### PR TITLE
Synchronize system dependencies used by Linux and Mac VTK packages

### PR DESCRIPTION
**Pull request by jamiesnape**
This makes life a little less complicated and reduces the chances of conflicts between vendored and system versions of various libraries that VTK uses. Note that unfortunately there is an issue with the system version of `liblz4` on Trusty, so on that platform `vtklz4` is still used.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6903)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by soonho-tri** [comment]
Passed tests:
```bash
bazel test //drake/systems/sensors:rgbd_camera_test
bazel run //tools:drake_visualizer
bazel run install -- ~/tmp/drake && ~/tmp/drake/bin/drake-visualizer
```

---

Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsJha1M5i1FoDqC0hl_:btabrtz)*

**Comment by jadecastro** [comment]
I did 
```
bazel run //drake/systems/sensors:rgbd_camera_test
bazel run //tools:drake_visualizer
```
and neither one of those works for me (in Trusty).  

In `rgbd_camera_test` I'm seeing a segfault at line 412 in `rgbd_camera.cc`, when it does something with the vtk pointer array:
https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/rgbd_camera.cc#L406

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsJhjdlzdc1shd9qy2z:b-mpgb0h)*

**Comment by jamiesnape** [comment]
Could you run that test on `master` too and let me know if you get the same result? It does not run on CI.

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsJnKicqzNymOv13hDl:b-igsodv)*

**Comment by jadecastro** [comment]
Just tried that - I was able to run both on current `master` (`rgbd_camera_test` passed and D-V launched).

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsJnUAf53IIWNNhINhf:b-zdqyyx)*

**Comment by soonho-tri** [comment]
:lgtm: (I haven't checked the new lists in Ubuntu scripts.)

---

Reviewed 2 of 8 files at r1, 2 of 2 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/vtk.bzl, line 369 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-KsJza9KEqGDfjeXSNqt:-KsJza9KEqGDfjeXSNqu:b-lx0lj7) ([raw file](https://github.com/robotlocomotion/drake/blob/5a026c7ff11c9d1a4a2d9c35e428d9cace32954a/tools/vtk.bzl#L369)):*
> ```Python
> 
>     if repository_ctx.os.name == "linux" and distro == "Ubuntu 14.04":
>         VTKLZ4 = "vtklz4"
> ```

BTW, nit, can it be `":vtklz4"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsJzuBP5Owjbs_1ZZIh:b70ljv9)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vtk.bzl, line 369 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-KsJza9KEqGDfjeXSNqt:-KsK4sOYmmVLBxeuYIq9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5a026c7ff11c9d1a4a2d9c35e428d9cace32954a/tools/vtk.bzl#L369)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, can it be `":vtklz4"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by jamiesnape** [comment]
@jadecastro Did you run the `./setup/ubuntu/14.04/install_prereqs.sh` script updated in this PR before you ran `drake_visualizer` and `rgbd_camera_test`?

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsKnp8Bu7xaCFYmeZca:b-o54qtn)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@jadecastro I can't reproduce the segfault on a Trusty box locally. Can you try rerunning the setup script in this PR and then run the two targets again?

**Comment by jadecastro** [comment]
Sorry for the delay (away from my trusty machine the past few days).  

I tried the 14.04 script and verified manually that I have all of the newly-updated prereqs installed.  Unfortunately, I still can't seem to run these scripts without them segfaulting. 

---

Reviewed 1 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsdG9K8mU_Y7BRES9K8:b-otqcse)*

**Comment by jamiesnape** [comment]
Do you (or @soonho-tri) have access to a Xenial machine on which you could also test?

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsdJBUfMP-4euK6RTws:bwnheyp)*

**Comment by soonho-tri** [comment]
I only have a Trusty box.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsdL9f9lBapHYii3Gtu:b-e2zegt)*

**Comment by jadecastro** [comment]
Ditto here as well.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KsdMgKMItO2Cvq-r0Lo:b-xz7um1)*

**Comment by jamiesnape** [comment]
@jadecastro please try testing again on Trusty with the latest version.

**Comment by jadecastro** [comment]
Interesting. 
1)`drake_visualizer` works fine. 
2) `rgbd_camera_test` no longer segfaults, but some of its tests are failing for other reasons. 

```
[==========] 13 tests from 3 test cases ran. (3843 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] ImageTest.TerrainRenderingTest
[  FAILED  ] ImageTest.BoxRenderingTest
[  FAILED  ] ImageTest.CylinderRenderingTest
[  FAILED  ] ImageTest.SphereRenderingTest
[  FAILED  ] ImageTest.CameraPoseUpdateTest
[  FAILED  ] ImageTest.LabelRenderingTest
[  FAILED  ] ImageTest.MultipleVisualsTest

```

I'm getting errors like:
```
ERROR: In /vtk/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 820
vtkXOpenGLRenderWindow (0x55afce725650): failed to create offscreen window
```

I can forward you a more complete screen dump of errors if needed. 

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtI-rxSvBtkGmNp_ttf:bkf274a)*

**Comment by jamiesnape** [comment]
Could you try installing `libgl1-mesa-glx-lts-xenial` from `trusty-updates`?

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtI4KS8UG3aJkuuxUhk:bfkxyqw)*

**Comment by jamiesnape** [comment]
Also, do you have the `mesa-utils` package installed?

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtI6PkxjzvFnDyLqhTk:b-t4912g)*

**Comment by jadecastro** [comment]
Installing `libgl1-mesa-glx-lts-xenial` seemed to do the trick. I can run both targets on my machine just fine.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtICt0v19kRu3owJa85:buakdaq)*

**Comment by soonho-tri** [comment]
Let me re-test this on my mac.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtIE0Wqlt75OYGXZXKF:b-xlboqm)*

**Comment by soonho-tri** [comment]
`bazel run //tools:drake_visualizer` gives me:

```
  File "/usr/local/opt/vtk@8.0/lib/python2.7/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ImportError: No module named vtkIOParallelPython
```

I've re-installed `vtk@8.0` but no luck so far.

---

Reviewed 2 of 4 files at r5.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtIKn7-HeavKE8GnOC8:biz77os)*

**Comment by jadecastro** [comment]
@soonho-tri I was getting that error on Mac OS even on current `master`. Could you verify that?

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtIL6oJVGWuEvkE84Vl:b-beky6p)*

**Comment by EricCousineau-TRI** [comment]
Running `bazel run //tools:drake_visualizer` worked fine and dandy on my system, and `bazel run //drake/systems/sensors:rgbd_camera_test` works; however, `bazel test //drake/systems/sensors:rgbd_camera_test` appears to be failing.

I have posted the log here:
https://gist.github.com/EricCousineau-TRI/a72c5d09a2c905e3a3d8cd6acd8967be

Actually, I just tested this on a branch off of an older version of `master`, and `bazel test` fails there too...
AFAI can remember, this used to work under both `bazel run` and `bazel test`...

Any clues as to what may be going wrong?

**Comment by soonho-tri** [comment]
@jadecastro : Yes, I can reproduce the problem on the current `master`.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtIMC7Yx9156U8TOKoq:biv5u7b)*

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Do you have `mesa-utils` installed?

**Comment by jamiesnape** [comment]
@soonho-tri Do you have a file `/usr/local/opt/vtk@8.0/lib/python2.7/site-packages/vtk/vtkIOParallelPython.so`?

**Comment by soonho-tri** [comment]
> Do you have a file /usr/local/opt/vtk@8.0/lib/python2.7/site-packages/vtk/vtkIOParallelPython.so?

Yes.

**Comment by EricCousineau-TRI** [comment]
> Do you have mesa-utils installed?

Yup:

```
$ dpkg -s mesa-utils 
Package: mesa-utils
Status: install ok installed
Priority: optional
Section: x11
Installed-Size: 115
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: mesa-demos
Version: 8.3.0-1
Depends: libc6 (>= 2.14), libgl1-mesa-glx | libgl1, libx11-6
Description: Miscellaneous Mesa GL utilities
 This package provides several basic GL utilities built by Mesa, including
 glxinfo and glxgears.
Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Homepage: http://mesa3d.org/
```

**Comment by jamiesnape** [comment]
I just updated all the packages. I tested the following locally on Mac, Ubuntu 14.04 and Ubuntu 16.04:
```
bazel run //tools:drake_visualizer
bazel run //drake/systems/sensors:rgbd_camera_test
bazel test //drake/systems/sensors:rgbd_camera_test
```
All ran/passed. Could everyone retest on whatever platforms you have available?

**Comment by soonho-tri** [comment]
`rgbd_camera_test` works but not `bazel run //tools:drake_visualizer` on my mac. I have:
```
  File "/usr/local/opt/vtk@8.0/lib/python2.7/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ImportError: No module named vtkIOParallelPython
```
FYI, I uninstall and reinstall `vtk@8.0` formula (made sure that cache was removed).

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtOWca-puO-sojqxeEV:bld10cx)*

**Comment by jamiesnape** [comment]
@soonho-tri Did you also grab the change the `tools/drake_visualizer_apple.sh` in this PR?

**Comment by soonho-tri** [comment]
@jamiesnape , I did. 

I just ran the same test, `bazel run //tools:drake_visualizer` on iMac and MacPro. It failed on both machines with the `No module named vtkIOParallelPython` message.

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtRZYbnZiXlIb04uhiQ:b3n05rt)*

**Comment by jamiesnape** [comment]
Can you print the `PYTHONPATH` and post it here?

**Comment by soonho-tri** [comment]
It has nothing on my machines:
```bash
$ echo $PYTHONPATH

```

**Comment by soonho-tri** [comment]
I manually set it to have `drake/bindings/python:drake/lcmtypes:external/drake_visualizer/lib/python2.7/dist-packages:external/lcmtypes_bot2_core/lcmtypes:external/lcmtypes_robotlocomotion/lcmtypes:/usr/local/opt/vtk@8.0/lib/python2.7/site-packages:external` and ran `./bazel-bin/tools/drake_visualizer`. But it made no difference.

**Comment by jamiesnape** [comment]
I just pushed new VTK bottles. Try updating to those.

**Comment by soonho-tri** [comment]
I have:
```
==> Downloading https://donn8mmazi9jw.cloudfront.net/bottles/vtk@8.0-8.0.1.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "vtk@8.0"
Download failed: https://donn8mmazi9jw.cloudfront.net/bottles/vtk@8.0-8.0.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```
Should I try it after 5-10 minutes?

**Comment by jamiesnape** [comment]
Try again now.

**Comment by soonho-tri** [comment]
It works.

**Comment by jamiesnape** [comment]
> It works.
drake_visualizer?

**Comment by jamiesnape** [comment]
@EricCousineau-TRI @jadecastro Please test when you have a spare moment. This is fairly high priority as it has a fix for an issue in Spartan, that is blocking the CMake to Bazel switch.

**Comment by soonho-tri** [comment]
> drake_visualizer?

```
bazel run //tools:drake_visualizer
bazel run //drake/systems/sensors:rgbd_camera_test
bazel test //drake/systems/sensors:rgbd_camera_test
```

All ran/passed on my macs.

**Comment by jamiesnape** [comment]
Cool. Can you remove the `/usr/local/opt/vtk@8.0/lib/python2.7` from `drake_visualizer_apple.sh` and tell me if drake_visualizer still works?

**Comment by EricCousineau-TRI** [comment]
Hmm... I am still getting the same failures with:
```
bazel test //drake/systems/sensors:rgbd_camera_test
```

I had run `install_prereqs.sh` again on my machine and restarted. Here's my git info:
```
$ git log -n 1
commit 3cd7a135975aba742f8ca315673a1c41e339d731
Author: Jamie Snape <jamie.snape@kitware.com>
Date:   Wed Sep 6 16:39:49 2017 -0400

    Synchronize system dependencies using by Linux and Mac VTK packages
$ git status
On branch vtk-system-dependencies
Your branch is up-to-date with 'jamiesnape/vtk-system-dependencies'.
nothing to commit, working directory clean
```

**Comment by soonho-tri** [comment]
@jamiesnape , yes.

It still works without `/usr/local/opt/vtk@8.0/lib/python2.7/site-packages` in `drake_visualizer_apple.sh`.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI And the version in the current master works for you?

**Comment by jadecastro** [comment]
The current setup works for me, though I admit I can't tell if this is in part/whole due to my earlier `apt-get` surgery. 

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtRtpKr1gnQStl_CZ-k:b-8c9oie)*

**Comment by EricCousineau-TRI** [comment]
I get the same failure on `master` as well, so perhaps this is only pertinent to my setup?
(My laptop also fails, but perhaps it is not an issue?)

My OS / WM info:
```
$ lsb_release -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
$ printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: GNOME
Session: gnome
```

**Comment by jamiesnape** [comment]
@jadecastro @EricCousineau-TRI Question to both of you: What graphics card do you have or are you using a VM?

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Are you using the NVIDIA drivers?

**Comment by EricCousineau-TRI** [comment]
> What graphics card do you have or are you using a VM?

I'm running directly on my PC, without a VM.

My graphics card is a TITAN X (Pascal)/PCIe/SSE2.
My display devices are DELL P2715Q (DFP-6) and DELL U3417W (DFP-4).

> Are you using the NVIDIA drivers?

Yes. Using 375.66, from `nvidia-375`.

**Comment by EricCousineau-TRI** [comment]
Ran it on another person's machine with Ubuntu 16.04.3 TLS and a GeForce GTX 1080, and had no issues.

Looks like it's just a problem on my end, that I've duplicated between my desktop and laptop - I'd say this shouldn't be a blocker for this PR unless someone else runs into this issue.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI @soonho-tri @jadecastro Is everyone happy to move onto platform review?

**Comment by soonho-tri** [comment]
:+1: 

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtS4Mrfh3j5I0A-kUaH:b-8fx2u7)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtS5EFdSjY6GFb1WMgW:bnfp4nl)*

**Comment by soonho-tri** [comment]
platform :lgtm: 

---

Reviewed 2 of 4 files at r5, 2 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtS6HJKvG064p71Y7bK:bzus18)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 39 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-KtS6VQBbtRruJ2XcKIL:-KtS6VQBbtRruJ2XcKIM:bqpi7cx) ([raw file](https://github.com/robotlocomotion/drake/blob/c721864fb5453fd16982d581781b2cc2895f484f/tools/drake_visualizer.bzl#L39)):*
> ```Python
> def _impl(repository_ctx):
>     if repository_ctx.os.name == "mac os x":
>         archive = "dv-0.1.0-173-g6e492205-qt-5.9.1-vtk-8.0.1-mac.tar.gz"
> ```

BTW, this filename does not match the above pattern anymore (`<platform>` is missing).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by jamiesnape** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 39 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-KtS6VQBbtRruJ2XcKIL:-KtS9kJidY5kVjwTiCjw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c721864fb5453fd16982d581781b2cc2895f484f/tools/drake_visualizer.bzl#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this filename does not match the above pattern anymore (`<platform>` is missing).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903)*

**Comment by jadecastro** [comment]
@jamiesnape I'm using nvidia-375 for my graphics as well. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtSAzL-VtcHj7xuaAgU:b-b4f384)*

**Comment by jadecastro** [comment]
:lgtm: from my vantage point.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6903#-:-KtSBCX85YkfRxvPmbAz:b-zg896r)*

**Comment by sankhesh** [comment]
@EricCousineau-TRI Do any other OpenGL applications work on the problematic machine? What is the output of `nvidia-smi`?

**Comment by EricCousineau-TRI** [comment]
Yes, the applications work well when run under `bazel run`, but they don't work under `bazel test`.

To check, I injected a call to `system("nvidia-smi");` in `rgbd_camera_test`, and got these outputs:
https://gist.github.com/EricCousineau-TRI/dff5ffd8fea31f344e3735729c31cd61

Perhaps it has something to do with some sort of process-monitoring restrictions on Bazel's side?

(Right now, `/proc/sys/kernel/yama/ptrace_scope` is still enabled.)

**Comment by jamiesnape** [comment]
Looks like TensorFlow just switch off the sandbox. Try `--spawn_strategy=standalone`.

**Comment by EricCousineau-TRI** [comment]
Yup, that worked!

It's still not clear what part of the sandboxing prevents OpenGL from running on my system, but can still run on other systems, but I will use that as a workaround for the time being.

Thanks!

**Comment by jamiesnape** [comment]
> a workaround for the time being.

It will probably be a permanent thing unless Bazel changes. You can add it to `~/.bazelrc` on those machines.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Could you add a short note to https://github.com/RobotLocomotion/drake/blob/master/drake/doc/faq.rst about the workaround? My guess is it is only going to be an issue for people using drivers provided by their graphics card vendor.

**Comment by jwnimmer-tri** [comment]
Does `local = 1` on the test resolve the difficulty?  That would probably be better than globally switching to standalone.

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri Yup, adding `local = 1` or `tags = [.., "local"],` causes it to pass.

@jamiesnape Given this, I will submit a PR (1) adding `local` to any VTK-based tests, and (2) will include this error in the FAQ, listing `local` as the main solution, but adding the `spawn_strategy=standalone` option as a last-ditch effort.

**Pull request merged**
