### PR TITLE
call_python_client: Use newer matplotlib API for 3d plotting

### LINKED ISSUE #17936: Errors with matplotib 3.6.0
### What happened?

On Mac unprovisioned builds, matplotlib was updated from 3.5.3 to 3.6.0 last night. This caused the `//common/proto:call_python_test` to fail:

```
Plotting a simple 3D surface
Traceback (most recent call last):
  File "/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-release/_bazel_bigsur/bec0ae6dc20cf0d6dbe6178cb16ef78f/sandbox/darwin-sandbox/4191/execroot/drake/bazel-out/darwin-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 371, in _execute_message
    self._execute_message_impl(msg)
  File "/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-release/_bazel_bigsur/bec0ae6dc20cf0d6dbe6178cb16ef78f/sandbox/darwin-sandbox/4191/execroot/drake/bazel-out/darwin-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 426, in _execute_message_impl
    out = eval(function_name + "(*_tmp_args, **_tmp_kwargs)",
  File "<string>", line 1, in <module>
  File "/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-release/_bazel_bigsur/bec0ae6dc20cf0d6dbe6178cb16ef78f/sandbox/darwin-sandbox/4191/execroot/drake/bazel-out/darwin-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/call_python_client.py", line 258, in surf
    ax = fig.gca(projection='3d')
TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'
  Continuing (no --stop_on_error)

....
======================================================================
FAIL [8.892s]: test_basic (call_python_test.TestCallPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-release/_bazel_bigsur/bec0ae6dc20cf0d6dbe6178cb16ef78f/sandbox/darwin-sandbox/4191/execroot/drake/bazel-out/darwin-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/test/call_python_test.py", line 113, in test_basic
    self.run_server_and_client(with_error)
  File "/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-release/_bazel_bigsur/bec0ae6dc20cf0d6dbe6178cb16ef78f/sandbox/darwin-sandbox/4191/execroot/drake/bazel-out/darwin-opt/bin/common/proto/call_python_test.runfiles/drake/common/proto/test/call_python_test.py", line 100, in run_server_and_client
    self.assertEqual(client_status, int(with_error))
AssertionError: 1 != 0
```

See slack thread [here](https://drakedevelopers.slack.com/archives/C270MN28G/p1663335286351369)

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per https://github.com/matplotlib/matplotlib/issues/20770#issuecomment-890494483

Resolves #17936

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@betsymcphail for feature and +@seancurtis-tri for platform, please!
\cc @DamrongGuoy 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938#-:-NC5wqkv3gtAWGyUNba-:b-x33z8)* status: LGTM missing from assignees BetsyMcPhail,SeanCurtis-TRI(platform), missing label for release notes (waiting on @BetsyMcPhail and @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17938#-NC5yC0IDyGiTJpTRN9t:-NC5yC0IDyGiTJpTRN9u:b-bkp0x3) (no related file):*
Working: Pending pass of Mac unprovisioned.

___

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: (pending CI)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938#-:-NC5yZ1KEWH97NRlIUnZ:b-lj32db)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: Pending CI.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938#-:-NC5yAnH5OdGAKLL8zxR:b7d95zk)* status: 2 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`common/proto/call_python_client.py` line 227 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17938#-NC5yQDUD6kaaq9D_ddC:-NC5yQDUD6kaaq9D_ddD:b171b5h) ([raw file](https://github.com/robotlocomotion/drake/blob/0dfa849779c108a3b10ff35b5d2b2cde774dc0db/common/proto/call_python_client.py#L227)):*
> ```Python
>     def box(bmin, bmax, rstride=1, cstride=1, **kwargs):
>         """Plots a box bmin[i] <= x[i] <= bmax[i] for i < 3."""
>         fig = plt.gcf()
> ```

nit: The definitions of `fig` are no longer used. `plt.subplot()` implicitly operates on currrent figure. (Applies to all four leftovers here.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
(I hope that quick push didn't mess up the mac test....).

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938#-:-NC5znhFD4C8kxZoB02V:b-3nnn58)* status: 2 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`common/proto/call_python_client.py` line 227 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17938#-NC5yQDUD6kaaq9D_ddC:-NC5zS_YEDU8fXFrodiw:b-us73n4) ([raw file](https://github.com/robotlocomotion/drake/blob/0dfa849779c108a3b10ff35b5d2b2cde774dc0db/common/proto/call_python_client.py#L227)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The definitions of `fig` are no longer used. `plt.subplot()` implicitly operates on currrent figure. (Applies to all four leftovers here.)
</blockquote></details>

Done. good catch!

**Comment by EricCousineau-TRI** [comment]
Ah, it probably did. However, r1 to r2 are functionally equivalent, so I say should be OK?
I posted URL to the testing in comment above; it is still running.
https://drake-jenkins.csail.mit.edu/job/mac-m1-monterey-unprovisioned-clang-bazel-experimental-release/23/

**Review by BetsyMcPhail — COMMENTED** [review]
If the original mac job succeeds I think we can call that good.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938#-:-NC69oOI8OHol0qSAB-c:b-ezv4fe)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17938)* status: missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17938#-NC5yC0IDyGiTJpTRN9t:-NC6kCmY4fSQaBS58qSD:b-dtkds3) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

It passed now.
</blockquote></details>

Done, thanks!

___

**Comment by EricCousineau-TRI** [comment]
Per #17672, setting `release notes: none`

**Pull request merged**
