### PR TITLE
[workspace] Update macOS to python@3.11

### PR DESCRIPTION
**Pull request by svenevs**
- [X] Waiting on: https://github.com/Homebrew/homebrew-core/pull/114154
- [X] Rebase after #18381 merges.
- [X] https://github.com/RobotLocomotion/pybind11/pull/60
- [X] #18297 and rebase this PR

Relates: #18252 

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.
@drake-jenkins-bot mac-x86-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

___
*[`tools/workspace/python/repository.bzl` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-L71oAWQn94fvpU01:-NG-L71oAWQn94fvpU02:by3qx4e) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L57)):*
> ```Starlark
>     # - Update URLs on doc/_pages/pip.md (`cpXY-cpXY` components), and
>     # - Tables on from_source.md and installation.md (python version number).
>     "macos_wheel": ["3.11"],
> ```

Working, local wheel build failure

```
ERROR: /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/external/lcm/BUILD.bazel:175:10: Compiling lcm-python/module.c failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 50 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/lcm/lcm-python/module.c:46:34: error: expression is not assignable
    Py_TYPE(&pylcmeventlog_type) = &PyType_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
external/lcm/lcm-python/module.c:47:26: error: expression is not assignable
    Py_TYPE(&pylcm_type) = &PyType_Type;
    ~~~~~~~~~~~~~~~~~~~~ ^
external/lcm/lcm-python/module.c:48:39: error: expression is not assignable
    Py_TYPE(&pylcm_subscription_type) = &PyType_Type;
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/python/repository.bzl` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-VsvLDvfkJUMmUrus:-NG-VsvLDvfkJUMmUrut:b7oxzve) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L58)):*
> ```Starlark
>     # - Tables on from_source.md and installation.md (python version number).
>     "macos_wheel": ["3.11"],
>     "manylinux": ["3.8", "3.9", "3.10"],
> ```

Working, failure that hit drake external examples too

```
[10:21:57 PM]  external/pybind11/include/pybind11/detail/type_caster_base.h:540:26: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
[10:21:57 PM]              frame = frame->f_back;
[10:21:57 PM]                           ^
[10:21:57 PM]  external/python/include/_opt_homebrew_opt_python@3.11_Frameworks_Python.framework_Versions_3.11_include_python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
[10:21:57 PM]  typedef struct _frame PyFrameObject;
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

___
*[`tools/workspace/python/repository.bzl` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-L71oAWQn94fvpU01:-NG21thG-eVoersx6VHq:b8yy8p3) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L57)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, local wheel build failure

```
ERROR: /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/external/lcm/BUILD.bazel:175:10: Compiling lcm-python/module.c failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 50 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/lcm/lcm-python/module.c:46:34: error: expression is not assignable
    Py_TYPE(&pylcmeventlog_type) = &PyType_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
external/lcm/lcm-python/module.c:47:26: error: expression is not assignable
    Py_TYPE(&pylcm_type) = &PyType_Type;
    ~~~~~~~~~~~~~~~~~~~~ ^
external/lcm/lcm-python/module.c:48:39: error: expression is not assignable
    Py_TYPE(&pylcm_subscription_type) = &PyType_Type;
```
</blockquote></details>

FYI See https://docs.python.org/3/whatsnew/3.11.html near `Py_SET_TYPE()` for a compatibility macro we'll need to use for LCM.

For expediency, we could do it as a `drake/tools/workspace/lcm/patches/...` file and submit it upstream later.
___
*[`tools/workspace/python/repository.bzl` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-VsvLDvfkJUMmUrus:-NG21L6T4TZ3fzrqTWAQ:b190t92) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L58)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, failure that hit drake external examples too

```
[10:21:57 PM]  external/pybind11/include/pybind11/detail/type_caster_base.h:540:26: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
[10:21:57 PM]              frame = frame->f_back;
[10:21:57 PM]                           ^
[10:21:57 PM]  external/python/include/_opt_homebrew_opt_python@3.11_Frameworks_Python.framework_Versions_3.11_include_python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
[10:21:57 PM]  typedef struct _frame PyFrameObject;
```
</blockquote></details>

FYI This one like a missing `#include`; hopefully will be easy to fix.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @svenevs)

___
*[`tools/workspace/python/repository.bzl` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-L71oAWQn94fvpU01:-NG343VKEYrYK8fNtEWv:b-oigbrb) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI See https://docs.python.org/3/whatsnew/3.11.html near `Py_SET_TYPE()` for a compatibility macro we'll need to use for LCM.

For expediency, we could do it as a `drake/tools/workspace/lcm/patches/...` file and submit it upstream later.
</blockquote></details>

I included a patch, upstreaming it is a little less clear (does lcm-python support python 2?)
___
*[`tools/workspace/python/repository.bzl` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-VsvLDvfkJUMmUrus:-NG34Aa329zgdtpjAzIt:b5462d0) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This one like a missing `#include`; hopefully will be easy to fix.
</blockquote></details>

https://github.com/RobotLocomotion/pybind11/pull/60

Pushed a commit with a test in that.  I'm getting a really bizarre issue, I think I'm missing one update somewhere.  All of drake builds but then in the final wheel stage locally (without python 3.9 installed) it's trying to create python 3.9 names.

```
Successfully installed delocate-0.10.3 packaging-21.3 pyparsing-3.0.9 setuptools-65.5.0 typing-extensions-4.4.0 wheel-0.38.1
WARNING: You are using pip version 21.2.4; however, version 22.3 is available.
You should consider upgrading via the '/opt/drake-wheel-build/python/bin/python3 -m pip install --upgrade pip' command.
Using packages=['pydrake', 'drake', 'pydrake.manipulation', 'pydrake.multibody', 'pydrake.common', 'pydrake.systems', 'pydrake.examples', 'pydrake.solvers', 'pydrake.visualization']
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.9-universal2-cpython-39
creating build/lib.macosx-10.9-universal2-cpython-39/pydrake
```

Perhaps CI will result in something different.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-snopt-mosek-packaging please.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by svenevs — COMMENTED** [review]
OK macOS wheel build issues resolved, linux still works as expected.  Closer!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262#-:-NGILnOh0qa2s5Y3QDaK:bvqver2)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @svenevs)

___
*[`tools/workspace/python/repository.bzl` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-L71oAWQn94fvpU01:-NGILT56EsFyZq26A7tX:b4irx4g) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L57)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I included a patch, upstreaming it is a little less clear (does lcm-python support python 2?)
</blockquote></details>

LCM patch currently has no PR, AFAICT the patch here will break python 2 support and the status of the repo is unclear to me.
___
*[`tools/workspace/python/repository.bzl` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-VsvLDvfkJUMmUrus:-NGIL_Is4DtQDmjbXSVN:blpowas) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L58)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/pybind11/pull/60

Pushed a commit with a test in that.  I'm getting a really bizarre issue, I think I'm missing one update somewhere.  All of drake builds but then in the final wheel stage locally (without python 3.9 installed) it's trying to create python 3.9 names.

```
Successfully installed delocate-0.10.3 packaging-21.3 pyparsing-3.0.9 setuptools-65.5.0 typing-extensions-4.4.0 wheel-0.38.1
WARNING: You are using pip version 21.2.4; however, version 22.3 is available.
You should consider upgrading via the '/opt/drake-wheel-build/python/bin/python3 -m pip install --upgrade pip' command.
Using packages=['pydrake', 'drake', 'pydrake.manipulation', 'pydrake.multibody', 'pydrake.common', 'pydrake.systems', 'pydrake.examples', 'pydrake.solvers', 'pydrake.visualization']
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.9-universal2-cpython-39
creating build/lib.macosx-10.9-universal2-cpython-39/pydrake
```

Perhaps CI will result in something different.
</blockquote></details>

Working, the patch here works, we can proceed with merging https://github.com/RobotLocomotion/pybind11/pull/60 and then I can update the repo rules to use a different commit after it merges.  Not sure what's going on with the CI there.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/python/repository.bzl` line 58 at r5](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGO7xyhEglwfI7PQrfU:-NGO7xyhEglwfI7PQrfV:b2zoq4x) ([raw file](https://github.com/robotlocomotion/drake/blob/b818987dfd10758a0810f833a99a4a0f2721e7f8/tools/workspace/python/repository.bzl#L58)):*
> ```Starlark
>     #   under "Nightly Releases".
>     # - Wheel URLs in tools/release_engineering/download_release_candidate.py
>     #   (`cpXY-cpXY` components).
> ```

Working, I think #18148 is going to land first, this PR needs to update `tools/release_engineering/download_release_candidate.py` wheel urls.

**Comment by sherm1** [comment]
Is this ready to have a feature reviewer assigned?

**Comment by jwnimmer-tri** [comment]
From f2f:

- The LCM patchfile can land in Drake for now.
- This PR should point to the pybind11 PR temporary sha, to prove it works OK.
- We can and should land both the pybind11 PR and a Drake sha bump PR of pybind11, ahead of this 3.11 PR.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGXp4_67PxIQ3yrJ3BL:-NGO7ovODqC0tVRa1IQo:b8pq9dr) (no related file):*
Working, found something in `CMakeLists.txt` that needs to update with this PR and python versions

___

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by svenevs — COMMENTED** [review]
OK we're ready to pull the trigger on this whenever we need to minus one caveat of the catch-22 of YYYYMMDD urls on `pip.md` and when those URLs should be updated (part of or as a followup to this PRI).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262#-:-NGbLzlOAQS8xshmwnoX:byt5w79)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGXp4_67PxIQ3yrJ3BL:-NGbK4WR7fCJant8EURv:b-oviteu) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, found something in `CMakeLists.txt` that needs to update with this PR and python versions
</blockquote></details>

Done, also added note in `python/repository.bzl` to point to updating that file (current `CMakeLists.txt` comments point to that file but not the reverse).

___
___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NGbLIk_9qQjBtuEwisD:b-rsmnxe) ([raw file](https://github.com/robotlocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
> ```Markdown
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp310-cp310-manylinux_2_31_x86_64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp310-cp310-manylinux_2_31_x86_64.whl)
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp311-cp311-macosx_12_0_x86_64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp311-cp311-macosx_12_0_x86_64.whl)
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp311-cp311-macosx_12_0_arm64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20221110-cp311-cp311-macosx_12_0_arm64.whl)
> ```

Working, this is the last snag on this PR.  These artifacts will not exist until this code is merged and run in nightlies.  I see two options:

1. Don't have this PR update this, do it in a followup day after it merges.
2. When we are ready to land this, I update the YYYYMMDD numbers here to be the day after we are merging (e.g., if merging today, 20221112).  Check back on them the following morning and confirm all the artifacts were built.
___
*[`tools/workspace/python/repository.bzl` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-L71oAWQn94fvpU01:-NGbL3kGBgbJJ1mHlUYl:b23snrm) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L57)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

LCM patch currently has no PR, AFAICT the patch here will break python 2 support and the status of the repo is unclear to me.
</blockquote></details>

Done, LCM patch is getting added to drake for now.
___
*[`tools/workspace/python/repository.bzl` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NG-VsvLDvfkJUMmUrus:-NGbL72l0BzClf33hBi_:b-i8opps) ([raw file](https://github.com/robotlocomotion/drake/blob/1a68b399701f0a23935307eb2187bafe08ed3ddb/tools/workspace/python/repository.bzl#L58)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, the patch here works, we can proceed with merging https://github.com/RobotLocomotion/pybind11/pull/60 and then I can update the repo rules to use a different commit after it merges.  Not sure what's going on with the CI there.
</blockquote></details>

Done, rebased and rerunning CI.
___
*[`tools/workspace/python/repository.bzl` line 58 at r5](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGO7xyhEglwfI7PQrfU:-NGbL1bu0Y5vF_OOUSxx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b818987dfd10758a0810f833a99a4a0f2721e7f8/tools/workspace/python/repository.bzl#L58)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, I think #18148 is going to land first, this PR needs to update `tools/release_engineering/download_release_candidate.py` wheel urls.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 2 of 3 files at r2, 3 of 3 files at r4, 1 of 2 files at r6, 6 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NGrTZ0s0ESv9ibCwnVY:ba9kih7) ([raw file](https://github.com/robotlocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, this is the last snag on this PR.  These artifacts will not exist until this code is merged and run in nightlies.  I see two options:

1. Don't have this PR update this, do it in a followup day after it merges.
2. When we are ready to land this, I update the YYYYMMDD numbers here to be the day after we are merging (e.g., if merging today, 20221112).  Check back on them the following morning and confirm all the artifacts were built.
</blockquote></details>

To me, (2) sounds simplest.  It seems like it would be easy to do concurrently with giving final LGTM emoji on this PR.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NGrev18BgwHAYA3bH5g:b-8mtgda) ([raw file](https://github.com/robotlocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To me, (2) sounds simplest.  It seems like it would be easy to do concurrently with giving final LGTM emoji on this PR.
</blockquote></details>

Works for me, FYI I may not have access to a computer next week in which case you should be able to push to the branch / finalize directly.

**Comment by bjacklyn** [comment]
Is this PR blocking creating 3.11 pip packages for linux, or could some subset of it merge now (the lcm patch?) + another PR that adds 3.11 packages for linux?

**Comment by svenevs** [comment]
@bjacklyn this is unrelated to linux, I've opened #18417 to track it.

**Comment by jwnimmer-tri** [comment]
This is ready for a rebase.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

Retesting now that https://github.com/RobotLocomotion/drake-ci/pull/197 has landed.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by svenevs — COMMENTED** [review]
-(status: do not merge) 

> Reviewed 1 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-:-NOCkCSw0Fs5y1Kury6k:b-b9fcpn)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NOClP2g1Di7NW8L55DY:b-hwel2e) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Works for me, FYI I may not have access to a computer next week in which case you should be able to push to the branch / finalize directly.
</blockquote></details>

Done, https://github.com/Homebrew/homebrew-core/pull/114154 has now landed so we should be ready to switchover here.  I have the date set for 2023-02-15 AKA if this merges tomorrow (2023-02-14) then nightly will produce the desired artifacts here.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18262)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NOCmfgR6fIVEf2dijVJ:b-2gdyvh) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, https://github.com/Homebrew/homebrew-core/pull/114154 has now landed so we should be ready to switchover here.  I have the date set for 2023-02-15 AKA if this merges tomorrow (2023-02-14) then nightly will produce the desired artifacts here.
</blockquote></details>

Or does drake desire to wait until https://github.com/Homebrew/homebrew-core/pull/123165 lands?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-:-NOCtlg54jvSBsxaIx03:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @svenevs)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NOCtRFY9na9PwYZtvLY:b5oirm3) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Or does drake desire to wait until https://github.com/Homebrew/homebrew-core/pull/123165 lands?
</blockquote></details>

I can't tell exactly what that last PR changes.

The invariant we want for Drake is that when a user runs `python3` on mac (i.e., `/usr/local/bin/python3`), the python version it runs is the python version we support.

**Review by svenevs — COMMENTED** [review]
+@rpoyner-tri for platform review please :slightly_smiling_face:

> Reviewed 3 of 9 files at r1, 1 of 3 files at r4, 1 of 2 files at r6, 2 of 6 files at r7, 4 of 6 files at r9, 4 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18262#-:-NOFcS9DBWtSV4HwCzdq:bqrafgz)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`doc/_pages/pip.md` line 120 at r7](https://reviewable.io/reviews/robotlocomotion/drake/18262#-NGbLIk_9qQjBtuEwisC:-NOFc0W67-nSuF7w8kIn:bpp6bgo) ([raw file](https://github.com/robotlocomotion/drake/blob/e1255b5c69b66484d80fed76485886073c8c34f8/doc/_pages/pip.md#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can't tell exactly what that last PR changes.

The invariant we want for Drake is that when a user runs `python3` on mac (i.e., `/usr/local/bin/python3`), the python version it runs is the python version we support.
</blockquote></details>

OK, those aliases were updated in the original PR we were tracking which has now merged so we're good to go.  I also don't understand what the last PR is doing, but brew has switched over now.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 3 files at r4, 1 of 2 files at r6, 2 of 6 files at r7, 4 of 6 files at r9, 4 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18262)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @svenevs)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18262#-:-NOFfcf69v48ekBaVzag:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @svenevs)

**Pull request merged**
