### PR TITLE
rigid_body_plant: Add contact Python bindings.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7909)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-:-L479xaLvrLkxsLuZaJf:b-akgh2s)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a couple of minor cosmetic suggestions.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-L47GcLEzPH9Ry8jpKv8:-L47GcLEzPH9Ry8jpKv9:b-3df1si) ([raw file](https://github.com/robotlocomotion/drake/blob/c36f6b8b38b5d64786a8cda3ee40c70565126e5a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L130)):*
> ```Python
>         self.assertEquals(flat_values(material), expected_default)
>         # Test mutation by chaining.
>         expected = (1e7, 0.2, 0.4, 0.3)
> ```

BTW This test could be weakened if the default values were to change and overlap these values. I'd recommend doing what I did in the C++ test.  Make these expected values some function of the default values which guarantees they can never be the same.

---

*[multibody/rigid_body_plant/compliant_contact_model.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-L47H2PxxxD_2u0rVDo7:-L47H2PxxxD_2u0rVDo8:b1tjioa) ([raw file](https://github.com/robotlocomotion/drake/blob/c36f6b8b38b5d64786a8cda3ee40c70565126e5a/multibody/rigid_body_plant/compliant_contact_model.h#L15)):*
> ```objc
> /// See @ref drake_contacts for details.
> struct CompliantContactModelParameters {
>   // 1 cm/s (in m/s).
> ```

FYI I'd recommend removing the value from here and putting it at the definition -- as is, the two can end up disagreeing non-obviously. Leaving the units here, though, would be a good thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-:-L47HQ_Qg5gQPjPTU52S:b8prcya)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-L47GcLEzPH9Ry8jpKv8:-L47JfQtxjxhVGPnKwCg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c36f6b8b38b5d64786a8cda3ee40c70565126e5a/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L130)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This test could be weakened if the default values were to change and overlap these values. I'd recommend doing what I did in the C++ test.  Make these expected values some function of the default values which guarantees they can never be the same.
</blockquote></details>

Done.

---

*[multibody/rigid_body_plant/compliant_contact_model.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-L47H2PxxxD_2u0rVDo7:-L47Jg0GKOttbPVMU8UH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c36f6b8b38b5d64786a8cda3ee40c70565126e5a/multibody/rigid_body_plant/compliant_contact_model.h#L15)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'd recommend removing the value from here and putting it at the definition -- as is, the two can end up disagreeing non-obviously. Leaving the units here, though, would be a good thing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7909)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7909#-:-L47Nc3er8qHUASYincA:bnfp4nl)*

**Pull request merged**
