### PR TITLE
RgbdCamera: Change the way of implementing camera pose update

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Relates: #6399

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6432)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@seancurtis-tri feature review please. Thanks!

cc @sankhesh, @ericcousineau-tri 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-KnacLZC4E_F8GcAj6Tc:b-6hlt2z)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a couple of BTWs and pending passing CI, of course.  :)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 446 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-Kndx_6GDHO0d7xXwj5V:-Kndx_6HE2AiPMhrhSg-:btlll9p) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L446)):*
> ```cpp
>   camera->SetPosition(0., 0., 0.);
>   camera->SetFocalPoint(0., 0., 1.);  // Sets z-forward.
>   camera->SetViewUp(0., -1, 0.);  // Sets y-down.
> ```

BTW Y-down seems *quite* surprising. This probably deserves an comment.

---

*[drake/systems/sensors/rgbd_camera.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyWHIY-L1zCx88rG6:-KndyWHIY-L1zCx88rG7:bhz350x) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L702)):*
> ```cpp
>     }
> 
>     const auto X_WBody = tree_.CalcBodyPoseInWorldFrame(cache, *body);
> ```

BTW Given the use of the monogram notation elsewhere, `X_WBody` could just be `X_WB` and `X_WVisual` could be simply `X_WV`. If you're concerned about clarity, a comment would be sufficient.  (But, for example, you have `X_BC` and `X_WB_initial_` which already use this strict monogram convention.)

---

*[externals/bullet, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyP82w61_smDItJYc:-KndyP83XRbqWTkwOabX:b-lpww4q) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/externals/bullet#L1)):*
> ```
> Subproject commit ae2c4ca0618d55c6a29900aed75b958604149fdb
> ```

BTW I can't imagine you really intended this to be included in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-Kndz9SafhgdP6VG-lM1:b-ejzqct)*

**Comment by kunimatsu-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 446 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-Kndx_6GDHO0d7xXwj5V:-Kne-T12CcuLl9pQsZuK:b9e6oi9) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L446)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Y-down seems *quite* surprising. This probably deserves an comment.
</blockquote></details>

I will add the link to [camera_info.h](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/camera_info.h) then.

---

*[drake/systems/sensors/rgbd_camera.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyWHIY-L1zCx88rG6:-Kne-hh5kxKu1-YVtuOR:b4tc299) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L702)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given the use of the monogram notation elsewhere, `X_WBody` could just be `X_WB` and `X_WVisual` could be simply `X_WV`. If you're concerned about clarity, a comment would be sufficient.  (But, for example, you have `X_BC` and `X_WB_initial_` which already use this strict monogram convention.)
</blockquote></details>

There are two different `B`s, one is for the camera base and the other for object's body.  I wanna avoid unnecessary confusion. That's why I'm using `X_WBody` instead of `X_WB`.

Also, in the previous PR, sherm told me we don't need to stick to strict monogram convention. So, I'll leave `X_WBody` as it-is.

Will change `X_WVisual` to `X_WV` since there is no naming conflict for `V`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 446 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-Kndx_6GDHO0d7xXwj5V:-Kne1lQubRiaSaZGvrIJ:bvzl20i) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L446)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I will add the link to [camera_info.h](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/camera_info.h) then.
</blockquote></details>

Ah...so, you're simulating the fact that in image space, the origin is typically in the upper-left corner? (Which leads to lots of code that does things like: `height - y`?)

---

*[drake/systems/sensors/rgbd_camera.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyWHIY-L1zCx88rG6:-Kne12ychq6b6uZ2knHM:bfki918) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L702)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

There are two different `B`s, one is for the camera base and the other for object's body.  I wanna avoid unnecessary confusion. That's why I'm using `X_WBody` instead of `X_WB`.

Also, in the previous PR, sherm told me we don't need to stick to strict monogram convention. So, I'll leave `X_WBody` as it-is.

Will change `X_WVisual` to `X_WV` since there is no naming conflict for `V`.


</blockquote></details>

I guess that's fine.  In my mind, `X_WB` is position of a body in the world. In one case, it was the body the sensor is attached to, in another case it's a body with attached visual elements. The value it has at any time, depends on where in the code path you are. However, the sensor isn't attached to a "body", per se. You just have a `frame_`. So, I'll mark myself as happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/rgbd_camera.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyWHIY-L1zCx88rG6:-Kne3xVBLzy6Pxkvto5j:b-vh65jg) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L702)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I guess that's fine.  In my mind, `X_WB` is position of a body in the world. In one case, it was the body the sensor is attached to, in another case it's a body with attached visual elements. The value it has at any time, depends on where in the code path you are. However, the sensor isn't attached to a "body", per se. You just have a `frame_`. So, I'll mark myself as happy.
</blockquote></details>

Thanks for the comment.

FYI, what `B` means is written here:
https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/rgbd_camera.h#L31

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/rgbd_camera.cc, line 446 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-Kndx_6GDHO0d7xXwj5V:-Kne2_wF0X0fjg89eEiO:bkhoegm) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/drake/systems/sensors/rgbd_camera.cc#L446)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ah...so, you're simulating the fact that in image space, the origin is typically in the upper-left corner? (Which leads to lots of code that does things like: `height - y`?)
</blockquote></details>

That's correct, in pixel coordinate system, the origin is upper-left.

vtkImageExport handles which (lower-left or upper-left) should be the origin, and it automatically converts for image's origin to be upper-left by calling `ImageLowerLeftOff()` so that we don't need to manually handle things like `height - y`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by kunimatsu-tri** [comment]
*[externals/bullet, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-KndyP82w61_smDItJYc:-Kne7UMkHg7sQnN8RLCO:b-o5hfmz) ([raw file](https://github.com/robotlocomotion/drake/blob/fcd30b4235174dc07513e4f6ed13fdbb16f237d1/externals/bullet#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I can't imagine you really intended this to be included in this PR.
</blockquote></details>

Oops, thanks for catching this. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by SeanCurtis-TRI** [comment]
Great; thanks.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-Kne83U0c1o7CbJy4B6l:b-sthyw8)*

**Comment by kunimatsu-tri** [comment]
Thanks @SeanCurtis-TRI for feature review.

+@sammy-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-Kne7xXP6I7BoZbZ13iq:bhway53)*

**Comment by sankhesh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-KneGfV19cyIskWHUVFh:bnfp4nl)*

**Comment by sankhesh** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432)*

**Comment by kunimatsu-tri** [comment]
Thanks @sankhesh for looking at this.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-KnegfgDwgiDoV7ux9L5:brhbvws)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6432#-:-Knf0Pt_zudiZ4YMTatf:bnfp4nl)*

**Pull request merged**
