### PR TITLE
Add symbolic::Polynomial::Evaluate

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7785)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jadecastro for feature-review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-:-L34SNu6WeEqlqC65Ocw:b2q2fko)*

**Comment by jadecastro** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-:-L35N_B8HApbsGphWud3:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sherm1 , could you platform-review this PR? (I'm on call tomorrow).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-:-L367Q09UhgnMc-alj4i:bj4axtt)*

**Comment by sherm1** [comment]
Platform: :lgtm: with a few ignorable BTWs.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[common/symbolic_polynomial.cc, line 477 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36dmEBw9BRsaiBcFd9:-L36dmEBw9BRsaiBcFdA:b-1h7r3v) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/symbolic_polynomial.cc#L477)):*
> ```cpp
>         const Monomial& monomial_i{item.first};
>         const Expression& coeff_i{item.second};
>         return v + monomial_i.Evaluate(env) * coeff_i.Evaluate(env);
> ```

BTW not sure why the `_i`s in the names here. Could do without I think.

---

*[common/symbolic_polynomial.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36btNIAq9P-6E_-g69:-L36btNIAq9P-6E_-g6A:b-i2514l) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/symbolic_polynomial.h#L104)):*
> ```objc
>   /// Evaluates this polynomial under a given environment @p env.
>   ///
>   /// @throws std::out_of_range if there is a variable in this polynomial whose
> ```

BTW why `std::out_of_range`? Does seem like an `std::logic_error` but out_of_range seems odd. I assume this bubbles up from existing code -- if so you could just change the comment to "throws std::logic_error" which would still be accurate. 

---

*[common/test/symbolic_polynomial_test.cc, line 687 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36cufml2GuNwh4_Jg-:-L36cufml2GuNwh4_Jg0:b-98ysb) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/test/symbolic_polynomial_test.cc#L687)):*
> ```cpp
> 
> TEST_F(SymbolicPolynomialTest, Evaluate) {
>   // p = a*x²y + b*xy + cz
> ```

BTW the `*`s seem superfluous here.

---

*[common/test/symbolic_polynomial_test.cc, line 720 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36dCDyh_JR3DFf12kD:-L36dCDyh_JR3DFf12kE:bgl9u5f) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/test/symbolic_polynomial_test.cc#L720)):*
> ```cpp
>       {var_z_, -2.0},
>   }};
>   EXPECT_THROW(p.Evaluate(partial_env), std::out_of_range);
> ```

BTW allow any logic_error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-:-L36dzgADz4CSbbAd5Ns:bv3uema)*

**Comment by soonho-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[common/symbolic_polynomial.cc, line 477 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36dmEBw9BRsaiBcFd9:-L38uGeR0ngsbgw1jbRc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/symbolic_polynomial.cc#L477)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not sure why the `_i`s in the names here. Could do without I think.
</blockquote></details>

Done.

---

*[common/symbolic_polynomial.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36btNIAq9P-6E_-g69:-L38uV1xyuD-HSDEANEw:b-a10673) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/symbolic_polynomial.h#L104)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why `std::out_of_range`? Does seem like an `std::logic_error` but out_of_range seems odd. I assume this bubbles up from existing code -- if so you could just change the comment to "throws std::logic_error" which would still be accurate. 
</blockquote></details>

Done.

Good catch! I've changed `symbolic::Monomial::Evaluate` to throw `runtime_error` to be consistent with `symbolic::Expression::Evaluate`.

---

*[common/test/symbolic_polynomial_test.cc, line 687 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36cufml2GuNwh4_Jg-:-L38v00xGOigfUJ8I7sD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/test/symbolic_polynomial_test.cc#L687)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the `*`s seem superfluous here.
</blockquote></details>

Done.

---

*[common/test/symbolic_polynomial_test.cc, line 720 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36dCDyh_JR3DFf12kD:-L38uoL4Ir84gu2ITmRx:b4rct19) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/test/symbolic_polynomial_test.cc#L720)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW allow any logic_error?
</blockquote></details>

Done. (changed to `std::runtime_error`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785)*

**Comment by jadecastro** [comment]
Reviewed 1 of 4 files at r2.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785)*

**Comment by sherm1** [comment]
*[common/symbolic_polynomial.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7785#-L36btNIAq9P-6E_-g69:-L39TAQS4-paw7liShLS:b1cvsz8) ([raw file](https://github.com/robotlocomotion/drake/blob/6a01de16e890cc0cf3ac45cc6940211f132bc889/common/symbolic_polynomial.h#L104)):*
Not that we have been handling this consistently, but this really should be an `std::logic_error` since it represents a programmer's error. `std::runtime_error` is conventionally used for exceptions outside the programmer's control, such as a badly formed input file, or a remote connection going down. From the standard (via stackoverflow):
>The class logic_error defines the type of objects thrown as exceptions to report errors presumably detectable before the program executes, such as violations of logical preconditions or class invariants.

>The class runtime_error defines the type of objects thrown as exceptions to report errors presumably detectable only when the program executes.

We don't have a Drake styleguide requirement to follow the standard here, and it is not clear why the distinction matters. Still I like to follow this convention so I thought I would mention it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7785)*

**Comment by soonho-tri** [comment]
I see. I'll open another PR to change them soon.

**Pull request merged**
