### PR TITLE
[systems/lcm] Factor out magical lcm_buses lookup for reuse

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18069.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18090)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18090#-:-NECcjQm046oPRBQSUOL:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18090#-NECXQX72tO3GDWppa9h:-NECXQX8ClFEFStqpfxQ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ebdbcbd9515584618e733f419122a0f38d75a/systems/lcm/test/lcm_config_functions_test.cc#L74)):*
> ```cpp
> }
> 
> // When the forced_result pointer is directly provided, then thelcm_buses and
> ```

typo



_Suggestion:_
```cpp
the lcm_buses
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18090#-:-NECfGxK74tElDMUpsmM:bybe5xg)* status: LGTM missing from assignee sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18090)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18090#-:-NED-oRj8FL-0pU4-xpA:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
