### PR TITLE
Extend copyable_unique_ptr const correctness

### LINKED ISSUE #15344: Make `drake::copyable_unique_ptr` const-correct
Per a discussion on slack.  @jwnimmer-tri originally said "The `std::unique_ptr` has const-get that returns mutable-pointer, but `drake::copyable_unique_ptr` diverges from that pattern and stays const-correct."  But upon inspection:
```
copyable_unique_ptr<ConvexSet> c = std::make_unique<MutablePoint>(Vector2d{1., 2.});
const copyable_unique_ptr<ConvexSet>& c_ref = c;
static_assert(std::is_const_v<decltype(*c_ref)>);
```
fails the static assert.  To which Jeremy responded "Eww, I missed that `copyable_unique_ptr` inherits from `std::unique_ptr<T>` and fails to shadow `operator*` to preserve const-correctness.  We should look into fixing this..."

This would improve my use of `copyable_unique_ptr` in `ConvexSets`.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
In order to be compatble with a future copy-on-write unique pointer, `copyable_unique_ptr` made a distinction between `get()` and `get_mutable()`. The idea being that it would be nice to swap copyable with copy on write with the absolute minimum number of changes. So, by declaring that `const` distinction now, callers will think about mutable access.

However, this allowed getting a non-const *reference* via dereferencing, even from a `const copyable_unique_ptr`. Therefore, we distinguish derefencing a `copyable_unique_ptr` based on the *container's* `const`ness. Dereferencing a `const copyable_unique_ptr` will *always* return a `const` reference (and will be preserved with a copy-on-write pointer). But
dereferencing a non-`const` container, when swapped to copy-on-write, will trigger a copy.

This also adds a novel constructor: a model constructor. Constructs a new, uniquely owned instance by a copying a given *value*.

resolves #15344

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346#-:-Me670In2i-5Rx58wWBs:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one minor comment.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346#-:-Me6u8lh-wc45A5Q4beI:bph6umh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6sFfK7uwCvyn1bNXR:-Me6sFfL21LY0QR9sjSP:bmrm7an) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L310)):*
> ```objc
>    reference (if `T` is non-const), even if the container itself is const. For
>    a const %copyable_unique_ptr will always return a const reference to its
>    contained value.
> ```

minor: should note in the comment that the protection provided here is only partial since this only shadows the base class method -- if the `const copyable_unique_ptr` is upcast to `const unique_ptr` it becomes possible to get a mutable reference from a const container.

Consider adding a TODO here also to reengineer this to make it bulletproof. Switching to has-a rather than is-a would do it. Maybe private inheritance would work also with a few more forwarded methods?
___
*[common/copyable_unique_ptr.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6t3F-8bX0Q_dOosMR:-Me6t3F-8bX0Q_dOosMS:btcqdkr) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L314)):*
> ```objc
>   const T& operator*() const { return *get(); }
> 
>   /** Return a writable referece to the contained object (if T is itself not
> ```

nit: referece -> reference

**Comment by jwnimmer-tri** [comment]
___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me6v5X15TUVdIltnppT:b3rhyzz) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
> ```objc
>   // TODO(SeanCurtis-TRI): Consider adding some debug assertions about whether
>   // T is const or not. If so, it would be nice to give feedback that calling
>   // the mutable version makes no sense.
> ```

I don't such a change would be helpful.  Code that is using `copyable_unique_ptr` generically (i.e., where it doesn't necessarily know whether `T` is const) might want call `get_mutable` unconditionally, without having to check for constness to guard which function to call.  And especially if its a compile-time assertion, now it's not just a ternary operator at the call site, it's a whole if-constexpr statement that will span multiple lines.  The spurious use of `get_mutable` doesn't seem like a problem worth solving.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me711QG56u63a4zF5BC:b-cl0l5c) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
Let me see if I can marshall the argument for why it *might* be a good thing.

This particular interface is to prepare for copy-on-write. With copy-on-write semantics, calling the "mutable" version will create a copy. Creating a copy of something that *can't* be written to indicates a clear flaw in reasoning/usage. 

Currently, people can call `get_mutable()` and have no problem with a`T = const U` as long as they don't call anything non-const on it. If it changes to copy on write under the hood, now they're getting a copy that they don't want. They might as well know that there's a usage that is currently misleading and, in the future, costly.

> code...might want call get_mutable unconditionally, without having to check for constness to guard which function to call.

Presumably, if it's calling `get_mutable` it is with the express purpose of mutating the instance pointed to. So, it is, in fact, a requirement of the caller that the template parameter *not* be a `const` type. If they're blindly calling `get_mutable` with no expectation of mutating, then they are doing something nonsensical.

**Comment by jwnimmer-tri** [comment]
___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me73nrH6mJ5FgLPu1rr:b-c7fjgp) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Let me see if I can marshall the argument for why it *might* be a good thing.

This particular interface is to prepare for copy-on-write. With copy-on-write semantics, calling the "mutable" version will create a copy. Creating a copy of something that *can't* be written to indicates a clear flaw in reasoning/usage. 

Currently, people can call `get_mutable()` and have no problem with a`T = const U` as long as they don't call anything non-const on it. If it changes to copy on write under the hood, now they're getting a copy that they don't want. They might as well know that there's a usage that is currently misleading and, in the future, costly.

> code...might want call get_mutable unconditionally, without having to check for constness to guard which function to call.

Presumably, if it's calling `get_mutable` it is with the express purpose of mutating the instance pointed to. So, it is, in fact, a requirement of the caller that the template parameter *not* be a `const` type. If they're blindly calling `get_mutable` with no expectation of mutating, then they are doing something nonsensical.
</blockquote></details>

OK Thinking further, I guess in my example the user could just as well call `&*foo` if they want to obtain the possibly-mutable underlying pointer.  A `static_assert` that defeats the `get_mutable` longhand form sounds fine in that case.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review (as you've looked already and been an active part of the discussion).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346#-:-Me74y2s7I8xU0HmTWFt:bvuo4ri)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @sherm1)

___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me75Tkn0xLCBRjtfoNY:b-4bzey3) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Thinking further, I guess in my example the user could just as well call `&*foo` if they want to obtain the possibly-mutable underlying pointer.  A `static_assert` that defeats the `get_mutable` longhand form sounds fine in that case.
</blockquote></details>

Would you like me to put it in now?
___
*[common/copyable_unique_ptr.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6sFfK7uwCvyn1bNXR:-Me74D9i9SNnvNbXvKjq:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L310)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should note in the comment that the protection provided here is only partial since this only shadows the base class method -- if the `const copyable_unique_ptr` is upcast to `const unique_ptr` it becomes possible to get a mutable reference from a const container.

Consider adding a TODO here also to reengineer this to make it bulletproof. Switching to has-a rather than is-a would do it. Maybe private inheritance would work also with a few more forwarded methods?
</blockquote></details>

Done
___
*[common/copyable_unique_ptr.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6t3F-8bX0Q_dOosMR:-Me74F3qCGjVkMwlOT12:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: referece -> reference
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346#-:-Me78P4M0kTDxO840S3O:b-vtj4vo)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me76UlQ2xCbS42ArV-y:b-dpiy2o) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Would you like me to put it in now?
</blockquote></details>

Nope, I was only worried about a suspicious TODO making into master.  Since it's not actually suspicious, it's all good.
___
*[common/copyable_unique_ptr.h, line 336 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me76z2sBW2wBF_p-eGD:-Me76z2sBW2wBF_p-eGE:b-ie2o2t) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/copyable_unique_ptr.h#L336)):*
> ```objc
>    @warning If %copyable_unique_ptr is instantiated on a const template
>    parameter (e.g., `copyable_unique_ptr<const Foo>`), then get_mutable()
>    returns a const pointer.
> ```

nit I don't grok the mention of `get_mutable` here, maybe this is pasta?

In any case, I don't think a `@warning` marker is warranted here.  With get vs get_mutable, the user is very explicitly communicating that they want mutability, so the stark warning makes sense.  Here, this a bog-standard C++ "give me the thing you've wrapped".  I'd buy something resembling paragraph as a clarification of the parenthetical from the summary line, but I don't buy that it needs a red banner in the generated documentation.
___
*[common/test/copyable_unique_ptr_test.cc, line 1210 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me78MYfCxLvkZEWN93K:-Me78MYfCxLvkZEWN93L:b3jnshc) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/test/copyable_unique_ptr_test.cc#L1210)):*
> ```cpp
>   child_ptr.release();
> }
> ```

nit This new blank line seems spurious?

**Review by SeanCurtis-TRI — COMMENTED** [review]
One more piece of guidance added -- definitely  needs eyes on it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346#-:-Me7B8Gr9S6XnTyosnph:b-seekzn)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @sherm1)

___
*[common/copyable_unique_ptr.h, line 336 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me76z2sBW2wBF_p-eGD:-Me7B3sMEUvIfR_WtkOX:b-2njapa) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/copyable_unique_ptr.h#L336)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't grok the mention of `get_mutable` here, maybe this is pasta?

In any case, I don't think a `@warning` marker is warranted here.  With get vs get_mutable, the user is very explicitly communicating that they want mutability, so the stark warning makes sense.  Here, this a bog-standard C++ "give me the thing you've wrapped".  I'd buy something resembling paragraph as a clarification of the parenthetical from the summary line, but I don't buy that it needs a red banner in the generated documentation.
</blockquote></details>

In light of you comment, I've offered further guidance. Let me know what you think.
___
*[common/test/copyable_unique_ptr_test.cc, line 1210 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me78MYfCxLvkZEWN93K:-Me79aC38Lvz8T9sF0Mo:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/test/copyable_unique_ptr_test.cc#L1210)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This new blank line seems spurious?
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @sherm1)

___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me7B8CG0-TW8QFRfFBz:bs8n2b2) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nope, I was only worried about a suspicious TODO making into master.  Since it's not actually suspicious, it's all good.
</blockquote></details>

We should probably forbid copy_on_write_ptr to be instantiated on a const type.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @sherm1)

___
*[common/copyable_unique_ptr.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6sFfK7uwCvyn1bNXR:-Me7CtUL8QbgjXOP7yub:bmywq3l) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L310)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Is there a missing push (not seeing a change)?
___
*[common/copyable_unique_ptr.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6t3F-8bX0Q_dOosMR:-Me7Crfx6-w98HvlTfNb:b-zc83kf) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L314)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not seeing a change?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 5 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 306 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7DKOS561WBsgjRs3n:-Me7DKOS561WBsgjRs3o:b6a6fo4) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L306)):*
> ```objc
>   T* get_mutable() noexcept { return std::unique_ptr<T>::get(); }
> 
>   // TODO(15344) We need to shore up this const corretness hole. Rather than an
> ```

nit: corretness 
___
*[common/copyable_unique_ptr.h, line 334 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7Dd4PBtNTWi9SUfFv:-Me7Dd4PBtNTWi9SUfFw:b-f8135g) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L334)):*
> ```objc
>    write access to the object it contains.
> 
>    We *strongly* recommended, that, if dereferencing a %copyable_unique_ptr
> ```

nit: recommended -> recommend
___
*[common/copyable_unique_ptr.h, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7Dn9cBdS8HGxluH30:-Me7Dn9cBdS8HGxluH31:b-ooaula) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L336)):*
> ```objc
>    We *strongly* recommended, that, if dereferencing a %copyable_unique_ptr
>    without the intention of mutating the underlying value, prefer to dereference
>    a *const* &copyable_unique_ptr (or use *my_ptr.get()) and not a mutable
> ```

nit: `&` -> `%` (I think)
___
*[common/copyable_unique_ptr.h, line 337 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7DiVlEybIBpnOcONv:-Me7DiVlEybIBpnOcONw:b1eytmv) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L337)):*
> ```objc
>    without the intention of mutating the underlying value, prefer to dereference
>    a *const* &copyable_unique_ptr (or use *my_ptr.get()) and not a mutable
>    %copyable_unique_pptr. As "copy-on-write" behavior is introduced in the
> ```

nit: pptr -> ptr

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 5 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 336 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me76z2sBW2wBF_p-eGD:-Me7CjWa7aAtFWvSbP9u:b3sugbz) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/copyable_unique_ptr.h#L336)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In light of you comment, I've offered further guidance. Let me know what you think.
</blockquote></details>

The new doc is fine, even though I don't love it.

To be honest, I think the hypothesis that we can folgers-crystals this class to be CoW in the future is madness.  That is far too subtle of a breaking change (e.g., threading data races -- remember that const doesn't mean immutable) to make without a choosing a new class name and actively porting to use the new name.  The benefit of using a correctly-constified `copyable_unique_ptr` in user code is not that it will morph into CoW semantics under the hood for free, it's that when the time comes to do the IDE search-and-replace to say `s/copyable_unique_ptr/copy_on_write_ptr/`, the user will have fewer complaints from the compiler to overcome during porting.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: 5 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6v5X15TUVdIltnppS:-Me7EcIBBu7mUyqr6Fp_:b3l25ks) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L296)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

We should probably forbid copy_on_write_ptr to be instantiated on a const type.
</blockquote></details>

I don't necessarily disagree, but I don't see how that applies to copyable_unique_ptr?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6sFfK7uwCvyn1bNXR:-Me7FecZ-h231vUBOZkr:b7iertg) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L310)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Is there a missing push (not seeing a change)?
</blockquote></details>

It's there. Both a TODO (above) and a warning (below).
___
*[common/copyable_unique_ptr.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me6t3F-8bX0Q_dOosMR:-Me7FpDB8FZ3gzFGYLRs:bvjjd5i) ([raw file](https://github.com/robotlocomotion/drake/blob/04eef6fe6a355e2fcacc62a81d03121616f92b75/common/copyable_unique_ptr.h#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Not seeing a change?
</blockquote></details>

I think you have a revision issue. It's definitely there.
___
*[common/copyable_unique_ptr.h, line 336 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me76z2sBW2wBF_p-eGD:-Me7G21KC5KZfUy0BpSB:b-di5daa) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/copyable_unique_ptr.h#L336)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The new doc is fine, even though I don't love it.

To be honest, I think the hypothesis that we can folgers-crystals this class to be CoW in the future is madness.  That is far too subtle of a breaking change (e.g., threading data races -- remember that const doesn't mean immutable) to make without a choosing a new class name and actively porting to use the new name.  The benefit of using a correctly-constified `copyable_unique_ptr` in user code is not that it will morph into CoW semantics under the hood for free, it's that when the time comes to do the IDE search-and-replace to say `s/copyable_unique_ptr/copy_on_write_ptr/`, the user will have fewer complaints from the compiler to overcome during porting.
</blockquote></details>

It's true.. the supposition is somewhat magical. It's also probably predicated on a couple of unspoken assumptions. The expectation *is* that the cow ptr is a *different* type. I figured that wasn't worth getting into in the comment. So, for now, I'll leave it as is.
___
*[common/copyable_unique_ptr.h, line 306 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7DKOS561WBsgjRs3n:-Me7GbUG7B0vENMTpB9s:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L306)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: corretness 
</blockquote></details>

Done
___
*[common/copyable_unique_ptr.h, line 334 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7Dd4PBtNTWi9SUfFv:-Me7GVcl77W_IGp_t4Sm:bt3dk81) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L334)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: recommended -> recommend
</blockquote></details>

Done

(You can tell I only *partially* backed out of passive voice there.)
___
*[common/copyable_unique_ptr.h, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7Dn9cBdS8HGxluH30:-Me7GSx46K3EZyUlWg6Q:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L336)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `&` -> `%` (I think)
</blockquote></details>

Done
___
*[common/copyable_unique_ptr.h, line 337 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me7DiVlEybIBpnOcONv:-Me7GSLz0xqtWlhnSqNW:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5b8ffb6547629a29aa052f1bb2c4608098504481/common/copyable_unique_ptr.h#L337)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: pptr -> ptr
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15346)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @SeanCurtis-TRI)

___
*[common/copyable_unique_ptr.h, line 336 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15346#-Me76z2sBW2wBF_p-eGD:-Me7JpocCHKvBpzIhoRu:bypi4u4) ([raw file](https://github.com/robotlocomotion/drake/blob/b72ea72dc143b19ee927e20308203a2891748872/common/copyable_unique_ptr.h#L336)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It's true.. the supposition is somewhat magical. It's also probably predicated on a couple of unspoken assumptions. The expectation *is* that the cow ptr is a *different* type. I figured that wasn't worth getting into in the comment. So, for now, I'll leave it as is.
</blockquote></details>

It's fine.  My only hypothetical worry is that a code reviewer would use this documentation to browbeat an author that they are using copyable_unique_ptr wrong, when in practice it doesn't actually matter.  "This doesn't actually matter" and "We strongly recommend" are at odds, but meh -- I'm happy to defer that hypothetical until it actually happens in situ.

**Pull request merged**
