### PR TITLE
multibody/plant: Opt-out from subtype checking in scalar conversion

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10414)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Indeed, if you need your _subclass constructor_ to run and add things to the _System_ (as opposed to only changing the _Tree_) during transmogrification, then this fix is not good enough.  We'd need to add the more complicated (and many) constructor overloads for that case.

For constraints in particular though, #10394 proposes auto-transmogrifying constraints, which would address your use case, with or without subclassing.

Maybe we should step back and see if you _really_ need to subclass, for this application.  Personally, I think subclassing MBP is a terrible, terrible idea, and we should not go very far down that path, if we can help it.

**Comment by jwnimmer-tri** [comment]
> Jeremy, can you explain why you think subclassing MBPlant is a bad idea?

Sure!

> The only example I see of that in Drake is AxiallySymmetricFreeBodyPlant<T> in a test case, but to me it looks very reasonable ...

Well, there is already a TODO on that plant to stop subclassing.  So I'm not sure that everyone agrees with you!

> ... and it does have its own data members that need to be transmogrified.

Not really true!  Those data members are _only_ used during construction (i.e., not by any member methods).  And (1) the constructor that uses them is dead code, because the transmogrification is incorrectly implemented, and (2) those constants only influence the bodies in the tree, so they don't need to be kept around -- the tree already knows how to transmogrify itself, keeping the same bodies (and masses, etc).  Even if we wrote a transmog constructor, it wouldn't need those fields to be available in the donor (`other`) system.

> And the result should be AxiallySymmetricFreeBodyPlant<U> rather than MultibodyPlant<U>.

Why do we care?  Why do we need the _C++ type system_ to describe that something is `ASFBP<AutoDiffXd>` -- what would we do differently, if we were able to downcast an object into that type?  We're certainly not (yet) doing that (because it would fail).

Note that the object we end up with _is already an ASFBP_ in all but the RTTI.  It has the right body / mass matrix / frames / etc.  It works exactly how we want.  I just can't cast it to an ASFBP.

If I want an `ASFBP<AutoDiffXd>` instance, I can still make one directly to interrogate -- I just can't _transmogrify_ a double-instantiated plant into one.

> Admittedly making nested transmog work properly is not the easiest thing to do, but I would expect most concrete derived MBPlants wouldn't need it anyway.

I haven't prototyped it, but I suspect its quite challenging, actually.  You'd really want to (conceptially) replay the `AddBody*` or whatever calls in the order they happened during _normal_ construction -- so that the subclass constructor order of operations can be correctly interleaved with the MBP constructor + mutation + Finalize methods.  You also don't have a SceneGraph pointer available anymore, so things get hairy there as well -- the subclass constructor couldn't change anything pre-finalize easily anymore.  If you do anything other than AddBody (and related) calls (e.g., add a SystemConstraint, or a new output port, or etc.) those _will not work_ with the current MBP transmog codepaths.  Maybe all of those things are solveable, but (as I'll try to explain below) we should _not even attempt it_.

> It seems very natural to me to have a specific plant inherit from the general one.

That's exactly the opposite of how algebraic datatypes work!  Subclassing cannot _narrow_ a contract of a type!  Anything I could do to a MBP, I should be able to do to an ASFBP.  If I call `MBP::AddJoint` on an ASFBP, is it still a valid ASFBP?  If I call `MBP::AddForceElement` on an ASFBP, is it still a valid ASFBP?  Will there _never be any method at all_ ever offered on MBP, that would be nonsense to apply to an ASFBP (and still have it be properly understood to be an ASFBP?).

I think, instead, that what makes sense is to deliver a factory that creates a MBP instance that _initially_ happens to model an ASFBP semantically, but without any special runtime type.  If the user talks to that, it behaves like the single free body that they want.  If the user calls mutators on it to tweak it, it's still a MBP but no longer acts like an ASFBP.

Yes, there are ergonomics questions around MBP factories, finalization, functional composition, adding in visualizations, etc. -- but those are the same for all MBP users, and we should make them easier to accomplish simply by improving the MBP API surface, _not_ by requiring users to subclass the plant.

**Comment by jwnimmer-tri** [comment]
Something like http://web.engr.oregonstate.edu/~budd/Books/oopintro3e/info/chap08.pdf seems like a good summary, and the principle of "substitution" is what I'm objecting to.  (Formally known as the https://en.wikipedia.org/wiki/Liskov_substitution_principle.)

**Comment by sherm1** [comment]
Well, you certainly make a compelling argument! I had been thinking that an ASFPB _is_a_ MultibodyPlant, which would be true if MBPlant weren't also an "MBPlantBuilder". I withdraw my objection to making MBPlant `final` and appreciate your taking the time to straighten me out.

**Comment by jwnimmer-tri** [comment]
Right!  If the plant were _immutable_ (not the same as `const`!) then the substitution principle becomes much easier to satisfy, and we can still achieve specialization.

Since this PR (appears to) move us in the wrong direction, I'll close it for now.  Github will remember, in case we ever need to resurrect this one.

**Pull request closed without merging**
