### PR TITLE
Remove redundant call to drake_find_package/target_include_directories for gurobi

### PR DESCRIPTION
**Pull request by jamiesnape**
`target_link_libraries` populates `target_include_directories` and finding gurobi with `pkg-config` is unnecessary.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4413)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4413#-:-KYPjKHh0NomIIXs3jKV:undefined)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4413#-:-KYQ3CGf6o_IO1qAvvqG:bnfp4nl)*

**Pull request merged**
