### PR TITLE
Add `call_python` client and test code.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses #7487, Step 1.

**NOTE**: This breaks compatibility between old and new `call_matlab` code. Let me know if I should just copy and paste the protobuf message to keep things the same.

\cc @RussTedrake @avalenzu

Stats:
```
$ git_cloc
Computing difference between $(git merge-base master HEAD) (bdff8c1) and 'HEAD' (894064c).

Category            added  modified  removed  
----------------------------------------------
code                565    15        3        
comments            126    3         1        
blank               132    0         0        
----------------------------------------------
TOTAL               823    18        4    
```
This goes slightly over the ~500 LOC limit for PRs, but I could not find a satisfying division. Let me know if you would like it divided in another way.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7496)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.
+@sherm1 for platform review, please.

I have set this to be reviewed by each commit separately.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-:-Kz6ZaPk9UPDvXeuR8Yz:b-qhg7vg)*

**Comment by sherm1** [comment]
Platform :lgtm: with some minor BTWs but still needs a careful feature review.

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_matlab.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAJ9tUtY63tNUza2zS:-KzAJ9tUtY63tNUza2zT:b3moqnx) ([raw file](https://github.com/robotlocomotion/drake/blob/c2ed9f5dd186dcc7e1fc060af38b17e0422b0430/drake/common/proto/call_matlab.cc#L29)):*
> ```cpp
> {}
> 
> void ToMatlabArray(const MatlabRemoteVariable& var, MatlabArray* matlab_array) {
> ```

BTW From the names I expected that the internal::ToMatlabArrayImpl() methods to be used to implement the ToMatlabArray() methods but it looks like they are all independent here. If these aren't "implementation" methods then a comment or name change would be helpful.

---

*[drake/common/proto/call_python.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAJjRu3G2YSaWqTFVo:-KzAJjRu3G2YSaWqTFVp:b-jkz8zg) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/call_python.h#L9)):*
> ```objc
> #include "drake/common/proto/call_matlab.h"
> 
> /// @file Utilities for calling Matlab from C++
> ```

BTW this isn't the right syntax for `@file` -- its argument is actually a file name that defaults to the current file. So it should always just appear on its own line, alone.

---

*[drake/common/proto/call_python.h, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzALmqLyKV8djZn48sY:-KzALmqLyKV8djZn48sZ:b-on8tnx) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/call_python.h#L23)):*
> ```objc
> // Necessary since we have not yet defined `PythonRemoteVariable`.
> class PythonRemoteVariable;
> void ToMatlabArray(const PythonRemoteVariable& var, MatlabArray* matlab_array);
> ```

BTW unclear to me why this is a *Matlab*Array?

---

*[drake/common/proto/test/call_python_full_test.sh, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAN_TWV8gBiLjwuwqN:-KzAN_TWV8gBiLjwuwqO:b-w40bgg) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/test/call_python_full_test.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

BTW a short file-level comment would be helpful here to say what this is for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-:-KzANz6UM_OvZk8FERg6:bncg5ee)*

**Comment by sherm1** [comment]
Also there are some build failures to investigate.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-:-KzAOEXdx0uLaYO9eiN3:b-sv25pd)*

**Comment by EricCousineau-TRI** [comment]
Tried a fix for the build failures (updating `install_prereqs.sh`). Thanks!

---

Review status: 2 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/proto/call_matlab.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAJ9tUtY63tNUza2zS:-KzAo5QD7P2OPU0c4I6i:b-k51omm) ([raw file](https://github.com/robotlocomotion/drake/blob/c2ed9f5dd186dcc7e1fc060af38b17e0422b0430/drake/common/proto/call_matlab.cc#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW From the names I expected that the internal::ToMatlabArrayImpl() methods to be used to implement the ToMatlabArray() methods but it looks like they are all independent here. If these aren't "implementation" methods then a comment or name change would be helpful.
</blockquote></details>

Done. Renamed to `ToMatlabArrayMatrix`.

---

*[drake/common/proto/call_python.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAJjRu3G2YSaWqTFVo:-KzAoIXrBRp0cwbUknfG:b-kwviq5) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/call_python.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this isn't the right syntax for `@file` -- its argument is actually a file name that defaults to the current file. So it should always just appear on its own line, alone.
</blockquote></details>

Done. Thanks for pointing that out!

---

*[drake/common/proto/call_python.h, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzALmqLyKV8djZn48sY:-KzAoKK9NmBsmCSLKaqF:bwjhnt) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/call_python.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unclear to me why this is a *Matlab*Array?
</blockquote></details>

Done. Added clarifying comment (pertinent to Step 3 [here](https://github.com/RobotLocomotion/drake/issues/7487#issue-274338788)).

---

*[drake/common/proto/test/call_python_full_test.sh, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAN_TWV8gBiLjwuwqN:-KzAoxOglXQsuZ5udEHf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/894064ce3d8213b807069d083e021f7ee210af0c/drake/common/proto/test/call_python_full_test.sh#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a short file-level comment would be helpful here to say what this is for.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-:-KzAoyELcSjI4BcXOVXI:b4nj2gq)*

**Comment by sherm1** [comment]
Reviewed 3 of 8 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/proto/call_matlab.h, line 59 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAs58MPJQmbz8TD-aX:-KzAs58MPJQmbz8TD-aY:bmtl1qy) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_matlab.h#L59)):*
> ```objc
> 
> void ToMatlabArrayMatrix(const Eigen::Ref<const Eigen::MatrixXi>& mat,
>                        MatlabArray* matlab_array, bool is_vector);
> ```

BTW nit - indent got messed up by 2 spaces

---

*[drake/common/proto/call_python.h, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAsEo2Et1m12fZoI-F:-KzAsEo35Q87vhrszVln:bxq0ugx) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L24)):*
> ```objc
> // Necessary since we have not yet defined `PythonRemoteVariable`.
> class PythonRemoteVariable;
> // TODO(eric.cousineau): Generalize RPC marhsaling so that we do not need to
> ```

BTW marhsaling -> marshaling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot 
linux-xenial-unprovisioned-clang-bazel-experimental-everything please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
linux-xenial-unprovisioned-clang-bazel-experimental linux-highsierra-unprovisioned-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Hmm... Looks like trying to test `matplotlib` on CI is not a good idea.
On Linux, there seems to be a `$DISPLAY` issue (possibly related to #5227?).
On Mac, it just looks like a `matplotlib` bug - some sort of API change.

Will try to think of alternatives (i.e. throwing in a flag in the unittest which enables plotting if run via `bazel run` rather than `bazel test` or whatever).

**Comment by kunimatsu-tri** [comment]
Reviewed 2 of 4 files at r2, 4 of 8 files at r5.
Review status: 8 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_python.h, line 10 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzBP1-xzuTgmDoTpro-:-KzBP1-xzuTgmDoTpro0:b-1z6btl) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L10)):*
> ```objc
> 
> /// @file
> /// @brief Utilities for calling Matlab from C++
> ```

I guess you meant "calling Python from C++"?

---

*[drake/common/proto/call_python.h, line 38 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzBPgUD1t8Fac0Ks-zh:-KzBPgUD1t8Fac0Ks-zi:btsvq30) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L38)):*
> ```objc
> PythonRemoteVariable NewPythonVariable(T value);
> 
> class PythonRemoteVariable;
> ```

You declare this twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Review status: 5 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/proto/call_matlab.h, line 59 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAs58MPJQmbz8TD-aX:-KzQoCpGhFEUlzELcz0d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_matlab.h#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW nit - indent got messed up by 2 spaces
</blockquote></details>

Done.

---

*[drake/common/proto/call_python.h, line 10 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzBP1-xzuTgmDoTpro-:-KzQoDfFVjXR_-Vr9UIb:ble5auz) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L10)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I guess you meant "calling Python from C++"?
</blockquote></details>

Oops! Done. 

---

*[drake/common/proto/call_python.h, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzAsEo2Et1m12fZoI-F:-KzQoH78LvYHER8vp0RD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW marhsaling -> marshaling
</blockquote></details>

Done.

---

*[drake/common/proto/call_python.h, line 38 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzBPgUD1t8Fac0Ks-zh:-KzQoHk9BBpp9JxLWv_G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2178043e8d002abe02b2af9bbe7cefd008b09c1d/drake/common/proto/call_python.h#L38)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

You declare this twice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
mac-highsierra-unprovisioned-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
mac-sierra-unprovisioned-clang-bazel-experimental please.

**Comment by kunimatsu-tri** [comment]
:lgtm: with some minor btw comments.

---

Reviewed 2 of 8 files at r5, 3 of 4 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_python_client.py, line 162 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRdzcFGmS0zp-TnEx0:-KzRdzcFGmS0zp-TnEx1:b-o2qe90) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L162)):*
> ```Python
> 
> 
> _default_filename = "/tmp/python_rpc"
> ```

BTW, constants should be written in all capital letters: https://www.python.org/dev/peps/pep-0008/#constants

---

*[drake/common/proto/call_python_client.py, line 171 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRiqhRsQTxYMZIq4as:-KzRiqhRsQTxYMZIq4at:bg5kdom) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L171)):*
> ```Python
>                  scope_globals=None, scope_locals=None):
>         if filename is None:
>             self.filename = _default_filename
> ```

BTW, do you have any particular reasons why you put `self.filename` instead of `self._filename`?

ditto for `self.scope_locals`, `self.scope_globals`, `self.stop_on_error` and `self.client_vars`.

---

*[drake/common/proto/call_python_client.py, line 316 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRa_bBR6yGoPAi7dFJ:-KzRa_bBR6yGoPAi7dFK:b-o2qe90) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L316)):*
> ```Python
> # Number of bytes we need to consume so that we may still use
> # `_DecodeVarint32`.
> _peek_size = 4
> ```

BTW, constants should be written in all capital letters: https://www.python.org/dev/peps/pep-0008/#constants

---

*[drake/common/proto/test/call_python_test.cc, line 72 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRWub67EHOl-1hTRN3:-KzRWub67EHOl-1hTRN4:bjwhhjy) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/test/call_python_test.cc#L72)):*
> ```cpp
> 
> GTEST_TEST(TestCallPython, Plot2d) {
>   int N = 100;
> ```

BTW, use `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-:-KzRjX38sAgoEvBcSkRj:be0q06r)*

**Comment by kunimatsu-tri** [comment]
Reviewed 1 of 8 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by EricCousineau-TRI** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 162 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRdzcFGmS0zp-TnEx0:-KzUF1nwBb75NTUpjxXi:byg2o10) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L162)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, constants should be written in all capital letters: https://www.python.org/dev/peps/pep-0008/#constants
</blockquote></details>

Done. (Didn't see private constants mentioned in PEP 008, but they are mentioned in the Python Google Style Guide.)

---

*[drake/common/proto/call_python_client.py, line 171 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRiqhRsQTxYMZIq4as:-KzUEQ_25mLU85gmGcql:b-178wgh) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L171)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, do you have any particular reasons why you put `self.filename` instead of `self._filename`?

ditto for `self.scope_locals`, `self.scope_globals`, `self.stop_on_error` and `self.client_vars`.
</blockquote></details>

Done. I would like `filename`, `scope_locals`, and `scope_globals` to be part of the public interface, and PEP 008 recommends keeping them as simple attributes, with the option to promote them to properties if need be.
For `stop_on_error`, `cilent_vars`, that was a mistake! Fixed those!

---

*[drake/common/proto/call_python_client.py, line 316 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRa_bBR6yGoPAi7dFJ:-KzUJj8TLHH5m5Sj-Oko:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L316)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, constants should be written in all capital letters: https://www.python.org/dev/peps/pep-0008/#constants
</blockquote></details>

Done.

---

*[drake/common/proto/test/call_python_test.cc, line 72 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRWub67EHOl-1hTRN3:-KzUJPK3ZbhkcgxXlk32:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/test/call_python_test.cc#L72)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, use `const`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot
mac-sierra-unprovisioned-clang-bazel-experimental please.
(I assume the failures here were just download flukes. Trying again to validate PR for additional prereqs.)

**Comment by kunimatsu-tri** [comment]
*[drake/common/proto/call_python_client.py, line 162 at r7](https://reviewable.io:443/reviews/robotlocomotion/drake/7496#-KzRdzcFGmS0zp-TnEx0:-KzWCwiyZA5t98edq6SR:b-nsvjr5) ([raw file](https://github.com/robotlocomotion/drake/blob/221d03ab9db82a7f02f4ae33a7c4c5f9a63ea00f/drake/common/proto/call_python_client.py#L162)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. (Didn't see private constants mentioned in PEP 008, but they are mentioned in the Python Google Style Guide.)
</blockquote></details>

I think PEP8 just doesn't distinguish whether constants are private or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by kunimatsu-tri** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7496)*

**Comment by jamiesnape** [comment]
Add this to [tools/install/libdrake/build_components.bzl](https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/build_components.bzl)?

**Comment by EricCousineau-TRI** [comment]
I'd prefer to hold off on including this in installation for this PR; I will post this as an additional task in the original issue.

**Comment by jamiesnape** [comment]
We do not curate what is installed from core at present, so I would prefer not to get too out of sync. If it is outright broken when used from the install, then edit [tools/install/libdrake/build_components_refresh.py](https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/build_components_refresh.py) to exclude it, otherwise it should probably be included in this PR so we do not get any surprises when someone next runs the script that generates the list.

**Comment by EricCousineau-TRI** [comment]
Removed `testonly` from `call_matlab` and `call_python` so that `build_components_refresh` will find them -- would that work for you?
(I'd prefer not to handle installing the Python components for now.)

**Comment by EricCousineau-TRI** [comment]
(Spoke to Jamie and Betsy Slack, PR is good to merge.)

**Pull request merged**
