### PR TITLE
[planning] Hotfix unit test for ARM machine precision

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18624)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

**Comment by jwnimmer-tri** [comment]
Tested locally; confirmed fix.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: +@rpoyner-tri rubber stamp

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18624#-:-NMAzrGD0CV_0AzCeOTh:b-kba8wq)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18624)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
