### PR TITLE
[pydrake] Add lcmtypes under a new package name

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Breaking change explanation: We no longer offer pydrake serializer dictionary entries for the `drake.lcmt_foo` spelling of lcmtypes.  Instead, users must use the `pydrake.lcmtypes.lcmt_foo` spelling instead.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for feature review, please.  Or at least -- of the Python-specific bits.  I can find a separate Bazel reviewer for the build system stuff, if that saves you time.

Note that I have chosen _not_ to deprecate the `from drake import lcmt_drake_signal` spelling in this PR, I'm only _adding_ the new spelling.  This is to keep the PR size in check, and also to allow us a slightly longer transition period to ease the deprecation.  I imagine adding the deprecation markers in +1 or +2 months from now, so the old types would stick around until ~the new year.

+(release notes: breaking change) -(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577#-:-MgO93onEsQd2Z7VWXU6:b-lgvdce)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgO8tEs9RVwgGD1fpXU:-MgO8tEs9RVwgGD1fpXV:b3t80zi) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf03e041bb30dc8b178dfefea4f0419863437dc/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17)):*
> ```cpp
> namespace pylcm {
> 
> void BindCppSerializers() {
> ```

@EricCousineau-TRI this is a breaking change -- we no longer offer `_Serializer` dict entries for the `drake.lcmt_foo` types.  Does that seem okay to you?

The entire point of this PR is that `import pydrake` cannot depend on `import drake` in the pip wheel, so if we need to keep them, then I only see two choices here:

(1) Try an `import drake` here first, and only add the drake lcmtype iff that module exists.

(2) Keep the existing `BindCppSerializer` using `drake` package as well as adding these new ones, but then injecct a patch file to our pip build process to revert the `drake` package here, for the pip build only.

Either work-around could be removed after we deprecate and remove `import drake` spelling for lcmtypes.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgO8tEs9RVwgGD1fpXU:-MgRGfHv6IoykTpxIYmw:btdouet) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf03e041bb30dc8b178dfefea4f0419863437dc/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@EricCousineau-TRI this is a breaking change -- we no longer offer `_Serializer` dict entries for the `drake.lcmt_foo` types.  Does that seem okay to you?

The entire point of this PR is that `import pydrake` cannot depend on `import drake` in the pip wheel, so if we need to keep them, then I only see two choices here:

(1) Try an `import drake` here first, and only add the drake lcmtype iff that module exists.

(2) Keep the existing `BindCppSerializer` using `drake` package as well as adding these new ones, but then injecct a patch file to our pip build process to revert the `drake` package here, for the pip build only.

Either work-around could be removed after we deprecate and remove `import drake` spelling for lcmtypes.
</blockquote></details>

I just tried (2) and it doesn't seem to work out of the box -- we can't have two messages of the same name, in different packages.  I think means (1) won't work, either.

I think the status quo in this PR is probably the right path forward.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 7 of 11 files at r2, 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/lcmtypes/test/acceptance_test.py, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSPkL85dH9DhPbzF8X:-MgSPkL90g3UCRbZxPGr:b6di2me) ([raw file](https://github.com/robotlocomotion/drake/blob/054c3c6ed6f3bfd4440223614d48920d1b2b84b4/bindings/pydrake/lcmtypes/test/acceptance_test.py#L9)):*
> ```Python
> class AcceptanceTest(unittest.TestCase):
> 
>     def test_nested_types(self):
> ```

Per below, since you are copying module source code, rather than attempting forward types, the Python class ids will be different b/c the code is reexecuted, rather than forwarding / aliasing the `drake` types.
The following should indicate the distinct class ids:
```
import drake

self.assertIsNot(drake.lcmt_quaternion, pydrake.lcmtypes.lcmt_quaternion)
```

Request:s:
- Encode this behavior in this unittest.
- Use solution (a) from below to preserve this relation in from-source mode.
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgO8tEs9RVwgGD1fpXU:-MgSMvwH-LRz1TXvH1IV:b-kjokvk) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf03e041bb30dc8b178dfefea4f0419863437dc/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17)):*
> Does that seem okay to you?

I believe this is more backwards-incompatible beyond `lcm` C++ <-> Python interop.
That being said, I think it's an OK compromise!

See below for possible alternatives.

> I just tried (2) [...] we can't have two messages of the same name, in different packages

Aye; in this specific case, I believe it's because you're trying to register two distinct Python class instances (`pydrake.lcmtypes.lcmt_foo` and `drake.lcmt_foo`) to the *same* C++ typeid (`drake::lcmt_foo`).

There is a way we could make this backwards-compatible:

(a) When running via a non-pip install, forward-alias the `drake` spellings into `pydrake.lcmtypes`. This means the classes would have same ids, i.e. `pydrake.lcmt_foo is drake.lcmtypes.lcmt_foo` should be true. For install tree, install copies.

(b) Update the logic in `_lcm_extra.py` with a heuristic to intercept any `drake.lcmt_foo` spelling, and replace it with `pydrake.lcmt_foo`. Since the associated C++ typeid should be same, this shouldn't be an issue.

IMO, (a) is the best, because any `isinstance(a, drake.lcmt_foo` spellings in downstream code will break until the `drake` spelling is removed.

WDYT? Would you like any help implementing this?
(there will be some complication btw forwarding from `drake` vs. `pydrake.lcmtypes`, tho...)

We can also just break things, and say `pydrake.lcmtypes.lcmt_foo is not drake.lcmt_foo`, because reasons.
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSR3hqB3rDTgCW8F9f:-MgSR3hqB3rDTgCW8F9g:b-p72usw) ([raw file](https://github.com/robotlocomotion/drake/blob/dbb6f4edfefee96e20358a12055dd478820e5fe9/bindings/pydrake/systems/meshcat_visualizer.py#L14)):*
> ```Python
> import numpy as np
> 
> from drake import lcmt_viewer_load_robot
> ```

BTW Yay! Free fix!
___
*[lcmtypes/BUILD.bazel, line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSMGMU6qs3pyL_BHeP:-MgSMGMU6qs3pyL_BHeQ:b-hvrm50) ([raw file](https://github.com/robotlocomotion/drake/blob/054c3c6ed6f3bfd4440223614d48920d1b2b84b4/lcmtypes/BUILD.bazel#L52)):*
> ```Starlark
> (len(_MISSING_ALL + _EXTRA_ALL) == 0) or fail(
>     "Please update lcmtypes/defs.bzl to add {} and remove {}".format(
>         _MISSING_ALL,
> ```

BTW Inlining large values / commands are hard to visually parse. Consider placing each value on a separate line.

**Comment by EricCousineau-TRI** [comment]
As an aside, another alternative is to eventually re-spell `pydrake` as `drake`.
That may be way more effort than it's worth, but would simplify oddities w/ LCM and other codegen tools that require top-level namespaces / modules (e.g. `drake` vs `drake.lcmtypes`).

**Review by jwnimmer-tri — COMMENTED** [review]
> As an aside, another alternative is to eventually re-spell pydrake as drake.

I think at this point we're using `pydrake` forevermore.  We're weeks away from `pip install pydrake` which will lock in the name permanently.  If a codegen tool can't handle the very basic namespacing we're doing, then it is broken and we should fix it and/or not use it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577#-:-MgSkAhXBveQPu8rAUjz:b-q76ww1)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[__init__.py, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6lJAETk7sZ7DSrQL:-MgT6lJAETk7sZ7DSrQM:b3l9pv8) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/__init__.py#L13)):*
> ```Python
> 
> try:
>     from pydrake.lcmtypes import *
> ```

Working

We should mark the `drake.lcmt_foo` names with deprecation warnings.
___
*[bindings/pydrake/lcmtypes/test/acceptance_test.py, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSPkL85dH9DhPbzF8X:-MgT5zdB6ISYdrfjy_Xo:b-pr278b) ([raw file](https://github.com/robotlocomotion/drake/blob/054c3c6ed6f3bfd4440223614d48920d1b2b84b4/bindings/pydrake/lcmtypes/test/acceptance_test.py#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per below, since you are copying module source code, rather than attempting forward types, the Python class ids will be different b/c the code is reexecuted, rather than forwarding / aliasing the `drake` types.
The following should indicate the distinct class ids:
```
import drake

self.assertIsNot(drake.lcmt_quaternion, pydrake.lcmtypes.lcmt_quaternion)
```

Request:s:
- Encode this behavior in this unittest.
- Use solution (a) from below to preserve this relation in from-source mode.
</blockquote></details>

Sorry, I'm not sure what the problem is here, and I'm also even unclear on what change you're proposing (even without understanding the problem yet)?
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgO8tEs9RVwgGD1fpXU:-MgSoEk54W0XYTZ6Mwje:bglclni) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf03e041bb30dc8b178dfefea4f0419863437dc/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> Does that seem okay to you?

I believe this is more backwards-incompatible beyond `lcm` C++ <-> Python interop.
That being said, I think it's an OK compromise!

See below for possible alternatives.

> I just tried (2) [...] we can't have two messages of the same name, in different packages

Aye; in this specific case, I believe it's because you're trying to register two distinct Python class instances (`pydrake.lcmtypes.lcmt_foo` and `drake.lcmt_foo`) to the *same* C++ typeid (`drake::lcmt_foo`).

There is a way we could make this backwards-compatible:

(a) When running via a non-pip install, forward-alias the `drake` spellings into `pydrake.lcmtypes`. This means the classes would have same ids, i.e. `pydrake.lcmt_foo is drake.lcmtypes.lcmt_foo` should be true. For install tree, install copies.

(b) Update the logic in `_lcm_extra.py` with a heuristic to intercept any `drake.lcmt_foo` spelling, and replace it with `pydrake.lcmt_foo`. Since the associated C++ typeid should be same, this shouldn't be an issue.

IMO, (a) is the best, because any `isinstance(a, drake.lcmt_foo` spellings in downstream code will break until the `drake` spelling is removed.

WDYT? Would you like any help implementing this?
(there will be some complication btw forwarding from `drake` vs. `pydrake.lcmtypes`, tho...)

We can also just break things, and say `pydrake.lcmtypes.lcmt_foo is not drake.lcmt_foo`, because reasons.
</blockquote></details>

I was planning to make `drake.lcmt_foo` into an alias in a soon-future PR, but it sounds like I should do it right away.  I've took a swing that that in the latest push.

It means that the `from drake import lcmt_foo` (and thus, drake_visualizer) now depends on libdrake.so, but I guess that will just be even more incentive to fix the TODO on `//bindings/pydrake/lcmtypes` quickly.
___
*[lcmtypes/test/nested_types_test.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6bEb0rBJusUP2oei:-MgT6bEb0rBJusUP2oej:b-vhp9vq) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/lcmtypes/test/nested_types_test.py#L1)):*
> ```Python
> import unittest
> ```

FYI I needed to change this test to use unittest now, because it now (indirectly) uses pydrake, and we can't call pydrake from a non-unittest test.
___
*[manipulation/schunk_wsg/schunk_buttons.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT7DGMD9YFHNrmONct:-MgT7DGMD9YFHNrmONcu:bl90psr) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/manipulation/schunk_wsg/schunk_buttons.py#L1)):*
> ```Python
> """Add buttons to drake-visualizer to open and close the Schunk WSG.
> ```

FYI Per #15583, this file is dead code (thus, no BUILD file change, even though imports have changed).

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 11 files at r2, 2 of 6 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[__init__.py, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6lJAETk7sZ7DSrQL:-MgTRCI_6wafHjICPvMz:b-wde54t) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/__init__.py#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

We should mark the `drake.lcmt_foo` names with deprecation warnings.
</blockquote></details>

My suggestion is to use the `ModuleShim` (PEP 562 stand-in).

FWIW It was actually design for deprecating forwarded symbols at root-level `pydrake`, e.g. `pydrake.rbtree`:
https://github.com/RobotLocomotion/drake/commit/06c690577b#diff-5490a5b644ae22988a6de5b0ea04943395da7ce04cb546695f67ce582c8438f2R40
___
*[bindings/pydrake/lcmtypes/test/acceptance_test.py, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSPkL85dH9DhPbzF8X:-MgTPoUe6nAN41utAPjM:bz8b1ob) ([raw file](https://github.com/robotlocomotion/drake/blob/054c3c6ed6f3bfd4440223614d48920d1b2b84b4/bindings/pydrake/lcmtypes/test/acceptance_test.py#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry, I'm not sure what the problem is here, and I'm also even unclear on what change you're proposing (even without understanding the problem yet)?
</blockquote></details>

My b; basically, I see no testing which guarantees `drake.lcmt_foo` is an alias of `pydrake.lcmtypes.lcmt_foo` vs. an entirely distinct class instance (what you'd get by copying the source code).

Can you add such a test (here, or in `//lcmtypes`?)
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgO8tEs9RVwgGD1fpXU:-MgTSGaeDpptVhmKfjv6:bt8fit1) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf03e041bb30dc8b178dfefea4f0419863437dc/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was planning to make `drake.lcmt_foo` into an alias in a soon-future PR, but it sounds like I should do it right away.  I've took a swing that that in the latest push.

It means that the `from drake import lcmt_foo` (and thus, drake_visualizer) now depends on libdrake.so, but I guess that will just be even more incentive to fix the TODO on `//bindings/pydrake/lcmtypes` quickly.
</blockquote></details>

OK Sweet! Using an alias means that this should no longer be an issue for `_Serializer_`.
___
*[lcmtypes/test/nested_types_test.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6bEb0rBJusUP2oei:-MgTQQ0s7qYVAawAdFWY:b-ewd4hq) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/lcmtypes/test/nested_types_test.py#L1)):*
> we can't call pydrake from a non-unittest test.

Not sure if I understand why this is the case; is it just b/c deprecation is thrown?
(That being said, may not be important that I understand)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[__init__.py, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6lJAETk7sZ7DSrQL:-MgahHIsASfPSkF5BbS4:bvi8yt8) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/__init__.py#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My suggestion is to use the `ModuleShim` (PEP 562 stand-in).

FWIW It was actually design for deprecating forwarded symbols at root-level `pydrake`, e.g. `pydrake.rbtree`:
https://github.com/RobotLocomotion/drake/commit/06c690577b#diff-5490a5b644ae22988a6de5b0ea04943395da7ce04cb546695f67ce582c8438f2R40
</blockquote></details>

Done.

When a user has `@drake//lcmtypes:lcmtypes_drake_py` in their BUILD deps, they will receive a bazel warning at analysis time.  Then, if they also do `import drake` anywhere with those bad deps, then they will receive a Python warning, even if the import was for something other than lcmtypes.  This is perhaps slightly more warnings than strictly required, but results in a simple implementation.
___
*[bindings/pydrake/lcmtypes/test/acceptance_test.py, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgSPkL85dH9DhPbzF8X:-Mga_hi_-MZy5wJAKlJu:b571jbe) ([raw file](https://github.com/robotlocomotion/drake/blob/054c3c6ed6f3bfd4440223614d48920d1b2b84b4/bindings/pydrake/lcmtypes/test/acceptance_test.py#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My b; basically, I see no testing which guarantees `drake.lcmt_foo` is an alias of `pydrake.lcmtypes.lcmt_foo` vs. an entirely distinct class instance (what you'd get by copying the source code).

Can you add such a test (here, or in `//lcmtypes`?)
</blockquote></details>

Done.

(To avoid deprecation warnings, the test case needs to live in `//lcmtypes`.)
___
*[lcmtypes/test/nested_types_test.py, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgT6bEb0rBJusUP2oei:-MgTeLsDD3O1ZiPJBjKz:b-plvz1h) ([raw file](https://github.com/robotlocomotion/drake/blob/64bcf9cdab815a37f71618d765e3f94b862ab4e8/lcmtypes/test/nested_types_test.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> we can't call pydrake from a non-unittest test.

Not sure if I understand why this is the case; is it just b/c deprecation is thrown?
(That being said, may not be important that I understand)
</blockquote></details>

It's because pydrake imports numpy which imports unittest which triggers our "you screwed up your unit-testing-main" linter.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgakJ8SEZSnsRWTzWAI:-MgakJ8T8xlAgqwDs_8o:b3oqj84) (no related file):*
Working

Needs nanual testing for
* installed deltas,
* Anzu warnings,
* drake-visualizer in Drake, 
* drake-visualizer in Anzu, and
* drake-external-examples.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgakJ8SEZSnsRWTzWAI:-Mgbr9f963chwNRVsG1L:b43h8tp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs nanual testing for
* installed deltas,
* Anzu warnings,
* drake-visualizer in Drake, 
* drake-visualizer in Anzu, and
* drake-external-examples.
</blockquote></details>

Testing in Anzu shows problem with shared library paths for the shims (ala #4594).  Given that, and the other headaches associated with having native code behind `import drake.lcmt_foo`, my plan now is to open a new PR that removes native code from a vanilla `import pydrake` as a first step, and then return to this PR.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgakJ8SEZSnsRWTzWAI:-MgcZLs95EnNgXs5QnMO:b-t4lv55) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Testing in Anzu shows problem with shared library paths for the shims (ala #4594).  Given that, and the other headaches associated with having native code behind `import drake.lcmt_foo`, my plan now is to open a new PR that removes native code from a vanilla `import pydrake` as a first step, and then return to this PR.
</blockquote></details>

I've pushed that change in #15585 (and rebased it into here).  We can hold off more review here until the other PR lands first.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MgakJ8SEZSnsRWTzWAI:-MggtHKi4lXRrVWDgrG0:b-bu12t5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I've pushed that change in #15585 (and rebased it into here).  We can hold off more review here until the other PR lands first.
</blockquote></details>

The native code fix has merged.  Still need to re-do my manual testing here.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @EricCousineau-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-Mh-EXsiAlmfLke2PtJC:-Mh-EXsiAlmfLke2PtJD:bwml7vs) (no related file):*
Working

Ugh.  Consider the following message definition:


```
package anzu;

struct twist_t {
  drake.lcmt_header header;
  float linear[3];
  float angular[3];
}
```

The codegen for python will try to "import drake.lcmt_header", but of course that's the deprecated name, which will evaporate soon.  Trying to use different package names depending on the language being bound seems like a rats nest.

We may need to rethink this entire approach.

---
___
*[bindings/pydrake/BUILD.bazel, line 52 at r10](https://reviewable.io/reviews/robotlocomotion/drake/15577#-Mh-6lVPEFtT_WO4E_3B:-Mh-6lVQ5j3P-NMM5rxT:burxaib) ([raw file](https://github.com/robotlocomotion/drake/blob/6e1b7edf4778b1bb146a6ffad0a5cd68f91a6306/bindings/pydrake/BUILD.bazel#L52)):*
> ```Starlark
>         # We use `common:_init_py` to avoid dependency cycles.
>         "//bindings:bazel_workaround_4594_libdrake_py",
>         "//bindings/pydrake/common:_init_py",
> ```

Working

It's not on the critical path for this PR, but note that even though we've deferred the _runtime_ dependency on `pydrake.common`, here we still have a _build-time_ dependency, such that deps on lcmtypes still cause all of libdrake to be compiled first.  We might want to fix that, or at least add a TODO.

This patch seems to fix it, though requires more testing (and a separate PR):

```patch
--- a/bindings/pydrake/BUILD.bazel
+++ b/bindings/pydrake/BUILD.bazel
@@ -46,11 +46,9 @@ drake_py_library(
     srcs = [
         "__init__.py",
     ],
+    imports = [".."],
     deps = [
-        # We use `common:_init_py` to avoid dependency cycles.
         "//bindings:bazel_workaround_4594_libdrake_py",
-        "//bindings/pydrake/common:_init_py",
-        "//bindings/pydrake/common:deprecation_py",
     ],
 )
 
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-Mh-EXsiAlmfLke2PtJC:-Mh058R1E0PufB0whKlP:bj6ey3g) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Ugh.  Consider the following message definition:


```
package anzu;

struct twist_t {
  drake.lcmt_header header;
  float linear[3];
  float angular[3];
}
```

The codegen for python will try to "import drake.lcmt_header", but of course that's the deprecated name, which will evaporate soon.  Trying to use different package names depending on the language being bound seems like a rats nest.

We may need to rethink this entire approach.
</blockquote></details>

Nuts!
My only suggestion is to transform the generated Python code after-the-fact - e.g. `sed 's#\bdrake\b#pydrake'`, assuming that affects only the desired symbols (and I forget if the hash is still unaffected). Alternative is to transform input.
But that's probably the rat's nest you're referring to.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15577)* status: 6 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[lcmtypes/drake/__init__.py, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MhOPv7f1c2W8FyM4h9-:-MhOPv7f1c2W8FyM4h90:b-xw5iq) ([raw file](https://github.com/robotlocomotion/drake/blob/6e1b7edf4778b1bb146a6ffad0a5cd68f91a6306/lcmtypes/drake/__init__.py#L14)):*
> ```Python
>     " remove the BUILD dependency on @drake//lcmtypes:lcmtypes_drake_py."
>     " The old module will be removed from Drake on or after 2021-12-01.",
>     category=DeprecationWarning)
> ```

nit Can you mention why we don't use `DrakeDeprecationWarning` here?
(import / dependencies, I assume?)
___
*[lcmtypes/test/acceptance_test.py, line 6 at r10](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MhOPKc4Eihd8eSQJov9:-MhOPKc4Eihd8eSQJovA:bysxfry) ([raw file](https://github.com/robotlocomotion/drake/blob/6e1b7edf4778b1bb146a6ffad0a5cd68f91a6306/lcmtypes/test/acceptance_test.py#L6)):*
> ```Python
> import pydrake.lcmtypes
> 
> # TODO(jwnimmer-tri) When deprecated drake.lcmt_foo is removed on or after
> ```

nit Why not use `catch_drake_warnings`?

(if there's a reason, such as import ordering, can you mention it here?)
___
*[lcmtypes/test/acceptance_test.py, line 24 at r10](https://reviewable.io/reviews/robotlocomotion/drake/15577#-MhOQ5JU6hcz_V9vjfXf:-MhOQ5JU6hcz_V9vjfXg:b-86fvt1) ([raw file](https://github.com/robotlocomotion/drake/blob/6e1b7edf4778b1bb146a6ffad0a5cd68f91a6306/lcmtypes/test/acceptance_test.py#L24)):*
> ```Python
> 
>         # Confirm that the deprecated names are aliases to the new names.
>         self.assertEqual(lcmt_drake_signal, pydrake.lcmtypes.lcmt_drake_signal)
> ```

nit While `assertEqual` may do what we want here, it can be made more explicit (and more robust, just in case there's some weird metaclass override of `__eq__`).

Can you instead use `self.assertIs(a, b)`?
https://docs.python.org/3.6/library/unittest.html#unittest.TestCase.assertIs

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15577#-Mh-EXsiAlmfLke2PtJC:-Mj6-lA24W33k-M0W08h:banna1o) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Nuts!
My only suggestion is to transform the generated Python code after-the-fact - e.g. `sed 's#\bdrake\b#pydrake'`, assuming that affects only the desired symbols (and I forget if the hash is still unaffected). Alternative is to transform input.
But that's probably the rat's nest you're referring to.
</blockquote></details>

Whether we transform the input or the output, either way it means that _every single user of Drake_ (not just the Anzu users) will need to re-implement that same code into their build systems.  That is a non-starter.  Drake needs to work out of the box, using stock `lcm-gen`, without those shenanigans.

---

**Comment by jwnimmer-tri** [comment]
I took another read over this PR today.  Given the problems with using `pydrake` as an LCM package name, I don't think there's any part of this PR that can be rescued into an incremental improvements.  I'll have to start over on a different tack.

**Pull request closed without merging**
