### PR TITLE
Factor out MakeGeometryData.

### PR DESCRIPTION
**Pull request by david-german-tri**
We're going to reuse it in code that sends aggregated poses to DrakeVisualizer without reference to RigidBodyTree.

@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5170)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: Just some BTW comments.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/rendering/drake_visualizer_client.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2exlnyOKe2Oe2cqIc:-Kd2dJVjwA9nHqFsJrLi:b-pdxtop) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/drake_visualizer_client.h#L6)):*
> ```objc
> #include "drake/multibody/shapes/visual_element.h"
> 
> /// @file Utilities for implementing the Drake Visualizer Interface.
> ```

BTW, is it well know what is the "Drake Visualizer Interface"? Is it the communication protocol between Drake and its `drake-visualizer`?

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2elWJZUFAIPKc_zTb:-Kd2elWJZUFAIPKc_zTc:b-fev7u6) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L1)):*
> ```cpp
> #include "drake/systems/rendering/drake_visualizer_client.h"
> ```

BTW, I see this unit test only covers two of the five possible geometry shapes (box and mesh). Was this intentional?

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2eZSnmBZTjn2aWpQc:-Kd2eZSo2C2q88EPsop_:b-7xiz1r) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L37)):*
> ```cpp
> 
> TEST_F(MakeGeometryDataTest, Box) {
>   DrakeShapes::VisualElement box(
> ```

BTW, consider making this `const`.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2ecALUAlKOxxZfKiJ:-Kd2ecALUAlKOxxZfKiK:b-7xiz1r) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L57)):*
> ```cpp
>   const std::string kFileName = drake::GetDrakePath() +
>       "/multibody/shapes/test/quad_cube.obj";
>   DrakeShapes::VisualElement mesh(
> ```

BTW, consider making this `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-:-Kd2fP9mdnO_gK8lG3FH:bhmra2g)*

**Comment by david-german-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/rendering/drake_visualizer_client.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2exlnyOKe2Oe2cqIc:-Kd6RpwFiu6Jv99KUTIj:b1u1nl2) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/drake_visualizer_client.h#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is it well know what is the "Drake Visualizer Interface"? Is it the communication protocol between Drake and its `drake-visualizer`?
</blockquote></details>

Done.  Added some clarifying text.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2elWJZUFAIPKc_zTb:-Kd6TEewULNmLzmRYRdD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I see this unit test only covers two of the five possible geometry shapes (box and mesh). Was this intentional?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2eZSnmBZTjn2aWpQc:-Kd6RxtwQxGdBKjqO0ci:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider making this `const`.
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd2ecALUAlKOxxZfKiJ:-Kd6RyMJBw3p3OfqLDgA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59d0e8dbc03d16c78cb2dab55ebd44caec1f85de/drake/systems/rendering/test/drake_visualizer_client_test.cc#L57)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider making this `const`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170)*

**Comment by david-german-tri** [comment]
+@ggould-tri +@soonho-tri for platform review.

---

Review status: 8 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-:-Kd6TJKNYQgbaY_wVQfW:b-cxoxdr)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170)*

**Comment by soonho-tri** [comment]
:lgtm: (just a few formatting issues)

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/drake_visualizer_client.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6iW0AEsEqlwfBZp9h:-Kd6iW0AEsEqlwfBZp9i:bwri3nd) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/drake_visualizer_client.cc#L39)):*
> ```cpp
>       auto cylinder = dynamic_cast<const DrakeShapes::Cylinder&>(geometry);
>       geometry_data.float_data.push_back(static_cast<float>(
>                                              cylinder.radius));
> ```

META : this can be fit into a single line. Please consider using clang-format.

---

*[drake/systems/rendering/drake_visualizer_client.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6iaKz72n_DVlmQg4p:-Kd6iaKz72n_DVlmQg4q:b-aa1ubv) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/drake_visualizer_client.cc#L81)):*
> ```cpp
>   // specified in the body's frame.
>   Eigen::Isometry3d transform = visual_element.getLocalTransform();
>   Eigen::Map <Eigen::Vector3f> position(geometry_data.position);
> ```

META : unnecessary space between `Eigen::Map` and `<Eigen::Vector3f>`. Please consider using clang-format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-:-Kd6mg4ghDKB_0_fjLpN:b-kyvuwa)*

**Comment by ggould-tri** [comment]
I concur with @soonho-tri on all files except the test; I have some additional comments about the test file.  :lgtm: once discussions are resolved.

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6wue6h_EaFkGR7LgZ:-Kd6wue7PQ5uBXg6H32j:b-d0ybi2) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L18)):*
> ```cpp
>   /// Expects that the position and quaternion in the given @p geometry_data
>   /// are an identity transform, and the color is a vector of ones.
>   static void ExpectPositionQuaternionAndColor(
> ```

BTW -- "ExpectStuff" is a surprising name for a method that checks that Stuff has a particular value.  Consider "Verify" or "Validate" as less surprising verbs.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6xP8eyhtrWuRnxCgr:-Kd6xP8fTZSW7rStteD8:b2o2rsn) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L20)):*
> ```cpp
>   static void ExpectPositionQuaternionAndColor(
>       const lcmt_viewer_geometry_data& geometry_data) {
>     for (int i = 0; i < 3; ++i) {
> ```

BTW -- can this and the following loops be rewritten in range-based style?

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 84 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6yFZoZUMD0EeGBmAt:-Kd6yFZpKOfnE_X17qwU:bnb7ycu) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L84)):*
> ```cpp
>   ASSERT_EQ(2, geometry_data.num_float_data);
>   EXPECT_EQ(radius, geometry_data.float_data[0]);
>   EXPECT_EQ(length, geometry_data.float_data[1]);
> ```

Rule-of-three on "this circumlocution".  Please factor if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-:-Kd6yRvOfjPR2pv43SY0:bfsgk4u)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/drake_visualizer_client.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6iW0AEsEqlwfBZp9h:-Kd7vCz4zQIiCbDTDlkv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/drake_visualizer_client.cc#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META : this can be fit into a single line. Please consider using clang-format.
</blockquote></details>

Done.

---

*[drake/systems/rendering/drake_visualizer_client.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6iaKz72n_DVlmQg4p:-Kd7vL_JqsXpaCp0xzAT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/drake_visualizer_client.cc#L81)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META : unnecessary space between `Eigen::Map` and `<Eigen::Vector3f>`. Please consider using clang-format.
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6wue6h_EaFkGR7LgZ:-Kd7vVRLLhewcqwPEi0z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L18)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- "ExpectStuff" is a surprising name for a method that checks that Stuff has a particular value.  Consider "Verify" or "Validate" as less surprising verbs.
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6xP8eyhtrWuRnxCgr:-Kd7vViqXXaeeD-sNow9:bm4nkm0) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- can this and the following loops be rewritten in range-based style?
</blockquote></details>

I don't think so; it's a C array.  (Thanks, LCM!)

---

*[drake/systems/rendering/test/drake_visualizer_client_test.cc, line 84 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd6yFZoZUMD0EeGBmAt:-Kd7wOzLBWqVWBU6_bQP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35830e97ad8d648ca6c678bb4a5d1626f239e0d7/drake/systems/rendering/test/drake_visualizer_client_test.cc#L84)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Rule-of-three on "this circumlocution".  Please factor if possible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170)*

**Comment by liangfok** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/CMakeLists.txt, line 37 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5170#-Kd8CPlal6Up3DmGp3z_:-Kd8CPlb2Q4KuiFOo-zJ:b-fz4o4h) ([raw file](https://github.com/robotlocomotion/drake/blob/f9046162ed63bebc4980185d76fc9975f515670c/drake/multibody/rigid_body_plant/CMakeLists.txt#L37)):*
> ```CMake
>   set(lcm_dependent_link_libraries
>     drakeLcmSystem
>     drakeSystemPrimitives
> ```

BTW, consider alpha sorting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5170)*

**Pull request merged**
