### PR TITLE
Adding dualshock4 teleoperation example to manipulation station.

### PR DESCRIPTION
**Pull request by darshanhegde**
Adds dualshock4 controller teleoperation support to manuplation station example. 

Here is the video of controlling the KUKA IIWA arm using dualshock 4 controller: https://www.youtube.com/watch?v=pVDcHKvvr_4

I'm assuming that the dualshock 4 controller is connected to your linux machine.

Uses pygame for interfacing with the dualshock 4 controller and the button mapping to end-effector command follows MoveIt! teleoperation conventions: https://ros-planning.github.io/moveit_tutorials/doc/joystick_control_teleoperation/joystick_control_teleoperation_tutorial.html#joystick-command-mappings

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13570)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
> Eric, you can self-assign when the right direction is clear.

FTR I think this would be great to have either here or in a demo repo. I'm hoping that my comments are helpful, regardless of where it lives (and hopefully not too annoying!)

**Comment by jwnimmer-tri** [comment]
___
*[examples/manipulation_station/end_effector_teleop_dualshock4.py, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13570#-MA7A7FT9SIV293_vItZ:-MA7EhNDDY1Lp4JR2KMH:b4zhlmb) ([raw file](https://github.com/robotlocomotion/drake/blob/44da09f9c1c362cf5384cff0cf6ddd2b3bd9cd4a/examples/manipulation_station/end_effector_teleop_dualshock4.py#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than try importing `pygame`, can you instead just fail fast (or just exist early)?
</blockquote></details>

This is copying existing precedent:

https://github.com/RobotLocomotion/drake/blob/46903f35a2b12c09e61c85832cf3a8e32612af9a/examples/manipulation_station/end_effector_teleop_mouse.py#L23-L35

Your comment is a suggested change.  What is the underlying defect?

**Comment by darshanhegde** [comment]
Thanks for the comments @EricCousineau-TRI and @jwnimmer-tri After I address the comments, do we merge in the present location or I have to do any refactor to remove the code duplication. I'm happy to do that as well, so that there is less duplication.

**Comment by jwnimmer-tri** [comment]
I'll defer to @EricCousineau-TRI.

**Comment by darshanhegde** [comment]
Also, do you have python linters for drake ? I can run them and fix any errors. Btw, seems like for each type of control `_mouse` / `_slider` / `_dualshock4` there are separate files for `end_effector_teleop_*` with a lot of code common to them. If we just put the Teleop leafsystem in their own files and just take in the controller as commandline argument, we can remove a lot of code duplication between these 3 files. I can do that refactor as part of this, if you think it's worth doing.

**Comment by jwnimmer-tri** [comment]
For the linters, running a `bazel test //examples/manipulation_station/...` will run all of the `manipulation_station` tests, including all of the linters for all of its code.  To run _only_ the linters, run `bazel test --config lint //examples/manipulation_station/...`.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

@EricCousineau-TRI ping -- the review needs your replies.

**Comment by darshanhegde** [comment]
Also, CI seems to be failing with 
```
Exception: Make sure dualshock 4 controller is connected. Controller initialization failed with: Invalid joystick device number
```

Since the device is not connected during the test build.

**Comment by darshanhegde** [comment]
> That's a good point! I think for this PR, though, I think it's good as-is.
> If you have time (and interest) in doing the refactoring, that'd be great! If not, no worries!

Yeah, I can take a stab at this over the weekend.

**Comment by darshanhegde** [comment]
Thank you @EricCousineau-TRI / @RussTedrake / @jwnimmer-tri  for your reviews and help :)

**Pull request merged**
