### PR TITLE
Tidy up some Doxygen grouping in automotive

### LINKED ISSUE #5619: Organize "automotive systems" Doxygen overview
We should organize the "automotive systems" Doxygen overview, including the block-level descriptions and and figures for our library of systems.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5619.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6087)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6087#-:-Kjx45c_ejGf433IuZyH:bltds52)*

**Comment by liangfok** [comment]
:lgtm: I generated the Doxygen and verified the changes in this PR look good.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6087#-:-KjymHy_nIlUl03jZoYW:b-kohjrm)*

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for platform review, please.

**Comment by RussTedrake** [comment]
Very nice.  :lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6087#-:-Kk2mUygInaj9VFKWyXQ:bi7yem0)*

**Pull request merged**
