### PR TITLE
Assorted improvements to automotive_demo.py

### PR DESCRIPTION
**Pull request by rpoyner-tri**
- Add options to skip visualizer launch.
- Improve error handling.
- Add some .gitignore love.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3597)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@sammy-tri for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSfnfKTvltWMGYqLq_M:b-1h8soq)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSgM4VwoAJUO75zDse6:bnfp4nl)*

**Comment by liangfok** [comment]
Just one question.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/automotive/automotive_demo.py, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-KSgMWq51-3l_jhMEJr9:-KSgMWq51-3l_jhMEJrA:btmk61h) ([raw file](https://github.com/robotlocomotion/drake/blob/ba08512cf4e72c411830780dca3c7d85eaf2d459/drake/automotive/automotive_demo.py#L186)):*
> ```Python
>                         dest='launch_visualizer',
>                         default=True, help="launch drake-visualizer (default)")
>     parser.add_argument("--no-visualizer", action='store_false',
> ```

It's interesting that _two_ flags are provided one to enable Drake Visualizer and another to disable it. Doesn't this unnecessarily invite trouble when someone tries to include _both_ flags simultaneously? Why not collapse it into a single flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSgMuML6nLNU0Eoznhp:b-w58e4h)*

**Comment by liangfok** [comment]
+@liangfok because I'm nosy :smile: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSgN5KGmapU1-VztxrR:b-wosncv)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-KSgMWq51-3l_jhMEJr9:-KSgcCPFU33h3qU2Bc9H:bea3wu6) ([raw file](https://github.com/robotlocomotion/drake/blob/ba08512cf4e72c411830780dca3c7d85eaf2d459/drake/automotive/automotive_demo.py#L186)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> It's interesting that _two_ flags are provided one to enable Drake Visualizer and another to disable it. Doesn't this unnecessarily invite trouble when someone tries to include _both_ flags simultaneously? Why not collapse it into a single flag?
</details>
What trouble? If you include both, the second one wins. This is exactly the semantics of say, gcc.

You *could* do a single flag taking an argument, but it just makes the string you type more abstract: --visualizer=false.

Also, the design presented here allows the default to be changed easily without respelling the flags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSgpQKBWuIgwGWtJ7Lh:bcpz082)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-KSgMWq51-3l_jhMEJr9:-KSgtXH5nKVpukiQLXEL:b1rzfip) ([raw file](https://github.com/robotlocomotion/drake/blob/ba08512cf4e72c411830780dca3c7d85eaf2d459/drake/automotive/automotive_demo.py#L186)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> What trouble? If you include both, the second one wins. This is exactly the semantics of say, gcc.
> 
> You *could* do a single flag taking an argument, but it just makes the string you type more abstract: --visualizer=false.
> 
> Also, the design presented here allows the default to be changed easily without respelling the flags.
</details>
OK. SGTM. I was not aware of the fact that `gcc` uses such confusing flags. Oh well, I suppose I'll leave this to your discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/automotive_demo.py, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-KSgMWq51-3l_jhMEJr9:-KSguMaYybbJ1ZClx_EB:b9daxlt) ([raw file](https://github.com/robotlocomotion/drake/blob/ba08512cf4e72c411830780dca3c7d85eaf2d459/drake/automotive/automotive_demo.py#L186)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK. SGTM. I was not aware of the fact that `gcc` uses such confusing flags. Oh well, I suppose I'll leave this to your discretion.
</details>
requires your :LGTM: for merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3597#-:-KSgus-A01Q6D5urJNRG:bnfp4nl)*

**Pull request merged**
