### PR TITLE
fix dd test

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review please. In short there is no linear cost that can avoid the multiple solutions in the polytope provided, so instead I just check that the expect solution is feasible and achieves the same cost.

cc @cohnt and @jwnimmer-tri from slack discussion

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-:-Niejh87306miyP7P0QC:bvatlhi)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  thanks for the fix

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-:-NihA6cA-ep6s6U9yMvC:b9hun0p)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/test/diagonally_dominant_matrix_test.cc` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-Nih9yrh93eE65mWL4DA:-Nih9yri2RHwP9D1qS0z:b-88muhg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b8e141075ddd796dd55a67a28fcc6cac2b01063d/solvers/test/diagonally_dominant_matrix_test.cc#L123)):*
> ```cpp
> 
>       // The matrix should be positive semidefinite.
>       const Eigen::Matrix3d X_sol = result_expected.GetSolution(X);
> ```

I think we still want to use `result.GetSolution(X)` here to check if "X is psd" is satisfied.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-:-NihAaunDwSqM1Rhh6Rs:buer3go)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`solvers/test/diagonally_dominant_matrix_test.cc` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-Nih9yrh93eE65mWL4DA:-Nijl6dkDcRkyGEzSU2r:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b8e141075ddd796dd55a67a28fcc6cac2b01063d/solvers/test/diagonally_dominant_matrix_test.cc#L123)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think we still want to use `result.GetSolution(X)` here to check if "X is psd" is satisfied.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`solvers/test/diagonally_dominant_matrix_test.cc` line 119 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-Nik9Smt9ejW8Zrm9jBg:-NikFZ_k-g8DeUhlT2gU:b-lawkie) ([raw file](https://github.com/RobotLocomotion/drake/blob/33ca42b146a1c8bffce93acc5d5859eafd3386b3/solvers/test/diagonally_dominant_matrix_test.cc#L119)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why the change from the passed-in `tol` to fixed 1e-8 here? If that's intentional, please add a comment explaining why tol is used below but not here.
</blockquote></details>

Good catch. The cost tolerance should in general be lower than the tolerance used to check if a matrix is PSD, so I added arguments.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/test/diagonally_dominant_matrix_test.cc` line 140 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20493#-NikIFJj2da4YRae2nyy:-NikIFJj2da4YRae2nyz:b-1t8jku) ([raw file](https://github.com/RobotLocomotion/drake/blob/558c7e1eafc08f15572258acc4fbf6b90542ed63/solvers/test/diagonally_dominant_matrix_test.cc#L140)):*
> ```cpp
> 
>   const double psd_tol{1E-6};
>   const double cost_equality_tol{1E-8};
> ```

FYI (feel free to ignore) You could simplify this and avoid duplication by moving these two constant declarations into the lambda and removing the arguments.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20493)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Pull request merged**
