### PR TITLE
[framework] Use new ValueProducer sugar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is the next step of #15161.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15402)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review or delegation, please.

**Review by sherm1 — COMMENTED** [review]
Nice! Love the negative SLOC. :lgtm: with a few comments. 

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15402#-:-MefOFZhCMosCLeVdI7k:b-6gkl9b)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/framework/leaf_system.h, line 1426 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefLHd77JctqDeudihJ:-MefLHd77JctqDeudihK:b-8towot) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.h#L1426)):*
> ```objc
>     auto& port = CreateAbstractLeafOutputPort(
>         NextOutputPortName(std::move(name)),
>         ValueProducer(this, model_value, calc),
> ```

minor: I think there is a slight change in functionality here. Where previously `this` was cast to `MySystem* this_ptr`, here it is sent as-is to ValueProducer. The cast allowed for some base or derived class of MySystem to do the actual port allocation. Since Drake compiled I presume that wasn't being used though. Consider preserving the old functionality?
___
*[systems/framework/leaf_system.h, line 1491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefMZNc-JD-FXJSCBPN:-MefMZNd7guy-W5qFZc3:b-ip1wxd) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.h#L1491)):*
> ```objc
>     auto& port = CreateAbstractLeafOutputPort(
>         NextOutputPortName(std::move(name)),
>         ValueProducer(this, std::move(allocate), calc),
> ```

minor: here the cast to `MySystem*` is used to feed `this_ptr` to the allocator, but the original `this` (of possibly different type) is used for ValueProducer. I'm not sure if that has any consequences but it's not obvious to me why `this_ptr` wouldn't be preferable for use in both places?
___
*[systems/framework/leaf_system.cc, line 695 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefNbGF-7_15xVO12Ds:-MefNbGF-7_15xVO12Dt:bwvvrln) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.cc#L695)):*
> ```cpp
>     const Context<T>& context = dynamic_cast<const Context<T>&>(context_base);
>     return captured_calc(context, result);
>   };
> ```

BTW could this be done instead just with `std::function<CalcCallback>(calc_function)` ?
___
*[systems/framework/system.cc, line 940 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefNwLz1FQyN9xUwDim:-MefNwLz1FQyN9xUwDin:b1vpodj) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/system.cc#L940)):*
> ```cpp
>                   this,
>                   &System<T>::AllocateTimeDerivatives,
>                   &System<T>::CalcTimeDerivatives),
> ```

BTW wow that's so much nicer!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15402)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @sherm1)

___
*[systems/framework/leaf_system.h, line 1426 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefLHd77JctqDeudihJ:-MefSP5K3iYgj7yr-6SQ:bpymgjt) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.h#L1426)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think there is a slight change in functionality here. Where previously `this` was cast to `MySystem* this_ptr`, here it is sent as-is to ValueProducer. The cast allowed for some base or derived class of MySystem to do the actual port allocation. Since Drake compiled I presume that wasn't being used though. Consider preserving the old functionality?
</blockquote></details>

I think `ValueProducer` already downcasts `this` to the class type of `calc`?  The `this` is `SomeInstance` but the `calc` class is `SomeClass`.

https://github.com/RobotLocomotion/drake/blob/v0.32.0/systems/framework/value_producer.h#L432-L441
___
*[systems/framework/leaf_system.h, line 1491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefMZNc-JD-FXJSCBPN:-MefTB6GByn3c95HvwGb:bxcbbrb) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.h#L1491)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: here the cast to `MySystem*` is used to feed `this_ptr` to the allocator, but the original `this` (of possibly different type) is used for ValueProducer. I'm not sure if that has any consequences but it's not obvious to me why `this_ptr` wouldn't be preferable for use in both places?
</blockquote></details>

Yes, that's better.
___
*[systems/framework/leaf_system.cc, line 695 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefNbGF-7_15xVO12Ds:-MefTYIhCR0E-joskKYD:bqw40r7) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.cc#L695)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could this be done instead just with `std::function<CalcCallback>(calc_function)` ?
</blockquote></details>

No, the signature of the `calc_function` we start from is:
```c++
void (const Context<T>&, AbstractValue*);
```

The signature supported by `ValueProducer` calc mode 5 (that we end up using below) is:
```c++
void (const ContextBase&, AbstractValue*);
```

Because we need to downcast from `ContextBase` to `Context<T>` during the call,  there is no `std::function` conversion constructor that works.  (If it were an upcast, perhaps it would work.)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15402)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[systems/framework/leaf_system.h, line 1426 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15402#-MefLHd77JctqDeudihJ:-MeffyF6DXzGXHJNnSVo:b-do1vdk) ([raw file](https://github.com/robotlocomotion/drake/blob/e015b7ce793e3dbecd45bd4d7f37c185dab72aaa/systems/framework/leaf_system.h#L1426)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think `ValueProducer` already downcasts `this` to the class type of `calc`?  The `this` is `SomeInstance` but the `calc` class is `SomeClass`.

https://github.com/RobotLocomotion/drake/blob/v0.32.0/systems/framework/value_producer.h#L432-L441
</blockquote></details>

Oh, great. I missed that. Retracted.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform - sweet!

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15402#-:-Meft43W1k4-n32PryUl:bkucxs2)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
