### PR TITLE
[workspace] Build IPOPT from source on Ubuntu

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

Also timely because we aspire to improve our `IpoptSolver` wrapper, so having the newest (and same) version on Ubuntu and macOS might aid that project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-:-NV50_jMEDQ3kHDAIBv8:blnrywe)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-NV511PE9zuTGG4F8dW8:-NV511PE9zuTGG4F8dW9:b9h8k3y) (no related file):*
Working

The macOS wheel builds are failing (because IPOPT is broken at runtime there).  I suspect the problem is due to the version upgrade, probably due to a missing build-config setting whose default changed.  I'll investigate.

In the meantime, the bulk of the changes here (Ubuntu, non-Wheel) should be ready for review.

___
___
*[`tools/workspace/ipopt_internal_pkgconfig/repository.bzl` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-NV5-RY88jNEdfZXTY_v:-NV5-RY88jNEdfZXTY_w:b4r7gw) ([raw file](https://github.com/RobotLocomotion/drake/blob/12bd922db3f49cd49892ddbc540493a2ec67e820/tools/workspace/ipopt_internal_pkgconfig/repository.bzl#L1)):*
> ```Starlark
> load(
> ```

FYI This file is renamed and lightly edited from the original `tools/workspace/ipopt/repository.bzl` on master.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-NV511PE9zuTGG4F8dW8:-NV572fO7Po3ApHyUYOr:bbpgbiy) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

The macOS wheel builds are failing (because IPOPT is broken at runtime there).  I suspect the problem is due to the version upgrade, probably due to a missing build-config setting whose default changed.  I'll investigate.

In the meantime, the bulk of the changes here (Ubuntu, non-Wheel) should be ready for review.
</blockquote></details>

Aha:

```
[6:50:10 AM]  configure: WARNING: unrecognized options: --with-mumps-lib, --with-mumps-incdir
```

Maybe fixed now in r5.

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-NV511PE9zuTGG4F8dW8:-NV5IVpr3b7Xdzn81p35:b-m5vl6d) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aha:

```
[6:50:10 AM]  configure: WARNING: unrecognized options: --with-mumps-lib, --with-mumps-incdir
```

Maybe fixed now in r5.
</blockquote></details>

Done.  The arm build passed.  I assume x86 will as well.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 23 files at r1, 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-:-NVAuoCP1GT1z3Vl9F_n:bnfp4nl)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 23 files at r1, 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19388#-:-NVBFv9q6RxQOlrVJtqz:bnfp4nl)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-address-sanitizer please

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Locally in a venv I did a final test of running the NLP tutorials notebook edited to use IPOPT, and it was fine.  That's a final smoke test, so I'll plan to merge once CI wraps up.

**Pull request merged**
