### PR TITLE
Update release details

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
While releasing v1.28.0, I encountered a couple of stale details in the documentation and automation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21302)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@mwoehlke-kitware for feature review, please.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21302#-:-NvJJy50E_IJyQTnwHM4:b7l6qvf)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
I pushed a related fix to version numbering that slipped through the cracks in weeks past.

:lgtm: platform.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21302#-:-NvJO3kP2MxUR3dLc0TU:b-a9p4t8)* status: LGTM missing from assignee mwoehlke-kitware, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21302#-:-NvXPZNw47Lk1sbc0XUh:bg7igkv)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21302)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Pull request merged**
