### PR TITLE
Implements a simple system that logs its inputs to memory ...

### PR DESCRIPTION
**Pull request by RussTedrake**
which can be retreived after a simulation.  Simplest (but incomplete) workaround to #3734.

Also fixes a few bugs/style issues in other places, including:
- simulator was not counting publish events
- affine system was allocating input/output ports even if their dimension was zero (thereby requiring users to attach an empty port to use the system)
- eigen_matrix_compare was printing out rows x rows !!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4257)

### CODE REVIEW

**Comment by liangfok** [comment]
I left some comments after a quick skim. Thanks for adding the `SignalLogger`!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW2iA02icHx4Lek2WW:-KXW2iA1PufbRB8C92SR:bf0oios) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/analysis/simulator.h#L342)):*
> ```objc
>   // Do a publish before the simulation starts.
>   system_.Publish(*context_);
>   ++num_publishes_;
> ```

BTW, to reduce code duplication and prevent forgetting to update the `num_publishes_` counter, consider pulling out the following two lines of code into a helper method:

```
system_.Publish(*context_);
++num_publishes_;
```

---

*[drake/systems/framework/primitives/signal_logger.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWCJN92NK1peIHa58k:-KXWCJNAhM3lnc9gU8et:b-h9jvn) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.cc#L16)):*
> ```cpp
>   DRAKE_DEMAND(input_size >= 0);
>   this->DeclareInputPort(kVectorValued, input_size, kInherited);
>   DRAKE_DEMAND(batch_allocation_size_ >= 0);
> ```

BTW, just wanted to confirm that it makes sense for `input_size` and `batch_allocation_size` to potentially be zero.

---

*[drake/systems/framework/primitives/signal_logger.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW59H3jqOw3eHFq_7F:-KXW59H4n9_GFYIPR397:b-b78ip1) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L25)):*
> ```objc
>   /// @param input_size Dimension of the (single) input port.
>   /// @param batch_allocation_size Storage is (re)allocated in blocks of
>   /// input_size-by-batch_allocation_size.
> ```

The above might clearer using: `input_size * batch_allocation_size`. Upon first glance, I didn't catch the fact that "-by-" meant "multiply".

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW5aAm4v5NTWmxzC-B:-KXW5aAm4v5NTWmxzC-C:b-cnknv7) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L34)):*
> ```objc
>   /// No output.
>   void EvalOutput(const Context<T>& context,
>                   SystemOutput<T>* output) const override{};
> ```

There needs to be a space before `{}` per style guide (this is enforced by `clang-format`).

---

*[drake/systems/framework/primitives/signal_logger.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWAe6BW7FA1Jp3fUsc:-KXWAe6BW7FA1Jp3fUsd:b63hm6o) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L36)):*
> ```objc
>                   SystemOutput<T>* output) const override{};
> 
>   /// Accessor methods for the logged data.
> ```

When rendered in Doxygen, this comment will only appear with `samples_times()`.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWA6z_Brv1WhaRKMV4:-KXWA6z_Brv1WhaRKMV5:b-zhsbjk) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L37)):*
> ```objc
> 
>   /// Accessor methods for the logged data.
>   const Eigen::VectorBlock<VectorX<T>> sample_times(void) const {
> ```

BTW, I'm not sure if it's against the style guide, but I believe the `void` is unnecessary. (Same comment below regarding `data()`.)

---

*[drake/systems/framework/primitives/signal_logger.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWBL8hfrZ5IBB5t2ep:-KXWBL8iQ782o9OzOSVz:b-wnfe7i) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L40)):*
> ```objc
>     return sample_times_.head(num_samples_);
>   }
>   const Eigen::Block<MatrixX<T>, Eigen::Dynamic, Eigen::Dynamic, true> data(
> ```

BTW, I believe we've typically been separating two method implementations by a blank line.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWDhtiDIZjRrRFTgt5:-KXWDhtiDIZjRrRFTgt6:b9nh8x6) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/test/affine_system_test.cc#L1)):*
> ```cpp
> 
> ```

Extra blank line?

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWDflN6xF9OETSAedK:-KXWDflOvBQw6oDxCBmL:b-4h0rp3) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/test/affine_system_test.cc#L3)):*
> ```cpp
> 
> #include "drake/systems/framework/primitives/affine_system.h"
> #include "drake/common/eigen_matrix_compare.h"
> ```

Alpha sort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXWEyzrW-B-Uul2juIW:bfskuwo)*

**Comment by siyuanfeng-tri** [comment]
Thanks Russ! This is great . A few meta comments:
Add an optional map<std::string, int> for trace name?
Might add an optional flag to disable resizing, and make it a ring buffer in that case. 
Have multiple sources? Or have a top level thing that manages / synchronizes different sources. 

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXXGEPr3JFUoskRHHrS:b-idc832)*

**Comment by RussTedrake** [comment]
FWIW - my primary use case right now is plotting the results of the (entire) simulation.  

I've been using multiple loggers instead of multiple sources on one logger.  Related: imho, the trace name doesn't seem obviously needed -- the caller keeps a pointer to the logger and (only) accesses the data that way.

I like the ring buffer idea.  Would want to handle that correctly in the accessor methods, too.  

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXXIqXWTFaoBmJhGAvy:b-d7068b)*

**Comment by RussTedrake** [comment]
Review status: 8 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW2iA02icHx4Lek2WW:-KXXKL7VlXsCM-5-aDji:b-7c4dyp) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/analysis/simulator.h#L342)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, to reduce code duplication and prevent forgetting to update the `num_publishes_` counter, consider pulling out the following two lines of code into a helper method:
> 
> ```
> system_.Publish(*context_);
> ++num_publishes_;
> ```
</details>
fwiw - i have a unit test that provides coverage on this.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWCJN92NK1peIHa58k:-KXb2elTKvm4B_JTvaIG:beupsst) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.cc#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, just wanted to confirm that it makes sense for `input_size` and `batch_allocation_size` to potentially be zero.
</details>
good call.  changed to > for both.  

---

*[drake/systems/framework/primitives/signal_logger.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW59H3jqOw3eHFq_7F:-KXb2nSEF7UI-jlibiti:b-ygoyh5) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The above might clearer using: `input_size * batch_allocation_size`. Upon first glance, I didn't catch the fact that "-by-" meant "multiply".
</details>
but it's allocating a matrix with input_size rows and batch_allocation_size columns.

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW5aAm4v5NTWmxzC-B:-KXb35wgMFct4wt5-ow7:b-izr99p) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a space before `{}` per style guide (this is enforced by `clang-format`).
</details>
done.  but fwiw clang-format didn't get it, nor did cpplint.

---

*[drake/systems/framework/primitives/signal_logger.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWAe6BW7FA1Jp3fUsc:-KXb3PbkSIxcXKOSn68a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L36)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> When rendered in Doxygen, this comment will only appear with `samples_times()`.
</details>
Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWA6z_Brv1WhaRKMV4:-KXb3SAPsAuR7KFbSNXI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I'm not sure if it's against the style guide, but I believe the `void` is unnecessary. (Same comment below regarding `data()`.)
</details>
Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWBL8hfrZ5IBB5t2ep:-KXb3YWh2P7-Cht5w9rO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L40)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I believe we've typically been separating two method implementations by a blank line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by RussTedrake** [comment]
Review status: 7 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWDhtiDIZjRrRFTgt5:-KXb483r4pB0ZmcZswJy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/test/affine_system_test.cc#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Extra blank line?
</details>
Done.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXWDflN6xF9OETSAedK:-KXb4CfM-Ouuz78e_uVS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/test/affine_system_test.cc#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Alpha sort.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by sherm1** [comment]
+@sherm1 for platform review. Some comments below, PTAL.

---

Reviewed 5 of 10 files at r1, 2 of 3 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXchg04O3FDuBces-JA:-KXchg04O3FDuBces-JB:b-5k3pm1) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.cc#L27)):*
> ```cpp
> 
>   // If num_samples exceeds the current allocation, then do a conservative
>   // resize (ouch!).
> ```

BTW, agreed -- ouch! As written this has `O(n^2)` complexity for
`n >> batch_allocation_size`. Consider using a strategy like `std::vector` does instead -- roughly, double the buffer size whenever you are forced to reallocate it. That gives an amortized `O(n)` complexity instead. You could use `batch_allocation_size` as the initial allocation (like `std::vector::reserve()`.

---

*[drake/systems/framework/primitives/signal_logger.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfOJYKDp5wbgHi5ES:-KXcfOJYKDp5wbgHi5ET:bw6c42e) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L23)):*
> ```objc
> class SignalLogger : public LeafSystem<T> {
>  public:
>   /// @param input_size Dimension of the (single) input port.
> ```

BTW this method needs a sentence before the first `@param` to serve as a brief.

---

*[drake/systems/framework/primitives/signal_logger.h, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfZ42KkI_vqKXDdDh:-KXcfZ42KkI_vqKXDdDi:bcofnqt) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L28)):*
> ```objc
>   explicit SignalLogger(int input_size, int batch_allocation_size = 1000);
> 
>   /// Non-copyable.
> ```

BTW, I believe this should be a `//` comment.

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfmKbJ3OTxMcvtR2a:-KXcfmKcoyxmeVHSJJ-r:b6il3y9) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L34)):*
> ```objc
>   /// No output.
>   void EvalOutput(const Context<T>& context,
>                   SystemOutput<T>* output) const override{};
> ```

BTW, needs a space before `{}` and has a spurious semicolon afterwards.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgVqS-XhnP1PSy-71:-KXcgVqS-XhnP1PSy-72:bgfnl) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L37)):*
> ```objc
> 
>   /// Access the (simulation) time of the logged data.
>   const Eigen::VectorBlock<VectorX<T>> sample_times() const {
> ```

Assuming you don't want the sample times mutable, the return type here should be `Eigen::VectorBlock<const VectorX<T>>` (note placement of `const`). As written the `VectorBlock` is const, but still provides mutable access.

---

*[drake/systems/framework/primitives/signal_logger.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgxL5Vp56lcaNW0hT:-KXcgxL5Vp56lcaNW0hU:bspj71h) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L42)):*
> ```objc
> 
>   /// Access the logged data.
>   const Eigen::Block<MatrixX<T>, Eigen::Dynamic, Eigen::Dynamic, true> data()
> ```

Same comment here about `const` placement -- `const MatrixX<T>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXcj9Mho9r4XVw1Lo6w:b83prsq)*

**Comment by sherm1** [comment]
Reviewed 2 of 10 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW5aAm4v5NTWmxzC-B:-KXd3Mh0FVJzVFzgOxni:b-40i5mr) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

done.  but fwiw clang-format didn't get it, nor did cpplint.
</blockquote></details>

Interesting. I tested this and the reason `clang-format` did not catch this is because of the extraneous `;`!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXchg04O3FDuBces-JA:-KXeiMS_5sabVN98D0hR:buf76pv) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, agreed -- ouch! As written this has `O(n^2)` complexity for
`n >> batch_allocation_size`. Consider using a strategy like `std::vector` does instead -- roughly, double the buffer size whenever you are forced to reallocate it. That gives an amortized `O(n)` complexity instead. You could use `batch_allocation_size` as the initial allocation (like `std::vector::reserve()`.
</blockquote></details>

Out of curiosity, why n^2.  malloc + memcpy should be 2n ... so O(n), no?  Would prefer to get this in and worry about efficiency in a future PR unless it will change the API.

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXW5aAm4v5NTWmxzC-B:-KXek0WIpQ1G4a0h0UWI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/76db641573042d8d2602665cd2a5f8421880c359/drake/systems/framework/primitives/signal_logger.h#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Interesting. I tested this and the reason `clang-format` did not catch this is because of the extraneous `;`!
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfOJYKDp5wbgHi5ES:-KXejuGRVLyK-yfcHh78:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this method needs a sentence before the first `@param` to serve as a brief.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfZ42KkI_vqKXDdDh:-KXejuwfz-sztNueJ36E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I believe this should be a `//` comment.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcfmKbJ3OTxMcvtR2a:-KXejzZKOTRix-W04wrW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, needs a space before `{}` and has a spurious semicolon afterwards.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgVqS-XhnP1PSy-71:-KXekHzkY3LB4ABG8_9N:b8ui632) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Assuming you don't want the sample times mutable, the return type here should be `Eigen::VectorBlock<const VectorX<T>>` (note placement of `const`). As written the `VectorBlock` is const, but still provides mutable access.
</blockquote></details>

i actually had spent time trying that, but it does not compile. just reproduced:
/Users/russt/drake-distro/drake/systems/framework/primitives/signal_logger.h:39:12: No viable conversion from returned value of type 'VectorBlock<Matrix<[6 * ...]>>' to function return type 'const VectorBlock<const Matrix<[6 * ...]>>'

---

*[drake/systems/framework/primitives/signal_logger.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgxL5Vp56lcaNW0hT:-KXekHbSp2cgHH9dF0kx:bqinvlo) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Same comment here about `const` placement -- `const MatrixX<T>`.
</blockquote></details>

(and same compile error)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by RussTedrake** [comment]
Review status: 9 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXchg04O3FDuBces-JA:-KXfauBpVS4JZa8UQs4_:b-qg8l0l) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.cc#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Out of curiosity, why n^2.  malloc + memcpy should be 2n ... so O(n), no?  Would prefer to get this in and worry about efficiency in a future PR unless it will change the API.
</blockquote></details>

facepalm.  realized 30 seconds after leaving the keyboard that it happens O(n) times over the lifetime of a simulation.  

i agree it would be better to use std::vector and do the copy on (first) data access.  but would still like to do that in the next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.h, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXfijvKgEUeqye_UDiX:-KXfijvLVqyXbWgyc5_J:b-91qvgp) ([raw file](https://github.com/robotlocomotion/drake/blob/d16919589281cf7e47c61b33793cb971e7719159/drake/systems/framework/primitives/signal_logger.h#L23)):*
> ```objc
> class SignalLogger : public LeafSystem<T> {
>  public:
>   /// Construct the signal logger system.
> ```

"Construct" should be "Constructs" per style guide. (I would be happy to direct-edit this PR if you prefer.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by RussTedrake** [comment]
Review status: 9 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.h, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXfijvKgEUeqye_UDiX:-KXgCag4AOBqwfrVLJqa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d16919589281cf7e47c61b33793cb971e7719159/drake/systems/framework/primitives/signal_logger.h#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"Construct" should be "Constructs" per style guide. (I would be happy to direct-edit this PR if you prefer.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXgDKR7zqr_LErpUe6Y:bnfp4nl)*

**Comment by sherm1** [comment]
PTAL comment below about the const VectorBlocks. I linked to an example that works -- please see if that helps. Either way, :lgtm: and my comments are non-blocking.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXchg04O3FDuBces-JA:-KXid_DveE0WuQ1nhSM0:b-g3akjz) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.cc#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

facepalm.  realized 30 seconds after leaving the keyboard that it happens O(n) times over the lifetime of a simulation.  

i agree it would be better to use std::vector and do the copy on (first) data access.  but would still like to do that in the next PR.
</blockquote></details>

OK. I'm fine with leaving this until it is a problem -- please consider filing an issue so we don't forget it.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgVqS-XhnP1PSy-71:-KXif8JY4W163UKE_S81:b-5nekn4) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i actually had spent time trying that, but it does not compile. just reproduced:
/Users/russt/drake-distro/drake/systems/framework/primitives/signal_logger.h:39:12: No viable conversion from returned value of type 'VectorBlock<Matrix<[6 * ...]>>' to function return type 'const VectorBlock<const Matrix<[6 * ...]>>'

</blockquote></details>

I'm trying to figure out how this differs from [BasicVector::get_value()](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/basic_vector.h#L62) which appears to do exactly the same thing. The only obvious difference is the `const VectorBlock` return. Have you tried:
```c++
Eigen::VectorBlock<VectorX<T>> sample_times() const { ... }
```
?

---

*[drake/systems/framework/primitives/signal_logger.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgxL5Vp56lcaNW0hT:-KXigEyempOmDHsBFo_X:b-duc46) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L42)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

(and same compile error)
</blockquote></details>

same comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXigMsiA7RPcIrmVK2d:bph0242)*

**Comment by RussTedrake** [comment]
@david-german-tri offered to look at the VectorBlock const issue when he has time.  As discussed, will merge this version as is.

---

Review status: 8 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/framework/primitives/signal_logger.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXchg04O3FDuBces-JA:-KXjfhBRihwf9pfmxV8e:b2kwk1g) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

OK. I'm fine with leaving this until it is a problem -- please consider filing an issue so we don't forget it.
</blockquote></details>

added the TODO.

---

*[drake/systems/framework/primitives/signal_logger.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgVqS-XhnP1PSy-71:-KXjfiqMq789bwVwWOi6:b-17ptsn) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm trying to figure out how this differs from [BasicVector::get_value()](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/basic_vector.h#L62) which appears to do exactly the same thing. The only obvious difference is the `const VectorBlock` return. Have you tried:
```c++
Eigen::VectorBlock<VectorX<T>> sample_times() const { ... }
```
?
</blockquote></details>

i used that example heavily in my initial implementation.  it doesn't work here.  the difference, I think, it that the data is marked mutable.  Even quick feedble attempts at const_casting the type before returning doesn't seem to help.

---

*[drake/systems/framework/primitives/signal_logger.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-KXcgxL5Vp56lcaNW0hT:-KXjfwMpkeLAySkiatZK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00ac34db102095f84d1408793aabd71f46c53744/drake/systems/framework/primitives/signal_logger.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

same comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4257#-:-KXlTtWnziFm2ZNeaM7A:b-8tyzj4)*

**Pull request merged**
