### PR TITLE
Make old kinsol methods call new kinsol methods when use_new_kinsol = true

### PR DESCRIPTION
**Pull request by tkoolen**
* no more silent failures when calling old methods when use_new_kinsol is true (call new stuff instead)
* no more silent failures when calling new methods when use_new_kinsol is false (throw error; I had missed a couple of methods)
* makes the transition to new kinsol easier

also renamed kinsol.qdot --> kinsol.qd in the new Matlab doKinematics to match the old implementation.

### CODE REVIEW

**Comment by tkoolen** [comment]
Should we warnOnce if an old method is called when use_new_kinsol is true?

**Comment by psiorx** [comment]
Thanks for this.  Also, warnOnce sounds like a good idea since we shouldn't be calling the old methods with use_new_kinsol even if they do work now.  If anything, it will help point out places in the code that need to be updated.

**Comment by RussTedrake** [comment]
Agreed on warnonce

- Russ

**Comment by tkoolen** [comment]
BTW, shouldn't warnOnce be calling `mexWarnMsgIdAndTxt` instead of the cout?

**Comment by RussTedrake** [comment]
no.  we want to have warnOnce even for the stand-alone C version (don't introduce matlab deps)

**Comment by tkoolen** [comment]
Must have messed up the qd/qdot during a merge. Should be fixed now.

**Pull request merged**
