### PR TITLE
Add retry to brew and apt-get update calls and add flag to skip update altogether

### PR DESCRIPTION
**Pull request by jamiesnape**
Things I could do:

1. Remove the retries and assume that If you are bothered that you do your one and only update beforehand (modulo `kcov`) you will pass `--without-update`.
2. Add some logic (not difficult, but verbose) to check that the `kcov`-related update really is needed.

I don't mind doing (1.) , just a couple of `sed` calls to fixup. Probably not worth doing (2.).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@soonho-tri for review.

**Review by jwnimmer-tri — COMMENTED** [review]
I do plan to test locally, but I'll wait til after the next push and perhaps even wait for Soonho to weigh in first.

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492#-:-MSZp-7aD0k8FT2q2PUL:bhi4hls)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape, @jwnimmer-tri, and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZo8T48acrHlcUTb6-:-MSZo8T5EovEjI2t3-LN:b-k823ej) (no related file):*
nit The PR overview does not cite an issue which this closes, nor does it provide any rationale to motivate these changes.  It's easy to infer why we want retries (the internet has hiccups from time to time) though, so that part is fine.

It's more difficult to infer why we want `--without-update`.  I don't object to the feature, but I'd like us to write down in the PR overview and/or commit message why we think its useful, or what need it meets, or something along those lines.

---
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZn2TP32d1rURf_D5O:-MSZn2TP32d1rURf_D5P:b-r7bbiv) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/ubuntu/source_distribution/install_prereqs.sh#L80)):*
> ```Shell
>   echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/${codename} ${codename} main" \
>     > /etc/apt/sources.list.d/drake.list
>   apt-get update || (sleep 30; apt-get update)
> ```

I think the language around "unless absolutely necessary" in the comments  pollutes the situation.  If the option is named `--without-update`, then when it is provided we should never do any update, full stop.

In this case, where we potentially do need to add a PPA in order to succeed, we then have two options:

(1) Unconditionally bomb out here when `${with_update}` is 0.  Say that "if you are turning on kcov, then you must always also turn on updates".

(2) If updates are disabled, skip the stanza from this line prior (the part that adds and updates the PPA), but still run the "install" line below.  If they user already had added the PPA in a prior run, it will be fine.  If not, they will get an error.  (We could customize the error to be clearer about the resolution, if we wanted to.)

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZo8T48acrHlcUTb6-:-MSc8FPb5LxIkjnRbB7k:b-gp0snf) (no related file):*
> I don't object to the feature,

I think you in effect requested the feature, but I will write something.

---
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZn2TP32d1rURf_D5O:-MSc8Nva-n9QE7VmYSCC:b-nl0yr6) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/ubuntu/source_distribution/install_prereqs.sh#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the language around "unless absolutely necessary" in the comments  pollutes the situation.  If the option is named `--without-update`, then when it is provided we should never do any update, full stop.

In this case, where we potentially do need to add a PPA in order to succeed, we then have two options:

(1) Unconditionally bomb out here when `${with_update}` is 0.  Say that "if you are turning on kcov, then you must always also turn on updates".

(2) If updates are disabled, skip the stanza from this line prior (the part that adds and updates the PPA), but still run the "install" line below.  If they user already had added the PPA in a prior run, it will be fine.  If not, they will get an error.  (We could customize the error to be clearer about the resolution, if we wanted to.)
</blockquote></details>

Probably the latter then, though recall the `--with-kcov` argument is also not 100% accurate if you just read the flag and not the description.

**Review by soonho-tri — COMMENTED** [review]
Checkpoint for the macos part.

> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492#-:-MScRpA876WIwvu8W99d:b-u3cnwr)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

___
*[setup/mac/install_prereqs.sh, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MScRJeaEGi9SDjTgxK4:-MScRJeaEGi9SDjTgxK5:bv0ulr2) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/mac/install_prereqs.sh#L9)):*
> ```Shell
> 
> source_distribution_args=()
> ```

nit, better to have `binary_distribution_args=()`?
___
*[setup/mac/install_prereqs.sh, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MScRRHnDoQxuh6WzZMm:-MScRRHnDoQxuh6WzZMn:byqotus) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/mac/install_prereqs.sh#L45)):*
> ```Shell
> # developing with source distributions.
> 
> source "${BASH_SOURCE%/*}/binary_distribution/install_prereqs.sh"
> ```

I think we want to pass `"${binary_distribution_args[@]:-}"` here?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

___
*[setup/mac/install_prereqs.sh, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MScRRHnDoQxuh6WzZMm:-MScj7zk1n1Mb0RQKLVS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/mac/install_prereqs.sh#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we want to pass `"${binary_distribution_args[@]:-}"` here?
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZn2TP32d1rURf_D5O:-MScjSgYDV8PNMXsFEtA:bfxueul) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/ubuntu/source_distribution/install_prereqs.sh#L80)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Probably the latter then, though recall the `--with-kcov` argument is also not 100% accurate if you just read the flag and not the description.
</blockquote></details>

Almost done. My `if `statement needs to expand.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape, @jwnimmer-tri, and @soonho-tri)

___
*[setup/ubuntu/install_prereqs.sh, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSclMwW0VMtt9PDQKN-:-MSclMwW0VMtt9PDQKN0:b-11qvyn) ([raw file](https://github.com/robotlocomotion/drake/blob/41b2635941f8a71088731a0abdc532221de54819/setup/ubuntu/install_prereqs.sh#L72)):*
> ```Shell
> # development dependencies such as build-essential and cmake.
> 
> source "${BASH_SOURCE%/*}/binary_distribution/install_prereqs.sh"
> ```

missing `"${binary_distribution_args[@]:-}"` here?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

___
*[setup/ubuntu/install_prereqs.sh, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSclMwW0VMtt9PDQKN-:-MScn3MsDAYvcMsfxZgX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/41b2635941f8a71088731a0abdc532221de54819/setup/ubuntu/install_prereqs.sh#L72)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

missing `"${binary_distribution_args[@]:-}"` here?
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZn2TP32d1rURf_D5O:-MScn5hNCdlWZ6q8jnYu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72a3562fff44d018991fc2a720e23ae333fd59c6/setup/ubuntu/source_distribution/install_prereqs.sh#L80)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Almost done. My `if `statement needs to expand.
</blockquote></details>

Done.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492#-:-MScxr-8CQs78NedepKx:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[setup/ubuntu/install_prereqs.sh, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSclMwW0VMtt9PDQKN-:-MSczuv6BzAC7ctR8Mg2:bryjba8) ([raw file](https://github.com/robotlocomotion/drake/blob/41b2635941f8a71088731a0abdc532221de54819/setup/ubuntu/install_prereqs.sh#L72)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

` "${binary_distribution[@]:-}"` => `"${binary_distribution_args[@]:-}"`

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZo8T48acrHlcUTb6-:-MSczJly2q4HuIZGyXOU:b-jb4m0j) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> I don't object to the feature,

I think you in effect requested the feature, but I will write something.
</blockquote></details>

Ah!  Very likely so, but sometimes my mind is a sieve so the breadcrumbs will help me out.

---

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSZo8T48acrHlcUTb6-:-MSdTQSz1kYmt-0nMZph:bv5z7dm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah!  Very likely so, but sometimes my mind is a sieve so the breadcrumbs will help me out.
</blockquote></details>

https://drakedevelopers.slack.com/archives/C270MN28G/p1609864099271000?thread_ts=1609860974.269600&cid=C270MN28G, but I guess it's going along the lines of "avoids updates for people who just updated and who do not need the extra remote network download".

---

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

___
*[setup/ubuntu/install_prereqs.sh, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14492#-MSclMwW0VMtt9PDQKN-:-MSdVEnm2X3NmhUh6lLA:b-xsnhqy) ([raw file](https://github.com/robotlocomotion/drake/blob/41b2635941f8a71088731a0abdc532221de54819/setup/ubuntu/install_prereqs.sh#L72)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

` "${binary_distribution[@]:-}"` => `"${binary_distribution_args[@]:-}"`
</blockquote></details>

Good catch. I actually copy and pasted that so it was wrong elsewhere too.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: tested the various ubuntu command-line options locally.

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14492#-:-MSe2mPo-ZGrYE-ljZb5:b-mzj377)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform)

**Pull request merged**
