### PR TITLE
Make NiceTypeName recognize a wider class of compiler-inserted dummy namespaces

### LINKED ISSUE #2236: nice_type_name_test failing on std::string template on ubuntu 16.04
(Classifying as 'feature request' as we don't officially support 16.04 yet.)

When running unit tests, I get a unit test failure from `TestNiceTypeName.StdClasses`.  This appears to be because `nice_type_name` relies on regex match of `std::basic_string<char,std::char_traits<char>` and it seems like the default version of things on 16.04 has `std::string` being `std::__cxx11::basic_string...`.

Here is a minimal set of commands:
```
git clone git@github.com:ggould-tri/drake.git drake-fork3 && cd drake-fork3
make configure && make -j8 && (cd drake && make -j8 && make -j8 test)
```
With the result:
```
/home/ggould/git/drake-fork/drake/common/test/nice_type_name_test.cc:83: Failure
      Expected: NiceTypeName::Get<std::string>()
      Which is: "std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>"
To be equal to: "std::string"
/home/ggould/git/drake-fork/drake/common/test/nice_type_name_test.cc:84: Failure
      Expected: NiceTypeName::Get<string>()
      Which is: "std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>"
To be equal to: "std::string"
/home/ggould/git/drake-fork/drake/common/test/nice_type_name_test.cc:89: Failure
      Expected: NiceTypeName::Get<MyStringAlias>()
      Which is: "std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>"
To be equal to: "std::string"
/home/ggould/git/drake-fork/drake/common/test/nice_type_name_test.cc:90: Failure
      Expected: NiceTypeName::Get<MyStringTypedef>()
      Which is: "std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>"
To be equal to: "std::string"
/home/ggould/git/drake-fork/drake/common/test/nice_type_name_test.cc:96: Failure
      Expected: NiceTypeName::Get<std::vector<std::string>>()
      Which is: "std::vector<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>,std::allocator<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>>"
To be equal to: "std::vector<std::string,std::allocator<std::string>>"
[  FAILED  ] TestNiceTypeName.StdClasses (1 ms)
```

### PR DESCRIPTION
**Pull request by sherm1**
`NiceTypeName` removes compiler-added dummy namespaces from the canonicalized names it produces. Previously only namespaces like `__123` (two underscores followed by digits) were removed. Apparently gcc 5.3 (in Ubuntu 16.04) inserts `__cxx11::` so I widened the "nuke me" set to any namespace that starts with two underscores (always reserved for system use per standard).

Fixes #2236.

@ggould-tri: I am having trouble getting a gcc 5 build in my Ubuntu VM, and ci won't check either. Would you please pull this to verify it fixes your problem before it gets merged?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2246)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Just one small nit.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGnix_JqExmaGeQiLyQ:-KGnix_JqExmaGeQiLyR:-503130112) ([raw file](https://github.com/robotlocomotion/drake/blob/c699ef7fcde5d3b9e1364a4e4dc8342693615306/drake/common/test/nice_type_name_test.cc#L48)):*
This comment has become inaccurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-:-KGnj0p3rfgLo6_ofRGj:460975895)*

**Comment by sherm1** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGnix_JqExmaGeQiLyQ:-KGnoJ2U30IRCrSy-hNv:1753452594) ([raw file](https://github.com/robotlocomotion/drake/blob/c699ef7fcde5d3b9e1364a4e4dc8342693615306/drake/common/test/nice_type_name_test.cc#L48)):*
Crap -- thanks! Sad that I can't change a couple of lines of code without an error :cry:. I fixed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by sherm1** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGnix_JqExmaGeQiLyQ:-KGnotEND101YfEqSFtf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c699ef7fcde5d3b9e1364a4e4dc8342693615306/drake/common/test/nice_type_name_test.cc#L48)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-:-KGnr_40KlhwpV4KnDk_:1417088721)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGqWOtv1VG3jljRdD66:-KGqWOtw_yu6JbCILTT3:1551609399) ([raw file](https://github.com/robotlocomotion/drake/blob/a983eafc16e1d8ea699050a5c6c05f49f28ba600/drake/common/test/nice_type_name_test.cc#L48)):*
I was just looking at [this rule in the C++ style guide](https://google.github.io/styleguide/cppguide.html#Namespace_Names) and didn't see anything preventing the user from deciding to create a legitimate namespace  starting with two underscores. Is it in fact illegal to start a namespace with two underscores or is it just poor style?

If it is just poor style, should we add a clarification to the style guide?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by ggould-tri** [comment]
This appears to work for me.

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGqWOtv1VG3jljRdD66:-KGrSvO4mTqgIMVaDLvN:-825098414) ([raw file](https://github.com/robotlocomotion/drake/blob/a983eafc16e1d8ea699050a5c6c05f49f28ba600/drake/common/test/nice_type_name_test.cc#L48)):*
From the C++ standard, "Each name that contains a double underscore _ _ or begins with an underscore followed by an uppercase letter (2.12) is reserved to the implementation for any use."

I think we don't need to repeat the standard in our code style conventions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by sherm1** [comment]
> This appears to work for me.

Thanks, Grant. I'm setting up a 16.04 to avoid future trouble.

cpplint is red for this but I can't see a cpplint error in Jenkins -- can anyone spot the problem?

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGqWOtv1VG3jljRdD66:-KGr_21swlXl5lsB40Uv:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a983eafc16e1d8ea699050a5c6c05f49f28ba600/drake/common/test/nice_type_name_test.cc#L48)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by jwnimmer-tri** [comment]
@sherm1
>19:34:20 /home/ubuntu/workspace/experimental/ae7636ba/drake/common/nice_type_name.cc:61: warning: Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]

**Comment by sherm1** [comment]
@jwnimmer-tri: thanks; now I see it. I didn't know what to search for. Fixed.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-:-KGrfFNLrWyPZ11n-RTI:1417088721)*

**Comment by sherm1** [comment]
Works in my new Ubuntu 16.04 VM with g++ 5.3.1. Ready to merge.

**Comment by david-german-tri** [comment]
:lgtm: pending CI

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-:-KGsKWhsgr_UYHinWzyc:202278974)*

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/nice_type_name_test.cc, line 48 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2246#-KGqWOtv1VG3jljRdD66:-KGrZm2BT-2y08sU96XR:-1167627368) ([raw file](https://github.com/robotlocomotion/drake/blob/a983eafc16e1d8ea699050a5c6c05f49f28ba600/drake/common/test/nice_type_name_test.cc#L48)):*
@liangfok this thread seems to be waiting for you to acknowledge it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2246)*

**Comment by jwnimmer-tri** [comment]
Actually, it was @ggould-tri whose comment is blocking (mouseover the lower right bubble in reviewable, look at the flair next to the headshots).

I am going to override-merge.  The reviews are done, and the 2a99200 passed CI; the subsequent merge from master flaked on msvc64, and the retest is still in progress, but whatever; this is ready to go in.

**Pull request merged**
