### PR TITLE
[parsing] Add package_downloader tool

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For now this is only unit tested; not installed nor used in earnest.

Towards #15774 and #9498.  You can see it used in action in #18955.

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: testing question

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948#-:-NPxFJta1kIOWi6_nMYz:b-knzq8r)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/package_downloader.py` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18948#-NPxEjQOAo0uLtNe6OXL:-NPxEjQOAo0uLtNe6OXM:b-f7mump) ([raw file](https://github.com/RobotLocomotion/drake/blob/fbe109a5f39ae79e1ab221b1970f6a9c0cbe34a8/multibody/parsing/package_downloader.py#L69)):*
> ```Python
>     output_dir_tmp = f"{output_dir}.tmp"
>     if os.path.exists(output_dir_tmp):
>         shutil.rmtree(output_dir_tmp)
> ```

nit this branch is not reached by tests. Should I worry?

**Review by jwnimmer-tri — COMMENTED** [review]
FYI I removed the shebang stuff for now, since this PR doesn't need it.  I'm still not 100% decided on how to invoke this program from the Parser, so I'll leave the subprocess details for a future PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948#-:-NPxGqw697_P2uQVbCrq:b51cdcn)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`multibody/parsing/package_downloader.py` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18948#-NPxEjQOAo0uLtNe6OXL:-NPxGz4iCeG455KR69e4:bwnfhuv) ([raw file](https://github.com/RobotLocomotion/drake/blob/fbe109a5f39ae79e1ab221b1970f6a9c0cbe34a8/multibody/parsing/package_downloader.py#L69)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this branch is not reached by tests. Should I worry?
</blockquote></details>

I didn't think it was worth testing.  I guess you weren't convinced by what was on the page, so I added the test coverage now.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule (Wednesday), please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Nice tests. I learned something for them, thanks.

Platform :lgtm: 

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18948#-:-NQ1Tla14XbRp46pw0CJ:b-624td6)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Thanks!  And yeah, writing good tests was like 75% of the effort on this project.  (I've rewritten the whole feature branch's test suite from scratch ~3 times until I found the current solutions.)

**Pull request merged**
