### PR TITLE
"Flatten" director superbuild

### LINKED ISSUE #4686: Run Director Tests on Drake CI
We want to run Director tests on Drake PRs.  Since Director itself is a superbuild, there is no means to export tests from the subproject, through the superbuild, into the Drake superbuild.  The current plan (work in progress on #4527) is to add Director's externals to Drake's own superbuild, and build Director directly.

There are also some unresolved challenges with running Director tests under xvfb on AWS instances.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Extract the bits of director's superbuild that we need into drake's own superbuild, and build director directly, rather than via its superbuild, so that its tests are exposed.
    
This also reshuffles some externals that have become trivial again back to the 'trivial externals' block, and uses an updated [PythonQt](https://github.com/commontk/PythonQt) which fixes some build issues.

Fixes #4686.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4527)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KZ7OHEZbcBuO8XPmuDa:bnfp4nl)*

**Comment by sherm1** [comment]
I'm not the right reviewer for this. Will punt to today's on call: -@sherm1 +@ggould-tri.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KZ7OsTZNvZdpEsZ01TD:b87rgza)*

**Comment by jwnimmer-tri** [comment]
If the words "CMake" and "superbuild" appear, it actually goes to @david-german-tri.

**Comment by david-german-tri** [comment]
+@patmarion should take a look also

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KZ9Bg36OvMR8NhPsqJL:b2m2ink)*

**Comment by david-german-tri** [comment]
CI seems displeased.  Once you've got that sorted out, should we expect to see director tests running?

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 286 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-KZ9CE3HEh4Baw2lPcgp:-KZ9CE3HEh4Baw2lPcgq:b-w7mnp5) ([raw file](https://github.com/robotlocomotion/drake/blob/25082b2fed45ba24aded9a20e6b9a614129369c3/CMakeLists.txt#L286)):*
> ```CMake
> # director
> drake_add_external(director PUBLIC CMAKE TEST PYTHON
>   SOURCE_SUBDIR distro/superbuild
> ```

BTW Huh, Director's superbuild is buried in a subdirectory?  I didn't know you could do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KZ9CLL59M7X6lMW2Wku:b-k855w1)*

**Comment by patmarion** [comment]
Quick scan of the changes and I didn't see any special handling of vtk dir.  By default I don't think it will find vtk 5.10 on mac homebrew, director's superbuild adds a hint to find it, so you might need something like.

**Comment by mwoehlke-kitware** [comment]
> CI seems displeased.  Once you've got that sorted out, should we expect to see director tests running?

They *are* running... or at least, trying to and failing, which is why CI is unhappy (at least for many of the builds).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KZMgR07XjQ1wtLdiaea:b-mull3e)*

**Comment by patmarion** [comment]
I see pros and cons to flattening the director superbuild.  I'm curious whether we are doing it so that drake's superbuild can have finer control, or is the main motivation to support tests in director?  If it's to support tests, then I would propose that we consider other routes than flattening the superbuild.

I don't see management of VTK in this new flattened build.  I think that means we lose support for USE_SYSTEM_VTK=OFF, which is a current use case.

**Comment by jamiesnape** [comment]
> I see pros and cons to flattening the director superbuild. I'm curious whether we are doing it so that drake's superbuild can have finer control, or is the main motivation to support tests in director? If it's to support tests, then I would propose that we consider other routes than flattening the superbuild.

It will also improve (parallel) build times since the dependencies of Director do not need to wait for Drake to finish building.

**Comment by patmarion** [comment]
So is CI testing of Director dependent on this PR now?  Is there not a more direct way to enable testing?  I'm afraid this PR may require more time and development before it's ready.

**Comment by jamiesnape** [comment]
Yes.

**Comment by jamiesnape** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 302 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-K_10UfBOFD1ZaL9NC3Y:-K_10UfBOFD1ZaL9NC3Z:bhnjgud) ([raw file](https://github.com/robotlocomotion/drake/blob/371d71ba9c1019b67595fc398e41ac652ce3b66b/CMakeLists.txt#L302)):*
> ```CMake
> # signalscope
> drake_add_external(signalscope PUBLIC
>   DEPENDS director)
> ```

Change to `DEPENDS ctk_python_console lcm pythonqt` it does not actually depend on `director`, just the superbuild of `director`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527)*

**Comment by mwoehlke-kitware** [comment]
> I don't see management of VTK in this new flattened build. I think that means we lose support for USE_SYSTEM_VTK=OFF, which is a current use case.

There is no such support currently; Drake requires that VTK has been externally provided. Actually, this is an improvement, since it is now possible to provide VTK in a non-standard location (without relying on `$ENV{CMAKE_PREFIX_PATH}`).

**Comment by patmarion** [comment]
There are some users who currently use director's superbuild `USE_SYSTEM_VTK=OFF` option to provide VTK from source, rather than use system VTK.  The docs for those users are in `drake/doc/from_source_ros_kinetic.rst`.  So that doc could be updated to tell users how to compile VTK 5.10 from source and provide it to the drake superbuild via `VTK_DIR`.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
@patmarion, I can't get the tests to run successfully. It appears to be a problem with `xvfb-run`. Can you help?

**Comment by patmarion** [comment]
sure, let me look at the dashboard errors

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
Note that #4765 adds additional references to the `-DUSE_SYSTEM_VTK=OFF` flag.

---

Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KaJNQYzK-8LnKjDyMsF:bf447p2)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
CI is green; waiting on reviews...

**Comment by david-german-tri** [comment]
Cool!  https://drake-cdash.csail.mit.edu/viewTest.php?onlypassed&buildid=309738

:lgtm: but please make sure to get @patmarion's approval before merging

---

Reviewed 2 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-Kah1GrIzC5v14tvoqbz:bm84w9l)*

**Comment by patmarion** [comment]
Changes look fine to me.  It would be nice to get the mac tests working eventually.  As I stated above, I still have concerns about Drake flattening the director superbuild.  It will require extra work to maintain.  But obviously this is the direction you guys have decided to go, so no reason to hold up this PR if there is consensus.

Still might want to consider updating the docs, since there is now outdated documentation telling the user how to build without system VTK.

**Comment by patmarion** [comment]
And of course, big thanks to @mwoehlke-kitware and others for getting the linux tests to run with xvfb on the ci images, that's really great.

**Comment by mwoehlke-kitware** [comment]
> I still have concerns about Drake flattening the director superbuild.

I'd prefer to avoid nested superbuilds, if possible; they present a point where build options can be lost and they create artificial choke-points in the build. (There was also a false dependency between director and signalscope that this PR eliminates.)

> Still might want to consider updating the docs, since there is now outdated documentation telling the user how to build without system VTK.

I plan to hoist VTK to drake proper in a follow-up PR. That will allow users that need to build VTK to do so in a much cleaner manner than what we have now.

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 302 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-K_10UfBOFD1ZaL9NC3Y:-KahGX4eBi6OvGn5q1HI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/371d71ba9c1019b67595fc398e41ac652ce3b66b/CMakeLists.txt#L302)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Change to `DEPENDS ctk_python_console lcm pythonqt` it does not actually depend on `director`, just the superbuild of `director`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4527#-:-KahGoHidLHBWzK3qT3A:bnfp4nl)*

**Comment by patmarion** [comment]
> I'd prefer to avoid nested superbuilds, if possible; they present a point where build options can be lost and they create artificial choke-points in the build. (There was also a false dependency between director and signalscope that this PR eliminates.)

I'm not questioning the benefits and I appreciate the motivation.  I'm just stating for the record that there are now two director superbuilds to maintain---one in drake that will be maintained by drake devs, and one that I maintain in Director.  So the build system is forked, and that's a concern of mine.  If I add new features to Director's build, they may not get ported into drake immediately (or ever) and vice versa.

**Pull request merged**
