### PR TITLE
MosekSolver supports QuadraticConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
MosekSolver now takes in convex QuadraticConstraint. We still recommended the users to formulate the convex QuadraticConstraint
 as Lorentz cone constraint to get best solver performance.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-:-NZ8iGLnBpsPsbZdI3iy:b1ikduc)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8tdncAURg3RLaLBRp):*
where do you recommend that to users?
___
*[`solvers/mosek_solver_internal.h` line 543 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8jEou3fPuLqfNChEz:-NZ8jEou3fPuLqfNChF-:b-gr0zw4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.h#L543)):*
> ```objc
> }
> 
> // @param slc Mosek dual variables for linear constraint lower bound. See
> ```

linear constraint?
___
*[`solvers/mosek_solver_internal.h` line 545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8jG1V9hWDqwKI5Ecr:-NZ8jG1V9hWDqwKI5Ecs:b-gr0zw4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.h#L545)):*
> ```objc
> // @param slc Mosek dual variables for linear constraint lower bound. See
> // https://docs.mosek.com/10.0/capi/alphabetic-functionalities.html#mosek.task.getslc
> // @param suc Mosek dual variables for linear constraint upper bound. See
> ```

linear constraint?
___
*[`solvers/mosek_solver_internal.cc` line 579 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8kSD_DBJClMJqRvXb:-NZ8kSD_DBJClMJqRvXc:bv5hlfa) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L579)):*
> ```cpp
>   for (const auto& constraint : prog.quadratic_constraints()) {
>     for (int i = 0; i < constraint.variables().rows(); ++i) {
>       for (int j = 0; j < i; ++j) {
> ```

i'm confused.  don't you need j<=i here to get the diagonal entries?  but the tests seem to pass?
___
*[`solvers/mosek_solver_internal.cc` line 598 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8nbx24jVRnRjUya2j:-NZ8nbx24jVRnRjUya2k:b-j4dq89) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L598)):*
> ```cpp
>   qcsubi.reserve(nnz_hessian);
>   qcsubj.reserve(nnz_hessian);
>   qcval.reserve(nnz_hessian);
> ```

the docs say "For large problems it is essential for the efficiency that the function [`MSK_putmaxnumqnz`](https://docs.mosek.com/10.0/capi/alphabetic-functionalities.html#mosek.task.putmaxnumqnz "mosek.task.putmaxnumqnz") is employed to pre-allocate space."
seems worth doing here?

https://docs.mosek.com/10.0/capi/alphabetic-functionalities.html#mosek.task.putqcon
___
*[`solvers/mosek_solver_internal.cc` line 634 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8n0STEs-hoXapS6LQ:-NZ8n0STEs-hoXapS6LR:bwaj7p6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L634)):*
> ```cpp
>     }
>     for (int j = 0; j < constraint.variables().rows(); ++j) {
>       for (int i = j; i < constraint.variables().rows(); ++i) {
> ```

the text below says lower-diagonal, but this is the upper diagonal entries?  (the mosek docs seem to flip them, too.. am I missing something?
___
*[`solvers/mosek_solver_internal.cc` line 649 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8oK_9DC8iZXKf-WeI:-NZ8oK_9DC8iZXKf-WeJ:b-1nq96n) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L649)):*
> ```cpp
>               // constraint. Since Mosek only takes the lower-diagonal entries
>               // of the Hessian matrix, we append Q()(i, j) to the off-diagonal
>               // entry of the Hessian matrix in Mosek.
> ```

btw -- that's a pretty confusing logic for the ultimate conclusion of -- just hand Q(i,j) to mosek.
___
*[`solvers/mosek_solver_internal.cc` line 656 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8q9XEC0Vh_8nZ-2q0:-NZ8q9XEC0Vh_8nZ-2q1:b-f444lo) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L656)):*
> ```cpp
>               // should not be added as an off-diagonal term, but a diagonal
>               // term in the Hessian matrix in Mosek. Namely we add (Q()(i, j) +
>               // Q()(j, i)) * decision_var[i] * decision_var[i], namely the
> ```

nit - would be a little more consistent to have `decision_var[j]` for one, or to write `Q(i,i)`.  
___
*[`solvers/mosek_solver_internal.cc` line 657 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8qtMRB2G1yIhBf_wS:-NZ8qtMRB2G1yIhBf_wT:b8cpmzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L657)):*
> ```cpp
>               // term in the Hessian matrix in Mosek. Namely we add (Q()(i, j) +
>               // Q()(j, i)) * decision_var[i] * decision_var[i], namely the
>               // coefficient is 2 * Q()(i, j).
> ```

btw -- i spent a long time trying to understand this.

x'Qx with x = [x1,x1,x2] => x1*(Q11*x1 + Q12*x1 + Q13*x3) + x1*(Q21*x1 + Q22*x1 + Q23*x2) + ... 
so the x1 terms are x1*(Q11 + Q21 + Q12 + Q22)*x1, which gets handled correctly if you pass 2*Q21 here.  ok, I believe it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8tdncAURg3RLaLBRp):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

where do you recommend that to users?
</blockquote></details>

Good call, I added that to the documentation of AddQuadraticConstraint
___
*[`solvers/mosek_solver_internal.h` line 543 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8jEou3fPuLqfNChEz:-NZ9-2hv5r74XsdxXgCz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.h#L543)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

linear constraint?
</blockquote></details>

Done.
___
*[`solvers/mosek_solver_internal.h` line 545 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8jG1V9hWDqwKI5Ecr:-NZ9-3C15JRhXE-zGlqb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.h#L545)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

linear constraint?
</blockquote></details>

Done.
___
*[`solvers/mosek_solver_internal.cc` line 579 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8kSD_DBJClMJqRvXb:-NZ9-DpW-cE2gICEf1jQ:b-s87qjj) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L579)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i'm confused.  don't you need j<=i here to get the diagonal entries?  but the tests seem to pass?
</blockquote></details>

Good catch!

This for loop computes the total number of non-zero entries, and then use `std::vector::reserve()` to reserve the memory for these non-zero entries. It then use `std::vector::push_back()` to insert the entries. So even if it count the number incorrectly, the final vector (after calling `std::vector::push_back()` is still correct).
___
*[`solvers/mosek_solver_internal.cc` line 598 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8nbx24jVRnRjUya2j:-NZ90c5d3NB80mHIuLSa:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L598)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the docs say "For large problems it is essential for the efficiency that the function [`MSK_putmaxnumqnz`](https://docs.mosek.com/10.0/capi/alphabetic-functionalities.html#mosek.task.putmaxnumqnz "mosek.task.putmaxnumqnz") is employed to pre-allocate space."
seems worth doing here?

https://docs.mosek.com/10.0/capi/alphabetic-functionalities.html#mosek.task.putqcon

</blockquote></details>

Done. Good call.
___
*[`solvers/mosek_solver_internal.cc` line 634 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8n0STEs-hoXapS6LQ:-NZ90jAm036mgXm3x8dU:b5el2hf) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L634)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the text below says lower-diagonal, but this is the upper diagonal entries?  (the mosek docs seem to flip them, too.. am I missing something?
</blockquote></details>

I think this is lower diagonal entries? It is Q(i, j) with i >= j.
___
*[`solvers/mosek_solver_internal.cc` line 649 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8oK_9DC8iZXKf-WeI:-NZ91Gdn4CWUmQzPRt6i:b-fg3027) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L649)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- that's a pretty confusing logic for the ultimate conclusion of -- just hand Q(i,j) to mosek.
</blockquote></details>

Done. I removed this part of the documentation.
___
*[`solvers/mosek_solver_internal.cc` line 656 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8q9XEC0Vh_8nZ-2q0:-NZ91ZPs2T5TcP-gDoUo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L656)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit - would be a little more consistent to have `decision_var[j]` for one, or to write `Q(i,i)`.  
</blockquote></details>

Done.
___
*[`solvers/mosek_solver_internal.cc` line 657 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8qtMRB2G1yIhBf_wS:-NZ9272_3bAyOFQTMUiW:b-dnzayd) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L657)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i spent a long time trying to understand this.

x'Qx with x = [x1,x1,x2] => x1*(Q11*x1 + Q12*x1 + Q13*x3) + x1*(Q21*x1 + Q22*x1 + Q23*x2) + ... 
so the x1 terms are x1*(Q11 + Q21 + Q12 + Q22)*x1, which gets handled correctly if you pass 2*Q21 here.  ok, I believe it.
</blockquote></details>

Done. I added your example here.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-:-NZClc5t9mj6I1mTy_Fe:bnfp4nl)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.cc` line 634 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZ8n0STEs-hoXapS6LQ:-NZClPZo1bSWE7flSMIY:bmn52yv) ([raw file](https://github.com/RobotLocomotion/drake/blob/c717ba2561225d3c61e31329663edc109e07ed2e/solvers/mosek_solver_internal.cc#L634)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this is lower diagonal entries? It is Q(i, j) with i >= j.
</blockquote></details>

you're right.  silly me.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for Wednesday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-:-NZY_uiHCcp-51DklTIq:b9q16kq)* status: LGTM missing from assignee sherm1(platform), missing label for release notes

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705)* status: LGTM missing from assignee sherm1(platform), missing label for release notes

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few minor comments

> Reviewed 7 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-:-NZcQCAKDKe6h5Ba-dkJ:b5096no)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.cc` line 581 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZcNaOy0w7vVdtCjxJJ:-NZcNaOy0w7vVdtCjxJK:bq9zxxh) ([raw file](https://github.com/RobotLocomotion/drake/blob/eb39e1f806bb550c3568e47f79b56f49d0eabf93/solvers/mosek_solver_internal.cc#L581)):*
> ```cpp
>       for (int j = 0; j <= i; ++j) {
>         if (constraint.evaluator()->Q()(i, j) != 0) {
>           nnz_hessian++;
> ```

nit: [prefer pre-increment](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) when possible (and below)



_Suggestion:_
```cpp
++nnz_hessian
```
___
*[`solvers/mosek_solver_internal.cc` line 600 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZcOMu351Xrltj5UIjG:-NZcOMu351Xrltj5UIjH:blw2at5) ([raw file](https://github.com/RobotLocomotion/drake/blob/eb39e1f806bb550c3568e47f79b56f49d0eabf93/solvers/mosek_solver_internal.cc#L600)):*
> ```cpp
>   qcval.reserve(nnz_hessian);
> 
>   // Store all the linear entries in all quadratic constraints into A *
> ```

BTW not clear (to me) what the "*" and end of line is doing here
___
*[`solvers/mosek_solver_internal.cc` line 623 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19705#-NZcOoyhDN6pOwDn_Bm3:-NZcOoyhDN6pOwDn_Bm4:b9cvmg1) ([raw file](https://github.com/RobotLocomotion/drake/blob/eb39e1f806bb550c3568e47f79b56f49d0eabf93/solvers/mosek_solver_internal.cc#L623)):*
> ```cpp
>               decision_var_index) > 0) {
>         throw std::runtime_error(fmt::format(
>             "variable {} shows up in the quadratic constraint {}, but this "
> ```

BTW consider preceding this with some kind of identification for where the message came from e.g. 
"MosekSolverProgram::AddQuadraticConstraint(): variable {} shows up ..."

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Pull request merged**
