### PR TITLE
Support forwarding more than one arg in Value ctor

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5973)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.
+@ericcousineau-tri for feature review, please (or punt to @amcastro-tri if you want).

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-:-KiqsBWOEkT61_ecSizp:bvi3vbh)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-:-KirSopJHIi4I1Pm1iOF:b8qx53o)*

**Comment by EricCousineau-TRI** [comment]
Punting on this one, just to make sure it's what he needs.
-@EricCousineau-TRI 

+@amcastro-tri for feature review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-:-Kireb7Ej7DQ92YvIer9:b1t9cv6)*

**Comment by amcastro-tri** [comment]
It does solve my problem! thanks @ericcousineau-tri and @jwnimmer-tri. Looks great :lgtm: 
Just a little comment but you can disregard it if you think it's too much of a pathological case.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-Kiv1g_l31Bla0akEaVf:-Kiv1g_megG1WMg8kVHN:b-eivnuk) ([raw file](https://github.com/robotlocomotion/drake/blob/e154e6a2bcf5c40c575e938625bfedb3c9a5cd94/drake/systems/framework/value.h#L183)):*
> ```objc
>                 // construct a T(const T&).
>                 !std::is_same<T, Arg1>::value &&
>                 !std::is_same<T&, Arg1>::value &&
> ```

BTW, I really don't have a case like this in my work right now but, what if we have a class `Foo` with constructor `Foo(const Foo& other_foo, int i)`? where `Arg1` resolves to `T&` and therefore this gets disabled if I understand correctly.

---

*[drake/systems/framework/test/value_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-Kiv2Rmq1qWrXutGE23z:-Kiv2Rmq1qWrXutGE24-:b-1cu1n2) ([raw file](https://github.com/robotlocomotion/drake/blob/e154e6a2bcf5c40c575e938625bfedb3c9a5cd94/drake/systems/framework/test/value_test.cc#L23)):*
> ```cpp
> struct NoDefaultCtor {
>   explicit NoDefaultCtor(int i) : data{i} {}
>   NoDefaultCtor(int c1, int c2) : data{c1 * c2} {}
> ```

BTW, up to you to fix now but probably nice if we could get it to work also for a constructor with signature `NoDefaultCtor(const NoDefaultCtor& other, int i)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-:-Kiv2vcLDEorn9nZlrc7:b-oyum0o)*

**Comment by jwnimmer-tri** [comment]
Yeah, I thought about that and decided it _was_ pathological.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5973#-:-KivG08KP9K89sDCXU7z:bk9wyig)*

**Pull request merged**
