### PR TITLE
Add AddLinearConstraint which takes an array of symbolic formula

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue: #5536.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5542)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfSn0T5h7-SaVk1z0OR:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1096 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-KfTn6iVvH1-knOEaAf0:-KfTn6iVvH1-knOEaAf1:b-e2oc16) ([raw file](https://github.com/robotlocomotion/drake/blob/94cadc50146efea34c68c58add60b677ce3b95c1/drake/solvers/mathematical_program.h#L1096)):*
> ```objc
>     // Decomposes 2D-array of formulas into 1D-vector of expression, `v`, and
>     // two 1D-vector of double `lb` and `ub`.
>     drake::VectorX<symbolic::Expression> v{n};
> ```

It might be an overkill, but if the input `formulas` is a fixed size array, the `v` can also be fixed size. Potentially we can do
```C++
const int flat_vector_size = Derived::RowsAtCompileTime != Eigen::Dynamic && Derived::ColsAtCompileTime != Eigen::Dynamic ? Derived::RowsAtCompileTime * Derived::ColsAtCompileTime : Eigen::Dynamic;
Eigen::Matrix<symbolic::Expression, flat_vector_size, 1> v{n};
```

---

*[drake/solvers/test/mathematical_program_test.cc, line 958 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-KfTorsbkQmjYhUC6lN1:-KfTorsbkQmjYhUC6lN2:b-wrjor9) ([raw file](https://github.com/robotlocomotion/drake/blob/94cadc50146efea34c68c58add60b677ce3b95c1/drake/solvers/test/mathematical_program_test.cc#L958)):*
> ```cpp
>   const auto ub_in_ctr = constraint_ptr->upper_bound();
>   for (int i{0}; i < M_f.size(); ++i) {
>     if (lb_in_ctr(i) != -numeric_limits<double>::infinity()) {
> ```

BTW, maybe `isinf(lb_in_ctr(i))`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1096 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-KfTn6iVvH1-knOEaAf0:-KfUGKnbgaVgWFLYxXR7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/94cadc50146efea34c68c58add60b677ce3b95c1/drake/solvers/mathematical_program.h#L1096)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It might be an overkill, but if the input `formulas` is a fixed size array, the `v` can also be fixed size. Potentially we can do
```C++
const int flat_vector_size = Derived::RowsAtCompileTime != Eigen::Dynamic && Derived::ColsAtCompileTime != Eigen::Dynamic ? Derived::RowsAtCompileTime * Derived::ColsAtCompileTime : Eigen::Dynamic;
Eigen::Matrix<symbolic::Expression, flat_vector_size, 1> v{n};
```
</blockquote></details>

Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 958 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-KfTorsbkQmjYhUC6lN1:-KfUGLOb_FkJODbi5Ja6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/94cadc50146efea34c68c58add60b677ce3b95c1/drake/solvers/test/mathematical_program_test.cc#L958)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, maybe `isinf(lb_in_ctr(i))`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfUIhKjwdZlK6DrNP6F:bozh2sc)*

**Comment by soonho-tri** [comment]
-@sherm1 is not the platform reviewer on Monday (20 Mar). Actually, I am..

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfWKcMydWo-XBzVqbns:b-iln6ne)*

**Comment by soonho-tri** [comment]
+@russtedrake , could you platform-review this PR?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfWLVZDNutx2IAKlHT5:b-kfsbc2)*

**Comment by sherm1** [comment]
> -@sherm1 is not the platform reviewer on Monday (20 Mar). Actually, I am.

Woohoo! Thanks, @soonho-tri!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfXeuODlxe5inTzve24:bmk3sbo)*

**Comment by RussTedrake** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1083 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kf_ytBC2derGfq3FpEE:-Kf_ytBC2derGfq3FpEF:bhtyw2h) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1083)):*
> ```objc
>    *  2. A formula in @p formulas includes a non-linear expression.
>    *  3. A formula in @p formulas is either a trivial constraint such
>    *     as "1 <= 2" or an unsatisfiable constraint such as "2 <= 1".
> ```

This is beautiful.  Can you make clear in the documentation that e1 <= e2 implies elementwise comparisons, and that by "symbolic array of formulas" you actually mean the Eigen::Array type.  Perhaps even a hint that these can be constructed from an Eigen::Matrix type with a.array().  E.g. "to add a constraint with the elementwise comparison between matrices A and B, use A.array() <= B.array()" .

---

*[drake/solvers/mathematical_program.h, line 1102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa-djPYx9Nst9vBYMn:-Kfa-djPYx9Nst9vBYMo:b-57iul) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1102)):*
> ```objc
>     Eigen::Matrix<symbolic::Expression, flat_vector_size, 1> v{n};
>     Eigen::Matrix<double, flat_vector_size, 1> lb{n};
>     Eigen::Matrix<double, flat_vector_size, 1> ub{n};
> ```

BTW, nice.  love the fixed-size support.  (presumably, we'll slowly start backporting to use that everywhere?)

---

*[drake/solvers/test/mathematical_program_test.cc, line 1027 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa1_yHbVX9Y15gHsS5:-Kfa1_yHbVX9Y15gHsS6:b-vo6pow) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/test/mathematical_program_test.cc#L1027)):*
> ```cpp
>   // clang-format off
>   M_f << (3 - 5 * x(0) + 10 * x(2) - 7 * y(1) > 3),
>                               x(2)            > -10;
> ```

could you update one or more of these tests to use what I would think is the more common/useful notation, where you write explicitly `A*x <= b` (instead of listing out the elements each as Formulas)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1083 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kf_ytBC2derGfq3FpEE:-KfgQB3oan7P5FfKmO1K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1083)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This is beautiful.  Can you make clear in the documentation that e1 <= e2 implies elementwise comparisons, and that by "symbolic array of formulas" you actually mean the Eigen::Array type.  Perhaps even a hint that these can be constructed from an Eigen::Matrix type with a.array().  E.g. "to add a constraint with the elementwise comparison between matrices A and B, use A.array() <= B.array()" .
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa-djPYx9Nst9vBYMn:-Kfg5g_kYMYXhTTZIXA8:b2okjm4) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1102)):*
> presumably, we'll slowly start backporting to use that everywhere?

@hongkai-dai and I will do that.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1027 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa1_yHbVX9Y15gHsS5:-KfhMOn6pnQ-qDYJE2fe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/test/mathematical_program_test.cc#L1027)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

could you update one or more of these tests to use what I would think is the more common/useful notation, where you write explicitly `A*x <= b` (instead of listing out the elements each as Formulas)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa-djPYx9Nst9vBYMn:-KfhN03m7bYI7KWSSYiH:b-i251kq) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1102)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> presumably, we'll slowly start backporting to use that everywhere?

@hongkai-dai and I will do that.
</blockquote></details>

We actually did similar fixed size vector before https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.h#L1427~L1431, but not using this nice struct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-Kfa-djPYx9Nst9vBYMn:-KfhOPR1nALgXLCnSSEb:boc004e) ([raw file](https://github.com/robotlocomotion/drake/blob/926e8a8defb0151564b5c73660e9b42181dc1ca1/drake/solvers/mathematical_program.h#L1102)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We actually did similar fixed size vector before https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.h#L1427~L1431, but not using this nice struct.
</blockquote></details>

I'll open another PR after this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5542#-:-KfuptiQTLhqKL2eNutm:bnfp4nl)*

**Pull request merged**
