### PR TITLE
[framework] Deprecate LeafSystem update dispatcher overrides

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Requires #20114.
See also #20035.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for feature review or delegation, please.   (OK with me if you want both reviews.)

+(priority: low)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-:-Ng1teEKEvEsTZVoWK7H:b4rirhz)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tOGP5kNK9GmITG_D:-Ng1tOGQAkCQRYGO8e80:b6udosc) (no related file):*
Working

Check Anzu build 230 to make sure the deprecation worked.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tSBXBKcvAR8KWk61:-Ng1tSBXBKcvAR8KWk62:b-ajnw64) (no related file):*
Working

I still need to develop and test forward-porting patch for Anzu.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tUq29PndtA5UlKds:-Ng1tUq29PndtA5UlKdt:b-i67kvr) (no related file):*
@sherm1 how quickly should we try to ditch this?  Possibly we could give 6 months instead of 3.5, in case people have a lot of code to port?

___

**Review by sherm1 — COMMENTED** [review]
A few thoughts:
- why only the update methods and not publish? Leaving publish means we still have to attempt to explain the difference between a publish with handler vs. overriding the DoPublish() dispatcher to accomplish the same thing.
- consider separating the clean-up-Drake-usage changes from the deprecation changes.

> Reviewed 1 of 27 files at r1, 18 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-:-NgK5ph81QvLHkqtafp2:b-fmmk3b)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tUq29PndtA5UlKds:-NgK4ydICMsaTsYIftDd:b-f2nspm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 how quickly should we try to ditch this?  Possibly we could give 6 months instead of 3.5, in case people have a lot of code to port?
</blockquote></details>

A longer deprecation period makes sense, but not because of the amount of code (the changes are rote once you get the idea and instances are easy to find). IMO it is the apparent fact that outside users don't update Drake fast enough to see the deprecation messages in 3 months, and this is a case where it would be very helpful to have some warning.

___
___
*[`systems/framework/leaf_system.h` line 1938 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgK34DH2tF0IAntV2FV:-NgK34DH2tF0IAntV2FW:b-c62tb7) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e2ae0d7c513f9e32302b7b3d0bb4c1726b9fc63/systems/framework/leaf_system.h#L1938)):*
> ```objc
>       const EventCollection<PublishEvent<T>>& events) const final;
> 
>   // Calls DoCalcDiscreteVariableUpdates (deprcated 2024-02-01).
> ```

typo deprcated -> deprecated

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tOGP5kNK9GmITG_D:-NgKB3TG4F8gRdN6A1ge:bkqyi4f) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Check Anzu build 230 to make sure the deprecation worked.
</blockquote></details>

OK passed.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tUq29PndtA5UlKds:-NgKB8DP1CaKRRTQ6V2n:bddzl9q) (no related file):*
> ... the changes are rote once you get the idea and instances are easy to find ...

I also just realized that there are cases where the logic in their override would not be easy to express in the new API.  (When not all of the events are independent.)  We don't anticipate that any users were doing that, but the longer period would give them more time to complain in case they were.

> ... it is the apparent fact that outside users don't update Drake fast enough to see the deprecation messages in 3 months ...

Citation needed.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgKApGX0ka3lgBsLt9d:-NgKApGYBg2AR6MZtwrI:b-out8z1) (no related file):*
Working

> why only the update methods and not publish? Leaving publish means we still have to attempt to explain the difference between a publish with handler vs. overriding the DoPublish() dispatcher to accomplish the same thing.

There's still some code that needs porting away from `DoPublish`.  I guess I can do that first, and they deprecate all at once.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgKAq5a8nTRQbZQuano:-NgKAq5a8nTRQbZQuanp:b-nc3o6j) (no related file):*
Working

> Consider separating the clean-up-Drake-usage changes from the deprecation changes.

To be clear, you just mean the bouncing ball example program, right?  (Not the unit tests?)

Assuming yes, that seems fine and I'll carve it out.

___

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tUq29PndtA5UlKds:-NgKoqR84D396p-iQg5A:b-sgsggc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... the changes are rote once you get the idea and instances are easy to find ...

I also just realized that there are cases where the logic in their override would not be easy to express in the new API.  (When not all of the events are independent.)  We don't anticipate that any users were doing that, but the longer period would give them more time to complain in case they were.

> ... it is the apparent fact that outside users don't update Drake fast enough to see the deprecation messages in 3 months ...

Citation needed.
</blockquote></details>

I don't have one -- I remember (misremember?) being told that at Drake Developers meetings, maybe by Andy?

___

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tUq29PndtA5UlKds:-NgKpKVyB2WMK_63amWG:b-crnovl) (no related file):*
> cases where the logic in their override would not be easy to express in the new API

Yes, that was the actual justification for allowing people to override the default dispatcher: if you don't like how we treat simultaneous events, you can implement your own dispatcher using a different policy. I have never actually seen anyone do that, instead the dispatchers are overloaded just to implement handlers that could have been event callbacks instead. If we remove the dispatcher overload feature, users will not be able to implement their own simultaneous event policies. But does that matter in real life?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-Ng1tSBXBKcvAR8KWk61:-NgLnJqWEP2gh4nBNopd:b-rq668p) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I still need to develop and test forward-porting patch for Anzu.
</blockquote></details>

Filed as 10955.  Awaiting review.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgKAq5a8nTRQbZQuano:-NgLrI214a1ukkOitJf6:bmk6998) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

> Consider separating the clean-up-Drake-usage changes from the deprecation changes.

To be clear, you just mean the bouncing ball example program, right?  (Not the unit tests?)

Assuming yes, that seems fine and I'll carve it out.
</blockquote></details>

OK => https://github.com/RobotLocomotion/drake/pull/20338

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgKApGX0ka3lgBsLt9d:-NgLrJc-BYpTFBIsMr0C:byxlk6u) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

> why only the update methods and not publish? Leaving publish means we still have to attempt to explain the difference between a publish with handler vs. overriding the DoPublish() dispatcher to accomplish the same thing.

There's still some code that needs porting away from `DoPublish`.  I guess I can do that first, and they deprecate all at once.
</blockquote></details>

Done.

https://github.com/RobotLocomotion/drake/pull/20338 for the porting.  It's temporarily incorporated here as a first commit.

The publish stuff is deprecated now, too.

___

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: with one minor issue. It will be a joyous day when these are gone!
+@rpoyner-tri for platform review per schedule, please

> Reviewed 1 of 27 files at r1, 2 of 26 files at r2, 3 of 7 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-:-NgQOn0c2ceWKOVIETTQ:b7i5ro4)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`systems/framework/vector_system.cc` line 15 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgQMgcA6foZxBJ-NJ28:-NgQMgcA6foZxBJ-NJ29:b-htt50v) ([raw file](https://github.com/RobotLocomotion/drake/blob/e226f113578e18499743bf160a20fd8379a72996/systems/framework/vector_system.cc#L15)):*
> ```cpp
>     if (status.severity() == EventStatus::Severity::kDidNothing) {
>       // Handle any deprecated no-handler events.
>       CalcDiscreteUpdate(context, discrete_state);
> ```

BTW I'm not sure of your intent here. If there are multiple "do nothing" Events then CalcDiscreteUpdate() will get called multiple times, but that call is not event-specific. Maybe call it just once after processing if all events were do nothing?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`systems/framework/vector_system.h` line 174 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgPGFaM3aisdFWsrEMc:-NgPGFaN2AROOPBfFIix:b-z1jv4) ([raw file](https://github.com/RobotLocomotion/drake/blob/eb4a10b89e501da7aa17f173cc01c6b6feed46cc/systems/framework/vector_system.h#L174)):*
> ```objc
>   /// Converts the parameters to Eigen::VectorBlock form, then delegates to
>   /// DoCalcVectorDiscreteVariableUpdates().
>   void DoCalcDiscreteVariableUpdates(
> ```

Working

Probably I should haven't changed the C++ visibility of this one, in case someone was calling it?  I'll investigate.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending open questions

> Reviewed 2 of 27 files at r1, 19 of 26 files at r2, 3 of 7 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-:-NgQrXrQ6lqNz3KLar5I:b4m3xlb)* status: 2 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 1 unresolved discussion

___
*[`systems/framework/vector_system.h` line 174 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgPGFaM3aisdFWsrEMc:-NgUcAyIA2_jPBJHbyJi:buku8r9) ([raw file](https://github.com/RobotLocomotion/drake/blob/eb4a10b89e501da7aa17f173cc01c6b6feed46cc/systems/framework/vector_system.h#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Probably I should haven't changed the C++ visibility of this one, in case someone was calling it?  I'll investigate.
</blockquote></details>

Done.  In effect, this function is back in the protected section now (by virtue of not being mentioned at all, so is inherited from LeafSystem).
___
*[`systems/framework/vector_system.cc` line 15 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20094#-NgQMgcA6foZxBJ-NJ28:-NgUcKog2tPSuOGeHKtR:bc42odd) ([raw file](https://github.com/RobotLocomotion/drake/blob/e226f113578e18499743bf160a20fd8379a72996/systems/framework/vector_system.cc#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm not sure of your intent here. If there are multiple "do nothing" Events then CalcDiscreteUpdate() will get called multiple times, but that call is not event-specific. Maybe call it just once after processing if all events were do nothing?
</blockquote></details>

This loop was correct, but the reasoning was a bit too subtle to explain easily.  Instead, I found a simpler solution.  PTAL (at the header file).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: 1 unresolved discussion

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20094)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
