### PR TITLE
Fix meshcat visualizer in master and use it in examples

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9982)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> Would it make sense for us to add a linter error for that?

Doing that seems difficult, because in general test classes may have helper methods, which themselves are not tests.  So you can't just do static checking of the method names.  The only check I can immediately think of is that every method must be called at least once, at runtime.  A quick search for best practices the python community didn't turn up anything for me.  Maybe others know more.

**Comment by RussTedrake** [comment]
Even making sure that there is a single instance of a test in the file (and saying “you need to name your methods blah to have them run as tests”) would have saved me on this one.

**Comment by jwnimmer-tri** [comment]
> We could check that at least one Python unittest runs for any given Bazel test fairly easily.

That seems like a fair compromise, but I wasn't sure it would be easy.  Is there a way when calling unittest.main, to have it report back to us how many tests were run?
```
        # Delegate the rest to unittest.
        unittest.main(module=test_name, argv=unittest_argv)
```

IIRC, there are also cases in-tree, were we pass conditional `args = []` in the BUILD rule to disable some or all cases, depending on, e.g., the solvers available, or dbg mode, or etc.  We'd have to have those opt-out of this check, as well.

> Even making sure that there is a single instance of a test in the file (and saying “you need to name your methods blah to have them run as tests”) would have saved me on this one.

I think Jamie's solution is fine, but I also haven't seen this problem come up often.  Most authors end up running the tests and confirming that they find bugs in the dut, as part of development, and so to date this kind of bug has not been common.  Copying test cases from another project with a different test framework is a novel workflow, I guess.

**Comment by RussTedrake** [comment]
I agree it’s probably rare.  Though even developing in tree one could have a false sense that their tests just worked on the first try.  

I’m fine with no action on that front.  Just calling out the possibility.

**Comment by jamiesnape** [comment]
> That seems like a fair compromise, but I wasn't sure it would be easy. Is there a way when calling unittest.main, to have it report back to us how many tests were run?

The most simplistic approach:
```python
test_program = unittest.main(exit=False)
sys.exit(test_program.result.testsRun == 0 or not test_program.result.wasSuccessful())
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
The cache builds have all passed.  That's good enough to merge.  Forcing in now.

**Pull request merged**
