### PR TITLE
Small improvements to monolithic_pick_and_place_demo

### PR DESCRIPTION
**Pull request by sammy-tri**
Pick some items off of my personal branch which seem like they should go to master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6511)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-:-KoJWxLYqlNQ6P3kGvVg:b-psw9ws)*

**Comment by naveenoid** [comment]
Barring 3 documentation requests, :lgtm: 

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXuCUK0up08bIhVvn:-KoJXuCUK0up08bIhVvo:b75ww41) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L1)):*
> ```cpp
> #include <memory>
> ```

BTW: Im wondering if we need a @file comment on what one is expected to see with this demo (echoing the README.md on this folder)

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXZqiTs_Kf9dLkNjw:-KoJXZqiTs_Kf9dLkNjx:b8010pp) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L161)):*
> ```cpp
>   // Location for the extra table from the pick and place tests.
>   Eigen::Vector3d table_position(0.9, -0.36, -0.07);  // position C
>   Eigen::Vector3d post_height_offset(0, 0, 0.26);
> ```

BTW: Could you add a little comment explaining the relevance of the offset for the demo?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXhQ51R1e0I8dKPAY:-KoJXhQ6Mk2E8FK5hnuP:b-rgtr24) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L208)):*
> ```cpp
>   ModelInstanceInfo<double> iiwa_instance, wsg_instance, box_instance;
> 
>   const Eigen::Vector3d table_offset(0.30, 0, 0);
> ```

BTW: likewise  - comment needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-:-KoJY3KhkRd-p8By86wo:b-miordl)*

**Comment by naveenoid** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511)*

**Comment by sammy-tri** [comment]
+@soonho-tri as tomorrow's platform reviewer

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXuCUK0up08bIhVvn:-KoJZ7Vy015TpULDzobi:bud94uh) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L1)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Im wondering if we need a @file comment on what one is expected to see with this demo (echoing the README.md on this folder)
</blockquote></details>

I'm not sure what it would say aside from "see README.md in this folder", but I can add that if it seems helpful.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXZqiTs_Kf9dLkNjw:-KoJa4VErTMG4DS8_mhU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L161)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Could you add a little comment explaining the relevance of the offset for the demo?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-KoJXhQ51R1e0I8dKPAY:-KoJa4wPu0RCubhVYrTL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb7e5eb73e51fc7e79331ea923131ed50273477/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L208)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: likewise  - comment needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-:-KoJaFvusTWVqu8zbNpp:b-d1fh6d)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6511#-:-KoNC4BBxJbQonrr9pZs:bnfp4nl)*

**Pull request merged**
