### PR TITLE
[solvers] Ipopt supports kPrintFileName

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17023 and #17035.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17034)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @hongkai-dai FYI

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17034)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17034#-:-N0XlXhJ0k_BYYo4aW6q:b-ws0fkp)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17034#-:-N0bCfyCBdDwXFtkDHST:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
