### PR TITLE
Libbot Enabled out of source builds.

### PR DESCRIPTION
**Pull request by jhoare**
Updated CMakeLists.txt for libbot to not pollute the source tree. 

CI PR for https://github.com/RobotLocomotion/libbot/pull/18

Provides progress towards #1859 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2777)

### CODE REVIEW

**Comment by jhoare** [comment]
@sherm1 for platform review (feel free to re-assign if necessary)

**Comment by david-german-tri** [comment]
-@sherm1, +@RussTedrake (build system PR).  Looks reasonable to me, for what it's worth.

**Comment by liangfok** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2777#-:-KMVrGgYmVJbMARVro10:980077423)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2777)*

**Comment by RussTedrake** [comment]
tested this one out.  and 👍

**Pull request merged**
