### PR TITLE
Adds a README.md to multibody/models/.

### PR DESCRIPTION
**Pull request by liangfok**
Addresses https://github.com/RobotLocomotion/drake/pull/4907#issuecomment-275413487.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4915)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sammy-tri for both levels of review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4915#-:-KbQMSXmAQYwOTk7oGNo:bzd9pib)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4915#-:-KbQNYEpUZV6YKwM_Xf6:bnfp4nl)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please.

**Pull request merged**
