### PR TITLE
Port sensors to SisoVectorSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #4448.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5261)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai could I ask you to feature review, as someone who has looked at RotaryEncoders previously?
/CC @russtedrake FYI.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5261#-:-KdaaTSl95x4qmc0vj01:bohb2v5)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5261#-:-KdbLhfkUD86_YacVHig:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5261#-:-KdbNDuUoVe_Vl5_q2Un:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5261#-:-Kdb_UR4khsjr1IEAFp7:bnfp4nl)*

**Pull request merged**
