### PR TITLE
Kill rb collision element

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This deletes the otherwise redundant `RigidBodyCollisionElement` class.

It provided no real functionality beyond the base element with one real exception; a constructor which allowed the collision element's corresponding `RigidBody` member to be set.

Deleting this class merely required extending the `Element` class to have the corresponding constructors.  References to the child class were pulled from various test classes

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3657)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Simple code change;  Platform @sherm1  and feature @amcastro-tri. PTAL

**Comment by amcastro-tri** [comment]
Reviewed 13 of 15 files at r1.
Review status: 13 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/Element.cpp, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF-MStjKGGECgtDV3O:-KTF-MStjKGGECgtDV3P:b-nnr77w) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.cpp#L25)):*
> ```cpp
> 
> Element::Element(const Isometry3d& T_element_to_link,
>                  const RigidBody * const body )
> ```

the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.
And also, is this constructor without geometry used anywhere? don't we always create a collision element for a given geometry?

---

*[drake/systems/plants/collision/Element.cpp, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF-qZe_sb097EmFC_Q:-KTF-qZe_sb097EmFC_R:b-1gfgrj) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.cpp#L33)):*
> ```cpp
> Element::Element(const DrakeShapes::Geometry& geometry,
>                  const Isometry3d& T_element_to_link,
>                  const RigidBody * const body )
> ```

the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.

---

*[drake/systems/plants/collision/Element.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF0KgBSfLXWCiaZBle:-KTF0KgBSfLXWCiaZBlf:bdog6nf) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.h#L34)):*
> ```objc
> 
>   Element(const Eigen::Isometry3d& T_element_to_link,
>           const RigidBody * const body);
> ```

Is this constructor used?

---

*[drake/systems/plants/collision/Element.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF0FY5JiWdPAiVix29:-KTF0FY5JiWdPAiVix2A:b-ojasvc) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.h#L38)):*
> ```objc
>   Element(const DrakeShapes::Geometry& geometry,
>           const Eigen::Isometry3d& T_element_to_link,
>           const RigidBody * const body);
> ```

the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.
Also small documentation for new constructor please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 12 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/Element.cpp, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF-MStjKGGECgtDV3O:-KTFDbmCjORwykIhKUzu:ba1kj3) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.cpp#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.
> And also, is this constructor without geometry used anywhere? don't we always create a collision element for a given geometry?
> 
</details>
Done

This isn't used -- I'd mindlessly assumed its presence in the sub-class implied that it should exist.

---

*[drake/systems/plants/collision/Element.cpp, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF-qZe_sb097EmFC_Q:-KTFCogocEfMIG8ynn-0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.cpp#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.
</details>
Done

---

*[drake/systems/plants/collision/Element.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF0KgBSfLXWCiaZBle:-KTFDEV5L7CYN1LynasG:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.h#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Is this constructor used?
</details>
Done

---

*[drake/systems/plants/collision/Element.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTF0FY5JiWdPAiVix29:-KTFSdXAj_SUNMwPPpGq:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/88a62ea16068fcce7a23a59a19840431f63fb525/drake/systems/plants/collision/Element.h#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> the second `const` is not needed (the pointer is passed by copy anyways). Also fix spacing for the `*`.
> Also small documentation for new constructor please.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by amcastro-tri** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/collision/Element.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTFdX9PR48NuTpsIN4k:-KTFdX9PR48NuTpsIN4l:b-upec2w) ([raw file](https://github.com/robotlocomotion/drake/blob/5bbf8a7e09658c95f2126fa6662b3bca49478486/drake/systems/plants/collision/Element.h#L35)):*
> ```objc
>    * Geometry constructor.
>    * @param[in] geometry                The colliding geometry.
>    * @param[in] T_element_to_local      The pose (defaults to identity).
> ```

"The pose" is ambiguous. This more like "The pose of the geometry in the collision element's frame".
Also notice you have "T_element_to_local" here and "T_element_to_link" below.
I think it'd be clearer if it was named something like "T_EG" using @sherm1's notation and explaining the notation ("where E denotes the Element frame and G denotes the Geometry frame" or something of the like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/Element.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTFdX9PR48NuTpsIN4k:-KTGRGrsvf1pZDKDZ_w4:b-r3b1jk) ([raw file](https://github.com/robotlocomotion/drake/blob/5bbf8a7e09658c95f2126fa6662b3bca49478486/drake/systems/plants/collision/Element.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "The pose" is ambiguous. This more like "The pose of the geometry in the collision element's frame".
> Also notice you have "T_element_to_local" here and "T_element_to_link" below.
> I think it'd be clearer if it was named something like "T_EG" using @sherm1's notation and explaining the notation ("where E denotes the Element frame and G denotes the Geometry frame" or something of the like.
</details>
I agree about the ambiguity of "the pose".  However, I disagree with using @sherm1 's notation.  Not because I like/dislike the notation, but it's such a terse notation that unless it is ubiquitous in the code, it won't carry much meaning.  However, expanding the definition of "pose" is definitely a good idea.

I'm going to add documentation which ties it into the underlying DrakeShape::Element class (as this derives from that.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/Element.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTFdX9PR48NuTpsIN4k:-KTGmLtQjO8vwlL3cc-M:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5bbf8a7e09658c95f2126fa6662b3bca49478486/drake/systems/plants/collision/Element.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary>
> I agree about the ambiguity of "the pose".  However, I disagree with using @sherm1 's notation.  Not because I like/dislike the notation, but it's such a terse notation that unless it is ubiquitous in the code, it won't carry much meaning.  However, expanding the definition of "pose" is definitely a good idea.
> 
> I'm going to add documentation which ties it into the underlying DrakeShape::Element class (as this derives from that.)
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by SeanCurtis-TRI** [comment]
Last review address.  PTAL @amcastro-tri 

---

Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTGmSHMVD2yZSNxTML8:b-iwo4k2)*

**Comment by sherm1** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/Element.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTFdX9PR48NuTpsIN4k:-KTKKSmpb1RxDKowXf9s:b-x4m9kf) ([raw file](https://github.com/robotlocomotion/drake/blob/5bbf8a7e09658c95f2126fa6662b3bca49478486/drake/systems/plants/collision/Element.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary>
> Done
</details>
Looks good to me -- Sean defined this unambiguously as T_EL in the class documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657)*

**Comment by sherm1** [comment]
-@amcastro-tri since he's on vacation (he did review).

---

Review status: 12 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTKKz1KcIFcM6c-Rki6:b-pb559y)*

**Comment by sherm1** [comment]
Review pass done - some minor comments, PTAL. I am glad to see this superfluous class nuked! I don't like the re-use of `Element` here; for code clarity I'd rather see a `CollisionElement` parallel to the existing `VisualElement` (and the `DrakeCollision` namespace has to go too!). But that can wait for another PR; this one is a step in the right direction.

---

Reviewed 13 of 15 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/collision/Element.cpp, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKTbVbyg-Zu0MGboy1:-KTKTbVbyg-Zu0MGboy2:b1ve4u) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.cpp#L25)):*
> ```cpp
> 
> Element::Element(const Isometry3d& T_element_to_link, const RigidBody* body)
>     : DrakeShapes::Element(T_element_to_link), body_(body) {
> ```

"local" and "link" should be "body": T_element_to_body (here, above & below).

---

*[drake/systems/plants/collision/Element.h, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKU2j9iDrrqR-Tx1XI:-KTKU2j9iDrrqR-Tx1XJ:bx9xg5f) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L25)):*
> ```objc
> 
> /**
>  * The underyling primitive class used for collision analysis.  Collisions
> ```

BTW, great to see documentation for this class!

---

*[drake/systems/plants/collision/Element.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKLuknVVxvf8pFFPjt:-KTKLuknVVxvf8pFFPju:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L29)):*
> ```objc
>  * on the `RigidBody` instances' corresponding collision `Element`s.  As such,
>  * The `Element` combines three pieces of data:
>  * - the geometric definition of the element's collidng shape (a `Geometry`
> ```

typo

---

*[drake/systems/plants/collision/Element.h, line 33 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKMAAF1QakefPGrKt6:-KTKMAAF1QakefPGrKt7:b9lqlha) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L33)):*
> ```objc
>  * - the transform (T_LE) from the space the shape is defined in (element) to
>  *   its position in the `RigidBody`'s "local" space (an instance of
>  *   `Eigen::Isometry3d` referred to as its "pose").
> ```

Rather than using the ambiguous from/to notation I would prefer:
```
the transform `T_element_to_body` (T_BE) giving the pose of the element's frame E in the body's local frame B, with the sense that p_B = T_BE * p_E for points measured and expressed in frames B or E.
```

---

*[drake/systems/plants/collision/Element.h, line 71 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKNiuyZQMA54irhNIM:-KTKNiuznwnP-caS-Cl-:bvt5er4) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L71)):*
> ```objc
>    */
>   Element(const DrakeShapes::Geometry& geometry,
>           const Eigen::Isometry3d& T_element_to_link, const RigidBody* body);
> ```

The transform here is named differently than the others. They should be the same if they have the same meaning. While renaming, please consider making them all T_element_to_body which would be consistent with the `body` argument and avoids the "local" neologism.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTKU9QQXYP7NFnpspMc:bqog2ag)*

**Comment by SeanCurtis-TRI** [comment]
Made some modifications. @sherm1  PTAL

---

Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/Element.cpp, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKTbVbyg-Zu0MGboy1:-KTKgD45uZDrHiy3isCv:bd1hbdy) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.cpp#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "local" and "link" should be "body": T_element_to_body (here, above & below).
</details>
I contemplated changing it; but it inherits from DrakeShapes::Element and that same syntax is used there.  I would suggest that the nomenclature should be changed in both in a separate PR.

---

*[drake/systems/plants/collision/Element.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKLuknVVxvf8pFFPjt:-KTKgZP8ZRCAt4s5mVZb:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> typo
</details>
Done

---

*[drake/systems/plants/collision/Element.h, line 33 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKMAAF1QakefPGrKt6:-KTKlZMA8Te4CzVylf2I:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Rather than using the ambiguous from/to notation I would prefer:
> ```
> the transform `T_element_to_body` (T_BE) giving the pose of the element's frame E in the body's local frame B, with the sense that p_B = T_BE * p_E for points measured and expressed in frames B or E.
> ```
</details>
Done

---

*[drake/systems/plants/collision/Element.h, line 71 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTKNiuyZQMA54irhNIM:-KTKliiJsWAj4IxO4Gjj:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/477ce1a93cb2e04ccc60814b7771ce79bd8ffee2/drake/systems/plants/collision/Element.h#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The transform here is named differently than the others. They should be the same if they have the same meaning. While renaming, please consider making them all T_element_to_body which would be consistent with the `body` argument and avoids the "local" neologism.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTKL8qoR0rgbx3u9Gk8:b-lncpji)*

**Comment by SeanCurtis-TRI** [comment]
PTAL @sherm1 HOpefully the final commit; I'd like to sneak it in before I have to rebase, yet again.

---

Review status: 9 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTLJ1IQ5ISyArOsff7O:b8ue5la)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/Element.h, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTLIwTd5NB97KrvywBY:-KTLIwTewIx_M5LC-QWO:b-hktut0) ([raw file](https://github.com/robotlocomotion/drake/blob/b57dd2050104af7ef17e4f492af2e4437638f08f/drake/systems/plants/collision/Element.h#L66)):*
> ```objc
>    * Full constructor.
>    * @param[in] geometry            The colliding geometry.
>    * @param[in] T_element_to_local   The pose.
> ```

BTW, indenting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTLJep8Bor4dlnN4NFD:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:lgtm: 

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/Element.h, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-KTLIwTd5NB97KrvywBY:-KTLK5u72CbEXpux-DWu:b-5wxwo3) ([raw file](https://github.com/robotlocomotion/drake/blob/b57dd2050104af7ef17e4f492af2e4437638f08f/drake/systems/plants/collision/Element.h#L66)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, indenting.
</details>
BTW, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3657#-:-KTLKLt3ykFiDUM7M62w:bg7igkv)*

**Pull request merged**
