### PR TITLE
[multibody] Remove dynamic_cast from private inline functions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The `dynamic_cast` operation does not meet our styleguide requirements for being inline.  We either need to get rid of the cast (by simplifying the function), or move its definition to the cc file.

This change is tangentially inspired by https://github.com/RobotLocomotion/drake/issues/22204.

(Technically the `GetParentPlant` is a public function so the commit subject isn't quite right, but anyway it seems reasonable to change it here, too, since its fix shares a mechanism within this cohort.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22208)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for a quick feature reviewer sanity-check from the MbT developer team, please.

+@rpoyner-tri for platform review per schedule (tomorrow), please.

**Review by amcastro-tri — COMMENTED** [review]
This looks good Jeremy, I just had one question.

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-:-OC07lJo2-7znPT-xYY4:bsi9cbo)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),amcastro-tri

___
*[`multibody/plant/force_density_field.h` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-OC04rGA04iH8irY29pj:-OC04rGA04iH8irY29pk:behhcio) ([raw file](https://github.com/RobotLocomotion/drake/blob/539fdb0c8f2bbcb0d08ea6b3a41df540f33dbdb1/multibody/plant/force_density_field.h#L18)):*
> ```objc
> 
> template <typename T>
> class MultibodyPlant;
> ```

I forget, do we need to guard this against being processed by Doxygen?
___
*[`multibody/plant/force_density_field.h` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-OC05YBV4wF9TAcPRc9f:-OC05YBV4wF9TAcPRc9g:b3zlekq) ([raw file](https://github.com/RobotLocomotion/drake/blob/539fdb0c8f2bbcb0d08ea6b3a41df540f33dbdb1/multibody/plant/force_density_field.h#L83)):*
> ```objc
>          invokes this function; force_density_field.h cannot do that for you.
>    @pre tree_system != nullptr. */
>   template <typename MultibodyPlantDeferred = MultibodyPlant<T>>
> ```

pardon my ignorance, do we still need this template trick?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22208)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),amcastro-tri

___
*[`multibody/plant/force_density_field.h` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-OC04rGA04iH8irY29pj:-OC0A1SSE2V4LvVnuWY1:bccwrrx) ([raw file](https://github.com/RobotLocomotion/drake/blob/539fdb0c8f2bbcb0d08ea6b3a41df540f33dbdb1/multibody/plant/force_density_field.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I forget, do we need to guard this against being processed by Doxygen?
</blockquote></details>

Not every forward declaration confuses Doxygen, but some do, and I don't know what detail(s) of the forward declaration are relevant to misleading Doxygen's parsing.

When I am writing new code I do always guard forward declarations with with an ifndef, but I'm not going to change this pre-existing code unless we find a specific cause for concern.
___
*[`multibody/plant/force_density_field.h` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-OC05YBV4wF9TAcPRc9f:-OC09nZ80t2YSQnl2DtQ:b-6afeyx) ([raw file](https://github.com/RobotLocomotion/drake/blob/539fdb0c8f2bbcb0d08ea6b3a41df540f33dbdb1/multibody/plant/force_density_field.h#L83)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

pardon my ignorance, do we still need this template trick?
</blockquote></details>

We still need it but it doesn't matter what type it mentions.  Simplified to use `void`, instead.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 15 of 23 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22208#-:-OC59oYf7G4yNx_Qd-yw:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @amcastro-tri from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22208)* status: LGTM missing from assignee amcastro-tri

**Comment by jwnimmer-tri** [comment]
@amcastro-tri we're missing the LGTM from you, please.

**Comment by jwnimmer-tri** [comment]
I'll deem the "sanity-check from the MbT developer team" sufficiently completed.

**Pull request merged**
