### PR TITLE
Fix lcm_vector_gen to use pragma once

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2137)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2137#-:-KFt5dByfZKfokEjV16Y:980077423)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2137#-:-KFtKgRqYIwQKpyIMJkm:1417088721)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
Code review pass, CI pass.  Using override-merge due to out-of-date with master.

**Comment by david-german-tri** [comment]
I'm going to create a rollback for this PR to see whether it explains #2154.

**Pull request merged**
