### PR TITLE
Initial version of the RigidBodyPlantBridge

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. New class, allows a RigidBodyPlant to contribute to GeometrySystem
   (currently to a limited degree).
2. Modify examples/contact_model/bowling_ball.cc to illustrate the usage.

```
Category            added  modified  removed  
----------------------------------------------
code                212    4         3        
comments            91     3         0        
blank               60     0         0        
----------------------------------------------
TOTAL               363    7         3 
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8027)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@amcastro-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L4wuHOpY92CmKC_4j_7:b5xll3r)*

**Comment by amcastro-tri** [comment]
:lgtm: , just minor comments.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[geometry/rigid_body_plant_bridge.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51EbDKqj4AU0RE44ET:-L51EbDKqj4AU0RE44EU:b-yq7ovl) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.cc#L1)):*
> ```cpp
> #include "drake/geometry/rigid_body_plant_bridge.h"
> ```

BTW interesting you placed this here. Don't you think it should live in `drake/multibody/rigid_body_plant`?

---

*[geometry/rigid_body_plant_bridge.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51GugXoQ9gP8iuryHd:-L51GugXoQ9gP8iuryHe:b-ya2qck) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.cc#L25)):*
> ```cpp
>     : // LeafSystem<T>(SystemTypeTag<geometry::RigidBodyPlantBridge>{}),
>       tree_(*tree) {
>   DRAKE_THROW_UNLESS(geometry_system != nullptr);
> ```

this check is happening after you de-referenced the pointer above. You should just make `tree_` a const pointer.

---

*[geometry/rigid_body_plant_bridge.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FF26gBACXfkpJ64T:-L51FF26gBACXfkpJ64U:bxpzbsx) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L27)):*
> ```objc
>  <H3>What geometry types are read and what roles can they be used for?</H3>
> 
>   %Shape      | Proximity | Visual | Render
> ```

BTW per text below saying what the origin is, "proximity" --> "collision"?

---

*[geometry/rigid_body_plant_bridge.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FOow1Vm3TAGtprF-:-L51FOow1Vm3TAGtprF0:b-rt1qqm) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L27)):*
> ```objc
>  <H3>What geometry types are read and what roles can they be used for?</H3>
> 
>   %Shape      | Proximity | Visual | Render
> ```

BTW, what is the "Render" column? how does it relate to the "origin" of things mentioned below?

---

*[geometry/rigid_body_plant_bridge.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51GFdzMVD5Igqgj77d:-L51GFdzMVD5Igqgj77e:bbgq2zb) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L37)):*
> ```objc
>   %Sphere     | V         | V      | .
> <h4>Table: Level of Support. Indication of what types of shapes are read from
>  the RigidBodyTree, what their origin is (collision or visual) and how they are
> ```

sry, bottom line. I don't know how to read this table. I guess is too late here....

---

*[geometry/rigid_body_plant_bridge.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FkQUsop321KeO0Qa:-L51FkQUsop321KeO0Qb:b4oqwoq) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L44)):*
> ```objc
> 
>     - C : Collision geometry used
>     - V : Visual geometry used (but without material values)
> ```

I guess I am confused. I thought the "V" was a check mark sorry. Are you saying that this implementation then renders both collision and visuals at the same time?

---

*[geometry/rigid_body_plant_bridge.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51Gf337vOQKQsmQyNq:-L51Gf337vOQKQsmQyNr:bjnpzkb) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L143)):*
> ```objc
> };
> }  // namespace geometry
> }  // namespace drake
> ```

BTW new line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L51HgrlCmWv5qsxv83H:b-w3px8i)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

---

Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[geometry/rigid_body_plant_bridge.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51EbDKqj4AU0RE44ET:-L5A-YTagKNvGpuU6WIW:bm045aa) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.cc#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW interesting you placed this here. Don't you think it should live in `drake/multibody/rigid_body_plant`?
</blockquote></details>

Done An excellent point.

---

*[geometry/rigid_body_plant_bridge.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51GugXoQ9gP8iuryHd:-L5A5A9FBV7ZnxXxSaky:b-cgyqqd) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.cc#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this check is happening after you de-referenced the pointer above. You should just make `tree_` a const pointer.
</blockquote></details>

Done (const * to const tree)

---

*[geometry/rigid_body_plant_bridge.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FF26gBACXfkpJ64T:-L5A5pnWQEofxTUFRf83:bbj482d) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW per text below saying what the origin is, "proximity" --> "collision"?
</blockquote></details>

See note below

---

*[geometry/rigid_body_plant_bridge.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FOow1Vm3TAGtprF-:-L5A5srRc1j0bx8Ntjiz:bbj482d) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, what is the "Render" column? how does it relate to the "origin" of things mentioned below?
</blockquote></details>

See note below

---

*[geometry/rigid_body_plant_bridge.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51GFdzMVD5Igqgj77d:-L5A5tpVllqSOOrF_pLe:b-ynr8as) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sry, bottom line. I don't know how to read this table. I guess is too late here....
</blockquote></details>

I'm not overly surprised; I had a hard time writing it. I have three axes to represent but only have 2D to draw them. I could use some help.
 
Axis 1: geometry type
Axis 2: role of geometry in RigidBodyTree (can be collision element or visual element)
Axis 3: role of geometry in GeometrySystem (can be proximity, drake visualizer, or render -- this last is largely predicated on an upcoming PR when GeometrySystem owns rendering as well).

The table hopes to communicate a mapping from what you have in a rigid body tree to the affect it will have in GeometrySystem.

Case 1: RBT has a sphere collision element. Table says, that sphere will be ignored. (All collision elements are, in fact, ignored in this version).

Case 2: RBT has a sphere as a visual element. Table says: that sphere will be used for both collision and drake visualizer visualization.

Case 3: RBT has mesh for visual element. Table says: that mesh will *only* be used in drake visualizer (but not collision)

Case 4: RBT has a box for visual element. Table says: that box will be ignored. 

I've updated the documentation in hopes of making it clearer, I'd happily accept suggestions.



In contrast, a

---

*[geometry/rigid_body_plant_bridge.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51FkQUsop321KeO0Qa:-L5A9ODOwI7miKxEhHOr:bwyfaum) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I guess I am confused. I thought the "V" was a check mark sorry. Are you saying that this implementation then renders both collision and visuals at the same time?
</blockquote></details>

See previous note and updated docs.

---

*[geometry/rigid_body_plant_bridge.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L51Gf337vOQKQsmQyNq:-L5A9RHfPHtTNq30YMyd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6f53eb43beaf1b607709579f2f9a8074b3b47e/geometry/rigid_body_plant_bridge.h#L143)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW new line?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5ADN9lF_uIPwVvzvh5:bh6gmpc)*

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri changes haven't been pushed yet -- wrestling CI stuff. Ignore for now.

---

Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5ADQedgPR-8nMYqFfo:bs51b3a)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) Uncurated commits left to facilitate review through the moved files. CI issues ostensibly addressed.

@amcastro-tri *now* it's ready for you.

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5AJNoFcYP0BceWP0yJ:b-7nnwuj)*

**Comment by amcastro-tri** [comment]
Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027)*

**Comment by SeanCurtis-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5Ea4OFuV1CI-psRjqo:bz1t39v)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/contact_model/bowling_ball.cc, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ez-ACsJx9BblGo2aE:-L5Ez-AD4jqUaVoiexuS:b-ct142c) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/bowling_ball.cc#L80)):*
> ```cpp
>               "'simulation_type=compliant'");
> // This facilitates running a binary in Clion's debugger.
> DEFINE_bool(gtest_color, false, "Ignored");
> ```

Should this be checked in?  I'm not aware of all of clion's issues with how we define our build, but I feel like this is the kind of thing which could become a pattern, and we should probably think that through before it does.

---

*[examples/contact_model/BUILD.bazel, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EyWnSTJ2GMufJUAn8:-L5EyWnT7oAr4oqBZ05O:b-lk2wuv) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/BUILD.bazel#L70)):*
> ```Python
>     ],
>     deps = [
>         "//drake/common:find_resource",
> ```

It looks like this file was previously de-`//drake`-ed.  I feel we should avoid adding them back?

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.cc, line 65 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5ExGlDOYZuIisIkgYH:-L5ExGlEsGrhXs01wjNU:bqvbz4c) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.cc#L65)):*
> ```cpp
> const InputPortDescriptor<T>&
> RigidBodyPlantBridge<T>::rigid_body_plant_state_input_port() const {
>   return this->get_input_port(0);
> ```

BTW different boilerplate for calling our own `get_input_port` vs `get_output_port` numeric accessors is a bit confusing.  Is this deliberate?

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ev7hQLAN0bMI14xAb:-L5Ev7hRt12LmQ1POMbH:bi3d4im) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L55)):*
> ```objc
>     queries.
> 
>  A RigidBody can have "visual" elements and "collision" elements. Which one is
> ```

BTW perhaps this paragraph and the next which explain the table entries and columns would be more helpful if they appeared before the table itself.

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Evdk8NlOziqPjNsle:-L5Evdk9hnp0wh9WVoKH:b-vffu8f) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L105)):*
> ```objc
>    registers them with the given geometry system. Ultimately, this system must
>    have its ports connected to the *same* geometry system and the RigidBodyPlant
>    which owns the rigid body tree.   */
> ```

extra whitespace before `*/`?

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 106 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EwINQjO78oNmIoJcx:-L5EwINSL7zWwmxR5Ep9:b72sw8m) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L106)):*
> ```objc
>    have its ports connected to the *same* geometry system and the RigidBodyPlant
>    which owns the rigid body tree.   */
>   RigidBodyPlantBridge(const RigidBodyTree<T>* rigid_body_tree,
> ```

Document lifetime requirements of `rigid_body_tree` (it appears it must remain valid for the lifetime of the instance?)

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EwkIw7kFefsbfzBT1:-L5EwkIxCD49GSwbpsyf:b-dvx404) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L119)):*
> ```objc
> 
>  private:
>   // Registers `this` system's tree's bodies and geometries  to the given
> ```

extra whitespace 'geometries  to`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5F-1LBg2_C6w8_SU9P:bvb1a6z)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/contact_model/bowling_ball.cc, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ez-ACsJx9BblGo2aE:-L5Jle2HdauL0Xikx9ug:b8c6oai) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/bowling_ball.cc#L80)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this be checked in?  I'm not aware of all of clion's issues with how we define our build, but I feel like this is the kind of thing which could become a pattern, and we should probably think that through before it does.
</blockquote></details>

I weighed this -- adding it, I believe, does no harm. And allows people to debug in CLion without banging their head. A recent version of the bazel plug-in changed how it packages executables for debug -- it puts them into test mode. So, *if* you have a non-googletest executable *and* you are using `gflags` in it, you have this perfect storm of immediate failure.

If you feel strongly, I can certainly pull it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027)*

**Comment by jwnimmer-tri** [comment]
*[examples/contact_model/bowling_ball.cc, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ez-ACsJx9BblGo2aE:-L5JmLBoXQG1FZybS56i:b-6ifmf9) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/bowling_ball.cc#L80)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I weighed this -- adding it, I believe, does no harm. And allows people to debug in CLion without banging their head. A recent version of the bazel plug-in changed how it packages executables for debug -- it puts them into test mode. So, *if* you have a non-googletest executable *and* you are using `gflags` in it, you have this perfect storm of immediate failure.

If you feel strongly, I can certainly pull it out.
</blockquote></details>

FYI I think the problem is one of a slippery slope.  If this were the only-ever copy, then its fine.  I suspect, though, that others might decide to copypasta this stanza into other places.  I don't mind having such a flag added, but I do mind copypasta.  If you wanted to factor this into a header file and deps= on it, I'd be happier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed (I believe).

---

Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/contact_model/bowling_ball.cc, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ez-ACsJx9BblGo2aE:-L5JsAuS5UGMEr1qEc6E:b-vmalgk) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/bowling_ball.cc#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think the problem is one of a slippery slope.  If this were the only-ever copy, then its fine.  I suspect, though, that others might decide to copypasta this stanza into other places.  I don't mind having such a flag added, but I do mind copypasta.  If you wanted to factor this into a header file and deps= on it, I'd be happier.
</blockquote></details>

A fine suggestion - I'll yank it now and go with the dependency if it burns me in the future -- the issue does have limited scope.

---

*[examples/contact_model/BUILD.bazel, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EyWnSTJ2GMufJUAn8:-L5JsQE7ik8etMPHDnM7:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/examples/contact_model/BUILD.bazel#L70)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks like this file was previously de-`//drake`-ed.  I feel we should avoid adding them back?
</blockquote></details>

Done

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.cc, line 65 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5ExGlDOYZuIisIkgYH:-L5JsU84OTozpVsibzXa:b34jb54) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.cc#L65)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW different boilerplate for calling our own `get_input_port` vs `get_output_port` numeric accessors is a bit confusing.  Is this deliberate?
</blockquote></details>

Can you elaborate on this? I assume you're alluding to the fact that this uses a literal instead of a stashed value? If that's correct, no elaboration required and I've made them match. If I misunderstood, please let me know.

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Ev7hQLAN0bMI14xAb:-L5JtGIozTba4FHlbigF:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L55)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW perhaps this paragraph and the next which explain the table entries and columns would be more helpful if they appeared before the table itself.
</blockquote></details>

Done

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5Evdk8NlOziqPjNsle:-L5JtJMZQ_A2mfQMNdPL:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L105)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

extra whitespace before `*/`?
</blockquote></details>

Done

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 106 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EwINQjO78oNmIoJcx:-L5JtbSFT40T33gqL6Kd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L106)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Document lifetime requirements of `rigid_body_tree` (it appears it must remain valid for the lifetime of the instance?)
</blockquote></details>

Done

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.h, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5EwkIw7kFefsbfzBT1:-L5Jtdc0GFmreiWgMnfE:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.h#L119)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

extra whitespace 'geometries  to`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5Jtt6-R_PeNKLmhXbS:b-b4ng8i)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.cc, line 65 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5ExGlDOYZuIisIkgYH:-L5KHGXAb81Z7lg5H7Co:b-12tl5z) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.cc#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Can you elaborate on this? I assume you're alluding to the fact that this uses a literal instead of a stashed value? If that's correct, no elaboration required and I've made them match. If I misunderstood, please let me know.
</blockquote></details>

oh, I meant the `this->` vs `systems::System<T>::`.  sorry, I should have said that up front.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant_bridge.cc, line 65 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-L5ExGlDOYZuIisIkgYH:-L5Orc3P8mCFsnVhS6zA:b-p59nlt) ([raw file](https://github.com/robotlocomotion/drake/blob/3fa5bd63e42dfdfe720a215712240414cab250e8/multibody/rigid_body_plant/rigid_body_plant_bridge.cc#L65)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

oh, I meant the `this->` vs `systems::System<T>::`.  sorry, I should have said that up front.
</blockquote></details>

Oh...dur.  :-/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5PChguXTBxKJxCiPjd:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8027#-:-L5PQEMAuYw2AF7LOi2N:b-l70wzf)*

**Pull request merged**
