### PR TITLE
wrap_function: Preserve return type for mutable and const class methods

### LINKED ISSUE #15505: [pydrake] WrapDeprecated seems to strip out references
# Problem

Consider the following code:

```c++
class FooSystem : public systems::LeafSystem<double> {
 public:
  FooSystem() : systems::LeafSystem<double>() {
    port1_ =
        this->DeclareAbstractOutputPort("port1", &FooSystem::Calc1).get_index();
    port2_ =
        this->DeclareAbstractOutputPort("port2", &FooSystem::Calc1).get_index();
  }
  const systems::OutputPort<double>& get_output_port1() const {
    return systems::System<double>::get_output_port(port1_);
  }
  const systems::OutputPort<double>& get_output_port2() const {
    return systems::System<double>::get_output_port(port2_);
  }

 private:
  void Calc1(const systems::Context<double>& context, double* output) const {
    *output = context.get_time() + 1.0;
  }
  void Calc2(const systems::Context<double>& context, double* output) const {
    *output = context.get_time() + 2.0;
  }
  int port1_{-1};
  int port2_{-1};
};

void BindStuff(py::module m) {
  using Class = FooSystem;
  py::class_<Class> cls(m, "FooSystem", "class doc");
  cls  // BR
      .def(py::init(), "Constructor")
      .def("get_output_port1", &Class::get_output_port1,
          py_rvp::reference_internal, "Port 1 doc")
      .def("get_output_port2", 
          WrapDeprecated("Deprecated 2038-01-01", &Class::get_output_port2),
          py_rvp::reference_internal, "Port 2 doc");
}
```

We define a simple system with two output ports (the functionality of the port is irrelevant). We bind the class and the port accessors in the very simple, direct way.

In the bindings, the two output ports were bound in the same way initially. However, the code above shows the effort to deprecate output port 2. The attempt uses `WrapDeprecated`. This produces the following error (file paths and line numbers are meaningless, but the final error, pointing to `WrapDeprecated` is what's important):

```
In file included from bindings/pydrake/geometry_py.cc:9:
In file included from bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/cpp_template_pybind/drake/bindings/pydrake/common/cpp_template_pybind.h:12:
In file included from bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/cpp_param_pybind/drake/bindings/pydrake/common/cpp_param_pybind.h:14:
In file included from bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/wrap_pybind/drake/bindings/pydrake/common/wrap_pybind.h:13:
bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/wrap_function/drake/bindings/pydrake/common/wrap_function.h:53:12: error: call to deleted constructor of 'drake::systems::OutputPort<double>'
    return (self->*method)(std::forward<Args>(args)...);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/deprecation_pybind/drake/bindings/pydrake/common/deprecation_pybind.h:79:26: note: in instantiation of function template specialization 'drake::pydrake::internal::infer_function_info<const drake::systems::OutputPort<double> &, drake::pydrake::(anonymous namespace)::FooSystem>' requested here
      message, internal::infer_function_info(std::forward<Func>(func)));
                         ^
bindings/pydrake/geometry_py.cc:1009:13: note: in instantiation of function template specialization 'drake::pydrake::WrapDeprecated<const drake::systems::OutputPort<double> &(drake::pydrake::(anonymous namespace)::FooSystem::*)() const>' requested here
            WrapDeprecated("Deprecated 2038-01-01", &Class::get_output_port2),
            ^
bazel-out/k8-opt/bin/tools/install/libdrake/_virtual_includes/drake_shared_library/drake/systems/framework/output_port.h:68:35: note: 'OutputPort' has been explicitly marked deleted here
  DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(OutputPort)
```

Ultimately, it's complaining that it's trying to bind a function whose return value can't be copied or moved. Somehow, the process of wrapping the function has changed the signature.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #15505

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15507)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please! +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15507#-:-Mfj8vj86gBEShXrcG5_:b-k7on0a)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X 2

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15507#-:-MfmV9vL5uDEUbJynUMQ:b-jhwbj9)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/common/wrap_function.h, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15507#-MfmUUkSEplYMHL8AphS:-MfmUUkSEplYMHL8AphT:b8n1oot) ([raw file](https://github.com/robotlocomotion/drake/blob/416ddeabba037d36a3a9f8d4bc7bdca15d4cd87a/bindings/pydrake/common/wrap_function.h#L43)):*
> ```objc
> template <typename Return, typename Class, typename... Args>
> auto infer_function_info(Return (Class::*method)(Args...)) {
>   auto func = [method](Class* self, Args... args) -> Return {
> ```

BTW Wow. I wouldn't have guessed that would be the fix. Even given this as the solution, I still can't explain it. I would've bet big money that the explicitly declared return type wold be 100% redundant. But it clearly isn't. Can you enlighten me?

**Comment by EricCousineau-TRI** [comment]
I don't have a good reference on hand, but especially for lambdas, it's important know diff. btw `-> auto` vs. `-> decltype(auto)` or `-> auto&&`.

Hacky empiricism FTW!
https://github.com/EricCousineau-TRI/repro/blob/6f2f280e/cpp/auto_lambda_return.cc

**Comment by EricCousineau-TRI** [comment]
Oh ya, also, in this case: `Return` has the qualifiers baked in `const T&`; however, without a trailing return type specification, it's interpreted as `auto`, which then resolves to `T` in this case.

**Comment by jwnimmer-tri** [comment]
Items 1 through 4 of "Effective Modern C++" are probably a good reference for this.

**Comment by SeanCurtis-TRI** [comment]
> without a trailing return type specification, it's interpreted as auto, which then resolves to T in this case.

That's the part that surprised me. I would've thought that given:

```c++
Bar& bar() { ... }

auto lambda_bar =[]() { return bar(); }
```

That the inference of the lambda's return type would most logically come from the function being called. But the fact that it's *further* processed seems....so odd.

**Pull request merged**
