### PR TITLE
[planning] Add RobotCollisionType

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Towards #14431.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIZ8ma5D7N9H8BxQo34:bax1t9m)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
It's our expectation that the feature review is going to be largely rubber stamp-y, but we're going out of way to make sure that neither of us are the platform reviewers, right?

Also, do we have an expectation for Anzu PR cadence?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIZThM72BoLahIAjCRO:b-fpb50o)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIZUGgZ5boh5mJhcwFz:bmxilld)* status: needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
I'm working on the Anzu PR presently; maybe posted tonight or tomorrow.

+@sherm1 for next-available non-co-author platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIZaZUZ9Xly9QKeiBq1:bip6jri)* status: LGTM missing from assignee sherm1(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor style suggestions

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIZlLW30lUAzo5Ktjfj:b-c4c4i1)* status: 2 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

___
*[`planning/robot_collision_type.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18405#-NIZgFC53FGdefZ-P8t2:-NIZgFC53FGdefZ-P8t3:b-g6clc6) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5afca07aabc1acfcf160e1fd96cdcee2e0347d/planning/robot_collision_type.h#L15)):*
> ```objc
>   kEnvironmentCollision = 0x01,
>   kSelfCollision = 0x02,
>   kEnvironmentAndSelfCollision = 0x03
> ```

BTW if the intent is that one of these is a combination of the others, consider writing it that way:



_Code snippet:_
```objc
kEnvironmentAndSelfCollision = 
    kEnvironmentCollision | kSelfCollision
```
___
*[`planning/test/robot_collision_type_test.cc` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18405#-NIZhqZi0_E66PIYbvlp:-NIZhqZi0_E66PIYbvlq:b7j7sja) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5afca07aabc1acfcf160e1fd96cdcee2e0347d/planning/test/robot_collision_type_test.cc#L21)):*
> ```cpp
>   RobotCollisionType input;
>   bool in_collision;
>   RobotCollisionType output;
> ```

BTW consider default-initializing these members with `{}` or values for style points

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405)* status: 2 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri and @sherm1)

___
*[`planning/test/robot_collision_type_test.cc` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18405#-NIZhqZi0_E66PIYbvlp:-NIZr-yO7G6nynKpRJ0j:bj9r41d) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5afca07aabc1acfcf160e1fd96cdcee2e0347d/planning/test/robot_collision_type_test.cc#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider default-initializing these members with `{}` or values for style points
</blockquote></details>

They should definitely be moustache-initialized. And the styleguide particularly calls for `enums` being value initialized (and not default).

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm going to go out on a limb and guess that you'll get a merge commit here -- but it'll be a merge commit on commits that have been rebased. (I hope I'm wrong...)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18405#-:-NIcwG3X9ohxyChx0wNA:bl07mao)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform), base commit is latest master (waiting on @rpoyner-tri)

**Pull request merged**
