### PR TITLE
Bind DeformableModel::AddFixedConstraint

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) 
+@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-:-O7BNbefAMC7A-DIXtjL:bu7gv6d)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-:-O7BP-jjEg_2YByMU9t0:b-85g6de)* status: 4 unresolved discussions

___
*[`bindings/pydrake/multibody/plant_py.cc` line 1698 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BNzjXCT_URiU3QzEt:-O7BNzjXCT_URiU3QzEu:b-fp2hbl) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/plant_py.cc#L1698)):*
> ```cpp
>         .def("GetDiscreteStateIndex", &Class::GetDiscreteStateIndex,
>             py::arg("id"), cls_doc.GetDiscreteStateIndex.doc)
>         .def("AddFixedConstraint", &Class::AddFixedConstraint,
> ```

nit Shouldn't this be moved up by one (prior to Get...Index) so it matches the header file order?
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOQPg-3qAlfxoWTEb:-O7BOQPg-3qAlfxoWTEc:bq0j9l) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3352)):*
> ```Python
> 
>         spatial_inertia = SpatialInertia_[float].SolidBoxWithDensity(
>             density=1000, lx=0.1, ly=0.2, lz=0.3)
> ```

nit We can drop the `_[float]` here -- we've imported `SpatialInertia` already.  Also probably there is a less-verbose constructor we could call?  We don't care about the shape details?
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3354 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOdd5D9IQtgB1KmBT:-O7BOdd5D9IQtgB1KmBU:b-qtdmdt) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3354)):*
> ```Python
>             density=1000, lx=0.1, ly=0.2, lz=0.3)
>         rigid_body = plant.AddRigidBody("rigid_body", spatial_inertia)
>         box = Box(1., 1., 1.)
> ```

nit GSG can't write `1.` for floats -- either use `1` or `1.0`.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOomr4h4SFYR9zBEy:-O7BOomr4h4SFYR9zBEz:bd4y7w4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3360)):*
> ```Python
>                                body_B=rigid_body,
>                                X_BA=X_BA, shape=box,
>                                X_BG=X_BG)
> ```

BTW It's not _wrong_ per se, but using local variables here seems like extra chaff we don't need?



_Suggestion:_
```Python
        dut.AddFixedConstraint(body_A_id=body_id,
                               body_B=rigid_body,
                               X_BA=RigidTransform(),
                               shape=Box(1, 1, 1),
                               X_BG=RigidTransform())
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930)* status: 1 unresolved discussion

___
*[`bindings/pydrake/multibody/plant_py.cc` line 1698 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BNzjXCT_URiU3QzEt:-O7BR89p2LAGkUiFZefu:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/plant_py.cc#L1698)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Shouldn't this be moved up by one (prior to Get...Index) so it matches the header file order?
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOQPg-3qAlfxoWTEb:-O7BS3006TqBZEDPyF7f:bytykwp) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We can drop the `_[float]` here -- we've imported `SpatialInertia` already.  Also probably there is a less-verbose constructor we could call?  We don't care about the shape details?
</blockquote></details>

I don't think we imported `SpatialInertia` and we definitely didn't alias it in this test.

Re detail: I want a valid spatial inertia here, but there's no easy constructor for an arbitrary spatial inertia that's non-zero and non-nan.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3354 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOdd5D9IQtgB1KmBT:-O7BRQc_6BR-LqDNWnA3:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3354)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit GSG can't write `1.` for floats -- either use `1` or `1.0`.
</blockquote></details>

Done
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOomr4h4SFYR9zBEy:-O7BS1xp6Ki_0HwGz2Eu:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW It's not _wrong_ per se, but using local variables here seems like extra chaff we don't need?
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOQPg-3qAlfxoWTEb:-O7BTpqNA6ye22dohUDh:b-5bd6ki) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3352)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think we imported `SpatialInertia` and we definitely didn't alias it in this test.

Re detail: I want a valid spatial inertia here, but there's no easy constructor for an arbitrary spatial inertia that's non-zero and non-nan.
</blockquote></details>

Ah right, I misread the existing code in terms of the imports.

For shortening, I was thinking even just `SolidCubeWithDensity(1, 1)` would be shorter.  I guess not _that_ much shorter, though, so this is fine.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 3352 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21930#-O7BOQPg-3qAlfxoWTEb:-O7BWFuG2_h0E2xvbTrq:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/3197b95ff6375c946d93822137fa60ffd06828d5/bindings/pydrake/multibody/test/plant_test.py#L3352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah right, I misread the existing code in terms of the imports.

For shortening, I was thinking even just `SolidCubeWithDensity(1, 1)` would be shorter.  I guess not _that_ much shorter, though, so this is fine.
</blockquote></details>

Done, thanks.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21930)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
