### PR TITLE
wrap Expression::Expand in python

### PR DESCRIPTION
**Pull request by rdeits**
needed to work around #5086

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5245)

### CODE REVIEW

**Comment by rdeits** [comment]
+@soonho-tri +@hongkai-dai 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWjFGdF18KUAQENMVA:b3ufea1)*

**Comment by soonho-tri** [comment]
:lgtm:

Do we have a plan to have test cases on Python side?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWjTfKtfGjOBEOdGxO:b-dm9zid)*

**Comment by rdeits** [comment]
done!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWljKE7kiY7fik5yDI:b-7rl0jq)*

**Comment by soonho-tri** [comment]
Thanks!!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWouBsMzYKNMknbqjl:b-hay2ia)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWxpqxNfDB7kW3SZjQ:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-@soonho-tri as feature review. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWxsDevSlOqJG8kdU_:b-v3s7mu)*

**Comment by hongkai-dai** [comment]
+@soonho-tri as platform reviewer

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWy1ziGmyc5nJjSw7p:b6g3h4a)*

**Comment by soonho-tri** [comment]
+@david-german-tri , platform-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWyB96psG2je7hiFWy:b-qoa6av)*

**Comment by soonho-tri** [comment]
@hongkai-dai : I am still under the training and do not have the platform-reviewer badge/bit yet.

@david-german-tri : FWIW, I think the simple test that we have here is good enough since we have a long list of functional tests on C++ side.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdWyNYi37-A5IRDuvTI:b-9n1a12)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5245#-:-KdXK4u93cHEAL7JPZzY:bnfp4nl)*

**Pull request merged**
