### PR TITLE
Use system IPOPT

### LINKED ISSUE #6513: Don't use genrule to compile IPOPT
Using a `genrule()` to compile C++ software is frowned upon by Bazel upstream, but that's currently how we're building IPOPT.  We should either write `BUILD` file(s) for IPOPT, create a pre-compiled shared library release (e.g. with a Dockerfile), or use the OS's default build of IPOPT (debs /homebrew).  (The OS build may be insufficient; see #4913).

There are several problems with using a genrule:
- the compile step is slow (lots of software), and even with "half the cores" it takes a while locally and is worse in CI;
- because its a genrule, its dependencies are too wide (e.g. on environment variables) and thus it recompiles too often, such as when switching between CLion and console builds (see #6500);
- while we could pass `$COMPILATION_MODE` through the genrule (debug vs release), we cannot pass any other e.g. `$CXX` or `$CXXFLAGS` from `CROSSTOOL` into the compilation step.  Thus, our builds will _always_ use GCC for IPOPT, even if the user has otherwise selected `clang` as their compiler.

Probably the #4913 fix should be rolled into this effort.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This PR changes Bazel to seek IPOPT via pkg-config (i.e., from the host system) on Mac and Xenial, but leaves it unchanged on Trusty.  (The Trusty version of IPOPT is broken, so we should not use it.)  This unconditionally removes the install target for IPOPT, because we will not support installation on Trusty.

This makes the genrule build uncommon enough to declare this closes #6513.

This solves #4913 for Mac and Xenial, but I'll leave that issue open until Trusty is removed.

For now, we expect pre-merge CI to fail, because this adds new packages to install_prerequisites.  Once this passes code review and `-unprovisioned-` CI, we can update the default image(s).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7027)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Do you want me to an upload IPOPT binary to S3 for Trusty?

**Comment by jwnimmer-tri** [comment]
Thanks, maybe eventually, but for the moment I'd like to experiment a little more first.  I ran out of time this week, I'll probably pick it up again next week.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
The CI failures are exactly as intended now.  If the code review is accepted, we'll update Jenkins with the new prereqs and then rebuild.

+@jamiesnape for feature review if you have time, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/os.bzl, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-KuS5kC4KoHZ_xfOrYJ9:-KuS5kC5EHw62CfUfQCz:bgfzrhf) ([raw file](https://github.com/robotlocomotion/drake/blob/bb8d39b13d22896b7b2f089f6da6c554d2d2c757/tools/os.bzl#L115)):*
> ```Python
>     - Anything else, via "default"
>     """
>     name = repository_ctx.name
> ```

Dead code.  I'll remove this line in the next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuS5KtbX3fb5uOgSFUC:b-eivzfv)*

**Comment by jamiesnape** [comment]
Add a TODO somewhere appropriate to remove the source build when Trusty support disappears?

:lgtm: 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuUICHgrZTG6z63F_sV:b6np6qt)*

**Comment by jamiesnape** [comment]
Currently testing locally on macOS Sierra and macOS High Sierra GM Candidate. High Sierra will take a while as Homebrew formulae `ampl`, `ipopt`, and `mumps` do not have bottles yet.

**Comment by jamiesnape** [comment]
Noting https://github.com/Homebrew/homebrew-science/issues/5470 means `mumps` will at best always be built from source on all versions of macOS.

**Comment by ggould-tri** [comment]
:lgtm: ; one request below.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[WORKSPACE, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-KuUVp1RkCRdV9lzgweh:-KuUVp1RkCRdV9lzgwei:b-clas5k) ([raw file](https://github.com/robotlocomotion/drake/blob/bb8d39b13d22896b7b2f089f6da6c554d2d2c757/WORKSPACE#L211)):*
> ```Python
> 
> # Build our own IPOPT; this is conditionally aliased into @ipopt above, or else
> # ends up unused (will not be compiled).
> ```

As I understand the PR message thread, this mechanism should go away once trusty support is dropped.  If that is correct, please comment it here (or on the `os_specific_alias_repository` block above) so later readers will understand the repository yak-juggling going on here and when they can safely delete it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuUYBHMVEGLXuJAomfo:bm8hwos)*

**Comment by jwnimmer-tri** [comment]
OK It sounds like we're in roughly good shape here.

@jamiesnape At some point in the next couple days if possible, would you please update the CI images to reflect the two setup script amendments?  Waiting for your local testing first is fine.

FYI @soonho-tri in case you want to test this locally on OSX, though there is already a bunch of Mac testing happening from Jamie and in CI, and I have tested on `macsim`.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-KuUZL6sKZ5_YsUemRj6:-KuUZL6sKZ5_YsUemRj7:b-in04tn) (no related file):*
DNM; this PR needs CI testing of `-unprovisioned-` builds after the next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuUYqCa-OzZq1dmxTYu:b-nr78hs)*

**Comment by jamiesnape** [comment]
I am getting failures on `MG_chaotic_babyboot_test` on both macOS platforms, not sure they are related to this change. Just checking master.

**Comment by jwnimmer-tri** [comment]
Yeah, that test is new as of yesterday, and is broken on Mac master; see #7056.

**Comment by jamiesnape** [comment]
Ok, so I think we are good on Mac.

**Comment by jamiesnape** [comment]
Does this use a shared or static IPOPT? If it uses shared, you may need to add something to https://github.com/RobotLocomotion/drake/blob/master/tools/drake.cps#L83 since Bazel does not link its dependencies.

**Comment by jwnimmer-tri** [comment]
@jamiesnape It uses shared, but it seems OK to me:

```console
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel run :install -- /home/jwnimmer/jwnimmer-tri/drake-distro/tmp 
...
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ ldd tmp/lib/libdrake.so
...
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f3587373000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f3586b8f000)
	libmumps_common_seq-4.10.0.so => /usr/lib/libmumps_common_seq-4.10.0.so (0x00007f3584999000)
...
```
though this isn't in a clean provision (I think my blas is a different /etc/alternatives).

Do you think I should do more testing somehow?  Is there a better way to validate than ldd?

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-KuUVp1RkCRdV9lzgweh:-KuUjpRryI0mwXThjv-j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bb8d39b13d22896b7b2f089f6da6c554d2d2c757/WORKSPACE#L211)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

As I understand the PR message thread, this mechanism should go away once trusty support is dropped.  If that is correct, please comment it here (or on the `os_specific_alias_repository` block above) so later readers will understand the repository yak-juggling going on here and when they can safely delete it.
</blockquote></details>

Done.

---

*[tools/os.bzl, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-KuS5kC4KoHZ_xfOrYJ9:-KuUjqAZEzx1lHIrOA5W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bb8d39b13d22896b7b2f089f6da6c554d2d2c757/tools/os.bzl#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Dead code.  I'll remove this line in the next push.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuUhV89J_ycjX0LFSuA:b-wc19g2)*

**Comment by jamiesnape** [comment]
Is `/usr/lib/libipopt.so`linked?

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuUlAqmyx2UOPI5i2lj:b-e8f930)*

**Comment by jwnimmer-tri** [comment]
Oops, yes it is.  I accidentally elided it above -- I re-edited the above with the info.

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027)*

**Comment by jamiesnape** [comment]
Everything is fine with the linking on Mac too, so no changes are needed to `drake.cps`.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , it works on my local mac.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7027#-:-KuVIRqbnsLnK61uw0S0:bde9bas)*

**Comment by jamiesnape** [comment]
@BetsyMcPhail is working on updating all the images.

**Comment by BetsyMcPhail** [comment]
The Xenial image has been updated. As always, it might take awhile for Jenkins to cycle through the old images.

Working on the Mac images next.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by BetsyMcPhail** [comment]
Mac has also been updated.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by liangfok** [comment]
Not certain yet but this PR might have caused the following CI failures:

* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/137/
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/138/

**Comment by jwnimmer-tri** [comment]
`//drake/examples/kuka_iiwa_arm/pick_and_place:pick_and_place_state_machine_test` timeouts?  Possibly to blame, but I'd suggest pinging the manipulation folks.  IIRC those are finicky, and should simply be disabled under valgrind.

**Comment by sammy-tri** [comment]
`//drake/examples/kuka_iiwa_arm/pick_and_place:pick_and_place_state_machine_test` shouldn't be finicky, it doesn't run a simulation.  It does seem to be taking longer to run under `memcheck` builds than it used to while producing the same result (eventually).

**Comment by jwnimmer-tri** [comment]
Ok, thanks.  I would be curious to know if the `release` timing for this test changed with the switch-over.

**Pull request merged**
