### PR TITLE
[doc] Add release notes v1.32.0

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.32.0.md` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-O47jBRh42pk1-HwvxRU:-O47jBRh42pk1-HwvxRV:b-5wt7lq) ([raw file](https://github.com/RobotLocomotion/drake/blob/87ca22fdf19faee44b6569a961d7021d8d7c8ee7/doc/_release-notes/v1.32.0.md#L68)):*
> ```Markdown
> * Fix a bug in computing OrientationCost ([#21785][_#21785])
> * Always use the convex hull for Convex shapes ([#21779][_#21779])
> * Clarify Frame dependencies on Parameters vs Context ([#21661][_#21661])
> ```

nit No "fix" note for this one (21661) -- for users, this PR was _only_ the breaking change (already noted atop this doc sufficiently).  In other words, please remove this line.

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri +@SeanCurtis-TRI +@amcastro-tri for reviews. Feel free to push to the commit.
-(status: do not review) +(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-:-O47jNNk85XvV5wrBNf_:b-rqj0vy)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),amcastro-tri, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)* status: LGTM missing from assignees jwnimmer-tri(platform),amcastro-tri,SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.32.0.md` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-O47jBRh42pk1-HwvxRU:-O47juVL2CdSYJ23JYiL:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/87ca22fdf19faee44b6569a961d7021d8d7c8ee7/doc/_release-notes/v1.32.0.md#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit No "fix" note for this one (21661) -- for users, this PR was _only_ the breaking change (already noted atop this doc sufficiently).  In other words, please remove this line.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)* status: 1 unresolved discussion, LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform),sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.32.0.md` line 108 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-O4GaWwZ-lDpy3r_YmAO:-O4GaWwZ-lDpy3r_YmAP:bllkbkg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bebe02f2995cbe4ab6514029c7ad4c4446e141c6/doc/_release-notes/v1.32.0.md#L108)):*
> ```Markdown
> * Add binding for MultibodyPlant::CalcCenterOfMassTranslationalVelocity() ([#21730][_#21730])
> * Add binding for MultibodyPlant::CalcCenterOfMassTranslationalAcceleration() ([#21730][_#21730])
> * Add missing python bindings for mathematical program ([#21754][_#21754])
> ```

nit: This should enumerate the bindings.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform),sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.32.0.md` line 108 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-O4GaWwZ-lDpy3r_YmAO:-O4GfCJbA-G46fLLiOiB:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/bebe02f2995cbe4ab6514029c7ad4c4446e141c6/doc/_release-notes/v1.32.0.md#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This should enumerate the bindings.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform),sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-:-O4GySKw2QOg4oQvGFvI:b-b9fcpn)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform),sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-:-O4HoA2x8ch44bsMTFDh:b3dcro0)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-:-O4INgdl4jebB1khpkDk:bm9o57a)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
-@amcastro-tri -@SeanCurtis-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21803#-:-O4INkOb7f6WyT8AFxKx:bh99ab4)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
