### PR TITLE
Add operators overloading between Eigen::Array and scalar type for symbolic classes

### PR DESCRIPTION
**Pull request by soonho-tri**
With this PR, we can write the following:
```c++
Eigen::Array<Variable, 2, 2> a;
a << Variable{"x"}, Variable{"y"},
     Variable{"z"}, Variable{"w"};
Eigen::Array<Formula, 2, 2> f = (a == 0.0);
// Here f = |(x == 0.0)  (y == 0.0)|
//          |(z == 0.0)  (w == 0.0)|.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5656)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please. Thank you!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-:-KgN9SytPYz-699oUyuJ:b-4cootz)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-:-KgNKV_NAB7oUI7uDktx:b-yxxxc1)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 359 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-KgNL5GqR4Sf9wj_F9F5:-KgNL5GqR4Sf9wj_F9F6:b-k80odw) ([raw file](https://github.com/robotlocomotion/drake/blob/64210c0bb7e8eef2fde1429e29b86f44da55aaaf/drake/common/symbolic_formula.h#L359)):*
> ```objc
> ///     Eigen::Array<Formula, 2, 2> f = (a == 0.0);
> ///     // Here f = |(x == 0.0)  (y == 0.0)|
> ///     //          |(z == 0.0)  (w == 0.0)|.
> ```

I am a bit concerned with this overloading. If we have `a == 1.5`, will it be interpreted as 1.5 * Identity(), or 1.5 * Ones()? I think we do not have this ambiguity, if `a` is just a column vector. But if `a` has multiple columns (especially same number of rows as columns), there is ambiguity.

So I would propose that we either
1. Restrict this overloading, if `Derived::ColsAtCompileTime` is 1. or
2. Add documentation here, not for `v = 0`, but `v = 1`, to show that we `a = v` means `a(i,j) = v`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 359 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-KgNL5GqR4Sf9wj_F9F5:-KgP8QtA2sVTITWQ0HWy:bn9tzwh) ([raw file](https://github.com/robotlocomotion/drake/blob/64210c0bb7e8eef2fde1429e29b86f44da55aaaf/drake/common/symbolic_formula.h#L359)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am a bit concerned with this overloading. If we have `a == 1.5`, will it be interpreted as 1.5 * Identity(), or 1.5 * Ones()? I think we do not have this ambiguity, if `a` is just a column vector. But if `a` has multiple columns (especially same number of rows as columns), there is ambiguity.

So I would propose that we either
1. Restrict this overloading, if `Derived::ColsAtCompileTime` is 1. or
2. Add documentation here, not for `v = 0`, but `v = 1`, to show that we `a = v` means `a(i,j) = v`.
</blockquote></details>

The meaning of `a == 1.5` is the same as `a == 1.5 * Ones().array()`.

I'll update the documentation to use `v = 1` to clarify its semantics. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 359 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-KgNL5GqR4Sf9wj_F9F5:-KgPOaO3VRxNa7gpHFHI:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/64210c0bb7e8eef2fde1429e29b86f44da55aaaf/drake/common/symbolic_formula.h#L359)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

The meaning of `a == 1.5` is the same as `a == 1.5 * Ones().array()`.

I'll update the documentation to use `v = 1` to clarify its semantics. 
</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-:-KgQ0_iJf60eiC5Sk9h4:b-68p82t)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5656#-:-KgQEhZkqqk899uMz0TS:bnfp4nl)*

**Pull request merged**
