### PR TITLE
Revert "Add clone method to MathematicalProgram (#7667)"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This reverts commit 38954898b3d4e70a96f3b6822be4bef0dbdb5f14.

Dear @hongkai-dai ,

The on-call build cop, @m-chaturvedi, believes that your PR #7667 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
[1](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan/146/), [2](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan-everything/147/)

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7707)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2LgRyfBKz9DF-eaTuH:bnfp4nl)*

**Comment by hongkai-dai** [comment]
The problem is that I added a virtual method `MathematicalProgram::Clone()`, that is declared in `mathematical_program.h`, and defined in `mathematical_program.cc`. Each solver class includes `mathematical_program.h`, but does not link to `mathematical_program.so`. Instead each solver links to `mathematical_program_api.so`, which does not have `mathematical_program.cc` as the source. So in each of the solver, the virtual function `MathematicalProgram::Clone()` is declared but not defined.

The target `mathematical_program_api` is defined in https://github.com/RobotLocomotion/drake/blob/master/solvers/BUILD.bazel#L385~L416

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2LgTRP9qHKAXECfQEB:bkyryr8)*

**Comment by m-chaturvedi** [comment]
+@EricCousineau-TRI for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2LhlQXlvKJQeGzyELZ:b-r34yat)*

**Comment by EricCousineau-TRI** [comment]
Given that this is still a functional PR, is there an easy workaround?
Is this a linking order issue, or simply a missing-symbol issue? Is there a way to wrap these libraries to prevent this error, and maintain the PR?

Or is the longer term solution to decouple the solver interfaces from MathematicalProgram?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2M1YlJdC--PfDT7srL:brx84th)*

**Comment by EricCousineau-TRI** [comment]
If there is not, :LGTM:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2M4InVfEnGlnEiiwvo:b-3957yl)*

**Comment by hongkai-dai** [comment]
I have not figured out a solution yet, other than putting the definition of `Clone()` to the header file `mathematical_program.h`. 

The problem I see is that the definition of `Clone()` is missing in the `mathematical_program_api` target. I can send a PR to put the definition in `mathematical_program.h`, if you think that is acceptable.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2MHAvepI4hlQtPACuu:b-gkuzlq)*

**Comment by EricCousineau-TRI** [comment]
That's a potential solution, as it'd allow the type to be complete - this may may have linker errors for things like `AddDecisionVariables`, but then again, maybe it'll be able to resolve those?

Would it be possible to try that out in a separate PR and see if that passes `linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything`?

If that fails, does `Clone()` have to `virtual` for now? It will be important for downstream classes, but for now there could be something like:
```
assert(typeid(this) == typeinfo(MathematicalProgram));
```
to at least catch the workaround.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2MICFWXT_lL8RKtXGG:bg51x1d)*

**Comment by EricCousineau-TRI** [comment]
Ah, you just submitted the PR - nice!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7707#-:-L2MJSuYB3IGl3kMGU6h:bm6cm6y)*

**Comment by EricCousineau-TRI** [comment]
This should be closed once #7709 lands.

**Pull request closed without merging**
