### PR TITLE
Adds a rigid gripper

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This is the simplest approximation of testing gripping with the schunk
gripper.  Introduces a rigid gripper in a permanent pose of squeezing.
Simply runs the simulation to see if the box slides out of the perma-grip.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5388)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@liangfok for feature review, because I *know* you're having so much fun with these examples.  :)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeGFWMhjxvn0CyyLevS:b1zt6nj)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeGKQ54ua32pzer7Sh1:b-hnxhsq)*

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/contact_model/BUILD, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGU4wLxWymfw2cPaSe:-KeGU4wLxWymfw2cPaSf:b729l63) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/BUILD#L22)):*
> ```Python
>         "//drake/common:drake_path",
>         "//drake/common/trajectories:piecewise_polynomial",
>         "//drake/common/trajectories:piecewise_polynomial_trajectory",
> ```

BTW, please verify all of these are needed.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGR4stWKnWFFQ4hauc:-KeGR4stWKnWFFQ4haud:b15h9av) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L1)):*
> ```cpp
> // A simple example of a rigid gripper attempting to hold a block. The gripper
> ```

BTW, I'm curious whether this could be made into a `@file` doxygen block and have it rendered in the generated website.

_(This is optional.)_

---

*[drake/examples/contact_model/rigid_gripper.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGRuOUdJikSiDi4pL7:-KeGRuOUdJikSiDi4pL8:b-5o892o) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L2)):*
> ```cpp
> // A simple example of a rigid gripper attempting to hold a block. The gripper
> // has rigid geometry: two fingers a fixed distance from each other. They
> ```

"a" should be "at a".

---

*[drake/examples/contact_model/rigid_gripper.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGSD51Leu9KsGJPznw:-KeGSD51Leu9KsGJPznx:be3egs6) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L12)):*
> ```cpp
> // This is an even simpler example of what is shown in schung_wsg_lift_test.
> // This eliminates the PID controller and ground contact.  At the end of the
> // simulation time, the box should have slipped an amount less than the duration
> ```

BTW, consider deleting "time".

---

*[drake/examples/contact_model/rigid_gripper.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGR_VE5xZfuFD9NV5I:-KeGR_VE5xZfuFD9NV5J:b2jiq49) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L39)):*
> ```cpp
> #include "drake/systems/lcm/lcm_publisher_system.h"
> #include "drake/systems/primitives/constant_vector_source.h"
> #include "drake/systems/primitives/trajectory_source.h"
> ```

BTW, numerous headers above don't appear to be used, like sdf, pid, piecewise polynomial trajectory, etc. Please verify all of the above are needed.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTD2NOdu53Ayx8mjC:-KeGTD2NOdu53Ayx8mjD:b-bukj2x) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L61)):*
> ```cpp
>   std::unique_ptr<RigidBodyTreed> tree = std::make_unique<RigidBodyTreed>();
> 
>   /// Add the gripper.  Offset it slightly back and up so that we can
> ```

Should not be doxygen comment (`///` should be `//`).

---

*[drake/examples/contact_model/rigid_gripper.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTId2VLTQ32sxaUbD:-KeGTId2VLTQ32sxaUbE:b-wiw4t0) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L62)):*
> ```cpp
> 
>   /// Add the gripper.  Offset it slightly back and up so that we can
>   // locate the bos at the origin.
> ```

"bos" should be "box".

---

*[drake/examples/contact_model/rigid_gripper.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTmuzWviuaBef3VUh:-KeGTmuzWviuaBef3VUi:b-q7b8ye) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L81)):*
> ```cpp
>       multibody::joints::kQuaternion, box_frame, tree.get());
> 
>   tree->compile();
> ```

BTW, this is already called by the parser.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGT5KkRJOtuT0AKEw_:-KeGT5KlHPYN9KNT0ZR9:b-dw1yd0) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L85)):*
> ```cpp
> }
> 
> // Simple scenario of gripper lifting box.
> ```

This comment does not appear to be correct. No lifting appears to be occurring​.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGSq81ZFiPE9oLlIRf:-KeGSq81ZFiPE9oLlIRg:bf74mbw) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L111)):*
> ```cpp
>                   viz_publisher->get_input_port(0));
> 
>   // contact force visualization
> ```

BTW, cappunc per style guide.

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGQqfZuThRvVdvk5Kv:-KeGQqfZuThRvVdvk5Kw:bcsm1gf) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.urdf#L6)):*
> ```XML
>  xsi:schemaLocation="http://drake.mit.edu ../../../../doc/drakeURDF.xsd" name="rigid_gripper">
> 
>

**Comment by liangfok** [comment]
BTW, I just curated my comments by marking myself satisfied for the ones that I feel are entirely optional.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeJ5xpzOfp_Tvw5SSUX:by542ji)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed. PTAL

---

Review status: 0 of 4 files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/contact_model/BUILD, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGU4wLxWymfw2cPaSe:-KeKbbMEsdZfxTV7vcTq:b5f3vd4) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/BUILD#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, please verify all of these are needed.
</blockquote></details>

Done Good catch; lots of leftover relics from a previous incarnation.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGR4stWKnWFFQ4hauc:-KeKc4U20yGVQTGbjUTq:bv24567) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I'm curious whether this could be made into a `@file` doxygen block and have it rendered in the generated website.

_(This is optional.)_
</blockquote></details>

Done  I don't know why I didn't do that in the first place.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGRuOUdJikSiDi4pL7:-KeKc9rIJ_wzPVGnz4RR:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"a" should be "at a".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGSD51Leu9KsGJPznw:-KeKcEeVb8hCDECLt6aV:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L12)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "time".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGR_VE5xZfuFD9NV5I:-KeKcH479icxYeOG5Fhg:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L39)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, numerous headers above don't appear to be used, like sdf, pid, piecewise polynomial trajectory, etc. Please verify all of the above are needed.
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTD2NOdu53Ayx8mjC:-KeKdgkuj2oKI2zqZvJz:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should not be doxygen comment (`///` should be `//`).
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTId2VLTQ32sxaUbD:-KeKdlobxZgh-KSLTkP3:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L62)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"bos" should be "box".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGTmuzWviuaBef3VUh:-KeKdpS73kBb0HpdL5Li:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L81)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this is already called by the parser.
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGT5KkRJOtuT0AKEw_:-KeKdujYhIBLkN9SQG2v:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L85)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This comment does not appear to be correct. No lifting appears to be occurring​.
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGSq81ZFiPE9oLlIRf:-KeKdzXSo_NcYcfq6dR5:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.cc#L111)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, cappunc per style guide.
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGQqfZuThRvVdvk5Kv:-KeKe9pkyVIW2jZINdLC:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.urdf#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "placement of" with "spacing between".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGPEkwbXKnaUf1SYpo:-KeKeByO546R9XLFcwax:bsvi38n) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.urdf#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Extra "the".
</blockquote></details>

Done (What can I say, I wanted to be doubly definite about that article.)

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGPzRmxEf9_cy69rCf:-KeKeIx92wuzeAPXUHUB:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.urdf#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"0.25" should be "0.025".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeGQ8SVfi-mJYV_Qrfw:-KeKecBqKjvoMo2_mWc2:b545h2z) ([raw file](https://github.com/robotlocomotion/drake/blob/eeef143b17c9a5a1d85edd8b49c33700d5ae2f74/drake/examples/contact_model/rigid_gripper.urdf#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should "radius" be "contact radius"?
</blockquote></details>

Done  (Modified in an alternate, but hopefully still satisfying, way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeKhScHtI4qx9cbhQuT:byq25nx)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/CMakeLists.txt, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeKjg7LHOXhXXSn7afx:-KeKjg7LHOXhXXSn7afy:b-twu9gd) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/CMakeLists.txt#L2)):*
> ```CMake
> if (lcm_FOUND AND Bullet_FOUND)
>   add_executable(sliding_bricks sliding_bricks.cc)
> ```

BTW, looks like this PR may need to be rebased with `master`. This is from #5296. Not sure why it's appearing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeKkALsGUG-qSomiaOG:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Thanks @liangfok 

+@ggould-tri  and even more contact model fun (with one more waiting in the wings...although you'll probably miss it.)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/CMakeLists.txt, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeKjg7LHOXhXXSn7afx:-KeKuIcUDsHfa2a08Ak_:bwf5k0v) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/CMakeLists.txt#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, looks like this PR may need to be rebased with `master`. This is from #5296. Not sure why it's appearing here.
</blockquote></details>

It has been rebased -- there was a race condition between three PRs.  Once the first one landed, I went to rebase the others.  We should be kosher now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeKuSez1rflPpjWpOM3:b-7yhf03)*

**Comment by ggould-tri** [comment]
Will not get to this until Monday.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeKwuydF4ILLXFpRMcq:b-3s1kjl)*

**Comment by SeanCurtis-TRI** [comment]
That was my expectation based on your earlier announcement. No worries.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeL30II4B6iqpoM8deY:bz973bj)*

**Comment by ggould-tri** [comment]
:lgtm: pending some small items below.

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ0PMdD-Q0wUZfH6V1:-KeZ0PMdD-Q0wUZfH6V2:b-2p3aym) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.cc#L14)):*
> ```cpp
> This eliminates the PID controller and ground contact.  At the end of the
> simulation, the box should have slipped an amount less than the duration
> length times v_stiction_tolerance (i.e., the highest allowable slip speed
> ```

No such thing as `v_stiction_tolerance` in this file.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ08k08QrqLUkCtkPu:-KeZ08k08QrqLUkCtkPv:b-4mcs5n) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.cc#L45)):*
> ```cpp
>               "The maximum slipping speed allowed during stiction");
> DEFINE_bool(playback, true,
>             "If true, simulation beings looping playback when complete");
> ```

FYI typo "beings".

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ-QFn2qDCA2daxyer:-KeZ-QFo-s6ue6J2WOm2:bls46js) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.urdf#L15)):*
> ```XML
>       <origin xyz="0 -0.03525 0" rpy="0 0 0" />
>       
>       <mass value="1.088882"/>
> ```

BTW --  why is this a slightly different arbitrary no-quite-1 mass than the SDF Schunk?  Not that it matters particularly, but it was weird enough the first time (I think that one was gazebo spoor) to be doubly weird when repeated with a variation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeZ0kuQD4JEhNjakUMq:b-bzd6ie)*

**Comment by SeanCurtis-TRI** [comment]
Updated

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/contact_model/rigid_gripper.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ0PMdD-Q0wUZfH6V1:-KeZV2dVuuFKe3bURlw9:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.cc#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

No such thing as `v_stiction_tolerance` in this file.
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ08k08QrqLUkCtkPu:-KeZV69uXSc9GR8qmFP3:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.cc#L45)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "beings".
</blockquote></details>

Done

---

*[drake/examples/contact_model/rigid_gripper.urdf, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-KeZ-QFn2qDCA2daxyer:-KeZVRNG00WMbCZjVgYc:b152ffp) ([raw file](https://github.com/robotlocomotion/drake/blob/ab7b0a2502bd5600bcbe10d3bb7227879650a9b3/drake/examples/contact_model/rigid_gripper.urdf#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW --  why is this a slightly different arbitrary no-quite-1 mass than the SDF Schunk?  Not that it matters particularly, but it was weird enough the first time (I think that one was gazebo spoor) to be doubly weird when repeated with a variation.
</blockquote></details>

I've updated the note; this one body contains the mass of the gripper body *plus* the fingers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388#-:-KeZVtInTxut97xgEOoH:b-bu91xm)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388)*

**Comment by liangfok** [comment]
Reviewed 2 of 4 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5388)*

**Pull request merged**
