### PR TITLE
Refactoring of the kuka arm sim and gtest added

### PR DESCRIPTION
**Pull request by naveenoid**
Keeps the prior example but builds out a new test with a gtest. 

@liangfok  : Please modify as needed. Once ready, feel free to assign reviewers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2933)

### CODE REVIEW

**Comment by liangfok** [comment]
Just added some notes to myself (I'll be fixing them).

I successfully ran the unit test by executing:

```
drake-distro/build/install/bin/drake-visualizer
drake-distro/build/drake/bin/kuka_iiwa_arm_test
```

+@liangfok 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgC2X70k_cuhBUL-yq:-KNgC2X70k_cuhBUL-yr:-689984806) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L21)):*
> ```CMake
>   target_link_libraries(kuka_iiwa_arm_test  drakeKukaIIWAArm drakeRBSystem drakeLCMSystem threads
>           ${GTEST_BOTH_LIBRARIES})
>     add_test(NAME testIIWAArm COMMAND kuka_iiwa_arm_test)
> ```

Test name should equal executable name.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.cc, line 71 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgCJku3RGMSsrbh7Pe:-KNgCJkvNmz97u4kqtHk:-1681784080) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.cc#L71)):*
> ```cpp
> //    throw std::runtime_error(
> //        "ERROR: Size of final robot state (" +
> //            std::to_string(final_robot_state.size()) +
> ```

delete

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgCVmHrBN8SnKMDRMi:-KNgCVmHrBN8SnKMDRMj:304991612) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L23)):*
> ```objc
> namespace kuka_iiwa_arm {
> /**
>  * Ceates the rigid body system of the IIWA arm to be
> ```

"Creates" typo

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 64 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBVUIXv9UpV5Pigsw:-KNgBVUIXv9UpV5Pigsx:-1681784080) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L64)):*
> ```objc
>  * This method simply throws an error if limits are generated.
>  */
> //void ValidateSimulation(const std::shared_ptr<RobotStateTap<RigidBodySystem::StateVector>>& robot_state_tap,
> ```

delete

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBRarpSTIgnGXXJya:-KNgBRarpSTIgnGXXJyb:-2100615301) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L68)):*
> ```objc
> }
> }
> }
> ```

Missing new line.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBXckt5tScEScBd2o:-KNgBXckt5tScEScBd2p:-1681784080) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L45)):*
> ```cpp
> //  Eigen::MatrixXd Kp = Eigen::VectorXd::Constant(7,100.0).asDiagonal();
> //  Eigen::MatrixXd Kd = Eigen::VectorXd::Constant(7,50.0).asDiagonal();
> //  auto robot_with_pd = std::allocate_shared<PDControlSystem<RigidBodySystem>>(
> ```

delete

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 70 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBb9euQ4V4zJUfL3z:-KNgBb9euQ4V4zJUfL4-:-1681784080) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L70)):*
> ```cpp
>   Drake::simulate(*sys.get(), kStartTime, duration, x0, options);
> //
> //  ASSERT_NO_THROW(ValidateSimulation(robot_state_tap, iiwa_system));
> ```

delete

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBdOwcFFb2E9Uazzq:-KNgBdOwcFFb2E9Uazzr:-197526424) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L73)):*
> ```cpp
> }
> 
> } // close namespace
> ```

Is this style guide compliant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNgCMnUfWNk5nq6Yfld:-21922248)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgDO_udw51RxblAVaJ:-KNgDO_udw51RxblAVaK:1383939307) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L43)):*
> ```cpp
> 
> //  Build up PD controller in this form.
> //  Eigen::MatrixXd Kp = Eigen::VectorXd::Constant(7,100.0).asDiagonal();
> ```

Move this file to `test/` subdirectory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/CMakeLists.txt, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgC2X70k_cuhBUL-yq:-KNhMc9PwVJC7NW-7i7L:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/CMakeLists.txt#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Test name should equal executable name.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.cc, line 71 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgCJku3RGMSsrbh7Pe:-KNhNUdJVU0OzVo9UlK5:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.cc#L71)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> delete
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgCVmHrBN8SnKMDRMi:-KNhNZ_Vh4DRlo6HXuQU:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "Creates" typo
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 64 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBVUIXv9UpV5Pigsw:-KNhNju2T2mIMg_uNPOk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> delete
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 68 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBRarpSTIgnGXXJya:-KNhNjFV7Uq6vxIOyQFL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing new line.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgDO_udw51RxblAVaJ:-KNhNlGftLtov3TzETdj:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Move this file to `test/` subdirectory.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBXckt5tScEScBd2o:-KNhNr-osFAHD4lNOrRm:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> delete
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 70 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBb9euQ4V4zJUfL3z:-KNhNs-Mxb4nOx7uc-Fs:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L70)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> delete
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNgBdOwcFFb2E9Uazzq:-KNhNvX5xmBxuU-EPxc4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/46bd19279b9edc7bd41f7adce89b93706089b05b/drake/examples/kuka_iiwa_arm/kuka_iiwa_arm_test.cc#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Is this style guide compliant?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by liangfok** [comment]
:lgtm:

+@sammy-tri for platform reivew please.

---

Reviewed 3 of 6 files at r3, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNhbGklnldqoeLYj4f4:1366457711)*

**Comment by liangfok** [comment]
I served as a feature reivew. But since I directly modified this PR, +@hongkai-dai for another feature review.

Once this PR is merged, I'll work on a gravity compensation demo.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNhbRVJZj47jPjxEiPN:1184247229)*

**Comment by sammy-tri** [comment]
Should the "do not review" tag go away?

---

Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNhjMnw5jnc_6hzO-2X:322915660)*

**Comment by liangfok** [comment]
Sorry. Yes, I removed that label. This PR is ready for review.

---

Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNhkNaVdXNQ4xY7ywu8:1661566173)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 6 files at r3, 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.cc, line 12 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhp_rPSIyYtWKqza-K:-KNhp_rPSIyYtWKqza-L:-1138257803) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/iiwa_simulation.cc#L12)):*
> ```cpp
> using Drake::RigidBodySystem;
> 
> std::shared_ptr<RigidBodySystem> CreateKukaIiwaSystem(void) {
> ```

FYI, it looks like this function could be used in kuka_lcm_visualizer.cc as well to reduce some duplicated code.  It might not be worth it since it's not that much code, and that file only wants the RigidBodyTree, not the whole system.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 29 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhpElRESBLg_j7gqht:-KNhpElRESBLg_j7gqhu:-116842247) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L29)):*
> ```objc
> 
> /**
>  * @param[out] duration The duration over which the simulation should run. The
> ```

The SetupSimulation function doesn't appear to have any parameters?

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 10 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhpzMbqblCdyFYAJd6:-KNhpzMbqblCdyFYAJd7:-1515280522) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L10)):*
> ```cpp
> #include "drake/systems/LCMSystem.h"
> #include "drake/systems/Simulation.h"
> #include "drake/systems/cascade_system.h"
> ```

Includes should be in alphabetical order within sections: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 57 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhrAg4SrE1wyb-FYuy:-KNhrAg4SrE1wyb-FYuz:1146386633) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L57)):*
> ```cpp
> 
>   // Simulation duration in seconds.
>   double duration = 0.5;
> ```

This seems like it performs the same function as kStartTime, but one of them is const and kStudlyCaps, and the other is not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by liangfok** [comment]
@sammy-tri I addressed your comments. PTAL. Thanks!

---

Reviewed 1 of 4 files at r8.
Review status: 4 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.cc, line 12 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhp_rPSIyYtWKqza-K:-KNhuEvIhjgrUe39bMYi:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/iiwa_simulation.cc#L12)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI, it looks like this function could be used in kuka_lcm_visualizer.cc as well to reduce some duplicated code.  It might not be worth it since it's not that much code, and that file only wants the RigidBodyTree, not the whole system.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_simulation.h, line 29 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhpElRESBLg_j7gqht:-KNht36mCCCcltLtgbaE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/iiwa_simulation.h#L29)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> The SetupSimulation function doesn't appear to have any parameters?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 10 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhpzMbqblCdyFYAJd6:-KNhtIP2AXN754IThzUJ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L10)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Includes should be in alphabetical order within sections: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 57 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNhrAg4SrE1wyb-FYuy:-KNhtYbspmNDmJ5xqeAR:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcdc5af4d4dc130aec01099debee156e7103d4d/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L57)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> This seems like it performs the same function as kStartTime, but one of them is const and kStudlyCaps, and the other is not.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNhyoqgTTdjISFZh7z0:-2116822502)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 6 files at r3, 3 of 4 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 50 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNi0VNjR9PGvKvGCchS:-KNi0VNkoTutFC5OGPlL:-617820414) ([raw file](https://github.com/robotlocomotion/drake/blob/1edb2f9309603f63af8ee6bae1fa0146958edbd2/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L50)):*
> ```cpp
>   std::shared_ptr<lcm::LCM> lcm = std::make_shared<lcm::LCM>();
> 
>   const auto& tree = CreateKukaIiwaSystem()->getRigidBodyTree();
> ```

I think it would be cleaner here to explicitly store tree as a shared_ptr<RigidBodyTree> instead of an auto referende.  It took me a few minutes to figure out why the tree wasn't being destroyed when the RigidBodySystem goes away after this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by liangfok** [comment]
@sammy-tri I addressed your comment. PTAL. Thanks!

---

Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 50 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNi0VNjR9PGvKvGCchS:-KNi2FK74cX9dJ-o12bI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1edb2f9309603f63af8ee6bae1fa0146958edbd2/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L50)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think it would be cleaner here to explicitly store tree as a shared_ptr<RigidBodyTree> instead of an auto referende.  It took me a few minutes to figure out why the tree wasn't being destroyed when the RigidBodySystem goes away after this line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNi2JebuqnVEVN3cwaJ:-1087309987)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 50 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNi0VNjR9PGvKvGCchS:-KNi4LfATNHMxHenwwvh:2027703139) ([raw file](https://github.com/robotlocomotion/drake/blob/1edb2f9309603f63af8ee6bae1fa0146958edbd2/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L50)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
I'm sorry for being nitpicky, because I'm 99% sure the compiler is doing the right thing behind the scenes, but can we make it not a reference but a real shared_ptr variable?  (yes, I feel bad about this at this point)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 50 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNi0VNjR9PGvKvGCchS:-KNi54Ilxk1fzf_1ukUh:-1330012695) ([raw file](https://github.com/robotlocomotion/drake/blob/1edb2f9309603f63af8ee6bae1fa0146958edbd2/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L50)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I'm sorry for being nitpicky, because I'm 99% sure the compiler is doing the right thing behind the scenes, but can we make it not a reference but a real shared_ptr variable?  (yes, I feel bad about this at this point)
</details>
Actually, I feel sufficiently bad about it I'm going to mark the discussion resolved and lgtm before I leave for vacation so this isn't a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNi5HU_0jZWVuIBlaRK:1417088721)*

**Comment by liangfok** [comment]
@sammy-tri I addressed your comment. PTAL. Thanks!

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 50 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNi0VNjR9PGvKvGCchS:-KNi5drwJZNysxsJEUPP:1278802536) ([raw file](https://github.com/robotlocomotion/drake/blob/1edb2f9309603f63af8ee6bae1fa0146958edbd2/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L50)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Actually, I feel sufficiently bad about it I'm going to mark the discussion resolved and lgtm before I leave for vacation so this isn't a blocker.
</details>
Done! No worries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNi5gPoEckSDIjsLS2J:-1087309987)*

**Comment by liangfok** [comment]
Thanks. Just waiting for @hongkai-dai's feature review.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNi5v-RHj2QqxqPHfp6:-91767128)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 25 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNiSHbetDbLchs3j4YX:-KNiSHbetDbLchs3j4YY:-190138579) ([raw file](https://github.com/robotlocomotion/drake/blob/767ad553172e273970f09a87fe02922f27264bab/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L25)):*
> ```cpp
> namespace {
> 
> int DoMain(int argc, char* argv[]) {
> ```

Why we use `DoMain` here but `do_main` in kuka_lcm_visualizer.cc? If we want to avoid name conflict, I feel we probably want to use the same name style, like `do_main_dynamics`. In the future, we might have more `do_main`-like functions.

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 60 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNiVOexP3eI0n5k0VRP:-KNiVOeyKNmIQO_5YCSH:-452425000) ([raw file](https://github.com/robotlocomotion/drake/blob/767ad553172e273970f09a87fe02922f27264bab/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L60)):*
> ```cpp
>   const double kDuration = 0.5;
> 
>   Drake::simulate(*sys.get(), kStartTime, kDuration, x0, options);
> ```

Sorry to ask a silly question, are we going to simulate this system with zero control?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933)*

**Comment by liangfok** [comment]
@hongkai-dai I addressed your comments. PTAL. Thanks!

---

Review status: 6 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 25 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNiSHbetDbLchs3j4YX:-KNiWh6iGCdX5H-RPTj7:-1311940316) ([raw file](https://github.com/robotlocomotion/drake/blob/767ad553172e273970f09a87fe02922f27264bab/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Why we use `DoMain` here but `do_main` in kuka_lcm_visualizer.cc? If we want to avoid name conflict, I feel we probably want to use the same name style, like `do_main_dynamics`. In the future, we might have more `do_main`-like functions.
</details>
Actually, `DoMain()` is correct based on the style guide:

https://google.github.io/styleguide/cppguide.html#Function_Names

I've updated `kula_lcm_visualizer.cc` to use `DoMain()`.

The main purpose of the `DoMain()` is so we don't have to namespace the contents inside of it with `drake::examples::kuka_iiwa_arm`.

Name conflict is not an issue since these methods are defined in two different `.cc` files and not included in any library.

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 60 \[r11\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-KNiVOexP3eI0n5k0VRP:-KNiY5nDDGKxQxymqlwt:-834265824) ([raw file](https://github.com/robotlocomotion/drake/blob/767ad553172e273970f09a87fe02922f27264bab/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L60)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Sorry to ask a silly question, are we going to simulate this system with zero control?
</details>
Yes, this is a minimal demo that simulates the robot dynamics without any controller present. Basically, we simply want to show that the robot's model can be loaded into Drake and that we can simulate the effects of gravity acting upon it.

The next step is to add an executable with a controller. I am planning on adding a controller that simply issues the gravity compensation torques. After that, we can add more sophisticated controllers like those that operate in operational space. I'm probably going to need your help doing that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNifjzzJTY8wnwzeZdM:1091805329)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNigdLYvCLxIBXniHrF:1417088721)*

**Comment by liangfok** [comment]
Thanks! Now waiting on CI to pass.

---

Review status: 6 of 7 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNiguB79tqI9nMMYU62:1997010811)*

**Comment by liangfok** [comment]
The [mysterious CI failure]() is being tracked in #2959.

@drake-jenkins-bot retest this please.

---

Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2933#-:-KNisioGUtyXG3IUhv1P:-1957510456)*

**Pull request merged**
