### PR TITLE
Fix #2972 by adding UnusableModel Collision model

### LINKED ISSUE #2972: Failing tests when Bullet is not installed
* bullet_collision_zero_rad_sphere_test
* rigid_body_tree_test
* testConstraintConstructor
* testKinematicsCacheChecks
* urdf_parser_test

https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=63218

### PR DESCRIPTION
**Pull request by jhoare**
* For when Drake is compiled without a collision library (e.g. minimal
    configuration)
  * Will call DRAKE_ASSERT and die when it is attempted to be used.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3040)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I will let @amcastro-tri do feature review, before doing platform review.  If that doesn't wrap up by today, we should kick platform review to the next on-deck.

**Comment by jhoare** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot windows-msvc-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-64-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-minimal please

**Comment by amcastro-tri** [comment]
This seems like a good short term solution to me that solves #2972. Just a few minor comments, PTAL.
It'll hopefully get better with the new design but that of course will take a bit longer. 

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGO3cmAdDIUp_r-GoO:-KOGO3cmAdDIUp_r-GoP:-1566990384) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L9)):*
> ```CMake
>   set(bullet "yes" CACHE STRING "yes")
> else()
>   set(drakeCollision_SRC_FILES ${drakeCollision_SRC_FILES} UnusableModel.cc)
> ```

Google style guide requires this file to be renamed to something like `unusable_model.cc`.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGOb9rJ51n_xfxEOHA:-KOGOb9sFSoUaWLWWqOc:151552552) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L17)):*
> ```CMake
>   pods_use_pkg_config_packages(drakeCollision bullet)
> endif()
> target_link_libraries(drakeCollision drakeShapes drakeCommon)
> ```

Now you don't include `drake_assert.h` in `DrakeCollision.cpp` I dont think `drakeCommon` is needed.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGOmuQvWo6MaAzuNu1:-KOGOmuQvWo6MaAzuNu2:1986847715) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/DrakeCollision.cpp#L4)):*
> ```cpp
> 
> #include <iostream>
> ```

Notice there is no dependency with `drakeCommon` anymore now per comment above.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGP4WUY_i6J41QtKW1:-KOGP4WUY_i6J41QtKW2:1578342645) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L9)):*
> ```cpp
> static void PrintErrorAndDie() {
>   DRAKE_ABORT_UNLESS(
>       !"Compile Drake with a collision library backend for Collision support!");
> ```

`Collision` --> `collision`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOGQKqvPM3RL7EFNlsA:-1004966829)*

**Comment by jwnimmer-tri** [comment]
One quick response, before I do my own review...

---

Reviewed 1 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGOb9rJ51n_xfxEOHA:-KOGTMViHR3aPZyZsFND:1393719132) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Now you don't include `drake_assert.h` in `DrakeCollision.cpp` I dont think `drakeCommon` is needed.
</details>
FWIW, from platform review point of view, I think linking everything against `drakeCommon` is just fine, even if it's not immediately required.  It doesn't hurt anything, and will reduce churn as new, useful utilities go into `common` and are desired here (e.g., text logging).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOGUB6YmedYM66mCU0y:805097324)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjpv2x7D8_xGCEHwa:-KOGjpv2x7D8_xGCEHwb:-1723699112) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L9)):*
> ```CMake
>   set(bullet "yes" CACHE STRING "yes")
> else()
>   set(drakeCollision_SRC_FILES ${drakeCollision_SRC_FILES} UnusableModel.cc)
> ```

I would prefer to compile this code into the library even when bullet is enabled, so that we can find out if/when it breaks even in builds that have access to bullet.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjeyAGwamDM_46oja:-KOGjeyAGwamDM_46ojb:1908188124) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/DrakeCollision.cpp#L3)):*
> ```cpp
> #include "drake/systems/plants/collision/DrakeCollision.h"
> 
> #include <iostream>
> ```

Unused include?

---

*[drake/systems/plants/collision/UnusableModel.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVhiOaPkHxsA8qsZ3:-KOGVhiOaPkHxsA8qsZ4:-2093377440) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L1)):*
> ```cpp
> #include "UnusableModel.h"
> ```

Needs full path.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGiayEPrmMeisJR9vl:-KOGiayEPrmMeisJR9vm:1203931233) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L9)):*
> ```cpp
> static void PrintErrorAndDie() {
>   DRAKE_ABORT_UNLESS(
>       !"Compile Drake with a collision library backend for Collision support!");
> ```

BTW I find the `DRAKE_ABORT_UNLESS(!"message");` an abhorrent pattern due to the obscure bang-magic, though I'll let this slide in this PR if need be.

Consider `(false && "message")` to be more explicit, or even better just use `cerr` for the message and then `DRAKE_ABORT()`, or even better add a new `DRAKE_ABORT_MSG` helper.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjSV6BRTU8K2OsVUK:-KOGjSV6BRTU8K2OsVUL:-802270752) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L24)):*
> ```cpp
> 
> bool UnusableModel::closestPointsAllToAll(
>                              const std::vector<ElementId>& ids_to_check,
> ```

Please confirm for me that this is what `clang-format` does for this file?  It's a bit odd whitespace.

---

*[drake/systems/plants/collision/UnusableModel.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVQQrcrKZNMXZxUVg:-KOGVQQrcrKZNMXZxUVh:-1789389069) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.h#L6)):*
> ```objc
> #include <vector>
> 
> #include "Element.h"
> ```

Must use full paths `"drake/systems/plants/collision/Element.h` etc.

---

*[drake/systems/plants/collision/UnusableModel.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVO_-hjejmMFV4GLK:-KOGVO_-hjejmMFV4GLL:1292687508) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.h#L11)):*
> ```objc
> namespace DrakeCollision {
> 
> /// An unusable model, used when no collision detection backend is available
> ```

Missing period at end of sentence.

---

*[drake/systems/plants/collision/UnusableModel.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGV_ewnDdN2Z1q0v9Y:-KOGV_exV1IQxGrEFRj9:-719543706) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.h#L14)):*
> ```objc
> class UnusableModel : public Model {
>  public:
>   UnusableModel() {}
> ```

Disable (`= delete;`) the C++ copy and assign, per cppguide.

---

*[drake/systems/plants/collision/UnusableModel.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGiMOq23qbzqkVH0_C:-KOGiMOrAyDI33Z9QpDi:-473903132) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.h#L55)):*
> ```objc
>       double collision_threshold) override;
> };
> };
> ```

Don't use `;` on close-namespace.
Missing comment on close-namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040)*

**Comment by jhoare** [comment]
I believe I addressed all reviewer comments. PTAL 

---

Reviewed 12 of 12 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGO3cmAdDIUp_r-GoO:-KOGtgB5BRxyBQ0smcja:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L9)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Google style guide requires this file to be renamed to something like `unusable_model.cc`.
</details>
Done.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjpv2x7D8_xGCEHwa:-KOGthZGyAz_hTXZ5mDw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I would prefer to compile this code into the library even when bullet is enabled, so that we can find out if/when it breaks even in builds that have access to bullet.
</details>
Done.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGOb9rJ51n_xfxEOHA:-KOGtlUjQMWO9elBxE5P:1518045109) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FWIW, from platform review point of view, I think linking everything against `drakeCommon` is just fine, even if it's not immediately required.  It doesn't hurt anything, and will reduce churn as new, useful utilities go into `common` and are desired here (e.g., text logging).
</details>
From this conversation I left drakeCommon in. 

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjeyAGwamDM_46oja:-KOGtuxRrUHbf1hebhoq:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/DrakeCollision.cpp#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused include?
</details>
Done.

---

*[drake/systems/plants/collision/unusable_model.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVQQrcrKZNMXZxUVg:-KOGu1BbpgExhwW8P1pS:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/unusable_model.h#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Must use full paths `"drake/systems/plants/collision/Element.h` etc.
</details>
Done.

---

*[drake/systems/plants/collision/unusable_model.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVO_-hjejmMFV4GLK:-KOGuDjtUnEKZPin26mf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/unusable_model.h#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing period at end of sentence.
</details>
Done.

---

*[drake/systems/plants/collision/unusable_model.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGV_ewnDdN2Z1q0v9Y:-KOGuXEMTlcP3xjAru7Y:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/unusable_model.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Disable (`= delete;`) the C++ copy and assign, per cppguide.
</details>
Done.

---

*[drake/systems/plants/collision/unusable_model.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGiMOq23qbzqkVH0_C:-KOGuGHNL1rADiUYZTnS:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/unusable_model.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Don't use `;` on close-namespace.
> Missing comment on close-namespace.
</details>
Done.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGVhiOaPkHxsA8qsZ3:-KOGuJj7V74Rh62PYk35:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Needs full path.
</details>
Done.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGP4WUY_i6J41QtKW1:-KOGuJIyByt949qquKx_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L9)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `Collision` --> `collision`
</details>
Done.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGiayEPrmMeisJR9vl:-KOGuKEJGQab-Z1mWJam:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I find the `DRAKE_ABORT_UNLESS(!"message");` an abhorrent pattern due to the obscure bang-magic, though I'll let this slide in this PR if need be.
> 
> Consider `(false && "message")` to be more explicit, or even better just use `cerr` for the message and then `DRAKE_ABORT()`, or even better add a new `DRAKE_ABORT_MSG` helper.
</details>
Done.

---

*[drake/systems/plants/collision/UnusableModel.cc, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGjSV6BRTU8K2OsVUK:-KOGuOS6bB9TwSNm4HTc:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/UnusableModel.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please confirm for me that this is what `clang-format` does for this file?  It's a bit odd whitespace.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOGuRhkZ2YvYgjuqg4c:-477274341)*

**Comment by jhoare** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot windows-msvc-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-64-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-minimal please

**Comment by amcastro-tri** [comment]
One more small comment. Otherwise :lgtm: 

---

Reviewed 1 of 12 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/systems/plants/collision/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGOb9rJ51n_xfxEOHA:-KOGlXtoiadSHML2sBNs:126816266) ([raw file](https://github.com/robotlocomotion/drake/blob/925eb0836824e0f2ea9db5e485b6622982290739/drake/systems/plants/collision/CMakeLists.txt#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FWIW, from platform review point of view, I think linking everything against `drakeCommon` is just fine, even if it's not immediately required.  It doesn't hurt anything, and will reduce churn as new, useful utilities go into `common` and are desired here (e.g., text logging).
</details>
Sure. I just tend to avoid pushing changes that actually don't have any functional effect. But that is just my preference I guess.

---

*[drake/systems/plants/collision/unusable_model.h, line 7 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGwd7wfEsurYlVAUgo:-KOGwd7wfEsurYlVAUgp:-1430014595) ([raw file](https://github.com/robotlocomotion/drake/blob/a33f7f195b8e173cb66c94098b1c5c6793ec7e4a/drake/systems/plants/collision/unusable_model.h#L7)):*
> ```objc
> 
> #include "drake/systems/plants/collision/Element.h"
> #include "Model.h"
> ```

`#include "drake/systems/plants/collision/Model.h`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOGxQ8Sy5VL-Oklr0dw:440481724)*

**Comment by jwnimmer-tri** [comment]
Reviewed 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/systems/plants/collision/unusable_model.h, line 55 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGxmwrWln4BEDrp0dG:-KOGxmwrWln4BEDrp0dH:324496514) ([raw file](https://github.com/robotlocomotion/drake/blob/a33f7f195b8e173cb66c94098b1c5c6793ec7e4a/drake/systems/plants/collision/unusable_model.h#L55)):*
> ```objc
>       double collision_threshold) override;
>  private:
>   // BulletModel objects are not copyable
> ```

Typo `BulletModel`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040)*

**Comment by jhoare** [comment]
Thanks for catching those errors. Fixed second round of reviews, PTAL. 

---

Reviewed 1 of 12 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/systems/plants/collision/unusable_model.h, line 7 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGwd7wfEsurYlVAUgo:-KOH-Y6RMCEFZPYKGIK0:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a33f7f195b8e173cb66c94098b1c5c6793ec7e4a/drake/systems/plants/collision/unusable_model.h#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `#include "drake/systems/plants/collision/Model.h`?
</details>
Done.

---

*[drake/systems/plants/collision/unusable_model.h, line 55 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-KOGxmwrWln4BEDrp0dG:-KOH-b9A0T_AgEWEgllu:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a33f7f195b8e173cb66c94098b1c5c6793ec7e4a/drake/systems/plants/collision/unusable_model.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Typo `BulletModel`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOH-g-3TBshXKnCvF10:-1396579367)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

All of the discussions show up as blocking on @jhoare, I'm not sure why that is.  I believe I have ack'd all of my comments satisfactorily for reviewable.

---

Reviewed 1 of 12 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOH-uVKXGkrc5G4syoZ:-783655356)*

**Comment by jhoare** [comment]
Ok I think I went through and unmarked everything. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOH1tebAKMnRdZmktSd:247750923)*

**Comment by jhoare** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot windows-msvc-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-64-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-minimal please

**Comment by jhoare** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot windows-msvc-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-64-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
All discussions resolved.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040#-:-KOHMJcnluoiouJ-dBVr:314952669)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 12 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3040)*

**Pull request merged**
