### PR TITLE
[workspace] Add and use syntactic sugar for repository.bzl labels

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
+@mwoehlke-kitware for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17536)

### CODE REVIEW

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: ...where's the "looks **awesome** to me" button? :slightly_smiling_face:

> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17536#-:-N6UU-PoDAt03Lrhgyig:b-tq8tu8)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tools/workspace/abseil_cpp_internal/repository.bzl` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17536#-N6UT7dY1ewMl12VV1fS:-N6UT7dY1ewMl12VV1fT:bbuzlj4) ([raw file](https://github.com/robotlocomotion/drake/blob/50f8db5dfa7aa0702d7cecadbe585af37adad532/tools/workspace/abseil_cpp_internal/repository.bzl#L14)):*
> ```Starlark
>         patches = [
>             ":patches/hidden_visibility.patch",
>             ":patches/inline_namespace.patch",
> ```

Nice! And having fewer longer-than-the-limit lines is a great benefit as well!

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri or @SeanCurtis-TRI for platform review (whoever reaches here first), please.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
A little clean up on the resulting documentation and a question about the resulting boilerplate.

> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17536#-:-N6hyZfP-PQaCS70hjSH:b1fg02j)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/github.bzl` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17536#-N6hxai65JokBPGiVzDz:-N6hxai65JokBPGiVzE-:b-8s49jl) ([raw file](https://github.com/robotlocomotion/drake/blob/50f8db5dfa7aa0702d7cecadbe585af37adad532/tools/workspace/github.bzl#L37)):*
> ```Starlark
>             comment it out) and then the checksum-mismatch error message will
>             offer a suggestion.
>         build_file: optional build file is the BUILD file label to use for
> ```

nit: You've lost the "optional" sense of this parameter. Previous documentation discussed what it means to omit it. That is no longer the case.

On a related note, we're left with the string `":package.BUILD.bazel"` in all of the places. Would this be the default value if `build_file` were to be omitted?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17536)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @mwoehlke-kitware and @SeanCurtis-TRI)

___
*[`tools/workspace/github.bzl` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17536#-N6hxai65JokBPGiVzDz:-N6iGcq_Cl6MqzeNxdw6:b-uzh7iw) ([raw file](https://github.com/robotlocomotion/drake/blob/50f8db5dfa7aa0702d7cecadbe585af37adad532/tools/workspace/github.bzl#L37)):*
> You've lost the "optional" sense of this parameter. Previous documentation discussed what it means to omit it. That is no longer the case.

Added back lost docs.

> On a related note, we're left with the string ":package.BUILD.bazel" in all of the places. Would this be the default value if build_file were to be omitted?

No, we still need the semantics of "None" intact.  Some upstream packages already provide their own BUILD files (e.g., dReal).

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17536#-:-N6iO8Xw6Nqi2LCiDIIm:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),mwoehlke-kitware (waiting on @jwnimmer-tri)

**Pull request merged**
