### PR TITLE
[framework] Add unittest showing confusing discrete initialization

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates #12649

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for post :turkey: discussion / review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356#-:-NHWzEwWDn_0MdgXxbc1:b-tgfubd)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I've attempted to explain the (correct but obscure) behavior below. There is nothing intuitive about the handling of simultaneous events -- sorry! If you think of them as operating independently, in an arbitrary order, each seeing the exact same Context values, that might help a little. No Context update occurs until _all_ simultaneous events have had their say. See my comments on the issue also.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356#-:-NH_jMv5DoL7X0iUvPW_:bnwovgb)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_e0D1-wTVDVFs_MjI:-NH_e0D2DtuO6O28hhbu:bmvs0ar) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L83)):*
> ```cpp
>   // Initialize.
>   simulator.Initialize();
>   // Note: Still false!
> ```

That's because you didn't declare any event with an Initialization trigger type. If you want a discrete update to happen at initialization, use 
[DeclareInitializationDiscreteUpdateEvent](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#ab4e7028e25a5d6e402a156a0115019a4)
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_ezzk7a1YtFas4aAc:-NH_ezzlE3e-H8iUl6g6:b-qpel5) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L89)):*
> ```cpp
>   // Advance.
>   simulator.AdvanceTo(0.0);
>   // Now it changes!
> ```

Your CalcNextUpdateTime() triggered a discrete update event and the end of the previous step (in this case, at the end of initialization). Triggered discrete updates are always applied at the beginning of a step, in this case the 0-length step you just took.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NH_hCw08KF5dq0nMwIN:b-ysw62p) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
> ```cpp
>   // ... but effectively dependent system has no state change upon
>   // *initialization* event?
>   EXPECT_FALSE(zoh_shows_initialized());
> ```

OK, this one is a little more complicated to explain because it involves _simultaneous_ events. What you were hoping for was that the Dut event would be handled first, then the ZOH event would be applied afterwards. That's not how simultaneous events work. Instead, each event handlers sees the _original, unmodified_ Context, while working on the same temporary discrete_state object. Once all simultaneous events have had their chance to modify the discrete_state object, that object replaces the discrete_state in the Context. So when the ZOH system's periodic event handler read its input port at time 0 (Dut's output) Dut's state _in the Context_ had not yet been updated.

I believe what you wanted was an actual initialization event in Dut so that its initialization would actually occur (i.e. its Context updated) prior to anyone looking at it.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_j2eB6HXPiTCo0Jzz:-NH_j2eB6HXPiTCo0K--:b-bff6y2) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L98)):*
> ```cpp
>   simulator.AdvanceTo(zoh_period_sec);
>   EXPECT_TRUE(dut->IsInitialized(dut_context));
>   // Er...?
> ```

An update event was _triggered_ at the end of the step that reached the trigger time. _Triggered_ does not mean _handled_ -- that occurs at the start of the next step.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_jFtx7PwpayMLLWg7:-NH_jFtx7PwpayMLLWg8:bw0zuoh) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L103)):*
> ```cpp
>   // Advance again.
>   simulator.AdvanceTo(zoh_period_sec + kEps);
>   // Everything as expected.
> ```

The ZOH event was handled at the beginning of that short step.

**Review by sherm1 — COMMENTED** [review]
I find it helpful to think of Simulator initialization as a zero-length step "-1" that occurs just prior to step 0. Thus discrete initialization event handlers execute at the beginning of step -1, and a search for triggers occurs at the end of step -1. Anything that triggers at the end of step -1 is handled at the beginning of step 0.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356#-:-NH_lAOt3J5ropCMgW6w:b-20xo0h)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Gotcha, thank you for the comments, this all makes sense! (and seems inline with things like Simulink's semantics, etc.)

I guess I wish that Drake had some "better than Simulink affordances", but perhaps that's just local to ZeroOrderHold and related systems (that may've cargo-culted off of it) - made comments below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356#-:-NI-rouP1GnQcHA2Xh4X:b-lctsov)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_e0D1-wTVDVFs_MjI:-NI-pZMODNr4Ody6clhH:b-54mt2w) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That's because you didn't declare any event with an Initialization trigger type. If you want a discrete update to happen at initialization, use 
[DeclareInitializationDiscreteUpdateEvent](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#ab4e7028e25a5d6e402a156a0115019a4)
</blockquote></details>

Gotcha.

So is it preferable to use `DeclareInitializationDiscreteUpdateEvent` over implementing `DoCalcNextUpdateTime()` for `t=now`, insofar as it's related to initialization?
And for abstract values, I would use something like  `DeclareInitializationUnrestrictedUpdateEvent`?

Additionally, is the `DoCalcNextUpdateTime()` incorrect / less preferred?
Should it be a proper initialization event as what Evan and Dexterous Robotics folk use?

As a user, I'd love to see all of Drake use the most proper mechanism consistently.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NI-qNPf-01CEdy9dW8z:bb136yk) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

OK, this one is a little more complicated to explain because it involves _simultaneous_ events. What you were hoping for was that the Dut event would be handled first, then the ZOH event would be applied afterwards. That's not how simultaneous events work. Instead, each event handlers sees the _original, unmodified_ Context, while working on the same temporary discrete_state object. Once all simultaneous events have had their chance to modify the discrete_state object, that object replaces the discrete_state in the Context. So when the ZOH system's periodic event handler read its input port at time 0 (Dut's output) Dut's state _in the Context_ had not yet been updated.

I believe what you wanted was an actual initialization event in Dut so that its initialization would actually occur (i.e. its Context updated) prior to anyone looking at it.
</blockquote></details>

Aye, gotcha, that makes sense for what you've stated as well as the docs you pointed out, specifically `x_{n+1} = f(n, x_n, u_n)`.

But I guess maybe my issue is that `ZeroOrderHold` (and other related systems, perhaps?) currently has the awkward affordance, `LatchInputPortToState`, and or manual setting of the state.
Is that correct, or can we do something better? (I think we could?)

Possible Options:
- Do the perhaps more proper workflow of "add initialize bit; direct feedthrough of y=u at init, flip bit via initialization event, then y=x afterwards" ?
- Add affordance for Drake to initialize (via initialization events or t=now discrete updates) using a "stable cascade of simultaneous events"
  - Dumbest approach is keep initializing until all values stop changing. Better is perhaps is topological sort of states / ports and execute initializations in said order, throw on any loops.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_j2eB6HXPiTCo0Jzz:-NI-qZLzE4rxcq4WV0Zz:b-2qus75) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L98)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

An update event was _triggered_ at the end of the step that reached the trigger time. _Triggered_ does not mean _handled_ -- that occurs at the start of the next step.
</blockquote></details>

Gotcha, thanks! New confusion, but will comment directly on that line.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_jFtx7PwpayMLLWg7:-NI-wb4_3LuPF2OeTMuH:bwogdos) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The ZOH event was handled at the beginning of that short step.
</blockquote></details>

Hm... it seems that "short step" can actually be "zero step"? Resolving this convo, adding line on new confusing point.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 110 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NI-wmre6EuxeWmjzb0l:-NI-wmre6EuxeWmjzb0m:bdrs6zc) ([raw file](https://github.com/robotlocomotion/drake/blob/bafc77949f248702948ba8f66b0ac11d962b54d0/systems/framework/test/leaf_system_discrete_initialization_test.cc#L110)):*
> ```cpp
>   // WARNING: The ZOH discrete update has executed, and thus the state has
>   // changed.
>   EXPECT_TRUE(zoh_shows_initialized());
> ```

Is this expected, even when advanced to a time point that has already been advanced to?

I understand that the events have been queued up, but seems to be an odd code smell that `AdvancedTo(t)` can produce two different results, and where as `AdvancedTo(t + ε)` doesn't?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_e0D1-wTVDVFs_MjI:-NI3PPZG2BgzyoMud6aE:baxpqmv) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha.

So is it preferable to use `DeclareInitializationDiscreteUpdateEvent` over implementing `DoCalcNextUpdateTime()` for `t=now`, insofar as it's related to initialization?
And for abstract values, I would use something like  `DeclareInitializationUnrestrictedUpdateEvent`?

Additionally, is the `DoCalcNextUpdateTime()` incorrect / less preferred?
Should it be a proper initialization event as what Evan and Dexterous Robotics folk use?

As a user, I'd love to see all of Drake use the most proper mechanism consistently.
</blockquote></details>

Yes, I think of DoCalcNextUpdateTime() override as a last resort for events that can't be triggered via initialization, periodic, or every-step triggers (e.g. events that occur at arbitrary times based on external conditions). If you really want an event that occurs upon initialization, definitely use an initialization event. Those are very narrow though, triggered only upon Simulator::Initialize(). (Initialize() is implicitly called once before the first AdvanceTo() but you would have to call it explicitly if you want to reinitialize the same simulator.)
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_ezzk7a1YtFas4aAc:-NI3Ruhs5pvlQa2SKj0o:b4yqbwr) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Your CalcNextUpdateTime() triggered a discrete update event and the end of the previous step (in this case, at the end of initialization). Triggered discrete updates are always applied at the beginning of a step, in this case the 0-length step you just took.
</blockquote></details>

You might consider using the little-known [Simulator::AdvancePendingEvents()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_simulator.html#ad8252b9d897ed041c44c301cfcd8c5ce) method here. It is actually equivalent to AdvanceTo(current_time) (i.e. time doesn't advance) but is more clear about what the effect of that is.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NI3TlQo1lkydLUzSZL9:b-szb7f0) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Aye, gotcha, that makes sense for what you've stated as well as the docs you pointed out, specifically `x_{n+1} = f(n, x_n, u_n)`.

But I guess maybe my issue is that `ZeroOrderHold` (and other related systems, perhaps?) currently has the awkward affordance, `LatchInputPortToState`, and or manual setting of the state.
Is that correct, or can we do something better? (I think we could?)

Possible Options:
- Do the perhaps more proper workflow of "add initialize bit; direct feedthrough of y=u at init, flip bit via initialization event, then y=x afterwards" ?
- Add affordance for Drake to initialize (via initialization events or t=now discrete updates) using a "stable cascade of simultaneous events"
  - Dumbest approach is keep initializing until all values stop changing. Better is perhaps is topological sort of states / ports and execute initializations in said order, throw on any loops.
</blockquote></details>

I took a look at our ZOH primitive. It currently does not have an initialization event so the output doesn't match the input right at the beginning of the simulation. That seems wrong to me, but depends on the intended use of that primitive. The current behavior is well documented.

My guess (as a naive user) is that ZOH would make more sense if it had an initialization event that transferred input u to output y. Then all the updates done at the start of the t=0 step would see the expected value on the ZOH output port. This would be a potentially breaking change but I'd be surprised if anyone would be hurt by it. And it would eliminate any need to call the Latch() method manually prior to starting a simulator.

Regarding treatment of simultaneous events, IMO there is _nothing_ that will be satisfactory. By far the way to avoid trouble is to make sure there are no mutually-dependent simultaneous events in your system -- that is very likely to be an error. In the present case, there was no need for any simultaneous events -- that only mattered because initialization was not handled properly.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_jFtx7PwpayMLLWg7:-NI3WyO67JmPp1GxlKT_:b68tv7i) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L103)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... it seems that "short step" can actually be "zero step"? Resolving this convo, adding line on new confusing point.
</blockquote></details>

Yes, that's right -- a zero-length step is still a step because a step consists of more than just time advancement. A prettier way to take a zero-length step is AdvancePendingEvents() since that is all that is left if you don't advance time.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 110 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NI-wmre6EuxeWmjzb0l:-NI3VjSpCTdpElFvT9r-:b5iasxk) ([raw file](https://github.com/robotlocomotion/drake/blob/bafc77949f248702948ba8f66b0ac11d962b54d0/systems/framework/test/leaf_system_discrete_initialization_test.cc#L110)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is this expected, even when advanced to a time point that has already been advanced to?

I understand that the events have been queued up, but seems to be an odd code smell that `AdvancedTo(t)` can produce two different results, and where as `AdvancedTo(t + ε)` doesn't?
</blockquote></details>

Again if you use the sugar method AdvancePendingEvents() here the code will make more sense. AdvanceTo() always takes a step -- consider that a step consists of a bunch of event handling stuff _as well as_ a time-advancing section. In this case you advanced time by zero seconds but all the event handling parts of the step still got executed. The elaborate "How a simulation is stepped" documentation covers this behavior, so yes this is expected.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NLDbKuG-KdxfUQNsfqF:b73dcmq) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
> My guess (as a naive user) is that ZOH [...]

Yup, I think that'd work for me!

> [...] IMO there is nothing that will be satisfactory [...]

I don't necessarily agree.

I do think it should be *relatively* straightforward to topologically sort dependencies, check for coupled simultaenous events (algebraic loops, but only in the sense of initialization) and fail fast if there is.
If there are no loops, then it should be easy to take the topologically sorted events and dispatch them.

I just ran into an incantation of this impediment in a controls workflow, so I may try to prototype something along this route.
That being said, is there a way I can get this on y'all's Q1 goals?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NLDfPTJ0z6ow8u_Lrc1:btndjhw) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> My guess (as a naive user) is that ZOH [...]

Yup, I think that'd work for me!

> [...] IMO there is nothing that will be satisfactory [...]

I don't necessarily agree.

I do think it should be *relatively* straightforward to topologically sort dependencies, check for coupled simultaenous events (algebraic loops, but only in the sense of initialization) and fail fast if there is.
If there are no loops, then it should be easy to take the topologically sorted events and dispatch them.

I just ran into an incantation of this impediment in a controls workflow, so I may try to prototype something along this route.
That being said, is there a way I can get this on y'all's Q1 goals?
</blockquote></details>

Whelp, I thought events had an affordance for something like `prerequisites_of_calc`, but blarg, it doesn't.
Thus, initialization depedency checks may be a bit kludgy.

Still, seems like something that can be solved if given attention?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @siyuanfeng-tri)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NLDj7EQ9xtSYC8kogD1:bxylm40) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Whelp, I thought events had an affordance for something like `prerequisites_of_calc`, but blarg, it doesn't.
Thus, initialization depedency checks may be a bit kludgy.

Still, seems like something that can be solved if given attention?
</blockquote></details>

Looking a bit more, yeah, could possibly inject stuff into `Diagram<T>::DispatchDiscreteVariableUpdateHandler()`, etc., to do the topological sort; ideally, this sorting only happens once, outside of that update.

Alternatively, stuff like `Simulator<T>::HandleUnrestrictedUpdate()` learns how to optionally downcast to the `DiagramEventCollection<>` thing and sort, at least given reference to something like `connection_map()` from diagram or the builder.

@siyuanfeng-tri Any chance you've pondered this stuff before?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @siyuanfeng-tri)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_hCw08KF5dq0nMwIM:-NLDrSSsESiLnYKDLwlf:bgqzdsn) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Looking a bit more, yeah, could possibly inject stuff into `Diagram<T>::DispatchDiscreteVariableUpdateHandler()`, etc., to do the topological sort; ideally, this sorting only happens once, outside of that update.

Alternatively, stuff like `Simulator<T>::HandleUnrestrictedUpdate()` learns how to optionally downcast to the `DiagramEventCollection<>` thing and sort, at least given reference to something like `connection_map()` from diagram or the builder.

@siyuanfeng-tri Any chance you've pondered this stuff before?
</blockquote></details>

From looking at it, hard to tell what can be processed "externally".
One rough possibility: #18551

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1 and @siyuanfeng-tri)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_ezzk7a1YtFas4aAc:-NLDzygF8P0Ma4dcSTN2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You might consider using the little-known [Simulator::AdvancePendingEvents()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_simulator.html#ad8252b9d897ed041c44c301cfcd8c5ce) method here. It is actually equivalent to AdvanceTo(current_time) (i.e. time doesn't advance) but is more clear about what the effect of that is.
</blockquote></details>

Done.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_jFtx7PwpayMLLWg7:-NLE-1tFBQnObYkdzNIZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Yes, that's right -- a zero-length step is still a step because a step consists of more than just time advancement. A prettier way to take a zero-length step is AdvancePendingEvents() since that is all that is left if you don't advance time.
</blockquote></details>

Done.
___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 110 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NI-wmre6EuxeWmjzb0l:-NLE-0OV-K4Yi-1XR6VS:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/bafc77949f248702948ba8f66b0ac11d962b54d0/systems/framework/test/leaf_system_discrete_initialization_test.cc#L110)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Again if you use the sugar method AdvancePendingEvents() here the code will make more sense. AdvanceTo() always takes a step -- consider that a step consists of a bunch of event handling stuff _as well as_ a time-advancing section. In this case you advanced time by zero seconds but all the event handling parts of the step still got executed. The elaborate "How a simulation is stepped" documentation covers this behavior, so yes this is expected.
</blockquote></details>

Done. Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1 and @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NLE-4jhCMoB1nNpJn7O:-NLE-4jhCMoB1nNpJn7P:b42zxjv) (no related file):*
Working: Will see if I can add in option to ZOH to add in initialization event.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1 and @siyuanfeng-tri)

___
*[`systems/framework/test/leaf_system_discrete_initialization_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NH_e0D1-wTVDVFs_MjI:-NLE43f78VhiQzCGHX_4:b-ifp397) ([raw file](https://github.com/robotlocomotion/drake/blob/66d0457facff9a2078addf595a7b064abdf59cfb/systems/framework/test/leaf_system_discrete_initialization_test.cc#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Yes, I think of DoCalcNextUpdateTime() override as a last resort for events that can't be triggered via initialization, periodic, or every-step triggers (e.g. events that occur at arbitrary times based on external conditions). If you really want an event that occurs upon initialization, definitely use an initialization event. Those are very narrow though, triggered only upon Simulator::Initialize(). (Initialize() is implicitly called once before the first AdvanceTo() but you would have to call it explicitly if you want to reinitialize the same simulator.)
</blockquote></details>

Done. Switched to initialization event, which smooths things over some. However, simultaneous events are still wiggy, as discussed below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1 and @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NLE-4jhCMoB1nNpJn7O:-NLE4EtZ1o5OdcO6SdR_:bryoayr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will see if I can add in option to ZOH to add in initialization event.
</blockquote></details>

Done. Showcases simultaneous events.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @sherm1, and @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NMGAobE4MWB21yBzVQL:-NMGAobF7hfkWz-sx8Px:bvo5k95) (no related file):*
Working: Check interaction between discrete periodic event, `.Initialize()`, and nuance for `.AdvancedTo(0.0)` and `.AdvancePendingEvents()`

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18356)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1 and @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18356#-NMGAobE4MWB21yBzVQL:-NMGE9mA4sCAq4dTcrsM:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Check interaction between discrete periodic event, `.Initialize()`, and nuance for `.AdvancedTo(0.0)` and `.AdvancePendingEvents()`
</blockquote></details>

Done.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18356)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @sherm1, and @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18356#-NMGTUPO4xv5Q5fESyNZ:-NMGTUPPCoEh4lSgd7X9:bpor34y) (no related file):*
Working: Trying out `InitializeRepeatedly`

___

**Comment by jwnimmer-tri** [comment]
Closing as abandoned. When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
