### PR TITLE
[render] Add RenderEngineGL to the render engine benchmark

### LINKED ISSUE #13617: [render] RenderEngineGl has incomplete implementation of RenderEngine interface
We've ported `RenderEngineGl` from Anzu back to Drake (#13584). However, the ported code is incomplete:

- [x] The ability to display the rendering is missing. (resolved by #13626)
- [x] Unable to render label images. (resolved by #13659)
- [x] Unable to render color images. (resolved by #14226 and #14260)
- [x] Needs to support full intrinsic specification (see, #11880 for details)
- [ ] Add RenderEngineGl to `render_benchmark.cc` (#14540)

This epic PR tracks the work for the `RenderEngineGl` to be "complete" (in the sense that it has the same functionality as the other `RenderEngine` implementations).

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Briefly, this adds `RenderEngineGl` to the render engine benchmark.

As part of that activity, it does several other things:

  - Move the documentation out of the .cc file into a new .h file so that it appears in the rendered documentation.
  - Refactor the benchmark code to allow more strategic benchmarking.
  - Correct oversight in `RenderEngineGl` implementation (posing light now works).

closes #13617

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRQF6YPBhOIWWQ9LoMB:blnrywe)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRQEtBa1E1pEMM-Ixg7:-MRQEtBb9r8JkMKBIODq:b-getkqq) (no related file):*
Note to reviewers:

Revision 1 contains the original benchmark documentation moved into its own file. None of the text has changed. The purpose was to make the *actual* changes more apparent.
Revision 2 contains all the functional changes (including the changes to the documentation).

The PR will be flattened prior to merging.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRRQ1iiCL-WsP9ZaqDZ:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[geometry/benchmarking/render_benchmark.cc, line 302 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRROmHx3V-1Mun6EhD1:-MRROmHx3V-1Mun6EhD2:b-teyw61) ([raw file](https://github.com/robotlocomotion/drake/blob/3643711eaaf04f6ca63c2851312c4b21c79ef79f/geometry/benchmarking/render_benchmark.cc#L302)):*
> ```cpp
> 
> // Args are: sphere count, camera count, image width, image height.
> #define CONFIGURATIONS \
> ```

Since this macro is a bit syntactically tricky, consider explaining the usage here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRRRn4S6U7WQkF_yCF-:bppyoqq)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @SeanCurtis-TRI, and @sherm1)

___
*[geometry/benchmarking/render_benchmark.cc, line 302 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRROmHx3V-1Mun6EhD1:-MRRRm8FBOWulEleCSym:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3643711eaaf04f6ca63c2851312c4b21c79ef79f/geometry/benchmarking/render_benchmark.cc#L302)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Since this macro is a bit syntactically tricky, consider explaining the usage here.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[geometry/benchmarking/render_benchmark.cc, line 310 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXBvO3IEqXXaXiU1g:-MRRXBvO3IEqXXaXiU1h:b-2s5o2h) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L310)):*
> ```cpp
>        ->Args(...);
> 
>  In other words, the return value of BENCHMARK_DEFINE_F is a pointer to
> ```

s/DEFINE/REGISTER/ ??
___
*[geometry/benchmarking/render_benchmark.cc, line 317 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXWhYDEckVQMzQEst:-MRRXWhYDEckVQMzQEsu:b-e6a9gi) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L317)):*
> ```cpp
>    CONFIGURATIONS;
> 
>  Be sure not to inject any spurious whitespace or terminal characters.
> ```

BTW, this sentence makes me wonder if a different formulation would be clearer and less error prone:`#define MY_REGISTER(x, y) BENCHMARK_REGISTER_F(x, y) [[expansion of CONFIGURE]]`

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @SeanCurtis-TRI, and @sherm1)

___
*[geometry/benchmarking/render_benchmark.cc, line 310 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXBvO3IEqXXaXiU1g:-MRRbkUV7sSnUYxv5pI9:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L310)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

s/DEFINE/REGISTER/ ??
</blockquote></details>

Done
___
*[geometry/benchmarking/render_benchmark.cc, line 317 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXWhYDEckVQMzQEst:-MRRb7obAoCWXKdhcJyH:bfct7rw) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L317)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, this sentence makes me wonder if a different formulation would be clearer and less error prone:`#define MY_REGISTER(x, y) BENCHMARK_REGISTER_F(x, y) [[expansion of CONFIGURE]]`
</blockquote></details>

I'll enlist your help on this one. The macros are *horrible*. It doesn't just create a pointer, it *captures* the damn thing in a *horribly* named, macro-derived local variable that basically renders it impossible to get otherwise.

I tried a number of alternative options and *this* was the best I could come up with.

(And don't even get me started on the *horribleness* of the so-called templated fixtures.)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @SeanCurtis-TRI, and @sherm1)

___
*[geometry/benchmarking/render_benchmark.cc, line 317 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXWhYDEckVQMzQEst:-MRS9EbYBw60-UzwsjAs:b-daxoul) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L317)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll enlist your help on this one. The macros are *horrible*. It doesn't just create a pointer, it *captures* the damn thing in a *horribly* named, macro-derived local variable that basically renders it impossible to get otherwise.

I tried a number of alternative options and *this* was the best I could come up with.

(And don't even get me started on the *horribleness* of the so-called templated fixtures.)
</blockquote></details>

I'll put together a  proposal.

**Review by sherm1 — COMMENTED** [review]
Nice! Platform :lgtm: with a few nits.

> Reviewed 2 of 2 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRSPX_Q4ol85t5qNIDE:bauruwr)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[geometry/benchmarking/render_benchmark.cc, line 317 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXWhYDEckVQMzQEst:-MRSOpiu8RMsPA20czJA:bi2i7qw) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L317)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll put together a  proposal.
</blockquote></details>

:+1: for MY_REGISTER (or BENCHMARK_REGISTER_F_WITH_CONFIGURATIONS for the ultimate in verbosity).
___
*[geometry/benchmarking/render_benchmark.cc, line 215 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSNLWa-G43UExRAFDt:-MRSNLWa-G43UExRAFDu:b-ofkjzf) ([raw file](https://github.com/robotlocomotion/drake/blob/3e24b49decc238e4c63dab6d1ec048647b3b6275/geometry/benchmarking/render_benchmark.cc#L215)):*
> ```cpp
>        N/R² ≤ α
>        N/α ≤ R²
>        √(N/α) ≤ R
> ```

BTW great comment!
___
*[geometry/benchmarking/render_benchmark.cc, line 310 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSODDl5lf4Cn5sQHxm:-MRSODDl5lf4Cn5sQHxn:bpk6ivi) ([raw file](https://github.com/robotlocomotion/drake/blob/3e24b49decc238e4c63dab6d1ec048647b3b6275/geometry/benchmarking/render_benchmark.cc#L310)):*
> ```cpp
>        ->Args(...);
> 
>  In other words, the BENCHMARK_REGISTER_F macro provides limted access to a
> ```

nit: limted -> limited
___
*[geometry/benchmarking/render_benchmark_doxygen.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSKzJk5PpGDRYuUZWX:-MRSKzJk5PpGDRYuUZWY:bba4mbg) ([raw file](https://github.com/robotlocomotion/drake/blob/79cf9b9a706260d400de0ddc6743d13bd3eb9a8e/geometry/benchmarking/render_benchmark_doxygen.h#L36)):*
> ```objc
>  The output will be something akin to:
> 
>  ```
> ```

nit: this comment is indented one space until this line, then the following table is not indented at all, then the text after that goes back to a one-space indent. Should the table match the rest or is this intentional?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I think I have an appropriate alternative macro. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRVXCph5DP8RN2LAgl6:b886m9z)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[geometry/benchmarking/render_benchmark.cc, line 317 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRRXWhYDEckVQMzQEst:-MRVR6wS7ifMMncoRijt:b-8gp19w) ([raw file](https://github.com/robotlocomotion/drake/blob/25c383c9c8921f215d0c738c43c024ee12225e87/geometry/benchmarking/render_benchmark.cc#L317)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

:+1: for MY_REGISTER (or BENCHMARK_REGISTER_F_WITH_CONFIGURATIONS for the ultimate in verbosity).
</blockquote></details>

Actually, we can roll everything together. The define, register, *and* configuration. I hadn't finished off *this* direction (having thrown in the towel in finding any value in the templated fixtures). But, in retrospect, there's a more obvious macro. Take a look.
___
*[geometry/benchmarking/render_benchmark.cc, line 215 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSNLWa-G43UExRAFDt:-MRVQuco2ddQLfQJkula:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/3e24b49decc238e4c63dab6d1ec048647b3b6275/geometry/benchmarking/render_benchmark.cc#L215)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW great comment!
</blockquote></details>

Thanks!
___
*[geometry/benchmarking/render_benchmark.cc, line 310 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSODDl5lf4Cn5sQHxm:-MRVQz_J6YIzL_fdifUW:b-vcca2j) ([raw file](https://github.com/robotlocomotion/drake/blob/3e24b49decc238e4c63dab6d1ec048647b3b6275/geometry/benchmarking/render_benchmark.cc#L310)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: limted -> limited
</blockquote></details>

Done

It's *so* limited, that I could only afford a single "i".
___
*[geometry/benchmarking/render_benchmark_doxygen.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14540#-MRSKzJk5PpGDRYuUZWX:-MRVVqLn2Sj4Onq90aBL:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/79cf9b9a706260d400de0ddc6743d13bd3eb9a8e/geometry/benchmarking/render_benchmark_doxygen.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this comment is indented one space until this line, then the following table is not indented at all, then the text after that goes back to a one-space indent. Should the table match the rest or is this intentional?
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sherm1 — COMMENTED** [review]
Very nice!

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRVtIN3Am2mu824ri9H:b-j7qk9t)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14540#-:-MRa0e7MDb0YD3iCy3iE:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
