### PR TITLE
Use the updated yellow bell pepper from RobotLocomotion/models/pull/27

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Relevant to //examples/hydroelastic/python_nonconvex_mesh:drop_pepper_py

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-NiaT0vR8q9mmY2k3_DD:-NiaT0vR8q9mmY2k3_DE:bcy9gj5) (no related file):*
Working temporary SHA1 until the models PR ([RobotLocomotion/models/pull/27](https://github.com/RobotLocomotion/models/pull/27)) is merged.

___

**Review by DamrongGuoy — COMMENTED** [review]
+@dmcconachie-tri for feature review, please.

This Drake PR 20485 links to RobotLocomotion/models PR 27.  You can confirm how the bell pepper looks by:
```
git pr 20485
bazel run //tools:meldis -- --open-window &
bazel run //examples/hydroelastic/python_nonconvex_mesh:drop_pepper_py -- --simulation_time=0
```

After we have this fix in Drake + RobotLocomotion/models, we can try a similar fix in Anzu.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-:-NiaTukU2Ji0brj7uDzT:bsghel5)* status: 1 unresolved discussion, LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
@rcory we are fixing the bump map of the bell pepper in [RobotLocomotion/models/pull/27](https://github.com/RobotLocomotion/models/pull/27).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-:-Nia_S8j09wJzKgkPfCw:b-96pa2p)* status: 1 unresolved discussion, LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-:-Nieudko01Wj9kMwYxwt:b-syrr9x)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485)* status: LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-NiaT0vR8q9mmY2k3_DD:-Niex3SV2BsiaBeHuGPy:bkgqcga) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Working temporary SHA1 until the models PR ([RobotLocomotion/models/pull/27](https://github.com/RobotLocomotion/models/pull/27)) is merged.
</blockquote></details>

The models repo [PR 27](https://github.com/RobotLocomotion/models/pull/27) was merged. Per https://drake.mit.edu/model_version_control.html , I have updated repository.bzl to the latest commit of the models repo's master.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-:-NifdlNCBrKKSGAl-UPe:bnfp4nl)* status: 1 unresolved discussion

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-NifcrQbCJ1a9w4z5rjM):*
commits like this usually have the exact release-notes text as the commit message:

```
Upgrade drake_models to latest commit
```

The actual reason can be figured out by looking at the newly included commits in the models repo, or by discussion in the PR.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485)* status: 1 unresolved discussion

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20485#-NifcrQbCJ1a9w4z5rjM):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

commits like this usually have the exact release-notes text as the commit message:

```
Upgrade drake_models to latest commit
```

The actual reason can be figured out by looking at the newly included commits in the models repo, or by discussion in the PR.
</blockquote></details>

Done. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20485)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),dmcconachie-tri

**Pull request merged**
