### PR TITLE
[solvers] Use interface_deps throughout

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This allows us to remove all of the third-party solvers from our header linter's list of known defects.

Add some useful new macros so that rules are easier to write.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17157)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please?

**Review by sammy-tri — COMMENTED** [review]
:lgtm:   +@sherm1 for platform review

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17157#-:-N1ouP-C4weZN3O1L3s7:b-rfsgjs)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
There are lots of tricky-looking conversions from the old ugly conditional code to the new elegant code. Is there a way to verify that those are all correct (other than eyeballing)?

Either way, platform :lgtm: with a couple of typos

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17157#-:-N1pGX7A9mw_d0z8OT5u:bq4g94y)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`solvers/defs.bzl` line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17157#-N1pCVunDt5qiqbzV7ym:-N1pCVunDt5qiqbzV7yn:bxs9lyo) ([raw file](https://github.com/robotlocomotion/drake/blob/b57cf485af8c980cb8d5ab56f3045cc70671eb16/solvers/defs.bzl#L51)):*
> ```Starlark
>     definitions that report failure (e.g., returning false or throwing).
> 
>     This rule is enables linting of all of the mentioned source files, even if
> ```

nit: ~is~
___
*[`solvers/defs.bzl` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17157#-N1pE4Om4d1p-l2FhP0d:-N1pE4Om4d1p-l2FhP0e:bxs9lyo) ([raw file](https://github.com/robotlocomotion/drake/blob/b57cf485af8c980cb8d5ab56f3045cc70671eb16/solvers/defs.bzl#L101)):*
> ```Starlark
>     Commercial solvers are usually OFF by default (so, will use opt_in_...).
> 
>     This rule is enables linting of all of the mentioned source files, even if
> ```

nit: ~is~

**Comment by jwnimmer-tri** [comment]
> Is there a way to verify that those are all correct (other than eyeballing)?

For the most part, the fact that the unit tests still pass should be enough.  I also spot-checked that introducing lint into various fails gets correctly flagged.

**Pull request merged**
