### PR TITLE
Added time stepping to examples and tests.

### PR DESCRIPTION
**Pull request by edrumwri**
Adds time stepping to examples and tests built upon rigid body plant.

NOTE: The examples are not expected to work properly until time stepping is properly activated through a second PR. This PR serves only to pave the way for that one, and will allow the reviewers for PR #7545 to verify proper operation of the time stepper.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7546)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for feature review please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-:-L-E3iE22zhwAsPYpezD:bgdoi2o)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-:-L-FPUcTWj9szbyZuPgd:bnfp4nl)*

**Comment by edrumwri** [comment]
Thanks Siyuan! +@soonho-tri for platform review per regular rotation please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-:-L-HZOQmBe0TdNH7A6qt:b-wj4wei)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HcIQhxIlMFG_ciJaT:-L-HcIQhxIlMFG_ciJaU:b-jcq9gj) ([raw file](https://github.com/robotlocomotion/drake/blob/7fe5e104761ea100234b5424025ba62c479287f8/drake/examples/valkyrie/valkyrie_simulation.cc#L15)):*
> ```cpp
> 
> DEFINE_string(simulation_type, "compliant",
>               "Type of simulation, valid values are "
> ```

BTW, I just noticed that you have 
```
"The type of simulation to use: "
"'compliant' (default) or 'timestepping'")
```
in the previous files. (a little inconsistency, not defects though)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-:-L-HclO8aikn5f8s9RmE:bg7igkv)*

**Comment by edrumwri** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HcIQhxIlMFG_ciJaT:-L-Hh6I2I1NARghuFUFk:by6gj5a) ([raw file](https://github.com/robotlocomotion/drake/blob/7fe5e104761ea100234b5424025ba62c479287f8/drake/examples/valkyrie/valkyrie_simulation.cc#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I just noticed that you have 
```
"The type of simulation to use: "
"'compliant' (default) or 'timestepping'")
```
in the previous files. (a little inconsistency, not defects though)
</blockquote></details>

BTW Right- I meant to remove that. Thanks! (Done)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-HkxJNkSZDoZAA_f4u:b-o8653) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
> ```cpp
> 
> int main() {
>   return drake::examples::valkyrie::main();
> ```

Missing calls to:
- gflags::SetUsageMessage()
 - gflags::ParseCommandLineFlags();

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-Hu_R1zNg3BURICIev:bkb8y2w) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Missing calls to:
- gflags::SetUsageMessage()
 - gflags::ParseCommandLineFlags();
</blockquote></details>

Nice catch!

Btw, the two tests -- `valkyrie_simulation_test` and `schunk_wsg_lift_test.cc` do not call those `gflag` calls either. Actually, it's not clear to me what we can get by using `gflags` inside of `gtest`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-HwJswb_lEyUbzF62X:b384czn) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Nice catch!

Btw, the two tests -- `valkyrie_simulation_test` and `schunk_wsg_lift_test.cc` do not call those `gflag` calls either. Actually, it's not clear to me what we can get by using `gflags` inside of `gtest`s.
</blockquote></details>

Drake's googletests altomatically initialize gflags; see https://github.com/RobotLocomotion/drake/blob/master/drake/common/test_utilities/drake_cc_googletest_main.cc.  But yes, the original defect is valid -- if you write your own `main()` function, you have to initialize gflags in order to use them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-HxbFC5FVym-Ai_qr1:bawvp1c) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Drake's googletests altomatically initialize gflags; see https://github.com/RobotLocomotion/drake/blob/master/drake/common/test_utilities/drake_cc_googletest_main.cc.  But yes, the original defect is valid -- if you write your own `main()` function, you have to initialize gflags in order to use them.
</blockquote></details>

@jwnimmer-tri , :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-I0LCVnOF2UM-dz2_v:b-2rhvle) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@jwnimmer-tri , :+1: 
</blockquote></details>

FYI, we have:
```
$ ./bazel-bin/drake/examples/valkyrie/valkyrie_simulation --help
valkyrie_simulation: Warning: SetUsageMessage() never called
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-I0qI_EceCp9v3NdR5:b9r2unr) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we have:
```
$ ./bazel-bin/drake/examples/valkyrie/valkyrie_simulation --help
valkyrie_simulation: Warning: SetUsageMessage() never called
...
```

</blockquote></details>

FYI I haven't been writing usage messages up to this point and the ones that I'm seeing in examples seem to add little utility. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-I3NHW5mvfex26ZJGb:b-722jgx) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI I haven't been writing usage messages up to this point and the ones that I'm seeing in examples seem to add little utility. Thoughts?
</blockquote></details>

I'm not sure that this is a defect given the existing tests which do not call `SetUsageMessage()`. 

At the same time, I check that https://github.com/RobotLocomotion/drake/blob/master/drake/common/test_utilities/drake_cc_googletest_main.cc#L25 has:
```c++
  google::SetUsageMessage(" ");  // Nerf a silly warning emitted by gflags.
```
which we can copy/paste here just to suppress the warning if we want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by edrumwri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/valkyrie/valkyrie_simulation.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7546#-L-HkxJNkSZDoZAA_f4t:-L-Ib57KD5pwrD5eBhTk:b7hcnjx) ([raw file](https://github.com/robotlocomotion/drake/blob/5e582878f7338fa42dad840a9f5d10f55744f3dd/drake/examples/valkyrie/valkyrie_simulation.cc#L62)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm not sure that this is a defect given the existing tests which do not call `SetUsageMessage()`. 

At the same time, I check that https://github.com/RobotLocomotion/drake/blob/master/drake/common/test_utilities/drake_cc_googletest_main.cc#L25 has:
```c++
  google::SetUsageMessage(" ");  // Nerf a silly warning emitted by gflags.
```
which we can copy/paste here just to suppress the warning if we want.
</blockquote></details>

Perfect- thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7546)*

**Pull request merged**
