### PR TITLE
[solvers] Adjust test tolerances for mac arm64

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #17009

+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please

**Review by hongkai-dai — COMMENTED** [review]
TAMSI solver test failed on mac CI.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205#-:-N29MPX460K_6EBesgfA:bvxu5bd)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
that is expected.  i've resolve that test failure in a different PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @RussTedrake)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2C_8OIA9ojbwdxcYRQ:b-19hwkb) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
> ```cpp
>     symbolic::Environment env;
>     env.insert(x, x0);
>     EXPECT_NEAR(z.cwiseAbs().sum(), y[0].Evaluate(env), 2e-15);
> ```

@hongkai-dai can you justify to me the tolerance changes in this PR, in the cases where are are keeping the limit very tight?

For example in this one, why is 2e-15 any more valid 1e-14 or 1e-13?  By saying "2" here, we imply that we need this limit to be _tight_, e.g., that "3e-15" would be suspicious and require further investigation.

If we are just going to add more buffer to the test conditions any time the test fails, without any research into _why_ it needs a larger tolerance, then that's not consistent with using tight limits.

If the comparison tolerance is only intended as a rough smoke test of the code, I would rather that we use `constexpr double kTolerance = 1e-13` globally so it's clear that they are not trying to check the numerical implementation choices, but rather just the rough logic.

**Comment by RussTedrake** [comment]
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2CjDziDxmoreG7bTqa:b-zi5zu6) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@hongkai-dai can you justify to me the tolerance changes in this PR, in the cases where are are keeping the limit very tight?

For example in this one, why is 2e-15 any more valid 1e-14 or 1e-13?  By saying "2" here, we imply that we need this limit to be _tight_, e.g., that "3e-15" would be suspicious and require further investigation.

If we are just going to add more buffer to the test conditions any time the test fails, without any research into _why_ it needs a larger tolerance, then that's not consistent with using tight limits.

If the comparison tolerance is only intended as a rough smoke test of the code, I would rather that we use `constexpr double kTolerance = 1e-13` globally so it's clear that they are not trying to check the numerical implementation choices, but rather just the rough logic.
</blockquote></details>

That is inconsistent with the advice that I routinely get during code review on my PRs... which is that one should find roughly the smallest round number that passes the tests.  Start from 1e-16 and work up from there... if the result is too big then you're missing something.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2CnNBx42Qf6nq3qUV1:b-p36a2z) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can you point to an example of such a discussion?  Then I can offline it with that reviewer and situation to see if we can be consistent.
</blockquote></details>

Likely to be me or someone else from Dynamics. Maybe a topic for the next Platform Reviewers meeting? Generally I like to see the tightest tolerance possible that doesn't make the test sensitive to within-machine-tolerance roundoff errors.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2Co35RD7XJj2PWNAEs:bs23odq) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Likely to be me or someone else from Dynamics. Maybe a topic for the next Platform Reviewers meeting? Generally I like to see the tightest tolerance possible that doesn't make the test sensitive to within-machine-tolerance roundoff errors.
</blockquote></details>

The outcome of a test case can be either to point out a bug (the common case), or point out a change (an exceptional case -- a so-called "change detector test"), without offering an opinion about whether the change is in fact a bug.

There are valid uses for change-detector tests.  But in cases where they are used, it needs to be clear to a developer how to respond in case they experience a change -- that is, what is the human metric by which we know that the change is satisfactory?  If the response is always to blindly commit a new limit, then only effect of the change-detector test is to waste our time.  Better would be to set the larger tolerance right from the start.

The defect here is not that the limit is too tight -- is that's when we have tight limits and see a change, then we need to investigate and explain the change concomitantly with upping the limit.

Do you disagree?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2Cz2cB39vW0YYwgIJA:b-kmm2l4) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The outcome of a test case can be either to point out a bug (the common case), or point out a change (an exceptional case -- a so-called "change detector test"), without offering an opinion about whether the change is in fact a bug.

There are valid uses for change-detector tests.  But in cases where they are used, it needs to be clear to a developer how to respond in case they experience a change -- that is, what is the human metric by which we know that the change is satisfactory?  If the response is always to blindly commit a new limit, then only effect of the change-detector test is to waste our time.  Better would be to set the larger tolerance right from the start.

The defect here is not that the limit is too tight -- is that's when we have tight limits and see a change, then we need to investigate and explain the change concomitantly with upping the limit.

Do you disagree?
</blockquote></details>

No, I agree completely. These aren't supposed to be change detectors but should be bug catchers. That's why they usually should not be machine epsilon but rather something larger that should be met by any correct implementation -- but not so large that it can be met by a subtly incorrect implementation! Finding that balance can be difficult since it can depend on matrix sizes and expected conditioning. But for many of the computations we see in practice 1e-15 or even 1e-14 is very hard to achieve with a bug, while 1e-12 (that's 100X sloppier than 1e-14) can cover up bugs in small-but-important terms.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2D017n07wzqe8Cqumv:bwyx83x) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No, I agree completely. These aren't supposed to be change detectors but should be bug catchers. That's why they usually should not be machine epsilon but rather something larger that should be met by any correct implementation -- but not so large that it can be met by a subtly incorrect implementation! Finding that balance can be difficult since it can depend on matrix sizes and expected conditioning. But for many of the computations we see in practice 1e-15 or even 1e-14 is very hard to achieve with a bug, while 1e-12 (that's 100X sloppier than 1e-14) can cover up bugs in small-but-important terms.
</blockquote></details>

Right.  So that's an argument that this test is supposed to be a bug-catcher.  In that sense, I find it suspicious that somehow `2e-15` would be a sensible bug-catcher cutoff while `1e-15` is not.  If the limit here were `1e-14`, would you consider that a defect?  I think Russ is trying to use `2e-14` here because he thinks you think that `1e-14` would be undesirable here.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2D47N9AzTM7mnvLwFj:bq8ouin) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right.  So that's an argument that this test is supposed to be a bug-catcher.  In that sense, I find it suspicious that somehow `2e-15` would be a sensible bug-catcher cutoff while `1e-15` is not.  If the limit here were `1e-14`, would you consider that a defect?  I think Russ is trying to use `2e-14` here because he thinks you think that `1e-14` would be undesirable here.
</blockquote></details>

The proposed change is to `2e-15` (not `2e-14`) unless I missed something. That is 10ε which is a very tight tolerance but should be fine for any simple computations (not sure what's being computed here). For example, if this is just summing up a column of 4 numbers of roughly similar magnitude roundoff should be well below 10ε. If it is more complicated, or the numbers vary widely then some analysis would be required to determine the appropriate tolerance.

In general, 1e-14 (50ε) is still a very tight tolerance and appropriate for most non-trivial computations. BTW Paul prefers to do this in binary, using 8ε, 32ε, etc. so it reads as "number of bits lost".

**Comment by sherm1** [comment]
It would be preferable to express the tolerance in terms of machine epsilon when it is expected to be computed "exactly". Then `10ⁿ ε` (or `2ⁿ ε` in Paul-style) correctly expresses that the bound is not expected to be tight.

However, since `ε≈2e-16`, `10ε≈2e-15` which may have been the author's intent. (That is, the 2 makes sense in a multiples-of-ε world.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/test/cost_test.cc` line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17205#-N2C_8OIA9ojbwdxcYRP:-N2ERf9_2l0uInk7LhD6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bd64cd067c0a34ce4696dca68d76fbb71243d750/solvers/test/cost_test.cc#L411)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> The proposed change is to 2e-15 (not 2e-14) unless I missed something. 

That's right.  I made a typo in my message.

In any case, I think we've established that there is no reason why `1e-14` is unacceptable in this instance.   There is no general principle or style rule that floating point comparison tolerances need to be set as absolutely tight as possible.  The guidance is that they are _appropriately_ tight, and that `1e-14` is a fairly reasonable guess as to a suitably tight tolerance.

Since there is no rationale given for why `2e-15` is an appropriate level for a bug-catcher, yet to me anything other than a power of 10 (or ε*2ⁿ in Paul's case) suggests that the limit is tight, I think the clarity defect stands and we need to use 1e-14 here, and similarly throughout.

In essence, we should not be using more precision (i.e., sig figs) in our unit test limits than we have reasonable logic to justify.  Empirical checking is how we discover bugs, not how we establish limits.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17205#-:-N2ESGZ_5c0FUv0IGOuI:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
