### PR TITLE
Remove Python Tests From Memcheck And Sanitizer Configurations

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Ref: https://github.com/RobotLocomotion/drake/pull/6019

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6077)

### CODE REVIEW

**Comment by jamiesnape** [comment]
FYI @stonier.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6077#-:-Kjt-dw1jP4Zg_bqxg57:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please

**Comment by stonier** [comment]
Just to check before we run away with this. @jwnimmer-tri posed an important question:

> Have we found any true-positive problems by running valgrind on python code yet?

@m-chaturvedi were there any problems found?

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6077#-:-KjtIOeJVuY1Y2HjQPVn:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6077)*

**Comment by m-chaturvedi** [comment]
@stonier No, we didn't.

**Pull request merged**
