### PR TITLE
[workspace] Upgrade sdformat_internal, gz_utils_internal, gz_math_internal to latest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #21979.

When merging, we should squash this (nixing the irrelevant second-and-following commit messages). The release note we want is just the version bump (the first commit message, including the details from its body).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21995)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews (off schedule), please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21995#-:-O8bsFtxDQVCpws1oU_u:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21995#-:-O8bsN3e2-yRYzl022PI:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
