### PR TITLE
Make PairwiseIntersectionsContinuousJoints Non-Internal

### LINKED ISSUE #20978: Move `PairwiseIntersectionsContinuousJoints` to public API
**Is your feature request related to a problem? Please describe.**
The function `PairwiseIntersectionsContinuousJoints` is used to detect intersections and the required offsets between convex sets based on the indices of continuous revolute joints. It means it can move the convex set in those dimensions by multiples of 2*pi to make them intersect. 

This function is not in the public API.

The use cases for this from a public user:
1- When using `Subgraph::AddRegions` as in [here](https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#aff9544b6375a592b1b9bda5eb1149a6f), there is an argument to give edge offsets. But there is no public API for computing those. 

2- This forces the user the other overload, which, under the hood, computes all intersections and offsets from scratch.  The user may simply know most of the intersections and edges and does not want to waste time on re-computing those. This comes handy when one has to quickly set up a modified GCS without re-computing all edges, etc. 

3- When creating Iris regions, I always check the connectivity. It is useful to just check the connection between a newly added region and previous regions in the case that some joints are continuous revolute. 

**Describe the solution you'd like**
Move this to the public API.

**Describe alternatives you've considered**
Messy workaround: The user sets up a GCS, registers new regions for which intersections are unknown as new subgraphs, ask to add edges, and check the existence of edges. 

@cohnt let me know what you think.

### PR DESCRIPTION
**Pull request by cohnt**
I've also moved these to the geodesic convexity file, to avoid cluttering up GcsTrajectoryOptimization's interface.

Still need to add test cases, now that they're public functions. Once I've done so, I'll call for review.

Resolves #20978.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)

### CODE REVIEW

**Comment by cohnt** [comment]
Since Sadra and I have both contributed code towards this PR, I don't think either of us can serve as feature reviewer. Maybe +@wrangelvid for feature review, if you have the time?

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 6 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX0yzv1wqUlzs1fYxu:-NrX0yzv1wqUlzs1fYxv:b67adbe) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/geodesic_convexity.h#L138)):*
> ```objc
> */
> std::vector<std::tuple<int, int, Eigen::VectorXd>> CalcPairwiseIntersections(
>     ConvexSets convex_sets_A, ConvexSets convex_sets_B,
> ```

Please document parameters using params.
___
*[`geometry/optimization/geodesic_convexity.h` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2hAa4zCo2MJ0YJVy:-NrX2hAa4zCo2MJ0YJVz:bs4q9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/geodesic_convexity.h#L143)):*
> ```objc
> /** Convenience overload to compute pairwise intersections within a list of
> convex sets. Equivalent to calling CalcPairwiseIntersections(convex_sets,
> convex_sets, continuous_revolute_joints). */
> ```

Ditto.
___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-NrX2NoS5_533vp9ekLc:bfz9zz0) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/geodesic_convexity.cc#L254)):*
> ```cpp
>   std::vector<std::vector<std::pair<double, double>>>&
>       region_minimum_and_maximum_values_B =
>           maybe_region_minimum_and_maximum_values_B;
> ```

I would advice agains this switching logic when convex_sets_B is empty.
Why can't you rewrite your overload s.t. it passes the convex_sets to both convex_sets_A and convex_sets_B?



_Code snippet:_
```cpp
std::vector<std::tuple<int, int, Eigen::VectorXd>> CalcPairwiseIntersections(
    ConvexSets convex_sets,
    const std::vector<int>& continuous_revolute_joints) {
  return CalcPairwiseIntersections(convex_sets, convex_sets,
                                   continuous_revolute_joints);
}
```
___
*[`geometry/optimization/geodesic_convexity.cc` line 299 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX3NE5-NT9AZZK77r0:-NrX3NE5-NT9AZZK77r1:btss7ya) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/geodesic_convexity.cc#L299)):*
> ```cpp
>       // First, we compute what the offset that should be applied to
>       // convex_sets_A[i] to potentially make it overlap with convex_sets_B[j].
>       for (int kk = 0; kk < ssize(continuous_revolute_joints); ++kk) {
> ```

Please use something more descriptive than kk, k for the revolute joints. E.g. joint_index instead of k. I think we had another PR with a similar resolution...
___
*[`geometry/optimization/test/geodesic_convexity_test.cc` line 295 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX44pD8QN9bSWmJUs-:-NrX44pD8QN9bSWmJUs0:b-355iu0) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/test/geodesic_convexity_test.cc#L295)):*
> ```cpp
>   ConvexSets sets_B = MakeConvexSets(h3, h4);
>   // Let's check the expected value of each pair of intersections.
>   // h1 <--> h3: would intersect if h1 is translated by (4, 0) * 2pi
> ```

nit: 2π
___
*[`geometry/optimization/test/geodesic_convexity_test.cc` line 313 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX4-ig3p3Z-cI1o-2U:-NrX4-ig3p3Z-cI1o-2V:b-355iu0) ([raw file](https://github.com/RobotLocomotion/drake/blob/7ffea39d032584936584929f531999bdda273d58/geometry/optimization/test/geodesic_convexity_test.cc#L313)):*
> ```cpp
>   EXPECT_EQ(intersection_edges.size(), 4);
>   for (const auto& [index_a, index_b, offset] : intersection_edges) {
>     // Verify all centers are integer multiples of 2pi apart.
> ```

nit: 2π

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 4 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-Nrb-Sut1Tnu_QVGDuIR:bqzd9x7) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L254)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I would advice agains this switching logic when convex_sets_B is empty.
Why can't you rewrite your overload s.t. it passes the convex_sets to both convex_sets_A and convex_sets_B?
</blockquote></details>

The benefit to this switching logic is if `convex_sets_A` and `convex_sets_B` are the same, then checking `convex_sets_A[i] ∩ convex_sets_B[j]` is equivalent to `convex_sets_A[j] ∩ convex_sets_B[i]`. But this will not be identified if `convex_sets` is passed to both `convex_sets_A` and `convex_sets_B`.

I've tried doing it a couple ways, and this ended up with the least code reuse. And because they're all pointers, there's very little copying overhead within.
___
*[`geometry/optimization/geodesic_convexity.cc` line 299 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX3NE5-NT9AZZK77r0:-Nrb09lMCIuWC9uQwccj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L299)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Please use something more descriptive than kk, k for the revolute joints. E.g. joint_index instead of k. I think we had another PR with a similar resolution...
</blockquote></details>

Done.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 4 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX0yzv1wqUlzs1fYxu:-Nrb1jtH--KboqFL-99-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.h#L138)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Please document parameters using params.
</blockquote></details>

Done.
___
*[`geometry/optimization/geodesic_convexity.h` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2hAa4zCo2MJ0YJVy:-Nrb1kAeEvZ4a-ad8TWO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.h#L143)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-NrbOyc4AQGA7ccx5KBv:b-jv6p4m) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L254)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

The benefit to this switching logic is if `convex_sets_A` and `convex_sets_B` are the same, then checking `convex_sets_A[i] ∩ convex_sets_B[j]` is equivalent to `convex_sets_A[j] ∩ convex_sets_B[i]`. But this will not be identified if `convex_sets` is passed to both `convex_sets_A` and `convex_sets_B`.

I've tried doing it a couple ways, and this ended up with the least code reuse. And because they're all pointers, there's very little copying overhead within.
</blockquote></details>

You can check if convex_sets_A and convex_sets_B have the same reference, which would allow you skip the intersection check in the loop.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-Nrb_SEg3fDqLuum9XU7:bunl5jz) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L254)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

You can check if convex_sets_A and convex_sets_B have the same reference, which would allow you skip the intersection check in the loop.
</blockquote></details>

Nice! Updated the logic to reflect this.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-NrbbOyv3ZZod2-IdjXR:b-u0ysou) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L254)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Nice! Updated the logic to reflect this.
</blockquote></details>

I think you can still clean up a little bit of the code to really make us of that. E.g. remove  maybe_region_minimum_and_maximum_values_B, some of the comments still say convex_sets_B.size() == 0, etc.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrX2NoS5_533vp9ekLb:-NrbpKO--DtgrZDFbpGG:b-dhbbav) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab741dc67056edcb63be0beb23b5d9545b955e5f/geometry/optimization/geodesic_convexity.cc#L254)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I think you can still clean up a little bit of the code to really make us of that. E.g. remove  maybe_region_minimum_and_maximum_values_B, some of the comments still say convex_sets_B.size() == 0, etc.
</blockquote></details>

You drive a hard bargain!

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 286 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrcZxuI3_U9odxwrR96:-NrfebCBCnIVLlatvK2J:b64hbvl) ([raw file](https://github.com/RobotLocomotion/drake/blob/043d63073875c786601854e94e07e57207f35683/geometry/optimization/geodesic_convexity.cc#L286)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

nit: This logic might be a little bit confusing if you don't know that region_minimum_and_maximum_values_B is empty because convex_sets_A matches convex_sets_B.
What do you think about renaming compute_intersections_within_A to sets_A_and_B_are_equal or similar? Then you can reuse the variable here.
</blockquote></details>

Done.

Also added a comment to explain a bit more here.
___
*[`geometry/optimization/geodesic_convexity.cc` line 358 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrcZno02o45B-HCI9oR:-NrfeeKK8SsHFpWe7aBb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/043d63073875c786601854e94e07e57207f35683/geometry/optimization/geodesic_convexity.cc#L358)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

nit: The argument names should match your header file (you called it convex_sets instead of convex_sets_A)
</blockquote></details>

Done.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by sadraddini — COMMENTED** [review]
+@rpoyner-tri for platform review please. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-:-NrgK6vH2oLKol8ZHt4Y:bgdnxzr)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor doc question

> Reviewed 1 of 1 files at r2, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-:-NrgngLpEEcgJODAuwYo:b-b2uuwo)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 132 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrgRmK91nNE_FbRFd0L:-NrgRmKA9zOakdMxVC33:b-szlkoh) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5d389089892c140d6521cc5548fd07d59c30c4a/geometry/optimization/geodesic_convexity.h#L132)):*
> ```objc
> Each edge is a tuple in the form [index_A, index_B, offset_A_to_B], where
> Each is a tuple in the form [index_A, index_B, offset_A_to_B],
> where index_A is the index of the list in @p convex_sets_A, index_B is the
> ```

minor: I can't find a written rule yet, but we are transitioning from `@p variable` to just variable in back-ticks. See for example https://github.com/RobotLocomotion/drake/pull/20213

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 132 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21011#-NrgRmK91nNE_FbRFd0L:-Nrgwt1-2FQRZGAWQITX:bt2vr1b) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5d389089892c140d6521cc5548fd07d59c30c4a/geometry/optimization/geodesic_convexity.h#L132)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: I can't find a written rule yet, but we are transitioning from `@p variable` to just variable in back-ticks. See for example https://github.com/RobotLocomotion/drake/pull/20213
</blockquote></details>

Fixed.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21011)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
