### PR TITLE
Create new RigidTransform constructors for 3x4 matrix, 4x4 matrix, and related Eigen expressions.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11922)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
As a user, I find it kinda painful to have names like `GetAs<Type>` and `MakeFrom<Type>` when it's really just a conversion and the verbs don't add that much value (in my mind); `To<Type>` and `From<Type>` would suffice.

Can I ask if there is a strong reason why this is done?
I would like to advocate for the opposite direction, and shrink down to the minimum descriptive name, because it's actually somewhat painful to have such a core type have verbose names, and then use those in Python (where tab length is 4 spaces).

**Comment by EricCousineau-TRI** [comment]
>  If this is possible, do you prefer a constructor over a Make() method.

Yup! Most certainly. I introduced `FromMatrix4` due to the ambiguity when trying to make it a constructor:
https://github.com/RobotLocomotion/drake/blob/bc77fda121ca1e555e29908b2dc865f9a0e9d01c/math/rigid_transform.h#L157-L158

> Note: Otherwise, my understanding is that we are supposed to use "Make" in conjunction with static factory methods.

I'm not sure if we have a hard-and-fast rule for this. In my opinion:
- `MakeFoo` makes sense if there's quite a bit of work / overhead going on, *or* if it's a non-static method where the type of the output might be unclear.
- For common conversions, though, a constructor would be preferred, and if that's not feasilbe or doesn't make sense, then a simple factory is good, and I personally would prefer minimum text to describe the action.

As a concrete example, `FromMatrix4` as a standalone makes zero sense, but `RigidTransform::FromMatrix4` is very clear in my mind, and `RigidTransform::MakeFromMatrix4` looks redundant.

(Discussed some of this with @jwnimmer-tri, but not saying any of this is necessarily his opinion)

**Comment by jwnimmer-tri** [comment]
On first glance the new `template <typename Derived>` constructor is missing the homogeneous check for the 4x4 case.

**Comment by jwnimmer-tri** [comment]
My intent was that the compile-time 4x4-sized matrix constructor and runtime 4x4-size matrix constructor should behave the same.  Either both should make the check, or neither should.

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/11922#-Lmev87gEsPiA4XO3Y8T:-Lmfn9OO0XR-e0bBnZSy:bjrklfz) ([raw file](https://github.com/robotlocomotion/drake/blob/303182acb4f8091a09b296b581c899c043d9f5cc/math/rigid_transform.h#L171)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Do you also have signatures like this: `foo(double number)`? `pose` communicates semantics, `matrix` does not.
</blockquote></details>

Depending on the context, yup!

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 261 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11922#-LmkSs8ICSDAWFxe5hek:-LmkcWjg7rkHPP8iHj-g:b3ocw52) ([raw file](https://github.com/robotlocomotion/drake/blob/fd19bffa84abedbfc71c3a917d2b0b04913520e7/math/rigid_transform.h#L261)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

my 2 cents. In Drake a good example of `MakeFoo` is in `AbstractValue::Make()`. In that case the factory method makes sense because it offers convenience. In this case, what does `FromMatrix4()` offer that the constructor with signature `RigidTransform(const Matrix4<T>&)` does not offer?

summarizing, my preference would be not having this method at all since:
1) the constructor gives you what you need.
2) why giving users multiple spellings and let them struggle why one or the other is preferable?
3) we'd break homogeneity of user facing APIs across the entirety of the code base, where I blieve we do not have a single `FromFoo()`?
</blockquote></details>

OK Both options here in this TODO imply that this method is going away, so no need to worry?

It existed first because the constructor flavor introduced ambiguity, but Paul has nicely solved that problem.

Regarding `MakeX` vs no, see above discussion? (e.g. conversions vs. accessors vs. whatever)

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/11922#-Lmev87gEsPiA4XO3Y8T:-LmkcI0p6HqBcqO4ccXu:b-m81jzt) ([raw file](https://github.com/robotlocomotion/drake/blob/303182acb4f8091a09b296b581c899c043d9f5cc/math/rigid_transform.h#L171)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

The word "pose" is used as an argument in a similar way throughout the documentation.
I defined "pose" at the start of the RigidTransform documentation.
The first appearance of "pose" in documentation is now in quotes  -- encouraged by Eric's comment.
I prefer to leave it as "pose" than "matrix".
</blockquote></details>

At a minimum, then, can you add a TODO in `math_py.cc` for me to deprecate / remove the constructor for `RigidTransform(matrix=...)`?

(At a maximum, perhaps make the deprecation?)

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 171 at r2](https://reviewable.io/reviews/robotlocomotion/drake/11922#-Lmev87gEsPiA4XO3Y8T:-Lml-Due9DkFXP_bNPx1:bqf1jsk) ([raw file](https://github.com/robotlocomotion/drake/blob/303182acb4f8091a09b296b581c899c043d9f5cc/math/rigid_transform.h#L171)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

At a minimum, then, can you add a TODO in `math_py.cc` for me to deprecate / remove the constructor for `RigidTransform(matrix=...)`?

(At a maximum, perhaps make the deprecation?)
</blockquote></details>

OK Withdrawing. Will just do it as follow-up.

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 225 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11922#-LmlAEbP78UC4HsV06HC:-LmlBa98-Ec3M1H38C_M:bu4fwbf) ([raw file](https://github.com/robotlocomotion/drake/blob/fd19bffa84abedbfc71c3a917d2b0b04913520e7/math/rigid_transform.h#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Renewing my `pose` vs. `matrix` complaint: The use of `pose` in the context of a translation still smells weird. `matrix` sounds more appropriate as it covers the intended semantics.

Feel free to dismiss, but I still disprefer `pose`, especially in this light.

To address prior comments, I don't find the definition of "pose" (with or without quotes) to lessen my distaste for it's usage here.
Additionally, I don't think saying that `pose` is used consistently addresses my concern, which is it feels like an odd delineation in this specific context.
(Sure, in some other case, saying `ComputeIk(Matrix4<T> pose)` seems fine, but this class is meant for poses.)
</blockquote></details>

(To clarify, used consistently in these newly added overloads.)

**Comment by SeanCurtis-TRI** [comment]
___
*[math/rigid_transform.h, line 225 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11922#-LmlAEbP78UC4HsV06HC:-LmlSjh9CI6aQT5mTkXa:bkxqcqp) ([raw file](https://github.com/robotlocomotion/drake/blob/fd19bffa84abedbfc71c3a917d2b0b04913520e7/math/rigid_transform.h#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(To clarify, used consistently in these newly added overloads.)
</blockquote></details>

Several thoughts:

1. While you don't like pose = translation, I have to say I don't much care for Vector3 = matrix, either. That is the implication of calling the parameter matrix combined with the fact that this is invoked for Vector3-flavored Eigen expressions. So, a name that is so strongly *typed* must fundamentally break down.
2. In C++ we have the declared type (which covers all syntax needs) and the name of the variable provides semantics. That's wonderful. But, as I pondered this, it seems like the problem is not in the C++ code, but its manifestation in the python bindings. I.e., if I have `RT(Iso pose)` and `RT(Matrix4 pose)` they both get bound the same way. Is that your concern? Or is having `X_AB = RigidTransform(pose=thing)` not a concern if sometimes `pose` is an `Iso3` and sometimes a `Matrix4` and sometimes a (`Vector3((1, 2, 3)) * 3`).

At the end of the day, I appreciate you don't like "pose". But, whatever your philosophical complaint is, "matrix" is not a viable alternative.

Surely a "pose" vs "matrix" debate is a false dichotomy and a peaceful resolution can be found by striking out into a different direction?

**Comment by EricCousineau-TRI** [comment]
___
*[math/rigid_transform.h, line 225 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11922#-LmlAEbP78UC4HsV06HC:-LmqfuQlBeM9873ZjIqw:bbkrm2) ([raw file](https://github.com/robotlocomotion/drake/blob/fd19bffa84abedbfc71c3a917d2b0b04913520e7/math/rigid_transform.h#L225)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Several thoughts:

1. While you don't like pose = translation, I have to say I don't much care for Vector3 = matrix, either. That is the implication of calling the parameter matrix combined with the fact that this is invoked for Vector3-flavored Eigen expressions. So, a name that is so strongly *typed* must fundamentally break down.
2. In C++ we have the declared type (which covers all syntax needs) and the name of the variable provides semantics. That's wonderful. But, as I pondered this, it seems like the problem is not in the C++ code, but its manifestation in the python bindings. I.e., if I have `RT(Iso pose)` and `RT(Matrix4 pose)` they both get bound the same way. Is that your concern? Or is having `X_AB = RigidTransform(pose=thing)` not a concern if sometimes `pose` is an `Iso3` and sometimes a `Matrix4` and sometimes a (`Vector3((1, 2, 3)) * 3`).

At the end of the day, I appreciate you don't like "pose". But, whatever your philosophical complaint is, "matrix" is not a viable alternative.

Surely a "pose" vs "matrix" debate is a false dichotomy and a peaceful resolution can be found by striking out into a different direction?
</blockquote></details>

I agree that maybe I should've isolated it to just  "I don't like `pose`" rather than fixate on `matrix`. 

(However, in my mind, a Vector (in Eigen-land at least) is effectively a Nx1 matrix, so it still seems appropriate to me ;) )

My concerns were (b) slightly laziness in not wanting to deprecate the `matrix` argument (though it's done now in a follow-up PR), and (b) namely trying to avoid too many overloads with the same name if possible, because it's confusing if you just look at argument names, and may kick off more complex disambiguation in `mkdoc`. (I should've articulated that earlier.)

But eh, since `pose` is now landed and the `mkdoc` didn't produce anything too esoteric, I'm fine with it as-is. Here's the follow-up:
https://github.com/RobotLocomotion/drake/pull/11948

**Pull request merged**
