### PR TITLE
Do not reconstruct solution when the problem is infeasible

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8430)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-nightly-memcheck-ubsan-everything please.

+@jwnimmer-tri for both reviews.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8430#-:-L8Dh6Yk920ertjzopH0:b4otq15)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8430#-:-L8Dhi06-knLeqBHYZTl:b2ol55z)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

For the record, this was exposed by #8397 where we aggressively set variables to NAN when the MathematicalProgram does not find a solution.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8430#-:-L8DhnUQVGry407p4lvW:bbn3so7)*

**Comment by jwnimmer-tri** [comment]
The ubsan build passed.

**Pull request merged**
