### PR TITLE
adds documentation for stochastic systems …

### PR DESCRIPTION
**Pull request by RussTedrake**
and links to it from the main sphinx page and appropriate methods/classes in the systems framework.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7276)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sherm1 for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KweKfLhWrFz8LCaD_vf:b7dve2f)*

**Comment by jwnimmer-tri** [comment]
With #7273 merged, the docs have moved up a folder.  This will need a rebase.

For #6996 learning purposes, I am curious to hear feedback on any challenges with either locally merging or rebasing this PR, or difficulties with the code review tooling.

**Comment by sherm1** [comment]
Feature :lgtm: with a few BTWs, ptal.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/doc/doxygen.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfCVlxXsuFysrr9DxK:-KwfCVlxXsuFysrr9DxL:b3xvxli) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/doc/doxygen.h#L57)):*
> ```objc
> only updated nightly.</p>
> 
> **/
> ```

BTW @jwnimmer-tri *hates* closing  Doxygen comments with `**/` (which I like). In a moment of warm camaraderie, I promised him I wouldn't do it that way any more. I suggest sticking with `*/` here as a minor concession to a fabulous colleague.

---

*[drake/systems/stochastic_systems.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfEpSOd7J1mj75Qm_T:-KwfEpSOd7J1mj75Qm_U:b-9wvimh) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/stochastic_systems.h#L16)):*
> ```objc
>   x[n+1] = f(n, x[n], u[n], w[n], p), 
> 
>   y[n] = g(n, x[n], u[n], w[n], p), 
> ```

BTW A notation I have adopted for fixed arguments is to list them first, separated from the rest by a semicolon. These would then be:
```
x[n+1] = f(p; n, x[n], u[n], w[n])
  y[n] = g(p; n, x[n], u[n], w[n])
```
This has been a very handy notation for showing functional dependence in constraint equations and their time derivatives, like
```
c(t; q)=0
ċ(t,q; v)=0
c̈(t,q,v; v̇)=0
```
where the constraints restrict only the quantities after the semicolon, but depend on the ones before. I think of this as a text version of the "taken about" math notation we use for derivatives (using a vertical bar), something like `f|ₚ(n, x, u, w)`.

Consider using this notation if you like it.

---

*[drake/systems/stochastic_systems.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfJgndpvVM2dNa1C27:-KwfJgndpvVM2dNa1C28:b-9185x5) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/stochastic_systems.h#L61)):*
> ```objc
> Library.
> 
> **/
> ```

BTW consider a diplomatic `*/` here.

---

*[drake/systems/primitives/random_source.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfK4k5fKI52RXtb2B1:-KwfK4k5fKI52RXtb2B2:b-kmuis4) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/primitives/random_source.h#L49)):*
> ```objc
> ///   http://en.cppreference.com/w/cpp/concept/RandomNumberDistribution
> ///
> /// Note: User code should not instantiate this class directly, but
> ```

BTW consider `@note` to get doxygen to beautify it (and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwfKRmNhUWN2EbxAx5e:b-ensyu7)*

**Comment by RussTedrake** [comment]
@jwnimmer-tri -- rebase was surprisingly pain free (just did a rebase of master onto my branch).  and reviewable looks to have survived nicely, too.  

---

Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/stochastic_systems.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfEpSOd7J1mj75Qm_T:-Kwghq3_kGiBGlGlmmKs:b-v7gann) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/stochastic_systems.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW A notation I have adopted for fixed arguments is to list them first, separated from the rest by a semicolon. These would then be:
```
x[n+1] = f(p; n, x[n], u[n], w[n])
  y[n] = g(p; n, x[n], u[n], w[n])
```
This has been a very handy notation for showing functional dependence in constraint equations and their time derivatives, like
```
c(t; q)=0
ċ(t,q; v)=0
c̈(t,q,v; v̇)=0
```
where the constraints restrict only the quantities after the semicolon, but depend on the ones before. I think of this as a text version of the "taken about" math notation we use for derivatives (using a vertical bar), something like `f|ₚ(n, x, u, w)`.

Consider using this notation if you like it.
</blockquote></details>

Why not.  ;-)  Done.

---

*[drake/systems/stochastic_systems.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfJgndpvVM2dNa1C27:-KwghuARcChYywem4lQP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/stochastic_systems.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider a diplomatic `*/` here.
</blockquote></details>

Done.

---

*[drake/systems/primitives/random_source.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfK4k5fKI52RXtb2B1:-KwgiLCGJ6A_iS1ontXy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/systems/primitives/random_source.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `@note` to get doxygen to beautify it (and below).
</blockquote></details>

Done.

---

*[drake/doc/doxygen.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwfCVlxXsuFysrr9DxK:-KwghWIg8pHaKYowEeIy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09063f8fa7f1b0318975ef512c53481e24d9924b/drake/doc/doxygen.h#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW @jwnimmer-tri *hates* closing  Doxygen comments with `**/` (which I like). In a moment of warm camaraderie, I promised him I wouldn't do it that way any more. I suggest sticking with `*/` here as a minor concession to a fabulous colleague.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwghLVJnYrl1oN6fiZt:bqyn4ju)*

**Comment by RussTedrake** [comment]
+@ericcousineau-tri +@ggould-tri +@jwnimmer-tri +@sammy-tri +@seancurtis-tri +@soonho-tri 
Adding all platform reviewers to confirm (and hereafter enforce) the policy.  

---

Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwgibYdWD4sFwfWEqL7:b1l171y)*

**Comment by sherm1** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by ggould-tri** [comment]
:lgtm:, one doc request below.

---

Reviewed 3 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/stochastic_systems.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjUJmnH3_6Da8vh-Ue:-KwjUJmnH3_6Da8vh-Uf:bpth36v) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L29)):*
> ```objc
> multi-rate systems, and systems with multiple input/output ports as
> well, precisely because w is treated exactly as an additional input
> throughout the system classes.
> ```

This seems a bit abrupt to me.  Continuous-time random variables are theoretically tricky, and the interaction with variable time-stepping is not at all clear to a user who hasn't already read the linked doc.

I  would suggest at least mentioning either that continuous-time randomness is simply fixed-rate sampling or else explicitly referring people to the `RandomSource` doxygen (and not to one of the more specific source classes -- `GaussianRandomSource`, eg, has super unhelpful doxgen http://drake.mit.edu/doxygen_cxx/group__primitive__systems.html#gaae0a3938a8accd4550517a6d3b1a3bbf ).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwjX9muvt7dYOIx-Xw4:b-e788p7)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a couple of BTWs.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/stochastic_systems.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjnjULBpjb51e7HeN7:-KwjnjUNoiVGJrt1Wn32:bj3xziu) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L9)):*
> ```objc
> 
> This page describes the implementation details of modeling a
> stochastic system in Drake and writing algorithms the explicitly
> ```

BTW minor nit Grammar, "~the~ that explicitly"

---

*[drake/systems/stochastic_systems.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjoNwxcb5UGGp6A-j3:-KwjoNwxcb5UGGp6A-j4:bopr5k7) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L47)):*
> ```objc
> random, and the random vector distribution type.  The list of
> supported distributions for random input ports is intentionally very
> limited (to simplify algorithm development); we place the burden on
> ```

BTW Should we explicitly mention that these transformations should *not* occur within an upstream block, but inside of the functions within the receiving block only?
e.g. The user should not make a `GaussianRandomTransform` block, as this will not propagate the `is_random()` flag on the port descriptor.

As an aside, is there anything to catch this defective case? It seems like the receiving block's input would be declared as random, but the actual upstream block would not be a unit distribution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwjqiDvmRKQu2Ygtiil:b-43bae5)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-Kwk5VQBbtM3GDFNjVcE:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwkDlf9HAhZyqY5XDeN:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-KwkNKxOZqDBzuiNNNtc:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/stochastic_systems.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjnjULBpjb51e7HeN7:-KwtGkSC8mJ1D2UZW5Kz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L9)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Grammar, "~the~ that explicitly"
</blockquote></details>

Done.

---

*[drake/systems/stochastic_systems.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjUJmnH3_6Da8vh-Ue:-KwtHqI-xRaVgIfwXMWM:bai54dv) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems a bit abrupt to me.  Continuous-time random variables are theoretically tricky, and the interaction with variable time-stepping is not at all clear to a user who hasn't already read the linked doc.

I  would suggest at least mentioning either that continuous-time randomness is simply fixed-rate sampling or else explicitly referring people to the `RandomSource` doxygen (and not to one of the more specific source classes -- `GaussianRandomSource`, eg, has super unhelpful doxgen http://drake.mit.edu/doxygen_cxx/group__primitive__systems.html#gaae0a3938a8accd4550517a6d3b1a3bbf ).
</blockquote></details>

Done.  Also added @see internal::RandomSource to the "unhelpful" doxygen.

---

*[drake/systems/stochastic_systems.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjoNwxcb5UGGp6A-j3:-KwtHvmUO1oFLsEf_01G:bfb8tve) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L47)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should we explicitly mention that these transformations should *not* occur within an upstream block, but inside of the functions within the receiving block only?
e.g. The user should not make a `GaussianRandomTransform` block, as this will not propagate the `is_random()` flag on the port descriptor.

As an aside, is there anything to catch this defective case? It seems like the receiving block's input would be declared as random, but the actual upstream block would not be a unit distribution.
</blockquote></details>

i don't actually see that as defective.  I agree that random signals will infect downstream signals (making them random variables as well), but the model of the downstream system are still meaningful for deterministic inputs.  

You make a very important point, though.  I've added a line up above to clarify that a random input label specifically denotes the "point of entry" of a new independent random variable.  Is that sufficiently clear?

If someone did write a GaussianRandomTransform block in their code, then I would be ok with it, as long as the system that consumed it was not written in a way that expected randomness in the input always (even if not wired up to the GaussianRandomTransform block).  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r4.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/stochastic_systems.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-Kwtmp-HOwwaETzek_W2:-Kwtmp-Iw9FJKtab6xQY:bizcbo2) ([raw file](https://github.com/robotlocomotion/drake/blob/972dd31d7239b584e4cb71790bef1291ff253bac/drake/systems/stochastic_systems.h#L35)):*
> ```objc
> throughout the system classes.  Continuous-time random signals must
> be treated with some care; see internal::RandomSource for details on
> how they are treated for the purpopses of simulation.  
> ```

FYI trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/stochastic_systems.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-KwjoNwxcb5UGGp6A-j3:-Kwu4mVaCTVWD2arhdkK:b-y37rar) ([raw file](https://github.com/robotlocomotion/drake/blob/69ba5a2650e06f6dc1d42d45408cd323988802aa/drake/systems/stochastic_systems.h#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't actually see that as defective.  I agree that random signals will infect downstream signals (making them random variables as well), but the model of the downstream system are still meaningful for deterministic inputs.  

You make a very important point, though.  I've added a line up above to clarify that a random input label specifically denotes the "point of entry" of a new independent random variable.  Is that sufficiently clear?

If someone did write a GaussianRandomTransform block in their code, then I would be ok with it, as long as the system that consumed it was not written in a way that expected randomness in the input always (even if not wired up to the GaussianRandomTransform block).  
</blockquote></details>

Sounds good, thank you for the explanation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276)*

**Comment by RussTedrake** [comment]
-@SeanCurtis-TRI since he is on vacation.  

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7276#-:-Kwu5_ESpwrGbDn4l55v:b-5u2jmy)*

**Pull request merged**
