### PR TITLE
Require CMake 3.5

### PR DESCRIPTION
**Pull request by bradking**
Per issue #2082.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2415)

### CODE REVIEW

**Comment by bradking** [comment]
Cc: @jamiesnape

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> Cc: @jamiesnape 
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIENOof99OcUDTuP5cJ:1417088721)*

**Comment by jwnimmer-tri** [comment]
On the ubuntu changes... giving hints for versions other than 14.04 might be fine, but we shouldn't call anything other than 14.04 "supported", because only 14.04 is listed in developers.rst as supported, and only 14.04 is covered by jenkins.

**Comment by liangfok** [comment]
Just one minor comment related to @jwnimmer-tri's comment above.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> On the ubuntu changes... giving hints for versions other than 14.04 might be fine, but we shouldn't call anything other than 14.04 "supported", because only 14.04 is listed in developers.rst as supported, and only 14.04 is covered by jenkins.
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-KIIFUIAkrNEssktOGsl:-KIIFUIAkrNEssktOGsm:-1087929894) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a5e96704821d2127ca3cb9124228677b3cbae9/drake/doc/ubuntu.rst#L5)):*
> ```reStructuredText
> ******
> 
> Ubuntu 14.04 LTS (Trusty) or higher is supported.
> ```

Consider replacing the above with:

```
Ubuntu 14.04 LTS (Trusty) is officially supported. More recent versions of Ubuntu are also known to work, and some details are provided below, but are not officially supported.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIIGJoCNuZ23ureFFmW:-1369752498)*

**Comment by bradking** [comment]
Thanks, folks.  I've pushed a revised version of the topic to update the wording about supported versions.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Just one minor comment related to @jwnimmer-tri's comment above.
</details>


---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-KIIFUIAkrNEssktOGsl:-KIT2nF7K7LjXIoA2262:-1494679870) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a5e96704821d2127ca3cb9124228677b3cbae9/drake/doc/ubuntu.rst#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider replacing the above with:
> 
> ```
> Ubuntu 14.04 LTS (Trusty) is officially supported. More recent versions of Ubuntu are also known to work, and some details are provided below, but are not officially supported.
> ```
</details>
Thanks.  I chose slightly different wording to make it easier to update the version(s) we list as supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIT2zSEp4rygg3LDyti:1309999792)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Sorry for the extremely long response time.  I think this merits an update to CHANGELOG.md.  Otherwise :lgtm:

<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> Thanks, folks.  I've pushed a revised version of the topic to update the wording about supported versions.
</details>


---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIcDwag_fe12Z4LGuPm:965396282)*

**Comment by david-german-tri** [comment]
Oh, one other question - are any changes needed to the Mac install instructions?

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Sorry for the extremely long response time.  I think this merits an update to CHANGELOG.md.  Otherwise :lgtm:
</details>


---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIcEp2RqYiC6BSHn3ys:-847731283)*

**Comment by bradking** [comment]
I've pushed a revised version of the topic to update CHANGELOG.md.

> are any changes needed to the Mac install instructions?

No.  Homebrew now installs CMake 3.5.2 automatically.



---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIcGLZeXzAreaihQE3b:1903023714)*

**Comment by david-german-tri** [comment]
Great!  The substantive part of this change passed CI last week, so I'd be willing to merge it without waiting for the current Jenkins backlog to clear.  However, I do want to give TRI developers a little time to update CMake in advance, so we might as well wait for CI to finish also.  I've already circulated a heads-up internally.

**Comment by david-german-tri** [comment]
jenkins: retest this please

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Great!  The substantive part of this change passed CI last week, so I'd be willing to merge it without waiting for the current Jenkins backlog to clear.  However, I do want to give TRI developers a little time to update CMake in advance, so we might as well wait for CI to finish also.  I've already circulated a heads-up internally.
</details>


---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2415#-:-KIcbXEZTAmJZat-Dghl:-1653431160)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
