### PR TITLE
Remove unused FEM code.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
We redesigned the FEM code with the aim to remove virtual methods and heap allocations in inner loop calculations. The new design resides in the namespace `fixed_fem`. The old design in the namespace `fem` is now obsolete.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15332)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for sole review (in dev) please.

I think you'd enjoy this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15332#-:-Me1DkVU53gRxpqE8Kbp:bryaep6)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: to me, if that helps.

> Reviewed 36 of 36 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15332#-:-Me23Eq-BMqq27QI13mf:b-2rmuj0)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-@rpoyner-tri since Jeremy lgtm'ed. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15332#-:-Me23eGG4_VOCQYnkDPg:b5k732l)* status: needs at least one assigned reviewer (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri to make reviewable happy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15332#-:-Me23yNi21RA32rx0DLc:biumdi4)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review (waiting on @xuchenhan-tri)

**Pull request merged**
