### PR TITLE
[multibody] Simplify frames in MultibodyPlant

### PR DESCRIPTION
**Pull request by sherm1**
This is a small step towards a high-performance multibody kernel, see issue #18442. An important goal is to eliminate Context spelunking and virtual methods from the multibody kernel; this moves us part way there and provides a modest performance boost (benchmarks below).

### Background
The Frame class hierarchy was originally designed to support frames on deformable bodies, supporting the notion that a frame's pose on its body might not be constant. We don't need that abstraction now -- all our Frames have fixed poses after parameters have been set (they are either RigidBodyFrames or FixedOffsetFrames). There is overhead associated with that abstraction -- virtual methods, runtime recalculations of pose, and copies rather than references.

### What's here
This PR removes the deformable-frame abstraction and then takes advantage of that to cache Frame pose information as soon as parameters are set rather than at run time. Specifically:
- Removes useless FrameBase class.
- Caches frame pose-in-body and inverse.
- Replaces runtime virtuals and computations with inline cache references.
- Now no kernel function looks in the Context for Frame body poses.

### What's not here
- There are still many places where a Context is being passed in to kernel functions. All of those need to be replaced with precalculated cache entries so that the kernel operates only on numerical quantities. TODOs for now.
- BodyNode needs to be templatized by concrete Mobilizer to allow fixed-size vectors and inline calls rather than virtual functions.

### Release note
Although FrameBase was a public class it had no functionality and served only as the useless base class for Frame. There are no direct uses of FrameBase in Drake or Anzu, and no Python bindings. So although this is technically a breaking change I'm not deprecating it because there is ~zero chance anyone will be affected.

### Benchmarking
CassieBench measures only multibody kernel time, in microseconds.

|      Test        | Master/GCC  |  This PR | Speedup |  Master/Clang  | ThisPR | Speedup |
| --------------- | ------------------ | ----------- | ------------ | -------------------- | ---------- | ------------ |
| MassMatrix |        15.7        |    13.6     |    13%     |         11.5          |   10.4    |    10%    |
| InverseDynamics |        18.3        |    15.3     |    16%     |         13         |   11    |    15%    |
| ForwardDynamics |        40.8        |    38.1     |    7%     |         37.1          |   35.5    |    4%    |

AutoDiff and Expression benchmarks were not measurably affected by this change.

- Puget Xeon E5-2699 v4 @2.2GHz
- gcc 11.4.0
- clang 15.0.7

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@joemasterjohn please LMK if you have time and interest to feature review this. It simplifies the Frame classes and caches poses so we can use inline references. Provides a modest performance boost, see PR description for benchmark data.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5QRllnC7_cqrlFxDXA:b4vgy4x)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @sherm1)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: Very nice! This is super clean, so not much to say on my part. I sprinkled a few thoughts, but all nits.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5UiQpC95dcvGhK1Knh:b-anvhr3)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/tree/frame_body_pose_cache.h` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UQrEH1SnQuDwYVxwJ:-O5UQrEH1SnQuDwYVxwK:bqmi4rz) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/frame_body_pose_cache.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

nit: Unused?



_Code quote:_
```objc
#include <memory>
```
___
*[`multibody/tree/multibody_tree.cc` line 1397 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UarzZEBEsSzXRT9nL:-O5UarzZEBEsSzXRT9nM:b-t4k4f8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/multibody_tree.cc#L1397)):*
> ```cpp
>     }
>     frame_body_poses->set_X_BF(body_pose_index_in_cache,
>                                frame->CalcPoseInBodyFrame(context));
> ```

Super nit picky, but calling `CalcPoseInBodyFrame()` on each frame ends up recomputing the frame compositions all the way up the antecedents each time. If we processed the frames in topological order or just memoized `X_BP` for a frame `F` with parent `P` we could avoid recomputing `X_BP` when computing `X_BF (= X_BP * X_PF)`. Of course this is only becomes a performance issue with super long chains of offset frames. Maybe just worth noting in a comment though? Whatever you think.



_Code quote:_
```cpp
    frame_body_poses->set_X_BF(body_pose_index_in_cache,
                               frame->CalcPoseInBodyFrame(context));
```
___
*[`multibody/tree/test/frames_test.cc` line 290 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5Uh_OhBpjvgz0iVCDi:-O5Uh_Oi1KyfqzI2k2Yv:bqcvp7f) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/test/frames_test.cc#L290)):*
> ```cpp
>       R_BG, kEpsilon));
> 
>   // Change the poses of the parent P and frame Q and make sure those are
> ```

nit: Is there an easy way to detect that a cached quantity has *not* been recomputed from the context of user level code like this? I was just thinking it would be nice to assert that a change to state doesn't recompute `X_BF` when `EvalPoseInBodyFrame()` gets called, to show the more granular dependency is working.

**Review by sherm1 — COMMENTED** [review]
Feature review comments addressed, PTAL. Thanks @joemasterjohn !

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5Uumqn6qAT8Smi_R8S:b-jtd7ao)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`multibody/tree/frame_body_pose_cache.h` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UQrEH1SnQuDwYVxwJ:-O5Un7VIE49Nk2iRzBld:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/frame_body_pose_cache.h#L3)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Unused?
</blockquote></details>

Done
___
*[`multibody/tree/multibody_tree.cc` line 1397 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UarzZEBEsSzXRT9nL:-O5UnBc2DWCv0Eszq064:b-hqvv0d) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/multibody_tree.cc#L1397)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Super nit picky, but calling `CalcPoseInBodyFrame()` on each frame ends up recomputing the frame compositions all the way up the antecedents each time. If we processed the frames in topological order or just memoized `X_BP` for a frame `F` with parent `P` we could avoid recomputing `X_BP` when computing `X_BF (= X_BP * X_PF)`. Of course this is only becomes a performance issue with super long chains of offset frames. Maybe just worth noting in a comment though? Whatever you think.
</blockquote></details>

Yeah, I thought of that too. I talked myself into doing this way based on (a) only doing this when parameters change, (b) likely only short offset frame stacks so not too much recalculation and (c) no convenient data structure around for doing this in a nice order. Added a TODO for now, PTAL. WDYT? 
___
*[`multibody/tree/test/frames_test.cc` line 290 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5Uh_OhBpjvgz0iVCDi:-O5UuKPSAKQ39K2Vmujf:b-rg7quz) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/test/frames_test.cc#L290)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Is there an easy way to detect that a cached quantity has *not* been recomputed from the context of user level code like this? I was just thinking it would be nice to assert that a change to state doesn't recompute `X_BF` when `EvalPoseInBodyFrame()` gets called, to show the more granular dependency is working.
</blockquote></details>

Done. Good idea. Requires a little caching-fu.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with one comment.

> Reviewed 13 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5UxBhh1NIkYwRb7REv:b-51qbwp)* status: 2 unresolved discussions

___
*[`multibody/tree/frame_base.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UoSuIE-C7UIHFeZlw:-O5UoSuIE-C7UIHFeZlx:b-m7478a) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ec9904362edb3bac819971b1156e0318a365e87/multibody/tree/frame_base.h#L51)):*
> ```objc
> /// @tparam_default_scalar
> template <typename T>
> class FrameBase : public MultibodyElement<T> {
> ```

This class is a part of public APIs. Is there a good reason why we aren't deprecating this? In any case, the release note label should be updated.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853)* status: 1 unresolved discussion

___
*[`multibody/tree/multibody_tree.cc` line 1397 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UarzZEBEsSzXRT9nL:-O5UxCHT1AJSLc65GsAv:blddv0i) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/multibody_tree.cc#L1397)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Yeah, I thought of that too. I talked myself into doing this way based on (a) only doing this when parameters change, (b) likely only short offset frame stacks so not too much recalculation and (c) no convenient data structure around for doing this in a nice order. Added a TODO for now, PTAL. WDYT?
</blockquote></details>

Totally agree. Thanks for the comment.
___
*[`multibody/tree/test/frames_test.cc` line 290 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5Uh_OhBpjvgz0iVCDi:-O5UxsUmA1uRlCOlM_c9:b-z43hwq) ([raw file](https://github.com/RobotLocomotion/drake/blob/e39366f21553c3061d9730b9d27bb9eb3b611c16/multibody/tree/test/frames_test.cc#L290)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. Good idea. Requires a little caching-fu.
</blockquote></details>

Awesome, looks great. I thought it might be doable given the access to the `MultibodyTreeSystem` in this unit test.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853)* status: 1 unresolved discussion

___
*[`multibody/tree/frame_base.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UoSuIE-C7UIHFeZlw:-O5V5I1d0-6pIkti1Q0q:b-jwgatw) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ec9904362edb3bac819971b1156e0318a365e87/multibody/tree/frame_base.h#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This class is a part of public APIs. Is there a good reason why we aren't deprecating this? In any case, the release note label should be updated.
</blockquote></details>

Done, thanks. Good point. Technically this is a breaking change so I changed the release note to that. However, there were no uses of this class in Drake or Anzu, no Python bindings, and no functionality so I believe it is harmless and not worth deprecating. I added a note about that in the PR description for the next release, PTAL.

**Review by sherm1 — COMMENTED** [review]
Thanks, @xuchenhan-tri -- I addressed your comment, WDYT?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5V6DZQ1X9Gq99Jwo4C:b-d5ds3h)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: as long as you are confident that no one is depending on the FrameBase class.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-:-O5V7NYP0FNfC9mDa1xy:bepff6a)* status: 1 unresolved discussion

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5V7DyA2KVCSSfa2ZI8):*
BTW, I think the release engineer only sees the commit message (but not the PR description), consider moving the note about the breaking change here.
___
*[`multibody/tree/frame_base.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UoSuIE-C7UIHFeZlw:-O5V6qB24ur8S3xiJ32w:b-hn46gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ec9904362edb3bac819971b1156e0318a365e87/multibody/tree/frame_base.h#L51)):*
If we are sure that no one is relying this, then I think a breaking change is fine. Otherwise, we should deprecate because our guidelines do say that a breaking change is "very rare".

> On very rare occasions it is impractical, too expensive, or logically unsound to meet the full three month deprecation window. In these cases the change will be announced in the “Breaking changes” section of the release notes.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5V7DyA2KVCSSfa2ZI8):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I think the release engineer only sees the commit message (but not the PR description), consider moving the note about the breaking change here.
</blockquote></details>

Done
___
*[`multibody/tree/frame_base.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UoSuIE-C7UIHFeZlw:-O5VA1PF5wuHP5w0VSb7:b-b4w49n) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ec9904362edb3bac819971b1156e0318a365e87/multibody/tree/frame_base.h#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If we are sure that no one is relying this, then I think a breaking change is fine. Otherwise, we should deprecate because our guidelines do say that a breaking change is "very rare".

> On very rare occasions it is impractical, too expensive, or logically unsound to meet the full three month deprecation window. In these cases the change will be announced in the “Breaking changes” section of the release notes.
</blockquote></details>

I know we're not using it internally, and since the class has no functionality there is no sane reason to mention it rather than starting with Frame as in all our examples. So IMO no deprecation needed.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21853)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

___
*[`multibody/tree/frame_base.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21853#-O5UoSuIE-C7UIHFeZlw:-O5VBwH54tIEkln0syKk:b-81nlyp) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ec9904362edb3bac819971b1156e0318a365e87/multibody/tree/frame_base.h#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I know we're not using it internally, and since the class has no functionality there is no sane reason to mention it rather than starting with Frame as in all our examples. So IMO no deprecation needed.
</blockquote></details>

SGTM!

**Pull request merged**
