### PR TITLE
symbolic_py: Bind and test symbolic::Polynomial and MonomialBasis 

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8140)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Fix #8098

+@ericcousineau-tri for feature-review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8140#-:-L5yo9vN4Ke_5-QRDLSU:b-a59e48)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items. Thanks!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/symbolic_py.cc, line 24 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8140#-L5ypCqfB421om__FsjP:-L5ypCqgEyRQoUhkty4_:b-dto8m0) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/symbolic_py.cc#L24)):*
> ```cpp
>   Variables variables;
>   for (const auto& item : l) {
>     variables.insert(item.cast<Variable>());
> ```

Can I ask why `std::vector<Variable>` is insufficient here (or better `Eigen::VectorX<Variable>`)? I believe using just `std::vector<>` should work with an `np.array`, since it's iterable.

---

*[bindings/pydrake/test/symbolic_test.py, line 23 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8140#-L5ypww427y59iZqi8Fj:-L5ypww427y59iZqi8Fk:b1wsgra) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L23)):*
> ```Python
>         self.assertEqual(str((x + y) * x), "(x * (x + y))")
> 
>     def testSimplify(self):
> ```

BTW Could you change these to `snake_case`?

---

*[bindings/pydrake/test/symbolic_test.py, line 81 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8140#-L5ypqRh637vCYBdC4Zt:-L5ypqRh637vCYBdC4Zu:b-oqpbvq) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L81)):*
> ```Python
> 
> # Define global variables to make the tests less verbose.
> x = sym.Variable("x")
> ```

Can you place these at the top, and replace the above declarations of `x` and `y` with these?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8140#-:-L5yq-1Q8IuzkSEVLPLt:b-lte0wg)*

**Comment by soonho-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L5ypCqfB421om__FsjP:-L5z6rt52aS-tTVi9Gd1:b-kd09ov) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/symbolic_py.cc#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can I ask why `std::vector<Variable>` is insufficient here (or better `Eigen::VectorX<Variable>`)? I believe using just `std::vector<>` should work with an `np.array`, since it's iterable.
</blockquote></details>

Done. Thanks for the suggestion!

---

*[bindings/pydrake/test/symbolic_test.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L5ypww427y59iZqi8Fj:-L5yqQmn1aMVel9EqFDT:b6vpblg) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you change these to `snake_case`?
</blockquote></details>

I'll open another PR after this one to 1) clean up the existing tests (such as this one) and 2) merge `symbolic_*_test.py`s into `symbolic_test.py` as you asked before.

---

*[bindings/pydrake/test/symbolic_test.py, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L5ypqRh637vCYBdC4Zt:-L5yqfEj4w6pAPiAhWsD:b5rkt7i) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L81)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you place these at the top, and replace the above declarations of `x` and `y` with these?
</blockquote></details>

Same for this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140)*

**Comment by soonho-tri** [comment]
+@sherm1 for platform-review, please (I'm on-call today).

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-:-L5z8bKUF1U8nb_pzrZR:bys301s)*

**Comment by soonho-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/test/symbolic_test.py, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L5ypqRh637vCYBdC4Zt:-L5z8jWE44tUFd3KT61D:b-uh88vc) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L81)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Same for this one.
</blockquote></details>

Actually, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/test/symbolic_test.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L5ypww427y59iZqi8Fj:-L5z9GqjhuooKl-Hc-_K:b-aevxo6) ([raw file](https://github.com/robotlocomotion/drake/blob/66196ffab5dc850ddfb2c849f8bd1587bade6075/bindings/pydrake/test/symbolic_test.py#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'll open another PR after this one to 1) clean up the existing tests (such as this one) and 2) merge `symbolic_*_test.py`s into `symbolic_test.py` as you asked before.
</blockquote></details>

OK Sounds good, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140)*

**Comment by sherm1** [comment]
Platform :lgtm: (one FYI)

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L62q-QqW5aueYHlsB_U:-L62q-QqW5aueYHlsB_V:b-bi2eo7) ([raw file](https://github.com/robotlocomotion/drake/blob/f2b982dd2d95a6f143bc02da00869df778c82847/bindings/pydrake/symbolic_py.cc#L464)):*
> ```cpp
>            })
>       .def("__pow__",
>            [](const Polynomial& self, const int n) { return pow(self, n); });
> ```

FYI no `__hash__` for Polynomial (in case there should be one).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-:-L62qkKrJug1x6vzwv0n:b-z9oguv)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8140#-L62q-QqW5aueYHlsB_U:-L633I2T-kj88LZ_gg3k:b-1t85qg) ([raw file](https://github.com/robotlocomotion/drake/blob/f2b982dd2d95a6f143bc02da00869df778c82847/bindings/pydrake/symbolic_py.cc#L464)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI no `__hash__` for Polynomial (in case there should be one).
</blockquote></details>

We don't have the function on the C++ side. I open an issue, https://github.com/RobotLocomotion/drake/issues/8159. I'll work on that and add to the Python-side as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8140)*

**Pull request merged**
