### PR TITLE
[setup] Remove dependency on bzip2

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We added this in #7418 to work around an Ubuntu 16.04 bug in its pkg-config files. That's no longer necessary.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20352)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review, please.  (Feel free to delegate.)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20352#-:-NgZsMqMEv5HJ3Kp7bdM:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),BetsyMcPhail

**Pull request merged**
