### PR TITLE
[common] Add string container helper aliases

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(See commit message for details.)

Requires:
- [ ] #20954
- [x] #20961

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Even though this won't pass CI until the CI config changes (dropping Focal support), I think the code here is finished so we can kick off the review. Jammy and macOS CI should still all be passing.

+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
Nice! Feature :lgtm: with a few questions/comments

> Reviewed 29 of 32 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-:-Nr1Lhef6bFkQ00_s0C3:b-4hzfea)* status: 9 unresolved discussions, needs at least two assigned reviewers

___
*[`common/string_hash.h` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1Clym2f2AOggoVchZ:-Nr1Clym2f2AOggoVch_:b7eg6uu) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/string_hash.h#L12)):*
> ```objc
> accept either `std::string` or `std::string_view` or `const char*` key during
> lookup operations (find, count, etc.) via "transparent" lookups. */
> struct StringHash final : public std::hash<std::string_view> {
> ```

BTW consider adding something like: "we don't need to add overloaded hash functions here because all of these convert to string_view" and then can be hashed with the base type." (it took me a while to sort that out)
___
*[`common/string_map.h` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr17wNFBBYCuz4OnIsc:-Nr17wNFBBYCuz4OnIsd:bbb4ye1) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/string_map.h#L10)):*
> ```objc
> 
> /** Like `std::map<std::string, T>`, but with defaults that aren't polluted by
> C++ backwards compatibility braindeath. */
> ```

minor: colorful for sure, but I didn't find the comment helpful. I _think_ the point here is to use the type-deducing `less<void>` rather than the default `less<string>`. The comment should make that clear. Re the color commentary, I like it but actually didn't understand how this is related to backwards compatibility. Should the STL default to `less<void>` always? Or just for strings?
___
*[`common/string_map.h` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1Dirr4yTQxlfYRBUf:-Nr1Dirr4yTQxlfYRBUg:b-cjsml1) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/string_map.h#L12)):*
> ```objc
> C++ backwards compatibility braindeath. */
> template <typename T>
> using string_map = std::map<std::string, T, std::less<void>>;
> ```

BTW I believe the syntax `less<>` would also work. To me that seems more suggestive of type flexibility than `less<void>` does. Either is fine; just wanted to write down that thought.
___
*[`common/test/string_container_test.cc` line 24 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1Fkw6CJNLqDJmkgYJ:-Nr1Fkw7EtyonUZLGyMV:b65irf6) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/test/string_container_test.cc#L24)):*
> ```cpp
>   dut.insert("hello");
>   const int count = 2;
>   EXPECT_EQ(dut.count("hello"), count);
> ```

BTW these first two tests don't check for string and string_view compatibility like the rest  of them do.
___
*[`common/test/string_container_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1G8Np6S0XbvvRaZXF:-Nr1G8Np6S0XbvvRaZXG:b-8dd3ui) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/test/string_container_test.cc#L93)):*
> ```cpp
>   // Demonstrate that the container is unordered.
>   EXPECT_GT(dut.bucket_count(), 0);
> }
> ```

BTW Ignorable: I was disappointed that none of these tests show that these containers avoid the heap allocation needed to convert a char* to a string for lookup. Properly implemented that is of course the job of the compiler, but it would be reassuring to see that it actually is working. WDYT about adding a test using LimitMalloc? Could contrast for example string_set::count() with std::set::count() to show that one is a heap hog and the other isn't. (Might be tricky with small string optimization though.)
___
*[`common/yaml/yaml_read_archive.h` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IN2b7n1umLuJJAUE:-Nr1IN2b7n1umLuJJAUF:b-j9dyxt) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L132)):*
> ```objc
>   // Serialize function required for the map itself.
>   template <typename Serializable, typename Compare, typename Allocator>
>   void DoAccept(std::map<std::string, Serializable, Compare, Allocator>* value,
> ```

BTW is this change just to increase applicability of this function, or was it actually needed here?
___
*[`common/yaml/yaml_read_archive.h` line 576 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IZYlEI9rzDRuhBk7:-Nr1IZYm6PRmfCGft0bA:b75k5cu) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L576)):*
> ```objc
>   // The set of NameValue::name keys that have been Visited by the current
>   // Serializable's Accept method so far.
>   string_set visited_names_;
> ```

BTW was the conversion from unordered to ordered here intentional?
___
*[`lcm/drake_lcm_log.cc` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1JgzVAqOikTJZT-7n:-Nr1JgzVAqOikTJZT-7o:bj5f8ll) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/lcm/drake_lcm_log.cc#L146)):*
> ```cpp
> 
>   // Dispatch message if necessary.
>   const std::string_view channel(next_event.channel, next_event.channellen);
> ```

BTW the change from string to string_view return type here implies a longer lifetime for the underlying string than was assumed before since it was copied. Is that reasonable? If so, please consider a comment noting why this is safe.
___
*[`systems/framework/diagram.cc` line 1726 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1KnUrE2o0RHTPWRPu:-Nr1KnUrE2o0RHTPWRPv:b88p1m9) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/systems/framework/diagram.cc#L1726)):*
> ```cpp
> template <typename T>
> bool Diagram<T>::NamesAreUniqueAndNonEmpty() const {
>   std::unordered_set<std::string> names;
> ```

BTW you changed from std::set to std::unordered_set here:
- why make this unordered? 
- why isn't this a string_set or string_unordered_set ?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`common/string_map.h` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr17wNFBBYCuz4OnIsc:-Nr1uxbr9kGecMZdhEMi:b-tx9pb) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/string_map.h#L10)):*
I added more text.

I guess it's still not quite to the point of a [religious text](https://github.com/mpv-player/mpv/commit/1e70e82baa9193f6f027338b0fab0f5078971fbe), though.  I am but an egg.

> ... how this is related to backwards compatibility.

It's insane that in C++20 I can't write the simple `std::map<std::string, T>` and have a lookup with `std::string_view` do the obvious thing automatically.  To me, this entire pile of header file aliases is necessary because the standards committee places backwards compatibility above everything else, to the detriment of language usability and performance.
___
*[`common/string_map.h` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1Dirr4yTQxlfYRBUf:-Nr1sk2d36Ypiv8MSXaS:b5d3sx8) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/string_map.h#L12)):*
> BTW I believe the syntax `less<>` would also work.

Yes, it would.

> To me that seems more suggestive of type flexibility than `less<void>` does. Either is fine; just wanted to write down that thought.

I was hoping that this spelling would help people find the docs at https://en.cppreference.com/w/cpp/utility/functional/less more approachable.

Anyway, I added some more docs.  LMK.
___
*[`common/test/string_container_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1G8Np6S0XbvvRaZXF:-Nr1x2ox6B0Yk1aNVUIO:b-3n1lwd) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/test/string_container_test.cc#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Ignorable: I was disappointed that none of these tests show that these containers avoid the heap allocation needed to convert a char* to a string for lookup. Properly implemented that is of course the job of the compiler, but it would be reassuring to see that it actually is working. WDYT about adding a test using LimitMalloc? Could contrast for example string_set::count() with std::set::count() to show that one is a heap hog and the other isn't. (Might be tricky with small string optimization though.)
</blockquote></details>

Working

For the most part, the existing no-heap tests (like in MbP) cover this indirectly, for all the cases we care about.  In any case, I think it's worth adding the tests.
___
*[`common/yaml/yaml_read_archive.h` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IN2b7n1umLuJJAUE:-Nr1pKT6BYFoegZhKlY8:bnv3686) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L132)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this change just to increase applicability of this function, or was it actually needed here?
</blockquote></details>

I added some test cases that cover it now.
___
*[`common/yaml/yaml_read_archive.h` line 576 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IZYlEI9rzDRuhBk7:-Nr1ntKvDOmZ2YcWIr7-:b55a5z) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L576)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW was the conversion from unordered to ordered here intentional?
</blockquote></details>

Yikes!  Fixed.
___
*[`lcm/drake_lcm_log.cc` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1JgzVAqOikTJZT-7n:-Nr1qOQw67T9UweMdtNZ:bb993vw) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/lcm/drake_lcm_log.cc#L146)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the change from string to string_view return type here implies a longer lifetime for the underlying string than was assumed before since it was copied. Is that reasonable? If so, please consider a comment noting why this is safe.
</blockquote></details>

I think maybe this PR diff is making this seem more important than a reader coming to this code for the first time would experience.  The `multi_handler(channel, ...);` call below already uses `string_view` as the type of its first argument.

I worry that trying to add a comment here would be more confusing than helpful.  Do you have some language you think might help?
___
*[`systems/framework/diagram.cc` line 1726 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1KnUrE2o0RHTPWRPu:-Nr1rukU-ORExQcqsB-x:b-uvyu7b) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/systems/framework/diagram.cc#L1726)):*
> Why make this unordered?

Because we never iterate over it (instead only using it for membership tests), so unordered is the correct choice.

> Why isn't this a string_unordered_set?

Meh.  It's not faster since we never look up string views, but I suppose we might as well.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`common/test/string_container_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1G8Np6S0XbvvRaZXF:-Nr23T7lAxDH9Y94bfwV:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/test/string_container_test.cc#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

For the most part, the existing no-heap tests (like in MbP) cover this indirectly, for all the cases we care about.  In any case, I think it's worth adding the tests.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
Love it, thanks!

> Reviewed 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-:-Nr295DNCq3zbNp9rT8M:b-xqeifk)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`common/yaml/yaml_read_archive.cc` line 342 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr28odq5sLoT2FRFPbW:-Nr28odr24TeGh_P7A_b:b2rkbr4) ([raw file](https://github.com/RobotLocomotion/drake/blob/83643da49f4aa952d0015447a033e4b3f84ac26a/common/yaml/yaml_read_archive.cc#L342)):*
> ```cpp
>   for (const auto& [key, value] : root_->GetMapping()) {
>     unused(value);
>     if (!visited_names_.contains(key)) {
> ```

FYI sweet!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`common/yaml/yaml_read_archive.cc` line 342 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr28odq5sLoT2FRFPbW:-Nr29eE8ArqVARN6Z2eT:bjfifuc) ([raw file](https://github.com/RobotLocomotion/drake/blob/83643da49f4aa952d0015447a033e4b3f84ac26a/common/yaml/yaml_read_archive.cc#L342)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI sweet!
</blockquote></details>

Yeah, h/t grant who reminded me of this.  I have a note on my list to follow up and fix it everywhere else in the codebase, too.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review, please (load balancing).

Even though this won't pass CI until the CI config changes (dropping Focal support), Jammy and macOS CI should still all be passing.  I'd like to have this ready to merge as soon as Focal is gone.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 13 of 32 files at r1, 1 of 4 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-:-Nr8QkCM3lCZjT2MHkJ0:b-cxwtpw)* status: 2 unresolved discussions

___
*[`common/string_hash.h` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr8NZ9j3uqI8axmY0mS:-Nr8NZ9j3uqI8axmY0mT:bqdy5tr) ([raw file](https://github.com/RobotLocomotion/drake/blob/83643da49f4aa952d0015447a033e4b3f84ac26a/common/string_hash.h#L13)):*
> ```objc
> lookup operations (find, count, etc.) via "transparent" lookups. */
> struct StringHash final : public std::hash<std::string_view> {
>   using is_transparent = void;
> ```

BTW didn't know about transparent lookup before. TIL, thanks.
___
*[`common/yaml/yaml_read_archive.h` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IN2b7n1umLuJJAUE:-Nr8Pf4H-e7zUvDCOW4J:b-tx4qil) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I added some test cases that cover it now.
</blockquote></details>

I believe the change is required here as part of the PR.

As we transition to `string_map` and company and start recommending people to use them over the plain string-keyed container, inevitably people will start using them and serializing them.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)* status: 1 unresolved discussion

___
*[`common/string_hash.h` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr8NZ9j3uqI8axmY0mS:-Nr8SFf76CCTKzae3CRE:bh2b78r) ([raw file](https://github.com/RobotLocomotion/drake/blob/83643da49f4aa952d0015447a033e4b3f84ac26a/common/string_hash.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW didn't know about transparent lookup before. TIL, thanks.
</blockquote></details>

It's is hard to overstate how much better C++20 will be than C++17.  I can't wait until we can use even more of it.
___
*[`common/yaml/yaml_read_archive.h` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1IN2b7n1umLuJJAUE:-Nr8S4ucD53C69CJb8-U:bcuze6a) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/common/yaml/yaml_read_archive.h#L132)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I believe the change is required here as part of the PR.

As we transition to `string_map` and company and start recommending people to use them over the plain string-keyed container, inevitably people will start using them and serializing them.
</blockquote></details>

Exactly right.  Serialization would not have worked, without this change.  I'd tried to sneak it in without tests, but I got caught and so I added the tests =P.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20970)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

___
*[`lcm/drake_lcm_log.cc` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20970#-Nr1JgzVAqOikTJZT-7n:-NrDppWL6OdPuJEtIpgC:b-gsaw81) ([raw file](https://github.com/RobotLocomotion/drake/blob/606b0b4c4b2965e6c97897445f02a49263913bc9/lcm/drake_lcm_log.cc#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think maybe this PR diff is making this seem more important than a reader coming to this code for the first time would experience.  The `multi_handler(channel, ...);` call below already uses `string_view` as the type of its first argument.

I worry that trying to add a comment here would be more confusing than helpful.  Do you have some language you think might help?
</blockquote></details>

LMK if there's more you think would help here.  For now, onward!

**Pull request merged**
