### PR TITLE
Add indeterminate

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6300)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-Km8i0SEsFpUOMKAXwcm:b-9bkfct)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
+@fischergundlach , feature-review please. I think we resolved the issue in `rotation_constraint_test` which was the reason why we reverted the origin PR. Basically, please check that this is what you put in the original PR.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-KmClEIqQh10-96ZAcpZ:bibbc75)*

**Comment by soonho-tri** [comment]
/cc @hongkai-dai

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-KmClZs4HMWc2SBTPI1l:bvxncw8)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-KmFUAUI5c6BuLgUPK-u:b-imq3bt)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-KmIDgg8YroAaEL-aZ0h:bq323eq)*

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-KmRESPTyf94SKGfP7e_:bnfp4nl)*

**Comment by soonho-tri** [comment]
This PR is to re-introduce #6153 which was reverted by #6210. We fixed the root-cause by #6299.
:lgtm: 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6300#-:-Knehwqy5GG0zfTFf7Ex:b-gxzyco)*

**Pull request merged**
