### PR TITLE
Install msgpack-cxx on Mac

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Mac unprovisioned builds (e.g. https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-big-sur-unprovisioned-clang-bazel-nightly-release/203/)  are failing with the error:

```
geometry/meshcat.cc:17:10: fatal error: 'msgpack.hpp' file not found
#include <msgpack.hpp>
```

The failures started after msgpack 4.0.0 (https://github.com/msgpack/msgpack-c/releases) was released. 

The c++ headers are no longer in msgpack but are now in msgpack-cxx (https://github.com/Homebrew/homebrew-core/commit/00cc39a5ccaa6c61e3a10b2dc15e1ad07f171b4f)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Review by BetsyMcPhail — COMMENTED** [review]
+@seancurtis-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWa3B17cS4KPneudQk:b-vwnbww)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Comment by RussTedrake** [comment]
___
*[setup/mac/binary_distribution/Brewfile, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15694#-MiWaECa0Sypl6uB91-2:-MiWaECa0Sypl6uB91-3:b2oa7mu) ([raw file](https://github.com/robotlocomotion/drake/blob/b8fd5c2b36dce079310cfbea16bfcfb10c98222c/setup/mac/binary_distribution/Brewfile#L24)):*
> ```Ruby
> brew 'nlopt'
> brew 'numpy'
> brew 'msgpack'
> ```

we only need msgpack-cxx, i think we should delete msgpack

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15694#-MiWaECa0Sypl6uB91-2:-MiWajp5DfWlPV10ZaRt:b-swkf82) ([raw file](https://github.com/robotlocomotion/drake/blob/b8fd5c2b36dce079310cfbea16bfcfb10c98222c/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we only need msgpack-cxx, i think we should delete msgpack
</blockquote></details>

Probably worth doing that quickly, so we can retrigger the mac tests.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Comment by BetsyMcPhail** [comment]
___
*[setup/mac/binary_distribution/Brewfile, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15694#-MiWaECa0Sypl6uB91-2:-MiWbggc0iisinlsQYvb:b9ap4wu) ([raw file](https://github.com/robotlocomotion/drake/blob/b8fd5c2b36dce079310cfbea16bfcfb10c98222c/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Probably worth doing that quickly, so we can retrigger the mac tests.
</blockquote></details>

Updated and mac tests have been re-run.

**Review by BetsyMcPhail — COMMENTED** [review]
Once this passes Mac unprovisioned CI, the Mac provisioned images should also be updated

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWgRIh7hw_8nq--4wW:b4oumv1)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by BetsyMcPhail — COMMENTED** [review]
CI (https://drake-jenkins.csail.mit.edu/job/mac-catalina-unprovisioned-clang-bazel-experimental-release/107/console) is _not_ happy with this change. 

```
[10:09:15 AM]    /Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/tools/workspace/msgpack/repository.bzl:14:26: in msgpack_repository
[10:09:15 AM]  Repository rule pkg_config_repository defined at:
[10:09:15 AM]    /Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/tools/workspace/pkg_config.bzl:285:40: in <toplevel>
[10:09:15 AM]  ERROR: An error occurred during the fetch of repository 'msgpack':
[10:09:15 AM]     Traceback (most recent call last):
[10:09:15 AM]  	File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/tools/workspace/pkg_config.bzl", line 279, column 13, in _impl
[10:09:15 AM]  		fail("Unable to complete pkg-config setup for " +
[10:09:15 AM]  Error in fail: Unable to complete pkg-config setup for @msgpack repository: error 1 from [/usr/local/bin/pkg-config, "msgpack"]: 
[10:09:15 AM]  ERROR: Error fetching repository: Traceback (most recent call last):
[10:09:15 AM]  	File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/tools/workspace/pkg_config.bzl", line 279, column 13, in _impl
[10:09:15 AM]  		fail("Unable to complete pkg-config setup for " +
[10:09:15 AM]  Error in fail: Unable to complete pkg-config setup for @msgpack repository: error 1 from [/usr/local/bin/pkg-config, "msgpack"]: 
[10:09:15 AM]  ERROR: /Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/geometry/BUILD.bazel:348:17: //geometry:meshcat_types depends on @msgpack//:msgpack in repository @msgpack which failed to fetch. no such package '@msgpack//': Unable to complete pkg-config setup for @msgpack repository: error 1 from [/usr/local/bin/pkg-config, "msgpack"]: 
[10:09:17 AM]  Analyzing: 8520 targets (362 packages loaded, 14282 targets configured)
[10:09:18 AM]  ERROR: /Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-experimental-release/src/geometry/BUILD.bazel:359:17: //geometry:meshcat depends on @msgpack//:msgpack in repository @msgpack which failed to fetch. no such package '@msgpack//': Unable to complete pkg-config setup for @msgpack repository: error 1 from [/usr/local/bin/pkg-config, "msgpack"]: 
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWnDjD2HNyNUSQ0R5Y:byzpcmw)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Big sur is in the same exact boat.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWoDWA2L5cXyF3kSsd:bc6r6ho)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Should we have an os-dependent spelling of what flavor of msgpack we depend on?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWoO129pTjoJGOf9gc:b-wtecqr)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
What a pain…. You’re right.  It *might* be enough to update only the pkgconfig path hint in that repository.bzl.  That hint is already there to help only homebrew.  I can try when i get back to a mac laptop in about 45 min.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiWwGacALkwUraJIKwZ:b-yvhiko)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Fingers crossed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiX32jc0mJ5GUiL8gya:bbs3yx6)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by RussTedrake — COMMENTED** [review]
It looks like msgpack-cxx doesn't even install a pkgconfig anymore.  I think the cflags are relatively trivial to write ourselves.  So I suspect that will be our best solution.   Unforunately, I've got to present in a few minutes.  @betsymcphail -- can you take it?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiXElAV4slFS9Hu9NkQ:b-lrxd0w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
I will take a look

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiXKa63AlvOICkgG6C4:b-2q02cb)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
The Mac provisioned images will absolutely need to be updated when this change goes in. It will be a bit of a chicken + egg situation, the current repo will fail with updated images but this PR will fail with current images.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiYDoqx-J_LvtskuuvK:bpcjv6r)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[tools/workspace/msgpack/repository.bzl, line 35 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15694#-MiYbVsi5fPqY5gyqGf1:-MiYbVsi5fPqY5gyqGf2:b-oiggfw) ([raw file](https://github.com/robotlocomotion/drake/blob/0e8b033a1b5ade8d82aa34051728adb2a03a9857/tools/workspace/msgpack/repository.bzl#L35)):*
> ```Starlark
>         file_content = """# -*- python -*-
> 
> # DO NOT EDIT: generated by msgpack_repository()
> ```

BTW  I'm not sure how to interpret this line. What is not to be edited? What is generated? Everything below this line? Then where's the generator? It's strange that the license is explicitly spelled out twice.

**Review by SeanCurtis-TRI — COMMENTED** [review]
One test down, the incomplete test has gone past the normal fail point. Definitely looks good.

I don't know the build infrastructure well enough to comment on the nitty gritty of how this was achieved, but I'm going to give it my :LGTM: because it apparently fixes the CI problems

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiYi5d12bRQcoI7wb7p:b-fjxjvb)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
All tests have passed! Given that it's almost 8 pm eastern time, I'm going to squash merge this so we can quite down nightly CI.

+(status: squashing now) 
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15694#-:-MiYjY5O0LMvdGupnswz:b-92xwjp)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
