### PR TITLE
Adds car_sim_lcm_speed_bump.

### LINKED ISSUE #4110: Create a version of car_sim_lcm that uses rough terrain
It currently uses a flat terrain.

### PR DESCRIPTION
**Pull request by liangfok**
This adds a demonstration of a simulated car driving over a speed bump. Here is a screenshot:

screen shot 2016-12-08 at 11 11 11 pm

Here is a video: https://youtu.be/on6DbVWzZqM

The speed bump is an `.obj` mesh generated by Maliput.

Resolves #4110.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4435)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR extends #3886. @ggould-tri and @jwnimmer-tri, since you were the reviewers of #3886:

+@jwnimmer-tri for feature review please.
+@ggould-tri for platform review please.

Thanks!

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-:-KYWpIZvjS-aSFsO3wvU:b-gdmako)*

**Comment by liangfok** [comment]
I am going to apply the "do no merge" label because I just recalled a previous conversation about committing the `maliput` YAML file that generates the `.obj` file rather than the `.obj` file itself. This is important because in this case, the `.obj` file is 1.3MB in side whereas the YAML file is only a few KB.

Until the build system is able to automatically generate the `.obj` files from the YAML files, I suppose the best we can do is to provide detailed instructions. This, however, will not be possible until Maliput's utilities are merged into Drake's master.

**Comment by liangfok** [comment]
I replaced the 1MB `speed_bump.obj` with the 1.3KB `speed_bump.yaml` and updated `README.md` with instructions on how to generate the `.obj` from the `.yaml`. I shall thus remove the "do not merge" label.

**Comment by ggould-tri** [comment]
:lgtm:.  Sorry to see that this can't run yet, but at least it is available and documented.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/models/speed_bump/speed_bump.sdf, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KYZsh5dD34_BWC5sREz:-KYZsh5eAym7TnZNaiuq:b-r7bfmu) ([raw file](https://github.com/robotlocomotion/drake/blob/4b159a5addf5414f300afbfededc4207675bafe2/drake/automotive/models/speed_bump/speed_bump.sdf#L7)):*
> ```
>     <link name="bump">
>       <pose>2 0 0 0 0 0</pose>
>

**Comment by liangfok** [comment]
This PR passed all pre-merge CI tests and is thus ready to be reviewed.

**Comment by liangfok** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/models/speed_bump/speed_bump.sdf, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KYZsh5dD34_BWC5sREz:-KY_3tXpOkzrNEdh9D30:b-d5q2ho) ([raw file](https://github.com/robotlocomotion/drake/blob/4b159a5addf5414f300afbfededc4207675bafe2/drake/automotive/models/speed_bump/speed_bump.sdf#L7)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

fyi -- typo "the" should be "be"?
</blockquote></details>

Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_sim_lcm_speed_bump.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KY_anPOWisAGXGZ78o7:-KY_anPOWisAGXGZ78o8:b-qseswt) ([raw file](https://github.com/robotlocomotion/drake/blob/cd32fb10a3316f4a40a0bb82ea3baea26f7873cc/drake/automotive/car_sim_lcm_speed_bump.cc#L1)):*
> ```cpp
> #include <gflags/gflags.h>
> ```

Why is this a separate main program and binary, instead of a command-line switch to the original binary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by liangfok** [comment]
*[drake/automotive/car_sim_lcm_speed_bump.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KY_anPOWisAGXGZ78o7:-KY_egMsPIRXK6dFRBVx:b-l8m5ky) ([raw file](https://github.com/robotlocomotion/drake/blob/cd32fb10a3316f4a40a0bb82ea3baea26f7873cc/drake/automotive/car_sim_lcm_speed_bump.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why is this a separate main program and binary, instead of a command-line switch to the original binary?
</blockquote></details>

I anticipate we will soon want to have the vehicle in many different environments. I figure programatically specifying the environment is preferable to specifying it via the command line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/car_sim_lcm_speed_bump.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KY_anPOWisAGXGZ78o7:-KY_gT0K5YZEBEAzzmno:byle8mh) ([raw file](https://github.com/robotlocomotion/drake/blob/cd32fb10a3316f4a40a0bb82ea3baea26f7873cc/drake/automotive/car_sim_lcm_speed_bump.cc#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I anticipate we will soon want to have the vehicle in many different environments. I figure programatically specifying the environment is preferable to specifying it via the command line.
</blockquote></details>

We don't need to turn code into data.  But a `--with-speed-bump`boolean flag that enabled the code to load and setup extra model?  I think having lots of binaries will be challenging to maintain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_sim_lcm_speed_bump.cc, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KY_anPOWisAGXGZ78o7:-KY_vsYbhevZfeWP4Cvr:bk8o0v1) ([raw file](https://github.com/robotlocomotion/drake/blob/cd32fb10a3316f4a40a0bb82ea3baea26f7873cc/drake/automotive/car_sim_lcm_speed_bump.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We don't need to turn code into data.  But a `--with-speed-bump`boolean flag that enabled the code to load and setup extra model?  I think having lots of binaries will be challenging to maintain.
</blockquote></details>

OK, I will use a `--with-speed-bump` in this case. I'll keep the `car_sim_lcm_common.h` in anticipation of future examples of a physical car operating in environments that are better created programmatically​.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by liangfok** [comment]
I addressed all reviewer​ comments. PTAL. Thanks.

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-:-KYaBZUaW89bppSWM0Qs:b-3rrw1w)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_sim_lcm_common.cc, line 240 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KYaFMpN6tFJmWCTf_DG:-KYaFMpOJFnt-YySdTMi:b-kfhvnb) ([raw file](https://github.com/robotlocomotion/drake/blob/4b159a5addf5414f300afbfededc4207675bafe2/drake/automotive/car_sim_lcm_common.cc#L240)):*
> ```cpp
> 
>   // TODO(liang.fok): Modify controller to provide named accessors to these
>   // ports.
> ```

BTW `get_{control,state}_input_port` exist now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-:-KYaH0CILOrlQGc-DmPD:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Now waiting for CI.

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_sim_lcm_common.cc, line 240 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-KYaFMpN6tFJmWCTf_DG:-KYaSVifzgHG02R4tXDB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b159a5addf5414f300afbfededc4207675bafe2/drake/automotive/car_sim_lcm_common.cc#L240)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `get_{control,state}_input_port` exist now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435#-:-KYaSwDGpvZEtoIuqDj5:b93f663)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4435)*

**Pull request merged**
