### PR TITLE
Bind GcsTrajectoryOptimization::EstimateComplexity

### PR DESCRIPTION
**Pull request by cohnt**
Very tiny PR -- I wanted to use this function for something in python, and figured there's a chance others might want to as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20861)

### CODE REVIEW

**Comment by sherm1** [comment]
Do you have a feature reviewer in mind for this, @cohnt ?

**Comment by RussTedrake** [comment]
wait... why do you want to use this function?  I actually don't like that function; and thought it was only there for testing purposes?

**Comment by cohnt** [comment]
As I'm running multiple GCS programs of different sizes and levels of connectivity, I wanted a better way to compare their complexity. It's not super important, but since it was publicly available in the C++, I figured I could add a quick Python binding.

**Review by sherm1 — COMMENTED** [review]
+@RussTedrake for design/feature/platform review since you already have eyes on
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20861#-:-Np_jNI19H3PiMsJ3p2D:b5nufdg)* status: LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @cohnt)

**Comment by jwnimmer-tri** [comment]
With my platform reviewer hat on:

At the moment, this PR is internally inconsistent because it binds a function for end-users whose docs say it's not intended for end-users.  (The API comment is somewhat ambiguous, though.)

I think we're on a saddle with two ways out:

(1) Clarify the ambiguous API comment by removing the "for regression testing purposes" text.  Add the Python binding.  Given https://github.com/RobotLocomotion/drake/pull/19444#pullrequestreview-1464885672, it seems like you might also need to convince Russ about a better function name, and/or an improved implementation.

(2) Clarify the ambiguous API comment by strengthening "for regression testing purposes" to more directly say "Internal use only", and hiding the function from Doxygen.  If y'all decide to go this route, LMK and I can prepare a new PR with the right Doxygen giblets for this approach.

\CC @ggould-tri FYI as reviewer on the prior PR.

**Review by ggould-tri — COMMENTED** [review]
Yeah, for better or for worse this is my review comment* coming home to roost.

I think Jeremy's suggestions are really the two most sensible approaches; my own inclination is that where there's an understandable user desire, we should be biased in favor of meeting it.  But if the entire concept of the method is unsound, suggestion 2 would be appropriate.

(* this one:
> I'd go so far as to say it probably should be a public function (albeit documented as advanced usage) since I expect some of the academic users might be interested in it, e.g. for lecture materials for Russ's manipulation course. But that's just a superficial opinion.

)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20861#-:-Np_oTfO2gZxL16pRuwI:b-fcpt9p)* status: LGTM missing from assignee RussTedrake(platform)

**Comment by wrangelvid** [comment]
I agree with Russ that the function should be improved. Full disclosure, in my fork I use a binding of this function to set the number of super basics SNOPT should use. There is use in an improved version that is not only for internal use.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20861)* status: LGTM missing from assignee RussTedrake(platform)

**Comment by RussTedrake** [comment]
The function was initially introduced because David was PR'ing an implementation-only change (no API change, no functionality change), citing that the problem formulation got smaller, and we wanted a strategy to confirm that in a test.

The conversation in this thread suggests to me that it is already being interpreted as having a meaningful correspondence with GCS solve times. I'm not at all convinced that it does.  (I could be convinced, and could definitely believe that it would be valuable if that correlation was available).  My first preference would be to become convinced.  My second preference would be to mark it explicitly internal (or even remove it entirely).

**Review by RussTedrake — COMMENTED** [review]
@cohnt -- WDYT?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20861#-:-NrWSQ3a2lMc0GQj0DXN:b-jvx5io)* status: LGTM missing from assignee RussTedrake(platform)

**Comment by cohnt** [comment]
Having some sort of measure of the complexity of a mathematical program is super useful. Even if it's only weakly monotonic, being able to compare two programs and say "this one is much harder than the other" is very nice. It doesn't have to be this method, and if there's a better method, I'm happy to use it. But for now, this is what's in GCS.

**Comment by cohnt** [comment]
I no longer need this feature, so I'm fine with closing the PR.

**Comment by ggould-tri** [comment]
Closing per author's note above; reopen or duplicate the next time someone wants this feature.

**Pull request closed without merging**
