### PR TITLE
cpp_template: Add C++ interface.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This finishes out C++ template stuff for pybind.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7790)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review, please. (Last bit for the C++ <-> Python template stuff).
+@soonho-tri for platform review, please. (Full circle :) )

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-:-L36z8qdehQNVazIXT9e:b8cmkmr)*

**Comment by jadecastro** [comment]
Finished first pass.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3EBNEVPy4XBWjDeTSU:-L3EBNEVPy4XBWjDeTSV:b-xm7yie) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L22)):*
> ```objc
> 
> // See document
> inline py::object GetOrInitTemplate(
> ```

BTW, please document this function; in particular, what is `create_extra`?

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3Bl97erZTDgRKZjQfi:-L3Bl97erZTDgRKZjQfj:btkpqas) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L33)):*
> ```objc
> inline void AddInstantiation(
>     py::handle py_template, py::handle obj,
>     py::tuple param) {
> ```

BTW, odd linebreak here.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E4grJhE300Z-xK95A:-L3E4grKuaYzsrqUVHar:bw5aot8) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L69)):*
> ```objc
> /// will be passed to `AddTemplateClass`.
> template <typename T>
> std::string TemporaryClassName() {
> ```

At first read the details of this function were not clear to me. Consider hiding the details by returning a `py::class_<T>` object constructed internally with a default name or else add some comments explaining a recipe in `AddTemplateClass` explaining by example how to use `TemporaryClassName` to make a valid `py_class`.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E2hIwYW8ltc9wYAj9:-L3E2hIxjK6UAY5JaeBq:b-unin30) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
> ```objc
> /// @param scope Parent scope of the template. This should be a class.
> /// @param name Name of the template.
> /// @param func Function to be added.
> ```

BTW, perhaps change this to `method` to align better with the function name? 

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E3BmPlHU_XFnlx638:-L3E3BmPlHU_XFnlx639:b-2oaoc9) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
> ```objc
> /// @param scope Parent scope of the template. This should be a class.
> /// @param name Name of the template.
> /// @param func Function to be added.
> ```

Is there an easy way to fail fast if the `func` is not a method in the given class?

---

*[bindings/pydrake/util/test/cpp_template_pybind_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3DspX_nuEWAzmjqzV0:-L3DspX_nuEWAzmjqzV1:b-bprvq7) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/test/cpp_template_pybind_test.cc#L21)):*
> ```cpp
> 
> namespace drake {
> namespace pydrake {
> ```

BTW, unit tests should be placed inside an anonymous namespace.

---

*[bindings/pydrake/util/test/cpp_template_pybind_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3DzxTeyVtzW4FMfjv3:-L3DzxTeyVtzW4FMfjv4:b-fnfrwt) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/test/cpp_template_pybind_test.cc#L106)):*
> ```cpp
> 
> int main(int argc, char** argv) {
>   py::scoped_interpreter guard;
> ```

BTW, You might want to add a comment explaining why this guard is necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-:-L3EAd9u4ZMJi_r7SnpH:b-xhgvng)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3EsOwDqHlsgtIvzG3e:-L3EsOwE3fQBoUnaBhS5:bvxpe4z) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L55)):*
> ```objc
>     py::handle scope, const std::string& name,
>     py::handle py_class, py::tuple param,
>     const std::string& default_instantiation_name = "") {
> ```

Can we have a test where this parameter is not specified and check it is set to `py_class` as documented here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-:-L3ExBEmz86E615DBLY_:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E4grJhE300Z-xK95A:-L3EyY_GiYgz_IAXko0_:bubyb5y) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L69)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

At first read the details of this function were not clear to me. Consider hiding the details by returning a `py::class_<T>` object constructed internally with a default name or else add some comments explaining a recipe in `AddTemplateClass` explaining by example how to use `TemporaryClassName` to make a valid `py_class`.
</blockquote></details>

I'd prefer to not create a `py_class` instance, because it inherits from `py::class_`, which has a lot of template magic behind it.

I will update the recipe and mention `TemporaryClassName`.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E3BmPlHU_XFnlx638:-L3EyqE3Yf6P3C7MsQOF:ba9guo8) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Is there an easy way to fail fast if the `func` is not a method in the given class?
</blockquote></details>

Not that I'm aware of. I think there's little gain for a lot of work, at least for this API.

Ultimately, `py::cpp_function` and `py::def` have overloads for handling different method types (lambda / functor vs. function pointer vs. method pointer), so I'd prefer to avoid entangling this logic.

There may be some failures at compile time in `pybind`, and there may be failures at runtime when casting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E3BmPlHU_XFnlx638:-L3EzmkYV1uFrtN83YBv:brxp9sd) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Not that I'm aware of. I think there's little gain for a lot of work, at least for this API.

Ultimately, `py::cpp_function` and `py::def` have overloads for handling different method types (lambda / functor vs. function pointer vs. method pointer), so I'd prefer to avoid entangling this logic.

There may be some failures at compile time in `pybind`, and there may be failures at runtime when casting.
</blockquote></details>

Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3EBNEVPy4XBWjDeTSU:-L3FBPCJsqCClGpkKZZ8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L22)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, please document this function; in particular, what is `create_extra`?
</blockquote></details>

Done.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3Bl97erZTDgRKZjQfi:-L3FBQWkxqEpO0sXaeGE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L33)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, odd linebreak here.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3EsOwDqHlsgtIvzG3e:-L3FBRJkIAdzGfqBPIdb:bab0db8) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L55)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can we have a test where this parameter is not specified and check it is set to `py_class` as documented here?
</blockquote></details>

Done. Removed `default_instantiation_name`, as it complicates the API.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E2hIwYW8ltc9wYAj9:-L3FBaWw7A18RAbqcHwo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, perhaps change this to `method` to align better with the function name? 
</blockquote></details>

Done.

---

*[bindings/pydrake/util/cpp_template_pybind.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3E3BmPlHU_XFnlx638:-L3FBbg96CuVQIE33O9L:b-5fmw9g) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/cpp_template_pybind.h#L95)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

BTW Could you mark this as satisfied?

---

*[bindings/pydrake/util/test/cpp_template_pybind_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3DspX_nuEWAzmjqzV0:-L3FBdpCtFr2oxd348bp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/test/cpp_template_pybind_test.cc#L21)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, unit tests should be placed inside an anonymous namespace.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/test/cpp_template_pybind_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-L3DzxTeyVtzW4FMfjv3:-L3FBgxZ2NAFQDCEqNbh:bg394ki) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e306b74c81c4c8054374d521324f32e01c70a6/bindings/pydrake/util/test/cpp_template_pybind_test.cc#L106)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, You might want to add a comment explaining why this guard is necessary.
</blockquote></details>

Done.

(Wanted to make a `drake_pybind_googletest_main.cc`, but that made things annoyingly complicated...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7790#-:-L3FSQot2yLUlcid8RYG:bnfp4nl)*

**Pull request merged**
