### PR TITLE
[pydrake] Centralize pybind11 includes for ODR safety

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For convenience and easier ODR-safety, consolidate the common pybind11 includes (especially the includes that specialize trait structs) into our central `pydrake_pybind.h` header. This avoids hazards where some modules forget to include the proper headers and experience compile-time or runtime failures as a result.

Towards #19250.

Tested locally for possible performance regressions (see below).

---

Checking for performance regression of a full rebuild:

Build time on **master**:
* `git checkout master`
* `bazel build //bindings/...`
* patch `pybind11/package.BUILD.bazel` to force a bindings rebuild [1]
* `time bazel build //bindings/...`

Result:
```
INFO: Elapsed time: 170.486s, Critical Path: 135.65s
INFO: 99 processes: 1 internal, 98 linux-sandbox.
```

Build time on **pull request**:
* `git checkout pydrake-canonical-includes`
* `bazel build //bindings/...`
* patch `pybind11/package.BUILD.bazel` to force a bindings rebuild [1]
* `time bazel build //bindings/...`

Result:
```
INFO: Elapsed time: 151.502s, Critical Path: 150.37s
INFO: 99 processes: 1 internal, 98 linux-sandbox.
```

I believe the critical path changes are just the luck of when `multibody_tree_py.cc` starts compiling.

[1] the patch:
```patch
--- a/tools/workspace/pybind11/package.BUILD.bazel
+++ b/tools/workspace/pybind11/package.BUILD.bazel
@@ -43,6 +43,7 @@ cc_library(
         "include/pybind11/stl_bind.h",
     ],
     includes = ["include"],
+    defines = ["TRIGGER_REBUILD=YES_PLEASE_master"],
     deps = [
         "@eigen",
         "@python",
```

---

Checking performance of a single-file incremental rebuild:

Neither of these two targets show any performance slow-down of a rebuild with the extra included headers:

```
bazel build //bindings/pydrake/common:schema_py
bazel build //bindings/pydrake/common:eigen_geometry_py
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review of **bindings/pydrake/pydrake_pybind.h** only, please -(status: single reviewer ok), to check the clarity there with >1 person.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-:-NXlLEHtBcuvXVAJFuBL:bwedq0e)* status: LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXkkwgs76Uhtt6-H1SB:-NXlLT33DNxmrwMWSn72:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

> Can you clarify the criterion for what includes make the cut to `pydrake_pybind.h`? For example, I see that "pybind11/eval.h" is excluded and not sure why. Is it not common enough? Does that undermines ODR-safety goal that we are trying to achieve here?
</blockquote></details>

Done.

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: with some follow-up questions

> Reviewed 98 of 100 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-:-NXljq4b4YaKxljxXBaJ:b8y4oeb)* status: 1 unresolved discussion

___
*[`bindings/pydrake/pydrake_pybind.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXlj3IH9K1WiXOzCo8b:-NXlj3IH9K1WiXOzCo8c:b-98unwx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef58f8ff36f1302a6203d27cc9ae002d04d96f80/bindings/pydrake/pydrake_pybind.h#L5)):*
> ```objc
> #include <utility>
> 
> // Here we include a lot of the pybind11 API, to ensure that all code in pydrake
> ```

btw I'm satisfied that this patch does the things the comment describes:
* includes `type_caster` headers
* includes ADL headers
* does not include headers we don't need (yet?)
* does not include headers that not involved in specializations

It looks then to me like I should verify that this header is seen by every pydrake C++ translation unit.

Are there any correctness invariants that I've missed?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)* status: 1 unresolved discussion

___
*[`bindings/pydrake/pydrake_pybind.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXlj3IH9K1WiXOzCo8b:-NXlvJuI21dADpK3weCV:b-pntj8y) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef58f8ff36f1302a6203d27cc9ae002d04d96f80/bindings/pydrake/pydrake_pybind.h#L5)):*
> Are there any correctness invariants that I've missed?

Those seem like the right ones to me.

> It looks then to me like I should verify that this header is seen by every pydrake C++ translation unit.

Every TU that includes `pybind11` stuff, yes.  If there is any C++ code in pydrake that doesn't use pybind11 at all, it would be safe without including this.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)* status: 1 unresolved discussion

___
*[`bindings/pydrake/pydrake_pybind.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXlj3IH9K1WiXOzCo8b:-NXpKkhXEeCX54LbTVdu:b-j942mz) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef58f8ff36f1302a6203d27cc9ae002d04d96f80/bindings/pydrake/pydrake_pybind.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Are there any correctness invariants that I've missed?

Those seem like the right ones to me.

> It looks then to me like I should verify that this header is seen by every pydrake C++ translation unit.

Every TU that includes `pybind11` stuff, yes.  If there is any C++ code in pydrake that doesn't use pybind11 at all, it would be safe without including this.
</blockquote></details>

There is one TU that might be on the bubble, and maybe has escaped attention so far: bindings/bazel_workaround_4594_libdrake_py.cc

Clearly it's an outlier and maybe doesn't need this header reform. I'm not quite far enough in the headspace to make a judgment. WDYT?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)* status: 1 unresolved discussion

___
*[`bindings/pydrake/pydrake_pybind.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXlj3IH9K1WiXOzCo8b:-NXpLyhk8p9LcJLpuNAi:b-967jr6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef58f8ff36f1302a6203d27cc9ae002d04d96f80/bindings/pydrake/pydrake_pybind.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since it doesn't define any types (only a module doc), I think it poses no risk.

My guess is that trying to capture that in a comment somewhere would cause more confusion that help.  WDYT?
</blockquote></details>

It's on the bubble -- a pretty trivial module. I was thinking to just use the drake_pybind header for consistency across the board, and not comment on it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19571)* status: 1 unresolved discussion

___
*[`bindings/pydrake/pydrake_pybind.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19571#-NXlj3IH9K1WiXOzCo8b:-NXpMVGABpHM0ZyfPTjH:b-5t6t5u) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef58f8ff36f1302a6203d27cc9ae002d04d96f80/bindings/pydrake/pydrake_pybind.h#L5)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

It's on the bubble -- a pretty trivial module. I was thinking to just use the drake_pybind header for consistency across the board, and not comment on it.
</blockquote></details>

Given that the point of that module is to _not_ be infected with pydrake (see `bindings/BUILD.bazel` docs), I am skeptical about using a pydrake header there.  The compiler might allow it, but I still come down on more-confusing-than-helpful for that change as well.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-release please.

**Pull request merged**
