### PR TITLE
Add symbolic formula representing positive-semidefinite constraint

### LINKED ISSUE #5645: Add a special formula for positive semidefinite
This formula takes an Eigen::Matrix<symbolic::Expression>. We should be able to write
```C++
Eigen::Matrix<symbolic::Expression, Eigen::Dynamic, Eigen::Dynamic> X(n, n);
Eigen::Matrix<symbolic::Expression, Eigen::Dynamic, Eigen::Dynamic> Y(n, n);
auto formula = (X >= Y);  // Returns a symbolic::Formula that (X - Y) is positive semidefinite.
auto formula = (X >= 0);  // Retuns a symbolic::Formula that X is positive semidefinite.
```
This should also work for static-sized matrix. We should possibly check if the matrix is square in the release mode, and if it is symmetric in the debug mode, if the checking is expensive.

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #5645.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5717)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kgu--Heh2mnSqB7rw6j:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kgu2xN85c4sw3gbMEIw:-Kgu2xN85c4sw3gbMEIx:b-t0wor9) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula.h#L228)):*
> ```objc
> /** Returns a symbolic formula constraining @p m to be a positive-semidefinite
>  * matrix. By definition, @p m, a n x n matrix, is positive-semidefinte if xᵀ m
>  * x ≥ 0 for all vector x ∈ ℝⁿ.
> ```

Usually we also require that `m` is a symmetric matrix.

Here we can say that only the lower (or upper) triangular part of `m` is used, to determine if it is positive definite. Namely if we decide to use lower triangular part, for a matrix 
```
m = [1 1]
    [0 1]
```
we will not care the value of `m(0, 1)`, instead we will infer `m(0, 1) = m(1, 0)`, and check if the matrix 
```
[1 0]
[0 1]
```
 is positive semidefinite.

---

*[drake/common/symbolic_formula.h, line 300 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kgu5CfSduJRIHpvQe_z:-Kgu5CfT516pAxSFatgi:b-sncyo0) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula.h#L300)):*
> ```objc
> 
> /** Returns the matrix in a positive-semidefinite formula @p f.
>  *  \pre{@p f is a positive-semidefinite formula.}
> ```

Will it throw a std::runtime_error, if it is not a positive-semidefinite formula?

---

*[drake/common/symbolic_formula_cell.cc, line 462 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguAK9kaz1k-J_ozxKV:-KguAK9kaz1k-J_ozxKW:bmg78ao) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.cc#L462)):*
> ```cpp
>     : FormulaCell{FormulaKind::PositiveSemidefinite,
>                   // Computes hash of m by traversing its elements.
>                   hash_range(m.data(), m.data() + m.rows() * m.cols())},
> ```

If we decide to use just the lower (or upper) triangular part, then we should only traverse the lower (or upper) triangular elements.

---

*[drake/common/symbolic_formula_cell.cc, line 465 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguAUim6yQkXQXNPx5y:-KguAUinM5xfUQDIBW2j:bautyf5) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.cc#L465)):*
> ```cpp
>       m_{m} {
>   // m should be a square matrix.
>   DRAKE_DEMAND(m.rows() == m.cols());
> ```

Probably throw a std::runtime_error here, so that the error message is more meaningful to the user?

---

*[drake/common/symbolic_formula_cell.h, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguDby1kCg02L0kLewt:-KguDby2N-E5CDmd0o9s:b-msm4gq) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.h#L329)):*
> ```objc
>    * Note that in the code above, `psd1.Less(psd2)` holds because we have
>    *  - m1 in column-major ordering : (x + y)  -3.14   1.0   y_
>    *  - m2 in column-major ordering : (x + y)   3.14   1.0  -y_.
> ```

`m2` has -1.0, y?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/test/symbolic_formula_test.cc, line 908 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguHSSRHHzibZ1Sk044:-KguHSSRHHzibZ1Sk045:bk9zfb4) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/test/symbolic_formula_test.cc#L908)):*
> ```cpp
> 
> TEST_F(SymbolicFormulaTest, GetMatrixInPSD) {
>   EXPECT_TRUE(CheckStructuralEquality(
> ```

Does this also check the storage order? If not, could you also add a check, that the psd matrix is in column order? Like
```
EXPECT_EQ(decltype(get_matrix_in_positive_semidefinite(f_psd_static_2x2))::Options, Eigen::ColMajor)?
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by soonho-tri** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kgu2xN85c4sw3gbMEIw:-KgzbX8sMH4bD5Ga_an3:b5cfcqj) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula.h#L228)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Usually we also require that `m` is a symmetric matrix.

Here we can say that only the lower (or upper) triangular part of `m` is used, to determine if it is positive definite. Namely if we decide to use lower triangular part, for a matrix 
```
m = [1 1]
    [0 1]
```
we will not care the value of `m(0, 1)`, instead we will infer `m(0, 1) = m(1, 0)`, and check if the matrix 
```
[1 0]
[0 1]
```
 is positive semidefinite.
</blockquote></details>

Done.

```c++
// The following two are identical. m doesn't have to be symmetric 
// since only its lower-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Lower>());
positive_semidefinite_from_triangular(m, false);

// The following two are identical. m doesn't have to be symmetric 
// since only its upper-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Upper>());
positive_semidefinite_from_triangular(m, true);

// Here, `m` has to be symmetric. We do call `math::IsSymmetric` to check.
positive_semidefinite(m);
```

---

*[drake/common/symbolic_formula.h, line 300 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kgu5CfSduJRIHpvQe_z:-KguHVl62oJpf7nkS5DN:b-6kc33b) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula.h#L300)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Will it throw a std::runtime_error, if it is not a positive-semidefinite formula?
</blockquote></details>

As indicated by `pre` doxygen tag, a user of this function should make sure that `is_positive_semidefinite(f)` is `true`.

This function calls a conversion function`to_positive_semidefinite` which is using `static_pointer_cast` (shared-pointer version of `static_cast`).

If `is_positive_semidefinite(f)` doesn't hold, we have *unspecified behavior* from `static_pointer_cast`.

---

*[drake/common/symbolic_formula_cell.cc, line 462 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguAK9kaz1k-J_ozxKV:-Kgzc9abqXgYmR1pDlWq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.cc#L462)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If we decide to use just the lower (or upper) triangular part, then we should only traverse the lower (or upper) triangular elements.
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula_cell.cc, line 465 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguAUim6yQkXQXNPx5y:-KgzcApmTsAD3idji3nA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.cc#L465)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Probably throw a std::runtime_error here, so that the error message is more meaningful to the user?
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula_cell.h, line 329 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguDby1kCg02L0kLewt:-KguUI3c1ouPBi7jRDDC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula_cell.h#L329)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`m2` has -1.0, y?
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_formula_test.cc, line 908 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-KguHSSRHHzibZ1Sk044:-KguZ6bXaSayvBzzodok:b-oz01gb) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/test/symbolic_formula_test.cc#L908)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Does this also check the storage order? If not, could you also add a check, that the psd matrix is in column order? Like
```
EXPECT_EQ(decltype(get_matrix_in_positive_semidefinite(f_psd_static_2x2))::Options, Eigen::ColMajor)?
```
</blockquote></details>

Done. (see above, we're using `.IsRowMajor`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by soonho-tri** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kgu2xN85c4sw3gbMEIw:-KgzcYB5uS29dO-lUV1B:b1xb9eh) ([raw file](https://github.com/robotlocomotion/drake/blob/2a15f7fdd3c8e0fde841a634625c4d32eb6e9990/drake/common/symbolic_formula.h#L228)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.

```c++
// The following two are identical. m doesn't have to be symmetric 
// since only its lower-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Lower>());
positive_semidefinite_from_triangular(m, false);

// The following two are identical. m doesn't have to be symmetric 
// since only its upper-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Upper>());
positive_semidefinite_from_triangular(m, true);

// Here, `m` has to be symmetric. We do call `math::IsSymmetric` to check.
positive_semidefinite(m);
```
</blockquote></details>

My mistake, there are typos. Please ignore the above code, but consider the following:

```c++
// The following two are identical. m doesn't have to be symmetric 
// since only its lower-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Lower>());
positive_semidefinite_from_triangular(m, true /* is_lower */);

// The following two are identical. m doesn't have to be symmetric 
// since only its upper-triangular part is considered. 
positive_semidefinite(m.triangularView<Eigen::Upper>());
positive_semidefinite_from_triangular(m, false /* is_lower */);

// Here, `m` has to be symmetric. We do call `math::IsSymmetric` to check.
positive_semidefinite(m);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ggould-tri for platform review please.

---

Reviewed 6 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 259 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh-HYKiGzih2uzGBfxD:-Kh-HYKiGzih2uzGBfxE:b-ifaab8) ([raw file](https://github.com/robotlocomotion/drake/blob/2d060947dbf7c43de61d86415a6cffc8f509d58d/drake/common/symbolic_formula.h#L259)):*
> ```objc
>  * @endcode
>  */
> Formula positive_semidefinite_from_triangular(const MatrixX<Expression>& m,
> ```

Maybe instead of using `bool is_lower`, it is cleaner to use `unsigned int mode`? So when the user writes the code, it will look like
```C++
positive_semidefinite_from_triangular(m, Eigen::Lower);
```
instead of 
```C++
positive_semidefinite_from_triangular(m, true);
```
I feel the `Eigen::Lower` is more informative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kh-InOekTG6jW1M5557:b-9ir12m)*

**Comment by soonho-tri** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 259 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh-HYKiGzih2uzGBfxD:-Kh-Sd-6n52hPlOt_uZp:bt4ox15) ([raw file](https://github.com/robotlocomotion/drake/blob/2d060947dbf7c43de61d86415a6cffc8f509d58d/drake/common/symbolic_formula.h#L259)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe instead of using `bool is_lower`, it is cleaner to use `unsigned int mode`? So when the user writes the code, it will look like
```C++
positive_semidefinite_from_triangular(m, Eigen::Lower);
```
instead of 
```C++
positive_semidefinite_from_triangular(m, true);
```
I feel the `Eigen::Lower` is more informative.
</blockquote></details>

Done. Thanks for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r4.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717)*

**Comment by ggould-tri** [comment]
Sorry I was slow on this -- I was out sick yesterday.

Consider +(status: curate commits before merging) (or remove that tag if you are happy with your commit history -- it's not obvious to me if it is how you want it and I have not tested each intermediate rev).

Minor nits, none critical.  :lgtm: pending those.

---

Reviewed 1 of 7 files at r1, 3 of 6 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.cc, line 476 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eGmheoHfHuz6uGjb:-Kh7eGmheoHfHuz6uGjc:bc5buzt) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L476)):*
> ```cpp
> 
> namespace {
> // Helper Eigen-visitor class that we use to implement
> ```

Sigh.  I had all sorts of comments on how this interface was awful, then discovered that it's the required eigen visitor concept.  Bleh.

---

*[drake/common/symbolic_formula_cell.cc, line 480 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eCwn1IPWr-CzwsWh:-Kh7eCwn1IPWr-CzwsWi:b-mmsq51) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L480)):*
> ```cpp
> struct VariablesCollector {
>   Variables vars_;
>   // called for the first coefficient
> ```

FYI -- Capitalize and punctuate

---

*[drake/common/symbolic_formula_cell.cc, line 481 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eRaIDKgiytGIOXfL:-Kh7df1FsskPatlRW4vw:bz5pa1o) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L481)):*
> ```cpp
>   Variables vars_;
>   // called for the first coefficient
>   void init(const Expression& e, const Eigen::Index i, const Eigen::Index j) {
> ```

BTW -- consider asserting that vars_ is empty.

---

*[drake/common/symbolic_formula_cell.cc, line 484 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eFy-YsV1EbNRI3Lu:-Kh7eFy-YsV1EbNRI3Lv:b-mmsq51) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L484)):*
> ```cpp
>     return operator()(e, i, j);
>   }
>   // called for all other coefficients
> ```

FYI -- Capitalize and punctuate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kh7bmVbaniKmalOkA2b:bb4pux9)*

**Comment by soonho-tri** [comment]
Oops I think I made a git mistake. I'll fix it soon.

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.cc, line 480 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eCwn1IPWr-CzwsWh:-Kh7hasBgJHjkgwjetnU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L480)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Capitalize and punctuate
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula_cell.cc, line 481 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eRaIDKgiytGIOXfL:-Kh7hbmhkdAZ_ovaUQkg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L481)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- consider asserting that vars_ is empty.
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula_cell.cc, line 484 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-Kh7eFy-YsV1EbNRI3Lu:-Kh7hbZC73mTC_yr8h7b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057ea1e2d2e381eff8fb59117943853f8e5ee956/drake/common/symbolic_formula_cell.cc#L484)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Capitalize and punctuate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kh7k-VaO7EViE14IxdP:b-w7bzwh)*

**Comment by soonho-tri** [comment]
@ggould-tri , thanks a lot for reviewing the PR. I hope you feel better.

> Consider +(status: curate commits before merging) (or remove that tag if you are happy with your commit history -- it's not obvious to me if it is how you want it and I have not tested each intermediate rev).

The current commit history is actually what I intended. I've just checked that each intermediate rev is compilable and passes all the tests.

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kh7ljoSDbf6c7coQhJH:bma066g)*

**Comment by ggould-tri** [comment]
Excellent.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5717#-:-Kh7oBQUg3sOYjwpeSA5:b-ec019f)*

**Pull request merged**
