### PR TITLE
Constraint dim check

### PR DESCRIPTION
**Pull request by hongkai-dai**
Add `num_vars` to `Constraint` class. Check if `Constraint::num_vars` matches with the dimension of the bound variable, when constructing a `Binding` object.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4770)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@david-german-tri for feature review, +@jwnimmer-tri for platform review.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KaJDVOi6DjtjpfOkhYy:by8dev6)*

**Comment by jwnimmer-tri** [comment]
Please re-add me (or whoever) for platform review once feature review is entirely completed.
-@jwnimmer-tri 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KaJHBdEHzUCialV8Bzo:bmqj3ny)*

**Comment by david-german-tri** [comment]
Thanks for doing this!

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/inverse_kinematics_trajectory_backend.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNSvtY6CkAnpRs_jFV:-KaNSvtZjRvB1hb-IkAO:brsht) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/multibody/inverse_kinematics_trajectory_backend.cc#L87)):*
> ```cpp
>                         const RigidBodyConstraint* const* constraint_array)
>       : Constraint(0, helper.nq() * (helper.nT() +
>                                      helper.num_qdotfree())),  // Update bounds
> ```

BTW I'm not sure this comment is helpful.  Up to you.

---

*[drake/solvers/constraint.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNR_b9OvztmYZxw_u_:-KaNR_b9OvztmYZxw_ua:bx36gik) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/solvers/constraint.h#L151)):*
> ```objc
> 
>  protected:
>   virtual void Eval_impl(const Eigen::Ref<const Eigen::VectorXd>& x,
> ```

https://google.github.io/styleguide/cppguide.html#Function_Names (x2)

In `drake/systems` we've been using the convention `DoEval` for NVI implementations like this.

---

*[drake/solvers/constraint.h, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNRvrGZZ1OHJG5QFkW:-KaNRvrHeBrAjQtmmN-v:b-7jm4pl) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/solvers/constraint.h#L152)):*
> ```objc
>  protected:
>   virtual void Eval_impl(const Eigen::Ref<const Eigen::VectorXd>& x,
>                          // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> ```

Why not just make it correct now (pass a pointer)? (x2)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KaNT5UpE-5V3gqrLJUB:bxgavm9)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/inverse_kinematics_trajectory_backend.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNSvtY6CkAnpRs_jFV:-KaOyYaQUSL0XBZbwkUo:bq4d9xn) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/multibody/inverse_kinematics_trajectory_backend.cc#L87)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW I'm not sure this comment is helpful.  Up to you.
</blockquote></details>

I still find this documentation useful

---

*[drake/solvers/constraint.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNR_b9OvztmYZxw_u_:-KaOyWJpdBRQOYtfS_Bc:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/solvers/constraint.h#L151)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Function_Names (x2)

In `drake/systems` we've been using the convention `DoEval` for NVI implementations like this.
</blockquote></details>

Done. Thanks!

---

*[drake/solvers/constraint.h, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-KaNRvrGZZ1OHJG5QFkW:-KaOpAzF3NMVwSSykIeS:batmqv2) ([raw file](https://github.com/robotlocomotion/drake/blob/f9361553733564d8ce390263a6db30289f76999b/drake/solvers/constraint.h#L152)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Why not just make it correct now (pass a pointer)? (x2)
</blockquote></details>

I do have a branch working on this, but using `Eigen::Ref<Eigen::VectorXd>` for a writable Eigen object. I do not think using pointer `Eigen::VectorXd*` is the best solution here, since it does not accept other Eigen types, such as Eigen block expression, static-sized Eigen vector, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KaP-7Cf9zLEgyNZ6jcA:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KaP-TXy0WP22ZHWwJmr:b-8qo47q)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770#-:-KabvMI7-X4Q3dWYkPin:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4770)*

**Pull request merged**
