### PR TITLE
add dynamics to system inspector + accessor APIs + HasAffineDynamics and IsTimeInvariant

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6900)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sherm1 for feature review.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-:-KsHsXpMeju9pcrn4A48:btfsfbp)*

**Comment by sherm1** [comment]
It's very cool that we can do this! Feature :lgtm: with an assortment of doc BTWs.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJntAQ-dfcErdthrPE:-KsJntAQ-dfcErdthrPF:b-3uiybw) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L15)):*
> ```objc
> 
> /// The SymbolicSystemInspector reports the connectivity between fields in a
> /// System's Context, and outputs computed by that System.
> ```

BTW this comment could use an upgrade now.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJoN5fJHoa4pyd8ijG:-KsJoN5fJHoa4pyd8ijH:bopbt3k) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L61)):*
> ```objc
>   /// Returns true iff all of the derivatives and discrete updates have at
>   /// most an affine dependence on state and input.
>   bool HasAffineDynamics() const;
> ```

BTW consider mentioning explicitly that this does not consider the affine-ness of the outputs.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJoejiuOPXe5TH_bKJ:-KsJoejiuOPXe5TH_bKK:bxr4axz) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L63)):*
> ```objc
>   bool HasAffineDynamics() const;
> 
>   /// @{
> ```

BTW this needs to be preceded by an `@name Title` and group comment to introduce the group.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJpZP4aQTnhlIuj3YQ:-KsJpZP4aQTnhlIuj3YR:bnk9m1a) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L92)):*
> ```objc
> 
>   /// Returns a reference to the symbolic representation of the continuous-time
>   /// dynamics.
> ```

BTW actually a copy rather than a reference; not sure it matters.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJq3-IX32apA3izW6B:-KsJq3-J012_RRfs0-gS:b3k8doz) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L135)):*
> ```objc
>   std::vector<VectorX<symbolic::Variable>> input_variables_;
>   VectorX<symbolic::Variable> continuous_state_variables_;
>   std::vector<VectorX<symbolic::Variable>> discrete_state_variables_;
> ```

BTW there are also parameters and abstract state variables; would be good to mention that these are intentionally left out rather than overlooked.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJqIX33OLjAmrxL_ng:-KsJqIX33OLjAmrxL_nh:bq8w2xz) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L140)):*
> ```objc
>   std::vector<PortDataType> output_port_types_;
> 
>   // True if the `context_` contains any abstract elements.
> ```

BTW Does this include abstract parameters? Abstract states and output ports can cause trouble for the inspections you have implemented, but I think abstract parameters can be safely ignored? They are likely rare though so it may not be worth explicitly excluding them.

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJtswinCwx6f4YXMnv:-KsJtswinCwx6f4YXMnw:bodcx6k) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L65)):*
> ```cpp
>   void CalcNothing(const Context<symbolic::Expression>& context, int*) const {}
> 
>   void DoCalcTimeDerivatives(
> ```

BTW would be helpful to have a short comment saying that this is intended to be time dependent and affine (or whatever).

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJu7tEYIf9ItB0j8GM:-KsJu7tEYIf9ItB0j8GN:bmjzxzm) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L112)):*
> ```cpp
> 
>   SparseSystem system_;
>   std::unique_ptr<SymbolicSystemInspector> matrix_;
> ```

BTW "matrix_" isn't a good name any more. "inspector_"?

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJuKDeR0TuS0OX-_Ir:-KsJuKDeR0TuS0OX-_Is:bx6zqy0) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L131)):*
> ```cpp
> // Tests that, if the System has an abstract input, the SymbolicSystemInspector
> // conservatively reports that every output might depend on every input.
> TEST_F(SymbolicSystemInspectorTest, AbstractContextThrwartsSparsity) {
> ```

BTW AbstractContextThwartsInspection? (Also a typo here)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-:-KsJw-w7ubQXOc2rcxQK:bdv01cm)*

**Comment by RussTedrake** [comment]
Review status: 4 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJntAQ-dfcErdthrPE:-KsK-4Xkl32gjg5IDYyD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this comment could use an upgrade now.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJoN5fJHoa4pyd8ijG:-KsK-OI87U70OhtxPf9W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider mentioning explicitly that this does not consider the affine-ness of the outputs.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJoejiuOPXe5TH_bKJ:-KsK0JabMQvyhOj5c3Bw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this needs to be preceded by an `@name Title` and group comment to introduce the group.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJpZP4aQTnhlIuj3YQ:-KsK0QlzgijobdonrZ7J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW actually a copy rather than a reference; not sure it matters.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJq3-IX32apA3izW6B:-KsK0StlHq8H6tha72ht:b94yks6) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW there are also parameters and abstract state variables; would be good to mention that these are intentionally left out rather than overlooked.
</blockquote></details>

there is an existing TODO in the constructor (left by David German).  the prerequisite has now been fulfilled, so I will implement it soon.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJqIX33OLjAmrxL_ng:-KsK0b2K59_n7dBEBX2o:b-6xtj7h) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/symbolic_system_inspector.h#L140)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Does this include abstract parameters? Abstract states and output ports can cause trouble for the inspections you have implemented, but I think abstract parameters can be safely ignored? They are likely rare though so it may not be worth explicitly excluding them.
</blockquote></details>

No.  Haven't handled the parameters at all yet.  Will evaluate that case carefully when I get to it.  (this context_is_abstract_ method was written by David)

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJtswinCwx6f4YXMnv:-KsK1-wh4QEymEN4-RDr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L65)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would be helpful to have a short comment saying that this is intended to be time dependent and affine (or whatever).
</blockquote></details>

Done.

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJu7tEYIf9ItB0j8GM:-KsK17hoKKoiY8hFY4Il:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L112)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "matrix_" isn't a good name any more. "inspector_"?
</blockquote></details>

Done.

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsJuKDeR0TuS0OX-_Ir:-KsK1H4s9d08N71bijfi:b-exgemo) ([raw file](https://github.com/robotlocomotion/drake/blob/1a93a4cd3bbdb0e4e8059053de080e73799eccba/drake/systems/framework/test/symbolic_system_inspector_test.cc#L131)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW AbstractContextThwartsInspection? (Also a typo here)
</blockquote></details>

Fixed the typo.  Blame david for the test name.   ;-)  I find it colorful but sufficiently descriptive. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review (and symbolic features, of course!  it's not a coincidence that I tried to get this done today. ;)

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-:-KsK2vZr4OtwdGnv2sSt:bp7uv4y)*

**Comment by soonho-tri** [comment]
:lgtm: (a few minor comments) Nice work!

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/symbolic_system_inspector.cc, line 178 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKLDt0k5y9OYJMKfmE:-KsKLDt1teSUqLIgVyyo:b-1lty21) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.cc#L178)):*
> ```cpp
>   for (int i = 0; i < expressions.size(); ++i) {
>     const Expression& e{expressions(i)};
>     const auto& vars = e.GetVariables();
> ```

FYI, you can rewrite this into:
```c++
    if (e.GetVariables().include(t)) {
      return false;
    }
```

---

*[drake/systems/framework/symbolic_system_inspector.h, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKMJW0KPTLtYtO-YBF:-KsKMJW0KPTLtYtO-YBG:b-2zo9c) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L78)):*
> ```objc
> 
>   /// Returns a copy of the symbolic representation of the continuous state.
>   const Eigen::VectorBlock<const VectorX<symbolic::Variable>> continuous_state()
> ```

BTW,
`'const' Eigen::VectorBlock<const VectorX<symbolic::Variable>>` -> `Eigen::VectorBlock<const VectorX<symbolic::Variable>>`

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKMz-Hjx-fo2azcl7t:-KsKMz-Hjx-fo2azcl7u:bclklit) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/test/symbolic_system_inspector_test.cc#L69)):*
> ```cpp
>       const Context<symbolic::Expression>& context,
>       ContinuousState<symbolic::Expression>* derivatives) const override {
>     const auto& u0 = this->EvalVectorInput(context, 0)->CopyToVector();
> ```

BTW, for `u0` and `u1`, I think it's clearer to use `const auto` instead of `const auto&` as their type because `CopyToVector()` does not return a reference.
Ditto in `DoCalcDiscreteVariableUpdates` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-:-KsKNUwH3l4fxQ2dERtm:b-ncddwd)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKU9qTKo71sNJb702Y:-KsKU9qTKo71sNJb702Z:b-zdg51b) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L14)):*
> ```objc
> namespace systems {
> 
> /// The SymbolicSystemInspector using symbolic::Expressions to analyze various
> ```

BTW using->uses

---

*[drake/systems/framework/symbolic_system_inspector.h, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUJy7U_r-P3Txs879:-KsKUJy7U_r-P3Txs87A:b-fjj670) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L63)):*
> ```objc
>   /// @name Reference symbolic components
>   /// A set of accessor methods that provide direct access to the symbolic
>   /// forms of the %System%.  This class carefully sets up and names all
> ```

BTW just `%System` to suppress doxygen highlighting, no trailing `%`.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUg65ploqVigejUOx:-KsKUg65ploqVigejUOy:b-7y13ls) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L77)):*
> ```objc
>   }
> 
>   /// Returns a copy of the symbolic representation of the continuous state.
> ```

BTW this one is not actually a copy since VectorBlock is a reference to an existing VectorX.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUuEqy9JTBLT860wC:-KsKUuEqy9JTBLT860wD:b5vw58e) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L95)):*
> ```objc
>   /// Returns a reference to the symbolic representation of the continuous-time
>   /// dynamics.
>   VectorX<symbolic::Expression> derivatives() const {
> ```

BTW this is the one I was referring to in the earlier comment; it does make a copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900)*

**Comment by RussTedrake** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/symbolic_system_inspector.cc, line 178 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKLDt0k5y9OYJMKfmE:-KsKUuOT7y0TNp92Ofr4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.cc#L178)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, you can rewrite this into:
```c++
    if (e.GetVariables().include(t)) {
      return false;
    }
```
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKU9qTKo71sNJb702Y:-KsKhqDMioa_oXtsgbEk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW using->uses
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUJy7U_r-P3Txs879:-KsKhwmg7osFrKp7Lw7r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just `%System` to suppress doxygen highlighting, no trailing `%`.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUg65ploqVigejUOx:-KsKhzg5O8TJGsvDtNc5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L77)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this one is not actually a copy since VectorBlock is a reference to an existing VectorX.
</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKMJW0KPTLtYtO-YBF:-KsKV0gEvja3BhqglAE0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L78)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW,
`'const' Eigen::VectorBlock<const VectorX<symbolic::Variable>>` -> `Eigen::VectorBlock<const VectorX<symbolic::Variable>>`

</blockquote></details>

Done.

---

*[drake/systems/framework/symbolic_system_inspector.h, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKUuEqy9JTBLT860wC:-KsKVvZKtj8DrRlXtG1I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/symbolic_system_inspector.h#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is the one I was referring to in the earlier comment; it does make a copy.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/symbolic_system_inspector_test.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6900#-KsKMz-Hjx-fo2azcl7t:-KsKVLId1djkZ8HoPTFk:bxyui9b) ([raw file](https://github.com/robotlocomotion/drake/blob/fde32650902be22e7147934304e426fc56b034d0/drake/systems/framework/test/symbolic_system_inspector_test.cc#L69)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, for `u0` and `u1`, I think it's clearer to use `const auto` instead of `const auto&` as their type because `CopyToVector()` does not return a reference.
Ditto in `DoCalcDiscreteVariableUpdates` below.
</blockquote></details>

done.  good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6900)*

**Pull request merged**
