### PR TITLE
Updating NLopt

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Mainly due to this: https://github.com/stevengj/nlopt/pull/128

Our failure: https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=141209

[Before](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-clang-experimental-memcheck-ubsan-release-11&field2=buildstarttime&compare2=84&value2=now)

[After](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-clang-experimental-memcheck-ubsan-release-12&field2=buildstarttime&compare2=84&value2=now)

Test in question: `nonlinear_program_test`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6584)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6584#-:-KpHLzvvbpCTMulKEaAC:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@jwnimmer-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
I suppose replacing undefined behavior with non-deterministic-but-defined behavior is an improvement...

:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6584#-:-KpHMfYJkStLPgaHF6A3:b-90tymv)*

**Pull request merged**
