### PR TITLE
Round up deprecation dates to first of the month

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Obeying the intermediate dates is not an efficient use of our time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11533)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews, please.

**Comment by SeanCurtis-TRI** [comment]
Would it not also make sense to change the definition as well? Instead of "09-01-2019", why not just "09-2019" and then have the message automatically insert the first day?

**Comment by jwnimmer-tri** [comment]
Having the full ISO 8601 date spelled out is better for anyone reading the source file directly (vs the Doxygen or GCC messages).

**Comment by SeanCurtis-TRI** [comment]
Good point. Lint it?

**Comment by jwnimmer-tri** [comment]
I think the cost of maintaining a linter is more than the cost of the occasional fixup like this.

**Comment by jwnimmer-tri** [comment]
I'm not going to wait for `-debug` on this.  Forcing in now.

**Pull request merged**
