### PR TITLE
[geometry] Fix installation paths for meshcat

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15732)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.
+@SeanCurtis-TRI for platform review, please.

I ran `drake/geometry/meshcat_manual_test` locally, and also plopped some test code in [drake_bazel_installed](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_bazel_installed) and it seemed to run fine.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15732#-:-Mj0Ixcr61Qp11Wmy2-_:bmxilld)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jwnimmer-tri** [comment]
In good news, it looks like that pushed a nice binary that Russ could test:

```
s3://drake-packages/drake/experimental/drake-20210907181122-9983cb4960f592c3b0ca0d53adf6d407f3433f6b-focal.tar.gz
```

---

In bad news, it looks like PR builds overwrite the nightly docker tags?

```
[2021-09-07T18:14:22.539Z] Successfully tagged robotlocomotion/drake:focal-20210907
```

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  i've tested it manually (not using your binaries) in both the jupyter workflow and the bazel installed workflow and it all appears to work.  Thanks!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15732#-:-Mj0dWdM1HjX1DZDfufv:by8loms)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/workspace/meshcat/package.BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15732#-Mj0cgXb6tcj6T48tUs9:-Mj0cgXb6tcj6T48tUsA:b-vkmv1i) ([raw file](https://github.com/robotlocomotion/drake/blob/4be60cda40ef4c63e97039c6e1a3b9e0010c60aa/tools/workspace/meshcat/package.BUILD.bazel#L9)):*
> ```
> # TODO(jwnimmer-tri) The main.min.js embeds Three.js and possible other third-
> # party dependencies as well.  We probably need to install the transitive
> # licences for those dependencies, since we are are derivative work.
> ```

nit: typo licenses.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15732)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> In bad news, it looks like PR builds overwrite the nightly docker tags?
> [2021-09-07T18:14:22.539Z] Successfully tagged robotlocomotion/drake:focal-20210907

Withdrawn (false alarm).  I misread this particular output (and I've made that same mistake several times previously).  We _do_ add the date-based tag, but in "experimental" builds we do not _push_ that tag anywhere.  Note the 'sudo docker push' in the nightly build's console output, but not in the experimental build's console output.

**Pull request merged**
