### PR TITLE
updated iris to ignore a build artifact 

### PR DESCRIPTION
**Pull request by RussTedrake**
that was causing drake's new git submodule logic to complain about iris being dirty all of the time

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2770)

### CODE REVIEW

**Comment by sherm1** [comment]
@russtedrake, are you saying you modified iris and then this PR updates Drake's iris submodule to use the modified version? I don't understand git submodules -- can we get a feature review from @mwoehlke-kitware?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2770#-:-KMPVfi0aNUKNa7bkuc5:-646784754)*

**Comment by RussTedrake** [comment]
correct.

**Comment by mwoehlke-kitware** [comment]
> @russtedrake, are you saying you modified iris and then this PR updates Drake's iris submodule to use the modified version?

Correct. In "the old days" this would correspond to an edit of the root `CMakeLists.txt` to change the SHA to be checked out. Now, the SHA is tracked "specially" by git instead, though the github diff looks similar; you still see the old SHA as a deletion and the new SHA as an addition.

I'm not going to claim knowledge to do any sort of review of iris itself. The mechanics of bumping iris to a newer version look fine to me, though.

Here's what changes to iris this will introduce: https://github.com/rdeits/iris-distro/compare/1533f20cff57504a46773f01e1730f11931d0ea6...a859e65b065638499713177e2a90f27aea5716ef. (Most of this is artifacts of master having moved on since the old SHA; the most recent commit is the "important" one for purposes of this PR.)

**Comment by liangfok** [comment]
Once this PR lands, will a simple `git pull upstream master` work or will need to execute two commands:

```
git pull upstream master
git submodule update --recursive
```

?

I'm also trying to understand the intricacies of using git submodules.

**Comment by jwnimmer-tri** [comment]
> git submodule update --recursive

This is taken care of automatically when you run the superbuild, assuming you've left AUTO_UPDATE_EXTERNALS enabled (the default).

**Comment by sherm1** [comment]
OK, :lgtm: and I'm interpreting @mwoehlke-kitware's comment as a "looks good to him" also.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2770#-:-KMPdzq-7TkrvYZE_aHe:1938067523)*

**Pull request merged**
