### PR TITLE
Add RgbdRendererOSPRay

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939#-:-LEizhUdEXxVVqj7im6l:b-6wg1k9)*

**Comment by EricCousineau-TRI** [comment]
Hup, looks like some of the Python stuff is a little angry:
```
ImportError: libvtkRenderingOSPRay-8.1.so.1: cannot open shared object file: No such file or directory
```

Not sure, but perhaps its related to https://github.com/RobotLocomotion/drake/issues/8964?
I will see if I can debug this.

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 10 files at r1.
Review status: 3 unresolved discussions, LGTM missing from assignee ericcousineau-tri, platform LGTM missing, labeled "do not merge"

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkbd910FYHYAoaDODs:-LEkbd910FYHYAoaDODt:bn9zwvj) (no related file):*
The fix to the Python failures is to apply the following patch:
```patch
diff --git a/tools/install/libdrake/BUILD.bazel b/tools/install/libdrake/BUILD.bazel
index eae3c0b..be87c92 100644
--- a/tools/install/libdrake/BUILD.bazel
+++ b/tools/install/libdrake/BUILD.bazel
@@ -93,6 +93,7 @@
         "@vtk//:vtkIOImage",
         "@vtk//:vtkRenderingCore",
+        "@vtk//:vtkRenderingOSPRay",
         "@vtk//:vtkRenderingOpenGL2",
     ],
 )
```

Would you be able to add that in?

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkdBBM4c_x3xqFOQgt:-LEkdBBN1fYuxHdxkIgZ:bfe23k0) (no related file):*
I get inconsistent segfaults when running the test:
```
$ bazel build //systems/sensors:rgbd_renderer_ospray_test
$ for i in $(seq 10); do bazel-bin/systems/sensors/rgbd_renderer_ospray_test; done
```

Without `-c dbg`, it segfaulted 4 / 10 times. With `-c dbg`, it segfaulted 5 / 10 times, so it at least seems to be invariant of build mode.

Would you have time for us to debug this?

---

*[systems/sensors/BUILD.bazel, line 471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkcG4PD3BTiPTv5JM1:-LEkcG4PD3BTiPTv5JM2:bkh5qkn) ([raw file](https://github.com/robotlocomotion/drake/blob/87522d15e484226d55f9c663b999324696142dd8/systems/sensors/BUILD.bazel#L471)):*
> ```Python
>         ":test_models",
>     ],
>     tags = [
> ```

Can you factor these tags into something like a variable called `vtk_test_tags` to remove duplication?
That way there's no duplication.

We may want to split these into a macro if these tags are to be used elsewhere.

---

*[systems/sensors/rgbd_camera.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkccwVEQIykHbPQL3H:-LEkccwW5rJD0Ndp1-cl:bnoulum) ([raw file](https://github.com/robotlocomotion/drake/blob/87522d15e484226d55f9c663b999324696142dd8/systems/sensors/rgbd_camera.h#L138)):*
> ```objc
>              int width = RenderingConfig::kDefaultWidth,
>              int height = RenderingConfig::kDefaultHeight,
>              bool flat_terrain = true);
> ```

FYI Is there anyway to query this in the `RigidBodyTree`? It'd be nice to have it reflect the tree, rather than having to diverge.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkdBBM4c_x3xqFOQgt:-LEkeBvK-QqwgJSl7XlX:b-x6rmji) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I get inconsistent segfaults when running the test:
```
$ bazel build //systems/sensors:rgbd_renderer_ospray_test
$ for i in $(seq 10); do bazel-bin/systems/sensors/rgbd_renderer_ospray_test; done
```

Without `-c dbg`, it segfaulted 4 / 10 times. With `-c dbg`, it segfaulted 5 / 10 times, so it at least seems to be invariant of build mode.

Would you have time for us to debug this?
</blockquote></details>

Unable to reproduce the issue when running under `gdb` (using `gdb -ex run <target>`, and be using `r` to re-run).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)*

**Comment by kunimatsu-tri** [comment]
*[systems/sensors/rgbd_camera.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkccwVEQIykHbPQL3H:-LEoSld-0NMvtOEO_xzc:b-1o841f) ([raw file](https://github.com/robotlocomotion/drake/blob/87522d15e484226d55f9c663b999324696142dd8/systems/sensors/rgbd_camera.h#L138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Is there anyway to query this in the `RigidBodyTree`? It'd be nice to have it reflect the tree, rather than having to diverge.
</blockquote></details>

I agree and just added TODO since it's been diverged internally already and going to be relatively large PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)*

**Comment by kunimatsu-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee ericcousineau-tri, platform LGTM missing, labeled "do not merge"

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkbd910FYHYAoaDODs:-LEoPS0DAJLwlr6rIcu0:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The fix to the Python failures is to apply the following patch:
```patch
diff --git a/tools/install/libdrake/BUILD.bazel b/tools/install/libdrake/BUILD.bazel
index eae3c0b..be87c92 100644
--- a/tools/install/libdrake/BUILD.bazel
+++ b/tools/install/libdrake/BUILD.bazel
@@ -93,6 +93,7 @@
         "@vtk//:vtkIOImage",
         "@vtk//:vtkRenderingCore",
+        "@vtk//:vtkRenderingOSPRay",
         "@vtk//:vtkRenderingOpenGL2",
     ],
 )
```

Would you be able to add that in?
</blockquote></details>

Done.

---

*[systems/sensors/BUILD.bazel, line 471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkcG4PD3BTiPTv5JM1:-LEoQuE188axzqKMZ31K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87522d15e484226d55f9c663b999324696142dd8/systems/sensors/BUILD.bazel#L471)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you factor these tags into something like a variable called `vtk_test_tags` to remove duplication?
That way there's no duplication.

We may want to split these into a macro if these tags are to be used elsewhere.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing, labeled "do not merge"

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkdBBM4c_x3xqFOQgt:-LEzknPQ4WZVQlnBtNUt:bcgyxps) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unable to reproduce the issue when running under `gdb` (using `gdb -ex run <target>`, and be using `r` to re-run).
</blockquote></details>

For tracking, this issue has been captured in https://github.com/RobotLocomotion/drake/issues/8978

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8939)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by kunimatsu-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8939#-LEkdBBM4c_x3xqFOQgt:-LGx29aV3mkHCTOeJpJq:b-8tbhwz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@jamiesnape found what was most likely the issue, and luckily it seems like a simple one: we were not properly scoping some `vtkNew<>` instances (the renderer, actors, and mappers), and the fix was simple to make sure they lived long enough.
I could run the unittest 100x on my machine without any issues.

I've pushed the changes here, but will need to rebase.

\cc @jwnimmer-tri 
</blockquote></details>

Ugh, my bad.. Thanks @jamiesnape for finding it and @EricCousineau-TRI for fixing it!

---

**Comment by jamiesnape** [comment]
Add new VTK libraries here also: https://github.com/RobotLocomotion/drake/blob/53d9c58063caee74aaa26d79b179d1e1dbb3b877/tools/install/libdrake/BUILD.bazel#L81-L96

**Comment by EricCousineau-TRI** [comment]
On my laptop + desktop, I now get different results than what we had before I had rebased on `master` on Friday, where `MeshTest` fails. This seems to be due to the VTK update in da66b78b; if I revert this commit on the latest revision, the test passes.

image
new rev (merge-base c1bd98f, 07/06): https://github.com/EricCousineau-TRI/drake/blob/0224c54/systems/sensors/test/rgbd_renderer_ospray_test.cc#L239
old rev (merge-base 935b4c5, 06/10): https://github.com/EricCousineau-TRI/drake/blob/82115e9/systems/sensors/test/rgbd_renderer_ospray_test.cc#L239

It seems like the rendering passes are now more prevalent, even for `MeshTest`.

@jamiesnape, can I ask if you did anything else other than include more libraries in da66b78b? Do you have an idea of what might need to be done to fix this?
(It's not high priority at the moment, so no rush.)

**Comment by jamiesnape** [comment]
I forget exactly. I pulled in changes from `master` related to OSPRay, but I have built so many versions of the packages, I forget whether that contained them. Can you try `vtk-8.1.1-embree-3.2.0-ospray-1.6.1-python-2.7.12-python-3.5.2-qt-5.5.1-xenial-x86_64.tar.gz` (matching bionic package is `vtk-8.1.1-embree-3.2.0-ospray-1.6.1-python-2.7.15-python-3.6.5-qt-5.9.5-bionic-x86_64.tar.gz`)? I know the configuration of those packages for sure.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Looks like Mac seems to be wanting the old values `ColorI({131, 255, 160}), 254u` vs. the new values `ColorI({106, 255, 129}), 214u`:
https://drake-cdash.csail.mit.edu/testDetails.php?test=20835263&build=1027119
@jamiesnape Can I ask if you were able to apply the same updates to the VTK on Homebrew?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@EricCousineau-TRI @kunimatsu-tri Needs some buildifier and lint fixes. Not sure why the install is choking on part of VTK. I will look into that.

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by kunimatsu-tri** [comment]
It's failing at install.

```
Multiple installation rules found for vtkChartsCorePython.so.make[2]: *** [drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-install] Error 1
```

Would you have any idea @jamiesnape?

**Comment by jamiesnape** [comment]
Yes, a bug in the install. I think we should exclude the duplicates for now since we do not use Python 3.x yet. I will get back you to shortly with the glob to change.

**Comment by kunimatsu-tri** [comment]
Thanks!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
```
[ RUN      ] RgbdRendererOSPRayTest.MeshTest
drake/systems/sensors/test/rgbd_renderer_test_util.h:30: Failure
The difference between pixel[0] and color.r is 2, which exceeds tolerance, where
pixel[0] evaluates to 106,
color.r evaluates to 104, and
tolerance evaluates to 1.0009999999999999.
[  FAILED  ] RgbdRendererOSPRayTest.MeshTest (5215 ms)
```

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Pull request merged**
