### PR TITLE
First step in moving class RotationMatrix up to drake/math from its c…

### PR DESCRIPTION
**Pull request by mitiguy**
…urrent location under multibody_tree

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8221)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@SeanCurtis-TRI
Platform review +@sherm1

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8221#-:-L6ZZHtD9hmPWPkJuAwh:b55jdhz)*

**Comment by sherm1** [comment]
This doesn't follow our standard where some_name_test.cc tests some_name.h. Better to rename both the header and its matching test at the same time. I suggest  squashing #8217 into a single commit instead as Jeremy proposed.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8221#-:-L6Ztvnd3vmMa2MBm_nu:bgpz440)*

**Comment by SeanCurtis-TRI** [comment]
Also, to pick my own nits:

1. the PR title shouldn't use ellipses to spill into the comment. :) Clever, but not helpful. The comment *should* give context for the PR.  In other words, why is this the first step? What will it lead to? As it is, it's all guessing games for the reviewer.
2. I'm unable to infer the value of this PR. As @sherm1 pointed out, it breaks our standard and it isn't clear that it does so in a beneficial way. The only thing I can infer is that you're going to create a *new* `rotation_matrix_test.cc` file and use that to test the new rotation matrix class. I don't understand why that isn't simply done in a single PR.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8221#-:-L6bUqOvVpOnF4kW8NI0:b-xuq2rg)*

**Comment by SeanCurtis-TRI** [comment]
Actually, having looked at 8217, it is clear that this PR should simply be discarded.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8221#-:-L6b_p4u9tCfdFHoUuHc:b-w0wwze)*

**Comment by sherm1** [comment]
To clarify: #8217 is fine, #8221 (this one) should be closed.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8221#-:-L6bdGTU9tqNFwM_2TnO:btx748i)*

**Pull request closed without merging**
