### PR TITLE
Remove lint from #2172

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2219)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2219#-:-KGYoZATvxImf1vzrSwd:980077423)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2219#-:-KGYoqn4WavZDMCdaUxO:1417088721)*

**Comment by sherm1** [comment]
Thank you for fixing that, @david-german-tri. Sorry I didn't catch those problems.

**Comment by jwnimmer-tri** [comment]
Jenkins green, reviewable green, drake005 building but not going to wait.  Will merge now.

**Pull request merged**
