### PR TITLE
[C-IRIS] Construct the program to search for the separating plane

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444#-:-NJ9Mj4s0u_dpbaqjodO:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
WIP: will check the tests soon

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444#-:-NJAuJidCwJe0YZ31LKB:bkzogds)* status: 13 unresolved discussions, LGTM missing from assignee AlexandreAmice (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAfK4OA7xpjJN8O_Y4:-NJAfK4OA7xpjJN8O_Y5:b-3ocek4) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L114)):*
> ```objc
>    numerator of a rational is non-negative in the C-space region C*s<=d,
>    s_lower<= s <=s_upper. Hence for each of the rational we will introduce
>    Lagrangian multipliers for the polytopic constraint d-C*s >= 0, s >= s_lower,
> ```

nit: change `s >= s_lower` to `s - s_lower >= 0` for consistency in the comment 
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAfYwV9n3C4aaTK2G6:-NJAfYwV9n3C4aaTK2G7:bgl3oq2) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L117)):*
> ```objc
>    s_upper - s >= 0.
>    */
>   struct SearchPlaneLagrangians {
> ```

This name suggests that the struct does the searching which makes it seem like a method. This is really storing the certificate of positivity in the polytopic region and in some sense has nothing to do with plane. Consider the name change to something in the spirit `PositiveInRegionLagrangians`
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAjoSY25fC0yvqHkej:-NJAjoSY25fC0yvqHkek:b2mf4t1) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L140)):*
> ```objc
>    numerator_i(s) - λ(s)ᵀ * (d - C*s) - λ_lower(s)ᵀ * (s - s_lower)
>          -λ_upper(s)ᵀ * (s_upper - s) is sos
>    λ(s) are sos, λ_lower(s) are sos, λ_upper(s) are sos.
> ```

This comment currently doesn't do a great job of describing what the members of this struct correspond to. After reading this comment, I don't know what you intended to use prog to do, nor the difference between `positive_side_lagrangians` and `negative_side_lagrangian` .
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAjNAIAiJp6BdS0Fak:-NJAjNAIAiJp6BdS0Fal:b-b9x2fz) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L142)):*
> ```objc
>    λ(s) are sos, λ_lower(s) are sos, λ_upper(s) are sos.
>    */
>   struct SearchPlaneStruct {
> ```

Again I find this a somewhat non-descriptive name. Consider the name change `CertificateOfSeparationStruct` as this is the certificate that the plane is separating.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAkpdd6v4St5jH5W-Y:-NJAkpdd6v4St5jH5W-Z:b-r1tuyg) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L171)):*
> ```objc
>    Constructs a program to search for the separating plane for a pair of
>    geometries, for the entire set of configuration C * s <= d and s_lower <= s
>    <= s_upper.
> ```

nit: sentence structure `Constructs the program which searches for plane separating a pair of geometries for all configurations in the set {s | C * s <= d, s_lower <= s<= s_upper}."
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAmBc3BgXOSno5EtTK:-NJAmBc3BgXOSno5EtTL:bqe75lv) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L228)):*
> ```objc
>  */
> template <typename T>
> [[nodiscard]] VectorX<symbolic::Polynomial> CalcDminusCs(
> ```

Is there a reason this in the in `.h` file? As it is, this is exposed to everything in the `optimization` namespace
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAmuVy8RuPp1SnyP0f:-NJAmuVy8RuPp1SnyP0g:bqzux32) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L104)):*
> ```cpp
>   auto it = map_body_to_monomial_basis->find(body_pair);
>   if (it == map_body_to_monomial_basis->end()) {
>     const std::vector<multibody::internal::MobilizerIndex> mobilizers =
> ```

Consider changing this name to `mobilizer_indices` to avoid the confusion with `mobilizer` which is used later.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAn6-I3xfCWoES8ujF:-NJAn6-I3xfCWoES8ujG:btcb894) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L114)):*
> ```cpp
>       const auto& mobilizer = tree.get_mobilizer(mobilizer_index);
>       if ((mobilizer.can_rotate() && !mobilizer.can_translate()) ||
>           (mobilizer.can_translate() && !mobilizer.can_rotate())) {
> ```

If this check fails do we want to throw something? 
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAnZLY9JPtwpOHT3hZ:-NJAnZLY9JPtwpOHT3h_:bhm66ma) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L136)):*
> ```cpp
> 
> template <typename T>
> void SymmetricMatrixFromLowerTriangularPart(
> ```

BTW: Is this the right place for this method? I imagine it would be useful more generally. I'll accept this here for now
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAnuFd-hOED03aNFTc:-NJAnuFd-hOED03aNFTd:bnzl2it) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L152)):*
> ```cpp
> }
> 
> void AddLagrangian(
> ```

Could you add documentation here?
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 386 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJApImM6oRkLB6uDJmd:-NJApImM6oRkLB6uDJme:bihz4av) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L386)):*
> ```cpp
> }
> 
> CspaceFreePolytope::SearchPlaneLagrangians
> ```

This is a typo right?
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJArfwc24b42TRImtoy:-NJArfwc24b42TRImtoz:b1uo8jv) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L402)):*
> ```cpp
> 
> CspaceFreePolytope::SearchPlaneStruct
> CspaceFreePolytope::ConstructProgramSearchPlane(
> ```

nit: naming `ConstructPlaneSearchProgram`
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 439 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAt2miERJOqeIEXDy1:-NJAt2miERJOqeIEXDy2:byl20zj) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L439)):*
> ```cpp
>             (monomial_basis.rows() + 1) * monomial_basis.rows() / 2;
>         const int num_gram_vars = gram_size * num_grams;
>         auto gram_vars = prog->NewContinuousVariables(num_gram_vars, "Gram");
> ```

BTW: This has the downside of naming several of the gram variables the same string. But any user who looks at this program with the variables named is going to have a hard time parsing it anyway

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444)* status: 13 unresolved discussions, LGTM missing from assignee AlexandreAmice (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444)* status: 9 unresolved discussions, LGTM missing from assignee AlexandreAmice (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAfYwV9n3C4aaTK2G6:-NJBZJxv0kLj-Lb-hOJ3:bng4pv9) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L117)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This name suggests that the struct does the searching which makes it seem like a method. This is really storing the certificate of positivity in the polytopic region and in some sense has nothing to do with plane. Consider the name change to something in the spirit `PositiveInRegionLagrangians`
</blockquote></details>

Good call.

I changed it to `SeparatingPlaneLagrangians`. I am trying to avoid `Positive` in the struct name, as we also have "positive side" and "negative side" when we search for separating planes.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAjoSY25fC0yvqHkej:-NJBayvHAdwC7ZVb-8-6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L140)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This comment currently doesn't do a great job of describing what the members of this struct correspond to. After reading this comment, I don't know what you intended to use prog to do, nor the difference between `positive_side_lagrangians` and `negative_side_lagrangian` .
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAjNAIAiJp6BdS0Fak:-NJBbYWKBuI0dRxPngP3:b7uvo1n) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L142)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Again I find this a somewhat non-descriptive name. Consider the name change `CertificateOfSeparationStruct` as this is the certificate that the plane is separating.
</blockquote></details>

Done. Good call.

I use `SeparationCertificate` to shorten the name.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAmBc3BgXOSno5EtTK:-NJBdqpQE3bfn2F2tBNP:b-hmgsj3) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.h#L228)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is there a reason this in the in `.h` file? As it is, this is exposed to everything in the `optimization` namespace
</blockquote></details>

Done. Good call. I moved this into the private method of CspaceFreePolytope.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAmuVy8RuPp1SnyP0f:-NJBeIwBE9DTA1TY3u8A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L104)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Consider changing this name to `mobilizer_indices` to avoid the confusion with `mobilizer` which is used later.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAn6-I3xfCWoES8ujF:-NJBegNL3g-jjUfeF-U0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L114)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If this check fails do we want to throw something? 
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAnZLY9JPtwpOHT3hZ:-NJBeiavEPwRKPXIVrTq:b-1a4gc0) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L136)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: Is this the right place for this method? I imagine it would be useful more generally. I'll accept this here for now
</blockquote></details>

Maybe move it outside of this folder later. But for the moment I think it can live here. If I move it outside of this dev folder it would be a separate PR which requires more extensive unit tests and code review. I don't want to delay this PR for too long.

I added a TODO here.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAnuFd-hOED03aNFTc:-NJBfXuMDW0ATz0c9hSr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L152)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add documentation here?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 386 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJApImM6oRkLB6uDJmd:-NJBfd1S10XnS4oKuzUP:b-vlf8zf) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L386)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is a typo right?
</blockquote></details>

Sorry what do you mean? This `CspaceFreePolytope::SearchPlaneLagrangians` is the return type of the function.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 439 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJAt2miERJOqeIEXDy1:-NJBg9qZEycc91RzWMra:b-u73jp0) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L439)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: This has the downside of naming several of the gram variables the same string. But any user who looks at this program with the variables named is going to have a hard time parsing it anyway
</blockquote></details>

I don't really expect the user to print out the sos polynomials and parse it. We have too many sos polynomials, and if we really want to differentiate between them, we would need to give each gram matrix really verbose name.

The nice thing is that this function just allocates all gram matrix in one heap allocation.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18444#-:-NJBl5Iy6xILw7swGrYK:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee AlexandreAmice, exempt from platform review (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 386 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18444#-NJApImM6oRkLB6uDJmd:-NJBkd2k979FthKKXvbT:b55gy35) ([raw file](https://github.com/robotlocomotion/drake/blob/f3e37b9163098ba6210d70077171ba7dd0a958a2/geometry/optimization/dev/cspace_free_polytope.cc#L386)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry what do you mean? This `CspaceFreePolytope::SearchPlaneLagrangians` is the return type of the function.
</blockquote></details>

Ah the line break in the return type confused me. Sorry about that!

**Pull request merged**
