### PR TITLE
Expose some package in examples/kuka_iiwa_arm

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7940)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for both feature and platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7940#-:-L4MmaF8DleaMRD0GuE9:b-wc7wzx)*

**Comment by sammy-tri** [comment]
:lgtm: with a couple of BTWs

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4Npf9w80G5VkyY5Dkd:-L4Npf9w80G5VkyY5Dke:b-kf7uso) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/BUILD.bazel#L50)):*
> ```Python
>     srcs = ["iiwa_lcm.cc"],
>     hdrs = ["iiwa_lcm.h"],
>     visibility = ["//visibility:public"],
> ```

BTW should we TODO this as a candidate for a future move to `manipulation/kuka_iiwa?`

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 76 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4NpOZb-PMh7JYZV1H6:-L4NpOZc7ldrs-6Pgypl:bvd7x95) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/BUILD.bazel#L76)):*
> ```Python
> 
> drake_cc_library(
>     name = "lcm_plan_interpolator",
> ```

BTW There was some discussion about also making this public and tagging for an eventual move?

---

*[examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel, line 12 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4Nq1ZA5bVi8dAxJshp:-L4Nq1ZB4FjnXQjQwh64:brby8w3) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel#L12)):*
> ```Python
> load("//tools/skylark:6996.bzl", "adjust_labels_for_drake_hoist")
> 
> drake_cc_library(
> ```

BTW should we have a TODO here for a potential future move to `manipulation/kuka_iiwa`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-:-L4Nq6Xn3_hnRQ5xj0aO:b-3rrx33)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4Npf9w80G5VkyY5Dkd:-L4NrOpM1fiVsDodBLSF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/BUILD.bazel#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW should we TODO this as a candidate for a future move to `manipulation/kuka_iiwa?`
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/BUILD.bazel, line 76 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4NpOZb-PMh7JYZV1H6:-L4NrQ5M4Gnc-8tBON31:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/BUILD.bazel#L76)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW There was some discussion about also making this public and tagging for an eventual move?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel, line 12 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-L4Nq1ZA5bVi8dAxJshp:-L4NrR1U7GoJqevTJGCU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc5286183a796e858739dbfc373a3264a43b0db7/examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel#L12)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW should we have a TODO here for a potential future move to `manipulation/kuka_iiwa`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-:-L4aN5nB8mfwbAXtJZ_W:b-s794vx)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7940#-:-L4adIYy0xqO-vTPy6rY:b-l70wzf)*

**Pull request merged**
