### PR TITLE
geometry/opt: Add ConvexSet::IntersectsWith()

### PR DESCRIPTION
**Pull request by avalenzu**
Not quite sure of the right way to unit test this without adding too much set implementation into `convex_set_test.cc`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@russtedrake for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-MeQ5R2u2TtNbrBiGkKf:b-nden6u)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
This code looks great.

For testing, I think it's ok to `#include "drake/geometry/optimization/hpolyhedron.h"` in convex_set_test.cc, since they are in the same compilation unit (bazel cc_library) anyhow.   Or you could drop examples into hpolyhedron_test.cc , etc.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-MeQwQquAZE7cEEbaJ3e:b6jgnn9)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
Added test. -(status: do not merge) @russtedrake could you take another look when you get a chance?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-Mekq_KS-IxRyISWN8wT:b4ljus)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-MenwcBG6jaoNBTdiPAL:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

___
*[geometry/optimization/test/convex_set_test.cc, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15372#-MenwZ8d5aYL1thTyPRK:-MenwZ8d5aYL1thTyPRL:b913v05) ([raw file](https://github.com/robotlocomotion/drake/blob/756a65772013f916824ef1e5527daa35a4fa76b0/geometry/optimization/test/convex_set_test.cc#L72)):*
> ```cpp
>        ┃  A      ┃
>      0 ┗━━━━━━━━━┛
>        0    1    2    3    4    5
> ```

btw -- love this!

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for monday platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-MenxCmLEkQHx_hezVS_:b-jbsovd)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

___
*[geometry/optimization/convex_set.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15372#-Mez2f5Q8xu1mBpE8yhI:-MezGgSF1HC1ujHEbtZW:bogm6nj) ([raw file](https://github.com/robotlocomotion/drake/blob/756a65772013f916824ef1e5527daa35a4fa76b0/geometry/optimization/convex_set.cc#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW A passing thought on `DRAKE_THROW_UNLESS`. Using this macro puts the burden on the user to infer what they did wrong from how the test is formulated. In recent changes to the [style guide's advice on exceptions](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) is the phrase:

> The clarity of the error message string matters more than the subtype choice.

While this in no way *requires* an exception message, it does emphasize the value of a message. So, I leave it with you to decide if there's any blurb that would provide more insight to an end user than just seeing the test condition.
</blockquote></details>

Thanks. I think the test actually conveys about as much what I could convey in a blurb.
___
*[geometry/optimization/test/convex_set_test.cc, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15372#-MenwZ8d5aYL1thTyPRK:-MezH0lzC851_097odzG:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/756a65772013f916824ef1e5527daa35a4fa76b0/geometry/optimization/test/convex_set_test.cc#L72)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Amen to that!
</blockquote></details>

Thanks!

**Review by avalenzu — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15372#-:-MezHFOh8J8LUNuuMcNh:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @avalenzu)

**Pull request merged**
