### PR TITLE
Amend the style guide's treatment of `std::hash`.

### PR DESCRIPTION
**Pull request by maddog-tri**
This proposal follows from a discussion in #6930:

https://reviewable.io/reviews/robotlocomotion/drake/6930#-Kse5XfQ0dd4-EHovlWa

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6937)

### CODE REVIEW

**Comment by sherm1** [comment]
:+1: I am in favor of this proposal.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KskN1efWxo0hj5saI2a:b8nojqa)*

**Comment by soonho-tri** [comment]
:+1: I'm in favor of this proposal.

Hashing is *not* something we can discourage people from doing it by making it more laborious.

GSG's suggestion on `std::hash` might be more meaningful if we are willing to implement the techniques introduced in [Types Don't know #](https://github.com/CppCon/CppCon2014/raw/master/Presentations/Types%20Don't%20Know%20%23/Types%20Don't%20Know%20%23%20-%20Howard%20Hinnant%20-%20CppCon%202014.pdf). But I'm afraid that we want to do this (at least, for now).

I've checked the C++ Core Guidelines from ISOCPP on the topic. The only thing it mentions is to make sure that a hash function does not throw (see [here](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-hash)).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KskS5Xm6Y1ApfaU-s5y:bxwpb6y)*

**Comment by soonho-tri** [comment]
Related topic: I wrote `drake/common/hash.h` last year when we were not allowed to use any `boost`. Now, AFAIK, the condition is relaxed to allow *header-only* `boost`s (correct me if I'm wrong). I'm :+1: if anyone volunteers to replace what we have in `drake/common/hash.h` with `boost::hash`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KskXbLcz_9SAk1Uuu7m:b-nckfeo)*

**Comment by maddog-tri** [comment]
That "Types Don't know #" proposal is pretty neat.(*)  (I found the [full paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3980.html) more readable than the slide-deck.)  But, it's not a standard yet and would require special instructions on how to use standard containers with custom-hashed types, and I don't think we have yet encountered a situation where we need to mix'n'match hashing algorithms.

I think our goal here is to allow new types to be hashable with the same level of adequacy as the built-in types, which is why specializing `std::hash` seems reasonable, because we would effectively be saying "Here is a hash() for T which is on par with the built-in std::hash()'es."

(* - And, it seems like the mechanism for describing "hash-worthy state" of a type could also be used for the definition of `operator==`, since equality and hash-value are so tightly coupled.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KslzZqiIfXfr7V3RwUr:bqsli5i)*

**Comment by maddog-tri** [comment]
I've rearranged/rewritten the original proposal, to more clearly state the *"this is what you should do"* followed by the *"and this is why"*.  Given the favorable initial feedback, I think it's ready for formal review.

Summoning all platform-reviewers.  \<caw>...\<caw>  +@sherm1 +@jwnimmer-tri +@sammy-tri +@seancurtis-tri +@soonho-tri +@ericcousineau-tri +@ggould-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtXNKxng3Np5y9d3B3e:b-tnv15d)*

**Comment by EricCousineau-TRI** [comment]
:+1: I'm in favor of this proposal.

Added a minor BTW regarding existing exceptions.

> ... might be more meaningful if we are willing to implement the techniques introduced in Types Don't know # ...

It seems like that pattern could lend itself to the Boost.Serialization visitor setup (with some extra setup for key-value pairs, possibly?).
Do we have near-term plans for incorporating this into Drake (be it Boost, cereal, or what not)? Could this be tied into it?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtX_5FEiqD6a8QrhPxD:-KtX_5FG1ls7RBVyik3q:b-pujzjz) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L222)):*
> ```reStructuredText
>     (``std::unordered_map``, ``std::unordered_set``) will "just work".
>   * If a type has implementations of any of ``std::hash``, ``std::equal_to``,
>     ``std::less``, ``operator==``, or ``operator<``, then those
> ```

BTW @soonho-tri Should this language be softened, or should an explicit mention be made of the disparity between`operator==` and `std::equal_to` for `symbolic::Expression` (w.r.t `Formula` returns for logical comparison operators)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtXcSHTiFMTDCIglekM:bwkci36)*

**Comment by sherm1** [comment]
:lgtm: -- thanks, @maddog-tri!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtXoHlykWIOu53Y7h4W:brroh39)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtXsVjhn8g7m8e6j6im:bnfp4nl)*

**Comment by maddog-tri** [comment]
-(status: do not review)   (Forgot that earlier!)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtX_5FEiqD6a8QrhPxD:-KtXwCmDPWPDxSXoF9N6:b-6h9aj0) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L222)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Hmm. I thought that "mutually compatible with each other" sounds flexible enough
</blockquote></details>

Having a `std::equal_to` with different behavior from a coexisting `operator==` seems dangerous --- as in "violates the principal of least surprise".  To be honest, from a shallow dive into `symbolic::Expression`, I have no idea what is going on in there in particular.

If calling `find(s)` on a `std::unordered_set<symbolic::Expression>` behaves differently than iterating over the elements and testing each against `s` with `operator==`,  I'd think that would be considered exceptional behavior that should be clearly documented as such in the `symbolic::Expression` code, like any other style-guide exception.  It wouldn't need to be cataloged in the style-guide itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtY1n9zkQFabzZ7fTqu:bq45r1)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtX_5FEiqD6a8QrhPxD:-KtY4aW24QE0oCpaKXwu:b-ba7jcz) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L222)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Having a `std::equal_to` with different behavior from a coexisting `operator==` seems dangerous --- as in "violates the principal of least surprise".  To be honest, from a shallow dive into `symbolic::Expression`, I have no idea what is going on in there in particular.

If calling `find(s)` on a `std::unordered_set<symbolic::Expression>` behaves differently than iterating over the elements and testing each against `s` with `operator==`,  I'd think that would be considered exceptional behavior that should be clearly documented as such in the `symbolic::Expression` code, like any other style-guide exception.  It wouldn't need to be cataloged in the style-guide itself.
</blockquote></details>

Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtY5ADMAg2GzBWt29bu:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Sorry for coming late to the party. A typo and suggestion; PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 231 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlSEetGjwfa_nJyy08:-KtlSEeu6PXfiTY31Rdd:b-73r7) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L231)):*
FYI I'd recommend a slight wording change. The points up to this point is guidance to the developer. This last point is an assertion of the review process. As such, I like stronger language.

> All hash functions __*will*__ be given the same level of scrutiny...

---

*[drake/doc/code_style_guide.rst, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlScON1oQbaZyLCRs4:-KtlScON1oQbaZyLCRs5:b-3g3p8m) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L235)):*
> ```reStructuredText
>   * Rationale:
> 
>     * Hash functions are necessity of modern C++ programming.
> ```

BTW typo: "...are __*a*__ necessity..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtlSrR6NaulY0tpxsIg:b-38an3c)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlQk_Ihox0qx7qZF_G:-KtlQk_Ihox0qx7qZF_H:b-9glgib) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L232)):*
> ```reStructuredText
>     special-purpose equality predicates (i.e., other than ``operator==``).
>   * All hash functions should be given the same level of scrutiny, no matter
>     what names they are given or where they are defined.
> ```

Its unclear to me what this bullet point is trying to say.

If it just means that all code receives the same level of review, then that is obvious and intrinsic in all coding guidelines, and so is confusing here because it begs the question of what in particular this bullet point is trying to say.

If something more specific is intended, then it didn't come through to my reading so needs to be clarified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KtlZWoVgv9CgP9DEosb:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlQk_Ihox0qx7qZF_G:-KtlZYb1OLJ7y03tPI_k:b-jyx4mj) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L232)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its unclear to me what this bullet point is trying to say.

If it just means that all code receives the same level of review, then that is obvious and intrinsic in all coding guidelines, and so is confusing here because it begs the question of what in particular this bullet point is trying to say.

If something more specific is intended, then it didn't come through to my reading so needs to be clarified.
</blockquote></details>

I realized, when I read this, that I'd read into it with my own baggage. I had the sense that creating hash functions for custom types is still generally discouraged, and that the *justification* of hashing a custom type would receive particular scrutiny. In retrospect, that mindset is wholly unsupported by this text.

So, the question is, should we be applying any downward pressure to prevent hashable custom types from arbitrarily popping up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlY-OavQ_Xf69Futxw:-KtlY-Ob6j-7jdnC3OfC:b90dbg9) (no related file):*
For prescriptive new rules in our code_style_guide, I am hesitant to sign off on a PR unless it is either documenting existing practice, or is accompanied by a (probably separate PR or dev branch) change that illustrates the consequences of the rule change.

In this case, to the extent that non-compound types are already specializing, e.g., `std::hash<Identifier>` to merely delegate to, e.g., `std::hash<int64_t>` without any combining, I think we are documenting existing practice and are all good.

However, for compound types, I don't think we have any code in-tree that obeys these new rules, so before I sign off I would like to see a worked-out example that follows the new rules...

One example that could be ported concurrently with this proposal would be `symbolic::Expression` and `symbolic::Formula`. (Right now, they do not follow the new rules because they do not specialize, e.g., `std::hash<drake::symbolic::Expression>`.)  This would demonstrate how the proposal works in the presence of inheritance.

Other examples that could be ported are generate_obj's `GeoVertex` are rgbd_camera's `ColorHash`, which would illustrate how the proposal works in the absence of inheritance.

---

*[drake/doc/code_style_guide.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlMayB5gheC-mrQ6DN:-KtlMayB5gheC-mrQ6DO:b-47sax8) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L227)):*
Imagine these classes:
```c++
struct Bar {
  int i;
}
struct Foo {
  std::string name;
  Bar bar;
};
```

In this bullet's text, by paring out the conditions and cases irrelevant here, I believe the rule demands:

> Foo's hash function should be implemented using drake::hash_combine
> to compose standard built-in hash functions.

I interpret "standard built-in hash functions" to refer to the list at http://en.cppreference.com/w/cpp/utility/hash#Standard_specializations_for_basic_types.  That includes `string` and `int`, but of course does not include `Bar`.  So as written, this rule demands:
```c++
namespace std {
struct hash<Foo> {
  size_t operator()(const Foo& foo) const {
    return drake::hash_combine(0, foo.name, foo.bar.i);
  }
};
```
In other words, hashers over Drake types must never be written inductively by delegating to other Drake hashers, but instead must list out all wrapped data types down to their primitives.

Is this the intended meaning?

If yes, the text must be clarified so that all readers will use that interpretation.

If yes, its unclear to me how a developer should obey that rule in the presence of virtual inheritance (if Bar were a virtual base class)  -- Foo's hash function might not know the full list of primitive types that Bar can encapsulate.  Maybe we have to declare that we never write hashers in the presence of inheritance?  That would be a problem for `symbolic::Expression`.

If no, then the text must be repaired to indicate whatever alternative meaning was intended.

---

*[drake/doc/code_style_guide.rst, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlQk_Ihox0qx7qZF_G:-KtlaQzwSGEe0LGYrV47:bvoq0et) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L232)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I realized, when I read this, that I'd read into it with my own baggage. I had the sense that creating hash functions for custom types is still generally discouraged, and that the *justification* of hashing a custom type would receive particular scrutiny. In retrospect, that mindset is wholly unsupported by this text.

So, the question is, should we be applying any downward pressure to prevent hashable custom types from arbitrarily popping up?
</blockquote></details>

My impression of this proposal's intent was to put hashing on par with its kin like equal_to, less, etc.... "write it iff you need it, and craft it in this way".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlQk_Ihox0qx7qZF_G:-KtlbcqWVWTWl5d8zCrZ:b-xfchmj) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L232)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My impression of this proposal's intent was to put hashing on par with its kin like equal_to, less, etc.... "write it iff you need it, and craft it in this way".
</blockquote></details>

Yours is obviously the consistent read.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlMayB5gheC-mrQ6DN:-KtlnKXcctt8S0_xwee3:b-1ifool) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Imagine these classes:
```c++
struct Bar {
  int i;
}
struct Foo {
  std::string name;
  Bar bar;
};
```

In this bullet's text, by paring out the conditions and cases irrelevant here, I believe the rule demands:

> Foo's hash function should be implemented using drake::hash_combine
> to compose standard built-in hash functions.

I interpret "standard built-in hash functions" to refer to the list at http://en.cppreference.com/w/cpp/utility/hash#Standard_specializations_for_basic_types.  That includes `string` and `int`, but of course does not include `Bar`.  So as written, this rule demands:
```c++
namespace std {
struct hash<Foo> {
  size_t operator()(const Foo& foo) const {
    return drake::hash_combine(0, foo.name, foo.bar.i);
  }
};
```
In other words, hashers over Drake types must never be written inductively by delegating to other Drake hashers, but instead must list out all wrapped data types down to their primitives.

Is this the intended meaning?

If yes, the text must be clarified so that all readers will use that interpretation.

If yes, its unclear to me how a developer should obey that rule in the presence of virtual inheritance (if Bar were a virtual base class)  -- Foo's hash function might not know the full list of primitive types that Bar can encapsulate.  Maybe we have to declare that we never write hashers in the presence of inheritance?  That would be a problem for `symbolic::Expression`.

If no, then the text must be repaired to indicate whatever alternative meaning was intended.
</blockquote></details>

If your interpretation were correct, it would be super brittle -- a change to Bar would require changes in the hash function of all users of Bar, and the absence of such changes could easily slip by a reviewer.

Absent some really good counterargument, I'm going to say that interpreted that way this change would be defective (unmaintainable), and so it should be clarified to not say that.  The obvious fix would be to add "or a hash function implemented under this rule" to the or clause.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlMayB5gheC-mrQ6DN:-KtnjLC7q26i4mVAP43X:b-sbqfcw) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L227)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

If your interpretation were correct, it would be super brittle -- a change to Bar would require changes in the hash function of all users of Bar, and the absence of such changes could easily slip by a reviewer.

Absent some really good counterargument, I'm going to say that interpreted that way this change would be defective (unmaintainable), and so it should be clarified to not say that.  The obvious fix would be to add "or a hash function implemented under this rule" to the or clause.
</blockquote></details>

Right.

So if we allow compound types to delegate to `std::hash` on their contained items and then `hash_combine` those results, then we have a hashing implementation that does not meet the highest level of standard for what it should be.  And the question on the table is whether we accept that deficiency as a compromise in the name of convenience, or instead whether we prescribe either a different spelling or different implementation so that we either require, or pave the way for, a more suitable implementation.

I am honestly not sure why we are trying to standardize our handling of compound types?  `symbolic::Expression` has a custom implementation, careful testing, and avoids specializing `std::hash`, which means that when you opt-in to use its conceptually imperfect hashers, you are stating that explicitly at the call sites (of which there are few).  I don't know of other compound types that we really want to hash in a generic and concise way.  Thus, the call for worked-out examples in my top-post comment.

(To be clear, the case for pass-through hashers for simple wrapper types like Identifier is clear, and merits a code_style_guide clarification.  Compound types are what's in doubt.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by maddog-tri** [comment]
Sorry for the lonnng delay.  With a few little tweaks, I think I have addressed all the comments.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlY-OavQ_Xf69Futxw:-KvdNYjeqj5ZvTJRucYc:bfefvkj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For prescriptive new rules in our code_style_guide, I am hesitant to sign off on a PR unless it is either documenting existing practice, or is accompanied by a (probably separate PR or dev branch) change that illustrates the consequences of the rule change.

In this case, to the extent that non-compound types are already specializing, e.g., `std::hash<Identifier>` to merely delegate to, e.g., `std::hash<int64_t>` without any combining, I think we are documenting existing practice and are all good.

However, for compound types, I don't think we have any code in-tree that obeys these new rules, so before I sign off I would like to see a worked-out example that follows the new rules...

One example that could be ported concurrently with this proposal would be `symbolic::Expression` and `symbolic::Formula`. (Right now, they do not follow the new rules because they do not specialize, e.g., `std::hash<drake::symbolic::Expression>`.)  This would demonstrate how the proposal works in the presence of inheritance.

Other examples that could be ported are generate_obj's `GeoVertex` are rgbd_camera's `ColorHash`, which would illustrate how the proposal works in the absence of inheritance.
</blockquote></details>

Done --- see #7190.

---

*[drake/doc/code_style_guide.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlMayB5gheC-mrQ6DN:-KvdBjoa_H63iyi1NKps:b-hkho73) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right.

So if we allow compound types to delegate to `std::hash` on their contained items and then `hash_combine` those results, then we have a hashing implementation that does not meet the highest level of standard for what it should be.  And the question on the table is whether we accept that deficiency as a compromise in the name of convenience, or instead whether we prescribe either a different spelling or different implementation so that we either require, or pave the way for, a more suitable implementation.

I am honestly not sure why we are trying to standardize our handling of compound types?  `symbolic::Expression` has a custom implementation, careful testing, and avoids specializing `std::hash`, which means that when you opt-in to use its conceptually imperfect hashers, you are stating that explicitly at the call sites (of which there are few).  I don't know of other compound types that we really want to hash in a generic and concise way.  Thus, the call for worked-out examples in my top-post comment.

(To be clear, the case for pass-through hashers for simple wrapper types like Identifier is clear, and merits a code_style_guide clarification.  Compound types are what's in doubt.)
</blockquote></details>

Done.  I believe I have addressed the original defect.

---

*[drake/doc/code_style_guide.rst, line 231 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlSEetGjwfa_nJyy08:-KvdBpQu7pcFq25cXNfw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L231)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'd recommend a slight wording change. The points up to this point is guidance to the developer. This last point is an assertion of the review process. As such, I like stronger language.

> All hash functions __*will*__ be given the same level of scrutiny...
</blockquote></details>

Done.

---

*[drake/doc/code_style_guide.rst, line 232 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlQk_Ihox0qx7qZF_G:-KvdBs9sBCEdfUoe_qBc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L232)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Yours is obviously the consistent read.  :)
</blockquote></details>

Done.

---

*[drake/doc/code_style_guide.rst, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlScON1oQbaZyLCRs4:-KtqvB_7igybLKJOipf6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L235)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW typo: "...are __*a*__ necessity..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KvdPniD4ymAzK_VTwHj:bh15wko)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-KtlMayB5gheC-mrQ6DN:-Kvgayzija-L9311FiCi:b-4gepm3) ([raw file](https://github.com/robotlocomotion/drake/blob/2a2f07885d91d52250ffcd1b5cbbfbecddca3460/drake/doc/code_style_guide.rst#L227)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.  I believe I have addressed the original defect.
</blockquote></details>

The delegation implicit in hash_combine looks adequate to me for maintainable code.  I withdraw my objections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937)*

**Comment by jwnimmer-tri** [comment]
So this PR will have to be refiled against the `styleguide` repository.

As part of that rework, I would also like to make the case that we should not enshrine `drake/common/hash.h` as our Drake recommendation.  I do not think we should endorse a `hash_combine`-based implementation, since that is a dead-end design that we know we will need to rework, per Hinnant's exposition.  I believe a `hash_append`-based implementation would be straightforward and has a low enough activation energy to require it as table stakes for anyone wishing to standardize our hashing within Drake.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6937#-:-KwBopA2LYxJoPcR1FIR:bajo0t8)*

**Comment by maddog-tri** [comment]
(Superseded by the `hash_append` work and associated changes to the replanted style guide.)

**Pull request closed without merging**
