### PR TITLE
Fix vtk link-include scope for CMake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5214)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@kunimatsu-tri for feature review, please.  Follow-up to #5200.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5214#-:-KdD4O5f5Iqzi720jBPb:b-7apmdq)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

Thank you!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5214#-:-KdD5kVg1osXbBpjuvV2:b-vdwr1z)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform please (no rush) -- because you were involved in the original VTK CMake PR review last week so have some context.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5214#-:-KdD61rX9ckyXsdJ9Q4z:b-uq98ci)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5214#-:-KdD9NR4s71CbkhVyPG6:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5214)*

**Pull request merged**
