### PR TITLE
[workspace] Upgrade buildifier to latest release v7.1.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21211

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI The fix for the CI errors here is to run the "fix via" instructions reported by the linting.  We generally just accept whatever it reformats the code to use, unless the formatting is totally awful and unreadable.

**Review by BetsyMcPhail — COMMENTED** [review]
+@rpoyner-tri as Jeremy is out this week, can you take a look at this for feature review? 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261#-:-NuyrO6X6zJtFK9amBah:b-vxllo4)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
-@rpoyner-tri - looks like there are still errors

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261#-:-Nuyske13QS5W22Gf88q:b-o3pbyq)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
Additionally ran the following commands:

`bazel-bin/tools/lint/buildifier cmake/external/workspace/eigen/BUILD.bazel.in`
`bazel-bin/tools/lint/buildifier cmake/external/workspace/fmt/BUILD.bazel.in`
`bazel-bin/tools/lint/buildifier cmake/external/workspace/spdlog/BUILD.bazel.in`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261#-:-Nuyty2_2ALFzqmtdOLR:b-uy1fw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
+@rpoyner-tri for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261#-:-Nuyy1KJ61oz0NAn1SeA:b-6pcnam)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 263 of 263 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21261#-:-Nv2f_Cs98rDG8XvzRSQ:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
