### PR TITLE
Add a first basic pass at gflags / spdlog integration

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This PR adds a first basic pass at gflags / spdlog integration, including a main program that can toggle the level.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3345)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Build errors appear to be genuine in some way, even though it works for me.  Will investigate later.

**Comment by jwnimmer-tri** [comment]
Well, the "unused variable" error in clang is fixed now, but windows is still unhappy.  It reads `ninja: error: 'gflags-NOTFOUND', needed by 'lib/drakeCommon.dll', missing and no known rule to make it`.

**Comment by jwnimmer-tri** [comment]
Windows break is likely because this PR switches gflags from a static library to a shared library.  Hello, #2501 tax.

Master build output:
```
-- Installing: C:/Users/Administrator/28EkFWtL/build/install/Lib/gflags_static.lib
-- Installing: C:/Users/Administrator/28EkFWtL/build/install/Lib/gflags_nothreads_static.lib
```

New PR build output:
```
-- Installing: C:/Users/Administrator/workspace/experimental/0b4ef046/build/install/Lib/gflags.lib
-- Installing: C:/Users/Administrator/workspace/experimental/0b4ef046/build/install/Lib/gflags.dll
```

**Comment by jwnimmer-tri** [comment]
Nobody can figure out how to get this working on windows.  I am going to rework this PR to guard this new feature to be disabled on windows.

**Comment by jwnimmer-tri** [comment]
This is ready for review now.  Note that I will squash some of the commits before merging -- I wanted to keep them separate for now while I danced with Jenkins.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUFfjtRAWrUZunmFSB:-KRUFfjuq-P_Gd1gudzr:bm3dj8l) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/CMakeLists.txt#L137)):*
> ```CMake
> 
> # gflags
> if(WIN32)
> ```

Please add a comment explaining this conditional.

---

*[drake/common/text_logging.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUGbWOIupRFOKDMErb:-KRUGbWOIupRFOKDMErc:bt3mike) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/drake/common/text_logging.cc#L14)):*
> ```cpp
> constexpr const char kTrace[] = "trace";
> constexpr const char kDebug[] = "debug";
> constexpr const char kLevelHelp[] =
> ```

BTW, this named constant seems like a minor antipattern to me, since it really should not be used more than once ever.

Also, while it's not difficult in this file, in some files you could imagine it being a pain for readers of the flag definition to dereference `kLevelHelp`.

---

*[drake/common/text_logging.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUGISB-uczi0Mn1XOd:-KRUGISB-uczi0Mn1XOe:bffu1m3) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/drake/common/text_logging.cc#L31)):*
> ```cpp
>     throw std::runtime_error("Unknown spdlog level");
>   }
> #ifdef HAVE_SPDLOG
> ```

Where does this come from, and when wouldn't it be true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3345)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUFfjtRAWrUZunmFSB:-KRUJNVtiDQYPtlnV41v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/CMakeLists.txt#L137)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please add a comment explaining this conditional.
</details>
Done.

---

*[drake/common/text_logging.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUGbWOIupRFOKDMErb:-KRUPLu6WSEmlFTvYYNV:b-8gplzf) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/drake/common/text_logging.cc#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this named constant seems like a minor antipattern to me, since it really should not be used more than once ever.
> 
> Also, while it's not difficult in this file, in some files you could imagine it being a pain for readers of the flag definition to dereference `kLevelHelp`.
</details>
Done.

It made more sense in an earlier iteration (and _argh_ to gflags for not being able to refer to `kTrace` and such here).

---

*[drake/common/text_logging.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUGISB-uczi0Mn1XOd:-KRUJoqNdnnP3C_nSt1I:b-6q91tn) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/drake/common/text_logging.cc#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Where does this come from, and when wouldn't it be true?
</details>
It comes from https://github.com/RobotLocomotion/drake/blob/04de60e25f44c7f4ae3d2ad7990fe67a6f2fbf81/drake/CMakeLists.txt#L296.

It would be false if the user has not built spdlog, either because they ran the superbuild like `-DWITH_SPDLOG:BOOL=OFF`, or were building Drake using their own superbuild and didn't add spdlog to the mix for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3345)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-KRUFfjtRAWrUZunmFSB:-KRUROS1ApmN__vpKZgu:b-unimer) ([raw file](https://github.com/robotlocomotion/drake/blob/51a7e8020b6995abeb3cdfe100053cfb7f6d5d54/CMakeLists.txt#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Done.
</details>
OK.  In a bizarre way, this has value as a forcing function to minimize flags in libraries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-:-KRURcJrlAv26e78172w:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-:-KRUrI6q4CUw1YPQ23Db:bppyoqq)*

**Comment by jwnimmer-tri** [comment]
FTR -- the jenkins error was a CDash upload flake.

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Reviewed, :lgtm:. Windows CI flaked again. I restarted it but if it reflakes I suggest merging anyway.

---

Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3345#-:-KRWlmLQdbFRQQAzCpL1:b-92x0ol)*

**Pull request merged**
