### PR TITLE
adding a dev foled in examples/kuka_iiwa_arm and preparing for pick and place demo

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
0. added a dev folder in examples/kuka_iiwa_arm
1. moved the new ik wrapper code and a simple test from #5231 to dev. all feature reviews have been addressed in #5231.
2. moved the robotlocomotion::robot_plan_t encoding code to iiwa_common, as it's needed by subsequent demo code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5289)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review (shouldn't have anything to review)
+@sammy-tri for platform review. thanks guys. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-:-KdgjBx1VqoZ0fNHTA_C:bowuzwh)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 4 of 11 files at r1.
Review status: 4 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-:-KdkFXdt6No7HWJO_2UJ:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) first pass still in progress

---

Reviewed 8 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl-QW-IDAsteiPWET0:-Kdl-QW-IDAsteiPWET1:bd3ypzd) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L199)):*
> ```cpp
>   DRAKE_DEMAND(keyframes.rows() == robot.get_num_positions());
> 
>   const int kNumTimesteps = keyframes.cols();
> ```

I don't think this should get kConst naming since it's not fixed for the duration of the program.  https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/examples/kuka_iiwa_arm/dev/BUILD, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl-zCD_XExF4DY_CxX:-Kdl-zCD_XExF4DY_CxY:bd8jdv8) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/BUILD#L8)):*
> ```Python
>     "//tools:drake.bzl",
>     "drake_cc_library",
>     "drake_cc_binary",
> ```

This isn't used in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-:-KdkymXAO0sgtsu5aL-f:b-2cgv0s)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlAuj6M9zdhJfMFoC1:-KdlAuj6M9zdhJfMFoC2:b-tv24d8) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L3)):*
> ```cpp
> #include "drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h"
> 
> #include <iostream>
> ```

Leftover debug include?

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlB30ASOqNyG7N5InM:-KdlB30ASOqNyG7N5InN:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L4)):*
> ```cpp
> 
> #include <iostream>
> #include <list>
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlBvD8rCG_TE5DDZbJ:-KdlBvD95vAG5rGAixQ-:b-cquopy) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L66)):*
> ```cpp
>     waypoints[i].pose.translation() = way_point_list[i];
>     waypoints[i].pos_tol = position_tol;
>     waypoints[i].rot_tol = 1;
> ```

This seems like a really high rotational tolerance in radians.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl8eLy1GnUX6jLFauq:-Kdl8eLzyF_BYtE-ynse:bm270o8) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h#L20)):*
> ```objc
>  * handling constraint relaxing and multiple initial guesses internally.
>  */
> class IiwaIkPlanner {
> ```

Consider using drake_copyable.h macros to disable copying

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl9Gb3sGRel4uY-hFl:-Kdl9Gb3sGRel4uY-hFm:bdcg8f9) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h#L25)):*
> ```objc
>    * Struct holding results from the IK planner.
>    */
>   struct IkResult {
> ```

BTW This seems mostly to duplicate IKResults from rigid_body_ik.h maybe we should just add times to that?  (I guess there's the matrix vs. vector of vectors question)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289)*

**Comment by siyuanfeng-tri** [comment]
Review status: 6 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl-QW-IDAsteiPWET0:-Kdl9CHycDON_I_hjYZD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L199)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think this should get kConst naming since it's not fixed for the duration of the program.  https://google.github.io/styleguide/cppguide.html#Constant_Names
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/BUILD, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl-zCD_XExF4DY_CxX:-Kdl9HMnNs_wjVrNQ7HZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/BUILD#L8)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This isn't used in this file.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlAuj6M9zdhJfMFoC1:-KdlM35svMNwo9M8oUu3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Leftover debug include?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlB30ASOqNyG7N5InM:-KdlM5MEw6-yVTW8nv35:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-KdlBvD8rCG_TE5DDZbJ:-KdlMBv1wsLXNSZ6c1rx:br1q2nn) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.cc#L66)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems like a really high rotational tolerance in radians.
</blockquote></details>

ah, good catch, this is dead code for backward compatibility with naveen's ik which doesn't have orientation constraints at all. so this number was completely arbitrary. 

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl8eLy1GnUX6jLFauq:-Kdla9NfsN7k7E3NXM2G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h#L20)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Consider using drake_copyable.h macros to disable copying
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-Kdl9Gb3sGRel4uY-hFl:-KdlN4uLxDPS6LFBmSMX:b-chhph2) ([raw file](https://github.com/robotlocomotion/drake/blob/84e08389c4611f0831696d76a066d5a0e0148761/drake/examples/kuka_iiwa_arm/dev/iiwa_ik_planner.h#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW This seems mostly to duplicate IKResults from rigid_body_ik.h maybe we should just add times to that?  (I guess there's the matrix vs. vector of vectors question)
</blockquote></details>

good point. i will just switch to that, since i am not doing anything intelligently with time here anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5289#-:-KdlyfX2VuIu1Dg5NlId:bnfp4nl)*

**Pull request merged**
