### PR TITLE
Improve ToLatex support for inf, nan, π, and e.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19941)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-:-Nb9XRf95i4QHobuDC_o:b-3q8wn7)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending a few more tests

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-:-NbBCrXq1P1M0l6TsZqb:byoe7zf)* status: 2 unresolved discussions

___
*[`common/symbolic/latex.cc` line 400 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-NbBC2bZ3gCfWlptGuIo:-NbBC2b_105p1Vi0YIop:b-xm8mg5) ([raw file](https://github.com/RobotLocomotion/drake/blob/06311832b78b6c43f5c2434b359978ba54fcc0be/common/symbolic/latex.cc#L400)):*
> ```cpp
>   std::string constant;
>   if (multiple_of_famous_constant(val, M_PI, "\\pi", precision, &constant)) {
>     return constant;
> ```

nit: `constant` is misnamed here since the full expression is returned. Maybe `expr` or `product`?
___
*[`common/symbolic/test/latex_test.cc` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-NbBCKHN1k-Nb7wB38gA:-NbBCKHO3RGCOaKT-y75:bd7bjf2) ([raw file](https://github.com/RobotLocomotion/drake/blob/06311832b78b6c43f5c2434b359978ba54fcc0be/common/symbolic/test/latex_test.cc#L33)):*
> ```cpp
>   EXPECT_EQ(ToLatex(-M_PI), "-\\pi");
>   EXPECT_EQ(ToLatex(14.0 * M_PI), "14\\pi");
>   EXPECT_EQ(ToLatex(-7.0 * M_E), "-7e");
> ```

minor: these test only the easy cases. Most of the new code uses round() and fmod() and an epsilon to handle the tricky near-multiple cases. There should be unit tests here that exercise that code to make sure it is working as expected now and in the future.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19941)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`common/symbolic/latex.cc` line 400 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-NbBC2bZ3gCfWlptGuIo:-NbCTrRX1adDXx5sHErd:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/06311832b78b6c43f5c2434b359978ba54fcc0be/common/symbolic/latex.cc#L400)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `constant` is misnamed here since the full expression is returned. Maybe `expr` or `product`?
</blockquote></details>

Done. 
___
*[`common/symbolic/test/latex_test.cc` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-NbBCKHN1k-Nb7wB38gA:-NbCUhYPBsb6mfjW24x9:beqnupw) ([raw file](https://github.com/RobotLocomotion/drake/blob/06311832b78b6c43f5c2434b359978ba54fcc0be/common/symbolic/test/latex_test.cc#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: these test only the easy cases. Most of the new code uses round() and fmod() and an epsilon to handle the tricky near-multiple cases. There should be unit tests here that exercise that code to make sure it is working as expected now and in the future.
</blockquote></details>

Done.  I felt I was already testing the round with the 14 and -7, etc.  But I've added a bit more for the fmod thresholds.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19941)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`common/symbolic/test/latex_test.cc` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19941#-NbBCKHN1k-Nb7wB38gA:-NbDJDMg6_ZTeJ2za4vu:b-6mhyx0) ([raw file](https://github.com/RobotLocomotion/drake/blob/06311832b78b6c43f5c2434b359978ba54fcc0be/common/symbolic/test/latex_test.cc#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I felt I was already testing the round with the 14 and -7, etc.  But I've added a bit more for the fmod thresholds.
</blockquote></details>

Great, thanks!

**Pull request merged**
