### PR TITLE
Updated bazel builds to use VTK 8.0

### PR DESCRIPTION
**Pull request by sankhesh**
New VTK packages for v8.0.0 and director packages against VTK 8.0

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6473)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6473#-:-KnogpDrixDHFa2HK59h:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@kunimatsu-tri and +@soonho-tri for feature review. Needs testing locally.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6473#-:-KnohhhXBjTUUrKuI7X6:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
> Needs testing locally.

FTR, my local testing was `bazel build install` and verify that something license-like (`Copyright.txt`) is installed. So that check box at least can be checked (which makes #6401 very happy :grinning:).

**Comment by soonho-tri** [comment]
:lgtm:

Works on my macs. @kunimatsu-tri , could you test it on a linux box?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6473#-:-Knoqs9Q_-3Z1OPdMArS:bvdwlhu)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

I tried two things on my local Trusty:

```
bazel test //drake/systems/sensors:rgbd_camera_test --compiler=gcc-4.9
```
and
```
bazel build install --compiler=gcc-4.9
```

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6473#-:-KnpKue_uL8eHOW5Nn-Z:b24uov2)*

**Pull request merged**
