### PR TITLE
Cleanup installation instructions and scripts

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7159)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review of `mac.rst`, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-:-KvSjDa7OTIHOMbZKHgB:b-arm59w)*

**Comment by jwnimmer-tri** [comment]
... and `setup/mac/install_preqs.sh` also of course.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-:-KvSjOIGrmiulrKxjz_h:bxler67)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-KvSimnYzEzA2aBl3Y0B:-KvSimnYzEzA2aBl3Y0C:b-vhrp4r) ([raw file](https://github.com/robotlocomotion/drake/blob/9c38fd273608a2ca4a98b616ad881bcecf6f0643/setup/ubuntu/16.04/install_prereqs.sh#L57)):*
> ```Shell
> if $install_cmake; then
>   apt install --no-install-recommends cmake cmake-curses-gui
> fi
> ```

The `developers.rst` still says that CMake is supported on Xenial.  Is there some other mechanism that will bring it in?  My initial though is that these stanzas should remain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-:-KvSjdFvHZ3Yi3olw4Gl:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-KvSimnYzEzA2aBl3Y0B:-KvSplAoWJ2vE0_VqwOJ:bd1ljhg) ([raw file](https://github.com/robotlocomotion/drake/blob/9c38fd273608a2ca4a98b616ad881bcecf6f0643/setup/ubuntu/16.04/install_prereqs.sh#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `developers.rst` still says that CMake is supported on Xenial.  Is there some other mechanism that will bring it in?  My initial though is that these stanzas should remain.
</blockquote></details>

I added a note in the text for now.  Documentation will be overhauled for the future state of the MATLAB bindings, probably next week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159)*

**Comment by soonho-tri** [comment]
:apple: :lgtm: 

---

Reviewed 2 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-:-KvSsLAJf3S0mxJ1LKEP:b-xrqx1z)*

**Comment by jwnimmer-tri** [comment]
SGTM.  Consider testing the `-unprovisioned-` builds pre-merge to forestall any `-nightly` hiccups.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159#-:-KvSuR3zKBKaBk_1eTL7:bvq655q)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7159)*

**Pull request merged**
