### PR TITLE
[C-IRIS] Add a public function to search for separation certificate for a given polytope.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484#-:-NJhtYBR8P1y23BnBupo:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Consider the change in design in https://reviewable.io/reviews/RobotLocomotion/drake/18485#- which would push the burden of collision filtering to your public method. We can talk offline about the design change.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484#-:-NJk3Fpy4csna__xKJxo:b-8csfpc)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJjh9cc6yNEsa4UltID:-NJjh9cc6yNEsa4UltIE:b1trwjx) ([raw file](https://github.com/robotlocomotion/drake/blob/4f94a00cc6adda7b8f79fe8d3e7c300dbfde005c/geometry/optimization/dev/cspace_free_polytope.h#L237)):*
> ```objc
>     // If backoff_scale is not empty, then after solving the problem with an
>     // optimal cost, we "back-off" the program to solve a feasibility program.
>     // Namely we remove the cost with a constraint cost(x) <= cost_upper_bound,
> ```

Nit: grammar "Namely we remove the cost and add the constraint...."
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 241 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJjhFey-EQQ02C79JtC:-NJjhFey-EQQ02C79JtD:b-7guu2x) ([raw file](https://github.com/robotlocomotion/drake/blob/4f94a00cc6adda7b8f79fe8d3e7c300dbfde005c/geometry/optimization/dev/cspace_free_polytope.h#L241)):*
> ```objc
>     // optimal_cost >= 0, and cost_upper_bound = (1 - backoff_scale) *
>     // optimal_cost if optimal_cost <= 0. This back-off technique is useful in
>     // bilinear alternation.
> ```

BTW: may be worth adding "This back-off technique is useful in bilinear alternations to ensure solutions in the strict interior of the set."

**Review by hongkai-dai — COMMENTED** [review]
I rebased the PR on top of #18485.

I also removed the public function `rationals_with_margin()` and `rationals_without_margin()`. @alexandreamice do you need to use these two functions in the public API? If you inherit from `CspaceFreePolytope` and need these two functions in the derived class, we can add these two functions as protected methods.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484#-:-NJlgPtI9xm8kpksnuOM:b-sbtgt0)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
I will likely make either those or the `GenerateRationals` function protected in the future. But we can take care of that when I get around to it. This seems to include some changes of #18485 but I have checked them off anyway.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484#-:-NJlnx-694pYobu1qR2y:b-sgh00a)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 366 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJlno2DEAN9Ycei-q-i:-NJlno2DEAN9Ycei-q-j:b-wahk4) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/cspace_free_polytope.h#L366)):*
> ```objc
>    free in the C-space region {s | C*s<=d, s_lower<=s<=s_upper}.
> 
>    @retval certificates certificates[i] is the separation certificate for the
> ```

nit: grammar "for the a" remove the word the
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 789 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJlu4D3-Cdv5RF3KyPP:-NJlu4D3-Cdv5RF3KyPQ:b-lf4ki3) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L789)):*
> ```cpp
> }
> 
> TEST_F(CIrisToyRobotTest, FindSeparationCertificateGivenPolytope1) {
> ```

I would change this test name to `SearchSeparationCertificateGivenCollisionFreePolytope`



_Code quote:_
```cpp
FindSeparationCertificateGivenPolytope1
```
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 798 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJlrGZW-7N7HwgF8t4R:-NJlrGZX4eq7EP6fR7OJ:b-qdi1sv) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L798)):*
> ```cpp
>   CspaceFreePolytopeTester tester(plant_, scene_graph_,
>                                   SeparatingPlaneOrder::kAffine, q_star);
>   const auto plane_geometries =
> ```

Is this still needed?
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 915 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltw4H75Bvvq9jAepJ:-NJltw4H75Bvvq9jAepK:bq59vb0) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L915)):*
> ```cpp
> }
> 
> TEST_F(CIrisToyRobotTest, FindSeparationCertificateGivenPolytope2) {
> ```

I would change this name to `SearchSeparationCertificateGivenPolytopeWithCollisions`.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 922 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltnmy9PH9AFO7enRA:-NJltnmy9PH9AFO7enRB:b-leyrbe) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L922)):*
> ```cpp
>                                   SeparatingPlaneOrder::kAffine, q_star);
> 
>   // This C-space polytope is collision free.
> ```

This polytope is NOT collision free
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 934 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltGzY0aWsePzmD4wf:-NJltGzY0aWsePzmD4wg:b-jzq8o) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L934)):*
> ```cpp
> 
>   VectorX<symbolic::Polynomial> d_minus_Cs;
>   std::unordered_set<int> C_redundant_indices;
> ```

Is this code needed?



_Code quote:_
```cpp
  VectorX<symbolic::Polynomial> d_minus_Cs;
  std::unordered_set<int> C_redundant_indices;
  std::unordered_set<int> s_lower_redundant_indices;
  std::unordered_set<int> s_upper_redundant_indices;
  SetupPolytope(tester, C, d, &d_minus_Cs, &C_redundant_indices,
                &s_lower_redundant_indices, &s_upper_redundant_indices);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 789 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJlu4D3-Cdv5RF3KyPP:-NJlvXFB4DGVSqFe5otN:b-nmlmjp) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L789)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would change this test name to `SearchSeparationCertificateGivenCollisionFreePolytope`
</blockquote></details>

Done. I think I want to highlight the name of the function under the test. This test is for the function `CspaceFreePolytope::FindSeparationCertificateGivenPolytope`. I just added `Success` at the end of the name to make it more clear.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 798 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJlrGZW-7N7HwgF8t4R:-NJlw-wUCgC8FAlwkF2K:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L798)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 915 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltw4H75Bvvq9jAepJ:-NJlw2Jl3P9_HrczluL0:b95o7r0) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L915)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would change this name to `SearchSeparationCertificateGivenPolytopeWithCollisions`.
</blockquote></details>

Done. I added `Failure` to the tester name.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 922 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltnmy9PH9AFO7enRA:-NJlw9gM0ZkpyWO9YUkz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L922)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This polytope is NOT collision free
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 934 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18484#-NJltGzY0aWsePzmD4wf:-NJlwMTlCxa6NOSvtppV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/651bd3a5414775a70193de60585d4ecfc3e1ba03/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L934)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Is this code needed?
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18484#-:-NJm-3kt4cQTj2ATVNHr:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
