### PR TITLE
Method for converting a type to double.

### PR DESCRIPTION
**Pull request by edrumwri**
Using @sherm1's beautiful piece of code, this PR permits converting an arbitrary type to double, if possible, thereby avoiding compiler errors. Autodiff's and doubles are converted to double types; all other types are currently converted to NaN's, allowing undesirable conversions to be identified.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4414)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@david-german-tri for feature review please (you've already looked at this code once) and +@sammy-tri for platform review (per rotation schedule) please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYPvLBJ9mhhu-qM2Kyx:bs4phrf)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/autodiff_overloads.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYPyZXT40S4tVtt_pqd:-KYPyZXT8C2ZdXDX5RWt:bdtgknh) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/autodiff_overloads.h#L142)):*
> ```objc
> /// This struct converts an object of type T to a double. The default
> /// implementation returns NaN. Overloads provide sensible conversions.
> /// Note that we do not expect to be running simulations while instantiated
> ```

Does this line about running simulations still make sense when this code isn't in simulator.h anymore?

---

*[drake/common/autodiff_overloads.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYPy9Ru-np6JAdo4Nt1:-KYPy9RvDzISwqYuUfVs:bk2610n) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/autodiff_overloads.h#L149)):*
> ```objc
> struct TtoDouble {
>   static double convert(const T&) {
>     return std::numeric_limits<double>::quiet_NaN();
> ```

BTW I'm not 100% sure I love this default (as opposed to aborting or something?) since it can be a PITA to track down where a NaN got introduced into your state.  I don't think my opinion is strong enough (or likely to be common enough) to hold up the PR over it.  Also it was already there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/autodiff_overloads_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYQ7ocv7E7fnD9-RRd3:-KYQ7ocv8y-vLFnVptcu:bvz2qo3) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/test/autodiff_overloads_test.cc#L27)):*
> ```cpp
> 
>   double y = 0.0;
>   EXPECT_EQ(TtoDouble<double>::convert(y), 0.0);
> ```

BTW, I suggest using a value other than 0 here and above since there *could* be a bug where the thing always returns 0, but one that returns some other values would be unlikely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414)*

**Comment by edrumwri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/autodiff_overloads.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYPyZXT40S4tVtt_pqd:-KYQAABHARW74MUs8Di5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/autodiff_overloads.h#L142)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this line about running simulations still make sense when this code isn't in simulator.h anymore?
</blockquote></details>

Done.

---

*[drake/common/autodiff_overloads.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYPy9Ru-np6JAdo4Nt1:-KYQ5epRAVuQKiVm0vj3:b3wgsmo) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/autodiff_overloads.h#L149)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm not 100% sure I love this default (as opposed to aborting or something?) since it can be a PITA to track down where a NaN got introduced into your state.  I don't think my opinion is strong enough (or likely to be common enough) to hold up the PR over it.  Also it was already there.
</blockquote></details>

We actually discussed just this thing. I've added in a DRAKE_ABORT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414)*

**Comment by edrumwri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/autodiff_overloads_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYQ7ocv7E7fnD9-RRd3:-KYQBycG91c6mDbQxS37:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a400ed49c1187cf81ef2ee0401e45786fc48ec52/drake/common/test/autodiff_overloads_test.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I suggest using a value other than 0 here and above since there *could* be a bug where the thing always returns 0, but one that returns some other values would be unlikely.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQCanK6rDc4ImHPu8N:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:, one BTW.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/autodiff_overloads.h, line 162 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-KYQJ-s69T6dj6HseoHC:-KYQJ-s6CS8siHtW5tYV:b-iklb9v) ([raw file](https://github.com/robotlocomotion/drake/blob/6af1aa29dbd86995ce0a3612b558c06a2a3a1c38/drake/common/autodiff_overloads.h#L162)):*
> ```objc
> };
> 
> // Specializations for floating types.
> ```

BTW, should be a doxygen comment I think (I'm not clear on what doxygen does with specialization though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQJEfh98SVd9G7vNXW:bwiev48)*

**Comment by jwnimmer-tri** [comment]
Shouldn't the base type go in common/double_overloads.h?

**Comment by david-german-tri** [comment]
> Shouldn't the base type go in common/double_overloads.h?

I thought you were joking, but then I discovered that's actually a file.  So, I guess I agree.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQMfCWDncJPHTAbJ-8:be41ho5)*

**Comment by sherm1** [comment]
That would introduce several headers into double_overloads.h from which it is currently mercifully free. Either place works for me.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQQTZkEuH2y9KMBK5N:bnvm4bq)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot retest linux-gcc-experimental-matlab please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQXfAw4a5JLsLC6lhO:bohf287)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4414#-:-KYQYKt57CRMZvcCPtNu:bzdwe9o)*

**Comment by jwnimmer-tri** [comment]
> That would introduce several headers into double_overloads.h from which it is currently mercifully free. Either place works for me.

Why?  The `double` stuff goes in `double_overloads.h` and the autodiff specialization of the type stays in `autodiff_overloads.h`.

Also, I'm not sure why we prefer to delay type errors to runtime (the abort).  My instinct is that writing this in a way that fails at compile-time should be trivial?

**Comment by sherm1** [comment]
> My instinct is that writing this in a way that fails at compile-time should be trivial?

My original intention for this class was that it should prevent compilation failures upon instantiation with *any* scalar type. I was trying to avoid instantiation failures of a large block of code caused by an operation in some tiny feature that would not likely be used by a non-computational scalar instantiation. Originally I used it for the real time slowdown clock (inherently `double`) in the simulator which is not used unless someone asks for it; that's something a `Simulator<SymbolicExpression>` is unlikely to request. If we're wrong and someone uses it inappropriately, they get a runtime error. It avoids baroque template specialization or SFINAE code that would otherwise be required.

So I think this is a useful class, but in keeping with @jwnimmer-tri's point we should use it judiciously, and review uses suspiciously.

**Comment by sherm1** [comment]
> The double stuff goes in double_overloads.h and the autodiff specialization of the type stays in autodiff_overloads.h.

Then split the test cases into two files also? Makes sense in theory but seems overly pedantic to me.

**Pull request merged**
