### PR TITLE
Require size_t and ptrdiff_t to be used without std:: prefix

### LINKED ISSUE #2374: Allow `size_t` and `ptrdiff_t` to be used without explicit `std::` namespace
`size_t` and `ptrdiff_t` are related standard types defined in C and C++ and are very useful. In Drake we frequently use `size_t` without the `std::` qualifier (which I think is a good idea). `ptrdiff_t` is used less often but should be written the same way as `size_t`. (That is, we are writing them as though they were in the global namespace.)

For a long discussion, see [stackoverflow](http://stackoverflow.com/questions/5813700/difference-between-size-t-and-stdsize-t). Bottom line is that the C++ standard says `<cstddef>` *must* define `std::size_t`, `std::ptrdiff_t` and certain other types, and *may* define `::size_`t, `::ptrdiff_t` etc. and if so those *must* be identical to the `std::` definitions. Apparently all compilers actually do that, because they implement `<cstddef>` by including `<stddef.h>`, which is obligated to define `::size_t` and so on. (That's why Drake works now.) So, like `#pragma once` there are hypothetical problems, but this will work in practice and would save us a lot of ugly `std::` pollution. And ... if it ever failed we could just add `using size_t = std::size_t;` to a common header.

I propose that we expressly allow unqualified `size_t` and `ptrdiff_t`. Thoughts?

(Discussion moved from PR #2370)

### PR DESCRIPTION
**Pull request by sherm1**
Add to coding style a rule saying that `size_t` and `ptrdiff_t` shall be used *without* the `std::` prefix.

Resolves #2374.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2382) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by sherm1** [comment]
Reviews please: +@liangfok feature, +@jwnimmer-tri platform

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> #### Require size\_t and ptrdiff\_t to be used without std:: prefix
> 
> Add to coding style a rule saying that `size_t` and `ptrdiff_t` shall be used *without* the `std::` prefix.
> 
> 
> 
> Resolves #2374.
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382#-:-KHzWD4aq6Ym9J0GyLHm:729537453)*

**Comment by liangfok** [comment]
Just left one consider comment. Otherwise, :lgtm_strong: 

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Reviews please: +@liangfok feature, +@jwnimmer-tri platform</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2382#-KHzYw-t9Fqc019kD5J9:-KHzYw-t9Fqc019kD5JA:995127339) ([raw file](https://github.com/robotlocomotion/drake/blob/f09e6ddafa85ca7b64bce6f7b914ba3804665486/drake/doc/code_style_guide.rst#L72)):*
> ```reStructuredText
> * After including ``<cstddef>``, assume that ``size_t`` and ``ptrdiff_t``
>   are defined in the global namespace. Do not preface them
>   with ``std::`` and do not write ``using std::size_t``. There is a
> ```

Consider changing:

> do not write ``using std::size_t``

to be:

> do not write ``using std::size_t`` or ``using std::ptrdiff_t`` in your code.

Just to be clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382#-:-KHzZgWeWOvVpdliLBnk:-1056019544)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2382#-KHzYw-t9Fqc019kD5J9:-KHzfeBU-OCkD9qq7Af8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f09e6ddafa85ca7b64bce6f7b914ba3804665486/drake/doc/code_style_guide.rst#L72)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Consider changing:
> 
> > do not write ``using std::size_t``
> 
> to be:
> 
> > do not write ``using std::size_t`` or ``using std::ptrdiff_t`` in your code.
> 
> Just to be clear.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Just left one consider comment. Otherwise, :lgtm_strong: </details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2382#-:-KI-7fUiJcfcEmL6dsPY:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge for out-of-date-with-master.

**Comment by liangfok** [comment]
Strange. I was just assigned this PR, which was merged 2 months ago.

**Pull request merged**
