### PR TITLE
MovingAverageFilter

### PR DESCRIPTION
**Pull request by naveenoid**
Moves from examples/kuka_iiwa_arm/dev/tools to manipulation/utils and replaces the template specialization on Array3d with VectorX<double>. Unit tests cover this mod.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6689)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@ericcousineau-tri for feature review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-:-Kq4Usf-Sx5zAvoW9XF8:b-7eskas)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items. Thanks!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/manipulation/util/moving_average_filter.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4YQu-1kM3LvWtpwQl:-Kq4YQu-1kM3LvWtpwQm:bk3ik0r) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.cc#L11)):*
> ```cpp
> namespace {
> 
> size_t get_dimensions(double data) { return 1; }
> ```

nit Could you use `int` here?

---

*[drake/manipulation/util/moving_average_filter.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4Y0Pk_LC2GGWz3PgN:-Kq4Y0Po-HNmczgom8h_:b3bo268) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.cc#L17)):*
> ```cpp
> 
> template <typename T>
> MovingAverageFilter<T>::MovingAverageFilter(unsigned int window_size)
> ```

nit Style guide mentions that we should used signed integers, even for sizes, unless it is used to simplify casting in loops or something like that:
http://drake.mit.edu/code_style_guide.html#clarifications

---

*[drake/manipulation/util/moving_average_filter.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4ZTbrMoigLcRgWyPk:-Kq4ZTbsbyIgWdP4b_s5:b-2f31ah) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.h#L16)):*
> ```objc
>  * The implementation of a Moving Average Filter. This discrete time filter
>  * outputs the average of the last n samples i.e.
>  *  y(k) = 1/n ∑ⱼ x(k-j) ∀ j = 0..n-1, when n<k and,
> ```

nit Since this discrete, would it make things more consistent with thins like `LinearSystem` to use square-bracket indexing, `x[k-j]`?

---

*[drake/manipulation/util/moving_average_filter.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4YrRIvmIxJKSljltk:-Kq4YrRIvmIxJKSljltl:bl7kkoo) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.h#L50)):*
> ```objc
>    * @return
>    */
>   T Compute(const T& new_data);
> ```

nit Rather than `Compute`, could we use `Update` to have consistent filter terminology?

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4_-JrqPEZnYX_Umti:-Kq4_-JrqPEZnYX_Umtj:bl2t6fv) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L20)):*
> ```cpp
> GTEST_TEST(MovingAverageFilterTest, InstantiationTest) {
>   std::unique_ptr<MovingAverageFilter<double>> ma_filter1, ma_filter2;
>   EXPECT_NO_THROW(ma_filter1 =
> ```

nit No need for `unique_ptr<>` here?

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4Zs8z60giU8EmVRR1:-Kq4Zs8z60giU8EmVRR2:b-c75jny) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L27)):*
> ```cpp
> 
> GTEST_TEST(MovingAverageDoubleTest, ComputeTest) {
>   auto filter = std::make_unique<MovingAverageFilter<double>>(kWindowSize);
> ```

nit Is there a reason for making this a `unique_ptr`, rather than a stack-based object?

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4ZfU6MlLt4oJM9PFv:-Kq4ZfU7-xdSwCuqRt4d:bag1cc3) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L28)):*
> ```cpp
> GTEST_TEST(MovingAverageDoubleTest, ComputeTest) {
>   auto filter = std::make_unique<MovingAverageFilter<double>>(kWindowSize);
>   std::vector<double> window;
> ```

BTW Could you use a brace initializer here? `std::vector<double> window = {-4.5, 1.0, 21.6};`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-:-Kq4_RBrDgj03pdJxqW_:b-lte0wg)*

**Comment by naveenoid** [comment]
+@ggould-tri for platform review

---

Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/manipulation/util/moving_average_filter.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4YQu-1kM3LvWtpwQl:-Kq4akq3saFdhwOWxdwv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.cc#L11)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Could you use `int` here?
</blockquote></details>

Done.

---

*[drake/manipulation/util/moving_average_filter.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4Y0Pk_LC2GGWz3PgN:-Kq4alJ9pdEFo-XVxHmY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.cc#L17)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Style guide mentions that we should used signed integers, even for sizes, unless it is used to simplify casting in loops or something like that:
http://drake.mit.edu/code_style_guide.html#clarifications
</blockquote></details>

Done.

---

*[drake/manipulation/util/moving_average_filter.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4ZTbrMoigLcRgWyPk:-Kq4apgmsbLePh9wijXM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.h#L16)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Since this discrete, would it make things more consistent with thins like `LinearSystem` to use square-bracket indexing, `x[k-j]`?
</blockquote></details>

Done.

---

*[drake/manipulation/util/moving_average_filter.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4YrRIvmIxJKSljltk:-Kq4arodSjvXeFYKIzFU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/moving_average_filter.h#L50)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Rather than `Compute`, could we use `Update` to have consistent filter terminology?
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4_-JrqPEZnYX_Umti:-Kq4dLxpDr4fbt3f0558:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit No need for `unique_ptr<>` here?
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4Zs8z60giU8EmVRR1:-Kq4ddelbh_SsHvGg_ne:bbaxkzg) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L27)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Is there a reason for making this a `unique_ptr`, rather than a stack-based object?
</blockquote></details>

No reason :) Changing now.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq4ZfU6MlLt4oJM9PFv:-Kq4dcwF6Gr1HUdKOEgx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9b051bd88e417fd9364b8f3d4ffbca1665c2fb6/drake/manipulation/util/test/moving_average_filter_test.cc#L28)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you use a brace initializer here? `std::vector<double> window = {-4.5, 1.0, 21.6};`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-:-Kq4f4x1PUX3gu0uE2vc:b-gbk9vg)*

**Comment by ggould-tri** [comment]
:lgtm: pending issues below.

---

Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/manipulation/util/moving_average_filter.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8LiYK5i8fGM6saMRE:-Kq8LiYK5i8fGM6saMRF:bomrw4l) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/moving_average_filter.cc#L38)):*
> ```cpp
>   window_.push(new_data);
> 
>   if (window_.size() > (unsigned int)window_size_) {
> ```

Use `static_cast<>` instead of C-style cast.  Also use `size_t` -- that's the documented return type of `std::queue.size()` and it equals `unsigned int` only by accident.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8MYGkpzfho3IMLr3R:-Kq8MYGkpzfho3IMLr3S:bsm17jc) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/test/moving_average_filter_test.cc#L51)):*
> ```cpp
>   sum.setZero();
> 
>   // output represents moving average.
> ```

BTW Please capitalize this complete sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-:-Kq8MmtDf1TevyFRpg4f:br5rejv)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/manipulation/util/moving_average_filter.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8LiYK5i8fGM6saMRE:-Kq8f27tp9zkAnX2w9yl:b4chp1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/moving_average_filter.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Use `static_cast<>` instead of C-style cast.  Also use `size_t` -- that's the documented return type of `std::queue.size()` and it equals `unsigned int` only by accident.
</blockquote></details>

BTW @ggould-tri The GSG guide mentions being able to use brace initialization for conversion of arithmetic types:
`if (window_.size() > size_t{window_size_}) {`

Would that be permissible? (This is a tad more aesthetic to me than `static_cast<...>(...)`.)

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8af7_1LvSNGW1wMts:-Kq8af7anVegQoTZ5W2F:b-9n99t6) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/test/moving_average_filter_test.cc#L19)):*
> ```cpp
> 
> GTEST_TEST(MovingAverageFilterTest, InstantiationTest) {
>   EXPECT_NO_THROW(MovingAverageFilter<double> ma_filter1(2));
> ```

nit Rather than declare an object, could you just construct one?
`EXPECT_NO_THROW(MovingAverageFilter<double>(2));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/manipulation/util/moving_average_filter.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8LiYK5i8fGM6saMRE:-Kq8mVYb8X6tzBLS9xp1:bx9t4u7) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/moving_average_filter.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW @ggould-tri The GSG guide mentions being able to use brace initialization for conversion of arithmetic types:
`if (window_.size() > size_t{window_size_}) {`

Would that be permissible? (This is a tad more aesthetic to me than `static_cast<...>(...)`.)
</blockquote></details>

I had no idea that was even a thing for numerics.  I learn something new every day.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689)*

**Comment by naveenoid** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/moving_average_filter.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8LiYK5i8fGM6saMRE:-Kq8pBUDCi6cOxqC1a3b:bq3r2vp) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/moving_average_filter.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I had no idea that was even a thing for numerics.  I learn something new every day.
</blockquote></details>

Done. Only the static cast worked. The brace conversion threw a compile error.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8af7_1LvSNGW1wMts:-Kq8p2x3cxiUp3U-9Cxu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/test/moving_average_filter_test.cc#L19)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Rather than declare an object, could you just construct one?
`EXPECT_NO_THROW(MovingAverageFilter<double>(2));`
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/moving_average_filter_test.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6689#-Kq8MYGkpzfho3IMLr3R:-Kq8rkMDQLwKGYa5xoHI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f6f6b9d651c5887f37ccbeb97f07471cb22426e5/drake/manipulation/util/test/moving_average_filter_test.cc#L51)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW Please capitalize this complete sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 8 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6689)*

**Pull request merged**
