### PR TITLE
Allow transmogrification to AutoDiffXd

### PR DESCRIPTION
**Pull request by david-german-tri**
For Systems and Contexts.  Use it for Pendulum as a motivating example.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3967)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Still working on tests for this.  Posted it early so that interested parties could patch it.

**Comment by sherm1** [comment]
Looks good!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-:-KVS4LIQL6XaFa06ISWw:b-vs1prh)*

**Comment by david-german-tri** [comment]
+@russtedrake for feature review, +@sammy-tri for platform review, -(status: do not merge) , -(status: do not review) 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-:-KVaVLhbuHaRRF7FuIzo:b-rh1bb2)*

**Comment by RussTedrake** [comment]
:lgtm: 

---

Reviewed 6 of 10 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/eigen_autodiff_types.h, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe578puhgxDiNb5rJa:-KVe578qryKJ-Cm0kJ83:b-5akjkd) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/common/eigen_autodiff_types.h#L40)):*
> ```objc
> static_assert(std::is_same<AutoDiffXd, TaylorVarXd>::value,
>               "AutoDiffXd and TaylorVarXd should be two different names "
>               "for the same type.");
> ```

i think we can just comb through and remove TaylorVarXd.  

---

*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVe5GRW4bm-iS4UeBDt:b-tfi2kz) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
> ```objc
> 
>   // System<T> override.
>   PendulumPlant<AutoDiffXd>* DoToAutoDiffXd() const override;
> ```

:ok: just don't love the name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-:-KVe69nuX_OoMSDcAZDI:bg7igkv)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_autodiff_types.h, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe578puhgxDiNb5rJa:-KVeZiu2uPvBldujZayC:bfbly1r) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/common/eigen_autodiff_types.h#L40)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i think we can just comb through and remove TaylorVarXd.  
</details>
Opened #4013.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVeZnMrP4XBoTXjzMQB:b-d527m) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> :ok: just don't love the name. 
</details>
I agree, it's a little awkward, but it's consistent with our convention for other NVI.  We could consider "ConvertToAutoDiffXd" and "DoConvertToAutoDiffXd".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVea25JfhjOZKuoE8aR:b-cdjxrg) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I agree, it's a little awkward, but it's consistent with our convention for other NVI.  We could consider "ConvertToAutoDiffXd" and "DoConvertToAutoDiffXd".
</details>
FYI The `maliput` work is also struggling with the `Foo` / `DoFoo` naming pattern for NVI. 

@david-german-tri Did the framework authors folks consider `Foo` and `FooImpl` as an alternative pattern?  It seems to me like it would read better for a wider variety of `Foo`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 10 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/modal_state.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVecsxsLRhs2vDnB626:-KVecsxtYgHMN-v7Xxdo:bdrjjlt) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/systems/framework/modal_state.cc#L39)):*
> ```cpp
> 
> void ModalState::CopyFrom(const ModalState& other) {
>   DRAKE_ASSERT(size() == other.size());
> ```

BTW not clear why this changed from DEMAND  to ASSERT when DifferenceState:SetFromGeneric remained as DEMAND.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-:-KVeeTa0mcvrdNE9CCw4:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVegNH2Iqq6IcpwmRZr:bqwx174) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI The `maliput` work is also struggling with the `Foo` / `DoFoo` naming pattern for NVI. 
> 
> @david-german-tri Did the framework authors folks consider `Foo` and `FooImpl` as an alternative pattern?  It seems to me like it would read better for a wider variety of `Foo`.
</details>
I went with `Do` because @sherm1 recommended it, not for any deep reason.  I like `Impl` marginally better, but not enough to want to churn it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967)*

**Comment by david-german-tri** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/modal_state.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVecsxsLRhs2vDnB626:-KVejwA_F7KeumOJDZdQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/systems/framework/modal_state.cc#L39)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW not clear why this changed from DEMAND  to ASSERT when DifferenceState:SetFromGeneric remained as DEMAND.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967)*

**Comment by sherm1** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVel_6Zf4q8khPuD6OS:b6otcm0) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I went with `Do` because @sherm1 recommended it, not for any deep reason.  I like `Impl` marginally better, but not enough to want to churn it.
</details>
Funny -- I thought we were using `Do` because *you* preferred it, David! I hadn't used that before. `Impl` would be fine too but I think any strictly-adhered-to pattern makes NVI easier and `Do` seems adequate to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967)*

**Comment by david-german-tri** [comment]
I've checked locally that this does not explode post RBT<T>.  Merging without further CI.

---

Review status: 12 of 14 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/examples/Pendulum/pendulum_plant.h, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-KVe5GRV870d7F9nAmC6:-KVfCTuIeTmlq9T1FlZO:bakxsaq) ([raw file](https://github.com/robotlocomotion/drake/blob/982715c5da1c8cbf33c93a9dd67ddae5c877db6d/drake/examples/Pendulum/pendulum_plant.h#L77)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Funny -- I thought we were using `Do` because *you* preferred it, David! I hadn't used that before. `Impl` would be fine too but I think any strictly-adhered-to pattern makes NVI easier and `Do` seems adequate to me.
</details>
Ha, oops.  I'm going to leave this as-is and merge; it will be trivial to `perl -pie` in a separate PR if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3967#-:-KVfCffWlhpeRScQxCCK:but7v0i)*

**Comment by amcastro-tri** [comment]
Late to the party. I just wanted to add my two cents; great work! I like this API.

**Pull request merged**
