### PR TITLE
[InverseKinematics] Add upper bound on the minimum distance.

### PR DESCRIPTION
**Pull request by hongkai-dai**
We can enforce the constraint that the minimum distance is below a certain threshold.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-:-NZWutHI33lFoKh_83P7:b-7vq6ss)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 130 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWwZej4QBvGtFLZmmn:-NZWwZej4QBvGtFLZmmo:b-8gqtua) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/minimum_distance_constraint.h#L130)):*
> ```objc
>   Constructs the constraint using MultibodyPlant<AutoDiffXd>. lower <=
>   min(distance) <= upper.
>   @pydrake_mkdoc_identifier{autodiff_with_upper_bound}
> ```

put the details about "if upper is finite, then ..." here too?
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWxMY09q6jsOrQHAwP:-NZWxMY09q6jsOrQHAwQ:b-jovk8t) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/minimum_distance_constraint.cc#L72)):*
> ```cpp
>         "MinimumDistanceConstraint: influence_distance must be finite.");
>   }
>   if (std::isfinite(minimum_distance_lower) &&
> ```

i don't think you need the isfinite check for the lower... (and you haven't documented it).
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWxsPtDcufGwYzmySt:-NZWxsPtDcufGwYzmySu:b-yck0ze) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L37)):*
> ```cpp
>       num_constraints++;
>       lower_bound_expected.push_back(-kInf);
>       upper_bound_expected.push_back(1);
> ```

this logic seems surprising... if it's correct probably worth documenting it?  i see "if finite, then expected -kInf".  I would think it it's finite, then you'd expect finite? 

same for the upper just below.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 105 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWyf003hJYb7rhW-T2:-NZWyf003hJYb7rhW-T3:bluosf3) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L105)):*
> ```cpp
>     EXPECT_LE(y_double(0), constraint.upper_bound()(0));
>     EXPECT_FALSE(y_double(1) >= constraint.lower_bound()(1) &&
>                  y_double(1) <= constraint.upper_bound()(1));
> ```

why GE, LE then switch to this?  I would think you could use GE, LE again here..
___
*[`solvers/minimum_value_constraint.cc` line 269 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZX-yaR35mm9xrBjg9U:-NZX-yaR35mm9xrBjg9V:bgxtsa7) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L269)):*
> ```cpp
>   // is a non-constraint. Return zero for the lower bound constraint, and 2 for
>   // the upper bound constraint.
>   if (max_num_values_ == 0) {
> ```

btw -- in trying to understand this, I just saw that the max_num_values() class method (in the header) returns a double instead of an int.  Maybe you can fix that here, too?
___
*[`solvers/minimum_value_constraint.cc` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzTfHCEpKE5dslibX:-NZWzTfHCEpKE5dslibY:b-ur3whf) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L272)):*
> ```cpp
>     if (y_lower_index >= 0) {
>       // The upper bound is 1. Set the value to 0 that guarantees to satisfy the
>       // constraint.
> ```

grammar:  => "Set the value to 0 to guarantee that the constraint is satisfied."

same below.
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 470 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzLOh1oLH55e3OEnV:-NZWzLOh1oLH55e3OEnW:b-ecx4nm) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/bindings/pydrake/multibody/inverse_kinematics_py.cc#L470)):*
> ```cpp
>             py::keep_alive<1, 2>(),
>             // Keep alive, reference: `self` keeps `plant_context` alive.
>             py::keep_alive<1, 4>(), cls_doc.ctor.doc_autodiff_no_upper_bound);
> ```

Why not bind the new constructors here, too?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 130 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWwZej4QBvGtFLZmmn:-NZX5Er9686sFEYqrStb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/minimum_distance_constraint.h#L130)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

put the details about "if upper is finite, then ..." here too?
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWxMY09q6jsOrQHAwP:-NZX5azh3tZ6d7LOoKQ5:b4dggn1) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/minimum_distance_constraint.cc#L72)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think you need the isfinite check for the lower... (and you haven't documented it).
</blockquote></details>

Done. I removed isfinite check.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWxsPtDcufGwYzmySt:-NZX7txe3nTDZxHYWH_C:b8lloxe) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this logic seems surprising... if it's correct probably worth documenting it?  i see "if finite, then expected -kInf".  I would think it it's finite, then you'd expect finite? 

same for the upper just below.
</blockquote></details>

Done.

Yeah it is quite confusing.

We impose the minimum value constraint using a smooth max function (because the penalty function we choose is monotonically decreasing). Hence it has a finite upper bound for minimum_distance_lower, and a finite lower bound for minimum_distnace_upper. I added the documentation.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 105 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWyf003hJYb7rhW-T2:-NZX8EAQ4Z8CA0zxzq8L:b-ogqmpx) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L105)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why GE, LE then switch to this?  I would think you could use GE, LE again here..
</blockquote></details>

I want to say `y_double(1)` is NOT in the range of `[constraint.lower_bound()(1), constraint.upper_bound()(1)]`. I don't know how to do this with `GE` and `LE`.
___
*[`solvers/minimum_value_constraint.cc` line 269 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZX-yaR35mm9xrBjg9U:-NZX8bQJ1BeVriAL8799:bu9gagv) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L269)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- in trying to understand this, I just saw that the max_num_values() class method (in the header) returns a double instead of an int.  Maybe you can fix that here, too?
</blockquote></details>

Done. Thanks for catching this!
___
*[`solvers/minimum_value_constraint.cc` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzTfHCEpKE5dslibX:-NZX8vw_7b97e1yNxtQ8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L272)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

grammar:  => "Set the value to 0 to guarantee that the constraint is satisfied."

same below.
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 470 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzLOh1oLH55e3OEnV:-NZX8wnY-kS5QhYncBhY:b-wqksv) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/bindings/pydrake/multibody/inverse_kinematics_py.cc#L470)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Why not bind the new constructors here, too?
</blockquote></details>

That would require me finishing the python binding of MinimumValuePenaltyFunction, as we discussed in the slack channel. I am working on the python binding in a separate branch.

Since python binding is not on the critical path to get use this feature in IRIS (I have another dev branch in C++ to add IrisInConfigurationSpace to use this MinimumDistanceConstraint), I would hope to land this PR as soon as possible to enable the new IRIS feature. What do you think?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWxsPtDcufGwYzmySt:-NZXQ__Z756b5rD44iwz:b-pta11b) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.

Yeah it is quite confusing.

We impose the minimum value constraint using a smooth max function (because the penalty function we choose is monotonically decreasing). Hence it has a finite upper bound for minimum_distance_lower, and a finite lower bound for minimum_distnace_upper. I added the documentation.
</blockquote></details>

I see.  Thanks!
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 105 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWyf003hJYb7rhW-T2:-NZXQx9d51x4WdHlrlHV:b5tecqx) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I want to say `y_double(1)` is NOT in the range of `[constraint.lower_bound()(1), constraint.upper_bound()(1)]`. I don't know how to do this with `GE` and `LE`.
</blockquote></details>

I see; I missed that on the first read.  Withdrawn.
___
*[`solvers/minimum_value_constraint.cc` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzTfHCEpKE5dslibX:-NZXRE4SAgh3oP_-54yd:b-2vim4l) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L272)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: constraint is spelled wrong x2.  
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 470 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzLOh1oLH55e3OEnV:-NZXRLQqBAU_yoCvrIau:b422jm0) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/bindings/pydrake/multibody/inverse_kinematics_py.cc#L470)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That would require me finishing the python binding of MinimumValuePenaltyFunction, as we discussed in the slack channel. I am working on the python binding in a separate branch.

Since python binding is not on the critical path to get use this feature in IRIS (I have another dev branch in C++ to add IrisInConfigurationSpace to use this MinimumDistanceConstraint), I would hope to land this PR as soon as possible to enable the new IRIS feature. What do you think?
</blockquote></details>

right.  i saw the slack after completing my review.  find to skip it here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/minimum_value_constraint.cc` line 272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZWzTfHCEpKE5dslibX:-NZXWntI-DfzEw91QKBg:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/020989c80152eac08770089f314717a66064607a/solvers/minimum_value_constraint.cc#L272)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: constraint is spelled wrong x2.  
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-:-NZXz9WdBQmjSnJSqQK-:bg7igk9)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by SeanCurtis-TRI** [comment]
+@SeanCurtis-TRI for platform review.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth a couple of small things.

> Reviewed 1 of 5 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-:-NZYBK7CBK9PE4pkZlxC:bhuqqxp)* status: 7 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY6qcu5t3Fl0KlMCff:-NZY6qcu5t3Fl0KlMCfg:b-qrf9xs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.h#L55)):*
> ```objc
> minimum distance lb, and the minimal distance is no larger than a specified ub.
> This constraint should be bound to decision variables corresponding to the
> configuration vector, q, of the associate MultibodyPlant.
> ```

nit typo



_Suggestion:_
```objc
of the associated MultibodyPlant
```
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 14 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY7ijJ8P5ftKTT4Brr:-NZY7ijJ8P5ftKTT4Brs:b-ygmo2a) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L14)):*
> ```cpp
> namespace multibody {
> using internal::RefFromPtrOrThrow;
> const double kInf = std::numeric_limits<double>::infinity();
> ```

nit: Better in an anonymous namespace. It matters more in library code than terminal binary code.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 72 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY85flDK7vb1mdAqHM:-NZY85flDK7vb1mdAqHN:b-ccvirh) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L72)):*
> ```cpp
>         "MinimumDistanceConstraint: influence_distance must be finite.");
>   }
>   if (influence_distance <= minimum_distance_lower) {
> ```

BTW: If `minimum_distance_lower` is `NaN`, this condition won't trigger. While it will get caught in the creation of the `MinimumValueConstraint`, that error message won't talk about the `MinimumDistanceConstraint`, so it might be better if this constraint took ownership of its own test so it can label it accordingly.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 74 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY824h3NIjr7SGElS4:-NZY824h3NIjr7SGElS5:b-rb45v9) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L74)):*
> ```cpp
>   if (influence_distance <= minimum_distance_lower) {
>     throw std::invalid_argument(
>         "MinimumDistanceConstraint: influence_distance must be "
> ```

nit: As with the minimum value constraint, it would be good if you printed out the offending values (here and below).
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 119 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY8vOj9TVv-_biztHY:-NZY8vOj9TVv-_biztHZ:b-pfagbn) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L119)):*
> ```cpp
>                                 influence_distance_offset + minimum_distance) {}
> 
> namespace {
> ```

BTW When you put `kInf` in the anonymous namespace, might be nice to consolidate this with that at the top of the file.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY92SR7Sz3JHfyqo7g:-NZY92SR7Sz3JHfyqo7h:b5heig1) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L13)):*
> ```cpp
> namespace drake {
> namespace multibody {
> const double kInf = std::numeric_limits<double>::infinity();
> ```

BTW: Again, anonymous namespace.  `kNumPositionsForTwoFreeBodies` as well. Admittedly, this compiles to a binary, so symbol collision risk is incredibly low. Still a good habit to get into.
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 452 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYB1TvE3Wi-kwtaIDP:-NZYB1TvE3Wi-kwtaIDQ:bpn9q56) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/bindings/pydrake/multibody/inverse_kinematics_py.cc#L452)):*
> ```cpp
>             py::keep_alive<1, 2>(),
>             // Keep alive, reference: `self` keeps `plant_context` alive.
>             py::keep_alive<1, 4>(), cls_doc.ctor.doc_double_no_upper_bound)
> ```

BTW Presumably the new bindings will come later?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: 1 unresolved discussion, missing label for release notes

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 72 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY85flDK7vb1mdAqHM:-NZYXndD7pDAYd1N90Mx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L72)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW: If `minimum_distance_lower` is `NaN`, this condition won't trigger. While it will get caught in the creation of the `MinimumValueConstraint`, that error message won't talk about the `MinimumDistanceConstraint`, so it might be better if this constraint took ownership of its own test so it can label it accordingly.
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 74 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZY824h3NIjr7SGElS4:-NZYXoyE7NjWR-AAJhvR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/multibody/inverse_kinematics/minimum_distance_constraint.cc#L74)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As with the minimum value constraint, it would be good if you printed out the offending values (here and below).
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 452 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYB1TvE3Wi-kwtaIDP:-NZYYfDq8hiZhojd5LXG:b-g5n00w) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf4fb98189b42d0c77e3836d4ae98d3c96d4f5c/bindings/pydrake/multibody/inverse_kinematics_py.cc#L452)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Presumably the new bindings will come later?
</blockquote></details>

Yes I have a separate branch on the binding. I want to land this PR quickly so I put the binding in a different branch.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: 2 unresolved discussions

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 269 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYkCzjDQMA8CDCOM6O:-NZYjdSw9WfPwoM1ubEE:bz02yqw) ([raw file](https://github.com/RobotLocomotion/drake/blob/44668007173b4c44027c2a0209093d101c5a58cf/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L269)):*
> ```cpp
>       MinimumDistanceConstraint(plant_double_, 0.1, plant_context_double_, {},
>                                 0.0),
>       "MinimumDistanceConstraint: influence_distance=0.1, must be larger than "
> ```

BTW As I was looking at your CI failure, I realized that the error message isn't necessarily 100% aligned with the public API.

If I use a constructor that provides `influence_distance_offset`, what I get printed is `influence_distance`. I wonder if that might not be confusing; the user will *not* see the parameter they're passing in.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 274 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYkR6W8A3fGBmW1Aej:-NZYgDvL9GXv32YHzFcE:b-z5b1xt) ([raw file](https://github.com/RobotLocomotion/drake/blob/44668007173b4c44027c2a0209093d101c5a58cf/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L274)):*
> ```cpp
>       MinimumDistanceConstraint(plant_double_, 0.1, plant_context_double_, {},
>                                 -0.1),
>       "MinimumDistanceConstraint: influence_distance=0, must be larger than "
> ```

This is the cause of your CI failure. In focal, "0" is being formatted as "0.0". This is the pitfall of attempting to match an error message *exactly*. It's a bit fraught. That said, I'm in favor of the effort because your *intent* is to communicate certain information back, and you want the test to confirm you've done that. So, you have two options:

1. Instead of an `influence_distance_offset` value of  -0.1 (which produces the problematic zero), change it to -0.05 which produces the universally happy 0.05 value.
2. Change the regular expression from `0` to `0[.\d+]?` (I think).

I'd advocate option 1.

Finally, some might argue that you've already tested the full message in the *first* test so you don't need to test the content of the exception message, only the existence. In this case, I'd argue against that since your original message prints the same value twice. Instead, I'd reverse it as follows:


```c++
  DRAKE_EXPECT_THROWS_MESSAGE(
      MinimumDistanceConstraint(plant_double_, 0.1, plant_context_double_, {},
                                -0.05),
      "MinimumDistanceConstraint: influence_distance=0.05, must be larger than "
      "minimum_distance_lower=0.1.");
  // We've already tested the message contents for a *smaller* influence
  // distance. We'll assume the message is the same for an equal distance and
  // just confirm the throw.
  EXPECT_THROW(MinimumDistanceConstraint(plant_double_, 0.1,
                                         plant_context_double_, {}, 0.0),
               std::exception);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: 2 unresolved discussions

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 269 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYkCzjDQMA8CDCOM6O:-NZYrPvA68iqQNqi_xAr:bvqfngs) ([raw file](https://github.com/RobotLocomotion/drake/blob/44668007173b4c44027c2a0209093d101c5a58cf/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L269)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As I was looking at your CI failure, I realized that the error message isn't necessarily 100% aligned with the public API.

If I use a constructor that provides `influence_distance_offset`, what I get printed is `influence_distance`. I wonder if that might not be confusing; the user will *not* see the parameter they're passing in.
</blockquote></details>

I added some documentation in the header file to make it more clear. Also I mentioned influence_distance_offset in the error message.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 274 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19718#-NZYkR6W8A3fGBmW1Aej:-NZYrPQF9X4arxdaNi7u:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/44668007173b4c44027c2a0209093d101c5a58cf/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L274)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is the cause of your CI failure. In focal, "0" is being formatted as "0.0". This is the pitfall of attempting to match an error message *exactly*. It's a bit fraught. That said, I'm in favor of the effort because your *intent* is to communicate certain information back, and you want the test to confirm you've done that. So, you have two options:

1. Instead of an `influence_distance_offset` value of  -0.1 (which produces the problematic zero), change it to -0.05 which produces the universally happy 0.05 value.
2. Change the regular expression from `0` to `0[.\d+]?` (I think).

I'd advocate option 1.

Finally, some might argue that you've already tested the full message in the *first* test so you don't need to test the content of the exception message, only the existence. In this case, I'd argue against that since your original message prints the same value twice. Instead, I'd reverse it as follows:


```c++
  DRAKE_EXPECT_THROWS_MESSAGE(
      MinimumDistanceConstraint(plant_double_, 0.1, plant_context_double_, {},
                                -0.05),
      "MinimumDistanceConstraint: influence_distance=0.05, must be larger than "
      "minimum_distance_lower=0.1.");
  // We've already tested the message contents for a *smaller* influence
  // distance. We'll assume the message is the same for an equal distance and
  // just confirm the throw.
  EXPECT_THROW(MinimumDistanceConstraint(plant_double_, 0.1,
                                         plant_context_double_, {}, 0.0),
               std::exception);
```

</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19718)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform)

**Pull request merged**
