### PR TITLE
[solvers] In CsdpSolver, use longjmp to avoid full-program exits

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16732.

This is a first draft.  It still needs some tune-up to make it less brittle for ongoing maintainers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
Apologies for a couple of drive-by notes on a draft; I was reading this after you posted it on slack.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736#-:-Mxiv7-c1Fptynuq78pp:b-1r722o)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

___
*[solvers/csdp_solver.cc, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16736#-Mxirmh-3aOqooSC07DT:-Mxirmh-3aOqooSC07DU:bainf1m) ([raw file](https://github.com/robotlocomotion/drake/blob/a65e6e6dcd5b3fa007851f9f400d7240477af1ec/solvers/csdp_solver.cc#L39)):*
> ```cpp
>   if (setjmp(env) > 0) {
>     throw std::runtime_error(
>         "CsdpColer: the CSDP library exited via a fatal exception");
> ```

minor:  The term "Coler" does not appear in this repository or in Csdp; is it a typo?
___
*[solvers/csdp_solver.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxisfmpAJipABR0-O_m:-MxisfmpAJipABR0-O_n:bszew14) ([raw file](https://github.com/robotlocomotion/drake/blob/a65e6e6dcd5b3fa007851f9f400d7240477af1ec/solvers/csdp_solver.cc#L48)):*
> ```cpp
> // that call into this function instead.
> void drake_csdp_exit(int status) {
>   jmp_buf& env = get_thread_jmp_buf();
> ```

Csdp uses openmp internally, so this code in theory cannot be certain that it is running on the same thread that set the jump point without knowing details of the csdp implementation.  This would result in the longjump below jumping to an unspecified cast of an unspecified uninitialized array (a thread local jump buffer on a thread that never initialized that buffer), which is very ub.

This is worth at least a comment explaining the design reason this can't happen (which, I assume, is that you swear never to turn on openmp in `csdp/package.BUILD.bazel`?) both here and at the location of the relevant design constraint (or possibly stapling on whatever gcc/bazel's spelling of `--without-pthread --without-openmp` would be).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri)

___
*[solvers/csdp_solver.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxisfmpAJipABR0-O_m:-Mxj7-7sE3mhyOwJJcAM:b-wrgfwm) ([raw file](https://github.com/robotlocomotion/drake/blob/a65e6e6dcd5b3fa007851f9f400d7240477af1ec/solvers/csdp_solver.cc#L48)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Csdp uses openmp internally, so this code in theory cannot be certain that it is running on the same thread that set the jump point without knowing details of the csdp implementation.  This would result in the longjump below jumping to an unspecified cast of an unspecified uninitialized array (a thread local jump buffer on a thread that never initialized that buffer), which is very ub.

This is worth at least a comment explaining the design reason this can't happen (which, I assume, is that you swear never to turn on openmp in `csdp/package.BUILD.bazel`?) both here and at the location of the relevant design constraint (or possibly stapling on whatever gcc/bazel's spelling of `--without-pthread --without-openmp` would be).
</blockquote></details>

Great point.  In #16606 I was already going to disable OpenMP for CSDP, but I've pulled that flag forward into this PR now.

I'll work on better comments & cross-references as part of the overall robustness cleanup still in flight.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxjCmFc2Ec8OrbzP0_S:-MxjCmFc2Ec8OrbzP0_T:b-sew5lt) (no related file):*
Oops.  The C manual for setjmp says:

> If the function which called setjmp() returns before longjmp() is called, the behavior is undefined.  Some kind of subtle or unsubtle chaos is sure to result.

The C++ manual doesn't contain that clause, but it might explain why this isn't always working.

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxjCmFc2Ec8OrbzP0_S:-MxjIwtD9srIUofRnECR:b-eqz5cp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  The C manual for setjmp says:

> If the function which called setjmp() returns before longjmp() is called, the behavior is undefined.  Some kind of subtle or unsubtle chaos is sure to result.

The C++ manual doesn't contain that clause, but it might explain why this isn't always working.
</blockquote></details>

Oh right.  You can't have a set-my-jump-point utility function because its stack frame goes away.  Back in C one would usually write those utilities as macros.

---

**Review by ggould-tri — COMMENTED** [review]
Looking good.
I'm out on vacation after today; I'm happy to self-assign and stamp this for you before I go if you think it's mature enough.

> Reviewed 1 of 4 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736#-:-MxnzxrLBGlYY0HeMkmZ:b77xij3)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/csdp_cpp_wrapper.h, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxnybtU0XyBxthtbvjE:-MxnybtU0XyBxthtbvjF:b5h6yl2) ([raw file](https://github.com/robotlocomotion/drake/blob/098faf060601a1c605807535c3da2f42cc6a0644/solvers/csdp_cpp_wrapper.h#L26)):*
> ```objc
> void cpp_initsoln(int n, int k, struct blockmatrix C, double *a, 
> 	      struct constraintmatrix *constraints, struct blockmatrix *pX0,
> 	      double **py0, struct blockmatrix *pZ0);
> ```

minor:  tabs and trailing whitespace in the section above.

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri if you'd still like to feature review.

-(status: do not merge) -(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736#-:-MxoiW99-_JLKeIJpuQK:bdnp80z)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxoiZwf2dORTyDuqs2Y:-MxoiZwgABviZTeFu0A5:blt4bmi) (no related file):*
Working

Needs macOS testing.

---

**Comment by jwnimmer-tri** [comment]
Unsurprisingly, the longjmp recovery leaks a ton of memory, and LSan is sad.  I'll see how to suppress that diagnostic.

**Comment by jwnimmer-tri** [comment]
I wonder, instead of using longjmp maybe we should compile CSDP in C++ mode?  I suppose that has its own can of worms.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: as inspected prior to my vacation.

> Reviewed 5 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736#-:-Mxp94B7AswctEEnGdu9:brbb4xs)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/BUILD.bazel, line 1249 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16736#-Mxp8mLE8owGG2zLKF50:-Mxp8mLE8owGG2zLKF51:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/a7dfadf78f90ae838a32ed15ef8ceca7bc4fe4b6/solvers/BUILD.bazel#L1249)):*
> ```Starlark
>         # The longjmp handling definitely leaks memory, and we've decided to
>         # just live with that. If we see the longjmp handler triggering when
>         # called by CsdpSovler, we should fix CsdpSovler to do more sanity
> ```

typo



_Suggestion:_
```Starlark
CsdpSolver, we should fix CsdpSolver
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review, please (off-schedule).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos

> Reviewed 7 of 12 files at r3, 4 of 7 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736#-:-Mxu-cyfB83IdAG_Tqiv:b-7vdkkg)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[solvers/csdp_solver_error_handling.cc, line 19 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16736#-MxtzH9fEAHzOFV946Pu:-MxtzH9fEAHzOFV946Pv:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/1c66b6948fbdca3a19d089b56a3d307e67894f8d/solvers/csdp_solver_error_handling.cc#L19)):*
> ```cpp
> 
> // The library code in CSDP calls the C exit() function. Since no library
> // should do that, our CSDP package.BUILD.bazezl rule uses the preprocessor
> ```

typo



_Code quote:_
```cpp
bazezl
```
___
*[tools/workspace/csdp/repository.bzl, line 25 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16736#-Mxu-ClU1lLAS-4wprX4:-Mxu-ClV6uuVZi9zW6tx:bj1df2i) ([raw file](https://github.com/robotlocomotion/drake/blob/1c66b6948fbdca3a19d089b56a3d307e67894f8d/tools/workspace/csdp/repository.bzl#L25)):*
> ```Starlark
>             "sed -i -e 's|^#include \"|#include \"csdp/|g;' lib/*.c",
>             # Add include guards.
>             "sed -i -e $'1s/^/#pragma once\\\n/' includes/csdp/*.h",
> ```

Hooray for `#pragma once`. No more of the tragedy of trying to do that the old way.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16736)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
