### PR TITLE
Polishes rigid_body_plant_that_publishes_xdot_test.cc.

### PR DESCRIPTION
**Pull request by liangfok**
Minor changes to abide by IWYU rule and for increased readability.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4815)

### CODE REVIEW

**Comment by liangfok** [comment]
Minor change. +@sammy-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-:-KanWWSavolbvhw2RLNX:b7ggiv2)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcuI1IpP6-WJkqHNI:-KarcuI1IpP6-WJkqHNJ:b-g0v64w) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L5)):*
> ```cpp
> #include <memory>
> 
> #include <Eigen/Dense>
> ```

This doesn't appear to be used in this file.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcmPMuFqFuiYp8rxW:-KarcmPMuFqFuiYp8rxX:b-g0v64w) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L14)):*
> ```cpp
> #include "drake/multibody/parsers/urdf_parser.h"
> 
> using Eigen::VectorXd;
> ```

This doesn't appear to be used in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcuI1IpP6-WJkqHNI:-Kas6QF8jGCWG8Yy_4G0:b-woap22) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This doesn't appear to be used in this file.
</blockquote></details>

This file uses `VectorXd`, which I believe is part of `<Eigen/Dense>`.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcmPMuFqFuiYp8rxW:-Kas6bd80HkO9_m0NOTj:b-dam43n) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This doesn't appear to be used in this file.
</blockquote></details>

This file uses `VectorXd::Map()` to save `xdot` into the `lcmt_drake_signal` message's `val`' field. This appears in `DoPublish()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcuI1IpP6-WJkqHNI:-Kawdzhi2-v5GH-CCEXb:brz21ou) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This file uses `VectorXd`, which I believe is part of `<Eigen/Dense>`.
</blockquote></details>

I can't seem to find that by expanding the whole file in reviewable and searching for "vector".   I can see the using below, but that's it.   Is something somehow being hidden?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4815#-KarcuI1IpP6-WJkqHNI:-Kax86SNOivmwZlW89qc:b7mg2tr) ([raw file](https://github.com/robotlocomotion/drake/blob/cc693025999bb89e2c8f77668987811d0081f94c/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I can't seem to find that by expanding the whole file in reviewable and searching for "vector".   I can see the using below, but that's it.   Is something somehow being hidden?
</blockquote></details>

Oops! You're right. I have no idea what I was thinking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4815)*

**Pull request closed without merging**
