### PR TITLE
Fixes to QuaternionFreeMobilizer

### LINKED ISSUE #8177: Re-enable QuaternionFloatingMobilizer.Simulation test case
In #8176 (assuming it merges) we disabled a test case that fails under valgrind -- `QuaternionFloatingMobilizer.Simulation` in `multibody/multibody_tree/test/floating_body_test.cc`.  This issue tracks re-enabling that test case.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Closes #8177.

#8176 exposed a difficult to detect bug in the `QuaternionFreeMobilizer`. This PR fixes such bug and introduces a set of unit tests that directly (vs the indirect tests through integration already in master) verify the correct behavior of the kinematic mapping methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8192)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-:-L6N5xaboLXvqx4cwE9p:b-a98c4g)*

**Comment by amcastro-tri** [comment]
+@sammy-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-:-L6N6YtsUKNilVBQWPOy:b-1zm1j3)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-:-L6NBAWtLzhbxZ5t3ARb:bnfp4nl)*

**Comment by amcastro-tri** [comment]
-@edrumwri  +@hongkai-dai please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-:-L6NaEAP7SEQ2yyJX8K0:bx944cm)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 203 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-L6NkqX5W3LKbGKpwUXC:-L6NkqX5W3LKbGKpwUXD:b66ys7e) ([raw file](https://github.com/robotlocomotion/drake/blob/29dae87594719503b0058166d44ce1d3bebd6d1f/multibody/multibody_tree/test/floating_body_test.cc#L203)):*
> ```cpp
>   const Vector3<double> DtW_p_WBcm = qdot_from_v.tail<3>();
> 
>   Quaterniond q_WB = mobilizer.get_quaternion(context);
> ```

BTW, const Quaterniond?

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-L6NkjxGmuy38DXNcxj9:-L6NkjxGmuy38DXNcxjA:b-x2hlc5) ([raw file](https://github.com/robotlocomotion/drake/blob/29dae87594719503b0058166d44ce1d3bebd6d1f/multibody/multibody_tree/test/floating_body_test.cc#L204)):*
> ```cpp
> 
>   Quaterniond q_WB = mobilizer.get_quaternion(context);
>   Vector4d q_WB_vec4(q_WB.w(), q_WB.x(), q_WB.y(), q_WB.z());
> ```

BTW, const Vector4d?

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 269 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-L6NlMNDqnMpmG5YeHwT:-L6NlMNDqnMpmG5YeHwU:bf314io) ([raw file](https://github.com/robotlocomotion/drake/blob/29dae87594719503b0058166d44ce1d3bebd6d1f/multibody/multibody_tree/test/floating_body_test.cc#L269)):*
> ```cpp
>       2.0 * Vector3d::UnitY() +
>       3.0 * Vector3d::UnitZ()).normalized();
>   const Matrix3d R_WB = AngleAxisd(M_PI / 3.0, axis_W).toRotationMatrix();
> ```

BTW, you can construct quaternion from angle-axis directly, as
```
const Quaterniond q_WB(AngleAxisd(M_PI / 3.0, axis_W));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-:-L6Nx2A8F6tpZJKju6DL:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 269 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8192#-L6NlMNDqnMpmG5YeHwT:-L6OG48cH67yIRjZKmJn:bgn3rwh) ([raw file](https://github.com/robotlocomotion/drake/blob/29dae87594719503b0058166d44ce1d3bebd6d1f/multibody/multibody_tree/test/floating_body_test.cc#L269)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you can construct quaternion from angle-axis directly, as
```
const Quaterniond q_WB(AngleAxisd(M_PI / 3.0, axis_W));
```
</blockquote></details>

BTW good point. This was copy/pasta from the test above where I did this intentionally to have the matrix `R_WB` handy. Here it is no needed and your solution makes more sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8192)*

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
