### PR TITLE
Draw the box sphere intersection in any orthant

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5675)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-:-KgW7PZqy8KHtBHv75pP:b-e8hf3g)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-:-KgiQAhdy-aJOunyrubT:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-:-Kgjf39E2RbwflRWIySl:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/rotation_constraint_visualization.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-Kgk7Uz73d62KpQZpS48:-Kgk7Uz8EOi7eRIP07oT:bqbu6nv) ([raw file](https://github.com/robotlocomotion/drake/blob/f07d54954ac61c7a3a26699d1186a5bee47a08dc/drake/solvers/test/rotation_constraint_visualization.cc#L143)):*
> ```cpp
>       orthant_bmax(i) = -bmin(i);
>       orthant_sign(i) = -1;
>     }
> ```

It seems like this allows for `orthant...` to remain unset when `bmin < 0 && bmax > 0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/rotation_constraint_visualization.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-Kgk7Uz73d62KpQZpS48:-KgodALG6IdP7EEgkiVF:b-3h61oa) ([raw file](https://github.com/robotlocomotion/drake/blob/f07d54954ac61c7a3a26699d1186a5bee47a08dc/drake/solvers/test/rotation_constraint_visualization.cc#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like this allows for `orthant...` to remain unset when `bmin < 0 && bmax > 0`.
</blockquote></details>

We actually do not allow `bmin < 0 && bmax > 0`, namely the box `bmin <= x <= bmax` should be contained in an orthant. I just add the code to throw an error, if `bmin < 0 && bmax > 0` happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675)*

**Comment by jwnimmer-tri** [comment]
:lgtm: 
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-:-KgpQ7_AawnK6vSdIp6Q:bmrym31)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5675#-:-KgpRR5uMLqSCUXp5CdC:b-l70wzf)*

**Pull request merged**
