### PR TITLE
Replace RotationMatrix::IsIdentityToInternalTolerance() with RotationMatrix::IsNearlyIdentity().

### PR DESCRIPTION
**Pull request by mitiguy**
Resolves issue #16551

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 
Note: Per @xuchenhan-tri  request, I also made modifications in favor of std::exception (instead of std::logic_error, etc).  Hopefully, these minor changes do not cause problems.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552#-:-MvUnVTn8R9gvaXxzQvN:bs78ya3)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552#-:-MvUpoP52MC0dxrdgmX-:b-n37teh)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @mitiguy)

___
*[bindings/pydrake/test/math_test.py, line 271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16552#-MvUp4rbCiFSPIfOzY-5:-MvUp4rc91GY8icBUBaH:bgy2zyi) ([raw file](https://github.com/robotlocomotion/drake/blob/9d96b4bd0695f99d91ff83f264139371bdf239b9/bindings/pydrake/test/math_test.py#L271)):*
> ```Python
>         R_AngleAxis = RotationMatrix(angle_axis)
>         R_I = R.inverse().multiply(R_AngleAxis)
>         numpy_compare.assert_equal(R_I.IsNearlyIdentity(2E-15), True)
> ```

nit Because the bindings code has `py::arg("tolerance")`, we need to cover that name with at least one test case.  In at least one of the calls to `IsNearlyIdentity` somewhere in this file, we need to pass a `tolerance=...` argument by name to demonstrate that it works.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552#-:-MvVEsr32Mbe_Jr2B2dB:bfqkacy)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552#-:-MvVN5RU8LkVMP28h3nG:b-vtj4vo)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
label +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16552#-:-MvV8GT7919XkCWMnuLC:br1597u)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

___
*[bindings/pydrake/test/math_test.py, line 271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16552#-MvUp4rbCiFSPIfOzY-5:-MvV7sg49fm-oYPOwLRu:bo9oedl) ([raw file](https://github.com/robotlocomotion/drake/blob/9d96b4bd0695f99d91ff83f264139371bdf239b9/bindings/pydrake/test/math_test.py#L271)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Because the bindings code has `py::arg("tolerance")`, we need to cover that name with at least one test case.  In at least one of the calls to `IsNearlyIdentity` somewhere in this file, we need to pass a `tolerance=...` argument by name to demonstrate that it works.
</blockquote></details>

Done.  See  below.

**Pull request merged**
