### PR TITLE
APIs to set the default joint damping.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151#-:-N1jfIEJCGjfJHpTW3Bn:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with one question on the pre-conditions. +@jwnimmer-tri for platform please, if you still have time today.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151#-:-N1jjwt7CWeYQ7Bp1RsF:bqlruih)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[`multibody/tree/joint.h` line 467 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17151#-N1jhnRP-P85Sq0AL3th:-N1jhnRP-P85Sq0AL3ti:bry2mv0) ([raw file](https://github.com/robotlocomotion/drake/blob/7967159a273fb026d2a89ca56ebf866a308fc72a/multibody/tree/joint.h#L467)):*
> ```objc
>   /// @throws std::exception if damping.size() != num_velocities().
>   /// @throws std::exception if any of the damping coefficients is negative.
>   void set_default_damping_vector(const VectorX<double>& damping) {
> ```

nit: Since damping is a model parameter, should we restrict this method to only be called pre-finalize? Or at least warn that changing these values will have no effect at some point post-finalize? (I guess in this case they can be changed until `MultibodyPlant::SetDiscreteUpdateManager()` is called.)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/tree/joint.h` line 467 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17151#-N1jhnRP-P85Sq0AL3th:-N1jn6wTDJJyFKLYmoo5:bngiq1v) ([raw file](https://github.com/robotlocomotion/drake/blob/7967159a273fb026d2a89ca56ebf866a308fc72a/multibody/tree/joint.h#L467)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Since damping is a model parameter, should we restrict this method to only be called pre-finalize? Or at least warn that changing these values will have no effect at some point post-finalize? (I guess in this case they can be changed until `MultibodyPlant::SetDiscreteUpdateManager()` is called.)
</blockquote></details>

Done. Added precondition.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151#-:-N1js_he2k3Sgktgyq3i:b-vtj4vo)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/tree/joint.h` line 467 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17151#-N1jrvSFA4cnJO4IzENC:-N1jrvSFA4cnJO4IzEND:bxpdg6t) ([raw file](https://github.com/robotlocomotion/drake/blob/134d7c67a9a636eb4fc19d2b68361db59904bc58/multibody/tree/joint.h#L467)):*
> ```objc
>   /// @throws std::exception if damping.size() != num_velocities().
>   /// @throws std::exception if any of the damping coefficients is negative.
>   /// @pre the MultibodyPlant must not be finalized.
> ```

Almost nobody will notice this condition, which lives only in documentation.

Shouldn't we fail-fast in case the user does the wrong thing here?

```c++
DRAKE_DEMAND(!this->get_parent_tree().topology_is_valid());
```

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151)* status: 1 unresolved discussion (waiting on @joemasterjohn and @jwnimmer-tri)

___
*[`multibody/tree/joint.h` line 467 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17151#-N1jrvSFA4cnJO4IzENC:-N1k39ZW0mhMReTad9py:bctpdcc) ([raw file](https://github.com/robotlocomotion/drake/blob/134d7c67a9a636eb4fc19d2b68361db59904bc58/multibody/tree/joint.h#L467)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Almost nobody will notice this condition, which lives only in documentation.

Shouldn't we fail-fast in case the user does the wrong thing here?

```c++
DRAKE_DEMAND(!this->get_parent_tree().topology_is_valid());
```
</blockquote></details>

Makes sense. Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17151)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),joemasterjohn (waiting on @amcastro-tri)

**Pull request merged**
