### PR TITLE
[examples/manipulation_station] Use DifferentialInverseKinematicsIntegrator

### LINKED ISSUE #11581: Make DifferentialIK leaf system available within pydrake
for examples/manipulation_station/differential_ik.py
Either implement in C++ and as the TODO within this file states or find some other way to expose this functionality to downstream consumers. Assigning to @RussTedrake since his names on the TODO.

### PR DESCRIPTION
**Pull request by RussTedrake**
Removes the local implementation of a differential IK in favor of the proper Drake version.

Resolves #11581 (again).

+@naveenoid for feature review, please.  (Please make sure you can run the three notebooks)

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please.

**Review by naveenoid — COMMENTED** [review]
There is a bug in 1 of them. Other two work well.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899#-:-NC_VjCSCB6Q358LpCcO:bv1l6le)* status: 1 unresolved discussion, LGTM missing from assignee naveenoid, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`examples/manipulation_station/end_effector_teleop_dualshock4.py` line 416 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17899#-NC_TteK8PTEKstXX6z3:-NC_TteL7g0Joh_KT5Gg:bx7sikn) ([raw file](https://github.com/robotlocomotion/drake/blob/1494685bf42aa80cd287645c82fd20d04cf56f8d/examples/manipulation_station/end_effector_teleop_dualshock4.py#L416)):*
> ```Python
> 
>     to_pose = builder.AddSystem(ToPose())
>     builder.Connect(filter.get_output_port(0),
> ```

I think you meant to connect filter_.get_output_port(0). The version above throws an Attribute error

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899)* status: 1 unresolved discussion, LGTM missing from assignee naveenoid, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @naveenoid)

___
*[`examples/manipulation_station/end_effector_teleop_dualshock4.py` line 416 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17899#-NC_TteK8PTEKstXX6z3:-NCyfkLAEX7e7v8nafsS:bmwagm5) ([raw file](https://github.com/robotlocomotion/drake/blob/1494685bf42aa80cd287645c82fd20d04cf56f8d/examples/manipulation_station/end_effector_teleop_dualshock4.py#L416)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I think you meant to connect filter_.get_output_port(0). The version above throws an Attribute error
</blockquote></details>

Done.  Sorry!  I had made that change on my dual-shock equipped machine but forgotten to push.

**Review by naveenoid — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899#-:-NDTdZ9ZAbUBlvhIQ9io:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899#-:-NDZzDsZ1lruDScaUeiB:b223nro)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17899)* status: :shipit: complete! all discussions resolved, LGTM from assignees naveenoid,xuchenhan-tri(platform) (waiting on @RussTedrake)

___
*[`examples/manipulation_station/end_effector_teleop_sliders.py` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17899#-NDcu8me10au9-kLWpR5:-NDdl8q79Yr79S34YHxu:b-l0qj9r) ([raw file](https://github.com/robotlocomotion/drake/blob/2eb2e096e4160a2eb4e96e09d76e5daa26977c31/examples/manipulation_station/end_effector_teleop_sliders.py#L144)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, seeing the copypasta of this adhoc system, I wonder if it makes sense for DifferentialInverseKinematicsIntegrator to open an alternative input port that takes rpy_xyz? Or is this setup in this directory unique?
</blockquote></details>

it's not a bad idea.  what was different here compared to my other pipelines is the addition of the filter; I didn't have an easy way to run the first-order filter directly on pose.  Future work.  ;-)

**Pull request merged**
