### PR TITLE
Add no_kcov to cpplint_unittest

### PR DESCRIPTION
**Pull request by m-chaturvedi**
@jwnimmer-tri pointed out here:
https://github.com/RobotLocomotion/drake/pull/12776#issuecomment-595315508

Closes #12821.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12822)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-nightly-coverage please.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.

**Comment by jamiesnape** [comment]
The coverage build takes 9 hours, I think we can cancel that since we know the `no_kcov` works.

**Comment by m-chaturvedi** [comment]
@jwnimmer-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
> The coverage build takes 9 hours, I think we can cancel that since we know the no_kcov works.

Agreed.  Also skipping lsan and debug, forcing in now.

**Pull request merged**
