### PR TITLE
Pay off some System2 technical debt.

### PR DESCRIPTION
**Pull request by david-german-tri**
- Rename `SystemInterface<T>::CreateDefaultOutput` to `AllocateOutput`.
- Add `VectorInterface::size()`.
- Use `out_of_range` where appropriate.

+@jwnimmer-tri for feature and platform review (but not urgent, can wait until Tuesday)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2474)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo8RZDn3m17BVZPd7U:-KIo8RZEwjPsBPryMXzA:1833521060) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
> ```objc
>   VectorInterface& operator=(VectorInterface<T>&& other) = delete;
> 
>   virtual size_t size() const = 0;
> ```

Needs at  least some kind of API comment.  For example, must it always be equal to get_value().size()?

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo9EmIz4wYicnA0ahN:-KIo9EmIz4wYicnA0ahO:-2126583747) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
> ```objc
>   VectorInterface& operator=(VectorInterface<T>&& other) = delete;
> 
>   virtual size_t size() const = 0;
> ```

Eigen uses a signed number (std::ptrdiff_t) for all of its indices by default.   The cppguide is very anti-unsigned (even moreso that when I last read it, it appears).  Are you sure we have a good reason to use unsigned numbers here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474)*

**Comment by david-german-tri** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo8RZDn3m17BVZPd7U:-KIoCU2pbyhyMkCx8yM1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Needs at  least some kind of API comment.  For example, must it always be equal to get_value().size()?
</details>
Done.

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo9EmIz4wYicnA0ahN:-KIoDUFbygEP5gJg0Gj-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Eigen uses a signed number (std::ptrdiff_t) for all of its indices by default.   The cppguide is very anti-unsigned (even moreso that when I last read it, it appears).  Are you sure we have a good reason to use unsigned numbers here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Pay off some System2 technical debt\.
> 
> - Rename `SystemInterface<T>::CreateDefaultOutput` to `AllocateOutput`.
> 
> - Add `VectorInterface::size()`.
> 
> - Use `out_of_range` where appropriate.
> 
> 
> 
> +@jwnimmer-tri for feature and platform review (but not urgent, can wait until Tuesday)
> 
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_interface.h, line 30 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIoDqPyKnPaFFeUDRPa:-KIoDqPyKnPaFFeUDRPb:-2033417239) ([raw file](https://github.com/robotlocomotion/drake/blob/e763f1f3a9d2d3baaececbdfb70f0815fb5cfd0d/drake/systems/framework/vector_interface.h#L30)):*
> ```objc
>   /// Returns the size of the vector, which must be equal to the number of rows
>   /// in get_value().
>   virtual ptrdiff_t size() const = 0;
> ```

BTW Missing `#include <cstddef>`.  (Sorry, I missed that first time around.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-:-KIoDz9QPR174i49cMJk:1417088721)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo9EmIz4wYicnA0ahN:-KIoBYwalAY9m1EDDp5K:1949721914) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
Could this be relevant? http://stackoverflow.com/questions/430346/why-doesnt-java-support-unsigned-ints

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474)*

**Comment by liangfok** [comment]
:lgtm_strong:  :shipit: 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-:-KIoL2bgy6TDuL1fA6YC:1545843994)*

**Comment by jwnimmer-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/framework/vector_interface.h, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2474#-KIo9EmIz4wYicnA0ahN:-KIoXZHMwcszAH8LKn61:-178845090) ([raw file](https://github.com/robotlocomotion/drake/blob/1fee9b7dd6b5aceec527ba7b1a4455bc189b7de4/drake/systems/framework/vector_interface.h#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Could this be relevant? http://stackoverflow.com/questions/430346/why-doesnt-java-support-unsigned-ints
</details>
Force-resolving the prior comment, as if it were "BTW".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2474)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
