### PR TITLE
[planning] Improve direct transcription error messages

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/pull/21623 (which will add abstract state, and trip the old error message which was not helpful in this situation), and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review. 
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-:-O19xzb14B4pex8Oyzro:b-9ns4oa)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19xnQv0EJMJb5RpsB_:-O19xnQv0EJMJb5RpsBa:b-cw3glc) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L158)):*
> ```cpp
>     throw std::logic_error(
>         "DirectTranscription cannot operate on systems with abstract state.");
>   }
> ```

DirectCollocation acquired this input argument:
```
bool 	assume_non_continuous_states_are_fixed = false,
```
back when SceneGraph declared abstract state. I guess it never came over to this class.  Perhaps you can add a TODO here (or perhaps decide that it should not be supported in DirectCollocation?)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O19yU6ZEiHgSGqL1pNJ:bvzd740) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
> ```cpp
>   if (system->num_abstract_states() > 0) {
>     throw std::logic_error(
>         "DirectTranscription cannot operate on systems with abstract state.");
> ```

i don't think you would let me get away with adding a new throw without adding a test that catches it?  would you?
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O19yYJu5KXr32tEb2x5:b-c7c8f6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
> ```cpp
>       system->GetUniquePeriodicDiscreteUpdateAttribute();
>   if (periodic_data.has_value()) {
>     DRAKE_THROW_UNLESS(periodic_data->offset_sec() == 0.0);
> ```

new throw?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O19zhTWBtdcKPjHUo0a:btrblde) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think you would let me get away with adding a new throw without adding a test that catches it?  would you?
</blockquote></details>

This PR wasn't yet polished up for review (it was marked as a draft). I've added the test now.
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19xnQv0EJMJb5RpsB_:-O19z8Zs3NTzj_B-CW5c:b-yht8yu) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L158)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

DirectCollocation acquired this input argument:
```
bool 	assume_non_continuous_states_are_fixed = false,
```
back when SceneGraph declared abstract state. I guess it never came over to this class.  Perhaps you can add a TODO here (or perhaps decide that it should not be supported in DirectCollocation?)
</blockquote></details>

The plant's new abstract state that I'm working on will be time-varying (periodically stepped) and affect most output ports, so at least for my MbP use case, setting `assume_non_continuous_states_are_fixed = true` would probably be a user mistake, so I'm not inclined to add code for that situation here.  The code on master already throws in the case of abstract state, just with a less-clear error message (talking about continuous time), so this change is intended just to be a small tweak to improve the error message.
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O19yvfQ4eeampmV64Rb:b-4ktmju) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

new throw?
</blockquote></details>

This is changing a pre-existing DEMAND to a THROW.  (We should not abort the process when we receive malformed input arguments.)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O1Cm8TH9upm8f4f9Cnp:b-updzw3) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR wasn't yet polished up for review (it was marked as a draft). I've added the test now.
</blockquote></details>

should we also declare the throw in 
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19xnQv0EJMJb5RpsB_:-O1Clxqa1uHZEjfwPngA:b-81nlyc) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L158)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The plant's new abstract state that I'm working on will be time-varying (periodically stepped) and affect most output ports, so at least for my MbP use case, setting `assume_non_continuous_states_are_fixed = true` would probably be a user mistake, so I'm not inclined to add code for that situation here.  The code on master already throws in the case of abstract state, just with a less-clear error message (talking about continuous time), so this change is intended just to be a small tweak to improve the error message.
</blockquote></details>

SGTM.
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O1CmlJ5EkEVE-sov6mt:b-tbui2a) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is changing a pre-existing DEMAND to a THROW.  (We should not abort the process when we receive malformed input arguments.)
</blockquote></details>

The docstring for the discrete-time constructor currently only documents:
```
  /// @throws std::exception if `context.has_only_discrete_state() == false`.
```
I think we should document the new throw?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O1Cq32L31T6yuS3ZztQ:bh7997f) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

should we also declare the throw in
</blockquote></details>

The documentation says `throws std::exception if context.has_only_discrete_state() == false`.

I believe `system->num_abstract_states() > 0` implies the former, so the documentation is already complete.  The only change here is using better for an already-existing exceptional condition.
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O1CpmBt7z2KZukZFEYB:b-fudfix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The docstring for the discrete-time constructor currently only documents:
```
  /// @throws std::exception if `context.has_only_discrete_state() == false`.
```
I think we should document the new throw?
</blockquote></details>

Reverted the DEMAND/THROW change.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O1Cr4xeDNe8R-lsMhJx:b-81jadv) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The documentation says `throws std::exception if context.has_only_discrete_state() == false`.

I believe `system->num_abstract_states() > 0` implies the former, so the documentation is already complete.  The only change here is using better for an already-existing exceptional condition.
</blockquote></details>

... is using better _error text_ for an already-existing exceptional condition.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yU6ZEiHgSGqL1pNI:-O1Cs_R08V6sCEFsaZRc:b-d3tq3j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... is using better _error text_ for an already-existing exceptional condition.
</blockquote></details>

Yes, agreed. I was only trying to comment below, realized half-way that i was writing in the wrong spot, but somehow failed to remove my half sentence.  My apologies.
___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O1CshyH8o9kyclqwMKu:bmup0j9) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Reverted the DEMAND/THROW change.
</blockquote></details>

if you believe it's wrong to abort the process, then why revert instead of just the one line change to the docstring?

but marking myself satisfied in either case.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O19yYJu5KXr32tEb2x4:-O1Cv18JDYf7MRLb-xSE:byb8ff8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e029179ed10446e7997358c906d94fa0e09df717/planning/trajectory_optimization/direct_transcription.cc#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

if you believe it's wrong to abort the process, then why revert instead of just the one line change to the docstring?

but marking myself satisfied in either case.
</blockquote></details>

It's actually more work than just the one line, and isn't relevant to my goals.  It seemed like a casual cleanup I could sneak in here at low cost, but not so much.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a doc update request.

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-:-O1HbtNv-grsV2Y7FbmA:b-aq8vuk)* status: 1 unresolved discussion

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O1HbWx82kKURnA1xhfc:-O1HbWx82kKURnA1xhfd:b-d6b3lu) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ea32d6cd131b3046923478f35beb9d1e5e58f69/planning/trajectory_optimization/direct_transcription.cc#L157)):*
> ```cpp
>   if (system->num_abstract_states() > 0) {
>     throw std::logic_error(
>         "DirectTranscription cannot operate on systems with abstract state.");
> ```

nit: This new piece of data is not included in the class documentation.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: 1 unresolved discussion

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O1HbWx82kKURnA1xhfc:-O1HdfDk49jBsz-Ar3Wz:b-j59nml) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ea32d6cd131b3046923478f35beb9d1e5e58f69/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This new piece of data is not included in the class documentation.
</blockquote></details>

I'm not sure what you mean.  The API doc says `throws std::exception if context.has_only_discrete_state() == false`, which is exactly what this is doing.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21688)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform)

___
*[`planning/trajectory_optimization/direct_transcription.cc` line 157 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21688#-O1HbWx82kKURnA1xhfc:-O1IGVQs2SzGRKzQxmm6:bnhram9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ea32d6cd131b3046923478f35beb9d1e5e58f69/planning/trajectory_optimization/direct_transcription.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure what you mean.  The API doc says `throws std::exception if context.has_only_discrete_state() == false`, which is exactly what this is doing.
</blockquote></details>

Oops. Missed that. I found the main documentation heavily emphasized discrete vs continuous and missed the fact that state composition wasn't treated the same.

**Pull request merged**
