### PR TITLE
Promote unused-but-set-parameter to Werror

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6793)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@nikos-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by nikos-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6793#-:-Kr2XynuGtSxcb8bapYd:bnfp4nl)*

**Comment by sherm1** [comment]
I'm unclear about the motivation for adding this gcc-only flag. It doesn't appear that clang offers this flag -- does it already detect these cases with `-Werror=unused`? In any case it seems like a good thing to catch so :lgtm: as an incremental improvement.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6793#-:-Kr3CkWwbkZ4rfmEnqTr:b-aza6ot)*

**Comment by jwnimmer-tri** [comment]
The motivation was that this was on by default as a warning (but not error), cluttering up the build output for the one file that this PR fixes.  This promotes it to an error, so that CI will holler if we ever trip over it.  If we eventually decide we don't like it as an error, we could instead shut it off entirely.

**Comment by stonier** [comment]
@sherm1 for reference, from the gcc pages, it looks like this option is part of `extra`, not `unused`.

**Pull request merged**
