### PR TITLE
release_playbook: Modifications used for v0.27.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Add download_release_candidate script
Use un-escaped docstring (given usage of backslash)
Should not break lines at 80-characters for PR bullet points
Be more explicit about full-symbol expansion for new bindings

Split off from #14646

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651#-:-MTfMrbe4PcMJruBpXRC:b-qf68jg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfPJdD9gf-fp5EG9LB:bda4yrq) (no related file):*
Working: Per @jamiesnape's request, should include an action item to ping Jamie about the date and commit.

https://github.com/robotlocomotion/drake/pull/14646#issuecomment-779896961

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfPRHIDWVDORPcxBpy:b-tjcor4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Per @jamiesnape's request, should include an action item to ping Jamie about the date and commit.

https://github.com/robotlocomotion/drake/pull/14646#issuecomment-779896961
</blockquote></details>

OK Nevermind. It's already there:
https://github.com/RobotLocomotion/drake/blame/fc1e0e5e7eb8cef3b9a38de650bd8ccdff04a4e4/doc/release_playbook.rst#L190

@jamiesnape I will ping you after the doc builds finish. If you want to reroder things, can you PR something according to your preferences?

---

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfQC6s-gydACemFuvx:b-afj6s4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Nevermind. It's already there:
https://github.com/RobotLocomotion/drake/blame/fc1e0e5e7eb8cef3b9a38de650bd8ccdff04a4e4/doc/release_playbook.rst#L190

@jamiesnape I will ping you after the doc builds finish. If you want to reroder things, can you PR something according to your preferences?
</blockquote></details>

I don't need a re-order, I just want three pieces of information in the ping, which is also going to minimize human error on my part. I can PR that, if it is too much trouble.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfQm3D-qbZio0QLjfQ:bxom6js) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I don't need a re-order, I just want three pieces of information in the ping, which is also going to minimize human error on my part. I can PR that, if it is too much trouble.
</blockquote></details>

Gotcha. Misread, will do.

But you asking for things out-of-order from playbook confused things. I think just asking for the modification, on the playbook itself, would've simplified things.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfRRp09rYrB6dCKuXq:b8vp8y0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. Misread, will do.

But you asking for things out-of-order from playbook confused things. I think just asking for the modification, on the playbook itself, would've simplified things.
</blockquote></details>

Done. See r2.

---

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTfPJdC-Z2n_Tw0shbX:-MTfRcU73TQipveAX-1j:bhvjgar) (no related file):*
Thanks.

> But you asking for things out-of-order from playbook confused things. I think just asking for the modification, on the playbook itself, would've simplified things

The modification was there until it was here...

---

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint.

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651#-:-MTmFfeC4EsmsA0qaAU3:by96gdd)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/release_playbook.rst, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmFLl5BCWchn5reUWb:-MTmFLl5BCWchn5reUWc:b-35lit2) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/doc/release_playbook.rst#L127)):*
> ```reStructuredText
>       to (open the latest build, go to "View as plain text", and search for
>       ``drake/nightly/drake-20``), and find the date.  It will be ``YYYYMMDD``
>       with today's date (they kick off after midnight).  All of the builds should have the same date. If not, wait until the following night.
> ```

nit >80
___
*[doc/release_playbook.rst, line 156 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmFVLjCGnpyLPpw7ne:-MTmFVLjCGnpyLPpw7nf:boiojun) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/doc/release_playbook.rst#L156)):*
> ```reStructuredText
>           via commit does not work if you don't use the correct length.
> 
>     d. Release title is: Drake v0.N.0
> ```

nit "c" not "d".

(Also "d" not "e" on the next one.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok).

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651#-:-MTmOXUVA_oBWjMKH7oV:b-fl40af)* status: 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tools/release_engineering/download_release_candidate.py, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmMzHdDAP3Jz8j8ANL:-MTmMzHe4_m4JWGltJdi:bc6mtp3) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L2)):*
> ```Python
> r"""
> Downloads the relevant archives, verify they are all the same version, and
> ```

nit Add `s` to "verifies" and "prepares", to match verb "downloads".
___
*[tools/release_engineering/download_release_candidate.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmNCDC-hTCe3-4lM8M:-MTmNCDC-hTCe3-4lM8N:b-rr1abc) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L12)):*
> ```Python
> Here's an example of how to download the archives:
> 
>   bazel build //tools/release_engineering:relnotes
> ```

nit Typo "relnotes"
___
*[tools/release_engineering/download_release_candidate.py, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmO5bC5UoOK_TXWWc2:-MTmO5bC5UoOK_TXWWc3:bkfxnl) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L16)):*
> ```Python
>     --version v0.27.0 --timestamp 20210216
> 
> Pay attention to the output.
> ```

nit As a user of this tool, I'm not sure what I'm supposed to take away from this advice.  Should I be watching for error messages, for example?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[doc/release_playbook.rst, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmFLl5BCWchn5reUWb:-MTmjUNM8-9F2B2Rfk-g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/doc/release_playbook.rst#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit >80
</blockquote></details>

Done.
___
*[doc/release_playbook.rst, line 156 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmFVLjCGnpyLPpw7ne:-MTmjV3N8rtZ-Q_k5wc6:bdfeivx) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/doc/release_playbook.rst#L156)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit "c" not "d".

(Also "d" not "e" on the next one.)
</blockquote></details>

Done. One day, I'll learn my ABCs!!!
___
*[tools/release_engineering/download_release_candidate.py, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmMzHdDAP3Jz8j8ANL:-MTmjXjCEk-WDVT7z-in:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Add `s` to "verifies" and "prepares", to match verb "downloads".
</blockquote></details>

Done.
___
*[tools/release_engineering/download_release_candidate.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmNCDC-hTCe3-4lM8M:-MTmjZKC7lj3eyFPiQ2g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Typo "relnotes"
</blockquote></details>

Done.
___
*[tools/release_engineering/download_release_candidate.py, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmO5bC5UoOK_TXWWc2:-MTmjZx1CVwj-9YQj7h9:b16grzg) ([raw file](https://github.com/robotlocomotion/drake/blob/e29abb6c36039979ff3ff9fca3021550ecea1d6b/tools/release_engineering/download_release_candidate.py#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit As a user of this tool, I'm not sure what I'm supposed to take away from this advice.  Should I be watching for error messages, for example?
</blockquote></details>

Done. Removed; mebbe more distracting than useful (as it is implicit).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmjhE9-0V_GmU4Zf9z:-MTmjhEA4qvTimNVOeeB:b-6ojd0t) (no related file):*
nit Either update the md in this PR, or add it to the transmogrification checklist.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14651)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14651#-MTmjhE9-0V_GmU4Zf9z:-MTmmxaJC9cISF7QLrqX:b-6zlwiq) (no related file):*
Done. Added to checklist:
> 

---

**Comment by EricCousineau-TRI** [comment]
Skipping slower builds.

**Pull request merged**
