### PR TITLE
[geometry] Update RenderEngineVtk and remove private friendship

### PR DESCRIPTION
**Pull request by zachfang**
Update RenderEngineVtk function access modifiers and remove private friendship between RenderEngineVtk and its derived class RenderEngineGltfClient.

Tested locally with the new changes by running the new client/server pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, thanks!
cc @svenevs

Will have another quick PR to fix the `verb mood` in `geometry/render/dev` folder.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846#-:-MyqsJxa-0YjF9_S0PkI:b83pirx)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

We'll also need a platform reviewer, but only for the two files that are outside of dev.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846#-:-MyqwGUJ9OnjVVsWyWoB:b4o89ci)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[geometry/render/render_engine_vtk.h, line 167 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqunVy3rRm_7BLzmca:-MyqunVy3rRm_7BLzmcb:b-r8ovk3) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L167)):*
> ```objc
>    render size camera intrinsics, visible windows, etc. */
>   void UpdateWindow(const RenderCameraCore& camera,
>                     bool show_window, const RenderingPipeline* p,
> ```

nit It's not clear to be why "p" is a pointer, instead of a reference.  It does not appear to meet any of the usual criteria (is nullable, is non-const, is retained, or is an output).
___
*[geometry/render/render_engine_vtk.h, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-Myqu1Gp3BbvvPw0J6i6:-Myqu1Gp3BbvvPw0J6i7:bxeu7w3) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L170)):*
> ```objc
>                     const char* name) const;
> 
>   /** Variant of configuring the VTK model (see previous method) that *also*
> ```

nit The term of art in C++ is "member functions", not "methods".



_Suggestion:_
```objc
function
```
___
*[geometry/render/dev/render_engine_gltf_client.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqvZD46rD1Eptf_C7c:-MyqvZD46rD1Eptf_C7d:b-b202uh) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/dev/render_engine_gltf_client.cc#L79)):*
> ```cpp
>  have to be revisited (e.g., two kinds of depth images supported). */
> RenderImageType VtkToClientRenderImageType(
>     ImageType image_type) {
> ```

nit This line could unwrap now that we have more space?
___
*[geometry/render/dev/render_engine_gltf_client.cc, line 238 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqvoIV41BHX6gmWdCr:-MyqvoIWAQMFeTCnSHug:bfbcet1) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/dev/render_engine_gltf_client.cc#L238)):*
nit Too-obscure use of `auto`.

> Use type deduction only if it makes the code clearer to readers who aren't familiar with the project, or if it makes the code safer. Do not use it merely to avoid the inconvenience of writing an explicit type.

https://drake.mit.edu/styleguide/cppguide.html#Type_deduction

Ditto below for depth and label.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqwA_ADA8tMggg7zQj:-MyqwA_ADA8tMggg7zQk:bd2ujto) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/dev/test/render_engine_gltf_client_test.cc#L43)):*
> ```cpp
> 
>   // Allow the HttpService backend to be swapped out.
>   void SetHttpService(std::unique_ptr<internal::HttpService> service) {
> ```

nit A bunch of "internal::" in this file should go away now, thoughout.

**Review by svenevs — COMMENTED** [review]
Changes :lgtm: as well, but it may be a good idea to `const` the `RenderingPipeline` access method.  Jeremy what are your thoughts?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846#-:-Myr5W-19HsI8BgbYdby:b-8gelz3)* status: 6 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

___
*[geometry/render/render_engine_vtk.h, line 167 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqunVy3rRm_7BLzmca:-Myr332u-_qin62qR4ng:b-gsrd5c) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It's not clear to be why "p" is a pointer, instead of a reference.  It does not appear to meet any of the usual criteria (is nullable, is non-const, is retained, or is an output).
</blockquote></details>

FYI this is a remnant of previous code, glTF work did not create this.
___
*[geometry/render/render_engine_vtk.h, line 182 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-Myr3E8eAUERuHPW8Vtd:-Myr3E8eAUERuHPW8Vte:b-lgrjsl) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L182)):*
> ```objc
>   /** Provides access to the private data member pipeline_ by returning a
>    mutable RenderingPipeline reference. */
>   RenderingPipeline& get_mutable_pipeline(internal::ImageType image_type) const;
> ```

FYI "officially" this can be a `const RenderingPipeline&`.  For the same reason that the existing `UpdateWindow` and `PerformVtkUpdate` can take `const RenderingPipeline` references / pointers -- it's kind of a lie since under the hood the VTK member variables do get modified deep within the trenches of the VTK rendering pipeline.  But the `RenderingPipeline` itself, does not get modified (nor should it).

```diff
diff --git a/geometry/render/dev/render_engine_gltf_client.cc b/geometry/render/dev/render_engine_gltf_client.cc
index 798460c490..35bdac2b65 100644
--- a/geometry/render/dev/render_engine_gltf_client.cc
+++ b/geometry/render/dev/render_engine_gltf_client.cc
@@ -235,7 +235,7 @@ void RenderEngineGltfClient::DoRenderColorImage(
     LogFrameStart(ImageType::kColor, color_scene_id);
   }
 
-  const auto& color_pipeline = get_mutable_pipeline(ImageType::kColor);
+  const auto& color_pipeline = get_pipeline(ImageType::kColor);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera.core(), camera.show_window(),
                &color_pipeline, "Color Image");
@@ -270,7 +270,7 @@ void RenderEngineGltfClient::DoRenderDepthImage(
     LogFrameStart(ImageType::kDepth, depth_scene_id);
   }
 
-  const auto& depth_pipeline = get_mutable_pipeline(ImageType::kDepth);
+  const auto& depth_pipeline = get_pipeline(ImageType::kDepth);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera, &depth_pipeline);
   PerformVtkUpdate(depth_pipeline);
@@ -304,7 +304,7 @@ void RenderEngineGltfClient::DoRenderLabelImage(
     LogFrameStart(ImageType::kLabel, label_scene_id);
   }
 
-  const auto& label_pipeline = get_mutable_pipeline(ImageType::kLabel);
+  const auto& label_pipeline = get_pipeline(ImageType::kLabel);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera.core(), camera.show_window(),
                &label_pipeline, "Label Image");
@@ -346,7 +346,7 @@ std::string RenderEngineGltfClient::ExportScene(ImageType image_type,
                                                 int64_t scene_id) const {
   vtkNew<vtkGLTFExporter> gltf_exporter;
   gltf_exporter->InlineDataOn();
-  gltf_exporter->SetRenderWindow(get_mutable_pipeline(image_type).window);
+  gltf_exporter->SetRenderWindow(get_pipeline(image_type).window);
   const std::string scene_path = ExportPathFor(image_type, scene_id);
   gltf_exporter->SetFileName(scene_path.c_str());
   gltf_exporter->Write();
@@ -361,7 +361,7 @@ void RenderEngineGltfClient::CleanupFrame(const std::string& scene_path,
 
 Eigen::Matrix4d RenderEngineGltfClient::CameraModelViewTransformMatrix(
     ImageType image_type) const {
-  auto* cam = get_mutable_pipeline(image_type).renderer->GetActiveCamera();
+  auto* cam = get_pipeline(image_type).renderer->GetActiveCamera();
   const auto* vtk_mat = cam->GetModelViewTransformMatrix();
   Eigen::Matrix4d ret;
   for (int i = 0; i < 4; ++i) {
diff --git a/geometry/render/render_engine_vtk.cc b/geometry/render/render_engine_vtk.cc
index 0c1632a8a4..11033c4aa4 100644
--- a/geometry/render/render_engine_vtk.cc
+++ b/geometry/render/render_engine_vtk.cc
@@ -571,7 +571,7 @@ void RenderEngineVtk::ImplementGeometry(vtkPolyDataAlgorithm* source,
   actors_.insert({data.id, std::move(actors)});
 }
 
-RenderEngineVtk::RenderingPipeline& RenderEngineVtk::get_mutable_pipeline(
+const RenderEngineVtk::RenderingPipeline& RenderEngineVtk::get_pipeline(
     internal::ImageType image_type) const {
   DRAKE_DEMAND(image_type >= ImageType::kColor &&
                image_type <= ImageType::kDepth);
diff --git a/geometry/render/render_engine_vtk.h b/geometry/render/render_engine_vtk.h
index 9623bdf59f..a7fe1dcb51 100644
--- a/geometry/render/render_engine_vtk.h
+++ b/geometry/render/render_engine_vtk.h
@@ -179,7 +179,7 @@ class RenderEngineVtk : public RenderEngine,
 
   /** Provides access to the private data member pipeline_ by returning a
    mutable RenderingPipeline reference. */
-  RenderingPipeline& get_mutable_pipeline(internal::ImageType image_type) const;
+  const RenderingPipeline& get_pipeline(internal::ImageType image_type) const;
 
  private:
   // @see RenderEngine::DoRegisterVisual().
```
___
*[geometry/render/render_engine_vtk.cc, line 577 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-Myr4mte0IyMFE8FciFq:-Myr4mte0IyMFE8FciFr:by1haof) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.cc#L577)):*
> ```cpp
>     internal::ImageType image_type) const {
>   DRAKE_DEMAND(image_type >= ImageType::kColor &&
>                image_type <= ImageType::kDepth);
> ```

Nit: `RenderEngineVtk` will crash in the event that somebody added something to `ImageType` between `kColor` and `kDepth`.  Probably best to be fully explicit (see `kNumPipelines` member, only 3 allowed, this enum used to be in the `.cc` file only).

```cpp
DRAKE_DEMAND(image_type == ImageType::kColor ||
             image_type == ImageType::kDepth ||
             image_type == ImageType::kLabel);
```

Order is not relevant, elsewhere in the implementation I somewhat arbitrarily always ordered things as color - depth - label.
___
*[geometry/render/dev/render_engine_gltf_client.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqvZD46rD1Eptf_C7c:-Myr2qR7EeAaXIdBmCba:b-br324r) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/dev/render_engine_gltf_client.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This line could unwrap now that we have more space?
</blockquote></details>

FYI all the files I created (so excluding `RenderEngineVtk` for this PR) were being fed through clang-format so there should be a fairly minimal diff if you re-format: `clang-format-9 -i -style=file geometry/render/dev/{file_to_format}`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: 7 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri, @svenevs, and @zachfang)

___
*[geometry/render/render_engine_vtk.h, line 167 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyqunVy3rRm_7BLzmca:-Myr9mks8yp_qSUb46uX:b-o96i37) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L167)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI this is a remnant of previous code, glTF work did not create this.
</blockquote></details>

Indeed, but it's still broken.  Elevating code out of private means fixing it too.
___
*[geometry/render/render_engine_vtk.h, line 182 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16846#-Myr3E8eAUERuHPW8Vtd:-Myr9sGL4HrnqiA3X6BE:b-nvhl68) ([raw file](https://github.com/robotlocomotion/drake/blob/86db1b62bb9c1581b43bb9987d21eaca4448ec58/geometry/render/render_engine_vtk.h#L182)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI "officially" this can be a `const RenderingPipeline&`.  For the same reason that the existing `UpdateWindow` and `PerformVtkUpdate` can take `const RenderingPipeline` references / pointers -- it's kind of a lie since under the hood the VTK member variables do get modified deep within the trenches of the VTK rendering pipeline.  But the `RenderingPipeline` itself, does not get modified (nor should it).

```diff
diff --git a/geometry/render/dev/render_engine_gltf_client.cc b/geometry/render/dev/render_engine_gltf_client.cc
index 798460c490..35bdac2b65 100644
--- a/geometry/render/dev/render_engine_gltf_client.cc
+++ b/geometry/render/dev/render_engine_gltf_client.cc
@@ -235,7 +235,7 @@ void RenderEngineGltfClient::DoRenderColorImage(
     LogFrameStart(ImageType::kColor, color_scene_id);
   }
 
-  const auto& color_pipeline = get_mutable_pipeline(ImageType::kColor);
+  const auto& color_pipeline = get_pipeline(ImageType::kColor);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera.core(), camera.show_window(),
                &color_pipeline, "Color Image");
@@ -270,7 +270,7 @@ void RenderEngineGltfClient::DoRenderDepthImage(
     LogFrameStart(ImageType::kDepth, depth_scene_id);
   }
 
-  const auto& depth_pipeline = get_mutable_pipeline(ImageType::kDepth);
+  const auto& depth_pipeline = get_pipeline(ImageType::kDepth);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera, &depth_pipeline);
   PerformVtkUpdate(depth_pipeline);
@@ -304,7 +304,7 @@ void RenderEngineGltfClient::DoRenderLabelImage(
     LogFrameStart(ImageType::kLabel, label_scene_id);
   }
 
-  const auto& label_pipeline = get_mutable_pipeline(ImageType::kLabel);
+  const auto& label_pipeline = get_pipeline(ImageType::kLabel);
   // Update the VTK scene before exporting to glTF.
   UpdateWindow(camera.core(), camera.show_window(),
                &label_pipeline, "Label Image");
@@ -346,7 +346,7 @@ std::string RenderEngineGltfClient::ExportScene(ImageType image_type,
                                                 int64_t scene_id) const {
   vtkNew<vtkGLTFExporter> gltf_exporter;
   gltf_exporter->InlineDataOn();
-  gltf_exporter->SetRenderWindow(get_mutable_pipeline(image_type).window);
+  gltf_exporter->SetRenderWindow(get_pipeline(image_type).window);
   const std::string scene_path = ExportPathFor(image_type, scene_id);
   gltf_exporter->SetFileName(scene_path.c_str());
   gltf_exporter->Write();
@@ -361,7 +361,7 @@ void RenderEngineGltfClient::CleanupFrame(const std::string& scene_path,
 
 Eigen::Matrix4d RenderEngineGltfClient::CameraModelViewTransformMatrix(
     ImageType image_type) const {
-  auto* cam = get_mutable_pipeline(image_type).renderer->GetActiveCamera();
+  auto* cam = get_pipeline(image_type).renderer->GetActiveCamera();
   const auto* vtk_mat = cam->GetModelViewTransformMatrix();
   Eigen::Matrix4d ret;
   for (int i = 0; i < 4; ++i) {
diff --git a/geometry/render/render_engine_vtk.cc b/geometry/render/render_engine_vtk.cc
index 0c1632a8a4..11033c4aa4 100644
--- a/geometry/render/render_engine_vtk.cc
+++ b/geometry/render/render_engine_vtk.cc
@@ -571,7 +571,7 @@ void RenderEngineVtk::ImplementGeometry(vtkPolyDataAlgorithm* source,
   actors_.insert({data.id, std::move(actors)});
 }
 
-RenderEngineVtk::RenderingPipeline& RenderEngineVtk::get_mutable_pipeline(
+const RenderEngineVtk::RenderingPipeline& RenderEngineVtk::get_pipeline(
     internal::ImageType image_type) const {
   DRAKE_DEMAND(image_type >= ImageType::kColor &&
                image_type <= ImageType::kDepth);
diff --git a/geometry/render/render_engine_vtk.h b/geometry/render/render_engine_vtk.h
index 9623bdf59f..a7fe1dcb51 100644
--- a/geometry/render/render_engine_vtk.h
+++ b/geometry/render/render_engine_vtk.h
@@ -179,7 +179,7 @@ class RenderEngineVtk : public RenderEngine,
 
   /** Provides access to the private data member pipeline_ by returning a
    mutable RenderingPipeline reference. */
-  RenderingPipeline& get_mutable_pipeline(internal::ImageType image_type) const;
+  const RenderingPipeline& get_pipeline(internal::ImageType image_type) const;
 
  private:
   // @see RenderEngine::DoRegisterVisual().
```
</blockquote></details>

There is a TODO in the cc file that the `const`-ness around this facet is broken.  Since we're going to be mutating these things, non-const seems correct even if C++ let's us use misleading consts in other places in the code for the moment.

**Review by zachfang — COMMENTED** [review]
+@xuchenhan-tri for platform review. Thanks!

Mainly on two files, `geometry/render/render_engine_vtk.h` and `geometry/render/render_engine_vtk.cc`. We promoted some private functions and added a getter function to expose `pipeline_` private member data for the derived class, RenderEngineGltfClient (currently in dev).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846#-:-MysVWbw413sSmwwNXiG:btcu5ut)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Comment by zachfang** [comment]
Also, as Jeremy mentioned, this PR also changed the function signature of `UpdateWindow(...)` in RenderEngineVtk to use const reference instead of const pointer.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with two documentation requests/questions.

> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846#-:-Mysi6sXE95bOBej-2Nf:b-rjk16k)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[geometry/render/render_engine_vtk.h, line 165 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyshKJZ60ZGLkhLlocC:-MyshKJZ60ZGLkhLlocD:b6g0rra) ([raw file](https://github.com/robotlocomotion/drake/blob/97e2cdbfdf7d2544be802873e2427924f06b0509/geometry/render/render_engine_vtk.h#L165)):*
> ```objc
> 
>   /** Configures the VTK model to reflect the given `camera`, this includes
>    render size camera intrinsics, visible windows, etc. */
> ```

nit, it's not clear to me how the `show_window` and `name` parameters should be used from the documentation and why they are omitted in the signature below. Could you clarify in the documentatino?
___
*[geometry/render/render_engine_vtk.h, line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyshvGt7n25UC0MdyyC:-MyshvGt7n25UC0MdyyD:bnq8652) ([raw file](https://github.com/robotlocomotion/drake/blob/97e2cdbfdf7d2544be802873e2427924f06b0509/geometry/render/render_engine_vtk.h#L182)):*
> ```objc
>   /** Provides access to the private data member pipeline_ by returning a
>    mutable RenderingPipeline reference. */
>   RenderingPipeline& get_mutable_pipeline(internal::ImageType image_type) const;
> ```

nit, there's an implicit requirement that `image_type` must be one of three types. Probably worth mentioning in the doc?

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri and @zachfang)

___
*[geometry/render/render_engine_vtk.h, line 165 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyshKJZ60ZGLkhLlocC:-Mysk2CkDP_IavEtslD5:b-sswvgw) ([raw file](https://github.com/robotlocomotion/drake/blob/97e2cdbfdf7d2544be802873e2427924f06b0509/geometry/render/render_engine_vtk.h#L165)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it's not clear to me how the `show_window` and `name` parameters should be used from the documentation and why they are omitted in the signature below. Could you clarify in the documentatino?
</blockquote></details>

For docs update, helpful to know that `show_window` is a pass-through parameter for `ColorRenderCamera::show_window()` (`render_camera.h`, user requests renderer to display window), `name` is the title of the window that will be displayed when `show_window=true`. Something like "when `show_window=true` the VTK window will be displayed with a window title `name`" or similar

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri, @svenevs, and @xuchenhan-tri)

___
*[geometry/render/render_engine_vtk.h, line 165 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyshKJZ60ZGLkhLlocC:-MytKBZy5AuHoCEnnDGn:b-1pwkso) ([raw file](https://github.com/robotlocomotion/drake/blob/97e2cdbfdf7d2544be802873e2427924f06b0509/geometry/render/render_engine_vtk.h#L165)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

For docs update, helpful to know that `show_window` is a pass-through parameter for `ColorRenderCamera::show_window()` (`render_camera.h`, user requests renderer to display window), `name` is the title of the window that will be displayed when `show_window=true`. Something like "when `show_window=true` the VTK window will be displayed with a window title `name`" or similar
</blockquote></details>

Done. Thank you both. Let me know if anything is still unclear.
___
*[geometry/render/render_engine_vtk.h, line 182 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16846#-MyshvGt7n25UC0MdyyC:-MytKLBw4kYg4iplxI6g:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/97e2cdbfdf7d2544be802873e2427924f06b0509/geometry/render/render_engine_vtk.h#L182)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, there's an implicit requirement that `image_type` must be one of three types. Probably worth mentioning in the doc?
</blockquote></details>

Done. PTAL.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16846)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @zachfang)

**Pull request merged**
