### PR TITLE
solvers: Report error when snopt fails to set a solver parameter

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947#-:-MZ7cRwm-IeINYzT4Vki:b-n689ep)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ericcousineau-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947#-:-MZ9QoZvA2FJz5ODN6hC:bfacy11)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: Yay another easy one!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947#-:-MZDP4VE-1pqHg1qNVNN:b-ss49ia)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14947#-MZDP-Np5r5k6L1Xlway:-MZDP-NqB1nTWUNrZVuq:b-hmdo10) (no related file):*
BTW If possible, would be nice to see a test (e.g. a super-invalid parameter in Snopt's eyes). Will hold off on merging, but won't block on it either!

---

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14947#-MZDP-Np5r5k6L1Xlway:-MZDUS3-0lD7MMJ8qpzt:b41iqzc) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW If possible, would be nice to see a test (e.g. a super-invalid parameter in Snopt's eyes). Will hold off on merging, but won't block on it either!
</blockquote></details>

totally reasonable.  i'll update it with a unit test tonight.

---

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14947#-MZDP-Np5r5k6L1Xlway:-MZDmYXhAl4BI2ttZait:b-nx6fv1) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

totally reasonable.  i'll update it with a unit test tonight.
</blockquote></details>

Done.  (the PR is now 12x larger. ;-)

---

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14947)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14947#-MZDP-Np5r5k6L1Xlway:-MZDqo-j-kSw8weRH8xk:b-ieyay5) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (the PR is now 12x larger. ;-)
</blockquote></details>

OK Sweet, thanks!

---
___
*[solvers/test/snopt_solver_test.cc, line 505 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14947#-MZDqfaK1r_0yBmzwOni:-MZDqfaL7a6AYvrJZVOx:b-3tajoa) ([raw file](https://github.com/robotlocomotion/drake/blob/85fa9836b683a33c644fb8366987545313f96684/solvers/test/snopt_solver_test.cc#L505)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(solver.Solve(prog),
>       std::exception,
>       "Error setting Snopt integer parameter not an option");
> ```

BTW May be more readable to surround the param name with `'` given that spaces are admissible for name. Not important for now, tho!

**Pull request merged**
