### PR TITLE
Add a unit length constraint program for testing

### PR DESCRIPTION
**Pull request by hongkai-dai**
This test that we can add a quadratic constraint as a generic nonlinear constraint, and solve it through nonlinear optimization.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8158)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/nonlinear_program_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L63n5mT4PGhf6PiI-P-:-L63n5mUnD5kBBbnXaBG:bqlrq33) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ee3f6d962b324d7b7ead78457acec88417c714/solvers/test/nonlinear_program_test.cc#L390)):*
> ```cpp
> 
>   prob.SetInitialGuessForAllVariables(Vector4d(1, 0, 0, 0));
>   RunNonlinearProgram(&prob, [&]() {prob.CheckSolution();});
> ```

Can you limit the capture's scope to just `[&prob]`?

---

*[solvers/test/nonlinear_program_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L63naWHk7ivVApJ6ha8:-L63naWHk7ivVApJ6ha9:b2gmqe8) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ee3f6d962b324d7b7ead78457acec88417c714/solvers/test/nonlinear_program_test.cc#L390)):*
> ```cpp
> 
>   prob.SetInitialGuessForAllVariables(Vector4d(1, 0, 0, 0));
>   RunNonlinearProgram(&prob, [&]() {prob.CheckSolution();});
> ```

`CheckSolution` looks like it just returns true or false, which will be ignored by this.
Can you add something like `DRAKE_THROW_UNLESS` to these lambdas? Maybe something like:

```
auto test_func = [&prob]() { DRAKE_THROW_UNLESS(prob.CheckSolution()); };

// For both invocations:
RunNonlinearProgram(&prob, test_func);
```

Can you also add a quick non-doxygen comment to `RunNonlinearProgram` stating that `test_func` is *only* checked by whether or not it throws?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-:-L63oB4d0Hh_zhZeHGB3:b-2l0s3s)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/nonlinear_program_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L63naWHk7ivVApJ6ha8:-L63oFSzH-3DwzTBqoXB:b-ezz5lr) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ee3f6d962b324d7b7ead78457acec88417c714/solvers/test/nonlinear_program_test.cc#L390)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

`CheckSolution` looks like it just returns true or false, which will be ignored by this.
Can you add something like `DRAKE_THROW_UNLESS` to these lambdas? Maybe something like:

```
auto test_func = [&prob]() { DRAKE_THROW_UNLESS(prob.CheckSolution()); };

// For both invocations:
RunNonlinearProgram(&prob, test_func);
```

Can you also add a quick non-doxygen comment to `RunNonlinearProgram` stating that `test_func` is *only* checked by whether or not it throws?
</blockquote></details>

That, or use `EXPECT_TRUE(prob.CheckSolution())`, or put the `EXPECT_*` in `CheckSolution` - that's what the other problems appear to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8158)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/nonlinear_program_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L63n5mT4PGhf6PiI-P-:-L64En_Mrhi4inR_tc89:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ee3f6d962b324d7b7ead78457acec88417c714/solvers/test/nonlinear_program_test.cc#L390)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you limit the capture's scope to just `[&prob]`?
</blockquote></details>

Done.

---

*[solvers/test/nonlinear_program_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L63naWHk7ivVApJ6ha8:-L64IVs9D-CfyaAbfXnG:b-eaubwv) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ee3f6d962b324d7b7ead78457acec88417c714/solvers/test/nonlinear_program_test.cc#L390)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

That, or use `EXPECT_TRUE(prob.CheckSolution())`, or put the `EXPECT_*` in `CheckSolution` - that's what the other problems appear to do.
</blockquote></details>

Done, good catch, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-:-L64IpXDSZgcCR3ZcScg:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a few BTWs.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/nonlinear_program_test.cc, line 395 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8158#-L64aXlV6r3yi3m5cCIt:-L64aXlV6r3yi3m5cCIu:b-g5ydmi) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/nonlinear_program_test.cc#L395)):*
> ```cpp
>   // constraint.
>   prob.SetInitialGuessForAllVariables(Vector4d(1, 2, 3, 4));
>   RunNonlinearProgram(&prob, [&prob]() {prob.CheckSolution();});
> ```

BTW is there a settable tolerance for RunNonlinearProgram? If so consider setting it to something explicit here that could be passed to CheckSolution(). Right now it looks like CheckSolution has to hard code some secret knowledge about the default tolerance?

---

*[solvers/test/optimization_examples.cc, line 641 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8158#-L64_3jvBiEgI6CMC8AC:-L64_3jvBiEgI6CMC8AD:b-iq4tkv) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/optimization_examples.cc#L641)):*
> ```cpp
>     : MathematicalProgram(), x_(NewContinuousVariables<4>()) {
>   auto unit_length_constraint = std::make_shared<QuadraticConstraint>(
>       2 * Eigen::Matrix4d::Identity(), Eigen::Vector4d::Zero(), 1, 1);
> ```

FYI I am always confused by the factor of 2 needed to specify quadratic constraints, where 2*I is the identity! Please consider having mercy on naive readers and including a comment here saying what the arguments mean here so it is clear that this is xᵀx = 1 (or xᵀIx = 1!)

---

*[solvers/test/optimization_examples.cc, line 648 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8158#-L64_vn_4U3uatu0tvTv:-L64_vn_4U3uatu0tvTw:bdpwf3b) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/optimization_examples.cc#L648)):*
> ```cpp
>   const auto x_val = GetSolution(x_);
>   const double tol{1E-8};
>   EXPECT_NEAR(x_val.squaredNorm(), 1, tol);
> ```

BTW if this is actually the square of the tolerance, should have a name like tol_squared rather than tol. 
BTW It looks like the expected tolerance here is actually
1e-4. Is that reasonable?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8158#-:-L64aoyI7GOeeczC9ePm:b-i06ut8)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/test/nonlinear_program_test.cc, line 395 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L64aXlV6r3yi3m5cCIt:-L65BdP6OFodY1rH-n8B:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/nonlinear_program_test.cc#L395)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there a settable tolerance for RunNonlinearProgram? If so consider setting it to something explicit here that could be passed to CheckSolution(). Right now it looks like CheckSolution has to hard code some secret knowledge about the default tolerance?
</blockquote></details>

Done

---

*[solvers/test/optimization_examples.cc, line 641 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L64_3jvBiEgI6CMC8AC:-L65DmO8QKBz9tJHh_6L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/optimization_examples.cc#L641)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI I am always confused by the factor of 2 needed to specify quadratic constraints, where 2*I is the identity! Please consider having mercy on naive readers and including a comment here saying what the arguments mean here so it is clear that this is xᵀx = 1 (or xᵀIx = 1!)
</blockquote></details>

Done.

---

*[solvers/test/optimization_examples.cc, line 648 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8158#-L64_vn_4U3uatu0tvTv:-L65CfpmKdFYZyEXYigy:b5iggpw) ([raw file](https://github.com/robotlocomotion/drake/blob/95809e28a58c7e79ea85fa8753a00cca4e2d4826/solvers/test/optimization_examples.cc#L648)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if this is actually the square of the tolerance, should have a name like tol_squared rather than tol. 
BTW It looks like the expected tolerance here is actually
1e-4. Is that reasonable?
</blockquote></details>

I think this is actually the tolerance. The constraint I impose is
```
xᵀx = 1
```
So I check how much constraint violation is at the solution, by comparing `xᵀx - 1` to the tolerance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8158)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8158)*

**Pull request merged**
