### PR TITLE
Add MathematicalProgram::AddLinearEqualityConstraint(const Formula& f)

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue: https://github.com/RobotLocomotion/drake/issues/5650

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5748)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please. Thank you!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-:-Kh30HuOvtPYHsfv4u4n:b-4cootz)*

**Comment by hongkai-dai** [comment]
:lgtm: +@david-german-tri for platform review please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1413 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh34VvwNJo6wpktG44h:-Kh34Vvxe94zHh9g4P1j:b-ik5r8r) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d524eca7946ab732b14eb65d37dec134fb8b2a/drake/solvers/test/mathematical_program_test.cc#L1413)):*
> ```cpp
> GTEST_TEST(testMathematicalProgram, AddSymbolicLinearEqualityConstraint5) {
>   MathematicalProgram prog;
>   auto x = prog.NewContinuousVariables<3>("2");
> ```

The name of the variable is `2`? Is this a typo of `x`?

---

*[drake/solvers/test/mathematical_program_test.cc, line 1466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh36ZYQdlCG5i5y1JNe:-Kh36ZYQdlCG5i5y1JNf:b-kyfrmi) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d524eca7946ab732b14eb65d37dec134fb8b2a/drake/solvers/test/mathematical_program_test.cc#L1466)):*
> ```cpp
>   // representation, we need to check if `exprs_in_added_constraint` is a
>   // permutation of `expected_exprs`.
>   EXPECT_TRUE(is_permutation(
> ```

Good to know we can use `is_permutation` for the check, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-:-Kh36mZMDjpcLGXc19V-:b-8bm2ul)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1413 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh34VvwNJo6wpktG44h:-Kh38MrfciaJI_W325xZ:b-hakueo) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d524eca7946ab732b14eb65d37dec134fb8b2a/drake/solvers/test/mathematical_program_test.cc#L1413)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The name of the variable is `2`? Is this a typo of `x`?
</blockquote></details>

Done. Nice catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3EeOJwZcMsVwTynUO:-Kh3EeOJwZcMsVwTynUP:b-4vlzpb) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/mathematical_program.cc#L48)):*
> ```cpp
> using std::unordered_map;
> using std::vector;
> using std::set;
> ```

BTW alphabetize

---

*[drake/solvers/mathematical_program.cc, line 853 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3FJZ_y51zQmr_K2cf:-Kh3FJZ_y51zQmr_K2cg:bk2fd4g) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/mathematical_program.cc#L853)):*
> ```cpp
>       //      (lhs - rhs == 0)
>       v(i) = get_lhs_expression(f) - get_rhs_expression(f);
>     } else {
> ```

BTW, could conjunctions be delegated back to the other overload here?  (I'm not certain that's correct, and have no idea whether it's useful - just curious.)

---

*[drake/solvers/test/mathematical_program_test.cc, line 1466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh36ZYQdlCG5i5y1JNe:-Kh3HLm8Zm2qOxcnZ_ue:b-66f6dq) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d524eca7946ab732b14eb65d37dec134fb8b2a/drake/solvers/test/mathematical_program_test.cc#L1466)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good to know we can use `is_permutation` for the check, thanks!
</blockquote></details>

+1, nice.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1452 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3Gsx4GxG4wEBxJZe8:-Kh3Gsx4GxG4wEBxJZe9:b-mb0b94) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/test/mathematical_program_test.cc#L1452)):*
> ```cpp
>       -5.0;
>   // clang-format on
>   const Formula f{A * x == b};
> ```

BTW, wow, what is happening under the hood here?  Does this vector formula automatically become a conjunction?  That's awesome!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 853 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3FJZ_y51zQmr_K2cf:-Kh3JSjN-my537YXVqhA:b-riysta) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/mathematical_program.cc#L853)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, could conjunctions be delegated back to the other overload here?  (I'm not certain that's correct, and have no idea whether it's useful - just curious.)
</blockquote></details>

I have an implicit assumption here that this function is called with an argument obtained by `get_operand(a_conjunctive_formula)`. With the assumption, I can have the following reasoning:

1) We flatten/simplify conjunctions at construction as follows:
    ```c++
    (f1 && f2) && (f3 && f4)  ==> (f1 && f2 && f3 && f4)
    ```
2) As a result, for a conjunctive formula `f`, we have an invariant:
    ```c++
    ∀ fᵢ ∈ get_operands(f). ¬is_conjunction(fᵢ).
    ```
3) So, we don't have another conjuntion inside of the loop of this function.

I'll add documentation and amend the exception message to state the assumption.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1466 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh36ZYQdlCG5i5y1JNe:-Kh3KrZpmAf55kGD4pna:botimpy) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d524eca7946ab732b14eb65d37dec134fb8b2a/drake/solvers/test/mathematical_program_test.cc#L1466)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

+1, nice.
</blockquote></details>

BTW, I wish Eigen classes provide standard iterators supports (such as `.begin()` and `.end()`) so that we can use STL algorithms instead of writing loops by ourselves.

We can use `.data()` but it's limited because
 - Its traversing order is bound to the storage order of the corresponding matrix (i.e. `RowMajor` / `ColMajor`). 
 - No support for views such as `.triangularView(Eien::Lower)`.

AFAIK, this is on Eigen team's TODO list but it's not implemented yet.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1452 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3Gsx4GxG4wEBxJZe8:-Kh3KqU5d5eEogr6mHBn:b-re7k1c) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/test/mathematical_program_test.cc#L1452)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, wow, what is happening under the hood here?  Does this vector formula automatically become a conjunction?  That's awesome!
</blockquote></details>

Yes, we have quite a lot of operators overloading. For example,

```c++
// Here, both of LHS and RHS are Eigen::Matrix, so it forms symbolic::Formula.
A * x == b

// While the following forms Eigen::Array<Formula>.
(A * x).array() == b.array()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3EeOJwZcMsVwTynUO:-Kh3PHSkdJVLv-8SQdjT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/mathematical_program.cc#L48)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW alphabetize
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 853 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3FJZ_y51zQmr_K2cf:-Kh3RFUgEf1KRx8rrfW7:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/b752e1e7473880d005134727fb72a80f5956fa91/drake/solvers/mathematical_program.cc#L853)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I have an implicit assumption here that this function is called with an argument obtained by `get_operand(a_conjunctive_formula)`. With the assumption, I can have the following reasoning:

1) We flatten/simplify conjunctions at construction as follows:
    ```c++
    (f1 && f2) && (f3 && f4)  ==> (f1 && f2 && f3 && f4)
    ```
2) As a result, for a conjunctive formula `f`, we have an invariant:
    ```c++
    ∀ fᵢ ∈ get_operands(f). ¬is_conjunction(fᵢ).
    ```
3) So, we don't have another conjuntion inside of the loop of this function.

I'll add documentation and amend the exception message to state the assumption.
</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3YEed22SpVv89eg-x:-Kh3YEefViEmEzV5m54n:b2ml24r) ([raw file](https://github.com/robotlocomotion/drake/blob/86681de9848d932724cc10fa5de163b6e5188916/drake/solvers/mathematical_program.cc#L43)):*
> ```cpp
> using std::runtime_error;
> using std::set;
> using std::set;
> ```

BTW duplicate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-:-Kh3YS9NFcCzfqdRhfNJ:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5748#-Kh3YEed22SpVv89eg-x:-Kh3bvtJWGFmue0FMGVP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/86681de9848d932724cc10fa5de163b6e5188916/drake/solvers/mathematical_program.cc#L43)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW duplicate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5748)*

**Pull request merged**
