### PR TITLE
Use -undefined dynamic_lookup when linking to python on macOS

### LINKED ISSUE #7981: Python modules have explicit framework links on macOS
Relates #1183. This is the output of the `brew audit` command for a potential `libdrake` formula.

```
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/multibody/rigid_body_tree.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/multibody/rigid_body_plant.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/multibody/shapes.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/multibody/parsers.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/_common_py.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/solvers/gurobi.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/solvers/mosek.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/solvers/ipopt.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/solvers/_ik_py.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/solvers/_mathematicalprogram_py.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/examples/pendulum.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/_autodiffutils_py.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/_symbolic_py.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/systems/sensors.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/systems/analysis.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/systems/primitives.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/pydrake/systems/framework.so
            /usr/local/opt/libdrake/lib/python2.7/site-packages/lcm/_lcm.so
```

This is very common defect on macOS and the solution is exactly in the output, using `-undefined dynamic_lookup`.

FYI @EricCousineau-TRI.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #7981.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7983)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
All the Python tests are passing, but `//bindings/pydrake/util:cpp_param_pybind_test` and `//bindings/pydrake/util:cpp_template_pybind_test` are failing:

```
INFO: From Testing //bindings/pydrake/util:cpp_param_pybind_test:
==================== Test output for //bindings/pydrake/util:cpp_param_pybind_test:
dyld: Symbol not found: _PyBaseObject_Type
  Referenced from: /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/7991704094566416321/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/bindings/pydrake/util/cpp_param_pybind_test_cc
  Expected in: flat namespace
 in /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/7991704094566416321/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/bindings/pydrake/util/cpp_param_pybind_test_cc
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/7991704094566416321/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/tools/skylark/py_env_runner.py", line 15, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bindings/pydrake/util/cpp_param_pybind_test_cc']' returned non-zero exit status -6
================================================================================
```
```
INFO: From Testing //bindings/pydrake/util:cpp_param_pybind_test:
==================== Test output for //bindings/pydrake/util:cpp_param_pybind_test:
dyld: Symbol not found: _PyBaseObject_Type
  Referenced from: /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/4927125017562494182/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/bindings/pydrake/util/cpp_param_pybind_test_cc
  Expected in: flat namespace
 in /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/4927125017562494182/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/bindings/pydrake/util/cpp_param_pybind_test_cc
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/bazel-sandbox/4927125017562494182/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/cpp_param_pybind_test.runfiles/drake/tools/skylark/py_env_runner.py", line 15, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bindings/pydrake/util/cpp_param_pybind_test_cc']' returned non-zero exit status -6
================================================================================
```

@EricCousineau-TRI, any suggestions what is different about those tests?

**Comment by EricCousineau-TRI** [comment]
Not sure... Is it possible to get debug output from this error so that it could potentially point to a source location where this symbol is? (will see if I can try this out on our Mac machine)
From what I can remember, I don't do anything with direct Python, aside from casting to a Python `type`:
https://github.com/RobotLocomotion/drake/blob/9205b1b/bindings/pydrake/util/cpp_param_pybind.cc#L76

However, from what I've seen in the `pybind11` source code, not of these operations that I do deviate from what is covered.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7983#-:-L4lFczCE4DzAiUMfwQ4:b-r91dkt)*

**Comment by EricCousineau-TRI** [comment]
On second thought, if these are the only two tests that fail, then it may be due to use of `py::scoped_interpreter_guard` or something related. Other parts of the code make use of the `cpp_param` and `cpp_template`, so they should have failed if that's where the issue lay.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7983#-:-L4lHRCPXVL7HyRPlG-a:b-8ki2ig)*

**Comment by EricCousineau-TRI** [comment]
Tried [this suggestion](https://stackoverflow.com/a/36959706/7829525) (adding `-Wl,-export_dynamic`), but it did not work.

**Comment by EricCousineau-TRI** [comment]
Ah, the issue is that these are standalone binaries which rely on Python functionality, which used to be directly linked in, but now aren't.

The fix in this case would be update to `drake_pybind_cc_googletest` to link directly to the Python version.

This should be fine for now, since we don't distribute any standalone binaries that use the interpreter.
If we do distribute these binaries, then we would have to either (a) directly link to the Python library, or (b) update `DYLD_LIBRARY_PATH` or what not to ensure that the Python libraries get linked in.

**Comment by jamiesnape** [comment]
> The fix in this case would be update to drake_pybind_cc_googletest to link directly to the Python version.

Ok, I will try to do that. Just trying to think if there is an particularly elegant way to do that as I basically throw the information about the location of the library away. I will think of something.

**Comment by EricCousineau-TRI** [comment]
Perhaps having `python_repository` produce an additional library, which just adds that library flag explicitly, and have those targets link against them?

**Comment by jamiesnape** [comment]
> Perhaps having python_repository produce an additional library, which just adds that library flag explicitly, and have those targets link against them?

Yes, I am creating an extra target.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW doc request.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/python/repository.bzl, line 7 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/7983#-L4m7ewDAho6Fg27fYI1:-L4m7ewE2Cwwits6eebs:bbvcqto) ([raw file](https://github.com/robotlocomotion/drake/blob/6c400a0e352c4e817bcb620e9feb293df187c264/tools/workspace/python/repository.bzl#L7)):*
> ```Python
> Finds local system Python headers and libraries using python-config and
> makes them available to be used as a C/C++ dependency.
> ```

BTW Could you add a mention of the `python_direct_link` target? (no example needed, but perhaps a mention that you may encounter linker errors otherwise?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7983#-:-L4m7wYL7ZSDYPngUUIT:b-dzpr5r)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/python/repository.bzl, line 7 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/7983#-L4m7ewDAho6Fg27fYI1:-L4m9dGBC2oAVk_1WkLf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6c400a0e352c4e817bcb620e9feb293df187c264/tools/workspace/python/repository.bzl#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Could you add a mention of the `python_direct_link` target? (no example needed, but perhaps a mention that you may encounter linker errors otherwise?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7983)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by jamiesnape** [comment]
Failure on `mac-*-clang-bazel-experimental-everything` builds are unrelated to this PR.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7983#-:-L4pmWQ1N2_kE0ognyJk:bnfp4nl)*

**Pull request merged**
