### PR TITLE
Update num_constraint when updating the bounds in the constraint

### LINKED ISSUE #7862: constraint.UpdateCoefficients results in `num_constraints` being incorrect
Due to the licensing issues with Gurobi, I'm trying to play with other solvers in the `QPInverseDynamics` code in an attempt to find an acceptable substitute. My first attempt is using Ipopt (since it's widely used in Drake, even if it's not the ideal tool for this), but it's failing immediately:

```
Exception of type: INVALID_TNLP in file "IpTNLPAdapter.cpp" at line 596:
 Exception message: There are inconsistent bounds on constraint 89: lower =   3.4584595208887258e-323 and upper =    0.0000000000000000e+00.
[2018-01-25 16:14:48.193] [console] [warning] Solution not found.
terminate called after throwing an instance of 'std::runtime_error'
  what():  QpInverseDynamicsSystem: QP cannot solve
```

`3.4584595208887258e-323` looks a lot like uninitialized memory being interpreted as a `double`. Looking at the constraints being loaded into Ipopt shows a lot of similar uninitialized-looking data. I'll see if I can figure out what's going on.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix #7862 

@rdeits

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7892)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L4-Knd0-FfXtVlqDg3G:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
First pass done with some comments. PTAL.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[solvers/constraint.h, line 132 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7892#-L41ZX15Bpq2XGk3h3CW:-L41ZX15Bpq2XGk3h3CX:btdwuuv) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/constraint.h#L132)):*
> ```objc
>     lower_bound_ = lower_bound;
>     upper_bound_ = upper_bound;
>     set_num_outputs(lower_bound.rows());
> ```

I'd strongly prefer that this live directly in the constraints for which changing the number of outputs "on the fly" is valid.
Perhaps set this just for linear constraints?

---

*[solvers/constraint.h, line 485 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7892#-L41_REO-7ea0qgpcXKS:-L41_REO-7ea0qgpcXKT:bblj1e1) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/constraint.h#L485)):*
> ```objc
> 
>     A_ = new_A;
>     set_bounds(new_lb, new_ub);
> ```

Perhaps place the output resizing here?
This should also cover the `LinearEqualityConstraint` case.

---

*[solvers/evaluator_base.h, line 124 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7892#-L41_6QABk7LeqTdjxoT:-L41_6QABk7LeqTdjxoU:b-4lapmg) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/evaluator_base.h#L124)):*
> ```objc
>                       AutoDiffVecXd& y) const = 0;
> 
>   // Setter for the number of outputs.
> ```

Can you add a note of caution here, saying that the number of outputs should *only* be changed when the evaluator's structure permits it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7892#-:-L41_qOs0mcN2VEl46xV:b-mx8859)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/constraint.h, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L41ZX15Bpq2XGk3h3CW:-L43XYaNJPsngEek3Q4b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/constraint.h#L132)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I'd strongly prefer that this live directly in the constraints for which changing the number of outputs "on the fly" is valid.
Perhaps set this just for linear constraints?
</blockquote></details>

Done.

---

*[solvers/constraint.h, line 485 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L41_REO-7ea0qgpcXKS:-L43XY3K4Bp7u4tcRdEc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/constraint.h#L485)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Perhaps place the output resizing here?
This should also cover the `LinearEqualityConstraint` case.
</blockquote></details>

Done.

---

*[solvers/evaluator_base.h, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L41_6QABk7LeqTdjxoT:-L43XWnpUfvJF_XXv4vO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc0aae6583257a04ce36d9958d4e2768f349b897/solvers/evaluator_base.h#L124)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you add a note of caution here, saying that the number of outputs should *only* be changed when the evaluator's structure permits it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by hongkai-dai** [comment]
Thanks @ericcousineau-tri , that is an excellent point, that we should only allow `num_outputs` to change for a certain type of constraints.

I also changed `num_constraints()` return type to `int` instead of `size_t`.

---

Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L43Xni-RXbWKIGQi4vd:bz5eiyi)*

**Comment by EricCousineau-TRI** [comment]
Nice! I've added a few more comments.

:lgtm:, pending those items.

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[solvers/constraint.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43k8elz0pxhTi_5oKC:-L43k8elz0pxhTi_5oKD:b-vul69j) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L105)):*
> ```objc
> 
>  protected:
>   virtual bool DoCheckSatisfied(const Eigen::Ref<const Eigen::VectorXd>& x,
> ```

BTW Could these two blocks remain where they were?

---

*[solvers/constraint.h, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43k00hmn9c8rEUyhOZ:-L43k00ilGJggKefD-0s:bvkyhs2) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L142)):*
> ```objc
>                   const Eigen::MatrixBase<DerivedU>& upper_bound) {
>     if (lower_bound.rows() != upper_bound.rows() || lower_bound.cols() != 1 ||
>         upper_bound.cols() != 1 || lower_bound.rows() != num_constraints()) {
> ```

BTW This seems a wee bit indirect - could both `rows()` be compared to `num_constraints`?

---

*[solvers/constraint.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43kTStPhPDZ79mU55S:-L43kTStPhPDZ79mU55T:bikzhnl) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L487)):*
> ```objc
>   }
> 
>   using Constraint::UpdateLowerBound;
> ```

Should these still be directly exposed? These won't allow resizing - only `UpdateCoefficients` allows this.

I'm fine with them being hidden or shown, as long as there's a mention of whether they can allow resizing.
Perhaps the easiest way would be to only show `UpdateCoefficients`?

---

*[solvers/constraint.h, line 527 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43lCD_zQ6EUcirO39T:-L43lCD_zQ6EUcirO39U:biwxkbg) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L527)):*
> ```objc
>    */
>   template <typename DerivedA, typename DerivedB>
>   void UpdateCoefficients(const Eigen::MatrixBase<DerivedA>& Aeq,
> ```

BTW I just realized that, because we still expose `LinearConstraint::UpdateCoefficients`, then a user could make a `LinearEqualityConstraint` not really be an equality constraint by calling the overload.

Could you try to protect the original (something like `protected: using LinearConstraint::UpdateCoefficients`), or add a TODO to address this at some point?

(A user could still cast the equality constraint to an inequality constraint and modify it there, but that may be overhead than it's worth to address?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L43lXKg1mr8nP6nJfHc:bsnulxu)*

**Comment by sammy-tri** [comment]
First pass complete.  CI seems unhappy though.

---

Reviewed 1 of 3 files at r1, 5 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L46RlGnscAjKDhWUyNT:b-g85o4s)*

**Comment by hongkai-dai** [comment]
Thanks! The CI actually caught a bug in our code.

---

Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L46ru1JkMs8RqJyZZbl:b9l5ve)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/constraint.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43k8elz0pxhTi_5oKC:-L46s24c_v623geFutPZ:b-5nuh1n) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

These two blocks are still at the beginning of the `protected` block. Their line numbers are changed, because functions like `set_bounds()` which were in the public field above the protected field, are now moved down to the protected field below these two blocks.
</blockquote></details>

OK I think it'd be possible to just move up the `protected` block and keep the rest of the code where it is (to keep Git as clean as possible), but I'm fine with it as is.

---

*[solvers/constraint.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43kTStPhPDZ79mU55S:-L46sI0vBuUFmFXI4Jks:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L487)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I hide them not because whether they resize the constraint or not, but that some constraint class should not update lower or upper bounds. For example, the bounds of the `LorentzConeConstraint` are hard-coded. I add a documentation here in `Constraint::UpdateLowerBound`.
</blockquote></details>

OK Thanks!

---

*[solvers/constraint.h, line 527 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43lCD_zQ6EUcirO39T:-L46sMepzR0G6nGmx1Nu:by9if7f) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L527)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Good point. I moved `LinearEqualityConstraint::UpdateCoefficients` to private.
</blockquote></details>

OK Awesome! Is it possible to just do a `using` statement? If not, I think you could simply stub the function (not even implementing anything) - if there's a linker error, then there's an incorrect call to this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/constraint.h, line 123 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L46sh-cLPN5XUvk1Epd:-L46sh-cLPN5XUvk1Epe:btesrj9) ([raw file](https://github.com/robotlocomotion/drake/blob/f9872222f93c69bd2b7c3a0367fa929beeabba1d/solvers/constraint.h#L123)):*
> ```objc
>   /** Updates the lower bound.
>    * @note if the users want to expose this method in a sub-class, do
>    * using constraint::set_bounds, as in linearconstraint.
> ```

FYI Casing, should be `Constraint`, `LinearConstraint`?
(same in `UpdateUpperBound`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by hongkai-dai** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/constraint.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43k8elz0pxhTi_5oKC:-L46vB2ujvxeVNhJtxNz:bemcmxn) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L105)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK I think it'd be possible to just move up the `protected` block and keep the rest of the code where it is (to keep Git as clean as possible), but I'm fine with it as is.
</blockquote></details>

Done. I put `UpdateLowerBound` above `DoCheckSatisfied`.

---

*[solvers/constraint.h, line 527 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43lCD_zQ6EUcirO39T:-L46taNw6L8gTZxrHxdB:bcr75ae) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L527)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK Awesome! Is it possible to just do a `using` statement? If not, I think you could simply stub the function (not even implementing anything) - if there's a linker error, then there's an incorrect call to this function.
</blockquote></details>

I left a runtime error here, just in case future maintainers incorrectly called this function. Do you think it is better to stub the function as
```
private:
  template <typename DerivedA, typename DerivedL, typename DerivedU>
  void UpdateCoefficients(const Eigen::MatrixBase<DerivedA>& new_A,
                          const Eigen::MatrixBase<DerivedL>& new_lb,
                          const Eigen::MatrixBase<DerivedU>& new_ub) {
  }

```
?

---

*[solvers/constraint.h, line 123 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L46sh-cLPN5XUvk1Epd:-L46tJxQ1vww7BhJM4kt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9872222f93c69bd2b7c3a0367fa929beeabba1d/solvers/constraint.h#L123)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

FYI Casing, should be `Constraint`, `LinearConstraint`?
(same in `UpdateUpperBound`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/constraint.h, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43k8elz0pxhTi_5oKC:-L46wD1-8W7GFowJiWuV:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I put `UpdateLowerBound` above `DoCheckSatisfied`.
</blockquote></details>

OK Thanks!

---

*[solvers/constraint.h, line 527 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43lCD_zQ6EUcirO39T:-L46wIByms8SI6-3KLBG:b-6155zw) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L527)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I left a runtime error here, just in case future maintainers incorrectly called this function. Do you think it is better to stub the function as
```
private:
  template <typename DerivedA, typename DerivedL, typename DerivedU>
  void UpdateCoefficients(const Eigen::MatrixBase<DerivedA>& new_A,
                          const Eigen::MatrixBase<DerivedL>& new_lb,
                          const Eigen::MatrixBase<DerivedU>& new_ub) {
  }

```
?
</blockquote></details>

OK I'd say having the runtime error is better than stubbing it.
Actually, since this method is deferred (due to templating), it seems like you could do a `static_assert`, something like:
```
static_assert(!std::is_same<DerivedA, DerivedA>::value, "This method should not be called form `LinearEqualityConstraint`");
```
(I think `static_assert(false, ...`) would trigger right away, even if the template evaluation is deferred.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by hongkai-dai** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/constraint.h, line 527 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-L43lCD_zQ6EUcirO39T:-L46yaU6Fti2P0-CtC4b:b3jkem4) ([raw file](https://github.com/robotlocomotion/drake/blob/f57679745a541cb50abe0d20fb9b04f9d116121f/solvers/constraint.h#L527)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK I'd say having the runtime error is better than stubbing it.
Actually, since this method is deferred (due to templating), it seems like you could do a `static_assert`, something like:
```
static_assert(!std::is_same<DerivedA, DerivedA>::value, "This method should not be called form `LinearEqualityConstraint`");
```
(I think `static_assert(false, ...`) would trigger right away, even if the template evaluation is deferred.)
</blockquote></details>

Done. That is clever! Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L47IrImB6kF7aeSJQTW:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7892#-:-L47V6DERffEmrnXGKaQ:b-l70wzf)*

**Pull request merged**
