### PR TITLE
Add constructors to RollPitchYaw that takes RotationMatrix and Quaternion

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@sammy-tri 

Note to reviewers:
1.  Part of this update is a mostly cut-paste an algorithm in quaternion.h to new constructors in RollPitchYaw.
     The comment section of the algorithm is in roll_pitch_yaw.h.
     The code section of the algorithm is in roll_pitch_yaw.cc
2.  Cleanup (removing unnecessary methods, changing to new RollPitchYaw methods), etc in rotation_conversion_test.cc

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721#-:-LBNOsPSAEIpVtkk0JPP:b-tjw1hm)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/test/rotation_conversion_test.cc, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBOmaZ9BRThIplUlKzo:-LBOmaZ9BRThIplUlKzp:b-jfcrok) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/test/rotation_conversion_test.cc#L340)):*
> ```cpp
> }
> 
> #if 1
> ```

Remove `#if 1` and `#endif`

---

*[math/test/rotation_conversion_test.cc, line 377 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBOmgCO2REUzhwQ3mZd:-LBOmgCO2REUzhwQ3mZe:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/test/rotation_conversion_test.cc#L377)):*
> ```cpp
> }
> 
> #if 1
> ```

Ditto

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721#-:-LBOmzsa-HutyHdvGUgG:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

First pass complete.  Just one question about a comment.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/roll_pitch_yaw.h, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBROOy78Tq4aFAHNe_O:-LBROOy78Tq4aFAHNe_P:b-gotvw3) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/roll_pitch_yaw.h#L199)):*
> ```objc
>   //           `e2 = L2*sin(theta/2)`, `e3 = L3*sin(theta/2)`.
>   //
>   // Note:  There are only 5 elements of the 3x3 rotation matrix R used in this
> ```

It seems like the text of this note is fundamentally duplicated in Step 1?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721#-:-LBRNWF25gPlnzk7EI5t:bgbuoau)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 4 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721#-:-LBS2UyA3maS0HeMuFhJ:bnfp4nl)*

**Comment by mitiguy** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[math/roll_pitch_yaw.h, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBROOy78Tq4aFAHNe_O:-LBRqekx8vQCn4desldS:b-ifq24h) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/roll_pitch_yaw.h#L199)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems like the text of this note is fundamentally duplicated in Step 1?
</blockquote></details>

Done.  Good catch.  I had meant to delete that note.

---

*[math/test/rotation_conversion_test.cc, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBOmaZ9BRThIplUlKzo:-LBRqM0i1qyIgze6MMQj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/test/rotation_conversion_test.cc#L340)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Remove `#if 1` and `#endif`
</blockquote></details>

Done.

---

*[math/test/rotation_conversion_test.cc, line 377 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8721#-LBOmgCO2REUzhwQ3mZd:-LBRqMnU1DOjiv8mtwiu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a112940399f710b0f2f95abb3e3f3915dcabe56/math/test/rotation_conversion_test.cc#L377)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8721)*

**Pull request merged**
