### PR TITLE
Add instructions for getting Stackoverflow drake-tag notifications.

### PR DESCRIPTION
**Pull request by sherm1**
Adds to the Drake "For Developers" guidance instructions for how to get an email notification when a user asks a `drake`-tagged question on Stackoverflow.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13216)

### CODE REVIEW

**Comment by sherm1** [comment]
BTW to generate the documentation, use this command:
`bazel run //doc:serve_sphinx`
That will bring up a browser showing the Drake home page. Select "For Developers" then "Handling User StackOverflow Questions".

**Comment by jwnimmer-tri** [comment]
FYI All docs commands are at https://drake.mit.edu/documentation_instructions.html.  If there are any additional tips we should be using, add them there.

**Comment by jwnimmer-tri** [comment]
___
*[doc/developers.rst, line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13216#-M6W-zGw-R_CDIlWXgHX:-M6XH8aJ2OOK9BIEawo8:bo9ep12) ([raw file](https://github.com/robotlocomotion/drake/blob/799af3aacc92117ffbf7a8a7f493cc3818ad39ee/doc/developers.rst#L283)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sounds good to me!
</blockquote></details>

Hold (stay tuned).

**Comment by sherm1** [comment]
Per our recent agreement to encourage StackOverflow questions over Slack, many more people have signed up for StackOverflow drake-tagged notifications, and many more Drake developers should do so (to show them how is the point of this PR). Russ, Eric, me, Sean and more are receiving notifications and responding. What is the point of listing the names here? We have never had a corresponding list for `#onramp`, for example.

> Why not let Eric and Russ decide if they want to keep the list here, or elsewhere? 

I did ask and Eric responded "SGTM" to removing the list. I haven't heard from Russ yet.

**Pull request merged**
