### PR TITLE
Revert #2299

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Dear @amcastro-tri,

The oncall build cop, @mwoehlke-kitware, believes that your PR #2299 may have broken Drake's continuous integration build [1]. It is possible to break the build even if your PR passed continuous integration on presubmit, because additional platforms and tests are built in postsubmit.

The specific build failures under investigation are:

    https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-matlab/302/changes
    https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-ninja-continuous-matlab/46/changes

(Specifically, several atlas tests are newly failing.)

Therefore, the build cop has created this revert PR and started a complete postsubmit build to determine whether your PR was in fact the cause of the problem. If that build passes, this revert PR will be merged 60 minutes from now. You can then fix the problem at your leisure, and send a new PR to reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be reverted, please review and LGTM this PR. This allows the build cop to merge without waiting for CI results.

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2506)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Experimental builds:
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-matlab/56/
https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-experimental-matlab/5/

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware FYI, we in an all-simulation-hands meeting at TRI, so unlikely we will take any corrective action soon.

**Comment by david-german-tri** [comment]
I've just alerted @amcastro-tri in person.  

@mwoehlke-kitware Due to the aforementioned all-hands, and the size of this revert, please hold off merging this PR until Alejandro has had a chance to look at fixing forward, even though the 60 minutes have already elapsed.

**Comment by amcastro-tri** [comment]
Looking into this now. Thanks @david-german-tri for driving my attention to it.

**Comment by amcastro-tri** [comment]
I won't be able to fix this within 60 minutes. Sorry. The tests failing are using Gurobi and we don't have a license for it yet. 
However, I do have a good idea of what the problem could be. I am creating a C++ version of this case based off Russ' PR #2164. Cleaning up @2164 was in my todo list before asked to prioritize height maps....
I'll see if I can reproduce a similar failure mode with a C++ test instead.

The possible failure might be that collision groups got somehow mixed up with Matlab's groups.

**Comment by mwoehlke-kitware** [comment]
I should go ahead and merge this revert, then?

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I should go ahead and merge this revert, then?
</details>


---

Review status: 0 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2506#-:-KJMdwDohOFT1NMvtcHz:1417088721)*

**Comment by mwoehlke-kitware** [comment]
Oooooorr.... @david-german-tri could merge it :smile:. That works too...

Thanks!

**Comment by david-german-tri** [comment]
Sorry for not posting first.  :-)

Happy Friday!

**Pull request merged**
