### PR TITLE
puts all mex calls to the c++ RigidBodyManipulator class through a single mex function interface

### PR DESCRIPTION
**Pull request by RussTedrake**
the goal is to:
  - reduce compile time (it was getting ridiculous)
  - reduce the barrier to exposing more interfaces.  we shouldn't feel any pain at exposing any (or all!) of the public methods
  - reduce the memory footprint - now we have only one mex file in memory instead of N, where N had gotten large

i'd eventually like to see a very clean parallel between the matlab and c++ RBM classes.  this is just a baby step.

### CODE REVIEW

**Comment by RussTedrake** [comment]
btw - opinions are welcome!

**Comment by psiorx** [comment]
One mex to rule them all? Looking this over.

**Comment by psiorx** [comment]
I think readability took a hit here, but it does compile faster.  I don't think contactConstraintsmex will merge with this without modification.

**Comment by RussTedrake** [comment]
i do worry about readability.  but i would argue that the pollution of *mex.cpp files in the class directory (with lots of copy/paste all over the place, as evidenced by a ridiculous number of comments specifying the wrong mex file in the text) was very messy before.  and the calls to the mex interface almost always happen directly inside the matlab method of the same name -- so having a slightly less (and only slightly less) readable one line call to the mex function doesn't seem bad.

The bad thing is the big file for the single mex interface.  but we have that for the main RBM.cpp, too.  
(also bad is the jumble of different interfaces, including some that appear to do identical things, like getCMM and centroidalMomentumMatrix, but we'll clean that all up eventually).

**Comment by RussTedrake** [comment]
john - might you be able to look to see if the memory footprint of matlab is any smaller (e.g. when running and atlas example before and after) with the new version?  do you notice any runtime speed differences?

**Comment by psiorx** [comment]
Yep, putting together a comparison now.

**Comment by psiorx** [comment]
@RussTedrake ,
runAtlasBalancing fails for me with these changes:

Attempt to reference field of non-structure array.

Error in QPController (line 199)
      obj.mex_ptr = SharedDataHandle(QPControllermex(0,obj,obj.robot.getMexModelPtr.ptr,getB(obj.robot),r.umin,r.umax,terrain_map_ptr));


Error in runAtlasBalancing (line 84)
qp = QPController(r,{},ctrl_data,options);

**Comment by RussTedrake** [comment]
taking a look.

**Comment by psiorx** [comment]
This one looks scary.  runAtlasRunning segfaults and brings down MATLAB with this inviting message:

MATLAB: malloc.c:3223: __libc_calloc: Assertion `!mem || ((((mchunkptr)((char*)(mem) - 2*(sizeof(size_t)))))->size & 0x2) || av == (((((mchunkptr)((char*)(mem) - 2*(sizeof(size_t)))))->size & 0x4) ? ((heap_info *) ((unsigned long) (((mchunkptr)((char*)(mem) - 2*(sizeof(size_t))))) & ~((2 * (4 * 1024 * 1024 * sizeof(long))) - 1)))->ar_ptr : &main_arena)' failed.

**Comment by RussTedrake** [comment]
that's actually fantastic.  i can reproduce this, too (btw - you might get a nicer assertion message if you build w/ (make clean; make BUILD_TYPE=Debug).  i've found a few similar eigen memory issues that have been nascent in the code, this might be one more, just because we're moving memory around slightly differently now.  it could be something i screwed up, but I didn't touch the QP controller.

**Comment by psiorx** [comment]
Oh, nice.  We might have discovered a sleeper.  Eigen memory issues are a lot less terrifying when you know they're there.

**Comment by RussTedrake** [comment]
found it.  :)

**Comment by psiorx** [comment]
I'm still seeing the issues on GNU/Linux after pulling your fix. (Both with runAtlasBalancing error and the runAtlasRunning segfault)

**Comment by psiorx** [comment]
I think the QPController code is getting mad because all mex_model_ptrs are currently broken.  There's a bug on line 2113 of RigidBodyManipulator.m that checks for the existence of constructModelmex (which doesn't exist anymore).

We should either remove that or point it to rigidBodyManipulatormex now.

**Comment by RussTedrake** [comment]
good catch.  (I still had an old constructModelmex on my harddrive). confirmed that it was broken and that your change fixed it.  will push it now.

**Comment by psiorx** [comment]
Performance comparison (All results are averages over 10 samples):

Before (RobotLocomotion:master)
Build time: 3 mins 35 seconds
runAtlasBalancing: 16.69 seconds

After (RussTedrake:mex_entry)
Build time: 3 mins 12 seconds
runAtlasBalancing: 18.50 seconds

The build is about 23 seconds faster, on average, but runAtlasBalancing is ~10% slower.  Is the entire mex codebase getting loaded into memory every time any mex call happens?  It's hard to explain those numbers as the overhead of a switch statement.

**Comment by RussTedrake** [comment]
Well crap.  That's no good.  :-/

Could it be the lookup of the constant variables for the commands?  (e.g. obj.FORWARD_KIN_COMMAND)?

**Comment by RussTedrake** [comment]
i ran them on my laptop, too.  master is ~ 13.5s to mex_entry at ~13.65s (though there is definitely a large variance in the timings).  hrmph.  maybe we'd better revert.

**Comment by psiorx** [comment]
I think we need more testing.  Maybe runAtlasBalancing isn't a representative sample.  I'll get some more comprehensive results with the profiler on a desktop tomorrow.

**Comment by psiorx** [comment]
Just tested this on an Alienware desktop (average of 10 samples):

mex_entry:
13.0738 runAtlasBalancing
31.9024 runAtlasRunning

master:
12.2753  runAtlasBalancing
31.7866  runAtlasRunning

Difference is less significant in runAtlasRunning (probably because mex calls aren't occurring during playback of the trajectory, which takes a while).

runAtlasBalancing is still ~6.5% slower than master

**Comment by RussTedrake** [comment]
how about runAtlasWalking?  (it hits more methods than either of those two)

**Comment by psiorx** [comment]
mex_entry:
112.8081 runAtlasWalking.m

master:
106.6510 runAtlasWalking.m

**Comment by RussTedrake** [comment]
seems like this one was a bust (except that it exposed the memory ghost in the QP controller)..  will close this.  I've cherry-picked the QP controller fix into a new pull request.

**Pull request closed without merging**
