### PR TITLE
Widget system

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13882)

### CODE REVIEW

**Comment by RussTedrake** [comment]
The other PR landed and I've rebased, so this should be all set.

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/systems/jupyter_widgets.py, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13882#-MEwO5loDOXX6lhG91L0:-MF0cDY4-E5alc2PJ6b9:b-ouux4k) ([raw file](https://github.com/robotlocomotion/drake/blob/4e9bb4e946603185139fec1e038cd1087d6fcabd/bindings/pydrake/systems/jupyter_widgets.py#L173)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Why the double backticks?
</blockquote></details>

see eric's comment immediately below?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/jupyter_widgets.py, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13882#-MExGnDa3TesT3_ZzGny:-MF0m5RE6sRfhCnyBqWY:b-gjlihv) ([raw file](https://github.com/robotlocomotion/drake/blob/4e9bb4e946603185139fec1e038cd1087d6fcabd/bindings/pydrake/systems/jupyter_widgets.py#L184)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This system is implemented exactly the same way that the others are.  The only difference is that I've given the update period as a constructor argument, which feels more important here since unlike the slider systems, I don't know if they want a button that can be updated once every 5 seconds, or a slider that it intended for smooth interaction.
</blockquote></details>

OK Yup, sorry, missed that!

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/jupyter_widgets_examples.ipynb, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13882#-MExHBLM43PbHuoaQcZW:-MF0mQFrBDkW6fTBBD9z:b5zgnfg) ([raw file](https://github.com/robotlocomotion/drake/blob/4e9bb4e946603185139fec1e038cd1087d6fcabd/bindings/pydrake/systems/jupyter_widgets_examples.ipynb#L136)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Eric, let me try one more time to explain myself.

First: there are multiple types of events in drake, they are distinguished by what amount of writable access they need to the Context.  If I was writing to discrete state, I would use discrete update.  If I was writing something generic, i would use unrestricted update.  I am not writing anything to the cache here, so I am using publish.

Second: as you and i have discussed, you want me to use discrete state for this, and I have so far just used output ports.  Using discrete state would have the advantage that it is leaving a record of the gui state in the context.  I agree that could be useful if/when we ever serialize context.  But right now, it would only add delay and unuseful complexity (e.g. my example would have to call discrete updates, then then eval the output port).  Neither use gets around the fundamental problem that the gui element themselves have state.  It feels to you, i think, like using discrete state would be better, but i think that's only because we don't (yet?) implement caching on discrete updates.  if we did, I would have to disable caching on the discrete update instead of disabling it on the output port.  The fact is values are being changed by a mechanism that it outside the understanding of the systems framework.  I prefer to do it in the output port for now.


</blockquote></details>

OK Sounds good, and thank you for the explanation!

**Pull request merged**
