### PR TITLE
[SAP] Newton iteration tests

### PR DESCRIPTION
**Pull request by amcastro-tri**
Add a number of tests to verify the Newton iterations are doing the right thing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940#-:-N-d5Xjk60vMBS6Hq914:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by amcastro-tri — COMMENTED** [review]
This became higher priority given one of my next PRs depends on it.
I'm reassigning to alleviate Joe's workload.

-@joemasterjohn 
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940#-:-N0gmgCU72VKsL2_0Ml_:b-42o6rw)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: nice tests!
+@sherm1 for platform review per rotation please.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940#-:-N0gzrGg3VG55GM_8tLo:bfdqyg6)* status: 16 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 650 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0grL091vJnoqB4WJDA:-N0grL091vJnoqB4WJDB:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L650)):*
> ```cpp
>   // limit vu and regularization R.
>   LimitConstraint(int clique, const VectorX<T>& vl, const VectorX<T>& vu,
>                   const VectorX<T> R)
> ```

nit



_Suggestion:_
```cpp
 VectorX<T> R)
```
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 657 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gwicC-_xF4yg9h1M-:-N0gwicC-_xF4yg9h1M0:bwlouk8) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L657)):*
> ```cpp
>         R_(std::move(R)),
>         vhat_(ConcatenateVectors(vl, -vu)) {
>     DRAKE_DEMAND(vl.size() == vu.size());
> ```

Do we also want to verify that vu > vl, entrywise?
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 666 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gsGL97LNoGlboympb:-N0gsGL97LNoGlboympc:b79cw0a) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L666)):*
> ```cpp
>   }
> 
>   // For this constraint the projection is the identity operation.
> ```

The projection is a rectifier, not an identity, right?
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 671 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0grxk3-iX3zIk3HHpd:-N0grxk3-iX3zIk3HHpe:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L671)):*
> ```cpp
>                EigenPtr<VectorX<double>> gamma,
>                MatrixX<double>* dPdy) const final {
>     // For this constrain the number of equations equals the number of
> ```

nit



_Suggestion:_
```cpp
// For this constraint the number of equations equals the number of
```
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 704 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gu2Pb6UfUYthRq_8u:-N0gu2Pb6UfUYthRq_8v:b7uhigt) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L704)):*
> ```cpp
>   VectorX<T> CalcConstraintFunction(const VectorX<T>& ql, const VectorX<T>& qu,
>                                     const VectorX<T>& q) const {
>     DRAKE_DEMAND(ql.size() == q.size());
> ```

Is it true that `q.size()` always needs to be `vhat_.size()`?
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 711 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gtpmgBqKTGzl8GNO4:-N0gtpmgBqKTGzl8GNO5:b-sk4di1) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L711)):*
> ```cpp
>   }
> 
>   MatrixX<T> CalcConstraintJacobian(int nq) const {
> ```

Is it true that `nq` always needs to be `vhat_.size()`? If that's the case, we don't need the parameter `nq`.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 723 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gvWR857hQJosjJJAB:-N0gvWR857hQJosjJJAC:bh2htkl) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L723)):*
> ```cpp
> 
> // This fixture is used to test the number of iterations performed by SAP's
> // Newton solver. We setup a contact problem for which the solution is v = v*,
> ```

nit setup -> set up.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 759 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gxQ0fCL9g8FEMulmL:-N0gxQ0fCL9g8FEMulmM:b-pfapdf) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L759)):*
> ```cpp
>     VectorXd v_star =
>         VectorXd::LinSpaced(num_velocities, 1., 1. * num_velocities);
>     v_star.segment<3>(2) = 0.5 * (vl_ + vu_);
> ```

nit, the number 2 here needs a comment.

Ideally, the numbers 2, 3, 6 in this function should have meaningful names.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 766 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gx88R3x_oKZY9EFEe:-N0gx88R3x_oKZY9EFEf:b-4retpn) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L766)):*
> ```cpp
>     sap_problem_->Reset(std::move(A), std::move(v_star));
> 
>     const VectorXd R = VectorXd::Constant(6, 1.0e-3);
> ```

nit No const to enable move.



_Suggestion:_
```cpp
VectorXd R = VectorXd::Constant(6, 1.0e-3);
```
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gxhPd3K2G2WzbxGMO:-N0gxhPd3K2G2WzbxGMP:b-zgkcqj) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L793)):*
> ```cpp
>   EXPECT_TRUE(stats.optimality_criterion_reached);
> 
>   // Since the initial guess is the solution to this problem, we exepct the
> ```

nit exepct->expect
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 809 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyAYiEClU7OBVwEe9:-N0gyAYiEClU7OBVwEeA:b-33z3c5) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L809)):*
> ```cpp
>   SapSolver<double> sap;
>   SapSolverParameters params;
>   // We setup the line search parameters so that the backtracking line-search
> ```

nit setup->set up
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 810 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyRrM3GfEoAEisdeE:-N0gyRrM3GfEoAEisdeF:bvhidhh) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L810)):*
> ```cpp
>   SapSolverParameters params;
>   // We setup the line search parameters so that the backtracking line-search
>   // tries alpha = ls_alpha_max = 1.0 / 0.8 = 1.25 and alpha = ls_alpha_max *
> ```

This sentence is confusing. You are saying alpha = 1.25 and alpha = 1.0 at the same time.

Consider 

... so that the backtracking line-search tries alpha = 1.0. Since alpha = ls_alpha_max * ls_rho, we set ls_lpha_max = 1.0/ls_rho.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 811 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyHnq34JNyifyPZWG:-N0gyHnq34JNyifyPZWH:b-igzupu) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L811)):*
> ```cpp
>   // We setup the line search parameters so that the backtracking line-search
>   // tries alpha = ls_alpha_max = 1.0 / 0.8 = 1.25 and alpha = ls_alpha_max *
>   // ls_rho = 1.0. Since in this case the guess is withing the constraint
> ```

nit withing->with in
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 812 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyKLBARPZxgcXCCHv:-N0gyKLBARPZxgcXCCHw:b-iljyf4) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L812)):*
> ```cpp
>   // tries alpha = ls_alpha_max = 1.0 / 0.8 = 1.25 and alpha = ls_alpha_max *
>   // ls_rho = 1.0. Since in this case the guess is withing the constraint
>   // limits, where th cost is exactly quadratic, one Newton iteration with alpha
> ```

nit th->the
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 827 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyxukBiIxqZEMloxi:-N0gyxukBiIxqZEMloxj:bb7lc4s) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L827)):*
> ```cpp
> 
>   // Since we provide the guess to be within the limits, and we know the
>   // solution is v = v*, then we expect the solver achieve convergence in a
> ```

nit 



_Suggestion:_
```cpp
  // solution is v = v*, we expect the solver achieves convergence in a
```
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 884 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gzbez-kIRuJ_UdgMU:-N0gzbez-kIRuJ_UdgMV:b-w04w8n) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L884)):*
> ```cpp
>   // Even though the initial guess is outside the constraint limits, once a SAP
>   // iteration reaches a solution within the constraint's bounds, it will
>   // converge in a single iteration within machine epsilon.
> ```

nit, this sentence needs a bit rewording? We are not testing single iteration convergence once the constraints are satisfied here.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few minor comments and unresolveds from feature review.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940#-:-N0hJZ_L5sUF-XzfFuK3:bp5ckgy)* status: 19 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 703 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hFP5yBJGAOByEjn31:-N0hFP5yBJGAOByEjn32:b-7cd8dh) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L703)):*
> ```cpp
> 
>   VectorX<T> CalcConstraintFunction(const VectorX<T>& ql, const VectorX<T>& qu,
>                                     const VectorX<T>& q) const {
> ```

BTW wouldn't it be clearer to call these parameters vl, vu, and v for this constraint?
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 704 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gu2Pb6UfUYthRq_8u:-N0hFkZqCagliDQNwd0A:bndsup2) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L704)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is it true that `q.size()` always needs to be `vhat_.size()`?
</blockquote></details>

BTW looks like vhat_ is twice as big as q
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 727 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hG5XBEz20ZGuTgKqM:-N0hG5XBEz20ZGuTgKqN:b-63lz50) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L727)):*
> ```cpp
> // LimitConstraint on the first clique. We can test how the Newton iterations
> // perform by changing the initial guess. For instance, when the initial guess
> // is whithin the contraint's bounds, the cost is quadratic and we expect SAP to
> ```

typo: whithin -> within
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 811 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyHnq34JNyifyPZWG:-N0hIJtc-ODptvnTrcN6:bsnw1rg) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L811)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit withing->with in
</blockquote></details>

nit actually "within" (no space)
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 864 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hIzes1Gwx-caSmxJS:-N0hIzes1Gwx-caSmxJT:bu2l6gv) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L864)):*
> ```cpp
>   // Newton iterations.
>   VectorXd v_guess = v_star_;
>   v_guess.segment<3>(2) = Vector3d(0.8 * vl_(0) /* below lower limit */,
> ```

nit: isn't `0.8*vl` actually above the lower limit since those are negative? 
E.g. `0.8*-3=-2.4`.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: 19 unresolved discussions (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 704 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gu2Pb6UfUYthRq_8u:-N0hPPDa34HqHG98854-:b-pa7e8b) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L704)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW looks like vhat_ is twice as big as q
</blockquote></details>

Ah right... In case it't not clear, my point is that the check should be against `vhat_.size()` if that's the implicit assumption.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: 6 unresolved discussions (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 657 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gwicC-_xF4yg9h1M-:-N0kjaU08vqxGrtGwEfy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L657)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do we also want to verify that vu > vl, entrywise?
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 666 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gsGL97LNoGlboympb:-N0kjxdaC5lScgfOsiHn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L666)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The projection is a rectifier, not an identity, right?
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 704 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gu2Pb6UfUYthRq_8u:-N0kkZtg9HTanq46qXKq:b-uuk0fv) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L704)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ah right... In case it't not clear, my point is that the check should be against `vhat_.size()` if that's the implicit assumption.
</blockquote></details>

I don't understand the request. `vhat_` does not even show up in this function.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 711 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gtpmgBqKTGzl8GNO4:-N0kkwq_0a3n66T3ibF2:buc10e8) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L711)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is it true that `nq` always needs to be `vhat_.size()`? If that's the case, we don't need the parameter `nq`.
</blockquote></details>

These are helpers to help make `vhat_` at construction, therefore `vhat_` might not be initialized yet.
I made these method `static` to make this clear.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 810 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyRrM3GfEoAEisdeE:-N0ko9cbEsVOnRMo-z0D:bhyl92j) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L810)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This sentence is confusing. You are saying alpha = 1.25 and alpha = 1.0 at the same time.

Consider 

... so that the backtracking line-search tries alpha = 1.0. Since alpha = ls_alpha_max * ls_rho, we set ls_lpha_max = 1.0/ls_rho.
</blockquote></details>

I found them both equally confusing. Paraphrased. 
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 864 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hIzes1Gwx-caSmxJS:-N0kollz3DpJQ-zFJB5l:b-oz8tyz) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L864)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: isn't `0.8*vl` actually above the lower limit since those are negative? 
E.g. `0.8*-3=-2.4`.
</blockquote></details>

Good call!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: 2 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 704 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gu2Pb6UfUYthRq_8u:-N0kybE-EWF7Kri4lOfw:b-m36bnl) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L704)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't understand the request. `vhat_` does not even show up in this function.
</blockquote></details>

In the previous revision, calculating the constraint function with v, vl, vu that have size incompatible with the member vhat_ doesn't make sense. Now that this function is static, it's more clear that it's meant to be a utility function, not tied to the specific object.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 810 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0gyRrM3GfEoAEisdeE:-N0kzZlQ7H3HunhP0wBR:b-h1hkmp) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L810)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I found them both equally confusing. Paraphrased. 
</blockquote></details>

Very nice, thanks.
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 864 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hIzes1Gwx-caSmxJS:-N0kztKv3MqfHheJUuhq:br2xafq) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L864)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Good call!
</blockquote></details>

Do you want 1.2 instead of -1.2?
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 763 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0l-5dWD13ZkS7pTDVB:-N0l-5dWD13ZkS7pTDVC:b3xdofb) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c170b5e57ec1bef9e1ea4585cc902f317e2d48/multibody/contact_solvers/sap/test/sap_solver_test.cc#L763)):*
> ```cpp
>         VectorXd::LinSpaced(num_velocities, 1., 1. * num_velocities);
>     // The limit constraint applies to the second clique (clique=1) only. This
>     // clique has clique1_nv = 3 degrees of freedom staring at entry 2 in the
> ```

nit s/staring/starting

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: 2 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 864 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hIzes1Gwx-caSmxJS:-N0l0Jh66gjSD7yn_oJ9:bjha5vz) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L864)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do you want 1.2 instead of -1.2?
</blockquote></details>

Better stick to calculus, Alejandro -- arithmetic is clearly too hard for you! :)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 864 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16940#-N0hIzes1Gwx-caSmxJS:-N0llcqw3Fv9PFczYLnN:bhc9ic5) ([raw file](https://github.com/robotlocomotion/drake/blob/d60e22221c3b33a381937c9db870f5b2a23b6e63/multibody/contact_solvers/sap/test/sap_solver_test.cc#L864)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Better stick to calculus, Alejandro -- arithmetic is clearly too hard for you! :)
</blockquote></details>

sometimes I wonder how I still have this job...

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16940)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
