### PR TITLE
Fixing UBSan for Bazel

### PR DESCRIPTION
**Pull request by m-chaturvedi**
https://groups.google.com/forum/#!topic/bazel-discuss/15h4GPixeGI

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6830)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
We didn't use `-fno-sanitize-recover=undefined` because it heed the suppressions and exits even for errors which should be suppressed.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6830#-:-KrWyK0NQvhCWBt3hBVC:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@jwnimmer-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6830#-:-KrX2H3mKbhtsA8Kokqm:bnfp4nl)*

**Pull request merged**
