### PR TITLE
Switch to regular std::map for eigen types

### PR DESCRIPTION
**Pull request by psiorx**
Fixes aligned allocator errors in gcc 4.8.

### CODE REVIEW

**Comment by RussTedrake** [comment]
for the discussion, here is an email from @psiorx 

Hi Russ,

Neither myself, Hongkai, nor Chris can currently build Drake master after the C++ runLCM changes.  This happens both upon pulling and on a fresh clone.  The compiler thinks it's a problem with Eigen::aligned_allocators.  I'm using gcc-4.8 on Ubuntu 14.04.

Here's a dump of the error that we're all getting:

/usr/include/c++/4.8/bits/hashtable.h:727:6: error: no matching function for call to ‘Eigen::aligned_allocator<std::__detail::_Hash_node<std::pair<const RigidBody* const, Eigen::Matrix<double, 6, 1> >, false> >::construct(std::_Hashtable<const RigidBody*, std::pair<const RigidBody* const, Eigen::Matrix<double, 6, 1> >, Eigen::aligned_allocator<std::pair<const RigidBody* const, Eigen::Matrix<double, 6, 1> > >, std::__detail::_Select1st, std::equal_to<const RigidBody*>, std::hash<const RigidBody*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::__node_type*&, const std::piecewise_construct_t&, std::tuple<const RigidBody*&&>, std::tuple<>)’
      _M_node_allocator().construct(__n, std::forward<_Args>(__args)...);
      ^
/usr/include/c++/4.8/bits/hashtable.h:727:6: note: candidate is:
In file included from /home/drc/drake-distro2/build/include/eigen3/Eigen/Core:256:0,
                 from /home/drc/drake-distro2/drake/systems/System.h:5,
                 from /home/drc/drake-distro2/drake/systems/LCMSystem.h:10,
                 from /home/drc/drake-distro2/drake/systems/plants/urdfLCMNode.cpp:2:
/home/drc/drake-distro2/build/include/eigen3/Eigen/src/Core/util/Memory.h:729:10: note: void Eigen::aligned_allocator<T>::construct(Eigen::aligned_allocator<T>::pointer, const T&) [with T = std::__detail::_Hash_node<std::pair<const RigidBody* const, Eigen::Matrix<double, 6, 1> >, false>; Eigen::aligned_allocator<T>::pointer = std::__detail::_Hash_node<std::pair<const RigidBody* const, Eigen::Matrix<double, 6, 1> >, false>*]
     void construct( pointer p, const T& value )
          ^
/home/drc/drake-distro2/build/include/eigen3/Eigen/src/Core/util/Memory.h:729:10: note:   candidate expects 2 arguments, 4 provided
make[6]: *** [systems/plants/CMakeFiles/urdfLCMNode.dir/urdfLCMNode.cpp.o] Error 1

It seems to happen in three different files: urdfLCMNode.cpp and Pendulum/test/urdfDynamicsTest.cpp and Quadrotor/test/urdfDynamicsTest.cpp

I've narrowed it down to the call to dynamics on RigidBodySystem and in particular it's caused by
these two lines:

          if (f_ext.find(body)==f_ext.end()) f_ext[body] = f_ext_i;
          else f_ext[body] = f_ext[body]+f_ext_i;

f_ext[body] = f_ext_i; // <-- this line causes the compiler error, assigning a vector to the map.

In fact, these 3 lines in a standalone executable will cause the problem for me:

  eigen_aligned_unordered_map<int, Matrix<double, 6, 1> > map;
  Matrix<double, 6, 1> vec;
  map[0] = vec;

I've found that switching to a regular std::map instead of a std::unordered_map and adding the appropriate template definition fixes the problem:

template <typename Key, typename T>
using eigen_aligned_map = std::map<Key, T, std::less<Key>, Eigen::aligned_allocator<std::pair<const Key, T> > >;

I'll put in a PR containing the fixes.

~JC

**Comment by RussTedrake** [comment]
@psiorx -- i feel like switching to std::map is a bad hack (we don't understand why it works for std::map and not std::unordered_map).  
I found this: http://permalink.gmane.org/gmane.comp.lib.eigen/5225 , which suggests that things might get better if we upgrade eigen to 3.2.7 .  i can't reproduce the compile error locally.  can you guys try building master with the newer eigen and see if that fixes things?

**Comment by psiorx** [comment]
> I found this: http://permalink.gmane.org/gmane.comp.lib.eigen/5225 ,

That seems like the same error and the poster mentioned that it didn't happen in gcc 4.7.  This is what the build server is using (drake006).

>  switching to std::map is a bad hack
I agree.  I'm not sure what the root cause of this is.  The template definition for the `std::unordered_map` looked correct to me.

>  can you guys try building master with the newer eigen and see if that fixes things

Trying it now.

**Comment by RussTedrake** [comment]
Thanks.  Let me know.

**Comment by psiorx** [comment]
> Thanks.  Let me know.

Looks like it's still happening in 3.2.7.

**Comment by RussTedrake** [comment]
The error message must be different, at least?  can you confirm that the eigen allocator construct method no longer exists?

**Comment by psiorx** [comment]
The error message is the same.  The allocator construct method is still there in 3.2.7.

https://bitbucket.org/eigen/eigen/src/79f0cba2957c13779953bca089fc668043121db8/Eigen/src/Core/util/Memory.h?fileviewer=file-view-default

This post is exactly the same thing we're hitting (and it was reported in 3.2.9)

http://listengine.tuxfamily.org/lists.tuxfamily.org/eigen/2015/05/msg00005.html

**Comment by RussTedrake** [comment]
again, i really don't like switching to std::map for this (especially switching in a way that the typedef is still called unordered_map).  What about replacing the one offending line with a manual call to insert(make_pair<>), possibly calling out the eigen aligned allocator explicitly?

**Comment by tkoolen** [comment]
Was the original error on a 32 bit machine?

**Comment by RussTedrake** [comment]
No.  gcc 4.8 on linux



On January 9, 2016 at 9:14:27 AM, Twan Koolen (notifications@github.com) wrote:

Was the original error on a 32 bit machine?

**Comment by psiorx** [comment]
Calling insert directly allows it to compile with `unordered_map`.  It seems the `operator[]` is really what was making gcc 4.8 freak out.

**Comment by RussTedrake** [comment]
i think it was only the if that should be changed. (that's where you are getting the allocation).  The else case can, and probably should, still use the operator[].  You're needlessly doing allocation here.

**Comment by psiorx** [comment]
>  The else case can, and probably should, still use the operator[].

Using operator[] at all fails to compile even with simple usage (e.g):
```C++
f_ext[body] = f_ext_i;
auto f = f_ext[body]; 
```
Both of those lines cause compiler errors.

Is there another way to avoid the allocations here?

**Comment by RussTedrake** [comment]
How about with .at()

**Comment by psiorx** [comment]
This should be good to go.

**Comment by RussTedrake** [comment]
Just rebooted drake003 to make sure it compiles there.  then will pull.



On January 10, 2016 at 12:59:34 PM, John Carter (notifications@github.com) wrote:

This should be good to go.

**Comment by psiorx** [comment]
For the record, the `insert` call in the else block here would not have performed an additional allocation at the map level, it simply would've returned false since the key already exists.  This silent failure would've created a hard to find bug.  What would've worked is `std::unordered_map::emplace` but it has the same issues as `operator[]` in this context.  In C++17, a new function called `insert_or_assign` will be added to the standard.

**Comment by psiorx** [comment]
> Just rebooted drake003 to make sure it compiles there.  then will pull.

Seems like the tinyxml symbols are not linking up between drakeRBM and drakeRBSystem on windows.  Maybe we need to add DLL_EXPORTS throughout the tinyxml code?

**Comment by tkoolen** [comment]
I think you're right @psiorx. I'm going to try to fix it.

**Comment by tkoolen** [comment]
I couldn't reproduce the error on my win64 install, but I tried to fix it by simply upgrading to tinyxml2. See https://github.com/RobotLocomotion/drake/pull/1591. tinyxml2 does the dllexport thing already, so this was much easier than adding dllexports everywhere myself.

**Comment by RussTedrake** [comment]
i've actually removed those lines, because we've changed the interface for rigid body forces to now compute the torques directly (instead of using f_ext).  that's coming in my next PR.  sigh.  sorry.

**Pull request closed without merging**
