### PR TITLE
[sensors] Add parameters to RgbdSensor

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Also, deprecate a variety of old accessor methods.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
For motivation, see #21872.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7GJ-WkDOHBKVEeRExA:b-2ju0ba)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri or delegate for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7GJFYK-FTGkyhAMkr9:baf5qp0)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
Looks like Anzu is not using any of the deprecated methods: https://robotics-enabling-jenkins.awsinternal.tri.global/job/Integrations/job/Anzu-master-Drake-PR/272/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7GO2vRBxzq7ANWMwIV:bo2lvgo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`systems/sensors/rgbd_sensor.h` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7UOPxZC_oGhFO8QqBX:-O7_MsZLCBTiIR9fGJfY:b-69o75b) ([raw file](https://github.com/RobotLocomotion/drake/blob/15f4ba15c1d91f72cb8c81abea8360379629ed56/systems/sensors/rgbd_sensor.h#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Can you talk me through the reasoning for using CamelCase here?

(1) Consistency with prior art?  (LMK which file?)

(2) GSG rules for snake?

(3) Consistency with its `Set...` twin?
</blockquote></details>

Consistency with multibody/tree/joint.h spellings. See the damping vector APIs.

**Review by jwnimmer-tri — COMMENTED** [review]
Okay, checkpoint on careful checks of the API design.  I'll continue reviewing the implementation & test changes momentarily.

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7_bdps9r8uW26XCAxI:bw6u98l)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_YrkY0WlWuGKK_bKo:-O7_YrkY0WlWuGKK_bKp:b-cnbd72) (no related file):*
> Looks like Anzu is not using any of the deprecated methods

That job only fails-fast on C++ deprecations.  I believe there is Anzu Python code still using some of these methods.

To test for certain, open an Anzu PR by hand (pinning to this Drake PR) and change `def _should_check_deprecations():` to hard-code True.

___
___
*[`systems/sensors/rgbd_sensor.h` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7UOPxZC_oGhFO8QqBX:-O7_WMp99hbqGSbm1j59:b-80xk54) ([raw file](https://github.com/RobotLocomotion/drake/blob/15f4ba15c1d91f72cb8c81abea8360379629ed56/systems/sensors/rgbd_sensor.h#L127)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Consistency with multibody/tree/joint.h spellings. See the damping vector APIs.
</blockquote></details>

Sold!
___
*[`systems/sensors/rgbd_sensor.h` line 164 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_ZSoi3vD3-xAVxh2d:-O7_ZSoi3vD3-xAVxh2e:b7bx6a) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/rgbd_sensor.h#L164)):*
> ```objc
>                math::RigidTransformd sensor_pose) const;
> 
>   /** Returns the default color camera's `X_BC`.  */
> ```

I am not so sure that we should keep around `X_BC` and `X_BD` getters anymore.

In this revision, we have them as halfway-sugar functions -- only available for defaults, not available for per-context.  These sugar functions provide monogram-encrypted access to a specific detail of the camera info parameters, which users can already access (albeit with longer words).

At minimum, here we would need clarify for users that these are just _sugar_ function (not foundational) and guide users how to use the (non-sugared) per-context functions to get the information in case they want to look inside a context. 

We could also duplicating the sugar with per-context "overloads" as well.

However, in the bigger picture -- we have zero uses of these sugar functions inside Drake, and of the two callers we have in Anzu one of them is actually defective by virtue of misapprehending the monogram-encrypted sugar as "C = Camera" instead of "C = Color".  So, we are not even at rule-of-three that would justify this sugar, and we have evidence that the encryption is actively harmful.

Therefore, my suggestion is to deprecate these two for removal (with a pointer to the unsugared spelling, and maybe some class-overview docs additions to help guide the user about the details), instead of renaming.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_YrkY0WlWuGKK_bKo:-O7_e5QG5NR8VDShVa3W:b-yqdrqa) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Looks like Anzu is not using any of the deprecated methods

That job only fails-fast on C++ deprecations.  I believe there is Anzu Python code still using some of these methods.

To test for certain, open an Anzu PR by hand (pinning to this Drake PR) and change `def _should_check_deprecations():` to hard-code True.
</blockquote></details>

s/fails-fast on/shows/

___

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM on C++.  Waiting for that to settle before cross-checking the Python.

> Reviewed 1 of 10 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7_uW7s8tzuEEiuLqr8:b-jxw8rz)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_uHw57sei61OAfkdy:-O7_uHw57sei61OAfkdz:b-2fpitp) (no related file):*
BTW Here an option to somewhat consolidate the parameter bookkeeping, possibly making it easier to add/remove/change the set of parameters over time.  (It's slightly more DRY.)

https://github.com/jwnimmer-tri/drake/commits/21937-uniparam/

___
___
*[`systems/sensors/rgbd_sensor.cc` line 82 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_ee6yCz8SUmvJJbJZ:-O7_ee6yCz8SUmvJJbJ_:b-w2blbr) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/rgbd_sensor.cc#L82)):*
> ```cpp
>       (std::numeric_limits<uint16_t>::max() - 1) / 1000.;
>   const double max_depth = defaults_.depth_camera.depth_range().max_depth();
>   if (max_depth > kMaxValidDepth16UInM) {
> ```

This diagnostic seems like it should be equally applicable to the setter function(s)?
___
*[`systems/sensors/rgbd_sensor.cc` line 98 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_eLgU-htCEnoWf0lZ:-O7_eLgU-htCEnoWf0l_:b-1c0i54) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/rgbd_sensor.cc#L98)):*
> ```cpp
> void RgbdSensor::set_default_color_render_camera(
>     ColorRenderCamera color_camera) {
>   defaults_.color_camera = color_camera;
> ```

nit If our choice is to pass-by-value, then we need `std::move` here.  (It would also be fine to pass-by-const-ref.)

Ditto on ~all of the setters.
___
*[`systems/sensors/rgbd_sensor.cc` line 243 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_jpSFEMDawUJBU3iu:-O7_jpSFEMDawUJBU3iv:b-bszie2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/rgbd_sensor.cc#L243)):*
> ```cpp
>   const QueryObject<double>& query_object = get_query_object(context);
>   query_object.RenderColorImage(GetColorRenderCamera(context),
>                                 GetParentFrameId(context), GetX_PB(context),
> ```

The `GetColorRenderCamera` and `GetX_PB` calls are on the `simulator.AdvanceTo` hot path here, but return copies instead of by-const-ref.  My first impression is that we should aim to avoid the copies, either by calling private functions that don't copy, or changing the public functions.  More than likely the copy is lost in the noise, but we might as well not regress things?

Ditto below.
___
*[`systems/sensors/test/rgbd_sensor_test.cc` line 219 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_pjtA0Ie9T1dm23eN:-O7_pjtA0Ie9T1dm23eO:b-k0trol) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/test/rgbd_sensor_test.cc#L219)):*
> ```cpp
>   // an input port. The optional `pre_render_callback` should do any work
>   // necessary to make the input port viable.
>   ::testing::AssertionResult ValidateConstruction(
> ```

This helper function now has a mix of return-assertion-result and assert-but-proceed, i.e., a hodge-podge of testing strategy.  That is somewhat confusing.

Also note that this helper function is called at most once from any given test case.

As such, I think it would be simple to change it to return `void` and only ever call `EXPECT_...`.  That would bring it back onto the beaten path of how we write tests these days.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`systems/sensors/rgbd_sensor.h` line 164 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_ZSoi3vD3-xAVxh2d:-O7edmMNDSGqTys6dbZS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/rgbd_sensor.h#L164)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not so sure that we should keep around `X_BC` and `X_BD` getters anymore.

In this revision, we have them as halfway-sugar functions -- only available for defaults, not available for per-context.  These sugar functions provide monogram-encrypted access to a specific detail of the camera info parameters, which users can already access (albeit with longer words).

At minimum, here we would need clarify for users that these are just _sugar_ function (not foundational) and guide users how to use the (non-sugared) per-context functions to get the information in case they want to look inside a context. 

We could also duplicating the sugar with per-context "overloads" as well.

However, in the bigger picture -- we have zero uses of these sugar functions inside Drake, and of the two callers we have in Anzu one of them is actually defective by virtue of misapprehending the monogram-encrypted sugar as "C = Camera" instead of "C = Color".  So, we are not even at rule-of-three that would justify this sugar, and we have evidence that the encryption is actively harmful.

Therefore, my suggestion is to deprecate these two for removal (with a pointer to the unsugared spelling, and maybe some class-overview docs additions to help guide the user about the details), instead of renaming.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7emBiR297yqusaK7YI:b-n37teh)* status: 8 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/sensors/test/rgbd_sensor_test.cc` line 219 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_pjtA0Ie9T1dm23eN:-O7ejZCy6dXgnt-sn_-H:bd1lgrg) ([raw file](https://github.com/RobotLocomotion/drake/blob/d263fa8de3f0dfcc18f0809356eb9c7c2f18345e/systems/sensors/test/rgbd_sensor_test.cc#L219)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This helper function now has a mix of return-assertion-result and assert-but-proceed, i.e., a hodge-podge of testing strategy.  That is somewhat confusing.

Also note that this helper function is called at most once from any given test case.

As such, I think it would be simple to change it to return `void` and only ever call `EXPECT_...`.  That would bring it back onto the beaten path of how we write tests these days.
</blockquote></details>

My comment was only about this one particular function.  The precondition of "only called from one place" which lets us do-away with the verbosity on this particular function does not hold for the other functions above that also got roped in.
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 97 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7ekWykDw4KMDBYtSq5:-O7ekWykDw4KMDBYtSq6:b9m1x48) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L97)):*
> ```cpp
>           py::arg("show_window") = false,
>           doc.RgbdSensor.ctor.doc_combined_intrinsics)
>       .def("default_color_render_camera",
> ```

nit In C++ the getters return references, but these bindings return copies.  I am okay with either choice, but the natural assumption would be references so if we want to copy on purpose we'll need a little comment nearby clarifying that.
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 102 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7ekNgXEi0fFjcYgTdP:-O7ekNgXEi0fFjcYgTdQ:b-nb2xom) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L102)):*
> ```cpp
>       .def("GetColorRenderCamera", &RgbdSensor::GetColorRenderCamera,
>           py::arg("context"), doc.RgbdSensor.GetColorRenderCamera.doc)
>       .def("set_default_color_render_camera",
> ```

nit Please re-order this listing of methods to match up with the header file order.
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 103 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7el-AA16kuwYez1V_u:-O7el-AA16kuwYez1V_v:b-25lhok) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L103)):*
> ```cpp
>           py::arg("context"), doc.RgbdSensor.GetColorRenderCamera.doc)
>       .def("set_default_color_render_camera",
>           &RgbdSensor::set_default_color_render_camera, py::arg("id"),
> ```

typo `id`
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 114 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7el9QZD9viZbbZDgHX:-O7el9Q_CujydO3HpYZg:b-25lhok) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L114)):*
> ```cpp
>           py::arg("context"), doc.RgbdSensor.GetDepthRenderCamera.doc)
>       .def("set_default_depth_render_camera",
>           &RgbdSensor::set_default_depth_render_camera, py::arg("id"),
> ```

typo `id`
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 123 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7elJvw591FnPHCZRHG:-O7elJvw591FnPHCZRHH:b-25lhok) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L123)):*
> ```cpp
>       .def("GetX_PB", &RgbdSensor::GetX_PB, py::arg("context"),
>           doc.RgbdSensor.GetX_PB.doc)
>       .def("set_default_X_PB", &RgbdSensor::set_default_X_PB, py::arg("id"),
> ```

typo `id`
___
*[`bindings/pydrake/systems/test/sensors_test.py` line 490 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7em7YF268kFYKt3Fqf:-O7em7YF268kFYKt3Fqg:b-bydila) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/test/sensors_test.py#L490)):*
> ```Python
>                 self.assertEqual(sensor.parent_frame_id(), parent_id)
>             check_ports(sensor)
>             # Check parameter API.
> ```

nit Always call using named kwargs in bindings unit tests, to lock in the kwarg names.  This goes for the entire block below.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 7 unresolved discussions, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 103 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7el-AA16kuwYez1V_u:-O7izYe102IFNUZUv8Ec:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo `id`
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 114 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7el9QZD9viZbbZDgHX:-O7izZ8l7gKiLztuiOxt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo `id`
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/sensors_py_rgbd.cc` line 123 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7elJvw591FnPHCZRHG:-O7izZex7cPP88jeSXo5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d083f9a280371a45681ca416599bec062058211/bindings/pydrake/systems/sensors_py_rgbd.cc#L123)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo `id`
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7j3dRvD8YYY5d9pNtJ:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_YrkY0WlWuGKK_bKo:-O7j97BiAB60NNlu9lpy:b-eoylsh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

s/fails-fast on/shows/
</blockquote></details>

found a few, checked locally with:
```
ANZU_LOCAL_DRAKE_PATH=$HOME/checkout/drake _ANZU_CHECK_PYDRAKE_DEPRECATIONS=1 bazel test //...
```
Will post an anzu patch shortly. 

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937)* status: LGTM missing from assignee sammy-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-O7_YrkY0WlWuGKK_bKo:-O7jCskh8D1OYXW8XbXj:b-bgrqia) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

found a few, checked locally with:
```
ANZU_LOCAL_DRAKE_PATH=$HOME/checkout/drake _ANZU_CHECK_PYDRAKE_DEPRECATIONS=1 bazel test //...
```
Will post an anzu patch shortly.
</blockquote></details>

See `anzu#14110`.

___

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 10 files at r1, 1 of 3 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21937#-:-O7kEY_mCu9aitvcKICW:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
