### PR TITLE
[multibody] Spatial inertial minimum bounding box and physical length methods

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)

### CODE REVIEW

**Comment by mitiguy** [comment]
Possible work for issue #20730.

**Review by mitiguy — COMMENTED** [review]
Feature review +@rpoyner-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-Nq4_rpAD5nuRRFIXzkS:b-zavrlv)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by mitiguy — COMMENTED** [review]
Feature review -@rpoyner-tri 
Feature review +@sherm1  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-NqjENLb2dSAg3baHof6:bar3d6)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri -@sherm1 I'll look at this later today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-NqmugRU5pYyiXIGMNNC:b279pg3)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 382 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-Nr7HCJr6RlJhRP7ilQl:-Nr7HCJr6RlJhRP7ilQm:b4cf9b) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2558cc68faf6f08d6bda576a2773d8d959759f0/multibody/tree/spatial_inertia.cc#L382)):*
> ```cpp
>       if (max_length > max_allowable_dimension) {
>         std::string error_message = fmt::format(
>             "Function {}() did not add rigid body {} because it is too large."
> ```

So, I copied the code in `r5` and did a quick parser integration experiment:

```
diff --git a/multibody/parsing/detail_common.cc b/multibody/parsing/detail_common.cc
index c2b3ad4767..cb7e3b8a6d 100644
--- a/multibody/parsing/detail_common.cc
+++ b/multibody/parsing/detail_common.cc
@@ -335,8 +335,10 @@ SpatialInertia<double> ParseSpatialInertia(
   const RotationalInertia<double> I_BBcm_B = I_BBcm_Bi.ReExpress(R_BBi);
 
   try {
-    return SpatialInertia<double>::MakeFromCentralInertia(
+    auto result = SpatialInertia<double>::MakeFromCentralInertia(
         mass, p_BoBcm_B, I_BBcm_B);
+    result.ThrowIfAssociatedBodyIsTooLarge(__func__, "");
+    return result;
   } catch (const std::exception& e) {
     diagnostic.Warning(
         fmt::format("While re-expressing as central inertia: {}", e.what()));
diff --git a/multibody/parsing/test/detail_urdf_parser_test.cc b/multibody/parsing/test/detail_urdf_parser_test.cc
index 1046d7e25c..f39d0026fb 100644
--- a/multibody/parsing/test/detail_urdf_parser_test.cc
+++ b/multibody/parsing/test/detail_urdf_parser_test.cc
@@ -1315,6 +1315,24 @@ TEST_F(UrdfParserTest, PointMass) {
   EXPECT_TRUE(body.default_rotational_inertia().get_products().isZero());
 }
 
+TEST_F(UrdfParserTest, MegaInertia) {
+  // Test that point masses don't get sent through the massless body branch.
+  EXPECT_NE(AddModelFromUrdfString(R"""(
+    <robot name='mega_inertia'>
+      <link name='mega_inertia'>
+        <inertial>
+          <mass value="1"/>
+          <inertia ixx="1e30" ixy="0" ixz="0" iyy="1e30" iyz="0" izz="1e30"/>
+        </inertial>
+      </link>
+    </robot>)""", ""), std::nullopt);
+  const auto& body = dynamic_cast<const RigidBody<double>&>(
+      plant_.GetBodyByName("mega_inertia"));
+  EXPECT_EQ(body.default_mass(), 1.);
+  EXPECT_TRUE(body.default_rotational_inertia().get_moments().isZero());
+  EXPECT_TRUE(body.default_rotational_inertia().get_products().isZero());
+}
+
 TEST_F(UrdfParserTest, BadInertiaFormats) {
   // Test various mis-formatted inputs.
   constexpr const char* base = R"""(
```

The test fails, because I didn't bother fixing up the results section, but that's a distraction. This little experiment helps me identify what I find awkward about this function:

* I'm not fond of the throw, but it turns out, the parser code already violated the style guide to accommodate previously existing throw-heavy code in *Inertia classes
* The function arguments and error message wording are awkward for parser integration:
   * I'm deep in parser internal implementation functions whose name no one knows or cares about
   * I don't have the body name at hand, and would have to modify several files to get it in all cases
   * I'm not "adding a rigid body" in any  way the the user will understand, exactly
   * The user context we need will be provided as a file name and line number

Perhaps more clear is another experiment I did to see the full warning message in the context of a (modified) full-scale robot file:

```
rico@torg:~/checkout/drake$ ROS_PACKAGE_PATH=$HOME/third/example-robot-data/ bazel run //multibody/parsing:parser_manual_test -- ~/tmp/foo_mega_inertia.urdf 
INFO: Invocation ID: 446d8419-7a5d-4c13-979b-efa4fd4eeffc
INFO: Analyzed target //multibody/parsing:parser_manual_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //multibody/parsing:parser_manual_test up-to-date:
  bazel-bin/multibody/parsing/parser_manual_test
INFO: Elapsed time: 0.377s, Critical Path: 0.01s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/multibody/parsing/parser_manual_test /home/rico/tmp/foo_mega_inertia.urdf
parsing /home/rico/tmp/foo_mega_inertia.urdf
/home/rico/tmp/foo_mega_inertia.urdf:184: warning: While re-expressing as central inertia: Function ParseSpatialInertia() did not add rigid body  because it is too large.
This body's spatial inertia has a minimum bounding box whose space-diagonal is 26985.984760500694 meters.
The maximum allowable space-diagonal is 355 meters.

 mass = 0.166
 Center of mass = [0.006435  0  -0.107388]
 Inertia about point P, I_BP =
[ 2.99797e+07             0  -2.64501e-05]
[           0   3.01402e+07             0]
[-2.64501e-05             0        324260]
 Inertia about center of mass, I_BBcm =
[ 2.99797e+07             0  -0.000141163]
[           0   3.01402e+07             0]
[-0.000141163             0        324260]
 Principal moments of inertia about Bcm (center of mass) =
[324260.0000000008  29979720  30140220]

Parsed 1 models.

```

What I see here is that the first line has the file name and line number, which will point me to the broken data, but the rest of the first line is all awkwardness, some from my code, some from yours.
* It claims the rigid body is too large, but in fact the only things I hacked in the input were spatial inertia values; the geometry size is fine. 
* The "while <blah>" clause is my awkwardness, trying to work around the awkwardness of catching thrown errors from elsewhere and feeding them to diagnostic policy
* The function name is kinda useless
* The body name is missing and the "did not add rigid body" text may or may not be confusing, in the context of model parsing, which uses the language of links

I like most of the rest of the lines (too-big quantity, limit, inertia data dump).

As an aside, note that the parser, when it finds unacceptable inertia tensors, will replace them with a "plausible guess", so that processing may continue. As a result, the check in AddRigidBody() will see the plausible substitute tensor, and not complain. Of course, direct API calls could still trigger that check.

So. (Whew.) What's the ask?

I'd like to have a way to use the math, and a suitable division of responsibility that allows us to give the right (probably different) messages in the various integration sites. I think I may work on things a bit more to come up with a concrete proposal, but feel free to do some work on it yourself.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 382 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-Nr7HCJr6RlJhRP7ilQl:-Nr7r97k9DujBbGfLlEJ:b113ujx) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2558cc68faf6f08d6bda576a2773d8d959759f0/multibody/tree/spatial_inertia.cc#L382)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, I copied the code in `r5` and did a quick parser integration experiment:

```
diff --git a/multibody/parsing/detail_common.cc b/multibody/parsing/detail_common.cc
index c2b3ad4767..cb7e3b8a6d 100644
--- a/multibody/parsing/detail_common.cc
+++ b/multibody/parsing/detail_common.cc
@@ -335,8 +335,10 @@ SpatialInertia<double> ParseSpatialInertia(
   const RotationalInertia<double> I_BBcm_B = I_BBcm_Bi.ReExpress(R_BBi);
 
   try {
-    return SpatialInertia<double>::MakeFromCentralInertia(
+    auto result = SpatialInertia<double>::MakeFromCentralInertia(
         mass, p_BoBcm_B, I_BBcm_B);
+    result.ThrowIfAssociatedBodyIsTooLarge(__func__, "");
+    return result;
   } catch (const std::exception& e) {
     diagnostic.Warning(
         fmt::format("While re-expressing as central inertia: {}", e.what()));
diff --git a/multibody/parsing/test/detail_urdf_parser_test.cc b/multibody/parsing/test/detail_urdf_parser_test.cc
index 1046d7e25c..f39d0026fb 100644
--- a/multibody/parsing/test/detail_urdf_parser_test.cc
+++ b/multibody/parsing/test/detail_urdf_parser_test.cc
@@ -1315,6 +1315,24 @@ TEST_F(UrdfParserTest, PointMass) {
   EXPECT_TRUE(body.default_rotational_inertia().get_products().isZero());
 }
 
+TEST_F(UrdfParserTest, MegaInertia) {
+  // Test that point masses don't get sent through the massless body branch.
+  EXPECT_NE(AddModelFromUrdfString(R"""(
+    <robot name='mega_inertia'>
+      <link name='mega_inertia'>
+        <inertial>
+          <mass value="1"/>
+          <inertia ixx="1e30" ixy="0" ixz="0" iyy="1e30" iyz="0" izz="1e30"/>
+        </inertial>
+      </link>
+    </robot>)""", ""), std::nullopt);
+  const auto& body = dynamic_cast<const RigidBody<double>&>(
+      plant_.GetBodyByName("mega_inertia"));
+  EXPECT_EQ(body.default_mass(), 1.);
+  EXPECT_TRUE(body.default_rotational_inertia().get_moments().isZero());
+  EXPECT_TRUE(body.default_rotational_inertia().get_products().isZero());
+}
+
 TEST_F(UrdfParserTest, BadInertiaFormats) {
   // Test various mis-formatted inputs.
   constexpr const char* base = R"""(
```

The test fails, because I didn't bother fixing up the results section, but that's a distraction. This little experiment helps me identify what I find awkward about this function:

* I'm not fond of the throw, but it turns out, the parser code already violated the style guide to accommodate previously existing throw-heavy code in *Inertia classes
* The function arguments and error message wording are awkward for parser integration:
   * I'm deep in parser internal implementation functions whose name no one knows or cares about
   * I don't have the body name at hand, and would have to modify several files to get it in all cases
   * I'm not "adding a rigid body" in any  way the the user will understand, exactly
   * The user context we need will be provided as a file name and line number

Perhaps more clear is another experiment I did to see the full warning message in the context of a (modified) full-scale robot file:

```
rico@torg:~/checkout/drake$ ROS_PACKAGE_PATH=$HOME/third/example-robot-data/ bazel run //multibody/parsing:parser_manual_test -- ~/tmp/foo_mega_inertia.urdf 
INFO: Invocation ID: 446d8419-7a5d-4c13-979b-efa4fd4eeffc
INFO: Analyzed target //multibody/parsing:parser_manual_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //multibody/parsing:parser_manual_test up-to-date:
  bazel-bin/multibody/parsing/parser_manual_test
INFO: Elapsed time: 0.377s, Critical Path: 0.01s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/multibody/parsing/parser_manual_test /home/rico/tmp/foo_mega_inertia.urdf
parsing /home/rico/tmp/foo_mega_inertia.urdf
/home/rico/tmp/foo_mega_inertia.urdf:184: warning: While re-expressing as central inertia: Function ParseSpatialInertia() did not add rigid body  because it is too large.
This body's spatial inertia has a minimum bounding box whose space-diagonal is 26985.984760500694 meters.
The maximum allowable space-diagonal is 355 meters.

 mass = 0.166
 Center of mass = [0.006435  0  -0.107388]
 Inertia about point P, I_BP =
[ 2.99797e+07             0  -2.64501e-05]
[           0   3.01402e+07             0]
[-2.64501e-05             0        324260]
 Inertia about center of mass, I_BBcm =
[ 2.99797e+07             0  -0.000141163]
[           0   3.01402e+07             0]
[-0.000141163             0        324260]
 Principal moments of inertia about Bcm (center of mass) =
[324260.0000000008  29979720  30140220]

Parsed 1 models.

```

What I see here is that the first line has the file name and line number, which will point me to the broken data, but the rest of the first line is all awkwardness, some from my code, some from yours.
* It claims the rigid body is too large, but in fact the only things I hacked in the input were spatial inertia values; the geometry size is fine. 
* The "while <blah>" clause is my awkwardness, trying to work around the awkwardness of catching thrown errors from elsewhere and feeding them to diagnostic policy
* The function name is kinda useless
* The body name is missing and the "did not add rigid body" text may or may not be confusing, in the context of model parsing, which uses the language of links

I like most of the rest of the lines (too-big quantity, limit, inertia data dump).

As an aside, note that the parser, when it finds unacceptable inertia tensors, will replace them with a "plausible guess", so that processing may continue. As a result, the check in AddRigidBody() will see the plausible substitute tensor, and not complain. Of course, direct API calls could still trigger that check.

So. (Whew.) What's the ask?

I'd like to have a way to use the math, and a suitable division of responsibility that allows us to give the right (probably different) messages in the various integration sites. I think I may work on things a bit more to come up with a concrete proposal, but feel free to do some work on it yourself.
</blockquote></details>

Done.  I changed a significant amount of this code to focus on the mathematics and the corresponding tests.  I removed all the Throw statements so ideally, you can do what you need without issue.  I think the important function to call is:

SpatialInertia<T>:: CalcMinimumPhysicalLength()

This should work with any type <T>, although it seems most sensible with a non-symbolic type that is real and finite (e.g., double or AutoDiff).

**Review by mitiguy — COMMENTED** [review]
@rpoyner-tri   Thanks for your comments. 
This PR was updated significantly to (hopefully) make it more useful for parsing.  The new tests in spatial_inertia_tests.cc help ensure that the length of the space-diagonal of the minimum bounding box is in fact what is returned by the function SpatialInertia:: CalcMinimumPhysicalLength().  There are also checks that the minimum bounding box corresponds directly to shapes with easily identifiable minimum bounding boxes (e.g., rod, rectangle, and box).  @sherm1 feel free to comment on the PR or check the derivation in the function UnitInertia<T>::CalcPrincipalHalfLengthsAndAxesForEquivalentShape in unit_inertia.cc.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-Nr7tlU82rfNhPCK5_NF:b-dyqzuw)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: doc questions
+@sherm1 for platform review, having already read much of this.

> Reviewed 3 of 7 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-NrHTRKS86u0zw_6Lj_0:blpccci)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 484 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrHSYj-5QHxvPsfg8mL:-NrHSYj-5QHxvPsfg8mM:b-f8uk7l) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/spatial_inertia.cc#L484)):*
> ```cpp
>   using std::sqrt;
>   return sqrt(2.0 * G_SScm_E.Trace());
>   // The derivation of the formula underlying this calculation is in
> ```

nit I think I would prefer this comment to be at the top of the function body, rather than at the end. Also, see question below about where to write down the proof.
___
*[`multibody/tree/unit_inertia.cc` line 308 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrHS7CTAI8hArDAqdhi:-NrHS7CTAI8hArDAqdhj:bm5qozu) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/unit_inertia.cc#L308)):*
> ```cpp
>   return std::pair(Vector3<double>(lmax, lmed, lmin), R_EA);
> 
>   // Proof that the space-diagonal of the minimum bounding box can be calculated
> ```

minor I'm good with having this proof somewhere, just looking for opinions on where it should go. It seems that here is an odd place, and maybe likely to be missed. Thoughts, @sherm1 ?

**Review by sherm1 — COMMENTED** [review]
Nice! I like this functionality and the test cases are very convincing.
Platform :lgtm: pending a few doc things

> Reviewed 3 of 7 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-NrI7zF87FYgsWJ3VK8y:b-2u2ptj)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 669 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI0m9sA_lF4Nz_8eZJ:-NrI0m9sA_lF4Nz_8eZK:b-cfeb3d) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/spatial_inertia.h#L669)):*
> ```objc
>   /// and 75 m wide, the USA space shuttle is ≈ 37 m long and can carry a 15.2 m
>   /// Canadarm, the world's largest humanoid robot (Mononofu) is ≈ 8.5 m tall.
>   T CalcMinimumPhysicalLength() const;
> ```

BTW for this and the previous function, consider saying something about the purpose, like "This can be useful in detecting erroneous inertias that are absurdly large, often due to units conversion issues."
___
*[`multibody/tree/unit_inertia.cc` line 308 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrHS7CTAI8hArDAqdhi:-NrI3snd7IBpxC8XeVc5:blh0h27) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/unit_inertia.cc#L308)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor I'm good with having this proof somewhere, just looking for opinions on where it should go. It seems that here is an odd place, and maybe likely to be missed. Thoughts, @sherm1 ?
</blockquote></details>

IMO the proof should be with CalcMinimumPhysicalLength(), with a reference to this function if necessary.
___
*[`multibody/tree/unit_inertia.cc` line 314 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI4Gtg9tFhj2E1UC9a:-NrI4Gtg9tFhj2E1UC9b:b8uewc1) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/unit_inertia.cc#L314)):*
> ```cpp
>   // 2. Gmin + Gmed + Gmax = Trace(this) is a unit inertia invariant meaning
>   //    Trace(this) = Gxx + Gyy + Gzz = Gmin + Gmed + Gmax is invariant to the
>   //    expressed-in frame for this unit inertia.
> ```

BTW does this mean the trace is invariant to whether there are products of inertia or not? The routine above first gets rid of those, then calculates the trace. If so, please mention that (I think I used to know that but I'm not certain).

A google search turned up this claim: "the trace of a symmetric matrix is invariant under an orthogonal transformation" -- that would seem to apply here?

Should also mention somewhere that the inertia_shape_factor=1 for the minimum bounding box!
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1362 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI6r-ZENgriclIo2ES:-NrI6r-ZENgriclIo2ET:b-kez15q) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/test/spatial_inertia_test.cc#L1362)):*
> ```cpp
>   EXPECT_TRUE(X_BA.translation() == p_BoBcm_B);
> 
>   // Repeat the previous test for the minimum bounding box B.
> ```

BTW consider adding "The answer should not be changed by translation"
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1422 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI7tey-5YsCfuBHDxj:-NrI7tey-5YsCfuBHDxk:b-5nsbrn) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/test/spatial_inertia_test.cc#L1422)):*
> ```cpp
> }
> 
> GTEST_TEST(SpatialInertia, VerifyMinimumBoundingBoxLengths) {
> ```

BTW great tests!

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`multibody/tree/spatial_inertia.h` line 669 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI0m9sA_lF4Nz_8eZJ:-NrIecnfEAw0cbqh3HKy:bmfxq1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/spatial_inertia.h#L669)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW for this and the previous function, consider saying something about the purpose, like "This can be useful in detecting erroneous inertias that are absurdly large, often due to units conversion issues."
</blockquote></details>

Done.  
___
*[`multibody/tree/spatial_inertia.cc` line 484 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrHSYj-5QHxvPsfg8mL:-NrI3J-UCGIpsw0PxyFJ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/spatial_inertia.cc#L484)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I think I would prefer this comment to be at the top of the function body, rather than at the end. Also, see question below about where to write down the proof.
</blockquote></details>

Done.
___
*[`multibody/tree/unit_inertia.cc` line 308 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrHS7CTAI8hArDAqdhi:-NrIeaczCTGINHcxgIy0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/unit_inertia.cc#L308)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

IMO the proof should be with CalcMinimumPhysicalLength(), with a reference to this function if necessary.
</blockquote></details>

Done.
___
*[`multibody/tree/unit_inertia.cc` line 314 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI4Gtg9tFhj2E1UC9a:-NrIe0EiD6rDCTOZCflh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/unit_inertia.cc#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this mean the trace is invariant to whether there are products of inertia or not? The routine above first gets rid of those, then calculates the trace. If so, please mention that (I think I used to know that but I'm not certain).

A google search turned up this claim: "the trace of a symmetric matrix is invariant under an orthogonal transformation" -- that would seem to apply here?

Should also mention somewhere that the inertia_shape_factor=1 for the minimum bounding box!
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1362 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI6r-ZENgriclIo2ES:-NrIeSRE2SqAuiHwRTl0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/test/spatial_inertia_test.cc#L1362)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding "The answer should not be changed by translation"
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1422 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrI7tey-5YsCfuBHDxj:-NrIeUtjCVB_ZW1-DBIr:b-vuj8ut) ([raw file](https://github.com/RobotLocomotion/drake/blob/723d64cdeed7a7b8589dcc97081c6dd3968820cb/multibody/tree/test/spatial_inertia_test.cc#L1422)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW great tests!
</blockquote></details>

Thank you :)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
This still needs typo fixes, squashing, and a  commit log message. Perhaps something like:

```
[multibody] Add spatial inertial minimum length methods

This patch adds a simple and very cheap calculation that infers a
minimum geometry size for a given spatial inertia tensor.

Given recent debugging misadventures with preposterous numbers, this
method is a step toward further sanity checking, to be integrated in
later work.
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-NrLsqxn04FJvA1jFoqK:bhmvr1n)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 663 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrLvUZ_3ZeKyULILrU8:-NrLvUZ_3ZeKyULILrU9:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d7a18e7220af487725679bdb2ec961dcad7a457/multibody/tree/spatial_inertia.h#L663)):*
> ```objc
>   /// object that underlies this spatial inertia. In other words, the underlying
>   /// physical object must have at least two particles whose distance between
>   /// each other is greater than or equal to the mininum possible length.
> ```

typo



_Suggestion:_
```objc
minimum
```
___
*[`multibody/tree/spatial_inertia.h` line 664 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrLuQwG4MUXDMypuS-s:-NrLuQwG4MUXDMypuS-t:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d7a18e7220af487725679bdb2ec961dcad7a457/multibody/tree/spatial_inertia.h#L664)):*
> ```objc
>   /// physical object must have at least two particles whose distance between
>   /// each other is greater than or equal to the mininum possible length.
>   /// @note The minium possible length is equal to the space-diagonal of the
> ```

typo



_Suggestion:_
```objc
minimium 
```
___
*[`multibody/tree/spatial_inertia.cc` line 502 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-NrLvGzM9EfzYwg_5ozd:-NrLvGzM9EfzYwg_5oze:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d7a18e7220af487725679bdb2ec961dcad7a457/multibody/tree/spatial_inertia.cc#L502)):*
> ```cpp
> //                    = 2 / inertia_shape_factor * Trace(unit_inertia)
> // 5. The largest inertia shape_factor is 1.0, which corresponds to a massless
> //    box with particles at its vertices. Hence the minimum space diagaonal is
> ```

typo



_Suggestion:_
```cpp
 diagonal
```

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20897#-:-Nrc2XJa5XNsnk2ocu6j:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Comment by jwnimmer-tri** [comment]
> Possible work for issue https://github.com/RobotLocomotion/drake/issues/20730.

To be clear -- this PR had some helpful code cleanups that improved implementation clarity, but the new API is not relevant for that ticket.  In that ticket, we need to distinguish between normal robot masses and astronomically huge bodies.  For that, the uniform ellipsoid (`CalcPrincipalSemiDiametersAndPoseForSolidEllipsoid`) would probably already have been sufficient to distinguish the two cases.  There is a gap of many orders of magnitude between the things we're trying to warn about vs not warn about.  The small factor between ellipsoid vs box-corners does not seem relevant, and so the `CalcPrincipalHalfLengthsAndPoseForMinimumBoundingBox` function does not seem to be on the critical path for solving that ticket.

I have said it before many times, and I guess I'll say it again -- when solving a UX issue, we need to start from an exposition of the use cases and work our way down from there.  In particular, since the most relevant facet of #20730 will be a _heuristic_ (as opposed to, e.g., fixing a bug with our implementation of the SDFormat specification), the first step in #20730 must be collecting use cases and proposing heuristic(s) that best fit them.  If you haven't done the work yet of writing up a list of heuristic ideas and seeking a document review on the possible choices of heuristic, it is _way too early_ to start writing code.  The most important part of #20730 is capturing use cases and turning those into test cases which will prove the heuristic has the true positive / true negative / false positive / false negative behavior that we seek.

Starting from the low-level code and trying to guess what code might help users will hit lot of false starts, retreats, and trying again.  We see that again in #21081, which is actively harmful for users.

If you are trying to work on #20730, please don't submit any more code for discussion until you have done some preparation on the back story so that you can explain to your reviewers why the big-picture approach is a good one.  The code is not the interesting part.  The reasoning behind it is, and that's what we need to focus on now.

**Pull request merged**
