### PR TITLE
Add SNOPT to the Bazel build.

### PR DESCRIPTION
**Pull request by david-german-tri**
Follows https://github.com/RobotLocomotion/snopt/pull/17

DNR, DNM for now while I test on OS X.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5020)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by david-german-tri** [comment]
Works on OS X locally.  +@jwnimmer-tri for feature review

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwN7mxhWzOkJTYfh7R:-KbwN7mxhWzOkJTYfh7S:b5h0m9) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/WORKSPACE#L171)):*
> ```
>   name = "snopt",
>   remote = "git@github.com:RobotLocomotion/snopt.git",
>   commit = "9f8c7972fa257d2341ecefcf58617e11b9ebb504",
> ```

BTW  I think we should bump the gitmodules external to match the same sha?

---

*[drake/solvers/BUILD, line 367 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwNoHcV-hLnAkckAdG:-KbwNoHcV-hLnAkckAdH:b-owga9a) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/drake/solvers/BUILD#L367)):*
> ```Python
>     "gurobi_solver.h",
>     "no_gurobi.cc",
> ])
> ```

The snopt files probably have to be listed here here now.  The https://github.com/RobotLocomotion/drake/blob/master/tools/dev/check_missing_sources.sh can help run a report for you to confirm if you are unsure.

---

*[tools/bazel.rc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwNZKwn8yJKZODJNEq:-KbwNZKxR6WqNemOOCMl:b-ik7kh8) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/tools/bazel.rc#L49)):*
> ```
> test:everything --test_tag_filters=
> 
> # -- Options for Gurobi.
> ```

BTW This is not quite true anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwPJOoXWhCpujgwToe:-KbwPJOoXWhCpujgwTof:bivl2cc) (no related file):*
```
ERROR: .../external/snopt/csrc/BUILD:3:1: @snopt//csrc:snopt_c: no such attribute 'strip_include_prefix' in 'cc_library' rule
```

The `strip_include_prefix` is a Bazel 0.4.3 feature, and we support 0.4.2 right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwPJOoXWhCpujgwToe:-KbzJIP7IXpdhuGIqPbr:bsd9h1o) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

```
ERROR: .../external/snopt/csrc/BUILD:3:1: @snopt//csrc:snopt_c: no such attribute 'strip_include_prefix' in 'cc_library' rule
```

The `strip_include_prefix` is a Bazel 0.4.3 feature, and we support 0.4.2 right now.
</blockquote></details>

Oooh, that's unfortunate.  I'll spend a little time looking into workarounds, then likely bump us to 0.4.3 unless you have objections.  (Seems CI is already there.)

---

*[WORKSPACE, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwN7mxhWzOkJTYfh7R:-KbzH93ezqgpZCCnO2_m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/WORKSPACE#L171)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW  I think we should bump the gitmodules external to match the same sha?
</blockquote></details>

Done.

---

*[drake/solvers/BUILD, line 367 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwNoHcV-hLnAkckAdG:-KbzJ6QdrA5LTMXDMRWa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/drake/solvers/BUILD#L367)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The snopt files probably have to be listed here here now.  The https://github.com/RobotLocomotion/drake/blob/master/tools/dev/check_missing_sources.sh can help run a report for you to confirm if you are unsure.
</blockquote></details>

Done.

---

*[tools/bazel.rc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwNZKwn8yJKZODJNEq:-KbzJH34h_JzsLd-rBmH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2bbf6faba0bc1b066e72342ea33456428492322/tools/bazel.rc#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This is not quite true anymore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwPJOoXWhCpujgwToe:-KbzNwK3vkefsT4NsyDs:b-91hxs3) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Oooh, that's unfortunate.  I'll spend a little time looking into workarounds, then likely bump us to 0.4.3 unless you have objections.  (Seems CI is already there.)
</blockquote></details>

SGTM.  Also change the CI driver to use the `--config=everything` setting, in at least some config(s)?

---

*[tools/dev/check_missing_sources.sh, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbzOEdmWgOuqeGuYySm:-KbzOEdn24yALHEkSjXx:brwyhdi) ([raw file](https://github.com/robotlocomotion/drake/blob/8b9f2234f43283abb117909266962d8e19d6f9dc/tools/dev/check_missing_sources.sh#L11)):*
> ```Shell
> 
> # Files covered by cc_ something.
> bazel query 'kind("source file", deps(kind("cc_.* rule", //... except //externals/...)))' |
> ```

OK Nice!  I had been conflicted about how to solve this for gurobi, and I didn't think of this option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-KbwPJOoXWhCpujgwToe:-KbzOGTlsJdC2iWiwoDa:b-5sia1a) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Oooh, that's unfortunate.  I'll spend a little time looking into workarounds, then likely bump us to 0.4.3 unless you have objections.  (Seems CI is already there.)
</blockquote></details>

`cc_inc_library` doesn't cut it; we would be into Skylark territory at least.  I think it's better to bump the version.  (Done.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r4.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5020#-:-KbzOUckStQpA0NSYTP6:bnfp4nl)*

**Pull request merged**
