### PR TITLE
Fix more minor issues in the drake/automotive demos

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is more "getting it to work again at all ever".  Next up will be namespace fixup.  Then some logic fixups with unit tests.  Then some automated acceptance tests that would have found these path issues.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3446)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/run_demo_multi_car.sh, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KRe0244wZ0_A4hWUkua:-KRe0244wZ0_A4hWUkub:be8oymh) ([raw file](https://github.com/robotlocomotion/drake/blob/002d5e1368bc7737b23da40df776cc2d7ab8c694/drake/automotive/run_demo_multi_car.sh#L33)):*
> ```Shell
> 
> function bot_spy_that_actually_works {
>     set -x
> ```

is this debug cruft?

---

*[drake/automotive/simple_car_demo.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KRe0Aq0cA8zrWMhHH0W:-KRe0Aq0cA8zrWMhHH0X:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/002d5e1368bc7737b23da40df776cc2d7ab8c694/drake/automotive/simple_car_demo.sh#L31)):*
> ```Shell
> 
> function bot_spy_that_actually_works {
>     set -x
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/run_demo_multi_car.sh, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KRe0244wZ0_A4hWUkua:-KRe0VCtVMW1Vmgy4eux:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/002d5e1368bc7737b23da40df776cc2d7ab8c694/drake/automotive/run_demo_multi_car.sh#L33)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> is this debug cruft?
</details>
Done.

---

*[drake/automotive/simple_car_demo.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KRe0Aq0cA8zrWMhHH0W:-KRe0Vn8smLbywj8q4pn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/002d5e1368bc7737b23da40df776cc2d7ab8c694/drake/automotive/simple_car_demo.sh#L31)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> ditto
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-:-KRe0h_Dut_b8XlJTfNN:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-:-KRe1-21qUt5abuqeLw8:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/run_demo_multi_car.sh, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KReBZ1PuAyAOsXahuR4:-KReBZ1PuAyAOsXahuR5:b6hv2bu) ([raw file](https://github.com/robotlocomotion/drake/blob/a50f1bd325c14172a73f7ea0e83efc6b2fd51acf/drake/automotive/run_demo_multi_car.sh#L38)):*
> ```Shell
> }
> 
> # TODO(#3232) Use this shell script once it works again.
> ```

BTW it would be nice if we could be at all sure that these TODOs would be removed when #3232 was fixed, but I'm not 100% sure how to do that.  Comment in the ticket indicating what to grep for?  Or don't do anything at all...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-:-KReBs7b_3eImzaiwUyS:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/automotive/run_demo_multi_car.sh, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-KReBZ1PuAyAOsXahuR4:-KReP9nRWxdLW-Lfow5y:b-5vzt0c) ([raw file](https://github.com/robotlocomotion/drake/blob/a50f1bd325c14172a73f7ea0e83efc6b2fd51acf/drake/automotive/run_demo_multi_car.sh#L38)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW it would be nice if we could be at all sure that these TODOs would be removed when #3232 was fixed, but I'm not 100% sure how to do that.  Comment in the ticket indicating what to grep for?  Or don't do anything at all...
</details>
Done (comment in ticket).

Also this helped me notice that the issue number was typo'd; fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446#-:-KReQElgTECbRdeis3qX:b-83330m)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3446)*

**Comment by jwnimmer-tri** [comment]
The ROS build passed last time, and this push was comment-only changes, so I'll not re-run it.

**Pull request merged**
