### PR TITLE
[render] Stop polluting downstream include paths with vtk

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Successor to #17169 and #17376.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17377)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17377)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`tools/install/libdrake/header_lint.bzl` line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17377#-N4E-QnT1GrBSYO2xz2l:-N4E-QnV2tI9MbmurIkF:b-ck3m4b) ([raw file](https://github.com/robotlocomotion/drake/blob/98762d8c5b1b5cf7ea56e5e512a5682d943083d4/tools/install/libdrake/header_lint.bzl#L46)):*
> ```Starlark
>     "HAVE_CSTDDEF",
>     "SDFORMAT_DISABLE_CONSOLE_LOGFILE",
>     "SDFORMAT_STATIC_DEFINE",
> ```

FYI Some of these were obsolete as of prior PRs, but in any case this PR gets is nearly 100% clean.  The only straggler is `@glib`, leaking in from LCM somewhere.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17377#-:-N4E5xtyE1biISBaCxGu:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17377)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
