### PR TITLE
Add a construtor to allow IDC to own the input plant

### PR DESCRIPTION
**Pull request by huihuaTRI**
This PR is trying to resolve the [issue](https://github.com/RobotLocomotion/drake/issues/14011).

This is still a work-in-progress. It's up for discussion purposes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037)

### CODE REVIEW

**Review by huihuaTRI — COMMENTED** [review]
Hi, @ggould-tri can you please help take a look at the changes I made? I added another constructor that takes ownership of the given plant. I am looking for your suggestions on whether this is a proper workaround. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGjdpCw-bqFtzOzbmKn:b-10d86i)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by huihuaTRI — COMMENTED** [review]
The CI fails due to the pybind, which I will fix later.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGjoEsd6xbg6X-u69Bn:b-ybgs34)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
The API is exactly what I was hoping for.  However I think your implementation is incorrect; see the comment below.  I expect you're going to need a smart pointer somewhere to solve this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGmryvN8Tl7sVCgjV9r:brtvdqg)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @huihuaTRI)

___
*[systems/controllers/inverse_dynamics_controller.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGmrSTu7RVmkRSuFDqk:-MGmrSTu7RVmkRSuFDql:byzt05a) ([raw file](https://github.com/robotlocomotion/drake/blob/16e18f49473eb4f04357a1bdc4aa1530034c5817/systems/controllers/inverse_dynamics_controller.cc#L125)):*
> ```cpp
>     const VectorX<double>& kp, const VectorX<double>& ki,
>     const VectorX<double>& kd, bool has_reference_acceleration)
>     : multibody_plant_for_control_(plant.release()),
> ```

I believe that this leaks `plant`, as you are releasing it from a smart pointer into a bare pointer that is never deleted.

This is what this CI failure is flagging: https://drake-cdash.csail.mit.edu/testDetails.php?test=39054719&build=1335802

**Review by jwnimmer-tri — COMMENTED** [review]
See `luenberger_observer` for an example:

https://github.com/RobotLocomotion/drake/blob/71dbe45d6f4a58d27a3b34d18e27388ab42ae011/systems/estimators/luenberger_observer.h#L109-L110

We overload the constructor to take both flavors, and keep both flavors as member variables.  The owned flavor member is sometimes null.  The code always operates on the unowned member; the owned member is _only_ there for storage.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGn61oLBL8juRrmck0W:b1pvj25)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @huihuaTRI)

___
*[systems/controllers/inverse_dynamics_controller.h, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGn631D0IPPndd5-zI3:-MGn631D0IPPndd5-zI4:b-9821cn) ([raw file](https://github.com/robotlocomotion/drake/blob/16e18f49473eb4f04357a1bdc4aa1530034c5817/systems/controllers/inverse_dynamics_controller.h#L113)):*
> ```objc
>    *  - Vector kp, ki and kd do not all have the same size equal to the number
>    *    of generalized positions.
>    */
> ```

nit Do not copy-paste documentation, it's unmaintainable.

Two possible solutions:

(1) Make this doc very short, only explaining the differences vs the other overload.  (This is the one I prefer).

(2) Use a Doxygen grouping to apply the same docstring to both.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

**Review by ggould-tri — COMMENTED** [review]
All files reviewed.  As noted, one doc issue and the storage issue (Jeremy is right about the common way to handle this), plus of course the python bindings.  I'll take a second look once that's in place.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGnU51V1oGDB5t4-e1g:bqxakhd)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @huihuaTRI)

**Review by huihuaTRI — COMMENTED** [review]
Thanks for the review. I thought about the method Jeremy mentioned, but I eventually choose the implementation currently is there and forgot to add the delete in the destructor. One reason I didn't choose to use the better one is I feel it's not necessary to keep two internal members for the same thing.

However, I do realize that I was wrong anyway. Even though the pointer is taken care of in the destructor. It's still not safe to do so and does not eliminate the probability of a dangling pointer if the program aborts somewhere before the destructor. 

I would like to learn if there are any other reasons. Thanks!

I will fix the comments and add a proper unit test. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGndX2p8Y9UWwP5OPAK:b-bhe1vt)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @huihuaTRI)

**Review by huihuaTRI — COMMENTED** [review]
I have fixed the comments and added unit tests. One thing I need suggestion is how to unit test the new constructor in pydrake. My understanding is that there is no easy way (if possible) to differentiate passing by reference or by a pointer. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGpZAqyBCx8giXyI45X:b-g09y7i)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[bindings/pydrake/systems/controllers_py.cc, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGpYyNg7aUHP_VJK-DW:-MGpYyNg7aUHP_VJK-DX:bz1swvw) ([raw file](https://github.com/robotlocomotion/drake/blob/3df895955a64baeec36fe396e4f6c5fa60a06d91/bindings/pydrake/systems/controllers_py.cc#L103)):*
> ```cpp
>           py::arg("has_reference_acceleration"),
>           // Keep alive, ownership: `plant` keeps `self` alive.
>           py::keep_alive<2, 1>(),
> ```

Hi @ggould-tri I don't quite get what does `keep_alive` mean here. Could you please give me some advice?

**Review by ggould-tri — COMMENTED** [review]
:lgtm: with some notes below.  I'm not a pybind expert so I'm asking for a bit of expert assistance.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGs7RVV7acfeap_sbrd:b-e8uowo)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @huihuaTRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGs9ONC-EV76EtBR97s:-MGs9ONC-EV76EtBR97t:b-oju1r) (no related file):*
Tagging @ericcousineau-tri for some consultation here, since I'm no pybind expert.

See the `controllers_py.cc` comment below.  I believe that pydrake already had the desired behaviour due to the `keep_alive<1,2>` and so there is no need to bind the new constructor?

---
___
*[bindings/pydrake/systems/controllers_py.cc, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGpYyNg7aUHP_VJK-DW:-MGs7ijk3m7nE_FsSuU3:brwia4t) ([raw file](https://github.com/robotlocomotion/drake/blob/3df895955a64baeec36fe396e4f6c5fa60a06d91/bindings/pydrake/systems/controllers_py.cc#L103)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

Hi @ggould-tri I don't quite get what does `keep_alive` mean here. Could you please give me some advice?
</blockquote></details>

`keep_alive<2,1>` means that argument 1 (`self`) cannot be destroyed by the python garbage collector until argument 2 (`robot`, although the comment incorrectly says `plant`) is, even if you let it go out of scope.  This is the opposite of the previous ctor.

It's not obvious to me that this is correct.  `robot` is likely to be released quickly by the caller, so I would expect this to have no effect in general.  The previous ctor's `keep_alive<1,2>` looks more correct to me (in fact I expect it was already accomplishing on the python side what the rest of this PR does on the C++ side).

I've tagged in Eric on a meta-issue here to check my thinking.

**Comment by EricCousineau-TRI** [comment]
Another casualty of #13058

**Review by huihuaTRI — COMMENTED** [review]
Got it, thanks for the discussion.  +@ericcousineau-tri for platform review since Grant is already the feature reviewer. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGtM_8G8JfSogh2YYZS:bnxwr9k)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @ggould-tri)

___
*[bindings/pydrake/systems/controllers_py.cc, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGpYyNg7aUHP_VJK-DW:-MGtMRu5A4QEdsMPtf6b:bjztuwi) ([raw file](https://github.com/robotlocomotion/drake/blob/3df895955a64baeec36fe396e4f6c5fa60a06d91/bindings/pydrake/systems/controllers_py.cc#L103)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

`keep_alive<2,1>` means that argument 1 (`self`) cannot be destroyed by the python garbage collector until argument 2 (`robot`, although the comment incorrectly says `plant`) is, even if you let it go out of scope.  This is the opposite of the previous ctor.

It's not obvious to me that this is correct.  `robot` is likely to be released quickly by the caller, so I would expect this to have no effect in general.  The previous ctor's `keep_alive<1,2>` looks more correct to me (in fact I expect it was already accomplishing on the python side what the rest of this PR does on the C++ side).

I've tagged in Eric on a meta-issue here to check my thinking.
</blockquote></details>

Thanks for the help. I have removed the bound as suggested.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14037#-:-MGtm0tpDBcSmI3f_ZZ0:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14037#-MGs9ONC-EV76EtBR97s:-MGtm-BFBi1sl_kNHY9w:b-ngtteo) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Tagging @ericcousineau-tri for some consultation here, since I'm no pybind expert.

See the `controllers_py.cc` comment below.  I believe that pydrake already had the desired behaviour due to the `keep_alive<1,2>` and so there is no need to bind the new constructor?
</blockquote></details>

OK Yup, correct!

---

**Pull request merged**
