### PR TITLE
[multibody] Zero out anchored inertias

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21095.

With the recent addition of the SAP constraints feature, we now have situation where some very common modeling features (e.g., constraints for a parallel-jaw gripper) are baked into the MbP model (often via some SDFormat input file), and **are incompatible with certain other MbP settings choices** like the `time_step` or `discrete_contact_approximation`.  When users have models with those constraints, they are forbidden from e.g. using a continuous-time plant -- the MbP will throw an error if they try to add their model to such a plant.

This has ripple effects throughout all of Drake.  Of course if users are simulating the MbP, they need to think about the dynamics model they want, and choose something plausible.  However, this design also affects things not related to simulation at all, like simply opening the model file in our standalone visualizer (#21095), or using the model for motion planning.  Those applications can no longer be agnostic to the `time_step` or contact approximation settings.  Every single one of those uses of the MbP must be changed to specify a SAP-capable plant, so that the plant is thus able to ingest any kind of model the user throws at it.

This presents a challenge, because the discrete-time plant currently induces _more requirements_ on the models, which the continuous-time plant did not.  Currently for a discrete-time plant, all inertia values must be valid, even for bodies that are anchored to the world.  This means that when users switch to SAP, any models where anchored geometry was given via bodies constructed using a **default SpatialInertia** will now throw (in debug builds), since the default spatial inertia is NaNs.  I hit this in #21098 when I converted our default planning model to use discrete time instead of continuous time.

One way to avoid throwing new errors at users is to change the MbP to stop caring about anchored inertias.  This commit changes the MbP to zero out all anchored inertias.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21151)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 and +@amcastro-tri for _design discussion_, please.  Obviously in r1 the code here is insufficient & incomplete, but before I clean anything up I want to make sure its heading in the right direction.  I've confirmed that this change solves my immediate problem.

Another question will be if @sherm1 already has something like this in the pipeline with his new graphing code.  If so, we can chat about pausing this and/or de-conflicting this particular change.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-:-Nt2aQbb5bQketIrPGMH:b-nd4702)* status: 5 unresolved discussions, LGTM missing from assignees sherm1(platform),amcastro-tri, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/tree/multibody_tree.cc` line 1226 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2amV65M_tYYSNxpWx:-Nt2amV65M_tYYSNxpWy:b-2ws3gl) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L1226)):*
> ```cpp
>   for (BodyIndex body_index(1); body_index < num_bodies(); ++body_index) {
>     const RigidBody<T>& body = get_body(body_index);
>     if (topology_.IsBodyAnchored(body_index)) {
> ```

Obviously `IsBodyAnchored` is too slow for this inner loop.  If we keep this idea, I plan to have the anchored-ness available as a pre-computed attribute of the topology (or similar).
___
*[`multibody/tree/multibody_tree.cc` line 2023 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2bC4f1RmbpEWZwrry:-Nt2bC4f1RmbpEWZwrrz:b-rqhve) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L2023)):*
> ```cpp
>   Vector3<T> sum_mi_pi = Vector3<T>::Zero();
> 
>   // Sum over all the bodies except the 0th body (which is the world body).
> ```

This is bizarre to me.

We are excluding the mass of the world body, but not other bodies that are welded to the world?

I could see the case for adding all of the bodies (world and everything), or the case for excluding all anchored mass (world body and anchored bodies), but I have no idea why splitting the difference could ever be the correct choice.

What should we do with anchored bodies here, to be consistent with the rest of the MbP?
___
*[`multibody/tree/multibody_tree.cc` line 2176 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2bspB-Zh8KhVx6Rv7:-Nt2bspC8q3PTC7RJ5fH:bndfn1) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L2176)):*
> ```cpp
>   Vector3<T> sum_mi_vi = Vector3<T>::Zero();
> 
>   // Sum over all the bodies except the 0th body (which is the world body).
> ```

Ditto here -- why exclude the world, but not anchored bodies?
___
*[`multibody/tree/multibody_tree.cc` line 3041 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2c9Km6jssbxgDswJk:-Nt2c9Km6jssbxgDswJl:bndfn1) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L3041)):*
> ```cpp
>   Js_v_ACcm_E->setZero();
>   T composite_mass = 0;
>   for (BodyIndex body_index(1); body_index < num_bodies(); ++body_index) {
> ```

Ditto here -- why exclude the world, but not anchored bodies?
___
*[`multibody/tree/multibody_tree.cc` line 3156 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2cFi92pMjOVtybITn:-Nt2cFi92pMjOVtybITo:bndfn1) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L3156)):*
> ```cpp
>   T composite_mass = 0;
>   Vector3<T> asBias_ACcm_E = Vector3<T>::Zero();
>   for (BodyIndex body_index(1); body_index < num_bodies(); ++body_index) {
> ```

Ditto here -- why exclude the world, but not anchored bodies?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21151)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/tree/multibody_tree.cc` line 1226 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2amV65M_tYYSNxpWx:-Nt7WqtO62CDkMg8NMUQ:bdt7bug) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L1226)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Obviously `IsBodyAnchored` is too slow for this inner loop.  If we keep this idea, I plan to have the anchored-ness available as a pre-computed attribute of the topology (or similar).
</blockquote></details>

BTW "is anchored" is free in the new topology code

**Review by sherm1 — COMMENTED** [review]
Currently MbP doesn't combine welded-together links into a single mobilized body in the multibody tree. That means it actually models the weld joints. Although those prevent relative motion between bodies, they do so by generating appropriate reaction forces on the bodies and those are calculated and reported. To calculate those correctly, we need the masses of all the anchored links, since gravity acts on them to produce forces and torques at the weld joints. However, the inertias don't matter. 

In the hopefully-not-too-distant future it will be possible for users to delete a weld joint, after which the inertias would be important. Consequently my preference would be to leave inertias at NaN if they haven't been specified but ignore them for anchored links, rather than setting them to some arbitrary value that could be confused with a user-specified one (and zero inertia is legitimate for links that are non-terminal or welded to something else).

The new graphing stuff has the option to combine welded links to single bodies, and contains a cheaply-precomputed "is anchored" flag for every link. In that case internal weld joints are not modeled at all so we won't get reaction forces for those (that's overridable for individual welds if someone wants that info). However, the "combine welded links" option is off by default because further MbP changes are required to remove its pervasive assumption that n_links==n_bodies.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-:-NtIILwt7ddyQ-iBrCou:bu3i4rb)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21151)* status: 5 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform), labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/tree/multibody_tree.cc` line 2023 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2bC4f1RmbpEWZwrry:-NtIMWxWA6DKJdM_K_u1:b-vv6sbc) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L2023)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is bizarre to me.

We are excluding the mass of the world body, but not other bodies that are welded to the world?

I could see the case for adding all of the bodies (world and everything), or the case for excluding all anchored mass (world body and anchored bodies), but I have no idea why splitting the difference could ever be the correct choice.

What should we do with anchored bodies here, to be consistent with the rest of the MbP?
</blockquote></details>

World is considered to have infinite mass and inertia. In the (future) case where we directly incorporate all anchored bodies into World, their mass props don't matter. However, in the (present) case where the welds-to-World are actually modeled, the reaction forces calculated there depend on the masses of the anchored links but _not_ on any properties of World. BTW it is actually useful to model a weld that connects directly to World -- consider a robot arm bolted to the floor: if you want to know the forces acting between the arm and the floor (useful e.g. for sizing the bolts) model the weld joint there and look at the calculated reaction forces.
___
*[`multibody/tree/multibody_tree.cc` line 2176 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2bspB-Zh8KhVx6Rv7:-NtINjou2MseV8PDogZE:b-34vmyd) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L2176)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto here -- why exclude the world, but not anchored bodies?
</blockquote></details>

See above
___
*[`multibody/tree/multibody_tree.cc` line 3041 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2c9Km6jssbxgDswJk:-NtINm0R8jqObE8iFfdr:b-34vmyd) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L3041)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto here -- why exclude the world, but not anchored bodies?
</blockquote></details>

See above
___
*[`multibody/tree/multibody_tree.cc` line 3156 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21151#-Nt2cFi92pMjOVtybITn:-NtINmbg5-KS6k54x29K:b-34vmyd) ([raw file](https://github.com/RobotLocomotion/drake/blob/51714d9d1baa1580b5e873d95348a208f73256d8/multibody/tree/multibody_tree.cc#L3156)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto here -- why exclude the world, but not anchored bodies?
</blockquote></details>

See above

**Pull request closed without merging**
