### PR TITLE
KinematicsCache object

### PR DESCRIPTION
**Pull request by tkoolen**
Extracted kinematics cache out of RigidBody and RigidBodyManipulator and put it all in
```
template <typename Scalar>
class KinematicsCache
```

doKinematicsmex now returns a mex pointer to the KinematicsCache object.

This means that:
* RigidBodyManipulator has a lot less state in it, allowing us to make many methods const
* We're a big step closer to being able to call RBM methods with AutoDiffScalar and TrigPoly inputs (see https://github.com/RobotLocomotion/drake/issues/1199.)
* the order of doKinematics calls does not matter anymore, i.e. you can call doKinematics twice, use the kinsol from the first one, and get the expected results.

I'm going to do some benchmarking to see if creating a new KinematicsCache on every doKinematics call is too expensive, but I wanted to get this pull request out there too.

### CODE REVIEW

**Comment by tkoolen** [comment]
One issue is that this breaks examples/Atlas/test/testRunningPlanner if we enable mex (another part of the reason for this pull request is to allow testRunningPlanner to use mex). This seems to be due to tiny numerical differences between Matlab and mex, and the extreme sensitivity of testRunningPlanner to this change.

**Comment by avalenzu** [comment]
Re. testRunningPlanner:  I'll take a look at this tomorrow.

**Comment by tkoolen** [comment]
@avalenzu, actually, I can't reproduce the issue anymore?! Could there be any state in testRunningPlanner that isn't source code?

**Comment by tkoolen** [comment]
so execution time of the now apparently working mex-calling testRunningPlanner is 40 seconds on my machine, compared to 184 without mex.

**Comment by tkoolen** [comment]
Decided to remove individualCentersOfPressure by the way. It was very far from working at this point. Fixes https://github.com/RobotLocomotion/drake/issues/585.

**Comment by avalenzu** [comment]
The SNOPT library itself has a certain amount of state. Running back to back programs of the same size causes the basis from the first to be used as a starting point for the second. On some occasions I've even observed an effect from running back to back programs of *differing* sizes - e.g. solving an IK problem causes a subsequent ComDynamicsFullKinematics program to fail. It's never been repeatable enough to track down though :(

**Comment by tkoolen** [comment]
Looks like drake004 is having some issues.

**Comment by tkoolen** [comment]
Probably shouldn't merge this until I'm done profiling; this will probably slow things down quite significantly right now (but that can be mitigated). See https://github.com/RobotLocomotion/drake/issues/1199.

**Comment by RussTedrake** [comment]
added tag so I remember not to merge it.

**Comment by tkoolen** [comment]
closing while I'm pushing changes.

**Pull request closed without merging**
