### PR TITLE
Mosek supports L2NormCost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #20552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-:-Nup-orLAnMGwkagTILc:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-:-NupCK-51EgEJwkf68qE:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.cc` line 1009 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-Nup3xP70O8yH7ESemay:-Nup3xP70O8yH7ESemaz:b-c1bicz) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1009)):*
> ```cpp
>   const MSKint32t s_index = num_mosek_vars;
>   // Put bound on s as s >= 0.
>   rescode = MSK_putvarbound(task_, s_index, MSK_BK_LO, 0, MSK_INFINITY);
> ```

BTW: Oof that enum is a subtle one. How did you catch that?
___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-NupBE8w1UW9I5ny7er6:b-kuaipk) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
> ```cpp
>   }
>   Eigen::SparseMatrix<double> A(C.rows() + 1, C.cols());
>   A.setFromTriplets(A_triplets.begin(), A_triplets.end());
> ```

BTW: is it more efficient to do this, and then call `sparseView`? A is already almost as dense as C.



_Suggestion:_
```cpp
  Eigen::MatrixXd A(C.rows()+1, C.cols());
  A.bottomRows(C.rows()) = C; 
  A.row(0) = Eigen::VectorXd::Zeros(C.cols());
```

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.h` line 471 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupDpFc4JKPswX8-2b0:-NupDpFd0LRrUMNsiGos:b-6qv52t) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.h#L471)):*
> ```objc
>       // is in Mosek's rotated quadratic cone. Namely we multiply 0.5 to the
>       // first row of A, b.
>       const Eigen::SparseMatrix<double>& A = binding.evaluator()->A();
> ```

This is the change breaking the `scaled_diagonally_dominant_matrix_test`. It's subtle, but in a few lines down, you access a reference to an entry in A and then modify it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/mosek_solver_internal.h` line 471 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupDpFc4JKPswX8-2b0:-NupKwQz05R3UkoSc8gc:b-1lwtto) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.h#L471)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is the change breaking the `scaled_diagonally_dominant_matrix_test`. It's subtle, but in a few lines down, you access a reference to an entry in A and then modify it.
</blockquote></details>

Done.

Thanks for catching it!
___
*[`solvers/mosek_solver_internal.cc` line 1009 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-Nup3xP70O8yH7ESemay:-NupKzkF3nRLhDnyctqw:b-b30u1r) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1009)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: Oof that enum is a subtle one. How did you catch that?
</blockquote></details>

I was reading the old code while implementing the new one and saw this line, which doesn't make sense to me.
___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-NupRasq2C0GT0YsBlgK:bo60rnv) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: is it more efficient to do this, and then call `sparseView`? A is already almost as dense as C.
</blockquote></details>

Good call, it is indeed faster to use the dense-to-sparse matrix version.

I did a quick timing on constructing the matrix using two approaches, one by std::vector<Eigen::Triplet<double>>, and one by first to dense, and then use sparseView()
```cc
#include <Eigen/Core>
#include <Eigen/Sparse>
#include <chrono>
#include <vector>
#include <iostream>

int main() {
  Eigen::MatrixXd A_dense(4, 8);
  A_dense(0, 1) = 2;
  A_dense(2, 4) = 1;
  A_dense(3, 5) = -2;
  A_dense(1, 4) = 3;
  A_dense(1, 6) = 3;
  A_dense(3, 6) = 3;
  const Eigen::SparseMatrix<double> A = A_dense.sparseView();

  auto start1 = std::chrono::high_resolution_clock::now();
  for (int count = 0; count < 10000; ++count) {
    std::vector<Eigen::Triplet<double>> C_triplets;
    C_triplets.reserve(A.nonZeros());
    for (int i = 0; i < A.outerSize(); ++i) {
      for (Eigen::InnerIterator it(A, i); it; ++it) {
        C_triplets.emplace_back(it.row() + 1, it.row(), ++it);
      }
    }
    Eigen::SparseMatrix<double> C(A.rows() + 1, A.cols());
    C.setFromTriplets(C_triplets.begin(), C_triplets.end());
  }
  auto end1 = std::chrono::high_resolution_clock::now();
  std::cout << "triplets takes: " << std::chrono::duration_cast<std::chrono::microseconds
    >(end1 - start1).count() << "ms\n";

  auto start2 = std::chrono::high_resolution_clock::now();
  for (int count = 0; count < 10000; ++count) {
  Eigen::MatrixXd C_dense(A.rows() + 1, A.cols());
  C_dense.bottomRows(A.rows()) = A;
  C_dense.row(0).setZero();
  Eigen::SparseMatrix<double> C = C_dense.sparseView();
  }
  auto end2 = std::chrono::high_resolution_clock::now();
  std::cout << "sparseView takes: " << std::chrono::duration_cast<std::chrono::microseconds
    >(end2 - start2).count() << "ms\n";
  return 0;
}

```
And the result is
```
triplets takes: 67205ms
sparseView takes: 41615ms
```

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for doing all of this! :lgtm: 

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-:-NupW7PC-2QsX4E-jH5f:b-h46v29)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-:-NuyYq9Y6Bb5epwM9S6V:b-3lhrgq)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with one comment.

+(release notes: feature) 

> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-:-NuydcPg2SnYmFt8XoxW:boluj2o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform)

___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-NuybFBF8KsItxAb6VLJ:b-agm07l) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call, it is indeed faster to use the dense-to-sparse matrix version.

I did a quick timing on constructing the matrix using two approaches, one by std::vector<Eigen::Triplet<double>>, and one by first to dense, and then use sparseView()
```cc
#include <Eigen/Core>
#include <Eigen/Sparse>
#include <chrono>
#include <vector>
#include <iostream>

int main() {
  Eigen::MatrixXd A_dense(4, 8);
  A_dense(0, 1) = 2;
  A_dense(2, 4) = 1;
  A_dense(3, 5) = -2;
  A_dense(1, 4) = 3;
  A_dense(1, 6) = 3;
  A_dense(3, 6) = 3;
  const Eigen::SparseMatrix<double> A = A_dense.sparseView();

  auto start1 = std::chrono::high_resolution_clock::now();
  for (int count = 0; count < 10000; ++count) {
    std::vector<Eigen::Triplet<double>> C_triplets;
    C_triplets.reserve(A.nonZeros());
    for (int i = 0; i < A.outerSize(); ++i) {
      for (Eigen::InnerIterator it(A, i); it; ++it) {
        C_triplets.emplace_back(it.row() + 1, it.row(), ++it);
      }
    }
    Eigen::SparseMatrix<double> C(A.rows() + 1, A.cols());
    C.setFromTriplets(C_triplets.begin(), C_triplets.end());
  }
  auto end1 = std::chrono::high_resolution_clock::now();
  std::cout << "triplets takes: " << std::chrono::duration_cast<std::chrono::microseconds
    >(end1 - start1).count() << "ms\n";

  auto start2 = std::chrono::high_resolution_clock::now();
  for (int count = 0; count < 10000; ++count) {
  Eigen::MatrixXd C_dense(A.rows() + 1, A.cols());
  C_dense.bottomRows(A.rows()) = A;
  C_dense.row(0).setZero();
  Eigen::SparseMatrix<double> C = C_dense.sparseView();
  }
  auto end2 = std::chrono::high_resolution_clock::now();
  std::cout << "sparseView takes: " << std::chrono::duration_cast<std::chrono::microseconds
    >(end2 - start2).count() << "ms\n";
  return 0;
}

```
And the result is
```
triplets takes: 67205ms
sparseView takes: 41615ms
```
</blockquote></details>

I'm not sure if this is a conclusive experiment. The test matrix is relatively small and dense.

This is what I get by changing A_dense to be of size 400 x 800 without changing the nonzero entries.

```
triplets takes: 43449ms
sparseView takes: 3478375ms
```

I'm not sure what the typical size of the problem this is targeting, but I thought you might find the info above useful.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: 1 unresolved discussion

___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-Nuydrv3Ars7CCiZ_R7S:b7rm9hp) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure if this is a conclusive experiment. The test matrix is relatively small and dense.

This is what I get by changing A_dense to be of size 400 x 800 without changing the nonzero entries.

```
triplets takes: 43449ms
sparseView takes: 3478375ms
```

I'm not sure what the typical size of the problem this is targeting, but I thought you might find the info above useful.
</blockquote></details>

I set myself to blocking here to prevent accidental merging. but feel free to dismiss me on this one

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: 1 unresolved discussion

___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-NuykTLg82Td6xgSh23X:bh3s47x) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I set myself to blocking here to prevent accidental merging. but feel free to dismiss me on this one
</blockquote></details>

Wow I would not have expected that large of a difference. I think typically the size of `A` would be pretty small, but it doesn't need to be. Given that the improvement is negligible in the small regime, and the reduction in performance is large in the large matrix regime, maybe we stick with the triplets version? Hongkai I will defer to you here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: 1 unresolved discussion

___
*[`solvers/mosek_solver_internal.cc` line 1129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21274#-NupBE8w1UW9I5ny7er5:-NuytC4u0t9I9RhkP2--:bxcodp9) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d579299523a3e81acc12e25279e929d2ac897e8/solvers/mosek_solver_internal.cc#L1129)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Wow I would not have expected that large of a difference. I think typically the size of `A` would be pretty small, but it doesn't need to be. Given that the improvement is negligible in the small regime, and the reduction in performance is large in the large matrix regime, maybe we stick with the triplets version? Hongkai I will defer to you here.
</blockquote></details>

Done. Thanks Xuchen for checking this! I reverted to the previous A_triplets implementation.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21274)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform)

**Pull request merged**
