### PR TITLE
Add equality constraints in LQR.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327#-:-N3fTW32D3XTOBvLeJFK:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Sorry for being slow.  I've found a few small issues.  PTAL. 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327#-:-N42Yksq-DvEhSKiSi9z:bz8zdrl)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`systems/controllers/linear_quadratic_regulator.h` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42RfW0AhBR2R0u_5H-:-N42RfW0AhBR2R0u_5H0:by0b1gz) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.h#L20)):*
> ```objc
> ///
> ///   @f[ \dot{x} = Ax + Bu @f]
> ///   @f[ \min_u \int_0^\infty x'Qx + u'Ru + 2x'Nu dt @f]
> ```

nit: could we move the dynamic to underneath the objective, so that it's in the standard minimize _ subject to __ form?
___
*[`systems/controllers/linear_quadratic_regulator.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42S1hUB5y7X-w-jKxK:-N42S1hUB5y7X-w-jKxL:bbwlqey) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.h#L32)):*
> ```objc
> /// zero-sized, N will be treated as a num_states x num_inputs zero matrix.
> /// @param F A constraint matrix of size num_constraints x num_states. rank(F)
> /// must be < num_states. If the matrix is zero-sized, F will be treated as a 0
> ```

"if the matrix is zero-sized".  that's not quite the condition you check; because you check if rows != 0, then cols must == N.  if the user passes an 4 x 0 matrix, that would still be zero-sized, but will fail the DRAKE_DEMAND.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42TKcFAWXgm4yIcgdq:-N42TKcG0QoRXcbnpFX_:bks5zn9) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L44)):*
> ```cpp
>   if (R_cholesky.info() != Eigen::Success)
>     throw std::runtime_error("R must be positive definite");
>   // The rows of P are the basis for the null-space of F, namely PPᵀ = I and
> ```

nit: *orthonormal* basis.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42T02w0eSGrJGbLCLK:-N42T02w0eSGrJGbLCLL:b-fpeaf6) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L49)):*
> ```cpp
>   if (F.rows() != 0) {
>     // Compute the null-space based on QR decomposition. If Fᵀ*S = [Q1 Q2][R; 0]
>     // = Q1*R, then take P=Q2ᵀ, where S is the permutation matrix.
> ```

yikes.  Q, R, and S already have different meanings in this function, making this documentation pretty confusing.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42UaU6-23qxU5jUcvv:-N42UaU6-23qxU5jUcvw:b74w1ep) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L52)):*
> ```cpp
>     // We introduce projected state y, such that y = Px.
>     // We form a new dynamical system
>     // ẏ = PAPᵀx + PBu
> ```

the x should be y.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42VxLO8Ys9gPIuXFAE:-N42VxLO8Ys9gPIuXFAF:btzsk10) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L88)):*
> ```cpp
>       //   = -R⁻¹(BᵀS+NᵀPᵀP)
>       ret.K = R_cholesky.solve(B.transpose() * ret.S +
>                                N.transpose() * P->transpose() * (*P));
> ```

P^T * P is the identity; you shouldn't need that here?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`systems/controllers/linear_quadratic_regulator.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42S1hUB5y7X-w-jKxK:-N44womB5zD-wNvWDbo8:bt4ntm1) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.h#L32)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"if the matrix is zero-sized".  that's not quite the condition you check; because you check if rows != 0, then cols must == N.  if the user passes an 4 x 0 matrix, that would still be zero-sized, but will fail the DRAKE_DEMAND.
</blockquote></details>

Done. I also changed the documentation for `N` above. We also checked `DRAKE_DEMAND(N.cols() == m)`.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42T02w0eSGrJGbLCLK:-N44yhgG5BxGHwlOOUQT:bhi0v16) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L49)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

yikes.  Q, R, and S already have different meanings in this function, making this documentation pretty confusing.
</blockquote></details>

Done. Good call. I factored out the function to compute the kernel.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42UaU6-23qxU5jUcvv:-N44ys640TggeneSf6ME:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L52)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the x should be y.
</blockquote></details>

Done.
___
*[`systems/controllers/linear_quadratic_regulator.cc` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42VxLO8Ys9gPIuXFAE:-N44yt8E9uXkjdJmzqGs:b-tyyytz) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L88)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

P^T * P is the identity; you shouldn't need that here?
</blockquote></details>

I don't think P^T*P is identity, we have P * P^T being identity, but swapping the order of P and P^T won't give us identity matrix, unless they are both full-rank square matrices.

One example is P = [1/sqrt(2), 1/sqrt(2)], we can see that P * P^T = 1, but P^T * P = [0.5, 0.5; 0.5 0.5]

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327#-:-N46k4xJ2VwxE-BVsnHU:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`systems/controllers/linear_quadratic_regulator.cc` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42VxLO8Ys9gPIuXFAE:-N46jxzQ6g_I63rQ2O2f:b-pljd0n) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think P^T*P is identity, we have P * P^T being identity, but swapping the order of P and P^T won't give us identity matrix, unless they are both full-rank square matrices.

One example is P = [1/sqrt(2), 1/sqrt(2)], we can see that P * P^T = 1, but P^T * P = [0.5, 0.5; 0.5 0.5]
</blockquote></details>

My bad!  Retracted.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: plaform, with very small nits / BTWs. Nice!

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327#-:-N49H2MH1Sxs6KWHSAEG:byxmj5w)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`systems/controllers/linear_quadratic_regulator.h` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49BpPL-L4DY5TX5jHz:-N49BpPL-L4DY5TX5jI-:bxfail0) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/linear_quadratic_regulator.h#L21)):*
> ```objc
> ///   @f[ \min_u \int_0^\infty x'Qx + u'Ru + 2x'Nu dt @f]
> ///   @f[ \dot{x} = Ax + Bu @f]
> ///   @f[ Fx=0 @f]
> ```

nit Above code has a space between ` = `. Consider using that here.
___
*[`systems/controllers/linear_quadratic_regulator.h` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49BuH_Ern7ks-KJ5hJ:-N49BuH_Ern7ks-KJ5hK:bjewk0j) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/linear_quadratic_regulator.h#L32)):*
> ```objc
> /// 0, N will be treated as a num_states x num_inputs zero matrix.
> /// @param F A constraint matrix of size num_constraints x num_states. rank(F)
> /// must be < num_states. If the F.rows() == 0, F will be treated as a 0
> ```

BTW `the F.rows()` sounds a bit odd. Consider removing `the`
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49FNIW2CsqooSjLGBv:-N49FNIX9gntPpBFfCOs:bjkyiq2) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L18)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(TestLQR, TestException) {
> ```

BTW (pre-existing) For acronyms, style guide says to prefer `TestLqr` over `TestLQR`
https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GFx7CjBtKu0VqNww:-N49GFx82tAc_fPmbKmN:b767jl9) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L124)):*
> ```cpp
> // Test if the LQR solution satisfies the HJB equality
> // minᵤ xᵀQx + uᵀRu + 2xᵀNu + 2xᵀS(Ax+Bu) = 0
> void TestLQRwHJB(
> ```

nit Not the most readable name.

Consider expanding to `TestLQRwithHJB`, or following style guide for acroynyms, `TestLqrWithHjb`
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 134 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GUeR7kPLxUPGRQ4d:-N49GUeR7kPLxUPGRQ4e:b-4wr30y) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L134)):*
> ```cpp
>   const int nx = A.rows();
>   const int nu = B.cols();
>   // We first try to remove the constraint F*x=0 by considering a new slack
> ```

BTW Missing space around ` = ` (for consistency)
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GsIoBcAr9luUG8PC:-N49GsIoBcAr9luUG8PD:bbn7n6h) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L149)):*
> ```cpp
>     ASSERT_EQ(qr_F.info(), Eigen::Success);
>     const Eigen::MatrixXd F_Q = qr_F.matrixQ();
>     P = F_Q.rightCols(nx - qr_F.rank()).transpose();
> ```

BTW Consider exposing `ComputerKernel` in `internal`, which you could then re-use here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`systems/controllers/linear_quadratic_regulator.cc` line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N42VxLO8Ys9gPIuXFAE:-N49IBQG9uA_-nHhspCh:b-amivfj) ([raw file](https://github.com/robotlocomotion/drake/blob/27dc4ce3d5582a691204fae2ffec2f28225020a1/systems/controllers/linear_quadratic_regulator.cc#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I added some documentation to explain it here.
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49FNIW2CsqooSjLGBv:-N49IYWG-XcZNt7a9Cp-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW (pre-existing) For acronyms, style guide says to prefer `TestLqr` over `TestLQR`
https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 124 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GFx7CjBtKu0VqNww:-N49IgHO3nM13Go03A5V:b-89qv3t) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L124)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not the most readable name.

Consider expanding to `TestLQRwithHJB`, or following style guide for acroynyms, `TestLqrWithHjb`
</blockquote></details>

DOne.
___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GsIoBcAr9luUG8PC:-N49ZGBm33XloojUq4w7:b-qvf37s) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L149)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Consider exposing `ComputerKernel` in `internal`, which you could then re-use here.
</blockquote></details>

For the moment I am hesitant to expose this function. The reason is that there are many approaches to compute the kernels, and here I use QR decomposition with column pivoting. One can also try other rank-revealing decomposition to compute the kernel. I put a TODO here to expose this function in the future. Would this be good?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17327)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[`systems/controllers/test/linear_quadratic_regulator_test.cc` line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17327#-N49GsIoBcAr9luUG8PC:-N49hmeYCsHAQah2E5tK:b-ni7uid) ([raw file](https://github.com/robotlocomotion/drake/blob/65efef898b21cc6782ce778f6af53417559f0afa/systems/controllers/test/linear_quadratic_regulator_test.cc#L149)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For the moment I am hesitant to expose this function. The reason is that there are many approaches to compute the kernels, and here I use QR decomposition with column pivoting. One can also try other rank-revealing decomposition to compute the kernel. I put a TODO here to expose this function in the future. Would this be good?
</blockquote></details>

OK Yup, works for me!

**Pull request merged**
