### PR TITLE
[input_port] Add Allocate() method

### LINKED ISSUE #13581: framework: Add (and bind) InputPort.Allocate()?
See Drake Slack thread:
https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590265311047200?thread_ts=1590184382.046300&cid=C2CHRT98E

@sherm1 Assigning you for now; feel free to delegate!

---

> [eric.cousineau](https://app.slack.com/team/U4PJQLBGR) [May 22nd at 5:53 PM](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590184382046300)
> 
> Dumb question: Is it all possible to ask an Input port value for its model value?
> Asking for a friend who's, uh, programming in Python 
> 
> 5 replies
> 
> [eric.cousineau](https://app.slack.com/team/U4PJQLBGR) [1 month ago](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590184478046400?thread_ts=1590184382.046300&cid=C2CHRT98E)
> 
> To expand, I know that we have  `OutputPort::Allocate()` , which I can use as a way to discover the type / get something to feed to the next port. Wondering if there's something similar for input ports, I believe the  `typeid`  is at least recorded?
> 
> [sherm1](https://app.slack.com/team/U272XV5NU) [1 month ago](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590186534046600?thread_ts=1590184382.046300&cid=C2CHRT98E)
> 
> Hard to find, but I think what you want is [System::AllocateInputVector()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#a6c7d64d658e5fb67234d9ffc918155bd) and
> [System::AllocateInputAbstract(](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#a3a50463e995d1d3e414ade7051c3458a)).
> 
> [eric.cousineau](https://app.slack.com/team/U4PJQLBGR) [1 month ago](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590191139046800?thread_ts=1590184382.046300&cid=C2CHRT98E)
> 
> Ahh, sweet - thanks!
> 
> [eric.cousineau](https://app.slack.com/team/U4PJQLBGR) [1 month ago](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590191203047000?thread_ts=1590184382.046300&cid=C2CHRT98E)
> 
> Random Q: Is there a reason why we have both  `*Vector`  and  `Abstract`  flavors? The  `OutputPort`  flavor always outputs abstract, which could be  `Value<BasicVector<T>>`
> 
> [sherm1](https://app.slack.com/team/U272XV5NU) [29 days ago](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1590265311047200?thread_ts=1590184382.046300&cid=C2CHRT98E)
> 
> I think there might be some ancient history involved. I'm not sure exactly how this  *should*  look, but I think at least it should be something you ask an input port for, rather than a System. Would be great to have an issue for this if you can describe the inconsistency (and cure, if it is obvious) -- I think you are the first person to notice it.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #13581

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[`systems/framework/system.cc` line 1327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NIyh_jOAR1OxDTiKkys:-NIyh_jOAR1OxDTiKkyt:bworhcc) ([raw file](https://github.com/robotlocomotion/drake/blob/fb41c234274a46edcf34e849593f2cb04325d930/systems/framework/system.cc#L1327)):*
> ```cpp
> }
> 
> // Blech.
> ```

@sherm1 @rpoyner-tri Do y'all know how to force an definition on a class method that's already `extern template`?

I *feel* like there's a way to do it, but this clearly ain't it.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[`systems/framework/system.cc` line 1327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NIyh_jOAR1OxDTiKkys:-NIyhnO02HwqCcBQgyqZ:b-g8p8ve) ([raw file](https://github.com/robotlocomotion/drake/blob/fb41c234274a46edcf34e849593f2cb04325d930/systems/framework/system.cc#L1327)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@sherm1 @rpoyner-tri Do y'all know how to force an definition on a class method that's already `extern template`?

I *feel* like there's a way to do it, but this clearly ain't it.
</blockquote></details>

This has to be done b/c `System<T>` is incomplete as seen by the translation unit as part of `:input_port` 

Alternative is to just lump the bazel targets together :shrug:

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431)* status: needs at least two assigned reviewers (waiting on @sherm1)

___
*[`systems/framework/input_port.h` line 166 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ6QaDF4yooV37gbOie:-NJ6teia-MLE0yOPePez:b-bpvvj3) ([raw file](https://github.com/robotlocomotion/drake/blob/3217fa2e2464ea1d92ab0a3101113dd7e08678a0/systems/framework/input_port.h#L166)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this seems slightly contorted. System has a private DoAllocateInput() virtual that always returns the input port object as an AbstractValue. Then AllocateInputVector() extracts the BasicVector, which you are then putting back into an AbstractValue. I _think_ you could just call AllocateInputAbstract() unconditionally here. Wouldn't that do what you want?
</blockquote></details>

Done. Much nicer!

I'm still a bit sad at the weird and arbitrary mixed distinctions between abstract value and vectors, and would love to know when that may creep into the dynamics team's improvement list. (I don't think I'd have sufficient time to tackle it, but would be more than up to describe my thoughts.)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for platform review, please!
(added bindings in the commit msg, if that works!)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431#-:-NJ6uDXt7EpGnKugUvo9:bo4ldf6)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`systems/framework/input_port.h` line 166 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ6QaDF4yooV37gbOie:-NJ77PnG25sg07J2qzOm:bsxiloz) ([raw file](https://github.com/robotlocomotion/drake/blob/3217fa2e2464ea1d92ab0a3101113dd7e08678a0/systems/framework/input_port.h#L166)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Much nicer!

I'm still a bit sad at the weird and arbitrary mixed distinctions between abstract value and vectors, and would love to know when that may creep into the dynamics team's improvement list. (I don't think I'd have sufficient time to tackle it, but would be more than up to describe my thoughts.)
</blockquote></details>

Agreed. I believe that's an artifact of our inability to transmogrify AbstractValue objects. By keeping the numeric vectors distinct we can scalar convert them. Would have been better I think to teach AV's how to make a best-effort transmogrification.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Two tiny nits.

Thanks for calling out the bindings. But...

One last confusing thoughts on the bindings. Unless my memory has betrayed me, I *believe* that the only time we enumerate the bindings is if they get added in a different release than the actual C++ feature gets introduced. The baseline is supposed to be a new feature is added with its bindings. Only if we come along later to shore up missing bindings do they get called out. I *may* be wrong, but that's my freshest understanding.

> Reviewed 1 of 3 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431#-:-NJ7CF5hBxWXEmRVXZA_:bgbipis)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`systems/framework/BUILD.bazel` line 462 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7C5zYEHD49O_g9wuo:-NJ7C5zYEHD49O_g9wup:bdqr9wk) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/BUILD.bazel#L462)):*
> ```Starlark
>     srcs = [
>         # See note above in `:input_port`.
>         "input_port.cc",
> ```

BTW I guarantee this'll cause confusion and consternation through the ages. But I'm ok with it.
___
*[`systems/framework/input_port.h` line 160 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7ARm1B4qHB1FMGaew:-NJ7ARm1B4qHB1FMGaex:b-6i1nrx) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/input_port.h#L160)):*
> ```objc
>   }
> 
>   /** Allocates a abstract value in the same fashion as OutputPort::Allocate().
> ```

nit s/a/an
___
*[`systems/framework/test/input_port_test.cc` line 355 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7BHBbALikNm_Z2094:-NJ7BHBbALikNm_Z2095:b-cp4ii7) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/test/input_port_test.cc#L355)):*
> ```cpp
> GTEST_TEST(InputPortTest, Allocate) {
>   SystemWithInputPorts system;
>   // Check allocate.
> ```

BTW The test is called `Allocate` and then we have the comment `Check allocate` twice. A bit redundant.

I'm sure what was intended is that *this* comment was supposed to be:
`// Vector-valued input-port.` and the next would be `// Abstract-valued input-port.`

**Review by EricCousineau-TRI — COMMENTED** [review]
Aye, SGTM. Removed from commit msg.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18431#-:-NJ7FHmVCdVcAToFRsfW:b7np7ob)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`systems/framework/BUILD.bazel` line 462 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7C5zYEHD49O_g9wuo:-NJ7EtFiD0ChnHichl06:b1vdy3o) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/BUILD.bazel#L462)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I guarantee this'll cause confusion and consternation through the ages. But I'm ok with it.
</blockquote></details>

OK Agreed as someone who was initially confused by initial layout.
Maybe it'd be good to ultimately lump things together that are truly interdependent / do less coupled setup, but I wanted to keep this PR change small (w/ minimum effort to properly check my box ;), hence commenting for traceability.
___
*[`systems/framework/input_port.h` line 160 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7ARm1B4qHB1FMGaew:-NJ7Eq0340jie2_CqKx4:bbtz4e3) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/input_port.h#L160)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit s/a/an
</blockquote></details>

Done. Gave me an excuse to add line break as well ;)
___
*[`systems/framework/test/input_port_test.cc` line 355 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18431#-NJ7BHBbALikNm_Z2094:-NJ7Eof1Dma9t6CtMAM6:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/524e0f0afb78ceeba850035bc7a1f791b54996ad/systems/framework/test/input_port_test.cc#L355)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The test is called `Allocate` and then we have the comment `Check allocate` twice. A bit redundant.

I'm sure what was intended is that *this* comment was supposed to be:
`// Vector-valued input-port.` and the next would be `// Abstract-valued input-port.`
</blockquote></details>

Done, thanks!

**Comment by jwnimmer-tri** [comment]
This totally hosed up the physical dependency design of System vs Port.  It broke the `:input_port` target and violates our style and custom.  I'll see if I can rework it in a follow-up to unbreak the BUILD file.

**Pull request merged**
