### PR TITLE
[build] Fully retire the non-lcmtypes drake module

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20731.  See #21453 for prior art.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please (low priority).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODIWQy7BAEh23RTbIEe:-ODIWQy8-5DcoU372o7U:b-7tt62v) (no related file):*
Working

Ugh, this breaks certain particular kinds of downstream projects (e..g, one of the drake-external-examples).  I will need to rework this a little bit.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODIWQy7BAEh23RTbIEe:-ODI_NKM0PIERb9gPiWO:b-m9zt9i) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Ugh, this breaks certain particular kinds of downstream projects (e..g, one of the drake-external-examples).  I will need to rework this a little bit.
</blockquote></details>

OK fixed now, by reverting ~20% of it with some new comments.

Tested via:
```
cd drake-external-examples/drake_bazel_external
env EXAMPLES_LOCAL_DRAKE_PATH=/path/to/drake bazel test //...
```

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a big picture question.

> Reviewed 4 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-:-ODJNGno58IQvmjP4s8U:b-8x3p9g)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODJJMHo-8bTuFUiJRq6:-ODJJMHo-8bTuFUiJRq7:b61dsxr):*
Could you say why (perhaps in reviewable and not necessarily in the commit message).
I have a vague sense that this has something to do with lowered visibility of the packages? but I don't fully get it.



_Code quote:_
```
With bzlmod this is no longer practical.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODJJMHo-8bTuFUiJRq6:-ODJOzHr5nKhjMJ5OEDz:b-ouvp2m):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could you say why (perhaps in reviewable and not necessarily in the commit message).
I have a vague sense that this has something to do with lowered visibility of the packages? but I don't fully get it.
</blockquote></details>

Previously, when the developer's WORKSPACE had the line `workspace(name = "foo")` the Python `sys.path` provided by `rules_python` would be organized to provide package names like `from foo.common import thing`.

Later, Bazel people decided this was a Really Bad Move and the paths should have been `from common import thing`.  This is important because "name of an external" with bzlmod is more complicated now -- globally there can be multiple copies of an external, so "my copy of foo" is now a local concept, rather than part of a (necessarily global) sys.path.

This is also more consistent with non-Bazelized Python, where the parent of the directory you cloned the git repository into is never on your sys.path.  Take for instance https://github.com/urllib3/urllib3, it has a subdir named `src` which is (notionally) on the sys.path, and then inside of `src` there is a directory named `urllib3` with a file `__init__.py`, so users would do `from urllib import ...`.  In other words, for anything spelled as `from xyz import ...` there should be a directory in source control named `xyz`; the git repository's name to clone doesn't count, since that is not actually a constant (the user can name it anything they want).  So that's how Python in the wider universe works, this is just bringing rules_python up to speed to match that.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.

**Comment by xuchenhan-tri** [comment]
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODJJMHo-8bTuFUiJRq6:-ODKP9iz4GHHDAkwxojY:b-92gzkp):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Previously, when the developer's WORKSPACE had the line `workspace(name = "foo")` the Python `sys.path` provided by `rules_python` would be organized to provide package names like `from foo.common import thing`.

Later, Bazel people decided this was a Really Bad Move and the paths should have been `from common import thing`.  This is important because "name of an external" with bzlmod is more complicated now -- globally there can be multiple copies of an external, so "my copy of foo" is now a local concept, rather than part of a (necessarily global) sys.path.

This is also more consistent with non-Bazelized Python, where the parent of the directory you cloned the git repository into is never on your sys.path.  Take for instance https://github.com/urllib3/urllib3, it has a subdir named `src` which is (notionally) on the sys.path, and then inside of `src` there is a directory named `urllib3` with a file `__init__.py`, so users would do `from urllib import ...`.  In other words, for anything spelled as `from xyz import ...` there should be a directory in source control named `xyz`; the git repository's name to clone doesn't count, since that is not actually a constant (the user can name it anything they want).  So that's how Python in the wider universe works, this is just bringing rules_python up to speed to match that.
</blockquote></details>

Thanks for the explanation. It helps somewhat but not completely. Do you happen to have some reference on this from bzlmod that you can share?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODJJMHo-8bTuFUiJRq6:-ODMIFoM6ATM-psGwshC:b8g2iba):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Thanks for the explanation. It helps somewhat but not completely. Do you happen to have some reference on this from bzlmod that you can share?
</blockquote></details>

Maybe these help:
https://github.com/bazelbuild/rules_python/issues/1679
https://github.com/bazelbuild/bazel/issues/18128

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 4 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-:-ODMLG9QD71PIqw4DiwK:bmxilld)* status: 2 unresolved discussions

___
*[`__init__.py` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODMJVqU1ZML0C6NC9NI:-ODMJVqV6sQMQNv-Adfy:b-kzqyel) ([raw file](https://github.com/RobotLocomotion/drake/blob/823f4aa00da46f62aed0b9110ad1e67d7250e1d5/__init__.py#L1)):*
> ```Python
> # It brittle to have both drake-the-workspace and drake-the-lcmtypes-package
> ```

nit: grammar

(If you've ever seen the movie, "Murder By Death", you should be able to imagine [Truman Capote shouting this](https://youtu.be/m4UD-J06OHc?si=HE_7MN_-Nx8Qw3sK&t=174).)



_Suggestion:_
```Python
It is brittle
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: 1 unresolved discussion

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22265)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22265#-ODJJMHo-8bTuFUiJRq6:-ODMZ_sICizMoxSWhYQU:b-4vayn6):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe these help:
https://github.com/bazelbuild/rules_python/issues/1679
https://github.com/bazelbuild/bazel/issues/18128
</blockquote></details>

Happy to keep chatting, but for now I'll merge this to keep the train going.

**Pull request merged**
