### PR TITLE
quadrotor: Upgrade to Skydio R2 model

### PR DESCRIPTION
**Pull request by RussTedrake**
provided by @abachrach from [Skydio](https://www.skydio.com/).  Thanks Abe!
also cleans up a little cruft (old files/tags that we haven't parsed since the matlab days)

EDIT (eric): Updated preview:

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13050)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@abachrach for feature review, perhaps?
+@EricCousineau-TRI for platform review, please?
(reviewable seems to be down, so I can't assign through there right now)

**Comment by jwnimmer-tri** [comment]
100KiB is [the limit](https://drake.mit.edu/model_version_control.html) for putting objs in git.  The new obj should go into https://github.com/RobotLocomotion/models/.

**Comment by EricCousineau-TRI** [comment]
Let me know if you would like help in migrating this to `models`.

**Comment by abachrach** [comment]
That's a good lookin drone! ;-)

lgtm

**Comment by gizatt** [comment]
I suspect that this might be a meshcat (javascript side) bug being exposed by the relatively complicated model. Do you see a javascript error in the console in your meshcat window? (F12 -> console tab, at least on chrome)

**Comment by gizatt** [comment]
[This PR to meshcat](https://github.com/rdeits/meshcat/pull/69) fixes this, I'm pretty sure (from some testing on my machine). Though, the MTL textures won't load in meshcat anyway until meshcat-python gets upgraded to support them. I don't think the problem is within Drake or this PR and it probably doesn't need to hold this up?

**Comment by RussTedrake** [comment]
Thanks @gizatt !  The reason I want to wait on the meshcat is because I don't want to break the students who are using the quadrotor for their class projects.

**Comment by EricCousineau-TRI** [comment]
For extra xref fun: Related `meshcat` PR is: https://github.com/rdeits/meshcat/pull/69

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/meshcat/repository.bzl, line 12 at r5](https://reviewable.io/reviews/robotlocomotion/drake/13050#-M5n6Mle7fpEGuwK8hDo:-M5nAJlGDxni_ruwrFTq:b7pi6qc) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1ab625d84e3d53c4fe0ed417f34aacf935f3ff/tools/workspace/meshcat/repository.bzl#L12)):*
Huh... Chrome works, but there's no color:
> 

Firefox still doesn't show up.
If I inspect `./bazel-bin`, `main.min.js` doesn't have an indication of the error string, so I wonder if it's a dumb caching issue on Firefox :(

**Comment by rdeits** [comment]
Try ctrl+shift+R to force an actual refresh? Otherwise your browser may be "helpully" caching things.

**Comment by EricCousineau-TRI** [comment]
Yup, that did it, thanks! FTR I've filed https://github.com/rdeits/meshcat/issues/70, just to see if there's a way to tell the local server for `meshcat-python` to not cache the files. (Not sure if it applies to other `meshcat` clients, so I can move it to `meshcat-python` if that helps.)

**Comment by EricCousineau-TRI** [comment]
> Chrome for me.

Aye, will update the upstream issue.

**Comment by rdeits** [comment]
Would you all mind confirming that this works with meshcat-python `master`? If so, I'll tag a new release too.

**Comment by EricCousineau-TRI** [comment]
Testing it out here: https://github.com/RobotLocomotion/drake/pull/13155

**Pull request merged**
