### PR TITLE
GetSolution works for variables

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8541)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-:-L9ai5_T8JOV8iajAY7C:bpno49v)*

**Comment by soonho-tri** [comment]
:lgtm:

+(status: curate commits before merging) 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-:-L9dVthE8GnCzwxeBWLy:b-r28rwp)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for platform-review, please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[solvers/mathematical_program.h, line 2464 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9dsz6m7x81eiDZGOOP:-L9dsz6m7x81eiDZGOOQ:bps2wtl) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.h#L2464)):*
> ```objc
> 
>   /**
>    * Return a vector containing the solution to each variable in @p variables.
> ```

BTW, nit, `Return` -> `Returns`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-:-L9dsv_X8NbbjrW_sdqz:b4fwciw)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.h, line 2466 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eV2vRCORiwxbIJjJg:-L9eV2vRCORiwxbIJjJh:b-he703p) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.h#L2466)):*
> ```objc
>    * Return a vector containing the solution to each variable in @p variables.
>    * The order of the solution is the same as the corresponding variable in
>    * @p variables.
> ```

Why use `Variables`?  Its like a set, not a vector.  Yes its ordering is deterministic, but is also unrelated to the order the user inserted them.  Doing `mp.GetSolution({c, b, a})` will _not_ return values in the order `c, b, a` -- it will return them in whatever order the Variable names were declared in.  Wouldn't an array-like (vector-like) parameter make more sense?

---

*[solvers/mathematical_program.cc, line 802 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eVeaS97rBE8Ia-eRb:-L9eVeaS97rBE8Ia-eRc:b-5vvitn) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.cc#L802)):*
> ```cpp
>   Eigen::VectorXd values(variables.size());
>   int count = 0;
>   for (auto it = variables.begin(); it != variables.end(); ++it) {
> ```

BTW Prefer range-for instead of raw iterators.

---

*[solvers/test/mathematical_program_test.cc, line 640 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eVpnr6u7qUf8AYVBi:-L9eVpnr6u7qUf8AYVBj:b8llzwl) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/test/mathematical_program_test.cc#L640)):*
> ```cpp
>     EXPECT_EQ(variables_value.rows(), 3);
>     int variable_count = 0;
>     for (auto it = variables.begin(); it != variables.end(); ++it) {
> ```

BTW Prefer range-for.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2466 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eV2vRCORiwxbIJjJg:-L9f0Rwt9TbzjRe0ki0I:b-3tx3zp) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.h#L2466)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why use `Variables`?  Its like a set, not a vector.  Yes its ordering is deterministic, but is also unrelated to the order the user inserted them.  Doing `mp.GetSolution({c, b, a})` will _not_ return values in the order `c, b, a` -- it will return them in whatever order the Variable names were declared in.  Wouldn't an array-like (vector-like) parameter make more sense?
</blockquote></details>

That's a very good point. The PR was requested by @tobiamarcucci , to retrieve the solution to coefficients (stored as `symbolic::Variables`) in a polynomial. Now thinking more carefully about it, I think I should return `symbolic::Polynomial` or `symbolic::Expression` directly, then the user does not need to worry about the order of the element in `symbolic::Variables`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2464 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9dsz6m7x81eiDZGOOP:-L9gNc9f93iohJCMnzPk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.h#L2464)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, `Return` -> `Returns`.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.cc, line 802 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eVeaS97rBE8Ia-eRb:-L9gNXzu9jBxbuXkMkTj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/mathematical_program.cc#L802)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Prefer range-for instead of raw iterators.
</blockquote></details>

Done.

---

*[solvers/test/mathematical_program_test.cc, line 640 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9eVpnr6u7qUf8AYVBi:-L9gN_TP5HDxw8ODJxl3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e3ebdcfe1e584d8076702d643140b9e226a7cff/solvers/test/mathematical_program_test.cc#L640)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Prefer range-for.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[solvers/mathematical_program.h, line 2467 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gkFPaB29O_WFH1uZ3:-L9gkFPaB29O_WFH1uZ4:b-t8sr8m) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2467)):*
> ```objc
>    * variables, returns the expression after substitution.
>    * @throw runtime error if some variables in the expression @e are NOT
>    * variables in the optimization program.
> ```

Does this mean that all the expression will always resolve to a constant?  Or are there some non-decision variables or something?  The unit test seems to have more detail than has been explained in this comment.

Perhaps writing up an example use, in the API documentation here, would help clarify?

(Ditty below for Polynomial.)

---

*[solvers/mathematical_program.h, line 2469 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gjxb55KnC3F4AzQhp:-L9gjxb55KnC3F4AzQhq:b45gi6y) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2469)):*
> ```objc
>    * variables in the optimization program.
>    */
>   symbolic::Expression GetSolution(const symbolic::Expression& e) const;
> ```

FYI Would renaming to `SubstituteSolution` or `SubstituteSolutionInto` be more clear?

(Ditty below for Polynomial.)

---

*[solvers/mathematical_program.cc, line 812 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gkndcD9LLASORyuQB:-L9gkndcD9LLASORyuQC:bdz8ymn) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.cc#L812)):*
> ```cpp
> 
> symbolic::Expression MathematicalProgram::GetSolution(
>     const symbolic::Expression& p) const {
> ```

BTW `e` (not `p`), to match the header.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2466 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9jqZudDlnWVUOFZhkg:-L9jqZudDlnWVUOFZhkh:b-idalwb) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2466)):*
> ```objc
>    * Replaces the variables in an expression with the solutions to the
>    * variables, returns the expression after substitution.
>    * @throw runtime error if some variables in the expression @e are NOT
> ```

BTW, `@e` -> `@p e`.

---

*[solvers/mathematical_program.h, line 2474 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9jqmRK5k0jloPU-M1C:-L9jqmRK5k0jloPU-M1D:b-ppf2d) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2474)):*
> ```objc
>    * Replaces the decision variables in a polynomial with the solutions to the
>    * variables, returns the polynomial after substitution.
>    * @throw runtime error if some decision variables in the polynomial @p are
> ```

BTW, `@p` -> `@p p`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2466 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9jqZudDlnWVUOFZhkg:-L9lDvme145qNiCbQebZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2466)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `@e` -> `@p e`.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2467 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gkFPaB29O_WFH1uZ3:-L9lDyHFBQEIKH9RpqDI:bgv9efk) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2467)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does this mean that all the expression will always resolve to a constant?  Or are there some non-decision variables or something?  The unit test seems to have more detail than has been explained in this comment.

Perhaps writing up an example use, in the API documentation here, would help clarify?

(Ditty below for Polynomial.)
</blockquote></details>

Good catch. If an expression contains a variable that is an indeterminate in the optimization program, then it will not be replaced by a double.

---

*[solvers/mathematical_program.h, line 2469 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gjxb55KnC3F4AzQhp:-L9lEnRREDg1_VEpqIke:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2469)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Would renaming to `SubstituteSolution` or `SubstituteSolutionInto` be more clear?

(Ditty below for Polynomial.)
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2474 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9jqmRK5k0jloPU-M1C:-L9lG0bZDI1OnM8vyxvw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.h#L2474)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `@p` -> `@p p`.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.cc, line 812 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-L9gkndcD9LLASORyuQB:-L9lG1uPAXLzcM74IB6o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/174d2059228c6133fd4f1cf32151ed4438fc0620/solvers/mathematical_program.cc#L812)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `e` (not `p`), to match the header.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541#-:-L9lUe3s-5YvYD44ov5a:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8541)*

**Pull request merged**
