### PR TITLE
add a initial tree option to world sim tree builder.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9048)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai for feature review. 
cc @andreas-tenpas-tri 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9048#-:-LFdDUBOAho7QucBSKxl:b-3hdwmj)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Reviewed 3 of 3 files at r1.
Review status: 1 unresolved discussion, platform LGTM missing

---

*[manipulation/util/world_sim_tree_builder.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdG96y2v60pxxy6QCx:-LFdG96y2v60pxxy6QCy:bizxj5n) ([raw file](https://github.com/robotlocomotion/drake/blob/5dbb519a45e8b3f50329aa6d456ccf325939ce19/manipulation/util/world_sim_tree_builder.h#L52)):*
> ```objc
>   ///
>   /// @param compile_tree Specifies whether the tree should be automatically
>   /// compiled. Defaults to true.
> ```

Add the documentation for `base_tree`?

---

*[manipulation/util/test/sim_diagram_builder_test.cc, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdH_80CUyYSe-OGFEp:-LFdH_80CUyYSe-OGFEq:b6vrepb) ([raw file](https://github.com/robotlocomotion/drake/blob/5dbb519a45e8b3f50329aa6d456ccf325939ce19/manipulation/util/test/sim_diagram_builder_test.cc#L88)):*
> ```cpp
>   // Add a second arm
>   Isometry3<double> expected_pose = Isometry3<double>::Identity();
>   expected_pose.translation()[0] = 233;
> ```

Second time to see `233` in this code. This is a magic number to people who do not play with Mop.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9048#-:-LFdHyjiBbTDc1qsHiTS:bozh2sc)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing

---

*[manipulation/util/world_sim_tree_builder.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdG96y2v60pxxy6QCx:-LFdIwk0CoV-iRIdZmkv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5dbb519a45e8b3f50329aa6d456ccf325939ce19/manipulation/util/world_sim_tree_builder.h#L52)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add the documentation for `base_tree`?
</blockquote></details>

Done.

---

*[manipulation/util/test/sim_diagram_builder_test.cc, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdH_80CUyYSe-OGFEp:-LFdJ1-AEysQl2pGplsG:b-yvszkp) ([raw file](https://github.com/robotlocomotion/drake/blob/5dbb519a45e8b3f50329aa6d456ccf325939ce19/manipulation/util/test/sim_diagram_builder_test.cc#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Second time to see `233` in this code. This is a magic number to people who do not play with Mop.
</blockquote></details>

just magic numbers :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9048)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few minor comments.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: 2 unresolved discussions, platform LGTM from [sherm1]

---

*[manipulation/util/test/sim_diagram_builder_test.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdKertEJ8hiq4iSHLg:-LFdKeruBv6AmFJ22FZa:beq00w0) ([raw file](https://github.com/robotlocomotion/drake/blob/3707b1c5d517762f08b30c6bdd4fddc63f358717/manipulation/util/test/sim_diagram_builder_test.cc#L67)):*
> ```cpp
>   EXPECT_THROW(
>       tree_builder->AddFixedModelInstance("233", Vector3<double>::Zero()),
>       std::exception);
> ```

BTW consider using DRAKE_EXPECT_THROWS_MESSAGE() to check that the right message is being thrown rather than just _some_ message (optional, but easy and makes for a better test).

---

*[manipulation/util/test/sim_diagram_builder_test.cc, line 90 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9048#-LFdLDMY9shYUnlj4o4b:-LFdLDMY9shYUnlj4o4c:b-eguxmu) ([raw file](https://github.com/robotlocomotion/drake/blob/3707b1c5d517762f08b30c6bdd4fddc63f358717/manipulation/util/test/sim_diagram_builder_test.cc#L90)):*
> ```cpp
>   Isometry3<double> expected_pose = Isometry3<double>::Identity();
>   expected_pose.translation()[0] = 233;
>   int id = tree_builder->AddFixedModelInstance("second_iiwa",
> ```

Nit: type should be ModelInstanceIndex instead of int.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9048#-:-LFdLkbLD1zTsbvbDpnC:bty5hbu)*

**Pull request merged**
