### PR TITLE
Add --non-realtime to many test programs.

### LINKED ISSUE #2024: No test should demand to run with realtime performance by default
By default, no test should run in realtime by when invoked by CTest -- the developer's computer may not be very fast (may be virtualized), and/or CI may not be very fast.

In #1920, we fixed this for one test, but there are least several more:
 - [ ] examples/Pendulum/runDynamics.cpp:33:  options.realtime_factor = 1.0;
 - [ ] examples/Pendulum/runEnergyShaping.cpp:36:    options.realtime_factor = 1.0;
 - [ ] examples/Pendulum/runLQR.cpp:35:  options.realtime_factor = 1.0;
 - [ ] examples/Quadrotor/runLQR.cpp:42:  options.realtime_factor = 1.0;

Once I figure out better things to grep for, I may find more examples.

Given the extent of the problem, the solution in #1920 likely should be factored out into a helper, rather than copy-pasted everywhere.

Example failure under OS X CI:
https://drake-jenkins.csail.mit.edu/job/experimental/681/compiler=clang,label=mac/

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This closes #2024.

It was impractical to factor this better, since SimulationOptions is not accessible to any the util/ helpers.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@liangfok PTAL?

**Comment by liangfok** [comment]
LGTM

**Comment by david-german-tri** [comment]
LGTM, but we should wait for the Jenkins result.  Appreciate the forward compatibility with gflags.

**Comment by david-german-tri** [comment]
@jamiesnape Interesting failure on clang-mac here:

https://drake-jenkins.csail.mit.edu/job/experimental/695/compiler=clang,label=mac/consoleText

```
Caused by: hudson.plugins.git.GitException: Command "git checkout -f d5618cfdf811d07fe372ffbd9b4ba3b1428aa9ff" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: d5618cfdf811d07fe372ffbd9b4ba3b1428aa9ff
``` 
Named commit is here: https://github.com/RobotLocomotion/drake/commit/d5618cfdf811d07fe372ffbd9b4ba3b1428aa9ff

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by jamiesnape** [comment]
It means either the head of the PR or the head of master changed between the build being requested and it occurring, e.g., because of a amended commit and force push on the PR or a merge into master. Therefore, the commit no longer exists.

**Comment by jwnimmer-tri** [comment]
Thinking about it now, I should probably also tweak the changelog as part of this PR.
But I'll wait until these builders finish before messing with anything.

**Comment by jwnimmer-tri** [comment]
The 991fcad build had some weird errors.  I pushed the changelog patch, and will wait to see what the retest says.

**Pull request merged**
