### PR TITLE
Moves lane into abstract state of MaliputRailcar and adds lane direction.

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards enabling `MaliputRailcar` to traverse `Lane` boundaries.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5497)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please.
+@jwnimmer-tri for car review please.
I'll assign a platform reviewer once this PR passes feature review.
Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-:-KfH3c1k3Ef45NIsNBis:buwjdl6)*

**Comment by jwnimmer-tri** [comment]
:car:

---

Reviewed 2 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHNHSfEJ3T8T8YRqo0:-KfHNHSfEJ3T8T8YRqo1:bsud8lv) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L53)):*
> ```cpp
>     : start_time_(start_time),
>       initial_lane_direction_(initial_lane_direction.lane,
>                               initial_lane_direction.with_s) {
> ```

BTW Why copy itemwise?  Use the copy constructor?

---

*[drake/automotive/maliput_railcar.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHMnxFxCZfPOPOW3wz:-KfHMnxGRrretgOVWF-p:b-3srdj9) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L59)):*
> ```cpp
>       this->DeclareVectorOutputPort(MaliputRailcarState<T>()).get_index();
>   lane_state_output_port_index_ =
>       this->DeclareAbstractOutputPort().get_index();
> ```

Prefer the model-based declaration (pass a `Value<>`) as an argument, and then don't override `AllocateAbstractOutput`.

I think in that case the `initial..._` member field can go away, because its save in the model value.

---

*[drake/automotive/maliput_railcar.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHQ4fpjTf4YbAm2geD:-KfHQ4fpjTf4YbAm2geE:bxza7pv) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L141)):*
> ```cpp
>     LaneDirection* output) const {
>   output->lane = lane_direction.lane;
>   output->with_s = lane_direction.with_s;
> ```

BTW Why not use the copy-assignment operator?

---

*[drake/automotive/maliput_railcar.cc, line 302 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHQRc4N6Em5NTt8Pv1:-KfHQRc4N6Em5NTt8Pv2:b1ycmte) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L302)):*
> ```cpp
>           template GetMutableValue<LaneDirection>();
>   lane_direction.lane = initial_lane_direction_.lane;
>   lane_direction.with_s = initial_lane_direction_.with_s;
> ```

BTW Why not use copy-assignment operator?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-:-KfHQ_sXl2XYJaooPXVJ:b-8ewamd)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHNHSfEJ3T8T8YRqo0:-KfHzNNj2IA8bueIcBJw:b-njaqjo) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why copy itemwise?  Use the copy constructor?
</blockquote></details>

Done. I need to recondition myself to stop thinking all copy constructors are deleted in Drake.

---

*[drake/automotive/maliput_railcar.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHMnxFxCZfPOPOW3wz:-KfI1vJHOlAu_xmURCFq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Prefer the model-based declaration (pass a `Value<>`) as an argument, and then don't override `AllocateAbstractOutput`.

I think in that case the `initial..._` member field can go away, because its save in the model value.
</blockquote></details>

Done.

---

*[drake/automotive/maliput_railcar.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHQ4fpjTf4YbAm2geD:-KfI-zUsiXmS8aA6ZnEL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why not use the copy-assignment operator?
</blockquote></details>

Done.

---

*[drake/automotive/maliput_railcar.cc, line 302 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfHQRc4N6Em5NTt8Pv1:-KfI05FM8a9n7GsdW53y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5348727674e28bc86ee6513b53bcdf57418cda4/drake/automotive/maliput_railcar.cc#L302)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why not use copy-assignment operator?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497)*

**Comment by liangfok** [comment]
Thanks. +@sammy-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 210 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfIbxHj9JpdPtJH5Ioz:-KfIeX8SddLBzfLrAM-K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ef6e211988f5856288be907289677685205a40/drake/automotive/maliput_railcar.cc#L210)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, since this operating on variables of type `T`, consider using `cond` instead.
</blockquote></details>

Done.

---

*[drake/automotive/maliput_railcar.h, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfI3N4Hcqi7wzdM30_u:-KfIegKUyA2eeXernzlM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b27f55b00092ce712e63adb21acff3fb941d010/drake/automotive/maliput_railcar.h#L108)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, stray `.`
</blockquote></details>

Done.

---

*[drake/automotive/test/maliput_railcar_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfI5DALfiPgcNW-0E4n:-KfIf6gECDGlE4c0lCYz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b27f55b00092ce712e63adb21acff3fb941d010/drake/automotive/test/maliput_railcar_test.cc#L457)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW `happens`
</blockquote></details>

Done.

---

*[drake/automotive/test/maliput_railcar_test.cc, line 456 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-KfIccZPTH7zbXp6EYWe:-KfIf63C8_yO0aClL8aH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ef6e211988f5856288be907289677685205a40/drake/automotive/test/maliput_railcar_test.cc#L456)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, isn't it the velocity, not the acceleration, that is negative?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-:-KfIfR4iYNRryLkSA85Q:b7jqb5y)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r4.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497)*

**Comment by jadecastro** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5497#-:-KfMSQLJbd6smyW4yzT3:bnfp4nl)*

**Pull request merged**
