### PR TITLE
add make install step to the pod makefile

### PR DESCRIPTION
**Pull request by patmarion**
pod makefiles should build and install

### CODE REVIEW

**Comment by patmarion** [comment]
This pull request re-adds the install step to the pod makefile as described here: https://github.com/RobotLocomotion/drake/pull/1945#issuecomment-203517265

**Comment by jwnimmer-tri** [comment]
Is a way to prevent regressions like this in the future?  Another CI target?  Add a "sample downstream project" in RobotLocomotion that just links a simple example against Drake, and get that under CI?  Some kind of in-build unit-test that looks for the presence of a required pod-build-placed file?

**Comment by jamiesnape** [comment]
Can openhumanoids wrap Drake as if it were a standard CMake project? Unless I am misreading things in other tickets, it may not stay compatible in the medium to long term.

**Comment by patmarion** [comment]
@jwnimmer-tri there is a Travis-ci build for openhumanoids.  We could setup a robot that automatically updates a branch to test openhumanoids+drake/master.  That would be ideal.  If you wanted, you could go further and run it for every new drake pull request, instead of after a drake master merge.

@jamiesnape previously, drake's superbuild did not expose enough options for the superbuild to be customized by the embedding project, but that's likely improved.  Right now, openhumanoids has it's own superbuild to satisfy dependencies, then it calls the inner drake/drake/Makefile to build just drake.  This strategy has its quirks, but it works, and affords flexibility.  We'd be open to improvements, for sure!

**Comment by patmarion** [comment]
assigned to @jwnimmer-tri for review.  I just picked you since you were the first to reply :)

**Comment by jwnimmer-tri** [comment]
LGTM +1.  Still waiting for some builders.  Assigning second review & merge to @david-german-tri.

**Comment by jhoare** [comment]
Should this also be added to the root Makefile?

**Comment by patmarion** [comment]
No, there isn't an install target at the root superbuild currently.  A no-op install target could be created, but it's not necessary for the current usage.

**Comment by patmarion** [comment]
In case anyone is interested, here is some (long) discussion on the topic of building drake in openhumanoids, after the drake superbuild was introduced: https://github.com/RobotLocomotion/drake/issues/1234

Now that both projects have made more progress, I think it's feasible to implement the approach described here: https://github.com/RobotLocomotion/drake/issues/1234#issuecomment-132641812

**Comment by david-german-tri** [comment]
LGTM +1, sorry for the delay, didn't notice this was assigned to me.  Once you sync it should be good to merge.

**Comment by wxmerkt** [comment]
@patmarion I recall that after a conference call we've backed down from this idea and decided _not_ to move drake into software/externals because it could accidentally override changes users make inside drake during research/development.

**Comment by patmarion** [comment]
We could still put it in software/externals, but keep it as a git submodule, and do not allow the CMake ExternalProject call to modify it, that is, skip the update step, but do run the build step.

**Pull request merged**
