### PR TITLE
Use system gflags

### LINKED ISSUE #7643: Use system gflags
We currently install `drake/common/text_logging_gflags.h` which requires gflags. The easiest why for consumers of that header to use gflags is via the system packages and drake should do the same.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7643.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7669)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-msan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-msan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
Mac failures are `//common/proto:call_python_full_test` and unrelated to this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: as ubuntu reviewer, most feature review, and most platform review.

+@soonho-tri for additional review please:
- `setup/mac/install_prereqs.sh` feature and apple review
- `tools/workspace/gflags/gflags.bzl` platform review

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7669#-:-L1rKURF8ZUCsj7EGpQZ:bs2b5ma)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7669#-:-L1rQdalMS336CihpVgr:bnfp4nl)*

**Comment by peteflorence** [comment]
As another heads up of downstream implications from some recent PRs, this breaks the CMake build of drake-iiwa-driver.  It sounds like this is OK for Sammy since he's using the bazel build but breaks RLG's build setup. 

@jamiesnape @manuelli @sammy-tri

**Comment by jwnimmer-tri** [comment]
FYI Shambhala's CMake code to use system gflags is RobotLocomotion/drake-shambhala#75, if that helps.

**Comment by peteflorence** [comment]
Thanks Jeremy, yes that seems like will help, appreciate the pointer

**Pull request merged**
