### PR TITLE
Re-enable render server integration test

### PR DESCRIPTION
**Pull request by zachfang**
Relates to #18104

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116)

### CODE REVIEW

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
Looks good so far.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116#-:-NEaIXck1__wPGYLrJHG:b-37o3tj)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18116#-NEaIIghCRBgUbIonBCb:-NEaIIgi8M3VQR3OfLLW:b-mdrcug) ([raw file](https://github.com/robotlocomotion/drake/blob/e0b73cfbd8ae03a193f9f673e62e966df724b8e9/geometry/render_gltf_client/test/integration_test.py#L52)):*
> ```Python
> 
>         # Wait for the server to spawn up fully.
>         time.sleep(1)
> ```

BTW when adding looping to this, typically the sleep will be much less e.g. `time.sleep(0.1)` so that the test program is more responsive getting started.

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(status: single reviewer ok)

+(release notes: none)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116#-:-NEaNaKsB-XpU_rKYIjB:bs9jbr4)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18116#-NEaNeqk0THrcBHVXXm_):*
nit The more descriptive (and important) subject line would be something more like "Re-enable render server integration test".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18116#-NEaNeqk0THrcBHVXXm_):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The more descriptive (and important) subject line would be something more like "Re-enable render server integration test".
</blockquote></details>

(We can adjust this on merge, no need to re-push.)

**Review by zachfang — COMMENTED** [review]
The macOS CI test still times out. I will investigate further once I have access to a macOS machine.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116#-:-NEaYi3D832gnN00Yf-V:b-jmo7yf)* status: 1 unresolved discussion (waiting on @zachfang)

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18116)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @zachfang)

**Pull request merged**
