### PR TITLE
Fix minimal builds of drake/automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This repairs build breaks from #3520.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3542)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/lcmt_simple_car_config_t.lcm, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3542#-KSCUflY-e7OJo3oE3ME:-KSCUflY-e7OJo3oE3MF:b3nn3lb) ([raw file](https://github.com/robotlocomotion/drake/blob/724247519159f10ce6a2e052d945d0a86d3dd5db/drake/lcmtypes/lcmt_simple_car_config_t.lcm#L1)):*
> ```
> // This file is generated by drake/automotive/lcm_vector_gen.py. Do not edit.
> ```

Why did this file change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3542#-:-KSCV9W_LaKG6K2zfYbG:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3542#-:-KSCVT7qkXbMT4u7SeJZ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/lcmtypes/lcmt_simple_car_config_t.lcm, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3542#-KSCUflY-e7OJo3oE3ME:-KSCVRTketiHJDxsQ9rQ:b-soe13u) ([raw file](https://github.com/robotlocomotion/drake/blob/724247519159f10ce6a2e052d945d0a86d3dd5db/drake/lcmtypes/lcmt_simple_car_config_t.lcm#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why did this file change?
</details>
It used to be hand-written, now it's generated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3542)*

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3542)*

**Comment by jwnimmer-tri** [comment]
The minimal builds all passed, but the edits broke ROS.  Repushed with ROS-only edits.
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3542)*

**Comment by jwnimmer-tri** [comment]
ROS passed, and all of the matrix builds passed except for matlab (which is still running).
Using override-merge to get Continuous quickly healthy again.

**Pull request merged**
