### PR TITLE
py systems: Bind Value[ContextBase]

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards Anzu PR 9782

\cc @sammy-tri @ggould-tri 

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/systems/test/general_test.py` line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18257#-NFzUDQB1JeuB_qweOaX:-NFzUDQB1JeuB_qweOaY:bog3zvw) ([raw file](https://github.com/robotlocomotion/drake/blob/ebb4e30a40eaebed9ff3992062e370475ab92524/bindings/pydrake/systems/test/general_test.py#L198)):*
> ```Python
> 
>             # Test value instantiations.
>             self.assertIsInstance(
> ```

Working: Our autocaster for `Value` is unhappy with dynamic polymorphism. Should be straightforward to fix, but may not fix it just yet.

**Comment by jwnimmer-tri** [comment]
The base class `ContextBase` defines a `Clone` function.  Therefore the only valid C++ spelling is `Value<ContextBase>`.  Any additional downcasting in the user's job, outside of the `Value` type-erasure.  If there is Anzu code that does `Value<Context<double>>` or `Value[Context_[float]]`, that code is broken.

**Comment by EricCousineau-TRI** [comment]
Kewl. I was struggling to figure out if type slicing was happening or not.
Will see if I can check what's going on w/ Anzu code, and reflect it here.

**Comment by EricCousineau-TRI** [comment]
Actually, the code in Anzu doesn't seem to be slicing the types. However, I will rejigger it to use `ContextBase` as type erased param of `Value<>`.

**Comment by jwnimmer-tri** [comment]
It's less of a "will necessarily fail at runtime" question and more of a policy question.  I think our expectation should be that we type-erase in the framework using the most base type, even if subtypes sometimes shadow the `Clone` function to change its return type.

**Comment by jwnimmer-tri** [comment]
I suppose another choice would be to make `ContextBase::Clone` not exist (e.g., rename it), in which case type-erasing the `Context<T>` might work.

**Review by EricCousineau-TRI — COMMENTED** [review]
I'm happy with a policy of "use the highest / most parent class" when doing any RTTI-constrained registrations.
It was purty easy to switch to `ContextBase` both here and in Anzu PR.

It's a bit awkward to use `dynamic_cast<const Context<T>*>(&port.Eval<ContextBase>(diagram_context))`, but at least the mechanics are straightforward (albeit weird).

+@jwnimmer-tri Might you be up for review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257#-:-NFzo78m8jVB92nTsmIm:bkpd6xg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/systems/test/general_test.py` line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18257#-NFzUDQB1JeuB_qweOaX:-NFzo5jv7nHE5aNrIuXg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ebb4e30a40eaebed9ff3992062e370475ab92524/bindings/pydrake/systems/test/general_test.py#L198)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Our autocaster for `Value` is unhappy with dynamic polymorphism. Should be straightforward to fix, but may not fix it just yet.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/_value_extra.py` line 20 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18257#-NFzr-Ft8duep6BjYRd4:-NFzr-Ft8duep6BjYRd5:b6ai3pb) ([raw file](https://github.com/robotlocomotion/drake/blob/282afabfc6d69fc00b1371b84b2ea912975c6b5e/bindings/pydrake/common/_value_extra.py#L20)):*
> ```Python
>     else:
>         cls = type(value)
>     if isinstance(cls, type):
> ```

It doesn't seem to me like guessing is the right answer here.

What do you think about `AbstractValue.Make(context, type=ContextBase)` at the call site?   The default of `type=None` would use `type(value)` as the default.

(I'd also be okay with `cls=` instead of `type=` as the kwarg name.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/_value_extra.py` line 20 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18257#-NFzr-Ft8duep6BjYRd4:-NFzruorD5tDNMoLJE7d:b45oo1h) ([raw file](https://github.com/robotlocomotion/drake/blob/282afabfc6d69fc00b1371b84b2ea912975c6b5e/bindings/pydrake/common/_value_extra.py#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It doesn't seem to me like guessing is the right answer here.

What do you think about `AbstractValue.Make(context, type=ContextBase)` at the call site?   The default of `type=None` would use `type(value)` as the default.

(I'd also be okay with `cls=` instead of `type=` as the kwarg name.)
</blockquote></details>

I would not call this guessing.
I do agree that there is a chance that a user could register a lower type; if you are concerned about that, I can add a "listener" to `Value` that will throw if any concrete `T` is registered that is a subclass of a base.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18257)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/_value_extra.py` line 20 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18257#-NFzr-Ft8duep6BjYRd4:-NFzuWU3E3om1DK1Wlx8:b-aeos39) ([raw file](https://github.com/robotlocomotion/drake/blob/282afabfc6d69fc00b1371b84b2ea912975c6b5e/bindings/pydrake/common/_value_extra.py#L20)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I would not call this guessing.
I do agree that there is a chance that a user could register a lower type; if you are concerned about that, I can add a "listener" to `Value` that will throw if any concrete `T` is registered that is a subclass of a base.
</blockquote></details>

In C++, the static type of the erased object comes from the compile-time type.  Since we only ever have runtime types in Python, if the dynamic type does not match the intended static type then we'll need to designate that somehow. This PR proposes one approach for doing so.

I don't think we have enough evidence to say that the "virtual types" approach is _always_ the correct answer.  To me, it's pretty clear that no matter what you or I think about the quality of this heuristic, we _must_ provide a kwarg escape hatch that allows the user to override the  `cls` (in which case we'd set `throw_error=True` during the lookup).  This would allow for a related use case -- where the user wants `Value[object]` for connecting Python leaf systems, even though the runtime type happens to be an otherwise-registered Value instantiation.

Taking the `cls=None` optional kwarg as a given, obviously the call sites _could_ say `AbstractValue.Make(context, cls=ContextBase)`.  Then the question is therefore whether the "virtual types" heuristic is sufficiently worthwhile?  How much syntax-spew or brittleness-risk does it save, versus how much call-site-ambiguity or wrong-guessing-risk does it introduce?

To me, I don't see it as a good trade-off but maybe you have examples to the contrary.

Is the use case for the heuristic _only_ when declaring the input port types on a Python leaf system?  If so, there are probably much better ways to handle that case than the "virtual types" here.  The fact that Python needs to supply a static type for input ports is stupid, and we should just do away with that entirely.

**Comment by jwnimmer-tri** [comment]
Closing as abandoned. When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
