### PR TITLE
Improve spatial inertia shift efficiency.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610)

### CODE REVIEW

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-continuous-release
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Review by mitiguy — COMMENTED** [review]
Feature review +@xuchenhan-tri 
Created one-step SpatialInertia shift from center of mass to mimic the functionality in RotationalInertia.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NY0isWf8vT7hA_Sb_CH:b-mcq9uf)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. I have some concerns about the check about whether P == Scm. PTAL, thanks.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NYPD53l0SZTLj7B1Mko:b-gtgkbu)* status: 7 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPCgN-AFdkc8pk7Zkt:-NYPCgN-AFdkc8pk7Zku:buk216g) (no related file):*
Should there be unit tests covering the new functions or do you think the existing tests on publicly available `Shift` related functions are enough coverage?

Personally I would like to see a test that stresses the `DRAKE_ASSERT` added in this PR. Please see below.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP6zRgD82XcQtUimms):*
nit, the commit message is a bit misleading. The PR actually adds new functions 
___
*[`multibody/tree/spatial_inertia.h` line 805 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP8h5zAe766cGD5ike:-NYP8h5zAe766cGD5ikf:byg8vr9) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L805)):*
> ```objc
>   // @return A reference to M_SP_E, `this` spatial inertia that has been shifted
>   // from about-point Scm to about-point P, expressed in frame E.
>   SpatialInertia<T>& ShiftFromCenterOfMassInPlace(const Vector3<T>& p_ScmP_E);
> ```

minor, is it a required precondition that `this` SpatialInertia is about `Scm` when the function is invoked? Ditto for the other new function below.
___
*[`multibody/tree/spatial_inertia.h` line 812 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP4R6eBI9k_nZya21A:-NYP4R6eBI9k_nZya21B:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L812)):*
> ```objc
>   // (both are expressed-in frame E).
>   // @param[in] p_ScmP_E Position vector from Scm to P, expressed-in frame E.
>   // @retval M_SP_E S's rotational inertia about-point P expressed-in frame E.
> ```

typo



_Suggestion:_
```objc
// @retval M_SP_E S's spatial inertia about-point P expressed-in frame E.
```
___
*[`multibody/tree/spatial_inertia.h` line 814 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP8vwJ0QDgfTqhqlja:-NYP8vwJ0QDgfTqhqljb:b7vlz3b) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L814)):*
> ```objc
>   // @retval M_SP_E S's rotational inertia about-point P expressed-in frame E.
>   SpatialInertia<T> ShiftFromCenterOfMass(const Vector3<T>& p_ScmP_E) const
>       __attribute__((warn_unused_result));
> ```

minor: this seems to be a violation of GSG https://drake.mit.edu/styleguide/cppguide.html#Nonstandard_Extensions

The preferred spelling is

```  [[nodiscard]] SpatialInertia<T> ShiftFromCenterOfMass(const Vector3<T>& p_ScmP_E) const;```
___
*[`multibody/tree/spatial_inertia.cc` line 364 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPBLiA2pLgcCrihRjl:-NYPBLiA2pLgcCrihRjm:b-ou0be) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.cc#L364)):*
> ```cpp
> SpatialInertia<T>& SpatialInertia<T>::ShiftFromCenterOfMassInPlace(
>     const Vector3<T>& p_ScmP_E) {
>   DRAKE_ASSERT(p_PScm_E_ == Vector3<T>::Zero());
> ```

This assert is a little suspicious to me. The use of `DRAKE_ASSERT` seems to indicate any violation is a bug. However, it seems to me like innocuous invocations of `ShiftInPlace` can trigger this condition?

Also, do we want to allow zero values with non empty derivatives in the case of autodiffxd? What about values that are slightly non-zero due to round-offs?
___
*[`multibody/tree/spatial_inertia.cc` line 367 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPA0pQ3VAgsoTfpodc:-NYPA0pQ3VAgsoTfpodd:bfwznss) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.cc#L367)):*
> ```cpp
>   G_SP_E_.ShiftFromCenterOfMassInPlace(p_ScmP_E);
>   p_PScm_E_ = -p_ScmP_E;
>   return *this;  // Returns M_B
> ```

nit, this comment is a bit confusing. What is B?



_Code quote:_
```cpp
// Returns M_B
```

**Review by mitiguy — COMMENTED** [review]
Updated -- please take a look.  I think P == Scm maybe OK, see below

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NYPXlYP7nd2_1Ab3gUT:bo9wit)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP6zRgD82XcQtUimms):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the commit message is a bit misleading. The PR actually adds new functions 
</blockquote></details>

Proposed new commit message -- what do you think:
Add SpatialInertia::ShiftFromCenterOfMassInPlace() and ShiftFromCenterOfMass() to enhance efficiency.
___
*[`multibody/tree/spatial_inertia.h` line 805 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP8h5zAe766cGD5ike:-NYPVX8K3lbazff8SVKS:bpt4lfz) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L805)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, is it a required precondition that `this` SpatialInertia is about `Scm` when the function is invoked? Ditto for the other new function below.
</blockquote></details>

Done.  Here and below.
___
*[`multibody/tree/spatial_inertia.h` line 812 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP4R6eBI9k_nZya21A:-NYPEYxyAhAA1TJ5NMNf:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L812)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.h` line 814 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP8vwJ0QDgfTqhqlja:-NYPRd5T8A_ie2UYnfSF:b-snh328) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L814)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor: this seems to be a violation of GSG https://drake.mit.edu/styleguide/cppguide.html#Nonstandard_Extensions

The preferred spelling is

```  [[nodiscard]] SpatialInertia<T> ShiftFromCenterOfMass(const Vector3<T>& p_ScmP_E) const;```
</blockquote></details>

Done here and elsewhere.
___
*[`multibody/tree/spatial_inertia.cc` line 364 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPBLiA2pLgcCrihRjl:-NYPWUyl9_WUSHCT4qyI:b-v0kyl) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.cc#L364)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This assert is a little suspicious to me. The use of `DRAKE_ASSERT` seems to indicate any violation is a bug. However, it seems to me like innocuous invocations of `ShiftInPlace` can trigger this condition?

Also, do we want to allow zero values with non empty derivatives in the case of autodiffxd? What about values that are slightly non-zero due to round-offs?
</blockquote></details>

ShiftFromCenterOfMassInPlace() and ShiftFromCenterOfMass() are private functions that are only called in a few places.  ShiftInPlace() does not use it, instead it uses a RotationalInertia::ShiftFromCenterOfMass().
___
*[`multibody/tree/spatial_inertia.cc` line 367 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPA0pQ3VAgsoTfpodc:-NYPTwll7Ge6L2QTW4ZX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.cc#L367)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this comment is a bit confusing. What is B?
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm:
+@jwnimmer-tri for platform review please.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NYPc-5Y79rrFNQgLtWo:b-u5ckl3)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP6zRgD82XcQtUimms):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Proposed new commit message -- what do you think:
Add SpatialInertia::ShiftFromCenterOfMassInPlace() and ShiftFromCenterOfMass() to enhance efficiency.
</blockquote></details>

That looks good. The goal of the new function is to enhance efficiency; I had missed that in the first iteration.
___
*[`multibody/tree/spatial_inertia.h` line 805 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYP8h5zAe766cGD5ike:-NYPbhTCCPn9h9UxkPsA:b-iqn00c) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.h#L805)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  Here and below.
</blockquote></details>

Looks good, but I feel like a simple `p_PScm_E_ == Vector3<T>::Zero()` would suffice.
___
*[`multibody/tree/spatial_inertia.cc` line 364 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-NYPBLiA2pLgcCrihRjl:-NYPbEYsD5abENBw3e-j:b-pve23f) ([raw file](https://github.com/RobotLocomotion/drake/blob/dffb453c07fffda4044c93eedbbbd203c9d0059d/multibody/tree/spatial_inertia.cc#L364)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

ShiftFromCenterOfMassInPlace() and ShiftFromCenterOfMass() are private functions that are only called in a few places.  ShiftInPlace() does not use it, instead it uses a RotationalInertia::ShiftFromCenterOfMass().
</blockquote></details>

I see, thanks for the explanation. This is really just a helper for certain factory methods where you have complete control of all the initial states.

**Comment by jwnimmer-tri** [comment]
+@sherm1 -@jwnimmer-tri for platform review for load balancing.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: -- wait for Mac CI before merging.

> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NYPoZh_6zxtPu_Y_XpD:bs55jpb)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19610#-:-NYPv_BoDRGpSdUBta_L:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
