### PR TITLE
pydrake: Merge `util` into `common`, maintain backwards compatibility

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
- [x] Do rename
- [x] Ensure backwards compatibility.
- [x] ~Hide modules / symbols not meant to be public.~

Requires:
- [x] #9544

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9416)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@EricCousineau-TRI I assigned this to you as the author for lack of better knowledge -- even knowing you're on vacation. But since this doesn't seem ready for merging/review, you'll have plenty of time to reassign when you get back (as necessary).

**Comment by jwnimmer-tri** [comment]
I'm nope'ing out of here.
-@jwnimmer-tri +@EricCousineau-TRI 

The PR is too big.  It's 1 line away from LOC limit, and there are too many different semantic changes conflated, even with the curated commits.

From my early look, instead I'd suggest a first PR that just moves the internal helper headers out of util -- that does not change the pydrake module APIs.  It seems like a lot of the chaff is just from that move, and it should really easy to grok in isolation.

**Comment by EricCousineau-TRI** [comment]
Done; simplified and concentrated just on the moving of files.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI FYI I am going to wait for this PR to merge, before (then immediately) turning on `clang-format` for pydrake's common and util folders.

**Comment by EricCousineau-TRI** [comment]
Fixed, I think; was b/c I was referring to `//:drake_shared_library`.

**Pull request merged**
