### PR TITLE
Remove add cost for all variables

### LINKED ISSUE #4910: Remove functions that add cost/constraints in MathematicalProgram for all variables.
Currently `MathematicalProgram` has functions like
```
MathematicalProgram::AddLinearConstraint(A, lb, ub);
```
which means imposing the constraint `lb <= A*x<=ub` for ALL variables inside `MathematicalProgram`. Personally I find this function unnecessary. This function also assumes that the user knows the order of the variables stored inside `MathematicalProgram`, as by reversing the order inside `x`, the meaning of this constraint is totally changed. I think that is a very strong assumption, and the user in most cases do not know the order of the variables inside `MathematicalProgram`.

Also, removing this function makes `mathematical_program.h` file a lot smaller, since for each type of cost/constraint, we have a function for all variables.

@sammy-tri and @RussTedrake what do you think?

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #4910 

@RussTedrake you might like the changes in `convex_optimization_test.cc`, when writing linear equality constraint for matrices. Thanks to @soonho-tri 's work on symbolic expression, this part is a lot cleaner.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4943)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbWYocP2OFaP7RrdfC6:bp61js4)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbWzHlqBN6eEFVmWxxR:bq323eq)*

**Comment by RussTedrake** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 1212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-KbaSoxn8UEA2EGxuUoU:-KbaSoxn8UEA2EGxuUoV:b-voj4t2) ([raw file](https://github.com/robotlocomotion/drake/blob/86e7fae609be82f3b72a69552e070ccfb1739cd0/drake/solvers/test/convex_optimization_test.cc#L1212)):*
> ```cpp
>   // M = A' * P + P * A + Q.
>   Eigen::Matrix<symbolic::Expression, x_dim, x_dim> M;
>   M = A.transpose() * P + P * A + Q;
> ```

@hongkai-dai -- i don't like it.  i love it!!  

---

*[drake/solvers/test/convex_optimization_test.cc, line 1218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-KbaSwcMIzJGk5ms91ck:-KbaSwcMIzJGk5ms91cl:belhyrq) ([raw file](https://github.com/robotlocomotion/drake/blob/86e7fae609be82f3b72a69552e070ccfb1739cd0/drake/solvers/test/convex_optimization_test.cc#L1218)):*
> ```cpp
>   for (int j = 0; j < x_dim; ++j) {
>     for (int i = j; i < x_dim; ++i) {
>       M_lower_triangular(M_count++) = M(i, j);
> ```

Can you use https://eigen.tuxfamily.org/dox/classEigen_1_1TriangularView.html to clean this part up, too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 1218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-KbaSwcMIzJGk5ms91ck:-KbafiFDSJ2uFDYl2zU8:b4wzkiy) ([raw file](https://github.com/robotlocomotion/drake/blob/86e7fae609be82f3b72a69552e070ccfb1739cd0/drake/solvers/test/convex_optimization_test.cc#L1218)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can you use https://eigen.tuxfamily.org/dox/classEigen_1_1TriangularView.html to clean this part up, too?
</blockquote></details>

This part is going to be cleaned by using 
```C++
AddPositiveSemidefiniteConstraint(A.transpose()*P + P*A)
```
Namely we do not need to create a matrix `Q`, with two constraints
```
A'*P + P*a = -Q
Q is psd
```
This clean up will becomes easier when I get the LMI constraint in the symbolic form, which I think can be finished next week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbjwbHh-3Wrc4AcNEDI:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbkLJDR3aMnX-yo5tbi:bfvx2sg)*

**Comment by sherm1** [comment]
:lgtm: -- love seeing all that code deleted!

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KblK0jD4jjIECGsBCHk:b9fbw5)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KblfSuUnWG_X7Dgsw6-:b-goi7bm)*

**Comment by hongkai-dai** [comment]
@russtedrake I will clean up the for loop in my next PR, which allows the user to call a linear equality constraint for a matrix of expressions. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbmNaltbM9hk1g-OC1A:b-3a1j3j)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4943#-:-KbpqtdTFev_-jYm-tVy:bnfp4nl)*

**Pull request merged**
