### PR TITLE
[workspace] Upgrade Clarabel.rs to latest release 0.7.1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This reverts the default tolerance changes from #20844, now that the solver can handle the tighter bounds.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21053)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@AlexandreAmice for review of the tolerance changes piece, please.

+@rpoyner-tri for platform review, please.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

I sent you a PR that actually captures the improved behavior if you are interested. Before this patch, my test causes Clarabel to panic, and hence crash Drake. After this PR, Clarabel simply returns insufficient progress which is desirable.

> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21053#-:-NvsZnyK0NB_2hJcUWJ0:bbk3afh)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks!  I merged it with one small code style tweak.

> Reviewed 19 of 19 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21053#-:-NvsdKWAAfczJBcAt6BA:b-yz4u4e)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 19 of 19 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21053#-:-Nw5U3KA2WyLWCjLWGzZ:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
