### PR TITLE
Move reusable parts of the schunk wsg 50 simulation into manipulation

### PR DESCRIPTION
**Pull request by sammy-tri**
While this is a moderately large PR in terms of number of lines, it's as close to pure `git mv` as I could make it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6105)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review
pinging @siyuanfeng-tri in case you've got any opinions on the result

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkCxGGOUTPYqSeKKTk_:b6z6q21)*

**Comment by siyuanfeng-tri** [comment]
lolz, this touched more files than i expected. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkCy0lOl84mWPWOTp_y:b-e5behm)*

**Comment by naveenoid** [comment]
A couple of minor BTWs apart :lgtm: 

Also, I feel like shouting "Olé" for every one of these clean up PRs :grinning: Hated the idea of one example linking to another. 

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/manipulation/models/wsg_50_description/LICENSE.TXT, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-KkFOLRKA6bDger60pQa:-KkFOLRKA6bDger60pQb:bscl5ji) ([raw file](https://github.com/robotlocomotion/drake/blob/f94a8f09dcac5c0b801ba90846677537e1115591/drake/manipulation/models/wsg_50_description/LICENSE.TXT#L12)):*
> ```
> terms (see LICENSE.TXT in Drake's root folder).
> 
> The files in sdf/ were developed entirely in Drake, and are also covered by Drake's license terms.
> ```

BTW: there is a weird line break seemingly inside the word "license"

---

*[drake/manipulation/schunk_wsg/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-KkFP25PfXOX6z0bZNaC:-KkFP25PfXOX6z0bZNaD:b-wbpg8) ([raw file](https://github.com/robotlocomotion/drake/blob/f94a8f09dcac5c0b801ba90846677537e1115591/drake/manipulation/schunk_wsg/CMakeLists.txt#L10)):*
> ```CMake
>   drake_install_libraries(drakeSchunkWsg)
>   drake_install_headers(
>     # N.B. The gen/*.h headers are installed by gen/CMakeLists.txt.
> ```

BTW: I had to google N.B. (shame-face). Perhaps "Note" would be easier for plebs like me?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkFPa9cJ7mlrycCvH9r:bm1a6t0)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 36 of 37 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkHGnZRzAhwYJcAZshe:b-rm2p6t)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review (punting to tomorrow's reviewer since I'm on-call today)

---

Review status: 35 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/LICENSE.TXT, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-KkFOLRKA6bDger60pQa:-KkHHbBxeHkwNL0U1T4T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f94a8f09dcac5c0b801ba90846677537e1115591/drake/manipulation/models/wsg_50_description/LICENSE.TXT#L12)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: there is a weird line break seemingly inside the word "license"
</blockquote></details>

Done.

---

*[drake/manipulation/schunk_wsg/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-KkFP25PfXOX6z0bZNaC:-KkHHkGbk2bCKBjkm7AX:b-y4acla) ([raw file](https://github.com/robotlocomotion/drake/blob/f94a8f09dcac5c0b801ba90846677537e1115591/drake/manipulation/schunk_wsg/CMakeLists.txt#L10)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: I had to google N.B. (shame-face). Perhaps "Note" would be easier for plebs like me?
</blockquote></details>

I count 37 uses of this abbreviation in drake tree at the moment (also I think this was copied from automotive which uses the same text).  anyway, I'm going to skip cleaning that up in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkHIEPUdmjiYCsJd8s0:baugk8f)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

---

Review status: 35 of 37 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkHNSnaoemHbIflIxhu:bko8goz)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: 35 of 37 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkHQQJ9gYUX_i5QIaa9:bq323eq)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by naveenoid** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 44 of 48 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6105#-:-KkLm5_FaSPsVaC3INnM:bnfp4nl)*

**Pull request merged**
