### PR TITLE
Move core/Vector.h to systems/Vector.h

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Move `core/Vector.h` to `systems/vector.h`.  It is deprecated (only used by System1), and in the way of killing off `core`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3032)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/vector_test.cc, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3032#-KOBsoMRXmFcQ4TzNErk:-KOBsoMRXmFcQ4TzNErl:-2124628224) ([raw file](https://github.com/robotlocomotion/drake/blob/2f494f2b40f7c930039b34c74c9063bff5ea1f68/drake/systems/test/vector_test.cc#L4)):*
> ```cpp
> 
> #include "drake/systems/test/pendulum.h"
> #include "drake/systems/vector.h"
> ```

nit: this should go at the top of the file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3032)*

**Comment by jwnimmer-tri** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/vector_test.cc, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3032#-KOBsoMRXmFcQ4TzNErk:-KOBuTjXLNEgOlJSZECT:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2f494f2b40f7c930039b34c74c9063bff5ea1f68/drake/systems/test/vector_test.cc#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: this should go at the top of the file
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3032)*

**Comment by jwnimmer-tri** [comment]
@ggould-tri for feature review please (is this a good idea?)
@david-german-tri for platform review please (is this good idea, and are all of the details correct?)

**Comment by ggould-tri** [comment]
:lgtm: ; one minor nit noted below.

---

Reviewed 24 of 25 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/simple_car_test.cc, line 8 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3032#-KOFnMlZz2fZfa-Eb_2r:-KOFnMlah42g3Cwmgz6N:1137356618) ([raw file](https://github.com/robotlocomotion/drake/blob/434276866c6d0b7d35ea038ec1692c1fc934ea6a/drake/examples/Cars/test/simple_car_test.cc#L8)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "drake/systems/Simulation.h"
> ```

FYI -- this is out of alpha order (unless we are saying capital letters are alpha-prior to lowercase)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3032#-:-KOFnmFraht-pUE1cTWo:-1296988181)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/test/simple_car_test.cc, line 8 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3032#-KOFnMlZz2fZfa-Eb_2r:-KOFpfJzOcOc22miBkci:-962977009) ([raw file](https://github.com/robotlocomotion/drake/blob/434276866c6d0b7d35ea038ec1692c1fc934ea6a/drake/examples/Cars/test/simple_car_test.cc#L8)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- this is out of alpha order (unless we are saying capital letters are alpha-prior to lowercase)
</details>
This change is consistent with what emacs `M-x sort-lines` and `clang-format` both want.  In other words: filenames are case-sensitive and follow ASCII order (capitals first).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3032)*

**Comment by jwnimmer-tri** [comment]
Sigh.  I broke ROS again.  As much as I rejoice in that outcome, I will go fix it now.

**Pull request merged**
