### PR TITLE
pydrake: Use transitive `py::keep_alive` to aid in REPL-friendly behavior.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates #7660.
Per discussions in Platform Reviewer's meeting and after.

\cc @jwnimmer-tri @sammy-tri @ggould-tri @rdeits 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7742)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@peteflorence for feature review, please (if you have time).
+@sherm1 for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-:-L2c2gZPhzhJ2ewTKW7T:bumwq0e)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/lifetime_test.py, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2eodvtGa49gKGcrAbE:-L2eodvu-Y2ddirQsW4L:b5vsil6) ([raw file](https://github.com/robotlocomotion/drake/blob/ad28eb1b90bac2b8b270276e2e7d91061524dc9f/bindings/pydrake/systems/test/lifetime_test.py#L64)):*
> ```Python
>         # `.AddSystem` is called, and `builder` will keep `diagram` alive after
>         # `.Build` is called.
>         # Transitively, `system` will keep `builder` alive (as it's old owner)
> ```

FYI typo "it's" should be 'its'
(also on next line)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/lifetime_test.py, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2eodvtGa49gKGcrAbE:-L2fGCoKzTZh97HTWojM:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/ad28eb1b90bac2b8b270276e2e7d91061524dc9f/bindings/pydrake/systems/test/lifetime_test.py#L64)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "it's" should be 'its'
(also on next line)
</blockquote></details>

Done. Thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742)*

**Comment by sherm1** [comment]
Platform review :lgtm: with the caveat that platform reviewer has very limited understanding of python wrapping -- so careful feature review is still needed.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2fpSM9nGS69D6Ib4Xs:-L2fpSM9nGS69D6Ib4Xt:bpslrau) ([raw file](https://github.com/robotlocomotion/drake/blob/5be647bc2b4f975e00314ceb64da6fac0a7b57ee/bindings/pydrake/systems/analysis_py.cc#L23)):*
> ```cpp
>     .def(py::init<const System<T>&, unique_ptr<Context<T>>>(),
>          // This refers to System, and thus must keep the system alive.
>          py::keep_alive<1, 2>(),
> ```

BTW please consider documenting your intentions for Nurse and Patient with each keep_alive -- with just the ints it is hard to look at the code and see that it is right. You could say "don't let the System die before the Simulator" or something like that, then the reader could match the argument indices to your intentions.

---

*[bindings/pydrake/systems/framework_py.cc, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2fqVDjDCdNm8d-sSG1:-L2fqVDjDCdNm8d-sSG2:b9yfsam) ([raw file](https://github.com/robotlocomotion/drake/blob/5be647bc2b4f975e00314ceb64da6fac0a7b57ee/bindings/pydrake/systems/framework_py.cc#L165)):*
> ```cpp
>     // Use transitive keep_alive to ensure all Systems stay alive with their
>     // new owner.
>     .def("Build", &DiagramBuilder<T>::Build, py::keep_alive<1, 0>())
> ```

BTW hard for me to understand what the 1 and 0 are referencing here. Something like "diagram builder class keeps the return argument alive"? A comment about the intent would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-:-L2frB4IfAb7f_OkXpTL:b-72sw4u)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2fpSM9nGS69D6Ib4Xs:-L2gZQ5oARG0JSoxxzN4:b-uw11hw) ([raw file](https://github.com/robotlocomotion/drake/blob/5be647bc2b4f975e00314ceb64da6fac0a7b57ee/bindings/pydrake/systems/analysis_py.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider documenting your intentions for Nurse and Patient with each keep_alive -- with just the ints it is hard to look at the code and see that it is right. You could say "don't let the System die before the Simulator" or something like that, then the reader could match the argument indices to your intentions.
</blockquote></details>

Done.

I want to avoid explicitly spelling out the corner cases in every invocation, as it would get quite verbose.
I've made terse comments, with explanations in one area (which will be moved to somewhere more obvious soon).

---

*[bindings/pydrake/systems/framework_py.cc, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-L2fqVDjDCdNm8d-sSG1:-L2gZ_v_P5Os5XsYp_Sn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5be647bc2b4f975e00314ceb64da6fac0a7b57ee/bindings/pydrake/systems/framework_py.cc#L165)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW hard for me to understand what the 1 and 0 are referencing here. Something like "diagram builder class keeps the return argument alive"? A comment about the intent would be nice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742)*

**Comment by EricCousineau-TRI** [comment]
Marginally related (for future-proofing) due to use of `keep_alive`:
https://github.com/pybind/pybind11/issues/1251

\cc @jwnimmer-tri

**Comment by sherm1** [comment]
Great comments -- thanks, @ericcousineau-tri!

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-:-L2gzAgtM-aqSH2Zz9up:b-rnn8uh)*

**Comment by peteflorence** [comment]
Hey Eric was happy to look this over.  Your comments were useful.  I am not familiar with pybind so I'm not much help on the `.cc` files, but this seems nice and I'd like to learn more, so was fun to poke a bit at. 

The `.py` tests were more useful for me to look over.

I would suggest potentially just having an explicit test which is to print out state and then ensure that the object is still mutable?  (Since that is the simple example that inspired this feature?)  Perhaps the current tests test the same idea.  What do you think?

**Comment by EricCousineau-TRI** [comment]
I think the current tests effectively cover that same idea (the object staying alive means that the object is still accessible  mutable), but I went ahead and added a value-based test. 

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-:-L36WZjLmiqCcFjZOK9L:ba8jnc2)*

**Comment by peteflorence** [comment]
LGTM

**Comment by peteflorence** [comment]
Thanks for the adding the value test -- yes looks good

**Comment by peteflorence** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7742#-:-L3KPXymDbVRfrQyj3V6:bnfp4nl)*

**Pull request merged**
