### PR TITLE
add autodiff explicit instantiations to rigid body plant contact classes

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8166)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for both reviews please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-:-L69rjZHGeHlr6hMyvlV:b-2gceyk)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/rigid_body_plant/contact_detail.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CWjNpmZm4T43X8Uc0:-L6CZMfXtFbZP7qu2Izg:b-6qghab) ([raw file](https://github.com/robotlocomotion/drake/blob/0d18f00871417ad27c9ddcb5734dcb83886b3edf/multibody/rigid_body_plant/contact_detail.cc#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ This should either use [drake/common/default_scalars.h](https://github.com/RobotLocomotion/drake/blob/master/common/default_scalars.h)'s provided helper `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS`, or document why the defaults are inappropriate.

Ditto for all classes changed by this PR.

(Note that when using the helper, the direct `autodiff.,h` include here goes away.)
</blockquote></details>

i expected you would say that, but the helper did not compile for me.  will reproduce the failure... and post

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Comment by RussTedrake** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CXjgkElZCaAsrCkKe:-L6CcnD_xRDryHjNz3jn:b-t5m2ic) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this needs a feature reviewer assigned, to double-check that everything newly marked with `T = AutoDiff` in this PR is something sensible that we could take derivatives on.
</blockquote></details>

+@seancurtis-tri for feature review, please.

---

*[multibody/rigid_body_plant/contact_detail.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CXKCO7srFncrSy7di:-L6CbFDOIKErU2LCHFmC:bvzkr24) ([raw file](https://github.com/robotlocomotion/drake/blob/0d18f00871417ad27c9ddcb5734dcb83886b3edf/multibody/rigid_body_plant/contact_detail.cc#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ The class overview comment now fails to document the supported scalar types.

Ditto for all classes changed by this PR.
</blockquote></details>

It seems that we have a fundamental issue with our documentation -- since we don't list the types specifically in the instantiations, but instead call e.g.DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS , but in the documentation we explicitly list the types.  

---

*[multibody/rigid_body_plant/contact_detail.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CWjNpmZm4T43X8Uc0:-L6CcGt54OEHXV-OTKWp:b3mggqp) ([raw file](https://github.com/robotlocomotion/drake/blob/0d18f00871417ad27c9ddcb5734dcb83886b3edf/multibody/rigid_body_plant/contact_detail.cc#L16)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i expected you would say that, but the helper did not compile for me.  will reproduce the failure... and post
</blockquote></details>

ok.  i worked it out.  i think i had the wrong/missing header, and the error was very obtuse.  done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Comment by jwnimmer-tri** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/contact_detail.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CXKCO7srFncrSy7di:-L6CdcO74OSopOlWQKbd:b5zgfa8) ([raw file](https://github.com/robotlocomotion/drake/blob/0d18f00871417ad27c9ddcb5734dcb83886b3edf/multibody/rigid_body_plant/contact_detail.cc#L16)):*
>  The class overview comment now fails to document the supported scalar types.

The DEFAULT_SCALARS actually brings in Symbolic.  (The NONSYMBOLIC macro skips it.)  So as it stands in r2, we have Symbolic types instantiated but the docs don't say so.

> It seems that we have a fundamental issue with our documentation ...

The documentation would be less brittle if it cited the default scalars, instead of repeating them.  Almost(?) nowhere does this yet (but rather repeats the list), but that's only a problem when someone decides to change the set of default scalars; prior to doing that, we'd need to de-boilerplate the documentation first.  For this PR, I'm satisfied if the explicitly documented types in the header are consistent, even if not de-boilerplated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/contact_detail.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-L6CXKCO7srFncrSy7di:-L6CfCRYMaKZ9CqibJ9w:b4ciaoj) ([raw file](https://github.com/robotlocomotion/drake/blob/0d18f00871417ad27c9ddcb5734dcb83886b3edf/multibody/rigid_body_plant/contact_detail.cc#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

>  The class overview comment now fails to document the supported scalar types.

The DEFAULT_SCALARS actually brings in Symbolic.  (The NONSYMBOLIC macro skips it.)  So as it stands in r2, we have Symbolic types instantiated but the docs don't say so.

> It seems that we have a fundamental issue with our documentation ...

The documentation would be less brittle if it cited the default scalars, instead of repeating them.  Almost(?) nowhere does this yet (but rather repeats the list), but that's only a problem when someone decides to change the set of default scalars; prior to doing that, we'd need to de-boilerplate the documentation first.  For this PR, I'm satisfied if the explicitly documented types in the header are consistent, even if not de-boilerplated.
</blockquote></details>

done.  but cool to know that it all compiles with symbolic, too.  (yeah @soonho-tri!) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-:-L6Cg1dydCXHIAvwKcMF:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
While I believe this works, I'd expect to see some modicum of testing (at least instantiation) of the new scalar. Otherwise, :LGTM:.

---

Reviewed 7 of 13 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-:-L6DM4MEPrLyUO78nce1:bqjs6rd)*

**Comment by RussTedrake** [comment]
added proof of life tests.

---

Review status: 13 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166#-:-L6E4LKza_PL-jPQbUCO:b-timchj)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8166)*

**Pull request merged**
