### PR TITLE
setup: Upgrade to Bazel 0.15.2 as minimum supported

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
~This PR can't merge until #9275 is done.~  _Edit: it is done._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9276)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by BetsyMcPhail** [comment]
Mac images should be all set now. Retesting.

@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Pull request merged**
