### PR TITLE
Convert the pendulum energy shaping example to System2

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3696)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review.  +@jwnimmer-tri for platform review since he's tomorrow's on-call reviewer

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-:-KTLe8u6f_x5tZ9_rG_x:bg3agw7)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLhBVfktgVKRwESqyF:-KTLhBVgibJD2S0UAWO8:b-wvph7e) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L40)):*
> ```cpp
>     DRAKE_ASSERT(state != nullptr);
>     const T Etilde = .5 * m_ * l_ * l_ * state->thetadot() * state->thetadot() -
>         m_ * g_ * l_ * cos(state->theta()) - 1.1 * m_ * g_ * l_;
> ```

Missing `#include <cmath>` for `std::cos`.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLhTVRKY7jUwAUZas9:-KTLhTVSBia5-9zirxGU:b-fqeruk) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L41)):*
> ```cpp
>     const T Etilde = .5 * m_ * l_ * l_ * state->thetadot() * state->thetadot() -
>         m_ * g_ * l_ * cos(state->theta()) - 1.1 * m_ * g_ * l_;
>     const T tau = b_ * state->thetadot() - .1 * state->thetadot() * Etilde;
> ```

Will you hate me if I ask for a citation for the math again?

FWIW -- If there were a "README.md" in this folder that cited all of the math used by these examples, that would be enough for me.  I don't need comments everywhere, just something to hang my hat on.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgEJw-rE2rnyRggcK:-KTLgEJx98hZs8VOdXd0:b-66q00s) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L46)):*
> ```cpp
> 
>  private:
>   const double m_;
> ```

BTW These are returned from `pendulum` as `T` but converted to `double` here.  Is that what you want?

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTLgmMtRYZhUpU557Dv:b-89t9fm) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
> ```cpp
> 
>   simulator.Initialize();
>   simulator.StepTo(10);
> ```

BTW This removes the "lock to wallclocktime" that the demo used to have (when not run under `-s`).  That's fine with me, but is that okay for any related purposes of this demo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLhBVfktgVKRwESqyF:-KTPgxrny0wl48CNf3Tt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing `#include <cmath>` for `std::cos`.
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLhTVRKY7jUwAUZas9:-KTPhAZXglNOTdtIwDUZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Will you hate me if I ask for a citation for the math again?
> 
> FWIW -- If there were a "README.md" in this folder that cited all of the math used by these examples, that would be enough for me.  I don't need comments everywhere, just something to hang my hat on.
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgEJw-rE2rnyRggcK:-KTPhBIZ9wRZEzrUT1h0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW These are returned from `pendulum` as `T` but converted to `double` here.  Is that what you want?
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTPhCx2NyRyxnJVBFFc:bgw4q8h) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This removes the "lock to wallclocktime" that the demo used to have (when not run under `-s`).  That's fine with me, but is that okay for any related purposes of this demo?
</details>
It's not ideal.  The demo definitely runs faster than I'd like when watching from drake-visualizer.  I thought about adding a deliberate sleep in the energy shaping controller which could be activated by a flag, but this seemed sketchy.  Have you heard anything about System2 planning to have a lock-to-realtime feature again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTPlLZ1wnL2Xs2n--WM:bs0mr25) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> It's not ideal.  The demo definitely runs faster than I'd like when watching from drake-visualizer.  I thought about adding a deliberate sleep in the energy shaping controller which could be activated by a flag, but this seemed sketchy.  Have you heard anything about System2 planning to have a lock-to-realtime feature again?
</details>
I don't know, but it's also easy to do yourself if you really want it.  Just add a System block that Publishes given some event times you control, and sleeps in its Publish method.

In any case, up to you.  I'll mark myself resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-:-KTPlgVj-xhhcAH300Wy:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTPqNucwdOcsXfrQlmQ:b3aban6) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't know, but it's also easy to do yourself if you really want it.  Just add a System block that Publishes given some event times you control, and sleeps in its Publish method.
> 
> In any case, up to you.  I'll mark myself resolved.
</details>
This would be a Simulator2 feature request, not a System2 feature request.  Seems like a good one to me.  @sherm1 FYI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
+@lucy-tri Can you take a look as feature reviewer?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-:-KTUdI4szaw2mablLQQn:b-issy63)*

**Comment by Lucy-tri** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTV_M3I1x7CJAWCBPS-:-KTV_M3JjAHZnoJPHEII:b-q48wl9) ([raw file](https://github.com/robotlocomotion/drake/blob/83d3c40bcb4274b6bd7fc22134b7df2a6ed77c2a/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L45)):*
> ```cpp
>     // Swimming, Flying, and Manipulation (Course Notes for MIT
>     // 6.832). Downloaded on 2016-09-30 from
>     // http://underactuated.csail.mit.edu/underactuated.html?chapter=2
> ```

3.5.2 is in chapter 3, so I think it should say ...chapter=3

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTVfnC8uwUoQj6U3kBG:-KTVfnC8uwUoQj6U3kBH:bibvlf5) ([raw file](https://github.com/robotlocomotion/drake/blob/83d3c40bcb4274b6bd7fc22134b7df2a6ed77c2a/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L68)):*
>   builder.Connect(controller->get_output_port(0), pendulum->get_tau_port());
>   builder.Connect(pendulum->get_output_port(), controller->get_input_port(0));
would it make more sense to swap the 2 lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by sammy-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTV_M3I1x7CJAWCBPS-:-KTVmyOHOeaGC7W7WMWG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83d3c40bcb4274b6bd7fc22134b7df2a6ed77c2a/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L45)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> 3.5.2 is in chapter 3, so I think it should say ...chapter=3
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTVfnC8uwUoQj6U3kBG:-KTVnFVXdtAXz-q0p4d9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83d3c40bcb4274b6bd7fc22134b7df2a6ed77c2a/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L68)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> >   builder.Connect(controller->get_output_port(0), pendulum->get_tau_port());
> >   builder.Connect(pendulum->get_output_port(), controller->get_input_port(0));
> would it make more sense to swap the 2 lines?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by sammy-tri** [comment]
-@naveenoid since @lucy-tri is reviewing.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-:-KTVniodRRl2y1tEOpMq:b-7he4ug)*

**Comment by sherm1** [comment]
*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTVoB9esGjwS7Sx2f6h:b-tv7zzx) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This would be a Simulator2 feature request, not a System2 feature request.  Seems like a good one to me.  @sherm1 FYI
</details>
BTW, added "slow to real time" Simulator option to Q4 OKRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by sammy-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_energy_shaping.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-KTLgmMtRYZhUpU557Du:-KTVpUuX7gHmg_q7YclA:besbfsw) ([raw file](https://github.com/robotlocomotion/drake/blob/1c899473e00428c9cf26d90be417eccd41c34b74/drake/examples/Pendulum/pendulum_run_energy_shaping.cc#L77)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, added "slow to real time" Simulator option to Q4 OKRs.
</details>
Awesome!  Thanks much!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3696#-:-KTVqWBQ7ocBfiyn7dwS:bnfp4nl)*

**Pull request merged**
