### PR TITLE
Add MonomialBasis for a map from Variables to its degree.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Generate the monomial basis, such that the total degree for each Variables set is less than a specific degree.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-NixP3LQ1cgwEIOSdsjV:b7vod24)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
Can you add a test/documentation on what 

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-Nj3uyGA8c9jIsKFddDr:b-wdq0ae)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.h` line 223 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3vFEc60PLxQQQWsex:-Nj3vFEc60PLxQQQWsey:b-er4dox) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.h#L223)):*
> ```objc
>  * @param variables_degree `(vars, degree)` maps each set of variables `vars` to
>  * the maximal degree of these variables in the monomial. Namely the summation
>  * of the degree of each variable in `vars` is no larger than `degree`.
> ```

What happens if `degree` is negative? Do we need to document?



_Code quote:_
```objc
`degree`.
```
___
*[`common/symbolic/monomial_util.h` line 226 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3hPxr18ehqCjtwAhE:-Nj3hPxr18ehqCjtwAhF:b-e16c1v) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.h#L226)):*
> ```objc
>  * @pre The variables in `variables_degree` don't overlap.
>  */
> [[nodiscard]] VectorX<Monomial> MonomialBasis(
> ```

Not sure on the name here as this is a somewhat specific. If the type were `std::unordered_map<Variable, int>` (i.e. just one variable) I would call this the `CoordinateDegreeMonomialBasis`. Given that you're doing it at the set of variables, perhaps `PartitionedCoordinateDegreeMonomialBasis`. Either way, I think the name of the method is not sufficiently descriptive for the subtle way this creates a basis.

In terms of having a more natural method, perhaps we should have the version of this method were it is just single variables, not sets of them.



_Code quote:_
```objc
MonomialBasis
```
___
*[`common/symbolic/monomial_util.cc` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3lkit0fw4XUKGp-Hx:-Nj3lkit0fw4XUKGp-Hy:bs6xmi8) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.cc#L54)):*
> ```cpp
>     }
>     monomials_count = ssize(monomials);
>   }
> ```

I sent you a PR that I think simplifies this a good bit.



_Code quote:_
```cpp
  for (const auto& monomial_vec : monomial_basis_each_vars) {
    // When monomials is empty, just append monomial_vec to monomials.
    if (monomials_count == 0) {
      monomials.insert(monomials.begin(), monomial_vec.data(),
                       monomial_vec.data() + monomial_vec.rows());
    } else {
      for (int i = 0; i < monomials_count; ++i) {
        // Multiply monomials[i] with monomial_vec[j] for each i and j, except
        // when monomial_vec[j] is 1 (when monomial_vec[j] = 1, multiplying
        // monomials[i] with monomial_vec[j] is just monomials[i], which is
        // already in monomials.
        for (int j = 0; j < monomial_vec.rows(); ++j) {
          if (monomial_vec(j).total_degree() != 0) {
            monomials.push_back(monomials[i] * monomial_vec(j));
          }
        }
      }
    }
    monomials_count = ssize(monomials);
  }
```
___
*[`common/symbolic/test/monomial_util_test.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3u8ifDB8goWJBYHOe:-Nj3u8ifDB8goWJBYHOf:b-w8a0em) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L80)):*
> ```cpp
> 
>   const VectorX<Monomial> monomials =
>       MonomialBasis({{x_set, 2}, {y_set, 1}, {z_set, 1}});
> ```

I would make this more arbitrary than `1`



_Suggestion:_
```cpp
3
```
___
*[`common/symbolic/test/monomial_util_test.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3uCwW6TT8fdg3T2Bj:-Nj3uCwW6TT8fdg3T2Bk:bawtlv7) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L85)):*
> ```cpp
>   // 2 monomials in MonomialBasis(z_set, 1).
>   // So in total we should have 10 * 3 * 2 = 60 monomials.
>   EXPECT_EQ(monomials.rows(), 60);
> ```

If you follow my above suggestion on the degree of `z_set`



_Suggestion:_
```cpp
120
```
___
*[`common/symbolic/test/monomial_util_test.cc` line 101 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3uICk5fsx5aYfW7R3:-Nj3uICk5fsx5aYfW7R4:bawtlv7) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L101)):*
> ```cpp
>     EXPECT_LE(degree_in_vars(monomials(i), x_set), 2);
>     EXPECT_LE(degree_in_vars(monomials(i), y_set), 1);
>     EXPECT_LE(degree_in_vars(monomials(i), z_set), 1);
> ```

If you follow my above suggestion on the degree of `z_set`



_Suggestion:_
```cpp
3
```

**Review by AlexandreAmice — COMMENTED** [review]
Can you add a test/documentation on what happens if the passed degrees are `0`/negative numbers? If it's `0` I have already confirmed to myself that it works correctly.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-Nj3vLyPDbASzXmZ7_w_:b-4rcwc3)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Done. I added a test on degree = 0, and the documentation on negative number. 

We have a DRAKE_DEMAND(degree >= 0) in `ComputeMonomialBasis` function.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-Nj9KG63214_eloK4hyg:b-hsqno2)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.h` line 223 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3vFEc60PLxQQQWsex:-Nj9FiSx1RwuN87Sr_23:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.h#L223)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

What happens if `degree` is negative? Do we need to document?
</blockquote></details>

Done.
___
*[`common/symbolic/monomial_util.h` line 226 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3hPxr18ehqCjtwAhE:-Nj9G3AzDQBZGQYjpuHw:b-xobqrh) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.h#L226)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Not sure on the name here as this is a somewhat specific. If the type were `std::unordered_map<Variable, int>` (i.e. just one variable) I would call this the `CoordinateDegreeMonomialBasis`. Given that you're doing it at the set of variables, perhaps `PartitionedCoordinateDegreeMonomialBasis`. Either way, I think the name of the method is not sufficiently descriptive for the subtle way this creates a basis.

In terms of having a more natural method, perhaps we should have the version of this method were it is just single variables, not sets of them.
</blockquote></details>

I think this is an overloaded version of `MonomialBasis`. This just gives more granularity in generating the monomial basis. 

I am not sure I like `PartitionedCoordinateDegree` or `CoordinateDegree`. I cannot infer the functionality from the name. I think if we cannot think of a concise name that conveys the functionality of the code, then it is better to use documentation to explain the functionality, rather than the name.
___
*[`common/symbolic/monomial_util.cc` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3lkit0fw4XUKGp-Hx:-Nj9HQuFDaHImapEyNGd:behqc70) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/monomial_util.cc#L54)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I sent you a PR that I think simplifies this a good bit.
</blockquote></details>

Done.

Thanks for the patch.
___
*[`common/symbolic/test/monomial_util_test.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3u8ifDB8goWJBYHOe:-Nj9IHeP1JRR5Tw6Zx_v:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L80)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would make this more arbitrary than `1`
</blockquote></details>

Done.
___
*[`common/symbolic/test/monomial_util_test.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3uCwW6TT8fdg3T2Bj:-Nj9IpCO0GVtC2BLh6J4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L85)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If you follow my above suggestion on the degree of `z_set`
</blockquote></details>

Done.
___
*[`common/symbolic/test/monomial_util_test.cc` line 101 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3uICk5fsx5aYfW7R3:-Nj9Iq62C6YQY9cQFWd4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L101)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If you follow my above suggestion on the degree of `z_set`
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`common/symbolic/test/monomial_util_test.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3u8ifDB8goWJBYHOe:-Nj9ZX4H3QLuuJwumZg_:b-kw4j05) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L80)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Not sure if you are looking at the same revision as I do. Here is what I see


So the degree for the z_set is changed to 3, and added the degree for w_set equal to 0.
___
*[`common/symbolic/test/monomial_util_test.cc` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-Nj3uCwW6TT8fdg3T2Bj:-Nj9q1WU25N5IiuS8kCI:bob5iyw) ([raw file](https://github.com/RobotLocomotion/drake/blob/d7d828ce734b4d3ee15bb066ecba9fee27736ff7/common/symbolic/test/monomial_util_test.cc#L85)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Maybe you are not checking the newest revision?

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-NjD5WJTERzTkNa-o55_:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
+@ggould-tri for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-NjDAz5x5vxPsuyGQ-5i:b-y7xxy6)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
+(release notes: feature)  :lgtm: 

> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-:-NjDH2P13V11955YCjy-:b8i1ln9)* status: 8 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.h` line 215 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDHFZS9n07yl9Iijhi:-NjDHFZT8h-A4i_QStsh:bmyun9i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L215)):*
> ```objc
> }
> 
> /** Returns all the monomials (under graded reverse lexicographic order) such
> ```

nit: awkward wording ("in order" is more conventional than "under order"; "under ... ordering" would also be appropriate)



_Suggestion:_
```objc
in
```
___
*[`common/symbolic/monomial_util.h` line 217 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDJfw0CLgZJunpXgtF:-NjDJfw1AMKQzgC_fIfa:bnh924b) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L217)):*
> ```objc
> /** Returns all the monomials (under graded reverse lexicographic order) such
>  * that the total degree for each set of variables is no larger than a specific
>  * degree. For example MonomialBasis({{x_set, 2}, {y_set, 1}}) will include all
> ```

minor:  This example is confusing because `x_set` and `y_set` are not defined in this file; you should at least mention that you're borrowing them from `monomial_util_test.cc`.
___
*[`common/symbolic/monomial_util.h` line 220 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDIcQn70rBjPlz9hxl:-NjDIcQn70rBjPlz9hxm:bqyt0u2) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L220)):*
> ```objc
>  * the monomials, whose total degree of x_set is no larger than 2, and the total
>  * degree of y_set is no larger than 1. Hence it can include monomials such as
>  * x₀x₁y₀, but not x₀y₀y₁.
> ```

minor:  I would find this clearer with a concrete example.  For instance (modulo the ordering, which I can't do in my head),



_Suggestion:_
```objc
 * x₀x₁y₀, but not x₀y₀y₁.
 *
 * For instance, `MonomialBasis({{x, y}, 1}, {{z}, 2})` will return
 * `{xzz, yzz, xz, yz, zz, x, y, z, 1}`
 * 
```
___
*[`common/symbolic/monomial_util.h` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDKlAR0RuatA524BUT:-NjDKlAR0RuatA524BUU:buqs0dn) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L225)):*
> ```objc
>  * of the degree of each variable in `vars` is no larger than `degree`.
>  * @pre The variables in `variables_degree` don't overlap.
>  * @pre The degree in `variables_degree` are non-negative.
> ```

It would be very easy to check these prerequisites in the implementation, and I think you probably should since the overlap case would be easy to hit by accident and give only subtly wrong results (silent duplicate entries in the vector).

(Alternatively, see below, line 28 of the cc file, you could remove this precondition entirely and avoid duplicate outputs regardless of duplicate inputs)
___
*[`common/symbolic/monomial_util.cc` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDLr4F5gQmZW2ym9By:-NjDLr4F5gQmZW2ym9Bz:b4l35) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.cc#L28)):*
> ```cpp
>   // and multiply these elements together. We insert the multiplied new
>   // monomial into `monomials`.
>   std::vector<Monomial> monomials;
> ```

BTW:  You could avoid the silent error on precondition violation and avoid the final sort by making this a set (since a set is just a sorted list).
(then you'd just `return std::vector<Monomial>(monomials.begin(), monomials.end());` at the end of the function) .
I expect the performance implications of incremental vs. in-place sort would be small (log(n)^2 extra comparisons in an nlog(n) procedure, plus a memcpy?) in exchange for future readers never having to think about duplicate inputs or outputs.

Author's discretion -- I'm not sure what makes more sense here, and perhaps you've already considered and rejected the set approach.



_Suggestion:_
```cpp
  std::set<Monomial, GradedReverseLexOrder<std::less<Variable>>> monomials;
```
___
*[`common/symbolic/monomial_util.cc` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDND4tBNZSqxsrE3dA:-NjDND4tBNZSqxsrE3dB:b-v18xew) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.cc#L28)):*
> ```cpp
>   // and multiply these elements together. We insert the multiplied new
>   // monomial into `monomials`.
>   std::vector<Monomial> monomials;
> ```

minor:  The word "monomial" is used a whole lot here, making this variable name uninformative.  This variable might be more clearly called "basis" or "result" since it's accumulating the basis for return.
___
*[`common/symbolic/monomial_util.cc` line 34 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDMBly6VRQkvJjXxDK:-NjDMBly6VRQkvJjXxDL:blfqoyj) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.cc#L34)):*
> ```cpp
>         return prod * (monomial_vec.rows());
>       }));
>   // Insert the 1 monomial
> ```

typo: punc complete sentence.



_Suggestion:_
```cpp
  // Insert the 1 monomial.
```
___
*[`bindings/pydrake/symbolic/test/symbolic_test.py` line 1213 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDO_EjDffrlBWoMUr7:-NjDO_EjDffrlBWoMUr8:b2xt850) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/bindings/pydrake/symbolic/test/symbolic_test.py#L1213)):*
> ```Python
>         basis5 = sym.MonomialBasis(
>             vars_degree={sym.Variables([x]): 2, sym.Variables([y]): 1})
>         self.assertEqual(basis5.size, 6)
> ```

minor:  Consider justifying this expected value.



_Suggestion:_
```Python
        self.assertEqual(basis5.size, 6)  # xxy, xx, xy, x, y, 1
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`common/symbolic/monomial_util.h` line 217 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDJfw0CLgZJunpXgtF:-NjDs2bdDTFb_BMGunKN:b-vqbdqg) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L217)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This example is confusing because `x_set` and `y_set` are not defined in this file; you should at least mention that you're borrowing them from `monomial_util_test.cc`.
</blockquote></details>

Done, I expanded the documentation.
___
*[`common/symbolic/monomial_util.h` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDKlAR0RuatA524BUT:-NjEIM7CAy3pz13cV9Fa:b-egnn7e) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.h#L225)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It would be very easy to check these prerequisites in the implementation, and I think you probably should since the overlap case would be easy to hit by accident and give only subtly wrong results (silent duplicate entries in the vector).

(Alternatively, see below, line 28 of the cc file, you could remove this precondition entirely and avoid duplicate outputs regardless of duplicate inputs)
</blockquote></details>

Good call, I added the check if the variables overlap. The prerequisites in degree >= 0 is already implemented in https://github.com/RobotLocomotion/drake/blob/86a69caa30ef4f830c5abd4e8759277aa2c7df1f/common/symbolic/monomial_util.cc#L38
___
*[`common/symbolic/monomial_util.cc` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20523#-NjDLr4F5gQmZW2ym9By:-NjE94cQ1Id0fOlZBVKX:b-mcgbhx) ([raw file](https://github.com/RobotLocomotion/drake/blob/1425fd6cee3c682a618855e517364f8120fbbca4/common/symbolic/monomial_util.cc#L28)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  You could avoid the silent error on precondition violation and avoid the final sort by making this a set (since a set is just a sorted list).
(then you'd just `return std::vector<Monomial>(monomials.begin(), monomials.end());` at the end of the function) .
I expect the performance implications of incremental vs. in-place sort would be small (log(n)^2 extra comparisons in an nlog(n) procedure, plus a memcpy?) in exchange for future readers never having to think about duplicate inputs or outputs.

Author's discretion -- I'm not sure what makes more sense here, and perhaps you've already considered and rejected the set approach.
</blockquote></details>

Done. I added the check on the overlapping variables. I think we will need to change the implementation by a lot if we want to remove this prerequisite.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20523)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Pull request merged**
