### PR TITLE
Switch from stock google_styleguide to new Drake-specific fork

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7177)

### CODE REVIEW

**Comment by ggould-tri** [comment]
For general attention of the platform review team:
+@sherm1 +@jwnimmer-tri +@sammy-tri +@SeanCurtis-TRI +@soonho-tri +@EricCousineau-TRI +@RussTedrake +@psiorx

This commit switches us to the new style guide.
This is your last opportunity to veto this plan.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-Kvbduemz-S27xkjBmkX:b77a3u2)*

**Comment by jwnimmer-tri** [comment]
I like it.  Two nits below.

FYI I am going to cross-check that all of the text made it over before a LGTM.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-Kvbg3nTATgngP_5Z1BX:-Kvbg3nTATgngP_5Z1BY:bahk9up) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/WORKSPACE#L75)):*
> ```Python
>     repository = "RobotLocomotion/styleguide",
>     commit = "8d38c5909a5ab38824d7f4566b3f3c6ae4557826",
>     sha256 = "",  # noqa
> ```

The sha256 needs to be non-empty.

---

*[drake/doc/code_review_checklist.rst, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbgGUkEEIvSotuUnYf:-KvbgGUkEEIvSotuUnYg:bgrzhq2) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/drake/doc/code_review_checklist.rst#L108)):*
> ```reStructuredText
> - Do all "plain old data" member fields have ``{}``?
> 
>   - See [our style guide](http://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization)
> ```

BTW punc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-Kvbga6OshX7ZqNResHB:bcz1w7n)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbiWyA8aJxZivUvwE_:-KvbiWyA8aJxZivUvwEa:bypw0ok) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/WORKSPACE#L72)):*
> ```Python
> 
> github_archive(
>     name = "drake_styleguide",
> ```

BTW Can we just call this `styleguide` to follow the pattern of most of our other external packages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Comment by ggould-tri** [comment]
Thanks.  It would also be nice if a clion user could check that I didn't break those instructions.

---

Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbiWyA8aJxZivUvwE_:-KvbkwCkTUKlPHT-qROg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/WORKSPACE#L72)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Can we just call this `styleguide` to follow the pattern of most of our other external packages?
</blockquote></details>

Done.

---

*[WORKSPACE, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-Kvbg3nTATgngP_5Z1BX:-KvbkiGh-hLD9pH8SNFD:b-9mf0ji) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/WORKSPACE#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The sha256 needs to be non-empty.
</blockquote></details>

Huh. surprised that was allowed!  When I wrote that I thought it would error and give me the right value to fix it.

*grumble* sentinel values *grumble*

---

*[drake/doc/code_review_checklist.rst, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbgGUkEEIvSotuUnYf:-Kvbl9A51hSPWSk_Dqz5:b-o82bts) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/drake/doc/code_review_checklist.rst#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW punc
</blockquote></details>

Done, assuming you meant the period outside the quotes on the next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KvbmURlyMoAFkRcHxO5:bf9v9p5)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 11 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-Kvbg3nTATgngP_5Z1BX:-Kvbo3d8M5GJmN-HDl9n:b-vlac9d) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/WORKSPACE#L75)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Huh. surprised that was allowed!  When I wrote that I thought it would error and give me the right value to fix it.

*grumble* sentinel values *grumble*
</blockquote></details>

OK Yup, if you had _removed_ the attribute entirely (both name and value), it would have done what you want.  I'll PR it so that empty-string has the same behavior (fails, and gives you a hint).

---

*[drake/doc/code_review_checklist.rst, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbgGUkEEIvSotuUnYf:-KvboQn2D9TLkaZRINC3:b-pv7y79) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94f7f17b731e20872ac8f2c8c6d3cb7b5e2cd/drake/doc/code_review_checklist.rst#L108)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Done, assuming you meant the period outside the quotes on the next line.
</blockquote></details>

OK Oops, I hadn't realized there was a next line.  Withdrawn.  (I'm with with either period placement.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-Kvbs_vu8uP1oDFj9CAZ:bnfp4nl)*

**Comment by sherm1** [comment]
A few of the links don't work because they are in Markdown rather than Sphinx syntax. Otherwise, :lgtm: and thank you very much!

---

Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbzJ4jSaUUt3r1WZKZ:-KvbzJ4jSaUUt3r1WZK_:bf8fy4l) ([raw file](https://github.com/robotlocomotion/drake/blob/74a258ace230eaf661623ab5c170865638a2ef28/drake/doc/code_review_checklist.rst#L108)):*
> ```reStructuredText
> - Do all "plain old data" member fields have ``{}``?
> 
>   - See [our style guide](http://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization)
> ```

BTW this link is in Markdown syntax rather than Sphinx and doesn't format correctly.

---

*[drake/doc/code_style_guide.rst, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-Kvbz0XQZJr94_D4Pmjk:-Kvbyw_bSyITikUNwcCx:b-r4h4bf) ([raw file](https://github.com/robotlocomotion/drake/blob/74a258ace230eaf661623ab5c170865638a2ef28/drake/doc/code_style_guide.rst#L30)):*
> ```reStructuredText
> 
> The Drake C++ style guide (which is derived from the Google C++ style guide)
> can be found [here](http://drake.mit.edu/styleguide/cppguide.html).  Its
> ```

BTW this link is in Markdown syntax rather than Sphinx and doesn't format correctly (also the one below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KvbzRX0gp1yDMe188Nf:bp0zk4g)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-KvbzJ4jSaUUt3r1WZKZ:-Kvc0-b29b2GU3eNXlaa:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/74a258ace230eaf661623ab5c170865638a2ef28/drake/doc/code_review_checklist.rst#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this link is in Markdown syntax rather than Sphinx and doesn't format correctly.
</blockquote></details>

Done. Oops!

---

*[drake/doc/code_style_guide.rst, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-Kvbz0XQZJr94_D4Pmjk:-Kvc2pNkre9dsYYHNp1B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74a258ace230eaf661623ab5c170865638a2ef28/drake/doc/code_style_guide.rst#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this link is in Markdown syntax rather than Sphinx and doesn't format correctly (also the one below).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-Kvc3TL-6H23WRRsLq3E:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:
(Tested `Cpplint File` - works fine!)

---

Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KvcFSFe9vUTs8zWJJ-V:b4si095)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 8 of 9 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KviHIjEVm29WVfnQ1mS:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KviLgljq-PuPBI2Dk07:bnfp4nl)*

**Comment by ggould-tri** [comment]
Absent new comments I will dismiss remaining reviewers and merge at the end of today.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-KvmtJcvX7tGaJ0NIudG:b-mbdptn)*

**Comment by ggould-tri** [comment]
-@SeanCurtis-TRI -@psiorx 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177#-:-Kw0QBSLVZGhZb27PDtN:by2o6y9)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7177)*

**Pull request merged**
