### PR TITLE
doc: Generate a minimal sitemap of HTML files

### LINKED ISSUE #14733: Generate a sitemap at the end of //doc:build
Does not even need to be XML (though that would not be difficult). Google are happy enough with a simple list of absolute URL's one per line in a text file.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #14733 and makes the googlebot a little less sad.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jamiesnape)

___
*[doc/build.py, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqQkY7AfXtG6oI8oDj:-MVqQkY7AfXtG6oI8oDk:b-o2zzt6) ([raw file](https://github.com/robotlocomotion/drake/blob/75c01af47555fc106bcc1c645da9e304b580b39a/doc/build.py#L59)):*
> ```Python
>     # instead of having it be a separate pipeline.
> 
>     if args.sitemap:
> ```

I'm not sure why this is toggleable on the command line?  It doesn't seem to take very long to run, at least not compared to Doxygen or Sphinx. I guess there's nothing wrong with offering the option, though.

However, if we do have an option, then the defaults for this script should be the same as the website deploy itself, i.e., the command line argument should be opt-out, not opt-in.
___
*[doc/build.py, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqS9wKEZByPx0Gg_Q4:-MVqS9wL4ZiYl0K1wBqG:byutcv2) ([raw file](https://github.com/robotlocomotion/drake/blob/75c01af47555fc106bcc1c645da9e304b580b39a/doc/build.py#L59)):*
> ```Python
>     # instead of having it be a separate pipeline.
> 
>     if args.sitemap:
> ```

nit I am fine either way, but it's possible that factoring this logic into a private helper function within this file would end up being clearer for future readers?
___
*[doc/build.py, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqUAEJ7VurDASpf6Ff:-MVqUAEJ7VurDASpf6Fg:b-1kcqa7) ([raw file](https://github.com/robotlocomotion/drake/blob/75c01af47555fc106bcc1c645da9e304b580b39a/doc/build.py#L85)):*
> ```Python
>             loc.text = location
>         sitemap = ET.ElementTree(urlset)
>         sitemap.write("sitemap.xml",
> ```

This is currently scribbling the sitemap into the runfiles cwd.  It should be writing to `out_dir` instead.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/build.py, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqQkY7AfXtG6oI8oDj:-MVqudKiD40i2qmSKn-5:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/75c01af47555fc106bcc1c645da9e304b580b39a/doc/build.py#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure why this is toggleable on the command line?  It doesn't seem to take very long to run, at least not compared to Doxygen or Sphinx. I guess there's nothing wrong with offering the option, though.

However, if we do have an option, then the defaults for this script should be the same as the website deploy itself, i.e., the command line argument should be opt-out, not opt-in.
</blockquote></details>

Removed.
___
*[doc/build.py, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqUAEJ7VurDASpf6Ff:-MVqup-d96-g982cZSJI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75c01af47555fc106bcc1c645da9e304b580b39a/doc/build.py#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is currently scribbling the sitemap into the runfiles cwd.  It should be writing to `out_dir` instead.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778#-:-MVqvOQbDjqbHglNtoRx:b-adicrb)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @jamiesnape)

___
*[doc/build.py, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqyGKD-ipCM35ZcVnw:-MVqyGKED3RtdlikzANg:b-czw28w) ([raw file](https://github.com/robotlocomotion/drake/blob/1d26b2c8320df4b30296c2dff005e028d4a179a7/doc/build.py#L100)):*
> ```Python
>             loc.text = location
>         sitemap = ET.ElementTree(urlset)
>         sitemap.write(os.path.join(site_dir, "sitemap.xml"),
> ```

I don't know what to expect from Jekyll for this, or how to confirm locally w/ how it's served.

Should it be served by the website preview?
I get a 404 here: `http://127.0.0.1:8000/sitemap.xml`

```
$ git log -n 1 --oneline --no-decorate
1d26b2c832 doc: Generate a minimal sitemap of HTML files
$ bazel run //doc:serve_jekyll
...
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @jamiesnape)

___
*[doc/build.py, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqyGKD-ipCM35ZcVnw:-MVqyt7HBxBVUN2LztcS:b-9dbmcc) ([raw file](https://github.com/robotlocomotion/drake/blob/1d26b2c8320df4b30296c2dff005e028d4a179a7/doc/build.py#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't know what to expect from Jekyll for this, or how to confirm locally w/ how it's served.

Should it be served by the website preview?
I get a 404 here: `http://127.0.0.1:8000/sitemap.xml`

```
$ git log -n 1 --oneline --no-decorate
1d26b2c832 doc: Generate a minimal sitemap of HTML files
$ bazel run //doc:serve_jekyll
...
```
</blockquote></details>

I also tried looking at generation, cannot see it:
```
$ rm -rf /tmp/website && bazel run //doc:gen_jekyll -- --out_dir=/tmp/website && cat /tmp/website/sitemap.xml
...
cat: /tmp/website/sitemap.xml: No such file or directory
```

Please add a unittest which matches your expectations for deployment.

**Comment by jamiesnape** [comment]
No, because it needs the whole website, not just the Jekyll part. `bazel run //doc:build -- --out_dir <out_dir>`.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @jamiesnape)

___
*[doc/build.py, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqyGKD-ipCM35ZcVnw:-MVqzA-eDMNAC6CPtQ1y:b-b9z2tc) ([raw file](https://github.com/robotlocomotion/drake/blob/1d26b2c8320df4b30296c2dff005e028d4a179a7/doc/build.py#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I also tried looking at generation, cannot see it:
```
$ rm -rf /tmp/website && bazel run //doc:gen_jekyll -- --out_dir=/tmp/website && cat /tmp/website/sitemap.xml
...
cat: /tmp/website/sitemap.xml: No such file or directory
```

Please add a unittest which matches your expectations for deployment.
</blockquote></details>

Ah, `build.py`:
```
For now, this tool is only intended to be used by Drake's CI tooling.  In the
future, we will enhance and document it for developer use.
```

For the future, please minimize burden on reviewers by making this more evident.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/build.py, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14778#-MVqyGKD-ipCM35ZcVnw:-MVqzHAr654fE_uwxDe1:b1xqh1) ([raw file](https://github.com/robotlocomotion/drake/blob/1d26b2c8320df4b30296c2dff005e028d4a179a7/doc/build.py#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, `build.py`:
```
For now, this tool is only intended to be used by Drake's CI tooling.  In the
future, we will enhance and document it for developer use.
```

For the future, please minimize burden on reviewers by making this more evident.
</blockquote></details>

(i.e. state the command that should be run)

**Comment by jamiesnape** [comment]
That was pre-existing, I do not think I need to point out the rest of the file.

**Comment by EricCousineau-TRI** [comment]
aye. but providing a command to run to match expecations?

**Comment by EricCousineau-TRI** [comment]
(running it now)

**Comment by jamiesnape** [comment]
Then that is a defect with the original PR of this file, I have no idea? We have to write command lines ad infinitum every time we change a binary?

**Comment by jwnimmer-tri** [comment]
As feature reviewer, I was completely clear on the desired outcome and how to test it locally (which I did).

In general, I do not expect platform reviewers to locally test documentation PRs -- I see local testing as the responsibility of the feature reviewer (for all PRs which require manual testing, not just documentation ones).

If the tool's instructions are unclear, then the solution is not to paste the commands into every PR, but rather to fix https://drake.mit.edu/documentation_instructions.html to address any confusion.

I have a rewrite of the doc tooling underway, which (in part) will make the commands more uniform and clear.
https://github.com/jwnimmer-tri/drake/commits/doc-mv-sphinx

This is not to cast blame but rather just share my thought process.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14778)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @jamiesnape)

**Comment by EricCousineau-TRI** [comment]
> In general, I do not expect platform reviewers to locally test documentation PRs -- I see local testing as the responsibility of the feature reviewer (for all PRs which require manual testing, not just documentation ones).

Aye. In my mind, platform reviewer is meant to double-check testing that is done; in this case, there was no unittest, nor was evidence of your testing apparent in the transcript (not a big deal, but why I decided to redo it).
Just a mismatch of expectations? (Maybe I didn't read the paltform reviewer docs closely enough?)

**Comment by EricCousineau-TRI** [comment]
Skipping slow build

**Comment by jwnimmer-tri** [comment]
> ..., nor was evidence of your testing apparent in the transcript (not a big deal, but why I decided to redo it).

That's fine.  I could have mentioned that I tested locally, for better clarity.  You also could have asked me whether I did, to save yourself some time.

**Pull request merged**
