### PR TITLE
[parsing] Rename directives files to .dmd.yaml

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This is preparation for supporting directives files within the main
Parser interface.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri for review.
+(status: single reviewer ok) 
+(release notes: none) 

Relevant to: #17390.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9gPjN8-pNXJaCF9C44:b-fcf274)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Does this properly deserve no release notes? You've changed the names of files in `manipulation/`. Those in `test/` and `examples/` are, of course, irrelevant. But the ones in `manipulation/`?  Specifically, `home_cart*.dmd.yaml`. Those files only got added five weeks ago, but this would constitute a change from one release to another in installed files.

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9gyPVR581MkrmoqGBV:btvvjjp)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
My perhaps-rash claim is that model files are not part of stable api: https://drake.mit.edu/stable.html

To be fair, I haven't tried to build anzu against this, so practical breakage might override any documented policy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9h24e1585syVqrSP7K:b-xgue87)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
I agree it's not a breaking change, since the files are not stable.  It's still a _notable_ change, since users may be impacted by it.

**Review by rpoyner-tri — COMMENTED** [review]
I've started an integration build job--we can wait and see what that says.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9h2ra-3298iC63_8lj:bu02zgx)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I buy the "not breaking, but notable".  Fix?

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9h3J5XBg3UW-KmQXK7:bqu3uzz)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: none) +(release notes: fix) 
Note to release manager: this patch changes file names which may be visible to downstream projects, but are not part of stable api. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733#-:-N9h3-pg390cjAgpi9Bd:b-o36sav)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17733#-N9h3kqU6v1X_DcL6uK-:-N9h3kqU6v1X_DcL6uK0:b-fjxapl) (no related file):*
I'll wait for the anzu integration experiment to complete -- there may at least be more to write as notes here.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17733)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17733#-N9h3kqU6v1X_DcL6uK-:-N9hNQQt6l_TM6k6q4IP:b-w833v) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll wait for the anzu integration experiment to complete -- there may at least be more to write as notes here.
</blockquote></details>

build experiment was clean success.

___

**Pull request merged**
