### PR TITLE
Contact point tracking

### PR DESCRIPTION
**Pull request by edrumwri**
This data structure is to be used for augmenting abstract state variables for rigid contact between bodies with polytopic geometries for use with the "active set method" (no relation to constrained optimization or mathematical programming).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6618)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6618#-:-KpXAmPSac3fILUDbmwa:b1tu4a9)*

**Comment by sherm1** [comment]
Per f2f I'll hold off reviewing this.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6618#-:-KpaoIsNZ-0pyHS-BVHV:b-jjy1ok)*

**Comment by sherm1** [comment]
One comment below, but it makes me wonder if this is being used anywhere. If not, would it make sense to hold off on this code until there is some context for it? Or is there a design doc somewhere of which this is a part? It is hard for me to see how it is going to be used or why it is designed this way. For example, there is an implication here I think that you only track contacts that are currently occurring, since there is no state "not in contact". That implies no tracking prior to contact, so I guess the signed distance witnesses are handled by some unrelated means? And no tracking after contact so this would not be used to collect impulse results after an elastic impact. No complaints assuming you're dealing with those things elsewhere but it is hard to review with no context.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_contact/rigid_contact_point.h, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6618#-KpqyisnK6e2CfNSTUNN:-KpqyisnK6e2CfNSTUNO:btl5zub) ([raw file](https://github.com/robotlocomotion/drake/blob/87c5fd5cac77512e1d460eed54070d1b31f9b0f2/drake/multibody/rigid_contact/rigid_contact_point.h#L36)):*
> ```objc
>   /// discrete state variables) to uniquely determine a point of contact between
>   /// two rigid bodies.
>   systems::Value<T> contact_point_key;
> ```

This isn't a type-erased AbstractValue. It is just one of the scalars T (double, AutoDiff or whatever). Did you want something abstract? If not, this data member should just be type T.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6618#-:-Kpqz83VM1aNtwIXsdDZ:b-fvcsyu)*

**Comment by edrumwri** [comment]
Closing this PR for now due to changes in objectives.

**Pull request closed without merging**
