### PR TITLE
bind QuadraticErrorCost

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8363)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri for both reviews, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8363#-:-L7Z50gvlN6_AB80FMgX:b-qb6q7i)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With a couple of pybindy, formatty things. I haven't played much in the pybind code so my comments may come from ignorance. Your call.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 247 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8363#-L7ZxvoR5AN1bLv9rBh6:-L7ZxvoSDFF_Egt6HD2I:b-alhm67) ([raw file](https://github.com/robotlocomotion/drake/blob/e3d0b8d3a520723c176149281e67733d5cc6ec9e/bindings/pydrake/solvers/mathematicalprogram_py.cc#L247)):*
> ```cpp
>                const Eigen::Ref<const Eigen::VectorXd>&,
>                const Eigen::Ref<const VectorXDecisionVariable>&>
>                (&MathematicalProgram::AddQuadraticErrorCost),
> ```

FYI Is this clang-format happy? I'm a bit surprised to see the opening parenthesis on the next line.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 68 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8363#-L7Zy0L_7BkIj-FPcpKd:-L7Zy0L_7BkIj-FPcpKe:bcaqlti) ([raw file](https://github.com/robotlocomotion/drake/blob/e3d0b8d3a520723c176149281e67733d5cc6ec9e/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L68)):*
> ```Python
>         prog.AddQuadraticCost(np.eye(2), np.zeros(2), x)
>         # Redundant cost just to check the spelling.
>         prog.AddQuadraticErrorCost(np.eye(2), np.zeros(2), x)
> ```

FYI Given that you've explicitly used `py::arg`, you've implied something about the binding that isn't tested. Would it be better to have this test use the parameter names in a jumbled order to make sure that the bound behavior is enforced in testing?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8363#-:-L7ZyEJsEFK8AHez50_L:b-1b0xgo)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 247 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8363#-L7ZxvoR5AN1bLv9rBh6:-L7avOVe-XMwoEtYPAJh:bx6i38b) ([raw file](https://github.com/robotlocomotion/drake/blob/e3d0b8d3a520723c176149281e67733d5cc6ec9e/bindings/pydrake/solvers/mathematicalprogram_py.cc#L247)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Is this clang-format happy? I'm a bit surprised to see the opening parenthesis on the next line.
</blockquote></details>

can't run clang-format on this file (#8329).  but i've fixed this paren.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8363#-L7Zy0L_7BkIj-FPcpKd:-L7awWwmwItcplm_AOrU:b-ruq6wp) ([raw file](https://github.com/robotlocomotion/drake/blob/e3d0b8d3a520723c176149281e67733d5cc6ec9e/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L68)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Given that you've explicitly used `py::arg`, you've implied something about the binding that isn't tested. Would it be better to have this test use the parameter names in a jumbled order to make sure that the bound behavior is enforced in testing?
</blockquote></details>

we've not done that before.  but i agree with your point.  done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8363)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8363)*

**Pull request merged**
