### PR TITLE
Example use of GenerateExportHeader to clean up DLLEXPORTs

### PR DESCRIPTION
**Pull request by tkoolen**
Found out that CMake has a [GenerateExportHeader](https://cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html) module. This contains the generate_export_header function, which generates a header file for a library that contains the right 'DLLEXPORT' macro. You can then just include the header in the library header files and use the macro.

I added an add_library_with_exports CMake function that makes using this really easy. Basically, replace e.g.
```
add_library(drakeCollision SHARED ${drakeCollision_SRC_FILES})
```
with
```
add_library_with_exports(LIB_NAME drakeCollision SOURCE_FILES ${drakeCollision_SRC_FILES})
```

The header files will be put in `${PROJECT_BINARY_DIR}/exports`.

Using this everywhere would resolve https://github.com/RobotLocomotion/drake/issues/576.

### CODE REVIEW

**Comment by tkoolen** [comment]
I suspect that the compilation errors are due to https://cmake.org/Bug/view.php?id=12645, which was fixed in cmake 2.8.8. I don't suppose we could upgrade our minimum cmake version?

**Comment by tkoolen** [comment]
I think I found a workaround.

**Comment by RussTedrake** [comment]
Our cmake version is constrained by what people can apt-get install on ubuntu (12.04).   To increase the min version, we need a very simple install line replacement.

**Comment by tkoolen** [comment]
Workaround seems to be working. For reference, up to 2.8.7 absolute paths don't work as the EXPORT_FILE_NAME argument of generate_export_header, only paths relative to ${CMAKE_CURRENT_BINARY_DIR}.

**Comment by tkoolen** [comment]
Alright, so should I convert everything to use this?

**Comment by RussTedrake** [comment]
I’m ok with it.  Would be cleaner.



On December 13, 2015 at 1:47:27 PM, Twan Koolen (notifications@github.com) wrote:

Alright, so should I convert everything to use this?

**Pull request merged**
