### PR TITLE
Add tag "no_ubsan" to all tests which use protobuf.

### PR DESCRIPTION
**Pull request by clalancette**
This is due to a bug in Protobuf 2.6; it is described in
more detail in the TODO comment in the code.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7636)

### CODE REVIEW

**Comment by clalancette** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-ubsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Comment by clalancette** [comment]
I have fixes for the linting errors that will come up here, but I'm going to wait to push them until the current tests (particularly ubsan) run.

**Comment by clalancette** [comment]
UBSan was happy, great.  I just pushed my linting fixes, so this should be ready for review.

**Comment by clalancette** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7636#-:-L0gH7R2qPTO30Ur-2ZF:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7636#-:-L0hSLBG4PXruGrD_Eyw:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For the record: follow-up issue was already filed as #7638.

**Pull request merged**
