### PR TITLE
Marked additional header files for installation.

### LINKED ISSUE #2659: Certain Drake Header Files Not Being Installed
The following header files are not being installed into `drake-build/install/include/`:

1. `drake/solvers/Constraint.h`
2. `drake/solvers/solution_result.h`
3. `systems/plants/pose_map.h`

This prevents external projects that rely on Drake as an external from including these header files. I discovered this while trying to compile the benchmark in https://github.com/RobotLocomotion/drake/issues/2656.

### PR DESCRIPTION
**Pull request by jhoare**
Fixes #2659 as well as allows the Cars Example to be used by an external project.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2700)

### CODE REVIEW

**Comment by jhoare** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/CMakeLists.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLSLlqf4XQcoaLB-uVi:-KLSLlqf4XQcoaLB-uVj:-430857597) ([raw file](https://github.com/robotlocomotion/drake/blob/706a4bb756ad8318702d24a85dcc08bc03003f32/drake/systems/plants/CMakeLists.txt#L28)):*
> ```CMake
> pods_install_libraries(drakeRBM)
> drake_install_headers(
>   BotVisualizer.h
> ```

Is it correct to include all of these header files for installation? Or should some NOT be installed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700)*

**Comment by jwnimmer-tri** [comment]
Partial review done; I have to step away.

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLSdIRX1HZ-M454YssL:-KLSdIRX1HZ-M454YssM:86485751) ([raw file](https://github.com/robotlocomotion/drake/blob/706a4bb756ad8318702d24a85dcc08bc03003f32/drake/common/CMakeLists.txt#L17)):*
> ```CMake
>   drake_deprecated.h
>   nice_type_name.h
>   eigen_types.h
> ```

Please alpha-sort above `nice_type_name`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-:-KLSdpDE5FpH0l6wOSvD:-1909811173)*

**Comment by liangfok** [comment]
Done with initial review.

---

Reviewed 7 of 7 files at r1, 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/CMakeLists.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLSLlqf4XQcoaLB-uVi:-KLSh0W9nOaRUrAVGbNz:1767368396) ([raw file](https://github.com/robotlocomotion/drake/blob/706a4bb756ad8318702d24a85dcc08bc03003f32/drake/systems/plants/CMakeLists.txt#L28)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> Is it correct to include all of these header files for installation? Or should some NOT be installed?
</details>
I'm tempted to say that all of these header files should be installed since they appear in [Drake's Doxygen-generated API](http://drake.mit.edu/doxygen_cxx/index.html). Maybe once we settle on a Release 1.0 API, we can scale back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-:-KLSk2FWfqv_3pHKWo-c:2062893049)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-:-KLSkM8qfJ-PBSPwwB2y:-1868698381)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700)*

**Comment by jhoare** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/common/CMakeLists.txt, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLSdIRX1HZ-M454YssL:-KLSfmcdp0AYBSlD811_:676635175) ([raw file](https://github.com/robotlocomotion/drake/blob/706a4bb756ad8318702d24a85dcc08bc03003f32/drake/common/CMakeLists.txt#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please alpha-sort above `nice_type_name`.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/CMakeLists.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLSLlqf4XQcoaLB-uVi:-KLTaBqx8NEL6S2Cbf4z:230606639) ([raw file](https://github.com/robotlocomotion/drake/blob/706a4bb756ad8318702d24a85dcc08bc03003f32/drake/systems/plants/CMakeLists.txt#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'm tempted to say that all of these header files should be installed since they appear in [Drake's Doxygen-generated API](http://drake.mit.edu/doxygen_cxx/index.html). Maybe once we settle on a Release 1.0 API, we can scale back.
</details>
I'm not sure that's the best metric to use, though I can't articular a better one.  For now I'll just do an ad-hoc review and evict a few (noted below).

---

*[drake/systems/plants/CMakeLists.txt, line 30 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLTa3aId5GP54x2Utha:-KLTa3aJhgXDZCwf4-YP:-644425027) ([raw file](https://github.com/robotlocomotion/drake/blob/841049ca17c7dacb26fe8a3ea50bf8a59b3af6ef/drake/systems/plants/CMakeLists.txt#L30)):*
> ```CMake
>   BotVisualizer.h
>   ConstraintWrappers.h
>   eiquadprog.h
> ```

Please remove this from the install list.

---

*[drake/systems/plants/CMakeLists.txt, line 43 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLTaZeM43dD_SO5QsNi:-KLTaZeM43dD_SO5QsNj:-104197815) ([raw file](https://github.com/robotlocomotion/drake/blob/841049ca17c7dacb26fe8a3ea50bf8a59b3af6ef/drake/systems/plants/CMakeLists.txt#L43)):*
> ```CMake
>   RigidBodySystem.h
>   RigidBodyTree.h
>   rigidBodyTreeMexConversions.h
> ```

This is internal (mex means matlab support), so should be removed from the install list.

---

*[drake/systems/plants/CMakeLists.txt, line 44 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLTacPBbKhBOPP-VXUh:-KLTacPBbKhBOPP-VXUi:-104197815) ([raw file](https://github.com/robotlocomotion/drake/blob/841049ca17c7dacb26fe8a3ea50bf8a59b3af6ef/drake/systems/plants/CMakeLists.txt#L44)):*
> ```CMake
>   RigidBodyTree.h
>   rigidBodyTreeMexConversions.h
>   rigidBodyTreeMexFunctions.h
> ```

This is internal (mex means matlab support), so should be removed from the install list.

---

*[drake/util/CMakeLists.txt, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLT_e6ierp1tE7RcIgb:-KLT_e6jJ5x-2Y4AosRn:1970340494) ([raw file](https://github.com/robotlocomotion/drake/blob/841049ca17c7dacb26fe8a3ea50bf8a59b3af6ef/drake/util/CMakeLists.txt#L37)):*
> ```CMake
> 
> drake_install_headers(drakeAppUtil.h)
> pods_install_pkg_config_file(drake-app-util
> ```

I don't know that this is accomplishing anything useful.  I think the future of `drakeAppUtil.h` is to either be deleted, or moved to `common`.  I'm not sure laying down groundwork for shipping a binary library here is useful (if that's indeed what this is doing)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700)*

**Comment by jhoare** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/util/CMakeLists.txt, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-KLT_e6ierp1tE7RcIgb:-KLvHUXiaH7hzPZi6cOl:1189881238) ([raw file](https://github.com/robotlocomotion/drake/blob/841049ca17c7dacb26fe8a3ea50bf8a59b3af6ef/drake/util/CMakeLists.txt#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't know that this is accomplishing anything useful.  I think the future of `drakeAppUtil.h` is to either be deleted, or moved to `common`.  I'm not sure laying down groundwork for shipping a binary library here is useful (if that's indeed what this is doing)?
</details>
It will generate a pkg-config file, but it's probably not necessary for only a header. I only put it in because everything else in the directory had one (but they were also building libraries, whereas this is header only.) I've removed it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jhoare** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-:-KLwN4HcggeSVXu-f26k:1417088721)*

**Comment by liangfok** [comment]
Just waiting on this to pass CI now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2700#-:-KLwPnSDgueeWeROSR-C:1366003909)*

**Comment by jhoare** [comment]
Looks like failure was a false negative?

@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Now that I look at this more carefully, I see that `RigidBodySystem.h` and `RigidBodyIK.h IKoptions.h` were already listed separately in `CMakeLists.txt`, so should not have been added again in this PR.

Relatedly, it looks like the meme is to list the headers near their library, so things like the `xmlUtil.h` should be in a separate group that the `RigidBody*` stuff.

**Comment by jhoare** [comment]
Okay, I'll make a new PR.

**Pull request merged**
