### PR TITLE
rbtree_py: Add dynamics methods.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7901)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@naveenoid for feature review, please.
+@sammy-tri for platform review, please.

For now, the tests are in `rbt_com_test`. I'd like to generalize this test, but I'd like to defer that to #7900.

\cc @russtedrake @gizatt @peteflorence

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-:-L43i6m0ILUHlckHFsMa:bya21oz)*

**Comment by sammy-tri** [comment]
One minor comment on test coverage, otherwise :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/rbtree_py.cc, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-L46QDUO2CsDaMABOXyL:-L46QDUPbKWfa7Tw9GAx:bsnj8yf) ([raw file](https://github.com/robotlocomotion/drake/blob/4cabd17d707fa338aed770bfa56529eec8b67221/bindings/pydrake/rbtree_py.cc#L201)):*
> ```cpp
>          py::arg("vd"),
>          py::arg("include_velocity_terms") = true)
>     .def("frictionTorques",
> ```

The other methods got existence tests, but this one didn't, which seems a bit odd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-:-L46QMOm3xFTBm3-_fLO:bi48re4)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/rbtree_py.cc, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-L46QDUO2CsDaMABOXyL:-L46rCUdvuHmqNHXkYTx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cabd17d707fa338aed770bfa56529eec8b67221/bindings/pydrake/rbtree_py.cc#L201)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The other methods got existence tests, but this one didn't, which seems a bit odd.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7901)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-:-L47JLpO6E9M11VC9gRv:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm: fine.fine.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7901#-:-L47jZsCBccPC8JD0Jpm:b-q2hp01)*

**Pull request merged**
