### PR TITLE
[render] Removes unused class in geometry/render

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The `RenderLabelClass` was a leftover artifact from a previous implementation of rendering. It should have gone away with the `RenderLabelManager` back in PR #11593.

Because it's in `drake::geometry::internal` no deprecation and no note of its passing is necessary.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15777)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) +@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15777#-:-Mjij2v17EsunYbGVI0o:b-r9i9wm)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: and that, my friends, is the magic of `internal`.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15777#-:-Mjj7uimBENwcIxG6y45:b-95nq4u)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@rpoyner-tri how do you feel about single reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15777#-:-MjjqmdhCRhNBKHR6Iqf:bjsl0xf)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15777#-:-MjjzHsl86_8VKBRfZKW:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
