### PR TITLE
SnoptSolver respects CommonSolverOption::kPrintFileName

### PR DESCRIPTION
**Pull request by hongkai-dai**
Relates to #12867 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-Mfd5sNfD5mQaJc2zDXq:b-j3v9j6)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[solvers/snopt_solver.cc, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MfeRsFN8XK0E3TtTmp0:-MfeRsFN8XK0E3TtTmp1:bw3p1wd) ([raw file](https://github.com/robotlocomotion/drake/blob/0cef51c08debef432a78f2a36de77a7a1ab55925/solvers/snopt_solver.cc#L1032)):*
> ```cpp
> 
>   std::string print_file_name;
>   if (print_file_common != "") {
> ```

nit This "if" guard here has no effect.  The following change is exactly the same, without the extra complexity:

```c++
std::string print_file_name = print_file_common;
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[solvers/snopt_solver.cc, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MfeRsFN8XK0E3TtTmp0:-MffHK9z8GTDKoKfFoec:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0cef51c08debef432a78f2a36de77a7a1ab55925/solvers/snopt_solver.cc#L1032)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This "if" guard here has no effect.  The following change is exactly the same, without the extra complexity:

```c++
std::string print_file_name = print_file_common;
```
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
One requested expansion of the test.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-MfhNybg4v6Z6d0olb5q:b-tvfop6)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/test/snopt_solver_test.cc, line 161 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MfhNlzy4szZ3_BB9ne-:-MfhNlzy4szZ3_BB9ne0:bnjtco5) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea07ade3b1b88f1141ab949e5f36185c279c464/solvers/test/snopt_solver_test.cc#L161)):*
> ```cpp
>   result = solver.Solve(prog, {}, solver_options2);
>   EXPECT_TRUE(result.is_success());
>   EXPECT_TRUE(filesystem::exists({print_file_common}));
> ```

nit:  You've also got a protocol -- when both are set, the solver-specific options should win out. You should test the scenario where *both* are set.

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW It would be a help to others if you put:

`relates #12867` in the PR summary. It'll keep issues and PRs nicely associated with each other. I've edited the issue to make explicit reference to this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-MfhOMf319UiyxyQTBrz:b-fi66a8)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Done. I edited the commit message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-Mfi2FTuBkhVBADkpW1B:b-wgtyti)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[solvers/test/snopt_solver_test.cc, line 161 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MfhNlzy4szZ3_BB9ne-:-Mfi2QzmDgLrNWzZh7B2:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/0ea07ade3b1b88f1141ab949e5f36185c279c464/solvers/test/snopt_solver_test.cc#L161)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit:  You've also got a protocol -- when both are set, the solver-specific options should win out. You should test the scenario where *both* are set.
</blockquote></details>

Done, good call.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: 

+@sammy-tri for platform review, please.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-Mfid78ZB3gNppr_vQAl:b-b01v0j)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @sammy-tri)

___
*[solvers/test/snopt_solver_test.cc, line 163 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MficnM8-NVnjPGTlTam:-MficnM8-NVnjPGTlTan:b-xw7x) ([raw file](https://github.com/robotlocomotion/drake/blob/5ff2ba901a70c3d662bda01f3bdf8bd0a74b52b7/solvers/test/snopt_solver_test.cc#L163)):*
> ```cpp
>   EXPECT_TRUE(filesystem::exists({print_file_common}));
> 
>   // Now set the solver option with both CommonSolverOption and solver specific
> ```

BTW Something to consider in the future. Rather than un-`const`-ing the strings, you could surround each otherwise independent test in its own block (`{ ... test code .. }`). Then you can simply re-use the name from block to block without collision and enumerations.

It also helps enforce the separation of the sub-tests; one can't accidentally get values that the other set.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493#-:-Mfimixr74HUGIaCKC-2:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @sammy-tri and @SeanCurtis-TRI)

___
*[solvers/test/snopt_solver_test.cc, line 163 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15493#-MficnM8-NVnjPGTlTam:-MfnCW_38JGlEehST4yk:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/5ff2ba901a70c3d662bda01f3bdf8bd0a74b52b7/solvers/test/snopt_solver_test.cc#L163)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Something to consider in the future. Rather than un-`const`-ing the strings, you could surround each otherwise independent test in its own block (`{ ... test code .. }`). Then you can simply re-use the name from block to block without collision and enumerations.

It also helps enforce the separation of the sub-tests; one can't accidentally get values that the other set.
</blockquote></details>

Done. Good call.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15493)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
