### PR TITLE
Enable Quadrotor example on Windows

### PR DESCRIPTION
**Pull request by sherm1**
The CMake file for the Quadrotor example prevented it from building on Windows. I removed that and both C++ executables it creates seemed to work so I'm submitting this PR in case the no-Windows guard was there for historical reasons only. Please close if there was another reason that I missed.

### CODE REVIEW

**Comment by RussTedrake** [comment]
looks vestigial (now that we build lcm, etc on win32).  good catch!

**Comment by sherm1** [comment]
Hmmm ... appveyor [failed to build LCM](https://ci.appveyor.com/project/RussTedrake/drake/build/1.0.480/job/wuwuc4x08st24m5c#L5219) apparently because `make` wasn't found. Doesn't seem likely to have been caused by Quadrotor -- any ideas?

**Comment by RussTedrake** [comment]
That's been resolved now.  Close and reopen  to retrigger the CI

**Comment by RussTedrake** [comment]
@jhoare -- looks like appveyor is still not finding make?

**Comment by jhoare** [comment]
It looks like changes I made to appveyor.yaml in #1819 are not being used here? It is still provisioning pkg-config the old way and not using chocolatey. 

From the appveyor log:
```(new-object net.webclient).DownloadFile('https://s3.amazonaws.com/drake-provisioning/pkg-config.exe', 'c:\pkg-config.exe')``` 

I would suggest to rebase against current master and see if that works around the problem. The issue seems to be with where appveyor is getting the appveyor.yml to provision the test machine from. We would want it to be the result of the merge of the pull request and master, but it may just be getting it from the pull request?

**Comment by RussTedrake** [comment]
Ah.  If you're right, then that's potentially a serious issue with the CI logic (i had that bug in my own build scripts at one point).

@billhoffman, @jamiesnape - can you confirm what the build servers are doing?

**Comment by jhoare** [comment]
It appears that it is using the appveyor.yaml from the pull request, which in this pull request is the version before I changed it. It looks like after the machine is provisioned by appveyor, the pull request is merged into master and then built, since it is getting the lcm pod that requires ``make`` but not the provisioning yaml file that has ``make``.

I created a question on appveyor's support page as well:

http://help.appveyor.com/discussions/problems/4263-appveyoryaml-changes-and-pull-requests

**Comment by RussTedrake** [comment]
Thanks.  (I was confused for a min but realize now that this is only about appveyor, not jenkins)

**Comment by sherm1** [comment]
@jhoare, thanks -- I merged the current master into this branch so the builds should pick up the new appveyor yaml. (Rebasing into an existing PR made me nervous.)

**Comment by jhoare** [comment]
Looks like builds are still failing due to bot_core_lcmtypes #1830

**Comment by sherm1** [comment]
I'm going to close this PR and resubmit against a fork that has the repaired history.

**Pull request closed without merging**
