### PR TITLE
Add Formula::Substitute

### PR DESCRIPTION
**Pull request by soonho-tri**
Close https://github.com/RobotLocomotion/drake/issues/4877

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5029)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@david-german-tri , platform-review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc-qkHDHFgvemN59Z2Y:bk31q4v)*

**Comment by ggould-tri** [comment]
-@david-german-tri +@ggould-tri 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc45ccQ1mxciGsKR14f:bpgd2sk)*

**Comment by soonho-tri** [comment]
@ggould-tri , thank you!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc45dxLUBpnduL5xBlb:b-53vxm3)*

**Comment by ggould-tri** [comment]
:lgtm: on this change.

Longer-term, I am a bit concerned about the level of repetition emerging in `symbolic_expression_cell.cc`.  It seems like we have repeats of what is essentially a destructure-map-structure operation -- f(x) -> x(f(x.a), f(x.b), ...)).  I wonder if a visitor pattern might avoid having to have separate to write separate, parallel implementations for each cell type for Subst, Eval, etc. operations that are basically monad operations, while still overriding the special cases (eg, short-circuiting explicit values).

Something to consider, anyway.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc4E3faxzPydaiaZYZz:b-hozwot)*

**Comment by soonho-tri** [comment]
Great point! Thanks for the suggestion. I'll make another PR soon.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc4Gqh1ifUSNzrHyHZi:b4y0uou)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.cc, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-Kc4NXgcU7BkfKZ4cRLG:-Kc4NXgcU7BkfKZ4cRLH:b-z5l641) ([raw file](https://github.com/robotlocomotion/drake/blob/6580fdd6feedb4d8d35a32b2fffe35c11ed7cd8a/drake/common/symbolic_formula_cell.cc#L298)):*
> ```cpp
>     // short-circuiting
>     if (is_false(ret)) {
>       return ret;
> ```

Why we do not return `FormulaFalse` directly?

---

*[drake/common/symbolic_formula_cell.h, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-Kc4O1prKQby3xYPLlPd:-Kc4O1prKQby3xYPLlPe:bys1yvn) ([raw file](https://github.com/robotlocomotion/drake/blob/6580fdd6feedb4d8d35a32b2fffe35c11ed7cd8a/drake/common/symbolic_formula_cell.h#L82)):*
> ```objc
>   RelationalFormulaCell(FormulaKind k, const Expression& e1,
>                         const Expression& e2);
>   Variables GetFreeVariables() const override;
> ```

Why we remove the documentation here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.h, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-Kc4O1prKQby3xYPLlPd:-Kc4OoArIyUkAS1Er-ns:b-g8havu) ([raw file](https://github.com/robotlocomotion/drake/blob/6580fdd6feedb4d8d35a32b2fffe35c11ed7cd8a/drake/common/symbolic_formula_cell.h#L82)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why we remove the documentation here?
</blockquote></details>

Presumably anything that is `override` can be reasonably assumed to inherit the contract of its parent.  Duplicating the doc just asks for bit-rot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.cc, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-Kc4NXgcU7BkfKZ4cRLG:-Kc4OZLx7uu4B44Eow3U:b-7sij70) ([raw file](https://github.com/robotlocomotion/drake/blob/6580fdd6feedb4d8d35a32b2fffe35c11ed7cd8a/drake/common/symbolic_formula_cell.cc#L298)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why we do not return `FormulaFalse` directly?
</blockquote></details>

Consider an example:
```
    f = (x > 5) && f1 && ... && fn
```
If we execute `f.Substitute(x, 0)`, the first conjunct `x > 5` becomes `false`. Then we don't need to substitute the following conjuncts `f1`, ... , `fn`. We can return `false` immediately.

---

*[drake/common/symbolic_formula_cell.h, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-Kc4O1prKQby3xYPLlPd:-Kc4OwtfBxbgz5_NKzNV:b-1vijnq) ([raw file](https://github.com/robotlocomotion/drake/blob/6580fdd6feedb4d8d35a32b2fffe35c11ed7cd8a/drake/common/symbolic_formula_cell.h#L82)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Presumably anything that is `override` can be reasonably assumed to inherit the contract of its parent.  Duplicating the doc just asks for bit-rot.
</blockquote></details>

Exactly!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5029#-:-Kc4VVsadws1xHiCqyZ6:bnfp4nl)*

**Pull request merged**
