### PR TITLE
WIP [geometry] Add time parameter to Meshcat::SetObject() of Shape.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Related to:
-  #19142

Experiment with an idea to transpile `SetObject(time)` to `SetObject()` without `time` and multiple `SetProperty(visible)` on and off at various `time`, as suggested [here](https://github.com/RobotLocomotion/drake/issues/19142#issuecomment-1927495603).

For simplicity, this draft PR experiments with SetObject(Shape), not mesh.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @DamrongGuoy)

___
*[`geometry/meshcat.cc` line 2410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nqj9Yaq2O5Z5S1-S3Lb:-Nqj9Yaq2O5Z5S1-S3Lc:b9i3ec3) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a9adf53c1db4981695d97884019f1132ddf399f/geometry/meshcat.cc#L2410)):*
> ```cpp
>     std::string path_object = fmt::format("{}/<object>", path);
>     SetProperty(path_object, "visible", false, time_start);
>   }
> ```

@jwnimmer-tri  This is my interpretation of the first line of the suggested transpilation:

```
 SetProperty(path=/foo/<object>, property=visible, value=false, time=time_tstart)
```

I'm not sure what's the implication of having `SetProperty(path_object,...)` **without** `SetObject(path_object,...)` ?  



_Code quote:_
```cpp
  if (!already_started.contains(path)) {
    already_started.insert(path);
    // TODO(DamrongGuoy): Find start time instead of 0.
    const double time_start = 0;
    std::string path_object = fmt::format("{}/<object>", path);
    SetProperty(path_object, "visible", false, time_start);
  }
```
___
*[`geometry/meshcat.cc` line 2443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NqjAcY55UyNzPO9ZQZj:-NqjAcY55UyNzPO9ZQZk:b-tldtmj) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a9adf53c1db4981695d97884019f1132ddf399f/geometry/meshcat.cc#L2443)):*
> ```cpp
>     const double time_final = std::numeric_limits<double>::infinity();
>     SetProperty(path_animation_last, "visible", false, time_final);
>     SetProperty(path_object, "visible", true, time_final);
> ```

@jwnimmer-tri   I'm also not sure what's the implication of this line.



_Code quote:_
```cpp
    SetProperty(path_object, "visible", true, time_final);
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NqjB-h81pcnE24osW89:-NqjB-h9E1Kh54NkcpLF:b-4y4aj5) (no related file):*
@jwnimmer-tri I understand the `SetProperty(path=/foo/<animation>/t...`.  They are brilliant.  However, I do not understand the ` SetProperty(path=/foo/<object>,...` at the first line and the last line (please see my two questions below).

Please help me.  I might misunderstand something.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @DamrongGuoy)

___
*[`geometry/meshcat.cc` line 2410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nqj9Yaq2O5Z5S1-S3Lb:-NqjDwU1CIx-2PMO0rtd:b344agd) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a9adf53c1db4981695d97884019f1132ddf399f/geometry/meshcat.cc#L2410)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@jwnimmer-tri  This is my interpretation of the first line of the suggested transpilation:

```
 SetProperty(path=/foo/<object>, property=visible, value=false, time=time_tstart)
```

I'm not sure what's the implication of having `SetProperty(path_object,...)` **without** `SetObject(path_object,...)` ?
</blockquote></details>

Maybe your test program (where is it?) doesn't tickle this case.

The idea is that when the animation starts, we need to hide any (untimed) object that already exists in the scene.

You can explore it by calling `SetObject()` with no `time` prior to starting the animation.  The idea is that the animation should _take over_ that object.
___
*[`geometry/meshcat.cc` line 2443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NqjAcY55UyNzPO9ZQZj:-NqjEPzq-87DYVo0mKpo:b-cscom5) ([raw file](https://github.com/RobotLocomotion/drake/blob/2a9adf53c1db4981695d97884019f1132ddf399f/geometry/meshcat.cc#L2443)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@jwnimmer-tri   I'm also not sure what's the implication of this line.
</blockquote></details>

After the animation is finished we need `<object>` to be the thing that is visible to the user, so that if they continue any _untimed_ changes to the path those will show up correctly.

It's possible that I was missing one more `SetObject` call in the transpilation to make that work all the way correctly:

```
SetObject(path=/foo/<object>, shape=shape_t3)
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NqjB-h81pcnE24osW89:-Nqj_Y5Y8bQDqpvI14Jp:b-eelng5) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@jwnimmer-tri I understand the `SetProperty(path=/foo/<animation>/t...`.  They are brilliant.  However, I do not understand the ` SetProperty(path=/foo/<object>,...` at the first line and the last line (please see my two questions below).

Please help me.  I might misunderstand something.
</blockquote></details>

Thank you for the clarification in the comments. Now I understand better that it's about managing untimed objects (<object>) to play well with timed objects (<animation>/t_i).  I'll complete the code and test it accordingly.

Working.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/meshcat.cc` line 2410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nqj9Yaq2O5Z5S1-S3Lb:-Nr8hFcm8oqgNaPma1qq:b-w6q9rd) ([raw file](https://github.com/RobotLocomotion/drake/blob/78b915a9f3b31b879ff579be6f06bce73cc7b8e0/geometry/meshcat.cc#L2410)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe your test program (where is it?) doesn't tickle this case.

The idea is that when the animation starts, we need to hide any (untimed) object that already exists in the scene.

You can explore it by calling `SetObject()` with no `time` prior to starting the animation.  The idea is that the animation should _take over_ that object.
</blockquote></details>

I have added a test to call `SetObject()` with no `time` before starting the animation.  Thanks.
___
*[`geometry/meshcat.cc` line 2443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NqjAcY55UyNzPO9ZQZj:-Nr8hYlIDLlpj5Grqwc9:b-6dgg5f) ([raw file](https://github.com/RobotLocomotion/drake/blob/78b915a9f3b31b879ff579be6f06bce73cc7b8e0/geometry/meshcat.cc#L2443)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

After the animation is finished we need `<object>` to be the thing that is visible to the user, so that if they continue any _untimed_ changes to the path those will show up correctly.

It's possible that I was missing one more `SetObject` call in the transpilation to make that work all the way correctly:

```
SetObject(path=/foo/<object>, shape=shape_t3)
```
</blockquote></details>

I'm still working on this part.
___
*[`geometry/test/meshcat_time_test.cc` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nr8hjrkDO6YyMQbz4mb:-Nr8hjrkDO6YyMQbz4mc:bk8jt9i) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f6aacf5b5d4fb93ab16ff9f3ddc6c60516f3370/geometry/test/meshcat_time_test.cc#L1)):*
> ```cpp
> #include "drake/geometry/meshcat.h"
> ```

For now, I have a separate test file `meshcat_time_test.cc` for convenience.  The non-draft version of this PR will have it in `meshcat_test.cc`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

___
*[`geometry/test/meshcat_time_test.cc` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nr96zsg8Q4yH1EhCGmL:-Nr96zshDPwy4VHgSeOb:b-d97jn) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f6aacf5b5d4fb93ab16ff9f3ddc6c60516f3370/geometry/test/meshcat_time_test.cc#L36)):*
> ```cpp
> 
>   // TODO(DamrongGuoy) Remove sleep() when I don't need to test it manually.
>   sleep(5);
> ```

BTW https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/maybe_pause_for_user.h is a helpful tool.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/test/meshcat_time_test.cc` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-Nr96zsg8Q4yH1EhCGmL:-NrDoc5aBZ62Sxl3OoUr:b-cam407) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f6aacf5b5d4fb93ab16ff9f3ddc6c60516f3370/geometry/test/meshcat_time_test.cc#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/maybe_pause_for_user.h is a helpful tool.
</blockquote></details>

Thank you.  I use `MaybePauseForUser()` now.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20959)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20959#-NrhZVwq0ALFoWZxxeZr:-NrhZVwrDUPYrIJLhRb1:brp310e) (no related file):*
BTW, this prototype PR is relevant to #18433.

___

**Comment by DamrongGuoy** [comment]
I have applied the idea from this experimental PR to #21279. I'll close this PR now.

**Pull request closed without merging**
