### PR TITLE
Fix 8854

### PR DESCRIPTION
**Pull request by m-chaturvedi**
[Similar problem](https://github.com/RobotLocomotion/drake/pull/6299)
>Reference: https://eigen.tuxfamily.org/dox/TopicPitfalls.html

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
[linux-xenial-gcc-bazel-experimental-debug](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/13389/)

**Comment by m-chaturvedi** [comment]
@soonho-tri for feature review, please.

**Comment by m-chaturvedi** [comment]
+@soonho-tri for feature review, please.

**Comment by soonho-tri** [comment]
:lgtm: with minor suggestions.

@hongkai-dai , @sherm1 , @seancurtis-tri , can one of you review this PR as a reviewer of https://github.com/RobotLocomotion/drake/pull/8854 ?

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: 5 unresolved discussions, platform LGTM from [soonho-tri]

---

*[multibody/BUILD.bazel, line 475 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ-tyPCPcpIbH0m6hj:-LFJ-tyPCPcpIbH0m6hk:b-7wvvjf) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/BUILD.bazel#L475)):*
> ```Python
>     deps = [
>         ":rigid_body_distance_constraint",
>         "//common/test_utilities:eigen_matrix_compare",
> ```

Nit, not needed?

---

*[multibody/rigid_body_distance_constraint.h, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LF7NwVB4ZpsfCcdGzRD:-LF7NwVDCmZZ3idXHx_e:b53i40k) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/rigid_body_distance_constraint.h#L3)):*
> ```objc
> #pragma once
> 
> #include <iostream>
> ```

Nit the two `#include <>` are not needed.

---

*[multibody/rigid_body_tree.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ39Xh8hcdf56q3IUP:-LFJ39Xi9s6o88smRtZq:bl8mmfr) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/rigid_body_tree.cc#L237)):*
> ```cpp
>   for (const auto& loop : loops) {
>     std::shared_ptr<RigidBodyFrame<double>> frame_a = clone->findFrame(
>         loop.frameA_->get_name(), loop.frameA_->get_model_instance_id());
> ```

Can you exclude those whitespace changes from the PR? That should help `git-blame` work better.

---

*[multibody/rigid_body_tree.cc, line 3197 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ3Oo5ATw43MmDqnW3:-LFJ3Oo5ATw43MmDqnW4:b-7j1yv0) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/rigid_body_tree.cc#L3197)):*
> ```cpp
>   RigidBodyDistanceConstraint dc(bodyA_index_in, r_AP_in, bodyB_index_in,
>                                  r_BQ_in, distance_in);
>   distance_constraints.push_back(dc);
> ```

FYI, using `emplace_back` is a better option here:
```c++
  distance_constraints.emplace_back(bodyA_index_in, r_AP_in, bodyB_index_in,
                                    r_BQ_in, distance_in);
```

---

*[multibody/test/rigid_body_distance_constraint_test.cc, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ-ckG1qPhDce9yKPG:-LFJ-ckG1qPhDce9yKPH:b-1ypcj7) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/test/rigid_body_distance_constraint_test.cc#L6)):*
> ```cpp
> 
> #include "drake/common/eigen_types.h"
> #include "drake/common/test_utilities/eigen_matrix_compare.h"
> ```

Nit, not used?

---

*[multibody/test/rigid_body_distance_constraint_test.cc, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ-dnN4HWG1ukBXG1r:-LFJ-dnN4HWG1ukBXG1s:b-xl71uz) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/test/rigid_body_distance_constraint_test.cc#L13)):*
> ```cpp
> 
> GTEST_TEST(RigidBodyDistanceConstraintTest, TestInitialization) {
>   int body1 = 1;
> ```

Nit, can be all `const`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008#-:-LFJ5WpQE5izRWFvZzDT:b-nnnlj5)*

**Comment by sherm1** [comment]
I'll do it +@sherm1.
@m-chaturvedi can you say what has changed since #8854 was reviewed? I'd like to concentrate on just the changes.

---

Review status: 5 unresolved discussions, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008#-:-LFJE1wF6xrd1UxvA5JX:b-aco4cf)*

**Comment by mpetersen94** [comment]
Since this is a fix to a PR I created originally, I'm happy to do the review work.  But I can't push to the branch that is being merged. Would closing this PR and creating a new one that I can push to cause any headaches for the reviewers?

**Comment by sherm1** [comment]
@mpetersen94 -- if Mmanu is willing to give you developer access to the m-chaturvedi/drake fork you wouldn't need a new PR.

**Comment by jwnimmer-tri** [comment]
@sherm1 The first commit is the original, the second commit is the changes that unbreak the build.  Because @m-chaturvedi's request for review was overly terse, @soonho-tri's review nitpicked things from the original commit.  My suggestion is to review only the second commit and then merge, and then @mpetersen94 can submit a new PR that responds to Soonho's comments.

**Comment by m-chaturvedi** [comment]
@sherm1 Just the second commit.  I am sorry for not being clear. 

I'd just cherry-picked what was reverted and made the three changes outlined in second commit.

**Comment by sherm1** [comment]
Ah, thanks @jwnimmer-tri and @m-chaturvedi. I reviewed the 2nd commit and it is :lgtm: pending one minor change.

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008#-:-LFJeiCxBX-aHbeJZEvP:bpfwgzo)*

**Comment by mpetersen94** [comment]
*[multibody/rigid_body_tree.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ39Xh8hcdf56q3IUP:-LFKF7hhEu4ZRrxxWLgs:by4dcxv) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/rigid_body_tree.cc#L237)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can you exclude those whitespace changes from the PR? That should help `git-blame` work better.
</blockquote></details>

I think `git-blame` has already been messed up by the original PR and the PR that reverted it. Unless there is some way to undo that, I don't think excluding the whitespace changes will work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008)*

**Comment by soonho-tri** [comment]
I've retracted all my minor comments.

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri, sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008#-:-LFKGyHd6jDxFb-MZn9O:b-6tep08)*

**Comment by SeanCurtis-TRI** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri, sherm1]

---

*[multibody/rigid_body_tree.cc, line 3197 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9008#-LFJ3Oo5ATw43MmDqnW3:-LFLDeTQ5XE_TjQsBnjI:bvhqlpm) ([raw file](https://github.com/robotlocomotion/drake/blob/4d1b990b02268dec1cfa1d3b05bf07af52c7af20/multibody/rigid_body_tree.cc#L3197)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, using `emplace_back` is a better option here:
```c++
  distance_constraints.emplace_back(bodyA_index_in, r_AP_in, bodyB_index_in,
                                    r_BQ_in, distance_in);
```
</blockquote></details>

Ha! I made a similar comment in the original PR.  :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9008)*

**Pull request merged**
