### PR TITLE
Add and use drake_install_libraries function

### PR DESCRIPTION
**Pull request by jamiesnape**
Since this touches a lot of files, this is a very simple first version just to get all the functions renamed. More to follow once this is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4171)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
CI disapproves?

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-:-KWtdctPxjJw_kmmaOhq:bxxqq0w)*

**Comment by jamiesnape** [comment]
I am really not getting on well with SWIG this week.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/install.cmake, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-KX6M0RweIGFKaydPTWe:-KX6M0RweIGFKaydPTWf:b-scjegz) ([raw file](https://github.com/robotlocomotion/drake/blob/8cee1e61d433159aa14dade7bd0b3b36b33c0340/cmake/install.cmake#L87)):*
> ```CMake
> # Arguments:
> #   TARGETS <targets...>
> #     List of library targets.
> ```

BTW, maybe `List of library targets to be installed`? (If this is being changed in another PR, could make the change locally and PR later...)

---

*[drake/lcmtypes/CMakeLists.txt, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-KX6NmtNM1x3jR0z8j_p:-KX6NmtOQmFfHQcBbkCw:b-myr673) ([raw file](https://github.com/robotlocomotion/drake/blob/8cee1e61d433159aa14dade7bd0b3b36b33c0340/drake/lcmtypes/CMakeLists.txt#L80)):*
> ```CMake
> 
> install(TARGETS drake_lcmtypes drakeLCMTypes
>   EXPORT ${PROJECT_NAME}-targets
> ```

BTW, are we going to create DrakeConfig.cmake or drake-config.cmake? We should probably be consistent with that convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-:-KX6OLJYw9ySp9ZJOVxT:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 40 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/install.cmake, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-KX6M0RweIGFKaydPTWe:-KX6PB1STxxPwoy-RKIT:bab74sr) ([raw file](https://github.com/robotlocomotion/drake/blob/8cee1e61d433159aa14dade7bd0b3b36b33c0340/cmake/install.cmake#L87)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, maybe `List of library targets to be installed`? (If this is being changed in another PR, could make the change locally and PR later...)
</details>
I will change in the next PR.

---

*[drake/lcmtypes/CMakeLists.txt, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-KX6NmtNM1x3jR0z8j_p:-KX6P6imUK1hJ28ABq0y:bevcy1s) ([raw file](https://github.com/robotlocomotion/drake/blob/8cee1e61d433159aa14dade7bd0b3b36b33c0340/drake/lcmtypes/CMakeLists.txt#L80)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, are we going to create DrakeConfig.cmake or drake-config.cmake? We should probably be consistent with that convention.
</details>
`drake-config.cmake`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4171)*

**Comment by jamiesnape** [comment]
All builds are blue/green. @david-german-tri for platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 37 of 38 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4171#-:-KX6UPie7RGGWd4poI20:bnfp4nl)*

**Pull request merged**
