### PR TITLE
Added test for constructing simulator with two arguments

### PR DESCRIPTION
**Pull request by edrumwri**
This test was created to address issue #3733.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3788)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-KTuXZOl8WEkf8Vt-8IJ:-KTuXZOl8WEkf8Vt-8IK:b-d7y90n) ([raw file](https://github.com/robotlocomotion/drake/blob/2de16feb9d97b32ecda6bd2c6d30ed589e813c98/drake/systems/analysis/test/simulator_test.cc#L27)):*
> ```cpp
> 
>   /// Construct the simulator with the created context.
>   Simulator<double> simulator(spring_mass, std::move(context));
> ```

Could you assert that get_mutable_context gives back the same pointer, just so this test is asserting something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-:-KTuXeOAC9JhPKgDNBZK:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm: (pending David's comment). Thanks, Evan!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-:-KTuZsKfw5txCYU6VpAV:bzaxsyw)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-KTuXZOl8WEkf8Vt-8IJ:-KTucJPN9-00HL8PqyeR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2de16feb9d97b32ecda6bd2c6d30ed589e813c98/drake/systems/analysis/test/simulator_test.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Could you assert that get_mutable_context gives back the same pointer, just so this test is asserting something?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788)*

**Comment by RussTedrake** [comment]
:lgtm: thanks!

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-KTuXZOl8WEkf8Vt-8IJ:-KTuitH6E_yYp90oeXxu:b-d0vgxk) ([raw file](https://github.com/robotlocomotion/drake/blob/2de16feb9d97b32ecda6bd2c6d30ed589e813c98/drake/systems/analysis/test/simulator_test.cc#L27)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>
> Done.
</details>
not seeing changes; did you push them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788)*

**Comment by edrumwri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/simulator_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-KTuXZOl8WEkf8Vt-8IJ:-KTukWxXsGZhyo-xBGf0:b-a2lzg) ([raw file](https://github.com/robotlocomotion/drake/blob/2de16feb9d97b32ecda6bd2c6d30ed589e813c98/drake/systems/analysis/test/simulator_test.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> not seeing changes; did you push them?
</details>
Doh! Now pushed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-:-KTutyj7F97kdbI9zzzR:bnfp4nl)*

**Comment by edrumwri** [comment]
-@edrumwri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3788#-:-KTuzQq-G5zJYP2CB5g0:bskca6d)*

**Pull request merged**
