### PR TITLE
Port more event-handling code to modern API

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #20114.  Towards #20094.

+@sherm1 for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a couple of minor items
+@rpoyner-tri for platform review per schedule, please

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-:-NgPwWvq0urDpVjqSBJD:by9n7xm)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`examples/bouncing_ball/bouncing_ball.h` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-NgPsSnF9aAI_-t6J4U0:-NgPsSnF9aAI_-t6J4U1:b-h41lw8) ([raw file](https://github.com/RobotLocomotion/drake/blob/18d12ddc60d08fc896a5fa038c1fee1fdd1c4a11/examples/bouncing_ball/bouncing_ball.h#L48)):*
> ```objc
>         [this](const systems::System<T>&, const systems::Context<T>& context,
>                const systems::Event<T>&, systems::State<T>* next_state) {
>           return this->CalcUnrestrictedUpdate(context, next_state);
> ```

minor: this isn't a good name for the handler (too generic, duplicates the name of a System API). Consider something like "HandleImpact()" instead.
___
*[`bindings/pydrake/systems/pyplot_visualizer.py` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-NgPtx_t7r4NWAXcQR_v:-NgPtx_t7r4NWAXcQR_w:b-6lm2ea) ([raw file](https://github.com/RobotLocomotion/drake/blob/18d12ddc60d08fc896a5fa038c1fee1fdd1c4a11/bindings/pydrake/systems/pyplot_visualizer.py#L89)):*
> ```Python
> 
>         self.DeclareInitializationPublishEvent(on_initialize)
>         self.DeclareInitializationPublishEvent(self._on_any_publish)
> ```

minor: this seems redundant with the PeriodicPublishEvent above which has offset=0 so will trigger at the end of initialization anyway. The test still passes without this line.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-:-NgPybWz8jWZHmHCDchH:bnfp4nl)* status: 2 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338)* status: 1 unresolved discussion

___
*[`bindings/pydrake/systems/pyplot_visualizer.py` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-NgPtx_t7r4NWAXcQR_v:-NgPze270uhaH_oe3G6e:blymkaq) ([raw file](https://github.com/RobotLocomotion/drake/blob/18d12ddc60d08fc896a5fa038c1fee1fdd1c4a11/bindings/pydrake/systems/pyplot_visualizer.py#L89)):*
> This seems redundant with the PeriodicPublishEvent above which has offset=0 so will trigger at the end of initialization anyway.

There is no reason to believe that initialization only ever happens at time == 0.

> The test still passes without this line.

Oh well.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338)* status: 1 unresolved discussion

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20338)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

___
*[`bindings/pydrake/systems/pyplot_visualizer.py` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20338#-NgPtx_t7r4NWAXcQR_v:-NgQDu0J-WdxndJe3GrO:b-w735df) ([raw file](https://github.com/RobotLocomotion/drake/blob/18d12ddc60d08fc896a5fa038c1fee1fdd1c4a11/bindings/pydrake/systems/pyplot_visualizer.py#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> This seems redundant with the PeriodicPublishEvent above which has offset=0 so will trigger at the end of initialization anyway.

There is no reason to believe that initialization only ever happens at time == 0.

> The test still passes without this line.

Oh well.
</blockquote></details>

I see your point. I guess there is no harm in calling this twice for initialization at time 0. Retracted.

**Pull request merged**
