### PR TITLE
Test collision checking with FCL (WIP)

### PR DESCRIPTION
**Pull request by sprax**
- Work In Progress -- Not ready for review.
- made model_test actually call FCL code by making sure `DRAKE_DISABLE_FCL` is not defined.
- code formatting to pass Drake cpp lint tests

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9036)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I am going to tag this "Do not review" for now, since its a WIP.  Please ping us when ready for review and I can remove the tag.

**Comment by SeanCurtis-TRI** [comment]
@sprax This doesn't seem to have moved in many months. Is this still active?

**Comment by SeanCurtis-TRI** [comment]
@sprax If I don't hear from you, I'm going to close this PR right after Thanksgiving.

**Comment by SeanCurtis-TRI** [comment]
I'm closing this for inactivity (based on previous warnings).

**Pull request closed without merging**
