### PR TITLE
Generate IdmWithTrajectoryAgentParameters

### PR DESCRIPTION
**Pull request by david-german-tri**
Introduce a YAML notation for lcm_vector_gen.py that provides docstrings as well as names for each field.

Use this notation to generate IdmWithTrajectoryAgentParameters.

Update the install instructions to require python-yaml.

@jwnimmer-tri for feature review

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3949)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/idm_with_trajectory_agent-inl.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVLZSuP4SX17bDhO3uH:-KVLZSuP4SX17bDhO3uI:bjuyzcs) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/automotive/idm_with_trajectory_agent-inl.h#L17)):*
> ```objc
> #include "drake/automotive/gen/idm_with_trajectory_agent_parameters.h"
> #include "drake/common/drake_assert.h"
> #include "drake/math/autodiff.h"
> ```

Unclear why this is needed.

---

*[drake/tools/lcm_vector_gen.py, line 392 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVPd9w-o3IIHZR0trFm:-KVPd9w-o3IIHZR0trFn:bo7ir8v) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/tools/lcm_vector_gen.py#L392)):*
> ```Python
>     parser.add_argument(
>         '--yaml_file',
>         help="YAML message description, which supersedes command-line fields")
> ```

BTW Strictly speaking, is it a message description, or a vector description?

---

*[drake/tools/lcm_vector_gen.sh, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVMgtuvzsYP0PRi98_T:-KVMgtuvzsYP0PRi98_U:b534sgh) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/tools/lcm_vector_gen.sh#L63)):*
> ```Shell
>     yaml_file="$2"
>     snake=$(echo "$title" | tr " " _)
>     shift
> ```

BTW This is a bit weird.  There are two positional args, only of which one is shifted away, but then `$@` is not used again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-:-KVPdHlL4wovJFeGRrBX:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/idm_with_trajectory_agent-inl.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVLZSuP4SX17bDhO3uH:-KVQ68iHDiMcSU0EDy3E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/automotive/idm_with_trajectory_agent-inl.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unclear why this is needed.
</details>
Done.

---

*[drake/tools/lcm_vector_gen.py, line 392 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVPd9w-o3IIHZR0trFm:-KVQ6ENzjj970mMRPScm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/tools/lcm_vector_gen.py#L392)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Strictly speaking, is it a message description, or a vector description?
</details>
Done.

---

*[drake/tools/lcm_vector_gen.sh, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVMgtuvzsYP0PRi98_T:-KVQ6nCu5mr3dhUgjttZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/tools/lcm_vector_gen.sh#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This is a bit weird.  There are two positional args, only of which one is shifted away, but then `$@` is not used again.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/idm_with_trajectory_agent-inl.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVLZSuP4SX17bDhO3uH:-KVQ7n3inQeYVL4TF94B:b-m8j7t3) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/automotive/idm_with_trajectory_agent-inl.h#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
Still unclear -- I don't see any use of autodiff types in this header?  I think the `.cc` file is likely where this should live, since that's where `T = TaylorVarXd` is bound?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/idm_with_trajectory_agent-inl.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVLZSuP4SX17bDhO3uH:-KVQ9RWqFnohVgwwWdY_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a25d674a851344bcad26e06a40d993257cca5ec/drake/automotive/idm_with_trajectory_agent-inl.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Still unclear -- I don't see any use of autodiff types in this header?  I think the `.cc` file is likely where this should live, since that's where `T = TaylorVarXd` is bound?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by david-german-tri** [comment]
Alternatively, @liangfok for feature review, and we'll treat jwnimmer-tri as platform

**Comment by david-german-tri** [comment]
Would kind of like to get this merged; there's nothing controversial here, but I have multiple trees of commits subsequent to this one queued up!

**Comment by sherm1** [comment]
A couple of questions: (1) there are a bunch of generated files checked in with this PR; is that intentional? (2) Are there tests somewhere that verify correct functioning, and if not should there be? And one BTW comment. But, :lgtm:.

---

Reviewed 12 of 15 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.sh, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVROxrMDPa_YsIN9gNo:-KVROxrNvurLhMzTfhm1:b-uptv2o) ([raw file](https://github.com/robotlocomotion/drake/blob/e7f10fb8eb68abee4bd6a6bf592d2c3f89fbfb0f/drake/tools/lcm_vector_gen.sh#L55)):*
> ```Shell
> }
> 
> # Call the code generator to produce just a Drake BasicVector based on a YAML spec.
> ```

BTW, line length.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-:-KVRPRm9-PPHkzYUiOQK:bojx8j3)*

**Comment by jwnimmer-tri** [comment]
@sherm1 (1) Checking in the generated files is intentional, yes.  We did that initially (months ago) because making codegen-as-part-of-build work on Windows was a yakshave.  At this point, I'd say we are waiting for Bazel before codegen-as-part-of-build, to reduce throwaway CMake effort.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-:-KVS12AeHAn5XjMJdq84:banfzno)*

**Comment by liangfok** [comment]
Looks good! :lgtm: 

---

Reviewed 12 of 15 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-:-KVT9vvfhKD6hPyDOF-S:b3prxon)*

**Comment by david-german-tri** [comment]
Test coverage for the genfiles comes from the code that uses them.

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.sh, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-KVROxrMDPa_YsIN9gNo:-KVV4HGgEe2X89CsVDJn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7f10fb8eb68abee4bd6a6bf592d2c3f89fbfb0f/drake/tools/lcm_vector_gen.sh#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, line length.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949#-:-KVV4MMtvEg294Qjnk9Y:b-mpbbak)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3949)*

**Comment by david-german-tri** [comment]
r4 was a whitespace change, and the new failures since r3 are agent errors due to AWS fire, so I'm going to override-merge.

**Pull request merged**
