### PR TITLE
[geometry] Add URL customization to Meshcat ctor

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Change unknown URLs to return empty, instead of random HTML.

When connecting from JavaScript, retain the sub-directory name (if any) from the http URL.

Towards #16639.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @RussTedrake FYI in case you'd like to weigh in.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/meshcat.h, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwRyVNkCD_kgS2oDeXz:-MwRyVNkCD_kgS2oDeY-:b-phqlzq) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.h#L97)):*
> ```objc
>   explicit Meshcat(
>       std::optional<int> port = std::nullopt,
>       std::string web_url_pattern = "http://localhost:{port}");
> ```

I wonder if we're going to gain more and more server settings, over time.  Services running on network ports aren't known for their small config files.

Possibly I should make `MeshcatParams` struct already now, so the constructor overloads on just the simple port, vs a full `params` configuration.  That would make room for customizing the listen address, for example.

WDYT?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.h, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSCcYoCTcCMJL3ghk6:-MwSCcYoCTcCMJL3ghk7:bn2k0vy) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.h#L92)):*
> ```objc
>   @param web_url_pattern may be used to change the web_url (and therefore the
>   ws_url) reported by this class. This may be useful in case this program sits
>   behind a firewall or proxy.
> ```

This documentation tells why, but doesn't describe the mechanics sufficiently. Nowhere does it say "this is format string for fmt::format() that will accept substitutions from specific variables, with specific default values".
___
*[geometry/meshcat.h, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwRyVNkCD_kgS2oDeXz:-MwSCV3u6-gu0MrzYyb7:bxgugib) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.h#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I wonder if we're going to gain more and more server settings, over time.  Services running on network ports aren't known for their small config files.

Possibly I should make `MeshcatParams` struct already now, so the constructor overloads on just the simple port, vs a full `params` configuration.  That would make room for customizing the listen address, for example.

WDYT?
</blockquote></details>

Maybe. I'm finding the `web_url_pattern` design a little obscure.
___
*[geometry/meshcat.cc, line 1447 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSEsav3oVROcpgkbMq:-MwSEsav3oVROcpgkbMr:b-5rftnk) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.cc#L1447)):*
> ```cpp
> Meshcat::Meshcat(std::optional<int> port, std::string web_url_pattern) {
>   // Sanity-check the pattern.
>   const std::string url = fmt::format(web_url_pattern, fmt::arg("port", 80));
> ```

AFAICT, this line goes nowhere, does nothing. Talk me down?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSPV6w8pXBpxKqq6S2:-MwSPV6xBMSsI-wDRoX9:b-yml0xw) (no related file):*
Working

I'm still need to to check the rendered Doxygen and Sphinx for good layout.

---
___
*[geometry/meshcat.h, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSCcYoCTcCMJL3ghk6:-MwSOkiS5jZlyJuC_I-L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.h#L92)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This documentation tells why, but doesn't describe the mechanics sufficiently. Nowhere does it say "this is format string for fmt::format() that will accept substitutions from specific variables, with specific default values".
</blockquote></details>

Done.
___
*[geometry/meshcat.h, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwRyVNkCD_kgS2oDeXz:-MwSOjQfCx9kQz4LAfiK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.h#L97)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe. I'm finding the `web_url_pattern` design a little obscure.
</blockquote></details>

Done.
___
*[geometry/meshcat.cc, line 1447 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSEsav3oVROcpgkbMq:-MwSJqHA82QFwzv-Usjf:b74eddu) ([raw file](https://github.com/robotlocomotion/drake/blob/19e8c401dc485b827d80f3fb931598f9ab60c654/geometry/meshcat.cc#L1447)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

AFAICT, this line goes nowhere, does nothing. Talk me down?
</blockquote></details>

Done (added two more test cases).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSPV6w8pXBpxKqq6S2:-MwSc8V0-ns0HObVml7j:b8p9dpq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'm still need to to check the rendered Doxygen and Sphinx for good layout.
</blockquote></details>

Done.

It would be better if the pydrake documentation displayed the default values found in bound `FooParams` structs, but _shrug_.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nittery

> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638#-:-MwSfYFr6Zs6PqAIhsqR:bb62doi)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1452 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSeqS6D2bsoyaUOYO1:-MwSeqS6D2bsoyaUOYO2:b-xyfv1a) ([raw file](https://github.com/robotlocomotion/drake/blob/7c12015c89bfe549589acaa69163b801ad3a7773/geometry/meshcat.cc#L1452)):*
> ```cpp
>   // Sanity-check the pattern.
>   const std::string url = fmt::format(
>       params.web_url_pattern, fmt::arg("port", 80));
> ```

nit It might still be useful to have a comment here indicating that the substitution is only done to leverage fmt:: error checking.
___
*[geometry/meshcat.cc, line 1452 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSf1ByCna644jT-z7q:-MwSf1ByCna644jT-z7r:b-j955w1) ([raw file](https://github.com/robotlocomotion/drake/blob/7c12015c89bfe549589acaa69163b801ad3a7773/geometry/meshcat.cc#L1452)):*
> ```cpp
>   // Sanity-check the pattern.
>   const std::string url = fmt::format(
>       params.web_url_pattern, fmt::arg("port", 80));
> ```

nit AFAICT, 80 is a don't-care value -- it doesn't much matter what number is here. That would be good to clarify.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform (did not locally test)

> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16638#-:-MwSqR17-K7kerxKhw_L:b-q6epf1)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 104 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16638#-MwSqJQX5gbnAUnzhMVp:-MwSqJQX5gbnAUnzhMVq:bmcuzic) ([raw file](https://github.com/robotlocomotion/drake/blob/0141aee66b63afbeef959fbbd79eb23bd9556b5b/geometry/test/meshcat_test.cc#L104)):*
> ```cpp
> GTEST_TEST(MeshcatTest, MalformedCustom) {
>   // Using a non-existent substitution is detected immediately.
>   DRAKE_EXPECT_THROWS_MESSAGE(
> ```

BTW Nice!

**Pull request merged**
