### PR TITLE
Port PackageMap away from GetDrakePath

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6536)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok-tri for feature review, please.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/package_map.cc, line 173 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-KoYXmzg0Vsx7M4Jp7S4:-KoYXmzg0Vsx7M4Jp7S5:bqzthog) ([raw file](https://github.com/robotlocomotion/drake/blob/b52359bdcc099447696c39250004539e5cd1b5b8/drake/multibody/parsers/package_map.cc#L173)):*
> ```cpp
>   DRAKE_DEMAND(extension == ".urdf" || extension == ".sdf");
> 
>   // Bail out if the model files is not in .../drake.
> ```

BTW, "model files" should be "model_file".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-:-KohToDySPQmIfN3HYmt:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per rotation (tomorrow), please.

**Comment by sammy-tri** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/BUILD, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-KohkVH1Z0eXqwvXw4un:-KohkVH28AWoQNFCet6p:bag22af) ([raw file](https://github.com/robotlocomotion/drake/blob/3a3a165bc5be33ad55a2cf6e00733131ce4d19eb/drake/multibody/parsers/BUILD#L33)):*
> ```Python
>     ],
>     deps = [
>         "//drake/common:find_resource",
> ```

Should all of `parsers` depend on this?  Or is it just a dependency of package_map_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6536)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/BUILD, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-KohkVH1Z0eXqwvXw4un:-KohmK_cG-XkaTXj08gq:b8wxvgr) ([raw file](https://github.com/robotlocomotion/drake/blob/3a3a165bc5be33ad55a2cf6e00733131ce4d19eb/drake/multibody/parsers/BUILD#L33)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should all of `parsers` depend on this?  Or is it just a dependency of package_map_test
</blockquote></details>

Ah, darn; you caught me cheating.  Various `drake_cc_{library,binary,googletest}` rules were relying on `:drake_path` here bringing in `:find_resource` downstream.  If I remove this line, many other targets break; this line makes it epsilon more truthy, but doesn't fix the missing declarations for the other rules.

What do you think about a follow-up PR that kills this line and adds it to the other places?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6536)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/BUILD, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-KohkVH1Z0eXqwvXw4un:-KohnJtiH-fETnrm0OsS:bspawc9) ([raw file](https://github.com/robotlocomotion/drake/blob/3a3a165bc5be33ad55a2cf6e00733131ce4d19eb/drake/multibody/parsers/BUILD#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, darn; you caught me cheating.  Various `drake_cc_{library,binary,googletest}` rules were relying on `:drake_path` here bringing in `:find_resource` downstream.  If I remove this line, many other targets break; this line makes it epsilon more truthy, but doesn't fix the missing declarations for the other rules.

What do you think about a follow-up PR that kills this line and adds it to the other places?
</blockquote></details>

Fixing in a follow-up PR would be fine with me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6536#-:-KohnQdV-tf6roOnpnOY:bnfp4nl)*

**Pull request merged**
