### PR TITLE
Add support for sanitizer environment variables and suppressions files

### PR DESCRIPTION
**Pull request by jamiesnape**
Still need to sort out `blacklist.txt`, which is compile time for Clang and really freaks out Bazel. Alternatively, I could tweak the F2C source in SNOPT with the necessary attribute to suppress, or upgrade F2C.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6096)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: assuming the potential issues aren't are not actual issues

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/asan.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHqYb9zKfeyEV9rk46:-KkHqYbCyWqVFWv-Q8us:b-162xfc) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L2)):*
> ```Shell
> #!/bin/bash
> tools=$(dirname $(realpath "$0"))
> ```

We can rely on GNU coreutils being installed on MacOS?

---

*[tools/asan.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHrgSDgLurIPs-dSRo:-KkHrgSFuFE0dFMQajxg:bspf7v2) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L3)):*
> ```Shell
> #!/bin/bash
> tools=$(dirname $(realpath "$0"))
> export ASAN_OPTIONS="$ASAN_OPTIONS:check_initialization_order=1:detect_stack_use_after_return=1:suppressions=$tools/asan.supp"
> ```

This is well-behaved is `ASAN_OPTIONS` has an empty element?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-:-KkHs3wJuwJjk4gVbW3Y:b-nayewp)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/asan.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHqYb9zKfeyEV9rk46:-KkHt9AAh7SOcpTGZBbe:bjtt2qv) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

We can rely on GNU coreutils being installed on MacOS?
</blockquote></details>

I guess not. Will fix.

---

*[tools/asan.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHrgSDgLurIPs-dSRo:-KkHsqz6w-uFwhRYhA4C:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L3)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

This is well-behaved is `ASAN_OPTIONS` has an empty element?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/asan.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHqYb9zKfeyEV9rk46:-KkHubqCPq8U1ikLctoo:b-anl443) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L2)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I guess not. Will fix.
</blockquote></details>

It's on tri-macbookm in `/usr/local`, but I don't if that's because I installed coreutils, or if it's there by default. (Maybe because there is no BSD version, that one goes in `/usr/local` while stuff thatwould replace a BSD program doesn't?)

If not, well... this is why I have that little perl nugget e.g. in `package_drake.sh` :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/asan.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkHqYb9zKfeyEV9rk46:-KkHvFt-qJl4bjZk7vZv:b-f0t51w) ([raw file](https://github.com/robotlocomotion/drake/blob/38c508c48738bc11b9a3f404b811f205e86b9031/tools/asan.sh#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

It's on tri-macbookm in `/usr/local`, but I don't if that's because I installed coreutils, or if it's there by default. (Maybe because there is no BSD version, that one goes in `/usr/local` while stuff thatwould replace a BSD program doesn't?)

If not, well... this is why I have that little perl nugget e.g. in `package_drake.sh` :smile:.
</blockquote></details>

```
$ realpath $(which realpath)
/usr/local/Cellar/coreutils/8.27/bin/grealpath
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
It would be nice not to duplicate all of the .sh files, but I'm not sure what alternate design would be better.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/bazel.rc, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkI5B29BblVVa-YTrp5:-KkI5B2AQoy8AcMdzNWE:b-vihefq) ([raw file](https://github.com/robotlocomotion/drake/blob/95a50048aa251e69e949091cad5362fea4c974ea/tools/bazel.rc#L157)):*
> ```
> build:msan --copt -fno-omit-frame-pointer
> build:msan --linkopt -fsanitize=memory
> test:lsan --run_under=//tools:msan
> ```

Should this say test:msan?  If so, why wasn't this a problem in CI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-:-KkI677be9IcQCxNplqA:b-vineuf)*

**Comment by jamiesnape** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-KkI5B29BblVVa-YTrp5:-KkI7795XayM0fezSRLC:b-j71tji) ([raw file](https://github.com/robotlocomotion/drake/blob/95a50048aa251e69e949091cad5362fea4c974ea/tools/bazel.rc#L157)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this say test:msan?  If so, why wasn't this a problem in CI?
</blockquote></details>

Yes, apparently it successfully ran MSan.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6096#-:-KkI9JLTgQEwD9CQmAFX:bnfp4nl)*

**Pull request merged**
