### PR TITLE
[meshcat] Add a URL path to call and serve StaticHtml downloads

### PR DESCRIPTION
**Pull request by Vinggui**
Adds a new URL path "/download" into Meshcat's server. Accessing this path will safely call "StaticHtml()" and return its processed data as a "Save As" dialog in the Browser.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot ok to test

**Review by jwnimmer-tri — COMMENTED** [review]
See https://github.com/Vinggui/drake/pull/1 for suggestions.

One missing part was any kind of testing.  I tweaked our existing acceptance test scripting to cover this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-:-NjOxJ9lEQZIDJ_CX16_:beokh5n)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`geometry/meshcat.cc` line 1809 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-NjObxpp7ocC_-eNOCNY:-NjObxpq4BaPnPkDfa2l:bh50gvw) ([raw file](https://github.com/RobotLocomotion/drake/blob/6beaf712759d4b1d86d2f3ea9db7e70c1a6e82ac/geometry/meshcat.cc#L1809)):*
> ```cpp
>                    const std::string output = StaticHtml();
>                    res->writeHeader("Content-Type", "text/html; charset=utf-8");
>                    res->writeHeader("Content-Encoding", "none");
> ```

BTW I did not understand what `Content-Encoding: none` means, and also why it would be important.  I haven't found the value of `none` documented anywhere in any references.  I did find some documentation that `Content-Encoding: identity` indicates uncompressed content, but the default anyway would be uncompressed so I'm not sure what it was buying us to do this?  I removed this line as part of my suggestions.

**Comment by Vinggui** [comment]
*[`geometry/meshcat.cc` line 1809 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-NjObxpp7ocC_-eNOCNY:-NjPVPaT5si3Od23o3kr:b-qkue07) ([raw file](https://github.com/RobotLocomotion/drake/blob/6beaf712759d4b1d86d2f3ea9db7e70c1a6e82ac/geometry/meshcat.cc#L1809)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I did not understand what `Content-Encoding: none` means, and also why it would be important.  I haven't found the value of `none` documented anywhere in any references.  I did find some documentation that `Content-Encoding: identity` indicates uncompressed content, but the default anyway would be uncompressed so I'm not sure what it was buying us to do this?  I removed this line as part of my suggestions.
</blockquote></details>

I think this was a mistake while attempting to force a download and a "Save as" from the browser. I appreciate your review here and totally agree with its removal.
Thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
This is a great feature, thanks!

I took the liberty of pushing a git merge to master, to resolve the merge conflict error.  I also pushed a short documentation update so people can find out about this feature.

+@SeanCurtis-TRI for feature review, please.

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-:-NjTTue33fwxY_4ILVlh:bv4l5b5)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Vinggui)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-NjTUBiz2j0YoVBwelMx:-NjTUBiz2j0YoVBwelMy:btn6aut) (no related file):*
I'll need platform reviewer assigned later.  Setting a reminder here for myself.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
What I love about this feature is that the user can initiate a static html version from the client side (and not have to do it from the server side).

What I *don't* like is the discoverability (or lack thereof). I think, ideally, we should simply have a button that triggers the download. That said, I'm good with proceeding with this as a monotonic improvement.

:LGTM:

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-:-NkMTYvY0nw_IEW7Za7E:b-isuqya)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Vinggui)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-:-NkMUEJtDYZAtGTVJ6EE:bt1x5ma)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Vinggui)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-NjTUBiz2j0YoVBwelMx:-NkMUFtU9vCUAY0MMNcU:bo48l0e) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll need platform reviewer assigned later.  Setting a reminder here for myself.
</blockquote></details>

I tagged platform in the main discussion thread.

___

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm:
Nice!

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20504#-:-NkNS5Vo7N71bKV-zR3m:b-xuteuq)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Vinggui)

**Comment by xuchenhan-tri** [comment]
+(status: squashing now)

**Pull request merged**
