### PR TITLE
linear_solve: Reduce use of SFINAE

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant (maybe?) to: #15685

Motivated by discussions in #15818, reduce some of the syntax noise by
replacing SFINAE with a combination of type aliases, if constexpr, and
static_assert. No functionality is changed, but perhaps things are easier to
read.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@hongkai-dai for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853#-:-MkrKSva6BtHV98mTk0a:bl5ccwd)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
r2 is `git clang-format`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853#-:-MkrMNP17Kx1IVtwCvSS:bmbwf6e)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  Thanks a lot!
+@jwnimmer-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853#-:-MkrRhYn6p9lEO0ovFD0:b-ugiekb)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[math/linear_solve.h, line 540 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrR5b81MSx9NAVRyxV:-MkrR5b81MSx9NAVRyxW:bpn0gqz) ([raw file](https://github.com/robotlocomotion/drake/blob/e1abaf6532cf9bc1f08a06a6f0be3df0d9e37558/math/linear_solve.h#L540)):*
> ```objc
> //@{
> /**
>  * Template specialization for both A and b being double-valued matrices.
> ```

This documentation needs to be updated? Now A and b must either
1. contain the same scalar type.
2. Contain different scalar types, neither one is symbolic.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[math/linear_solve.h, line 540 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrR5b81MSx9NAVRyxV:-MkrVZul8TxyO7PUeFPl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1abaf6532cf9bc1f08a06a6f0be3df0d9e37558/math/linear_solve.h#L540)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This documentation needs to be updated? Now A and b must either
1. contain the same scalar type.
2. Contain different scalar types, neither one is symbolic.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853#-:-MkrpXD30tfL9sgp8NJI:bnfp4nl)* status: 7 unresolved discussions (waiting on @rpoyner-tri)

___
*[math/linear_solve.h, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-Mkrbc8x8HpIxCpPD9pl:-Mkrbc8x8HpIxCpPD9pm:b-1mg6iu) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L20)):*
> ```objc
> 
> template <typename T>
> inline constexpr bool is_symbolic_v = is_symbolic<T>::value;
> ```

nit This seems like long-winded way of saying `= is_same_v<T, symbolic::Expression>`?  Why do we need a helper struct and specializations?
___
*[math/linear_solve.h, line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-Mkrc2Mm6KSL0wkmLCFH:-Mkrc2Mm6KSL0wkmLCFI:bl0oq1w) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L23)):*
> ```objc
> 
> template <typename T>
> using is_double_or_symbolic =
> ```

nit This name is only ever used once.  Why do we need a helper struct?  Seems like the condition could be inlined at its sole point of use, in the next statement.
___
*[math/linear_solve.h, line 424 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrnKmt7wXepC1GA8OA:-MkrnKmt7wXepC1GA8OB:brl33x9) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L424)):*
> ```objc
>     DerivedA::MaxRowsAtCompileTime, DerivedA::MaxColsAtCompileTime>>;
> 
> /**
> ```

nit Don't use `/**` on `namespace internal` code (you can use `/*`).

Ditto throughout.

https://drake.mit.edu/styleguide/cppguide.html#Doxygen
___
*[math/linear_solve.h, line 427 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrcrGKB95OaiYW0mlO:-MkrcrGKB95OaiYW0mlP:bc0ph52) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L427)):*
> ```objc
>  * The most "promoted" of two scalar types; if they are the same, then that
>  * type, if they are different, then whichever one is not 'double'.
>  */
> ```

nit Should it be an error condition if both of them are not double?  (If we don't care, then perhaps say that as `@pre` in the comment; otherwise, the contract is ambiguous.)
___
*[math/linear_solve.h, line 481 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-Mkront59Rv8Wba9shpS:-Mkront59Rv8Wba9shpT:bnl2x8k) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L481)):*
> ```objc
>  * specified scalar type. The entries with NA are not supported.
>  *
>  * | ＼A  |        |     |      |
> ```

FYI Doxygen does not seem to be rendering this line correctly
___
*[math/linear_solve.h, line 540 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrnYvJARbfbciJSC91:-MkrnYvK4kmdqMCjNJGv:b-s8v8ch) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L540)):*
> ```objc
> //@{
> /**
>  * Solve system A*x=b.  The supported combinations of scalar types are
> ```

nit `Solves` per GSG verb.
___
*[math/linear_solve.h, line 650 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-Mkrn2T_BppaHdy622f4:-Mkrn2TaB86c2hrm9c3u:b-3bzq0y) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L650)):*
> ```objc
>   template <typename DerivedB>
>   using SolutionType = internal::Solution<DerivedA, DerivedB>;
>   using ScalarA = typename DerivedA::Scalar;
> ```

nit By placing `ScalarA` in public, you're making it part of the supported API.  Would it be better to keep it isolated within the function body instead?
___
*[math/linear_solve.h, line 672 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-MkrnoBTASdUkIaTxBVq:-MkrnoBTASdUkIaTxBVr:b6v6kvq) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L672)):*
> ```objc
> 
>     if constexpr (!internal::is_autodiff_v<ScalarA> &&
>                   std::is_same_v<ScalarA, ScalarB>) {
> ```

nit For whatever reason, swapping the order of these two predicates (checking is_same first) seems like it would read more clearly to me.  Up to you.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[math/linear_solve.h, line 481 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15853#-Mkront59Rv8Wba9shpS:-MksUT3h9QExIoY6N0-P:b-gd6ec1) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4f6cc39d5411ce56e842ef59f689b0f4873e4b/math/linear_solve.h#L481)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Doxygen does not seem to be rendering this line correctly
</blockquote></details>

FWIW, tried various multiline header solutions; none worked.

Also, the doxygen rendering of `std::enable_if` return types is ... not all that helpful.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15853)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @rpoyner-tri)

**Pull request merged**
