### PR TITLE
[workspace] Further automate monthly externals upgrades

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
To preview of new docs, see [link](https://github.com/jwnimmer-tri/drake/blob/doc-upgrades/tools/workspace/README.md#semi-automated-monthly-upgrades).  For example results, see #16004.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
That vast majority of changes are straightforward -- update sha and checksum. Sometimes it leads to other changes. Should there be some mention that those ancillary changes should be captured in the commit message? Given that the upstream changes that necessitate these ancillary changes are opaque to the reviewer, some formal acknowledgement of their necessity would provide a basis for confidence in the reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005#-:-MnRW7t2Ei5PM7dEuOLA:bmulamh)* status: LGTM missing from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
(No need for "retest this please" on this one -- no C++ nor relevant Python code changes.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @BetsyMcPhail, @jwnimmer-tri, and @rpoyner-tri)

___
*[tools/workspace/README.md, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnRzsZf3ZT1U2LrHR26:-MnRzsZf3ZT1U2LrHR27:b-tcil73) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L96)):*
> ```Markdown
> https://drake.mit.edu/jenkins.html#scheduling-an-on-demand-build
> 
> Once the macOS build passes, assign the pull request for review.
> ```

Working

I plan to add a small note of advice here, something like

"If any of the changes were out of the ordinary (i.e., if they were anything more than just editing the version numbers and checksums), please be sure those changes are explained in the pull request overview, so that your reviewer(s) can understand the context and/or reasoning behind them."

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005#-:-MnSAVJYBQti1catLiK2:bnfp4nl)* status: 5 unresolved discussions, LGTM missing from assignee BetsyMcPhail (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[tools/workspace/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS2Ku894i_83AYGZ1r:-MnS2Ku894i_83AYGZ1s:bsvpfo6) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L88)):*
> ```
> and
> ```
typo
___
*[tools/workspace/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS2NAU6SaBUJeGOdEe:-MnS2NAU6SaBUJeGOdEf:b6i5dh9) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L88)):*
> ```
> rever
> ```
typo
___
*[tools/workspace/README.md, line 248 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS1Qre7P8Tz1eSFqPX:-MnS1Qre7P8Tz1eSFqPY:b-1e2bj3) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L248)):*
> ```
> complet
> ```
typo
___
*[tools/workspace/README.md, line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS1V1n80aRTyvBZS4X:-MnS1V1pBOoyW_EbCDlR:blue74x) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L249)):*
> ```
> minic
> ```
typo

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)* status: 4 unresolved discussions, LGTM missing from assignee BetsyMcPhail (waiting on @BetsyMcPhail and @rpoyner-tri)

___
*[tools/workspace/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS2Ku894i_83AYGZ1r:-MnSHvMXAL32XYhC7Dja:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L88)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> and
> ```
typo
</blockquote></details>

Done.
___
*[tools/workspace/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS2NAU6SaBUJeGOdEe:-MnSHz-p47Q1njE1ONtc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L88)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> rever
> ```
typo
</blockquote></details>

Done.
___
*[tools/workspace/README.md, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnRzsZf3ZT1U2LrHR26:-MnSI4Ow1XZBxNBQH5UI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I plan to add a small note of advice here, something like

"If any of the changes were out of the ordinary (i.e., if they were anything more than just editing the version numbers and checksums), please be sure those changes are explained in the pull request overview, so that your reviewer(s) can understand the context and/or reasoning behind them."
</blockquote></details>

Done.
___
*[tools/workspace/README.md, line 248 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS1Qre7P8Tz1eSFqPX:-MnSISaE1bew9xS2srsE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L248)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> complet
> ```
typo
</blockquote></details>

Done.
___
*[tools/workspace/README.md, line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MnS1V1n80aRTyvBZS4X:-MnSISsfDPWnXyTcBhhj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64aaf7774dd599c8256667bef50abb5b5ae1d76e/tools/workspace/README.md#L249)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> minic
> ```
typo
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)* status: LGTM missing from assignee BetsyMcPhail (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail would it make more sense to have @svenevs review the README here?  (Do you have any guesses as to who from Kitware is going to take on this monthly task?)

**Comment by BetsyMcPhail** [comment]
I'm sorry, I completely missed this PR. I can do the review (although Stephen is more than welcome to take a look as well). I'm not sure who will take on this monthly task yet, we can get back to you at next week's meeting.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005#-:-MoEyGVx8ZoKBvorIvnJ:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @jwnimmer-tri)

___
*[tools/workspace/README.md, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MoExPpI7UGz6SSb97gk:-MoExPpI7UGz6SSb97gl:b8c71m5) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc339f9fee8cf2ac5f6c6d919411de7562f56e3/tools/workspace/README.md#L36)):*
> ```Markdown
> Begin from an up-to-date checkout of Drake ``master``.
> 
> Read the documentation in ``//tools/workspace:new_release``.  If you haven't
> ```

BTW In new_release, it mentions "This program is only supported on Ubuntu Bionic 18.04". Should that be mentioned here as well?
___
*[tools/workspace/README.md, line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MoExxBA7o4EfeTQmq_x:-MoExxBA7o4EfeTQmq_y:bfi1rta) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc339f9fee8cf2ac5f6c6d919411de7562f56e3/tools/workspace/README.md#L85)):*
> ```Markdown
> 
> Once all upgrades are ready, open a Drake pull request and label it
> ``status: commits are properly curated``.  Each external being upgraded
> ```

BTW mention the feature in Reviewable to leave commits separated?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @rpoyner-tri)

___
*[tools/workspace/README.md, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MoExPpI7UGz6SSb97gk:-MoFc6KQ1TdtvfGY5lMR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc339f9fee8cf2ac5f6c6d919411de7562f56e3/tools/workspace/README.md#L36)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW In new_release, it mentions "This program is only supported on Ubuntu Bionic 18.04". Should that be mentioned here as well?
</blockquote></details>

Done.
___
*[tools/workspace/README.md, line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16005#-MoExxBA7o4EfeTQmq_x:-MoFcfyV8BhquAnu8VCe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc339f9fee8cf2ac5f6c6d919411de7562f56e3/tools/workspace/README.md#L85)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW mention the feature in Reviewable to leave commits separated?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16005)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @jwnimmer-tri)

**Pull request merged**
