### PR TITLE
Updates the style guide to specify the use of MKS.

### LINKED ISSUE #2284: Drake Documentation Should Specify Default Units and Coordinate Frames Used By Code
It will prevent needing to include the units in variable names when they use the default units / frames.

Suggested defaults: http://www.ros.org/reps/rep-0103.html

This should go somewhere in the wiki.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #2284.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5471)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm: - thanks, Liang.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-KezO6ii90JZnO_Adc1o:b-w66yc0)*

**Comment by liangfok** [comment]
Thanks +@sherm1. +@jwnimmer-tri for feature review / merge please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf-6Xt-eeMk0mYI9xQN:bxfjaot)*

**Comment by jwnimmer-tri** [comment]
:lgtm: but I think style changes should have a higher bar (even though this one is probably very agreeable).
+@russtedrake +@david-german-tri +@sammy-tri +@ggould-tri +@soonho-tri for review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf1ld7uhopWDvz53fR2:b-6n3rer)*

**Comment by ggould-tri** [comment]
:lgtm_strong:.  In a future PR perhaps we should also note radians/degrees.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf6k5HwtrFhndv13Gym:b-kave3)*

**Comment by david-german-tri** [comment]
:lgtm: sure.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf6xa0dAJH3XgolBie5:b-7vzvx2)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf6yRf4ZXJcy2itBl9M:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf71pg8K9IdJdeN7ntm:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For this one I think we can -@soonho-tri.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5471#-:-Kf72XrcF3uNcieZdn7d:bvpzh3y)*

**Pull request merged**
