### PR TITLE
Add Bazel support for ccd, octomap, FCL

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel test drake/multibody/collision:fcl_model_test 
INFO: Found 1 test target...
Target //drake/multibody/collision:fcl_model_test up-to-date:
  bazel-bin/drake/multibody/collision/fcl_model_test
INFO: Elapsed time: 1.632s, Critical Path: 0.43s
//drake/multibody/collision:fcl_model_test                      (cached) PASSED in 0.1s
Executed 0 out of 1 test: 1 test passes.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4600)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
CI is green, yay!

+@rpoyner-tri for the first review pass, please.

Note that the `tools/third_party/kythe/tools/build_rules/config/pkg_config.bzl` should not be reviewed within this PR.  The change was cherry-picked onto here to get CI working again, but will come into master separately as #4609, first.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-KZyUNBDrZLVWv0BWGOr:b-t9agyx)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-llGuIEIcFhqfWZA_:-K_-llGuIEIcFhqfWZAa:b-nchinp) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/WORKSPACE#L66)):*
> ```
>     remote = "https://github.com/danfis/libccd.git",
>     commit = "16b9379fb6e8610566fe5e1396166daf7106f165",
>     build_file = "tools/ccd.BUILD",
> ```

I actually have a Bazel branch of CCD, but I am waiting on the repo owner to PR something else first.

---

*[tools/cmake_configure_file.bzl, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-mAiAGQhUkBTgOpyx:-K_-mAiAGQhUkBTgOpyy:b-39ome8) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L56)):*
> ```Python
>     key-value "MYSCALAR=DOUBLE").
> 
>     Definitions optionally can be read from simple CMake listfiles that contain
> ```

CMakeLists files

---

*[tools/cmake_configure_file.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-mHmBzvrLWDCfDvGb:-K_-mHmBzvrLWDCfDvGc:bxuh1wy) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L3)):*
> ```Python
> #!/usr/bin/env python
> 
> """A re-implentation of CMake's configure_file substitution semanatics.  This
> ```

re-implementation, semantics

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jwnimmer-tri** [comment]
Thanks!

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/cmake_configure_file.bzl, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-mAiAGQhUkBTgOpyx:-K_-reMo6sd7DyFS_KG2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L56)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

CMakeLists files
</blockquote></details>

Done.

---

*[tools/cmake_configure_file.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-mHmBzvrLWDCfDvGb:-K_-rpSA1u___n4hhv3U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

re-implementation, semantics
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-K_-rql7jGjgOdRZMGwW:b-ucfknh)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by rpoyner-tri** [comment]
Reviewed 5 of 8 files at r1, 4 of 4 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[tools/cmake_configure_file.bzl, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_05O3pRRn7nrM2cExX:-K_05O3qv0gBfklgV8NA:b-akwfl3) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L44)):*
> ```Python
>         name,
>         src=None,
>         out=None,
> ```

What does it mean for 'src' and 'out' to default to None if both have attr definitions with 'mandatory=True' ?

---

*[tools/cmake_configure_file.bzl, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-q3j0wbXasOuQ2Wtp:-K_-q3j1vrA_RTOhnvcT:bpu2x09) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L49)):*
> ```Python
>         **kwargs):
>     """Creates a rule to generate an out= file from a src= file, using CMake's
>     configure_file substitution semanatics.  This implementation is incomplete,
> ```

typo 'semanatics'

---

*[tools/cmake_configure_file.bzl, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qCDx2LRRco_OYDKp:-K_-qCDyQO_Fk5my9SYf:b-sdpe8l) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L57)):*
> ```Python
> 
>     Definitions optionally can be read from simple CMake listfiles that contain
>     statements of the form "set(FOO_MAJOR_VERISON 1)" and similar.
> ```

typo 'VERISON'

---

*[tools/cmake_configure_file.py, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_06VbKs8aI042HrPbI:-K_06VbLvYJC4rkK7uq1:b-pp0243) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L7)):*
> ```Python
> all (or even many) cases.
> 
> """
> ```

BTW, consider copying or moving the ref-link to CMake configure-file documentation here.

---

*[tools/cmake_configure_file.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qXNn3c7qHuLf57nS:-K_-qXNojopST42LX1ki:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L10)):*
> ```Python
> 
> import argparse
> import logging
> ```

unused.

---

*[tools/cmake_configure_file.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qZZrg1FaKDdFvrdy:-K_-qZZrg1FaKDdFvrdz:b-rl3bzo) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L24)):*
> ```Python
> 
> # Transform a source code line per CMake's configure_file semantics.
> def _transform(line, definitions):
> ```

PEP8: all the module-level functions in this file want an additional blank line above.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-ui1ua2JYizjA8Xnf:-K_-ui1ua2JYizjA8Xng:b7pw4sf) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
> ```
>     srcs = glob(["include/**/*.h"]),
>     outs = ["include/fcl/fcl.h"],
>     cmd = "echo '#pragma once' > '$@' && echo '$(SRCS)' | xargs -n1 echo | sed -e 's|.*include/\\(.*\\)|#include \"\\1\"|g' >> '$@'",
> ```

BTW, some bash nerd improvements to consider:

 * Use as sub-shell '( )' to write the output in a single redirection.
 * Replace fork-bomb 'xargs -n1 echo' with "tr ' ' '\n'" for a somewhat noticeable performance boost.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-wHypAqnG8sNvkIqc:-K_-wHyq2loIIQoO04GA:b-u1ssrd) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
> ```
>     srcs = glob(["include/**/*.h"]),
>     outs = ["include/fcl/fcl.h"],
>     cmd = "echo '#pragma once' > '$@' && echo '$(SRCS)' | xargs -n1 echo | sed -e 's|.*include/\\(.*\\)|#include \"\\1\"|g' >> '$@'",
> ```

Long line. Can be broken up with enclosing parens and string-cat '+' signs.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_0-H108Nwn1lPF_uVf:-K_0-H119iMTGmz8hOGs:b-ob7nc2) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
> ```
>     srcs = glob(["include/**/*.h"]),
>     outs = ["include/fcl/fcl.h"],
>     cmd = "echo '#pragma once' > '$@' && echo '$(SRCS)' | xargs -n1 echo | sed -e 's|.*include/\\(.*\\)|#include \"\\1\"|g' >> '$@'",
> ```

BTW, some sed-head improvements to consider:

 * '-e' is not necessary;  the first argument will be recognized as a script automatically in this case.
 * consider '-r' to reduce '\' escaping hair.
 * The BUILD core language supports Python raw strings r"blah" for further hair reduction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jamiesnape** [comment]
Reviewed 5 of 8 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jwnimmer-tri** [comment]
Review status: 5 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[tools/cmake_configure_file.bzl, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_05O3pRRn7nrM2cExX:-K_08aVpu7KwK2vTP8WP:bawr6z2) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L44)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

What does it mean for 'src' and 'out' to default to None if both have attr definitions with 'mandatory=True' ?
</blockquote></details>

Skylark convention strongly prefers kwargs for everything but `name`.  Thus, I have to provide _some_ default here, and `None` seemed like a good one.

---

*[tools/cmake_configure_file.bzl, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-q3j0wbXasOuQ2Wtp:-K_086S807nG95iswxQz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L49)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo 'semanatics'
</blockquote></details>

Done.

---

*[tools/cmake_configure_file.bzl, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qCDx2LRRco_OYDKp:-K_0874U0dnI5VqdVYeR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.bzl#L57)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo 'VERISON'
</blockquote></details>

Done.

---

*[tools/cmake_configure_file.py, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_06VbKs8aI042HrPbI:-K_08slFMit031a5er32:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider copying or moving the ref-link to CMake configure-file documentation here.
</blockquote></details>

Done.

---

*[tools/cmake_configure_file.py, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qXNn3c7qHuLf57nS:-K_08CakgWw1ndq_kIS5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[tools/cmake_configure_file.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-qZZrg1FaKDdFvrdy:-K_08xjvCUvXKUJnWpM3:b-oyeulq) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/cmake_configure_file.py#L24)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

PEP8: all the module-level functions in this file want an additional blank line above.
</blockquote></details>

Done.

(I disagree with PEP8 on this but that ship sailed long ago.)

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-ui1ua2JYizjA8Xnf:-K_0BMkWBDeNDPdJlzjw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, some bash nerd improvements to consider:

 * Use as sub-shell '( )' to write the output in a single redirection.
 * Replace fork-bomb 'xargs -n1 echo' with "tr ' ' '\n'" for a somewhat noticeable performance boost.
</blockquote></details>

Done.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_-wHypAqnG8sNvkIqc:-K_0BAG4mlcHxuf1Xhik:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Long line. Can be broken up with enclosing parens and string-cat '+' signs.
</blockquote></details>

Done.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_0-H108Nwn1lPF_uVf:-K_0A8UdBFyLswd8fqpQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, some sed-head improvements to consider:

 * '-e' is not necessary;  the first argument will be recognized as a script automatically in this case.
 * consider '-r' to reduce '\' escaping hair.
 * The BUILD core language supports Python raw strings r"blah" for further hair reduction.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-K_0EcJQ7dqY0X1fH47D:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_0-H108Nwn1lPF_uVf:-K_0L0Xwyv8plYzti9IV:b10px60) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Whee!  OSX sed doesn't have `-r`.  I will repair.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/fcl.BUILD, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-K_0-H108Nwn1lPF_uVf:-K_0Oht1whI-L89sS4sw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3626ccd99230278ea0878093c3327d10a68a29d2/tools/fcl.BUILD#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Whee!  OSX sed doesn't have `-r`.  I will repair.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-K_0QusGO2i3RPiFs6Up:bz1t39v)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600)*

**Comment by sammy-tri** [comment]
(checkpoint, review still in progress)

---

Reviewed 2 of 8 files at r1, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-K_0gfG3QENRP5OR2joI:b-ujrq2m)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4600#-:-K_0wf_61yr1htpHu6MO:bnfp4nl)*

**Pull request merged**
