### PR TITLE
Add -O0 to dbg mode on all platforms.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri or @RussTedrake for all levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5224)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/CROSSTOOL, line 176 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5224#-KdHx1-FkeugHejwq3cE:-KdHx1-FkeugHejwq3cF:brwjutc) ([raw file](https://github.com/robotlocomotion/drake/blob/ac086e8c95dbf32d8c4a248047a20e4e9a123e6a/tools/CROSSTOOL#L176)):*
> ```
>     mode: DBG
>     compiler_flag: "-g"
>   }
> ```

Does this need `-O0` also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5224#-:-KdHx5Zi9EOXkv0I4NUe:bnfp4nl)*

**Comment by RussTedrake** [comment]
Did this address an issue?  I don't believe we've had it enabled for the CMAKE Debug mode, and it will likely notably slow things down.  Here is a snippet from my local CMakeCache.txt
```
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

//Flags used by the compiler during debug builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5224#-:-KdII8z6d2NuIMxBUN8S:byfj5fj)*

**Comment by jwnimmer-tri** [comment]
For GCC at least, I think an absent `-O#` means `-O0` so this should be no change.  I haven't been able to find out the clang default.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5224#-:-KdLH8JdgIM6q1kumjFh:b-4gw2f3)*

**Comment by david-german-tri** [comment]
Yes, the performance hit is pretty noticeable, at least on Clang.  I'll close this; individual developers can always change the optimization level with `--copt`.

**Pull request closed without merging**
