### PR TITLE
pydrake: Bind some missing multibody math-related items

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14193)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with minor nits

For my own curiosity, can you state the motivation for binding this?

Did you (or someone else) run into an acute lack of bindings?
Or is it more like "OMG it's easy to do this, stop beating around the bush and let's just do this"?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14193#-:-MJSoTmD3IW4XyrVAwFX:b-7gds4m)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/tree_py.cc, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSlhjuBsri2inTGPMS:-MJSlhjuBsri2inTGPMT:b1p6y1c) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/tree_py.cc#L38)):*
> ```cpp
> // It is fine to use this at a file-wide scope since in practice we only
> // encounter these warnings in bindings due to pybind11's operators.
> #if (__clang__) && (__clang_major__ >= 9)
> ```

BTW For traceability, it may help to have this comment match `math_py.cc`s comment. Consider having them match by using one or the other.

(This seems best.)
___
*[bindings/pydrake/multibody/tree_py.cc, line 683 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSmTx43WOPOzyE4ur5:-MJSmTx43WOPOzyE4ur6:b-r6ifyp) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/tree_py.cc#L683)):*
> ```cpp
>             cls_doc.CalcMaximumPossibleMomentOfInertia.doc)
>         .def(
>             "__getitem__",
> ```

nit We should encode this convention of "use getitem when that's what C++ wanted, but couldn't express and instead used operator()".

Would you be up for encoding this briefly in `pydrake_doxygen.h`, or would you like me to do this in a separate PR?
___
*[bindings/pydrake/multibody/test/math_test.py, line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSnDI-45z1NQNoHlHJ:-MJSnDI0DbNpwUk6-hSC:ba0w4z3) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/test/math_test.py#L135)):*
> ```Python
>         """
>         to_T = np.vectorize(T)
>         p = to_T(np.zeros(3))
> ```

nit `p` is confusing when it's also used for angular velocity arguments.

Please either rename this variable to something neutral (e.g. `z`), or define `w = to_T(np.zeros(3))`.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSng7FCC4nPZrhokUm:-MJSng7FCC4nPZrhokUn:b8wywpm) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/test/plant_test.py#L427)):*
> ```Python
>         dut.CalcMaximumPossibleMomentOfInertia()
>         self.assertIsInstance(dut[0, 0], T)
>         with self.assertRaises(Exception):
> ```

nit `assertRaises(Exception)` is too generic for Python, as it could mean that pretty much anything went wrong.

Can you instead capture either `TypeError`, `ValueError`, or something that will capture the more acute exception.

(I get why we promise that in C++, and I guess it's OK to not promise anything in the Python API, but I don't think it's healthy just to check `Exception` in unittest code.)

**Review by jwnimmer-tri — COMMENTED** [review]
I decided to finish binding `pydrake.multibody...` because I was embarrassed that we didn't have it yet, especially when finishing it is so easy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14193#-:-MJSuToc91DB44ayGOam:b-crxgma)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/tree_py.cc, line 683 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSmTx43WOPOzyE4ur5:-MJStM5u0uEP20Jo02Zi:bds9o1o) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/tree_py.cc#L683)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit We should encode this convention of "use getitem when that's what C++ wanted, but couldn't express and instead used operator()".

Would you be up for encoding this briefly in `pydrake_doxygen.h`, or would you like me to do this in a separate PR?
</blockquote></details>

OK I think you would do better on your own in another if you want to work on the policy language.

I used this formulation for consistency with numpy, not because I thought C++ wanted it this way.
___
*[bindings/pydrake/multibody/test/math_test.py, line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSnDI-45z1NQNoHlHJ:-MJSsUrH0OzJ6TxU2EZ5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/test/math_test.py#L135)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `p` is confusing when it's also used for angular velocity arguments.

Please either rename this variable to something neutral (e.g. `z`), or define `w = to_T(np.zeros(3))`.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSng7FCC4nPZrhokUm:-MJSuFwQD8V09dUxIBX-:b-sdgoyt) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/test/plant_test.py#L427)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `assertRaises(Exception)` is too generic for Python, as it could mean that pretty much anything went wrong.

Can you instead capture either `TypeError`, `ValueError`, or something that will capture the more acute exception.

(I get why we promise that in C++, and I guess it's OK to not promise anything in the Python API, but I don't think it's healthy just to check `Exception` in unittest code.)
</blockquote></details>

Done.

The message seems more important than the subclass.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14193)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

___
*[bindings/pydrake/multibody/tree_py.cc, line 683 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14193#-MJSmTx43WOPOzyE4ur5:-MJSyYsh2aGs94qa298R:bl00cdx) ([raw file](https://github.com/robotlocomotion/drake/blob/6376ee51f8d300e3b103b3df3e5975de415ae6cf/bindings/pydrake/multibody/tree_py.cc#L683)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I think you would do better on your own in another if you want to work on the policy language.

I used this formulation for consistency with numpy, not because I thought C++ wanted it this way.
</blockquote></details>

OK SGTM!

**Review by EricCousineau-TRI — COMMENTED** [review]
Aye, makes sense!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14193#-:-MJSydzsBEnQBYHwUT2H:botl68a)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
