### PR TITLE
Implements quaternion mobilizer for free bodies.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implementation in `quaternion_floating_mobilizer.h/.cc`. Testing in `floating_body_test.cc`.
Additionally, bug fixes in `MultibodyTree<T>::MapVelocityToQDot()` and `MobilizerImpl::get_mutable_velocities()`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8135)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please. Don't get scared by the lines counts, lots of boilerplate and docs (which hopefully help you review).

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L5uBHPeeJRd0TGEKCpX:b-uelw58)*

**Comment by hongkai-dai** [comment]
Checkpoint.

---

Reviewed 1 of 16 files at r2.
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vHp2-u3jj9ilA2p-k:-L5vHp2-u3jj9ilA2p-l:b-yx1m56) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L37)):*
> ```cpp
>   const MultibodyTreeContext<T>& mbt_context =
>       this->GetMultibodyTreeContextOrThrow(context);
>   auto q = this->get_positions(mbt_context);
> ```

`const auto`?

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vDnQUGIb9xaYaoJHU:-L5vDnQUGIb9xaYaoJHV:bnh7vfy) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L49)):*
> ```objc
>   ///   the inboard frame F.
>   /// @param[in] outboard_frame_M
>   ///   the outboard frame M which can move freely with respect to frame M.
> ```

with respect to frame `F`?

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vE_owleO_D8VBNnNC:-L5vE_owleO_D8VBNnND:b2mkd7h) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L87)):*
> ```objc
>   ///   The desired orientation of M in F to be stored in `context`.
>   /// @returns a constant reference to `this` mobilizer.
>   const QuaternionFloatingMobilizer<T>& set_quaternion(
> ```

I am bit concerned to have a const method with name containing `set`. Besides I think we should put `out` parameter AFTER `in` parameter?

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5vIr_fvFyYKQQZgZN7:bmsqw6r) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
> ```objc
>   static Eigen::Matrix<T, 4, 3> CalcLMatrix(const Quaternion<T>& q);
>   // Helper to compute the kinematic map N(q) for which q̇ = N(q)v.
>   // With L given by CalcLMatrix we have:
> ```

Would you think it is cleaner if we put that `1/2` inside the calculation of `L` matrix? Namely define `L` as
```
          |         -qv_Fᵀ    |  * 0.5
   L(q) = | qs * Id - [qv_F]x |
```
So that we do not need to worry about multiplying `2` or `1/2` when we call `CalcLMatrix` when computing `N` or its pseudo-inverse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L5vKSBsKYAzvPcJMDv7:by96gdd)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vHp2-u3jj9ilA2p-k:-L5yKTf8NKolhCf6HdIx:b-ptdmv0) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const auto`?
</blockquote></details>

In this case the `auto` would resolve to `VectorBlock<const VectorX<T>>` which already has the `const` flavor. However, I do agree `cost auto` spells out intentions more nicely. Done.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vDnQUGIb9xaYaoJHU:-L5yMuMJh4OF-NKw5baM:b-i21bbo) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L49)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

with respect to frame `F`?
</blockquote></details>

Thanks. Done.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vE_owleO_D8VBNnNC:-L5yNOqRZri5GmJUg303:b-9d1hnm) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am bit concerned to have a const method with name containing `set`. Besides I think we should put `out` parameter AFTER `in` parameter?
</blockquote></details>

We actually made an amendment to the style guide for this, [here](http://drake.mit.edu/styleguide/cppguide.html#Function_Parameter_Ordering). The idea being able to provide a homogeneous API. Notice that users will never have access to a mutable `Mobilizer` object or any other MBT object. Therefore they can only make modifications to the `Context` through the MBT API but not to the MBT itself.
Then we'd have `mbt_object.get_foo(context)` and `mbt_object.set_foo(&context, foo_value, other_parameters)`, which reads nicely and homogeneous.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5yOKLK19ZI1d86hhJU:b-vtmoxf) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would you think it is cleaner if we put that `1/2` inside the calculation of `L` matrix? Namely define `L` as
```
          |         -qv_Fᵀ    |  * 0.5
   L(q) = | qs * Id - [qv_F]x |
```
So that we do not need to worry about multiplying `2` or `1/2` when we call `CalcLMatrix` when computing `N` or its pseudo-inverse.

</blockquote></details>

A fine idea. However I opted for this version for two reasons:
1. It leads to less floating point operations to do the multiplications first (4 vs. 12).
2. It actually is more compact and reads more nicely in math, no? (this last one more subjective) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vE_owleO_D8VBNnNC:-L5yPsvHR_M8MRqkMvbF:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L87)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

We actually made an amendment to the style guide for this, [here](http://drake.mit.edu/styleguide/cppguide.html#Function_Parameter_Ordering). The idea being able to provide a homogeneous API. Notice that users will never have access to a mutable `Mobilizer` object or any other MBT object. Therefore they can only make modifications to the `Context` through the MBT API but not to the MBT itself.
Then we'd have `mbt_object.get_foo(context)` and `mbt_object.set_foo(&context, foo_value, other_parameters)`, which reads nicely and homogeneous.
</blockquote></details>

Got it, thanks!

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5yQ1d5I5Xf6qtSIK2_:b10qc6y) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

A fine idea. However I opted for this version for two reasons:
1. It leads to less floating point operations to do the multiplications first (4 vs. 12).
2. It actually is more compact and reads more nicely in math, no? (this last one more subjective) 
</blockquote></details>

I am fine either way, just threw a suggestion. Good point on the number of floating  point operations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5yTuEooiqmj40_8LRA:bvc5jwl) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am fine either way, just threw a suggestion. Good point on the number of floating  point operations.
</blockquote></details>

Just to be clear, I mean to put the constant factor 0.5 inside the function CalcLMatrix. Inside CalcLMatrix, you can still do
```
q_half = q * .5;
L = function of q_half
```
This leaves the same amount of floating point calculation.

Again, it is up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5yWXaJJk7refok4rYt:b-7leini) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just to be clear, I mean to put the constant factor 0.5 inside the function CalcLMatrix. Inside CalcLMatrix, you can still do
```
q_half = q * .5;
L = function of q_half
```
This leaves the same amount of floating point calculation.

Again, it is up to you.
</blockquote></details>

humm... Maybe I don't understand your point yet, but if you look at the computation for Nplus, that requires `L(2 * q)` (instead of `L(q/2)`). So not including the factor allows me to reuse `L` for both `N(q)` and `Nplus(q)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vIr_fvFyYKQQZgZN6:-L5y_jEI82JhrYD1pNsk:b-svvhpp) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L231)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

humm... Maybe I don't understand your point yet, but if you look at the computation for Nplus, that requires `L(2 * q)` (instead of `L(q/2)`). So not including the factor allows me to reuse `L` for both `N(q)` and `Nplus(q)`.
</blockquote></details>

Got it, makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform review please.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L5zQN9Viubm_4HSLA1s:b-vt9vbo)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 16 files at r2, 3 of 3 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/test/floating_body_plant.cc, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5znN5kzb6N03ifVfQM:-L5znN5kzb6N03ifVfQN:b-nau4vu) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.cc#L103)):*
> ```cpp
> 
>   // With vdot = 0, this computes:
>   //   tau = C(q, v)v - tau_app - ∑ J_WBᵀ(q) Fapp_Bo_W.
> ```

Does this include the gravitational force?

---

*[multibody/multibody_tree/test/floating_body_plant.cc, line 113 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zn6z--GJrxD-WlysL:-L5zn6z--GJrxD-WlysM:b5hehbl) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.cc#L113)):*
> ```cpp
>       &tau_array);
> 
>   vdot = M.ldlt().solve(-tau_array);
> ```

Is `M` positive definite here? If so, better to use `llt` instead of `ldlt`?

---

*[multibody/multibody_tree/test/floating_body_plant.h, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zfMS8V377o3ARAFZK:-L5zfMS8V377o3ARAFZL:bvzegi0) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.h#L17)):*
> ```objc
> 
> /// This plant models the free motion of a torque free body in space.
> /// This body is axially symmetric with rotational inertia about its axis of
> ```

Would be better if we say it explicitly, that the axis of symmetry is the same as the axis of revolution.

---

*[multibody/multibody_tree/test/floating_body_plant.h, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zlXoPVpzOK6n4E97Q:-L5zlXoPVpzOK6n4E97R:b-6hryz) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.h#L42)):*
> ```objc
>   ///   revolution of the body.
>   /// @param J
>   ///   rotational inertia about the axis of revolution of the body.
> ```

Document `g` as well? `g` should be positive, being the magnitude of the gravitational acceleration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 16 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/test/floating_body_plant.h, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zfMS8V377o3ARAFZK:-L5zqup5KqFlPKqh4JtN:b-uu9gyi) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.h#L17)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would be better if we say it explicitly, that the axis of symmetry is the same as the axis of revolution.
</blockquote></details>

Maybe change the name to `AxialSymmetricFloatingBodyPlant`, and mention it in the documentation that the trajectory of this system has an analytical solution.

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zrOrp3LQpNpPN98_p:-L5zrOrp3LQpNpPN98_q:bqfg3j9) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_test.cc#L41)):*
> ```cpp
>   // There are no external forces in this test, not even gravity.
>   const double acceleration_of_gravity = 9.81;
>   Vector3d gravity_W = -acceleration_of_gravity * Vector3d::UnitZ();
> ```

BTW, const Vector3d

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L5zscgSfGrXLcJH_iiY:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5vE_owleO_D8VBNnNC:-L62UzUuvhOJW2EWgGVz:bzh25e2) ([raw file](https://github.com/robotlocomotion/drake/blob/c03206923d54e550c0f302fdaa41b6e3c91f52fd/multibody/multibody_tree/quaternion_floating_mobilizer.h#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Got it, thanks!
</blockquote></details>

Thank you for reviewing!

---

*[multibody/multibody_tree/test/floating_body_plant.cc, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5znN5kzb6N03ifVfQM:-L62OHMGYVn7yyzZuENu:b-j6i5ht) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.cc#L103)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Does this include the gravitational force?
</blockquote></details>

Correct. Since in this case the only applied forces are those due to gravity, I decided to simplify the comment.

---

*[multibody/multibody_tree/test/floating_body_plant.cc, line 113 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zn6z--GJrxD-WlysL:-L62QlhuZ3z2wQS3BZjC:bfiywxs) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.cc#L113)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is `M` positive definite here? If so, better to use `llt` instead of `ldlt`?
</blockquote></details>

I've been mostly using it out of habit when I had some more difficult problems where robustness was more important than speed. Clearly in this case LLT is the right choice. Soon this will get replace by a real O(n) forward dynamics!

---

*[multibody/multibody_tree/test/floating_body_plant.h, line 17 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zfMS8V377o3ARAFZK:-L62SeWLzutuGv-oc3Hj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.h#L17)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe change the name to `AxialSymmetricFloatingBodyPlant`, and mention it in the documentation that the trajectory of this system has an analytical solution.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/test/floating_body_plant.h, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zlXoPVpzOK6n4E97Q:-L62UN4wESQzMYas7d-K:b-czmepe) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_plant.h#L42)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document `g` as well? `g` should be positive, being the magnitude of the gravitational acceleration.
</blockquote></details>

Woops, I forgot, thanks.

---

*[multibody/multibody_tree/test/floating_body_test.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L5zrOrp3LQpNpPN98_p:-L62UtfNNr_I8Fc6-Z6Q:bhxa6x4) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/test/floating_body_test.cc#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, const Vector3d
</blockquote></details>

BTW I had forgotten a bunch of `const`'s here, I add them all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by soonho-tri** [comment]
Checkpoint.

---

Reviewed 3 of 16 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L62WfJjHIGu96CZNRX_:-L62WfJjHIGu96CZNRXa:b-3pbfr3) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L4)):*
> ```cpp
> 
> #include <memory>
> #include <stdexcept>
> ```

BTW, not used?

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L62Xj4kyZyWVqDkVtjA:-L62Xj4kyZyWVqDkVtjB:bmhozy9) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L148)):*
> ```cpp
> QuaternionFloatingMobilizer<T>::set_translational_velocity(
>     systems::Context<T>* context, const Vector3<T>& v_FM) const {
>   return set_angular_velocity(*context, v_FM, &context->get_mutable_state());
> ```

I think it should be `set_translational_velocity`?

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.h, line 232 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L62Py9Bau8VMNtawFE9:-L62Py9Bau8VMNtawFEA:bwz2dgz) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/quaternion_floating_mobilizer.h#L232)):*
> ```objc
>   // Helper to compute the kinematic map N(q) for which q̇ = N(q)v.
>   // With L given by CalcLMatrix we have:
>   // N(q) = [L(q_FM/2) 0₄ₓ₃
> ```

BTW, nit, need a closing `]` at the end? (also for `N⁺(q)` below and `.cc` file)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L62YeODj_88gYuOdZ-j:by96gdd)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L62hCpL-QUM2RGgzjpS:bnfp4nl)*

**Comment by amcastro-tri** [comment]
While at it, I simplified things a bit by avoiding the big zeroes within the `N(q)` matrices, and use the fact there's a bit identity matrix in one of the blocks. Unit tests still pass, indicating this is equivalent. PTAL.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 148 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L62Xj4kyZyWVqDkVtjA:-L62wjm5H2iWVA3ckO6Z:blvka6d) ([raw file](https://github.com/robotlocomotion/drake/blob/f91c1b1477c947a29d1c03d3b01ea0dddb369b8a/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L148)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it should be `set_translational_velocity`?
</blockquote></details>

Shame on me. Added missing unit tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L634kV1Moq1Y4GWqGrC:blu7emx)*

**Comment by soonho-tri** [comment]
Looks cleaner to me. @hongkai-dai could you confirm the updates in `QuaternionFloatingMobilizer` are sound?

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-:-L635pXFdLJQsXn9AYfG:btih2t)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 218 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L63FrxTOF6rZZh4aRGa:-L63FrxTOF6rZZh4aRGb:b-n5tpae) ([raw file](https://github.com/robotlocomotion/drake/blob/5db2bdabfc6b556f902904bb6c9524ec15036fdd/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L218)):*
> ```cpp
>   // This L matrix helps us compute both N(q) and N⁺(q) since it turns out that:
>   //   N(q) = [L(q_FM/2) 0₄ₓ₃]
>   //          [     0₃ₓ₃   I₃]
> ```

This documentation needs to be updated. N(q) and its pseudo inverse has changed the size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by amcastro-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/quaternion_floating_mobilizer.cc, line 218 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/8135#-L63FrxTOF6rZZh4aRGa:-L63T5gltpKEy3_TNmtR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5db2bdabfc6b556f902904bb6c9524ec15036fdd/multibody/multibody_tree/quaternion_floating_mobilizer.cc#L218)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This documentation needs to be updated. N(q) and its pseudo inverse has changed the size.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8135)*

**Pull request merged**
