### PR TITLE
sort the result of ComputeSignedDistanceToPoint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #13739

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709#-:-O1XZpceAbSulQvTfPyh:bltfyse)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of small tweaks.

+(release notes: fix) 
+@jwnimmer-tri for platform review, please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709#-:-O1quDcF3uoh1HaPzSgk:bwurpyc)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/query_object.h` line 791 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21709#-O1qrSEQ2mqenZPqkAWI:-O1qrSEQ2mqenZPqkAWJ:b-luodjc) ([raw file](https://github.com/RobotLocomotion/drake/blob/4878fc8238fec26036bf5e855c0e6e3da774c165/geometry/query_object.h#L791)):*
> ```objc
>                               results is guaranteed to be consistent -- for
>                               fixed geometry poses, the results will remain the
>             same.*/
> ```

nit: Odd whitespace on the final line.
___
*[`geometry/test/proximity_engine_test.cc` line 940 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21709#-O1qtLb85TUwhT83jUHy:-O1qtLb85TUwhT83jUHz:b-haqzzb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4878fc8238fec26036bf5e855c0e6e3da774c165/geometry/test/proximity_engine_test.cc#L940)):*
> ```cpp
>                                           -kPenetration * 0.5 - kEps);
>   EXPECT_EQ(results_barely_out.size(), 0u);
> }
> ```

nit This test passes even if I comment out the new line to sort the results. So, this test is protection against some bizarre change that would ruin this very specific test, but it doesn't really *prove* the correctness of the code.

This change to the code *does* fail without the `sort`.

Note: The code snippet below is badly formatted so that only the *meaningful* changes get highlighted by reviewable. You'll want to fix the indentation introduced by the for loop after pasting it into the code.



_Suggestion:_
```cpp
GTEST_TEST(ProximityEngineTests, SignedDistanceToPointNonPositiveThreshold) {
  const double kRadius = 0.5;
  const double kPenetration = kRadius * 0.1;

  const GeometryId id_A = GeometryId::get_new_id();
  const GeometryId id_B = GeometryId::get_new_id();
  const unordered_map<GeometryId, RigidTransformd> X_WGs{
      {id_A,
       RigidTransformd{Translation3d{-kRadius + 0.5 * kPenetration, 0, 0}}},
      {id_B,
       RigidTransformd{Translation3d{kRadius - 0.5 * kPenetration, 0, 0}}}};

  Sphere sphere{kRadius};
  for (bool flip_order : {true, false}) {
    ProximityEngine<double> engine;
    // Confirm the results are sorted, regardless of the order the spheres are
    // added to the engine.
    const GeometryId first_id = flip_order ? id_B : id_A;
    const GeometryId second_id = flip_order ? id_A : id_B;
  engine.AddDynamicGeometry(sphere, {}, first_id);
  engine.AddDynamicGeometry(sphere, {}, second_id);
  engine.UpdateWorldPoses(X_WGs);

  const Vector3d p_WQ{0, 0, 0};
  std::vector<SignedDistanceToPoint<double>> results_all =
      engine.ComputeSignedDistanceToPoint(p_WQ, X_WGs, kInf);
  EXPECT_EQ(results_all.size(), 2u);
  // Make sure the result is sorted.
  auto parameters_in_order = [](const SignedDistanceToPoint<double>& p1,
                                const SignedDistanceToPoint<double>& p2) {
    return p1.id_G < p2.id_G;
  };
  EXPECT_TRUE(parameters_in_order(results_all[0], results_all[1]));

  std::vector<SignedDistanceToPoint<double>> results_zero =
      engine.ComputeSignedDistanceToPoint(p_WQ, X_WGs, 0);
  EXPECT_EQ(results_zero.size(), 2u);
  EXPECT_TRUE(parameters_in_order(results_zero[0], results_zero[1]));

  const double kEps = std::numeric_limits<double>::epsilon();

  std::vector<SignedDistanceToPoint<double>> results_barely_in =
      engine.ComputeSignedDistanceToPoint(p_WQ, X_WGs,
                                          -kPenetration * 0.5 + kEps);
  EXPECT_EQ(results_barely_in.size(), 2u);
  EXPECT_TRUE(parameters_in_order(results_barely_in[0], results_barely_in[1]));

  std::vector<SignedDistanceToPoint<double>> results_barely_out =
      engine.ComputeSignedDistanceToPoint(p_WQ, X_WGs,
                                          -kPenetration * 0.5 - kEps);
  EXPECT_EQ(results_barely_out.size(), 0u);
  }
}
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/test/proximity_engine_test.cc` line 940 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21709#-O1qtLb85TUwhT83jUHy:-O1r5n5o95UoqNV1d689:boyexb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/4878fc8238fec26036bf5e855c0e6e3da774c165/geometry/test/proximity_engine_test.cc#L940)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit This test passes even if I comment out the new line to sort the results. So, this test is protection against some bizarre change that would ruin this very specific test, but it doesn't really *prove* the correctness of the code.

This change to the code *does* fail without the `sort`.

Note: The code snippet below is badly formatted so that only the *meaningful* changes get highlighted by reviewable. You'll want to fix the indentation introduced by the for loop after pasting it into the code.
</blockquote></details>

Done. Thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709)* status: 2 unresolved discussions

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21709)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
