### PR TITLE
Disable tests that are failing valgrind in CI

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14311)

### CODE REVIEW

**Comment by ggould-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Review by ggould-tri — COMMENTED** [review]
+@sherm1 can I get a quick badge on this to clear up CI?
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14311#-:-MLmwE9X34JBAkFAK4Rx:blo6ui)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri -@sherm1

:lgtm: both reviews.

For reference: https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-valgrind-memcheck/725/

```
//multibody/fem/dev:fem_elasticity_test                                  FAILED in 2.2s
//multibody/fem/dev:fem_state_test                                       FAILED in 1.7s
//multibody/fem/dev:linear_elasticity_model_cache_test                   FAILED in 2.3s
```

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14311#-:-MLn1_QhDODmL2aeNLTQ:ben0jnx)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review

**Comment by jwnimmer-tri** [comment]
\CC @xuchenhan-tri FYI

**Comment by sherm1** [comment]
Filed issue #14312 to track fix.

**Pull request merged**
