### PR TITLE
[relnotes] Use pull request labels to exclude non-notable commits

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Using the process documented in #15339.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for your review and testing (as you shepherd the pending release), please.

**Review by ggould-tri — COMMENTED** [review]
Testing this today.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347#-:-MePrWkE1nkOBVJid-uY:b-kdueme)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15347#-MePra5aAau4d4tZHjHC:-MePra5aAau4d4tZHjHD:b-q4kqq6) (no related file):*
Placeholder for practical testing.

---

**Review by ggould-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347#-:-MeVLc2a2WvmEhLA2zSr:bg7igkv)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15347#-MePra5aAau4d4tZHjHC:-MeVLSR37Gk9R4Qt6fxp:b-pwkkk4) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Placeholder for practical testing.
</blockquote></details>

This appears to work as advertised.

---

**Comment by jwnimmer-tri** [comment]
@ggould-tri FYI possibly of note here, the tool does not yet automatically collate "breaking changes" PRs atop the document.  For now, the release manager will have to run the query on github.com website directly.  We can imagine semi-automating that in the next spin.

+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347#-:-MeVPJQf7vC1rE1EF5mh:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/release_engineering/relnotes.py, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15347#-MeVORFE8aVLv_OxFnin:-MeVORFF157vzPFTaLWn:bo3amn6) ([raw file](https://github.com/robotlocomotion/drake/blob/2c9c3c7b6b959c9ae33f0ab8c60f79d74e6f69ff/tools/release_engineering/relnotes.py#L94)):*
> ```
> numbert
> ```
typo

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347)* status: 1 unresolved discussion (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/release_engineering/relnotes.py, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15347#-MeVORFE8aVLv_OxFnin:-MeVQTsl80HeqB7aYPls:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c9c3c7b6b959c9ae33f0ab8c60f79d74e6f69ff/tools/release_engineering/relnotes.py#L94)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> numbert
> ```
typo
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15347)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
