### PR TITLE
tutorials: convert dynamical_systems tutorial to colab

### PR DESCRIPTION
**Pull request by RussTedrake**
Once we are happy with this one, I can quickly convert the rest.

You can test this using
https://colab.research.google.com/github/RussTedrake/drake/blob/one_colab_tutorial/tutorials/dynamical_systems.ipynb

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQD8f4tEyEv7iWOpyek:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@rpoyner-tri for platform review please.

Just curious, how do you convert the tutorial to colab? Is it as simple as creating a colab notebook and pasting the old ipynb to the colab notebook on the browser?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQDMNBe50oMEw7TWI5N:bszzphn)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

___
*[tutorials/dynamical_systems.ipynb, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14483#-MQDSrvi7xgF4Xo23z4H:-MQDSrvj08Wx58bhEVup:b-ie2x36) ([raw file](https://github.com/robotlocomotion/drake/blob/74bb9a42eb39f2d8373778013b282e1be9304c02/tutorials/dynamical_systems.ipynb#L336)):*
> ```
> FixInputPort
> ```
I think this method is in the throes of deprecation. Do we need to update the advice here? /cc @jwnimmer-tri @sherm1

**Review by RussTedrake — COMMENTED** [review]
cc @jwnimmer-tri and @ericcousineau-tri , who have expressed their opinions on this before, too.

@hongkai-dai -- you can navigate colab to any notebook on github as a starting point.  E.g. https://colab.research.google.com/github/RobotLocomotion/drake/blob/master/tutorials/linear_program.ipynb 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQDSnZP8g5mWppcmXFa:b-elzdnf)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: modulo possibly deprecated advice

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQDTFJ1-ej234cNjjXs:b9m0sxx)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
All I have to say is already captured in #13683.

Given that we're going to relocate these files into a new repository, is the plan to first switch to colab within Drake, and then second relocate to a new repo?

**Comment by jwnimmer-tri** [comment]
___
*[tutorials/dynamical_systems.ipynb, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14483#-MQDSrvi7xgF4Xo23z4H:-MQDUG9VBTYnwUa9QE5_:bt5aq0v) ([raw file](https://github.com/robotlocomotion/drake/blob/74bb9a42eb39f2d8373778013b282e1be9304c02/tutorials/dynamical_systems.ipynb#L336)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> FixInputPort
> ```
I think this method is in the throes of deprecation. Do we need to update the advice here? /cc @jwnimmer-tri @sherm1 
</blockquote></details>

I was going to say that "PRs should do one thing well, so I would argue against mixing changes to modernize the text with the change to the hosting engine." but then I noticed that the PR is _already_ making a revision to the text, so I think it either needs to be fixed use the correct API link, or else revert to keeping the old text intact.  If the text change remains, then the PR overview and commit message should be rebased to reflect that there are multiple changes happening and describe what they are.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[tutorials/dynamical_systems.ipynb, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14483#-MQDSrvi7xgF4Xo23z4H:-MQDWxp-E8mCv_iBxvNr:b38yq6a) ([raw file](https://github.com/robotlocomotion/drake/blob/74bb9a42eb39f2d8373778013b282e1be9304c02/tutorials/dynamical_systems.ipynb#L336)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was going to say that "PRs should do one thing well, so I would argue against mixing changes to modernize the text with the change to the hosting engine." but then I noticed that the PR is _already_ making a revision to the text, so I think it either needs to be fixed use the correct API link, or else revert to keeping the old text intact.  If the text change remains, then the PR overview and commit message should be rebased to reflect that there are multiple changes happening and describe what they are.
</blockquote></details>

Yeah, not easy to read this kind of diff and even tell if the text changed. :/

**Comment by jwnimmer-tri** [comment]
___
*[tutorials/dynamical_systems.ipynb, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14483#-MQDSrvi7xgF4Xo23z4H:-MQDYojpAE6Dw-QERpwX:btdg5o7) ([raw file](https://github.com/robotlocomotion/drake/blob/74bb9a42eb39f2d8373778013b282e1be9304c02/tutorials/dynamical_systems.ipynb#L336)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Yeah, not easy to read this kind of diff and even tell if the text changed. :/
</blockquote></details>

Actually, it looks like this notebook was converted from a stale revision.  The PR #14093 changed the tutorial, but this PR is trying to revert that change.  The text should simply stay unchanged, it was correct before.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[tutorials/dynamical_systems.ipynb, line 336 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14483#-MQDSrvi7xgF4Xo23z4H:-MQDdwEzAyCNGORaMfpZ:b6zrrkh) ([raw file](https://github.com/robotlocomotion/drake/blob/74bb9a42eb39f2d8373778013b282e1be9304c02/tutorials/dynamical_systems.ipynb#L336)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually, it looks like this notebook was converted from a stale revision.  The PR #14093 changed the tutorial, but this PR is trying to revert that change.  The text should simply stay unchanged, it was correct before.
</blockquote></details>

Good catch.

**Review by RussTedrake — COMMENTED** [review]
That was my (implicit) proposal, but only because I'd like to move this migration along.  I think setting up the new repo first would make more sense.  I can certainly create the repo and put this file there.. but setting up the "little extra infrastructure" is probably on @jamiesnape .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQDtkw75-xjTmcbd-pQ:bwuxf2r)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
That's fine by me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14483#-:-MQDvV062RaYiv95ttrW:bxajhl7)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
closing this, as our colab status is totally foo-bar'd until we resolve the Python 3.7 issue.  will need to revisit with a more complete solution.

**Pull request closed without merging**
