### PR TITLE
Tidy up name preservation during transmogrification

### LINKED ISSUE #7108: System::set_name during transmogrification is brittle
The code by which `System`'s names are propagated during transmogrification (AutoDiffXd, etc.) is not properly encapsulated, and thus its brittle and duplicated.  We should try to find a way to consolidate it.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7108.  Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7113)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.
+@SeanCurtis-TRI for platform review per rotation, please.

**Comment by SeanCurtis-TRI** [comment]
Two quick questions... otherwise :LGTM:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 1180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2kdarER8Kg8yk-S4P:-Kv2kdas3uldWwGva120:b8ne6i8) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/diagram.h#L1180)):*
> ```objc
>       DRAKE_DEMAND(new_system != nullptr);
> 
>       // Scalar conversion preserves the name; however, if DiagramBuilder
> ```

It isn't clear to me why this happens here and not just part of the conversion `SystemScalarConverter` -- then it's truly a one-stop shop.

---

*[drake/systems/framework/test/diagram_test.cc, line 449 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2l4rzGrCtXk2146eW:-Kv2l4rzGrCtXk2146eX:b-cb4ny4) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/test/diagram_test.cc#L449)):*
> ```cpp
>   const std::string original_name = integrator->get_name();
>   EXPECT_EQ(original_name, integrator->GetMemoryObjectName());
>   EXPECT_NE(original_name, "");
> ```

FYI This is robust, but surely we've already tested elsewhere that `GetMemoryObjectName()` does *not* return an empty string  (e.g., `system_test.cc`)? Or does this test something else that I'm missing? (Same applies below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv2lzJZQBRQRGO7jBU9:bjiqq0b)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/diagram.h, line 1180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2kdarER8Kg8yk-S4P:-Kv2nm-0NcDjdJ1qSBmD:b-wocptp) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/diagram.h#L1180)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It isn't clear to me why this happens here and not just part of the conversion `SystemScalarConverter` -- then it's truly a one-stop shop.
</blockquote></details>

Hmm, interesting.  My thought was that the "curate the default name" behavior was a responsibility of the Diagram that contains the System, not the System framework in general.  If the user crafts some bespoke system and sets it to use GetMemoryObjectName, should we change the name when we transmogrify?  My intuition was "no".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 1180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2kdarER8Kg8yk-S4P:-Kv2sQOQ6KxGrkwGJcKs:b-smd6tf) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/diagram.h#L1180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, interesting.  My thought was that the "curate the default name" behavior was a responsibility of the Diagram that contains the System, not the System framework in general.  If the user crafts some bespoke system and sets it to use GetMemoryObjectName, should we change the name when we transmogrify?  My intuition was "no".
</blockquote></details>

I have several thoughts: 
1. Given the nature of the "default" name, it's definitely screwy when transmogrified/cloned to have the old pointer address at all. Do we handle this for cloning?
2. `DiagramBuilder` is the one that sets this "default" name, but `Diagram` is now the entity that corrects it upon conversion. That feels like a bit of an odd disconnect. However, this clearly shortcuts the builder process...in some sense, duplicating it. So, it's probably alright. (except now the word "duplicate" hangs in my mind.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/diagram.h, line 1180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2kdarER8Kg8yk-S4P:-Kv2vdeoWmAQ0FfVyZY2:bbyv4c3) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/diagram.h#L1180)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I have several thoughts: 
1. Given the nature of the "default" name, it's definitely screwy when transmogrified/cloned to have the old pointer address at all. Do we handle this for cloning?
2. `DiagramBuilder` is the one that sets this "default" name, but `Diagram` is now the entity that corrects it upon conversion. That feels like a bit of an odd disconnect. However, this clearly shortcuts the builder process...in some sense, duplicating it. So, it's probably alright. (except now the word "duplicate" hangs in my mind.)
</blockquote></details>

(1) `System`s are not clone-able.  (Well, you can transmogrify and then reverse-transmogrify, but meh.)  Also, here the "default" of MemoryObjectName is not a global or Drake-wide default, but rather a "when you add it to a Diagram" default.

(2) The Build and DiagramBuilder are C++ friends; I think a little sharing between the two is OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 1180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2kdarER8Kg8yk-S4P:-Kv2xe4y8ksJ3OI54dEa:b-ba7jcz) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/diagram.h#L1180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1) `System`s are not clone-able.  (Well, you can transmogrify and then reverse-transmogrify, but meh.)  Also, here the "default" of MemoryObjectName is not a global or Drake-wide default, but rather a "when you add it to a Diagram" default.

(2) The Build and DiagramBuilder are C++ friends; I think a little sharing between the two is OK.
</blockquote></details>

Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by amcastro-tri** [comment]
I personally would've preferred the name to be an "invariant", even in the case when `Diagram` provided a wacky default name containing a memory address. Is that part of the contract? meaning, does the user know that that wacky name was generated using a memory address? would the user try to convert the string back to a memory address? (I hope not!). What I mean is, the memory address thing is a nice trick to generate different names, but once that's done, I think the contract for transmogrification should not change based on whether we provided a name ourselves or let the system do it for us. I think it is just much simpler to explain that the name is invariant, vs "if you provide your name, this happens... if not, this other thing happens...". Thoughts?

Another thing, is there any sugar or helper to retrieve my new scalar type variant given I have the original? to be more specific, in your integrator example if I know my integrator's name, I could use that to retrieve my autodiff variant. That will be super helpful when setting new autodiff values of the context for instance using the provided system API (for instance for integrator we'd like to use `Integrator::set_integral_value()`.

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/test/diagram_test.cc, line 461 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv3Hep3LpGc7clqNl-Y:-Kv3Hep3LpGc7clqNl-Z:b-2knmxm) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/test/diagram_test.cc#L461)):*
> ```cpp
>       dynamic_cast<const Integrator<AutoDiffXd>&>(*new_subsystem);
> 
>   // After transmogrification, the integrator has a different name.
> ```

Is this the behavior we want? I would've thought names would help retrieve the `AutoDiffXd` variant of my original `double` system. So, I thought we'd want `new_name` and `original_name` to be the same strings (and so we'd want them to be an invariant under scalar conversion?).
If not, what is the plan to retrieve my `new_system` templated on the new scalar type from my original system?

In MBT I've been getting around names so far with the `MBT::get_variant()` methods. The "invariant" in my case is the element's index.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3JMaS2ud7gJFbCYM8:bb9skah)*

**Comment by jwnimmer-tri** [comment]
> I personally would've preferred the name to be an "invariant", even in the case when Diagram provided a wacky default name containing a memory address. Is that part of the contract? meaning, does the user know that that wacky name was generated using a memory address? would the user try to convert the string back to a memory address? (I hope not!).

Nope, the default name is not documented anywhere in the Diagram contract.

> What I mean is, the memory address thing is a nice trick to generate different names, but once that's done, I think the contract for transmogrification should not change based on whether we provided a name ourselves or let the system do it for us. I think it is just much simpler to explain that the name is invariant, vs "if you provide your name, this happens... if not, this other thing happens...". Thoughts?

I think if the user was silent on what the name was, I think we should feel enabled to assign it as we see fit, which includes updating it to contain the correct pointer address as part of transmogrification.

> Another thing, is there any sugar or helper to retrieve my new scalar type variant given I have the original? to be more specific, in your integrator example if I know my integrator's name, I could use that to retrieve my autodiff variant. That will be super helpful when setting new autodiff values of the context for instance using the provided system API (for instance for integrator we'd like to use Integrator::set_integral_value().

If the user sets a specific name (like "integrator") it would be preserved.  Alternatively, the GetSystemIndex for the system will be unchanged during transmogrification, though the API doesn't promise that.

> setting new autodiff values of the context 

I don't think we have any code in-tree that does this, do we?

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/test/diagram_test.cc, line 449 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv2l4rzGrCtXk2146eW:-Kv3QN8sU4OLgoJbL7bq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/test/diagram_test.cc#L449)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This is robust, but surely we've already tested elsewhere that `GetMemoryObjectName()` does *not* return an empty string  (e.g., `system_test.cc`)? Or does this test something else that I'm missing? (Same applies below.)
</blockquote></details>

Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 461 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv3Hep3LpGc7clqNl-Y:-Kv3RFR1TunntTeltQqY:bnivaz5) ([raw file](https://github.com/robotlocomotion/drake/blob/b2fd24c6606f1255b2aad4f90e847cfab32122e8/drake/systems/framework/test/diagram_test.cc#L461)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Is this the behavior we want? I would've thought names would help retrieve the `AutoDiffXd` variant of my original `double` system. So, I thought we'd want `new_name` and `original_name` to be the same strings (and so we'd want them to be an invariant under scalar conversion?).
If not, what is the plan to retrieve my `new_system` templated on the new scalar type from my original system?

In MBT I've been getting around names so far with the `MBT::get_variant()` methods. The "invariant" in my case is the element's index.
</blockquote></details>

Done.  I've updated the test case to show that if the user provides a name, it remains unchanged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3RM2r2iVzCNu-yN0p:bj07cbk)*

**Comment by amcastro-tri** [comment]
> I don't think we have any code in-tree that does this, do we?

For integrator we have `Integrator::set_integral_value()`. If I want to do it on my new autodiff version I'd need to retrieve the `new_integrator ` given I only have the original integrator. 

I was imagining a workflow like the one in the `double_pendulum_test.cc`, where [you can get your autodiff variant given you have the original double variant](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1072) and then use it, for instance, to [set stuff in the autodiff context](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1116).

I think what you are doing here is ok but wanted to double check with you because clearly this will not allow us to use a system's name as its invariant to retrieve its scalar-converted counterpart in the future. 

---

Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3VP3cKVphWWEfjOjD:bf159nj)*

**Comment by jwnimmer-tri** [comment]
In Systems framework you have.
```c++
System<double> food;
Context<double> food_context;
System<AutoDiffXd> fooadx = foo.ToAutoDiffXd();
Context<AutoDiffXd> fooadx_context = foo_ad.CreateDefaultContext();
fooadx_context->SetTimeStateAndParametersFrom(food_context);
fooadx->FixInputPortsFrom(food, food_context, fooadx_context.get());
```

In other words, the way that you populate an AutoDiff context is from the double context, via the SetTimeAndState... method.  It would be irregular for a user to do that by hand, especially for the Systems that are hidden within a Diagram!

> clearly this will not allow us to use a system's name as its invariant to retrieve its scalar-converted counterpart in the future.

Clearly if you set a name yourself, you can still do this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3XzT16LKXZ7FK-Mfa:b-oeaxwj)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 789 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv3ZN0cIFQIP9MX8nZ1:-Kv3ZN0dzlfkexsvLKeG:b-2s2opq) ([raw file](https://github.com/robotlocomotion/drake/blob/49d1c1bada9eba3c24039914828e7de498bdecdd/drake/systems/framework/system.h#L789)):*
> ```objc
>   /// Returns the name last supplied to set_name(), or empty if set_name() was
>   /// never called.  Systems created through transmogrification have by default
>   /// an identical name to the system they were created from.
> ```

Hmm, this is lies now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 789 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv3ZN0cIFQIP9MX8nZ1:-Kv3_7gXKcJysuvraVvV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49d1c1bada9eba3c24039914828e7de498bdecdd/drake/systems/framework/system.h#L789)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, this is lies now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113)*

**Comment by amcastro-tri** [comment]
I like it, but that sets all your derivatives to zero. I believe there is no other way to set your derivatives to something meaningful than doing it by hand, [see here in the same double pendulum example](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1107). Setting derivatives is what sets the order of the independent variables in your problem. For instance, I could want to differenciate just with respect to `q1`. Or even more, with respect to a vector that has entries swapped `qtilde = [q2, q1]`. 

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3b59qEiyX1k-ffmX7:boblr0g)*

**Comment by jwnimmer-tri** [comment]
Yes, you must choose your partials by hand.  Usually you'll just do _all_ state variables, for example (as, e.g., Linearize does).  But if you need to do "Within this Diagram, I want only the State of the FooSystem, not the State of the whole Diagram" then you have to identify your FooSystem in the transmogrified result.  Use the GetSubsystemIndex do to that.  You can't index on the subsystem by name, anyway.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3c2MFTTDUgfbNiBOu:bxwqx2z)*

**Comment by amcastro-tri** [comment]
>  Usually you'll just do all state variables

I don't think so. I can see how for some sys id we'd like to take partials with respect to, say, a mass (a parameter of the system, not a state).

In any case, sounds good. I just wanted to check with you on that. Clearly the plan is not using a sys's name as an invariant across scalar converted systems. I'm good with that.  :lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3fM4vOgsitpncsOsm:b-gpya4h)*

**Comment by sherm1** [comment]
Sorry to be late to this discussion. Regarding the name, I think the discussion above makes it clear that it is a mistake to generate default names from memory addresses. Cloning a System shouldn't cause the system names to change! That's just weird. Why not generate default names from preserved quantities like system index?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3hmeGSQJMXosleRWk:b-76zrwt)*

**Comment by jwnimmer-tri** [comment]
By putting the address in the default name, we make it nearly impossible for a user to later add another System to the DiagramBuilder and happen upon a conflicting name.  For example, if we used a default like `"subsystem " + to_string(i)`, who's to say that the user wouldn't want to name something else `"subsystem 1"` also, e.g., if their existing documentation of a block diagram has subsystem names like so.  We could defer name assignment until `Diagram::Compile` time, but then if you do `diagram.AddSystem<MySystem>(...)->get_name()` it might be misleading (empty now, real name later).

I'm going to merge this for now, since it seems like a monotonic improvement.  If someone wants to figure out a way to assign names that can persist, I'm happy to review.

**Comment by SeanCurtis-TRI** [comment]
Blast!  You merged just before I published my new comment.

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/system.h, line 789 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-Kv3ZN0cIFQIP9MX8nZ1:-Kv3jpUFvgSxa1qZ9Rya:bcyg1yr) ([raw file](https://github.com/robotlocomotion/drake/blob/49d1c1bada9eba3c24039914828e7de498bdecdd/drake/systems/framework/system.h#L789)):*
I don't think this does enough. 
1. Sentence 1 is incomplete; if the system is instantiated through a `DiagramBuilder`, it will never by the empty string (even though the user never called `set_name()`). So, it's misleading, at best.
2. Simply appending leaves a contradiction. The contradiction is one of timing -- transmogrifying a system created by a `DiagramBuilder` will *never* have  an empty name, but the new system will have a different name. So, the context in which the name is defined matters. It is not reflected in this language.
3. So, a more accurate description would be:

> Returns the name of the system. The system name defaults to the empty string. Otherwise, it is set explicitly by the user with a call to `set_name()`, or the `DiagramBuilder` will provide a default name if a system without a specified name is added to the builder. The transmogrified version of this system will have the same name, unless the source system's name is identical to the default name the DiagramBuilder would have assigned it; in which case it is updated.

This whole thing becomes simpler if the name were set to the "memory" name by default as part of the system constructor, handled in conversion by the system, and overridden by a call to `set_name()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3mBoks6GSGxr2h7XJ:b4r65vs)*

**Comment by jwnimmer-tri** [comment]
Hmm, I think there was some reason that we didn't want the default `name` to be `GetMemoryObjectName()`, that I don't the reason at the moment.  I will explore.

**Comment by SeanCurtis-TRI** [comment]
While one solution -- certainly the documentation in `system.h` is a "lie".

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3o7CWWlvBOUU4UnMH:bxs4l3g)*

**Comment by SeanCurtis-TRI** [comment]
One solution is to make all default names pre-pended with an underscore, and forbid users to name systems with a leading underscore. TA DA!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7113#-:-Kv3oIKsWbNTBvyJ57AK:b-8ax4hh)*

**Pull request merged**
