### PR TITLE
pydrake systems: Expose initial round of different scalar types

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires:
- [x] RobotLocomotion/pybind11#17 - disables any runtime usage of references for `dtype=object`

Can merge without, but would be nice to have:
- (probs won't get 'em in time) #8608 + #8452 to remove some of the silly shims, but this can maintain functionality, while also (annoyingly) warning users when things will break if the wrong operations are done upon a type.

This does not yet enable custom Python classes with scalar-type conversion. We can hack that in if need be, or wait for the above PRs to complete that.

\cc @RussTedrake @gizatt 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Jenkins has a complaint:
```
/framework_py_semantics.pic.o: C++ compilation of rule '//bindings/pydrake/systems:framework.so' failed (Exit 1)
bindings/pydrake/systems/framework_py_semantics.cc: In lambda function:
bindings/pydrake/systems/framework_py_semantics.cc:55:30: error: declaration of 'using T = decltype (dummy)' shadows a global declaration [-Werror=shadow]
     using T = decltype(dummy);
                              ^
bindings/pydrake/systems/framework_py_semantics.cc:28:17: note: shadowed declaration is here
 using T = double;
```

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LAsPJaC5vE4_JNoul8V:b1h9iwb)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[bindings/pydrake/autodiffutils_py.cc, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsQTpG7S18AfEMnTeG:-LAsQTpG7S18AfEMnTeH:b-9edvth) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/autodiffutils_py.cc#L28)):*
> ```cpp
>   py::class_<AutoDiffXd> autodiff(m, "AutoDiffXd");
>   autodiff
>     .def(py::init<double>())
> ```

The three new lines in this file lack direct unit test coverage?

---

*[bindings/pydrake/systems/framework_py_values.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsS_IE5UA3RK_BxbVA:-LAsS_IE5UA3RK_BxbVB:burysv2) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_values.cc#L27)):*
> ```cpp
>   using namespace drake::systems;
> 
>   auto bind_common_scalar_types = [m](auto dummy) {
> ```

Its difficult for me to immediately understand what passing a `py::module` by-value means.

(Ditto for all the other `type_visit` lambda targets in other files.)

---

*[bindings/pydrake/systems/primitives_py.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAshL_n6JE_Nocpa38M:-LAshL_n6JE_Nocpa38N:b1d8nde) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/primitives_py.cc#L113)):*
> ```cpp
> 
>     DefineTemplateClassWithDefault<Multiplexer<T>, LeafSystem<T>>(
>         m, "Multiplexer", GetPyParam<T>())
> ```

FYI Alpha-sort "Multiplexer" between "LinearSystem" and "Passthrough", for consistency?

---

*[bindings/pydrake/systems/primitives_py.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsgcxpEZiVKI0cHwHt:-LAsgcxpEZiVKI0cHwHu:bmhe6g4) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/primitives_py.cc#L120)):*
> ```cpp
>   type_visit(bind_common_scalar_types, pysystems::CommonScalarPack{});
> 
>   using T = double;
> ```

Given that `T` is used above with special meaning (its _actually_ a generic scalar marker), it seems misleading in the below code for `T` to not mean "various scalars".

I suggest just saying `double` literally below where needed.

---

*[bindings/pydrake/systems/systems_pybind.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsR3Kj5bVNAs7pbRsU:-LAsR3Kj5bVNAs7pbRsV:buc147p) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/systems_pybind.h#L103)):*
> ```objc
>     double,
>     AutoDiffXd
>     >;
> ```

Either the above two lists are supposed to be identical to default_scalars.h in which case its a brittleness defect not to have cross-linked comments in the two files instructing developers to keep them in sync, or else these lists do not need to be kept in sync in which case its a confusion defect how and why these two lists _should_ evolve differently.

---

*[bindings/pydrake/systems/trajectory_optimization_py.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsiAM03C2G4lNNEYJI:-LAsiAM03C2G4lNNEYJJ:b1byh7x) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/trajectory_optimization_py.cc#L31)):*
> ```cpp
>       .def("fixed_timestep", &MultipleShooting::fixed_timestep)
>       // TODO(eric.cousineau): Restore original bindings (using VectorXBlock)
>       // once dtype=custom is resolved.
> ```

BTW If I'm understanding correctly, I _think_ the important fact here is that the functions return references instead of copies.  If that's what you mean, it probably should be made more obvious.

---

*[bindings/pydrake/systems/test/general_test.py, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsejKA4mK8yoX7y5ig:-LAsejKA4mK8yoX7y5ih:b9258fn) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L47)):*
> ```Python
>         # Quick check of instantions for given types.
>         self._check_instantiations(Simulator_, False)
>         self._check_instantiations(BasicVector_)
> ```

What about the VectorBase / Supervector / Subvector?

---

*[bindings/pydrake/systems/test/general_test.py, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsez5fEyco1Ch8rJv4:-LAsez5hEdA7u5h6vMRX:b3nuh0d) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L55)):*
> ```Python
>             system = Adder_[T](1, 1)
>             # N.B. Current scalar conversion does not auto-register idempotent
>             # conversions.
> ```

I don't understand what this is saying.

---

*[bindings/pydrake/systems/test/general_test.py, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsfAUW5AmgcEIt4dJj:-LAsfAUW5AmgcEIt4dJk:b-26r2eq) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L61)):*
> ```Python
>             if T != Expression:
>                 system_sym = system.ToSymbolic()
>                 self.assertIsInstance(system_sym, System_[Expression])
> ```

As a basic sanity check, it seems worth checking some fact about the resulting system, e.g. that the num_inputs == 1 and input_port[0].size == 1, or similar.

---

*[bindings/pydrake/systems/test/general_test.py, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsjDcxCpzthENXm2ry:-LAsjDcxCpzthENXm2rz:bgs24p0) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L63)):*
> ```Python
>                 self.assertIsInstance(system_sym, System_[Expression])
> 
>     def test_simular_ctor(self):
> ```

BTW typo

---

*[bindings/pydrake/systems/test/general_test.py, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsfZ7vDE_6z3N2T2v-:-LAsfZ7xD8Pm50JXRqL8:b-z30d12) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L82)):*
> ```Python
>                     # possible, to use for `np.allclose`.
>                     self.assertEqual(value.shape, (1,))
>                     self.assertEqual(value[0], AutoDiffXd(1.))
> ```

BTW ... or else fail-fast (when T is neither of the two that its supposed to be?).

---

*[bindings/pydrake/systems/test/primitives_test.py, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsh9s44whQ3rPY82uf:-LAsh9s44whQ3rPY82ug:b-d5lljk) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/primitives_test.py#L65)):*
> ```Python
>         self._check_instantiations(Saturation_)
>         self._check_instantiations(SignalLogger_)
>         self._check_instantiations(WrapToSystem_)
> ```

Unclear why missing:
- ConstantValueSource
- ZeroOrderHold

---

*[bindings/pydrake/util/cpp_template.py, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsihs28UCxUlroOCVJ:-LAsihs41NkzuMTiK6bq:b6258xx) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/util/cpp_template.py#L169)):*
> ```Python
>             # Define `__qualname__` in Python2 because that's what `pybind11`
>             # uses when showing function signatures when an overload cannot be
>             # found.
> ```

FYI Should there be a unit test to make any assertions about the quality of the exception messages that are coming out related to this?

---

*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsPe4Y-TsU9F7sTn0j:-LAsPe4Y-TsU9F7sTn0k:bs06yv6) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/tools/workspace/pybind11/repository.bzl#L9)):*
> ```Python
> 
> # PR DRAFT(eric.cousineau): Change this once RobotLocomotion/pybind11#17 lands.
> _COMMIT = "f8d6b820a30936d21f261e2162464f1cabe4ceda"
> ```

Blocking on reaching our master.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LAsjNKh3n70na1Y5dCn:by96gdd)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 22 files reviewed at latest revision, 19 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsQTpG7S18AfEMnTeG:-LAxjxCs2zDyPsDmj328:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/autodiffutils_py.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The three new lines in this file lack direct unit test coverage?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/framework_py_semantics.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsn7Al0Ki4NeN4zz0l:-LAx_b-wDqTqYwOhRRyE:bc63pxj) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_semantics.cc#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can't tease out why this moved, especially when BasicVectorPtrList didn't move.  The prior location down below seems to be to be closer to its first point of use, which is more clear to the reader.
</blockquote></details>

Done. Moved the binding for `AbstractValues` (and other non-`T` stuff) up, since it used this definition and did not depend on `T`.

---

*[bindings/pydrake/systems/framework_py_semantics.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsnQWAEetfU83sHG2J:-LAx_l_N2pSvrmQFifKM:bw3rb0d) ([raw file](https://github.com/robotlocomotion/drake/blob/628400a64d2c05a5588d6e3a0221c239b8919fc3/bindings/pydrake/systems/framework_py_semantics.cc#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Just to double-check... you are okay losing this TODO?  We'll figure it out once we need it, without any TODO reminder?
</blockquote></details>

OK Yup. I should have removed it earlier; primarily because it's not needed since we get auto-downcasting wiht `AbstractValue.GetValue()` in Python, and secondarily because binding templated methods, exposing parameters, is demonstrated in `cpp_template_test.py`.

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsrSujBjgDHuCZQg-z:-LAxk7nT2YWWm8urBCcb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_systems.cc#L176)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Since its not doxygen you don't need `@see`, so it doesn't have to be on this line, and then just a URL on a line by itself can never trigger a line-length complaint (`// SomeUrl` is auto-whitelisted).
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsrqUMACYWofp8FO_5:-LAxk99J67LbSi6j52-5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_systems.cc#L289)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think ToAutoDiffXdMaybe and ToSymbolicMaybe are not tested?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/framework_py_values.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsS_IE5UA3RK_BxbVA:-LAxc2GV7EQrPpOprKoH:bnx24au) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_values.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its difficult for me to immediately understand what passing a `py::module` by-value means.

(Ditto for all the other `type_visit` lambda targets in other files.)
</blockquote></details>

OK `py::module` inherits from `py::object`; both are effectively C++-friendly wrappers of `PyObject*`, inherent to the API of `pybind11`.

Would you like me to add some more doc to `pydrake_pybind.h` pointing to the `pybind11` docs?

---

*[bindings/pydrake/systems/primitives_py.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAshL_n6JE_Nocpa38M:-LAxkACm5j5tAR7h8kNO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/primitives_py.cc#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Alpha-sort "Multiplexer" between "LinearSystem" and "Passthrough", for consistency?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/primitives_py.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsgcxpEZiVKI0cHwHt:-LAxkAuk-z_NT1ARjs-W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/primitives_py.cc#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given that `T` is used above with special meaning (its _actually_ a generic scalar marker), it seems misleading in the below code for `T` to not mean "various scalars".

I suggest just saying `double` literally below where needed.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/systems_pybind.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsR3Kj5bVNAs7pbRsU:-LAxkBTH8S9ve8CAj9t6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/systems_pybind.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Either the above two lists are supposed to be identical to default_scalars.h in which case its a brittleness defect not to have cross-linked comments in the two files instructing developers to keep them in sync, or else these lists do not need to be kept in sync in which case its a confusion defect how and why these two lists _should_ evolve differently.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/trajectory_optimization_py.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsiAM03C2G4lNNEYJI:-LAxkCoN6HkAH3cj8OcW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/trajectory_optimization_py.cc#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If I'm understanding correctly, I _think_ the important fact here is that the functions return references instead of copies.  If that's what you mean, it probably should be made more obvious.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsejKA4mK8yoX7y5ig:-LAxkEnm6AMbyKlrjSmU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What about the VectorBase / Supervector / Subvector?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsez5fEyco1Ch8rJv4:-LAxkFNT9Keo4ZVfpqle:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand what this is saying.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsjDcxCpzthENXm2ry:-LAxkKVB1OY6dd-cBMNM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW typo
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsfZ7vDE_6z3N2T2v-:-LAxkL8yERd_qfB9Z6Pk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW ... or else fail-fast (when T is neither of the two that its supposed to be?).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Comment by EricCousineau-TRI** [comment]
Addressed comments, PTAL.

---

Review status: 10 of 24 files reviewed at latest revision, 17 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py_semantics.cc, line 273 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsnyqC-A9tJwcsv63I:-LAxx3d1C7Yr-QILJkHL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_semantics.cc#L273)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like we should have `_check_instantiations` tests for all of the above?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsfAUW5AmgcEIt4dJj:-LAxx6_9EmyN-SDrf4p2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/general_test.py#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As a basic sanity check, it seems worth checking some fact about the resulting system, e.g. that the num_inputs == 1 and input_port[0].size == 1, or similar.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsh9s44whQ3rPY82uf:-LAxx80-4ktJn7qf-WUb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/test/primitives_test.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why missing:
- ConstantValueSource
- ZeroOrderHold
</blockquote></details>

Done.

---

*[bindings/pydrake/util/cpp_template.py, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsihs28UCxUlroOCVJ:-LAxx94e0dcyoY9molKB:bkf5qhw) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/util/cpp_template.py#L169)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Should there be a unit test to make any assertions about the quality of the exception messages that are coming out related to this?
</blockquote></details>

Done. See `cpp_template_pybind_test`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LAxxOFB5u8fPlI2Dagq:b-cubg63)*

**Comment by jwnimmer-tri** [comment]
*[bindings/pydrake/systems/framework_py_values.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsS_IE5UA3RK_BxbVA:-LAyseuUB-UACbHEKXXT:b1utjfb) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_values.cc#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK `py::module` inherits from `py::object`; both are effectively C++-friendly wrappers of `PyObject*`, inherent to the API of `pybind11`.

Would you like me to add some more doc to `pydrake_pybind.h` pointing to the `pybind11` docs?
</blockquote></details>

So is the bottom line here basically `py::object` is like a pointer, so capturing by-reference is unnecessary / weird, because copies are both cheap and interchangeable with the original?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Comment by jwnimmer-tri** [comment]
AFAIK we have http://drake.mit.edu/doxygen_cxx/python_bindings.html as a guide for _developers_ of the python bindings and http://drake.mit.edu/python_bindings.html as documentation for users.

**Comment by EricCousineau-TRI** [comment]
Added docs on the pattern for template stuff. PTAL.

---

Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py_values.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsS_IE5UA3RK_BxbVA:-LB--9SHAFGPC5hSGpjM:b54gfki) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/bindings/pydrake/systems/framework_py_values.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So is the bottom line here basically `py::object` is like a pointer, so capturing by-reference is unnecessary / weird, because copies are both cheap and interchangeable with the original?
</blockquote></details>

OK Yup. Added some docs to `pydrake_pybind.h`, will see if I can upstream some of them (they have some docs, but they're not super cohesive on conversions).

---

*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LAsPe4Y-TsU9F7sTn0j:-LB--JWHCkrovOn9g3D1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f13f6f6d18757d00ac7b129c273731b2aa3b733/tools/workspace/pybind11/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Blocking on reaching our master.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LB--TrmDxrx-Nf0wsDs:bh5w6g8)*

**Comment by EricCousineau-TRI** [comment]
BTW While not completely pythonic, it has parallels to type hints introduce in Python3:
https://docs.python.org/3/library/typing.html
(`pybind11` also uses the bracket syntax for error reporting on types, e.g. `List[str]`)

---

Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LB--wA9E2_TvbazX7RW:b2bo8oi)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Comment by SeanCurtis-TRI** [comment]
Great documentation.  Just a couple of small editorial quibbles.

---

Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[doc/python_bindings.rst, line 185 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IVVD3zkRw_uYSEbr:-LB1IVVEAmRb6KItbVsR:b-cv8k89) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L185)):*
> ```reStructuredText
> binding convention is used.
> 
> For example, ``Adder<T>`` is a Systems primitive which has user-defined number
> ```

BTW "...has __*a*__ user-defined number..."

---

*[doc/python_bindings.rst, line 186 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IeE79tPdojm_Ti5r:-LB1IeE79tPdojm_Ti5s:bp04bbc) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L186)):*
> ```reStructuredText
> 
> For example, ``Adder<T>`` is a Systems primitive which has user-defined number
> of inputs, and outputs a single port which is the summation of all of the
> ```

BTW s/summation/sum  (sum is the value, summation is the process)

---

*[doc/python_bindings.rst, line 193 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IrmY0nyfabGGG_39:-LB1IrmY0nyfabGGG_3A:b-v5xysh) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L193)):*
BTW I'm not 100% sure on the beginning of this sentence.  "To access..., to then access..." It seems that the second clause supplants the first. So, simply:

> To access other instantiations, you should add...

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665#-:-LB1JDRcER30Xdzi88c_:b-9d987d)*

**Comment by EricCousineau-TRI** [comment]
Review status: 25 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/python_bindings.rst, line 185 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IVVD3zkRw_uYSEbr:-LB2-EUU06pFv1KsEswT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L185)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "...has __*a*__ user-defined number..."
</blockquote></details>

Done.

---

*[doc/python_bindings.rst, line 186 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IeE79tPdojm_Ti5r:-LB2-E4MEvwmntfndVuD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L186)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW s/summation/sum  (sum is the value, summation is the process)
</blockquote></details>

Done.

---

*[doc/python_bindings.rst, line 193 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8665#-LB1IrmY0nyfabGGG_39:-LB2-Ewx2FlFd_sBuDoT:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d22fd28c3eaa47170b4493f83f3bc76f86f95702/doc/python_bindings.rst#L193)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm not 100% sure on the beginning of this sentence.  "To access..., to then access..." It seems that the second clause supplants the first. So, simply:

> To access other instantiations, you should add...
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8665)*

**Pull request merged**
