### PR TITLE
[doc] Add release notes v1.34.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/end_of_support.md` line 50 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21956#-O8czhW21ZvE9gmXPg29:-O8czhW21ZvE9gmXPg2A:b63c6l2) ([raw file](https://github.com/RobotLocomotion/drake/blob/83de317de07306a89f170f35852273adcf7b044f/doc/_release-notes/end_of_support.md#L50)):*
> ```Markdown
> * Wheel-only packages:
>   * The last version with support for macOS running on x86_64 hardware was
>     [v1.34.0](https://github.com/RobotLocomotion/drake/releases/tag/v1.34.0).
> ```

Working

Sync this fact with `installation.md` footnote 5 about macOS x86_64.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one patch.

> Reviewed 1 of 2 files at r1, 4 of 5 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956#-:-O9GPPLp0Tt7Npj2t31k:b308owb)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.34.0.md` line 14 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21956#-O9GP9fO7rRmPYmi8czB:-O9GP9fO7rRmPYmi8czC:b6zbnkh) ([raw file](https://github.com/RobotLocomotion/drake/blob/7f94afa42dc55686fc572f1145d476a5c6ef0d6e/doc/_release-notes/v1.34.0.md#L14)):*
> ```Markdown
>   * This is especially useful when meshes need to be created dynamically;
>     now a temp directory is no longer needed to story the mesh data.
>   * A single shape can heterogeneously mix in-memory and disk files (e.g.,
> ```

nit: This statement isn't quite right. I have a patch for it, but I don't have push permissions on this branch.

Here's the patch or you can ping me when I can push.


```diff
@@ -9,12 +9,12 @@ released: YYYY-MM-DD
 * SceneGraph now supports in-memory meshfiles.
   * The Mesh and Convex shapes can now specify meshfile data in-memory,
     instead of only ever loading meshes from disk.
   * This is especially useful when meshes need to be created dynamically;
     now a temp directory is no longer needed to story the mesh data.
-  * A single shape can heterogeneously mix in-memory and disk files (e.g.,
-    on-disk for the geometry, in-memory for the texture).
+  * An in-memory mesh shape can make use of heterogeneous supporting files
+    (e.g., an in-memory obj uses an in-memory .mtl but uses an on-disk texture).
   * All geometry consumers in Drake (e.g., visualizers, render engines,
     collision queries, plant contact dynamics) support the in-memory data.
     * Downstream code that directly access a shape's mesh data (by calling the
       `filename()` function) should be adjusted to handle both file paths and
       in-memory buffers.

```

**Comment by jwnimmer-tri** [comment]
Oops; pushes are enabled now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.34.0.md` line 14 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21956#-O9GP9fO7rRmPYmi8czB:-O9GQ8TI1hefCo9wbXWU:b7t3kxp) ([raw file](https://github.com/RobotLocomotion/drake/blob/7f94afa42dc55686fc572f1145d476a5c6ef0d6e/doc/_release-notes/v1.34.0.md#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This statement isn't quite right. I have a patch for it, but I don't have push permissions on this branch.

Here's the patch or you can ping me when I can push.


```diff
@@ -9,12 +9,12 @@ released: YYYY-MM-DD
 * SceneGraph now supports in-memory meshfiles.
   * The Mesh and Convex shapes can now specify meshfile data in-memory,
     instead of only ever loading meshes from disk.
   * This is especially useful when meshes need to be created dynamically;
     now a temp directory is no longer needed to story the mesh data.
-  * A single shape can heterogeneously mix in-memory and disk files (e.g.,
-    on-disk for the geometry, in-memory for the texture).
+  * An in-memory mesh shape can make use of heterogeneous supporting files
+    (e.g., an in-memory obj uses an in-memory .mtl but uses an on-disk texture).
   * All geometry consumers in Drake (e.g., visualizers, render engines,
     collision queries, plant contact dynamics) support the in-memory data.
     * Downstream code that directly access a shape's mesh data (by calling the
       `filename()` function) should be adjusted to handle both file paths and
       in-memory buffers.

```
</blockquote></details>

Merged.

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 5 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956#-:-O9GlJxO6Nbj9E0weTPB:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21956)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
