### PR TITLE
Move //tools/third_party to //third_party

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This better matches Bazel conventions, and paves the way for tools to stop being build-system-only contents.

Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7154)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-continuous-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS4z5MEEWv8w-6pXta:-KvS4z5MEEWv8w-6pXtb:b-on0p0j) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/BUILD.bazel#L1)):*
> ```
> # -*- python -*-
> ```

BTW Why `BUILD.bazel` and not `BUILD`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-:-KvS5DNmIz4oWJ2rt61_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-tri for platform review per rotation, please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS5yx8lycPiD4Bl3Yi:-KvS5yx9abb_4LdQlgcp:bpe1j8i) (no related file):*
Do not merge, pending `BUILD.bazel` preference convention discussion.

---

*[third_party/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS4z5MEEWv8w-6pXta:-KvS5RL4wiYWafBwy8wY:bdnw1ug) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/BUILD.bazel#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Why `BUILD.bazel` and not `BUILD`?
</blockquote></details>

OK Right, that was unclear.  My plan is to change Drake to use `BUILD.bazel` pervasively for clarity, so my intent is to author _new_ BUILD files in future PRs with this spelling.  In the meantime, it will be a bit inconsistent though.  I will hop on `#bazel` slack and see what people think of this proposal, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-:-KvS68Hi1XvVbUnt6SSp:bf47uzo)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS4z5MEEWv8w-6pXta:-KvS6sLjnTEXN1aofiOQ:bqczzxw) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/BUILD.bazel#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Right, that was unclear.  My plan is to change Drake to use `BUILD.bazel` pervasively for clarity, so my intent is to author _new_ BUILD files in future PRs with this spelling.  In the meantime, it will be a bit inconsistent though.  I will hop on `#bazel` slack and see what people think of this proposal, though.
</blockquote></details>

Ok, fine by me. Do you want to follow up with a documentation update to codify that somewhere if everyone agrees with the convention?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Comment by jwnimmer-tri** [comment]
*[third_party/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS4z5MEEWv8w-6pXta:-KvSG174-3LoWlEQH5cO:buhyven) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/BUILD.bazel#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Ok, fine by me. Do you want to follow up with a documentation update to codify that somewhere if everyone agrees with the convention?
</blockquote></details>

Yeah, I will PR that style update if / when people agree -- hopefully before filing any more PRs that assume it to be the style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending preference discussion.

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/com_github_google_kythe/tools/build_rules/config/BUILD, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvTTZFOmlndtSlDtuz2:-KvTTZFOmlndtSlDtuz3:b-2gsexk) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/com_github_google_kythe/tools/build_rules/config/BUILD#L6)):*
> ```Python
> 
> exports_files([
>     "BUILD.tpl",
> ```

BTW Following the preference convention, would `BUILD.tpl` be renamed to `BUILD.bazel.tpl`?

(Well, perhaps that wouldn't apply to third party supplied files)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-:-KvTTww2hNToVlPmppSp:bonh7hr)*

**Comment by jwnimmer-tri** [comment]
*[third_party/com_github_google_kythe/tools/build_rules/config/BUILD, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvTTZFOmlndtSlDtuz2:-KvTUXSnv85kIaLHOGiY:b-17d4e8) ([raw file](https://github.com/robotlocomotion/drake/blob/cfb378db575c94d485c429610d7b5de3a22d3c09/third_party/com_github_google_kythe/tools/build_rules/config/BUILD#L6)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Following the preference convention, would `BUILD.tpl` be renamed to `BUILD.bazel.tpl`?

(Well, perhaps that wouldn't apply to third party supplied files)
</blockquote></details>

OK In our code, yes I would probably generate an outfile named `BUILD.bazel` and thus the src would be `BUILD.bazel.in`.  But I would not change third_party code just for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvTVindg5XN_r1PHgV_:-KvTVinfCLCx2U7904Tq:b-xnk7pu) (no related file):*
I think that `tools/buildifier.sh -f` might miss `third_party/BUILD.bazel`.  I will test and fix in case so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Comment by jwnimmer-tri** [comment]
Review status: 22 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvS5yx8lycPiD4Bl3Yi:-KvX1Tx6zUAu1Cj1MHKd:b8s7zqw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do not merge, pending `BUILD.bazel` preference convention discussion.
</blockquote></details>

No objections.  Will file a styleguide later.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7154#-KvTVindg5XN_r1PHgV_:-KvX1T1fHRZIYMELubAf:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think that `tools/buildifier.sh -f` might miss `third_party/BUILD.bazel`.  I will test and fix in case so.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7154)*

**Pull request merged**
