### PR TITLE
Use JCenter for Maven JAR downloads

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7465)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

Sad that Bazel doesn't offer list-of-servers instead of just one-server.

If you think we should put it back to maven central, maybe file an issue once this merges.

Possibly also worth capturing the single point of failure in a Drake feature request issue, to add self-hosted images like we do with github and bitbucket.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7465#-:-KyqekBSdnZkKAiF9ITL:b-acx2h8)*

**Comment by jamiesnape** [comment]
At first glance, I think we have to use `maven_server` and write our own `settings.xml`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7465#-:-KyqgEjUvlMgq6560a3r:bgijvlq)*

**Comment by jwnimmer-tri** [comment]
Ah, yes, thanks -- I see that now.  I am still OK with this as a hotfix in the meantime if we want.

**Pull request merged**
