### PR TITLE
Made RigidBodyFrame member variables private and added accessors.

### PR DESCRIPTION
**Pull request by liangfok**
Public access to mutable class member variables is a big no-no since it violates state encapsulation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3003)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KNxoYLl1H54VswCiFOa:-1516772162)*

**Comment by sherm1** [comment]
Platform: nice, just a few comments.

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBodyFrame.h, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyKuLv8mRbKdHJrpOl:-KNyKuLv8mRbKdHJrpOm:826220210) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L61)):*
> ```objc
>    * to which this frame is attached.
>    */
>   const Eigen::Isometry3d& get_transform_to_body() const;
> ```

BTW, it would be great to document this transform unambiguously if you can. If we denote the body's frame `B` and this RBFrame is called `F`, then the resulting transform T is either `T_BF` or its inverse `T_FB`. Those can be defined unambiguously by their function like this:
```
p_B = T_BF * p_F;
p_F = T_FB * p_B;
```
where p_B is the location of a point measured from B's origin and expressed in the B frame, and p_F is the location of that same point, but measured from F's origin and expressed in the F frame. With this notation the frame symbols must match in pairs, BB FF in the first case and FF BB in the second (see [these slides](https://drive.google.com/open?id=0B-dn8WKPpzq4NnBTU184V2JlWHM)). Do you know which of these two possibilities is the actual returned value?

---

*[drake/systems/plants/RigidBodyFrame.h, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyNhx5n9Ms6J6nnU4W:-KNyNhx5n9Ms6J6nnU4X:-1786347712) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L74)):*
> ```objc
>   /**
>    * Returns the index of this `RigidBodyFrame` within the vector of
>    * RigidBodyFrame` defined in the `RigidBodyTree`.
> ```

spurious back quote

---

*[drake/systems/plants/RigidBodyFrame.h, line 86 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyNshUEF8P0yrMJP_t:-KNyNshUEF8P0yrMJP_u:-1104956040) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L86)):*
> ```objc
>    * Sets the rigid body to which this frame is attached.
>    */
>   void set_rigid_body(RigidBody* rigid_body);
> ```

BTW, mention lifetime requirement.

---

*[drake/systems/plants/RigidBodyFrame.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyO1RnTkDdlLExN2X8:-KNyO1RnTkDdlLExN2X9:-2113215690) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L102)):*
> ```objc
>    * Sets the transform to body of this `RigidBodyFrame`.
>    */
>   void set_transform_to_body(const Eigen::Isometry3d& transform_to_body);
> ```

BTW, ambiguous.

---

*[drake/systems/plants/RigidBodyFrame.h, line 111 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyO75VbMSYZ-39PH6F:-KNyO75VbMSYZ-39PH6G:-625685580) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L111)):*
> ```objc
>    RigidBody* body_{nullptr};
>    Eigen::Isometry3d transform_to_body_;
>    int frame_index_ = 0;  // this will be negative, but will also be gone soon!
> ```

I don't understand the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KNyOff-2fzY9Lo671O1:566953166)*

**Comment by liangfok** [comment]
@sherm1: I addressed your comments. PTAL. Thanks!

---

Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyFrame.h, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyKuLv8mRbKdHJrpOl:-KNynmyjnNiXWx10j7Do:87061831) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, it would be great to document this transform unambiguously if you can. If we denote the body's frame `B` and this RBFrame is called `F`, then the resulting transform T is either `T_BF` or its inverse `T_FB`. Those can be defined unambiguously by their function like this:
> ```
> p_B = T_BF * p_F;
> p_F = T_FB * p_B;
> ```
> where p_B is the location of a point measured from B's origin and expressed in the B frame, and p_F is the location of that same point, but measured from F's origin and expressed in the F frame. With this notation the frame symbols must match in pairs, BB FF in the first case and FF BB in the second (see [these slides](https://drive.google.com/open?id=0B-dn8WKPpzq4NnBTU184V2JlWHM)). Do you know which of these two possibilities is the actual returned value?
</details>
Done. I verified it is `T_BF` by doing the following.

I looked at [prius_with_lidar.sdf#L660](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/models/prius/prius_with_lidar.sdf#L660).  The line defines a sensor called "rear_right_laser" with a pose of `<pose>0.055 0.08 0 0 0 0</pose>`. This pose is defined in its rigid body's frame (the rigid body is called "[rear_right_lidar_link](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/models/prius/prius_with_lidar.sdf#L647)" in this case).

The `RigidBodyFrame` created for this sensor contains the following transform:

```
Sensor rear_right_laser:
  - frame_to_body_transform:
    1     0     0 0.055
    0     1     0  0.08
    0     0     1     0
    0     0     0     1
```

I then defined a coordinate of `(0, 0, 0)` and transformed it. Here is the code:


```
      Vector3<double> coord;
      coord << 0, 0, 0;
      auto transformed_coord = frame->get_transform_to_body() * coord;
      std::cout << "transformed coord: " << transformed_coord << std::endl;
```

The resulting transformed coordinate was:

```
transformed coord: 0.055
 0.08
    0
```

This fits the theory that the original coordinate was defined in the `RigidBodyFrame`'s coordinate frame (`F`)  and was transformed into the `RigidBody`'s coordinate frame (`B`).

---

*[drake/systems/plants/RigidBodyFrame.h, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyNhx5n9Ms6J6nnU4W:-KNyRbExYrFTdKDhCykM:-1915369923) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L74)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> spurious back quote
</details>
Done. I also polished the text some.

---

*[drake/systems/plants/RigidBodyFrame.h, line 86 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyNshUEF8P0yrMJP_t:-KNyuzjUncDoW1rMEZhv:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, mention lifetime requirement.
</details>
Done.

---

*[drake/systems/plants/RigidBodyFrame.h, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyO1RnTkDdlLExN2X8:-KNyvE-PIwViaA-UvwJy:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, ambiguous.
</details>
Done.

---

*[drake/systems/plants/RigidBodyFrame.h, line 111 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyO75VbMSYZ-39PH6F:-KNyS049ssCLrNC1YElp:1202857219) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L111)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't understand the comment.
</details>
I also don't understand this comment, but it was there prior to this PR:

https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBodyFrame.h#L45

Since this could be classified as technical debt, I'd prefer to leave it as such for this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KNz1eK37uK_EovT55mK:1909952911)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 9 of 14 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KNz1tkWDFrQKon0tqQr:-206704113)*

**Comment by liangfok** [comment]
The [Drake / ROS CI build](https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/35/) suffered the following error:

```
[drake_cars_examples:make] /usr/bin/ld: cannot find -ldrakeCore
```
This is because the `drakeCore` library no longer exists as of [this commit](https://github.com/RobotLocomotion/drake/commit/d6bcc7d4b229bc643d3fc15355843803cb720bfc#diff-0e984921dd171e3672f67568c1932869).

---

Review status: 9 of 15 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO0-wLzTybr04Eaw5An:94413978)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 9 of 15 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO01VkAeMHf3tS_eqTS:-206704113)*

**Comment by liangfok** [comment]
This PR passed both https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/36/ and https://drake-jenkins.csail.mit.edu/job/experimental/3228/. It is thus ready for another round of review.

---

Review status: 9 of 15 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO0JTDGFHYqN9M3E85Z:321645276)*

**Comment by sherm1** [comment]
Platform: :lgtm: (a couple of BTW comments).

---

Reviewed 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyFrame.h, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyKuLv8mRbKdHJrpOl:-KO1QReAAjwGGFw7CUFF:-967460132) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I verified it is `T_BF` by doing the following.
> 
> I looked at [prius_with_lidar.sdf#L660](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/models/prius/prius_with_lidar.sdf#L660).  The line defines a sensor called "rear_right_laser" with a pose of `<pose>0.055 0.08 0 0 0 0</pose>`. This pose is defined in its rigid body's frame (the rigid body is called "[rear_right_lidar_link](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/models/prius/prius_with_lidar.sdf#L647)" in this case).
> 
> The `RigidBodyFrame` created for this sensor contains the following transform:
> 
> ```
> Sensor rear_right_laser:
>   - frame_to_body_transform:
>     1     0     0 0.055
>     0     1     0  0.08
>     0     0     1     0
>     0     0     0     1
> ```
> 
> I then defined a coordinate of `(0, 0, 0)` and transformed it. Here is the code:
> 
> 
> ```
>       Vector3<double> coord;
>       coord << 0, 0, 0;
>       auto transformed_coord = frame->get_transform_to_body() * coord;
>       std::cout << "transformed coord: " << transformed_coord << std::endl;
> ```
> 
> The resulting transformed coordinate was:
> 
> ```
> transformed coord: 0.055
>  0.08
>     0
> ```
> 
> This fits the theory that the original coordinate was defined in the `RigidBodyFrame`'s coordinate frame (`F`)  and was transformed into the `RigidBody`'s coordinate frame (`B`).
</details>
Awesome, thanks! I agree with your analysis which now no one else will have to do! Side note: this works because Eigen interpreted your point (0,0,0) as the homogenous vector (0,0,0,1). See (long) discussion [here](https://eigen.tuxfamily.org/dox/classEigen_1_1Transform.html).

---

*[drake/systems/plants/RigidBodyFrame.h, line 119 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KO1SiTV4uALqA8N1ijc:-KO1SiTV4uALqA8N1ijd:-2006689846) ([raw file](https://github.com/robotlocomotion/drake/blob/4299c08ed7ca291c78c9ff838f73c9cd41e4bc09/drake/systems/plants/RigidBodyFrame.h#L119)):*
> ```objc
>    * be `T_BF` as described in method RigidBodyFrame::get_transform_to_body().
>    *
>    * @see RigidBodyFrame#get_transform_to_body
> ```

BTW, does the `#` there produce correct doxygen? I think you could use `RigidBodyFrame::get_transform_to_body()` as you did above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO1TZXBn3-fzeSoJU6E:1396148878)*

**Comment by liangfok** [comment]
Now waiting on @amcastro-tri for a feature review.

---

Review status: 14 of 15 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/RigidBodyFrame.h, line 61 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KNyKuLv8mRbKdHJrpOl:-KO1bUgB0q5gmlOOdNBh:826642240) ([raw file](https://github.com/robotlocomotion/drake/blob/e9766ddb5b2d411269202b2400ac9794089e45bc/drake/systems/plants/RigidBodyFrame.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Awesome, thanks! I agree with your analysis which now no one else will have to do! Side note: this works because Eigen interpreted your point (0,0,0) as the homogenous vector (0,0,0,1). See (long) discussion [here](https://eigen.tuxfamily.org/dox/classEigen_1_1Transform.html).
</details>
Thanks for the info. :thumbsup: 

---

*[drake/systems/plants/RigidBodyFrame.h, line 119 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-KO1SiTV4uALqA8N1ijc:-KO1cRmC5xaGRgWQ8y8j:1483591733) ([raw file](https://github.com/robotlocomotion/drake/blob/4299c08ed7ca291c78c9ff838f73c9cd41e4bc09/drake/systems/plants/RigidBodyFrame.h#L119)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, does the `#` there produce correct doxygen? I think you could use `RigidBodyFrame::get_transform_to_body()` as you did above.
</details>
The `#` produces correct doxygen as does `::`, see note 3 here:

https://www.stack.nl/~dimitri/doxygen/manual/autolink.html#linkfunc

Since `::` is more akin to C++ syntax, I modified it to use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO1l7som3w-qYYrZ6Zd:-1224462819)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 14 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3003#-:-KO5NJ6TaI5RDQ6Ptn0w:1417088721)*

**Pull request merged**
