### PR TITLE
Use third party vtkCapsuleSource for rendering capsules

### PR DESCRIPTION
**Pull request by tehbelinda**
Relates to #10153 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12305)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@jwnimmer-tri I thought it might be easier to ask you with the WIP PR - is this the right direction with adding the cc library to the .bazel file? or should I be doing something in repository.bzl? I'm new to bazel so any guidance is much appreciated thanks :)

In its current state I get the build error:
```
bazel-out/k8-opt/bin/tools/workspace/vtk/vtkCapsuleSource.cxx:20:10: fatal error: vtkCapsuleSource.h: No such file or directory
 #include "vtkCapsuleSource.h"
          ^~~~~~~~~~~~~~~~~~~~
```

**Comment by jwnimmer-tri** [comment]
I think in this case you should stay away from `//tools/workspace` entirely.  We'll treat this like a tiny little forked file, not a full-blown external dependency.  You should write a BUILD file directly adjacent to these two source files, and cite it in `deps` where it's needed.  I can look more on Monday.

**Comment by jamiesnape** [comment]
BTW The authors are happy for `vtkCapsuleSource` to be upstreamed into VTK proper (which I can handle, though it may take a week or two).

**Comment by jwnimmer-tri** [comment]
I think VTK upstream would be ideal.  I was almost going to suggest rewriting a (simpler) version of this, instead of having to deal with licensing docs for such a trivial item.  Maybe this PR could be replaced with a TODO to use VTK upstream once it's available.

**Comment by sherm1** [comment]
Upstreaming this would be great -- thanks, @jamiesnape! However that's likely to take a while so I would prefer we use it now with a TODO to remove it when VTK has a capsule.

**Comment by tehbelinda** [comment]
I updated it to use an adjacent BUILD file to see if that would work, but still having the same issue with the .h not being found. Let me know if you have ideas on what I'm missing!

**Comment by tehbelinda** [comment]
I believe the other benefit, apart from visualisation, is for computing the hydroelastic mesh so the overlapping half spheres don't get in the way

Also this is helping me learn more about bazel, thank you for the help!

**Comment by tehbelinda** [comment]
Now that I'm trying to reference it from geometry, I get:
```
ERROR: /home/belindateh/drake/geometry/render/BUILD.bazel:117:1: no such target '//third_party/com_github_finetjul_bender:vtkCapsuleSource.installed_headers': target 'vtkCapsuleSource.installed_headers' not declared in package 'third_party/com_github_finetjul_bender' defined by /home/belindateh/drake/third_party/com_github_finetjul_bender/BUILD.bazel and referenced by '//geometry/render:render_engine_vtk_base.installed_headers'
ERROR: Analysis of target '//geometry/render:render_engine_vtk_base.installed_headers' failed; build aborted: Analysis failed
```

Is `installed_headers` another drake specific setting? I didn't see it in the bazel docs, but I do see references to it in drake_cc.bzl

**Comment by tehbelinda** [comment]
+@sherm1 for feature review please

and after that I was thinking Jeremy could do platform review (if you wouldn't mind since you've already been looking at this? otherwise I'll reassign)

**Comment by jwnimmer-tri** [comment]
I don't understand, this only affects `RgbdSensor`'s output port images, not `drake-visualizer`?

**Comment by sherm1** [comment]
Er, duh -- right. What I'm really asking for is to see the mesh that got produced. Bel showed me that the test case can do some vtk-direct rendering now and will see if she can get it to do wireframe.

**Comment by tehbelinda** [comment]
Got a before vs after image with wireframes - the size is a little different but you get the idea with the spheres being gone

**Comment by jwnimmer-tri** [comment]
> > BTW The authors are happy for vtkCapsuleSource to be upstreamed into VTK proper (which I can handle, though it may take a week or two).
>
> Upstreaming this would be great -- thanks, jamiesnape! However that's likely to take a while so I would prefer we use it now with a TODO to remove it when VTK has a capsule.

@tehbelinda Please open a Drake issue with the request for Kitware to provide the capsule shape directly in VTK (with any details you think are relevant).  That way we can place work into their hopper.

**Comment by tehbelinda** [comment]
___
*[third_party/com_github_finetjul_bender/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12305#-Lt0Qrn84ylVwb_2Cj9E:-Lt1tIxi8zKWlRRKGYYR:bn4jnfu) ([raw file](https://github.com/robotlocomotion/drake/blob/87a2babcefc034338330325dd8c7dfffc75e300a/third_party/com_github_finetjul_bender/BUILD.bazel#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please try adding `copts = ["-fvisibility=hidden"],` to this target and then see if all tests still pass -- we should only ever use this code inside Drake, not allow others to load against it, so its symbols should be hidden.
</blockquote></details>

How does that work with the `visibility` already set to geometry subpackages though?

When I tried it, tests weren't happy:
```
bazel-out/k8-opt/bin/geometry/render/_objs/render_engine_vtk_base/render_engine_vtk_base.pic.o:render_engine_vtk_base.cc:function drake::geometry::render::CreateVtkCapsule(vtkTransformPolyDataFilter*, double, double): error: undefined reference to 'vtkCapsuleSource::New()'
```

**Comment by tehbelinda** [comment]
___
*[third_party/com_github_finetjul_bender/vtkCapsuleSource.h, line 39 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12305#-Lt0QNfGAnI6jh6GxHHH:-Lt2-nYL7DZiKFbiwNtk:b-h5c5un) ([raw file](https://github.com/robotlocomotion/drake/blob/87a2babcefc034338330325dd8c7dfffc75e300a/third_party/com_github_finetjul_bender/vtkCapsuleSource.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I would feel slightly more comfortable if we could put the bender code into a C++ namespace, instead of leaving it in the global namespace.  Maybe `namespace com_github_finetjul_bender {`?
</blockquote></details>

Done. Good idea

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12305#-Lt273J9978bL72kQuqY:-Lt2G21b0tMUOUU-23Pq:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is a problem with the commit curation.  The copy of the files in the first comit is not identical to the upstream copy.  It looks like they have been clang-formatted in the Drake commit, compared to upstream.
</blockquote></details>

Done.

---

**Pull request merged**
