### PR TITLE
call_python: Rewrite test in Python

### LINKED ISSUE #7703: Refactor `call_python_full_test.sh` into Python
Per @jwnimmer-tri and @jamiesnape's request (#7672), and given the current lack of readability / maintainability of the script, `call_python_full_test` should be refactored into Python.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #7703

Given that this test is failing more frequently in CI, will see if this resolves some of the sticking points.

\cc @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699)

### CODE REVIEW

**Comment by jamiesnape** [comment]
I would be surprised if it fixes the flakiness, but certainly an improvement.

:lgtm:

---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/proto/BUILD.bazel, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQsRhwCLWmhFAGhLxf:-LBQsRhwCLWmhFAGhLxg:b-vnxpzg) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/BUILD.bazel#L149)):*
> ```Python
>     ],
>     # Do not isolate, as we wish to access neighboring files.
>     isolate = False,
> ```

We typically use `0` and `1` for booleans in BUILD files. You may wish to shorten the comment to `We wish to access neighboring files.` since the `Do not isolate` is self-evident.

---

*[common/proto/BUILD.bazel, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtRhB-esRqY9KBMp5:-LBQtRhB-esRqY9KBMp6:b49kcoc) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/BUILD.bazel#L152)):*
> ```Python
>     # TODO(eric.cousineau): Find the source of (more) sporadic CI failures, but
>     # after refactoring the script into Python.
>     # flaky = 1,
> ```

I think we keep the flaky until proven otherwise. This is a fairly faithful reproduction of the shell test.

---

*[common/proto/test/call_python_test.py, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQrQYvDapmL-d3xtAx:-LBQrQYvDapmL-d3xtAy:b-du85cg) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L31)):*
> ```Python
> # `bazel test` can cover the same capabilities as `bazel run` (debugging,
> # command-line arguments via command-line, etc).
> assert "TEST_TMPDIR" in os.environ, "Must run under `bazel test`"
> ```

Not sure I understand the comment, nor its relevance to the code. Aside, you are looking for the `--test_arg` and `--test_output` flags (we do not need that in a comment, though).

---

*[common/proto/test/call_python_test.py, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtD_u90mCdO-RO4bF:-LBQtCId5zrA8zOc6ux2:bgv1o2v) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L34)):*
> ```Python
> 
> # By default, set backend so that the test does not open windows.
> os.environ["MPLBACKEND"] = "ps"
> ```

As far as I can tell the `By default` is redundant since I do not see any setting of the environment variable otherwise.

---

*[common/proto/test/call_python_test.py, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtu0QD42SKDK1PcpT:-LBQtu0QD42SKDK1PcpU:b-u6eatj) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L44)):*
> ```Python
> client_bin = os.path.join(cur_dir, "../call_python_client_cli")
> # Change this if you wish to skip plotting testing (useful if debugging).
> no_plotting = False
> ```

Can we have positive variable name? Also the comment does not add any useful information since the purpose of the variable is self-evident.

---

*[common/proto/test/call_python_test.py, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQuaYw9ojd_DS7eORs:-LBQuaYx20TPIE6UFd7S:buqms7o) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L99)):*
> ```Python
>                 self.assertIn(server.wait(), server_valid_statuses)
>                 # Wait until the client has indicated that the server process
>                 # has run twice.
> ```

Why twice?

---

*[common/proto/test/call_python_test.py, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQujzQ8zkXJW10U8wV:-LBQujzQ8zkXJW10U8wW:b8k653) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L101)):*
> ```Python
>                 # has run twice.
>                 wait_for_done_count(2)
>                 # Kill the client with SIGINT since it's waiting.
> ```

`Kill the client since it's waiting.` would be sufficient given the passing of the `SIGINT` is pretty obvious.

---

*[common/proto/test/call_python_test.py, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQvqik3dLE09Jm0yM1:-LBQvqik3dLE09Jm0yM2:b-mib0cd) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L104)):*
> ```Python
>                 client.send_signal(signal.SIGINT)
>             client_status = client.wait()
>             if not with_error:
> ```

I think `if with_error: ... else: ...` would be better, those feels like you should be able to contract this to one statement with an `int()` call.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699#-:-LBQv2b2ASkAyq2u3srI:bh6i9lo)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[common/proto/BUILD.bazel, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQsRhwCLWmhFAGhLxf:-LBR0JEvCYS5J96lNM0B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/BUILD.bazel#L149)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We typically use `0` and `1` for booleans in BUILD files. You may wish to shorten the comment to `We wish to access neighboring files.` since the `Do not isolate` is self-evident.
</blockquote></details>

Done.

---

*[common/proto/BUILD.bazel, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtRhB-esRqY9KBMp5:-LBR0JjbB-YzAnchKrqV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/BUILD.bazel#L152)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I think we keep the flaky until proven otherwise. This is a fairly faithful reproduction of the shell test.
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQrQYvDapmL-d3xtAx:-LBR0GeQ2D4QFak8L-gi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L31)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Not sure I understand the comment, nor its relevance to the code. Aside, you are looking for the `--test_arg` and `--test_output` flags (we do not need that in a comment, though).
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtD_u90mCdO-RO4bF:-LBR0GAMBrvRgiEpd6m4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L34)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

As far as I can tell the `By default` is redundant since I do not see any setting of the environment variable otherwise.
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQtu0QD42SKDK1PcpT:-LBR0FhO50WgJU28ZbFl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L44)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Can we have positive variable name? Also the comment does not add any useful information since the purpose of the variable is self-evident.
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQuaYw9ojd_DS7eORs:-LBR0FJ49V5NXLAy6PfG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L99)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Why twice?
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQujzQ8zkXJW10U8wV:-LBR0F5QDx9pmKfe5SYP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L101)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`Kill the client since it's waiting.` would be sufficient given the passing of the `SIGINT` is pretty obvious.
</blockquote></details>

Done.

---

*[common/proto/test/call_python_test.py, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBQvqik3dLE09Jm0yM1:-LBR0EwQB6pwkTjRIh80:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a763b09035206a1e4f427fed6a8f822eaebc16a1/common/proto/test/call_python_test.py#L104)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I think `if with_error: ... else: ...` would be better, those feels like you should be able to contract this to one statement with an `int()` call.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699#-:-LBSnp8-CajmovB5XInN:bz1t39v)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699)*

**Comment by jamiesnape** [comment]
Optional builds all passed.

**Comment by sammy-tri** [comment]
Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/proto/test/call_python_test.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBWYEpF86w-hDs9Tqmf:-LBWYEpF86w-hDs9Tqmg:bm2o3vq) ([raw file](https://github.com/robotlocomotion/drake/blob/6da062cc0f0acf590a69fdaf36a4e6230ad81c71/common/proto/test/call_python_test.py#L50)):*
> ```Python
>     values_read = set()
>     while done_count < num_expected:
>         assert done_count <= num_expected
> ```

I'm having trouble figuring out what this assert is guarding inside the while loop.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_test.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBWYEpF86w-hDs9Tqmf:-LBXbjCi3KLcvRsCiCmS:b-fhrlhj) ([raw file](https://github.com/robotlocomotion/drake/blob/6da062cc0f0acf590a69fdaf36a4e6230ad81c71/common/proto/test/call_python_test.py#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm having trouble figuring out what this assert is guarding inside the while loop.
</blockquote></details>

OK to prevent against a rogue write, or a stale written state. It's already kinda taken care of by the other machinery, so I can remove it.

Would you like me to remove it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_test.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8699#-LBWYEpF86w-hDs9Tqmf:-LBXqRDw7bAvH0LPPlCl:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/6da062cc0f0acf590a69fdaf36a4e6230ad81c71/common/proto/test/call_python_test.py#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK to prevent against a rogue write, or a stale written state. It's already kinda taken care of by the other machinery, so I can remove it.

Would you like me to remove it?
</blockquote></details>

Done. Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8699#-:-LBaBb509yJM106dHz0U:bnfp4nl)*

**Pull request merged**
