### PR TITLE
Implement elevation bounds in `dragway` maliput backend.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6224)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please (since it's the dragway backend).

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-:-KlZeQeZRFc-Rw_AHulC:by1fmo2)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/dragway/road_geometry.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-KlZxqiznw7K1V2u9TPH:-KlZxqj0mZDdo4Jd0bV_:b-tr9tbx) ([raw file](https://github.com/robotlocomotion/drake/blob/87077ea9097c46e15fe8dc4e00ff1bcfda6f2286/drake/automotive/maliput/dragway/road_geometry.h#L42)):*
> ```objc
>   ///
>   /// @param[in] maximum_height The maximum height above the road surface
>   /// modelled by the RoadGeometry
> ```

BTW, missing period at end of sentence.

---

*[drake/automotive/maliput/dragway/segment.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-KlZyAMeJe0srf6XqLjf:-KlZyAMgbC0WdWAVxquE:b-tr9tbx) ([raw file](https://github.com/robotlocomotion/drake/blob/87077ea9097c46e15fe8dc4e00ff1bcfda6f2286/drake/automotive/maliput/dragway/segment.h#L73)):*
> ```objc
>   ///
>   /// @param[in] maximum_height The maximum height above the road surface
>   /// modelled by the RoadGeometry
> ```

BTW, missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-:-KlZzYzSlEGJ6IDgR-GM:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/dragway/road_geometry.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-KlZxqiznw7K1V2u9TPH:-Kl_2HDJQX6Y9UqDcixZ:bmf1ij1) ([raw file](https://github.com/robotlocomotion/drake/blob/87077ea9097c46e15fe8dc4e00ff1bcfda6f2286/drake/automotive/maliput/dragway/road_geometry.h#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing period at end of sentence.
</blockquote></details>

I'll add the period for the sake of consistency --- but for the record, there are only three legitimate sentences in this docstring, and this is not one of them.  (This and everything else are just noun phrases.  :) )

---

*[drake/automotive/maliput/dragway/segment.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-KlZyAMeJe0srf6XqLjf:-Kl_3KYxtXG2T8QQtqZp:b-y4e0vg) ([raw file](https://github.com/robotlocomotion/drake/blob/87077ea9097c46e15fe8dc4e00ff1bcfda6f2286/drake/automotive/maliput/dragway/segment.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing period at end of sentence.
</blockquote></details>

I'll add the period for the sake of consistency --- but for the record, there is only one legitimate sentence in this docstring, and this is not one of them.  (This and everything else are just noun phrases.  :) )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-:-Kl_29id2V3XyX2BmPOr:bxwr5c8)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6224)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 16 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6224#-:-Kl_RorlPfaqyas0S21r:bnfp4nl)*

**Pull request merged**
