### PR TITLE
Return bindings from KinematicTrajectoryOptimization Add* methods.

### LINKED ISSUE #20894: KinematicTrajectoryOptimization: Return constraint binding to enable naming constraints
**Is your feature request related to a problem? Please describe.**

I'm solving a `KinematicTrajectoryOptimization` problem using `AugmentedLagrangianNonsmooth` and would like to know which constraints are currently violated. For this, it would be useful to be able to name the constraints.

Naming constraints is possible using the constraint binding returned by `MathematicalProgram`:
```python
binding = prog.AddConstraint(...)
constraint = binding.evaluator()
constraint.set_description(name)
```

However, the `KinematicTrajectoryOptimization` API (e.g. `AddPositionBounds`, `AddPathVelocityConstraint`, `AddPathPositionConstraint`, etc.) does not return the constraint bindings.

**Describe the solution you'd like**
Have the `KinematicTrajectoryOptimization` return the constraint bindings.

I quickly looked at the code, and it should be relatively simple to make this change.

**Describe alternatives you've considered**
Doing the following after creating a new constraint. However, this loses some detail if multiple constraints are added at once.
```python
def name_unnamed_constraints(prog: MathematicalProgram, name: str) -> None:
    """Assigns `name` to each unnamed constraint in `prog`."""
    constraint_bindings = prog.GetAllConstraints()
    constraints = [binding.evaluator() for binding in constraint_bindings]
    for constraint in constraints:
        if constraint.get_description() == "":
            constraint.set_description(name)
```

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20894.

+@nepfaff for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014)

### CODE REVIEW

**Review by nepfaff — COMMENTED** [review]
Thanks for taking this on this quickly! Providing default names is also fantastic for speeding up debugging. 
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-:-NrE54IICrQF42qLRPci:b-qrq9xd)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.cc` line 495 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrE3ky37SiJ2y0c-QdO:-NrE3ky37SiJ2y0c-QdP:blr5z2i) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e9368c91375d270f364a8f0e2a1a7237f95277/planning/trajectory_optimization/kinematic_trajectory_optimization.cc#L495)):*
> ```cpp
>     vars.tail(num_positions_) = control_points_.col(i - 1);
>     if (use_conic_constraint) {
>       auto t = prog_.AddL2NormCostUsingConicConstraint(A, b, vars);
> ```

I find the name `t` confusing (it required me to look up the function in the docs to understand what is happening here). What about using a [structured binding](https://en.cppreference.com/w/cpp/language/structured_binding)?

**Review by RussTedrake — COMMENTED** [review]
Thanks Nick.  Still need the lgtm from you.
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-:-NrFXn-M1Xb_4XvTDOgS:bf2y1um)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.cc` line 495 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrE3ky37SiJ2y0c-QdO:-NrFXdMl5hUuvXSRewxC:b-dbsf13) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e9368c91375d270f364a8f0e2a1a7237f95277/planning/trajectory_optimization/kinematic_trajectory_optimization.cc#L495)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

I find the name `t` confusing (it required me to look up the function in the docs to understand what is happening here). What about using a [structured binding](https://en.cppreference.com/w/cpp/language/structured_binding)?
</blockquote></details>

Done. I considered that first, but it's not as nice (there is no default constructor for Binding).  I've improved the name.

**Review by nepfaff — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-:-NrGB1pkCvF9o9IVv_4F:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one request for some additional doc

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-:-NrGvUj38wU3sfSeMQQD:b-1kz9ak)* status: 3 unresolved discussions

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrGsPd7DsP4T1Keo1-k:-NrGsPd7DsP4T1Keo1-l:b-1ax3g1) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e910c37434a185d85b9e36d4d423a8b2020f1e6/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L146)):*
> ```objc
>       const Eigen::Ref<const Eigen::VectorXd>& ub, double s);
> 
>   /** Adds upper and lower bounds on the duration of the trajectory. */
> ```

BTW this is the only comment here that doesn't mention the specific type of the added constraint.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 154 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrGsx554yBWqGxn_TnU:-NrGsx554yBWqGxn_TnV:b-qmbe75) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e910c37434a185d85b9e36d4d423a8b2020f1e6/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L154)):*
> ```objc
>   t∈[0,T]. This also implies the constraints are satisfied for r(s), for all
>   s∈[0,1]. */
>   std::vector<solvers::Binding<solvers::BoundingBoxConstraint>>
> ```

minor: for the multiple-constraint return types the function comment should specify the ordering. (Here and below, especially the `vector<vector>` returns!)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014)* status: 1 unresolved discussion

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 154 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrGsx554yBWqGxn_TnU:-NrKyybJ3MWCf_OqnKcW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e910c37434a185d85b9e36d4d423a8b2020f1e6/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L154)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: for the multiple-constraint return types the function comment should specify the ordering. (Here and below, especially the `vector<vector>` returns!)
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.cc` line 495 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21014#-NrE3ky37SiJ2y0c-QdO:-NrKz1WN2IZM3te6GyGC:b-lsj77c) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e9368c91375d270f364a8f0e2a1a7237f95277/planning/trajectory_optimization/kinematic_trajectory_optimization.cc#L495)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done. I considered that first, but it's not as nice (there is no default constructor for Binding).  I've improved the name.
</blockquote></details>

@nepfaff -- you need to acknowledge/accept this change for me to merge.

**Review by nepfaff — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21014)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),nepfaff

**Pull request merged**
