### PR TITLE
Update gcc and fortran version; minor corrections.

### PR DESCRIPTION
**Pull request by Lucy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3611)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@naveenoid  for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSmTGeaV5SjHhJBgldW:bnpzzxu)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-KSpglb7oKD4iJsonH4y:-KSpglb8BmaW7fTHuul4:bin5723) ([raw file](https://github.com/robotlocomotion/drake/blob/9dbd2b9409bf7907ece1c93a76db6ff2a0e9b32c/drake/doc/clion.rst#L44)):*
> ```reStructuredText
>    ``-DCMAKE_INSTALL_PREFIX=/absolute_path_to_your/drake-distro/build/install``.
> 8. Under ``CMake Options`` expand the tab ``Pass system 
>    environment``. Add the following environment variables.  (You can copy these
> ```

BTW : This still shows up as 'system and custom environment' in my IDE (2016.1.3)..I dont want to block on this anyhow. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSphPMeIdKxsZey3taJ:bnfp4nl)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611)*

**Comment by jamiesnape** [comment]
The previous versions were not correct? AFAIK GCC 4.9 is still the supported compiler.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSq5b4HNHF2DZim33A7:bs4yicr)*

**Comment by jwnimmer-tri** [comment]
@jamiesnape Yeah.  I was wondering the same thing.  Lucy is on Xenial, but the CLion instructions should still support Trusty.

**Comment by Lucy-tri** [comment]
Instructions point to drake-distro/setup/ubuntu/16.04/install_prereqs.sh specifically calls out g++-5, so I thought that was the right thing.  Is it?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-KSpglb7oKD4iJsonH4y:-KSqNP3ky5w8Mv2UYw-n:b-spohzm) ([raw file](https://github.com/robotlocomotion/drake/blob/9dbd2b9409bf7907ece1c93a76db6ff2a0e9b32c/drake/doc/clion.rst#L44)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : This still shows up as 'system and custom environment' in my IDE (2016.1.3)..I dont want to block on this anyhow. 
</details>
What I noticed happening is that the first time I saw the "tab" it didn't say anything about custom, then the text changed, adding "custom". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqP8EUWZTOYXhSFM7D:b-lzxw3v)*

**Comment by Lucy-tri** [comment]
+@jwnimmer-tri for feature review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqRimv24Vrx9Pdgy5M:b-1tks9q)*

**Comment by Lucy-tri** [comment]
@jwnimmer-tri  I meant platform review, sorry.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqSSsOvxszM4AfKU_f:b-3pk6ek)*

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel: This breaks Trusty users, doesn't it?  Our only supported platform?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqU1JCKw4jWUQCO6ov:br2982b)*

**Comment by Lucy-tri** [comment]
OK, so assuming g++-5 is correct for Xenial, then I should change this doc to have 5 for Xenial and 4.9 for Trusty?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqUfHE27wp3us0cNI3:b-rkmc65)*

**Comment by jwnimmer-tri** [comment]
(Discussed f2f; experiments and updates pending.)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqY5TpjIW8BS0kVyX8:b7qepam)*

**Comment by Lucy-tri** [comment]
As @jwnimmer-tri  suspected, if Ubuntu 16 has no special instructions or setup for gcc (and fortran, etc.), it will work just fine. The env var setup only needs to happen for Ubuntu 14, where we are not using the default gcc. So now it just has a note explaining it's only for Ubuntu 14. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSqzLbCQnpHrbw2KhNa:bi2vz2g)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSr1xwvIwPC3wgj5z3C:bnfp4nl)*

**Comment by Lucy-tri** [comment]
Slave went offline during the build
13:46:47 ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
13:46:47 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)

@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3611#-:-KSr501uoEkC144SutBk:bu4179l)*

**Comment by jwnimmer-tri** [comment]
Lucy asserts that this builds locally without any sphinx warnings.  Using override-merge for doc-only change, since Jenkins is extra flaky today.

**Pull request merged**
