### PR TITLE
Add changelog for #2666

### PR DESCRIPTION
**Pull request by wxmerkt**
#2666 didn't include a changelog for an API change; added as just tripped over this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2774)

### CODE REVIEW

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2774#-KMPrjnrRy5F3xO_T87m:-KMPrjnrRy5F3xO_T87n:1998559678) ([raw file](https://github.com/robotlocomotion/drake/blob/731b77de6ea60b8a318a2c84c73cf2d796b797ab/CHANGELOG.md#L81)):*
> ```Markdown
> [#2602]: https://github.com/RobotLocomotion/drake/issues/2602
> [#2621]: https://github.com/RobotLocomotion/drake/issues/2621
> [#2666]: https://github.com/RobotLocomotion/drake/issues/2666
> ```

missing newline at end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2774)*

**Comment by david-german-tri** [comment]
Thanks, and apologies!

**Comment by wxmerkt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2774#-KMPrjnrRy5F3xO_T87m:-KMQ7wU5RqXIdfhxQyfx:-533640921) ([raw file](https://github.com/robotlocomotion/drake/blob/731b77de6ea60b8a318a2c84c73cf2d796b797ab/CHANGELOG.md#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at end of file
</details>
Thanks - Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2774)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2774#-:-KMQDij-VX1kHeXNUnyR:1417088721)*

**Pull request merged**
