### PR TITLE
FixUp GCS PhiConstraint test

### PR DESCRIPTION
**Pull request by RussTedrake**
PR #21053 to upgrade clarabel fell over on some numerical problems in the PhiConstraint unit test.  I've captured that failure and reported it in https://github.com/oxfordcontrol/Clarabel.rs/issues/96 .

In examining the problem, I found a number of small errors in the existing test. Resolving those errors allows clarabel 7.1 to pass the tests without any upstream changes required.

The changes in the PhiConstraint test are:

- QuadraticCost was being used incorrectly (we forgot the factor of 2). It was also documented as being the L2 norm, instead of the L2 norm squared.

- Added a diagram to the doc and minor code cleanup.

In GCS, I made two changes, both of which have no functional impact:

- The bounding box constraint with lb==ub was replaced with a linear equality constraint (which should be preferred).

- I've slightly improved the variable names used in the mathematical program, for readability during debugging. This program is intentionally not exposed to the user, and all of the changes were to internally defined variables. Although a user _could_ have gotten to these by mucking around in the MathematicalProgramResult, there is nothing in the API contract that would make this a breaking change.

+@bernhardpg for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21330)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
-@bernhardpg +@AlexandreAmice for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21330#-:-Nvo91CPAoRs8PtDpP1G:bys0vt0)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21330#-:-NvrktM6-5qwBbDQ37RH:bg7igkv)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1404 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21330#-Nvrjvap00dHIHo4yddz:-NvrjvaqBpIcdKWsjYUN:b61cmi3) ([raw file](https://github.com/RobotLocomotion/drake/blob/bef0dcfd72bb902fe053c28804f0a77b3c64b7de/geometry/optimization/test/graph_of_convex_sets_test.cc#L1404)):*
> ```cpp
> //   │        ┌──┐      │
> //   └───────►│v1├──────┘
> //            └──┘
> ```

BTW: is this rendering correctly in your IDE? I know that reviewable sometimes renders ascii art strangely.



_Code quote:_
```cpp
//            ┌──┐
//   ┌───────►│v2├──────┐
//   │        └──┘      │
//   │                  ▼
// ┌─┴┐                ┌──┐
// │v0│                │v3│
// └─┬┘                └──┘
//   │                  ▲
//   │        ┌──┐      │
//   └───────►│v1├──────┘
//            └──┘
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21330#-:-Nvrpec8-55xfeL-Gniz:b-vtj4vo)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1404 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21330#-Nvrjvap00dHIHo4yddz:-Nvrq5e65QqxbHmg7iA4:b-pvq0z4) ([raw file](https://github.com/RobotLocomotion/drake/blob/bef0dcfd72bb902fe053c28804f0a77b3c64b7de/geometry/optimization/test/graph_of_convex_sets_test.cc#L1404)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: is this rendering correctly in your IDE? I know that reviewable sometimes renders ascii art strangely.
</blockquote></details>

It displays fairly well for me in reviewable.  Locally my font doesn't quite get the monospace right, but the same is true for other ASCII art figures in other tests in this file.

**Pull request merged**
