### PR TITLE
Port drake/examples to FindResource

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6446)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@naveenoid feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnfkEd0jOXmuY9fkH7C:bwbt7zt)*

**Comment by kunimatsu-tri** [comment]
cc @jwnimmer-tri

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnipMOrt3yOSfLdZWDh:b-1a6oaw)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by naveenoid** [comment]
I left some BTWs related to moving the string paths to const char* for cleanliness sake. I leave it up to you to change if you want. :lgtm: 

---

Reviewed 79 of 79 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[drake/examples/Pendulum/pendulum_run_lqr.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoLTXOGY5UIzjFZQsE:-KnoLTXOGY5UIzjFZQsF:b23okjs) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Pendulum/pendulum_run_lqr.cc#L29)):*
> ```cpp
>   auto tree = std::make_unique<RigidBodyTree<double>>();
>   drake::parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>       FindResourceOrThrow("drake/examples/Pendulum/Pendulum.urdf"),
> ```

BTW: I know its not directly related to this PR but perhaps you can move this string to a const char * to be a bit cleaner like all the other examples?

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoLeW-Fn-qMDxZfEVD:-KnoLeW-Fn-qMDxZfEVE:b-fe0a1w) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Pendulum/pendulum_run_swing_up.cc#L93)):*
> ```cpp
>   auto tree = std::make_unique<RigidBodyTree<double>>();
>   parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>       FindResourceOrThrow("drake/examples/Pendulum/Pendulum.urdf"),
> ```

BTW: Same comment (move to const char*) maybe?

---

*[drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoLl9HHa-CeWl98BrQ:-KnoLl9HHa-CeWl98BrR:b-t3q7e4) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Pendulum/test/pendulum_urdf_dynamics_test.cc#L20)):*
> ```cpp
>   auto tree = std::make_unique<RigidBodyTree<double>>();
>   parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>       FindResourceOrThrow("drake/examples/Pendulum/Pendulum.urdf"),
> ```

BTW: const char * maybe?

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoM12GphK2zCk1nXci:-KnoM12GphK2zCk1nXcj:brch04q) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc#L43)):*
> ```cpp
>       "drake/multibody/test/rigid_body_tree/two_dof_robot.urdf");
>   std::string config = FindResourceOrThrow(
>       std::string(kTestDir) + "test.alias_groups");
> ```

BTW: consider const char* 

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/joint_level_controller_system_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMO_hWRXKQuIpNg8A:-KnoMO_hWRXKQuIpNg8B:b-rga7g2) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/QPInverseDynamicsForHumanoids/system/test/joint_level_controller_system_test.cc#L29)):*
> ```cpp
>         FindResourceOrThrow(
>             "drake/examples/Valkyrie/urdf/urdf/"
>             "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
> ```

BTW: const char*?

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMY74AEJD2YN9OzLn:-KnoMY74AEJD2YN9OzLo:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc#L24)):*
> ```cpp
>   std::string urdf = FindResourceOrThrow(
>       "drake/manipulation/models/iiwa_description/urdf/"
>       "iiwa14_polytope_collision.urdf");
> ```

BTW: const char*

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/lcm_utils_test.cc, line 203 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMbsTmGPSBADxdMmm:-KnoMbsUSLXhOr_7jwv1:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/QPInverseDynamicsForHumanoids/test/lcm_utils_test.cc#L203)):*
> ```cpp
>     parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>         FindResourceOrThrow(
>             "drake/examples/Valkyrie/urdf/urdf/"
> ```

BTW: const char*

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMhrpVa30EsF5DQI9:-KnoMhrpVa30EsF5DQIA:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc#L36)):*
> ```cpp
>   std::string controller_config = FindResourceOrThrow(
>       "drake/examples/QPInverseDynamicsForHumanoids/"
>       "config/valkyrie.id_controller_config");
> ```

BTW: const char*

---

*[drake/examples/Quadrotor/run_quadrotor_dynamics.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMndXBHJNRPo-1VTa:-KnoMndXBHJNRPo-1VTb:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Quadrotor/run_quadrotor_dynamics.cc#L51)):*
> ```cpp
>     AddModelInstancesFromSdfFile(
>         FindResourceOrThrow("drake/examples/Quadrotor/warehouse.sdf"),
>         kFixed, nullptr /* weld to frame */, tree.get());
> ```

BTW: const char*

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMrZMDumB5Crh04qw:-KnoMrZMDumB5Crh04qx:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L45)):*
> ```cpp
>   auto tree = std::make_unique<RigidBodyTree<double>>();
>   parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>       FindResourceOrThrow("drake/examples/Quadrotor/quadrotor.urdf"),
> ```

BTW: const char*

---

*[drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoMvrHGayOT5SDQkub:-KnoMvrHGayOT5SDQkuc:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Quadrotor/test/quadrotor_dynamics_test.cc#L79)):*
> ```cpp
> 
>     drake::parsers::urdf::AddModelInstanceFromUrdfFile(
>         FindResourceOrThrow("drake/examples/Quadrotor/quadrotor.urdf"),
> ```

BTW: const char*

---

*[drake/examples/schunk_wsg/simulated_schunk_wsg_system.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoN6z0YtJsygFno941:-KnoN6z0YtJsygFno942:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/schunk_wsg/simulated_schunk_wsg_system.cc#L21)):*
> ```cpp
>   drake::parsers::sdf::AddModelInstancesFromSdfFile(
>       FindResourceOrThrow(
>           "drake/manipulation/models/wsg_50_description/sdf/schunk_wsg_50.sdf"),
> ```

BTW: const char*

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNAAoNsJCWH0dVn4k:-KnoNAAoNsJCWH0dVn4l:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L64)):*
> ```cpp
>   const auto lifter_id_table =
>       parsers::sdf::AddModelInstancesFromSdfFile(
>       FindResourceOrThrow("drake/examples/schunk_wsg/test/test_lifter.sdf"),
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/valkyrie_pd_ff_controller.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNFf8m-gTKPyd19hv:-KnoNFf8m-gTKPyd19hw:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/valkyrie_pd_ff_controller.cc#L130)):*
> ```cpp
> void run_valkyrie_pd_ff_controller() {
>   std::string urdf = FindResourceOrThrow(
>           "drake/examples/Valkyrie/urdf/urdf/"
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/valkyrie_simulator.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNJ5iQgfvCT6K2igz:-KnoNJ5iQgfvCT6K2ih-:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/valkyrie_simulator.h#L47)):*
> ```objc
>         FindResourceOrThrow(
>             "drake/examples/Valkyrie/urdf/urdf/"
>             "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/test/robot_command_to_desired_effort_converter_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNL3Zjwyaw-ma-2U9:-KnoNL3Zjwyaw-ma-2UA:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/test/robot_command_to_desired_effort_converter_test.cc#L70)):*
> ```cpp
>       FindResourceOrThrow(
>           "drake/examples/Valkyrie/urdf/urdf/"
>           "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/test/robot_command_to_desired_effort_converter_test.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNMFJ-oI2sJWf7uDA:-KnoNMFJ-oI2sJWf7uDB:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/test/robot_command_to_desired_effort_converter_test.cc#L88)):*
> ```cpp
>       FindResourceOrThrow(
>           "drake/examples/Valkyrie/urdf/urdf/"
>           "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNOiOSxfNHccaRaH_:-KnoNOiOSxfNHccaRaHa:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L64)):*
> ```cpp
>       FindResourceOrThrow(
>           "drake/examples/Valkyrie/urdf/urdf/"
>           "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
> ```

BTW: const char*

---

*[drake/examples/Valkyrie/test/valkyrie_ik_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-KnoNQfZ_GsVV44GVWWA:-KnoNQfZ_GsVV44GVWWB:b-vvomn) ([raw file](https://github.com/robotlocomotion/drake/blob/aa904c328bec03ef24d46afbc9cd80d99911a9bb/drake/examples/Valkyrie/test/valkyrie_ik_test.cc#L70)):*
> ```cpp
>           "drake/examples/Valkyrie/urdf/urdf/"
>           "valkyrie_A_sim_drake_one_neck_dof_wide_ankle_rom.urdf"),
>       multibody::joints::kRollPitchYaw, tree.get());
> ```

BTW: const char*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnoNTHk0xWmbWCi9-94:b-fvfmsm)*

**Comment by kunimatsu-tri** [comment]
Thanks @naveenoid for reviewing.

I replaced those strings literals with `const char*` only when it's used more than once in a file.
For the rest, I will leave it to the original authors.

+@soonho-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnomctYQiP0Pj1Z89aX:b-1rusns)*

**Comment by soonho-tri** [comment]
I just want to point that we're using three different types to hold string literals:

```c++
// drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc
const char kRelUrdfPath[] =
    "drake/manipulation/models/jaco_description/urdf/j2n6s300.urdf";

// drake/examples/kuka_iiwa_arm/iiwa_controller.cc
const char* const kIiwaUrdf = "drake/manipulation/models/iiwa_description/urdf/"
    "iiwa14_polytope_collision.urdf";

// drake/examples/kuka_iiwa_arm/kuka_simulation.cc
const std::string kModelPath = "drake/manipulation/models/iiwa_description/"
    "urdf/iiwa14_polytope_collision.urdf";
```

I'll also leave it up to you to change if you want (or feel free to ignore them or delegate them to the owner of each directory).

:lgtm: 

---

Reviewed 53 of 79 files at r1, 25 of 26 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-Knq6LA3jBl_WqmfBkEM:baazdq5)*

**Comment by kunimatsu-tri** [comment]
Thanks @soonho-tri and Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnqEwZyx2vZjDksGdSR:b1uejf5)*

**Comment by soonho-tri** [comment]
:lgtm: Thank you.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6446#-:-KnqHSldpEgGkS6i3XNn:b-ae66do)*

**Pull request merged**
