### PR TITLE
More install_prereqs refactoring

### PR DESCRIPTION
**Pull request by jamiesnape**
Two refactorings here. The first enables the source distribution `install_prereqs.sh` to be run in isolation (which saves downloading the binary distribution one that is already included in the binary distribution archives) for Shambhala. The second splits the Debian packages off into a text file, which helps with the creation of Debian packages for Drake itself.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8106)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review. This can wait until after #8016 if you prefer.

**Comment by jwnimmer-tri** [comment]
> This can wait until after #8016 if you prefer.

This is fine; I don't mind resolving merge conflicts if my PR remains stalled.

Code read-through done.  I'll test locally if / after any changes get pushed.

Needs mac feature reviewer.

---

Reviewed 6 of 14 files at r1.
Review status: 6 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nmt--mfKgSYQ5uWwI:-L5nmt-0DWRm4N1fHSTW:b-aic7y7) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L28)):*
> ```Shell
> apt install --no-install-recommends lsb-release
> 
> [[ "$(lsb_release -sc)" == 'xenial' ]] || die "${me} only supports Ubuntu 16.04."
> ```

It seems to me that in `binary_distribution/install_prereqs.sh`, it would be  important to check for Xenial prior to adding apt sources that hard-code xenial.  Thus, this check should move over there?  (At which point, the run-as-root check moves there as well, and then this script here has no more useful logic it in, and the at_exit reporting should move into those scripts; they deserve good error reporting, even prior to this PR.)

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nm3WRlg1qdKWIflLe:-L5nm3WRlg1qdKWIflLf:b-9catup) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L36)):*
> ```Shell
> # Note that the list of packages in binary_distribution/packages.txt is used to
> # generate the dependencies of the drake .deb package, so does not include
> # development dependencies such as build-essential and cmake.
> ```

BTW Wouldn't this comment make more sense if placed within `binary_distribution/install_prereqs.sh` instead of here?

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5noSUVEvRW8u7khDxx:-L5noSUW6zA4ikweeQQo:b4wwps3) ([raw file](https://github.com/robotlocomotion/drake/blob/c7c1ba95ecb3c8ddf35d4ece07f9455f2f64e66b/setup/ubuntu/16.04/install_prereqs.sh#L43)):*
> ```Shell
> clang-4.0
> clang-format-4.0
> cmake-curses-gui
> ```

BTW Please amend the commit message to specifically call out that we've removed `cmake-curses-gui` -- that its not just a vanilla refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-:-L5nnw4oOtcpkhTmPQeF:bpd6ux7)*

**Comment by jamiesnape** [comment]
Review status: 6 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nmt--mfKgSYQ5uWwI:-L5nqrkU9cCJ2dqX3X1E:bil1g0q) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me that in `binary_distribution/install_prereqs.sh`, it would be  important to check for Xenial prior to adding apt sources that hard-code xenial.  Thus, this check should move over there?  (At which point, the run-as-root check moves there as well, and then this script here has no more useful logic it in, and the at_exit reporting should move into those scripts; they deserve good error reporting, even prior to this PR.)
</blockquote></details>

Maybe so, I will look into it.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nm3WRlg1qdKWIflLe:-L5nqOqBDTQU5C7TZ4HN:b-nxz2fx) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Wouldn't this comment make more sense if placed within `binary_distribution/install_prereqs.sh` instead of here?
</blockquote></details>

It would, but it kind of loses its context when installed, hence it is here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106)*

**Comment by jwnimmer-tri** [comment]
*[setup/ubuntu/16.04/install_prereqs.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nm3WRlg1qdKWIflLe:-L5nu-4VM8-qCJfyuDty:b92ggjc) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L36)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It would, but it kind of loses its context when installed, hence it is here.
</blockquote></details>

OK This is fine.  A possible improvement (either in this PR, or future one) might be to add a README.md to this folder that explains an overview of all of the pieces and what they are responsible for, thus shortening or removing the rationale comments such as this one sprinkled across the files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106)*

**Comment by jamiesnape** [comment]
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nmt--mfKgSYQ5uWwI:-L5nvSvjuapROmgt2IgJ:bg4bf9k) ([raw file](https://github.com/robotlocomotion/drake/blob/8e1ec5fed33316bc149672abb98c4069d98ce3ea/setup/ubuntu/16.04/install_prereqs.sh#L28)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Maybe so, I will look into it.
</blockquote></details>

Moved the Xenial check across. Will add improved error reporting in all scripts in a separate commit.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5noSUVEvRW8u7khDxx:-L5nvagCgIk-QjW_z4GB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7c1ba95ecb3c8ddf35d4ece07f9455f2f64e66b/setup/ubuntu/16.04/install_prereqs.sh#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Please amend the commit message to specifically call out that we've removed `cmake-curses-gui` -- that its not just a vanilla refactor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: 6 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nxZggaHRIchzTdV8T:-L5nxZghPXHXoffc2utD:bcvtfi7) ([raw file](https://github.com/robotlocomotion/drake/blob/4126408a4319320734d68ecb2b177682f19aef18/setup/ubuntu/16.04/install_prereqs.sh#L12)):*
> ```Shell
>     trap : EXIT  # Disable line number reporting; the "$@" message is enough.
>     exit 1
> }
> ```

BTW This function is dead code now.

---

*[setup/ubuntu/16.04/binary_distribution/install_prereqs.sh, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nxw-wlxXGplRbJRJ9:-L5nxw-xSngoWD-X5VcG:buzun58) ([raw file](https://github.com/robotlocomotion/drake/blob/4126408a4319320734d68ecb2b177682f19aef18/setup/ubuntu/16.04/binary_distribution/install_prereqs.sh#L22)):*
> ```Shell
> )
> 
> if [[ "$(lsb_release -sc)" == 'xenial' ]]; then
> ```

BTW I think the condition is opposite of what we want?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106)*

**Comment by jamiesnape** [comment]
Review status: 4 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/binary_distribution/install_prereqs.sh, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-L5nxw-wlxXGplRbJRJ9:-L5o1hxKdPRGmxi6ZNFz:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/4126408a4319320734d68ecb2b177682f19aef18/setup/ubuntu/16.04/binary_distribution/install_prereqs.sh#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think the condition is opposite of what we want?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106)*

**Comment by jwnimmer-tri** [comment]
Code LGTM.  Will test soon.

---

Reviewed 2 of 2 files at r3.
Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-:-L5o2ORXGuXE8MlteipS:b-s8sek9)*

**Comment by jamiesnape** [comment]
+@soonho-tri for mac feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
:lgtm: tested locally that the scripts run to completion without error, and that the installed prereqs script runs to completion.

---

Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-:-L5oHkORb8q-wStHZ2lT:b-pka9az)*

**Comment by soonho-tri** [comment]
:lgtm:, locally tested.

---

Reviewed 8 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-:-L5oMYpRm3AxQPhy6h1D:bsmqy34)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8106#-:-L5oZUYhQEr0qqstz5F3:bnfp4nl)*

**Pull request merged**
