### PR TITLE
[ad] Add support for nearest-integer functions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: minor author's-discretion suggestions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657#-:-N8OhN8N1ZPs2xwjZ_1l:b-tepbp5)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[`common/ad/internal/standard_operations.h` line 226 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8OfAal6B6Dtc3pZ5LF:-N8OfAam3BrHP9mZGrvi:bjagaoj) ([raw file](https://github.com/robotlocomotion/drake/blob/0ebbeabd58a239bc19511d690ad97e6faaa5d43a/common/ad/internal/standard_operations.h#L226)):*
> ```objc
> 
> /** ADL overload to mimic std::ceil from <cmath>.
> Discards the derivatives. */
> ```

minor:  "Discards the derivatives" sounds like a warning, even though really it's just the definition of the function.

"Its derivatives are all always zero" might be more informative (ie that we don't implement the non-finite derivative at the discontinuities) and less ominous?
___
*[`common/ad/internal/standard_operations.h` line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8Oeyu-34pxMbuGxNEV:-N8Oeyu0D53fYF2reISb:bfo390s) ([raw file](https://github.com/robotlocomotion/drake/blob/0ebbeabd58a239bc19511d690ad97e6faaa5d43a/common/ad/internal/standard_operations.h#L242)):*
> ```objc
> 
> /** ADL overload to mimic std::isfinite from <cmath>.
> Discards the derivatives. */
> ```

minor:  Here and below I see no need to document "discards the derivatives" as the return type is just `bool`.
___
*[`common/ad/test/standard_operations_integer_test.cc` line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8Ogtrx-k7gorYTU-r6:-N8Ogtrx-k7gorYTU-r7:bgdy80g) ([raw file](https://github.com/robotlocomotion/drake/blob/0ebbeabd58a239bc19511d690ad97e6faaa5d43a/common/ad/test/standard_operations_integer_test.cc#L13)):*
> ```cpp
>   const AutoDiffDut x{0.5, 3, 0};
>   const AutoDiffDut y = ceil(x);
>   EXPECT_EQ(y.value(), 1.0);
> ```

minor:  Might this phrasing (here and below) more clearly state the invariant?
Author's discretion -- I can see both sides.



_Suggestion:_
```cpp
std::ceil(x.value())
```
___
*[`common/ad/test/standard_operations_integer_test.cc` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8OhiGY2IsBCPrhjoJm:-N8OhiGZ-a2D0RuHdueF:bd3nuqb) ([raw file](https://github.com/robotlocomotion/drake/blob/0ebbeabd58a239bc19511d690ad97e6faaa5d43a/common/ad/test/standard_operations_integer_test.cc#L34)):*
> ```cpp
>   const AutoDiffDut x{0.5, 3, 0};
>   const AutoDiffDut y = nexttoward(x, 1.0);
>   EXPECT_EQ(y.value(), 0.5000000000000001);
> ```

minor:  I slightly prefer the phrasing of `AutodiffOverloadsTest::NextToward` which explicitly obtains and adds the ulp.  But author's discretion.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657)* status: LGTM missing from assignee sherm1(platform) (waiting on @ggould-tri and @sherm1)

___
*[`common/ad/internal/standard_operations.h` line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8Oeyu-34pxMbuGxNEV:-N8OlYG11zBpiaWB_kJ6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ebbeabd58a239bc19511d690ad97e6faaa5d43a/common/ad/internal/standard_operations.h#L242)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Here and below I see no need to document "discards the derivatives" as the return type is just `bool`.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one question

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657#-:-N8P_x1u4y6d3_fJC-mO:b-iwjkzv)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/ad/internal/standard_operations.cc` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8PZH-iCpZLde4Hen8R:-N8PZH-jB3aIu3OesscF:bhg780p) ([raw file](https://github.com/robotlocomotion/drake/blob/ebf857a10cf1dfaf572c3a8d4e40bdeed370b8ec/common/ad/internal/standard_operations.cc#L18)):*
> ```cpp
> AutoDiff ceil(AutoDiff x) {
>   x.value() = std::ceil(x.value());
>   x.partials().SetZero();
> ```

BTW I was surprised to see that this doesn't set the derivatives back to being zero length but rather just fills whatever's there with zeros. Wouldn't it be more efficient to use the zero-length trick, and easy if the machinery for dealing with that is already in place?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17657)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[`common/ad/internal/standard_operations.cc` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17657#-N8PZH-iCpZLde4Hen8R:-N8Par7G5xE7uhVSypQQ:b-1dzd0q) ([raw file](https://github.com/robotlocomotion/drake/blob/ebf857a10cf1dfaf572c3a8d4e40bdeed370b8ec/common/ad/internal/standard_operations.cc#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I was surprised to see that this doesn't set the derivatives back to being zero length but rather just fills whatever's there with zeros. Wouldn't it be more efficient to use the zero-length trick, and easy if the machinery for dealing with that is already in place?
</blockquote></details>

Down the road, the implementation of `SetZero()` will become more efficient (two branches, a bitwise-or, and decrementing the use_count of any partials on the heap).

When performing operations on an AutoDiff, an important invariant is that the known-size of partials remains intact, even when the gradient goes to zero.  We want to fail-fast in case the user mixes this return value with a differently-sized operand later, and users generally expect a non-zero size outputs at the end of their full calculation, matching whatever size they initialized it with.

**Pull request merged**
