### PR TITLE
Updated Prius Demo

### PR DESCRIPTION
**Pull request by liangfok**
Contributes towards https://github.com/RobotLocomotion/drake/issues/1654.

# Main Changes:
- Cleaned up `prius.sdf` by removing trailing spaces and separating each link / joint with a blank line. The ability to discern different joints and links is easier on my eyes.
- Added a `prius_with_lidar.sdf` that contains four LIDAR sensors. Verified it loads in both Gazebo and Drake. The sensor works in Gazebo, but is not yet parsed / instantiated in Drake. I will add that in a future PR.
- Polished the README for this car demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2134) &emsp; Multiple assignees:&emsp;@RussTedrake&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/RussTedrake">RussTedrake</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by liangfok** [comment]
@RussTedrake, since this is mostly SDF updates, I'll assign this to you. I'd like to get this merged before I submit a followup PR that adds SDF parsing of sensor elements to Drake.

**Comment by liangfok** [comment]
@david-german-tri: I encountered a strange CI flake on [build 961](https://drake-jenkins.csail.mit.edu/job/experimental/961/). The Windows tests failed with the following error:

```
Cannot open include file: 'drake/drakeRBSystem_export.h': No such file or directory
```

I don't think it's the same as https://github.com/RobotLocomotion/drake/issues/2035.

**Comment by jwnimmer-tri** [comment]
@liangfok The actual error is:
01:45:27 cl : Command line error D8040: error creating or communicating with child process [C:\projects\workspace\experimental\e052ff41\pod-build\externals\lcm\lcm-prefix\src\lcm-build\lcm\lcm.vcxproj] [C:\projects\workspace\experimental\e052ff41\pod-build\externals\lcm\lcm.vcxproj] [C:\projects\workspace\experimental\e052ff41\pod-build\lcm.vcxproj]

Your error message is subsequent to that:
01:50:54 C:\projects\workspace\experimental\e052ff41\drake\..\drake/systems/plants/RigidBodyFrame.h(5): fatal error C1083: Cannot open include file: 'drake/drakeRBSystem_export.h': No such file or directory (compiling source file C:\projects\workspace\experimental\e052ff41\drake\systems\plants\RigidBodyTreeURDF.cpp) [C:\projects\workspace\experimental\e052ff41\drake\pod-build\systems\plants\drakeRBM.vcxproj]

**Comment by liangfok** [comment]
Ah. Thanks. So is that the same flake as https://github.com/RobotLocomotion/drake/issues/2035?

**Comment by jwnimmer-tri** [comment]
Actually, #2135.  Neat now the msvc CI flakes are off-by-100.

**Comment by david-german-tri** [comment]
No, I do not think this is a WinRM hiccup.  That message is coming from Visual Studio on the build slave, which means  Jenkins is still connected to the buildslave VM.  @jwnimmer-tri filed #2135 separately and I think that's correct.

**Comment by liangfok** [comment]
Thanks. What the best practice for my current situation? Should I simply ask Jenkins to run again and hope the flake goes away?

**Comment by david-german-tri** [comment]
This isn't a flake; it's sinking all the builds.  No point re-running until it's diagnosed and fixed.

**Comment by liangfok** [comment]
OK I will wait.

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Should this still be assigned to me?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KFtzG_ral3EhW8rsq0K:-258440983)*

**Comment by liangfok** [comment]
Since you're looking into fixing the CI now, I will re-assign this back to @russtedrake. Sorry I didn't do so sooner.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KFu0-hqc86uZGMpvb4A:-298372223)*

**Comment by liangfok** [comment]
@RussTedrake: This PR is ready for another round of review. I assigned it to you since it's primarily the addition of a new SDF file (a Prius with four LIDAR sensors).

**Comment by RussTedrake** [comment]
it's impossible to carefully review the big sdf file addition, but it looks aok to me on quick inspection.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/README.md, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDC7CRl-GCRDbKH6i:-KGFDC7DuUsWoym4G5hZ:-1993516107) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/README.md#L12)):*
i worry a bit that this could get confused future environment variables that we may or may not ask people to set.  perhaps it's ok.

---

*[drake/examples/Cars/README.md, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDPmLcWq4irGjeCdx:-KGFDPmLcWq4irGjeCdy:2104595424) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/README.md#L16)):*
you don't actually need the `export` for this, since you're only using it in the local shell, and that might contain the change.

---

*[drake/examples/Cars/prius/prius_with_lidar.sdf, line 582 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDrl--UOwbtESVtwc:-KGFDrl--UOwbtESVtwd:-2054724643) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/prius/prius_with_lidar.sdf#L582)):*
wow.  that's a lot of precision. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KGFE-0MiS6yvMaQCX09:825426551)*

**Comment by liangfok** [comment]
@russtedrake: I've addressed your comments. PTAL.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/README.md, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDC7CRl-GCRDbKH6i:-KGFHy2PP9ilccKqutwk:-534603135) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/README.md#L12)):*
Since there's a potential to be confusing and @billhoffman is against using environment variables, I shall remove this and update the instructions.

---

*[drake/examples/Cars/README.md, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDPmLcWq4irGjeCdx:-KGFIkNLxiiNWiJOOg-k:1265122089) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/README.md#L16)):*
Fixed. Removed command from instructions.

---

*[drake/examples/Cars/prius/prius_with_lidar.sdf, line 582 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFDrl--UOwbtESVtwc:-KGFH7SNZenSyfJ0tkpv:-1156915688) ([raw file](https://github.com/robotlocomotion/drake/blob/2a7521f74a959b83796b09c520a3a43e535b54ba/drake/examples/Cars/prius/prius_with_lidar.sdf#L582)):*
Yeah, I figured having more decimal places wouldn't hurt. It was in fact necessary to get the Prius SDF and URDF models to match with a tolerance equal to the machine epsilon. Eventually, I'd like to see Drake support model specifications with [properties and simple math expressions using them](http://wiki.ros.org/xacro#Math_expressions). This would simplify the above number to be a simple `${pi/2}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KGFIybLL8D9pWEsLhcj:-2065208248)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KGFLwOOIm4oFWXw_R4M:1417088721)*

**Comment by liangfok** [comment]
+@jwnimmer-tri  Forwarding to you for final review / merge.  Thanks!!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KGFNKHYdU8yKz4z31qz:235411015)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/Cars/README.md, line 15 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-KGFQIp-7o680yOTTkuc:-KGFQIp-7o680yOTTkud:1484645708) ([raw file](https://github.com/robotlocomotion/drake/blob/42d34a619c1647b0774432727086101a7880469f/drake/examples/Cars/README.md#L15)):*
For the record, in the SimpleCar example we put all of this (and the below) detail into a shell script -- so the users have a one-liner to run the demo.  (Though looking now, SimpleCar should still have a README saying "Hey, run the simple_car_demo.sh!").  You might consider turning these shell commands into a script instead, next time you are fixing up things in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2134#-:-KGFQFD0AQz6oFluImkg:1417088721)*

**Comment by jwnimmer-tri** [comment]
Just need Jenkins to pass and then we can merge.

**Comment by jwnimmer-tri** [comment]
Actually, the final commit was README-only.  The prior 2a7521f passed CI except for the OSX flake #2154.  Going to override-merge now.

**Pull request merged**
