### PR TITLE
Superbuild refactor, part 2

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Continue refactoring the top-level CMakeLists.txt (i.e. 'the superbuild') into several files (see also part 1: #2820). In particular, this extracts the external project logic into functions and converts the mostly-declarative (and somewhat superfluously repetitive) logic for setting up externals into more imperative/procedural logic that is hopefully better organized and easier to read.

One particular change of note is that all special case "externals" have been removed in favor of new options `ALWAYS` and `LOCAL`, indicating, respectively, that an external is always enabled, and that an external is local to the repository (does not need download/update steps). This allows drake itself to be simply a `LOCAL`, `ALWAYS` subproject rather than having a completely separate block for setting up the subproject. The mechanism for propagating cache values from the superbuild to the external projects has also been improved.

The overall formatting and documentation (comments) of the superbuild logic has also been improved. In particular, the new functions all have at least a brief blurb describing their purpose, and similar documentation has been added to the recently added functions in `config.cmake`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2896)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by david-german-tri** [comment]
I haven't finished grokking `externals.cmake` - will continue on Monday.  This change works for me with `make` on both Linux and Mac, but note the Mac CI failure, which looks real.

---

Reviewed 3 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 222 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJBfrRCNjDvqklo9AF:-KNJBfrSBxr33rN1koeB:-1016680470) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/CMakeLists.txt#L222)):*
> ```CMake
> # director
> drake_add_external(director PUBLIC
>   BUILD_COMMAND_DIR distro/pods/drake-distro # FIXME
> ```

Please elaborate on the `# FIXME`

---

*[cmake/externals.cmake, line 107 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJPvUjDA_ElHG2Dhp_:-KNJPvUkGrJYuviB-IW4:-825418087) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/cmake/externals.cmake#L107)):*
> ```CMake
>     # All targets that contain a submodule update command, or depend on a
>     # target that does, need to depend on the submodule-sync target.
>     foreach(_step_target ${PROJECT} ${PROJECT}-update)
> ```

BTW, note to self: this function combines drake_forceupdate and drake_depend_submodule_sync, which were always called back-to-back anyway.

---

*[cmake/externals.cmake, line 129 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJR3OJfRSNQZB4bxvv:-KNJR3OJfRSNQZB4bxvw:1316780545) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/cmake/externals.cmake#L129)):*
> ```CMake
>   endif()
> 
>   # Capture additional commands for ep_add
> ```

What's `ep_add`?

---

*[cmake/externals.cmake, line 233 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJOeqQ74nitfvZAI8M:-KNJOeqQ74nitfvZAI8N:1900317468) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/cmake/externals.cmake#L233)):*
> ```CMake
> #   PUBLIC - External is public
> #   CMAKE  - External uses CMake
> #   ALWAYS - External is always build
> ```

s/build/built

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNJTyrhVLGWN3TTIm5H:-1890300088)*

**Comment by mwoehlke-kitware** [comment]
The OS X CI failure is a bunch of `-Werror=shadow` problems. Nothing in this PR should be affecting that in any way; the logic to add `-Werror=shadow` is in [`drake/CMakeLists.txt`](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/drake/CMakeLists.txt#L85) and hasn't been touched, and there are no source changes. I don't know why it would be tripping for this PR but not generally...

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/externals.cmake, line 129 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJR3OJfRSNQZB4bxvv:-KNXhzw9fzG1ipoSiaKz:-1792584603) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/cmake/externals.cmake#L129)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> What's `ep_add`?
</details>
`ep` is short for `ExternalProject`. "...for ExternalProject_add" looks strange to me; will change this to "...for the external project" instead.

---

*[cmake/externals.cmake, line 233 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJOeqQ74nitfvZAI8M:-KNXiIL_w-JBwQK06Yfr:-561903756) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/cmake/externals.cmake#L233)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> s/build/built
</details>
Good catch, thanks...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNXh8HWAXTWE_3WzsdN:-841760401)*

**Comment by mwoehlke-kitware** [comment]
Specifically, this is #2915, and it *is* showing up on master... not sure why it only just started showing up...

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNXkD18mL_qyQNtZer5:-1910244570)*

**Comment by mwoehlke-kitware** [comment]
Oh, here it is: looks like probably f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333 broke it.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNXkiI2MPmSBBSP57xJ:-232739373)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 222 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNJBfrRCNjDvqklo9AF:-KNXoa4ABkYRUYoqS8lG:852732104) ([raw file](https://github.com/robotlocomotion/drake/blob/830d4766359c557e24cb5519e82ba8e39af353a3/CMakeLists.txt#L222)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please elaborate on the `# FIXME`
</details>
Old diff? Current version says "FIXME: fix need for this". (There is also a somewhat better comment in `externals.cmake` where this argument is handled.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

@david-german-tri, ping? (#2915 should be fixed, so firing off that build again to verify; otherwise, are there any issues remaining?)

**Comment by david-german-tri** [comment]
Aside from one comment, looks good to me.  Before I emoji-LGTM it, let me inquire whether @russtedrake wants to review.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNcYb3pJfo84EGhB7Qx:1805176462) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
> ```CMake
>     string(TOUPPER ${_ext_req_found} _ext_req_found_upper)
>     find_package(${_ext_req})
>     if(DEFINED ${_ext_req_found} AND ${_ext_req_found})
> ```

Please add a comment explaining why we need to check for both lower-case and upper-case.  I can't find equivalent logic in the LHS of this diff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNc_UnRDbBtYC7nPDkm:1656922846)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNccxL8nTo1pxXyQF0t:-1368698227) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
> I can't find equivalent logic in the LHS of this diff.


The old logic was:

    if(WITH_TEXTBOOK OR WITH_ALL_SUPPORTED_EXTERNALS OR WITH_ALL_PUBLIC_EXTERNALS)
      find_package(PythonInterp)
      if(NOT PYTHON_EXECUTABLE)
        message(FATAL_ERROR "could not find python, which is required for the the textbook examples")
      endif()
    endif()

(So... very specific to the package being searched and the external that needed it. This was replaced with a new, generic function  — though, still only used for pythoninterp+textbook — to allow any external to require any dependency. Besides being more declarative, it consolidates the decision logic whether the external is enabled. )

 It is generally true of `find_package` that it may set either `SomePackage_FOUND` or `SOMEPACKAGE_FOUND`, depending on the package. (Packages found via a package configuration file always use same-case, but find modules might set either, or both.)

In fact, `FindPythonInterp.cmake` (and more generally, anything using `find_package_handle_standard_args`) does set both; if we don't mind *possibly* having to re-add the extra functionality at some future point, we could probably drop checking the upper-case var... (@bradking might have an opinion here...?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNcjhewdeN9G0qdlYWG:-1347343930) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
OK, thanks for the explanation.  I think adding some variation of this sentence as a comment would be useful for future readers:

> It is generally true of find_package that it may set either SomePackage_FOUND or SOMEPACKAGE_FOUND, depending on the package. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNckms96Ndcs0oYepoS:-1196802460) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK, thanks for the explanation.  I think adding some variation of this sentence as a comment would be useful for future readers:
> 
> > It is generally true of find_package that it may set either SomePackage_FOUND or SOMEPACKAGE_FOUND, depending on the package. 
</details>
Actually, unless there are objections, I'm leaning heavily toward just dropping the 7 lines supporting old find modules...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNclJQduzkc01T936zn:1006860896) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Actually, unless there are objections, I'm leaning heavily toward just dropping the 7 lines supporting old find modules...
</details>
You just lost me, not sure which lines you mean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNcmjkmAJ_H894rdW8L:-35022683) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> You just lost me, not sure which lines you mean.
</details>
       # Check external dependencies of project
       set(_ext_reqs_found TRUE)
       foreach(_ext_req IN LISTS _ext_REQUIRES)
    -    set(_ext_req_found ${_ext_req}_FOUND)
    -    string(TOUPPER ${_ext_req_found} _ext_req_found_upper)
         find_package(${_ext_req})
    -    if(DEFINED ${_ext_req_found} AND ${_ext_req_found})
    -      # Found requisite; same-case FOUND variable
    -    elseif(DEFINED ${_ext_req_found_upper} AND ${_ext_req_found_upper})
    -      # Found requisite; uppercase FOUND variable
    -    else()
    -      # Requisite not found
    +    if(NOT ${_ext_req}_FOUND)
           message(SEND_ERROR "Could not find ${_ext_req}, required for ${PROJECT}")
           set(_ext_reqs_found FALSE)
         endif()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNcnPpPOXKOmxRDHp9N:-173334676) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
>        # Check external dependencies of project
>        set(_ext_reqs_found TRUE)
>        foreach(_ext_req IN LISTS _ext_REQUIRES)
>     -    set(_ext_req_found ${_ext_req}_FOUND)
>     -    string(TOUPPER ${_ext_req_found} _ext_req_found_upper)
>          find_package(${_ext_req})
>     -    if(DEFINED ${_ext_req_found} AND ${_ext_req_found})
>     -      # Found requisite; same-case FOUND variable
>     -    elseif(DEFINED ${_ext_req_found_upper} AND ${_ext_req_found_upper})
>     -      # Found requisite; uppercase FOUND variable
>     -    else()
>     -      # Requisite not found
>     +    if(NOT ${_ext_req}_FOUND)
>            message(SEND_ERROR "Could not find ${_ext_req}, required for ${PROJECT}")
>            set(_ext_reqs_found FALSE)
>          endif()
> 
</details>
Oh, I see.  You're saying that `find_package` implementations which output `FOOBAR_FOUND` _and not_ `FooBar_FOUND` are following a legacy convention, but still exist in modern CMake.  Right now, we don't rely on any of those, but the PR as currently written is proof against them.

I agree that's fine to drop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 313 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNcYb3pJfo84EGhB7Qw:-KNgxBB4V1nsDUSoLCvE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/503771e5581e15d4449a0ac2287a996f2b22fa2a/cmake/externals.cmake#L313)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, I see.  You're saying that `find_package` implementations which output `FOOBAR_FOUND` _and not_ `FooBar_FOUND` are following a legacy convention, but still exist in modern CMake.  Right now, we don't rely on any of those, but the PR as currently written is proof against them.
> 
> I agree that's fine to drop.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Sorry, one more question.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhKtVwLoq8y7EaGcBM:1424470740) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
> ```CMake
> 
> add_custom_target(download-all)
> add_custom_target(clean-all)
> ```

It looks like this target wasn't carried over.  For all I know it's part of someone's workflow.  What's the modern alternative?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KNhLECBc5Y0ewqRsLKO:1731396547)*

**Comment by david-german-tri** [comment]
Also, could you please fix up the merge conflicts?

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhMHz2xXXpbgxaN4OJ:11325953) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> It looks like this target wasn't carried over.  For all I know it's part of someone's workflow.  What's the modern alternative?
</details>
This was intentionally removed. It's broken. See discussion in #2758.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhQVsw_42QuDAgiAXr:-149859522) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This was intentionally removed. It's broken. See discussion in #2758.
</details>
OK, thanks.  Anything else removed that I may have missed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhRP8EPjNd28N8X6BW:-1070230744) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK, thanks.  Anything else removed that I may have missed?
</details>
`REMOVE_UNUSED_EXTERNALS`... doesn't play nicely with git submodules, and (like the clean targets) doesn't clean up stuff from the `CMAKE_INSTALL_PREFIX`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhTk6PEpmEvpCqayb2:676834233) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> `REMOVE_UNUSED_EXTERNALS`... doesn't play nicely with git submodules, and (like the clean targets) doesn't clean up stuff from the `CMAKE_INSTALL_PREFIX`.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 443 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-KNhKtVv3PntM5TO0gFj:-KNhTsizbKPdqvoIdXBY:1194521331) ([raw file](https://github.com/robotlocomotion/drake/blob/ab557d554cbf7e6bfc381a71692703f123d77bce/CMakeLists.txt#L443)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> LGTM
</details>
Thanks... I just tweaked the commit message to mention these two items (no code changes).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Just waiting for @RussTedrake now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jhoare** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
friendly ping to @RussTedrake - this is blocked on your review.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KOBN3zxgDc7Qq09Wv1c:876847599)*

**Comment by david-german-tri** [comment]
I've got verbal confirmation from @russtedrake that this is OK to merge, but it looks like some tests broke in the most recent push.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KOGFmBJyYMMlnRKUkAC:-426483065)*

**Comment by mwoehlke-kitware** [comment]
> looks like some tests broke in the most recent push

The failing test is the drake-visualizer test, because it can't find `directorPython`. I don't see in the CI logs that director was ever *built*. Drake doesn't depend on director, either in this branch or on master... it's probably dumb luck it's working at all.

I'll add a dependency here... although I have this sneaking suspicion that director ought to depend on drake (which it currently doesn't; again, either in the branch or master), in which case we've managed to introduce a circular dependency.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by david-german-tri** [comment]
:lgtm: assuming those builds pass

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2896#-:-KOGzJMGzud6gi-Atcic:-1359317327)*

**Pull request merged**
