### PR TITLE
py mp: Allow upcasting to Binding<Constraint>

### LINKED ISSUE #15405: Binding_LinearConstraint cannot be cast as Binding_Constraint in pydrake
Reported in #15272 , for example, I have to add the overload of `RemoveCost` for each derived cost type in https://github.com/RobotLocomotion/drake/blob/3d71fac70bad294f93c9e5adb5b5ac155219b536/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1379-L1392, same for `RemoveConstraint`. If I don't have these overload, I receive the following error
```
TypeError: RemoveConstraint(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Constraint>) -> int

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0cd70b1030>; kwargs: constraint=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0cd420d130>
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #15405

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!
+@russtedrake for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408#-:-MegruSVEE6QPttK2mb6:b-7h3j2f)* status: LGTM missing from assignees hongkai-dai,RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408)* status: 1 unresolved discussion, LGTM missing from assignees hongkai-dai,RussTedrake(platform) (waiting on @EricCousineau-TRI, @hongkai-dai, and @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 315 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15408#-MehNcku5hTmaGQby-sV:-MehNcku5hTmaGQby-sW:bjfahq8) ([raw file](https://github.com/robotlocomotion/drake/blob/3a2fa06aa8f6bf60ebb30b1def3a0cd5d3ec2d75/bindings/pydrake/solvers/mathematicalprogram_py.cc#L315)):*
> ```cpp
> };
> 
> class StubEvaluatorBase : public EvaluatorBase {
> ```

Curious why this is in `mathematicalprogram_py.cc` instead of the test file

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408#-:-MeiyyUI0sro1eKt4Xi-:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 315 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15408#-MehNcku5hTmaGQby-sV:-MeysNbrCeQ_QU-oVhId:bu7sne2) ([raw file](https://github.com/robotlocomotion/drake/blob/3a2fa06aa8f6bf60ebb30b1def3a0cd5d3ec2d75/bindings/pydrake/solvers/mathematicalprogram_py.cc#L315)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why this is in `mathematicalprogram_py.cc` instead of the test file
</blockquote></details>

OK Solely for the purpose of ease-of-use; it's C++ file, so "the test file" doesn't make sense (Python).

I can split it out, but not sure if it's useful at this point. Can do in the future, if that's OK?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408)* status: LGTM missing from assignee hongkai-dai (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 315 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15408#-MehNcku5hTmaGQby-sV:-MezjCYi-h84icjQgUo8:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/3a2fa06aa8f6bf60ebb30b1def3a0cd5d3ec2d75/bindings/pydrake/solvers/mathematicalprogram_py.cc#L315)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Solely for the purpose of ease-of-use; it's C++ file, so "the test file" doesn't make sense (Python).

I can split it out, but not sure if it's useful at this point. Can do in the future, if that's OK?
</blockquote></details>

Got it, thanks!

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15408#-:-MezjFjSBZmQduQNWVw8:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,RussTedrake(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
