### PR TITLE
Bump VGT with raycasting performance improvements

### PR DESCRIPTION
**Pull request by calderpg-tri**
Bumps VGT with minor change to device point cloud voxelization API that allows the raycasting process to be restructured. Improved GPU raycasting implementations offer >= 2x performance (CPU implementation performance improves as well, but not as significantly).

+@ggould-tri for review, thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14919)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14919#-:-MYfTmdb2rR7CX71tUO7:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Comment by calderpg-tri** [comment]
+@SeanCurtis-TRI for platform review, thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14919#-:-MYfj7Dk0KJx3kRiCI7c:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
