### PR TITLE
Implements BlockSparseLinearOperator

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-MbmoliF0dpgLWJrM2rM:b-i95o8t)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a few nits. 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-MbmzTO7AyZRZp_y08wC:b-8ho5k2)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.h, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmtVAg7UGYBOhNRZk1:-MbmtVAg7UGYBOhNRZk2:bmfxqpn) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/block_sparse_linear_operator.h#L10)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/common/eigen_types.h"
> #include "drake/common/unused.h"
> ```

nit: this can be in the .cc file.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbmv7aL4TKHr7rXq5Nu:-Mbmv7aL4TKHr7rXq5Nv:bqlhh9r) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/block_sparse_linear_operator.cc#L75)):*
> ```cpp
>     }
>   }
>   A->resize(A_->rows(), A_->cols());
> ```

nit: Looks like this resize is not needed because the size of A is checked in the NVI.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbmwukr4nUqdR9I_wQe:-Mbmwukr4nUqdR9I_wQf:bfrws3q) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L10)):*
> ```cpp
> 
> #include "drake/common/test_utilities/eigen_matrix_compare.h"
> #define PRINT_VAR(a) std::cout << #a ": " << a << std::endl;
> ```

nit: left over debugging macro and `<iostream>` include.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyZnB8tsgumb4Wc8Z:-MbmyZnB8tsgumb4Wc8_:b-ww7p4o) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L97)):*
> ```cpp
>   Ablock_.Multiply(VectorXd(x), &y_expected);
>   EXPECT_EQ(VectorXd(y), y_expected);
>   EXPECT_TRUE(CompareMatrices(VectorXd(y), y_expected, kTolerance_));
> ```

nit: This comparison seems to be extraneous? Ditto below.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyrWn9ehTRc4EMTfm:-MbmyrWn9ehTRc4EMTfn:b-500jx5) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L114)):*
> ```cpp
>   Aop_->AssembleMatrix(&Asparse);
>   // Copy into a dense matrix for comparison.
>   const MatrixX<double> Acopy = Asparse;
> ```

BTW, should `Acopy` and `ASparse` be `A_copy` and `A_sparse` instead according to GSG?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbmv7aL4TKHr7rXq5Nu:-MbqYDGO2bcqNmgb-sLI:b74x666) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/block_sparse_linear_operator.cc#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: Looks like this resize is not needed because the size of A is checked in the NVI.
</blockquote></details>

in retrospect, I am not sure I like that check in the NVI. Maybe the right thing to do is to allow the resizing?
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyZnB8tsgumb4Wc8Z:-MbqYoYL1Y2FQtZavOMc:bq3gwy8) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L97)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: This comparison seems to be extraneous? Ditto below.
</blockquote></details>

yes. Leftover of my quick prototyping. Removed.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyrWn9ehTRc4EMTfm:-MbqZ1RH3JFrcBwOYgKK:b-j0v5ls) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L114)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, should `Acopy` and `ASparse` be `A_copy` and `A_sparse` instead according to GSG?
</blockquote></details>

those would not follow GSG either. A_sparse is not valid GSG. We typically allow a bit more flexibility for math symbols if they do make sense. Consider Aop above, should it be A_op?

**Review by amcastro-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-MbqZSgOD3UKPCL2-vtO:b-qxjhdt)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Most comments are nits.  The one big non-nit thing is the use of `mutable`; see below.

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-MbqimvbDRKr2WPRFQ7k:b-obaa60)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqaw-o171Lkvn84tmQ:-Mbqaw-o171Lkvn84tmR:b5nkxaq) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.h#L33)):*
> ```objc
>                             const BlockSparseMatrix<T>* A);
> 
>   ~BlockSparseLinearOperator() = default;
> ```

nit Missing either `override` or `final` per GSG.
___
*[multibody/contact_solvers/block_sparse_linear_operator.h, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqarKJAQK0CUDv8SbY:-MbqarKJAQK0CUDv8SbZ:b-dl9aic) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.h#L49)):*
> ```objc
>   void DoAssembleMatrix(Eigen::SparseMatrix<T>* A) const final;
> 
>  private:
> ```

nit Don't say `private:` twice.
___
*[multibody/contact_solvers/block_sparse_linear_operator.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqaPwc7ZYZRRRDvdPz:-MbqaPwc7ZYZRRRDvdQ-:b-5miq69) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.h#L50)):*
> ```objc
> 
>  private:
>   const BlockSparseMatrix<T>* A_{nullptr};
> ```

nit On first skim, it looks like the implementation never re-assigns `A_` once it's been set by the constructor.  To help assure the reader of that invariant, it would be an improvement here to add the second const:

```c++
const BlockSparseMatrix<T>* const A_;
```

Once it has that second const, you're allowed to drop the "nullptr" boilerplate.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqbcucDAPsIbbxOqS7:-MbqbcucDAPsIbbxOqS8:b-avcvp) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L33)):*
> ```cpp
>   // TODO(amcastro-tri): consider alternative to avoid copies from/to sparse
>   // vector.
>   col_vec_ = x;
> ```

From my limited understanding of the design here, my guess is that these linear operators will eventually be called by MbP as part of computing updates or outputs based on a Context.  Is that correct?

If so, note that we must support the use case where a single MbP object is able to be called from multiple threads, each with its own unique Context to compute into.

In that case, it seems like a single scratch field in the operator is not enough, because the operator will be owned by MbP (not by the Context) and so all of the threads would try to overwrite each other's scratch storage here.  Is that accurate?

If so, then at minimum we need a giant disclaimer in the documentation somewhere that this class is juggling chainsaws, and that we must fix that before it gets called by any non-internal code.

I wonder, though, since you're going to have to solve this problem anyway, perhaps it's worth exploring the solution sooner rather than later, in case you need to substantially redesign any of your class hierarchies in support of declaring temporary storage in the Context?
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqdYE0-GivZzaeaqU9:-MbqdYE0-GivZzaeaqUA:b-68gvzt) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L57)):*
> ```cpp
> template <typename T>
> void BlockSparseLinearOperator<T>::DoAssembleMatrix(
>     Eigen::SparseMatrix<T>* A) const {
> ```

nit Having the two matrices in play here be named `A` and A_` makes the implementation somewhat difficult to wade through.

Something like `output` or `A_output` would make it much more clear.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqckQw1rapLXLNg7Jx:-MbqckQxAZVwCS0zdGMA:b-gq521r) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L59)):*
> ```cpp
>     Eigen::SparseMatrix<T>* A) const {
>   // Count number of non-zeros.
>   int num_nnz = 0;
> ```

nit I don't understand what "nn" means here.  The "num" must be "number of" and "z" must be "zeros", and one of the "n" in "nn" must be "non-", but what is the other "n" for?

Writing out "num_nonzero" doesn't seem overly onerous, either.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqd4Gn1aRLG6qTE9aa:-Mbqd4Gn1aRLG6qTE9ab:bjxlbs7) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L62)):*
> ```cpp
>   for (const auto& [ib, jb, B] : A_->get_blocks()) {
>     unused(ib);
>     unused(jb);
> ```

nit If you like, you could do `unused(ib, jb);` on a single line.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyrWn9ehTRc4EMTfm:-Mbq_Bh52BWxmwGZmP3x:bx7c2hc) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L114)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

those would not follow GSG either. A_sparse is not valid GSG. We typically allow a bit more flexibility for math symbols if they do make sense. Consider Aop above, should it be A_op?
</blockquote></details>

I actually think our GSG is not very clear on this point.

The allowance for capitalized matrix names like `A` doesn't necessarily move us into CamelCase land.  I think a valid interpretation would be that we take a normal variable name like `a_foo` and want to be clearer about the matrix part, and so we could uppercase the `A` to say `A_foo`.  I don't think I would de jure defect a spelling like `A_foo` or `Afoo`, though possibly we should amend the rule to specify one or the other.

However, general _readability_ is always in scope, and as such I've noted a few complaints in other threads above.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqdtIr5fQ-kdR2qVtk:-MbqdtIr5fQ-kdR2qVtl:bp8t7si) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L17)):*
> ```cpp
> using SparseVectord = Eigen::SparseVector<double>;
> using Eigen::VectorXd;
> using Triplet = Eigen::Triplet<double>;
> ```

nit Unused `Triplet` alias.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqeETz4Qq7BWUKOHlN:-MbqeEU-CsdkutGvuqgy:b-kybsid) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L53)):*
> ```cpp
> 
>   const int kNumRows_{10};
>   const int kNumCols_{9};
> ```

nit See https://github.com/google/styleguide/issues/307

Don't use a trailing underscore on `kFoo` constants.  Either `const int num_rows_;` or `const int kNumRows;`.  Marking it static (as `kFoo`) is also fine.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqg6anEob0r_0AXPFH:-Mbqg6anEob0r_0AXPFI:b-j0e9ks) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L56)):*
> ```cpp
>   MatrixX<double> A_;
>   BlockSparseMatrix<double> Ablock_;
>   std::unique_ptr<BlockSparseLinearOperator<double>> Aop_;
> ```

nit I'll buy `A_` of course, and `Ablock_` is at least a plausible extension of that idea, with a new storage type.

But `Aop_` is a bridge too far on the readability front.  It's not some vanilla mathematical matrix, it's a class with a virtual interface and the actual device under test.

A name like like `operator_` or `dut_` would be suitably readable.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqi19wAIbBv5OqLURM:-Mbqi19wAIbBv5OqLURN:b-9itt8t) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L102)):*
> ```cpp
> 
> TEST_F(BlockSparseLinearOperatorTest, AssembleMatrix) {
>   SparseMatrixd Asparse(Aop_->rows(), Aop_->cols());
> ```

nit `Asparse` reads as `As parse` to me.  I think you need to make "sparse" its own word, ala `A_sparse`.  Or else choose a name that speaks more to semantics that storage, i.e., `actual` in the sense of "actual value" vs "expected value" in a test case.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqbcucDAPsIbbxOqS7:-MbqjI0x5TN01_1Ve4Sf:b-h2bhp4) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

From my limited understanding of the design here, my guess is that these linear operators will eventually be called by MbP as part of computing updates or outputs based on a Context.  Is that correct?

If so, note that we must support the use case where a single MbP object is able to be called from multiple threads, each with its own unique Context to compute into.

In that case, it seems like a single scratch field in the operator is not enough, because the operator will be owned by MbP (not by the Context) and so all of the threads would try to overwrite each other's scratch storage here.  Is that accurate?

If so, then at minimum we need a giant disclaimer in the documentation somewhere that this class is juggling chainsaws, and that we must fix that before it gets called by any non-internal code.

I wonder, though, since you're going to have to solve this problem anyway, perhaps it's worth exploring the solution sooner rather than later, in case you need to substantially redesign any of your class hierarchies in support of declaring temporary storage in the Context?
</blockquote></details>

Maybe a simpler path would be to remove the mutable members and use a new VextorXd here every time, with a TODO.  That would place correctness first over performance, deferring the optimization for some future PR.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbmv7aL4TKHr7rXq5Nu:-MbqrVfb4Wfp8p_v6sNs:b-c47ydn) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/block_sparse_linear_operator.cc#L75)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

in retrospect, I am not sure I like that check in the NVI. Maybe the right thing to do is to allow the resizing?
</blockquote></details>

Since `LinearOperator` provides `rows()` and `cols()`, the caller has the information to do the resize as well. I don't have a preference who actually does the resize.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbmyrWn9ehTRc4EMTfm:-MbqsL7D0haff0Ej9-Kj:bbra6ax) ([raw file](https://github.com/robotlocomotion/drake/blob/6882b55903153b651b4983d95b68da5f8660eb17/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I actually think our GSG is not very clear on this point.

The allowance for capitalized matrix names like `A` doesn't necessarily move us into CamelCase land.  I think a valid interpretation would be that we take a normal variable name like `a_foo` and want to be clearer about the matrix part, and so we could uppercase the `A` to say `A_foo`.  I don't think I would de jure defect a spelling like `A_foo` or `Afoo`, though possibly we should amend the rule to specify one or the other.

However, general _readability_ is always in scope, and as such I've noted a few complaints in other threads above.
</blockquote></details>

Good to know, thanks for the info.

**Review by amcastro-tri — COMMENTED** [review]
Sorry for the delay on this. I believe I addressed all comments, PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-Mf3cFVMDCNq8HuQhqgQ:botc9d7)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqaPwc7ZYZRRRDvdPz:-Mf3Yp5O48AU7o6F2DPO:b35kf80) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.h#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit On first skim, it looks like the implementation never re-assigns `A_` once it's been set by the constructor.  To help assure the reader of that invariant, it would be an improvement here to add the second const:

```c++
const BlockSparseMatrix<T>* const A_;
```

Once it has that second const, you're allowed to drop the "nullptr" boilerplate.
</blockquote></details>

I like that, thanks. I was thinking to convey that with a reference, but I dislike referencing external objects with just a reference that in local scope might be misleading. This is superior.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqbcucDAPsIbbxOqS7:-Mf3_B8SEVK7b9Ah60bR:bijkxjs) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe a simpler path would be to remove the mutable members and use a new VextorXd here every time, with a TODO.  That would place correctness first over performance, deferring the optimization for some future PR.
</blockquote></details>

Given this won't affect the performance of the newest solvers, I opted for the TODO for now and removed the mutable members.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-MbqckQw1rapLXLNg7Jx:-Mf3a3Kd7vXGc_GQlisF:b-tuan95) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't understand what "nn" means here.  The "num" must be "number of" and "z" must be "zeros", and one of the "n" in "nn" must be "non-", but what is the other "n" for?

Writing out "num_nonzero" doesn't seem overly onerous, either.
</blockquote></details>

very common to see nnz in sparse algebra libraries. I just mixed up my old habits of seeing nnz with new habits from GSG. Done.
___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqd4Gn1aRLG6qTE9aa:-Mf3aHzR8UA0tOQ0F8Pw:b-xlaxz6) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/block_sparse_linear_operator.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If you like, you could do `unused(ib, jb);` on a single line.
</blockquote></details>

I had no idea, thanks.
___
*[multibody/contact_solvers/test/block_sparse_linear_operator_test.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mbqg6anEob0r_0AXPFH:-Mf3bKy43bSKTWD8uzMK:b-k8504f) ([raw file](https://github.com/robotlocomotion/drake/blob/c9d42abe52b57e6aa1aa7159696f3259bc99254b/multibody/contact_solvers/test/block_sparse_linear_operator_test.cc#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'll buy `A_` of course, and `Ablock_` is at least a plausible extension of that idea, with a new storage type.

But `Aop_` is a bridge too far on the readability front.  It's not some vanilla mathematical matrix, it's a class with a virtual interface and the actual device under test.

A name like like `operator_` or `dut_` would be suitably readable.
</blockquote></details>

I settled somewhere in the middle.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164#-:-Mf3juy5DNRavdFsgyJn:b-vtj4vo)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 55 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mf3kJjb6CkPfzSqpCqD:-Mf3kJjc3Hn4AiRnDw5v:bknzlcy) ([raw file](https://github.com/robotlocomotion/drake/blob/a997d446de266eb6174143d3435defc4603c8f68/multibody/contact_solvers/block_sparse_linear_operator.cc#L55)):*
> ```cpp
> template <typename T>
> void BlockSparseLinearOperator<T>::DoAssembleMatrix(
>     Eigen::SparseMatrix<T>* Asparse) const {
> ```

nit `A_sparse` with underscore.

_... we still use underscores ("snake case") to delimit its words ..._
-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[multibody/contact_solvers/block_sparse_linear_operator.cc, line 55 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15164#-Mf3kJjb6CkPfzSqpCqD:-Mf3pOC57ZapHwFw1JcH:b-7m74ox) ([raw file](https://github.com/robotlocomotion/drake/blob/a997d446de266eb6174143d3435defc4603c8f68/multibody/contact_solvers/block_sparse_linear_operator.cc#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `A_sparse` with underscore.

_... we still use underscores ("snake case") to delimit its words ..._
-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

</blockquote></details>

nice!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15164)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri (waiting on @amcastro-tri)

**Pull request merged**
