### PR TITLE
Adds Optitrack LCM object streaming to the Kuka bi-manual box rotation simulation

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7326)

### CODE REVIEW

**Comment by rcory** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-:-KxEYLJOp3XrlOpd9Wmq:bll7v0f)*

**Comment by avalenzu** [comment]
:lgtm: with a couple BTWs.  +@soonho-tri  for platform review of change to comments in `optitrack_encoder.h` (the only non-`dev` file in this PR.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNui_7nWd_7I7x9Qm0:-KxNui_7nWd_7I7x9Qm1:b-gkemi7) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc#L195)):*
> ```cpp
>   // send three objects: left arm base, right arm base, and box.
>   auto optitrack_sender = builder.AddSystem<OptitrackLCMFrameSender>(3);
>   optitrack_sender->set_name("optitrack frame sender");
> ```

BTW, I don't think these `set_name()` calls are actually necessary. The systems should get an auto-generated name.

---

*[drake/systems/sensors/optitrack_encoder.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNvPAv8Ncr9pgRNpC-:-KxNvPAv8Ncr9pgRNpC0:bai3skz) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/systems/sensors/optitrack_encoder.h#L60)):*
> ```objc
>  * from the incoming PoseBundle object is used.
>  * For an example on how to use the OptitrackEncoder class see
>  * iiwa_box_simulation.cc
> ```

BTW: Two things:
 - I'm not sure if directing readers to a file in a `dev` directory violates our "non-dev files shall not depend on dev files" rule, but it might. I'll let @soonho-tri decide.
 - If we do keep this reference, should we give the full path from the Drake root?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-:-KxNvADv8rozEb0uPyg0:bmu582j)*

**Comment by soonho-tri** [comment]
:lgtm: (for non-dev part)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/optitrack_encoder.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNvPAv8Ncr9pgRNpC-:-KxO2l-rqNZ6Ewep7wV3:bwdaxse) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/systems/sensors/optitrack_encoder.h#L60)):*
> I'm not sure if directing readers to a file in a dev directory violates our "non-dev files shall not depend on dev files" rule, but it might. 

I think this is fine since we provide a file in `dev` directory as an example. Please correct me if it's the case non-dev code depends on dev code here.

> If we do keep this reference, should we give the full path from the Drake root?

While `doxygen` is smart enough to infer the location of this file, I think it's slightly better to write down the full-path so that a reader can locate the file more easily. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-:-KxO3dn0PmGhlGbLB-gR:b-oix6f9)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Comment by avalenzu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxO8Donq2L33f6C14Hu:-KxO8DooQzIaqLwPFasc:bkqlcsv) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc#L115)):*
> ```cpp
>       base_builder->ExportOutput(plant_->contact_results_output_port());
> 
>   output_port_kinematics_results_t_ =
> ```

BTW: There's no need for the `_t` here. Should just be `output_port_kinematics_results_`. For that matter, it should just be `output_port_contact_results_` as well. These aren't LCM message ports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Comment by avalenzu** [comment]
Added another BTW.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-:-KxO8qxm8dp6OAjSum46:b-a4z1bp)*

**Comment by avalenzu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Comment by rcory** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxO8Donq2L33f6C14Hu:-KxOa6VoX6DWdGTMRV0X:b-c6o6s3) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc#L115)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW: There's no need for the `_t` here. Should just be `output_port_kinematics_results_`. For that matter, it should just be `output_port_contact_results_` as well. These aren't LCM message ports.
</blockquote></details>

Done. BTW, I realized that `examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h` has the same `output_port_contact_results_t_` issue. Can you confirm? Perhaps we can just address that in a separate PR?

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNui_7nWd_7I7x9Qm0:-KxOkQZuVxregGSGmNJR:b-6ds63u) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc#L195)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, I don't think these `set_name()` calls are actually necessary. The systems should get an auto-generated name.
</blockquote></details>

Noted. Thanks. Btw, I wonder if set_name() would be more useful when we more heavily support graphviz for diagram visualization (where default system names may not be so pretty, apparently).

---

*[drake/systems/sensors/optitrack_encoder.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNvPAv8Ncr9pgRNpC-:-KxOmi1_iamdHpLBphyR:b-a3udqy) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/systems/sensors/optitrack_encoder.h#L60)):*
> I think this is fine since we provide a file in dev directory as an example. Please correct me if it's the case non-dev code depends on dev code here.

Good points. I just checked this link: http://drake.mit.edu/directory_structure.html#directory-structure-special-directories. I couldn't find anything related to "non-dev files depending on dev-files".  I agree that we should be enforcing some standards for `dev`. I don't believe these are documented anywhere?

I'm going to leave this change out for this PR, to avoid any pollution. I can always add it back in once we agree on the `dev` standards.

> If we do keep this reference, should we give the full path from the Drake root?

I thought about including the full path file, but was worried about forgetting to update this once the example moves out of `dev`. But again, I'm leaving this change out for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxNui_7nWd_7I7x9Qm0:-KxT2QvWB4KFE_We6Els:b-8goqr7) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc#L195)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Noted. Thanks. Btw, I wonder if set_name() would be more useful when we more heavily support graphviz for diagram visualization (where default system names may not be so pretty, apparently).
</blockquote></details>

True, these names would be much prettier in that context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Comment by avalenzu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7326#-KxO8Donq2L33f6C14Hu:-KxT2hPqVLLuXB6448tj:bu0g1b4) ([raw file](https://github.com/robotlocomotion/drake/blob/35a3ac91633bbec3457911abb9e1d94612815151/drake/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc#L115)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Done. BTW, I realized that `examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h` has the same `output_port_contact_results_t_` issue. Can you confirm? Perhaps we can just address that in a separate PR?
</blockquote></details>

I'm actually modifying that file right now in #7346. I've added a comment for myself over there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7326)*

**Pull request merged**
