### PR TITLE
Upgrade Externals December 2023

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #20594.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20630)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Something wonky is going on; when I had rules_python in the set, it *built* fine but failed ``//:py/install_test`, apparently due to rules_python. The latest run seems to be experiencing intermittent failures. I'm strongly tempted to just break this into individual PRs this time around...

**Comment by jwnimmer-tri** [comment]
My first impression of the errors is that `gz_utils` is broken.  I wonder if you cull that one out, if everything might work?  At least, that explains the debug + lsan failures

**Review by sherm1 — COMMENTED** [review]
I didn't double-check the commits and shas, just scanned for reasonable-looking changes and clean CI. On that basis, :lgtm: x 2. If that isn't a sufficient review, please LMK. I'll leave it to you to squash & merge.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20630#-:-Nl-GhXv9WqF1PPkc_3A:b-n7abjj)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
@sherm1, no squashing! Note the "commits are properly curated" label. Also, monthly upgrades should never be squashed.

**Pull request merged**
