### PR TITLE
Default to use non-git sources for SNOPT

### LINKED ISSUE #8801: Defer snopt download (or unpacking) errors to build-time, instead of load-time
The `library_lint.bzl` implementation uses `genquery()` rules, but when those rules touch upon `@snopt` they can fail to run, even though we don't need to clone snopt, since its not actually going to be compiled.  Ideally, we would defer errors in locating the snopt code to build time, instead of load time, so that we could enable that linter even when non in `-everything` mode.  We already do something similar with `@gurobi`.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This defers errors finding SNOPT to the building phase (not the loading phase) by default, so that we now `bazel query` will work by default.

Thus, here we also re-enable library_lint tests even in non-snopt configurations.

Closes #8801.  Relates #6464.  Relates #8031.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8825)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LCif8F_BwgWPlzdoaN7:-LCilxVIAtzg0-ywOnlD:b23vlvt) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@jamiesnape If you approve of this approach, please also then modify `drake-ci` to set `SNOPT_PATH=git` in the `-everything` builds.  (That would also pave the way for #7240 to set `SNOPT_PATH` to a zipfile in the future.)
</blockquote></details>

Ah, hm; that would have to be an coordinated merge, wouldn't it?  Perhaps I should propose a separate PR having _both_ `""` and `"git"` values mean to pull from git, and then the CI change (and user's local env settings) could happen next to allow for a transition period.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8825)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LCif7O91QdXuPr1urN6:-LDC9Xy-EbJoiutNMtJ8:b-qc1ip8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@jamiesnape Any votes on whether I should change `CMakeLists.txt` to retain the "git by default" behavior when `SNOPT_PATH` is unset, or else perhaps warn or error out in that case?  (I am happy to take a patch if that's easier to share than writing up some prose here, too.)  Because of the way Bazel works I can't really keep the from-source-bazel workflow the same, but we could keep the cmake-from-source workflow undisturbed.
</blockquote></details>

I guess the whole idea of pointing to an archive rather than searching for headers and libraries is a little alien to CMake, so not sure there is an amazingly good answer at this stage. I would probably add an `option`, so something like:
```cmake
if(WITH_SNOPT)
  option(WITH_ROBOTLOCOMOTION_SNOPT "Build with SNOPT from the RobotLocomotion/snopt private GitHub repository" OFF)
  if(WITH_ROBOTLOCOMOTION_SNOPT)
    list(APPEND BAZEL_ENV "SNOPT_PATH=git")
  else()
     set(SNOPT_PATH SNOPT_PATH-NOTFOUND CACHE FILEPATH "Path to SNOPT source archive")
     if(NOT EXISTS "${SNOPT_PATH}")
        message(FATAL_ERROR "SNOPT source archive was NOT found")
     endif()
     mark_as_advanced(SNOPT_PATH)
     list(APPEND BAZEL_ENV "SNOPT_PATH=${SNOPT_PATH}")
  endif()
endif()
```

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LCif8F_BwgWPlzdoaN7:-LDCD7cUBN5BRLKSZW6r:bkrgjn9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, hm; that would have to be an coordinated merge, wouldn't it?  Perhaps I should propose a separate PR having _both_ `""` and `"git"` values mean to pull from git, and then the CI change (and user's local env settings) could happen next to allow for a transition period.
</blockquote></details>

Yes, it would be easier to do a separate PR to allow for the transition.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8825#-:-LDCDMgk78m1KUDE4j64:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I've filed #8863 as a preparatory PR.

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LCif7O91QdXuPr1urN6:-LDqVqShBd7WpwYW4EQv:b1jmtcz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I pushed this into the PR, but I still have to test it locally.
</blockquote></details>

Done.

In local testing with the `ccmake` GUI, if I wanted to use RL snopt, I had to first enable WITH_SNOPT, then click through an error message, then enable WITH_ROBOTLOCOMOTION_SNOPT -- that seemed annoying, so I've elevated it to a top-level option, instead of being conditioned on WITH_SNOPT being first.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8825)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LCif7O91QdXuPr1urN6:-LDqzAWk1B41BmuNp05G:b-joe593) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

In local testing with the `ccmake` GUI, if I wanted to use RL snopt, I had to first enable WITH_SNOPT, then click through an error message, then enable WITH_ROBOTLOCOMOTION_SNOPT -- that seemed annoying, so I've elevated it to a top-level option, instead of being conditioned on WITH_SNOPT being first.
</blockquote></details>

FYI I guess that is fine. It is pretty common to see an "error" that exposes another option or variable as a fallback, but since we do not have any logic for automatically finding the SNOPT archive, I guess it could get annoying. The consequential question is what is the user expecting the behavior to be when both options are modified and is it unambiguous?

---

*[CMakeLists.txt, line 157 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8825#-LDr0z-m-hpyXaEAKwgX:-LDr0z-m-hpyXaEAKwgY:bw63maf) ([raw file](https://github.com/robotlocomotion/drake/blob/5f9c34da40c63567b712609f218990cfa2ce426e/CMakeLists.txt#L157)):*
> ```CMake
>   list(APPEND BAZEL_ARGS --config=snopt)
>   list(APPEND BAZEL_ENV "SNOPT_PATH=git")
> else()
> ```

BTW `elseif(WITH_SNOPT)`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8825)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Pull request merged**
