### PR TITLE
Rotation constraint tighten3

### PR DESCRIPTION
**Pull request by hongkai-dai**
We want to compute the convex hull of the region, as the intersection between the box and the surface of the sphere. Previously we only used on halfspace to push the point out. But if the intersection region has more than 3 vertices, we can get the convex hull by using more than one halfspace.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5639)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review. @gizatt might also be interested.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-KgH7Ne9wKiAiY4EN_94:bpfogz9)*

**Comment by RussTedrake** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHM8vAX4zzOM9w0xWS:-KgHM8vBthrofzZxF3pP:b-kt9yzp) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L209)):*
> ```cpp
>     // according to the Gurobi solver tolerance.
>     double position_error = 1E-5;
>     double orientation_error = 3E-5;
> ```

why did it have to go UP?  do you have any evidence that your tightening actually made things tighter?

---

*[drake/solvers/rotation_constraint.cc, line 427 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHLbN81DMng7yJUh9x:-KgHLbN92ZUgg8dFx38E:bl5tfdu) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/solvers/rotation_constraint.cc#L427)):*
> ```cpp
>   // multiple rotation matrices, all relaxed with the same number of binary
>   // variables per half axis, the result `n` and `d` are the same. Should
>   // consider th hard-code the result, in order to save the computation.
> ```

-> "consider hard-coding the result to avoid repeating the computation"

---

*[drake/solvers/rotation_constraint.cc, line 444 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHMfYlCdNIepVJDtcw:-KgHMfYmzgBbQk9pcbl4:b-1mtrdw) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/solvers/rotation_constraint.cc#L444)):*
> ```cpp
> /**
>  * For the intersection region between the surface of the unit sphere, and the
>  * interior of a box aligned with the axes, relax this nonconvex intersetion
> ```

"intersection"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 427 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHLbN81DMng7yJUh9x:-KgIcZpKgVD6qyZXslni:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/solvers/rotation_constraint.cc#L427)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

-> "consider hard-coding the result to avoid repeating the computation"
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 444 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHMfYlCdNIepVJDtcw:-KgIcewOmJdt6jG_M6LR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/solvers/rotation_constraint.cc#L444)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"intersection"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639)*

**Comment by hongkai-dai** [comment]
-(status: do not review) 

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test.cc, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgHM8vAX4zzOM9w0xWS:-KgW_Swmx4A4Y4i7WNYl:biexvry) ([raw file](https://github.com/robotlocomotion/drake/blob/ef24033de3c3b3683e9e715f26d591fc770e7a47/drake/multibody/dev/test/global_inverse_kinematics_test.cc#L209)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why did it have to go UP?  do you have any evidence that your tightening actually made things tighter?
</blockquote></details>

Yes, I just added a test in `rotation_constraint_test.cc` to show that there are points between the inner facets and the halfspace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-KgW_RnsY4RDAW74GV-n:ba0k9zt)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/rotation_constraint.cc, line 411 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgiMqh8Wn2giLQBozIB:-KgiMqh8Wn2giLQBozIC:brdhc2t) ([raw file](https://github.com/robotlocomotion/drake/blob/82f9607c7e0bcfbfc67b140e31a7a1bbc35ba5c6/drake/solvers/rotation_constraint.cc#L411)):*
> ```cpp
>       *n *= -1;
>     }
>     *d = n->dot(pts[0]);
> ```

BTW, bad indentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-KgiN7yKER5c0CgShW5-:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/rotation_constraint.cc, line 411 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgiMqh8Wn2giLQBozIB:-KgjoyyXf7k6hEo_tAku:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82f9607c7e0bcfbfc67b140e31a7a1bbc35ba5c6/drake/solvers/rotation_constraint.cc#L411)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, bad indentation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-Kgjozyv24p-sG7ssTpc:b-qxjhdt)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 414 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkCAKGWlc1pyulxu-X:-KgkCAKGWlc1pyulxu-Y:b-emdn7i) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L414)):*
> ```cpp
>   // Determine if the other vertices are on the plane nᵀ * x = d.
>   bool pts_on_plane = true;
>   for (int i = 3; i < static_cast<int>(pts.size()); ++i) {
> ```

FYI I don't know how many points you'd typically have, but you could consider `&& pts_on_plane` here to skip a few dot products when things are not coplanar.

---

*[drake/solvers/rotation_constraint.cc, line 421 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkAudUSdy10Z7y7COY:-KgkAudUSdy10Z7y7COZ:b-3bfiqq) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L421)):*
> ```cpp
>   if (pts_on_plane) {
>     return;
>   }
> ```

It is a little difficult for me to reason about the unit test coverage of the new non-optimization-based code for the solution here.  Are there good tests that are sure to (1) cover the outcomes offered by the new code that also (2) prove the early-exit is happening instead of calling the solver, while (3) not always short-circuiting so that the solver is also sometimes used?

Typically the way I would write early-exit code like this is to put the new code into a separate method, test it on its own (it's allowed to return "no answer", and should do so in a deterministic way), and then call that from here.  And then in the context of unit testing the original method, I would ask the _solver_ if it ever got invoked (e.g. statistics counters), and then check that _this method_ is taking the early-exit path exactly when we thought it would.

---

*[drake/solvers/rotation_constraint.cc, line 492 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkE-SLbALWdXee3j4m:-KgkE-SLbALWdXee3j4n:bf1usve) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L492)):*
> ```cpp
>           c *= -1;
>         }
>         double d = c.dot(pts[i]);
> ```

FYI This "compute the outward triangle using a cross-product and conditional negation" `{Vector3d, double}` seems duplicate between here and the new code above.  Should it be a helper function?

---

*[drake/solvers/rotation_constraint.cc, line 497 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkE79yFrVJ7HlaNIxM:-KgkE79yFrVJ7HlaNIxN:bvj46gg) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L497)):*
> ```cpp
>         bool is_valid_halfspace = true;
>         // Now check if the other vertices pts[l] satisfies cᵀ * pts[l] >= d.
>         for (int l = 0; l < static_cast<int>(pts.size()); ++l) {
> ```

FYI Ditto here; the for-loop could early exit once we hit false, if you thought it was worth it.

---

*[drake/solvers/rotation_constraint_internal.h, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-Kgk8REQedl7gt4Mn9RL:-Kgk8RERTyi7QqzpA6gZ:bmg9nzw) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint_internal.h#L20)):*
> ```objc
> void ComputeInnerFacetsForBoxSphereIntersection(
>     const std::vector<Eigen::Vector3d>& pts,
>     Eigen::Matrix<double, Eigen::Dynamic, 3>* A, Eigen::VectorXd* b);
> ```

FYI It might worth pointing out somewhere in this file that API documentation for these functions lives in `rotation_constraint.cc` where they are implemented.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkCUJQsg2lcaUubn5f:-KgkCUJQsg2lcaUubn5g:b4k14e5) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/test/rotation_constraint_test.cc#L202)):*
> ```cpp
> void CheckInnerFacets(const std::vector<Vector3d>& pts) {
>   // Compute the inner facets of the convex hull of pts. Make sure for each
>   // facet, there are  three points on the facet, and the facet points
> ```

BTW nit double whitespace `are  three`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 414 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkCAKGWlc1pyulxu-X:-KgpLiwH43v_Lb3I5AS5:b-h8lntc) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L414)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I don't know how many points you'd typically have, but you could consider `&& pts_on_plane` here to skip a few dot products when things are not coplanar.
</blockquote></details>

Done. Good catch. There are at most 6 points. In most cases there are 3 or 4 points.

---

*[drake/solvers/rotation_constraint.cc, line 421 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkAudUSdy10Z7y7COY:-KgphiSO5qyPjpIofGef:b-5y39yh) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L421)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is a little difficult for me to reason about the unit test coverage of the new non-optimization-based code for the solution here.  Are there good tests that are sure to (1) cover the outcomes offered by the new code that also (2) prove the early-exit is happening instead of calling the solver, while (3) not always short-circuiting so that the solver is also sometimes used?

Typically the way I would write early-exit code like this is to put the new code into a separate method, test it on its own (it's allowed to return "no answer", and should do so in a deterministic way), and then call that from here.  And then in the context of unit testing the original method, I would ask the _solver_ if it ever got invoked (e.g. statistics counters), and then check that _this method_ is taking the early-exit path exactly when we thought it would.
</blockquote></details>

Done. I added a separate helper function `AreAllVerticesCoPlanar`, and also a test `TestAreAllVerticesCoPlanar`, which shows there are early exit. Does that look OK?

---

*[drake/solvers/rotation_constraint.cc, line 492 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkE-SLbALWdXee3j4m:-KgpnMWdLk3F6r8wqmLx:b-4au2yh) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L492)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This "compute the outward triangle using a cross-product and conditional negation" `{Vector3d, double}` seems duplicate between here and the new code above.  Should it be a helper function?
</blockquote></details>

Done. I added a function `ComputeTriangleOutwardNormal`.

---

*[drake/solvers/rotation_constraint.cc, line 497 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkE79yFrVJ7HlaNIxM:-Kgpnd2zbgsPBdTpsAZK:b95ec7o) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L497)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Ditto here; the for-loop could early exit once we hit false, if you thought it was worth it.
</blockquote></details>

I think I did early exit here? As in https://github.com/hongkai-dai/drake/blob/rotation_constraint_tighten3/drake/solvers/rotation_constraint.cc#L501

---

*[drake/solvers/rotation_constraint_internal.h, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-Kgk8REQedl7gt4Mn9RL:-KgpoNcJ8ASxMT0TbpMt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint_internal.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It might worth pointing out somewhere in this file that API documentation for these functions lives in `rotation_constraint.cc` where they are implemented.
</blockquote></details>

Done.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkCUJQsg2lcaUubn5f:-KgpoToxODpVJK-rbv5s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/test/rotation_constraint_test.cc#L202)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit double whitespace `are  three`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/rotation_constraint.cc, line 497 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-KgkE79yFrVJ7HlaNIxM:-KgpqfsbmOGVIrJRicS_:bb18kfz) ([raw file](https://github.com/robotlocomotion/drake/blob/7c571a1ec76ef93404790a0ffe05daa84671b2ef/drake/solvers/rotation_constraint.cc#L497)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think I did early exit here? As in https://github.com/hongkai-dai/drake/blob/rotation_constraint_tighten3/drake/solvers/rotation_constraint.cc#L501
</blockquote></details>

Ah, there's a `break;`; thanks.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-KgprUF0dM_v8CLy5jpg:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5639#-:-Kgr2ce2CGVKvcjGIqOD:b-l70wzf)*

**Pull request merged**
