### PR TITLE
Fix CI failure by disabling a test

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18104)

### CODE REVIEW

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-continuous-release please

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews.  No need to wait for the macOS build, there is a 99.9% change this works and the consequences of it not working are low (we'll just need another tweak).  The post-merge macOS builds will report whether it worked.

**Comment by jwnimmer-tri** [comment]
The linters have passed, so I'll force-merge this now.

FYI to trigger a macos build you would have needed to say "experimental" not "continuous" (see https://drake.mit.edu/jenkins.html).

**Pull request merged**
