### PR TITLE
meshcat: add option to set contact cylinder radius

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14131)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14131#-:-MIH3_g05RCRMUS8b822:b-dpgjx8)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with a request

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14131#-:-MIJjmjkBNzdm8G3cLB7:b30ua3t)* status: 2 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 555 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14131#-MIJjjNy8YVdUPcZ5Spp:-MIJjjNy8YVdUPcZ5Spq:bfguny3) ([raw file](https://github.com/robotlocomotion/drake/blob/6b249a765273da1fb95647043e1c1129602319c4/bindings/pydrake/systems/meshcat_visualizer.py#L555)):*
> ```Python
>                  contact_force_scale=10,
>                  plant=None,
>                  radius=0.01):
> ```

Can you qualify the name as `contact_force_cylinder_radius`, to match `contact_force_scale`?
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 564 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14131#-MIJjYep58-d4Wx2p5IO:-MIJjYep58-d4Wx2p5IP:b-udpzs8) ([raw file](https://github.com/robotlocomotion/drake/blob/6b249a765273da1fb95647043e1c1129602319c4/bindings/pydrake/systems/meshcat_visualizer.py#L564)):*
> ```Python
>                 displayed as a cylinder with length F/contact_force_scale
>                 (in meters).
>             plant: the MultibodyPlant associated with meshcat_viz.scene_graph.
> ```

nit Can you document the radius here?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14131)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 555 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14131#-MIJjjNy8YVdUPcZ5Spp:-MIJoczJDm5V4B_aMyIc:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/6b249a765273da1fb95647043e1c1129602319c4/bindings/pydrake/systems/meshcat_visualizer.py#L555)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you qualify the name as `contact_force_cylinder_radius`, to match `contact_force_scale`?
</blockquote></details>

done.
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 564 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14131#-MIJjYep58-d4Wx2p5IO:-MIJodo85CzOhq1_WGdm:bl07yp2) ([raw file](https://github.com/robotlocomotion/drake/blob/6b249a765273da1fb95647043e1c1129602319c4/bindings/pydrake/systems/meshcat_visualizer.py#L564)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you document the radius here?
</blockquote></details>

oops.  done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14131)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
