### PR TITLE
[solvers] IpoptSolver can use SPRAL

### LINKED ISSUE #21476: Enable SPRAL(+METIS) option for IpoptSolver
**Is your feature request related to a problem? Please describe.**

Ipopt requires a linear solver under the hood.  See https://coin-or.github.io/Ipopt/index.html#PREREQUISITES for background.

Currently, Drake's build configures Ipopt to use MUMPS for this purpose.  However, the MUMPS build system is kind of a portability disaster (#20429), and its license (LGPL-like) means that we need to ship it as shared libraries in our wheel builds, which also increases brittleness.  In an ideal world, we would evict MUMPS from our build.

**Describe the solution you'd like**

Most of the alternative linear solvers for Ipopt are also unusable, with one exception: the [SPRAL](https://github.com/ralna/spral) package is suitably maintained and licensed, and its required dependency [METIS](http://glaros.dtc.umn.edu/gkhome/metis/metis/overview) is also available with a suitable license.

We should add the SPRAL solver to our build so that IpoptSolver can opt-in to it.  (It has a setting `linear_solver="mumps"` as a default; a user can opt-in to SPRAL by providing a different option.)

Once we have some experience with SPRAL, and assuming we like it, we should switch to it by default and deprecate the MUMPS option for removal, eventually removing MUMPS from our build entirely.

**Describe alternatives you've considered**

Drop support for Ipopt entirely.

**Additional context**

The end of a related discussion: https://github.com/RobotLocomotion/drake/issues/4913#issuecomment-1407787587.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #21476.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for (low priority) feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: cosmetic bits

> Reviewed 17 of 23 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-:-ODDSWkd016d1-3HWaLU:b-k9xsgo)* status: 6 unresolved discussions, needs at least two assigned reviewers

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDSFkP7-SirXic6rZ0:-ODDSFkP7-SirXic6rZ1:brbsagx) (no related file):*
minor is `fortran.bzl` generic enough that it should live somewhere other than `../snopt/` ?
___
*[`-- commits` line 18 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDL69809gwamwrNldq:-ODDL69809gwamwrNldr:br5pfw4):*
typo (respect)



_Suggestion:_
```
British
```
___
*[`tools/workspace/snopt/fortran.bzl` line 53 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDRJH6E-UNze6-gDUX:-ODDRJH6E-UNze6-gDUY:b-drmmok) ([raw file](https://github.com/RobotLocomotion/drake/blob/305d1dbf36778e7f2bd0cacfcdb0b5bdec7b2c27/tools/workspace/snopt/fortran.bzl#L53)):*
> ```Starlark
>         _output_mods = [],
>         **kwargs):
>     """Compiles a Fortran library. This library's symbols will have hidden
> ```

typo in existing code: 'becaused' ==> 'because'
___
*[`tools/workspace/snopt/fortran.bzl` line 112 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDRVsREE0tdR5jUQzA:-ODDRVsS3zIk-ckwXblU:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/305d1dbf36778e7f2bd0cacfcdb0b5bdec7b2c27/tools/workspace/snopt/fortran.bzl#L112)):*
> ```Starlark
>         deps = []):
>     """Compiles a Fortran 90 module. This library's symbols will have hidden
>     visibility, becaused Drake binary release artifacts should never provide
> ```

typo



_Suggestion:_
```Starlark
because
```
___
*[`tools/workspace/snopt/fortran.bzl` line 118 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDNYAP08XQrse8zpvM:-ODDNYAP08XQrse8zpvN:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/305d1dbf36778e7f2bd0cacfcdb0b5bdec7b2c27/tools/workspace/snopt/fortran.bzl#L118)):*
> ```Starlark
>     uses: List of module names that this module requires.
>     extra_provides: List of module names that this module provides; the `name`
>        module is always provided, this just extra modules beyond the main one.
> ```

typo



_Suggestion:_
```Starlark
this just adds extra modules
```
___
*[`tools/workspace/metis_internal/patches/typewidth.patch` line 6 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDQi20AnWaRIH7SFcH:-ODDQi20AnWaRIH7SFcI:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/305d1dbf36778e7f2bd0cacfcdb0b5bdec7b2c27/tools/workspace/metis_internal/patches/typewidth.patch#L6)):*
> ```Diff
> 
> Reasoning for not upstreaming this patch: upstream wants end users
> like us to purposefully edit this file as the canonicnal mechanism
> ```

typo



_Suggestion:_
```Diff
canonical
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review (on Thursday / Monday), please.  This is probably a bit more than we want to ask Sherm to wade through today.

> Reviewed 23 of 23 files at r1, 6 of 6 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-:-ODHIBKBDZpZuSp3vPyc:b1myuck)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODDSFkP7-SirXic6rZ0:-ODHHD3H3Ooh3ZSFfvxn:brds0gs) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor is `fortran.bzl` generic enough that it should live somewhere other than `../snopt/` ?
</blockquote></details>

I am satisfied with its current home.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. One testing comment and one build clarity comment.

> Reviewed 17 of 23 files at r1, 4 of 6 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-:-ODMZQ966D9SXW419SFR:bcm1ryh)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`solvers/ipopt_solver.h` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMUb9_17QHY6bCoLre:-ODMUb9_17QHY6bCoLrf:b-ijytqv) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/solvers/ipopt_solver.h#L65)):*
> ```objc
> 
>   /// Changes the default value for Ipopt's "linerar_solver" solver option. This
>   /// is the lowest precedence default -- setting the "linear_solver" option in
> ```

nit: It's not clear to me that this documented precedence is tested.

And, in fact, I'm not wholly persuaded perusing the code that it works as documented.

1. `default_linear_solver_` gets set in one of two places: constructor of `SetDefaultLinearSolver`.
2. `SetAppOptions()` is invoked one time, and it passes `default_linear_solver_` (along with the "specific options".
3. `SetAppOptions()` calls `app->Options()->SetStringValue()` with the passed linear solver using the default parameter value for `allow_clobber = true`.
4. The comment on `options->Respell()` says "options handled below will overwrite the above defaults." But "linear_solver" is not "handled below".

Taken together, that suggests to me that *this* value has the highest precedence. I could certainly be missing something, and a test could simply reveal my mistake.
___
*[`tools/workspace/spral_internal/package.BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMYZz45AJTkavA7DyW:-ODMYZz45AJTkavA7DyX:blc35fg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/tools/workspace/spral_internal/package.BUILD.bazel#L73)):*
> ```
> )
> 
> cc_library(
> ```

BTW Without digging, I'm a bit surprised to see `omp.*` being compiled with the compiler flag `-fno-openmp`. Is it just my ignorance, or is an explanatory note justified?

Perhaps a note on the definition of `_COPTS`? I assume it's because we want to reserve use of open mp at the Drake level and not have to worry about nested OpenMP. But then a note here would be nice.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`solvers/ipopt_solver.h` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMUb9_17QHY6bCoLre:-ODMbFRa5obTwM0Ps5ck:b-ji8467) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/solvers/ipopt_solver.h#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: It's not clear to me that this documented precedence is tested.

And, in fact, I'm not wholly persuaded perusing the code that it works as documented.

1. `default_linear_solver_` gets set in one of two places: constructor of `SetDefaultLinearSolver`.
2. `SetAppOptions()` is invoked one time, and it passes `default_linear_solver_` (along with the "specific options".
3. `SetAppOptions()` calls `app->Options()->SetStringValue()` with the passed linear solver using the default parameter value for `allow_clobber = true`.
4. The comment on `options->Respell()` says "options handled below will overwrite the above defaults." But "linear_solver" is not "handled below".

Taken together, that suggests to me that *this* value has the highest precedence. I could certainly be missing something, and a test could simply reveal my mistake.
</blockquote></details>

If we had a bug where the member field trumped the SolverOptions, then the test case `IpoptSolverTest.UnsupportedLinearSolver` would fail because no exception would be thrown.

The final line of SetAppOptions (`options->CopyToCallbacks(...)`) is where the user's specific SolverOptions are copied over into IPOPT, taking precedence over anything that had already been configuired.
___
*[`tools/workspace/spral_internal/package.BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMYZz45AJTkavA7DyW:-ODMage9EpgCg0-tgXAB:b-896fig) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/tools/workspace/spral_internal/package.BUILD.bazel#L73)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Without digging, I'm a bit surprised to see `omp.*` being compiled with the compiler flag `-fno-openmp`. Is it just my ignorance, or is an explanatory note justified?

Perhaps a note on the definition of `_COPTS`? I assume it's because we want to reserve use of open mp at the Drake level and not have to worry about nested OpenMP. But then a note here would be nice.
</blockquote></details>

Done?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`solvers/ipopt_solver.h` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMUb9_17QHY6bCoLre:-ODMhVfIAHWGhPAFCgD5:b-ei0t34) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/solvers/ipopt_solver.h#L65)):*
> test case `IpoptSolverTest.UnsupportedLinearSolver` would fail because no exception would be thrown.

Ah...a pre-existing test. I hadn't notice that. Thanks.

---------

Tangentially, perhaps the comment about "options handled below will overwrite" is misleading? Given some options are explicitly processed in the respell they seem to be what is referred to and *not* the invocation of `CopyToCallbacks()` outside of `Respell`. `CopyToCallbacks()` does not obviously implement the "overwrite precedence". The function `SetAppOptions()` clearly writes to the "linear_solver" property to the output parameter `app->Options()`. It also does things to the output parameter `options`. But it's impossible to discern that there's any entanglement between the two output parameters.

But that is outside the scope of this PR.
___
*[`tools/workspace/spral_internal/package.BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMYZz45AJTkavA7DyW:-ODMhnoMB6bHcQOgOfgH:babl8nz) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/tools/workspace/spral_internal/package.BUILD.bazel#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

re: `omp`.

Presumably, it's a dependency of what we're actually building and disabling openmp as a compiler options reduces this to something boring and nonfunctional. It's simpler to leave it in place (turned off) than to remove the illusory dependency via a patch?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/spral_internal/package.BUILD.bazel` line 73 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-ODMYZz45AJTkavA7DyW:-ODMrtZUDaYAJ8duYXYJ:bdo3oa3) ([raw file](https://github.com/RobotLocomotion/drake/blob/e3f3557985a7dcc6994d64c0619b51ea776fb6f6/tools/workspace/spral_internal/package.BUILD.bazel#L73)):*
> ... reduces this to something boring and nonfunctional.

Yes, basically.  Function in that the API for questions like "how many threads can I use" returns a hard-coded `1` instead of asking the runtime.

> It's simpler to leave it in place (turned off) than to remove the illusory dependency via a patch?

Yes, surely.  It's upstream's shim file to deal with OMP not being available on the runtime platform.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Ooops.  :LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22206#-:-ODMzeZh0pbgycUBOgXe:b-j6ty7n)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
