### PR TITLE
Simplify trajectory optimization code using symbolic operations

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5690)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@russtedrake , platform-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-:-KgbCMWQzwsNvY3mOJGL:bh6miqz)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-KgbCj4A4sCJXl1NHXTv:-KgbCj4A4sCJXl1NHXTw:b-oz9s2j) ([raw file](https://github.com/robotlocomotion/drake/blob/98a38fa1353556fefdf0f33c289432540d421b6c/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L50)):*
> ```cpp
>                       trajectory_time_lower_bound, trajectory_time_upper_bound);
>   for (int i = 0; i < N_ - 2; ++i) {
>     AddLinearEqualityConstraint(h_vars_(i + 1) - h_vars_(i), 0.0);
> ```

@hongkai-dai , do you think the new code is bad because we call `AddLinearEqualityConstraint` `N - 1` times? I think, at least, in terms of readability, it's better. But I wanted to know your opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-KgbCj4A4sCJXl1NHXTv:-KgbD6C3f0QMQC5AhtFj:b-gcm2j2) ([raw file](https://github.com/robotlocomotion/drake/blob/98a38fa1353556fefdf0f33c289432540d421b6c/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L50)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai , do you think the new code is bad because we call `AddLinearEqualityConstraint` `N - 1` times? I think, at least, in terms of readability, it's better. But I wanted to know your opinion.
</blockquote></details>

Well.. to be correct, it's `N - 2` times. We have another `AddLinearConstraint` above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690)*

**Comment by hongkai-dai** [comment]
This looks great! Thanks a lot! :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-KgbCj4A4sCJXl1NHXTv:-KgbEpVRFrP6nlikcs6v:b-wysbhd) ([raw file](https://github.com/robotlocomotion/drake/blob/98a38fa1353556fefdf0f33c289432540d421b6c/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L50)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Well.. to be correct, it's `N - 2` times. We have another `AddLinearConstraint` above.
</blockquote></details>

I think it is good. The readability of this code should be more important than the speed. And I do not think adding constraints for multiple times is a problem.

If we really do not want to add the constraint for multiple times, we can do
```C++
AddConstraint(h_vars_.head(N_-2) - h_vars_.tail(N_-2) == 0);
```
or 
```C++
AddConstraint(h_vars_.head(N_-2) - h_vars_.tail(N_-2) == Eigen::VectorXd::Zeros(N_-2));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-:-KgbFfzBMWjCABE9Cxr-:b-cvvs15)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-KgbCj4A4sCJXl1NHXTv:-KgbHUbv9U9Rwo-Th2xF:b-abi71m) ([raw file](https://github.com/robotlocomotion/drake/blob/98a38fa1353556fefdf0f33c289432540d421b6c/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L50)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is good. The readability of this code should be more important than the speed. And I do not think adding constraints for multiple times is a problem.

If we really do not want to add the constraint for multiple times, we can do
```C++
AddConstraint(h_vars_.head(N_-2) - h_vars_.tail(N_-2) == 0);
```
or 
```C++
AddConstraint(h_vars_.head(N_-2) - h_vars_.tail(N_-2) == Eigen::VectorXd::Zeros(N_-2));
```
</blockquote></details>

I see. I'll keep the code as it is. If it hits a performance problem, let's revisit it! Thanks for the comments!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5690#-:-Kgjtk_LqVqVRYS3RvEX:bnfp4nl)*

**Pull request merged**
