### PR TITLE
Revert "Fixes bug in rigid body velocity<->quaternion time derivative mapping"

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @edrumwri ,

The on-call build cop, @betsymcphail, believes that your PR #4965 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation include:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-continuous-matlab-documentation/813/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-continuous-matlab-debug/887/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4981)

### CODE REVIEW

**Comment by david-german-tri** [comment]
It looks to me like the test is asserting equality between the kinematic solution from C++ and the kinematic solution from MATLAB.  Given that the C++ solution was previously buggy and #4965 fixed it, let's not roll back #4965 until Evan has a chance to weigh in.  I strongly suspect the right course of action here is to fix forward by deleting the MATLAB test.

In the meantime, no one will be blocked in a serious way because this only runs post-merge, and the lack of coverage on kinematics is not too significant.  (Odds of another kinematics PR today: not high.)

**Comment by david-german-tri** [comment]
Definitely good to test the revert, though - please kick off a build that exercises the long-running test if you haven't already!

**Comment by BetsyMcPhail** [comment]
Sounds good @david-german-tri.

**Comment by edrumwri** [comment]
This is exactly the same problem code as before- how can we disable CI from
running this?


--------------------------------
Evan Drumwright
Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Comment by jwnimmer-tri** [comment]
To disable the test on Continuous CI, the line to comment out would be https://github.com/RobotLocomotion/drake/blob/acb5586100db1b0b8b4ca4190a6cbfa06f3b8430/drake/matlab/systems/plants/test/CMakeLists.txt#L95 -- or possibly some case within the `.m` file itself if only a portion of it is failing

**Comment by edrumwri** [comment]
Great- thought as much but wanted to make sure.

Thanks Jeremy!


--------------------------------
Evan Drumwright
Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Comment by BetsyMcPhail** [comment]
Fixed via #4986.

**Pull request closed without merging**
