### PR TITLE
Clean up Eigen-related code in symbolic classes

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4644)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@hongkai-dai , feature-review please.
@ggould-tri , platform-review please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-:-K_FQW5Kr6gQHkUtAUVz:b-t6vaxo)*

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@ggould-tri , platform-review please.

(sorry for the duplicate, I missed '+' previously)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-:-K_FTGMMtj4mgOfigOS7:bog0o6s)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.h, line 670 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-K_GRdVN-MhRud1Z0P4D:-K_GRdVO_aprjdP7DGlj:b-ohhuyp) ([raw file](https://github.com/robotlocomotion/drake/blob/31c66992827ce976e5b0127f93e92da1ba7cabc4/drake/common/symbolic_expression.h#L670)):*
> ```objc
> };
> 
> namespace internal {
> ```

Why do we remove this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.h, line 670 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-K_GRdVN-MhRud1Z0P4D:-K_GS5qJjNMsEuo9X92c:bnzrb8f) ([raw file](https://github.com/robotlocomotion/drake/blob/31c66992827ce976e5b0127f93e92da1ba7cabc4/drake/common/symbolic_expression.h#L670)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why do we remove this?
</blockquote></details>

I actually do not remember why I added it. This time, I've found that all tests pass without it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-:-K_GSnlvYDPj7eYzNyyT:bnfp4nl)*

**Comment by ggould-tri** [comment]
Nice!  Always good to see code go away :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4644#-:-K_UrNLPm_ioRhxe8IrX:bncxhqg)*

**Pull request merged**
