### PR TITLE
Simplify RenderEngineVtk tests

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
There are a *mountain* of tests which poke at narrow aspects of the render engine's rendering capability. It leads to a huge number of renderings being made.

This replaces the host with a couple of renderings by populating a scene with many elements, each of which contribute to a final image. By looking at the image, we can assess whether the rendering is correct. And by having the unit tests re-render and compare against that reference, we can cover a multitude of features with a single rendering.

This includes generating a new obj at build time: box_checkered.obj. It applies a checkered texture to the box by swapping material files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) 
+(release notes: none) 
+@zachfang for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-:-Nq2vRPVA2Yi0GcfwKFv:b-6eoaex)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-:-Nq3JP5pDtISi4XqUMJ7:b-zcjvte)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: feature!

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-:-Nq8Y1ClCX0Cthfcw0Jf:bs6n4ri)* status: 8 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq5j8FB3GLFwCxHQ1F0):*
nit. 



_Suggestion:_
```
Simplify
```
___
*[`geometry/render/test/meshes/checker.mtl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq5jacm4XOBXsVEITmr:-Nq5jacm4XOBXsVEITms:b-1sq3rn) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render/test/meshes/checker.mtl#L9)):*
> ```
> Ns 0.000000
> # N.B. The next line has trailing whitespace on purpose, to prove that Drake
> # ignores it during parsing.
> ```

BTW. Maybe the trailing whitespace is no longer true in this `.mtl` file? (At least from how GitHub renders the file.)



_Code quote:_
```
# N.B. The next line has trailing whitespace on purpose, to prove that Drake
# ignores it during parsing.
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8LBFj3bdwJWEKzd3R:-Nq8LBFkDS47TOx7MVdE:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2211)):*
> ```cpp
> 
>   x -= 0.15;
>   // This mesh has materials (box_checkered.obj or fully_texture_pyramid.gltf).
> ```

nit.



_Suggestion:_
```cpp
textured
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2262 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8Ld8j7nC1IPEj0Aah:-Nq8Ld8j7nC1IPEj0Aai:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2262)):*
> ```cpp
> }
> 
> // Compare the test image against a reference image.
> ```

nit.



_Suggestion:_
```cpp
Compares
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2274 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8WAXs2g1R0rV0pMVG:-Nq8WAXs2g1R0rV0pMVH:bf8q79) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2274)):*
> ```cpp
> //   2. label images: To view the 16-bit image in an 8-bit world, we use label
> //                    values that truncate nicely (see AddShapeRows()).
> //   3. depth images: To view the 32-bit depth image in an 8-bit world, we
> ```

nit. I think it's also worth documenting that depth images are always compared in the color space instead of the actual depth values in meters.



_Code quote:_
```cpp
To view the 32-bit depth image in an 8-bit world
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2287 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8VPaV8dVSzXb9bSlX:-Nq8VPaV8dVSzXb9bSlY:b-fbs7te) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2287)):*
> ```cpp
>   CompareType compare_image;
>   const std::filesystem::path ref_path = FindResourceOrThrow(ref_filename);
>   if (const char* dir = std::getenv("TEST_UNDECLARED_OUTPUTS_DIR")) {
> ```

I assume this needs to be `true` always, otherwise `compare_image` will be unassigned to any value, i.e., `test_image`?
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2326 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8UxqC6J7pzaObFOPD:-Nq8UxqD5tDfGL2HiOkZ:b3hs9b7) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2326)):*
> ```cpp
>   Eigen::Map<const VectorX<T>> data_expected(expected_image.at(0, 0),
>                                              expected_image.size());
>   Eigen::Map<const VectorX<T>> data2(compare_image.at(0, 0),
> ```

nit. Maybe `data_actual` for slightly better readability?



_Suggestion:_
```cpp
data_actual
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2370 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8Wyb8EOr3NaZ77dM5:-Nq8Wyb8EOr3NaZ77dM6:b-nqwhcx) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2370)):*
> ```cpp
>   const double last_x = AddShapeRows(&engine);
>   // Now make the rendering.
>   // The camera is above the Wz plane, looking in the -y direction (across the
> ```

BTW. Isn't the camera looking down and along the +y direction? (I was reconstructing the coordinate system from the ground truth images.)



_Code quote:_
```cpp
looking in the -y direction
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-:-NqTqkr5COx7OH7INsj2:b-ruv0ff)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2287 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-Nq8VPaV8dVSzXb9bSlX:-NqTpMi0ELnbGtgKtCzo:b-k6t0bm) ([raw file](https://github.com/RobotLocomotion/drake/blob/c2aad4863df0c4add56d12a0db389c5701f23cce/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2287)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I assume this needs to be `true` always, otherwise `compare_image` will be unassigned to any value, i.e., `test_image`?
</blockquote></details>

Big oops there. I put too much into the branch. I've now broken it up into separate concerns.  Thanks for catching that.

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

FYI I looked mostly at readability / clarity.  I didn't assess whether or not we lost functional test coverage -- relying on feature review for that.

> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-:-NqUXHtv4VT1GBqggQA-:bc6uhza)* status: 6 unresolved discussions

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUCfgU6U2SBO5D8_Rv:-NqUCfgU6U2SBO5D8_Rw:b-ru7n9c) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
> ```cpp
> 
>   unique_ptr<RenderEngineVtk> renderer_;
> };
> ```

BTW If you didn't already, please double-check this entire fixture for any newly-dead code?  For example, unused member fields, unused functions, etc.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2108 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUTuVY7QDEIA_wfENj:-NqUTuVY7QDEIA_wfENk:b-t3i1e6) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2108)):*
> ```cpp
> // The rows start at x = 0 and extend in the -x direction.
> // @returns the x-value for the shape farthest from the origin (along Wx).
> double AddShapeRows(RenderEngineVtk* render_engine, bool gltf_mesh = false) {
> ```

nit The effect of what `gltf_mesh` accomplishes is later enough in this function to be worth summarizing in the docs here, so a ready doesn't need to go hunt it down.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUUO2TD5n2n7gkvQH-:-NqUUO2TD5n2n7gkvQH0:benrway) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2135)):*
> ```cpp
>   };
> 
>   PerceptionProperties texture_material(minimum_material());
> ```

nit Here we have `minimum_material` and `diffuse_material` as functors, but `texture_material` is the actual properties, not a functor.  That's too confusing of a naming pattern.

Maybe `minimum_material` should be named `make_minimum_material` to help highlight its functor nature?  (Ditto for diffuse.)
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2314 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWArX8toVVw9WRkwB:-NqUWArX8toVVw9WRkwC:b-xcrojp) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2314)):*
> ```cpp
>   //   - `tolerance`: allowed per-channel deviation.
>   //   - conformity: the fraction of channel values that must deviate less than
>   //                 `tolerance`.
> ```

nit Inconsistent backticking for the two bullet definitions



_Suggestion:_
```cpp
  //   - tolerance: allowed per-channel deviation.
  //   - conformity: the fraction of channel values that must deviate less than
  //                 `tolerance`.
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWXqYDfiKGBS5UAZw:-NqUWXqYDfiKGBS5UAZx:b-nipjjd) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2327)):*
> ```cpp
>   Eigen::Map<const VectorX<T>> data_actual(compare_image.at(0, 0),
>                                            compare_image.size());
>   const auto differences = (data_expected.template cast<float>() -
> ```

nit With Eigen, either don't use `auto` or call `.eval()` at the end of the expression.  (The former is usually simplest; here I think we just have `VectorXd, right?)

https://eigen.tuxfamily.org/dox/TopicPitfalls.html
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2328 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWoxA3Bx_1Gd7j_Br:-NqUWoxA3Bx_1Gd7j_Bs:b313ek6) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2328)):*
> ```cpp
>                                            compare_image.size());
>   const auto differences = (data_expected.template cast<float>() -
>                             data_actual.template cast<float>())
> ```

nit Bad things will happen if the two Map `.size()`s are different.  The test should fail-fast with a better message before we start subtracting Eigen vectors with mismatched-sizes (UB).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUCfgU6U2SBO5D8_Rv:-NqUjt8O-A9fENxrO3eR:b-edl0aj) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you didn't already, please double-check this entire fixture for any newly-dead code?  For example, unused member fields, unused functions, etc.
</blockquote></details>

I'm quite confident that the core infrastructure is still used.  I'm not yet to the point where I get to cull it.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUUO2TD5n2n7gkvQH-:-NqUiGgV40S8BR020cPa:b-345znd) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Here we have `minimum_material` and `diffuse_material` as functors, but `texture_material` is the actual properties, not a functor.  That's too confusing of a naming pattern.

Maybe `minimum_material` should be named `make_minimum_material` to help highlight its functor nature?  (Ditto for diffuse.)
</blockquote></details>

Done

I actually decided to go the other way and make them all functors (that way every declaration gets a unique label).
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2314 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWArX8toVVw9WRkwB:-NqUfcJEDWn3p1wyEGW5:b-7dpm18) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2314)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Inconsistent backticking for the two bullet definitions
</blockquote></details>

Done

FTR It wasn't "inconsistent" per se. It was just using a different typographic system than you were expecting. The backticks on `tolerance` were intended as  callback to the fact that it's an input parameter. Whereas the idea of conformity, isn't. The distinction was intended to be meaningful. Now, whether the typography is *successful* is a different issue. For you, obviously, it isn't.

I've taken an alternate tack.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWXqYDfiKGBS5UAZw:-NqUhbr4Ea5FGmCbesfC:b-53nxpw) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2327)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit With Eigen, either don't use `auto` or call `.eval()` at the end of the expression.  (The former is usually simplest; here I think we just have `VectorXd, right?)

https://eigen.tuxfamily.org/dox/TopicPitfalls.html
</blockquote></details>

Done

I gotta say, I liked the `auto` version more. It handled the type conversion automatically.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2328 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWoxA3Bx_1Gd7j_Br:-NqUeuhR-qz5lBhhUdGr:bmy8tdk) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Bad things will happen if the two Map `.size()`s are different.  The test should fail-fast with a better message before we start subtracting Eigen vectors with mismatched-sizes (UB).
</blockquote></details>

Shouldnt' be a problem. Both images are of the same type `CompareImage` and I already assert that the images have the same size (six or seven lines up).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2314 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWArX8toVVw9WRkwB:-NqUkw8hDgZFENKnx3gt:b-f2j0uf) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2314)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

FTR It wasn't "inconsistent" per se. It was just using a different typographic system than you were expecting. The backticks on `tolerance` were intended as  callback to the fact that it's an input parameter. Whereas the idea of conformity, isn't. The distinction was intended to be meaningful. Now, whether the typography is *successful* is a different issue. For you, obviously, it isn't.

I've taken an alternate tack.
</blockquote></details>

Aha!  Thanks.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2328 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqUWoxA3Bx_1Gd7j_Br:-NqUl6NU5AA3HOdZXByF:b-frhq6d) ([raw file](https://github.com/RobotLocomotion/drake/blob/205606771367315e35209847b66061c560cfbfd7/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2328)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Shouldnt' be a problem. Both images are of the same type `CompareImage` and I already assert that the images have the same size (six or seven lines up).
</blockquote></details>

Ah yes, I overlooked the ASSERT_EQ by mistake.  That's all I wanted.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2335 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20701#-NqXrKcv9oHO7h3XBI8X:-NqXrKcv9oHO7h3XBI8Y:b-tw6qq7) ([raw file](https://github.com/RobotLocomotion/drake/blob/a899c5120de60a6d0832e9e6c625ee42f7e9a362/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2335)):*
> ```cpp
>   Eigen::Map<const VectorX<T>> data_actual(compare_image.at(0, 0),
>                                            compare_image.size());
>   const Eigen::ArrayX<double> differences =
> ```

BTW On Focal CI:

`**error:** '**ArrayX**' in namespace '**Eigen**' does not name a template type; did you mean '**ArrayXd**'?`



_Suggestion:_
```cpp
const Eigen::ArrayXd differences =
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

**Comment by jwnimmer-tri** [comment]
BTW CI wants a lint fix:

```
/usr/bin/clang-format-12 -style=file -i geometry/render_vtk/test/internal_render_engine_vtk_test.cc
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20701)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

**Pull request merged**
