### PR TITLE
Basic schunk dynamics simulation

### PR DESCRIPTION
**Pull request by ggould-tri**
An extremely basic sdf-based simulation of the Schunk gripper's dynamics.  Does not include any simulation of the Schunk's control system.

This also contains a number of small fixups related to the Schunk simulation, or to debugging needed for Schunk development.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3794)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@sammy-tri (feature; likely future owner of this code)
+@jwnimmer-tri (on-call platform)

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-:-KTyoYWPda6RebJxJO4E:b-nk6f53)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 7 of 13 files at r1.
Review status: 7 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/lcmtypes/lcmt_schunk_command.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywXr7s7XfBW8zJqmp:-KTywXr8tggXI7wjuRxB:bsnqoor) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/lcmtypes/lcmt_schunk_command.lcm#L5)):*
> ```
> struct lcmt_schunk_command
> {
>   int64_t timestamp;
> ```

Comment the units?  `// The timestamp in milliseconds.` is widely-used.

---

*[drake/lcmtypes/lcmt_schunk_status.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywbwfbXLmemSlzIzS:-KTywbwfbXLmemSlzIzT:bsnqoor) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/lcmtypes/lcmt_schunk_status.lcm#L5)):*
> ```
> struct lcmt_schunk_status
> {
>   int64_t timestamp;
> ```

Comment the units?  `// The timestamp in milliseconds.` is widely-used.

---

*[drake/systems/plants/parser_sdf.cc, line 570 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywwuMWvEb-x3Mv_48:-KTywwuMWvEb-x3Mv_49:b225mgq) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/systems/plants/parser_sdf.cc#L570)):*
> ```cpp
>     model->loops.push_back(l);
> 
>     drake::log()->info("Made joint {} a loop joint.", name);
> ```

IIRC `info` is emitted by default?  If so, please affirm that you want these (two) logs to appear for all users, for all time?

---

*[drake/systems/plants/RigidBody.h, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxBwx6GWY1IqAw5cd:-KTyxBwx6GWY1IqAw5ce:b-2i3uxg) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/systems/plants/RigidBody.h#L363)):*
> ```objc
> 
>  public:
>   DRAKE_EXPORT friend std::ostream& operator<<(
> ```

:headdesk:

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxQoq_eIAXW7oCPOl:-KTyxQoq_eIAXW7oCPOm:b-ve1wtx) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L25)):*
> ```cpp
> 
> template <typename T>
> RigidBodyPlant<T>::RigidBodyPlant(std::unique_ptr<const RigidBodyTree> tree) :
> ```

Colon goes on the next line:
https://google.github.io/styleguide/cppguide.html#Constructor_Initializer_Lists

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-:-KTyxYSixBVot9MqWlZo:by96gdd)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 13 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/schunk_gripper/CMakeLists.txt, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyz27wckuGmd0pkHil:-KTyz27wckuGmd0pkHim:bb7t2bl) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/CMakeLists.txt#L8)):*
> ```CMake
>     drakeRigidBodyPlant
>     drakeRBSystem
>     drakeLCMSystem)
> ```

Unclear why drakeSchunkGripper depends on drakeLCMSystem.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyNrr9jvbQNobIyUz:-KTyyNrr9jvbQNobIyV-:b-fgmlfe) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.cc#L12)):*
> ```cpp
> std::unique_ptr<drake::systems::RigidBodyPlant<T>>
> CreateSimulatedSchunkSystem() {
>   // Instantiates a Multibody Dynamics (MBD) model of the world.
> ```

I don't understand what this comment is getting at.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyXkxCjNW3LKUsJ7O:-KTyyXkxCjNW3LKUsJ7P:b-iebl8y) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.cc#L20)):*
> ```cpp
>       rigid_body_tree.get());
> 
>   std::unique_ptr<drake::systems::RigidBodyPlant<T>> ret =
> ```

BTW Consider `auto` here for brevity?  Or just omit the local entirely?

---

*[drake/examples/schunk_gripper/simulated_schunk_system.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyA_dI0gI1N51_bVL:-KTyyA_dI0gI1N51_bVM:b6i4p9a) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.h#L8)):*
> ```objc
> #include "drake/systems/framework/diagram.h"
> #include "drake/systems/framework/diagram_builder.h"
> #include "drake/systems/plants/parser_sdf.h"
> ```

Unused includes (all 4 lines above).

---

*[drake/examples/schunk_gripper/simulated_schunk_system.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyy1TSwk6UWm_-AlhP:-KTyy1TSwk6UWm_-AlhQ:b-o91tz8) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.h#L15)):*
> ```objc
> namespace schunk_gripper {
> 
> template<typename T>
> ```

Unclear what values of `T` are allowed.

---

*[drake/examples/schunk_gripper/models/schunk_gripper.sdf, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxvXMrCC3vhVko8GM:-KTyxvXN7y5_DLXrHZk7:bnsbvyw) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/models/schunk_gripper.sdf#L1)):*
> ```
> <?xml version='1.0'?>
> ```

BTW I didn't review this file.  Should I?

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyynFL0wk3v09ZzDjZ:-KTyynFMleig9PBHCmDh:bdqu0jo) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L5)):*
> ```cpp
> #include <map>
> #include <memory>
> #include <gtest/gtest.h>
> ```

Missing blank line between cstdlib and third-party includes.

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyt3PThufW9Pho092:-KTyyt3PThufW9Pho093:b1okbfg) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L9)):*
> ```cpp
> #include "drake/lcm/drake_lcm.h"
> #include "drake/systems/analysis/simulator.h"
> #include "drake/common/eigen_types.h"
> ```

Alpha-sort.

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyzIx-JedhdeCfk1lN:-KTyzIx0ONpG-2CNT9WI:bytat5n) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L28)):*
> ```cpp
>       builder.AddSystem<systems::RigidBodyPlant<double>>(
>           CreateSimulatedSchunkSystem<double>());
>   EXPECT_NE(schunk, nullptr);
> ```

BTW `ASSERT_NE` to avoid segfault on next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by sammy-tri** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/schunk_gripper/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTz1UIG-tFayUM3zPFK:-KTz1UIG-tFayUM3zPFL:b-6gt5tf) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/CMakeLists.txt#L7)):*
> ```CMake
>   target_link_libraries(drakeSchunkGripper
>     drakeRigidBodyPlant
>     drakeRBSystem
> ```

drakeRBSystem is the System1 code.  Are we using that?

---

*[drake/examples/schunk_gripper/models/schunk_gripper.sdf, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxvXMrCC3vhVko8GM:-KTz0mNe6ZWoYpmfm5jZ:bc8hw5r) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/models/schunk_gripper.sdf#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I didn't review this file.  Should I?
</details>
BTW I wasn't going to attempt it either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by ggould-tri** [comment]
Review status: 5 of 13 files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/schunk_gripper/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTz1UIG-tFayUM3zPFK:-KTzAKpdadQm3nefbj_F:b-vwxf87) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/CMakeLists.txt#L7)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> drakeRBSystem is the System1 code.  Are we using that?
</details>
Hangover from an older version of the code.  The first time I wrote this code it was still System1 :)

---

*[drake/examples/schunk_gripper/CMakeLists.txt, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyz27wckuGmd0pkHil:-KTzBKFcAbyxZQAlUWgx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unclear why drakeSchunkGripper depends on drakeLCMSystem.
</details>
Done.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyNrr9jvbQNobIyUz:-KTzBLTeKF4cFBGQ8w75:bq6878q) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't understand what this comment is getting at.
</details>
Copypasta is what it was getting at.  Have applied antipasto.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyXkxCjNW3LKUsJ7O:-KTzWMIhi393FURaZL5V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.cc#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider `auto` here for brevity?  Or just omit the local entirely?
</details>
Done.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyA_dI0gI1N51_bVL:-KTzX1fJu26SaeoPWjuX:b-qp12gs) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused includes (all 4 lines above).
</details>
Yup -- unused in this version of the code -- presumably they will be added back later when the control system is done.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyy1TSwk6UWm_-AlhP:-KTzXC1TCoIf3XITfxf3:bg9tohb) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/simulated_schunk_system.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unclear what values of `T` are allowed.
</details>
Documented.

---

*[drake/examples/schunk_gripper/models/schunk_gripper.sdf, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxvXMrCC3vhVko8GM:-KTz0fXj0200NgxeN8wa:b467hwb) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/models/schunk_gripper.sdf#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I didn't review this file.  Should I?
</details>
It is reasonable to not review it.  I can explain it in detail if you like.

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyynFL0wk3v09ZzDjZ:-KTzXZ4HzsS1I_2dvhPA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing blank line between cstdlib and third-party includes.
</details>
Done.

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyyt3PThufW9Pho092:-KTzXZPhajhms0TP-rhN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Alpha-sort.
</details>
Done.

---

*[drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyzIx-JedhdeCfk1lN:-KTzYrflf7KL7hmZ8aFh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/examples/schunk_gripper/test/simulated_schunk_system_test.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW `ASSERT_NE` to avoid segfault on next line.
</details>
Done.

---

*[drake/lcmtypes/lcmt_schunk_command.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywXr7s7XfBW8zJqmp:-KTzXk92ai1SoRJNECu6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/lcmtypes/lcmt_schunk_command.lcm#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Comment the units?  `// The timestamp in milliseconds.` is widely-used.
</details>
Done.

---

*[drake/lcmtypes/lcmt_schunk_status.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywbwfbXLmemSlzIzS:-KTzXkto4eNfvOomJodq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/lcmtypes/lcmt_schunk_status.lcm#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Comment the units?  `// The timestamp in milliseconds.` is widely-used.
</details>
Done.

---

*[drake/systems/plants/parser_sdf.cc, line 570 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTywwuMWvEb-x3Mv_48:-KTzY4HyAALkTOeqszVm:bx4xv2g) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/systems/plants/parser_sdf.cc#L570)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> IIRC `info` is emitted by default?  If so, please affirm that you want these (two) logs to appear for all users, for all time?
</details>
For all users, there is no way to write correct code for trees with loop joints without the information these emit (#3673).  But they can go away when that bug is fixed, so I am commenting that.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTyxQoq_eIAXW7oCPOl:-KTzYsj1F6y54xP45EHj:b38a00x) ([raw file](https://github.com/robotlocomotion/drake/blob/6713ad85c8b25384b8e2e7b033f9bcc5c5500c9c/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Colon goes on the next line:
> https://google.github.io/styleguide/cppguide.html#Constructor_Initializer_Lists
</details>
Done.  I think this was a mis-merge on my part at some distant past time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.h, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTzh4zrG0gjRmlUofvR:-KTzh4zrG0gjRmlUofvS:b-le5nv3) ([raw file](https://github.com/robotlocomotion/drake/blob/07496b7594440ebda7e66bebe59589c2f6f3542e/drake/examples/schunk_gripper/simulated_schunk_system.h#L16)):*
> ```objc
> CreateSimulatedSchunkSystem();
> 
> // At present this System is only tested and instantiated for T == `double`.
> ```

BTW We usually put this in the class doxygen, but I guess for an example it doesn't matter anyway?

---

*[drake/lcmtypes/lcmt_schunk_command.lcm, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTzhyjH5TRtxY9HHEwG:-KTzhyjH5TRtxY9HHEwH:b-edxpvc) ([raw file](https://github.com/robotlocomotion/drake/blob/07496b7594440ebda7e66bebe59589c2f6f3542e/drake/lcmtypes/lcmt_schunk_command.lcm#L5)):*
> ```
> struct lcmt_schunk_command
> {
>   int64_t timestamp;  //< The timestamp in microseconds.
> ```

Is it really in micros?  That would be unconventional.

And now that I look, are these message types even used by this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by sammy-tri** [comment]
:lgtm: pending remaining discussions + jenkins

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-:-KTziyWWtB0vGKX3pGAE:b8sv2cq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-:-KTzjD0YyBRkvGGBCE3P:bnfp4nl)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/lcmt_schunk_command.lcm, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTzhyjH5TRtxY9HHEwG:-KTzjGkKAZtQcFA-Padt:bqo0kt7) ([raw file](https://github.com/robotlocomotion/drake/blob/07496b7594440ebda7e66bebe59589c2f6f3542e/drake/lcmtypes/lcmt_schunk_command.lcm#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Is it really in micros?  That would be unconventional.
> 
> And now that I look, are these message types even used by this PR?
</details>
Those messages are not yet used; I moved them from the Schunk driver at the same time as I moved the SDF as a general "oh, those things all belong in drake" commit.

I can change this to millis in the driver if you can convince me that's the right choice, but I have serious misgivings about that.  Many existing OH control loops are circa 1kHz (Valkyrie, e.g.) and Atlas is known to be unstable at <300Hz control frequency and in practice operated near 1kHz.  If we are using millis elsewhere that seems very bad to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/lcmt_schunk_command.lcm, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3794#-KTzhyjH5TRtxY9HHEwG:-KTzlJnVbQh956ADzsIQ:b-8dwikj) ([raw file](https://github.com/robotlocomotion/drake/blob/07496b7594440ebda7e66bebe59589c2f6f3542e/drake/lcmtypes/lcmt_schunk_command.lcm#L5)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Those messages are not yet used; I moved them from the Schunk driver at the same time as I moved the SDF as a general "oh, those things all belong in drake" commit.
> 
> I can change this to millis in the driver if you can convince me that's the right choice, but I have serious misgivings about that.  Many existing OH control loops are circa 1kHz (Valkyrie, e.g.) and Atlas is known to be unstable at <300Hz control frequency and in practice operated near 1kHz.  If we are using millis elsewhere that seems very bad to me.
</details>
TTBOMK System1 only ever used millis for the message timestamp.  If you look at the `*.lcm` messages in this same directly, I think that is documented.

In any case, I guess I don't care, but perhaps consider `timestamp_us`, as the unit is not seconds.

Marking resolved, do as you see fit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3794)*

**Pull request merged**
