### PR TITLE
Add MeshcatVisualizer option to draw collision geometry

### PR DESCRIPTION
**Pull request by gizatt**
Adds a flag to MeshcatVisualizer to toggle between the geometry role type that is illustrated. (Hope I didn't miss some obvious existing way to do this!)

Setting it to "illustration" draws the usual visual geometry, and shouldn't change functionality at all. This is the default arg.
image

Setting it to "proximity" instead draws the collision geometry (i.e. proximity-role geometry), with random colors to make them easier to distinguish:
image

(Since a fair amount of my collision geometry is `Convex`-type, I also enabled drawing of that type using the `Mesh` codepath.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
@gizatt I love this change!  Easy collision visualization is one of our most frequent requests.

 If this commit is ready for review I can go ahead and find you a feature reviewer if you like; otherwise we can mark it as draft or do-not-review.  Let me know what you'd prefer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOl5AP48r7iWzCrMhSG:b1nwqeb)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by EricCousineau-TRI — COMMENTED** [review]
:cut_of_meat:-holder found - it's me! This looks good as-is, will assume it's ready for review.

+@ericcousineau-tri for feature

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOli2eM9u0fLdlW-jJ4:b-9go3ex)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by ggould-tri — COMMENTED** [review]
:+1:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOliwhG2OhkZMs3bUvp:bb6mt9b)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOljBR31QFkapIRje4J:b-v6scke)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @gizatt)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliFqN4hvj5HWo8TYW:-MOliFqN4hvj5HWo8TYX:b-4fce9j) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L144)):*
> ```Python
>                  axis_radius=0.006,
>                  delete_prefix_on_load=True,
>                  geometry_role_type="illustration",
> ```

Can you use the enum for this instead, `Role`?
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliHzf0jEtMoFUrCIY:-MOliHzf0jEtMoFUrCIZ:b-e8qvv) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L144)):*
> ```Python
>                  axis_radius=0.006,
>                  delete_prefix_on_load=True,
>                  geometry_role_type="illustration",
> ```

Other visualizers use the name `role`, e.g.:
https://drake.mit.edu/doxygen_cxx/structdrake_1_1geometry_1_1_drake_visualizer_params.html

Can you rename to `geometry_role` or just `role`?
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliTjEEyA71uuYGLww:-MOliTjEEyA71uuYGLwx:b-vfjspc) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L198)):*
> ```Python
>         self._delete_prefix_on_load = delete_prefix_on_load
>         if geometry_role_type == "illustration":
>             self.role_type = Role.kIllustration
> ```

Can you `self._role_type` (or whatever it will be named) a private member?
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 369 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliZ5eCkP_U8UPPRnG:-MOliZ5eCkP_U8UPPRnH:bedng94) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L369)):*
> ```Python
>                     # Pick a random color to make collision geometry
>                     # visually distinguishable.
>                     color = np.random.randint(2**(24))
> ```

Can you use a fixed-seed, local RNG?
https://numpy.org/doc/1.13/reference/generated/numpy.random.RandomState.html
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliiHe1TjMOirDAzoV:-MOliiHf5F0cZEwYkeQZ:bno19km) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L388)):*
> ```Python
>                     R_GC = RotationMatrix.MakeXRotation(np.pi/2.0).matrix()
>                     X_FG[0:3, 0:3] = X_FG[0:3, 0:3].dot(R_GC)
>                 elif isinstance(shape, Mesh) or isinstance(shape, Convex):
> ```

nit You can make this more brief:
```
elif isinstance(shape, (Mesh, Convex)):
   ...
```

FTR https://docs.python.org/3.6/library/functions.html#isinstance

**Review by gizatt — COMMENTED** [review]
Thanks both of you! :)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOmz0pj0s9iWbR3uZvb:bsjpmgh)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliFqN4hvj5HWo8TYW:-MOmuXSwBFu8kIY-I3h7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L144)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you use the enum for this instead, `Role`?
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliHzf0jEtMoFUrCIY:-MOmuZ9SD0dvYcPpvdCh:bn542rz) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L144)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Other visualizers use the name `role`, e.g.:
https://drake.mit.edu/doxygen_cxx/structdrake_1_1geometry_1_1_drake_visualizer_params.html

Can you rename to `geometry_role` or just `role`?
</blockquote></details>

Nice, wasn't sure what the standard was. Done!
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliTjEEyA71uuYGLww:-MOmufHyEW1WDDCKXEXV:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L198)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you `self._role_type` (or whatever it will be named) a private member?
</blockquote></details>

Done
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 369 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliZ5eCkP_U8UPPRnG:-MOmw842-2WX4GTyhEj8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L369)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you use a fixed-seed, local RNG?
https://numpy.org/doc/1.13/reference/generated/numpy.random.RandomState.html
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOliiHe1TjMOirDAzoV:-MOmw2qo3nro93TOJR8l:b-e5z2gp) ([raw file](https://github.com/robotlocomotion/drake/blob/96164eaa46fae0befc14708d2d9ae6cabba13e68/bindings/pydrake/systems/meshcat_visualizer.py#L388)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit You can make this more brief:
```
elif isinstance(shape, (Mesh, Convex)):
   ...
```

FTR https://docs.python.org/3.6/library/functions.html#isinstance

</blockquote></details>

Didn't know that, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: - you're welcome, and thank you!
Just one remaining nit

I'm also fine with serving as a platform reviewer too, +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467#-:-MOn9NyQ62WaFffwVDz2:b-p046tn)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @gizatt)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 184 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOnAQYQ9Z0EkmZsvN5I:-MOnAQYQ9Z0EkmZsvN5J:b-o4ecyo) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4bdfb6d81c00aff71393053e4bb65fb2e0c5e2/bindings/pydrake/systems/meshcat_visualizer.py#L184)):*
> ```Python
>                 may call ``delete_prefix()`` manually to clear the scene.
>             role: Renders geometry of the specified pydrake.geometry.Role
>             type -- defaults to Role.kIllustration to draw visual geometry,
> ```

nit This breaks with above documented arguments, which use a hanging indent for line continuation.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 184 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOnAQYQ9Z0EkmZsvN5I:-MOnBB9g5FQ8gmgB_Bys:b-2yjj98) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4bdfb6d81c00aff71393053e4bb65fb2e0c5e2/bindings/pydrake/systems/meshcat_visualizer.py#L184)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This breaks with above documented arguments, which use a hanging indent for line continuation.
</blockquote></details>

meant: This breaks *convention* with above [...]

**Review by gizatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 184 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOnAQYQ9Z0EkmZsvN5I:-MOnCA4o69e2jC8XH8-p:bepcxva) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4bdfb6d81c00aff71393053e4bb65fb2e0c5e2/bindings/pydrake/systems/meshcat_visualizer.py#L184)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

meant: This breaks *convention* with above [...]
</blockquote></details>

Woops, fixed!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 184 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14467#-MOnAQYQ9Z0EkmZsvN5I:-MOnCXMwBbAucApb5a6-:b-zfh9kw) ([raw file](https://github.com/robotlocomotion/drake/blob/4c4bdfb6d81c00aff71393053e4bb65fb2e0c5e2/bindings/pydrake/systems/meshcat_visualizer.py#L184)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

Woops, fixed!
</blockquote></details>

OK Awesome, thanks!

**Comment by EricCousineau-TRI** [comment]
Skipping slower builds (given that they had passed in prior revisions)

**Pull request merged**
