### PR TITLE
systems/lcm: Add LcmInterfaceSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #10895.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10935)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri Now that this is code instead of chatter, curious to get your early thoughts on this design / approach.

**Comment by jwnimmer-tri** [comment]
I've posted the full WIP to #10981 (and some of it leaked into here).  This will probably end up as the second(?) PR in the train.  First will be to make `//lcm` APIs better, second to teach `//systems/lcm` about it.  Stay tuned, but "do not review" for now.

**Comment by jwnimmer-tri** [comment]
I've updated this PR to have (as its second commit) what I intend to submit for review here.  The first commit is PR #11041 and will disappear here once that's merged.

**Comment by jwnimmer-tri** [comment]
@sammy-tri this is (finally!) ready for feature review now.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
___
*[lcm/lcm_receive_thread.h, line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/10935#-LbPWF-BAH-dfTxdE1ws:-LbP_lvM0FjMnSxiGYKz:b-hdpmyg) ([raw file](https://github.com/robotlocomotion/drake/blob/b9a0a719fe941d5909de23ce674f4682f579a70e/lcm/lcm_receive_thread.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this clarify that `LcmInterfaceSystem` should always be preferred when plugging LCM into the systems framework?
</blockquote></details>

Could you explain more?  Do you mean that "LcmInterfaceSystem should preferred over HandleSubscriptions" or "LcmInterfaceSystem should be preferred over [something else]"?  If the former, I'm not sure there is any way for a user to go wrong -- they would have to go out of their way to use HandleSubscriptions, in which case maybe they are doing it for a good reason anyway.

**Comment by EricCousineau-TRI** [comment]
Er... I'm super sorry for this way back when, but when posting #11403, I was reviewing this interface, and realized that this uses multiple inheritance... Can I ask why inheritance was used, rather than composition?
From a bystander's view, it looks as though it just forwards the relevant implementations, and thus could have been satisfied with composition?

**Comment by jwnimmer-tri** [comment]
Current way (1):
```c++
auto lcm = builder->AddSystem<LcmInterfaceSystem>();
auto subscriber1 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan1, lcm));
auto subscriber2 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan2, lcm));
```

Without public interface inheritance (2a):
```c++
auto lcm = builder->AddSystem<LcmInterfaceSystem>();
auto subscriber1 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan1, lcm->get()));
auto subscriber2 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan2, lcm->get()));
```
or else (2b)
```c++
auto lcm_system = builder->AddSystem<LcmInterfaceSystem>();
auto lcm = lcm_system->get();
auto subscriber1 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan1, lcm));
auto subscriber2 = builder->AddSystem(LcmSubscriberSystem::Make<lcmt_foo>(chan2, lcm)));
```

I found the former easier to read and reason about.  Most users only use the default or `string` constructor to LcmInterfaceSystem, so would not otherwise have an interface pointer.  By having the interface inheritance, the object returned by AddSystem can be directly passed to API users that need that pointer, without wrapping it with `get()` or similar every single time.

**Comment by EricCousineau-TRI** [comment]
Aye, makes sense for a usage P.O.V.
However, if/when there's desire for this in the Python API, I fear that the story gets a bit muddled.
`pybind11` is finicky about multiple-inheritance, and my mods on top of that make it even more finicky. (Sorry for not catching and discussing this earlier...)

**Pull request merged**
