### PR TITLE
Rename StateVectorInterface to StateVector, and implement StateVector::operator+=.

### PR DESCRIPTION
**Pull request by david-german-tri**
There is a default implementation in StateVector, and a higher-performance implementation in BasicStateVector (which has contiguous state).

+@sherm1 for feature and platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2552)

### CODE REVIEW

**Comment by david-german-tri** [comment]
New and weird flake on gcc,linux:

```
12:21:18 /home/ubuntu/workspace/experimental/7a2abcb0/build/lib/liblcmtypes_bot2-core.a: file not recognized: File format not recognized
```

https://drake-jenkins.csail.mit.edu/job/experimental/2043/compiler=gcc,label=linux/consoleFull
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=34085

@jamiesnape FYI

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by sherm1** [comment]
Feature & platform review: Sweet! See -- premature optimization can be fun :sunglasses: ! 
Just a few minor comments. 

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> jenkins: retest this please
</details>


---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/state_vector.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAxHrPm3uhji_3m2Gq:-KKAxHrQBIaOKHJIguss:455795017) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L31)):*
> ```objc
>   /// Implementations should ensure this operation is O(1) and allocates no
>   /// memory.
>   virtual const T GetAtIndex(ptrdiff_t index) const = 0;
> ```

This should be a `const T&` because some scalar types (like a many-variable AutoDiffScalar) are expensive to copy and this will be called in a tight loop.

---

*[drake/systems/framework/state_vector.h, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAy8F8ZKCJWsMuratH:-KKAy8F8ZKCJWsMuratI:-1670541904) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L60)):*
> ```objc
>   /// the value and allocates no memory.
>   virtual void AddToVector(Eigen::Ref<VectorX<T>> vec) const {
>     assert(vec.rows() == size());
> ```

Is size mismatch our programming error, or some user's logic error? I'm thinking the latter. (Same comment for other asserts here.)

---

*[drake/systems/framework/state_vector.h, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAxoHgCo6DI_tNsxol:-KKAxoHgCo6DI_tNsxom:-1844502815) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L66)):*
> ```objc
>   }
> 
>   /// Adds the vector @rhs to this vector. Both vectors must be the same size.
> ```

I believe you meant `@p rhs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-:-KKAzNoc3gOGoEi29L9p:806651657)*

**Comment by sherm1** [comment]
P.S. There is a `std::length_error` that is a kind of `std::logic_error`. It could be a good exception to throw in cases of size mismatch (I'm not certain that was the original intent but it seems underused.) I'm not sure whether that's an improvement over just throwing the base class, but I offer it for your consideration.

**Comment by david-german-tri** [comment]
The way I read it `length_error` has more to do with exceeding numerical limits (e.g. max_size) than simple size mismatches.  I've used `out_of_range` instead.

---

Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/state_vector.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAxHrPm3uhji_3m2Gq:-KKGUslVdadJPEQmbSz6:689954218) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This should be a `const T&` because some scalar types (like a many-variable AutoDiffScalar) are expensive to copy and this will be called in a tight loop.
</details>
I agree, and there's gotta be a way to make it work, but it's (surprisingly) nontrivial.  I'd like to defer it to a follow-up PR.

---

*[drake/systems/framework/state_vector.h, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAy8F8ZKCJWsMuratH:-KKGXc1SChvQPxFVr81N:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Is size mismatch our programming error, or some user's logic error? I'm thinking the latter. (Same comment for other asserts here.)
</details>
Done.

---

*[drake/systems/framework/state_vector.h, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAxoHgCo6DI_tNsxol:-KKGV-5mO4WnEkPQ6kKI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L66)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I believe you meant `@p rhs`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-:-KKGVQ6hGsnE5OKST27Z:-1744053820)*

**Comment by sherm1** [comment]
Linux debug build failed -- looks like a debug-only assertion rather than a flake:
```
21:41:58 17: basic_state_vector_test: /home/ubuntu/workspace/experimental/2e937e5a/build/include/eigen3/Eigen/src/Core/
CommaInitializer.h:114: Eigen::CommaInitializer<Eigen::Matrix<int, 3, 1, 0, 3, 1> >::~CommaInitializer() 
[MatrixType = Eigen::Matrix<int, 3, 1, 0, 3, 1>]: 
Assertion `(m_row+m_currentBlockRows) == m_xpr.rows() 
                 && m_col == m_xpr.cols() && 
               "Too few coefficients passed to comma initializer (operator<<)"' failed.
```

**Comment by sherm1** [comment]
Oh, I found the problem -- see comments.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/state_vector.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKAxHrPm3uhji_3m2Gq:-KKH1bOo45lTgOI1wz2n:160383661) ([raw file](https://github.com/robotlocomotion/drake/blob/55692f86eb40f855eb421bb3ab67c78e8801881e/drake/systems/framework/state_vector.h#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I agree, and there's gotta be a way to make it work, but it's (surprisingly) nontrivial.  I'd like to defer it to a follow-up PR.
</details>
OK.

---

*[drake/systems/framework/test/basic_state_vector_test.cc, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-KKH1wp1UwBfCxetZ3sO:-KKH1wp1UwBfCxetZ3sP:2042527395) ([raw file](https://github.com/robotlocomotion/drake/blob/e5ac2679f37f0f9309991d71d7aad69aa1fe8f9a/drake/systems/framework/test/basic_state_vector_test.cc#L102)):*
> ```cpp
> TEST_F(BasicStateVectorTest, AddToVectorInvalidSize) {
>   Eigen::Vector3i target;
>   target << 3, 5;
> ```

This throws an Eigen assertion because it is a fixed-size 3-vector that only got 2 values. You could use a Vector2i or VectorXi with only 2 elements here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-:-KKH2QqBKQlskgVviGXc:-1207078748)*

**Comment by sherm1** [comment]
:lgtm: Per discussion this needs some refinement for subvectors, and also because we need a scaled += for integrators. That's a topic for a different PR though.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2552#-:-KKJxREqM5Z0HQI3ESdr:-380797346)*

**Pull request merged**
