### PR TITLE
Add filtering to iiwa14_spheres_collision.urdf.

### PR DESCRIPTION
**Pull request by avalenzu**
Also fixes a broken origin tag.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8410)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@rcory for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8410#-:-L84GGeG8nGTdyJ_ZN4e:b-8i5c0w)*

**Comment by avalenzu** [comment]
The fact that nothing complained about the broken XML tag is a bit scary.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8410#-:-L84Hd1wVku9S_4ixl44:bt0qdgy)*

**Comment by avalenzu** [comment]
-@rcory  +@siyuanfeng-tri  for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8410#-:-L87z3idaIWaD5wRVdb5:b-w6onc2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8410#-:-L880SXeq3lHOJJGdong:bnfp4nl)*

**Comment by avalenzu** [comment]
+@ericcousineau-tri for platform review, because I ran into him in the kitchen.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8410#-:-L8839wjXDYLztPVYtVj:barg2kb)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8410#-:-L8858IYCPdM26WBUOB2:bnfp4nl)*

**Pull request merged**
