### PR TITLE
lint: Add cpp_docstring_lint

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I would like to not care anything about docstring whitespace styles, and I remember there being a chat about using a consistent format.

Towards #13491

Requires:
- [ ] https://github.com/RobotLocomotion/styleguide/pull/30

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13461)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Style change should begin their review with a PR to the styleguide with all of platform team approving the new policy, not an implementation.

**Comment by jwnimmer-tri** [comment]
> I remember there being a chat about using a consistent format.

My styleguide WIP for comment formatting is here:
https://github.com/jwnimmer-tri/styleguide/commits/comment-formatting

**Comment by EricCousineau-TRI** [comment]
Sounds good to me! Will try to get to `styleguide` PR in ~2 weeks.
Thanks!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Punting another 2 weeks down the road. Will wait til Q2 wind-down + Q3 wind-up settles.

**Comment by EricCousineau-TRI** [comment]
Saw this for `dm_control`; using `pyparsing`: https://github.com/pyparsing/pyparsing
https://github.com/deepmind/dm_control/blob/7ec5a46d0152bcd024cb87eeb6052cc8bc77df7b/dm_control/autowrap/header_parsing.py

**Comment by jwnimmer-tri** [comment]
This PR doesn't seem like it needs CI, even though there is a little recent discussion newer than 6 months here.  Can we close this for now?

**Comment by EricCousineau-TRI** [comment]
Sorry, and yup!

**Pull request closed without merging**
