### PR TITLE
Meshcat can handle Mesh(foo.gltf)

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Meshcat passes embedded .gltf files along to the meshcat session. This includes an incidental recentering of the objects created in the meshcat_manual_test.cc.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) 

You can test it by calling:

```
bazel run //geometry:meshcat_manual_test
```

The old green box has been replaced with the box shown above. All other aspects of the test should still work as advertised.

+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NYQp23H9Xu3eRHGkV4p:bv2pe8y)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NYR-PIY71B3q4teqniK:b-l8xbmn)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.cc` line 404 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR0aJO68j9kj8MeUD4:-NYR0aJO68j9kj8MeUD5:b-sp15w1) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/meshcat.cc#L404)):*
> ```cpp
>       matrix(1, 1) = mesh.scale();
>       matrix(2, 2) = mesh.scale();
>     } else {  // not obj or no mtllib.
> ```

bitrot



_Suggestion:_
```cpp
// not obj (or no mtllib) nor gltf
```
___
*[`geometry/render/test/meshes/cube.gltf` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR-ZB_58aAcMjrlQFI:-NYR-ZB_58aAcMjrlQFJ:biqgs0n) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/render/test/meshes/cube.gltf#L2)):*
> ```JSON
> {
> 	"asset":{
> ```

nit All of the other gltf files in Anzu and Drake use spaces instead of tabs.  Could we use spaces in this one for consistency?
___
*[`geometry/test/meshcat_manual_test.cc` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR1zvR6Hu0QzCzbsRH:-NYR1zvR6Hu0QzCzbsRI:b-owuefr) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L208)):*
> ```cpp
>   animation.SetTransform(40, "sphere", RigidTransformd(sphere_home));
> 
>   std::cout << "- the blue box should spin clockwise about the +z axis.\n";
> ```

nit This is a tiny bit ambiguous now.  There are two blue boxes, albeit one we call a "box" vs "cube" for whether or not the diameters are uniform.

Maybe "leftmost blue box" is sufficient?

Ditto below near "should have disappeared".
___
*[`geometry/test/meshcat_manual_test.cc` line 398 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR3TnkDPO8vrpthTK6:-NYR3TnkDPO8vrpthTK7:b-g9d6ek) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L398)):*
> ```cpp
>             << html_filename
>             << "\nOpen that location in your browser now and confirm that "
>                "the iiwa is visible and the animation plays."
> ```

This isn't working for me.  (The camera is zoomed into the iiwa base with no ability to pan/zoom, but the animation player does work.)

I'll see if it's also broken on master for me.
___
*[`geometry/test/meshcat_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYQz9xcAgHF3nEovkQo:-NYQz9xdAtMtrC2sSr5V:boe86hy) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_test.cc#L300)):*
> ```cpp
>       "gltf", Mesh(FindResourceOrThrow(
>                        "drake/geometry/render/test/meshes/cube.gltf"),
>                    .25));
> ```

nit GSG https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```cpp
0.25
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_manual_test.cc` line 398 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR3TnkDPO8vrpthTK6:-NYR51tuABw_MnWggbup:b-9eniah) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L398)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This isn't working for me.  (The camera is zoomed into the iiwa base with no ability to pan/zoom, but the animation player does work.)

I'll see if it's also broken on master for me.
</blockquote></details>

Weird.  It's passing now both on this branch (and of course on master).  I tried a few different things and nothing was able to repro the problem.  I guess it was a browser fluke.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've also reversed the order of the commits. The intention is to mark this as curated so that the meshcat dependency gets updated in its own commit.

Or would that be adversarial to release engineering? Is the true solution to update meshcat in its own PR and then to merge this one after the fact?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NYRHgut471bTWA9cPeO:bwjejqa)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render/test/meshes/cube.gltf` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR-ZB_58aAcMjrlQFI:-NYRFSfRC1k1EpmAJPC5:bv4wi31) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/render/test/meshes/cube.gltf#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit All of the other gltf files in Anzu and Drake use spaces instead of tabs.  Could we use spaces in this one for consistency?
</blockquote></details>

I'm somewhat disinclined to do so. Those were generated by VTK, this was generated by blender. Unless we want to create an auto-formatter for our ascii gltf files, I'd say we have to let it go. It doesn't seem reasonable for the author to force one generator to look like another.
___
*[`geometry/test/meshcat_manual_test.cc` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR1zvR6Hu0QzCzbsRH:-NYRGYia0mU_33sQUDxy:bjhl9k) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L208)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is a tiny bit ambiguous now.  There are two blue boxes, albeit one we call a "box" vs "cube" for whether or not the diameters are uniform.

Maybe "leftmost blue box" is sufficient?

Ditto below near "should have disappeared".
</blockquote></details>

I pushed the cube back to being green. Seemed simpler that way.
___
*[`geometry/test/meshcat_manual_test.cc` line 398 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR3TnkDPO8vrpthTK6:-NYRGd_4BI4eFeWrSmMT:b-r87iua) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L398)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Weird.  It's passing now both on this branch (and of course on master).  I tried a few different things and nothing was able to repro the problem.  I guess it was a browser fluke.
</blockquote></details>

Next time, I'd recommend sacrificing a chicken before trying. I can give you one of mine.
___
*[`geometry/test/meshcat_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYQz9xcAgHF3nEovkQo:-NYRHK502PdrnacQOaoZ:b-jh32wa) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_test.cc#L300)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit GSG https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals
</blockquote></details>

Fixed throughout this file and `meshcat_manual_test.cc`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
For future reviewers, the blue box is now green again.



> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NYRNZ2mD4o6VHLy7hNF:b-teb30w)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> I've also reversed the order of the commits. The intention is to mark this as curated so that the meshcat dependency gets updated in its own commit.

Right.  If this is merged as "curated" ideally the upgrade is first and the new feature is second.  Physically its the same either way, but this order might be slightly clearer for buildcops that they would need to revert either the second commit or both commits; they shouldn't revert just the first commit on its own.

> Or would that be adversarial to release engineering? Is the true solution to update meshcat in its own PR and then to merge this one after the fact?

Release engineer doesn't care either way, the most people who care are buildcops.  Since both commits require meshcat_manual_test inspection, it's probably smoothest to keep them in the same PR.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NYTQpeMBRz2pEfPG-G_:b65nmab)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_manual_test.cc` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYR1zvR6Hu0QzCzbsRH:-NYTNZvKDTGdfyvHaGVM:btojbfd) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_manual_test.cc#L208)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I pushed the cube back to being green. Seemed simpler that way.
</blockquote></details>

Great!
___
*[`geometry/test/meshcat_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYQz9xcAgHF3nEovkQo:-NYTQVVeCtT216EfaX61:bkmegaf) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_test.cc#L300)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Fixed throughout this file and `meshcat_manual_test.cc`.
</blockquote></details>

The global fix was incomplete (I found about a dozen more missed), and anyway I object to mixing this much unrelated churn into a feature PR that also upgrades an external (i.e., one that's more at risk of revert wars than usual).

I took the liberty of forking the cleanups into their own PR, which I hope to merge during the day today:
https://github.com/RobotLocomotion/drake/pull/19645

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-NYQz9xcAgHF3nEovkQo:-NYV7PTz3aPSz0h4gwSq:b-alam2k) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd4216ba93f0cce0d1eb7407dbe1183ff5273ffd/geometry/test/meshcat_test.cc#L300)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The global fix was incomplete (I found about a dozen more missed), and anyway I object to mixing this much unrelated churn into a feature PR that also upgrades an external (i.e., one that's more at risk of revert wars than usual).

I took the liberty of forking the cleanups into their own PR, which I hope to merge during the day today:
https://github.com/RobotLocomotion/drake/pull/19645
</blockquote></details>

D'oh! Sloppy, sloppy, sloppy. Thanks for breaking it out. It makes this PR much happier.  :)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) 
Meshcat has now updated (see https://github.com/rdeits/meshcat/pull/144). This is ready to get through the process.

Ready for full feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NZUo5j8BfM5Us2QTB-b:bop00ce)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@sherm1 for platform review or delegation, please.

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NZaJGaNDZuqleR0m9QA:bsalil7)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:
I ran meshcat_manual_test and followed the instructions -- everything looked great.

> Reviewed 1 of 4 files at r2, 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19635#-:-NZb1GQr7QL4BCvQoFsQ:bj9mjx4)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Pull request merged**
