### PR TITLE
[WIP] AddRigidBody() throws exception if object is preposterously large

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Ready for design review @sherm1 and @rpoyner-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-:-Nrrn2s42RErdiyQokv9:b-xezdoz)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dmEF7pwk3344aFcO:-Ns0dmEF7pwk3344aFcP:b-rb4x7k) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
> ```cpp
>           "\nThe maximum allowable space-diagonal is {} meters.\n",
>           __func__, name, space_diagonal, max_allowable_dimension);
>         throw std::runtime_error(error_message);
> ```

It is unacceptable to throw exceptions about invalid inertia on bodies that are welded to the world.  Once welded, their inertia will be ignored.  Throwing during "AddBody" is too early to know whether it will eventually be welded.  We must not force users to fine-tune the inertia of things like e.g. a "terrain" body that do not affect the dynamics.
___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dnKVD8XWPvnGjmru:-Ns0dnKVD8XWPvnGjmrv:b-xs5af) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
> ```cpp
>           "\nThe maximum allowable space-diagonal is {} meters.\n",
>           __func__, name, space_diagonal, max_allowable_dimension);
>         throw std::runtime_error(error_message);
> ```

It is unacceptable to throw exceptions about big inertias for users who are only going to calculate kinematics or collision queries.  The too-large number will not adversely affect some of those operations, so we should not force users to adjust their models if they are only tried to do those kinds of use cases.

**Comment by jwnimmer-tri** [comment]
I'll take over the design review, so that @rpoyner-tri and @sherm1 can stay focused on their other work.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0gRP1Ekc5Nyr5_-Rn:-Ns0gRP1Ekc5Nyr5_-Ro:bvccpo3) (no related file):*
So far, the PR overview fails to provide any context by which to proceed with design review.

It this trying to resolve an issue?  Add a capability?  What's the big picture.

Please provide sufficient written details so that we can understand what you're thinking, in order to provide feedback.

___

**Comment by mitiguy** [comment]
This PR helps to detect a spatial inertia that is associated with preposterously large objects (e.g., dimension of more than 1/2 km). These spatial inertia can arise from a simple units conversion error that can enter Drake directly from C++ or Python or from an erroneous URDF, SDF, or USD file. For example, a copy/paste from a CAD/CAE tool of 60 (which for CAD/CAE convenience may use units of g*cm²) into Drake or a SDF file which assumes units of kg*m², causes a 10⁷ error conversion! 

Spatial inertia only need to be tested when used by algorithms for dynamic analyses.  It is not necessary if the body is welded to the world or for calculating kinematics, do collision queries, etc.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dnKVD8XWPvnGjmru:-NsEW0xBDU7f1xQwUtiA:btx7gbh) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is unacceptable to throw exceptions about big inertias for users who are only going to calculate kinematics or collision queries.  The too-large number will not adversely affect some of those operations, so we should not force users to adjust their models if they are only tried to do those kinds of use cases.
</blockquote></details>

FWIW I don't think there are false-positive issues here, even in the case of static bodies or kinematics-only use cases. In order to trigger this error, someone has had to actively set intertia properties (presumably with intent to use them) and has done so with an absurd result. It won't be triggered by the common ways of ignoring inertia ,like setting it to 0 0 0 or 1 1 1. IMO if someone went to the trouble of setting the inertias to some very non-default values, and screwed that up, it is OK for us to reject those values with a helpful message.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dnKVD8XWPvnGjmru:-NsEXCq23sfnoiftmyHq:b-1yyj7w) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FWIW I don't think there are false-positive issues here, even in the case of static bodies or kinematics-only use cases. In order to trigger this error, someone has had to actively set intertia properties (presumably with intent to use them) and has done so with an absurd result. It won't be triggered by the common ways of ignoring inertia ,like setting it to 0 0 0 or 1 1 1. IMO if someone went to the trouble of setting the inertias to some very non-default values, and screwed that up, it is OK for us to reject those values with a helpful message.
</blockquote></details>

It's not accurate to say that users always wrote down the preposterous inertia with purpose or intention.  In both of the cases reported in #20730, the inertial stanza was created by an automated tool.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0gRP1Ekc5Nyr5_-Rn:-NsAt0K36lvzuDs7I9hA:b-bcxws3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So far, the PR overview fails to provide any context by which to proceed with design review.

It this trying to resolve an issue?  Add a capability?  What's the big picture.

Please provide sufficient written details so that we can understand what you're thinking, in order to provide feedback.
</blockquote></details>

This PR helps to detect a spatial inertia that is associated with preposterously large objects (e.g., dimension of more than 1/2 km). These spatial inertia can arise from a simple units conversion error that can enter Drake directly from C++ or Python or from an erroneous URDF, SDF, or USD file. For example, a copy/paste from a CAD/CAE tool of 60 (which for CAD/CAE convenience may use units of g*cm²) into Drake or a SDF file which assumes units of kg*m², causes a 10⁷ error conversion! 

___
___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dmEF7pwk3344aFcO:-NsAufpWD_rz8bRc9XB8:bqdio82) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is unacceptable to throw exceptions about invalid inertia on bodies that are welded to the world.  Once welded, their inertia will be ignored.  Throwing during "AddBody" is too early to know whether it will eventually be welded.  We must not force users to fine-tune the inertia of things like e.g. a "terrain" body that do not affect the dynamics.
</blockquote></details>

Agreed.  Perhaps better to move this check/throw to a post-finalize part of the code so we know the object is moving and is part of dynamic calculations?
___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dnKVD8XWPvnGjmru:-NsAvOPP4FLywFynpQIZ:b-f0yz4h) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is unacceptable to throw exceptions about big inertias for users who are only going to calculate kinematics or collision queries.  The too-large number will not adversely affect some of those operations, so we should not force users to adjust their models if they are only tried to do those kinds of use cases.
</blockquote></details>

Agreed.  Same thought as above.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21081)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/multibody_tree.cc` line 126 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21081#-Ns0dnKVD8XWPvnGjmru:-NsFQI1w4I1Tjm9SCNVs:b6fv4wb) ([raw file](https://github.com/RobotLocomotion/drake/blob/851af42cb0e6f33b0b11a81a5ee1946e5fdd2e44/multibody/tree/multibody_tree.cc#L126)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Agreed.  Same thought as above.
</blockquote></details>

Discussing this as part of a code review -- trying to reason bottom-up in a Reviewable thread -- is not going to be effective.  The next task for #20730 is to collect our thoughts and build consensus around which heuristic(s) we think are a good idea (top-down) and doing that using a more effective tool than Reviewable.  That's what Sherm said he would help facilitate, so my intention here is to suspend any Reviewable discussions until that design process reaches consensus.

**Comment by jwnimmer-tri** [comment]
Closing as abandoned.

If I recall the contemporaneous discussions, the disconned was that Mitiguy didn't understand that the preposterous numbers were coming from https://drake.mit.edu/pydrake/pydrake.multibody.mesh_to_model.html, so the fix in #20966 was already sufficient on its own to call the problem solved.

**Pull request closed without merging**
