### PR TITLE
Change an eps for AddSosConstraintUnivariate2 test

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6601)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@m-chaturvedi , feature-review please. Could you also trigger the affected OSX builds?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6601#-:-KpQPbpqn3FCBhP1rrfF:b-545qfe)*

**Comment by m-chaturvedi** [comment]
@drake-cdash-bot mac-clang-bazel-nightly-everything-release please
@drake-jenkins-bot mac-clang-bazel-nightly-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-nightly-everything-release please
@drake-jenkins-bot mac-clang-bazel-nightly-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
+@ericcousineau-tri and +@ggould-tri , platform-review please.

I've confirmed that this PR fixes the problem in `sos_constraint_test.cc` in CI. 

I believe that the current failure in `mac-clang-bazel-experimental-everything` has nothing to do with this PR:
```
ImportError: dlopen(/Users/elcapitan/workspace/mac-clang-bazel-experimental-everything/_bazel_elcapitan/c394ab6516e254625484eb969addef4a/bazel-sandbox/8141942120667232324/execroot/drake/bazel-out/osx-opt/bin/drake/bindings/pydrake_urdf_parser_test.runfiles/drake/drake/bindings/python/pydrake/_pydrake_common.so, 2): Library not loaded: libgurobi70.so
  Referenced from: /Users/elcapitan/workspace/mac-clang-bazel-experimental-everything/_bazel_elcapitan/c394ab6516e254625484eb969addef4a/bazel-sandbox/8141942120667232324/execroot/drake/bazel-out/osx-opt/bin/drake/bindings/pydrake_urdf_parser_test.runfiles/drake/drake/bindings/python/pydrake/_pydrake_common.so
  Reason: unsafe use of relative rpath libgurobi70.so in /Users/elcapitan/workspace/mac-clang-bazel-experimental-everything/_bazel_elcapitan/c394ab6516e254625484eb969addef4a/bazel-sandbox/8141942120667232324/execroot/drake/bazel-out/osx-opt/bin/drake/bindings/pydrake_urdf_parser_test.runfiles/drake/drake/bindings/python/pydrake/_pydrake_common.so with restricted binary
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6601#-:-KpR2wFxwQCENVL1TLA1:bdz4tbn)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6601#-:-KpR3uhLW-tCMmD6Nug6:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6601#-:-KpRCFTNJeRsWgTWrlPp:bnfp4nl)*

**Comment by soonho-tri** [comment]
-@EricCousineau-TRI to fix the `master`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6601#-:-KpRCX0lAjY_v8oDqmlc:bca15hk)*

**Pull request merged**
