### PR TITLE
[geometry] Implements CalcVolume for mesh geometry

### PR DESCRIPTION
**Pull request by RussTedrake**
This is needed to properly parse many mujoco mesh files. Related to #17267.

Note that one of our simple obj geometries (octahedron.obj) was not water-tight.  I've fixed it, but also kept the bad version to document that behavior.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: pending a few comments.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312#-:-NGhEGJP3geACTSwDv9Z:b-c3nwo5)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhE0tXBG2Q7m1n102k):*
BTW, maybe worth mentioning the in documentation of `geometry::CalcVolume` that the result is only meaningful for a "closed" shape.
___
*[`geometry/shape_specification.cc` line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGh91e22ZsZJiZfXT6X:-NGh91e22ZsZJiZfXT6Y:bkrm73o) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/shape_specification.cc#L289)):*
> ```cpp
>   void ImplementGeometry(const Mesh& mesh, void*) {
>     TriangleSurfaceMesh<double> surface_mesh =
>         ReadObjToTriangleSurfaceMesh(mesh.filename(), mesh.scale());
> ```

We also support Mesh with file extension `.vtk` now  for volume meshes. Have you considered supporting that as well?

If not, we should at least put up a note somewhere saying this only supports surface meshes.
___
*[`geometry/proximity/meshing_utilities.h` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGh7znmDpgdl5sSl20q:-NGh7znmDpgdl5sSl20r:bwqdy0z) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/proximity/meshing_utilities.h#L57)):*
> ```objc
>                                                     int v3, int v4);
> 
> /* Returns the volume enclosed by the surface mesh. */
> ```

nit This needs a note that the result is only meaningful if the mesh is watertight.
___
*[`geometry/proximity/test/meshing_utilities_test.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhCqcyEsBVYlsQzAXJ:-NGhCqcyEsBVYlsQzAXK:bfqv09h) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/proximity/test/meshing_utilities_test.cc#L76)):*
> ```cpp
>   // meshlab reports volume 0 for this mesh, also!
>   surface_mesh = ReadObjToTriangleSurfaceMesh(obj, 1.0);
>   EXPECT_NEAR(CalcEnclosedVolume(surface_mesh), 0.0, 1e-14);
> ```

minor, I'm suspicious of this test. Why should we expect any particular result with a not-allowed input?
___
*[`geometry/test/octahedron_no_volume.obj` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhB8tV6u8DgJYanzhk:-NGhB8tV6u8DgJYanzhl:b4mxs4b) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/test/octahedron_no_volume.obj#L1)):*
> ```
> mtllib octahedron.mtl
> ```

BTW, it'd be nice to put a comment here explaining what the file is like. I had a hard time imagining what a octahedron with no volume looks like.
I visualized this mesh and it looks perfectly fine to me? Is it because the winding is incorrect?

**Review by RussTedrake — COMMENTED** [review]
Thanks.  I've also added a bit more file extension robustness.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312#-:-NGhIdFs3ny5jumvaL1Y:bbb4h5g)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhE0tXBG2Q7m1n102k):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, maybe worth mentioning the in documentation of `geometry::CalcVolume` that the result is only meaningful for a "closed" shape.
</blockquote></details>

Done.
___
*[`geometry/shape_specification.cc` line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGh91e22ZsZJiZfXT6X:-NGhGtPxB0WJVI9eUkPf:b-a8fei0) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/shape_specification.cc#L289)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We also support Mesh with file extension `.vtk` now  for volume meshes. Have you considered supporting that as well?

If not, we should at least put up a note somewhere saying this only supports surface meshes.
</blockquote></details>

Done. I've added a note to the doc and a todo to the code.
___
*[`geometry/proximity/meshing_utilities.h` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGh7znmDpgdl5sSl20q:-NGhHbDw3-8m9xUUO5I-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/proximity/meshing_utilities.h#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit This needs a note that the result is only meaningful if the mesh is watertight.
</blockquote></details>

Done.
___
*[`geometry/proximity/test/meshing_utilities_test.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhCqcyEsBVYlsQzAXJ:-NGhHwyR1xHHVZazfPne:b9543j3) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/proximity/test/meshing_utilities_test.cc#L76)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I'm suspicious of this test. Why should we expect any particular result with a not-allowed input?
</blockquote></details>

I've added more to the comment so nobody thinks that I *want* zero to be the answer.
___
*[`geometry/test/octahedron_no_volume.obj` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhB8tV6u8DgJYanzhk:-NGhIbab2p01HTWHyxNP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/test/octahedron_no_volume.obj#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, it'd be nice to put a comment here explaining what the file is like. I had a hard time imagining what a octahedron with no volume looks like.
I visualized this mesh and it looks perfectly fine to me? Is it because the winding is incorrect?
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/shape_specification.cc` line 263 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhLY_CAbv6yw0y7VfB:-NGhLY_CAbv6yw0y7VfC:b-haxism) ([raw file](https://github.com/robotlocomotion/drake/blob/9a4b4f8e306cfa771679bb4113797cf61bcda6c2/geometry/shape_specification.cc#L263)):*
> ```cpp
> namespace {
> ```

nit is the whitespace addition intended?
___
*[`geometry/proximity/test/meshing_utilities_test.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhCqcyEsBVYlsQzAXJ:-NGhL2yF0zGjkOjhYc81:b-ff3c3q) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/proximity/test/meshing_utilities_test.cc#L76)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I've added more to the comment so nobody thinks that I *want* zero to be the answer.
</blockquote></details>

Understood. The comment is helpful for me, thanks.

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312#-:-NGnzZVW6VNO2qCYxRyV:btfqah9)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqtUnO4pcDDCDeIceY:-NGrPPgV5PvEzHUK3z0G:b-myh2q7) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm not clear about the value of keeping `octahedron_no_volume.obj`. It represents *one* way that one can specify a mesh that doesn't produce a valid volume, but certainly not the only way.  What about open manifolds? Or meshes which have cracks because  vertices were split and offset from each other? Or, my favorite, all faces are wound in the opposite direction and the volume has the correct, but negative, measure? If we're asserting that bad meshes produce bad measures, why limit ourselves to one particular way? Presumably, the test is in place so that if we inadvertantly "fix" this, the test will let us know that we need to update the documentation? (Which doesn't make much sense, because it's difficult to imagine we'd actually "fix" it.)
</blockquote></details>

I'm ok if we zap it.  It was a bug in the existing octahedron.obj which captured one possible failure -- I thought there was value in keeping it.  But it certainly doesn't capture all possible failure modes. 

Zap it, then?

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqtUnO4pcDDCDeIceY:-NGrRov4BI6SloDibNUk:b-b2n7t3) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I'm ok if we zap it.  It was a bug in the existing octahedron.obj which captured one possible failure -- I thought there was value in keeping it.  But it certainly doesn't capture all possible failure modes. 

Zap it, then?
</blockquote></details>

Zapping gets my vote. We don't do anything special for malformed meshes; we merely say the result is reliable for good meshes.

___

**Review by RussTedrake — COMMENTED** [review]
I've pushed my fixes, but turns out I can't actually compile on my work mac today (xcode version is too old; need to upgrade the OS!).  Hopefully this will get most of the code review done, and i'll let the mac update during my next meeting!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312#-:-NGs6mwD68X42sY-W_0M:bu9rmjx)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqtUnO4pcDDCDeIceY:-NGs2xcP9pa_K8-P98Qg:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Zapping gets my vote. We don't do anything special for malformed meshes; we merely say the result is reliable for good meshes.
</blockquote></details>

Done.

___
___
*[`geometry/shape_specification.cc` line 282 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqsPdy38DjDVCW_B4Q:-NGs3hct1RFebf2OfYQJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9220cbd9d78b6731d2000b6c1b5d3d72550db17/geometry/shape_specification.cc#L282)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: While you haven't crossed the three-copy boundary yet, we currently have two functions with identical implementations. It might be better to  put the implementation into a single function and have both of them call it. 
</blockquote></details>

Done.
___
*[`geometry/shape_specification.cc` line 284 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqrq2rDsSE8f8UpO75:-NGs3m0b2xEMsUWr-0mO:bnx95vg) ([raw file](https://github.com/robotlocomotion/drake/blob/a9220cbd9d78b6731d2000b6c1b5d3d72550db17/geometry/shape_specification.cc#L284)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: Did you mean for this to refer to `convex` (instead of mesh) geometries to differentiate this from the `Mesh` type? Or is the fact that it originated from a `Convex` or `Mesh` irrelevant?
</blockquote></details>

Here it is irrelevant.
___
*[`geometry/proximity/meshing_utilities.cc` line 51 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqvQdrEVi6niRc-yPG:-NGs49-sCgYiGQyqqKxz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9220cbd9d78b6731d2000b6c1b5d3d72550db17/geometry/proximity/meshing_utilities.cc#L51)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Perhaps a comment being clear about the assumption that pqr is wound with an outward facing normal?

Certainly, if my winding is consistent and reversed, I'll get a negative volume.
</blockquote></details>

Done.
___
*[`geometry/test/shape_specification_test.cc` line 626 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqwzLF4KtcBeuNwzEQ:-NGs5-AL1hGfKGu2_9f7:b-sjnt6l) ([raw file](https://github.com/robotlocomotion/drake/blob/a9220cbd9d78b6731d2000b6c1b5d3d72550db17/geometry/test/shape_specification_test.cc#L626)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd make an argument that this is testing `ReadObjToTraingleSurfaceMesh` behavior (and not `CalcVolume()`). Furthermore, the API doesn't document throwing for bad file names so the test doesn't support documentation.
</blockquote></details>

Done.  (updated the API to include bad file names in addition to bad file types).  I feel that is reasonable to cover it here.
___
*[`geometry/test/shape_specification_test.cc` line 631 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGqxdVhCL4niAUjk_U-:-NGs5cDvBoJVz8nItZI3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9220cbd9d78b6731d2000b6c1b5d3d72550db17/geometry/test/shape_specification_test.cc#L631)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I can appreciate that the next dozen lines is an aspirational place holder. However, an exhaustive list of files we don't support may be overkill. Therefore, the whole thing could be truncated and made to more directly reflect the code under test:

```c++
  // We only support obj but should eventually support vtk.
  const std::string non_obj = "only_extension_matters.not_obj";
  DRAKE_EXPECT_THROWS_MESSAGE(CalcVolume(Convex(non_obj, 1.0)),
                              ".*only supports .obj files.*");
  DRAKE_EXPECT_THROWS_MESSAGE(CalcVolume(Mesh(non_obj, 1.0)),
                              ".*only supports .obj files.*");
```



</blockquote></details>

Done.
___
*[`geometry/test/octahedron_no_volume.obj` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGhB8tV6u8DgJYanzhk:-NGs4b_lBZMFA9bJvN5S:b2nhjff) ([raw file](https://github.com/robotlocomotion/drake/blob/0215fa092621636e4c241ba01de3d3ba544276bb/geometry/test/octahedron_no_volume.obj#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Curious naming question: is the name misleading? What it is is `octahedron_bad_winding.obj` or `octahedron_inconsistent_winding.obj`. The "zero volume" is merely an implication based on a particular calculation. Certainly, ignoring volume calculation via signed volume, it has a non-zero volume. Probably not that important, but, as they say, naming is one of the two big problems (the others being caching and counting).
</blockquote></details>

N/A

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.cc` line 263 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18312#-NGs_GLH3FxOITjNNtnc:-NGs_GLH3FxOITjNNtnd:b-jxo2ov) ([raw file](https://github.com/robotlocomotion/drake/blob/53101dbb72ead0c24cb61ec0a1fadfcf7d38c3e5/geometry/shape_specification.cc#L263)):*
> ```cpp
> namespace {
> 
> template <MeshType>
> ```

FYI, the missing `class` keyword here is causing CI failure.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18312#-:-NGvUcJhDoqPy_jglP6g:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
