### PR TITLE
Bump CRU & VGT to latest

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17702)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
+@EricCousineau-TRI for review, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2, thanks! And sorry for the delay! (had reviewed the Anzu PR and somehow missed this one!)
+(status: single reviewer ok) +(release notes: fix) 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17702#-:-N9C3K15-AFbxX1YYyya:b-s26two)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
