### PR TITLE
[multibody] Fix NaN in body_spatial_acceleration output

### PR DESCRIPTION
**Pull request by Brian-Acosta**
This comment in `multibody_plant.h` is lying about `zero_acceleration_kinematics_placeholder_` getting populated with zeros :

```
  // When use_sampled_output_ports_ is true, then during Finalize() we populate
  // this with all-zero data, for use when the State has not yet been stepped.
```

This PR fixes this issue to avoid sending NaNs from the `body_spatial_accelerations` output port on the first step of a discret-time MBP simulation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22020)

### CODE REVIEW

**Comment by sherm1** [comment]
@drake-jenkins_bot ok to test

**Comment by sherm1** [comment]
@drake-jenkins-bot ok to test

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for a quick (4 line) sampled-output-ports-related feature review, please. Is this a one-off or are there other instances we should fix?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22020#-:-O8sB74a8alY8C77_mdS:bu2sskh)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @Brian-Acosta)

**Comment by jwnimmer-tri** [comment]
I am happy to review.  But it won't be as quick as four lines -- I will also need to develop and push the missing unit test.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for feature review, please.

(We'll assign a platform reviewer who is not me, later on.)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22020#-:-O8x2gHk3C5ALCQMoqN3:bdycs45)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22020#-:-O8xuN4HBICWWWVxeCQg:b-n0m1lx)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule (Tuesday), please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22020#-:-O9AEO2KA9FXAmIXoaoc:bnfp4nl)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

**Pull request merged**
