### PR TITLE
[workspace] Rewrite buildifier rule to use a github-centric flow

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(To be squashed.)

Towards #14967.

Closes #20638.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review, please.

**Comment by mwoehlke-kitware** [comment]
After staring at this for a long time trying to figure out what it does, I think I finally have some handle on it...

Things I don't like:
- Version and checksum information is uniquely not in `repository.bzl`
- `new_release` handling is bespoke to buildifier.

I saw some more minor points in the actual code, but I'd like to submit #20638 as an alternate proposal.

**Review by jwnimmer-tri — COMMENTED** [review]
@mwoehlke-kitware this is ready for another look.  I rewrote it to take your ideas from the other PR, but to push any arch-specific details into `package.BUILD.bazel` files instead of repository rules.  Now the repository rules just download attachments, which I think should scale better long term.  (At the cost of a little extra disk space for developers.)

I didn't polish the new_release changes to perfection, feel free to push amendments there as you wish.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-:-Np2Y1MvC3ULHVHAzF1t:bxc8kv4)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by mwoehlke-kitware — COMMENTED** [review]
The approach with `github_release_attachments` generally looks good, but I have a few comments/suggestions. I haven't looked at the `new_release` changes yet.

> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-:-Np6WPoZ-O10FAxbV6mu:b-hpbgpi)* status: 4 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/github.bzl` line 398 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6Ron1-Su4dVFM-FaD:-Np6Ron1-Su4dVFM-FaE:b-mj6qcn) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L398)):*
> ```Starlark
>     ]
> 
> def github_release_attachments(
> ```

I feel like this ought to at least support `upgrade_advice`, and possibly `commit_pin` also.
___
*[`tools/workspace/github.bzl` line 417 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6SKhs2AzCwx2r-qmv:-Np6SKhs2AzCwx2r-qmw:bu3hn12) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L417)):*
> ```Starlark
>         repository: required GitHub repository name in the form
>             organization/project.
>         commit: required the tag name to download.
> ```

Documentation for many parameters repeats the parameter name, but not here. It would be good to be consistent. (TBH, I lean toward the repetition being unnecessary.)

Similar for `attachments`.



_Suggestion:_
```Starlark
commit: required commit is the tag name to download.
```
___
*[`tools/workspace/github.bzl` line 515 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6UdF3Aw57xV0lh85l:-Np6UdF3Aw57xV0lh85m:bxr44ic) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L515)):*
> ```Starlark
>             output = filename,
>             sha256 = _sha256(sha256),
>             executable = True,
> ```

I feel like this should be a parameter or somehow an attribute of each attachment. It also seems unnecessary for buildifier due to the step to copy the platform-named artifact to the generic `buildifier` that also adds `+x`.
___
*[`tools/workspace/github.bzl` line 532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6VP8E6f3RxpLGOvRz:-Np6VP8E6f3RxpLGOvS-:bq0syk6) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L532)):*
> ```Starlark
>         commit = commit,
>         attachments = attachments,
>         downloads = downloads,
> ```

It looks like nothing actually uses this? I don't object to it being available, but I wonder if we could use the same format (i.e. `downloads` as a list-of-dict) for `github_archive`?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 8 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/github.bzl` line 398 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6Ron1-Su4dVFM-FaD:-Np6Xlzr7-5ErGi3WRQu:b7wgka7) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L398)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I feel like this ought to at least support `upgrade_advice`, and possibly `commit_pin` also.
</blockquote></details>

Added `upgrade_advice`.  I think we can wait on the pin support until we need it.
___
*[`tools/workspace/github.bzl` line 515 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6UdF3Aw57xV0lh85l:-Np6XTPFA-XTz0Y9905h:b-tycbur) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L515)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I feel like this should be a parameter or somehow an attribute of each attachment. It also seems unnecessary for buildifier due to the step to copy the platform-named artifact to the generic `buildifier` that also adds `+x`.
</blockquote></details>

Ah, yes.  This was from an earlier draft and never got removed.  It's gone now.
___
*[`tools/workspace/github.bzl` line 532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6VP8E6f3RxpLGOvRz:-Np6XJH_3iHPe2SW4ur_:b-pl9p94) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L532)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

It looks like nothing actually uses this? I don't object to it being available, but I wonder if we could use the same format (i.e. `downloads` as a list-of-dict) for `github_archive`?
</blockquote></details>

The `new_release` logic uses it, I think.

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/github.bzl` line 398 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6Ron1-Su4dVFM-FaD:-Np6nW_F8yqzDZFDmRbt:b-tbrwcz) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L398)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Added `upgrade_advice`.  I think we can wait on the pin support until we need it.
</blockquote></details>

Okay, I guess I can live with that...
___
*[`tools/workspace/github.bzl` line 515 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6UdF3Aw57xV0lh85l:-Np6kk0A37n5NvWTHwAd:bb6mt9b) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L515)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, yes.  This was from an earlier draft and never got removed.  It's gone now.
</blockquote></details>

:+1:
___
*[`tools/workspace/github.bzl` line 532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6VP8E6f3RxpLGOvRz:-Np6l63b4tr1Yfm03q5h:b8bhqjp) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L532)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `new_release` logic uses it, I think.
</blockquote></details>

Where? The only occurrence of `downloads` in `new_release` is in the documentation of `_download`. In any case, as noted, I think it's fine having the information available. My main point was rather the suggestion to change the metadata for `github_archive` so the two use the same schema. (`urls` and `sha256` are also not used AFAICT.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/github.bzl` line 532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6VP8E6f3RxpLGOvRz:-Np6uCU88_Gz2HW6c61I:b-uxkthf) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L532)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Where? The only occurrence of `downloads` in `new_release` is in the documentation of `_download`. In any case, as noted, I think it's fine having the information available. My main point was rather the suggestion to change the metadata for `github_archive` so the two use the same schema. (`urls` and `sha256` are also not used AFAICT.)
</blockquote></details>

Sorry, brain fart.  It's used by `mirror_to_s3`.

Repository rules with just 1 download put its urls and sha256 directly into the metadata file.  Rules with >1 download group a list of those under a separate `downloads` array.

I support we could try to clean up `mirror_to_s3` to be more uniform (and always use "downloads") but that's a bigger project than just github things.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: (please review `new_release` changes).

Tested by locally reverting buildifier to 6.3.3 and running `bazel run //tools/workspace:new\_release  -- --lint --commit buildifier`

> Reviewed 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-:-NpGrkZ15uRGhrORQdAi:b-6fyt6)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/github.bzl` line 532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-Np6VP8E6f3RxpLGOvRz:-NpGdfi87aif_4SvgJr-:bhsii9r) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ed533182af4aedefc249eeb519342aae88f1eef/tools/workspace/github.bzl#L532)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry, brain fart.  It's used by `mirror_to_s3`.

Repository rules with just 1 download put its urls and sha256 directly into the metadata file.  Rules with >1 download group a list of those under a separate `downloads` array.

I support we could try to clean up `mirror_to_s3` to be more uniform (and always use "downloads") but that's a bigger project than just github things.
</blockquote></details>

Ah, I hadn't realized this was used outside `new_release`, or that `downloads` was an existing schema.
___
*[`tools/workspace/new_release.py` line 346 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpGpIvj65pVpS7ykFmh:-NpGpIvj65pVpS7ykFmi:bgr8o7u) ([raw file](https://github.com/RobotLocomotion/drake/blob/228f952b86e251d09fccfc88a5aa105a15fd0ec3/tools/workspace/new_release.py#L346)):*
> ```Python
>     print("Downloading new attachments...")
>     new_attachments = {}
>     for filename in old_attachments.keys():
> ```

FYI, even though it's superfluous, I think `.keys()` here helps with clarity; any concerns/objections?
___
*[`tools/workspace/new_release.py` line 384 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpGpVOfBIbQ7JegYCMl:-NpGpVOfBIbQ7JegYCMm:b-6j90hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/228f952b86e251d09fccfc88a5aa105a15fd0ec3/tools/workspace/new_release.py#L384)):*
> ```Python
>         workspace_name, old_commit, new_commit))
> 
>     # Determine if we should and can commit the changes made.
> ```

FYI, this was the original wording. We *could*, in theory, commit over top of local changes, but we obviously *shouldn't*. (If we don't have a repo, then we *can't* commit anything.)

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpL8HvN6BBAKgOWR9Rw:b8n95m2) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
> ```Python
> 
> import git
> import github3
> ```

```
$ flake8 tools/workspace/new\_release.py
tools/workspace/new\_release.py:49:1: I201 Missing newline between import groups. 'import github3' is identified as Third Party and 'im  
port git' is identified as Third Party.
```



_Suggestion:_
```Python
import git

import github3
```

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpL8eZp-DNfeDx_trGv:b-dnhr0a) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

```
$ flake8 tools/workspace/new\_release.py
tools/workspace/new\_release.py:49:1: I201 Missing newline between import groups. 'import github3' is identified as Third Party and 'im  
port git' is identified as Third Party.
```
</blockquote></details>

I don't know what `isort` does, but `flake8-import-order` wants *all* third-party imports in their own group. Where they come from is irrelevant. (I am, of course, ignoring that it wants to sort `drake` before `git`.)

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpLB2Op25siZneCz7ge:be4l8ev) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I don't know what `isort` does, but `flake8-import-order` wants *all* third-party imports in their own group. Where they come from is irrelevant. (I am, of course, ignoring that it wants to sort `drake` before `git`.)
</blockquote></details>

Okay, it looks like this is [configurable](https://pypi.org/project/flake8-import-order/), with the above being the default (`cryptography`) style. Do we want to explicitly use the `edited` style?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpLEPut1_Q5ZYaOdKoR:bsl8488) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, it looks like this is [configurable](https://pypi.org/project/flake8-import-order/), with the above being the default (`cryptography`) style. Do we want to explicitly use the `edited` style?
</blockquote></details>

Possibly flake or isort is mis-flagging `git` as first-party, because it's in `/usr`?  It's third-party.  Anyway, those questions are best dealt with in the linting PRs, where we can look at the effect across many different places in Drake.  Trying to give an answer from just one isolated example here is not sufficient context.

Our prevailing style is one group of first party at the top, then all third-party as a group, then all drake as a group.  The current revision here is consistent with that prevailing style.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpLF8EeA8BUaWl9aN7A:b-scjqba) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Possibly flake or isort is mis-flagging `git` as first-party, because it's in `/usr`?  It's third-party.  Anyway, those questions are best dealt with in the linting PRs, where we can look at the effect across many different places in Drake.  Trying to give an answer from just one isolated example here is not sufficient context.

Our prevailing style is one group of first party at the top, then all third-party as a group, then all drake as a group.  The current revision here is consistent with that prevailing style.
</blockquote></details>

Sorry, typo in my last.  I should have said:

Our prevailing style is one group of standard library imports at the top, then all third-party imports as a group, then all drake imports as a group.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpLFSzJ1RDTabMI_uxh:b-l2h7ae) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry, typo in my last.  I should have said:

Our prevailing style is one group of standard library imports at the top, then all third-party imports as a group, then all drake imports as a group.
</blockquote></details>

No, `cryptography` specifies *each* third-party import as its own group. It isn't confused, it wants `git` in its own group, and `github3` *also* in its own group. See [example](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_cryptography.py).

I think you're asking for [`edited`](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_edited.py)...

Personally, however, I find this a little odd:
```python
import git
import github3
from git import *
```

With `cryptography`, that would be:
```python
import git
from git import *

import github3
```

There's also [`appnexus`](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_appnexus.py) style, which has its own quirks:
```python
import argparse
from dataclasses import dataclass
import getpass

import git
from git import *
import github3
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/new_release.py` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpL8HvN6BBAKgOWR9Rv:-NpLJuIa3uB34wXCd66g:b-o2u32d) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L49)):*
> No, `cryptography` specifies _each_ third-party import as its own group. It isn't confused, it wants `git` in its own group, and `github3` _also_ in its own group.

Ah, I understand now, thanks.

The `cryptography` style is awful and we won't choose that for Drake.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 1 of 8 files at r3, 7 of 7 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-:-NpRtpS4B0DzqMdiJHvm:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/new_release.py` line 109 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20579#-NpRqgNb1GcmxTTcFeqG:-NpRqgNb1GcmxTTcFeqH:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/964825e64d220cf600e221061736f40af37d0571/tools/workspace/new_release.py#L109)):*
> ```Python
>     result = original.replace(old, new)
>     if result == original:
>         raise RuntimeError(f"Could not find '{old}' to subtitute")
> ```

typo



_Suggestion:_
```Python
substitute
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20579)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
