### PR TITLE
Adds `CompositeTrajectory`

### PR DESCRIPTION
**Pull request by RussTedrake**
In particular, we need composite Bezier curves as the output of the upcoming GCS trajectory optimization code.

Also adds python bindings for this class and for BezierCurve.

+@sammy-tri for feature review, please?
fyi @wrangelvid

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
+@rpoyner-tri for platform review (I've got one open question but I don't think it needs to hold things up)

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-:-NSkCZl725HJDhm1KXR4:bz1x7p7)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),rpoyner-tri(platform) (waiting on @rpoyner-tri and @RussTedrake)

___
*[`common/trajectories/composite_trajectory.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSkBDHk9rA0DqdJcRBQ:-NSkBDHk9rA0DqdJcRBR:bt9baq0) ([raw file](https://github.com/RobotLocomotion/drake/blob/bbf7573170a7280e10f7efe8ac447d98a718843f/common/trajectories/composite_trajectory.h#L56)):*
> ```objc
> 
>  private:
>   bool do_has_derivative() const override { return true; }
> ```

I'm wondering why this is always true, as opposed to checking that all of the segments have derivatives (similar to `StackedTrajectory` for it's components)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-:-NSkSdF45w7D9sUOe5Im:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: testing questions

> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-:-NSl7rLs97-Lk5j53ZXp:b-1dr3o2)* status: 5 unresolved discussions (waiting on @RussTedrake)

___
*[`common/trajectories/composite_trajectory.cc` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl72U6EIc3ZaNvu-iF:-NSl72U6EIc3ZaNvu-iG:b-91hshh) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L18)):*
> ```cpp
>   std::vector<T> breaks(segments.size() + 1);
>   if (segments.empty()) {
>     breaks[0] = 0;
> ```

nit this branch is not reached by unit tests. Should I worry?
___
*[`common/trajectories/composite_trajectory.cc` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl79PlElMudQwpNNwx:-NSl79PlElMudQwpNNwy:bjl419p) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L51)):*
> ```cpp
> 
> template <typename T>
> Eigen::Index CompositeTrajectory<T>::rows() const {
> ```

nit this method is not reached by c++ unit tests. Should I worry?
___
*[`common/trajectories/composite_trajectory.cc` line 61 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl7EVF5USOLybaM0R-:-NSl7EVF5USOLybaM0R0:bjl419p) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L61)):*
> ```cpp
> 
> template <typename T>
> Eigen::Index CompositeTrajectory<T>::cols() const {
> ```

nit this method is not reached by c++ unit tests. Should I worry?
___
*[`common/trajectories/composite_trajectory.cc` line 98 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl7HyWAdA81ik-mwYF:-NSl7HyWAdA81ik-mwYG:b-91hshh) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L98)):*
> ```cpp
>   DRAKE_DEMAND(derivative_order >= 0);
>   if (derivative_order == 0) {
>     return this->Clone();
> ```

nit this branch is not reached by unit tests. Should I worry?
___
*[`bindings/pydrake/test/trajectories_test.py` line 474 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl6Zs6CHMV-tT16rSP:-NSl6Zs6CHMV-tT16rSQ:bjetk1d) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/bindings/pydrake/test/trajectories_test.py#L474)):*
> ```Python
>         numpy_compare.assert_float_equal(traj.start_time(), 0.0)
>         numpy_compare.assert_float_equal(traj.end_time(), 4.0)
>         self.assertIsInstance(traj.segment(0), PiecewisePolynomial)
> ```

nit the arg name "segment_index" should be exercised somewhere.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[`common/trajectories/composite_trajectory.cc` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl72U6EIc3ZaNvu-iF:-NSlEwAd7SgX4h9o5jSS:b-84plze) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L18)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this branch is not reached by unit tests. Should I worry?
</blockquote></details>

Done.  added a test.
___
*[`common/trajectories/composite_trajectory.cc` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl79PlElMudQwpNNwx:-NSlFGbR17FGINP63nD0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L51)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this method is not reached by c++ unit tests. Should I worry?
</blockquote></details>

Done.
___
*[`common/trajectories/composite_trajectory.cc` line 61 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl7EVF5USOLybaM0R-:-NSlFH86DUNel6JF-ijI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L61)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this method is not reached by c++ unit tests. Should I worry?
</blockquote></details>

Done.
___
*[`common/trajectories/composite_trajectory.cc` line 98 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl7HyWAdA81ik-mwYF:-NSlFjlrEDxOv5TpZa7U:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/common/trajectories/composite_trajectory.cc#L98)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this branch is not reached by unit tests. Should I worry?
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/trajectories_test.py` line 474 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19163#-NSl6Zs6CHMV-tT16rSP:-NSlGo1tCuQAcPgImANH:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bf36726276ae3eade9139cea57795a185b64518b/bindings/pydrake/test/trajectories_test.py#L474)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit the arg name "segment_index" should be exercised somewhere.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19163)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
