### PR TITLE
[parsing] Allow duplicate geometry names in URDF input

### LINKED ISSUE #19028: URDFs with duplicate geometry names
See http://sdformat.org/spec?ver=1.9&elem=visual for the SDFormat contract on geometry names.  The specification of `name` says:

>  Description: Unique name for the visual element within the scope of the parent link.

... i.e., that we're supposed to reject duplicate names.

To date, Drake has assumed that the same property must be true for URDF files as well.

However, if we compare the URDF spec for [joint names](http://wiki.ros.org/urdf/XML/joint) versus [geometry names](http://wiki.ros.org/urdf/XML/link#Elements) we see that joint names are specified as "a unique name" and geometry names are "a name for a part of a link's geometry" with no mention of uniqueness.  From that, I conclude that URDFs with duplicate geometry names are valid.

Apparently some URDF exporting tools generate files that look like this:
```xml
<?xml version="1.0" ?>
<robot name="...">
  <link name="link_0">
    <visual name="link_0">
      <origin xyz="..."/>
      <geometry>
        <mesh filename="link_0_0.obj"/>
      </geometry>
    </visual>
    <visual name="link_0">
      <origin xyz="..."/>
      <geometry>
        <mesh filename="link_0_1.obj"/>
      </geometry>
    </visual>
    ...
```

Note that the visual name is `link_0` for all meshes on that link.  Currently, Drake flags this as an error.

Given that the URDF specification does not mandate that geometry names must be unique, I think flagging an error here is too stern.

Instead, for URDF files we should demote this condition to a warning instead of error (by automatically salting geometry names in case there are duplicates).  Then users who turn on "strict" parsing mode would still get errors (because Drake's can't actually implement the file as-requested, due to the salting), but normal users would be able to proceed (modulo a warning message on their console).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19028

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 782 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQvOATP8yKoRNHP3kO1:-NQvOATP8yKoRNHP3kO2:btubjuk) ([raw file](https://github.com/RobotLocomotion/drake/blob/d9ee19ee60ef51c7d1950f2b6da280d495ff0ded/multibody/parsing/test/detail_urdf_geometry_test.cc#L782)):*
> ```cpp
>   ASSERT_EQ(collision_instances_.size(), 1);
>   EXPECT_EQ(visual_instances_[0].name(), "box");
>   EXPECT_EQ(collision_instances_[0].name(), "box2");
> ```

Should visual vs collision share a uniquefication domain, or should each one be its own domain?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 782 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQvOATP8yKoRNHP3kO1:-NQvu6n6556nNi6bgJVA:b-3fa3dt) ([raw file](https://github.com/RobotLocomotion/drake/blob/d9ee19ee60ef51c7d1950f2b6da280d495ff0ded/multibody/parsing/test/detail_urdf_geometry_test.cc#L782)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should visual vs collision share a uniquefication domain, or should each one be its own domain?
</blockquote></details>

Done.  Name uniqueness should be within a single role, so this is tested at the URDF layer now, not the geometry utilities.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: with some small clarity quibbles.

> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-:-NQz_2Kp59maUVF-h5g2:bn02y37)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`multibody/parsing/detail_urdf_geometry.h` line 143 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzV5yZE8M-FlBYB4iz:-NQzV5yZE8M-FlBYB4j-:b4atlqp) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/detail_urdf_geometry.h#L143)):*
> ```objc
>  repeated if the material properties are identical.
>  @param[in,out] geometry_names The list of geometry names already used within
>  the current MbP body (i.e., link) with the illustration role, so that this
> ```

nit: "...with the illustration and perception roles".

We currently have no facility to distinguish the two roles during parsing, so both get set. Admittedly, it happens via a tortuous mechanism (in which MbP promotes illustration to illustration + perception). So, although this code doesn't reference PerceptionProperties, it is still currently written with that end in mind.
___
*[`multibody/parsing/detail_urdf_parser.cc` line 265 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzY6fRB9jc-JyY70GY:-NQzY6fRB9jc-JyY70GZ:b-h2t8t6) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/detail_urdf_parser.cc#L265)):*
BTW Worth putting a note here about *why* this clear is here? 

> SceneGraph supports overlapping names for different roles; this segregates geometry names implicitly along those lines.

(Or some such thing.)
___
*[`multibody/parsing/test/detail_urdf_parser_test.cc` line 1102 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzZCTnEvLAVwBk5uTj:-NQzZCTnEvLAVwBk5uTk:b8iixdn) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/test/detail_urdf_parser_test.cc#L1102)):*
> ```cpp
> }
> 
> TEST_F(UrdfParserTest, TestDuplicateVisualName) {
> ```

nit: Two thoughts:

1. What about the same test for collision?
2. What about the case where a collision and visual geometry share the same name? Both should be instantiated verbatim. That is dependent on the `geometry_names.clear();`(whose significance doesn't get its full weight without such a supporting test). In fact, these tests wouldn't fail if you removed the line.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`multibody/parsing/test/detail_urdf_parser_test.cc` line 1102 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzZCTnEvLAVwBk5uTj:-NQza3DqA_o_ZAMlr2vr:b-pbl2el) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/test/detail_urdf_parser_test.cc#L1102)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Two thoughts:

1. What about the same test for collision?
2. What about the case where a collision and visual geometry share the same name? Both should be instantiated verbatim. That is dependent on the `geometry_names.clear();`(whose significance doesn't get its full weight without such a supporting test). In fact, these tests wouldn't fail if you removed the line.
</blockquote></details>

Oops, I somehow used the wrong test case name here, which I think confused you.

This is supposed to be the "visual vs collision" test with no warnings, not "duplicate visual".

(1) That's already covered in the other test program.

(2) That's exactly what this test is.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`multibody/parsing/detail_urdf_geometry.h` line 143 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzV5yZE8M-FlBYB4iz:-NQzfgo27jWgpBINz3bV:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/detail_urdf_geometry.h#L143)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "...with the illustration and perception roles".

We currently have no facility to distinguish the two roles during parsing, so both get set. Admittedly, it happens via a tortuous mechanism (in which MbP promotes illustration to illustration + perception). So, although this code doesn't reference PerceptionProperties, it is still currently written with that end in mind.
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_urdf_parser_test.cc` line 1102 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzZCTnEvLAVwBk5uTj:-NQzfKtB8KKxEeLvcz-O:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/test/detail_urdf_parser_test.cc#L1102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I somehow used the wrong test case name here, which I think confused you.

This is supposed to be the "visual vs collision" test with no warnings, not "duplicate visual".

(1) That's already covered in the other test program.

(2) That's exactly what this test is.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`multibody/parsing/test/detail_urdf_parser_test.cc` line 1102 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzZCTnEvLAVwBk5uTj:-NQzprAM6Y2Xa4jbrsUq:b-t7ayc7) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdc0d547de00b763f5fa6228cafcdda03837ece2/multibody/parsing/test/detail_urdf_parser_test.cc#L1102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You are correct. THe test named lulled my attention. Still, it led to an improvement, even if by accident.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzr6S18VBGfXWAppaC):*
This numbering scheme does not match 153f3fb18b8c2f5203ffb0531e96af75610c5040, nor does it match the scheme discussed [in slack](https://drakedevelopers.slack.com/archives/C2NN588UA/p1677769925341499). Did something change?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-NQzr6S18VBGfXWAppaC):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This numbering scheme does not match 153f3fb18b8c2f5203ffb0531e96af75610c5040, nor does it match the scheme discussed [in slack](https://drakedevelopers.slack.com/archives/C2NN588UA/p1677769925341499). Did something change?
</blockquote></details>

Nope.  I just completely misremembered what the consensus was.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19029#-:-NR-L9jPAqbq52QsvZJz:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
