### PR TITLE
Suppress Valgrind false positive in mosek_solver_internal_test

### PR DESCRIPTION
**Pull request by williamjallen**
The test `solvers/mosek_solver_internal_test` is currently failing under Valgrind on Jammy.  To speed our migration to Jammy, Valgrind has been disabled for this test.

This change fixes one of the issues listed in https://github.com/RobotLocomotion/drake/issues/18091.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539)

### CODE REVIEW

**Comment by williamjallen** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-valgrind-memcheck please.

**Comment by williamjallen** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-valgrind-memcheck please

**Review by williamjallen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18539#-NL2jubI9WXng44UDDSP:-NL2jubI9WXng44UDDSQ:b9rse0m) (no related file):*
+@betsymcphail for review

___

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539#-:-NL2lguI6ZjvER09UdRN:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by BetsyMcPhail — COMMENTED** [review]
+@sammy-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539#-:-NL2mIwrE3RE-pRJjqs_:b-6xrt9v)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
We have several mosek suppressions in `tools/dynamic_analysis/valgrind.supp`.  Do we think they're still valid?  Also what's the rationale for disabling memcheck entirely instead of adding a new suppression?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539#-:-NL2nu0l4ASCGfqbGd20:buin65e)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @williamjallen)

**Review by BetsyMcPhail — COMMENTED** [review]
Thanks for the suggestion, I completely forgot about the suppression file when working on this. That does seem like the better approach.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539#-:-NL2q24E-995Tncolfir:bg4s2nx)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @williamjallen)

**Comment by williamjallen** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
*[`tools/dynamic_analysis/valgrind.supp` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18539#-NL3FP-062myXPOrZQQ9:-NL3FP-062myXPOrZQQA:bb41k37) ([raw file](https://github.com/robotlocomotion/drake/blob/b80569b7e35c91a1f0a8fedb51a68cc2ae7268ce/tools/dynamic_analysis/valgrind.supp#L23)):*
> ```
>     match-leak-kinds: possible
>     ...
>     fun:_ZN7testing4Test3RunEv
> ```

This matching pattern is way too wide.  It will in effect disable Memcheck on every single test in Drake.

The match should be on something like `fun:moseklicense_checkout`, or anything else in https://drake-cdash.csail.mit.edu/test/924782530 that seems specific to this exact control flow path.

**Comment by williamjallen** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
*[`tools/dynamic_analysis/valgrind.supp` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18539#-NL3FP-062myXPOrZQQ9:-NL3LHIr8GPxq1VsBybj:brs5d06) ([raw file](https://github.com/robotlocomotion/drake/blob/b80569b7e35c91a1f0a8fedb51a68cc2ae7268ce/tools/dynamic_analysis/valgrind.supp#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This matching pattern is way too wide.  It will in effect disable Memcheck on every single test in Drake.

The match should be on something like `fun:moseklicense_checkout`, or anything else in https://drake-cdash.csail.mit.edu/test/924782530 that seems specific to this exact control flow path.
</blockquote></details>

Now it's the other end of Goldilocks.  The exact function names of "allocate_stack, allocate_rls, allocate_dtv" are subject to change as libc6 evolves, or different heap conditions are in effect.  Never mind that if a developer renames the test case, this suppression will no longer match but nobody will notice until the nightly build tips over.

The goal of a suppression should be to have _as few frames as possible_ while matching _only the problematic conditions_.  In this case that means something like the 1 fun I mentioned above -- any leaks _that happen within the license manager_ are of no consequence for us, since we can't actually fix them (MOSEK is closed-source).  It doesn't matter which test case name first called into the license manager -- we should suppress the message for all test cases.

**Review by williamjallen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail, @jwnimmer-tri, and @sammy-tri)

___
*[`tools/dynamic_analysis/valgrind.supp` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18539#-NL3FP-062myXPOrZQQ9:-NL3QCah7Y8R7sgmCxqz:b-eqf1n4) ([raw file](https://github.com/robotlocomotion/drake/blob/b80569b7e35c91a1f0a8fedb51a68cc2ae7268ce/tools/dynamic_analysis/valgrind.supp#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Now it's the other end of Goldilocks.  The exact function names of "allocate_stack, allocate_rls, allocate_dtv" are subject to change as libc6 evolves, or different heap conditions are in effect.  Never mind that if a developer renames the test case, this suppression will no longer match but nobody will notice until the nightly build tips over.

The goal of a suppression should be to have _as few frames as possible_ while matching _only the problematic conditions_.  In this case that means something like the 1 fun I mentioned above -- any leaks _that happen within the license manager_ are of no consequence for us, since we can't actually fix them (MOSEK is closed-source).  It doesn't matter which test case name first called into the license manager -- we should suppress the message for all test cases.
</blockquote></details>

My thought was that we would want to restrict it to the most minimal code path possible.  I now see that it's a library call which could get called again (and then need to be ignored again) at some point in the future.  I have made the suggested updates.

**Comment by williamjallen** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-valgrind-memcheck please

**Review by jwnimmer-tri — COMMENTED** [review]
I can do platform +@jwnimmer-tri -@sammy-tri.

:lgtm: modulo CI results.

> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18539#-:-NL3U4JS6zSRu0gUaGQG:b-a275o0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @williamjallen)

___
*[`tools/dynamic_analysis/valgrind.supp` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18539#-NL3FP-062myXPOrZQQ9:-NL3Ts3e-44x1JrR1HV2:b-k7gkyh) ([raw file](https://github.com/robotlocomotion/drake/blob/b80569b7e35c91a1f0a8fedb51a68cc2ae7268ce/tools/dynamic_analysis/valgrind.supp#L23)):*
<details><summary><i>Previously, williamjallen (William Allen) wrote…</i></summary><blockquote>

My thought was that we would want to restrict it to the most minimal code path possible.  I now see that it's a library call which could get called again (and then need to be ignored again) at some point in the future.  I have made the suggested updates.
</blockquote></details>

Yup. We want it specific enough to not risk false negatives, but also general enough to avoid foreseeable false positives down the road.

**Pull request merged**
