### PR TITLE
[WIP] Downgrade SNOPT to 7.2

### PR DESCRIPTION
**Pull request by aykut-tri**
(WIP; please don't review)

I’ve been working on downgrading SNOPT to 7.2. At this point, I got it into a working state for [a relaxed IK problem for iiwa](https://github.com/aykut-tri/drake/blob/downgrade_snopt/examples/kuka_iiwa_arm/iiwa_relaxed_ik.cc). However, it fails in tests, such as [the acrobot swing up](https://github.com/RobotLocomotion/drake/blob/master/examples/acrobot/test/run_swing_up_traj_optimization.cc).

Also, even for the working example, there are some memory issues (as shown in [this valgrind output](https://github.com/RobotLocomotion/drake/files/11114454/valgrind_iiwa_relaxed_ik.txt), during the LU decomposition of linear constraints) that I cannot find the root cause for. Something noteworthy is [the workspace memory resizing operations](https://github.com/RobotLocomotion/drake/compare/master...aykut-tri:downgrade_snopt?expand=1#diff-0c3815e5a67a9470653f46577afa91ff6fa611452496ef742a086ca5ce46bd35R1397-R1429) fail w/o [this change for increasing the initial size](https://github.com/RobotLocomotion/drake/compare/master...aykut-tri:downgrade_snopt?expand=1#diff-0c3815e5a67a9470653f46577afa91ff6fa611452496ef742a086ca5ce46bd35R388-R390) that was copied [from the adapter version compatible with 7.2](https://github.com/RobotLocomotion/drake/blob/4a7615d1c08c5c3bab7a9db7dbd94c15618073af/solvers/snopt_solver.cc#L165).

Any help would be greatly appreciated, and I'd be happy to provide further details.

---

Relates to #17609.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19103)

### CODE REVIEW

**Review by aykut-tri — COMMENTED** [review]
FYI, I've just fixed the issue!! It was about this part:
```
diff --git a/solvers/snopt_solver.cc b/solvers/snopt_solver.cc
index 0c2e49c0f0..4bdaa3cdb9 100644
--- a/solvers/snopt_solver.cc
+++ b/solvers/snopt_solver.cc
@@ -384,12 +384,12 @@ class WorkspaceStorage {
   explicit WorkspaceStorage(const SnoptUserFunInfo* user_info)
       : user_info_(user_info) {
     DRAKE_DEMAND(user_info_ != nullptr);
      iw_.resize(500);
      rw_.resize(500);
      cw_.resize(8 * 500);
   }

-  snopt::integer* iw() { return reinterpret_cast<snopt::integer*>(iw_.data()); }
+  snopt::integer* iw() { return iw_.data(); }
   int leniw() const { return iw_.size(); }
   void resize_iw(int size) { iw_.resize(size); }

@@ -409,7 +409,7 @@ class WorkspaceStorage {

  private:
   std::vector<char> cw_;
-  std::vector<int> iw_;
+  std::vector<snopt::integer> iw_;
   std::vector<double> rw_;
```

So now,`bazel test --config snopt --test_tag_filters=snopt //...` succeeds for all tests except for `SnoptTest.TestStringOption`, as this is unavailable in 7.2.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19103#-:-NRtGHCjCv2uJQYpSrmQ:b9n7utq)* status: LGTM missing from assignees aykut-tri,jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-packaging please

@jwnimmer-tri -- it looks like our instructions at https://drake.mit.edu/jenkins.html#building-binary-packages-on-demand are out of date?  The build requested above doesn't exist anymore?

**Comment by RussTedrake** [comment]
I tried making a docker image with this, but the [docker build script](https://github.com/RobotLocomotion/drake/tree/master/tools/install/dockerhub/focal) failed with
```
#7 70.19 Traceback (most recent call last):
#7 70.19   File "/opt/drake/lib/python3.8/site-packages/pydrake/__init__.py", line 42, in <module>
#7 70.19     from . import common
#7 70.19   File "/opt/drake/lib/python3.8/site-packages/pydrake/common/__init__.py", line 9, in <module>
#7 70.19     from ._module_py import *
#7 70.19 ModuleNotFoundError: No module named 'pydrake.common._module_py'
#7 70.19 
#7 70.19 During handling of the above exception, another exception occurred:
#7 70.19 
#7 70.19 Traceback (most recent call last):
#7 70.19   File "<string>", line 1, in <module>
#7 70.19   File "/opt/drake/lib/python3.8/site-packages/pydrake/__init__.py", line 44, in <module>
#7 70.19     if '/pydrake/' in e.path and 'cannot open shared object file' in e.msg:
#7 70.19 TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jwnimmer-tri** [comment]
> During handling of the above exception, another exception occurred:

=> https://github.com/RobotLocomotion/drake/pull/19296 for that fix.

**Comment by jwnimmer-tri** [comment]
> @jwnimmer-tri -- it looks like our instructions ... are out of date?

=> https://github.com/RobotLocomotion/drake/pull/19297

**Comment by RussTedrake** [comment]
Thanks Jeremy.

**Comment by RussTedrake** [comment]
Given the discussions we've had about the cost of supporting an old version, i think we should probably close this?  WDYT @aykut-tri ?

**Comment by aykut-tri** [comment]
Yes, I agree. So, I'm closing the issue.

**Pull request closed without merging**
