### PR TITLE
PID controller (system 2.0) moved to system/controllers

### LINKED ISSUE #3699: move PIDController from framework/primitives to controllers
@david-german-tri please execute if you support the idea?

related to #3698

### PR DESCRIPTION
**Pull request by naveenoid**
Clean up of framework/primitives. PID and any future controllers will from now on be a part of the DrakeSystemControllers library.

Fixes #3699

+@david-german-tri  for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3682)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTKeb5ElYGC9OU8vyAH:-KTKeb5FjVXoTneF-b0e:bc4ok3w) ([raw file](https://github.com/robotlocomotion/drake/blob/5822fdd4c0122e201b63a7474f43830e23b1854c/drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt#L5)):*
> ```CMake
> target_link_libraries(drakeControlledSpringMassSystemPlant
>     drakeSpringMassSystemPlant
>     drakeSystemControllers
> ```

Wait, so now `controllers` precedes `plants` in the physical ordering of `drake/systems`?  We should first have a conversation about whether that makes sense.  If it does, `drake/systems/CMakeLists.txt` should be updated accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682)*

**Comment by david-german-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTKeb5ElYGC9OU8vyAH:-KTKiS5pQNbG2PywkQ1T:b-lqqfax) ([raw file](https://github.com/robotlocomotion/drake/blob/5822fdd4c0122e201b63a7474f43830e23b1854c/drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Wait, so now `controllers` precedes `plants` in the physical ordering of `drake/systems`?  We should first have a conversation about whether that makes sense.  If it does, `drake/systems/CMakeLists.txt` should be updated accordingly.
</details>
Scribed from Slack #system2: plants should precede controllers.  We should cut the knot by moving this system out to `drake/examples`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682)*

**Comment by david-german-tri** [comment]
Please update `drake/systems/CMakeLists.txt` to reflect the correct physical ordering in its `add_subdirectory` calls (and document that that ordering is meaningful).

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTKeb5ElYGC9OU8vyAH:-KTKiibqYF_-4oeGp_ck:b-adrrav) ([raw file](https://github.com/robotlocomotion/drake/blob/5822fdd4c0122e201b63a7474f43830e23b1854c/drake/systems/plants/controlled_spring_mass_system/CMakeLists.txt#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Scribed from Slack #system2: plants should precede controllers.  We should cut the knot by moving this system out to `drake/examples`.
</details>
Wait, no.  That doesn't work because this system is used in the `analysis` tests.  So, that's where this system should move.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTKiqDGFUkbm7RejbnP:b3lm8kp)*

**Comment by naveenoid** [comment]
Moved controlled spring mass system. PTAL.

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTKeb5ElYGC9OU8vyAH:-KTVk8rorENkirA1wjZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5822fdd4c0122e201b63a7474f43830e23b1854c/drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Wait, no.  That doesn't work because this system is used in the `analysis` tests.  So, that's where this system should move.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTVk9xJDTyAE4Qw5Kdt:b2zn51h)*

**Comment by naveenoid** [comment]
Also assigning +@sherm1 for  feature review.

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTijD7uiaAA_ZXn_W5i:b-coyoyh)*

**Comment by sherm1** [comment]
:lgtm: -- a few minor things to fix, PTAL.

---

Reviewed 8 of 15 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjnmMYz0sjJAcT6UuI:-KTjnmMYz0sjJAcT6UuJ:b7z4mg2) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt#L16)):*
> ```CMake
> 
> drake_add_cc_test(controlled_spring_mass_system_test)
> target_link_libraries(controlled_spring_mass_system_test drakeControlledSpringMassSystemPlant drakeSystemFramework)
> ```

Newline missing and end of file.

---

*[drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system.h, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjo-iqSuL_x8xeJI2H:-KTjo-iqSuL_x8xeJI2I:bdsrmd4) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system.h#L11)):*
> ```objc
> #include "drake/systems/framework/primitives/demultiplexer.h"
> #include "drake/systems/framework/primitives/gain.h"
> #include "drake/systems/controllers/pid_controller.h"
> ```

Needs alphabetizing.

---

*[drake/systems/controllers/pid_controller.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjoHg5GTV97lL9PV_8:-KTjoHg5GTV97lL9PV_9:bdsrmd4) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/controllers/pid_controller.cc#L4)):*
> ```cpp
> 
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/common/drake_export.h"
> ```

Needs alphabetizing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTjp-sy0n6IVM5YPB6Q:b8e1fib)*

**Comment by david-german-tri** [comment]
:lgtm: aside from @sherm1's comments and my request re. `drake/systems/CMakeLists.txt` above.

---

Reviewed 8 of 15 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTkTNyJ4wvZPtyuGBZZ:-KTkTNyJ4wvZPtyuGBZ_:b-10o17o) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L16)):*
> ```cpp
> #include "drake/systems/framework/primitives/demultiplexer.h"
> #include "drake/systems/framework/primitives/gain.h"
> #include "drake/systems/controllers/pid_controller.h"
> ```

alphabetize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTkTH1TdhZjLbaI7jn1:b-2btoim)*

**Comment by naveenoid** [comment]
@david-german-tri I dont follow..what do you mean by 'correct physical ordering' ? The current order has controllers following plants as it should be..

---

Review status: 9 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTkTNyJ4wvZPtyuGBZZ:-KTqY_0goGZfOsW6NC-L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L16)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> alphabetize
</details>
Done.

---

*[drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjnmMYz0sjJAcT6UuI:-KTqYvy-sQB6DtPlfNuw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/analysis/test/controlled_spring_mass_system/CMakeLists.txt#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Newline missing and end of file.
</details>
Done.

---

*[drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system.h, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjo-iqSuL_x8xeJI2H:-KTqZCgQ-rdUUGTywuyL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Needs alphabetizing.
</details>
Done.

---

*[drake/systems/controllers/pid_controller.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-KTjoHg5GTV97lL9PV_8:-KTqZTBH8NUIth20uekM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be14482b226b341dc7136d1829d076d787ad52b1/drake/systems/controllers/pid_controller.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Needs alphabetizing.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTq_ljiavWKqewM6KhL:b-9r9jwm)*

**Comment by david-german-tri** [comment]
You are correct!  I'm just bad at reading, apparently.  :lgtm:

---

Review status: 9 of 17 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3682#-:-KTtA9KnG7AlPRDccYKR:bd19gj0)*

**Pull request merged**
