### PR TITLE
RgbdCamera: reduce duplicate code

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5576)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok: feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-Kfhoc9ILuGLE5wNyW-w:b6wxvvn)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-KfipEz3_nd3banQi9SR:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/rgbd_camera.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-Kfip3269V_d5NodgY2P:-KflFBKhFzn5gnHNK6E4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ffe99ba040056837b365038fd3009ae8630b9d/drake/systems/sensors/rgbd_camera.cc#L317)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider using `kFoo` constants for the indices.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576)*

**Comment by kunimatsu-tri** [comment]
+@david-german-tri: platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-KflFNBIorj_U7qv_wQ6:b-y7v93w)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 246 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-KflHUgPrTKrqa9a2I5B:-KflHUgQY0Gkz6TmjxUT:b-ap6w2f) ([raw file](https://github.com/robotlocomotion/drake/blob/405156ca3441ceb97d15791b40c6567e1391193e/drake/systems/sensors/rgbd_camera.cc#L246)):*
> ```cpp
> 
>   // Indices for id_object_maps_, renderers_ and render_windows_.
>   enum RenderTarget { kRenderTargetColorAndDepth = 0, kRenderTargetLabel = 1 };
> ```

BTW, consider using `enum class` for stronger type checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576)*

**Comment by liangfok** [comment]
*[drake/systems/sensors/rgbd_camera.cc, line 246 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-KflHUgPrTKrqa9a2I5B:-KflHf1zayj7oqfUhBw3:b-yyko39) ([raw file](https://github.com/robotlocomotion/drake/blob/405156ca3441ceb97d15791b40c6567e1391193e/drake/systems/sensors/rgbd_camera.cc#L246)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider using `enum class` for stronger type checking.
</blockquote></details>

Oh, nevermind, these are being used as indices into `std::array`. Marking myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

:lgtm:

This is fine, and you should feel free to merge it as-is, but let me just mention an alternative design: You could leave the class members as they were, not introduce index enums, and instead create local convenience arrays like `const std::array<some_pointer_type, 3> {depth_buffer_, color_buffer_, label_buffer_};` in the places where you need to loop over all the things.  This would let you keep the clear, terse `color_buffer_->SetInput` phrasing for operations that you do differently for each buffer.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 305 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-KflLh9hARNw1Sd7RFgV:-KflLh9hARNw1Sd7RFgW:b-yfexky) ([raw file](https://github.com/robotlocomotion/drake/blob/405156ca3441ceb97d15791b40c6567e1391193e/drake/systems/sensors/rgbd_camera.cc#L305)):*
> ```cpp
>   }
> 
>   int i = 0;
> ```

BTW, I think it's clearer just to loop on `i` in this situation, but it's within author's discretion either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-KflKTbUiCsMy2C9dUxI:b-fkvxtq)*

**Comment by kunimatsu-tri** [comment]
Thanks for your suggestion. Indeed, I think that way made the code much readable. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 305 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-KflLh9hARNw1Sd7RFgV:-KflSLXvCaLMjC2c4OA9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/405156ca3441ceb97d15791b40c6567e1391193e/drake/systems/sensors/rgbd_camera.cc#L305)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I think it's clearer just to loop on `i` in this situation, but it's within author's discretion either way.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-Kflj-em3N4M6C5W-QHl:b-2wah3f)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576#-:-KflpIw63_LOUGgxlar3:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5576)*

**Pull request merged**
