### PR TITLE
pydrake doc: Use `constexpr auto&` for nesting aliases

### LINKED ISSUE #9600: pydrake doc: gcc and clang disagree on need for lambda capture for `constexpr` vars
From here: https://github.com/RobotLocomotion/drake/pull/9571#issuecomment-426708850

Workarounds:
- Use `constexpr auto& doc`, rather than `auto& doc`
- Use `[&]` in lambda capture
- Add `copts = ["-Wno-unused-lambda-capture"]` for `pybind_py_library`

Action items:
- [x] Use a workaround in relevant sites (searching for `doc_lambda`)
- [x] Find or file upstream bug report:
   - clang: https://bugs.llvm.org/show_bug.cgi?id=39202
   - gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87559

\cc @m-chaturvedi @jamiesnape

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9600

\cc @m-chaturvedi 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9606)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by jamiesnape** [comment]
Can you unwind the workarounds here? https://github.com/RobotLocomotion/drake/blob/d3c9db36f44ab9eedcbef22d7d181e3d71736397/bindings/pydrake/multibody/rigid_body_tree_py.cc#L261-L414

**Comment by EricCousineau-TRI** [comment]
Done.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Pull request merged**
