### PR TITLE
This PR Should Be The Same As #2755.

### PR DESCRIPTION
**Pull request by liangfok**
This is identical to #2755 but does not suffer from the mysterious Matlab error in that PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2759)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review
+@ggould-tri for platform review

I believe this should be real quick since it's identical to #2755.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2759#-:-KM9g9Alk4UT1mYIziti:980707888)*

**Comment by jhoare** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2759#-:-KM9k6tOrEfSTQcIQHMS:1417088721)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2759#-:-KM9pvvsYe8Y7m2YXxdm:1417088721)*

**Comment by liangfok** [comment]
@nkoenig: I'm sorry I forgot to tag you on this PR before it was merged. Please take a look and let me know if there are any problems. I will be sure to tag you on all future ROS-related pull requests.

**Pull request merged**
