### PR TITLE
Bazel Lang Filter For Shell

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This is perhaps a more succinct way of doing the following:
https://github.com/RobotLocomotion/drake/pull/5909

Ref: https://github.com/RobotLocomotion/drake/pull/6045

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6046)

### CODE REVIEW

**Comment by jamiesnape** [comment]
From #6045:  I prefer this, though I wonder whether we should also ignore python tests.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6046#-:-KjOn8uUBOngH__N-p4M:b-qcjxox)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6046#-:-KjOnw2uFSKwn03rbQCA:b-uwkowd)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6046#-:-KjOopkadtCAm5BoxOJ0:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6046#-:-KjOuRfFBl0aK0grsk2M:bnfp4nl)*

**Pull request merged**
