### PR TITLE
[multibody] Remove CalcDiscreteContactPairs update manager forwarding

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15264)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: Thanks for the clean up.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15264#-:-MdPCHMi6gXoWsp8QfNz:b6p3ez2)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@sammy-tri for platform review on Wednesday per rotation please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15264#-:-MdPCTw90nX7C1B-lHs6:b-vcw7hi)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15264#-:-MdTKM2HBsx8vT3B-GFL:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
