### PR TITLE
Methods for evaluating batches of expressions and polynomials

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/math_py.cc` line 703 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NccBG4QEVm_s8bPnonX:-NccBG4QEVm_s8bPnonY:b-tlcjos) ([raw file](https://github.com/RobotLocomotion/drake/blob/f6dd2bfdba274f95240a8455b0c32ba135bd43c0/bindings/pydrake/math_py.cc#L703)):*
> ```cpp
>   bind.operator()<double, Monomial>();
>   bind.operator()<Monomial, double>();
> //  bind.operator()<Monomial, Monomial>();
> ```

Not sure why this one doesn't work natively? Any thoughts @jwnimmer-tri

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`common/symbolic/test/polynomial_test.cc` line 1096 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NccqRNQ6k5DSxiOfnvA:-NccqRNR6gHFr50C3Mp5:b-166gui) ([raw file](https://github.com/RobotLocomotion/drake/blob/3118546668254c056cf7607ea5b9fccccf3a48d6/common/symbolic/test/polynomial_test.cc#L1096)):*
> ```cpp
>   }};
>   envs.push_back(partial_env);
>   EXPECT_THROW(unused(p.EvaluateBatch(envs)), runtime_error);
> ```

After making this mutlithreaded, I succeed in throwing a runtime error, but I fail to catch it with this test and the program exits. Any thoughts?

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Review by jwnimmer-tri — COMMENTED** [review]
There is a lot going on here.  I've read through about half of it so far, and posted some comments below to get us started.

> Reviewed 1 of 11 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-:-NcmwHHwDPNuavK4KHXa:b-bioozy)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.h` line 115 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmprCcEl5SPffcUxtn:-NcmprCcEl5SPffcUxto:bf0ajfa) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.h#L115)):*
> ```objc
>   explicit Polynomial(const Expression& e);
> 
>   /// Constructs a polynomial from a varaible @p v. Note that v is considered an
> ```

nit The lexical placement of this constructor ends up splitting up the two `Expression` overloads (with and w/o `indeterminates`), which is a hindrance to readability.  (We want to keep similar things nearby each other.)

This overload should move somewhere else in the sequence.  I'd buy either just before or just after the `const Monomial&` overload.
___
*[`common/symbolic/polynomial.h` line 219 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmrMTCDj7d27NVyxXt:-NcmrMTCDj7d27NVyxXu:br4hlp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.h#L219)):*
> ```objc
>   ///
>   /// @throws std::exception if there is a variable in this polynomial whose
>   /// assignment is not provided by at least one of the enivornments @p envs.
> ```

Is "at least one" accurate?  I'd expect that _all_ envs must have _all_ variables provided.  Otherwise, how can we resolve the polynomial down to a plain `double` in the return value?
___
*[`common/symbolic/polynomial.h` line 544 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmsKVK3o_eBpPP64LO:-NcmsKVK3o_eBpPP64LP:bww56gz) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.h#L544)):*
> ```objc
> /// - Matrix<Variable> * Matrix<Polynomial> => Matrix<Polynomial>
> /// - Matrix<Monomial> * Matrix<Variable> => Matrix<Polynomial>
> /// - Matrix<Variable> * Matrix<Monomial> => Matrix<Polynomial>
> ```

Why is this stanza an entirely separate copy of the boilerplate, instead of adding these 4 more cases to the logic immediately above?
___
*[`common/symbolic/polynomial.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-Ncmu-8h9F3zHJFnrkXM:-Ncmu-8h9F3zHJFnrkXN:bkln2e6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.cc#L582)):*
> ```cpp
>   std::vector<double> ret(ssize(envs));
> #if defined(_OPENMP)
> #pragma omp parallel for num_threads(std::thread::hardware_concurrency())
> ```

nit Don't override user preferences for thread control.

Ditto below.



_Suggestion:_
```cpp
#pragma omp parallel for
```
___
*[`common/symbolic/polynomial.cc` line 828 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmtVOt9uvSJvvCWdbt:-NcmtVOt9uvSJvvCWdbu:bol8znf) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e819d4739eda9e14a125f59ebd0574dc72189ea/common/symbolic/polynomial.cc#L828)):*
> ```cpp
>     const std::unordered_map<Variable, Polynomial>& indeterminate_substitution,
>     SubstituteAndExpandCacheData* substitutions_cached_data)
>     const {
> ```

BTW Please do not make unrelated whitespace changes.  Please revert this edit.

(Use `git clang-format` not `clang-format`, when the BUILD file has `enable_clang_format_lint = False`. See https://drake.mit.edu/code_style_tools.html)
___
*[`common/symbolic/expression/expression.h` line 1597 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmmNjc-GCJk8LFDlfY:-NcmmNjc-GCJk8LFDlfZ:bf8qcam) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/expression/expression.h#L1597)):*
> ```objc
>                  MatrixLikewise<Expression, Derived>>
> EvaluatePartial(const Eigen::MatrixBase<Derived>& m,
>                 const Environment& env = Environment{}) {
> ```

nit The member function `Expression::EvaluatePartial` does not default to an empty environment, and nor do I think we should do so here.  (It doesn't make any sense, since the operation would be a no-op.)



_Suggestion:_
```objc
EvaluatePartial(const Eigen::MatrixBase<Derived>& m,
                const Environment& env) {
```
___
*[`common/symbolic/expression/expression.h` line 1606 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-Nce22XF7FsUHzk5xwrv:-Nce22XG9vpe-VNL7r_n:b-siucs5) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/expression/expression.h#L1606)):*
> ```objc
> }
> 
> /** Partially evaluates @p m using a given environment.
> ```

nit Please switch to `///` formatting so we're consistent within this header file.
___
*[`common/symbolic/expression/expression.h` line 1609 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-Nce2SZKC09G717-fW9U:-Nce2SZKC09G717-fW9V:b47djgl) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/expression/expression.h#L1609)):*
> ```objc
>  *
>  * @throws std::exception if there exists a variable in @p m whose value is
>  *                        not provided by @p env.
> ```

nit This exception doesn't seem appropriate for `EvaluatePartial`.
___
*[`common/symbolic/expression/expression.h` line 1614 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmmcmN55mPMoSiCtVz:-NcmmcmO3jxKukcUUrvK:bmoytl6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/expression/expression.h#L1614)):*
> ```objc
> Eigen::SparseMatrix<Expression> EvaluatePartial(
>     const Eigen::Ref<const Eigen::SparseMatrix<Expression>>& m,
>     const Environment& env = Environment{});
> ```

BTW ditto



_Suggestion:_
```objc
Eigen::SparseMatrix<Expression> EvaluatePartial(
    const Eigen::Ref<const Eigen::SparseMatrix<Expression>>& m,
    const Environment& env);
```
___
*[`common/symbolic/expression/test/expression_matrix_test.cc` line 505 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-Ncmnw7l1SurTc7O8xE8:-Ncmnw7l1SurTc7O8xE9:b-xajmdu) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/expression/test/expression_matrix_test.cc#L505)):*
> ```cpp
>   // clang-format on
>   const Eigen::Matrix<Expression, 3, 2> A_eval{EvaluatePartial(1.0 * A_, env)};
>   std::cout << "check 1" << std::endl;
> ```

nit Avoid `cout` in unit tests.  (I assume these are vestigial.)

Ditto throughout.
___
*[`common/symbolic/test/polynomial_test.cc` line 1096 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NccqRNQ6k5DSxiOfnvA:-NcmuGx0-R9PJJ5ddVtb:bpinr67) ([raw file](https://github.com/RobotLocomotion/drake/blob/3118546668254c056cf7607ea5b9fccccf3a48d6/common/symbolic/test/polynomial_test.cc#L1096)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

After making this mutlithreaded, I succeed in throwing a runtime error, but I fail to catch it with this test and the program exits. Any thoughts?
</blockquote></details>

It is illegal to allow exceptions to percolate out of an OMP par-for loop (see https://stackoverflow.com/questions/69889899/what-is-the-correct-way-for-exception-handling-with-openmp-tasks).

For now, the easiest fix is probably to remove the OMP usage here.  The batching function at least would still help with C++/Python function call overhead, even if it isn't multicore yet.

Later, we could circle back and add multicore.  It will require a new argument in any case, to control the concurrency.  TRI has a `Parallelism = true|false|int` class on the way that will help with that.  (It's not OK for a function to launch worker threads with no way to opt-out.)
___
*[`bindings/pydrake/symbolic_py.cc` line 502 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmonST7xIfR85FJjzn:-NcmonST7xIfR85FJjzo:bmoytl6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/bindings/pydrake/symbolic_py.cc#L502)):*
> ```cpp
>         return EvaluatePartial(M, Environment{env});
>       },
>       py::arg("m"), py::arg("env") = Environment::map{},
> ```

BTW ditto



_Suggestion:_
```cpp
py::arg("env")
```

**Review by jwnimmer-tri — COMMENTED** [review]
I pulled the matmul improvements out into #20057, which I hope we can land first.

The batch operations here will take a little more finesse.  I'm happy to help with that also, but I'd like to get the matmul fixes and #20093 landed first, and then we can circle back here.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-:-Nd7RSOV2uLghaBY562p:b490i6y)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`common/symbolic/polynomial.h` line 115 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmprCcEl5SPffcUxtn:-Nd7Rj2f0-UUl8pKAkoZ:b-tdeboi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.h#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The lexical placement of this constructor ends up splitting up the two `Expression` overloads (with and w/o `indeterminates`), which is a hindrance to readability.  (We want to keep similar things nearby each other.)

This overload should move somewhere else in the sequence.  I'd buy either just before or just after the `const Monomial&` overload.
</blockquote></details>

Withdrawn (other PR).
___
*[`common/symbolic/polynomial.h` line 544 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NcmsKVK3o_eBpPP64LO:-Nd7RlBu0eh9JCFR-E-T:b-tdeboi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.h#L544)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why is this stanza an entirely separate copy of the boilerplate, instead of adding these 4 more cases to the logic immediately above?
</blockquote></details>

Withdrawn (other PR).
___
*[`bindings/pydrake/math_py.cc` line 703 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NccBG4QEVm_s8bPnonX:-Nd7Ru4989MhpavsbzA2:bebwbrd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f6dd2bfdba274f95240a8455b0c32ba135bd43c0/bindings/pydrake/math_py.cc#L703)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Not sure why this one doesn't work natively? Any thoughts @jwnimmer-tri
</blockquote></details>

I fixed it in the other PR.  It was because the type of `Monomial * Monomial` is `Monomial` but the type of `Matrix<Monomial> * Matrix<Monomial>` is `Matrix<Polynomial>`.  The T3 typedef above needed to use the matrix mul interrogation, but was mistakenly using scalar mul interrogation.

**Comment by jwnimmer-tri** [comment]
Oops, I meant to say pulled into https://github.com/RobotLocomotion/drake/pull/20099.

**Comment by jwnimmer-tri** [comment]
FYI my plan is to push a merge commit to this PR, to sync with latest master, so we can look at the batch-eval stuff here.

Also, recently I noticed `Polynomial::EvaluateIndeterminates`.  That function seems a bit related to the new batch-eval stuff here.  I wonder if it already does what you need (for some cases).

**Review by jwnimmer-tri — COMMENTED** [review]
I've pushed the merge-up now, as additional commits.  (Feel free to squash and force-push anytime you like; I just didn't want to force-push since its not my branch.)

> Reviewed 2 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-:-Ndrhd5NBNL0TFfCWuOK:bqdo5ha)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-Ncmu-8h9F3zHJFnrkXM:-NdrhKDk2aLX9w9B61xt:bx2cu8c) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8aae956c01820749bd7e7a45d4cac50d77552b/common/symbolic/polynomial.cc#L582)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Don't override user preferences for thread control.

Ditto below.
</blockquote></details>

OK Actually, we have a better way do to this now.  I'll post that sample code separately, and retract this discussion.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.h` line 217 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NnAnDHq9fYToVltpQty:-NnAnDHq9fYToVltpQtz:bphfsj2) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a91460cdb805736a5b46a94c61bfde85d32a8a8/common/symbolic/polynomial.h#L217)):*
> ```objc
>   /// assignment is not provided by at least one of the enivornments @p envs.
>   [[nodiscard]] std::vector<double> EvaluateBatch(
>       const std::vector<Environment>& envs) const;
> ```

For all of these new functions, if we are going to use OpenMP, then we must offer an argument to control the level of parallelism:

```c++
[[nodiscard]] std::vector<double> EvaluateBatch(
    const std::vector<Environment>& envs,
    Parallelism parallelize = Parallelism::Max()) const;
```

Or, a possible step forward would be to add EvaluateBatch API but not yet use multicore internally (instead, adding multicore in a follow-up PR).  Even the single-threaded batching might cut down on the Python/C++ call overhead, though I'm not sure how much of a help that is.

**Review by AlexandreAmice — COMMENTED** [review]
This PR is somewhat stale. I will try to look into it again soon.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-:-NnExobwBANSMaXCPmrt:b-c6msv6)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`common/symbolic/polynomial.h` line 217 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NnAnDHq9fYToVltpQty:-NnExV2m3IWEpsCwrFfL:b5ems0l) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a91460cdb805736a5b46a94c61bfde85d32a8a8/common/symbolic/polynomial.h#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For all of these new functions, if we are going to use OpenMP, then we must offer an argument to control the level of parallelism:

```c++
[[nodiscard]] std::vector<double> EvaluateBatch(
    const std::vector<Environment>& envs,
    Parallelism parallelize = Parallelism::Max()) const;
```

Or, a possible step forward would be to add EvaluateBatch API but not yet use multicore internally (instead, adding multicore in a follow-up PR).  Even the single-threaded batching might cut down on the Python/C++ call overhead, though I'm not sure how much of a help that is.
</blockquote></details>

When I was adding this function, the overhead from Python to C++ was negligible compared to the time it would take to evaluate a single polynomial. This was useful when I had to evaluate about 100 polynomial expressions each of which took between 2-10 seconds to evaluate.

If we were to use OpenMP, can we access the `Parallelsim` type in Python?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20057)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.h` line 217 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20057#-NnAnDHq9fYToVltpQty:-NnEyyp8-MrkN8XKRxTP:b-5k0r8s) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a91460cdb805736a5b46a94c61bfde85d32a8a8/common/symbolic/polynomial.h#L217)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

When I was adding this function, the overhead from Python to C++ was negligible compared to the time it would take to evaluate a single polynomial. This was useful when I had to evaluate about 100 polynomial expressions each of which took between 2-10 seconds to evaluate.

If we were to use OpenMP, can we access the `Parallelsim` type in Python?
</blockquote></details>

Yes: https://drake.mit.edu/pydrake/pydrake.common.html#pydrake.common.Parallelism

**Pull request closed without merging**
