### PR TITLE
[workspace] Upgrade curl_internal to latest release curl-8_3_0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Needs new definitions, some of which aren't immediately obvious.

Towards #20290.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20302)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri to take a look at the CMake definition changes

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge)  +(status: single reviewer ok) +(priority: low) 

@rpoyner-tri for both reviews tomorrow, please.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20302#-:-NfrH1VhEtfgPPPz06ek:bgwo44v)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
The only surprising change was disabling the "Form API".  We do post forms, but apparently we use the "Mime API" for that, not the "Form API".

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20302#-:-NfvdnlXB_hTbxMhMxL7:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20302#-:-Nfvdu4V26gxhL68SAx1:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
