### PR TITLE
Bump CRU and VGT with new DegreeOfParallelism API

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`tools/workspace/common_robotics_utilities/repository.bzl` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_54xts6NFHpkNlOdMq:-N_54xts6NFHpkNlOdMr:b-g6l07q) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/tools/workspace/common_robotics_utilities/repository.bzl#L11)):*
> ```Starlark
>     github_archive(
>         name = name,
>         repository = "calderpg/common_robotics_utilities",
> ```

working When ready, land changes upstream and update
___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_54yjI6rXc-r-a6Fnj:-N_54yjI6rXc-r-a6Fnk:b-g6l07q) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/tools/workspace/voxelized_geometry_tools/repository.bzl#L11)):*
> ```Starlark
>     github_archive(
>         name = name,
>         repository = "calderpg/voxelized_geometry_tools",
> ```

working When ready, land changes upstream and update

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: fix) to release-note the upgraded externals.

LGTM so far.  I'm going to wait to cross-check the updated repository rules until we have a final commit version for the dependencies.

> Reviewed 3 of 5 files at r2, 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-:-N_5wkRn2zgdiOwoyWCi:bp5lry0)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`planning/collision_checker.h` line 1220 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_5xc0uDQM4HxwLfCub:-N_5xc0uDQM4HxwLfCuc:bmj5auh) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/planning/collision_checker.h#L1220)):*
> ```objc
> 
>   /* Gets the number of threads that may be used in an OpenMP-parallelized loop,
>     if parallelize=true, or 1 if parallelize=false. */
> ```

nit In this file, API comment indentation after a line wrap is +1 space versus the `/*` opener.  This line has +2 spaces.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`planning/collision_checker.h` line 1220 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_5xc0uDQM4HxwLfCub:-N_B1mq0-oZ1Lwg7Yge5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/planning/collision_checker.h#L1220)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In this file, API comment indentation after a line wrap is +1 space versus the `/*` opener.  This line has +2 spaces.
</blockquote></details>

Done.
___
*[`tools/workspace/common_robotics_utilities/repository.bzl` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_54xts6NFHpkNlOdMq:-N_B1o8h8lJutGjSpBGT:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/tools/workspace/common_robotics_utilities/repository.bzl#L11)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

working When ready, land changes upstream and update
</blockquote></details>

Done.
___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_54yjI6rXc-r-a6Fnj:-N_B1pKi7PBKcKFecZNj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5c2ba0ca3e08286ba6e140cda551022a09ffc70/tools/workspace/voxelized_geometry_tools/repository.bzl#L11)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

working When ready, land changes upstream and update
</blockquote></details>

Done.

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 6 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-:-N_BuIiI1l6Dy0T80zrG:b-n37teh)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`tools/workspace/voxelized_geometry_tools/package.BUILD.bazel` line 108 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_BtO-M1Fc5MxIz6WgT:-N_BtO-N8bXKaGqgogIs:b6nj9j0) ([raw file](https://github.com/RobotLocomotion/drake/blob/b910e74821b31468df29f96542f38c4d0f7c97df/tools/workspace/voxelized_geometry_tools/package.BUILD.bazel#L108)):*
> ```
> )
> 
> # N.B. This test uses two threads even when OpenMP is not available.
> ```

BTW Is this comment accurate?

I can see that the `DegreeOfParallelism dispatch_parallelism` is set to `2` for one of the suites, but the OpenCL backend(s) don't use CPUs (at least not for me?), and the CPU back-end seems to be serial-only (based on the console output).  Only the OpenMP back-end seems to be CPU-parallel (from the console output).

I didn't run the CRU planning_test, but I also wonder whether the same question applies there.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`tools/workspace/voxelized_geometry_tools/package.BUILD.bazel` line 108 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_BtO-M1Fc5MxIz6WgT:-N_BycVyC5m8cGquIVZ-:b94kcm1) ([raw file](https://github.com/RobotLocomotion/drake/blob/b910e74821b31468df29f96542f38c4d0f7c97df/tools/workspace/voxelized_geometry_tools/package.BUILD.bazel#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this comment accurate?

I can see that the `DegreeOfParallelism dispatch_parallelism` is set to `2` for one of the suites, but the OpenCL backend(s) don't use CPUs (at least not for me?), and the CPU back-end seems to be serial-only (based on the console output).  Only the OpenMP back-end seems to be CPU-parallel (from the console output).

I didn't run the CRU planning_test, but I also wonder whether the same question applies there.
</blockquote></details>

The dispatch process uses multiple threads, but relatively little work is performed on the CPU versus the GPU. Additionally, most (all?) OpenCL implementations end up serializing kernels, so aside from the float packing performed on the CPU, one of those threads is most likely going to be waiting to dispatch its kernel until the other kernel is complete. Using `cpu:2` here is just being conservative.

As for the CRU planning test, there is now a `std::async`-based fallback for KNN when OpenMP isn't available, so the nearest neighbor checks of the PRM and RRT planners are still parallelized.

**Review by calderpg-tri — COMMENTED** [review]
I was planning to leave a `std::async`-based fallback for the CPU voxelizer for a later PR, but when trying it out I fixed a bug related to KNN per-thread range assignments and it makes sense to pull in the fix here.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-:-N_DMJLKDL3Nl_zf6gbb:b-1z0fwn)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`tools/workspace/voxelized_geometry_tools/package.BUILD.bazel` line 108 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19729#-N_BtO-M1Fc5MxIz6WgT:-N_DLhqB5NlJUWb2XS1V:b-youkh6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b910e74821b31468df29f96542f38c4d0f7c97df/tools/workspace/voxelized_geometry_tools/package.BUILD.bazel#L108)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The dispatch process uses multiple threads, but relatively little work is performed on the CPU versus the GPU. Additionally, most (all?) OpenCL implementations end up serializing kernels, so aside from the float packing performed on the CPU, one of those threads is most likely going to be waiting to dispatch its kernel until the other kernel is complete. Using `cpu:2` here is just being conservative.

As for the CRU planning test, there is now a `std::async`-based fallback for KNN when OpenMP isn't available, so the nearest neighbor checks of the PRM and RRT planners are still parallelized.
</blockquote></details>

r7 additionally adds a `std::async`-based fallback to the CPU voxelizer, so two threads will be used in non-OpenMP cases by the CPU voxelizer as well.

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Did you want me to squash as-is (with an attempt to curate the commit message), or is there one you wanted to see?

My naive attempt:

> Bump CRU and VGT with new DegreeOfParallelism API
>
> The new DegreeOfParallelism API to control the number of threads used in all parallelized operations. Formerly all of these uses in CRU and VGT allowed OpenMP to determine the number of threads automatically; while convenient, this makes it annoying to limit and difficult to nest parallelism effectively. The new API allows the user to specify an explicit number of threads to use in each operation (generally consumed via an OpenMP num_threads clause). This is particularly useful for motion planning users, who want to specify specific numbers of threads to use when running multiple planners in parallel or using Parallel-(Bi)RRT.
> Future PRs will introduce a public type that is compatible with DegreeOfParallelism to users to easily control the number of threads in use.
>
> Upgrade CRU and VGT to latest commit
> Roll up testing of CRU and VGT testing into test suite
> Ensure tests use multiple threads

**Comment by calderpg-tri** [comment]
I'll write the squash commit message. I'd like to hold off a little bit on merging to let anzu 10656 be ready to go.

**Comment by EricCousineau-TRI** [comment]
'aight, will add `do not merge` pending that.

**Pull request merged**
