### PR TITLE
Bushing example of 2D closed-loop linkage mechanism (robotic finger) with controller

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15734)

### CODE REVIEW

**Comment by mitiguy** [comment]
I mangled the commits on PR #15226 so I restarted the work as PR #15734.

**Comment by jwnimmer-tri** [comment]
This seems like it will have nice instructional value.  Is there any plan or timeline to continue work on it?

**Comment by sherm1** [comment]
Attn @mitiguy !

**Comment by mitiguy** [comment]
Glad to hear this is moving up in importance.  Got it.

**Comment by mitiguy** [comment]
Closed this for now to save Jenkins some cycles.

**Pull request closed without merging**
