### PR TITLE
Define enough of RightOfWayRule to specify dynamic state interface.

### PR DESCRIPTION
**Pull request by maddog-tri**
This is the first piece of the maliput RoadRulebook API to land.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8057)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5FDt4OffEQFJLoL4eR:bltds52)*

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[automotive/maliput/api/BUILD.bazel, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HUrK0j8_7LFBJiQGj:-L5HUrK0j8_7LFBJiQGk:bgf0c4b) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/BUILD.bazel#L57)):*
> ```Python
> 
> drake_cc_googletest(
>     name = "rules_wip_test",
> ```

Does "wip" stand for "work in progress"? If so, let's remove it from the name and add a TODO comment in the file explaining how it's a work in progress.

Or, are you planning on removing `rules_wip_test.cc`?

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5GUUAYaA2qTtfgJ-iU:-L5GUUAYaA2qTtfgJ-iV:bcprkfk) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L16)):*
> ```objc
> /// Right-of-way rules cover things like stop signs, yield signs, and
> /// traffic lights:  in other words, control over how competing traffic
> /// flows take turns traversing regions of the the road network.
> ```

extra "the".

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HVVYT-AKaEVMFAZAK:-L5HVVYT-AKaEVMFAZAL:b-69mpcw) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L24)):*
> ```objc
> ///   traversing the controlled-zone.
> /// The type may be "dynamic", in which the semantic state is delegated to
> /// an RightOfWayStateProvider agent.
> ```

BTW, consider documenting that the link between the rule and provider is via the rule's ID.

I see it's documented in below but might as well mention it here as well since this is typically read first.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5GVFBet7aCdIBtSLnG:-L5GVFBet7aCdIBtSLnH:beyogjj) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L26)):*
> ```objc
> /// an RightOfWayStateProvider agent.
> ///
> /// The controlled-zone is exclusionary.  A rule instance determines whether
> ```

I'm struggling to figure out how "exclusionary" is used in this context. Is it saying that rules apply at the border of the rule's controlled zone?

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW0OseX9znR3Trc50:-L5HW0OseX9znR3Trc51:bmjxrg) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L37)):*
> ```objc
>   ///  * kProceed:  no restriction on vehicle's right-of-way, but it must still
>   ///               avoid stopping within the controlled-zone;
>   ///  * kYield:  vehicles must yield to competing traffic
> ```

Missing semi-colon (to be consistent with the other bullets).

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW6EClYMCOZO7OHJu:-L5HW6EClYMCOZO7OHJv:b-uacqev) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L38)):*
> ```objc
>   ///               avoid stopping within the controlled-zone;
>   ///  * kYield:  vehicles must yield to competing traffic
>   ///  * kStopThenGo: vehicles must come to complete stop before entering
> ```

Missing "a" after "to".

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW9CiE4M6Qn3szev-:-L5HW9CiE4M6Qn3szev0:b-jshnna) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L39)):*
> ```objc
>   ///  * kYield:  vehicles must yield to competing traffic
>   ///  * kStopThenGo: vehicles must come to complete stop before entering
>   ///                 controlled-zone, but may then proceed if safe;
> ```

Missing "the" before "controlled-zone".

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HWVQD1HFz4OM85Y7P:-L5HWVQD1HFz4OM85Y7Q:b-flv5rm) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L40)):*
> ```objc
>   ///  * kStopThenGo: vehicles must come to complete stop before entering
>   ///                 controlled-zone, but may then proceed if safe;
>   ///  * kDynamic:  delegate semantics to a dynamic RightOfWayStateProvider,
> ```

BTW, consider deleting "dynamic".

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5FtQ2EzyqSqXFZE3f7:-L5FtQ2F_FceB2k6r2MY:b-aqi7ms) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L47)):*
> ```objc
>   // TODO(maddog@tri.global) Add explicit yield-to-whom semantics.
>   enum class Type {
>     kProceedWithCaution = 0,
> ```

Should be `kProceed`.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYywKv1kj8i3uwNlI:-L5HYywKv1kj8i3uwNlJ:b3i2iy3) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L55)):*
> ```objc
>   /// Rule semantics which may be expressed via a dynamic agent.
>   ///
>   /// * kUncontrolled:  signalling apparatus is non-functional (e.g.,
> ```

typo: signaling

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HX4LF-ON7kxanu73u:-L5HX4LF-ON7kxanu73v:b-afeuwk) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L64)):*
BTW, consider expanding upon this since it's the exact same text as `kGo`. Maybe:

> vehicle has right-of-way but faces a higher than usual chance of being cut-off by an inconsiderate agent.

(Oh, I later read your TODO comment below. Feel free to ignore.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYvteRqFIXJTLwRCt:-L5HYvteRqFIXJTLwRCu:b-kwyh7u) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L69)):*
> ```objc
>   ///                controlled-zone, but may then proceed if safe;
>   // TODO(maddog@tri.global) Better define fallback semantics of "dark-mode".
>   // TODO(maddog@tri.global) Better distiguish Go, Caution, Yield
> ```

typo: distinguish

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYMkc5brnoSZ2mFWJ:-L5HYMkc5brnoSZ2mFWK:b-5jfr7v) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L102)):*
> ```objc
> 
> 
> /// Abstract interface for the provider of the dynamic semanatic state of
> ```

typo: semantic

---

*[automotive/maliput/api/test/rules_wip_test.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HZpQEGsASi643U7Oq:-L5HZpQEGsASi643U7Or:b-iid73v) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/test/rules_wip_test.cc#L35)):*
> ```cpp
> 
>   RightOfWayRule dut1(RightOfWayRule::Id("other_id"),
>                       RightOfWayRule::Type::kYield);
> ```

BTW, consider adding:

```
  EXPECT_EQ(dut1.id(), RightOfWayRule::Id("other_id"));
  EXPECT_EQ(dut1.type(), RightOfWayRule::Type::kYield);
```

---

*[automotive/maliput/api/test/rules_wip_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HZjRjRtulHB5t_AOd:-L5HZjRjRtulHB5t_AOe:bbhoyar) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/test/rules_wip_test.cc#L38)):*
> ```cpp
>   dut1 = source;
>   EXPECT_EQ(dut0.id(), RightOfWayRule::Id("dut_id"));
>   EXPECT_EQ(dut0.type(), RightOfWayRule::Type::kStopThenGo);
> ```

The above two lines should check `dut1`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5H_CLbKfFpK6PTLWIF:bl4rucz)*

**Comment by maddog-tri** [comment]
Comments addressed, PTAL.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[automotive/maliput/api/BUILD.bazel, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HUrK0j8_7LFBJiQGj:-L5PY5dJeb7McGOmE9ZK:b3fkicv) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/BUILD.bazel#L57)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Does "wip" stand for "work in progress"? If so, let's remove it from the name and add a TODO comment in the file explaining how it's a work in progress.

Or, are you planning on removing `rules_wip_test.cc`?
</blockquote></details>

Done.  (I renamed the file to simply `rules_test.cc`.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5GUUAYaA2qTtfgJ-iU:-L5PYbZPjZHraKpyPV6w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

extra "the".
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HVVYT-AKaEVMFAZAK:-L5PYupv8ny2wOsXWFSx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider documenting that the link between the rule and provider is via the rule's ID.

I see it's documented in below but might as well mention it here as well since this is typically read first.
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5GVFBet7aCdIBtSLnG:-L5PbR97ZdzWdVQdO8hP:b-lq42z) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I'm struggling to figure out how "exclusionary" is used in this context. Is it saying that rules apply at the border of the rule's controlled zone?
</blockquote></details>

Done.  (Removed that first confusing sentence, and clarified the rest.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW0OseX9znR3Trc50:-L5Pbd-ajlgsMzTig_j1:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Missing semi-colon (to be consistent with the other bullets).
</blockquote></details>

Done. 

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW6EClYMCOZO7OHJu:-L5Pbdb2sDvzrs-jExpp:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L38)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Missing "a" after "to".
</blockquote></details>

Done. 

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HW9CiE4M6Qn3szev-:-L5PbmG19sWKjd5pYiiW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L39)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Missing "the" before "controlled-zone".
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HWVQD1HFz4OM85Y7P:-L5PbqN0pHMQufSn1NDr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L40)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "dynamic".
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5FtQ2EzyqSqXFZE3f7:-L5Pbw-CdmUyW4zzIxuZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L47)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should be `kProceed`.
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYywKv1kj8i3uwNlI:-L5Pc6NfiCXPoEgpTHUh:bdd687p) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

typo: signaling
</blockquote></details>

Done.  (...though, both are accepted spelings _(HAR HAR!)_ in American English.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYvteRqFIXJTLwRCt:-L5Pc_NsyhSkbWlW0L4q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

typo: distinguish
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HYMkc5brnoSZ2mFWJ:-L5Pcc2gwo6GxFU0zzEV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/rules/right_of_way_rule.h#L102)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

typo: semantic
</blockquote></details>

Done.

---

*[automotive/maliput/api/test/rules_wip_test.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HZpQEGsASi643U7Oq:-L5PctYoYUb1klgG8pzt:bz6068s) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/test/rules_wip_test.cc#L35)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding:

```
  EXPECT_EQ(dut1.id(), RightOfWayRule::Id("other_id"));
  EXPECT_EQ(dut1.type(), RightOfWayRule::Type::kYield);
```
</blockquote></details>

(Nah... the `Accessors` test already ensures that the accessors work.  I suppose this could assert that the fields are _not equal_ to the final expected values at this point, to eliminate a chance of a false-positive, but that is probably overkill.)

---

*[automotive/maliput/api/test/rules_wip_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5HZjRjRtulHB5t_AOd:-L5PeD9n3f4DVrHGTQdD:b9qjkcr) ([raw file](https://github.com/robotlocomotion/drake/blob/03e8d4db55f00ce4bd3cf7f60e2291c8c3e38c2f/automotive/maliput/api/test/rules_wip_test.cc#L38)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The above two lines should check `dut1`.
</blockquote></details>

Done.

Gah... I hate that kind of mistake.  I went and split this into two tests, and cleaned up all the EXPECTs as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5PegvyH1qGNLcQcNHF:b-idmig1)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5PylNWz2o09uq10Dyk:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5Q-CiCgM-VogHjPFwk:bxwr5c8)*

**Comment by soonho-tri** [comment]
1st pass completed. PTAL.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q20UjSN3hvicqAM8P:-L5Q20UjSN3hvicqAM8Q:b-ywda96) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L19)):*
> ```objc
> ///
> /// Each rule instance comprises:
> /// * a controlled-zone, which specifies a contiguous longitudinal lane-wise
> ```

My understanding is that the `RightOfWayRule` class only provides `type` information for now without presenting "controlled-zone" information. Is it something to be added to the class, later (or will be provided as a separate class)?

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q5MTZiUMH2AL54mXY:-L5Q5MTZiUMH2AL54mXZ:b-lzos38) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L48)):*
> ```objc
>   //                          related to...
>   // TODO(maddog@tri.global) Add explicit yield-to-whom semantics.
>   enum class Type {
> ```

FYI (META), we can inline Doxygen comments for enum classes (as we have examples in Drake):

```c++
  enum class Type {
    kProceed,     ///< No restriction on vehicle's right-of-way, but it must still
                  ///  avoid stopping within the controlled-zone.
    kYield,       ///< vehicles must yield to competing traffic.
    kStopThenGo,  ///< vehicles must come to a complete stop before entering the
                  ///  controlled-zone, but may then proceed if safe
    kDynamic      ///< delegate semantics to a RightOfWayStateProvider, with state
                  ///  linked by the Id of this rule.
  };
```
which will give you:



Reference: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#memberdoc

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q6IQb5XJp98O0vdBy:-L5Q6IQb5XJp98O0vdBz:b-z42na) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L99)):*
> ```objc
>   // TODO(maddog@tri.global)  Define controlled_zone as
>   //                          LaneRoute controlled_zone_;
>   Type type_;
> ```

BTW, need `{}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5Q7iDrXzP6vyFZ1DHM:b4fpv7i)*

**Comment by maddog-tri** [comment]
Thanks.... Comments addressed, PTAL.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q20UjSN3hvicqAM8P:-L5QCSYsIKKG6kzOJWE-:bvr3ymh) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

My understanding is that the `RightOfWayRule` class only provides `type` information for now without presenting "controlled-zone" information. Is it something to be added to the class, later (or will be provided as a separate class)?
</blockquote></details>

As alluded to in a `TODO` below, a subsequent PR will add a `controlled_zone` field to this class, typed as a `LaneRoute` --- and that PR will also define `LaneRoute`.   (This was all left out of this PR in order to speed up making the type/state aspects available to Liang.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q5MTZiUMH2AL54mXY:-L5QOEONFNwP9n-i2P68:bmgmetz) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L48)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI (META), we can inline Doxygen comments for enum classes (as we have examples in Drake):

```c++
  enum class Type {
    kProceed,     ///< No restriction on vehicle's right-of-way, but it must still
                  ///  avoid stopping within the controlled-zone.
    kYield,       ///< vehicles must yield to competing traffic.
    kStopThenGo,  ///< vehicles must come to a complete stop before entering the
                  ///  controlled-zone, but may then proceed if safe
    kDynamic      ///< delegate semantics to a RightOfWayStateProvider, with state
                  ///  linked by the Id of this rule.
  };
```
which will give you:



Reference: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#memberdoc
</blockquote></details>

Awesome - Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q6IQb5XJp98O0vdBy:-L5QOK3jSZO5vIKapL-3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L99)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, need `{}`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5QOWE8KF8VeIBDt5cT:b-aqufe6)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-L5Q20UjSN3hvicqAM8P:-L5QP6FpHhVOam2-YAjI:blemowb) ([raw file](https://github.com/robotlocomotion/drake/blob/022c99e4886e722f772aeccdf97b295e66b598a4/automotive/maliput/api/rules/right_of_way_rule.h#L19)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

As alluded to in a `TODO` below, a subsequent PR will add a `controlled_zone` field to this class, typed as a `LaneRoute` --- and that PR will also define `LaneRoute`.   (This was all left out of this PR in order to speed up making the type/state aspects available to Liang.)
</blockquote></details>

I see. Good to know!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057#-:-L5QPIjkYN--LXptUXdD:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8057)*

**Pull request merged**
