### PR TITLE
Derivative Boundary conditions in Toppra::SolvePathParameterization 

### PR DESCRIPTION
**Pull request by sadraddini**
Toppra can handle non-zero `ṡ` (time-derivative of path parameter), but zero defaults were hard coded. This PR makes them an argument that the user can change.

The use case is obtaining trajectories with non-zero start/end velocities.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975)

### CODE REVIEW

**Comment by sadraddini** [comment]
+@hongkai-dai assigning you as you are familiar with the code. Feel free to reassign.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ggould-tri for platform review please, thanks!

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-:-O85EUa_7nSiX7TVxt3g:b-svovrs)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`multibody/optimization/toppra.h` line 121 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-O85E6PLEvXTeVWEeanh:-O85E6PLEvXTeVWEeani:bdoz8gk) ([raw file](https://github.com/RobotLocomotion/drake/blob/014ad6306bd902c15a99940869974ea875cee77b/multibody/optimization/toppra.h#L121)):*
> ```objc
>    */
>   std::optional<PiecewisePolynomial<double>> SolvePathParameterization(
>       const double s_dot_start = 0, const double s_dot_end = 0);
> ```

nit, no need to add `const` here for pass-by-value arguments.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-:-O87PqIlE7GXF9Gf_JOg:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`multibody/optimization/test/toppra_test.cc` line 115 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-O87RHxs2B0VCTdbfTVu:-O87RHxs2B0VCTdbfTVv:bjqasy2) ([raw file](https://github.com/RobotLocomotion/drake/blob/014ad6306bd902c15a99940869974ea875cee77b/multibody/optimization/test/toppra_test.cc#L115)):*
> ```cpp
>                                      Eigen::VectorXd::Constant(7, 10));
>   double s_dot_start = 0.7;
>   double s_dot_end = 0.4;
> ```

minor:  These are constant, and it would be clearer to say so since they're used for multiple purposes here.  (note that `kConst` naming style is optional in this case).



_Suggestion:_
```cpp
  const double s_dot_start = 0.7;
  const double s_dot_end = 0.4;
```

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`multibody/optimization/toppra.h` line 121 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-O85E6PLEvXTeVWEeanh:-O87o1Zz0iPf_6ZbMdYG:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/014ad6306bd902c15a99940869974ea875cee77b/multibody/optimization/toppra.h#L121)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, no need to add `const` here for pass-by-value arguments.
</blockquote></details>

Done
___
*[`multibody/optimization/test/toppra_test.cc` line 115 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21975#-O87RHxs2B0VCTdbfTVu:-O87o2jiAhxd2AujaLKM:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/014ad6306bd902c15a99940869974ea875cee77b/multibody/optimization/test/toppra_test.cc#L115)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  These are constant, and it would be clearer to say so since they're used for multiple purposes here.  (note that `kConst` naming style is optional in this case).
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21975)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Pull request merged**
