### PR TITLE
Revert "Simulation of a PID controlled second order plant."

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @amcastro-tri ,

The on-call build cop, @betsymcphail , believes that your PR #3288 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
mac-continuous, such as https://drake-jenkins.csail.mit.edu/view/Continuous/job/mac-clang-continuous-release/796/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3636)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
See #3635 for an attempt to fix this issue.

**Comment by jwnimmer-tri** [comment]
Confirm that the revert actually fixes it:
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

Matrix msvc executor flaked, retest (in prep for override-merge):
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
> Since the test is new, I wonder if reverting might be a little heavy-handed, but at least I suppose it should be disabled on OS X until it can be fixed.

@amcastro-tri has an opportunity to ask to fix-forward (e.g., disable or fix the test).  Absent that, the 60 minute grace period has been met, and we will merge this once the builds pass.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3636#-:-KSvSKuEzXtMAsBvzYiV:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Taking a look right now.

**Comment by amcastro-tri** [comment]
I found the problem and I will submit in a few minutes

**Comment by amcastro-tri** [comment]
I just pushed #3639.

**Pull request closed without merging**
