### PR TITLE
Reproduce the SCS program with python code.

### PR DESCRIPTION
**Pull request by hongkai-dai**
We can specify solver options standalone_reproduction_file_name to write a python script, that will reproduce the optimization program in SCS.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
:lgtm: with only very minor questions/requests.
+@sammy-tri for platform review, please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-:-OCwd-Di7NGSiNSP41nU:b-efjls4)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 407 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-OCwcreoAGCZrKiMnvws:-OCwcreoAGCZrKiMnvwt:b-yy9wff) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1856c250db21d1dbffbf038d44b0eef6777acd2/solvers/scs_solver.cc#L407)):*
> ```cpp
>     // kMaxThreads option.
>   });
>   options->CopyToSerializableStruct(scs_stgs);
> ```

why did this move down?  (it seems unrelated to the primary goal of the PR?)
___
*[`solvers/scs_solver.cc` line 320 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-OCwcNzK4v778yOtXqQH:-OCwcNzK4v778yOtXqQI:b-b832rm) ([raw file](https://github.com/RobotLocomotion/drake/blob/10423d225d7d29119467573e9dee8e475bb6e508/solvers/scs_solver.cc#L320)):*
> ```cpp
>   }
>   auto write_csc = [&](const Eigen::SparseMatrix<double>& mat,
>                        const std::string& name) {
> ```

btw -- I know it's only the 2nd occurrence, but rather than duplicate this should we move it to a shared location?
___
*[`solvers/scs_solver.cc` line 351 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-OCwce0t4bRzEizd6IDc:-OCwce0t4bRzEizd6IDd:b-r9b7hd) ([raw file](https://github.com/RobotLocomotion/drake/blob/10423d225d7d29119467573e9dee8e475bb6e508/solvers/scs_solver.cc#L351)):*
> ```cpp
>   };
>   out_file << fmt::format(
>       R"""(
> ```

nit: maybe it should be on the previous line?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes

___
*[`solvers/scs_solver.cc` line 320 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-OCwcNzK4v778yOtXqQH:-OD-H_O-BdqRHFOG4a02:b-quaxch) ([raw file](https://github.com/RobotLocomotion/drake/blob/10423d225d7d29119467573e9dee8e475bb6e508/solvers/scs_solver.cc#L320)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- I know it's only the 2nd occurrence, but rather than duplicate this should we move it to a shared location?
</blockquote></details>

Good call, I moved it to `matrix_util.h/cc`
___
*[`solvers/scs_solver.cc` line 407 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-OCwcreoAGCZrKiMnvws:-OD-I0bl3xhNEIPlYOez:bsd6w6l) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1856c250db21d1dbffbf038d44b0eef6777acd2/solvers/scs_solver.cc#L407)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why did this move down?  (it seems unrelated to the primary goal of the PR?)
</blockquote></details>

We need to move options->Respell done because it needs `A` matrix, which is not set until this line. Then I think it is better to put all the `scs_stgs` code together, so I move the whole block involving `scs_stgs` down after calling `A.makeCompressed()`.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
I'm out of time for today.   -@sammy-tri   Spilling to +@rpoyner-tri for tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-:-OD8_ytS77d4Or6311g_:bvwst0f)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: some minor points

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-:-ODDBYQz9EeceTDBehZS:b2bwjwr)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`math/matrix_util.h` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD6faPDT2KvbpQDnj4:-ODD6faPDT2KvbpQDnj5:b-b8u5j7) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/matrix_util.h#L256)):*
> ```objc
> }
> 
> /// Generate the python code to construct scipy.sparse matrix.
> ```

minor Maybe the doc should say you are constructing a call to `scipy.sparse.csc_matrix()` specifically. It took me a little bit of docs reading to figure out whether `GeneratePythonCsc` was a good enough name.
___
*[`math/matrix_util.cc` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD79oNB2glgkRFDs2-:-ODD79oNB2glgkRFDs20:b-m6kfg9) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/matrix_util.cc#L8)):*
> ```cpp
> namespace math {
> void GeneratePythonCsc(const Eigen::SparseMatrix<double>& mat,
>                        std::string_view name, std::ofstream* python_stream) {
> ```

minor is there any reason that the output stream has to be an `ofstream` here? could it just be `ostream`? That would let you write unit tests against `stringstream` and avoid a bunch of unit-test file handling.
___
*[`math/test/matrix_util_test.cc` line 260 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD8qsl6AUyS6_C0d0K:-ODD8qsl6AUyS6_C0d0L:bt8ptub) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/test/matrix_util_test.cc#L260)):*
> ```cpp
>   std::getline(file, line);
>   file.close();
>   EXPECT_EQ(line,
> ```

nit consider if `EXPECT_THAT(blah, ::testing::MatchesRegex(blah))` or `EXPECT_THAT(blah, ::testing::HasSubstr(blah))` would be nicer. They might save having to do the line extraction above.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-:-ODDCx0X5JaEl9hkggm2:b-l8xbmn)* status: 3 unresolved discussions

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223)* status: 1 unresolved discussion

___
*[`math/matrix_util.h` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD6faPDT2KvbpQDnj4:-ODDaJlC1UKST32weWPv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/matrix_util.h#L256)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor Maybe the doc should say you are constructing a call to `scipy.sparse.csc_matrix()` specifically. It took me a little bit of docs reading to figure out whether `GeneratePythonCsc` was a good enough name.
</blockquote></details>

Done.
___
*[`math/matrix_util.cc` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD79oNB2glgkRFDs2-:-ODDrhtlAdgImcMIUxJS:b-yh16lj) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/matrix_util.cc#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor is there any reason that the output stream has to be an `ofstream` here? could it just be `ostream`? That would let you write unit tests against `stringstream` and avoid a bunch of unit-test file handling.
</blockquote></details>

Done. Good call!
___
*[`math/test/matrix_util_test.cc` line 260 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD8qsl6AUyS6_C0d0K:-ODDrsar4-uvVEjIXbr5:b-s95rg4) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/test/matrix_util_test.cc#L260)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider if `EXPECT_THAT(blah, ::testing::MatchesRegex(blah))` or `EXPECT_THAT(blah, ::testing::HasSubstr(blah))` would be nicer. They might save having to do the line extraction above.
</blockquote></details>

I used std::ostringstream and now I don't need to extract the line. Do you think it is good now?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22223)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform)

___
*[`math/test/matrix_util_test.cc` line 260 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22223#-ODD8qsl6AUyS6_C0d0K:-ODHNPd02AB3hHGmI07q:b-u5kuu5) ([raw file](https://github.com/RobotLocomotion/drake/blob/7bc7cb572c1a3d584ac36c9d28866fb49465e4ba/math/test/matrix_util_test.cc#L260)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I used std::ostringstream and now I don't need to extract the line. Do you think it is good now?
</blockquote></details>

Yup, looks great!

**Pull request merged**
