### PR TITLE
Updated URDF Parser Methods that Load String To Not Overload Each Other

### PR DESCRIPTION
**Pull request by liangfok**
This is half way towards resolving #3545.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3576)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please.

**Comment by liangfok** [comment]
The `linux-gcc-experimental-matlab-ros` CI test flaked with the following error:

```
Build timed out (after 240 minutes). Marking the build as aborted.
```

@drake-jenkins-bot linux-gcc-experimental-matlab-ros please.

**Comment by liangfok** [comment]
+@naveenoid for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSbH2yXgQRk36-Ocw4X:b-jlfufc)*

**Comment by naveenoid** [comment]
:lgtm: except for some cosmetic issues.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1082 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSfb-5igrOtHu59DKzp:-KSfb-5igrOtHu59DKzq:b-q6ikna) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.cc#L1082)):*
> ```cpp
> }
> 
> // TODO(liang.fok) Remove this deprecated method prior to Release 1.0.
> ```

BTW : 
Are deprecated method comments only noted in the source and not the header?

---

*[drake/systems/plants/parser_urdf.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSfbhZmk4evfWWwZsh_:-KSfbhZmk4evfWWwZsha:bmot292) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.h#L68)):*
> ```objc
>  */
> DRAKERBM_EXPORT
> ModelInstanceIdTable AddUrdfStringRpyToWorld(
> ```

BTW : just a suggestion for a method name change : 
AddUrdfStringRpyJointToWorld

---

*[drake/systems/plants/parser_urdf.h, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSf_kZwbtZsZFNtvP-T:-KSf_kZwbtZsZFNtvP-U:b-t5twb3) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.h#L105)):*
> ```objc
>     const std::string& urdf_string,
>     std::map<std::string, std::string>& package_map, RigidBodyTree* tree);
> ```

The documentation of this method is nearly identical to the AddUrdfStringRpyToWorld method. What distinguishes the $Ros method? Is it only a question of usage within a Ros-Drake application?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSfbsf75B5_RBrdq2WK:bc1jsps)*

**Comment by liangfok** [comment]
@naveenoid, thanks for the review. I've addressed your comments. PTAL.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1082 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSfb-5igrOtHu59DKzp:-KSgVBOOBGnYrN-zGXsK:b-v7tyr6) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.cc#L1082)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : 
> Are deprecated method comments only noted in the source and not the header?
</details>
The header includes `DRAKE_DEPRECATED()` declarations. This should be sufficient right?

---

*[drake/systems/plants/parser_urdf.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSfbhZmk4evfWWwZsh_:-KSgWLUk89UZbmyY1Qf2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.h#L68)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : just a suggestion for a method name change : 
> AddUrdfStringRpyJointToWorld
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSf_kZwbtZsZFNtvP-T:-KSgXA4CepE9XDQEQPml:b-6f9s5n) ([raw file](https://github.com/robotlocomotion/drake/blob/97818bed8cd0e2f9cb9827dcfdd13d70b089ba66/drake/systems/plants/parser_urdf.h#L105)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> The documentation of this method is nearly identical to the AddUrdfStringRpyToWorld method. What distinguishes the $Ros method? Is it only a question of usage within a Ros-Drake application?
</details>
I've updated the documentation. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSgXaRNJxdg5sfZ3dB2:b6y44l9)*

**Comment by naveenoid** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576)*

**Comment by liangfok** [comment]
+@david-german-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSgszebV1qjOXbjGVpU:b-buchxz)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShAF1AoQTD-yckizbU:-KShAF1BKES3wss4pFCk:b-1bof88) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L68)):*
> ```objc
>  */
> DRAKERBM_EXPORT
> ModelInstanceIdTable AddUrdfStringRpyJointToWorld(
> ```

BTW, it's hard to guess what this means with so many nouns and so few prepositions.  Consider: `AddUrdfFromStringWithRpyJointToWorld` or just `AddUrdfWithRpyJoint`

---

*[drake/systems/plants/parser_urdf.h, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSgwLddIuOne5ajdpa4:-KSgwLddIuOne5ajdpa5:b-3932hf) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L71)):*
> ```objc
>     const std::string& urdf_string, RigidBodyTree* tree);
> 
> #ifndef SWIG
> ```

BTW, I assume this is because `DRAKE_DEPRECATED` doesn't compile under swig for some reason?  That's annoying.

---

*[drake/systems/plants/parser_urdf.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShATRDSEzEfp_LnUud:-KShATRDSEzEfp_LnUue:bxos2iv) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L107)):*
> ```objc
>  */
> DRAKERBM_EXPORT
> ModelInstanceIdTable AddUrdfStringRpyJointToWorldRos(
> ```

BTW, ditto re. preposition deficit

---

*[drake/systems/plants/parser_urdf.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShY2QJlUYgHqama89J:-KShY2QJlUYgHqama89K:bjvm3xo) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L107)):*
> ```objc
>  */
> DRAKERBM_EXPORT
> ModelInstanceIdTable AddUrdfStringRpyJointToWorldRos(
> ```

BTW, as a reader of a call site, I'm not sure what to expect from the `Ros` suffix here.  Is it correct that if you don't care about ROS, you shouldn't call this method?  If so, it's fine as-is.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576)*

**Comment by david-german-tri** [comment]
:lgtm:, this is an improvement from the perspective of call site clarity (which is the stated goal).  I think there might be room to improve further on the names, though, see BTWs below.

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KShYV2EWaCV-u3RPGVV:b-65z3po)*

**Comment by liangfok** [comment]
@david-german-tri: I addressed your comments. PTAL. Thanks.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShAF1AoQTD-yckizbU:-KSk4qL3zBuRXFu28KxU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L68)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, it's hard to guess what this means with so many nouns and so few prepositions.  Consider: `AddUrdfFromStringWithRpyJointToWorld` or just `AddUrdfWithRpyJoint`
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KSgwLddIuOne5ajdpa4:-KSk5IAHTOrYkVLBYN8i:b-i8tehv) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L71)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I assume this is because `DRAKE_DEPRECATED` doesn't compile under swig for some reason?  That's annoying.
</details>
Yeah. We unfortunately need #ifndef SWIG outside of the macro too:

https://reviewable.io/reviews/robotlocomotion/drake/2597#-KKyshnUyy05WVVvAuQd

---

*[drake/systems/plants/parser_urdf.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShATRDSEzEfp_LnUud:-KSk5KGrOWcyuhdrSvK1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L107)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, ditto re. preposition deficit
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-KShY2QJlUYgHqama89J:-KSk5LXhqMq3OJb-2KvP:b9t76qn) ([raw file](https://github.com/robotlocomotion/drake/blob/b5f8b90026e3d8942c8d346dc25df2ce9bde68a2/drake/systems/plants/parser_urdf.h#L107)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, as a reader of a call site, I'm not sure what to expect from the `Ros` suffix here.  Is it correct that if you don't care about ROS, you shouldn't call this method?  If so, it's fine as-is.  
</details>
I updated the method name and documentation to be more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSk5SVkGitVwHTQLa8g:bairexf)*

**Comment by naveenoid** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSlNMmmUhIQgFQ5veMr:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Merging now.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3576#-:-KSlPMReraX3khewYYip:b4joi5f)*

**Pull request merged**
