### PR TITLE
Shallow clone snopt git repo when branch or tag is specified

### PR DESCRIPTION
**Pull request by jamiesnape**
Note that commits that exist not on a branch and only as a tag and must now use the tag argument rather than the commit argument.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11791)

### CODE REVIEW

**Comment by jamiesnape** [comment]
pycodestyle and buildifier appear to completely disagree how to wrap
```py
if (not branch and not commit and not tag) or (commit and tag) or (branch and tag) or (branch and commit):
    fail("Exactly one of branch, commit, or tag must be provided.")
```

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Ready for re-review, I think. I can simplify a little if you don't mind not deferring any errors with applying patches (not sure there is as much need to defer now that there is `cquery` anyway).

**Comment by jamiesnape** [comment]
> (3) Open a Bazel PR to fix git_worker.bzl.

Like this?

https://github.com/bazelbuild/bazel/compare/master...jamiesnape:git-worker-fetch-all-tags

**Comment by jamiesnape** [comment]
So the precise regression is that you cannot specify *by commit* a commit that exists not on a branch, but only as tag?

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Pull request merged**
