### PR TITLE
Add an OS X debugging workaround.

### PR DESCRIPTION
**Pull request by david-german-tri**
See https://github.com/bazelbuild/bazel/issues/2537

@soonho-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5334)

### CODE REVIEW

**Comment by soonho-tri** [comment]
This is nice and looking great!
I'll test things on my mac this afternoon.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke-uYcgEHd8M1nhuOZN:b4j0oxz)*

**Comment by soonho-tri** [comment]
@david-german-tri , I've tried it on my machine. Somehow it didn't work as expected but after some builds, it started working. I've figured out a way to reproduce my issue. PTAL.

The following works:
```
bazel clean
bazel build --config=apple_debug //drake/common:symbolic_expression_test
lldb ./bazel-bin/drake/common/symbolic_expression_test
```

The following doesn't work:
```
bazel clean
bazel build -c dbg //drake/common:symbolic_expression_test
bazel build --config=apple_debug //drake/common:symbolic_expression_test
lldb ./bazel-bin/drake/common/symbolic_expression_test
```

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke06RGrPcRKP3bnGD0A:b-n47jh1)*

**Comment by david-german-tri** [comment]
@soonho-tri Ah, interesting.  Disabling the sandbox does not invalidate the cache.  Let me see if I can patch that, but if not, I guess we'll document another `bazel clean`.  :-(

**Comment by soonho-tri** [comment]
It's be great if we can have `--config=apple_debug` by default for Mac when we enable `-c dbg`. If it's difficult to have that in `bazel.rc` file, I'm happy to have `.bazelrc` set-up for that (and we can document that here?).

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke08eCN_CdPNkk5pbzW:bkfku4)*

**Comment by david-german-tri** [comment]
> Disabling the sandbox does not invalidate the cache. Let me see if I can work around that

done, PTAL

> It's be great if we can have --config=apple_debug by default for Mac when we enable -c dbg. 

Sadly, no, that's semantically backwards.  `--config` can control the values of other Bazel flags, but `--c[ompilation_mode]` can't. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke0BnfeAbPJxoD9Uc5k:bb55xit)*

**Comment by soonho-tri** [comment]
:lgtm: Fantastic!!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke0PefqKwWNy9jxocWm:b6h89d8)*

**Comment by david-german-tri** [comment]
+@russtedrake for platform review, since you volunteered on Slack to be the guinea pig

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke0SVOl93ovu9jxnrlr:b-tcyj56)*

**Comment by RussTedrake** [comment]
:lgtm: 
tested.  i *think* it worked.  lldb shows more symbols.  thank you!!  

gdb looks like it gets farther than before?  (working from memory here):
```
Reading symbols from bazel-bin/drake/automotive/trajectory_optimization_test...done.
```
but still barfs when I go to actually run:
```
(gdb) run
Starting program: /private/var/tmp/_bazel_russt/3e477aa1673e9c80e91d410bb65d1970/execroot/drake-distro/bazel-out/osx-dbg/bin/drake/automotive/trajectory_optimization_test
During startup program terminated with signal ?, Unknown signal.
```

is there a way to make the clion integration call --config=apple_debug instead of -c dbg?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1ZpE-ht5x5L5w7ZG9:bphwpsz)*

**Comment by soonho-tri** [comment]
Hi Russ ,

I think one way is to have the following line at `~/.bazelrc` file:

```
build --config=apple_debug
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1c996c0zs_HKKKFdh:bcgghr0)*

**Comment by RussTedrake** [comment]
would that mean that it's always compiling in debug mode, though?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1cqsdb2GQ5s-2gDx5:bhgdq3q)*

**Comment by soonho-tri** [comment]
That's correct.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1d-KQV5ppJUy1JiqE:bmwtcq4)*

**Comment by soonho-tri** [comment]
FYI, I've asked David this before:

>> It'd be great if we can have --config=apple_debug by default for Mac when we enable -c dbg.

> Sadly, no, that's semantically backwards. --config can control the values of other Bazel flags, but --c[ompilation_mode] can't.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1d6Xcqh-yzWbS1vOA:b-tjjd9f)*

**Comment by jwnimmer-tri** [comment]
Note that "Can `-c dbg` imply `--config apple_debug`?" and "Can we setup CLion to use `--config apple_debug` before running the debugger?" are two separate questions.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , that's right.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke1eAK2uCPLEXtQSdOe:b-dnhj7r)*

**Comment by david-german-tri** [comment]
> is there a way to make the clion integration call --config=apple_debug instead of -c dbg?

@russtedrake @soonho-tri Could you try adding `--config=apple_debug` to the "Bazel flags" field in your CLion "Run/Debug Configurations"?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke4oK6fK-ioA8zsgoUz:ba5xgxj)*

**Comment by david-german-tri** [comment]
> tested.  i *think* it worked. 

If you can `breakpoint set -f foo.cc -l 42` now, and you couldn't before, then it worked.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke4oitcfvTEWSPab28x:bot35ji)*

**Comment by david-german-tri** [comment]
> gdb looks like it gets farther than before? ... but still barfs when I go to actually run:

I'll try to reproduce this when I'm next in front of a mac with a codesigned gdb.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5334#-:-Ke4pnw7r-Wcd_UFIy0U:b-l9okmi)*

**Pull request merged**
