### PR TITLE
remove all swig-generated matlab bindings

### PR DESCRIPTION
**Pull request by rdeits**
This PR deletes the swig-generated MATLAB bindings from drake. They haven't (as far as I'm aware) had any users, and are currently what's forcing us to use `swig_matlab` instead of upstream swig. 

Note that this does not yet remove the `swig_matlab` dependency (sorry). That will have to wait until we've:
- [ ] determined whether swig 3.0.11 solves our C++ 11 issues
- [ ] decided how to pull in swig 3.0.11 from upstream

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4869)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4869#-:-KbCP3Kj6W0gSbrJr9wa:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@jamiesnape +@david-german-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4869#-:-KbCPjtMP8b1Hpa1LdzB:b6p47td)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4869#-:-KbCPtHNNzLaSG7zpNT7:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
FWIW -- it appears that the `addpath_drake.m` is still trying to add `bindings/matlab` to the path, leading to (I think) harmless warnings in CI and for users.

**Comment by rdeits** [comment]
@jwnimmer-tri good point, thanks. Should be fixed in #4891

**Pull request merged**
