### PR TITLE
[doc] Fix formatting of v0.32.0 notes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15393)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri xor +@ggould-tri for review, whoever get here first?

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  Confirmed that it looks right in the github markdown view.  Didn't build the website view.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15393#-:-Mea99j1EfEwNP1tLSTQ:bisa37s)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  Loving the italic backslashes.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15393#-:-Mea9YcL2hQiqRmYySRI:b-d2c65x)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Forced in.

**Pull request merged**
