### PR TITLE
Avoid unnecessary re-computation of deformable sdf

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20347)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +@DamrongGuoy can you take a look and see if this makes sense? 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-:-NgUmHlS6fWg_QFN8hdV:b-4wllgr)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) +@sherm1 for platform review. Please feel free to punt it to tomorrow's reviewer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-:-NgW2rg16gRCoVkbiaQQ:b-5ltiek)* status: LGTM missing from assignee sherm1(platform)

___
*[`geometry/proximity/deformable_contact_internal.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-NgV0EgeC_9-amHH1N47:-NgW1syh3lOI70JJ2VKQ:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb9ab62f756d76aa5b3b65336c0b1b8a3c3b1c67/geometry/proximity/deformable_contact_internal.cc#L63)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Should we help readers by specifying the type?
</blockquote></details>

Done
___
*[`geometry/proximity/deformable_mesh_intersection.h` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-NgV41uS8ebTHBQYC0OD:-NgW1xjCCsYRwQYpYn5J:bopk51i) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb9ab62f756d76aa5b3b65336c0b1b8a3c3b1c67/geometry/proximity/deformable_mesh_intersection.h#L21)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I've a question about frames.  Do we want to use frame D? Or do we assume deformable_sdf and deformable_mesh will always be in World frame?  I'm satisfied with one of these three options, including keeping it as is:

1. right now: `deformable_sdf`, `deformable_mesh`
2. continue to use D: `deformable_sdf_D`, `deformable_mesh_D`
3. explicitly use World frame: `deformable_sdf_W`, `deformable_mesh_W`
</blockquote></details>

Done . We usually use D for deformable with the implicit assumption that all deformable frames are world frames. This assumption may change in the future.

**Review by sherm1 — COMMENTED** [review]
Timed out. -@sherm1 +@sammy-tri for Thursday platform review, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-:-NgWNfpsB2hs04POGTjR:b-86j34b)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20347#-:-NgZrQ4s9DUKDDumu3-3:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),DamrongGuoy

**Pull request merged**
