### PR TITLE
Port plants to default_scalars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7097)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.
+@soonho-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/spring_mass_system/spring_mass_system.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-Kuucpm2qdfoYN4tlmLJ:-Kuucpm2qdfoYN4tlmLK:byng67m) ([raw file](https://github.com/robotlocomotion/drake/blob/fa3b2c586086a915faf6a769512e3fe6826753d5/drake/systems/plants/spring_mass_system/spring_mass_system.cc#L8)):*
> ```cpp
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/common/symbolic.h"
> #include "drake/systems/framework/basic_vector.h"
> ```

BTW, No need to delete this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/spring_mass_system/spring_mass_system.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-Kuucpm2qdfoYN4tlmLJ:-Kuud9-soCYUkz_p3iM9:bnuf1ob) ([raw file](https://github.com/robotlocomotion/drake/blob/fa3b2c586086a915faf6a769512e3fe6826753d5/drake/systems/plants/spring_mass_system/spring_mass_system.cc#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, No need to delete this?
</blockquote></details>

You mean the `basic_vector.h`?  It's already included by the header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097)*

**Comment by soonho-tri** [comment]
*[drake/systems/plants/spring_mass_system/spring_mass_system.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-Kuucpm2qdfoYN4tlmLJ:-Kuudlwk92MroNjo1O9j:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/fa3b2c586086a915faf6a769512e3fe6826753d5/drake/systems/plants/spring_mass_system/spring_mass_system.cc#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You mean the `basic_vector.h`?  It's already included by the header file.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-:-Kuudpn53O2uPpYzNL7O:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/spring_mass_system/spring_mass_system.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-KuuhpWVCfI4reLMKEaE:-KuuhpWWHI7ZBFLmS0wB:baqcad4) ([raw file](https://github.com/robotlocomotion/drake/blob/1ad3253a20df42d789e63ff96c7314d304bae13f/drake/systems/plants/spring_mass_system/spring_mass_system.cc#L200)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_SCALARS(
> ```

Typo INSTIATIONS; will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7097#-:-KuyfRb2N3pm9gz9vdsS:bnfp4nl)*

**Pull request merged**
