### PR TITLE
Add compiler-specific warnings in Bazel.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4717)

### CODE REVIEW

**Comment by david-german-tri** [comment]
I'm not exactly in love with this approach, but it seems to work on both OS X and Ubuntu.  @jwnimmer-tri for initial feature review.  I've also opened https://github.com/bazelbuild/bazel/issues/2358

**Comment by jwnimmer-tri** [comment]
First pass done.

I will probably wait for one round of any edits you elect to do, and after that work on stress testing it locally.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFSwcIhCeHCmfnqtZj:-KaFSwcJFHX6-6wFqBSo:b-1ak5d4) (no related file):*
Please run `tools/buildifier.sh` to format this PR.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFTQvwTlf_e2odHfCR:-KaFTQvxLihjdxU7zo-N:b-1otk5a) (no related file):*
FYI Probably not worth attempting in this same PR, but I wonder if this toolchain shim would let us do better on #4464.  I guess if `local_config_cc` has already finished it may be too late.  Maybe we can still fail-fast and report a good error, though.

---

*[tools/amend_crosstool.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFPDAUZful8QWD-8A8:-KaFPDAUZful8QWD-8A9:b-dletkr) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

*Meta* This file mixed tabs and spaces for indent.

Also lines are >80 and while that's not a rule I guess, it's better for reviewable to keep it all <80.

---

*[tools/amend_crosstool.sh, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFPXhwlZSOtUljYyj9:-KaFPXhwlZSOtUljYyjA:b-t5mgfx) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L10)):*
> ```Shell
> # It also may not be the right thing to do, since it forces our flag choices onto all
> # the externals.
> # TODO(david-german-tri): Improve this if possible.
> ```

Add citation to bazelbuild/build#2358 discussion?

---

*[tools/amend_crosstool.sh, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFR6Ou4pKkrvh4dB3c:-KaFR6Ou4pKkrvh4dB3d:b-s7vm27) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L20)):*
> ```Shell
>     | sed 's/cc_wrapper\.sh/.\/cc_wrapper.sh/' \
>     | grep -v '/bin/false' \
>     > $compiler_version_commands
> ```

BTW If you put the `|` on the prior line, you don't need the `\`s; it will continue the line for you.

---

*[tools/amend_crosstool.sh, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFQnx9GfC5oGPTI5-6:-KaFQnx9GfC5oGPTI5-7:b-edfdsq) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L24)):*
> ```Shell
> has_gcc=$?
> source $compiler_version_commands | grep clang > /dev/null
> has_clang=$?
> ```

BTW Consider confirming that the exitcode of the `source ...` portion was success (zero)?  Also that would let you only run it once (to a tmpfile) and then grep twice.

---

*[tools/amend_crosstool.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFRkTjhhc1vYsxks3q:-KaFRkTkXBY8rXstAezd:b-1xev6q) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L36)):*
> ```Shell
> 	# Assemble additional warnings for gcc.
> 	echo '  # Additional GCC warnings from amend_crosstool.sh' >> $extra_warnings
> 	echo '  cxx_flag: "-Werror=extra"' >> $extra_warnings
> ```

BTW Should we read these from a one-per-line text file like `drake-distro/tools/gcc-cxxopts.txt` that the repository rule could reference?  That might be easier for developers to maintain over time.  Actually, I guess all of the echo'd content could just be in a file, cxx_flag goop and all.  Then this script just has to chose which txt file to use and then wedge it in place.

---

*[tools/amend_crosstool.sh, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFRcpXOU7t1yLtK9KW:-KaFRcpYcusbjxOcsR17:b-8wajex) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L43)):*
> ```Shell
>     # Inject the warnings into the "local" configuration.
>     sed -i -e "/^toolchain {/r ${extra_warnings}" CROSSTOOL
> 	exit 0
> ```

BTW De-duplicate the above three lines between the two cases that share them?

---

*[tools/bazel.rc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFIkPUmtNK0Z-jozfn:-KaFIkPVvuFdfmmNzbLO:bbkyfq8) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/bazel.rc#L9)):*
> ```
> build --crosstool_top=//external:drake_toolchain
> 
> # Compilation flags that apply on all supported compilers.
> ```

BTW Consider a comment citation for where to place new warning flags that are only for _some_ compilers?

---

*[tools/toolchain.bzl, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFP-u7YV3gO9ve4fAb:-KaFP-u7YV3gO9ve4fAc:bupnpmd) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/toolchain.bzl#L17)):*
> ```Python
>         print("toolchain.bzl: Failed to detect exactly one supported compiler.")
> 
> drake_toolchain_autoconf = repository_rule(
> ```

BTW I think the word `autoconf` here could be easily confused for GNU autoconf.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-:-KaFSb7Oqvfy9zajnhGI:b-u9wyvb)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[tools/toolchain.bzl, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFWcWC44DZTEFWfse3:-KaFWcWDNbGXn7p9gdWj:binq6ph) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/toolchain.bzl#L8)):*
> ```Python
> 
> def _drake_toolchain_impl(repository_ctx):
>     repository_ctx.file("scratch", content="foo")
> ```

Unclear what purpose this serves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717)*

**Comment by david-german-tri** [comment]
Review status: 3 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFSwcIhCeHCmfnqtZj:-KaIMvrQ24YGOueN8CGv:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please run `tools/buildifier.sh` to format this PR.
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFTQvwTlf_e2odHfCR:-KaIN2Ku6hIsvpsxKTRP:b-4rsjjj) (no related file):*
> Maybe we can still fail-fast and report a good error, though.

Yes, we definitely could.

---

*[tools/amend_crosstool.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFPDAUZful8QWD-8A8:-KaIYGUdtAXrA11Ng7nc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

*Meta* This file mixed tabs and spaces for indent.

Also lines are >80 and while that's not a rule I guess, it's better for reviewable to keep it all <80.
</blockquote></details>

Done.

---

*[tools/amend_crosstool.sh, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFPXhwlZSOtUljYyj9:-KaIOfWZI7dwMvGGV72l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Add citation to bazelbuild/build#2358 discussion?
</blockquote></details>

Done.

---

*[tools/amend_crosstool.sh, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFR6Ou4pKkrvh4dB3c:-KaIO1S8CCDOdSswo11s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you put the `|` on the prior line, you don't need the `\`s; it will continue the line for you.
</blockquote></details>

Done.

---

*[tools/amend_crosstool.sh, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFQnx9GfC5oGPTI5-6:-KaIYFMQx3-cb_3O1d4T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider confirming that the exitcode of the `source ...` portion was success (zero)?  Also that would let you only run it once (to a tmpfile) and then grep twice.
</blockquote></details>

Done.

---

*[tools/amend_crosstool.sh, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFRkTjhhc1vYsxks3q:-KaIRoGuTDFbbNqGU8Ib:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should we read these from a one-per-line text file like `drake-distro/tools/gcc-cxxopts.txt` that the repository rule could reference?  That might be easier for developers to maintain over time.  Actually, I guess all of the echo'd content could just be in a file, cxx_flag goop and all.  Then this script just has to chose which txt file to use and then wedge it in place.
</blockquote></details>

Done.

---

*[tools/amend_crosstool.sh, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFRcpXOU7t1yLtK9KW:-KaIOqwed6pJvX6N8nRN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW De-duplicate the above three lines between the two cases that share them?
</blockquote></details>

Done.

---

*[tools/bazel.rc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFIkPUmtNK0Z-jozfn:-KaIRaWCOMEi1QFaD3nV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/bazel.rc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider a comment citation for where to place new warning flags that are only for _some_ compilers?
</blockquote></details>

Done.

---

*[tools/toolchain.bzl, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFWcWC44DZTEFWfse3:-KaITtLFzlYxXSCaCtJi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/toolchain.bzl#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear what purpose this serves.
</blockquote></details>

Done.

---

*[tools/toolchain.bzl, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFP-u7YV3gO9ve4fAb:-KaIU3_YDhjwF40Mr85R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/toolchain.bzl#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think the word `autoconf` here could be easily confused for GNU autoconf.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717)*

**Comment by jwnimmer-tri** [comment]
Alright, just a few more notes.  Next I will stress test it locally.  After these discussions have a response, probably a fine time to tag a second reviewer.

---

Reviewed 7 of 7 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/amend_crosstool.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaFPDAUZful8QWD-8A8:-KaIjFDrJcSzmo_9Cr2u:bbz548a) ([raw file](https://github.com/robotlocomotion/drake/blob/5968e53db31030ec7cd1fe9d0a7e762f04f4031d/tools/amend_crosstool.sh#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

These two intro paragraphs are still showing up >>80 in reviewable for me?

---

*[tools/amend_crosstool.sh, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaIkL2aeMhjPq131P_Q:-KaIkL2aeMhjPq131P_R:brum2sj) ([raw file](https://github.com/robotlocomotion/drake/blob/4033a56819a1e19596ba37d263115208067617ae/tools/amend_crosstool.sh#L26)):*
> ```Shell
> 
> compiler_versions=$(mktemp)
> source $compiler_version_commands > $compiler_versions
> ```

BTW *Meta* its always a bit safer to quote all variable-provided filenames, e.g. `"$compiler_version_commands"` and `"$compiler_versions"` and etc. below, in case the user is insane and their tmpdir has spaces in its path.

---

*[tools/amend_crosstool.sh, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaIl3bUA-xQk9YtIOsh:-KaIl3bUA-xQk9YtIOsi:b-mr6f5v) ([raw file](https://github.com/robotlocomotion/drake/blob/4033a56819a1e19596ba37d263115208067617ae/tools/amend_crosstool.sh#L42)):*
> ```Shell
> # cxx_flag field, and appends the result onto the second file.
> read_options_into() {
>     sed -e 's/^/  cxx_flag: "/' "$1" | sed -e 's/$/"/' >> "$2"
> ```

Does this script fail-fast when `gcc_options.txt` disappears or isn't sandboxed correctly somehow?  Otherwise it seems like we could silently lose warnings accidentally.

---

*[tools/BUILD, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaIjhAHtbHsH2zQ9ICq:-KaIjhAHtbHsH2zQ9ICr:bjzxoix) ([raw file](https://github.com/robotlocomotion/drake/blob/4033a56819a1e19596ba37d263115208067617ae/tools/BUILD#L40)):*
> ```Python
>         "gcc_options.txt",
>     ],
> )
> ```

BTW Both of these labels are public visibility.  I guess that's okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-:-KaIlYd-Er1tvtT_ZQP5:b-a9w35a)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/BUILD, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaIo4-IhM3SxId1ury8:-KaIo4-J_WMwFLq9fm7z:bd806vk) ([raw file](https://github.com/robotlocomotion/drake/blob/4033a56819a1e19596ba37d263115208067617ae/tools/BUILD#L30)):*
> ```Python
>     name = "amend_crosstool",
>     srcs = ["amend_crosstool.sh"],
>     deps = [":compiler_options"],
> ```

Huh, I would have thought this was at least `data`?  Or is it really just all data anyway, and amend_crosstool.sh should also just be in a filegroup and not a sh_binary?  I guess I don't know exactly how sandboxing works (or doesn't) for repository rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717)*

**Comment by jwnimmer-tri** [comment]
*[tools/BUILD, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-KaIo4-IhM3SxId1ury8:-KaIprksWAD3XKKdjoMz:b-3gegg0) ([raw file](https://github.com/robotlocomotion/drake/blob/4033a56819a1e19596ba37d263115208067617ae/tools/BUILD#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Huh, I would have thought this was at least `data`?  Or is it really just all data anyway, and amend_crosstool.sh should also just be in a filegroup and not a sh_binary?  I guess I don't know exactly how sandboxing works (or doesn't) for repository rules.
</blockquote></details>

Indeed, changing gcc_options.txt only has an effect the *second* time I run bazel.  I think the `repository_rule` has to declare its dependencies on all of the labels is uses as inputs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717)*

**Comment by jwnimmer-tri** [comment]
I take that back.  I'm going to stop testing, and we should defer additional review, until the PR correctly and immediately rebuilds everything when the files in this PR are edited.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-:-KaIrzXfieBj7IHkY95N:b96joec)*

**Comment by david-german-tri** [comment]
I agree.  Looking into it now.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4717#-:-KaJ0US9s9JkcJd6mmp7:b-ubz908)*

**Comment by david-german-tri** [comment]
It turns out there is no way to invalidate a repository_rule based on changes to a file that it references.  (Because we referenced a Label, we got invalidation of that Label on the second call to `bazel` after changes to a file included in the Label.)

I'm abandoning this approach in favor of (3) from bazelbuild/bazel#2358.

**Pull request closed without merging**
