### PR TITLE
SetZero() and PlusEqScaled() additions to VectorBase and BasicVector by edrumwri

### PR DESCRIPTION
**Pull request by edrumwri**
This is a duplicate of PR #3799, which was created to address a git rebase issue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3823)

### CODE REVIEW

**Comment by edrumwri** [comment]
+sherm1 for platform reviewer, +david-german-tri for feature reviewer

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-:-KUIxsxdpBu42f8BQhLH:bpz2t6h)*

**Comment by david-german-tri** [comment]
+@sherm1, +@david-german-tri

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-:-KUIyEo1QxRVkGAsoFHT:b2t6iw6)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-:-KUIy_fg8CbYpG2xX4cg:bnfp4nl)*

**Comment by sherm1** [comment]
Thanks for cleaning up the commits -- looks great now! One minor comment to address, then :lgtm:.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/subvector_test.cc, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-KUIzfNRPA1WjbnE8OcQ:-KUIzfNRPA1WjbnE8OcR:b-h6fqlp) ([raw file](https://github.com/robotlocomotion/drake/blob/fb631bd28535af96fe012e8de0abc28586bf2244/drake/systems/framework/test/subvector_test.cc#L123)):*
> ```cpp
> // Tests all += * operations for VectorBase.
> TEST_F(SubvectorTest, PlusEqScaled) {
>   Subvector<int> ogvec(state_vector_.get(), 0, kSubVectorLength);
> ```

BTW, from previous review: not clear what `ogvec` means. Please use a more descriptive name or add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-:-KUIzvzQLuph-3kcbFZF:bhmgrc)*

**Comment by edrumwri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/subvector_test.cc, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-KUIzfNRPA1WjbnE8OcQ:-KUJ0XVnHZnWhNBvpbiq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb631bd28535af96fe012e8de0abc28586bf2244/drake/systems/framework/test/subvector_test.cc#L123)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, from previous review: not clear what `ogvec` means. Please use a more descriptive name or add a comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-:-KUJ1U8lKyG6WwwkrikA:bnfp4nl)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/test/subvector_test.cc, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3823#-KUIzfNRPA1WjbnE8OcQ:-KUJ9mZZSEdtIgDfi5yv:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/fb631bd28535af96fe012e8de0abc28586bf2244/drake/systems/framework/test/subvector_test.cc#L123)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>
> Done.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3823)*

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-release please

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by sherm1** [comment]
CI rerun worked; override merging.

**Pull request merged**
