### PR TITLE
Add drake-lcm-spy utility

### PR DESCRIPTION
**Pull request by jamiesnape**
`bazel run //drake/lcmtypes:drake-spy` to run.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6412)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@sammy-tri for review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/lcm.bzl, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-KnGvjVA9vColybMz6jY:-KnGvjVA9vColybMz6jZ:b8mtnaa) ([raw file](https://github.com/robotlocomotion/drake/blob/bb1f40fb88644d029039eeec894fb7add99accec/tools/lcm.bzl#L127)):*
> ```Python
>     structs per file, then the parameter is required and must list every
>     `struct ...;` declared by lcm_srcs.
>     """
> ```

FYI Given that it looks like several of the pre-existing LCM C++ libraries in Drake were missing dependencies, would it be worth having `lcm_cc_library` here generate a test rule that proves `#include <newly_generated_header.h>` compiles on its own?  (That could be in a follow-up PR, of course.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-:-KnGwCwh6nyTc8lNrsEu:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.bzl, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-KnKbnnGa2CZ9fhcWFGL:-KnKbnnL_b--jKxhXpoA:b63bn5t) ([raw file](https://github.com/robotlocomotion/drake/blob/2950c64bd38f99a1b816121985ba725ef9654598/tools/lcm.bzl#L335)):*
> ```Python
>         if key not in CC_ONLY_ARGS:
>             cc_args[key] = value
> ```

Did you mean `java_args` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412)*

**Comment by jamiesnape** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.bzl, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-KnKbnnGa2CZ9fhcWFGL:-KnKgnL-oWM2U4_px2fq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2950c64bd38f99a1b816121985ba725ef9654598/tools/lcm.bzl#L335)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Did you mean `java_args` here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental  please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412)*

**Comment by RussTedrake** [comment]
can we call it `drake-lcm-spy` if lcm-spy is not appropriate? `drake-spy` feels insufficient.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-:-KnZCfZ2GYCUlGa2nIWd:b-3abcs4)*

**Comment by jamiesnape** [comment]
@RussTedrake Of course. Done.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-:-KnZWPj4HtnK6odFhTEI:b-6mshqg)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6412#-:-KnZkkAe7gTXpFMyxZfJ:bnfp4nl)*

**Pull request merged**
