### PR TITLE
[geometry] Generalize DeformableVolumeMesh

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #18922.

This commit does the following:

1. Change DeformableVolumeMesh to DeformableMeshWithBvh and templatize on mesh type to allow for other mesh types.
2. Create DeformableMesh to allow for meshes with changing vertex positions with the bvh structure.
3. Plumb through the change from DeformableVolumeMesh to DeformableMeshWithBvh at call sites.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
This allows to me use mesh deformer on TriangleSurfaceMesh without having to update Bvh.

+@SeanCurtis-TRI for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-:-Np1mglW5-mqeOhjLP6c:b-800tab)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-:-NpLfIJs0qP4R09MxDBh:bmxilld)* status: 12 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLN-nr12Iu1IaAZsNQ:-NpLN-nr12Iu1IaAZsNR:b-gj9pd) (no related file):*
Presumably this is going to have a conflict with #20813.  What's your plan for reconciliation? Presumably, files now in `geometry/` will be going into `geometry/mesh/`, right?

___
___
*[`geometry/deformable_mesh.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLNzz4Esi5MJ-hDXF2:-NpLNzz4Esi5MJ-hDXF3:b-o33vi5) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L1)):*
> ```objc
> #pragma once
> ```

BTW I get the sense that splitting `DeformableVolumeMesh` into two classes, `DeformableMeshWithBvh` and `DeformableMesh` is speculative, right? In my pass through, I didn't see any actual usage of `DeformableMesh` as a stand alone type (other than the fact that `DeformableMeshWithBvh` uses it).

Is there a particular application where you anticipate using the `DeformableMesh` type independently of `DeformablemeshWithBvh`? Presumably rendering?
___
*[`geometry/deformable_mesh.h` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPpgn4SGzLLNZRe6R:-NpLPpgo5PCLVJDC7aJr:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L17)):*
> ```objc
> /* Representation of a mesh whose vertices can be moved. Consider using
>  DeformableMeshWithBvh instead if you need a bounding volume hierarchy (BVH)
>  acceleration structure of proximity queries.
> ```

nit: typo



_Suggestion:_
```objc
for 
```
___
*[`geometry/deformable_mesh.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPtsBB_3bF09NWpee:-NpLPtsBB_3bF09NWpef:bnf3r47) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L19)):*
> ```objc
>  acceleration structure of proximity queries.
> 
>  This is currently a speculative feature and not formally supported by
> ```

nit: As with `DeformableMeshWithBvh`, let's nix this paragraph.  (Hey, there's a three-letter word for you.)
___
*[`geometry/deformable_mesh.h` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLQ6481P6ZCvWlC6PI:-NpLQ6481P6ZCvWlC6PJ:b5nltcq) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L53)):*
> ```objc
>   DeformableMesh& operator=(const DeformableMesh& other) {
>     if (this == &other) return *this;
>     mesh_ = other.mesh();
> ```

nit: Again, as with `DeformableMeshWithBvh`, some comments here about an in-place update so that the deformer's pointer remains valid.
___
*[`geometry/deformable_mesh.h` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPFm951phAN7IVNDR:-NpLPFm951phAN7IVNDS:blisoo1) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L86)):*
> ```objc
> 
> template <typename T>
> using DeformableTriangleSurfaceMesh = DeformableMesh<TriangleSurfaceMesh<T>>;
> ```

BTW I'd argue that "triangle" and "surface" mesh are redundant. Admittedly, a surface mesh can be strictly triangles or polygons -- that's a problem we don't have with the volume mesh (which, we've accepted will strictly be tetrahedra and not arbitrary polytopes). But, in the goal of a shorter name, I think "triangle" is sufficiently suggestive. However, what you've done here is not defective.

As this symbol isn't currently used anywhere, now's the time to change it.



_Suggestion:_
```objc
DeformableTriangleMesh
```
___
*[`geometry/deformable_mesh_with_bvh.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpL9wct0vwR4EIVohTz:-NpL9wct0vwR4EIVohU-:b-ij8mhr) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L1)):*
> ```objc
> #pragma once
> ```

BTW It's a shame that this lost the history of the previous file.  :(  There's not *a lot* of history, so it's probably not worth trying to fix this so the history isn't lost. But I thought I'd point it out. Particularly as the history got spread over two files.  Probably not worth saving. But it would've been nice if the history had been preserved slightly.
___
*[`geometry/deformable_mesh_with_bvh.h` line 20 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLBLq1-MlVisyITYZD:-NpLBLq1-MlVisyITYZE:bhstq22) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L20)):*
> ```objc
>  don't need the BVH.
> 
>  This is currently a speculative feature and not formally supported by
> ```

nit: You've preserved my redundant comment. The TODO says the same thing as this paragraph. And, as this paragraph doesn't get published anywhere, it's not worth having twice. Go ahead and delete this in favor of the TODO.
___
*[`geometry/deformable_mesh_with_bvh.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLC0JR7HAwggBKJJXK:-NpLC0JR7HAwggBKJJXL:b8zr0c5) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L35)):*
> ```objc
>    same frame.
> 
>    The %DeformableMeshWithBvh will *own* its own underlying mesh. */
> ```

nit: "...own underlying mesh __*and constructs a BVH on that mesh.*__"
___
*[`geometry/deformable_mesh_with_bvh.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLDX6V7k8vvB1WsOKX:-NpLDX6V7k8vvB1WsOKY:b54p12i) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L56)):*
BTW Revisiting this years later, it's probably worth putting a clarifying comment here and on the move assignment.

> Update the mesh and bvh *in place*, allowing the pointer values in bvh_updater_ and deformer_ to remain valid.
___
*[`geometry/deformable_mesh_with_bvh.h` line 96 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLMKkd4JFP23WQZPz-:-NpLMKkd4JFP23WQZPz0:b-c24rea) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L96)):*
> ```objc
> 
>  private:
>   // The delegate constructor used by move and copy constructors. We can't
> ```

nit: Since I originally wrote this, I have a better understanding of the problem. Let's update the text here:

```c++
// The delegate constructor used by move and copy constructors. The mesh-only
// constructor cannot delegate to this function because it would have to both
// construct a BVH from its input mesh *and* move that mesh. The C++
// specification leaves the ordering of evaluating those two expressions as
// unspecified. We cannot guarantee that we'll construct the BVH before moving
// the mesh's contents out. So, it has its own initialization.
``
```

___
*[`geometry/proximity/bvh_updater.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLMpOm1z25q3FCaQIp:-NpLMpOm1z25q3FCaQIq:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/proximity/bvh_updater.h#L26)):*
> ```objc
>  This class cannot be moved or copied. It is assumed upon creation that it will
>  be permanently associated with *specific* MeshType and Bvh instances and
>  maintain those associations for its entire lifetime (see DeformableWithBvh
> ```

nit: typo



_Suggestion:_
```objc
DeformableMeshWithBvh
```

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-:-NpMvI9Y-EKhbRyNND4B:b-a7aj82)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLN-nr12Iu1IaAZsNQ:-NpMoauR5_OHs3W--4xl:bodo3ee) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Presumably this is going to have a conflict with #20813.  What's your plan for reconciliation? Presumably, files now in `geometry/` will be going into `geometry/mesh/`, right?
</blockquote></details>

It depends on how #20813 gets resolved. I think Jeremy is offering to take over the dir reorg effort, which means that this PR train doesn't need to worry about it just yet.

___
___
*[`geometry/deformable_mesh.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLNzz4Esi5MJ-hDXF2:-NpMa5UPA-uIxcrTTSE5:b-ro51xp) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L1)):*
> BTW I get the sense that splitting `DeformableVolumeMesh` into two classes, `DeformableMeshWithBvh` and `DeformableMesh` is speculative, right?

Yes.

> Is there a particular application where you anticipate using the `DeformableMesh` type independently of `DeformablemeshWithBvh`? Presumably rendering?

Yes, I plan to use it in rendering where the rendered mesh deform with the control mesh. And I don't want to carry the bvh in each vertex position update for the render mesh.
___
*[`geometry/deformable_mesh.h` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPpgn4SGzLLNZRe6R:-NpMowHe6Q1MTdxaf2tU:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done
___
*[`geometry/deformable_mesh.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPtsBB_3bF09NWpee:-NpMapBXDl4KcFUF_RLQ:b2nhdku) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As with `DeformableMeshWithBvh`, let's nix this paragraph.  (Hey, there's a three-letter word for you.)
</blockquote></details>

Don
___
*[`geometry/deformable_mesh.h` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLQ6481P6ZCvWlC6PI:-NpMpnUw15KajM15Navk:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L53)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Again, as with `DeformableMeshWithBvh`, some comments here about an in-place update so that the deformer's pointer remains valid.
</blockquote></details>

Done
___
*[`geometry/deformable_mesh.h` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPFm951phAN7IVNDR:-NpMpFd_BiTp5DqYKMnc:b-4yn7v9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L86)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd argue that "triangle" and "surface" mesh are redundant. Admittedly, a surface mesh can be strictly triangles or polygons -- that's a problem we don't have with the volume mesh (which, we've accepted will strictly be tetrahedra and not arbitrary polytopes). But, in the goal of a shorter name, I think "triangle" is sufficiently suggestive. However, what you've done here is not defective.

As this symbol isn't currently used anywhere, now's the time to change it.
</blockquote></details>

Done. Why didn't we name `TriangleSurfaceMesh` to be `TriangleMesh` to start with?
___
*[`geometry/deformable_mesh_with_bvh.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpL9wct0vwR4EIVohTz:-NpMb3Gc7HVlivvhiwYy:bi3rdfh) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It's a shame that this lost the history of the previous file.  :(  There's not *a lot* of history, so it's probably not worth trying to fix this so the history isn't lost. But I thought I'd point it out. Particularly as the history got spread over two files.  Probably not worth saving. But it would've been nice if the history had been preserved slightly.
</blockquote></details>

ok, I'll try to remember this next time around when I'm moving files.
___
*[`geometry/deformable_mesh_with_bvh.h` line 20 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLBLq1-MlVisyITYZD:-NpMpQhq9ZtYSL_XmOI_:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L20)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: You've preserved my redundant comment. The TODO says the same thing as this paragraph. And, as this paragraph doesn't get published anywhere, it's not worth having twice. Go ahead and delete this in favor of the TODO.
</blockquote></details>

Done
___
*[`geometry/deformable_mesh_with_bvh.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLC0JR7HAwggBKJJXK:-NpMpW5bBR7jzIlp9GPq:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "...own underlying mesh __*and constructs a BVH on that mesh.*__"
</blockquote></details>

Done
___
*[`geometry/deformable_mesh_with_bvh.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLDX6V7k8vvB1WsOKX:-NpMph6M0KgaBSrlGwNk:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L56)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Revisiting this years later, it's probably worth putting a clarifying comment here and on the move assignment.

> Update the mesh and bvh *in place*, allowing the pointer values in bvh_updater_ and deformer_ to remain valid.
</blockquote></details>

Done
___
*[`geometry/deformable_mesh_with_bvh.h` line 96 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLMKkd4JFP23WQZPz-:-NpMq22S4WKs76UbmcLk:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh_with_bvh.h#L96)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Since I originally wrote this, I have a better understanding of the problem. Let's update the text here:

```c++
// The delegate constructor used by move and copy constructors. The mesh-only
// constructor cannot delegate to this function because it would have to both
// construct a BVH from its input mesh *and* move that mesh. The C++
// specification leaves the ordering of evaluating those two expressions as
// unspecified. We cannot guarantee that we'll construct the BVH before moving
// the mesh's contents out. So, it has its own initialization.
``
```

</blockquote></details>

Done
___
*[`geometry/proximity/bvh_updater.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLMpOm1z25q3FCaQIp:-NpMq53yAmIX7VcmwMl5:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/proximity/bvh_updater.h#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/deformable_mesh.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPtsBB_3bF09NWpee:-NpQ70S5-11FCvTMSj90:brckx1t) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Don
</blockquote></details>

And what did you put on in response? (Assuming you were doing your own three-letter word joke.)
___
*[`geometry/deformable_mesh.h` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPFm951phAN7IVNDR:-NpQ78yF0WqwyucggEXY:bg69yc9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done. Why didn't we name `TriangleSurfaceMesh` to be `TriangleMesh` to start with?
</blockquote></details>

That's a fine question. I don't truly remember. Possibly because the other was called `VolumeMesh`. At one point, there *may* have been the thought that it could be implemented using some other volume representation, perhaps? In retrospect, I think they should probably have been called `TetrahedralMesh` and `TriangleMesh`. But now we deal with the world we live in.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/deformable_mesh.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-NpLPtsBB_3bF09NWpee:-NpQIUpp3XxFYJaxnvYg:b32vhw) ([raw file](https://github.com/RobotLocomotion/drake/blob/4920c2ca270144871544eb2e58b227d96f6b87f1/geometry/deformable_mesh.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

And what did you put on in response? (Assuming you were doing your own three-letter word joke.)
</blockquote></details>

:)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 17 of 20 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20826#-:-NpQzOkg45ia4izR8tIH:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
