### PR TITLE
Add CPack configuration for building Debian packages, etc.

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #1183.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8188)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8188#-:-L6S4VgIFqUYkV6J3d_H:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
I provide a largely ignorant :LGTM:.  But it all *looks* good.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8188#-:-L6SVg_XSrFtm37hBB9F:b-qi6wkc)*

**Pull request merged**
