### PR TITLE
Fix Wunused-parameter in common

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5986)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for first review, please.

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-:-Kj4PAZCy2n1MYIZvWcO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+(priority: low) 
+@ggould-tri for platform review; it can wait until your on-call day if you wish.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-:-Kj4TKBvm4e_Oc7UIcoz:bu05ur5)*

**Comment by ggould-tri** [comment]
One comment below; :lgtm: once resolved.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/call_matlab.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-Kj4_gooM5o1LFLe6_Cf:-Kj4_gopGP42Y07wrWc7:b-foz9df) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be69635a2ff901b84535c472f451aaedd68ba1/drake/common/call_matlab.h#L62)):*
> ```objc
> inline void AssembleCallMatlabMsg(MatlabRPC* msg) {
>   // Intentionally left blank.  Base case for template recursion.
>   unused(msg);
> ```

Is there a reason to prefer this `unused()` idiom over omitting the parameter name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-:-Kj4a8xuMlpdVE0MTteo:b-ub99or)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/call_matlab.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-Kj4_gooM5o1LFLe6_Cf:-Kj4fqLGF_8pazajXK12:bblwl4t) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be69635a2ff901b84535c472f451aaedd68ba1/drake/common/call_matlab.h#L62)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Is there a reason to prefer this `unused()` idiom over omitting the parameter name?
</blockquote></details>

Done.  This one was borderline, and upon re-review it would probably not meet my written-up heuristics (forthcoming PR) for how to solve unused-parameter warnings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5986)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/call_matlab.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5986#-Kj4_gooM5o1LFLe6_Cf:-Kj4gjqUMCj3GE_EjalX:b-khrk4y) ([raw file](https://github.com/robotlocomotion/drake/blob/a5be69635a2ff901b84535c472f451aaedd68ba1/drake/common/call_matlab.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  This one was borderline, and upon re-review it would probably not meet my written-up heuristics (forthcoming PR) for how to solve unused-parameter warnings.
</blockquote></details>

Eager to see those heuristics :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5986)*

**Comment by jwnimmer-tri** [comment]
Huh, no builds reported any status.
@drake-jenkins-bot retest this please

**Pull request merged**
