### PR TITLE
Moved package.xml To Be At The Drake Superbuild Level

### PR DESCRIPTION
**Pull request by liangfok**
This enables Drake to be compiled as part of a Catkin package. This was originally done by @jhoare [here](https://github.com/jhoare/drake/commit/72b6dec8293746980d3253c67e21cc29f7336028#diff-34ae68f4adad56c25c5bc05dcb64794e). I tested this by executing the following commands, which creates a ROS Catkin workspace, downloads Drake as a package within this workspace, and then compiles the entire workspace:

```
$ mkdir -p ~/dev/drake_catkin_workspace/src
$ cd ~/dev/drake_catkin_workspace/src
$ source /opt/ros/indigo/setup.bash
$ catkin_init_workspace
$ cd ..
$ catkin_make
$ cd src
$ git clone git@github.com:liangfok/drake.git
$ cd drake
$ git checkout -t origin/feature/drake_superbuild_is_ros_package
$ cd ~/dev/drake_catkin_package
$ catkin_make -j1 -DDISABLE_MATLAB=TRUE
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2755)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review
+@jwnimmer-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM2VxrGMBv_o4USpl5B:-892967772)*

**Comment by liangfok** [comment]
The gcc-linux CI build https://drake-jenkins.csail.mit.edu/job/experimental/2535/compiler=gcc,label=linux_matlab/consoleFull appears to have suffered a new flake:

```
00:16:28 CMake Error at cmake/mex.cmake:107 (message):
00:16:28   Failed to find mex executable
00:16:28 Call Stack (most recent call first):
00:16:28   CMakeLists.txt:136 (mex_setup)
```

@drake-jenkins-bot retest this please.

**Comment by jhoare** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.xml, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4VAf9-KfeidtCk5H6:-KM4VAfA4b1E1Wb2lYjJ:1735145751) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L3)):*
> ```XML
> <package>
>     <name>drake</name>
>     <version>1.0.0</version>
> ```

Perhaps this should be changed to something like 0.0.0, rather than implying this is actually a point release.

---

*[package.xml, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4VT1IBEbw8m2dV4ce:-KM4VT1IBEbw8m2dV4cf:367406192) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L5)):*
> ```XML
>     <version>1.0.0</version>
>     <description>A planning, control, and analysis toolbox for nonlinear dynamical systems</description>
>     <maintainer email="russt@mit.edu">Russ Tedrake</maintainer>
> ```

Should Russ be the author? Maybe you should put yourself as maintainer (or drake-devleopers mailing list) and change Russ to an "author". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755)*

**Comment by ggould-tri** [comment]
The commands documented in your comment above should be scribed somewhere other than a github issue comment.  I would suggest an appendix to the Drake docs.

(I am also concerned by the level of shell contamination implied by the `source` command in there, but I assume that's just the price of working with catkin).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[package.xml, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4_du8ocsYaBUYS09D:-KM4_du9wk7yJdt1qIrz:-1014894267) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L1)):*
> ```XML
> <package>
> ```

It would be good to have a comment here explaining that this file is a catkin build configuration file.  Otherwise developers who have never heard of or used catkin (ie, nearly everybody) will be confused by this file, which has an extremely generic name and no clear consumer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM4ZdQwYDwI_nwCLqxF:-1408091659)*

**Comment by liangfok** [comment]
-@jwnimmer-tri for platform review
+@ggould-tri for platform review

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM4iDuiZ7hl3rBLvZtH:1980341776)*

**Comment by jhoare** [comment]
@drake-jenkins-bot retest this please

**Comment by jhoare** [comment]
> $ catkin_make -j1 -DDISABLE_MATLAB=TRUE

Why do you have to do the ``-j1`` ? Also, are you preferring not to use catkin-tools ? I find it works a lot better for this use case. Otherwise, to build the with ``drake_ros`` package I have created, you would have to use ``catkin_make_isolated`` rather than ``catkin_make``

**Comment by liangfok** [comment]
The `-j1` is optional. I sometimes do that in an abundance of caution and to avoid hitting memory limits (I was using my laptop, which only has 16GB of RAM). I have removed it and will push an update to this PR soon.

I am OK with using `catkin-tools` and will likely switch to it in a future PR when we add mentioning of the   `drake_ros` package. For now, I figured since `catkin-tools` is not strictly necessary, it would be better to avoid mentioning it in this PR. Basically, I am trying to keep the PR as simple as possible :smile:.

**Comment by jhoare** [comment]
> I am OK with using catkin-tools and will likely switch to it in a future PR when we add mentioning of the drake_ros package. 

Okay, just wanted to make sure as I am trying to get up a CI system and what build tools it uses.

**Comment by liangfok** [comment]
About that `-DDISABLE_MATLAB=TRUE` flag:

I used it because I did not have access to the MATLAB license server and this lack of access was causing the build to fail. I'll try again today without the flag since I should have access to the MATLAB license server from the office.

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[package.xml, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4_du8ocsYaBUYS09D:-KM4m-LB2l9N5Lh5UTns:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> It would be good to have a comment here explaining that this file is a catkin build configuration file.  Otherwise developers who have never heard of or used catkin (ie, nearly everybody) will be confused by this file, which has an extremely generic name and no clear consumer.
</details>
Done.

---

*[package.xml, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4VAf9-KfeidtCk5H6:-KM4m1BSgCKSlQfpCmrH:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L3)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> Perhaps this should be changed to something like 0.0.0, rather than implying this is actually a point release.
</details>
Done.

---

*[package.xml, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM4VT1IBEbw8m2dV4ce:-KM4m1yfRb53UKZ94IjZ:1476561930) ([raw file](https://github.com/robotlocomotion/drake/blob/e39f40c47062c4d3d8391159cf868dc7b353ad75/package.xml#L5)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> Should Russ be the author? Maybe you should put yourself as maintainer (or drake-devleopers mailing list) and change Russ to an "author". 
</details>
Done. Per @rpoyner-tri's suggestion, I went with drake-users@mit.edu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM5PhXCckbE-t8FN6IV:701515998)*

**Comment by jhoare** [comment]
Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.xml, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM5QZJgnVqFu5ffTFsL:-KM5QZJgnVqFu5ffTFsM:1984732535) ([raw file](https://github.com/robotlocomotion/drake/blob/11face938a690634d5e7c2e568d3237d9fb3d9b7/package.xml#L31)):*
> ```XML
>   <depend>sensor_msgs</depend>
>   <depend>std_msgs</depend>
>   <depend>tf</depend>
> ```

Does drake actually have a dependency on any of these ROS packages? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755)*

**Comment by ggould-tri** [comment]
:lgtm: (pending of course resolution of @jhoare 's remaining blocking comment)

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM5Qy_ot3xfPXTmoLS7:-1685355033)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.xml, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-KM5QZJgnVqFu5ffTFsL:-KM5SMYlE8KpkZA0Owl8:2101694372) ([raw file](https://github.com/robotlocomotion/drake/blob/11face938a690634d5e7c2e568d3237d9fb3d9b7/package.xml#L31)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> Does drake actually have a dependency on any of these ROS packages? 
</details>
Oops! No, I removed them. Thanks for catching this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755)*

**Comment by jhoare** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM5StncnybaqtGOeeMb:1417088721)*

**Comment by jhoare** [comment]
Is this mex error for gcc-matlab happening on any other pull request? It seems consistent on this PR but I haven't seen it happening anywhere else...

**Comment by liangfok** [comment]
It appears to be a true positive. I will investigate soon.

**Comment by liangfok** [comment]
CI `gcc-linux` build https://drake-jenkins.csail.mit.edu/job/experimental/2543/compiler=gcc,label=linux_matlab/consoleFull also suffered #2756. Earlier in the log it also had the following error:

```
13:46:26  > git checkout -f 008373a352dcf8deeb520208ca1145c8204c5df3
13:46:26 Using 'Changelog to branch' strategy.
13:46:26 fatal: bad revision '^origin/master'
13:46:26 ERROR: Unable to retrieve changeset
13:46:26 hudson.plugins.git.GitException: Error launching git whatchanged
13:46:26 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$6.execute(CliGitAPIImpl.java:840)
13:46:26 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
13:46:26 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
13:46:26 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
13:46:26 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
13:46:26 	at hudson.remoting.Request$2.run(Request.java:326)
13:46:26 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
13:46:26 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
13:46:26 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
13:46:26 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
13:46:26 	at java.lang.Thread.run(Thread.java:745)
13:46:26 	at ......remote call to drake-linux-2016-07-01-c4.8xlarge (i-ca96125a)(Native Method)
13:46:26 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
13:46:26 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
13:46:26 	at hudson.remoting.Channel.call(Channel.java:781)
13:46:26 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
13:46:26 	at sun.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
13:46:26 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:46:26 	at java.lang.reflect.Method.invoke(Method.java:606)
13:46:26 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
13:46:26 	at com.sun.proxy.$Proxy86.execute(Unknown Source)
13:46:26 	at hudson.plugins.git.GitSCM.computeChangeLog(GitSCM.java:1215)
13:46:26 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1135)
13:46:26 	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:143)
13:46:26 	at hudson.scm.SCM.checkout(SCM.java:485)
13:46:26 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
13:46:26 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
13:46:26 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
13:46:26 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
13:46:26 	at hudson.model.Run.execute(Run.java:1738)
13:46:26 	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
13:46:26 	at hudson.model.ResourceController.execute(ResourceController.java:98)
13:46:26 	at hudson.model.Executor.run(Executor.java:410)
```
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM5tGM_3yuqqap668ja:561532972)*

**Comment by liangfok** [comment]
I started the following on-demand CI build / test to see if the same error is repeatable: https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/63/

**Comment by liangfok** [comment]
The [manually-scheduled linux-gcc-matlab test passed](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/63/). Thus, I hope the previous pre-merge CI failures were a flake:

@drake-jenkins-bot: retest this please.

**Comment by liangfok** [comment]
Unfortunately the pre-merge CI test failed again. We at least now I can compare a [successful manually-scheduled test](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/63/consoleFull) with the latest [unsuccessful pre-merge test](https://drake-jenkins.csail.mit.edu/job/experimental/2549/compiler=gcc,label=linux_matlab/consoleFull).

**Comment by liangfok** [comment]
Unfortunately, practically every single line between the two logs mentioned in my previous post were different. The failure log was only 30K lines long whereas the success log was closer to 100K lines long.

Comparing a [pre-merg failure log](https://drake-jenkins.csail.mit.edu/job/experimental/2549/compiler=gcc,label=linux_matlab/consoleFull) with a [pre-merge success log](https://drake-jenkins.csail.mit.edu/job/experimental/2548/compiler=gcc,label=linux_matlab/console), the biggest difference is the failure log includes:

```
23:16:47 CMake Error at cmake/mex.cmake:107 (message):
23:16:47   Failed to find mex executable
23:16:47 Call Stack (most recent call first):
23:16:47   CMakeLists.txt:136 (mex_setup)
```
whereas the successful log has:
```
20:55:53 -- Found MATLAB at /usr/local/MATLAB/R2015b/bin/matlab
```

Let's try isolating the problem. #2759 just moves the location of package.xml without changing its content.

**Comment by liangfok** [comment]
In PR #2759, [build #2550](https://drake-jenkins.csail.mit.edu/job/experimental/2550/compiler=gcc,label=linux_matlab/)  passed with just one warning:

```
CMake Warning at cmake/mex.cmake:241 (message):
  Your MEX compiler flags contained '-ansi', but we've removed that flag for
  compatibility with C++11
Call Stack (most recent call first):
  CMakeLists.txt:136 (mex_setup)
```

 I shall now update the content within the `package.xml` file, which'll trigger a re-test. The re-test is [build #2551](https://drake-jenkins.csail.mit.edu/job/experimental/2551/compiler=gcc,label=linux_matlab/).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM9L-5fd1iDH3iICXag:-1270524753)*

**Comment by liangfok** [comment]
[Build #2551](https://drake-jenkins.csail.mit.edu/job/experimental/2551/) passed. Note that this includes both the relation of `package.xml` and modification of its content. Hmm...I guess the MATLAB failure holding up this PR must be a repeatable flake. I'm now going to update #2759 to be _identical_ to this PR.

The re-test is [build #](https://drake-jenkins.csail.mit.edu/job/experimental/2552/).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM9VtIwkyzsMpRQ51T-:1524934949)*

**Comment by liangfok** [comment]
https://drake-jenkins.csail.mit.edu/job/experimental/2552/ passed. I'm thus going to close this PR and switch to #2759 .

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2755#-:-KM9g-PIB7OgTDRr8JYn:-968287937)*

**Pull request closed without merging**
