### PR TITLE
Added approximating functions support for IVP and quadrature classes

### PR DESCRIPTION
**Pull request by hidmic**
This pull request adds support to obtain an `ApproximatingFunction` based on a provided `ApproximationTechnique` for any of the IVP and quadrature classes available below the `drake::systems::analysis` namespace. The motivating use case for this implementation involves _dense output_ requirements for both an IVP solution and a quadrature computation, while maintaining a given accuracy.

A few high level explanations to help the review. The `ApproximatingFunction` is not bound to any given type to avoid constraining the user in the absence of a general enough approximation device that can also remain consistent with the public interface of each class (e.g. vector vs scalar IVP solvers). Performing the interpolation within these classes where direct access to the underlying integrators is available reduces the overhead and allows leveraging variable, error controlled step sizes for the final result.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8707)

### CODE REVIEW

**Comment by hidmic** [comment]
Review status: 8 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[systems/analysis/scalar_initial_value_problem.h, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBSVxDN3wR9MHUBmybh:-LBVtpOP2brdWXmKtzGP:boi9kjb) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/scalar_initial_value_problem.h#L64)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"approximation technique function type" is misleading. Perhaps this is better? "Definition of an approximating function type, toward constructing functions of the form z(t) that approximate a solution to an initial value problem x(t; k)..."
</blockquote></details>

Hmm. So I came up with this naming because, at least in my mind, the approximating function and the method to construct that approximating function are not the same thing. As an example, consider a polynomial interpolator (i.e. the approximating function) and the procedure to compute its coefficients (i.e. the aproximation technique) to match an arbitrary function. With that in mind, this type would not represent the approximating function. 

But I can see that maybe the current naming is misleading or confusing. How would you call it?

---

*[systems/analysis/scalar_initial_value_problem.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBSW2fR2IZ4ICZ2v68k:-LBWX2_Z1zF_9UqUzEyh:byzlgjr) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/scalar_initial_value_problem.h#L65)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

A partition of its domain into what?
</blockquote></details>

...N contiguous intervals. The sequences provide the boundary values for each one. I've made this more explicit in the documentation. 

---

*[systems/analysis/scalar_initial_value_problem.h, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBSX97V-zO1LNpfpvrs:-LBVupksDNYK2e2VgV_E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/scalar_initial_value_problem.h#L149)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This would read better if you replace @p tf with `tf`.
</blockquote></details>

Done.

---

*[systems/analysis/scalar_initial_value_problem.h, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBSXjy38ryU_WqDMpE1:-LBWBFaDAK-e0cOy7-bX:bgrw0u8) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/scalar_initial_value_problem.h#L230)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This seems like a good place to point out the difference(s) between the two approximation techniques, as VectorApproximationTechnique is not really described.
</blockquote></details>

Done. Also added a reference to the actual definitions.

---

*[systems/analysis/test/antiderivative_function_test.cc, line 131 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBBrCL1CDiQbvscNSdZ:-LBWLhLJ4ULb-elLE-CA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/test/antiderivative_function_test.cc#L131)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please document the purpose of this function.
</blockquote></details>

Done.

---

*[systems/analysis/test/initial_value_problem_test.cc, line 233 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8707#-LBSYEOL3lEl32m7PAuJ:-LBVu_9H41QGkNcgi_XN:bng7ub9) ([raw file](https://github.com/robotlocomotion/drake/blob/df53f1f6dc124cb069baf56ffb5a5e8f0fc52d48/systems/analysis/test/initial_value_problem_test.cc#L233)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

At a glance, this appears identical to the piece of code in antiderivative_function_test.cc. Can you refactor this into another file?
</blockquote></details>

Hmm this one in particular is not. Note that for regular (vector) IVPs, we're approximating a vector function and for scalar IVPs and scalar quadrature, a scalar function. Though it is the same code snippet in `scalar_initial_value_problem_test.cc` and `antiderivative_function_test.cc`. Making them common test utilities.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8707)*

**Comment by hidmic** [comment]
Per today's discussion with @edrumwri, following steps for this PR are:
1. Constrain the approximating function type, e.g. using an abstract class with an `Evaluate()` method.
2. Migrate the `Approximate()` interface to the `IntegratorBase` class, along with the Hermitian interpolator as the default implementation, but allowing for specialization on a per integrator basis.
3. Open an issue to enforce specialization on each integrator.

---

Review status: 3 of 13 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8707#-:-LBd5X7Z34Eso5T-1VX0:b6su3bi)*

**Comment by hidmic** [comment]
Also, I'll make this approximation interface available through the IVP and quadrature classes.

---

Review status: 3 of 13 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8707#-:-LBd7abL8JSYkjIJr-BF:bu65k5x)*

**Comment by edrumwri** [comment]
Sweet!

---

Review status: 3 of 13 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8707#-:-LBdEqB0BulDCdcVynyp:bzftu3a)*

**Comment by hidmic** [comment]
Superseded by #8949, #8950, #8951 and #8952.

**Pull request closed without merging**
