### PR TITLE
Add/move/document/use drake_install_(executables|headers)

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4162)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
Nits on documentation... most comments will apply to multiple instances. I think it makes sense to strive for consistency here. The documentation of `drake_add_external` is generally the canonical example of "correct" formatting. (I'm not *necessarily* opposed to something different, but if we want to go that way, let's please update the other existing documentation to conform.)

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKaH59eL_6QwfsVt9:-KWsKaH59eL_6QwfsVtA:b-4p1sle) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L20)):*
> ```CMake
> #   drake_install_executables(<targets>)
> #
> #   drake_install_executables(TARGETS <targets> [<ARGS>])
> ```

nit: `args` s.b. lower case; multi-valued  parameters should have `...`

```
#   drake_install_executables(TARGETS <targets...> [<args...>])
```

---

*[cmake/install.cmake, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsLSDDOg2CGH_i3mbF:-KWsLSDDOg2CGH_i3mbG:b-wco0ph) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L23)):*
> ```CMake
> #
> # Arguments:
> #   TARGETS
> ```

nit: also show the value(s):

```
#   TARGETS <targets...>
```

---

*[cmake/install.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKLv68emvXm8fnrxq:-KWsKLv68emvXm8fnrxr:b-3oh6xw) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L27)):*
> ```CMake
> #     permissions OWNER_EXECUTE, OWNER_READ, OWNER_WRITE, GROUP_READ,
> #     GROUP_EXECUTE, WORLD_READ, and WORLD_EXECUTE.
> #   <ARGS>
> ```

nit: blank line between arguments with block descriptions

---

*[cmake/install.cmake, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsK9zUPgQWjrMPnTDZ:-KWsK9zUPgQWjrMPnTD_:b-kw9cga) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L43)):*
> ```CMake
>     ${_UNPARSED_ARGUMENTS})
> endfunction()
> ```

nit: only one blank line please

---

*[cmake/install.cmake, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsLnAPSjIyldakcYYC:-KWsLnAPSjIyldakcYYD:b-pvykzh) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L71)):*
> ```CMake
> 
>   file(RELATIVE_PATH _relative_path
>     "${PROJECT_SOURCE_DIR}/"
> ```

BTW, is there a reason the first argument has a trailing `/` and the second does not? It seems odd...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-:-KWsME9OL8E1bjEo9fnA:b12okgw)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsLnAPSjIyldakcYYC:-KWsN8Yr_VmwF2jln8qC:bur2sgo) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L71)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, is there a reason the first argument has a trailing `/` and the second does not? It seems odd...
</details>
I think Brad wrote the original function, so I assume there is good reason,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKaH59eL_6QwfsVt9:-KWsP9LV_HuMynb_OYKX:b848p9w) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> nit: `args` s.b. lower case; multi-valued  parameters should have `...`
> 
> ```
> #   drake_install_executables(TARGETS <targets...> [<args...>])
> ```
</details>
`<NAME>` in `drake_install_pkg_config_file` should be upper or lower?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsLSDDOg2CGH_i3mbF:-KWsRASo4WCXXH8P-Oaj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L23)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> nit: also show the value(s):
> 
> ```
> #   TARGETS <targets...>
> ```
</details>
Done.

---

*[cmake/install.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKLv68emvXm8fnrxq:-KWsRNLq3whUBkVeSRQo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L27)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> nit: blank line between arguments with block descriptions
</details>
Done.

---

*[cmake/install.cmake, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsK9zUPgQWjrMPnTDZ:-KWsROV6ioSKs6-F31wm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L43)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> nit: only one blank line please
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKaH59eL_6QwfsVt9:-KWsWSmESCVv5W3wpulJ:b-igresd) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L20)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> `<NAME>` in `drake_install_pkg_config_file` should be upper or lower?
</details>
In the synopsis, would be lower... "keywords" (basically, text that appears literally), are upper-case, placeholders are lower-case and surrounded with `<>`s.

---

*[cmake/install.cmake, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZ3JxCBUTTdoJ87kW:-KWsZ3Jy7N8FouKYWqtd:b-1oorl6) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L19)):*
> ```CMake
> #   drake_install_executables(<targets...>)
> #
> #   drake_install_executables(TARGETS <targets...> [<args...>])
> ```

On a separate note, I just realized... `<args...>` will never be seen, since `TARGETS` is multi-valued... easiest fix is to instead give the synopsis as `[<args...>] TARGETS <targets...>`.

---

*[cmake/install.cmake, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsYu_sbAfbS-_yIi8z:-KWsYu_sbAfbS-_yIi9-:b-vvowhj) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L76)):*
> ```CMake
>     DESTINATION "${DRAKE_INSTALL_INCLUDE_DIR}/drake/${_relative_path}")
> endfunction()
> ```

...missed an extra blank line here

---

*[cmake/install.cmake, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZnD5FOK6xTmgxPQQ:-KWsZnD5FOK6xTmgxPQR:b-n4lfn1) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L87)):*
> ```CMake
> #                               [VERSION <major.minor.patch>]
> #                               [REQUIRES <packages...>] [LIBS <flags...>]
> #                               [CFLAGS <flags...>] [CLASSPATH <classpath>])
> ```

BTW, since I believe this will need to be wrapped (see comment below), it might make sense to break after `REQUIRES` and have `LIBS` and `CFLAGS` together. (Purely aesthetic, though...)

---

*[cmake/install.cmake, line 117 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZhOOI62OcSMCE7sO:-KWsZhOOI62OcSMCE7sP:b-u1rpmi) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L117)):*
> ```CMake
> #     prepended to the field.
> #
> #   CLASSPATH <classpath>
> ```

...this is multi-valued, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmake/install.cmake, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsKaH59eL_6QwfsVt9:-KWseJzhi4zjq9TX1dlk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed93a9ba45d71435995b74de0f8a128d68630143/cmake/install.cmake#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> In the synopsis, would be lower... "keywords" (basically, text that appears literally), are upper-case, placeholders are lower-case and surrounded with `<>`s.
</details>
Done.

---

*[cmake/install.cmake, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZ3JxCBUTTdoJ87kW:-KWseJ3ybcz8kLG9UZau:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L19)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> On a separate note, I just realized... `<args...>` will never be seen, since `TARGETS` is multi-valued... easiest fix is to instead give the synopsis as `[<args...>] TARGETS <targets...>`.
</details>
Done.

---

*[cmake/install.cmake, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsYu_sbAfbS-_yIi8z:-KWsdwkaLrlULkmxm4hY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L76)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> ...missed an extra blank line here
</details>
Done.

---

*[cmake/install.cmake, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZnD5FOK6xTmgxPQQ:-KWsdw-yvxBWMlOCd19R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L87)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> BTW, since I believe this will need to be wrapped (see comment below), it might make sense to break after `REQUIRES` and have `LIBS` and `CFLAGS` together. (Purely aesthetic, though...)
</details>
Done.

---

*[cmake/install.cmake, line 117 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-KWsZhOOI62OcSMCE7sO:-KWsdy2ndN7geOOUGOK-:b-b6d7ju) ([raw file](https://github.com/robotlocomotion/drake/blob/0f08ff3555c7b8ea3b3badace5636aa63e983edf/cmake/install.cmake#L117)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> ...this is multi-valued, no?
</details>
Done. Spotted a bug too (not that we have any multi-valued classpaths, though).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:; thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-:-KWsh8Tfp_0WnkoF36tl:b3jxd5u)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4162#-:-KWsjGPLZ2HWi6RZxFHO:bnfp4nl)*

**Pull request merged**
