### PR TITLE
Add binary code match constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8513)

### CODE REVIEW

**Comment by avalenzu** [comment]
Review pass done. PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[solvers/integer_optimization_util.h, line 75 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FmKDHBsYQinJUOMqO:-L9FmKDHBsYQinJUOMqP:br38qcl) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L75)):*
> ```objc
>     const symbolic::Expression& b1_xor_b2);
> 
> /** Create linear constraints, when these constraints are satisfied, match = 1
> ```

"Create linear constraints **such that**, when these . . ."

---

*[solvers/integer_optimization_util.h, line 84 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FplkFCVI-oCHLM7pY:-L9FplkFCVI-oCHLM7pZ:b-m2pqor) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L84)):*
> ```objc
>  *
>  * This function is useful integer optimization, for example, if we have a
>  * constraint match = ((b1 == 0) & (b2 == 1) && (b3 == 1)), we can call the
> ```

Do you intend to have `&` between the first two sets of parentheses and `&&` between the second two sets?

---

*[solvers/integer_optimization_util.h, line 85 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9For2f-hAcW98WgPsJ:-L9For2f-hAcW98WgPsK:b-n4sg2a) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L85)):*
> ```objc
>  * This function is useful integer optimization, for example, if we have a
>  * constraint match = ((b1 == 0) & (b2 == 1) && (b3 == 1)), we can call the
>  * function CreateCodeMatchConstraint({b1, b2, b3}, {0, 1, 1}, match) to create
> ```

s/CreateCodeMatchConstraint/CreateBinaryCodeMatchConstraint/

---

*[solvers/integer_optimization_util.cc, line 49 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9Fq4nY11SQYmMevftl:-L9Fq4nY11SQYmMevftm:bacvp9j) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L49)):*
> ```cpp
> 
> Binding<LinearConstraint> CreateBinaryCodeMatchConstraint(
>     const VectorX<symbolic::Expression>& code,
> ```

Do you need to enforce that `code` and `match` are linear expressions?

---

*[solvers/integer_optimization_util.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FnAEC5gmfc9UeIbrs:-L9FnAEC5gmfc9UeIbrt:brevndf) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L53)):*
> ```cpp
>     const symbolic::Expression& match) {
>   DRAKE_ASSERT(code.rows() == expected.rows());
>   // If the elementwise and of match_and = 1, then code = expected.
> ```

BTW, could you use "AND" for the boolean operation in your comments? Lowercase is fine in the variable names, but I have to read the comment a few times to figure out what's a boolean operation and whats an English conjunction. :-)

---

*[solvers/integer_optimization_util.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FnjFm3aOtMZQmM8TA:-L9FnjFm3aOtMZQmM8TB:b13k59r) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L53)):*
> ```cpp
>     const symbolic::Expression& match) {
>   DRAKE_ASSERT(code.rows() == expected.rows());
>   // If the elementwise and of match_and = 1, then code = expected.
> ```

Do you really mean "elementwise" here? I thought element-wise AND was a binary operation, e.g.  (1, 0, 1) & (1, 1, 0) = (1, 0, 0)

---

*[solvers/integer_optimization_util.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FrYbNEsBhQt92oGqE:-L9FrYbNEsBhQt92oGqF:b-ref34m) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L67)):*
> ```cpp
>     f = f && match <= match_and(i);
>   }
>   f = f && match >= match_and.sum() - (code.rows() - 1);
> ```

Where does the `(code.rows() - 1)` come from? Sorry if I'm being dense.

---

*[solvers/test/integer_optimization_util_test.cc, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FrmcB0LbumEyjN38B:-L9FrmcB0LbumEyjN38C:b-fxeqzp) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/test/integer_optimization_util_test.cc#L116)):*
> ```cpp
> }
> 
> GTEST_TEST(TestBinaryCodeMatchConstraint, Test) {
> ```

BTW, this name doesn't match the others in the file. Following their pattern it would be
```
GTEST_TEST(IntegerOptimizationUtilTest, TestBinaryCodeMatchConstraint) {
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-:-L9Fs8ibEAuTeRp0R3dT:b837gv3)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[solvers/integer_optimization_util.h, line 75 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FmKDHBsYQinJUOMqO:-L9GQ20y3-nl95YJEj_d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L75)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"Create linear constraints **such that**, when these . . ."
</blockquote></details>

Done.

---

*[solvers/integer_optimization_util.h, line 84 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FplkFCVI-oCHLM7pY:-L9GQ5A6Al-E0u8HqacV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L84)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Do you intend to have `&` between the first two sets of parentheses and `&&` between the second two sets?
</blockquote></details>

Done.

---

*[solvers/integer_optimization_util.h, line 85 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9For2f-hAcW98WgPsJ:-L9GQAkf0xjypiTdfypi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.h#L85)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/CreateCodeMatchConstraint/CreateBinaryCodeMatchConstraint/
</blockquote></details>

Done.

---

*[solvers/integer_optimization_util.cc, line 49 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9Fq4nY11SQYmMevftl:-L9GQCOC2duPLZt6JpHa:b-jazj8h) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L49)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Do you need to enforce that `code` and `match` are linear expressions?
</blockquote></details>

That is a complicated issue. Ideally I want `ParseLinearConstraint` function, which was removed in https://github.com/RobotLocomotion/drake/pull/8338. When I call this function, it will throw an error if the constraint is non-linear. Now I think we still get an error, but in `internal::BindingDynamicCast<LinearConstraint>`, if the resultant constraint is non-linear.

---

*[solvers/integer_optimization_util.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FnAEC5gmfc9UeIbrs:-L9GU9gEEyXOceAiu0-k:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L53)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, could you use "AND" for the boolean operation in your comments? Lowercase is fine in the variable names, but I have to read the comment a few times to figure out what's a boolean operation and whats an English conjunction. :-)
</blockquote></details>

Done. Good call.

---

*[solvers/integer_optimization_util.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FnjFm3aOtMZQmM8TA:-L9GUlUZBb8d_ZWsG57i:b-gshqmz) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L53)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Do you really mean "elementwise" here? I thought element-wise AND was a binary operation, e.g.  (1, 0, 1) & (1, 1, 0) = (1, 0, 0)
</blockquote></details>

Done. Do you think the documentation is clearer now?

---

*[solvers/integer_optimization_util.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FrYbNEsBhQt92oGqE:-L9GWK-XDcGd5yethouO:b7i7kx4) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L67)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Where does the `(code.rows() - 1)` come from? Sorry if I'm being dense.
</blockquote></details>

I document it in the equations above.

---

*[solvers/test/integer_optimization_util_test.cc, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FrmcB0LbumEyjN38B:-L9GWPeH6CGhQvuRNOno:btfi6d2) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/test/integer_optimization_util_test.cc#L116)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, this name doesn't match the others in the file. Following their pattern it would be
```
GTEST_TEST(IntegerOptimizationUtilTest, TestBinaryCodeMatchConstraint) {
```
</blockquote></details>

I already used `IntegerOptimizationUtilTest` as in `TEST_F(IntegerOptimizationUtilTest, blah)`. GTEST does not allow me to use the same name in both `TEST_F` and `GTEST_TEST`. It is not easy to write this test using the test class `IntegerOptimizationUtilTest`, as it consists different number of decision variables.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513)*

**Comment by avalenzu** [comment]
:lgtm: +@ggould-tri for platform review

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/integer_optimization_util.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FnjFm3aOtMZQmM8TA:-L9Gm_TB1kKBDW70PPQX:bf0wkjs) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/integer_optimization_util.cc#L53)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Do you think the documentation is clearer now?
</blockquote></details>

Much better! Thanks.

---

*[solvers/test/integer_optimization_util_test.cc, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-L9FrmcB0LbumEyjN38B:-L9GmhT15l-mJEdLnA7G:bbsmaa7) ([raw file](https://github.com/robotlocomotion/drake/blob/11e581fea1af7409d989c6086165ce3a92d16665/solvers/test/integer_optimization_util_test.cc#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I already used `IntegerOptimizationUtilTest` as in `TEST_F(IntegerOptimizationUtilTest, blah)`. GTEST does not allow me to use the same name in both `TEST_F` and `GTEST_TEST`. It is not easy to write this test using the test class `IntegerOptimizationUtilTest`, as it consists different number of decision variables.
</blockquote></details>

Got it. I'd missed that the previous ones were `TEST_F`. Objection withdrawn!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-:-L9Gmo9T6s6D-Q7IvKE7:bmwuj5a)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8513#-:-L9GqJzHArXelWxMa_1x:bnfp4nl)*

**Pull request merged**
