### PR TITLE
lcmtypes: Deprecate unused messages

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14362.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14372)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@avalenzu for feature review please (of the message culling selection).  I can get another reviewer to double-check the build-related stuff, if you like.

\CC @hongkai-dai @siyuanfeng-tri FYI

**Comment by avalenzu** [comment]
> I can get another reviewer to double-check the build-related stuff, if you like.

Yes, please!

**Review by avalenzu — COMMENTED** [review]
:lgtm: for message culling.

> Reviewed 30 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14372#-:-MNOgHXC0lCwu9jNMA0s:b-p1r2jn)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[lcmtypes/README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14372#-MNOfzoK36yZOaC1VQpf:-MNOfzoK36yZOaC1VQpg:bbc7oqo) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ffb7c2e2f1cf60f65b50f9918023084ffc6cc9/lcmtypes/README.md#L3)):*
> ```Markdown
> The follow lcmtypes are unused within Drake and therefore are being removed:
> 
> - lcmt_body_acceleration
> ```

I've verified that the **bold** text here is a Reviewable artifact. It does not appear when viewing this file on GitHub.

**Review by avalenzu — COMMENTED** [review]
> Reviewed 2 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14372)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review please *and also* feature review of the `lcmtypes/BUILD.bazel` and `tools/workspace/lcm/lcm.bzl` changes.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14372)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,EricCousineau-TRI(platform)

___
*[tools/workspace/lcm/lcm.bzl, line 178 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14372#-MNy42JU5-8oAB6_1b_L:-MNy42JU5-8oAB6_1b_M:bjgrho1) ([raw file](https://github.com/robotlocomotion/drake/blob/2040937b028cf5608858b789fdcd1984c3572ed7/tools/workspace/lcm/lcm.bzl#L178)):*
> ```Starlark
> 
>     helper_tags = []
>     if "manual" in kwargs.get("tags", []):
> ```

BTW The pattern of `kwargs.get()` can sometimes be misleading / lead to slightly convoluted logic.

More ideal is to use the explicit argument name in the function name, and then explicitly re-forward it at the call site.

**Pull request merged**
