### PR TITLE
[geometry] Strengthen VTK to volume mesh error cases

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Add some slightly more adversarial VTK files to the test suite, and improve error reporting for VTK parse failures.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Downpayment on #20226. +(release notes: none) 
+@DamrongGuoy for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-NexhDDn6FfNMvJiigyE:bp8djl9)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
FYI @SeanCurtis-TRI  do these sorts of fixes trigger updates to the "graphics file support" doc?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-Ney6N7Z1T1D1-DblyWT:b5794o4)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
That page doesn't have enough content to require a response to this; it's largely a place-holding indicator that one can use VTKs but doesn't have the best practices/guidance yet. Obviously, the kinds of errors you're exposing should be alluded to when the full text is written.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-NfBPopMEjzXJGzrd9zA:bc5nb0b)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP79w2l7DJz9LlL0G:-NfBP79w2l7DJz9LlL0H:b-3pofsw) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/proximity/vtk_to_volume_mesh.cc#L49)):*
> ```cpp
>   std::vector<VolumeElement> elements;
>   elements.reserve(vtk_mesh->GetNumberOfCells());
>   vtkCellIterator* iter = vtk_mesh->NewCellIterator();
> ```

BTW I believe if these iterators were captured in a `vtkSmartPointer<Foo>`, you wouldn't need the `ScopeExit`.
___
*[`geometry/test/bad_tet.vtk` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP_hW1f0ZuZ6lgusF:-NfBP_hW1f0ZuZ6lgusG:b-lvyfp) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/test/bad_tet.vtk#L2)):*
> ```
> # vtk DataFile Version 2.0
> Example of bad one-tetrahedron mesh
> ```

BTW It would be nice if the "badness" were characterized. It could be inside out, it could be degenerate. It could simply be too small (I'm not sure if that's a thing at the parsing stage).

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: none) +(release notes: fix)  I will claim that this improves at least one previously inadequate error message.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-Neyq2G10Ftp5TxWLv-v:b-5k0em1)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP79w2l7DJz9LlL0G:-NfBlMzdC7tHYIz4EN6W:b-d3vnz6) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/proximity/vtk_to_volume_mesh.cc#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I believe if these iterators were captured in a `vtkSmartPointer<Foo>`, you wouldn't need the `ScopeExit`.
</blockquote></details>

:facepalm: It's like they have a different word for everything...

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/test/bad_tet.vtk` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP_hW1f0ZuZ6lgusF:-NfCg2eJBTSeyMwWIOpv:b-ngllgk) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/test/bad_tet.vtk#L2)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It would be nice if the "badness" were characterized. It could be inside out, it could be degenerate. It could simply be too small (I'm not sure if that's a thing at the parsing stage).
</blockquote></details>

Sadly, this line has some file format-imposed limit like 65 characters, so its explanatory power is not great.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP79w2l7DJz9LlL0G:-NfDCFDh1FQzUIG80EhM:bcijdl8) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/proximity/vtk_to_volume_mesh.cc#L49)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

:facepalm: It's like they have a different word for everything...
</blockquote></details>

BTW It may not be obvious but:

```c++
vtkSmartPointer<vtkCellIterator>> iter(vtk_mesh->NewCellIteraotr());
```

should be enough.
___
*[`geometry/test/bad_tet.vtk` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP_hW1f0ZuZ6lgusF:-NfDCass2XuJtCJcbX7y:b-b9un2) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/test/bad_tet.vtk#L2)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Sadly, this line has some file format-imposed limit like 65 characters, so its explanatory power is not great.
</blockquote></details>

You've given a succinct description. I'm happy. (When in doubt, you can shorten the prefix. The file is already called "bad_test".)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-NfDF-ca1UC3OB8SVYph:bnfp4nl)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/BUILD.bazel` line 633 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfCkhmz1FyzP8XK6iJv:-NfCkhmz1FyzP8XK6iJw:b-r9s4gl) ([raw file](https://github.com/RobotLocomotion/drake/blob/918819308992d24aed6844058b3ed627772f4791/geometry/BUILD.bazel#L633)):*
> ```Starlark
>     srcs = [
>         "test/bad_tet.vtk",
>         "test/cube.vtk",
> ```

nit: To prevent confusion, could we rename it to something like "cube_as_6squares.vtk" ? It's a cube represented by 6 polygons, each of which is a square.  I don't want someone misunderstood and tried to use `cube.vtk` for hydroelastics or deformables.



_Suggestion:_
```Starlark
        "test/cube_as_6squares.vtk",
```
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 3 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfDDfgF3UZsqMPbm4lE:-NfDDfgF3UZsqMPbm4lF:b-zho5on) ([raw file](https://github.com/RobotLocomotion/drake/blob/135430d2b44504e75a280035ce4afe3e7df03821/geometry/proximity/vtk_to_volume_mesh.cc#L3)):*
> ```cpp
> #include "drake/geometry/proximity/vtk_to_volume_mesh.h"
> 
> #include <sstream>
> ```

nit: I'm not sure whether we need `#include <sstream>` here?
___
*[`geometry/test/cube.vtk` line 2 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfD9d-LByi5WqPhrpSx:-NfD9d-LByi5WqPhrpSy:bi6rv84) ([raw file](https://github.com/RobotLocomotion/drake/blob/918819308992d24aed6844058b3ed627772f4791/geometry/test/cube.vtk#L2)):*
> ```
> # vtk DataFile Version 2.0
> Cube example from https://examples.vtk.org/site/VTKFileFormats/
> ```

nit: more description?



_Suggestion:_
```
Cube example represented by six squares from https://examples.vtk.org/site/VTKFileFormats/
```
___
*[`geometry/test/some_volume.vtk` line 2 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfD5Ijj0fOWNyyRe_uS:-NfD5Ijj0fOWNyyRe_uT:b-16tr9f) ([raw file](https://github.com/RobotLocomotion/drake/blob/918819308992d24aed6844058b3ed627772f4791/geometry/test/some_volume.vtk#L2)):*
> ```
> # vtk DataFile Version 2.0
> Volume example from https://examples.vtk.org/site/VTKFileFormats/
> ```

nit: more description? 





_Suggestion:_
```
Example of scalar field on uniform rectilinear grid from https://examples.vtk.org/site/VTKFileFormats/
```
___
*[`geometry/test/unstructured.vtk` line 2 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfD7Zlm0_OKXPsc2GSp:-NfD7Zlm0_OKXPsc2GSq:bi6rv84) ([raw file](https://github.com/RobotLocomotion/drake/blob/918819308992d24aed6844058b3ed627772f4791/geometry/test/unstructured.vtk#L2)):*
> ```
> # vtk DataFile Version 2.0
> Unstructured Grid Example from https://examples.vtk.org/site/VTKFileFormats/
> ```

nit: more description?



_Suggestion:_
```
Example of Unstructured Grid of Many Cell Types from https://examples.vtk.org/site/VTKFileFormats/
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP79w2l7DJz9LlL0G:-NfDMmzW1fx3tvTmgonU:b617fpw) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/proximity/vtk_to_volume_mesh.cc#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It may not be obvious but:

```c++
vtkSmartPointer<vtkCellIterator>> iter(vtk_mesh->NewCellIteraotr());
```

should be enough.
</blockquote></details>

I tried exactly that and died 1k deaths in LSAN. See `r2`. Any ideas why?
___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 3 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfDDfgF3UZsqMPbm4lE:-NfDMiWWAUrVknP_b56m:bpd3ixp) ([raw file](https://github.com/RobotLocomotion/drake/blob/135430d2b44504e75a280035ce4afe3e7df03821/geometry/proximity/vtk_to_volume_mesh.cc#L3)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit: I'm not sure whether we need `#include <sstream>` here?
</blockquote></details>

ah, nope, that's cruft.

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review -- I'm on-call tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-NfDSPeT3HAnd96LDcGt:bn36dee)* status: LGTM missing from assignee sherm1(platform)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: LGTM missing from assignee sherm1(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: LGTM missing from assignee sherm1(platform)

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfBP79w2l7DJz9LlL0G:-NfIii_93L3piHYOVzdK:bom6fwm) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c204d3972fbb44dc6aa42de8270182d1a75be5b/geometry/proximity/vtk_to_volume_mesh.cc#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I have no explanation for that. VTK does a weird thing where the reference counter for a thing is *inside* that thing itself. Which is why the above spelling is supposed to work. The smart pointer merely reaches into the cell iterator and bumps its reference counter (and subsequently decrements it).

By calling `Take` you're actively going around the reference *increment* (equivalent of "moving a shared pointer"), but, apparently, properly decrementing the counter and deleting it on the way out. So, where does the asymmetry in counter increments come from? Who is incrementing but never decrementing?

Blech.  Not worth fighting it now.
</blockquote></details>

`r7` improves one of the sites -- I don't think I know of a better spelling for the other one.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one nit

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-:-NfNp1XFDkWx8vQgyJhk:b-8gq7ov)* status: 1 unresolved discussion

___
*[`geometry/proximity/vtk_to_volume_mesh.cc` line 56 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20240#-NfNoNBA8kYu5rSMBuge:-NfNoNBA8kYu5rSMBugf:b-qf7ziu) ([raw file](https://github.com/RobotLocomotion/drake/blob/2ef2303bfd6d365db52cc2718fd81b5613d1d6cc/geometry/proximity/vtk_to_volume_mesh.cc#L56)):*
> ```cpp
>       auto msg = fmt::format(
>           "ReadVtkToVolumeMesh('{}', {}): file contains a"
>           " non-tetrahedron(type id=10) cell with type id {}, dimension {},"
> ```

nit: I'm assuming the "10" here is the value of VTK_TETRA? If so, use another `{}` here so you don't have to hard code it into the message.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20240)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

**Comment by jwnimmer-tri** [comment]
The commit message didn't make sense for release notes.  I'll use `Add more error checks when loading `*.vtk` files` as the release note.  If you'd like something different, note the change in the (forthcoming) notes PR.

**Pull request merged**
