### PR TITLE
Revert gtest upgrade and CsdpSolver printout changes due to valgrind errors

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This reverts commits 92bb2a655babff5c1171330f75dc5541a44ecb91 and 5faadf745ed1f48922b5d5281bd3e6c14fd134db.

Given that this is a holiday, will merge around 11a if CI passes and no one can review.

Context: https://drakedevelopers.slack.com/archives/C270MN28G/p1625225610076200

## Boilerplate

Dear @jwnimmer-tri,

The on-call build cop, Eric, believes that your PRs #15291 and #15281 may have
broken one or more of Drake's continuous integration builds [1]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms are tested post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-everything-valgrind-memcheck/965/
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-valgrind-memcheck/963/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly On-call Build Cop

[1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
[2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15306)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by EricCousineau-TRI** [comment]
Testing locally on my machine
```
# Pre-revert fails, post-revert succeeds
CC=clang-9 CXX=clang++-9 bazel test --compilation_mode=dbg --config=memcheck \
  //manipulation/models/jaco_description:jaco_arm_test \
  //multibody/parsing:acrobot_parser_test \
  //multibody/parsing:common_parser_test

# Pre-revert succeeds, no change post-revert
CC=clang-9 CXX=clang++-9 bazel test --compilation_mode=dbg --config=memcheck \
  //solvers:csdp_solver_internal_test \
  //solvers:sdpa_free_format_test
```

**Comment by EricCousineau-TRI** [comment]
Seems like valgrind still fails due to #15281

Will add that in here

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
:lgtm: +(status: commits are properly curated)

**Comment by EricCousineau-TRI** [comment]
Thanks!

**Pull request merged**
