### PR TITLE
Prune unused dependencies from Xenial install script

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6719)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-nightly-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Testing locally now...

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-KqTnnMAm8xwS2T5Dsle:-KqTnnMCuE45IoIbaJtY:b8k6z4c) ([raw file](https://github.com/robotlocomotion/drake/blob/db3a9412625d67356af41a96f8242afa4d198be1/setup/ubuntu/16.04/install_prereqs.sh#L129)):*
> ```Shell
> # is removed.
> 
> apt update
> ```

I'm not sure why the `update` is helping anything here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-:-KqTnvsxA5WiGKH6jugE:bmvgpx1)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-KqTtqOhXAaPk29YxP6F:-KqTtqOip_epimaIb9ek:bdrny1v) ([raw file](https://github.com/robotlocomotion/drake/blob/db3a9412625d67356af41a96f8242afa4d198be1/setup/ubuntu/16.04/install_prereqs.sh#L121)):*
> ```Shell
> # See https://github.com/RobotLocomotion/drake/issues/4464.
> # See https://github.com/bazelbuild/bazel/issues/1322.
> $(dirname $0)/ccache-bazel-wrapper-mkdeb.sh --install
> ```

Running from a clean debootstrap (+ `universe`), here I get:
```
+ ./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh --install
./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh: line 28: fakeroot: command not found
```
and then if I `sudo apt install fakeroot`, I get:
```
/usr/bin/fakeroot: line 175: alien: command not found
```

Installing both `fakeroot` and `alien` was enough to get line this to pass.

Not sure why CI didn't yell about this.  Maybe this was a rebase error subsequent to when the unprovisioned builds were launched?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-:-KqTw-vegbz6M4YvLymF:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-nightly-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-nightly-release please

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-KqTtqOhXAaPk29YxP6F:-KqU423Um1pqy_chJYiW:bqmjwcz) ([raw file](https://github.com/robotlocomotion/drake/blob/db3a9412625d67356af41a96f8242afa4d198be1/setup/ubuntu/16.04/install_prereqs.sh#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Running from a clean debootstrap (+ `universe`), here I get:
```
+ ./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh --install
./setup/ubuntu/16.04/ccache-bazel-wrapper-mkdeb.sh: line 28: fakeroot: command not found
```
and then if I `sudo apt install fakeroot`, I get:
```
/usr/bin/fakeroot: line 175: alien: command not found
```

Installing both `fakeroot` and `alien` was enough to get line this to pass.

Not sure why CI didn't yell about this.  Maybe this was a rebase error subsequent to when the unprovisioned builds were launched?
</blockquote></details>

Added.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-KqTnnMAm8xwS2T5Dsle:-KqU41G7ZajsaJpfBSUM:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/db3a9412625d67356af41a96f8242afa4d198be1/setup/ubuntu/16.04/install_prereqs.sh#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure why the `update` is helping anything here?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6719)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6719)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6719#-:-KqUN9cYc2LVM9yS_uy5:bnfp4nl)*

**Pull request merged**
