### PR TITLE
Remove some obsolete sentences from the build cop manual.

### PR DESCRIPTION
**Pull request by david-german-tri**
@liangfok for feature review, @sammy-tri for platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3667)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-KTFH16AaPPcMKKpyHsk:-KTFH16BjzB4_RSTqWi7:b-e9hrqc) ([raw file](https://github.com/robotlocomotion/drake/blob/5841947f336d0add02bc1cc8a648dc4f3c96ed00/drake/doc/buildcop.rst#L147)):*
> ```reStructuredText
> in that particular run.
> 
> Build Known Not to Work
> ```

We've got a number of yellow and red nightlies on the dashboard now.  Are they expected to be blue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-KTFH16AaPPcMKKpyHsk:-KTFHUe4UxENH10n_01y:b-gu7407) ([raw file](https://github.com/robotlocomotion/drake/blob/5841947f336d0add02bc1cc8a648dc4f3c96ed00/drake/doc/buildcop.rst#L147)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> We've got a number of yellow and red nightlies on the dashboard now.  Are they expected to be blue?
</details>
They are not.  Chatter about that in Slack #buildcop right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-KTFH16AaPPcMKKpyHsk:-KTFHb-RGeb6ojbDeMnc:b7azi7n) ([raw file](https://github.com/robotlocomotion/drake/blob/5841947f336d0add02bc1cc8a648dc4f3c96ed00/drake/doc/buildcop.rst#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> They are not.  Chatter about that in Slack #buildcop right now.
</details>
(and to be specific, the number is two :-) )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-KTFH16AaPPcMKKpyHsk:-KTFJCJMiSuxMNJwK7pa:byv5ea9) ([raw file](https://github.com/robotlocomotion/drake/blob/5841947f336d0add02bc1cc8a648dc4f3c96ed00/drake/doc/buildcop.rst#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> (and to be specific, the number is two :-) )
</details>
Oh, also there are continuous failures.  Updated to reference the correct dashboard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-KTFH16AaPPcMKKpyHsk:-KTFJOoYbuQCjEin2MU6:b3ajc6l) ([raw file](https://github.com/robotlocomotion/drake/blob/5841947f336d0add02bc1cc8a648dc4f3c96ed00/drake/doc/buildcop.rst#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, also there are continuous failures.  Updated to reference the correct dashboard.
</details>
s/the correct/a more useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-:-KTFJVdMaVjeUvhJnvg5:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3667#-:-KTG3DJwa7iVAcg79k-S:bnfp4nl)*

**Pull request merged**
