### PR TITLE
Change SNOPT to use in-tree build file

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
There are actually four commits here:
1. Switch snopt to custom git rules, instead of Bazel's git wrapper

    In the future we want to support non-git sources for SNOPT (and in particular, sources with no BUILD files); by having our own direct implementation of the repository rule, it is easier to mix and match the pieces we need.  (Plus, Bazel's implementation is actually pretty lame.)

2. Import BUILD rules from RobotLocomotion/snopt

    Copied from https://github.com/RobotLocomotion/snopt as of commit `0f475624131c9ca4d5624e74c3f8273ccc926f9b`.

    Co-authored-by: David German <...>
    Co-authored-by: Jamie Snape <...>

   This is a straight copy (though cat'ing them into one file) from our existing `BUILD` rules from the RL/snopt repository.

3. Rework the copied BUILD files into one; use it by default.

    This means that the RL/snopt repository's `BUILD` files are now dead code as far as Drake is concerned.

 4. Add some more comments.

The overall effect should be an entirely non-functional change, but prepares us to:
- Use SNOPT from sources other than git (#7240), such as when a user has their own source archive already but doesn't have RobotLocomotion credentials.  (The source archive doesn't have a `BUILD` file of course, so Drake needs to have a `package.BUILD.bazel` in-tree.)
- Inter-operate with other releases of SNOPT (#245, #1647, #4611) by amending our `package.BUILD.bazel` file to detect and configure itself based on the provided snopt.

The full branch with future work is at https://github.com/jwnimmer-tri/drake/commits/snopt.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7932)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/snopt/package.BUILD.bazel, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4LmMdrIMtTdo_DSg7n:-L4LmMdrIMtTdo_DSg7o:b4kecee) ([raw file](https://github.com/robotlocomotion/drake/blob/639da7991192c89104c0af305ba64f9306ec43d5/tools/workspace/snopt/package.BUILD.bazel#L14)):*
> ```
>     ],
>     linkopts = ["-lm"],
>     # Link statically so that Fortran MAIN__ resolution works on gcc.
> ```

BTW I know this is a straight import, but can you modify this to mention that we are required to statically link for licensing reasons with respect to our Drake binary distributions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jamiesnape** [comment]
So are you ultimately going to support https://github.com/snopt/snopt-interface and the binaries?

**Comment by jwnimmer-tri** [comment]
> So are you ultimately going to support https://github.com/snopt/snopt-interface and the binaries?

Interesting find!  I don't recall seeing that yet.  I will give it a try in my next PR -- so far I had it drafted by using the cexamples headers from the tarball.  It looks like the snopt-interface though might allow me to get rid of a reinterpret_cast that I had to use in the next PR, which would at least help me sleep better at night.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/snopt/package.BUILD.bazel, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4LmMdrIMtTdo_DSg7n:-L4O4vPSDgXcMvqKwl-b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/639da7991192c89104c0af305ba64f9306ec43d5/tools/workspace/snopt/package.BUILD.bazel#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I know this is a straight import, but can you modify this to mention that we are required to statically link for licensing reasons with respect to our Drake binary distributions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-:-L4O4xIJtqL33YayVH8U:b-xuhf40)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
In my WIP branch I have a patch now that actually hides (always) and strips (except in debug) all of the SNOPT symbols.  I'll file that after this one has merged and passed the full CI matrix.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for macOS and feature review, please.
+@EricCousineau-TRI for Ubuntu and platform review, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/git.bzl, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aYWd5yrO6VRBoKG1t:-L4aYWd5yrO6VRBoKG1u:bavids0) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L4)):*
> ```Python
> 
> def _run_git(repo_ctx, *args):
>     result = repo_ctx.execute(["git", "--git-dir=.git"] + list(args))
> ```

What happens if we don't pass `--git-dir` option here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-:-L4aatN2J3Rr9w6--wZr:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor btws and one question about `git_clone` vs `git_repository`.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4alzpCrwy9X6qNdNrp:b9f9569) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
> ```Python
>     this rule should generally not be used.  The recommemded alternative is the
>     github.bzl rules (in the same folder as this rule).
>     """
> ```

Is there a reason that we cannot use Bazel's `git_repository`?
https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl#L133

If not, or if there's reason for this implementation (e.g. simpler), could that be documented here?

---

*[tools/workspace/snopt/package.BUILD.bazel, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4ajZkZ-3NmscTH9btp:-L4ajZk_H51TI5LYuGqn:b-nqwfxz) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/snopt/package.BUILD.bazel#L32)):*
> ```
> # TODO(jwnimmer-tri) Use a different value here, depending on what's needed for
> # a specific version of snopt.
> _LIBF2C = "libf2c/"
> ```

BTW One thing I've been wondering: Can `BUILD` files even export symbols that are not targets?
If not, should we really bother "hiding" constants like this? (it seems like it'd be more of a local variable in a `__main__` file than a constant)

---

*[tools/workspace/snopt/package.BUILD.bazel, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4ajNkdDiLpUpUVO8XH:-L4ajNkdDiLpUpUVO8XI:b-5ogjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/snopt/package.BUILD.bazel#L48)):*
> ```
>     srcs = [],
>     outs = [_LIBF2C + "arith.h"],
>     cmd = "$(location :arithchk) > $(@)",
> ```

BTW Why not just use `$@` rather than `$(@)`, since you use `$<` elsewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-:-L4amZaXp4wJv0OW-FIr:b-a1t5pw)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4anBF0uAiyN0Tjc_lf:baa2f2t) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a reason that we cannot use Bazel's `git_repository`?
https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl#L133

If not, or if there's reason for this implementation (e.g. simpler), could that be documented here?
</blockquote></details>

I guess it's because SNOPT is in a private repository but `git_repository` does not support authentication yet (this is documented in `snopt/package.BUILD.bazel`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4ansm8RiyxJB194aCu:b-jxcb4h) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
I think the issue is that *native* `*git_repository` rules are implemented in jGit and may not support SSH authentication.

From what I can see, it looks like the Skylark `*git_repository` rules just uses system `git`, and thus bypasses that issue. (It's a wee bit confusing that they're named the same, but meh.) Per the doc page URL:

> If you are using a private repository, prefer the Skylark git repository rules, which will use your system's git install (instead of jGit). These rules are built into Bazel and have the same API as the native rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4aoPlKhZez9sgYIpTf:bibrhx1) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I think the issue is that *native* `*git_repository` rules are implemented in jGit and may not support SSH authentication.

From what I can see, it looks like the Skylark `*git_repository` rules just uses system `git`, and thus bypasses that issue. (It's a wee bit confusing that they're named the same, but meh.) Per the doc page URL:

> If you are using a private repository, prefer the Skylark git repository rules, which will use your system's git install (instead of jGit). These rules are built into Bazel and have the same API as the native rules.
</blockquote></details>

Yes, there are two different `git_repository` rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4aqEJjKZn0wMXyR0cl:b-89pujq) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, there are two different `git_repository` rules.
</blockquote></details>

We use our own implementation because for SNOPT we perform additional steps beyond just "clone and add a BUILD file".  (We remove other BUILD files, and soon we'll offer a flag to use a tarball instead of a clone.)  None of Bazel's built-in rules are factored to be extensible to perform these additional actions.

I'll work on the documentation in this PR to clarify this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4auqrdrmQBbvtpHPy9:b3ocjsv) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We use our own implementation because for SNOPT we perform additional steps beyond just "clone and add a BUILD file".  (We remove other BUILD files, and soon we'll offer a flag to use a tarball instead of a clone.)  None of Bazel's built-in rules are factored to be extensible to perform these additional actions.

I'll work on the documentation in this PR to clarify this.
</blockquote></details>

On that note, why are we actually keeping the `BUILD` files in SNOPT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4avIxbJ8lxGCCNocOa:b-2sc6p2) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

On that note, why are we actually keeping the `BUILD` files in SNOPT?
</blockquote></details>

I was going to have a separate discussion about that.  In any case, I shouldn't remove them from RLG/snopt until this PR has merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4avYtRclFxgVUWXmZ3:bagi5q7) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was going to have a separate discussion about that.  In any case, I shouldn't remove them from RLG/snopt until this PR has merged.
</blockquote></details>

I don't think it would be unreasonable to bump the SHA at the same time and save complicating the download code, but that is just a personal view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4avfGlCfLiXbh7Y4VN:btx3xv3) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I don't think it would be unreasonable to bump the SHA at the same time and save complicating the download code, but that is just a personal view.
</blockquote></details>

(Moving follow-up comment to a separate discussion for tracking.)

---

*[tools/workspace/git.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aw060aCr_hyCNH9Y_:-L4aw060aCr_hyCNH9Ya:bfvpel8) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L24)):*
Per above discussion:

> We use our own implementation because for SNOPT we perform additional steps beyond just "clone and add a BUILD file".

I can understand why we have `snopt_repository`, but I'm not sure why we have `git_clone`, which seems like a subset of the functionality of Bazel's Skylark `git_repository`.

Could we potentially just use the Bazel Skylark rule in lieu of `git_clone`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/git.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aw060aCr_hyCNH9Y_:-L4awIm57zKuDidH-lng:b-4dqad3) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Per above discussion:

> We use our own implementation because for SNOPT we perform additional steps beyond just "clone and add a BUILD file".

I can understand why we have `snopt_repository`, but I'm not sure why we have `git_clone`, which seems like a subset of the functionality of Bazel's Skylark `git_repository`.

Could we potentially just use the Bazel Skylark rule in lieu of `git_clone`?
</blockquote></details>

No, we can't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4awE25Y8e3TGdP_z3r:b55ek7u) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

(Moving follow-up comment to a separate discussion for tracking.)
</blockquote></details>

I agree with Jamie - at least, it'd be nice to ensure that this works on a SHA where the BUILD files are not present. If this will be tested, it seems like it'd be relatively simple to upstream the SHA before this PR merges?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4awTJoZiibOWEAU0cp:bq3aqsl) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I agree with Jamie - at least, it'd be nice to ensure that this works on a SHA where the BUILD files are not present. If this will be tested, it seems like it'd be relatively simple to upstream the SHA before this PR merges?
</blockquote></details>

How about this: stop speculating until I push the fixes to this PR.  You are just wasting your time until I have a chance to write up a more thorough rationale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/git.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aw060aCr_hyCNH9Y_:-L4awW2Sij9Z-qbEHWMZ:b3a6os3) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No, we can't.
</blockquote></details>

Ah, because it's simple a `repo_ctx.execute` from an external `repo_ctx`.
Could that be mentioned in the documentation?
And could the fact that this acts on an existing repository be mentioned in the documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tools/workspace/snopt/package.BUILD.bazel, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4ajZkZ-3NmscTH9btp:-L4aqiUkcp7OxQVosApU:bepvdp2) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/snopt/package.BUILD.bazel#L32)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW One thing I've been wondering: Can `BUILD` files even export symbols that are not targets?
If not, should we really bother "hiding" constants like this? (it seems like it'd be more of a local variable in a `__main__` file than a constant)
</blockquote></details>

OK In bzl files you could import/export named constants, and absent any style guide rule that I'm missing, I prefer keep the BUILD names similar.

---

*[tools/workspace/snopt/package.BUILD.bazel, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4ajNkdDiLpUpUVO8XH:-L4c5awaycUHOBbJIUJZ:bk8vx8t) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/snopt/package.BUILD.bazel#L48)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Why not just use `$@` rather than `$(@)`, since you use `$<` elsewhere?
</blockquote></details>

OK This is unchanged in this PR, its what RLG/snopt has.

---

*[tools/workspace/git.bzl, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aYWd5yrO6VRBoKG1t:-L4bxYWgepvln8ToEKps:b-ytga5l) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L4)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

What happens if we don't pass `--git-dir` option here?
</blockquote></details>

Done.  (Added comments in other file.)

---

*[tools/workspace/git.bzl, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4alzpCrwy9X6qNdNro:-L4c1asogInBdPD0qs9g:b-xjmgxj) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L23)):*
> Is there a reason that we cannot use Bazel's git_repository?  If not, or if there's reason for this implementation (e.g. simpler), could that be documented here?

I've tried to document why its this way, including moving the helpers into this same file.

> ... it'd be nice to ensure that this works on a SHA where the BUILD files are not present.

I have done that locally with SNOPT 7.5.  As far as CI goes, it would be tested either when we rm the BUILD files from RLG/snopt and bump the commit here, or when we add CI coverage for SNOPT 7.5 source tarball.

---

*[tools/workspace/git.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7932#-L4aw060aCr_hyCNH9Y_:-L4c1DMuT4J1MeBZJQuy:b-mwatlg) ([raw file](https://github.com/robotlocomotion/drake/blob/47963fb7a121eadb021cff4dc98bf98076803d0f/tools/workspace/git.bzl#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Ah, because it's simple a `repo_ctx.execute` from an external `repo_ctx`.
Could that be mentioned in the documentation?
And could the fact that this acts on an existing repository be mentioned in the documentation?
</blockquote></details>

I've reworked this all to try to clarify what's happening and why.  PTAL and let me know if there's more I can do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7932)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
> > So are you ultimately going to support https://github.com/snopt/snopt-interface and the binaries?
>
> Interesting find! I don't recall seeing that yet. I will give it a try in my next PR ...

In #7975 at least I've left the API alone.  I guess we are using some arcane API in Drake, not the default C bindings as advertised in the SNOPT manual and declared by the `snopt-interface` github repository.  It would be future work to respell our API calls to the other phrasing (which admittedly would be much cleaner) at which point we could use the `snopt-interface` repository for the headers if that were helpful (they are also in the SNOPT source tarballs).

**Comment by jamiesnape** [comment]
I think we are basically using an old `f2c` based implementation. They switched to wrapping F90.

**Comment by jefesaurus** [comment]
I'm guessing when the documentation mentions claims it is "reentrant" and  "threadsafe" that is referring to the f90 version only, btw. The f2c version uses static variables everywhere, and I couldn't fix it.

**Comment by jwnimmer-tri** [comment]
That makes sense.  In #7984 hopefully we can fix that by porting to F90.

**Pull request merged**
