### PR TITLE
[geometry] reverse `no_cleanup` logic

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
(Feel free to assign this to me if you didn't have someone else in mind already.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675#-:-N8UvfM262w4JED21czi:ba0f58j)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by zachfang — COMMENTED** [review]
Thanks! I was waiting for the CI to pass in case I broke something.
I will take your offer for an extra pair of eyes. +@seancurtis-tri for feature.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675#-:-N8UwYDECZF5supVxb-6:b62i29k)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

I found to editorial things right around where the changes happened. Addressing them in this PR is optional.

+@jwnimmer-tri for platform review, please.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675#-:-N8VNA7WESAfMzqibFpw:b-ya9k5b)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

___
*[`geometry/render_gltf_client/internal_render_client.h` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17675#-N8VKxhT4xSVlU0-KPQ2:-N8VKxhT4xSVlU0-KPQ3:b-fsi9u6) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb680eede424c86bd7455ada090ff58c0248a04/geometry/render_gltf_client/internal_render_client.h#L33)):*
> ```objc
> 
>    @note
>      RenderEngineGltfClientParams.default_label struct member is not relavant
> ```

BTW This jumped out at me when I was looking at the file

s/relavant/relevant
___
*[`geometry/render_gltf_client/render_engine_gltf_client_params.h` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17675#-N8VLbO66m1sfVHvT38G:-N8VLbO66m1sfVHvT38H:b-4htxk4) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb680eede424c86bd7455ada090ff58c0248a04/geometry/render_gltf_client/render_engine_gltf_client_params.h#L34)):*
BTW The phrase "no longer needed" is an interesting one. It's difficult to define because "need" is unclear. So, here are three options for avoiding the vaguness

It might be worth being more precise:

> By default, after a server image response has been loaded into the client's memory, the glTF scene file and images will be deleted.

Alternatively, if you still like to keep it nicely vague:

> If `cleanup == true`, the glTF scene file and server response image will be deleted when the client is done with them.

Or the absolutely minimum change:

> By default (`cleanup=true`), as soon as __*the client no longer needs*__ the glTF scene file and server image response, they will be deleted.



_Suggestion:_
```objc
   By default (`cleanup=true`), as soon as a glTF scene file as
   well as server image response for a given frame are no longer needed they
   will be deleted.
```

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +(status: single reviewer ok)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_gltf_client/internal_render_client.h` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17675#-N8VKxhT4xSVlU0-KPQ2:-N8VU_hi5MkJDbBsBEKZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb680eede424c86bd7455ada090ff58c0248a04/geometry/render_gltf_client/internal_render_client.h#L33)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This jumped out at me when I was looking at the file

s/relavant/relevant
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/render_engine_gltf_client_params.h` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17675#-N8VLbO66m1sfVHvT38G:-N8VUrPyBPWjLHvgqP51:b-rnpn65) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb680eede424c86bd7455ada090ff58c0248a04/geometry/render_gltf_client/render_engine_gltf_client_params.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The phrase "no longer needed" is an interesting one. It's difficult to define because "need" is unclear. So, here are three options for avoiding the vaguness

It might be worth being more precise:

> By default, after a server image response has been loaded into the client's memory, the glTF scene file and images will be deleted.

Alternatively, if you still like to keep it nicely vague:

> If `cleanup == true`, the glTF scene file and server response image will be deleted when the client is done with them.

Or the absolutely minimum change:

> By default (`cleanup=true`), as soon as __*the client no longer needs*__ the glTF scene file and server image response, they will be deleted.

</blockquote></details>

Done. Being vague is not the intent :sweat_smile:. Replaced with the more precise suggestion. I also changed some wording to avoid repeating `delete` in the comment.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17675)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @zachfang)

**Pull request merged**
