### PR TITLE
doc: Add release notes v0.36.0

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo-WWPl9kAs2wXwHvC0:-Mo-WWPm84SWHX2Bzcx5:b-vc91ul) (no related file):*
I'd like to hold the release until #16061 is merged, if possible.

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo-WWPl9kAs2wXwHvC0:-Mo-tQrSEjmEMWgCGDJ_:b-hhfh28) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'd like to hold the release until #16061 is merged, if possible.
</blockquote></details>

That seems extremely reasonable to me.  Realistically as long as this release goes out before too many people start going on vacation we're good.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo-WWPl9kAs2wXwHvC0:-Mo-z885EVTrSL99IAj9:b-896fix) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

That seems extremely reasonable to me.  Realistically as long as this release goes out before too many people start going on vacation we're good.
</blockquote></details>

Done.

---

**Comment by jwnimmer-tri** [comment]
___
*[doc/_release-notes/v0.36.0.md, line 51 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo5IX_qBnufJJIMjzZQ:-Mo5IX_qBnufJJIMjzZR:ba385mk) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd8ebdfdda3ba14dc9711ff9f210193ae041cc2/doc/_release-notes/v0.36.0.md#L51)):*
> ```Markdown
> 
> * Rename `SurfaceMesh` to `TriangleSurfaceMesh` ([#15962][_#15962])
> * Add `IrisInConfigurationSpace` with Ibex geometry optimization ([#15789][_#15789])
> ```

nit Per recent relnotes traditions, `//geometry/optimization/...` changes (15789, 16017, 16016, 15964) should be filed under Mathematical Program, not Multibody Geometry.  We should teach the tool to do this for us, but we haven't yet.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v0.36.0.md, line 55 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo5F_H64noFsE25g_Qq:-Mo5F_H7-DEGCnkLGacg:b-41zp5p) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd8ebdfdda3ba14dc9711ff9f210193ae041cc2/doc/_release-notes/v0.36.0.md#L55)):*
> ```Markdown
> * Cleanup memory management in `GraphOfConvexSets`; this includes API-breaking changes (allowable as this is an unstable experimental API) removing `VertexIds()` (Use `Vertices()` instead) and changing the return value of `Edges()`. ([#16016][_#16016])
> * Toppra: Use one solver for every optimization and fix zero velocity bug ([#15964][_#15964])
> * Migrate hydroelastic modulus in property functions from a material property to a contact property (allowable as this is an unstable experimental API). ([#16009][_#16009])
> ```

attn @seancurtis-tri -- should we be rolling up some set of hydro related changes under the typical "progress on hydroelastic contact"-ish one-liner?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, and @SeanCurtis-TRI)

___
*[doc/_release-notes/v0.36.0.md, line 55 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo5F_H64noFsE25g_Qq:-Mo5dBXk7TDnhWArRY8w:b-jlzisd) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd8ebdfdda3ba14dc9711ff9f210193ae041cc2/doc/_release-notes/v0.36.0.md#L55)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

attn @seancurtis-tri -- should we be rolling up some set of hydro related changes under the typical "progress on hydroelastic contact"-ish one-liner?
</blockquote></details>

I am happy to go with whatever #dynamics prefers.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @jwnimmer-tri, @rpoyner-tri, and @SeanCurtis-TRI)

___
*[doc/_release-notes/v0.36.0.md, line 55 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo5F_H64noFsE25g_Qq:-Mo5f6Io8nKKcfN7m8CF:b-rtto89) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd8ebdfdda3ba14dc9711ff9f210193ae041cc2/doc/_release-notes/v0.36.0.md#L55)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I am happy to go with whatever #dynamics prefers.
</blockquote></details>

Roll this under the "hydro under construction" section.
___
*[doc/_release-notes/v0.36.0.md, line 35 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo5ezWdDpsVC3rnoO15:-Mo5ezWdDpsVC3rnoO16:bqzkode) ([raw file](https://github.com/robotlocomotion/drake/blob/8887401915e95b21d693b51b520f558de0f73a91/doc/_release-notes/v0.36.0.md#L35)):*
> ```Markdown
> New features
> 
> * Rename `SurfaceMesh` to `TriangleSurfaceMesh` ([#15962][_#15962])
> ```

nit: Roll this under the "hydro under construction" section.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @jwnimmer-tri, @rpoyner-tri, @SeanCurtis-TRI, and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I've pushed my fixes now.

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064#-:-Mo6NpMTCafYfLuWoe68:b-cyr88g)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-Mo9XU7B9P2uH6ILYaia:b7dynmo) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
> ```Markdown
> * Add `systems::sensors::OptitrackReceiver` ([#16011][_#16011])
> * Add `VectorX`-returning value methods to `systems::framework::BasicVector` and `systems::framework::DiscreteValues` ([#16051][_#16051])
> * Return `const VectorX&` rather than `VectorBlock` where possible from `port.Eval()` and similar methods. ([#16031][_#16031])
> ```

This is also a Breaking Change (i.e., it should also be mentioned up top).
___
*[doc/_release-notes/v0.36.0.md, line 215 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XJYI4P7bcRrvvF5Q:-Mo9XJYI4P7bcRrvvF5R:b-1xrtqz) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L215)):*
> ```Markdown
> * Deprecate installed use of kuka_simulation and kuka_plan_runner ([#16061][_#16061])
> * Deprecate the direct use of YAML::Node by users ([#16057][_#16057])
> * Deprecate installed use of kuka_simulation and kuka_plan_runner ([#16061][_#16061])
> ```

nit 16061 This duplicates the line that's two lines prior.

**Review by ggould-tri — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064#-:-Mo9VXSz-Yih8-2KFjek:b-ucfknh)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

**Comment by ggould-tri** [comment]
___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-Mo9b1g2CG6VkfEjoZkK:b-6ogs7u) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is also a Breaking Change (i.e., it should also be mentioned up top).
</blockquote></details>

I don't see what's breaking here -- I don't see any changed signatures or new pure virtuals in headers.  Nor is the PR tagged as breaking.  Can you clarify?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-Mo9oKKKCJj4foBAGJTb:b-k61i09) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I don't see what's breaking here -- I don't see any changed signatures or new pure virtuals in headers.  Nor is the PR tagged as breaking.  Can you clarify?
</blockquote></details>

#16031 is tagged "breaking change" because it changes return types. The PR description lists the particular changes. Please LMK if you want me to add text about that here.

**Comment by ggould-tri** [comment]
___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-Mo9pGCu44aMasG2cGIk:b-mk3m82) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

#16031 is tagged "breaking change" because it changes return types. The PR description lists the particular changes. Please LMK if you want me to add text about that here.
</blockquote></details>

Ah, somehow reviewable was showing this on the #16051 line until I reloaded.  That's clearer.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @sherm1)

___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-Mo9p91Q49Zlij1gtD23:b-6tixyq) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Ah, somehow reviewable was showing this on the #16051 line until I reloaded.  That's clearer.
</blockquote></details>

Oops, I probably should have said "16031" in my review comment.  It's easy to get the "which discussion is about which bullet point" mixed up across different revisions.  I always try to note the number in my review threads, but missed on it this time around.  The PR overview has some pretty good text for the break change message above.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.36.0.md, line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16064#-Mo9XU7B9P2uH6ILYai_:-MoA3G404pS7Lgb9v1kG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60f8d6671de8f264eb8d77a270fd9ed80d7f2687/doc/_release-notes/v0.36.0.md#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I probably should have said "16031" in my review comment.  It's easy to get the "which discussion is about which bullet point" mixed up across different revisions.  I always try to note the number in my review threads, but missed on it this time around.  The PR overview has some pretty good text for the break change message above.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: as reviewer.

> Reviewed 2 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064#-:-ModWvpD5e1vA2rGZNrZ:b-m74cdy)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16064#-:-Moe5bpMBmJ6oJSqjV-N:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
