### PR TITLE
Install Drake and LCM Python bindings from Bazel

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6280)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Reviewed 4 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/BUILD, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km3Syt0kHCIS7YuGBNI:-Km3Syt0kHCIS7YuGBNJ:bb0pbo) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/drake/BUILD#L41)):*
> ```Python
>     license_docs = ["//:LICENSE.TXT"],
>     targets = ["libdrake.so"],
>     deps = ["//drake/bindings:install"],
> ```

BTW, does this need `@drake`? (Also the license, I guess, which seems to have been missed in the great addition-of-`@drake`.)

---

*[tools/install.bzl, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6qb2Jen8UbUc6km9s:-Km6qb2KC40jfnwEqhwa:b-secol7) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L194)):*
> ```Python
>             of :obj:`str` to :obj:`str`): List of prefixes to strip from the
>             input path before prepending the destination. A :obj:`dict` may be
>             given to supply a mapping of prefixes to strip to destination path.
> ```

I'm pretty sure this is wrong. I *think* maybe you meant "mapping of file extension to [list[s] of] prefixes to strip"? (I'll let you decide if the text is more or less clear with the bits in []'s, or if something else is better still.)

---

*[tools/install.bzl, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6r8w27cjQIsrMI3MY:-Km6r8w27cjQIsrMI3MZ:b-el1kg4) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L215)):*
> ```Python
>                 sp = strip_prefix
> 
>             p = _output_path(ctx, a, sp)
> ```

For clarity/consistency, maybe rename the parameter to `strip_prefixes` (and then this line won't change)?

---

*[tools/install.bzl, line 230 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6rbpXnZTwvnqBzvYb:-Km6rbpXnZTwvnqBzvYc:b-oakrm2) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L230)):*
> ```Python
>     }
>     strip_prefix = {
>         "so": ctx.attr.library_strip_prefix,
> ```

BTW, should we have `archive_strip_prefix` and `runtime_strip_prefix` for consistency? (Even if they aren't used ATM...)

---

*[tools/lcm.BUILD, line 170 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tIuZpZegBHS3r73B:-Km6tIu_H6Jgw-QIchoE:bxm4yf0) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L170)):*
> ```
>     name = "lcm-python",
>     srcs = ["__init__.py"],  # Shim, from the genrule above.
>     deps = [":lcm-python-private"],
> ```

Eh? I don't see such a target; did you mean `lcm-python-upstream`?

---

*[tools/lcm.BUILD, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tYH7jTOHcGaLtJ4g:-Km6tYH80pubrrC_oqWC:bmc415v) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L221)):*
> ```
>     doc_dest = DOC_DEST,
>     library_dest = "lib/python2.7/site_packages/lcm",
>     license_docs = LICENSE_DOCS,
> ```

Yuck, this is why I'm not sure this approach to enforcing licenses makes sense... (Also, if this sort of thing is going to be happening, we should make sure it doesn't create duplicate install actions; I suspect, without having checked, that right now it does...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/BUILD, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km3Syt0kHCIS7YuGBNI:-Km73RKTYC-75Yo1kCsa:b2iyyjf) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/drake/BUILD#L41)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, does this need `@drake`? (Also the license, I guess, which seems to have been missed in the great addition-of-`@drake`.)
</blockquote></details>

No it is within drake.

---

*[tools/lcm.BUILD, line 170 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tIuZpZegBHS3r73B:-Km73kfry8HDjZdrF61v:b-xsir71) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L170)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Eh? I don't see such a target; did you mean `lcm-python-upstream`?
</blockquote></details>

Indeed. You reviewed an old revision.

---

*[tools/lcm.BUILD, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tYH7jTOHcGaLtJ4g:-Km73atKe7Mxr9MIKfsT:bf4yh2f) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L221)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Yuck, this is why I'm not sure this approach to enforcing licenses makes sense... (Also, if this sort of thing is going to be happening, we should make sure it doesn't create duplicate install actions; I suspect, without having checked, that right now it does...)
</blockquote></details>

It is not great, I know, but we should fix it in a follow up with a better overall solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lcm.BUILD, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tYH7jTOHcGaLtJ4g:-Km7G0YSMvnaTOaB0YIt:bn4xqqp) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L221)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It is not great, I know, but we should fix it in a follow up with a better overall solution.
</blockquote></details>

Okay, but we definitely should fix it so we aren't creating duplicate install actions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lcm.BUILD, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tYH7jTOHcGaLtJ4g:-Km7K7NTALi0n8wERUw-:bx2pxwy) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L221)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, but we definitely should fix it so we aren't creating duplicate install actions.
</blockquote></details>

In the follow up, yes. The duplicate is harmless in this instance for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.bzl, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6qb2Jen8UbUc6km9s:-Km7NjmdFjrA5Hs4zEk-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L194)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm pretty sure this is wrong. I *think* maybe you meant "mapping of file extension to [list[s] of] prefixes to strip"? (I'll let you decide if the text is more or less clear with the bits in []'s, or if something else is better still.)
</blockquote></details>

Done.

---

*[tools/install.bzl, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6r8w27cjQIsrMI3MY:-Km7NojD6RGqypBhIroP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L215)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

For clarity/consistency, maybe rename the parameter to `strip_prefixes` (and then this line won't change)?
</blockquote></details>

Done.

---

*[tools/install.bzl, line 230 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6rbpXnZTwvnqBzvYb:-Km7NxmaOM0KX9bzGMa0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L230)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, should we have `archive_strip_prefix` and `runtime_strip_prefix` for consistency? (Even if they aren't used ATM...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.bzl, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6qb2Jen8UbUc6km9s:-Km7SDkLSm9yUB-9r-dn:b2nhouv) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L194)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TY!

---

*[tools/install.bzl, line 230 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6rbpXnZTwvnqBzvYb:-Km7SIWU5ySnQMeZ0H5C:b2nhouv) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/install.bzl#L230)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TY!

---

*[tools/lcm.BUILD, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km6tYH7jTOHcGaLtJ4g:-Km7SRfyd2TufEtN6DpM:bs5ed97) ([raw file](https://github.com/robotlocomotion/drake/blob/05955b19b3d4ad9d33c17a083cf3dd70b55c28b2/tools/lcm.BUILD#L221)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

In the follow up, yes. The duplicate is harmless in this instance for now.
</blockquote></details>

Yes, that's what I meant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lcm.BUILD, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km7VpyZiEVTSlu1DFC-:-Km7Vpy_RVboyRlaxjbe:b-oluvj4) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/lcm.BUILD#L161)):*
> ```
> 
> py_library(
>     name = "lcm-python-upstream",
> ```

BTW, why does this need to be split?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-:-Km7W7_3tTwIyx-P-428:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.BUILD, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km7VpyZiEVTSlu1DFC-:-Km7W9GCxWngJhhjM0Nx:b-b2wz3w) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/lcm.BUILD#L161)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, why does this need to be split?
</blockquote></details>

To remove the hack that does not work outside of the sandbox.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/lcm.BUILD, line 161 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-Km7VpyZiEVTSlu1DFC-:-Km7YRf0yqMkRfsipH-I:b-p0yqs0) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/lcm.BUILD#L161)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

To remove the hack that does not work outside of the sandbox.
</blockquote></details>

Ah, I see... because the `-upstream` is the one that gets installed. D'oh; I missed that :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
@soonho-tri Can you look at this today, or should I reassign the platform review?

**Comment by soonho-tri** [comment]
Sorry for the delay, I'll finish it before lunch today.

**Comment by soonho-tri** [comment]
:lgtm: (a BTW)

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 223 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-KmC9HNS_4c6wFHY1orh:-KmC9HNS_4c6wFHY1ori:bx2n9go) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/install.bzl#L223)):*
> ```Python
>             if type(strip_prefixes) == "dict":
>                 strip_prefix = strip_prefixes.get(a.extension,
>                                                   strip_prefixes[None])
> ```

BTW, I think it's worth mentioning the constraint "if `strip_prefixes` is a dict, `strip_prefixes[None]` should be provided" in the above documentation  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-:-KmC9yRx9FYpsaDzv9a3:b-qxkpxg)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 223 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-KmC9HNS_4c6wFHY1orh:-KmCD8WQnKs49ZC-djzQ:b-pmv62p) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/install.bzl#L223)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's worth mentioning the constraint "if `strip_prefixes` is a dict, `strip_prefixes[None]` should be provided" in the above documentation  
</blockquote></details>

Hmm, yes, we could do that, or alternatively we could fix the logic to use an empty list if there is no entry for `None`. Either would be okay. However, now that you mention it, `dests` ought to have such a note [also]... Maybe:

```
The :obj:`dict` must have an entry with the key ``None``, which is used as
the default if there is no entry for the specific extension.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 223 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-KmC9HNS_4c6wFHY1orh:-KmCEbrx2YtzGy-MUKwu:bngjni9) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/install.bzl#L223)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Hmm, yes, we could do that, or alternatively we could fix the logic to use an empty list if there is no entry for `None`. Either would be okay. However, now that you mention it, `dests` ought to have such a note [also]... Maybe:

```
The :obj:`dict` must have an entry with the key ``None``, which is used as
the default if there is no entry for the specific extension.
```
</blockquote></details>

I understand we're fine since this function `_install_actions` is only called from `_install_cc_actions` which does the right thing. But I think for the future reference, it's good to document it (or refactor to eliminate the constraint).

If this PR is urgent and has to be merged, please feel free to merge it first and add the suggested update in another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 223 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6280#-KmC9HNS_4c6wFHY1orh:-KmCFPal5h2MkHFSJEBg:b-n18gtu) ([raw file](https://github.com/robotlocomotion/drake/blob/86d24b6a3d11a158e6af10b14be29de35a94bafc/tools/install.bzl#L223)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I understand we're fine since this function `_install_actions` is only called from `_install_cc_actions` which does the right thing. But I think for the future reference, it's good to document it (or refactor to eliminate the constraint).

If this PR is urgent and has to be merged, please feel free to merge it first and add the suggested update in another PR.
</blockquote></details>

Quite urgent, so I will follow up later today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6280)*

**Pull request merged**
