### PR TITLE
Use find_package instead of pkg-config to find dreal

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3768)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by soonho-tri** [comment]
@jamiesnape, could you update dReal Hash in this PR?

**Comment by jamiesnape** [comment]
Done, thanks.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@soonho-tri How problematic would be to install dreal and dependencies into `${prefix}/lib` instead of `${prefix}/lib/dreal`?

**Comment by soonho-tri** [comment]
@jamiesnape, I'll do that. (or at least provide an option for `PREFIX` so that things go to `lib/<PREFIX>/` if `PREFIX` is not null.

**Comment by jamiesnape** [comment]
Thanks.

**Comment by jamiesnape** [comment]
I will revisit this after dreal/dreal3#311 is resolved.

**Pull request closed without merging**
