### PR TITLE
[GcsTrajOpt] Support symbolic eval of nonconvex derivative constraints

### PR DESCRIPTION
**Pull request by RussTedrake**
It turns out this was helpful for debugging, even if the primary workflow doesn't use it.

+@wrangelvid for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)

### CODE REVIEW

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)* status: 2 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-NzT5l160IIAv5i-KPUu:-NzT5l160IIAv5i-KPUv:bcj92h6) ([raw file](https://github.com/RobotLocomotion/drake/blob/95aa836765dc24bdcd0e13afb1b49513f1c57e04/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2241)):*
> ```cpp
>   const int kOrder = 4;
> 
>   GcsTrajectoryOptimization trajopt(kDimension);
> ```

nit: It seems like you switched from calling `gcs.` for GcsTrajOpt to `trajopt.` I like trajopt, but for consistency sake would prefer either sticking with `gcs.` or changing the every occurrence of gcs to trajopt.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2253 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-NzT6TiFEMosNCmQvhFe:-NzT6TiGC07HE8E36roA:bqptybp) ([raw file](https://github.com/RobotLocomotion/drake/blob/95aa836765dc24bdcd0e13afb1b49513f1c57e04/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2253)):*
> ```cpp
>           {GraphOfConvexSets::Transcription::kRestriction});
>   ASSERT_EQ(constraints.size(),
>             kDimension + 1); /* C0 and C1 continuity constraints. */
> ```

I am a bit confused why this is kDimension + 1. C0 and C1 continuity should be added to both dimensions separately, so shouldn't it be 2*kDimension?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)* status: 2 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-NzT5l160IIAv5i-KPUu:-NzoQviQDplPLNjFaGYH:b-axlntx) ([raw file](https://github.com/RobotLocomotion/drake/blob/95aa836765dc24bdcd0e13afb1b49513f1c57e04/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2241)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

nit: It seems like you switched from calling `gcs.` for GcsTrajOpt to `trajopt.` I like trajopt, but for consistency sake would prefer either sticking with `gcs.` or changing the every occurrence of gcs to trajopt.
</blockquote></details>

The reason I did it here is because I needed both trajopt and gcs. (that's why i've been calling it trajopt in most of my examples).  I don't think we necessarily need to change the existing tests here.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2253 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-NzT6TiFEMosNCmQvhFe:-NzoRiYc-b2aTLXwbIoi:b-k0els6) ([raw file](https://github.com/RobotLocomotion/drake/blob/95aa836765dc24bdcd0e13afb1b49513f1c57e04/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2253)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I am a bit confused why this is kDimension + 1. C0 and C1 continuity should be added to both dimensions separately, so shouldn't it be 2*kDimension?
</blockquote></details>

Done.  I've made a more verbose comment.

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-:-O-WXEhC2Ml2giR410DA:b-ruv0ff)* status: 2 unresolved discussions, LGTM missing from assignees wrangelvid,jwnimmer-tri(platform)

**Review by RussTedrake — COMMENTED** [review]
@wrangelvid ping to finalize your review, please. (on this and the other PRs).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-:-O-WXJ23ED32agWIXcdC:b-mk6abb)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),wrangelvid

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)* status: LGTM missing from assignees jwnimmer-tri(platform),wrangelvid

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 2253 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-NzT6TiFEMosNCmQvhFe:-O-X2Uai3chZLCB2dywx:b-83sjo4) ([raw file](https://github.com/RobotLocomotion/drake/blob/95aa836765dc24bdcd0e13afb1b49513f1c57e04/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L2253)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I've made a more verbose comment.
</blockquote></details>

Nice.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)* status: LGTM missing from assignee wrangelvid

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1502 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21505#-O-bzK9l1ZACVZaBxJEv:-O-jP2g06c8JwwQOY6qH:b4pld7g) ([raw file](https://github.com/RobotLocomotion/drake/blob/40fa1637405fe9dbc969552f73e22ed448217d7a/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1502)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing unit tests.  (If I delete either or both of the two new stanzas of code, no unit tests fail.)
</blockquote></details>

Done.  (This is only needed to support the now properly declare @pre condition in the docstring in all cases.  When there were regions/edges, the methods below threw the error... but in the case where there were no regions yet, then we need to test these explicitly here)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21505)* status: LGTM missing from assignee wrangelvid

**Pull request merged**
