### PR TITLE
[doc] Add release notes v1.0.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16601#-MwYhQIq34Xta3VUPg7_:-MwYhQIr7xkf8ZiDi0f0:bup1ukx) (no related file):*
Working

Restore some of the #16644 verbiage as part of this PR.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16601#-MwYhQIq34Xta3VUPg7_:-MwYkE3F3EsH8pUCGK0m:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Restore some of the #16644 verbiage as part of this PR.
</blockquote></details>

Done.

---

**Comment by jwnimmer-tri** [comment]
___
*[doc/_release-notes/v1.0.0.md, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx1vApE3LUs_oqKdSTe:-Mx1vApE3LUs_oqKdSTf:bnvzg9k) ([raw file](https://github.com/robotlocomotion/drake/blob/2a10b49e4e1ac182baa55fa39d2e7c34cb7085fa/doc/_release-notes/v1.0.0.md#L8)):*
> ```Markdown
> # Announcements
> 
> * TBD Hydroelastic!
> ```

@sherm1 would you like to push some hydro announcement text here?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @sherm1)

___
*[doc/_release-notes/v1.0.0.md, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx1vApE3LUs_oqKdSTe:-Mx1zV6A2bxcEUMRKPRs:bebrt1w) ([raw file](https://github.com/robotlocomotion/drake/blob/2a10b49e4e1ac182baa55fa39d2e7c34cb7085fa/doc/_release-notes/v1.0.0.md#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 would you like to push some hydro announcement text here?
</blockquote></details>

Will do

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, and @sherm1)

___
*[doc/_release-notes/v1.0.0.md, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx1vApE3LUs_oqKdSTe:-Mx24sbL8s71Jf8pjkHb:b-h0ybz4) ([raw file](https://github.com/robotlocomotion/drake/blob/2a10b49e4e1ac182baa55fa39d2e7c34cb7085fa/doc/_release-notes/v1.0.0.md#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done. I tried unsuccessfully to push this to your branch but kept getting "permission denied". Should that have worked? In any case here's what I was trying to push:
```
* Hydroelastic Contact model is now released!
  * Provides a rich, patch-based contact surface with pressure distribution
    between contacting objects rather than treating contact as though it
    occurs at a point.
  * Formerly an experimental feature, now fully supported.
  * Rigid-compliant and compliant-compliant contact both supported.
    (Rigid object can be any mesh; compliant currently limited to primitive
    shapes.)
  * See [User Guide](https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html)
  * See [Elandt, et al.](https://arxiv.org/abs/1904.11433)
    and [Masterjohn, et al.](https://arxiv.org/abs/2110.04157) for theory.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, and @sherm1)

___
*[doc/_release-notes/v1.0.0.md, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx1vApE3LUs_oqKdSTe:-Mx268kSCiFHCBSdzVNz:b-pe1ikm) ([raw file](https://github.com/robotlocomotion/drake/blob/2a10b49e4e1ac182baa55fa39d2e7c34cb7085fa/doc/_release-notes/v1.0.0.md#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. I tried unsuccessfully to push this to your branch but kept getting "permission denied". Should that have worked? In any case here's what I was trying to push:
```
* Hydroelastic Contact model is now released!
  * Provides a rich, patch-based contact surface with pressure distribution
    between contacting objects rather than treating contact as though it
    occurs at a point.
  * Formerly an experimental feature, now fully supported.
  * Rigid-compliant and compliant-compliant contact both supported.
    (Rigid object can be any mesh; compliant currently limited to primitive
    shapes.)
  * See [User Guide](https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html)
  * See [Elandt, et al.](https://arxiv.org/abs/1904.11433)
    and [Masterjohn, et al.](https://arxiv.org/abs/2110.04157) for theory.
```
</blockquote></details>

Oops, I had "allow edits" unticked.  It's checked now, so you should be able to push, but I'm also happy to paste this in myself tomorrow.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @sherm1)

___
*[doc/_release-notes/v1.0.0.md, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx1vApE3LUs_oqKdSTe:-Mx4wohZ8bxI7cGLJpGi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a10b49e4e1ac182baa55fa39d2e7c34cb7085fa/doc/_release-notes/v1.0.0.md#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I had "allow edits" unticked.  It's checked now, so you should be able to push, but I'm also happy to paste this in myself tomorrow.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v1.0.0.md, line 98 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx5YWTU97usaMesJLxl:-Mx5YWTU97usaMesJLxm:bespryc) ([raw file](https://github.com/robotlocomotion/drake/blob/5a16e179f65abe3ecef758be984f79f020068edc/doc/_release-notes/v1.0.0.md#L98)):*
> ```Markdown
> 
> * Add pydrake.common.configure_logging() to set up a nice formatter style ([#16577][_#16577])
> * Make some subclasses of ConvexSet picklable ([#16628][_#16628])
> ```

BTW, it took me a while, due to my limited Python, to understand that this is about serialization in Python (pickling in Python terminology).
Previously I mistakenly thought `picklable` is a typo of `pickable`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[doc/_release-notes/v1.0.0.md, line 98 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx5YWTU97usaMesJLxl:-Mx7604l1fr0BNDrpXRI:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/5a16e179f65abe3ecef758be984f79f020068edc/doc/_release-notes/v1.0.0.md#L98)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, it took me a while, due to my limited Python, to understand that this is about serialization in Python (pickling in Python terminology).
Previously I mistakenly thought `picklable` is a typo of `pickable`.
</blockquote></details>

Done, thanks.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri to begin platform review, please (tomorrow).  Note that the YYYYMMDD and similar content isn't finished yet, until we are finally ready to release.  I think there's enough here to begin the proofreading, though.

**Review by xuchenhan-tri — COMMENTED** [review]
BTW, I think Sammy is on deck tomorrow. Happy to review the monumental release note though.

Looking good so far.

> Reviewed 2 of 5 files at r2, 2 of 3 files at r6, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601#-:-Mx79F1WDz81t1SSfndG:bmgjtve)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-Mx7A7st0RZFYTjoIuxv:bkvdd46) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
> ```Markdown
>   * Formerly an experimental feature, now fully supported.
>   * Rigid-compliant and compliant-compliant contact both supported.
>     (Rigid object can be any mesh; compliant currently limited to primitive
> ```

nit, "any mesh" seems to imply that only meshes (not primitives) are supported.



_Suggestion:_
```Markdown
Rigid object can be any shape; compliant currently limited to primitive
```
___
*[doc/_release-notes/v1.0.0.md, line 50 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7E2EE21o1FyzZazyo:-Mx7E2EE21o1FyzZazyp:bt2ulgl) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L50)):*
> ```Markdown
> * Enable linear costs in GraphOfConvexSets ([#16680][_#16680])
> * Add Intersection convex set ([#16629][_#16629])
> * Add PerspectiveQuadraticCost and include in GraphOfConvexSets cost options ([#16679][_#16679])
> ```

nit not sure about the proper grammar here



_Suggestion:_
```Markdown
Add PerspectiveQuadraticCost and include it in GraphOfConvexSets cost options 
```
___
*[doc/_release-notes/v1.0.0.md, line 70 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7FCU33JtyeaJX79Xl:-Mx7FCU33JtyeaJX79Xm:bt3b3dp) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L70)):*
> ```Markdown
> * Add URL and hostname customization to Meshcat ([#16638][_#16638], [#16654][_#16654])
> * Add MultibodyPlant getter to the Parser ([#16655][_#16655])
> * PositionConstraint can update lower and upper bounds ([#16631][_#16631])
> ```

BTW, Not sure if this message follows convention. This seems to be "present tense"? 



_Code quote (from doc/_pages/release_playbook.md):_
```Markdown
* We have four common grammatical forms for our commit messages:
  * Past tense ("Added new method foo") is acceptable
  * Noun phrase ("Ability to foo the bar") is acceptable
  * Imperative ("Add new method foo", i.e. PEP-8 style) is acceptable
  * Present tense ("Adds new method foo", i.e. Google styleguide style) is
    discouraged
```
___
*[doc/_release-notes/v1.0.0.md, line 83 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7BhAd33DpJSTxTXAp:-Mx7BhAd33DpJSTxTXAq:bj63yak) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L83)):*
> ```Markdown
> * Install tutorials in binary releases ([#16644][_#16644])
> * Withdraw tutorials from Colab ([#16568][_#16568])
> * Add hydroelastic example of compliant ball on a rigid plate mesh ([#15804][_#15804])
> ```

reminder: the spatula example goes here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-Mx7RLuHBdJzOj7_qDw6:b-c3vx3w) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, "any mesh" seems to imply that only meshes (not primitives) are supported.
</blockquote></details>

I think it's worth emphasizing that a rigid object can be a shape or any mesh. The mesh doesn't need to be air tight, or even closed. So, "just" saying shape doesn't really capture that amount of freedom available.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-Mx7UrnB6I3nnQwBNJQa:b-yz2bbr) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think it's worth emphasizing that a rigid object can be a shape or any mesh. The mesh doesn't need to be air tight, or even closed. So, "just" saying shape doesn't really capture that amount of freedom available. 
</blockquote></details>

I like the idea to include non-convex non-closed meshes like surface meshes of terrains. Indeed we had users with walking robots on terrains see Cassie walking on a non-convex non-closed surface in Slack [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1644438117513599?thread_ts=1644437000.738829&cid=C2WBPQDB7).



_Code snippet:_
```Markdown
(Rigid object can be any shape including a non-convex non-closed surface mesh; compliant ...
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-MxA26WU1B_hJjlTFMFP:bne0oho) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I like the idea to include non-convex non-closed meshes like surface meshes of terrains. Indeed we had users with walking robots on terrains see Cassie walking on a non-convex non-closed surface in Slack [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1644438117513599?thread_ts=1644437000.738829&cid=C2WBPQDB7).
</blockquote></details>

This text was from Sherm originally, so I'll defer on any fixes on my own.  Once Sherm and Damrong and etc. agree on wording, you can either push to my branch, or use the edit pencil [here](https://github.com/jwnimmer-tri/drake/blob/release_notes-v1.0.0/doc/_release-notes/v1.0.0.md) (which also pushes to my branch), or paste the text here and I'll push it.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-MxAJh436hedwI981nU6:bnr3hvh) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This text was from Sherm originally, so I'll defer on any fixes on my own.  Once Sherm and Damrong and etc. agree on wording, you can either push to my branch, or use the edit pencil [here](https://github.com/jwnimmer-tri/drake/blob/release_notes-v1.0.0/doc/_release-notes/v1.0.0.md) (which also pushes to my branch), or paste the text here and I'll push it.
</blockquote></details>

Done. I used the edit pencil to put in the improved text, but it took me three tries!

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7A7st0RZFYTjoIuxu:-MxAMkuwBpUkrxqKi-OM:b-mqk6c9) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. I used the edit pencil to put in the improved text, but it took me three tries!
</blockquote></details>

It looks great! Thanks. Satisfied.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 83 at r10](https://reviewable.io/reviews/robotlocomotion/drake/16601#-Mx7BhAd33DpJSTxTXAp:-MxAmICc2d9PD2-0u3oi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cda7366db1966bee93288b9198409a1dc42112a1/doc/_release-notes/v1.0.0.md#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

reminder: the spatula example goes here.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 31 at r15](https://reviewable.io/reviews/robotlocomotion/drake/16601#-MxApm4g32aZ72gXob6V:-MxApm4h8ffXfcixF2Nn:b-gzoc7w) ([raw file](https://github.com/robotlocomotion/drake/blob/5ed33a320a8efd7dde9f14b905dc7327ac3a493b/doc/_release-notes/v1.0.0.md#L31)):*
> ```Markdown
>     time (in order to switch to Python 3.8 or Python 3.9).
>   * macOS users already use Python 3.9, so will not be affected.
> * Reinder: The use of ``drake-visualizer`` on macOS is deprecated and will be
> ```

nit: typo. `Reinder` => `Reminder`

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601#-:-MxAqZPaC5kzl-WQcis-:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @jwnimmer-tri, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[doc/_release-notes/v1.0.0.md, line 31 at r15](https://reviewable.io/reviews/robotlocomotion/drake/16601#-MxApm4g32aZ72gXob6V:-MxAqtUn6mcHfNlIorzp:b-nody0b) ([raw file](https://github.com/robotlocomotion/drake/blob/5ed33a320a8efd7dde9f14b905dc7327ac3a493b/doc/_release-notes/v1.0.0.md#L31)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit: typo. `Reinder` => `Reminder`
</blockquote></details>

:droplet::deer:

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: pending YYYYMMDD stuff.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601#-:-MxCylZm4jJUjbtoqDHw:b5u480y)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16601#-:-MxFhrTU6ssN2E1mktnp:b-b9fcpn)* status: labeled "do not merge" (waiting on @DamrongGuoy and @xuchenhan-tri)

**Pull request merged**
