### PR TITLE
Updates to unrecognized sdf elements EnforcementPolicy

### LINKED ISSUE #16362: sdformat: Parsing errors provide less information than warnings?
When exercising #16347 on Anzu, it changes SDFormat warnings to errors.

However, the errors are much less information than the warnings, and thus harder to trace out (e.g. requires `--spdlog_level=trace` or something else super noisy).

As example, warnings in Anzu provides very useful context:
```
Warning [Utils.cc:129] [/sdf/model[@name="actuated_planar_fixture"]/joint[@name="y_joint"]/limit:.../actuated_planar_fixture.sdf:L64]: XML Element[limit], child of element[joint], not defined in SDF. Copying[limit] as children of [joint].
```

But the same info as an error has much less useful information:
```
From AddModelFromSdfFile():
Error: XML Element[limit], child of element[joint], not defined in SDF. Copying[limit] as children of [joint].
```

Ideally, we have the same information as the warning.

Marking as high priority b/c it can make the transition from warnings to errors painful.

FYI @sherm1 @jwnimmer-tri for user story; not sure how this should influence release

### PR DESCRIPTION
**Pull request by marcoag**
Related to the last point in #15018.
Resolves #16362

The target date for setting a warning to error has been shifted back (2022-02-01).
This includes more information in SDFormat error messages (on par with the information shown
in warnings).
Some of these fixes involved removing unparsed elements. No function
This also fixes models that were issuing warnings, at least as far as they're exercised in unittests.
This involved fixing elements that are unparsed, so their removal should have no functional effect.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

\CC @rpoyner-tri FYI per #16229

**Comment by jwnimmer-tri** [comment]
Jenkins shows some errors -- seems like several other XML files also need to be cleaned up.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for feature review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt5wXTn0k9wBdCpQ5eE:b95uae5)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by marcoag — COMMENTED** [review]
Missed some unrecognized elements in the examples, just removed them in https://github.com/RobotLocomotion/drake/pull/16347/commits/9fd8033f9d5d38988e65f6cf903d99ab09935a30. Jenkins should be fine now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt8JbhFA1RVwTNs7c3w:b-6uuib2)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: some comment cleanup

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt8z8dB40ssKTxxCs6-:bc5lfvq)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @marcoag)

___
*[examples/multibody/four_bar/four_bar.sdf, line 239 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8yZ6MDCsrCo7B7Hk7:-Mt8yZ6N5sfhHL3NCCmn:b9538qf) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L239)):*
> ```
>           tan⁻¹(√15) ≈ 1.318116071652818 ≈ 75.52°.
>           See the README for more details.
>         -->
> ```

This comment belongs with the removed element, and should go as well.
___
*[examples/multibody/four_bar/four_bar.sdf, line 258 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ydMG3Yse7lqCXMkc:-Mt8ydMG3Yse7lqCXMkd:bplbly0) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L258)):*
> ```
>           π − tan⁻¹(√15) ≈ 1.8234765819369751 ≈ 104.48°.
>           See the README for more details.
>         -->
> ```

same as above -- this comment should go.
___
*[examples/multibody/four_bar/four_bar.sdf, line 277 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8yj6608X9YB6IawYP:-Mt8yj6608X9YB6IawYQ:bplbly0) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L277)):*
> ```
>           π − tan⁻¹(√15) ≈ 1.8234765819369751 ≈ 104.48°.
>           See the README for more details.
>         -->
> ```

same as above -- this comment should go.
___
*[multibody/plant/test/block_on_halfspace.sdf, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ywpyE54rvhSKOlRe:-Mt8ywpyE54rvhSKOlRf:b4unipo) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/plant/test/block_on_halfspace.sdf#L41)):*
> ```
>                world frame is fixed and that the geometry aligns with that of
>                the box.
>           -->
> ```

nit We should figure out if this comment still means anything and maybe delete it.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @marcoag)

___
*[multibody/plant/test/block_on_halfspace.sdf, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ywpyE54rvhSKOlRe:-Mt90fk_CEgCDFrm8cPO:b-kozg5g) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/plant/test/block_on_halfspace.sdf#L41)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit We should figure out if this comment still means anything and maybe delete it.
</blockquote></details>

Looked at this a bit more. I don't think the comment is useful any more (the test passes without the pose element), but would appreciate a look from another set of eyes: maybe @joemasterjohn or @sherm1 .

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn and @marcoag)

___
*[multibody/plant/test/block_on_halfspace.sdf, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ywpyE54rvhSKOlRe:-Mt97ONeD7lip5A5_tib:b-e239r8) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/plant/test/block_on_halfspace.sdf#L41)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Looked at this a bit more. I don't think the comment is useful any more (the test passes without the pose element), but would appreciate a look from another set of eyes: maybe @joemasterjohn or @sherm1 .
</blockquote></details>

Geez -- I don't know how to interpret that comment. I'd say if the unit test is passing then we should go ahead and remove it. If trouble ensues downstream, we can address it then.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: removal of deprecated)  -- not sure if this is right, but hopefully the release manager can figure something out.

+@sherm1 for off-schedule platform review, since I featured it on my on-call day and you've already had a look.
+@xuchenhan-tri for shadow platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9BgYS0iS5Y912Ec-i:b-4mq1mn)* status: 4 unresolved discussions, LGTM missing from assignees sherm1(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn, @marcoag, and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending minor changes.

BTW I'm surprised to see pose, material, and initial_position simply removed. Does modern sdf not have equivalent specifications? Or were those just being ignored altogether before?

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9Jh-Z0xsjwCDHXkUC:b-n3stk3)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn, @marcoag, and @xuchenhan-tri)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9IcbiDj0xh3tXHnSG:-Mt9IcbiDj0xh3tXHnSH:b-ci2zhh) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/parsing/test/detail_sdf_parser_test.cc#L1160)):*
> ```cpp
> </model>
> )"""),
>       std::runtime_error,
> ```

nit: per Drake [styleguide](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) should only check that an `std::exception` is thrown, not a particular subclass.
(Also below)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with the same question as above: were poses/material/etc being ignored before?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9LNpY9a-yzjMI4pBE:b8uabyy)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn and @marcoag)

**Review by rpoyner-tri — COMMENTED** [review]
I don't know the full history; perhaps @ericcousineau-tri could provide some insight.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9NAIt9gmezHV9p37d:b-h7av90)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn and @marcoag)

**Review by EricCousineau-TRI — COMMENTED** [review]
Before, SDFormat parser simply ignored unknown elements. I'm not sure why those elements were there initially, but I'd chalk it up to either simple mistakes (most likely) and/or old SDFormat parser perhaps using them in a non-standard way (less likely). Anything concrete would require `git blame`; not sure if it's worth the effort beyond the comment below about plane parsing for unittest.

As to why they were ignored, it was b/c SDFormat parser didn't warn about unparsed elements before (or if it did, not in a way that was visible to us in Drake). In recent work, we've improved the parser, hence why this coming about now.

Does that explain?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9Qbc26x65jyl6P2z5:b-whbgbc)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9QYOM2OfV_LeyhmzY:-Mt9QYOM2OfV_LeyhmzZ:baebx5t) (no related file):*
Working: I should fix Anzu models as well before this merges.

---

**Review by sherm1 — COMMENTED** [review]
Yep! Thanks, Eric.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-Mt9VOIa3yrGZj-6JmQ0:brj2muk)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, and @marcoag)

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, @marcoag, and @sherm1)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9IcbiDj0xh3tXHnSG:-Mt9WxTA57JgZjxOthlP:b-q12qlc) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/parsing/test/detail_sdf_parser_test.cc#L1160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per Drake [styleguide](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) should only check that an `std::exception` is thrown, not a particular subclass.
(Also below)
</blockquote></details>

This rises a good point. A lot of the exception checks on this test file are using `std::runtime_error`. Since this seems to be a bit out of the scope of this PR, shall I correct in a new one?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, and @marcoag)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9IcbiDj0xh3tXHnSG:-Mt9_cPVC7F4QsGniaCq:b9rzbol) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/parsing/test/detail_sdf_parser_test.cc#L1160)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

This rises a good point. A lot of the exception checks on this test file are using `std::runtime_error`. Since this seems to be a bit out of the scope of this PR, shall I correct in a new one?
</blockquote></details>

At a minimum, just correct the ones you added (change std::runtime_error -> std::exception). If you want to fix the other ones in the same file in this PR that would be great, and justified for consistency. If you want to leave those for a future PR that's OK too.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9QYOM2OfV_LeyhmzY:-Mt9gJfo5PsnnW1o-WY4:bjwubzj) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I should fix Anzu models as well before this merges.
</blockquote></details>

Just to clarify: so that means develop and review an Anzu patch, and then merge the two close together? Or can you just land the Anzu patch, and then this one?

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @marcoag)

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sherm1)

___
*[examples/multibody/four_bar/four_bar.sdf, line 239 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8yZ6MDCsrCo7B7Hk7:-Mt9kVmX5mVOPqBSEKoN:b-b7i29e) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L239)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This comment belongs with the removed element, and should go as well.
</blockquote></details>

Removed in https://github.com/RobotLocomotion/drake/pull/16347/commits/97bd57a9f642f1b05e7b5bdd4bdb72a1e03c3ae7.
___
*[examples/multibody/four_bar/four_bar.sdf, line 258 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ydMG3Yse7lqCXMkc:-Mt9kfx7A0cFLRCHyzod:be0dlph) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L258)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

same as above -- this comment should go.
</blockquote></details>

Removed in 97bd57a.
___
*[examples/multibody/four_bar/four_bar.sdf, line 277 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8yj6608X9YB6IawYP:-Mt9khJ5EwAbK2r3-iJZ:b-fl54e3) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/examples/multibody/four_bar/four_bar.sdf#L277)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

same as above -- this comment should go.
</blockquote></details>

Removed in 97bd57a.
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9IcbiDj0xh3tXHnSG:-Mt9kBSN4ZKOgEMmkavx:bxun2j2) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/parsing/test/detail_sdf_parser_test.cc#L1160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

At a minimum, just correct the ones you added (change std::runtime_error -> std::exception). If you want to fix the other ones in the same file in this PR that would be great, and justified for consistency. If you want to leave those for a future PR that's OK too.
</blockquote></details>

Since you seem OK with it I went ahead and fixed the rest of the exceptions of `deail_sdf_parser_test.cc` in this PR for consistency.
___
*[multibody/plant/test/block_on_halfspace.sdf, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt8ywpyE54rvhSKOlRe:-Mt9kpJnDERLpbqCxEI7:b5vkidk) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/plant/test/block_on_halfspace.sdf#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Geez -- I don't know how to interpret that comment. I'd say if the unit test is passing then we should go ahead and remove it. If trouble ensues downstream, we can address it then.
</blockquote></details>

Since the comment goes along with the pose tag I went ahead and removed it. If you wanna have a look at some context of this you can check this PR where it was modified:  https://github.com/RobotLocomotion/drake/pull/12172.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1160 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9IcbiDj0xh3tXHnSG:-Mt9y7peBImV1zcCvjFd:b-qcpy25) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd8033f9d5d38988e65f6cf903d99ab09935a30/multibody/parsing/test/detail_sdf_parser_test.cc#L1160)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Since you seem OK with it I went ahead and fixed the rest of the exceptions of `deail_sdf_parser_test.cc` in this PR for consistency.
</blockquote></details>

Thanks, @marcoag !

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9QYOM2OfV_LeyhmzY:-MtAdFnp8uWsIJcnokRd:b-ptfx41) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Just to clarify: so that means develop and review an Anzu patch, and then merge the two close together? Or can you just land the Anzu patch, and then this one?
</blockquote></details>

Either one. To unblock Drake, I think "two close together" will be most expedient.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-MtAk6cv9ONagFZqIsjr:-MtAk6cv9ONagFZqIsjs:b-o28lsv) (no related file):*
Blocking: See https://github.com/RobotLocomotion/drake/issues/16362
(blocking b/c it seems like solution is quickly feasible)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-MtAk6cv9ONagFZqIsjr:-MtApCbs1jjXGmKRXPW0:btze89q) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Blocking: See https://github.com/RobotLocomotion/drake/issues/16362
(blocking b/c it seems like solution is quickly feasible)
</blockquote></details>

See: https://github.com/marcoag/drake/pull/1

---

**Comment by jwnimmer-tri** [comment]
Even without #16362, I'd been pondering asking to hold this PR for now anyway.

I'm not sure the "newly deprecated" release text for #15672 and #15680 in v0.34.0 was sufficiently dire to warn users about this hazard, especially given that Anzu had so many problems with this change.

With @rpoyner-tri, I have been discussing allowing `multibody::Parser` to offer the the user an option to configure warning strictness.  If the users can demote errors to warnings, this PR might be a lot easier to swallow.  We might have that feature done within a few weeks.  I don't think this date of 2022-01-01 was particularly time-critical, so I think it makes sense to give the smoother transition plan a try, and see if we can finish it quickly enough.

**Comment by EricCousineau-TRI** [comment]
Makes sense!

From what I've seen / fixed thus far in Anzu, I'd love to have this enabled by default, and never let people write (easily detected) malformed SDFormat files again.

Also, if there isn't a global option to relax this (which has it's own issues), there may not be steep value gain for users who may construct `Parser()` multiple times throughout there codebase.

That all being said, I'd be fine w/ this missing the release mark.

And if you'd like to hold off on the merge to master pending more configurable `Parser()`, I'd be fine, but I'd be eager to patch Drake in Anzu with the one-liner fix if this gets held back. (and never have to worry about this again, at least on my part)

If we do hold this back, I think we can still carve out most improvements Marco has made (incl. resolution to #16362)

**Review by marcoag — COMMENTED** [review]
Given the hold on this PR, should I move the resolution #16362 and other improvements into separate PRs?  

Shall we open an issue for a configurable `Parser()` that allows the user to set different levels of `EnforcementPolicy`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-MtDC7c_2aaAQ_Awqqqm:b-tbpo8q)* status: 2 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @marcoag, @rpoyner-tri, and @sherm1)

**Comment by jwnimmer-tri** [comment]
> Shall we ... ?

I wanted to sleep on it before giving a recommendation.

Here's my current suggestion:

(1) Update this PR to put back this stanza into the implementation, instead of doing `ERR`:

```c++
  // TODO(#15018): Change unrecognized elements policy to become an error on
  // or after 2022-02-01.
  parser_config.SetUnrecognizedElementsPolicy(sdf::EnforcementPolicy::WARN);
```

Note the new date of 2022-02-01, vs 2022-01-01 that's currently on `master`.

That also means that we need to partially undo the changes to the test expectations for exception vs console warning.

(2) Keep all of the other changes intact (removing the unrecognized XML in sample files; improving GSG-related spellings in the adjacent tests, etc.)

(3) Finish (re-)review given those changes, and then merge this PR.

(4) Leave #15018 open and re-assign to @rpoyner-tri.  He and I will explore finishing it (switching to `ERR` as the default), but alongside a Parser configuration flag to allow for a more graceful transition, and in concert with other parsing strictness changes -- that go beyond just unrecognized elements in the sdformat XML namespace.

> From what I've seen / fixed thus far in Anzu, I'd love to have this enabled by default, and never let people write (easily detected) malformed SDFormat files again.

I share your desire for that default.  But since this interface is the primary entry point into Drake (in my opinion), I think it's important to be a bit more generous with the transition plan, as long as we can do so quickly.

> Also, if there isn't a global option to relax this (which has it's own issues), there may not be steep value gain for users who may construct Parser() multiple times throughout there codebase.

With no flag at all, users are completely stuck, and will need to wade through _all_ of their models (some of which might be coming from dependencies, instead of being vendored) to make repairs.  Even if they need to patch dozens of calls into the Parser constructor in their code, that is still a relatively quick job for some code search.  Certainly less time-consuming that trying to maintain a fork of all of their model dependencies' repositories.

> And if you'd like to hold off on the merge to master pending more configurable Parser(), I'd be fine, ...

Ok.  I proposed a specific plan for this, above.  LMK.

> ... but I'd be eager to patch Drake in Anzu with the one-liner fix if this gets held back. (and never have to worry about this again, at least on my part)

Landing Anzu's XML fixes immediately is great.  It would be nice to have 'strict' mode enabled in Anzu right away, but we've lived without it for 2+ years, so waiting a couple more weeks until we have a Parser toggle doesn't seem too onerous.

> If we do hold this back, I think we can still carve out most improvements Marco has made (incl. resolution to #16362)

Rather than carve out while leaving this open, I think it's going to be logistically easier to just rework this PR to be the increment to be merged, and leave the ERR swap PR to Rico and I.

**Review by EricCousineau-TRI — COMMENTED** [review]
> (1) Update this PR to [...]
> (2) Keep all of the other changes intact [...]
> (3) Finish (re-)review given those changes [...]
> (4) Leave #15018 open [...]
> Ok. I proposed a specific plan for this, above. LMK.

All that sounds good to me! Added discussion item. @marcoag Would you be able to handle that?

> Landing Anzu's XML fixes immediately is great. [...]

Done (thanks @sammy-tri!)

> [...] so waiting a couple more weeks until we have a Parser toggle doesn't seem too onerous.

SGTM

> Rather than carve out while leaving this open [...]

SGTM

> Reviewed 1 of 2 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-MtDwJZFAYiyhuc354Yh:bqqb5vc)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-Mt9QYOM2OfV_LeyhmzY:-MtDw9jCE6fV2foXSbZG:bdqh6j6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Either one. To unblock Drake, I think "two close together" will be most expedient.
</blockquote></details>

Done. Merged relevant Anzu model changes.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16347#-MtAk6cv9ONagFZqIsjr:-MtDwCJv54z5q8P1UVz8:bmbyxv0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

See: https://github.com/marcoag/drake/pull/1
</blockquote></details>

Done. (Relevant changes merged)

---
___
*[multibody/parsing/detail_sdf_parser.cc, line 1266 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16347#-MtDwcv09zrzmOWk3dUb:-MtDwcv09zrzmOWk3dUc:bw8f407) ([raw file](https://github.com/robotlocomotion/drake/blob/3c3191a71e61d3f1f0a696430cdc297eb1dc4304/multibody/parsing/detail_sdf_parser.cc#L1266)):*
> ```cpp
>   parser_config.SetWarningsPolicy(sdf::EnforcementPolicy::ERR);
>   parser_config.SetDeprecatedElementsPolicy(sdf::EnforcementPolicy::WARN);
>   // TODO(#15018): Change unrecognized elements policy to become an error on
> ```

@marcoag Would you be able to incorporate Jeremy's suggested changes here?
(restore this chunk, relax test expectations, and change date to 2022-02-01?)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

**Comment by jwnimmer-tri** [comment]
I've set release notes tag to just "yes", with the idea of "exception have better error message details" as the notable item.

**Comment by EricCousineau-TRI** [comment]
@marcoag Can you change the title to more accurately reflect the PR?

**Review by marcoag — COMMENTED** [review]
Addressed suggestion steps 1 and 2 in https://github.com/RobotLocomotion/drake/pull/16347/commits/ee0ab7d257db217c0eefb62d18fd3640e6d581d6.

Updated the PR title, let me know if you think of a better one.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16347#-:-MtELuII8LNmato5ViVl:b-hwkx83)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

**Comment by EricCousineau-TRI** [comment]
Looks better! I've also updated PR overview to hopefully be digestible for release notes.

I will go ahead and merge.

**Pull request merged**
