### PR TITLE
[parsing] Use DiagnosticPolicy instead of log_once in SDFormat

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16784.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
One question is whether we think we need to implement warning message throttling in `parser.cc` as a prerequisite to this change (e.g., after 100 warnings occur, warn that we're going to stop printing any more).  My inclination was not to worry about it.

**Review by rpoyner-tri — COMMENTED** [review]
for throttling, meh? We can always come back around to that.

:lgtm: 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810#-:-MyJPdjB5SG3TAd7-tjn:b-bt5px7)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_geometry.cc, line 473 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyJP2KtE9zAOXj0cSXw:-MyJP2Ku4haIupxYdQnY:bp96dl4) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/detail_sdf_geometry.cc#L473)):*
> ```cpp
>         if (MaybeGetChildElement(*ode_element, "mu") ||
>             MaybeGetChildElement(*ode_element, "mu2")) {
>           diagnostic.Warning(fmt::format(
> ```

not a blocker for this PR, but I'm thinking of posting a PR that offers variadic-template overloads for Error() and Warning() various places.
- to make them closer equivalents to the text logging API
- to make including run-time-available context as easy as possible.
thoughts?
___
*[multibody/parsing/detail_urdf_geometry.cc, line 597 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyJOKt88JdUu2a3lM56:-MyJOKt88JdUu2a3lM57:b-ahr5lr) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/detail_urdf_geometry.cc#L597)):*
> ```cpp
> 
>     // TODO(jwnimmer-tri) ParseCollision should accept a policy as an argument
>     // and pass it along here, instead of making a temporary one.
> ```

agreed. that is coming.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_geometry.cc, line 473 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyJP2KtE9zAOXj0cSXw:-MyJS58c0seuH9rOMwxy:bimpcaf) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/detail_sdf_geometry.cc#L473)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

not a blocker for this PR, but I'm thinking of posting a PR that offers variadic-template overloads for Error() and Warning() various places.
- to make them closer equivalents to the text logging API
- to make including run-time-available context as easy as possible.
thoughts?
</blockquote></details>

Seems plausible.  So basically we can nix the `fmt::format()` here?

For myself, I don't mind this as-written.  I'm not losing a vertical line due to the`fmt::` mumble.  My only worries with a wrapper would be (1) do we lose access to fmt's compile-time format string checking, and (2) does it bloat our object code.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_geometry.cc, line 473 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyJP2KtE9zAOXj0cSXw:-MyJYLaL8zwg0hQA56m-:b-x5g906) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/detail_sdf_geometry.cc#L473)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Seems plausible.  So basically we can nix the `fmt::format()` here?

For myself, I don't mind this as-written.  I'm not losing a vertical line due to the`fmt::` mumble.  My only worries with a wrapper would be (1) do we lose access to fmt's compile-time format string checking, and (2) does it bloat our object code.
</blockquote></details>

Good points. I found this https://fmt.dev/latest/api.html#argument-lists -- not sure if our version supports it. I will look some more.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_geometry.cc, line 473 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyJP2KtE9zAOXj0cSXw:-MyJlpMSDUScV-UvD0yR:b8s5xbz) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/detail_sdf_geometry.cc#L473)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Good points. I found this https://fmt.dev/latest/api.html#argument-lists -- not sure if our version supports it. I will look some more.
</blockquote></details>

Right.  I'm not sure if we access to those features today, but I'd like to think if we're painting ourselves into a corner.  On the other hand, adding back `fmt::format()` to every call site would be pretty easy to do later, if we needed to.

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri platform :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810#-:-MyKLgIDBR3Q5fy7eGQ5:b-o7e8hz)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[multibody/parsing/test/detail_common_test.cc, line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyKKV0y4Q6BNwOuOUqW:-MyKKV0y4Q6BNwOuOUqX:b93866d) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/test/detail_common_test.cc#L93)):*
> ```cpp
>  public:
>   ParseProximityPropertiesTest() {
>     diagnostic_.SetActionForWarnings(&DiagnosticPolicy::ErrorDefaultAction);
> ```

BTW, is the purpose of this catching potentially missed warnings? A comment would help here.
___
*[multibody/parsing/test/detail_common_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyKITzL84-fEiTqOJXV:-MyKITzL84-fEiTqOJXW:boaejcc) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/test/detail_common_test.cc#L97)):*
> ```cpp
> 
>   // This shadows the namespace-scoped free function under test in order to
>   // curry the `diagnostic` argument.
> ```

BTW, now sure why "curry" the argument means.
___
*[multibody/parsing/test/detail_sdf_geometry_test.cc, line 1056 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyKJ6uX1NCTFgtQyaLx:-MyKJ6uX1NCTFgtQyaLy:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/test/detail_sdf_geometry_test.cc#L1056)):*
> ```cpp
> // Verify we can parse drake collision properties from a <collision> element.
> GTEST_TEST(SceneGraphParserDetail, MakeProximityPropertiesForCollision) {
>   // Curry a `diagnostic` arugment into the function under test.
> ```

nit



_Suggestion:_
```cpp
argument
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16810)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

___
*[multibody/parsing/test/detail_common_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16810#-MyKITzL84-fEiTqOJXV:-MyKNcUU9_HfmdcnvphV:bbvm9ci) ([raw file](https://github.com/robotlocomotion/drake/blob/05bbcb65bb85f521247209bd89268ecd4bdd291b/multibody/parsing/test/detail_common_test.cc#L97)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, now sure why "curry" the argument means.
</blockquote></details>

https://en.wikipedia.org/wiki/Currying, but probably "bind" is a more familiar term to readers here.

**Pull request merged**
