### PR TITLE
Made RigidBody::mass and RigidBody::contact_pts Private

### PR DESCRIPTION
**Pull request by liangfok**
Added accessors for this member variable.
Builds upon #2910.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2911)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-:-KOBGu4gN-K3dys7bzjt:-1862437413)*

**Comment by david-german-tri** [comment]
:lgtm: Thanks for chipping away at this stuff!  Consider squashing this PR into one commit before you merge.

---

Reviewed 1 of 33 files at r2, 8 of 27 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/parser_urdf.cc, line 101 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOBKsosoTMrlN_K0ESb:-KOBKsotzkolPriKk7GE:-909304070) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/parser_urdf.cc#L101)):*
> ```cpp
>   XMLElement* mass = node->FirstChildElement("mass");
>   if (mass) {
>     double body_mass = 0;
> ```

BTW, the initialization here is inconsistent with the SDF parser (though it really doesn't matter)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-:-KOBL8nt0nFvpsD1fMzc:1886415994)*

**Comment by amcastro-tri** [comment]
Two small comments. Otherwise :lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/RigidBody.h, line 249 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOC0wpwPsImf_jJosq2:-KOC0wpwPsImf_jJosq3:-2063715776) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/RigidBody.h#L249)):*
> ```objc
>    * RigidBody::set_contact_points().
>    */
>   const Eigen::Matrix3Xd& get_contact_points() const;
> ```

Change comment to something like:
"Returns the points on this rigid body to be considered for collision with the environment."

---

*[drake/systems/plants/RigidBody.h, line 252 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOC0cOglqWyl0LzQxIb:-KOC0cOglqWyl0LzQxIc:1294512744) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/RigidBody.h#L252)):*
> ```objc
> 
>   /**
>    * Saves the contact points between this rigid body and the environment.
> ```

Rephrase to: "Sets the points of contact on the rigid body to be considered for collision with the environment."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-:-KOC1Bj7YglzN9dLHq18:-1511430416)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 101 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOBKsosoTMrlN_K0ESb:-KOD9QYzHY-oaFUp04-b:-173188490) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/parser_urdf.cc#L101)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, the initialization here is inconsistent with the SDF parser (though it really doesn't matter)
</details>
Done. I modified the SDF parser to also initialize `mass` to be zero.

---

*[drake/systems/plants/RigidBody.h, line 249 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOC0wpwPsImf_jJosq2:-KOD9C3CtyDYEvpGm7m1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/RigidBody.h#L249)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Change comment to something like:
> "Returns the points on this rigid body to be considered for collision with the environment."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 252 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-KOC0cOglqWyl0LzQxIb:-KOD9DNbtnYK_QR79yDa:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d269702c6af62ed753af7eaca72410a108fb004b/drake/systems/plants/RigidBody.h#L252)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Rephrase to: "Sets the points of contact on the rigid body to be considered for collision with the environment."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2911#-:-KODFRcHpIuoZw93LRGm:272680688)*

**Pull request merged**
