### PR TITLE
Renaming VisualizedPlant to PlantAndVisualizerDiagram

### LINKED ISSUE #4813: Consider Renaming VisualizedPlant to be PlantAndVisualizerDiagram
This issue was inspired by @SeanCurtis-TRI's comment here: https://reviewable.io/reviews/robotlocomotion/drake/4766#-Kah0nNXSdBGVBzH92UR

Basically, the name "VisualizedPlant" implies that the object instantiation _is a_ plant whereas in actuality it _has a_ plant.

### PR DESCRIPTION
**Pull request by naveenoid**
Resolved #4813 

+@liangfok for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5381)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-KeFE7MVeSwNnBuZBUbA:-KeFE7MVeSwNnBuZBUbB:bhk70t3) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ff73ecd92377441ccac5f8c7463be1d406a527/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L29)):*
> ```objc
> class PlantAndVisualizerDiagram : public systems::Diagram<T> {
>  public:
>   /// Builds the VisualizedPlant.
> ```

BTW, this should be updated to match the new name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-:-KeFEJCFH6_2xFNGWbVb:bnfp4nl)*

**Comment by naveenoid** [comment]
+@ggould-tri for feature review please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-:-KeIIxMvhR1P-zOJhJV7:blzaqsn)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-KeFE7MVeSwNnBuZBUbA:-KeILjY-cLqyJRGTU2bf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ff73ecd92377441ccac5f8c7463be1d406a527/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this should be updated to match the new name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381)*

**Comment by naveenoid** [comment]
Sorry! 
+@ggould-tri for platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-:-KeJJ6IeszjAofbMaPtT:bp54ng2)*

**Comment by ggould-tri** [comment]
:lgtm:.  FYI This one would have been reasonable to single-reviewer.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5381#-:-KeJU324VQAwTiNhZihc:b-brhzz1)*

**Pull request merged**
