### PR TITLE
Use correct indices for joint/body velocities

### PR DESCRIPTION
**Pull request by joemasterjohn**
Joint locking was using an assumed velocity indexing for joints/bodies. This fixes it to use the actual assigned velocity indices.

cc: @rpoyner-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@amcastro-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MyOJVy946b1Cav5i0ux:b5xll3r)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
When did this assumption become false? If we didn't notice, then that suggests that (perhaps many) tests are missing. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MyP5sIA1gPQDY8_XyDJ:b-nq3kwp)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
I agree with @rpoyner-tri here, we should at least have a unit tests that triggers an error that then this patch fixes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MygdxJcDdLO74HOa9Di:bftk3gg)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Review by joemasterjohn — COMMENTED** [review]
OK, I've added the unit test and verified that it fails in master and passes with the these changes to `multibody_plant.cc`. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MyiPQ0s2enLvWS11PeI:b8nxd3o)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri, @joemasterjohn, and @rpoyner-tri)

___
*[multibody/plant/test/multibody_plant_test.cc, line 161 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym51po5QmX_YXqk_Sq:-Mysgp5TE5dY05BF8dSf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L161)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, naming is awkward. Why not just body1, body2, and body3?
</blockquote></details>

Done.
___
*[multibody/plant/test/multibody_plant_test.cc, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym6J8eEh_0tsBFqZnM:-MyxCmBZ5a2DZ4X-GB3f:b3db5dt) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L167)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

what about getting rid of `joint_w_1`? that way you can also test the branch in the code where there is a free body.
That is, you'd have a free body and a double pendulum.
</blockquote></details>

Done. `MultibodyPlantTopology::Finalize()` traverses and assigns velocity indices for the child trees of the world body in the order that their mobilizers were added to the model. But `MultibodyTree::Finalize()` builds all of the joint blueprints (and thus adds all joint mobilizers) first and then processes the remaining floating bodies, adding the freebody mobilizers, so no ordering of adding bodies could trigger the problem. So I had to add a free body with a joint attached in order to trigger the problem with the original joint locking indices.
___
*[multibody/plant/test/multibody_plant_test.cc, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym59nv4op-XNptVVGJ:-Mysh4fJBZsnQhJE9Smp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L169)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

naming here is awkward and border line GSG non compliant.
Since we know these are joints, I propose something like `world_body1`, `world_body2`, `body2_body3`.
</blockquote></details>

Done.
___
*[multibody/plant/test/multibody_plant_test.cc, line 247 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym6ANu6Cnn3kbF6zfl:-Mysh9-NDbTNxb2BjXvy:b-xy4bmv) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L247)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

TIL, wow! I had no idea you could do that!
</blockquote></details>

Yeah these gtest container matchers are great, just learned about them recently: https://github.com/google/googletest/blob/main/docs/reference/matchers.md
___
*[multibody/plant/test/multibody_plant_test.cc, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym6eb17pBRVVrnT79l:-MyxKS547c2OhPH9vGsM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L262)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

add test for locking a free body? say if we just lest body1 to be a free body.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @joemasterjohn)

**Review by amcastro-tri — COMMENTED** [review]
Thanks @joemasterjohn, :lgtm:. 
Could you move these tests into their own file?

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-Myxg5-945jzsgJZ3z4P:b-xvof2j)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by rcory — COMMENTED** [review]
Any chance we can prioritize merging this, please? It is about to become a blocker :(

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MzGN6w1EDx_5xabDT6m:b-d4kpfv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Yes, I'll try and make sure it is merged this afternoon. +@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MzGjjK80JDgdZ5og9uK:b-u5joqj)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri, @ggould-tri, and @rpoyner-tri)

___
*[multibody/plant/test/multibody_plant_test.cc, line 156 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16818#-Mym6lmr73XRFC8rA8ic:-MzGjfnGClDos8gPpPE2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f56cec161fec78319bb7e25b235de926d994a163/multibody/plant/test/multibody_plant_test.cc#L156)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I hate to keep adding more stuff to this file. There is no reason for this to live here.
Lets move it to a new file.  Somewhere like `multibody/plant/test/joint_locking_test.cc` seems appropriate.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MzGq_zyDtD8AMKXICW2:bnfp4nl)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @joemasterjohn)

___
*[multibody/plant/multibody_plant.cc, line 2367 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzGnMGwDsdGuWIP433q:-MzGnMGx3B65KISRnwv4:bvka6sl) ([raw file](https://github.com/robotlocomotion/drake/blob/154cac7854d1fa33a8b6255847dcfe3c133af231/multibody/plant/multibody_plant.cc#L2367)):*
> ```cpp
>   indices.resize(num_velocities());
> 
>   int velocity_cursor = 0;
> ```

minor:  Since this is no longer used as a cursor and is only ever used to assert that the right total number of velocities were accumulated, renaming it `velocity_counter` would be more appropriate.
___
*[multibody/plant/test/joint_locking_test.cc, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzGovnYCgSmBgPUlISB:-MzGovnYCgSmBgPUlISC:bnez4kt) ([raw file](https://github.com/robotlocomotion/drake/blob/154cac7854d1fa33a8b6255847dcfe3c133af231/multibody/plant/test/joint_locking_test.cc#L110)):*
> ```cpp
> 
>   // No joints/bodies are locked, all joint/body velocity indices should exist.
>   const std::vector<int>& unlocked_indices =
> ```

minor:  The names of these `...locked_indices` variables are confusing, since they imply that they are the indices of the locked or unlocked joints, rather than the unlocked joints of the test of that name (particularly since `EvalJointLockingIndices` returns the _unlocked_ indices, which is weird).
This might be clearer if the test cases were in separate stanzas so they didn't need extended names like this.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri, @ggould-tri, and @rpoyner-tri)

___
*[multibody/plant/multibody_plant.cc, line 2367 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzGnMGwDsdGuWIP433q:-MzGxQBg0wd9mlTfPFSd:bfdvlvf) ([raw file](https://github.com/robotlocomotion/drake/blob/154cac7854d1fa33a8b6255847dcfe3c133af231/multibody/plant/multibody_plant.cc#L2367)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Since this is no longer used as a cursor and is only ever used to assert that the right total number of velocities were accumulated, renaming it `velocity_counter` would be more appropriate.
</blockquote></details>

Done. I decided to remove the variable all together, since it isn't doing anything anymore.
___
*[multibody/plant/test/joint_locking_test.cc, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzGovnYCgSmBgPUlISB:-MzGyehc4n_Uk5ewqg4m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/154cac7854d1fa33a8b6255847dcfe3c133af231/multibody/plant/test/joint_locking_test.cc#L110)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The names of these `...locked_indices` variables are confusing, since they imply that they are the indices of the locked or unlocked joints, rather than the unlocked joints of the test of that name (particularly since `EvalJointLockingIndices` returns the _unlocked_ indices, which is weird).
This might be clearer if the test cases were in separate stanzas so they didn't need extended names like this.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
:rock: :on: :thumbsup: 

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818#-:-MzH02Q3B6bIsv8uRXQT:b-be8fl3)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

___
*[multibody/plant/test/joint_locking_test.cc, line 5 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzH0JjODhTztbiFLTrX:-MzH0JjODhTztbiFLTrY:beluuct) ([raw file](https://github.com/robotlocomotion/drake/blob/74d029b693efd4a037215441dd388153afa741c8/multibody/plant/test/joint_locking_test.cc#L5)):*
> ```cpp
> #include <vector>
> 
> #include <gmock/gmock.h>
> ```

nit, not used?

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

___
*[multibody/plant/test/joint_locking_test.cc, line 5 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzH0JjODhTztbiFLTrX:-MzH2aPB-YZ3feASmgUL:bomtkkp) ([raw file](https://github.com/robotlocomotion/drake/blob/74d029b693efd4a037215441dd388153afa741c8/multibody/plant/test/joint_locking_test.cc#L5)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, not used?
</blockquote></details>

That header is actually where `EXPECT_THAT` and `testing::UnorderedElementsAreArray()` come from. I'm not sure if there's a more specific header that could be used, but it is consistent with what all of our other tests `#include`.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16818)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri

___
*[multibody/plant/test/joint_locking_test.cc, line 5 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16818#-MzH0JjODhTztbiFLTrX:-MzHHBC43aUluIHgjWyu:b4ncmef) ([raw file](https://github.com/robotlocomotion/drake/blob/74d029b693efd4a037215441dd388153afa741c8/multibody/plant/test/joint_locking_test.cc#L5)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

That header is actually where `EXPECT_THAT` and `testing::UnorderedElementsAreArray()` come from. I'm not sure if there's a more specific header that could be used, but it is consistent with what all of our other tests `#include`.
</blockquote></details>

ah... thanks.

**Pull request merged**
