### PR TITLE
[setup] Add Xcode 16 specific build configuration

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes https://github.com/RobotLocomotion/drake/issues/22204.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

**@drake-jenkins-bot** mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.
</blockquote></details>

**@drake-jenkins-bot** mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCFIpZhC-FO8-JN0vrP:-OCGr0655q83TYvCd6Jc:b-irv1ps) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

**@drake-jenkins-bot** mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.
</blockquote></details>

-(status: do not merge) -(status: do not review) 
+(release notes: none) +@jwnimmer-tri for feature review, or both reviews if you like.
___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCGrC3R5OPc_Uxp407h:-OCGrC3R5OPc_Uxp407i:b-j79ygv) (no related file):*
This patch doesn't fix `[//examples/hardware\_sim:py/hardware\_sim\_py\_test](https://drake-cdash.csail.mit.edu/test/1638523679)` on the sequoia CI image; I suspect that image is missing a routing table entry for LCM.

**Review by rpoyner-tri — COMMENTED** [review]
Closes: #22204.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCGsguM8PdCMDO30HJe:b-mfehkb)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Closes: `#22204.

BTW Posting this as a _comment_ does not engage GitHub's auto-close logic.  I edited the PR overview with this text, so that it have immediate effect.

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCJyuEx9ic9GimNuqpY:bjmh5f1)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`setup/mac/source_distribution/install_prereqs_user_environment.sh` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCK-aofDbfbzeOibxd2:-OCK-aofDbfbzeOibxd3:bjw3d69) ([raw file](https://github.com/RobotLocomotion/drake/blob/22d9f962987d89cea38e883f6e2fd76dbe8d31e8/setup/mac/source_distribution/install_prereqs_user_environment.sh#L19)):*
> ```Shell
> bazelrc="${workspace_dir}/gen/environment.bazelrc"
> arch="$(/usr/bin/arch)"
> clang_version="$(clang --version |head -n1 |sed 's#.*(clang-\([0-9]*\)\..*#\1#g')"
> ```

I am skeptical that conditionalizing our setup script is worth the complexity cost (possibility of failure).  Instead, it seems to me that we could declare XCode >= 16 as our only supported version moving forward (i.e., in the nightly build, and then released as of Drake 1.36).  In that case, we would add the new `-fno-assume...` line to the `macos.bazelrc` directly.
___
*[`setup/mac/source_distribution/install_prereqs_user_environment.sh` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCK0hCK1xAkKkTNh-qt:-OCK0hCK1xAkKkTNh-qu:b-980tlj) ([raw file](https://github.com/RobotLocomotion/drake/blob/22d9f962987d89cea38e883f6e2fd76dbe8d31e8/setup/mac/source_distribution/install_prereqs_user_environment.sh#L29)):*
> ```Shell
> if (( $clang_version >= 1600 )); then
> cat >> "${bazelrc}" <<EOF
> import %workspace%/tools/apple-clang-1600.bazelrc
> ```

The `install_prereqs_user_environment.sh` is not run during CMake builds.  Instead, its logic is re-implemented fresh:

https://github.com/RobotLocomotion/drake/blob/1c5e3415c9a30c0bf15c4cc13d2173c0019dc865/CMakeLists.txt#L44-L55

If we keep the version-probing logic, then we need to do it in both places.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`setup/mac/source_distribution/install_prereqs_user_environment.sh` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCK-aofDbfbzeOibxd2:-OCMBZzl0Gx1ZEtAGclL:b9lla7l) ([raw file](https://github.com/RobotLocomotion/drake/blob/22d9f962987d89cea38e883f6e2fd76dbe8d31e8/setup/mac/source_distribution/install_prereqs_user_environment.sh#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am skeptical that conditionalizing our setup script is worth the complexity cost (possibility of failure).  Instead, it seems to me that we could declare XCode >= 16 as our only supported version moving forward (i.e., in the nightly build, and then released as of Drake 1.36).  In that case, we would add the new `-fno-assume...` line to the `macos.bazelrc` directly.
</blockquote></details>

flag day it is, then.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`setup/mac/source_distribution/install_prereqs_user_environment.sh` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCK-aofDbfbzeOibxd2:-OCOnZ6S4_HcaKrOQ_g1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/22d9f962987d89cea38e883f6e2fd76dbe8d31e8/setup/mac/source_distribution/install_prereqs_user_environment.sh#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

flag day it is, then.
</blockquote></details>

Done.
___
*[`setup/mac/source_distribution/install_prereqs_user_environment.sh` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCK0hCK1xAkKkTNh-qt:-OCOnb067W0vEEtnK93M:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/22d9f962987d89cea38e883f6e2fd76dbe8d31e8/setup/mac/source_distribution/install_prereqs_user_environment.sh#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `install_prereqs_user_environment.sh` is not run during CMake builds.  Instead, its logic is re-implemented fresh:

https://github.com/RobotLocomotion/drake/blob/1c5e3415c9a30c0bf15c4cc13d2173c0019dc865/CMakeLists.txt#L44-L55

If we keep the version-probing logic, then we need to do it in both places.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: none) +(release notes: fix) Probably needs to be in "Announcements" section of release notes as well.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCOpVzNAYZ15bJOZk2I:b-axu3ij)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
Sonoma CI will fail until images are re-spun with Xcode 16 or later.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCOptOO2IlFSvCAVjtJ:bnjklbv)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCPpHcV49jNtot6Rnx5:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`doc/_pages/installation.md` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCPnn0K8jiRl-MmYV4e:-OCPnn0K8jiRl-MmYV4f:b-1bh9dh) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5a08dcc08506e5ef8c18339ea10b124ec8d675f/doc/_pages/installation.md#L69)):*
> ```Markdown
> | Ubuntu 24.04 LTS (Noble Numbat)    | GCC 13                   | C++20 |
> | macOS Sonoma (14)                  | Apple LLVM 16 (Xcode 16) | C++20 |
> | macOS Sequoia (15)                 | Apple LLVM 16 (Xcode 16) | C++20 |
> ```

nit I think it's fine for Sequoia row in the table say either `TBD` or `XCode 16` for the compiler, but whichever one we choose we should be consistent between `installation.md` and `from_source.md`.  Right now we have `XCode 16` here and `TBD` in `from_source.md`.
___
*[`tools/macos.bazelrc` line 16 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-OCPojEF6c298ARUj45Q:-OCPojEF6c298ARUj45R:b-ubjc6j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5a08dcc08506e5ef8c18339ea10b124ec8d675f/tools/macos.bazelrc#L16)):*
> ```
> 
> # https://github.com/RobotLocomotion/drake/issues/22204
> build:clang --copt=-fno-assume-unique-vtables
> ```

nit The user passing `--config=clang` on the command line is *not* required.  We need to compile correctly by default without any flags on the command line.  (See my suggested edit, below.)

Yes, the "Options for explicitly using Clang" stanza below is nonsense.  Ideally, our macOS CI scripting would *not* be passing `--config=clang` so that CI would have caught this bug for us.  If you are eager, you're invited to PR to https://github.com/RobotLocomotion/drake-ci with that fix as well, though I'm also fine if you'd rather just ignore it.



_Suggestion:_
```
build --copt=-fno-assume-unique-vtables
```

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review, Monday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCQ3wdV6FBLUkkNOIl5:bxii12v)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 
BTW, does this warrant a slack message in the DrakeDevelopers workspace in case this immediately affects developers on macOS? 

> Reviewed 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCZvQH4C8G4s75LeHlJ:b-5dfk4s)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
Yes.  However, the bigger picture is that we can't merge this until new CI images are ready, which is estimated to be a couple of weeks away.

**Review by xuchenhan-tri — COMMENTED** [review]
Good to know, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-OCZwoqn1wJTdUsEjNHJ:bgzdlde)* status: labeled "do not merge" (waiting on @rpoyner-tri)

**Comment by williamjallen** [comment]
@rpoyner-tri the new CI images containing Xcode 16 have been prepared.  Please let me know when you'd like the new Sonoma images to be enabled in CI.  The Sequoia unprovisioned and provisioned images are already available.

**Comment by rpoyner-tri** [comment]
Let's enable the new images ASAP; I'd like to get a clean nightly on the new images tonight.

**Comment by williamjallen** [comment]
@rpoyner-tri I just enabled the new Sonoma unprovisioned and provisioned images.

**Review by rpoyner-tri — COMMENTED** [review]
looks like I need a rebase here; I'll do that now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227#-:-ODvXU7e6gh7P2eq6-04:b43nw07)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22227)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
