### PR TITLE
[framework] Adjust "sole port" getters to work around deprecation

### LINKED ISSUE #20082: Behavior of "sole port" functions vs deprecation
**Is your feature request related to a problem? Please describe.**

We have a few convenience functions in Drake that make it easier to use Systems that have exactly 1 input port or 1 output port.

For example, `system.get_output_port()` with no arguments returns the sole output port, or `builder.Connect(src_sys, dest_sys)` connects the sole output port on `src_sys` to the sole input port on `dest_sys`, so the user doesn't need to type in the boilerplate `builder.Connect(src_sys.get_output_port(), dest_sys.get_input_port()`` etc.

However, when deprecating a sole input (or output) port, we will temporarily have _two_ ports declared -- the old name and the new name.  This will break any downstream code that relied on the "sole port" magic functions.  See e.g. `planar_gripper_simulation` in #20079.

**Describe the solution you'd like**

Framework functions that require a "sole port" should ignore deprecated ports.  If there is exactly one non-deprecated port, it should be automatically selected, with no warnings.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20082.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for feature review, please.

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-:-Nd0mWq49EbOfsOGIdu0:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
Feature pass done. Definitely a nice touch. The new inconsistency between the one-port sugar methods and port counters is bothering me though, PTAL below. Please consider reconciling those so that count==1 continues to mean we can use the sugar.

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-:-Nd1EncXDEAiet0ay7X1:b-63yrnx)* status: 9 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`systems/controllers/linear_model_predictive_controller.cc` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd16Jwo0zyeiOPIeYT5:-Nd16Jwo0zyeiOPIeYT6:b925xis) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/controllers/linear_model_predictive_controller.cc#L43)):*
> ```cpp
>   // Check that the model is SISO
>   model_->get_input_port();
>   model_->get_output_port();
> ```

BTW this seems awkward compared to the more straightforward original
```c++
 DRAKE_DEMAND(model_->num_input_ports() == 1);
  DRAKE_DEMAND(model_->num_output_ports() == 1);
```

I presume the problem is that num_input_ports() now counts both the renamed port and the deprecated one? Maybe it would be worth changing num_foo_ports() not to count deprecated ports? (Would likely need to rename the old one num_input_ports_including_deprecated() for internal use.)
___
*[`systems/framework/diagram_builder.h` line 369 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd17YyT8nGe35modHIF:-Nd17YyT8nGe35modHIG:b-jw75hs) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/diagram_builder.h#L369)):*
> ```objc
>   /// output port on the @p src system.
>   /// This function ignores deprecated ports, unless there is only port in which
>   /// case it will use the deprecated port.
> ```

typo: there is only port -> that is the only port
___
*[`systems/framework/diagram_builder.cc` line 238 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd17xL973ROQl53LalH:-Nd17xL973ROQl53LalI:b-mmjwwz) ([raw file](https://github.com/RobotLocomotion/drake/blob/55c57ac3d7474d3a3a9cc575d8b99e3d990d894a/systems/framework/diagram_builder.cc#L238)):*
> ```cpp
>   ThrowIfAlreadyBuilt();
>   DRAKE_THROW_UNLESS(src.num_output_ports() == 1);
>   DRAKE_THROW_UNLESS(dest.num_input_ports() == 1);
> ```

BTW use code might also have these checks before calling Connect() -- that would fail for deprecated-port systems even if Connect() would succeed. Consider making the count match the sugar behavior.
___
*[`systems/framework/system.h` line 1099 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd18jrA3O84qj9ER9Tg:-Nd18jrA3O84qj9ER9Th:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.h#L1099)):*
> ```objc
> 
>   /** Convenience method for the case of exactly one input port.
>   This function ignores deprecated ports, unless there is only port in which
> ```

typo
___
*[`systems/framework/system.h` line 1142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1AnTYBwF1GLNE46Uv:-Nd1AnTYBwF1GLNE46Uw:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.h#L1142)):*
> ```objc
> 
>   /** Convenience method for the case of exactly one output port.
>   This function ignores deprecated ports, unless there is only port in which
> ```

typo
___
*[`systems/framework/system.cc` line 767 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1ChTBBdOG2_VVzoF4:-Nd1ChTBBdOG2_VVzoF5:b-552hgq) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L767)):*
> ```cpp
>     if (port_base.get_deprecation() == std::nullopt) {
>       ++num_non_deprecated;
>       non_deprecated_index = i;
> ```

BTW  to avoid being at the O(n) mercy of a many-port system you could duck out after the 2nd non-deprecated port. Message below would have to change to "more than one".
___
*[`systems/framework/system.cc` line 776 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1BwY33T5BA26PVYCk:-Nd1BwY33T5BA26PVYCl:b-hdel2d) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L776)):*
> ```cpp
>   // Too many inputs.
>   throw std::logic_error(fmt::format(
>       "System::get_input_port(): {} system '{}' has {} inputs, so this "
> ```

minor: this message says the system has "n inputs" where n=num_non_deprecated. That will be awkwardly inconsistent with num_input_ports() applied to this same system as currently implemented. The message should say "non deprecated" (at least if there are some deprecated ports) or (better IMO) make num_input_ports() report only non-deprecated ports.

(same comments for GetSoleOutputPort())
___
*[`systems/framework/test/system_test.cc` line 434 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1ETS2EdJxZonSkR_6:-Nd1ETS2EdJxZonSkR_7:bse4mhp) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/test/system_test.cc#L434)):*
> ```cpp
> 
>   // Three deprecated ports: fail
>   // The error message is lame, but doesn't seem worth fixing.
> ```

minor: it's at least worth adding "non deprecated" to the message
___
*[`systems/framework/test/system_test.cc` line 469 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1Ej9iDapgkUTXqZz8:-Nd1Ej9iDapgkUTXqZz9:byjlwr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/test/system_test.cc#L469)):*
> ```cpp
> 
>   // Three deprecated ports: fail.
>   // The error message is lame, but doesn't seem worth fixing.
> ```

minor: ditto

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090)* status: 8 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`systems/controllers/linear_model_predictive_controller.cc` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd16Jwo0zyeiOPIeYT5:-Nd1GS6t-59M94WHsJ3z:bdsrn0g) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/controllers/linear_model_predictive_controller.cc#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems awkward compared to the more straightforward original
```c++
 DRAKE_DEMAND(model_->num_input_ports() == 1);
  DRAKE_DEMAND(model_->num_output_ports() == 1);
```

I presume the problem is that num_input_ports() now counts both the renamed port and the deprecated one? Maybe it would be worth changing num_foo_ports() not to count deprecated ports? (Would likely need to rename the old one num_input_ports_including_deprecated() for internal use.)
</blockquote></details>

This would be possible if we used Identifier instead of Index to access ports, and we used iterators instead of array getters.  However, it is not possible with the current design where ports are densely packed within a continuous set of indices.

There is no rule that deprecated ports need to come first (or last) within the list of ports; they could even be mingled in the middle.  If the user checked `num_input_ports() == 1` and then accessed `get_input_port(0)`, they might get the deprecated port by mistake.
___
*[`systems/framework/system.cc` line 767 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1ChTBBdOG2_VVzoF4:-Nd1H0Av1n0xjK3_iBr6:b-8au0k1) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L767)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW  to avoid being at the O(n) mercy of a many-port system you could duck out after the 2nd non-deprecated port. Message below would have to change to "more than one".
</blockquote></details>

Given that we're about to crash, I'm happy to spend the time to give a slightly more detailed error message.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram_builder.cc` line 238 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd17xL973ROQl53LalH:-Nd1Jsrb4A_dhhsAVeDE:b4x3cjr) ([raw file](https://github.com/RobotLocomotion/drake/blob/55c57ac3d7474d3a3a9cc575d8b99e3d990d894a/systems/framework/diagram_builder.cc#L238)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW use code might also have these checks before calling Connect() -- that would fail for deprecated-port systems even if Connect() would succeed. Consider making the count match the sugar behavior.
</blockquote></details>

See other thread -- it doesn't seem realistic.
___
*[`systems/framework/system.cc` line 767 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1ChTBBdOG2_VVzoF4:-Nd1JLAY2C1IX9lkJb7F:b-7j5w8m) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L767)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given that we're about to crash, I'm happy to spend the time to give a slightly more detailed error message.
</blockquote></details>

(Actually, same disposition but for a different reason.  Code clarity is the goal here, and I think trying to break early might pollute that.)
___
*[`systems/framework/system.cc` line 776 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1BwY33T5BA26PVYCk:-Nd1It0i3ftn6ZnsKD-y:b-jk8qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L776)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this message says the system has "n inputs" where n=num_non_deprecated. That will be awkwardly inconsistent with num_input_ports() applied to this same system as currently implemented. The message should say "non deprecated" (at least if there are some deprecated ports) or (better IMO) make num_input_ports() report only non-deprecated ports.

(same comments for GetSoleOutputPort())
</blockquote></details>

Changed to report the actual number of ports.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one suggestion
@rpoyner-tri for platform review per rotation, please

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-:-Nd1V2fc7RCHWTM4w6SQ:bmh9m2x)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`systems/controllers/linear_model_predictive_controller.cc` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd16Jwo0zyeiOPIeYT5:-Nd1Syys2FP3582i4nAC:bhekuci) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/controllers/linear_model_predictive_controller.cc#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This would be possible if we used Identifier instead of Index to access ports, and we used iterators instead of array getters.  However, it is not possible with the current design where ports are densely packed within a continuous set of indices.

There is no rule that deprecated ports need to come first (or last) within the list of ports; they could even be mingled in the middle.  If the user checked `num_input_ports() == 1` and then accessed `get_input_port(0)`, they might get the deprecated port by mistake.
</blockquote></details>

I see your point.
___
*[`systems/framework/system.cc` line 776 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-Nd1BwY33T5BA26PVYCk:-Nd1TTR88RFEnOehyI2t:b-392zmp) ([raw file](https://github.com/RobotLocomotion/drake/blob/07b2fd93c18f200bc093ec2bc631689f46ad1a3e/systems/framework/system.cc#L776)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Changed to report the actual number of ports.
</blockquote></details>

BTW That's marginally better but it still doesn't capture exactly why this fails -- it is because there is more than one _non-deprecated_ port. Better I think would be to continue to report the number of non-deprecated ports but change the text to read "has {} non-deprecated inputs"

**Review by sherm1 — COMMENTED** [review]
Er, +@rpoyner-tri that is!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-:-Nd1Y1040dqaSZY-OD6w:b-tf8qxk)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20090#-:-Nd1a_u_E4Jx0RNGD0Bt:bnfp4nl)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Pull request merged**
