### PR TITLE
Add python binding for SceneGraph::RemoveGeometry

### PR DESCRIPTION
**Pull request by hongkai-dai**
cc @SeanCurtis-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17336)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17336#-:-N3rCgCZ8erHi5hucTLl:bhru7xi)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2 with some small comments

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17336#-:-N3tPKNK0A0PockykEjm:b264lc4)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 301 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tPcpM3sHLvq1Q3EaW:-N3tPcpM3sHLvq1Q3EaX:b-j1e4hp) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L301)):*
> ```Python
>     def test_scene_graph_remove_geometry(self, T):
>         SceneGraph = mut.SceneGraph_[T]
>         InputPort = InputPort_[T]
> ```

`InputPort` and `OutputPort` are unused.
___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 306 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tPZCq-fl1tY8sVVas:-N3tPZCq-fl1tY8sVVat:by6inwl) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L306)):*
> ```Python
>         scene_graph = SceneGraph()
>         global_source = scene_graph.RegisterSource("anchored")
>         global_frame = scene_graph.RegisterFrame(
> ```

nit To make test more compact, why not use `SceneGraph.world_frame_id()`?
___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tOsUg64-3NHHJ5VUt:-N3tOsUg64-3NHHJ5VUu:bebsjs7) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L309)):*
> ```Python
>             source_id=global_source,
>             frame=mut.GeometryFrame("anchored_frame1"))
>         scene_graph.RegisterFrame(
> ```

nit This frame appears unused. Can we remove it?
___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tOlvaBi1Gq_Ch05Ap:-N3tOlvaBi1Gq_Ch05Aq:b-5l59uf) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L324)):*
> ```Python
>             source_id=global_source,
>             geometry_id=global_geometry)
>         self.assertEqual(inspector.num_geometries(), 1)
> ```

nit This test isn't checking the context-bound operation. Should you add something like:
```
self.assertEqual(context_inspector.num_geometries(), 0)  # Changed
self.assertEqual(model_inspector.num_geometries(), 1)  # Unchanged
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17336)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 301 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tPcpM3sHLvq1Q3EaW:-N3tdOsM3Pedignwep-k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L301)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`InputPort` and `OutputPort` are unused.
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/geometry_scene_graph_test.py` line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17336#-N3tOlvaBi1Gq_Ch05Ap:-N3tfqxz3RqLciDF-oGK:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/7e0328fcd66f472a08b1f1a8ac090d80b11dd89c/bindings/pydrake/test/geometry_scene_graph_test.py#L324)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This test isn't checking the context-bound operation. Should you add something like:
```
self.assertEqual(context_inspector.num_geometries(), 0)  # Changed
self.assertEqual(model_inspector.num_geometries(), 1)  # Unchanged
```
</blockquote></details>

Done. Good catch.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17336)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
