### PR TITLE
Add Reset functions for realtime rate calculation

### PR DESCRIPTION
**Pull request by Xining-Du**
Previously when resuming simulator from a paused state, the realtime rate (RTR) calculator will use a wrong prev_sim_time_, resulting in a sudden drop of RTR in meshcat. This adds a new API ResetRealtimeRateCalculator() to meshcat visualizer which should be called upon simulation resuming to fix the issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot ok to test

**Review by joemasterjohn — COMMENTED** [review]
+@joemasterjohn for feature review.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-:-NYiPKSSCKiZmxV2M8Rd:bjjfqi0)* status: 9 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @Xining-Du)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiUXPL9YGBgGs-z1iS:-NYiUXPL9YGBgGs-z1iT:b-z1g4cv) (no related file):*
You'll need a unit test in `geometry/test/meshcat_visualizer_test.cc` for coverage of `ResetRealtimeRateCalculator()`.

___
___
*[`geometry/meshcat_visualizer.h` line 67 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiLsQtERYYi_GHhgI0:-NYiLsQtERYYi_GHhgI1:b-7bp4al) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/geometry/meshcat_visualizer.h#L67)):*
> ```objc
> 
>   /** Resets the realtime rate calculator so that realtime rate is accurate
>    * after simulator is resumed from a paused state. */
> ```

Comment should match the formatting of other comments in this file.

Also, you state just one of the possible use cases for resetting the realtime rate calculator. You might for instance have distinct periods in your sim where you'd like to measure realtime rate separately (a period of many transient contacts vs. a steady state, etc.) I'd just state the contract of the function upfront and then mention any possible uses cases after. My suggestion is below.



_Suggestion:_
```objc
  /** Resets the realtime rate calculator. Calculation will resume on the next
   periodic publish event. This is useful for correcting the realtime rate after
   simulator is resumed from a paused state, etc. */
```
___
*[`geometry/meshcat_visualizer.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiP7pDAiku9RlSAmLb:-NYiP7pDAiku9RlSAmLc:b-jgk85n) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/geometry/meshcat_visualizer.h#L68)):*
> ```objc
>   /** Resets the realtime rate calculator so that realtime rate is accurate
>    * after simulator is resumed from a paused state. */
>   void ResetRealtimeRateCalculator() const { realtime_rate_calculator_.Reset(); }
> ```

This new function now sits in between two constructors of the class. Breaking up this logical grouping of common functions hurts readability. I'd place this function after the scalar-converting constructor.
___
*[`systems/analysis/instantaneous_realtime_rate_calculator.h` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiRI_Z1ApLX-ArqHtY:-NYiRI_Z1ApLX-ArqHtZ:b-hv6fbh) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/instantaneous_realtime_rate_calculator.h#L31)):*
> ```objc
>    * the first call after the simulator is resumed. Otherwise the realtime
>    * rate value would be inaccurate since the timer was not paused.
>    */
> ```

Instead of stating the use case that was the inception of the function, just state its contract and how it affects the class or relevant functions. My suggestion is below. Also private members of a class shouldn't be mentioned in a public functions documentation.



_Suggestion:_
```objc
  /* Resets the internal state of `this` rate calculator. After a call, the next
   call to UpdateAndRecalculate() will re-seed the rate calculation as if it was
   the first call.
   */
```
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiST4rC6vwRK3KuGdC:-NYiST4rC6vwRK3KuGdD:b-vvo091) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L39)):*
> ```cpp
> 
> // Tests that the InstantaneousRealtimeRateCalculator resets properly
> // after simulation is paused.
> ```

There is no simulation happening in this unit test. Just state that you are testing `Reset()`.



_Suggestion:_
```cpp
// Tests that the InstantaneousRealtimeRateCalculator resets properly on call to Reset().
```
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiU72w3tyK6SO2QUNJ:-NYiU72w3tyK6SO2QUNK:bw6vl91) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L44)):*
> ```cpp
> 
>   InstantaneousRealtimeRateCalculator calculator{};
>   calculator.InjectMockTimer(std::move(timer));
> ```

nit: No need for the named variable as it's not used in the test and the compiler will optimize it out anyway.



_Suggestion:_
```cpp
  InstantaneousRealtimeRateCalculator calculator{};
  calculator.InjectMockTimer(std::make_unique<MockTimer>());
```
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiSem2D0pzeZFPYMxN:-NYiSem2D0pzeZFPYMxO:br133hv) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L45)):*
> ```cpp
>   InstantaneousRealtimeRateCalculator calculator{};
>   calculator.InjectMockTimer(std::move(timer));
>   // First call is seed and gives nullopt result.
> ```

nit: grammar and you aren't testing that the seeding actually happened.



_Suggestion:_
```cpp
  // First (seed) call returns nullopt.
```
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiT9XD0oiASWsaWx1e:-NYiT9XD0oiASWsaWx1f:b2z3ner) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L54)):*
> ```cpp
> 
>   // Pause simulation for 2.0 seconds, then unpausing will reset the 
>   // prev_sim_time_ to nullopt, so the next calculation will be correct.
> ```

No simulation actually happening here, so don't mention it.



_Suggestion:_
```cpp
  // Reset the calculator to initial state.
```
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiTRDS5q1wCqX2tauH:-NYiTRDS5q1wCqX2tauI:b-xx0ost) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L57)):*
> ```cpp
>   calculator.Reset();
> 
>   // Reset time and observe another nullopt result.
> ```

You reset above, not here. Just state the expected behavior in terms of the function's contract.



_Suggestion:_
```cpp
  // First call to UpdateAndRecalculate() after Reset() returns nullopt.
  // and calculation resumes on the next call.
```

**Review by joemasterjohn — COMMENTED** [review]
Looks like CI is failing because of code formatting errors. You can lint the files you changed with:

```
bazel test --config lint //geometry/...
bazel test --config lint //systems/analysis/...
```

The styleguide lives [at this site](https://drake.mit.edu/styleguide/cppguide.html). `clang-format` should use `.clang-format` file in the root of the drake repository.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-:-NYiUqug7OPjWt01STXy:b-mcjxkg)* status: 9 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @Xining-Du)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667)* status: 11 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @Xining-Du)

___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiXnoD4ZAT3V4uGsGL:-NYiXnoD4ZAT3V4uGsGM:b-75309t) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L35)):*
> ```cpp
>   // Reset time and observe another nullopt result.
>   EXPECT_FALSE(calculator.UpdateAndRecalculate(0.0).has_value());
>   EXPECT_DOUBLE_EQ(calculator.UpdateAndRecalculate(0.1).value(), 1.0);
> ```

Add the call to Reset() at the end of this unit test and verify it here. 
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiXAOf8boquRDXKQe9:-NYiXAOf8boquRDXKQeA:b6q9rga) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L40)):*
> ```cpp
> // Tests that the InstantaneousRealtimeRateCalculator resets properly
> // after simulation is paused.
> GTEST_TEST(InstantaneousRealtimeRateCalculatorTest, UnpausedSimTest) {
> ```

This test repeats all of the same setup as `BasicTest` just for one call to `Reset()`. The function is so simple, it doesn't really require its own setup, I suggest moving it into the end of `BasicTest`. I believe the things tested there would have no effect on testing Reset() afterwards. 



_Code quote:_
```cpp
GTEST_TEST(InstantaneousRealtimeRateCalculatorTest, UnpausedSimTest) {
```

**Review by Xining-Du — COMMENTED** [review]
Fixed format issues.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-:-NZ25MWVDezAw0Vn3F1O:bhqkzto)* status: 9 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiUXPL9YGBgGs-z1iS:-NZ1zno7-TCOrWvp3D4G:b-pe02s6) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

You'll need a unit test in `geometry/test/meshcat_visualizer_test.cc` for coverage of `ResetRealtimeRateCalculator()`.
</blockquote></details>

Done. Added additional tests in BasicTest.

___
___
*[`geometry/meshcat_visualizer.h` line 67 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiLsQtERYYi_GHhgI0:-NZ2-Opx1FL3mIXiiCAF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/geometry/meshcat_visualizer.h#L67)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Comment should match the formatting of other comments in this file.

Also, you state just one of the possible use cases for resetting the realtime rate calculator. You might for instance have distinct periods in your sim where you'd like to measure realtime rate separately (a period of many transient contacts vs. a steady state, etc.) I'd just state the contract of the function upfront and then mention any possible uses cases after. My suggestion is below.
</blockquote></details>

Done.
___
*[`geometry/meshcat_visualizer.h` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiP7pDAiku9RlSAmLb:-NZ2-hIM643vuxuUxjdp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/geometry/meshcat_visualizer.h#L68)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

This new function now sits in between two constructors of the class. Breaking up this logical grouping of common functions hurts readability. I'd place this function after the scalar-converting constructor.
</blockquote></details>

Done.
___
*[`systems/analysis/instantaneous_realtime_rate_calculator.h` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiRI_Z1ApLX-ArqHtY:-NZ2-mVj0L4Vfs6rbnzM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/instantaneous_realtime_rate_calculator.h#L31)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Instead of stating the use case that was the inception of the function, just state its contract and how it affects the class or relevant functions. My suggestion is below. Also private members of a class shouldn't be mentioned in a public functions documentation.
</blockquote></details>

Done.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiXnoD4ZAT3V4uGsGL:-NZ2607S8CzehqcRxf8_:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L35)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Add the call to Reset() at the end of this unit test and verify it here. 
</blockquote></details>

Done.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiST4rC6vwRK3KuGdC:-NZ25YXP6u9BWXE5NiVe:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L39)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

There is no simulation happening in this unit test. Just state that you are testing `Reset()`.
</blockquote></details>

Done.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiXAOf8boquRDXKQe9:-NZ25p6JDDNF_YhJZHga:b-srz03b) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L40)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

This test repeats all of the same setup as `BasicTest` just for one call to `Reset()`. The function is so simple, it doesn't really require its own setup, I suggest moving it into the end of `BasicTest`. I believe the things tested there would have no effect on testing Reset() afterwards. 
</blockquote></details>

Combined it with BasicTest.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiU72w3tyK6SO2QUNJ:-NZ207aZ7DhY7iU0uBWb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L44)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: No need for the named variable as it's not used in the test and the compiler will optimize it out anyway.
</blockquote></details>

Done.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiSem2D0pzeZFPYMxN:-NZ25hW71l2ogcCTdvSw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L45)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: grammar and you aren't testing that the seeding actually happened.
</blockquote></details>

Done.
___
*[`systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-NYiTRDS5q1wCqX2tauH:-NZ26F5RE2NO6IyyhFpu:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/340068213f3d56392e42b6172f5038e3cced907e/systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc#L57)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

You reset above, not here. Just state the expected behavior in terms of the function's contract.
</blockquote></details>

Done.

**Review by joemasterjohn — COMMENTED** [review]
Awesome! :lgtm: +@EricCousineau-TRI for platform review, please.

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-:-NZ2MkJ229DGy_OcBKz-:b-9mzu5v)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @Xining-Du)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19667#-:-NZ343xz3wqgsVHfj6gX:bhm0jc2)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @Xining-Du)

**Pull request merged**
