### PR TITLE
Add utility to run pycodestyle on Bazel files

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create a new utility that wraps pycodestyle, disabling some checks and adding another (to enforce space around named parameters). Create `bazel_lint.bzl` to invoke this, adding the ability to ignore further checks (and also adding this same ability to `python_lint.bzl`).

By default, `bazel_lint` disables some checks that are inimical to readability, in addition to the checks which are hard-disabled by the wrapper. (The latter are checks that are either impossible to enforce in Skylark as they request use of non-existing features, or are contrary to buildifier formatting.)

Note that this is not yet integrated into the build, as there are a significant number of style issues currently present. This is being PR'd as-is first to make the tool available, so that developers have a way to check new work. We will start enforcing style later, as style issues are fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6384)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MgmIElG1GtGi-cDA:-Kn1MgmIElG1GtGi-cDB:b4aujka) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L11)):*
> ```Python
>         if ignore:
>             ignore = ["--ignore=" + ",".join(["E%s" % e for e in ignore])]
>             print(ignore[0])
> ```

It seems like this would display warnings to the user's console by default?  That doesn't seem warranted to me, on first glance.

Ditto for the other print below.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-Kn1MYaZvq6ZDIJJpTWS:b-ffv8y8) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
> ```Python
>     _bazel_lint(
>         name = name,
>         files = native.glob(["*.bzl", "BUILD"]),
> ```

Probably also add `BUILD.bazel`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn1Ne6I1JXCtcJy9dNn:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Thanks. Since #6386 landed, I am putting this temporarily on hold. Once #6347 lands, I have another pending patch that will incidentally take care of the lingering issue in `install.bzl`. I'll update this after that lands also to also enable `bazel_lint` for `tools`, also fixing any errors that pop up in the mean time if needed.

If you'd rather stick with the original plan, that's fine also, just let me know. However now that the current state of the repo is nearly clean, I'm thinking it's reasonable to wait until this can be switched immediately to "enforcing".

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MgmIElG1GtGi-cDA:-Kn25U2F2rJm6cYBsjp0:beu7rcs) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like this would display warnings to the user's console by default?  That doesn't seem warranted to me, on first glance.

Ditto for the other print below.
</blockquote></details>

Oops; leftover cruft from debugging. Will remove in next update. Thanks.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-Kn25_RKyRLASjsA-ukY:b-7euxlt) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Probably also add `BUILD.bazel`.
</blockquote></details>

In *theory* buildifier is sufficient for non-Skylark files... but sure, no reason not to include `BUILD.bazel`. Will be in the next update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn25qbfT8mWCpCOVcTs:bspi8oi)*

**Comment by jwnimmer-tri** [comment]
Not sure if that question was for @jamiesnape or me, but I'm okay with any path forward.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MgmIElG1GtGi-cDA:-Kn2Ba9Y3oH35lVlpOcA:btojbfq) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L11)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Oops; leftover cruft from debugging. Will remove in next update. Thanks.
</blockquote></details>

Great.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-Kn2Bc_cUx7RTIOBFWWG:b-8llkbo) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

In *theory* buildifier is sufficient for non-Skylark files... but sure, no reason not to include `BUILD.bazel`. Will be in the next update.
</blockquote></details>

At least to keep `BUILD` and `BUILD.bazel` identically treated, one way or another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn2BWHeUR1uYD0DqYM0:bktchuh)*

**Comment by jamiesnape** [comment]
I am ok with either. Do we have to add `bazel_lint()` at the end of each file? If so, I think it is time for a `lint()` macro to run `bazel_lint()`, `cpplint()`, `python_lint()` to appear at the end of every `BUILD` file regardless of content.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn4b3q0nMI7Yk7TaOCD:b-fkz3g5)*

**Comment by mwoehlke-kitware** [comment]
> Do we have to add `bazel_lint()` at the end of each file?

I *think* "yes", though since `bazel_lint()` is based on `glob` rather than `existing_rules`, it might be possible for a rule at the repo root to see everything.

> If so, I think it is time for a `lint()` macro to run `bazel_lint()`, `cpplint()`, `python_lint()` to appear at the end of every BUILD file regardless of content.

Possibly. I'd prefer to do that separately, as I am not even trying to `bazel_lint` anything outside of `tools` yet in this PR. (As we turn on `bazel_lint` for more things, we could do it by introducing such a helper.)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-Kn4ry9RTrLJ9178_pME:b-wugjah) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

At least to keep `BUILD` and `BUILD.bazel` identically treated, one way or another.
</blockquote></details>

Right.

It just occurred to me that `*.BUILD` could also be added... however, if we end up with a `lint()` macro that is used in these, either we would need an option to disable bazel-lint, or they would be linted twice (but maybe we don't care?).

BTW, can buildifier be run in 'test' mode? There are some things it "catches" that `bzlcodestyle` does not (and vice versa of course).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn4r0WpnfAHPLJ0sGrQ:b4r0vku)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-Kn4ulOL4mg4qJCRjNwi:b-v4yc36) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Right.

It just occurred to me that `*.BUILD` could also be added... however, if we end up with a `lint()` macro that is used in these, either we would need an option to disable bazel-lint, or they would be linted twice (but maybe we don't care?).

BTW, can buildifier be run in 'test' mode? There are some things it "catches" that `bzlcodestyle` does not (and vice versa of course).
</blockquote></details>

I don't mind if things are checked twice.  There are a few places where we have a few cxx files linted twice.

Buildifier can run in check mode, like `./tools/buildifier.sh -mode=check BUILD.bazel`; however, its check behavior is to _print_ filenames that need reformatting, rather that a non-zero returncode.  We could update our shell-script wrapper to provide an exitcode if we like, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Comment by mwoehlke-kitware** [comment]
Updated; now enforcing both bzlcodestyle and buildifier on `tools`...

---

Review status: 2 of 22 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn67Ht_YyZca-yO17In:bm96prp)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn67cBQpqDkYPEa-2Lv:-Kn67cBRrzKk7iVhHZJm:b-7h6kwk) ([raw file](https://github.com/robotlocomotion/drake/blob/357ebe677e873d63fd2cdc92073c7a3e00e31c6c/tools/bazel_lint.bzl#L52)):*
> ```Python
>     _bazel_lint(
>         name = name,
>         # TODO(jwnimmer-tri) Add WORKSPACE to the list of files to find and
> ```

FYI this comment is copied from `buildifier.sh`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-:-Kn6LwDF1R_QMT13ZCw7:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tools/nlopt.BUILD, line 82 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn9ox77H_qFdH6vBT7A:-Kn9ox77H_qFdH6vBT7B:b-hb6sf7) ([raw file](https://github.com/robotlocomotion/drake/blob/357ebe677e873d63fd2cdc92073c7a3e00e31c6c/tools/nlopt.BUILD#L82)):*
> ```
>         "direct/direct-internal.h",
>         "direct/direct.h",
>         " cdirect/cdirect.c",
> ```

Extra space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Comment by mwoehlke-kitware** [comment]
Review status: 21 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/bazel_lint.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn1MYaZvq6ZDIJJpTWR:-KnATzuBC_Dz0PCjn4rH:b-5o2m3) ([raw file](https://github.com/robotlocomotion/drake/blob/a7132ff3739dbe114dda5a704544c55cb58d10be/tools/bazel_lint.bzl#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't mind if things are checked twice.  There are a few places where we have a few cxx files linted twice.

Buildifier can run in check mode, like `./tools/buildifier.sh -mode=check BUILD.bazel`; however, its check behavior is to _print_ filenames that need reformatting, rather that a non-zero returncode.  We could update our shell-script wrapper to provide an exitcode if we like, though.
</blockquote></details>

This has been added in the latest update.

---

*[tools/nlopt.BUILD, line 82 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6384#-Kn9ox77H_qFdH6vBT7A:-KnATi7Vbz1YexijQ1q_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/357ebe677e873d63fd2cdc92073c7a3e00e31c6c/tools/nlopt.BUILD#L82)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Extra space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Comment by jamiesnape** [comment]
Reviewed 7 of 7 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6384)*

**Pull request merged**
