### PR TITLE
Revert "Integrate IPOPT with Drake"

### PR DESCRIPTION
**Pull request by jamiesnape**
Dear @sammy-tri,

The oncall build cop believes that your PR #2505 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration on presubmit, because additional
platforms and tests are built in postsubmit.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-matlab/279/
https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-matlab/280/

Therefore, the build cop has created this revert PR and started a complete
postsubmit build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2572)

### CODE REVIEW

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental-matlab/37/

**Comment by sammy-tri** [comment]
Can we hold back on this PR for a moment?  I'm going to submit an alternate which disables IPOPT on Mac for now to minimize flail in the main tree...

**Comment by sammy-tri** [comment]
#2573 has passed on mac with ipopt disabled, and it's just waiting on linux matlab now.  Definitely suggest merging that instead once the builder is done.

**Comment by jamiesnape** [comment]
The continuous job was the one that was failing, so either of these needs to pass:
* https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental-matlab/37/
* https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental-matlab/38/

**Comment by sammy-tri** [comment]
Thank you for starting a mac matlab build with #2573 applied.  It really will do a lot less damage to other in-flight PR's than a revert.

**Comment by liangfok** [comment]
I have an OS X machine with Matlab installed but was unable to replicate the error. Maybe it's because I don't have a particular solver installed?

**Comment by sammy-tri** [comment]
I think you would need SNOPT installed to see the error (as well as IPOPT which is on by default...  or till be until #2753 is applied).  The mex files in question aren't built when only IPOPT is available because the solver hasn't been tuned well enough to get the tests to pass.

**Comment by liangfok** [comment]
That explains it. I did not enable SNOPT. I will retry with SNOPT enabled and report back.

**Comment by liangfok** [comment]
I enabled MATLAB and SNOPT on my OS X build and got mixed results.

# Commands
Here are the commands I executed:

```
$ cd drake-build
$ cmake ../drake-distro -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DDISABLE_MATLAB=OFF -DWITH_SNOPT=ON -DWITH_SNOPT_PRECOMPILED=OFF
$ ninja -j1
$ cd drake
$ cmake -DLONG_RUNNING_TESTS=ON .
$ cd ..
$ ninja -j1
```
# Failures Successfully Replicated
The following test failed as they did in CI:

```
$ ctest -VV -R solvers/test/testMultipleTaskSpaceRRTStar
$ ctest -VV -R solvers/test/testTaskSpaceRRT
$ ctest -VV -R systems/plants/test/testApproximateIK
$ ctest -VV -R systems/plants/test/testIKtraj
```

# Failures Unsuccessfully Replicated
The following tests were successful even though they failed in CI:

```
$ ctest -VV -R examples/Atlas/runAtlasHandControl
$ ctest -VV -R systems/plants/test/testIK
$ ctest -VV -R examples/Atlas/runAtlasWalkingPlanning
```

# Failures That Couldn't Be Tested
The following unit tests couldn't be tested because `gurobi` was not available:

```
$ ctest -VV -R examples/Atlas/runAtlasManip
```

**Comment by jwnimmer-tri** [comment]
@jamiesnape Can this PR be closed now?

**Comment by jamiesnape** [comment]
Yes.

**Pull request closed without merging**
