### PR TITLE
Add CollisionGeometry for C-Iris.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Currently we only add box and convex polytopes.
Will add sphere, cylinder and capsule in the next PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please.

Since the change is in the dev folder, we only need one reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358#-:-NHb-vWyDegC0u4Bu4rp:b73iywj)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)* status: 10 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.h` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbFh1f-8-zne2EpneU:-NHbFh1f-8-zne2EpneV:b-o1a4u4) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L48)):*
> ```objc
>    this constraint with the following conditions
>    1. Some rational functions are always non-negative.
>    2. Certain vector has length <= 1.
> ```

nit gramma: "A certain"
___
*[`geometry/optimization/dev/collision_geometry.h` line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbGCg887KutrWvnJDm:-NHbGCg887KutrWvnJDn:byzy74b) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L56)):*
> ```objc
>    |a| ≤ 1                      (2)
>    where p_AS(s) is the position of the sphere center S expressed in a frame A.
>    The lefet hand side of equation (1) is a rational function of indeterminate
> ```

nit spelling "left hand side"
___
*[`geometry/optimization/dev/collision_geometry.h` line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbGIpYB5Inw-RBr60J:-NHbGIpYB5Inw-RBr60K:bafua8o) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L60)):*
> ```objc
> 
>    Similarly we can write down the conditions for other geometry types,
>    including polytopes, cylinders and capsules.
> ```

nit: missing last comma after cylinders
___
*[`geometry/optimization/dev/collision_geometry.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbGehu7jo2Je2RRqCy:-NHbGehu7jo2Je2RRqCz:bcqpfmy) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L96)):*
> ```objc
> 
>  private:
>   // Implement support shapes for the ShapeReifier interface.
> ```

nit spelling "Implements"
___
*[`geometry/optimization/dev/collision_geometry.h` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbGlBnDGsb1XY9hoWT:-NHbGlBnDGsb1XY9hoWU:bk72q29) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L101)):*
> ```objc
>   // void ImplementGeometry(const Capsule& capsule, void* data) final;
>   void ImplementGeometry(const Convex& convex, void* data) final;
>   // void ImplementGeometry(const Cylinder& cylinder, void* data) final;
> ```

Remove these comments for this PR perhaps?
___
*[`geometry/optimization/dev/collision_geometry.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbHoeT65r8CSvR-xjD:-NHbHoeT65r8CSvR-xjE:b-egphm6) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L66)):*
> ```cpp
> // Compute the rational function
> // aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
> // -offset - separating_margin -(aᵀ*p_AQ + b) if plane_side = kNegative
> ```

I think this would be easier to read if it were consistent with the order of the terms here and also on the expansion
___
*[`geometry/optimization/dev/collision_geometry.cc` line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbIJMe6VwYO7j3-waf:-NHbIJMe6VwYO7j3-wag:blg2258) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L67)):*
> ```cpp
> // aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
> // -offset - separating_margin -(aᵀ*p_AQ + b) if plane_side = kNegative
> [[nodiscard]] symbolic::RationalFunction ComputePointOnPlaneSideRational(
> ```

Could you explain the expected frames of the inputs to this function?
___
*[`geometry/optimization/dev/collision_geometry.cc` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbJ08P4FTQKINGJx1V:-NHbJ08P4FTQKINGJx1W:b-jdrlep) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L101)):*
> ```cpp
> void CollisionGeometry::ImplementGeometry(const Box& box, void* data) {
>   // For a polytope (including box) to be on one side of the separating plane,
>   // if we only require separation but don't explicitly compute the separating
> ```

Something is funky with the English in this documentation. I am also not sure how this documentation about delta aligns with the actual function involved.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbIt1T2K-QJCNNGIsF:-NHbIt1T2K-QJCNNGIsG:bz6w29m) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L138)):*
> ```cpp
> }
> 
> void CollisionGeometry::ImplementGeometry(const Convex& convex, void* data) {
> ```

This looks like a lot of copy and paste. Can we combine the `Convex` and the `Box` version of this method more elegantly
___
*[`geometry/optimization/dev/test/convex.mtl` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbJxy97coz5m7yOwII:-NHbJxy97coz5m7yOwIJ:bhdv5vt) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/test/convex.mtl#L1)):*
> ```
> newmtl ConvexMaterial
> ```

I am not sure what this is?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.h` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbGlBnDGsb1XY9hoWT:-NHbOwEy3WfRexQnfgC7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.h#L101)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Remove these comments for this PR perhaps?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbHoeT65r8CSvR-xjD:-NHbPFGx0bKzuQHTQWYB:b-q900ix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L66)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this would be easier to read if it were consistent with the order of the terms here and also on the expansion
</blockquote></details>

Sorry I don't get this comment, could you elaborate? What is "the order of the terms"?
___
*[`geometry/optimization/dev/collision_geometry.cc` line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbIJMe6VwYO7j3-waf:-NHbQ7KjE7QysUUzCqwO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L67)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you explain the expected frames of the inputs to this function?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbJ08P4FTQKINGJx1V:-NHbQY_47yMc9ERzI-kD:b-hav774) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L101)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Something is funky with the English in this documentation. I am also not sure how this documentation about delta aligns with the actual function involved.
</blockquote></details>

Done. I modified the documentation a little bit.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbIt1T2K-QJCNNGIsF:-NHbR_8HDUFeK0DBlqJS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L138)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This looks like a lot of copy and paste. Can we combine the `Convex` and the `Box` version of this method more elegantly
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/convex.mtl` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbJxy97coz5m7yOwII:-NHbRaGe73lnu2wpHMyM:b-su2z2g) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/test/convex.mtl#L1)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am not sure what this is?
</blockquote></details>

This just gives the name of this material to be "ConvexMaterial", it is used in `convex.obj`.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbHoeT65r8CSvR-xjD:-NHjWe8U7O61_E9tjSUj:bwyexms) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L66)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't get this comment, could you elaborate? What is "the order of the terms"?
</blockquote></details>

I mean change
``` 
// aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
// -offset - separating_margin -(aᵀ*p_AQ + b) if plane_side = kNegative
```
to
``` 
// aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
// -(aᵀ*p_AQ + b) - (offset + separating_margin)  if plane_side = kNegative
```

it makes it easier to compare the differences in the two expression.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NHbHoeT65r8CSvR-xjD:-NHk2Crd1o47hj2wpqw0:b-ieo89z) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6325711e41c2ea72e626751e3945b8e3bf3827/geometry/optimization/dev/collision_geometry.cc#L66)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I mean change
``` 
// aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
// -offset - separating_margin -(aᵀ*p_AQ + b) if plane_side = kNegative
```
to
``` 
// aᵀ*p_AQ + b - (offset + separating_margin) if plane_side = kPositive
// -(aᵀ*p_AQ + b) - (offset + separating_margin)  if plane_side = kNegative
```

it makes it easier to compare the differences in the two expression.
</blockquote></details>

Done. Thanks for the explanation.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358#-:-NI-MOw479QlgYINYR21:bg7igkv)* status: needs platform reviewer assigned, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for platform review on the "vpolytope.h/cc" file. The other files are in `dev` folder.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358#-:-NI-NUxfDFydqMCk6qVS:bcb9z8i)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
A few small tweaks on `vpolytope`, but, otherwise, :LGTM:.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358#-:-NI-QsG7E7fBook7ZThb:b-4qc62u)* status: 4 unresolved discussions (waiting on @hongkai-dai)

___
*[`geometry/optimization/vpolytope.h` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-PsGDBBJYhOAXuLzB:-NI-PsGDBBJYhOAXuLzC:b2yenzd) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.h#L120)):*
> ```objc
> 
> /** Obtain all the vertices stored in the convex object.
>  * @return vertices. Each column of `vertices` is a vertex. We don't impose any
> ```

nit: swap `@return` for `@retval`.  That's the macro to use if you're *naming* the return value as you have done here.
___
*[`geometry/optimization/vpolytope.h` line 121 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-Q-xo9xSzau6mQNHx:-NI-Q-xo9xSzau6mQNHy:b-bb3ai5) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.h#L121)):*
> ```objc
> /** Obtain all the vertices stored in the convex object.
>  * @return vertices. Each column of `vertices` is a vertex. We don't impose any
>  * specific order on the vertices. The vertices are expressed in the convex own
> ```

nit: convex __*shape's*__ own frame.
___
*[`geometry/optimization/vpolytope.cc` line 369 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-QKyi5OuHLJCJ_DfK:-NI-QKyi5OuHLJCJ_DfL:b8nxq8x) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.cc#L369)):*
> ```cpp
>   const Eigen::Matrix3Xd vertices = GetVertices(convex);
>   Matrix3Xd* vertices_data = static_cast<Matrix3Xd*>(data);
>   *vertices_data = vertices;
> ```

nit: It seems this forces an unwanted copy. Admittedly, this only happens at initialization, right? However, if you care, make `vertices` non-const and then `std::move` it into `*vertices_data` to avoid the copy. Alternatively:

```c++
Matrix3Xd* vertices_data = static_cast<Matrix3Xd*>(data);
*vertices_data = GetVertices(convex);
```

will do it too.
___
*[`geometry/optimization/vpolytope.cc` line 369 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-QjuDE4dZH7SWBe2Z:-NI-QjuEBObmvlMVzgd_:b64rqfm) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.cc#L369)):*
> ```cpp
>   const Eigen::Matrix3Xd vertices = GetVertices(convex);
>   Matrix3Xd* vertices_data = static_cast<Matrix3Xd*>(data);
>   *vertices_data = vertices;
> ```

BTW "vertex_data" would be a better name. It's the "data" word that takes care of "plural".

**Review by SeanCurtis-TRI — COMMENTED** [review]
(Note: I've ignored everything in the `dev` folder.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358#-:-NI-R21oCPlpVGjnIknp:bli6j4x)* status: 4 unresolved discussions (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18358)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),AlexandreAmice (waiting on @hongkai-dai)

___
*[`geometry/optimization/vpolytope.h` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-PsGDBBJYhOAXuLzB:-NI-TANz6iqNkR3-W_qR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.h#L120)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: swap `@return` for `@retval`.  That's the macro to use if you're *naming* the return value as you have done here.
</blockquote></details>

Done.
___
*[`geometry/optimization/vpolytope.h` line 121 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-Q-xo9xSzau6mQNHx:-NI-TBCk8zhHPAeeWXLb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.h#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: convex __*shape's*__ own frame.
</blockquote></details>

Done.
___
*[`geometry/optimization/vpolytope.cc` line 369 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-QKyi5OuHLJCJ_DfK:-NI-Tb468IWEBO3-kzIM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.cc#L369)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: It seems this forces an unwanted copy. Admittedly, this only happens at initialization, right? However, if you care, make `vertices` non-const and then `std::move` it into `*vertices_data` to avoid the copy. Alternatively:

```c++
Matrix3Xd* vertices_data = static_cast<Matrix3Xd*>(data);
*vertices_data = GetVertices(convex);
```

will do it too.
</blockquote></details>

Done.
___
*[`geometry/optimization/vpolytope.cc` line 369 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18358#-NI-QjuDE4dZH7SWBe2Z:-NI-Th3W5FBK1oQCcCFC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc41de73e9c96bc4de46e02be7fd2853d6db1ef7/geometry/optimization/vpolytope.cc#L369)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "vertex_data" would be a better name. It's the "data" word that takes care of "plural".
</blockquote></details>

Done.

**Pull request merged**
