### PR TITLE
[workspace] Withdraw stable API support for several externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These are the python- and models-only repositories that should not be public.
    
The models already have Drake-public filegroup wrappers where appropriate, in the `@drake//` namespace.

The python libraries are either for maintainer-only code (github3, uritemplate), or else brittle interior dependencies (clang) of Drake-private tools (mkdoc).

Relates to #17231 in the sense of a uniform stable / internal policy, even though there is no C/C++ code here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17324)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri what do you think about +(status: single reviewer ok)?

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri what do you think about +(status: single reviewer ok)?

**Review by rpoyner-tri — COMMENTED** [review]
single is fine. Still looking.

> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17324#-:-N3z3vTS4Wtmlp8T4Ojn:bhl9o0i)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17324#-N3z2GdG6mnjwofr8Jo8):*
grammar? missing words?



_Code quote:_
```
  The python libraries either for maintainer-only code (github3, template),
  or else brittle interior dependencies (clang) of private tools (mkdoc).
```

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: new_release.py

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17324#-:-N3z5OX26H4iYMUiK5wE:blga73y)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17324#-N3z5F4t5LO4kndGyBuH:-N3z5F4t5LO4kndGyBuI:b-yioqnj) (no related file):*
Similar to a previous PR, are there names in `tools/workspace/new_release.py` that need updating?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17324)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17324#-N3z5F4t5LO4kndGyBuH:-N3z6_DI4y-_QVZW2pDO:b-896fix) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Similar to a previous PR, are there names in `tools/workspace/new_release.py` that need updating?
</blockquote></details>

Done.

___

**Pull request merged**
