### PR TITLE
unit_inertia: Change ReExpress to use frame A instead of frame F

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For consistency with rotational_inertia and spatial_inertia

Follow-up to #14111

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14112)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Presently, see inconsistency here: (as of master @ c48083e6):
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_rotational_inertia.html#a08eb5284c5ec57a645aee167798a1f2c
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html#a87068d58ff4a71b1d3d9795e9fed4aa6
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_unit_inertia.html#ab8231314dc085af878e5ff89cd36b40a

**Review by EricCousineau-TRI — COMMENTED** [review]
+@amcastro-tri for feature review, please (I think this should be uber brief)
+@sammy-tri for platform review, please.

Didn't deprecate the Python API here b/c the PR landed today (2020-09-22).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14112#-:-MHsFe1o55nLq5osThSD:bzgtbll)* status: LGTM missing from assignees amcastro-tri,sammy-tri(platform) (waiting on @amcastro-tri and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
I've been waiting for feature review before doing mine..  If this happens to linger until tomorrow, I don't mind remaining assigned for platform.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14112#-:-MHwfccUEJ4ElWqG0B7a:b-qcdf2l)* status: LGTM missing from assignees sammy-tri(platform),amcastro-tri (waiting on @amcastro-tri and @sammy-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14112#-:-MI-dzK59qH9ywUNECzZ:bg7igkv)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14112#-:-MI-vqcL6uKOY2eq2FOo:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri

**Pull request merged**
