### PR TITLE
AddLorentzConeConstraint accept eval_type.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553#-:-MgCWKG2CVUtmVRf6Vnz:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  just need a few more docstrings, i think.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553#-:-MgKbvmy1p-gmQW_hkz8:b-8689w2)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1992 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgKbZEs5QgyfC9_x0To:-MgKbZEs5QgyfC9_x0Tp:bi0rngy) ([raw file](https://github.com/robotlocomotion/drake/blob/099c7e8ea1354413ef88d2e7dd4166ab72920c02/solvers/mathematical_program.h#L1992)):*
> ```objc
>       const Eigen::Ref<const Eigen::VectorXd>& b, const VariableRefList& vars,
>       LorentzConeConstraint::EvalType eval_type =
>           LorentzConeConstraint::EvalType::kConvexSmooth) {
> ```

I guess we should add the argument to the documentation for this and the other methods, too...

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553#-:-MgN1R9h7_dcQFlF8xoc:buxscyd)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[solvers/mathematical_program.h, line 1992 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgKbZEs5QgyfC9_x0To:-MgN1PiSEHYv-EMZ6yOE:b-h5g1tk) ([raw file](https://github.com/robotlocomotion/drake/blob/099c7e8ea1354413ef88d2e7dd4166ab72920c02/solvers/mathematical_program.h#L1992)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I guess we should add the argument to the documentation for this and the other methods, too...
</blockquote></details>

Done. Good call

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553#-:-MgNBCLuDF5p65txzciG:b-vtj4vo)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/constraint.h, line 322 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgN7dgS7AQe6opmaUDi:-MgN7dgT5M_9QhC00WWe:b-f3elgr) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2226168c967428dd36352c92b0b0c5777fd71c/solvers/constraint.h#L322)):*
> ```objc
>   LorentzConeConstraint(const Eigen::Ref<const Eigen::MatrixXd>& A,
>                         const Eigen::Ref<const Eigen::VectorXd>& b,
>                         EvalType eval_type = EvalType::kConvexSmooth);
> ```

FYI If the `eval_type` here were `optional<>` instead (and the default was thus buried in the cc file), then all of the places touched by this PR could avoid repeating the default value.  On the other hand, perhaps repeating the value at all of the call sites is more clear for users, so they don't have to chase through documentation indirection.  I am fine either way.
___
*[solvers/test/mathematical_program_test.cc, line 3429 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgNAh9C601J4w6SteDq:-MgNAh9C601J4w6SteDr:birpvo0) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2226168c967428dd36352c92b0b0c5777fd71c/solvers/test/mathematical_program_test.cc#L3429)):*
> ```cpp
>   auto lorentz_con = prog.AddLorentzConeConstraint(
>       x.cast<symbolic::Expression>(),
>       LorentzConeConstraint::EvalType::kConvexSmooth);
> ```

For the mathematical program API testing, all of the tests are just repeating the existing default.  We don't appear to have any new test that confirm that if we used a non-default value, that at least the `eval_type()` getter shows that the setting made it through to the underlying Constraint.

Would adding more tests be worthwhile, or is the code sufficiently correct by inspection?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @RussTedrake)

___
*[solvers/constraint.h, line 322 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgN7dgS7AQe6opmaUDi:-MgRb8Iv2voehxecONPD:b8fdbpn) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2226168c967428dd36352c92b0b0c5777fd71c/solvers/constraint.h#L322)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If the `eval_type` here were `optional<>` instead (and the default was thus buried in the cc file), then all of the places touched by this PR could avoid repeating the default value.  On the other hand, perhaps repeating the value at all of the call sites is more clear for users, so they don't have to chase through documentation indirection.  I am fine either way.
</blockquote></details>

Thanks for the suggestion. I would prefer to have the default value kConvexSmooth here to make it more obvious to the user.
___
*[solvers/test/mathematical_program_test.cc, line 3429 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15553#-MgNAh9C601J4w6SteDq:-MgRb5gL6bRGGOROtnQR:b-s0fbtl) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2226168c967428dd36352c92b0b0c5777fd71c/solvers/test/mathematical_program_test.cc#L3429)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For the mathematical program API testing, all of the tests are just repeating the existing default.  We don't appear to have any new test that confirm that if we used a non-default value, that at least the `eval_type()` getter shows that the setting made it through to the underlying Constraint.

Would adding more tests be worthwhile, or is the code sufficiently correct by inspection?
</blockquote></details>

Done. Good call. I added more tests.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15553)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
