### PR TITLE
add cmake option for long running tests.

### PR DESCRIPTION
**Pull request by RussTedrake**
addresses #2078 which also requires that the build logic turns this flag on for nightly builds

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2166)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Looks good (except for the one typo).

When LONG_RUNNING_TESTS goes into the nightly builds, we'll have to be sure the documentation for those builds explains to developers how to reproduce any errors shown there, but that doesn't need to be part of this PR.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/CMakeLists.txt, line 169 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-KGC_WpNfjogihas4uHr:-KGC_WpNfjogihas4uHs:855406748) ([raw file](https://github.com/robotlocomotion/drake/blob/17f8bfde99ad5738e9a58cfa0605df4606684565/drake/CMakeLists.txt#L169)):*
This says RANDOMIZED_, but above it is RANDOMIZE_.  Probably one of them is wrong.

Why does CMake let us get away with that?  Is there something like "use strict" that would prevent this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-:-KGCablRFuznT-IX0aAk:1177311477)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/CMakeLists.txt, line 169 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-KGC_WpNfjogihas4uHr:-KGCbdVRasIVyakmgU3C:419141161) ([raw file](https://github.com/robotlocomotion/drake/blob/17f8bfde99ad5738e9a58cfa0605df4606684565/drake/CMakeLists.txt#L169)):*
No. CMake does not know that there is not another target called RANDOMIZED_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166)*

**Comment by RussTedrake** [comment]
should be good to go.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/CMakeLists.txt, line 169 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-KGC_WpNfjogihas4uHr:-KGR18LFI4lE6w7cRf0N:1806316251) ([raw file](https://github.com/robotlocomotion/drake/blob/17f8bfde99ad5738e9a58cfa0605df4606684565/drake/CMakeLists.txt#L169)):*
good catch.  thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-:-KGR1B7Bt29OL8RnNuS6:1613778863)*

**Comment by liangfok** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-:-KGRbBy5YVzd1370JtPc:980077423)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-:-KGSB54TyT8PwvuRK2sV:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 169 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-KGC_WpNfjogihas4uHr:-KGSBAY2BqFSrnkv4zgO:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/17f8bfde99ad5738e9a58cfa0605df4606684565/drake/CMakeLists.txt#L169)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 169 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-KGC_WpNfjogihas4uHr:-KGSBJ2YMlgOjNtmT7XU:418140604) ([raw file](https://github.com/robotlocomotion/drake/blob/17f8bfde99ad5738e9a58cfa0605df4606684565/drake/CMakeLists.txt#L169)):*
@jwnimmer-tri, you marked this as blocking.  Are you satisfied with the fix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166#-:-KGSETxIG5Gccv1b3qZO:1417088721)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2166)*

**Pull request merged**
