### PR TITLE
Polynomial removes the term if is_zero(coeff) is true in that term.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611#-:-N7T3Qpo2DdfWuejL5Ox:bs3tquo)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7T3UMj8rgE-y9OEunA:-N7T3UMj8rgE-y9OEunB:brfthxi) ([raw file](https://github.com/robotlocomotion/drake/blob/76e7153daad568841b0ecdaf30dc8176c7201621/common/symbolic/polynomial.cc#L135)):*
> ```cpp
>     const double c = get_constant_in_multiplication(e);
>     if (c == 0) {
>       return Polynomial::MapType{};
> ```

This line is not tested because after calling Expand(), the coefficient `c` should not be 0. But I still add this check here since it is cheap to check and also could prevent potentially incorrect call to DecomposePolynomialVisitor without expanding the expression.
___
*[`common/symbolic/polynomial.cc` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7T3mhH7kBJkhCSs0RL:-N7T3mhH7kBJkhCSs0RM:bkcp75q) ([raw file](https://github.com/robotlocomotion/drake/blob/76e7153daad568841b0ecdaf30dc8176c7201621/common/symbolic/polynomial.cc#L151)):*
> ```cpp
>     }
>     if (symbolic::is_zero(coeff)) {
>       return Polynomial::MapType{};
> ```

Ditto, this line is not tested, but it is cheap to check. `is_zero(coeff)`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7T3UMj8rgE-y9OEunA:-N7T8J-f0XQYfGXWBVAI:b861sfk) ([raw file](https://github.com/robotlocomotion/drake/blob/76e7153daad568841b0ecdaf30dc8176c7201621/common/symbolic/polynomial.cc#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I agree with the premise of being careful.  But if the condition is impossible, then it should be written down as `DRAKE_DEMAND(c != 0);` instead of trying to correctly implement a response to an impossible condition, to make that clear to the reader and to avoid untestable code.
</blockquote></details>

I realize when calling `DoAddProduct` (at the end of this function), `DoAddProduct` actually handles the case when the product c_i * c_j equals to 0. So I can safely ignore this check here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7T3UMj8rgE-y9OEunA:-N7T9Ew75mYBdR_LYBpv:brdxycf) ([raw file](https://github.com/robotlocomotion/drake/blob/76e7153daad568841b0ecdaf30dc8176c7201621/common/symbolic/polynomial.cc#L135)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I realize when calling `DoAddProduct` (at the end of this function), `DoAddProduct` actually handles the case when the product c_i * c_j equals to 0. So I can safely ignore this check here.
</blockquote></details>

My previous comment was wrong. I added DRAKE_DEMAND here.

**Review by jwnimmer-tri — COMMENTED** [review]
FYI I checked the mathematical program benchmarks vs this PR.  It seems to be a statistically significant ~1% slowdown on the SOS 3 case.


```
Benchmark                      Time          CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------
BenchmarkSosProgram3_mean   +0.0082      +0.0082      582.8 ms      587.6 ms       582.7 ms      587.5 ms
BenchmarkSosProgram3_pvalue  0.0000       0.0000      U Test, Repetitions: 100 vs 100
```

However, I do think it's still worth that price, so :lgtm: feature.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611#-:-N7WP9EK5uBbFTTFWpaL:b-hx6hyi)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/polynomial.cc` line 407 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7TVIQz9CVA1UjaFke2:-N7TVIR-61WH27WDD_Np:b-pnh01p) ([raw file](https://github.com/robotlocomotion/drake/blob/94a868543e90bf5cf7378fa3345c0d28ca8e1c01/common/symbolic/polynomial.cc#L407)):*
> ```cpp
>       decision_variables_{GetDecisionVariables(monomial_to_coefficient_map_)} {
>   // No need to call CheckInvariant() because DecomposePolynomialVisitor is
>   // supposed to make sure the invariant holds as a post-condition.
> ```

Is this comment still accurate?

Even if it is, we only use the invariant checks in `DRAKE_ASSERT` mode anyway, so there is little reason to avoid doing the extra checks -- we don't care whether or not Debug code is fast.  To my taste, only when the condition is already blindingly obvious (like in the `Polynomial(Monomial)` constructor) should we skip the invariant checking.

What do you think about adding the check here?
___
*[`common/symbolic/test/polynomial_test.cc` line 207 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7WF3ba8FRGKuqm1qqp:-N7WF3ba8FRGKuqm1qqq:b9j3lng) ([raw file](https://github.com/robotlocomotion/drake/blob/94a868543e90bf5cf7378fa3345c0d28ca8e1c01/common/symbolic/test/polynomial_test.cc#L207)):*
> ```cpp
> TEST_F(SymbolicPolynomialTest, ConstructorFromExpressionAndIndeterminates3) {
>   // The expression has some coefficient being 0. Show that the constructed
>   // polynomial removed the 0-coefficient term.
> ```

nit Is it worth noting in the comment here that the `0 * x^2` => `0` and `x + 0y` => `x` simplifications happen in the Expression class, before it ever reaches the Polynomial class?

As an acceptance test, I can see the point of writing out some superfluous multiplies to mimic what real-life code might do.  As a unit test, it might be clearer to remove the fluff (i.e., just use `const symbolic:Expression e1{0};` as the input).

**Review by hongkai-dai — COMMENTED** [review]
I see, so that extra 1% is spent on the for loop at the constructor `Polynomial(const MapType& map)`, that it checks if any coefficient of the map is 0? That's good to know. I thought that this check should be super cheap. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611#-:-N7WkhCq7qf-4c3VimF-:bi8qvwm)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 407 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7TVIQz9CVA1UjaFke2:-N7Wj4TR6Xryi2uOhEmp:bywkilq) ([raw file](https://github.com/robotlocomotion/drake/blob/94a868543e90bf5cf7378fa3345c0d28ca8e1c01/common/symbolic/polynomial.cc#L407)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is this comment still accurate?

Even if it is, we only use the invariant checks in `DRAKE_ASSERT` mode anyway, so there is little reason to avoid doing the extra checks -- we don't care whether or not Debug code is fast.  To my taste, only when the condition is already blindingly obvious (like in the `Polynomial(Monomial)` constructor) should we skip the invariant checking.

What do you think about adding the check here?
</blockquote></details>

I see. I tried to make sure that `DecomposePolynomialVisitor` satisfy the invariant. But as you say it is good to use the invariant check in the dbug mode anyway.
___
*[`common/symbolic/test/polynomial_test.cc` line 207 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17611#-N7WF3ba8FRGKuqm1qqp:-N7WkKCDBvQgRIEARt99:bptzvsb) ([raw file](https://github.com/robotlocomotion/drake/blob/94a868543e90bf5cf7378fa3345c0d28ca8e1c01/common/symbolic/test/polynomial_test.cc#L207)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Is it worth noting in the comment here that the `0 * x^2` => `0` and `x + 0y` => `x` simplifications happen in the Expression class, before it ever reaches the Polynomial class?

As an acceptance test, I can see the point of writing out some superfluous multiplies to mimic what real-life code might do.  As a unit test, it might be clearer to remove the fluff (i.e., just use `const symbolic:Expression e1{0};` as the input).
</blockquote></details>

Right. I forgot that Expression already removes these 0-terms. I changed to use `e1{0}` and removed the test for `e2`.

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611#-:-N7Wl58eCPIOrUsepgvp:b-c9pjop)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> ... extra 1% is spent on the for loop ...

That was my guess, yes.

> I thought that this check should be super cheap.

After #17554, the `is_zero` itself will be super cheap.  The red-black map iteration will still be doing pointer-chasing, but in any case seems worthwhile.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17611#-:-N7Wmz6D3LfJ4Z2xe3Q4:b1a2x1i)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Pull request merged**
