### PR TITLE
[geometry] Relax AffineHullIntersection tolerance for MOSEK

### PR DESCRIPTION
**Pull request by svenevs**
Followup to #19864.

I don't have a way to run this test locally, using CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19915)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Review by ggould-tri — COMMENTED** [review]
+@ggould-tri :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19915#-:-NaqSgWeDDkAbDLJqq6W:b2k9fdi)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
something weird went on with the status checks here, closing and reopening to retrigger

**Pull request closed without merging**
