### PR TITLE
Enable specifying the world frame for a custom Drake joint.

### PR DESCRIPTION
**Pull request by amcastro-tri**
That is, I'd like to say  `<drake:parent>world</drake:parent>` within `<drake:joint>`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13859)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 993 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13859#-METO18n-QT_0dQrBzwM:-METO18n-QT_0dQrBzwN:b-97n04h) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcc9fff5595db0e65fd3aa553656da552ce4578/multibody/parsing/test/detail_sdf_parser_test.cc#L993)):*
> ```cpp
>   // Specifying the world frame with the "world" string.
>   {
>     auto [plant, scene_graph] = ParseTestString(R"(
> ```

nit This test file changed convention since you forked this case.  We now use `R"""(` for multi line literals.

https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

**Comment by jwnimmer-tri** [comment]
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 993 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13859#-METO18n-QT_0dQrBzwM:-METPQgO4CLs0F7t9pMV:btw2d0w) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcc9fff5595db0e65fd3aa553656da552ce4578/multibody/parsing/test/detail_sdf_parser_test.cc#L993)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thanks. This files uses the single quot everywhere. Will someone push a "fix all string literals PR"? should I change here this one single entry? would that fix cause headaches to that one someone fixing all entries with a regexp?
</blockquote></details>

I thought we'd already changed them all in #13811, but it looks like I missed several in here, sorry.  (Some of them _are_ triple already, though.)

Note that `R"(in <inertial/> or <model/> tags.)"` single line raw is fine -- only _multi line_ should use triple.

Anything you change here won't disrupt other work.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 748 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13859#-METydbk5PtXhiRCUgaq:-MEU6VaA662uu3A7G_jV:b-kiwscg) ([raw file](https://github.com/robotlocomotion/drake/blob/f8d60d3fc5cc7dabd51a0fc558a62f7e5fc6fdb8/multibody/parsing/test/detail_sdf_parser_test.cc#L748)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

interesting, isn't the linter supposed to tell me this? (or at least I do rely on it mistakenly)
</blockquote></details>

The cpplint checks use regexs; perhaps the >80 check doesn't know how to deal with raw string literals.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13859)* status: 3 unresolved discussions (waiting on @amcastro-tri, @EricCousineau-TRI, and @sherm1)

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri for platform review, to clear wasted pixels off of my dashboard.  Please add me back as reviewer once this PR is resurrected.

**Comment by jwnimmer-tri** [comment]
Thanks for your interest in contributing to Drake! Since this PR has not received any updates over the past 6+ months, we are closing it automatically. To resume the PR again, you may reopen it with updates (be sure to reopen before you push any changes), or open a new one.

**Pull request closed without merging**
