### PR TITLE
[hotfix] Circumvent a race condition when baking query objects

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Relates to #17720.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17721)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17721#-N9EFKUeAF_x84Umlhsc:-N9EFKUeAF_x84Umlhsd:b-ngvjci) (no related file):*
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please.

**Review by xuchenhan-tri — COMMENTED** [review]
+@seancurtis-tri +@ericcousineau-tri for reviews if not too late.

Ideally we can get this in before today's nightly.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17721#-:-N9EFN-JBf1sUJVxIuwP:b-ouc9fn)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

:LGTM:

Hopefully, it'll put out some of the fires.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17721#-:-N9HIvVx20kTxEsoAEq2:b-3ligly)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/test/multibody_plant_reaction_forces_test.cc` line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17721#-N9HFg2ACeSq_qST5gWK:-N9HFg2ACeSq_qST5gWL:blsfhp8) ([raw file](https://github.com/robotlocomotion/drake/blob/afc8e2da36425082247e5dcab227572c9add2d6e/multibody/plant/test/multibody_plant_reaction_forces_test.cc#L326)):*
> ```cpp
>     std::vector<geometry::internal::DeformableRigidContact<double>>
>         deformable_rigid_contact;
>     query_object.ComputeDeformableRigidContact(&deformable_rigid_contact);
> ```

BTW The more obvious, alternate solution is to create a vector of `Context*` *outside* in the main thread by cloning it serially. And then just having the ith thread pick up the ith clone.  But I'm letting this through as is.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@ericcousineau-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17721#-:-N9HJ2_UDayQ8Pe5aCtZ:b-vhpoeh)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
