### PR TITLE
Revert 2171 feature/urdf world link

### PR DESCRIPTION
**Pull request by liangfok**
I am creating this pull request in an attempt to replicate the continuous build error shown here: 

https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-continuous-debug/197/

I am not sure if this is the correct procedure for doing this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2491)

### CODE REVIEW

**Comment by jonathan-owens** [comment]
@drake-jenkins-bot test this please

**Comment by liangfok** [comment]
I suspect Jenkins is running the pre-submit test suite. Is there a way to run the post-submit test suite on this PR without merging into master?

**Comment by jonathan-owens** [comment]
Hmm. Good question. There used to be a "build with parameters" option in there somewhere where you could point to the appropriate git hash, but I can't seem to find it. @jamiesnape any idea?

**Comment by liangfok** [comment]
Just a quick note that this PR passed the following two CI tests, though I suspect they are the pre-submit test suite:

* https://drake-jenkins.csail.mit.edu/job/experimental/1883/
* https://drake-jenkins.csail.mit.edu/job/experimental/1882/

I just received instructions from @david-german-tri on how to run a post-submit CI test and will next attempt to run that on this PR.

**Comment by jamiesnape** [comment]
Go to the [windows-msvc-32-experimental](https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-experimental/) job, check the `debug` checkbox, and enter `pr/2491` as the `sha1` parameter.

**Comment by liangfok** [comment]
Thanks. I believe I've triggered a post-submit 32-bit Windows test here: https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental/55/

**Comment by jamiesnape** [comment]
You did, yes.

**Comment by liangfok** [comment]
To verify that [windows-msvc-32-experimental/55](https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental/55/) is in fact a post-submit build, I opened the [full console log output](https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental/55/consoleFull), searched for "CTEST_CONFIGURATION_TYPE", and verified that it is assigned a value of "Debug". In pre-submit CI tests, this variable is assigned a value of "Release".

On another note, it appears that this PR [passed the post-submit build](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-windows-msvc-32-experimental-55&field2=buildstarttime&compare2=84&value2=now) and is thus ready for review / merge.

**Comment by jwnimmer-tri** [comment]
Yes, I will review.  I've pulled the two PR's diffs will and review their comparison -- there are some real changes between the two PRs (maybe just new merge edits?), but seems to be less than a dozen small edits.

I  am disturbed that it "just started working" but for now I will just review the code, and then consider the broader picture.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri, since this PR is a rehash of https://github.com/RobotLocomotion/drake/pull/2171, which was reverted in https://github.com/RobotLocomotion/drake/pull/2438, can you do both the feature and platform reviews?
> 
> Note that I was unable to replicate the problem either locally or on the build servers and thus didn't change any code relative to https://github.com/RobotLocomotion/drake/pull/2171.
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJBZt84U31lHbtKuNek:-1088585407)*

**Comment by jwnimmer-tri** [comment]
Reviewed 24 of 24 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 317 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBebZWbkuXtsULJNWB:-KJBebZWbkuXtsULJNWC:-672856429) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L317)):*
> ```cpp
> 
>   body->name_ = attr;
>   if (body->name_ == std::string(RigidBodyTree::kWorldLinkName)) return false;
> ```

The original PR added the comment `// World links are handled by parseWorldJoint()` here.  Was that intentionally removed from the new PR?

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 401 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBdc4Zj2PO8zVx1LvB:-KJBdc4_nWwQCOHmH-Zf:1516511835) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L401)):*
> ```cpp
>   if (!attr)
>     throw runtime_error("ERROR: joint " + name +
>                         "'s' parent does not have a link attribute!");
> ```

The second `'` seems superfluous.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 617 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBcYrTijxNrCs3nwBG:-KJBcYrTijxNrCs3nwBH:-695366062) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L617)):*
> ```cpp
>                         child_name);
> 
>     if (parent_name == "world") {
> ```

Why not use RBT::kWorldLinkName?

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 637 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBaFx7La_8zDwJ-6s-:-KJBaFx7La_8zDwJ-6s0:1103835925) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L637)):*
> ```cpp
>       if (weld_to_frame == nullptr) weld_to_frame.reset(new RigidBodyFrame());
> 
>       weld_to_frame->name = "world";
> ```

Why not use RBT::kWorldLinkName?   The original PR used it here, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491)*

**Comment by liangfok** [comment]
I did a compare of the head of this PR with SHA 36e1b8ce0be0e087b54057414ed013006e8d83ca and, you're right, there were some differences in `RigidBodyTreeURDF.cpp`. I see that the changes you've identified are these differences. I've updated this PR to eliminate these differences. Thanks for catching them!

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Yes, I will review.  I've pulled the two PR's diffs will and review their comparison -- there are some real changes between the two PRs (maybe just new merge edits?), but seems to be less than a dozen small edits.
> 
> I  am disturbed that it "just started working" but for now I will just review the code, and then consider the broader picture.
</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 317 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBebZWbkuXtsULJNWB:-KJBim3D-gSlKpFaHh-t:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L317)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The original PR added the comment `// World links are handled by parseWorldJoint()` here.  Was that intentionally removed from the new PR?
</details>
Fixed.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 401 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBdc4Zj2PO8zVx1LvB:-KJBj3YxVY4xxLglGhBr:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L401)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The second `'` seems superfluous.
</details>
Fixed.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 617 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBcYrTijxNrCs3nwBG:-KJBj5Js3sX7BEebDwZ_:-497468049) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L617)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Why not use RBT::kWorldLinkName?
</details>
Fixed

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 637 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-KJBaFx7La_8zDwJ-6s-:-KJBjHGQtMdS66pDIyND:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/e9e2933b55cb253a4860a3a52d399927173b85d7/drake/systems/plants/RigidBodyTreeURDF.cpp#L637)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Why not use RBT::kWorldLinkName?   The original PR used it here, I think.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJBiE95jlMJPjQxW5Kv:-208394248)*

**Comment by jwnimmer-tri** [comment]
I'm not seeing a new push yet.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I did a compare of the head of this PR with SHA 36e1b8ce0be0e087b54057414ed013006e8d83ca and, you're right, there were some differences in `RigidBodyTreeURDF.cpp`. I see that the changes you've identified are these differences. I've updated this PR to eliminate these differences. Thanks for catching them!
</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJBso0oUKyGVMyoFsZt:-526338593)*

**Comment by liangfok** [comment]
Sorry, I pushed to the wrong remote. Now it should appear. PTAL.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I'm not seeing a new push yet.
</details>


---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJC6TomuFLPxAMO4_hG:1073366171)*

**Comment by jwnimmer-tri** [comment]
Okay the code looks good now.   I guess I'll :lgtm: and take a "wait and see" for breaking Continuous or not (since the need for the original revert is not yet understood), rather than trying to figure it out now pre-submit.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Sorry, I pushed to the wrong remote. Now it should appear. PTAL.
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJC6doUpYuLfddNC-z7:-1868642858)*

**Comment by liangfok** [comment]
SGTM.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Okay the code looks good now.   I guess I'll :lgtm: and take a "wait and see" for breaking Continuous or not (since the need for the original revert is not yet understood), rather than trying to figure it out now pre-submit.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2491#-:-KJCFMsi89VIVFO7HDBc:-486510564)*

**Comment by jwnimmer-tri** [comment]
@liangfok I'm thinking wait to merge this until Continuous goes green (blue) first -- a few hours.  If you need it sooner though, just ping me.

**Comment by liangfok** [comment]
No worries! I can wait.

**Comment by jwnimmer-tri** [comment]
Continuous is blue (enough).  Fine to merge this one now.

Using override-merge due to out-of-date-with-master.

**Comment by jwnimmer-tri** [comment]
> Thanks. I believe I've triggered a post-submit 32-bit Windows test here: https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental/55/

The presence of warning C4316 in that build log indicates that the underlying problem from the earlier revert was still there, but I suppose we just lucked out on the heap allocation being aligned by luck, whereas in the Continuous builder of master now, we are losing the dice-roll and hitting the alignment assertion.

I suspect that C4316 should be promoted to an error within drake (not in the superbuild though; there appear to be false positives in bullet there).  I will file an issue to that effect.

**Pull request merged**
