### PR TITLE
[workspace] Refactor python rule for maintainability

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21844.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21999)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21999#-:-O8brFe3BZzoBaKtjNOe:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/python/repository.bzl` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21999#-O8bn_9N4cP-P1cCvXLD:-O8bn_9O1BGchC77ip58:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/533ab487587d3241a9232f38ac27d28e3b8bc800/tools/workspace/python/repository.bzl#L30)):*
> ```Starlark
> 
> def _get_python_interpreter(repo_ctx):
>     """Returns the tuple (python_interprer_path, major_minor_version) based on
> ```

typo



_Suggestion:_
```Starlark
interpreter
```
___
*[`tools/workspace/python/repository.bzl` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21999#-O8bnqQJ7kGSc2xpUusq:-O8bnqQJ7kGSc2xpUusr:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/533ab487587d3241a9232f38ac27d28e3b8bc800/tools/workspace/python/repository.bzl#L66)):*
> ```Starlark
>     ).stdout.strip()
> 
> # TODO(jwnimmer-ti): Much of the logic for parsing includes and linkopts is the
> ```

typo



_Suggestion:_
```Starlark
jwnimmer-tri)
```

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21999#-:-O8cotCcBUBLzF0kftnd:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
See anzu#14265.

**Comment by SeanCurtis-TRI** [comment]
Marvelous. That unlocks building anzu against Drake PRs again. Thanks.

**Pull request merged**
