### PR TITLE
Move drake/systems/framework/primitives to drake/systems/primitives.

### LINKED ISSUE #4462: Move systems/framework/primitives to systems/primitives
I recall @RussTedrake suggesting this in the hallway.  Is that correct?

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4462.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4476)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm:

Be sure to opt-in to Bazel builds before merging, also.

---

Reviewed 140 of 170 files at r1, 30 of 30 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/primitives/CMakeLists.txt, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-KYomz_pnBoK7xlo_2D6:-KYomz_pnBoK7xlo_2D7:b-atdwm3) ([raw file](https://github.com/robotlocomotion/drake/blob/4a7fd30b642a87b17447ce795021b9f67b8ca79b/drake/systems/primitives/CMakeLists.txt#L55)):*
> ```CMake
>     REQUIRES
>     drake-common
>     drake-system-primitives
> ```

This seems wrong.

---

*[drake/systems/primitives/test/BUILD, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-KYonLpnsEjVSrRZ4i5L:-KYonLporMu-OwbsxLu4:b-c1elcl) ([raw file](https://github.com/robotlocomotion/drake/blob/4a7fd30b642a87b17447ce795021b9f67b8ca79b/drake/systems/primitives/test/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

BTW I'm surprised this file still exists.  Did I miss it in my bazel-tests-location rework?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-:-KYon_ZKWp3gWQ9MY1cp:b-2q2rma)*

**Comment by jwnimmer-tri** [comment]
Given the conflicts, it looks like this was branched pre-#4459; it will need a merge / rebase.

**Comment by david-german-tri** [comment]
Done.

---

Reviewed 25 of 170 files at r1.
Review status: 107 of 112 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-:-KYsngRLE1RriezN5EzT:b-896fix)*

**Comment by david-german-tri** [comment]
Review status: 107 of 112 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/CMakeLists.txt, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-KYomz_pnBoK7xlo_2D6:-KYsnr6GLiUUjdfWV4Wa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a7fd30b642a87b17447ce795021b9f67b8ca79b/drake/systems/primitives/CMakeLists.txt#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems wrong.
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/BUILD, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4476#-KYonLpnsEjVSrRZ4i5L:-KYsntaLI0Yzrh0v45Ez:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a7fd30b642a87b17447ce795021b9f67b8ca79b/drake/systems/primitives/test/BUILD#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I'm surprised this file still exists.  Did I miss it in my bazel-tests-location rework?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4476)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 170 files at r1, 6 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4476)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 170 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4476)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
