### PR TITLE
Added a --without-asking flag which installs with apt-get install -y

### PR DESCRIPTION
**Pull request by odellus**
I wanted to avoid having to sit there and babysit the script as it installs the dependencies.

Love to hear feedback on this idea.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15819)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Good day, @odellus. I’m assigning +@BetsyMcPhail  as the most relevant team member to assist with this pull request. If you already had a different team member in mind, please let us know. To @BetsyMcPhail, feel free to delegate in case there is someone else more suitable.

**Comment by odellus** [comment]
Sounds good. Thank you!

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot ok to test

**Comment by jwnimmer-tri** [comment]
> Love to hear feedback on this idea.

Is the use case for direct personal use, or more for like a CI scripting environment?

For personal use, have you tried `yes | sudo install_prereqs.sh`?  That is our usual advice for accepting the prompts on the command-line automatically.  Works for more than just this one case.

In a scripted CI environment, turning off apt prompts system-wide is even better:

> echo 'APT::Get::Assume-Yes "true";' | sudo tee /etc/apt/apt.conf.d/90yes
> echo "debconf debconf/frontend select Noninteractive" | sudo debconf-set-selections

**Comment by odellus** [comment]
First I've heard of either of those options. Neat! I put it in there for
personal use, but I work with CI systems and docker a lot so the -y flag
has sort of become default for me.

**Comment by jwnimmer-tri** [comment]
That actually is an interesting idea -- what do you think about naming this switch just `-y` instead of `--without-asking`?  That would possibly be what other users might try out of the box.  I know that it doesn't match in style with some of the other options here, but perhaps sticking with tradition outweighs uniformity?

**Comment by odellus** [comment]
I like it.

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15819)* status: 2 unresolved discussions, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail and @odellus)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15819)* status: LGTM missing from assignees jwnimmer-tri(platform),BetsyMcPhail, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @odellus)

___
*[setup/ubuntu/binary_distribution/install_prereqs.sh, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15819#-MkqscDy9pPKFkqPL0ow:-Mksf2kzD7zL5-o7dl9X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c278947d669052d4a83c0b4ead68bef78ee3c6b/setup/ubuntu/binary_distribution/install_prereqs.sh#L17)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit: Add a comment similar to others above to explain this option
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15819#-MkqvHy_0YKOufQOv5Zn:-Mksf3Q_1ThniDPBrp3A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c278947d669052d4a83c0b4ead68bef78ee3c6b/setup/ubuntu/source_distribution/install_prereqs.sh#L47)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit: Add a comment similar to others above to explain this option
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

I'll plan to squash-merge this once Jenkins is all green.

**Comment by jwnimmer-tri** [comment]
Thanks @odellus!

**Comment by odellus** [comment]
🙇🏻‍♂️

**Pull request merged**
