### PR TITLE
Add degenerate examples to SDP test.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Include psd constraints on 1x1 or 2x2 matrices.

Towards #21663

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OAf-I5T5fQpT7UJgCOq:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OB1MCyFDS0QlI5AneZV:bg7igkv)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/csdp_solver_test.cc` line 81 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB17iOpEiYOmMABUCAi:-OB17iOq077l7SqAx51G:b-sj23ez) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/csdp_solver_test.cc#L81)):*
> ```cpp
>   }
> }
> ```

missing `TestTrivial1x1SDP`
___
*[`solvers/test/degenerate_semidefinite_program_examples.h` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB17zmA4Lza0C6n2VxT:-OB17zmA4Lza0C6n2VxU:bb9g0om) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.h#L5)):*
> ```objc
>  * 2x2 matrices, which can be formulated as a bounding box constraint on the
>  * scalar, or the second order cone constraints.
>  */
> ```

I don't like the name `degenerate` for this file. How about `trivial_dimension_sdp` or `low_dimension_isomorphic_sdp`? I don't love either name so feel free to change it to something else.


 If X is the optimal solution of and SDP and has rank r, then the SDP is called primal degenerate if the tangent space of the rank r matrices plus the nullspace of the constraints is not full rank. A primal-dual pair (X, S) is degenerate when they are complementary but not strictly complementary (i.e. their ranks don't add up to `n`) See "Complementarity and nondegeneracy in semidefinite programming" by Alizadeh.



_Code quote:_
```objc
/**
 * Includes Semidefinite programs, but some of the PSD constraints are on 1x1 or
 * 2x2 matrices, which can be formulated as a bounding box constraint on the
 * scalar, or the second order cone constraints.
 */
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.h` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1Bj1O8TV_AGWyqQvw:-OB1Bj1O8TV_AGWyqQvx:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.h#L32)):*
> ```objc
>                        bool check_dual = true);
> 
> // A semidefinite program with both 1x1 psd matrix and 3x3 psd matrix
> ```

nit: grammar



_Suggestion:_
```objc
// A semidefinite program with both a 1x1 psd matrix and a 3x3 psd matrix
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.h` line 44 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1GdW87U4Wt7aknGNe:-OB1GdW87U4Wt7aknGNf:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.h#L44)):*
> ```objc
>                        bool check_dual = true);
> 
> // A semidefinite program with both 2x2 psd matrix and 3x3 psd matrix
> ```

nit: grammar



_Suggestion:_
```objc
/ A semidefinite program with both a 2x2 psd matrix and 3x3 psd matrix
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1LmSz2jDlCKOFX2U3:-OB1LmSz2jDlCKOFX2U4:b-ho2wnd) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L13)):*
> ```cpp
> namespace test {
> void TestTrivial1x1SDP(const SolverInterface& solver, double tol,
>                        bool check_dual) {
> ```

Throughout should we use a different tolerance for checking primal variables and the dual result? In the test files, it feels like we need to set the tolerance very low mostly due to checking the dual solution for accuracy. I would expect that many of the primal tolerances are much better than e.g. `1e-2` for the last example



_Code quote:_
```cpp
void TestTrivial1x1SDP(const SolverInterface& solver, double tol,
                       bool check_dual) {
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1HN1sD5o0Fw7cbCaj:-OB1HN1sD5o0Fw7cbCak:b4fc0gc) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L70)):*
> ```cpp
>   // clang-format on
>   const auto psd_con = prog.AddPositiveSemidefiniteConstraint(psd_mat);
>   prog.AddBoundingBoxConstraint(9, 9, x(0));
> ```

BTW: out of curiousity why do you use bounding box constraints rather than linear equality constraints?



_Code quote:_
```cpp
prog.AddBoundingBoxConstraint(9, 9, x(0));
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1K4nI8nntbSWQMBmU:-OB1K4nI8nntbSWQMBmV:b8bqqdz) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L93)):*
> ```cpp
>     const auto x_sol = result.GetSolution(x);
>     // The dual problem is
>     // max 9*y(0) + y(1)+4*y(2)
> ```

nit: whitespace



_Suggestion:_
```cpp
// max 9*y(0) + y(1) + 4*y(2)
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 106 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1KqOg-9_3o8Yppy9A:-OB1KqOg-9_3o8Yppy9B:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L106)):*
> ```cpp
>     EXPECT_NEAR(-9 * psd_dual(0, 0) - psd_dual(1, 1) - 4 * psd_dual(2, 2),
>                 result.get_optimal_cost(), tol);
>     // Check complementarity slackness.
> ```

nit: grammar



_Suggestion:_
```cpp
// Check complementary slackness.
```
___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1LAqeEfiSq8ynG-L3:-OB1LAqeEfiSq8ynG-L4:b-huq5c4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L135)):*
> ```cpp
>   prog.AddBoundingBoxConstraint(1, 1, x(3));
>   MathematicalProgramResult result;
>   solver.Solve(prog, std::nullopt, std::nullopt, &result);
> ```

btw: throughout why not use?



_Suggestion:_
```cpp
auto result = solver.Solve(prog, std::nullopt, std::nullopt, &result);
```

**Review by AlexandreAmice — COMMENTED** [review]
The primal tolerances still feel very high to me. The default tolerance for satisfying the linear constraints should be on the order of `1e-8`. But I suppose there's not too much that can be done if the solvers aren't willing to behave.

> Reviewed 5 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OB2_03c4cUSyX79qrpG:b2pfigr)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/degenerate_semidefinite_program_examples.cc` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-OB1HN1sD5o0Fw7cbCaj:-OB2_Z_NCFHooKToHtqq:b-8qnq39) ([raw file](https://github.com/RobotLocomotion/drake/blob/c100ff0d2fddb2d762ee8faa0f3d8dddbb6e3bdd/solvers/test/degenerate_semidefinite_program_examples.cc#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure if I understand what you mean. Do you mean to impose the x(0)=9 constraint as a linear equality constraint? They both can work, but I typically find that the solver can violate the linear constraint by a small epsilon, but don't violate the bounding box constraint
</blockquote></details>

Yes that was my question. That is good to know about the bounding box constraints.

**Review by hongkai-dai — COMMENTED** [review]
I hope that later when we handle these small-size PSD matrices with bounding box or rotated Lorentz cone constraint, I can improve the tolerance. But for the moment there is not much I can do.

+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OB2aSQS1IZ5t60kvoFa:b-ovrk08)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Nice! Platform :lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OB3-JMV6Ph65lmudBMI:b-8w251k)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
@AlexandreAmice you have one blocking comment to remove before this can merge

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114#-:-OB3-UT-2ntq0jP8IebW:b-n3vwhp)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22114)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),AlexandreAmice

**Pull request merged**
