### PR TITLE
[parsing] Fix race conditions in the downloader

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #18948.

Towards #15774 and #9498.

(This program wasn't used yet (outside of a little unit testing), so it's non-notable.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri could I interest you in feature review?

**Comment by jwnimmer-tri** [comment]
*[`multibody/parsing/package_downloader.py` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQfWeKPCeoa4JUVekbT:-NQfWeKPCeoa4JUVekbU:bg21pyk) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f48feb8ea4ed376667c9b0c3853c9effe80d55/multibody/parsing/package_downloader.py#L137)):*
> ```Python
>     finally:
>         try:
>             shutil.rmtree(output_dir_temp)
> ```

Hmm.  I can see now that I should have used `with tempfile.TemporaryDirectory` to own the `output_dir_temp`, to use the simpler auto-cleanup of the context manager, instead of my own try-finally.  I'll refactor it that way shortly.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/parsing/package_downloader.py` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQfWeKPCeoa4JUVekbT:-NQfYrFB2xf2Vr2cV_SJ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f48feb8ea4ed376667c9b0c3853c9effe80d55/multibody/parsing/package_downloader.py#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  I can see now that I should have used `with tempfile.TemporaryDirectory` to own the `output_dir_temp`, to use the simpler auto-cleanup of the context manager, instead of my own try-finally.  I'll refactor it that way shortly.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. The big picture is clear to me, but I was tripped on a few details. PTAL, thanks.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-:-NQgm8d47KSW-6bFT5MP:b-62q2yb)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`multibody/parsing/package_downloader.py` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQfWeKPCeoa4JUVekbT:-NQgjRme-25Bi9cvdsDu:bknupct) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f48feb8ea4ed376667c9b0c3853c9effe80d55/multibody/parsing/package_downloader.py#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand how we recover to a valid state if we ever get to this assertion. 

IIUC, if an exception occurs during `move_destination.rename(output_dir)`, then the rename doesn't happen and the downloaded content is still in that temp dir? How do we recover from that?
___
*[`multibody/parsing/package_downloader.py` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgeGHb513en2Nqucq9:-NQgeGHb513en2NqucqA:b-6irj4q) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/package_downloader.py#L73)):*
> ```Python
>         for url in urls:
>             f.write(f" {url}\n")
>     temp.chmod(0o644)
> ```

This is cryptic to me. Could you explain?
___
*[`multibody/parsing/package_downloader.py` line 135 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgl0Nb58BNfpYI39bD:-NQgl0Nb58BNfpYI39bE:blsw242) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/package_downloader.py#L135)):*
> ```Python
> 
>     # All done.
>     assert output_dir.is_dir()
> ```

What does this assert achieve? Isn't this the directory passed in by the caller?
___
*[`multibody/parsing/test/package_downloader_stress_test.py` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgiUDn8Cf0XWhAVObJ:-NQgiUDn8Cf0XWhAVObK:b-bh06e1) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/test/package_downloader_stress_test.py#L52)):*
> ```Python
>             # Launch child processes until we are running at max parallelism.
>             while (len(children) + 1 < cpus) and (launch_count < N):
>                 children.append(subprocess.Popen([
> ```

Are we guaranteed here that there are more than one process running at the same time? If the downloader finishes fast enough, could this still be serial?

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-:-NQgvh748sVzLBozL4t5:bbnvyd5)* status: 4 unresolved discussions, LGTM missing from assignees xuchenhan-tri(platform),SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[`multibody/parsing/package_downloader.py` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQfWeKPCeoa4JUVekbT:-NQguv6oAaKbL3UGF9Ys:bno152w) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f48feb8ea4ed376667c9b0c3853c9effe80d55/multibody/parsing/package_downloader.py#L137)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't understand how we recover to a valid state if we ever get to this assertion. 

IIUC, if an exception occurs during `move_destination.rename(output_dir)`, then the rename doesn't happen and the downloaded content is still in that temp dir? How do we recover from that?
</blockquote></details>

Hopefully the new comments help?
___
*[`multibody/parsing/package_downloader.py` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgeGHb513en2Nqucq9:-NQgvNdF948SI25cjt1Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/package_downloader.py#L73)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is cryptic to me. Could you explain?
</blockquote></details>

Done.
___
*[`multibody/parsing/package_downloader.py` line 135 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgl0Nb58BNfpYI39bD:-NQguBOY-a7mVysK4q_Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/package_downloader.py#L135)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What does this assert achieve? Isn't this the directory passed in by the caller?
</blockquote></details>

Done.
___
*[`multibody/parsing/test/package_downloader_stress_test.py` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQgiUDn8Cf0XWhAVObJ:-NQgvgYHArVxSxqCXKni:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf320c5ce5340cf0761c20618db823e3737b2652/multibody/parsing/test/package_downloader_stress_test.py#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Are we guaranteed here that there are more than one process running at the same time? If the downloader finishes fast enough, could this still be serial?
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-:-NQgwxCt-gu_PlTO4Q8e:bg7igkv)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`multibody/parsing/package_downloader.py` line 137 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQfWeKPCeoa4JUVekbT:-NQgwfRO5khn9awGdW1P:b7six7g) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f48feb8ea4ed376667c9b0c3853c9effe80d55/multibody/parsing/package_downloader.py#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hopefully the new comments help?
</blockquote></details>

Ah I see, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[`multibody/parsing/package_downloader.py` line 12 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQzQ5H96hpLD9dDrFud:-NQziJmB64xFJLQJoINC:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/12d5d0c053d0233a08f4e337e7831402b79a7354/multibody/parsing/package_downloader.py#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW While this sentence is strictly true, it has some misleading implications. I expect the common inference would be to interpret this sentence as "no op" (or at least a reasonable approximation thereof). In reality:

1. The readme will definitely be overwritten/created.
2. The download logic (network activity, sha computation, and extraction) will be engaged. So, it's a lot of work to not change the contents of the `output_dir`.
3. The "silent exit" presumes success in the discarded download logic. If, for whatever reason, the download logic fails, we'll get an error logged.
</blockquote></details>

Done
___
*[`multibody/parsing/package_downloader.py` line 74 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQzNin5DxPg-W6P0pAT:-NQzjbWN6MKzidZ6jd6d:b-3st36u) ([raw file](https://github.com/RobotLocomotion/drake/blob/12d5d0c053d0233a08f4e337e7831402b79a7354/multibody/parsing/package_downloader.py#L74)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW What are the odds of two different attempts to download `foo` with different sets of urls (or in alternate ordering)? That would be the only case where a race condition on the creation of this file would be meaningfully apparent. (Also, I'm kind of surprised that the renaming isn't deferred until the successful download/extraction).
</blockquote></details>

It's not _supposed_ to happen, but I think you're right that we need to defend ourselves against confused users who call PackageMap with bogus arguments.
___
*[`multibody/parsing/package_downloader.py` line 118 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQzR59z-P1DsUJlQB9v:-NQziWTL7MXgSRi_VmlP:bw70yzr) ([raw file](https://github.com/RobotLocomotion/drake/blob/12d5d0c053d0233a08f4e337e7831402b79a7354/multibody/parsing/package_downloader.py#L118)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Might be worth noting that the choice has been made to blindly move (instead of testing to see if our original temp directory was already on the common filesystem) as producing simpler code with no appreciable performance impact.

Otherwise, I fear that future readers of this code will think, "Why the additional move if we've already satisfied the condition?"
</blockquote></details>

In general, it's impossible to query whether two paths are on the same filesystem.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/package_downloader.py` line 118 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19010#-NQzR59z-P1DsUJlQB9v:-NQzqXkD7GQ1wwW2u2HF:b-qc8bck) ([raw file](https://github.com/RobotLocomotion/drake/blob/12d5d0c053d0233a08f4e337e7831402b79a7354/multibody/parsing/package_downloader.py#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In general, it's impossible to query whether two paths are on the same filesystem.
</blockquote></details>

I hadn't been aware of that. That *particular* insight might be helpful so future readers don't waste their time thinking otherwise. How about:

```py
    # Now comes the really tricky part. Moving a directory is atomic but only
    # on the same filesystem (generally untestable)! Explicitly moving it from
    # the temporary directory into the output directory (under a temporary
    # name), satisfies the requirement for an atomic rename to the real name.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19010)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
