### PR TITLE
[tools] Consolidate rules_cc to a single point of control

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Never use the implicit `native.cc_library`, `native.cc_binary`, etc. We want to have a single point of control where we can pin a version of `@rules_cc`, or insert project-wide build flags.

Undo the mysticism around loading from `@drake//foo` vs just `//foo`. Several years ago this made a subtle difference (#6736), but it no longer does.

Towards #20217 (in prep for controlling `features = ['pic']`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I'm hoping one of @rpoyner-tri or @EricCousineau-TRI or @xuchenhan-tri are interested in signing up for all review here.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri here we go.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230#-:-NesvedL5ibn__sT8jQo:b-er642t)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 377 of 377 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20230#-Net1m_l8rP_KMEhRm7t:-Net1m_l8rP_KMEhRm7u:b-d5fwpw) (no related file):*
Ok, first pass done.

I think I've understood the changes you *have* made, now I'm trying to understand some of the changes you apparently *haven't* made, and work out the invariants. Here's what I have so far:

1. Inside-drake BUILD and bazel files don't need to load() inside-drake files via `@drake//` any more.
2. `package*.BUILD.bazel` files are building some external package on drake's behalf, so are effectively outside drake, and still need to say `@drake//`, as do any loaded rules files that they use.
3. There are assorted other uses of `@drake//` (configuration, dependencies, etc.) that are not relevant to the current project.
4. Nobody should be saying `native.cc*`, except the new point-of-control file.
5. Users of undecorated `cc_library` or similar need to add a load statement for the new point-of-control file.

One example that looks out-of-spec is `expat/repository.bzl`. I think it obeys 1-4 above, but not 5. Similar is `mosek/repository.bzl`.

I haven't located or experimented with all of the possible corner cases. What are your thoughts on invariants (and possibly even linting)?

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: with big invariant/consistency question

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230#-:-Net7RXHEkZ8jnUMiUVM:bp51h6w)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20230#-Net1m_l8rP_KMEhRm7t:-NetFv-28--2JhXPIvXj:bmjrs8u) (no related file):*
> (1..3)

The short version would be that the only places we write out a literal `"@drake//etc"` are:
* In a `package.BUILD.bazel` file (or its equivalent); in this case, the root workspace `//` refers to the external, not Drake, so when we need to cite Drake we need the `@drake` qualifier.
* In a `*.bzl` file, when writing down a label (e.g., as a `deps = ...`).  Labels in macros are interpreted relative to the package that _called_ the macro, not the package that _defined_ the macro.  (For example, this is why `//tools/lint` still says `@drake` a lot.)

Other than in those times of need, we should avoid saying `@drake`, for consistency.

> (4..5)

I suppose I should write down those rules somewhere.  Maybe in `cc.bzl`?

My hope is that by fixing it up to 100% compliance now, people's habit of cargo-culting will mean that the invariant is preserved.

In most of our BUILD files, we use `drake_cc_library` by habit, which is easy to get correct.  I think the primary hazard is for externals.  We could imagine a linter that checks for `cc_library` hygiene in `package.BUILD.bazel` files, but at the moment I'm not sure it's worth the trade-off.

> One example that looks out-of-spec ... Similar is ...

Nice finds.  I'd forgotten about the annoying legacy mechanism of using `repo_ctx.file(...)` to write out BUILD files from programmatically-created literal strings.  (Filed for cleanup here: https://github.com/RobotLocomotion/drake/issues/20233.)

I grepped for all of those uses now, and fixed several more.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20230)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
