### PR TITLE
trajectories: Adds PiecewisePolynomial::AppendFirstOrderSegment

### PR DESCRIPTION
**Pull request by RussTedrake**
for incremental construction of first-order polynomial trajectories.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14030)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14030#-:-MGaEht0Dc168x1tqMhl:b-fcupkv)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14030#-:-MGaGWlW8buINtjBMPhO:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri :lgtm: platform.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14030#-:-MGd0RunBaiUOj9RUWpw:b-cy5i)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[common/trajectories/piecewise_polynomial.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14030#-MGd0l913lNEpjwxqaIE:-MGd0l913lNEpjwxqaIF:b-ulnckx) ([raw file](https://github.com/robotlocomotion/drake/blob/266dc00f2b14a83670fcdcaf56d56ec833d2b06a/common/trajectories/piecewise_polynomial.cc#L361)):*
> ```cpp
>     }
>   }
>   polynomials_.push_back(matrix);
> ```

nit If I'm reading this correctly, I think we want `std::move(matrix)` here to avoid re-copying all of the `Polynomial`s.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14030)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[common/trajectories/piecewise_polynomial.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14030#-MGd0l913lNEpjwxqaIE:-MGd3tOi6-qDsXa0HoNA:bs49xoz) ([raw file](https://github.com/robotlocomotion/drake/blob/266dc00f2b14a83670fcdcaf56d56ec833d2b06a/common/trajectories/piecewise_polynomial.cc#L361)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If I'm reading this correctly, I think we want `std::move(matrix)` here to avoid re-copying all of the `Polynomial`s.
</blockquote></details>

Done.  (here an in the identical usage above).  thanks.

**Pull request merged**
