### PR TITLE
Add more compile time check for updating constraint bound.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8609)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAGS8AVEe1-SbPE3QcH:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[solvers/constraint.h, line 113 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAIwNAfDIJrD2-ombyV:-LAIwNAhDsZ6ZvQ6sS8J:b-w50p9w) ([raw file](https://github.com/robotlocomotion/drake/blob/6d7450a59a7fd29c0ddb5572a52f2f43cd8d5c44/solvers/constraint.h#L113)):*
> ```objc
>    */
>   template <typename Derived>
>   typename std::enable_if<is_eigen_vector_of<Derived, double>::value>::type
> ```

BTW Rather than use SFINAE to constrain this to vectors, could you possibly use `Eigen::Ref<>`, if that simplifies it?
(A slightly larger more runtime overhead, but reduces the number of templates required.)

That being said, I'm not 100% sure if it will simplify errors.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAIwhIl4lKx2je_fZnY:b-lsk0ew)*

**Comment by EricCousineau-TRI** [comment]
*[solvers/constraint.h, line 113 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAIwNAfDIJrD2-ombyV:-LAIwlDd3GDs3kVp2NKU:bt9lmbr) ([raw file](https://github.com/robotlocomotion/drake/blob/6d7450a59a7fd29c0ddb5572a52f2f43cd8d5c44/solvers/constraint.h#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Rather than use SFINAE to constrain this to vectors, could you possibly use `Eigen::Ref<>`, if that simplifies it?
(A slightly larger more runtime overhead, but reduces the number of templates required.)

That being said, I'm not 100% sure if it will simplify errors.
</blockquote></details>

`Eigen::Ref<Eigen::VectorXd>` to be specific

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAJCdJeBa2Potm8S9R2:b-1zm1j3)*

**Comment by sammy-tri** [comment]
In the previous implementation, this check was already present because `UpdateLowerBound` and `UpdateUpperBound` were calling `set_bounds` to do the actual update.  This seems to spread the checking over more functions but not introduce any more checks, which I'm not sure is an improvement.  Is there an additional motivation for this PR?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/constraint.h, line 137 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAJLC4s-6HIkpPDoh-9:-LAJLC4s-6HIkpPDoh-A:bq0cvyw) ([raw file](https://github.com/robotlocomotion/drake/blob/87ed4b3a6a5eb5cc1481d27a29723752a6eec040/solvers/constraint.h#L137)):*
> ```objc
>                   const Eigen::MatrixBase<DerivedU>& upper_bound) {
>     if (lower_bound.rows() != num_constraints() ||
>         upper_bound.rows() != num_constraints() || lower_bound.cols() != 1 ||
> ```

Is losing the check on number of columns here intentional?  The comment still calls for only one column, and I', not sure having more than one would work out well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAJKnfaE_MXJOaQDYWE:b-2d6oj3)*

**Comment by sammy-tri** [comment]
I missed a critical part of the change.  Sorry about that!

:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAJYpSo5ryiig3sbVK0:bbaux3q)*

**Comment by EricCousineau-TRI** [comment]
*[solvers/constraint.h, line 138 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAJgafH5ZVSCOK-pdW0:-LAJgafH5ZVSCOK-pdW1:b-rm90df) ([raw file](https://github.com/robotlocomotion/drake/blob/d0785d6bfc0305e2fb2616b129a5aab7e01a9c42/solvers/constraint.h#L138)):*
> ```objc
>    */
>   void set_bounds(const Eigen::Ref<const Eigen::VectorXd>& lower_bound,
>              const Eigen::Ref<const Eigen::VectorXd>& upper_bound) {
> ```

BTW Visual indent is under-indented?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/constraint.h, line 139 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAJgpUX9Buh0exM34B2:-LAJgpUX9Buh0exM34B3:b-czdcms) ([raw file](https://github.com/robotlocomotion/drake/blob/d0785d6bfc0305e2fb2616b129a5aab7e01a9c42/solvers/constraint.h#L139)):*
> ```objc
>   void set_bounds(const Eigen::Ref<const Eigen::VectorXd>& lower_bound,
>              const Eigen::Ref<const Eigen::VectorXd>& upper_bound) {
>     if (lower_bound.rows() != num_constraints() ||
> ```

BTW In line with Sammy's comment about redundant checks, how about having `set_bounds` call` UpdateUpperBound` and `UpdateLowerBound`?

That way the errors are a little more informative, and there's no redundancy.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/constraint.h, line 138 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAJgafH5ZVSCOK-pdW0:-LAOEJMlD6PBI4nv1bEp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0785d6bfc0305e2fb2616b129a5aab7e01a9c42/solvers/constraint.h#L138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Visual indent is under-indented?
</blockquote></details>

Done.

---

*[solvers/constraint.h, line 139 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-LAJgpUX9Buh0exM34B2:-LAOEJrwBp8RyQOydFwC:b-yh16lj) ([raw file](https://github.com/robotlocomotion/drake/blob/d0785d6bfc0305e2fb2616b129a5aab7e01a9c42/solvers/constraint.h#L139)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW In line with Sammy's comment about redundant checks, how about having `set_bounds` call` UpdateUpperBound` and `UpdateLowerBound`?

That way the errors are a little more informative, and there's no redundancy.
</blockquote></details>

Done. Good call!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609#-:-LAOOCWTC0uB-jyK1zeI:b-8uy5s1)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8609)*

**Pull request merged**
