### PR TITLE
Import new versions of FindProtobuf and FindMatlab CMake modules from upstream

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed for both #7293 and #7323. Really just relocating and slightly updating files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7356)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-KxUHJOTixEm8ynK3yhd:-KxUHJOU6Ags7OQuLtr-:bi1gtys) ([raw file](https://github.com/robotlocomotion/drake/blob/f90a036198500c754f8e6fa7d32f8ee98b7413dd/cmake/config.cmake#L47)):*
> ```CMake
> # Add local CMake modules to CMake search path.
> #------------------------------------------------------------------------------
> function(drake_setup_cmake BASE_PATH)
> ```

Why are these paths not necessary anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-KxUHJOTixEm8ynK3yhd:-KxUICkBvg_Z0PinClqd:b-qo133b) ([raw file](https://github.com/robotlocomotion/drake/blob/f90a036198500c754f8e6fa7d32f8ee98b7413dd/cmake/config.cmake#L47)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Why are these paths not necessary anymore?
</blockquote></details>

Which paths?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-KxUHJOTixEm8ynK3yhd:-KxUIo66glqm1QKlJVaG:bjt4co9) ([raw file](https://github.com/robotlocomotion/drake/blob/f90a036198500c754f8e6fa7d32f8ee98b7413dd/cmake/config.cmake#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Which paths?
</blockquote></details>

They are set below. This was massively over-engineered.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-:-KxUORQpaRsEvZyLmmbH:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform :lgtm:. One minor BTW to consider.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-KxUhf7TsvW1JY4cSubV:-KxUhf7TsvW1JY4cSubW:bsll9tw) ([raw file](https://github.com/robotlocomotion/drake/blob/01edd1137ecd4dfb2ddc87965d09125b9ec2bebb/third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake#L86)):*
> ```CMake
> #   protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS foo.proto)
> #   protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS EXPORT_MACRO DLL_EXPORT foo.proto)
> #   protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS DESCRIPTORS PROTO_DESCS foo.proto)
> ```

BTW better to keep these to 80 character lines if you can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-:-KxUi0FsB87dV5z9Zr32:b-4w2lbe)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7356#-KxUhf7TsvW1JY4cSubV:-KxUkrgxlcMMk9hJBtsZ:b-h1bf6u) ([raw file](https://github.com/robotlocomotion/drake/blob/01edd1137ecd4dfb2ddc87965d09125b9ec2bebb/third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW better to keep these to 80 character lines if you can.
</blockquote></details>

BTW This is a third party file, so I will stick with their formatting for better or worse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7356)*

**Pull request merged**
