### PR TITLE
[math] Add RotationMatrix::ToRollPitchYaw()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18172)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI I've removed the component label on this PR. The "component" labels are only specified for use on [issues](https://drake.mit.edu/issues.html), not on [pull requests](https://drake.mit.edu/reviewable.html).  When component labels are added to pull requests, they clutter up Reviewable's overview dashboard (because "component" alpha-sorts first) and they can end up pushing the actually important labels (priority, release notes, status, etc) off so far to the right such that they are not displayed.

**Review by mitiguy — COMMENTED** [review]
@jwnimmer-tri  -- Wow, I had just removed that label a millisecond before you did.  You move fast.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18172#-:-NFBOSR-0wo4nLQCKpyU:b4sh5uh)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by mitiguy — COMMENTED** [review]
PR #18172 helps to address the C++ part of issue #18151.
A separate PR will create Python bindings to finish resolving that issue.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18172#-:-NFBOev87VAaHf_kW3Mn:b-d3c801)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18172#-:-NFBa2B0DiBMjlZpWnq-:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
FYI I've also just re-titled this PR to aid with release notes:
- The implementation language is not a relevant part of the subject line (i.e., how we communicate with users).  If you wish to highlight that your work plan defers the Python bindings until later, then you can mention that in the body (description) as a detail for your reviewer; it doesn't need to go into the subject line.
- Mentioning "tests" in the subject line is a tautology.  PRs always have tests, and in any case users don't need to care about it.
- Mentioning two numbers in the subject line is too confusing (and tends to blow through the nominal 72-character limit).  You can place the issue number into the body instead of the subject, if you like.

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 
:lgtm: x 2

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18172#-:-NFG_wfD4PLbnOmKbo8W:bibb74)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
