### PR TITLE
November 2022 updates

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #18232

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@xuchenhan-tri for both reviews please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244#-:-NFtCudk3bNcEvdV1w39:bdnkd7p)* status: LGTM missing from assignee xuchenhan-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:x2 thanks!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244#-:-NFtJSM7DZdO8RTMmAf1:b-qs6dst)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Could you rebase the PR on top of master? I'll hold the other PRs in the queue for the moment.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244#-:-NFtJjY39Q7NTJCC3oKA:bjkd0lw)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
Thanks, rebasing now...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244#-:-NFtLaS61VyJV-CyH2FW:b-1u5i2z)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
All set (CI is re-running)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244#-:-NFtMQP6Dk046teFwzn1:b-jexwvy)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform), base commit is latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18244)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform), base commit is latest master (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
I'll use my superpowers to merge now.

**Comment by xuchenhan-tri** [comment]
Thanks!

**Pull request merged**
