### PR TITLE
Adding ids to GeometryFrame and GeometryInstance

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This smooths the road in the future for asynchronous addition of frames/geometry. One system can generate them (know the final ids by querying the specification instances), and rely on those being the ids when the GeometrySystem realizes the specification.

1. Adding the ids to the instances themselves.
2. Ancillary, modifying the get_value() methods to simply be value().
3. GeometryState returns the id of the provided instance.
4. Test said functionality.

```
Category            added  modified  removed  
----------------------------------------------
code                22     10        0        
comments            6      1         0        
blank               4      0         0        
----------------------------------------------
TOTAL               32     11        0        
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7498)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@amcastro-tri  for a tiny feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-Kz9oIYwDO7h_CdW6GfE:b-sp9w)*

**Comment by amcastro-tri** [comment]
Minor comments. :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/geometry/geometry_frame.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9s6SdtPdFCyUPK9mR:-Kz9s6SeZis1mwMxvys1:bvhp05q) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_frame.h#L47)):*
> ```objc
>         frame_group_(frame_group_id) {}
> 
>   FrameId id() const { return id_; }
> ```

BTW, all other methods are called `get_something()` so maybe worth having `get_id()`. Also, isn't `id()`  sort of border line the style guide? (I actually like id(), just saying that `get_id()` probably makes it clearer).

---

*[drake/geometry/geometry_frame.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sRbHxDvgczwqk4vt:-Kz9sRbHxDvgczwqk4vu:b-zbps96) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_frame.h#L47)):*
> ```objc
>         frame_group_(frame_group_id) {}
> 
>   FrameId id() const { return id_; }
> ```

I'd add doc for this getter. Specifically mentioning it is unique per instance and its invariance under copy.

---

*[drake/geometry/geometry_instance.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sv01Jcs6ebvwCrwS:-Kz9sv01Jcs6ebvwCrwT:b-mj7umj) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_instance.h#L28)):*
> ```objc
>   GeometryInstance(const Isometry3<double>& X_PG, std::unique_ptr<Shape> shape);
> 
>   GeometryId id() const { return id_; }
> ```

same thing about `get_id()`

---

*[drake/geometry/geometry_instance.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sx8ZzLyvyDx2wO3s:-Kz9sx8ZzLyvyDx2wO3t:bcrhbuy) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_instance.h#L28)):*
> ```objc
>   GeometryInstance(const Isometry3<double>& X_PG, std::unique_ptr<Shape> shape);
> 
>   GeometryId id() const { return id_; }
> ```

Same thing about documenting it remains invariant under copy/assignment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-Kz9tP2LYZW1pb7o6fRH:brcxnaa)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed.  PTAL

---

Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/geometry/geometry_frame.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9s6SdtPdFCyUPK9mR:-Kz9uz31lGuNxdDCwoni:b-wiaysl) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_frame.h#L47)):*
Done Oops. That was an oversight. I'd made the changes to `GeometryInstance` but forgot to do that here. I even made a comment in the PR description alluding to the fact that `get_value()` --> `value()` was part of this PR.

As for the styleguide, you'll find that it's 100% styleguide-compliant. http://drake.mit.edu/styleguide/cppguide.html#Function_Names

> Accessors and mutators (get and set functions) may be named like variables. These often correspond to actual member variables, but this is not required. For example, int count() and void set_count(int count).

---

*[drake/geometry/geometry_frame.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sRbHxDvgczwqk4vt:-Kz9vouyovl9Xq_rX33U:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_frame.h#L47)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd add doc for this getter. Specifically mentioning it is unique per instance and its invariance under copy.
</blockquote></details>

Done

---

*[drake/geometry/geometry_instance.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sv01Jcs6ebvwCrwS:-Kz9vcI1dIif0z0kuxjI:b61b9lw) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_instance.h#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

same thing about `get_id()`
</blockquote></details>

See previous note (although, in this case, you'll note the methods *are* `pose()`, and `shape()`.

---

*[drake/geometry/geometry_instance.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-Kz9sx8ZzLyvyDx2wO3s:-Kz9vlREuUBWIrgtesKm:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/022b90504a75030e63a24ba1f37820657060a6e4/drake/geometry/geometry_instance.h#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Same thing about documenting it remains invariant under copy/assignment.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-KzA0xdMSQjQbRUoYqHQ:ba8prf5)*

**Comment by SeanCurtis-TRI** [comment]
+@sherm1 for platform review, please

---

Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-KzA67hepQEM1YU9OT3t:bwwp0j0)*

**Comment by amcastro-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/geometry/geometry_frame.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-KzAFjlVcqdrew3I8Ct9:-KzAFjlVcqdrew3I8CtA:b-ooty09) ([raw file](https://github.com/robotlocomotion/drake/blob/dbb4540023f3c96da443b4d8a6e3abf36901ec64/drake/geometry/geometry_frame.h#L52)):*
BTW

> After successfully registering this %FrameInstance, this id will serve as the identifier for the registered representation as well.

Is this a detail that should leak to users?

---

*[drake/geometry/geometry_instance.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-KzAFrA16tpU57xw11fP:-KzAFrA16tpU57xw11fQ:b7jq1vg) ([raw file](https://github.com/robotlocomotion/drake/blob/dbb4540023f3c96da443b4d8a6e3abf36901ec64/drake/geometry/geometry_instance.h#L30)):*
> ```objc
>   /** Returns the globally unique id for this geometry specification. Every
>    instantiation of %GeometryInstance will contain a unique id value. The id
>    value is preserved across copies. After successfully registering this
> ```

BTW same about implementation detail leaking to users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/geometry/geometry_frame.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-KzAFjlVcqdrew3I8Ct9:-KzAGGc-Pep31sUNQPpW:b48htxb) ([raw file](https://github.com/robotlocomotion/drake/blob/dbb4540023f3c96da443b4d8a6e3abf36901ec64/drake/geometry/geometry_frame.h#L52)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW

> After successfully registering this %FrameInstance, this id will serve as the identifier for the registered representation as well.

Is this a detail that should leak to users?

</blockquote></details>

OK Yep. 100%. It's the whole point of this PR.

---

*[drake/geometry/geometry_instance.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-KzAFrA16tpU57xw11fP:-KzAGJExjxWYLIEy2SfN:bj5fryv) ([raw file](https://github.com/robotlocomotion/drake/blob/dbb4540023f3c96da443b4d8a6e3abf36901ec64/drake/geometry/geometry_instance.h#L30)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW same about implementation detail leaking to users.
</blockquote></details>

Done See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498)*

**Comment by sherm1** [comment]
Should have unit tests that cover copying (id is preserved) and (if this is possible) that after copying there is no way to register two geometry entities that have the same id. I didn't look closely enough to see if there are tests for those conditions. Assuming yes, :lgtm:. Otherwise please add (or explain why not needed).

---

Reviewed 2 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-KzAWw2GDG09f11Xh0Lk:b6h1wul)*

**Comment by sherm1** [comment]
Reviewed 1 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498)*

**Comment by SeanCurtis-TRI** [comment]
An *excellent* point. Done.

---

Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-KzBRFNsTrGGn6jYCYs-:bmftbbu)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7498#-:-KzBkNLq2pPYqLxMze1o:bnfp4nl)*

**Pull request merged**
