### PR TITLE
Superbuild refactor, part 1

### LINKED ISSUE #2772: lcm java interface to matlab is broken
My version of matlab on mac is no longer able to load and use the lcm java bindings in lcm.jar.  To reproduce, simply run
```
addpath_drake
checkDependency('lcm')
```
in matlab.  it will say that lcm is not found.  that is because the lcm.jar is not being loaded successfully by matlab.

Once again, this is sneaking through our CI -- probably because missing dependencies currently fail silently.  This means that the matlab functionality in drake is absolutely crippled (It is also blocking the work I was hoping to do today.)

Having not looked into it yet, i suspect that flags like supporting older java versions (which have been the subject of conversation before) are missing.
```
>> version -java

ans =

Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
```
but at the command line
```
drake008% javac -version
javac 1.8.0_60
```

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove (superbuild level) PODS support. Move general build configuration logic to a separate file and refactor to share this between the superbuild and the build of drake itself. Move logic to set the Java target version to match the matlab JVM into here, and pass Java build flags to all (CMake) externals. Improve compiler version checks and fix message for MSVC version.

Fixes #2772.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2820)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, you're probably not the best person to review, but I know #2772 has been giving you trouble. Please feel free to reassign (I don't know who's on rotation today).

**Comment by mwoehlke-kitware** [comment]
Putting @david-german-tri on this also since he's been working with build system stuff, but same comment applies.

**Comment by david-german-tri** [comment]
Looks good overall.  I'd like to try it on my Mac before it merges, and I hope to be able to do that later today.  Tomorrow morning at the latest.  In the meantime, could you please run `mac-clang-experimental-matlab`?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KMyqIwftOacHnllnHDI:1857016957) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
> ```CMake
> 
> # Set default install prefix
> if(PROJECT_NAME STREQUAL "drake-superbuild")
> ```

Seems like this clause should stay in the superbuild CMakeLists, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-:-KMyoRu7bMAACNwqWkjw:-135303742)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KMyvGGm7uApapDaSVjm:-913060771) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Seems like this clause should stay in the superbuild CMakeLists, no?
</details>
The objective was to remove as much of the general setup as possible from the `CMakeLists.txt`. The original intent (which can be seen in the git history) was not even to share this file, but I later realized that some parts — the matlab JVM bits in particular — *should* be shared.

Another option would be to have a `config.cmake` (superbuild only) and `config-common.cmake` (shared). I'm somewhat partial to that; what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
> could you please run `mac-clang-experimental-matlab`?

https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental-matlab/44/

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KMzWMucDTfQVmBZD8G6:-1932391742) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> The objective was to remove as much of the general setup as possible from the `CMakeLists.txt`. The original intent (which can be seen in the git history) was not even to share this file, but I later realized that some parts — the matlab JVM bits in particular — *should* be shared.
> 
> Another option would be to have a `config.cmake` (superbuild only) and `config-common.cmake` (shared). I'm somewhat partial to that; what do you think?
</details>
I like the concept, but I'm not sold on that exact division.  Everything in this file except this clause is configuring a compiler/interpreter.  How about `drake-compilers.cmake` and `drake-superbuild-install.cmake`?

I'd also be in favor of moving the free code into functions; it's kind of surprising for `include(...)` to have a side effect.  perhaps `configure_compilers()` (called from both CMakeLists) and `configure_superbuild_install(...)` (called from just the Sueprbuild CMakeLists)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by sherm1** [comment]
@mwoehlke-kitware, I'm on platform duty today but I'm definitely not the right person to review this. I think @RussTedrake as platform reviewer would make sense for this one.

**Comment by david-german-tri** [comment]
I agree with @sherm1, BTW - I'm feature review, @RussTedrake is platform review.

**Comment by david-german-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KN2r3NiXuv3HZDhdeey:-1760997799) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I like the concept, but I'm not sold on that exact division.  Everything in this file except this clause is configuring a compiler/interpreter.  How about `drake-compilers.cmake` and `drake-superbuild-install.cmake`?
> 
> I'd also be in favor of moving the free code into functions; it's kind of surprising for `include(...)` to have a side effect.  perhaps `configure_compilers()` (called from both CMakeLists) and `configure_superbuild_install(...)` (called from just the Sueprbuild CMakeLists)?
</details>
I'm awaiting resolution on this thread.  If you can get to it today, that would be convenient for me to test on a Mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KN3ML96DMLnGNaaaGxW:835420247) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I'm awaiting resolution on this thread.  If you can get to it today, that would be convenient for me to test on a Mac.
</details>
I moved everything into functions/macros.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by RussTedrake** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KN7GrLhnHZNYOTm52q1:1544039459) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I moved everything into functions/macros.
</details>
but i still think you should move this particular piece, which is only relevant for superbuild, out of the cmake repo?

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7FIUEfPngFrmsZxVb:-842386807) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
> ```CMake
> function(drake_get_matlab_jvm_version)
>   # Find matlab
>   find_program(MATLAB_EXECUTABLE matlab)
> ```

should this be find_package(MATLAB ..) to be compatible with the other uses?  

---

*[drake/doc/from_source.rst, line 123 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7H5Z2_MQ6JihbbRzN:-KN7H5Z3ntcGZtEpb5QF:-131442578) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/drake/doc/from_source.rst#L123)):*
> ```reStructuredText
>     mkdir build
>     cd build
>     cmake ../
> ```

:OK: I've always preferred without the trailing slash?  (for aesthetics)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KN7a_fngRlcjBaTScOH:-1709366626) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> but i still think you should move this particular piece, which is only relevant for superbuild, out of the cmake repo?
</details>
@russtedrake just to clarify, this isn't in the cmake repo.  It's in a new superbuild directory called `cmake`.  Seems reasonable to me as rewritten.

---

*[cmake/config.cmake, line 114 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7atgFWxLi7jvHrAWi:-KN7atgGDm-guTV4WaSw:1823192355) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L114)):*
> ```CMake
> macro(drake_setup_superbuild)
>   # Set default install prefix
>   if(PROJECT_NAME STREQUAL "drake-superbuild")
> ```

This `if` statement now seems redundant.

---

*[drake/doc/from_source.rst, line 123 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7H5Z2_MQ6JihbbRzN:-KN7bLfAjaUW29q5Hp6U:-289740215) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/drake/doc/from_source.rst#L123)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> :OK: I've always preferred without the trailing slash?  (for aesthetics)
</details>
BTW, the Reviewable keyword "OK" is a bare string, not an emoji.  Since I'm assuming your intent was to make this a non-blocking comment, I'm setting it as such.

---

*[drake/doc/from_source.rst, line 128 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7bqgVa1BNpaJaRR8G:-KN7bqgWVLOoahRuwBYI:-623959010) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/drake/doc/from_source.rst#L128)):*
> ```reStructuredText
> **Do NOT use sudo.** Just ``make`` is sufficient, and will prevent problems
> later. Feel free to use ``make -j`` if your platform supports it. Note that the
> above ``cmake`` command does not specify a build type, so drake will be built
> ```

BTW also, these changes are already on master from someone else's PR, so it's possible your git tree is in an odd state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KMyqIwftOacHnllnHDH:-KN7euCxoClA8iBhoF4K:-1755201495) ([raw file](https://github.com/robotlocomotion/drake/blob/a5a44d1856851757dcf23eea0831d3bed6cc297e/cmake/config.cmake#L102)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @russtedrake just to clarify, this isn't in the cmake repo.  It's in a new superbuild directory called `cmake`.  Seems reasonable to me as rewritten.
</details>
What @david-german-tri said :smile:. My eventual goal is to lift as much logic as possible out of the root CMakeLists.txt (i.e. by moving it to utility files like this new `config.cmake`), leaving *just* the external project definitions and minimal calls into the helpers.

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7fW4UurbvDyb1IGud:-1079040234) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> should this be find_package(MATLAB ..) to be compatible with the other uses?  
</details>
No... I'll try to explain why this works the way it does; @billhoffman might want to chime in to confirm, as this is my understanding of logic I didn't originally create.

The original logic¹ does the same thing. The reason is that `find_package(Matlab)` is "*really* good at finding MATLAB", but it was desired that MATLAB support should only be enabled if the executable is in the user's `PATH`. Thus, we first do this simple check for the main executable, and only if it succeeds (and `DISABLE_MATLAB` is `OFF`) do we enable MATLAB support and² do the full `find_package(Matlab)` routine.

(¹ ...well buried in `mex_setup` of [`mex.cmake`](https://github.com/RobotLocomotion/cmake/blob/master/mex.cmake). This is what initially sets `MATLAB_FOUND`, and note that [the call to `find_package(Matlab)`](https://github.com/RobotLocomotion/drake/blob/ad1636819d1f238066dc7927d2181b0d82510f49/drake/CMakeLists.txt#L144) only occurs `if(MATLAB_FOUND)`)

(² ...in drake proper; this particular logic doesn't need more than the base executable.)

This probably warrants a comment...

---

*[cmake/config.cmake, line 114 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7atgFWxLi7jvHrAWi:-KN7eon4H0vLZoITH7t9:2007328348) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L114)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This `if` statement now seems redundant.
</details>
Oops :blush:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7kN1neM_8BDcIBvQX:-1726691682) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> No... I'll try to explain why this works the way it does; @billhoffman might want to chime in to confirm, as this is my understanding of logic I didn't originally create.
> 
> The original logic¹ does the same thing. The reason is that `find_package(Matlab)` is "*really* good at finding MATLAB", but it was desired that MATLAB support should only be enabled if the executable is in the user's `PATH`. Thus, we first do this simple check for the main executable, and only if it succeeds (and `DISABLE_MATLAB` is `OFF`) do we enable MATLAB support and² do the full `find_package(Matlab)` routine.
> 
> (¹ ...well buried in `mex_setup` of [`mex.cmake`](https://github.com/RobotLocomotion/cmake/blob/master/mex.cmake). This is what initially sets `MATLAB_FOUND`, and note that [the call to `find_package(Matlab)`](https://github.com/RobotLocomotion/drake/blob/ad1636819d1f238066dc7927d2181b0d82510f49/drake/CMakeLists.txt#L144) only occurs `if(MATLAB_FOUND)`)
> 
> (² ...in drake proper; this particular logic doesn't need more than the base executable.)
> 
> This probably warrants a comment...
</details>
more than a comment, it probably deserves to be one contiguous piece of logic somewhere instead of disparate calls to find_package and find_program?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7rYizPwOffxZGviu-:1486591693) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> more than a comment, it probably deserves to be one contiguous piece of logic somewhere instead of disparate calls to find_package and find_program?
</details>
I won't disagree with that, but for now I don't see a good way to achieve that without a serious refactor of mex.cmake. Suggestions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7sW37N8yILooVFVkL:-1013791295) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I won't disagree with that, but for now I don't see a good way to achieve that without a serious refactor of mex.cmake. Suggestions?
</details>
Please add a comment for now, and file an issue for the `mex.cmake` refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KN7FIUEfPngFrmsZxVa:-KN7uERWDjRhcC8G8COl:-1024499932) ([raw file](https://github.com/robotlocomotion/drake/blob/368809de44032df38ad4a2db22e79c1c3ace482f/cmake/config.cmake#L20)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please add a comment for now, and file an issue for the `mex.cmake` refactor.
</details>
Okay. I also twiddled the later logic where `find_package(Matlab)` is actually called to use `MATLAB_EXECUTABLE` (from here) rather than `MATLAB_FOUND` (from `mex_setup`) as the conditional. I think this is a little better, but could probably still use improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by david-german-tri** [comment]
FYI, there is a conflict with master.  Appears trivial to resolve.  Testing on Mac locally now.

**Comment by david-german-tri** [comment]
I am still experiencing #2772 with this change.

```
>> checkDependency('lcm')
 Added the lcm jar to your javaclasspath (found via pkg-config)
 
 LCM not found.  LCM support will be disabled.
 To re-enable, add lcm-###.jar to your matlab classpath
 (e.g., by putting javaaddpath('/usr/local/share/java/lcm-0.9.2.jar') into your startup.m .
 
Error using checkDependency (line 450)
Cannot find required dependency: lcm
```

**Comment by mwoehlke-kitware** [comment]
> I am still experiencing #2772 with this change.

When you configure the superbuild, do you get the message "MATLAB JVM version (...) does not match installed Java Development Kit version (...)"? If you search your build directory for `CMAKE_JAVA_COMPILE_FLAGS`¹, what is it set to?

(¹ `find . -name CMakeCache.txt | xargs grep CMAKE_JAVA_COMPILE_FLAGS`)

**Comment by david-german-tri** [comment]
```
build davidgerman$ cmake ..
-- CMAKE_INSTALL_PREFIX=/Users/davidgerman/drake/makefile_build/drake-distro/build/install
-- Found Java: /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java (found suitable version "1.8.0.74", minimum required is "1.6") 
CMake Warning at cmake/config.cmake:45 (message):
  MATLAB JVM version (1.7) does not match installed Java Development Kit
  version (1.8)
```

```
build davidgerman$ grep -R CMAKE_JAVA_COMPILE_FLAGS . --include="CMakeCache.txt"
./drake/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/bot_core_lcmtypes/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/bullet/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/eigen/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/googletest/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/lcm/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/libbot/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/spotless/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/swig_matlab/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/swigmake/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
./externals/yaml_cpp/CMakeCache.txt:CMAKE_JAVA_COMPILE_FLAGS:STRING=
```

**Comment by mwoehlke-kitware** [comment]
Oh... fudge. There's a typo in the version compare... fix coming (going to take a few to rebase)...

**Comment by david-german-tri** [comment]
OK, I now get `-source 1.7 -target 1.7` in all the `CMakeCache.txt`, but `javac` coughs up the following inside LCM:

```
[ 77%] Building Java objects for jchart2d.jar
javac: invalid flag: -source 1.7 -target 1.7
Usage: javac <options> <source files>
use -help for a list of possible options
make[5]: *** [lcm-java/jchart2d-code/CMakeFiles/jchart2d.dir/java_compiled_jchart2d] Error 2
make[4]: *** [lcm-java/jchart2d-code/CMakeFiles/jchart2d.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [lcm-prefix/src/lcm-stamp/lcm-build] Error 2
make[1]: *** [CMakeFiles/lcm.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by david-german-tri** [comment]
`VERBOSE=1` suggests it might be an escaping issue:

```
[ 77%] Building Java objects for jchart2d.jar
cd /Users/davidgerman/drake/makefile_build/drake-distro/externals/lcm/lcm-java/jchart2d-code && /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/javac -source\ 1.7\ -target\ 1.7 -classpath :/Users/davidgerman/drake/makefile_build/drake-distro/externals/lcm/lcm-java/jchart2d-code:/Users/davidgerman/drake/makefile_build/drake-distro/build/externals/lcm/lcm-java/jchart2d-code:ext/build/profile.jar:ext/build/junit-4.8.1.jar:ext/build/proguard-4.5.1.jar:ext/build/jipViewer.jar:ext/xmlgraphics-commons-1.3.1.jar:ext/jide-oss-2.9.7.jar -d /Users/davidgerman/drake/makefile_build/drake-distro/build/externals/lcm/lcm-java/jchart2d-code/CMakeFiles/jchart2d.dir @/Users/davidgerman/drake/makefile_build/drake-distro/build/externals/lcm/lcm-java/jchart2d-code/CMakeFiles/jchart2d.dir/java_sources
javac: invalid flag: -source 1.7 -target 1.7
```

**Comment by mwoehlke-kitware** [comment]
> `javac` coughs up the following [...] might be an escaping issue

:headdesk:

Well, *that's* just lovely... unlike e.g. `CMAKE_CXX_FLAGS`, `CMAKE_JAVA_COMPILE_FLAGS` needs to be a *list*.

I pushed a... "fix"... if you can call it that...

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/config.cmake, line 55 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KNDVOEImMDfO2g7AwYi:-KNDUFGYCRCous-lAc3Y:1400849188) ([raw file](https://github.com/robotlocomotion/drake/blob/ea95a50cc301daba037b653ee1635e894305e17a/cmake/config.cmake#L55)):*
> ```CMake
>             -source ${MATLAB_JVM_VERSION}
>             -target ${MATLAB_JVM_VERSION})
>           string(REPLACE ";" "\\\\\\\\\\\\\\;" _java_flags "${_java_flags}")
> ```

This still doesn't work for me.

```
[  5%] Building Java objects for lcmtypes_drake-java.jar
javac: invalid flag: -source\\\
Usage: javac <options> <source files>
use -help for a list of possible options
/bin/sh: 1.7\\\: command not found
/bin/sh: -target\\\: command not found
/bin/sh: 1.7: command not found
```

I'm not sure what you were getting at with fourteen backslashes in particular - in addition to fixing it, could you please document how it works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
> I'm not sure what you were getting at with fourteen backslashes in particular

Trial and error; it's what worked on my machine. Per the commit message, trying to pass lists into CMake cache arguments for an external project is "an adventure in escaping hell", as evidenced by it *not* working for you...

Alternatively, there is the `LIST_SEPARATOR` option... I switched to that instead and squashed it back into the earlier history. Please try the latest version.

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/config.cmake, line 55 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KNDVOEImMDfO2g7AwYi:-KNDmOaB7nY0KE_E7bbd:-556679088) ([raw file](https://github.com/robotlocomotion/drake/blob/ea95a50cc301daba037b653ee1635e894305e17a/cmake/config.cmake#L55)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This still doesn't work for me.
> 
> ```
> [  5%] Building Java objects for lcmtypes_drake-java.jar
> javac: invalid flag: -source\\\
> Usage: javac <options> <source files>
> use -help for a list of possible options
> /bin/sh: 1.7\\\: command not found
> /bin/sh: -target\\\: command not found
> /bin/sh: 1.7: command not found
> ```
> 
> I'm not sure what you were getting at with fourteen backslashes in particular - in addition to fixing it, could you please document how it works?
</details>
This works, which is great.  Three requests, hopefully the last:

- Please either pass the separator down as a parameter, or clearly document that `drake_setup_platform` assumes the string variables it sets will be parsed into lists with an exclamation point separator.

- I can see from local testing that `drake/CMakeCache.txt` gets semicolons, not exclamation points, in `CMAKE_JAVA_COMPILE_FLAGS`.  That seems like the right outcome, but I don't understand how it works out that way.  Shouldn't it get clobbered with exclamation points when `drake/CMakeLists.txt` calls this function?

- Please run Mac and Windows MATLAB CI again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/config.cmake, line 55 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KNDVOEImMDfO2g7AwYi:-KNDvrF5ztTvTZdVILra:-1357641786) ([raw file](https://github.com/robotlocomotion/drake/blob/ea95a50cc301daba037b653ee1635e894305e17a/cmake/config.cmake#L55)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This works, which is great.  Three requests, hopefully the last:
> 
> - Please either pass the separator down as a parameter, or clearly document that `drake_setup_platform` assumes the string variables it sets will be parsed into lists with an exclamation point separator.
> 
> - I can see from local testing that `drake/CMakeCache.txt` gets semicolons, not exclamation points, in `CMAKE_JAVA_COMPILE_FLAGS`.  That seems like the right outcome, but I don't understand how it works out that way.  Shouldn't it get clobbered with exclamation points when `drake/CMakeLists.txt` calls this function?
> 
> - Please run Mac and Windows MATLAB CI again.
</details>
Actually, it occurs to me now that the flags for drake itself *ought* to be getting clobbered. Sigh... the only right way to do this is to munge the variable right before it gets fed into `COMMON_CMAKE_ARGS`. And we should be doing that for *all* variables that are propagated to external projects.

I'm not even going to try that now; this sort of thing is why the refactor part II is needed.

Meanwhile, I changed the logic to do it for just `CMAKE_JAVA_COMPILE_FLAGS`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by mwoehlke-kitware** [comment]
> Please run Mac and Windows MATLAB CI again

Since you didn't say which (not all of them, I hope?), I guessed:

- [mac-clang-ninja-experimental-matlab](https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-ninja-experimental-matlab/7/)
- [windows-msvc-ninja-64-experimental-matlab](https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-64-experimental-matlab/11/)

OS X is failing though; seems to be having problems checking out the code...

**Comment by mwoehlke-kitware** [comment]
@jamiesnape, do you know why I can't get Jenkins to do experimental builds of this PR?

**Comment by jamiesnape** [comment]
sha1=pr/2820/head or sha=pr/2820/merge

**Comment by jamiesnape** [comment]
GitHub

**Comment by RussTedrake** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820)*

**Comment by david-german-tri** [comment]
The Mac failure looks like a run-of-the-mill flake.  I hope the Windows failures are just because you haven't synced past #2857, so I've kicked off a 'pr/2820/merge` run to make sure.  Once the executor starts up, it should appear here:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-64-experimental-matlab/13/

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 270 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-KNEi2SeyMTSjrqx_wi_:-KNEi2SeyMTSjrqx_wia:-2000414020) ([raw file](https://github.com/robotlocomotion/drake/blob/176777c3a0458ed8deb28bffaf35d412789de3fe/CMakeLists.txt#L270)):*
> ```CMake
> endforeach()
> 
> string(REPLACE ";" "!" CMAKE_JAVA_COMPILE_FLAGS "${CMAKE_JAVA_COMPILE_FLAGS}")
> ```

BTW, consider a comment here.  (If it will be rendered moot by the next stage of the refactor, feel free not to bother.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-:-KNEi8EjLlrf6U4j9qr8:910983802)*

**Comment by david-german-tri** [comment]
(If it's clean, I'll LGTM first thing tomorrow morning.)

---

Reviewed 1 of 3 files at r4, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-:-KNEjyoKP7BftnSr-tNX:-1973625052)*

**Comment by david-german-tri** [comment]
Well, it's much cleaner, and the remaining failures are timeouts that really can't plausibly be caused by this change.  :lgtm:, merge at your own discretion.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-:-KNHroh6zTE5TnpeaXQB:1739390895)*

**Comment by david-german-tri** [comment]
And BTW, thanks for seeing this through.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2820#-:-KNHs0AUu7tY3S5EUx_f:1148325181)*

**Pull request merged**
