### PR TITLE
Google Benchmark 2-step update

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@betsymcphail for feature review.

Needs a bunch mac builds thrown at it -- working on this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447#-:-NJBV5BN6v5fhUzNxdEY:b-xsv7s8)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
FYI @xuchenhan-tri -- we will see if this makes it into the release, I guess.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447#-:-NJBVtAfAJhZOO1YmNdl:bnmx0fp)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @drake-jenkins-bot)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18447#-NJBViMDEF0kO5oup-2z:-NJBYjAB5IPpuhExENts:bwjhzh0) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-debug please.
</blockquote></details>

:lgtm: pending successful CI

___

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review, as next available in rotation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447#-:-NJB_0pgCN58EpaCJ_Ht:b-npcy9x)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @drake-jenkins-bot and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: thanks!

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18447#-:-NJB_OQE9dCk6bq8Hk96:brfqlux)* status: 1 unresolved discussion (waiting on @drake-jenkins-bot)

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

:lgtm: pending successful CI
</blockquote></details>

@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please.

**Pull request merged**
