### PR TITLE
pydrake multibody: Add bindings for Toppra

### PR DESCRIPTION
**Pull request by mpetersen94**
Depends on #15799

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@hongkai-dai for feature review, please (or reassign)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836#-:-Mkix0KC7voXbyZ2JUA6:bl2qbox)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ericcousineau-tri for platform review please.

Eric, please only review the second commit. The first commit is the PR #15799. This PR will be rebased after #15799 is merged.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836#-:-MkmRxJk2ioQWdRb4wQL:b-ja9vw2)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, and @mpetersen94)

___
*[bindings/pydrake/multibody/optimization_py.cc, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-Mkmr5iCEBUsp0M2y_Kc:-Mkmr5iCEBUsp0M2y_Kd:bnbglhb) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/optimization_py.cc#L69)):*
> ```cpp
>     py::class_<Class, solvers::Constraint, Ptr>(
>         m, "QuaternionEulerIntegrationConstraint", cls_doc.doc)
>         .def(py::init([](bool allow_quaternion_negation) {
> ```

nit It's unclear why this factory-style constructor is necessary.

Can I ask why you needed this, vs. the more vanilla style? e.g.
```
.def(py::init<bool>(), py::arg(...), cls_doc.ctor.doc)
```
___
*[bindings/pydrake/multibody/optimization_py.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-Mkmq6bC9h9llz8795vP:-Mkmq6bC9h9llz8795vQ:bcs3haw) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/optimization_py.cc#L100)):*
> ```cpp
> 
>   {
>     py::enum_<ToppraDiscretization>(
> ```

nit Can you separate this and `CalcGridPointsOptions` into their own stanzas, `{ using Class = ...; }`?
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-MkmqKWS9fuJD4huw5bM:-MkmqKWS9fuJD4huw5bN:bsy4aei) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/test/optimization_test.py#L119)):*
> ```Python
> 
>     def test_one_box(self):
>         if not SnoptSolver().available():
> ```

nit Can you use `unittest.skipIf` instead?

Example:
https://github.com/RobotLocomotion/drake/blob/40301ca67ea6fa746d4b23e56dfdc6a7b68d6cc9/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1067-L1070
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 248 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-MkmsRXm4OlUHSwLW3pe:-MkmsRXm4OlUHSwLW3pf:b-s9n3j6) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/test/optimization_test.py#L248)):*
> ```Python
>         self.assertIsInstance(forward_con, mp.Binding[mp.LinearConstraint])
>         constraint = toppra.AddFrameVelocityLimit(constraint_frame=frame,
>                                                   lower_limit=lower_limit[:6],
> ```

nit It's confusing to see a mixture of limits used for joint-space limits and for spatial velocities.

Rather than re-use based on (trimmed) size, can you instead create new limit variables for frame velocities?
(here and elsewhere)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, with some small nits - nice!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836#-:-Mkmw1qnEbBQbO0YlFWR:b-q0r1yh)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, and @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/multibody/optimization_py.cc, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-Mkmr5iCEBUsp0M2y_Kc:-Mkn5_zJCFlvYV9cZyRC:bgu1xcr) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/optimization_py.cc#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's unclear why this factory-style constructor is necessary.

Can I ask why you needed this, vs. the more vanilla style? e.g.
```
.def(py::init<bool>(), py::arg(...), cls_doc.ctor.doc)
```
</blockquote></details>

I only moved these bindings to organize the bindings closer to alphabetical order.  Done anyway.
___
*[bindings/pydrake/multibody/optimization_py.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-Mkmq6bC9h9llz8795vP:-MkoOVsl-aSmBYw9L7SD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/optimization_py.cc#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you separate this and `CalcGridPointsOptions` into their own stanzas, `{ using Class = ...; }`?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-MkmqKWS9fuJD4huw5bM:-MkoPVvY4-6HsM05u9sL:bl29kwd) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/test/optimization_test.py#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you use `unittest.skipIf` instead?

Example:
https://github.com/RobotLocomotion/drake/blob/40301ca67ea6fa746d4b23e56dfdc6a7b68d6cc9/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1067-L1070
</blockquote></details>

Done. SkipUnless seemed to make more sense.
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 248 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-MkmsRXm4OlUHSwLW3pe:-MkoPy3F0-3vshIgm781:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/test/optimization_test.py#L248)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's confusing to see a mixture of limits used for joint-space limits and for spatial velocities.

Rather than re-use based on (trimmed) size, can you instead create new limit variables for frame velocities?
(here and elsewhere)
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15836)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/multibody/optimization_py.cc, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-Mkmr5iCEBUsp0M2y_Kc:-MkqoIrx7c6owEwzLX1b:b-ircmwe) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/optimization_py.cc#L69)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I only moved these bindings to organize the bindings closer to alphabetical order.  Done anyway.
</blockquote></details>

OK Ah, missed that, thanks!
___
*[bindings/pydrake/multibody/test/optimization_test.py, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15836#-MkmqKWS9fuJD4huw5bM:-MkqoN2g7jp1j_2s9KCp:b-bfu5qp) ([raw file](https://github.com/robotlocomotion/drake/blob/65aeb28e9cdc420c9d62864e4f71e5b08fea097e/bindings/pydrake/multibody/test/optimization_test.py#L119)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Done. SkipUnless seemed to make more sense.
</blockquote></details>

OK Yup, thanks!

**Comment by mpetersen94** [comment]
Rebased on master and ready to merge pending CI.

**Pull request merged**
