### PR TITLE
[trajectories] Fix BezierCurve move operators

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Noticed during #19620.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19648)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19648#-:-NYVGJkhEl-V5uedk5fn:btapcr8)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review, please.  (I'm on-call today.)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19648#-:-NYZ1SEk3LPktwsuHsos:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

**Pull request merged**
