### PR TITLE
Pass the time limit to OSQP settings

### PR DESCRIPTION
**Pull request by yminchen**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14625)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for feature review.

@yminchen could you please add a unit test for this PR?  You could test a hard QP with time limit equals to 1ms, and then solve the same QP with time limit equals to a much longer time. They should give different results since the first one terminates prematurely.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14625#-:-MT-ZCpzD6BkJ9BNmR5Q:bpksz1)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by yminchen — COMMENTED** [review]
@hongkai-dai Done! Feel free to let me know if the test needs to be modified.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14625#-:-MT6JAIj7YYMy7t3GxTN:bjj6kpn)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: thanks for adding the test!

+@sammy-tri for platform review please, thanks!

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14625#-:-MT8lRvT8y2CYDPiQ_JP:blajygs)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

+(status: squashing now) 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14625#-:-MTCGIzpBtmUqaOeks2j:bs1ipsa)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai

**Pull request merged**
