### PR TITLE
Add tol as input argument to HPolyhedron functions

### PR DESCRIPTION
**Pull request by hongkai-dai**
Including Intersect, ReduceInequalities and ContainedIn

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895#-:-NBmuTnbEt0XRUSMDcOn:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by AlexandreAmice — COMMENTED** [review]
Quick note on the tolerance value. Adding the documentation that a positive tolerance tests for relaxed redundancy and positive tolerance checks for strict redundancy may be important in case the user wishes to decide whether to be conservative or more relaxed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895#-:-NBmxeVJ0rizgfbsWFRF:b-ssledp)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Yes, along those lines I'd like the docs to be clearer about what the `tol` means (beyond just the formula) -- especially in case we allow it to be negative, or if it's always supposed to be non-negative.

+(release notes: fix) 

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895#-:-NBn7hPT4F-K1ubp4RJO:b-p7fm10)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17895#-NBmwGXkB5KejvtivbNp):*
typo



_Code quote:_
```
Interset
```
___
*[`geometry/optimization/hpolyhedron.h` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17895#-NBmwLYR5xXtlbzdeLjM:-NBmwLYSDYfRcbuwpzJG:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/ef61baba2868f754b3bf14835e6788eca638bb57/geometry/optimization/hpolyhedron.h#L64)):*
> ```objc
>   @param tol We check if this polyhedron is contained in other.A().row(i).dot(x)
>   <= other.b()(i) + tol. The larger tol value is, the more relaxation we add to
>   the containment.*/
> ```

typo



_Suggestion:_
```objc
containment. */
```
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 734 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17895#-NBmw2Az4nXSuiaXzrvb:-NBmw2Az4nXSuiaXzrvc:b-ui8j65) ([raw file](https://github.com/robotlocomotion/drake/blob/ef61baba2868f754b3bf14835e6788eca638bb57/geometry/optimization/test/hpolyhedron_test.cc#L734)):*
> ```cpp
> }  // namespace drake
> 
> int main(int argc, char** argv) {
> ```

I don't think this is particularly useful.  Only the weekly builds test Mosek without Gurobi.  (I think usually Gurobi is used for these programs, when available? Otherwise we would have seen test failures for other build configurations that just the weekly build.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@sammy-tri for platform review per schedule please +(priority: high).

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895#-:-NBrkhniCWlJEf5c6XeQ:b-xkhqm5)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @sammy-tri)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17895#-NBrkqnWEzRxl8JwZdQq:-NBrkqnX0mT_yUVr4JMy:b-9fawh9) ([raw file](https://github.com/robotlocomotion/drake/blob/35b12ec6e49b60ec5e30a08fe39a549cd089e344/bindings/pydrake/geometry_py_optimization.cc#L130)):*
> ```cpp
>             cls_doc.Intersection.doc)
>         .def("ReduceInequalities", &HPolyhedron::ReduceInequalities,
>             py::arg("tol") = 1E-9, cls_doc.ReduceInequalities.doc)
> ```

nit The python unit test should pass `tol` by kwarg as a regression test that `tol` is bound as an argument.

(Ditto for all three functions.)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (pending the last nit)

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895#-:-NBs1mPb39pxkilyRn6B:b6a29qh)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17895)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17895#-NBrkqnWEzRxl8JwZdQq:-NBsNnrj1o0NSa2rPGav:bca9u69) ([raw file](https://github.com/robotlocomotion/drake/blob/35b12ec6e49b60ec5e30a08fe39a549cd089e344/bindings/pydrake/geometry_py_optimization.cc#L130)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The python unit test should pass `tol` by kwarg as a regression test that `tol` is bound as an argument.

(Ditto for all three functions.)
</blockquote></details>

ok, in the interest of respecting the "priority:high" tag I'm going to deem this complete.

**Pull request merged**
