### PR TITLE
Compute Minimal Representation of Degenerate VPolytopes

### LINKED ISSUE #22218: VPolytope::GetMinimalRepresentation Throws for Degenerate VPolytopes
### What happened?

Because this method directly calls QHull, we run into similar issues to those encountered in #19717. In all of the following cases, we are throwing an error (which is not documented in doxygen). But also, ~~we~~ I can fix this pretty easily.

QHull doesn't support ambient dimension 1:
```
from pydrake.all import VPolytope
VPolytope([[1]]).GetMinimalRepresentation()
```

QHull needs at least dimension+1 points:
```
from pydrake.all import VPolytope
v = VPolytope([[0, 1], [0, 1]]).GetMinimalRepresentation()
```

QHull doesn't like when points lie along an affine subspace:
```
from pydrake.all import VPolytope
v = VPolytope([[0, 1, 2], [0, 1, 2]]).GetMinimalRepresentation()
```

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cohnt**
Closes #22218.

+@hongkai-dai for feature review if you're avaiable?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220)

### CODE REVIEW

**Comment by cohnt** [comment]
-@hongkai-dai

+@alexandreamice

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220)* status: 3 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/vpolytope_test.cc` line 867 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9SPS95E_OxxDofMuz:-OC9SPS95E_OxxDofMv-:b-oyr0i6) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/test/vpolytope_test.cc#L867)):*
> ```cpp
>   // One dimensional instance with one point.
>   Matrix<double, 1, 1> degenerate;
>   degenerate << 0;
> ```

Use a non-zero value to make a non-trivial initialization?
___
*[`geometry/optimization/test/vpolytope_test.cc` line 896 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9Slfi--fCHhdSVzAg:-OC9Slfi--fCHhdSVzAh:bte5ime) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/test/vpolytope_test.cc#L896)):*
> ```cpp
>   if (lower > upper) {
>     std::swap(lower, upper);
>   }
> ```

Ditto, you can do 
```cc
lower = v_minimal.vertices().row(0).minCoeff();
upper = v_minimal.vertices().row(0).maxCoeff();
```
___
*[`geometry/optimization/vpolytope.cc` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9RZEs6Mz_RdCFTvSR:-OC9RZEs6Mz_RdCFTvSS:b26wvpf) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/vpolytope.cc#L401)):*
> ```cpp
>       min = std::min(min, vertices_(0, i));
>       max = std::max(max, vertices_(0, i));
>     }
> ```

You could use
```cc
const double min = vertices_.row(0).minCoeff();
const double max = vertices_.row(0).maxCoeff();
```
instead of the for loop (and might also be faster with O(n logn) complexity).

**Review by cohnt — COMMENTED** [review]
-@alexandreamice +@hongkai-dai

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-:-OC9USOp-5mEH4eD-UG7:bk9fqtk)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/vpolytope.cc` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9RZEs6Mz_RdCFTvSR:-OC9Ufpw51PZVwy40OPR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/vpolytope.cc#L401)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You could use
```cc
const double min = vertices_.row(0).minCoeff();
const double max = vertices_.row(0).maxCoeff();
```
instead of the for loop (and might also be faster with O(n logn) complexity).
</blockquote></details>

Done.
___
*[`geometry/optimization/test/vpolytope_test.cc` line 867 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9SPS95E_OxxDofMuz:-OC9Uo1WC1mW7xUsTOL4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/test/vpolytope_test.cc#L867)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Use a non-zero value to make a non-trivial initialization?
</blockquote></details>

Done.
___
*[`geometry/optimization/test/vpolytope_test.cc` line 896 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9Slfi--fCHhdSVzAg:-OC9Uxjf2k4MDVx0FSJ6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b87ea4cd550bcc8a3862575278d2d408c3e3dc/geometry/optimization/test/vpolytope_test.cc#L896)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto, you can do 
```cc
lower = v_minimal.vertices().row(0).minCoeff();
upper = v_minimal.vertices().row(0).maxCoeff();
```
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sherm1 for platform review please, thanks!

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-:-OC9X5bVC1ZO69fDCA5Y:b-z000um)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/vpolytope.cc` line 399 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9Wra38L_41e9AEFkY:-OC9Wra38L_41e9AEFkZ:b-dqbjg8) ([raw file](https://github.com/RobotLocomotion/drake/blob/9de27a0d3c3b41b8bc12dfa8c6cbef5539aab5f7/geometry/optimization/vpolytope.cc#L399)):*
> ```cpp
>     const double max = vertices_.row(0).maxCoeff();
>     Eigen::Matrix<double, 1, 2> out;
>     out << min, max;
> ```

BTW, you could do return `return VPolytope(Eigen::RowVector2d(min, max))` for simplicity.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/vpolytope.cc` line 399 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9Wra38L_41e9AEFkY:-OC9biE-9toKbKkLUF_u:bwmivjp) ([raw file](https://github.com/RobotLocomotion/drake/blob/9de27a0d3c3b41b8bc12dfa8c6cbef5539aab5f7/geometry/optimization/vpolytope.cc#L399)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you could do return `return VPolytope(Eigen::RowVector2d(min, max))` for simplicity.
</blockquote></details>

I think this is actually a counterintuitive naming, since it really represents two column vectors of size 1.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/vpolytope.cc` line 399 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-OC9Wra38L_41e9AEFkY:-OC9l1JI0B5KwonA_LiC:bfuybyb) ([raw file](https://github.com/RobotLocomotion/drake/blob/9de27a0d3c3b41b8bc12dfa8c6cbef5539aab5f7/geometry/optimization/vpolytope.cc#L399)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I think this is actually a counterintuitive naming, since it really represents two column vectors of size 1.
</blockquote></details>

Sounds good.

BTW, you could also do
```cc
return VPolytope(Eigen::Matrix<double, 1, 2>(min, max));
```
if you want to emphasize its shape.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

Notes: 
- still has a "do not merge" label
- commits need a squash and succinct commit message

> Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22220#-:-OCAW1848ltF3RPcv-6K:b3qc8p5)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
