### PR TITLE
Update director to current

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
[EWISOTT](http://tvtropes.org/pmwiki/pmwiki.php/Main/ExactlyWhatItSaysOnTheTin).

See recent comments in #1942 for rationale. I picked current master for no particular reason other than that being the obvious choice. I'm happy to change it if anyone has strong feelings what we should be using, provided `18cc79235b60196ef5aa1af67494bf5bb80ef942` is included.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2142)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: 

Thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2142#-:-KFt_xBORSUoyE8qkQuf:-244862327)*

**Comment by liangfok** [comment]
By switching Director to version c00034a7934476d72633b5611823a387bc8e5b59, I'm now able see a red line in `drake-visualizer` after running `testLidar`. Is this the expected visualization?

screenshot from 2016-04-21 12 16 07

I was hoping to see every single laser beam as it sweeps the scan region.

**Comment by david-german-tri** [comment]
@liangfok, are your questions blocking?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2142#-:-KFtmdchxyaoZVLi6BWV:1722662186)*

**Comment by mwoehlke-kitware** [comment]
> Is this the expected visualization? [screenshot]

Looks right.

> I was hoping to see every single laser beam as it sweeps the scan region.

The LCM message encodes a list of points which are sent as a single message, which is being displayed directly. (The 'test sender' also does not have a way of sending "animated" data.)

**Comment by liangfok** [comment]
Nope. They are non-blocking. Please merge when you can.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2142#-:-KFtyFjb777Kc7ASruGr:1155728261)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2142#-:-KFtypW78vyfsjQpUPEZ:1417088721)*

**Pull request merged**
