### PR TITLE
[workspace] Deprecate the usockets and uwebsockets externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@xuchenhan-tri for platform review, please (Rico is on-call).

**Review by xuchenhan-tri — COMMENTED** [review]
BTW @sherm1 is on-call after Rico for this week :)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-:-NamS1BN9gTYZ5z-Te-w:b75ylix)* status: LGTM missing from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
Right.  Sherm just rubber stamps build system things; in contrast, you've expressed interest in learning more about how build system things work.

**Review by xuchenhan-tri — COMMENTED** [review]
:thumbsup: Happy to review. Just wanted to make sure this is intentional.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-:-NamT2TS2QAPUoo_8yub:bd5eze8)* status: LGTM missing from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-:-NanjWOlAy9LPNLInyW9:bnfp4nl)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with some naive questions.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-:-NarAxoV9JJSNOcThkIK:b-5fduna)* status: 2 unresolved discussions

___
*[`tools/workspace/usockets/package.BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-Nar8R3mAKVur4o09X1X:-Nar8R3nD8csYiUi1vX0:brf57zj) ([raw file](https://github.com/RobotLocomotion/drake/blob/ba9d07dd1302d02504a712992ea9c0ac02fd3d9c/tools/workspace/usockets/package.BUILD.bazel#L26)):*
> ```
> )
> 
> # Install the license file.
> ```

BTW, why do we not need to install the license anymore? Is it because we only need one copy of the license when duplicating dependencies?
___
*[`tools/workspace/usockets_internal/package.BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-NarA3bf-uK7bPrSSMhX:-NarA3bf-uK7bPrSSMhY:brhvbv6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e097042a2d74a2edd315ca41e955a072a576345c/tools/workspace/usockets_internal/package.BUILD.bazel#L24)):*
> ```
>     copts = [
>         "-DLIBUS_NO_SSL",
>         "-fvisibility=hidden",
> ```

BTW, possibly dumb question: I see in the referenced issue that for c code this is enough. Why is it not enough for C++ code? Is it because namespace pollution? Do we also pass in this flag when compliling c++ library and it's done by `vendor_cxx`?



_Code quote:_
```
"-fvisibility=hidden",
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889)* status: 2 unresolved discussions

___
*[`tools/workspace/usockets/package.BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-Nar8R3mAKVur4o09X1X:-NarDMpY5kVl55kkcGm1:b-ip079j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ba9d07dd1302d02504a712992ea9c0ac02fd3d9c/tools/workspace/usockets/package.BUILD.bazel#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why do we not need to install the license anymore? Is it because we only need one copy of the license when duplicating dependencies?
</blockquote></details>

If the `:install` target remained defined here, it would be dead code.  Only `:install` targets that are actually cited by another install target have any effect.  (Similar to how a cc_library is only ever compiled if it's cited by another cc_library or cc_binary, etc.)

With the change to `drake/tools/workspace/BUILD.bazel` up above, we've switched which install target we depend on.  We should only install licenses that match the libraries we're actually depending from our installed C++ code.  Since our C++ doesn't use `@usockets` at all anymore, we should not install the `@usockets` license.

BTW In fact, since no BUILD file inside Drake refers to `@usockets` anymore, this `package.BUILD.bazel` file is not even covered by Drake CI anymore (other than our linting it).  If there were a typo in this cc_library, nothing would notice.
___
*[`tools/workspace/usockets_internal/package.BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-NarA3bf-uK7bPrSSMhX:-NarBovYCLkIGVASuPX1:b-yrel78) ([raw file](https://github.com/RobotLocomotion/drake/blob/e097042a2d74a2edd315ca41e955a072a576345c/tools/workspace/usockets_internal/package.BUILD.bazel#L24)):*
> Why is it not enough for C++ code?

For C++ code, it is both "not enough" and "too much".

It's "not enough" because if there is anything inlined in the upstream C++ headers (e.g., a template), then the upstream object code emitted *in Drake's translation unit* at the point of use will not be marked as hidden.  The upstream compilation actions would have hidden symbols, but Drake's compilation action would not.  This is a non-issue for C code because TANSTA inlining in C.

It's "too much" because if the upstream project uses any other libraries _besides_ itself (e.g., the C++ standard library) then _those_ symbols would also be compiled as hidden in the upstream translation units at their point of use.  Generally it's not a great idea to mark the standard library as hidden -- the compiler and/or linker will yet at us when we do that.

> Do we also pass in this flag when compiling c++ library and it's done by `vendor_cxx`?

Nope.  Per my above exposition, that flag is unsafe ("too much") when used on C++ code.

For C code, we should use `-fvisibility=hidden`.  For C++ code, we should use a hidden `namespace`.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

___
*[`tools/workspace/usockets/package.BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-Nar8R3mAKVur4o09X1X:-NarFjWt1fSsj5A5Kw3N:bcom4y3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ba9d07dd1302d02504a712992ea9c0ac02fd3d9c/tools/workspace/usockets/package.BUILD.bazel#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the `:install` target remained defined here, it would be dead code.  Only `:install` targets that are actually cited by another install target have any effect.  (Similar to how a cc_library is only ever compiled if it's cited by another cc_library or cc_binary, etc.)

With the change to `drake/tools/workspace/BUILD.bazel` up above, we've switched which install target we depend on.  We should only install licenses that match the libraries we're actually depending from our installed C++ code.  Since our C++ doesn't use `@usockets` at all anymore, we should not install the `@usockets` license.

BTW In fact, since no BUILD file inside Drake refers to `@usockets` anymore, this `package.BUILD.bazel` file is not even covered by Drake CI anymore (other than our linting it).  If there were a typo in this cc_library, nothing would notice.
</blockquote></details>

I see. To confirm my understanding then, the only point of deprecation here is for potential users that are using drake's copy of `@usockets` to get a warning so they can switch to an independent copy?
___
*[`tools/workspace/usockets_internal/package.BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-NarA3bf-uK7bPrSSMhX:-NarIRdm2rosjthnMjIs:b-71zb2n) ([raw file](https://github.com/RobotLocomotion/drake/blob/e097042a2d74a2edd315ca41e955a072a576345c/tools/workspace/usockets_internal/package.BUILD.bazel#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Why is it not enough for C++ code?

For C++ code, it is both "not enough" and "too much".

It's "not enough" because if there is anything inlined in the upstream C++ headers (e.g., a template), then the upstream object code emitted *in Drake's translation unit* at the point of use will not be marked as hidden.  The upstream compilation actions would have hidden symbols, but Drake's compilation action would not.  This is a non-issue for C code because TANSTA inlining in C.

It's "too much" because if the upstream project uses any other libraries _besides_ itself (e.g., the C++ standard library) then _those_ symbols would also be compiled as hidden in the upstream translation units at their point of use.  Generally it's not a great idea to mark the standard library as hidden -- the compiler and/or linker will yet at us when we do that.

> Do we also pass in this flag when compiling c++ library and it's done by `vendor_cxx`?

Nope.  Per my above exposition, that flag is unsafe ("too much") when used on C++ code.

For C code, we should use `-fvisibility=hidden`.  For C++ code, we should use a hidden `namespace`.
</blockquote></details>

What is "TANSTA inlining in C"?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

___
*[`tools/workspace/usockets/package.BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-Nar8R3mAKVur4o09X1X:-NarL05V7vIPAVaNhb7k:byr4fl6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ba9d07dd1302d02504a712992ea9c0ac02fd3d9c/tools/workspace/usockets/package.BUILD.bazel#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I see. To confirm my understanding then, the only point of deprecation here is for potential users that are using drake's copy of `@usockets` to get a warning so they can switch to an independent copy?
</blockquote></details>

Right!
___
*[`tools/workspace/usockets_internal/package.BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-NarA3bf-uK7bPrSSMhX:-NarKsxZ-T6O6qqQXXDp:b-bbahn8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e097042a2d74a2edd315ca41e955a072a576345c/tools/workspace/usockets_internal/package.BUILD.bazel#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What is "TANSTA inlining in C"?
</blockquote></details>

Oops.  Apparently TANSTA isn't as well-known as I thought.  It's an initialism for "There Ain't No Such Thing As ...".

https://www.econlib.org/library/Columns/y2014/Hendersontanstaafl.html

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19889)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

___
*[`tools/workspace/usockets_internal/package.BUILD.bazel` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19889#-NarA3bf-uK7bPrSSMhX:-NarQE697X05CMp0j5zU:b7olyuy) ([raw file](https://github.com/RobotLocomotion/drake/blob/e097042a2d74a2edd315ca41e955a072a576345c/tools/workspace/usockets_internal/package.BUILD.bazel#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  Apparently TANSTA isn't as well-known as I thought.  It's an initialism for "There Ain't No Such Thing As ...".

https://www.econlib.org/library/Columns/y2014/Hendersontanstaafl.html
</blockquote></details>

Ok, I asked in HQ and no one seems to know either :0

**Pull request merged**
