### PR TITLE
Snopt defaults not to print. Also report iteration limit.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously snopt always print each iteration to a file called "snopt.out".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8169)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-:-L6B47v7gyauGLyZ0ruV:bvhsv4m)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 694 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I5wxuCckb6tbaXBT-:-L6IrGpASQL9VHRTuYct:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L694)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Grammar, `Determine if we should print out ...`
</blockquote></details>

Done.

---

*[solvers/snopt_solver.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I6Ey1PmaSvgR4hN5O:-L6IrcjpDoL6rkz9q_Kp:b-t5frm0) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L702)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can I ask why you add `1` here?
(To me, it seems `.length()` would have returned the same thing as `strlen(...)`.)
</blockquote></details>

I basically copied the code from https://stackoverflow.com/questions/7352099/stdstring-to-char, where it adds 1 to the string length.

I think c char array has an `\0` at the end, that is not included in c++ string. As shown in the example http://en.cppreference.com/w/cpp/string/basic_string/copy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-:-L6IwbDgUcqqyPvl0bDR:b-qxjhdt)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6Iy9q8pjFYDpmIwqKl:b-vjli53) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
> ```cpp
> 
>   SnoptSolver solver;
>   if (solver.available()) {
> ```

Please document (perhaps atop this file) why we choose to check for the solver at runtime, instead of `tags = ["snopt"]` in the BUILD file.

---

*[solvers/test/snopt_solver_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iymgl2w7R2yoBbTyR:-L6Iymgl2w7R2yoBbTyS:b-gfookr) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L92)):*
> ```cpp
>     prog.SetSolverOption(SnoptSolver::id(), "Print file", "snopt.out");
>     result = solver.Solve(prog);
>   }
> ```

FYI This doesn't test that the file comes out the other side.  Are we okay if this happens to stop working?  (If so, maybe document that fact.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-:-L6IxdxJmGNsykPYW2Sp:b-s794vx)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6J37qYgAI2NLhn-eBF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please document (perhaps atop this file) why we choose to check for the solver at runtime, instead of `tags = ["snopt"]` in the BUILD file.
</blockquote></details>

Done.

---

*[solvers/test/snopt_solver_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iymgl2w7R2yoBbTyR:-L6J396b04jV9DrTRyXs:b-5vh7c2) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This doesn't test that the file comes out the other side.  Are we okay if this happens to stop working?  (If so, maybe document that fact.)
</blockquote></details>

Hmm, I do not know an easy way to check if `snopt.out` file is created on CI. In order to do that, we need to 
1. remove `snopt.out` on CI before running the test.
2. run the test.
3. Check if CI has `snopt.out`.

I add a documentation here saying that the user can check if `snopt.out` exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by EricCousineau-TRI** [comment]
*[solvers/snopt_solver.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I6Ey1PmaSvgR4hN5O:-L6J6uDtSG2DFyk0hBPn:bxwexmj) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L702)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I basically copied the code from https://stackoverflow.com/questions/7352099/stdstring-to-char, where it adds 1 to the string length.

I think c char array has an `\0` at the end, that is not included in c++ string. As shown in the example http://en.cppreference.com/w/cpp/string/basic_string/copy
</blockquote></details>

Yes, C strings have a `\0` terminator, but that's not normally included in the string length, but rather in the buffer length.

Can I ask if `snopenappend_` takes the string length, or buffer length?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 699 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I687UOnvMUaaZ9HV7:-L6JA6w1GGWHmcKIAKMj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L699)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than `const_cast` this, can you instead copy it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 699 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I687UOnvMUaaZ9HV7:-L6JAO-BCyj-KJLemxXc:b5adh1c) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L699)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
Can you put in a quick check to ensure that the string length is under the buffer length? (and use a constant, like `buffer_len`?)

---

*[solvers/snopt_solver.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I6Ey1PmaSvgR4hN5O:-L6JAX-CMOuleGBpp4a9:b-y9u8r0) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L702)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think `snopenappend_` takes buffer length.
</blockquote></details>

That seems like it contradicts the previous code, where `strlen` is the string length (1 less than the minimum buffer length)?
Is it possible to just use `str.length()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 699 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I687UOnvMUaaZ9HV7:-L6JDQUyOVJksD3Wt9ez:b-yh16lj) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L699)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks!
Can you put in a quick check to ensure that the string length is under the buffer length? (and use a constant, like `buffer_len`?)
</blockquote></details>

Done. Good call!

---

*[solvers/snopt_solver.cc, line 702 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6I6Ey1PmaSvgR4hN5O:-L6JDUn9tGzqEhVbw6Wh:bpt2c5l) ([raw file](https://github.com/robotlocomotion/drake/blob/50613349fc05bd85f63108954d352f08270175c4/solvers/snopt_solver.cc#L702)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

That seems like it contradicts the previous code, where `strlen` is the string length (1 less than the minimum buffer length)?
Is it possible to just use `str.length()`?
</blockquote></details>

Done. I think you are right. I tried both with +1 and without. Both works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8169)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[solvers/snopt_solver.cc, line 706 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6JIkdreWQOajYjYnQb:-L6JIkdreWQOajYjYnQc:b-vk5uix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1c0cb54d39e9257d09e12ad29fb0d18e2bc068b/solvers/snopt_solver.cc#L706)):*
> ```cpp
>       throw std::logic_error(oss.str());
>     }
>     char print_file_name[kMaxFileNameLength];
> ```

When writing C++ code, doing basic string manipulation with char arrays and manual NIL termination should be viewed with skepticism, and documented why we're not using `std::string`, if there is some good reason.

I suspect what you want is a simple `std::string print_filename(*print_file_it);` or similar, and then `&print_filename[0]` to get the `char*`, similar to `snopt::snseti_(&opt[0],` from up around line 190 or so.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6JK6Wwn02TQExVy0NS:br0qryy) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think that answers what I meant to ask.  Why should this program have `if (solver.available())` sprinkled everywhere?  Why not do like most solver-dependent tests and tag it in the BUILD file, to only be run when `snopt` is enabled?  Possibly either choice is fine, but its unclear to me why this particular choice has been made.

If it will take more research, I'm OK with a follow-up issue instead of fixing it here.

---

*[solvers/test/snopt_solver_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iymgl2w7R2yoBbTyR:-L6JKWHosaCS6fE_jakg:b6pknfc) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L92)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Hmm, I do not know an easy way to check if `snopt.out` file is created on CI. In order to do that, we need to 
1. remove `snopt.out` on CI before running the test.
2. run the test.
3. Check if CI has `snopt.out`.

I add a documentation here saying that the user can check if `snopt.out` exists.
</blockquote></details>

OK Fine by me.

The way to test in CI (also works locally) is:
```c++
std::string print_file = std::string(::getenv("TEST_TMPDIR")) + "/snopt.out";
EXPECT_FALSE(spruce::path(print_file).exists());
// ... SetSolverOption; Solve ...
EXPECT_TRUE(spruce::path(print_file).exists());
```

The TEST_TMPDIR will start out empty (guaranteed), so you don't need to remove anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 706 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6JIkdreWQOajYjYnQb:-L6JPnyF1FG9GVk_Mmi0:bxrievg) ([raw file](https://github.com/robotlocomotion/drake/blob/e1c0cb54d39e9257d09e12ad29fb0d18e2bc068b/solvers/snopt_solver.cc#L706)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When writing C++ code, doing basic string manipulation with char arrays and manual NIL termination should be viewed with skepticism, and documented why we're not using `std::string`, if there is some good reason.

I suspect what you want is a simple `std::string print_filename(*print_file_it);` or similar, and then `&print_filename[0]` to get the `char*`, similar to `snopt::snseti_(&opt[0],` from up around line 190 or so.
</blockquote></details>

Done. Thanks! That looks a lot better.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6JPupJ9Xt9sEhpXfSj:bt5koov) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think that answers what I meant to ask.  Why should this program have `if (solver.available())` sprinkled everywhere?  Why not do like most solver-dependent tests and tag it in the BUILD file, to only be run when `snopt` is enabled?  Possibly either choice is fine, but its unclear to me why this particular choice has been made.

If it will take more research, I'm OK with a follow-up issue instead of fixing it here.
</blockquote></details>

I add the `solver.available()` here, in case I build the test without the snopt flag.
```
bazel build //solvers:snopt_solver_test
```
and then run the test as
```
$ ./bazel-bin/solvers/snopt_solver_test
```

In this way the build succeeds, but the test fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 702 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6JQgCG96EYJHSWz-Wm:-L6JQgCG96EYJHSWz-Wn:b94n1dk) ([raw file](https://github.com/robotlocomotion/drake/blob/4e68f4a8cbfbed3dcad0ea137fb86a5fe5d45852/solvers/snopt_solver.cc#L702)):*
> ```cpp
>     cur.iPrint = 9;
>     snopt::integer print_file_name_len =
>         static_cast<snopt::integer>(print_file_it->second.length());
> ```

FYI We could `print_file_name.length()` here, but either way is  fine.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6JR1jRPekzddzMDiIt:b-4vqyca) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I add the `solver.available()` here, in case I build the test without the snopt flag.
```
bazel build //solvers:snopt_solver_test
```
and then run the test as
```
$ ./bazel-bin/solvers/snopt_solver_test
```

In this way the build succeeds, but the test fails.
</blockquote></details>

I'm not understanding.  With the if-available guard, this test will pass even when snopt is off.  You're saying you want it to pass even when run by hand, including to have it trivially pass when SNOPT is unavailable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 702 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6JQgCG96EYJHSWz-Wm:-L6JXF6OyMNAevSoVib6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4e68f4a8cbfbed3dcad0ea137fb86a5fe5d45852/solvers/snopt_solver.cc#L702)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI We could `print_file_name.length()` here, but either way is  fine.
</blockquote></details>

Done.

---

*[solvers/test/snopt_solver_test.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iy9q8pjFYDpmIwqKk:-L6JXA06U5rJsJbMNNQF:bshwqoj) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not understanding.  With the if-available guard, this test will pass even when snopt is off.  You're saying you want it to pass even when run by hand, including to have it trivially pass when SNOPT is unavailable?
</blockquote></details>

Done. You are right. I should not expect the test to pass when `SNOPT` is unavailable.

---

*[solvers/test/snopt_solver_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-L6Iymgl2w7R2yoBbTyR:-L6JX8t8QqTw_UT3rQD7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/985332bf2fc98e6fbd0dcc3c7e6c68c95bfba057/solvers/test/snopt_solver_test.cc#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Fine by me.

The way to test in CI (also works locally) is:
```c++
std::string print_file = std::string(::getenv("TEST_TMPDIR")) + "/snopt.out";
EXPECT_FALSE(spruce::path(print_file).exists());
// ... SetSolverOption; Solve ...
EXPECT_TRUE(spruce::path(print_file).exists());
```

The TEST_TMPDIR will start out empty (guaranteed), so you don't need to remove anything.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-:-L6JZqrfpJbDwPEBSS70:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169#-:-L6K1v7YieJqlpKoZBRD:b-l70wzf)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8169)*

**Pull request merged**
