### PR TITLE
[multibody] Establish detail_mujoco_parser.

### PR DESCRIPTION
**Pull request by RussTedrake**
First step towards #16369.

This PR simply establishes the class and the test files. The following
PRs will start adding more meaningful functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with a couple of nits.  For the `.xml` assets, I verified that there are no changes from the upstream source in `LICENSE.txt` but didn't inspect the contents.

+@ericcousineau-tri for platform review.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtJVsh39N8cIQDGdMBB:bqfqtk4)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[multibody/models/mujoco_gym/LICENSE.txt, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJRC0N2xINmZy_R-ac:-MtJRC0N2xINmZy_R-ad:b-ysd4r8) ([raw file](https://github.com/robotlocomotion/drake/blob/aa34a142a4b1310d3a7572801f77b6166a45b240/multibody/models/mujoco_gym/LICENSE.txt#L1)):*
> ```help
> The files in this directory were taken from openai/gym's [MuJoCo models](https://github.com/openai/gym/tree/8a96440084a6b9be66b2216b984a1c170e4a061c/gym/envs/mujoco).  
> ```

nit: This would probably render more nicely when viewed through github if the file had a `.md` extension?
___
*[multibody/parsing/detail_mujoco_parser.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJSV3zARgWQHVA5gfH:-MtJSV3zARgWQHVA5gfI:b1vz5bq) ([raw file](https://github.com/robotlocomotion/drake/blob/aa34a142a4b1310d3a7572801f77b6166a45b240/multibody/parsing/detail_mujoco_parser.cc#L19)):*
> ```cpp
> using geometry::GeometryInstance;
> using math::RigidTransformd;
> using math::RotationMatrixd;
> ```

nit: All of these `using` statements (except for the `tinyxml2` ones are unused), same for everything but `SceneGraph` in the test file.   If they're just coming back in the next PR in the series, we can probably leave this as it.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @sammy-tri)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJSV3zARgWQHVA5gfH:-MtJWsaSClbwxhtfYA-I:b-udo2w7) ([raw file](https://github.com/robotlocomotion/drake/blob/aa34a142a4b1310d3a7572801f77b6166a45b240/multibody/parsing/detail_mujoco_parser.cc#L19)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: All of these `using` statements (except for the `tinyxml2` ones are unused), same for everything but `SceneGraph` in the test file.   If they're just coming back in the next PR in the series, we can probably leave this as it.
</blockquote></details>

You got it.  They are coming back/cleaned up in the next PR (I realized it after).  I'll take you up on it being ok to leave them, just to save myself one merge conflict.
___
*[multibody/models/mujoco_gym/LICENSE.txt, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJRC0N2xINmZy_R-ac:-MtJXUtr6FIloRuPXNLw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa34a142a4b1310d3a7572801f77b6166a45b240/multibody/models/mujoco_gym/LICENSE.txt#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: This would probably render more nicely when viewed through github if the file had a `.md` extension?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
I did a build/license check and posted below.  I'll still leave Eric to handle platform review of the code.

> Reviewed 2 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtJ_35-Do0D4YqMgKi1:bps9cy6)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @RussTedrake, and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJZVUn4RE45jFkUY3w:-MtJZVUn4RE45jFkUY3x:bczl4p0) (no related file):*
The LICENSE file for the vendored test data has two parts -- the MIT license for Gym, and then the "Models" section at the bottom.  Which one (or both) applies to these copied files?

The MIT license is fine, of course.

The "This work is derived from MuJuCo models used under the following license:" section does not contain any grant of rights, though, so on first appearance, we cannot use files covered by those terms.

---
___
*[multibody/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJXjeG2enLH59PetcO:-MtJXjeICPcDzJKSGqIy:b1shz19) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/BUILD.bazel#L12)):*
> ```Starlark
>         "models/box.urdf",
>         "models/box_small.urdf",
>     ] + glob(["models/mujoco_gym/*.xml"]),
> ```

The `multibody/models` is vestigial and is probably an incorrect pattern to replicate.

Are these models going to be only used for tests (versus shipping them in production releases)?  If test-only, then they need to have the word "test" appear in part of the full directory name.  So `multibody/test_models` or more likely `multibody/parsing/test/mujoco_gym`?

For clarity of dependencies, we should also not mingle SDFormat models and MuJoCo models under the same bazel label.
___
*[multibody/models/mujoco_gym/LICENSE.md, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJZBHo-AKET_vXvT0V:-MtJZBHpBMtaS_7lac63:b-4cj4rr) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/models/mujoco_gym/LICENSE.md#L1)):*
> ```Markdown
> The files in this directory were taken from openai/gym's [MuJoCo models](https://github.com/openai/gym/tree/8a96440084a6b9be66b2216b984a1c170e4a061c/gym/envs/mujoco).  
> ```

nit Trailing whitespace.
___
*[multibody/models/mujoco_gym/LICENSE.md, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJZDUb49dULoHp9bLp:-MtJZDUc2RCxzjrq8ueu:braxi2f) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/models/mujoco_gym/LICENSE.md#L4)):*
> ```Markdown
> 
> They are redistributed under the following license:
> https://github.com/openai/gym/blob/8a96440084a6b9be66b2216b984a1c170e4a061c/LICENSE.md
> ```

We need to copy-paste the license text into our git.  The URL is still good to keep if you like, but we can't rely on the URL existing indefinitely when trying to track down the license.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[multibody/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJXjeG2enLH59PetcO:-MtJbNG3BS-4KXAvnLis:b-fouk7m) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/BUILD.bazel#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `multibody/models` is vestigial and is probably an incorrect pattern to replicate.

Are these models going to be only used for tests (versus shipping them in production releases)?  If test-only, then they need to have the word "test" appear in part of the full directory name.  So `multibody/test_models` or more likely `multibody/parsing/test/mujoco_gym`?

For clarity of dependencies, we should also not mingle SDFormat models and MuJoCo models under the same bazel label.
</blockquote></details>

(Also, if they are for tests only, then they should be marked `testonly = True`.)

**Review by EricCousineau-TRI — COMMENTED** [review]
LGTM platform pending Jeremy's comments.

> Reviewed 18 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtK07OE9_kX0LPjv-bN:bcx7c9b)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtK-rrWDlzCauI03kWJ:-MtK-rrWDlzCauI03kWK:b-jbqgdu) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/parsing/detail_mujoco_parser.cc#L32)):*
> ```cpp
>     drake::log()->warn(
>         "The tag '{}' found in MuJoCo XML is currently unsupported and will be "
>         "ignored.",
> ```

nit Consider referencing Drake issue so that users could see support plan.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJXjeG2enLH59PetcO:-MtK3Cl85qbvi7DQdNwt:b1k7glq) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/BUILD.bazel#L12)):*
One option:

An email from the author of the files, saying something like this:

> The Mujoco models downloaded from https://github.com/openai/gym may be used under the terms of the FOO_NAME license at FOO_URL.

e.g.
FOO_NAME = Apache-2.0
FOO_URL = https://spdx.org/licenses/Apache-2.0.html
FOO_NAME = MIT
FOO_URL = https://spdx.org/licenses/MIT.html

We would then paste that email in into the LICENSE / README for the test models folder.

Ideally, this information would _also_ be posted on the github website where they came from, but for the purposes of Drake, an archive of the email should be sufficient.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtK-rrWDlzCauI03kWJ:-MtKFtY5A7az9z3uzua8:b-xpvjp5) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/parsing/detail_mujoco_parser.cc#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider referencing Drake issue so that users could see support plan.
</blockquote></details>

There are no users: I've scoped it's visibility in bazel.  Plus the follow-up PRs are queued up and waiting.  (I wouldn't mind doing it for this one, but it would make sense to do it everywhere if anywhere and that seems too much).

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @RussTedrake, and @sammy-tri)

___
*[multibody/models/mujoco_gym/LICENSE.md, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJZDUb49dULoHp9bLp:-MtKHwzC3UKuDJMtAdZg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/models/mujoco_gym/LICENSE.md#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We need to copy-paste the license text into our git.  The URL is still good to keep if you like, but we can't rely on the URL existing indefinitely when trying to track down the license.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @RussTedrake, and @sammy-tri)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtK-rrWDlzCauI03kWJ:-MtKI8Ru56bY71muGy43:b-c8abvi) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/parsing/detail_mujoco_parser.cc#L32)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

There are no users: I've scoped it's visibility in bazel.  Plus the follow-up PRs are queued up and waiting.  (I wouldn't mind doing it for this one, but it would make sense to do it everywhere if anywhere and that seems too much).
</blockquote></details>

OK Ah, thanks for explaining!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @RussTedrake, and @sammy-tri)

___
*[multibody/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJXjeG2enLH59PetcO:-MtKLkz83K58BgynSuo4:b-xehsbf) ([raw file](https://github.com/robotlocomotion/drake/blob/05379c8cdb706c09ca75db7826986e3877bff614/multibody/BUILD.bazel#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One option:

An email from the author of the files, saying something like this:

> The Mujoco models downloaded from https://github.com/openai/gym may be used under the terms of the FOO_NAME license at FOO_URL.

e.g.
FOO_NAME = Apache-2.0
FOO_URL = https://spdx.org/licenses/Apache-2.0.html
FOO_NAME = MIT
FOO_URL = https://spdx.org/licenses/MIT.html

We would then paste that email in into the LICENSE / README for the test models folder.

Ideally, this information would _also_ be posted on the github website where they came from, but for the purposes of Drake, an archive of the email should be sufficient.
</blockquote></details>

(As you can probably guess, in my hurry, I posted my license comment above into the wrong thread.  It was meant for the other one, atop the PR.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @RussTedrake, and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtJZVUn4RE45jFkUY3w:-MtN4DCo2XrEr7diFAhg:b4t06a3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The LICENSE file for the vendored test data has two parts -- the MIT license for Gym, and then the "Models" section at the bottom.  Which one (or both) applies to these copied files?

The MIT license is fine, of course.

The "This work is derived from MuJuCo models used under the following license:" section does not contain any grant of rights, though, so on first appearance, we cannot use files covered by those terms.
</blockquote></details>

I've replaced the openAI-gym examples with the https://github.com/deepmind/dm_control/tree/master/dm_control/suite , and added it as an external instead of copying the files (per discussion w/ @jwnimmer-tri ).

+@jwnimmer-tri for review of this change, please.

---

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @RussTedrake, and @sammy-tri)

___
*[tools/workspace/dm_control/package.BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16370#-MtN4LqM3pHRpSH2CC_J:-MtN4LqM3pHRpSH2CC_K:b-f94t0m) ([raw file](https://github.com/robotlocomotion/drake/blob/49faddd79cc5e99559cc9af3d7cf0d65fba2d689/tools/workspace/dm_control/package.BUILD.bazel#L11)):*
> ```
>         "dm_control/suite/common/*.xml",
>     ] + ["LICENSE"], allow_empty = False),
>     visibility = ["//visibility:public"],
> ```

btw -- i tried restricting the scope here to `@drake//multibody/parsing:__pkg__` and similar, but couldn't get it to work.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: -- I reviewed everything except for the C++ code.

> Reviewed 1 of 4 files at r3, 6 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtO7lz44EQT7JKsIzJw:b-8xmc7x)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
-(release notes: none) +(release notes: yes) because we should mention the new workspace item (for users who build from source and need to mirror any new dependencies, even if testonly.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtO7vkn05SzEJkssAEE:batu2x4)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
Thank you.  I think everyone has blessed the c++, and given the lgtm conditional on Jeremy, so I'm going to merge.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16370#-:-MtOAqH9AMYxGn0Hk5Bw:b-o2lsh2)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @sammy-tri)

**Pull request merged**
