### PR TITLE
Begin extracting drake/math/quaternion.h from drakeGeometryUtil.h.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2664)

### CODE REVIEW

**Comment by sherm1** [comment]
Made a review pass.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/quaternion.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJ8wt92Vq4V19WpUOp:-KLJ8wtAkyrKFLQU3aAP:-1750265678) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/math/quaternion.h#L12)):*
> ```objc
> 
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 4, 1> quatConjugate(
> ```

BTW, should include `eigen_types.h` and return Vector4<typename Derived::Scalar>.
(Actually I think that one is missing but Vector3 is there so this would be a good add.)

I'm leaving this optional in case you want to restrict this PR to copy-and-pasting. But it would be nice to clean this up a little while you're there!

---

*[drake/math/quaternion.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJA1me75UfgIHb1sHf:-KLJA1me75UfgIHb1sHg:286257291) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/math/quaternion.h#L49)):*
> ```objc
> 
>   typedef Matrix<typename DerivedV::Scalar, 4, 1> Vector4;
>   typedef Matrix<typename DerivedV::Scalar, 3, 1> Vector3;
> ```

This makes it worse since these are the same names as in eigen_types.h but have (slightly) different meanings.

---

*[drake/util/drakeGeometryUtil.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJAgsBYJpfTToYlmYq:-KLJAgsBYJpfTToYlmYr:475979041) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/util/drakeGeometryUtil.h#L44)):*
> ```objc
>  */
> template <typename Derived1, typename Derived2, typename Scalar>
> Eigen::Matrix<Scalar, 4, 1> slerp(const Eigen::MatrixBase<Derived1>& q1,
> ```

slerp() is a quaternion method and ought to go with the quaternion code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-:-KLJAucC8S3l25-bPzYm:-1424681478)*

**Comment by david-german-tri** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/quaternion.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJ8wt92Vq4V19WpUOp:-KLJCmXsrGw-V0iP9dRq:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/math/quaternion.h#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, should include `eigen_types.h` and return Vector4<typename Derived::Scalar>.
> (Actually I think that one is missing but Vector3 is there so this would be a good add.)
> 
> I'm leaving this optional in case you want to restrict this PR to copy-and-pasting. But it would be nice to clean this up a little while you're there!
</details>
Done.

---

*[drake/math/quaternion.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJA1me75UfgIHb1sHf:-KLJCe4dvXQPukja_OE9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/math/quaternion.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This makes it worse since these are the same names as in eigen_types.h but have (slightly) different meanings.
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJAgsBYJpfTToYlmYq:-KLJDUCnbzf2p1B4s7yo:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8459fae0992bf00f9c315b9a18435ab092640ea3/drake/util/drakeGeometryUtil.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> slerp() is a quaternion method and ought to go with the quaternion code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664)*

**Comment by jwnimmer-tri** [comment]
:lgtm: with one easily-resolved nit.

(For the record of course, the code that got moved has many defects, but this doesn't make them any worse.)

---

Reviewed 5 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/quaternion.h, line 79 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJHDs-5IwEiMY9cJpC:-KLJHDs-5IwEiMY9cJpD:-1988174426) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L79)):*
> ```objc
> template <typename Derived>
> typename Derived::Scalar quatNorm(const Eigen::MatrixBase<Derived>& q) {
>   return std::acos(q(0));
> ```

Missing `#include <cmath>` for `std::cos`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-:-KLJHfLz6JhskIiS2EzW:-1574854700)*

**Comment by sherm1** [comment]
:lgtm: with a few minor comment-comments.

---

Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/math/quaternion.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJOaNSc6D8YyKGb7gc:-KLJOaNTpUmBHzqzF7p2:1106559492) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L84)):*
> ```objc
> /*
>  * Q = Slerp(q1, q2, f) Spherical linear interpolation between two quaternions
>  *   This function uses the implementation given in Algorithm 8 of [1].
> ```

This is a nice comment but needs to start with `/**` so users can read it!

---

*[drake/math/quaternion.h, line 88 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJPQJ60DGTmY8gmeuw:-KLJPQJ60DGTmY8gmeux:8648674) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L88)):*
> ```objc
>  * @param q1   Initial quaternion (w, x, y, z)
>  * @param q2   Final quaternion (w, x, y, z)
>  * @param f    Interpolation parameter between 0 and 1 (inclusive)
> ```

param name f is wrong here

---

*[drake/math/quaternion.h, line 91 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJOmdDSF8lWDNzlDnz:-KLJOmdDSF8lWDNzlDo-:1405624022) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L91)):*
> ```objc
>  * @retval Q   Interpolated quaternion(s). 4-by-1 vector.
>  *
>  * [1] Kuffner, J.J., "Effective sampling and distance metrics for 3D rigid
> ```

BTW, look who the author is on this reference!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-:-KLJQB-dnsAg-EwYS4MG:-662280913)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/quaternion.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJOaNSc6D8YyKGb7gc:-KLJUmkgvxI4G7IsNxpA:1821759238) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L84)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is a nice comment but needs to start with `/**` so users can read it!
</details>
BTW I noticed that too, but I don't think that level of technical debt payoff appropriate for code-shuffling PRs.  I think it's important, for PRs like this one, that the new code and old code are virtually identical, without any embellishments from this PR's author.  We shouldn't be taking on new risk with these kinds of refactorings; that risk should be in other PRs, where the change can be inspected more carefully.  Same for the doxygen typo below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/quaternion.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJOaNSc6D8YyKGb7gc:-KLKFkVi1Hx7RiXZdeqx:573218441) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I noticed that too, but I don't think that level of technical debt payoff appropriate for code-shuffling PRs.  I think it's important, for PRs like this one, that the new code and old code are virtually identical, without any embellishments from this PR's author.  We shouldn't be taking on new risk with these kinds of refactorings; that risk should be in other PRs, where the change can be inspected more carefully.  Same for the doxygen typo below.
</details>
In general I agree, but I think fixing a comment is in scope here and risk free. We're unlikely to get another look at this code any time soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/quaternion.h, line 79 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJHDs-5IwEiMY9cJpC:-KLMFYlgh-JYM1XlfOl8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing `#include <cmath>` for `std::cos`.
</details>
Done.

---

*[drake/math/quaternion.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJOaNSc6D8YyKGb7gc:-KLMFaSvUsMnhxr0wesh:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L84)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> In general I agree, but I think fixing a comment is in scope here and risk free. We're unlikely to get another look at this code any time soon.
</details>
Done.

---

*[drake/math/quaternion.h, line 88 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2664#-KLJPQJ60DGTmY8gmeuw:-KLMFgopm63-BZ_lKeSK:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7484474e2ce1fd09c049c0e7331a0db165037049/drake/math/quaternion.h#L88)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> param name f is wrong here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2664)*

**Pull request merged**
