### PR TITLE
trajectories: Switch to Sparse solver for constructing CubicWithContinuousSecondDerivatives

### PR DESCRIPTION
**Pull request by mpetersen94**
Also, switches from using 4 constraints per knot point to only 3 constraints per knot point by removing the trivial constraint that the constant term is equal to the knot point location.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake or @siyuanfeng-tri for feature review.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@siyuanfeng-tri 

(I'm explicitly assigning this to @siyuanfeng-tri and he can pass it along if this assignment isn't appropriate.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdIBY0w29P17rkU_hwk:bbcp42q)* status: LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siyuanfeng-tri)

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Review by siyuanfeng-tri — COMMENTED** [review]
thanks! minor comments. i am curious if you have done a speed check for the sparse solver?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdIPtI0AG2P5fMkXTZH:b-3tfbcf)* status: 2 unresolved discussions, LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

___
*[common/trajectories/piecewise_polynomial.cc, line 827 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIP2H34VqNVfoM9IhG:-MdIP2H42_2cWM7TN4pS:b-9g1vh) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7837a6bd278e9008ee558baaf4b1962d44c7ae/common/trajectories/piecewise_polynomial.cc#L827)):*
> ```cpp
>   int row_idx = 0;
>   std::vector<Eigen::Triplet<T>>& triplet_ref = *triplet_list;
>   VectorX<T>& bref = *b;
> ```

nit, should we set bref[0] = 0 to be extra safe?
___
*[common/trajectories/piecewise_polynomial.cc, line 908 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIPkmJ2_yj88Tce8aF:-MdIPkmJ2_yj88Tce8aG:b-cg591k) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7837a6bd278e9008ee558baaf4b1962d44c7ae/common/trajectories/piecewise_polynomial.cc#L908)):*
> ```cpp
>     for (int k = 0; k < cols; ++k) {
>       std::vector<Eigen::Triplet<T>> triplet_list;
>       triplet_list.reserve(10 * (N - 2) + 7);
> ```

can you add a comment to how this capacity is computed? thanks!

**Comment by siyuanfeng-tri** [comment]
also i am in a shanghai timezone, so i won't make comments blocking, feel free to move to platform.

**Review by mpetersen94 — COMMENTED** [review]
I did do a rough speed check and for a PiecewisePolynomial generated from 100 knot points (each of size 10), the sparse solver was 100 times faster.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdITvM2A6jEx7dlN0WB:bcoubvt)* status: 1 unresolved discussion, LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siyuanfeng-tri)

___
*[common/trajectories/piecewise_polynomial.cc, line 827 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIP2H34VqNVfoM9IhG:-MdIRO5P0rUMQkJuvAG7:bh8n8y5) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7837a6bd278e9008ee558baaf4b1962d44c7ae/common/trajectories/piecewise_polynomial.cc#L827)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

nit, should we set bref[0] = 0 to be extra safe?
</blockquote></details>

I don't understand what that would do.  Is the concern what the behavior is if `N-1 == 0`?
___
*[common/trajectories/piecewise_polynomial.cc, line 908 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIPkmJ2_yj88Tce8aF:-MdITqPV76gNKOaOeaAJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7837a6bd278e9008ee558baaf4b1962d44c7ae/common/trajectories/piecewise_polynomial.cc#L908)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you add a comment to how this capacity is computed? thanks!
</blockquote></details>

Done.

**Comment by mpetersen94** [comment]
@SeanCurtis-TRI for platform review

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm relying on feature review and existing unit tests to feel completely confident. Otherwise: :LGTM:

(With one note about documentation.)

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdIfBfT-5RW4VYTqd_y:b-zd2cgj)* status: 2 unresolved discussions, LGTM missing from assignee siyuanfeng-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94 and @siyuanfeng-tri)

___
*[common/trajectories/piecewise_polynomial.h, line 825 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIdY7m7RpUeR908ybN:-MdIdY7m7RpUeR908ybO:ba59oic) ([raw file](https://github.com/robotlocomotion/drake/blob/4550c8c05679c1c7c436ea58eb01e5a603ebeec5/common/trajectories/piecewise_polynomial.h#L825)):*
> ```objc
>       const std::vector<T>& breaks,
>       const std::vector<MatrixX<T>>& samples, int row, int col,
>       std::vector<Eigen::Triplet<T>>* triplet_list, VectorX<T>* b);
> ```

BTW I find it highly disturbing that the signature can change this much and yet, the documentation doesn't change at all. We've change from `A` to `triplet_list` and changed the semantics of `b` -- neither are documented.

Part of that is that A and b were never documented prior to this change. It would be kind of nice if this were shored up and the semantics of these parameters were included in the documentation.

However, as this is not a defect introduced by this PR, you're not obliged to correct it.

**Review by mpetersen94 — COMMENTED** [review]
When this is ready to merge, it would be nice if we do not squash to maintain the sequence of changes in the commit history.  The commits are properly curated with that goal in mind.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdJAolr0dZtuGb2-e93:bgw8huf)* status: 2 unresolved discussions, LGTM missing from assignee siyuanfeng-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @siyuanfeng-tri)

___
*[common/trajectories/piecewise_polynomial.h, line 825 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIdY7m7RpUeR908ybN:-MdJAhqKApwwddDoXKSq:b-a8xudf) ([raw file](https://github.com/robotlocomotion/drake/blob/4550c8c05679c1c7c436ea58eb01e5a603ebeec5/common/trajectories/piecewise_polynomial.h#L825)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I find it highly disturbing that the signature can change this much and yet, the documentation doesn't change at all. We've change from `A` to `triplet_list` and changed the semantics of `b` -- neither are documented.

Part of that is that A and b were never documented prior to this change. It would be kind of nice if this were shored up and the semantics of these parameters were included in the documentation.

However, as this is not a defect introduced by this PR, you're not obliged to correct it.
</blockquote></details>

I took a stab at the documentation. PTAL.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've tested the commits, they seem well curated. We'll merge accordingly.

@siyuanfeng-tri, we're missing the `lgtm` from you.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdJEWUl-R041iL8jwGk:b-uexwzb)* status: 1 unresolved discussion, LGTM missing from assignee siyuanfeng-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siyuanfeng-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: do not merge) (we're going to merge with curated commits. We don't want anyone accidentally merging until we're ready.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdJEmcBAVgfFbWHwnED:b-mw6mxo)* status: 1 unresolved discussion, LGTM missing from assignee siyuanfeng-tri, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdL55K5CR985oXe0wSo:bg7igkv)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

___
*[common/trajectories/piecewise_polynomial.cc, line 827 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15248#-MdIP2H34VqNVfoM9IhG:-MdL4dcO94R3v7KVNqxT:b54me7p) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7837a6bd278e9008ee558baaf4b1962d44c7ae/common/trajectories/piecewise_polynomial.cc#L827)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I don't understand what that would do.  Is the concern what the behavior is if `N-1 == 0`?
</blockquote></details>

i just wanted to make sure we don't have uninitialized memory, and i think we are fine here after looking at it more.

**Review by siyuanfeng-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

**Comment by mpetersen94** [comment]
@SeanCurtis-TRI Can you add the right label and merge this now?

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) +(status: commits are properly curated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15248#-:-MdN3J6m40dNN35cH7aK:b-um2lrk)* status: labeled "do not merge" (waiting on @mpetersen94)

**Pull request merged**
