### PR TITLE
python: Exclude third-party headers

### LINKED ISSUE #8840: python: `@python` C libraries may bring in system-installed `numpy` headers; exclude these
We found in Anzu that if a user does not have system-installed NumPy, but a `pip` installed NumPy, then our builds fail. This was simply because we did not specify `@numpy` dependencies.

However, @jwnimmer-tri found that `@python` may include system-installed NumPy headers due to its globbing. We should exclude these.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8840

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8841)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

Please test macOS CI before merging.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/python/repository.bzl, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2SZ8CCh0aJl5rXHL0:-LD2SZ8CCh0aJl5rXHL1:b-r3qgdj) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L100)):*
> ```Python
> 
> # Exclude a given set of non-system third-party libraries that Ubuntu may
> # overlay with the system Python install.
> ```

BTW The phrase "non-system" doesn't seem right.  These _are_ installed via Ubuntu, that just aren't part of _Python_.

---

*[tools/workspace/python/repository.bzl, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2Sgim9KTimlhuyYCY:-LD2Sgim9KTimlhuyYCZ:b-oubx7) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L102)):*
> ```Python
> # overlay with the system Python install.
> headers = glob(
>     ["include/**"],
> ```

FYI My intuition would be to do `include/*` only (no recursion) and then `exclude_directories = `1, though this way seems OK also.

---

*[tools/workspace/python/repository.bzl, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2SOmc4eeUXshYFwRe:-LD2SOmc4eeUXshYFwRf:b-n6h2p7) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L106)):*
> ```Python
>         "**/mpi4py/**",
>         "**/numpy/**",
>         "**/pygame/**",
> ```

FYI Do we want `**/numpy` etc or just `include/numpy/**` to be excluded?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8841#-:-LD2SBzP5BVFGpouIsa5:b-se2fii)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/workspace/python/repository.bzl, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2SZ8CCh0aJl5rXHL0:-LD3fJDlBzGepEKdLWOE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The phrase "non-system" doesn't seem right.  These _are_ installed via Ubuntu, that just aren't part of _Python_.
</blockquote></details>

Done.

---

*[tools/workspace/python/repository.bzl, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2Sgim9KTimlhuyYCY:-LD3fHVW0wIXvorH1YAZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI My intuition would be to do `include/*` only (no recursion) and then `exclude_directories = `1, though this way seems OK also.
</blockquote></details>

Done.

---

*[tools/workspace/python/repository.bzl, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8841#-LD2SOmc4eeUXshYFwRe:-LD3fHvo4NXqce5mNOLC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81866a88921c6e22a525e8166351a5c878dc1016/tools/workspace/python/repository.bzl#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Do we want `**/numpy` etc or just `include/numpy/**` to be excluded?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8841)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8841)*

**Pull request merged**
