### PR TITLE
[examples] Add main and yaml parsing to python hardware_sim

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17112.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18566)

### CODE REVIEW

**Comment by sherm1** [comment]
Do you have a feature reviewer in mind for this?

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

There are some quite unique bazel gymnastics in play here. In a couple of cases, I've asked some questions to improve my understanding (i.e., things I simply couldn't figure out of my own). In a couple of other cases, I've requested some captured explanation of some of the others. (And the requisite typo or two.)

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-:-NM9u5Jx2HCjnUuo2tlE:b-ear6nj)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/BUILD.bazel` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9mTUN6iGObiZ5N0Uu:-NM9mTUN6iGObiZ5N0Uv:ba86xze) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L25)):*
> ```Starlark
>     name = "demo_data",
>     srcs = [
>         "test/test_scenarios.yaml",
> ```

BTW Why is this yaml file a source when the others are data?
___
*[`examples/hardware_sim/BUILD.bazel` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9rQRW97pIAnc_Gb0F:-NM9rQRX1FJY-7w3xAEd:b-y6mq20) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L96)):*
> ```Starlark
>     name = "hardware_sim_cc_test",
>     data = [":demo_cc"],
>     env = {"EXE_LANG": "cc"},
> ```

The environment variable (and on the test of the python implementation) could benefit from a cross reference to the python file. Otherwise the "EXE_LANG" looks more "official" than it is. 

I also wonder if it isn't worth picking a more verbose but obviously bespoke name: `DRKAE_HARDWARE_TEST_LANG` (or some such thing).
___
*[`examples/hardware_sim/BUILD.bazel` line 123 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9nx-J1Fz1-J5UKAyJ:-NM9nx-J1Fz1-J5UKAyK:bjtzkrm) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L123)):*
> ```Starlark
>     data = [
>         ":demo_data",
>         ":hardware_sim_py",
> ```

BTW Similar question. What is the significance of a `py_binary` being data and not a dependency?
___
*[`examples/hardware_sim/BUILD.bazel` line 130 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9tQxGDC9MjZosTExV:-NM9tQxGDC9MjZosTExW:bkr60u6) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L130)):*
> ```Starlark
> )
> 
> drake_py_unittest(
> ```

nit: The whole simlink thing was a bit unexpected. Presumably, it's the easiest way to have a target *named* `hardware_sim_py_test` (empahsis on py), looking like a python unittest in the bazel file but still satisfying the need that the target name must match a file name.

That's sufficiently exotic to merit documentation.
___
*[`examples/hardware_sim/hardware_sim.py` line 105 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9oYTR-MBPUAjCL7DU:-NM9oYTS5SPohkW9d-9g:bawrpef) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/hardware_sim.py#L105)):*
> ```Python
> 
> def _load_scenario(*, filename, scenario_name, scenario_text):
>     """Implements the comamnd-line handling logic for scenario data.
> ```

nit s/comamnd/command
___
*[`examples/hardware_sim/hardware_sim.py` line 188 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9q_RZ9oFVN6WG4OnA:-NM9q_RZ9oFVN6WG4OnB:bodhs1r) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/hardware_sim.py#L188)):*
> ```Python
>     parser.add_argument(
>         "--scenario_text", default="{}",
>         help="Additional YAML scenario text to load, in order to override "
> ```

BTW This seems particularly esoteric. Coming at this demo relatively ignorant, I'm left quite unsure exactly how I would use this parameter. E.g., "overriding a value" etc. Given this is an example, perhaps spelling out the utility of this parameter a bit more explicitly would serve a greater pedagogical role (i.e., in the README.md) .
___
*[`examples/hardware_sim/test/hardware_sim_py_test.py` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9sYd_CpSeYOy5SA62:-NM9sYd_CpSeYOy5SA63:bt43gy) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/test/hardware_sim_py_test.py#L1)):*
> ```Python
> hardware_sim_cc_test.py
> ```

BTW Reviewable really doesn't like changing files for simlinks. Confuses the heck out of it. It took some legwork to figure out what this meant.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18566)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`examples/hardware_sim/BUILD.bazel` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9mTUN6iGObiZ5N0Uu:-NMA6E_UASQDvpJNopiD:b2q45x4) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Why is this yaml file a source when the others are data?
</blockquote></details>

My mistake.  Shrapel from lots of rebasing.
___
*[`examples/hardware_sim/BUILD.bazel` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9rQRW97pIAnc_Gb0F:-NMA6XJ--5e3ZKE8Et77:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L96)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The environment variable (and on the test of the python implementation) could benefit from a cross reference to the python file. Otherwise the "EXE_LANG" looks more "official" than it is. 

I also wonder if it isn't worth picking a more verbose but obviously bespoke name: `DRKAE_HARDWARE_TEST_LANG` (or some such thing).
</blockquote></details>

Done.
___
*[`examples/hardware_sim/BUILD.bazel` line 123 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9nx-J1Fz1-J5UKAyJ:-NMAGj0gCUMUOKeWB3Wv:btwibjm) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L123)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Similar question. What is the significance of a `py_binary` being data and not a dependency?
</blockquote></details>

When declaring a `py_binary` rule, the `deps` are for other `py_library` things that we will call `import` on.  The same holds when writing a `py_library` or `py_unittest` rule -- the deps are the things we'll import.

(This is exactly like in C++ where we use `deps` to refer to `cc_library` things that we `#include.)

By contrast, `data` is for things we open directly ourselves, e.g., via runfiles, or `FindResourceOrThrow`, or `subprocess.call(pathname)`, etc.

Thus the `data` can refer to almost any kind of thing, whereas `deps` must always be libraries.
___
*[`examples/hardware_sim/BUILD.bazel` line 130 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9tQxGDC9MjZosTExV:-NMAGcdm4a5gu8ZWp9iD:be9frsy) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L130)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The whole simlink thing was a bit unexpected. Presumably, it's the easiest way to have a target *named* `hardware_sim_py_test` (empahsis on py), looking like a python unittest in the bazel file but still satisfying the need that the target name must match a file name.

That's sufficiently exotic to merit documentation.
</blockquote></details>

Done.  I was able to find a more natural way to reuse the code.
___
*[`examples/hardware_sim/hardware_sim.py` line 188 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9q_RZ9oFVN6WG4OnA:-NMAHc-ICKGta5wbBZkg:b-j3fr4k) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/hardware_sim.py#L188)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This seems particularly esoteric. Coming at this demo relatively ignorant, I'm left quite unsure exactly how I would use this parameter. E.g., "overriding a value" etc. Given this is an example, perhaps spelling out the utility of this parameter a bit more explicitly would serve a greater pedagogical role (i.e., in the README.md) .
</blockquote></details>

Done (via TODO).

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-:-NMASIuv3kfZv29ATKU6:bnfp4nl)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18566)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/BUILD.bazel` line 123 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18566#-NM9nx-J1Fz1-J5UKAyJ:-NMATQnICZ5nrmpO-WFs:b-g6llej) ([raw file](https://github.com/RobotLocomotion/drake/blob/db49b0c5092721f4dc473d9392ee7064268c158a/examples/hardware_sim/BUILD.bazel#L123)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When declaring a `py_binary` rule, the `deps` are for other `py_library` things that we will call `import` on.  The same holds when writing a `py_library` or `py_unittest` rule -- the deps are the things we'll import.

(This is exactly like in C++ where we use `deps` to refer to `cc_library` things that we `#include.)

By contrast, `data` is for things we open directly ourselves, e.g., via runfiles, or `FindResourceOrThrow`, or `subprocess.call(pathname)`, etc.

Thus the `data` can refer to almost any kind of thing, whereas `deps` must always be libraries.
</blockquote></details>

Makes sense. Thanks.

**Pull request merged**
