### PR TITLE
Create SpatialInertia::SolidSphereWithMass() and HollowSphereWithMass().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
PR #19268 helps resolve part of issue #18416.
Also +@rpoyner-tri  for possible use with pending PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTppUWZ4AuQsYreBsXL:b21hxgw)* status: LGTM missing from assignees sherm1(platform),rpoyner-tri(platform) (waiting on @rpoyner-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
The call sites look SO much better!
Feature :lgtm: with a few minor comments, ptal

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTtriCR8zchmZmESYs6:boby680)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @mitiguy and @rpoyner-tri)

___
*[`multibody/tree/spatial_inertia.h` line 312 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtpfm40s7cmF1pn9kS:-NTtpfm40s7cmF1pn9kT:bhyfnzo) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.h#L312)):*
> ```objc
>   /// frame B is equal to M_BBo expressed in an arbitrary frame E.
>   /// @note B's rotational inertia about Bo is triaxially symmetric, meaning
>   /// B's has an equal moment of inertia about any line passing through Bo.
> ```

typo: B's -> B
___
*[`multibody/tree/spatial_inertia.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtplzQ27IjP9GvOVi4:-NTtplzQ27IjP9GvOVi5:bhyfnzo) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.h#L341)):*
> ```objc
>   /// frame B is equal to M_BBo expressed in an arbitrary frame E.
>   /// @note B's rotational inertia about Bo is triaxially symmetric, meaning
>   /// B's has an equal moment of inertia about any line passing through Bo.
> ```

typo: B's -> B
___
*[`multibody/tree/spatial_inertia.cc` line 330 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtqNXg6kaaIA8vva1i:-NTtqNXg6kaaIA8vva1j:b-g223d2) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.cc#L330)):*
> ```cpp
>   if (!is_positive_finite(radius)) {
>     const std::string error_message = fmt::format(
>         "{}(): A solid sphere's radius = {} is not positive and finite.",
> ```

BTW the two messages seem arbitrarily different. Please format them similarly unless there is a reason not to. Either style seems fine.
___
*[`multibody/tree/spatial_inertia.cc` line 370 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtqeWD6YIffJydMrrB:-NTtqeWD6YIffJydMrrC:b-g223d2) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.cc#L370)):*
> ```cpp
>   if (!is_positive_finite(radius)) {
>     const std::string error_message = fmt::format(
>         "{}(): A hollow sphere's radius = {} is not positive and finite.",
> ```

BTW the two messages seem arbitrarily different. Please format them similarly unless there is a reason not to. Either style seems fine.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 484 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtrFTLA0ETFDMW0jsV:-NTtrFTLA0ETFDMW0jsW:b-3ju2rg) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/test/spatial_inertia_test.cc#L484)):*
> ```cpp
> 
> // Tests the static method for the spatial inertia of a thin hollow sphere.
> GTEST_TEST(SpatialInertia, HollowSphereWithDensity) {
> ```

nit test name += "OrMass"

**Review by mitiguy — COMMENTED** [review]
Ready for another look.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTu7Vci2yWQ8oUDiykI:b467oqh)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[`multibody/tree/spatial_inertia.h` line 312 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtpfm40s7cmF1pn9kS:-NTttLdL1li8bGHSSd4F:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.h#L312)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: B's -> B
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtplzQ27IjP9GvOVi4:-NTttMrn-pJKYEbOdvjN:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.h#L341)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: B's -> B
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 330 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtqNXg6kaaIA8vva1i:-NTtuBti2xwTBsLnRcHs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.cc#L330)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the two messages seem arbitrarily different. Please format them similarly unless there is a reason not to. Either style seems fine.
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 370 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtqeWD6YIffJydMrrB:-NTtuD9p-LniOer2mD_i:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/spatial_inertia.cc#L370)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the two messages seem arbitrarily different. Please format them similarly unless there is a reason not to. Either style seems fine.
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 484 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-NTtrFTLA0ETFDMW0jsV:-NTtvXNb8-m6uZXqlPSX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3a39195fec142f9f45504e5995f93aa4d250daf/multibody/tree/test/spatial_inertia_test.cc#L484)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit test name += "OrMass"
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation, please (also you might be able to make use of the SolidSphereWithMass()).

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTuFwFb7DY7L3rCmzmG:b-wjk8ds)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTuHgK3EgDLdCIBHEr6:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19268#-:-NTuIeH0B8GaoqQWFWDI:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Comment by jwnimmer-tri** [comment]
> ... you might be able to make use of the SolidSphereWithMass().

I assume this is referring to #19238. My intuition there is that we won't use `SolidSphereWithMass`. In that case, we have a known mass but the user has made a mistake typing in the inertia, so we need to invent one. For lack of a better choice, we'll assume a sphere and go from there.

We can either choose an assumed radius and solve for density (by calling `SolidSphereWithMass`), or choose an assumed density and solve for radius.  My intuition is that the most physically realistic guess would be to assume a density, not a radius. For robotics, we should be in the right ballpark by guessing a characteristic density. A characteristic length would have a much wider variation.

**Pull request merged**
