### PR TITLE
Eschew use of operator!!

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We propose that the bangbang operator is not widely enough known[1] outside of C++ experts to merit use in everyday code and error messages[2].

This PR will stay open for one week to receive comments.

If we all agree that all of the changes are improvements (or at least, if nobody disagrees within the window), the next step would be to amend the style guide to make the style choice permanent.

[1] We're excluding those who know know of it via the famous B-52's song.

[2] Just to be clear, for those who don't get the sarcasm: there is actually no `operator!!` in C++ (see https://en.cppreference.com/w/cpp/language/operators).  That's actually the whole point here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15506)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Sad, but probably for the best. next we'll be outlawing xor-swap =P .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15506#-:-Mfj9A9G4jxWmBpanQ1p:b-q7qvxw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15506)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please

**Comment by SeanCurtis-TRI** [comment]
I never cared for it anyways. Good riddance.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15506)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for both reviews per schedule, please.

**Pull request merged**
