### PR TITLE
workspace: Upgrade fcl to latest commit

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This currently pulls from the PR and not master. Do not merge!

We want to make sure this doesn't trash known downstream users before we
merge into FCL.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14063)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) -(status: do not review) 

+@jwnimmer-tri for all reviews.

Currently running against Anzu (job 71).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14063#-:-MHJ0qOP2YBPTed2zYFy:bbnv2b8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok)

Consider running the macOS CI if you think the FCL change risks compilation or tolerancing errors unique to macOS.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14063#-:-MHJ37By1jnggJCAvJvG:bz0er5l)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
Since we have the time anyway...
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by SeanCurtis-TRI** [comment]
Thanks!

**Pull request merged**
