### PR TITLE
[tri_homecart] Move to drake_models package

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For example, users should now load

  `package://drake_models/tri_homecart/homecart.dmd.yaml`

instead of

  `package://drake/manipulation/models/tri_homecart/homecart.dmd.yaml`

---

Towards #20932 and #13942.

Models PR: https://github.com/RobotLocomotion/models/pull/31

Per https://drake.mit.edu/stable.html#model-files our model data is not Stable API so this is regular release notes, not "breaking change".

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

**Review by zachfang — COMMENTED** [review]
:lgtm: 

> Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-:-NrGSd8R77IrZhWCiCC6:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`BUILD.bazel` line 69 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-NrGRqDC7Yh_dEEcEc37:-NrGRqDC7Yh_dEEcEc38:barl5nx) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e20cef3a0f6f18e08035c42fb703df4c8f1812a/BUILD.bazel#L69)):*
> ```Starlark
>         "//manipulation/models/ycb:models",
>         "//multibody/benchmarks/acrobot:models",
>         "@drake_models",
> ```

BTW. Just to understand the strategy better, is our plan to lump all the model files into one `@drake_models` even though a target only needs a subset of the models?



_Code quote:_
```Starlark
"@drake_models"
```
___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-NrGObbt1_8QllEj885G:-NrGObbu4fvxKq7p8Ytk:b77waox) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e20cef3a0f6f18e08035c42fb703df4c8f1812a/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "92ed9246562caf6a77a4376b74b41eb777b319c8",
> ```

I assume the commit needs updating after model#31 is merged. Put a comment to gate that.



_Code quote:_
```Starlark
92ed9246562caf6a77a4376b74b41eb777b319c8
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-:-NrGTqYy06EBPVNCjWpf:bybe5xg)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`BUILD.bazel` line 69 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-NrGRqDC7Yh_dEEcEc37:-NrGTDoOBIXBrmoml0nh:bmveqlf) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e20cef3a0f6f18e08035c42fb703df4c8f1812a/BUILD.bazel#L69)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Just to understand the strategy better, is our plan to lump all the model files into one `@drake_models` even though a target only needs a subset of the models?
</blockquote></details>

Well, this is Drake's top-level `:all_models` target, so it really does want everything.

For the `benchmarking` program change down below, we _could_ imagine writing down just the subset of of the models that it cares about, but I don't think it would help very much.  Our developers do not frequently re-pin the models repository.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:
Do these name changes require an Anzu update to match?

> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-:-NrGqXXM0CiaHjdt2O9v:b-nmrv8i)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004)* status: 1 unresolved discussion

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-NrGObbt1_8QllEj885G:-NrGrUlpB6fZeGNx0Wod:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e20cef3a0f6f18e08035c42fb703df4c8f1812a/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I assume the commit needs updating after model#31 is merged. Put a comment to gate that.
</blockquote></details>

Done.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),zachfang

**Review by jwnimmer-tri — COMMENTED** [review]
> Do these name changes require an Anzu update to match?

Nope, I checked and neither Anzu, nor Underactuated, nor Manipulation use this model.  The only place it seems to be used is the planning benchmark.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21004#-:-NrGrfer78gDpKEG1UmZ:b-gx0g9h)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),zachfang

**Pull request merged**
