### PR TITLE
Add support for HTTP CMake externals and add externals from Bitbucket

### PR DESCRIPTION
**Pull request by jamiesnape**
Originally to fix the same issue as #5955, which is not now needed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5957)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
:lgtm: Looks okay aside from possible bikeshedding where the source should be unpacked.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/externals.cmake, line 502 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-KikjKGmPr_ht7-Gyo4r:-KikjKGmPr_ht7-Gyo4s:b-t7v9jh) ([raw file](https://github.com/robotlocomotion/drake/blob/e9ee90ddde58179e8a54f05c9eb61d0e33cf0811/cmake/externals.cmake#L502)):*
> ```CMake
>     set(_ext_SOURCE_DIR ${PROJECT_SOURCE_DIR}/externals/${PROJECT})
>   elseif(_ext_URL)
>     set(_ext_SOURCE_DIR ${PROJECT_BINARY_DIR}/${PROJECT}-src)
> ```

BTW I wonder if it wouldn't make sense to leave this in the source directory? At least, I wonder if it shouldn't still have `externals/` in it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-KikjcJH4oJyLY3hhjRB:b-r58njp)*

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 502 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-KikjKGmPr_ht7-Gyo4r:-Kikn9Qve0dBPDEaVNl_:b7g6fav) ([raw file](https://github.com/robotlocomotion/drake/blob/e9ee90ddde58179e8a54f05c9eb61d0e33cf0811/cmake/externals.cmake#L502)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW I wonder if it wouldn't make sense to leave this in the source directory? At least, I wonder if it shouldn't still have `externals/` in it?
</blockquote></details>

Added `externals/` to the path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
I have the following error. FYI, I'm using ubuntu-14.
```
FAILED: cd /home/soonhok/work/drake-distro/build/debug-gcc/externals && /usr/local/bin/cmake -P /home/soonhok/work/drake-distro/build/debug-gcc/eigen-prefix/src/eigen-stamp/download-eigen.cmake && /usr/local/bin/cmake -P /home/soonhok/work/drake-distro/build/debug-gcc/eigen-prefix/src/eigen-stamp/verify-eigen.cmake && /usr/local/bin/cmake -P /home/soonhok/work/drake-distro/build/debug-gcc/eigen-prefix/src/eigen-stamp/extract-eigen.cmake && /usr/local/bin/cmake -E touch /home/soonhok/work/drake-distro/build/debug-gcc/eigen-prefix/src/eigen-stamp/eigen-download
-- downloading...
       src='https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz'
       dst='/home/soonhok/work/drake-distro/build/debug-gcc/3.3.3.tar.gz'
       timeout='none'
error: downloading 'https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
```

---

Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-KikyUFGnxPyVgyd0uTi:b2an6ee)*

**Comment by jamiesnape** [comment]
Did you compile your own CMake?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-Kikyz3CfybupwBLev9S:b-xj4127)*

**Comment by soonho-tri** [comment]
Yes (version 3.6.3).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-Kikz_jQdhn7EiSlIErm:b-brrrd9)*

**Comment by jamiesnape** [comment]
Your CMake was compiled without SSL support. Try re-building it with (from memory) `./bootstrap --system-curl` or `cmake -DCMAKE_USE_SYSTEM_CURL=ON` (or download a binary version from cmake.org).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-Kil-1NTLaXir7Ti5_by:b-ttjs15)*

**Comment by soonho-tri** [comment]
> download a binary version from cmake.org

trying this..

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-Kil0KBZeP_hq_qWc62Z:b-4go5sh)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5957#-:-Kil1R3MWpwkvgx_6STG:bnfp4nl)*

**Pull request merged**
