### PR TITLE
Begin adding Python coding style advice.

### LINKED ISSUE #2465: Document our code_style_guide rules for python
We need to document our `code_style_guide.rst` rules for python code.  We have C++, Java, and MATLAB rules now, but not python.

For the record, in #1741 we choose googlestyle for C++ but didn't appear to discuss other languages.  I don't think there's anything else major we've missed, though.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Here's a start for general review and discussion. PEP8 is the meat of it, though there are some additional rules suggested by folks working on internal TRI projects.

Closes #2465.

Of note:

 * I haven't made any attempt to make existing python files comply.
 * I wouldn't object to working on a detailed pylint configuration, but that feels like a separate PR.
 * My tool installation instructions put pylint within the user's account space -- no more `sudo pip install` nonsense. :)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4663)

### CODE REVIEW

**Comment by rdeits** [comment]
I'm not sure the `-B` flag is a great idea, since as soon as a user does `python scriptname.py` or `python -m drake.examples.whatever` or anything like that, all the `.pyc` files will be generated anyway. `.pyc` file clutter is a big enough issue that it was directly addressed in python 3, but it's kind of unavoidable in python 2.

**Comment by rpoyner-tri** [comment]
@rdeits acknowledged. Worse still, it doesn't work, because the "shebang" technique can only handle one argument. I'll withdraw the '-B'.

**Comment by rht** [comment]
`pylint --reports=n --disable=C,R **/*.py` on the python binding subtree:
```
************* Module pydrake
W:  9, 4: Relative import 'insource_path', should be 'pydrake.insource_path' (relative-import)
************* Module pydrake.test.testPR2IK
E:  4, 0: No name 'ik' in module 'pydrake.solvers' (no-name-in-module)
W: 23, 4: Redefining name 'robot' from outer scope (line 38) (redefined-outer-name)
W:  6,25: Redefining name 'urdf_file' from outer scope (line 35) (redefined-outer-name)
************* Module pydrake.test.testRBTIK
E:  4, 0: No name 'ik' in module 'pydrake.solvers' (no-name-in-module)
************* Module pydrake.test.testRBTTransformPoints
E:  5, 0: No name 'autodiffutils' in module 'pydrake' (no-name-in-module)
E:  5, 0: Unable to import 'pydrake.autodiffutils' (import-error)
```

**Comment by rpoyner-tri** [comment]
@rht as stated, I've made no attempt to actually clean any of the existing python sources. I haven't gone back to note the causes of all those warnings, but I bet it is a mix of possibly legitimate issues (variable shadowing) and stuff that should be suppressed or fixed by configuration (imports that depend on run-time editing of sys.path, names not discoverable by static checking, etc.).

**Comment by rht** [comment]
@rpoyner-tri I see. I tried generating the build folders with cmake and the pylint errors just exploded to 1131 of wc-count!

log: https://gist.github.com/0675bbe599345272f0494ad0ac863384
(85% due to no-member which can be disabled, while some can be cleaned for sure)

> I wouldn't object to working on a detailed pylint configuration, but that feels like a separate PR.

Noted. For reference, here is what the tensorflow team did (since they use the swig-generated wrappers as well): https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/tools/ci_build/pylintrc#L41

**Comment by rpoyner-tri** [comment]
Thanks for the tensorflow link!

I expect that any python files generated by swig will be completely un-check-able; I will add some mechanism to ignore those.

I've been working elsewhere today, but expect to return to this before the end of the week.

TODOs:
 * add an exception to the 80-column rule for long URLs
 * add tool documentation for pep8.py or equivalent, since i'm unsure how completely pylint polices white space.
 * document/mechanism for ignoring python files generated by swig

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-:-K_eXf8wI7lX4p0ot3Jx:box7czw)*

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri In #4684 it came up whether we mandate a verb command vs description in our python docstrings, i.e., "Returns the thing" vs "Return the thing" -- and more widely whether PEP 257 is incorporated into our standards via its citation from PEP 8.  Probably worth adding language to this PR that speaks to those, even if the answer is "don't know yet".

**Comment by rpoyner-tri** [comment]
My default inclination is to go with PEP 257, but I need to review things and think a bit.

**Comment by rpoyner-tri** [comment]
At this point, I think I've got a decent start on the *policy*, and a bit about the *tools*. A subsequent PR will sharpen the tool execution and configuration, and fix whatever present problems exist.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-:-Ka7oJLANndYXpu-RnvW:bz3dl5v)*

**Comment by rpoyner-tri** [comment]
+@ggould-tri for feature review, +@sammy-tri (Wednesday's on-call, I know -- i can wait) for platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-:-Ka7okMd2k8XvFn6aOb2:b7uhgeq)*

**Comment by ggould-tri** [comment]
This looks sound and sensible to me.  There are probably details along which it will have to evolve, but the style guide has proven quite able to accommodate that in the past.  Let's land it and see where it goes. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-:-Ka7z_maXZ0PTYO5M7s3:be0zdg)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka895WdXh-K0ppf-l4V:-Ka895WecpTUJTMFrj8K:b-tcbt3w) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L293)):*
> ```reStructuredText
> ----------
> 
> * Lines containing a long URL maybe longer than 80 columns if necessary to
> ```

missing space "may be"?

---

*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka89GHVV0LACoMupeJ5:bjbf80y) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
> ```reStructuredText
> ----------------
> 
> * When including in-tree files, always use absolute import paths.
> ```

Does this actually mean "when modifying sys.path to import in-tree files?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka8afB7p75dVIY3GA--:b-niicg7) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this actually mean "when modifying sys.path to import in-tree files?"
</blockquote></details>

No, it means in-tree files. For the project, define one or more roots (already on the python path, by magic). From those, always use `import foo.bar.baz`, even if your file is already in foo/bar.

Perhaps the part that is not worked out yet is how to seed the python path and avoid the dreaded `project_paths.py` anti-pattern. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka8by6Qjhkas3XQYnyt:b1m758a) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

No, it means in-tree files. For the project, define one or more roots (already on the python path, by magic). From those, always use `import foo.bar.baz`, even if your file is already in foo/bar.

Perhaps the part that is not worked out yet is how to seed the python path and avoid the dreaded `project_paths.py` anti-pattern. 
</blockquote></details>

FYI You know what I'm going to say to this ;).  Use Bazel and the paths are correct out-of-the-box.  My soon-to-post PR rm's `drake/automotive/drake_paths.py` entirely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by rpoyner-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka895WdXh-K0ppf-l4V:-Ka8c9ccrx4YnxcfG1U0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L293)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

missing space "may be"?
</blockquote></details>

Done.

---

*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka8cHznx8jUse6nQQ_X:b-9yrqpo) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI You know what I'm going to say to this ;).  Use Bazel and the paths are correct out-of-the-box.  My soon-to-post PR rm's `drake/automotive/drake_paths.py` entirely.
</blockquote></details>

I wanted you to say it, because I suspected it was true, but didn't have the details at my fingertips. :) :100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka8mjty53GW_nKvfvQ_:b3025nu) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I wanted you to say it, because I suspected it was true, but didn't have the details at my fingertips. :) :100: 
</blockquote></details>

I think the fact that I failed to understand the current wording still suggests a change is necessary (even if it's just a reference to some part of PEP8 which I didn't remember which would have made this all clearer).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by rpoyner-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-Ka89GHVV0LACoMupeJ4:-Ka8tRbMdCc0rkEAy6Jj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d67d88f97ca5bfdb596cb87becf3e108a6156dca/drake/doc/code_style_guide.rst#L301)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think the fact that I failed to understand the current wording still suggests a change is necessary (even if it's just a reference to some part of PEP8 which I didn't remember which would have made this all clearer).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4663#-:-KaDccfB2aeXR33At32k:bnfp4nl)*

**Pull request merged**
