### PR TITLE
[workspace] Remove deprecated externals 2021-12

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove the ignition_math shared library (now it's static-only).
Remove jsoncpp entirely.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16155)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: one crufty bit

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16155#-:-MpmOAoo9uRMGHz46Why:b-t8fzc5)* status: 1 unresolved discussion, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/workspace/ignition_math/package.BUILD.bazel, line 214 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16155#-MpmNrzo6eAvN15ENzAi:-MpmNrzo6eAvN15ENzAj:b7wogls) ([raw file](https://github.com/robotlocomotion/drake/blob/b2dee99591b7298a4699d5e10c7e66993b66bd6f/tools/workspace/ignition_math/package.BUILD.bazel#L214)):*
> ```
> install(
>     name = "install",
>     # XXX
> ```

The XXX looks like cruft, or work in progress? Also the commented code line following.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16155)* status: 1 unresolved discussion, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

___
*[tools/workspace/ignition_math/package.BUILD.bazel, line 214 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16155#-MpmNrzo6eAvN15ENzAi:-MpmP5ZuEyYCAPaGuI0U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2dee99591b7298a4699d5e10c7e66993b66bd6f/tools/workspace/ignition_math/package.BUILD.bazel#L214)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The XXX looks like cruft, or work in progress? Also the commented code line following.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16155)* status: labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Pull request merged**
