### PR TITLE
py mbp: Allow SpatialVector's to be pickled

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For use in Anzu

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104#-:-MHmE5XY3HqMW6n1Ru9A:bpluupl)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
One quick question prior to the stamp.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104#-:-MHmJH3LD_AIsGJGOlp9:b-3uce7)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/test/math_test.py, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14104#-MHmIYTD-58LSrAM55sZ:-MHmIYTD-58LSrAM55s_:b69v2u) ([raw file](https://github.com/robotlocomotion/drake/blob/b1fb898276adb020274c1c936b595de2df0c61d3/bindings/pydrake/multibody/test/math_test.py#L8)):*
> ```Python
> from pydrake.common.cpp_param import List
> from pydrake.common.value import Value
> import pydrake.common.test_utilities.numpy_compare as numpy_compare
> ```

Why aren't these combined as they are for e.g., `multibody.math` below. I.e.,

```py
from pydrake.common.test_utilities import (
    numpy_compare,
    assert_pickle
)
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/test/math_test.py, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14104#-MHmIYTD-58LSrAM55sZ:-MHmJX-CAkPdKXbDqb-e:b7xld7f) ([raw file](https://github.com/robotlocomotion/drake/blob/b1fb898276adb020274c1c936b595de2df0c61d3/bindings/pydrake/multibody/test/math_test.py#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Why aren't these combined as they are for e.g., `multibody.math` below. I.e.,

```py
from pydrake.common.test_utilities import (
    numpy_compare,
    assert_pickle
)
```
</blockquote></details>

Because `assert_pickle` is imported from `pickle_compare` (a separate module), not from `test_utilities`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104#-:-MHmKVxg4yExztrKFks3:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[bindings/pydrake/multibody/test/math_test.py, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14104#-MHmIYTD-58LSrAM55sZ:-MHmKOqyA83PTQU1ImtH:b5r65qc) ([raw file](https://github.com/robotlocomotion/drake/blob/b1fb898276adb020274c1c936b595de2df0c61d3/bindings/pydrake/multibody/test/math_test.py#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Because `assert_pickle` is imported from `pickle_compare` (a separate module), not from `test_utilities`.
</blockquote></details>

Riiiiiight. I carefully matched the first couple of namespaces but didn't get all the way to the end. One pickle is as good as another, right?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14104)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[bindings/pydrake/multibody/test/math_test.py, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14104#-MHmIYTD-58LSrAM55sZ:-MHmLLv73is-PrTb6twD:bfo3dog) ([raw file](https://github.com/robotlocomotion/drake/blob/b1fb898276adb020274c1c936b595de2df0c61d3/bindings/pydrake/multibody/test/math_test.py#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Riiiiiight. I carefully matched the first couple of namespaces but didn't get all the way to the end. One pickle is as good as another, right?
</blockquote></details>

Yup! And given that, the more (written) pickles, the better, right? :P

**Pull request merged**
