### PR TITLE
Adds a version of RigidBodyPlant that publishes xdot over LCM.

### PR DESCRIPTION
**Pull request by liangfok**
This was extracted from #4682. It is intended to be a workaround until #2890 is resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4721)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka4iDquBl3nmx8dPTuq:b-p31ow2)*

**Comment by sherm1** [comment]
Platform review: looks great, just a few comments.

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka4kQqLFV9HaZ2c6gqX:-Ka4kQqLFV9HaZ2c6gqY:b-sbanew) ([raw file](https://github.com/robotlocomotion/drake/blob/14e16e377a1222cc74f652eeab13f6ac2a0d2df1/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L39)):*
> ```cpp
> void RigidBodyPlantThatPublishesXdot<T>::DoPublish(const Context<T>& context)
>     const {
>   RigidBodyPlant<T>::DoCalcTimeDerivatives(context, derivatives_.get());
> ```

Should call `CalcTimeDerivatives()` here since that is the public interface. (DoCalc... should really be private.)

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka52gfC-X1zAGE12jMr:-Ka52gfC-X1zAGE12jMs:b-onlzb8) ([raw file](https://github.com/robotlocomotion/drake/blob/814f3e139753a1c1f521468647f6d60a5fd9e267/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L51)):*
> ```cpp
>     message_.val[i] = xdot(i);
>   }
>   message_.timestamp = static_cast<int64_t>(context.get_time() * 1000);
> ```

BTW, is this intended as a conversion to milliseconds? If so would be good to comment.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka4kyKK2XHwNhxTwnso:-Ka4kyKK2XHwNhxTwnsp:bu1kryr) ([raw file](https://github.com/robotlocomotion/drake/blob/14e16e377a1222cc74f652eeab13f6ac2a0d2df1/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.h#L21)):*
> ```objc
> 
> /// This is a child class of RigidBodyPlant that publishes `xdot`, the
> /// derivative of x, which is the RigidBodyPlant's output state vector.
> ```

BTW, -> "time derivative of RBPlant's state vector x."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka53AI3LIOzK3yq8Ryn:bw16l1q)*

**Comment by liangfok** [comment]
@sherm1: Thanks for the review. I've addressed your comments.

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka4kQqLFV9HaZ2c6gqX:-Ka56ABe9GdvUGMnl-mB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14e16e377a1222cc74f652eeab13f6ac2a0d2df1/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Should call `CalcTimeDerivatives()` here since that is the public interface. (DoCalc... should really be private.)
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka52gfC-X1zAGE12jMr:-Ka56FGeq2JHMnNpqRjb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/814f3e139753a1c1f521468647f6d60a5fd9e267/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is this intended as a conversion to milliseconds? If so would be good to comment.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka4kyKK2XHwNhxTwnso:-Ka572neS5jUSwDfyhoq:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/14e16e377a1222cc74f652eeab13f6ac2a0d2df1/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, -> "time derivative of RBPlant's state vector x."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka57jBOSHYxMR0dkTW7:bfq9dil)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-matlab/2412/ has two unit tests timing out. I hope it's due to license / MATLAB flakiness.

@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Comment by sherm1** [comment]
Thanks, @liangfok. Platform :lgtm:.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka5fXGTYjZQmseSZf2k:buabpsa)*

**Comment by amcastro-tri** [comment]
Just a few comments. Otherwise :lgtm: 

---

Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 47 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7nFQWugeRF3VNU216:-Ka7nFQWugeRF3VNU217:b-z13ss9) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L47)):*
> ```cpp
>                          rigid_body_tree.get_num_velocities();
> 
>   DRAKE_DEMAND(xdot.size() == num_states);
> ```

BTW, we have `RigidBodyPlant<T>::get_num_states()` 

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 50 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7o85rxD-uy_sJF-Ql:-Ka7o85rxD-uy_sJF-Qm:b-vkqgih) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L50)):*
> ```cpp
>   for (int i = 0; i < num_states; ++i) {
>     message_.val[i] = xdot(i);
>   }
> ```

BTW, you can also do `VectorXd::Map(message_.val.data(), xdot.size()) = xdot;`

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7p6bZkS0ileixGrwS:-Ka7p6bZkS0ileixGrwT:bin7u2s) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L25)):*
> ```cpp
> using parsers::urdf::AddModelInstanceFromUrdfFile;
> 
> namespace systems {
> ```

`sytems/plants` --> `multibody`

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 59 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7r360WJksEsPETVnj:-Ka7r360WJksEsPETVnk:bbtwwbs) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L59)):*
> ```cpp
> 
>   lcmt_drake_signal transmitted_message;
>   EXPECT_EQ(transmitted_message.decode(transmitted_message_bytes.data(), 0,
> ```

BTW, add explanatory text?: "Decodes message and checks that the correct number of bytes was processed."

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 71 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7rIPTSHF2j9PAkZen:-Ka7rIPTSHF2j9PAkZeo:b-857jr5) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L71)):*
> ```cpp
>   expected_message.timestamp = 0;
> 
>   EXPECT_TRUE(CompareLcmtDrakeSignalMessages(
> ```

BTW, add explanatory text?: "Compares the previously decoded message entry by entry."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka7rfKe4Jkxqc3W9_iJ:b-q8jcs4)*

**Comment by liangfok** [comment]
@amcastro-tri I addressed your comments. PTAL. Thanks! 

---

Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 47 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7nFQWugeRF3VNU216:-Ka7sHsahN3CBMrqmQtF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L47)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, we have `RigidBodyPlant<T>::get_num_states()` 
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc, line 50 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7o85rxD-uy_sJF-Ql:-Ka7sYs2vsANVcIVmBxx:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/rigid_body_plant_that_publishes_xdot.cc#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, you can also do `VectorXd::Map(message_.val.data(), xdot.size()) = xdot;`
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7p6bZkS0ileixGrwS:-Ka7skjvvyOtTiZ7eKKt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`sytems/plants` --> `multibody`
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 59 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7r360WJksEsPETVnj:-Ka7sucQulO3ksr6gJVd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L59)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, add explanatory text?: "Decodes message and checks that the correct number of bytes was processed."
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc, line 71 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7rIPTSHF2j9PAkZen:-Ka7t01s_L1JS7iSHh5-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1b8120c8fb1b7af3206ce28cf2cb8f7b6dedf6b/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_outputs_xdot_test.cc#L71)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, add explanatory text?: "Compares the previously decoded message entry by entry."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka7t2ZXi2ZThUqWld9e:b1nzz09)*

**Comment by amcastro-tri** [comment]
Thanks. One last little comment.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 34 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7wDbjSPmJg8f-ecjJ:-Ka7wDbjSPmJg8f-ecjK:b-gpjt9w) ([raw file](https://github.com/robotlocomotion/drake/blob/ee7415b7c88798d899433ab8b46cff6f2d51e927/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L34)):*
> ```cpp
> // Tests that RigidBodyPlantThatPublishesXdot actually publishes LCM messages
> // when DoPublish() is called.
> GTEST_TEST(RigidBodyPlantThatOutputsXdotTest, TestPublishLcmMessage) {
> ```

`RigidBodyPlantThatPublishesXdotTest` for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka7wLUQVtmvIbv3rc1B:bkn9ts9)*

**Comment by liangfok** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc, line 34 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-Ka7wDbjSPmJg8f-ecjJ:-Ka7webO7U52akK_nd_C:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/ee7415b7c88798d899433ab8b46cff6f2d51e927/drake/multibody/rigid_body_plant/test/rigid_body_plant_that_publishes_xdot_test.cc#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`RigidBodyPlantThatPublishesXdotTest` for consistency?
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721)*

**Comment by liangfok** [comment]
@amcastro-tri: Thanks. I will merge once this passes CI.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4721#-:-Ka7wmtSJ-IcgKUjc-G-:bfpzvnr)*

**Pull request merged**
