### PR TITLE
Internal function to sum default mass and check for zero rotational inertia.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N2t0Lrp09kwuWGlgPLj:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature pass  #1 done -- a few things need rethinking IMO. Let's discuss.

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N2xl6BbBQd8AjxGaZ9J:b-y5u373)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy and @sherm1)

___
*[`multibody/tree/body.h` line 359 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xjROM9xGZvu_RhF_J:-N2xjROM9xGZvu_RhF_K:bmazk63) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/body.h#L359)):*
> ```objc
>   /// body B's about Bo (B's origin), expressed in B (this body's frame).
>   /// @retval I_BBo_B body B's rotational inertia about Bo, expressed in B.
>   virtual RotationalInertia<double> default_rotational_inertia() const = 0;
> ```

minor: it surprised me that default_mass is held in the base Body class but we need a virtual to get the inertia. Later I see that RigidBody has a default_spatial_inertia which I presume would be handled differently in a DeformableBody. But it's confusing because default_spatial_inertia also contains a mass -- is that somehow kept in sync with the base class default_mass?

I'd like to see some explanation in the comments here as to why the default mass and inertia aren't handled the same way.
___
*[`multibody/tree/multibody_tree.h` line 2488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xkJz-28MpbPl76ljT:-N2xkJz-28MpbPl76ljU:bttfap8) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.h#L2488)):*
> ```objc
>   // sum of the default rotational inertia of all bodies in the set body_indexes
>   // (without shifting to a common point or expressing in a common frame).
>   RotationalInertia<double> CalcTotalDefaultRotationalInertia(
> ```

I don't think this function makes sense. It is too weird to be adding up inertias in a meaningless way just to check if they are all zero. I'd like to see something more straightforward that simply checks whether all the inertias are zero rather than this terrifying computation.
___
*[`multibody/tree/multibody_tree.cc` line 2879 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xklHgAOuDwFQErwMH:-N2xklHgAOuDwFQErwMI:b9v3h3d) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.cc#L2879)):*
> ```cpp
>     const Body<T>& body_B = get_body(body_index);
>     const double mass_B = body_B.get_default_mass();
>     if (!std::isnan(mass_B)) total_mass += mass_B;
> ```

BTW can it really happen that a body's default mass is NaN? Should this just be a DRAKE_DEMAND(!isnan)?
___
*[`multibody/tree/multibody_tree.cc` line 2896 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xkx5Y3QP_7hckIE8e:-N2xkx5Z9Tt5bX5Ss8MU:blusgzd) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.cc#L2896)):*
> ```cpp
>     // Each body B has its own origin point Bo and own unit vectors Bx, By, Bz.
>     // As such, simply adding a body B1's rotational inertia to a body B2's
>     // rotational inertia may have no physical meaning.
> ```

Let's not do it then!
___
*[`multibody/tree/rotational_inertia.h` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xj3yO6t8LO8dplyv6:-N2xj3yO6t8LO8dplyv7:b-sqxvbv) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/rotational_inertia.h#L491)):*
> ```objc
>   }
> 
>   /// Returns `true` if all moments of inertia and products of inertia are zero.
> ```

BTW consider "are _exactly_ zero"
___
*[`multibody/tree/rotational_inertia.h` line 492 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xjE3_A3sjmHFUGw1Q:-N2xjE3_A3sjmHFUGw1R:b-eb3miv) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/rotational_inertia.h#L492)):*
> ```objc
> 
>   /// Returns `true` if all moments of inertia and products of inertia are zero.
>   boolean<T> IsZero() const {
> ```

minor: this method needs a unit test

**Review by mitiguy — COMMENTED** [review]
@sherm1  This is ready for another look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N31tHJjAvtlemWH9H4E:b-rtpvw7)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`multibody/tree/body.h` line 359 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xjROM9xGZvu_RhF_J:-N31SYRn-zMgWaRNwEFP:b-m4ril3) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/body.h#L359)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: it surprised me that default_mass is held in the base Body class but we need a virtual to get the inertia. Later I see that RigidBody has a default_spatial_inertia which I presume would be handled differently in a DeformableBody. But it's confusing because default_spatial_inertia also contains a mass -- is that somehow kept in sync with the base class default_mass?

I'd like to see some explanation in the comments here as to why the default mass and inertia aren't handled the same way.
</blockquote></details>

Opened Github issue so this can be resolved in a subsequent PR.
https://github.com/RobotLocomotion/drake/issues/17277
___
*[`multibody/tree/multibody_tree.h` line 2488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xkJz-28MpbPl76ljT:-N31VSh_AUG7ERoNcflc:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.h#L2488)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I don't think this function makes sense. It is too weird to be adding up inertias in a meaningless way just to check if they are all zero. I'd like to see something more straightforward that simply checks whether all the inertias are zero rather than this terrifying computation.
</blockquote></details>

Done.  
___
*[`multibody/tree/multibody_tree.cc` line 2879 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xklHgAOuDwFQErwMH:-N31PYudCO2rgs9QJXUO:bht8dp) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.cc#L2879)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can it really happen that a body's default mass is NaN? Should this just be a DRAKE_DEMAND(!isnan)?
</blockquote></details>

From what I see in other parts of the code base, it seems it can.
For example, from lines 199-203 in multibody_plant.cc
          // This check is needed for such models for which the user leaves the
          // spatial inertias unspecified (i.e. initialized to NaN). A user
          // might do this when only interested in performing kinematics
          // computations.
          if (std::isnan(body->get_default_mass())) {
___
*[`multibody/tree/multibody_tree.cc` line 2896 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xkx5Y3QP_7hckIE8e:-N31VZGs5vZwIgrlxVQW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/multibody_tree.cc#L2896)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Let's not do it then!
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.h` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xj3yO6t8LO8dplyv6:-N31Vkxm-TZBQy7cnfZ8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/rotational_inertia.h#L491)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider "are _exactly_ zero"
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.h` line 492 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17261#-N2xjE3_A3sjmHFUGw1Q:-N31ZO7e7gsU9lJ35ZhY:b-sld7st) ([raw file](https://github.com/robotlocomotion/drake/blob/61b1f3d7cf84b3ecaef0aac01e478bf0b54dccef/multibody/tree/rotational_inertia.h#L492)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this method needs a unit test
</blockquote></details>

Done in rotational_inertia_test.cc (now in this PR).

**Review by sherm1 — COMMENTED** [review]
Thanks, Paul -- feature :lgtm:
+@rpoyner-tri for platform review (Tuesday) per rotation, please

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N31xtsO6AKforg1CQnd:b-bxreyt)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N3QOyvO0C3-E91Phkoc:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17261#-:-N3Qn5Gq7jOrjBEsrCzR:bm9o57a)* status: missing label for release notes (waiting on @mitiguy)

**Pull request merged**
