### PR TITLE
Declare MATLAB dependencies in CMakeLists

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #1997. This assumes that dependencies were already correctly declared in the MATLAB source code using `checkDependency` calls.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3094)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab-open-source  please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab-open-source  please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot linux-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
PTAL @david-german-tri.

**Comment by david-german-tri** [comment]
Looking at the windows-msvc-ninja-32 build with this PR: https://drake-cdash.csail.mit.edu/viewTest.php?buildid=88152

Versus without it: https://drake-cdash.csail.mit.edu/viewTest.php?buildid=88363

The number of test cases has dropped from 468 to 416 and the build has gotten half an hour shorter.  Obviously that's the kind of effect we want, so woohoo!  Have you spot-checked the lists (for all the various builds) to confirm that the tests that are disappearing are the ones you expect to disappear?  (I had hoped the "Download Table as CSV File" link in CDash would help with this, but it doesn't seem to work.)

---

Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 164 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlSEzCZP1DuLxgm60:-KPrlSF-t0NuKTuEaRGb:b-21vuay) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/CMakeLists.txt#L164)):*
> ```CMake
>   endif()
>   set(oneValueArgs NAME COMMAND WORKING_DIRECTORY)
>   set(multiValueArgs PROPERTIES REQUIRES OPTIONAL)
> ```

where is this new arg `OPTIONAL` used?

---

*[drake/examples/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlszCBEWQtGPXaIgk:-KPrlszCBEWQtGPXaIgl:b9i6jcs) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/examples/CMakeLists.txt#L14)):*
> ```CMake
> add_matlab_test(NAME examples/LinearGaussianExample.run COMMAND LinearGaussianExample.run)
> 
> add_matlab_test(NAME examples/SineSys.runTaylor REQUIRES spotless OPTIONAL mosek sedumi COMMAND SineSys.runTaylor)
> ```

and how did you decide which dependencies were `OPTIONAL`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-:-KPrmRPHBxtWTP6lYH1y:bexjsfl)*

**Comment by jamiesnape** [comment]
I did, yes. The tests that are not going to be run are output at the configure stage, along with the (first) missing dependency in question.

---

Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 164 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlSEzCZP1DuLxgm60:-KPrnU8VSvroGpmsljb_:b-s3fcmi) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/CMakeLists.txt#L164)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> where is this new arg `OPTIONAL` used?
</details>
Nowhere yet. Consider it useful documentation for now.

---

*[drake/examples/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlszCBEWQtGPXaIgk:-KPrno7-mGmUqbkxAw1w:bjx1fnz) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/examples/CMakeLists.txt#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> and how did you decide which dependencies were `OPTIONAL`?
</details>
The MATLAB function has two forms based on the return value. With no return value, it causes the program to terminate, with a return value it returns a boolean that is used to enable different behavior depending on the value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-:-KPrnCwBhED2iY7S5I5l:b-x0ko3)*

**Comment by jamiesnape** [comment]
Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlszCBEWQtGPXaIgk:-KProrJwsEJsvifWYzvB:b2l8yir) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/examples/CMakeLists.txt#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> The MATLAB function has two forms based on the return value. With no return value, it causes the program to terminate, with a return value it returns a boolean that is used to enable different behavior depending on the value.
</details>
The `checkDependency` MATLAB function, that is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 164 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlSEzCZP1DuLxgm60:-KPrsMcsOMefTuxHekjK:bm43s18) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/CMakeLists.txt#L164)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Nowhere yet. Consider it useful documentation for now.
</details>
How do you plan to use it?

---

*[drake/examples/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlszCBEWQtGPXaIgk:-KPrsV-gKiOIsNbGNVPJ:b-eko1o1) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/examples/CMakeLists.txt#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> The `checkDependency` MATLAB function, that is.
</details>
So you're saying that, somewhere, the execution of this test passes through an `if(checkDependency('mosek'))`?  How did you determine that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-:-KPrrGGojvF2E1QVlnmQ:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 54 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlszCBEWQtGPXaIgk:-KPrvOggopIoNBsDtdBQ:b-slggrk) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/examples/CMakeLists.txt#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> So you're saying that, somewhere, the execution of this test passes through an `if(checkDependency('mosek'))`?  How did you determine that?
</details>
Adding print statements to MATLAB and then grepping the output. This PR was basically fun with grep and sed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094)*

**Comment by jamiesnape** [comment]
Review status: 0 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 164 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3094#-KPrlSEzCZP1DuLxgm60:-KPs2KHZVFrBCn-N7B_t:b-k5hw9a) ([raw file](https://github.com/robotlocomotion/drake/blob/8ebfc3d57888a8686fddd7bee69698334dc72e6a/drake/CMakeLists.txt#L164)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> How do you plan to use it?
</details>
To ensure we have reasonable code coverage of the various conditional branches eventually. Initially, it will probably be some sort of informational debug message summarizing the optional dependencies being used for a test run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3094)*

**Pull request merged**
