### PR TITLE
Remove DRC terrain maps from drake

### PR DESCRIPTION
**Pull request by rdeits**
We already did the hard work this spring to make the controller operate without heightmaps, but there was still some vestigial code lying around. This pull request solidifies the contract that the RigidBodySupportState contains the contact plane, which is what all of our walking plans were doing already.

### CODE REVIEW

**Comment by patmarion** [comment]
Nice!  +1

**Comment by RussTedrake** [comment]
let me know about the drake005 error -- looks like it could definitely be related.

**Comment by rdeits** [comment]
ok, conflicts are fixed. Let's see if this works now.

**Comment by rdeits** [comment]
The error on drake005 is real: it looks like Atlas's rear contact points are *just* missing the second stair, which causes it to fall. I bet that the test has just been timing out on every machine before reaching that point until now.

**Comment by rdeits** [comment]
Ok, should be good to go

**Pull request merged**
