### PR TITLE
Add documentation on polynomial type.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14790)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14790#-:-MVy--gL6ymXAb4i_Bui:bshz79q)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
one discussion point below.  otherwise :LGTM:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14790#-:-MVy19rC3B_pFAvTapfZ:bsa75j2)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 582 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14790#-MVy0GskAQ1cuFDJjOCh:-MVy0GskAQ1cuFDJjOCi:b-6xfkq) ([raw file](https://github.com/robotlocomotion/drake/blob/306baa8e0fd2a600c7d07c99f85ca1b940877603/bindings/pydrake/solvers/mathematicalprogram_py.cc#L582)):*
> ```cpp
>               MathematicalProgram::NonnegativePolynomial)>(
>               &MathematicalProgram::NewNonnegativePolynomial),
>           py::arg("grammian"), py::arg("monomial_basis"), py::arg("type"),
> ```

technically this could be an API breaking change.  (though I agree that one m is the correct spelling).

the right solution would be to also provide a deprecated overload that takes the original argument, and provide this variant as a second overload.

i'm inclined to believe that this is a little known/used api, and that the user would get a reasonable message if they did have a named argument with the mis-spelling, so would say we can probably sneak this one in.  

@jwnimmer-tri -- WDYT?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14790)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 582 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14790#-MVy0GskAQ1cuFDJjOCh:-MWAmBpO0Cb7Zkon2blX:b-fical1) ([raw file](https://github.com/robotlocomotion/drake/blob/306baa8e0fd2a600c7d07c99f85ca1b940877603/bindings/pydrake/solvers/mathematicalprogram_py.cc#L582)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

technically this could be an API breaking change.  (though I agree that one m is the correct spelling).

the right solution would be to also provide a deprecated overload that takes the original argument, and provide this variant as a second overload.

i'm inclined to believe that this is a little known/used api, and that the user would get a reasonable message if they did have a named argument with the mis-spelling, so would say we can probably sneak this one in.  

@jwnimmer-tri -- WDYT?
</blockquote></details>

Sorry for the delay. Jeremy showed me how to use WrapDeprecated to deprecate the python interface. I tested locally on my machine, that if I use the incorrect "grammian" version, now it prints a deprecation message.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14790#-:-MWKcf3Z3h0o2WS4IHOc:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Could I ask you to open a follow-up PR to correct the deprecation removal date to be `2021-07-01` to match our standard 3-months policy?

**Pull request merged**
