### PR TITLE
Add Bool<T> class in common/drake_bool.h

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue #8362.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8404)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@sherm1 for feature-review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8404#-:-L7z_eq6veR1TcBs84Kt:bmooc1s)*

**Comment by jwnimmer-tri** [comment]
*[common/drake_bool.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8404#-L7zhTrHhmulCMIEagzs:-L7zhTrJ6OJ5Zgm5UGxe:b-t4jlfl) ([raw file](https://github.com/robotlocomotion/drake/blob/caec4a6b3d489496e7bfc78017053a32dd6e43bb/common/drake_bool.h#L29)):*
> ```objc
> /// bool_t.
> template <typename T>
> class bool_t {
> ```

When this was going to be a traits-like type wrapper, the name `bool_t` made sense (short for `bool<T>::type`).  Now that this is a real class, it should not be named like a traits-type lookup, but rather follow GSG, so e.g. `Bool<T>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8404)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/drake_bool.h, line 29 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zhTrHhmulCMIEagzs:-L7zqGvuJauw4NpIyhC4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/caec4a6b3d489496e7bfc78017053a32dd6e43bb/common/drake_bool.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When this was going to be a traits-like type wrapper, the name `bool_t` made sense (short for `bool<T>::type`).  Now that this is a real class, it should not be named like a traits-type lookup, but rather follow GSG, so e.g. `Bool<T>`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by jwnimmer-tri** [comment]
I think actually the witness functions' use of T-dependent booleans is one of the more controversial questions we could choose.  Instead of touching the witness code, what do you think about instead changing the vector_gen codegen output for `IsValid` to use `Bool<T>`?  I think that is a clear and simple example.

---

Reviewed 1 of 6 files at r1, 2 of 4 files at r2.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---

*[common/drake_bool.h, line 33 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7ztZR-2ZfNMHsPtevu:-L7ztZR-2ZfNMHsPtevv:bkklojv) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L33)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Bool);
> 
>   using formula_t = decltype(T() < T());
> ```

FYI I suggest either `value_type` to match STL containers such as vector or optional, or else `SomeCamelName` to match GSG.

---

*[common/drake_bool.h, line 57 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zw0gI3BlnUaYAn1JP:-L7zw0gI3BlnUaYAn1JQ:b-i6dgi) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L57)):*
> ```objc
> 
> /// Extracts a bool value from @p b or throws an exception if the extraction
> /// fails.
> ```

FYI Consider explaining to the reader _why_ this might fail (i.e., unbound variables).

---

*[common/symbolic_formula.h, line 190 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zuzO55tvFq-MVjv6A:-L7zuzO55tvFq-MVjv6B:b1x2ao2) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/symbolic_formula.h#L190)):*
> ```objc
> 
>   /** Conversion to bool. */
>   explicit operator bool() const { return Evaluate(); }
> ```

BTW Is the intention to remove this?  If so, please add a TODO around here.  If not, its unclear to me why symbolic_formula needs to specialize ExtractBoolOrThrow.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-:-L7zvaSQCTgqhYVzYEaG:b-ecqzry)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 48 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zwVl0-RYg_pOQBuhk:-L7zwVl0-RYg_pOQBuhl:b1nl0qx) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L48)):*
> ```cpp
>   Bool<double> b2{3.0 > 4.0};
>   b2 = b1;
>   EXPECT_EQ(ExtractBoolOrThrow(b1), ExtractBoolOrThrow(b2));
> ```

BTW Just EXPECT_TRUE on each individually?  If they both ended up false, this would incorrectly pass.

---

*[common/test/drake_bool_test.cc, line 89 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zwxCz2Yj7mLp-xCBV:-L7zwxCz2Yj7mLp-xCBW:bdroh4z) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L89)):*
> ```cpp
>   const bool v{ExtractBoolOrThrow(b)};
>   EXPECT_TRUE(v);
> }
> ```

BTW For thoroughness, might as well test the reverse (false) as well?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by soonho-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[common/symbolic_formula.h, line 190 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zuzO55tvFq-MVjv6A:-L7zxkpL-2OizJPV46Ox:b-jqiu3r) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/symbolic_formula.h#L190)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is the intention to remove this?  If so, please add a TODO around here.  If not, its unclear to me why symbolic_formula needs to specialize ExtractBoolOrThrow.
</blockquote></details>

FYI, I found that gcc-5 generates an error without it:
```
bazel-out/k8-dbg/bin/common/_virtual_includes/essential/drake/common/drake_bool.h: In instantiation of 'bool drake::ExtractBoolOrThrow(const drake::Bool<T>&) [with T = drake::symbolic::Expression]':
common/test/drake_bool_test.cc:116:36:   required from here
bazel-out/k8-dbg/bin/common/_virtual_includes/essential/drake/common/drake_bool.h:60:24: error: cannot convert 'drake::Bool<drake::symbolic::Expression>::formula_t {aka drake::symbolic::Formula}' to 'bool' in initialization
   return bool{b.value()};
                        ^
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by sherm1** [comment]
Nice -- thanks, @soonho-tri!

I agree with @jwnimmer-tri that symbolic witness function evaluation is rather ... um ... speculative, but since there was already a `decltype(T() < T())` there I'm happy to see it improved. The question of whether it should have been doing that all remains unresolved. Would be good to have an example of this being used in a less controversial case also.

Feature :lgtm: with a few comments, ptal.

---

Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[common/drake_bool.h, line 9 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Nmgj3KulSL74wp2G:-L8-Nmgj3KulSL74wp2H:b3mnpd8) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L9)):*
> ```objc
> namespace drake {
> 
> /// Class representing a formula whose variables are T-typed.
> ```

BTW I think this is emphasizing the wrong thing since "formula" as used here is a symbolic term of art. Consider instead something like:
```
/// Class representing a boolean value independent of the underlying
/// scalar type. 
```
Then your comments below make clear what happens in the various cases.

---

*[common/drake_bool.h, line 14 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Oq-B0hVymlM-looK:-L8-Oq-B0hVymlM-looL:bix6c5p) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L14)):*
> ```objc
> ///
> /// A value of this class is *not* contextually convertible to bool. As a result
> /// the following code does not compile.
> ```

BTW would like to see sample code that _does_ compile first, to contrast with the failure case below.

---

*[common/drake_bool.h, line 33 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7ztZR-2ZfNMHsPtevu:-L8-MYQd98ZlaCSgv6Pn:b-3ogsah) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I suggest either `value_type` to match STL containers such as vector or optional, or else `SomeCamelName` to match GSG.
</blockquote></details>

FYI I think value_type would be most conventional (see [std::false_type](http://www.cplusplus.com/reference/type_traits/false_type/), e.g.)

---

*[common/symbolic_formula.h, line 1085 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Q2Gr7JzPydzogBKT:-L8-Q2Gr7JzPydzogBKU:b-ktqg1c) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/symbolic_formula.h#L1085)):*
> ```objc
> /// Specialization of ExtractBoolOrThrow for `Bool<symbolic::Expression>`
> /// which includes `symbolic::Formula`. It calls `Evaluate` with an empty
> /// environment.
> ```

BTW consider adding "... and throws if there are variables in the expression."

---

*[common/test/drake_bool_test.cc, line 72 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-QcC9CH8Yw94I1VBV:-L8-QcC9CH8Yw94I1VBW:b-7ajuaa) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L72)):*
> ```cpp
> GTEST_TEST(BoolTest, DoubleValue) {
>   const Bool<double> b{3.0 < 4.0};
>   EXPECT_EQ(b.value(), 3.0 < 4.0);
> ```

BTW consider `EXPECT_EQ(b.value(), true);`. Going out on a limb here, I know :)

---

*[common/test/drake_bool_test.cc, line 95 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-RAYK0F3vS1_mRS7A:-L8-RAYK0F3vS1_mRS7B:b-ikaczu) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L95)):*
> ```cpp
>   const AutoDiffXd y(4., Eigen::Vector2d{0., 1.});
>   const Bool<AutoDiffXd> b{x < y};
>   EXPECT_EQ(b.value(), x < y);
> ```

FYI you could just include this line in the previous test.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-:-L8-S0KAEJWrIPYeygc_:ba0t7gg)*

**Comment by soonho-tri** [comment]
I've updated the PR based on the comments. PTAL.

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[common/drake_bool.h, line 9 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Nmgj3KulSL74wp2G:-L801CKFBaipF4srfriK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think this is emphasizing the wrong thing since "formula" as used here is a symbolic term of art. Consider instead something like:
```
/// Class representing a boolean value independent of the underlying
/// scalar type. 
```
Then your comments below make clear what happens in the various cases.
</blockquote></details>

Done.

---

*[common/drake_bool.h, line 14 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Oq-B0hVymlM-looK:-L801nNfEzc_RbskhNGh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would like to see sample code that _does_ compile first, to contrast with the failure case below.
</blockquote></details>

Done.

---

*[common/drake_bool.h, line 33 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7ztZR-2ZfNMHsPtevu:-L8-2y7i6EzvNb3UFVle:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I suggest either `value_type` to match STL containers such as vector or optional, or else `SomeCamelName` to match GSG.
</blockquote></details>

Done.

---

*[common/drake_bool.h, line 57 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zw0gI3BlnUaYAn1JP:-L8-2yOL7BBZ8EBIyy1Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/drake_bool.h#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider explaining to the reader _why_ this might fail (i.e., unbound variables).
</blockquote></details>

Done.

---

*[common/symbolic_formula.h, line 1085 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-Q2Gr7JzPydzogBKT:-L801ySkBF7zWV_DxLnz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/symbolic_formula.h#L1085)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding "... and throws if there are variables in the expression."
</blockquote></details>

Done.

---

*[common/test/drake_bool_test.cc, line 48 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zwVl0-RYg_pOQBuhk:-L8-GoBiPnrJJA4QXHVT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Just EXPECT_TRUE on each individually?  If they both ended up false, this would incorrectly pass.
</blockquote></details>

Done.

---

*[common/test/drake_bool_test.cc, line 89 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L7zwxCz2Yj7mLp-xCBV:-L8-GouqMJz-bry51_vQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For thoroughness, might as well test the reverse (false) as well?
</blockquote></details>

Done.

---

*[common/test/drake_bool_test.cc, line 95 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-RAYK0F3vS1_mRS7A:-L806FHt6CGwc_KdTYRg:bxyo8u6) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI you could just include this line in the previous test.
</blockquote></details>

Done? I've rewritten this test file. PTAL.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-:-L806xxH4MCiUKBHtGch:botw99u)*

**Comment by soonho-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 72 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L8-QcC9CH8Yw94I1VBV:-L8074ch0HpeLLQLVoyr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e19cc127d914c34d2a480f2fd6f73acbff2c58c/common/test/drake_bool_test.cc#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `EXPECT_EQ(b.value(), true);`. Going out on a limb here, I know :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by jwnimmer-tri** [comment]
:lgtm: feature and platform.

---

Reviewed 7 of 9 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L809wumEWiRoMKt_Ae7:-L809wumEWiRoMKt_Ae8:b-cct1u1) (no related file):*
FYI The commit message subject still stays `bool_t`.

---

*[common/drake_bool.h, line 13 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L80981uEEKSv0LSNX_B:-L80981uEEKSv0LSNX_C:bwhnolc) ([raw file](https://github.com/robotlocomotion/drake/blob/1ecfc361b5d576a5fda71ab8d2cb35a8318620d9/common/drake_bool.h#L13)):*
> ```objc
> /// scalar type T.
> /// For T = `double` and `AutoDiffXd`, this class includes a `bool` value.
> /// For T = `symbolic::Expression`, a `symbolic::Formula` is embedded.
> ```

FYI Consider using parallel phrasing for clarity:
- For double or autodiff, this class embeds a `bool` value.
- For expression, this class embeds a symbolic::Formula value.

---

*[common/drake_bool.h, line 61 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L809TqyDlwN9d6TzZLW:-L809TqyDlwN9d6TzZLX:btpqgb) ([raw file](https://github.com/robotlocomotion/drake/blob/1ecfc361b5d576a5fda71ab8d2cb35a8318620d9/common/drake_bool.h#L61)):*
> ```objc
> 
>  private:
>   value_type value_;
> ```

BTW Missing moustache on possibly-POD type.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-:-L8089V5-RfLu-MlWnFL:b-1i7w6f)*

**Comment by soonho-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L809wumEWiRoMKt_Ae7:-L80C5RF59XHnLxfqQ80:bt2vr1b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The commit message subject still stays `bool_t`.
</blockquote></details>

Fixed.

---

*[common/drake_bool.h, line 13 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L80981uEEKSv0LSNX_B:-L80AsAi2mCsHScfGnNY:b-ioxi1u) ([raw file](https://github.com/robotlocomotion/drake/blob/1ecfc361b5d576a5fda71ab8d2cb35a8318620d9/common/drake_bool.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider using parallel phrasing for clarity:
- For double or autodiff, this class embeds a `bool` value.
- For expression, this class embeds a symbolic::Formula value.
</blockquote></details>

Done. Thank you.

---

*[common/drake_bool.h, line 61 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-L809TqyDlwN9d6TzZLW:-L80Aur6A02VaoWkdJAo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1ecfc361b5d576a5fda71ab8d2cb35a8318620d9/common/drake_bool.h#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing moustache on possibly-POD type.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404)*

**Comment by sherm1** [comment]
Perfect, thanks @soonho-tri.

---

Reviewed 6 of 9 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8404#-:-L80UsMi4ySYJ1tJcJV4:bcpq0nd)*

**Pull request merged**
