### PR TITLE
Remove MATLAB Valkyrie example

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6368)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Valkyrie/README.md, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-KmnL_G4J-tzlG15cEkv:-KmnL_G5fdZxfVwrG9z9:b-w8qyxk) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6fbc02add0c35a024ebc56180b7e1130fe7382/drake/examples/Valkyrie/README.md#L38)):*
> ```Markdown
> Most of that was removed from the head of git master during 2017.
> 
> To view or use the original MATLAB implementation of Atlas you may use this tag:
> ```

s/Atlas/Valkyrie/; will fix in the next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368)*

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-:-Kn-k9GHx4Vvd0sUiZgU:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.
-(status: do not merge) 

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-:-Kn-kWsHPQ4oVbjQGT5N:bxpspci)*

**Comment by ggould-tri** [comment]
Does @russtedrake 's previous comment (from the Atlas PR) about opening an issue for this (and thus my previous comment about noting it in the readme) apply here as well?

---

Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-:-Kn0RP5pUUNVQM9td7qR:bmpd5pq)*

**Comment by jwnimmer-tri** [comment]
I think this is okay as-is; we can ping @siyuanfeng-tri in case he things there needs to be more documentation, but that can be a follow-up PR if need be.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-:-Kn0i61Sua0nkVnhL3uF:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6368#-:-Kn0loL6DnUoR3MXeyNR:bnfp4nl)*

**Pull request merged**
