### PR TITLE
Remove SimpleFourBar example code (but not models)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The MATLAB software is no longer supported and being removed.

The model data is cited by the URDF specification and used in a C++ unit test, so needs to stay around.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6269)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6269#-:-KmQlDjLcBv6Uy0yGu70:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@ggould-tri for all review, please.  (I'm manually cycling the MATLAB PRs through platform review, off-schedule.)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6269#-:-KmRYz_o_elwKPy696DH:bybu15w)*

**Comment by ggould-tri** [comment]
The resulting contents of this directory -- a `BUILD` file, a `dev` directory, and model files, if I read it correctly -- is surprising and needs some explanation.  I recommend a simple two-ish line readme explaining why it contains what it does, and why those contents should not be deleted.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6269#-:-KmS2MjCfamUlqfvFG63:b3d2sf5)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6269#-:-KmScNhkXO9DNb76w0U0:b-83330m)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6269#-:-KmSd4z4uOGBLL3XDGdu:bnfp4nl)*

**Pull request merged**
