### PR TITLE
Update iiwa mass/interia values 

### PR DESCRIPTION
**Pull request by sammy-tri**
...to behave in a slightly more realistic manner when fed recorded torques from a stationary arm.

(with thanks to Harvard Agile Robotics Lab, who I copied these values from)

Tested by feeding in constant torque values recorded from a stationary arm and qualitatively determining that these parameters kept the arm in steady state for considerably longer (still not very long) than the previous values.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4631)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-:-K_6ftjF1lhhRR0aMnZF:b-psw9ws)*

**Comment by naveenoid** [comment]
Im ok with these values but the history of this change must be recorded on the URDF itself. i.e. within the comment tag on top.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_8VuflbPj0cIU1juVN:-K_8VuflbPj0cIU1juVO:bcjxsve) ([raw file](https://github.com/robotlocomotion/drake/blob/d105223ce7ab89b27ab25b6fc9c305b78d0d5204/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L7)):*
> ```XML
>      underwent changes and therefore cannot be exactly generated from the
>      original source file. See pull requests #2163 and #2520.
> ```

Please comment about the parameter modifications here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-:-K_8VgFWTD3SS8mZsFjG:b-wwwt0a)*

**Comment by sammy-tri** [comment]
Done.  +@ggould-tri for platform review.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_8VuflbPj0cIU1juVN:-K_ADiFXS5B7nBk7TJCe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d105223ce7ab89b27ab25b6fc9c305b78d0d5204/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L7)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Please comment about the parameter modifications here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-:-K_ADimg2pb7HTW2LrJt:bf8w1c8)*

**Comment by ggould-tri** [comment]
:lgtm: But requested a couple of optional sanity checks below just to be sure.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K_AFp2GzV5Uc_8nY6gx:b71ggtx) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
> ```XML
>       <origin rpy="0 0 0" xyz="0 0.03 0.13"/>
>       <mass value="3.5"/>  
>       <inertia ixx="0.025" ixy="0" ixz="0" iyy="0.0238" iyz="0.00487" izz="0.0076"/>
> ```

BTW -- I am surprised to find an off-diagonal term here, and even more so that it is between the long axis and one short axis (but not the other).  Author should double-check that this is intended; if it is then no defect (but the implications of this for controller tuning may be a bit complicated).

The same comment applies to each of the changes below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-:-K_AGlYZMMd7t4dY1Qp8:b-fds8o9)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K_AHTScF55K-fXWsgsE:b-syq4ny) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- I am surprised to find an off-diagonal term here, and even more so that it is between the long axis and one short axis (but not the other).  Author should double-check that this is intended; if it is then no defect (but the implications of this for controller tuning may be a bit complicated).

The same comment applies to each of the changes below.
</blockquote></details>

Good catch.  I'll have to test a bit more (sanity check, you are referring to the iyz term, right?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K_AIC3QzwF-K_KbATq9:b-4stuqv) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Good catch.  I'll have to test a bit more (sanity check, you are referring to the iyz term, right?)
</blockquote></details>

Yes.  Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K_AgjdhhngeIN2eJLdn:b-309ag2) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Yes.  Thanks.
</blockquote></details>

Zeroed out the iyz interia terms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-:-K_CfAb7UgWXmIbhM49D:bnfp4nl)*

**Comment by YeZhao** [comment]
*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K__p5n21ygZo9qz2fZW:b-h2hfiq) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Zeroed out the iyz interia terms.
</blockquote></details>

As a late side comment, the off-diagonal term Iyz was referred from Kuka CAD model. Here attached is a solidworks screenshot with link 3 parameters. Maybe there is an error there or it is caused by other factors, like the slightly irregular geometry of each link (although all of them look like a cylinder).


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Comment by YeZhao** [comment]
*[drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4631#-K_AFp2GzV5Uc_8nY6gw:-K__tegtpGr91tppQh6d:bvhwjmt) ([raw file](https://github.com/robotlocomotion/drake/blob/095823484132b9edc4c60e00e8b3bd4051e327c0/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf#L152)):*
> As a late side comment, the off-diagonal term Iyz was referred from Kuka CAD model. Here attached is a solidworks screenshot with link 3 parameters. The second last set of inertia parameters is the one used (e.g., Taken at the center of mass and aligned with the output coordinate system) Also the unit is pound*inch^2, after converting to kg*m^2, the numbers are the ones we had. Maybe there is an error there or it is caused by other factors, like the slightly irregular geometry of each link (although all of them look like a cylinder).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4631)*

**Pull request merged**
