### PR TITLE
Add Bazel macro for cc_googletest

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Replaces #4480.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4549)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Versus #4480, this backs away from `cc_component`.  I think people _should_ use single-component libraries, but the BUILD boilerplate is arguably more clear when written out explicitly.

However, the googletest ceremony probably doesn't add value, so rolling it up into a macro should be a net win.  It _does_ slightly obscure the `test/name.cc` default, but that is unlikely to cause much debugging pain, and helps helps encourage us to keep our test names and source names identical, which is better for everyone.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for conceptual review, please.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-:-KZOn6Jrk16yenKl5vtr:b-wo3b4g)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-:-KZSEkZfX9NrXUPlAIt6:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 24 of 24 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549)*

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for full review, please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-:-KZSRzVbRqgXxls228u5:b-poh2gp)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549)*

**Comment by rpoyner-tri** [comment]
Reviewed 23 of 24 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-KZXym_vsQtLONsyXxwq:-KZXym_vsQtLONsyXxwr:bw1ax19) ([raw file](https://github.com/robotlocomotion/drake/blob/3268894ecca598538c6a9dadb3ee8fafff8574f7/drake/solvers/BUILD#L157)):*
> ```Python
> cc_test(
>     name = "system_identification_test",
>     size = "medium",
> ```

i assume this original size estimate was in error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549)*

**Comment by jwnimmer-tri** [comment]
*[drake/solvers/BUILD, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-KZXym_vsQtLONsyXxwq:-KZXzHf2ZKDMfpNkGSaS:bxgkn4y) ([raw file](https://github.com/robotlocomotion/drake/blob/3268894ecca598538c6a9dadb3ee8fafff8574f7/drake/solvers/BUILD#L157)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

i assume this original size estimate was in error?
</blockquote></details>

Yeah, `size` was wrong.  Possibly `timeout="medium"` should be here, but I was going to tag all of those in a separate pass later, after taking a little survey of a few different build environments.  I can keep this one `timeout="medium"` for now though if you prefer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549)*

**Comment by jwnimmer-tri** [comment]
Review status: 23 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-KZXym_vsQtLONsyXxwq:-KZY4DeLG88b-faPQxBY:b-ovtk5f) ([raw file](https://github.com/robotlocomotion/drake/blob/3268894ecca598538c6a9dadb3ee8fafff8574f7/drake/solvers/BUILD#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, `size` was wrong.  Possibly `timeout="medium"` should be here, but I was going to tag all of those in a separate pass later, after taking a little survey of a few different build environments.  I can keep this one `timeout="medium"` for now though if you prefer?
</blockquote></details>

For me the test is 41s, which is still "short", so I think this is fine.  For this PR, I fixed up the only test that complained on my box, which was in maliput.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/solvers/BUILD, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-KZXym_vsQtLONsyXxwq:-KZY75nAefwBFB-nIEJs:b-fxdt2u) ([raw file](https://github.com/robotlocomotion/drake/blob/3268894ecca598538c6a9dadb3ee8fafff8574f7/drake/solvers/BUILD#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For me the test is 41s, which is still "short", so I think this is fine.  For this PR, I fixed up the only test that complained on my box, which was in maliput.
</blockquote></details>

meh, it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4549#-:-KZY7CmAAv67ddMeCXGF:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Only MATLAB and opensourcedebug builds remain. Using override-merge for Bazel-only change.

**Pull request merged**
