### PR TITLE
Add EvaluateParatial and Substitute in Python binding

### LINKED ISSUE #8547: Add EvaluateParatial and Substitute in Python binding
feature requested by @TobiaMarcucci

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #8547

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8549)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@EricCousineau-TRI for feature-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/symbolic_py.cc, line 174 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-L9e64uw6o5l96yjTYvS:-L9e64uw6o5l96yjTYvT:b-4oltgr) ([raw file](https://github.com/robotlocomotion/drake/blob/e10caca103c19428bd0dd401417521e33d97b8b9/bindings/pydrake/symbolic_py.cc#L174)):*
> ```cpp
>            [](const Expression& self, const Variable& var,
>               const Expression& e) { return self.Substitute(var, e); })
>       .def("Substitute",
> ```

I'm wondering if there is a way to remove this and the following overloads. For now, without them, the tests do not pass.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-:-L9e602E7Vg5i1te-c0g:b-epwmsv)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 174 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-L9e64uw6o5l96yjTYvS:-L9evtEv9AcxjKGAiX8O:bqsf7al) ([raw file](https://github.com/robotlocomotion/drake/blob/e10caca103c19428bd0dd401417521e33d97b8b9/bindings/pydrake/symbolic_py.cc#L174)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm wondering if there is a way to remove this and the following overloads. For now, without them, the tests do not pass.
</blockquote></details>

It's because the literal at line 552 is an `int`, and `pybind` does not permit transitive conversions:
https://github.com/pybind/pybind11/blob/289e5d9cc2a4545d832d3c7fb50066476bce3c1d/include/pybind11/pybind11.h#L1629

If you change `3` to `3.`, you can collapse the overloads. I will briefly see if adding `implicitly_convertible<int, Expression>` does anything.

---

*[bindings/pydrake/symbolic_py.cc, line 180 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-L9etqsbAuzZfmYxB70_:-L9etqsbAuzZfmYxB70a:b-5vghmv) ([raw file](https://github.com/robotlocomotion/drake/blob/e10caca103c19428bd0dd401417521e33d97b8b9/bindings/pydrake/symbolic_py.cc#L180)):*
> ```cpp
>                             const double v) { return self.Substitute(var, v); })
>       .def("Substitute",
>            [](const Expression& self, const Substitution& s) {
> ```

Is `Substitution` currently bound in Python? I cannot find its binding.
Would it be possible to just remove this for now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/symbolic_py.cc, line 174 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-L9e64uw6o5l96yjTYvS:-L9ewZfG3cw9sp_XPaqJ:bvrqn69) ([raw file](https://github.com/robotlocomotion/drake/blob/e10caca103c19428bd0dd401417521e33d97b8b9/bindings/pydrake/symbolic_py.cc#L174)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's because the literal at line 552 is an `int`, and `pybind` does not permit transitive conversions:
https://github.com/pybind/pybind11/blob/289e5d9cc2a4545d832d3c7fb50066476bce3c1d/include/pybind11/pybind11.h#L1629

If you change `3` to `3.`, you can collapse the overloads. I will briefly see if adding `implicitly_convertible<int, Expression>` does anything.
</blockquote></details>

Yup, adding that line allows it to pass, and I didn't get any warnings.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-:-L9ewgol-pWeUpSGhLCy:b-2l0s3s)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8549#-:-L9gcBzY2SZAZzQPQQhG:bcpz082)*

**Pull request merged**
