### PR TITLE
[pydrake] Resolve dependency cycle across root modules

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Refer to the commit message for details.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.  +@EricCousineau-TRI for platform review, please (but feel free to chime in on feature review, too).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-:-NiFHkJjCfzkfFShl7Q3:bx3x5j3)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFHhlz1yHqIatM7Esj:-NiFHhlz1yHqIatM7Esk:bfpzpz1) (no related file):*
Working

Anzu integration build 234 in progress.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFHhlz1yHqIatM7Esj:-NiFaBFH-6NDUu1m6iDr:bmy76zv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Anzu integration build 234 in progress.
</blockquote></details>

OK passed (build 235, after a rebase).

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFaQQV36IEix-NLcj_:-NiFczCl-KsQsP0M84oU:bgxpfng) ([raw file](https://github.com/RobotLocomotion/drake/blob/e59e93db0b659d1091c9ad958c59dcd4cce3f766/bindings/pydrake/symbolic/_symbolic_extra.py#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I am not familiar with this constraint. Will see what the error looks like.
</blockquote></details>

Ah, `_symbolic_sympy` is a module, derp.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`-- commits` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFZlwy1r4bEDIaZ09M):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider stating "can eventually" given next paragraph
</blockquote></details>

IIRC we do actually fix _some_ of the problems with our new module_py init order.  Rephrased.
___
*[`-- commits` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFZtnZCoerfk3GsUj7):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I'm not sure if this is accurate - it is not strictly re-importing, but instead just import order.

Now that these cyclic modules are loaded at the same time, they need access to the pure Python functions.

Before this PR, their definitions happened after `pydrake.__init__` had already loaded its pure Python functions before the bindings for `autodiff`, `value`, etc. were defined.
After this PR, their definitions happen before `pydrake.__init__` is finished loading.
</blockquote></details>

Yeah.  It was somewhat more complicated in earlier of my drafts where both `common/__init__.py` and `common/_module_py.so` were separate modules.
___
*[`bindings/pydrake/common/BUILD.bazel` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFa2MsDvzP6km-p4Y6:-NiFf-XPBij1fvvPwBoq:be4vwwk) ([raw file](https://github.com/RobotLocomotion/drake/blob/e59e93db0b659d1091c9ad958c59dcd4cce3f766/bindings/pydrake/common/BUILD.bazel#L112)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This could also be remedied by including `# noqa: shebang` in the generated file.
</blockquote></details>

Wow, so much better!
___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-NiFaQQV36IEix-NLcj_:-NiFeQBl7mOKkdU7q6Ps:bd4xpe8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e59e93db0b659d1091c9ad958c59dcd4cce3f766/bindings/pydrake/symbolic/_symbolic_extra.py#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, `_symbolic_sympy` is a module, derp.
</blockquote></details>

Yeah.  The "conditionally depend on `import sympy`" leads to some awkward code organization.  Sigh.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 31 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 17 of 31 files at r1, 2 of 4 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465#-:-NiLwWfQ5JG5KcFeAlr_:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20465)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
