### PR TITLE
[workspace] Upgrade rules_python to 0.36.0

### PR DESCRIPTION
**Pull request by nicolecheetham**
Tries to upgrade rules_python to 0.37.2.

When running the command to upgrade rules_python the build failed locally

Output:
```
/rules_python/python/private/reexports.bzl", line 37, column 23, in <toplevel>
                BuiltinPyInfo = config.BuiltinPyInfo
Error: 'struct' value has no field or method 'BuiltinPyInfo'
Available attributes: enable_pystar

initialization of module 'python/private/reexports.bzl' failed
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-OB2Kc3y3fNnK5o9i2ju:-OB2Kc3z8PvhqYy_t6p7:b1i4ged) (no related file):*
Notes so far:
* bumping to version 0.36.0 works fine.
*  even with refreshing the vendored file `third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl`:
** any later version is broken.
** any later *commit* is broken.

I'm about to time out on this for today. Perhaps we bump to 0.36.0 for now and file an issue to integrate later versions?
/cc @jwnimmer-tri 

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-OB2Kc3y3fNnK5o9i2ju:-OB2NSXC2ZUE96G5y41s:b6vzupg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Notes so far:
* bumping to version 0.36.0 works fine.
*  even with refreshing the vendored file `third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl`:
** any later version is broken.
** any later *commit* is broken.

I'm about to time out on this for today. Perhaps we bump to 0.36.0 for now and file an issue to integrate later versions?
/cc @jwnimmer-tri
</blockquote></details>

Oh, huh. looks like maybe "everything works" if I delete the vendoring entirely. Time to excavate the original intent of that stuff.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-OB2Kc3y3fNnK5o9i2ju:-OB2O16Y3j4RjUJqs8wJ:bed43ph) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Oh, huh. looks like maybe "everything works" if I delete the vendoring entirely. Time to excavate the original intent of that stuff.
</blockquote></details>

Nope, that just evades the first hurdle. brrrr

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-OB2Kc3y3fNnK5o9i2ju:-OB6rS1uDUXdhvPW9IOw:b9c7xwu) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nope, that just evades the first hurdle. brrrr
</blockquote></details>

I'm tapping out. From what I can understand, the `WORKSPACE` style configuration now requires a whole mess of internal-to-rules starlark files to load and run, way more than can be trivially vendored.

___

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-:-OBVhlYIDh6KZrt_5Gn_:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22129#-:-OBVhxfD225UAszPCIE3:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
