### PR TITLE
Add toy example of parsing phases

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per action item in https://github.com/RobotLocomotion/drake/pull/16727#issuecomment-1333972776

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)* status: 1 unresolved discussion, LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @azeey)

___
*[`tmp/parsing_toy.py` line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NImKMaF86B0wrZMivOJ:-NImKMaGEuwlnpesZNzL:bqyqo2d) ([raw file](https://github.com/robotlocomotion/drake/blob/c0f7e3c8d67c2c5bfbfff364422129e8bafdddec/tmp/parsing_toy.py#L100)):*
> ```Python
> 
> 
> # TODO: Add in placement_frame functionality to show (or maybe resolve?)
> ```

+@azeey Can you take a stab at this when you have a chance?

**Comment by azeey** [comment]
I've updated the code to show why I think callbacks are needed for custom parsers. IMO the main issue is what's discussed here: https://github.com/RobotLocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L406-L419

 @EricCousineau-TRI @jwnimmer-tri PTAL.

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! Posted request for comments based on this in https://github.com/RobotLocomotion/drake/pull/16727#issuecomment-1432211797

I've made requests for this prototype, but if it's more clear to pursue a direct prototype as mentioned in #16727 then we can defer any changes here.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422#-:-NOMLW6DCAUWp_fsvxuB:b-8vja9g)* status: 3 unresolved discussions, LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @azeey)

___
*[`tmp/parsing_toy.py` line 376 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMCTM28nvXPOYQpgmS:-NOMCTM28nvXPOYQpgmT:bse9ii5) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L376)):*
> ```Python
>         for directive in schema:
>             if isinstance(directive, FrameSchema):
>                 # We'll assume that all poses of frames parsed the custom
> ```

nit Unclear why we don't use `resolve_pose` here and below for this example?

Alternatively, should assert based on expectations.
___
*[`tmp/parsing_toy.py` line 421 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMMLSG0Ott4WdLkxef:-NOMMLSG0Ott4WdLkxeg:b-yz8o6h) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L421)):*
> ```Python
>         plant.add_frame(link.name, model_instance, frame.attached_to, X_PF)
> 
>     # We'll assume that nested models have already been parsed through the
> ```

I believe reposturing is an important facet of a fully resolved pose graph.

Is it possible to include here?
___
*[`tmp/parsing_toy.py` line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOM6SKv1zBp9S_rL4Kn:-NOM6SKv1zBp9S_rL4Ko:bhlybuy) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L431)):*
> ```Python
>     def test_expected(self):
>         plant = mock_drake_sdf_parser("top", "top.model")
>         self.assertEqual(plant.num_bodies(), 3)
> ```

This should still check kinematics, as that's necessary to ensure pose resolution is functioning as expected.

Can you restore / update the testing for "nuanced" element(s)
 (e.g. elements that are affected both by nested relative-to statements as well as nested posturing?)

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)* status: 3 unresolved discussions, LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`tmp/parsing_toy.py` line 376 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMCTM28nvXPOYQpgmS:-NOR57s--YDn532QT_Kf:b4le3hm) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L376)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why we don't use `resolve_pose` here and below for this example?

Alternatively, should assert based on expectations.
</blockquote></details>

We don't use `resolve_pose` because we assume the poses are already in the frame we want--relative to the parent frame. If that weren't the case, the current (merged) implementation would have needed a PoseGraph type functionality to resolve poses within the nested (custom parsed) model. 
___
*[`tmp/parsing_toy.py` line 421 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMMLSG0Ott4WdLkxef:-NOR6-ke525Rn6EdSxYa:b-86evoj) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L421)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe reposturing is an important facet of a fully resolved pose graph.

Is it possible to include here?
</blockquote></details>

Sure, I'll work on it.
___
*[`tmp/parsing_toy.py` line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOM6SKv1zBp9S_rL4Kn:-NOR65Kk609MmBCybh8p:bpszu1b) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L431)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This should still check kinematics, as that's necessary to ensure pose resolution is functioning as expected.

Can you restore / update the testing for "nuanced" element(s)
 (e.g. elements that are affected both by nested relative-to statements as well as nested posturing?)
</blockquote></details>

I removed it because I thought the toy example was meant to show why the callback/Interface API was necessary. I can add test expectations if we want to make sure things are functioning as expected.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)* status: 3 unresolved discussions, LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @azeey)

___
*[`tmp/parsing_toy.py` line 376 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMCTM28nvXPOYQpgmS:-NORHPsX4WFQ6GqCMNrv:b-v0rb2e) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L376)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

We don't use `resolve_pose` because we assume the poses are already in the frame we want--relative to the parent frame. If that weren't the case, the current (merged) implementation would have needed a PoseGraph type functionality to resolve poses within the nested (custom parsed) model. 
</blockquote></details>

Gotcha, avoiding the need for additional work sounds good; however, could you then assert that the `relative_to` frame is as expected?
(basically, "assume"= > "assert"?)
___
*[`tmp/parsing_toy.py` line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOM6SKv1zBp9S_rL4Kn:-NORHeNJ4Tmo6p5lB5Vm:b-mi7bjk) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L431)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I removed it because I thought the toy example was meant to show why the callback/Interface API was necessary. I can add test expectations if we want to make sure things are functioning as expected.
</blockquote></details>

Yup, hopefully the expected values and checks are sufficiently simple so that it's not too much overhead!

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)* status: LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`tmp/parsing_toy.py` line 376 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMCTM28nvXPOYQpgmS:-NOysBzy0zbV_Mj_on1b:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L376)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha, avoiding the need for additional work sounds good; however, could you then assert that the `relative_to` frame is as expected?
(basically, "assume"= > "assert"?)
</blockquote></details>

Done
___
*[`tmp/parsing_toy.py` line 421 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOMMLSG0Ott4WdLkxef:-NPAX1rg9e-tfv3DR_vw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L421)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Sure, I'll work on it.
</blockquote></details>

Done.
___
*[`tmp/parsing_toy.py` line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOM6SKv1zBp9S_rL4Kn:-NPAWjaW0Dp4f68aSQbx:b-4obkim) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L431)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup, hopefully the expected values and checks are sufficiently simple so that it's not too much overhead!
</blockquote></details>

Done. There was a copy/paste bug exposed by the test :) And, as you mentioned, reposturing was necessary to have correct poses for some of the frames.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18422)* status: LGTM missing from assignee azeey, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @azeey)

___
*[`tmp/parsing_toy.py` line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18422#-NOM6SKv1zBp9S_rL4Kn:-NPPOqNG4Ov9-KZ0wpDu:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake/blob/08af8a51776cefc24f432f4026f0dfa566c75a00/tmp/parsing_toy.py#L431)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Done. There was a copy/paste bug exposed by the test :) And, as you mentioned, reposturing was necessary to have correct poses for some of the frames.
</blockquote></details>

OK Sweet, thanks!

**Comment by jwnimmer-tri** [comment]
Closing as abandoned. When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
