### PR TITLE
Clean up and update docker instructions to optionally use nvidia-docker 2.0

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10897)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review and local testing (particular the `nvidia-docker` instructions.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/docker.rst, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10897#-L_nDPvGE5Z4LGd3lDjk:-L_nG4706NCy5Freuc4D:b-1zlj3f) ([raw file](https://github.com/robotlocomotion/drake/blob/6d46420ea92d3a6e627ff1665e13d1f55faf20e4/doc/docker.rst#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same thing here: Can we just reference to the instructions? (Even if it's a fixed commit?)
</blockquote></details>

OK Nevermind on this one; the NVIDIA CUDA installation instructions are a spiderweb of disgusting.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/docker.rst, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10897#-L_nHPIHBSiNIPxlZ8K2:-L_nHPIHBSiNIPxlZ8K3:bm8b2yf) ([raw file](https://github.com/robotlocomotion/drake/blob/6d46420ea92d3a6e627ff1665e13d1f55faf20e4/doc/docker.rst#L88)):*
> ```reStructuredText
>   sudo apt-get update
>   sudo apt-get install --no-install-recommends build-essential linux-headers-$(uname -r) wget
>   wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.105-1_amd64.deb
> ```

Silly me... I tried upgrading CUDA versions from what we have on Anzu, and it borked my system.
Will post update shortly.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/docker.rst, line 208 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10897#-LaaRnEu0VQtLXw_XKp8:-LaaRnEv66zwScCfwmUN:bicp6hd) ([raw file](https://github.com/robotlocomotion/drake/blob/92f110d4db109ba053a58c3cb5caaddae6304933/doc/docker.rst#L208)):*
> ```reStructuredText
>   cd drake
>   docker build \
>     --file setup/ubuntu/docker/bionic/Dockerfile.nvidia-cuda-9.0-devel-ubuntu18.04 \
> ```

Per below conversion, this file needs to be updated.

**Comment by EricCousineau-TRI** [comment]
Hm... Seems like the multiline bits have been longstanding: https://github.com/moby/moby/issues/34423
Won't hold my breath.

**Pull request merged**
