### PR TITLE
Add a version of controlled_kuka_demo which uses MultibodyPlant.

### PR DESCRIPTION
**Pull request by sammy-tri**
This currently has the same issue as the existing demo (#3869).

My thought is to land this and then fix that issue for both
versions so that they can be reasonably compared.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@seancurtis-tri for feature review to (keeping the load down for @amcastro-tri who was also a co-author anyway and probably shouldn't review the result).

The LOC count is high, but most of it is the sdf file, which is pretty low information density.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDECYt1Bzor02ZOhLUH:b-5pquou)*

**Comment by sammy-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDHKXd39dC3U-a-3X3s:-LDHdyu95AIzX8t0kP4T:binhnm7) ([raw file](https://github.com/robotlocomotion/drake/blob/3b69e7cb5a944bd1398b0fba785668ad3cf353bf/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc#L73)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW This is a good example of what @avalenzu asked yesterday and I don't think I did a good job to answer. Yes, you can make multiple calls to `AddModelFromSdfFile()` and add any other modeling elements (bodies, frames, joints, forces) *before* `Finalize()`. For instance, you could load a file, get the the base body of your robot with `GetBodyByName()` and then fixe it to the world by adding a `WeldJoint`.
</blockquote></details>

Ah, thanks!  That is a clearer explanation.

---

*[examples/kuka_iiwa_arm/controlled_kuka/README.md, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDHLlmu9zoX9t7ukg7M:-LDHeGJN1MnXEwpREOgc:b-avxnyk) ([raw file](https://github.com/robotlocomotion/drake/blob/3b69e7cb5a944bd1398b0fba785668ad3cf353bf/examples/kuka_iiwa_arm/controlled_kuka/README.md#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW 2.
</blockquote></details>

In markdown a list starting entirely with `1.` should get rendered with the proper numbering in the final result  see https://github.com/sammy-tri/drake/blob/kuka_sdf_demo/examples/kuka_iiwa_arm/controlled_kuka/README.md  but improving the readability of the source is beneficial.  Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864)*

**Comment by SeanCurtis-TRI** [comment]
Boy howdy! The gods of CI are *angry*! Do you want me to do my review pass with that much red?

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDHtjOK2OyTEUVyt-Dg:bqbozhb)*

**Comment by sammy-tri** [comment]
Ah, the joys of breaking an unrelated module which relies on transitive dependencies.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDHvZT9CJph4r1VnDt5:b-1mjsuz)*

**Comment by SeanCurtis-TRI** [comment]
Ok, I'll assume it's been fixed and proceed.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDHyFdT76B2zspFj7Pi:b-hk8vy1)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some cosmetic suggestions and curiosities.

---

Reviewed 8 of 10 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDHzT_UC2koMSl7J-NT:-LDHzT_UC2koMSl7J-NU:bw9tx9r) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel#L11)):*
> ```Python
> 
> drake_cc_library(
>     name = "controlled_kuka_plan",
> ```

FYI Is there an alternative to this name that doesn't look like a typo of `controlled_kuka_plant`? Given the ubiquity of `plant`, `plan` generally feels like it will always invite a soupcon of confusion. Possibly "controlled_kuka_trajectory"?

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0zWa7ZMH4csSk_Nt:-LDI0zWa7ZMH4csSk_Nu:bgb9u9q) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc#L8)):*
> ```cpp
> /// the zero configuration to reach to a position in space and then
> /// repeat this reaching task with a different joint configuration
> /// constraint.
> ```

FYI I'm surprised this documentation is formatted differently from `controlled_kuka_demo` -- it doesn't fill up the space.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI1a63EAD-EfD0L7RF:-LDI1a63EAD-EfD0L7RG:bywcq1l) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc#L87)):*
> ```cpp
> 
>   // Sanity check on the availability of the optional source id before using it.
>   DRAKE_DEMAND(!!kuka_plant.get_source_id());
> ```

BTW Might be worth moving it to *before* the DrakeLcm stuff. After all, if there's no source id, there's no point in generating that cruft.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI-Dhx4mbnMkrlZv--:-LDI-Dhx4mbnMkrlZv-0:bsdcmiv) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc#L28)):*
> ```cpp
> const char kUrdfPath[] =
>     "drake/manipulation/models/iiwa_description/urdf/"
>     "iiwa14_polytope_collision.urdf";
> ```

BTW Leaving this as the urdf? Does that invite an inherent disconnect between MBP and RBP? 

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0jqu38AKLKruU7my:-LDI0jqu38AKLKruU7mz:bcd45hl) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L1)):*
> ```
> <?xml version="1.0" ?>
> ```

FYI I'm stipulating that the constants are all correct here. I'm not doing a diff with a urdf.  :D

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0WnM0OESZu4qp3f5:-LDI0WnM0OESZu4qp3f6:b98pjz8) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L33)):*
> ```
>         </geometry>
>         <material>
>           <script>
> ```

FYI Do we care that this material definition is neither parsed, nor valid (in the sense that that file doesn't exist in drake)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDI2KpC6_aCbiv1ObsE:b-4hxnd3)*

**Comment by sammy-tri** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDHzT_UC2koMSl7J-NT:-LDI5WteCv9uzB2TfL7T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Is there an alternative to this name that doesn't look like a typo of `controlled_kuka_plant`? Given the ubiquity of `plant`, `plan` generally feels like it will always invite a soupcon of confusion. Possibly "controlled_kuka_trajectory"?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0zWa7ZMH4csSk_Nt:-LDI5g6R-F3jXKy2dDoW:b-2b39cx) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'm surprised this documentation is formatted differently from `controlled_kuka_demo` -- it doesn't fill up the space.
</blockquote></details>

Huh, I guess was using a more aggressive line wrapping column than needed.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI1a63EAD-EfD0L7RF:-LDI6Szh4-x1B7q_Y9An:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc#L87)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Might be worth moving it to *before* the DrakeLcm stuff. After all, if there's no source id, there's no point in generating that cruft.
</blockquote></details>

Done.

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0WnM0OESZu4qp3f5:-LDI7-uG1q0kTn4hPOhL:b-qng2gl) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L33)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Do we care that this material definition is neither parsed, nor valid (in the sense that that file doesn't exist in drake)?
</blockquote></details>

AFAICT it's required to say something according to the spec and this is the autogenerated output...  http://sdformat.org/spec?ver=1.6&elem=material#script_uri

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI-Dhx4mbnMkrlZv--:-LDI7hehCRM9qoAMQlI2:b715ynl) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Leaving this as the urdf? Does that invite an inherent disconnect between MBP and RBP? 
</blockquote></details>

It does in the sense that it allows the models to get out of sync with each other...  which is actually currently the case deliberately since (for example) the SDF has no damping on the joints (not supported in MBP yet) and the URDF does (which RBP simulates).  My thought is that if we're worried about this it bumps the priority of #3869 to make sure the outcomes of the simulations are sufficiently similar.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864)*

**Comment by SeanCurtis-TRI** [comment]
In trying to appease the CI gods, they've merely retreated behind a veneer of ineffable inscrutability.

---

Reviewed 5 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI0WnM0OESZu4qp3f5:-LDID_wN-SwblCEuGcTb:biqzf9l) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L33)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

AFAICT it's required to say something according to the spec and this is the autogenerated output...  http://sdformat.org/spec?ver=1.6&elem=material#script_uri
</blockquote></details>

I just worry about tags in these files that are distributed by drake. I can imagine some other user tweaking tags and then banging their head against the screen when it doesn't seem to change anything.

---

*[examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8864#-LDI-Dhx4mbnMkrlZv--:-LDIDMg05zgmMARXiVXt:brxp9sq) ([raw file](https://github.com/robotlocomotion/drake/blob/d401a42c87a490f1400f0aeabd6869063ed701c1/examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_plan.cc#L28)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It does in the sense that it allows the models to get out of sync with each other...  which is actually currently the case deliberately since (for example) the SDF has no damping on the joints (not supported in MBP yet) and the URDF does (which RBP simulates).  My thought is that if we're worried about this it bumps the priority of #3869 to make sure the outcomes of the simulations are sufficiently similar.
</blockquote></details>

Sounds good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDICu3s2WZO2XvoAk2q:b-bpqyxm)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8864#-:-LDIK2ns4S5AtDo8T3Sw:b-3b5j4i)*

**Pull request merged**
