### PR TITLE
Fix sign-compare warnings in shapes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2874)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
Small comment for my own education only. Otherwise it :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/shapes/Geometry.cpp, line 328 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2874#-KNCgXS54Lm_sVyNqWYW:-KNCgXS54Lm_sVyNqWYX:-1855406029) ([raw file](https://github.com/robotlocomotion/drake/blob/43e0086838d2c71b8db53371c5fc8728b47b9be8/drake/systems/plants/shapes/Geometry.cpp#L328)):*
> ```cpp
>   // Verifies that the maximum index referenced when defining faces does not
>   // exceed the number of vertices.
>   if (maximum_index > static_cast<int>(vertices->size())) {
> ```

This is pretty annoying. What should the best practice be here? to make `maximum_index` an unsigned type or the best solution is just to static cast here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2874#-:-KNCgnwa9kCEO_V1RKw0:1161382297)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/shapes/Geometry.cpp, line 328 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2874#-KNCgXS54Lm_sVyNqWYW:-KNCk6uIaWPP3zoV5JPN:1732208049) ([raw file](https://github.com/robotlocomotion/drake/blob/43e0086838d2c71b8db53371c5fc8728b47b9be8/drake/systems/plants/shapes/Geometry.cpp#L328)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This is pretty annoying. What should the best practice be here? to make `maximum_index` an unsigned type or the best solution is just to static cast here? 
</details>
The fewer unsigned types, the better.  Especially since the `index` being parsed is an `int`, the arithmetic related to it should also be in terms of `int`.

The cast is annoying, but honestly I think not a big deal to live with.

I have considered something like a free function `int size(const T& collection) { return static_cast<int>(collection.size());` so that this line would read: `if (maximum_index > size(vertices)) {`.  We probably would want a better name than `size`, and would want a `DRAKE_ASSERT` that the cast isn't overflowing, but it's an option.

Having done many of these PRs now though, the greatest source of sign warnings is integer-based `for` loops over `vector`s, where using ranged-for would b ea vastly superior solution, followed secondly by an `enumerate`-like range-for, followed thirdly by the `size` function above, followed last by the `static_cast`.  For now I'm just littering `static_cast` everywhere, but as we remove `size_t` from our own interfaces (`RBT`, `Polynomial`, etc.) we can start to attack the `vector` problem next.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2874)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/shapes/Geometry.cpp, line 328 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2874#-KNCgXS54Lm_sVyNqWYW:-KNCwpSeZ2dC2IIuzKIQ:-608139997) ([raw file](https://github.com/robotlocomotion/drake/blob/43e0086838d2c71b8db53371c5fc8728b47b9be8/drake/systems/plants/shapes/Geometry.cpp#L328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The fewer unsigned types, the better.  Especially since the `index` being parsed is an `int`, the arithmetic related to it should also be in terms of `int`.
> 
> The cast is annoying, but honestly I think not a big deal to live with.
> 
> I have considered something like a free function `int size(const T& collection) { return static_cast<int>(collection.size());` so that this line would read: `if (maximum_index > size(vertices)) {`.  We probably would want a better name than `size`, and would want a `DRAKE_ASSERT` that the cast isn't overflowing, but it's an option.
> 
> Having done many of these PRs now though, the greatest source of sign warnings is integer-based `for` loops over `vector`s, where using ranged-for would b ea vastly superior solution, followed secondly by an `enumerate`-like range-for, followed thirdly by the `size` function above, followed last by the `static_cast`.  For now I'm just littering `static_cast` everywhere, but as we remove `size_t` from our own interfaces (`RBT`, `Polynomial`, etc.) we can start to attack the `vector` problem next.
</details>
Sounds good. Thank you for the quick review on where this problem appears. I saw the range based for solution and I also agree is far superior. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2874)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri for platform review and merge, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2874#-:-KND9DzK1j9TcP08wTwE:1417088721)*

**Pull request merged**
