### PR TITLE
Upgrade SpatialForce documentation and keyword arguments for Python.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MyyjjE6C-75cJmmeNcY:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature pass done, ptal.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-Mz2SAyVCowbSbfL7GCt:b-7ctdg7)* status: 14 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/math/spatial_force.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Na9e9yFvWa2-trdW:-Mz2Na9e9yFvWa2-trdX:b-wvri5t) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L21)):*
> ```objc
> template <typename T> class SpatialVelocity;
> 
> /// This class represents a _spatial force_ (also called a _wrench_) and has 6
> ```

BTW did you want to say "a spatial force F" similar to the additions you made to the other spatial quantity docs?
___
*[multibody/math/spatial_force.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2O9IXAtV7R7nPQ8_W:-Mz2O9IXAtV7R7nPQ8_X:b-os5l06) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L68)):*
> ```objc
>   /// Constructs a spatial force F from an Eigen expression that represents a
>   /// 6-element vector, i.e., a 3-element torque 𝛕 and a 3-element force 𝐟.
>   /// This constructor will assert the size of `F` is six (6) either at
> ```

nit: inconsistent use of backquotes -- IMO best not to use them for single-letter quantities like these
___
*[multibody/math/spatial_force.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2OpEo4DGfZF6548-M:-Mz2OpEpA1wBSQ9yECkZ:blf5jmz) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L89)):*
> ```objc
>   /// Note: There are related functions to shift spatial momentum and spatial
>   /// velocity (see SpatialMomentum::Shift() and SpatialVelocity:Shift()).
>   /// @see This classes static ShiftInPlace() and Shift() functions shift
> ```

nit: classes -> class's

This seems to be worded as a `@note` not a `@see` (which is "see also")
___
*[multibody/math/spatial_force.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2P_vQ9SVyQpSVylhD:-Mz2P_vQ9SVyQpSVylhE:bq1khmm) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L100)):*
> ```objc
>     //        = Φ(-p_BpBq) F_Bp    where Φ(p_BpBq) is the linear operator:
>     //   Φ(p_BpBq) = | I₃  p_BpBqx |
>     //               | 0        I₃ |
> ```

minor: the sign is wrong here on the offset
___
*[multibody/math/spatial_force.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2PMLG9E_mLHJhRtzG:-Mz2PMLG9E_mLHJhRtzH:b-15fx71) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L103)):*
> ```objc
>     // where p_BpBqx denotes the cross product skew-symmetric matrix such that
>     // p_BpBqx vec = p_BpBq x vec (where vec is any vector).
>     // Note: There are related Φ operators to shift spatial momentum and spatial
> ```

minor: same comment as in the SpatialMomentum PR. These are more than just "related".
___
*[multibody/math/spatial_force.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QBb39venBctF0VOe:-Mz2QBb39venBctF0VOf:bsplkxz) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L112)):*
> ```objc
>   /// Shifts a matrix of spatial forces from one point of frame B to another
>   /// point of frame B.
>   /// @param[in,out] F_Bp_E_all 6 x n matrix where each of the n columns is
> ```

This parameter has an "old school" name involving frames that won't make sense at the call site. Should also be fixed along with `offset`.
___
*[multibody/math/spatial_force.h, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QS135sAz6Tk9fSGZ:-Mz2QS14ErQKrrKX56kF:b-miohp8) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L120)):*
> ```objc
>   /// p_BpBq_E must have the same expressed-in frame E as the spatial forces
>   /// stored in F_Bp_E_All (spatial forces on Bp, expressed in frame E).
>   /// @see This classes static ShiftInPlace() and Shift() functions shift
> ```

nit: shoudl be `@note` and classes -> class's
___
*[multibody/math/spatial_force.h, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Qg3q6mlh7-HxkyxH:-Mz2Qg3r9100NBC5Sgou:b-wvhrpd) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L140)):*
> ```objc
>   /// frame B.
>   /// @param[in] offset which is the position vector p_BpBq_E from point Bp
>   /// (fixed on frame B) to point Bq (fixed on frame B), expressed in frame E.
> ```

BTW I like this "point Bp fixed on frame B" phrase better than "point Bp of B" that you used above.
___
*[multibody/math/spatial_force.h, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QwVNC0y7bj9pqVB4:-Mz2QwVNC0y7bj9pqVB5:bxgj8hb) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L144)):*
> ```objc
>   /// where `this` is F_Bp_E (spatial force on Bp, expressed in frame E).
>   /// @retval F_Bq_E which is the spatial force on Bq, expressed in frame E.
>   /// @see This classes static ShiftInPlace() and Shift() functions shift
> ```

nit: `@note` and class's
___
*[multibody/math/spatial_force.h, line 153 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2R6eM-mCPhq1IMHpC:-Mz2R6eM-mCPhq1IMHpD:b2f2dpu) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L153)):*
> ```objc
>   /// Shifts a matrix of spatial forces from one point of frame B to another
>   /// point of frame B.
>   /// @param[in] F_Bp_E_all 6 x n matrix where each of the n columns is regarded
> ```

minor: old school name needs an upgrade (in this PR so deprecation doesn't have to be done twice)
___
*[multibody/math/spatial_force.h, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RQV8CVRgZEelBsQN:-Mz2RQV8CVRgZEelBsQO:bjmfc7y) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L159)):*
> ```objc
>   /// (fixed on frame B) to point Bq (fixed on frame B), expressed in frame E.
>   /// p_BpBq_E must have the same expressed-in frame E as that in F_Bp_E_All.
>   /// @param[out] F_Bq_E_all 6 x n matrix where each of the n column is regarded
> ```

nit: column -> columns
___
*[multibody/math/spatial_force.h, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RXDu3g3WFPStEhIX:-Mz2RXDu3g3WFPStEhIY:b56s1ro) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L163)):*
> ```objc
>   /// shifted from point Bp (fixed on frame B) to point Bq (fixed on frame B).
>   /// Each of spatial forces contained in F_Bq_E_all are expressed in frame E.
>   /// @pre F_Bq_E_all must be non-null and must point to a 6 x n matrix (i.e.,
> ```

minor: needs name fixup
___
*[multibody/math/spatial_force.h, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Rb199ILIbUTgJVFt:-Mz2Rb199ILIbUTgJVFu:bxgj8hb) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L165)):*
> ```objc
>   /// @pre F_Bq_E_all must be non-null and must point to a 6 x n matrix (i.e.,
>   /// it must be the same size as the input matrix F_Bp_E_all).
>   /// @see This classes static ShiftInPlace() and Shift() functions shift
> ```

nit: `@note` and class's
___
*[multibody/math/spatial_force.h, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RiyA8zSNC0TG8yJz:-Mz2RiyA8zSNC0TG8yK-:blczu75) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L170)):*
> ```objc
>   /// @note Although this Shift() function will work properly if the input and
>   /// output matrices are the same (i.e., F_Bp_E_all = F_Bq_E_all), it is faster
>   /// and more efficient if these are the same to avoid needless copying.
> ```

minor: "more efficient _to use ShiftInPlace()_"

**Review by mitiguy — COMMENTED** [review]
@sherm1   Although it is ready for another look, there are a few pending some local assignments (marked Todo).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzIacJW6re5ozskJgTr:bc6f3zu)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/math/spatial_force.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Na9e9yFvWa2-trdW:-MzHiLuC5GWzVwJ5HxL1:bs2ct8x) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW did you want to say "a spatial force F" similar to the additions you made to the other spatial quantity docs?
</blockquote></details>

Done.  Here and elsewhere for consistency.
___
*[multibody/math/spatial_force.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2O9IXAtV7R7nPQ8_W:-MzHfszS6i6BHfmFzs3P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: inconsistent use of backquotes -- IMO best not to use them for single-letter quantities like these
</blockquote></details>

Done.
___
*[multibody/math/spatial_force.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2OpEo4DGfZF6548-M:-MzHoXJB8AuQrqPCLiJ-:b-twga7g) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: classes -> class's

This seems to be worded as a `@note` not a `@see` (which is "see also")
</blockquote></details>

Done.  Reworded to be more compatible with @see here and elsewhere. 
We can use @note with slightly different language if preferred.
___
*[multibody/math/spatial_force.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2P_vQ9SVyQpSVylhD:-MzHocfi01TWpQgKUHTO:b-hdmvua) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L100)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the sign is wrong here on the offset
</blockquote></details>

Done.  Mimicked SpatialMomentum PR.
___
*[multibody/math/spatial_force.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2PMLG9E_mLHJhRtzG:-MzHoj-E2FoaeAy4GIAJ:b-hdmvua) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: same comment as in the SpatialMomentum PR. These are more than just "related".
</blockquote></details>

Done.  Mimicked SpatialMomentum PR.
___
*[multibody/math/spatial_force.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QBb39venBctF0VOe:-MzI7Ok07lbZuMGAuvqw:bz6r2ru) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L112)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This parameter has an "old school" name involving frames that won't make sense at the call site. Should also be fixed along with `offset`.
</blockquote></details>

Done here and elsewhere.
___
*[multibody/math/spatial_force.h, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QS135sAz6Tk9fSGZ:-MzHsiGR6Uh4wK7uOSO6:b-ud8jcg) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L120)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: shoudl be `@note` and classes -> class's
</blockquote></details>

Done.  Reworded to be more compatible with @see here and elsewhere. 
___
*[multibody/math/spatial_force.h, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Qg3q6mlh7-HxkyxH:-MzI71-wALXFS8KmpwSD:bp1kwlg) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L140)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I like this "point Bp fixed on frame B" phrase better than "point Bp of B" that you used above.
</blockquote></details>

Changed here and several other places.
___
*[multibody/math/spatial_force.h, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2QwVNC0y7bj9pqVB4:-MzI7CVp1pANCyz34SIR:b-ud8jcg) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `@note` and class's
</blockquote></details>

Done.  Reworded to be more compatible with @see here and elsewhere. 
___
*[multibody/math/spatial_force.h, line 153 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2R6eM-mCPhq1IMHpC:-MzI7Zia7_ZOXATRxbgJ:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L153)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: old school name needs an upgrade (in this PR so deprecation doesn't have to be done twice)
</blockquote></details>

Done here and elsewhere.
___
*[multibody/math/spatial_force.h, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RQV8CVRgZEelBsQN:-MzI7o3Y6KyIvq9zaBjz:b-qj92pf) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L159)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: column -> columns
</blockquote></details>

Reworded.
___
*[multibody/math/spatial_force.h, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RXDu3g3WFPStEhIX:-MzI7sGx4RUyrn-geCWy:b-qj92pf) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L163)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: needs name fixup
</blockquote></details>

Reworded.
___
*[multibody/math/spatial_force.h, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2Rb199ILIbUTgJVFt:-MzI7tq99K1fh8EZsjbo:b-ud8jcg) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L165)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `@note` and class's
</blockquote></details>

Done.  Reworded to be more compatible with @see here and elsewhere. 
___
*[multibody/math/spatial_force.h, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16851#-Mz2RiyA8zSNC0TG8yJz:-MzI7vU1EMwz5Zr__dyJ:b-n0ky7d) ([raw file](https://github.com/robotlocomotion/drake/blob/0ce90bbea11eef4f4b0fcee6140606a008b793df/multibody/math/spatial_force.h#L170)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: "more efficient _to use ShiftInPlace()_"
</blockquote></details>

Done.  Wow -- looks like a squirrel ran by while I made these previous changes.

**Review by mitiguy — COMMENTED** [review]
@sherm1   This is now ready for a full review.  You and I addressed the TODOs yesterday.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzRTsCnDtCNouyp9eO6:b-lsei6n)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few nits
+@rpoyner-tri for platform review per rotation (Monday) please

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzWmoSL8XpLtX4dxGSW:b-lahdr0)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy and @rpoyner-tri)

___
*[multibody/math/spatial_force.h, line 91 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlCU57wIi4Rvi2NLx:-MzWlCU6CMtTuL3OP2U2:b-1e6e2m) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L91)):*
> ```objc
>   /// @see Member function Shift() to shift one spatial force without modifying
>   /// `this` and static functions ShiftInPlace() and Shift() to shift multiple
>   /// spatial forces (with or without modifying the input parameter F_Bp_E_all).
> ```

nit: I think this input parameter got renamed
___
*[multibody/math/spatial_force.h, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlZXI4qlG_jKlIX3a:-MzWlZXI4qlG_jKlIX3b:bqxi9qj) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L117)):*
> ```objc
>   /// each spatial force is applied to a point Bp of frame B. On output, each
>   /// spatial force has been shifted to a point Bq of frame B. In other words,
>   /// on output, spatial_forces = F_Bq_E_All.
> ```

nit: All -> all
___
*[multibody/math/spatial_force.h, line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlfhKDs_hYQ9jKBDl:-MzWlfhKDs_hYQ9jKBDm:b-ngjwbv) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L122)):*
> ```objc
>   /// p_BpBq_E must have the same expressed-in frame E as in spatial_forces.
>   /// @see Static function Shift() to shift multiple spatial forces without
>   /// modifying the input parameter F_Bp_E_all and member functions
> ```

nit: parameter renamed
___
*[multibody/math/spatial_force.h, line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlp_tAluqCbS-FnEd:-MzWlp_tAluqCbS-FnEe:b-ngjwbv) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L149)):*
> ```objc
>   /// @see Member function ShiftInPlace() to shift one spatial force (modifying
>   /// `this`) and static functions ShiftInPlace() and Shift() to shift multiple
>   /// spatial forces (with or without modifying the input parameter F_Bp_E_all).
> ```

nit: parameter renamed
___
*[multibody/math/spatial_force.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWm5oz5RLTEafhMLtL:-MzWm5oz5RLTEafhMLtM:b-ngjwbv) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L169)):*
> ```objc
>   /// (i.e., it must be the same size as the input matrix spatial_forces).
>   /// @see Static function ShiftInPlace() to shift multiple spatial forces with
>   /// modification to the input parameter F_Bp_E_all and member functions
> ```

nit: parameter renamed

**Review by mitiguy — COMMENTED** [review]
@sherm1   In case you want to take one more look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzXHd1Q3vFRKe5dVbyv:b-pkdfkj)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[multibody/math/spatial_force.h, line 91 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlCU57wIi4Rvi2NLx:-MzXBOlI8do1I3L2bSA0:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L91)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: I think this input parameter got renamed
</blockquote></details>

Done here and elsewhere.
___
*[multibody/math/spatial_force.h, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlZXI4qlG_jKlIX3a:-MzXBVyt1cVqqqv52cD3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L117)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: All -> all
</blockquote></details>

Done.
___
*[multibody/math/spatial_force.h, line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlfhKDs_hYQ9jKBDl:-MzXBZEdAsth12PKqBWM:bz6r2ru) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L122)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: parameter renamed
</blockquote></details>

Done here and elsewhere.
___
*[multibody/math/spatial_force.h, line 149 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWlp_tAluqCbS-FnEd:-MzXBa0T6z5CBDJT_qzy:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L149)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: parameter renamed
</blockquote></details>

Done here and elsewhere.
___
*[multibody/math/spatial_force.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzWm5oz5RLTEafhMLtL:-MzXBbIU1ngjfMZT3acE:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/d67245fcefe617bb0902c02516029714d1d8d1d6/multibody/math/spatial_force.h#L169)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: parameter renamed
</blockquote></details>

Done here and elsewhere.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: deprecation date issue
+(release notes: newly deprecated) 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzoxiWs3YiAA37PNSg7:b1mcg2u)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[bindings/pydrake/multibody/math_py.cc, line 285 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzoxLb80VrYUdXHejPp:-MzoxLb80VrYUdXHejPq:b49s49d) ([raw file](https://github.com/robotlocomotion/drake/blob/f3b56d630b784c2b6f40671df142c26cae2075d0/bindings/pydrake/multibody/math_py.cc#L285)):*
> ```cpp
>         " Shift(p_BqBq_E) to"
>         " Shift(offset)."
>         " Deprecated kwarg will be unavailable after 2022-07-01.";
> ```

Since this PR will have the unfortunate fate of merging in April, the deprecation date needs to be pushed to 2022-08-01.



_Code quote:_
```cpp
2022-07-01
```
___
*[bindings/pydrake/multibody/test/math_test.py, line 192 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzoxVbn5RpQjSpARhLt:-MzoxVbn5RpQjSpARhLu:b-dgvyej) ([raw file](https://github.com/robotlocomotion/drake/blob/f3b56d630b784c2b6f40671df142c26cae2075d0/bindings/pydrake/multibody/test/math_test.py#L192)):*
> ```Python
>         p = to_T(np.zeros(3))
>         self.assertIsInstance(F.Shift(offset=p), SpatialForce_[T])
>         # TODO(2022-07-01) Remove with completion of deprecation.
> ```

ditto above on deprecate date issue.

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-MzpJyVg8YHcPNXZeMo3:bm9o57a)* status: 2 unresolved discussions (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16851#-:-Mzpg1vW0NwNlFQhWruf:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

___
*[bindings/pydrake/multibody/math_py.cc, line 285 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzoxLb80VrYUdXHejPp:-MzpPIcoDRYBYFSPMPEA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3b56d630b784c2b6f40671df142c26cae2075d0/bindings/pydrake/multibody/math_py.cc#L285)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Since this PR will have the unfortunate fate of merging in April, the deprecation date needs to be pushed to 2022-08-01.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/test/math_test.py, line 192 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16851#-MzoxVbn5RpQjSpARhLt:-MzpPCvy3WiM_T8zwbJh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3b56d630b784c2b6f40671df142c26cae2075d0/bindings/pydrake/multibody/test/math_test.py#L192)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

ditto above on deprecate date issue.
</blockquote></details>

Done.

**Pull request merged**
