### PR TITLE
Remove unused MATLAB dependencies code

### PR DESCRIPTION
**Pull request by jamiesnape**
_Edited to add (jwnimmer-tri): Relates #6369_.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6507)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review. FYI @RussTedrake.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 47 of 47 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6507#-:-KoN9Q-aX0WAY0wMIeyS:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by RussTedrake** [comment]
aok.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6507#-:-KoRu6Rqh_iRV1Rms4ua:bb7d5jq)*

**Comment by soonho-tri** [comment]
:lgtm:

-@RussTedrake , I believe his aok is his 'LGTM'.

+(status: do not merge)  I'll test it on a mac this morning and merge it.

---

Reviewed 47 of 47 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6507#-:-KoRuVbF2uk0-Ksdx6FL:ba2x0rt)*

**Pull request merged**
