### PR TITLE
Add SchunkWsgDriver for hardware_sim 

### PR DESCRIPTION
**Pull request by zachfang**
Toward #17112

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
Reopen to separate commits for review.

+@jwnimmer-tri for feature review.
Confirmed that the wsg_status messages are published when running the demo.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719#-:-N9DQNPt5ovb5j72luun:be1vtpo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DQc_qE8FFdWw_1Wt1:-N9DQc_qE8FFdWw_1Wt2:bsod48w) (no related file):*
FYI. I changed the file names or the function names from Wsg to SchunkWsg to be consistent with other files in `//manipulation/schunk_wsg`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719#-:-N9DXKu8EGcIE3UyotWc:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DWqK_1LTiBGKdIsJ7:-N9DWqK_1LTiBGKdIsJ8:bme0v6h) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/build_schunk_wsg_control.h#L13)):*
> ```objc
> namespace drake {
> namespace manipulation {
> namespace schunk_wsg {
> ```

Hmm.  Did we talk about marking this function `namespace internal` for now?

Let me ponder.
___
*[`manipulation/schunk_wsg/schunk_wsg_driver.h` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DXFBN8M2ZGo22PXyS:-N9DXFBN8M2ZGo22PXyT:b-mxwlb5) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver.h#L26)):*
> ```objc
>   /// Gains to apply to the the WSG fingers.  The p term corresponds
>   /// approximately to the elastic modulus of the belt, the d term to the
>   /// viscous friction of the geartrain.  The i term is nonphysical.
> ```

nit Use `/** ... */` Doxygen formatting, for consistency with the above struct overview.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DWqK_1LTiBGKdIsJ7:-N9DXYOR87lHsAGM1izA:bnhzq0b) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/build_schunk_wsg_control.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  Did we talk about marking this function `namespace internal` for now?

Let me ponder.
</blockquote></details>

We did talk about putting `MakeArmControllerModel()` to internal namespace but not specifically about `build*control()` if I recall correctly (I looked into the related PRs).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DWqK_1LTiBGKdIsJ7:-N9DY26w6LwH95hzdvhW:b-nkjri4) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/build_schunk_wsg_control.h#L13)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

We did talk about putting `MakeArmControllerModel()` to internal namespace but not specifically about `build*control()` if I recall correctly (I looked into the related PRs).
</blockquote></details>

OK Yeah.  I was worried about this function being subject to changes or brittleness in the future, but I think it should be fine.  Withdrawn.
___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DXmcYB-R-risusrXe:-N9DXmcYB-R-risusrXf:b-neaqht) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/build_schunk_wsg_control.h#L21)):*
> ```objc
> void BuildSchunkWsgControl(
>     const multibody::MultibodyPlant<double>& plant,
>     const multibody::ModelInstanceIndex wsg_instance,
> ```

nit Can't use a meaningless `const` here on `wsg_instance`.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const

Note that the cc file is fine as-is if you like; only the h file need to drop the `const`.



_Suggestion:_
```objc
multibody::ModelInstanceIndex wsg_instance
```
___
*[`manipulation/schunk_wsg/schunk_wsg_driver_functions.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DYJPXBGxOT2Ldx4ae:-N9DYJPY5iRPyFnL6jBw:b-8fb4wq) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver_functions.cc#L24)):*
> ```cpp
>   DRAKE_THROW_UNLESS(builder != nullptr);
>   const std::string& hand_name = model_instance_name;
>   if (models_from_directives.count(hand_name) == 0) {
> ```

nit This isn't unit tested.  Rather than unit testing it, it would be easier to just remo all use of models_from_directives entirely, by simplifying the call to `Build...` below (see suggestion).
___
*[`manipulation/schunk_wsg/schunk_wsg_driver_functions.cc` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DYZQi3m4YCwNcSmKp:-N9DYZQi3m4YCwNcSmKq:b1x1z2f) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver_functions.cc#L32)):*
> ```cpp
>       lcms.Find("Driver for " + hand_name, driver_config.lcm_bus);
>   const ModelInstanceInfo& hand_model = models_from_directives.at(hand_name);
>   BuildSchunkWsgControl(
> ```

nit This can be simplified, I think?



_Suggestion:_
```cpp
  BuildSchunkWsgControl(
      sim_plant, plant.GetModelInstanceByName(wsg_model_instance),
      lcm, builder, driver_config.pid_gains);
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DXmcYB-R-risusrXe:-N9EsODi2pqHlRgeovio:bw6xayj) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/build_schunk_wsg_control.h#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Can't use a meaningless `const` here on `wsg_instance`.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const

Note that the cc file is fine as-is if you like; only the h file need to drop the `const`.
</blockquote></details>

Done. Kept the cc file as-is to emphasize it's not modified.
___
*[`manipulation/schunk_wsg/schunk_wsg_driver.h` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DXFBN8M2ZGo22PXyS:-N9EsdPMD1qsRU_yOi2A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Use `/** ... */` Doxygen formatting, for consistency with the above struct overview.
</blockquote></details>

Done.
___
*[`manipulation/schunk_wsg/schunk_wsg_driver_functions.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DYJPXBGxOT2Ldx4ae:-N9ExbO0BI1PGXiJ6sVC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver_functions.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This isn't unit tested.  Rather than unit testing it, it would be easier to just remo all use of models_from_directives entirely, by simplifying the call to `Build...` below (see suggestion).
</blockquote></details>

Done.
___
*[`manipulation/schunk_wsg/schunk_wsg_driver_functions.cc` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9DYZQi3m4YCwNcSmKp:-N9Exchn7x1sATZKV7nE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cb063c039ca85de4d96c3d5317af6707130bf27a/manipulation/schunk_wsg/schunk_wsg_driver_functions.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This can be simplified, I think?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
+@ggould-tri for platform review.

This PR copies Wsg-related files from Anzu, and replaces the SchunkWsg driver with it in the hardware_sim demo program. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719#-:-N9WwiyDAFbxW6-NP9d2:bo4ovkn)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 11 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719#-:-N9X8GoBALRMEPqtAQKC:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[`examples/hardware_sim/hardware_sim.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9XE7j39Jj_3aPz3Mwp:-N9XE7j47GVq9fvOios-:b-qlbj4u) ([raw file](https://github.com/robotlocomotion/drake/blob/e36a5fc4242dd3cc28b76460ff48faced5d5ef21/examples/hardware_sim/hardware_sim.cc#L15)):*
> ```cpp
> 
> #include "drake/examples/hardware_sim/scenario.h"
> #include "drake/manipulation/schunk_wsg/schunk_wsg_driver_functions.h"
> ```

It took me quite a while to figure out why this include was required, when it really looked as though it was not.

It might be worth documenting in `ApplyDriverConfigs` that the caller is responsible for including the variant members' apply functions.

(Or actually this whole thing might be a usability snakepit?  I'm hard-pressed to see how https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1manipulation.html#adb8ec6471d1a13e6fcea69aebb9ee7ab signposts the variant madness going on here enough for anyone to figure out how to call it soundly, but I'm also not sure how to fix it.  Possibly we need to document the driver "concept" somewhere?)

Feel free to dismiss this discussion as too meta if you don't see anything actionable here, or resolve it with a TODO in `apply_driver_configs.h`.
___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9X9nIoACap7izX3_ux:-N9X9nIoACap7izX3_uy:bb7lc5i) ([raw file](https://github.com/robotlocomotion/drake/blob/e36a5fc4242dd3cc28b76460ff48faced5d5ef21/manipulation/schunk_wsg/build_schunk_wsg_control.h#L18)):*
> ```objc
> /// model in @p plant indicated by @p wsg_instance; hooks those systems up to
> /// @p lcm and the relevant MbP ports in the diagram.
> /// The argument pid_gains can be used to override the default sim PID gains.
> ```

nit:



_Suggestion:_
```objc
@p pid_gains
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

___
*[`examples/hardware_sim/hardware_sim.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9XE7j39Jj_3aPz3Mwp:-N9XW5659iQeCRtiQjb1:b-wr65p4) ([raw file](https://github.com/robotlocomotion/drake/blob/e36a5fc4242dd3cc28b76460ff48faced5d5ef21/examples/hardware_sim/hardware_sim.cc#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It took me quite a while to figure out why this include was required, when it really looked as though it was not.

It might be worth documenting in `ApplyDriverConfigs` that the caller is responsible for including the variant members' apply functions.

(Or actually this whole thing might be a usability snakepit?  I'm hard-pressed to see how https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1manipulation.html#adb8ec6471d1a13e6fcea69aebb9ee7ab signposts the variant madness going on here enough for anyone to figure out how to call it soundly, but I'm also not sure how to fix it.  Possibly we need to document the driver "concept" somewhere?)

Feel free to dismiss this discussion as too meta if you don't see anything actionable here, or resolve it with a TODO in `apply_driver_configs.h`.
</blockquote></details>

Done. I added a comment in `apply_driver_configs.h`.
___
*[`manipulation/schunk_wsg/build_schunk_wsg_control.h` line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17719#-N9X9nIoACap7izX3_ux:-N9XWEv6-LSSg-6WIkPQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e36a5fc4242dd3cc28b76460ff48faced5d5ef21/manipulation/schunk_wsg/build_schunk_wsg_control.h#L18)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
This needs a rebase onto the tip of master and force-push (after which we can merge it).

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17719)* status: missing label for release notes (waiting on @zachfang)

**Pull request merged**
