### PR TITLE
Fixed a bug in the Discrete Algebraic Riccati Equation Solver

### PR DESCRIPTION
**Pull request by weiqiao**
Solved the issue #8034 "DARE cannot solve trivial problem (stuck in infinite loop)"

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8469)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8469#-:-L8eay_587sf26HSs44E:bltox9h)*

**Comment by hongkai-dai** [comment]
:lgtm: I didn't go through the math. 

I would suggest to do more tests on the dare function, with many different combinations of `A, B, Q, R`, and compare the result with MATLAB `dare`. Maybe do this in a future PR.

+@soonho-tri for platform review please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/discrete_algebraic_riccati_equation.cc, line 324 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8469#-L8mbSF39l9igQykVwPA:-L8mbSF39l9igQykVwPB:b-k6d3ge) ([raw file](https://github.com/robotlocomotion/drake/blob/152a98a828ddb0ac7dbd696753e00e9dcd198829/math/discrete_algebraic_riccati_equation.cc#L324)):*
> ```cpp
>       }
>     } else {  // p block size = 2
>       double det_S = S(p, p) * S(p + 1, p + 1) - S(p + 1, p) * S(p, p + 1);
> ```

`double` -> `const double`. Same thing below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8469#-:-L8mb_LN58kmSxDfUV9h:b-vzso8l)*

**Comment by soonho-tri** [comment]
@weiqiao , I do not follow the math part either. Could you find another feature-reviewer (at MIT?) who can confirm the fix? I'll hold my lgtm emoji until then.

I've checked that the added test does not terminate (in a minute) without the fix in `.cc` file. This is a good sign. But as @hongkai-dai mentioned, I'd like to see at least a couple of more tests.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/discrete_algebraic_riccati_equation.cc, line 323 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8469#-L8miW6B84FP3hcpdHf-:-L8miW6B84FP3hcpdHf0:b-y2w9km) ([raw file](https://github.com/robotlocomotion/drake/blob/152a98a828ddb0ac7dbd696753e00e9dcd198829/math/discrete_algebraic_riccati_equation.cc#L323)):*
> ```cpp
>         continue;
>       }
>     } else {  // p block size = 2
> ```

FYI, consider restructuring this else branch to compute `det_S` only when needed. For example,

```c++
      const double det_T =
          T(p, p) * T(p + 1, p + 1) - T(p + 1, p) * T(p, p + 1);
      if (fabs(det_T) > eps) {
        const double det_S =
            S(p, p) * S(p + 1, p + 1) - S(p + 1, p) * S(p, p + 1);
        if (fabs(det_S) <= fabs(det_T)) {  // stable
          p += 2;
          continue;
        }
      }
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8469#-:-L8migkUD0Yp3-HLacB-:b-brf2p0)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by jwnimmer-tri** [comment]
@hongkai-dai This seems stalled.  Would you like to take over the fixups yourself?  Otherwise, we could close it.

**Comment by hongkai-dai** [comment]
@weiqiao , would you like to address the reviewers' comments?

**Comment by weiqiao** [comment]
@hongkai-dai Sure, I'll do it soon.

**Comment by hongkai-dai** [comment]
@weiqiao , could you update the status of this PR? Will you rebase it on top of master and push it again?

**Comment by sadraddini** [comment]
OK I will look very soon.

**Comment by soonho-tri** [comment]
@hongkai-dai , I think it's safe to close this one as we have #11118 ?

**Comment by hongkai-dai** [comment]
Close this PR in as we have #11118.

**Pull request closed without merging**
