### PR TITLE
[geometry/dev] Extend the example to cover more API

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This extends the example in a couple of important ways.

1. The mustard bottle is no longer welded to the world; as part of the plant, it'll be a moving object.
   - the movement is simple: zero gravity with a constant spatial velocity.
2. Introduce the framework to introduce a number of primitives (textured and untextured).

Not all shapes have been introduced (there is a TODO) and there are still a number of features that need to be exercised as indicated in the list.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16172)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
This is what you should see:



+@zachfang for single review and FYI @joemasterjohn.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16172#-:-Mpwq3iW2obDMpz5LtHY:b-20cbgu)* status: LGTM missing from assignee zachfang (waiting on @zachfang)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@joemasterjohn You'll probably have to take over this PR to get it over the finish line. I think it's 85% self-explanatory. Let me know if you have any questions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16172#-:-MqLtKUNBU4MBW_CCqpC:b9suubm)* status: LGTM missing from assignee zachfang (waiting on @zachfang)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot retest this please

**Review by zachfang — COMMENTED** [review]
:lgtm_strong:
Thanks, Sean! We will add the remaining features later on.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16172#-:-MqPelJb1P9ZqJJlSZP2:b7adj1g)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @SeanCurtis-TRI)

**Comment by kunimatsu-tri** [comment]
I came late to the party. It doesn't look like the right `capsule` is textured properly. If that would be the case, we should investigate it.

@SeanCurtis-TRI Do you have any insight for us to start with?

**Comment by SeanCurtis-TRI** [comment]
There's a note in the code that we aren't generating texture coordinates for capsules. That's a known defect -- this image merely captures that. (And if/when we add those UVs, this will automatically reflect the change.)

**Comment by kunimatsu-tri** [comment]
Ah, I have missed that note. If we were to implement texture coordinates for capsules, where should be the right place?

**Comment by SeanCurtis-TRI** [comment]
Our VTK capsule source is forked (`see /drake/third_party/com_github_finetjul_bender/vtkCapsuleSource.h`). It's part of VTK9. The expectation is that when we upgrade VTK we'll jettison the fork and pick up VTK's flavor. The fork we have doesn't appear to generated texture coordinates, and I don't know what VTK is doing with that. IN contrast, `RenderEngineVtk` uses `vtkTexturedSphereSource` instead of `vtkSphereSource` to get uvs. I would imagine VTK has a comparable duo for the capsule.

It's probably not a high priority. There hasn't been a lot of requests for textured capsules.  :)  I added textures to the other shapes (where convenient) more for the sense of philosophical completeness than a hard, demonstrable need.  Although, it has come in handy.

**Comment by kunimatsu-tri** [comment]
Yeah, I agree that it's not a high priority, but it's also good to know where the thing is going wrong. Thanks, Sean.

**Pull request merged**
