### PR TITLE
Re-generate valkyrie obj meshes from dae

### LINKED ISSUE #8130: Valkyrie model's left-side OBJ meshes have reversed normals
On the left is the .obj file for Val's left arm link 5, and on the right is the .dae file for the same link:

screenshot from 2018-02-21 12-26-42

The meshes for the right side of the robot don't have this problem:

screenshot from 2018-02-21 12-27-33

Simply opening the .dae in Meshlab and and then exporting it as .obj fixes the problem. I'll see if I can do that from the command line.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #8130

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8626)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Seems like CI is failing possibly because the `meshlab` script is losing the name to the original `*.mtl` file?

Do you know what the cause of that might be?

**Comment by rdeits** [comment]
Yeah, the `.mtl` files are all new (they're autogenerated as part of the meshlab export). I assume they need to be listed as bazel resources somewhere?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI This is perhaps waiting for you to resume review?  We'll want to re-test before merging, at least.

**Comment by EricCousineau-TRI** [comment]
Ah, jeepers :( I had missed the follow-up comment on email - sorry about that!

@drake-jenkins-bot retest this please.

**Comment by EricCousineau-TRI** [comment]
Confirmed that things look nice after the fact:
Before:
> image
After:
> image

**Pull request merged**
