### PR TITLE
Fixes race condition in IrisInConfigurationSpaceFromCliqueCover

### PR DESCRIPTION
**Pull request by wernerpe**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21136)

### CODE REVIEW

**Review by wernerpe — COMMENTED** [review]
+@AlexandreAmice for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21136#-:-NspfjMO0gr-eWMyKKx1:b-l84zec)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wernerpe)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21136#-:-Nspft2y1EjsZaLhMItB:b-uwkowd)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wernerpe)

**Review by AlexandreAmice — COMMENTED** [review]
+(release notes: fix) +(priority: high) 
+@sherm1 for platform per schedule. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21136#-:-Nspfv5mAoI0n6xsqlM8:b3vvxbl)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +@jwnimmer-tri -@sherm1 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21136#-:-Nspgvpi26p4-6l_Mp_R:btpuwke)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

**Pull request merged**
