### PR TITLE
Add quadrature class for FEM.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Create the API for a general quadrature rule class for FEM applications.
Add a concrete class, SimplexGaussianQuadrature that implements the APIs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 4 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/quadrature.h, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUFwm00Xig3QL66A04:-MJUFwm00Xig3QL66A05:b-bg5y0i) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L10)):*
> ```objc
> #include "drake/common/nice_type_name.h"
> 
> namespace drake {
> ```

This is not in the `drake::multibody` namespace?
___
*[multibody/fem/dev/quadrature.h, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJTwYNa61qRkSjaTYMy:-MJTwYNa61qRkSjaTYMz:b-er1arl) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L13)):*
> ```objc
> namespace fem {
> template <typename T, int NaturalDimension>
> class Quadrature {
> ```

Missing class documentation? Could you explain briefly what is the purpose of this class? 
___
*[multibody/fem/dev/quadrature.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUDrpl6bpInmxS8-_R:-MJUDrpl6bpInmxS8-_S:ba09ubm) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L52)):*
> ```objc
> The 2D unit triangle has vertices located at (0,0), (1,0) and (0,1). The 3D unit
> tetrahedron has vertices located at (0,0,0), (1,0,0), (0,1,0) and (0,0,1).
>  @tparam QuadratureOrder order of the quadrature rule. Must be 1, 2, or 3.
> ```

It isn't clear to me what `QuadratureOrder` means by reading this documentation. Is it the order of the polynomial to be integrated? How does it relates to the number of quadrature points? 
___
*[multibody/fem/dev/quadrature.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUG5fVC2Nke17qT0KX:-MJUG5fVC2Nke17qT0KY:b42ukby) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L72)):*
> ```objc
>       // For a unit triangle, area = 0.5.
>       if constexpr (QuadratureOrder == 1) {
>         // quadrature point location,  weight/area
> ```

Sorry, could you explain more on how these quadrature points are computed? I only know the quadrature points on 1-D function using Legendre function, and the roots of Legendre function don't look like rational numbers.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 4 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[multibody/fem/dev/quadrature.h, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUFwm00Xig3QL66A04:-MJV-J5X6ehSKmXXiMEy:b-jb6kj3) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L10)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This is not in the `drake::multibody` namespace?
</blockquote></details>

It should be, sorry. Done.
___
*[multibody/fem/dev/quadrature.h, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJTwYNa61qRkSjaTYMy:-MJV0mFJC3kB38pi2TT3:bvo03j9) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L13)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Missing class documentation? Could you explain briefly what is the purpose of this class? 
</blockquote></details>

Added some class documentation. PTAL, thank you.
___
*[multibody/fem/dev/quadrature.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUDrpl6bpInmxS8-_R:-MJV0tWJDFL1QAQdrCcO:b-s1m7l0) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L52)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It isn't clear to me what `QuadratureOrder` means by reading this documentation. Is it the order of the polynomial to be integrated? How does it relates to the number of quadrature points? 
</blockquote></details>

Added some documentation. It's unclear to me how it relates to the number of quadrature points in the case of simplex. I'm under the impression that in higher dimensions, the most efficient quadrature rule remains an open question. For our purposes, however, I believe cubic order is enough for the foreseeable future and the number of points used seems reasonable from this reference. I do not know whether they are optimal.
___
*[multibody/fem/dev/quadrature.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUG5fVC2Nke17qT0KX:-MJV3o6LA-lRiB2bzN1f:b-s9luxz) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L72)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, could you explain more on how these quadrature points are computed? I only know the quadrature points on 1-D function using Legendre function, and the roots of Legendre function don't look like rational numbers.
</blockquote></details>

The Legendre function idea can be generalized to higher dimension and the resulting quadrature rule would take m^d quadrature points to get order 2m-1, where d is the number of dimensions. Although in higher dimensions the Gaussian quadratures from Legendre polynomials are no longer optimal.

The quadrature rule I used here is from the paper I cited in the reference which uses equal or fewer number of points and have the added advantage that they are symmetric. It is referenced in an FEM book I'm following so I used this. Unfortunately, the paper does not provide general theory of how to produce these quadrature points.

**Review by xuchenhan-tri — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202#-:-MJV7PoS1vb6WoBZ78EK:byeu43f)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[multibody/fem/dev/quadrature.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUG5fVC2Nke17qT0KX:-MJX2I9i5zWn0r9nhAk1:b-p1cv2k) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L72)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The Legendre function idea can be generalized to higher dimension and the resulting quadrature rule would take m^d quadrature points to get order 2m-1, where d is the number of dimensions. Although in higher dimensions the Gaussian quadratures from Legendre polynomials are no longer optimal.

The quadrature rule I used here is from the paper I cited in the reference which uses equal or fewer number of points and have the added advantage that they are symmetric. It is referenced in an FEM book I'm following so I used this. Unfortunately, the paper does not provide general theory of how to produce these quadrature points.
</blockquote></details>

I recommend that here you add a reference to where you got these numbers from @xuchenhan-tri. It'd help the reviewer and it'd help us in the future if we wanted for instance a good reference for other quadrature rules.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri, @hongkai-dai, and @xuchenhan-tri)

___
*[multibody/fem/dev/quadrature.h, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUDrpl6bpInmxS8-_R:-MJXeBcSAnVyG5OT9p8W:b-wsvas3) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Added some documentation. It's unclear to me how it relates to the number of quadrature points in the case of simplex. I'm under the impression that in higher dimensions, the most efficient quadrature rule remains an open question. For our purposes, however, I believe cubic order is enough for the foreseeable future and the number of points used seems reasonable from this reference. I do not know whether they are optimal.
</blockquote></details>

Thanks for the explanation.
___
*[multibody/fem/dev/quadrature.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUG5fVC2Nke17qT0KX:-MJXlvat3MgjOafdCIOr:b-e2nczc) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L72)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I recommend that here you add a reference to where you got these numbers from @xuchenhan-tri. It'd help the reviewer and it'd help us in the future if we wanted for instance a good reference for other quadrature rules.
</blockquote></details>

I see, it would be more clear if you mention it is section 3 "symmetrical formulas" of [Hammer, 1956]. I read the first two sections and didn't find the formula used here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri, @hongkai-dai, and @xuchenhan-tri)

___
*[multibody/fem/dev/quadrature.h, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJXmTpX5ytkmJ0r-o_6:-MJXmTpX5ytkmJ0r-o_7:bq0y38k) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L89)):*
> ```objc
>         // proposed at https://github.com/cpplint/cpplint/pull/136.
>         // NOLINTNEXTLINE(readability/braces)
>       } else if constexpr (QuadratureOrder == 2) {
> ```

You could mention that you choose `r=1/2` in section 3 of [Hammer, 1956]. They also mentioned the other choice with `r=-1/2`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri, @hongkai-dai, and @xuchenhan-tri)

___
*[multibody/fem/dev/quadrature.h, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJYX61l50FJyhrN1ju4:-MJYX61l50FJyhrN1ju5:b-s6383p) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L75)):*
> ```objc
>       : Quadrature<T, NaturalDimension>(GetPoints(), GetWeights()) {}
> 
>   std::vector<VectorD> GetPoints() {
> ```

Since the points and weights are highly coupled, I would think they should be computed together, and returned together. Is there a strong reason why they are returned separately? What is the use case for only getting points, but not the weights, or vice versa?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[multibody/fem/dev/quadrature.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJUG5fVC2Nke17qT0KX:-MJ_SEHsDLKHcPc_qnL1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bef84aad24662ee7f65365665330e783fdf3cdc6/multibody/fem/dev/quadrature.h#L72)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, it would be more clear if you mention it is section 3 "symmetrical formulas" of [Hammer, 1956]. I read the first two sections and didn't find the formula used here. 
</blockquote></details>

Done.
___
*[multibody/fem/dev/quadrature.h, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJYX61l50FJyhrN1ju4:-MJ_M8KzEM7-GPFcnTNa:b8oo6hb) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L75)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Since the points and weights are highly coupled, I would think they should be computed together, and returned together. Is there a strong reason why they are returned separately? What is the use case for only getting points, but not the weights, or vice versa?
</blockquote></details>

There are use cases where we would only get weights. For example, if we are integrating f*g over a domain. It could be imagined that we want to evaluate f(q) and g(q) at different places and integrate at yet another place where we actually need the weights.

However, in that imagined scenario we would be calling `get_weight` in the base class instead of the `GetWeights()/GetPoints()` here. The `GetWeights()/GetPoints()` here are only used in the constructor of `SimplexGaussianQuadrature`. They probably should not be public to start with. I moved them to private.
___
*[multibody/fem/dev/quadrature.h, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJXmTpX5ytkmJ0r-o_6:-MJ_OumQBig1yTddE1z7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L89)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You could mention that you choose `r=1/2` in section 3 of [Hammer, 1956]. They also mentioned the other choice with `r=-1/2`.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @xuchenhan-tri)

___
*[multibody/fem/dev/quadrature.h, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJYX61l50FJyhrN1ju4:-MJbnFWU7yXvWLo21Q1e:b-777086) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There are use cases where we would only get weights. For example, if we are integrating f*g over a domain. It could be imagined that we want to evaluate f(q) and g(q) at different places and integrate at yet another place where we actually need the weights.

However, in that imagined scenario we would be calling `get_weight` in the base class instead of the `GetWeights()/GetPoints()` here. The `GetWeights()/GetPoints()` here are only used in the constructor of `SimplexGaussianQuadrature`. They probably should not be public to start with. I moved them to private.
</blockquote></details>

I like that you compute the points and the weights in the constructor.

One more thing, I think the points and the weights should be computed at the same time? So I would recommend a function `ComputePointsAndWeights()`, which combines `GetPoints` and `GetWeights` function, something like this
```cc
    if constexpr (NaturalDimension == 2) {
      // For a unit triangle, area = 0.5.
      if constexpr (QuadratureOrder == 1) {
        // quadrature point location,  weight/area
        //  (1/3, 1/3)                     1.0
        std::vector<VectorD> points = {{1.0 / 3.0, 1.0 / 3.0}};
        std::vector<T> weights = {0.5};
        return std::make_pair(points, weights);
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[multibody/fem/dev/quadrature.h, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14202#-MJYX61l50FJyhrN1ju4:-MJc5b0J6XzYfzc8d16Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dea07bf64657ddd0e868aadcb6f2a2358518a15d/multibody/fem/dev/quadrature.h#L75)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I like that you compute the points and the weights in the constructor.

One more thing, I think the points and the weights should be computed at the same time? So I would recommend a function `ComputePointsAndWeights()`, which combines `GetPoints` and `GetWeights` function, something like this
```cc
    if constexpr (NaturalDimension == 2) {
      // For a unit triangle, area = 0.5.
      if constexpr (QuadratureOrder == 1) {
        // quadrature point location,  weight/area
        //  (1/3, 1/3)                     1.0
        std::vector<VectorD> points = {{1.0 / 3.0, 1.0 / 3.0}};
        std::vector<T> weights = {0.5};
        return std::make_pair(points, weights);
```
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14202#-:-MJcY2Mo6Ogc5OFWPwV_:bg7igkv)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
