### PR TITLE
update simulation environment for iiwa pick and place demo

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
1. added a wsg gripper with a "lip". there is a better way than completely duplicate the model. 
2. added a oracular state estimator to translate robot state into bot_core::robot_state_t lcm message. this is needed doing feedback in the planner. 
3. update the iiwa_wsg_sim.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5212)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai for feature,
+@sammy-tri for platform,
@liangfok for advice about the gripper model. 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdCkcrpQD45M02J7CdR:bto4c7)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

---

Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdHXZOCp4nUUCVBxP5J:bko8goz)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/models/objects/block_for_pick_and_place.urdf, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdHa4wbNpEkKXyz4yEi:-KdHa4wbNpEkKXyz4yEj:b5n1stz) ([raw file](https://github.com/robotlocomotion/drake/blob/7ea78316b53e816ae530f8a1e979dc0230f38fe1/drake/examples/kuka_iiwa_arm/models/objects/block_for_pick_and_place.urdf#L7)):*
> ```XML
>       <origin xyz="0 0 0" rpy="0 0 0" />
>       <mass value="0.1" />
>       <inertia ixx="0.004166" ixy="0" ixz="0" iyy="0.004166" iyz="0"
> ```

Is this the right number? It seems to me that `ixx + iyy < izz`, which violates the triangular inequality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdHadUMzUx-XGBzdZ_A:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/models/objects/block_for_pick_and_place.urdf, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdHa4wbNpEkKXyz4yEi:-KdHhsnXpMu3JChZZ_4N:b-awkq01) ([raw file](https://github.com/robotlocomotion/drake/blob/7ea78316b53e816ae530f8a1e979dc0230f38fe1/drake/examples/kuka_iiwa_arm/models/objects/block_for_pick_and_place.urdf#L7)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is this the right number? It seems to me that `ixx + iyy < izz`, which violates the triangular inequality.
</blockquote></details>

good catch. it's possible that i need to hack this number later though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by siyuanfeng-tri** [comment]
@hongkai-dai can you take another quick look? I added some code to add the gripper inertia stuff to the controller's RBT. 
thanks!
also i had to bump up the inertia for the block urdf, otherwise the sim blows up. 

---

Reviewed 2 of 4 files at r3.
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdISBy-2GLuNFE2TMPx:b-lpeobh)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by sammy-tri** [comment]
(review just started, still a lot to go.  sorry for the delays over the USA holiday weekend)

---

Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 378 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWBqXOvmTa2MO3wGA_:-KdWBqXOvmTa2MO3wGAa:bk02egr) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L378)):*
> ```cpp
>   auto iiwa_state_pub = builder.AddSystem(
>       systems::lcm::LcmPublisherSystem::Make<bot_core::robot_state_t>(
>           "IIWA_STATE_EST", &lcm));
> ```

What other code is the consumer of this message and OBJECT_STATE_EST?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdWCHDxs1yG2frOyNf9:b-tsbsfs)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 378 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWBqXOvmTa2MO3wGA_:-KdWCbUxKalwuGS5Usp6:b4oehtb) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L378)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

What other code is the consumer of this message and OBJECT_STATE_EST?
</blockquote></details>

the actual plan trajectory demo code. (in the next pr lol)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by siyuanfeng-tri** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 69 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWaO3LSsOxKicJozpK:-KdWiVdppVpsaJNpDMdA:b5b3w4c) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L69)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW is there some kind of assertion it's worth making about conditions where the number of positions/velocities doesn't match the number of actuators (or where the number of positions and velocities doesn't match?)  Obviously these conditions are not relevant for the iiwa, but...
</blockquote></details>

yeah. probably a good idea. added in the constructor. 

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 81 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWaGRYagQ41mfZfzZp:-KdWiy7QK9vX7NsdmcTM:babvrgt) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L81)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this be get_velocity_start_index?
</blockquote></details>

Done. it's the same for iiwa in this case. 

---

*[drake/examples/schunk_wsg/models/schunk_wsg_50_w_lip.sdf, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWawVJT-cxggAkDIw3:-KdWl6Uutqjp3GbGAMFX:b-30s5td) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/schunk_wsg/models/schunk_wsg_50_w_lip.sdf#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I did not attempt to review this.
</blockquote></details>

don't worry. i just copied pasted it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 2 of 8 files at r1, 3 of 3 files at r4.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 202 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWkcNUIVmkyAhkgUNU:-KdWkcNVJBMrYKRllduZ:b3lrvs5) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L202)):*
> ```cpp
>     RigidBody<T>* controller_ee =
>         iiwa_controller->get_robot_for_control().FindBody("iiwa_link_7");
>     controller_ee->set_spatial_inertia(lumped_gripper_inertia_EE);
> ```

Does this have the effect of including the inertia of the end effector in gravity compensation?  I'm not sure that resembles the physical arm's behavior very well if so (it certainly does not when the arm is in torque controlled mode).  I haven't done a lot of investigation of programming the parameters of the attached tool into KUKA's controller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdWmChx1AYkxeNBqpvw:bvb1a6z)*

**Comment by siyuanfeng-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 202 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWkcNUIVmkyAhkgUNU:-KdX6BAaR_C4doIMP-pD:b-n51vsd) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L202)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this have the effect of including the inertia of the end effector in gravity compensation?  I'm not sure that resembles the physical arm's behavior very well if so (it certainly does not when the arm is in torque controlled mode).  I haven't done a lot of investigation of programming the parameters of the attached tool into KUKA's controller.
</blockquote></details>

this pr includes the gravity comp for the gripper, which is sort of a must have for the current sim controllers, regardless of however kuka handles it in real life. the planning part doesn't care about the added gripper's inertia since that's all based on geometry.  

for the real arm, i'd assume their pid controller is going to handle the added mass of the gripper pretty well. 

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 69 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWaO3LSsOxKicJozpK:-KdX6kX3kDRq7ZvbByIr:bnisan) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L69)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

yeah. probably a good idea. added in the constructor. 
</blockquote></details>

opp. the unit tests actually caught something! i used this to publish status for the arm as well as the floating block. 
i can't just assert those due to the floating base. (the block is a floating thing with no actuators)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 202 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWkcNUIVmkyAhkgUNU:-KdX82NlRt2XN-2hx7er:b-vg1v28) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L202)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

this pr includes the gravity comp for the gripper, which is sort of a must have for the current sim controllers, regardless of however kuka handles it in real life. the planning part doesn't care about the added gripper's inertia since that's all based on geometry.  

for the real arm, i'd assume their pid controller is going to handle the added mass of the gripper pretty well. 
</blockquote></details>

If we can't tune our controller well enough to handle the tool being added to the end without using extra gravity compensation which isn't on the physical arm, I think it's at least worth adding a comment explaining what we're doing and that we know it isn't a match to the real hardware.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-:-KdXFcCMY3Y3OgynDWXZ:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 202 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5212#-KdWkcNUIVmkyAhkgUNU:-KdXKC6KkZsuZL8BVahx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b575fa04aa7fc53d26f160e23bdde7b9870b9b3c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L202)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

If we can't tune our controller well enough to handle the tool being added to the end without using extra gravity compensation which isn't on the physical arm, I think it's at least worth adding a comment explaining what we're doing and that we know it isn't a match to the real hardware.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5212)*

**Pull request merged**
