### PR TITLE
Make AddBilinearProductMcCormickEnvelopeSos2 a template function

### PR DESCRIPTION
**Pull request by hongkai-dai**
And also return lambda

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6617)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-KpX7hFplPO_SRe_vvuB:b-i3pynq)*

**Comment by EricCousineau-TRI** [comment]
For the commit message, could you add a quick blurb on the motivation for switching to templating? (optimizing for small variable sizes allocated many times, or something to that effect?)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KUgZZ3EzxP4iOlNX:-Kp_KUgZZ3EzxP4iOlNY:b-tyb8tj) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L120)):*
> ```objc
> 
> template <typename Derived>
> struct IsPhiValid {
> ```

BTW I believe the goal here may be to check if this is a vector of symbolic variables. You may also be able to do this with this function:
https://github.com/RobotLocomotion/drake/blob/6beff28/drake/solvers/create_constraint.h#L40

(sorry that it's not in a more aptly named header file)

---

*[drake/solvers/mixed_integer_optimization_util.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KFd9KRW_mVxdozq2:-Kp_KFdBGpMjuDOId_PZ:b-6bp45v) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L122)):*
> ```objc
> struct IsPhiValid {
>   static constexpr bool value =
>       std::is_base_of<Eigen::MatrixBase<Derived>, Derived>::value &&
> ```

I'm not sure if the above check, `is_base_of<...>` really does anything here.
Since `MatrixBase<Derived>` explicitly derives from `Derived` as part of a CRTP, I think this will always be true - you will run into another compiler error / substitution failure if the passed type cannot be deduced into something akin to `MatrixBase<Derived>`, but the error message may be a little more obscure.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_MavizLtlJ4DcHzWh:-Kp_MavizLtlJ4DcHzWi:b-cpogo1) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L205)):*
> ```objc
>       lambda.template cast<symbolic::Expression>().colwise().sum().transpose(),
>       By);
>   return lambda;
> ```

Is there ever a case where a user would want access to the bindings that are added here?
(And should that possibly be added to the unittest?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-Kp_LT36PtHNzcMHYSqh:bl4b8yr)*

**Comment by hongkai-dai** [comment]
Sure. There are two motivations to this PR
1. We can avoid the dynamic allocation for the newly created variable `lambda`.
2. Return `lambda` to the user. 

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KUgZZ3EzxP4iOlNX:-Kp_lHn9JXiksqifdsD5:b-b9eob4) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L120)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I believe the goal here may be to check if this is a vector of symbolic variables. You may also be able to do this with this function:
https://github.com/RobotLocomotion/drake/blob/6beff28/drake/solvers/create_constraint.h#L40

(sorry that it's not in a more aptly named header file)
</blockquote></details>

Thanks for providing this function! Maybe we can submit a separate PR which moves the functions in `detail` namespace to a separate file, so that we can use it afterwards? 

---

*[drake/solvers/mixed_integer_optimization_util.h, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KFd9KRW_mVxdozq2:-Kp_n8j6BPFaVxnhTkIC:bx40ouy) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L122)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I'm not sure if the above check, `is_base_of<...>` really does anything here.
Since `MatrixBase<Derived>` explicitly derives from `Derived` as part of a CRTP, I think this will always be true - you will run into another compiler error / substitution failure if the passed type cannot be deduced into something akin to `MatrixBase<Derived>`, but the error message may be a little more obscure.
</blockquote></details>

Got it, thanks for the explanation.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_MavizLtlJ4DcHzWh:-Kp_nJzWoD4yVq6-yKtJ:b-1uv99d) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L205)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there ever a case where a user would want access to the bindings that are added here?
(And should that possibly be added to the unittest?)
</blockquote></details>

Good question. The constraints on `lambda` is quite complicated, involving other variables in this case. I think it is cleaner if we just return lambda. In my use case I only need the variable (on which we can impose other constraints). 

I think usually we return the bindings, so that we can modify the constraint later. In this case I do not think we need to modify the constraint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-Kp_kr9Vo2ZBVc2FCnhy:b3dtdaw)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KUgZZ3EzxP4iOlNX:-Kp_qhU3G7zX83aQIAQM:b-97hdk1) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L120)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for providing this function! Maybe we can submit a separate PR which moves the functions in `detail` namespace to a separate file, so that we can use it afterwards? 
</blockquote></details>

How about consolidating them into `drake/common/eigen_types.h`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_KUgZZ3EzxP4iOlNX:-KpajJbT4zpMjaxJ6pH6:b-rlogx2) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L120)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How about consolidating them into `drake/common/eigen_types.h`?
</blockquote></details>

I like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kp_MavizLtlJ4DcHzWh:-Kpa0otFkuO3AzcDIssE:brxp9sd) ([raw file](https://github.com/robotlocomotion/drake/blob/438f0a33103fac736d94781f9aab5f16cac840d0/drake/solvers/mixed_integer_optimization_util.h#L205)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good question. The constraints on `lambda` is quite complicated, involving other variables in this case. I think it is cleaner if we just return lambda. In my use case I only need the variable (on which we can impose other constraints). 

I think usually we return the bindings, so that we can modify the constraint later. In this case I do not think we need to modify the constraint.
</blockquote></details>

Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-KparGfuDUmFkwnGp8Ab:bpqxd5f)*

**Comment by hongkai-dai** [comment]
+@seancurtis-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-KparPrzss8NRTPITdSc:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
A typo and question. +@sherm1 for final platform review.

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kpb76SIIAvwhQs_7Vy3:-Kpb76SIIAvwhQs_7Vy4:b-udsy6w) ([raw file](https://github.com/robotlocomotion/drake/blob/6a336f70d9ab6b537b2343bf2c4d9d13158270d0/drake/solvers/test/mixed_integer_optimization_util_test.cc#L303)):*
> ```cpp
>           EXPECT_NEAR(prog_.GetOptimalCost(), cost_at_vertices.minCoeff(),
>                       1E-4);
>           // Check that λ has the correct value, execpt λ(i, j), λ(i, j+1),
> ```

typo: s/execpt/except

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 304 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kpb7JYuQ0ySPaDZPg7N:-Kpb7JYuQ0ySPaDZPg7O:b-t07gqb) ([raw file](https://github.com/robotlocomotion/drake/blob/6a336f70d9ab6b537b2343bf2c4d9d13158270d0/drake/solvers/test/mixed_integer_optimization_util_test.cc#L304)):*
> ```cpp
>                       1E-4);
>           // Check that λ has the correct value, execpt λ(i, j), λ(i, j+1),
>           // λ(i+1, j) and λ(i+1, j+1), all other entries in λ are zero.
> ```

Not testing the core values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-Kpb7kVDLdJJHKwKssLg:bvaq3ue)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kpb76SIIAvwhQs_7Vy3:-KpbEtESpkhi8d5Rutrm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a336f70d9ab6b537b2343bf2c4d9d13158270d0/drake/solvers/test/mixed_integer_optimization_util_test.cc#L303)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

typo: s/execpt/except
</blockquote></details>

Done.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 304 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-Kpb7JYuQ0ySPaDZPg7N:-Kpb9DpHVM1ognBHAQEH:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/6a336f70d9ab6b537b2343bf2c4d9d13158270d0/drake/solvers/test/mixed_integer_optimization_util_test.cc#L304)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Not testing the core values?
</blockquote></details>

Done. Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-KpbF9KGBJBPveVr-Pf7:bmxilld)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6617#-:-KpbIUAm49vWV89t8BVI:bnfp4nl)*

**Pull request merged**
