### PR TITLE
Updates doc on CLion setup.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Updates doc to reflect the change of the externally visible build artifacts into drake-distro/build/install.
Also doc is updated on how to pass the right compilers to CLion.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2866)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sammy-tri since you are the platform reviewer of the day.
+@naveenoid for feature review since I think you are one of the CLion users.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KN8sD3uWlueyTvY2bML:-1213934387)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAAwk54QlMIpRu5SIO:-KNAAwk6vGMtKb89RxKL:-389584517) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L18)):*
> ```reStructuredText
> 1. :ref:`Build Drake <build_the_collection>` from the command line.
> 2. In the Welcome to CLion screen, click `Import Project from Sources`. Or from the menu `File > Import Project...`
> 3. Browse and select the `drake` sub-folder of your `drake-distro` install (i.e. `drake-distro/drake`) and click OK.
> ```

should this be "drake-distro install " or rather "your drake-distro clone"? The usage of "install seems ambiguous here..

---

*[drake/doc/clion.rst, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNABu7G08P3e2rUCUAf:-KNABu7H9Npb1gbRTP5W:1920031461) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L29)):*
> ```reStructuredText
>   * `F77=gfortran-4.9`      
>   You can copy these from this documentation one at a time and click on the `paste` button at the right of the environment variables dialog.
> 9. Click OK. CLion will take about a minute to reload the CMake Project. If everything is in order, there should be no errors or warnings. For fun, check out the CMake Cache pane too by the way; it's pretty handy.
> ```

I know these are not really your comments but perhaps you could clarify where is the CMakeCache pane? I never found it :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866)*

**Comment by liangfok** [comment]
Left a few comments.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/clion.rst, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAAwk54QlMIpRu5SIO:-KNAPMhWAOu78j9GFeVk:-517661150) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L18)):*
I recommend simplifying it to be:

> Browse and select `drake-distro/drake` and click OK.

This is because we can assume people are following the [official installation instructions](http://drake.mit.edu/from_source.html#getting-drake), which specify that Drake should be cloned into `drake-distro`. Users who choose to deviate from this must do so at their own peril :stuck_out_tongue_winking_eye: .

---

*[drake/doc/clion.rst, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAQ2L3n1UoWfzh0fEX:-KNAQ2L3n1UoWfzh0fEY:1427081745) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L22)):*
> ```reStructuredText
> 5. Go to CLion Preferences (on OSX, `CLion-EAP > Preferences`, on Ubuntu, `File > Settings...`). Note that this preferences window comprises both global settings and project-specific settings (as noted by the text 'for current project' on some of the preference pages).
> 6. Browse to `Build, Execution, Deployment > CMake`.
> 7. Under `CMake Options`, fill in `-DCMAKE_INSTALL_PREFIX=/absolute_path_to_your/drake-distro/build/install` or whatever the path to your build artifacts directory may be.
> ```

"build artifacts directory" should be "install directory". However, I think the entire "or whatever..." can be removed since users who choose to not follow the official installation instructions should also know how to adapt these instructions to their local configuration.

---

*[drake/doc/clion.rst, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAQkTt7QWAOSoDwvDS:-KNAQkTt7QWAOSoDwvDT:-349130286) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L29)):*
> ```reStructuredText
>   * `F77=gfortran-4.9`      
>   You can copy these from this documentation one at a time and click on the `paste` button at the right of the environment variables dialog.
> 9. Click OK. CLion will take about a minute to reload the CMake Project. If everything is in order, there should be no errors or warnings. For fun, check out the CMake Cache pane too by the way; it's pretty handy.
> ```

BTW, I recommend deleting "too by the way" since the sentence is arguably more clear and concise without those words.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KNAQvylNuFmuhmwuz5X:-2076087489)*

**Comment by sammy-tri** [comment]
:lgtm: on this because I don't have any issues with it at the platform level.  I'm not a CLion user and have not attempted to verify the instructions.  Thanks for @liangfok and @naveenoid for your help with the CLion parts.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KNCr2kNUPpY3ERrH70G:725180322)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/clion.rst, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAAwk54QlMIpRu5SIO:-KNCpxernAVWtP-dGGJd:13826373) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I recommend simplifying it to be:
> 
> > Browse and select `drake-distro/drake` and click OK.
> 
> This is because we can assume people are following the [official installation instructions](http://drake.mit.edu/from_source.html#getting-drake), which specify that Drake should be cloned into `drake-distro`. Users who choose to deviate from this must do so at their own peril :stuck_out_tongue_winking_eye: .
</details>
The simplified version looks much better. Accepted. I also added a like indicating we are expecting to have Drake cloned into drake-distro.

---

*[drake/doc/clion.rst, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNAQ2L3n1UoWfzh0fEX:-KNCqMyK_aF_a33tZP0k:501886373) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "build artifacts directory" should be "install directory". However, I think the entire "or whatever..." can be removed since users who choose to not follow the official installation instructions should also know how to adapt these instructions to their local configuration.
</details>
Agree. Also IMO the use of "whatever" does not sound very professional in any documentation.

---

*[drake/doc/clion.rst, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-KNABu7G08P3e2rUCUAf:-KNCw2E14_Fylp9q4Ta-:1366372492) ([raw file](https://github.com/robotlocomotion/drake/blob/89732a789ac14961100d3adc7b7c52886d7d1ee8/drake/doc/clion.rst#L29)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> I know these are not really your comments but perhaps you could clarify where is the CMakeCache pane? I never found it :(
</details>
Added some links. Hopefully it helps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KNCx3qhpWqmO3LD41n9:-1868698381)*

**Comment by liangfok** [comment]
Just waiting on @naveenoid to resolve two issues.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KNCxIVcv4CoOlSYgzE6:-1989346039)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2866#-:-KNDSqpGb_XWVYMUmAZj:1417088721)*

**Pull request merged**
