### PR TITLE
Remove Jammy APT packages warning from documentation

### PR DESCRIPTION
**Pull request by williamjallen**
The [documentation](https://drake.mit.edu/apt.html) currently indicates that no stable APT packages are published for Ubuntu 22.04 Jammy.

The warning has been removed since stable packages are now published.

Closes https://github.com/RobotLocomotion/drake/issues/18649.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654)

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
+@BetsyMcPhail for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-:-NMezvBN8GwbbhnBafUP:b6t817a)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-:-NMitkIo6pUQgxXMk0cU:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @williamjallen)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-NMiqP1p1hpYnyifs7t6):*
Nit could you please update the commit message to be a bit more descriptive (you should be able to update locally and force push). Suggestion "[doc] Remove outdated Jammy Apt packages warning"

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @williamjallen)

**Review by williamjallen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-NMnaim05IgmjLfjFBSl:-NMnaim15GOdWggowHgl:b-e5d69f) (no related file):*
+@ggould-tri for platform review as per schedule

___

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @williamjallen)

___
*[`doc/_pages/apt.md` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-NN20WqsDLDicCO49XyZ:-NN20WqsDLDicCO49Xy_:b-e6ud9c) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea2c5c3d7f8ef82b7f665d0373efb1c385d41a52/doc/_pages/apt.md#L9)):*
> ```Markdown
> Drake publishes pre-compiled binaries as APT packages (``*.deb``) for the
> Ubuntu 20.04 (Focal) and Ubuntu 22.04 (Jammy) operating systems.
> (At the moment, the Ubuntu 22.04 packages are only provided for nightly builds,
> ```

This comment also needs to be removed. I missed it on the first pass.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18654#-:-NN23dov1AOPY7Lw6Xxj:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Pull request merged**
