### PR TITLE
[multibody] Remove BlockSparseLinearOperator

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
BlockSparseLinearOperator is the LinearOperator version of BlockSparseMatrix. We anticipated that it might be useful when developing new contact solvers but it has since become unused.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

I'd be happy to remove all unused code in `contact_solvers` including all of the `LinearOperator`s as well as all the `ContactSolver`s. Let me know if you don't have plans to use them. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQRJaFwD9ZbyC9lOIBv:bfa7u3f)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
I think that if we are not using code, it is fair to remove it.

That being said, :lgtm:  for this PR

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQS6Q4aCe-mbSgwnTGr:b-t7vl8x)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQS6nIk3xHUDrSntreN:b-q8kqhl)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
Ok, I'll prepare a subsequent PR that removes more files and send you for review. Thanks!

-@SeanCurtis-TRI has timed out for today. +@sammy-tri for platform review on Tuesday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQS6hBi4oJv9FF4cg7m:b-qxfh1q)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
I think that `BlockSparseLinearOperator` meets the definition of "Stable API" from https://drake.mit.edu/stable.html

I think this means we need to go through the deprecation window, or come up with a reason why we're going to make a breaking change (e.g. we strongly believe that there are no downstream users for this code)

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQWEERDA4fZ8VWoMJT0:bdzn62z)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This class is internal so it should be fine.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQWFo635UCVvI6N71an:b-2iiu67)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
Whoops, missed the `namespace internal`.  :lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18986#-:-NQWGu247_chJBGmkLom:b-7f2nyj)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
OTOH the target `@drake//multibody/contact_solvers::block_sparse_linear_operator` is publicly visible, but since all code is internal, I'll assume this is not part of the stable API guarantee...

**Comment by jwnimmer-tri** [comment]
Correct.

> The Bazel Stable API covers all Drake Bazel targets with public visibility that refer to C++ or Python library code that is itself part of the “Stable API”.

In short -- labels for `namespace internal` code are not Stable.

**Pull request merged**
