### PR TITLE
Removes a KinematicsCache Constructor and Adds Unit Test to RBT:doKinematics() Verifying Elegant Handling of Maleformed Cache

### PR DESCRIPTION
**Pull request by liangfok**
The `KinematicsCache` constructor with two-parameters was resulting in confusion. This PR removes this constructor. The robustness of `RigidBodyTree::doKinematics()` was also increased to check for a `KinematicsCache` that is bad in terms of not having the proper number of `KinematicsCacheElement` objects. A unit test was added to lock in this newly added logic.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4685)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@jwnimmer-tri for platform review please.

Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_j78OZsfAylwQic3aM:b-y7ffu7)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 934 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBPdY1nEeFK_jHHCM:-K_jBPdY1nEeFK_jHHCN:b-mok6i0) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/rigid_body_tree.cc#L934)):*
> ```cpp
>   cache.setPositionKinematicsCached();
> 
>   if (cache.get_num_cache_elements() != static_cast<int>(bodies.size())) {
> ```

BTW, I wonder why we still don't have in `drake_throw.h` a `DRAKE_THROW(msg)`. Is that because we think it is a bad idea?

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBnuNOl7MTHJ5Zskc:-K_jBnuO6FERHJwJ79v7:b-iju803) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc#L445)):*
> ```cpp
> // number of KinematicCacheElement objects within it does not equal the number
> // of RigidBody objects within the RigidBodyTree.
> TEST_F(RigidBodyTreeTest, TestDoKinematicWithBadCache) {
> ```

BTW, There is no math in this file at all. I wonder if we should keep it that way and move this test into `rigid_body_tree_inverse_dynamics_test.cc`. 
Maybe even rename:
`rigid_body_tree_test.cc` --> `rigid_body_tree_creation_test.cc` (all creation/construction API tests)
`rigid_body_tree_inverse_dynamics_test.cc` --> `rigid_body_tree_dynamics_test.cc` (all dynamics related tests with math)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 934 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jCsUQYX0qjXuhNQMU:-K_jCsUQYX0qjXuhNQMV:b6koddo) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/rigid_body_tree.cc#L934)):*
> ```cpp
>   cache.setPositionKinematicsCached();
> 
>   if (cache.get_num_cache_elements() != static_cast<int>(bodies.size())) {
> ```

BTW, there are other reason why the cache may be malformed. You could have the same number of bodies but different dof's per body. So this test is not complete. I good approach would be to have a `RBT::CheckForValidCache(const KinematicsCache&)` that checks all sizes are consistent. This is something MBT will do well and therefore I won't block this PR for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 934 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBPdY1nEeFK_jHHCM:-K_jFhLduabWFJGdwIMO:bmqo0vq) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/rigid_body_tree.cc#L934)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I wonder why we still don't have in `drake_throw.h` a `DRAKE_THROW(msg)`. Is that because we think it is a bad idea?
</blockquote></details>

There is a `drake_throw.h` but the macro that it defines will result in a relatively less expressive error message. It will simply state that the call to RBT::CheckForValidCache() returned false. Should I use it regardless?

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBnuNOl7MTHJ5Zskc:-K_jG-OIw1zc2XqknsuV:b-3rnx18) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc#L445)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, There is no math in this file at all. I wonder if we should keep it that way and move this test into `rigid_body_tree_inverse_dynamics_test.cc`. 
Maybe even rename:
`rigid_body_tree_test.cc` --> `rigid_body_tree_creation_test.cc` (all creation/construction API tests)
`rigid_body_tree_inverse_dynamics_test.cc` --> `rigid_body_tree_dynamics_test.cc` (all dynamics related tests with math)
</blockquote></details>

I find it odd to test a method called `doKinematics()` in a unit test file called `rigid_body_tree_dynamics_test.cc`. How about I move this unit test into a new file called `rigid_body_tree_kinematics_test.cc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri 

You can add me back as platform once feature review decides where the pants are.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_jHJeFn5v2JgrF9RgG:bg9zm3z)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 934 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBPdY1nEeFK_jHHCM:-K_jUfEeLSvgOaUgTfhO:be8d487) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/rigid_body_tree.cc#L934)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

There is a `drake_throw.h` but the macro that it defines will result in a relatively less expressive error message. It will simply state that the call to RBT::CheckForValidCache() returned false. Should I use it regardless?
</blockquote></details>

BTW, Nope. `DRAKE_THROW_UNLESS` is pretty useless (to me at least). Much better would be to have a `DRAKE_THROW(message)` that you could use here. I thought this should be in your radar. Not blocking this PR though.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBnuNOl7MTHJ5Zskc:-K_jV03pBf9eOwS2POyQ:b-nmzh0c) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc#L445)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I find it odd to test a method called `doKinematics()` in a unit test file called `rigid_body_tree_dynamics_test.cc`. How about I move this unit test into a new file called `rigid_body_tree_kinematics_test.cc`?
</blockquote></details>

Either way (kinematics or dynamics) works for me. I just thought it'd be more organized to leave `rigid_body_tree_test.cc` with all the non-math related tests in there (and thus the suggested rename).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by gizatt** [comment]
General form of this PR looks good to me -- resolves an important confusion.  People trying to update Drake-dependent code that used the here-removed kinematics cache generation idiom (i.e. large amounts of code originating back during the DRC) might be a little confused, but I think the tests/examples and documentation will be sufficient. Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_jxOzSQFQzfM84lcGJ:b-rohjs2)*

**Comment by gizatt** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 934 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jCsUQYX0qjXuhNQMU:-K_lURhBq3O1pGGsxofR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/rigid_body_tree.cc#L934)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, there are other reason why the cache may be malformed. You could have the same number of bodies but different dof's per body. So this test is not complete. I good approach would be to have a `RBT::CheckForValidCache(const KinematicsCache&)` that checks all sizes are consistent. This is something MBT will do well and therefore I won't block this PR for this.
</blockquote></details>

Done.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_jBnuNOl7MTHJ5Zskc:-K_lUT948caR-ZPLNP5y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34c476ae280c8eec88b4d69284281c2ca223b807/drake/multibody/test/rigid_body_tree/rigid_body_tree_test.cc#L445)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Either way (kinematics or dynamics) works for me. I just thought it'd be more organized to leave `rigid_body_tree_test.cc` with all the non-math related tests in there (and thus the suggested rename).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_lVURdDOFZfKZ7R64-:bblnx7i)*

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks. Thus +@sammy-tri for platform review please.

---

Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_lzySQsPwTKuUjPwEq:b-ll1wvl)*

**Comment by amcastro-tri** [comment]
Reviewed 6 of 9 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 967 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oSMlsSyLhXAN3nFfA:-K_oSMlsSyLhXAN3nFfB:bcl3szp) ([raw file](https://github.com/robotlocomotion/drake/blob/a6216f239f3734db42fb8f66f7c13c206aeb0dfe/drake/multibody/rigid_body_tree.cc#L967)):*
> ```cpp
>       if (cache_element.get_num_positions() != joint.get_num_positions() ||
>           cache_element.get_num_velocities() != joint.get_num_velocities()) {
>         throw std::runtime_error("RigidBodyTree: CheckCacheValidity: Cache "
> ```

BTW, `RigidBodyTree::CheckCacheValidity()` to be more specify IMO

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_kinematics_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oRUtw3a1uoi09XI5T:-K_oRUtx2cpGd29Bc3xm:b-870tfa) ([raw file](https://github.com/robotlocomotion/drake/blob/a6216f239f3734db42fb8f66f7c13c206aeb0dfe/drake/multibody/test/rigid_body_tree/rigid_body_tree_kinematics_test.cc#L19)):*
> ```cpp
>  protected:
>   virtual void SetUp() {
>     tree_.reset(new RigidBodyTree<double>());
> ```

BTW, `tree_ = make_unique<RigidBodyTree<double>>()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 9 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 967 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oSMlsSyLhXAN3nFfA:-K_oVOP-FG9GxokYEBkd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6216f239f3734db42fb8f66f7c13c206aeb0dfe/drake/multibody/rigid_body_tree.cc#L967)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, `RigidBodyTree::CheckCacheValidity()` to be more specify IMO
</blockquote></details>

Done.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_kinematics_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oRUtw3a1uoi09XI5T:-K_oWJd2Feoo2h_zRJJb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6216f239f3734db42fb8f66f7c13c206aeb0dfe/drake/multibody/test/rigid_body_tree/rigid_body_tree_kinematics_test.cc#L19)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, `tree_ = make_unique<RigidBodyTree<double>>()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_oWPFyS_Cv_lDffRzG:bblnx7i)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 5 files at r1, 6 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 959 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oX9UNWctfmXGhIdLX:-K_oX9UON_edqV49eFe2:b4ls7a6) ([raw file](https://github.com/robotlocomotion/drake/blob/d5701e5a74ced7da8345b5df283e68ab68fedada/drake/multibody/rigid_body_tree.cc#L959)):*
> ```cpp
>         std::to_string(bodies.size()) + ")");
>   }
>   for (int i = 0; i < get_num_bodies(); ++i) {
> ```

Inconsistent use of get_num_bodies() vs bodies.size()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_oWUA2z69Te4vWy0h4:b-s794vx)*

**Comment by liangfok** [comment]
@sammy-tri I addressed your comment. PTAL. Thanks.

---

Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_tree.cc, line 959 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-K_oX9UNWctfmXGhIdLX:-K_p5Zjuw7boR2uFxNyG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5701e5a74ced7da8345b5df283e68ab68fedada/drake/multibody/rigid_body_tree.cc#L959)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Inconsistent use of get_num_bodies() vs bodies.size()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_p5dvKEmIgoExn1VO5:b-hzctqu)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r2, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_pEYSJzL0NBmL-xwuS:bnfp4nl)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please.

**Comment by liangfok** [comment]
Since @gizatt indicated approval of this PR above and it has both a platform and feature LGTM, I shall proceed with the merge.

-@gizatt 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4685#-:-K_pMj89kBVd8qAeT1NP:bipyu4c)*

**Pull request merged**
