### PR TITLE
Aggregate BoundingBoxConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248#-:-MKMqQar4eE0fNX5Z9mK:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248#-:-MKaIKAS8jb2Evgbo6jp:by96gdd)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKQO0304IBnFL-kZH_y:-MKQO0304IBnFL-kZH_z:b-obgf8d) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a8e8a2bb51e9b84c1ae2a2a27c6f931e47dfa8/solvers/aggregate_costs_constraints.h#L2)):*
> ```objc
> #pragma once
> #include <unordered_map>>
> ```

nit Double `>>`
___
*[solvers/aggregate_costs_constraints.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKQO8L84-1bDcQF0FLb:-MKQO8L926sJQ72TMT5a:bbxj7u8) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a8e8a2bb51e9b84c1ae2a2a27c6f931e47dfa8/solvers/aggregate_costs_constraints.h#L47)):*
> ```objc
> 
> /**
>  * Aggregate many bounding box constraints, return the intersection (the
> ```

nit GSG "Aggregates" not "Aggregate" (throughout), "returns" etc.
___
*[solvers/aggregate_costs_constraints.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKa3t-lBtLywlM3bE5a:-MKa3t-lBtLywlM3bE5b:bvza4gk) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a8e8a2bb51e9b84c1ae2a2a27c6f931e47dfa8/solvers/aggregate_costs_constraints.h#L54)):*
> ```objc
>  * bounding_box_constraints.
>  */
> std::unordered_map<symbolic::Variable, std::pair<double, double>>
> ```

I am not sure about using `pair` to mean `lower, upper` -- GSG suggests to avoid `pair` for this use case. 

https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Tuples

Would it work to have named results here (are there calling code samples we could evaluate to see how they work)?
___
*[solvers/aggregate_costs_constraints.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKQPWI848hhM9-wAEKl:-MKQPWI848hhM9-wAEKm:b-v7f4uv) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a8e8a2bb51e9b84c1ae2a2a27c6f931e47dfa8/solvers/aggregate_costs_constraints.cc#L170)):*
> ```cpp
>         bounds.emplace_hint(it, var, std::make_pair(var_lower, var_upper));
>       } else {
>         if (it->second.first < var_lower) {
> ```

nit This conditional is phrased backwards vs what's done in the other method below.  I actually thought it was wrong for a minute before I realized the swap.  How about `if (var_lower > it->second.first)`?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKa3t-lBtLywlM3bE5a:-MKb65WU51sWuTcXiBrh:b-x5ri2w) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a8e8a2bb51e9b84c1ae2a2a27c6f931e47dfa8/solvers/aggregate_costs_constraints.h#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not sure about using `pair` to mean `lower, upper` -- GSG suggests to avoid `pair` for this use case. 

https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Tuples

Would it work to have named results here (are there calling code samples we could evaluate to see how they work)?
</blockquote></details>

Done. I changed to use a struct.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248#-:-MKbb1Am93l3rrhLO7ec:b-n37teh)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.h, line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbaqn199XkpisgXWz0:-MKbaqn199XkpisgXWz1:b-on7mxk) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/aggregate_costs_constraints.h#L46)):*
> ```objc
>     VectorX<symbolic::Variable>* linear_vars, double* constant_cost);
> 
> struct Bound {
> ```

nit We need a class overview Doxygen here for the `drake::solvers::Bound` public symbol.
___
*[solvers/aggregate_costs_constraints.h, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbYY_iE44iTmsQJDrm:-MKbYY_iE44iTmsQJDrn:b38gti2) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/aggregate_costs_constraints.h#L47)):*
> ```objc
> 
> struct Bound {
>   Bound(double m_lower, double m_upper) : lower(m_lower), upper(m_upper) {}
> ```

nit I'm not sure what a `m_` prefix stands for?  In non-Google coding standards, sometimes it means "member", but that's is not the case here.

If we need to disambiguate args vs member fields, sometimes we append `_in` to the arg names to denote the inputs.

Alternatively, we don't strictly need a constructor here at all.  Using `Bound{.lower = var_lower, .upper = var_upper}` at the call site also works (once we remove this constructor).

Alternatively, if the defaults for lower and upper are the neg/pos infinities, then the cc file could be rephrased to be like a Python `defaultdict` (I think -- haven't tried it):
```c++
      if (it == bounds.end()) {
        it = bounds.emplace_hint(it, var);
      }
      if (var_lower > it->second.lower) {
        it->second.lower = var_lower;
      }
      if (var_upper < it->second.upper) {
        it->second.upper = var_upper;
      }
    }
```

(The default Bound constructor is the correct default value to insert into the map.  Once we've done that, we can proceed with narrowing it as usual.)
___
*[solvers/aggregate_costs_constraints.h, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbY_bK3VKjGtlztSb2:-MKbY_bK3VKjGtlztSb3:b-b7y2dh) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/aggregate_costs_constraints.h#L49)):*
> ```objc
>   Bound(double m_lower, double m_upper) : lower(m_lower), upper(m_upper) {}
>   double lower;
>   double upper;
> ```

nit Need `{}` on both of these.

https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization
___
*[solvers/test/aggregate_costs_constraints_test.cc, line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbb_-E0gHlB29yPwlz:-MKbb_-E0gHlB29yPwm-:bcbwmcj) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/test/aggregate_costs_constraints_test.cc#L290)):*
> ```cpp
>   EXPECT_EQ(result.size(), 3);
>   EXPECT_EQ(result.at(x_[0]).lower, 1.5);
>   EXPECT_EQ(result.at(x_[0]).upper, 2);
> ```

nit Consider maybe only checking `x_[1]` here -- it's probably safe to presume that `x[0]` and `x[2]` are fine, and repeating them is more noise to survey as a reader?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 46 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbaqn199XkpisgXWz0:-MKc-d0f5eArh9bdChXa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/aggregate_costs_constraints.h#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We need a class overview Doxygen here for the `drake::solvers::Bound` public symbol.
</blockquote></details>

Done.
___
*[solvers/aggregate_costs_constraints.h, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbYY_iE44iTmsQJDrm:-MKbzyLQDmhKbWpzEFjN:be4arhd) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/aggregate_costs_constraints.h#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure what a `m_` prefix stands for?  In non-Google coding standards, sometimes it means "member", but that's is not the case here.

If we need to disambiguate args vs member fields, sometimes we append `_in` to the arg names to denote the inputs.

Alternatively, we don't strictly need a constructor here at all.  Using `Bound{.lower = var_lower, .upper = var_upper}` at the call site also works (once we remove this constructor).

Alternatively, if the defaults for lower and upper are the neg/pos infinities, then the cc file could be rephrased to be like a Python `defaultdict` (I think -- haven't tried it):
```c++
      if (it == bounds.end()) {
        it = bounds.emplace_hint(it, var);
      }
      if (var_lower > it->second.lower) {
        it->second.lower = var_lower;
      }
      if (var_upper < it->second.upper) {
        it->second.upper = var_upper;
      }
    }
```

(The default Bound constructor is the correct default value to insert into the map.  Once we've done that, we can proceed with narrowing it as usual.)
</blockquote></details>

Done. Thanks! 

TIL struct initialization
___
*[solvers/test/aggregate_costs_constraints_test.cc, line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKbb_-E0gHlB29yPwlz:-MKc-WA513hhpvxf_nCl:br85zi4) ([raw file](https://github.com/robotlocomotion/drake/blob/d68993aa1e6d8c326c207c3026caad44f0b89ba9/solvers/test/aggregate_costs_constraints_test.cc#L290)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider maybe only checking `x_[1]` here -- it's probably safe to presume that `x[0]` and `x[2]` are fine, and repeating them is more noise to survey as a reader?
</blockquote></details>

I added more documentation.

I would like to keep the test. IMHO the more tests the better.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)* status: needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248#-:-MKc5tpXDhFOch4Wozzz:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with minor comments.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248#-:-MKelspY9BzsA-eQ3ONA:buozk8x)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.h, line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKehPhV3n92fZOTjwxb:-MKehPhV3n92fZOTjwxc:bckulo0) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L52)):*
> ```objc
>   /* Lower bound. */
>   double lower{};
>   /* Upper bound. */
> ```

FYI you can make these member comments show up in doxygen also (if you want them to) by starting them with `/**`. It looks like this:

___
*[solvers/aggregate_costs_constraints.h, line 60 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKeigtN5FqP0eXkwWpU:-MKeigtN5FqP0eXkwWpV:bqcfn7f) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L60)):*
> ```objc
>  * tightest bounds) of these constraints.
>  * @param bounding_box_constraints The constraints to be aggregated.
>  * @return aggregated_bounds aggregated_bounds[var.get_id()] returns the pair
> ```

nit: you want `@retval` here rather than `@return` so doxygen knows you are naming the return value. Then it looks like this:

___
*[solvers/aggregate_costs_constraints.h, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKejSW425gf7NolAAGD:-MKejSW425gf7NolAAGE:b-f80ylz) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L70)):*
> ```objc
> /**
>  * Aggregates all the BoundingBoxConstraints inside @p prog, returns the lower
>  * and upper bound for each variable in @p prog.
> ```

minor: should clarify that this signature also returns the intersection of the bounding box constraints.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[solvers/aggregate_costs_constraints.h, line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKehPhV3n92fZOTjwxb:-MKetveu2CDsapbgvwp1:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI you can make these member comments show up in doxygen also (if you want them to) by starting them with `/**`. It looks like this:


</blockquote></details>

Done, thanks!
___
*[solvers/aggregate_costs_constraints.h, line 60 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKeigtN5FqP0eXkwWpU:-MKeu2LH0cVETNDSX9XW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: you want `@retval` here rather than `@return` so doxygen knows you are naming the return value. Then it looks like this:


</blockquote></details>

Done.
___
*[solvers/aggregate_costs_constraints.h, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14248#-MKejSW425gf7NolAAGD:-MKeu9xhEzhWPHpf9AxA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2121e467a66929a55395f61b4c17629cadefb/solvers/aggregate_costs_constraints.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should clarify that this signature also returns the intersection of the bounding box constraints.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14248)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Pull request merged**
