### PR TITLE
setup: Upgrade recommended Bazel version to 5.1.0 for Linux

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #16865

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16878)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please. Homebrew has not updated to 5.1.0 yet, should we update the Mac documentation now or wait for homebrew?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16878#-:-MzGbzhZ2DEHrZifM9UM:b7xk005)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16878)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16878#-:-MzGrZSRCX3Ej84KTGVx:bnfp4nl)* status: missing label for release notes (waiting on @BetsyMcPhail)

**Pull request merged**
