### PR TITLE
Python binding for SetInitialGuess

### PR DESCRIPTION
**Pull request by gizatt**
@EricCousineau-TRI or @soonho-tri, would either of you be willing to give a quick review once I get this past tests?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8605)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

+(status: curate commits before merging) 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-:-LAFdLHX8VOOfssWao_x:bu0897m)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 401 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-LAFr8DuC9Li4-XmtLKD:-LAFr8DuC9Li4-XmtLKE:b-hb2oh3) ([raw file](https://github.com/robotlocomotion/drake/blob/f96945ced892c85a4cba22eac70db097708052db/bindings/pydrake/solvers/mathematicalprogram_py.cc#L401)):*
> ```cpp
>           [](MathematicalProgram& prog,
>              const MatrixXDecisionVariable& decision_variable_mat,
>              const Eigen::MatrixXd x0) {
> ```

BTW, can't it be `const Eigen::MatrixXd& x0` like C++ version? 

(also the one in below)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-:-LAFrRlq8CtwsfwXR-zN:bnfp4nl)*

**Comment by gizatt** [comment]
Thanks! +@sammy-tri for platform in the morning?

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 401 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-LAFr8DuC9Li4-XmtLKD:-LAFsi8e8hsLS9hiGi33:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f96945ced892c85a4cba22eac70db097708052db/bindings/pydrake/solvers/mathematicalprogram_py.cc#L401)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can't it be `const Eigen::MatrixXd& x0` like C++ version? 

(also the one in below)
</blockquote></details>

Done, thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-:-LAFslSsD9nDh8vtmXiT:b-2ejum0)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8605#-:-LAJI6vr0fmJdcgwXwu1:bnfp4nl)*

**Pull request merged**
