### PR TITLE
Ubuntu-14.04 Valgrind Fixes

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Related https://bugs.chromium.org/p/chromium/issues/detail?id=94174  ? 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5608)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot  linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source-drake please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-memcheck-tsan-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-tsan-open-source please

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/valgrind-cmake.supp, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5608#-Kh3Lj22kZuEcvMWF25I:-Kh3Lj22kZuEcvMWF25J:bam5bai) ([raw file](https://github.com/robotlocomotion/drake/blob/060816acc45d9439c3163e669066dfe2cca53c9a/tools/valgrind-cmake.supp#L154)):*
> ```
> }
> 
> # These memory leaks seem to be caused by EXPECT_DEATHs, when we remove those expectations
> ```

By "These", do you mean all the suppressions introduced in this PR?  If so, let's just get rid of the death tests, as in #5754

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5608#-Kh3Lj22kZuEcvMWF25I:-Kh3mnuIIvGdmp7VHYQt:brmmwrd) ([raw file](https://github.com/robotlocomotion/drake/blob/060816acc45d9439c3163e669066dfe2cca53c9a/tools/valgrind-cmake.supp#L154)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

By "These", do you mean all the suppressions introduced in this PR?  If so, let's just get rid of the death tests, as in #5754
</blockquote></details>

Yeah.  
Sure, let me try them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608)*

**Comment by m-chaturvedi** [comment]
Well, I checked all other occurrences of death tests (except urdf which you changed) , but they can't be replaced with runtime error exception tests because they don't throw any exception, simply abort.

**Comment by david-german-tri** [comment]
In the URDF example, I rewrote the code under test to throw an exception.  Are you saying that's not practical in the other cases?  Can you share an example?

**Comment by m-chaturvedi** [comment]
Yeah we expect the test should fail, not just with valgrind, but even without it.  Because we're looking for an exception where none exists.
Here's a branch I made with the output. 
https://github.com/m-chaturvedi/drake/commit/5524db4ae860e78d91fe57597382f1d2a80fa1bc

**Comment by m-chaturvedi** [comment]
The test was run with ` ctest --extra-verbose -R gain_test > gain_test_op.txt `

**Comment by m-chaturvedi** [comment]
I see, it's my mistake.  I didn't see that you'd changed the throwing of error.  I'm sorry.  I missed the last line where you throw the exception.

**Comment by m-chaturvedi** [comment]
So, one of the assertions is calling abort from drake_assert.cc:
https://github.com/RobotLocomotion/drake/blob/master/drake/common/drake_assert.cc#L20

The assertion calling it:
https://github.com/RobotLocomotion/drake/blob/master/drake/examples/kuka_iiwa_arm/test/sim_diagram_builder_test.cc#L133

It looked like a fundamental function for assertions.  Do you think I should change the abort to throw?

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by david-german-tri** [comment]
> It looked like a fundamental function for assertions. Do you think I should change the abort to throw?

Nope, that one clearly we keep (and suppress as necessary).

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608#-:-Khcji_S-Z_MCuVvGbvE:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608#-:-KhckGL6WL2PtR7WBHUL:bnfp4nl)*

**Comment by david-german-tri** [comment]
Override merging (I'm not sure why GitHub is blocking on the non-required build failure).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5608#-:-Khck_QesNMIzvfTLBxt:b5cxxip)*

**Comment by jamiesnape** [comment]
Some random Reviewable issue by the looks of it.

**Pull request merged**
