### PR TITLE
[Multilane] Loader to support lane-to-lane connections.

### PR DESCRIPTION
**Pull request by agalbachicar**
Modifies `multilane` loader to support lane-to-lane connections after PR #8973.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9090)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@rpoyner-tri for feature review please.

Tagging @maddog-tri for awareness. 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9090#-:-LGWCitbEEruCPu-hPCI:bhvqeeh)*

**Comment by rpoyner-tri** [comment]
Hi @agalbachicar, -@rpoyner-tri +@maddog-tri  since he is back from vacation.

---

Review status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9090#-:-LH4EZ-fCDRuAKRKsfDZ:btsdvsw)*

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all discussions resolved, LGTM missing from assignee maddog-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9090)*

**Comment by agalbachicar** [comment]
___
*[automotive/maliput/multilane/test/multilane_loader_test.cc, line 325 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9090#-LHdLZRU0jnRPfXUju0H:-LHiyKqpBjzYimAeFZDg:b-2580hj) ([raw file](https://github.com/robotlocomotion/drake/blob/15ccbaaaf6295f158311019f3ed90abe0f6d8cb1/automotive/maliput/multilane/test/multilane_loader_test.cc#L325)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Should be "connections.s1.start.2.forward" to keep the original structure (and the arc radius becomes 10, and the ref offset becomes 0 -- just like the changes to connection `s2`).

Otherwise, ASCII art needs to be updated.
</blockquote></details>

Hmm... this typo and your comment remembered me an old thought: `explicit_end` does not trigger any geometric check to validate that within linear and angular tolerance `(x,y,theta)` match from `start_spec` to the `explicit_end` with an `arc|line_offset` as we only use the `EndpointZ` of the point. So, should we add a TODO to check it?

**Pull request merged**
