### PR TITLE
pydrake: Add miscellaneous bindings to enable iiwa arm trajectory tracking w/ contact in Python

### PR DESCRIPTION
**Pull request by pangtao22**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055)

### CODE REVIEW

**Comment by pangtao22** [comment]
+@ericcousineau-tri for feature review. Thanks! 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055#-:-LFsIt45A71fPCBTDNLW:bde9f0)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor comments and a request to reword the title. Thanks!

+@sammy-tri for platform review, please.

---

Reviewed 9 of 9 files at r1.
Review status: 3 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsYA2SBrCjKqbQL1O1:-LFsYA2SBrCjKqbQL1O2:b-roi0pk) (no related file):*
Given that this is a useful but semi-miscellaneous set of Python bindings, can you reword the title of this PR to mention what workflow it enables?

Perhaps something like the following (but less, uh, butchered):
"pydrake: Add miscellaneous bindings to enable quasi-static optimization in Python"

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 268 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsXAGr5j0PW-BJblb2:-LFsXAGr5j0PW-BJblb3:b-7y3xq2) ([raw file](https://github.com/robotlocomotion/drake/blob/8a508f6e1e660e140cd57909ede19d812469b7fd/bindings/pydrake/multibody/rigid_body_tree_py.cc#L268)):*
> ```cpp
>       // centroidalMomentumMatrix
>       // forwardKinPositionGradient
>       // geometricJacobianDotTimesV
> ```

Can you keep the method definition starting at this line, without extra linebreaks?
(The esoteric ordering stuff is explained in the above lines, starting with `This lambda defines RigidBodyTree...`.)

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsX3cI-qFjT0XhSKNO:-LFsX3cI-qFjT0XhSKNP:bweuh84) ([raw file](https://github.com/robotlocomotion/drake/blob/85dfd077eeee184f6c14886b6a00e4fe6499d678/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L87)):*
> ```Python
>             self.assertTrue(
>                 plant.state_output_port() is not None)
>             if is_discrete is False:
> ```

Since this variable is not intended to be tri-modal, can you just use `not is_discrete`?

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsY3CC9viYhn4OjCax:-LFsY3CC9viYhn4OjCay:b-412hn8) ([raw file](https://github.com/robotlocomotion/drake/blob/85dfd077eeee184f6c14886b6a00e4fe6499d678/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L432)):*
> ```Python
>         # Test collision-related methods.
>         self.assertEqual(body.get_num_collision_elements(), 0)
>         body.get_collision_element_ids()  # check spelling.
> ```

BTW If it's simple to do, can you check then `len()` of the output of `get_collision_element_ids`?

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsXq0XE8ISYdd-ewLe:-LFsXq0YDj6iQwlJ4Pr7:b-1ti1vl) ([raw file](https://github.com/robotlocomotion/drake/blob/85dfd077eeee184f6c14886b6a00e4fe6499d678/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L73)):*
> ```Python
>         prog.AddQuadraticErrorCost(vars=x, Q=np.eye(2),
>                                    x_desired=np.zeros(2))
>         prog.AddL2NormCost(np.eye(2), np.zeros(2), x)
> ```

BTW Can you use the `kwarg` names?
```
prog.AddL2NormCost(A=np.eye(2), b=np.zeros(2), vars=x)
```

---

*[bindings/pydrake/test/trajectories_test.py, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsWtcfBoTBKWF2JCpp:-LFsWtcfBoTBKWF2JCpq:b9jm00r) ([raw file](https://github.com/robotlocomotion/drake/blob/85dfd077eeee184f6c14886b6a00e4fe6499d678/bindings/pydrake/test/trajectories_test.py#L35)):*
> ```Python
>         self.assertEqual(pp.get_segment_index(1.5), 1)
>         self.assertEqual(pp.get_segment_times(), [0., 1., 2.])
> ```

BTW Can you remove this extra linebreak?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055#-:-LFsYdzsDaQL27SoYKmH:b9ghfws)*

**Comment by pangtao22** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM from [ericcousineau-tri], commit history needs curation

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsYA2SBrCjKqbQL1O1:-LFscL2DCuzWwUFfECZC:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Given that this is a useful but semi-miscellaneous set of Python bindings, can you reword the title of this PR to mention what workflow it enables?

Perhaps something like the following (but less, uh, butchered):
"pydrake: Add miscellaneous bindings to enable quasi-static optimization in Python"
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 268 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsXAGr5j0PW-BJblb2:-LFs_wKn5TsoBBnFKfQL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8a508f6e1e660e140cd57909ede19d812469b7fd/bindings/pydrake/multibody/rigid_body_tree_py.cc#L268)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you keep the method definition starting at this line, without extra linebreaks?
(The esoteric ordering stuff is explained in the above lines, starting with `This lambda defines RigidBodyTree...`.)
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_plant_test.py, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsX3cI-qFjT0XhSKNO:-LFsa0EpDjC9x8SPB2yb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85dfd077eeee184f6c14886b6a00e4fe6499d678/bindings/pydrake/multibody/test/rigid_body_plant_test.py#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Since this variable is not intended to be tri-modal, can you just use `not is_discrete`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r1, 5 of 5 files at r2.
Review status: 3 unresolved discussions, platform LGTM from [ericcousineau-tri, sammy-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055#-:-LFt8YG2C3B1lNbIg1qz:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri, sammy-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 268 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9055#-LFsXAGr5j0PW-BJblb2:-LFt9TztAmX91swlhooi:b-52dmv8) ([raw file](https://github.com/robotlocomotion/drake/blob/8a508f6e1e660e140cd57909ede19d812469b7fd/bindings/pydrake/multibody/rigid_body_tree_py.cc#L268)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I may have not been specific enough (sorry about that!)
I went ahead and pushed the change that I had intended (keeping it at the line where the comment is).

(I also rebased + squashed.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9055)*

**Pull request merged**
