### PR TITLE
Add generated vscode folder to git ignore

### PR DESCRIPTION
**Pull request by tehbelinda**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12174)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@edrumwri for feature review please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please

**Comment by tehbelinda** [comment]
ok, closing

**Comment by sherm1** [comment]
We have CLion stuff in .gitignore -- why not vscode also?

**Pull request closed without merging**
