### PR TITLE
[workspace] Build yaml-cpp from source

### LINKED ISSUE #15868: Remove yaml-cpp as public dependency
In #7451 and #15815 we discuss the public header file dependencies of Drake.  In general, it's to our advantage to keep our public header footprint small, to maximize compatibility with our users who might want to use different version of those dependencies (e.g., #1183 or #14967).  For most libraries we depend on, we should build them with private symbols that only we can see, so that downstream users can build their own, different version if they need to.

For vocabulary types like Eigen, it's appropriate to have a public dependency.  However, for yaml-cpp, we mostly only use it for parsing, not as an abstract syntax tree (AST), so there is no great reason why it's currently a public dependency.  Furthermore, it is a C++ library and does not try to handle ABI compatibility carefully, so has a somewhat higher chance of causing trouble than other, simpler libraries.  (It's upstream maintainer is also no longer very active, and is seeking volunteers to take over.)

We should implement a minimal AST on our own that we can code against (in both our h and cc files), and only rely on yaml-cpp for it's parsing front-end, private to our cc files.

This will also enable us to easily pull in newer revisions of yaml-cpp with parser fixes.  As it stands now, because it's a public dependency, we are stuck being pinned to the Ubuntu version.

Relatedly, it's AST uses a confusing form of value syntax that actually has mutable reference semantics, so the readability of our code that's written against that API is a constant struggle.  Using our own AST will be an improvement on that front as well.

- [x] #15865
  - [x] #15910
  - [x] #15934
    - [x] #15940
  - [x] #15894 
- [x] #15866
- [x] #15867
  - [x] #15890
- [x] #16000
- [x] #15902
- [x] Port all of Drake to the new sugar
  - [x] #15998
  - [x] #16049
  - [x] #16050
- [x] Port all of Anzu to the new sugar
  - [x] #16059
  - [ ] Add option to specify ignored keys.
- [x] #16083
- [x] #16057
- [x] The "Archive" classes are all marked "Advanced".  Should they just be internal, instead? => deferred to #16706.
- [x] After the deprecations die on 2022-03-01, make the dependency actually private:
   - [x] #16701 Remove yaml-cpp from `drake-config.cmake` and the related installation infrastructure.
   - [x] #16701 Switch yaml-cpp to build from source with hidden symbols and upgrade to the latest tagged source release, and remove our one vendored upstream file from Drake.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Upgrade to use 0.7.0 on all platforms.

This will enable us to patch some I/O bugs, down the road:

https://github.com/RobotLocomotion/drake/blob/06e1deb12539f05eff968c5bd9e11d259916f268/common/yaml/yaml_write_archive.h#L275-L282

This reverts commit a1baff7f4c4f87e23a3517b3974240d405f6ab60 (#16728), effectively re-applying 62ce208922f4a192f74c67dc655cf52a07e1011f (#16701) but with heavy edits in support of a better deprecation path.

Closes #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @mwoehlke-kitware FYI on yaml-cpp dependency change.

+@rpoyner-tri for feature review, please.

In the future, I think we should switch to using this new tooling for all of our private dependencies, instead of only passing `copts = ["-fvisibility=hidden"]` like we do for them currently.  When statically linking, the copt is not sufficient hiding because it's still the same DSO.  (Also, clang's linker on macOS is very whiny about `-fvisibility=hidden` when we have C++ code using the standard library, emitting weak `std::vector<ThirdPartyType>` symbols and such.)

**Comment by mwoehlke-kitware** [comment]
Has this been tested on a wheel build? It removes the build of yaml-cpp itself (which I think is correct), but not Drake's bazel references to it, which seems likely to fail? (Or does it succeed only because nothing ever actually uses `@yaml_cpp`?)

Is it possible to totally remove the `repository.bzl` logic for `manylinux`?

**Review by rpoyner-tri — COMMENTED** [review]
checkpoint after first read-through. Still working on understanding the whole picture.

> Reviewed 25 of 27 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756#-:-MxoaQaR6aQgJov3bPjz:b-95j42x)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/yaml_cpp/package-macos.BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoTEH-CD3DwQUSp4Dj:-MxoTEH-CD3DwQUSp4Dk:b-kns3o3) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/package-macos.BUILD.bazel#L12)):*
> ```
> cc_library(
>     name = "yaml_cpp",
>     deprecation = "DRAKE DEPRECATED: The @yaml_cpp alias for the operating system's libyaml-cpp is no longer used by Drake. If you still to use it, you may copy the @yaml_cpp_deprecated rules into your own project. This target will be removed removed from Drake on or after 2022-07-01.",  # noqa
> ```

typo. still want? still need?



_Code quote:_
```
still to use
```
___
*[tools/workspace/yaml_cpp/package-macos.BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoTKtr0oN3kxZM7uYI:-MxoTKtr0oN3kxZM7uYJ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/package-macos.BUILD.bazel#L12)):*
> ```
> cc_library(
>     name = "yaml_cpp",
>     deprecation = "DRAKE DEPRECATED: The @yaml_cpp alias for the operating system's libyaml-cpp is no longer used by Drake. If you still to use it, you may copy the @yaml_cpp_deprecated rules into your own project. This target will be removed removed from Drake on or after 2022-07-01.",  # noqa
> ```

typo



_Code quote:_
```
removed removed
```
___
*[tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoTUFE7BoaIubM6qiv:-MxoTUFE7BoaIubM6qiw:b-j9dqi6) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel#L7)):*
> ```
> cc_library(
>     name = "yaml_cpp",
>     deprecation = "DRAKE DEPRECATED: The @yaml_cpp alias for the operating system's libyaml-cpp is no longer used by Drake. If you still to use it, you may copy the @yaml_cpp_deprecated rules into your own project. This target will be removed removed from Drake on or after 2022-07-01.",  # noqa
> ```

typo. Same ones as the other instance of this message.
___
*[tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoTZ8D5IWpZHwC-l30:-MxoTZ8D5IWpZHwC-l31:b-dkiflo) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel#L7)):*
> ```
> cc_library(
>     name = "yaml_cpp",
>     deprecation = "DRAKE DEPRECATED: The @yaml_cpp alias for the operating system's libyaml-cpp is no longer used by Drake. If you still to use it, you may copy the @yaml_cpp_deprecated rules into your own project. This target will be removed removed from Drake on or after 2022-07-01.",  # noqa
> ```

typo. ditto the ones above.

**Comment by jwnimmer-tri** [comment]
___
*[tools/workspace/yaml_cpp/repository.bzl, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoZ84B8_K_ODScJKU1:-MxodZOi8Z__V5jzjwCL:b-rlvs7h) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/repository.bzl#L27)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Can we make it so the `manylinux` case just does nothing (no `include` symlink, since that won't exist) and (add) an empty `BUILD`? That would "obviously" be the correct thing then for `macos_wheel` also.
</blockquote></details>

Yup, that's my plan.

I think the wheel builds will completely skip this code in any case (since the repository is not depended on anywhere), but I'm happy to make it a no-op just to be safe.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/workspace/yaml_cpp/repository.bzl, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16756#-MxoZ84B8_K_ODScJKU1:-MxoezCmDbDQ1drZp5L6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/276ffac67d6f198c5de8cdcd9603f436278710b7/tools/workspace/yaml_cpp/repository.bzl#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yup, that's my plan.

I think the wheel builds will completely skip this code in any case (since the repository is not depended on anywhere), but I'm happy to make it a no-op just to be safe.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756#-:-Mxp0RjyBnxt0FdR_gdj:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform

> Reviewed 21 of 27 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16756#-:-MxpYRCD8ZKileTf2eSr:b-71a3kq)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
