### PR TITLE
[geometry/optimization] fix vpolytope test for mosek

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16287)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai -- are you willing to give me a feature review, please?

Given the circumstances (and how minor this change is), I think that your review will be sufficient for me to merge.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16287#-:-Mrwvhm5CLdsfYcXrykZ:b-3e2q4y)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16287#-:-Mrww4A66js2SD1Hee3A:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-release please.

**Comment by RussTedrake** [comment]
@svenevs -- fyi.  This should resolve the issue noted in #16286.

**Pull request merged**
