### PR TITLE
Fix cpplint readability/todo

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all cpplint readability/todo errors, and enable the warning.

I filled in most of the proposed TODO-blame content here using the github usernames of the most recent 'git blame' for the comment, working back in history prior to the Drake Refactor Bot.  (Some comments already had usernames, and just needed the parens.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2184)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri Could you review?

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2184#-:-KGFlbK5BZTD6w3cgmrc:-1965089507)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 31 of 32 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2184#-:-KGHOx7NorP4uUOSQFOm:-1868698381)*

**Comment by jwnimmer-tri** [comment]
Jenkins is red due only to #2154.  This should me ready to merge after the platform review happens.

**Comment by ggould-tri** [comment]
:lgtm:.  One quibble, noted below, which you may resolve or not at author's discretion.

---

Reviewed 31 of 32 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/SnoptSolver.cpp, line 434 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2184#-KGHqccLtAiGEON9s6FQ:-KGHqccLtAiGEON9s6FR:-818169337) ([raw file](https://github.com/robotlocomotion/drake/blob/ed444c2c0b3d2e67c3b877623f66cb36e8c09fcd/drake/solvers/SnoptSolver.cpp#L434)):*
Should be sammy-tri (for consistency with how we todo sammy elsewhere)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2184#-:-KGHrTHhD-FdZqaCuH_i:1398335323)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/SnoptSolver.cpp, line 434 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2184#-KGHqccLtAiGEON9s6FQ:-KGHw_A94bN09LYPsRRy:4688993) ([raw file](https://github.com/robotlocomotion/drake/blob/ed444c2c0b3d2e67c3b877623f66cb36e8c09fcd/drake/solvers/SnoptSolver.cpp#L434)):*
I was going to leave well enough alone if @sammy-tri wrote it this way initially.  _Shrug_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2184)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Can you double check me that the build error is #2154 and then override-merge this?

**Comment by david-german-tri** [comment]
Confirmed.  Merging.

**Pull request merged**
