### PR TITLE
Move acrobot monte carlo simulation out of dev

### PR DESCRIPTION
**Pull request by ggould-tri**
* Toward #13904
 * This is the infrastructure to run monte carlo simulations
   of the acrobot under Spong control.
 * This is an example of how to use the stochastic schema
   mechanism for monte carlo testing
 * A subsequent PR will bring in an example of using this along
   with an optimizer to learn controller parameters (that code
   remains in dev in this PR)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522)

### CODE REVIEW

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14522#-MQsdhh877JFpodDHW96:-MQsdhh877JFpodDHW97:b-e3xsc0) (no related file):*
(test message to debug reviewable issue)

---

**Review by ggould-tri — COMMENTED** [review]
+(priority: low) +(type: feature request) +(type: TRI anzu wishlist) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MQsdlHu3raIVUIjNVVx:bu2t76q)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
+@rpoyner-tri for feature review (last person to touch this directory not involved in writing this code)

Note:  This code is moving out of dev and has not had Drake review; please expand and review each moved (non-BUILD) file as-new.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MQsdnwj-J_XWxOfyevq:b2rpadw)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
With the new stuff coming in, I'd like to advocate for a `README.md` in this folder that explains how to browse and run what's available.  It used to be fairly homogeneous, but is no longer so.

**Comment by ggould-tri** [comment]
For informational purposes, you can be informed by https://github.com/ggould-tri/drake/blob/acrobot_monte_carlo_dedev_2/examples/acrobot/README.md as a draft README.  That README is long enough that I don't want to include in this PR, and also it needs a bit more polish.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@sammy-tri  for platform Wednesday schedule.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MQwwk-h0KHwHwAV6tEu:bg6pt6a)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Making super-slow progress on this due to higher priority items being added to my queue today.  Will resume tomorrow if I don't manage to finish tonight.

> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MQxucaYDycT0NJVflJT:bqr7pnr)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522)* status: LGTM missing from assignee sammy-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
No worries; that's why I marked it low priority :-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MR02X8h1mf7N4AFaoUl:bp7gdmh)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14522#-:-MR1rBR8E_aGezJLn2Us:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
