### PR TITLE
Suppress Wunused-parameter in off-by-default solvers code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6053)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6053#-:-Kjd29vOTSf4OVXRQc49:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri self assign

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6053#-:-Kjd2FY7voeo5Ke8oHMu:bm0t07k)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6053#-:-Kjd2f63taAeI2o5zIEg:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6053#-:-Kjd2mmU46buT7VEpHrr:bnfp4nl)*

**Pull request merged**
