### PR TITLE
Remove calls to some of the deprecated functions in rotation_matrix_deprecated.h

### PR DESCRIPTION
**Pull request by mitiguy**
At calling sites, remove calls to some of the deprecated functions in rotation_matrix_deprecated.h

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8311)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review @seancurtis-tri 
Platform review @sherm1 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-:-L7B25MfQZs1YDBYdnEl:bgg0pup)*

**Comment by mitiguy** [comment]
Feature review +@SeanCurtis-TRI
Platform review +@sherm1

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-:-L7B492wbgJ-TX21FSaA:bhpgij7)*

**Comment by sherm1** [comment]
Per f2f - should also DRAKE_DEPRECATE the old method if all calls have been removed (that way they won't come back!).

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-:-L7BFOqi9LOU2hgW7btz:b-jwez1m)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

Quick thought/question for you two. As I looked at the change to the call, I note that we're *producing* a `RotationMatrix` but then throwing it out in favor of just stashing its underlying matrix. Would this code be better off actually using a `RotationMatrix`? I assume the answer, generally, is probably yes. However, by doing this API change, we've reduced the pressure on the owners of this code to do so. In other words, we're not using the deprecation to get replace `Matrix3` with `RotationMatrix` and that seems a loss but we are removing a potential vector to apply pressure to affect that change down the road.

Thoughts?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-:-L7BcthIdu5yQRejiEXT:b-797s87)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/global_inverse_kinematics.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-L7BpGT117-CrG64lFhP:-L7BpGT2NpXKUAd2u-rX:b7fzak1) ([raw file](https://github.com/robotlocomotion/drake/blob/8183ba55aff8207211d419fb93175dd387184421/multibody/global_inverse_kinematics.cc#L182)):*
> ```cpp
>       // p_WBi is the position of the body frame in the world frame.
>       const Vector3d p_WBi = GetSolution(p_WBo_[body_idx]);
>       const Matrix3d normalized_rotmat =
> ```

BTW per f2f should be a RotationMatrix here, with the `.matrix()` used as needed below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311)*

**Comment by sherm1** [comment]
Looks great -- platform :lgtm:.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8311#-:-L7BuRX5EnEvcPl5JLny:bj0mx0x)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: feature

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8311#-:-L7C0MuZikG4W1shoNKp:b-vycl09)*

**Comment by jwnimmer-tri** [comment]
> Per f2f - should also DRAKE_DEPRECATED the old method if all calls have been removed (that way they won't come back!).

FYI On master, calling a deprecated method produces a warning but doesn't fail CI.  After #8259, re-introducing calls to a deprecated method would be caught by CI.

**Pull request merged**
