### PR TITLE
Disables monolithic p&p test scenario 5.

### PR DESCRIPTION
**Pull request by edrumwri**
Disables this brittle test in CI- test can still be run manually- in order to pass the nightly build.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7054)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sammy-tri for feature and platform review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7054#-:-KuQmQnHitLIpfK9vWOB:bvxy5ls)*

**Comment by sammy-tri** [comment]
:lgtm:  Sorry this got in your way, I'll look at prioritizing the replacement planner to try to make sure you don't need to do this again.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7054#-KuQn1BWTSa7Lm_ktSIF:-KuQn1BWTSa7Lm_ktSIG:b855t2b) ([raw file](https://github.com/robotlocomotion/drake/blob/b7d6288079c2cc3b01d6d84468d01e655dc01f06/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L136)):*
> ```Python
> )
> 
> # TODO(sam.creasy) Re-enable this test once it is not so sensitive.
> ```

BTW the spelling of my name 3 lines below is the correct one (also occurs earlier in this file in the TODO disabling scenario 1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7054#-:-KuQnAvO45s-yyjLSDL_:b-adhm1h)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7054#-KuQn1BWTSa7Lm_ktSIF:-KuQo4qyI9ORmy_F1dBN:b4uddjl) ([raw file](https://github.com/robotlocomotion/drake/blob/b7d6288079c2cc3b01d6d84468d01e655dc01f06/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L136)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW the spelling of my name 3 lines below is the correct one (also occurs earlier in this file in the TODO disabling scenario 1)
</blockquote></details>

BTW Done. (Sorry!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7054)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7054#-:-KuQs3kkjbxnCzxjOxdp:b-s794vx)*

**Pull request merged**
