### PR TITLE
Add utility for computing convex hull of a Wavefront OBJ file

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Provides a new stand-alone function that will read an obj file and produce a mesh representation of its convex hull.

This introduces the computation of the convex mesh. The application of the mesh for proximity geometry visualization will come in a follow up PR.

Related to #20618.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@DamrongGuoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrDGEHu0LXD1-I9QA5l:b-feiw5h)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
Checkpoint.  I have finished the main code.  I'll check the tests after lunch.

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrHNi1-C-O_l7F2c2IX:b-o2s9hj)* status: 8 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.h` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrGvqbnB9MGJXBUv-Os:-NrGvqbnB9MGJXBUv-Ot:bnfti6s) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.h#L9)):*
> ```objc
> namespace geometry {
> 
> /** Creates a mesh representing the convex hull of a Convex or Mesh shape.
> ```

BTW, would you like to say the output mesh is polygonal, not triangulated, not tetrahedral?



_Suggestion:_
```objc
/** Creates a polygonal mesh representing the convex hull of a Convex or Mesh shape.
```
___
*[`geometry/proximity/make_convex_hull_mesh.h` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrGwYKk-pkpQwvFO7Gf:-NrGwYKk-pkpQwvFO7Gg:b-ermoe9) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.h#L14)):*
> ```objc
> 
>  @throws if `shape` is not an instance of Mesh or Convex.
>  @throws if the mesh references anything but an obj. */
> ```

BTW, would this be clearer?



_Suggestion:_
```objc
 @throws if `shape` references anything but a Wavefront OBJ file. */
```
___
*[`geometry/proximity/make_convex_hull_mesh.h` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH5TLD8nkE83abJzx8:-NrH5TLD8nkE83abJzx9:bjawsbb) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.h#L14)):*
> ```objc
> 
>  @throws if `shape` is not an instance of Mesh or Convex.
>  @throws if the mesh references anything but an obj. */
> ```

BTW, I saw this `throw` in the code and wondered whether we should document it or not?

```
    throw std::runtime_error(
        fmt::format("MakeConvexHull failed. Qhull terminated with status {} "
                    "and  message:\n{}",
                    qhull.qhullStatus(), qhull.qhullMessage()));
```



_Suggestion:_
```objc
 @throws if the mesh references anything but an obj.
 @throws if we can't compute the convex hull. */
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrGxJWh7PrQHd7m91B_:-NrGxJWh7PrQHd7m91Ba:b-62vom4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.cc#L12)):*
> ```cpp
> #include <libqhullcpp/Qhull.h>
> #include <libqhullcpp/QhullFacet.h>
> #include <libqhullcpp/QhullVertexSet.h>
> ```

Thank you for showing me how to use Qhull.



_Code quote:_
```cpp
#include <libqhullcpp/Qhull.h>
#include <libqhullcpp/QhullFacet.h>
#include <libqhullcpp/QhullVertexSet.h>
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH4rjqC4Ifu_Zpx0Hv:-NrH4rjr0ZL0TlrubtLD:b7obld8) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.cc#L143)):*
> ```cpp
>   qhull.runQhull("", dim, v_reader.vertices().size(),
>                  reinterpret_cast<const double*>(v_reader.vertices().data()),
>                  "");
> ```

BTW, would this help the reader?  When I saw the empty strings, I wasn't sure what they were.



_Suggestion:_
```cpp
  qhull.runQhull(/**inputComment*/ "", dim, v_reader.vertices().size(),
                 reinterpret_cast<const double*>(v_reader.vertices().data()),
                 /*qhullCommand*/ "");
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH65V41B78KrVErnLX:-NrH65V41B78KrVErnLY:b-pmi4g0) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.cc#L148)):*
> ```cpp
>     throw std::runtime_error(
>         fmt::format("MakeConvexHull failed. Qhull terminated with status {} "
>                     "and  message:\n{}",
> ```

BTW, remove extra space.



_Suggestion:_
```cpp
                    "and message:\n{}",
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH9uZC2kzZRC0CVqXz:-NrH9uZC2kzZRC0CVqY-:bj3nz2u) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.cc#L152)):*
> ```cpp
>   }
> 
>   // A mapping from qhull vertex ids to indices in the final mesh (vertices_M).
> ```

BTW, at first, I wonder whether `id_to_mesh_index` is an identity map.  Then, I read that [QhullVertexList](http://www.qhull.org/html/qh-code.htm#TOC) is a linked list, so I imagine the order of entries in the linked list does not necessarily follow the `QhullVertex::id()`.

Please feel free to edit or remove my addition.



_Suggestion:_
```cpp
  // A mapping from qhull vertex ids to indices in the final mesh (vertices_M).
  // The qhull.vertexList() is a linked list, and the unique QhullVertex::id()
  // can be arbitrary.
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHMc2TBEovvi5kgQFz:-NrHMc2TBEovvi5kgQG-:b-fyd2l1) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L48)):*
> ```cpp
>   const vector<Vector3d>& vertices() const { return vertices_; }
> 
>   const vector<vector<int>> faces() const { return faces_; }
> ```

BTW, missing `&` ?



_Suggestion:_
```cpp
  const vector<vector<int>>& faces() const { return faces_; }
```

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with minor questions.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrHh0Ct38gCDszvl-LL:bed8puf)* status: 14 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.h` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHdReN1TT9rUL7GWMW:-NrHdReO2--qQ8ig2lJc:b3jnwnj) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.h#L7)):*
> ```objc
> 
> namespace drake {
> namespace geometry {
> ```

BTW, is `MakeConvexHull` public API?  Is there a follow-up python-binding PR?



_Code quote:_
```objc
namespace drake {
namespace geometry {
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 128 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH_PK5-t7MMC0TwZjN:-NrH_PK5-t7MMC0TwZjO:b-jkoztn) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L128)):*
> ```cpp
>                     |/
>    -----------------o-------o---------
>                  v0 |       v1
> ```

BTW, add axis labels, please.



_Suggestion:_
```cpp
 We'll build the following tet:

                    Z
                    |
                 v3 o     Y
                    |    /
                    |   o v2
                    |  /
                    | /
                    |/
   -----------------o-------o--------- X
                 v0 |       v1
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 201 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHcrqIBeImgViTrytj:-NrHcrqIBeImgViTrytk:b-5nbsvw) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L201)):*
> ```cpp
> /* Expects that the meshes are equivalent. Equivalence is defined as follows:
>   - Same number of elements (vertices and polygons)
>   - There exists a bijection between the vertices of `dut` and `expected` such
> ```

BTW, typos?



_Suggestion:_
```cpp
  - There exists a bijection between the vertices of `dut_mesh` and `expected_mesh` such
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHd3jo7fWycwMD3YtU:-NrHd3jo7fWycwMD3YtV:bnmsgo2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L205)):*
> ```cpp
>   - There exists a bijection between the polygons of the two meshes such that
>     for a mapped pair:
>       - */
> ```

nit, incomplete sentence?



_Code quote:_
```cpp
  - There exists a bijection between the polygons of the two meshes such that
    for a mapped pair:
      - */
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 229 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHVzbqCIdm4KcypvCH:-NrHVzbr4BAbDoSmZ4eP:b98yzes) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L229)):*
> ```cpp
>     }
>   }
> }
> ```

BTW, is this leftover from debugging?  I don't see how it's related to `MakeConvexHull()`.



_Code quote:_
```cpp
GTEST_TEST(CompareTest, Compare) {
  vector<Vector3d> ordered{Vector3d(-1, -1, -1), Vector3d(-1, -1, 1),
                           Vector3d(-1, 1, -1),  Vector3d(-1, 1, 1),
                           Vector3d(1, -1, -1),  Vector3d(1, -1, 1),
                           Vector3d(1, 1, -1),   Vector3d(1, 1, 1)};

  for (int i = 0; i < ssize(ordered); ++i) {
    const Vector3d& a = ordered[i];
    for (int j = i + 1; j < ssize(ordered); ++j) {
      const Vector3d& b = ordered[j];
      ASSERT_TRUE(std::lexicographical_compare(a.data(), a.data() + 3, b.data(),
                                               b.data() + 3))
          << fmt::format("{}", fmt_eigen(a.transpose())) << " < "
          << fmt::format("{}", fmt_eigen(b.transpose()));
    }
  }
}
```
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 245 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHeHF89YU0VqliDjZo:-NrHeHF9Dvz9KIbbFeGo:bfr4m7p) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L245)):*
> ```cpp
>                               ".* only applies .*");
>   DRAKE_EXPECT_THROWS_MESSAGE(MakeConvexHull(Sphere(1)), ".* only applies .*");
> }
> ```

BTW, should we test this `throws` too?

```
 @throws if the mesh references anything but an obj. */
```



_Code quote:_
```cpp
}
```

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012)* status: 14 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-Nra12a10bheSsY13Cwo:bppyoqq)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.h` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHdReN1TT9rUL7GWMW:-Nr_y2pQ8Qg3BsfLxi0h:bkw5snn) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.h#L7)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, is `MakeConvexHull` public API?  Is there a follow-up python-binding PR?
</blockquote></details>

Done

I've moved it to internal for now so i can defer the question. I haven't come up with an explicit strategy one way or the other.
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrH9uZC2kzZRC0CVqXz:-Nr_ztO8EwA4kz2C2LDT:bgjc5qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/make_convex_hull_mesh.cc#L152)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, at first, I wonder whether `id_to_mesh_index` is an identity map.  Then, I read that [QhullVertexList](http://www.qhull.org/html/qh-code.htm#TOC) is a linked list, so I imagine the order of entries in the linked list does not necessarily follow the `QhullVertex::id()`.

Please feel free to edit or remove my addition.
</blockquote></details>

I'm not entirely sure what you're clarifying. While what you're saying is factual, it's not clear to me that it's helpful.

All that really matters is that the ids used by the vertices are the same ids used by the facets. Furthermore, the comment distinguishes between "indices" and "ids" and Drake has a deep pattern for contrasting those two concepts.
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 229 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrHVzbqCIdm4KcypvCH:-Nra0C0rDZIQiP1TrSKD:b-z4k2ts) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2a8cdd073b1547fa4697ab787b6e9beeadf67a4/geometry/proximity/test/make_convex_hull_mesh_test.cc#L229)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, is this leftover from debugging?  I don't see how it's related to `MakeConvexHull()`.
</blockquote></details>

You're 100% correct.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm_strong: beautiful! A few minor comments.

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrbV_qJ3zn7KHAHZ-qC:b-6lzfo2)* status: 8 unresolved discussions, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 141 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbL8pCBJmtqGBFTzUB:-NrbL8pD7sxcISYhXddS:b-7six5d) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/make_convex_hull_mesh.cc#L141)):*
> ```cpp
>   // This is a cheat that relies on the fact that a vector of Vector3d really
>   // is just a vector<double> with three times as many entries. It *does*
>   // eliminate a copy.
> ```

nit: add a static_assert that `sizeof(Vector3d) == 3 * sizeof(double)` to guard against aggressive padding (it isn't unheard of to round up 3-vectors to use 4 doubles to get better alignment) 
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 154 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbMjYbDE3YNM2nolKN:-NrbMjYbDE3YNM2nolKO:brmk5jq) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/make_convex_hull_mesh.cc#L154)):*
> ```cpp
> 
>   // A mapping from qhull vertex ids to indices in the final mesh (vertices_M).
>   std::map<countT, int> id_to_mesh_index;
> ```

BTW `countT`? Where did that come from? It's not in `orgQhull::` and I don't see a definition anywhere. Consider a clarifying comment.
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 64 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbPD-w9-JNnGsio_iZ:-NrbPD-w9-JNnGsio_i_:bmoiqyg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L64)):*
> ```cpp
>                 const Vector3d& vb = mesh.vertex(b);
>                 return std::lexicographical_compare(va.data(), va.data() + 3,
>                                                     vb.data(), vb.data() + 3);
> ```

BTW cool!
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbQqiu-hzqGYQL1-_O:-NrbQqiu-hzqGYQL1-_P:bg3inav) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L92)):*
> ```cpp
>       // Rotate the face so the first vertex has lowest index.
>       auto min_iter = std::min_element(canon_face.begin(), canon_face.end());
>       std::rotate(canon_face.begin(), min_iter, canon_face.end());
> ```

BTW  C++20 FTW!
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 113 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbSILMAysmcEy8X9W6:-NrbSILMAysmcEy8X9W7:b-286wpy) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L113)):*
> ```cpp
>                          const CanonicalMesh& expected, double tolerance) {
>   ASSERT_THAT(dut.vertices(),
>               testing::Pointwise(NearVertex(tolerance), expected.vertices()));
> ```

BTW that's some gtest wizardry! Consider a short comment explaining the magic being performed. I had to wade through gtest docs to understand this.
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 156 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbTV919DaymSktdEIm:-NrbTV919DaymSktdEIn:b-ayz2gn) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L156)):*
> ```cpp
>                   Vertex indices  */
>   const vector<Vector3d> canon_vertices{v0, v3, v2, v1};
>   const vector<Vector3d> perturbed_vertices{v1, v2, v3, v0};
> ```

minor: I can't make the perturbed_vertices order match the table above. Please clarify how 1230 is the right order. Is it 3012 but then rotated?

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012)* status: 8 unresolved discussions, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks. Comments addressed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrfIt3r7FQojfIxofgR:b-b4igux)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 52 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-Nrayl3y0aWRAgYjeGqr:-NrfH8SN7d5rXYCDio2G:bmmrt9q) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/make_convex_hull_mesh.cc#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could this be stricter: `vertices.size() >= v_indices.size()`?
</blockquote></details>

Done

Actually, I opted to remove this. What really matters is that the polygon's vertex indices are valid. That's a more convoluted test, so I've simply moved it to be a prerequisite.
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 69 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrazkUU5h7vqQIuvhB6:-NrfHPei2mLGz-BOHQpd:b-uhcgpi) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/make_convex_hull_mesh.cc#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: I suspect the `dot(n)` after the cross product is unnecessary. IIUC v_C0 and v_CI already lie in the plane whose normal is n, so their cross product should be entirely in the direction of n already. Is there some reason to believe otherwise here?
</blockquote></details>

Actually, you need to examine your dimensionality. It's absolutely necessary because we're storing a scalar and not a vector.

Your point is *exactly* correct. The cross product *does* lie in the direction of the normal (or, at least, *should*). We're simply using the normal to compute vector magnitude without a square root.
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbQqiu-hzqGYQL1-_O:-NrfI9adAWciD7TXMyyn:b-4y7q1x) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW  C++20 FTW!
</blockquote></details>

Amen to that!
___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 156 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-NrbTV919DaymSktdEIm:-NrfIm4_DuMrXvYmLYTH:btzrxvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb63a2c42a310f0e49f0050911ef3a3bf3bc0413/geometry/proximity/test/make_convex_hull_mesh_test.cc#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I can't make the perturbed_vertices order match the table above. Please clarify how 1230 is the right order. Is it 3012 but then rotated?
</blockquote></details>

I've changed the table label. Let me know if that's sufficient.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Oops...I was sloppy about my two machines and I ended up making changes based on R2 instead of R3. The difference between R2 and R5 should now represent what I'd intended this morning.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012#-:-NrfXR5p-5BAIdTpzoZt:bl8mrbb)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21012)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Pull request merged**
