### PR TITLE
solvers.py: Add vectorized version of EvalBinding (for python)

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHDu7Bl6bBIfiV_7gY3:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  +@ericcousineau-tri for platform review please, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHDv4gk5vfsdAE_FUyc:b-v2hixp)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 931 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHDuwYY2EpTQzNmqvzG:-MHDuwYY2EpTQzNmqvzH:blufybn) ([raw file](https://github.com/robotlocomotion/drake/blob/f48d28cebcede1830e7ce28d2bbaa46c81fc2e78/bindings/pydrake/solvers/mathematicalprogram_py.cc#L931)):*
> ```cpp
>           "EvalBindingAtMultipleValues",
>           [](const MathematicalProgram& prog,
>               const Binding<EvaluatorBase>& binding,
> ```

nit, indentation is slightly off, consider run clang-format on these lines?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 931 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHDuwYY2EpTQzNmqvzG:-MHEATcb89Bol3eUhuil:bs5aagc) ([raw file](https://github.com/robotlocomotion/drake/blob/f48d28cebcede1830e7ce28d2bbaa46c81fc2e78/bindings/pydrake/solvers/mathematicalprogram_py.cc#L931)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, indentation is slightly off, consider run clang-format on these lines?
</blockquote></details>

i agree with you, but this *is* the result of clang-format..when I change them the linter complains...

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with design nits.

Won't block as I'm unsure of desired deadline.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHEY83v3mTPcbynH6aP:bsi0tl3)* status: 5 unresolved discussions (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEUQMS26syuEa3AIta:-MHEUQMS26syuEa3AItb:bctcv42) (no related file):*
nit If naming were to remain, I would prefer the more succinct suffix "*Vectorized" over "*AtMultipleValues", especially given the commit title.

(Feel free to dismiss)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEVGHR7wDWfxWDeogp:-MHEVGHR7wDWfxWDeogq:b-xci2qn) (no related file):*
nit Rather than have these vectorized overloads be explicitly named, my preference would be that it's an overload...

It would require a minor bit of finagling on the the `pybind` side (e.g. 5 lines), but something like this could make it feasible and unambiguous w.r.t. the existing overload:
```
.def("EvalBinding", WrapVectorOnly(&Class::EvalBinding), ...)
.def("EvalBinding", WrapVectorized<3>(&MathematicalProgram::EvalBinding), ...)
```

The only caveat is that if users were passing in `(N, 1)` or `(N, 1)` matrices as vectors, they would now get `(1,)`, but I think that would be workable?

I think this is OK to dismiss for now, but I can forsee this happening more, so we may want to make this generalized at some point.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEXUMf4UzVJA5Nqs-e:-MHEXUMf4UzVJA5Nqs-f:br3d7o5) (no related file):*
nit I'm not sure if I'm a huge fan of pure Python functionality skipping C++ and going straight to `pybind11`.

For example, multiplication for `RigidTransform` has its vectorized overload in C++.

Ideally, this API exists in C++ s.t. Python is a *really* thin wrapper.
Even more ideal (in conjunction with above) is that its an overload, assuming it doesn't create ambiguity in resolving the VectorXd vs. MatrixXd version.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEYVy8DqCXc2T0Jesn:-MHEYVy93cdrgF0TsYPj:bkmon2q) (no related file):*
BTW On a broader scope, I can see us running into issues where we confuse users over what "multiple values" indicates when going from Vectors to Matrices.

I believe in Drake we have columns indicating individual values, but in NumPy, Torch, etc., it might be that rows indicate individual values.
Is it at all worth considering revisiting this? (or has this conversation already been had?)

I ask because I remember getting confused in MATLAB (e.g. `ode45`) vs. Simulink values on what axis values vary on, and I see similar things happening here with multiply, transposes, etc.

---
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 933 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEV9245PYjDaDsgwOr:-MHEV9245PYjDaDsgwOs:bm2dg38) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6333bc244cae30654a588624d3f541103c3464/bindings/pydrake/solvers/mathematicalprogram_py.cc#L933)):*
> ```cpp
>               const Binding<EvaluatorBase>& binding,
>               const MatrixX<double>& prog_var_vals) {
>             MatrixX<double> Y(
> ```

nit Here and elsewhere:
Given that this is a unique entry point from Python to Eigen matrices, we should do size-checking here so that errors appear in Release mode, not just Debug mode, for users.

e.g. `DRAKE_DEMAND(prog_var_vals.rows() == binding.num_variables())`

(I don't mind if the negative tests for badly-shaped inputs are missing for now)
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 941 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEUVpq0Jein2-0B0Fi:-MHEUVpq0Jein2-0B0Fj:b-n9d1vi) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6333bc244cae30654a588624d3f541103c3464/bindings/pydrake/solvers/mathematicalprogram_py.cc#L941)):*
> ```cpp
>           },
>           py::arg("binding"), py::arg("prog_var_vals"),
>           R""(A "vectorized" version of EvalBinding.  It evaluates the binding 
> ```

nit Here and below, should be three quotes, not two: `R"""( ... )"""`:
https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

(Feel free to dismiss)

**Comment by RussTedrake** [comment]
I would rather get it right than rush it in.  @hongkai-dai and I thought `AtMultipleValues` was more clear.  @hongkai-dai -- what do you think about the `Vectorized` proposal?

I actually think having a separate method might be better than overloading a single method, on principle.  (I actually tried the single overload first, but my version changed the return type from VectorX to MatrixX, and therefore changed some details about the numpy object that was returned.

Apart from the name, I think all of the other changes you propose could be done easily without breaking this API, if it goes in as proposed (e.g. we could easily push down to C++), and if we did want to have EvalBindings serve both roles, that would be a simple deprecation.

Will leave it open tonight in case anyone else wants to weigh in.

**Review by hongkai-dai — COMMENTED** [review]
I also like a separate method rather than an overload. In my mind, `EvalBinding` evaluates the binding at a single `x`, while `EvalBindingAtMultipleValues` evaluates at multiple `x`s. They have different behaviors, and I think that warrants a separate method. This method could be in C++ or python. I don't see we need it immediately in C++. If later we find it useful in C++, we could always add the method to the C++ class and change the python function to a binding to the C++ function.

I am a little hesitant to name it `Vectorized`. Especially we haven't really vectorized the python code (we still have a for loop in the python code), in my opinion a vectorized code means getting rid of the for loop.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHEkiKr4oX5U61NVe6d:b-jkvvxu)* status: 5 unresolved discussions (waiting on @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
In my mind, `vectorize` is a well-known term in NumPy:
https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html

It's also present in `pybind11`, via `py::vectorize`:
https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#vectorizing-functions

In the case of `pybind11` and NumPy, "vectorizing" doesn't mean that it's using a more advanced instruction set, but rather that the for-loop is in a faster language (C / C++).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHGfi6m8Yw0zdEo8-No:b-o6w7o8)* status: 5 unresolved discussions (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEVGHR7wDWfxWDeogp:-MHGs5vD34SMZB86kl-d:bxy3507) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than have these vectorized overloads be explicitly named, my preference would be that it's an overload...

It would require a minor bit of finagling on the the `pybind` side (e.g. 5 lines), but something like this could make it feasible and unambiguous w.r.t. the existing overload:
```
.def("EvalBinding", WrapVectorOnly(&Class::EvalBinding), ...)
.def("EvalBinding", WrapVectorized<3>(&MathematicalProgram::EvalBinding), ...)
```

The only caveat is that if users were passing in `(N, 1)` or `(N, 1)` matrices as vectors, they would now get `(1,)`, but I think that would be workable?

I think this is OK to dismiss for now, but I can forsee this happening more, so we may want to make this generalized at some point.
</blockquote></details>

Discussed above.

---

**Review by RussTedrake — COMMENTED** [review]
I'm ok with either name.  @hongkai-dai  -- I consider you the owner of MP.  I will defer to your decision.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHGtjmf2lW_j113Gcub:b-4gjbvq)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEXUMf4UzVJA5Nqs-e:-MHGsBuT8Qxj_tsJ9VH9:b-gvqt1u) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I'm not sure if I'm a huge fan of pure Python functionality skipping C++ and going straight to `pybind11`.

For example, multiplication for `RigidTransform` has its vectorized overload in C++.

Ideally, this API exists in C++ s.t. Python is a *really* thin wrapper.
Even more ideal (in conjunction with above) is that its an overload, assuming it doesn't create ambiguity in resolving the VectorXd vs. MatrixXd version.
</blockquote></details>

I think we agree that it's easy to push to c++ if / when we need/want it..  (hongkai and I are both uncertain that we need/want it there).  But agree that we want to decide if this is to become a pattern.  

ftr -- we have plenty of other instances of features that exist in python, but not in c++.  drawing, meshcat, ...  and other places where c++ methods are exposed with a more python-friendly interface.  I don't see this as a major deviation from that.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEYVy8DqCXc2T0Jesn:-MHGscRzE52y-ibAgOxq:b-s3q6hf) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW On a broader scope, I can see us running into issues where we confuse users over what "multiple values" indicates when going from Vectors to Matrices.

I believe in Drake we have columns indicating individual values, but in NumPy, Torch, etc., it might be that rows indicate individual values.
Is it at all worth considering revisiting this? (or has this conversation already been had?)

I ask because I remember getting confused in MATLAB (e.g. `ode45`) vs. Simulink values on what axis values vary on, and I see similar things happening here with multiply, transposes, etc.
</blockquote></details>

Agreed, this comment is out of scope.

---
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 933 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEV9245PYjDaDsgwOr:-MHGtAne6yU3K-egk9RM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6333bc244cae30654a588624d3f541103c3464/bindings/pydrake/solvers/mathematicalprogram_py.cc#L933)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Here and elsewhere:
Given that this is a unique entry point from Python to Eigen matrices, we should do size-checking here so that errors appear in Release mode, not just Debug mode, for users.

e.g. `DRAKE_DEMAND(prog_var_vals.rows() == binding.num_variables())`

(I don't mind if the negative tests for badly-shaped inputs are missing for now)
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 941 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEUVpq0Jein2-0B0Fi:-MHGtBcNDiQlEDOpgDO7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6333bc244cae30654a588624d3f541103c3464/bindings/pydrake/solvers/mathematicalprogram_py.cc#L941)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Here and below, should be three quotes, not two: `R"""( ... )"""`:
https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

(Feel free to dismiss)
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: 1 unresolved discussion (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEXUMf4UzVJA5Nqs-e:-MHH-Wjb76CHolbJLxAh:b-9jcvh1) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think we agree that it's easy to push to c++ if / when we need/want it..  (hongkai and I are both uncertain that we need/want it there).  But agree that we want to decide if this is to become a pattern.  

ftr -- we have plenty of other instances of features that exist in python, but not in c++.  drawing, meshcat, ...  and other places where c++ methods are exposed with a more python-friendly interface.  I don't see this as a major deviation from that.
</blockquote></details>

OK For things that are Python only, yes, those make sense. However, for things that area easily expressible in C++, I'm not sure if I would bin this strictly there, given other "vectorizations" (e.g. multiplication for RigidTransform).

But yeah, marking myself satisfied.

---
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 359 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHH-kpD12Bei0WPYgNG:-MHH-kpEETJIPU5IdZP4:b-jnci1a) ([raw file](https://github.com/robotlocomotion/drake/blob/3a9140ce9917bed9fb14f96c37f5cb284d854092/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L359)):*
> ```Python
>             value = prog.EvalBinding(constraint, x_expected)
>             self.assertTrue(np.allclose(value, value_expected))
>             print(np.vstack((x_expected, x_expected)).T.shape)
> ```

nit Unclear debugging statements.

Should these be removed?

**Review by hongkai-dai — COMMENTED** [review]
Thanks Eric with the explanation. I am convinced that we should use `vectorized` as the name.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHHDwYkBpW5sOQwAnAY:bp6ofg7)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: 2 unresolved discussions (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEUQMS26syuEa3AIta:-MHHJk5vEyDG8uaQ9Yki:b-i2wlli) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit If naming were to remain, I would prefer the more succinct suffix "*Vectorized" over "*AtMultipleValues", especially given the commit title.

(Feel free to dismiss)
</blockquote></details>

Promoting back to blocking given Hongkai's comment.

---

**Review by RussTedrake — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064#-:-MHHRrRMC7D6Iydwo0fM:b-896fix)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHEUQMS26syuEa3AIta:-MHHOvYc0NkfU1OuhW04:bb6un1j) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Promoting back to blocking given Hongkai's comment.
</blockquote></details>

Done

---
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 359 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14064#-MHH-kpD12Bei0WPYgNG:-MHHP-sp6GO05DCIC0ZA:b18kiia) ([raw file](https://github.com/robotlocomotion/drake/blob/3a9140ce9917bed9fb14f96c37f5cb284d854092/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L359)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear debugging statements.

Should these be removed?
</blockquote></details>

Done.  (must have forgotten to push)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14064)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai

**Pull request merged**
