### PR TITLE
Clean up shebangs, Update lint to run under Python3

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For #8352
Towards #9614 

Requires:
- [x] https://github.com/RobotLocomotion/styleguide/pull/13

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9615)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
___
*[tools/lint/formatter.py, line 72 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9615#-LPS6ep331Np9yYjstCq:-LPS6ep44c-R1Cd0F0wc:b-vp9xuh) ([raw file](https://github.com/robotlocomotion/drake/blob/fe7355a9f10b41083fea5064cc3d27bc8c4afd7c/tools/lint/formatter.py#L72)):*
> ```Python
>             assert line.endswith("\n"), line
>         for line in self._working_lines:
>             assert isinstance(line, (str, unicode)), (type(line), line)
> ```

Self-fix: Replace `(str, unicode)` with `unicode`

**Comment by EricCousineau-TRI** [comment]
___
*[common/test/cpplint_wrapper.py, line 1 at r7](https://reviewable.io/reviews/robotlocomotion/drake/9615#-LPSIKvG7cBKe_21USgQ:-LPTOJOY1ZXmeMs9oxbl:b5gm806) ([raw file](https://github.com/robotlocomotion/drake/blob/d2a20870979d1991754528b18c20c2ba9130167a/common/test/cpplint_wrapper.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's my impression that some developers might still run this by hand.  Please ask on slack especially for HQ folks, before removing this line.

(Alternatively, I'm not sure that we need to remove this line?)
</blockquote></details>

I'm fine with leaving it here, since it doesn't have any dependencies, though it feels odd to have the shebang there when Bazel in fact runs it with its own version.
(Trying to force Bazel to use the shebang version seems like a fruitless endeavor to me, at least.)

Are we OK with having a shebang that may potentially mislead people on what version of Python will be executing this code?
(If so, then cool, but I would like to at least comment here stating something to that effect.)

**Comment by jwnimmer-tri** [comment]
I'll look into resolving my final discussion this morning -- need to investigate.  Also FYI there are both merge conflicts and CI errors now.

**Comment by jwnimmer-tri** [comment]
You forgot to test on macOS.  I guess we'll roll the dice.

**Pull request merged**
