### PR TITLE
Revert "Modifies multilane's Loader tests using gmock. (#8071)"

### PR DESCRIPTION
**Pull request by thduynguyen**
This reverts commit 7f2a6bbcc9f0c88e7621bcbd4e5070cba318dc41.

@jwnimmer-tri for platform review please!

Dear @agalbachicar,

The on-call build cop, @thduynguyen, believes that your PR #8071 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan/239/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan/240/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan/241/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8555)

### CODE REVIEW

**Comment by agalbachicar** [comment]
Truth is it is not that simple for me to solve it right now. Not sure how long it will take. Let me know if you prefer to move on with the revert PR.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8555#-:-L9g94WY8Nl7TYupB5R5:br1bje3)*

**Comment by agalbachicar** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8555#-:-L9gCIss3_xH2tZZ-IBH:bg7igk9)*

**Comment by thduynguyen** [comment]
@agalbachicar If that's the case that it would take a long time to resolve the problem, we will go ahead and revert your commit with this PR. This will give you less pressure on fixing the issues. Please submit another PR once the problem is fixed. Thanks.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8555#-:-L9gBTrg7CdYHpRm3XE6:bytrmqh)*

**Comment by agalbachicar** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8555)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform rubber-stamp.

For _newly added_ tests that fail only in _post-merge_ build configurations, another option is to tag the test `no_ubsan` until the problem is resolved, but to keep running it in all of the other build configurations.  I'll leave it to buildcop and author to choose whether thats better in this case.

**Comment by thduynguyen** [comment]
Thanks Jeremy! 
@agalbachicar if getting this into master is important to your work, please consider submit another PR without the failed test or tag it as `no_ubsan` as Jeremy suggested? Thanks!

---

Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8555#-:-L9gdfzI1VGCUxOdmsZU:b-fdo6ke)*

**Pull request merged**
