### PR TITLE
Revert "[geometry] Extend characterization framework, apply to point-pair penetration (2 of 4)"

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Reverts RobotLocomotion/drake#14795

 Dear @SeanCurtis-TRI ,

 The on-call build cop, Damrong Guoy, believes that your PR #14795 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:
:full_moon: [mac-big-sur-clang-bazel-continuous-release](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-big-sur-clang-bazel-continuous-release/)
:full_moon: [mac-catalina-clang-bazel-continuous-release](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-catalina-clang-bazel-continuous-release/)

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14819)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please
@drake-jenkins-bot mac-catalina-clang-bazel-continuous-release please

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please
@drake-jenkins-bot mac-catalina-clang-bazel-continuous-release please

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
See #14821 for the preferred fix forward.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14819#-:-MWbdc527zU6yB1qv8pA:b-o1yqh6)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Comment by SeanCurtis-TRI** [comment]
Closed in lieu of #14821.

**Pull request closed without merging**
