### PR TITLE
Support arbitrary geometric continuity order for GcsTrajectoryOptimization

### PR DESCRIPTION
**Pull request by sadraddini**
It was mentioned in the documentation of `GcsTrajectoryOptimization` that it supports arbitrary degrees of path continuity whereas it did not. This PR adds the constraints for arbitrary geometric continuity order at the transitions between Gcs regions.

Some results on the `SimpleEnv2D` unittest (_the script for generation of the images is not included in the PR_):
  

**Note about Toppra notes** the documentation stated that "The resulting trajectories can be post-processed with e.g. Toppra in order to smooth out the timing rescaling.".  We found that this is very nuanced. Toppra does **not** know about the piecewise nature of its trajectory. Therefore, the output can be a timed trajectory that violates the dynamic limits by arbitrary wide margins.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20243)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review

I've added a quick question on the API to discuss before we do the full review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20243#-:-Nf1RkLE6DlJMlAeOmb1:b-ir9uh2)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sadraddini)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20243#-Nf1RCmQ6_UDBNtBIli9:-Nf1RCmQ6_UDBNtBIliA:bolf9b7) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e1ca989a4121e72a9b0a04dc7f0caf943094311/planning/trajectory_optimization/gcs_trajectory_optimization.h#L293)):*
> ```objc
>       const std::vector<std::pair<int, int>>& edges_between_regions, int order,
>       double h_min = 0, double h_max = 20, int geometric_continuity_order = 0,
>       std::string name = "");
> ```

Adding it here would be an API-breaking change.  If we add it as the last argument, it would not be breaking.

Alternatively, I wondered if we should add it as an additional method on Subgraph.  E.g. leave this entry point alone, and instead say `AddDerivativeContinuityConstraints` ... 

Presumably you'll also want to add these to the edges between subgraphs?

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20243)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sadraddini)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20243#-Nf1RCmQ6_UDBNtBIli9:-Nf2Dtv2CxPuAYfC5mqJ:bodgezs) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e1ca989a4121e72a9b0a04dc7f0caf943094311/planning/trajectory_optimization/gcs_trajectory_optimization.h#L293)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Adding it here would be an API-breaking change.  If we add it as the last argument, it would not be breaking.

Alternatively, I wondered if we should add it as an additional method on Subgraph.  E.g. leave this entry point alone, and instead say `AddDerivativeContinuityConstraints` ... 

Presumably you'll also want to add these to the edges between subgraphs?
</blockquote></details>

Took it to the last argument. I acknowledge that it would have been API-breaking. I thought it is cleaner to have it there. 

Right now, the constraints are added within the subgraph, and also between subgraph1 and subgraph 2, where the order becomes the minimum of two. 

 About `AddDerivativeContinuityConstraints`:
I'm not fully against it. I feel it is a bit work on the user side to carefully add them for each subgraph they introduce and then also do it for between those subgraphs.

**Comment by RussTedrake** [comment]
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20243#-Nf1RCmQ6_UDBNtBIli9:-NfCsh_g2zAkVmfaR-I0:bm8x2hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e1ca989a4121e72a9b0a04dc7f0caf943094311/planning/trajectory_optimization/gcs_trajectory_optimization.h#L293)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Took it to the last argument. I acknowledge that it would have been API-breaking. I thought it is cleaner to have it there. 

Right now, the constraints are added within the subgraph, and also between subgraph1 and subgraph 2, where the order becomes the minimum of two. 

 About `AddDerivativeContinuityConstraints`:
I'm not fully against it. I feel it is a bit work on the user side to carefully add them for each subgraph they introduce and then also do it for between those subgraphs.
</blockquote></details>

Take a look at AddTimeCost on the main GcsTrajectoryOptimization class.
https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#a515805314ae145e3be6b636d0986bb09

In this case, the user calls it once, and it gets applied everywhere.  So that would actually be even less of a burden on the user than having to list it on every call to AddRegions.  I feel like that would be the better api here?

**Comment by sadraddini** [comment]
> _[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20243#-Nf1RCmQ6_UDBNtBIli9:-NfCsh_g2zAkVmfaR-I0:bm8x2hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e1ca989a4121e72a9b0a04dc7f0caf943094311/planning/trajectory_optimization/gcs_trajectory_optimization.h#L293)):_
> Previously, sadraddini (Sadra Sadraddini) wrote…
> 
> Take a look at AddTimeCost on the main GcsTrajectoryOptimization class. https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#a515805314ae145e3be6b636d0986bb09
> 
> In this case, the user calls it once, and it gets applied everywhere. So that would actually be even less of a burden on the user than having to list it on every call to AddRegions. I feel like that would be the better api here?

I like the idea. Wait until I implement it.

**Comment by RussTedrake** [comment]
As discussed, this functionality is being implemented instead in #20441.

**Pull request closed without merging**
