### PR TITLE
doc: Refactor Doxygen builds to use common code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14803. (That PR contains more example uses of the `defs.py` common helpers, as well as new `drake/doc/_pages/documentation_instructions.md` that show the overall UX goal.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri could I lean on you for feature review on this one, at least for the code review piece?  (This also needs local testing as part of feature review, but we can assign that separately if you like.)  Dynamics team is a heavy user of Doxygen previews but perhaps less of the team is well-familiarized with Python code like this.  This can wait until your Tuesday reviews day if you like.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYLCktwBvHEqm-1NJVv:-MYLCktx92yIcy2X5apy:b-z83mv4) (no related file):*
Nothing more fun nor potentially error prone than Python refactoring :)

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 6 of 13 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYM2RIODwaPRoUJcdee:-MYM2RIODwaPRoUJcdef:bcar57f) (no related file):*
Placeholder discussion for manual testing.

---
___
*[doc/doxygen_cxx/build.py, line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYLzvIEEv--HgrMcYfX:-MYLzvIEEv--HgrMcYfY:b5i16yj) ([raw file](https://github.com/robotlocomotion/drake/blob/de024be601ebd6531ecea565f6891e782aa07350/doc/doxygen_cxx/build.py#L27)):*
> ```Python
>         "bazel-*",      # Ignore Bazel build artifacts.
>         "build",        # Ignore CMake build artifacts.
>         "cmake",        # There no C++ code here.
> ```

typo: s/There no/There is no/
___
*[doc/doxygen_cxx/build.py, line 90 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYM0K1nBbesYP5OsekD:-MYM0K1nBbesYP5OsekE:bj2pcw1) ([raw file](https://github.com/robotlocomotion/drake/blob/de024be601ebd6531ecea565f6891e782aa07350/doc/doxygen_cxx/build.py#L90)):*
> ```Python
>         definitions["DOXYGEN_DOT_EXECUTABLE"] = ""
> 
>     check_call([
> ```

BTW, do we need to justify continuing to `subprocess` to `cmake_configure_file`, having deleted the "integrate as a library" TODO?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
FYI @seancurtis-tri  -- you want to supplement my testing of user previews? I didn't push things very hard.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834#-:-MYMP75V96qoWfraBt5D:b-2ic2t4)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYM2RIODwaPRoUJcdee:-MYMP2tE26odKoB5tJri:b2ni9bh) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Placeholder discussion for manual testing.
</blockquote></details>

ok.

---

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI will have platform review (on Monday).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[doc/doxygen_cxx/build.py, line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYLzvIEEv--HgrMcYfX:-MYMQF0J2t1McfmLyl3y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de024be601ebd6531ecea565f6891e782aa07350/doc/doxygen_cxx/build.py#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo: s/There no/There is no/
</blockquote></details>

Done.
___
*[doc/doxygen_cxx/build.py, line 90 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYM0K1nBbesYP5OsekD:-MYMQJQFDPLEUU43A5HV:bwc1163) ([raw file](https://github.com/robotlocomotion/drake/blob/de024be601ebd6531ecea565f6891e782aa07350/doc/doxygen_cxx/build.py#L90)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, do we need to justify continuing to `subprocess` to `cmake_configure_file`, having deleted the "integrate as a library" TODO?
</blockquote></details>

Meh.  I took the TODO as a general complaint about BUILD integration and implicit dependency, rather than the process boundary being some acute problem.  Using the same API as everyone else who calls this helper (i.e., a process boundary) is probably the most durable solution.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 11 files at r1, 5 of 13 files at r3, 5 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834#-:-MYedFczDcmPosgDZf6p:bmxilld)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[doc/defs.py, line 195 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeXu3BAz4jeUYoUTYj:-MYeXu3BAz4jeUYoUTYk:b-qdp4vb) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/defs.py#L195)):*
> ```Python
>             help="Limit the generated documentation to only these modules and "
>             "their children.  When none are provided, all will be generated. "
>             "Either . or / may be used as a submodule delimiter. "
> ```

I'm not sure how to interpret this.

------------------------------------------------------

I'm revisiting this comment. I'm leaving the initial comment to underscore that it left me simply confused. However, after reading through the implementation, I was able to recognize that you meant one could type `drake.math` or `drake/math` as a way to specify a module. I think there are defects in the note precluding this interpretation:

1. There's a change in language from "module" in the first sentence and "submodule" in this. However, in retrospect, I believe there is no meaningful distinction in what they are actually referencing.
2. The delimiter isn't of modules/submodules, it's the delimiter of the *path* to a submodule. The delimiter of modules is simply white space.
3. There's no hint that all paths must start with `drake`.

Of those three items:

1. This should *definitely* be addressed here.
2. This should *probably* be addressed here.
3. This doesn't necessarily need to be addressed here. As a long term user of this functionality, I was tripped up by this new requirement. However, between the implicit example in the documentation and the error message I was quickly able to infer the requirement and it is unlikely that a user would trip over that multiple times. So, I'm open to the argument that the current state is good enough in this regard, but also, perhaps, it would be good to be explicit in the linked documentation.
___
*[doc/doxygen_cxx/BUILD.bazel, line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYecqL42dLocCF2oJVw:-MYecqL42dLocCF2oJVx:b-64xnfh) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/doxygen_cxx/BUILD.bazel#L14)):*
> ```Starlark
>     "//doc:defs.bzl",
>     "DEFAULT_TEST_TAGS",
>     "enumerate_filegroup",
> ```

BTW I know this predates this PR and so I'm merely using the opportunity where this goes from *one* usage to *three* usages to express a fleeting opinion. It wasn't obvious to me that this generated a new file. I'd have hoped for a name that was more "generate-y". That's all, continue about your lives, citizens.
___
*[doc/doxygen_cxx/BUILD.bazel, line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeYkM2Dr8Vrmu_3N_D:-MYeYkM2Dr8Vrmu_3N_E:b-467djf) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/doxygen_cxx/BUILD.bazel#L43)):*
> ```Starlark
>     ],
>     tags = [
>         # Don't re-lint system_doxygen.py.
> ```

BTW Perhaps a further note on why it's necessary to list here rather than simply being a declared dependency on whatever depends on `doxygen_input`? The redundancy is exceptional enough that it would benefit from capturing the design decision.

**Comment by jwnimmer-tri** [comment]
___
*[doc/doxygen_cxx/BUILD.bazel, line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeYkM2Dr8Vrmu_3N_D:-MYfQ3F66cPEVA4yZEzS:b-sht8e7) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/doxygen_cxx/BUILD.bazel#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Perhaps a further note on why it's necessary to list here rather than simply being a declared dependency on whatever depends on `doxygen_input`? The redundancy is exceptional enough that it would benefit from capturing the design decision.
</blockquote></details>

We list it here because it is used by the Doxygen program itself, in contrast to something like `cmake_configure_file` which is used only by `build.py` and not ever by the Doxygen program.

Can you help me out with any suggested comments in this file to help clarify this?  Perhaps the scope of "doxygen_input" is not immediately clear -- that it must be exactly the files used by Doxygen while running, maybe?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: 2 unresolved discussions (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[doc/defs.py, line 195 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeXu3BAz4jeUYoUTYj:-MYfSZg47QCbFYKTDRlm:bo5zpby) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/defs.py#L195)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm not sure how to interpret this.

------------------------------------------------------

I'm revisiting this comment. I'm leaving the initial comment to underscore that it left me simply confused. However, after reading through the implementation, I was able to recognize that you meant one could type `drake.math` or `drake/math` as a way to specify a module. I think there are defects in the note precluding this interpretation:

1. There's a change in language from "module" in the first sentence and "submodule" in this. However, in retrospect, I believe there is no meaningful distinction in what they are actually referencing.
2. The delimiter isn't of modules/submodules, it's the delimiter of the *path* to a submodule. The delimiter of modules is simply white space.
3. There's no hint that all paths must start with `drake`.

Of those three items:

1. This should *definitely* be addressed here.
2. This should *probably* be addressed here.
3. This doesn't necessarily need to be addressed here. As a long term user of this functionality, I was tripped up by this new requirement. However, between the implicit example in the documentation and the error message I was quickly able to infer the requirement and it is unlikely that a user would trip over that multiple times. So, I'm open to the argument that the current state is good enough in this regard, but also, perhaps, it would be good to be explicit in the linked documentation.
</blockquote></details>

Done.

Since the program's overall help already displays the instructions' URL, I've omitted it from `--quick`'s details here.

I reworded the detailed help to address (1..3), I hope.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/BUILD.bazel, line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeYkM2Dr8Vrmu_3N_D:-MYfdqmv3eSu70AsgJ7_:b-1uvy4c) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/doxygen_cxx/BUILD.bazel#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We list it here because it is used by the Doxygen program itself, in contrast to something like `cmake_configure_file` which is used only by `build.py` and not ever by the Doxygen program.

Can you help me out with any suggested comments in this file to help clarify this?  Perhaps the scope of "doxygen_input" is not immediately clear -- that it must be exactly the files used by Doxygen while running, maybe?
</blockquote></details>

It's solely attributable to my build ignorance. It was a pattern I hadn't encountered before and the reason for it wasn't apparent to me upon inspection.

What I inferred is that we set up one build target (`system_doxygen`) for the express purpose of linting that file. And then we put it in a filegroup so some other build target would get access to the file. Why doesn't that *other* thing simply declare its dependency on *this* file group and the `system_doxygen` target?

(Note: this description of my mental state has been quickly recreated and is not guaranteed to be what I actually thought at the time.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[doc/doxygen_cxx/BUILD.bazel, line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14834#-MYeYkM2Dr8Vrmu_3N_D:-MYfjPYzEjXGt6yBKQW-:bikrqk) ([raw file](https://github.com/robotlocomotion/drake/blob/79ae05487a510a3e6378f4b0df2bce55468472ed/doc/doxygen_cxx/BUILD.bazel#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Part of the difficulty here is that the code in `system_doxygen.py` functions as both a library and a main program.  Doxygen uses it as a main program.  The library rule and its unit test induce the linting.  I will see what I can do to clarify all of this.
</blockquote></details>

Done, to some degree.  I think the best answer will probably be to refactor the Python file so its users can be more clear, but I don't plan to tackle that yet.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14834)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
