### PR TITLE
Update Docker `drake-distro` to `drake`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Depends on the outcome of https://github.com/RobotLocomotion/drake/issues/7654

\cc @jwnimmer-tri 
\cc @peteflorence (added in mention of Spartan and Underactuated)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7998)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-:-L4nfTM8EXzWEV5mnHMM:b-drds6b)*

**Comment by jamiesnape** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-L4pp7tiE3C2Ekwb6yIw:-L4pp7tjwrAwtH4aFy-c:bfu75xf) ([raw file](https://github.com/robotlocomotion/drake/blob/f45d914bffa5d123d50bb22e0f8d547612b651b0/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L14)):*
> ```Shell
> 
> apt update
> apt install wget  # We want the recommended packages to allow validation of the key below.
> ```

If need one (or more) of the recommended packages, please install it (them) explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/docker.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-L4qYf4easGfhPqq-KC0:-L4qYf4easGfhPqq-KC1:bka19wr) ([raw file](https://github.com/robotlocomotion/drake/blob/f45d914bffa5d123d50bb22e0f8d547612b651b0/doc/docker.rst#L227)):*
> ```reStructuredText
> * `docker cp <https://docs.docker.com/engine/reference/commandline/cp/>`_ can
>   be used to copy files into and out of a running image.
> * `-v <https://docs.docker.com/engine/tutorials/dockervolumes/#locate-a-volume>`_
> ```

FYI, this link is outdated. Please use https://docs.docker.com/storage/volumes/#choose-the--v-or-mount-flag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998)*

**Comment by soonho-tri** [comment]
:lgtm: (pending discussions)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-:-L4rKr-06kadPZOzbD9y:b6aqkhs)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-L4pp7tiE3C2Ekwb6yIw:-L4ryMYZCt4M4BQU9hBJ:bhswoto) ([raw file](https://github.com/robotlocomotion/drake/blob/f45d914bffa5d123d50bb22e0f8d547612b651b0/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

If need one (or more) of the recommended packages, please install it (them) explicitly.
</blockquote></details>

(Since there is only one recommended package, I assume you need `ca-certificates`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/docker.rst, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-L4qYf4easGfhPqq-KC0:-L4s-USqsbj4LNPSVvSn:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/f45d914bffa5d123d50bb22e0f8d547612b651b0/doc/docker.rst#L227)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this link is outdated. Please use https://docs.docker.com/storage/volumes/#choose-the--v-or-mount-flag
</blockquote></details>

Done. Thanks for catching that!

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-L4pp7tiE3C2Ekwb6yIw:-L4s-Q07WAxHcLfAl7CW:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/f45d914bffa5d123d50bb22e0f8d547612b651b0/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

(Since there is only one recommended package, I assume you need `ca-certificates`.)
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7998#-:-L4sBGsmspRclJNcqQCG:bnfp4nl)*

**Pull request merged**
