### PR TITLE
Use row major Delassus operator in PGS solver

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
With the change in storage order, the average time spent on 100 PGS iterations for a sim with ~80 contact points reduces from ~1.3e-3 second to around ~1e-4 second, which is a ~13x improvement.

In addition, change the default number of iterations for PGS to 100.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-MckXscJ8uHooXjkCEDF:bwshpyi)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
This is a very nice improvement @xuchenhan-tri. Could you document in the PR's description what performance improvement you observe? at least for the problem sizes you tried. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-MctI6KfAV5wp7W64qsZ:b-hlopx8)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/contact_solvers/pgs_solver.h, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15223#-MctHOgOBewf5Ba6xoxH:-MctHOgOBewf5Ba6xoxI:bohft46) ([raw file](https://github.com/robotlocomotion/drake/blob/27726b257c165617145558676bcca851aad106ec/multibody/contact_solvers/pgs_solver.h#L97)):*
> ```objc
>     // The row major form of the Delassus operator used in the Gauss-Seidel
>     // iterations for better locality.
>     Eigen::SparseMatrix<T, Eigen::RowMajor> W_row_major;
> ```

question, do we really need a copy? The Delassus operator is symmetric. Could we just work with its transpose to improve memory access?

**Review by xuchenhan-tri — COMMENTED** [review]
Addressed the comment and documented the performance improvement in the PR description. PTAL, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-Mctxu0wENoXMIt_5rzl:bn8wp9o)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/pgs_solver.h, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15223#-MctHOgOBewf5Ba6xoxH:-MctgKZl60XKf10kZ0PF:b-skv9bd) ([raw file](https://github.com/robotlocomotion/drake/blob/27726b257c165617145558676bcca851aad106ec/multibody/contact_solvers/pgs_solver.h#L97)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

question, do we really need a copy? The Delassus operator is symmetric. Could we just work with its transpose to improve memory access?
</blockquote></details>

Ah, you are definitely right. Thanks for the reminder.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
This is an amazing fix, excellent. :lgtm_strong: 
+@sammy-tri for platform please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-MdT4tJB6B_o4YxJ2i4S:by9miey)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-MdTLvdO3uvaPR8ER7_R:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15223#-:-MdTM-UU-kBXmkyug_jo:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Comment by sherm1** [comment]
Wow, nice one @xuchenhan-tri !

**Pull request merged**
