### PR TITLE
[geometry,doc] Clarify RenderEngineVtk texture assignment

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #13179

Also fix a nearby formatting blunder.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 
+@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531#-:-MvKeGDf6Z5pvHKmUMdf:b6cqf2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531#-:-MvP3USc49vFAhkO0Khl:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/render/render_engine_vtk_factory.h, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16531#-MvP3Lkq7RDmznQBjAGt:-MvP3Lkq7RDmznQBjAGu:bxar1ei) ([raw file](https://github.com/robotlocomotion/drake/blob/00898e0970fe32d751b4285bcc0d7260f3f1960f/geometry/render/render_engine_vtk_factory.h#L59)):*
> ```objc
>  directive. Instead, it has two ways to associate a color texture with an obj
>  file:
>  - file name matching; see footnote 3 above.
> ```

nit: Capitalization of first words of these bullets. "file" -> "File"

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review, Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531#-:-MvPGh9GAyQ1g7Bhaex2:b2hrd0d)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @joemasterjohn and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531#-:-MvPMd8p6J-NoT8Ksiju:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform) (waiting on @rpoyner-tri)

___
*[geometry/render/render_engine_vtk_factory.h, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16531#-MvPM7Xm2IEn7jLiRngG:-MvPM7Xm2IEn7jLiRngH:b-x497pw) ([raw file](https://github.com/robotlocomotion/drake/blob/7b3c8e4776088912daf0399c2984b523177c5bcb/geometry/render/render_engine_vtk_factory.h#L61)):*
BTW, when I follow this link in doxygen, I got 

> SDFormat path: //model/link/visual/material/drake:diffuse_map
URDF path: N/A

If we support texture in URDF now, should this documentation be updated?
___
*[geometry/render/render_engine_vtk_factory.h, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16531#-MvPKkLD8lM9SS4c12Uj:-MvPKkLD8lM9SS4c12Uk:b-c6b5ko) ([raw file](https://github.com/robotlocomotion/drake/blob/7b3c8e4776088912daf0399c2984b523177c5bcb/geometry/render/render_engine_vtk_factory.h#L92)):*
> ```objc
>  
> ```

BTW, is this new blank line intentional?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[geometry/render/render_engine_vtk_factory.h, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16531#-MvPM7Xm2IEn7jLiRngG:-MvPNH821p4FyXJb377M:bquita7) ([raw file](https://github.com/robotlocomotion/drake/blob/7b3c8e4776088912daf0399c2984b523177c5bcb/geometry/render/render_engine_vtk_factory.h#L61)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, when I follow this link in doxygen, I got 

> SDFormat path: //model/link/visual/material/drake:diffuse_map
URDF path: N/A

If we support texture in URDF now, should this documentation be updated?
</blockquote></details>

We don't support it via drake:diffuse_map. That's why I said "In URDF, use `//visual/material/texture`".

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16531)* status: :shipit: complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform) (waiting on @rpoyner-tri)

___
*[geometry/render/render_engine_vtk_factory.h, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16531#-MvPM7Xm2IEn7jLiRngG:-MvPYknq2WohZxxEL-Cs:bn6yydc) ([raw file](https://github.com/robotlocomotion/drake/blob/7b3c8e4776088912daf0399c2984b523177c5bcb/geometry/render/render_engine_vtk_factory.h#L61)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

We don't support it via drake:diffuse_map. That's why I said "In URDF, use `//visual/material/texture`".
</blockquote></details>

OIC, thanks!

**Pull request merged**
