### PR TITLE
make kuka_plan_runner to ignore all plan msg that has fewer than 2 knots.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6497)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature. @sammy-tri for platform. 
the problem i observed is that an empty plan msg will be sent and crash plan_runner. 

i suspect state machine is modified to set out a empty dummy message every time it's done (because of the changes naveen made for the system version to work) in any case, i don't think this change should do any harm. 
@naveenoid please confirm. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KnufmAnM-JQ5vre82p0:blxzilc)*

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for platform

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KnujyaBRWPAm931UFiD:b-2etf7p)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KnukpKrNFcD2zudlJx9:bnfp4nl)*

**Comment by sammy-tri** [comment]
`RobotPlanInterpolator` (and thus `iiwa_controller`) has a slightly different behavior where sending an empty message causes the system to output the measured position at the time the empty plan is received continuously until a new plan is received (this is somewhat documented in its constructor).   `PickAndPlaceStateMachine` makes use of this behavior.

The patch below mimics this behavior if the previous plan has already reached its end, but not otherwise.  Is it worth copying the `RobotPlanInterpolator` behavior here?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KoIFNhefJQiQp66_lAI:bku68bp)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497)*

**Comment by sammy-tri** [comment]
I don't use `kuka_plan_runner` anymore...   and only `iiwa_controller` has been extended to support multiple arms (though there might still be some issues in this case, I need to debug an assertion in `LcmDrivenLoop` which is occasionally triggered in the multi-arm case a bit more).  `kuka_plan_runner` is simpler and still does it's think perfectly fine, so I haven't tried to deprecate it.

I don't think it's an artifact, it's a documented feature of how `RobotPlanInterpolator` handles certain constructions of `robot_plan_t` messages.  Admittedly, we could implement "stop at current position" with a two-knot plan containing identical knot points at the current measured positions...   and then `kuka_plan_runner` would handle that correctly.  Would you prefer that we go in this direction?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KoIIP84e1ao6OLwhiF1:b-bohw1z)*

**Comment by siyuanfeng-tri** [comment]
Good to know. 
I still think this quick fix is a reasonable thing to do regardless of whoever is sending the plans, and I don't think it's worth it to patch all the system stuff to play nice with this. I think this serves as an excellent starting point and a real example, so I don't want a mal formed lcm message to crash it. What do you think? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KoIJlGZe-Cv_O-0ETBZ:beg3fk8)*

**Comment by sammy-tri** [comment]
:lgtm: it's strictly better than the status quo implementation

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6497#-:-KoIOzNqFT0XX0ivnEKd:bfiyaqv)*

**Pull request merged**
