### PR TITLE
Add FixInputPort convenience overloads

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This ended up being using while developing #7560.

(This PR was extracted from #8862.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8877)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for all review, please. This is similar to what you saw in #8862, but limited to just the framework changes and reworked to have less comment changes and a tweak to the unit test to put over overload in its own nested block.

**Comment by jwnimmer-tri** [comment]
Update: I realized the same reasoning applies to AbstractValue, so I've also now updated `context_base.h` in the same way.

**Comment by sherm1** [comment]
Platform & feature :lgtm: with a couple of BTWs.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/context.h, line 258 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKPjt2B-IaFPEpJexH:-LDKPjt2B-IaFPEpJexI:b-dkybdk) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/context.h#L258)):*
> ```objc
>   /// Same as above method but the vector is passed by const reference instead
>   /// of by unique_ptr.
>   FixedInputPortValue& FixInputPort(int index, const BasicVector<T>& vec) {
> ```

BTW consider stating clearly that the port will contain a copy of the input argument rather than retaining a pointer to it. The "same as above method" comment might mislead a user into thinking that, like the above method, this one works directly with the supplied object.

---

*[systems/framework/context_base.h, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKQJyiDSGVU10-9CG3:-LDKQJyiDSGVU10-9CG4:b-dkybdk) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/context_base.h#L165)):*
> ```objc
>   /** Same as above method but the value is passed by const reference instead
>   of by unique_ptr. */
>   FixedInputPortValue& FixInputPort(int index, const AbstractValue& value) {
> ```

BTW consider stating clearly that the port will contain a copy of the input argument rather than retaining a pointer to it. The "same as above method" comment might mislead a user into thinking that, like the above method, this one works directly with the supplied object.

---

*[systems/framework/test/leaf_context_test.cc, line 312 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKQbmu3mobwbdSku8q:-LDKQbmu3mobwbdSku8r:bgbfdtv) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/test/leaf_context_test.cc#L312)):*
> ```cpp
> 
>   // N.B. The GetAbstractInput test case above already covers the FixInputPort
>   // overloads for AbstractValue.
> ```

BTW I don't think there is a unit test for the new AbstractValue signature.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8877#-:-LDKQjiC96s8NgLzSWJp:bsekgjq)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/framework/context.h, line 258 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKPjt2B-IaFPEpJexH:-LDKReG0AOoFPlsjjlAs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/context.h#L258)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider stating clearly that the port will contain a copy of the input argument rather than retaining a pointer to it. The "same as above method" comment might mislead a user into thinking that, like the above method, this one works directly with the supplied object.
</blockquote></details>

Done.

---

*[systems/framework/test/leaf_context_test.cc, line 312 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKQbmu3mobwbdSku8q:-LDKR1un8QRy6T5Diu_K:br2evia) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/test/leaf_context_test.cc#L312)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't think there is a unit test for the new AbstractValue signature.
</blockquote></details>

The change on line 273 does so, I think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8877)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/test/leaf_context_test.cc, line 312 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKQbmu3mobwbdSku8q:-LDKUeo97GhPLCIP5MHW:b-lcs0u) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/test/leaf_context_test.cc#L312)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The change on line 273 does so, I think?
</blockquote></details>

Yes it does -- sorry, I missed that. Did that replace the only test of the original unique_ptr signature or is there another one somewhere?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8877)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[systems/framework/test/leaf_context_test.cc, line 312 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8877#-LDKQbmu3mobwbdSku8q:-LDKVk1xBolrMAwfEjP2:bs2q8p8) ([raw file](https://github.com/robotlocomotion/drake/blob/1164e38fffbcc6a2bc917ec09b41a51f22e0511c/systems/framework/test/leaf_context_test.cc#L312)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Yes it does -- sorry, I missed that. Did that replace the only test of the original unique_ptr signature or is there another one somewhere?
</blockquote></details>

BTW I found one in fixed_input_port_value_test.cc:48.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8877)*

**Pull request merged**
