### PR TITLE
Add names to manipulation-related systems.

### PR DESCRIPTION
**Pull request by david-german-tri**
@siyuanfeng-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5837)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
:lgtm: thanks david! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5837#-:-Khi1Uthl8TxPQY_mc9a:b-bk36hh)*

**Comment by siyuanfeng-tri** [comment]
BTW, are you adding the viz to doxygen or something like that? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5837#-:-Khi1ahRjV1D7-gm9491:b-ilwwyf)*

**Comment by david-german-tri** [comment]
+@soonho-tri for platform review

> BTW, are you adding the viz to doxygen or something like that?
I'm failing to parse this question.  :confused:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5837#-:-Khi3UIwNhAXCf8WmkAt:bp3wfw)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 11 files at r1.
Review status: 1 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5837)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 10 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5837#-:-KhlP30GBozwbLxMTeau:bnfp4nl)*

**Pull request merged**
