### PR TITLE
Update Xenial setup script and instructions to support Bazel.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4441)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-:-KY_BfkKDTTIL_YoUAT_:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-KY_CJ5EUOK4uM52T_JD:-KY_CJ5FzMqiH5Axj2YY:b-sjnr7f) ([raw file](https://github.com/robotlocomotion/drake/blob/bf356ba5c964adfcf5152a9aaf402ead164d3ba0/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
> ```Shell
> 
> # Install the APT dependencies.
> # TODO(david-german-tri): Can we remove libvtk-java?
> ```

BTW This TODO is perhaps slightly misplaced now?  I refers to the EOF-list below, I think.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-KY_CoUjoVH3_LaxHDQB:-KY_CoUjoVH3_LaxHDQC:b-6j2ovs) ([raw file](https://github.com/robotlocomotion/drake/blob/bf356ba5c964adfcf5152a9aaf402ead164d3ba0/setup/ubuntu/16.04/install_prereqs.sh#L112)):*
> ```Shell
> 
> # Install Bazel.
> wget -O /tmp/bazel_0.4.2-linux-x86_64.deb https://github.com/bazelbuild/bazel/releases/download/0.4.2/bazel_0.4.2-linux-x86_64.deb
> ```

Please verify the checksum prior to installation.  (Its likely that wget's https implementation is satisfactory, but better safe?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-:-KY_CzWYjIPH0l5nmDUr:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-KY_CJ5EUOK4uM52T_JD:-KY_GVETu7mMJhh3n4wa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf356ba5c964adfcf5152a9aaf402ead164d3ba0/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This TODO is perhaps slightly misplaced now?  I refers to the EOF-list below, I think.
</blockquote></details>

Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4441#-KY_CoUjoVH3_LaxHDQB:-KY_GWknOSRkorXOLj6e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf356ba5c964adfcf5152a9aaf402ead164d3ba0/setup/ubuntu/16.04/install_prereqs.sh#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please verify the checksum prior to installation.  (Its likely that wget's https implementation is satisfactory, but better safe?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4441)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4441)*

**Pull request merged**
