### PR TITLE
Minor fixes for matlab <-> drake-visualizer interactions

### LINKED ISSUE #1376: terrainInterpTest shows obvious mismatch with the terrain as visualized in the director
The dynamics are self-consistent and pass all of the matlab-side tests, but the visualization is obviously wrong.  The most likely culprit, I think, it my obj writing code.  @patmarion -- it's low priority, but tagging you in case you have ideas.

The test is drake/systems/plants/test/terrainInterpTest.m 
screenshot-2015-09-26_17 48 12

### PR DESCRIPTION
**Pull request by RussTedrake**
resolves #1376 and #1452 
also cleans up the writeMeshOBJ, which was computing normals then never using them.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2230)

### CODE REVIEW

**Comment by patmarion** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2230#-:-KGgUmmg6Jpm9vRRntj5:1417088721)*

**Comment by RussTedrake** [comment]
+jeremy-nimmer-tri for the merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2230#-:-KHC87w96Y4UIV13_7to:-472209830)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +@sherm1 for platform review of matlab code.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2230#-:-KHCQVxSkK4mIAgDp9x2:-1455380139)*

**Comment by sherm1** [comment]
I'm currently unable to run Matlab, but the changes look good. I deem this sufficiently tested by @russtedrake and @patmarion and will merge. :lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> -@jwnimmer-tri +@sherm1 for platform review of matlab code.</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2230#-:-KHRPcVqHYepSM8_sC5q:1100344698)*

**Pull request merged**
