### PR TITLE
CompliantContactManager computes contact results

### PR DESCRIPTION
**Pull request by amcastro-tri**
`CompliantContactManager` instantiates a SAP solver and loads contact results.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989#-:-N-y_hRx1Pvc5Uic6Vgg:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. I have a concern about the assumption that the contact constraints are always added first. PTAL, thanks.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989#-:-N-ymuRfCoJLt3UUOwYn:b4r1dn7)* status: 8 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/plant/compliant_contact_manager.h, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ybvVLEm0QR68FbcnR:-N-ybvVMD_1qjQRjzOuO:b-xcq4vh) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L132)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(CompliantContactManager)
> 
>   // Constructs a contact manager that takes ownership of the supplied
> ```

This comment needs an update.
___
*[multibody/plant/compliant_contact_manager.h, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ycXEv8SmcUhSJh0Ul:-N-ycXEv8SmcUhSJh0Um:b-82mdmh) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L158)):*
> ```objc
>   }
> 
>   // TODO(amcastro-tri): Implement these methods in future PRs.
> ```

BTW, this TODO is no longer accurate given 16955
___
*[multibody/plant/compliant_contact_manager.h, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ygAIJ70Jf2-U6SRS-:-N-ygAIJ70Jf2-U6SRS0:b37w0lg) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L294)):*
> ```objc
>   // on output.
>   // @pre contact_results is not nullptr.
>   // @pre All `num_contacts` contact constraints in `problem` were added before
> ```

This seems like an awkward requirement. The correctness of all functions (in particular, `DoCalcContactSolverResults()`) that invoke this function depends on the ordering of constraints in the SapContactProblem, which is opaque to the caller. 

Are there some guidance on how the constraints should be added when constructing the sap contact problem? We'd want to fail early if the caller tries to add other types of constraints before adding contact constraints. It'd be even better if there's an inspector type of thing that extracts the contact impulse from the sap results without assuming any ordering of the constraints.
___
*[multibody/plant/compliant_contact_manager.cc, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yfexBEJgr28rDUVKT:-N-yfexBEJgr28rDUVKU:btbwnwv) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L620)):*
> ```cpp
>   if (status !=
>       drake::multibody::contact_solvers::internal::SapSolverStatus::kSuccess) {
>     throw std::runtime_error("SAP solver failed.");
> ```

The error message should be more helpful with hints on how to avoid the solver failure. Perhaps at least a TODO for now?
___
*[multibody/plant/compliant_contact_manager.cc, line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yjklf3_265duWjmIW:-N-yjklf3_265duWjmIX:b8okw9u) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L643)):*
> ```cpp
>   const VectorX<T> contact_forces =
>       sap_results.gamma.head(3 * num_contacts) / plant().time_step();
>   const VectorX<T> contact_velocities = sap_results.vc.head(3 * num_contacts);
> ```

nit, is a copy needed here?
___
*[multibody/plant/compliant_contact_manager.cc, line 652 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yjtiD1THmfy-vob7g:-N-yjtiD1THmfy-vob7h:bsmf4lk) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L652)):*
> ```cpp
>   tau_contact.setZero();
>   for (int i = 0; i < num_contacts; ++i) {
>     const auto& c = problem.get_constraint(i);
> ```

nit, opaque auto.
___
*[multibody/plant/compliant_contact_manager.cc, line 749 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yh1a72AziRsTQCtXz:-N-yh1a88g4ROvAwNgPn:b-dc1t22) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L749)):*
> ```cpp
>     const drake::systems::Context<T>& context,
>     drake::systems::DiscreteValues<T>* updates) const {
>   const contact_solvers::internal::ContactSolverResults<T>& results =
> ```

BTW, more liberal uses of cc-file-level aliases could help with the namespace spam.
___
*[multibody/plant/compliant_contact_manager.cc, line 755 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yi3ulC7ua04p5JIvn:-N-yi3ulC7ua04p5JIvo:bodfgcy) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L755)):*
per documentation in `DiscreteValues`:

>   /// (Don't use this in new code) Returns the entire vector as a const
  /// Eigen::VectorBlock for the _only_ group. Prefer `value()` which returns
  /// direct access to the underlying VectorX rather than wrapping it in a
  /// VectorBlock.
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 331 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ykb650RQi0yZpig1F:-N-ykb650RQi0yZpig1G:blnhzxm) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L331)):*
> ```cpp
> 
>   void PackContactSolverResults(
>       const contact_solvers::internal::SapContactProblem<double>& problem,
> ```

BTW, you don't need the namespaces here with the alias at the top of the file
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 742 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ylYDGExD9Dm42wiAg:-N-ylYDGExD9Dm42wiAh:bhna6i1) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L742)):*
> ```cpp
>   sap_results.Resize(nv, 3 * num_contacts);
>   sap_results.v = VectorXd::LinSpaced(nv, -3.0, 14.0);
>   sap_results.gamma = VectorXd::LinSpaced(3 * num_contacts, -12.0, 8.0);
> ```

nit, would it be helpful to set up the sap results to have more than contact impulse?
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N-ymY_QBVG91NTn7gFk:bc5ynxs) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
> ```cpp
> 
>   ContactSolverResults<double> contact_results_expected;
>   PackContactSolverResults(sap_problem, num_contacts, sap_results,
> ```

It feels like the expected results are calculated using the same code path as the results under tests. Could you clarify the testing strategy here? Ditto for the test below.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/plant/compliant_contact_manager.h, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ybvVLEm0QR68FbcnR:-N01TCzX1a2esJ5D8x2F:b-hrxhmb) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L132)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This comment needs an update.
</blockquote></details>

Done.
BTW, I don't see anything useful to add here beyond what it is stated in the class's documentation. Let me know if there'd be something I am missing.
___
*[multibody/plant/compliant_contact_manager.h, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ygAIJ70Jf2-U6SRS-:-N01JOmE7uTvU4cZpUjV:by42ju7) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L294)):*
I added notes. IMO it is not awkward at all, though I agree with you it should be properly documented. It is the manager after all who has control on how constraints are added to the problem. That is, this ordering is very local to the manager's implementation. I added notes here and in the implementation of PackContactSolverResults() to make this clear.

> an inspector type of thing

I didn't understand this. But I believe simple is better in this case?
___
*[multibody/plant/compliant_contact_manager.cc, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yfexBEJgr28rDUVKT:-N01N8ga00yLqqaKn9XO:b4619md) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L620)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The error message should be more helpful with hints on how to avoid the solver failure. Perhaps at least a TODO for now?
</blockquote></details>

added a better error message. I kept it simple for now assuming (knowing) it'll change as users run into this exception and this one message does not cover their problem.
___
*[multibody/plant/compliant_contact_manager.cc, line 755 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yi3ulC7ua04p5JIvn:-N01Rf4vCVCIhMQCVLv1:bd5l6mr) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L755)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

per documentation in `DiscreteValues`:

>   /// (Don't use this in new code) Returns the entire vector as a const
  /// Eigen::VectorBlock for the _only_ group. Prefer `value()` which returns
  /// direct access to the underlying VectorX rather than wrapping it in a
  /// VectorBlock.
</blockquote></details>

thanks!
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 742 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ylYDGExD9Dm42wiAg:-N01SQCI2jQJGWmuJzfO:b-dhdcir) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L742)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, would it be helpful to set up the sap results to have more than contact impulse?
</blockquote></details>

Yes, it would be. However the manager does not add any other constraints yet. I placed a TODO that I'll be able to address when the manager adds other constraints (e.g. coupler and joint limit constraints).
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N01SjuwBlw-Tj6vQMat:b9korib) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It feels like the expected results are calculated using the same code path as the results under tests. Could you clarify the testing strategy here? Ditto for the test below.
</blockquote></details>

yes, that's correct. I was hoping the comment at the top of this test would help. Not sure what else to add though. Would it help  to explicitly state in the comment that the computations are the same?

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: @rpoyner-tri for platform review per rotation please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989#-:-N01tEm6CfHbU4VjNuQy:bu38on)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/plant/compliant_contact_manager.h, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ygAIJ70Jf2-U6SRS-:-N01sBKsDtwpJOTGJqV4:bkeok1h) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.h#L294)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I added notes. IMO it is not awkward at all, though I agree with you it should be properly documented. It is the manager after all who has control on how constraints are added to the problem. That is, this ordering is very local to the manager's implementation. I added notes here and in the implementation of PackContactSolverResults() to make this clear.

> an inspector type of thing

I didn't understand this. But I believe simple is better in this case?
</blockquote></details>

I'm content with the documentation (but I think it needs to be in the header of CalcContactProblemCache(), see the thread below).
___
*[multibody/plant/compliant_contact_manager.cc, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yfexBEJgr28rDUVKT:-N01ryDZ4Cv34l0fzg5J:b65fop5) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L620)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

added a better error message. I kept it simple for now assuming (knowing) it'll change as users run into this exception and this one message does not cover their problem.
</blockquote></details>

Thanks for the better message. Unblocked.

This code path not covered by test though.
___
*[multibody/plant/compliant_contact_manager.cc, line 756 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N01reHr3U2AtRj1rkAI:-N01reHr3U2AtRj1rkAJ:b-5jrbrz) ([raw file](https://github.com/robotlocomotion/drake/blob/e44131eb1229fd33ebcc26475196877ab7c5a635/multibody/plant/compliant_contact_manager.cc#L756)):*
> ```cpp
>   CalcFreeMotionVelocities(context, &v_star);
>   problem.Reset(std::move(A), std::move(v_star));
>   // N.B. All contact constraints must be added before any other constraint
> ```

minor, I'd vote for moving this comment to the header. This is a promise that this Calc function needs to fulfill in order for other parts of the manager to work properly. 
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N01sVFp1QDYSae88dPk:b-y5x2us) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

yes, that's correct. I was hoping the comment at the top of this test would help. Not sure what else to add though. Would it help  to explicitly state in the comment that the computations are the same?
</blockquote></details>

Unblocked for now because the result seems fine to me. However, the circular logic still concerns me because the unit test will always pass if we just copypaste the implementation. For example, in the implementation of assembling the next state, if we accidentally swapped q and v in our implementation and copypasted into the test, the test won't complain.

I'd advocate for a dummy value where we can actually compare against but I'm not sure how feasible that is. I'll unblock and see if @rpoyner-tri have some insight on this.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N01yeW_C7Jt7_8TJ0mm:b-x7zi4p) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
> f we accidentally swapped q and v in our implementation and copypasted into the test, the test won't complain.

That's true. This test only cares about making sure the NVI loads the corresponding results appropriately. Therefore the comment "The purpose of this test is not to verify the correctness of the computation".

Notice that the unit test below `DoCalcDiscreteValues` does test for the order of q and v.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N029OczCbquB-7F-Ztf:b-f2f41d) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
> Notice that the unit test below DoCalcDiscreteValues does test for the order of q and v.

That's based on the assumption that the implementation code is correct to start with (because the test is essentially a copypasta of the implementation)?

> This test only cares about making sure the NVI loads the corresponding results appropriately

I understand the purpose of the test. I'm questioning whether the purpose is achieved. How do we know if the result is loaded correctly if we calculate the "expected" result the same way the actual results are loaded. The results will always be identical.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02De3QCTp58Pbr1mQ3:bhdndn6) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
> That's based on the assumption that the implementation code is correct to start with (because the test is essentially a copypasta of the implementation)?

For the test below, yes. Are you proposing we should have a test with analytical solution or something of the like? TBH I'd need to think much harder about that test. Any ideas?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02JCYLDwDZ7c9IWx-N:b7sth9) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> That's based on the assumption that the implementation code is correct to start with (because the test is essentially a copypasta of the implementation)?

For the test below, yes. Are you proposing we should have a test with analytical solution or something of the like? TBH I'd need to think much harder about that test. Any ideas?
</blockquote></details>

Let I said before, I'm gonna punt on this one and let the platform reviewer decide if this is worth holding up this PR.

One could imagine setting up a scenario where the next time step state is known analytically (easier if no contact actually happens).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02Pdcd0qBQEPOOSvx7:b-8adwf2) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Let I said before, I'm gonna punt on this one and let the platform reviewer decide if this is worth holding up this PR.

One could imagine setting up a scenario where the next time step state is known analytically (easier if no contact actually happens).
</blockquote></details>

Uhm, thanks @xuchenhan-tri ? :) I'm not wild about the circular logic here either. I'll need to think on this.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: generally, but I'm still thinking about the test strategy question.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989#-:-N02PyJm9V_pt9W3Wtym:b-e768yv)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02WjJfD-vs1R2sLKae:be8pu5h) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Uhm, thanks @xuchenhan-tri ? :) I'm not wild about the circular logic here either. I'll need to think on this.
</blockquote></details>

Hrm. The testing problem is moderately hard. @amcastro-tri what do you think about marking these to tests with a TODO and revisiting once we have had a chance to discuss?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02aDDH36vE_rEc4bHJ:bmlwmxq) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hrm. The testing problem is moderately hard. @amcastro-tri what do you think about marking these to tests with a TODO and revisiting once we have had a chance to discuss?
</blockquote></details>

@rico I didn't mean to dump the responsibility on you (sorry it came off that way). What I intended to express was that "I'm ok to check in this code as is (perhaps with a TODO). If you want to block it, feel free to do that".

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @rico)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02fXUf4takVgK0Eqwq:b-8jiws2) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@rico I didn't mean to dump the responsibility on you (sorry it came off that way). What I intended to express was that "I'm ok to check in this code as is (perhaps with a TODO). If you want to block it, feel free to do that".
</blockquote></details>

Why yes, I think I will block. Since testing problem is tricky, I would be satisfied with some TODOs.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 3 unresolved discussions (waiting on @amcastro-tri and @rico)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 1 unresolved discussion (waiting on @rico and @xuchenhan-tri)

___
*[multibody/plant/compliant_contact_manager.cc, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-yfexBEJgr28rDUVKT:-N02rcuJ5863FB_skNYT:be1vvj9) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/compliant_contact_manager.cc#L620)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Thanks for the better message. Unblocked.

This code path not covered by test though.
</blockquote></details>

added unit test.
___
*[multibody/plant/compliant_contact_manager.cc, line 756 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N01reHr3U2AtRj1rkAI:-N02cCLI5oMeOR7-MNBj:b6kkf1r) ([raw file](https://github.com/robotlocomotion/drake/blob/e44131eb1229fd33ebcc26475196877ab7c5a635/multibody/plant/compliant_contact_manager.cc#L756)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I'd vote for moving this comment to the header. This is a promise that this Calc function needs to fulfill in order for other parts of the manager to work properly. 
</blockquote></details>

I placed this in the header and also left it here since as a developer I like to see this warning not to swap the order of things locally.
___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02ch9g0vGLL31IZwPw:brw0rc5) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Why yes, I think I will block. Since testing problem is tricky, I would be satisfied with some TODOs.
</blockquote></details>

In f2f @rpoyner-tri gave me an idea to test this. Essentially a case without contact so that we can verify the state updates flow correctly through the pipeline. PTAL.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: 1 unresolved discussion (waiting on @rico)

___
*[multibody/plant/test/compliant_contact_manager_test.cc, line 793 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16989#-N-ymY_QBVG91NTn7gFj:-N02stMU6_xxKstueAcJ:b-h1hkmp) ([raw file](https://github.com/robotlocomotion/drake/blob/9d3a4a8c40360dea2a3118b36363ad46455d84a4/multibody/plant/test/compliant_contact_manager_test.cc#L793)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

In f2f @rpoyner-tri gave me an idea to test this. Essentially a case without contact so that we can verify the state updates flow correctly through the pipeline. PTAL.
</blockquote></details>

Very nice, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16989)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
