### PR TITLE
remove constraint from MathematicalProgram

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please as we discussed removing constraint a week ago.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350#-:-Me8lJ-9Ddy80I17qKLy:bkhso2g)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm: Sorry for the delay! +@sammy-tri for platform review.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350#-:-MeaQPXhBmPrLDl3-sPb:bn1b1sm)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MeaR17-90mBeyGAZY2d:b-mxtaep) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
> ```cpp
>       .def("RemoveCost", &MathematicalProgram::RemoveCost, py::arg("cost"),
>           doc.MathematicalProgram.RemoveCost.doc)
>       .def(  // Remove this overload when #15272 is resolved.
> ```

nit 15272 _is_ resolved (as of recently).

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MeamOwqCcTJm09nWa6v:b-l9ejr7) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 15272 _is_ resolved (as of recently).
</blockquote></details>

Upgrading this from a nit.  If we can remove this boilerplate, we should.
___
*[solvers/mathematical_program.cc, line 1436 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-Meajs7I1_cMCrmJn-V7:-Meajs7I1_cMCrmJn-V8:b-qeui0x) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/solvers/mathematical_program.cc#L1436)):*
> ```cpp
>     case ProgramAttribute::kLinearCost: {
>       UpdateRequiredCapabilityImpl(query_capability, this->linear_costs(),
>                                    &(this->required_capabilities_));
> ```

Is there a reason this is spelled `&(this->required_capabilities_)` instead of `&required_capabilities_`?  (same question below about the constraints)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-Meceym2-63u2jieldup:b-i5rs4y) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Upgrading this from a nit.  If we can remove this boilerplate, we should.
</blockquote></details>

I tried to remove this overload, but got the error

```
TypeError: RemoveConstraint(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearEqualityConstraint>) -> int
    2. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::BoundingBoxConstraint>) -> int
    3. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LorentzConeConstraint>) -> int
    4. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::RotatedLorentzConeConstraint>) -> int
    5. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::PositiveSemidefiniteConstraint>) -> int
    6. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearMatrixInequalityConstraint>) -> int
    7. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::ExponentialConeConstraint>) -> int
    8. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearComplementarityConstraint>) -> int
    9. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Constraint>) -> int

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0cd70b1030>; kwargs: constraint=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0cd420d130>

```
I think we still can't cast `Binding_LinearConstraint` to `Constraint` class in pydrake..
___
*[solvers/mathematical_program.cc, line 1436 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-Meajs7I1_cMCrmJn-V7:-MecfdZ18wRuQNTlQxi2:brehjjn) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/solvers/mathematical_program.cc#L1436)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is there a reason this is spelled `&(this->required_capabilities_)` instead of `&required_capabilities_`?  (same question below about the constraints)
</blockquote></details>

Done. I changed them all to `&required_capabilities_`

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-Mee74vr0-Qd5-GHxJn7:ba8t0bw) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I tried to remove this overload, but got the error

```
TypeError: RemoveConstraint(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearEqualityConstraint>) -> int
    2. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::BoundingBoxConstraint>) -> int
    3. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LorentzConeConstraint>) -> int
    4. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::RotatedLorentzConeConstraint>) -> int
    5. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::PositiveSemidefiniteConstraint>) -> int
    6. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearMatrixInequalityConstraint>) -> int
    7. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::ExponentialConeConstraint>) -> int
    8. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, constraint: drake::solvers::Binding<drake::solvers::LinearComplementarityConstraint>) -> int
    9. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Constraint>) -> int

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0cd70b1030>; kwargs: constraint=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0cd420d130>

```
I think we still can't cast `Binding_LinearConstraint` to `Constraint` class in pydrake..
</blockquote></details>

Ok.  Well, eventually...
___
*[solvers/mathematical_program.cc, line 1572 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15350#-Mee7JlY-z0K-u1aZvCN:-Mee7JlY-z0K-u1aZvCO:b-ydxiwl) ([raw file](https://github.com/robotlocomotion/drake/blob/39fcb070a1c213c8e351dedfa94c35ac619422fb/solvers/mathematical_program.cc#L1572)):*
> ```cpp
>         internal::BindingDynamicCast<ExponentialConeConstraint>(constraint),
>         ProgramAttribute::kExponentialConeConstraint,
>         &(this->exponential_cone_constraints_));
> ```

Can we remove the `this->` in this function too?

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MeeQc357suew5C4uZcP:b-egomo2) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ok.  Well, eventually...
</blockquote></details>

Even if we can't remove the extra overloads now, the problem with this PR is that the comment is lie.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @sammy-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MegiFMR9qR_jI2PyLkC:bbtjlyj) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Even if we can't remove the extra overloads now, the problem with this PR is that the comment is lie.
</blockquote></details>

I updated the comment and filed the github issue #15405

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[solvers/mathematical_program.cc, line 1572 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15350#-Mee7JlY-z0K-u1aZvCN:-Megir2VErItX6NCuVKp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/39fcb070a1c213c8e351dedfa94c35ac619422fb/solvers/mathematical_program.cc#L1572)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Can we remove the `this->` in this function too?
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MejYGYt1vGtiGUNEVY9:b-lfm9xi) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I updated the comment and filed the github issue #15405 
</blockquote></details>

Do you want to wait on #15408 to merge and then use that for this PR?  Or merge as-is and fix up later?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-MekgobiDD_4757p_lhm:bcsigty) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do you want to wait on #15408 to merge and then use that for this PR?  Or merge as-is and fix up later?
</blockquote></details>

Good call. Yes I would like to wait #15408 to merge.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1352 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15350#-MeaR16y4SLiXprDnmUG:-Mf17edj2YsVI2xY0EgZ:by6zlj0) ([raw file](https://github.com/robotlocomotion/drake/blob/66a23520e60c94cf12ad7094837073f91a8001f3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1352)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call. Yes I would like to wait #15408 to merge.
</blockquote></details>

Done, the overloaded functions are removed.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15350#-:-Mf3oJse6Y_zLu1yMVBN:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),avalenzu (waiting on @hongkai-dai)

**Pull request merged**
