### PR TITLE
[doc] Add direct links for buildcop cache server checks

### LINKED ISSUE #17806: [buildcop] Document which jobs expect remote cache usage
We need to produce a simple list of which jobs do / do not expect to have `REMOTE_CACHE_KEY` set.  See [slack discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1661951253328859).

### PR DESCRIPTION
**Pull request by svenevs**
Closes #17806.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review please.  To build docs locally: `bazel run //doc:pages -- --serve` and look at `http://localhost:8000/buildcop.html` in browser.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455#-:-NJGiudu0sHTeAthyrdI:b-wfs419)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455#-:-NJMBmucCLLs9lwOiR6g:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by BetsyMcPhail — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455#-:-NJlF3tQ7IWqTstNiDYq:b-hnc6mz)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @svenevs)

___
*[`doc/_pages/buildcop.md` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18455#-NJlGe4rBK-cBjSK2a9l:-NJlGe4rBK-cBjSK2a9m:bvbwbns) ([raw file](https://github.com/robotlocomotion/drake/blob/885780f95def8e146a29c5fe81939478d42e9540/doc/_pages/buildcop.md#L176)):*
> ```Markdown
> 
> - [https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-release/lastBuild/consoleFull)
> - [https://drake-jenkins.csail.mit.edu/job/mac-x86-monterey-clang-bazel-continuous-release/lastBuild/consoleFull](https://drake-jenkins.csail.mit.edu/job/mac-x86-monterey-clang-bazel-continuous-release/lastBuild/consoleFull)
> ```

I tried to do what the document said, and I could not find `REMOTE_CACHE_KEY` in the text logs. I did find this: `--remote_cache=http://172.31.20.109/v2/2a690ca10aa78b224c5a7f1e91fe9d17d30be3432cb0154f06ab123d6c4f4556`. Am I doing something wrong, or do the docs need adjusting?

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`doc/_pages/buildcop.md` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18455#-NJlGe4rBK-cBjSK2a9l:-NJlHmkb86IpKdMoJnwU:b-crdqlv) ([raw file](https://github.com/robotlocomotion/drake/blob/885780f95def8e146a29c5fe81939478d42e9540/doc/_pages/buildcop.md#L176)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I tried to do what the document said, and I could not find `REMOTE_CACHE_KEY` in the text logs. I did find this: `--remote_cache=http://172.31.20.109/v2/2a690ca10aa78b224c5a7f1e91fe9d17d30be3432cb0154f06ab123d6c4f4556`. Am I doing something wrong, or do the docs need adjusting?
</blockquote></details>

You may need to click on "Full Log" first. At the beginning of every job there's a table with various versions listed, `REMOTE_CACHE_KEY` is there.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`doc/_pages/buildcop.md` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18455#-NJlGe4rBK-cBjSK2a9l:-NJlIDIA1u3nSowzfyuM:bcoltqx) ([raw file](https://github.com/robotlocomotion/drake/blob/885780f95def8e146a29c5fe81939478d42e9540/doc/_pages/buildcop.md#L176)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

You may need to click on "Full Log" first. At the beginning of every job there's a table with various versions listed, `REMOTE_CACHE_KEY` is there.
</blockquote></details>

Actually the full log should be shown with the `consoleFull url`. It is not too far above the `--remote-cache=...` lines

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18455#-:-NJla2RK-Dj90pAfyBeJ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @svenevs)

___
*[`doc/_pages/buildcop.md` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18455#-NJlGe4rBK-cBjSK2a9l:-NJl_ufE-0yxcDZyIrMy:b5r92lk) ([raw file](https://github.com/robotlocomotion/drake/blob/885780f95def8e146a29c5fe81939478d42e9540/doc/_pages/buildcop.md#L176)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Actually the full log should be shown with the `consoleFull url`. It is not too far above the `--remote-cache=...` lines
</blockquote></details>

Yeah, I see it now. Not sure what I was doing wrong, but nevermind.

**Pull request merged**
