### PR TITLE
Adds CommonSolverOption::kStandaloneReproductionFileName

### PR DESCRIPTION
**Pull request by RussTedrake**
and adds support for it to ClarabelSolver.

+@jwnimmer-tri for feature review, please.
Our slack discussion was [here](https://drakedevelopers.slack.com/archives/C0557S260N8/p1713492966311459?thread_ts=1709046236.828909&cid=C0557S260N8).

I was encouraged to finish this because bumping to the latest Drake (which had bumped Clarabel) broke one of my simple examples in underactuated again.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I can look at this later next week, but I have other high-priority stuff taking my time at the moment.

One question / prompt -- should the option point to a _directory_ instead of a _file_?

In cases like GCS where we are solving more than just one program, I worry that an option for a _filename_ will be too limiting.  We would only ever get the output from the last program, or worse if we are using multithreading they might fight about who writes to the file.

**Review by RussTedrake — COMMENTED** [review]
If pointing to a file is good enough for kPrintFileName, then it should be good enough here. GCS has modes where it solves multiple programs, but we can also set the options so that it only solves one... and that's what I would expect that we want for writing a reproduction to file.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-:-O009lBY0cKM5ZD9UYiR:b2zdhu4)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
Okay.  In short -- I don't understand how this is designed be used.  You should probably find a feature reviewer who understands that (i.e., will be a user of this feature), and let them assess.  -@jwnimmer-tri opting out.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-:-O00Blb31gPjIM0tuilg:b-j52g7q)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/common_solver_option.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O00CPIq-1SoY_3SNLmG:-O00CPIr3XWVf2K94PMr:b-xjjtsz) ([raw file](https://github.com/RobotLocomotion/drake/blob/468f0d5938fa203d56b6a19bb94f3ae125dad60a/solvers/common_solver_option.h#L35)):*
> ```objc
>    * solver. To enable this, use e.g.
>    * SolverOptions::SetOption(kStandaloneReproductionFileName,
>    * "reproduction.py"). To disable, use
> ```

nit This is _common_ solver option, not a clarabel option.  It is not specified to only output Python code.



_Suggestion:_
```objc
reproduction.txt
```

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please?

FTR -- these are the two upstream PRs I've generated with this so far:
https://github.com/oxfordcontrol/Clarabel.rs/issues/96
https://github.com/oxfordcontrol/Clarabel.rs/issues/119

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/common_solver_option.h` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O00CPIq-1SoY_3SNLmG:-O00V2TTD4xwoq5GXJQ4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/468f0d5938fa203d56b6a19bb94f3ae125dad60a/solvers/common_solver_option.h#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is _common_ solver option, not a clarabel option.  It is not specified to only output Python code.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/clarabel_solver.cc` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O07gOr_5Oxa_4X3Nopy:-O07gOr_5Oxa_4X3Nopz:b-13cgy6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1326f3e47ed7a033105d91a24d3fc399aaaefc88/solvers/clarabel_solver.cc#L327)):*
> ```cpp
>     std::vector<double> data;
>     std::vector<int> rows;
>     std::vector<int> cols;
> ```

BTW, we can reserve the size of `data, rows, cols` here as
```cc
data.reserve(mat.nonZeros());
rows.reserve(mat.nonZeros());
cols.reserve(mat.nonZeros());
```
___
*[`solvers/clarabel_solver.cc` line 386 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O07hW3NEDNOBr8H7LSg:-O07hW3NEDNOBr8H7LSh:b-277sjs) ([raw file](https://github.com/RobotLocomotion/drake/blob/1326f3e47ed7a033105d91a24d3fc399aaaefc88/solvers/clarabel_solver.cc#L386)):*
> ```cpp
>         break;
>       default:
>         throw std::runtime_error("Unsupported cone type.");
> ```

nit, also indicate the function that throws the error?
```cc
throw std::runtime_error("WriteClarabelReproduction: Unsupported cone type.");
```

**Review by RussTedrake — COMMENTED** [review]
@hongkai-dai, did you mean to add LGTM?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-:-O08_2m26e8tlDZnxNB3:b-uime0b)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/clarabel_solver.cc` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O07gOr_5Oxa_4X3Nopy:-O08ZkzDE3vl8khBR3jj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1326f3e47ed7a033105d91a24d3fc399aaaefc88/solvers/clarabel_solver.cc#L327)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, we can reserve the size of `data, rows, cols` here as
```cc
data.reserve(mat.nonZeros());
rows.reserve(mat.nonZeros());
cols.reserve(mat.nonZeros());
```
</blockquote></details>

Done.
___
*[`solvers/clarabel_solver.cc` line 386 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O07hW3NEDNOBr8H7LSg:-O08ZvaeDXjoU6K1FF5M:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1326f3e47ed7a033105d91a24d3fc399aaaefc88/solvers/clarabel_solver.cc#L386)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, also indicate the function that throws the error?
```cc
throw std::runtime_error("WriteClarabelReproduction: Unsupported cone type.");
```
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@SeanCurtis-TRI for platform review please, thanks!

> Reviewed 4 of 10 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-:-O0AOuTk-yZIkLpyQbRh:btc9pyf)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one documentation question and one error condition question.

> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-:-O0Aw7Ur0egibyLR2zek:bfb9y2h)* status: 2 unresolved discussions

___
*[`solvers/clarabel_solver.cc` line 389 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0Avhm0AC6azYprBCel:-O0AvdJQ0cXVlTTEBIf7:bmkknk8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/clarabel_solver.cc#L389)):*
> ```cpp
>         break;
>       default:
>         throw std::runtime_error(
> ```

BTW If there is a problem opening the file, we simply log an error and move on. Why throw in this case?
___
*[`solvers/common_solver_option.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0Au0apDkv4mDdwoqPj:-O0Au0apDkv4mDdwoqPk:btpfupc) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/common_solver_option.h#L35)):*
> ```objc
>    * solver. To enable this, use e.g.
>    * SolverOptions::SetOption(kStandaloneReproductionFileName,
>    * "reproduction.txt"). To disable, use
> ```

nit: In the clarabel solver, you explicitly append the `.py` extension. Is there guidance about extensions that depend on solvers?



_Code quote:_
```objc
"reproduction.txt"
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607)* status: 3 unresolved discussions

___
*[`solvers/clarabel_solver.cc` line 306 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0AxsKcC1cUdtQWYq59:-O0AxsKdBdS5Rg16OH_N:b-re7q22) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/clarabel_solver.cc#L306)):*
Sean's discussion caught my eye flying by my inbox.

> nit: In the clarabel solver, you explicitly append the `.py` extension. Is there guidance about extensions that depend on solvers?

Nothing about the API docs on the common solver option reflect that the solvers are going to alter the filename the user asked for.

For my taste, I don't think we _should_ amend the file name in any way here, but if we do decide to amend it then at minimum we need to clarify the option's doxygen that it's an _approximate_ request and the actual filename on disk might be different.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21607)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

___
*[`solvers/clarabel_solver.cc` line 306 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0AxsKcC1cUdtQWYq59:-O0THyNp4hMu7NTuTHpQ:bdser8v) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/clarabel_solver.cc#L306)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sean's discussion caught my eye flying by my inbox.

> nit: In the clarabel solver, you explicitly append the `.py` extension. Is there guidance about extensions that depend on solvers?

Nothing about the API docs on the common solver option reflect that the solvers are going to alter the filename the user asked for.

For my taste, I don't think we _should_ amend the file name in any way here, but if we do decide to amend it then at minimum we need to clarify the option's doxygen that it's an _approximate_ request and the actual filename on disk might be different.
</blockquote></details>

Done. I've removed the ammending.
___
*[`solvers/clarabel_solver.cc` line 389 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0Avhm0AC6azYprBCel:-O0TI7Sy48PArCy8kAcd:bsd90at) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/clarabel_solver.cc#L389)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If there is a problem opening the file, we simply log an error and move on. Why throw in this case?
</blockquote></details>

Done.  Now i log an error but don't throw.  (this one was stranger, since the file is half written)
___
*[`solvers/common_solver_option.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21607#-O0Au0apDkv4mDdwoqPj:-O0TIFbb-AdJ0VqfVOC_:b-obon5t) ([raw file](https://github.com/RobotLocomotion/drake/blob/b446815299e7b114383eefd8590bf29cd627b506/solvers/common_solver_option.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: In the clarabel solver, you explicitly append the `.py` extension. Is there guidance about extensions that depend on solvers?
</blockquote></details>

Done. (removed the ammending)

**Pull request merged**
