### PR TITLE
workspace: Use system Eigen, not downloaded bitbucket tag

### LINKED ISSUE #11758: Use OS version of Eigen
We are using a pinned version of Eigen (3.3.3) because it used to be the case that the OS version of Eigen was too old on most platforms (Trusty and Xenial).  However, in Bionic we have 3.3.4 available.

So once we drop support for Xenial (#10606) there is no more reason to pin and download and install our own version of Eigen.

I'd like to start that transition now, conditioned on an `os != xenial` guard in `repository.bzl`, so that we can both de-risk it and and reap the benefits prior to the Xenial EOL date.

- Use ubuntu Eigen 3.3.4 on Bionic.
- Use homebrew Eigen 3.3.7 on macOS.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #11758.  Needs #12784 and #12785 first.

I decided not to try to do Ubuntu and macOS separately.  It seems clearest to purge the installed-cmake-config code all at once, instead of conditioning it by platform.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12780)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please

**Comment by jwnimmer-tri** [comment]
The `unrevised_lemke_solver` error occurs while multiplying a 0x3 matrix with a 3x1 vector to get a 0x1 vector.

Might be similar to https://gitlab.com/libeigen/eigen/-/commit/0db6d5b3f434ae2e0c2e8b78402e062e67e86339 (which claims fixed in 3.3.1).

```
#6  0x000055555650e311 in __ubsan_handle_type_mismatch_v1 ()
#7  0x00005555565d6074 in Eigen::internal::blas_data_mapper<double const, long, 0, 0>::operator() (this=0x7fffffffcdc0, i=0, j=<optimized out>) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/util/BlasUtil.h:218
#8  Eigen::internal::blas_data_mapper<double const, long, 0, 0>::getVectorMapper (this=0x7fffffffcdc0, i=0, j=<optimized out>) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/util/BlasUtil.h:212
#9  Eigen::internal::general_matrix_vector_product<long, double, Eigen::internal::const_blas_data_mapper<double, long, 0>, 0, false, double, Eigen::internal::const_blas_data_mapper<double, long, 1>, false, 0>::run (rows=<optimized out>, cols=3, lhs=..., rhs=..., res=<optimized out>, resIncr=1, alpha=1)
    at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/products/GeneralMatrixVector.h:291
#10 0x00005555565d2891 in Eigen::internal::gemv_dense_selector<2, 0, true>::run<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > (lhs=..., rhs=..., dest=..., alpha=<optimized out>)
    at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/GeneralProduct.h:238
#11 0x00005555565d23c4 in Eigen::internal::generic_product_impl_base<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::internal::generic_product_impl<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::DenseShape, Eigen::DenseShape, 7> >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (dst=..., lhs=..., rhs=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/ProductEvaluators.h:349
#12 0x00005555565d2112 in Eigen::internal::product_evaluator<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0>, 7, Eigen::DenseShape, Eigen::DenseShape, double, double>::product_evaluator (this=0x7fffffffcf78, xpr=...)
    at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/ProductEvaluators.h:124
#13 0x00005555565d1c3d in Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, Eigen::internal::IndexBased, Eigen::internal::IndexBased, double, double>::binary_evaluator (this=0x7fffffffcf70, xpr=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/CoreEvaluators.h:701
#14 0x0000555556644573 in Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, Eigen::internal::assign_op<double, double> > (dst=..., src=..., func=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/AssignEvaluator.h:730
#15 0x000055555664431f in Eigen::internal::call_assignment<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> const> > (dst=..., src=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/AssignEvaluator.h:782
#16 0x0000555556644223 in Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::_set<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> const> > (this=0x7fffffffd7d0, other=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/PlainObjectBase.h:710
#17 0x00005555565752dc in Eigen::Matrix<double, -1, 1, 0, -1, 1>::operator=<Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> const> > (
    this=0x7fffffffd7d0, other=...) at external/eigen/include/_usr_include_eigen3/Eigen/src/Core/Matrix.h:225
#18 0x000055555656fa5a in drake::solvers::UnrevisedLemkeSolver<double>::LemkePivot (this=0x7fffffffd668, M=..., q=..., driving_index=<optimized out>, zero_tol=2.6645352591003757e-15, M_prime_col=0x7fffffffd578, q_prime=0x7fffffffd558) at solvers/unrevised_lemke_solver.cc:446
#19 0x000055555656be71 in drake::solvers::UnrevisedLemkeSolver<double>::SolveLcpLemke (this=0x7fffffffd668, M=..., q=..., z=0x7fffffffd930, num_pivots=<optimized out>, zero_tol=<optimized out>) at solvers/unrevised_lemke_solver.cc:804
#20 0x000055555651f354 in drake::solvers::RunLCP<Eigen::Matrix<double, 3, 3, 0, 3, 3> > (M=..., q=..., expected_z_in=...) at solvers/test/unrevised_lemke_solver_test.cc:27
#21 0x000055555650f7de in drake::solvers::TestUnrevisedLemke_TestCycling_Test::TestBody (this=<optimized out>) at solvers/test/unrevised_lemke_solver_test.cc:73
```

**Comment by sherm1** [comment]
cc @edrumwri

**Comment by jwnimmer-tri** [comment]
I'm pretty sure it's a regression in Eigen when operating on matrices whose size == 0 but where one of rows or cols are non-zero, not any bug in Drake code.  I'm bisecting vs Eigen git now.

**Comment by jwnimmer-tri** [comment]
Ugh.  I bet it's just that our suppression is no longer matching the path: https://github.com/RobotLocomotion/drake/blob/d243bba621cb97d87bf351b9d0137e108ef84640/tools/dynamic_analysis/ubsan.supp#L12-L15

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape are you available for feature review?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
Anzu CI has passed on this PR.

**Pull request merged**
