### PR TITLE
Update build cop instructions to take into account weekly builds

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9557)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by EricCousineau-TRI** [comment]
FYI: `doc/buildcop.rst:12: ERROR: Unknown target name: "robotlocomotion/drake https://github.com/robotlocomotion/drake".`

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Pull request merged**
