### PR TITLE
Adds ability to throttle drake visualizer's publishing rate.

### LINKED ISSUE #4111: Update DrakeVisualizer to Throttle Message Publishing Rate
System 2.0 now allows a system to tell the integrator how frequently it wants to be published. DrakeVisualizer is currently publishing update message _every_ cycle of the simulation loop, which may be too fast.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4111.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4775)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@jwnimmer-tri for platform review please.

Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-KaKuD2pm-lgpaumFtmx:b-y7ffu7)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaL0esYqP2PvSi1hNG0:-KaL0esYqP2PvSi1hNG1:bhavuq) ([raw file](https://github.com/robotlocomotion/drake/blob/191c4199dd6e07e2a431cdc4e625da0ad438a258/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
> ```cpp
>   if (context.get_time() == 0.0) {
>     PublishLoadRobot();
>   }
> ```

FYI Yuck.  Were the braces bad?  I guess an 80x24 dialup terminal would have lost the last line of the method previously, but by saving 1 vertical line here the method now fits.  This removal is allowed by cppguide but you're temping me want to mandate the closing braces.  (Marking resolved.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-KaL3cqOIyzLy8xjjhX3:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaL0esYqP2PvSi1hNG0:-KaMYI6was746B64soJL:b-apy4f) ([raw file](https://github.com/robotlocomotion/drake/blob/191c4199dd6e07e2a431cdc4e625da0ad438a258/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Yuck.  Were the braces bad?  I guess an 80x24 dialup terminal would have lost the last line of the method previously, but by saving 1 vertical line here the method now fits.  This removal is allowed by cppguide but you're temping me want to mandate the closing braces.  (Marking resolved.)
</blockquote></details>

Done. #4777.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775)*

**Comment by amcastro-tri** [comment]
Just a few comments. 

---

Reviewed 4 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 507 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOV2gGkBwxv8gM2CTi:-KaOV2gGkBwxv8gM2CTj:b2vnhsm) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L507)):*
> ```cpp
>                            transmitted_message_bytes.size()),
>             transmitted_message_bytes.size());
>   EXPECT_EQ(transmitted_message.timestamp, timestamp);
> ```

Should probably use EXPECT_NEAR for floating point comparisons in general

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 534 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOUjTidsLejO6V85N6:-KaOUjTidsLejO6V85N7:bi849p4) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L534)):*
> ```cpp
>   for (double time = 0; time < 4; time += 0.01) {
>     simulator.StepTo(time);
>     EXPECT_EQ(simulator.get_mutable_context()->get_time(), time);
> ```

Should probably use EXPECT_NEAR for floating point comparisons in general.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 535 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOUdGYFwAPPdXGFlYu:-KaOUdGYFwAPPdXGFlYv:b1s32t1) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L535)):*
> ```cpp
>     simulator.StepTo(time);
>     EXPECT_EQ(simulator.get_mutable_context()->get_time(), time);
>     const double expected_time =
> ```

BTW, add comment the factor `1000` is to convert to milliseconds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-KaOVCqUxrfaZL8ollyQ:b-bilcp0)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. 

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 507 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOV2gGkBwxv8gM2CTi:-KaOn-YvKKRp7RdaS7Ih:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L507)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Should probably use EXPECT_NEAR for floating point comparisons in general
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 534 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOUjTidsLejO6V85N6:-KaOn5NxefaUetGiRBBH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L534)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Should probably use EXPECT_NEAR for floating point comparisons in general.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 535 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-KaOUdGYFwAPPdXGFlYu:-KaOnBogEVQKcfIdXg5I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c626b2062c45e13b877fd6454112e357f0f4031b/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L535)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, add comment the factor `1000` is to convert to milliseconds?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-KaOo78wCmHuHYeuFnRd:brn7v3u)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775)*

**Comment by jwnimmer-tri** [comment]
@amcastro-tri PTAL -- missing your LGTM.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-KaXOdatmQsO2LeUdxkG:b-314423)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4775#-:-Kags5mx7bJjgTRopJtY:bnfp4nl)*

**Pull request merged**
