### PR TITLE
Stop suppressing -Wunused-local-typedefs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #2372.
Do not merge until #2441 goes in first.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2454)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Looks okay; I take it you plan to rebase after #2441 lands (which will affect the `CMakeLists.txt` changes)?

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Stop suppressing \-Wunused\-local\-typedefs
> 
> Towards #2372.
> 
> Do not merge until #2441 goes in first.
> 
> 
> 
</details>


---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2454#-:-KIh_D2zMJeIyy-Ts4hJ:-1605646720)*

**Comment by jwnimmer-tri** [comment]
Precisely.

<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Looks okay; I take it you plan to rebase after #2441 lands (which will affect the `CMakeLists.txt` changes)?
</details>


---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2454#-:-KIh__Nt3hnZbCguRlJ4:857648875)*

**Comment by jwnimmer-tri** [comment]
Rebase completed.  Over to +@ggould-tri for platform review and merge (no hurry; tomorrow is fine).

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Precisely.
</details>


---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2454#-:-KIiSkASNpzjU2i8vhM-:-1527327563)*

**Comment by ggould-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Rebase completed.  Over to +@ggould-tri for platform review and merge (no hurry; tomorrow is fine).
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 95 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2454#-KIiTV2dccf2_vobs5tt:-KIiTV2dccf2_vobs5tu:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/a4be9d9c14ab79e156fcb63d942283e4b0518513/drake/CMakeLists.txt#L95)):*
> ```CMake
>   # TODO(#2372) These are warnings that we can't handle yet.
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare")
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-local-typedefs")
> ```

Yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2454#-:-KIiTyoiNULKu2LHZLXK:1417088721)*

**Pull request merged**
