### PR TITLE
[yaml] Deprecate the direct use of YAML::Node by users

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057#-:-Mo-cQO54QtAyLcf2u7L:bk7giky)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0JhsIC2Hg21r-E3CA:-Mo0JhsIC2Hg21r-E3CB:b-5fr84) (no related file):*
Working

I have a few Anzu PRs in flight that should be merged prior to this.

---

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a few nits.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057#-:-Mo13Y4z744LavSvxZ4G:b-u274hq)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo10xYfETD5mzYYgMR2:-Mo10xYfETD5mzYYgMR3:b-e760pb) (no related file):*
BTW, 

`drake/common/name_value.h` line 44 still says: "For how Serialize and Archive interact, see the drake::yaml::YamlReadArchive
class overview." That doesn't seem to be accurate anymore.

---
___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo0xLEp7clmi4p5JjMu:b-o6jvgo) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
> ```objc
>   void ParseScalar(const std::string& value, std::string* result);
> 
>   template <typename T, typename DeprecatedYamlNode = YAML::Node>
> ```

Could you explain why this template parameter is needed? i.e. What's wrong with just calling 

```
bool success = YAML::convert<T>::decode(YAML::Node(value), *result);
```

below?
___
*[common/yaml/yaml_read_archive.cc, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0zQgA83wQNrLvtVgB:-Mo0zQgA83wQNrLvtVgC:b-s69u52) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.cc#L159)):*
> ```cpp
> }
> 
> #pragma GCC diagnostic push
> ```

Should be a `pop` here?
___
*[common/yaml/test/example_structs.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0yNkn7SAGWmOOkzbK:-Mo0yNkn7SAGWmOOkzbL:b-l9h9rm) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/test/example_structs.h#L68)):*
> ```objc
>   double some_double = kNominalDouble;
>   int some_int = 12;
>   double some_size_t = 13;
> ```

nit, double->size_t.
___
*[bindings/pydrake/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo1-axNE-qVbJt6Fm6N:-Mo1-axNE-qVbJt6Fm6O:b-knsjma) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/bindings/pydrake/BUILD.bazel#L60)):*
> ```Starlark
>     name = "generate_pybind_documentation_header",
>     out = "documentation_pybind.h",
>     exclude_hdr_patterns = [
> ```

I'm not familiar with pybind. Does this ignore the headers listed when generating documentation?

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for platform review on Tuesday per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057#-:-Mo13hoJ8rzMGkCdzJz1:b-vkdyks)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo10xYfETD5mzYYgMR2:-Mo14DwV0QOEoOfoz9Lk:b3jyzfx) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, 

`drake/common/name_value.h` line 44 still says: "For how Serialize and Archive interact, see the drake::yaml::YamlReadArchive
class overview." That doesn't seem to be accurate anymore.
</blockquote></details>

OK I'll open a draft of the documentation PR soon; that PR resolves this.

---
___
*[bindings/pydrake/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo1-axNE-qVbJt6Fm6N:-Mo141Hp0IaUhYV9oCww:b-hl0wui) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/bindings/pydrake/BUILD.bazel#L60)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not familiar with pybind. Does this ignore the headers listed when generating documentation?
</blockquote></details>

Right!  The documentation extractor can't parse the forward-declared YAML types anymore, so I need to exclude those files.  However, none of those files are bound in pydrake, so it's a moot point.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri, @sherm1, and @xuchenhan-tri)

___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo16_Ze8BT3YFCozsoy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could you explain why this template parameter is needed? i.e. What's wrong with just calling 

```
bool success = YAML::convert<T>::decode(YAML::Node(value), *result);
```

below?
</blockquote></details>

Done.
___
*[common/yaml/yaml_read_archive.cc, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0zQgA83wQNrLvtVgB:-Mo16cxECUeFrjrmB3mi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.cc#L159)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should be a `pop` here?
</blockquote></details>

Done.
___
*[common/yaml/test/example_structs.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0yNkn7SAGWmOOkzbK:-Mo16z3x-R_Ag2yJ4IaU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/test/example_structs.h#L68)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, double->size_t.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo1IaPZ-c52za2buUG4:b-4mi7xn) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still don't get it. Perhaps there's a typo (unused -> used)?

Anyway, I get the sense that this has something to do with `YAML::Node` hasn't been defined yet, and we have to trick the linker here. Is that the idea?

But somehow replacing the line in question with
```
bool success = YAML::convert<T>::decode(YAML::Node(value), *result);
``` 
and getting rid of the newly introduced template parameter doesn't cause an issue for me?
___
*[bindings/pydrake/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo1-axNE-qVbJt6Fm6N:-Mo1K4_U96l7obipnRa_:b-lg05o9) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/bindings/pydrake/BUILD.bazel#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right!  The documentation extractor can't parse the forward-declared YAML types anymore, so I need to exclude those files.  However, none of those files are bound in pydrake, so it's a moot point.
</blockquote></details>

I see, thanks for the explanation.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo1KdU4C1E9Bt4vSo17:b-x65mlu) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
Hmm, I see how "unused" might be misleading.  I meant "typical case where this function is unused _by users of the header_".   The cc file uses this function, but already includes YAML::Node, so the forward-declaration is fully defined in that case.  I'll clean up the comment.

> ... doesn't cause an issue for me?

Did you try all of our supported compilers?  As I recall, at least one of them fails without this (maybe Clang 9)?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo1OS9w7B2nYo90I6o4:b74wmev) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
>  I meant "typical case where this function is unused by users of the header"

I see, thanks for the explanation.

> As I recall, at least one of them fails without this (maybe Clang 9)?

You are right. Clang 9 doesn't like that incomplete type.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0JhsIC2Hg21r-E3CA:-Mo1ckm80bDjx1FS-zMN:b-4etn23) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I have a few Anzu PRs in flight that should be merged prior to this.
</blockquote></details>

(In particular, 7994 and 8018.)

---

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:
+(status: do not merge) pending Anzu PRs 7994 and 8018 mentioned below.

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057#-:-Mo4kmL24JEMsuVvxBxT:b-kqhunl)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: labeled "do not merge" (waiting on @sherm1 and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0JhsIC2Hg21r-E3CA:-Mo5UWvh9t7hFaClDthK:b-1zsgnw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(In particular, 7994 and 8018.)
</blockquote></details>

The Anzu PRs have all merged now, so -(status: do not merge) .

---
___
*[common/yaml/yaml_read_archive.h, line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16057#-Mo0xLEp7clmi4p5JjMt:-Mo5Xc8s7TAZLzxkWv-e:bmkw2yj) ([raw file](https://github.com/robotlocomotion/drake/blob/4f8eab4b4f7374950292987bf1cdfc6db6b86f21/common/yaml/yaml_read_archive.h#L507)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

>  I meant "typical case where this function is unused by users of the header"

I see, thanks for the explanation.

> As I recall, at least one of them fails without this (maybe Clang 9)?

You are right. Clang 9 doesn't like that incomplete type.
</blockquote></details>

I've clarified the comment.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16057)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
