### PR TITLE
Improve accuracy of prereq tickets in MbP

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2980 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O-xrgZnBELiEF1Lmjb2:-O-xrgZo13fKySHS_u6F:b9zo4s1) ([raw file](https://github.com/RobotLocomotion/drake/blob/561da607cbfe2e7a1c679a23cbca0b676e597ffd/multibody/plant/multibody_plant.cc#L2980)):*
> ```cpp
> 
>   // State ticket.
>   const systems::DependencyTicket state_ticket =
> ```

BTW One more thing you could do to help out my PR train -- add `using systems::DependencyTicket;` atop the file and remove the namespace prefix from the handful of places it's used in this file.  My branch has a _lot_ more uses of this, and fighting merge conflicts with it being present-vs-missing in master and different branches is no fun.



_Code quote:_
```cpp
systems::DependencyTicket
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2980 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O-xrgZnBELiEF1Lmjb2:-O0BHwsF19_8NVcUwqu8:bh9d6cs) ([raw file](https://github.com/RobotLocomotion/drake/blob/561da607cbfe2e7a1c679a23cbca0b676e597ffd/multibody/plant/multibody_plant.cc#L2980)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW One more thing you could do to help out my PR train -- add `using systems::DependencyTicket;` atop the file and remove the namespace prefix from the handful of places it's used in this file.  My branch has a _lot_ more uses of this, and fighting merge conflicts with it being present-vs-missing in master and different branches is no fun.
</blockquote></details>

Working

**Comment by jwnimmer-tri** [comment]
Also, I'm happy to coordinate the merge train.  I can pause merging my refactoring PRs that touch this file while this one is underway.

**Review by xuchenhan-tri — COMMENTED** [review]
ok, thanks. I'll work on getting this PR to reviewable form when #21590 lands.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-:-O0BuUGMCy__UoClChlk:b4031kd)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/plant/multibody_plant.cc` line 3213 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0Buev12uiyrovgTcMm:-O0Buev12uiyrovgTcMn:bnglka5) ([raw file](https://github.com/RobotLocomotion/drake/blob/561da607cbfe2e7a1c679a23cbca0b676e597ffd/multibody/plant/multibody_plant.cc#L3213)):*
> ```cpp
>   // Contact results output port.
>   std::set<systems::DependencyTicket> contact_results_prerequisites = {
>       state_ticket, get_geometry_query_input_port().ticket()};
> ```

check if all input ports and parameters are needed for continuous.

**Comment by jwnimmer-tri** [comment]
Thanks!  Possibly https://github.com/RobotLocomotion/drake/pull/21609 goes in first, too.  That one and this one won't fight a _lot_ on merge conflicts, but probably might fight a _little_.  We can see tomorrow.

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +(release notes: fix) 
+@sherm1 for feature review please. This is a follow up to #21590, but instead of targeting just MbTS, this PR aims to audit every output port and cache entry in the MbP system.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-:-O0HIKk2-9gEflLDq5AV:bnptlad)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.cc` line 2980 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O-xrgZnBELiEF1Lmjb2:-O0Gan2a21y5daidKMjI:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/561da607cbfe2e7a1c679a23cbca0b676e597ffd/multibody/plant/multibody_plant.cc#L2980)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few minor comments.
Would be nice to verify that this doesn't noticeably affect runtime. There are a few tickets that weren't there before (like "time") which could conceivably cause invalidations that weren't there before either.

> Reviewed 4 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-:-O0LaojWB6AUBG50MwCY:b-6811xf)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/plant/discrete_update_manager.cc` line 92 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0KsRi50A6UUPcVMvmL:-O0KsRi62B32RaH-V05d:b-qa2ua4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/discrete_update_manager.cc#L92)):*
> ```cpp
>       // ContactSolverResults include contribution from force elements, which
>       // could involve user-injected dependencies. So we need to include all
>       // possible tickets that users can choose to depend on.
> ```

BTW would be helpful to have the first of these TODOs say why we can't just add that dependency ticket now.
___
*[`multibody/plant/multibody_plant.cc` line 3254 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0L_iUM5M-2gT6HnLgo:-O0L_iUM5M-2gT6HnLgp:b-ngsoth) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/multibody_plant.cc#L3254)):*
> ```cpp
>             &MultibodyPlant<T>::CalcHydroelasticContactForcesContinuous,
>             // Compliant contact forces due to hydroelastics with Hunt &
>             // Crosseley are function of the kinematic variables q & v only.
> ```

typo: Crosseley -> Crossley
___
*[`multibody/plant/multibody_plant.cc` line 3267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0La1n0BOcnCwvVa8bn:-O0La1n12_j2_uKPWlC5:b-wj2zc8) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/multibody_plant.cc#L3267)):*
> ```cpp
>         &MultibodyPlant<T>::CalcContactResultsContinuous,
>         {state_ticket, this->all_parameters_ticket(),
>          get_geometry_query_input_port().ticket()});
> ```

BTW previously this depended on hydroelastic_contact_forces_continuous ticket also. Is that not needed now?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 4 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0PJTNo2K1ykXWARUMB:-O0PJTNp2I6b8ckla0rL:b9p8qnl) (no related file):*
> Would be nice to verify that this doesn't noticeably affect runtime. There are a few tickets that weren't there before (like "time") which could conceivably cause invalidations that weren't there before either.

The "time" is only from user-supplied force elements, right?  Possibly we should add the time ticket if and only if the user has added  force elements to the plant.

Though given that even springs are modeled as force elements, maybe we should fix ForceElement to declare `is_time_dependent()` as a constructor argrument, and then we can be precise.

___

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 4 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0PJTNo2K1ykXWARUMB:-O0PLODPDdqHrPZhtXQV:b5sn1ct) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Would be nice to verify that this doesn't noticeably affect runtime. There are a few tickets that weren't there before (like "time") which could conceivably cause invalidations that weren't there before either.

The "time" is only from user-supplied force elements, right?  Possibly we should add the time ticket if and only if the user has added  force elements to the plant.

Though given that even springs are modeled as force elements, maybe we should fix ForceElement to declare `is_time_dependent()` as a constructor argrument, and then we can be precise.
</blockquote></details>

My expectation is that the dependence on time doesn't actually cause any unwanted evaluations (since everything else changes with time also). So I wouldn't advocate any optimizations here unless we can show they matter.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 3 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0PJTNo2K1ykXWARUMB:-O0PM-VeAcZMnjn4FmH3:b-ra74ya) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My expectation is that the dependence on time doesn't actually cause any unwanted evaluations (since everything else changes with time also). So I wouldn't advocate any optimizations here unless we can show they matter.
</blockquote></details>

Fine by me.

___

**Review by xuchenhan-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per rotation please (if there's still time).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-:-O0QVLJ929xV-226o_Ie:b2yf6on)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/plant/discrete_update_manager.cc` line 92 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0KsRi50A6UUPcVMvmL:-O0QUt3qBvHH96K9AUiT:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/discrete_update_manager.cc#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would be helpful to have the first of these TODOs say why we can't just add that dependency ticket now.
</blockquote></details>

Done
___
*[`multibody/plant/multibody_plant.cc` line 3254 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0L_iUM5M-2gT6HnLgo:-O0QTQUC8ATl1slj5MhX:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/multibody_plant.cc#L3254)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: Crosseley -> Crossley
</blockquote></details>

Done
___
*[`multibody/plant/multibody_plant.cc` line 3267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0La1n0BOcnCwvVa8bn:-O0QTamhE_eGgsPOcUAM:b1g2g4u) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/multibody_plant.cc#L3267)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW previously this depended on hydroelastic_contact_forces_continuous ticket also. Is that not needed now?
</blockquote></details>

The current set of tickets should cover all contact results, including point contact, hydro, and deformable contact.

If you look at the dependency tickets of `hydroelastic_contact_forces_continuous`, it's exactly the same set.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with small nit on spelling of tickets for user input forces

> Reviewed 2 of 9 files at r2, 3 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-:-O0QY_YN500C1QXX_1DZ:bfve24b)* status: 2 unresolved discussions

___
*[`multibody/plant/discrete_update_manager.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QXtoc5uBj347p01dT:-O0QXtoc5uBj347p01dU:bcu5k91) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d95d7da914975f185401290e781eb329d0484b2/multibody/plant/discrete_update_manager.cc#L89)):*
> ```cpp
>       systems::ValueProducer(
>           this, &DiscreteUpdateManager<T>::CalcContactSolverResults),
>       // TODO(#20545): this should include all_input_ports_ticket, but we can't
> ```

nit (here and elsewhere) Why do we need `all_input_ports_ticket()` vs. something like `user_force_input_ports_ticket()`, if the goal is to be more precise?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 2 unresolved discussions

___
*[`multibody/plant/deformable_driver.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QZLtK6ecB_YtYyWE0:-O0QZLtK6ecB_YtYyWE1:bhg2fl6) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/deformable_driver.cc#L69)):*
> ```cpp
>   DRAKE_DEMAND(manager_ == manager);
>   const auto& deformable_contact_cache_entry = manager->DeclareCacheEntry(
>       "deformable contact data",
> ```

BTW did you intentionally remove this cache entry altogether?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 2 unresolved discussions

___
*[`multibody/plant/deformable_driver.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QZLtK6ecB_YtYyWE0:-O0Q_-fZ2sdQ6VdKC0P1:b-kiolaq) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/deformable_driver.cc#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW did you intentionally remove this cache entry altogether?
</blockquote></details>

Yes, this is intentional. It was done in https://github.com/RobotLocomotion/drake/pull/21619 and I'm rebasing this PR to resolve conflicts.
___
*[`multibody/plant/discrete_update_manager.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QXtoc5uBj347p01dT:-O0QZO0LDRofr_wSw-gK:b-a3q7kb) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d95d7da914975f185401290e781eb329d0484b2/multibody/plant/discrete_update_manager.cc#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and elsewhere) Why do we need `all_input_ports_ticket()` vs. something like `user_force_input_ports_ticket()`, if the goal is to be more precise?
</blockquote></details>

There's no such ticket just yet, but more importantly, this does depend on *all* input ports of MbP.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: 2 unresolved discussions

___
*[`multibody/plant/deformable_driver.cc` line 69 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QZLtK6ecB_YtYyWE0:-O0Q_9hO6Kh04G-iw8Dl:b-qk8xko) ([raw file](https://github.com/RobotLocomotion/drake/blob/d24ac03101ad9de3a39ebc1a9360f2fc6216a998/multibody/plant/deformable_driver.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes, this is intentional. It was done in https://github.com/RobotLocomotion/drake/pull/21619 and I'm rebasing this PR to resolve conflicts.
</blockquote></details>

To be clear, it's not removed, but moved to MbP instead.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/plant/discrete_update_manager.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21589#-O0QXtoc5uBj347p01dT:-O0QjBLu1Vd1dTmGNBb8:b-vmrj4e) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d95d7da914975f185401290e781eb329d0484b2/multibody/plant/discrete_update_manager.cc#L89)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There's no such ticket just yet, but more importantly, this does depend on *all* input ports of MbP.
</blockquote></details>

SGTM, thanks!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21589)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

**Pull request merged**
