### PR TITLE
Make symbolic::{Polynomial,Monomial} Eigen-compatible

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6558)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-:-KosQys4P9PyZHNNMeA-:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_polynomial_matrix_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KowSyHkGSGjGmjGIZJ2:-KowSyHkGSGjGmjGIZJ3:b-xmkotl) ([raw file](https://github.com/robotlocomotion/drake/blob/bbec4979e1c67d9b07bee997d1d291f2fe1effaa/drake/common/test/symbolic_polynomial_matrix_test.cc#L28)):*
> ```cpp
>   const Monomial m_z_{var_z_};
> 
>   MatrixX<Polynomial> M_poly_{2, 2};
> ```

Shall we also add fixed-size matrix?

---

*[drake/common/test/symbolic_polynomial_matrix_test.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KoxMXskaKs1nr6VJaRQ:-KoxMXskaKs1nr6VJaRR:b-qs08zo) ([raw file](https://github.com/robotlocomotion/drake/blob/bbec4979e1c67d9b07bee997d1d291f2fe1effaa/drake/common/test/symbolic_polynomial_matrix_test.cc#L86)):*
> ```cpp
> TEST_F(SymbolicPolynomialMatrixTest, PolynomialPolynomial) {
>   EXPECT_TRUE(CompareMatricesWithExpansion(
>       (M_poly_ + M_poly_).cast<Expression>(),
> ```

M_poly_ + M_poly_ should already return a matrix of expressions? Why we need to call `cast<Expression>()` again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_polynomial_matrix_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KowSyHkGSGjGmjGIZJ2:-KoxOpoRcEEW5zc5o2Ln:bvsfhm) ([raw file](https://github.com/robotlocomotion/drake/blob/bbec4979e1c67d9b07bee997d1d291f2fe1effaa/drake/common/test/symbolic_polynomial_matrix_test.cc#L28)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Shall we also add fixed-size matrix?
</blockquote></details>

I'll add more test cases.

---

*[drake/common/test/symbolic_polynomial_matrix_test.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KoxMXskaKs1nr6VJaRQ:-KoxO-EYKhL5bAXwOcpa:b-ag5j3b) ([raw file](https://github.com/robotlocomotion/drake/blob/bbec4979e1c67d9b07bee997d1d291f2fe1effaa/drake/common/test/symbolic_polynomial_matrix_test.cc#L86)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

M_poly_ + M_poly_ should already return a matrix of expressions? Why we need to call `cast<Expression>()` again?
</blockquote></details>

`symbolic::Polynomial` is closed under addition, subtraction, and multiplication. As a result, `M_poly_ + M_poly_` is of `Eigen::Matrix<Polynomial>` not `Eigen::Matrix<Expression>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by soonho-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_polynomial_matrix_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KowSyHkGSGjGmjGIZJ2:-KoyQs8p3lHJb7d9mmc_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bbec4979e1c67d9b07bee997d1d291f2fe1effaa/drake/common/test/symbolic_polynomial_matrix_test.cc#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'll add more test cases.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review.

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-:-Koyg6aGFbV8vocI6ZPk:b-xrxq0n)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 3 of 7 files at r1, 3 of 4 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 181 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0mJ9DZ3ylWDWECjxy:-Kp0mJ9E-jG7ixrcizlr:b-obaw0c) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L181)):*
> ```objc
> }
> 
> /// Provides Matrix<Monomial> * Matrix<Monomial> => Matrix<Polynomial>
> ```

Unclear why this should yield `<Polynomial>` instead of `<Monomial>`.
Ditto for the other `non-Polynomial` specializations below.  Maybe its because BinaryOpTraits doesn't let us distinguish between the return types of `op*` and `op+`?

---

*[drake/common/symbolic_polynomial.h, line 181 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0oG0tLq3yzPzzSa-r:-Kp0oG0tLq3yzPzzSa-s:b5es1wk) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L181)):*
> ```objc
> }
> 
> /// Provides Matrix<Monomial> * Matrix<Monomial> => Matrix<Polynomial>
> ```

Please also explain why a user who only included `Eigen` and `symbolic_monomial.h` wouldn't be at risk by this overload being absent in their translation unit, but present in others' translation units, which later perhaps join together through some include path and alter the resulting type?

---

*[drake/common/symbolic_polynomial.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0n7xntWyy2WPOmDZS:-Kp0n7xoJATEGTvSl2_K:b-cdqu9x) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L231)):*
> ```objc
> operator*(const MatrixL& lhs, const MatrixR& rhs) {
>   return lhs.template cast<Polynomial>() * rhs.template cast<Polynomial>();
> }
> ```

FYI Does `foo.template cast<Polynomial>()` compile down into a no-op if `foo` is already of type `Matrix<Polynomial>`?  In other words, is it possible to make all of the functions bodies here identical?

If so, consider reworking the above to reduce duplication, either through a preprocessor macro, or else widening the `enable_if` to cover all of MatrixL/MatrixR variations in a single function.

---

*[drake/common/symbolic_polynomial.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0nmmCtFYPRjQvAAwO:-Kp0nmmCtFYPRjQvAAwP:b-bdjewd) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L231)):*
> ```objc
> operator*(const MatrixL& lhs, const MatrixR& rhs) {
>   return lhs.template cast<Polynomial>() * rhs.template cast<Polynomial>();
> }
> ```

FYI Consider also hiding this new code under `DRAKE_DOXYGEN_CXX`, replacing it with some simpler signature + Doxygen API comment that illustrates the conversions being supported.

---

*[drake/common/symbolic_polynomial.h, line 475 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0oYmj1UnTwMTRhm5B:-Kp0oYmkdu1EVeDf-bFH:bfr54sq) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L475)):*
> ```objc
>   enum { Defined = 1 };
>   typedef drake::symbolic::Polynomial ReturnType;
> };
> ```

This is really a whole lot of copypasta.  Would it truly not be better to use the preprocessor for this?

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-Kp0kYIYfiXlIoKwuCWP:bqwkowu) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
> ```objc
> }  // namespace internal
> }  // namespace Eigen
> #endif  // !defined(DRAKE_DOXYGEN_CXX)
> ```

There is an incredible amount of boilerplate in this file.  Feature review @hongkai-dai, did you programmatically confirm that all of these declarations were covered by a unit test, either by removing them one by one and ensuring something failed, or by looking through kcov report?  If not, please do so and report back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-:-Kp0osnTEuNf4_sfd2uB:by96gdd)*

**Comment by soonho-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 181 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0mJ9DZ3ylWDWECjxy:-Kp1c26cXLzlwY7IbXcL:b9063t0) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L181)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this should yield `<Polynomial>` instead of `<Monomial>`.
Ditto for the other `non-Polynomial` specializations below.  Maybe its because BinaryOpTraits doesn't let us distinguish between the return types of `op*` and `op+`?
</blockquote></details>

It's because Monomial is not closed under multiplication and addition. Note that it's not `Monomial * Monomial` but `Matrix<Monomial> * Matrix<Monomial>`.

---

*[drake/common/symbolic_polynomial.h, line 181 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0oG0tLq3yzPzzSa-r:-Kp1cLlGf9-DVG424Uji:b-tvj88p) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L181)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please also explain why a user who only included `Eigen` and `symbolic_monomial.h` wouldn't be at risk by this overload being absent in their translation unit, but present in others' translation units, which later perhaps join together through some include path and alter the resulting type?
</blockquote></details>

As discussed in f2f, I'll open another PR to provide a representative header (`symbolic.h`) and let users include that file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by soonho-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0n7xntWyy2WPOmDZS:-KpG15L9VPn3FkTEJIcR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L231)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Does `foo.template cast<Polynomial>()` compile down into a no-op if `foo` is already of type `Matrix<Polynomial>`?  In other words, is it possible to make all of the functions bodies here identical?

If so, consider reworking the above to reduce duplication, either through a preprocessor macro, or else widening the `enable_if` to cover all of MatrixL/MatrixR variations in a single function.
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 231 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0nmmCtFYPRjQvAAwO:-KpG24040KT-qKSN0tmR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L231)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider also hiding this new code under `DRAKE_DOXYGEN_CXX`, replacing it with some simpler signature + Doxygen API comment that illustrates the conversions being supported.
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 475 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0oYmj1UnTwMTRhm5B:-KpGM4qKWXSBMGboAdL4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L475)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is really a whole lot of copypasta.  Would it truly not be better to use the preprocessor for this?
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-KpGM96dxgjCkZLfoIaJ:b-snpgbx) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is an incredible amount of boilerplate in this file.  Feature review @hongkai-dai, did you programmatically confirm that all of these declarations were covered by a unit test, either by removing them one by one and ensuring something failed, or by looking through kcov report?  If not, please do so and report back.
</blockquote></details>

I've checked that `symbolic_polynomial.h` has 100% coverage in kcov.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-KpGhxxF5HmqWFnaWW1C:b-813fwp) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I've checked that `symbolic_polynomial.h` has 100% coverage in kcov.
</blockquote></details>

That makes me happy!  But I think a better process would be to have the feature reviewer affirm that coverage is OK.

---

*[drake/common/symbolic_polynomial.h, line 168 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KpGi_iAIoY6Io-SawVW:-KpGi_iB-Eveo4RpUAua:bowdig) ([raw file](https://github.com/robotlocomotion/drake/blob/74544928ea40452463754a2e35a3c67f6541386a/drake/common/symbolic_polynomial.h#L168)):*
> ```objc
>          std::is_same<typename MatrixR::Scalar, Monomial>::value ||
>          std::is_same<typename MatrixR::Scalar, double>::value) &&
>         // Exclude Polynomial x Polynomial case.
> ```

... because Eigen already handles it for us?  (Unclear here.)

---

*[drake/common/symbolic_polynomial.h, line 225 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KpGjJTfS5kuYd969RYr:-KpGjJTgk9p7VDCycoUK:b-yb4njv) ([raw file](https://github.com/robotlocomotion/drake/blob/74544928ea40452463754a2e35a3c67f6541386a/drake/common/symbolic_polynomial.h#L225)):*
> ```objc
>                                                      ResultType)       \
>   DRAKE_SYMBOLIC_SCALAR_BINARY_OP_TRAITS(                              \
>       LhsType, RhsType, internal::scalar_conj_product_op, ResultType)
> ```

FYI It seems to be like every use of any of the above four macros always uses all four of them.  For conciseness, perhaps they should just be one macro with all four Op specializations rolled into one?

(I guess at that point even consider folding _all_ the macros together and just duplicate the `struct ...` stuff within a single macro four times?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-:-KpGk9d7YB0yYGTx5fjr:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-KpGoPsAJjJ25K--eKcY:b-5q5ocs) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That makes me happy!  But I think a better process would be to have the feature reviewer affirm that coverage is OK.
</blockquote></details>

@hongkai-dai , could you check?

---

*[drake/common/symbolic_polynomial.h, line 168 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KpGi_iAIoY6Io-SawVW:-KpGnPy-Ky5K4OWW5BBX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74544928ea40452463754a2e35a3c67f6541386a/drake/common/symbolic_polynomial.h#L168)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... because Eigen already handles it for us?  (Unclear here.)
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 225 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-KpGjJTfS5kuYd969RYr:-KpGoKvzcUqDFw41dneX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74544928ea40452463754a2e35a3c67f6541386a/drake/common/symbolic_polynomial.h#L225)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It seems to be like every use of any of the above four macros always uses all four of them.  For conciseness, perhaps they should just be one macro with all four Op specializations rolled into one?

(I guess at that point even consider folding _all_ the macros together and just duplicate the `struct ...` stuff within a single macro four times?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-KpHZsu3_PMEo1jIyDIM:bp6x769) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai , could you check?
</blockquote></details>

1. It seems that our `kcov` setup is not working anymore with the latest `kcov`. @hongkai-dai and I had the same symptom. (0% coverage overall).



2. In OSX, `kcov` is still working. I took some screenshots.





The only uncovered part is the following (which is not introduced by this PR).



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.h, line 487 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-Kp0kYIYfiXlIoKwuCWO:-KpHbxvjuZHTRSw4j2hm:b4c2yr8) ([raw file](https://github.com/robotlocomotion/drake/blob/3f0f32e46f6dcb891adeba8543cece23920c768a/drake/common/symbolic_polynomial.h#L487)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

1. It seems that our `kcov` setup is not working anymore with the latest `kcov`. @hongkai-dai and I had the same symptom. (0% coverage overall).



2. In OSX, `kcov` is still working. I took some screenshots.





The only uncovered part is the following (which is not introduced by this PR).



</blockquote></details>

We've reported the problem to @rpoyner-tri. @hongkai-dai , could you resolve this thread based on my screenshots?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6558#-:-KpHcUkjElq6ibyJI5os:bnfp4nl)*

**Pull request merged**
