### PR TITLE
[workspace] Add boost_internal

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also add `com_github_nelhage_rules_boost_internal` for its BUILD file.

These two repositories are not enabled by default. They are only used when `--WITH_USD=ON` is enabled.

Towards #20898. Amends #20923.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-:-NrWQgBf79Tad8cnTyeO:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-:-Nraq86s8S7C3Njzk5RW:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-NrapG3Q8Gpcag9HET2G):*
nit I don't understand this statement. If I pull the branch and run `bazel fetch //...`, they certainly get fetched. Do you mean they only get built/used when USD is on?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-NrapG3Q8Gpcag9HET2G):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I don't understand this statement. If I pull the branch and run `bazel fetch //...`, they certainly get fetched. Do you mean they only get built/used when USD is on?
</blockquote></details>

The command `fetch` is a special, in the sense that it fetches the dependencies of _all configurations_.  The use case when you're about to go offline, e.g., airplane and want to have everything available locally, even as you change configs.  It's setting you up to be able to run `--WITH_USD={ON,OFF}` both ways, while you're on the flight.

For the normal use case, where users and developers only run `build //...` or `test //...`, the boost archive will be not downloaded (or unpacked, or ...).

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few comments
FYI I didn't see any explicit dependency on WITH_USD here. I presume that's handled automatically by some already-in-place code; just checking.

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-:-NrbrDVk-xUMoKphod3q:bbjdm3r)* status: 4 unresolved discussions

___
*[`tools/workspace/github.bzl` line 403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-Nrbmf7SExeH1wtI4fsh:-Nrbmf7SExeH1wtI4fsi:b-jjlq33) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f70028b6835cbc08d708ffaa9309e4c1c1a7999/tools/workspace/github.bzl#L403)):*
> ```Starlark
>         commit = None,
>         attachments = None,
>         strip_prefix = None,
> ```

BTW IIUC this performs double duty: (1) specifies that attachments are archives of some kind that need to have files extracted, and (2) provides a prefix to strip from the resulting file names. Of those I would think function (1) is the most significant but the name hides that. Consider something like `extract_and_strip_prefix` to make that clearer.
___
*[`tools/workspace/github.bzl` line 422 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-NrbpSjs7DRxjkMoO6u0:-NrbpSjs7DRxjkMoO6u1:b-gprs8z) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f70028b6835cbc08d708ffaa9309e4c1c1a7999/tools/workspace/github.bzl#L422)):*
> ```Starlark
>         attachments: required dict whose keys are the filenames (attachment
>             names) to download and values are the expected SHA-256 checksums.
>         strip_prefix: optional dict whose keys are the filenames and values
> ```

BTW is the filename key here the same as the filename mentioned two lines above? One is "filenames (attachment names)" and the other just "filenames" which made me think they were different. If they are the same (which I think now) it would be better to describe them identically (or have "strip_prefix" reference "attachment").
___
*[`tools/workspace/github.bzl` line 531 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-NrbnqjGEKXSHW8Sya7n:-NrbnqjGEKXSHW8Sya7o:b7t6wkb) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f70028b6835cbc08d708ffaa9309e4c1c1a7999/tools/workspace/github.bzl#L531)):*
> ```Starlark
>             repository_ctx.download_and_extract(
>                 urls,
>                 stripPrefix = should_strip_prefix,
> ```

BTW here "stripPrefix" has only the obvious meaning but the name is nearly identical to "strip_prefix" above which carries the "extract" meaning as well -- I'd prefer more linguistic distance.
___
*[`tools/workspace/metadata.py` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-Nrbq6LL6eRV0JgkkEEJ:-Nrbq6LL6eRV0JgkkEEK:b6r2lrc) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f70028b6835cbc08d708ffaa9309e4c1c1a7999/tools/workspace/metadata.py#L46)):*
> ```Python
>         # see TODO in tools/workspace/rust_toolchain/repository.bzl.
>         repositories.add("bazel_skylib")
>         repositories.add("com_github_nelhage_rules_boost_internal")
> ```

BTW (just pattern matching here) you added two repositories but only mention one here. I assume that's intentional but thought I should mention it.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21037)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

___
*[`tools/workspace/github.bzl` line 403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21037#-Nrbmf7SExeH1wtI4fsh:-Nrc6UqYEbhQ63aXdgT1:btgx1li) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f70028b6835cbc08d708ffaa9309e4c1c1a7999/tools/workspace/github.bzl#L403)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For utmost clarity, I've split the two concepts into distinct arguments now.
</blockquote></details>

Very nice -- thanks!

**Pull request merged**
