### PR TITLE
Use quoted includes for pybind11

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #8137. Needs a fix to IBEX to totally resolve that issue, but this not going to break anything if it goes in prior to that.

FYI @jwnimmer-tri @soonho-tri @EricCousineau-TRI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8146)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
FWIW I have tested locally on Mac with Homebrew pybind11 installed and manually fixed up `pkg-config` files for CLP, CoinUtils, dReal, and IBEX.

**Comment by EricCousineau-TRI** [comment]
Using quoted includes for an upstream dependency makes me sad... Is there any simple way to tell Bazel how to prioritize includes? (I'm guessing no, but I'll grasp at straws if possible...)

**Comment by jamiesnape** [comment]
Bazel considers these local since it builds them itself, so they should be quoted, unfortunately.

**Comment by EricCousineau-TRI** [comment]
:panda:
It still seems like there should be some way in Bazel to prefer one include directory over the other (which is understandably difficult with `depset` stuff). Should we create an upstream issue?

**Comment by jamiesnape** [comment]
It goes against the Google way of going things. You could probably hack something it, but it goes against the idea of having a single monolithic workspace for everything.

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
:lgtm:

FWIW, I've fixed coin-or formulas and am building bottles for them. Will move to ibex/dreal after then.

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8146#-:-L5zuHfTIzMXrSzu64vH:buyzucg)*

**Comment by soonho-tri** [comment]
+@ericcousineau-tri can we have your platform blessing on this?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8146#-:-L5zxErLAZM0SFxrVtUl:b-jg65cm)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8146#-:-L60FaFnad1hbQDx3_al:bpqxd5f)*

**Pull request merged**
