### PR TITLE
Fix RenderEngineVtk upside down glTF textures

### LINKED ISSUE #20081: RenderEngineVtk applies textures upside down for glTF files
### What happened?

The initial implementation of glTF support for `RenderEngineVtk` revealed an inexplicable bug: textures would be applied upside down. This was initially [reported to VTK](https://discourse.vtk.org/t/vtkgltfimporter-loads-textures-upside-down/12113). Further probing revealed that the defect wasn't necessarily in `vtkGLTFImporter`, but it is the use of `vtkAssembly` that seems to be the most direct cause of the phenomenon. The specific *reason* is unclear, but given that `vtkAssembly` seems to be an incomplete concept in VTK, removing its usage will at least resolve the proximal cause.

See the linked VTK discussion for the details of the bug and its analysis.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
It has been shown that vtkAssembly leads to textures being rendered upside down. See
https://discourse.vtk.org/t/vtkgltfimporter-loads-textures-upside-down/12113 The fix we're applying is to get in front of of that and flip the textures ourselves when importing the glTF.

This PR further modifies rainbow_box.gltf so that its texture is no longer vertically symmetric (therefore the GltfSupport test now tests whether the texture is flipped or not).

It also provides a novel glTF file that contains all texture types and some instructions for doing a visual check on whether the flipping code works as advertised.

Resolves #20081

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
To the reviewer:

The function added in `internal_render_engine_vtk.cc` has some instructions for testing the texture flipping. Invoke:

```bash
     bazel run //tools:model_visualizer  -- --show_rgbd_sensor \
         package://drake/examples/scene_graph/fully_textured_pyramid.sdf
```

On master (with the `fully_textured_pyramid.sdf` file), doing this would produce the following image (once you've manipulated the camera a bit):



This PR should produce an image akin to:

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review. I'd appreciate particular response on where I could/should dump `fully_texture_pyramid.*`. I wanted it some place I could reference via `package://drake/...` and dumping it in `examples/scene_graph` was convenient but ill-disciplined. Most of the other files of that ilk have been dumped into `test` directories and are only available via absolute path when running `model_visualizer`.

I've also considered creating a unit test specifically where I dump the .glTF file (without sdf) in a test directory, but I include a rendered image that I *expect* to produce and simply compare the rendered image with the expected image. I'd welcome any thoughts.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nczcx7NCsGr0soQRDBq:bn5s53r)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd0r5SL6kSf07le0aVv:-Nd1WUHf3X-XXBxf5L8s:b-vh0dpp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I'd appreciate particular response on where I could/should dump `fully_texture_pyramid.*`.

Here's a patch to add the geometry render test meshes to model_visualizer:

https://github.com/RobotLocomotion/drake/pull/20091

Does it seem useful?  (If so, you could feature-review it.)

> I've also considered creating a unit test specifically where I dump the .glTF file (without sdf) in a test directory, but I include a rendered image that I _expect_ to produce and simply compare the rendered image with the expected image. I'd welcome any thoughts.

What's the hesitation about going this route?  Struggling with pixel-tolerance tests in CI?  It seems better than a manual test, assuming it doesn't take too much of an investment to create and maintain.
</blockquote></details>

I just hate putting images into unit tests. That said, it'd be better to nail the behavior down that way. So, I've updated the tests.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/BUILD.bazel` line 120 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd2FF-N1CRCIcJScvMO:-Nd2FF-N1CRCIcJScvMP:byx2u9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d81c91f6038bd263963d7c9090b19559f20d43c/geometry/render_vtk/BUILD.bazel#L120)):*
> ```Starlark
>         # We have disabled the test cases that fail on Mac Arm CI.
>         # TODO(#19424) Try to re-enable the tests.
>         "@platforms//cpu:arm64": [
> ```

BTW I think its fair to say the default behavior for VTK tests on ARM CI is to fail.

It's probably time we turn them all off by default here.  Or at most, opt-in to the few test cases that are just C++ API sanity checks (with no actual rendering).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd0r5SL6kSf07le0aVv:-Nd2HIQk1tMoBTa-7b_k:b-ds21lr) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I just hate putting images into unit tests. That said, it'd be better to nail the behavior down that way. So, I've updated the tests.
</blockquote></details>

Ok, adding the test isn't working. The xvfb is rendering a sufficiently different image that even with a permissive pixel tolerance (2)  the images don't match. I'll take one more stab at figuring out what is *actually* going on there to decide if it's worth trying. At the least, setting it to manual might be the easiest way out.

Thoughts?

___
___
*[`geometry/render_vtk/BUILD.bazel` line 120 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd2FF-N1CRCIcJScvMO:-Nd2H9w94fwdEODKEPFE:b-7m8umj) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d81c91f6038bd263963d7c9090b19559f20d43c/geometry/render_vtk/BUILD.bazel#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think its fair to say the default behavior for VTK tests on ARM CI is to fail.

It's probably time we turn them all off by default here.  Or at most, opt-in to the few test cases that are just C++ API sanity checks (with no actual rendering).
</blockquote></details>

I'm open to that. I think there's something nice about adding a new test and having to add it here so that the author of the test *knows* that it's omitted from ARM CI.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd0r5SL6kSf07le0aVv:-Nd2J81NA7uEPQnPRHRY:bfz5wzl) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ok, adding the test isn't working. The xvfb is rendering a sufficiently different image that even with a permissive pixel tolerance (2)  the images don't match. I'll take one more stab at figuring out what is *actually* going on there to decide if it's worth trying. At the least, setting it to manual might be the easiest way out.

Thoughts?
</blockquote></details>

Check out `integration_test.py` in the glTF client tests.  The assertions it does are like "80% of the pixels are within +/- 20 (out of 255) of their golden value.  That papers over some unimportant differences (like which exact pixel a mesh edge rounded off to), while still catching grossly-wrong results.  I would hope that such a test would still flag an upside-down image.

___
___
*[`geometry/render_vtk/BUILD.bazel` line 120 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd2FF-N1CRCIcJScvMO:-Nd2Iq_t5_ku9ODlt0Ha:b-643rc) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d81c91f6038bd263963d7c9090b19559f20d43c/geometry/render_vtk/BUILD.bazel#L120)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm open to that. I think there's something nice about adding a new test and having to add it here so that the author of the test *knows* that it's omitted from ARM CI.
</blockquote></details>

The hazard is if they don't _know_ that ARM CI is broken-by-default, and so they try to invest their time in trying to fix their code (which is impossible, since it's CI that's broken, not their code).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd0r5SL6kSf07le0aVv:-Nd5taHI1BodDmO_tFrc:b-ezsjlz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Check out `integration_test.py` in the glTF client tests.  The assertions it does are like "80% of the pixels are within +/- 20 (out of 255) of their golden value.  That papers over some unimportant differences (like which exact pixel a mesh edge rounded off to), while still catching grossly-wrong results.  I would hope that such a test would still flag an upside-down image.
</blockquote></details>

That rubric seems to pass locally via `xvfb-run`. I have high hopes that it should work on CI now.

___
___
*[`geometry/render_vtk/BUILD.bazel` line 120 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd2FF-N1CRCIcJScvMO:-Nd5tPSx1hEKRLs2cUA3:b-bz22gf) ([raw file](https://github.com/RobotLocomotion/drake/blob/2d81c91f6038bd263963d7c9090b19559f20d43c/geometry/render_vtk/BUILD.bazel#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The hazard is if they don't _know_ that ARM CI is broken-by-default, and so they try to invest their time in trying to fix their code (which is impossible, since it's CI that's broken, not their code).
</blockquote></details>

I'm certainly sympathetic with that having fallen exactly into that trap. But now I consider it to be useful information. But, like I said, I'm open to reversing the semantics.

**Comment by jwnimmer-tri** [comment]
The `macOS-arm-...` is happy now.  Let's check x86 as well:

@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
The [mac x86 CI build](https://drake-jenkins.csail.mit.edu/job/mac-x86-monterey-clang-bazel-experimental-release/74/) seems unrelated to this PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7-M407zxj-eS4LNl8:b-39ckd1)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7-bnR1nTwSqIwIU3g:bppyoqq)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
I am unable to run either
```
bazel run //tools:model_visualizer  -- --show_rgbd_sensor 
  package://drake/examples/scene_graph/fully_textured_pyramid.sdf
```
(from above instruction) or switching to
```
package://drake/geometry/render/test/meshes/fully_textured_pyramid.sdf
```
from what I understood of your f2f comment. In either case I get an error like:
```
... _model_visualizer.py", line 242, in AddModels
    self._builder.parser().AddModels(**kwargs)
RuntimeError: error: URI 'package://drake/geometry/render/test/meshes/fully_textured_pyramid.sdf' resolved to '/home/sherm/.cache/bazel/_bazel_sherm/e6c506c79a0a2d8ce8be77e2bf55a048/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/visualization/model_visualizer.runfiles/drake/geometry/render/test/meshes/fully_textured_pyramid.sdf'
which does not exist.
```

Please advise.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7U3lN9kYubMtEhkh9:b8vcd52)* status: LGTM missing from assignee sherm1(platform)

**Comment by jwnimmer-tri** [comment]
Two problems:

(1) The sdf has a typo:

```patch
--- a/geometry/render/test/meshes/fully_textured_pyramid.sdf
+++ b/geometry/render/test/meshes/fully_textured_pyramid.sdf
@@ -6,7 +6,7 @@
       <visual name="visual">
         <geometry>
           <mesh>
-            <uri>package://drake/examples/scene_graph/fully_textured_pyramid.gltf</uri>
+            <uri>package://drake/geometry/render/test/meshes/fully_textured_pyramid.gltf</uri>
           </mesh>
         </geometry>
       </visual>
```

(2) The command line needs to say "private":
```
bazel run //tools:model_visualizer_private  -- --show_rgbd_sensor \
  package://drake/geometry/render/test/meshes/fully_textured_pyramid.sdf
```

**Review by sherm1 — COMMENTED** [review]
Platform pass done -- looks good but I'd like to do the visual inspection before affixing the stamp. How can I run that?

> Reviewed 2 of 6 files at r1, 5 of 7 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7YPOT-SNweP1kqdr9:bfhp37k)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1007 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd7Xu_48HS1KEk-VhkB:-Nd7Xu_48HS1KEk-VhkC:bu99gt5) ([raw file](https://github.com/RobotLocomotion/drake/blob/13f4c896d875aa17570ea10333716c81ddbebcdf/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1007)):*
> ```cpp
>   const auto differences =
>       (data_expected.cast<float>() - data2.cast<float>()).array().abs();
>   const int num_acceptable = (differences <= 20).count();
> ```

BTW I don't understand how this resolves to "³√20". Can you elaborate?
___
*[`geometry/render/test/meshes/fully_textured_pyramid.sdf` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd7WKql3IRsh3Lu8ptD:-Nd7WKqm8q_Slz97PHKp:b-fqc4qw) ([raw file](https://github.com/RobotLocomotion/drake/blob/13f4c896d875aa17570ea10333716c81ddbebcdf/geometry/render/test/meshes/fully_textured_pyramid.sdf#L9)):*
> ```
>         <geometry>
>           <mesh>
>             <uri>package://drake/examples/scene_graph/fully_textured_pyramid.gltf</uri>
> ```

BTW is this URI still correct? I see this file in the local directory but not in the one named here.

**Review by sherm1 — COMMENTED** [review]
Thanks, @jwnimmer-tri. With the typo & command fixed a window "Color image" popped up with this image:


It looks different in Meshcat though:


Are these the expected outcomes?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7Zl4VDf7TmhAC8iyo:b1mfy1o)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
If those images are right then platform :lgtm: pending:
- fix of the typo in the URI
- update of instructions on how to test

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-Nd7_s5_5LsCcePYZfZS:b-hdxa86)* status: 2 unresolved discussions

**Review by SeanCurtis-TRI — COMMENTED** [review]
Well, the "how to test" instructions are likewise stale because a specific unit test was added after those instructions were pulled out of the commit message. However, I'm glad you tried as it revealed a bug in the sdf (one masked by local environment).

As for the question on the images, the testing instructions did include an image of what things should look like. Clearly the expected image was unhelpful. I need to find out why it was so unhelpful so I can do it better in the future. How much of that was a domain knowledge thing, and how much is attributable to a poorly articulated piece of information?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-NdB3oTSBjr94i5p9xGd:bkqjrks)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1007 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-Nd7Xu_48HS1KEk-VhkB:-NdB6U_B93hLZyzKCX2y:bbzco7d) ([raw file](https://github.com/RobotLocomotion/drake/blob/13f4c896d875aa17570ea10333716c81ddbebcdf/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1007)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't understand how this resolves to "³√20". Can you elaborate?
</blockquote></details>

Done

The comment reflected my original plan for the test and didn't get updated when the test became more naive.

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW One of the long-lasting frustrations I have with Reviewable is the inability to edit the discussion text and have it appear in Reviewable. If you go to github's view of the PR, you'll find the instructions to the reviewer has been updated in place.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089#-:-NdB6pEgAOuHZfR0kH-F:b2r59bh)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20089)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Comment by sherm1** [comment]
> Clearly the expected image was unhelpful.

Not entirely -- I could tell that the image that popped up looked a lot like the repaired image you provided (other than camera angle). But when I ran the test it also output a link for Meshcat which I took to mean I should look there. That image looked reasonable but different and I had no guidance as to whether it was right.

> long-lasting frustrations I have with Reviewable is the inability to edit the discussion text

Me too.

**Comment by SeanCurtis-TRI** [comment]
Ah...so the missing domain knowledge is that I was simply using `model_visualizer` as the simplest tool at hand to quickly see how `RenderEngineVtk` sees the glTF file. The fact that it came along with `meshcat` was immaterial. But it wasn't *obviously* unimportant. I'll make note of that in the future.

Although, it's worth noting that meshcat had some token relevance: it provided the mechanism by which you could move the camera to change what you were seeing in the rendered image.

**Pull request merged**
