### PR TITLE
[pydrake] Add bindings for SharedPointerSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Requires:
- [x] #17260

No release notes, because this only contains bindings for a class that is also newly-added as of the same next release.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please?

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@rpoyner-tri for platform review per rotation (Tuesday)

Documentation question:  I'm assuming because the created `SharedPointerSystem` will be created with `Held` as `py::object`, that C++ code could never usefully call `get()` on a system created from python, and vice versa?  I think this is OK.  In practice, do we think that limitation will ever matter?  If so, should we document it?

> Reviewed 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264#-:-N3165PcDoPBcgLR7RLV:bx2befl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17264#-N31BVll60R8L8iA1LOz:-N31BVll60R8L8iA1LP-:bflyews) (no related file):*
> Documentation question:  I'm assuming because the created SharedPointerSystem will be created with Held as py::object, that C++ code could never usefully call get() on a system created from python, and vice versa?

Exactly so.

In the future we could imagine adding more code in order to support those use cases, but as of this API they could not work.

> I think this is OK.  In practice, do we think that limitation will ever matter?

I think probably not.  We don't have any calls to `get()` function at all anywhere, as best I can remember.  Certainly nothing beyond of the immediate moment where this class is first created.

> If so, should we document it?

I tried a few ideas about how to place this in the documentation.  It seems we don't have any good way to mark certain Doxygen paragraphs as "C++ only" vs "Python only".  I tried a few ways of writing it up with careful prose, but I didn't like any of them.  I ended up concluding that this function is is marked advanced, so if users struggle to use it, I'd not be surprised but would still be OK with it.

If you (or others here) can propose some patch where we comment about this, I am open to it.  I just couldn't come up with anything myself.

___

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17264#-N31BVll60R8L8iA1LOz:-N31EFFE38iXYgHC4cth:b-kboaod) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Documentation question:  I'm assuming because the created SharedPointerSystem will be created with Held as py::object, that C++ code could never usefully call get() on a system created from python, and vice versa?

Exactly so.

In the future we could imagine adding more code in order to support those use cases, but as of this API they could not work.

> I think this is OK.  In practice, do we think that limitation will ever matter?

I think probably not.  We don't have any calls to `get()` function at all anywhere, as best I can remember.  Certainly nothing beyond of the immediate moment where this class is first created.

> If so, should we document it?

I tried a few ideas about how to place this in the documentation.  It seems we don't have any good way to mark certain Doxygen paragraphs as "C++ only" vs "Python only".  I tried a few ways of writing it up with careful prose, but I didn't like any of them.  I ended up concluding that this function is is marked advanced, so if users struggle to use it, I'd not be surprised but would still be OK with it.

If you (or others here) can propose some patch where we comment about this, I am open to it.  I just couldn't come up with anything myself.
</blockquote></details>

ok, if you already tried some language I doubt I'll come up with anything better.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17264#-:-N3PgRM52dyp-0-WO6-l:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
