### PR TITLE
Decompose systems/analysis/BUILD into smaller targets.

### PR DESCRIPTION
**Pull request by david-german-tri**
@sherm1 for both levels of review, and a chance to see Bazel in action.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4503)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Friendly ping to @sherm1 - my request has greater legitimacy now that the current time rounds to Monday!

**Comment by sherm1** [comment]
(Sorry, I missed this somehow when you first posted it.) I see that you are listing dependencies explicitly -- does Bazel ensure somehow that the headers listed here are actually used and that no additional dependencies exist that didn't make it into the BUILD file? In any case, :lgtm: (feature & platform).

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4503#-:-KZDlVxD6LL04AGRYtdW:br4s6fx)*

**Comment by jwnimmer-tri** [comment]
> does Bazel ensure... that no additional dependencies exist that didn't make it into the BUILD file?

Yes.  If an item is missing from `deps`, the code being compiled will not have access to that unit, and so the build will fail.  It guarantees "sufficient deps".

> does Bazel ensure... that the headers listed here are actually used ... ?

No.  If you list extra `deps`, Bazel will happily add them into the compilation sandbox and let them go unused.  It does not guarantee "minimal deps".

**Pull request merged**
