### PR TITLE
Added syntactic sugar for variable step integration without simulation.

### PR DESCRIPTION
**Pull request by edrumwri**
Per request from Paul Mitiguy, this PR adds some syntactic sugar for facilitating variable step integration _without a simulator_.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5429)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 and +@soonho-tri for platform review and +@mitiguy for feature review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-:-Ke_qaNWKdDu95f2dTgh:b7hlvx5)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-:-KebUtptwFlNdgev2hDu:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm: with one BTW.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 373 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KeaHtwsH2XanvK-pjxk:-KeaHtwsH2XanvK-pjxl:b5a80r5) ([raw file](https://github.com/robotlocomotion/drake/blob/a2e846a051155647957ec788d6186e706a0628f0/drake/systems/analysis/integrator_base.h#L373)):*
> ```objc
>   ///       fixed step mode should use StepExactlyFixed().
>   /// @throws std::logic_error If the integrator has not been initialized or
>   ///                          boundary_dt is negative **or** if the integrator
> ```

BTW, can you double-check if it throws `std::logic_error` if `boundary_dt` is negative as stated here (and also below)? I think the program terminates due to `DRAKE_DEMAND` in `StepOnceAtMost`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-:-KebcFWQwjA8Ru59b_AT:b2cjle6)*

**Comment by edrumwri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 373 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KeaHtwsH2XanvK-pjxk:-KefDVbcjtXcYcAVLvn5:b-tg4jba) ([raw file](https://github.com/robotlocomotion/drake/blob/a2e846a051155647957ec788d6186e706a0628f0/drake/systems/analysis/integrator_base.h#L373)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can you double-check if it throws `std::logic_error` if `boundary_dt` is negative as stated here (and also below)? I think the program terminates due to `DRAKE_DEMAND` in `StepOnceAtMost`.
</blockquote></details>

Nice catch- it did indeed map to an assertion failure. StepOnceAtMost() now throws a logic_error() (as its signature states it would) if any of the dt's are not valid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429)*

**Comment by mitiguy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/analysis/integrator_base.h, line 366 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOqHZ4HZDW6dZlRwR9:-KfOqHZ4HZDW6dZlRwRA:bkhe2sq) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L366)):*
> ```objc
>   /// circumstances. This method is designed for integrator
>   /// users that do not wish to consider publishing or discontinuous,
>   /// mid-interval updates _and_ are using integrators with error control.
> ```

Please add description of @param boundary_dt.
Also, I think it helpful if boundary_dt can be 0.0, 
and the utility of this should be explained. 

---

*[drake/systems/analysis/integrator_base.h, line 384 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOpE2_RrpzRXw5cCWx:-KfOpE2aoOM-g9lVC0Ob:bj1tvwg) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L384)):*
> ```objc
>     const T inf = std::numeric_limits<double>::infinity();
>     T t_remaining = boundary_dt;
>     const T t_final = context.get_time() + t_remaining;
> ```

To avoid round-off problems, consider something like following:

  const epsilon_based_on_boundary_dt = 1.0E-11 * boundary_dt;
...
while( t_remaining > epsilon_based_on_boundary_dt  )

---

*[drake/systems/analysis/integrator_base.h, line 1273 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOs1HtJLy6qIbLU6xU:-KfOs1HtJLy6qIbLU6xV:bnulqnb) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L1273)):*
> ```objc
>   // Verify that update dt is positive.
>   if (update_dt <= 0.0)
>     throw std::logic_error("Update dt must be non-negative.");
> ```

I copied the following documentation from:
  StepResult StepOnceAtMost(const T& publish_dt, const T& update_dt,
                            const T& boundary_dt);

   * @param publish_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next publish will occur.
   * @param update_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next update will occur.
   * @param boundary_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) marking the end of the user-designated
   *        simulated interval.

It seems as if update_dt is documented as allowing == 0 above,
but the above test is not consistent with this.

Also, regardless of what is intended, the message in the logic_error is unclear to me.
It seems as if the line should be:
  if (update_dt <= 0.0)
    throw std::logic_error("Update dt is negative or zero.");

---

*[drake/systems/analysis/test/explicit_euler_integrator_test.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOtOaM60NokBrkMejJ:-KfOtOaM60NokBrkMejK:b-i7ftx1) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/test/explicit_euler_integrator_test.cc#L71)):*
> ```cpp
> 
>   EXPECT_NO_THROW(integrator.StepOnceAtMost(dt, dt, dt));
>   EXPECT_THROW(integrator.StepOnceAtMost(dt, 0.0, dt), std::logic_error);
> ```

From the documentation from:
  StepResult StepOnceAtMost(const T& publish_dt, const T& update_dt,  const T& boundary_dt);

   * @param update_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next update will occur.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429)*

**Comment by edrumwri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/analysis/integrator_base.h, line 366 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOqHZ4HZDW6dZlRwR9:-KfUzzXrNutqu0rdpTDg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L366)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Please add description of @param boundary_dt.
Also, I think it helpful if boundary_dt can be 0.0, 
and the utility of this should be explained. 
</blockquote></details>

Done.

---

*[drake/systems/analysis/integrator_base.h, line 384 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOpE2_RrpzRXw5cCWx:-KfTpxqyfZtDNFAWMmvA:b985z0e) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L384)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

To avoid round-off problems, consider something like following:

  const epsilon_based_on_boundary_dt = 1.0E-11 * boundary_dt;
...
while( t_remaining > epsilon_based_on_boundary_dt  )
</blockquote></details>

I had to look at this one carefully. A unit test, `MagDisparity` in `runge_kutta3_integrator_test.cc` illustrates that this is not a problem. I also put some documentation in here to describe why this code is not problematic.

---

*[drake/systems/analysis/integrator_base.h, line 1273 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOs1HtJLy6qIbLU6xU:-KfV-4YnsgQDnPMXCycC:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/integrator_base.h#L1273)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

I copied the following documentation from:
  StepResult StepOnceAtMost(const T& publish_dt, const T& update_dt,
                            const T& boundary_dt);

   * @param publish_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next publish will occur.
   * @param update_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next update will occur.
   * @param boundary_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) marking the end of the user-designated
   *        simulated interval.

It seems as if update_dt is documented as allowing == 0 above,
but the above test is not consistent with this.

Also, regardless of what is intended, the message in the logic_error is unclear to me.
It seems as if the line should be:
  if (update_dt <= 0.0)
    throw std::logic_error("Update dt is negative or zero.");
</blockquote></details>

PTAL.

---

*[drake/systems/analysis/test/explicit_euler_integrator_test.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-KfOtOaM60NokBrkMejJ:-KfV-749JP6H6wevMBgI:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/6432b73519af694c99e1a844da37247e175bb439/drake/systems/analysis/test/explicit_euler_integrator_test.cc#L71)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

From the documentation from:
  StepResult StepOnceAtMost(const T& publish_dt, const T& update_dt,  const T& boundary_dt);

   * @param update_dt The step size, >= 0.0 (exception will be thrown
   *        if this is not the case) at which the next update will occur.
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429)*

**Comment by mitiguy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5429#-:-Kfmv-1Cw7J37cLwUzWs:bnfp4nl)*

**Pull request merged**
