### PR TITLE
Fix the mac failure on rotation_constraint_tighten2

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5587)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-KfngiMV2MCfaMjleO1t:b-ixi1zj)*

**Comment by hongkai-dai** [comment]
+@liangfok for both review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-KfngmyIQd5nY5bR_0p6:b9yjtur)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-KfniJFziJSDZY_V01GC:b-ixvtlv)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-Kfnn2RVmR1Smv5cbsZ6:b-ixvtlv)*

**Comment by liangfok** [comment]
:lgtm:

+@david-german-tri for platform review please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-KfnoZL_MpqikdY8Ulfx:buftkvp)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5587#-:-KfqFHltaTyzVBDwi_Z9:bnfp4nl)*

**Pull request merged**
