### PR TITLE
multibody: Deprecate public version of MBT headers

### LINKED ISSUE #9366: multibody: Make API distinctions clearer between MBT and MPB
At present, there are significant bits of the `MultibodyTree` API that are manually forwarded into the `MultibodyPlant` API as sugar. However, this introduces coupling and some confusion as to what *really* belongs where, and what the concrete responsibilities are for each API. (Is MBT really just for kinematics and dynamics? What if an external contributor decides to PR unique functionality to MBP?)

Per f2f with @amcastro-tri, this coupling was initially offered as sugar methods; however, as I've been binding stuff in Python, it's been a bit confusing to know what duplicates I should bind and test.

While it's true that copy and pasting APIs and docstrings are kind of low-effort, it makes testing (for proper code coverage, which we really should go for?), maintenance, and in general high-level explanations much more annoying and boilerplate-y.

My vote is to deprecate *all* of `MultibodyPlant`s forwarding of the `MultibodyTree` API, and simplify things once and for all.

\cc @amcastro-tri @sherm1 @RussTedrake @sammy-tri @jwnimmer-tri 

---

Given my current travel, I'd like to suggest these updated steps / timelines:

- [x] (Dec. ~9~ ~11~ 13) Forward relevant methods (w/ Python bindings) *
  - [x] #10128
  - [x] #10197
  - [x] #10212 CalcInverseDynamics, other bits
- [x] #10199 (Dec. ~12~ 13) Move `MultibodyTree` to `internal::MultibodyTree`, make alias
- [x] #10252 (Dec. ~14~ 17) Move other classes that do not need to be public into `internal`:
   - `MultibodyTreeSystem`, all cache objects, `BodyNodeIndex`, `Mobilizer` stuff, `MultibodyTreeTopology`, `MultibodyTreeContext`
- [x] (~Dec. 20~ Jan. 5?) Deprecate aliases.
- ~#10380 (Jan. 10) Shuffle headers to `internal/`~

\* We have a TRI-only document (search for "Drake Issue 9366") for methods that we want to migrate; I can share this publicly if anyone outside of TRI requests it.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9366 - may just close this PR - see below.

Poor man's deprecation - not splitting `BUILD` files for, to keep the diffs simple.

Hacky perl pie: [dir](https://github.com/EricCousineau-TRI/drake/tree/9b72c6ae6ad3c2ea18070953f8d49d0c05896925/tmp)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10380)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Looking it over a bit more, it seems somewhat awkward.  In #9314 we worked on reducing the deep nesting, but this goes in the opposite direction and adds more nesting.  The single BUILD file is a bad smell, too -- I suspect trying to write two BUILD files would actually be challenging due to circular dependencies between the two folders, which to me suggests that they should stay in the same folder.  One folder (+ tests) per package is a great rule of thumb.

What's the overall motivation here?  Having the code in an `internal` namespace is at least a start on informing users what's public and what's not.  Is there some thought that in certain kinds of workflows that would not be obvious enough quickly enough to some users?

**Comment by EricCousineau-TRI** [comment]
Sorry - I had added the phrasing "Consider shuffling headers", and arbitrarily changed it to a concrete task ~3 weeks ago, but did not discuss / confirm what that would look like.

The goal was for consistency, and to better communicate what portion is `internal` from the top-level. However, yes, the symbols being in `internal::` make that apparent.

I'm totally fine with not shuffling the headers, leaving them as-is, and closing out #9366.

@sherm1 Would you be OK with this?
\cc @amcastro-tri

**Comment by EricCousineau-TRI** [comment]
(If you'd like, I can also offline the discussion from this issue.)

**Comment by sherm1** [comment]
Yes, I think it is better not to move the headers to `internal`. Thanks for all your work on #9366 Eric, I think you can close this PR and declare victory!

There is definitely more work to be done to clean up the MBP/MBT internals but I don't think any of it has to affect API users now that you've made it so they can do everything through MBP.

**Comment by EricCousineau-TRI** [comment]
Sweet, awesome!

**Pull request closed without merging**
