### PR TITLE
Extracts AddFlatTerrainToWorld() into a single shared source file.

### PR DESCRIPTION
**Pull request by liangfok**
As enabled by the rule-of-three, this was being used by automotive, iiwa, and quadrotor demos. It's also being used by another demo I'm working on that is a user of Drake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4056)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sherm1 for platform review please.

/CC: @naveenoid, @foehnph and @sammy-tri since I believe I touched your code.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-:-KW-9sj0kVpFllWRh55P:bu7tzhb)*

**Comment by liangfok** [comment]
This PR passed https://github.com//RobotLocomotion/drake/pull/4056/commit/67345fc69e6a95e0766f1516be2672dedf00f4d4/show_partial?partial=commit%2Fpull_condensed and is thus ready for review.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-:-KW-hMTqws9nPrZUKXX2:b-4wylkm)*

**Comment by jwnimmer-tri** [comment]
Feature :lgtm:.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-:-KW-oiuUm4wYpWalBvaN:b-37uu31)*

**Comment by sherm1** [comment]
Platform :lgtm: -- nice to see the duplicate code nuked. One BTW comment.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-KW3jqnpb1I4ZrvS2GM5:-KW3jqnqu4zrBdS__AZu:b-wrkxna) ([raw file](https://github.com/robotlocomotion/drake/blob/67345fc69e6a95e0766f1516be2672dedf00f4d4/drake/examples/kuka_iiwa_arm/iiwa_common.h#L14)):*
> ```objc
>  * Aborts if the tree isn't as expected.
>  */
> DRAKE_EXPORT
> ```

BTW, can this macro be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-:-KW3k34gU1VWuepcTYH1:bav4iq5)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4056#-KW3jqnpb1I4ZrvS2GM5:-KW3lb3U6EtdGVTDNPee:b6b6fg6) ([raw file](https://github.com/robotlocomotion/drake/blob/67345fc69e6a95e0766f1516be2672dedf00f4d4/drake/examples/kuka_iiwa_arm/iiwa_common.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, can this macro be removed?
</details>
Yes. I believe @jwnimmer-tri is submitting a bunch of PRs that remove these export macros. I'll let that change be in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4056)*

**Pull request merged**
