### PR TITLE
Add lint tests for MEX code

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7422)

### CODE REVIEW

**Comment by fbudin69500** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7422)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7422#-:-KzOtCMqPwvISmAZz6wJ:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7422#-:-KzPMRtgdVlGWF_sozkH:bq11ftp)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7422#-:-KzPPLhigOwefzHegD14:bnfp4nl)*

**Pull request merged**
