### PR TITLE
[fem] Move IsoparametricElement out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503#-:-Mfih5rkCQjHpN5Zu2Pq:bwshpyi)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: .
+@ericcousineau-tri for platform review please (tomorrow)

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503#-:-MfivsAa3EEYOJZwsW3W:b-2gw07z)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
BTW, @ericcousineau-tri since this is moving out of dev/, please make sure to review the new files under `multibody/fem/` in their entirety, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503#-:-MfiwMGp4gsuuas6nfKR:b-fwp7vc)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with one nit on a minor Eigen thing

(also, merge conflict)

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503#-:-MfndS721pFyCcCkZiDG:bv548rc)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_simplex_element.cc, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15503#-Mfnc8HS1Sx9zi-eFDpM:-Mfnc8HS1Sx9zi-eFDpN:b-8zntq) ([raw file](https://github.com/robotlocomotion/drake/blob/04786d69937fbd363603d1dd2b21e855a1c314e2/multibody/fem/linear_simplex_element.cc#L101)):*
> ```cpp
>     }
>     /* S₀ = 1−ξ₀ − ... − ξₙ₋₂. */
>     Sq(0) = 0;
> ```

nit This is a little distracting for this summation.

Can you instead do something like this?
```
Sq(0) = 1 - Sq.tail<num_nodes - 1>().sum()
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[multibody/fem/linear_simplex_element.cc, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15503#-Mfnc8HS1Sx9zi-eFDpM:-MfnxMxc-46vohpdDD10:b9fkm92) ([raw file](https://github.com/robotlocomotion/drake/blob/04786d69937fbd363603d1dd2b21e855a1c314e2/multibody/fem/linear_simplex_element.cc#L101)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is a little distracting for this summation.

Can you instead do something like this?
```
Sq(0) = 1 - Sq.tail<num_nodes - 1>().sum()
```
</blockquote></details>

Unfortunately, this won't compile... I think the type alias `VectorNumNodes` is confusing the compiler.

OTOH
```
Sq(0) = 1 - Sq.tail(num_nodes - 1).sum();
```
is not ideal but does work.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)* status: 1 unresolved discussion (waiting on @amcastro-tri, @EricCousineau-TRI, and @xuchenhan-tri)

___
*[multibody/fem/linear_simplex_element.cc, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15503#-Mfnc8HS1Sx9zi-eFDpM:-Mfnyuct3eCs4Ns4Pv-D:be4p0h4) ([raw file](https://github.com/robotlocomotion/drake/blob/04786d69937fbd363603d1dd2b21e855a1c314e2/multibody/fem/linear_simplex_element.cc#L101)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Unfortunately, this won't compile... I think the type alias `VectorNumNodes` is confusing the compiler.

OTOH
```
Sq(0) = 1 - Sq.tail(num_nodes - 1).sum();
```
is not ideal but does work.
</blockquote></details>

Yeah, that seems way less ideal from runtime perspective.

Sorry for not catching this, but b/c it's template-dependent, I guess you needed `template` (as below, e.g. `CalcGradientInParentCoordinates` :sweat_smile: - sorry!)
```
Sq(0) = 1 - Sq.template tail<num_nodes - 1>().sum();
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)* status: 1 unresolved discussion (waiting on @amcastro-tri, @EricCousineau-TRI, and @xuchenhan-tri)

___
*[multibody/fem/linear_simplex_element.cc, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15503#-Mfnc8HS1Sx9zi-eFDpM:-Mfo0I5D-HD5rhNX6Qhe:b-x9a6aq) ([raw file](https://github.com/robotlocomotion/drake/blob/04786d69937fbd363603d1dd2b21e855a1c314e2/multibody/fem/linear_simplex_element.cc#L101)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, that seems way less ideal from runtime perspective.

Sorry for not catching this, but b/c it's template-dependent, I guess you needed `template` (as below, e.g. `CalcGradientInParentCoordinates` :sweat_smile: - sorry!)
```
Sq(0) = 1 - Sq.template tail<num_nodes - 1>().sum();
```
</blockquote></details>

(and yeah, the compiler errors didn't help either!!!)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)* status: 1 unresolved discussion (waiting on @amcastro-tri, @EricCousineau-TRI, and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15503)* status: 1 unresolved discussion (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[multibody/fem/linear_simplex_element.cc, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15503#-Mfnc8HS1Sx9zi-eFDpM:-Mfo0XWQ4QxbcaD0tTmb:b-qxsty5) ([raw file](https://github.com/robotlocomotion/drake/blob/04786d69937fbd363603d1dd2b21e855a1c314e2/multibody/fem/linear_simplex_element.cc#L101)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(and yeah, the compiler errors didn't help either!!!)
</blockquote></details>

Of course... Thanks for the reminder!

**Pull request merged**
