### PR TITLE
Make CI builds more verbose

### LINKED ISSUE #1919: CI Servers Should Save Verbose Output
Can the CI servers use "make VERBOSE=true" so we know exactly what compiler / linker commands are being executed?

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #1919.

### CODE REVIEW

**Comment by jhoare** [comment]
FYI Travis has a restriction of 4mb maximum log size. For some testing on another PR I needed more verbose output and changed ``make`` to ``make VERBOSE=1`` and it died partway through because I hit the 4MB limit.  Does the output from the CI here look as expected? It looks less verbose than a ``make VERBOSE=1`` would be at least.

**Comment by jamiesnape** [comment]
I doubt the verbose flag is being passed down through the many pod wrappers.

**Comment by jhoare** [comment]
Fair enough. So my word of caution would be once they are being passed down, travis will likely stop building successfully, because of the 4MB log limit.

**Comment by jamiesnape** [comment]
Sure. Travis CI will be switched off as soon as I can get the OS X builds running, so if it becomes an issue, I will delay until then.

**Comment by jwnimmer-tri** [comment]
+1 (review complete).

**Comment by jamiesnape** [comment]
Merge conflict resolved.

**Comment by jamiesnape** [comment]
retest this please

**Pull request merged**
