### PR TITLE
Convert MultilayerPerceptron benchmark to googlebench

### PR DESCRIPTION
**Pull request by RussTedrake**
+@jwnimmer-tri for feature review, please.

Towards #17515.

(Note: we will squash-merge this once it's ready.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`systems/benchmarking/BUILD.bazel` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd8W_64SZglZhkDkXF:-NNd8W_64SZglZhkDkXG:b-3smv1i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/BUILD.bazel#L3)):*
> ```Starlark
> # -*- python -*-
> 
> load(
> ```

nit Unused `drake_cc_binary`.
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd91wM19VUGjOVtTEx:-NNd91wM19VUGjOVtTEy:b9btmq8) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L3)):*
> ```cpp
> /* @file
>  A simple binary to benchmark the performance of the MultilayerPerceptron.
>  Run this at the command line with, e.g.
> ```

nit The command line suggestion here is no longer correct.

I tried using `bazel run :multilayer_perceptron_experiment -- --output_dir=temptemp --sleep=2` but there didn't seem to be any way to change the `--batch_size` anymore in that spelling, but that's the spelling that gives cpu-locked reliable results.

At minimum, I think that means we should increase the default batch_size so that it's a little bit larger to match a more typical use?
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNdBam08lPIZQqNoxI_:-NNdBam08lPIZQqNoxIa:b-ncwfic) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L30)):*
> ```cpp
>   MultilayerPerceptronBenchmark() {
>     tools::performance::AddMinMaxStatistics(this);
> //    this->Unit(benchmark::kSecond);
> ```

nit Commented-out code.

It seems like defaulting to microseconds might work well, I don't think these measurements will typically be sub-microsecond.
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd9GGf8RRfL5CjIijF:-NNd9GGf8RRfL5CjIijG:b-x19isb) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L46)):*
> ```cpp
>   }
> 
>   const int num_inputs{10};
> ```

nit Member fields should end with an underscore, and be marked `protected:` access.

Ditto throughout.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`systems/benchmarking/BUILD.bazel` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd8W_64SZglZhkDkXF:-NNwpikL4Uiy2wFn-KXG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/BUILD.bazel#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused `drake_cc_binary`.
</blockquote></details>

Done.
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd91wM19VUGjOVtTEx:-NNwpkN47aWwblNqu69V:bxxav1t) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The command line suggestion here is no longer correct.

I tried using `bazel run :multilayer_perceptron_experiment -- --output_dir=temptemp --sleep=2` but there didn't seem to be any way to change the `--batch_size` anymore in that spelling, but that's the spelling that gives cpu-locked reliable results.

At minimum, I think that means we should increase the default batch_size so that it's a little bit larger to match a more typical use?
</blockquote></details>

Working

I'll fix my TODO below now, at which point I can also push useful instructions here as well.
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNdBam08lPIZQqNoxI_:-NNwptdZ5rc-AGvsU5sU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Commented-out code.

It seems like defaulting to microseconds might work well, I don't think these measurements will typically be sub-microsecond.
</blockquote></details>

Done.
___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd9GGf8RRfL5CjIijF:-NNwpuJk82sCxIicAK0N:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Member fields should end with an underscore, and be marked `protected:` access.

Ditto throughout.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: but needs co-feature review from you for my changes.

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-:-NNwxjb55kA7B5rnBupA:b-rc9c1t)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd91wM19VUGjOVtTEx:-NNwwrFu4ylhUDIsArVM:b-rhkrhf) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll fix my TODO below now, at which point I can also push useful instructions here as well.
</blockquote></details>

I've pushed my changes.  Please feature-review them to see if you like them.

In particular, please consider which exact dimensions (num_inputs, num_layers, width, num_outputs, batch_size) are the appropriate sets of values to optimize for.  If you have changes, you can just push them with new `->Args()` values.

The goal is that all scenarios you care about are covered by the benchmark cases, and every benchmark case is worthwhile to be optimizing for.  The output of this benchmark report on proposed changes will determine which ones we pursue.

**Review by RussTedrake — COMMENTED** [review]
Awesome.  Thanks @jwnimmer-tri .

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-:-NO5n5MvE4WChZSn0hMZ:b-tel1ly)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd91wM19VUGjOVtTEx:-NO5mtdZ4h-c7-4P0_lK:boe4bya) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I've pushed my changes.  Please feature-review them to see if you like them.

In particular, please consider which exact dimensions (num_inputs, num_layers, width, num_outputs, batch_size) are the appropriate sets of values to optimize for.  If you have changes, you can just push them with new `->Args()` values.

The goal is that all scenarios you care about are covered by the benchmark cases, and every benchmark case is worthwhile to be optimizing for.  The output of this benchmark report on proposed changes will determine which ones we pursue.
</blockquote></details>

These look excellent to me.  I've asked the question (about the most relevant parameters) to my students, too... and will finalize this after I give them a chance to respond.

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

+(priority: medium) 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-:-NO6HoeE9QW77KkkCPuX:b-o5gn0z)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @RussTedrake)

___
*[`systems/benchmarking/multilayer_perceptron_benchmark.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NNd91wM19VUGjOVtTEx:-NO6HcQl6OqEeY76aXW3:b-vfush4) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ce9ca1096a40f9645b7d8357c7220e2f59c32e0/systems/benchmarking/multilayer_perceptron_benchmark.cc#L3)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

These look excellent to me.  I've asked the question (about the most relevant parameters) to my students, too... and will finalize this after I give them a chance to respond.
</blockquote></details>

Thanks.  I'll let you dismiss this thread once you have responses you're happy with.

In the meantime I'll assign platform review since any more changes are likely to be minor & rote.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-:-NO7XdhZ66emN3XCd1K7:bnfp4nl)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NOAN4g2DLy3tdBn-9J-:-NOAQCaw9WokfkLFslqQ:b-b6t4pn) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Current PR commit message isn't very descriptive; be sure to set a new commit message when squashing.
</blockquote></details>

My plan is to use the PR title as the commit subject, with no body text.  LMK if you think that's insufficient.

___

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18744)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18744#-NOAN4g2DLy3tdBn-9J-:-NOARXkq9OX4muurhhbJ:b-xsp0ro) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My plan is to use the PR title as the commit subject, with no body text.  LMK if you think that's insufficient.
</blockquote></details>

Fine by me; I just would rather not have the cryptic "toward mumble" sneak through without some further explanation, and omitting it is a fine way to do that.

___

**Pull request merged**
