### PR TITLE
Remove more redundant CMake code

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4085)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: I'll take your word for it

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4085#-:-KW8WsjI0Az5pchJ0Lai:b3g0r5)*

**Comment by jamiesnape** [comment]
`egrep -r '(pods_get_config_path|pods_get_include_path|pods_get_models_path|pods_get_r_path|write_procman)' drake`

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4085#-:-KW8_uK-1NkRhLK9qSYW:bnfp4nl)*

**Pull request merged**
