### PR TITLE
Z1 Working temporary SHA1 until the models PR RobotLocomotion/models#26 is merged

### PR DESCRIPTION
**Pull request by siilats**
[Working temporary SHA1 until the models PR](https://github.com/RobotLocomotion/drake/commit/70d261608b0be14556a64495ee5ac3407a4088bf) https://github.com/RobotLocomotion/models/pull/26

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20288)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by siilats** [comment]
Any idea why cmake CI version works and bazel doesnt? Maybe there are instructions how to compile the wheels with bazel on mac m1? I failed, the clion bazel plugin is supposed to support M1 now according to docs, I think your bazel_wrapper doesnt...

**Comment by siilats** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release

**Comment by siilats** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release

**Comment by siilats** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release

**Comment by siilats** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release

**Comment by jwnimmer-tri** [comment]
I don't see a purpose to having both #20284 and #20288 pull requests open simultaneously.  (We can't accept #20284 unless and until it contains the `RobotLocomotion/models` sha bump as well.)  Please add the final commit from this PR back onto the original one in #20284, and we'll keep that one open. I'll close this pull request as a duplicate.

> Any idea why cmake CI version works and bazel doesn't?

The only errors I see in the Jenkins output are linter errors (i.e., code formatting).  The Jenkins output in most cases has command line suggestions for how to automatically fix things.  For example, this is part of the build console log:

```
[9:44:29 PM]  FAIL: //:py/bazel_buildifier (see /media/ephemeral0/ubuntu/workspace/linux-focal-clang-bazel-experimental-release/_bazel_ubuntu/cc74fae110fa1b94f51887a2d2ef1425/execroot/drake/bazel-out/k8-opt/testlogs/py/bazel_buildifier/test.log)
[9:44:29 PM]  INFO: From Testing //:py/bazel_buildifier:
[9:44:29 PM]  ==================== Test output for //:py/bazel_buildifier:
[9:44:29 PM]  ./BUILD.bazel # reformat
[9:44:29 PM]  ./BUILD.bazel # reformat
[9:44:29 PM]  ERROR: buildifier: the required formatting is incorrect
[9:44:29 PM]  ERROR: ./BUILD.bazel:1: error: the required formatting is incorrect
[9:44:29 PM]  ERROR: ./BUILD.bazel:1: note: fix via bazel-bin/tools/lint/buildifier ./BUILD.bazel
[9:44:29 PM]  ERROR: ./BUILD.bazel:1: note: if that program does not exist, you might need to compile it first: bazel build //tools/lint/...
[9:44:29 PM]  NOTE: see https://drake.mit.edu/bazel.html#buildifier
[9:44:29 PM]  ================================================================================
```

You can also see the lint errors locally by running `bazel test //... --config=lint`.  (Our CMake build only knows how to install Drake; it does not know how to run any tests or linters.)

**Pull request closed without merging**
