### PR TITLE
Port Cars vectors to use Vector2 APIs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Update lcm_vector_gen.py:
  - Remove drake::Vector concept and its storage (eigen_ctor, eigen_assignment, to_eigen, coord_namer); extend BasicStateAndOutputVector instead.
  - Switch accessors to use System2 APIs.
  - Typo fix on coordinate indices.
- Add System1Vector wrapper to convert Vector2 to Vector1 APIs.
- Replace system1_cars_vectors aliases with System1Vector wrappers around the newly-geneated code.
- Re-commit generated code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3165)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
When changing Cars code, do a sanity check of ROS build:
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3165#-:-KPOrH0rFNqdf9Rm0Maq:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3165#-:-KPP6dQ-VAh6UCYFErdz:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Heh, oops.  Oh well, it was probably fine.  I guess Continuous will tell us.

**Pull request merged**
