### PR TITLE
Hotfix to repair build failure caused by #14337

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14503)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@drake-jenkins-bot mac-catalina-clang-cmake-experimental-release please

**Comment by mpetersen94** [comment]
@SeanCurtis-TRI for review pending Mac success.

If this passes I will add a follow up PR that tests the different flavors of PiecewiseQuaternion.

**Review by SeanCurtis-TRI — COMMENTED** [review]
On the basis that this makes the mac happy, :LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14503#-:-MQSv1E342g62N88l59g:b-78hvpt)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14503#-:-MQSv5M90yz9vzgLYaWN:b49u381)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

The `ComputeInterpTime` is great: `T`-valued functions should always use ADL for scalar binops.

The `is_approx` change makes no sense at all, but whatever.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14503#-:-MQSwQQd59SNakG8sJLx:b9y2ssr)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by SeanCurtis-TRI** [comment]
Good point. I glossed over `is_approx` too quickly.

**Pull request merged**
