### PR TITLE
[planning] Opt-in to clang-format lint

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See #18175 for prior art.  That PR has a long explanation for the motivation here.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri and +@SeanCurtis-TRI for all reviews, please.

\CC @rpoyner-tri you're invited to opt-in to review if you'd like to.

(I'll keep this as "do not merge" for now, since we'll need to ensure we rendezvous with any other planning-related PRs so we don't get merge conflicts or linter failures.)

**Review by calderpg-tri — COMMENTED** [review]
Autoformating is where the world is going :shrug:. As a general note, I don't get why some cases end up condensed to one line, while others get expanded. E.g.
- constructors with empty bodies get `{}` expanded to multiple lines
- many (all?) one-line lambdas get expanded to multiple lines
- basic getters get condensed to one line

Is there a way to make `clang-format` be more consistent on these?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-:-NNDkest6yoSj1e31bDw:b-9edjbd)* status: LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
I'll check.  (See below for tracking thread.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-:-NNDpB_M0UUqC5EU1e0c:babefyu)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNDp--A49hb-Wu9Gd-9:bciw71m) (no related file):*
Working

>  I don't get why some cases end up condensed to one line, while others get expanded, e.g.,
>
>*   constructors with empty bodies get {} expanded to multiple lines
>*    many (all?) one-line lambdas get expanded to multiple lines
>*    basic getters get condensed to one line
>
> Is there a way to make clang-format be more consistent on these?

I'll investigate.  Opening a discussion thread here so it doesn't get lost.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNEb5pW5MhiYxRDeMt3:b-ag6myx) (no related file):*
> constructors with empty bodies get {} expanded to multiple lines
> basic getters get condensed to one line

These two fall under the same option: [AllowShortFunctionsOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortfunctionsonasingleline).

We had it set to `InlineOnly`, but I just tried `Inline` and it seems better (or at least, not worse) so I've updated to that now in r2.  Now constructors and getters are consistent in that they are both smooshed.

> many (all?) one-line lambdas get expanded to multiple lines

This is [AllowShortLambdasOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortlambdasonasingleline).

We have it set to `Empty` so any non-empty lamba gets its at least line for the function body now.

In some of these cases here it is probably not required to use a full line for readability (e.g., the `return 0.0` one), in some cases I 
think it's a slight improvement.

However, the major reason I used `Empty` is that if I set it to `Inline` or `All` then it goes to extreme lengths to try to smoosh things onto one line that are totally unreadable when formatted that way, and we'd need to add line-breaking comments in a lot of places to fight with it.  My thought is that eating a little bit of unnecessary space for trivial lambdas was an OK tradeoff versus making non-trivial lambdas worse.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done -- I've picked up the conversation in the thread.

Generally, as is, I'd consider it to be a net improvement over the previous state. Although, there are a couple of cases where I wouldn't choose it. However, the question of single-line "functions" is still one of interest to me.

> Reviewed 14 of 21 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-:-NNHnLiaDA9vKdpnHiUl:bhqrvk5)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNHm1JR7RBDf0UKMyrU:b-fguyoz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> constructors with empty bodies get {} expanded to multiple lines
> basic getters get condensed to one line

These two fall under the same option: [AllowShortFunctionsOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortfunctionsonasingleline).

We had it set to `InlineOnly`, but I just tried `Inline` and it seems better (or at least, not worse) so I've updated to that now in r2.  Now constructors and getters are consistent in that they are both smooshed.

> many (all?) one-line lambdas get expanded to multiple lines

This is [AllowShortLambdasOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortlambdasonasingleline).

We have it set to `Empty` so any non-empty lamba gets its at least line for the function body now.

In some of these cases here it is probably not required to use a full line for readability (e.g., the `return 0.0` one), in some cases I 
think it's a slight improvement.

However, the major reason I used `Empty` is that if I set it to `Inline` or `All` then it goes to extreme lengths to try to smoosh things onto one line that are totally unreadable when formatted that way, and we'd need to add line-breaking comments in a lot of places to fight with it.  My thought is that eating a little bit of unnecessary space for trivial lambdas was an OK tradeoff versus making non-trivial lambdas worse.
</blockquote></details>

__re: functions__

Why  not `AllowShortFunctionsOnASingleLine: All`? The single-line free functions seem fine. The [examples](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortfunctionsonasingleline) don't conjure any boogeymen, so I assume you encountered a case that was bad? 

__re: lambdas__

I tried `All` and applied it only to `planning/` but didn't see anything which I felt had degraded readibility (a subjective measure, of course). Can you point to an example of such a case? Generally, my imagination fails to conjure the set of functions that 1) *Can* be defined on a single line but 2) *shouldn't* be for readability reasons.

In both cases, I *can* easily imagine that you were casting a wider net to assess the impact of these settings and what night become apparent in the scope of *this* PR is still something that would cause concern.

___
___
*[`planning/test/collision_checker_test.cc` line 565 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNHjrz0DpA4YFlgPRme:-NNHjrz0DpA4YFlgPRmf:b5mkoby) ([raw file](https://github.com/RobotLocomotion/drake/blob/a455cc9b6300df8a2b464f15b61033c2829cfef8/planning/test/collision_checker_test.cc#L565)):*
> ```cpp
>   };
> 
>   EXPECT_EQ(count_contexts(dut_.get()), dut_->num_allocated_contexts()
> ```

BTW This test would benefit from swapping from terminal comments to in-line comments. Like where you've done elsewhere, a change in formatting regimen invites a change in expression.

```c++
  EXPECT_EQ(count_contexts(dut_.get()),
            dut_->num_allocated_contexts() + 1 /* prototype context */);

  // Add one standalone context.
  auto context = dut_->MakeStandaloneModelContext();
  EXPECT_EQ(count_contexts(dut_.get()), dut_->num_allocated_contexts() +
                                            1 /* prototype context */ +
                                            1 /* standalone context */);

  auto cloned = dut_->Clone();
  EXPECT_NE(cloned, nullptr);
  EXPECT_EQ(count_contexts(cloned.get()),
            dut_->num_allocated_contexts() + 1 /* prototype context */ +
                0 /* standalone context has not been carried over */);

  context.reset();  // Give up our standalone context.
  EXPECT_EQ(count_contexts(dut_.get()),
            dut_->num_allocated_contexts() + 1 /* prototype context */;
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNHnriGDMwDogXwsgTa:bpqn2n8) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

__re: functions__

Why  not `AllowShortFunctionsOnASingleLine: All`? The single-line free functions seem fine. The [examples](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortfunctionsonasingleline) don't conjure any boogeymen, so I assume you encountered a case that was bad? 

__re: lambdas__

I tried `All` and applied it only to `planning/` but didn't see anything which I felt had degraded readibility (a subjective measure, of course). Can you point to an example of such a case? Generally, my imagination fails to conjure the set of functions that 1) *Can* be defined on a single line but 2) *shouldn't* be for readability reasons.

In both cases, I *can* easily imagine that you were casting a wider net to assess the impact of these settings and what night become apparent in the scope of *this* PR is still something that would cause concern.
</blockquote></details>

The only scope I'm considering is what `bazel test //... --config lint` covers.  Try changing the dotfile to a new proposal, then run the linter that way, correct its complaints, then look at the diffs.  (In short -- look at lcm + planning + visualization, the three directories currently covered as of this PR).

---

**re: functions** -- I have a miniscule personal preference for `*.cc` files to look like this:

```c++
std::string DrakeLcm::get_lcm_url() const {
  return impl_->lcm_url_;
}
```

instead of like this:

```c++
std::string DrakeLcm::get_lcm_url() const { return impl_->lcm_url_; }
```

However, I am very happy to switch to "All" though, if I'm outvoted.  I don't think it's a defectable degradation in readability.

\CC @sammy-tri in case you want to weigh in on this one.

---

**re: lambdas**

Some changes to `lcm/...` are fairly bad, I think.

In general, my premise goes like this -- a lot of lambdas have a return statement (i.e., usually they have return values instead of output arguments), and control flow should always appear on its own line.

___

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNHtsp_0EyDuw45yVQV:b-g9t4xy) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The only scope I'm considering is what `bazel test //... --config lint` covers.  Try changing the dotfile to a new proposal, then run the linter that way, correct its complaints, then look at the diffs.  (In short -- look at lcm + planning + visualization, the three directories currently covered as of this PR).

---

**re: functions** -- I have a miniscule personal preference for `*.cc` files to look like this:

```c++
std::string DrakeLcm::get_lcm_url() const {
  return impl_->lcm_url_;
}
```

instead of like this:

```c++
std::string DrakeLcm::get_lcm_url() const { return impl_->lcm_url_; }
```

However, I am very happy to switch to "All" though, if I'm outvoted.  I don't think it's a defectable degradation in readability.

\CC @sammy-tri in case you want to weigh in on this one.

---

**re: lambdas**

Some changes to `lcm/...` are fairly bad, I think.

In general, my premise goes like this -- a lot of lambdas have a return statement (i.e., usually they have return values instead of output arguments), and control flow should always appear on its own line.
</blockquote></details>

These people have a mighty restrictive interpretation of the word "allow" in that it's defined as "unconditionally cram down your throat."   I prefer the existing `InlineOnly` and `Empty`, but I wouldn't fight terribly hard against changing either one.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-:-NNI6CkBCq-GmDZYzYTL:bmxilld)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NNDp--A49hb-Wu9Gd-8:-NNI5rXx3mOSWgIdUvVv:b-6n7u2v) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

These people have a mighty restrictive interpretation of the word "allow" in that it's defined as "unconditionally cram down your throat."   I prefer the existing `InlineOnly` and `Empty`, but I wouldn't fight terribly hard against changing either one.
</blockquote></details>

@sammy-tri I agree 100% on the misuse of the word "allow". [You keep using that word...I do not think it means what you think it means.]

I'm content to mark myself as satisfied. 

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: LGTM missing from assignee calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 13 of 21 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: LGTM missing from assignee calderpg-tri, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri)

**Comment by jwnimmer-tri** [comment]
@calderpg-tri just waiting for your emoji, once you've had time to look.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: LGTM missing from assignee calderpg-tri, labeled "do not merge" (waiting on @calderpg-tri)

**Comment by jwnimmer-tri** [comment]
Switching -@calderpg-tri +@rpoyner-tri for review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending cruftectomy

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-:-NOGoqgxEPkIrztwMYkr:bqfhs9t)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`planning/test/scene_graph_collision_checker_test.cc` line 67 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NOGocnJ0K6F_gdqETU7:-NOGocnJ0K6F_gdqETU8:bgzk3t2) ([raw file](https://github.com/RobotLocomotion/drake/blob/54220f8319a2925cbcc6e5b5cf19103a7ae093ae/planning/test/scene_graph_collision_checker_test.cc#L67)):*
> ```cpp
>   RobotDiagramBuilder<double> builder;
>   const std::string model_data = R"""(
> >>>>>>> 80708e5025 ([planning] Opt-in to clang-format lint)
> ```

cruft? also below.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @rpoyner-tri)

___
*[`planning/test/scene_graph_collision_checker_test.cc` line 67 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18701#-NOGocnJ0K6F_gdqETU7:-NOGrMMb1J30hqVASfUp:brgef5l) ([raw file](https://github.com/RobotLocomotion/drake/blob/54220f8319a2925cbcc6e5b5cf19103a7ae093ae/planning/test/scene_graph_collision_checker_test.cc#L67)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

cruft? also below.
</blockquote></details>

Done.

TIL about emacs conflict resolution versus R-strings.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18701)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Pull request merged**
