### PR TITLE
[wheel] Use 'docker cp' (not tar) to extract wheels

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The tar pipe seems to spuriously fail (https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-release/105/) for unknown reasons.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
Hmm. It looks... maybe okay. I'm a bit worried as I seem to recall there was a reason I was trying to avoid `docker cp`. If necessary, I suppose we can merge this and hope it works, but I'm going to go see if there's any history there, and if the reason was something "worse" than "I don't want to create a container that needs to be reaped".

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-:-NY4r_uV9fs4B2XXPTvx:b6uju9x)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/wheel/wheel_builder/linux.py` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4qnc-7rFsY8CQqPFH:-NY4qnc-7rFsY8CQqPFI:bizxcqd) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L68)):*
> ```Python
>     """
>     Runs a docker command.
>     The stdout is passed through to the subprocess module.
> ```

FYI, "The value of \`\`stdout\`\` is passed..."? (I want to say we use backticks on param names in help strings, but maybe I'm making that up. Anyway, "value of" seems clearer.)

**Review by jwnimmer-tri — COMMENTED** [review]
Jenkins was happy with this, so it at least seems better than the status quo, even if we need to improve it later on.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-:-NY4uGzSDi9UQFciekDy:bboxz0b)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/wheel/wheel_builder/linux.py` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4qnc-7rFsY8CQqPFH:-NY4uSQ4-o0_Z1SyFXYv:b-hcebbh) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L68)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, "The value of \`\`stdout\`\` is passed..."? (I want to say we use backticks on param names in help strings, but maybe I'm making that up. Anyway, "value of" seems clearer.)
</blockquote></details>

Done.  (We seem to use single backticks in this file, shrug.)

**Review by mwoehlke-kitware — COMMENTED** [review]
It looks like this approach has been present since the first version of `build_wheels.sh`. Given that was bash and not Python, it _may_ be I just didn't want to deal with creating and needing to clean up a temporary container. Or, perhaps more likely, it would have been more of a pain to obtain the names of individual wheels to be copied out one at a time.

So, I guess :lgtm:...

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-:-NY4sMhu7AHdY4zsQpv2:b5tbzgw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/wheel/wheel_builder/linux.py` line 253 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4tfHv6NWi7v3NOFpf:-NY4tfHv6NWi7v3NOFpg:bbg7pw9) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L253)):*
> ```Python
>             assert len(wheel_paths) > 0
>             for container_path in wheel_paths:
>                 wheel_basename = pathlib.Path(container_path).name
> ```

FYI, I have a sneaking suspicion this is sub-optimal



_Suggestion:_
```Python
os.path.basename(container_path)
```
___
*[`tools/wheel/wheel_builder/linux.py` line 255 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4tylC07-HUYg6SDIO:-NY4tylC07-HUYg6SDIP:bwhbkho) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L255)):*
> ```Python
>                 wheel_basename = pathlib.Path(container_path).name
>                 _docker('cp', f'{container_name}:{container_path}',
>                         f'{options.output_dir}/{wheel_basename}')
> ```

FYI (pedantic):



_Suggestion:_
```Python
os.path.join(options.output_dir, wheel_basename)
```

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/wheel_builder/linux.py` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4qnc-7rFsY8CQqPFH:-NY4ufTn8l3ekCGs5l_B:b-q2t7kx) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  (We seem to use single backticks in this file, shrug.)
</blockquote></details>

Hehe, single, double, I wasn't sure and hadn't looked. :slightly_smiling_face: Let's not worry about it. In any case, thanks! :+1:

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/wheel_builder/linux.py` line 247 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4wDPP5RhDwvqz9KHt:-NY4wDPP5RhDwvqz9KHu:bkmm63q) ([raw file](https://github.com/RobotLocomotion/drake/blob/b4bde9560a065006bb2b973a6cdf39db8e9ec4eb/tools/wheel/wheel_builder/linux.py#L247)):*
> ```Python
>         container_name = f'{tag}.extract'.replace(':', '.')
>         completed_process = _docker('run', f'--name={container_name}', tag,
>                                     'bash', '-c', f'ls {wheelhouse}/*.whl',
> ```

FYI, if you _really_ want to be paranoid, `find -0` would be more robust. But probably overkill, it seems safe to assume there is no `\n` in the wheel names. If you're a _little_ paranoid, `ls -1` will ensure one file per line, though it's _probably_ safe to rely on `ls` recognizing that it isn't writing to a TTY and defaulting to that behavior.

IMHO it's probably safe to ignore this comment; I'm mostly pointing out the options in case you hadn't thought of them already.



_Suggestion:_
```Python
ls -1
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/wheel/wheel_builder/linux.py` line 253 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-NY4tfHv6NWi7v3NOFpf:-NY4vZcMDr1NeiX3uji5:b-1isw4u) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8f3fce01f3ae43aa6e327658a5b8ff38b74730/tools/wheel/wheel_builder/linux.py#L253)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, I have a sneaking suspicion this is sub-optimal
</blockquote></details>

New code in Drake should prefer the modern `pathlib` over the legacy `os.path`, but I suppose an emergency PR isn't the right time to start porting wheel tooling to the preferred API.  I've switched back to `os.path` for now.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19618#-:-NYBmRzU9QDAszdYPOZs:bcpz082)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Pull request merged**
