### PR TITLE
Geometric Jacobian for the world fix

### PR DESCRIPTION
**Pull request by amcastro-tri**
It fixes a simple bug in the computation for the geometric Jacobian when requested for the world frame (it should return a zero Jacobian!).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749#-:-LBaK3ZY4Hrskb1O27cj:bll7v0f)*

**Comment by avalenzu** [comment]
:lgtm: with a few BTWs on punctuation and word choice. +@soonho-tri for platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/multibody_tree.cc, line 739 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaMfG7BEXtbcqKmF1J:-LBaMfG7BEXtbcqKmF1K:baehkfj) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/multibody_tree.cc#L739)):*
> ```cpp
> 
>   // Do nothing for the world body and return a zero Jacobian.
>   // That is Jv_WQi * v = 0, always, for the world body.
> ```

BTW, insert comma after "That is".

---

*[multibody/multibody_tree/multibody_tree.cc, line 816 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaNKv7AjOrXT7SAQgl:-LBaNKv7AjOrXT7SAQgm:baehkfj) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/multibody_tree.cc#L816)):*
> ```cpp
> 
>   // Do nothing for the world body and return a zero Jacobian.
>   // That is Jv_WQi * v = 0, always, for the world body.
> ```

BTW, insert comma after "That is".

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 636 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaNhWJ8S6xLyNjVTgU:-LBaNhWJ8S6xLyNjVTgV:b2f5yw2) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/test/multibody_tree_test.cc#L636)):*
> ```cpp
> // Verify that even when the input set of points and/or the Jacobian might
> // contain garbage on input, a query for the world body Jacobian will always
> // return:
> ```

BTW s/return/yield the following results

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 672 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaO2Ss1iH8vzYi188U:-LBaO2Ss1iH8vzYi188V:b5kcexm) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/test/multibody_tree_test.cc#L672)):*
> ```cpp
> // return a zero Jacobian since the world does not move.
> TEST_F(KukaIiwaModelTests, FrameGeometricJacobianForTheWorldFrame) {
>   // Simply a non-zero point in the world body. The actual value does
> ```

BTW "Simply ..." is an incomplete sentence.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 679 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaOK-Z1bbjulBi7nN-:-LBaOK-Z1bbjulBi7nN0:blyivoc) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/test/multibody_tree_test.cc#L679)):*
> ```cpp
>   const int nv = model_->num_velocities();
> 
>   // We set the output Jacobian to garbage so that on output from
> ```

BTW s/on output from/upon returning from/

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaOZY67-1JeoyRSRnQ:-LBaOZY67-1JeoyRSRnR:bwr21l2) ([raw file](https://github.com/robotlocomotion/drake/blob/29283e2219accdb4c2f0411435b6a6020666f748/multibody/multibody_tree/test/multibody_tree_test.cc#L690)):*
> ```cpp
>       *context_, model_->world_body().body_frame(), p_WP, &Jv_WP);
> 
>   // Since in this case we are querying for the world frame the Jacobian should
> ```

BTW comma after "frame".

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749#-:-LBaOhe41N_I_QDk9aTZ:bx38isy)*

**Comment by soonho-tri** [comment]
:lgtm: (aside two minor issues in the tests)

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 665 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaXK1C7QnwCitxg8LY:-LBaXK1C7QnwCitxg8LZ:b-g7q7d9) ([raw file](https://github.com/robotlocomotion/drake/blob/4567544d6cbbb9731b5a6059ea37714a731cd806/multibody/multibody_tree/test/multibody_tree_test.cc#L665)):*
> ```cpp
>   //   b) the Jacobian should be exactly zero.
>   EXPECT_EQ(p_WP_out, p_WP_set);
>   EXPECT_EQ(Jv_WP, Matrix3X<double>::Zero(3 * npoints, nv));
> ```

It should be:
```c++
  EXPECT_EQ(Jv_WP, MatrixX<double>::Zero(3 * npoints, nv));
```
Otherwise, you will get:
```
Assertion failed: (v == T(Value)), function variable_if_dynamic, file external/eigen/Eigen/src/Core/util/XprHelper.h, line 110.
```

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaXSlnE1HB6D3nXsb8:-LBaXSlnE1HB6D3nXsb9:budevqd) ([raw file](https://github.com/robotlocomotion/drake/blob/4567544d6cbbb9731b5a6059ea37714a731cd806/multibody/multibody_tree/test/multibody_tree_test.cc#L692)):*
> ```cpp
>   // Since in this case we are querying for the world frame, the Jacobian should
>   // be exactly zero.
>   EXPECT_EQ(Jv_WP, Matrix3X<double>::Zero(6, nv));
> ```

Similarly, it should be:
```
  EXPECT_EQ(Jv_WP, MatrixX<double>::Zero(6, nv));
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749#-:-LBaX_of5RD69T3AH1Co:b-jxjy44)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 665 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8749#-LBaXK1C7QnwCitxg8LY:-LBab2isD_sQxUwBIEas:b-kl8g4c) ([raw file](https://github.com/robotlocomotion/drake/blob/4567544d6cbbb9731b5a6059ea37714a731cd806/multibody/multibody_tree/test/multibody_tree_test.cc#L665)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It should be:
```c++
  EXPECT_EQ(Jv_WP, MatrixX<double>::Zero(3 * npoints, nv));
```
Otherwise, you will get:
```
Assertion failed: (v == T(Value)), function variable_if_dynamic, file external/eigen/Eigen/src/Core/util/XprHelper.h, line 110.
```
</blockquote></details>

good catch!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8749)*

**Pull request merged**
