### PR TITLE
[doc] Remove official support of macOS 13 (Ventura)

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21978

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review. This should remove the remaining references to "Ventura" from drake's documentation. This PR can go in first, followed by the `drake-ci` and `drake-jenkins-jobs` changes to actually remove the jobs

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-:-O8cuv889AUFCzroNh_n:by3bltj)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
I would like to have Sequoia listed explicitly (but as "TBD") to make it clear it's on the way.  I pushed the patch for that.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-:-O8cw_FX2FV8ecMyFslL:b7r31zw)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

___
*[`doc/_pages/installation.md` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwdGx6JwOfcYRMwBa:-O8cwdGx6JwOfcYRMwBb:b-szqlbn) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/doc/_pages/installation.md#L26)):*
> ```Markdown
> | Ubuntu 22.04 LTS (Jammy Jellyfish) | x86_64       | 3.10 ⁽³⁾   | March 2026      |
> | Ubuntu 24.04 LTS (Noble Numbat)    | x86_64       | 3.12 ⁽³⁾   | March 2028      |
> | macOS Ventura (13)                 | arm64 ⁽⁵⁾    | 3.12 ⁽³⁾   | October 2024    |
> ```

Should we also remove the (5) note?
___
*[`tools/wheel/wheel_builder/macos.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwuOGEAKFuRkTQBYj:-O8cwuOGEAKFuRkTQBYk:bwk8qde) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/tools/wheel/wheel_builder/macos.py#L138)):*
> ```Python
> 
>     # Xcode updates may change the default -mmacosx-version-min when not
>     # specified.  For example, Xcode 14.1 on monterey (macOS 12.x) was using a
> ```

I'm not sure we should actually remove this, as it's part of the documentation why we're setting `MACOSX_DEPLOYMENT_TARGET`. Unless we remove that logic entirely. (Hopefully it isn't *needed* any more, though we might want to keep it for paranoia's sake.)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`tools/wheel/wheel_builder/macos.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwuOGEAKFuRkTQBYj:-O8cyCmm59ImT29Y2MHq:b-i3uden) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/tools/wheel/wheel_builder/macos.py#L138)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm not sure we should actually remove this, as it's part of the documentation why we're setting `MACOSX_DEPLOYMENT_TARGET`. Unless we remove that logic entirely. (Hopefully it isn't *needed* any more, though we might want to keep it for paranoia's sake.)
</blockquote></details>

I wasn't sure about this, it's slightly annoying noise when looking for ventura references... I'll put it back in

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`doc/_pages/installation.md` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwdGx6JwOfcYRMwBa:-O8czHy-5ZRlraofjhbd:b-6x3r2x) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/doc/_pages/installation.md#L26)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Should we also remove the (5) note?
</blockquote></details>

Maybe? Or as part of #19057?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

___
*[`doc/_pages/installation.md` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwdGx6JwOfcYRMwBa:-O8czPph5C5K_JKZcyG1:b-iaj7wj) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/doc/_pages/installation.md#L26)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Maybe? Or as part of #19057?
</blockquote></details>

I plan to ship one last x86_64 wheel (if I can) for next week's 1.34 release.  I will set myself a reminder in #21956 to adjust this documentation, so we can skip it as part of this review.
___
*[`tools/wheel/wheel_builder/macos.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwuOGEAKFuRkTQBYj:-O8cygKD7IltYTSZaJtm:byztw6d) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/tools/wheel/wheel_builder/macos.py#L138)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I wasn't sure about this, it's slightly annoying noise when looking for ventura references... I'll put it back in
</blockquote></details>

This sentence is just a "for example".  IMO the remaining text still provides a sufficient justification without the example.

I'm OK if you want to keep the for-example @mwoehlke-kitware but in that case please propose (here; or via git push) some specific wording that doesn't have false-positive grep hits for macOS version names and numbers that we are purging.  This matches Betsy's point that this text will keep causing us pain every fall when we grep for the verboten macOS words during an upgrade.

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`doc/_pages/installation.md` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwdGx6JwOfcYRMwBa:-O8go83cBsT5gThUKv7-:bb6mt9b) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/doc/_pages/installation.md#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I plan to ship one last x86_64 wheel (if I can) for next week's 1.34 release.  I will set myself a reminder in #21956 to adjust this documentation, so we can skip it as part of this review.
</blockquote></details>

:+1:
___
*[`tools/wheel/wheel_builder/macos.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwuOGEAKFuRkTQBYj:-O8gnX6O81yTUqAk4FwR:b-atr720) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/tools/wheel/wheel_builder/macos.py#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This sentence is just a "for example".  IMO the remaining text still provides a sufficient justification without the example.

I'm OK if you want to keep the for-example @mwoehlke-kitware but in that case please propose (here; or via git push) some specific wording that doesn't have false-positive grep hits for macOS version names and numbers that we are purging.  This matches Betsy's point that this text will keep causing us pain every fall when we grep for the verboten macOS words during an upgrade.
</blockquote></details>

Sure, I'm fine with being vague about the versions. The "goal" in my mind is rather to clarify what "may change the default -mmacosx-version-min" means, why we care, and that there is a history of this happening.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri.

Ping to @mwoehlke-kitware for final feature-LGTM.

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-:-O8msUu172-_AMIDuIEa:b-n682k9)* status: LGTM missing from assignee mwoehlke-kitware, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`tools/wheel/wheel_builder/macos.py` line 138 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-O8cwuOGEAKFuRkTQBYj:-O8msPtw3bFOxLMHLdyb:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ed564380b1907deb01dbd26ed9553463a66cf1d/tools/wheel/wheel_builder/macos.py#L138)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Sure, I'm fine with being vague about the versions. The "goal" in my mind is rather to clarify what "may change the default -mmacosx-version-min" means, why we care, and that there is a history of this happening.
</blockquote></details>

Done

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22004#-:-O8rmc3_BiMhmqjB57Uq:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Pull request merged**
