### PR TITLE
[setup] Prune some unused macOS dependencies

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
No need to tap 'robotlocomotion' anymore.
Switch 'cmake' to a source prereq.
Drop unused 'xz' (vestigial from VTK).
Drop unused 'yaml-cpp' (now built from source).
Drop unused 'zeromq' (vestigial from meshcat).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21454)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both(?) reviews, please.  I'm hoping that "CI is happy" plus the PR overview is enough context for you.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21454#-:-Nya5ZmH-B-TjROQWf9M:bv4ifto)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Pull request merged**
