### PR TITLE
Fix dare

### PR DESCRIPTION
**Pull request by hongkai-dai**
This essentially reopens the PR #11118, but the original author has deleted the WIP branch, so I re-open a new PR here.

I addressed the comment by Soonho on that PR. I was the feature review of the PR, but I have to admit I don't understand this PR, and I can't access the paper referenced by the PR (it is behind the paywall).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please. +@soonho-tri for platform review since you were the platform review for the original PR #11118 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865#-:-MXYjmgy7XdXtCgiH1hN:bp29mpb)* status: LGTM missing from assignees RussTedrake(platform),soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @soonho-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865#-:-MXiUwFFA4lLYboC8Hww:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @soonho-tri)

___
*[math/discrete_algebraic_riccati_equation.cc, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14865#-MXiUmHb13hK1Yzn3__h:-MXiUmHc4KoglXr_YY4v:bad67an) ([raw file](https://github.com/robotlocomotion/drake/blob/3eb585980e81424c890021254c040c4bccf676ff/math/discrete_algebraic_riccati_equation.cc#L316)):*
> ```cpp
>   int n = n2 / 2, p = 0, q = 0;
> 
>   // Find the first unstable p block.
> ```

nit: you left a comment about not understanding p block, etc on the original PR.  are you ok with it now?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @soonho-tri)

___
*[math/discrete_algebraic_riccati_equation.cc, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14865#-MXiUmHb13hK1Yzn3__h:-MXidh2E8bLUbP8nIRpz:bafavd3) ([raw file](https://github.com/robotlocomotion/drake/blob/3eb585980e81424c890021254c040c4bccf676ff/math/discrete_algebraic_riccati_equation.cc#L316)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: you left a comment about not understanding p block, etc on the original PR.  are you ok with it now? 
</blockquote></details>

Yes after re-reading the code I think I understand the meaning of each variable (from the documentation of this function).

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865#-:-MXlNufw8Qy2PIl7b4mb:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14865)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jamiesnape** [comment]
> I addressed the comment by Soonho on that PR

Does this need `Co-authored-by: ...` in the commit body. Was the change significant?

**Comment by hongkai-dai** [comment]
> > I addressed the comment by Soonho on that PR
> 
> Does this need `Co-authored-by: ...` in the commit body. Was the change significant?

Hi Jamie, the PR is primarily written by @weiqiao , I only made slight change. If I could I would mark Weiqiao as the primary author of this PR, but I don't know how to do that so the commit message only contains "Co-authored-by:". Does this make sense?

**Comment by jamiesnape** [comment]
You handled it correctly. The ordering (primary/secondary) of the authors is not significant as regards copyright in any case, so you as author and @weiqiao as co-author would be the same as @weiqiao as author and you as co-author.

**Pull request merged**
