### PR TITLE
Add more features to symbolic Variables class

### PR DESCRIPTION
**Pull request by soonho-tri**
This is a part of the commits that we're migrating from the SOS (sum-of-squares) sprint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6453)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@fischergundlach , feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-:-KnjdfL_7eVXYnwvDvy-:b-w98muk)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variables.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnjeAoF43WeIqiaUvvA:-KnjeAoF43WeIqiaUvvB:bos78b1) ([raw file](https://github.com/robotlocomotion/drake/blob/aad8bd2b1c877ad77587596d5fd2527649405daf/drake/common/symbolic_variables.h#L45)):*
> ```objc
> 
>   /** Constructs from an Eigen vector of variables. */
>   explicit Variables(const VectorX<Variable>& init);
> ```

Maybe better to use `const Eigen::Ref<const VectorX<Variable>& init` to accept more Eigen types?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variables.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnjeAoF43WeIqiaUvvA:-Knjg_4LzDQFPRh5-qmx:b-7lxq4r) ([raw file](https://github.com/robotlocomotion/drake/blob/aad8bd2b1c877ad77587596d5fd2527649405daf/drake/common/symbolic_variables.h#L45)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe better to use `const Eigen::Ref<const VectorX<Variable>& init` to accept more Eigen types?
</blockquote></details>

Done. Thanks for the point!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by FischerGundlach** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variables.cc, line 124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-Knk7jytjzNJwKBWwXIN:-Knk7jyuZLys4_Agp5d9:bwwru6i) ([raw file](https://github.com/robotlocomotion/drake/blob/5e40cdecc8f02301030feca115ace187a178b93a/drake/common/symbolic_variables.cc#L124)):*
> ```cpp
> }
> 
> Variables intersect(const Variables& vars1, const Variables& vars2) {
> ```

I wonder why we implement this rather than using the STL set_intersection? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variables.cc, line 124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-Knk7jytjzNJwKBWwXIN:-KnkNAdyKlloI4DTR9eP:b-azg4xr) ([raw file](https://github.com/robotlocomotion/drake/blob/5e40cdecc8f02301030feca115ace187a178b93a/drake/common/symbolic_variables.cc#L124)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

I wonder why we implement this rather than using the STL set_intersection? 
</blockquote></details>

It's more about usability. To use `set_intersection`, one should do:

```c++
const Variables vars1{x_, y_, z_, w_, v_};
const Variables vars2{x_, y_};

Variables var3;
std::set_intersection(vars1.begin(), vars1.end(), vars2.begin(), vars2.end(),
                      inserter(vars3, vars3.begin()), less<Variable>{});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please.

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_variables.cc, line 124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-Knk7jytjzNJwKBWwXIN:-Kno6u8qRbf7f6rq8Qc6:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/5e40cdecc8f02301030feca115ace187a178b93a/drake/common/symbolic_variables.cc#L124)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It's more about usability. To use `set_intersection`, one should do:

```c++
const Variables vars1{x_, y_, z_, w_, v_};
const Variables vars2{x_, y_};

Variables var3;
std::set_intersection(vars1.begin(), vars1.end(), vars2.begin(), vars2.end(),
                      inserter(vars3, vars3.begin()), less<Variable>{});
```
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-:-Kno7Qu446Nxs5hlBVx9:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , could you platform-review this? If you're too busy, please ping me.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-:-KnoGJxay3ccKsFoxumk:bkgwowf)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variables.h, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoJeZNi1Vw8YeJxaNd:-KnoJeZOelajQlGwcJ66:b-y730ke) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/symbolic_variables.h#L30)):*
> ```objc
> 
>   typedef typename drake::symbolic::Variable key_type;
>   typedef typename drake::symbolic::Variable value_type;
> ```

I don't understand what `key_type` vs `value_type` is supposed to mean.

---

*[drake/common/symbolic_variables.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoJDnpwuOyi7f03-i_:-KnoJDnpwuOyi7f03-ia:b-ugv27f) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/symbolic_variables.h#L31)):*
> ```objc
>   typedef typename drake::symbolic::Variable key_type;
>   typedef typename drake::symbolic::Variable value_type;
>   typedef typename std::set<key_type> set;
> ```

This ends up being a fairly confusing abbreviation in the below change (as well as for the pre-existing member field), because it appears as just a bare `set` which naively would appear to mean `std::set` as if someone did `using std::set`.

(It doesn't seem to be buying much, so maybe just remove it instead of renaming it?)

---

*[drake/common/test/symbolic_variables_test.cc, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoKUonW0DEf0F6XVjV:-KnoKUonW0DEf0F6XVjW:b9e0osm) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/test/symbolic_variables_test.cc#L24)):*
> ```cpp
> TEST_F(VariablesTest, ConstructFromVariableVector) {
>   const Eigen::Matrix<symbolic::Variable, 3, 1> v1(x_, y_, z_);
>   const Variables vars1(v1);  // vars1 = {x, y_, z}
> ```

BTW nit Inconsistent trailing underscore in comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-:-KnoKpBraueOwspvW0HA:bnfp4nl)*

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-:-KnoMw4xWMctrnRbS326:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_variables.h, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoJeZNi1Vw8YeJxaNd:-KnrQvhc83E3jar5DtPB:bw0fd2l) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/symbolic_variables.h#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand what `key_type` vs `value_type` is supposed to mean.
</blockquote></details>

Done. (removed)

FYI, I took them from http://en.cppreference.com/w/cpp/container/set.

---

*[drake/common/symbolic_variables.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoJDnpwuOyi7f03-i_:-KnrQw85XdQ5hNwKs44y:b2ar3so) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/symbolic_variables.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This ends up being a fairly confusing abbreviation in the below change (as well as for the pre-existing member field), because it appears as just a bare `set` which naively would appear to mean `std::set` as if someone did `using std::set`.

(It doesn't seem to be buying much, so maybe just remove it instead of renaming it?)
</blockquote></details>

Done. (removed)

---

*[drake/common/test/symbolic_variables_test.cc, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6453#-KnoKUonW0DEf0F6XVjV:-KnrR-RwqZQrr9kbP4Xx:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/c48fe198bb997460e8d6e1bde07324140bb89c1a/drake/common/test/symbolic_variables_test.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Inconsistent trailing underscore in comment.
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6453)*

**Pull request merged**
