### PR TITLE
Add tests on Binding with cost and evaluator.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8164)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-:-L65Ou8kyzU0ttbURoEG:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor discussion items.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/binding_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-L69faVxNDfBp94tR0vI:-L69faVyYN4s5RlQlMAv:b-ocazcx) ([raw file](https://github.com/robotlocomotion/drake/blob/fec338d74397d4f09944509375261e9801bd4a27/solvers/test/binding_test.cc#L15)):*
> ```cpp
> using drake::symbolic::test::VarEqual;
> 
> GTEST_TEST(TestBinding, constructBinding) {
> ```

Can you rename this to `TestConstraint`?

---

*[solvers/test/binding_test.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-L69foNZ7T6EkFWez7bG:-L69foNZ7T6EkFWez7bH:b-s0082r) ([raw file](https://github.com/robotlocomotion/drake/blob/fec338d74397d4f09944509375261e9801bd4a27/solvers/test/binding_test.cc#L81)):*
> ```cpp
> GTEST_TEST(TestBinding, TestEvaluator) {
>   // Tests binding with an evaluator.
>   symbolic::Variable x1("x1");
> ```

BTW Can these be made `const`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-:-L69fv6zqqEjhcW32VIm:b7xj22s)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/binding_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-L69faVxNDfBp94tR0vI:-L6AcI5fg6BMts3MD3GE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fec338d74397d4f09944509375261e9801bd4a27/solvers/test/binding_test.cc#L15)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you rename this to `TestConstraint`?
</blockquote></details>

Done.

---

*[solvers/test/binding_test.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-L69foNZ7T6EkFWez7bG:-L6AcIeI4r-n_3tAKc33:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fec338d74397d4f09944509375261e9801bd4a27/solvers/test/binding_test.cc#L81)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can these be made `const`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-:-L6AcliOWHy6IhYA03qV:b-qxjhdt)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-:-L6CTxvJn-Bob_SswA2-:b-kmrewj)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8164#-:-L6Ipsz5jgDYxnFpwbtv:b-l70wzf)*

**Pull request merged**
