### PR TITLE
Review and finalize the cache design document

### LINKED ISSUE #7681: Cache design doc needs review
PR #7674 added a draft of the caching system design and implementation doxygen document into Drake master so that it would be available during caching code review. The text needs to be updated along with the code review, and the "draft" warning removed.

Relates to #4364, #7668.

### PR DESCRIPTION
**Pull request by sherm1**
Per issue #7681 the cache design document in cache_doxygen.h needs to be reviewed to make sure it is up to date with the as-built cache system.

This PR removes the "unreviewed draft" warning at the top of the document, and contains detailed text about the handing of Diagram cache dependencies to address issue #9251.

Reorganizes Drake's "Modules" doxygen section somewhat. Recovers `multibody_doxygen.h` from the attic.

Resolves #7681.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9136)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
Oops.  I totally forgot to leave a marker here for me to return to the review.  I will finish this today.

**Comment by sherm1** [comment]
CI failure in Debug build seems to be caused by recent merge of: `multilane_loader_test.cc` (PR #9302)

**Comment by jwnimmer-tri** [comment]
I can use admin powers to force-merge this, if you like?

**Comment by sherm1** [comment]
Merging this doc-only PR anyway since CI failure is unrelated.

**Pull request merged**
