### PR TITLE
Throws exception in QpInverseDynamics if gurobi is not available.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Address #6986

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7046)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for feature review. thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7046#-:-KuLUQQhPd9GjjsUTnxR:b4k5yms)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7046#-:-KuLaAaUTrmtH0m-K0TZ:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for platform as well. thanks

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7046#-:-KuLetdQyPoHE5PWa7y8:b-6wy4p2)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: (for platform)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7046#-:-KuLf3OCCkAmh5mnCu2c:b-l1mmwq)*

**Pull request merged**
