### PR TITLE
[geometry] Move MakeRenderEngineGltfClient() from the dev folder

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@seancurtis-tri Can I ask for another feature review? Thanks!

\CC @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8WewhGBY3ym49NiZmi:b-ges147)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_gltf_client/factory.h` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8WfFk2ETU2qB85S6R0:-N8WfFk2ETU2qB85S6R1:b-l1m9x2) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L70)):*
> ```objc
>  [libcurl_cleanup]: https://curl.se/libcurl/c/curl_global_cleanup.html
>  */
> std::unique_ptr<render::RenderEngine> MakeRenderEngineGltfClient(
> ```

Do we need a test to exercise `MakeRenderEngineGltfClient()`? I imagine that would be fairly similar to the constructor test of RenderClient or RenderEngineGltfClient. I didn't find tests for MakeRenderEngineVtk(), and thus asking here to confirm.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8ZKD7t2ALXNth-1r3r:b-te4kzy)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/BUILD.bazel` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8ZEoTH2DLfUk50pOAz:-N8ZEoTH2DLfUk50pOB-:b-4zsagt) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/BUILD.bazel#L34)):*
> ```Starlark
>     interface_deps = [
>         "//geometry/render:render_camera",
>         "//geometry/render_gltf_client:render_engine_gltf_client_params",
> ```

nit: Target is in the same bazel file, should simply be `":render_engine_gltf_client_params"`.
___
*[`geometry/render_gltf_client/factory.h` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8ZFPn_EuDEWl9bdNXQ:-N8ZFPn_EuDEWl9bdNXR:b-xf753y) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L18)):*
BTW To prevent this from looking like a copypasta error, perhaps:

> The rules for supported geometries and textures are __*the same as for the VTK-based engine and are*__ described in MakeRenderEngineVtk().
___
*[`geometry/render_gltf_client/factory.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8ZGKMD572UJRQdFH0p:-N8ZGKMD572UJRQdFH0q:b78zsdv) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L23)):*
nit: "...by instantiating this RenderEngine with the default..."

Makes it sound like that it's the responsibility of the caller to invoke this a particular way. The opposite is true. Perhaps it would be clearer to say:

> Instantiating this RenderEngine automatically initializes curl with the default [`....`], the implication for consuming applications being:
___
*[`geometry/render_gltf_client/factory.h` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8WfFk2ETU2qB85S6R0:-N8ZIJuu5XRrfmzeGpbh:b-dwjbuy) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L70)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Do we need a test to exercise `MakeRenderEngineGltfClient()`? I imagine that would be fairly similar to the constructor test of RenderClient or RenderEngineGltfClient. I didn't find tests for MakeRenderEngineVtk(), and thus asking here to confirm.
</blockquote></details>

An excellent question.

1. All the factory does is call the hidden constructor.
2. It'd be immediately obvious if the factory didn't actually produce an engine.

That said, the key difference between the VTK render engine and this one is that the VTK render engine factory is called at multiple sites. So, if the factory didn't work there are multiple build targets that would have the opportunity to report failure. This factory isn't similarly exercised.

I see there's the `run_simulation_and_render.cc` that is still in `dev`. Presumably, that'll come out and serve that same role. Yes?

That said, in retrospect, I'd argue that a simple smoke test of invoking the factory in a test showing that it builds and returns something of the right type would not be a bad thing. It'd be nice if there were any regressions, it would be shouted about in a targeted way rather than having to infer it from downstream consequences.

Conclusion? I'd vote for a single, simple unit test. And I'll add the same to the other render engines.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_gltf_client/BUILD.bazel` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8ZEoTH2DLfUk50pOAz:-N8Zw49b7Dq0QE3egUHP:b-khexh7) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/BUILD.bazel#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Target is in the same bazel file, should simply be `":render_engine_gltf_client_params"`.
</blockquote></details>

Done. Copypasta error.
___
*[`geometry/render_gltf_client/factory.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8ZGKMD572UJRQdFH0p:-N8ZwHAt5wixHM3d7OKd:b6qh0v3) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "...by instantiating this RenderEngine with the default..."

Makes it sound like that it's the responsibility of the caller to invoke this a particular way. The opposite is true. Perhaps it would be clearer to say:

> Instantiating this RenderEngine automatically initializes curl with the default [`....`], the implication for consuming applications being:
</blockquote></details>

Done. I think it's clearer.
___
*[`geometry/render_gltf_client/factory.h` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8WfFk2ETU2qB85S6R0:-N8ZwL741NxDNGfiGygT:b-ahk2ib) ([raw file](https://github.com/robotlocomotion/drake/blob/04437568201763f649915895a9a32965342e7475/geometry/render_gltf_client/factory.h#L70)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

An excellent question.

1. All the factory does is call the hidden constructor.
2. It'd be immediately obvious if the factory didn't actually produce an engine.

That said, the key difference between the VTK render engine and this one is that the VTK render engine factory is called at multiple sites. So, if the factory didn't work there are multiple build targets that would have the opportunity to report failure. This factory isn't similarly exercised.

I see there's the `run_simulation_and_render.cc` that is still in `dev`. Presumably, that'll come out and serve that same role. Yes?

That said, in retrospect, I'd argue that a simple smoke test of invoking the factory in a test showing that it builds and returns something of the right type would not be a bad thing. It'd be nice if there were any regressions, it would be shouted about in a targeted way rather than having to infer it from downstream consequences.

Conclusion? I'd vote for a single, simple unit test. And I'll add the same to the other render engines.
</blockquote></details>

Done. A simple unit test to call the function and check nullity/default values is added. 

Yes, eventually `run_simulation_and_render.cc` will be moved out of dev and serve as an example.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a recommended tweak of the test.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8__tpp6G_03J1WZPkc:bw5d5s7)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__T7p1nADzSXujgMO:-N8__T7q88k-Vdi6NSmF:bekj910) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L13)):*
> ```cpp
> namespace {
> 
> using geometry::render::RenderEngine;
> ```

BTW This isn't wrong, but you don't need the `geometry::` namespace. simply `render::RenderEngine` would be enough.
___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8__cquAdGd3__6LcC0:b1vfco9) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
> ```cpp
>   EXPECT_NE(render_engine_gltf_client, nullptr);
>   // Check the default RenderEngineGltfClientParams is propagated properly.
>   EXPECT_EQ(render_engine_gltf_client->get_params().GetUrl(),
> ```

nit: I'd recommend the following:

1. Create a non-default set of parameters. Te goal is to have evidence that the parameters you provide are the ones passed to the instance. By using default parameters, you can't tell if the constructor is using *your* default parameters, or its own.
2. Express these last three tests in terms of the custom parameters you created instead of relying on fragile literals.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__T7p1nADzSXujgMO:-N8_nLAg1T3dGBkGVJO8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L13)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This isn't wrong, but you don't need the `geometry::` namespace. simply `render::RenderEngine` would be enough.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_nMqh0n5rAEVl-yNj:b-7xlotn) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'd recommend the following:

1. Create a non-default set of parameters. Te goal is to have evidence that the parameters you provide are the ones passed to the instance. By using default parameters, you can't tell if the constructor is using *your* default parameters, or its own.
2. Express these last three tests in terms of the custom parameters you created instead of relying on fragile literals.
</blockquote></details>

Done. How about two tests with a default RenderEngineGltfClientParams and a non-default one similar to RenderClient and RenderEngineGltfClient?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8_rpgx3nbtKu3CB6mA:bfvx2sg)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_oPkC2qVMd8af76V6:b-l47bbz) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Done. How about two tests with a default RenderEngineGltfClientParams and a non-default one similar to RenderClient and RenderEngineGltfClient?
</blockquote></details>

I guess I don't see the value in two incarnations. What does passing a default set of parameters reveal about the `MakeRenderEngineGltfClient` that the non-default set of parameters doesn't reveal? 
___
*[`geometry/render_gltf_client/test/factory_test.cc` line 31 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8_rObNEwEwdyqyhUJ0:-N8_rObNEwEwdyqyhUJ1:b-t3szhy) ([raw file](https://github.com/robotlocomotion/drake/blob/12ca21bbe554d414d65c2ee1a7ad3d5765341d11/geometry/render_gltf_client/test/factory_test.cc#L31)):*
> ```cpp
> 
> GTEST_TEST(FactoryTest, ConstructWithNonDefaultParams) {
>   const std::string base_url{"http://127.0.0.1:1234"};
> ```

BTW Slightly more compact spelling:

```c++
  RenderEngineGltfClientParams params{.base_url = "http://127.0.0.1:1234",
                                      .render_endpoint = "testing",
                                      .verbose = true,
                                      .cleanup = false};

  const std::unique_ptr<RenderEngine> render_engine =
      MakeRenderEngineGltfClient(params);
  const RenderEngineGltfClient* render_engine_gltf_client =
      dynamic_cast<RenderEngineGltfClient*>(render_engine.get());

  EXPECT_NE(render_engine_gltf_client, nullptr);
  // Check the non-default RenderEngineGltfClientParams is propagated properly.
  EXPECT_EQ(render_engine_gltf_client->get_params().GetUrl(),
            params.base_url + "/" + params.render_endpoint);
  EXPECT_EQ(render_engine_gltf_client->get_params().verbose, params.verbose);
  EXPECT_EQ(render_engine_gltf_client->get_params().cleanup, params.cleanup);
```

**Comment by jwnimmer-tri** [comment]
@sherm1 note this is moving code out of `dev`, so please expand the files in full and review as-if the files were newly-written.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_us6g-D8gibaLAW_m:bctk15n) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I guess I don't see the value in two incarnations. What does passing a default set of parameters reveal about the `MakeRenderEngineGltfClient` that the non-default set of parameters doesn't reveal? 
</blockquote></details>

Maybe it can serve as a trivial test to validate the default values are as advertised? On the other hand, I can remove that in the spirit of keeping the exercise simple.
___
*[`geometry/render_gltf_client/test/factory_test.cc` line 31 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8_rObNEwEwdyqyhUJ0:-N8_unISC6LVV3CLNu_O:bokrj44) ([raw file](https://github.com/robotlocomotion/drake/blob/12ca21bbe554d414d65c2ee1a7ad3d5765341d11/geometry/render_gltf_client/test/factory_test.cc#L31)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Slightly more compact spelling:

```c++
  RenderEngineGltfClientParams params{.base_url = "http://127.0.0.1:1234",
                                      .render_endpoint = "testing",
                                      .verbose = true,
                                      .cleanup = false};

  const std::unique_ptr<RenderEngine> render_engine =
      MakeRenderEngineGltfClient(params);
  const RenderEngineGltfClient* render_engine_gltf_client =
      dynamic_cast<RenderEngineGltfClient*>(render_engine.get());

  EXPECT_NE(render_engine_gltf_client, nullptr);
  // Check the non-default RenderEngineGltfClientParams is propagated properly.
  EXPECT_EQ(render_engine_gltf_client->get_params().GetUrl(),
            params.base_url + "/" + params.render_endpoint);
  EXPECT_EQ(render_engine_gltf_client->get_params().verbose, params.verbose);
  EXPECT_EQ(render_engine_gltf_client->get_params().cleanup, params.cleanup);
```
</blockquote></details>

Done. Changed accordingly.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_wvyB8_keBWO9msYD:b-aw56hk) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Maybe it can serve as a trivial test to validate the default values are as advertised? On the other hand, I can remove that in the spirit of keeping the exercise simple.
</blockquote></details>

My inclination is that if we can't state the clear purpose of the test, it probably shouldn't exist.

You raise an interesting possibility: it's not a test of `MakeRenderEngineGltfClient`. It's a regression test on the default values. That is arguably worthwhile. The idea being: if they ever change that represents a breaking change and some mechanism could help catch that (so someone doesn't do it thoughtlessly.

To that end, I'd recommend replacing the current `ConstructWithDefaultParams` test with:

```c++
/* Serves as a regression test on the default parameter values. If the default
 values change, this test should fail and that constitutes a breaking change. */
GTEST_TEST(ParamTest, DefaultValues) {
  RenderEngineGltfClientParams params;
  EXPECT_EQ(params.base_url, "http://127.0.0.1:8000");
  EXPECT_EQ(params.render_endpoint, "render");
  EXPECT_EQ(params.verbose, false);
  EXPECT_EQ(params.cleanup, true);
}
```

**Comment by jwnimmer-tri** [comment]
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_yhkAArrhlHuhBiwU:b-e63rch) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

My inclination is that if we can't state the clear purpose of the test, it probably shouldn't exist.

You raise an interesting possibility: it's not a test of `MakeRenderEngineGltfClient`. It's a regression test on the default values. That is arguably worthwhile. The idea being: if they ever change that represents a breaking change and some mechanism could help catch that (so someone doesn't do it thoughtlessly.

To that end, I'd recommend replacing the current `ConstructWithDefaultParams` test with:

```c++
/* Serves as a regression test on the default parameter values. If the default
 values change, this test should fail and that constitutes a breaking change. */
GTEST_TEST(ParamTest, DefaultValues) {
  RenderEngineGltfClientParams params;
  EXPECT_EQ(params.base_url, "http://127.0.0.1:8000");
  EXPECT_EQ(params.render_endpoint, "render");
  EXPECT_EQ(params.verbose, false);
  EXPECT_EQ(params.cleanup, true);
}
```
</blockquote></details>

Default values are excluded from the Stable API policy.  I don't think a change-detector test here serves any value.  If someone edits the default value, it will be plenty clear in the header file during code review.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8_zht_5BAFAmg5w4M3:b-w6kvof) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Default values are excluded from the Stable API policy.  I don't think a change-detector test here serves any value.  If someone edits the default value, it will be plenty clear in the header file during code review.
</blockquote></details>

Excellent point. I really need to better internalize the Stable API policy. "Plenty clear...during code review" can be a might tricky. 

Then I'd definitely err on the side of, "This only needs the single test with non-default parameters."

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`geometry/render_gltf_client/test/factory_test.cc` line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17678#-N8__cquAdGd3__6LcC-:-N8aD3JZ-TTxXOZHZ1fT:b4ddetc) ([raw file](https://github.com/robotlocomotion/drake/blob/dc0da79a746a8a4ec65e6e50744a1df41201fec8/geometry/render_gltf_client/test/factory_test.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Excellent point. I really need to better internalize the Stable API policy. "Plenty clear...during code review" can be a might tricky. 

Then I'd definitely err on the side of, "This only needs the single test with non-default parameters."


</blockquote></details>

OK. Thanks for the input. Changes applied.

**Review by sherm1 — COMMENTED** [review]
bumping to +@sammy-tri for platform review (sorry, Sam!)
-@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8aR2bG-ZhZdgFq-0JJ:b-60lalt)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17678#-:-N8dlqRG7_ODOpXfdgK3:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @zachfang)

**Pull request merged**
