### PR TITLE
Add vector_gen support to Bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

This teaches Bazel how to run the `lcm_vector_gen` tool, so that we won't have to commit the generated code anymore.  (Keeping that workflow alive across #6996 was going to be annoying.)  For now, we only convert one `*.named_vector` (the unit test) to the new workflow -- which means keeping some shims around so that the prior workflow is still supported.

To prove that this PR retains correctness, we can see that:
- the updated unit test passes;
- manually running one of the old-workflow update scripts like `./drake/systems/sensors/beam_model_gen.sh` is an no-op on the source tree;
- if we hack a typo into the `lcm_vector_gen.py` code template and repeat the above line, we _do_ see disturbances in the source tree -- proving that the tool is indeed rewriting the generated files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7340)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please?
+@soonho-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
Reviewed 13 of 18 files at r1.
Review status: 8 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by jwnimmer-tri** [comment]
I was guessing about feature review for this.  I think -@rpoyner-tri and then perhaps +@EricCousineau-TRI  could you do a feature-review pass on Monday?

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 18 files at r1.
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 540 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-KxU77J3mqno7LEhpWH8:-KxU77J3mqno7LEhpWH9:bhy1d5l) ([raw file](https://github.com/robotlocomotion/drake/blob/87a75729c05cb5d27881fc4431e5481afb347b2b/drake/tools/lcm_vector_gen.py#L540)):*
> ```Python
>         lcm_filename = None
> 
>     # Delete to the helper function.
> ```

s/delete/delegate/ ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by rpoyner-tri** [comment]
Reviewed 17 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---

*[drake/tools/lcm_vector_gen.py, line 540 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-KxU77J3mqno7LEhpWH8:-KxYuk6qAh2qK2BtC53y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87a75729c05cb5d27881fc4431e5481afb347b2b/drake/tools/lcm_vector_gen.py#L540)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

s/delete/delegate/ ??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-:-KxhzFypJ4MiQ46mccVq:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with very minor nits + BTWs.

---

Reviewed 5 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/tools/lcm_vector_gen.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhww0WkvHlgSAq-KGE:-Kxhww0WkvHlgSAq-KGF:b-2rmow3) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L1)):*
> ```Python
> """Generate c++ and LCM definitions for the LCM Vector concept.
> ```

BTW Should this file include a shebang?

---

*[drake/tools/lcm_vector_gen.py, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhy3dSXWfe9lmZKtu-:-Kxhy3dTSLMO_P4Xv0wR:b-aaua3d) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L16)):*
> ```Python
> # we'll try both.  TODO(jwnimmer-tri) Replace with a single import block once
> # the depreacted command-line interface is gone.
> try:
> ```

BTW Can you add a comment whether the given section is in the Bazel-execroot-land or not?

---

*[drake/tools/lcm_vector_gen.py, line 518 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhze90e7T8vkQVhryX:-Kxhze91gBcbIfm3rjjr:bkm7dqt) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L518)):*
> ```Python
> def deprecated_generate_all_code(args):
>     # This is a compatiblity shim from the old ArgumentParser semantics, to the
>     # new implementation function `generate_code()`.  TODO(jwnimmer-tri) Remove
> ```

BTW minor nit Can this be `TODO` can be placed on a newline, to keep it as `# TODO(...)`?

---

*[drake/tools/lcm_vector_gen.py, line 760 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhz74hu_rBgzh1BWKk:-Kxhz74hu_rBgzh1BWKl:bgrnfql) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L760)):*
> ```Python
>     # TODO(jwnimmer-tri) This block is the deprecated command-line interface;
>     # remove it when lcm_vector_gen.sh disappers.
>     if ((args.cxx_dir is not None) or
> ```

BTW While PEP8 is inconsistent for line breaks for conditionals and binary operators (in some accepted examples they are consistent, others they are not), could this be made consistent (make the binary operators start on the next line)? e.g.
```
if ((cond1)
        or (cond2)
        or (cond3)):
```

---

*[tools/vector_gen/BUILD, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-KxhxclhdFQLsKcO8qO5:-Kxhxcli3k1CgQ46H6ZO:b-tlnxxw) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/tools/vector_gen/BUILD#L5)):*
> ```Python
> # N.B. This has the "wrong" name `BUILD`, because it is a temporary artifact;
> # soon, it will be replaced with a `BUILD.bazel` moved from elsewhere.
> #
> ```

FYI Comment continuation may not be necessary?

---

*[tools/vector_gen/vector_gen.bzl, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-KxhvpHQy9vNWoX1X7_H:-KxhvpHQy9vNWoX1X7_I:b-8x39ov) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/tools/vector_gen/vector_gen.bzl#L36)):*
> ```Python
>         hdrs = [
>             join_paths(subdir, "gen", name + ".h")
>             for name in names
> ```

BTW I do not see anything in our style guide for list comprehension and linebreaks, but for readability, could this be changed to something like:
```
hdrs = [
    join_paths(subdir, "gen", name + ".h")
        for name in names
]
```
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-:-KxhyVwmt7ZFstm-VyiX:b-7phexn)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxi1JJA-vgqOG0ABORd:-Kxi1JJA-vgqOG0ABORe:b94o09v) ([raw file](https://github.com/robotlocomotion/drake/blob/f5186ca6ccc5c0095ab51742466d2cd32497ac3f/drake/tools/test/lcm_vector_gen_test.sh#L1)):*
> ```Shell
> #/bin/bash
> ```

BTW, still need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by jwnimmer-tri** [comment]
Interesting.  With this PR, a `bazel test --config lint //...` needs to compile protobuf before running -- because we are linting the generated code and its no longer committed into the tree.  I am tempted to block this PR until #7323 happens for that reason.  I will mull it over myself, but if anyone has strong feelings one way or another, please speak up.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-:-KxiB5MCOGyWwhvmG0SU:bwqb9t2)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/tools/lcm_vector_gen.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhww0WkvHlgSAq-KGE:-KxiE_L0E5eWWliQ4HqG:b-oyudid) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should this file include a shebang?
</blockquote></details>

OK Nope, the file is mode 664, not 775.

---

*[drake/tools/lcm_vector_gen.py, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhy3dSXWfe9lmZKtu-:-KxiFcNrfyMEFhirmfq9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L16)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you add a comment whether the given section is in the Bazel-execroot-land or not?
</blockquote></details>

Done.

---

*[drake/tools/lcm_vector_gen.py, line 760 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxhz74hu_rBgzh1BWKk:-KxiDGkWO95YmVk9604l:b-ipzj0l) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/drake/tools/lcm_vector_gen.py#L760)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW While PEP8 is inconsistent for line breaks for conditionals and binary operators (in some accepted examples they are consistent, others they are not), could this be made consistent (make the binary operators start on the next line)? e.g.
```
if ((cond1)
        or (cond2)
        or (cond3)):
```
</blockquote></details>

I think this file is internally consistent as-is?  The one other case wraps after an `and`.  I guess for _"could this be made consistent"_, I'm not seeing what the consistency comparison is with reference to.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-Kxi1JJA-vgqOG0ABORd:-KxiDpBD5-Bbs2vx0zyS:b-a0gfi6) ([raw file](https://github.com/robotlocomotion/drake/blob/f5186ca6ccc5c0095ab51742466d2cd32497ac3f/drake/tools/test/lcm_vector_gen_test.sh#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, still need this?
</blockquote></details>

No?  This should only run via Bazel, and Bazel sets the interpreter.  I've swapped the two comment lines to hopefully make this clearer, and added a fail-fast.

---

*[tools/vector_gen/vector_gen.bzl, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7340#-KxhvpHQy9vNWoX1X7_H:-KxiCUjCYqOUZGyrfM-a:byymccb) ([raw file](https://github.com/robotlocomotion/drake/blob/6befaf498d9168159480fe5c31b764a51eda756f/tools/vector_gen/vector_gen.bzl#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I do not see anything in our style guide for list comprehension and linebreaks, but for readability, could this be changed to something like:
```
hdrs = [
    join_paths(subdir, "gen", name + ".h")
        for name in names
]
```
?
</blockquote></details>

Nope, that trips up E131 from pep8: http://pep8.readthedocs.io/en/latest/intro.html#error-codes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7340)*

**Pull request merged**
