### PR TITLE
[meshcat] Support keycodes in JointSliders

### PR DESCRIPTION
**Pull request by RussTedrake**
+@trowell-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`multibody/meshcat/test/joint_sliders_test.cc` line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18087#-NEBRsAQD0qdkYX75vN3:-NEBRsAQD0qdkYX75vN4:b-asd1a) ([raw file](https://github.com/robotlocomotion/drake/blob/6f11089865c759bfe74d09c54c976b53b82aae32/multibody/meshcat/test/joint_sliders_test.cc#L287)):*
> ```cpp
> 
>   // Note: the stop button is deleted on timeout, so we cannot easily check
>   // that it was created correctly here.
> ```

Btw -- i wasn't able to think of a reasonable testing strategy for these, but am open to suggestions.

**Review by trowell-tri — COMMENTED** [review]
Roger, will look this evening or tomorrow.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087#-:-NEBfu6c9Z_3z_TNxT9l:bhgnhe5)* status: LGTM missing from assignee trowell-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
I'm trying to keep moving fast.  If you can't get to it today (hopefully with enough time for me to respond before folks break for the long weekend), please pass it to someone who can.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087#-:-NEGTXWl5ubWkgE9vzsc:b3g560t)* status: LGTM missing from assignee trowell-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @trowell-tri)

**Review by trowell-tri — COMMENTED** [review]
~~I'm already on it. I need to duck out late morning to get a crown re-attached but will be back by lunchtime.~~

:lgtm: on feature review

+@sammy-tri for platform review, please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087#-:-NEGY-VZD6xZkx8X-3dN:bn7pm8s)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[`bindings/pydrake/multibody/test/meshcat_test.py` line 131 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18087#-NEGYu4f64fz82NtOkg6:-NEGYu4f64fz82NtOkg7:b4z35qi) ([raw file](https://github.com/robotlocomotion/drake/blob/b41305e2a48bd5677b5803821529226d85b51b9e/bindings/pydrake/multibody/test/meshcat_test.py#L131)):*
> ```Python
>         builder.AddSystem(dut)
>         diagram = builder.Build()
>         dut.Run(diagram=diagram, timeout=1.0, stop_button_keycode="ArrowLeft")
> ```

FYI I took a second look to make sure this keycode wasn't copy-pasta. I don't think it can be, and it can't matter anyway, but pointing it out in case it actually was unintentional.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`multibody/meshcat/joint_sliders.h` line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18087#-NEGuK7PCny5nfeorfbn:-NEGw2In7QYU2XYMWAQi:b-duygm8) ([raw file](https://github.com/robotlocomotion/drake/blob/b41305e2a48bd5677b5803821529226d85b51b9e/multibody/meshcat/joint_sliders.h#L51)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW In trying to test this code, I noticed that this API seems a little non-intuitive in cases like `show_model`, where the number of sliders for an iiwa model is 7 (which is also the number of joints in the plant), but the number of positions is 14 (the robot is a free body, I assume).  The rest of the constructor arguments should have this problem too where you'd need to provide 7 useless (maybe not for initial value?) elements along with the ones for the robot, so I don't think it needs attention as part of this PR.
</blockquote></details>

(this is definitely not intended as a blocking comment so I'm not sure why reviewable is showing it as unresolved)

**Review by RussTedrake — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18087#-:-NEJ69FGBDTUteQz7lwg:b-ucfknh)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),trowell-tri (waiting on @RussTedrake)

___
*[`multibody/meshcat/joint_sliders.h` line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18087#-NEGuK7PCny5nfeorfbn:-NEJ5zrd8KHCkYs4RCuJ:basgs8e) ([raw file](https://github.com/robotlocomotion/drake/blob/b41305e2a48bd5677b5803821529226d85b51b9e/multibody/meshcat/joint_sliders.h#L51)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

(this is definitely not intended as a blocking comment so I'm not sure why reviewable is showing it as unresolved)
</blockquote></details>

Proper support for floating base is mentioned as future work in the class documentation.  I definitely would like to see it added.
___
*[`bindings/pydrake/multibody/test/meshcat_test.py` line 131 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18087#-NEGYu4f64fz82NtOkg6:-NEJ5i7O0dFqxJOLxxXQ:b-lpcvfn) ([raw file](https://github.com/robotlocomotion/drake/blob/b41305e2a48bd5677b5803821529226d85b51b9e/bindings/pydrake/multibody/test/meshcat_test.py#L131)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

FYI I took a second look to make sure this keycode wasn't copy-pasta. I don't think it can be, and it can't matter anyway, but pointing it out in case it actually was unintentional.
</blockquote></details>

I agree it looks a bit strange.  I just wanted something that was not "Escape" (since that was the default).  But it could have been anything.

**Pull request merged**
