### PR TITLE
 Ensure shared libraries have SONAME set

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates https://github.com/RobotLocomotion/drake-shambhala/issues/99.

FYI @stonier.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8308)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review :lgtm: and :penguin: tested.

Confirmed
```console
$ readelf -d lib/libdrake.so
....
 0x000000000000000e (SONAME)             Library soname: [libdrake.so]
...
$ readelf -d lib/libdrake_bullet_collision.so
 0x000000000000000e (SONAME)             Library soname: [libdrake_bullet_collision.so]
...
(etc)
```

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8308#-:-L776iF3x8Ng4WODDKaJ:buzl2ia)*

**Comment by stonier** [comment]
:+1: tested with shambhala, looks good.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8308#-:-L7AVcpZMCj-5atI0qL9:bnfp4nl)*

**Pull request merged**
