### PR TITLE
Prototype: hydroelastic compliant non-convex tetrahedral meshes from VTK

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Import VTK tetrahedral meshes for hydroelastic compliant non-convex objects.

This PR will rebase on these sub-tasks as we go.

- [X] Add scaling parameter for ReadVtkToVolumeMesh().
    - #17817 
- [x] MakeVolumeMeshFromVtk()
    - #17820
- [x] MakeNonConvexMeshPressureField()
    - #17828
- [x] Compliant non-convex mesh in hydroelastic_internal.
    - #17836  
- [x] Compliant non-convex mesh in ProximityEngine.
    - #17837
- [ ] ~~(this PR) bazel run //examples/hydroelastic/python_nonconvex_compliant_mesh:drop_pepper_py~~
- [x] #17959
- [x] RobotLocomotion/[models/19](https://reviewable.io/reviews/RobotLocomotion/models/19)

Until we finish all the tasks, we keep this PR `status: do no merge`.

Update: We have finished all the sub-tasks.  I close this draft PR now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
This is very cool.  :) Nice to see this evolution.

I know this PR is intended as a simple mechanism for sharing your branch, but we want to make sure it doesn't merge with the huge model files, even by accident. So, to be safe, +(status: do not merge).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NAPTCirCQHIOkM6rd1O:bpphamz)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
Thank you. Agreed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NASXs4x0QLm7B3nxzrO:bce6adc)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
Inspired by @russtedrake's idea, I also have a branch [hack_hydroelastic_compliant_pepper_tet_uri](https://github.com/RobotLocomotion/drake/compare/master...DamrongGuoy:drake:hack_hydroelastic_compliant_pepper_tet_uri) to play with `drake:tet_uri` to specify VTK file in addition to `uri` for OBJ file.

This branch:
```
<uri> pepper.1.obj </uri>
```
That branch:
```
<uri> pepper.1.obj </uri>
<drake:tet_uri> pepper.1.vtk <drake:tet_uri>
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NAa0WCW2c5dSyuF9-AY:bywnd0t)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
Now this branch use `<uri>` to specify VTK file for collision non-convex volume mesh:
```
      <collision name="collision">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>pepper.1.vtk</uri>
            <scale>0.005 0.005 0.005</scale>
          </mesh>
        </geometry>
```
Run with:
```
 bazel run //examples/hydroelastic/python_ball_paddle:contact_sim_demo_py -- --target_realtime_rate=0.04 --simulation_time=2
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NAo7wq712Ay1E_QhWDy:blbd9mq)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
CC: @rcory   

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NAvNMNj5coDhwyv5H4s:b-9zv15c)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by DamrongGuoy** [comment]
2/6 tasks done.

**Comment by DamrongGuoy** [comment]
#17828 and #17836 are merged today.

We need only one more PR #17837 before creating examples.

**Review by DamrongGuoy — COMMENTED** [review]
Now run it by:
```
bazel run //examples/hydroelastic/python_nonconvex_compliant_mesh:drop_pepper_py
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NC817JG3n1ha45WuYwl:b-mlbqo0)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
It will look like this:
[2022-09-16\_drop\_pepper.mp4](https://files.reviewableusercontent.io/images/reviewable/42557859/XBah8qrgb2alCL5IhoLn3O8i/2022-09-16_drop_pepper.mp4)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17780#-:-NC81LR7-y9wBGy4AKVx:brydmhk)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Pull request closed without merging**
