### PR TITLE
WIP: Add z1 arm from Unitree

### PR DESCRIPTION
**Pull request by siilats**
Original robot files are here
https://github.com/unitreerobotics/z1_ros

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20284)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Hi @siilats, thanks for your interest in Drake! 

I'd like to understand the plan here, to save you some time in case we're on the wrong track.  Please see https://drake.mit.edu/model_version_control.html:

> Before you decide to submit models, please ensure that you have tests that will need them. Do not submit a PR that adds models but has zero intent to use them, as Drake is not a model repository.

Our policy is that we only put model files _directly_ into `drake` or `drake_models` when those models will be used by Drake's built-in tutorials or examples.  For models not directly used by Drake itself, we ask users to keep their own model repositories, separate from Drake.

Do you know if there are any plans to use this new z1 model in future Drake pull requests?

FYI For loading non-Drake model packages, Drake can use `ROS_PACKAGE_PATH` to load models via [PackageMap.PopulateFromRosPackagePath()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_package_map.html#a82b086143ce943e2318a7b2added1313), or Drake can download packages from remote servers using [PackageMap.AddRemote()](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_package_map.html#a315d439afb48490c763ff66f4fc24b86), or you can add path entries directly to PackageMap with other of its API.

**Comment by siilats** [comment]
> model files _directly_ into `drake` or `drake_models` when those models will be used by Drake's built-in tutorials or examples. For models not directly used by Drake itself, we ask users to keep their own model repositories, separate from Drake.

Hi I have the actual Z1 arm and I am teaching it how to fly a business jet. You can see a bit more in the patent
https://patentsgazette.uspto.gov/week39/OG/html/1514-4/US11767099-20230926.html
Basically I realized I need impedance control in order to push buttons, I also have some cool research stuff on dynamic time warping to align several demonstrations. I will implement them in drake, I started with Peter Corkes and CoppeliaSim but I need better control algorithms.

Also the Z1 is under $10k, its similar to xArm so its a pretty cool research tool.

**Comment by jwnimmer-tri** [comment]
That sounds exciting, but I wasn't able to understand whether it directly answers my question?

The question is whether you are planning to contribute a new Drake [tutorial](https://drake.mit.edu/#tutorials) file to [drake/tutorials](https://github.com/RobotLocomotion/drake/tree/master/tutorials) that demonstrates something which requires Z1 arm model file -- or something along those lines.  Unless and until Drake has tutorial (or example, demo, etc.) code that needs the Z1 model files, we would not accept a pull request that adds the Z1 model to Drake.  (As the document says, "Drake is not a model repository."  The only reason we directly incorporate model files as first-party content is when it's a necessary condition to write a good tutorial.)

Possibly if you could share more of your plans for contributing, we'd be able to give better advice & help with the pull requests.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20284)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @siilats)

**Comment by jwnimmer-tri** [comment]
Closing for lack of response.

**Pull request closed without merging**
