### PR TITLE
Add Value<T> support for clone-only types

### LINKED ISSUE #5469: Value<T> should support T's that implement Clone
Right now, `Value<T>` only supports `T`'s that are copyable (using C++ copy constructor / copy-assignment operator).  It would be very nice for users if `T`'s that quack like a `std::unique_ptr<T> Clone() const` member method could be used as well, and especially that the `AbstractValue` methods like `template <class T> const T& AbstractValue::GetValue()` also worked seamlessly (with exposing some kind of `unique_ptr` intermediary).  I think that should all be possible with a bit of SFINAE and `type_traits`.

At the same time, we might also consider if we could offer `AbstractValue` some kind of move semantics, e.g. `AbstractValue::MoveFrom` or `::MoveTo` and friends to mimic `AbstractValue::SetFrom`.  Or at least, consider that future possibility when updating the code for `Clone`-able `T`'s.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Resolves #5469.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6177)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.  Do you have time to spike test a trial integration of this into your code?

**Comment by siyuanfeng-tri** [comment]
awesome, let me try it.

**Comment by jwnimmer-tri** [comment]
In subsequent work, I've found a need for one more overload:
```c++
  /// Constructs a Value<T> by copying or moving the given value @p v.
  explicit Value(std::unique_ptr<T> v);
```

Let me know if you need it now, and I could add to this PR.

**Comment by siyuanfeng-tri** [comment]
This could be handy. I am still merging and compiling.. 
At a glance, this has more c++ stuff than I am normally comfortable with. I am not sure if I can give much value feedback on the design or implementation. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-KkzjqD0zrNYmER4lvph:bg3131g)*

**Comment by jwnimmer-tri** [comment]
Yeah, I just finished testing the new ctor for unique_ptr.  It is very elegant, so I will push it into this PR.

Don't worry about checking the code for correctness.  I'd like to know from you (1) does this meet your needs, and (2) do you understand the API documentation.  I'll get some gurus to carefully check the code and tests.

**Comment by siyuanfeng-tri** [comment]
Sounds good! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-KkzlB4mygbK2zTcRXGk:bdnerqr)*

**Comment by siyuanfeng-tri** [comment]
Works great with my stuff, the call sites for non-copyable objects appears to be the same as for copyable types. Polymorphic stuff works as well.
Since I know enough of what this PR is trying to do, and with enough googling, I can figure out what the template stuff is trying to do. Comments seems sufficient. I am not sure more comments would help much. :lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzuIR_7kYCHYViVe8l:-KkzuIR_7kYCHYViVe8m:bgu8tpc) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L217)):*
> ```objc
>                 !std::is_same<T&, Arg1>::value &&
>                 // ... except only for cloneable T.
>                 !value_detail::ValueTraits<T>::use_copy::value
> ```

BTW, you are not checking !POD here because POD is not cloneable => cloneable is not POD? 

---

*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-KkzsMJAgZF4g-1Bieo-:b-91see8) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
> ```objc
>   /// Constructs a Value<T> by copying or moving the given value @p v.
>   explicit Value(std::unique_ptr<T> v)
>       : value_(Traits::to_storage(std::move(v))) {}
> ```

I don't get this line.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-Kkzv9eNIFzGBqcCmXCM:b-goep7z)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/value.h, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzuIR_7kYCHYViVe8l:-KkzzoCTtUr9vd8MelXt:b-okxhkk) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L217)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, you are not checking !POD here because POD is not cloneable => cloneable is not POD? 
</blockquote></details>

Right-o.  But leaving it out will make everyone ask that questions, so I've put it back in.

---

*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl-0YeUzOlQgMHuNGEi:b-47t8m5) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I don't get this line.. 
</blockquote></details>

We start with a `unique_ptr<T> v`.  We `std::move` it to get an xvalue `unique_ptr<T>&&` that we pass to `to_storage`.

In the copyable case, that matches `to_storage(const unique_ptr<T>&)`, which does a nonnull check and then returns an alias to the owned `const T&` within `v`.  Back in the `Value` constructor, the `value_` member constructor is offered `const T&` so it does `T::T(const T&)` copy construction.  As the constructor returns, the `v` argument goes out of scope and the `T` owned by `v` is deleted.  The users's `unique_ptr<T>` was transferred to `Value<T>` with a single copy.

In the cloneable case, that matches `to_storage(unique_ptr<T>)`, which means `v` is moved into `other`.  The `to_storage` does a nonnull check, then `std::move`s `other` into an xvalue `unique_ptr<T>&&` again, then constructs a `copyable_unique_ptr<T>` from the xvalue which moves the owned T resource into that temporary, then returns the temporary by-value.  By RVO, the return value was already directly place into `value_` and we are done.  The user's `unique_ptr<T>` was transferred to `Value<T>` without any Clone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

/CC @sherm1 if you are interested, you can self-assign this for a look today or tomorrow.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-Kl-4IpoGmyK0dHqPfii:b63m05r)*

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl-4zABRDLBYz1FHMip:b-738hq0) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We start with a `unique_ptr<T> v`.  We `std::move` it to get an xvalue `unique_ptr<T>&&` that we pass to `to_storage`.

In the copyable case, that matches `to_storage(const unique_ptr<T>&)`, which does a nonnull check and then returns an alias to the owned `const T&` within `v`.  Back in the `Value` constructor, the `value_` member constructor is offered `const T&` so it does `T::T(const T&)` copy construction.  As the constructor returns, the `v` argument goes out of scope and the `T` owned by `v` is deleted.  The users's `unique_ptr<T>` was transferred to `Value<T>` with a single copy.

In the cloneable case, that matches `to_storage(unique_ptr<T>)`, which means `v` is moved into `other`.  The `to_storage` does a nonnull check, then `std::move`s `other` into an xvalue `unique_ptr<T>&&` again, then constructs a `copyable_unique_ptr<T>` from the xvalue which moves the owned T resource into that temporary, then returns the temporary by-value.  By RVO, the return value was already directly place into `value_` and we are done.  The user's `unique_ptr<T>` was transferred to `Value<T>` without any Clone.
</blockquote></details>

ah.. somehow I read this part, but didn't read the accompanying to_storage with unique_ptrs. That was very confusing. Thanks for the explanation. 
In the copyable case, after Traits::to_storage(std::move(v)) returns, who has the unique_ptr? shouldn't it be deleted already?, and thus the returned const reference is invalid? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl-6jUGyAznxfKrC6cg:b-v7mmjk) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

ah.. somehow I read this part, but didn't read the accompanying to_storage with unique_ptrs. That was very confusing. Thanks for the explanation. 
In the copyable case, after Traits::to_storage(std::move(v)) returns, who has the unique_ptr? shouldn't it be deleted already?, and thus the returned const reference is invalid? 
</blockquote></details>

In the copyable case, `v` is not destroyed until the `Value` constructor is done, so we should be ok.  The key fact is that `std::move` makes a thing _eligible_ for moving but does not _force_ it to move or otherwise disappear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl-81-bRQgILrcsUkjU:bmcobz5) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In the copyable case, `v` is not destroyed until the `Value` constructor is done, so we should be ok.  The key fact is that `std::move` makes a thing _eligible_ for moving but does not _force_ it to move or otherwise disappear.
</blockquote></details>

... urr, ok, I didn't know that before. 
Just to make sure I get this, suppose I have void Foo(std::unique_ptr<stuff> ptr), and inside Foo, I didn't actually do anything about it (i.e. move it),  after Foo(std::move(ptr)), ptr is still valid? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl-9CHE1ZCunxktAAX-:bt3d70d) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

... urr, ok, I didn't know that before. 
Just to make sure I get this, suppose I have void Foo(std::unique_ptr<stuff> ptr), and inside Foo, I didn't actually do anything about it (i.e. move it),  after Foo(std::move(ptr)), ptr is still valid? 
</blockquote></details>

Maybe just fine me offline and we can whiteboard through a few cases to explain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl3FZsFtWesBoeuYKHY:b-fyd0w3) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe just fine me offline and we can whiteboard through a few cases to explain.
</blockquote></details>

Thanks for the explanation, it helps a lot!

---

*[drake/systems/framework/value.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-Kl3G3LQ-z_XeHa8MYjr:-Kl3G3LQ-z_XeHa8MYjs:bt0j327) ([raw file](https://github.com/robotlocomotion/drake/blob/ceaf27b1784f1150514d896e5f4f86a7900de139/drake/systems/framework/value.h#L19)):*
> ```objc
> class Value;
> 
> #if !defined(DRAKE_DOXYGEN_CXX)
> ```

I think it would be easier to read the code if we move the implementation of `ValueTraitsImpl` up here instead of having forward-decl of them. 

---

*[drake/systems/framework/value.h, line 293 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-Kl3ExcPkdcHgxtFcdqD:-Kl3ExcQTCZ6EvOBmJpv:bwgbko4) ([raw file](https://github.com/robotlocomotion/drake/blob/ceaf27b1784f1150514d896e5f4f86a7900de139/drake/systems/framework/value.h#L293)):*
> ```objc
>       drake::is_cloneable<T>::value,
>       "Types placed into a Value<T> must either be copyable or cloneable");
>   using use_copy = std::false_type;
> ```

BTW, using the same name `use_copy` here confused me when I first read it. How about using `ValueTraitsImpl::UseCopy` while keeping `bool use_copy` above (line 265)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-Kl3Fc1fM8IT_qlZ41Ln:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
PTAL.  The moved code is unchanged _except_ for the `UseCopy` adjustment.

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/value.h, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-KkzsMJAgZF4g-1Bienz:-Kl3YPDSt8TC8IBB_jO1:b4xuyd5) ([raw file](https://github.com/robotlocomotion/drake/blob/cad31e29dae96aac6fa82e7aa5b362884dfff1ad/drake/systems/framework/value.h#L228)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Thanks for the explanation, it helps a lot!
</blockquote></details>

Seems worth putting into the code.  Done.

---

*[drake/systems/framework/value.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-Kl3G3LQ-z_XeHa8MYjr:-Kl3XlNnzUxzgAdgk6TN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ceaf27b1784f1150514d896e5f4f86a7900de139/drake/systems/framework/value.h#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it would be easier to read the code if we move the implementation of `ValueTraitsImpl` up here instead of having forward-decl of them. 
</blockquote></details>

Done.

---

*[drake/systems/framework/value.h, line 293 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-Kl3ExcPkdcHgxtFcdqD:-Kl3YZlOEvfFFMvDbSrZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ceaf27b1784f1150514d896e5f4f86a7900de139/drake/systems/framework/value.h#L293)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, using the same name `use_copy` here confused me when I first read it. How about using `ValueTraitsImpl::UseCopy` while keeping `bool use_copy` above (line 265)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-Kl3Z0ILjlthqwbjhFwQ:bh5m3k4)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6177#-:-Kl3gr9T6Ac4fj9hpIGl:bnfp4nl)*

**Comment by sherm1** [comment]
@jwnimmer-tri, awesome! I love the traits class.

**Pull request merged**
