### PR TITLE
Return geometric mean cost

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373#-:-MtK60qmDmygPIHQuUnF:bs3tquo)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/test/second_order_cone_program_examples.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtK6OFxBTOr2BIH6YMc:-MtK6OFxBTOr2BIH6YMd:b-2dnzxq) ([raw file](https://github.com/robotlocomotion/drake/blob/9ca13d63d16b34cdeff47a8e02caeaeeddadf4e7/solvers/test/second_order_cone_program_examples.cc#L361)):*
> ```cpp
>   Eigen::Vector2d A(2, 3);
>   Eigen::Vector2d b(3, 2);
>   prog_->AddMaximizeGeometricMeanCost(A, b, Vector1<symbolic::Variable>(x_));
> ```

@jwnimmer-tri I had to modify the test in `second_order_cone_program_examples` to test the returned cost. If I keep the old structure, I will return the cost here, but then I need to store the returned cost as a data inside this class, so as to use this cost later in `CheckSolution` function. On the other hand, `Binding<LinearCost>` doesn't have a default constructor, so I cannot construct this data at the construction of the class. Namely the following approach fails
```cc
class MazimizeGeometricMeanTrivialProblem1 {
 private:
  Binding<LinearCost> cost_;
}
```
Jeremy, do you think there is a better approach that doesn't need to convert MaximizeGeometricMeanTrivialProblem1 from a class to a function? Thanks a lot!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/test/second_order_cone_program_examples.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtK6OFxBTOr2BIH6YMc:-MtPyAaS-DFECkdQrtfp:b-ui7rqx) ([raw file](https://github.com/robotlocomotion/drake/blob/9ca13d63d16b34cdeff47a8e02caeaeeddadf4e7/solvers/test/second_order_cone_program_examples.cc#L361)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@jwnimmer-tri I had to modify the test in `second_order_cone_program_examples` to test the returned cost. If I keep the old structure, I will return the cost here, but then I need to store the returned cost as a data inside this class, so as to use this cost later in `CheckSolution` function. On the other hand, `Binding<LinearCost>` doesn't have a default constructor, so I cannot construct this data at the construction of the class. Namely the following approach fails
```cc
class MazimizeGeometricMeanTrivialProblem1 {
 private:
  Binding<LinearCost> cost_;
}
```
Jeremy, do you think there is a better approach that doesn't need to convert MaximizeGeometricMeanTrivialProblem1 from a class to a function? Thanks a lot!
</blockquote></details>

I think if you stored the cost as `std::unique_ptr<Binding<LinearCost>> cost_;` just like we already do with `prog_`, then it should work?  You should be able to do:

```c++
auto cost = prog_->AddMaximizeGeometricMeanCost(...);
cost_ = std::make_unique(std::move(cost));
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/test/second_order_cone_program_examples.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtK6OFxBTOr2BIH6YMc:-MtQodGb4X0846qPoHDI:b-6voha7) ([raw file](https://github.com/robotlocomotion/drake/blob/9ca13d63d16b34cdeff47a8e02caeaeeddadf4e7/solvers/test/second_order_cone_program_examples.cc#L361)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think if you stored the cost as `std::unique_ptr<Binding<LinearCost>> cost_;` just like we already do with `prog_`, then it should work?  You should be able to do:

```c++
auto cost = prog_->AddMaximizeGeometricMeanCost(...);
cost_ = std::make_unique(std::move(cost));
```
</blockquote></details>

Thanks Jeremy, I thought I tried this approach before, but I must missed something and found it didn't work.

Anyway, I think I like the new code better, as in each test (snopt_solver_test.cc, mosek_solver_test.cc), it takes less lines. Would you mind if I just use this new `second_order_program_examples.h` code?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/test/second_order_cone_program_examples.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtK6OFxBTOr2BIH6YMc:-Mtika496w2V-P10Cio0:bf7hyjw) ([raw file](https://github.com/robotlocomotion/drake/blob/9ca13d63d16b34cdeff47a8e02caeaeeddadf4e7/solvers/test/second_order_cone_program_examples.cc#L361)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks Jeremy, I thought I tried this approach before, but I must missed something and found it didn't work.

Anyway, I think I like the new code better, as in each test (snopt_solver_test.cc, mosek_solver_test.cc), it takes less lines. Would you mind if I just use this new `second_order_program_examples.h` code?
</blockquote></details>

The benefit of using the two different calls is that it gives the test author the ability to (1) tweak the SolverOptions prior to solving (by giving the developer access to the raw `prog`, and (2) add additional checks on the result after the solving (by giving the developer access to the raw `result`).

In practice, we do not seem to be using either of those benefits for these maximize-mean example programs. If you don't think we'd need those abilities in the future, it's fine to remove them.

Note, however, that example programs like `LinearMatrixEqualityExample` _do_ use those features, so now the API for our example programs are inconsistently formulated.

If you do stick with this new approach of consolidation, then I'd also ask if the `if (solver.available())` boilerplate should also be rolled into the helper, instead of having it copied into every test program.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/test/second_order_cone_program_examples.cc, line 361 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtK6OFxBTOr2BIH6YMc:-Mtk2hKh2lp1jtIlcTvl:bh6yio) ([raw file](https://github.com/robotlocomotion/drake/blob/9ca13d63d16b34cdeff47a8e02caeaeeddadf4e7/solvers/test/second_order_cone_program_examples.cc#L361)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The benefit of using the two different calls is that it gives the test author the ability to (1) tweak the SolverOptions prior to solving (by giving the developer access to the raw `prog`, and (2) add additional checks on the result after the solving (by giving the developer access to the raw `result`).

In practice, we do not seem to be using either of those benefits for these maximize-mean example programs. If you don't think we'd need those abilities in the future, it's fine to remove them.

Note, however, that example programs like `LinearMatrixEqualityExample` _do_ use those features, so now the API for our example programs are inconsistently formulated.

If you do stick with this new approach of consolidation, then I'd also ask if the `if (solver.available())` boilerplate should also be rolled into the helper, instead of having it copied into every test program.
</blockquote></details>

Good point. I switched back to the previous implementation.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 4 of 12 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373#-:-MtnmZIk-9UtOn-mQiIO:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtniwxP1aMhxZOVOK8s:-MtniwxP1aMhxZOVOK8t:b-v9p4u) ([raw file](https://github.com/robotlocomotion/drake/blob/eeaec4dc0d3e29d4aac3be194c9ed7bde28e0319/solvers/mathematical_program.h#L1307)):*
> ```objc
>    * is 1.
>    * @return cost The added cost (note that since MathematicalProgram only
>    * minimizes the cost, the returned cost evaluates to -c * power(∏ᵢx(i), 1/n).
> ```

nit This function has two overloads; should this note appear in both of them?
___
*[solvers/mathematical_program.cc, line 624 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtnjEwa0fHV5Ak9IWR9:-MtnjEwa0fHV5Ak9IWRA:b3fjr7q) ([raw file](https://github.com/robotlocomotion/drake/blob/eeaec4dc0d3e29d4aac3be194c9ed7bde28e0319/solvers/mathematical_program.cc#L624)):*
> ```cpp
>   if (w.rows() == 1) {
>     auto cost = AddLinearCost(-w(0));
>     return cost;
> ```

nit It's not really wrong, I suppose, but it's a bit weird for this "Add + return" to be split into two lines, whereas a couple of lines below, we do it all on one line.

Ditto on L673 below.
___
*[solvers/test/second_order_cone_program_examples.cc, line 372 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16373#-MtnmHhUAwVc9LPadZmQ:-MtnmHhUAwVc9LPadZmR:b-etp5ff) ([raw file](https://github.com/robotlocomotion/drake/blob/eeaec4dc0d3e29d4aac3be194c9ed7bde28e0319/solvers/test/second_order_cone_program_examples.cc#L372)):*
> ```cpp
>   ASSERT_TRUE(result.is_success());
>   EXPECT_NEAR(result.GetSolution(x_), 10, tol);
>   const double cost_expected = -std::sqrt(23. * 32);
> ```

nit For float literals, we need a zero after the dot.
https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```cpp
23.0
```

**Review by hongkai-dai — COMMENTED** [review]
@sammy-tri is it OK if I ask you to do a platform review? Jeremy is the platform review tomorrow and he has already done the feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373#-:-MtowyRGAtI-uF04aw6G:b-l838b6)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
I can take platform for today! +@ericcousineau-tri for platform
:lgtm: platform

> Reviewed 2 of 12 files at r1, 1 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16373#-:-Mtst6Pu8-vuh7YAzQlF:batkyec)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Comment by EricCousineau-TRI** [comment]
er, sorry; typos in merge commit!

**Pull request merged**
