### PR TITLE
Fix various issues related to finding a Drake binary install with CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
These do not affect most people, but in theory they could.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12339)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Comment by jwnimmer-tri** [comment]
@jamiesnape Hmm, I know I reviewed this -- but on Ubuntu why did `pkg-config` move from `setup/ubuntu/source_distribution/packages-bionic.txt` to `setup/ubuntu/binary_distribution/install_prereqs.sh` instead of `setup/ubuntu/binary_distribution/packages-bionic.txt`?  Or in general, why are some packages in the text file and some in the shell script?

In Anzu, I reuse only the text files, I do not run the bash scripts, so I've lost the pkg-config dependency.

**Comment by jamiesnape** [comment]
> Or in general, why are some packages in the text file and some in the shell script?

The text files for the binary distribution are (supposed to be) strictly the runtime dependencies.

> In Anzu, I reuse only the text files, I do not run the bash scripts, so I've lost the pkg-config dependency.

Not a supported usage, of course. We could break the rest of dependencies into lists, if really necessary, or we can fix the scripts for whatever the reason you are not using them, but the packages were broken out into lists for package managers, docker containers, etc.

**Comment by jwnimmer-tri** [comment]
> The text files for the binary distribution are (supposed to be) strictly the runtime dependencies.

So the idea is that the txt file is runtime dependencies, and the shell script is anything additional required to be able to do `find_package(drake CONFIG REQUIRED)`?

That's a fair distinction.  Next time we're in those files, we should add a comment to the shell script to that effect.

> ... fix the scripts for whatever the reason you are not using them ...

For background: my use case is that I a need an Anzu setup script like https://github.com/RobotLocomotion/drake-external-examples/blob/master/scripts/setup/linux/ubuntu/bionic/install_prereqs, but I don't want to manually keep the list of packages up to date by hand-authoring a file.  I sync Drake's txt files into Anzu automatically (any time the Drake pin changes), but I do not want to relinquish full control to the Drake install_prereqs.sh script -- the the source_distribution flavor of it does more than I can allow, because it is designed only for first-party builds, not for external builds -- it tries to update a gen-rc file, it adds a ppa, and it forces the version of bazel.  None of those three are workable for Anzu -- it has its own rcfiles, it cannot use ppas, and we like to keep our own pin of bazel in case our needs diverge from Drake.

I am OK with the current status quo though -- I just added `pkg-config` to my list of manual Anzu deps.

At most in Drake, we could put `pkg-config` back into `source_distribution/packages-bionic.txt` since it is still a source dep.  But I understand the argument about not duplicating the shell script.

**Comment by jamiesnape** [comment]
> So the idea is that the txt file is runtime dependencies, and the shell script is anything additional required to be able to do find_package(drake CONFIG REQUIRED)?

Exactly.

> For background: my use case is that I need an Anzu setup script like https://github.com/RobotLocomotion/drake-external-examples/blob/master/scripts/setup/linux/ubuntu/bionic/install_prereqs, but I don't want to manually keep the list of packages up to date by hand-authoring a file. I sync Drake's txt files into Anzu automatically (any time the Drake pin changes), but I do not want to relinquish full control to the Drake install_prereqs.sh script -- the the source_distribution flavor of it does more than I can allow, because it is designed only for first-party builds, not for external builds -- it tries to update a gen-rc file, it adds a ppa, and it forces the version of bazel. None of those three are workable for Anzu -- it has its own rcfiles, it cannot use ppas, and we like to keep our own pin of bazel in case our needs diverge from Drake.

Good to know.

**Pull request merged**
