### PR TITLE
[setup] Restructure Ubuntu dependencies on clang-9

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16606.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16622)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
Interesting, our Unprovisioned Clang CMake builds pass `--without-test-only`, but still expect Clang to be there.  I guess I'll need something slightly more subtle here.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16622#-:-MwS3wNm1so2Si3iXPzf:bnfp4nl)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

After reviews are complete, I'll help coordinate the CI updating dance for landing this.  We might just be able to merge it straight-away.  I'll figure that out later on.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16622#-:-MwS5PXo3-FvV7WqS7-l:bcpz082)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Since this is a monotonic addition of packages, with no need (yet) for anything else that depends on them, we can safely merge this now without an extra CI interlock.  I'll do that now and then open an issue for the CI image updates.

**Pull request merged**
