### PR TITLE
workspace: Upgrade to buildifier 0.12.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per schedule, please.

There are a lot of changes.  If nothing else, please look at the first and last commits directly -- they were hand written.  The level of review of the middle commit (or just the overall PR) is up to you.

---

Review status: 1 unresolved discussion, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9001#-LEztoDAB4300YlROhJQ:-LEztoDAB4300YlROhJR:b-z2uc72) (no related file):*
Needs macOS CI testing prior to merge.  I'll do a round of review / fixes first though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001#-:-LEztqoT9Fg9y8Hzho_H:b-61ex7l)*

**Comment by soonho-tri** [comment]
Reviewed 73 of 85 files at r1.
Review status: 1 unresolved discussion, LGTM missing from assignee soonho-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 12 of 85 files at r1, 1 of 1 files at r2.
Review status: 1 unresolved discussion, platform LGTM from [soonho-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9001#-LEztoDAB4300YlROhJQ:-LF2s1l91VUVBWXPv3KT:blmjt3v) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs macOS CI testing prior to merge.  I'll do a round of review / fixes first though.
</blockquote></details>

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

---

*[tools/install/install.bzl, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9001#-LF2rQfg0_I9ljxVqeXU:-LF2rQfg0_I9ljxVqeXV:bnot3gp) ([raw file](https://github.com/robotlocomotion/drake/blob/78ff34480a1fde5392d8a7f033f8e14fc2059d94/tools/install/install.bzl#L81)):*
> ```Python
>     elif scope == "WORKSPACE":
>         return [
>             f for f in candidates
> ```

BTW, running `buildifier-0.12.0` will change these lines to the following
```
            f
            for f in candidates
```

I definitely, prefer the current formatting though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001#-:-LF2s2Y_4oZCerf2CT-l:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri]

---

*[tools/install/install.bzl, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9001#-LF2rQfg0_I9ljxVqeXU:-LF49rkx9-fEFdAAxtJj:b-3170yp) ([raw file](https://github.com/robotlocomotion/drake/blob/78ff34480a1fde5392d8a7f033f8e14fc2059d94/tools/install/install.bzl#L81)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, running `buildifier-0.12.0` will change these lines to the following
```
            f
            for f in candidates
```

I definitely, prefer the current formatting though.
</blockquote></details>

I was wondering how that is possible, since the linter should be barking if so.  As it turns out, though, the BUILD file in this directory is actually missing `add_lint_test` -- oops!  I'll fix that in a follow-up PR (including any fallout here) though, so that I can get this one in without merge hell.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9001)*

**Pull request merged**
