### PR TITLE
Move remaining acrobot monte carlo material out of dev

### LINKED ISSUE #13904: Acrobot monte carlo moved out of dev
This is a tracking issue for moving the contents of `examples/acrobot/dev` into `examples/acrobot`, on the theory that every dev directory should have a corresponding drake issue.

* [ ] Wait until all of the monte carlo acrobot is in dev (both python and C++)
* [ ] Checklist the contents of dev and write a README
* [ ] PR moving them out of dev

### PR DESCRIPTION
**Pull request by ggould-tri**
This moves the new matrial not from anzu, plus its immediate deps
 * metrics.py (from anzu) implements metrics over simulation output
 * optimizer_demo.py (new) demonstrates how to perform parameter
   optimization using Drake stochastic scenarios.
 * tests for the above
 * This resolves #13904

It also adds a README to the directory.  This is overdue given the
relatively large number of binaries in here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@sammy-tri this is the follow up to the previous PR I sent you.  As before this is +(priority: low) 
/cc @russtedrake this PR introduces a README over a lot of code that you wrote; rendered version at https://github.com/RobotLocomotion/drake/blob/5f0b7be30476dd8b0fcbf41c7c429810457a7195/examples/acrobot/README.md

+(type: TRI anzu wishlist) +(team: manipulation)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MRQfmEa0ZN7IkIoQHaB:b-c3bq8d)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Comment by RussTedrake** [comment]
Thanks @ggould-tri.  I'm sorry for leaving a mess for you to clean up!

**Review by ggould-tri — COMMENTED** [review]
Oh, no worries, it was quite educational!

We've got a really good set of basic tutorials here, entirely free of the complexities of MBP, and if we shine a bit of documentary light on them they should really help to smooth the currently less-well-paved control side of the drake onramp.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MRV1-TK-dYwMBViJnMg:bp1s9aj)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[examples/acrobot/README.md, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRVtWDu9POw_182MvAL:-MRVtWDu9POw_182MvAM:bu1si3z) ([raw file](https://github.com/robotlocomotion/drake/blob/5f0b7be30476dd8b0fcbf41c7c429810457a7195/examples/acrobot/README.md#L37)):*
> ```Markdown
> ```
> bazel run //tools:drake_visualizer &
> bazel run //examples/acrobot:run_passive
> ```

I think this should be `run_lqr`.
___
*[examples/acrobot/metrics.py, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRVsDQk9ayJiaixwFRW:-MRVsDQk9ayJiaixwFRX:b-hl6aja) ([raw file](https://github.com/robotlocomotion/drake/blob/5f0b7be30476dd8b0fcbf41c7c429810457a7195/examples/acrobot/metrics.py#L42)):*
> ```Python
>     """
>     return np.linalg.norm(deviation_from_upright_equilibrium(
>         x_tape[:, -1])) < 1e-3
> ```

nit: would this be slightly clearer if the code read `final_state_cost(x_tape) < 1e-3` ?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

___
*[examples/acrobot/README.md, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRVtWDu9POw_182MvAL:-MRW_y0h5q_2dc0C9FjH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f0b7be30476dd8b0fcbf41c7c429810457a7195/examples/acrobot/README.md#L37)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think this should be `run_lqr`.
</blockquote></details>

Done.
___
*[examples/acrobot/metrics.py, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRVsDQk9ayJiaixwFRW:-MRW_mwb0njAUTjcr9Xr:b-1kx5mk) ([raw file](https://github.com/robotlocomotion/drake/blob/5f0b7be30476dd8b0fcbf41c7c429810457a7195/examples/acrobot/metrics.py#L42)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: would this be slightly clearer if the code read `final_state_cost(x_tape) < 1e-3` ?
</blockquote></details>

Well that's an understatement.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MR_V1p1-zS3fnimvNes:bnfp4nl)* status: needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
+@seancurtis-tri for platform review (Jeremy is on-call but has already reviewed this when it was dev).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MR_WtcP8gE3FDBrk291:b-s0gnmp)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
FWIW I did a full-text review without thinking about it (I guess habit from platform review).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MRayZTRCJy20rP4-yrg:b-l9nxya)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done with a bunch of superficial stuff.

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MRu_qao8mqFm5mNtG_j:b-ldw5r5)* status: 12 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @ggould-tri)

___
*[examples/acrobot/README.md, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuUFQACC2eR7tJgFKz:-MRuUFQACC2eR7tJgFL-:bh6p477) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L26)):*
> ```Markdown
> 
> The acrobot plant is implemented analytically rather than from the URDF or
> SDFormat files, which are used only for visualization.
> ```

nit: I believe `acrobot_geometry` is responsible for visualization. I believe the only urdf/sdf files are in the test folder.
___
*[examples/acrobot/README.md, line 80 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuV01d4TMyfb48cDRC:-MRuV01d4TMyfb48cDRD:b-48bm53) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L80)):*
> ```Markdown
> ```
> bazel run //tools:drake_visualizer &
> bazel run //examples/acrobot:run_swing_up
> ```

nit: s/run_swing_up/run_lqr_w_estimator
___
*[examples/acrobot/README.md, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuV3y99OTLAPDQhnPP:-MRuV3y99OTLAPDQhnPQ:b-5n8kdz) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L81)):*
> ```Markdown
> bazel run //tools:drake_visualizer &
> bazel run //examples/acrobot:run_swing_up
> bazel run //common/proto:call_python_client_cli
> ```

nit: This additional process is not mentioned in the documentation above.
___
*[examples/acrobot/README.md, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuVEE5142nTY_-RFpK:-MRuVEE5142nTY_-RFpL:b-1pj11t) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L96)):*
> ```Markdown
> ```
> bazel run //tools:drake_visualizer &
> bazel run //examples/acrobot:run_swing_up_traj_optimization
> ```

BTW This is located in `examples/acrobot/test`. Does that get installed as a meaningful binary?
___
*[examples/acrobot/README.md, line 152 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuVlXq8ItXiRnAO70I:-MRuVlXq8ItXiRnAO70J:b-z95sst) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L152)):*
> ```Markdown
> 
> A simulation runner is a binary that takes a scenario and a random seed in and
> outputs the scenario that was actually run (ie with no stochastic elements)
> ```

nit s/ie/i.e.,
___
*[examples/acrobot/metrics.py, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuMlyNDrFT7Kv-JEVe:-MRuMlyNDrFT7Kv-JEVf:b-n0f0ri) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/metrics.py#L11)):*
> ```Python
> def deviation_from_upright_equilibrium(x):
>     return np.array([
>         _wrap_to(x[0], 0, 2 * np.pi) - np.pi,
> ```

BTW Perhaps I'm slow. But both x[0] and x[1] are being periodically mapped to the range [-pi, pi]. However, the different spellings define a different mapping; a 90-degree phase shift. It's not clear why this is the case. I don't doubt that there's a good reason for it. Would it be possible for this to contain a hint as to what that reason is? A reference to some other documentation?
___
*[examples/acrobot/metrics.py, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuNgxn6n7Kvrn0VUl6:-MRuNgxn6n7Kvrn0VUl7:b7hwp7n) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/metrics.py#L21)):*
> ```Python
>     """
>     Returns the L2-norm of the deviation from the upright equilibrium at the
>     final state in `x_tape`
> ```

nit. Missing final period.
___
*[examples/acrobot/metrics.py, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuP-Yp4QEPP0RpF4iz:-MRuP-Yq-ZN_L9DK2xBA:b-drm1y) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/metrics.py#L26)):*
> ```Python
> 
> 
> def ensemble_cost(x_tapes):
> ```

nit: This isn't tested in `metrics_test.py`.
___
*[examples/acrobot/optimizer_demo.py, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuY86v8DTfC_udeuUj:-MRuY86v8DTfC_udeuUk:btk7r66) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/optimizer_demo.py#L94)):*
> ```Python
>     parser.add_argument(
>         "--scenario_file", "-f", type=str, default=None,
>         help="Scenario to run (default is example_stochastic_scenario.yaml)")
> ```

BTW When I first saw this I was curious the explicitly recorded default value isn't just stored as the `default=....` value in the declaration of the argument. 

As I read the code below, I realized that there's some hidden semantics. If none is provided, the default is the named file installed as part of drake. But if a path is provided, it must be a path that can be resolved strictly through relative/absolute path semantics. Drake resources will not enter into it.  Seems that's worth capturing somewhere.
___
*[examples/acrobot/optimizer_demo.py, line 99 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRu_PtcARt73d5RQ-xL:-MRu_PtcARt73d5RQ-xM:b-v2oyke) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/optimizer_demo.py#L99)):*
> ```Python
>         default="ensemble_cost")
>     parser.add_argument(
>         "--ensemble_size", "-e", type=int, default=10,
> ```

BTW Given calling `--help` with `argparse` doesn't *display* the default values, would it be worth including the default values in the help text?
___
*[examples/acrobot/test/metrics_test.py, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuSMwX1EzNWQWAyXMv:-MRuSMwX1EzNWQWAyXMw:b-11nl5v) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/test/metrics_test.py#L39)):*
> ```Python
>             == 0)
>         # Verify a few other values.
>         self.assertTrue((deviation_from_upright_equilibrium(
> ```

nit: This first "other value" seems redundant of the test above where we assert zero deviation when "adding or subtracting 2pi".
___
*[examples/acrobot/test/metrics_test.py, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuSbig5ZBENDbnclLf:-MRuSbig5ZBENDbnclLg:b-ncxvzj) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/test/metrics_test.py#L41)):*
> ```Python
>         self.assertTrue((deviation_from_upright_equilibrium(
>             [0, 0, 0, 0]) == np.array([-np.pi, 0, 0, 0])).all())
>         self.assertTrue((deviation_from_upright_equilibrium(
> ```

nit: None of the *rest* of these "other values" test the wrapping functionality of x[0] and x[1] in any kind of dispositive manner. We've only examined the case where we're some integer multiple of 2pi away from equilibrium. A value or two where the wrapping logic is more interesting would go along way to inspire confidence.

BTW: Given the nature of these four tests, I don't see why they couldn't simply all be combined in a single test (`x = [-np.pi, np.pi / 2, 1, 1]`).  That would allow you to further test wrapping without the number of cases going through the roof. That said, there's no defect in breaking each of the state members out like this. 
___
*[examples/acrobot/test/metrics_test.py, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuTE1e106p_pVH1Iv8:-MRuTE1e106p_pVH1Iv9:bh3h9lo) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/test/metrics_test.py#L54)):*
> ```Python
>         # Verify that tapes ending at non-equilibrium points have positive
>         # cost.
>         for x_tape in self.nonequilibrium_tapes:
> ```

BTW All of your nonequilibirium tapes contain strictly positive values. A wider sprinkling of values would make these positive costs more significant. This test can't *prove* correctness, but a more interesting set of input would increase the weight of the evidence towards correctness.

**Review by ggould-tri — COMMENTED** [review]
I love me some superficial stuff.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MS-Lj3YBtD3tspycLvz:b-adufcv)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @sammy-tri and @SeanCurtis-TRI)

___
*[examples/acrobot/README.md, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuVEE5142nTY_-RFpK:-MS4IgmM4XWIrPMmTECc:b-rw1sfz) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/README.md#L96)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This is located in `examples/acrobot/test`. Does that get installed as a meaningful binary?
</blockquote></details>

From `BUILD.bazel`:
```
drake_cc_binary(
    name = "run_swing_up_traj_optimization",
```
___
*[examples/acrobot/metrics.py, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuMlyNDrFT7Kv-JEVe:-MS4BJsH8pNG6cX_cTpZ:b-c7q9yl) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/metrics.py#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Perhaps I'm slow. But both x[0] and x[1] are being periodically mapped to the range [-pi, pi]. However, the different spellings define a different mapping; a 90-degree phase shift. It's not clear why this is the case. I don't doubt that there's a good reason for it. Would it be possible for this to contain a hint as to what that reason is? A reference to some other documentation?
</blockquote></details>

Commented.  It's a legitimately annoying difference.
___
*[examples/acrobot/optimizer_demo.py, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuY86v8DTfC_udeuUj:-MS4EIw02b-yK_XZUioe:b-2snlgx) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/optimizer_demo.py#L94)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW When I first saw this I was curious the explicitly recorded default value isn't just stored as the `default=....` value in the declaration of the argument. 

As I read the code below, I realized that there's some hidden semantics. If none is provided, the default is the named file installed as part of drake. But if a path is provided, it must be a path that can be resolved strictly through relative/absolute path semantics. Drake resources will not enter into it.  Seems that's worth capturing somewhere.
</blockquote></details>

Interesting point.  I can't really think of another way to default it (any default must be a bazel data= dependency, but any user-specified file cannot be relied on to be a bazel dependency), and the current help text is about as clear as it can be.  So I've commented it rather than change the help text.
___
*[examples/acrobot/test/metrics_test.py, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuSbig5ZBENDbnclLf:-MS4Jd8eCSOoBYZQE_49:b-9wexnz) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/test/metrics_test.py#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: None of the *rest* of these "other values" test the wrapping functionality of x[0] and x[1] in any kind of dispositive manner. We've only examined the case where we're some integer multiple of 2pi away from equilibrium. A value or two where the wrapping logic is more interesting would go along way to inspire confidence.

BTW: Given the nature of these four tests, I don't see why they couldn't simply all be combined in a single test (`x = [-np.pi, np.pi / 2, 1, 1]`).  That would allow you to further test wrapping without the number of cases going through the roof. That said, there's no defect in breaking each of the state members out like this. 
</blockquote></details>

Since I'm not actually the original author I'm going to edit with a light touch :-)
Added a wrap with positive, negative, different multiples, nonzero.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Well, you definitely came to the right man for that.  :)

:LGTM:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14541#-:-MS4mkOdDP-uLAOPhGAv:b1ttrzw)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[examples/acrobot/optimizer_demo.py, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MRuY86v8DTfC_udeuUj:-MS4n2Ec33vu2fqDnD-d:buyzh9i) ([raw file](https://github.com/robotlocomotion/drake/blob/f393566768c710131c2fb449a80ef8cca321090f/examples/acrobot/optimizer_demo.py#L94)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Interesting point.  I can't really think of another way to default it (any default must be a bazel data= dependency, but any user-specified file cannot be relied on to be a bazel dependency), and the current help text is about as clear as it can be.  So I've commented it rather than change the help text.
</blockquote></details>

The comment is exactly what I was hoping for -- just so future developers don't have the same, "huh?" moment I had.
___
*[examples/acrobot/optimizer_demo.py, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14541#-MS4nNUR3_tG9LyGd8uw:-MS4nNUR3_tG9LyGd8ux:b-bb48sc) ([raw file](https://github.com/robotlocomotion/drake/blob/532660afb6cbf7ebb54dc55466b62733fb9ec1b5/examples/acrobot/optimizer_demo.py#L101)):*
> ```Python
>     parser.add_argument(
>         "--metric", "-m", type=str, choices=METRICS.keys(),
>         help="Choice of metric to optimize (default: %(default)s)",
> ```

TIL You can do this! Sweet!

**Pull request merged**
