### PR TITLE
Fix missing link in drakeQPControllerLcmTranslator

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Since @63c53c22276a (#4042), `drakeQPControllerLcmTranslator` uses `RigidBodyTree`, but was not linking to `drakeRBSystem`, resulting in a link error. Add the missing link.

+@jamiesnape (CMake), +@siyuanfeng-tri (for breaking it :smile:) for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4130)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@david-german-tri for platform review

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYVunE4-SBxgcZa6dG:-KWYVunE4-SBxgcZa6dH:b-wfbct0) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L16)):*
> ```CMake
>   add_library(drakeQPControllerLcmTranslator lcm_utils.cc)
>   target_link_libraries(drakeQPControllerLcmTranslator
>     drakeRBSystem
> ```

Should this be `drakeRBM`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYVunE4-SBxgcZa6dG:-KWYWLe6PUCXW-5nRc1S:b-ujcjwl) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this be `drakeRBM`?
</details>
+1, `drakeRBSystem` is deprecated and I don't think it's in use here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWYXEymfzbJCTAQqoVT:bzjv3) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
> ```CMake
> target_link_libraries(drakeQPController
>   drakeOptimization
>   drakeRBSystem
> ```

should this be drakeRBM as well then? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWYXKkeKejaVrTjvxVW:b2nhswy) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> should this be drakeRBM as well then? 
</details>
Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWYX_MVgAbBO0cAROhB:b4wwjy) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yes
</details>
FTR, here are the source files included in `drakeRBM`:

https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/CMakeLists.txt#L10

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWYZ8BEiwFQ4bxIXfAQ:b39j7wr) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> FTR, here are the source files included in `drakeRBM`:
> 
> https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/CMakeLists.txt#L10
</details>
yes, i was looking at that as well. So I should never link to drakeRBSystem? that's some system1 thing? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWYZhw85J_o9968M69h:bo667bz) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
> So I should never link to drakeRBSystem? that's some system1 thing?
Correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWY_7TvNUTSjmkY0kPB:b-brznw7) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > So I should never link to drakeRBSystem? that's some system1 thing?
> Correct.
</details>
got it. 

since we are doing this, can someone double check if I am linking with other stuff that I am not supposed to? thanks.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-KWYXEymfzbJCTAQqoVS:-KWY_zeu6Z4-fZTSlBE5:buf6k2g) ([raw file](https://github.com/robotlocomotion/drake/blob/f8052583e1c4a00ebcf86fb6739db9f100ebcae4/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> got it. 
> 
> since we are doing this, can someone double check if I am linking with other stuff that I am not supposed to? thanks.. 
</details>
Okay, these are both `drakeRBM` now. I'll leave it to someone else to make any other changes as needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-:-KWYcweNEtKSGkEz-CAn:bg7igkv)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-:-KWYdReZ3nHu1O5xWyOV:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-:-KWYi6Da_a8O8xfj41Jm:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4130#-:-KWYiHjt9AVCKUnf81Jp:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot  linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jamiesnape** [comment]
The first retest phrase worked.

**Comment by mwoehlke-kitware** [comment]
Yeah... build queue lies if you aren't on the "all" view...

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
