### PR TITLE
SpatialInertia tetrahedron calculations always returns a valid spatial inertia.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@SeanCurtis-TRI 
FYI +@sherm1  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-:-NNE78Nw1b3PXevbPucv:baf0myg)* status: LGTM missing from assignees SeanCurtis-TRI(platform),sherm1(platform), missing label for release notes (waiting on @SeanCurtis-TRI and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Ah, so nice to see SpatialInertia restricted to actual physics!
Platform :lgtm: pending feature review of course

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-:-NNE8Zql8q88itxrrFsl:baepxrf)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some test shrapnel clean up.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-:-NNHdLcu0tg_nd_yJXww:b-q742q6)* status: 2 unresolved discussions, missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/test/spatial_inertia_test.cc` line 273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcc1gDurxHLivd9n8:-NNHcc1gDurxHLivd9n9:b-1wl2cg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L273)):*
> ```cpp
> 
>   // Ensure nothing changes if two arguments are switched (e.g., p1 and p2).
>   M_BB0_expected = SpatialInertia<double>(mass, p_B0Bcm, G_BB0);
> ```

nit: This line has become redundant. In fact, you should remove this and make the original definition `const`.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 314 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcxly21ixMG4qIMax:-NNHcxlzB577cTb8F0B8:bu511f8) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L314)):*
> ```cpp
> 
>   // Ensure nothing changes if two arguments are switched (e.g., p_AB2, p_AB3).
>   const double mass = M_BA_expected.get_mass();
> ```

nit: These four lines are now redundant. You grab all the components of `M_BA_expected` and feed them right back into `M_BA_expected` unchanged.

In this case, you can't make the original `const`, but you definitely don't have to redundantly recreate it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[`multibody/tree/test/spatial_inertia_test.cc` line 273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcc1gDurxHLivd9n8:-NNIx7-s7aeUzhkJpaYU:beo6sp8) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L273)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This line has become redundant. In fact, you should remove this and make the original definition `const`.
</blockquote></details>

We have a baby and bathwater situation here.

I didn't mean throw out the test where you perturb vertex order. That is a good test. What I mean is not to redefine `M_BBO_expected` redundantly. Just the one line.

Please put the test and the comment back.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 314 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcxly21ixMG4qIMax:-NNIxKc10mE7M7f2OVEC:b-ixh0l4) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L314)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: These four lines are now redundant. You grab all the components of `M_BA_expected` and feed them right back into `M_BA_expected` unchanged.

In this case, you can't make the original `const`, but you definitely don't have to redundantly recreate it.
</blockquote></details>

Same comment applies here. (I mentioned *four* lines, you deleted more.  :(

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`multibody/tree/test/spatial_inertia_test.cc` line 273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcc1gDurxHLivd9n8:-NNIjlvICjYjnQ40JSGt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L273)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This line has become redundant. In fact, you should remove this and make the original definition `const`.
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 314 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-NNHcxly21ixMG4qIMax:-NNIjmwD-Gh076uMFIIQ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcd8733467306117450131e517be7a3bc3b2438d/multibody/tree/test/spatial_inertia_test.cc#L314)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: These four lines are now redundant. You grab all the components of `M_BA_expected` and feed them right back into `M_BA_expected` unchanged.

In this case, you can't make the original `const`, but you definitely don't have to redundantly recreate it.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-:-NNJCTkF1Y-1tSOf847j:bm9o57a)* status: missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18725#-:-NNJDGJeE9TuL4NJY_dC:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
