### PR TITLE
Add pendulum_run_swing_up_test to Bazel

### LINKED ISSUE #5238: support adding drake_cc_binary as a drake_cc_test with some command line flags
For a specific example in cmake, see
https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Pendulum/CMakeLists.txt#L56

I'd like to do the equivalent in bazel.  I've added a drake_cc_binary for pendulum_run_swing_up, but now want to add a test that uses the command line arguments to run faster than realtime (without having to write a one-off python wrapper).  

when asked quickly, @jwnimmer-tri said "We should share that shell script across BUILD files though I think, or wrap it up into a `cc_noncrash_test` macro if we wanted to do that."

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #5238.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5266)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by RussTedrake** [comment]
perhaps also a line or two of documentation somewhere so that this gets found and used (properly)?

**Comment by jwnimmer-tri** [comment]
Perhaps if I mimic'd all (most?) existing examples of CMake "run this program for N non-realtime seconds" into Bazel, that would be enough?  My intuition is that copy-paste is more likely how people will learn this versus documentation.

Though also I think I will add more comments into `exec.sh` to help with this as well.

**Comment by jwnimmer-tri** [comment]
With the new push, every directory that (1) has BUILD files and (2) has some CMake non-GTest `add_test` has at least one sample of using Bazel `sh_test` for the same purpose.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-KdfFuKgO2LaXjrBjkYO:b-s0ahrj)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-KdfH8yGXFq-HOzxnSwC:bbpa3zd)*

**Comment by rpoyner-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-KdfHznzkmHlIb8Xe65m:-KdfHzo-G2kM5ORon6Zx:b-g038lx) ([raw file](https://github.com/robotlocomotion/drake/blob/6fcf086b5391ff3b686758edd769b457d9e80b4b/drake/examples/kuka_iiwa_arm/BUILD#L138)):*
> ```Python
>     args = [
>         "$(location :iiwa_wsg_simulation)",
>         "-simulation_sec=0.01",
> ```

one dash, or two?

---

*[drake/examples/schunk_wsg/BUILD, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-KdfIA1Jq2ivdf-FEkvt:-KdfIA1Jq2ivdf-FEkvu:b-g038lx) ([raw file](https://github.com/robotlocomotion/drake/blob/6fcf086b5391ff3b686758edd769b457d9e80b4b/drake/examples/schunk_wsg/BUILD#L102)):*
> ```Python
>     args = [
>         "$(location :schunk_wsg_simulation)",
>         "-simulation_sec=0.1",
> ```

one dash, or two?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-KdfHznzkmHlIb8Xe65m:-Kdfgy2GMFaQDNspJTcE:bs5xyuv) ([raw file](https://github.com/robotlocomotion/drake/blob/6fcf086b5391ff3b686758edd769b457d9e80b4b/drake/examples/kuka_iiwa_arm/BUILD#L138)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

one dash, or two?
</blockquote></details>

Done.  (_Meta_.)

---

*[drake/examples/schunk_wsg/BUILD, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-KdfIA1Jq2ivdf-FEkvt:-Kdfh-YjDPrJmaPWNBNv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6fcf086b5391ff3b686758edd769b457d9e80b4b/drake/examples/schunk_wsg/BUILD#L102)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

one dash, or two?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266)*

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri PTAL.

+@sammy-tri for platform review, please.

---

Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-Kdfh66-q6kOW4ozmDzn:bljkpb7)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r2.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-KdfiUHiz13P1TYJfuDC:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-KdgI6Mhx6HLA6lSi-ev:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: for automotive blessing.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5266#-:-Kdh9_SrsSmQRCV9qQci:b-b69e66)*

**Comment by jwnimmer-tri** [comment]
Well, the mac build never happened somehow.  I will merge anyway, and deal with Continuous if there's a problem.

**Pull request merged**
