### PR TITLE
[geometry] Remove deprecated code 2022-09

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17812)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17812#-:-NAyn6bGBC8DGPTwNrXo:bxqo58p)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by EricCousineau-TRI** [comment]
For better or worse, this has "broken" Anzu. In upgrading from cbde16d314 to 215ee5448b:
- The old Bazel targets did not have `deprecation` set, so we left them in.
- Somehow, Anzu was able to access `internal_render_engine_vtk` (at least as before upgrade). After upgrade, Anzu connect access it.

Debugging in Anzu PR 9428

**Comment by EricCousineau-TRI** [comment]
Ah, yup, remove of this:
```
# TODO(jwnimmer-tri) Remove this after deprecation 2022-09-01.
exports_files(["internal_render_engine_vtk.h"])
```

**Comment by EricCousineau-TRI** [comment]
Third break was that `@drake//geometry/render:render` was also made private.
Thankfully, though, I could just remove it (it was not directly used).

**Comment by jwnimmer-tri** [comment]
> Third break was that `@drake//geometry/render:render` was also made private.

Oops, that was a mistake in the PR.

Hotfix posted at #17841.

**Pull request merged**
