### PR TITLE
Remove unused include in parser_sdf

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4316)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4316#-:-KXqpATxAK-vJdjlIAEN:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4316)*

**Comment by jwnimmer-tri** [comment]
Really, _no_ builds started?
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
:lgtm: Note the mismatch between the PR's name and the file changed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4316#-:-KXsJ8LCd0PPsDtg-_JO:b-721348)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Pull request merged**
