### PR TITLE
Extracts RigidBodyTree::AddFloatingJoint() and DrakeJoint::FloatingBaseType() Into Their Own Files

### PR DESCRIPTION
**Pull request by liangfok**
This change was shown to decrease build times by ~3 minutes and memory footprint by a whopping 3GB. For more information, see: https://github.com/RobotLocomotion/drake/issues/2074#issuecomment-244994773.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3358)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review please.

---

Review status: 0 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR-EChUoqkLHbhXBdag:blpvwg6)*

**Comment by liangfok** [comment]
FTR, here's a discussion about the original introduction of `RigidBodyTree::AddFloatingJoint()`: https://github.com/robotlocomotion/drake/pull/2053#issuecomment-208373351

---

Review status: 0 of 46 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR-GVYkeew7FaSBf_NE:bfrkw6l)*

**Comment by david-german-tri** [comment]
Review status: 0 of 46 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/parser_common.cc, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-YG8aJVNLd4S_v8Pb:-KR-YG8aJVNLd4S_v8Pc:b-vnnm7w) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.cc#L3)):*
> ```cpp
> #include "drake/systems/plants/parser_common.h"
> 
> #include "drake/systems/plants/joints/DrakeJoints.h"
> ```

Please don't add new uses of `DrakeJoints.h`.  Instead, include the joint types you actually use.  

---

*[drake/systems/plants/parser_common.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-XdT6OOt1vY5CRFE0:-KR-XdT6OOt1vY5CRFE1:b-1tvaf0) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.h#L18)):*
> ```objc
>  * not already have a parent. Typically, @p link_indices is created while
>  * calling RigidBodyTree::add_rigid_body(). The floating joints connect the
>  * links and of their child branches to the rigid body tree.
> ```

Please also explain why this is only useful for parsers.

---

*[drake/systems/plants/parser_common.h, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-Xh9D7QdGEUfJCnh9:-KR-Xh9D7QdGEUfJCnhA:bbxdmrl) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.h#L41)):*
> ```objc
>  */
> DRAKERBM_EXPORT
> int AddFloatingJoint(
> ```

Should this be `DRAKE_DEPRECATED`?

---

*[drake/systems/plants/parser_urdf.cc, line 1045 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-XsuAiuqWl3ZR1fTn:-KR-XsuAiuqWl3ZR1fTo:bd5d6lg) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_urdf.cc#L1045)):*
> ```cpp
>   // rest of the rigid body tree.
>   AddFloatingJoint(tree, actual_floating_base_type, link_indices,
>                           weld_to_frame);
> ```

indentation

---

*[drake/systems/plants/joints/floating_base_types.h, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-Wu2gEv7ua_Xk_8ke:-KR-Wu2gEv7ua_Xk_8kf:bqttceq) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/joints/floating_base_types.h#L3)):*
> ```objc
> #pragma once
> 
> // TODO(liang.fok) Place this inside proper namespace.
> ```

These need to be namespaced, and it would be no less incremental to do it now, since you're touching every single line where they appear anyway.

---

*[drake/systems/plants/joints/floating_base_types.h, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-WzeLWToYgI0ue9V7:-KR-WzeLWToYgI0ue9V8:bwfpna8) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/joints/floating_base_types.h#L4)):*
> ```objc
> 
> // TODO(liang.fok) Place this inside proper namespace.
> enum FloatingBaseType { FIXED = 0, ROLLPITCHYAW = 1, QUATERNION = 2 };
> ```

kFixed, kRollPitchYaw, kQuaternion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358)*

**Comment by david-german-tri** [comment]
Also, there are merge conflicts, and the CI failures on Windows appear genuine.  It looks like namespacing the joint type enum will fix them, though.

---

Reviewed 7 of 47 files at r1, 40 of 41 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR-YQhH3_MUYCTrB9gH:bxh8xn6)*

**Comment by jwnimmer-tri** [comment]
@liangfok FYI the #3021 that just merged.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
Review status: 3 of 47 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/parser_common.cc, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-YG8aJVNLd4S_v8Pb:-KR-fkVZNMANeX_mvjBS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.cc#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please don't add new uses of `DrakeJoints.h`.  Instead, include the joint types you actually use.  
</details>
Done.

---

*[drake/systems/plants/parser_common.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-XdT6OOt1vY5CRFE0:-KR-fmA2lRpph9eXa_9D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please also explain why this is only useful for parsers.
</details>
Done.

---

*[drake/systems/plants/parser_common.h, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-Xh9D7QdGEUfJCnh9:-KR-iDUkNsnbg97JCm1d:b-thm833) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_common.h#L41)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Should this be `DRAKE_DEPRECATED`?
</details>
Not yet since it's still used by the parsers. I added a TODO and https://github.com/RobotLocomotion/drake/issues/3361 to track its eventual deprecation.

---

*[drake/systems/plants/parser_urdf.cc, line 1045 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-XsuAiuqWl3ZR1fTn:-KR-cLAjKx4pVI6M15ee:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/parser_urdf.cc#L1045)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> indentation
</details>
Done.

---

*[drake/systems/plants/joints/floating_base_types.h, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-Wu2gEv7ua_Xk_8ke:-KR11vH1w21BTKZTzkgz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/joints/floating_base_types.h#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> These need to be namespaced, and it would be no less incremental to do it now, since you're touching every single line where they appear anyway.
</details>
Done.

---

*[drake/systems/plants/joints/floating_base_types.h, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR-WzeLWToYgI0ue9V7:-KR12yu7NfkbA2Cv9UqX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f6c03d45196dfd996544e677673d6fd9b9bbdbe/drake/systems/plants/joints/floating_base_types.h#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> kFixed, kRollPitchYaw, kQuaternion
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
Dear @david-german-tri, this PR passed the following two CI pre-merge tests and is thus ready for another round of review.

* https://drake-jenkins.csail.mit.edu/job/experimental/4372/ 
* https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/98/

---

Review status: 3 of 47 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR39MIm6E3plfnTuHFq:b-wcjq3t)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 41 files at r2, 16 of 44 files at r3, 28 of 28 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_common.h, line 50 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3sQhKOrJHb_aUarwh:-KR3sQhKOrJHb_aUarwi:bgnqtey) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/parser_common.h#L50)):*
> ```objc
> int AddFloatingJoint(
>     RigidBodyTree* tree,
>     drake::systems::plants::joints::FloatingBaseType floating_base_type,
> ```

BTW, you don't have to say `drake::` here, since you're already in the `drake` namespace.  There are probably other similar cases.

---

*[drake/systems/plants/RigidBodySystem.h, line 196 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3sieJ1d0rGcorJrCN:-KR3sieK3zXx3zynke_y:ba5mwm7) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/RigidBodySystem.h#L196)):*
> ```objc
>   drake::parsers::ModelInstanceIdTable AddModelInstanceFromUrdfString(
>       const std::string& urdf_string, const std::string& root_dir = ".",
>       const drake::systems::plants::joints::FloatingBaseType
> ```

BTW, this file seems like it would benefit from `using`-decls

---

*[drake/systems/plants/joints/floating_base_types.h, line 10 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3svk2z4_4MIuJ4XE2:-KR3svk2z4_4MIuJ4XE3:b8tvr6m) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/joints/floating_base_types.h#L10)):*
> ```objc
> enum FloatingBaseType { kFixed = 0, kRollPitchYaw = 1, kQuaternion = 2 };
> 
> }  // namespace joints
> ```

BTW, this namespace is pretty verbose, but I agree it's the correct choice for now.  Maybe in the future we should flatten the directory structure - perhaps remove `plants`, or promote `plants` to be a child of `drake`.  I leave it to the dynamics team's judgment.

---

*[drake/systems/plants/test/load_model_test.cc, line 161 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3tCiZ3axvktil1tMr:-KR3tCi_zZpogMWAijia:b-oqrieu) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/test/load_model_test.cc#L161)):*
> ```cpp
>       drake::GetDrakePath() +
>           "/systems/plants/test/models/cylindrical_0dof_robot." + GetParam(),
>       drake::systems::plants::joints::kFixed, weld_to_frame);
> ```

BTW, oddly inconsistent not to using-decl this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR409KCdFJ7pVG-BVh1:bnfp4nl)*

**Comment by liangfok** [comment]
+@ggould-tri for platform review please. Thanks!

---

Review status: 42 of 47 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/parser_common.h, line 50 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3sQhKOrJHb_aUarwh:-KR43XDUJReFMk5aockD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/parser_common.h#L50)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, you don't have to say `drake::` here, since you're already in the `drake` namespace.  There are probably other similar cases.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.h, line 196 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3sieJ1d0rGcorJrCN:-KR43QPX0XcpFgbuF8A7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/RigidBodySystem.h#L196)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this file seems like it would benefit from `using`-decls
</details>
Done.

---

*[drake/systems/plants/joints/floating_base_types.h, line 10 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3svk2z4_4MIuJ4XE2:-KR41sT1fsZIYgCty5DF:b-prbwis) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/joints/floating_base_types.h#L10)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this namespace is pretty verbose, but I agree it's the correct choice for now.  Maybe in the future we should flatten the directory structure - perhaps remove `plants`, or promote `plants` to be a child of `drake`.  I leave it to the dynamics team's judgment.
</details>
I agree it is verbose. Here's a tracker issue: https://github.com/RobotLocomotion/drake/issues/3373

---

*[drake/systems/plants/test/load_model_test.cc, line 161 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR3tCiZ3axvktil1tMr:-KR417FKtdqpBwPgTmwQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1f32d1c351e4c646009c3ee6e3e906bb2a4395/drake/systems/plants/test/load_model_test.cc#L161)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, oddly inconsistent not to using-decl this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR45ELECu_0ixEqLMrH:b-yqnxb4)*

**Comment by ggould-tri** [comment]
Looks good -- a real improvement in the factoring.  Several comments below.

---

Reviewed 1 of 47 files at r1, 5 of 44 files at r3, 11 of 28 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/demo_multi_car.cc, line 26 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR48sfFNfQn8XWm1TkP:-KR48sfFNfQn8XWm1TkQ:b-wlaeld) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/demo_multi_car.cc#L26)):*
> ```cpp
> using drake::BotVisualizer;
> using drake::NullVector;
> using drake::cascade;
> ```

All four of the above seem to be unnecessary.  N`AffineSystem` and `NullVector` are unused.  `BotVisualizer` and `cascade` are used only with the `drake::` qualifier and so do not need `using` declarations.

---

*[drake/examples/Cars/multi_car_sim_lcm.cc, line 19 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR49OOusvmeYAucpO18:-KR49OOusvmeYAucpO19:b-raszlo) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/multi_car_sim_lcm.cc#L19)):*
> ```cpp
> 
> using drake::BotVisualizer;
> using drake::Gain;
> ```

`Gain` appears to be unused.

---

*[drake/systems/plants/parser_common.cc, line 99 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4A4-tPHjahjKBWDWp:-KR4A4-tPHjahjKBWDWq:b-74v2je) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/systems/plants/parser_common.cc#L99)):*
> ```cpp
>     throw std::runtime_error(
>         "No root bodies found. Every body referenced by the supplied list of "
>         "body indices has a joint connecting it to some other body).  You're "
> ```

FYI -- Close paren without corresponding open paren.

---

*[drake/systems/plants/parser_common.h, line 49 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4816N9zWHtBTEybl9:-KR4816N9zWHtBTEyblA:bvbvjah) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/systems/plants/parser_common.h#L49)):*
> ```objc
> DRAKERBM_EXPORT
> int AddFloatingJoint(
>     RigidBodyTree* tree,
> ```

Google styleguide specifies output parameters come after input parameters:  https://google.github.io/styleguide/cppguide.html#Function_Parameter_Ordering

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR4AGmYmfHXDJK8sNjX:bak5xz3)*

**Comment by liangfok** [comment]
@ggould-tri: Thanks for the review. I addressed your comments. PTAL.

---

Review status: 40 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/demo_multi_car.cc, line 26 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR48sfFNfQn8XWm1TkP:-KR4aRhG-R4eVIUhE8vW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/demo_multi_car.cc#L26)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> All four of the above seem to be unnecessary.  N`AffineSystem` and `NullVector` are unused.  `BotVisualizer` and `cascade` are used only with the `drake::` qualifier and so do not need `using` declarations.
</details>
Done.

---

*[drake/examples/Cars/multi_car_sim_lcm.cc, line 19 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR49OOusvmeYAucpO18:-KR4aXguCFGWz4_dfett:b-u52pvh) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/multi_car_sim_lcm.cc#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> `Gain` appears to be unused.
</details>
Done. I removed _all_ of these using statements since we're in the `drake` namespace.

---

*[drake/systems/plants/parser_common.cc, line 99 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4A4-tPHjahjKBWDWp:-KR4b0CELIAByH-Oyx5-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/systems/plants/parser_common.cc#L99)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- Close paren without corresponding open paren.
</details>
Done.

---

*[drake/systems/plants/parser_common.h, line 49 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4816N9zWHtBTEybl9:-KR4czmxPnTu0EYLE3PI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/systems/plants/parser_common.h#L49)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Google styleguide specifies output parameters come after input parameters:  https://google.github.io/styleguide/cppguide.html#Function_Parameter_Ordering
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR4d-v2XUWqOWgFHVMa:b7xp0d6)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 41 files at r2, 8 of 44 files at r3, 10 of 28 files at r5, 8 of 8 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/demo_multi_car.cc, line 26 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR48sfFNfQn8XWm1TkP:-KR4g6fkAmVumrlr3Kq-:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/demo_multi_car.cc#L26)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> All four of the above seem to be unnecessary.  N`AffineSystem` and `NullVector` are unused.  `BotVisualizer` and `cascade` are used only with the `drake::` qualifier and so do not need `using` declarations.
</details>
OK

---

*[drake/examples/Cars/multi_car_sim_lcm.cc, line 19 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR49OOusvmeYAucpO18:-KR4gCamGV9pJiEpx_8X:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/c0a2fdab2e7690fc9136df1af193a5b5db98f0de/drake/examples/Cars/multi_car_sim_lcm.cc#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> `Gain` appears to be unused.
</details>
OK

---

*[drake/systems/plants/parser_urdf.cc, line 1116 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4gq0RFdRC66jzEBOa:-KR4gq0RFdRC66jzEBOb:b-z2bhrn) ([raw file](https://github.com/robotlocomotion/drake/blob/1bc6e61a44b4ea57f8d624c6c7eef021e4736f10/drake/systems/plants/parser_urdf.cc#L1116)):*
> ```cpp
>   xml_doc.Parse(urdf_string.c_str());
>   return ParseUrdf(&xml_doc, package_map, root_dir, kRollPitchYaw,
>             weld_to_frame, tree);
> ```

FYI -- unusual indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR4hysNQbGsSsLCU1BU:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358)*

**Comment by liangfok** [comment]
I addressed all reviewer comments and am now waiting for CI to pass.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/plants/parser_urdf.cc, line 1116 \[r7\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-KR4gq0RFdRC66jzEBOa:-KR4iNK9jaI79HggFrz_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1bc6e61a44b4ea57f8d624c6c7eef021e4736f10/drake/systems/plants/parser_urdf.cc#L1116)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- unusual indentation.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR4iX4sRfleSxuVr2Uc:b-ykj178)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

(I doubt the failure is related to this PR, but let's be sure.)

**Comment by david-german-tri** [comment]
Hm, I guess it's real, and it's not showing up on continuous so this PR must be to blame, somehow.  https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=104708

**Comment by liangfok** [comment]
One more try since the problem appears to be at the super-build level.

@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
OK I admit the following error must be real:

```
CMake Error at /home/ubuntu/workspace/experimental/c5b85b52/cmake/mex.cmake:102 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:143 (mex_setup)


SWIG_EXECUTABLE: /home/ubuntu/workspace/experimental/c5b85b52/build/install/bin/swig
Checking if Swig has Matlab support... yes
Found Swig with Matlab support
CMake Error at /home/ubuntu/workspace/experimental/c5b85b52/build/install/share/cmake/SwigMatlab.cmake:43 (message):
  Please run 'mex_setup(REQUIRED)' which is provided by mex.cmake in
  https://github.com/RobotLocomotion/cmake before using this macro.
Call Stack (most recent call first):
  bindings/swig/CMakeLists.txt:55 (add_swig_matlab_module)
```

Commencing investigation...

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR5guIqsSZur4SkLJ8h:b-otsscc)*

**Comment by liangfok** [comment]
Whoa....bizarre situation as indicated by print statement:

```
18:35:00 -- ************************** MATLAB ROOT: _matlab_root=This change was shown to decrease build times by
```

---

Review status: 48 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3358#-:-KR5uzzPD_hcR3O5W3rI:b-d62b5b)*

**Comment by liangfok** [comment]
I just removed some text that from this issue's original description. Let's see if the above error continues to persist.

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
All checks passed. Got two LGTMs. Will proceed to merge...

**Comment by liangfok** [comment]
Oops. Accidentally clicked close button. Will merge in the morning :confused: .

**Pull request merged**
