### PR TITLE
Update pkg_config_repository

### PR DESCRIPTION
**Pull request by soonho-tri**
- Handle `-Wl,-rpath` issue reported in https://github.com/RobotLocomotion/drake/issues/7387#issuecomment-359952616.
 - Add `pkg_config_paths` argument to `pkg_config_repository`.
 - Update the debs for dreal and libibex-dev (included in this PR to test the above two items).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7858)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3iV6bQZRR2wdIx3Owk:bpava0n)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3ig0hrdAOPRe622pOo:b-g5sb9l)*

**Comment by jamiesnape** [comment]
Add `@dreal` here, I think, otherwise, unfortunately, the RPATH will not propagate: https://github.com/RobotLocomotion/drake/blob/e7dd311ec73e889a17342840bb72651f2dbe18a4/tools/install/libdrake/BUILD.bazel#L122

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please. I've added "@dreal" at drake/tools/install/libdrake/BUILD.bazel. Thank you!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3ig5KGUVvJlPBdht3r:b1xo82i)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3izR0yt5qOmLGjwfEI:b-g5sb9l)*

**Comment by soonho-tri** [comment]
@jamiesnape , `//bindings/pydrake:common_install_test` still fails. I think it's because of the same reason that we have in https://github.com/RobotLocomotion/drake/issues/7283 ?

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3j8Oh8OTZhfTKOaBT6:bqhofnm)*

**Comment by soonho-tri** [comment]
FYI, setting up `export LD_LIBRARY_PATH=/opt/dreal/4.18.01.3/lib:/opt/libibex/2.6.5/lib` makes `//bindings/pydrake:common_install_test` pass.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3j98CGbzSXW2yFNOKZ:b-owdu6l)*

**Comment by jamiesnape** [comment]
Something is not right with the install, I think. Whatever is being added in this PR appears to be getting stripped out during the install.

**Comment by jamiesnape** [comment]
```
drake/bazel-bin/tools/install/libdrake$ objdump -a -x libdrake.so | grep RPATH
  RPATH                $ORIGIN/../../../_solib_k8/_U@ignition_Urndf_S_S_Cignition_Urndf___Uexternal_Signition_Urndf:$ORIGIN/../../../_solib_k8/_U@ignition_Umath_S_S_Cignition_Umath___Uexternal_Signition_Umath:$ORIGIN/../../../_solib_k8/_U@bullet_S_S_CBulletCollision___Uexternal_Sbullet:$ORIGIN/../../../_solib_k8/_U@bullet_S_S_CLinearMath___Uexternal_Sbullet:$ORIGIN/../../../_solib_k8/_U@tinyobjloader_S_S_Ctinyobjloader___Uexternal_Stinyobjloader:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkFiltersSources___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkFiltersGeneral___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonComputationalGeometry___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkIOGeometry___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkIOLegacy___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkIOCore___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkIOImage___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkDICOMParser___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_Cvtkmetaio___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkRenderingOpenGL2___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkRenderingCore___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonColor___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkFiltersCore___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkFiltersGeometry___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonExecutionModel___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonDataModel___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonSystem___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonTransforms___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonMisc___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonMath___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_CvtkCommonCore___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_Cvtksys___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@vtk_S_S_Cvtkglew___Uexternal_Svtk_Slib:$ORIGIN/../../../_solib_k8/_U@scs_S_S_Cscsdir___Uexternal_Sscs:$ORIGIN/../../../_solib_k8/_U@lcm_S_S_Clcm___Uexternal_Slcm:/usr/lib/x86_64-linux-gnu:/opt/dreal/4.18.01.3/lib:/opt/libibex/2.6.5/lib:/usr/lib/gcc/x86_64-linux-gnu/5:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib:/lib/../lib:/usr/lib/../lib:/usr/lib/gcc/x86_64-linux-gnu/5/../../..
```

```
/opt/drake/lib$ objdump -a -x libdrake.so | grep RPATH
  RPATH                $ORIGIN/:/usr/lib/x86_64-linux-gnu/
```

**Comment by jamiesnape** [comment]
The assumption that libraries outside of the install prefix do not matter is no longer true:
https://github.com/RobotLocomotion/drake/blob/8ee580cde1758bb816a6cb4fde88b29dde3d5925/tools/install/install.py.in#L175-L177

**Comment by jamiesnape** [comment]
This needs to change: https://github.com/RobotLocomotion/drake/blob/8ee580cde1758bb816a6cb4fde88b29dde3d5925/tools/install/install.py.in#L183-L185

The quick hack to try here is to allow RPATHS beginning `/opt` through.

**Comment by soonho-tri** [comment]
I've changed the lines (183 -- 185) to be:
```python
        if len(ldd_result) < 2 or \
                not (ldd_result[1] == "not found" or
                     ldd_result[1].startswith(prefix) or
                     ldd_result[1].startswith("/opt/")):
            continue
```
But it still fails to pass line 191. Can you help?
https://github.com/RobotLocomotion/drake/blob/8ee580cde1758bb816a6cb4fde88b29dde3d5925/tools/install/install.py.in#L188-L192

**Comment by jamiesnape** [comment]
Yes. Looking closer, we need more than that. I will work on it now.

**Comment by soonho-tri** [comment]
@jamiesnape , thank you!

**Comment by jamiesnape** [comment]
@soonho-tri Can you grab the head commit from https://github.com/RobotLocomotion/drake/pull/7869 ?

**Comment by soonho-tri** [comment]
> @soonho-tri Can you grab the head commit from #7869 ?

Done. It's included in this PR.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by soonho-tri** [comment]
Checked that both of unprovisioned builds passed.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3nO8GDuvrX_-JmkFr2:b6lgdvx)*

**Comment by soonho-tri** [comment]
> One side question, which you can feel free to punt on. Should we actually be respecting PKG_CONFIG_PATH set by the user? One side effect I have seen (unrelated to this PR) is that I had the wrong libpng linked into my build when I had /opt/X11/lib/pkgconfig in my system PKG_CONFIG_PATH.

I have no strong opinion on it. Respecting the `PKG_CONFIG_PATH` environment variable was how it worked before. So I wanted to keep the semantics (but overriding it by prepending user-provided ones to it).

@jwnimmer-tri , can you share your opinion on it? Also can you platform-review it? Otherwise, I'll ask today's platform-reviewer for it.

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lint/buildifier-tables.json, line 54 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3nQosQLzawtubk8b4I:-L3nh-cHhpNRaQv_LSY_:baprg93) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b3d7aaeaf2d069d3f6568f9cbcd43caa26071a/tools/lint/buildifier-tables.json#L54)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Personally I would put this somewhere around 200-202 since it affects the `pkg-config` call like `atleast_version` and `static`.
</blockquote></details>

Good point. I'll hold until I have comments in platform-review.

---

*[tools/workspace/pkg_config.bzl, line 251 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3nRNTptpMHbgzZXMG-:-L3nh8Cj5CJ0YD1Kny7S:b-2hlqch) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b3d7aaeaf2d069d3f6568f9cbcd43caa26071a/tools/workspace/pkg_config.bzl#L251)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW You could make an argument for `extra_pkg_config_paths`, though if I were writing this PR I probably would have written `pkg_config_paths` also.
</blockquote></details>

I was thinking about the point. I preferred this one because we don't have an existing `pkg_config_paths` attribute so `extra_` sounds redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3nfv4wWeMn6bmi-ONN:bvyosiq)*

**Comment by jamiesnape** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 251 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3nRNTptpMHbgzZXMG-:-L3nRSAAlHQRgQ4IiSTm:bg9bt9b) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b3d7aaeaf2d069d3f6568f9cbcd43caa26071a/tools/workspace/pkg_config.bzl#L251)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I was thinking about the point. I preferred this one because we don't have an existing `pkg_config_paths` attribute so `extra_` sounds redundant.
</blockquote></details>

Certainly the `extra` would have a slightly different context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858)*

**Comment by jamiesnape** [comment]
@soonho-tri, #7869 has merged. Can you rebase on `master`?

**Comment by soonho-tri** [comment]
> @soonho-tri, #7869 has merged. Can you rebase on master?

Done.

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lint/buildifier-tables.json, line 54 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3nQosQLzawtubk8b4I:-L3o3TXb2lZOLHdGmA5T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b3d7aaeaf2d069d3f6568f9cbcd43caa26071a/tools/lint/buildifier-tables.json#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Good point. I'll hold until I have comments in platform-review.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3o3W5jvG5rCUY6rmhR:b-jnz8oh)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858)*

**Comment by soonho-tri** [comment]
+@sherm1 for platform-review please (per rotation). Thank you.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3oJvdcKU98yf_pkXDx:byhxcx4)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3oT5lkDaR1elo-nG1A:-L3oT5lmCKHzrMWriSJy:b-kci4vd) (no related file):*
FYI

> > One side question, which you can feel free to punt on. Should we actually be respecting PKG_CONFIG_PATH set by the user? One side effect I have seen (unrelated to this PR) is that I had the wrong libpng linked into my build when I had /opt/X11/lib/pkgconfig in my system PKG_CONFIG_PATH.
> 
> I have no strong opinion on it. Respecting the PKG_CONFIG_PATH environment variable was how it worked before. So I wanted to keep the semantics (but overriding it by prepending user-provided ones to it).
> @jwnimmer-tri , can you share your opinion on it? Also can you platform-review it? Otherwise, I'll ask today's platform-reviewer for it.

For some reason, I thought I remembered that macOS failed to work when `PKG_CONFIG_PATH` was zeroed out -- that homebrew had special entries there that needed to be picked up?

On Ubuntu the proper value is empty, so certainly in that case I am happy to zero it out.  If the same works for macOS, then it seems like a fine idea.

I'm not 100% certain how environment variables relate to repository rules.  I know if you declare them, then you are re-run when they change, but I'm unclear on whether if they are omitted from both any action_env setting in any rcfile and you don't list them in your repostiory rule, if the exec call of `pkg-config` has them absent, or inherited from the user.  Build rule actions definitely drop everything note listed, but repository rules give you a footgun so you have to be careful how to use it.  We'd want to understand exactly what's happening if / when we change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858)*

**Comment by sherm1** [comment]
Superficial platform :lgtm: with one BTW that probably reveals my ignorance of Drake's install scheme more than anything.

---

Reviewed 3 of 8 files at r1, 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/dreal/repository.bzl, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3oqDmXHTRFFsF1irCs:-L3oqDmXHTRFFsF1irCt:bxu91qq) ([raw file](https://github.com/robotlocomotion/drake/blob/e3349e86fd58ec0dff7c305d063368a36383ef84/tools/workspace/dreal/repository.bzl#L13)):*
> ```Python
>                           pkg_config_paths = [
>                               "/opt/dreal/4.18.01.3/lib/pkgconfig",
>                               "/opt/libibex/2.6.5/share/pkgconfig",
> ```

BTW does this have to be kept in sync with install_prereqs.sh? I see the same version numbers there. If so, consider comments in both places as an attempt to make sure some future updater knows to edit both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L3oquDVfUO2Yb-xpjOC:b-3c8gsw)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3oT5lkDaR1elo-nG1A:-L41machpQTLn8UvOsbz:b-ymu0a9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI

> > One side question, which you can feel free to punt on. Should we actually be respecting PKG_CONFIG_PATH set by the user? One side effect I have seen (unrelated to this PR) is that I had the wrong libpng linked into my build when I had /opt/X11/lib/pkgconfig in my system PKG_CONFIG_PATH.
> 
> I have no strong opinion on it. Respecting the PKG_CONFIG_PATH environment variable was how it worked before. So I wanted to keep the semantics (but overriding it by prepending user-provided ones to it).
> @jwnimmer-tri , can you share your opinion on it? Also can you platform-review it? Otherwise, I'll ask today's platform-reviewer for it.

For some reason, I thought I remembered that macOS failed to work when `PKG_CONFIG_PATH` was zeroed out -- that homebrew had special entries there that needed to be picked up?

On Ubuntu the proper value is empty, so certainly in that case I am happy to zero it out.  If the same works for macOS, then it seems like a fine idea.

I'm not 100% certain how environment variables relate to repository rules.  I know if you declare them, then you are re-run when they change, but I'm unclear on whether if they are omitted from both any action_env setting in any rcfile and you don't list them in your repostiory rule, if the exec call of `pkg-config` has them absent, or inherited from the user.  Build rule actions definitely drop everything note listed, but repository rules give you a footgun so you have to be careful how to use it.  We'd want to understand exactly what's happening if / when we change it.
</blockquote></details>

Thanks for the input. I've changed the `pkg_config.bzl` file not to respect the `PKG_CONFIG_PATH` environment variable set by the user. I locally tested that it works on my macs. 

+(status: do not merge) to wait for unprovisioned builds.

---

*[tools/workspace/dreal/repository.bzl, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-L3oqDmXHTRFFsF1irCs:-L41m6SbczG_w2s5ypbo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3349e86fd58ec0dff7c305d063368a36383ef84/tools/workspace/dreal/repository.bzl#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this have to be kept in sync with install_prereqs.sh? I see the same version numbers there. If so, consider comments in both places as an attempt to make sure some future updater knows to edit both.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L41m_8mb6ESGR99GwPt:b-g5sb9l)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L41zwA0elhrVnRBvQfq:b-3rlbf1)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7858#-:-L42PREL2n76dPMjh602:b-3rlbf1)*

**Pull request merged**
