### PR TITLE
Removes name of system from start of Doxygen comment blocks in drake/automotive/

### PR DESCRIPTION
**Pull request by liangfok**
The motivation for this is this comment: https://reviewable.io/reviews/robotlocomotion/drake/5463#-Kf4ng3kYHfYTieWm6a2.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5482)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for all three levels of review please.

\cc: @jadecastro and @maddog-tri 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-:-Kf9QgzmjqfSlG5MotxS:b35mmfi)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-Kf9Rt5lnHVSYEo8EPqG:b17qqrs) (no related file):*
I am not entirely sure that we should do this, and would like others' input.

The code review defect that kicked this off was repeating a _function_ name atop a function's doxygen.  This PR removes the _class_ name from the class's overview documentation.  I don't think its obvious that the same conventions should apply for both, but perhaps they should.

Fundamentally, I also don't think polishing doxygen is ever worth much salt.  Either its understood or its not, and if not we fix the specific cases that matter.  My intuition here is "author's discretion".

@jadecastro and @maddog-tri and @rpoyner-tri what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by sherm1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-Kf9pmQbo9oyv7Op_ocP:b-tkopib) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not entirely sure that we should do this, and would like others' input.

The code review defect that kicked this off was repeating a _function_ name atop a function's doxygen.  This PR removes the _class_ name from the class's overview documentation.  I don't think its obvious that the same conventions should apply for both, but perhaps they should.

Fundamentally, I also don't think polishing doxygen is ever worth much salt.  Either its understood or its not, and if not we fix the specific cases that matter.  My intuition here is "author's discretion".

@jadecastro and @maddog-tri and @rpoyner-tri what do you think?
</blockquote></details>

BTW my 2 cents: harmless but not helpful to put the class name here. It will look repetitive in doxygen since that first sentence is the "brief" and comes out right next to the class name. Doxygen actually has a [configuration feature](http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_abbreviate_brief) that attempts to remove classname fluff from the brief. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by maddog-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-KfAPH4T0qUEf9BYUvgs:b-1tz939) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW my 2 cents: harmless but not helpful to put the class name here. It will look repetitive in doxygen since that first sentence is the "brief" and comes out right next to the class name. Doxygen actually has a [configuration feature](http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_abbreviate_brief) that attempts to remove classname fluff from the brief. 
</blockquote></details>

My sundry cents:
  * The "Identifier -- " prefix in the doxygen blocks is indeed dumb, whether the identifier is a function name or a class name.  It is pretty redundant in the source code (since the declared name is rarely far away, and often in the filename as well), and it is redundantly redundant in the doxygen output (which has the name in multiple bold headers and window-titlebars, etc).
  * I prefer doxygen source to yield both sensible brief descriptions and well-reading detailed descriptions.
  * (As per style guide) the first sentence of a _function_ description should be a declarative verb phrase (e.g., "Returns the most glorious value.").
  * I prefer the first sentence of a _class_ description to be a _noun phrase_ or a _complete sentence_ (e.g., either "A nonlinear rigid body bicycle model..." or "BicycleCar implements a nonlinear rigid body bicycle model...").
  * (I disagree with half the results of the changes here, because they are inconsistent w.r.t. to noun phrasing, but these were issues in the original doxygen.  Nonetheless, I completely agree with stripping the redundant prefixes.)

As to the _meta_ question of whether or not doxygen-polishing is worth it:  I'm generally in favor of stamping out anti-patterns --- because anti-patterns are by definition weeds that will spread their dumbness throughout the garden if left unchecked.  An anti-pattern in our documentation is still an anti-pattern in our work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-KfC0mNUU8tlbKaU0qNw:bgo7b5g) (no related file):*
I like that a lot, especially:
> I prefer the first sentence of a class description to be a noun phrase or a complete sentence (e.g., either "A nonlinear rigid body bicycle model..." or "BicycleCar implements a nonlinear rigid body bicycle model...").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by sherm1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-KfC2igHw_vJPSqoIb80:bb6mt9b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I like that a lot, especially:
> I prefer the first sentence of a class description to be a noun phrase or a complete sentence (e.g., either "A nonlinear rigid body bicycle model..." or "BicycleCar implements a nonlinear rigid body bicycle model...").
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by rpoyner-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-KfC3BMQsKpMWA2nyu-d:b-edq43h) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

I hate to even type in this review, since I feel like too much time has been wasted on it already.  That said:

* Repeating the identifier in the doxygen block is one of the few pointless redundancies that is not yet mandated by style guides. (Looking at you, end-brace comments.) For that reason alone, I support removing them, but am un-persuaded of the timeliness of a repository-wide jihad.
* Grammar wars are rarely productive, unless there is true confusion or ambiguity as revealed in an inspection. By all means get rid of typos, repeated words, vagueness, etc., but provide some evidence that someone misunderstood. 
* I don't feel like I have a good gauge of the utility of our doxygen output -- are people reading, using, trusting it? Is its value mainly for developers, on-ramp-ers, those just starting to choose tools? If it were better, would that boost the marginal value of improving it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by rpoyner-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by liangfok** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-Kf9Rt5k7FKKn1gjD8NG:-KfCaDGFXUz0wGCKr4Jr:bdktz0m) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I hate to even type in this review, since I feel like too much time has been wasted on it already.  That said:

* Repeating the identifier in the doxygen block is one of the few pointless redundancies that is not yet mandated by style guides. (Looking at you, end-brace comments.) For that reason alone, I support removing them, but am un-persuaded of the timeliness of a repository-wide jihad.
* Grammar wars are rarely productive, unless there is true confusion or ambiguity as revealed in an inspection. By all means get rid of typos, repeated words, vagueness, etc., but provide some evidence that someone misunderstood. 
* I don't feel like I have a good gauge of the utility of our doxygen output -- are people reading, using, trusting it? Is its value mainly for developers, on-ramp-ers, those just starting to choose tools? If it were better, would that boost the marginal value of improving it?
</blockquote></details>

Per comments above, I updated this PR to include a noun in the first sentence. I am definitely reading, using, and trusting the Doxygen-generate website, though I might be an outlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482)*

**Comment by jwnimmer-tri** [comment]
This is mostly +@jadecastro's comments, so once that's signed-off then :lgtm: automotive and platform.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-:-KfCauQREzFq2SR0O0KV:b-e6a1ng)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5482#-:-KfCei2x9AAMfP3k5RDK:bnfp4nl)*

**Pull request merged**
