### PR TITLE
Revert "[geometry:optimization] Add VPolytope from HPolyhedron (#16272)"

### PR DESCRIPTION
**Pull request by svenevs**
This reverts commit 23db6644d998d5184c4253372f4269296cfb0ab7.

Unofficial build cop test, unable to test with MOSEK locally.  There were a large number of weekly failures in CI all related to MOSEK builds and vpolytope tests, subset:

- [linux-bionic-clang-bazel-weekly-mosek-leak-sanitizer](https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-weekly-mosek-leak-sanitizer/38/changes)
- [linux-bionic-clang-bazel-weekly-mosek-release](https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-weekly-mosek-release/167/changes)
- [linux-focal-clang-bazel-weekly-mosek-release](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-weekly-mosek-release/84/changes)
- [linux-focal-gcc-bazel-weekly-mosek-release](https://drake-jenkins.csail.mit.edu/job/linux-focal-gcc-bazel-weekly-mosek-release/84/changes)

Failing with

```
[7:41:09 PM]  //geometry/optimization:vpolytope_test                                   FAILED in 2.0s
[7:41:09 PM]    /media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-weekly-mosek-leak-sanitizer/_bazel_ubuntu/25f813d23e1f46e003f8bffeb7e81337/execroot/drake/bazel-out/k8-dbg/testlogs/geometry/optimization/vpolytope_test/test.log
```

Issuing CI tests against mosek reverting the commit that seems to affect these tests, but this is not a build cop revert (yet).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16286)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please.
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-release please.

**Comment by svenevs** [comment]
CC @RussTedrake @mpetersen94 @TobiaMarcucci 

#16272 appears to have broken the MOSEK solver builds, I got a bunch of emails about it so opened a revert PR to test the builds.  Things are slow right now, which means it could be a good opportunity to fix it casually or alternatively revert now and use the above tests ( https://github.com/RobotLocomotion/drake/pull/16286#issuecomment-1001624717 ) in a future PR.  Unfortunately I cannot replicate the test locally and cannot advise on what specifically has broken.

**Comment by RussTedrake** [comment]
Thanks.  I will take a look today

**Comment by svenevs** [comment]
Fixed in #16287

**Pull request closed without merging**
