### PR TITLE
 	fixed case sensitivity issue for docker installation

### PR DESCRIPTION
**Pull request by ethanweber**
I couldn't create a Docker image because Acrobat was referenced with an uppercase A instead of a lowercase like in the directory "acrobat". Now the image is created successfully.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6941)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

Very sorry for the spam, @ethanweber.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot test this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@jamiesnape I don't understand what's going wrong here.  Please take a look, when you have a moment.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jamiesnape** [comment]
Jenkins seems to be ignoring comments totally. Looking into it now.

**Comment by jamiesnape** [comment]
Looks like maybe it is just being slow at processing. The "ok to test" just showed up 90 seconds ago.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
+@jamiesnape for feature review.

:lgtm:

+@sherm1 for platform review.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6941#-:-KsxlWz1wZjftxeoDb_D:b-rghq1r)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6941#-:-Ksy74YYitIu_vWSiLsx:b8qx53o)*

**Pull request merged**
