### PR TITLE
Clarify the documentation of AddMaximizeLogDeterminantCost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19849)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19849#-:-NaEtsnX6naVD6f0p4HK:badrumm)* status: LGTM missing from assignee RussTedrake(platform)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19849)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform)

___
*[`solvers/mathematical_program.h` line 1221 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19849#-NaEvPYA1pQbG_Jg-iiL:-NaEvPYA1pQbG_Jg-iiM:b-vgjk6z) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ace9af5bcd31b3b540e2c450f795ea83fa21f5/solvers/mathematical_program.h#L1221)):*
> ```objc
>    * @note We implicitly require that `X` being positive semidefinite (psd) (as
>    * X is the diagonal entry of the big psd matrix above). If your `X` is not
>    * necessarily psd, then don't call this function.
> ```

can we remove this version? I think the version below is more clear. ("we implicitly require" was confusing, but "DO NOT need to" is super clear!)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19849)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform)

___
*[`solvers/mathematical_program.h` line 1221 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19849#-NaEvPYA1pQbG_Jg-iiL:-NaEz7HMAhbHXnm-VX1M:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ace9af5bcd31b3b540e2c450f795ea83fa21f5/solvers/mathematical_program.h#L1221)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we remove this version? I think the version below is more clear. ("we implicitly require" was confusing, but "DO NOT need to" is super clear!)
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: x2.  Thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19849#-:-NaF-ztp-dRzwRC_C7Zq:bt2kd1v)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Pull request merged**
