### PR TITLE
Added visualization triads in meldis

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
+@sammy-tri For review please!

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 536 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaJG8DN7E5lv8U-qdPS:-NaJG8DN7E5lv8U-qdPT:bhgpit3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed8aed58763d5fe40464d00de02ab33819327528/bindings/pydrake/visualization/_meldis.py#L536)):*
> ```Python
>     def on_frame_update(self, channel, message):
>         """Handler for lcmt_viewer_draw."""
>         for i in range(message.num_links):
> ```

I have one compatibility request (which can probably be a TODO if it ends up being tricky to implement).  In https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_frame.py#L24 we delete the old objects and create the new ones if the set of link names changes, I believe to keep from having old triads from a channel hanging around if the channel resets the collection of things it's drawing.  I'd like to do that here too.
___
*[`bindings/pydrake/visualization/_meldis.py` line 546 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaJCMNT8ZNg33GAwnx3:-NaJCMNT8ZNg33GAwnx4:bbz795n) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed8aed58763d5fe40464d00de02ab33819327528/bindings/pydrake/visualization/_meldis.py#L546)):*
> ```Python
> 
>     @staticmethod
>     def _to_pose(position, quaternion):
> ```

Can we make this a module level helper function instead of copy/pasting it?

**Comment by jwnimmer-tri** [comment]
If it helps, feel free to assign me for platform review once it's ready.  It seems mostly in good shape so far.

**Comment by AdityaBhat-TRI** [comment]
*[`bindings/pydrake/visualization/_meldis.py` line 546 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaJCMNT8ZNg33GAwnx3:-NaNqFAMBi28f43rmZjC:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed8aed58763d5fe40464d00de02ab33819327528/bindings/pydrake/visualization/_meldis.py#L546)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Can we make this a module level helper function instead of copy/pasting it?
</blockquote></details>

Done.

**Comment by AdityaBhat-TRI** [comment]
*[`bindings/pydrake/visualization/_meldis.py` line 536 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaJG8DN7E5lv8U-qdPS:-NaNunTx3ZX2SmwalZYv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed8aed58763d5fe40464d00de02ab33819327528/bindings/pydrake/visualization/_meldis.py#L536)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I have one compatibility request (which can probably be a TODO if it ends up being tricky to implement).  In https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_frame.py#L24 we delete the old objects and create the new ones if the set of link names changes, I believe to keep from having old triads from a channel hanging around if the channel resets the collection of things it's drawing.  I'd like to do that here too.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review.  I have one change request still but it's (hopefully!) small.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-:-NaO1sLq-je67eWNCJ9o:bz1dl5s)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 527 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaO1-uE4vGJul3xsNqO:-NaO1-uF099Oj3lsknbe:b-4xu139) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L527)):*
> ```Python
>         """Handler for lcmt_viewer_draw."""
>         # delete old frames if the link names have changed
>         if set(self._link_name_published) != set(message.link_name):
> ```

I think `self._link_name_published` should be a per-channel value so that using multiple channels doesn't cause frequent deletion and recreation of objects.

**Review by jwnimmer-tri — COMMENTED** [review]
I did a first pass to help speed things along.  I'll wait to LGTM until some of the code fixes happen.

Is there any program inside Drake that I can run to generate these frame commands, so that I can see what shows up on the screen with the new code?

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-:-NaOCC3L9mv9mdjbA2eK:b-5xshqh)* status: 7 unresolved discussions, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 482 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOAMFP-Xdw2B79nD5Q:-NaOAMFP-Xdw2B79nD5R:b-th8kmo) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L482)):*
> ```Python
> 
> class _DrawFrameApplet:
>     """Visualizes frame"""
> ```

This comment doesn't sufficiently explain what's happening here.
___
*[`bindings/pydrake/visualization/_meldis.py` line 499 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOAZhVBx2WSGLtNxgf:-NaOAZhW5iZtpBgE0QA-:b-4rk5lk) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L499)):*
> ```Python
> 
>     def _add_meshcat_triad(self, path, length=0.25, radius=0.01,
>                            opacity=1.0, X_PT=RigidTransform()):
> ```

nit Some arguments (length, radius, opacity) are never used at any call site.  In other words, the arguments are dead code.

Therefore, these should be local variables instead.
___
*[`bindings/pydrake/visualization/_meldis.py` line 525 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOBlTg0Qx6_gXgqEVr:-NaOBlTg0Qx6_gXgqEVs:b-c4nkoi) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L525)):*
> ```Python
> 
>     def on_frame_update(self, channel, message):
>         """Handler for lcmt_viewer_draw."""
> ```

This comment is somewhat misleading.  This doesn't handle _all_ of the lcmt_viewer_draw messages (in fact, it handles a very small percentage of them) --  just the bastard ones on the `DRAKE_DRAW_FRAMES...` channels.  The ones on `DRAKE_VIEWER_DRAW` are not handled here.
___
*[`bindings/pydrake/visualization/_meldis.py` line 533 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOBGDC5TIWCJRaWzVa:-NaOBGDC5TIWCJRaWzVb:b-g3sta7) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L533)):*
> ```Python
>         for i in range(message.num_links):
>             link_name = message.link_name[i].replace("::", "/")
>             link_path = (f"{self._channel_to_meshcat_path(channel)}/"
> ```

nit Calling `_channel_to_meshcat_path` inside the loop has a slight implication that the result might be different each time through.  Probably having a local variable outside the loop `channel_path = self._channel_to_meshcat_path(channel)` would help clarify that the first part of the path is invariant within the loop.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 26 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaO917t5HOUREjLj38n:-NaO917t5HOUREjLj38o:b-971yj2) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/test/meldis_test.py#L26)):*
> ```Python
>     lcmt_viewer_geometry_data,
>     lcmt_viewer_link_data,
>     lcmt_viewer_draw,
> ```

nit Keep the imports alpha-sorted.
___
*[`bindings/pydrake/visualization/test/meldis_test.py` line 519 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaO9dMO4eyUwq_OPvXf:-NaO9dMO4eyUwq_OPvXg:baqg2z1) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/test/meldis_test.py#L519)):*
> ```Python
>                          buffer=message.encode())
> 
>         meshcat_path = (
> ```

nit No need for `(` hijinks; this fits on one line without any special wrapping.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848)* status: 7 unresolved discussions, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 499 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOAZhVBx2WSGLtNxgf:-NaOCc_C6Nv0ol3-693G:b2brbsb) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L499)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Some arguments (length, radius, opacity) are never used at any call site.  In other words, the arguments are dead code.

Therefore, these should be local variables instead.
</blockquote></details>

Along the same lines, X_PT should not be defaulted (dead code), since its default is never used for anything.

**Comment by AdityaBhat-TRI** [comment]
Running the meldis_test.py is the quickest way. I have mostly been testing with Anzu: running PublishFramesToLcmTest

**Review by jwnimmer-tri — COMMENTED** [review]
> I have mostly been testing with Anzu: running PublishFramesToLcm.Test.

Ideally, all code in Drake has a demo in Drake that can tickle it.  After this PR lands, I'll see if I can update the some demo (e.g., manipulation station) to publish some frame(s).

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-:-NaO_2QWAImr0KikErFh:bpnhxha)* status: 5 unresolved discussions, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

**Review by AdityaBhat-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848)* status: 2 unresolved discussions, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 482 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NaOAMFP-Xdw2B79nD5Q:-NaT-EuMAHeoGvTaU4ij:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd1a3e50ef5383915fa79474a5eb623373752d9f/bindings/pydrake/visualization/_meldis.py#L482)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment doesn't sufficiently explain what's happening here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
I run `bushing_sysid` to generate a sample frame.  It worked OK.

:lgtm:

> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-:-NagK1uL1PXaHfCAGCJY:bs8dwh1)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`bindings/pydrake/visualization/_meldis.py` line 535 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NagLBuAB-J0jB8Keodj:-NagLBuAB-J0jB8Keodk:bchy48f) ([raw file](https://github.com/RobotLocomotion/drake/blob/f3de7e522294164bf3b8e7d23b61d27e85abe06c/bindings/pydrake/visualization/_meldis.py#L535)):*
> ```Python
>                     != set(message.link_name)):
>                 self._meshcat.Delete(path=channel_path)
>         self._channel_link_map[channel] = message.link_name
> ```

BTW If I'm reading correctly, I think this can be further simplified (see below).  As simple as possible is to our benefit, since we are not testing this logic with any unit test cases.



_Suggestion:_
```Python
        link_names = set(message.link_name)
        if self._channel_link_map.get(channel) != link_names:
            self._meshcat.Delete(path=channel_path)
        self._channel_link_map[channel] = link_names
```

**Comment by AdityaBhat-TRI** [comment]
*[`bindings/pydrake/visualization/_meldis.py` line 535 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-NagLBuAB-J0jB8Keodj:-NagRAR-4xoInQq9SrZD:b-9755fn) ([raw file](https://github.com/RobotLocomotion/drake/blob/f3de7e522294164bf3b8e7d23b61d27e85abe06c/bindings/pydrake/visualization/_meldis.py#L535)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If I'm reading correctly, I think this can be further simplified (see below).  As simple as possible is to our benefit, since we are not testing this logic with any unit test cases.
</blockquote></details>

Thank you!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19848#-:-Nahc32F5ynlG1gsuM7m:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
