### PR TITLE
Adds CarVisApplicator and PoseBundleToDrawMessage to AutomotiveSimulator.

### PR DESCRIPTION
**Pull request by liangfok**
This is another incremental step towards #5541.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5622)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please since this builds upon #5474 by connecting `PoseAggregator` to `CarVisApplicator`.

+@jwnimmer-tri for platform and car reviews please.

Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-:-KgBjZMbQ1a90zpnAwoZ:bvmbbhs)*

**Comment by jwnimmer-tri** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgFqEB2mALtEuBivKC4:b-xzi6oo) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
> ```cpp
>   AddPublisher(*coord_transform, vehicle_number);
>   // TODO(liang.fok): Update this method to take a CarVis as an input parameter
>   // and use it here. It is currently hard coded to use a BoxCarVis.
> ```

I don't see why this method should force the user to supply a CarVis.  Can't it always internally figure out the right CarVis to make?

Ditto for the identical TODOs below.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 288 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqyjgKE08hakkUASt:-KgFqyjgKE08hakkUASu:blrywt2) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L288)):*
> ```cpp
>   EXPECT_EQ(draw_context.get_num_input_ports(), 1);
>   EXPECT_EQ(draw_context.num_numeric_parameters(), 0);
> }
> ```

This doesn't seem like the right test at all.  None of these EXPECT_EQs are durably meaningful, and the thing we care about (the draw message coming out) appears to not be tested at all?

It seems like the correct test is to take the pose_bundle_to_draw_message output port and either ExportOutput on it, or hook up an LcmPublisherSystem to it (then use the LcmMock) -- but in either case, to check that the correct draw messages come out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by liangfok** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgFrms1PHj_KQqPxbg2:b-8d2evc) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't see why this method should force the user to supply a CarVis.  Can't it always internally figure out the right CarVis to make?

Ditto for the identical TODOs below.
</blockquote></details>

I suppose the actual API will have to undergo a design evaluation. How about I simply change this TODO to say "remove the hard-coding of BoxCarVis"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgFt1lD1oGHZWT6Eu5i:b-phvrmi) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I suppose the actual API will have to undergo a design evaluation. How about I simply change this TODO to say "remove the hard-coding of BoxCarVis"?
</blockquote></details>

Sure.  Or just `// TODO This method claims to visualize an SDF, but instead just hard-codes a box.`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by liangfok** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgFtdg6bSCUVUAKJQDR:b-4n8bj0) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure.  Or just `// TODO This method claims to visualize an SDF, but instead just hard-codes a box.`, right?
</blockquote></details>

Not yet since the old way of visualizing the model still works and the Prius will show up (it's the "current design" described in #5541). I have a WIP branch that removes the old design and replaces it with the "new" way (the "Proposed Redesign -Version 3" in #5541). I created this PR because that WIP branch was becoming too big an unwieldy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgFyRaHwaOR0QyvN5a1:bvc01wd) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Not yet since the old way of visualizing the model still works and the Prius will show up (it's the "current design" described in #5541). I have a WIP branch that removes the old design and replaces it with the "new" way (the "Proposed Redesign -Version 3" in #5541). I created this PR because that WIP branch was becoming too big an unwieldy.
</blockquote></details>

Whatever; push a change and I'll review it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by liangfok** [comment]
I shall add the "do not review" label until I make the requested changes.

**Comment by jadecastro** [comment]
First pass. PTAL.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 548 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGUvpZmtw0QUm5RKt0:-KgGUvp_6ee5zqF1ScEk:bl3atb3) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L548)):*
> ```cpp
>   diagram_ = builder_->Build();
>   simulator_ = std::make_unique<systems::Simulator<T>>(*diagram_);
> ```

BTW, Given that you have a lot of invariants specified in the unit test as to what properties the context should take on, consider adding these invariants here, perhaps (e.g. `is_stateless()`, `get_num_input_ports()`) rather than including them in the unit test?

---

*[drake/automotive/automotive_simulator.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGMySvxWvgrpZbqgy6:-KgGMySwhKO05bzpPLms:b-nxnefy) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.h#L296)):*
> ```objc
>       builder_->template AddSystem<systems::rendering::PoseAggregator<T>>()};
> 
>   CarVisApplicator<T>* car_vis_applicator_{
> ```

BTW, consider adding some comments describing these two member fields, as the names themselves do not lend well to understanding their functionality.

---

*[drake/automotive/automotive_simulator.h, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGSEtMDqcouewvfcPW:-KgGSEtMDqcouewvfcPX:brc0jcn) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.h#L299)):*
> ```objc
>       builder_->template AddSystem<CarVisApplicator<T>>()};
> 
>   systems::rendering::PoseBundleToDrawMessage* pose_bundle_to_draw_message_{
> ```

BTW, this name, and its `*_context` getter function is a mouthful. Consider shortening it. Perhaps even `bundle_to_draw_`?

---

*[drake/automotive/test/automotive_simulator_test.cc, line 257 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGRb8QusdKzmr6EMKQ:-KgGRb8QusdKzmr6EMKR:b-v6l9kj) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L257)):*
> ```cpp
> }
> 
> // Verifies that CarVisApplicator and PoseBundleToDrawMessage are instantiated
> ```

The wording here is not very descriptive of what the unit test actually accomplishes. Below, the unit test not only checks that they are instantiated, but moreover checks that their contexts have certain, very specific properties.  Consider stating this explicitly.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 264 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGVhJlh1Wem-5jSI5l:-KgGVhJlh1Wem-5jSI5m:bwafn1o) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L264)):*
> ```cpp
>       std::make_unique<lcm::DrakeMockLcm>());
>   const std::string kFileName = GetDrakePath() +
>       "/automotive/models/prius/prius.sdf";
> ```

BTW, the added functions in `AutomotiveSimulator` only use `BoxCar` but you are adding a Prius model here. This is a bit confusing as this model is unrelated?  If true, please add a comment here that the `BoxCar` is being used and what the significance of the `pirus.sdf` is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-:-KgGWfb6DCGNL_j3vC5f:b-s1usvt)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 5 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqEB2mALtEuBivKC3:-KgKUJtcoKmd_CNEqLdT:bqfiez) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Whatever; push a change and I'll review it.
</blockquote></details>

Done. I switched to use `PriusVis` now that #5602 is merged.

---

*[drake/automotive/automotive_simulator.cc, line 548 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGUvpZmtw0QUm5RKt0:-KgKUa9ydT7dmQVX_yfc:bcui71y) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.cc#L548)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Given that you have a lot of invariants specified in the unit test as to what properties the context should take on, consider adding these invariants here, perhaps (e.g. `is_stateless()`, `get_num_input_ports()`) rather than including them in the unit test?
</blockquote></details>

Done. I decided to delete the checks and instead just check the resulting LCM output.

---

*[drake/automotive/automotive_simulator.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGMySvxWvgrpZbqgy6:-KgLN3OKmVvBr072yrkg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.h#L296)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, consider adding some comments describing these two member fields, as the names themselves do not lend well to understanding their functionality.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGSEtMDqcouewvfcPW:-KgLNjJbuBFOXS77oUP_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/automotive_simulator.h#L299)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, this name, and its `*_context` getter function is a mouthful. Consider shortening it. Perhaps even `bundle_to_draw_`?
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 257 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGRb8QusdKzmr6EMKQ:-KgLNmIaX82sw7Fzrvon:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L257)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

The wording here is not very descriptive of what the unit test actually accomplishes. Below, the unit test not only checks that they are instantiated, but moreover checks that their contexts have certain, very specific properties.  Consider stating this explicitly.
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 264 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgGVhJlh1Wem-5jSI5l:-KgLNn_WCZnyfdxUEKJm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L264)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, the added functions in `AutomotiveSimulator` only use `BoxCar` but you are adding a Prius model here. This is a bit confusing as this model is unrelated?  If true, please add a comment here that the `BoxCar` is being used and what the significance of the `pirus.sdf` is.
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 288 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-KgFqyjgKE08hakkUASt:-KgLNootwb-P-OhKxZ-Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00e45201fa182d894f1e14f602adeb286c09dbc6/drake/automotive/test/automotive_simulator_test.cc#L288)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This doesn't seem like the right test at all.  None of these EXPECT_EQs are durably meaningful, and the thing we care about (the draw message coming out) appears to not be tested at all?

It seems like the correct test is to take the pose_bundle_to_draw_message output port and either ExportOutput on it, or hook up an LcmPublisherSystem to it (then use the LcmMock) -- but in either case, to check that the correct draw messages come out.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-:-KgLUQTsoxBskY-anbFY:bblnx7i)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform and automotive

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-:-KgLv--P-0YszSu6-e7e:bj1jpb0)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622)*

**Comment by jadecastro** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5622#-:-KgMe5FVJ166p_uSR0wV:bnfp4nl)*

**Pull request merged**
