### PR TITLE
Update meshcat to include resizable control panel

### LINKED ISSUE #18542: [meshcat] Provide better handling for truncated labels in control panel
Long label text in the Meshcat control panel gets truncated, leaving users with no way to differentiate some labels. This has been noticed in slider labels but might also become an issue with buttons and the scene tree.

A simple solution would be to add hover text with the full label, either just for labels that are too wide or for all labels.

### PR DESCRIPTION
**Pull request by trowell-tri**
Also makes a minor update to the meshcat workspace documenation.

- [x] Requires https://github.com/rdeits/meshcat/pull/151.

Closes #19973.
Closes #18542.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20000)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

The control panel is definitely resizable. It's a shame that dat.gui doesn't offer any indication of this (other than changing the mouse pointer when hovering over the possibly invisible edge of the control panel).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-:-NbvEGBYCzZVoCGfIaGT:b-witmy2)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @trowell-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvEFg1DEM4GYgd7lVq:-NbvEFg1DEM4GYgd7lVr:b-jf5p7q) (no related file):*
You might want this in two commits.

One commit strictly updates the meschat sha. After your meshcat PR merges, you can go back into that commit and update it back to the original repo and proper sha.

The second commit can make the change to drake content.

___
___
*[`tools/workspace/meshcat/README.md` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvD_Bl5ZyDHf6JHoDa:-NbvD_Bl5ZyDHf6JHoDb:b-sfs424) ([raw file](https://github.com/RobotLocomotion/drake/blob/123051299a21e937562b61f473d79fc72e0a4b40/tools/workspace/meshcat/README.md#L12)):*
As long as we're addressing things, the file doesn't have documentation explaining expected behavior.

> Confirm that the displayed behavior matches the description printed to the console.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-:-NbvK_SY5DGK0JYq7FtD:b-vtj4vo)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @trowell-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvKaRh4DVvdr2d5NRJ:-NbvKaRh4DVvdr2d5NRK:b-tw7f3e) (no related file):*
Working

Reminder not to merge this until `rdeits/meshcat` has already merged, and the new sha has been placed into here.

___

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20000)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvKaRh4DVvdr2d5NRJ:-NbytXb20UfSFBRGJ0t7:b-8f9rxp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Reminder not to merge this until `rdeits/meshcat` has already merged, and the new sha has been placed into here.
</blockquote></details>

I've updated this PR to include the current meshcat HEAD.

___
___
*[`tools/workspace/meshcat/README.md` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvD_Bl5ZyDHf6JHoDa:-Nbyt-2W7oe5lyLcFTvT:b-lcbgap) ([raw file](https://github.com/RobotLocomotion/drake/blob/123051299a21e937562b61f473d79fc72e0a4b40/tools/workspace/meshcat/README.md#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As long as we're addressing things, the file doesn't have documentation explaining expected behavior.

> Confirm that the displayed behavior matches the description printed to the console.
</blockquote></details>

So it doesn't. Are you looking for a tweak in the wording here ("meshcat_manual_test prints instructions") or a change to test/meshcat_manual_test.cc to include some documentation (and what would that be) or something else?

**Review by jwnimmer-tri — COMMENTED** [review]
I've confirmed `meshcat_manual_test` still works after the meshcat sha bump.  (As mentioned in slack, the environment map reflection is really subtle so I'm not 100% sure it's correct, but _shrug_.)

I tested the panel resizing and it's great!  Works in model_visualizer, too.

> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @SeanCurtis-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-:-NbywxOcCL8SBFI2laLC:bisdi8h)* status: needs at least two assigned reviewers

___
*[`tools/workspace/meshcat/README.md` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20000#-NbvD_Bl5ZyDHf6JHoDa:-NbyuXXA67yKNNXPwpql:b-r8i678) ([raw file](https://github.com/RobotLocomotion/drake/blob/123051299a21e937562b61f473d79fc72e0a4b40/tools/workspace/meshcat/README.md#L12)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

So it doesn't. Are you looking for a tweak in the wording here ("meshcat_manual_test prints instructions") or a change to test/meshcat_manual_test.cc to include some documentation (and what would that be) or something else?
</blockquote></details>

The timezone difference here doesn't really allow for iteration, so I'll dismiss this thread to get the new features merged ASAP.  Sean (or anyone) is invited to improve this text in a follow-up.  This PR is at least a partial improvement.

To me, the fundamental problem here is "Possible options" is too nebulous and we probably shouldn't have any _at all_.  Either things are important and we should do them every single time (and explain precisely what to do), or they are not important and we shouldn't distract people by mentioning them.

**Pull request merged**
