### PR TITLE
[primitives] Run clang-format on all non-test files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Plus a very few adjustments by hand for readability.

Towards #19707 and #4843.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19708)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for both reviews.  
:lgtm:

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19708#-:-NZBqtzD6FhMaOfrMQ5f:bjiqnjw)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Review by RussTedrake — COMMENTED** [review]
btw -- you didn't actually add the bazel rule for the formatting?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19708#-:-NZBrZeF2_rwSyl51pMj:b-ih76n6)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Comment by jwnimmer-tri** [comment]
> btw -- you didn't actually add the bazel rule for the formatting?

That's right.  I can't add it until I reformat the `test/**` files as well.

**Review by RussTedrake — COMMENTED** [review]
Makes sense.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19708#-:-NZBs3p2B3xNq0n-FO_f:b-dxcbts)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Comment by jwnimmer-tri** [comment]
=> https://github.com/RobotLocomotion/drake/pull/19710 for the follow-up.

**Pull request merged**
