### PR TITLE
[tools] Reduce local_ram_resources under ASan

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
CI is experiencing the OOM killer ~daily.

Towards #17560.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17593)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri :LGTM: For what it's worth.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17593#-:-N7Gs1PO0wmzX4jtndDt:b-s9o0ib)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@svenevs for review also, please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.

**Review by svenevs — COMMENTED** [review]
:lgtm:

```
[11:46:36 AM]  INFO: Found applicable config definition build:asan in file /media/ephemeral0/ubuntu/workspace/linux-focal-clang-bazel-experimental-mosek-address-sanitizer/src/tools/dynamic_analysis/bazel.rc: --build_tests_only --local_ram_resources=HOST_RAM*0.5 --copt=-g --copt=-fno-common --copt=-fsanitize=address --copt=-fsanitize-address-use-after-scope --copt=-fstandalone-debug --copt=-O0 --copt=-fno-omit-frame-pointer --linkopt=-fsanitize=address --linkopt=-fsanitize-address-use-after-scope --linkopt=-fuse-ld=ld --start_end_lib=no --fission=no --run_under=//tools/dynamic_analysis:asan --test_env=ASAN_OPTIONS --test_env=LSAN_OPTIONS --test_env=ASAN_SYMBOLIZER_PATH --test_env=LSAN_SYMBOLIZER_PATH --test_tag_filters=-gurobi,-mosek,-snopt,-no_asan,-no_lsan --test_lang_filters=-sh,-py --test_timeout=150,750,2250,9000
```

Job was able to launch and is currently running with the desired `local_ram_resources`, I don't think we need to wait for it to finish, we'll need to collect data over the next couple of days to see if this helps or not.  (AKA this is ready to merge IMO).

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17593#-:-N7GzbiU3LS9j7n15i0-:b-69m1w3)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),svenevs (waiting on @jwnimmer-tri)

**Pull request merged**
