### PR TITLE
[geometry] InternalGeometry supports deformable representation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for feature review please, thanks.
This is the first of the PR train towards #17007 for registering a deformable geometry in SceneGraph. Relevant to #16875.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036#-:-N0Xp54KCg5EAd7MyOmE:b-lvc7l9)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: not much to say, good test coverage. +@sherm1 for platform review, please.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036#-:-N0gTkEA6RHTQLSM2pdi:b-7ilypb)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`geometry/internal_geometry.h` line 330 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gYb_s3cGEwNj7HGXs:-N0gYb_s3cGEwNj7HGXt:b6n9h5l) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L330)):*
> ```objc
>   // mesh. The vertex positions are immaterial and unused. We should have an
>   // abstraction for just the connectivity of a mesh.
>   copyable_unique_ptr<VolumeMesh<double>> mesh_;
> ```

Just for my own edification: When this geometry eventually makes its way to the proximity engine, this is the mesh that will be copied for the `DeformableVolumeMesh` representation when reifying the `DeformableGeometry` type in `geometry::internal::deformable::Geometries`, correct?
___
*[`geometry/test/internal_geometry_test.cc` line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gXvYd6PbTAJZmgqBh:-N0gXvYd6PbTAJZmgqBi:b-q31say) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L153)):*
> ```cpp
>   ASSERT_NE(internal_mesh, nullptr);
>   EXPECT_TRUE(mesh.Equal(*internal_mesh));
> ```

nit: maybe just a quick assertion that `X_FG` and `X_PG` are both identity for the deformable geometry for complete coverage of the conditions laid out in `InternalGeometry`.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending some minor clarifications and unresolveds from feature review.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036#-:-N0h48496VIRaslz6aO-:b-ugk3f8)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/internal_geometry.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h3LCY537XkVZJxyaE:-N0h3LCY537XkVZJxyaF:bo1bztc) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L27)):*
> ```objc
> // same class very nicely. For example, rigid geometries have the concept of
> // "hangs-in" frame and parent geometry while deformable geometries have mesh
> // representations. Right now we are manually disabling incompatible features.
> ```

BTW I don't think you need this TODO. The objects are both internal geometry and share many features, with a few exception. My guess is that it would be messier (or have a lot of duplication) to split them rather than leave them combined. Even the current prohibition on parent frame could be relaxed in the future if we need to.
___
*[`geometry/internal_geometry.h` line 183 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gzX5vBNhU4OJCgrMf:-N0gzX5vBNhU4OJCgrMg:b-c5k5lz) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L183)):*
> ```objc
>   }
> 
>   /* A geometry is deformable iff it has a mesh representation. */
> ```

minor: this is unclear because some rigid geometries are also meshes. They also have a mesh "representation", though not the one you mean. Is there a better way to say this? How about calling the data member `deformable_mesh_`? Then you could say "a geometry is deformable iff it has a deformable_mesh representation.
___
*[`geometry/internal_geometry.h` line 187 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gyGpTC4nJ11yl-ykG:-N0gyGpTC4nJ11yl-ykH:b-468zeq) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L187)):*
> ```objc
> 
>   /* Returns true if the geometry is not "fixed" in (or "hangs" on) the world
>    frame. */
> ```

minor: I found the "hangs on" addition here confusing. I thought you meant to exclude deformable geometries that are attached to World (like a deformable beam fixed at one end to World) but I see that all deformables are considered dynamic. Consider something more direct like "Returns true if the geometry can move with respect to the World frame. That includes any deformable geometry, and any rigid geometry attached to a frame other than World."
___
*[`geometry/internal_geometry.h` line 263 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-MdjAsvl5hWNJvEN:-N0h-MdjAsvl5hWNJvEO:b-gprs26) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L263)):*
> ```objc
>   /* Returns a pointer to the geometry's mesh representation if one exists, or
>    nullptr otherwise.  */
>   const VolumeMesh<double>* mesh() const { return mesh_.get(); }
> ```

BTW consider calling this `deformable_mesh()` to avoid confusion with rigid geometries that are (rigid) meshes.
___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0h-tEP2Lw10ra1tjlY:b-7tmdv0) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
> ```objc
>   // TODO(xuchenhan-tri): InternalGeometry only needs the connectivity of the
>   // mesh. The vertex positions are immaterial and unused. We should have an
>   // abstraction for just the connectivity of a mesh.
> ```

BTW is that because the vertex positions are supplied later at run time? I'm surprised there isn't some nominal vertex positions that are meaningful here. Can you elaborate a little?
___
*[`geometry/test/internal_geometry_test.cc` line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h1Ptl5Yh1HW6vKbO6:-N0h1Ptl5Yh1HW6vKbO7:bg2xnmy) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L138)):*
> ```cpp
> }
> 
> GTEST_TEST(InternalGeometryTest, MeshedGeometry) {
> ```

BTW consider calling this test "DeformableMeshedGeometry" (I'd like to maintain a clear distinction between deformable meshes and the ubiquitous rigid meshes and contact patch meshes we already have.)

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed. @sherm1 PTAL on naming conventions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036#-:-N0hD3a56upfb_LIsIko:b-u38ptw)* status: 4 unresolved discussions (waiting on @joemasterjohn and @sherm1)

___
*[`geometry/internal_geometry.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h3LCY537XkVZJxyaE:-N0h6PprEQJNl3UE6TRz:bnok9mx) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't think you need this TODO. The objects are both internal geometry and share many features, with a few exception. My guess is that it would be messier (or have a lot of duplication) to split them rather than leave them combined. Even the current prohibition on parent frame could be relaxed in the future if we need to.
</blockquote></details>

The TODO is there to remind me to circle back to this in the future. I don't have enough argument to say which is better.
This PR prohibits (or renders useless) the following functions in InternalGeometry for deformable geometries:

```
  const math::RigidTransform<double>& X_PG() const;
  const math::RigidTransform<double>& X_FG() const;
  std::optional<GeometryId> parent_id() const;
  void set_geometry_parent(GeometryId id, math::RigidTransform<double> X_FG);
  bool is_child_of_geometry(GeometryId geometry_id) const;
  const std::unordered_set<GeometryId>& child_geometry_ids() const;
  bool has_child(GeometryId geometry_id) const;
  void add_child(GeometryId geometry_id);
  void remove_child(GeometryId geometry_id);
```

I think that's a long-enough list for us to reconsider the class structure. In particular, all these parent/child concepts are unique to rigid geometries since these relationships are built into the topology and don't make sense for deformable geometies. (They are different from the discussion we had earlier about having non-world frames.)
___
*[`geometry/internal_geometry.h` line 183 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gzX5vBNhU4OJCgrMf:-N0h87Zi-Bug2wOvt4Qg:b-dz3l80) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L183)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is unclear because some rigid geometries are also meshes. They also have a mesh "representation", though not the one you mean. Is there a better way to say this? How about calling the data member `deformable_mesh_`? Then you could say "a geometry is deformable iff it has a deformable_mesh representation.
</blockquote></details>

I'm shying away from the word "deformable mesh" because it has caused another reviewer confusion (the mesh is not deformable itself even though it is related to the deformable geometry). 

I modified the comment here. WDYT?
___
*[`geometry/internal_geometry.h` line 187 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gyGpTC4nJ11yl-ykG:-N0h9kUr9Wd3aRe0Bt8j:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L187)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I found the "hangs on" addition here confusing. I thought you meant to exclude deformable geometries that are attached to World (like a deformable beam fixed at one end to World) but I see that all deformables are considered dynamic. Consider something more direct like "Returns true if the geometry can move with respect to the World frame. That includes any deformable geometry, and any rigid geometry attached to a frame other than World."
</blockquote></details>

Done. Thanks!
___
*[`geometry/internal_geometry.h` line 263 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-MdjAsvl5hWNJvEN:-N0h9oR7DBkRbUfeoIk7:bpots08) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L263)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider calling this `deformable_mesh()` to avoid confusion with rigid geometries that are (rigid) meshes.
</blockquote></details>

See my reservation about `deformable_mesh()` above.
___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0h9upc8Gu0daLFBPlH:b-guy2fg) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is that because the vertex positions are supplied later at run time? I'm surprised there isn't some nominal vertex positions that are meaningful here. Can you elaborate a little?
</blockquote></details>

The class documentation declares that this class "... includes ... aspects that do *not* depend on computed values."
Only the connectivity of the mesh satisfy this criterion (unless we do fracture). The vertex positions are stored in `GeometryState`, parallel to the `X_WGs_` that lives there at the moment.
___
*[`geometry/internal_geometry.h` line 330 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gYb_s3cGEwNj7HGXs:-N0hAYNv-d0GI0xUizgB:b5qs8e7) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L330)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Just for my own edification: When this geometry eventually makes its way to the proximity engine, this is the mesh that will be copied for the `DeformableVolumeMesh` representation when reifying the `DeformableGeometry` type in `geometry::internal::deformable::Geometries`, correct?
</blockquote></details>

Yes, that's the plan.
___
*[`geometry/test/internal_geometry_test.cc` line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h1Ptl5Yh1HW6vKbO6:-N0hAls80ZaPJeJE_4M3:b-m49l2r) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L138)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider calling this test "DeformableMeshedGeometry" (I'd like to maintain a clear distinction between deformable meshes and the ubiquitous rigid meshes and contact patch meshes we already have.)
</blockquote></details>

Again see my comment above. I can be convinced that throwing the word deformable in there is ok.
___
*[`geometry/test/internal_geometry_test.cc` line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0gXvYd6PbTAJZmgqBh:-N0hD0Av4opC_UB0MKUS:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L153)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe just a quick assertion that `X_FG` and `X_PG` are both identity for the deformable geometry for complete coverage of the conditions laid out in `InternalGeometry`.
</blockquote></details>

Done, thanks.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)* status: 2 unresolved discussions (waiting on @joemasterjohn and @xuchenhan-tri)

___
*[`geometry/internal_geometry.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h3LCY537XkVZJxyaE:-N0hQIngCmKeGU9R6wGK:bhekuc5) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The TODO is there to remind me to circle back to this in the future. I don't have enough argument to say which is better.
This PR prohibits (or renders useless) the following functions in InternalGeometry for deformable geometries:

```
  const math::RigidTransform<double>& X_PG() const;
  const math::RigidTransform<double>& X_FG() const;
  std::optional<GeometryId> parent_id() const;
  void set_geometry_parent(GeometryId id, math::RigidTransform<double> X_FG);
  bool is_child_of_geometry(GeometryId geometry_id) const;
  const std::unordered_set<GeometryId>& child_geometry_ids() const;
  bool has_child(GeometryId geometry_id) const;
  void add_child(GeometryId geometry_id);
  void remove_child(GeometryId geometry_id);
```

I think that's a long-enough list for us to reconsider the class structure. In particular, all these parent/child concepts are unique to rigid geometries since these relationships are built into the topology and don't make sense for deformable geometies. (They are different from the discussion we had earlier about having non-world frames.)
</blockquote></details>

I see your point!
___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0hQn8CBZfvdnplhMCU:bnup703) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The class documentation declares that this class "... includes ... aspects that do *not* depend on computed values."
Only the connectivity of the mesh satisfy this criterion (unless we do fracture). The vertex positions are stored in `GeometryState`, parallel to the `X_WGs_` that lives there at the moment.
</blockquote></details>

Initial (default) values don't depend on computed values so would meet the criterion you specified. But I gather those aren't needed here, though it isn't obvious where the initial values come from. Default values for states and parameters are stored in the System and are used to initialize a newly-created Context. If I create a Context for a System that contains a deformable geometry, and then render that Context, what shape does the geometry have and where did that come from?
___
*[`geometry/test/internal_geometry_test.cc` line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h1Ptl5Yh1HW6vKbO6:-N0hSOya0fRo1LTJsX4R:b922oo1) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L138)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Again see my comment above. I can be convinced that throwing the word deformable in there is ok.
</blockquote></details>

I think it is worth changing here even if you don't do it elsewhere, just to make the test purpose more obvious. You could accomplish the same thing with a comment though.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)* status: 2 unresolved discussions (waiting on @joemasterjohn and @sherm1)

___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0h_clM0ZhKwkXUhZrJ:bmbexdw) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
The initial values don't come from InternalGeometry either. In my mental picture, InternalGeometry geometries behave similar to parameters. They don't change according to computed values.

> If I create a Context for a System that contains a deformable geometry, and then render that Context, what shape does the geometry have and where did that come from?

The initial positions would be dictated by the geometry instance being registered at SceneGraph. However, that position information is stored in GeometryState instead of InternalGeometry. This is in line with the treatment of rigid geometries. 

Conceptually, the vertex positions of the mesh stored in InternalGeometry can be garbage and should **never** be touched, and thus the TODO. See also the TODO I added in the unit test in the new revision.
___
*[`geometry/test/internal_geometry_test.cc` line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h1Ptl5Yh1HW6vKbO6:-N0h__BuDiO5k5GxYqZY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/test/internal_geometry_test.cc#L138)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think it is worth changing here even if you don't do it elsewhere, just to make the test purpose more obvious. You could accomplish the same thing with a comment though.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0l-ctB-G5YqLWV5rlX:b-xog09l) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
> Maybe the member should be called mesh_topology then to emphasize that the vertex positions are ignored? 

That is better. Working.

> but it is a bit of a (justified) hack and IMO deserves more emphasis and explanation in the code than is there

Yes, it is a hack. In a f2f with @joemasterjohn, he mentioned that he has plan to provide the real solution to distill the topology of a mesh abstraction. So we can be saved by that later on.

> Are the vertex positions set to something ugly like NaNs to make sure no future programmer thinks they can make use of them?

Working.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[`geometry/internal_geometry.h` line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17036#-N0h-tEP2Lw10ra1tjlX:-N0n4jTE9qZdZcUtBlS4:b-puwmuj) ([raw file](https://github.com/robotlocomotion/drake/blob/481a5b087b35931b2f8d4235623e6638a5e518df/geometry/internal_geometry.h#L329)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> Maybe the member should be called mesh_topology then to emphasize that the vertex positions are ignored? 

That is better. Working.

> but it is a bit of a (justified) hack and IMO deserves more emphasis and explanation in the code than is there

Yes, it is a hack. In a f2f with @joemasterjohn, he mentioned that he has plan to provide the real solution to distill the topology of a mesh abstraction. So we can be saved by that later on.

> Are the vertex positions set to something ugly like NaNs to make sure no future programmer thinks they can make use of them?

Working.
</blockquote></details>

I realized that it's not true that these reference positions of the vertices are never useful. In ProximityEngine, we will use the positions of the vertices in their reference configuration to generate an approximate distance field. 

Sorry for the confusion. PTAL at the change in the new revision.

**Review by sherm1 — COMMENTED** [review]
Great, thanks! I like the `reference_mesh` name and I'm glad the vertex coords are good for something.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17036#-:-N0vXK7D4qKYqzT37qRK:b-e6g5pc)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @xuchenhan-tri)

**Pull request merged**
