### PR TITLE
exclude dev directories from doxygen

### PR DESCRIPTION
**Pull request by RussTedrake**
We agreed on this on slack ages ago.. and it's finally coming off my todo list.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8239)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for both reviews, please.
fyi platform reviewers: @sherm1, @sammy-tri, @soonho-tri , @ggould-tri , @seancurtis-tri , @ericcousineau-tri .

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8239#-:-L6hP72iJc5W8pALF1Nz:b-nttz8m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8239#-:-L6hTJts5X6QV4Tlxsr2:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
(er, missed that it was just FYI, sorry!)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8239#-:-L6hTNxk5tBok6-_a0GV:b-md0vlx)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8239)*

**Comment by jwnimmer-tri** [comment]
:lgtm:  Tested locally that a class in `dev` was present on master and gone as of this PR.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8239#-:-L6m2o_wNfWz9W9wxS7Q:b-jdzcr6)*

**Pull request merged**
