### PR TITLE
Factor out ipopt_solver_internal.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #21485 and #18292

I will add code to test the internals of IpoptSolver when I change IpoptSolver class.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

I didn't make any functional changes to the code, just moved the code from ipopt_solver.cc to ipopt_solver_internal.h and ipopt_solver_internal.cc, so that I can test the class IpoptSolver_NLP later.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-:-NysPtLt6aoswYZCTqqT:bzi7wme)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/ipopt_solver_internal.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-NysQ6Tb7Qlw6saecHxF:-NysQ6Tb7Qlw6saecHxG:b5xchhx) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf36c072bfb451449225dba42ecdbf831f366c9/solvers/ipopt_solver_internal.h#L57)):*
> ```objc
> // IpoptSolver creates an instance of IpoptSolver_NLP which lives for
> // the duration of the Solve() call.
> #pragma GCC diagnostic push
> ```

@jwnimmer-tri I do not understand why, but if I don't have these pragma, then I got the compilation error
```
bazel-out/k8-opt/bin/solvers/_virtual_includes/_ipopt_solver_compiled_cc_impl/drake/solvers/ipopt_solver_internal.h:55:7: error: 'drake::solvers::internal::IpoptSolver_NLP' declared with greater visibility than its base 'Ipopt::TNLP' [-Werror=attributes]
   55 | class IpoptSolver_NLP : public Ipopt::TNLP {
 ```
What does this error message mean?

**Comment by jwnimmer-tri** [comment]
The change is that the problematic class/struct moved from the anonymous namespace (which has hidden linker visibility) to the `internal` namespace (which has public linker visibility).  To fix the warning you'll need to move it back to hidden linker visibility, by using the `DRAKE_NO_EXPORT` macro.  See for example the `MergeRecord` class in `drake/geometry/render_gltf_client`.

After CI is happy, you can assign the on-call platform reviewer.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy.

I do not quite understand the CI failure
```
[10:04:03 PM]  ERROR: /media/ephemeral0/ubuntu/workspace/linux-jammy-clang-bazel-experimental-everything-release/src/bindings/pydrake/BUILD.bazel:55:37: Action bindings/pydrake/documentation_pybind.h failed: (Exit 1): mkdoc failed: error executing Action command (from target //bindings/pydrake:generate_pybind_documentation_header) bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/tools/workspace/pybind11/mkdoc -DDRAKE_COMMON_SYMBOLIC_EXPRESSION_DETAIL_HEADER -DEIGEN_MPL2_ONLY -DSPDLOG_SHARED_LIB -DSPDLOG_COMPILED_LIB ... (remaining 917 arguments skipped)
[10:04:03 PM]  
[10:04:03 PM]  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
[10:04:03 PM]  bazel-out/k8-opt/bin/tools/install/libdrake/_virtual_includes/drake_headers/drake/solvers/ipopt_solver_internal.h:11:10: fatal error: 'IpIpoptApplication.hpp' file not found
```
It complains that it cannot find `IpIpoptApplication.hpp` from `documentation_pybind.h`. But I can compile `//solvers:ipopt_solver` and the compiler can find `IpIpoptApplication.hpp`. So it is just a problem of `documentation_pybind.h`?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-:-Nz-7WjJ4MADS5NsX_t8:b-enmtf1)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
Best guess, `ipopt_solver_internal.h` should be in `srcs_enabled` not `hdrs`.  We don't want to install it (nor bind it in pydrake).

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy, when I moved `ipopt_solver_internal.h` from `hdrs` to `scrs_enabled`, I got this error
```
solvers/ipopt_solver_internal.cc:1:10: fatal error: drake/solvers/ipopt_solver_internal.h: No such file or directory
    1 | #include "drake/solvers/ipopt_solver_internal.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Is there another way to prevent installing or binding this file?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-:-Nz-Gu_R8_6BU5PrnqwK:b-y9cngs)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
I imagine that the mosek and gurobi examples of similar internal-file-carving would be on point.

**Review by hongkai-dai — COMMENTED** [review]
I changed to carve out `ipopt_solver_internal` target. This requires a small change in `ipopt_solver_internal.cc`, as it cannot access IpoptSolverDetails, which is declared in `ipopt_solver.h`. We cannot have `ipopt_solver_internal.cc` to depend on `ipopt_solver.h`, as that would create a cyclic dependency (ipopt_solver-> ipopt_solver_internal -> ipopt_solver).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-:-Nz-QX14Cu3n6E3pWo9g:b-w8hhfe)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-:-Nz-owg-64TirkaCVyw0:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/ipopt_solver_internal.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-NysQ6Tb7Qlw6saecHxF:-Nz-pHBzE8G3UVUCOxtc:bc6t6b8) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf36c072bfb451449225dba42ecdbf831f366c9/solvers/ipopt_solver_internal.h#L57)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@jwnimmer-tri I do not understand why, but if I don't have these pragma, then I got the compilation error
```
bazel-out/k8-opt/bin/solvers/_virtual_includes/_ipopt_solver_compiled_cc_impl/drake/solvers/ipopt_solver_internal.h:55:7: error: 'drake::solvers::internal::IpoptSolver_NLP' declared with greater visibility than its base 'Ipopt::TNLP' [-Werror=attributes]
   55 | class IpoptSolver_NLP : public Ipopt::TNLP {
 ```
What does this error message mean?
</blockquote></details>

What I think this error _should_ mean is:  An exported subclass cannot have less restrictive linker visibility attribute's than its superclass's non-pure-virtual symbols, or else users of the subclass would get a linker error when calling methods defined by the superclass.
I can't figure out how that would have been the case here, but the no export pragma is a sensible way to resolve it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21486)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/ipopt_solver_internal.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21486#-NysQ6Tb7Qlw6saecHxF:-Nz-vPsQ3EF7WOfBJXFF:b8pjqon) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf36c072bfb451449225dba42ecdbf831f366c9/solvers/ipopt_solver_internal.h#L57)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

What I think this error _should_ mean is:  An exported subclass cannot have less restrictive linker visibility attribute's than its superclass's non-pure-virtual symbols, or else users of the subclass would get a linker error when calling methods defined by the superclass.
I can't figure out how that would have been the case here, but the no export pragma is a sensible way to resolve it.
</blockquote></details>

Thanks Grant!

**Pull request merged**
