### PR TITLE
Upgrade gurobi 8

### PR DESCRIPTION
**Pull request by hongkai-dai**
According to http://www.gurobi.com/products/whats-new/whats-new-in-the-latest-version, Gurobi 8 is 16% faster than Gurobi 7.5, on mixed integer problems.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-gurobi please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
Update this line too (once all the extra builds are done): https://github.com/RobotLocomotion/drake/blob/68c65489cba2c69fbbe49f922e663169de51f1b4/CMakeLists.txt#L126

**Comment by jamiesnape** [comment]
+@jamiesnape for feature review

:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695#-:-LB8kou_1Ur_y6jovSTr:b-dra7mm)*

**Comment by hongkai-dai** [comment]
Thanks @jamiesnape , I just fixed the gurobi version in CMakeLists.txt

@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-gurobi please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695#-:-LBCIQb2D0IdKfN_beKv:bhzt3c6)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695)*

**Comment by jamiesnape** [comment]
A note on logistics. We need simultaneous commits here and in drake-ci to have this work in master, so leave the "do not merge" tag on and ping me when it is ready and I will handle the merge (which may need to happen at a quiet moment).

**Comment by hongkai-dai** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8695#-LBMzxWa2J2w9t-52ME_:-LC61qLz7d-OGtFOCT5L:b-r9n68e) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per f2f, we should ensure that these licenses work for TRI users. Making a blocking comment here.
</blockquote></details>

TRI server has been updated to Gurobi 8 license. 

---

*[tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8695#-LBMyz8V1BKzWHE6sVc7:-LC61pDs0cYtNJ5voxBa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a53be57cdde0a0171ff3fc8915b14f8a50d4ee3/tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you make the Ubuntu error message as informative as the Mac error?
(state that it's looking for Gurobi 8.0.0, and perhaps print the value of `GUROBI_PATH`?)

If I'm using Gurobi 7.5.2, the error message just states that my environment variable is incorrectly set.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8695#-LBMzxWa2J2w9t-52ME_:-LC9e-DH4VIZT4mRP6Pc:bmvsxn) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

TRI server has been updated to Gurobi 8 license. 
</blockquote></details>

Test on my machine, it worked!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending sync with `drake-ci`

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695#-:-LC9eKqV641TKRmB_DWA:b-ihgvr7)*

**Comment by hongkai-dai** [comment]
@jamiesnape, @ericcousineau-tri and I have tested this PR with the TRI gurobi license. Could you commit it to drake-ci and handle the merge? Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8695#-:-LC9eKuSEbC5s2tO2bZ-:b-y0wlf1)*

**Comment by jamiesnape** [comment]
Done.

**Pull request merged**
