### PR TITLE
Add SceneGraphInspector::GetParent(FrameId)

### PR DESCRIPTION
**Pull request by sloretz**
This adds a new API `SceneGraphInspector::GetParent()` to get the parent frame given a `FrameId` of the child. The motivation is to enable RobotLocomotion/drake-ros#20 to include the parent/child relationships in the published tf tree.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Since I'm the next on-call platform reviewer I'll call this :lgtm: platform pending feature review (with a couple of comments).
Still needs a feature reviewer -- +@joemasterjohn can you feature review this (it's short)?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368#-:-MtLC9ap6M3cRdMdDOx0:b-i2i0jy)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, missing label for release notes (waiting on @joemasterjohn and @sloretz)

___
*[geometry/geometry_state.h, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtLA6GK68VGn5OTOh98:-MtLA6GLA8IMhbSZZ69y:b-wcnngi) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbc9d0d5da3cfdaa6347c0fb6c795466ee46fd3/geometry/geometry_state.h#L177)):*
> ```objc
> 
>   /** Implementation of SceneGraphInspector::GetParent(FrameId) const.  */
>   FrameId GetParent(FrameId frame_id) const;
> ```

minor: please consider naming this `GetParentFrame()` to make it more clear at the call sites. (Like `GetFrameGroup()` below rather than `GetGroup()`.)
___
*[geometry/test/geometry_state_test.cc, line 2385 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtLBpXBBTqEd8Jb9FQe:-MtLBpXBBTqEd8Jb9FQf:b-cexnkl) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbc9d0d5da3cfdaa6347c0fb6c795466ee46fd3/geometry/test/geometry_state_test.cc#L2385)):*
> ```cpp
>       }
>     }
>     ASSERT_TRUE(found_relationship)
> ```

nit: this can be `EXPECT_EQ` since the other cases might still work

**Review by sherm1 — COMMENTED** [review]
Thanks, @sloretz -- just waiting for @joemasterjohn now.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368#-:-MtOTgEU0B7epr_ifa4Y:b7hko3i)* status: LGTM missing from assignee joemasterjohn, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Taking a look now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368#-:-MtOY9BE2utMApRydDVC:bqhqmv7)* status: LGTM missing from assignee joemasterjohn, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: after a test clean up.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368#-:-MtO_1s-BMigC6bojux-:b-l5oau8)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sloretz)

___
*[geometry/test/geometry_state_test.cc, line 2360 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtOYtNyA0Cv1RBJUGoS:-MtOYtNz-CgYBmkLmGsQ:b-ohcmya) ([raw file](https://github.com/robotlocomotion/drake/blob/17333cc3e04aeb928521c417b235e49f2b7c22a1/geometry/test/geometry_state_test.cc#L2360)):*
> ```cpp
> 
>   // {child, parent}
>   std::vector<std::pair<std::string, std::string>> expected_relationships = {
> ```

I would make this a `std::map<std::string, std::string>` (using the same initializer list), then the below algorithm can just be:

```
for (const FrameId frame_id : geometry_state.get_frame_ids()) {
  const std::string& frame_name = geometry_state_.GetName(frame_id);
  const FrameId parent_frame_id = geometry_state_.GetParentFrame(frame_id);
  const std::string& parent_frame_name = geometry_state_.GetName(parent_frame_id);
  EXPECT_TRUE(parent_frame_name, expected_relationships[frame_name]);
}
```

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

___
*[geometry/test/geometry_state_test.cc, line 2360 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtOYtNyA0Cv1RBJUGoS:-MtOcI6qEXvOFaP6XKul:bmcuzic) ([raw file](https://github.com/robotlocomotion/drake/blob/17333cc3e04aeb928521c417b235e49f2b7c22a1/geometry/test/geometry_state_test.cc#L2360)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I would make this a `std::map<std::string, std::string>` (using the same initializer list), then the below algorithm can just be:

```
for (const FrameId frame_id : geometry_state.get_frame_ids()) {
  const std::string& frame_name = geometry_state_.GetName(frame_id);
  const FrameId parent_frame_id = geometry_state_.GetParentFrame(frame_id);
  const std::string& parent_frame_name = geometry_state_.GetName(parent_frame_id);
  EXPECT_TRUE(parent_frame_name, expected_relationships[frame_name]);
}
```
</blockquote></details>

BTW Nice!

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn and @sherm1)

___
*[geometry/test/geometry_state_test.cc, line 2360 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtOYtNyA0Cv1RBJUGoS:-MtOqIo1DadYvgTDUWRd:bfmm22z) ([raw file](https://github.com/robotlocomotion/drake/blob/17333cc3e04aeb928521c417b235e49f2b7c22a1/geometry/test/geometry_state_test.cc#L2360)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Nice!
</blockquote></details>

Simplified test with `std::map` in 17279dd3a

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16368)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sloretz)

___
*[geometry/test/geometry_state_test.cc, line 2360 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16368#-MtOYtNyA0Cv1RBJUGoS:-MtP02z0CEj23--feTEA:b-ng8uhp) ([raw file](https://github.com/robotlocomotion/drake/blob/17333cc3e04aeb928521c417b235e49f2b7c22a1/geometry/test/geometry_state_test.cc#L2360)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Simplified test with `std::map` in 17279dd3a
</blockquote></details>

OK, looks good!

**Comment by jwnimmer-tri** [comment]
When preparing the squashed commit message, always omit the "Signed-off-by" line in the message.  Drake does not use that convention.

**Pull request merged**
