### PR TITLE
Port primitives to SisoVectorSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #4448.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5262)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5262#-:-Kdaebgebvlbja9ABjLa:bz1t39v)*

**Comment by soonho-tri** [comment]
+@soonho-tri

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5262#-:-KdafJz8yEfMz89bAJKG:bv2pqqi)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5262#-:-KdahCcXk6WJJYU35HLV:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5262#-:-Kdb-rLxMnd7km6RwZ6X:bnfp4nl)*

**Pull request merged**
