### PR TITLE
Add a simple demo to move the end effector 

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7728)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2WHjNrCM72E3_Nlgax:bvpmr17)*

**Comment by avalenzu** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2_x9pkJQ5JUn-y0bMs:-L2_x9plt36rGHcEWnAj:b1h8zqe) ([raw file](https://github.com/robotlocomotion/drake/blob/85038188841430147c817d913371eb457c36429c/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L29)):*
> ```cpp
> DEFINE_double(z, 0., "z coordinate to move to");
> DEFINE_double(r, 0., "target roll for end effector");
> DEFINE_double(p, 0., "target pitch for end effector");
> ```

BTW: Could these be "roll" and "pitch" to match "yaw"?i

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2_xxUNR2ayZ0P9aInN:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2_x9pkJQ5JUn-y0bMs:-L2fnh9KDdhXfmaPzCMs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85038188841430147c817d913371eb457c36429c/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L29)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW: Could these be "roll" and "pitch" to match "yaw"?i
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2fphXE2eLmxzT-YFgW:buasbda)*

**Comment by sherm1** [comment]
Nice example! Assuming it has some pedagogical purpose, would be very helpful to have some hand-holding comments explain some of its magic, ptal. Other than comment requests, platform :lgtm:.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gFlV4TwmDvozZlV9T:-L2gFlV4TwmDvozZlV9U:b7i3yeq) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L3)):*
> ```cpp
> /// @file
> ///
> /// Demo of moving the iiwa's end effector in cartesian space.
> ```

BTW please say more about what this demo is supposed to do. I read through the code and I *think* it sets up a plan to move the end effector to the given location in 2 seconds (?). Then does it stay there afterwards?

A few comments in the code would have helped me -- I'll BTW where I was confused.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gGbTtw37JZmsfOMEK:-L2gGbTtw37JZmsfOMEL:b-5v9q3j) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L30)):*
> ```cpp
> DEFINE_double(roll, 0., "target roll for end effector");
> DEFINE_double(pitch, 0., "target pitch for end effector");
> DEFINE_double(yaw, 0., "target yaw for end effector");
> ```

BTW no mention here of the frame or sequence interpretation of the rpy angles. Possibly that is because there is some iron-clad convention that everyone already knows? If not, you could say "target roll about world x axis for end effector" etc.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gHCT6w_xflXSaRy4u:-L2gHCT6w_xflXSaRy4v:b-2olbe4) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L61)):*
> ```cpp
> 
>  private:
>   void HandleStatus(const lcm::ReceiveBuffer*, const std::string&,
> ```

BTW I had trouble figuring out how often you expect this to be called. The plan only goes out on the first call, but then I gather you'll get lots of calls after that as kind of a progress report? A short comment about that would help me understand this.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gHoM1TDgxYG3y7Pl-:-L2gHoM1TDgxYG3y7Pl0:b858qfz) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L71)):*
> ```cpp
>     }
> 
>     if (status_count_ % 100 == 1) {
> ```

BTW does nothing unless logging is enabled?

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gK3exNyBuUxQVuF7I:-L2gK3exNyBuUxQVuF7J:b-nwpopb) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L95)):*
> ```cpp
>       waypoints.push_back(wp);
>       IKResults ik_res;
>       ik.PlanSequentialTrajectory(waypoints, iiwa_q, &ik_res);
> ```

BTW one waypoint goes in, but then the trajectory has two configurations? Better if I don't have to know that already or infer it from reading the rest of the code.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gIn3ta_o4Qp9Dgl68:-L2gIn3ta_o4Qp9Dgl69:b-2louzn) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L100)):*
> ```cpp
>       if (ik_res.info[0] == 1) {
>         drake::log()->info("IK sol size {}", ik_res.q_sol.size());
>         std::vector<double> times{0, 2};
> ```

BTW I am still confused about how you know there are two frames in the IK solution, and where these particular times come from. Consider DRAKE_DEMANDing that you're getting what you expect. (And commenting)

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gJf0LYcbcOGb_5gG9:-L2gJf0LYcbcOGb_5gGA:b-ol1fni) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L102)):*
> ```cpp
>         std::vector<double> times{0, 2};
>         MatrixX<double> q_mat(ik_res.q_sol.front().size(), ik_res.q_sol.size());
>         for (size_t i = 0; i < ik_res.q_sol.size(); ++i) {
> ```

BTW does this have to have exactly two columns? Why is this copy necessary -- just a change of format from the ik solution to something ApplyJointVelocityLimits() wants?

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gIVGnizVbbtVkUdM4:-L2gIVGnizVbbtVkUdM5:b-f855ww) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L105)):*
> ```cpp
>           q_mat.col(i) = ik_res.q_sol[i];
>         }
>         ApplyJointVelocityLimits(q_mat, &times);
> ```

BTW I was confused about why velocity limits were being applied to positions q but understand now that I read the ApplyJointVelocityLimits code. A comment would have saved me the time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2gK_flBr3LBt9e6E_c:brvbtfk)*

**Comment by sammy-tri** [comment]
Added a number of comments (which I really should have done in the first place, since this is indeed supposed to function both as an instructive example and a utility program).

---

Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gFlV4TwmDvozZlV9T:-L2gOGgqEG7VBFyC_kpP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please say more about what this demo is supposed to do. I read through the code and I *think* it sets up a plan to move the end effector to the given location in 2 seconds (?). Then does it stay there afterwards?

A few comments in the code would have helped me -- I'll BTW where I was confused.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gGbTtw37JZmsfOMEK:-L2gP4fFDyROTHRpdtCM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW no mention here of the frame or sequence interpretation of the rpy angles. Possibly that is because there is some iron-clad convention that everyone already knows? If not, you could say "target roll about world x axis for end effector" etc.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gHCT6w_xflXSaRy4u:-L2gPSWCGDjT4GjcaWvJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I had trouble figuring out how often you expect this to be called. The plan only goes out on the first call, but then I gather you'll get lots of calls after that as kind of a progress report? A short comment about that would help me understand this.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gHoM1TDgxYG3y7Pl-:-L2gPcV2J6e8kVMjqVg8:bw7ynwb) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does nothing unless logging is enabled?
</blockquote></details>

Info logging should be enabled by default (and is when testing on my machine)

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gK3exNyBuUxQVuF7I:-L2gQFad21BsswayVlWs:b-etydc6) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW one waypoint goes in, but then the trajectory has two configurations? Better if I don't have to know that already or infer it from reading the rest of the code.
</blockquote></details>

Done.  (a bit further above when the waypoint is defined)

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gIn3ta_o4Qp9Dgl68:-L2gR5xs7gA-3rTtoyxK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L100)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I am still confused about how you know there are two frames in the IK solution, and where these particular times come from. Consider DRAKE_DEMANDing that you're getting what you expect. (And commenting)
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gJf0LYcbcOGb_5gG9:-L2gR7qanGXfbVjNkmTS:b2rmras) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this have to have exactly two columns? Why is this copy necessary -- just a change of format from the ik solution to something ApplyJointVelocityLimits() wants?
</blockquote></details>

Added a comment.  It would be more than two columns if we added additional waypoints (but yes it's always two here).

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gIVGnizVbbtVkUdM4:-L2gRXiRBF9wYxM0rllr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90607c14c183db8539f7587f3991db6df2417b46/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I was confused about why velocity limits were being applied to positions q but understand now that I read the ApplyJointVelocityLimits code. A comment would have saved me the time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2gSHSb5e2FVJMuB5nB:b-axc0lj)*

**Comment by sherm1** [comment]
Great -- thanks, @sammy-tri! Added a few new BTWs, ptal.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gwgPUNYgl0eRVZn_8:-L2gwgPUNYgl0eRVZn_9:b3wmbdn) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L35)):*
> ```cpp
> DEFINE_double(roll, 0., "target roll about world x axis for end effector");
> DEFINE_double(pitch, 0., "target pitch about world y axis for end effector");
> DEFINE_double(yaw, 0., "target yaw (about world z axis) for end effector");
> ```

BTW for consistency, no parentheses for z.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 102 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gxMrpUSYbEeRBYeLn:-L2gxMrpUSYbEeRBYeLo:b50gb5k) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L102)):*
> ```cpp
>       // Create a single waypoint for our plan (the destination).
>       // This results in a trajectory with two knot points (the
>       // current pose and the calculated final pose).
> ```

BTW I don't see where the current pose is being supplied to ik. It appears to read the urdf_ though so does it start with some default pose, and then we happen to know our current pose is just the default at this point?

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gxoi9M-mZr8LlSRq0:-L2gxoi9M-mZr8LlSRq1:bwd5hgy) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L120)):*
> ```cpp
>         // arbitrary choice).  This may be slowed down if executing
>         // the plan in that time would exceed any joint velocity
>         // limites.
> ```

BTW limites->limits

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L2gy07TnPRXdA9tGHU_:bq6im89)*

**Comment by sammy-tri** [comment]
Good catch on those.  Thanks!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gwgPUNYgl0eRVZn_8:-L3-3r8yVZ-QNEek0cb2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW for consistency, no parentheses for z.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 102 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gxMrpUSYbEeRBYeLn:-L3-4CpabjYMw55RYND9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't see where the current pose is being supplied to ik. It appears to read the urdf_ though so does it start with some default pose, and then we happen to know our current pose is just the default at this point?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/move_iiwa_ee.cc, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-L2gxoi9M-mZr8LlSRq0:-L3-4MI4dW0PWc7-j1p0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e636d89fa9ef42a98dcf75ace184c4709b1febe/examples/kuka_iiwa_arm/move_iiwa_ee.cc#L120)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW limites->limits
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728#-:-L3-4g-eCQzJkIB8_nKE:b1bzvnd)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7728)*

**Pull request merged**
