### PR TITLE
Scs and Clarabel parses 2x2 PSD/LMI constraints as second order cone constraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
A second order cone problem is easier to solve than a positive semidefinite programming problem.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-:-OC9KJ3S6PJMlGWxze7N:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/aggregate_costs_constraints.cc` line 893 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-OC9RN_x0wIdbsq2d3eV:-OC9Vuxw7IkWUn7BR365:b-yh10tr) ([raw file](https://github.com/RobotLocomotion/drake/blob/a0ec46c413a0d33577c5f2a1fbd0be80049385f3/solvers/aggregate_costs_constraints.cc#L893)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Don't we want `<` due to 0 indexing?
</blockquote></details>

Done. Good catch
___
*[`solvers/scs_clarabel_common.cc` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-OC9TEecBPOG2UlGg8__:-OC9W0jI78AFFDs9_hQ7:b5oat4h) ([raw file](https://github.com/RobotLocomotion/drake/blob/a0ec46c413a0d33577c5f2a1fbd0be80049385f3/solvers/scs_clarabel_common.cc#L83)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Where is the scaling constant?
</blockquote></details>

The scaling constant is 0.5, which we have already considered in solving `y` from `soc_dual`.
___
*[`solvers/aggregate_costs_constraints.cc` line 950 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-OC9SiTTC4xzzk4IlIap:-OC9W09LDbrTmHZGbN7D:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a0ec46c413a0d33577c5f2a1fbd0be80049385f3/solvers/aggregate_costs_constraints.cc#L950)):*
> ```cpp
>       // -∑ᵢ(F[1+i](0,0) + F[1+i](1,1))x[i] + s[0] = F[0](0, 0) + F[0](1, 1)
>       // -∑ᵢ(F[1+i](0,0) - F[1+i](1,1))x[i] + s[1] = F[0](0, 0) - F[0](1, 1)
>       //  -2*∑ᵢF[1+i](0, 1)*x[i] + s[2] + s[2] = 2 * F[0](0, 1)
> ```

Done.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-:-OC9WGEH9SNOvSO69ffD:buer3go)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending open comments

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-:-OCALPGB-bjTS3_N3zKh:b8ux4j9)* status: 4 unresolved discussions

___
*[`solvers/aggregate_costs_constraints.cc` line 886 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-OCA7Wnr9kOpJ-ohTWA8:-OCA7WnsEuypJ9cdoSq8:bhd0kya) ([raw file](https://github.com/RobotLocomotion/drake/blob/f977f01797bc5783eddd1c954db7b92b749fb890/solvers/aggregate_costs_constraints.cc#L886)):*
> ```cpp
>     std::vector<std::optional<int>>* twobytwo_lmi_dual_start_indices) {
>   DRAKE_ASSERT(ssize(*b) == *A_row_count);
>   DRAKE_ASSERT(num_new_second_order_cones != nullptr);
> ```

BTW consider DRAKE_DEMAND here since the cost will be insignificant given the amount of code below.
___
*[`solvers/aggregate_costs_constraints.cc` line 924 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-OCAJFNY9lUtnWk24Kx7:-OCAJFNY9lUtnWk24Kx8:bydcosn) ([raw file](https://github.com/RobotLocomotion/drake/blob/f977f01797bc5783eddd1c954db7b92b749fb890/solvers/aggregate_costs_constraints.cc#L924)):*
> ```cpp
>       A_triplets->emplace_back(*A_row_count, x0_index, -1);
>       A_triplets->emplace_back(*A_row_count, x3_index, -1);
>       b->push_back(0);
> ```

BTW below you filled in the rhs after you finished the left. I found that easier to follow. In any case it would be good to deal with "b" the same way in both loops.
Consider filling in the three b's together at the end.

**Review by sherm1 — COMMENTED** [review]
Just waiting now for @AlexandreAmice to unblock 2 comments

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219#-:-OCAh_mp3VWhDfeHp-_X:b-50nam5)* status: 2 unresolved discussions

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22219)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),AlexandreAmice

**Pull request merged**
