### PR TITLE
Add models for pick and place test

### PR DESCRIPTION
**Pull request by sammy-tri**
Also includes some slight refactoring/updates to make future PR's a bit easier to read.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6241)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review (sorry for continuing to assign these to you...   I can start picking more random feature reviewers if you'd prefer for the future)

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-KldyaV3FqzG3vRMK9-e:b-346hsw)*

**Comment by siyuanfeng-tri** [comment]
no worries. i am out of town next week though. i will get to this later today. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-Kle0WgZ9H3yEBMLXFBx:bhrwctm)*

**Comment by sammy-tri** [comment]
-@siyuanfeng-tri +@ericcousineau-tri (as siyuan is out of the office this week)

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-KlsRQf1cuw5izD98Oq6:b-45gi5)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgF0i_bkHypj6OUSX:-KlsgF0jO88tjJWEgMmK:b-y98dx7) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L30)):*
> ```XML
>       points around the face).  However, for arbitrary grip configuration, the
>       slightly inset box will provide contact with a *slight* offset (in this
>       case a deviation of 0.0005 m from the visual surface).
> ```

Is there a corresponding TODO / issue somewhere where we could address this at some point in the future, such that we don't have to hack the collision geometry to get something usable?

---

*[drake/examples/kuka_iiwa_arm/models/objects/yellow_post.urdf, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-Klsg5I7uhaHsT4j3flv:-Klsg5I8TzlMVp1WBjfc:b329xv1) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/yellow_post.urdf#L22)):*
> ```XML
>       </geometry>
>       <material name="Black">
> 	<color rgba="0.0 0.0 0.0 1.0"/>
> ```

nit It looks like these are tabs. Could these be changed to spaces?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KlsgwA_vObJOzG_v4n9:bea65zz) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
> ```objc
> class WorldState {
>  public:
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(WorldState)
> ```

BTW Can I ask the motivation for this change?
If it's for being able to pass this around, would it make more sense to make a move-only variant of this?
(I ended up hacking something like this [here](https://github.com/EricCousineau-TRI/drake/blob/0005f707b047bc35aea7a6c2f49dd049754fe0f6/drake/manipulation/estimators/dev/tree_state_portion.h#L34).)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 8 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsjcEkIDXuvwdR8Yoa:-KlsjcEkIDXuvwdR8Yob:b-n12gtj) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L2)):*
> ```XML
> <?xml version="1.0"?>
> <robot name="simple_cuboid">
> ```

BTW, i havent

---

*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgF0i_bkHypj6OUSX:-KlsjNG1QyJBwuOGQboP:bv7ij4i) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a corresponding TODO / issue somewhere where we could address this at some point in the future, such that we don't have to hack the collision geometry to get something usable?
</blockquote></details>

not reallt? i think this is the most appropriate place for this comment. 

---

*[drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsjnstjX8iJBccyyb7:-KlsjnstjX8iJBccyyb8:b-jan47k) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf#L7)):*
> ```XML
>       <origin xyz="0 0 0" rpy="0 0 0" />
>       <mass value="0.068" />
>       <inertia ixx="0.0000408" ixy="0" ixz="0" iyy="0.0000408" iyz="0"
> ```

BTW, why this change? instead of making a new urdf?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KlskJFgLf3uBbz090Mx:b-4ae8u) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can I ask the motivation for this change?
If it's for being able to pass this around, would it make more sense to make a move-only variant of this?
(I ended up hacking something like this [here](https://github.com/EricCousineau-TRI/drake/blob/0005f707b047bc35aea7a6c2f49dd049754fe0f6/drake/manipulation/estimators/dev/tree_state_portion.h#L34).)
</blockquote></details>

in this case, why not just have a * and somebody else owns this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by sammy-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgF0i_bkHypj6OUSX:-KltJ4NjwXSvBbNg_qOq:b5jqkdn) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L30)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

not reallt? i think this is the most appropriate place for this comment. 
</blockquote></details>

BTW I agree with siyuan above

---

*[drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsjnstjX8iJBccyyb7:-KltJDX0t7YNtn1HhsEG:b794bry) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf#L7)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, why this change? instead of making a new urdf?
</blockquote></details>

There were no existing users of this urdf.  I could have deleted it and created a new one I guess.

---

*[drake/examples/kuka_iiwa_arm/models/objects/yellow_post.urdf, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-Klsg5I7uhaHsT4j3flv:-KltJm_vTFizRcAGHSf5:b102mij) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/yellow_post.urdf#L22)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit It looks like these are tabs. Could these be changed to spaces?
</blockquote></details>

oops!  Fixed

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KltKElm1dcarZUN01uB:bedfn6f) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

in this case, why not just have a * and somebody else owns this?
</blockquote></details>

The motivation (which is mentioned below but in a less clear location) is to be able to store WorldState as part of a system's abstract state...  Since it then becomes part of a context, it needs to be copyable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by siyuanfeng-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsjnstjX8iJBccyyb7:-KltWAg1MNh0PV2MCh81:bokz8c3) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

There were no existing users of this urdf.  I could have deleted it and created a new one I guess.
</blockquote></details>

ah, ok then. 

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KltWFTKOJD0Y3Ix2drT:b-ombsfj) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The motivation (which is mentioned below but in a less clear location) is to be able to store WorldState as part of a system's abstract state...  Since it then becomes part of a context, it needs to be copyable.
</blockquote></details>

you can be copyable with just a pointer. this doesnt have to own rbt. does it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by sammy-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KltYfyEIMvj-KxUwJKe:b-vvst5n) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

you can be copyable with just a pointer. this doesnt have to own rbt. does it?
</blockquote></details>

The comment on the `iiwa_` member speaks to this as well.  Because the base position comes from LCM, it's easier to own the model internally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by EricCousineau-TRI** [comment]
*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgF0i_bkHypj6OUSX:-Klt_7QO7f29dC1GIxUO:bwrq15h) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L30)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I agree with siyuan above
</blockquote></details>

Per f2f with Sam and Andres, Andres has created #6254 to address the underlying issue.
Would it be possible to make a quick mention of this within these comments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-Klt_vpkTgSWSiaOLKIi:b-2l0s3s)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-KltaAI8gK5UPvFnhOuE:b-k0hcg5) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The comment on the `iiwa_` member speaks to this as well.  Because the base position comes from LCM, it's easier to own the model internally.
</blockquote></details>

I agree with Siyuan in this point - would it be possible to pass in just a `T*` / `weak_ptr<T>`externally, rather than an URDF?
I would definitely be fine if this was mentioned as a `TODO`, to minimize the work needed for this PR / the changes needed with the rest of the refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgF0i_bkHypj6OUSX:-Kltdmc7Yc2fn8A_ju6D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/models/objects/black_box.urdf#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Per f2f with Sam and Andres, Andres has created #6254 to address the underlying issue.
Would it be possible to make a quick mention of this within these comments?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-Kltd9DPMbfiXRlF6neC:bwh5hq2) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I agree with Siyuan in this point - would it be possible to pass in just a `T*` / `weak_ptr<T>`externally, rather than an URDF?
I would definitely be fine if this was mentioned as a `TODO`, to minimize the work needed for this PR / the changes needed with the rest of the refactor.
</blockquote></details>

I think no (or not easily?), for the reason stated above that the base position in the world is not necessarily known.  There might be some other way around this involving storing the base position which I haven't thought of...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-Klte4OM88MrWhvljU4J:b-ykw85)*

**Comment by EricCousineau-TRI** [comment]
*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KlsgwAZHT3olcRrFC5f:-Kltkt70ZFTz1gfOJdy4:bw9s9gi) ([raw file](https://github.com/robotlocomotion/drake/blob/6c659f959c650c6bd8c2897a68efce754dd6fb2a/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think no (or not easily?), for the reason stated above that the base position in the world is not necessarily known.  There might be some other way around this involving storing the base position which I haven't thought of...
</blockquote></details>

BTW Ah, my bad, sorry for not understanding that earlier - and I do see that you already have that TODO below the constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 10 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltnwLmDz3lt1mwSRCU:-KltnwLmDz3lt1mwSRCV:b-i8pdpk) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc#L43)):*
> ```cpp
>         iiwa_base_);
> 
>     std::shared_ptr<RigidBodyTree<double>> new_iiwa =
> ```

FYI `auto` is often used as the result type of `make_shared` or `make_unique`, since the RHS makes the type apparent.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltoXmOQx4DI_CyN1iR:-KltoXmOQx4DI_CyN1iS:b7z671p) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc#L43)):*
> ```cpp
>         iiwa_base_);
> 
>     std::shared_ptr<RigidBodyTree<double>> new_iiwa =
> ```

FYI It took me a few seconds here to realize that the point of `new_iiwa` as a local was to not have the `const` on the RBT during construction.  Maybe rename this `mutable_iiwa` to highlight that?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 109 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltpYwC31DUTzt4EcTp:-KltpYwDrc7_sI7SgJ-D:bsy6lpm) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L109)):*
> ```objc
>   Isometry3<double> obj_pose_;
>   Vector6<double> obj_vel_;
> };
> ```

FYI Depending on how much you care, you might consider putting a [reinit_after_move](http://drake.mit.edu/doxygen_cxx/classdrake_1_1reinit__after__move.html#details) around some of all of these fields, if its important to you that moved-from objects return to their default state (rather than being unspecified-but-valid state).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-Kltqfo_Z4JT9lHF_IKM:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Also the feature reviewer(s) have not marked all of the model-file edits as reviewed-as-of-lastest-commit (missing some headshots in the file matrix).  Please make sure that happens before merge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-KltqilfO_Jk8XSo3qkZ:b-4d1yhn)*

**Comment by sammy-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltnwLmDz3lt1mwSRCU:-Kltt_OO_avI9HYDjjcR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `auto` is often used as the result type of `make_shared` or `make_unique`, since the RHS makes the type apparent.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc, line 43 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltoXmOQx4DI_CyN1iR:-Klttfk1aW2abb6d_whx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.cc#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It took me a few seconds here to realize that the point of `new_iiwa` as a local was to not have the `const` on the RBT during construction.  Maybe rename this `mutable_iiwa` to highlight that?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h, line 109 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-KltpYwC31DUTzt4EcTp:-KlttKLcwd9AYnAk9iow:bj17w55) ([raw file](https://github.com/robotlocomotion/drake/blob/2d06fb6c1f01e478cdceaae7c14ee8aa09389818/drake/examples/kuka_iiwa_arm/pick_and_place/world_state.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Depending on how much you care, you might consider putting a [reinit_after_move](http://drake.mit.edu/doxygen_cxx/classdrake_1_1reinit__after__move.html#details) around some of all of these fields, if its important to you that moved-from objects return to their default state (rather than being unspecified-but-valid state).
</blockquote></details>

I think I'm OK with unspecified state after move on this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241#-:-Klvm0D6N0ImF1DNqxUg:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6241)*

**Pull request merged**
