### PR TITLE
Merge `drake/bindings/pybind11` and `drake/bindings/python/pydrake` into `drake/bindings/pydrake`.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates #6760, implements Step 1.a [from here](https://github.com/RobotLocomotion/drake/issues/6760#issuecomment-337797746).

This is a minor aesthetic change.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7296)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
May defer fixing CMake stuff until #7293 lands, removing the need for CMake overall.

---

Review status: 0 of 51 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-:-KxE8mjwFMpO8TnxVpfX:bs35qyd)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for feature + platform review, please.

---

Review status: 0 of 48 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-:-KzVm3qyee-RtSln8vWR:b7xtm6q)*

**Comment by sammy-tri** [comment]
:lgtm: (with one BTW)

---

Reviewed 87 of 87 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/drake_visualizer/drake_visualizer_apple.sh, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-Kzykg4_HWtAfxThkOLl:-Kzykg4_HWtAfxThkOLm:b-hp1dcq) ([raw file](https://github.com/robotlocomotion/drake/blob/8df347cc78a8b30a3b18672385e21d9146950dfc/tools/workspace/drake_visualizer/drake_visualizer_apple.sh#L17)):*
> ```Shell
> fi
> 
> export PYTHONPATH="drake/bindings:drake/lcmtypes:external/drake_visualizer/lib/python2.7/dist-packages:external/lcmtypes_bot2_core/lcmtypes:external/lcmtypes_robotlocomotion/lcmtypes:external/optitrack_driver/lcmtypes:external${PYTHONPATH:+:$PYTHONPATH}"
> ```

BTW this is arguably the only part of this diff which I dislike, since it has the vague feel like there could be other (non-python) bindings in a directory which is in `PYTHONPATH` but given that this script is rooting around in `bazel-bin` to begin with, I don't think it's too big of a deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-:-KzylD7LwAHiJGIpcxeP:b-mbnba9)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/drake_visualizer/drake_visualizer_apple.sh, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-Kzykg4_HWtAfxThkOLl:-KzypxOnIZTeOavney_s:b-2y8osh) ([raw file](https://github.com/robotlocomotion/drake/blob/8df347cc78a8b30a3b18672385e21d9146950dfc/tools/workspace/drake_visualizer/drake_visualizer_apple.sh#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this is arguably the only part of this diff which I dislike, since it has the vague feel like there could be other (non-python) bindings in a directory which is in `PYTHONPATH` but given that this script is rooting around in `bazel-bin` to begin with, I don't think it's too big of a deal.
</blockquote></details>

Yeah, since it's in the`.runfiles` directory, it seems like there should not be extra dependencies leaking in from other `build` actions (though there could be some directory shadowing snafus do to Bazel's auto `__init__.py` placement).

At some point, the Python bindings may end up living next to the C++ source code; if we encounter problems, we can look into having these Python libs being placed into a more isolated folder.

Would that work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7296)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/drake_visualizer/drake_visualizer_apple.sh, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7296#-Kzykg4_HWtAfxThkOLl:-Kzyw3JSYWlX5B6dypSI:b7s25zk) ([raw file](https://github.com/robotlocomotion/drake/blob/8df347cc78a8b30a3b18672385e21d9146950dfc/tools/workspace/drake_visualizer/drake_visualizer_apple.sh#L17)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yeah, since it's in the`.runfiles` directory, it seems like there should not be extra dependencies leaking in from other `build` actions (though there could be some directory shadowing snafus do to Bazel's auto `__init__.py` placement).

At some point, the Python bindings may end up living next to the C++ source code; if we encounter problems, we can look into having these Python libs being placed into a more isolated folder.

Would that work?
</blockquote></details>

I'm fine with merging as is.  I have mixed feelings about bindings living in the same directory as the C++ code being wrapped, but that's not relevant to this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7296)*

**Pull request merged**
