### PR TITLE
[proximity] Adds hydroelastic support for Convex shapes

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Declaring a Convex shape to be rigid, will now produce a hydroelastic representation. It is treated the same as a more general Mesh.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review.

(This should alleviate your Convex problems.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ-FK4M-aj8J-916yKn:bgqrdbr)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with a minor nit - thanks!!!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ-Id8m5WFRvuHNVoUV:b-eexsvr)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ-IFYNEg5IHh_u-7Af:-MJ-IFYNEg5IHh_u-7Ag:bfarwb1) (no related file):*
Looks like you have a related test in for the proximity engine?
https://drake-cdash.csail.mit.edu/testDetails.php?test=39085579&build=1345425
```
[ RUN      ] ProximityEngineTests.ProcessHydroelasticProperties
...
geometry/test/proximity_engine_test.cc:197: Failure
Expected equality of these values:
  ProximityEngineTester::hydroelastic_type(convex_id, engine)
    Which is: rigid
  HydroelasticType::kUndefined
    Which is: undefined
```

---
___
*[geometry/proximity/test/hydroelastic_internal_test.cc, line 590 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ-HacL8LCdc47xDHel:-MJ-HacL8LCdc47xDHem:bhyd1nk) ([raw file](https://github.com/robotlocomotion/drake/blob/dbe9522bf9288d0e98cb05de93e0123282402c27/geometry/proximity/test/hydroelastic_internal_test.cc#L590)):*
> ```cpp
>   std::string file =
>     FindResourceOrThrow("drake/geometry/test/quad_cube.obj");
>   const double scale = 1.1;
> ```

nit For both this and the mesh case, `scale` doesn't seem to be meaningfully tested.

It may be helpful to note / TODO that, or briefly test the maximum vertex distance from the centroid or geometric center, or something of that sort.

Is it possible to do that here?
Or if this data piping is handled elsewhere, can that be uber briefly mentioned?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed -- big enough changes that I'd like you to look before pushing it to platform.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ2soG_51tuhsqzyo_I:b-dxem62)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ-IFYNEg5IHh_u-7Af:-MJ2Xavy7GqPsJSEV7Ow:b-3en26b) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Looks like you have a related test in for the proximity engine?
https://drake-cdash.csail.mit.edu/testDetails.php?test=39085579&build=1345425
```
[ RUN      ] ProximityEngineTests.ProcessHydroelasticProperties
...
geometry/test/proximity_engine_test.cc:197: Failure
Expected equality of these values:
  ProximityEngineTester::hydroelastic_type(convex_id, engine)
    Which is: rigid
  HydroelasticType::kUndefined
    Which is: undefined
```
</blockquote></details>

D'oh! And Done. 

---
___
*[geometry/proximity/test/hydroelastic_internal_test.cc, line 590 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ-HacL8LCdc47xDHel:-MJ2YKcXC9nCqn0p_0ri:ba7d8nb) ([raw file](https://github.com/robotlocomotion/drake/blob/dbe9522bf9288d0e98cb05de93e0123282402c27/geometry/proximity/test/hydroelastic_internal_test.cc#L590)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For both this and the mesh case, `scale` doesn't seem to be meaningfully tested.

It may be helpful to note / TODO that, or briefly test the maximum vertex distance from the centroid or geometric center, or something of that sort.

Is it possible to do that here?
Or if this data piping is handled elsewhere, can that be uber briefly mentioned?
</blockquote></details>

Done

Great catch! I've modified the tests accordingly. It led to further modifications because `quad_cube.obj`, wasn't.

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks good!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ2zlnLEhBGMT8UwZGq:b-vs1prh)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ2zqS1CjJtzSYzVzOh:-MJ2zqS1CjJtzSYzVzOi:bmtld8j) (no related file):*
nit My only question right now is, what happens if you provide a `Convex` with a non-convex mesh - is that worth testing? (or is it already tested?)

---
___
*[geometry/proximity/test/hydroelastic_internal_test.cc, line 590 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ-HacL8LCdc47xDHel:-MJ2zZ9w2m5QyFMkrerw:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/dbe9522bf9288d0e98cb05de93e0123282402c27/geometry/proximity/test/hydroelastic_internal_test.cc#L590)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

Great catch! I've modified the tests accordingly. It led to further modifications because `quad_cube.obj`, wasn't.
</blockquote></details>

OK Sweet!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ2zqS1CjJtzSYzVzOh:-MJ3-4SS5NzAW87SgTxQ:b8yho9x) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit My only question right now is, what happens if you provide a `Convex` with a non-convex mesh - is that worth testing? (or is it already tested?)
</blockquote></details>

(Perhaps this can be made as a brief documentation note on the `Convex` overload for `MakeRigidRepresentation`?)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ2zqS1CjJtzSYzVzOh:-MJ3-DDvBoRU0_hsEYIx:b-9zs4co) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Perhaps this can be made as a brief documentation note on the `Convex` overload for `MakeRigidRepresentation`?)
</blockquote></details>

FWIW I think it's totes fine if it's completely unchecked - actually, I think I would stand to explicitly benefit from that ;)

Just seeing if it'd be possible to mention that.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ2zqS1CjJtzSYzVzOh:-MJ32ae0Bc-7jp3ZCLfW:b-g431zo) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW I think it's totes fine if it's completely unchecked - actually, I think I would stand to explicitly benefit from that ;)

Just seeing if it'd be possible to mention that.
</blockquote></details>

Comment added.  (Note: one of my OKRs this quarter will bring this (and other) information out into public documentation such that it is discoverable).

---

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!
+@sammy-tri for platform review, please!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ37f3-28mQ9j5IOHAP:bdvaa2g)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14178#-MJ2zqS1CjJtzSYzVzOh:-MJ37do61upik60_G0Xy:b-w196av) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Comment added.  (Note: one of my OKRs this quarter will bring this (and other) information out into public documentation such that it is discoverable).
</blockquote></details>

OK Thanks!

---

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14178#-:-MJ3Z-2q-PfkVh83aCLo:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
