### PR TITLE
[fem] Report status of Petsc solver

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

This PR comes from a discussion in the review of #16917.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961#-:-N-_64c0E1LV_fyyLyGL:bswqqxl)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961#-:-N-caOVxC45ksVfrX-Gn:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cZcbG4s0c2XIWAe7Z:-N-cZcbH4VMwxcmVQmXc:b-ny8rt1) ([raw file](https://github.com/robotlocomotion/drake/blob/3b1e794e1361b434873f0d345eb8c31c0ee33b68/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L114)):*
> ```objc
>   PetscSolverStatus Solve(SolverType solver_type,
>                           PreconditionerType preconditioner_type,
>                           const VectorX<double>& b, VectorX<double>* x) const;
> ```

you might want to use `EigenPtr` as you do below in SolveInPlace?
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 181 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-c_T5Q-MkQ4GxfZGnZ:-N-c_T5Q-MkQ4GxfZGn_:bxt6y93) ([raw file](https://github.com/robotlocomotion/drake/blob/3b1e794e1361b434873f0d345eb8c31c0ee33b68/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L181)):*
> ```cpp
>     bool converged = reason == KSP_CONVERGED_RTOL ||
>                      reason == KSP_CONVERGED_ATOL ||
>                      reason == KSP_CONVERGED_ITS;
> ```

according to those docs it looks like the right way to do this (without having to enumerate each possible reason) is with `const bool converged = reason > 0`?

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961#-:-N-cuwlS0JIKARNH9ira:b3yut2i)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cZcbG4s0c2XIWAe7Z:-N-cuw4Q5bnV6xo7kUda:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b1e794e1361b434873f0d345eb8c31c0ee33b68/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L114)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

you might want to use `EigenPtr` as you do below in SolveInPlace?
</blockquote></details>

Done.
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 181 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-c_T5Q-MkQ4GxfZGnZ:-N-cuva5ElYPc6aPY0YS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b1e794e1361b434873f0d345eb8c31c0ee33b68/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L181)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

according to those docs it looks like the right way to do this (without having to enumerate each possible reason) is with `const bool converged = reason > 0`?
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri, @jwnimmer-tri, and @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cwE7h9RXqrs1HNAgv:-N-cwE7h9RXqrs1HNAgw:biiyje5) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L108)):*
> ```objc
>    If the solver fails, the value in x will be undefined.
>    @pre b.size() == A.rows()
>    @pre x != nullptr and x->size() == b.size()
> ```

btw, did this requirement change only because we are now using EigenPtr? that'd be weird
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 180 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cvzfO8lxvyOHxiwKN:-N-cvzfP4Nsp1PI3JNfe:brpkb21) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L180)):*
> ```cpp
>      https://petsc.org/main/docs/manualpages/KSP/KSPGetConvergedReason.html#KSPGetConvergedReason
>      for the list of convergence criteria.  */
>     bool converged = reason > 0;
> ```

minor, `const`

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri, @jwnimmer-tri, and @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cwE7h9RXqrs1HNAgv:-N-cx4jQCubCLWomqaFU:bx4iblh) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L108)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, did this requirement change only because we are now using EigenPtr? that'd be weird
</blockquote></details>

Yes. The size of the vector can't be changed via EigenPtr.
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 180 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cvzfO8lxvyOHxiwKN:-N-cxEvyCSaKGeqacghZ:b-ikzppp) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L180)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, `const`
</blockquote></details>

working. I'll roll this change into the response to platform.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961#-:-N-cxc8F0wopVMgZQf0Z:bnfp4nl)* status: 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cwoyO9V6_E3ELSVXw:-N-cwoyO9V6_E3ELSVXx:b-xa2opw) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L112)):*
> ```objc
>    this method even if the matrix hasn't changed.
>    @pre Matrix must be assembled. See AssembleIfNecessary(). */
>   PetscSolverStatus Solve(SolverType solver_type,
> ```

nit Consider using ``[[nodiscard]]` here (and below), so that it's impossible to accidentally ignore the success-vs-failure condition?

If unit tests have false warnings (e.g., in EXPECT_THROWS), you can place `unused()` around the Solve to clarify the intent.
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cxRY4AnDtOIUilHbd:-N-cxRY4AnDtOIUilHbe:b-w69j3q) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L118)):*
> ```objc
> 
>   /* Similar to Solve(), but writes the result in `b`. The value in `b` is
>    undefined if the solve fails.
> ```

nit It took me a moment to understand what's happening here.  The `b` is both an input (b) and output (x).  Maybe document `@param[in,out] b ...` to clarify that?  Or name it `b_in_x_out` to be explicit.  Calling it just `b` is a bit awkward, since it's not actually `b` on the way out.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 157 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cyNIbBOI1XKdvjtbq:-N-cyNIbBOI1XKdvjtbr:bforepe) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L157)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(x, x_expected, b.norm() * kEps));
> 
>   status = A->Solve(
> ```

nit Consider resetting `x` prior to each Solve(), or using a new variable for every test case, so that past successes don't spuriously paper over bugs in the repeated calls (e.g., the implementation failes to write anything into `x`)?  From the implementation I see that `b` will reset `x` already, but that might not always be the case if the implementation changes?
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 294 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cyvDi6Uwzp1-huAPn:-N-cyvDi6Uwzp1-huAPo:bz3lic1) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L294)):*
> ```cpp
>     x->resize(b.size());
>     A->Solve(PetscSymmetricBlockSparseMatrix::SolverType::kMINRES,
>              PetscSymmetricBlockSparseMatrix::PreconditionerType::kNone, b, x);
> ```

Unclear why it's OK to ignore the status return value here.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961)* status: 2 unresolved discussions (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cwoyO9V6_E3ELSVXw:-N-dREyL0uZ-zcQ-_5zb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider using ``[[nodiscard]]` here (and below), so that it's impossible to accidentally ignore the success-vs-failure condition?

If unit tests have false warnings (e.g., in EXPECT_THROWS), you can place `unused()` around the Solve to clarify the intent.
</blockquote></details>

Done.
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cxRY4AnDtOIUilHbd:-N-dR1OOAkmw78PGHpcB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a moment to understand what's happening here.  The `b` is both an input (b) and output (x).  Maybe document `@param[in,out] b ...` to clarify that?  Or name it `b_in_x_out` to be explicit.  Calling it just `b` is a bit awkward, since it's not actually `b` on the way out.
</blockquote></details>

Done.
___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 180 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cvzfO8lxvyOHxiwKN:-N-dQOOJ3UJ9qmV-sk-n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L180)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

working. I'll roll this change into the response to platform.
</blockquote></details>

Done.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 157 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cyNIbBOI1XKdvjtbq:-N-dPmuo1x7mZyJ5T4b8:b-qu6n94) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider resetting `x` prior to each Solve(), or using a new variable for every test case, so that past successes don't spuriously paper over bugs in the repeated calls (e.g., the implementation failes to write anything into `x`)?  From the implementation I see that `b` will reset `x` already, but that might not always be the case if the implementation changes?
</blockquote></details>

Good point. Done.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 294 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16961#-N-cyvDi6Uwzp1-huAPn:-N-dQNPl8FJSaBBRRPS6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cbfbf6fd1c8dd56a90b2f4adb485e6c50b56f28/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L294)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why it's OK to ignore the status return value here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16961)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
