### PR TITLE
pybind: Rebase + CMake updates for RobotLocomotion/drake-shambhala#98

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Steps:
- [x] Validate for RobotLocomotion/pybind11#18
- [x] Make a follow-up PR to merge in pybind/pybind11#1373 and pybind/pybind11#1367 while they are under review: https://github.com/RobotLocomotion/pybind11/pull/19
- Merge to enable RobotLocomotion/drake-shambhala#98

\cc @jamiesnape 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8860)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Validating RobotLocomotion/pybind11@719532b522e9d30aeb2f05da6e148580323f6e9f for RobotLocomotion/pybind11#18

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for both reviews, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8860#-:-LDMhCwe1k1aORGVJ49z:bfw3kon)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8860#-:-LDMlQSbEsrqK9o8KLcR:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Failure in `linux-xenial-clang-bazel-experimental-debug` is ignorable, as it will be resolved by #8880.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

**Pull request merged**
