### PR TITLE
Updated documentation to point to unit test page.

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2445

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2446)

### CODE REVIEW

**Comment by liangfok** [comment]
Perhaps +@jwnimmer-tri for feature review and maybe also platform review?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Updated documentation to point to unit test page\.
> 
> Closes https://github.com/RobotLocomotion/drake/issues/2445
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-:-KIZC2S6SN1_t5c-n1Oq:892394615)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/from_source.rst, line 115 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIZIomsoftL39ZvKu9W:-KIZIomsoftL39ZvKu9X:928033308) ([raw file](https://github.com/robotlocomotion/drake/blob/eea76a67613d1def27b0366b92a4428300557c42/drake/doc/from_source.rst#L115)):*
> ```reStructuredText
> 
> For an exhaustive test (which can take more than an hour to run if you have all
> of the backend solvers enabled), see the instructions here:
> ```

I think this `from_source` page should still provide the one-liner that runs all the tests (to get users quickly up and running), even if it links to a separate page with more verbose details.

---

*[drake/doc/from_source.rst, line 118 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIZJAfkEISieXvjsOhN:-KIZJAfl2eNJQf29B5qE:1181673646) ([raw file](https://github.com/robotlocomotion/drake/blob/2df6ac4f36daea766de226e07abea933a60717d7/drake/doc/from_source.rst#L118)):*
> ```reStructuredText
> 	make test
> 
> Note that this is slow -- it starts a fresh instance of MATLAB for every individual test -- but it is the most robust way to test for issues that can potentially crash MATLAB.  Currently, the make test script is setup to send a summary of the success / failures to our continuous integration server after it finishes all of the jobs.  This was our internal setup, and has been left there for now so that we can help you debug your installations.
> ```

BTW That for fixing the "sends a summary"; I didn't realize the documentation claimed the Makefile did that, when I removed it from the makefile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Please forgive me; I couldn't help but polish the unit testing instructions some.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Perhaps +@jwnimmer-tri for feature review and maybe also platform review?
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/from_source.rst, line 115 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIZIomsoftL39ZvKu9W:-KIcVE4I3zOik3xp2q_T:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/eea76a67613d1def27b0366b92a4428300557c42/drake/doc/from_source.rst#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think this `from_source` page should still provide the one-liner that runs all the tests (to get users quickly up and running), even if it links to a separate page with more verbose details.
</details>
Done.

---

*[drake/doc/from_source.rst, line 118 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIZJAfkEISieXvjsOhN:-KIcVFCRsL7YyNbuzOOJ:536472645) ([raw file](https://github.com/robotlocomotion/drake/blob/2df6ac4f36daea766de226e07abea933a60717d7/drake/doc/from_source.rst#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW That for fixing the "sends a summary"; I didn't realize the documentation claimed the Makefile did that, when I removed it from the makefile.
</details>
No problem! I agree such involuntary feedback should be removed or made opt-in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-:-KIcVmG7rnz0NDiSbrNA:-1104231172)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 117 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcn-AlrFod3AFfqm_Y:-KIcn-AmdmAK1chKSkf5:16682869) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L117)):*
> ```reStructuredText
> of the solvers enabled), execute the following::
> 
>     $ cd [drake distro]/drake/pod-build
> ```

All command lines in this rst file use `drake-distro` and not `[drake distro]`.  I think `[drake distro]` is an anti-pattern.

It is not standard shell syntax so it might be confusing to naive readers.

It is not a worthwhile abstraction, either, because we are not offering (and should not offer) to teach users how to build the source using a different superbuild directory name.  There is no reason to allow for variance here. Everyone[1] should call it `drake-distro` on disk, and the docs should use that name pervasively, to remove all opportunity for doubt about what directory is supposed to be what.  Variety is the enemy of reproducibility.  We should only add it when it meets some need, and I don't see the need in this case.

[1] Of course, expert users can do whatever they want, and implicitly agree to deal with the fallout if they screw something up.

---

*[drake/doc/from_source.rst, line 118 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIco24Iqq7HtvphLTqp:-KIco24Iqq7HtvphLTqq:-1115138571) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L118)):*
> ```reStructuredText
> 
>     $ cd [drake distro]/drake/pod-build
>     $ cmake -DLONG_RUNNING_TESTS=ON ..
> ```

I am unconvinced that the "common case" recommendation for testing from-source builds should include LONG_RUNNING_TESTS.  It seems like they don't add much value for most users or developers.  Convince me otherwise?

---

*[drake/doc/unit_testing_instructions.rst, line 54 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcpDAIkqiXz5_lTTWf:-KIcpDAIkqiXz5_lTTWg:518957159) ([raw file](https://github.com/robotlocomotion/drake/blob/69a781128739335d04909c087d3de3817cdb3e71/drake/doc/unit_testing_instructions.rst#L54)):*
> ```reStructuredText
>     $ cd [drake build artifacts directory]
>     $ cmake -DLONG_RUNNING_TESTS=ON ..
>     $ make
> ```

The new text looks fine, but I'd like a moment to run this locally before signing off on the PR.  I should have some time this afternoon to try it.

---

*[drake/doc/windows.rst, line 171 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcol3jxhFDRj0GbSyG:-KIcol3jxhFDRj0GbSyH:-546335763) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/windows.rst#L171)):*
> ```reStructuredText
> To verify Drake was successfully compiled, run the unit tests::
> 
>     $ cd [build artifacts directory]/drake
> ```

Please confirm for me that you've tested this alternation on a windows build, and that it works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446)*

**Comment by liangfok** [comment]
I've addressed all reviewer comments. Thanks for the comments!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I addressed all reviewer comments. Please forgive me; I couldn't help but polish the unit testing instructions some.
</details>


---

Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/from_source.rst, line 117 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcn-AlrFod3AFfqm_Y:-KIcsP2uFlDQitqdzDRm:668711807) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> All command lines in this rst file use `drake-distro` and not `[drake distro]`.  I think `[drake distro]` is an anti-pattern.
> 
> It is not standard shell syntax so it might be confusing to naive readers.
> 
> It is not a worthwhile abstraction, either, because we are not offering (and should not offer) to teach users how to build the source using a different superbuild directory name.  There is no reason to allow for variance here. Everyone[1] should call it `drake-distro` on disk, and the docs should use that name pervasively, to remove all opportunity for doubt about what directory is supposed to be what.  Variety is the enemy of reproducibility.  We should only add it when it meets some need, and I don't see the need in this case.
> 
> [1] Of course, expert users can do whatever they want, and implicitly agree to deal with the fallout if they screw something up.
</details>
I'm pretty sure I've seen many other libraries use the `[directory description]` moniker, but it may be something from the ROS world, from which I come. Since I'm not sufficiently motivated to fight this battle, I've changed it as you recommend. :smiling_imp: 

I also removed the dollar signs, which, as you know, indicate a terminal prompt, to be consistent with the rest of this page.

---

*[drake/doc/from_source.rst, line 118 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIco24Iqq7HtvphLTqp:-KIcs7CGDuDidqGws-mK:-95537076) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am unconvinced that the "common case" recommendation for testing from-source builds should include LONG_RUNNING_TESTS.  It seems like they don't add much value for most users or developers.  Convince me otherwise?
</details>
Don't the words "exhaustive test" imply _all_ tests including long running ones?

---

*[drake/doc/windows.rst, line 171 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcol3jxhFDRj0GbSyG:-KIct3-AQnEAmuBdyTtp:33825450) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/windows.rst#L171)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please confirm for me that you've tested this alternation on a windows build, and that it works?
</details>
Yes, I confirm that it works. In fact, there are _no_ unit tests defined within the `[build artifacts directory]` in an out-of source build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-:-KIctD1o5mritQPK89yR:-1303832233)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 118 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIco24Iqq7HtvphLTqp:-KId8pVGCkHJWkM8Rfkk:1225759843) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L118)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Don't the words "exhaustive test" imply _all_ tests including long running ones?
</details>
Possibly?  But maybe the solution then is to reword the that phrase?  My tentative position is that we should recommend the common case in this page, which is not to run the long-running-tests.  Does _anyone_ actually use that setup as a default?  (I don't.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 54 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIcpDAIkqiXz5_lTTWf:-KIdAvuoKjyEhOH0zule:-267832716) ([raw file](https://github.com/robotlocomotion/drake/blob/69a781128739335d04909c087d3de3817cdb3e71/drake/doc/unit_testing_instructions.rst#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The new text looks fine, but I'd like a moment to run this locally before signing off on the PR.  I should have some time this afternoon to try it.
</details>
Great; works for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446)*

**Comment by liangfok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 118 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-KIco24Iqq7HtvphLTqp:-KIdJdDwcJbV87hdL8wJ:-1437751608) ([raw file](https://github.com/robotlocomotion/drake/blob/70eaeaa66cd9e7714e76415db6cc438168e83543/drake/doc/from_source.rst#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Possibly?  But maybe the solution then is to reword the that phrase?  My tentative position is that we should recommend the common case in this page, which is not to run the long-running-tests.  Does _anyone_ actually use that setup as a default?  (I don't.)
</details>
Done. PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I've addressed all reviewer comments. Thanks for the comments!
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2446#-:-KIdLwh4vS5NQ-6BbW2l:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master and not-going-to-wait-for-jenkins-on-a-doc-change.

**Pull request merged**
