### PR TITLE
Change the installation on macOS to use just "protobuf".

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This is one smaller part of #7323 , which is a smaller part of #7278 .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7409)

### CODE REVIEW

**Comment by clalancette** [comment]
@BetsyMcPhail FYI, we'll need new macOS images with this.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7409#-:-KyGjHy4EjHCHEYMfdgN:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
All mac images have been updated with the latest install script. Also, protobuf@2.6 was removed.

**Pull request merged**
