### PR TITLE
Pick and place demo fix (assorted)

### PR DESCRIPTION
**Pull request by sammy-tri**
Pull various fixes/improvements for the pick and place demo from a personal branch.  I've tried (mostly) to keep distinct changes in different commits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6863)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-KrlFW4pzoH_eJ-AQzf8:bvpmr17)*

**Comment by avalenzu** [comment]
Review pass done. CI is sad :(

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrlXU9N3O6YCZUW0FGy:-KrlXU9N3O6YCZUW0FGz:bvmk8ok) ([raw file](https://github.com/robotlocomotion/drake/blob/69b1a1c3fd646b49d97cd24c052400290a2a6eba/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L145)):*
> ```cpp
>                         max_plan_velocity / max_joint_velocity);
>     for (int i = 0; i < num_time_steps; i++) {
>       (*time)[i] *= max_plan_velocity / max_joint_velocity;
> ```

If you have a situation where one the velocity is very high for a single step in the plan, this will cause the parts of the plan that would otherwise have been at normal speed to be _very_ slow. That could be fine, but I just want to make sure it's what you want.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrlZovgmnx-ctFWOCJu:-KrlZovgmnx-ctFWOCJv:b-tvrq5c) ([raw file](https://github.com/robotlocomotion/drake/blob/69b1a1c3fd646b49d97cd24c052400290a2a6eba/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L188)):*
> ```cpp
>       const double current_plan_time = context.get_time() - plan.start_time;
>       MakeFixedPlan(context.get_time(),
>                     plan.pp.value(current_plan_time),
> ```

Is this guaranteed to be close to the robot's current state?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-Krl_bP7PRVSF6QUBQmY:by0wvsk)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-snopt please

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrlXU9N3O6YCZUW0FGy:-KrleRp2cok_YnFN1FTV:b-wakc3r) ([raw file](https://github.com/robotlocomotion/drake/blob/69b1a1c3fd646b49d97cd24c052400290a2a6eba/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L145)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

If you have a situation where one the velocity is very high for a single step in the plan, this will cause the parts of the plan that would otherwise have been at normal speed to be _very_ slow. That could be fine, but I just want to make sure it's what you want.
</blockquote></details>

Added a comment to indicate that this is known behavior.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrlZovgmnx-ctFWOCJu:-KrlfBg3UB9hKMf9I5Md:b55rdid) ([raw file](https://github.com/robotlocomotion/drake/blob/69b1a1c3fd646b49d97cd24c052400290a2a6eba/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L188)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Is this guaranteed to be close to the robot's current state?
</blockquote></details>

There's no particular guarantee.  It should be close to whatever was being output at the last call to `OutputState` (unless the context time has advanced significantly, which seems unlikely).  Commanding the last measured position can actually cause the robot to move fairly significantly in the presence of steady state error (which the iiwa can have quite a bit of depending on the configured control mode/parameters).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-KrlgTWs3lhePZA2hdAe:b-bbc16h)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrlZovgmnx-ctFWOCJu:-KrloT-aI9Nn4etkz2o3:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/69b1a1c3fd646b49d97cd24c052400290a2a6eba/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L188)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

There's no particular guarantee.  It should be close to whatever was being output at the last call to `OutputState` (unless the context time has advanced significantly, which seems unlikely).  Commanding the last measured position can actually cause the robot to move fairly significantly in the presence of steady state error (which the iiwa can have quite a bit of depending on the configured control mode/parameters).
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-Krlobyjym7gRjvK1kKi:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review.  I think the mac CI failure is unrelated to this change.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-KrmYqwPGbcGxr2HzzFH:b-hy3dyw)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few BTWs, ptal. I can't figure out what the CI failure is about -- I'm fine with it if you're sure it's unrelated. It does say something about trajectory_optimization, so it isn't *obviously* unrelated. 

---

Reviewed 6 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 131 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq5z8ADYbmpI3sTjhV:-Krq5z8ADYbmpI3sTjhW:bchnzi1) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L131)):*
> ```cpp
>   const int num_time_steps = keyframes.cols();
> 
>   Eigen::MatrixXd velocities(keyframes.rows(), num_time_steps - 1);
> ```

BTW could use a short comment explaining what you're about to do here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq3X2O-fCyLNbAMd34:-Krq3X2O-fCyLNbAMd35:b3ebcbl) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L133)):*
> ```cpp
>   Eigen::MatrixXd velocities(keyframes.rows(), num_time_steps - 1);
>   for (int i = 0; i < velocities.cols(); i++) {
>     for (int j = 0; j < keyframes.rows(); j++) {
> ```

BTW I found this a little hard to read. The usual convention in computational matrix code is to index rows by i and columns by j. Also you are just filling in the velocity matrix which wasn't obvious since one of the loops refers to keyframes. Please consider:
```c++
for (int i = 0; i < velocities.rows(); i++) {
    for (int j = 0; j < velocities.cols(); j++) {
      velocities(i, j) =
          std::abs((keyframes(i, j + 1) - keyframes(i, j)) /
                   ((*time)[j + 1] - (*time)[j]));
    }
``` 

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 136 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq4v9hFnA_rdk4Pjj7:-Krq4v9hFnA_rdk4Pjj8:b-tlxa4v) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L136)):*
> ```cpp
>       velocities(j, i) =
>           std::abs((keyframes(j, i + 1) - keyframes(j, i)) /
>                    ((*time)[i + 1] - (*time)[i]));
> ```

BTW this will divide by zero if adjacent times are the same. I presume there is some reason that can't happen. It would be good to state why you don't have to worry about it here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq5VysjpzX_acFxavc:-Krq5VytJCC2mk87JeAB:bk0qwsf) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L146)):*
> ```cpp
>   if (max_plan_velocity > max_joint_velocity) {
>     drake::log()->debug("Slowing plan by {}",
>                         max_plan_velocity / max_joint_velocity);
> ```

BTW you can use the SPDLOG_DEBUG macro here if you want the code to disappear completely in Release builds.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq2Od6TC44SgJ5kuEY:-Krq2Od6TC44SgJ5kuEZ:bsyb5r3) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.h#L53)):*
> ```objc
> 
> /// Scales a plan so that no step exceeds the maximum joint velocity
> /// specified.
> ```

BTW should mention that time's size must match the number of columns in keyframes (I found that surprising; would have expected one keyframe per row). It would be helpful to briefly document the expected layout of the keyframes matrix, or at least refer to the place where it is documented.

Another precondition that should be mentioned here is that times must be in strictly increasing order.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq1_pzlkSWhdpiXjDR:-Krq1_pzlkSWhdpiXjDS:b-papxer) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.h#L54)):*
> ```objc
> /// Scales a plan so that no step exceeds the maximum joint velocity
> /// specified.
> void ApplyJointVelocityLimits(double max_joint_velocity,
> ```

BTW seeing all these free functions makes me think there is a class missing here, in which these would be methods. Not a defect in this PR, but I think you should consider refactoring this soon, before adding any more free functions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq0v8IqNukVQxnHCVT:-Krq0v8IqNukVQxnHCVU:b-68tvx3) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L28)):*
> ```cpp
> }
> 
> const double kMaxIiwaJointVelocity = 1.;  // rad/s
> ```

BTW can you say why this particular limit? Is this a property of the arm or a policy you're choosing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-Krq7IUQe-pkDYlQmsVd:b-1z3ea1)*

**Comment by sammy-tri** [comment]
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 131 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq5z8ADYbmpI3sTjhV:-KrqDwTGu4Ux0OP5I-LM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L131)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could use a short comment explaining what you're about to do here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq3X2O-fCyLNbAMd34:-KrqCz2FbJu7o7RH5Bnc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L133)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I found this a little hard to read. The usual convention in computational matrix code is to index rows by i and columns by j. Also you are just filling in the velocity matrix which wasn't obvious since one of the loops refers to keyframes. Please consider:
```c++
for (int i = 0; i < velocities.rows(); i++) {
    for (int j = 0; j < velocities.cols(); j++) {
      velocities(i, j) =
          std::abs((keyframes(i, j + 1) - keyframes(i, j)) /
                   ((*time)[j + 1] - (*time)[j]));
    }
``` 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 136 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq4v9hFnA_rdk4Pjj7:-KrqCzsSj46KH82NrIbp:b-rz2q6z) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this will divide by zero if adjacent times are the same. I presume there is some reason that can't happen. It would be good to state why you don't have to worry about it here.
</blockquote></details>

Added DRAKE_ASSERT to enforce the newly added doxygen comment about times being in strictly increasing order.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.cc, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq5VysjpzX_acFxavc:-KrqDDHPqVjirCza_FYH:b-pae60i) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.cc#L146)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW you can use the SPDLOG_DEBUG macro here if you want the code to disappear completely in Release builds.
</blockquote></details>

I've been looking at this from time to time in Release builds, it seems fairly cheap to keep there.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq2Od6TC44SgJ5kuEY:-KrqC54GgyaUuQKKYPhX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should mention that time's size must match the number of columns in keyframes (I found that surprising; would have expected one keyframe per row). It would be helpful to briefly document the expected layout of the keyframes matrix, or at least refer to the place where it is documented.

Another precondition that should be mentioned here is that times must be in strictly increasing order.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq1_pzlkSWhdpiXjDR:-KrqC9noXmRQpdDQYDF4:b-pd9u83) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/iiwa_common.h#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW seeing all these free functions makes me think there is a class missing here, in which these would be methods. Not a defect in this PR, but I think you should consider refactoring this soon, before adding any more free functions.
</blockquote></details>

I agree it's a bit odd looking, but I'm not sure if the functions in such a class would even share any member variables (maybe a RigidBodyTree for a couple of them).  Will keep it in mind.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/action.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-Krq0v8IqNukVQxnHCVT:-KrqDu4pey8TGHhb9Ddp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0facca0f3992b7453e7a9c2ea04abb43c5ec211/drake/examples/kuka_iiwa_arm/pick_and_place/action.cc#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can you say why this particular limit? Is this a property of the arm or a policy you're choosing?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863)*

**Comment by sherm1** [comment]
Thanks, @sammy-tri -- looks great. Spotted a typo.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrqL_wObPsHFe8aFMMo:-KrqL_wObPsHFe8aFMMp:box7b13) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6fdc6c473316e07a0575ccb94a592c0d3ed033/drake/examples/kuka_iiwa_arm/iiwa_common.h#L53)):*
> ```objc
> 
> /// Scales a plan so that no step exceeds the maximum joint velocity
> /// specified.  The number of columts in @p keyframes must match the
> ```

BTW columts -> columns

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrqLhNG-hZxfAV_DJoY:-KrqLhNG-hZxfAV_DJoZ:box7b13) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6fdc6c473316e07a0575ccb94a592c0d3ed033/drake/examples/kuka_iiwa_arm/iiwa_common.h#L61)):*
> ```objc
> 
> /// Makes a robotlocomotion::robot_plan_t message.  The number of
> /// columts in @p keyframes must match the size of @p time.  Times
> ```

BTW columts -> columns

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-KrqLoiH6Un85SI3l9W0:bft9l9w)*

**Comment by sammy-tri** [comment]
Thanks!

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrqL_wObPsHFe8aFMMo:-KrqNQUaUPMFt7_tdI63:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6fdc6c473316e07a0575ccb94a592c0d3ed033/drake/examples/kuka_iiwa_arm/iiwa_common.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW columts -> columns
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-KrqLhNG-hZxfAV_DJoY:-KrqNSw3M_41vHRZ-Qca:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a6fdc6c473316e07a0575ccb94a592c0d3ed033/drake/examples/kuka_iiwa_arm/iiwa_common.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW columts -> columns
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863#-:-KrqNZUWQ92cpT5jWG--:b-ucfknh)*

**Comment by avalenzu** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6863)*

**Pull request merged**
