### PR TITLE
doc: Add release notes v0.30.0

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri , +@xuchenhan-tri for anything that may fall under no-release-notes policy: hydroelastic, soft-sim progress.
+@jwnimmer-tri for build section, and overall form and content.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_lvMI76Ry1SjWpvl_r:bnv06gv)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),xuchenhan-tri,jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_lvRk19Va-2-5B5lr-:-M_lvRk19Va-2-5B5lr0:b-jfzox1) (no related file):*
I noticed some deprecations with an odd date that didn't get deleted; I'll post a PR separately for that.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_lvRk19Va-2-5B5lr-:-M_m57j097bIIO-ro9jT:b-oiwxb4) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I noticed some deprecations with an odd date that didn't get deleted; I'll post a PR separately for that.
</blockquote></details>

https://github.com/robotlocomotion/drake/pull/15050 -- should get merged into this branch once landed.

---

**Review by xuchenhan-tri — COMMENTED** [review]
@rpoyner-tri By soft-sim progress, I suppose you are referring to PR #14844? I believe that falls under the "contact solver" progress category. I didn't find any no-release-notes policy related to that, but digging through the old release notes I saw that other contact solver progress PRs (e.g. #13958) were **not** mentioned in the release notes. I therefore believe the same would apply here.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_nZIn7DosuRum3K-i1:b-g89dxv)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
In my mind, the principle for what to include goes like this:

Is there a new feature that is now available to end users; or, is there a bug fix in a pre-existing feature?  If yes to either, then note it.

That's why hydroelastic is not notable -- because it's designated as not being ready for end users yet.  In #14844 the new `PgsSolver` class was added to an _internal_ namespace.  That means it's unavailable to end-users, so it should not appear in the release notes.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_pgJfHANWiLiAUUzxF:b-9dp2vy)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.30.0.md, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_pfzYy5VttU26VlEVs:-M_pfzYy5VttU26VlEVt:b-iiprdv) ([raw file](https://github.com/robotlocomotion/drake/blob/a3c1c6004628a07376bea9911ecbce63a54395c1/doc/_release-notes/v0.30.0.md#L76)):*
> ```Markdown
> New features
> 
> * Implement PGS contact solver ([#14844][_#14844])
> ```

nit The `PgsSolver` class lives in the _internal_ namespace, so it should not appear in the release notes.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so car.  I've looked over everything except the "Multibody" section.  That section needs more surgery before its ready -- those bullets are not uniformly phrased, contain confusing abbreviations, contain non-notable remarks about internal and test-only code, contain non-notable remarks about documentation changes, etc.  Probably @SeanCurtis-TRI should and push fixes there directly (or delegate).

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_pluijEd5wxhbUXKdR:bnukz0j)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
Somehow the merge commit didn't get pushed, so I just did that now to fix Reviewable.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
Hmm.  It didn't actually fix Reviewable, though.  Might be worth dumping this PR and opening a new one from the same branch.

**Review by rpoyner-tri — COMMENTED** [review]
It showed for me. I had a similar issue with reviewable on some prior rev. Not sure what is up, but seems like a reviewable issue.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_q4iTF7OGK9H53zJVP:b-wgcnks)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: 6 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.30.0.md, line 14 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uiMRNDpD9mWWAisZY:-M_uiMRNDpD9mWWAisZZ:b6hzesv) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L14)):*
> ```Markdown
> # Breaking changes since v0.29.0
> 
> * On Ubuntu systems, Drake's now requires the AVX2 and FMA family of SIMD
> ```

nit s/Drake's/Drake
___
*[doc/_release-notes/v0.30.0.md, line 15 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uiDBFCgMU_cqykgNv:-M_uiDBFCgMU_cqykgNw:bbwgvmh) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L15)):*
> ```Markdown
> 
> * On Ubuntu systems, Drake's now requires the AVX2 and FMA family of SIMD
>   intrisics, i.e., the Intel's "Broadwell" microarchitecture or newer
> ```

nit s/intrisics/intrinsics
___
*[doc/_release-notes/v0.30.0.md, line 33 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uiZqdEBZAQdRZN_Jy:-M_uiZqdEBZAQdRZN_Jz:b-mww06e) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L33)):*
> ```Markdown
>   argument ([#14969][_#14969], [#15032][_#15032]).
> 
> * Within Drake's geometry support, all overloads ContactSurface::EvaluateE_MN()
> ```

BTW I'd argue that because we've never particularly advertised changes to hydroelastic, we shouldn't call out breaking changes to the APIs we've not advertised.
___
*[doc/_release-notes/v0.30.0.md, line 58 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uixia2PTL7zDuGLkV:-M_uixia2PTL7zDuGLkW:b-nn9u1z) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L58)):*
> ```Markdown
> * Do not declare state variables in AffineSystem if num_states==0 ([#15003][_#15003])
> * Deprecate and rename System::ValidateChildOfContext() ([#14999][_#14999])
> * Make internal methods of Diagram private ([#15031][_#15031])
> ```

btw: I feel this is covered in the breaking changes.
___
*[doc/_release-notes/v0.30.0.md, line 86 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_ujE9x4nxe0wAsRAtT:-M_ujE9x4nxe0wAsRAtU:bjzlpb5) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L86)):*
> ```Markdown
> * Add QuaternionEulerIntegrationConstraint ([#14960][_#14960])
> * Add CalcTotalMass methods to MultibodyPlant ([#14957][_#14957])
> * Progress on differentiable hydroelastic contact ([#14904][_#14904], [#14951][_#14951], [#14943][_#14943], [#14995][_#14995], [#14998][_#14998], [#14952][_#14952], [#15012][_#15012])
> ```

nit: These should all simply go under the "hydroelastic under construction" label we've historically used. I note that in release 27, specific hydro details were called out. That should be considered aberrant. We should simply have a single aggregate: "New hydroelastic contact model in progress" to capture all hydro-related PRs.
___
*[doc/_release-notes/v0.30.0.md, line 96 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_ujv7g8Q5L6CiP9Ga0:-M_ujv7g8Q5L6CiP9Ga1:b-171dqk) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L96)):*
> ```Markdown
> * Fix constness of JointActuator's SetRotorInertia() and SetGearRatio() ([#14983][_#14983])
> * Defer joint limits warning until it's relevant ([#15017][_#15017])
> * Fix bug in hydroelastic visualization ([#15000][_#15000])
> ```

nit: Another hydro item.

**Comment by jwnimmer-tri** [comment]
___
*[doc/_release-notes/v0.30.0.md, line 58 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uixia2PTL7zDuGLkV:-M_uky749wwHp8M8zSOv:b-89p3in) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: I feel this is covered in the breaking changes.
</blockquote></details>

My suggestion to notes-writers has been to have it _both_ in the overall breaking changes, _as well_ as the topical section's change list to contextualize it.  If we like that, I can work on clarifying it in the playbook.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.30.0.md, line 58 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uixia2PTL7zDuGLkV:-M_uud5w4ZtlRV8SF_og:b-m92qjr) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My suggestion to notes-writers has been to have it _both_ in the overall breaking changes, _as well_ as the topical section's change list to contextualize it.  If we like that, I can work on clarifying it in the playbook.
</blockquote></details>

Then I'd advocate some explicit recognition that the change gets extra coverage. I'd like to see it labeled as breaking here with, ideally, some kind of reference to the breaking section for more details.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.30.0.md, line 58 at r8](https://reviewable.io/reviews/robotlocomotion/drake/15045#-M_uixia2PTL7zDuGLkV:-M_uwVXZ66BC-WdyaNA8:b-ewinug) ([raw file](https://github.com/robotlocomotion/drake/blob/7fc8144213e2776576f88ce99939e320b88d9af9/doc/_release-notes/v0.30.0.md#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Then I'd advocate some explicit recognition that the change gets extra coverage. I'd like to see it labeled as breaking here with, ideally, some kind of reference to the breaking section for more details.
</blockquote></details>

Let's review. Of the breaking changes listed, all are listed twice. The contentious item is the only one where the breaking change was completely isolated in its own PR; all the rest had PRs with a mix of other work and breaking changes. None of the other PRs have a breaking change tag in their lower mentions.

You could argue thusly: this change's consequences are fully covered by the breaking change listing at the top, so no other mention is necessary. I'm reasonably convinced by this, and will just drop this line.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_v0HIG1wsngCnNT-Vh:bnfp4nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),xuchenhan-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

(Also, I know I'm late to this party....but why is there still so much chaff in Reviewable for changes that shouldn't be related to this PR?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_v2X2V1OwvKz5wX1Ls:b-o0h911)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
Merging master to pick up changes after the initial branch does that. Once it lands (with squash), none of it will matter.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_v2hvj8_JFvZ4ZB9T_:bopf2w0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_v2zd25ev53ZJgLjbr:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I don't remember seeing those artifacts in the past. But my memory is not to be trusted in this regard.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_v2xsxCUbHxk_NQXGG:b-npuwlc)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
The File Matrix default range is somehow borked.  If you click-drag (r_base .. r_final) in the File Matrix, then it shows up correctly.  An artifact of pushing patches from master to this branch without using a proper merge commit, and then me accidentally locking those in by clicking on a comment.

**Review by rpoyner-tri — COMMENTED** [review]
@jamiesnape v0.30.0 is out. The datestamp is 20210517. The git tag is v0.30.0 = 3e86d88df36f1a7d34cb5663e5f404eb43ce4e42.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15045#-:-M_vNX0B-v-IMpWwoV6J:b-i714uh)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Oops, #14852 was both a breaking change (for includes) and a newly-deprecated items change (for multiple models), but it only got release-noted as the former.  Thus, the removal of the feature in #15540 was not preceded by a deprecation announcement in the notes, only by a console warning at runtime.  Sorry, users!

**Pull request merged**
