### PR TITLE
Breaks cyclic dependencies between sensors and their outputs.

### PR DESCRIPTION
**Pull request by liangfok**
These cyclic dependencies were detected by @rpoyner-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5196)

### CODE REVIEW

**Comment by liangfok** [comment]
+@siyuanfeng-tri for feature review please. Thanks.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5196#-:-Kd7UuCRz5aekM5Q_1xE:bex8s8j)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5196#-:-Kd7WtSTcg96U_QPjueV:bg7igkv)*

**Comment by liangfok** [comment]
Thanks. 

+@soonho-tri and +@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5196#-:-Kd7ZMMD5L9oDfVxHyu8:b3y7vo7)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5196#-:-Kd7gn8d8LbWVFafytke:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5196#-:-KdBZCZCphOF1geCu9X5:bnfp4nl)*

**Pull request merged**
