### PR TITLE
[SAP] Implements contact constraint.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements cone constraint for the SAP solver.

Towards landing the [SapSolver](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in https://github.com/RobotLocomotion/drake/pull/16543.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715#-:-MxLUhyu4IPqEdJYwFW_:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: the code looks solid, just some nit requests in the documentation. +@rpoyner-tri for platform review, please. 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715#-:-MxfEMdL5cmd4PNRicne:bpwiw55)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxexewi2v2vYaIguKgJ:-Mxexewi2v2vYaIguKgK:b7wyk9u) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L22)):*
> ```objc
>     γₙ/δt = (−k⋅ϕ−d⋅vₙ)₊
>   where δt is the time step used in the formulation, k is the contact stiffness
>   (in N/m), d is the dissipation (in N⋅s/m) and (x)₊ = max(0, x). ϕ and vₙ are
> ```

nit: why not ϕₙ ?
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxeyN6i6PsDxTcYLKE0:-MxeyN6i6PsDxTcYLKE1:b-6fpdek) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L31)):*
> ```objc
>  Regularized Friction:
>   SAP contact constraints regularize friction. That is, in stiction the
>   tangential contact forces obeys:
> ```

nit: γₜ as expressed here is an impulse, correct? I am a little confused by the mixing of force/impulse language.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf6ZzI4oBvsTKEmIDF:-Mxf6ZzI4oBvsTKEmIDG:b-4qmym3) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L79)):*
> ```objc
>      ωₙ is below the limit ωₙ⋅δt ≤ 2π. That is, the period is Tₙ = β⋅δt. w
>      corresponds to a diagonal approximation of the Delassuss operator for
>      each contact. See [Castro et al., 2021. §IX.A] for details. */
> ```

nit: maybe a TODO to update the section number if the PDF at the link provided is edited with different sections.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf8YaC5qsTKTh41UTF:-Mxf8YaC5qsTKTh41UTG:bq5r8zx) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L49)):*
> ```cpp
> 
> template <typename T>
> VectorX<T> SapFrictionConeConstraint<T>::CalcBiasTerm(const T& time_step,
> ```

nit: a reference to the section in the paper that defines `vhat` for the friction cone constraint would be nice here. (Section VII I believe).
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf9a0Z7uIHjT5Iq0Ya:-Mxf9a0_Cm3LTebnkexx:bs9vluk) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L63)):*
> ```cpp
>   // Rigid approximation constant: Rₙ = β²/(4π²)⋅wᵢ when the contact frequency
>   // ωₙ is below the limit ωₙ⋅δt ≤ 2π. That is, the period is Tₙ = β⋅δt. See
>   // [Castro et al., 2021] for details.
> ```

nit: a section reference would be nice here as well. (Section IX I believe).
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfBUSG3qzqOn4YhRLV:-MxfBUSG3qzqOn4YhRLW:b1gwmm4) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L80)):*
> ```cpp
>     const Eigen::Ref<const VectorX<T>>& y,
>     const Eigen::Ref<const VectorX<T>>& R, EigenPtr<VectorX<T>> gamma,
>     MatrixX<T>* dPdy) const {
> ```

nit: maybe a reference to Appendix E here would be nice.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf4KM27taEnhKZZk1w:-Mxf4KM27taEnhKZZk1x:bjjfkyq) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L90)):*
> ```cpp
>     // TODO(amcastro-tri): consider exposing this as a parameter.
>     constexpr double soft_tolerance = 1.0e-7;
>     return sqrt(x.squaredNorm() + soft_tolerance * soft_tolerance);
> ```

nit: I assume the compiler is smart enough to not redo this multiplication of two `constexpr`, but you could make it explicit by just defining `soft_tolerance_squared`.
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 209 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfDRkd5oVsk44pl3UA:-MxfDRkd5oVsk44pl3UB:b5dgx7e) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L209)):*
> ```cpp
> // This method is used to validate SapFrictionConeConstraint::Project().
> // We use MathematicalProgram to obtain numerical values that we use to compare
> // againthe analytical projection implemented by SapFrictionConeConstraint.
> ```

nit: "againthe" -> "against the"

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfJRVJBYxLHa8uIAri:-MxfJRVJBYxLHa8uIArj:b-5j59js) (no related file):*
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos, and a mac build to avoid morning-after numeric regrets :)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715#-:-MxfK9n9BMyjsdPlF7Fn:b-s8wl5y)* status: 12 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfGsyD6OQDSh0MZ9w6:-MxfGsyEEvCjCZX6SziM:botio7e) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L68)):*
> ```objc
> 
>   /* Numerical parameters that define the constraint. Refer to this class's
>    documention for details. */
> ```

typo s/documention/documentation/



_Code quote:_
```objc
documention
```
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 248 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfHEZy94Qx9PaQoXRs:-MxfHEZy94Qx9PaQoXRt:b1o49fn) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L248)):*
> ```cpp
> 
> // Region I corresponds to the friction cone, see [Castro et al., 2021].
> // Phisically this is the stiction region.
> ```

typo s/Phisically/Physically/



_Code quote:_
```cpp
Phisically
```
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 301 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfHPT95jWwv_0pLKL4:-MxfHPT95jWwv_0pLKL5:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L301)):*
> ```cpp
> 
> // Region III corresponds to the polar cone, see [Castro et al., 2021].
> // Phisically this is the no contact region, i.e. gamma = 0.
> ```

typo



_Code quote:_
```cpp
Phisically
```

**Review by amcastro-tri — COMMENTED** [review]
ah, good call @rpoyner-tri. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715#-:-MxfTlq83dYODy4Ewktv:be0bsmb)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drake-jenkins-bot, @joemasterjohn, and @rpoyner-tri)

___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxexewi2v2vYaIguKgJ:-MxfTvcIDSxJxPYt1fmk:bqvkt6t) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L22)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: why not ϕₙ ?
</blockquote></details>

because there is no such a thing as "tangential" ϕₜ, as we do have for velocities. Also, ϕ is a very common notation for the distance function so I'm trying to stick to it. 
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxeyN6i6PsDxTcYLKE0:-MxfUYjA0Yoht7B4YcpK:bhcwwm1) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L31)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: γₜ as expressed here is an impulse, correct? I am a little confused by the mixing of force/impulse language.
</blockquote></details>

using impulses now.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf6ZzI4oBvsTKEmIDF:-MxfUwsnDMznwsR5qUck:b3ae5ej) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L79)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe a TODO to update the section number if the PDF at the link provided is edited with different sections.
</blockquote></details>

Good catch, removed section. Anyone looking at this `internal::` code should have a vague familiarity with that paper anyway.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf8YaC5qsTKTh41UTF:-MxfV9Xk5PQVdoOztcTT:b-otlwr0) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L49)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: a reference to the section in the paper that defines `vhat` for the friction cone constraint would be nice here. (Section VII I believe).
</blockquote></details>

per comment above. Sections will definitely change in the revised version and I believe anyone looking at this code should at least scan the paper for symbols. So from now on I think good idea not to reference specific sections.
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-Mxf9a0Z7uIHjT5Iq0Ya:-MxfVNM0-LhImV2mHHUJ:b-rqxvol) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L63)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: a section reference would be nice here as well. (Section IX I believe).
</blockquote></details>

ditto 
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfBUSG3qzqOn4YhRLV:-MxfVOaK2NlM39TzbURh:b-rqxvol) ([raw file](https://github.com/robotlocomotion/drake/blob/f7ff2b79adbdbeb3d8314fbd788775944d671605/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L80)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe a reference to Appendix E here would be nice.
</blockquote></details>

ditto

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drake-jenkins-bot, @joemasterjohn, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16715#-MxfJRVJBYxLHa8uIAri:-MxfWeBaDJO97BS4VFnw:b-tfb42m) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16715)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drake-jenkins-bot)

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Pull request merged**
