### PR TITLE
Hotfix to repair asan failure

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #14549. Relates  #14533.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14550)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jamiesnape for review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14550#-:-MRWOg443Qv5SEN1kbPh:b5bol5c)* status: LGTM missing from assignee jamiesnape (waiting on @jamiesnape)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please @drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please

**Review by jamiesnape — COMMENTED** [review]
Returning a reference seems consistent with the rest of the API, so if it passes CI, :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14550#-:-MRWPfToEM-TMFbkMkIw:bfwyrqu)* status: :shipit: complete! all discussions resolved, LGTM from assignee jamiesnape, exempt from platform review

**Comment by jamiesnape** [comment]
"Do not merge" pending the additional CI jobs.

**Pull request merged**
