### PR TITLE
New SpatialInertia factory method for SolidBox.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@seancurtis-tri 
Reminder: This is a prototype for SpatialInertia calculations for standard shapes.
PR #18407 is one of the many used to work on issue #18416.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIeI4Jr9VrJtJtKg7NK:b-xkp2ax)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`multibody/tree/spatial_inertia.h` line 139 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIeIPKQElKs39LrAfKl:-NIeIPKQElKs39LrAfKm:b-dn7ju6) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L139)):*
> ```objc
>   /// @param[in] lz The length of the box edge in the principal z-axis.
>   /// @retval M_BBo_B, B's spatial inertia about Bo, expressed in B.
>   /// @throws std::exception if any of Lx, Ly, Lz are negative.
> ```

Self-blocking: Change Lx, Ly, Lz to lx, ly, lz.

**Review by SeanCurtis-TRI — COMMENTED** [review]
You've clearly opted to avoid the python bindings as being "outside the scope of the prototype". It behooves you to explain what this is a prototype *of* and how to determine if the prototype succeeded or failed. Let me see if I can explain what I mean.

A prototype is an attempt at a possible solution. The act of making the prototype is not a measure of the "goodness" of the prototype (unless, in fact, what you are prototyping is the creation process -- not applicable here). The prototype must be tested in some way to determine if it represents a truly viable solution.

What makes this a prototype and what metric should we be applying to determine if this is a viable solution?. This PR seems to imply the basis for that evaluation lies *outside* this PR. As this PR is only 48 lines, it seems to me the exploration of its viability can and should be included in the PR. I would expect that, at the end of review, the prototype found here has either been fully evaluated or a concrete plan for determining its validity has been formulated (and reviewed). In the absence of either outcome, then this isn't properly serving as a prototype.

In support of that, one thing we discussed yesterday is that if you go this narrow in the scope of *new code*, this PR should include updated call sites that show benefit of the API (at least in internal Drake code). That would be one possible metric to measure validity.

FTR I also subscribe to the idea that if doing the review process the prototype is validated, then there's probably no good reason not to pivot the PR to make it *real* code (removing the "internal" note and adding bindings).

-(release notes: feature) I'm removing this while it's labeled as "internal only", because you haven't actually produced a piece of functionality that should be included in release notes. +(release notes: none) 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIgwSqr0ynUdGZhwGeZ:bqq810t)* status: 6 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/geometry_spatial_inertia.cc` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgxU16CKdW6VfF_GJ1:-NIgxU16CKdW6VfF_GJ2:bqhc0zq) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/geometry_spatial_inertia.cc#L34)):*
> ```cpp
>  private:
>   void ImplementGeometry(const geometry::Box& box, void*) final {
>     spatial_inertia_ = SpatialInertia<double>::SolidBoxWithDensity(density_,
> ```

I feel that this change (and the further anticipated changes) should require a change to the documentation in `geometry_spatial_inertia.h`. That file should bear less responsibility for documenting the semantics of the return values and be more explicit about the fact that it's a vector to the `SpatialInertia` APIs, limiting redundancy of APIs.

I'm disinclined to accept a TODO on this one because it is very much an implication of extending this prototype to cover all of the `Shape` types and I'd like to see what that would look like.
___
*[`multibody/tree/spatial_inertia.h` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgy2K9-BefVRg4ayIF:-NIgy2K9-BefVRg4ayIG:beze2i3) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L127)):*
> ```objc
>   static SpatialInertia<T> MakeUnitary();
> 
>   /// (Internal use only) ToDo(Mitiguy) Python-bind this and related functions.
> ```

nit: TODOs should never be in the same block as doxygen-like things.
___
*[`multibody/tree/spatial_inertia.h` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgyKF51YRlZpUnS_M8:-NIgyKF51YRlZpUnS_M9:b-4hwdcm) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L135)):*
> ```objc
>   /// @param[in] density mass per volume (kg/m³). If one length is zero, density
>   /// is mass per area. If two lengths are zero, density is mass per length.
>   /// @param[in] lx The length of the box edge in the principal x-axis.
> ```

BTW "principal x-axis" feels like a rather indirect way to say Bx. You've defined a frame B why ignore it now? 
___
*[`multibody/tree/spatial_inertia.cc` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgye3i014prRCE5QoJ:-NIgye3i014prRCE5QoK:b-63s9st) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.cc#L23)):*
nit: This comment is unhelpful. That is *literally* what `p_BoBcm` means. If you *really* wanted to give a hint to the user you'd write something like,

> By definition Bcm is coincident with Bo.

Arguably, no comment is necessary at all.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgzA6j7akExd_CzaCJ:-NIgzA6j7akExd_CzaCK:b-1t61k0) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/test/spatial_inertia_test.cc#L83)):*
> ```cpp
>       density, lx, ly, lz);
>   EXPECT_TRUE(CompareMatrices(M_expected.CopyToFullMatrix6(),
>                                        M.CopyToFullMatrix6()));
> ```

nit Incorrect horizontal whitespace.

In fact an application of clang-format changes this line and the previous for the better.

**Review by mitiguy — COMMENTED** [review]
@sean I agree that this should NOT be included in release notes.  Thank you for making that change.

Note: I discussed the scope of this prototype with @sherm1 and he is fine with deferring the bindings until later.  In general, a prototype is not intended to have all the features of a final product -- instead it has _some_ of the form, function, and fit that makes it intelligible to how it looks (form), works (functions) and is useful for the application at hand (fit).

From design-thinking: "A prototype is a simple experimental model of a proposed solution used to test or validate ideas, design assumptions and other aspects of its conceptualisation quickly and cheaply, so that the designer/s involved can make appropriate refinements or possible changes in direction."

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIim_4u3lDcdgSQsZwv:b-p54v9x)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`multibody/tree/geometry_spatial_inertia.cc` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgxU16CKdW6VfF_GJ1:-NIj3-yn-ZTNjmMDdAg3:b8t2f70) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/geometry_spatial_inertia.cc#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I feel that this change (and the further anticipated changes) should require a change to the documentation in `geometry_spatial_inertia.h`. That file should bear less responsibility for documenting the semantics of the return values and be more explicit about the fact that it's a vector to the `SpatialInertia` APIs, limiting redundancy of APIs.

I'm disinclined to accept a TODO on this one because it is very much an implication of extending this prototype to cover all of the `Shape` types and I'd like to see what that would look like.
</blockquote></details>

Sean -- I might need some clarification here.  I reread the documentation in geometry_spatial_inertia.h and it is still accurate.  It still calculates the quantities whether indirectly or directly.  

Once the prototype is propagated to the other shapes, it _might_ make sense to change the documentation. However, it would be helpful for you to provide some text since it seems the text is valid as is and I am unsure what you are trying to say.  As we discussed, the method is called ImplementGeometry() which is more general than just CalcSpatialInertia() -- even if that is all it does.
___
*[`multibody/tree/spatial_inertia.h` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgy2K9-BefVRg4ayIF:-NIj8I95-bV_SQmFEjzS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L127)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: TODOs should never be in the same block as doxygen-like things.
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.h` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgyKF51YRlZpUnS_M8:-NIj8HHF-PAQ4_CSeRhV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L135)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "principal x-axis" feels like a rather indirect way to say Bx. You've defined a frame B why ignore it now? 
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.h` line 139 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIeIPKQElKs39LrAfKl:-NIj8L-83F5Y3ParXbAz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.h#L139)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Self-blocking: Change Lx, Ly, Lz to lx, ly, lz.
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgye3i014prRCE5QoJ:-NIj8V8K7Gxoegg9oY34:btesnx1) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/spatial_inertia.cc#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This comment is unhelpful. That is *literally* what `p_BoBcm` means. If you *really* wanted to give a hint to the user you'd write something like,

> By definition Bcm is coincident with Bo.

Arguably, no comment is necessary at all.
</blockquote></details>

Done.  Removed.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgzA6j7akExd_CzaCJ:-NIj8j-U2GBrbaL87P_D:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/test/spatial_inertia_test.cc#L83)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit Incorrect horizontal whitespace.

In fact an application of clang-format changes this line and the previous for the better.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
You don't need to restate my own definition of prototype. You need to answer the questions. However, I'll restate the question in terms of your provided definition:

What ideas are you testing or validating? And how does this PR do that?

Obviously, you implicitly suggest that bindings have nothing to do with the idea/test. That's fine. But I can't infer what strategy this prototype serves. So, since I can't infer it, I'm asking you to spell it out for me. 

Despite the fact that I'm confused about what the strategy underlying this prototype is, the code is clear and (essentially) defect free, therefore it earns the stamp.  :LGTM:

> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIm6SCH007CLrusclXd:b-i7jp52)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 659 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm7H7R6rj5iB8BLOHn:-NIm7H7R6rj5iB8BLOHo:bilmdiy) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/parsing/test/detail_mujoco_parser_test.cc#L659)):*
> ```cpp
>   check_body_spatial(
>       "box_from_mesh_w_density",
>       SpatialInertia<double>(8.0, Vector3d::Zero(),
> ```

BTW Why not this one as well?
___
*[`multibody/tree/geometry_spatial_inertia.cc` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIgxU16CKdW6VfF_GJ1:-NIm7OLDAlQGbfS3kUS0:b-cms3rz) ([raw file](https://github.com/robotlocomotion/drake/blob/edea21efc5faa4f0ef77a0510c6a0ca4f152226f/multibody/tree/geometry_spatial_inertia.cc#L34)):*
It's not about *accuracy*. It's about what the user *should* understand about it and how it relates to the rest of Drake. When it was written it was the *only* APIs that would generate `SpatialInertia` from a description of geometry. As this pattern proceeds, that won't be the case. The primary goal is, as stated above:

> That file should ... be more explicit about the fact that it's a vector to the SpatialInertia APIs, limiting redundancy of APIs.

The flaw, as I see it is two-fold:

1. It makes accurate statements that are redundant of what is/will be documented in `SpatialInertia`. Why write that twice in two different ways?
2. The user should feel confident that this is just a different way to execute the `SpatialInertia` API. I like the idea of promising that they should produce equal inertias. In other words, the only reason to pick one API over the other is convenience based on how the data they currently have is represented (shape or independent measures)?

That said, I'm going to mark myself satisfied. If I'm alone in seeing this as a need, it isn't fair for me to attempt to turn you into a typist. If I care enough, I'll come in after the fact and propose the change in my own PR that others can review.
___
*[`multibody/tree/spatial_inertia.h` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm9ayrEOyfTmWzxkKV:-NIm9ays4fNn8t5bAnme:b-2d6vln) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/tree/spatial_inertia.h#L140)):*
> ```objc
>   /// @retval M_BBo_B, B's spatial inertia about Bo, expressed in B.
>   /// @throws std::exception if any of lx, ly, lz are negative.
>   // TODO(Mitiguy) Python-bind this function when related functions are done.
> ```

They also can't go between doxygen blocks and the code, because that messes up our doxygen scraping algorithms.

**Review by mitiguy — COMMENTED** [review]
PR #18407 prototypes the name, test, and utility of the newly proposed function.   

1. There were several candidate names including MakeSolidBox(), SolidBox(), SolidBoxViaDensity(), SolidBoxFromDensity() and the winning candidate SolidBoxWithDensity().

2. There were two candidate ways to test this function.  The test implemented in the final commit of PR #18407 is shorter and clearer than the initial test (which was correct but overly laborious).  

3. The utility of SolidBoxWithDensity() was investigated by replacing code in geometry_spatial_inertia.c with its shorter call to SolidBoxWithDensity().  Similarly, a few other call sites demonstrated that SolidBoxWithDensity() has utility in more than one part of Drake's C++ code.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIoBORt9ZND-fsX9WVR:b-kr1kn6)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 659 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm7H7R6rj5iB8BLOHn:-NIo0smN73AkMrYbi02n:b-ag0h0y) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/parsing/test/detail_mujoco_parser_test.cc#L659)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Why not this one as well?
</blockquote></details>

This call use uses UnitInertia::SolidCube() not UnitInertia::SolidBox().
This call site is a good candidate to be upgraded when SpatialInertia::SolidCubeWithDensity() exists.
___
*[`multibody/tree/spatial_inertia.h` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm9ayrEOyfTmWzxkKV:-NIo6Z2N3WlPBlVCG2JQ:bii7k6f) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/tree/spatial_inertia.h#L140)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

They also can't go between doxygen blocks and the code, because that messes up our doxygen scraping algorithms.
</blockquote></details>

That does not seem to jibe with what I see.
I issued the following command from the OS prompt:
bazel run   //doc/doxygen_cxx:build -- --serve --quick  drake.multibody.tree

I then looked at the generated Doxygen with @xuchenhan-tri (for reality check).
Here is what appeared on screen.




Regardless, I moved the comment to the top (before the first \\\) and it seemed to be OK there too.
Moving on ....

**Review by mitiguy — COMMENTED** [review]
Feature review +@sammy-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIoFR1H9y_C84YOb2V2:bq2y4h1)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm9ayrEOyfTmWzxkKV:-NIoKfZl7aehF3uMeN9_:bjvbbp3) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/tree/spatial_inertia.h#L140)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

That does not seem to jibe with what I see.
I issued the following command from the OS prompt:
bazel run   //doc/doxygen_cxx:build -- --serve --quick  drake.multibody.tree

I then looked at the generated Doxygen with @xuchenhan-tri (for reality check).
Here is what appeared on screen.




Regardless, I moved the comment to the top (before the first \\\) and it seemed to be OK there too.
Moving on ....
</blockquote></details>

I think "scraping" here refers to our processing of the documentation for Python. Doxygen for C++ doesn't get confused by comment placement.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm9ayrEOyfTmWzxkKV:-NIoM5My5PVu4phKSxsH:b-uv4ta) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/tree/spatial_inertia.h#L140)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think "scraping" here refers to our processing of the documentation for Python. Doxygen for C++ doesn't get confused by comment placement.
</blockquote></details>

Thanks for the clarification.

**Review by sherm1 — COMMENTED** [review]
That's _platform_ review @sammy-tri per Tuesday schedule (since Sean is Monday's but was feature reviewer)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIoNENX8SEtap5mJPUm:bprn58q)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by mitiguy — COMMENTED** [review]
Feature review -@sammy-tri 
Platform review +@sammy-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NIoNcYz0rjXUMRHL8u7:b-8t5hma)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 659 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NIm7H7R6rj5iB8BLOHn:-NIrr1dU2CfmkRTDLgEi:b-ivmjkf) ([raw file](https://github.com/robotlocomotion/drake/blob/df8c43ffe800797101e52b464e735ac9f86d36ab/multibody/parsing/test/detail_mujoco_parser_test.cc#L659)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

This call use uses UnitInertia::SolidCube() not UnitInertia::SolidBox().
This call site is a good candidate to be upgraded when SpatialInertia::SolidCubeWithDensity() exists.
</blockquote></details>

D'oh! Happily retracted.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 135 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NJBIele7fCcC1QG0991:-NJBIele7fCcC1QG0992:baa1p6o) ([raw file](https://github.com/robotlocomotion/drake/blob/8c4b108b2ad16c87c622ace2608031205888416f/multibody/tree/spatial_inertia.h#L135)):*
> ```objc
>   /// corresponds to a thin rod in the remaining non-zero length direction.
>   /// @param[in] density mass per volume (kg/m³). If one length is zero, density
>   /// is mass per area. If two lengths are zero, density is mass per length.
> ```

Is this comment correct?  AFAICT if any length is zero the result is massless and density is ignored.

(it's possible I'm missing a specific definition of term due to relative lack of subject matter expertise)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

___
*[`multibody/tree/spatial_inertia.h` line 135 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NJBIele7fCcC1QG0991:-NJBbabdA60eBPWolGyY:b-5m34pn) ([raw file](https://github.com/robotlocomotion/drake/blob/8c4b108b2ad16c87c622ace2608031205888416f/multibody/tree/spatial_inertia.h#L135)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

An interesting question. If you look at `UnitInertia` there are things like `ThinRod()` which is the abstract idea of a cylinder with a zero radius, but non-zero mass.

My first thought about this API is that it goes along with the `UnitInertia` APIs. These are abstractions that aren't *physical*, but may still be useful.

However, when you posed this question, a further thought came to mind. The limit of the mass as one of the measures goes to zero is *not* zero. That seems like some odd behavior. 

So, the question is: is the utility of being able to specify a zero-volume rectangle or line segment with non-zero mass sufficiently useful here to invite this degree of subtlety in the documentation and discussion? Perhaps `SolidBox` should legitimately refer to "solid boxes" and be done with it? If we need non-physical abstractions, they could stand on their own two feet?
</blockquote></details>

FWIW I would not try to combine SolidBox (a nice physical abstraction) with ThinPlate or ThinRod which are different (non physical but useful) abstractions.

**Review by mitiguy — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

___
*[`multibody/tree/spatial_inertia.h` line 135 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18407#-NJBIele7fCcC1QG0991:-NJC65T61_XXhdpB0sPT:b-22je67) ([raw file](https://github.com/robotlocomotion/drake/blob/8c4b108b2ad16c87c622ace2608031205888416f/multibody/tree/spatial_inertia.h#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FWIW I would not try to combine SolidBox (a nice physical abstraction) with ThinPlate or ThinRod which are different (non physical but useful) abstractions.
</blockquote></details>

@sammy-tri   Good catch.  My documentation was wrong.  Thank you for seeing it!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NJC7_Nl22TGEkBvtJrK:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
label +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18407#-:-NJCdHOEESJI0fAU_qtj:br1597u)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @mitiguy)

**Pull request merged**
