### PR TITLE
Polynomial evaluates a batch of indeterminates.

### LINKED ISSUE #16982: Support symbolic::Polynomial::Evaluate for a batch of data
Currently symbolic::Polynomial::Evaluate only evaluates a single symbolic::Environment. We should be able to evaluate the polynomial for a batch of data.

To do so, we will add two new functions
```cc
Eigen::VectorXd symbolic::Monomial::Evaluate(const Eigen::Ref<const VectorX<symbolic::Variable>>& x_vars, const Eigen::Ref<const MatrixXd> x_vals);
Eigen::VectorXd symbolic::Polynomial::Evaluate(const Eigen::Ref<const VectorX<symbolic::Variable>>& x_vars, const Eigen::Ref<const MatrixXd> x_vals);
```
where we evaluate the polynomial/monomial if variable `x_vars` takes the value `x_vals.col(i)`

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #16982

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065#-:-N0lb1v6CH_XViqk_iZY:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm: after fixing a typo

+@xuchenhan-tri for platform review please, thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065#-:-N14dlIm9E778IBJPcXE:b-2sqx9k)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai and @xuchenhan-tri)

___
*[`common/symbolic_polynomial.h` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17065#-N14Mu_c9ycO1duKN2C0:-N14Mu_c9ycO1duKN2C1:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/11ea1ba7eb39fe03e2243ef8d0877e633b057572/common/symbolic_polynomial.h#L204)):*
> ```objc
>   /// @param[in] indeterminates Must include all this->indeterminates()
>   /// @param[in] indeterminates_values Each column of `indeterminates_values`
>   /// store one specific values of `indeterminates`.
> ```

typo



_Code quote:_
```objc
store one specific values of
```

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 
+(release notes: yes) 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065#-:-N152Na49vWdr92I8BWG:bkdjaaz)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.h` line 209 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17065#-N151IGd72PQTxKbxIeT:-N151IGd72PQTxKbxIeU:br49ch) ([raw file](https://github.com/robotlocomotion/drake/blob/11ea1ba7eb39fe03e2243ef8d0877e633b057572/common/symbolic_polynomial.h#L209)):*
> ```objc
>   /// substituting indeterminates(i) in this polynomial with
>   /// indeterminates_values(i, j) for all i.
>   /// @note This function only works when all coefficients in this polynomial
> ```

nit, doxygen renders the text like this (probably not what you want?)

___
*[`common/test/symbolic_polynomial_test.cc` line 968 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17065#-N151vgYCfgjsGMdnuhM:-N151vgYCfgjsGMdnuhN:b-mpy61l) ([raw file](https://github.com/robotlocomotion/drake/blob/11ea1ba7eb39fe03e2243ef8d0877e633b057572/common/test/symbolic_polynomial_test.cc#L968)):*
> ```cpp
>   Eigen::VectorXd polynomial_values =
>       p.EvaluateIndeterminates(indeterminates, indeterminates_values);
>   EXPECT_EQ(polynomial_values.rows(), indeterminates_values.cols());
> ```

nit, this should be an ASSERT_EQ to prevent going out of bound below.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,xuchenhan-tri(platform) (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.h` line 209 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17065#-N151IGd72PQTxKbxIeT:-N158CUu91CPRQDnbp55:b-7qxogv) ([raw file](https://github.com/robotlocomotion/drake/blob/11ea1ba7eb39fe03e2243ef8d0877e633b057572/common/symbolic_polynomial.h#L209)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, doxygen renders the text like this (probably not what you want?)


</blockquote></details>

Done. Thanks! Now it looks like this

___
*[`common/test/symbolic_polynomial_test.cc` line 968 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17065#-N151vgYCfgjsGMdnuhM:-N158aQI2TtgQAd5FsKf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11ea1ba7eb39fe03e2243ef8d0877e633b057572/common/test/symbolic_polynomial_test.cc#L968)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this should be an ASSERT_EQ to prevent going out of bound below.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17065)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,xuchenhan-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
