### PR TITLE
[framework] Improve system graphviz output

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20203.

---

Using the command line from #20198, we can see the change in output.

Before this PR:

image

After this PR:

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NedZrdc80s8dx5RkQ3G:-NedZrdc80s8dx5RkQ3H:b8zhp51) (no related file):*
Working

Add python bindings & unit tests of custom leaf system override.

___
___
*[`systems/framework/test/diagram_test.cc` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nee4e7X-c6kkRpob8es:-Nee4e7X-c6kkRpob8et:b-jtapq9) ([raw file](https://github.com/RobotLocomotion/drake/blob/b07b8d2d84f9a8dbff0359b868f7166e9a43f7fc/systems/framework/test/diagram_test.cc#L1)):*
> ```cpp
> #include "drake/systems/framework/diagram.h"
> ```

Working

Missing unit tests for options substring propagation.
___
*[`systems/framework/test/leaf_system_test.cc` line 2409 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeeDsiyD4096z9yjwMD:-NeeDsiyD4096z9yjwME:bue95mz) ([raw file](https://github.com/RobotLocomotion/drake/blob/c48eb515d4fa020b477ead7b983d585bf9695b67/systems/framework/test/leaf_system_test.cc#L2409)):*
> ```cpp
>   EXPECT_THAT(dot, ::testing::HasSubstr("PORT=\"y0\""));
> }
> ```

Working

Missing unit test for `split=1`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NedZrdc80s8dx5RkQ3G:-NefIPKO5fPJn-e9cnn_:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Add python bindings & unit tests of custom leaf system override.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NefIXvU6AcIbUFjDOHJ:-NefIXvU6AcIbUFjDOHK:b-orj1ma) (no related file):*
Working 

Test rendering with Focal graphviz.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NefIXvU6AcIbUFjDOHJ:-NefLPD769QgHS6ztNs9:b-vs1pr4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working 

Test rendering with Focal graphviz.
</blockquote></details>

Looks good.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-:-NehVjd576a-EKBaeaDJ:b-gpqagm)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
FYI See #20203 for a examples of customizing the Graphviz output using this new API.  It's overview has a picture of the result, and the commits on that branch have some curated changes.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. Mostly a bunch of small typos and the like.

:LGTM:

> Reviewed 6 of 10 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-:-NehnsAf5W7W5dibeEuD:bp67kd5)* status: 17 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/framework/diagram.h` line 238 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NehpOb39uBDMoGWY4jr:-NehpOb39uBDMoGWY4js:bo454b8) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/diagram.h#L238)):*
> ```objc
>   DRAKE_DEPRECATED(
>       "2024-01-01",
>       "Instead of calling or overriding this function, either "
> ```

nit This boilerplate message (about overriding) seems inappropriate for a function marked `final`.  (Same for the other comments in this file.)
___
*[`systems/framework/diagram.cc` line 513 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NehsCr0528fbcyq1Kp8:-NehsCr0528fbcyq1Kp9:bs97h44) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/diagram.cc#L513)):*
> ```cpp
>                         const std::string& kind /* "input" or "output" */,
>                         const std::string& ports_node_id,
>                         const std::string& color,
> ```

BTW I'm not seeing that the color on the port box or the directly connected edges provides much information value.

That said, if I presuppose value based on its presence, I would guess the value is that for subsystems that get laid out a fair distance from the parent Diagram's port block, you can still see that that subsystem's port directly connects to the Diagram's port without having to follow the arrow. Is that the point? That's certainly not *valueless* and it's certainly harmless. 

Ultimately, I don't have enough experience trying to answer questions from these graphs to feel the pain points on which questions are a pain to answer. So, I'll happily defer to you.
___
*[`systems/framework/leaf_system.h` line 163 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nehu4jJ0AmMVBHGAO67:-Nehu4jJ0AmMVBHGAO68:b-xjuehu) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/leaf_system.h#L163)):*
> ```objc
>   DRAKE_DEPRECATED(
>       "2024-01-01",
>       "Instead of calling or overriding this function, either "
> ```

BTW Same issue in this file as in `diagram.h`: references to "overriding" `final` methods.
___
*[`systems/framework/system.cc` line 957 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NehvSbs1Hnc51QZpoNY:-NehvSbtEUR8T5_aRQs5:b-tb3bd3) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system.cc#L957)):*
> ```cpp
>   static const logging::Warn log_once(
>       "The member functions "
>       "System<T>::GetGraphvizFragment(), ",
> ```

nit: erratic commas?
___
*[`systems/framework/system_base.h` line 122 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei5iWP2ABMmHHlfbU_:-Nei5iWP2ABMmHHlfbUa:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L122)):*
> ```objc
>   Notes about the display conventions:
> 
>   - The nodes the graph are systems, and the solid edges are connections between
> ```

nit: grammar



_Suggestion:_
```objc
nodes of the graph are
```
___
*[`systems/framework/system_base.h` line 153 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei6IZG5Kqjgr7okV2a:-Nei6IZG5Kqjgr7okV2b:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L153)):*
> ```objc
>   @param options Arbitrary strings to request alterations to the output. Options
>   that are unknown will be silently skipped. These options are often bespoke
>   flags that are only understood by particular systems, but Drake has a one
> ```

nit: typo



_Suggestion:_
```objc
but Drake has one
```
___
*[`systems/framework/system_base.h` line 154 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei78NODd3lUJ2Nwnk7:-Nei6Uf_-geEJFwzsPAM:b25rxkt) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L154)):*
> ```objc
>   that are unknown will be silently skipped. These options are often bespoke
>   flags that are only understood by particular systems, but Drake has a one
>   built-in flag that is generally applicable: `"split"`. When set to `"1"`, the
> ```

BTW I worry slightly that a string representation of a number might lead to confusion down the road. Particularly with dynamically typed languages. In C++ you'll at least get in trouble if you try to set it with an int. Could there be a reasonably compact alternative that is, nevertheless, unambiguously a string value?
___
*[`systems/framework/system_base.h` line 155 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei7FJoDg11CpIaeiSh:-Nei7FJoDg11CpIaeiSi:bgnpqib) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L155)):*
> ```objc
>   flags that are only understood by particular systems, but Drake has a one
>   built-in flag that is generally applicable: `"split"`. When set to `"1"`, the
>   system will be added as two nodes with all input on one node and all output on
> ```

nit: Grammar

While one can argue that "input" and "output" are technically correct, generally, given the way Drake uses the terms "input" and "output", they are typically enumerable objects (e.g., ducks) and not continuous quantities (e.g. grass).



_Suggestion:_
```objc
all inputs on one node and all outputs on
```
___
*[`systems/framework/system_base.h` line 1270 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei8vme6_78fIwjYlz-:-Nei8vme6_78fIwjYlz0:b-r13cvu) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L1270)):*
> ```objc
>   internal::SystemId get_system_id() const { return system_id_; }
> 
>   /** The arguments to DoGetGraphvizFragment(). These parameters contitute a
> ```

nit s/contitute/constitute
___
*[`systems/framework/system_base.h` line 1271 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei94UF5irB2N0MT_uM:-Nei94UF5irB2N0MT_uN:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L1271)):*
> ```objc
> 
>   /** The arguments to DoGetGraphvizFragment(). These parameters contitute a
>   polite request; a user's %System's implementation DoGetGraphvizFragment() is
> ```

nit: typo



_Suggestion:_
```objc
implementation of DoGetGraphvizFragment()
```
___
*[`systems/framework/system_base.h` line 1273 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei99To0P0EM2gtrE85:-Nei99To0P0EM2gtrE86:b-6h5ax2) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L1273)):*
> ```objc
>   polite request; a user's %System's implementation DoGetGraphvizFragment() is
>   not strictly required to honor any of these parameters, but generally should
>   attempt to honor as much as possible. */
> ```

BTW grammar awkwardness. 

We've got two phrases: "honor any of these parameters" and "honor as much as possible". If "these parameters" is supposed to be the common object, then the second would be "as __*many*__ as possible". "as much" moves the object of the verb *from* the properties and to an adverbial phrase describing the code's effort.
___
*[`systems/framework/system_base.h` line 1347 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiDgM892iFNme9exPr:-NeiDgM892iFNme9exPs:b-cm9mll) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L1347)):*
> ```objc
>   // Returns the names of all input (or output) ports, styled for Graphviz using
>   // its subset of HTML. For example, this handles the markup for deprecated or
>   // size-0 ports as documented in GetGraphvizString().
> ```

BTW Should this function be making the promise that the ith string goes with the ith port? Ultimately, the ordering promised in the public API is born here.
___
*[`systems/framework/system_base.cc` line 114 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiEqYeDZD-tdJau1HN:-NeiEqYeDZD-tdJau1HO:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.cc#L114)):*
> ```cpp
> 
>   // Prepare a table of port labels. Input ports are on the left (col 0), and
>   // output ports are on the right (col 1). A nullopt labels indicates that the
> ```

nit: typo



_Suggestion:_
```cpp
label
```
___
*[`systems/framework/system_base.cc` line 167 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiG60WExr13ngXxOIT:-NeiG60WExr13ngXxOIU:b-hrry7a) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.cc#L167)):*
> ```cpp
>         (split_in_twain && node == 0)   ? params.node_id + "in"
>         : (split_in_twain && node == 1) ? params.node_id + "out"
>                                         : params.node_id;
> ```

BTW You have these values defined already: `node_id_input` and `node_id_output`. Probably nothing wrong with spelling it out here so that the subtle logic of what `node_id_input`'s value actually is doesn't matter. But the second concatenation of "in"/"out" jumped out at me.



_Suggestion:_
```cpp
    const std::string& node_id =
        node == 0 ? node_id_input : node_id_output;
```
___
*[`systems/framework/test/leaf_system_test.cc` line 2374 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiU2dw-zDQpGpPDGQV:-NeiU2dw-zDQpGpPDGQW:b-ps6lsd) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2374)):*
> ```cpp
>   void GetGraphvizFragment(int max_depth, std::stringstream* dot) const final {
>     DRAKE_THROW_UNLESS(max_depth >= 0);
>     *dot << "// The first ten million years were the worst,\n"
> ```

Bwa, ha, ha, ha!
___
*[`systems/framework/test/leaf_system_test.cc` line 2417 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiVCnSEbTSKL1J2Cy2:-NeiVCnSEbTSKL1J2Cy3:b-n29524) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2417)):*
> ```cpp
>   // By default, the graph does not use "split" mode.
>   std::string dot = system.GetGraphvizString();
>   EXPECT_THAT(dot, ::testing::Not(::testing::HasSubstr("(split)")));
> ```

BTW Are you testing for the string "split" with a capture? Are testing for the string "(split)"? I think you need to escape the `(` and `)`.
___
*[`systems/framework/test/leaf_system_test.cc` line 2423 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiUmDg1phetlc75pxD:-NeiUmDh-qeXCUI4uBOT:b104s2r) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2423)):*
> ```cpp
>   options.emplace("split", "1");
>   dot = system.GetGraphvizString({}, options);
>   EXPECT_THAT(dot, ::testing::HasSubstr("(split)"));
> ```

BTW  When I saw this, I kind of hoped we were looking for *two* "(split)"s. But there's no matcher for counting instances of a substring and my quick and dirty modification failed (and I wasn't overly interested in following it up).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/framework/diagram.cc` line 513 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NehsCr0528fbcyq1Kp8:-Neiqytn57C97p_jRnVQ:b-lfeu6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/diagram.cc#L513)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm not seeing that the color on the port box or the directly connected edges provides much information value.

That said, if I presuppose value based on its presence, I would guess the value is that for subsystems that get laid out a fair distance from the parent Diagram's port block, you can still see that that subsystem's port directly connects to the Diagram's port without having to follow the arrow. Is that the point? That's certainly not *valueless* and it's certainly harmless. 

Ultimately, I don't have enough experience trying to answer questions from these graphs to feel the pain points on which questions are a pain to answer. So, I'll happily defer to you.
</blockquote></details>

My main motivation was only "that's how we've always done it, and it doesn't seem obviously wrong".
___
*[`systems/framework/system_base.h` line 154 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-Nei78NODd3lUJ2Nwnk7:-NeivXQO61Io-R8rJZZG:b-71zw8y) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/system_base.h#L154)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I worry slightly that a string representation of a number might lead to confusion down the road. Particularly with dynamically typed languages. In C++ you'll at least get in trouble if you try to set it with an int. Could there be a reasonably compact alternative that is, nevertheless, unambiguously a string value?
</blockquote></details>

In pydrake, if I did `params.options |= {"split": 1}` it _did_ fail-fast with a plausible error message (wanted str, got int) but it wasn't a _great_ error message.  So, I've changed it to an string, as suggested.
___
*[`systems/framework/test/leaf_system_test.cc` line 2417 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiVCnSEbTSKL1J2Cy2:-Neitjw3DoMCJ72IV9wR:b-8t57ab) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2417)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Are you testing for the string "split" with a capture? Are testing for the string "(split)"? I think you need to escape the `(` and `)`.
</blockquote></details>

This is `HasSubstr` not `MatchesRegex` -- I don't think `()` forms a grouping?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/framework/diagram.h` line 245 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NejNv-KBIVcQGMAM_Lw:-NejNv-KBIVcQGMAM_Lx:b-yp6475) ([raw file](https://github.com/RobotLocomotion/drake/blob/81e43aa1cdc244ca7d451af23b5407ebd0d3d017/systems/framework/diagram.h#L245)):*
> ```objc
>   DRAKE_DEPRECATED(
>       "2024-01-01",
>       "Instead of calling this function, call GetGraphvizFragment()")
> ```

nit: Inconsistent final punctuation. Of the four similar deprecation messages (spread over two files), only the one above this one has a final period.
___
*[`systems/framework/diagram.cc` line 513 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NehsCr0528fbcyq1Kp8:-NejNzH_2GPvGEPDaEhO:brcbpte) ([raw file](https://github.com/RobotLocomotion/drake/blob/cab56cbbf7197e2635d5a14db30925d9e523e4e6/systems/framework/diagram.cc#L513)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My main motivation was only "that's how we've always done it, and it doesn't seem obviously wrong".
</blockquote></details>

Oops. I'd glossed over that. Sounds good to me.
___
*[`systems/framework/test/leaf_system_test.cc` line 2417 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiVCnSEbTSKL1J2Cy2:-NejOXps0eZOu7DOY8rc:b-na42zr) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2417)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is `HasSubstr` not `MatchesRegex` -- I don't think `()` forms a grouping?
</blockquote></details>

I tested it with the '(' escaped (i.e., '\\(') and it still passed. If it were already escaping them I'd expect that it *wouldn't* pass. But I'm marking myself as satisfied. The distinction is slight.
___
*[`bindings/pydrake/systems/test/custom_test.py` line 86 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NejP3fLDdOc2OjSmnlr:-NejP3fLDdOc2OjSmnls:b-g0lnb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/81e43aa1cdc244ca7d451af23b5407ebd0d3d017/bindings/pydrake/systems/test/custom_test.py#L86)):*
> ```Python
>         # getter returns a _copy_ of the lines, not a _reference_.
>         params.header_lines += ["hello=world"]
>         params.options |= {"split": "I/O"}
> ```

BTW Apparently, python 3.8 doesn't want you doing this.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review (tomorrow) per schedule, please.

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-:-NejRFqO-JVJWgqm4rcC:bml47ue)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/framework/diagram.h` line 245 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NejNv-KBIVcQGMAM_Lw:-NejPLXS8vdQk8w0S2yZ:b289x4l) ([raw file](https://github.com/RobotLocomotion/drake/blob/81e43aa1cdc244ca7d451af23b5407ebd0d3d017/systems/framework/diagram.h#L245)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Inconsistent final punctuation. Of the four similar deprecation messages (spread over two files), only the one above this one has a final period.
</blockquote></details>

I don't think trailing punctuation inconsistency in deprecation messages warrants an investment of time from anyone on the team.
___
*[`systems/framework/test/leaf_system_test.cc` line 2417 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NeiVCnSEbTSKL1J2Cy2:-NejPWlC2JjKnV-9Ot9p:bnmglx) ([raw file](https://github.com/RobotLocomotion/drake/blob/2b06678c9525c522d9ec8fae5e695535940c467a/systems/framework/test/leaf_system_test.cc#L2417)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I tested it with the '(' escaped (i.e., '\\(') and it still passed. If it were already escaping them I'd expect that it *wouldn't* pass. But I'm marking myself as satisfied. The distinction is slight.
</blockquote></details>

As I understand it, a single backslash would escape the character of C string (a no-op, since it's not special anyway), not pass a backslash to gmock.
___
*[`bindings/pydrake/systems/test/custom_test.py` line 86 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NejP3fLDdOc2OjSmnlr:-NejQjjtA6uMfWm3613i:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/81e43aa1cdc244ca7d451af23b5407ebd0d3d017/bindings/pydrake/systems/test/custom_test.py#L86)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Apparently, python 3.8 doesn't want you doing this.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/framework/diagram.h` line 245 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NejNv-KBIVcQGMAM_Lw:-NejcufVEAqRB_EomzTd:b61ejxw) ([raw file](https://github.com/RobotLocomotion/drake/blob/81e43aa1cdc244ca7d451af23b5407ebd0d3d017/systems/framework/diagram.h#L245)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think trailing punctuation inconsistency in deprecation messages warrants an investment of time from anyone on the team.
</blockquote></details>

Yeah. I figured as much.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 10 files at r2, 1 of 2 files at r3, 2 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-:-Nenvbmf8x1OcfLHAPFG:bcpz082)* status: 2 unresolved discussions

___
*[`systems/framework/diagram.cc` line 514 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NenjQWs7ahQ41s8ejHS:-NenjQWs7ahQ41s8ejHT:bb7lc4s) ([raw file](https://github.com/RobotLocomotion/drake/blob/1110f50b6bb6c1dce09785f6237b2b7e5db74650/systems/framework/diagram.cc#L514)):*
> ```cpp
>                         const std::string& ports_node_id,
>                         const std::string& color,
>                         const std::vector<std::string> labels) {
> ```

nit 



_Suggestion:_
```cpp
const std::vector<std::string>& labels) {
```
___
*[`systems/framework/system_base.cc` line 234 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NenvVyI21i5Uk4DSzg4:-NenvVyI21i5Uk4DSzg5:b-um1u8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/1110f50b6bb6c1dce09785f6237b2b7e5db74650/systems/framework/system_base.cc#L234)):*
> ```cpp
>     if (port.get_data_type() == PortDataType::kVectorValued &&
>         port.size() == 0) {
>       label = fmt::format(R"""(<FONT COLOR="grey">{}</FONT>)""", label);
> ```

nit kcov suggests that this isn't covered by the tests.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`systems/framework/system_base.cc` line 234 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20204#-NenvVyI21i5Uk4DSzg4:-Neo6oL-1kiphwOKp63R:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/1110f50b6bb6c1dce09785f6237b2b7e5db74650/systems/framework/system_base.cc#L234)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit kcov suggests that this isn't covered by the tests.
</blockquote></details>

Done

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20204)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
