### PR TITLE
pydrake cpp_template: Add decorator for ease of defining instantiations

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards defining user classes with scalar type conversion, etc, in parallel with #8665.

\cc @gizatt @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@avalenzu for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAs97sD6i5lrWl3ZVJ7:bfuj1er)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAsCW3iEiCKxH1bzTKH:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/util/cpp_template.py, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAsO4im4aNywJGYG44H:-LAsooRaBHjcLk8NNzgZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c11cff47e25dc20bd6e3e760627f38b7868d7a0/bindings/pydrake/util/cpp_template.py#L160)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I don't know if this is an issue here or on `add_instantiations`, but it's not clear to me how `param_list` is used.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/cpp_template.py, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAsR40P4cnzKsGZ2FKI:-LAsopUT8_lzmqgRGgLV:b7sxs78) ([raw file](https://github.com/robotlocomotion/drake/blob/3c11cff47e25dc20bd6e3e760627f38b7868d7a0/bindings/pydrake/util/cpp_template.py#L161)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Is it worth explaining that there's a convention that the name of the decorated function should be the `name` argument to the `define` decorator?  Or would that be super obvious to someone familiar with this code?  (or is that not actually a convention at all?)
</blockquote></details>

Done. Tried to clarify, sorry about that!

---

*[bindings/pydrake/util/test/cpp_template_test.py, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAsRLQ72NS8FBYab1_q:-LAsosw92aD9HO6SxTHM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c11cff47e25dc20bd6e3e760627f38b7868d7a0/bindings/pydrake/util/test/cpp_template_test.py#L113)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems confusing to me to use `MyClass` as the name of both the inner class being returned by the decorated function and as the name of a variable here which refers to an instance of...   I guess I'd call it an instance of `MyTemplate`?  though that's just the name of a generator function...  which is named to be like a class because it's kinda like a class in `C++` which takes template arguments?  My mind is a little bent, I feel like a python newb.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/cpp_template.py, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAsR40P4cnzKsGZ2FKI:-LAsute138iIalKTHYFo:b-4yaw22) ([raw file](https://github.com/robotlocomotion/drake/blob/3c11cff47e25dc20bd6e3e760627f38b7868d7a0/bindings/pydrake/util/cpp_template.py#L161)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Tried to clarify, sorry about that!
</blockquote></details>

*way* clearer now.   Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAsv0_D6PfU7DJV5qkh:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
(Another alternative is to defer evaluation of instantiations using a queue until requested, which shouldn't be too hard.)

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAt34tw0Y_8uJVbEB1e:bkyv78j)*

**Comment by sammy-tri** [comment]
I think I'm fine with this implementation if you are.

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[bindings/pydrake/util/cpp_template.py, line 182 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAtCfhy0fSZGc2nHMpj:-LAtCfhy0fSZGc2nHMpk:b-o2m4uc) ([raw file](https://github.com/robotlocomotion/drake/blob/1ac95e41b64022fc88d4fd4172ae71b8a95f56b7/bindings/pydrake/util/cpp_template.py#L182)):*
> ```Python
>         Example:
>         @TemplateClass.define("MyTemplate", param_list=[(int,), (float,)])
>         def MyTemplate(param):
> ```

BTW I think this needs to be updated to match the change to `add_instantiations`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAtCsY76WnpNvpQVn3v:b-y0qbvh)*

**Comment by EricCousineau-TRI** [comment]
OK Sounds good!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/cpp_template.py, line 182 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8666#-LAtCfhy0fSZGc2nHMpj:-LAtPrDP4pb1x4t5wS3i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1ac95e41b64022fc88d4fd4172ae71b8a95f56b7/bindings/pydrake/util/cpp_template.py#L182)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I think this needs to be updated to match the change to `add_instantiations`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666#-:-LAtPt5aBDpzgHIT2iUm:b56uezr)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8666)*

**Pull request merged**
