### PR TITLE
Cleanup LCM Message Definitions

### PR DESCRIPTION
**Pull request by liangfok**
1. Fixed grammar.
2. Added documentation.
3. Fixed spacing per style guide. (Includes replacing tabs with spaces.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3464)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this touches `automotive/lcm_vector_gen.py`. +@jwnimmer-tri for feature review. 

@jwnimmer-tri , is this PR big enough to warrant a separate feature reviewer?

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRj8MLqSdqdmub3Y-wg:brb342c)*

**Comment by jwnimmer-tri** [comment]
We should probably find a second reviewer who knows what LCM files are supposed to look like.

**Comment by liangfok** [comment]
+@russtedrake for feature review please.

I checked git history and it only goes back to a commit you made back in August 2015, so I assume you were one of the original authors of these LCM message definitions.

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRj9y7-Dwcj4TZg-Xb-:bex0178)*

**Comment by david-german-tri** [comment]
> I checked git history and it only goes back to a commit you made back in August 2015

Do you mean https://github.com/liangfok/drake/commit/9a67372fa00054aedf8a9f30684bdd5dc2ee9b0d, "moved all current files into drake subdirectory"?

**Comment by jwnimmer-tri** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/lcmtypes/lcmt_qp_controller_input.lcm, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjBrGEJGmnSVwp_P6C:-KRjBrGF0khmp1dQPpkJ:bhtaa7w) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_qp_controller_input.lcm#L7)):*
> ```
>   int64_t timestamp;
> 
>   boolean be_silent;
> ```

Doesn't reordering the fields break compatibility between old and new builds of different tools?  I'm hesitant do to that in a cleanup PR.

---

*[drake/lcmtypes/lcmt_robot_state.lcm, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjCIDdbfLiSFkgXusk:-KRjCIDdbfLiSFkgXusl:b-spm0re) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_robot_state.lcm#L13)):*
> ```
> 
>   // The following variable defines which model instance
>   // [0, num_model_instances) each joint is associated with.
> ```

This doesn't define what `num_model_instances` means.  Why wasn't `num_robots` better, since is the name of a field in this message?

---

*[drake/lcmtypes/lcmt_scope_data.lcm, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjDBrjaom1b8JI_jNV:-KRjDBrjaom1b8JI_jNW:bdp287x) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_scope_data.lcm#L9)):*
> ```
>   int64_t scope_id;
> 
>   // Specifies the length of the history to use for this trace.
> ```

FYI I think the noun phrases were fine, and extra verb is a distraction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464)*

**Comment by liangfok** [comment]
@david-german-tri: Yes!! Can we look up history past 9a67372fa00054aedf8a9f30684bdd5dc2ee9b0d?

**Comment by david-german-tri** [comment]
It's not terribly convenient, but you can browse Drake at the preceding commit: https://github.com/RobotLocomotion/drake/tree/d3ff393f9639135c6d421a311e789773fdc74701

**Comment by liangfok** [comment]
@david-german-tri Thanks!
@jwnimmer-tri I addressed your comments. PTAL.

---

Review status: 28 of 32 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/lcmtypes/lcmt_qp_controller_input.lcm, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjBrGEJGmnSVwp_P6C:-KRkWsYw7Wl04TR7mMs_:b2yemny) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_qp_controller_input.lcm#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Doesn't reordering the fields break compatibility between old and new builds of different tools?  I'm hesitant do to that in a cleanup PR.
</details>
Good point. I'd defect a tool that is sensitive to the ordering but, in an abundance of caution, I've reverted the ordering change.

---

*[drake/lcmtypes/lcmt_robot_state.lcm, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjCIDdbfLiSFkgXusk:-KRkXWWajPowWzU83Oli:brjtibh) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_robot_state.lcm#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This doesn't define what `num_model_instances` means.  Why wasn't `num_robots` better, since is the name of a field in this message?
</details>
The term "model instance" is the term we're using in `RigidBodyTree` to express the fact that multiple model instances may exist in a single tree.  See, for example, the following method that returns the number of model instances in the tree:

http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html#aebeff7c0bac25b7bfdb28c21fb3faf9d

I've reverted the comment change and will include it in a future PR that changes the field names to use "model" instead of joint".

---

*[drake/lcmtypes/lcmt_scope_data.lcm, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjDBrjaom1b8JI_jNV:-KRkZ6eRpCUQfqb9yCq7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_scope_data.lcm#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI I think the noun phrases were fine, and extra verb is a distraction.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRkZ8W708ONpHG20fur:bsaf5lj)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcmtypes/lcmt_drake_signal.lcm, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRkdYLu2CKw8tBEiB7I:-KRkdYLvovKMIAsUjTnp:b22rvcc) ([raw file](https://github.com/robotlocomotion/drake/blob/88330d3e4f43acd84fe0f63a3b3983a3d111229a/drake/lcmtypes/lcmt_drake_signal.lcm#L10)):*
> ```
>   int32_t dim;
> 
>   // The value of element in the signal.
> ```

BTW "value of _each_ element" to match the below?

---

*[drake/lcmtypes/lcmt_robot_state.lcm, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjCIDdbfLiSFkgXusk:-KRkbyzZqDW9I30gDKwV:b-pl7x8y) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_robot_state.lcm#L13)):*
The fix is fine.

I was aware of the other use.  But someone reading these message comments might not be.  The defect was that the term appeared out of thin air, with no citation.

> ... changes the field names to use "model" instead of joint".

I would first advise finding how such a rename might affect users of drake.  There don't appear to be any uses within drake anyway, which suggests that this message is perhaps not tied to how RBT names its ideas, so doesn't need to match the terminology?  In other words: consider leaving well enough alone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRke80ApbaxyKHiWYDf:bnfp4nl)*

**Comment by liangfok** [comment]
I addressed all reviewer comments.

I'm going to do an ultra-deep dive into git history to find out who the original authors are of these messages.

---

Review status: 31 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/lcmt_drake_signal.lcm, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRkdYLu2CKw8tBEiB7I:-KRkgv8YIr7F4Jm6A4ip:b-d5q2ho) ([raw file](https://github.com/robotlocomotion/drake/blob/88330d3e4f43acd84fe0f63a3b3983a3d111229a/drake/lcmtypes/lcmt_drake_signal.lcm#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW "value of _each_ element" to match the below?
</details>
Fixed. Thanks.

---

*[drake/lcmtypes/lcmt_robot_state.lcm, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-KRjCIDdbfLiSFkgXusk:-KRkggb_iiaYArIc6tiR:brqpva8) ([raw file](https://github.com/robotlocomotion/drake/blob/bd810c48d8df18aadf1819345a8d2b6bd830d423/drake/lcmtypes/lcmt_robot_state.lcm#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The fix is fine.
> 
> I was aware of the other use.  But someone reading these message comments might not be.  The defect was that the term appeared out of thin air, with no citation.
> 
> > ... changes the field names to use "model" instead of joint".
> 
> I would first advise finding how such a rename might affect users of drake.  There don't appear to be any uses within drake anyway, which suggests that this message is perhaps not tied to how RBT names its ideas, so doesn't need to match the terminology?  In other words: consider leaving well enough alone.
</details>
OK STGM. It's definitely a low priority TODO item.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRkhIiWeAu5GjRD3-tN:b-arjeuq)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464)*

**Comment by liangfok** [comment]
I believe `lcmt_drake_signal.lcm` was first committed by @russtedrake in d212b8948a812629ba138d9261a37538e35c9bf2 because the file does not exist in  517551ded44d44701c0939fd4842209cb67a8ba8, which is the version that immediatley precedes it. I will thus leave the current review assignments for this PR unchanged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRkmaeA4Gb6pkQq2D6m:bx9v00t)*

**Comment by RussTedrake** [comment]
:lgtm: based on my quire inspection.  specifically, i was trying to make sure that you did not change the actual variable names (only the comments and formatting) for the types which have dependencies outside of drake.  i hope that this is true and that everyone understands that those are only changed at potentially great cost.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRm5FY3JH-hkdWNaHFw:b-cdl2jt)*

**Comment by liangfok** [comment]
Thanks. I am curious: does the order of the fields inside a message matter? There are a few messages like Drake Signal where the timestamp is not first. It might be nice to make it first for consistency.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3464#-:-KRmRuECWyy5-wvTM9aD:b-z9s6o1)*

**Comment by RussTedrake** [comment]
the order of the fields should not matter.

**Comment by jwnimmer-tri** [comment]
LCM encodes messages in field-declaration order.  If we change the field order in the message, folks will have to be sure to recompile all code that uses the message, and any binary recordings of the message will no longer load correctly.

**Pull request merged**
