### PR TITLE
[geometry] Factor MaybePauseForUser to test_utilities/

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19971)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-:-NbR-Z4wEcYxWotydCs8:b-85g6de)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-NbQzmHo6IIshkm0PDSG:-NbQzmHp8IHA86ZIenyn:ba7dkye) (no related file):*
Could I counter-propose placing this into `common/test_utilities`?  I don't think anything here is meshcat-specific per se.

___
___
*[`geometry/test_utilities/maybe_pause_for_user.h` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-NbQzskSDZIW7bYgwtIz:-NbQzskSDZIW7bYgwtJ-:bvrj25v) ([raw file](https://github.com/RobotLocomotion/drake/blob/d5f3bbfe05932212ac3e248f05a3bd86c0e4520e/geometry/test_utilities/maybe_pause_for_user.h#L13)):*
> ```objc
>  as a bazel test, but when running as a command-line executable, it will enable
>  users to see the visualization outputs. */
> void MaybePauseForUser() {
> ```

nit Since `<iostream>` is [Satan](https://github.com/RobotLocomotion/drake/blob/d8de89ffea3517441371767da313e8849d2c26e0/tools/lint/drakelint.py#L128), we should use a separate `*.cc` file here to avoid spamming our tests' translation units with it.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19971)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-NbQzmHo6IIshkm0PDSG:-NbR66uv0wXvNjxin8pu:b3pom78) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Could I counter-propose placing this into `common/test_utilities`?  I don't think anything here is meshcat-specific per se.
</blockquote></details>

Could do. I was trying to be conservative about demoting stuff beyond its immediate use/reach.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19971)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-NbQzmHo6IIshkm0PDSG:-NbRApSp-4mAOnQrbZHz:b7xksqh) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Could do. I was trying to be conservative about demoting stuff beyond its immediate use/reach.
</blockquote></details>

Thinking more, I would also buy it in `visualization/test_utilities` as another valid alternative, though I still prefer `common/test_utilities` myself.

Remember that `MeshcatVisualizer` and `DrakeVisualizer` and etc will no longer be part of `geometry` soon (#19786).

___
___
*[`common/test_utilities/maybe_pause_for_user.h` line 6 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19971#-NbRBUZa3ETtTpFeTS2_:-NbRBUZa3ETtTpFeTS2a:b-2wyxei) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc28ccafdb6d46e51e7789b44cc8d1548f8f46e/common/test_utilities/maybe_pause_for_user.h#L6)):*
> ```objc
> namespace common {
> 
> /** Pause execution for the user to examine visualization output, for use
> ```

nit GSG mood.



_Suggestion:_
```objc
Pauses
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19971)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
