### PR TITLE
python bindings for inverse dynamics controller

### PR DESCRIPTION
**Pull request by pvarin**
@EricCousineau-TRI  for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9236)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Note that @pvarin  needs to be added to the RobotLocomotion GitHub organization.

@drake-jenkins-bot test this please

**Comment by jwnimmer-tri** [comment]
@jamiesnape We had previously done "add to whitelist" in #9035.  Does that not work anymore, or do we have to repeat that to refresh Jenkins' memory?

**Comment by jamiesnape** [comment]
It does work, but we need to refresh Jenkins' memory, unfortunately. Ideally we would use the `RobotLocomotion/Drake-Jenkins-Whitelist` team (the whitelist and organization are not entirely equivalent), but it seems few people have the bits to actually add anyone to it.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache, please.

**Pull request merged**
