### PR TITLE
sample-based lyapunov analysis as a linear program.

### PR DESCRIPTION
**Pull request by RussTedrake**
simple example of the pendulum reproducing mechanical energy (roughly).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8236)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@gizatt for feature review, please.
cc @frankpermenter , @peteflorence 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-:-L6fUMzEsSCS26GRRKMf:b-gicq98)*

**Comment by RussTedrake** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gK-69cizihUyORrOc:-L6gK-69cizihUyORrOd:bcdwk0s) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/solvers/mathematical_program.cc#L734)):*
> ```cpp
>              gurobi_solver_->available()) {
>     return gurobi_solver_->Solve(*this);
>   } else if ((required_capabilities_ & kQuadraticCost) &&
> ```

@hongkai-dai -- I needed to add this for the LPs to solve at all w/o gurobi/mosek.  it seems that OSQP does not handle LPs (this is a trivial one)?  Do you approve?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236)*

**Comment by gizatt** [comment]
Very cool! Only a few minor questions on comments, besides the thing you're already asking Hongkai. I think the choice of defaulting to that objective rather than having users supply points where V=1 is sensible, and it's nice that it keeps the interface simpler.

:lgtm: pending the comment tweaks

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[systems/analysis/lyapunov.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gy8XhCUj5aDnwBOqM:-L6gy8XhCUj5aDnwBOqN:boxz1gs) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L40)):*
> ```objc
> /// argument and returns the vector of values of the basis functions at that
> /// state.  The Lyapunov function will then have the form
> ///   Vₚ(x) = ∑ pᵢ φᵢ(x),
> ```

I'm seeing "Vₚ(x)" (i.e. "V[box](x)"

---

*[systems/analysis/lyapunov.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gyKN_X_6zu4lRLouC:-L6gyKNanOKlpUuq8rBc:b-waetd2) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L51)):*
> ```objc
> ///
> /// @return params the VectorXd of parameters, p, that satisfies the Lyapunov
> /// conditions described above.  The resulting Lyapunov funciton is
> ```

funciton -> function

---

*[systems/analysis/lyapunov.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gyHJGq_XvXpbFwM8g:-L6gyHJGq_XvXpbFwM8h:bbhmg6c) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L52)):*
> ```objc
> /// @return params the VectorXd of parameters, p, that satisfies the Lyapunov
> /// conditions described above.  The resulting Lyapunov funciton is
> ///   Vₚ(x) = ∑ pᵢ φᵢ(x),
> ```

Ditto as above, "V[box](x)"

---

*[systems/analysis/lyapunov.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gy_rjGeXgk76ZLoOi:-L6gy_rkwitLSip__2ya:bm5c139) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L54)):*
> ```objc
> ///   Vₚ(x) = ∑ pᵢ φᵢ(x),
> ///
> // TODO(russt): Consider passing a Context into the basis functions instead of
> ```

BTW: I don't know enough about the details of how Contexts are constructed to know the answer to this (or if it's a dumb question): would this affect the current feature that System only has to be double-templated, if you'd expect to consume AutoDiffXd-templated contexts? (Can Autodiff'd contexts be created for non-autodiff'd systems?)

---

*[systems/analysis/test/lyapunov_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6h1YYelC0I2bDfIape:-L6h1YYelC0I2bDfIapf:bofxavv) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/test/lyapunov_test.cc#L45)):*
> ```cpp
> 
> // Verifies by only taking samples inside the region of attraction of the
> // origin, x ∈ [-1, 1].
> ```

The textbook uses this as an example in the Lyapunov chapter -- wouldn't hurt to link to it?

---

*[systems/analysis/test/lyapunov_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6h2t54QEXWC41D_BUA:-L6h2t54QEXWC41D_BUB:b-a74hjp) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/test/lyapunov_test.cc#L106)):*
> ```cpp
>   const double factor = energy_params(0) / params(0);
>   params *= factor;
>   EXPECT_NEAR(params[2], energy_params[2], 1e-4);
> ```

that's pretty magical!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-:-L6h31tmZxAftmcQC9Pl:b150zyd)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gK-69cizihUyORrOc:-L6h3UVIHgKqQuj12REv:b-rupy4o) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/solvers/mathematical_program.cc#L734)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@hongkai-dai -- I needed to add this for the LPs to solve at all w/o gurobi/mosek.  it seems that OSQP does not handle LPs (this is a trivial one)?  Do you approve?
</blockquote></details>

Osqp does handle LPs. It may not solve LPs to a high precision. I have seen some cases that OSQP returns a solution in an LP, with accuracy about 1E-5. 
If accuracy is the concern here, then I think we can turn off OSQP for LP.

I will submit a PR to add the linear program test to OSQP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gK-69cizihUyORrOc:-L6h7AdGVQelSSNgGLwF:b-jg27un) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/solvers/mathematical_program.cc#L734)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Osqp does handle LPs. It may not solve LPs to a high precision. I have seen some cases that OSQP returns a solution in an LP, with accuracy about 1E-5. 
If accuracy is the concern here, then I think we can turn off OSQP for LP.

I will submit a PR to add the linear program test to OSQP.
</blockquote></details>

I did more tests on OSQP. It reaches iteration limit 100000 for a very simple linear program. So I think we can say it turn off OSQP for linear program.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review, please.  

---

Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gK-69cizihUyORrOc:-L6hBLND8hy4mEuVUEIM:bwc3r1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/solvers/mathematical_program.cc#L734)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I did more tests on OSQP. It reaches iteration limit 100000 for a very simple linear program. So I think we can say it turn off OSQP for linear program.
</blockquote></details>

thanks.  yes, it returned nans for my trivial LP.  

---

*[systems/analysis/lyapunov.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gy8XhCUj5aDnwBOqM:-L6hBjzU8tuJQCNn4Nc7:b-3d1fb1) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L40)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I'm seeing "Vₚ(x)" (i.e. "V[box](x)"
</blockquote></details>

strange. fixed.

---

*[systems/analysis/lyapunov.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gyKN_X_6zu4lRLouC:-L6hCOIBsAlviNMok_54:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L51)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

funciton -> function
</blockquote></details>

Done.

---

*[systems/analysis/lyapunov.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gyHJGq_XvXpbFwM8g:-L6hCOos5M5HX7ADF1cr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L52)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Ditto as above, "V[box](x)"
</blockquote></details>

Done.

---

*[systems/analysis/lyapunov.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6gy_rjGeXgk76ZLoOi:-L6hCXLo5XX81g9OZnMX:b-vuswql) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/lyapunov.h#L54)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

BTW: I don't know enough about the details of how Contexts are constructed to know the answer to this (or if it's a dumb question): would this affect the current feature that System only has to be double-templated, if you'd expect to consume AutoDiffXd-templated contexts? (Can Autodiff'd contexts be created for non-autodiff'd systems?)
</blockquote></details>

You're right.  That would be gross.  Nice thinking!

---

*[systems/analysis/test/lyapunov_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6h1YYelC0I2bDfIape:-L6hDA40gbu2xc0QkPwM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5a1209a55ab448ff8d50b41cfa571f8ca6aa6374/systems/analysis/test/lyapunov_test.cc#L45)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

The textbook uses this as an example in the Lyapunov chapter -- wouldn't hurt to link to it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-:-L6hDXM6eN1F6ftb1ue0:b-ftzmm0)*

**Comment by gizatt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236)*

**Comment by soonho-tri** [comment]
Platform :lgtm:. Nice! A couple of cosmetic FYI/BTWs below.

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[systems/analysis/lyapunov.cc, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6juYCJjIRjU5LBUprH:-L6juYCJjIRjU5LBUprI:b-9va92e) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.cc#L5)):*
> ```cpp
> #include <limits>
> #include <utility>
> #include <vector>
> ```

FYI, those three headers are not needed here. Instead, we need `#include <string>` for the use of `std::to_string`.

---

*[systems/analysis/lyapunov.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6jpmfO5p0c-WY-cOYA:-L6jpmfO5p0c-WY-cOYB:bvyc524) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.h#L3)):*
> ```objc
> #pragma once
> 
> #include <utility>
> ```

FYI, 
`#include <utility>` -> `#include <functional` 
as `std::function` is included in the `<functional>` header.

---

*[systems/analysis/lyapunov.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6jpwzUcq-YMIHGsglg:-L6jpwzUcq-YMIHGsglh:b-ygqr9z) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.h#L33)):*
> ```objc
> /// many analysis algorithms, the system does *not* need to support conversion
> /// to other ScalarTypes (double is sufficient).
> /// @param context is used only to specify any parameters of the system, and to
> ```

BTW, a new line to separate two `@param` sections?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-:-L6juohAYzpOY-a-jbSb:bf9rmor)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[systems/analysis/lyapunov.cc, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6juYCJjIRjU5LBUprH:-L6k7X81oxfvVwwg2B5S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.cc#L5)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, those three headers are not needed here. Instead, we need `#include <string>` for the use of `std::to_string`.
</blockquote></details>

Done.

---

*[systems/analysis/lyapunov.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6jpmfO5p0c-WY-cOYA:-L6k7bRpDUzakMSY0L7W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.h#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, 
`#include <utility>` -> `#include <functional` 
as `std::function` is included in the `<functional>` header.
</blockquote></details>

Done.

---

*[systems/analysis/lyapunov.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8236#-L6jpwzUcq-YMIHGsglg:-L6k7gT2Ibp_k-TP0-ud:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6753d81124de4ad38229be86cd4d3d4856c8d22c/systems/analysis/lyapunov.h#L33)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, a new line to separate two `@param` sections?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8236)*

**Pull request merged**
