### PR TITLE
[doc] Add release notes v1.15.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Target is to merge on ~April 17~ April 18

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Requesting review of existing notes; planning to cut release and merge tomorrow (Tues, April 18). Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-:-NTFW7p1Dpzw1OOXT4Ix:bf7thea)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai,rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVpBQEO03SUfFY6WN:-NTFVpBQEO03SUfFY6WO:b-jd2hg7) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L1)):*
> ```Markdown
> ---
> ```

+@jwnimmer-tri for general review, please!
___
*[`doc/_release-notes/v1.15.0.md` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVdLZCC5amrKfN1r2:-NTFVdLZCC5amrKfN1r3:bx0u4uv) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L55)):*
> ```Markdown
> * TBD
> 
> ## Mathematical Program
> ```

+@hongkai-dai for review for mathematical program, please!
___
*[`doc/_release-notes/v1.15.0.md` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVh7E-J9YcPSliXva:-NTFVh7E-J9YcPSliXvb:b-f6iwgi) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L73)):*
> ```Markdown
> * TBD
> 
> ## Multibody Dynamics and Geometry
> ```

+@rpoyner-tri for MbP / Geometry, please!
\cc @amcastro-tri @seancurtis-tri

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVdLZCC5amrKfN1r2:-NTFZJhg5ky-W4TZmvFR:bb6ywmx) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

+@hongkai-dai for review for mathematical program, please!
</blockquote></details>

LGTM

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.15.0.md` line 59 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFvbdvEf7mWy8Dye7j:-NTFvbdw16BIuJglXM-0:bs804jy) ([raw file](https://github.com/RobotLocomotion/drake/blob/db0d92a4925e7e62e055ef98e4c0c11dd516ec12/doc/_release-notes/v1.15.0.md#L59)):*
> ```Markdown
> 
> 
> * Add convenience overloads for AddIndeterminates ([#18992][_#18992])
> ```

In r3, you removed all of the `[feature]` vs `[fix]` hintings, but you didn't sort the bullets into the "New Features" vs "Fixes" subject headings.  Most all of the bullet points in this document are in the wrong locations (after a "notes go here" comment, instead of after a "New features" or "Fixes" grouping).

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.15.0.md` line 205 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG3ouc8WHgUzf_AcEt:-NTG3oud50k4FiChGPAR:byy9yon) ([raw file](https://github.com/RobotLocomotion/drake/blob/db0d92a4925e7e62e055ef98e4c0c11dd516ec12/doc/_release-notes/v1.15.0.md#L205)):*
> ```Markdown
> ## Newly-deprecated APIs
> 
> * TBD
> ```

This still needs work, as does "removal of deprecated" below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 59 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFvbdvEf7mWy8Dye7j:-NTG6YXD3Lfc1ENozLuu:b-emrda) ([raw file](https://github.com/RobotLocomotion/drake/blob/db0d92a4925e7e62e055ef98e4c0c11dd516ec12/doc/_release-notes/v1.15.0.md#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In r3, you removed all of the `[feature]` vs `[fix]` hintings, but you didn't sort the bullets into the "New Features" vs "Fixes" subject headings.  Most all of the bullet points in this document are in the wrong locations (after a "notes go here" comment, instead of after a "New features" or "Fixes" grouping).
</blockquote></details>

Done - oops!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 205 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG3ouc8WHgUzf_AcEt:-NTGB-B6BAdim20HbfrQ:bo6dbi3) ([raw file](https://github.com/RobotLocomotion/drake/blob/db0d92a4925e7e62e055ef98e4c0c11dd516ec12/doc/_release-notes/v1.15.0.md#L205)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This still needs work, as does "removal of deprecated" below.
</blockquote></details>

Done (I believe)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVdLZCC5amrKfN1r2:-NTGB3yK0Ur9I64U_HbJ:b-5fphpe) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Thanks! Any chance I could get your stamp?

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.15.0.md` line 60 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8lBXCbpgj1fQplOP:-NTG8lBXCbpgj1fQplOQ:bkrmzex) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L60)):*
> ```Markdown
> 
> * Add convenience overloads for AddIndeterminates ([#18992][_#18992])
> * Ensure MathematicalProgram stores QuadraticConstraint ([#19016][_#19016])
> ```

@hongkai-dai This revised summary seems wrong to me.  If I recall correctly, we were _already_ storing quadratic constraints (as generic constraints), and the only user-visible change from this commit is that users can _retrieve_ them using a specific collection now, without needing extra dynamic casts.



_Code quote:_
```Markdown
Ensure MathematicalProgram stores QuadraticConstraint
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-:-NTG7c8E-5GXVR7Yx0nK:bnfp4nl)* status: 19 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVpBQEO03SUfFY6WN:-NTGD0ZeCuFkQmsJ-ob2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

+@jwnimmer-tri for general review, please!
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 4 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG7frG3wBMCVHUiKIE:-NTG7frH5odcQYIJT4qt:bbxk7ki) ([raw file](https://github.com/RobotLocomotion/drake/blob/354c43fb043ff3f139cea83159dad82c0371421f/doc/_release-notes/v1.15.0.md#L4)):*
> ```Markdown
> title: Drake v1.15.0
> date: YYYY-MM-DD
> released: YYYY-MM-DD
> ```

BTW Reminder: these two lines need a real date instead of YYYY-MM-DD.
___
*[`doc/_release-notes/v1.15.0.md` line 208 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG7lqt57JC4MOT8oMU:-NTG7lquDHq1zJoD_3Jk:b-jb8bpv) ([raw file](https://github.com/RobotLocomotion/drake/blob/354c43fb043ff3f139cea83159dad82c0371421f/doc/_release-notes/v1.15.0.md#L208)):*
> ```Markdown
> 
> This release provides [pre-compiled binaries](https://github.com/RobotLocomotion/drake/releases/tag/v1.15.0) named
> ``drake-YYYYMMDD-{focal|jammy|mac|mac-arm64}.tar.gz``. See [Stable Releases](/from_binary.html#stable-releases) for instructions on how to use them.
> ```

BTW Reminder: needs a real date instead of YYYY-MM-DD.
___
*[`doc/_release-notes/v1.15.0.md` line 47 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8Hfy2KxTjl-huOLT:-NTG8HfzD7badnrmlpvQ:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L47)):*
> ```Markdown
> New features
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
None
```
___
*[`doc/_release-notes/v1.15.0.md` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8JopDV7o-RwyiXVz:-NTG8JopDV7o-RwyiXW-:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L51)):*
> ```Markdown
> Fixes
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
None
```
___
*[`doc/_release-notes/v1.15.0.md` line 61 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG9ncK79cxJFknQDMH:-NTG9ncK79cxJFknQDMI:buy51x2) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L61)):*
> ```Markdown
> * Add convenience overloads for AddIndeterminates ([#18992][_#18992])
> * Ensure MathematicalProgram stores QuadraticConstraint ([#19016][_#19016])
> * Ensure PiecewisePolynomial supports serialization ([#19062][_#19062])
> ```

nit The new word makes the subject line more confusing, not less.  Saying "Ensure" makes it sound like there was a bug where an invariant was violated.  This is simply a new feature, not an update of anything pre-existing.



_Suggestion:_
```Markdown
PiecewisePolynomial supports serialization
```
___
*[`doc/_release-notes/v1.15.0.md` line 104 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGA6bY4gHNBKKjTz3a:-NTGA6bZ3LGccYVEvV0-:b-kd2l5p) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L104)):*
> ```Markdown
> 
>

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-:-NTGNCJN9Gf3bPDFlHbD:bg7igkv)* status: 19 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 19 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 12 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.15.0.md` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTFVpBQEO03SUfFY6WN:-NTK2-0t0sHSebj2einx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/afd800b5b9aa5c32c962afbb07bd32bd1732855c/doc/_release-notes/v1.15.0.md#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 4 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG7frG3wBMCVHUiKIE:-NTK2-iM5q1Uf4DPnEW9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/354c43fb043ff3f139cea83159dad82c0371421f/doc/_release-notes/v1.15.0.md#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Reminder: these two lines need a real date instead of YYYY-MM-DD.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 208 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG7lqt57JC4MOT8oMU:-NTK2V9n8ZV3cJzLmvNi:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/354c43fb043ff3f139cea83159dad82c0371421f/doc/_release-notes/v1.15.0.md#L208)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Reminder: needs a real date instead of YYYY-MM-DD.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 47 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8Hfy2KxTjl-huOLT:-NTK20Rg9op2Cj3_tgLz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8JopDV7o-RwyiXVz:-NTK217z61tTGhvH7200:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 113 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGAAQAAc-scegxBxFa:-NTK25fK6c4dM8mVDlo6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 61 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG9ncK79cxJFknQDMH:-NTK3Yjp37zvcSAXtiGx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The new word makes the subject line more confusing, not less.  Saying "Ensure" makes it sound like there was a bug where an invariant was violated.  This is simply a new feature, not an update of anything pre-existing.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 132 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGAGGSBtL9pgVZP2aK:-NTK3hOC4VZeMOWXts4L:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unabbreviate (vs "signed distance field").
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 138 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGAXWT2UrGxHJenYPV:-NTK3i4Y2rHXcEo8oiol:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 19063 is more of a "pydrake" fix than anything.  I suggest moving into the "pydrake fixes" section instead of misc.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 149 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGB9RJ2y_eI_k6YOU5:-NTK3imI1-KgX2FMWXlh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For 19172, my taste would be to _not_ have it listed in the bindings section since 19141 above already covered it.

My suggestion is to either demote 19172 to non-notable, or else to tack on the 19172 link to the 19141 bullet point up above (i.e., having two links in the parenthetical).

It isn't a big deal either way, but to me it's most clear to only list _backfill_ bindings here, so there's less for users to wade through to find information of merit.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 159 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGAsRI4m0tnnv_fYqg:-NTK3jOF4k9Wv325-7wj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L159)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For 19118, somehow the link is malformed.  I think it's probably the `<T>`.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 75 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGDJdH4XDQsztD1X3I:-NTK3Zgy2HAKWfF0n6i4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 19171 and 19141 are two legs of a related epic, so at minimum should be adjacent to each other in the bullet list.

(Personally I'd smoosh them into a single bullet.)
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 76 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGDWA92pxeuGJDjIU0:-NTK3__u-3Wccc4-l8MS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 19174 and 19162 are two legs of a related epic, so at minimum should be adjacent to each other in the bullet list.

(Personally I'd smoosh them into a single bullet.)
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 79 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGDcNy2lbEOxxXxl4Z:-NTK3dqLES686aynSwes:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For 19117, this is a `geometry/optimization` feature so goes into "MathematicalProgramming" not "Multibody Dynamics".  (The relnotes tool hasn't been taught this rule yet.)
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 89 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGDrqB4Qtxn8R1Y7rG:-NTK3evz6_AnCDeV_a11:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This XML tag renders incorrectly in HTML during local preview.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 98 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGE-TC8z-Sm7lgzq3s:-NTK3ffiC5qnzSWxQwT8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L98)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unabbreviate, or something:
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.15.0.md` line 182 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTGCfXm02eQYRnqJI79:-NTK3kDV8KkAG54vMz9F:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb3a97578f53b954f2b4a97a9fb15f3030ef56bc/doc/_release-notes/v1.15.0.md#L182)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This particular fraction of 19185 ("fix documentation in new_release") is non-noteable.  The rest of the 19185 lines are okay.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.15.0.md` line 60 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTG8lBXCbpgj1fQplOP:-NTK4q9921y16CRrBfmD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce1cbb7661ad49007fb9c464a2a7363e359d80fa/doc/_release-notes/v1.15.0.md#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@hongkai-dai This revised summary seems wrong to me.  If I recall correctly, we were _already_ storing quadratic constraints (as generic constraints), and the only user-visible change from this commit is that users can _retrieve_ them using a specific collection now, without needing extra dynamic casts.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTK5MHMApM1wLIZrvj-:-NTK5MHMApM1wLIZrvj0:b-a943k4) (no related file):*
Working: Building wheels.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTKd4jIBuzv80YQmrJw:-NTKd4jIBuzv80YQmrJx:b47k67z) (no related file):*
BTW Reminder: needs `from_binary.md` date update still.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTK5MHMApM1wLIZrvj-:-NTKjMYk6G8knrWWysSh:b-kaa4vw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

sha1: d55ac42eba8027bd4a643fb485236ae01f8618c9
release_version: 1.15.0

https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-focal-unprovisioned-gcc-wheel-staging-release/2/console
https://drake-jenkins.csail.mit.edu/view/Staging/job/mac-x86-monterey-unprovisioned-clang-wheel-staging-release/2/console
https://drake-jenkins.csail.mit.edu/view/Staging/job/mac-arm-monterey-unprovisioned-clang-wheel-staging-release/2/console
https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-focal-unprovisioned-gcc-bazel-staging-packaging/2/console
https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-jammy-unprovisioned-gcc-bazel-staging-packaging/2/console
</blockquote></details>

Done. Downloaded locally w/ tooling.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-NTKd4jIBuzv80YQmrJw:-NTKjPHe2nbtIw9lOzfH:b-3hrq6a) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Reminder: needs `from_binary.md` date update still.
</blockquote></details>

Done - oops, and thanks for the reminder!

___

**Comment by EricCousineau-TRI** [comment]
Gonna go ahead and sidestep slow debug / leak sanitizer and merge in.

**Review by EricCousineau-TRI — COMMENTED** [review]
-@hongkai-dai (got LGTM in wording)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19178#-:-NTL6Ea97M9Ss6RdXOcn:b-ivtvre)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Doc job: https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-jammy-unprovisioned-gcc-bazel-nightly-documentation/105/

**Pull request merged**
