### PR TITLE
bot_core_lcmtypes use shell_path

### PR DESCRIPTION
**Pull request by jhoare**
Testing if using shell_path for bot_core_lcmtypes helps cygwin/drake003

### CODE REVIEW

**Comment by jhoare** [comment]
@billhoffman It looks like this change breaks the build when cygwin isn't being used.

**Comment by jamiesnape** [comment]
retest this please

**Comment by billhoffman** [comment]
retest this please

**Comment by billhoffman** [comment]
retest this please

**Comment by billhoffman** [comment]
retest this please

**Comment by billhoffman** [comment]
The -cp looks reasonable, not sure why this breaks things...


"C:\Program Files (x86)\Java\jdk1.8.0_71\bin\javac.exe" -source 6 -target 6 -cp C:/projects/workspace/experimental/compiler/msvc-64/label/windows/externals/bot_core_lcmtypes/java/src;C:/projects/workspace/experimental/compiler/msvc-64/label/windows/build/share/java/lcm.jar;C:/projects/workspace/experimental/compiler/msvc-64/label/windows/externals/bot_core_lcmtypes/pod-build/java/../lcmtypes_bot2_core.jar -d C:/projects/workspace/experimental/compiler/msvc-64/label/windows/externals/bot_core_lcmtypes/pod-build/java/java-build C:/projects/workspace/experimental/compiler/msvc-64/label/windows/externals/bot_core_lcmtypes/java/src/bot2_spy/ImagePlugin.java C:/projects/workspace/experimental/compiler/msvc-64/label/windows/externals/bot_core_lcmtypes/java/src/bot2_spy/PlanarLidarPlugin.java

**Comment by RussTedrake** [comment]
@jhoare -- can you give me a quick update on this?  drake003 is still failing

**Comment by jhoare** [comment]
Right, this didn't seem to work. I believe @billhoffman has a fix cooking for this but I'm not sure of the status on it. 

drake003 never seemed to try this pull request, unfortunately, but this breaks the build on jenkins. I believe bill had a fix that would be applied to RobotLocomotion/cmake

**Comment by jhoare** [comment]
Hoping #1934 is the correct fix for this. Closing.

**Pull request closed without merging**
