### PR TITLE
Use system dependencies for ROS compatibility.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This pull request incorporates WORKSPACE and bazel configuration changes to switch libraries that conflict with library versions used by common ROS stacks with the versions provided by Ubuntu and, in octomap's case, ROS kinetic.

libraries moved to Xenial system version
- ccd (fcl dependency)
- yaml-cpp

libraries moved to ROS kinetic version
- octomap (fcl dependency)

### Setup scripts

The setup script will check if your available apt repositories have a ros-kinetic-octomap package and if not will die with an error. We could make it add the ROS apt repository but I thought it better to start simpler.

### Ongoing work

I don't have ready access to a MacOS machine to test these changes and there are no formula for ccd and octomap available from homebrew. I've built and tested this branch in a clean xenial docker container but I still need to test the install target with drake-shambhala.

CC @stonier @j-rivero and @clalancette who collaborated on this work. 

It might also be of some value to @soonho-tri with regards to https://github.com/RobotLocomotion/drake/issues/7335

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7347)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jamiesnape** [comment]
You also need to ensure the redistributable packages still work. Anything deleted from `drake.cps` most likely needs to be replaced with suitable logic to ensure that happens.

The `install_prereqs.sh` scripts need to be all inclusive, so if a ROS repo is needed, it needs to be added there. CI relies on the scripts having everything needed to compile and use drake.

**Comment by jamiesnape** [comment]
(Maybe do each external in a separate PR. yaml-cpp is already on the images and ccd is easy to install.)

**Comment by jwnimmer-tri** [comment]
I was also pondering whether to suggest breaking this up.  If homebrew is going to be a question mark, and each external has different packaging requirements, I also agree that three PRs seems like a good proposal.

**Comment by jamiesnape** [comment]
> there are no formula for ccd and octomap available from homebrew

```
$ brew info homebrew/science/libccd
homebrew/science/libccd: stable 2.0, HEAD
http://libccd.danfis.cz
Not installed
From: https://github.com/Homebrew/homebrew-science/blob/master/libccd.rb
==> Dependencies
Build: cmake ✔
==> Options
--with-single-precision
	Use single precision
--HEAD
	Install HEAD version
```

**Comment by jamiesnape** [comment]
For OctoMap, I can just create a package on `robotlocomotion/director` if we really need to. I would have thought `homebrew/science` would accept a PR, though

**Comment by nuclearsandwich** [comment]
> I was also pondering whether to suggest breaking this up. If homebrew is going to be a question mark, and each external has different packaging requirements, I also agree that three PRs seems like a good proposal.

This branch is actually a cherry pick of three independent branches so I can easily submit individual pull requests if that's preferred.

> there are no formula for ccd ... available from homebrew

Cool. It's been ages since I've worked in depth with homebrew so I wasn't aware of the separate science packages.

**Comment by nuclearsandwich** [comment]
This has been superceded by https://github.com/RobotLocomotion/drake/issues/7412 which references the suite of pull requests resolving necessary system dependencies.

**Pull request closed without merging**
