### PR TITLE
Add Python binding for GetForceElement

### LINKED ISSUE #14874: pydrake missing MultibodyPlant.GetForceElement method
I am working to convert the strandbeest example using pydrake. 

I am currently unsure how to add the position constraints for each bushing element (line 198 run_with_motor.cc) because there is not a method GetForceElement in the pydrake bindings.

Was this method intentionally left out of the python bindings?

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Fixes #14874.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
I know this is currently marked "do not review", but I posted a though below in case it saves you time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953#-:-MZFoIAqBBPRbhUmluCr:b6zawa9)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[bindings/pydrake/multibody/plant_py.cc, line 743 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZFmzWw1UR8346I-LdV:-MZFmzWx9llKfNotXpUH:b-ss7t91) ([raw file](https://github.com/robotlocomotion/drake/blob/5e73eaf60200fdcbb59cda82a65775901dcbdf23/bindings/pydrake/multibody/plant_py.cc#L743)):*
> ```cpp
>             cls_doc.get_force_element.doc)
>         .def(
>             "GetForceElement",
> ```

nit From the point of view of a pydrake user (i.e., with dynamic typing, instead of static typing), the semantics of `get_force_element` and `GetForceElement` are identical, but the docstring for the CamelCase binding is more confusing (due to the tparam description, which is not a feature present in pydrake bindings).  In this case, I think you should remove the CamelCase binding and leave only the snake_case binding.

(The C++ code also is wrong for offering both spellings -- it should offer only the snake_case spelling, but with the template-template semantics of the current CamelCase method.  However, that is not in scope for this PR.  But omitting CamelCase here will be one less thing to deprecate when we repair the C++ bug.)

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review please (since you essentially already did it).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953#-:-MZGJ6fY7c3BQ6dNS9GI:b-8r2zat)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/plant_py.cc, line 743 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZFmzWw1UR8346I-LdV:-MZGJ-vDERXEMcJFNuVL:b-fxmx6x) ([raw file](https://github.com/robotlocomotion/drake/blob/5e73eaf60200fdcbb59cda82a65775901dcbdf23/bindings/pydrake/multibody/plant_py.cc#L743)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit From the point of view of a pydrake user (i.e., with dynamic typing, instead of static typing), the semantics of `get_force_element` and `GetForceElement` are identical, but the docstring for the CamelCase binding is more confusing (due to the tparam description, which is not a feature present in pydrake bindings).  In this case, I think you should remove the CamelCase binding and leave only the snake_case binding.

(The C++ code also is wrong for offering both spellings -- it should offer only the snake_case spelling, but with the template-template semantics of the current CamelCase method.  However, that is not in scope for this PR.  But omitting CamelCase here will be one less thing to deprecate when we repair the C++ bug.)
</blockquote></details>

Thanks for the feedback! Agreed and done.

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not review) :lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953#-:-MZGJxWN1CNfYIX2T76k:bytngwr)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 750 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZGKyKm-njjl-0ZtgAx:-MZGKyKm-njjl-0ZtgAy:bwh59cp) ([raw file](https://github.com/robotlocomotion/drake/blob/a879316c6d383988d5f215705e10532cec57323b/bindings/pydrake/multibody/test/plant_test.py#L750)):*
> ```Python
> 
>         # Test get_force_element().
>         self.assertIs(plant.get_force_element(linear_spring_index),
> ```

nit When testing pydrake bindings, always test the kwarg calling convention:

```py
plant.get_force_element(force_element_index=linear_spring_index)
```

This serves as a regression test that the keyword name works, and does not silently change.  See https://drake.mit.edu/doxygen_cxx/group__python__bindings.html under "Testing".

You can optionally also call the non-keyword form, but usually that is not super useful and in this case I would skip it.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 757 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZGKt17AZ7zFex32810:-MZGKt17AZ7zFex32811:b7vrfjz) ([raw file](https://github.com/robotlocomotion/drake/blob/a879316c6d383988d5f215705e10532cec57323b/bindings/pydrake/multibody/test/plant_test.py#L757)):*
> ```Python
>                       door_hinge)
>         self.assertIs(plant.get_force_element(bushing_index),
>                       bushing)
> ```

nit What is testing it four times buying us, that testing it once did not?

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953#-:-MZGVCHnBPfQIK3M0Vcv:bbboct3)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 750 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZGKyKm-njjl-0ZtgAx:-MZGTII15RxL_krWYCJc:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/a879316c6d383988d5f215705e10532cec57323b/bindings/pydrake/multibody/test/plant_test.py#L750)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When testing pydrake bindings, always test the kwarg calling convention:

```py
plant.get_force_element(force_element_index=linear_spring_index)
```

This serves as a regression test that the keyword name works, and does not silently change.  See https://drake.mit.edu/doxygen_cxx/group__python__bindings.html under "Testing".

You can optionally also call the non-keyword form, but usually that is not super useful and in this case I would skip it.
</blockquote></details>

Done, thanks.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 757 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14953#-MZGKt17AZ7zFex32810:-MZGTT9P1rmclJg55N3E:b9qut8z) ([raw file](https://github.com/robotlocomotion/drake/blob/a879316c6d383988d5f215705e10532cec57323b/bindings/pydrake/multibody/test/plant_test.py#L757)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit What is testing it four times buying us, that testing it once did not?
</blockquote></details>

I was testing that `get_force_element()` indeed returns the `ForceElement` indexed by the given index instead of just returning a fixed one (Admittedly testing it four times is an overkill). But I see the point made in the testing guide for pydrake you linked in the other comment about not testing the c++ logic and thus deleted the last three tests.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Thanks, Xuchen! Platform :lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14953#-:-MZIu-3F8ODCedfBg2Vq:b-ebk9tf)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
