### PR TITLE
Fixes to PPTrajectory.append

### PR DESCRIPTION
**Pull request by eric-wieser**
`append(pptraj, consttraj)` now works

### CODE REVIEW

**Comment by eric-wieser** [comment]
This pulls across changes from #1480

**Comment by eric-wieser** [comment]
The "frame lost upon operation" issue seems to be pretty pervasive across the codebase...

**Comment by RussTedrake** [comment]
looks like the build servers caught one real failure.

**Comment by eric-wieser** [comment]
Yep:

```
Error using PPTrajectory/append (line 596)
Cannot append trajectories with different coordinate frames

Error in PPTrajectory/subsref (line 506)
        [varargout{:}] = builtin('subsref',a,s);

Error in runAtlasJumping (line 142)
V_S = V_takeoff.S.append(S_flight);
```

I think this comes down to the default value of `PPTrajectory.getOutputFrame` being unique each time.

Sadly, I need `gurobi` to diagnose the failure

**Comment by eric-wieser** [comment]
Easy fix - don't add fatal checks where they didn't exist before - now at least emits a warning

**Pull request merged**
