### PR TITLE
Integrate SimulatorConfig into existing configuration code

### PR DESCRIPTION
**Pull request by dmcconachie-tri**
In support of #12903

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI My expectation was that the `simulator_flags` filename goes away (with deprecation) and `simulator_config_functions` filename stays.  I think the `foo_config` and `foo_config_functions` file naming pattern will suit us better over time, than `foo_flags` which is a bit more limiting.

**Review by dmcconachie-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135#-:-MIPpl4s3nhh16WKbCcD:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
a couple minor comments. :lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135#-:-MIV4lwp71jU7p8fqZpx:bjusd3b)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator_flags.cc, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIUk-Z95GLRWRPdYEvN:-MIUk-Z95GLRWRPdYEvO:bkgqqfh) ([raw file](https://github.com/robotlocomotion/drake/blob/dba012de4c30a1e9f3a23c11ad6fa67d573a2b90/systems/analysis/simulator_flags.cc#L2)):*
> ```cpp
> #include "drake/systems/analysis/simulator_flags.h"
> ```

sry, why not to remove this file altogether? 
___
*[systems/analysis/test/simulator_config_functions_test.cc, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIV47OlDy4DB7iv2dTe:-MIV47Om928MtdsivIhz:b-dwdqek) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/test/simulator_config_functions_test.cc#L39)):*
> ```cpp
>   Simulator<double> simulator(source);
>   for (const auto& one_scheme : schemes) {
>     ResetIntegratorFromFlags(&simulator, one_scheme, 0.001);
> ```

should we have an EXPECT_NO_THROW or similar here?

**Review by amcastro-tri — COMMENTED** [review]
+@soonho-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135#-:-MIV4sWm7NnHgGaOSQF3:b-vt9vbo)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @dmcconachie-tri and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135#-:-MIVYl023h0UyGDCZb3C:bnfp4nl)* status: 5 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/BUILD.bazel, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVR22Y-6REtYW6OUCS:-MIVR22Y-6REtYW6OUCT:bsddtxu) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/BUILD.bazel#L71)):*
> ```Starlark
>     visibility = ["//:__subpackages__"],
>     deps = [
>         ":simulator_config",
> ```

nit, `:simulator_config" is not a (direct) dependency of this target.
___
*[systems/analysis/simulator_config_functions.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVTe8l7Wv5j-BnaLTE:-MIVTe8l7Wv5j-BnaLTF:bwdeugk) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/simulator_config_functions.h#L30)):*
> ```objc
>   GetIntegrationSchemes() for a the list of valid options.
> @param[in] max_step_size The IntegratorBase::set_maximum_step_size() value.
> @returns A reference to the the newly created integrator owned by `simulator`.
> ```

nit, `the the` => `the`.  
___
*[systems/analysis/simulator_config_functions.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVU5IEB6Zcpk4EgE5O:-MIVU5IEB6Zcpk4EgE5P:beluucc) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/simulator_config_functions.cc#L32)):*
> ```cpp
> using std::string;
> using std::vector;
> using symbolic::Expression;
> ```

nit, not used.

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @soonho-tri)

___
*[systems/analysis/BUILD.bazel, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVR22Y-6REtYW6OUCS:-MIVZOsn6M1k8wnvv8yD:b-skq33g) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/BUILD.bazel#L71)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `:simulator_config" is not a (direct) dependency of this target.
</blockquote></details>

A`SimulatorConfig` object is explicitly created [in `simulator_gflags.cc` L92](https://github.com/RobotLocomotion/drake/pull/14135/files#diff-4149c8d7af34ab19aa6aaa9b1765ec7aR92).
___
*[systems/analysis/simulator_config_functions.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVTe8l7Wv5j-BnaLTE:-MIV_XfC350UpmoqnFt7:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/simulator_config_functions.h#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `the the` => `the`.  
</blockquote></details>

Done
___
*[systems/analysis/simulator_config_functions.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIVU5IEB6Zcpk4EgE5O:-MIV_mkM-XwXa8L7CSww:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/simulator_config_functions.cc#L32)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, not used.
</blockquote></details>

Done
___
*[systems/analysis/simulator_flags.cc, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIUk-Z95GLRWRPdYEvN:-MIV_qPPDj0cTO6EaueB:b2k0wtx) ([raw file](https://github.com/robotlocomotion/drake/blob/dba012de4c30a1e9f3a23c11ad6fa67d573a2b90/systems/analysis/simulator_flags.cc#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sry, why not to remove this file altogether? 
</blockquote></details>

On the "every header gets a `cc` file to ensure basic compilation" principle.
___
*[systems/analysis/test/simulator_config_functions_test.cc, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIV47OlDy4DB7iv2dTe:-MIVbAqtBSvKjY31pcph:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8079872b19c88868a56496b2d2c94121300f33fc/systems/analysis/test/simulator_config_functions_test.cc#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should we have an EXPECT_NO_THROW or similar here?
</blockquote></details>

Done

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[systems/analysis/simulator_flags.cc, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14135#-MIUk-Z95GLRWRPdYEvN:-MIVl13Q7nAvB7_4Xbje:b1s23f2) ([raw file](https://github.com/robotlocomotion/drake/blob/dba012de4c30a1e9f3a23c11ad6fa67d573a2b90/systems/analysis/simulator_flags.cc#L2)):*
<details><summary><i>Previously, dmcconachie-tri wrote…</i></summary><blockquote>

On the "every header gets a `cc` file to ensure basic compilation" principle.
</blockquote></details>

Thanks, I didn't know about that principle.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14135)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
