### PR TITLE
Linker options for building on arm64

### PR DESCRIPTION
**Pull request by alsocapprin**
### Description of Changes
When building Drake on arm64, a handful of components fail because of a missing `-pthread` linker option. This branch adds those missing options and results in a passing build.

### Testing Done

On both arm64 and x86:
```
bazel build //...
bazel test //...
```
> At time of writing, build passes for both platforms. My arm machine is headless, so tests that require a display are currently failing. I'll chase the tests down in the next day or two and update this PR.

> We've also run this build against some of our existing Drake sims and [drake-ros](https://github.com/RobotLocomotion/drake-ros), which inspires confidence, although those "tests" don't really provide coverage.

### Related Issues

Addresses #13514 in part.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Re: "Testing Done" -- don't worry about it too much.  If this makes things better, I'm happy to land it.  Later if you find more missing pieces, we can fix those down the road.

The main questions here will be:

(1) Does it break any _existing_ CI builds?  We'll just let Jenkins tell us, no big deal.

@drake-jenkins-bot ok to test

(2) Are the code changes clear enough / well-formulated?  I'll handle this during my code review.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

___
*[`common/BUILD.bazel` line 1132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-Nrf1JR99G7YuSS_xrjT:-Nrf1JRA4nrmdtwOtrpR:b-clbxsk) ([raw file](https://github.com/RobotLocomotion/drake/blob/e94671aa3376d66fe7d1915cf66c267f7fe329a3/common/BUILD.bazel#L1132)):*
> ```Starlark
>     ],
>     linkopts = [
>         "-pthread",
> ```

What code in this test is using threads?  I can't find any, so I don't understand the reason we need this one.
___
*[`tools/workspace/lcm/package.BUILD.bazel` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-Nrf-pwa8HglbGvK8Ean:-Nrf-pwa8HglbGvK8Eao:bblwzo5) ([raw file](https://github.com/RobotLocomotion/drake/blob/e94671aa3376d66fe7d1915cf66c267f7fe329a3/tools/workspace/lcm/package.BUILD.bazel#L32)):*
> ```
> config_setting(
>     name = "linux",
>     values = {"cpu": "k8"},
> ```

nit I think the LCM problem is this line, which is the old & wrong way to check for linux.

Replace the `values = ...` line with `constraint_values = ["@platforms//os:linux"],` instead, and see if that fixes it for you.
___
*[`tools/workspace/lcm/package.BUILD.bazel` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-Nrf-mfj-LTi6dqeOdUB:-Nrf-mfk8m7kGfrKq5M6:b-v91hk8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e94671aa3376d66fe7d1915cf66c267f7fe329a3/tools/workspace/lcm/package.BUILD.bazel#L145)):*
> ```
>     ],
>     linkopts = [
>         "-pthread",
> ```

nit I don't think this one is in the right place.  See above.

**Review by jwnimmer-tri — COMMENTED** [review]
For review discussions, you'll want to open the "Reviewable" badge atop this PR, and reply inline to each thread.  (Often it's just clicking "Resolve" with no comment.)  I'll do that myself for this round, though.

Some of the test failures in the original round were linter complaints.  In the Jenkins output, it will print the commands you should run to fix the lint.  But locally, you can also just do `bazel test --config=lint //...` to see all of them, and fix them locally without a round-trip through Jenkins.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-:-NrgCed38PiR1RVrF6L_:bo00o5c)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

**Review by alsocapprin — COMMENTED** [review]
Got it. Fixed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-:-NrgMxRc-5iVvRq1ySxB:b4844z4)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

___
*[`common/BUILD.bazel` line 1148 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-NrgbnzgEneePEck-co9:-Nrgbnzh8vtUrKRoVGhA:bu0s2cy) ([raw file](https://github.com/RobotLocomotion/drake/blob/de3140f41ce238e55157837ed439c359729c27e6/common/BUILD.bazel#L1148)):*
> ```Starlark
>     ],
>     linkopts = [
>         "-pthread",
> ```

What code in this test is using threads? I can't find any, so I don't understand the reason we need this one.

**Review by alsocapprin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

___
*[`common/BUILD.bazel` line 1148 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-NrgbnzgEneePEck-co9:-NrggNXT25VF4ydg5rR_:b-ic55sc) ([raw file](https://github.com/RobotLocomotion/drake/blob/de3140f41ce238e55157837ed439c359729c27e6/common/BUILD.bazel#L1148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What code in this test is using threads? I can't find any, so I don't understand the reason we need this one.
</blockquote></details>

Addressed; as above, this was necessary a couple months ago (I assume), but is no longer.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: as feature reviewer.  (FYI https://drake.mit.edu/developers.html#review-process.)

+@rpoyner-tri for platform review per schedule, please.  You might notice that Drake is not consistent about whether the `-pthread` linkopt needs to be guarded to be linux-specific.  It does not seem to cause any trouble on macOS, so our linux-only guards are probably vestigial as this point.  I've decided not to try to tackle/enforce in the scope of this PR.  We can clean it up later, if we decide to.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-:-Nrgil7VDfcB4Mob-GAG:bl0btn5)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21047#-:-Nrgok-_-gc0q97fzDBt:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @alsocapprin)

**Pull request merged**
