### PR TITLE
Provide and use DRAKE_RESOURCE_ROOT in resource_tool

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6343)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.
+(label: do not merge) until I find a feature reviewer.

**Comment by ggould-tri** [comment]
Having to invoke a tool with a flag to find out the name of an environment variable used by the tool is a bizarre behaviour and I don't believe I have ever seen a tool do anything like this.

It seems like you are jumping through your own armpit to avoid exposing the name of the envvar as part of your public interface.  Wouldn't it be simpler to just make the envvar name part of the documented API of `resource_tool`?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn-sAwuXNeY8lRreqAN:b-y0m2x9)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri  for volunteer feature review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn00neOMNaoXJRmZwS7:b67bgkm)*

**Comment by rpoyner-tri** [comment]
I too am confused by the tool prints the variable name; can you elaborate the use cases?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn0Be5PbYX1TLqNN1Cx:bz2taho)*

**Comment by jwnimmer-tri** [comment]
The idea was to hide the variable name from the user, and only promise that the tool would print it.  It sounds like that is too unusual or cumbersome a choice, so I'll rework it to document the variable name as a long-lived API promise.

**Comment by jwnimmer-tri** [comment]
Done.  PTAL.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn0toSjLhDVvda2_t0t:b-19xu5k)*

**Comment by ggould-tri** [comment]
Sure.  :lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn0y5LSTtGCb0L3RJl4:b-fchfpc)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6343#-:-Kn15Y420TnMoQ8q7cQF:bnfp4nl)*

**Pull request merged**
