### PR TITLE
Removes extraneous blank line from RigidBody::Clone().

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5042)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ggould-tri for both levels of review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5042#-:-Kc3LnpfHnptb2pj3X45:b-tg60x5)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5042#-:-Kc3Olb1iXWtIFpwa05Q:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5042)*

**Comment by liangfok** [comment]
Thanks. Now awaiting CI.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5042#-:-Kc3P7EJoGapGxx1pSEC:b-7xi1xe)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please.

**Pull request merged**
