### PR TITLE
[symbolic] ToLatex displays matrix/vector variables using subscript for indices

### PR DESCRIPTION
**Pull request by RussTedrake**
+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16720)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16720)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[common/symbolic_latex.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16720#-MxW7rkB40FDxHGfK20j:-MxW7rkB40FDxHGfK20k:brpa76m) ([raw file](https://github.com/robotlocomotion/drake/blob/8198b17fb90f53569140c371a49f8e3a008471b1/common/symbolic_latex.cc#L33)):*
> ```cpp
>  private:
>   [[nodiscard]] std::string VisitVariable(const Expression& e) const {
>     std::string s = get_variable(e).to_string();
> ```

If the variable name is `x(abc(10))` then this will display as `x_{abc(10)}`. Should we make sure that there is only one pair of () in the name?

**Comment by RussTedrake** [comment]
___
*[common/symbolic_latex.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16720#-MxW7rkB40FDxHGfK20j:-MxWQdRl1sAXjpHNk5Np:bph28k5) ([raw file](https://github.com/robotlocomotion/drake/blob/8198b17fb90f53569140c371a49f8e3a008471b1/common/symbolic_latex.cc#L33)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If the variable name is `x(abc(10))` then this will display as `x_{abc(10)}`. Should we make sure that there is only one pair of () in the name?
</blockquote></details>

Having x_{abc(10)} for that was my intention.  Do you think it's better to leave the string alone in that case?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16720#-:-MxYMJh-7tWFzYT35rvY:bptxe99)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai and @sammy-tri)

___
*[common/symbolic_latex.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16720#-MxW7rkB40FDxHGfK20j:-MxYM53Y1xn7TC6bjvwX:baso26m) ([raw file](https://github.com/robotlocomotion/drake/blob/8198b17fb90f53569140c371a49f8e3a008471b1/common/symbolic_latex.cc#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Having x_{abc(10)} for that was my intention.  Do you think it's better to leave the string alone in that case?
</blockquote></details>

I think it's fine either way, just want to make sure that's `x_{abc(10)}` is the intended result. I mark myself satisfied.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

I had some difficulty convincing myself that this was correct since it creates (further instills?) a convention that any part of a variably name surrounded in parens is intended to be read as a subscript...   but eventually I decided that this change is more likely to produce desirable latex output in the common case (presumably it's rather unusual that someone has otherwise managed to create a variable with parens in the name and would object to the latex form being subscripted).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16720#-:-Mx_uuXMC2ucELhWza9j:br0czlx)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
