### PR TITLE
Adds onramp road network option to automotive_demo.

### PR DESCRIPTION
**Pull request by liangfok**
# Screenshot of On-ramp Road Network
Here's a screenshot of a `MaliputRailcar` traversing an onramp road network:

screen shot 2017-04-02 at 11 28 21 am

The onramp was originally introduced in #5169.

# Video

https://youtu.be/VmUCRWHor5c

# Commands
The commands to run the demo are:

```
./build/install/bin/drake-visualizer
bazel run //drake/automotive:automotive_demo -- --num_trajectory_car=0 --num_maliput_railcar=2 --with_onramp 

```

# Annotated Onramp

onramp_annotated

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5699)

### CODE REVIEW

**Comment by liangfok** [comment]
@jadecastro, can you look at the screenshots of the on-ramp shown above. It appears to be a mirror image of what you posted in #5169. Is the road network shown in my screenshots what you expect it to be? Are the two starting positions I annotated correct?

**Comment by jadecastro** [comment]
It looks the same as the original except that the main road appears to transition into an off-ramp. You could always run the cars in reverse, so there should be no problem using the starting points you've indicated with arrows.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-Kgli_0IjCyTTVAcfrwl:b-9nvksv)*

**Comment by liangfok** [comment]
Thanks! I will proceed as-is then.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-Kglk_KcXeeOWE_swVI8:bysh06y)*

**Comment by liangfok** [comment]
+@soonho-tri for feature review please.
+@jwnimmer-tri for platform and car reviews please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-KgoTV9y_F6XgEnOBdjY:b-wsc2wr)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-KgotTTiTMPSFmTMYwIU:b-ioqduq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

So I think the epsilon / ongoing fixes are fine, but the amount of duplication in that method is un-durably brittle for the medium term, and its one of the things I intend to look at in the refactoring effort.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-Kgok7MShFFHKbN4xISv:-Kgok7MShFFHKbN4xISw:bjvnqbk) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/automotive_simulator.cc#L220)):*
> ```cpp
>       }
>     }
>   }
> ```

FYI This is fine, but if it comes up here, likely it would come up in other places, so should be a native API within RoadGeometry, perhaps?  That would probably be an easier place to unit test it. too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-Kgoxvct_FYW-x7DxXHp:b-fdg4lg)*

**Comment by liangfok** [comment]
Yes, I agree. The epsilon logic should probably be moved into a superclass of all lane-based vehicle models. Without it, the vehicle gets infinitesimally close to the end of the current lane to the point where the next update time equals the current time. At this point, the simulator aborts saying the next update time must be strictly greater than the current time.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-Kgok7MShFFHKbN4xISv:-Kgp9oOLy3Ht4J8b-0h5:b-5dn4cc) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/automotive_simulator.cc#L220)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is fine, but if it comes up here, likely it would come up in other places, so should be a native API within RoadGeometry, perhaps?  That would probably be an easier place to unit test it. too.
</blockquote></details>

Agreed: #5708.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-KgpA9fW6uURIRzZ1TUb:bohqspp)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgsyrgfCpncRXsqemg0:-KgsyrgfCpncRXsqemg1:b-hm0gip) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/maliput_railcar.cc#L326)):*
> ```cpp
>     actions->time = context.get_time() + distance / s_dot;
>   }
>   DRAKE_ASSERT(actions->time != context.get_time());
> ```

FYI, this assertion fails when I run `bazel test //drake/automotive:maliput_railcar_test -c dbg --compiler=gcc-4.9`:

```
[ RUN      ] MaliputRailcarTest.DoCalcNextUpdateTimeDragwayWithS
abort: failure at drake/automotive/maliput_railcar.cc:326 in DoCalcNextUpdateTime(): assertion 'actions->time != context.get_time()' failed.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgsyrgfCpncRXsqemg0:-KgszFmG6wyewRvmW89T:b-je4srj) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/maliput_railcar.cc#L326)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this assertion fails when I run `bazel test //drake/automotive:maliput_railcar_test -c dbg --compiler=gcc-4.9`:

```
[ RUN      ] MaliputRailcarTest.DoCalcNextUpdateTimeDragwayWithS
abort: failure at drake/automotive/maliput_railcar.cc:326 in DoCalcNextUpdateTime(): assertion 'actions->time != context.get_time()' failed.
```
</blockquote></details>

Can you reproduce the problem? I'm wondering why CI didn't detect this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by liangfok** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgsyrgfCpncRXsqemg0:-Kgt20o4W4RL9gcnYIR0:b-1pyjua) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/maliput_railcar.cc#L326)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can you reproduce the problem? I'm wondering why CI didn't detect this one.
</blockquote></details>

Yes, I can replicate the error. Thanks for catching it! CI didn't detect the problem because there are no pre-merge bazel + debug mode tests and this unit test is only run in Bazel (it was not added to `CMakeLists.txt`.)

I fixed the problem by adding a `kTimeEpsilon` to `MaliputRailcar`. I'm not 100% certain that this is the correct solution since it is possible that the tested scenario where the vehicle is at the end of the lane may never occur. I believe it depends on the type of integrator being used. Since I was sure, I took the "safe" route, which handles this potentially degenerate scenario. PTAL. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgsyrgfCpncRXsqemg0:-KgtF3Ej5UdN0RZLxB9E:bivqarc) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/maliput_railcar.cc#L326)):*
The new version works!

> no pre-merge bazel + debug mode tests

Right, just remembered. Thank you!

---

*[drake/automotive/maliput_railcar.cc, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtEI0BITk_kCB_q3uy:-KgtEI0BITk_kCB_q3uz:b-9hf22p) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.cc#L48)):*
> ```cpp
> template <typename T> constexpr T MaliputRailcar<T>::kDefaultInitialSpeed;
> template <typename T> constexpr double MaliputRailcar<T>::kLaneEndEpsilon;
>   template <typename T> constexpr double MaliputRailcar<T>::kTimeEpsilon;
> ```

FYI, nit: indentation.

---

*[drake/automotive/maliput_railcar.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtETHqb3VokJLkU6O_:-KgtETHqb3VokJLkU6Oa:b-lxbz5b) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.h#L61)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(MaliputRailcar)
>   /// Defines a distance that is "close enough" to the end of a lane for the
>   /// vehicle to transition to an ongoing branch.
> ```

Could you document if there are any constraints on the choice of `kLaneEndEpsilon` and `kTimeEpsilon`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by liangfok** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput_railcar.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgsyrgfCpncRXsqemg0:-KgtHB4dHoCKgGfnRp4w:bw8k9su) ([raw file](https://github.com/robotlocomotion/drake/blob/68705d133a68259e1a12ffa7b0879d72f57d939d/drake/automotive/maliput_railcar.cc#L326)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

The new version works!

> no pre-merge bazel + debug mode tests

Right, just remembered. Thank you!

</blockquote></details>

Great! Thanks again.

---

*[drake/automotive/maliput_railcar.cc, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtEI0BITk_kCB_q3uy:-KgtHPmISt-70xdmJRyt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.cc#L48)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, nit: indentation.
</blockquote></details>

Done.

---

*[drake/automotive/maliput_railcar.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtETHqb3VokJLkU6O_:-KgtJLkP_bRbG2oTU1jl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.h#L61)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you document if there are any constraints on the choice of `kLaneEndEpsilon` and `kTimeEpsilon`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtETHqb3VokJLkU6O_:-KgtLiKb0_kiU-f0vfYP:b-r54dnc) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.h#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very nice! Thank you!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-:-KgtLocTb6rpCusnPFKY:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by liangfok** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5699#-KgtETHqb3VokJLkU6O_:-KgtM-4J-OIAKO-guoXB:bx1pvez) ([raw file](https://github.com/robotlocomotion/drake/blob/405dcc31cc1cf4c3a8b520d3ce6f7439e30b61ff/drake/automotive/maliput_railcar.h#L61)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Very nice! Thank you!!
</blockquote></details>

No problem. I just further updated the text to clarify that a time that "greater than" is a time that is "after'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5699)*

**Pull request merged**
