### PR TITLE
Move IiwaIkPlanner out of dev/ and rename to ConstraintRelaxingIk

### PR DESCRIPTION
**Pull request by sammy-tri**
This is almost a pure move.  Some code is also deleted.

Note to platform reviewer: The files now located in drake/manipulation/planner were previously in a dev/ folder.  They should probably be reviewed as new.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6127)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkNAFnjmsxnBtXF4ZmM:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
nit. I might rename it something like constraint_relaxing_ik :lgtm: 

---

Reviewed 17 of 20 files at r1.
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/BUILD, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkNAxuWW-_R6uIvUVCE:-KkNAxuWW-_R6uIvUVCF:b-nxz3l9) ([raw file](https://github.com/robotlocomotion/drake/blob/c7e10ca1c96f8694e49944826fdb59efd2c80290/drake/manipulation/planner/BUILD#L37)):*
> ```Python
>         "//drake/manipulation/models/iiwa_description:models",
>     ],
>     tags = ["snopt"],
> ```

we don't want this anymore? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkNFcKwnvOZYUqyRL8E:b-8lqjit)*

**Comment by sammy-tri** [comment]
Renamed.  I like that better.

+@soonho-tri for platform review

---

Review status: 4 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/BUILD, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkNAxuWW-_R6uIvUVCE:-KkQpxkjGwIN0j0Sz8j1:b7pjgv) ([raw file](https://github.com/robotlocomotion/drake/blob/c7e10ca1c96f8694e49944826fdb59efd2c80290/drake/manipulation/planner/BUILD#L37)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

we don't want this anymore? 
</blockquote></details>

For a couple of reasons, we never wanted it, afaict.  I think #6090 got it wrong and should only have skipped this test when neither IPOPT or SNOPT was available... and disabling IPOPT isn't a supported bazel build configuration, so it seemed like the right thing to do was just to leave the test enabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkQtLJiWBNI9PNAivF_:b-yy1ywj)*

**Comment by siyuanfeng-tri** [comment]
Review status: 4 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/BUILD, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkNAxuWW-_R6uIvUVCE:-KkQv3TcPakeKqZ0qbAs:bzeyi24) ([raw file](https://github.com/robotlocomotion/drake/blob/c7e10ca1c96f8694e49944826fdb59efd2c80290/drake/manipulation/planner/BUILD#L37)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

For a couple of reasons, we never wanted it, afaict.  I think #6090 got it wrong and should only have skipped this test when neither IPOPT or SNOPT was available... and disabling IPOPT isn't a supported bazel build configuration, so it seemed like the right thing to do was just to leave the test enabled.
</blockquote></details>

Sure. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127)*

**Comment by soonho-tri** [comment]
First pass done. PTAL.

---

Reviewed 8 of 23 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/manipulation/planner/BUILD, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkRDF4cqOLUUwNCCNoJ:-KkRDF4cqOLUUwNCCNoK:b-1ljhyi) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/BUILD#L31)):*
> ```Python
> drake_cc_googletest(
>     name = "constraint_relaxing_ik_test",
>     size = "medium",
> ```

FYI, on a mac, the test times out when `ipopt` is used. It works well with `snopt` though.

---

*[drake/manipulation/planner/constraint_relaxing_ik.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR0LyV1jH21HHW0OBj:-KkR0LyV1jH21HHW0OBk:bc8mfe) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.cc#L23)):*
> ```cpp
>     const std::string& end_effector_link_name,
>     const Isometry3<double>& base_to_world)
>     : rand_generator_(kDefaultRandomSeed) {
> ```

BTW, is it OK not to provide a way to pass a different random-seed?

---

*[drake/manipulation/planner/constraint_relaxing_ik.cc, line 190 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkQz7OQFYzSiJzKadN_:-KkQz7OQFYzSiJzKadNa:boeztza) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.cc#L190)):*
> ```cpp
>              infeasible_constraints);
> 
>   if ((*info)[0] != 1) {
> ```

FYI, this if-statement+returns can be reduced to:
```c++
return (*info)[0] == 1;
```

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 41 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR3c9K3CDVqdy0W1zO:-KkR3c9K3CDVqdy0W1zP:b-878nxz) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L41)):*
> ```objc
>     EIGEN_MAKE_ALIGNED_OPERATOR_NEW
> 
>     /// Default constructor.
> ```

FYI, I think it is cleaner and more readable to use class member initialization above:
```c++
    /// Desired end effector pose in the world frame.
    Isometry3<double> pose{Isometry3<double>::Identity()};
    /// Bounding box for the end effector in the world frame.
    Vector3<double> pos_tol{Vector3<double>(0.005, 0.005, 0.005)};
    /// Max angle difference (in radians) between solved end effector's
    /// orientation and the desired.
    double rot_tol{0.05};
    /// Signals if orientation constraint is enabled.
    bool constrain_orientation{false};
```
instead of providing a custom default-constructor.

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkQxw6GPnLNQA8WwZfz:-KkQxw6GPnLNQA8WwZg-:bloq3xw) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L102)):*
> ```objc
>   bool SolveIk(const IkCartesianWaypoint& waypoint, const VectorX<double>& q0,
>                const VectorX<double>& q_nom,
>                const Vector3<double>& position_tol, double rot_tolerance,
> ```

FYI, differing parameters are named here: `('position_tol', 'rot_tolerance', 'ik_res')`, in definition: `('pos_tol', 'rot_tol', 'q_res')`

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkRAU8VEdIFsuAw0jJS:-KkRAU8VEdIFsuAw0jJT:b-1qo3wd) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L108)):*
> ```objc
>   std::default_random_engine rand_generator_;
>   std::unique_ptr<RigidBodyTree<double>> robot_{nullptr};
>   int end_effector_body_idx_;
> ```

BTW, need `{}` at the end.

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-4kpgcc1P8GcrKvd:-KkR-4kpgcc1P8GcrKve:bs9edok) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L4)):*
> ```cpp
> 
> #include "drake/common/drake_path.h"
> #include "drake/manipulation/planner/constraint_relaxing_ik.h"
> ```

FYI, this `#include` should be atop this file.

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-8fKDgICy3TIrZOG:-KkR-8fKDgICy3TIrZOH:b-qvue9e) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L21)):*
> ```cpp
> // N random samples are taken from the configuration space (q), and the
> // corresponding end effector poses are computed with forward kinematics.
> // We use inverse kinematics to try recover a set of joint angles that would
> ```

BTW, `to try recover` -> `to try to recover`

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-uQcuEvn-nVFCpUq:-KkR-uQcuEvn-nVFCpUr:br1lc0y) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L30)):*
> ```cpp
>       "iiwa14_polytope_collision.urdf";
>   const std::string kEndEffectorLinkName = "iiwa_link_ee";
>   std::default_random_engine rand_generator(1234);
> ```

`ConstraintRelaxingIk ik_planner` below includes `std::default_random_engine rand_generator_` which is initialized with the same magic number `1234`. Does it make sense to make a way to access that one and reuse that here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkRDUkjf07r1vZRVQQK:b-1tzs3z)*

**Comment by sammy-tri** [comment]
Review status: 12 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/manipulation/planner/BUILD, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkRDF4cqOLUUwNCCNoJ:-KkRI9_2-kO3epvBoyBG:bry2t3w) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/BUILD#L31)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, on a mac, the test times out when `ipopt` is used. It works well with `snopt` though.
</blockquote></details>

Replaced "snopt" tag with explanation about Mac timeouts.

---

*[drake/manipulation/planner/constraint_relaxing_ik.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR0LyV1jH21HHW0OBj:-KkRILSUvqE5R0SMAhRf:b-e350u8) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.cc#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, is it OK not to provide a way to pass a different random-seed?
</blockquote></details>

There were no users of the optional seed argument.  My thought was that it was simple enough to add the default argument back or provide a `SetRandomSeed()` which would allow users who really wanted to control the randomness to update the seed whenever.

---

*[drake/manipulation/planner/constraint_relaxing_ik.cc, line 190 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkQz7OQFYzSiJzKadN_:-KkRIg1RNRp_BgwILxiq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.cc#L190)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this if-statement+returns can be reduced to:
```c++
return (*info)[0] == 1;
```
</blockquote></details>

Done.

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 41 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR3c9K3CDVqdy0W1zO:-KkRJBmysxixyATIGDOV:bojbmqs) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, I think it is cleaner and more readable to use class member initialization above:
```c++
    /// Desired end effector pose in the world frame.
    Isometry3<double> pose{Isometry3<double>::Identity()};
    /// Bounding box for the end effector in the world frame.
    Vector3<double> pos_tol{Vector3<double>(0.005, 0.005, 0.005)};
    /// Max angle difference (in radians) between solved end effector's
    /// orientation and the desired.
    double rot_tol{0.05};
    /// Signals if orientation constraint is enabled.
    bool constrain_orientation{false};
```
instead of providing a custom default-constructor.
</blockquote></details>

Done.  (I wonder how long it will take me to get used to that.)

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkQxw6GPnLNQA8WwZfz:-KkRJbSS8Ui8L-NxgVv6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L102)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, differing parameters are named here: `('position_tol', 'rot_tolerance', 'ik_res')`, in definition: `('pos_tol', 'rot_tol', 'q_res')`
</blockquote></details>

Done.

---

*[drake/manipulation/planner/constraint_relaxing_ik.h, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkRAU8VEdIFsuAw0jJS:-KkRJkYNNOZ33t-iTuaE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/constraint_relaxing_ik.h#L108)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, need `{}` at the end.
</blockquote></details>

Done.

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-4kpgcc1P8GcrKvd:-KkRJno4HUd3t4RsP_Ks:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L4)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this `#include` should be atop this file.
</blockquote></details>

Done.

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-8fKDgICy3TIrZOG:-KkRJq6qQ2iFhzf3fYLj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L21)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `to try recover` -> `to try to recover`
</blockquote></details>

Done.

---

*[drake/manipulation/planner/test/constraint_relaxing_ik_test.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-KkR-uQcuEvn-nVFCpUq:-KkRJtJa0MH00h6NPI9f:b-ggfzzh) ([raw file](https://github.com/robotlocomotion/drake/blob/0aefd079eba62edf1d76901a3a0ec84122fa62bf/drake/manipulation/planner/test/constraint_relaxing_ik_test.cc#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`ConstraintRelaxingIk ik_planner` below includes `std::default_random_engine rand_generator_` which is initialized with the same magic number `1234`. Does it make sense to make a way to access that one and reuse that here? 
</blockquote></details>

I don't think it really matters.  The random generators are used for different purposes and the identical seed is basically coincidental.  (I did move the declaration close to its usage because I suspected it might improve readability)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 4 of 23 files at r1, 3 of 15 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkRLZSBAPYIFUrvVx_U:bg7igkv)*

**Comment by RussTedrake** [comment]
fwiw, i think disabling ipopt IS a valid bazel configuration.  (david german posted on slack a while back)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6127#-:-KkVeoPf-3cCfAkzb20G:b-5o3ccl)*

**Comment by jwnimmer-tri** [comment]
There is a flag you can set to disable Ipopt, but the flag is not published in the documentation, and is commented in the source as "here be dragons", so is not a _supported_ configuration.  Therefore, we don't need to worry about which tests pass or fail if the user turns it off.

**Comment by RussTedrake** [comment]
thanks for the clarification

**Pull request merged**
