### PR TITLE
fix libcurl installation

### PR DESCRIPTION
**Pull request by svenevs**
xargs was hiding the [Y/n] prompt

Refs: #16233.

Edit: Link to bug report on Slack [here](https://drakedevelopers.slack.com/archives/C270MN28G/p1640183163197600)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16280)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review and drake-ci testing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16280#-:-MrY4jg052xn35t5Gvrq:b43p8wf)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

+@sammy-tri for platform review

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16280#-:-MrY8Oc89ud_Lw5GXE1a:b-6n2219)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Didn't verify locally (well, I tested that the new version of `install_prereqs.sh` still runs) because I didn't want to deal with removing all of the packages which depend on `libcurl-dev` from my local machine.   :lgtm: based on reading slack convo + feature review + CI.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16280#-:-MrYSPVNAmJjVP3ddaKv:bo166ja)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),BetsyMcPhail (waiting on @svenevs)

**Pull request merged**
