### PR TITLE
Rewrite of MeshcatContactVisualizer

### PR DESCRIPTION
**Pull request by RussTedrake**
I looked more closely at the code because I hit a bug where the contact force IDs were incrementing unstably even though my scene was in steady state.  It caused flickering contact forces, and ground the performance in meshcat to a halt.

I found the current implementation to be unnecessarily complex and inefficient.  This PR cleans it up.

As a bonus, I've also added arrow heads to the cylinders, and changed the colors to match the contact forces in drake visualizer.  The overall result improves the visualization quite a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJasPyFE4SGYBftp28m:b-t5m2ic)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Comment by RussTedrake** [comment]
(forgot to include the new screenshot)
meshcat

**Comment by RussTedrake** [comment]
so nice!
meshcat
meshcat (1)

**Review by RussTedrake — COMMENTED** [review]
-@seancurtis-tri 
+@gizatt for feature review
+@pangtao22 for feature review
(realized i can/should distribute the load when i can!)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJazi3J7DyVKNvTuZSC:bpuh818)* status: LGTM missing from assignees gizatt,pangtao22, needs platform reviewer assigned (waiting on @gizatt and @pangtao22)

**Review by gizatt — COMMENTED** [review]
LGTM pending a nit. Much cleaner! I'm guessing it'll still have a performance bottleneck for lots of contacts, though? (See an inline comment.)

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJcU2yt9FCTGxQq5Y4N:b3vblbg)* status: 3 unresolved discussions, LGTM missing from assignees pangtao22,gizatt, needs platform reviewer assigned (waiting on @pangtao22 and @RussTedrake)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 588 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcRC2b5Mz1iWRd8BIq:-MJcRC2b5Mz1iWRd8BIr:b-oy0nxm) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L588)):*
> ```Python
>         if (not self._warned_pose_bundle_input_port_connected
>                 and self.get_input_port(0).HasValue(context)):
>             warnings.warn(
> ```

Shouldn't`_warned_pose_bundle_input_port_connected` get set to true after the warning is printed?
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 597 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcOug5ERjAuhFLMFSx:-MJcOug5ERjAuhFLMFSy:b-604be9) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L597)):*
> ```Python
>         #   self._contacts.
>         # If True, update the magnitude and location of
>         #   the _ContactState in self._contacts.
> ```

Nit -- this comment seems out of date since` _ContactState` no longer exists. Maybe a good place to mention that `_contacts` will be filled with pairs of IDs -- and maybe worth adding a line to the comment what `to_remove` is doing too? 
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 618 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcUV7K37-k0JnDnB2x:-MJcUV7K37-k0JnDnB2y:b-3krcgd) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L618)):*
> ```Python
>             cvis = vis[str(key)]
>             height = force_norm/self._contact_force_scale
>             cvis.set_object(meshcat.geometry.Cylinder(
> ```

So this is republishing the geometry of every cylinder every step -- I take it that that's performing fine for you?  The idea in the previous implementation, I think, was a belief that changing geometry is more expensive than changing transformation -- which is true for big meshes, but not sure about cylinders.

Anyway, fixing this bottleneck with msgpack upgrades / a C++ meshcat client / a transformation update on existing cylinders to alter their scale (if that really is faster) seems like a a doable fix downstream if this poses an issue.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210)* status: 1 unresolved discussion, LGTM missing from assignees pangtao22,gizatt, needs platform reviewer assigned (waiting on @gizatt and @pangtao22)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 588 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcRC2b5Mz1iWRd8BIq:-MJcfaM7EqryfssqJ2aw:b-fe0urp) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L588)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

Shouldn't`_warned_pose_bundle_input_port_connected` get set to true after the warning is printed?
</blockquote></details>

Done.  (yikes, thanks for catching that)
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 597 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcOug5ERjAuhFLMFSx:-MJcgKqaBrvYTcZ5VBAi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L597)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

Nit -- this comment seems out of date since` _ContactState` no longer exists. Maybe a good place to mention that `_contacts` will be filled with pairs of IDs -- and maybe worth adding a line to the comment what `to_remove` is doing too? 
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 618 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14210#-MJcUV7K37-k0JnDnB2x:-MJcglKdD9m2_EovZC9W:b-b4v1ul) ([raw file](https://github.com/robotlocomotion/drake/blob/a9f93fd2870cb1badcb057a9834843755d031a9c/bindings/pydrake/systems/meshcat_visualizer.py#L618)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

So this is republishing the geometry of every cylinder every step -- I take it that that's performing fine for you?  The idea in the previous implementation, I think, was a belief that changing geometry is more expensive than changing transformation -- which is true for big meshes, but not sure about cylinders.

Anyway, fixing this bottleneck with msgpack upgrades / a C++ meshcat client / a transformation update on existing cylinders to alter their scale (if that really is faster) seems like a a doable fix downstream if this poses an issue.
</blockquote></details>

Done.  Added a comment.

Your diagnosis is correct -- i think the performance seems fine (certainly on the publishing side, and I haven't seen any ill effects on the browser side, either).

**Review by RussTedrake — COMMENTED** [review]
+@soonho-tri for platform review, please.
-@pangtao22 for feature review.

greg your LGTM didn't go through yet (you need colons before and after it).  thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJciFJ3-oT9BxObRusJ:bhfr8pw)* status: 1 unresolved discussion, LGTM missing from assignees gizatt,soonho-tri(platform) (waiting on @gizatt and @soonho-tri)

**Review by gizatt — COMMENTED** [review]
:lgtm: !

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJcjL-K9OYkgLsokdNw:b593w5u)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14210#-:-MJcreCy--bE3F37Oywa:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),gizatt

**Pull request merged**
