### PR TITLE
[fem] FEM matrix math helpers improvements

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
* Avoid mixing `auto` with Eigen expression.
* Change DRAKE_DEMAND to DRAKE_ASSERT for tight inner loop calculations.

These changes lead to a ~4x performance improvement in constitutive calculations (profiled with the simple gripper demo).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for sole review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605#-:-MgsAtefBIYgCs_TS4t2:bbqfo5m)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: on the auto.

I don't know enough about this function to know whether `DEMAND` vs `ASSERT` is a meaningful difference in caution in this case.  If you're in doubt about that, you might want to add a second reviewer who is more familiar.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605#-:-MgsIxMpDuyhI2wl_0zk:bddncrk)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This is per element per newton iteration, so pretty much one of the tightest loops in the `fem` namespace so far. I remember @sherm1 and @amcastro-tri mentioned at some point that `DRAKE_DEMAND` can be undesirable in situations like this.

@amcastro-tri would you like to comment on whether this case fall under that category? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605#-:-MgsPlaRA4dJBOJu0l16:bfomp8)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
I can't we believe we let those `auto` go through review, good catch!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605#-:-Mgudtfr3fTgLdoDiTy2:b-e1rlv6)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgubzXG2aseatiFlZK-:-MgubzXG2aseatiFlZK0:b-605atb) ([raw file](https://github.com/robotlocomotion/drake/blob/eb42cccd916e7df44468016d25c2b593a355a13d/multibody/fixed_fem/dev/matrix_utilities.h#L40)):*
> ```objc
> void PolarDecompose(const Matrix3<T>& F, EigenPtr<Matrix3<T>> R,
>                     EigenPtr<Matrix3<T>> S) {
>   const Eigen::JacobiSVD<Matrix3<T>, Eigen::HouseholderQRPreconditioner> svd(
> ```

nit, I was confused here seeing an iterative method for such a small matrix, but I found in Eigen's docs for Eigen::BDCSVD this:
" For small matrices (<16), it is thus preferable to directly use JacobiSVD."

I think worth placing that information here.
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgucxBLDuZdWKAjPSXB:-MgucxBLDuZdWKAjPSXC:b-5156m8) ([raw file](https://github.com/robotlocomotion/drake/blob/eb42cccd916e7df44468016d25c2b593a355a13d/multibody/fixed_fem/dev/matrix_utilities.h#L99)):*
> ```objc
>   A.diagonal().array() += S.trace();
>   const T J = A.determinant();
>   DRAKE_ASSERT(J != 0);
> ```

humm.... I like using asserts in numeric checks when I have math guarantees that the assert won't trigger. In that case I place the assert to catch a bug caused by things like divergences, round-off errors, etc. 
In this case I don't think we have such guarantee? say for very large states of deformation? wouldn't it be worth to leave the DEMAND here? they are cheap anyway?

You code as is is consistent with the `@pre`. So I'd be satisfied if the precondition is checked somewhere else.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605)* status: 1 unresolved discussion (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgubzXG2aseatiFlZK-:-MgvICcpAqff4x9jP4EW:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/eb42cccd916e7df44468016d25c2b593a355a13d/multibody/fixed_fem/dev/matrix_utilities.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I was confused here seeing an iterative method for such a small matrix, but I found in Eigen's docs for Eigen::BDCSVD this:
" For small matrices (<16), it is thus preferable to directly use JacobiSVD."

I think worth placing that information here.
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgucxBLDuZdWKAjPSXB:-MgvGU3yBj-Iwvpfa2BR:b52o9sm) ([raw file](https://github.com/robotlocomotion/drake/blob/eb42cccd916e7df44468016d25c2b593a355a13d/multibody/fixed_fem/dev/matrix_utilities.h#L99)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

humm.... I like using asserts in numeric checks when I have math guarantees that the assert won't trigger. In that case I place the assert to catch a bug caused by things like divergences, round-off errors, etc. 
In this case I don't think we have such guarantee? say for very large states of deformation? wouldn't it be worth to leave the DEMAND here? they are cheap anyway?

You code as is is consistent with the `@pre`. So I'd be satisfied if the precondition is checked somewhere else.
</blockquote></details>

No we don't have that guarantee if the elements are inverted. More specifically, it happens when any two singular values of the deformation gradient add up to zero. I believe (not 100% sure) that the energy is not twice-differentiable on those manifolds. 

Switched back to `DRAKE_DEMAND`. Thanks for the input.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgvKxtv2uDUlGacUdNc:-MgvKxtw2lPs_ziEjjx-:br2vx8o) ([raw file](https://github.com/robotlocomotion/drake/blob/ba67398d55415fda0ee2c77e7619db15aee1fe25/-- commits#L5)):*
nit This commit message bullet is not accurate anymore.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review (waiting on @xuchenhan-tri)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15605#-MgvKxtv2uDUlGacUdNc:-MgvMsH_6fzxcI3WDLFn:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/ba67398d55415fda0ee2c77e7619db15aee1fe25/-- commits#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This commit message bullet is not accurate anymore.
</blockquote></details>

Done, thanks.

**Comment by amcastro-tri** [comment]
pardon my ignorance, I see Reviewable generated this "Commits" file looking object. What's the deal with this? are we supposed to review it as any other file?

**Review by xuchenhan-tri — COMMENTED** [review]
I think it is a new Reviewable feature that gives the reviewer and the author a channel to iterate on the commit messages.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15605#-:-Mgv_KCtAPqMtnvD_srD:bql96yc)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review

**Comment by amcastro-tri** [comment]
thanks, Yes, I just found the announcement here: https://changelog.reviewable.io/commit-message-reviewing-202214

**Pull request merged**
