### PR TITLE
Rename AbstractState to AbstractValues

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #5490.  @sherm1 for all review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5495)

### CODE REVIEW

**Comment by sherm1** [comment]
Thanks for the one-trick PR, David -- easy to review. A couple BTWs, then :lgtm:.

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/abstract_values.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-KfEqqeJLFeZpnbLsn_8:-KfEqqeJLFeZpnbLsn_9:b-24ncam) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d5661285184f359720f99b2513979dea25814d/drake/systems/framework/abstract_values.h#L23)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(AbstractValues)
> 
>   // Constructs an empty abstract state.
> ```

BTW META "abstract state" -> "abstract value container" ?
Several instances below of "state" and "AbstractState" that probably should change.

---

*[drake/systems/framework/parameters.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-KfEraFrSNwtJvvyGWo9:-KfEraFsa7fi2CDIZpmt:b-73od0p) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d5661285184f359720f99b2513979dea25814d/drake/systems/framework/parameters.h#L151)):*
> ```objc
>   // TODO(david-german-tri): Consider renaming AbstractState and DiscreteState
>   // to NumericValues and AbstractValues, since the abstraction is actually
>   // used in both State and Parameters.
> ```

BTW, can tone down this TODO now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-:-KfEsBFAhZdM7vHwytot:ba9amv3)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/abstract_values.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-KfEqqeJLFeZpnbLsn_8:-KfHRrH2IeyFXHKWSIDC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d5661285184f359720f99b2513979dea25814d/drake/systems/framework/abstract_values.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW META "abstract state" -> "abstract value container" ?
Several instances below of "state" and "AbstractState" that probably should change.
</blockquote></details>

Done.

---

*[drake/systems/framework/parameters.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-KfEraFrSNwtJvvyGWo9:-KfHRvI7V7xW_jQu2-dF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d5661285184f359720f99b2513979dea25814d/drake/systems/framework/parameters.h#L151)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, can tone down this TODO now!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5495)*

**Comment by sherm1** [comment]
One ignorable BTW.

---

Reviewed 3 of 28 files at r1, 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/abstract_values.h, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-KfHXw0FGNujnW8sRMlU:-KfHXw0FGNujnW8sRMlV:bqxykxg) ([raw file](https://github.com/robotlocomotion/drake/blob/64da0c94c1fc5740970b1ee39673d7e6a2a0e71b/drake/systems/framework/abstract_values.h#L26)):*
> ```objc
>   AbstractValues();
> 
>   /// Constructs a AbstractValues that owns the underlying data.
> ```

BTW, a->an (and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5495#-:-KfHY8DbCUBGEfb5283D:b-io6alh)*

**Comment by sherm1** [comment]
Reviewed 1 of 28 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5495)*

**Pull request merged**
