### PR TITLE
[py sensors] Hotfix ImageIo for XCode 15

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20611)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please.

:crossed_fingers:

**Comment by svenevs** [comment]
It's alive! https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release/4/consoleFull

Please don't launch ventura yet, that is not ready

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20611#-:-NkaXNuFCRZUOCQWuvld:b-9thol1)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
