### PR TITLE
Fix for issue #2055.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2124)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkwaKZYNtcbdDwrqON:-KFkwaKZYNtcbdDwrqOO:-115170807) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L30)):*
META: The 'ntests = 1' (with its corresponding for-loops that always run just one time) seems like baggage that serves no purpose to a naive reader.  Some explanation as to why it's in the code is in order.  (Perhaps you feel it's worth keeping to allow future developers to recreate the performance test reports?  In which case put that in a comment.)

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkxDT3w9g6Zv2BfJal:-KFkxDT3w9g6Zv2BfJam:-875849047) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L125)):*
Similarly, it is unclear why 'check = true' is useful in this code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFl730hiNflnIcLd5MR:-KFl730hiNflnIcLd5MS:-919594413) (no related file):*
Meta: should use github's magic words to close issue automatically upon merge of this PR: https://help.github.com/articles/closing-issues-via-commit-messages/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124)*

**Comment by maddog-tri** [comment]
Closes #2055 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkwaKZYNtcbdDwrqON:-KFoLqxnpPvjPKkPCD5A:-249486481) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L30)):*
My intent was to make the minimum amount of changes necessary to fulfill the requests in the original Issue.  The file has enough other serious issues (e.g., random irreproducible selection of test cases, use of non-GTest test primitives, testing only composition of functions with their inverses instead of individual functions, etc.) that it needs a complete overhaul.  Doing any more surgery to eliminate the "ntests" seemed like it would just complicate the commit.  I could add a bunch of comments, but the purpose of the baggage should be clear to anyone looking at the commit history, and the next person who looks at this file should be the person rewriting it from scratch anyway.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 125 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkxDT3w9g6Zv2BfJal:-KFoP5_X-2CabP40nLg0:1027710649) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L125)):*
Similarly, see response regarding "ntests".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-:-KFoPe-nAvr-D010cZ80:-1765673601)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkwaKZYNtcbdDwrqON:-KFoRblIf5aotjHn762s:409774245) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L30)):*
Wow. Very good points. I know at least one other unit test (compareRigidbodySystems) that also has random irreproducible selection of test cases. I created https://github.com/RobotLocomotion/drake/issues/2130 to track that fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-KFkwaKZYNtcbdDwrqON:-KFoaF4qWbmqkWj0Nv8F:-2133804362) ([raw file](https://github.com/robotlocomotion/drake/blob/095a6a4711f49806e50d647ff8fb54c494dff61d/drake/util/test/testDrakeGeometryUtil.cpp#L30)):*
I guess my own intuition was that a short TODO comment on the first instance of ntests would not be a burden, but I guess I'll leave it to author's discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2124#-:-KFoaxGkxlja2HXNL9Kr:1417088721)*

**Comment by jwnimmer-tri** [comment]
I'm calling drake005 a flake, since this is a C++ unit test and jenkins passed.  I'm override-merging to override the merged-with-master check as well.

**Pull request merged**
