### PR TITLE
Factor out build_components.bzl

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is non-functional; merely moving some text around.

The intent is to keep this content segregated for easier maintenance, such as automatically generating or cross-checking this listing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7195)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per rotation, please.

Sadly, github and reviewable are showing the text as add + delete, not moved.  If I view it locally in gitk, it shows a more appropriate diff (making it obvious that the list contents are identical).  You might consider using the same tool, or a similar one that shows a good diff.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7195#-:-KvhAAOH1U3Urxj-itp_:b-o2uxl1)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/build_components.bzl, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7195#-KvhDVwCq8uh8ILokH32:-KvhDVwCq8uh8ILokH33:b5j4quo) ([raw file](https://github.com/robotlocomotion/drake/blob/23822073cea899afaf5fe08e5a8bb7d57b3d770f/drake/build_components.bzl#L17)):*
> ```Python
> # except("//drake:drake_shared_library")'
> #
> # TODO(jwnimmer-tri) The list *should* be the output of the below query, but
> ```

BTW, `the *below* query` ->  `the *above* query`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7195#-:-KvhE1JTtFTrK9URMbyd:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7195)*

**Comment by jwnimmer-tri** [comment]
Some kind of CI flake... unlikely to be relevant, but no hurry either.
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
The rebuild passed, but the status didn't make it back to github again.  Using override-merge.

**Pull request merged**
