### PR TITLE
Remove the use of `testUtil` from within `drake/util` and `drake/examples`

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3277)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3277#-:-KR-BfjI4rPa5wpjz8hr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3277#-:-KR-WJ6GdV3GRPWNzmKn:bnfp4nl)*

**Pull request merged**
