### PR TITLE
Remove Travis CI configuration

### PR DESCRIPTION
**Pull request by jamiesnape**
OS X builds on Jenkins are now live.

### CODE REVIEW

**Comment by jamiesnape** [comment]
PTAL @david-german-tri @RussTedrake.

**Comment by david-german-tri** [comment]
:lgtm: (test-driving reviewable.io)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2007#-:-KEcSLGZu6n7U1xO7i0u:1007356770)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
I can't imagine what CI is going to tell us about this PR.  Any reason I shouldn't just merge it?

**Comment by jamiesnape** [comment]
No reason that I can think of.

**Pull request merged**
