### PR TITLE
Fix all cpplint runtime/explicit warnings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all cpplint runtime/explicit warnings, and enable the check for new code.

For now, all `explicit` tags that appeared to compile have been added.  Code authors can opt-in to implicit conversion by removing the keyword and adding a comment.

I suspect I will have to fight the build serves on this one for a while, so no need to review yet.  Let me get CI working first.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2191) &emsp; Multiple assignees:&emsp;@bmartin-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/bmartin-tri">bmartin-tri</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The drake005 and jenkins linux-matlab both agree that I've broken `examples/Acrobot/test/testCpp`, so I guess it's real.  The assertion line number indicates some polynomial-related change.  I will have to bisect tomorrow (and I guess add a C++ unit test).

I guess the fact that marking conversion operators `explicit` didn't result in a compile-time error wasn't enough to conclude that the code would behave the same.

**Comment by liangfok** [comment]
Just curious: Why wasn't this caught by CI prior to merge into master?

**Comment by jwnimmer-tri** [comment]
This code isn't on master yet.  This PR's CI experimental build failed.  I still need to figure out why before we review the code and merge it.

**Comment by liangfok** [comment]
Oh, OK, sorry for the confusion.

**Comment by jwnimmer-tri** [comment]
I will reopen once I repro locally and have this debugged.

**Comment by jwnimmer-tri** [comment]
After many hours of installing matlab and trying to get a debug + matlab build to run to completion, I have run out of my timebox.  I'll have to pick this up another day.

**Comment by liangfok** [comment]
Are you using Linux? If so, were you able to run Matlab? It segfaults upon launch on my Linux machine.

**Comment by jwnimmer-tri** [comment]
In a matlab + debug build now, the error appears to be thus:
```
351: MATLAB: /home/jwnimmer/jwnimmer-tri/drake/build/include/eigen3/Eigen/src/Core/CommaInitializer.h:114: Eigen::CommaInitializer<MatrixType>::~CommaInitializer() [with XprType = Eigen::Matrix<TrigPoly<double>, 2, 2, 0, 2, 2>]: Assertion `(m_row+m_currentBlockRows) == m_xpr.rows() && m_col == m_xpr.cols() && "Too few coefficients passed to comma initializer (operator<<)"' failed.
```

**Comment by jwnimmer-tri** [comment]
The problem is due to the addition of `explicit` to one or both of the following lines:
```
explicit Polynomial(const CoefficientType& scalar);
explicit TrigPoly(const CoefficientType& scalar) : poly(scalar) {}
```
Reverting those two changes is enough to make the test pass.

Per @ggould-tri, the implicit conversion in both cases is likely desirable, so I will restore both to be implicit and reopen the PR, instead of root-causing which of the two was at fault for the test failure.

**Comment by jwnimmer-tri** [comment]
Jenkis passed.  I think the drake005 build failure is spurious.

Ready for code review.

**Comment by jwnimmer-tri** [comment]
+@bmartin-tri Up for review.

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2191#-:-KGY6z-hak-cDO8HDlbq:88299481)*

**Comment by bmartin-tri** [comment]
:lgtm:

---

Reviewed 23 of 30 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2191#-:-KGY96dpMBm36fcIlO5F:1417088721)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2191#-:-KGY9w80CkGy_x-W0UxU:-356787046)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 23 of 30 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2191#-:-KGY_BYzi_fIL_V9-O2q:1417088721)*

**Pull request merged**
