### PR TITLE
Add functionality to merge one glTF file into another

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Given two nlohmann::json representations of a glTF file, this modifies one of the json trees to include the elements of the second gltf file. glTF files use internal references (via indices) to relate different elements. The indicies of the added glTF file all get offset to account for the elements in the first glTF file.

relates #19532  (PR 2 of 4)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@zachfang as feature reviewer.

+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYQ6UV8AOpbZF9wlT9v:bmwq1yh)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
By convention, this render engine using `internal_...` prefix on filenames with internal-only code, so that its easier for users to find what they are looking for (i.e., the factory).  It might be worth doing that rename now before review gets too far along?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYQ8EFO88Jg1my77BL6:bb6un1j)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by zachfang — COMMENTED** [review]
Checkpoint. My plan is to come back tonight to finish reviewing the .cc file and the tests before 10 PM EST.

> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYUcBTN4iLXs5MT3FmG:b-n4bpeo)* status: 5 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUQKMU5ToC64t1DpAO):*
nit. For consistency.



_Suggestion:_
```
glTF
```
___
*[`geometry/render_gltf_client/internal_merge_gltf.h` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUWS2WEZg9oDVxuX3y:-NYUWS2WEZg9oDVxuX3z:b8cvfhk) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.h#L31)):*
> ```objc
> 
>  All index references in j2's elements are updated based on the number of
>  indices already used by j1. */
> ```

BTW. As this comment applies to most of the `Merge*()`, do you think it makes sense to put that as a higher-level comment or just in `MergeGltf()` function?



_Code quote:_
```objc
 All index references in j2's elements are updated based on the number of
 indices already used by j1. */
```
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 274 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUZ9TgA1Q0otT1Rih-:-NYUZ9TgA1Q0otT1Rih0:b-o733xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.cc#L274)):*
> ```cpp
> }
> 
> void MergeGltf(json* j1, json&& j2) {
> ```

BTW. Should this be named `MergeGltfs` or `MergeGltfFiles` as the other functions?



_Code quote:_
```cpp
void MergeGltf
```
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 275 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUa9R08COP6TAOoaUi:-NYUa9R08COP6TAOoaUj:b52mdva) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.cc#L275)):*
> ```cpp
> 
> void MergeGltf(json* j1, json&& j2) {
>   (*j1)["asset"]["generator"] = "Drake gltf merger";
> ```

BTW. Maybe use `glTF` when referencing the format vs. the code or function names.



_Suggestion:_
```cpp
glTF
```
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUYQU89So8Zbcsnyci:-NYUYQU89So8Zbcsnycj:b-yki601) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.cc#L279)):*
> ```cpp
>   DRAKE_DEMAND(j2["asset"]["version"].get<string>() == "2.0");
> 
>   // Don't change the order. Because we mutate j1 as we go, we need to make sure
> ```

BTW. Maybe we can provide a pointer about the order of a glTF file here for reference? For example, I found [this one](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_002_BasicGltfStructure.md) very helpful when writing the glTF integration test.



_Code quote:_
```cpp
// Don't change the order.
```

**Review by zachfang — COMMENTED** [review]
I run out of time to finish reviewing the tests (I have fully finished the rest). I will continue tomorrow.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYW1qVI55OUdbNK-00R:b-xo5kff)* status: 8 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYVmB4O9JsRblaROAw1:-NYVmB4O9JsRblaROAw2:b-4nph4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L92)):*
> ```cpp
>    @param merge         The function that merges the named arrays. This is the
>                         device under test. */
>   static void BumpIndex(vector<MergeCase>* cases, const std::string& array,
> ```

nit. With `using std::string`, we can use `string` directly same as `vector`.



_Suggestion:_
```cpp
const string
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 466 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYVi7Q34F0sSBmXXY1D:-NYVi7Q34F0sSBmXXY1E:b8ryp14) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L466)):*
> ```cpp
> 
>   /* Save the merged glTF for inspection.
>    bazel-testlogs/geometry/render_gltf_client/merge_gltf_test/test.outputs/output.zip.
> ```

BTW. I assume the folder name will change due to the file renaming.



_Suggestion:_
```cpp
bazel-testlogs/geometry/render_gltf_client/internal_merge_gltf_test
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 472 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYVivQkBstNflEpPpzz:-NYVivQkBstNflEpPq--:b-hi7t5r) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L472)):*
> ```cpp
>     json& merged = target;
>     std::ofstream f(std::filesystem::path(dir) / "merged.gltf");
>     f << std::setw(2);
> ```

nit. Is this intentional to truncate the output file (if I understand correctly)?



_Code quote:_
```cpp
f << std::setw(2);
```

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: With the hierarchy of a glTF in mind, the .cc file is straightforward to understand.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYYfX-b-MN7M-JLEeLy:b-n4nspa)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYYap4AOmN9kIY_BJ_:-NYYYap4AOmN9kIY_BJa:b-q3ik77) (no related file):*
nit. I vaguely remember a PR I had to [use `R"""` for raw string literals](https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals). I wonder if we should use triple-quote for all the test JSON texts. 

___
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYFK1q-JNNsqwWVbaG:-NYYFK1q-JNNsqwWVbaH:bswm6me) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.cc#L62)):*
> ```cpp
> }
> 
> // Walks the json tree rooted at j_ptr looking for int-valued descendent keys
> ```

nit. We seem to add backticks around the args. (Also for `offset`.)



_Suggestion:_
```cpp
`j_ptr`
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 230 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYcTuQBkdA975qSMvv:-NYYcTuQBkdA975qSMvw:b-lze3kd) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L230)):*
> ```cpp
>         {.target = R"({"scenes":[{"name":"Scene", "nodes":[0]}],
>                       "nodes":[0, 1]})",
>          .source = R"({"scenes":[{"name":"Scene", "nodes":[0]}], "nodes":[0]})",
> ```

nit. Should we also test that, during merging, any `extras` from source (but not target as a previous test case) will be dropped?



_Suggestion:_
```cpp
.source = R"({"scenes":[{"name":"Scene", "nodes":[0], "extras": {"v":123}}], "nodes":[0]})",
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 245 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYctCF0mTSHFpom8-V:-NYYctCF0mTSHFpom8-W:b-d2ac20) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L245)):*
> ```cpp
>          .merge = merge},
>         {.target = R"({"scenes":[{"nodes":[0]}], "nodes":[0, 1]})",
>          .source = R"({"scenes":[{"nodes":[0, 2]}], "nodes":[0,1,2]})",
> ```

nit. Minor formatting.



_Suggestion:_
```cpp
"nodes":[0, 1, 2]
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYWITo2IlEF0Y7IYJ9:-NYYWITo2IlEF0Y7IYJA:b-tt6npt) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L327)):*
> ```cpp
>          .expected = R"([{"primitives":[{"mode":17,
>                                          "extras":{"v":2}}]}])",
>          .description = "Non-index primitive fields propagate.",
> ```

BTW. I wonder if it's worth testing whether the non-index fields are propagated AND remain the same value by providing some offsets from `.target`, i.e., we are not incrementing all the int-values.



_Suggestion:_
```cpp
        {.target = R"({"accessors":[0, 1]})",
         .source = R"({"meshes":[{"primitives":[{"mode":17,
                                                "extras":{"v":2}}]}]})",
         .array_name = "meshes",
         .expected = R"([{"primitives":[{"mode":17,
                                         "extras":{"v":2}}]}])",
         .description = "Non-index primitive fields propagate.",
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYYap4AOmN9kIY_BJ_:-NYYgchb87lgul1s8HVH:b-fju45k) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. I vaguely remember a PR I had to [use `R"""` for raw string literals](https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals). I wonder if we should use triple-quote for all the test JSON texts. 
</blockquote></details>

https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals
</blockquote></details>

I tried that and *hated* how much it bloated the test text. I'll put a note in there indicating that I know I'm breaking the styleguide.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ggould-tri for platform review come Monday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYb7S6bAAD397N1jkzk:bf2ftdq)* status: LGTM missing from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYYap4AOmN9kIY_BJ_:-NYb74h2-GEeX6vR373M:b-l4a9r7) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I tried that and *hated* how much it bloated the test text. I'll put a note in there indicating that I know I'm breaking the styleguide.
</blockquote></details>

Nevermind.  I tried it in the original version of the tests. In the newer, streamlined version the offense is significantly reduced. So, I've simply made it compliant.

___
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 274 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYUZ9TgA1Q0otT1Rih-:-NYb27s33KLiaGD6D0pr:b-sa3lnt) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/internal_merge_gltf.cc#L274)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Should this be named `MergeGltfs` or `MergeGltfFiles` as the other functions?
</blockquote></details>

In this case, I'm leaving it. This function doesn't actually have anything to do with *files*, but everything to do with glTF.
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYYWITo2IlEF0Y7IYJ9:-NYb45E07n8K0OPtEkWx:b-9wv1u3) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L327)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. I wonder if it's worth testing whether the non-index fields are propagated AND remain the same value by providing some offsets from `.target`, i.e., we are not incrementing all the int-values.
</blockquote></details>

A fine idea.
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 472 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYVivQkBstNflEpPpzz:-NYb4BG-CezQBP8TCVWc:bqaij7p) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a6e49203ef2f24c2ba8aa64526a75fece325770/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L472)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Is this intentional to truncate the output file (if I understand correctly)?
</blockquote></details>

It doesn't truncate, it pretty-prints. I've added documentation.

**Review by zachfang — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 2 of 6 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-:-NYsI7gpA_uSWYOstSH7:b-uwkowd)* status: 4 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYsBYmaAKNAr5OMVdV5:-NYsBYmaAKNAr5OMVdV6:bmgsf8l) (no related file):*
BTW:  The test suite here is a really excellent exemplar; for data semantics this brittle, it is exactly what is needed.  Bravo!

___
___
*[`geometry/render_gltf_client/internal_merge_gltf.cc` line 114 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYsECzdE1uYZbJmA-Yk:-NYsECzdE1uYZbJmA-Yl:b-yl6mqn) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4963c7cfeafd68ba0aeb25135cd17ef450b8eb3/geometry/render_gltf_client/internal_merge_gltf.cc#L114)):*
> ```cpp
>             // may be stored with j2's scene. Consider merging them as well.
>             // It's unclear what to do if two identically named scenes have the
>             // same extras property, but different values.
> ```

BTW:  Well, the obvious thing to do would be to fail fast with an error -- this is the only case where GlTF requires uniqueness and so is extra hazardous for a merge operation.
But I'm happy to live with a TODO for now.
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 61 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYsHdJq344LmBn06jzK:-NYsHdJq344LmBn06jzL:bqjlx1w) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4963c7cfeafd68ba0aeb25135cd17ef450b8eb3/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L61)):*
> ```cpp
>  is necessary to bump indices contained in the elements of the source array
>  which reference other *independent* arrays. Finally, in some cases, we
>  actually cull some attributes.
> ```

minor:  "In some cases" is worrying vague; consider a reassuring parenthetical since you've already noted these cases later.



_Suggestion:_
```cpp
 which reference other *independent* arrays. Finally, in some cases
 (noted explicitly in their test cases), we actually cull some attributes.
```
___
*[`geometry/render_gltf_client/test/internal_merge_gltf_test.cc` line 135 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYsA5h958qHgkjPdf1o:-NYsA5h958qHgkjPdf1p:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/a4963c7cfeafd68ba0aeb25135cd17ef450b8eb3/geometry/render_gltf_client/test/internal_merge_gltf_test.cc#L135)):*
> ```cpp
>   }
> 
>   /* Creates a test case where the elements of the array in question is copied
> ```

typo



_Suggestion:_
```cpp
the elements of the array in question are copied
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19642)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),zachfang

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19642#-NYsBYmaAKNAr5OMVdV5:-NYuDFX_B-pUuial5RXq:bcsx6e0) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  The test suite here is a really excellent exemplar; for data semantics this brittle, it is exactly what is needed.  Bravo!
</blockquote></details>

Well, that met my budget for this week's feel goods.  Thanks!

___

**Pull request merged**
