### PR TITLE
bazel: Enable downstream custom bindings for drake + pydrake

### LINKED ISSUE #8902: pydrake: Allow downstream Bazel projects to bind custom C++ code
Per [requests on Slack](https://drakedevelopers.slack.com/archives/C2CK4CWE7/p1527703761000648):

There should be a means to bind custom Drake-consuming C++ code in Bazel.

The long-term solution is to complete #5752 + #7294, the short-term solution would be to expose `drake_shared_library` for the intermediate code to consume, and try to generalize `pybind.bzl` to allow for non-Drake bindings to be used.

\cc @mposa @aespielberg @mpetersen94
(Will try to figure out other GitHub handles as well.)

As an aside, there is currently a PR in flight for CMake:
https://github.com/RobotLocomotion/drake-shambhala/pull/98

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8902

Downstream example / PR: https://github.com/RobotLocomotion/drake-shambhala/pull/105

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/install/libdrake/BUILD.bazel, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe-B-DpFWJRjHha2O:-LDqe-B-DpFWJRjHha2P:bmi4l11) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/install/libdrake/BUILD.bazel#L117)):*
> ```Python
>     # N.B. To pull in transitive `data` dependencies, we must list
>     # `libdrake.so` as a data target.
>     data = ["//tools/install/libdrake:libdrake.so"],
> ```

Unclear why the `//tools/install/libdrake:` package prefix must be listed here, since that's our own package.  Ditto above.

---

*[tools/install/libdrake/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe6WtCTguvTqUk9l5:-LDqe6WtCTguvTqUk9l6:brt706c) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/install/libdrake/BUILD.bazel#L118)):*
> ```Python
>     visibility = [
>         "//bindings:__subpackages__",
>         "//examples:__subpackages__",
> ```

Unclear why this has to be changed / should be changed.

Drake code in non-bindings, non-examples packages should link to static archives; code in those two packages should link to the shared library.

---

*[tools/skylark/drake_cc.bzl, line 617 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqcCK82s1cgNWKXHaD:-LDqcCK91EcRurjcENXT:b-xraqrl) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/drake_cc.bzl#L617)):*
> ```Python
>             # `srcs`.
>             # TODO(eric.cousineau): This may or may not be needed when Drake is
>             # being consumed as an external? Need to confirm.
> ```

On the TODO -- this doesn't make sense to me.  `drake_example_cc_binary` should not be used by an external project.

---

*[tools/skylark/pybind.bzl, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqfDTx3AvbAe_Anakw:-LDqfDTx3AvbAe_Anakx:b-lmwwz9) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L28)):*
> ```Python
> 
>     The defines the library with the given name and srcs.
>     """
> ```

If we are going to export this macro now, especially for third-party downstream developers, this needs more documentation -- what the params mean, how to fill them in correctly, maybe an example, etc.  It might also make sense to fail-fast if something wrong is given (e.g., malformed name).

(Or maybe it should stay private?)

---

*[tools/skylark/pybind.bzl, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqgYI241Zv1DhBxaBH:-LDqgYI241Zv1DhBxaBI:bmymgt1) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L149)):*
> ```Python
>         Additional Python import directories.
>     @param add_install (optional)
>         Add install targets.
> ```

This comment block is largely a duplicate of the above.

At worst, there should be a comment in each saying to keep them in sync.  Ideally, this would get factored to cite the other comment for the duplicated params.

---

*[tools/skylark/pybind.bzl, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqhUnO3Bh_i1YUmLKU:-LDqhUnO3Bh_i1YUmLKV:bwht4og) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L161)):*
> ```Python
>         cc_srcs = cc_srcs,
>         cc_deps = cc_deps + [
>             "//:drake_shared_library",
> ```

I don't understand why this spelling had to change.  This new label is documented as being for downstream projects, but this macro is for internal use.

---

*[tools/skylark/pybind.bzl, line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqheqp7XViQyO4yZ5r:-LDqheqp7XViQyO4yZ5s:bwht4og) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/skylark/pybind.bzl#L217)):*
> ```Python
>         deps = cc_deps + [
>             "//bindings/pydrake:pydrake_pybind",
>             "//tools/install/libdrake:drake_shared_library",
> ```

I don't understand why this spelling had to change.  This new label is documented as being for downstream projects, but this macro is for internal use.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/install/libdrake/BUILD.bazel, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe-B-DpFWJRjHha2O:-LDqxSAx3LYxmpxSebRN:b-8agdrn) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/install/libdrake/BUILD.bazel#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why the `//tools/install/libdrake:` package prefix must be listed here, since that's our own package.  Ditto above.
</blockquote></details>

D'oh.

---

*[tools/install/libdrake/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe6WtCTguvTqUk9l5:-LDqwS1A4nW4gGfeYVSd:b-a28wv3) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/install/libdrake/BUILD.bazel#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this has to be changed / should be changed.

Drake code in non-bindings, non-examples packages should link to static archives; code in those two packages should link to the shared library.
</blockquote></details>

If we already expose `//:drake_shared_library`, why not just use that target in Drake bindings and example packages, to potentially simplify things?

I can modify the comment for `//:drake_shared_library` to say it's for (a) installed binaries, (b) Python bindings, and (c) downstream code that may be bound in Python, regarding your other two comments.

---

*[tools/skylark/drake_cc.bzl, line 617 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqcCK82s1cgNWKXHaD:-LDqwr4G4v7aoyhmiRxm:btbstgm) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/drake_cc.bzl#L617)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On the TODO -- this doesn't make sense to me.  `drake_example_cc_binary` should not be used by an external project.
</blockquote></details>

Sorry, this ultimately was me trying to summarize #8908 - I had meant if a binary was consuming `drake_shared_library` as an external library, not that `drake_example_cc_binary` would be used downstream.

If/when #8909 merges, this will be irrelevant.

---

*[tools/skylark/pybind.bzl, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqfDTx3AvbAe_Anakw:-LDqxAZN1LuGdZBs0mAL:b7mpb91) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we are going to export this macro now, especially for third-party downstream developers, this needs more documentation -- what the params mean, how to fill them in correctly, maybe an example, etc.  It might also make sense to fail-fast if something wrong is given (e.g., malformed name).

(Or maybe it should stay private?)
</blockquote></details>

True, will make it private.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/install/libdrake/BUILD.bazel, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe-B-DpFWJRjHha2O:-LDs2reH05_eUU6_q7Gc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/install/libdrake/BUILD.bazel#L117)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

D'oh.
</blockquote></details>

Done.

---

*[tools/install/libdrake/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe6WtCTguvTqUk9l5:-LDs2rvS1j6rZHXl7e0o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/install/libdrake/BUILD.bazel#L118)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

If we already expose `//:drake_shared_library`, why not just use that target in Drake bindings and example packages, to potentially simplify things?

I can modify the comment for `//:drake_shared_library` to say it's for (a) installed binaries, (b) Python bindings, and (c) downstream code that may be bound in Python, regarding your other two comments.
</blockquote></details>

Done.

---

*[tools/skylark/pybind.bzl, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqfDTx3AvbAe_Anakw:-LDs2tYc7tl_pFOQ5wgy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

True, will make it private.
</blockquote></details>

Done.

---

*[tools/skylark/pybind.bzl, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqgYI241Zv1DhBxaBH:-LDs3ZZw9QG3JwXrQ1SO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment block is largely a duplicate of the above.

At worst, there should be a comment in each saying to keep them in sync.  Ideally, this would get factored to cite the other comment for the duplicated params.
</blockquote></details>

Done.

---

*[tools/skylark/pybind.bzl, line 161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqhUnO3Bh_i1YUmLKU:-LDs2wm7Ey-uF-DoFvGT:b5h8mwy) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/pybind.bzl#L161)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand why this spelling had to change.  This new label is documented as being for downstream projects, but this macro is for internal use.
</blockquote></details>

Done. Re-worded purpose of `//:drake_shared_library`

---

*[tools/skylark/pybind.bzl, line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqheqp7XViQyO4yZ5r:-LDs3-BTBjxnbDEfUD4l:b5h8mwy) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/skylark/pybind.bzl#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand why this spelling had to change.  This new label is documented as being for downstream projects, but this macro is for internal use.
</blockquote></details>

Done. Re-worded purpose of `//:drake_shared_library`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by jwnimmer-tri** [comment]
:lgtm: modulo discussions.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/libdrake/BUILD.bazel, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqe6WtCTguvTqUk9l5:-LDsgBb_1J05W8VFJw7b:b-hfi3x9) ([raw file](https://github.com/robotlocomotion/drake/blob/a44ea379a11abbba05fb531d12e8624003110952/tools/install/libdrake/BUILD.bazel#L118)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I guess I still don't see the point of having two names for the same thing, or this new name being any better (downstream code could have used the old name just fine), but I realize now (I didn't on the first read-through) that the new visibility here is `pkg` not `subpackages` as I'd originally misread, so at least there is only one _usable_ name for the item, so I guess there's no defect.  Withdrawn.

---

*[tools/skylark/drake_cc.bzl, line 617 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqcCK82s1cgNWKXHaD:-LDsfNbl1lw_9qq5YMGG:b-uslwa1) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/drake_cc.bzl#L617)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry, this ultimately was me trying to summarize #8908 - I had meant if a binary was consuming `drake_shared_library` as an external library, not that `drake_example_cc_binary` would be used downstream.

If/when #8909 merges, this will be irrelevant.
</blockquote></details>

The fact remains that the TODO still doesn't make sense to me when placed here within `drake_cc_example_binary` code.  Maybe there is a better home for the TODO?

---

*[tools/skylark/pybind.bzl, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDsh1G69qIGww7isxYo:-LDsh1G69qIGww7isxYp:b-s25s2j) ([raw file](https://github.com/robotlocomotion/drake/blob/835373e49a018782bc9912bde894a3abb89b8a00/tools/skylark/pybind.bzl#L59)):*
> ```Python
>     cc_binary_rule(
>         name = cc_so_target,
>         # This is how you tell Bazel to link in a shared library.
> ```

I just realized that this comment no longer makes sense, now that the `.so` isn't listed on the next line anymore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906#-:-LDshpX52vLirireyNlz:bkpiwgu)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/pybind.bzl, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDsh1G69qIGww7isxYo:-LEBGRLkAlsCmnqaOkEl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/835373e49a018782bc9912bde894a3abb89b8a00/tools/skylark/pybind.bzl#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I just realized that this comment no longer makes sense, now that the `.so` isn't listed on the next line anymore.
</blockquote></details>

Done.

---

*[tools/skylark/drake_cc.bzl, line 617 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LDqcCK82s1cgNWKXHaD:-LEBGSHsBVyWdO6HGPUQ:bdip3y5) ([raw file](https://github.com/robotlocomotion/drake/blob/6d0e3ce8b3b084b2a7c3417383c548338a3cd32f/tools/skylark/drake_cc.bzl#L617)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The fact remains that the TODO still doesn't make sense to me when placed here within `drake_cc_example_binary` code.  Maybe there is a better home for the TODO?
</blockquote></details>

Done. Removed since #8909 has merged - sorry that I hadn't clarified my wording, but I had intended to block this PR until that merged in, if it could merge in quickly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906#-:-LEBGaugEiQaY-MNPZGY:bz1t39v)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tools/install/libdrake/BUILD.bazel, line 115 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBIFsD1lfRyvXxLc72:-LEBIFsD1lfRyvXxLc73:bqf5mtr) ([raw file](https://github.com/robotlocomotion/drake/blob/c02476234c4497b7ab2289f33649b2927b28889c/tools/install/libdrake/BUILD.bazel#L115)):*
> ```Python
> #
> # TODO(eric.cousineau) This target should be merged into `//:drake_shared_library`
> # to minimize name duplication.
> ```

I think this PR's current proposal is superior to relocating this rule's logic to the top-level BUILD file.  The correctness of its detailed attribute lists are much more apparent when read in the context of this BUILD file, versus putting it off an an island in the top-level BUILD file.

(Also, this line is too long, and probably will break momentarily in CI.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/libdrake/BUILD.bazel, line 115 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBIFsD1lfRyvXxLc72:-LEBKJ10Bwkj2c9S-9eF:b-vl9ibh) ([raw file](https://github.com/robotlocomotion/drake/blob/c02476234c4497b7ab2289f33649b2927b28889c/tools/install/libdrake/BUILD.bazel#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this PR's current proposal is superior to relocating this rule's logic to the top-level BUILD file.  The correctness of its detailed attribute lists are much more apparent when read in the context of this BUILD file, versus putting it off an an island in the top-level BUILD file.

(Also, this line is too long, and probably will break momentarily in CI.)
</blockquote></details>

Done. (Also, ensured targets are by default private in this package.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/install/libdrake/BUILD.bazel, line 65 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLhBACnVnNtMXbWRb:-LEBLhBACnVnNtMXbWRc:b-tbnp03) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L65)):*
> ```Python
> cc_library(
>     name = "gurobi_deps",
>     visibility = [],
> ```

Vestigial.

---

*[tools/install/libdrake/BUILD.bazel, line 75 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLiwXD5W82T43j5xE:-LEBLiwXD5W82T43j5xF:b-tbnp03) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L75)):*
> ```Python
> cc_library(
>     name = "mosek_deps",
>     visibility = [],
> ```

Vestigial.

---

*[tools/install/libdrake/BUILD.bazel, line 85 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLjHb-26hzwPPSw-J:-LEBLjHb-26hzwPPSw-K:b-tbnp03) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L85)):*
> ```Python
> cc_library(
>     name = "vtk_deps",
>     visibility = [],
> ```

Vestigial.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install/libdrake/BUILD.bazel, line 65 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLhBACnVnNtMXbWRb:-LEBMI_WAFG4O_E-wha9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Vestigial.
</blockquote></details>

Done.

---

*[tools/install/libdrake/BUILD.bazel, line 75 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLiwXD5W82T43j5xE:-LEBMIpC4Oibp5iGrZQ7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Vestigial.
</blockquote></details>

Done.

---

*[tools/install/libdrake/BUILD.bazel, line 85 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8906#-LEBLjHb-26hzwPPSw-J:-LEBMJ2R8RHHGA1rAgLG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/844777f5a7bd9fa9110eb183a1f6bbd2075a7ed7/tools/install/libdrake/BUILD.bazel#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Vestigial.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8906)*

**Pull request merged**
