### PR TITLE
Updating ign-math

### PR DESCRIPTION
**Pull request by m-chaturvedi**
re https://github.com/RobotLocomotion/drake/issues/5956#issuecomment-301345974

@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6112)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6112#-:-KkHNsSrepkMnju4WW6A:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Pull request merged**
