### PR TITLE
Update dReal version

### PR DESCRIPTION
**Pull request by soonho-tri**
Use 4.18.02.2 which provide supports for if-then-else expressions.

The new `.deb` is available at https://dl.bintray.com/dreal/dreal/dreal_4.18.02.2_amd64.deb.

/cc @jamiesnape

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8039)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Can you keep the previous version in the `PKG_CONFIG_PATH` as well (with lower priority) for now. Makes life a little easier switching the images over.

**Comment by soonho-tri** [comment]
@jamiesnape , sure. I'll update the PR shortly.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8039#-:-L5A26CfDc4t_NlcS2u5:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8039#-:-L5A5Qe_G1BHPwNkPG-K:b4fwciw)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8039#-:-L5A8Niz6ntZfuKqKo7D:bnfp4nl)*

**Pull request merged**
