### PR TITLE
Revert #2440

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Dear @ggould-tri,

The oncall build cop, @mwoehlke-kitware, believes that your PR #2440 may have broken Drake's continuous integration build [1]. It is possible to break the build even if your PR passed continuous integration on presubmit, because additional platforms and tests are built in postsubmit.

The specific build failures under investigation are:
- https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab/270/changes
- https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab/16/changes

(Specifically, the examples/Atlas/test/runAtlasWalkingDownStairs test is newly failing.)

Therefore, the build cop has created this revert PR and started a complete postsubmit build to determine whether your PR was in fact the cause of the problem. If that build passes, this revert PR will be merged 60 minutes from now. You can then fix the problem at your leisure, and send a new PR to reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be reverted, please review and LGTM this PR. This allows the build cop to merge without waiting for CI results.

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2458)

### CODE REVIEW

**Comment by ggould-tri** [comment]
https://github.com/RobotLocomotion/drake/pull/2459 resolves this issue by
commenting out the failing test (this test was missed from #2432)

On Thu, May 26, 2016 at 12:28 PM, Matthew Woehlke <notifications@github.com>
wrote:

> Assigned #2458 <https://github.com/RobotLocomotion/drake/pull/2458> to
> @ggould-tri <https://github.com/ggould-tri>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/2458#event-673411488>
>



-- 
Grant Gould
Toyota Research Institute

**Comment by mwoehlke-kitware** [comment]
If that is the right approach, can you nudge someone to get #2459 merged? If yes, and it fixes the CI, I'll discard this.

**Comment by mwoehlke-kitware** [comment]
Interestingly, prior to #2440, the test seemed to be passing consistently, and is failing consistently after @2440... (see also https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/55/)

**Comment by ggould-tri** [comment]
Yes, the InstantaneousQp solver used by atlas tests has some lingering
memory corruption issue that is exercised by (we suspect) the increase in
the size of Polynomial's vtable, so adding any method to Polynomial breaks
this test.  As we don't have anyone right now who can deep-dive into fixing
the solver, we have decided to disable Atlas/Valkyrie tests that hit this
issue.

On Thu, May 26, 2016 at 1:36 PM, Matthew Woehlke <notifications@github.com>
wrote:

> Interestingly, prior to #2440
> <https://github.com/RobotLocomotion/drake/pull/2440>, the test seemed to
> be passing consistently, and is failing consistently after @2440... (see
> also
> https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/55/
> )
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/2458#issuecomment-221940815>
>



-- 
Grant Gould
Toyota Research Institute

**Comment by ggould-tri** [comment]
#2459 is landed.  We will see if it fixes continuous.

**Comment by ggould-tri** [comment]
70eda3d7137959177d6e1aca77cd5de6d85439db appears to have passed continuous.

**Comment by mwoehlke-kitware** [comment]
Fixed by #2459 :
- https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab/275/
- https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab/20/

**Pull request closed without merging**
