### PR TITLE
Update automotive directory namespace

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3447)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-:-KRe9PgBxoCrp1QxKAiM:b-a66qxi)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-:-KReAQWwBa1rC2xV7eGG:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by sammy-tri** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/idm_with_trajectory_agent.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReCOX9rldz3QKitgDF:-KReCOX9rldz3QKitgDG:b-m1bp2t) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/idm_with_trajectory_agent.cc#L10)):*
> ```cpp
> // These instantiations must match the API documentation in
> // idm_with_trajectory_agent.h.
> template class DRAKEAUTOMOTIVE_EXPORT IdmWithTrajectoryAgent<double>;
> ```

Are we missing an include-what-you-use for this macro?

---

*[drake/automotive/test/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReDBVGf4so1Re9goAd:-KReDBVGf4so1Re9goAe:bnlwvr7) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/test/CMakeLists.txt#L45)):*
> ```CMake
>   
>   add_executable(trajectory_car_test trajectory_car_test.cc)
>   target_link_libraries(trajectory_car_test ${GTEST_BOTH_LIBRARIES} drakeAutomotive)
> ```

FYI long line (if we're enforcing this in CMakeLists.txt)

---

*[drake/automotive/test/CMakeLists.txt, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReDGCLRxVhdFlswnYt:-KReDGCLRxVhdFlswnYu:bnlwvr7) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/test/CMakeLists.txt#L49)):*
> ```CMake
> 
>   add_executable(car_simulation_test car_simulation_test.cc)
>   target_link_libraries(car_simulation_test ${GTEST_BOTH_LIBRARIES} drakeAutomotive)
> ```

FYI long line (if we're enforcing this in CMakeLists.txt)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3447)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 47 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/idm_with_trajectory_agent.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReCOX9rldz3QKitgDF:-KReNkyxe7P9gjUief2z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/idm_with_trajectory_agent.cc#L10)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Are we missing an include-what-you-use for this macro?
</details>
Done.

---

*[drake/automotive/test/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReDBVGf4so1Re9goAd:-KReNmqgRpQwbpHVz8Th:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/test/CMakeLists.txt#L45)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI long line (if we're enforcing this in CMakeLists.txt)
</details>
Done.

---

*[drake/automotive/test/CMakeLists.txt, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-KReDGCLRxVhdFlswnYt:-KReNn4TxkqqihyUN2k7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a1b539329120896247fdf58eb465f055e65e4bb6/drake/automotive/test/CMakeLists.txt#L49)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI long line (if we're enforcing this in CMakeLists.txt)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-:-KReNoHftV0o1MUPy22O:b-83330m)*

**Comment by sammy-tri** [comment]
:lgtm:  (pending Jenkins)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3447#-:-KReNyYjts64r5_1ZIXm:b-qdz1jh)*

**Pull request merged**
