### PR TITLE
Rename FemElasticity to ElasticityElement.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
There is a class renaming that I promised but forgot to do in PR#14263 and here it is. Better late than never.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307#-:-MLj5uTR6qWD62VLxIAz:b-mzw7u3)* status: needs at least one assigned reviewer

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307#-:-MLj6_s39Qp_m_A9_LkX:b5xll3r)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307#-:-MLnXri577gxE0vuoc1L:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307#-:-MLngeWx127NiSyScMAS:buasbda)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:. Needs a manual rebase to master to resolve conflicts.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14307#-:-MLngtvm-9KcULqdZq1E:bt0gykj)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform), exempt from platform review

**Pull request merged**
