### PR TITLE
[pydrake] Add dynamic_attr support to cpp_template_pybind

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #22022.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22037)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22037#-:-O9FvRKy3zuPnYofnL24:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; test coverage question.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22037#-:-O9G24wn4VSagxMUzvX5:b-y2eqgo)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22037#-O9G4_rs2Z_kZfr0-yBU:-O9G4_rs2Z_kZfr0-yBV:bb741km) (no related file):*
I am surprised not to see test coverage of an actual python use of a dynamic attr on a bound class.  Is that because that will be forthcoming in the next PR of the train?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22037)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22037#-O9G4_rs2Z_kZfr0-yBU:-O9G5eOK5ElICoyBXRUZ:b-k72mto) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I am surprised not to see test coverage of an actual python use of a dynamic attr on a bound class.  Is that because that will be forthcoming in the next PR of the train?
</blockquote></details>

The existing test case _does_ set a dynamic attr in python.  (The string literal with code is passed to `eval`.)  Or did you mean that we only set an attribute, but not get it?

I think its fine to assume that `py::dynamic_attr()` is implemented correctly in pybind11, so the only thing the test case needs to prove is that we asked pybind11 to enable it, which the current test does prove.  (If I bug the implementation and don't pass along the dynamic_attr request, the test fails.)

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22037)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22037#-O9G4_rs2Z_kZfr0-yBU:-O9GDpRF-iJi2NWPVImx:b-16c360) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Yes, I had meant testing it from python code; `py::dynamic_attr()` is of course correctly implemented in pybind11 but I cannot tell from inspection that we have used it correctly and so would have tested in a `.py` file.  But you have better knowledge of the bindings than I do so I will defer to your experience.
</blockquote></details>

Okay.  I am happy with this somewhat basic smoke test.  If this new feature doesn't work, then tons of new bindings updates will crash in their unit tests.  It won't go unnoticed, just maybe not specifically pointed out by a narrow unit test.

___

**Pull request merged**
