### PR TITLE
show_model: Use MultibodyPlant. Add meshcat visualization

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Needs a rebase for pydrake formatter changes.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI can I place an upvote for working on this PR again to reach master?  At least, having the inspector / show_model code using MBP instead of RBT would be a nice win, even if meshcat is later.

**Comment by EricCousineau-TRI** [comment]
Yup! Sorry for letting it languish.

**Comment by EricCousineau-TRI** [comment]
___
*[manipulation/util/geometry_inspector.py, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10012#-LTTUKqSE9D19eRF2O_f:-LTTYU-l4XqsbeS7gqma:b4qk185) ([raw file](https://github.com/robotlocomotion/drake/blob/e29e641ff476c37759d67ffb09d97109ded34f0e/manipulation/util/geometry_inspector.py#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand why there is a new requirement in this PR that the filename is an absolute path?  That seems strictly worse -- an extra burden on the user, with no positive value.

(If this check ends up being removed, then both the `${PWD}` change to the docstring, and the unit test's use of abspath, should also be removed.)
</blockquote></details>

Because `bazel run` makes relative paths awkward, especially if you don't declare model as `data` prereqs; however, I'll just reword the examples to encourage using this via `bazel-bin` and add a note about absolute paths. Will update once I do the rewording.

**Pull request merged**
