### PR TITLE
Additionally nerf AtlasWalkingDownStairs

### PR DESCRIPTION
**Pull request by ggould-tri**
Required by #2440, per #2458

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2459)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> #### Additionally nerf AtlasWalkingDownStairs
> 
> Required by #2440, per #2458
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2459#-:-KIhx7oqz5Ib9Nz4OGyS:1417088721)*

**Comment by sherm1** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2459#-:-KIhzVGuG41zgUzj8Pqp:1417088721)*

**Comment by mwoehlke-kitware** [comment]
jenkins: retest this please

**Comment by mwoehlke-kitware** [comment]
AtlasWalkingHeelSupport also seems to be failing intermittently...

**Pull request merged**
