### PR TITLE
Added a subclass of DepthSensor with dropout

### PR DESCRIPTION
**Pull request by nikos-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6314)

### CODE REVIEW

**Comment by nikos-tri** [comment]
+@liangfok

**Comment by nikos-tri** [comment]
+@liangfok feature review please

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmEQ5c8k0bW36450Sxy:bgx298j) (no related file):*
I had previously suggested implementing drop-outs as a filter system cascaded after the DepthSensor, instead of a subclass.  This implementation appears to make no advantage of being a subclass -- the only thing it uses from the parent is calling the DoCalcOutput, which is as-well available to an input port if this were a filter.  What is the thought process behind making it a subclass instead of a filter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by nikos-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmS2pyodEBaw-T9Ofln:brhxh6x) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I had previously suggested implementing drop-outs as a filter system cascaded after the DepthSensor, instead of a subclass.  This implementation appears to make no advantage of being a subclass -- the only thing it uses from the parent is calling the DoCalcOutput, which is as-well available to an input port if this were a filter.  What is the thought process behind making it a subclass instead of a filter?
</blockquote></details>

This initial version doesn't take advantage of being a subclass because it simply drops the entire frame. However, the plan is to refine it so that it eventually drops out part of the world. For this, it needs to have access to the RigidBodyTree, because the goal is to experiment with things in the actual world appearing/disappearing instead of simply adding noise to the depth measurements. In the cascaded layout, this wouldn't be possible, since the filter would only be seeing the depth measurements and not know how those measurements correspond to actual things. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmS50LVGmFOEyq4csmz:b-sg33j2) (no related file):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

This initial version doesn't take advantage of being a subclass because it simply drops the entire frame. However, the plan is to refine it so that it eventually drops out part of the world. For this, it needs to have access to the RigidBodyTree, because the goal is to experiment with things in the actual world appearing/disappearing instead of simply adding noise to the depth measurements. In the cascaded layout, this wouldn't be possible, since the filter would only be seeing the depth measurements and not know how those measurements correspond to actual things. 
</blockquote></details>

For that second case, a dropout filter on the poses cascaded _prior to_ this sensor would work, I think?  It still doesn't need to subclass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by liangfok** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmXWRw_cmM5SL6Hd72z:b-6i3skj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For that second case, a dropout filter on the poses cascaded _prior to_ this sensor would work, I think?  It still doesn't need to subclass.
</blockquote></details>

Modifying the input does not seem easy since I doubt  [RigidBodyTree::doKinematics()](http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html#aabdcd62794d8bb261b3fa4c836dce46e) supports invalid`q` values.

I think a downstream filter is preferable for increased code clarity. [DepthSensor](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1sensors_1_1_depth_sensor.html) maintains a `const` reference to a `RigidBodyTree`. Couldn't a downstream filter do the same and thus access the same tree? Would this be sufficient for it to selectively corrupt depth measurements belonging to certain objects in the world?

I'm curious how you will obtain a correspondence between depth measurements and objects since [RigidBodyTree::collisionRaycase()](http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html#a3b8516e2261e850c3f3086d252ef3ab6) does not provide this information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmXfDZvmgkIBPL4SabI:b1en9pt) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Modifying the input does not seem easy since I doubt  [RigidBodyTree::doKinematics()](http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html#aabdcd62794d8bb261b3fa4c836dce46e) supports invalid`q` values.

I think a downstream filter is preferable for increased code clarity. [DepthSensor](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1sensors_1_1_depth_sensor.html) maintains a `const` reference to a `RigidBodyTree`. Couldn't a downstream filter do the same and thus access the same tree? Would this be sufficient for it to selectively corrupt depth measurements belonging to certain objects in the world?

I'm curious how you will obtain a correspondence between depth measurements and objects since [RigidBodyTree::collisionRaycase()](http://drake.mit.edu/doxygen_cxx/class_rigid_body_tree.html#a3b8516e2261e850c3f3086d252ef3ab6) does not provide this information.
</blockquote></details>

You don't use "invalid" q values, you just move the object really far away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by liangfok** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-KmEQ5c8k0bW36450Sxx:-KmXhovh45p3N7snZnRW:bogyd5k) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You don't use "invalid" q values, you just move the object really far away.
</blockquote></details>

I suppose that'll work but only for objects that are not fixed to the world.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314)*

**Comment by nikos-tri** [comment]
Thanks for the feedback. I will incorporate this feedback in a revised version, but it will be a while. Currently I am working on a simpler demo with the automotive simulator.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
-@liangfok for now. Please feel free to tag me again once this PR is ready for another round of review.

---

Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6314#-:-KuKdDeONuKJee3-WM9T:b-sbdw0m)*

**Comment by jwnimmer-tri** [comment]
@nikos-tri This PR seems to be stale?  Consider closing it until it's going to be worked again.

**Pull request closed without merging**
