### PR TITLE
Add a door hinge force element

### PR DESCRIPTION
**Pull request by huihuaTRI**
See the issue: https://github.com/RobotLocomotion/drake/issues/12759.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12812)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sherm1 @amcastro-tri is it correct to place this bespoke new ForceElement in the `multibody/tree` folder?

**Comment by jwnimmer-tri** [comment]
FYI See https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github for the conventional way to attribute commits to an additional author ("Co-authored-by: ").

**Comment by jwnimmer-tri** [comment]
I am a little skeptical that the hinge calibration tool is general enough to live in the tutorials folder; it's not exactly introductory material.  Did the reviewers discuss this already?  Could it instead live adjacent to the hinge code, maybe even in the `drake/multibody/tree/test` folder?

Also check https://github.com/RobotLocomotion/drake/blob/2d4887435434b096ba23249fd39f195b97b7efa5/tools/jupyter/README.md#committing-to-git and make sure the notebook outputs are cleared in git.

**Comment by jwnimmer-tri** [comment]
> IIRC we preferred a different location but there was a restriction imposed by current infrastructure regarding automatic uploading of notebooks?

Please open an issue describing the problem, so that Eric or Jamie or I can fix the infrastructure and allow you to place the file in your more sensible, desired location in the future.

**Comment by sherm1** [comment]
>> IIRC we preferred a different location but there was a restriction imposed by current infrastructure regarding automatic uploading of notebooks?

> Please open an issue describing the problem, so that Eric or Jamie or I can fix the infrastructure and allow you to place the file in your desired location in the future.

@hongkai-dai or @huihuaTRI can you file an issue explaining why we couldn't put the Jupyter notebook next to the DoorHInge implementation?

**Comment by jwnimmer-tri** [comment]
Also the commit message should always have a blank line after the subject line.

**Pull request merged**
