### PR TITLE
Adding CoM methods from RBT to MBT/MBP

### PR DESCRIPTION
**Pull request by yangwill**
The CalcCenterOfMassJacobian and CalcCenterOfMassJacobianDotTimesV methods from RigidBodyTree were not migrated over to MBP and I would like to have access to them in MBP.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12839)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review (or else delegate), please.

**Comment by sherm1** [comment]
Assigned to @mitiguy per f2f  to work out proper naming and signatures for consistency with the other Jacobian methods.

**Comment by yangwill** [comment]
Ready for re-review

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/plant/multibody_plant.h, line 2707 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12839#-M3foB3F-DGiPav_Yj9G:-M3lXWecDAjWx1uV5jjV:b-4pi69a) ([raw file](https://github.com/robotlocomotion/drake/blob/c1f29607e5519f7c4245804c2b2e05e817f44981/multibody/plant/multibody_plant.h#L2707)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

By "best way" I didn't mean "best of all possible worlds" but rather "best given the rest of MultibodyPlant". I agree that ModelInstance is a crude way to make lists of bodies, but that seems most consistent with the current API. It would be worth discussing something more flexible along the lines of Sean's collision exclusion lists. Do we have use cases where ModelInstance wouldn't be enough here?
</blockquote></details>

Will make an issue!

**Comment by mitiguy** [comment]
@yangwill  Thank you for your excellent work on this PR.
It is much appreciated.
- Paul

**Comment by jwnimmer-tri** [comment]
@yangwill Also FYI we have https://drake.mit.edu/credits.html list; you are welcome to open a PR adding your name to https://github.com/RobotLocomotion/drake/blob/master/doc/credits.rst if you'd like to be listed.

**Pull request merged**
