### PR TITLE
RenderEngineGl supports in-memory meshes

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O7fRt3R2U9VvdfP3ip1:b-bpi9p7)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O7jYwr8EX5uiLnaLGbY:bnfp4nl)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 671 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7fubx7EAAhM2fLSSy3:-O7fubx7EAAhM2fLSSy4:b-drez5h) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/internal_render_engine_gl.cc#L671)):*
> ```cpp
>   std::string prefix;
>   if (mesh_source.is_in_memory()) {
>     // TODO(SeanCurtis-TRI): This is a *bit* tricky. I have an in-memory mesh
> ```

I've read this TODO a few times, but I'm still not sure what you are getting at. Is what you did here simply weakening the contract of this function to be

"// Given a **mesh source** (e.g., of a mesh), this produces a string that we use in
  // our maps to guarantee we only load the **source** once."
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1422 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7fvW-T-XROZ9zWFD8c:-O7fvW-UDf7AWUu0jIvO:b-22fa7h) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/internal_render_engine_gl.cc#L1422)):*
> ```cpp
>                                      const RegistrationData& data) {
>     // We need this available for other methods in the callstack.
>     source_ = &mesh_source;
> ```

nit, this looks like a styleguide violation to me, holding on to the const reference.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 883 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7jX4otAMZ-INx2NjEj:-O7jX4otAMZ-INx2NjEk:b-5h75jo) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb9fd713007bc8cce0df2cf7a52c102bac1a05ef/geometry/render_gl/internal_render_engine_gl.cc#L883)):*
> ```cpp
>   const std::string file_key = GetPathKey(mesh_source, is_convex);
>   // If mesh_source is in memory, we want to pass an *empty* filename to
>   // MaybeMakeMeshFallbackmaterial() to avoid looking for foo.png.
> ```

nit, Is this behavior consistent with the contract of `MaybeMakeMeshFallbackMaterial`? I read its documentation, and it seems to require a "valid mesh". Is the documentation there out of date?



_Code quote:_
```cpp
  // If mesh_source is in memory, we want to pass an *empty* filename to
  // MaybeMakeMeshFallbackmaterial() to avoid looking for foo.png.
```
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1529 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7jVmY--RsKKBAn8NhO:-O7jVmY--RsKKBAn8NhP:b2a8xhh) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb9fd713007bc8cce0df2cf7a52c102bac1a05ef/geometry/render_gl/internal_render_engine_gl.cc#L1529)):*
> ```cpp
>                   if (err) {
>                     *err += fmt::format(
>                         "Error reading in-memory glTF file '{}'\n", filepath);
> ```

BTW, why doesn't this error message get the same treatment as the other missing files above get, which is more specific and indicate "something is missing".
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 1276 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7ftGfD24UyOysKUsKH:-O7ftGfD24UyOysKUsKI:b6pxmhw) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/test/internal_render_engine_gl_test.cc#L1276)):*
> ```cpp
> 
>   // TODO(SeanCurtis-TRI): This is a LIE! This single gltf does not have both
>   // kind of URIs. Make one that is.
> ```

BTW, why not doing that right now?



_Code quote:_
```cpp
  // TODO(SeanCurtis-TRI): This is a LIE! This single gltf does not have both
  // kind of URIs. Make one that is.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks.

+@jwnimmer-tri for platform review, come Monday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O7oQLfo4GsTqQZU5bda:b-aiye50)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 671 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7fubx7EAAhM2fLSSy3:-O7oIYrPCRc4oaUoGpZL:byxzyxp) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/internal_render_engine_gl.cc#L671)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I've read this TODO a few times, but I'm still not sure what you are getting at. Is what you did here simply weakening the contract of this function to be

"// Given a **mesh source** (e.g., of a mesh), this produces a string that we use in
  // our maps to guarantee we only load the **source** once."
</blockquote></details>

I've radically rephrased it, acknowledging a theoretical problem, a sense of how one might resolve it, and a reason why we're not doing so now.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1422 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7fvW-T-XROZ9zWFD8c:-O7oFoZmD9EDPz_MijBb:b7c4xh7) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/internal_render_engine_gl.cc#L1422)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this looks like a styleguide violation to me, holding on to the const reference.
</blockquote></details>

I can make strong arguments for why it isn't. 

However, changing the code slightly (with a slightly extended comment), worked better.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 883 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7jX4otAMZ-INx2NjEj:-O7oGc_dCkYMn7nUVOnY:bodejo) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb9fd713007bc8cce0df2cf7a52c102bac1a05ef/geometry/render_gl/internal_render_engine_gl.cc#L883)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, Is this behavior consistent with the contract of `MaybeMakeMeshFallbackMaterial`? I read its documentation, and it seems to require a "valid mesh". Is the documentation there out of date?
</blockquote></details>

That documentation is clearly broken.  :) The documentation to which you allude names a parameter that doesn't exist: `mesh_filename`.

It got partially updated in a previous PR, but, obviously, not completely.

If you read higher in that documentation you'll see:

```
An existing foo.png that can't be read or an empty `mesh_path`
     are both treated as "no compatible png could be found" and will fall
     through to the next condition.
```

I've removed the offending line.
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 1276 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7ftGfD24UyOysKUsKH:-O7oQId13vUWAhDbpaQq:b-mks545) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/test/internal_render_engine_gl_test.cc#L1276)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why not doing that right now?
</blockquote></details>

Simplest to add another rendering.

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint on the easy stuff.  I'll do the big file later on.

> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O7pjVsu-6BtxeNEk1Ua:b1iw6t0)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 150 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7piM6C11ax0t2wDMP3:-O7piM6C11ax0t2wDMP4:bs53x2h) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.h#L150)):*
> ```objc
>   // or existence of an identically named png file.
>   //
>   // @pre The file key derived from `mesh_source` and `is_convex` is in the
> ```

BTW I had to read this a few times before I figured out the parse -- the "mesh source and is_convex" is a compound noun.  I was reading "file key derived from mesh source" as the first half of the precondition and then trying to parse "is convex is in the cache" as a second half of the precondition.

Maybe "derived from _the combination of_ mesh_sourc and is_convex", to clarify?
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 1303 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7pjNJ80wEZXJJgzk5k:-O7pjNJ80wEZXJJgzk5l:bol4xls) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/test/internal_render_engine_gl_test.cc#L1303)):*
> ```cpp
>             MemoryFile::Make(obj_path),
>             {{"rainbow_box.mtl",
>               MemoryFile::Make(FindResourceOrThrow(
> ```

BTW Possibly hoisting these two FindResource... calls into named locals would make this constructor easier to scan.

**Review by jwnimmer-tri — COMMENTED** [review]
A few more notes before I run off to a meeting ...

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O82b7wi66ccCg0CkE_V:bbs8idh)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 693 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82WwVE5kIEBYjzuuqI:-O82WwVE5kIEBYjzuuqJ:btycbdw) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L693)):*
> ```cpp
>     //
>     // For now, we'll assume that anyone who does such a thing gets what they
>     // deserve.
> ```

Wouldn't it be extraordinarily common to leave `foo.obj` unchanged and repeatedly tweak its cited `foo.mtl` to play with the diffuse colors?  For example, restarting a simulation with different colors by removing the old shape from SG, rewriting the mtl on disk, and they adding back the shape to SG. In other words, I don't buy "get what they deserve".

I can get on board with "the addition of the in-memory capability here equally as broken as the filesystem implementation" so that this PR can move forward, but I don't think we should accept this amount of broken-ness as the status quo indefinitely.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 884 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82YgT9EvPGNzgqyPgm:-O82YgT9EvPGNzgqyPgn:b-89otpr) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L884)):*
> ```cpp
>   // If mesh_source is in memory, we want to pass an *empty* filename to
>   // MaybeMakeMeshFallbackmaterial() to avoid looking for foo.png.
>   const std::string filename =
> ```

nit The second parameter to `MaybeMakeMeshFallbackmaterial` is a `fs::path`, so likewise this local variable should be that same type to avoid gratuitous conversions.

It might be worth checking for more `fs::path` vs `std::string` confusion throughout this whole file.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1326 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82Zo4L7h3R1m-MrUpG:-O82Zo4L7h3R1m-MrUpH:b3alnon) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L1326)):*
> ```cpp
>       if (convex.scale() == 1.0) {
>         return convex;
>       } else if (convex.source().is_path()) {
> ```

Convex takes a `MeshSource` so there is no need to branch on the type of `source()`.

In fact, since the lambda is unconditionally copying even for scale==1, we might as well just keep the old code on master with just a little s/filename/source/ respelling, no lambda necessary.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1422 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82_U6cAPS0MGAIUP9B:-O82_U6cAPS0MGAIUP9C:btctaez) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L1422)):*
> ```cpp
>                                      const RegistrationData& data) {
>     // To make the source available everywhere without passing it ad nauseam,
>     // we alias it into a member *temporarily*.
> ```

By my count, it's only 4 functions.  That's not enough "nauseum" to justify this obscurity.

Or, if it's important to have this as a member field, then it should be passed into the constructor and kept intact through the lifetime of the extractor.  Since the extractor must be used for _exactly one_ gltf file (not >1 files back-to-back), passing the source to the constructor is actually _better_ than the current API.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Updates for the first set of comments.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O83L8632E8mvlWUx2R0:b-z8t5pc)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 693 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82WwVE5kIEBYjzuuqI:-O83F4vsAU3_8G3qBVOE:b-87kzsd) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L693)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Wouldn't it be extraordinarily common to leave `foo.obj` unchanged and repeatedly tweak its cited `foo.mtl` to play with the diffuse colors?  For example, restarting a simulation with different colors by removing the old shape from SG, rewriting the mtl on disk, and they adding back the shape to SG. In other words, I don't buy "get what they deserve".

I can get on board with "the addition of the in-memory capability here equally as broken as the filesystem implementation" so that this PR can move forward, but I don't think we should accept this amount of broken-ness as the status quo indefinitely.
</blockquote></details>

See? The phrasing of the TODO has already reaped benefit. Clear arguments were made which lend themselves to clear refutation.  TADA!

I've rephrased the TODO and the nature of the deferral.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1326 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82Zo4L7h3R1m-MrUpG:-O83HpdZ1dXR6_jfiTfu:buiurk2) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L1326)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Convex takes a `MeshSource` so there is no need to branch on the type of `source()`.

In fact, since the lambda is unconditionally copying even for scale==1, we might as well just keep the old code on master with just a little s/filename/source/ respelling, no lambda necessary.
</blockquote></details>

Taken one step further to actually realize the hoped-for gain.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1422 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O82_U6cAPS0MGAIUP9B:-O83ItSO2le32ksLE4rR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8775d3b1f09cdaed9ce7cb3b0a8fce399679717e/geometry/render_gl/internal_render_engine_gl.cc#L1422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

By my count, it's only 4 functions.  That's not enough "nauseum" to justify this obscurity.

Or, if it's important to have this as a member field, then it should be passed into the constructor and kept intact through the lifetime of the extractor.  Since the extractor must be used for _exactly one_ gltf file (not >1 files back-to-back), passing the source to the constructor is actually _better_ than the current API.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
First pass complete.

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O87z0-ZDfL9LxI_03Lm:bvb1a6z)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1444 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87xhoMEFIapaYfduMW:-O87xhoMEFIapaYfduMX:b-m7a2h2) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L1444)):*
> ```cpp
>     string_map<string> all_embedded_images;
> 
>     /* Drake's internal tinygltf has been  configured to skip all external
> ```

typo "beenXXconfigured" two spaces.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1478 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87xAHm8X9CST48emRF:-O87xAHm8X9CST48emRG:b7ot8lx) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L1478)):*
> ```cpp
>       DRAKE_DEMAND(mesh_source.is_in_memory());
> 
>       tinygltf::FsCallbacks callbacks{
> ```

These callback lambdas are too be to be inline. They need to grow up to real functions. Here is one take on how to do that:

https://github.com/jwnimmer-tri/drake/commits/21953-members-not-big-lambdas/

My patch chooses to put the `mesh_source_` into a member, and use instance member functions for the callbacks.  If you dislike the source as a member, it would also work to use static member functions and pass in the InMemoryMesh as a function argument.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1604 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87y4Ry3ReW4ptI86nn:-O87y4Ry3ReW4ptI86no:b-6rwttr) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L1604)):*
> ```cpp
>    will be compatible with TextureLibrary's documented needs for adding
>    in-memory images. */
>   string GetEmbeddedImageName(std::string_view prefix, int image_index) const {
> ```

nit What is the `prefix` here?  It's not the `InMemoryPrefix`.  Needs more docs for clarity.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1967 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87yQkP78dQO7UxmNHN:-O87yQkP78dQO7UxmNHO:b-tjszn5) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L1967)):*
> ```cpp
>         } else {
>           material.diffuse_map = std::visit<TextureSource>(
>               overloaded{[](const std::filesystem::path& path) {
> ```

nit Use `fs::path` shorthand uniformly.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 2123 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87ybVuD1O9o5MSfwXh:-O87ybVuD1O9o5MSfwXi:b-xjywzd) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L2123)):*
> it may indicate that no filename hint was provided

Possibly I missed something obvious, but I didn't find any code that implemented this part of the comment.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 2192 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87ypeN7klU4qSrDhTl:-O87ypeN7klU4qSrDhTm:b-atbr1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L2192)):*
> ```cpp
>           // The input render meshes read from an .obj should either have no
>           // diffuse map, a file path, or an in-memory image.
>           DRAKE_DEMAND(std::get_if<TextureKey>(&material.diffuse_map) ==
> ```

nit Probably more conventional would be to demand `!std::holds_alternative`.  We don't actually need to `get` it.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 671 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O7fubx7EAAhM2fLSSy3:-O8I-1o-6qrK3C4AcV5H:b-spxyxy) ([raw file](https://github.com/RobotLocomotion/drake/blob/174f191f3252bad7035fb2f2e5f017af0df568e8/geometry/render_gl/internal_render_engine_gl.cc#L671)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've radically rephrased it, acknowledging a theoretical problem, a sense of how one might resolve it, and a reason why we're not doing so now.
</blockquote></details>

Ok, I understand the problem better now. Thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1478 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87xAHm8X9CST48emRF:-O8bivZG3kGqy2Sw93eZ:b-3z4una) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L1478)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These callback lambdas are too be to be inline. They need to grow up to real functions. Here is one take on how to do that:

https://github.com/jwnimmer-tri/drake/commits/21953-members-not-big-lambdas/

My patch chooses to put the `mesh_source_` into a member, and use instance member functions for the callbacks.  If you dislike the source as a member, it would also work to use static member functions and pass in the InMemoryMesh as a function argument.
</blockquote></details>

I've taken your patch verbatim.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 2123 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-O87ybVuD1O9o5MSfwXh:-O8bcpVB8yOX9w4PuKJL:b-pdbnbc) ([raw file](https://github.com/RobotLocomotion/drake/blob/75708bad8202839a8d1cb519dcdcaedba832778b/geometry/render_gl/internal_render_engine_gl.cc#L2123)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> it may indicate that no filename hint was provided

Possibly I missed something obvious, but I didn't find any code that implemented this part of the comment.
</blockquote></details>

I'd obliquely meant that the string `the in-memory glTF file: ''` would "indicate no filename hint". I've taken the liberty of pushing it a bit further:

1. I've removed the comment.
2. `MeshSource` now takes ownership of the description to ensure that it doesn't return an empty string.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21953#-:-O8bm7SiDANCdv5xIUa7:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

**Comment by SeanCurtis-TRI** [comment]
Bwa ha ha! You hit merge a second or two before I did!

**Pull request merged**
