### PR TITLE
Add in-tree support for running valgrind

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add in-tree support for running valgrind, including a first pass at supporting documentation.

Currently passes for me with release builds; some debug builds hit a timeout.

I'm not sure yet what else I want to add here before merging, but I wanted to post this as a starting point FYI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3656)

### CODE REVIEW

**Comment by david-german-tri** [comment]
I tried introducing a memory leak to a test, and it still passed:

```
65: Test command: /usr/bin/valgrind "--show-leak-kinds=definite,possible" "--suppressions=/media/dgerman/ssd-build/3656/drake-distro/drake/valgrind.supp" "/media/dgerman/ssd-build/3656/drake-distro/build/drake/bin/integrator_test"
65: Test timeout computed to be: 300
65: ==32564== Memcheck, a memory error detector
65: ==32564== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
65: ==32564== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
65: ==32564== Command: /media/dgerman/ssd-build/3656/drake-distro/build/drake/bin/integrator_test
65: ==32564== 
65: Running main() from gtest_main.cc
65: [==========] Running 4 tests from 1 test case.
65: [----------] Global test environment set-up.
65: [----------] 4 tests from IntegratorTest
65: [ RUN      ] IntegratorTest.Topology
65: [       OK ] IntegratorTest.Topology (28 ms)
65: [ RUN      ] IntegratorTest.Output
65: [       OK ] IntegratorTest.Output (9 ms)
65: [ RUN      ] IntegratorTest.Derivatives
65: [       OK ] IntegratorTest.Derivatives (4 ms)
65: [ RUN      ] IntegratorTest.IntegratorIsNotDirectFeedthrough
65: [       OK ] IntegratorTest.IntegratorIsNotDirectFeedthrough (2 ms)
65: [----------] 4 tests from IntegratorTest (51 ms total)
65: 
65: [----------] Global test environment tear-down
65: [==========] 4 tests from 1 test case ran. (82 ms total)
65: [  PASSED  ] 4 tests.
65: ==32564== 
65: ==32564== HEAP SUMMARY:
65: ==32564==     in use at exit: 75,640 bytes in 81 blocks
65: ==32564==   total heap usage: 404 allocs, 323 frees, 133,825 bytes allocated
65: ==32564== 
65: ==32564== LEAK SUMMARY:
65: ==32564==    definitely lost: 16 bytes in 4 blocks
65: ==32564==    indirectly lost: 0 bytes in 0 blocks
65: ==32564==      possibly lost: 0 bytes in 0 blocks
65: ==32564==    still reachable: 75,624 bytes in 77 blocks
65: ==32564==         suppressed: 0 bytes in 0 blocks
65: ==32564== Rerun with --leak-check=full to see details of leaked memory
65: ==32564== 
65: ==32564== For counts of detected and suppressed errors, rerun with: -v
65: ==32564== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
1/1 Test #65: valgrind_integrator_test .........   Passed    0.95 sec

The following tests passed:
	valgrind_integrator_test

100% tests passed, 0 tests failed out of 1

Label Time Summary:
small    =   0.95 sec (1 test)

Total Test time (real) =   0.97 sec

```

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTBGBUhXKlObIWmyYJ6:b9ub2ko)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/test.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBQOy8xxado5EeXmRz:-KTBQOy8xxado5EeXmS-:b-26z2jt) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L27)):*
> ```CMake
>   elseif(SIZE STREQUAL enormous OR SIZE STREQUAL large++)
>     set(_timeout 2700)
>   elseif(SIZE STREQUAL enormous++)
> ```

Use `TEST_TIMEOUT_MULTIPLIER` to increase timeouts when running under Valgrind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by david-german-tri** [comment]
Yep, `/usr/bin/valgrind "--show-leak-kinds=definite,possible" "--suppressions=/media/dgerman/ssd-build/3656/drake-distro/drake/valgrind.supp" "/media/dgerman/ssd-build/3656/drake-distro/build/drake/bin/integrator_test"` exits `0` on memory leak.

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/test.cmake, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBRIjhJ8Rjoypzi7Dv:-KTBRIjhJ8Rjoypzi7Dw:bvjs59z) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L167)):*
> ```CMake
>       NAME valgrind_${_NAME}
>       COMMAND /usr/bin/valgrind
>           "--show-leak-kinds=definite,possible"
> ```

```
"--error-exitcode=1" "--leak-check=full"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/unit_testing_instructions.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBSRYFeDMgzbdSpala:-KTBSRYFeDMgzbdSpalb:b-m86vvy) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/drake/doc/unit_testing_instructions.rst#L93)):*
> ```reStructuredText
> 
>     cd drake-distro/build/drake
>     ctest -C valgrind -R ^valgrind
> ```

BTW, interestingly, ctests have a number that is persistent regardless of which configurations you enable.  It threw me for a loop to see "Test 219" running.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by jwnimmer-tri** [comment]
*[cmake/test.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBQOy8xxado5EeXmRz:-KTBULjfxvm3azh0IjOL:bx8kaqp) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L27)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Use `TEST_TIMEOUT_MULTIPLIER` to increase timeouts when running under Valgrind.
</details>
I hadn't yet found any uses of that flag, so I assumed it was an, e.g., user-facing configuration flag, such as when you have a sucky computer.  I was worried about overriding that for users who might need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/test.cmake, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBRIjhJ8Rjoypzi7Dv:-KTBUwMmY34HYnQ-HWgZ:b-mbvbgb) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L167)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ```
> "--error-exitcode=1" "--leak-check=full"
> ```
</details>
With the additional flags noted above, four of the `valgrind_` tests fail.  Obviously, those failures don't block this PR, but it's good to know:

```
The following tests FAILED:
	 46 - valgrind_mathematical_program_test (Failed)
	109 - valgrind_model_test (Failed)
	138 - valgrind_load_model_test (Failed)
	150 - valgrind_rigid_body_tree_test (Failed)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by jwnimmer-tri** [comment]
*[cmake/test.cmake, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBRIjhJ8Rjoypzi7Dv:-KTBVMsFKN6au1C3UOzH:b2xg5k0) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L167)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> With the additional flags noted above, four of the `valgrind_` tests fail.  Obviously, those failures don't block this PR, but it's good to know:
> 
> ```
> The following tests FAILED:
> 	 46 - valgrind_mathematical_program_test (Failed)
> 	109 - valgrind_model_test (Failed)
> 	138 - valgrind_load_model_test (Failed)
> 	150 - valgrind_rigid_body_tree_test (Failed)
> ```
</details>
I feel like this PR should pass, even when run outside of CI, so I will `NO_VALGRIND` those tests for now (or fix them).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/test.cmake, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBRIjhJ8Rjoypzi7Dv:-KTBXNvG7JfAKEF-gUz_:bjsb8os) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I feel like this PR should pass, even when run outside of CI, so I will `NO_VALGRIND` those tests for now (or fix them).
</details>
46: uninitialized value in nlopt
109: memory leak that is probably a Drake bug
138: uninitialized value in gtest itself (!!!)
150: memory leak that is probably a Drake bug

I'll dig deeper on 109 and 150, and maybe PR separate fixes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/test.cmake, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBRIjhJ8Rjoypzi7Dv:-KTBYR-m2FYOXhdimwLe:b-44a9ta) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L167)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> 46: uninitialized value in nlopt
> 109: memory leak that is probably a Drake bug
> 138: uninitialized value in gtest itself (!!!)
> 150: memory leak that is probably a Drake bug
> 
> I'll dig deeper on 109 and 150, and maybe PR separate fixes.
</details>
Done (both the flags, and the NO_VALGRIND on those four.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by jwnimmer-tri** [comment]
Hmm.  Perhaps I should have "expected fail" for those four tests, rather than skipping them.  Will consider tomorrow.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTBaw61QAP5WSegu0D_:b48qbgj)*

**Comment by amcastro-tri** [comment]
This is just great! thank you!. I just have two little questions. If you could add a very short answer to the doc it'd be super useful. 

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBSRYFeDMgzbdSpala:-KTExRPOJQRtaNKf7Emt:bxk5l1x) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/drake/doc/unit_testing_instructions.rst#L93)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, interestingly, ctests have a number that is persistent regardless of which configurations you enable.  It threw me for a loop to see "Test 219" running.
</details>
BTW, two questions here:
1. I fell into the practice of running tests/demos by typing (from withing `drake-distro/build/drake`) `./bin/test_or_demo_name`. What would the `Valgrind` variant of this be? or do I necessarily need to use ctest as above?
2. How do I determine if a given test/demo is "valgrind-enabled"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTExzqNegtIYBTEsBSx:bvewleg)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/unit_testing_instructions.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBSRYFeDMgzbdSpala:-KTF2aiyHjYgkhOe4K6F:b84h9pj) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/drake/doc/unit_testing_instructions.rst#L93)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, two questions here:
> 1. I fell into the practice of running tests/demos by typing (from withing `drake-distro/build/drake`) `./bin/test_or_demo_name`. What would the `Valgrind` variant of this be? or do I necessarily need to use ctest as above?
> 2. How do I determine if a given test/demo is "valgrind-enabled"?
</details>
(1) You could learn how to run it by hand, but you shouldn't, because it's lots of flags and you'll probably mess it up.  You should just ask the build & test system to run it for you.

(2) Ideally, they will all be.  `ctest -C valgrind -N | grep mytest` will show you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656)*

**Comment by jamiesnape** [comment]
I am not amazingly sold on creating duplicate tests just for the purposes of running Valgrind. You should be running the existing tests, but under Valgrind. The same goes for adding another build configuration. A lot of CMake code assumes the usual four build configurations.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/test.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTBQOy8xxado5EeXmRz:-KTF4eqlZwzNDhNL12oK:b-r4zu4o) ([raw file](https://github.com/robotlocomotion/drake/blob/b998fcf5afa0e5052caff0de5bc8d0b476af9f15/cmake/test.cmake#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I hadn't yet found any uses of that flag, so I assumed it was an, e.g., user-facing configuration flag, such as when you have a sucky computer.  I was worried about overriding that for users who might need it.
</details>
I think it would be better to follow the same logic even if you did not use that variable.

---

*[cmake/test.cmake, line 172 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-KTB_cclq8KJooVCWG_h:-KTB_cclq8KJooVCWG_i:b-wovktz) ([raw file](https://github.com/robotlocomotion/drake/blob/8758a97718c307d9e1bc29a0194956f7f62e4ac4/cmake/test.cmake#L172)):*
> ```CMake
>          "--suppressions=${PROJECT_SOURCE_DIR}/valgrind.supp"
>           $<TARGET_FILE:${_NAME}>
>       CONFIGURATIONS valgrind${_CONFIGURATIONS}
> ```

CMake convention would be to call the configuration `Valgrind`. I am not sure you want to pass `${_CONFIGURATIONS}` as well, but even if you did you would need a space or semicolon beforehand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTF5Pz5yj5HJwNJXNem:bgv4zes)*

**Comment by jwnimmer-tri** [comment]
What would be a better way to enable developers to frictionlessly run valgrind tests on their workstation, as their default test target during daily development.  "Check out drake-ci and run_local.bash" is a non-starter.  I am open to better ideas.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTFChTLJbuiXKp1M35p:bgbrh8x)*

**Comment by billhoffman** [comment]
ctest -T memcheck  should be the way to do this from the command line.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTFG_QcfJR_vWT-QmFi:borw2bq)*

**Comment by billhoffman** [comment]
Might need to do some tweaks to get the suppression file working but it should be configurable.  Ctest already knows how to run valgrind on tests, duplicating them should not be needed.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3656#-:-KTFS0FsmmknlD2vUNbQ:b-5ebclg)*

**Comment by jwnimmer-tri** [comment]
Yeah, I tried that locally and it seemed to be okay at very first glance.  Probably less friction to use the tool as intended, so (pending consult with @david-german-tri) I think I will pivot to just documenting that approach.

**Comment by david-german-tri** [comment]
Happy to defer to the experts!

**Comment by jwnimmer-tri** [comment]
I'm going to retract this, and instead issue a documentation change, so that folks can run valgrind locally without hassle.

**Comment by david-german-tri** [comment]
With `ctest -VV -T memcheck -R`, I don't get the actual valgrind output, just:

```
-- Processing memory checking output: 
Memory checking results:
Potential Memory Leak - 1
```

Which is not so useful.  @jamiesnape @billhoffman any pointers?

**Comment by david-german-tri** [comment]
Basically, I want CTest not to generate the `--output-log-file` and `-q` flags to Valgrind.

**Comment by jamiesnape** [comment]
Looking at the C++ source code, we can override the `-q` but not `--output-log-file`.

**Comment by jamiesnape** [comment]
If no options are set, you get:
```
-q --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50
```

**Pull request closed without merging**
