### PR TITLE
[doc] Add release notes v1.30.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.30.0.md` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-NzdkhLY6sTm8yBoeXkE:-NzdkhLY6sTm8yBoeXkF:b4er66a) ([raw file](https://github.com/RobotLocomotion/drake/blob/de7349b00e9b269dfc8a53897892a977362aa7bb/doc/_release-notes/v1.30.0.md#L11)):*
> ```Markdown
> * ``SceneGraph`` now accepts and uses a ``SceneGraphConfig`` ([#21366][_#21366])
>   * This enables setting default values for proximity properties (e.g.,
>     ``relaxation_time``) that will be used in the absence of more specific
> ```

I'm not sure `relaxation_time` is the example field I would use, since it is *only* used by SAP-based contact approximations.  If nothing else, I would pick Hunt-Crossley instead.
___
*[`doc/_release-notes/v1.30.0.md` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-NzdkeW11OmXWmeFjEUY:-NzdkeW11OmXWmeFjEUZ:b-ia2co5) ([raw file](https://github.com/RobotLocomotion/drake/blob/de7349b00e9b269dfc8a53897892a977362aa7bb/doc/_release-notes/v1.30.0.md#L12)):*
> ```Markdown
>   * This enables setting default values for proximity properties (e.g.,
>     ``relaxation_time``) that will be used in the absence of more specific
> 	properties given in model files being loaded.
> ```

nit: tab??

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.30.0.md` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-NzdkhLY6sTm8yBoeXkE:-NzdmGo-1VlEE6ODusth:b-rjmj6f) ([raw file](https://github.com/RobotLocomotion/drake/blob/de7349b00e9b269dfc8a53897892a977362aa7bb/doc/_release-notes/v1.30.0.md#L11)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm not sure `relaxation_time` is the example field I would use, since it is *only* used by SAP-based contact approximations.  If nothing else, I would pick Hunt-Crossley instead.
</blockquote></details>

Oops.  I had the same goal in mind, I just forgot which one was used where.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 7 of 9 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-:-O-7lcTm5Th2zZAc_ZRU:bnfp4nl)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 7 of 9 files at r2, 3 of 4 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_pages/installation.md` line 67 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-O-88VzIAb6eswKnRrL-:-O-88VzJ264iL8g4LjN9:b-ggjexm) ([raw file](https://github.com/RobotLocomotion/drake/blob/cd3ff0a0933420d6562dcfdd8d043d7a3c77689d/doc/_pages/installation.md#L67)):*
> ```Markdown
> |------------------------------------|--------------------------|-------|
> | Ubuntu 22.04 LTS (Jammy Jellyfish) | GCC 11                   | C++20 |
> | Ubuntu 24.04 LTS (Jammy Jellyfish) | GCC 13                   | C++20 |
> ```

Is it Noble Numbat?



_Suggestion:_
```Markdown
Noble Numbat
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 5 of 9 files at r2, 2 of 4 files at r3, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-:-O-DWwHm0b0UYzj_pSJ0:bnfp4nl)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Assuming tonight's builds are happen, the plan will be to release tomorrow.

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21524#-:-O-HCHKn9nLHed-011af:b5r5r4e)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
