### PR TITLE
Manage external source trees as Git submodules

### PR DESCRIPTION
**Pull request by bradking**
Drake's top-level `CMakeLists.txt` file has a table of Git repository URLs and commit SHA-1s for the external source trees.  These two pieces of information are exactly what Git submodules record (in a `.gitmodules` file and a tree-object entry, respectively).  Drake also tells CMake's ExternalProject module to create build rules that clone the Git repositories into subdirectories within its own source tree.  This is exactly what Git submodules are meant to do.

Drake's external source trees are actually part of its overall source tree from the perspective of local development and build operations.  This is why we place them in subdirectories of the main source tree.  They just happen to be externally maintained and version-controlled separately.  Using the build system to manage parts of the source tree is sub-optimal:

* We need a kludge like the `AUTO_UPDATE_EXTERNALS` option to help developers update their external source trees after performing `git pull` on the main source tree while still providing a way to do local development in the external source trees without erasing the changes on the next build.

* We need to `.gitignore` the `externals/*` directories (and a few others) since they are placed in the source tree but not managed by Git as part of the main source tree.  This means that top-level operations like `git status` only see the main source tree rather than the whole source tree.

A solution to these problems is to use Git to manage the whole source tree by using Git submodules to manage the external source trees underneath our main source tree.  The only involvement we need from the build system is to determine *which* external source trees need to be downloaded for the chosen build options.  After the needed external source trees (submodules) have been downloaded (cloned) all further source tree status and update operations can be managed cleanly by the version control tool (Git).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2487)

### CODE REVIEW

**Comment by bradking** [comment]
Cc: @david-german-tri

**Comment by bradking** [comment]
Some CI builds fail with:

```
error: could not lock config file .git/config: File exists
Failed to register url for submodule path 'externals/...'
```

I suspect this is caused by parallel downloads colliding on submodule initialization.  Will fix.

**Comment by mwoehlke-kitware** [comment]
:lgtm: (caveat: I didn't attempt to verify that the repository URL's and SHA's are unchanged; I'll just trust you there :smile:)

<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> Some CI builds fail with:
> 
> 
> 
> ```
> 
> error: could not lock config file .git/config: File exists
> 
> Failed to register url for submodule path 'externals/...'
> 
> ```
> 
> 
> 
> I suspect this is caused by parallel downloads colliding on submodule initialization.  Will fix.
> 
> 
</details>


---

Reviewed 34 of 34 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJ7NXa2y7QMuoE1i6Q-:1024566337)*

**Comment by mwoehlke-kitware** [comment]
> Some CI builds fail with:
>
>     error: could not lock config file .git/config: File exists
>     Failed to register url for submodule path 'externals/...'
>
> I suspect this is caused by parallel downloads colliding on submodule initialization.  Will fix.

That could be; I always run the top level build as `ninja -j1` (since the sub-ninjas will run in parallel anyway, there isn't much point building multiple externals in parallel, and besides, that would result in n^2 total jobs :grin:).

In fact, since we require CMake 3.5 which I believe is new enough, can we just make the externals use ninja's console pool for all steps?

**Comment by bradking** [comment]
> parallel downloads colliding on submodule initialization. Will fix.

I've revised the topic to fix this, and the CI builds are now clean.  The fix was simply to perform `git submodule init` serially during the CMake configuration step in order to make all needed changes to `.git/config` ahead of time.

> can we just make the externals use ninja's console pool for all steps

Perhaps, but that is beyond the scope of this change/PR.

**Comment by bradking** [comment]
> :lgtm: (caveat: I didn't attempt to verify that the repository URL's and SHA's are unchanged; I'll just trust you there :smile:)

The topic commit history shows how this was done automatically to preserve the values.  Basically I added temporary changes to `CMakeLists.txt` to do the conversion, did the conversion, and then reverted the temporary changes.

**Comment by mwoehlke-kitware** [comment]
>> can we just make the externals use ninja's console pool for all steps
>
> Perhaps, but that is beyond the scope of this change/PR.

I was expecting you would need to explicitly serialize the download steps, likely making changes very similar to having the externals use the console pool also. Since you ended up doing something quite different, such a change would indeed be much more orthogonal than I was anticipating.

Anyway, LGTM... :lgtm:



---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJC2JfkEf5UV1kOiCey:2031988002)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJCLve2BqkbR0bIxhyX:-KJCLve30fE3yGnwwPQ3:984813755) ([raw file](https://github.com/robotlocomotion/drake/blob/168a335ca95e7c0583fdda7693cd41f82de48d9d/drake/doc/from_source.rst#L137)):*
> ```reStructuredText
> 	git checkout master
> 	git pull
> 	git submodule update --recursive
> ```

Am I correctly understanding the following?

1. Someone changes an external SHA.
2. I `git pull`.
3. I build.
4. I'm still using the old version of the external, because I didn't `git submodule update`.  Things explode.

If so: is it possible to make the generated build files re-run `${proj}-download` when the submodule file changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by bradking** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJCLve2BqkbR0bIxhyX:-KJCQUFUDDaxdRr0bd03:1186534618) ([raw file](https://github.com/robotlocomotion/drake/blob/168a335ca95e7c0583fdda7693cd41f82de48d9d/drake/doc/from_source.rst#L137)):*
That's correct.  Some people have trained themselves to do both steps.  Others create an alias for them:

    $ git config alias.pullall '!bash -c "git pull && git submodule update --recursive"'
    ...
    $ git pullall

We could have CMake create this alias for the local Git work tree, or provide a "developer setup" script.

> is it possible to make the generated build files re-run ${proj}-download when the submodule file changes?

We could make the build do the update by setting the external project `UPDATE_COMMAND` to `git submodule update --recursive` too.  This would mean restoring an option like `AUTO_UPDATE_EXTERNALS` to control it, but the behavior when the option is `OFF` will be much more tractable than it is without submodules because updating manually will be easy.

Either way we will still have gained whole-tree management by Git (e.g. `git status`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJCLve2BqkbR0bIxhyX:-KJCwuvuf2CuCyR2Y2kR:1609302081) ([raw file](https://github.com/robotlocomotion/drake/blob/168a335ca95e7c0583fdda7693cd41f82de48d9d/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> That's correct.  Some people have trained themselves to do both steps.  Others create an alias for them:
> 
>     $ git config alias.pullall '!bash -c "git pull && git submodule update --recursive"'
>     ...
>     $ git pullall
> 
> We could have CMake create this alias for the local Git work tree, or provide a "developer setup" script.
> 
> > is it possible to make the generated build files re-run ${proj}-download when the submodule file changes?
> 
> We could make the build do the update by setting the external project `UPDATE_COMMAND` to `git submodule update --recursive` too.  This would mean restoring an option like `AUTO_UPDATE_EXTERNALS` to control it, but the behavior when the option is `OFF` will be much more tractable than it is without submodules because updating manually will be easy.
> 
> Either way we will still have gained whole-tree management by Git (e.g. `git status`).
> 
</details>
The `UPDATE_COMMAND` approach sounds like a good idea to me.  Using an sha other than the one specified in `master` for a subproject should be a conscious choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by bradking** [comment]
Review status: 34 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJCLve2BqkbR0bIxhyX:-KJHK0jlEo069SLMCLFn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/168a335ca95e7c0583fdda7693cd41f82de48d9d/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> The `UPDATE_COMMAND` approach sounds like a good idea to me.  Using an sha other than the one specified in `master` for a subproject should be a conscious choice.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by david-german-tri** [comment]
Looks good to me.  @russtedrake, did you want to review this change as well?

<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> >> can we just make the externals use ninja's console pool for all steps
> >
> > Perhaps, but that is beyond the scope of this change/PR.
> 
> I was expecting you would need to explicitly serialize the download steps, likely making changes very similar to having the externals use the console pool also. Since you ended up doing something quite different, such a change would indeed be much more orthogonal than I was anticipating.
> 
> Anyway, LGTM... :lgtm:
</details>


---

Review status: 34 of 35 files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/from_source.rst, line 137 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJCLve2BqkbR0bIxhyX:-KJHNmtoPP95APRdeGFV:141133547) ([raw file](https://github.com/robotlocomotion/drake/blob/168a335ca95e7c0583fdda7693cd41f82de48d9d/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> Done.
</details>
LGTM, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJHNlNnSwCFOmh5bP4x:1568090610)*

**Comment by david-german-tri** [comment]
Reviewed 33 of 34 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by rdeits** [comment]
We actually already had this discussion almost two years ago: https://github.com/RobotLocomotion/drake/issues/1169 and came to exactly the opposite conclusion. We had been using git submodules within drake for a long time, and ultimately decided to abandon them for several reasons:

1) Submodules were an extremely common point of failure for new users. We spent an unreasonable amount of time helping people `git submodule update --init --recursive`. I really can't stress enough how confusing this was for a lot of students working with Drake. 
2) There was no way for users to check out only a specific set of submodules, which was a particular problem since some of our externals are private. 
3) It forced us to handle git externals and non-git externals through entirely different mechanisms
4) It's annoying and difficult to change the URL that a submodule points to. This turns out to be a useful feature of the current system because I can, for example, fork one of our externals, push a branch to my fork, then edit Drake's CMakeLists to point to my fork in order to test my changed external with Drake. 

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Looks good to me.  @russtedrake, did you want to review this change as well?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJYlgTh-9PXOv6mN3lm:998122082)*

**Comment by bradking** [comment]
@rdeits thanks for the link and the summary of previous discussion.

I've found it difficult to work with Drake externals without submodules.  It is very hard to tell whether any external sources have been modified.  In fact while working on this I found that our builds were making some source trees dirty and no one noticed (I added `.gitignore` updates to the externals to fix this).

> 1) Submodules were an extremely common point of failure for new users. We spent an unreasonable amount of time helping people git submodule update --init --recursive. I really can't stress enough how confusing this was for a lot of students working with Drake.
> 2) There was no way for users to check out only a specific set of submodules, which was a particular problem since some of our externals are private. 

With the approach proposed in this PR no users actually have to deal with submodules.  The workflow is the same as before for users.  The needed subset of externals is automatically selected by the CMake configuration and used to configure a subset of submodules.  Builds automatically update them unless `AUTO_UPDATE_EXTERNALS` is turned off (this changed during review so the opening description in this PR is no longer up to date).

> 3) It forced us to handle git externals and non-git externals through entirely different mechanisms

Currently we have no non-Git externals.  We can handle them by importing them into Git ourselves in a dedicated support repository.  Even before this change the externals logic hard-coded use of `GIT_REPOSITORY ...` in ExternalProject_Add calls.

> 4) It's annoying and difficult to change the URL that a submodule points to. This turns out to be a useful feature of the current system because I can, for example, fork one of our externals, push a branch to my fork, then edit Drake's CMakeLists to point to my fork in order to test my changed external with Drake. 

Turn off `AUTO_UPDATE_EXTERNALS` and deal with the submodule repository work trees as you would any other tree.  Add a remote, fetch, and checkout the desired branch.  The local edit will appear in `git diff` of the top-level source tree just as a change to its `CMakeLists.txt` file would.

**Comment by rdeits** [comment]
Ok, thanks @bradking for the explanation. So all users will have all of the submodules listed in their `.gitmodules`, but only some of them will actually be initialized? That's definitely better than what I had imagined (trying to have cmake rewrite `.gitmodules` itself, which would be a very bad idea). I've never worked with a project that had uninitialized submodules, but I suppose it should work fine. 

One additional thing to consider: I believe this will make it more difficult to check out older versions of drake without `rm -rf`-ing the entire `externals` directory. That's because if I checkout a revision before this change, I'll have untracked files in, e.g. `externals/iris`. When I try to move back to `master`, the checkout will fail with `error: Updating the following directories would lose untracked files in it:` until I `rm -rf externals`. This issue has already happened to us in the `openhumanoids/oh-distro` project when we replaced a source directory with a submodule, and it was somewhat annoying. But if doing this makes working with Drake easier in other ways then it may be worth that somewhat uncommon annoyance.

**Comment by bradking** [comment]
> So all users will have all of the submodules listed in their .gitmodules, but only some of them will actually be initialized?

Correct.  Actually `.gitmodules` is part of the repository tracked content and is just a table of available submodules.  Initializing a submodule means copying the configuration into `.git/config`, and only the needed subset will have that done.  Furthermore, checking out a submodule is only done by `git submodule update`, and that can be restricted even to a subset of initialized modules.  Indeed the download step implemented in this PR for each external project just checks out its own submodule.

> I believe this will make it more difficult to check out older versions of drake without rm -rf-ing the entire externals directory. 

I did that regularly while developing this change without removing the externals directory and I never saw that diagnostic.  It should be fairly clean because in both cases the subdirectories are managed by Git.  I think difficulty like you encountered occurs only when `.gitignore` is insufficient in the older external repo versions.  One can simply remove the untracked files.  Either way, this is a temporary transitional concern.  Over time the need to checkout versions prior to submodules will diminish.

**Comment by david-german-tri** [comment]
+@russtedrake +@rdeits 

<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> > So all users will have all of the submodules listed in their .gitmodules, but only some of them will actually be initialized?
> 
> 
> 
> Correct.  Actually `.gitmodules` is part of the repository tracked content and is just a table of available submodules.  Initializing a submodule means copying the configuration into `.git/config`, and only the needed subset will have that done.  Furthermore, checking out a submodule is only done by `git submodule update`, and that can be restricted even to a subset of initialized modules.  Indeed the download step implemented in this PR for each external project just checks out its own submodule.
> 
> 
> 
> > I believe this will make it more difficult to check out older versions of drake without rm -rf-ing the entire externals directory. 
> 
> 
> 
> I did that regularly while developing this change without removing the externals directory and I never saw that diagnostic.  It should be fairly clean because in both cases the subdirectories are managed by Git.  I think difficulty like you encountered occurs only when `.gitignore` is insufficient in the older external repo versions.  One can simply remove the untracked files.  Either way, this is a temporary transitional concern.  Over time the need to checkout versions prior to submodules will diminish.
> 
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJg2rgYjZW2hXKz_QcQ:-2052288235)*

**Comment by RussTedrake** [comment]
@rdeits -- thanks for clearly articulating the concerns that I had immediately, too.  I'm still a bit worried because the current system has been much better / cleaner than any submodule approach we had before.

a few clarification questions to make sure I understand:
- we are avoiding the major pain-point with novice users because cmake will call git submodule update (recursively) on every build?  
- every user will have a directory for every external, but the directories which are not used (e.g. they do not have access) will be empty?
- is the mechanism for NOT initializing the disabled externals simply that cmake never calls init/update on them?
- if the above is true, what happens if I run git submodule update --init --recursive in the top directory (as your from_source.rst instructs them to do)?  won't it try to download those other repos?

We should also add some documentation in the developers section telling them how to update the submodule hash since I know we'll get questions about it.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> +@russtedrake +@rdeits 
</details>


---

Reviewed 10 of 34 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 316 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtO_zW4gYEa6gQ1jTY:-KJtO_zXHNNbn7enHEHa:110277133) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/CMakeLists.txt#L316)):*
> ```CMake
> 
>     # Download externals as Git submodules.
>     set(${proj}_DOWNLOAD_COMMAND ${GIT_EXECUTABLE} submodule update --init --recursive -- ${${proj}_GIT_SUBMODULE_PATH})
> ```

i would have said that leaning on CMake to do this properly (instead of calling git manually) would be better, but I suppose if the curator of CMake is recommending this then I will heed the advice.

---

*[CMakeLists.txt, line 489 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtP-EwG7iYlu6-xAUA:-KJtP-EwG7iYlu6-xAUB:-1459069083) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/CMakeLists.txt#L489)):*
> ```CMake
> 
>     # Initialize the submodule configuration now so parallel downloads do not conflict later.
>     execute_process(COMMAND ${GIT_EXECUTABLE} submodule init -- drake/examples/${example}
> ```

it's impossible for me to think through all of the use cases in reading this PR.  i have to trust that you've thought through them all.

---

*[drake/doc/from_source.rst, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtQGC_kY6VdYPevmF8:-KJtQGC_kY6VdYPevmF9:-1649697479) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/drake/doc/from_source.rst#L137)):*
> ```reStructuredText
> 	git checkout master
> 	git pull
> 	git submodule update --recursive
> ```

i thought we said cmake would do this for you??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJtP9gEbsm-axEUMBK-:2122480632)*

**Comment by bradking** [comment]
> we are avoiding the major pain-point with novice users because cmake will call git submodule update (recursively) on every build?

Yes.

> every user will have a directory for every external, but the directories which are not used (e.g. they do not have access) will be empty?

Yes.

> is the mechanism for NOT initializing the disabled externals simply that cmake never calls init/update on them?

Yes.

> if the above is true, what happens if I run git submodule update --init --recursive in the top directory (as your from_source.rst instructs them to do)? won't it try to download those other repos?

The `from_source.rst` suggests:

```
git submodule update --recursive
```

Without the `--init` flag no extra repos will be downloaded.



---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtQGC_kY6VdYPevmF8:-KJuGR9fOtfiV3KD9qi5:-962657332) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i thought we said cmake would do this for you??
</details>
CMake does take care of this, but it won't hurt for the user to do it either (without `--init`).  We can drop this line from the documentation if you prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KJuFrFwZErLZGw5fBel:-1249361080)*

**Comment by mwoehlke-kitware** [comment]
> what happens if I run git submodule update --init --recursive in the top directory (as your from_source.rst instructs them to do)? won't it try to download those other repos?

It will, as will I believe `git submodule init` (with no path given). You can use `git submodule deinit <path(s)>` to "undo" this (as I learned the hard way :smile:).

**Comment by RussTedrake** [comment]
thx.  i trust that you've thought it through.  i'm willing to give it a shot. :lgtm: 

<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> > what happens if I run git submodule update --init --recursive in the top directory (as your from_source.rst instructs them to do)? won't it try to download those other repos?
> 
> 
> 
> It will, as will I believe `git submodule init` (with no path given). You can use `git submodule deinit <path(s)>` to "undo" this (as I learned the hard way :smile:).
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-:-KK5T9NqabPXlXjOCiV4:-1456913832)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by bradking** [comment]
This is ready to merge other than some Reviewable discussions not marked as resolved.

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 316 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtO_zW4gYEa6gQ1jTY:-KKJr0sD71sCpcpMPfwE:-217436990) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/CMakeLists.txt#L316)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i would have said that leaning on CMake to do this properly (instead of calling git manually) would be better, but I suppose if the curator of CMake is recommending this then I will heed the advice.
</details>
Closing this thread since Russ has LGTMed.

---

*[CMakeLists.txt, line 489 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtP-EwG7iYlu6-xAUA:-KKJr5aXv8j1JJr1bJEJ:-217436990) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/CMakeLists.txt#L489)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> it's impossible for me to think through all of the use cases in reading this PR.  i have to trust that you've thought through them all.
</details>
Closing this thread since Russ has LGTMed.

---

*[drake/doc/from_source.rst, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtQGC_kY6VdYPevmF8:-KKJrBiwdNb4mlWjqiGJ:630220820) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> CMake does take care of this, but it won't hurt for the user to do it either (without `--init`).  We can drop this line from the documentation if you prefer.
</details>
I'd support dropping it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by bradking** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtQGC_kY6VdYPevmF8:-KKJtUhP3TRP_EWtBE00:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I'd support dropping it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/from_source.rst, line 137 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2487#-KJtQGC_kY6VdYPevmF8:-KKJuX6LGKJ5Lp6qBFNK:676834233) ([raw file](https://github.com/robotlocomotion/drake/blob/b08be483b0d87cd601d7857e7d1e5979a6a8588b/drake/doc/from_source.rst#L137)):*
<details><summary><i>Previously, bradking (Brad King) wrote…</i></summary>
> Done.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2487)*

**Pull request merged**
