### PR TITLE
Consolidate, simplify, and purge yet more CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7235)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-matlab-documentation please

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri :lgtm: platform review.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7235#-:-KwD1ysU06bYCmzbaMQ0:bkns37u)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7235#-:-KwFbow865duyxyx8Ies:bnfp4nl)*

**Pull request merged**
