### PR TITLE
add Mosek solver to MixedIntegerConvexProgram

### PR DESCRIPTION
**Pull request by hongkai-dai**
MixedIntegerConvexProgram should support both gurobi and mosek

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3090)

### CODE REVIEW

**Comment by rdeits** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by rdeits** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KOoqbQoXc0Nse6ETIbM:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@psiorx for platform review

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KOxRl5noCuUhYWwv7M4:bjha9jr)*

**Comment by hongkai-dai** [comment]
@psiorx could you do a platform review? Thanks a lot!

**Comment by hongkai-dai** [comment]
+@russtedrake for platform review

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KPiRiXFkgpYukmMEl_9:b-ddhj1v)*

**Comment by RussTedrake** [comment]
probably need to put logic around the test program in cmake to make sure it's only called if both solvers are present.  but it would be better to improve the logic to test all solvers that are present (e.g. test only gurobi if that's what the user has).

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 68 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeNZRM_GPx43IUGYR:-KPmeNZThC75AcddE47R:b-2ee8fx) ([raw file](https://github.com/robotlocomotion/drake/blob/dbdd552203ed73e23d47a3911704c731c45b9d25/drake/solvers/MixedIntegerConvexProgram.m#L68)):*
> ```objc
>       end
> 
>       checkDependency('gurobi');
> ```

this should not be a requirement anymore.  if gurobi is not present, then it should check for and switch to mosek.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 407 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeW5GYSIV3yOct9aZ:-KPmeW5GYSIV3yOct9a_:b-3y2elk) ([raw file](https://github.com/robotlocomotion/drake/blob/dbdd552203ed73e23d47a3911704c731c45b9d25/drake/solvers/MixedIntegerConvexProgram.m#L407)):*
> ```objc
>     end
>     
>     function [obj,solvertime,objval] = solveMosek(obj)
> ```

FYI -- too much code for me to scrutinize the details in this method.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KPmeoVM9TcDtdljGNee:bnv0j82)*

**Comment by hongkai-dai** [comment]
I added a `compareSolvers` function in MixedIntegerConvexProgram, that tests the available solver among gurobi and mosek. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 68 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeNZRM_GPx43IUGYR:-KPqDTUzg6B0KCZAQC6g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9b436b8155f124526c3817d27e49d0185e0db26/drake/solvers/MixedIntegerConvexProgram.m#L68)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> this should not be a requirement anymore.  if gurobi is not present, then it should check for and switch to mosek.
</details>
Done.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 407 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeW5GYSIV3yOct9aZ:-KPqDUmr5eMmX-5THIKg:b-pva9t5) ([raw file](https://github.com/robotlocomotion/drake/blob/a9b436b8155f124526c3817d27e49d0185e0db26/drake/solvers/MixedIntegerConvexProgram.m#L407)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> FYI -- too much code for me to scrutinize the details in this method.  
</details>
Would it be OK if I ask someone else in the lab for platform review? On this page http://drake.mit.edu/developers.html#code-review, it says only you and John are the platform reviewer in RLG. But I feel Michael or Twan should also be able to review this PR, if they have time.

It is not easy to break this PR to smaller pieces, but if that helps the reviewer, I can try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KPqEHgEnSt1QTZS5HUQ:beb9hnk)*

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 407 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeW5GYSIV3yOct9aZ:-KQ0FjPGc8mpVqyu6Ggr:b-6os9py) ([raw file](https://github.com/robotlocomotion/drake/blob/a9b436b8155f124526c3817d27e49d0185e0db26/drake/solvers/MixedIntegerConvexProgram.m#L407)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Would it be OK if I ask someone else in the lab for platform review? On this page http://drake.mit.edu/developers.html#code-review, it says only you and John are the platform reviewer in RLG. But I feel Michael or Twan should also be able to review this PR, if they have time.
> 
> It is not easy to break this PR to smaller pieces, but if that helps the reviewer, I can try.
</details>
i considered myself as the platform reviewer.  yes, they would make great feature reviewers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by RussTedrake** [comment]
:lgtm:  but still waiting on a second reviewer.

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KQytP5A-hfSX5KAtuXe:b-x10cfy)*

**Comment by hongkai-dai** [comment]
+@tkoolen for review

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KR-EZCuCOi_zDKrMWMG:bhpy5qj)*

**Comment by tkoolen** [comment]
Added comments.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 409 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-GyYea8y_obJOMwEt:-KR-GyYf_ibGsYRvMX2e:bburope) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L409)):*
> ```objc
>       params = struct();
>       start_time = clock();
>       [r,res] = mosekopt('minimize',prob,params);
> ```

I guess this is pervasive throughout the Matlab code base, but I find `r` and `res` to be terrible variable names.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 420 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-H5t1jwcWfW1zbAJX:-KR-H5t1jwcWfW1zbAJY:bwslmiq) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L420)):*
> ```objc
>       else
>         if(strcmp(res.sol.itr.prosta,'PRIMAL_INFEASIBLE'))
>           error('Drake:MixedIntegerConvexProgram:PrimalInfeasible','The probelm is primal infeasible');
> ```

spelling: probelm.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 426 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-HRf6eRmvBz-bT-Xm:-KR-HRf6eRmvBz-bT-Xn:b1aono4) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L426)):*
> ```objc
>           error('Drake:MixedIntegerConvexProgram:PrimalDualInfeasible','The problem is primal and dual infeasible');
>         elseif(strcmp(res.sol.itr.prosta,'UNKNOWN'))
>           warning('Drake:MixedIntegerConvexProgram:Unknown','The problem solution is unknown');
> ```

The solution is unknown? Maybe something like 'The problem solution status is unknown' would be better.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 427 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-Hq1FQzP4CcT5B5Kd:-KR-Hq1FQzP4CcT5B5Ke:b-l56qkx) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L427)):*
> ```objc
>         elseif(strcmp(res.sol.itr.prosta,'UNKNOWN'))
>           warning('Drake:MixedIntegerConvexProgram:Unknown','The problem solution is unknown');
>         end
> ```

I think there should be a fallback else statement here.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 436 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-I6iTXoNlT99tmi4i:-KR-I6iTXoNlT99tmi4j:b-obn66h) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L436)):*
> ```objc
>       prob.c = obj.c;
>       [prob.qosubi,prob.qosubj,prob.qoval] = find(2*obj.Q);
>       lower_idx = prob.qosubi>=prob.qosubj;
> ```

Add space around comparison operator.
Also, I have no idea what lower_idx is supposed to be. Maybe add a comment or use a better variable name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KR-JOpZAQO7qpw8JfvE:b-277h9n)*

**Comment by hongkai-dai** [comment]
The change is moved to `matlab/solvers` after rebase.

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 409 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-GyYea8y_obJOMwEt:-KR-dW889HXlco0vIYPM:bip9t14) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L409)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I guess this is pervasive throughout the Matlab code base, but I find `r` and `res` to be terrible variable names.
</details>
Thanks! This is just the names of the return arguments used in mosek documentation. They are terrible names, I will change it to `[return_code, result]`

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 420 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-H5t1jwcWfW1zbAJX:-KR-rUrbypvL1hPsC_8D:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L420)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> spelling: probelm.
</details>
Done

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 426 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-HRf6eRmvBz-bT-Xm:-KR-rWe4gXU-iv0hueZQ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L426)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> The solution is unknown? Maybe something like 'The problem solution status is unknown' would be better.
</details>
Done

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 427 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-Hq1FQzP4CcT5B5Kd:-KR-g9i0F1xtrn8cR8z3:bottemo) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L427)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I think there should be a fallback else statement here.
</details>
The fallback else is for successful result, which I think we should not print out anything.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 436 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-I6iTXoNlT99tmi4i:-KR-rXuMWnkfk9gwu7us:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/93bd9614988897aa17b9813ba4fbbe5573ecdd59/drake/solvers/MixedIntegerConvexProgram.m#L436)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> Add space around comparison operator.
> Also, I have no idea what lower_idx is supposed to be. Maybe add a comment or use a better variable name.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KR-ryDOkEvVbwlM6Q6o:b-8k1lq2)*

**Comment by tkoolen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/solvers/MixedIntegerConvexProgram.m, line 426 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-suhBH5FDi5ldqqwi:-KR-suhBH5FDi5ldqqwj:b45quma) ([raw file](https://github.com/robotlocomotion/drake/blob/531cfd62d9107a59b02a923f9459b3ee9687a866/drake/matlab/solvers/MixedIntegerConvexProgram.m#L426)):*
> ```objc
>           error('Drake:MixedIntegerConvexProgram:PrimalDualInfeasible','The problem is primal and dual infeasible');
>         elseif(strcmp(result.sol.itr.prosta,'UNKNOWN'))
>           warning('Drake:MixedIntegerConvexProgram:Unknown','The problem solution status is unknown');
> ```

Continuing discussion from moved file: I'm not satisfied with that. What's to stop Mosek from adding another solution status in a future release? I think there should be an else that throws an error, stating that the solution status returned by Mosek is not recognized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/solvers/MixedIntegerConvexProgram.m, line 426 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KR-suhBH5FDi5ldqqwi:-KR00A9Kw4Cs_zU936po:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/531cfd62d9107a59b02a923f9459b3ee9687a866/drake/matlab/solvers/MixedIntegerConvexProgram.m#L426)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> Continuing discussion from moved file: I'm not satisfied with that. What's to stop Mosek from adding another solution status in a future release? I think there should be an else that throws an error, stating that the solution status returned by Mosek is not recognized.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by tkoolen** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KR0DLUBl2Y6jFZsnqKo:bnfp4nl)*

**Comment by tkoolen** [comment]
Reviewed 2 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/MixedIntegerConvexProgram.m, line 407 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-KPmeW5GYSIV3yOct9aZ:-KRlRjzs6zzI9Gh5Ex39:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9b436b8155f124526c3817d27e49d0185e0db26/drake/solvers/MixedIntegerConvexProgram.m#L407)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i considered myself as the platform reviewer.  yes, they would make great feature reviewers.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090)*

**Comment by tkoolen** [comment]
@RussTedrake, your comment is blocking.
@rpoyner-tri, @jadecastro (build cops), please consider override-merging this.

**Comment by rpoyner-tri** [comment]
FTR, not all build cops have override-merge bits (including Jon and myself). However, I will look this over and ping @david-german-tri if it seems ok to me.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KS8NWjkcDhmtawqxJkx:b-810cdb)*

**Comment by rpoyner-tri** [comment]
Ah, +@david-german-tri has schooled me on the intricacies of reviewable dismiss. Branch merged.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3090#-:-KS8PJ90z0GyxyCw4CeV:b-nd05ns)*

**Pull request merged**
