### PR TITLE
Adds support for differnet vehicle speeds on each lane of a dragway.

### PR DESCRIPTION
**Pull request by liangfok**
Vehicles to the left can now travel faster that vehicles to the right.

Video: https://youtu.be/Ha_hFafB26o

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5257)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please since I believe the next step is to implement a lane change model.
+@jwnimmer-tri for platform review please.
\CC: @maddog-tri since you reviewed the previous two dragway-related PRs.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-:-KdZDhUmGDJPu555bZvS:b-f3j5xm)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-Kd_stBZZXMnjqgoFhrE:-Kd_stBZZXMnjqgoFhrF:b-lfn1fp) ([raw file](https://github.com/robotlocomotion/drake/blob/78c805b67161729bb648408a0af8f71d7a0357cd/drake/automotive/README.md#L75)):*
> ```Markdown
>        --num_dragway_lanes=10 \
>        --num_trajectory_car=10
>    ```
> ```

I'm unclear on why this recipe stays here; it seems strictly worse than the below demo in every way.

---

*[drake/automotive/README.md, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-Kd_sq6mjn2_lsqPJtgX:-Kd_sq6mjn2_lsqPJtgY:bmkllhb) ([raw file](https://github.com/robotlocomotion/drake/blob/78c805b67161729bb648408a0af8f71d7a0357cd/drake/automotive/README.md#L84)):*
> ```Markdown
>        --num_dragway_lanes=3 \
>        --num_trajectory_car=12 \
>        --dragway_lane_speed_delta=2
> ```

BTW I think this last item could be the default and not have to mention it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-:-Kd_tNVaZaFJ8WHpPCfn:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-Kd_stBZZXMnjqgoFhrE:-Kda0ZH5uHS5F5alBWoA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/78c805b67161729bb648408a0af8f71d7a0357cd/drake/automotive/README.md#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm unclear on why this recipe stays here; it seems strictly worse than the below demo in every way.
</blockquote></details>

Done.

---

*[drake/automotive/README.md, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-Kd_sq6mjn2_lsqPJtgX:-Kda0_iBnEeplfjvJqAI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/78c805b67161729bb648408a0af8f71d7a0357cd/drake/automotive/README.md#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think this last item could be the default and not have to mention it here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-KdaBOz_5Bj7yrwlh3hI:-KdaBOzbifBTbCwKn4-b:begox3e) ([raw file](https://github.com/robotlocomotion/drake/blob/4c998a41a49bc5bec2497c32613819d28d09e668/drake/automotive/automotive_demo.cc#L44)):*
> ```cpp
>               "dragway_base_speed + 2 * dragway_lane_speed_delta m/s.");
> DEFINE_double(dragway_vehicle_temporal_spacing, 3,
>               "The temporal spacing between consecutive vehicles on a lane.");
> ```

BTW A better name might be `dragway_vehicle_delay`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-:-KdaFy4TUjBjP99zyPn3:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5257#-KdaBOz_5Bj7yrwlh3hI:-KdaIj2qzn2egWkxwvUj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c998a41a49bc5bec2497c32613819d28d09e668/drake/automotive/automotive_demo.cc#L44)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW A better name might be `dragway_vehicle_delay`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5257)*

**Pull request merged**
