### PR TITLE
Upgrade Drake's FCL to v0.6.1

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12762)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
macOS passed but is choking on CDash upload.  We can merge this now anyway.

**Pull request merged**
