### PR TITLE
Fix warnings about redefinition of _FORTIFY_SOURCE on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8183)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and +@jwnimmer-tri for platform review.

**Comment by soonho-tri** [comment]
Yay! Thanks for the fix! :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8183#-:-L6IN9lTKLDnindAB6gv:bm1bdhu)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

FYI We have sometimes added `  # Added for Drake.` when we change lines, but having done the clang-4.0 toolchain swap a few months ago I'm not sure that such comments really add value.  I had to manually review every change when regenerating these stanzas anyway.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8183#-:-L6IRS7yvs6SQQEJqm5r:b-bgf5nj)*

**Pull request merged**
