### PR TITLE
ik wrappers for iiwa demo

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5231)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai +@naveenoid for feature reviews. i am not planning to add unit tests for now.. however we should think about what's a good meaningful *unit* test.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-KdR90bOTYdr7CflNqwH:bswua0j)*

**Comment by naveenoid** [comment]
Starting the review..first going to test the demo on my machine.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-KdVACppQRLU7l4CWh1X:b8syq6f)*

**Comment by hongkai-dai** [comment]
Reviewed 7 of 13 files at r1.
Review status: 7 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdX9UxwigmZ7yRPLa-R:-KdX9UxwigmZ7yRPLa-S:b4snomu) ([raw file](https://github.com/robotlocomotion/drake/blob/fa03dc5b1892e455684cd1e3facc47c474feab78/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc#L101)):*
> ```cpp
>   int random_ctr = 0;
> 
>   const int kRelaxPosTol = 0;
> ```

I think it is better to use a enum class here 
```C++
enum class RelaxMode {
  kRelaxPosTol = 0,
  kRelaxRotTol = 1,
}
```

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdX0noLlTDQS3YGDR7F:-KdX0noNPXEdjxNyBxIf:b79godi) ([raw file](https://github.com/robotlocomotion/drake/blob/fa03dc5b1892e455684cd1e3facc47c474feab78/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.h#L46)):*
> ```objc
>     Vector3<double> pos_tol;
>     /// Max angle difference between solved end effector's orientation and
>     /// the desired.
> ```

Could you add documentation to clarify that the unit of the `rot_tol` is in radians, not in angle degrees?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by naveenoid** [comment]
After a day of fiddling with different build systems (settled for running ninja to get the visualizer and bazel for the examples) I really think each of the demo executables in PR needs a does it run unit test added. For some reason I cant yet figure out, iiwa_wsg_simulation is no longer able to find the path to the sdf / urdfs of the model objects. Will proceed with a code review now and a hangouts with you( @siyuanfeng-tri ) later.

---

Reviewed 1 of 13 files at r1.
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-Kd_SdsHiQf3LpR6dpIW:b9911i5)*

**Comment by siyuanfeng-tri** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdX9UxwigmZ7yRPLa-R:-KdaIWcxPRDKNUCgmuSR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa03dc5b1892e455684cd1e3facc47c474feab78/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc#L101)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is better to use a enum class here 
```C++
enum class RelaxMode {
  kRelaxPosTol = 0,
  kRelaxRotTol = 1,
}
```
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdX0noLlTDQS3YGDR7F:-KdaIdpc61D3dN9yQqSm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa03dc5b1892e455684cd1e3facc47c474feab78/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.h#L46)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add documentation to clarify that the unit of the `rot_tol` is in radians, not in angle degrees?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by david-german-tri** [comment]
Am I correctly understanding that this PR introduces a new, substantive library, `iiwa_ik_planner`, with no test coverage?  If so, I'm raising a red flag.  Tests are [required](http://drake.mit.edu/developers.html#review-process) in Drake, and this directory doesn't seem to have any.

```
drake/examples/kuka_iiwa_arm$ find . -name "*_test.cc"
drake/examples/kuka_iiwa_arm$ grep -R "EXPECT" .
drake/examples/kuka_iiwa_arm$ 
```

> I really think each of the demo executables in PR needs a does it run unit test added

"does it run" tests are only epsilon better than no tests at all.  Without assertions, it's impossible for other developers to know whether they've broken your code, and pretty difficult for you yourself to know.  (I had this problem just a few weeks ago when adding BUILD files to this directory.)

>  i am not planning to add unit tests for now.. however we should think about what's a good meaningful unit test.

Please consider reversing the priorities here.  Unit tests are vital.  Even assertions on regression-level tests would be a great improvement, if that's an easier place to start.

I've tagged this "do not merge" pending further discussion.

**Comment by siyuanfeng-tri** [comment]
@david-german-tri @RussTedrake can i make a dev dir in kuka_iiwa? and move all these there? i am about to hit a point where everything i do hits the 500 line cap, and it's hard to write 2k lines of stuff, chop it up, and dance between branches.

**Comment by siyuanfeng-tri** [comment]
i am going to add a test for the ik stuff. 
i agree it's very important, and we never had much test for ik related stuff.

**Comment by david-german-tri** [comment]
> @david-german-tri @RussTedrake can i make a dev dir in kuka_iiwa? and move all these there?

I don't know, but here are some questions that might lead us to an answer.  Is this code important to our business?  If it breaks, do we care?  Does anyone besides you need to use, develop, or maintain it?  Will any code outside of `dev` need to depend on it?  Will it ever need to "graduate" from `dev`?

**Comment by naveenoid** [comment]
Reviewed 1 of 4 files at r3.
Review status: 5 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdbzvkrjuU8R2LbWawn:-KdbzvkrjuU8R2LbWawo:b-b8n2zr) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L75)):*
> ```cpp
>     EXPECT_TRUE((pos_diff.array() <= kUpperBound.array()).all());
>     EXPECT_TRUE((pos_diff.array() >= kLowerBound.array()).all());
> ```

BTW: tagging @sammy-tri on this..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdcaOeLOukty7r9qD6L:-KdcaOeMUF57mytgNYIo:bevgne5) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
> ```cpp
>     EXPECT_TRUE((pos_diff.array() >= kLowerBound.array()).all());
> 
>     // to Hongkai: this fails sometimes with pretty large error, any ideas?
> ```

When the tolerance is `1E-3`, in some test the angle is `1.3E-3`, exceed the tolerance.

The reason is that our constraint has a very flat gradient  for small tolerance, so although the angle exceed the tolerance by `0.3E-3`, the constraint is violated by a much smaller number, below the solver numerical tolerance.

The constraint for the orientation is that `cos(θ) >= cos(θ_tolerance)`. Unfortunately the cos function has a very flat gradient around θ=0. 

I chose to compute cos(θ) because for two quaternions `q1` and `q2`, the cos of the angle θ can be easily computed, as `cos(θ) = 2 * (q1.conj() * q2)^2 - 1`, because `cos(θ/2) = q1.conj() * q2`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdcaOeLOukty7r9qD6L:-Kdcd44YFHFC0LcgW-QJ:btqo3wn) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

When the tolerance is `1E-3`, in some test the angle is `1.3E-3`, exceed the tolerance.

The reason is that our constraint has a very flat gradient  for small tolerance, so although the angle exceed the tolerance by `0.3E-3`, the constraint is violated by a much smaller number, below the solver numerical tolerance.

The constraint for the orientation is that `cos(θ) >= cos(θ_tolerance)`. Unfortunately the cos function has a very flat gradient around θ=0. 

I chose to compute cos(θ) because for two quaternions `q1` and `q2`, the cos of the angle θ can be easily computed, as `cos(θ) = 2 * (q1.conj() * q2)^2 - 1`, because `cos(θ/2) = q1.conj() * q2`
</blockquote></details>

Ah, instead of writing `q1.conj() * q2`, I should have written `q1.transpose() * q2`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by siyuanfeng-tri** [comment]
Review status: 4 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-KdcaOeLOukty7r9qD6L:-Kdd56hilAKWSYTkcwB7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ah, instead of writing `q1.conj() * q2`, I should have written `q1.transpose() * q2`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 4 of 13 files at r1, 3 of 5 files at r2, 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-Kdd9dUWtTh_uj2n9ddo:bnfp4nl)*

**Comment by naveenoid** [comment]
I have your pick and place demo (including this PR's IK wrapper) working properly. I will most likely expand on the unit test added here and added some logic for seeding in a followup PR. Meanwhile just a general comment : Perhaps this IK stuff needs to move to a subfolder? I guess eventually it will sit in a common location in a future drake/manipulation/

Other than these comments.. :lgtm:  

---

Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde7LDOhXyZV9Dhy_1Y:-Kde7LDPxII4Mcp7aVFh:b-mklp6y) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/BUILD#L45)):*
> ```Python
> )
> 
> drake_cc_library(
> ```

BTW: does this library have to be "iiwa_ik" ? I see very little IIWA specificity in this code, perhaps it can just be called manipulator_ik_planner and a TODO somewhere saying that it should move to a common location similar to the factory builder classes in iiwa_world.

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde6EXFhWo7nzwlG1z4:-Kde6EXGvD74lDfI7pcP:b-glh6m0) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc#L105)):*
> ```cpp
>     kRelaxRotTol = 1
>   };
> ```

BTW: I think these magic numbers need a little explanation comment on top. Might be useful for future tweaking.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde6a5-bNgeATVXSTNw:-Kde6a5-bNgeATVXSTNx:b-ahhzje) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
> ```cpp
>     EXPECT_TRUE((pos_diff.array() >= kLowerBound.array()).all());
> 
>     // to Hongkai: this fails sometimes with pretty large error, any ideas?
> ```

BTW: I guess this can stay as a TODO comment for now..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-Kde6jPvRCT__v-v0Srg:b9jahiv)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde6a5-bNgeATVXSTNw:-KdfxEO0vJYuI8PmBVv_:b-w40guz) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: I guess this can stay as a TODO comment for now..
</blockquote></details>

@naveenoid , sorry I do not get it, do you suggest an alternative way to implement angle_diff < tol?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231)*

**Comment by siyuanfeng-tri** [comment]
after discussing this with the relevant parties, i have decided to close this pr and resubmit another one, in which: 
all the new stuff will be in dev, including the little test;
i won't remove any of the existing functionality;
the next pr (script for the pick and place demo) will also live in dev. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde7LDOhXyZV9Dhy_1Y:-KdgWlLnnJsxIyh0Df6w:byqgelu) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/BUILD#L45)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: does this library have to be "iiwa_ik" ? I see very little IIWA specificity in this code, perhaps it can just be called manipulator_ik_planner and a TODO somewhere saying that it should move to a common location similar to the factory builder classes in iiwa_world.
</blockquote></details>

we are going to do a major cleaning pass at some point anyway. might as well just wait till that time. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde6EXFhWo7nzwlG1z4:-KdgW5J6URTgOLENS7jh:bihev42) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/iiwa_ik_planner.cc#L105)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: I think these magic numbers need a little explanation comment on top. Might be useful for future tweaking.
</blockquote></details>

unfortunately i don't have too much to say about these. pat seems to believe none of this matters, if the ik can't solve it with the tightest constraint, it won't be able to solve it. i have seen a couple cases these hack did help.. so it remains a black magic now. need to hook it up to a visualization tool to see the failed solution, printing out the infeasible constraints would also be helpful. i tried, but i couldn't get it to print what constraint failed though. 

---

*[drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-Kde6a5-bNgeATVXSTNw:-KdgWcx5VrtcH_YN2d-0:box4til) ([raw file](https://github.com/robotlocomotion/drake/blob/de47bf03148574833e28043d05dc3708d68da09a/drake/examples/kuka_iiwa_arm/test/iiwa_ik_test.cc#L76)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@naveenoid , sorry I do not get it, do you suggest an alternative way to implement angle_diff < tol?
</blockquote></details>

i think constraining cos is fine. it'd be nice to say it in the header file though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5231#-:-KdgWry7-OEoQVPVs8Zn:bze5sjy)*

**Pull request closed without merging**
