### PR TITLE
Only add non-zero coefficient to SCS/Clarabel LMI constraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously we also add zero coefficient, which is still correct, but unnecessary.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241#-:-OCdS8FSCKrXZJAAOZxm:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241#-:-OCf1oep-OYzeyrkOSyU:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241#-:-OD8LvF9BlCoGzM9aILm:b-c9pjop)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241#-:-OD8_e7xBj9jN_B5RLSQ:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22241#-:-OD8_irm-ZjDTu4wwdPN:b-safpmt)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),AlexandreAmice

**Pull request merged**
