### PR TITLE
py mbp: Bind operators for SpatialVector, shifting for velocity and force

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I would like to use this in Python in ANzu

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098#-:-MHbESw9-EN2yX3Sk5L2:b-gvyt5w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/math_py.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14098#-MHbexwo-QCiPWVIMhye:-MHbexwo-QCiPWVIMhyf:b-yx3uzk) ([raw file](https://github.com/robotlocomotion/drake/blob/b807bf95b7752da503fe67379ac51ddc818a05ea/bindings/pydrake/multibody/math_py.cc#L45)):*
> ```cpp
>           doc.SpatialVector.get_coeffs.doc_0args_const)
>       .def_static("Zero", &Class::Zero, doc.SpatialVector.Zero.doc)
>       .def(-py::self)
> ```

Need to suppress warnings here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@ericcousineau-tri I'm inclined to defer review until CI has been resolved. Do you agree?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098#-:-MHl7oXz6LZ-tyXVBrBy:b-5pa0en)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Eh, I think this is just slapping compiler flags around, so I think a basic review could work before / after.
The solution will just involve changing the `#ifdef`s below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098#-:-MHlRLFx3ms1yQlM5kHV:b-ejrv52)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll go ahead and assume you've addressed CI and review it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098#-:-MHlSvyW-Fy2UWAj5mF9:b-fgrgg7)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one question about suppressing warnings.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098#-:-MHlWSn2C0hs5t72vNlU:bd2ao1o)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/math_py.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14098#-MHbexwo-QCiPWVIMhye:-MHlTwsT2pcLAjIXukFa:b-3yd7gw) ([raw file](https://github.com/robotlocomotion/drake/blob/b807bf95b7752da503fe67379ac51ddc818a05ea/bindings/pydrake/multibody/math_py.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Need to suppress warnings here.
</blockquote></details>

Suppressed now?
___
*[bindings/pydrake/multibody/math_py.cc, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14098#-MHlUzIp2yNiG8kci_ME:-MHlUzIp2yNiG8kci_MF:b-ys6jld) ([raw file](https://github.com/robotlocomotion/drake/blob/c125769c22f3c4e9a2cf48a2b29c6c6ee0113f64/bindings/pydrake/multibody/math_py.cc#L19)):*
> ```cpp
> 
> #pragma GCC diagnostic push
> // Different than `symbolic_py.cc`, we must also enable this for clang 9 on
> ```

With file-wide scope on this pragma, there is a possibility of letting unintended things into the file on other classes. Could you put in a comment for why that's not a bad thing?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/math_py.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14098#-MHbexwo-QCiPWVIMhye:-MHlZKn11jIYglKNkqHd:bnle8ss) ([raw file](https://github.com/robotlocomotion/drake/blob/b807bf95b7752da503fe67379ac51ddc818a05ea/bindings/pydrake/multibody/math_py.cc#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Suppressed now?
</blockquote></details>

OK Yup!
___
*[bindings/pydrake/multibody/math_py.cc, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14098#-MHlUzIp2yNiG8kci_ME:-MHlZvu8CZWgcayBlKY3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c125769c22f3c4e9a2cf48a2b29c6c6ee0113f64/bindings/pydrake/multibody/math_py.cc#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

With file-wide scope on this pragma, there is a possibility of letting unintended things into the file on other classes. Could you put in a comment for why that's not a bad thing?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14098)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Comment by EricCousineau-TRI** [comment]
Skipping slow build (given that it passed in prior rev)

**Pull request merged**
