### PR TITLE
Add ros config files

### PR DESCRIPTION
**Pull request by jamiesnape**
Still more work to be done, but this adds config files and makes the directory structure a little more catkin-like.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2653)

### CODE REVIEW

**Comment by sherm1** [comment]
Feature review: +@liangfok
Platform review: +@sherm1

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-:-KLHTU8qa6O567YiYadS:1434642787)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-:-KLHob-CPURBCelUOR-G:-1868698381)*

**Comment by sherm1** [comment]
Platform one comment; otherwise :lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/ros/drake/CMakeLists.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-KLIDY0hOV1ji0iLWxs0:-KLIDY0hOV1ji0iLWxs1:-1711776186) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb0ea0fdcabd2cae4c8561bd47eabcf2e34568e/drake/ros/drake/CMakeLists.txt#L1)):*
> ```CMake
> if(GTEST_FOUND)
> ```

Should remove GTEST_FOUND guards -- gtest is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-:-KLIDgKsrSSVQMX8Sdy9:1307031194)*

**Comment by jamiesnape** [comment]
Cancelling new CI build since the changed code is not run anyway.

**Comment by jamiesnape** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/ros/drake/CMakeLists.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-KLIDY0hOV1ji0iLWxs0:-KLIG9WKFVJy9cPPIjc9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7fb0ea0fdcabd2cae4c8561bd47eabcf2e34568e/drake/ros/drake/CMakeLists.txt#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should remove GTEST_FOUND guards -- gtest is required.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653)*

**Comment by liangfok** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653)*

**Comment by liangfok** [comment]
Since this PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2300/ and the subsequent change does not impact this result, I believe this PR is ready to be merged once @sherm1 resolves the last remaining thread.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-:-KLIQidA2B3G6qn3g5Uv:983570377)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2653#-:-KLIkQpAlIBJvfXupNYZ:1417088721)*

**Pull request merged**
