### PR TITLE
Split (some) IK solver interface code into new functions

### PR DESCRIPTION
**Pull request by sammy-tri**
In preparation for converting IK trajectory optimization to the new solver API, split out parts of the existing IK implementation to allow for a bit of code reuse.

Also splits out the DecisionVariable* declarations from Optimization.h because (1) that file was really long already and (2) I wanted to pass around DecisionVariableView without pulling all of Optimization.h into inverseKinBackend.h.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2939)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-:-KNcos1f23fWJGBp_PQm:-1973176957)*

**Comment by ggould-tri** [comment]
:lgtm: pending items noted below.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/decision_variable.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcqA9v5ujr-sv92RX0:-KNcqA9wm0RyLtiyXzZg:429072138) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/solvers/decision_variable.h#L1)):*
> ```objc
> #pragma once
> ```

FTI -- Because this code is a straight move, I am not reviewing it.  If it were under review I would defect its comment formatting and test (non-) coverage.

---

*[drake/systems/plants/inverseKinBackend.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcrNyaA9OVbESXUl2h:-KNcrNyaA9OVbESXUl2i:1756028707) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/systems/plants/inverseKinBackend.h#L67)):*
> ```objc
> /// Add a single time linear posture constraint to @p prog at time @p
> /// t covering @p vars.  @p nq is the number of positions in
> /// underlying model.
> ```

FYI -- grammar.  "the underlying model" perhaps?

---

*[drake/systems/plants/inverseKinBackend.h, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcrihqrvgtZ4Lyo-0l:-KNcrihry3vEtm8jJ4vQ:-332354316) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/systems/plants/inverseKinBackend.h#L74)):*
> ```objc
> 
> /// Add a single time linear posture constraint to @p prog at time @p
> /// t covering @p vars.  @p nq is the KinematicsCacheHelper for the
> ```

There is no parameter named `nq`.  You probably mean `kin_helper`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-:-KNcrs2ygLCs8Bx_eLIS:617404291)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/decision_variable.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcqA9v5ujr-sv92RX0:-KNcsrU5X9xBCnrVlZTh:225332703) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/solvers/decision_variable.h#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FTI -- Because this code is a straight move, I am not reviewing it.  If it were under review I would defect its comment formatting and test (non-) coverage.
</details>
FYI, I suspect that was supposed to start with FYI...

---

*[drake/systems/plants/inverseKinBackend.h, line 67 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcrNyaA9OVbESXUl2h:-KNct6zesSfmYrOWhri7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/systems/plants/inverseKinBackend.h#L67)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- grammar.  "the underlying model" perhaps?
</details>
Done.

---

*[drake/systems/plants/inverseKinBackend.h, line 74 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcrihqrvgtZ4Lyo-0l:-KNct6GL60KksFHZmC4a:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/systems/plants/inverseKinBackend.h#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> There is no parameter named `nq`.  You probably mean `kin_helper`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/solvers/decision_variable.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNcqA9v5ujr-sv92RX0:-KNcuSScXQFOtr9Mo5tt:-501611594) ([raw file](https://github.com/robotlocomotion/drake/blob/9a87ba9e51276e5922d8227377fb674d49657d4f/drake/solvers/decision_variable.h#L1)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI, I suspect that was supposed to start with FYI...
</details>
Ayup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939)*

**Comment by sammy-tri** [comment]
+@david-german-tri for being today's on-call reviewer (and I'm tomorrow's, so he might have gotten this one anyway)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-:-KNcv1XuZ4sOEr0gnYvh:1176032029)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 94 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNdFJwi_ZfKrz0jhbc5:-KNdFJwi_ZfKrz0jhbc6:1279503743) ([raw file](https://github.com/robotlocomotion/drake/blob/81bb0482da573aedb052e161da392c300dee3981/drake/systems/plants/inverseKinBackend.cpp#L94)):*
> ```cpp
> 
>   const SingleTimeLinearPostureConstraint* st_lpc =
>       static_cast<const SingleTimeLinearPostureConstraint*>(constraint);
> ```

Why isn't this just the type of the argument to begin with?  I see that would just bump the pseudo-RTTI-dispatch up the call stack by one, but still.  It's baked right into the function name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 94 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNdFJwi_ZfKrz0jhbc5:-KNgqMELydyAUZpXxn0O:-315574571) ([raw file](https://github.com/robotlocomotion/drake/blob/81bb0482da573aedb052e161da392c300dee3981/drake/systems/plants/inverseKinBackend.cpp#L94)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why isn't this just the type of the argument to begin with?  I see that would just bump the pseudo-RTTI-dispatch up the call stack by one, but still.  It's baked right into the function name.
</details>
To remove the two-line cast at the call sites (which I guess there is only one of now and will only be two later), which have determined the category but don't need to look into the constraint beyond that.  I can move the cast to the other side if you prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 94 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-KNdFJwi_ZfKrz0jhbc5:-KNhGQcept-iTd8r1Pp1:1753078970) ([raw file](https://github.com/robotlocomotion/drake/blob/81bb0482da573aedb052e161da392c300dee3981/drake/systems/plants/inverseKinBackend.cpp#L94)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> To remove the two-line cast at the call sites (which I guess there is only one of now and will only be two later), which have determined the category but don't need to look into the constraint beyond that.  I can move the cast to the other side if you prefer.
</details>
OK, I defer to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2939#-:-KNhGYBvCHi41C0pmjRF:1417088721)*

**Pull request merged**
