### PR TITLE
[multibody] SystemDynamicsData describes both forward and inverse dynamics

### PR DESCRIPTION
**Pull request by amcastro-tri**
Part of larger SAP solver PR #16080.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169#-:-MpvnMXW0fGwlw3EUb5U:btfsfbp)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few minor things.
@ericcousineau-tri for platform review per rotation, please

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169#-:-Mpw0us30VnsdSon4-l6:b-t7xeup)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/system_dynamics_data.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-Mpw0ZITD2-KOWce-wBd:-Mpw0ZITD2-KOWce-wBe:bjqhusa) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.h#L21)):*
> ```objc
> 
>   /// Empty problem data with zero velocities.
>   SystemDynamicsData() = default;
> ```

minor: why do you need a default constructor at all? It doesn't have a unit test -- can you do without this constructor?
___
*[multibody/contact_solvers/system_dynamics_data.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-Mpw-XPm1XOsJEo-cM8p:-Mpw-XPm1XOsJEo-cM8q:b3yzqei) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.h#L47)):*
> ```objc
>   // @param Ainv The inverse of operator A, describing the forward dynamics of
>   // the system.
>   // @param v_star Predictor's step velocity v*, of size nv.
> ```

minor: please note that both the operators and v_star must have lifetimes longer than SystemDynamicsData since only references to them are stored.
___
*[multibody/contact_solvers/system_dynamics_data.h, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-MpvypWs-YWNVOQqfi7H:-MpvypWs-YWNVOQqfi7I:bolckh6) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.h#L50)):*
minor: also 
> @pre the provided operators must be square
> (I think) @pre v_star must have the same size as the provided operators
___
*[multibody/contact_solvers/system_dynamics_data.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-MpvyeFn-DIFBg9ekDon:-MpvyeFn-DIFBg9ekDoo:bdyzpz8) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.cc#L34)):*
> ```cpp
>     DRAKE_DEMAND(A->rows() == Ainv->rows());
>     DRAKE_DEMAND(A->cols() == Ainv->cols());
>     DRAKE_DEMAND(A->rows() == A->cols());
> ```

minor: this test is unneeded -- you checked it above
___
*[multibody/contact_solvers/system_dynamics_data.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-MpvzSLHDgXhXcFSNx8G:-MpvzSLHDgXhXcFSNx8H:bjc1g4t) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.cc#L37)):*
> ```cpp
>   }
>   nv_ = A != nullptr ? A->rows() : Ainv->rows();
>   DRAKE_DEMAND(v_star->size() == num_velocities());
> ```

minor: I was confused why you weren't enforcing that v_star is the same size as the operators. But now I see that the assignment to `nv_` on the previous line affects the return value of `num_velocities()`. This code would be less mysterious if you write `DRAKE_DEMAND(v_start->size() == nv_)`. Alternatively, add a comment noting that num_velocities() is just another name for nv_, the size of the operators.

**Review by EricCousineau-TRI — COMMENTED** [review]
Platform :lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169#-:-Mpw1uAcCb-QBIBE18yQ:b8qx53o)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/system_dynamics_data.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16169#-Mpw0ZITD2-KOWce-wBd:-Mpw2qaQ1pUwm3EN_OVz:bsbykdo) ([raw file](https://github.com/robotlocomotion/drake/blob/098cac52935db5e88092032780d00a31ab00b52d/multibody/contact_solvers/system_dynamics_data.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: why do you need a default constructor at all? It doesn't have a unit test -- can you do without this constructor?
</blockquote></details>

I believe you are right and I don't need it. Removed.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
we didn't assign Eric. 
+@ericcousineau-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16169#-:-MpwB33y8yrML9dgRwyZ:bgldswb)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform) (waiting on @amcastro-tri)

**Pull request merged**
