### PR TITLE
pydrake math: Permit convenience overloads for math functions (autodiff, symbolic). Fix autodiff operator overloads

### LINKED ISSUE #8388: pydrake: Replace custom operator overloads with `py::self` pybind magic
Per Slack conversation (and TODO items in the code):
https://github.com/RobotLocomotion/drake/blob/70405614ade432f1ee59a3a9a90de0d318ff6cbd/bindings/pydrake/symbolic_py.cc#L20

> russtedrake [8:33 AM]
> i've got a new one here... in my drake/bindings/pydrake/.. test file, I can write
> ```
> from pydrake.all import AutoDiffXd
> 
> x = AutoDiffXd(1, [1., 0.])
> y = x/2.
> ```
> and all is well, but in my jupter notebook (using out of source build), I get
> ```
> TypeError                                 Traceback (most recent call last)
> <ipython-input-19-93a35ae2c56a> in <module>()
>       2 
>       3 x = AutoDiffXd(1, [1., 0.])
> ----> 4 y = x/2.
> 
> TypeError: unsupported operand type(s) for /: 'pydrake._autodiffutils_py.AutoDiffXd' and 'float'
> ```
> (edited)
> and `dir(AutoDiffXd)` reports
> 
> ```
> ['__add__',
> ...
>  '__rtruediv__',
> ...
>  '__truediv__',
> ...
>  'value']
> ```
> which looks right
> 
> sean.curtis [9:13 AM]
> Missing `__div__`? (edited)
> Oops...`__truediv__`....
> nevermind
> 
> sean.curtis [10:40 AM]
> So, in python 2, `__div__` is used when `__future__.division` is not in effect. I would suggest that this is the problem you're having. In Jupyter, `__future__.division` is *not* in effect, so it's looking for `__div__` which you *don't* have. How's that?
> 
> eric.cousineau [10:58 AM]
> @russtedrake On this matter, @soonho-tri had shown me about `py::self` which you can use to define overloads.
> 
> When looking at the internals for `pybind11/operators.h`, it actually handles switching between `__div__` and `__truediv__` based on the Python version, so this could be solvable by using the following operator definition style:
> ```.def(py::self * X{})```
> Implemented here:
> https://github.com/pybind/pybind11/blob/master/include/pybind11/operators.h#L59-L64
> 
> Caveat is, there is not 'wrapper" option for `AutoDiffXd` (for calling `eval`); however, it'd be relatively trivial to make `pybind11` support this.
> 
> Is this something you'd like? (edited)
> 
> soonho-tri [11:01 AM]
> You can find more examples at https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/symbolic_py.cc#L51-L54.

\cc @RussTedrake @soonho-tri @SeanCurtis-TRI

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #8388 

Steps / options:
- ~Upstream changes~
  - ~Teach `pybind` operator `.def` methods to wrap functions, or~
  - ~Just make an external `def_op` for wrapping (maybe simplest?). A tiny slice of https://github.com/RobotLocomotion/pybind11/pull/12 would help.~ This ended up not really needing `eval`, most likely how `py::self` resolves the values.
- [x] Finish this

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8389)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please. (Let me know if you'd like me to break this up.)

\cc @russtedrake This adds the centralized overloads into `pydrake.math`. I've added a note about potential non-determinism in overload order (`pybind` evaluates overloads in FIFO order), but I don't think it should be problem.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-:-L7kmAKAoKwO0esQQxk5:b-f0bpfh)*

**Comment by RussTedrake** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/math_py.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7l8Ad4meSv48BZTsSx:-L7l8Ad5obwifxryYNrS:b-cwgtpf) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/math_py.cc#L60)):*
> ```cpp
>   // N.B. The ordering in which the overloads are resolved will change based on
>   // when modules are loaded. However, there should not be ambiguous implicit
>   // conversions from `double` to {autodiff, sybmolic}, so it shouldn't be a
> ```

"sybmolic"

---

*[bindings/pydrake/test/autodiffutils_test.py, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7l8RlW32AY539HIeVH:-L7l8RlW32AY539HIeVI:b-11hli6) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/test/autodiffutils_test.py#L44)):*
> ```Python
>         self._compare_scalar(sin(c), AD(0, [1, 0]))
>         self.assertEquals(cos(fc), 1)
>         self._compare_scalar(cos(c), AD(1, [0, 0]))
> ```

nice!!  does it work for symbolic, too?  (I didn't see sin/cos in the symbolic_test diff)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/autodiffutils_py.cc, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7n4XDED-9TDzFB3OyE:-L7n4XDED-9TDzFB3OyF:bm74e40) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/autodiffutils_py.cc#L25)):*
> ```cpp
>             double value,
>             const Eigen::VectorXd& derivatives) {
>            new (&self) AutoDiffXd(value, derivatives);
> ```

BTW, I think we've updated this part? I guess it's where we have a merge conflict with the `master` in upstream. 

---

*[bindings/pydrake/math_py.cc, line 60 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7n5eeI5Y7Zwpo1VR94:-L7n5eeI5Y7Zwpo1VR95:b-jzkuhr) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/math_py.cc#L60)):*
> there should not be ambiguous implicit conversions from `double` to {autodiff, sybmolic}

FYI, I've added the following at the end of `symbolic_py.cc` file:

```c++
py::implicitly_convertible<double, drake::symbolic::Expression>();
```

Could you check if this is still OK and does not conflict with this sentence?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/test/autodiffutils_test.py, line 44 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7l8RlW32AY539HIeVH:-L7pZ53z22Qml5zM1v6k:bflb4zh) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/test/autodiffutils_test.py#L44)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nice!!  does it work for symbolic, too?  (I didn't see sin/cos in the symbolic_test diff)
</blockquote></details>

Yup!
https://github.com/EricCousineau-TRI/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/test/symbolic_test.py#L434-L471

That being said, there actually isn't a test which combines and tests all of the overloads. Will add that in. (Will block myself in this discussion.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by RussTedrake** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/autodiffutils_py.cc, line 54 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7prMHJ4UJKxFbXVpfX:-L7prMHJ4UJKxFbXVpfY:b107tcq) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/autodiffutils_py.cc#L54)):*
> ```cpp
>     math
>       .def("sin", [](const AutoDiffXd& x) { return sin(x); })
>       .def("cos", [](const AutoDiffXd& x) { return cos(x); });
> ```

btw - i need tanh, too... but was waiting for this to land before adding it.  if it's trivial for you to include, that would be awesome.  otherwise i'll do it after.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7n4XDED-9TDzFB3OyE:-L7rZsxcBjYYFkwoPOB_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/autodiffutils_py.cc#L25)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think we've updated this part? I guess it's where we have a merge conflict with the `master` in upstream. 
</blockquote></details>

Done.

---

*[bindings/pydrake/autodiffutils_py.cc, line 54 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7prMHJ4UJKxFbXVpfX:-L7rZtk_DCJ-4qNfqesP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/autodiffutils_py.cc#L54)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw - i need tanh, too... but was waiting for this to land before adding it.  if it's trivial for you to include, that would be awesome.  otherwise i'll do it after.
</blockquote></details>

Done.

---

*[bindings/pydrake/math_py.cc, line 60 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7l8Ad4meSv48BZTsSx:-L7rZuzs0KXzL5H-S4jb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/math_py.cc#L60)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"sybmolic"
</blockquote></details>

Done.

---

*[bindings/pydrake/math_py.cc, line 60 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7n5eeI5Y7Zwpo1VR94:-L7rZveLAc_S0td3XdHN:b-azibow) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/math_py.cc#L60)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> there should not be ambiguous implicit conversions from `double` to {autodiff, sybmolic}

FYI, I've added the following at the end of `symbolic_py.cc` file:

```c++
py::implicitly_convertible<double, drake::symbolic::Expression>();
```

Could you check if this is still OK and does not conflict with this sentence?
</blockquote></details>

Done. Sorry, I had worded that incorrectly - fixed the wording. Thanks!

---

*[bindings/pydrake/test/autodiffutils_test.py, line 44 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7l8RlW32AY539HIeVH:-L7r_0x28FT7Fkb4j_K4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/test/autodiffutils_test.py#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup!
https://github.com/EricCousineau-TRI/drake/blob/43711f19d88b48878a9e446eba83064e60840951/bindings/pydrake/test/symbolic_test.py#L434-L471

That being said, there actually isn't a test which combines and tests all of the overloads. Will add that in. (Will block myself in this discussion.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 3 of 9 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yo4ot1HYCL3fmFC6B:-L7yo4ot1HYCL3fmFC6C:b234n9h) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/autodiffutils_py.cc#L48)):*
> ```cpp
>     auto math = py::module::import("pydrake.math");
>     math
>       .def("sin", [](const AutoDiffXd& x) { return sin(x); })
> ```

BTW, can we have `log` here as well?

---

*[bindings/pydrake/math_py.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7ynDpgr_iifmvJxQpR:-L7ynDpgr_iifmvJxQpS:b-7060yo) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/math_py.cc#L64)):*
> ```cpp
>   // See `math_overloads_test`, which tests this specifically.
>   m
>       .def("abs", [](double x) { return fabs(x); })
> ```

BTW, I think we can have `log` here as well?

---

*[bindings/pydrake/test/math_overloads_test.py, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yc5QPJo98q-Yl0W0b:-L7yc5QQCurS-O1M1gj0:b-k7s3j4) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L75)):*
> ```Python
>             return True
>         supported = [
>             "tan", "asin", "acos", "atan2",
> ```

I think including `sin` and `cos` here is better for maintainability (to be consistent with the implementation in `autodiffutils_py.cc`)?

---

*[bindings/pydrake/test/math_overloads_test.py, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7ypP9HePc9xBlrZMmO:-L7ypP9HePc9xBlrZMmP:bq46e9t) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L80)):*
> ```Python
>         return func.__name__ in supported
> 
>     def to_float(self, y_type):
> ```

BTW, I think this variable name `y_type` is a bit misleading since it doesn't hold a type but a value, while we have `self.type` above which does hold a type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-:-L7yqciHuW9VZd-sHAtf:bg7igkv)*

**Comment by EricCousineau-TRI** [comment]
Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yo4ot1HYCL3fmFC6B:-L7z1RMA3DJY9NMmqirW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/autodiffutils_py.cc#L48)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can we have `log` here as well?
</blockquote></details>

Done.

---

*[bindings/pydrake/math_py.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7ynDpgr_iifmvJxQpR:-L7z1Nw_m3N_yFkFd93m:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/math_py.cc#L64)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think we can have `log` here as well?
</blockquote></details>

Done. Thanks for catching that!

---

*[bindings/pydrake/test/math_overloads_test.py, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yc5QPJo98q-Yl0W0b:-L7z1T7xcxAkGdkVtfIN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L75)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think including `sin` and `cos` here is better for maintainability (to be consistent with the implementation in `autodiffutils_py.cc`)?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_overloads_test.py, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7ypP9HePc9xBlrZMmO:-L7z1UWdMGesAT3846o_:b9onv0g) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L80)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think this variable name `y_type` is a bit misleading since it doesn't hold a type but a value, while we have `self.type` above which does hold a type.
</blockquote></details>

Done. Renamed to `y_T`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-:-L7z1dYbUnARQfeDYOt8:bz1t39v)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/test/math_overloads_test.py, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yc5QPJo98q-Yl0W0b:-L7z2ANpktC4VCroot9M:b-xayl6i) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L75)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI, `"sin"` and `"cos"` are not added here yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/test/math_overloads_test.py, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7yc5QPJo98q-Yl0W0b:-L7z2ajABwFsCOJLcX5W:b-kgo5df) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L75)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `"sin"` and `"cos"` are not added here yet.
</blockquote></details>

OK They're added by means of `backwards_compat + [...]`. I'd prefer not to duplicate the names until we deprecate and remove them. (If you see the list in symbolic, the list is a tad longer.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/test/math_overloads_test.py, line 75 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7yc5QPJo98q-Yl0W0b:-L7z39zICp4E4ezV0Nwv:b-4hvi0z) ([raw file](https://github.com/robotlocomotion/drake/blob/db4b3b83176a03a30730fdc723419e305a384e2a/bindings/pydrake/test/math_overloads_test.py#L75)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK They're added by means of `backwards_compat + [...]`. I'd prefer not to duplicate the names until we deprecate and remove them. (If you see the list in symbolic, the list is a tad longer.)
</blockquote></details>

Got it!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 52 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7z7tKLdMr8J5SWtaK7:-L7z7tKLdMr8J5SWtaK8:b-kip82r) ([raw file](https://github.com/robotlocomotion/drake/blob/05202c9ae1b8f170eb9b9b3d43462e1f54b14c00/bindings/pydrake/autodiffutils_py.cc#L52)):*
> ```cpp
>     .def(py::self == py::self)
>     .def(py::self == double())
>     .def(double() == py::self)
> ```

BTW, I suspect that those`.def(double() rop py::self)`s are not necessary as pybind is designed to use its reflected operator (i.e. `3.0 > ad` => `ad < 3.0`). Could you check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 52 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7z7tKLdMr8J5SWtaK7:-L7z8n6IBQwQGskQlAB3:b-da9rqr) ([raw file](https://github.com/robotlocomotion/drake/blob/05202c9ae1b8f170eb9b9b3d43462e1f54b14c00/bindings/pydrake/autodiffutils_py.cc#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I suspect that those`.def(double() rop py::self)`s are not necessary as pybind is designed to use its reflected operator (i.e. `3.0 > ad` => `ad < 3.0`). Could you check?
</blockquote></details>

Done. Thanks! Didn't realize that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389#-L7zWE_05rj5nc1l6LUh:-L7zWE_05rj5nc1l6LUi:begs88o) (no related file):*
@ericcousineau-tri , FYI, we have:

```
13:27:35 ======================================================================
13:27:35 FAIL: test_no_import_warnings (all_test.TestAll)
13:27:35 Ensures that we have no warnings (primarily from `pybind11`) when
13:27:35 ----------------------------------------------------------------------
13:27:35 Traceback (most recent call last):
13:27:35   File "./bindings/pydrake/test/all_test.py", line 21, in test_no_import_warnings
13:27:35     self.assertEquals(len(w), 0)
13:27:35 AssertionError: 2 != 0
```

FWIW, on my mac, I had a warning from `matplotlib` complaining that updating font-cache via `fc-list` takes too much time. I was able to resolve it locally so I didn't mention it before. I am not sure that this is related here though (since this is from Ubuntu build).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8389)*

**Comment by sammy-tri** [comment]
First pass complete, only one minor comment (along with whatever is going on in CI)

---

Reviewed 2 of 9 files at r1, 3 of 7 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/test/symbolic_test.py, line 8 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7znsHRMRxXKYW_I4vX:-L7znsHS3GZCoWbqpggk:bf4pi8r) ([raw file](https://github.com/robotlocomotion/drake/blob/96a2e01ad7bdc215b9258a8f69e91aff94012b29/bindings/pydrake/test/symbolic_test.py#L8)):*
> ```Python
> import numpy as np
> import pydrake.symbolic as sym
> import pydrake.math as dmath
> ```

unused?  (outside of the TODO)  possibly also true for `import math` unless there's some spooky action I'm not getting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-:-L7zoWawysg6hpGQmFHp:b-96wmgn)*

**Comment by EricCousineau-TRI** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7zWE_05rj5nc1l6LUh:-L7ztTEYcPdttGT75cHE:b-ju14b6) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ericcousineau-tri , FYI, we have:

```
13:27:35 ======================================================================
13:27:35 FAIL: test_no_import_warnings (all_test.TestAll)
13:27:35 Ensures that we have no warnings (primarily from `pybind11`) when
13:27:35 ----------------------------------------------------------------------
13:27:35 Traceback (most recent call last):
13:27:35   File "./bindings/pydrake/test/all_test.py", line 21, in test_no_import_warnings
13:27:35     self.assertEquals(len(w), 0)
13:27:35 AssertionError: 2 != 0
```

FWIW, on my mac, I had a warning from `matplotlib` complaining that updating font-cache via `fc-list` takes too much time. I was able to resolve it locally so I didn't mention it before. I am not sure that this is related here though (since this is from Ubuntu build).
</blockquote></details>

Just pushed a commit to print out the warnings; will see what they are on CI. Setting this to blocking for now.

---

*[bindings/pydrake/test/symbolic_test.py, line 8 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7znsHRMRxXKYW_I4vX:-L7ztMb2oqoj4IyTeVou:b-oqofco) ([raw file](https://github.com/robotlocomotion/drake/blob/96a2e01ad7bdc215b9258a8f69e91aff94012b29/bindings/pydrake/test/symbolic_test.py#L8)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?  (outside of the TODO)  possibly also true for `import math` unless there's some spooky action I'm not getting.
</blockquote></details>

Done. No spooky action, thankfully!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7zWE_05rj5nc1l6LUh:-L8-Bi8AC_hPc-DACHeX:bp0pd76) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Just pushed a commit to print out the warnings; will see what they are on CI. Setting this to blocking for now.
</blockquote></details>

Hmm... Did not get the same error, so yeah, seems that retesting was all that was needed?
(added in print statement)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by soonho-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-L7zWE_05rj5nc1l6LUh:-L8-Dg7I51IKYFcWork9:bz45ldz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Hmm... Did not get the same error, so yeah, seems that retesting was all that was needed?
(added in print statement)
</blockquote></details>

It seems like that was a glitch? Also I couldn't reproduce it on my Ubuntu box either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8389#-:-L8-ELB-wlpAV3h4Z91I:bnfp4nl)*

**Pull request merged**
