### PR TITLE
Add unit tests for frame and dynamic topology operations in GeometryState

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This provides the testing code for the code added in #6688 and #6774.

For the record, while it reports 744 lines of changes, that breaks down to roughly:
  - 516 lines of code
  - 142 lines of comments
  - 86 empty lines

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6813)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@avalenzu for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KrBlPyUXFSANkVqer5h:bvpmr17)*

**Comment by avalenzu** [comment]
Review pass done. Sorry that took me so long!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[drake/geometry/test/geometry_state_test.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx11OKufZCawVz6nb:-KrWx11OKufZCawVz6nc:blpjwq2) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L136)):*
> ```cpp
> 
>   // This method confirms that the stored dummy identifiers don't map to any
>   // active source identifier. This should only be invoked for scenarios where
> ```

s/active/registered

---

*[drake/geometry/test/geometry_state_test.cc, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWytV8hzuxrO-rt2Uy:-KrWytV8hzuxrO-rt2Uz:bdslo4v) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L139)):*
> ```cpp
>   // there is *only* the single source.
>   void AssertSingleTreeCleared() {
>     // confirm frames have been closed
> ```

"closed" sounds like a vestige of some previous nomenclature .

---

*[drake/geometry/test/geometry_state_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-Kra7xut0NxCm9N1j2KH:-Kra7xut0NxCm9N1j2KI:bdv24pl) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L146)):*
> ```cpp
>                            "Referenced frame \\d+ has not been registered.");
>     }
>     // confirm geometries have been closed
> ```

See previous comment on "closed."

---

*[drake/geometry/test/geometry_state_test.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraNeAEOc4TvRe45OJ9:-KraNeAEOc4TvRe45OJA:b-hy7od0) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L163)):*
> ```cpp
>   // Utility function for facilitating tests; confirms that the identified
>   // frame doesn't belong to the identified source. This explicitly tests the
>   // underlying state data structures.
> ```

Does this have to be so invasive? You'll have to modify all these tests if the internals of `GeometryState` change.

---

*[drake/geometry/test/geometry_state_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraO3eFxF9gadtBE-X2:-KraO3eFxF9gadtBE-X3:bjjd3gd) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L192)):*
> ```cpp
>   // The geometry ids created in the dummy tree instantiation.
>   vector<GeometryId> geometries_;
>   // THe id of the single-source tree.
> ```

s/THe/The/

---

*[drake/geometry/test/geometry_state_test.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOAVVCNlarHpUrUJ4:-KraOAVVCNlarHpUrUJ5:bu9umdv) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L196)):*
> ```cpp
> 
>   // The default source name.
>   const std::string source_name{"default_source"};
> ```

Should this be `kSourceName`?

---

*[drake/geometry/test/geometry_state_test.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOM9fss8WN9BaW0aW:-KraOM9fss8WN9BaW0aX:bxfm0ah) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L206)):*
> ```cpp
> }
> 
> // Confirms the registration of the source with a user-specified name, a default
> ```

Could this sentence be re-worded? It's not clear to me (from the text) what's being confirmed.

---

*[drake/geometry/test/geometry_state_test.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOnGS_SLeNFZoDS4S:-KraOnGS_SLeNFZoDS4T:bz70d7t) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L208)):*
> ```cpp
> // Confirms the registration of the source with a user-specified name, a default
> // name, and requesting the name for an invalid id. This also folds in looking
> // up source name for invalid id -- because this already implicitly tests
> ```

Antecedent of "this" is unclear here. The test? Looking up source name for invalid id?

---

*[drake/geometry/test/geometry_state_test.cc, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraP8yinwUzmu4qLwpO:-KraP8yinwUzmu4qLwpP:bn1cqgc) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L220)):*
> ```cpp
>   EXPECT_EQ(geometry_state_.get_source_name(s_id), name);
> 
>   // Case: Unique id with duplicate name.
> ```

What is the "Unique id" here? I'm only seeing the duplicate name.

---

*[drake/geometry/test/geometry_state_test.cc, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx6Ewvnhe7U7JGWKL:-KrWx6Ewvnhe7U7JGWKM:blpjwq2) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L233)):*
> ```cpp
> 
> // Tests the geometry statistics values. It uses the single-source tree to
> // create a state with interesting metrics. Also confirms the "is active"-ness
> ```

s/active/registered

---

*[drake/geometry/test/geometry_state_test.cc, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraRDR3p9BWnF9BmKjr:-KraRDR3p9BWnF9BmKjs:bnpiwf) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L303)):*
> ```cpp
>     auto test_geometry = [internal_geometries, this, s_id](int i) {
>       const auto& geometry = internal_geometries.at(geometries_[i]);
>       EXPECT_EQ(geometry.get_frame_id(), frames_[i / 2]);
> ```

It may be worth noting somewhere that this testpoint will break if someone changes the number of geometries per frame. Or perhaps this could be `frames_[i / kGeometryCount]`?

---

*[drake/geometry/test/geometry_state_test.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx8M7gvsDa0HtogUp:-KrWx8M7gvsDa0HtogUq:blpjwq2) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L317)):*
> ```cpp
> // with meaningful message.
> TEST_F(GeometryStateTest, AddFrameToInvalidSource) {
>   SourceId s_id = SourceId::get_new_id();  // This is not an active source.
> ```

s/active/registered

---

*[drake/geometry/test/geometry_state_test.cc, line 323 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraRoDjs-41fZ91RczY:-KraRoDjs-41fZ91RczZ:b-ws1ax2) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L323)):*
> can be used to acquire that source

I don't see this happening below. Am I just missing it?

---

*[drake/geometry/test/geometry_state_test.cc, line 475 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraTeXQ1UEjLYy9fWp9:-KraTeXQ1UEjLYy9fWpA:bkt1u83) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L475)):*
> ```cpp
> // Tests registration of geometry on valid source and frame. This relies on the
> // correctness of GeometryState::BelongsToSource(GeometryId, SourceId) and
> // GeometryState::GetFrameId(GeometryId) and, therefore, implicitly tests them.
> ```

Copy-paste error. This is the comment for the `RegisterGeometryGoodSource` test point.

---

*[drake/geometry/test/geometry_state_test.cc, line 505 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraTtMMnjeSUb7YEO2o:-KraTtMMnjeSUb7YEO2p:b-6npk15) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L505)):*
> ```cpp
>                                                      move(null_geometry)),
>                        std::logic_error,
>                        "Registering null geometry to frame \\d+, on source "
> ```

FYI: I missed this during the review of the source for `GeometryState`, but this error message makes it sound like it the registration actually takes place.

---

*[drake/geometry/test/geometry_state_test.cc, line 626 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraWNjLnfx3rhCbD2u7:-KraWNjMbCwwDGHR5M0e:b-kr3yl7) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L626)):*
> ```cpp
> }
> 
> // Tests the response to invalid misuse of RemoveGeometry.
> ```

"Invalid misuse" seems like a double negative ...

---

*[drake/geometry/test/geometry_state_test.cc, line 701 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraWlHI6eFdcYtIwOTY:-KraWlHI6eFdcYtIwOTZ:b-ov1nca) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L701)):*
> It examines dynamic and anchored geometry.

I don't se this happening in the test below.

---

*[drake/geometry/test/geometry_state_test.cc, line 722 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx9pI2MAghi-jkdbH:-KrWx9pI2MAghi-jkdbI:blpjwq2) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L722)):*
> ```cpp
> 
> // This tests that clearing a source eliminates all of its geometry and frames,
> // leaving the source active.
> ```

s/active/registered

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KraWurxLENO1y1lM8C2:b-7k7huy)*

**Comment by SeanCurtis-TRI** [comment]
No apologies -- this is nothing but a long hard slog into a painful jungle of unit tests.

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[drake/geometry/test/geometry_state_test.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx11OKufZCawVz6nb:-Krb8SmGBE1iPyv64bDq:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L136)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/active/registered
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWytV8hzuxrO-rt2Uy:-Krb8_q7xDxGzddjZA7K:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L139)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"closed" sounds like a vestige of some previous nomenclature .
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-Kra7xut0NxCm9N1j2KH:-Krb8dgmaZFowcWoWSUQ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L146)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

See previous comment on "closed."
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraNeAEOc4TvRe45OJ9:-Krb8hEUl0Y7-gqDwoIj:b-95s7t1) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L163)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Does this have to be so invasive? You'll have to modify all these tests if the internals of `GeometryState` change.
</blockquote></details>

I would argue it does. This is testing the internal workings of state. I want to confirm that the internal state (which ordinarily shouldn't be publicly viewable), actually does what it claims to do. I subscribe to the belief that even private methods should be unit tested.

---

*[drake/geometry/test/geometry_state_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraO3eFxF9gadtBE-X2:-Krb8wt1OqQSix2CoNyb:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L192)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/THe/The/
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOAVVCNlarHpUrUJ4:-Krb99wcNK8aX9StRjn3:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L196)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Should this be `kSourceName`?
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOM9fss8WN9BaW0aW:-Krb9iqc19Nf-TIrFtwy:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L206)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Could this sentence be re-worded? It's not clear to me (from the text) what's being confirmed.
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOnGS_SLeNFZoDS4S:-Krb9j_Ej1dBEM4YWamM:bwkcr9i) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L208)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Antecedent of "this" is unclear here. The test? Looking up source name for invalid id?
</blockquote></details>

Done (rendered moot)

---

*[drake/geometry/test/geometry_state_test.cc, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraP8yinwUzmu4qLwpO:-Krb9wvbsDJI57Jl7wxJ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L220)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

What is the "Unique id" here? I'm only seeing the duplicate name.
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx6Ewvnhe7U7JGWKL:-Krb9znUP8vCwf9kr7pK:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L233)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/active/registered
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraRDR3p9BWnF9BmKjr:-KrbAQX1xtpr0DGk4mGB:b-ijjsrm) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L303)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

It may be worth noting somewhere that this testpoint will break if someone changes the number of geometries per frame. Or perhaps this could be `frames_[i / kGeometryCount]`?
</blockquote></details>

Done -- also removed the redundant lambda. (Definitely a relic of past versions of the code).

---

*[drake/geometry/test/geometry_state_test.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx8M7gvsDa0HtogUp:-KrbAcFjkk4FjAa1-hAb:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L317)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/active/registered
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 323 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraRoDjs-41fZ91RczY:-KrbAm5ZP5xHOq2Tz1eb:bveu7vy) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L323)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> can be used to acquire that source

I don't see this happening below. Am I just missing it?
</blockquote></details>

Done It was an old feature that I killed; it broke the security. 

---

*[drake/geometry/test/geometry_state_test.cc, line 475 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraTeXQ1UEjLYy9fWp9:-KrbB-p3ab-nxUFH0kI7:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L475)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Copy-paste error. This is the comment for the `RegisterGeometryGoodSource` test point.
</blockquote></details>

Done

---

*[drake/geometry/test/geometry_state_test.cc, line 505 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraTtMMnjeSUb7YEO2o:-KrbB9UillM1ZTHdAcoT:b-rt41ey) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L505)):*
FYI I presume you'd like to see language along the lines of "Attempting..."?

I did a quick perusal on the language in this regard.  I have the following:It follows the pattern:

  - `Referenced [object] has not been registered`
  - `Querying source name for an invalid source id...`
  - `Registering new source with duplicate name...`
  - `Indicated parent id does not belong...`
  - `Referenced frame for source, but frame doesn't belong...`
  - `Trying to remove frame from source...`
  - `Trying to remove geometry from source...`

Definitely inconsistent. I like the flavor of a message of the form:

> Operation - problem

Hence the "Registering null geometry..."  But in this context it would be better as "Registering geometry; the provided geometry is null". However, some of those messages *directly* reflect the API and are directly mappable to a user action but some are internal. So, I'll probably just simplify the messages to "problem", and rely on them to look at the stack trace to detect the where.

Thoughts?

---

*[drake/geometry/test/geometry_state_test.cc, line 626 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraWNjLnfx3rhCbD2u7:-KrbDj_zh0b5OEKxmO27:bc51glc) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L626)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"Invalid misuse" seems like a double negative ...
</blockquote></details>

Done

That's very exclusionary.  What about all of the perfectly valid misuses?

---

*[drake/geometry/test/geometry_state_test.cc, line 701 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraWlHI6eFdcYtIwOTY:-KrbDxXthFMgCzsn4wCY:b-z3x7hl) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L701)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> It examines dynamic and anchored geometry.

I don't se this happening in the test below.
</blockquote></details>

Done

typo: /s/se/see  (Har, har, har!)

The error is that I didn't clean up the comment -- the anchored geometry PR hasn't been submitted yet. So, that functionality is missing from the body but ghostly present in the comment.

---

*[drake/geometry/test/geometry_state_test.cc, line 722 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx9pI2MAghi-jkdbH:-KrbENP34PkVia_H-yja:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L722)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/active/registered
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-Krb88SPE7_yWFci_uvv:b2hul9n)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 1 of 2 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-Krb_GZjyW3qZEiSB5b_:b-1hejgk)*

**Comment by avalenzu** [comment]
:lgtm: pending resolution of final "active -> registered" comment

+@ggould-tri for platform review

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/geometry/test/geometry_state_test.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx11OKufZCawVz6nb:-KrfAWWO5B7hpgg6u3Ay:bvbqdds) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L136)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not done? I still see "active source identifier" at the start of this line.

---

*[drake/geometry/test/geometry_state_test.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraNeAEOc4TvRe45OJ9:-KrfAvQP4Kwqx6AbYWpu:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L163)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I would argue it does. This is testing the internal workings of state. I want to confirm that the internal state (which ordinarily shouldn't be publicly viewable), actually does what it claims to do. I subscribe to the belief that even private methods should be unit tested.
</blockquote></details>

OK.

---

*[drake/geometry/test/geometry_state_test.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraOM9fss8WN9BaW0aW:-KrfB45xZKx1B5B7tkei:b4fm3e) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L206)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Much clearer. Thanks!

---

*[drake/geometry/test/geometry_state_test.cc, line 505 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraTtMMnjeSUb7YEO2o:-KrfCS9HF0jcRpqj5Q6b:b-ao31eh) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L505)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I presume you'd like to see language along the lines of "Attempting..."?

I did a quick perusal on the language in this regard.  I have the following:It follows the pattern:

  - `Referenced [object] has not been registered`
  - `Querying source name for an invalid source id...`
  - `Registering new source with duplicate name...`
  - `Indicated parent id does not belong...`
  - `Referenced frame for source, but frame doesn't belong...`
  - `Trying to remove frame from source...`
  - `Trying to remove geometry from source...`

Definitely inconsistent. I like the flavor of a message of the form:

> Operation - problem

Hence the "Registering null geometry..."  But in this context it would be better as "Registering geometry; the provided geometry is null". However, some of those messages *directly* reflect the API and are directly mappable to a user action but some are internal. So, I'll probably just simplify the messages to "problem", and rely on them to look at the stack trace to detect the where.

Thoughts?
</blockquote></details>

FYI: I'd propose keeping the messages that are directly mappable to user action as is. Helping the user is a good thing. I think for the internal messages,  "problem" is a good format. That being said, I'd also be fine with leaving the messages as they are.

---

*[drake/geometry/test/geometry_state_test.cc, line 626 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KraWNjLnfx3rhCbD2u7:-KrfC5uIe9lQPwLRZBid:b32vhw) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L626)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

That's very exclusionary.  What about all of the perfectly valid misuses?
</blockquote></details>

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KrfDGBV6kTo41lLdLrg:b7dm3ha)*

**Comment by SeanCurtis-TRI** [comment]
Updated

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/test/geometry_state_test.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-KrWx11OKufZCawVz6nb:-KrfI_TiAEK2vPZFOQ0a:b-yyhoew) ([raw file](https://github.com/robotlocomotion/drake/blob/36189ca6360b04b9f0ce732a23ca6cd492ad5be5/drake/geometry/test/geometry_state_test.cc#L136)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Not done? I still see "active source identifier" at the start of this line.
</blockquote></details>

Done  I'd done a search on "active" -- must've been a "go-around-the-horn" problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KrfJYfJcytpMxRnT68D:b-bu91xm)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KrfTBEzx3CyFX06TEqE:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Forgot to rebase onto master -- yesterday's merged PR caused conflicts with this one. I'll let CI spin through to make sure things are happy.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813#-:-KrfVqptABYD9VKZNpsd:b-cvzkg4)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6813)*

**Pull request merged**
