### PR TITLE
[workspace] Add drake_models regression test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Required for #13942.  Related to #17061.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19986)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

I see you've noted elsewhere that this strategy requires PRs on two repos to get a model tested. It's fine as long as we're aware -- we can always revisit that.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-:-NboWyeU2W1xjO4of5NE:bypr7gc)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/drake_models/test/parse_test.py` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-NboWUd3D0P06Ja1DpnL:-NboWUd3D0P06Ja1DpnM:b-l8iipi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1f165bfef81fc08937d03419e012276439457365/tools/workspace/drake_models/test/parse_test.py#L21)):*
> ```Python
> 
>     @staticmethod
>     def inventory():
> ```

BTW consider annotations to indicate this is a generator: https://stackoverflow.com/questions/27264250/how-to-annotate-a-generator-in-python3
___
*[`tools/workspace/drake_models/test/parse_test.py` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-NboWclIE2wRD64CnXc8:-NboWclIE2wRD64CnXc9:b-l8iipi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1f165bfef81fc08937d03419e012276439457365/tools/workspace/drake_models/test/parse_test.py#L33)):*
> ```Python
> 
>     @staticmethod
>     def get_all_models():
> ```

BTW consider annotations to indicate this is a generator: https://stackoverflow.com/questions/27264250/how-to-annotate-a-generator-in-python3

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-:-NbocZik8zZnHO7SAAqZ:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-:-NboeILEB3FOJOUyv6Bp:bnfp4nl)* status: 3 unresolved discussions

___
*[`tools/workspace/drake_models/test/parse_test.py` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-NboexKT-It7vmXpOcxN:-NboexKU3bJn23BPeZmU:b-6qooet) ([raw file](https://github.com/RobotLocomotion/drake/blob/17f42bedbaa60c25a1afc374b91871e192581b90/tools/workspace/drake_models/test/parse_test.py#L29)):*
> ```Python
>         result = Path(manifest.Rlocation(
>             "drake/tools/workspace/drake_models/inventory.txt"))
>         with open(result, encoding="utf-8") as f:
> ```

nit:  "result" is a generic name; consider a descriptive one.



_Suggestion:_
```Python
        inventory_path = Path(manifest.Rlocation(
            "drake/tools/workspace/drake_models/inventory.txt"))
        with open(inventory_path, encoding="utf-8") as f:
```
___
*[`tools/workspace/drake_models/test/parse_test.py` line 48 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-NboflAcEtchcnBr-ZHp:-NboflAcEtchcnBr-ZHq:b-s7ss6o) ([raw file](https://github.com/RobotLocomotion/drake/blob/17f42bedbaa60c25a1afc374b91871e192581b90/tools/workspace/drake_models/test/parse_test.py#L48)):*
> ```Python
>                 # We can't tell a MuJoCo file just by its suffix.
>                 runfiles = TestDrakeModels.package_xml().parent.parent
>                 if "<mujoco" in (runfiles / path).open().read():
> ```

BTW:  "What the Zalgo!?!" I exclaimed upon reading this.  Which caused me to look up mujoco files and... oh.  Oh.
They don't even have a DTD or any processing directives or...   :hangs head:  Well, Zalgo away I guess.



_Code quote:_
```Python
                if "<mujoco" in (runfiles / path).open().read():
```
___
*[`tools/workspace/drake_models/test/parse_test.py` line 58 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19986#-NboikDV-znycfrepO7I:-NboikDV-znycfrepO7J:b5ybzi) ([raw file](https://github.com/RobotLocomotion/drake/blob/17f42bedbaa60c25a1afc374b91871e192581b90/tools/workspace/drake_models/test/parse_test.py#L58)):*
> ```Python
>         all_models = list(TestDrakeModels.get_all_models())
> 
>         # Allow warnings on these models until they are repaired.
> ```

BTW, here and below, is/are there issue/s open for these files that could be cited in these comments?

**Pull request merged**
