### PR TITLE
Fix a bug in QuaternionToHopfCoordinate.

### PR DESCRIPTION
**Pull request by hongkai-dai**
The psi angle was computed incorrectly before.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-:-NNc3bMnARvA1UmoxzQf:b-7vq6ss)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
a couple of drive-by comments

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-:-NNcFlXS-F5zOslPMi1a:b-lgmd4j)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`math/hopf_coordinate.h` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-NNcDQS23kOS9EWcYzOs:-NNcDQS23kOS9EWcYzOt:b-usb3o2) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d0b0a8fc535a7e242f09dc524a35f6f9c1f33bf/math/hopf_coordinate.h#L50)):*
> ```objc
> 
> /**
>  * Convert a unit-length quaternion (w, x, y, z) (with the requirement x >= 0)
> ```

BTW did you mean w >= 0?
___
*[`math/hopf_coordinate.h` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-NNcF_0zEi-kWJQDAQTz:-NNcF_0zEi-kWJQDAQU-:bpgxtp4) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d0b0a8fc535a7e242f09dc524a35f6f9c1f33bf/math/hopf_coordinate.h#L58)):*
> ```objc
>  * φ is in the range of [0, 2pi].
>  * θ is in the range of [0, pi].
>  * If the given quaternion has w < 0, then we revert the signs of (w, x, y, z),
> ```

typo revert -> reverse

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-:-NNduc1_428E4oVBpjQh:bnfp4nl)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`math/hopf_coordinate.h` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-NNduHP3DRW5G37JYK2I:-NNduHP4781a3iF0Lqbw:b-l6mwxj) ([raw file](https://github.com/RobotLocomotion/drake/blob/62950fa2fc6ed3baf1e4a65d53b76f841f684106/math/hopf_coordinate.h#L11)):*
> ```objc
> 
> #include <cmath>
> #include <iostream>
> ```

remove

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-:-NNdxrAO8_fPOBvKjSMT:buxscyd)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`math/hopf_coordinate.h` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-NNduHP3DRW5G37JYK2I:-NNdxpSh5k9zhOUmS_6f:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/62950fa2fc6ed3baf1e4a65d53b76f841f684106/math/hopf_coordinate.h#L11)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(release notes: fix) 

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18747#-:-NNdyfZvDjwANju2MTLJ:b-q7wly)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
