### PR TITLE
Add Hyperellipsoid::Scale() functionality

### LINKED ISSUE #21976: Add a function to scale Hyperellipsoids
There is built in functionality to scale HPolyhedrons (HPolyhedron::Scale) but not hyperellipsoids. I wished to find the approximate volume of a small high-dimensional polyhedron using the MaximumLargestInscribedEllipsoid method. The solver (not using an initial guess) was required to converge to an appropriate scale (which could be anywhere from ~1e-6 to 1e-20). Instead, it seemed more appropriate to scale the hpolyhedron by some factor, 'r', then scale the inscribed ellipsoid down by the same factor. before finding the volume. 

Similar to HPolyhedron::Scale(), a Hyperellipsoid::Scale(double 'r') might be useful. For every point x on the boundary of the original ellipsoid, there would be an associated x' = r*(x-center) + center on the boundary of the returned ellipsoid. This could simply be done by uniformly scaling 'A', resulting in Hyperellipsoid(A_ / r,  center_). 

While this could have been certainly done without the need for a specialized scaling method, I figured that it seemed a natural addition. I have linked a possible solution and test [here](https://github.com/RobotLocomotion/drake/compare/master...Akshay5312:drake:master).

### PR DESCRIPTION
**Pull request by Akshay5312**
Closes #21976.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by jwnimmer-tri** [comment]
My impression from the issue discussion is that +@hongkai-dai was interested in reviewing this.  If not @hongkai-dai, just let us know.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: , thanks for the PR!

+@xuchenhan-tri for platform review please, thanks!

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-:-O8IFUPIAk3eHNJAKYBw:bpdl45y)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`geometry/optimization/test/hyperellipsoid_test.cc` line 163 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IFCUD33XJfUzG6A74:-O8IFCUD33XJfUzG6A75:bl0hp2e) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/test/hyperellipsoid_test.cc#L163)):*
> ```cpp
>   Hyperellipsoid E_scaled = E.Scale(kScale);
>   EXPECT_TRUE(CompareMatrices(E.A() / kRadius, E_scaled.A()));
>   EXPECT_TRUE(CompareMatrices(E.center(), E_scaled.center()));
> ```

BTW, could you also confirm that the volume is scaled?
```cc
EXPECT_NEAR(E.Volume() * kScale, E_scaled.Volume(), 1E-7);
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`geometry/optimization/hyperellipsoid.h` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMEqFEPDK0EPOi97q:-O8IMEqFEPDK0EPOi97r:b-h8ty3s) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.h#L80)):*
> ```objc
>   center. Any point on the boundary of the ellipsoid, x, is now translated to a
>   new point, x*, such that ||x - center|| = ||x* - center|| *
>   pow(scale, 1.0/ambient_dimension()). The volume of the resulting shape is
> ```

I want to confirm my understanding of this new function.

If ambient dimension is 1, scale is 2, and center is 0, then we have `||x|| = ||x*|| * 2`, which is more like scaling the ellipsoid by 1/2 instead of 2.



_Code quote:_
```objc
  new point, x*, such that ||x - center|| = ||x* - center|| *
  pow(scale, 1.0/ambient_dimension()). The volume of the resulting shape is
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMskE0eFC5Sn5GqaJ):*
nit, a friendly reminder to squash your commits and curate a nice commit message before merging the PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMskE0eFC5Sn5GqaJ):*
For infrequent contributors, this best left as a job for the platform reviewer, not the contributors:

> In that case, when the PR is ready to merge, the author of a PR has three choices for how to proceed:
>
> (1) Wait for the assigned Platform Reviewer to “Squash and merge” the PR.
> ...

-- https://drake.mit.edu/reviewable.html#curated-commits

Our goal is to make contributions easy, and it's easiest for us to just tidy up the message when squashing to master on the contributor's behalf.  New contributors don't have permissions to land things on master, anyway.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`geometry/optimization/hyperellipsoid.h` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMEqFEPDK0EPOi97q:-O8ISaLa6o565mVXgglj:b-6062mh) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.h#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I want to confirm my understanding of this new function.

If ambient dimension is 1, scale is 2, and center is 0, then we have `||x|| = ||x*|| * 2`, which is more like scaling the ellipsoid by 1/2 instead of 2.
</blockquote></details>

Good catch, it should be dividing the pow(scale, 1.ambient_dimension), instead of multiplying.
___
*[`geometry/optimization/hyperellipsoid.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8ISlT4B7MS_KrxdAtZ:-O8ISlT4B7MS_KrxdAt_:b1i52el) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.cc#L180)):*
> ```cpp
> Hyperellipsoid Hyperellipsoid::Scale(double scale) const {
>   DRAKE_THROW_UNLESS(scale > 0);
>   return Hyperellipsoid(A_ / std::pow(scale, 1.0 / ambient_dimension()),
> ```

Should be multiplying the pow(scale, 1/ambient_dimension()) here.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMskE0eFC5Sn5GqaJ):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For infrequent contributors, this best left as a job for the platform reviewer, not the contributors:

> In that case, when the PR is ready to merge, the author of a PR has three choices for how to proceed:
>
> (1) Wait for the assigned Platform Reviewer to “Squash and merge” the PR.
> ...

-- https://drake.mit.edu/reviewable.html#curated-commits

Our goal is to make contributions easy, and it's easiest for us to just tidy up the message when squashing to master on the contributor's behalf.  New contributors don't have permissions to land things on master, anyway.
</blockquote></details>

My intention was to prevent accidental merges, but I forgot new contributors don't have the bits.

@Akshay5312 apologies for the confusion!
___
*[`geometry/optimization/test/hyperellipsoid_test.cc` line 163 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IFCUD33XJfUzG6A74:-O8IWe874WXGFQamjobg:brtbl7f) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/test/hyperellipsoid_test.cc#L163)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, could you also confirm that the volume is scaled?
```cc
EXPECT_NEAR(E.Volume() * kScale, E_scaled.Volume(), 1E-7);
```
</blockquote></details>

This test would have caught it.

**Comment by Akshay5312** [comment]
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)_ status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)
> 
> _[`geometry/optimization/hyperellipsoid.h` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8IMEqFEPDK0EPOi97q:-O8IMEqFEPDK0EPOi97r:b-h8ty3s) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.h#L80)):_
> 
> > ```objc
> >   center. Any point on the boundary of the ellipsoid, x, is now translated to a
> >   new point, x*, such that ||x - center|| = ||x* - center|| *
> >   pow(scale, 1.0/ambient_dimension()). The volume of the resulting shape is
> > ```
> 
> I want to confirm my understanding of this new function.
> 
> If ambient dimension is 1, scale is 2, and center is 0, then we have `||x|| = ||x*|| * 2`, which is more like scaling the ellipsoid by 1/2 instead of 2.
> 
> _Code quote:_
> 
> ```objc
>   new point, x*, such that ||x - center|| = ||x* - center|| *
>   pow(scale, 1.0/ambient_dimension()). The volume of the resulting shape is
> ```

Oops, thanks for catching this. I'll be sure to fix it.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

**Review by Akshay5312 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/hyperellipsoid.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8ISlT4B7MS_KrxdAtZ:-O8JmmvcA59a2Sjud9SO:b94x7v3) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.cc#L180)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should be multiplying the pow(scale, 1/ambient_dimension()) here.
</blockquote></details>

Would that not scale the volume inversely? My understanding is that x on the boundary of the original ellipsoid (x s.t. ||A * (x-center)||^2 = 1) would be transformed to x' s.t (x'-center) = (x-center)/r,  a point closer to the center. 
It looked like the volume test passed!

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

___
*[`geometry/optimization/hyperellipsoid.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8ISlT4B7MS_KrxdAtZ:-O8KS-e2Bc0G7QTYPCj0:b-4ttino) ([raw file](https://github.com/RobotLocomotion/drake/blob/91837afd037bc4e8c036452cfd5cfac75611571b/geometry/optimization/hyperellipsoid.cc#L180)):*
<details><summary><i>Previously, Akshay5312 wrote…</i></summary><blockquote>

Would that not scale the volume inversely? My understanding is that x on the boundary of the original ellipsoid (x s.t. ||A * (x-center)||^2 = 1) would be transformed to x' s.t (x'-center) = (x-center)/r,  a point closer to the center. 
It looked like the volume test passed!
</blockquote></details>

Ah right, I forgot the definition of the ellipsoid is (x-center)ᵀAᵀA(x-center) ≤ 1.

**Review by Akshay5312 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Akshay5312)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8_4nZ8DPyTCPH7OTXv:-O8_4nZ9EvmkSRtvCXSx:brce048) (no related file):*
Hi! Reviewable states that the PR is 'waiting on' me, but I cannot identify what is left to do. All discussions seem resolved (sans combining commits, but I do not believe I have the permissions to do that). Is there something I am missing? Thanks!

___

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-:-O8_VFC4BLSuxGxnoQfC:bm9o57a)* status: LGTM missing from assignee xuchenhan-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21985#-O8_4nZ8DPyTCPH7OTXv:-O8_V9zB-YjFDFb9zKBZ:b-vm5oqh) (no related file):*
<details><summary><i>Previously, Akshay5312 wrote…</i></summary><blockquote>

Hi! Reviewable states that the PR is 'waiting on' me, but I cannot identify what is left to do. All discussions seem resolved (sans combining commits, but I do not believe I have the permissions to do that). Is there something I am missing? Thanks!
</blockquote></details>

The PR is waiting for me to squash and merge. Sorry for the delay.

___

**Comment by xuchenhan-tri** [comment]
:lgtm:

**Pull request merged**
