### PR TITLE
Made RigidBody::robotnum private. Renamed it to be model_id_

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #2902 by making `RigidBody::robotnum` private with get/set accessors. I also renamed the member variable to be `model_id_` to match current terminology. This is an incremental PR towards future PRs that will eventually result in the complete elimination of the `model_id` abstraction.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2903)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2958/ and is thus ready for feature review. +@amcastro-tri for feature review since this touches `RigidBody*` classes.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNQ7fyzmTi64V4qjbLW:-1015022478)*

**Comment by amcastro-tri** [comment]
Same problem with diffs here. I see #2900 and #2902 changes here. Not big deal, we'll just work these PR's in order if that works for you.

**Comment by liangfok** [comment]
SGTM. -@amcastro-tri until #2902 is merged.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNT45RkvolWCi02gOCU:-1474880507)*

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Many thanks!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNYYxRBYPOkzHurf7Rh:1495215921)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
Reviewed 4 of 18 files at r2, 1 of 2 files at r4.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNY_sUYWVTn6iD-qMGe:-KNY_sUYWVTn6iD-qMGf:-1626800483) ([raw file](https://github.com/robotlocomotion/drake/blob/9cb32affa3570bb6401faa301828e5c21b6b652e/drake/systems/plants/RigidBody.cpp#L21)):*
> ```cpp
>       collision_filter_ignores(DrakeCollision::NONE_MASK),
>       parent(nullptr) {
>   model_id_ = 0;
> ```

You can value initialize these guys right at the place they are declared

---

*[drake/systems/plants/RigidBody.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNYaiDKVbYMaWttRpo3:-KNYaiDKVbYMaWttRpo4:662110447) ([raw file](https://github.com/robotlocomotion/drake/blob/9cb32affa3570bb6401faa301828e5c21b6b652e/drake/systems/plants/RigidBody.cpp#L21)):*
> ```cpp
>       collision_filter_ignores(DrakeCollision::NONE_MASK),
>       parent(nullptr) {
>   model_id_ = 0;
> ```

You can value initialize these guys right at the place they are declared with the curly braces. It'll look like (in the header) `int body_index{}` and then the initialization in the different constructors is not needed anymore, neat.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903)*

**Comment by liangfok** [comment]
@amcastro-tri I addressed your comments. PTAL. Thanks.

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNY_sUYWVTn6iD-qMGe:-KNYdOrqg7Mnfxu54y-x:514232271) ([raw file](https://github.com/robotlocomotion/drake/blob/9cb32affa3570bb6401faa301828e5c21b6b652e/drake/systems/plants/RigidBody.cpp#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> You can value initialize these guys right at the place they are declared
</details>
I updated `model_id_` to initialize it at the time of declaration. To avoid merge conflicts, I'll update the rest in future PRs that make them private.

---

*[drake/systems/plants/RigidBody.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNYaiDKVbYMaWttRpo3:-KNYeINZMOgxMsh6cZ-c:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9cb32affa3570bb6401faa301828e5c21b6b652e/drake/systems/plants/RigidBody.cpp#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> You can value initialize these guys right at the place they are declared with the curly braces. It'll look like (in the header) `int body_index{}` and then the initialization in the different constructors is not needed anymore, neat.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNYeYtjtqVtJN0YGZD4:-135296492)*

**Comment by sherm1** [comment]
Platform review: :lgtm:, one BTW comment. I appreciate these bite-sized PRs -- they are nice to review!

---

Reviewed 4 of 18 files at r2, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 230 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNYikvmtsHv4uu5WFtn:-KNYikvmtsHv4uu5WFto:1357678127) ([raw file](https://github.com/robotlocomotion/drake/blob/ff147938419e4a1e12a373218696a114aae43b8b/drake/systems/plants/RigidBody.h#L230)):*
> ```objc
> 
>   // A unique ID for each model. It uses 0-index, starts from 0.
>   int model_id_{};
> ```

BTW, if you are counting on this to be initialized to 0, IMO it is more clear to write:
```c++
int model_id_{0};
```
although it is doing that anyway so your discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNYj42yw72AKaYrPSKH:-1175641702)*

**Comment by liangfok** [comment]
Waiting on @amcastro-tri for another round of feature review.

---

Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 230 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-KNYikvmtsHv4uu5WFtn:-KNYjks9tUaDzbe-lPy7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ff147938419e4a1e12a373218696a114aae43b8b/drake/systems/plants/RigidBody.h#L230)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, if you are counting on this to be initialized to 0, IMO it is more clear to write:
> ```c++
> int model_id_{0};
> ```
> although it is doing that anyway so your discretion.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNYjnA4PPkXR4hD05Z8:-302541108)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2903#-:-KNZCmBDo6Z-3Lfa6BX9:1417088721)*

**Pull request merged**
