### PR TITLE
Disable some sanitizers the new automotive smoke test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7896)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-asan please
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-tsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-asan please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-tsan please

**Comment by EricCousineau-TRI** [comment]
+@ericcousineau-tri for feature and platform review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7896#-:-L42I8T06zKQWEv3xqcX:bnax1v0)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

Should the LCM issue be tracked in another issue?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7896#-:-L42IBWX0cam8-5YgEjQ:bgyhahz)*

**Comment by jwnimmer-tri** [comment]
The follow-up is in #7897.  I'm not sure its worth figuring out why liblcm isn't working correctly when run outside of a cc_test (or whatever the cause is); if we see another build break, we can look into it then.  For now, I think the test_lang_filters is the more important thing.

**Pull request merged**
