### PR TITLE
[workspace] Add LICENSE and tagging for common_robotics_utilities

### LINKED ISSUE #15673: Tagging Dependencies
I would like to use Drake but I am only able to use tagged code. There are a handful of dependencies that are untagged and are forks, so I cannot file an issue on their repository. These are:

1. Optitrack_driver: https://github.com/RobotLocomotion/optitrack-driver.
2. Styleguide: https://github.com/RobotLocomotion/styleguide
3. Voxelized_geometry_tools: https://github.com/ToyotaResearchInstitute/voxelized_geometry_tools
4. clang_cindex_python3: https://github.com/wjakob/clang-cindex-python3
5. common_robotic_utilities: https://github.com/ToyotaResearchInstitute/common_robotics_utilities

I would file an issue directly on the main repositories (from which the forks were made) but these repo's seem to be ahead of the main repositories. if it is possible could the commit being used by Drake be tagged? I can submit a PR to change the tools/workspace/*/repository.bzl files but I cannot tag these projects as I am not a maintainer.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15673.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri and +@rpoyner-tri for all reviews, please.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825#-:-Mkc-U-w1N4hyQje6pBF:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @calderpg-tri and @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15825#-MkgdO_y2qwwMW1D87EM:-MkgdO_z0i0yDCaaLaCX:b-aghrgh) ([raw file](https://github.com/robotlocomotion/drake/blob/2308e986ef17557d4d5abed418a878f7bf1d36d0/doc/_pages/release_playbook.md#L165)):*
> ```Markdown
>          [ToyotaResearchInstitute/common_robotics_utilities](https://github.com/ToyotaResearchInstitute/common_robotics_utilities/releases)
>          and check whether that commit already has an associated release tag.
>       2. If not, then create a new release named ``v0.0.foo`` where ``foo`` is
> ```

Oops, our release staff don't have the bits to tag a new release yet.

@calderpg-tri would you like to give Write access to the accounts listed below, or would you instead prefer that I change the instructions here to ping you when we need to tag new releases of c-r-u?

Accounts for Write access:
* EricCousineau-TRI
* ggould-tri
* jwnimmer-tri
* rpoyner-tri
* sammy-tri

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15825#-MkgdO_y2qwwMW1D87EM:-MkgpvoMA2WRyx6-viAx:bpfpmg8) ([raw file](https://github.com/robotlocomotion/drake/blob/2308e986ef17557d4d5abed418a878f7bf1d36d0/doc/_pages/release_playbook.md#L165)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, our release staff don't have the bits to tag a new release yet.

@calderpg-tri would you like to give Write access to the accounts listed below, or would you instead prefer that I change the instructions here to ping you when we need to tag new releases of c-r-u?

Accounts for Write access:
* EricCousineau-TRI
* ggould-tri
* jwnimmer-tri
* rpoyner-tri
* sammy-tri
</blockquote></details>

Access added, both for CRU and VGT where I expect a similar need will emerge in the near future

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15825#-MkgdO_y2qwwMW1D87EM:-MkhAjcy0TT_Ueg9VDjn:bcacuin) ([raw file](https://github.com/robotlocomotion/drake/blob/2308e986ef17557d4d5abed418a878f7bf1d36d0/doc/_pages/release_playbook.md#L165)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Access added, both for CRU and VGT where I expect a similar need will emerge in the near future
</blockquote></details>

Thanks!

I've confirmed by cutting a tag for the most recent commit (as used by Drake v0.34.0).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15825#-:-MkhNCzo5W_AQ5fiHvOd:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),calderpg-tri (waiting on @jwnimmer-tri)

**Pull request merged**
