### PR TITLE
[workspace] Upgrade meshcat to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/meshcat-dev/meshcat/pull/179

Closes: #21314.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21313)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21313)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/meshcat/repository.bzl` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21313#-Nvc-hEW8uoWRx-cRNcB:-Nvc-hEW8uoWRx-cRNcC:b-1u9f3f) ([raw file](https://github.com/RobotLocomotion/drake/blob/7f9c0a257d0d457ea0da5f799af963d52faa88a6/tools/workspace/meshcat/repository.bzl#L13)):*
> ```Starlark
>         drake/tools/workspace/meshcat/README.md for details.
>         """,
>         commit = "c0cff8e6990db8e9fb968e6309f9ca16c9dbd3b1",
> ```

Working

Needs sha from master

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews (and meshcat manual test testing), please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21313)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/meshcat/repository.bzl` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21313#-Nvc-hEW8uoWRx-cRNcB:-Nvc5pj71jNFV9d1dPeQ:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/7f9c0a257d0d457ea0da5f799af963d52faa88a6/tools/workspace/meshcat/repository.bzl#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs sha from master
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21313#-:-Nvc8pU9D-uGDcS_yDdH:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
