### PR TITLE
Add sphinx documention of pydrake

### PR DESCRIPTION
**Pull request by jamiesnape**
There are a few issues at the moment. `sphinx-apidoc` cannot detect pure C extensions, so the skeleton `.rst` files have had to be hand-coded, and the pure Python documentation causes large numbers of warnings (promoted to errors) and is interspersed with Doxygen notation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9578)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Would love to see (a) somehow making an optional Sphinx build that doesn't require `pydrake` being built (when changing the quick docs) and (b) auto-generating the `doc/pydrake/**.rst` files.

However, we can handle that later.

**Comment by EricCousineau-TRI** [comment]
For current docstrings, will briefly tinker with a custom `sphinx` plugin, like [napolean](https://github.com/sphinx-contrib/napoleon), but to use our existing Doxygen -> GSG Python docstring converter.

**Comment by EricCousineau-TRI** [comment]
Things I'd like to fix, ordered in terms of priority:
1. (For me) The current `TemplateClass` setup hides the documentation for actual classes, like `pydrake.systems.framework.System_[float]`; need to figure out how the documentation will come from that.
   * Hopefully there is a way to make a plugin in Sphinx to change how `autodoc` gets its items to document; this way, we could parse `TemplateClass` instances.
2. Alias / forwarding modules (e.g. `pydrake.rbtree`) currently show the documentation of all members, even if they don't belong to this module. We should tell Sphinx to explicitly mention that this is documented, maybe mention aliases, and that's it.
3. The side bar uses the whole module name, rather than nesting submodules in a list. Is there an option for this?
4. (From Jamie) All Python docstrings should be recognizable via Sphinx; I guess I don't care if we just redo the strings in code, or if we make a simple preprocessor call `mkdoc.py`s `process_comment` method.
5. Can each module be on its own page, and have a TOC at the top to browse through members? (Would yield less clutter)
6. All classes show `pybind11_builtins.pybind11_object` as their base; we should strip that from the docs.
7. Make a Sphinx build that doesn't require `pydrake` being built (when changing the high-level docs).
8. Auto-generating the `doc/pydrake/**.rst` (which I hope is not too difficult?).

@RussTedrake Can I ask how polished you want the first revision? Would you want it as-is, or are there certain items from above you'd want?
It may take until Monday to refine and polish, but Jamie's current PR will give an overview of what's bound (albeit a bit messy due to our current module organization).

**Comment by RussTedrake** [comment]
I agree with @jwnimmer-tri that having it as a subset of pages (like the C++ doxygen) is much more clear.  I think that's worth fixing even in this first pass.

Other than that, I'm of the opinion that the existence of documentation -- any documentation -- for the python bindings is much better than nothing.  I'd rather push something that is a little unsatisfying to look at and then work on cleaning it up with successive PRs.

**Comment by jamiesnape** [comment]
> It's even worse than that, though -- because previewing documentation is a "for host" target, this PR means that the entirety of libdrake.so is going to be recompiled for host mode -- doubling a large chunk of Drake's build time. I guess making it a separate sphinx site doesn't solve that, but at least it takes it off the critical path of, say, previewing developers.rst updates.

Indeed. The host needs to be able to run pydrake to get the docstrings. If you have to have a double compilation when host are target are the same, maybe you should raise the defect with Google? As it happens, I did not see that on Mac.

**Comment by jwnimmer-tri** [comment]
It's possible that the formulation of the runfile binary is making it harder to prove they're the same or not?  In any case, I'm okay deferring that issue until later, as long as `bazel run doc:serve_sphinx` does not relate to / depend on the pydrake documentation.

What I'm asking for (and I think what Russ means, too) is that the http://drake.mit.edu/ looks identical to master now, except for next to "Doxygen (C++)" there is another entry "Documentation (Python)" http link, which opens a set of pages outside of the main sphinx build (i.e., a different directory, like we have with doxygen_cxx).

**Comment by jwnimmer-tri** [comment]
The host vs target is explained a bit at https://docs.bazel.build/versions/master/user-manual.html#configurations including some config switches that detail how the two build may differ.

**Comment by jamiesnape** [comment]
> What I'm asking for (and I think what Russ means, too) is that the http://drake.mit.edu/ looks identical to master now, except for next to "Doxygen (C++)" there is another entry "Documentation (Python)" http link, which opens a set of pages outside of the main sphinx build (i.e., a different directory, like we have with doxygen_cxx).

Modulo the sidebar entry, this is exactly what you would have got with PR. Just happened to be built at the same time...

**Comment by jwnimmer-tri** [comment]
> Just happened to be built at the same time.

So then that's the only piece that needs fixing.  We should be able to work on the non-API portion of the website without compiling pydrake (even in target mode).

**Comment by jamiesnape** [comment]
For reference (not for review) https://jamiesnape.github.io/drake/ has a copy of the latest generated documentation.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/doc/index.rst, line 7 at r4](https://reviewable.io/reviews/robotlocomotion/drake/9578#-LO3cuk17ut2kw-O7ZGb:-LO3cuk24qaP5zxUL57P:b-9p2jfl) ([raw file](https://github.com/robotlocomotion/drake/blob/7de9d6fcb0647232b2ffff37456719c21d0cf435/bindings/pydrake/doc/index.rst#L7)):*
> ```reStructuredText
>     :maxdepth: 1
> 
>     pydrake.all
> ```

Could we remove `pydrake.all`? At least until we can ensure that we properply document aliases.

**Comment by EricCousineau-TRI** [comment]
Created separate issue: #9599

**Pull request merged**
