### PR TITLE
common:  Add std::optional support to DRAKE_DEMAND.

### PR DESCRIPTION
**Pull request by ggould-tri**
* `std::optional`s (and `std::function`s and a few others) are
   contextually bool-convertible; this is
   why they can be used as an `if` predicate.
 * However its `operator bool` is `explicit`, so it is not
   `std::is_convertible<bool...>`.
 * By switching from `is_convertible` to `is_constructible` we
   allow `DRAKE_DEMAND(optional_thing)` to work in the same
   way as `if(optional-thing)`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14172)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+(status: commits are properly curated) (first commit passed CI)
+@jwnimmer-tri (original author) for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14172#-:-MIymdL62fzyr10M5WdZ:b-k5x7bq)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
For the record -- I have noticed this PR and it's in my TODO queue, but it tickles some `symbolic::Expression` questions that I'm having a hard time articulating, nevermind deciding whether this change is correct.  I'll revisit it once I have some headspace open for careful thought.

**Review by ggould-tri — COMMENTED** [review]
Understandable -- it's a subtle and potentially far-reaching change.  If you'd like to start a wider discussion on #cpp that might also be reasonable.

And there's no hurry:  It's mostly an aesthetic issue on my part (I like lots of optionals but I hate the machine-gun idiom) and has no downstream urgency.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14172#-:-MJ84DvtChdAiUf3Z5Q5:b-8ay6xr)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
For my own aesthetics, I'm a fan of `DEMAND(foo.has_value());` for the same reason I say `DEMAND(bar != nullptr);` -- I want to be clear in the code and error message about the predicate in question, without neither explicit nor implicit conversion to bool.  In other words, we could forbid the machine gun in our GSG, without needing this PR as a prereq.

**Review by sherm1 — COMMENTED** [review]
FWIW I also prefer the spelled-out condition for the same reason.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14172#-:-MJ8OA0T9DqwZ4Vzu94Z:b-zbuxmc)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
I think with two platform reviewers in agreement on this not being the way forward, I'm going to withdraw this PR.  The style question can be left to another time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14172#-:-MJ8OYxGABgVd8J2itSB:b-brpsfz)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Pull request closed without merging**
