### PR TITLE
Add initial/final cost functions and input limits to DirectTrajectoryOptimization

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3098)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@lucy-tri for feature review (@hongkai-dai may also be an interested party)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOk_jWA1ouvZZjAm-_j:bge9vhm)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOka8LHrF5iK_wH-5AW:-KOka8LHrF5iK_wH-5AX:bvvhwl) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L72)):*
> ```cpp
>   Eigen::VectorXd lb_all(num_inputs_ * N_);
>   Eigen::VectorXd ub_all(num_inputs_ * N_);
>   for (int i = 0; i < N_; i++) {
> ```

++i instead of i++?

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 105 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOkartRTv3nGxqHiNrO:-KOkartRTv3nGxqHiNrP:b-6fi0lg) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L105)):*
> ```cpp
> 
>     TaylorVecXd wrapped_x(num_states_ + 1);
>     wrapped_x(0) = x.head(num_time_samples_).sum();
> ```

x.head(num_time_samples_-1)?

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOkbDkz6JokrQlR3wyv:-KOkbDkz6JokrQlR3wyw:bwfdllg) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L54)):*
> ```objc
>    * Add upper and lower bounds on the input values.
>    */
>   void SetInputBounds(const Eigen::VectorXd& lower_bound,
> ```

I am in favor of `AddInputBounds` instead of `SetInputBounds`. The latter implies that if there was an input bound, we can overwrite that bounds. But what we do here is to impose additional constraint on the input bounds. So if we
```
prog->AddInputBounds(-1,1);
prog->AddInputBounds(0,2);
```
The input bounds should be `(0,1)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Comment by sammy-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOka8LHrF5iK_wH-5AW:-KOkcFr9cmMj2d1Gs7Mt:btul4ee) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L72)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> ++i instead of i++?
</details>
https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement --  "For simple scalar (non-object) values there is no reason to prefer one form and we allow either."

Though I'm noting this annoys some reviewers, so perhaps I should consider switching in the future for the sake of team harmony, since I don't really care.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 105 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOkartRTv3nGxqHiNrO:-KOkd-z9MqxRk7ZtBMcO:bkz5cki) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> x.head(num_time_samples_-1)?
</details>
Done.  Good catch!

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOkbDkz6JokrQlR3wyv:-KOkh5aWSMTxbsL-njvl:biveazt) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8dbc1129571dc7052b2cf67c2e2eb09943cb4f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L54)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I am in favor of `AddInputBounds` instead of `SetInputBounds`. The latter implies that if there was an input bound, we can overwrite that bounds. But what we do here is to impose additional constraint on the input bounds. So if we
> ```
> prog->AddInputBounds(-1,1);
> prog->AddInputBounds(0,2);
> ```
> The input bounds should be `(0,1)`.
</details>
facepalm...   that's actually what the current implementation does.  Fixed comments and function name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOknH8N69W7d9-O5XdE:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOko9y6YqYaIlYbsVrG:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@david-german-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOkuMmRtegADk8SDDTH:b-rhk18b)*

**Comment by sammy-tri** [comment]
-@david-german-tri (who seems quite busy and whose review day is over anyway) +@ggould-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOp-euSoykPBuYlCKgJ:b-dnldz1)*

**Comment by ggould-tri** [comment]
:lgtm: pending a comment request noted below.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 97 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp-w51OT2Ur-eqxcH_:-KOp-w51OT2Ur-eqxcHa:bv5bqbn) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L97)):*
> ```cpp
>   void Eval(const Eigen::Ref<const Eigen::VectorXd>& x,
>             Eigen::VectorXd& y) const override {
>     throw std::runtime_error("Non-Taylor constraint eval not implemented.");
> ```

If a simple copy-paste of the Taylorized implementation with the Taylor lines removed is not adequate, the reason needs to be documented.  If it is adequate, why not do it or TODO it?

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 107 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp39Ts7cb6hqx0rQBZ:-KOp39Ts7cb6hqx0rQB_:bca0ai9) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L107)):*
> ```objc
>    *
>    * @param f A callable which meets the requirments of
>    * OptimizationProblem::AddCost().
> ```

FYI -- should `AddCost` here be `MakeCost` as that is what is actually called?  I am unsure but please consider.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 112 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp1lILVLL3cfYbRLjj:-KOp1lILVLL3cfYbRLjk:b-zhnn5r) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L112)):*
> ```objc
>   typename std::enable_if<
>       !std::is_convertible<F, std::shared_ptr<Constraint>>::value,
>       std::shared_ptr<Constraint>>::type
> ```

Wow.  Just... wow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOp3IwvTD_eH56OlPGf:b-l5gtws)*

**Comment by sammy-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc, line 97 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp-w51OT2Ur-eqxcH_:-KOpKTBKRd6QRHDGfZqe:b-hukn99) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.cc#L97)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> If a simple copy-paste of the Taylorized implementation with the Taylor lines removed is not adequate, the reason needs to be documented.  If it is adequate, why not do it or TODO it?
</details>
Added TODO.

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 107 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp39Ts7cb6hqx0rQBZ:-KOpKfnoIi2XMFZwM_is:bvcjp10) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L107)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- should `AddCost` here be `MakeCost` as that is what is actually called?  I am unsure but please consider.
</details>
Both functions have the same requirement (and it would be very strange for them to diverge)

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 112 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp1lILVLL3cfYbRLjj:-KOpKpeDeV1U8xSvYwfw:b-ciwefn) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L112)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Wow.  Just... wow.
</details>
Yeah, that was a cut-and-paste job from OptimizationProblem.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Comment by sammy-tri** [comment]
I'm sorry, but I really want to move this along and it's blocking other work.  I'm going to dismiss the remaining discussions because of the LGTM.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-:-KOpaWnGF11Y2dxHiOSr:b-2fjgzp)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 112 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp1lILVLL3cfYbRLjj:-KOtYgN-XJP1url6nPmG:b-491v81) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L112)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Yeah, that was a cut-and-paste job from OptimizationProblem.  :)
</details>
The worst thing is, that means it was probably a copy-paste from _my_ code and it _still_ threw me for a while

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Comment by liangfok** [comment]
*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 112 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3098#-KOp1lILVLL3cfYbRLjj:-KOtcw7M1AMsSOe0GM9V:bejvku1) ([raw file](https://github.com/robotlocomotion/drake/blob/1f89d73576039db50cdff8570544906f62b24c88/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L112)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> The worst thing is, that means it was probably a copy-paste from _my_ code and it _still_ threw me for a while
</details>
Oh the trials and tribulations of the English language. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3098)*

**Pull request merged**
