### PR TITLE
models: Add YCB subset

### LINKED ISSUE #10024: Include YCB objects in drake examples
this involves resolving the licensing issues first.
then curating the model files to our preferred formats. (related to #10023)
then deciding if they live in drake or in a separate model repository.  (e.g. as prototyped in a manipulation station dev branch)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #10024

Supersedes #10518

Requires:
- [x] https://github.com/RobotLocomotion/models/pull/5

\cc @kmuhlrad @RussTedrake @jwnimmer-tri 

Prolly should wait for upstream stuff to get figured out before reviewing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10532)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Aye, duly noted. Let's give it one more round, but if it requires much more, then we go that approach.

**Comment by EricCousineau-TRI** [comment]
At current rev (6f7cafe46), things are looking good!
> image

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please

**Pull request merged**
