### PR TITLE
Fix installed libraries on MacOS

### PR DESCRIPTION
**Pull request by fbudin69500**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6819)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: on the first commit.  I will kick the second commit over to +@soonho-tri for review and testing.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install.py.in, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsSYcS5QkPoUTsLVH:-KrCsSYd5K5FZg364VF8:b-u8wrx1) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L13)):*
> ```
> subdirs = set()
> prefix = None
> libs = {}
> ```

Should the code in this file turn into a class with member data, instead of globals?

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrCsBpLZ32A62TUMaNd:bvmpzpr) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
> ```
> 
>     if dst.endswith('.so') or dst.endswith('.dylib'):
>         libs[os.path.basename(dst)] = (dst_full, installed)
> ```

If an `install(foo, bar)` pair is duplicated in `<<actions>>`, doesn't this risk overwriting `installed` to be `False` and skipping the fixup?

---

*[tools/install.py.in, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsYxNjs7DEb-HZDQy:-KrCsYxNjs7DEb-HZDQz:bt0ccl1) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L89)):*
> ```
>                          libs[dep_basename][0],
>                          dst_full]
>                     )
> ```

At what point does the interesting code in this file move from `install.py.in` into a separate `py_library` that gets its own python unit tests?  Or perhaps more generally, how is `fix_library_rpaths`'s correctness covered by Drake's CI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrCrv4x1Eo62zlsbCJX:bw7js1n)*

**Comment by fbudin69500** [comment]
I removed a 'strip()' call when cleaning up my code in the first release. 'r2' just corrects that problem.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/install.py.in, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsSYcS5QkPoUTsLVH:-KrDAOrl6HWfC65zqXiT:b-afl9w4) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should the code in this file turn into a class with member data, instead of globals?
</blockquote></details>

I am not sure it is worth it to convert this script to a class, but it is possible.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrDAaCMqmKbJK0_TI7z:b-lntwi3) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If an `install(foo, bar)` pair is duplicated in `<<actions>>`, doesn't this risk overwriting `installed` to be `False` and skipping the fixup?
</blockquote></details>

I think this: https://github.com/RobotLocomotion/drake/blob/master/tools/install.bzl#L256-L264
Probably covers most (if not all) cases of duplication. A check could be added directly in the script to add an extra safety net.

---

*[tools/install.py.in, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsYxNjs7DEb-HZDQy:-KrDAlDCN2gvAzRSPMOg:b-4qd0et) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

At what point does the interesting code in this file move from `install.py.in` into a separate `py_library` that gets its own python unit tests?  Or perhaps more generally, how is `fix_library_rpaths`'s correctness covered by Drake's CI?
</blockquote></details>

Indeed, there is no test for now. Maybe for another PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrDAwhNrHmcEzEYPgiI:b-wotilx)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrDCAmBfNj9sJDSL2Tq:b42xh5x) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

I think this: https://github.com/RobotLocomotion/drake/blob/master/tools/install.bzl#L256-L264
Probably covers most (if not all) cases of duplication. A check could be added directly in the script to add an extra safety net.
</blockquote></details>

Sure, but then it seems worth a fail-fast here, instead of silently being wrong.

---

*[tools/install.py.in, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsYxNjs7DEb-HZDQy:-KrDCNNt9y69IDggY8M5:b-4j7ocm) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L89)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Indeed, there is no test for now. Maybe for another PR?
</blockquote></details>

I will let @soonho-tri decide, since he's the one who gets to own all of the OSX problems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrDr1J_UF5ewb8MhrIJ:b-ioqduq)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.py.in, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsYxNjs7DEb-HZDQy:-KrGi78MV32brheBaxw7:b-48ule0) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I will let @soonho-tri decide, since he's the one who gets to own all of the OSX problems.
</blockquote></details>

+1 for adding test(s) for `fix_library_rpaths`. Doing it in another PR is fine with me.

---

*[tools/install.py.in, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrGiZn9hapqI9J1QW9v:-KrGiZn9hapqI9J1QW9w:b-l6scvo) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2b878af61309499f8fdef9aa5189007166d36/tools/install.py.in#L57)):*
> ```
>         print("[Up to date] %s" % dst)
> 
>     if dst.endswith('.so') or dst.endswith('.dylib'):
> ```

BTW, I don't see any `.dylib` files installed. Do we have a plan to do so in the future?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.py.in, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrGiZn9hapqI9J1QW9v:-KrH3XOWqcf7d5y3DY3E:b-ko1hbq) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2b878af61309499f8fdef9aa5189007166d36/tools/install.py.in#L57)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I don't see any `.dylib` files installed. Do we have a plan to do so in the future?
</blockquote></details>

BTW I can think of only two `.dylib`s that would be installed, both of which are from the pre-built `drake-visualizer`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.py.in, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrGiZn9hapqI9J1QW9v:-KrHC2y3KhUACFjtfSOV:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2b878af61309499f8fdef9aa5189007166d36/tools/install.py.in#L57)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I can think of only two `.dylib`s that would be installed, both of which are from the pre-built `drake-visualizer`.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by fbudin69500** [comment]
Thanks for checking. The best way I have to check is to run tools that actually use the installed libraries and make sure that they run. I am working on making Spartan use drake/bazel and this is how I uncovered the issue. Compiling Spartan and running Director's tests is how I made sure that this PR was working.

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrHsMDy8DaFBX8KS1Hl:b-ovwaw7) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure, but then it seems worth a fail-fast here, instead of silently being wrong.
</blockquote></details>

Good idea.

---

*[tools/install.py.in, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsYxNjs7DEb-HZDQy:-KrHsSJXW6K12gGDw9GQ:b-nrnelf) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L89)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

+1 for adding test(s) for `fix_library_rpaths`. Doing it in another PR is fine with me.
</blockquote></details>

Ok, I'll create another PR for the tests.

---

*[tools/install.py.in, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrGiZn9hapqI9J1QW9v:-KrHry318bNMiMu4F7aO:b2itx7c) ([raw file](https://github.com/robotlocomotion/drake/blob/36c2b878af61309499f8fdef9aa5189007166d36/tools/install.py.in#L57)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

This was more as a safety as usually dynamic libraries on Mac are *.dylib . Maybe it is not relevant in this case. I can remove it but it doesn't cost much to leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrHsXPuM0LwARKlja_C:b-e50hm8)*

**Comment by fbudin69500** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrGgjP8Ba9V9AlpGTjk:-KrI2_q1whpT3hy4hBOe:b-896fix) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can we remove this line https://github.com/RobotLocomotion/drake/blob/master/tools/package_drake.sh#L3 with this PR?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrIFgddntFK-VCIO97u:bwqw04v) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Good idea.
</blockquote></details>

The fail-fast seems to be going to great lengths to only enforce non-duplicate at the last possible moment, in the fewest possible cases.  If truly L256 prevents duplicates, why not just fail immediately here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by fbudin69500** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrWVfOoRhXNI6XMKE9B:b9b1lsk) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The fail-fast seems to be going to great lengths to only enforce non-duplicate at the last possible moment, in the fewest possible cases.  If truly L256 prevents duplicates, why not just fail immediately here?
</blockquote></details>

It enables to only perform this "multiple" check in the case of MacOS. I'll simplify the code since as you mentioned the duplicate library case should never arise anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install.py.in, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrCsBpKvfgLpLmKZ220:-KrWX1wzzmHwQD-ZlBL3:b-ucfkn4) ([raw file](https://github.com/robotlocomotion/drake/blob/93fcd2e1c58f3175e1add9c14f057ead36fb356d/tools/install.py.in#L58)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

It enables to only perform this "multiple" check in the case of MacOS. I'll simplify the code since as you mentioned the duplicate library case should never arise anyway.
</blockquote></details>

Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by fbudin69500** [comment]
@drake-jenkins-bot retest this please

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrWglVMdau84Rox4kHE:bzdwe9o)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrWhZrrb1b1IRCaLzO1:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jwnimmer-tri** [comment]
Thanks!  My feature review is complete (already posted LGTM).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrWj0jvGhttih1S3kdZ:b968a60)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-:-KrWwuDlMFPJZp6ZGGT3:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrX0MBiya832qfgTYUa:-KrX0MBiya832qfgTYUb:b2te2in) (no related file):*
Needs platform review (or else for someone here to validate that they have a platform hat on).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrX0MBiya832qfgTYUa:-KrXBVYdIl-2IUsacPF9:b-6w1rk8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs platform review (or else for someone here to validate that they have a platform hat on).
</blockquote></details>

+@jwnimmer-tri Platform review please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrX0MBiya832qfgTYUa:-KrXFS9fVleUn6NktS5w:b-896fix) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

+@jwnimmer-tri Platform review please
</blockquote></details>

Done.

---

*[tools/install.py.in, line 70 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXEP_Hl6pyUHf64g0l:-KrXEP_IPlzXhS9IbVjM:b-pjdbnv) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L70)):*
> ```
> 
> def fix_library_rpaths():
>     # Only fix libraries that are installed now
> ```

FYI I wish all of the comments here used punctuation, but I am not finding any rule that says its required.

---

*[tools/install.py.in, line 83 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXEeqS5MZCAsUL4okJ:-KrXEeqS5MZCAsUL4okK:b-gky98g) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L83)):*
> ```
>         # Check if library dependencies are specified with relative paths
>         p = Popen(["otool", "-L", dst_full], stdout=PIPE, stderr=PIPE)
>         file_output, _ = p.communicate()
> ```

This ignores the return code of `otool`.  Is that by design?  If so, please comment as such.  If not, consider `subprocess.check_output`.

---

*[tools/install.py.in, line 99 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXFDQnoV3trVG-8lYb:-KrXFDQnoV3trVG-8lYc:b8ofrxb) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L99)):*
> ```
>                  libs[dep_basename][0],
>                  dst_full]
>             )
> ```

The two `check_call` invocations within this file are inconsistent about how much to indent this closing paren.  I suspect the first instance is correct, but at least be consistent.  (I ran pycodestyle locally, and it doesn't seem to care which one is used!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by fbudin69500** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install.py.in, line 70 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXEP_Hl6pyUHf64g0l:-KrXO37U7n5Qq2H2yVRy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I wish all of the comments here used punctuation, but I am not finding any rule that says its required.
</blockquote></details>

Done.

---

*[tools/install.py.in, line 83 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXEeqS5MZCAsUL4okJ:-KrXO5ByCiAb9YG5XwJd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This ignores the return code of `otool`.  Is that by design?  If so, please comment as such.  If not, consider `subprocess.check_output`.
</blockquote></details>

Done.

---

*[tools/install.py.in, line 99 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6819#-KrXFDQnoV3trVG-8lYb:-KrXO6EXlCIJ7uMGAsHR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/845bae167f4700aa66a22840daadf546b2699ec6/tools/install.py.in#L99)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The two `check_call` invocations within this file are inconsistent about how much to indent this closing paren.  I suspect the first instance is correct, but at least be consistent.  (I ran pycodestyle locally, and it doesn't seem to care which one is used!)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6819)*

**Pull request merged**
