### PR TITLE
[geometry] Add bindings for collision filter manager and declaration

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Related to #15115. This binds the new C++ APIs into pydrake.

Relates #15089.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15130)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15130#-:-MbINnYF4u08l-vKuxmc:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15130#-:-MbJEAQs1-sYNim0-hHm:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for platform review (on Monday, as per schedule).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15130#-:-MbJESZbAdc05tQujRVK:btko5id)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: do not merge) +(status: do not review) 

I think I've got a solution so that the manager is *properly* not dependent on T. However, I think I have to push a couple more PRs before I bind and deprecate. Hold on while I confirm this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15130#-:-MbNzSPs-39XS_1o9bjf:b-ikfued)* status: LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge" (waiting on @EricCousineau-TRI)

**Comment by SeanCurtis-TRI** [comment]
I think I need to change the new API before I do bindings. Closing this in favor of an alternate PR train.

**Pull request closed without merging**
