### PR TITLE
setup: Deprecate Bionic-specific option --with-kov

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #13391

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please.

**Review by jwnimmer-tri — COMMENTED** [review]
See one small redirect, below.  Otherwise LGTM.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-TVUN7Cxv2MrEMw9_m:ble1j0c)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[setup/ubuntu/install_prereqs.sh, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16938#-N-TV1bC9B0bS5uyFOoX:-N-TV1bC9B0bS5uyFOoY:bc8wk7a) ([raw file](https://github.com/robotlocomotion/drake/blob/9c662722b02707c2de7d016160b30b74aacf7964/setup/ubuntu/install_prereqs.sh#L33)):*
> ```Shell
>     --with-kcov)
>       source_distribution_args+=(--with-kcov)
>       ;;
> ```

nit This stanza needs to remain intact, through deprecation (see below).
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16938#-N-TV87iEdc7RJ5PYuNU:-N-TV87jBzLIJzOFtdQV:b-il2kvf) ([raw file](https://github.com/robotlocomotion/drake/blob/9c662722b02707c2de7d016160b30b74aacf7964/setup/ubuntu/source_distribution/install_prereqs.sh#L33)):*
> ```Shell
>     # "universe" apt repository.
>     --with-kcov)
>       with_kcov=1
> ```

This removal will cause even focal users to fail, if they were still passing `--with-kcov` (even though it had no effect).  We should keep this option-parsing code intact, but have it print a deprecation warning (with removal date 3+ months away).
___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16938#-N-TVJyU8kl6P9TgFy-u:-N-TVJyV7UAqQrw_QZ_h:b-lbpesu) ([raw file](https://github.com/robotlocomotion/drake/blob/9c662722b02707c2de7d016160b30b74aacf7964/setup/ubuntu/source_distribution/install_prereqs.sh#L94)):*
> ```Shell
> codename=$(lsb_release -sc)
> 
> # On Bionic, developers must opt-in to kcov support; it comes in with the
> ```

FYI it's fine to remove this block now.  Only the option parsing stuff needs to be deprecated.

**Review by BetsyMcPhail — COMMENTED** [review]
Output from testing on my local machine:

```
sudo ./setup/ubuntu/install_prereqs.sh
...
bazel is already at the desired version 5.1.0
WARNING: The --with-kcov option is deprecated and should no longer be used.
install_prereqs: success
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-Tk-pR1aI58xXADFkS:bhpoj66)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16938#-N-TV87iEdc7RJ5PYuNU:-N-TjrGJ7GuHh24aBKlX:brdw464) ([raw file](https://github.com/robotlocomotion/drake/blob/9c662722b02707c2de7d016160b30b74aacf7964/setup/ubuntu/source_distribution/install_prereqs.sh#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This removal will cause even focal users to fail, if they were still passing `--with-kcov` (even though it had no effect).  We should keep this option-parsing code intact, but have it print a deprecation warning (with removal date 3+ months away).
</blockquote></details>

Thanks for the reminder.

**Review by BetsyMcPhail — COMMENTED** [review]
+@sherm1 for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-TkL0q4F8c7XgJgnzo:bu0bkqk)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-Tm7Bl7HGvbdU4Z9zn:b-n37teh)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail and @sherm1)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16938#-N-Tm3Cm5QJj_r1yspsm):*
nit When merging, fix the typo in the subject line s/kov/kcov/

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-VrumQ3YvTh8wcNOHJ:b8qx53o)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by sherm1 — COMMENTED** [review]
+(release notes: newly deprecated) 
assign +@jwnimmer-tri to satisfy Reviewable

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16938#-:-N-Vs-Q24Sx6bpfZjNSd:bdzyclo)* status: 1 unresolved discussion (waiting on @BetsyMcPhail)

**Pull request merged**
