### PR TITLE
Implement ImageToLcmImageArrayT

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This PR also includes an example executable that combines both `RgbdCamera` and `ImageToLcmImageArrayT`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6233)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Kla6bqYAbr-wxZ1D3Fw:b-6wg1k9)*

**Comment by EricCousineau-TRI** [comment]
*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaVl202CUPUFgtxumP:-KlaVl202CUPUFgtxumQ:bd7513c) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L67)):*
> ```cpp
>       label_frame_name_(label_frame_name) {
>   color_image_input_port_index_ =
>       DeclareAbstractInputPort(systems::Value<ImageBgra8U>()).get_index();
> ```

Is there a way to 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by EricCousineau-TRI** [comment]
Just a few minor comments. PTAL when you have a chance - thanks!

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaR_cImi3QUaP5jKkz:-KlaR_cMGLhTTK38Vms1:b-auw8s2) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/CMakeLists.txt#L38)):*
> ```CMake
>   list(APPEND drakeSensors_SRC_FILES rgbd_camera.cc vtk_util.cc)
>   list(APPEND drakeSensors_HEADERS rgbd_camera.h vtk_util.h)
>   list(APPEND drakeSensors_TARGET_LINK_LIBRARIES drakeRendering vtkIO vtkRendering)
> ```

BTW This may create conflicts with #6152, as these seem to be VTK 5.x libraries:
https://github.com/RobotLocomotion/drake/pull/6152/files#diff-9d97c6f37a211b8ee749a9c41719bcf0R49

However, it does look like (down below) that this is presently broken for VTK >6.x elsewhere, so I can submit my a separate PR based on this:
https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:hotfix/pr/6152
(Problem is, I don't think this will be shared with the `test/` subdirectory, and thus would violate IWYU unless we make a function.)

@jamiesnape Any comments on this?

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaVeYedEu0KW-7rTEK:-KlaVeYf80Nt6thyuUaq:b1d51y4) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L26)):*
> ```cpp
> template <PixelType kPixelType>
> void Compress(const Image<kPixelType>& image, image_t* msg) {
>   msg->compression_method = image_t::COMPRESSION_METHOD_ZLIB;
> ```

Is there a way to make compression optional / selectable?

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaUdNFDvvwuP4ICnYc:-KlaUdNGqDESPWzur8jw:bl0hfo) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L46)):*
> ```cpp
> 
> template <PixelType kPixelType>
> void PackImageToLcmImageT(const Image<kPixelType>& image,
> ```

BTW Siyuan has a PR in flight that may help to address this issue: #6192.
However, it does not presently support multiple input ports, but we could start to consider ways to generalize multiple, possibly optional, ports (which may be easy enough using parameter packs w/ pointers.)

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaV1fbFwUdEolJgaAA:-KlaV1fcvABj3NYkfNI7:b-d63srk) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L53)):*
> ```cpp
>   msg->width = image.width();
>   msg->height = image.height();
>   msg->row_stride = image.kNumChannels * msg->width * sizeof(image.at(0, 0)[0]);
> ```

nit Rather than `sizeof(image.at(0, 0)[0]`, could we do something like `sizeof(ImageTraits<kPixelType>::ChannelType)`, to make the intent more clear?
Or even make a helper, that is something to the effect of `kPixelSize = kNumChannels * kChannelSize`?

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaVl202CUPUFgtxumP:-KlaVpYvVW8ZlZr7HpGd:b-kt3fkf) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a way to 
</blockquote></details>

Oops, sorry, meant to delete that.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaWgNDffCPxiICQDWd:-KlaWgNEJYlsgXVB1tuF:b-xetrqw) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L109)):*
> ```cpp
>       context, depth_image_input_port_index_)->GetValue<ImageDepth32F>();
> 
>   const ImageLabel16I& label_image = this->EvalAbstractInput(
> ```

Will this always require there to be non-trivial label / depth images? Are there any cases where we would just have RGB-D, or RGB-Label?
Is it possible to make to the input ports optional?

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaWYnW-dkvp9-lr6rG:-KlaWYnXy68dzYkXs59w:bmcg4bu) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L128)):*
> ```cpp
> 
>   image_t label_image_msg;
>   label_image_msg.pixel_format = image_t::PIXEL_FORMAT_LABEL;
> ```

Is there a way to incorporate these fields into `PackImageToLcmImageT`? (`pixel_format`, `channel_type`, `frame_name`?)

---

*[drake/systems/sensors/image_to_lcm_image_array_t.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaX-ddLrfqxIJz6u8a:-KlaX-dextEE59dvWfq1:b-3jzidb) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.h#L13)):*
> ```objc
> namespace sensors {
> 
> /// A ImageToLcmMessage takes as input a ImageBgra8U, ImageDepth32F and
> ```

BTW Will it ever be useful to have a different color image channel order / type, like RGB, BGR, RGBA?
Would it be possible to place this as a `TODO`?

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaXOCEzNpE1i94w290:-KlaXOCEzNpE1i94w291:b-23aal9) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L5)):*
> ```cpp
> #include <string>
> 
> #include <gflags/gflags.h>
> ```

nit If `robotlocomotion` is to be used as an external, should `#include` use `<>` rather than `""`? (Though Bazel may have an issue....)

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaXhz2E4h3zlujIAzs:-KlaXhz3ny5fNY8opDPn:bd9y0cs) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L35)):*
> ```cpp
> const double kImageArrayPublishPeriod{0.01};
> 
> const char* kCameraBaseFrameName = "camera_base_frame";
> ```

nit Not sure if we gain any benefit, but should we consider using `constexpr double X`, `constexpr char X[]`?

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZajnFMLvJZAUj5dQ:-KlaZajnFMLvJZAUj5dR:b-5ryn9f) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L45)):*
> ```cpp
> 
> int main(int argc, char* argv[]) {
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
> ```

BTW Other examples I've seen (`run_quadrotor_lqr.cc`) does the parsing directly in `::main`, then calls `do_main()`.

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZR3ps0PDw3TjDe2I:-KlaZR3q0jXYcImhH3AN:b94n8w) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L48)):*
> ```cpp
> 
>   if (argc != 2) {
>     cout << "Usage:" << endl;
> ```

Is there any motivation for using this approach rather than using `gflags` stuff?
https://github.com/gflags/gflags/blob/master/src/gflags_reporting.cc#L40

---

*[drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZuSChAYEjLWp_kt5:-KlaZuSDEimVjXcn1UIN:bs4shkl) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc#L9)):*
> ```cpp
> #include "drake/systems/framework/system_port_descriptor.h"
> 
> const int8_t robotlocomotion::image_t::PIXEL_FORMAT_BGRA;
> ```

Is there way to avoid defining these here? If you're getting linker errors, would that be an issue with upstream `lcm`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Kla_BBA6wkG-O8Lcytz:bphxlir)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaR_cImi3QUaP5jKkz:-KldafBJzADfZ1l2nhaC:buwzivh) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/CMakeLists.txt#L38)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This may create conflicts with #6152, as these seem to be VTK 5.x libraries:
https://github.com/RobotLocomotion/drake/pull/6152/files#diff-9d97c6f37a211b8ee749a9c41719bcf0R49

However, it does look like (down below) that this is presently broken for VTK >6.x elsewhere, so I can submit my a separate PR based on this:
https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:hotfix/pr/6152
(Problem is, I don't think this will be shared with the `test/` subdirectory, and thus would violate IWYU unless we make a function.)

@jamiesnape Any comments on this?
</blockquote></details>

Everything currently in master should be working with VTK 5 and 7 or 8.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by kunimatsu-tri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/systems/sensors/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaR_cImi3QUaP5jKkz:-Kldlq0hBoZb1i7neEJk:b-qib42j) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/CMakeLists.txt#L38)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Everything currently in master should be working with VTK 5 and 7 or 8.
</blockquote></details>

Thanks! Good catch.

Also, thanks for the cleaning this up.

For now, I simply removed this line.

Done.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaVeYedEu0KW-7rTEK:-Kld5z2ja5Ga8msIE192:b-fd64io) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a way to make compression optional / selectable?
</blockquote></details>

Good point. Let me put a TODO comment for it.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaUdNFDvvwuP4ICnYc:-KldiFyvSnX4oWLMiSr2:brozg15) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L46)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Siyuan has a PR in flight that may help to address this issue: #6192.
However, it does not presently support multiple input ports, but we could start to consider ways to generalize multiple, possibly optional, ports (which may be easy enough using parameter packs w/ pointers.)
</blockquote></details>

Thanks. I'll consider this once #6038 is landed. Please look at the comment below too.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaV1fbFwUdEolJgaAA:-KldD0fw5CiM9am-tyeu:b-s32it4) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Rather than `sizeof(image.at(0, 0)[0]`, could we do something like `sizeof(ImageTraits<kPixelType>::ChannelType)`, to make the intent more clear?
Or even make a helper, that is something to the effect of `kPixelSize = kNumChannels * kChannelSize`?
</blockquote></details>

Thanks!  I like the latter idea.

Made kPixelSize in Image class and replaced with it.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaWgNDffCPxiICQDWd:-KldDRkO3Iqobfbi0bC5:b-tynx1u) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L109)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Will this always require there to be non-trivial label / depth images? Are there any cases where we would just have RGB-D, or RGB-Label?
Is it possible to make to the input ports optional?
</blockquote></details>

Good point. I think this will be automatically achieved by #6038, so let me leave this as-is.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaWYnW-dkvp9-lr6rG:-KldNZlAblaBNNtsqGF5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.cc#L128)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a way to incorporate these fields into `PackImageToLcmImageT`? (`pixel_format`, `channel_type`, `frame_name`?)
</blockquote></details>

Done.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaX-ddLrfqxIJz6u8a:-KldRe8pyPKwSlBUPE5a:bmr3pez) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/image_to_lcm_image_array_t.h#L13)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Will it ever be useful to have a different color image channel order / type, like RGB, BGR, RGBA?
Would it be possible to place this as a `TODO`?
</blockquote></details>

This is also a good point. Left a TODO comment for it.

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaXOCEzNpE1i94w290:-KldhJOIOyKjCtWgLkj3:bm71xz8) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L5)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit If `robotlocomotion` is to be used as an external, should `#include` use `<>` rather than `""`? (Though Bazel may have an issue....)
</blockquote></details>

It seems the current convention in Drake is `""` rather than `<>` for  including lcmtypes.

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaXhz2E4h3zlujIAzs:-KldWrg6Las8AnW6e1Jc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L35)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Not sure if we gain any benefit, but should we consider using `constexpr double X`, `constexpr char X[]`?
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZajnFMLvJZAUj5dQ:-KldamkxFxkpLlrs_x3S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Other examples I've seen (`run_quadrotor_lqr.cc`) does the parsing directly in `::main`, then calls `do_main()`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera_publish_lcm_example.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZR3ps0PDw3TjDe2I:-KldfYovAboGQB-ZebsN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/rgbd_camera_publish_lcm_example.cc#L48)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there any motivation for using this approach rather than using `gflags` stuff?
https://github.com/gflags/gflags/blob/master/src/gflags_reporting.cc#L40
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZuSChAYEjLWp_kt5:-KldgErkPoeQ9_SkLDE8:b93yf6) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc#L9)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there way to avoid defining these here? If you're getting linker errors, would that be an issue with upstream `lcm`?
</blockquote></details>

Yeah, I know this is annoying and isn't good way.
I'll ask someone how to handle this correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by kunimatsu-tri** [comment]
Thanks for your review, @EricCousineau-TRI.

Addressed your comments. PTAL.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-KldmOd7V_VlaiLwIkL-:b-syneiy)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, modulo either adding a `TODO` or resolving the need to forward the lcm constants.
Thanks!

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-KleK5FBzRfIpWdhB7re:b6ivqqp)*

**Comment by kunimatsu-tri** [comment]
I found a workaround for lcm constans here:
https://stackoverflow.com/questions/8452952/c-linker-error-with-class-static-constexpr

It should be no problem as long as those consts aren't directly referenced.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Klibir-PHLbhtzNMTNT:b-tay33s)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlaZuSChAYEjLWp_kt5:-Klid4ZNSZajjvb8PWnM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52ad7e7bf41745c9012d0782d5d0ca7e99eb41a2/drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc#L9)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Yeah, I know this is annoying and isn't good way.
I'll ask someone how to handle this correctly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc, line 82 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-Klj7uuJLe_EDoitSiKB:-Klj7uuJLe_EDoitSiKC:bco5tlt) ([raw file](https://github.com/robotlocomotion/drake/blob/95b9d9ed6608a0c729316d1c37341dcb91256987/drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc#L82)):*
> ```cpp
>     EXPECT_EQ(image.data.size(), image.size);
>     EXPECT_FALSE(image.bigendian);
>     uint8_t expected_compression_method =
> ```

BTW Cool! Could you possibly refer to the above workaround, maybe using a short permalink?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Klj88ntRd37s1rI9dP1:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc, line 82 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-Klj7uuJLe_EDoitSiKB:-KljTjSCcd9p-pnBfnQn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/95b9d9ed6608a0c729316d1c37341dcb91256987/drake/systems/sensors/test/image_to_lcm_image_array_t_test.cc#L82)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Cool! Could you possibly refer to the above workaround, maybe using a short permalink?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233)*

**Comment by kunimatsu-tri** [comment]
+@sammy-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-KlyMsvZ1WJLCzqOVARq:b3j5bdc)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-KlybrO0vUBljQ-5wH0e:b-up35mr)*

**Comment by sammy-tri** [comment]
First pass complete

---

Reviewed 1 of 7 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 32 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-Klyg0MJ_eLKXtdowN0Q:-Klyg0MLCkwA1ZW0B0Zo:b977v92) ([raw file](https://github.com/robotlocomotion/drake/blob/ef043eb6c17bc1f1b35fdbd3cf7ecaca4149d58d/drake/systems/sensors/image_to_lcm_image_array_t.cc#L32)):*
> ```cpp
>   // http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/zlib-compress2-1.html
>   uint64_t buf_size = source_size * 1.001 + 12;
>   std::unique_ptr<uint8_t> buf(new uint8_t[buf_size]);
> ```

I think this should read `std::unique_ptr<uint8_t[]>`based on https://stackoverflow.com/questions/21377360/proper-way-to-create-unique-ptr-that-holds-an-allocated-array  (you could also use a vector and potentially eliminate a copy if you can do `msg->data.swap(buf)` (not sure that works) but I don't think the array version of `unique_ptr` is necessarily defective).

---

*[drake/systems/sensors/image_to_lcm_image_array_t.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlyenxeLSDa-LRa1Yqo:-KlyenxfG4xJ5dafY1_K:blpugur) ([raw file](https://github.com/robotlocomotion/drake/blob/ef043eb6c17bc1f1b35fdbd3cf7ecaca4149d58d/drake/systems/sensors/image_to_lcm_image_array_t.h#L13)):*
> ```objc
> namespace sensors {
> 
> /// A ImageToLcmMessage takes as input a ImageBgra8U, ImageDepth32F and
> ```

The term `ImageToLcmMessage` doesn't seem to appear anywhere else in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-KlyiBMvPDhzppgWpmx6:ba6b0kz)*

**Comment by kunimatsu-tri** [comment]
Thanks @sammy-tri. Addressed your comments. PTAL.

---

Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 32 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-Klyg0MJ_eLKXtdowN0Q:-KlykSQ0q9ZUAYdKTfhf:birhcbm) ([raw file](https://github.com/robotlocomotion/drake/blob/ef043eb6c17bc1f1b35fdbd3cf7ecaca4149d58d/drake/systems/sensors/image_to_lcm_image_array_t.cc#L32)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think this should read `std::unique_ptr<uint8_t[]>`based on https://stackoverflow.com/questions/21377360/proper-way-to-create-unique-ptr-that-holds-an-allocated-array  (you could also use a vector and potentially eliminate a copy if you can do `msg->data.swap(buf)` (not sure that works) but I don't think the array version of `unique_ptr` is necessarily defective).
</blockquote></details>

Thanks for catching this.
Done.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-KlyenxeLSDa-LRa1Yqo:-Klyj1VkAGDkqxGzFF0E:bjrtlr4) ([raw file](https://github.com/robotlocomotion/drake/blob/ef043eb6c17bc1f1b35fdbd3cf7ecaca4149d58d/drake/systems/sensors/image_to_lcm_image_array_t.h#L13)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The term `ImageToLcmMessage` doesn't seem to appear anywhere else in this file?
</blockquote></details>

Oops, this was the old name.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Klylhk1OMpOxpScOPMT:bousc4m)*

**Comment by sammy-tri** [comment]
:lgtm: (pending CI and open discussions)

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Klyn_aw2OQAI5Htbadj:b-decqgd)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Klz53uGkiIdugVIBj8N:b-nikqms)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6233#-:-Km-4p2rgNAZHEufUbl8:b-j9ui69)*

**Pull request merged**
