### PR TITLE
Don't require license_docs for Drake's own install rules

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6282)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6282#-:-Km6d88psWzPImpP_L13:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review please, per on-call rotation.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6282#-:-Km6oF9CXYJdLSzwtfMu:bnfp4nl)*

**Pull request merged**
