### PR TITLE
[common] Add missing Python kwarg for Polynomial constructor

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Noticed while working on #19062.

+@xuchenhan-tri for both reviews please, if you're available?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19063)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-:-NRZJTdb8_IQzwe-HUFi:bks4n6x)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`common/polynomial.h` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZIRVNBSTEpvytmEi9:-NRZIRVNBSTEpvytmEiA:b-poo0u4) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.h#L152)):*
> ```objc
>   template <typename Derived>
>   explicit Polynomial(const Eigen::MatrixBase<Derived>& coefficients)
>       : Polynomial(WithCoefficients{coefficients.template cast<T>()}) {}
> ```

nit, previously there's nothing preventing users from constructing a polynomial from a *matrix* of coefficients instead of a vector. With this change, the constructor can no longer take a matrix as input. Are we worried about breaking code that has been misusing the constructor by passing in a matrix?

Perhaps there should be a prerequisite on the dimension of `coefficients` to start with?
___
*[`common/polynomial.cc` line 122 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZJHb57kjow7y3g4X8:-NRZJHb57kjow7y3g4X9:b-h0ekm8) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.cc#L122)):*
> ```cpp
> template <typename T>
> Polynomial<T>::Polynomial(const WithCoefficients& coefficients) {
>   const Eigen::Ref<const VectorX<T>>& coeffs = coefficients.coefficients;
> ```

BTW, `coefficients.coefficients` reads a little awkward. How about `coefficients.value`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19063)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`common/polynomial.h` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZIRVNBSTEpvytmEi9:-NRZNIYsDClaKrVt7Xux:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.h#L152)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, previously there's nothing preventing users from constructing a polynomial from a *matrix* of coefficients instead of a vector. With this change, the constructor can no longer take a matrix as input. Are we worried about breaking code that has been misusing the constructor by passing in a matrix?

Perhaps there should be a prerequisite on the dimension of `coefficients` to start with?
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19063)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/polynomial.h` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZIRVNBSTEpvytmEi9:-NRZNnKe39L153ttFUIF:b-tde55g) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.h#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd imagine this throw won't be hit because binding `Eigen::Ref<VectorX<T>>` to a matrix would already fail in the constructor of `WithCoefficients`. Checking now.

**Comment by xuchenhan-tri** [comment]
*[`common/polynomial.h` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZIRVNBSTEpvytmEi9:-NRZOXQk8Pa_vjWOYDX-:br97m3f) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.h#L152)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'd imagine this throw won't be hit because binding `Eigen::Ref<VectorX<T>>` to a matrix would already fail in the constructor of `WithCoefficients`. Checking now.
</blockquote></details>

Yeah, I get an Eigen static assert error instead of the Drake throw.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19063)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/polynomial.h` line 152 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19063#-NRZIRVNBSTEpvytmEi9:-NRZo96U6Uyrud5Ahbml:b-wdj8zi) ([raw file](https://github.com/RobotLocomotion/drake/blob/8e7d2eedb808b5975cfa0f9b4372ef20c67781a9/common/polynomial.h#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

With a fixed-size matrix, you'd get a static assert.  With a dynamic-size matrix, it's a Debug-only runtime abort.  Fixed to be an exception for dynamic-size matrix no matter the build mode.
</blockquote></details>

Nice, thanks!

**Pull request merged**
