### PR TITLE
Added detailed Windows Installation Instructions.

### PR DESCRIPTION
**Pull request by liangfok**
[EWISOTT](http://tvtropes.org/pmwiki/pmwiki.php/Main/ExactlyWhatItSaysOnTheTin)

I tested my changes by generating the Sphinx document using the following commands:

```
$ cd [drake distro]/drake/doc
$ make html
```

Note that there's a missing reference to the unit test page. I've requested that @amcastro-tri add the anchor in https://github.com/RobotLocomotion/drake/pull/2186.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2203) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 +@mikeelkins-tri   -- Since I believe you are also using Windows with Drake

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-:-KGOSThXKEFj3kcp0277:986988188)*

**Comment by sherm1** [comment]
This looks great. It is only one possible Windows workflow though, probably the best one for people building Drake just once. There is also the developer's workflow which would typically involve the Visual Studio IDE and repeated builds from in there. No need to add that here if you are after the build once user; but it might be worth mentioning that this is a no-IDE scenario and that it is also possible to do Drake development within VS.
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/windows.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOYi4zf6QYSPsH72rm:-KGOYi4zf6QYSPsH72rn:1871063637) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L23)):*
Installed->Install

---

*[drake/doc/windows.rst, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOZXTqZA4pvwMZ0rJz:-KGOZXTqZA4pvwMZ0rK-:-724249617) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L26)):*
You talk about the Generator again below under "Configure Build" -- maybe just forward reference here? It seems confusing to throw in CMAKE_FLAGS here when it isn't necessary.

---

*[drake/doc/windows.rst, line 141 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGO_1pZka1NHoxEMUiI:-KGO_1p_JD944aIvYZd9:1575133197) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L141)):*
Those are called "Configurations" in Windows & CMake terminology, rather than "modes".

---

*[drake/doc/windows.rst, line 149 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOa3RgCuwMeZH0aItY:-KGOa3RgCuwMeZH0aItZ:950591145) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L149)):*
This captures a build-once scenario. Is that what you are after here? For developers this would be followed by many builds from within Visual Studio, but using the solution file that is one level down (build/drake). 

---

*[drake/doc/windows.rst, line 158 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGO_OGNXp87GlESE4u6:-KGO_OGOrCXOtb6w-t7R:-1488112705) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L158)):*
[build mode] -> [configuration] 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-:-KGOaZSIuDevtRYL-43T:1576294579)*

**Comment by liangfok** [comment]
@sherm1: Thanks for the quick review. I created https://github.com/RobotLocomotion/drake/issues/2204 to track the addition of Visual Studio instructions.

---

Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/doc/windows.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOYi4zf6QYSPsH72rm:-KGPfWR655NbTts0VGBT:-795674665) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L23)):*
Fixed. Thanks!

---

*[drake/doc/windows.rst, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOZXTqZA4pvwMZ0rJz:-KGPfbVlSIINs8z_D87m:243435070) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L26)):*
Moved it down as suggested.

---

*[drake/doc/windows.rst, line 141 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGO_1pZka1NHoxEMUiI:-KGPgLTEyURzIfl9zTim:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L141)):*
Fixed. Thanks.

---

*[drake/doc/windows.rst, line 149 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGOa3RgCuwMeZH0aItY:-KGPgNngzORxdN4mEWl9:1588233036) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L149)):*
Actually, I've been executing this command over and over again in between making small changes to the code. Thus, I believe these instructions can be used for development using a text editor. I was probably superfluously re-executing it at the super-build level instead of the drake/ sublevel. I've updated the instructions to indicate that future builds can be done from within the drake/ sub-directory.

---

*[drake/doc/windows.rst, line 158 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-KGO_OGNXp87GlESE4u6:-KGPhTLtP9h3emSwRV50:-1055488007) ([raw file](https://github.com/robotlocomotion/drake/blob/8518d9039c24e110ecde8b2c2b7c777f3e476aef/drake/doc/windows.rst#L158)):*
Fixed. To be more clear, I decided to call it "build configuration". I didn't want the reader to think it was some "drake configuration".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-:-KGPAtPaiMt0CR9aSBwh:-1418076222)*

**Comment by liangfok** [comment]
@sherm1 and @david-german-tri: I re-based this PR with the latest from master and the extraneous files went away. Thus, I believe this PR is ready for another look. Thanks!!

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-:-KGSYYKAW0oFpMXoaCsi:-782000430)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2203#-:-KGU51P88k__bCDZfjO5:1417088721)*

**Comment by david-german-tri** [comment]
Builder failures (on windows, amusingly enough) are unrelated.  Merging.

**Comment by liangfok** [comment]
How frequently is Drake's wiki refreshed? The following page is now out of date:

http://drake002.csail.mit.edu/drake/sphinx/windows.html

**Comment by david-german-tri** [comment]
Hmm.  There's a transition in process from drake002 to github.io (see discussion on #2143), but I didn't know updates on drake002 had been turned off.  @RussTedrake, is this expected?

**Pull request merged**
