### PR TITLE
Remove MATLAB Atlas example and test that use it

### LINKED ISSUE #4513: runAtlasDynamics fails after updating Eigen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The first commit removes many `drake/matllab/...` unit tests that were coded to required either the Atlas model, or Atlas software in particular.

The second commit removes the Atlas example itself.

Relates #6369.

Resolves #4513.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6367)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
approved.  glad to see that the urdfs stayed (correct?).   please add another issue assigned to me like we did for the quadrotor examples about atlas.

---

Review status: 0 of 227 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-:-Kn-gEEq9_QdhMK6GmEi:buxjdp2)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 227 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-:-Kn-gRrjMSUTeMcFFPdI:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.
-(status: do not merge) 

> glad to see that the urdfs stayed (correct?). 

Yes.

> please add another issue assigned to me like we did for the quadrotor examples about atlas.

#6381

---

Review status: 0 of 227 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-:-Kn-hIFV3RLVYm9Jx81X:bbbh23y)*

**Comment by ggould-tri** [comment]
First time I can recall a PR so big the file matrix doesn't display by default.
:lgtm: with one consider below, which might apply to all similar PRs as well.

---

Reviewed 10 of 227 files at r1.
Review status: 10 of 227 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Atlas/README.md, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-Kn-uCA6Z1drLTa_BzT4:-Kn-uCA6Z1drLTa_BzT5:b-qlgx16) ([raw file](https://github.com/robotlocomotion/drake/blob/008cdba4f269edcccb2657baee3b122f395d661d/drake/examples/Atlas/README.md#L3)):*
> ```Markdown
> 
> This directory contains models for Atlas.
> ```

BTW -- Consider referring to your new issue 6381 here; most people reading this note will want to refer to that to understand the status.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-:-Kn-v7Hm2oevPsuoQ4V2:b-c2leff)*

**Comment by ggould-tri** [comment]
Reviewed 217 of 227 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367)*

**Comment by jwnimmer-tri** [comment]
Review status: 226 of 227 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Atlas/README.md, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6367#-Kn-uCA6Z1drLTa_BzT4:-Kn00-NzTqxhFoTWqedI:bkshitp) ([raw file](https://github.com/robotlocomotion/drake/blob/008cdba4f269edcccb2657baee3b122f395d661d/drake/examples/Atlas/README.md#L3)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Consider referring to your new issue 6381 here; most people reading this note will want to refer to that to understand the status.
</blockquote></details>

OK Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6367)*

**Comment by jwnimmer-tri** [comment]
The most recent push was a README-only change; the build had previously passed.
The two build failures are:
- linux-gcc-experimental-matlab: CDash reported "bad gateway"
- linux-xenial-gcc-ninja-experimental-open-source-debug: unstable due to git failures

Using override-merge since those are both known flakes.

**Pull request merged**
