### PR TITLE
Simplecar autodiffxd

### PR DESCRIPTION
**Pull request by RussTedrake**
implements DoToAutoDiffXd for simplecar transform.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5859)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@liangfok for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-KhwEB0QvR_hcmaOiPDb:b-ui3opy)*

**Comment by liangfok** [comment]
First feature review round completed.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmClOi6Xj60wet78O:-KhwmClOi6Xj60wet78P:b-5srpx2) (no related file):*
Should a unit test be added to `drake/automotive/test/simple_car_to_euler_floating_joint_test.cc` verifying that `SimpleCarToEulerFloatingJoint::DoToAutoDiffXd()` works?

---

*[drake/systems/framework/system.h, line 1336 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmXVVwx-WvvE_L5M3:-KhwmXVVwx-WvvE_L5M4:bgei7wx) ([raw file](https://github.com/robotlocomotion/drake/blob/ae55a11b12660c264b5b9d89ea472d16e4471a48/drake/systems/framework/system.h#L1336)):*
> ```objc
>   virtual System<AutoDiffXd>* DoToAutoDiffXd() const {
>     std::stringstream ss;
>     ss << "Override DoToAutoDiffXd for object named [" << this->get_name() << "] of type " << typeid(*this).name() << " before using ToAutoDiffXd.";
> ```

This line is greater than 80 characters in width, which violates the style guide.

https://google.github.io/styleguide/cppguide.html#Line_Length

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-Khwm9lBOZjuDXRGj-AX:bfc411a)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmClOi6Xj60wet78O:-KhwyTLP4CE_ATduZRe1:b2ysxxo) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should a unit test be added to `drake/automotive/test/simple_car_to_euler_floating_joint_test.cc` verifying that `SimpleCarToEulerFloatingJoint::DoToAutoDiffXd()` works?
</blockquote></details>

I skipped it because the implementation was trivial and the class has no member variables.  Of course it would be better to have it.  Would you be willing to contribute it?

---

*[drake/systems/framework/system.h, line 1336 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmXVVwx-WvvE_L5M3:-KhwyIALYI9yLC2_KiGA:b-fz0nkc) ([raw file](https://github.com/robotlocomotion/drake/blob/ae55a11b12660c264b5b9d89ea472d16e4471a48/drake/systems/framework/system.h#L1336)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This line is greater than 80 characters in width, which violates the style guide.

https://google.github.io/styleguide/cppguide.html#Line_Length
</blockquote></details>

done.  (had forgotten to push after running clang-format)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmClOi6Xj60wet78O:-Khx-fO0IlmX65_K3W4j:b-rxwtbv) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I skipped it because the implementation was trivial and the class has no member variables.  Of course it would be better to have it.  Would you be willing to contribute it?
</blockquote></details>

Yes, of course. I will do so in a followup PR. Marking myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-Khx-lWuazUq23Lm4ME1:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@sherm1 for platform

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-Khx211NgcbS3Yubl1fd:b-ch1qom)*

**Comment by sherm1** [comment]
Platform :lgtm:. A couple of BTWs, ptal.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car_to_euler_floating_joint.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhxZR8RaetQHlahmQH2:-KhxZR8RaetQHlahmQH3:b-ofpiv7) ([raw file](https://github.com/robotlocomotion/drake/blob/626d855a5d767ff575a7dd5d9a53546fc2de65a4/drake/automotive/simple_car_to_euler_floating_joint.h#L57)):*
> ```objc
>   }
> 
>  protected:
> ```

BTW I suggest "private" here so this implementation detail doesn't show up in doxygen. (Also for DoCalcOutput().)

---

*[drake/systems/framework/system.h, line 1323 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhxYcplT_7SAmmFrX8O:-KhxYcplT_7SAmmFrX8P:b7kjdia) ([raw file](https://github.com/robotlocomotion/drake/blob/626d855a5d767ff575a7dd5d9a53546fc2de65a4/drake/systems/framework/system.h#L1323)):*
> ```objc
>     std::stringstream ss;
>     ss << "Override DoToAutoDiffXd for object named [" << this->get_name()
>        << "] of type " << typeid(*this).name() << " before using ToAutoDiffXd.";
> ```

BTW, use [`NiceTypeName::Get(*this)`](http://drake.mit.edu/doxygen_cxx/classdrake_1_1_nice_type_name.html) instead of typeid to get something human-readable here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-Khx_AOgmv6ZaDSHftX6:bnh55n3)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhwmClOi6Xj60wet78O:-KhzFupMqtvxHEoxYS8X:bkxf0m8) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, of course. I will do so in a followup PR. Marking myself satisfied.
</blockquote></details>

Thank you Liang!

---

*[drake/automotive/simple_car_to_euler_floating_joint.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhxZR8RaetQHlahmQH2:-KhzGBFrQ9scvpZeDc0e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/626d855a5d767ff575a7dd5d9a53546fc2de65a4/drake/automotive/simple_car_to_euler_floating_joint.h#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I suggest "private" here so this implementation detail doesn't show up in doxygen. (Also for DoCalcOutput().)
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 1323 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-KhxYcplT_7SAmmFrX8O:-KhzGdrUgu1GAfWWte-j:b-sdzfnf) ([raw file](https://github.com/robotlocomotion/drake/blob/626d855a5d767ff575a7dd5d9a53546fc2de65a4/drake/systems/framework/system.h#L1323)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, use [`NiceTypeName::Get(*this)`](http://drake.mit.edu/doxygen_cxx/classdrake_1_1_nice_type_name.html) instead of typeid to get something human-readable here.
</blockquote></details>

way better.  thanks Sherm!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859)*

**Comment by sherm1** [comment]
Changes need a push, Russ?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5859#-:-KhzNkZPVMMaxoVGVY1V:b39ryp3)*

**Comment by jwnimmer-tri** [comment]
@sherm1 With your platform review hat on, please do not let authors submit `clang-format` fixups to otherwise-unchanged areas of files, especially when the reformatting makes the code more difficult to read.

**Comment by sherm1** [comment]
OK, thanks @jwnimmer-tri -- I don't like that either but was under the misimpression that you were encouraging it!

**Comment by jwnimmer-tri** [comment]
Nope, sorry for the confusion!  See #4843.

Even if we were encouraging reformatting, it should be in a separate commit.

**Pull request merged**
