### PR TITLE
[multibody] Add joint for each free body

### PR DESCRIPTION
**Pull request by joemasterjohn**
Towards #14949 and part of #18258.

- Creates a `QuaternionFloatingJoint` at finalize time for every free body in the tree.
    This creates a small breaking change: MbP::num_joints() will change in all existing
    plants that had previously declared at least one free body. 
- Explicitly declares `is_floating` to mean: is mobilized by a 6-dof mobilzer AND parent body of the mobilizer is world
  (this was only implicitly true before)
- Fixes all of the tests to deal with the breaking change.

This PR depends on the small behavior change from #18389 and will be rebased off of that branch. The changes to `body.h`, `joint.h` and `mobilizer.h` (all in the first commit) can be ignored. All of the relevant changes are in the second commit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIERhSM1y5VO85vvZXW:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: pending a few minor comments

> Reviewed 15 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIEpYj97k5BhV56ory3:b-hwrg50)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[`multibody/plant/multibody_plant.cc` line 1068 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIE_-Ag1kARm6Ozp6Ih:-NIE_-Ag1kARm6Ozp6Ii:b-wvxqku) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/multibody_plant.cc#L1068)):*
> ```cpp
>   DRAKE_DEMAND(geometry_source_is_registered());
>   // Disallow collisions between adjacent bodies. Adjacency is implied by the
>   // existence of a joint between bodies.
> ```

minor: comment needs an update to note the exceptions for the new joint type (and also for parent==world with any joint)
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIE_mglChD0lIaRSzNC:-NIE_mglChD0lIaRSzND:bnaeafg) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/kuka_iiwa_model_tests.h#L89)):*
> ```objc
>   // spatial velocity.
>   void SetState(const VectorX<double>& x_joints) {
>     EXPECT_EQ(plant_->num_joints(), kNumJoints + 1);  // + 1 for floating joint
> ```

BTW this seems odd -- why not update kNumJoints to be the number of joints? A comment could note that the last joint is the free body's joint so the loop below can go to kNumJoints-1.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEaOzi7FQOQjaO8FPy:-NIEaOzi7FQOQjaO8FPz:btud227) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L178)):*
> ```cpp
>     // This model only has weld, revolute, and floating joints. Set the revolute
>     // joints to an arbitrary angle.
>     if (joint.num_velocities() == 1) {
> ```

FYI could use joint.type_name()=="revolute" here as you did in other tests. That seems clearer to me.
___
*[`multibody/plant/test/multibody_plant_jacobians_test.cc` line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEa9I8DDmjdX3HgvAp:-NIEa9I8DDmjdX3HgvAq:b7mnex9) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/multibody_plant_jacobians_test.cc#L80)):*
> ```cpp
>   // Sanity check basic invariants.
>   // Seven dofs for the arm plus floating base.
>   EXPECT_EQ(plant_->num_joints(), kNumJoints + 1);  // + 1 for floating joint.
> ```

BTW odd -- I would expect kNumJoints == num_joints(). Maybe change that instead?
___
*[`multibody/tree/multibody_tree.cc` line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEk1IsE4VaQ4J59urN:-NIEk1IsE4VaQ4J59urO:b-r3llso) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L620)):*
> ```cpp
> void MultibodyTree<T>::CreateJointImplementations() {
>   DRAKE_DEMAND(!topology_is_valid());
>   // Create Joint objects's implementation. Joints are implemented using a
> ```

nit: objects's -> objects'
___
*[`multibody/tree/multibody_tree.cc` line 632 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEkLlB7IUSFhuUEOIw:-NIEkLlB7IUSFhuUEOIx:b37wt2c) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L632)):*
> ```cpp
>   // changes are NOT allowed after Finalize(), joint implementations MUST be
>   // assembled BEFORE the tree's topology is finalized.
>   int num_joints_pre_floating_joints = num_joints();
> ```

nit: should be `const int`
___
*[`multibody/tree/multibody_tree.cc` line 638 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEk__r3zgchIiqmMxB:-NIEk__s7rIeQkUkgVNl:b-k2xpka) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L638)):*
> ```cpp
>     std::vector<Mobilizer<T>*> mobilizers =
>         internal::JointImplementationBuilder<T>::Build(joint.get(), this);
>     // Below we assume a single mobilizer per joint, the sane thing to do.
> ```

BTW :-)
___
*[`multibody/tree/multibody_tree.cc` line 640 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIElBLaA5M-NRIJr_yv:-NIElBLaA5M-NRIJr_yw:b5hcwt) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L640)):*
> ```cpp
>     // Below we assume a single mobilizer per joint, the sane thing to do.
>     // TODO(amcastro-tri): clean up the JointImplementationBuilder so that this
>     // assumption (one mobilizer per joint) is set in stone once and for all.
> ```

FYI I think the motivation for this was to allow Joints to be built up from a combination of mobilizers. For example, if we have a revolute and prismatic mobilizer we could implement a planar joint using two prismatics and a revolute with two intermediate massless bodies (aka frames). In practice I can't think of why we wouldn't just write the appropriate mobilizer and use it directly.

There is however a real case where a Joint doesn't map to _any_ mobilizer. That's when the Joint has to be implemented as a constraint rather than a mobilizer. This comes up in systems with closed topologies. Normally we would handle those by cutting bodies and using weld constraints, but on occasion it is much more efficient to cut at a joint (very nice with ball joints, e.g.). You don't see this now because we don't yet have the constraint infrastructure in place, but it is arriving very soon.
___
*[`multibody/tree/multibody_tree.cc` line 648 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEom5ZEYQsn9PIlZEd:-NIEom5ZEYQsn9PIlZEe:blgjad) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L648)):*
> ```cpp
>     }
>   }
>   // It is VERY important to add quaternions if needed only AFTER joints had a
> ```

nit: quaternions -> joints to free bodies
(Or something like that -- it's not about the quaternions)
___
*[`multibody/tree/multibody_tree.cc` line 649 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEogajAGi2B5UnjO2f:-NIEogajAGi2B5UnjO2g:b-z1x7ls) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L649)):*
> ```cpp
>   }
>   // It is VERY important to add quaternions if needed only AFTER joints had a
>   // chance to get implemented with mobilizers. This is because joints's
> ```

nit: joints's -> joints'
___
*[`multibody/tree/multibody_tree.cc` line 670 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEpDKE7wN_wqu5Wd_X:-NIEpDKE7wN_wqu5Wd_Y:b-iica64) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L670)):*
> ```cpp
>     // Below we assume a single mobilizer per joint, the sane thing to do.
>     // TODO(amcastro-tri): clean up the JointImplementationBuilder so that this
>     // assumption (one mobilizer per joint) is set in stone once and for all.
> ```

BTW see above comments

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390)* status: needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[`multibody/plant/multibody_plant.cc` line 1068 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIE_-Ag1kARm6Ozp6Ih:-NIErw9e18o5JqL8SZ2p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/multibody_plant.cc#L1068)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: comment needs an update to note the exceptions for the new joint type (and also for parent==world with any joint)
</blockquote></details>

Done.
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIE_mglChD0lIaRSzNC:-NIEsYWy8DD3uxRKqUOF:bsrhp8h) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/kuka_iiwa_model_tests.h#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems odd -- why not update kNumJoints to be the number of joints? A comment could note that the last joint is the free body's joint so the loop below can go to kNumJoints-1.
</blockquote></details>

Done, good point. I think I was writing them that way as a sanity check when prototyping.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEaOzi7FQOQjaO8FPy:-NIEuCgUAU6JPpQDJmCz:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L178)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI could use joint.type_name()=="revolute" here as you did in other tests. That seems clearer to me.
</blockquote></details>

Done, thanks.
___
*[`multibody/plant/test/multibody_plant_jacobians_test.cc` line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEa9I8DDmjdX3HgvAp:-NIEv9PjBLqJZhzeaiDY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/plant/test/multibody_plant_jacobians_test.cc#L80)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW odd -- I would expect kNumJoints == num_joints(). Maybe change that instead?
</blockquote></details>

Done.
___
*[`multibody/tree/multibody_tree.cc` line 640 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIElBLaA5M-NRIJr_yv:-NIEwvBV69JuDYI5hZzO:bgkkwvf) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L640)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI I think the motivation for this was to allow Joints to be built up from a combination of mobilizers. For example, if we have a revolute and prismatic mobilizer we could implement a planar joint using two prismatics and a revolute with two intermediate massless bodies (aka frames). In practice I can't think of why we wouldn't just write the appropriate mobilizer and use it directly.

There is however a real case where a Joint doesn't map to _any_ mobilizer. That's when the Joint has to be implemented as a constraint rather than a mobilizer. This comes up in systems with closed topologies. Normally we would handle those by cutting bodies and using weld constraints, but on occasion it is much more efficient to cut at a joint (very nice with ball joints, e.g.). You don't see this now because we don't yet have the constraint infrastructure in place, but it is arriving very soon.
</blockquote></details>

Thanks for that explanation. I've updated the outdated comment to reflect near future changes.
___
*[`multibody/tree/multibody_tree.cc` line 648 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIEom5ZEYQsn9PIlZEd:-NIEw00H2TtyuG_J8ZM3:b-90f84c) ([raw file](https://github.com/robotlocomotion/drake/blob/4df06b05afa5500a7be3b9c54ce4217cc0fb0f7b/multibody/tree/multibody_tree.cc#L648)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: quaternions -> joints to free bodies
(Or something like that -- it's not about the quaternions)
</blockquote></details>

Done, thanks. Re-worded to explain why the ordering matters for detecting floating bodies.

**Review by joemasterjohn — COMMENTED** [review]
+@sammy-tri for platform review on Monday, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIEyYxN9Sr8QkF9XcZ_:bu326de)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
I'm trying to think through how much of a breaking change this really is and what (if anything) to do about it.   One example, the size of the plant's reaction forces output port (`get_reaction_forces_output_port`) will change, and this isn't captured by any tests (nor is the resulting new value).   There are probably other places?  I think at the least there likely needs to be a stronger-than-usual warning in the release notes.

> Reviewed 3 of 15 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIYL1p11W1vMKXS8UH4:b-l7i3wb)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn and @sherm1)

___
*[`multibody/tree/multibody_tree.cc` line 660 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIY6BbV3MM5rKHngHc0:-NIY6BbW2dwbWxicDSsp:b-pz6w0t) ([raw file](https://github.com/robotlocomotion/drake/blob/25c66120606a65328f752722a19b307b81a7938e/multibody/tree/multibody_tree.cc#L660)):*
> ```cpp
>     const BodyTopology& body_topology = get_topology().get_body(body.index());
>     if (!body_topology.inboard_mobilizer.is_valid()) {
>       this->AddJoint<QuaternionFloatingJoint>("world_" + body.name(),
> ```

Is this joint naming convention for automatically generated joints now part of the stable drake API?  If so, should it be documented?  If not...   ok, I'm not sure what if not, maybe a comment here?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

___
*[`multibody/tree/multibody_tree.cc` line 660 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIY6BbV3MM5rKHngHc0:-NIYrVjw-D9zb-cseGdd:b-tvaq6q) ([raw file](https://github.com/robotlocomotion/drake/blob/25c66120606a65328f752722a19b307b81a7938e/multibody/tree/multibody_tree.cc#L660)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Ah you bring up a good point. If it did become part of the API it would put a restriction on the user to never have a non-automatically generated joint named "world_<bodyname>" when there is a freebody named <bodyname> (not sure WHY anyone would, but they could).

side-thought: This also might be part of the breaking change. If any users' sims today have a joint with conflicting name, this line will fail. 

I guess the most robust solution would be to use the name if it doesn't collide with user named joints and have a scheme to generate a unique identifier if so, but that seems cumbersome. Otherwise maybe I could at least make auto generated joint names less likely to collide (e.g "drake_autogenerated_joint::world_bodyname" and then document that in MbP's docs? What do you think?
</blockquote></details>

If that's too bulky you could just stuff in an unlikely character like `$world_bodyname` for made-up joints and mention that in the docs somewhere and note the potential (but very unlikely) breaking change.

**Review by sammy-tri — COMMENTED** [review]
I re-read the design discussion in Slack (referenced from #14949) and it did clear some of my concerns.  Enough people have signed off on the breaking change (at least in principle) there.

I tried running (most) Anzu (TRI-internal) tests against a version of drake with this change.  The failures fell into a few categories:

1. Model parse tests -- easy to fix, just change the expected value like the allegro test here.
2. Python which introspects joints  -- can't fix, all models with free bodies now have a joint type that doesn't exist in python.  Can probably kludge by ignoring joints where (child_body().is_floating() == True).
3. Assumptions that joints and floating bodies are disjoint parts of the state vector -- fixable, tedious depending on API
4. Assuming that`num_joints()` doesn't change after `Finalize` -- I only found one, but this scares me.
5. MultibodyPlantSubgraph -- fixable and it was making a lot of assumptions about internals anyway

Assuming that none of those were surprises (based on the design discussion) or are things we can live with, I don't think keeping up with this change will be too painful for users with good test coverage.

> Reviewed 2 of 15 files at r1, 4 of 4 files at r2, 3 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIZ1qh8ECW_862_PvPS:b4rh1kv)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn and @sherm1)

___
*[`multibody/tree/multibody_tree.cc` line 660 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18390#-NIY6BbV3MM5rKHngHc0:-NIZBu7C37cf4F2gORxv:blci6up) ([raw file](https://github.com/robotlocomotion/drake/blob/25c66120606a65328f752722a19b307b81a7938e/multibody/tree/multibody_tree.cc#L660)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

If that's too bulky you could just stuff in an unlikely character like `$world_bodyname` for made-up joints and mention that in the docs somewhere and note the potential (but very unlikely) breaking change.
</blockquote></details>

I think  @sherm1 's suggestion seems fine (use an unlikely prefix and document it).  `::` in model names can have some specific connotations so I might avoid that.

**Review by sammy-tri — COMMENTED** [review]
A follow-up PR works for me for the bindings.  I agree there's nothing to be done about changing the `num_joints()`/`Finalize()` situation.

:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIby0rOATL2_N2tDyi2:b-b0f87c)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by EricCousineau-TRI — COMMENTED** [review]
Joe - any chance you could change "at finalize time" to be more explicit "after `Finalize() is called"?
Will help draw attention to the concrete places where breaking change will occur.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIc3AOp5vw5svwNwps_:bfh1afi)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by EricCousineau-TRI — COMMENTED** [review]
(in the PR overview, which I assume will be in the commit msg)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18390#-:-NIc3lB06htDXvB8l4HZ:b-v3mr04)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Comment by jwnimmer-tri** [comment]
Nobody involved with this PR should have approved a breaking change for merging into Drake without a concurrent Anzu PR waiting in the wings to deal with the breakage. There's no reason for an own-goal here. Please adjust your thought process and judgement to avoid making such a hugely disruptive mistake in the future.

**Pull request merged**
