### PR TITLE
Adds Configuration File Support for Specifying MaliputRailcars and IDM-controlled MaliputRailcars.

### PR DESCRIPTION
**Pull request by liangfok**
This PR only defines the configuration file and its parser. It does not integrate them with AutomotiveDemo. The integration will be done in a followup PR.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5250)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please. Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5250#-:-KhnVmjKSbW5TIKSe-ci:be2y8p3)*

**Comment by jwnimmer-tri** [comment]
How about doing a design review for such a major initiative, before a PR?

**Comment by liangfok** [comment]
Sure. I'll create on ASAP.

**Comment by liangfok** [comment]
I'm going to close this until a relevant design document has been accepted.

**Pull request closed without merging**
