### PR TITLE
Making Numeric Specialization For AutoDiffScalar Succinct

### PR DESCRIPTION
**Pull request by m-chaturvedi**
@EricCousineau-TRI suggested the change.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6057)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
Ref: https://github.com/RobotLocomotion/drake/pull/5930

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by EricCousineau-TRI** [comment]
Would it be possible to add a simple test for this? Something simple, such as ensuring that `numeric_limits<AutoDiffScalar<T>>` matches `numeric_limits<T>`, or even just:
`EXPECT_TRUE(std::is_base<numeric_limits<T>, numeric_limits<AutoDiffScalar<T>>::value)`?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6057#-:-Kji2PiCJzbdXZ_pe8qZ:b-75th7)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by EricCousineau-TRI** [comment]
*[drake/common/test/eigen_autodiff_types_test.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6057#-KkIJdcRvV6dE2t2mpGG:-KkIJdcSMbrK9Uf-0q0B:bttvdk2) ([raw file](https://github.com/robotlocomotion/drake/blob/2f0ba686311d583dceb9134b0af4bd449f637164/drake/common/test/eigen_autodiff_types_test.cc#L7)):*
> ```cpp
> namespace {
> GTEST_TEST(EigenAutodiffTypesTest, CheckingInheritance) {
> typedef double Scalar;
> ```

nit Could you run this through `clang-format -i` right quick?

(If it's helpful, I use this bash function:
```bash
$ declare -f drake-clang-format 
drake-clang-format () 
{ 
    ( set -e -x -u;
    upstream=${1-upstream/master};
    cd $DRAKE;
    files="$(git diff --name-only $(git merge-base $upstream HEAD) HEAD -- '*.cc' '*.h')";
    echo $files | xargs clang-format -i )
}
```
and then select the hunks I want via `git gui`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6057)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6057#-:-KkMcSGjLIhVLHt2UPJh:bpqxd5f)*

**Comment by m-chaturvedi** [comment]
*[drake/common/test/eigen_autodiff_types_test.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6057#-KkIJdcRvV6dE2t2mpGG:-KkMdBWA2OOYdvs3vRxI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f0ba686311d583dceb9134b0af4bd449f637164/drake/common/test/eigen_autodiff_types_test.cc#L7)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Could you run this through `clang-format -i` right quick?

(If it's helpful, I use this bash function:
```bash
$ declare -f drake-clang-format 
drake-clang-format () 
{ 
    ( set -e -x -u;
    upstream=${1-upstream/master};
    cd $DRAKE;
    files="$(git diff --name-only $(git merge-base $upstream HEAD) HEAD -- '*.cc' '*.h')";
    echo $files | xargs clang-format -i )
}
```
and then select the hunks I want via `git gui`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6057)*

**Comment by ggould-tri** [comment]
Huh, that's clever.  :lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6057#-:-KkMeq0gT7S-lm4EwrZv:bqos2i8)*

**Pull request merged**
