### PR TITLE
Move resolve_center_of_pressure into its own file

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6464, per cleaning up `util.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7367)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/util/drakeUtil.h, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7367#-Kxhl42T1bcuLPV-oTzs:-Kxhl42T1bcuLPV-oTzt:bmh3ibh) ([raw file](https://github.com/robotlocomotion/drake/blob/91f661e7f91e6a28d3bb3b6a441c34456a144b67/drake/util/drakeUtil.h#L200)):*
> ```objc
> void baseZeroToBaseOne(std::vector<int>& vec);
> 
> double angleAverage(double theta1, double theta2);
> ```

I think you can now also safely remove this file (and the cpp) since the two methods above are not even used anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7367#-:-KxhlGKH6-0lJh5bVeqv:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/util/drakeUtil.h, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7367#-Kxhl42T1bcuLPV-oTzs:-Kxhm6h48JeHDk-bgHH7:b-142o0h) ([raw file](https://github.com/robotlocomotion/drake/blob/91f661e7f91e6a28d3bb3b6a441c34456a144b67/drake/util/drakeUtil.h#L200)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think you can now also safely remove this file (and the cpp) since the two methods above are not even used anywhere.
</blockquote></details>

OK #7364 removes those two methods.

Also note the ~180 LOC above the fold above those two methods, that is not dead yet.  (The `std::vector` to `Eigen::Matrix` to `cVector` conversion routines are quite popular.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7367)*

**Comment by amcastro-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/drakeUtil.h, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7367#-Kxhl42T1bcuLPV-oTzs:-KxhxWTXn7_Z2RDiPI2f:b-ct5z8w) ([raw file](https://github.com/robotlocomotion/drake/blob/91f661e7f91e6a28d3bb3b6a441c34456a144b67/drake/util/drakeUtil.h#L200)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK #7364 removes those two methods.

Also note the ~180 LOC above the fold above those two methods, that is not dead yet.  (The `std::vector` to `Eigen::Matrix` to `cVector` conversion routines are quite popular.)
</blockquote></details>

Ah, good point, I was only judging by the cpp contents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7367)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7367)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per rotation, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7367#-:-Kxi0fq_T2b4TSOtgXkG:bnfp4nl)*

**Pull request merged**
