### PR TITLE
Add BsplineBasis and BsplineTrajectory classes

### PR DESCRIPTION
**Pull request by avalenzu**
This is a first step in upstream-ing some kinematic planning code. The classes in this PR are general, however; they do not have any connection to kinematics.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11990)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[math/test/bspline_trajectory_test.cc, line 34 at r5](https://reviewable.io/reviews/robotlocomotion/drake/11990#-M3mb0O05D8gfLBScG8H:-M3nBU5hBOMmqkHF0fUF:bs9rql9) ([raw file](https://github.com/robotlocomotion/drake/blob/6f9467f211ccd9eabde48202258d47a0af1646da/math/test/bspline_trajectory_test.cc#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This all fits on one line.

Generally, you have code here that changes after a clang format.
</blockquote></details>

FYI --

A valid defect would go like "nit This would be more readable as a single line" or "nit Consider reflow onto a single line to fit more on the screen at once".

The fact that "clang-format would format this line (/ file) differently" is not a defect, and I'm going to actively discourage reviewers from remarking on it.  If the formatting in incorrect or needs improvement then say so, but the _reason_ should not because of that tool.  Mentioning the tool can mislead authors into thinking that it holds more authority than it really does.

**Comment by jwnimmer-tri** [comment]
___
*[math/test/bspline_trajectory_test.cc, line 34 at r5](https://reviewable.io/reviews/robotlocomotion/drake/11990#-M3mb0O05D8gfLBScG8H:-M3q40A67PAS33JVourd:b-69xkkh) ([raw file](https://github.com/robotlocomotion/drake/blob/6f9467f211ccd9eabde48202258d47a0af1646da/math/test/bspline_trajectory_test.cc#L34)):*
> ... where some subsequent developer chooses to hit their modification with clang format and it trashes formatting of code otherwise unrelated to their changes ...

If someone uses clang-format instead of clang-format-diff, then we make them go through their changes and revert it.  We should not support them in their abuse of the code.

If we want to enable them to run clang-format, then we need to make it a requirement that clang-format is idempotent on all files, and then have the linter enforce it.  Failing that, we reviewers should be silent.  Even a BTW suggests that it's relevant.  It's not -- either the code is readable and we leave it alone with no comment, or its defective and we make the developer respond to a review defect.  Rambling on without a defect wastes time on unimportant matters.  BTW are for teaching, not for mentioning things so trivial to not be worth fixing in the first place.

**Comment by jwnimmer-tri** [comment]
___
*[math/bspline_trajectory.cc, line 161 at r7](https://reviewable.io/reviews/robotlocomotion/drake/11990#-M3twfey4hOWKj1LHZE-:-M3uxhzQCQHMiCUAbiLj:b-7ew7qj) ([raw file](https://github.com/robotlocomotion/drake/blob/07ef87b64b5d3020d2dc7bdff4948a8c3c600e48/math/bspline_trajectory.cc#L161)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Woohoo! If constexpr for the win!!!
</blockquote></details>

But... which is the correct semantics?  Value equality or structural equality?

Counter-proposal: this method should return `boolean<T>`, and not branch on scalar type.  So approximately:

```c++
return
    (this->basis() == other.basis()) &&
    all(this->control_points() == other.control_points());
```

Using `drake::all` from https://github.com/RobotLocomotion/drake/blob/18439baa6451585b8e66f54ff82eb9e00c6db935/common/drake_bool.h#L36.

**Comment by avalenzu** [comment]
-(priority: low) +(priority: high) Now that #12986 has merged, this PR needs to be fixed and merged quickly to allow TRI internal repos to use the most recent Drake.

**Comment by avalenzu** [comment]
___
*[math/bspline_trajectory.cc, line 161 at r7](https://reviewable.io/reviews/robotlocomotion/drake/11990#-M3twfey4hOWKj1LHZE-:-M40bnit0uwq5nBUTYgP:bcwio0h) ([raw file](https://github.com/robotlocomotion/drake/blob/07ef87b64b5d3020d2dc7bdff4948a8c3c600e48/math/bspline_trajectory.cc#L161)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Need to bail early if basis doesn't match.

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please.

**Pull request merged**
