### PR TITLE
[render] Deprecate RgbdSensor's CameraProperties API

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Deprecate the `RgbdSensor` API that depends on `CameraProperties` (only constructors) and related infrastructure.

- `RgbdSensor`
  - deprecate `CameraPoses`
  - deprecate the constructors on `CameraProps` and `CameraPoses` (print console warning if exercised).
  - Add single-camera constructor (infer color from depth).
  - bindings
    - deprecate `CameraPoses` binding
    - deprecated `RgbdSensor` constructors that use `CameraPoses`.
    - Add bindings for `RenderCamera` constructors.
- Conversion constructors on `RenderCamera`s now take additional sensor pose.
- Add `DeprecatedParamInit` to facilitate deprecation of constructors that have otherwise been declared with `ParamInit`.

Towards resolving checklist in #11880.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri more fun and games.

Currently running Anzu against this: `.../Anzu-master-Drake-PR/89/`

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMSI0o50eJST3trCvmW:b5dw86n)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with some minor comments

+@sammy-tri for platform review (or feel free to punt!)

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMSMKsvDA1fvNDZg2-a:bkrvix3)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/deprecation_pybind.h, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSJYg052z3ebp20hsq:-MMSJYg052z3ebp20hsr:b-2fehkh) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce7e7a3f40be31fdd717775fa75498bbd3ed75a/bindings/pydrake/common/deprecation_pybind.h#L101)):*
> ```objc
> }
> 
> /// Returns a deprecated constructor for creating an instance of Class and
> ```

nit The volume of this text made it hard for me to know if this added more bells and whistles, or if it's really just a deprecated version of `ParamInit<>`.

I'd recommend removing any overlap this has with `ParamInit<>`, and restate the docs as ``The deprecated flavor of `ParamInit<>` ``.
___
*[bindings/pydrake/systems/test/sensors_test.py, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSKhDAC5bsjwVlDylz:-MMSKhDAC5bsjwVlDym-:blf6r9c) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce7e7a3f40be31fdd717775fa75498bbd3ed75a/bindings/pydrake/systems/test/sensors_test.py#L270)):*
> ```Python
>         height = 720
> 
>         # TODO: There are *two* variants of the constructor: one with color and
> ```

This isn't really phrased as a TODO? (also, it seems done?)

Is it stale?
___
*[geometry/render/render_camera.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSL7vQ6K8sf6AY9J2p:-MMSL7vQ6K8sf6AY9J2q:bmxypbb) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1f39ac04e4ea028837555a79e5645cc4377381/geometry/render/render_camera.cc#L28)):*
> ```cpp
>                        CameraInfo{camera.width, camera.height, camera.fov_y},
>                        ClippingRange{kClippingNear, clipping_far},
>                        std::move(X_BS)) {}
> ```

nit This move seems redundant, possibly harmful?

(I can dig up Soonho's old post about copy elision vs. move if you'd like)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Hopefully fixing CI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMSkPVQCMmsLoc1y7nT:bnk3lvw)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/common/deprecation_pybind.h, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSJYg052z3ebp20hsq:-MMSSF68BpFNnqTEHHVq:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce7e7a3f40be31fdd717775fa75498bbd3ed75a/bindings/pydrake/common/deprecation_pybind.h#L101)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The volume of this text made it hard for me to know if this added more bells and whistles, or if it's really just a deprecated version of `ParamInit<>`.

I'd recommend removing any overlap this has with `ParamInit<>`, and restate the docs as ``The deprecated flavor of `ParamInit<>` ``.
</blockquote></details>

Done
___
*[bindings/pydrake/systems/test/sensors_test.py, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSKhDAC5bsjwVlDylz:-MMSSWII0OXz76iYndrk:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce7e7a3f40be31fdd717775fa75498bbd3ed75a/bindings/pydrake/systems/test/sensors_test.py#L270)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This isn't really phrased as a TODO? (also, it seems done?)

Is it stale?
</blockquote></details>

Done
___
*[geometry/render/render_camera.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSL7vQ6K8sf6AY9J2p:-MMSSf1V8KGofE8qdLtK:b-tjyavl) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1f39ac04e4ea028837555a79e5645cc4377381/geometry/render/render_camera.cc#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This move seems redundant, possibly harmful?

(I can dig up Soonho's old post about copy elision vs. move if you'd like)
</blockquote></details>

Please do. I can't see the harm or the redundancy. I would've thought, worse case, it'd be no worse than the copy constructor.

**Review by sammy-tri — COMMENTED** [review]
I'm offline for the rest of the day, but I don't mind being platform review, will pickup this PR tomorrow morning.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMSmoLS4_dZ6Vg8Apv2:b42nddk)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks! That'll be great. I'm about to disconnect as well.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMSnIjf5sIhDt5KIY0x:b-nqndwc)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/systems/test/sensors_test.py, line 271 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMTNXa5CZ-UZ_PYuNBL:-MMTNXa69k8ji39S_7Z6:b3g06ha) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f4853dd694422bd56f76d04cb9b6279cc80382/bindings/pydrake/systems/test/sensors_test.py#L271)):*
> ```Python
> 
>         # There are *two* variants of the constructor for each camera
>         # representaiton: one with color and depth explicitly specified and one
> ```

nit misspelling: "representaiton"

(Made it a `nit` since CI is failing ;)
___
*[geometry/render/render_camera.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMSL7vQ6K8sf6AY9J2p:-MMTObJM7giqeTpzoOk-:b-k22j10) ([raw file](https://github.com/robotlocomotion/drake/blob/9d1f39ac04e4ea028837555a79e5645cc4377381/geometry/render/render_camera.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Please do. I can't see the harm or the redundancy. I would've thought, worse case, it'd be no worse than the copy constructor.
</blockquote></details>

OK Ah, I crossed my wires, sorry!

I was thinking about some of the points here:
https://developers.redhat.com/blog/2019/04/12/understanding-when-not-to-stdmove-in-c/
But that only makes sense for return values. That is not the case here, because it's used in a member initialization.

(I think I crossed them due to it being the last statement...)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I think/hope I figured out the CI issues.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMWBYUkChHu0b_s_-On:b-1hjk8z)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/systems/test/sensors_test.py, line 271 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMTNXa5CZ-UZ_PYuNBL:-MMWe3Hy4CQNIDzVPri4:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f4853dd694422bd56f76d04cb9b6279cc80382/bindings/pydrake/systems/test/sensors_test.py#L271)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit misspelling: "representaiton"

(Made it a `nit` since CI is failing ;)
</blockquote></details>

Done

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 3 of 4 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/common/deprecation_pybind.h, line 103 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMWediy1l4sQ_Z1oium:-MMWediy1l4sQ_Z1oiun:b-5nqrzj) ([raw file](https://github.com/robotlocomotion/drake/blob/69e1b6bad9041737c426582199db6ebd53e45032/bindings/pydrake/common/deprecation_pybind.h#L103)):*
> ```objc
> /// The deprecated flavor of ParamInit<>.
> template <typename Class>
> auto DeprecatedParamInit(py::str message) {
> ```

should this have a test or some sort (probably in  `bindings/pydrake/common/test/deprecation_example/`)?  Alternately maybe have a comment somewhere noting that it should be removed when it's sole user goes away, so that we're not left with code in the tree that's never invoked?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/common/deprecation_pybind.h, line 103 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMWediy1l4sQ_Z1oium:-MMWjCpwEEZw8KT1gDX-:bve2lfh) ([raw file](https://github.com/robotlocomotion/drake/blob/69e1b6bad9041737c426582199db6ebd53e45032/bindings/pydrake/common/deprecation_pybind.h#L103)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

should this have a test or some sort (probably in  `bindings/pydrake/common/test/deprecation_example/`)?  Alternately maybe have a comment somewhere noting that it should be removed when it's sole user goes away, so that we're not left with code in the tree that's never invoked?
</blockquote></details>

Oops. Good point.

I've put it into the `cc_module_py.cc`. We definitely don't want to remove it. The nature of deprecation machinery is that they should be available, even if they're not *currently* exercised.  And as long as we're creating constructors with `ParamInit`, we should be able to deprecate those with `DeprecateParamInit`.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14358#-:-MMWyChd0XbnsacYOXNv:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform)

**Comment by EricCousineau-TRI** [comment]
Just to follow-up: What was the root cause of the stuff mentioned in d4115d2?

Was it some weird expression evaluation ordering that you fixed by removing `std::move()` here?
image

**Comment by EricCousineau-TRI** [comment]
(or more concretely: was it a `pybind11` issue, or a C++ issue?)

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/common/test/deprecation_example/cc_module_py.cc, line 33 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14358#-MMXCOTRBoH4S3Ygqrbl:-MMXCOTRBoH4S3Ygqrbm:bonw6p1) ([raw file](https://github.com/robotlocomotion/drake/blob/0c95a57322342ae66b9f18b6e6c16ce6b49e9cf7/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L33)):*
> ```cpp
>     //   o.i = 1
>     //   o.j = 2
>     py::class_<Class> cls(m, "ExampleCppStruct", cls_doc.doc);
> ```

To be properly tested / not a lie, this should've had some Python code to support this.

I'll file a brief follow-up PR.

**Comment by SeanCurtis-TRI** [comment]
It's quite weird. I think it was a confluence of pybind, gcc, and debug. But, yeah. Essentially, the move into the depth camera was preceding the copy into the color camera (despite the ordering of the members in the class). So, by the time the color camera was processed, the name was gone. Clang was happy, and gcc in release was happy. And, C++ was happy -- we have unit tests testing that API. But all three together made things angry! So, rather than figuring out the cause for anger, I decided this was a reasonable away *around* the anger.

**Comment by EricCousineau-TRI** [comment]
K, sgtm. I'll a low-priority issue to track this bug. Not a huge deal if it's just in our `pybind11`, but maybe a bigger deal if it affects upstream.

**Pull request merged**
