### PR TITLE
Changed rod to use general constraint solver (rather than bespoke LCP…

### PR DESCRIPTION
**Pull request by edrumwri**
… formulation).

Additionally, cfm and erp are now computed from stiffness, dt, and dissipation parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7365)

### CODE REVIEW

**Comment by sherm1** [comment]
Feature :lgtm: after a few minor BTWs.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/rod2d/rod2d-inl.h, line 796 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtKKErz_aY-n5xmwDC:-KxtKKErz_aY-n5xmwDD:bv7fjbw) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L796)):*
> ```objc
>   const Vector3<T> fext = ComputeExternalForces(context);
>   v += dt_ * problem_data.solve_inertia(fext);
>   problem_data.Mv = GetInertiaMatrix() * v;
> ```

BTW Per f2f: (assume v was already v₀) This calculates
```
Mv = M (v0 + hM⁻¹f)
```
but could instead calculate
```
Mv = M v0 + hf
```
which avoids multiplication by M⁻¹ and potential cancellation errors.

---

*[drake/examples/rod2d/rod2d-inl.h, line 821 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtNuL9CY-SvS2ZSjRW:-KxtNuL9CY-SvS2ZSjRX:bz131u3) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L821)):*
> ```objc
>   VectorX<T> vplus = v + delta_v;
> 
>   // Compute the new position using explicit Euler integration.
> ```

BTW this is explicit (since doesn't involve qplus) but isn't really explicit Euler despite appearances. It is the explicit half of the semi-implicit Euler integration scheme. (Although ours doesn't actually handle the first half implicitly either.) Consider "Compute the new position. This is the explicit part of a semi-implicit Euler scheme which part looks like an explicit Euler step." If that doesn't seem better feel free to ignore.

---

*[drake/examples/rod2d/rod2d-inl.h, line 1321 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQ3tYvkxYZZNnlYI_:-KxtQ3tYvkxYZZNnlYIa:b85i2al) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L1321)):*
> ```objc
>   M_inv << 1.0 / mass_, 0, 0,
>       0, 1.0 / mass_, 0,
>       0, 0, 1.0 / J_;
> ```

BTW please fix alignment to be beautiful like the new method above.

---

*[drake/examples/rod2d/rod2d.h, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxsbluyAw-UmL7JixiR:-Kxsbluzhq5ZiylOYH0K:b-2gjnvb) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L221)):*
> ```objc
>   /// systems only).
>   double get_cfm() const {
>     return 1.0 / (stiffness_ * dt_ + dissipation_);
> ```

BTW This should be stiffness k (units of N/m) and damping c (N/(m/s)) rather than dissipation which has units of (1/(m/s)). The formula is right, just needs a name change from dissipation->damping.

---

*[drake/examples/rod2d/rod2d.h, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQWrkDRtztoNkF1xD:-KxtQWrkDRtztoNkF1xE:bphizoz) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L225)):*
> ```objc
> 
>   /// Gets the error reduction parameter (ERP, used for time stepping
>   /// systems only).
> ```

BTW do you want to mention that the returned value is always between 0 and 1?

---

*[drake/examples/rod2d/rod2d.h, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxscswI27Do7WaxusEK:-KxscswI27Do7WaxusEL:bhw3z3c) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L227)):*
> ```objc
>   /// systems only).
>   double get_erp() const {
>     return dt_ * stiffness_ / (stiffness_ * dt_ + dissipation_);
> ```

BTW dissipation->damping

---

*[drake/examples/rod2d/rod2d.h, line 305 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQcyaTuPHpHTiiYvZ:-KxtQcyaTuPHpHTiiYv_:b1d4c6g) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L305)):*
> ```objc
>   /// Sets stiffness and dissipation for the rod from cfm and erp values (used
>   /// for time stepping implementations).
>   void SetStiffnessAndDissipation(double cfm, double erp) {
> ```

BTW this should be `SetStiffnessAndDamping()` -- see comment above.

---

*[drake/examples/rod2d/test/rod2d_test.cc, line 707 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtR1ji8wrBxNpdDK0O:-KxtR1ji8wrBxNpdDK0P:b-1ua5mx) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/test/rod2d_test.cc#L707)):*
> ```cpp
>   // Compute the derivatives and verify that the linear and angular acceleration
>   // are approximately zero.
>   const double eps = 250 * std::numeric_limits<double>::epsilon();
> ```

BTW use tol instead of eps here for consistency? eps sounds like epsilon. 
Also, consider setting `eps = std::numeric_limits<double>::epsilon()` at the top of this file so you don't have to keep repeating the long form.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-:-KxtRY2YoiClLzQ23RjX:b-r9bc63)*

**Comment by edrumwri** [comment]
I put in a conversion for transformation from dissipation to damping. I'm pretty sleepy, so your normal, thorough check of my math will be greatly appreciated :)

---

Review status: 2 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/rod2d/rod2d-inl.h, line 796 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtKKErz_aY-n5xmwDC:-KxtfAXMYRnzUPCeILXd:bi609ye) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L796)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Per f2f: (assume v was already v₀) This calculates
```
Mv = M (v0 + hM⁻¹f)
```
but could instead calculate
```
Mv = M v0 + hf
```
which avoids multiplication by M⁻¹ and potential cancellation errors.
</blockquote></details>

BTW Right- I end up needing this updated v below, rather than Mv, so it's not really a win here.

---

*[drake/examples/rod2d/rod2d-inl.h, line 821 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtNuL9CY-SvS2ZSjRW:-KxtekTiDy2ZT2QY-aGy:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L821)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is explicit (since doesn't involve qplus) but isn't really explicit Euler despite appearances. It is the explicit half of the semi-implicit Euler integration scheme. (Although ours doesn't actually handle the first half implicitly either.) Consider "Compute the new position. This is the explicit part of a semi-implicit Euler scheme which part looks like an explicit Euler step." If that doesn't seem better feel free to ignore.
</blockquote></details>

PTAL.

---

*[drake/examples/rod2d/rod2d-inl.h, line 1321 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQ3tYvkxYZZNnlYI_:-Kxtdwho-4WBcD7TRI__:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d-inl.h#L1321)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please fix alignment to be beautiful like the new method above.
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d.h, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxsbluyAw-UmL7JixiR:-KxuaIQzk07vkaFSRcqH:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L221)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW This should be stiffness k (units of N/m) and damping c (N/(m/s)) rather than dissipation which has units of (1/(m/s)). The formula is right, just needs a name change from dissipation->damping.
</blockquote></details>

PTAL.

---

*[drake/examples/rod2d/rod2d.h, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQWrkDRtztoNkF1xD:-KxteFLWIf-WPdGcIcaf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L225)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW do you want to mention that the returned value is always between 0 and 1?
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d.h, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxscswI27Do7WaxusEK:-Kxv5Fr_MklZ-ogHXIvz:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L227)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW dissipation->damping
</blockquote></details>

PTAL.

---

*[drake/examples/rod2d/rod2d.h, line 305 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtQcyaTuPHpHTiiYvZ:-Kxv5HwN3UUGxIPbUe80:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/rod2d.h#L305)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this should be `SetStiffnessAndDamping()` -- see comment above.
</blockquote></details>

PTAL.

---

*[drake/examples/rod2d/test/rod2d_test.cc, line 707 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-KxtR1ji8wrBxNpdDK0O:-KxteVo0Xx7PW8bTuLmw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e577c21c3f5d1f5ac7601886600cc7c3f4789de/drake/examples/rod2d/test/rod2d_test.cc#L707)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW use tol instead of eps here for consistency? eps sounds like epsilon. 
Also, consider setting `eps = std::numeric_limits<double>::epsilon()` at the top of this file so you don't have to keep repeating the long form.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-:-Kxv6_qVGrMacA1e0PB7:b96fwx1)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by sherm1** [comment]
Added a few suggestions about the dissipation->damping transform, which is a cool idea.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[drake/examples/rod2d/rod2d.h, line 241 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2iPCn7wU9wgG_RliL:-Ky2iPCn7wU9wgG_RliM:bjszoki) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L241)):*
> ```objc
>   }
> 
>   /// Transforms damping to dissipation (α), given the amount of deformation.
> ```

BTW  Cool! An interesting idea. 
Comment is backwards (diss->damp)

---

*[drake/examples/rod2d/rod2d.h, line 246 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2iW2ucoGp17xUDH2s:-Ky2iW2ucoGp17xUDH2t:b-np62dc) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L246)):*
> ```objc
>     // assume that the stiffness and dissipation are determined for a small
>     // deformation (x), which we will somewhat arbitrarily represent using a
>     // scale factor of 1/1000.
> ```

BTW I'd call that an "assumed characteristic deformation of 1mm" rather than a "scale factor".

As I understand this, it is linearizing the H&C model about a penetration of 1mm. That is, the system will behave like a harmonic oscillator oscillating around x=1mm, for very small amplitudes. Please consider explaining that in the comment.

Also, consider making the linearization point an argument, just so it will show in the call -- `TransformDissipationToDampingAbout(.001)` or something like that.

---

*[drake/examples/rod2d/rod2d.h, line 357 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2loMzxAiaxkWbd-a8:-Ky2loMzxAiaxkWbd-a9:bfeto5p) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L357)):*
> ```objc
>     const double alpha = b / (1.5 * k * characteristic_deformation *
>         half_length_);
>     set_dissipation(alpha);
> ```

BTW this should be using the Transform...() method you wrote. See my comments above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-:-Ky2m0S_hA8mrBJwg25u:b-qutbp)*

**Comment by edrumwri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/rod2d/rod2d.h, line 241 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2iPCn7wU9wgG_RliL:-Ky2oDbLKjbaopsJ-KbG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L241)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW  Cool! An interesting idea. 
Comment is backwards (diss->damp)
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d.h, line 246 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2iW2ucoGp17xUDH2s:-Ky2oKSngGggd1rx30pj:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L246)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'd call that an "assumed characteristic deformation of 1mm" rather than a "scale factor".

As I understand this, it is linearizing the H&C model about a penetration of 1mm. That is, the system will behave like a harmonic oscillator oscillating around x=1mm, for very small amplitudes. Please consider explaining that in the comment.

Also, consider making the linearization point an argument, just so it will show in the call -- `TransformDissipationToDampingAbout(.001)` or something like that.
</blockquote></details>

PTAL.

---

*[drake/examples/rod2d/rod2d.h, line 357 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2loMzxAiaxkWbd-a8:-Ky2pF-Gn8pZMbRZRHRx:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/a4c0c7ef4583214d92cf80645ae2591c9b77387f/drake/examples/rod2d/rod2d.h#L357)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this should be using the Transform...() method you wrote. See my comments above.
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365)*

**Comment by sherm1** [comment]
One new question ...

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/examples/rod2d/rod2d.h, line 257 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2wB5FBaLCALFDzEKN:-Ky2wB5FBaLCALFDzEKO:bzi0e5b) ([raw file](https://github.com/robotlocomotion/drake/blob/576c92836761c6f66db5bede62a6ce8446c91848/drake/examples/rod2d/rod2d.h#L257)):*
> ```objc
>   /// Transforms damping (b) to dissipation (α) , given a characteristic
>   /// deformation.
>   double TransformDampingToDissipationAboutDeformation(
> ```

BTW this doesn't appear to be used?

---

*[drake/examples/rod2d/rod2d.h, line 372 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2wH2ONE57RzvKDVtP:-Ky2wH2ONE57RzvKDVtQ:bgob1rn) ([raw file](https://github.com/robotlocomotion/drake/blob/576c92836761c6f66db5bede62a6ce8446c91848/drake/examples/rod2d/rod2d.h#L372)):*
> ```objc
>     const double characteristic_deformation = 1.0 / 1000;
>     const double alpha = b / (1.5 * k * characteristic_deformation *
>         half_length_);
> ```

BTW did you mean to use the new TransformDampingToDissipationAboutDeformation() here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-:-Ky2wM2vPZT61jRV08uL:bu336xf)*

**Comment by edrumwri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/rod2d/rod2d.h, line 257 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2wB5FBaLCALFDzEKN:-Ky2wtZs48xKbj_vKzRl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/576c92836761c6f66db5bede62a6ce8446c91848/drake/examples/rod2d/rod2d.h#L257)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this doesn't appear to be used?
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d.h, line 372 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-Ky2wH2ONE57RzvKDVtP:-Ky2wttJlbZR0ELYaKn2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/576c92836761c6f66db5bede62a6ce8446c91848/drake/examples/rod2d/rod2d.h#L372)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW did you mean to use the new TransformDampingToDissipationAboutDeformation() here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365)*

**Comment by sherm1** [comment]
:lgtm: (feature & platform)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7365#-:-Ky3F9Jm0ok1lBG6R2pI:b-1huhtz)*

**Pull request merged**
