### PR TITLE
[sensors] Simplify the creation of empty images

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Inspired by being annoyed by this during #19436.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19443)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@kunimatsu-tri for feature review, please.

**Review by kunimatsu-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19443#-:-NW3GmwW8lEXMth9pBxR:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19443#-:-NW3Pmya5_8lZ_WxLQWU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),kunimatsu-tri

**Pull request merged**
