### PR TITLE
Add DiscreteTimeDelay system block

### PR DESCRIPTION
**Pull request by mpetersen94**
I'm opening this pull request to get feedback on the design of this system before implementing the abstract version and adding python bindings.  I'm also curious about thought on the best suite of tests for this system.  The test (and the system as a whole) are currently based off the ZeroOrderHold system.

cc @sherm1, @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10856)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[systems/primitives/time_delay.cc, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10856#-L_Q06no1HFCQh3SNQxT:-L_SHiCv5m0RGKB02kRo:bvst4cf) ([raw file](https://github.com/robotlocomotion/drake/blob/2d7591b2ea7614db61dc0b8e6d3c0250de3a182d/systems/primitives/time_delay.cc#L67)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

good question.

in the ring buffer case, the integer index would have be declared as additional state.  integer state is hard to reason about.

i do think that the analysis tools would like to see the state effectively sliding backwards.  it might still be possible to provide that abstract without copying the memory (e.g. by deriving from Context?), and i would prefer to get the mathematical model right first and address performance if/when it becomes a concern?  @sherm1 and @jwnimmer-tri might want to chime in on this specifically.

one note -- your implementation above might be the right thing for abstract states.  it's only the vector states where I think we should do better.  but i also think that it would be ok to land a first version of this with a TODO for abstract state support.
</blockquote></details>

I think in the discrete update handler here, doing the full slide-back copy will not be too dangerously expensive.  It's will just turn into memcpy under the hood, without any special guards or new heap allocations.  Even if we have an 100-wide input with 10-step delay, that's still only 8kb to copy, likely aligned on a nice memory boundary already.

In a follow-up PR, we might be able to optimize it by using a BasicVector subclass for our discrete state declaration (e.g., CircularVector is-a BasicVector), so then in the event handler we could slide by calling `dynamic_cast<CircularVector&>(context.get_mutable_discrete_state(0)).rotate(num_inputs)` or similar.

**Comment by jwnimmer-tri** [comment]
___
*[systems/primitives/time_delay.cc, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10856#-L_Q06no1HFCQh3SNQxT:-L_SgjBr0PRxk5IdevgM:b7pl5xy) ([raw file](https://github.com/robotlocomotion/drake/blob/2d7591b2ea7614db61dc0b8e6d3c0250de3a182d/systems/primitives/time_delay.cc#L67)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Ok, I'll implement the sliding buffer for the discrete state version.  For the abstract state version, what is the consensus?  Would a similar implementation work or should I use something more like what I currently have implemented?  Or option 3, should I defer an abstract state delay to a separate PR?
</blockquote></details>

For me, I am OK if the abstract waits for another PR.

Whichever PR its in, the memory layout doesn't matter -- so if you'd like to have a circular buffer with "int begin_offset" that's fine.  It might make sense to have something like this:
```
struct TimeDelayAbstractState {
  int current = 0;
  drake::copyable_unique_ptr<drake::systems::AbstractValues> values;
}

TimeDelay::TimeDelay(... /*abstract version */ ... model_input) {
  std::vector<std::unique_ptr<AbstractValue>> data;
  data.reserve(update_depth);
  for (0..update_depth) { data.emplace_back(model_input.Clone()); }
  TimeDelayAbstractState model_state;
  model_state.values = make_unqiue(AbstractValues(std::move(data)));
  this->DeclareAbstractState(AbstractValue::Make(model_state));
}
```

**Comment by jwnimmer-tri** [comment]
With platform review on-call hat on: it seems like +@sherm1 is already involved in feature review; @sherm1 are you willing to be the official assignee?  Otherwise, let's try to find someone to be on the hook, so this doesn't linger.

**Comment by sherm1** [comment]
Yes, I'm happy to be feature reviewer for this nice Drake addition.

**Comment by sherm1** [comment]
___
*[systems/primitives/discrete_time_delay.h, line 24 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10856#-L_tQdk18QRZym7WMPh5:-L_uW4aQ25CXShjMkYm2:b-33pu6o) ([raw file](https://github.com/robotlocomotion/drake/blob/16b9a67156afb1233b205d79df5b83866dc06717/systems/primitives/discrete_time_delay.h#L24)):*
> For future reference, how do you write these unicode comments?

These are my favorite techniques, applied in this order:
1. If I'm looking at some nice Unicode, cut and paste!
2. Otherwise, go to http://www.unicodeit.net which lets you type in LaTeX and get back unicode.
3. If that doesn't work, ask google for "Unicode arrows" and things like that. There are lots of web sites displaying the available characters, suitable for cut and paste.

**Pull request merged**
