### PR TITLE
Rename libspdlog.so to libdrake_spdlog.so

### LINKED ISSUE #12393: Rename libspdlog.so to libdrake_spdlog.so in install tree
cf. `libdrake_ignition_math.so`, `libdrake_lcm.so`.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #12393.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13698)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Comment by jwnimmer-tri** [comment]
Can you elaborate on the motivation?  To my eye, the current revision on master is correct.

For things like ignition and sdformat, they are private dependencies with headers not included by Drake's public headers, so we should be linking them statically (+ hidden) in any case, such that the shared library name is irrelevant.

For spdlog, it is a public dependency and we use it in our public headers with its conventional C++ namespace.  We are essentially providing a pre-compiled release of it as part of our larger binary release, and we intend the shared library to be compatible with both Drake and with any other ecosystem dependencies that require spdlog.  Under that umbrella, it seems like we should be using the conventional upstream name for the shared library as well?  It would not be possible for a user to supply their own, different `libspdlog.so` even if our library name is `libdrake_spdlog.so`; the symbols would be duplicated and step on each other's toes, since the C++ namespace would be the same for both libraries.

**Comment by jamiesnape** [comment]
Conventionally a vendored library would have its name mangled as much to prevent causing problems with other libraries that require spdlog, rather than a different spdlog causing drake and its dependencies issues. This is especially a problem since bazel does not version its shared libraries with their ABI.

**Comment by jamiesnape** [comment]
Note also, https://packages.ubuntu.com/focal/libspdlog1, which is `libspdlog.so`.

**Comment by jwnimmer-tri** [comment]
To me, the issue with thinking of spdlog as "vendored" is that spdlog is a vocabulary type across API and ABI boundaries (akin to `std::function`, for example).  It would be wrong for a user to have several different definitions of it, even if the loader didn't complain -- there should be one definition used by all code that logs, so the logging levels, channels, etc are controllable in one place for many log-generation sources.  We don't want our library sink to be incompatible with other revisions spdlog within the same application binary.

So for sure, we should try to change our build on focal to use the OS revision of spdlog if we can.  Its vendored fmt integration may be problematic, though.  It looks like sid has libfmt-dev separately, but bionic does not appear to.  We should see if anything in ROS cares (see, e.g., https://github.com/ros2/rcl_logging/pull/17).

Possibly the ecosystem is fractured enough that we need to stop using spdlog directly, and only offer the ability to bind into it -- but where drake itself (other than the log adapter) does not touch spdlog.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jwnimmer-tri** [comment]
I discussed this with Jamie on a call last week.  The background info not explained above is that this change should make the debian packaging easier, e.g., that we can regex on the shared library names to understand how to tease apart the install into packages.

In that light, "differently wrong" will be sufficient here -- both master and this PR are wrong (per the above discussions), but if apt packages are easier with this wrong instead of the other wrong, then I can support this.

I'll peek at the experimental binaries and then can LGTM this.

**Comment by jwnimmer-tri** [comment]
I am checking the tarball now.

But @jamiesnape looking at the Jenkins output, it reads to me like the experimental build created a docker tag 20200727 -- this seems wrong, like I stomped on the nightly release?

**Comment by jamiesnape** [comment]
Looks fine. The tag was not pushed. On the nightly builds you will see additional lines of output where that happens.

**Pull request merged**
