### PR TITLE
Add BUILD for automotive simulator and demo

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Specific items:
- Remove spurious include
- Use DrakeMockLcm for TestTrajectoryCarWithSdf tests
- Add BUILD for gflags
- Add BUILD for spruce, tinydir, tinyxml2
- Add BUILD for util (only some)
- Add BUILD for lcmt_viewer
- Add BUILD for multiplexer
- Add BUILD for drake/multibody (RBT only)
- Add BUILD for automotive_demo
- Add BUILD for automotive_simulator_test

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4235)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri and +@david-german-tri for review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-:-KXGL8n-tVDRDx6uh8KZ:b-menlzv)*

**Comment by rpoyner-tri** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGWbt3_hE8CyMc14ef:-KXGWbt4E-SsGX7ofCAK:b5vosli) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/WORKSPACE#L22)):*
> ```
> )
> 
> bind(
> ```

I am not familiar with `bind`, and what I read about it only troubles me: https://github.com/bazelbuild/bazel/issues/1952

Thoughts?

---

*[drake/automotive/BUILD, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGXEZ1JTnG-OFURkvM:-KXGXEZ2j5LHYCNTd6F3:b-lpnnjq) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/drake/automotive/BUILD#L123)):*
> ```Python
>     name = "models",
>     srcs = glob(["models/**"]),
>     visibility = ["//visibility:public"])
> ```

hm, is this visibility spec necessary, given the `package` statement?

---

*[drake/common/BUILD, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGYrinO1WaWIRUSP4S:-KXGYriplW_WFtSf9aA7:b-xhyngf) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/drake/common/BUILD#L132)):*
> ```Python
>     hdrs = ["text_logging_gflags.h"],
>     deps = [":common", "//external:gflags"],
>     linkopts = ["-pthread"],
> ```

Is this linkopts requirement induced by gflags? If so, I'd prefer some sort of rule phrasing that declares this at dependency root, rather than at the branches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGWbt3_hE8CyMc14ef:-KXGjxSP2SC26aT_KUgV:b8pdjic) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/WORKSPACE#L22)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> I am not familiar with `bind`, and what I read about it only troubles me: https://github.com/bazelbuild/bazel/issues/1952
> 
> Thoughts?
</details>
Done.

I found gflags instructions saying to do it this way, but agree it seems to be stale / deprecated advice.  I've matched it to the rest now.

---

*[drake/automotive/BUILD, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGXEZ1JTnG-OFURkvM:-KXGkd1cqyiN-Iw2IZYQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/drake/automotive/BUILD#L123)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> hm, is this visibility spec necessary, given the `package` statement?
</details>
Done.

---

*[drake/common/BUILD, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGYrinO1WaWIRUSP4S:-KXGlBtIKnYyJrH5OO6c:b5ptc9s) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/drake/common/BUILD#L132)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Is this linkopts requirement induced by gflags? If so, I'd prefer some sort of rule phrasing that declares this at dependency root, rather than at the branches.
</details>
Agreed.  I haven't quite figured this out yet, so put a TODO here instead.  In practice, all uses of gflags in Drake (will) use ":text_logging_gflags" anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/BUILD, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXGYrinO1WaWIRUSP4S:-KXGqZfbwV_RtMvkCRop:bsqw7iz) ([raw file](https://github.com/robotlocomotion/drake/blob/beefc7971d41948298df7c3192d8729be8f675dc/drake/common/BUILD#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Agreed.  I haven't quite figured this out yet, so put a TODO here instead.  In practice, all uses of gflags in Drake (will) use ":text_logging_gflags" anyway.
</details>
Meh, good enough for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-:-KXGqjt_1u8Sd98PVcDm:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 113 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfibc2nQcE5yqgXxuL:-KXfibc2nQcE5yqgXxuM:b-7e0otj) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/automotive/BUILD#L113)):*
> ```Python
> cc_binary(
>     name = "automotive_demo",
>     srcs = ["automotive_demo.cc", "create_trajectory_params.cc", "create_trajectory_params.h"],
> ```

BTW one per line please

---

*[drake/common/BUILD, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfkvdwrx2p1_vC8aPg:-KXfkvdwrx2p1_vC8aPh:bw7muui) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/common/BUILD#L100)):*
> ```Python
>     deps = [":common"],
>     linkstatic = 1)
> genrule(
> ```

Could you add a TODO saying that this should die in a fire once we have properly-expressed data dependencies?

https://www.bazel.io/versions/master/docs/build-ref.html#types_of_dependencies

Probably can't happen until CMake is gone though.

---

*[drake/multibody/BUILD, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfk4lPSllhLDcj-RBv:-KXfk4lQKSIUbIEedLvh:bpd01x3) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/multibody/BUILD#L21)):*
> ```Python
>         "rigid_body_tree.cc",
>         "xml_util.cc",
>         # N.B. Not yet "collision/bullet_model.cc",
> ```

btw this is kind of cryptic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-:-KXfkfFocBNR6c-izSZD:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 113 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfibc2nQcE5yqgXxuL:-KXfmqzTeUNd1242vKR4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/automotive/BUILD#L113)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW one per line please
</blockquote></details>

Done.

---

*[drake/common/BUILD, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfkvdwrx2p1_vC8aPg:-KXfo1U4LEDFU_h24uVE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/common/BUILD#L100)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Could you add a TODO saying that this should die in a fire once we have properly-expressed data dependencies?

https://www.bazel.io/versions/master/docs/build-ref.html#types_of_dependencies

Probably can't happen until CMake is gone though.
</blockquote></details>

Done.

---

*[drake/multibody/BUILD, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfk4lPSllhLDcj-RBv:-KXfoMiLfiVScej3bsXE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54027c054fbe03be4b39167a6a9bf26de3c34f32/drake/multibody/BUILD#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

btw this is kind of cryptic
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Comment by rpoyner-tri** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/BUILD, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfx92QL9qO7BmVfn0N:-KXfx92RvocRl8dOIb_u:bgw1mx3) ([raw file](https://github.com/robotlocomotion/drake/blob/b42991f1f8a7a10563be9da89c89e34bd20416bc/drake/common/BUILD#L103)):*
> ```Python
> # here in Bazel is intended as a temporary shim, in order to support Bazel and
> # CMake build systems concurrently.  We should endeavor to remove this rule (in
> # lieu of properly-declared data dependencies) once we are unchaned from CMake.
> ```

sp.: "unchaned" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/BUILD, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4235#-KXfx92QL9qO7BmVfn0N:-KXfyCkl5vRvk82wfn1M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b42991f1f8a7a10563be9da89c89e34bd20416bc/drake/common/BUILD#L103)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

sp.: "unchaned" ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Comment by david-german-tri** [comment]
Reviewed 6 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4235)*

**Pull request merged**
