### PR TITLE
DRC Terrain Files: Modified

### PR DESCRIPTION
**Pull request by scottviteri**
Added files necessary to generate DRC terrain simulation.

Originally I created the files using an architecture that necessitated support for non-static bodies. These unsurprisingly failed in Drake. 
This pull request includes cleaned up files, and a much better layout without non-static dependencies. Here are some pictures: first in Gazebo, then natively in Drake, and lastly in Drake with Atlas.

modifiednonstaticfield

modifiedfielddrake

atlasonfield

### CODE REVIEW

**Comment by RussTedrake** [comment]
these don't run in drake yet.  and a LOT more changed than I expected, including the addition of many new files (even new world files).  i'm hoping you can take another clean up pass before I dig in, and give us the minimal required commit?

**Comment by scottviteri** [comment]
Okay. 

And the reason I had to change so much is that not only was the original world file not accurate in several ways, but also I needed to change some structure completely in order to make it accurate. 

So I created and edited some ruby programs that generate the SDF files that I am using in my world file} There is a secord world file because that one is product of Gazebo saving the final terrain and exporting its own formulation of the xml structure. This is unneccessary: but I included it anyways in the hope that it might play nicer with the Drake parser.

Everything added is meant to be there, I just need to work on modifying either the parser or the files or both to allow a Drake visualization.

Thanks,
Scott

**Comment by rdeits** [comment]
I just tested this out. It looks great, except that both the flat and tilted cinder block stacks are slightly below the ground level: https://www.dropbox.com/s/qaxwd8svqjqyke5/terrain_below_ground.mp4?dl=0

Can you shift them up appropriately, Scott?

**Comment by RussTedrake** [comment]
will go ahead and merge this.  thanks @scottviteri !  if you can send a new pull request to raise them up slightly, that would be fantastic!

**Pull request merged**
