### PR TITLE
Updates AutomotiveSimulator to wire up velocity outputs of vehicle models to PoseAggregator.

### PR DESCRIPTION
**Pull request by liangfok**
Controllers like IDM need velocity state.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5894)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please. We really ought to figure out how to add unit test coverage for these wirings. Maybe we can add a sink that stores the output of `PoseAggregator` in its state, which we can then be analyzed by exposing the `Context`?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-Ki8WKiOAzYS7Oc4W5Za:biowj1q)*

**Comment by jadecastro** [comment]
Yes.  Alternatively the unit test could check check connectivity, by directly analyzing the `*.dot` file produced by `GetGraphvizString`?  I'm unsure whether this would be better than checking the context.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiUa4xzKQwmBd-DF6LC:bbjv6yo)*

**Comment by liangfok** [comment]
Interesting idea. I hadn't considered checking a `.dot` file for wiring correctness. In the past, I attempted to add methods to `Diagram` to directly check the wiring, but was rebuffed saying I should instead "test the behavior that actually matters":

https://github.com/RobotLocomotion/drake/pull/4218#issuecomment-263297792

I wonder if checking the `.dot` file would also fall under the defect of not checking the behavior that actually matters.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiUycxA-VpCoWipEW0t:b-y2r4l8)*

**Comment by jadecastro** [comment]
I see. I think that checking the behaviors makes a lot more sense than checking only the wiring. For the case of `IdmControlledMaliputRailcar`, I believe it is enough for the unit test to start with two such cars in the same lane, set initial `speed` to different settings, and then verify that, after running `StepBy()`, that the LCM messages behave as expected?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiV0KJFpZlROrHQeNu5:bd34wko)*

**Comment by liangfok** [comment]
I agree and will update this PR accordingly. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiVcFX8jSScf-IsFowS:b404wad)*

**Comment by liangfok** [comment]
Currently, the velocity information within `AutomotiveSimulator`'s`PoseAggregator`'s output is not revealed over LCM. It will take more work to obtain the velocity information. I shall thus apply the "do not review" label while I figure out how to reveal the velocity information.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiVi9zTG5Mw17mCZOR7:bsrlotn)*

**Comment by liangfok** [comment]
I considered using `PoseBundleToDrawMessage` but decided against it because `lcmt_viewer_draw` messages do not contain velocity information. I'm now thinking about implementing a `PoseBundleToRobotStateMessage` system that outputs `lcmt_robot_state` messages, which contain velocity information.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiVskBALduFxKtVpKWd:bzii4ls)*

**Comment by jadecastro** [comment]
Or, to get around having to add messages, just execute `StepBy()` a fixed number of times, and then compare the resulting position messages for one initial `speed` setting to other `speed` settings? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiVuw6f3Lotazx_OlqM:bp0n5jj)*

**Comment by jwnimmer-tri** [comment]
Absolutely.  Adding messages that nobody cares about should is not a good way to test.

**Comment by liangfok** [comment]
Alright. I will attempt to infer the wiring of `MaliputRailcar's velocity output into `PoseAggregator` based on the observed behavior of the `IdmController`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiW1ctZ3l5ADxKMrw4Y:b-k5q54q)*

**Comment by liangfok** [comment]
Done. PTAL. Thanks!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiWVldur73VWVuRDu_0:b-fiuzj6)*

**Comment by jadecastro** [comment]
One small comment - PTAL.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 549 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-KinlvRbjQk3ieML4R5h:-KinlvRbjQk3ieML4R5i:b-ns5zen) ([raw file](https://github.com/robotlocomotion/drake/blob/be033fcd21892ba9093d12f1a557b4a00d050777/drake/automotive/test/automotive_simulator_test.cc#L549)):*
> ```cpp
> 
>   const int kAliceIndex{0};
>   const int kBobIndex{17};
> ```

BTW more generally this number is `draw_message.num_links`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-Kio82w0CBIA8Gmbz4ml:bmcopzn)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 549 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-KinlvRbjQk3ieML4R5h:-KiuBqVNKq4OmRuSMiKx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be033fcd21892ba9093d12f1a557b4a00d050777/drake/automotive/test/automotive_simulator_test.cc#L549)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW more generally this number is `draw_message.num_links`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiuBt4wvi4j_CQ1XlzQ:bblnx7i)*

**Comment by jadecastro** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiuJUOFL7QxyDkg0XeX:bnfp4nl)*

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-KiuRkYYneBiCCdpiosd:b-1bcdxl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 192 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-Kiup3YS4kxkgdSeMoCU:-Kiup3YS4kxkgdSeMoCV:bfoh6pi) ([raw file](https://github.com/robotlocomotion/drake/blob/25a9e3f87e35977111f324c654069c12ee978386/drake/automotive/automotive_simulator.cc#L192)):*
> ```cpp
>   const systems::InputPortDescriptor<T>& velocity_port = ports.second;
>   builder_->Connect(railcar->pose_output(), pose_port);
>   builder_->Connect(railcar->velocity_output(), velocity_port);
> ```

Rule of three on brittleness.  Here's my suggestion:

```c++
void AutomotiveSimulator::ConnectCarOutputs(
    const OutputPortDescriptor& pose_output,
    const OutputPortDescriptor& velocity_output) {
  DRAKE_DEMAND(pose_output.get_system() == velocity_output.get_system());
  const System* const system = pose_output.get_system();
  const int id = /* Find `system` in `vehicles_`. */;
  auto ports = aggregator_->AddSinglePoseAndVelocityInput(system->get_name(), id);
  builder_->Connect(system->pose_output(), ports.first);
  builder_->Connect(system->velocity_output(), ports.second);
  car_vis_applicator_->AddCarVis(std::make_unique<PriusVis<T>>(id, name));
}
```

---

*[drake/automotive/test/automotive_simulator_test.cc, line 561 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-KiurEmyGg6Z1RW6EEBv:-KiurEmyGg6Z1RW6EEBw:bvqfdw) ([raw file](https://github.com/robotlocomotion/drake/blob/25a9e3f87e35977111f324c654069c12ee978386/drake/automotive/test/automotive_simulator_test.cc#L561)):*
> ```cpp
>   const int kXIndex{0};
>   EXPECT_GT(draw_message.position[kBobIndex][kXIndex], kPosWithoutVelData);
> }
> ```

FYI This is fine, but it would seem simpler to ExportOutput of the PoseAggregator's PoesBundle and just read out the post-mux values directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 192 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-Kiup3YS4kxkgdSeMoCU:-Kiw0cQTBHKr-BJINZCz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25a9e3f87e35977111f324c654069c12ee978386/drake/automotive/automotive_simulator.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Rule of three on brittleness.  Here's my suggestion:

```c++
void AutomotiveSimulator::ConnectCarOutputs(
    const OutputPortDescriptor& pose_output,
    const OutputPortDescriptor& velocity_output) {
  DRAKE_DEMAND(pose_output.get_system() == velocity_output.get_system());
  const System* const system = pose_output.get_system();
  const int id = /* Find `system` in `vehicles_`. */;
  auto ports = aggregator_->AddSinglePoseAndVelocityInput(system->get_name(), id);
  builder_->Connect(system->pose_output(), ports.first);
  builder_->Connect(system->velocity_output(), ports.second);
  car_vis_applicator_->AddCarVis(std::make_unique<PriusVis<T>>(id, name));
}
```
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 561 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-KiurEmyGg6Z1RW6EEBv:-Kiwqx6L39kq2oUwp-qa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25a9e3f87e35977111f324c654069c12ee978386/drake/automotive/test/automotive_simulator_test.cc#L561)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is fine, but it would seem simpler to ExportOutput of the PoseAggregator's PoesBundle and just read out the post-mux values directly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 530 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-Kj-l_rV_QDbwrNi3N_O:-Kj-l_rWzSQPEgJPQl7I:bp679so) ([raw file](https://github.com/robotlocomotion/drake/blob/e8d88b35dd4a3e5ac2e6d24896d5ff337ea0e2f7/drake/automotive/automotive_simulator.cc#L530)):*
> ```cpp
>   const PoseBundle<T>& pose_bundle =
>       abstract_value->GetValueOrThrow<PoseBundle<T>>();
>   // DRAKE_DEMAND(pose_bundle != nullptr);
> ```

BTW nit Commented code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-:-Kj-lnzEy-eB3CxG0ZZ8:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 530 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5894#-Kj-l_rV_QDbwrNi3N_O:-Kj04MbakJxIVNHGGUIJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e8d88b35dd4a3e5ac2e6d24896d5ff337ea0e2f7/drake/automotive/automotive_simulator.cc#L530)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Commented code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5894)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please.

**Pull request merged**
