### PR TITLE
[systems/framework] Sugar for setting/getting Eigen::VectorX data from DiscreteValues

### PR DESCRIPTION
**Pull request by RussTedrake**
Related to #9171

Removes one level of indirection required in writing a discrete variable update method.  Now one can set/get the Eigen::VectorX directly, without having to use `discrete_values->get_vector()->set_value(...)`, etc. 

Importantly, this also makes it possible to do more things without having to ever think about `BasicVector`.

I've included a second commit applying this sugar throughout the codebase.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15539)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15539#-:-Mg1LfBI1MtbOgGkZfcd:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
A nice improvement! Feature :lgtm:
+@ggould-tri for platform review per rotation, please

> Reviewed 5 of 5 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15539#-:-Mg3CmZr9zJ7huuq9kCf:bnzev7m)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @RussTedrake)

___
*[systems/framework/discrete_values.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg39b-qBpnW5eJee8Bw:-Mg39b-qBpnW5eJee8Bx:b-3l9n94) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L147)):*
> ```objc
>   /// Returns the entire vector for the _only_ group as a mutable
>   /// Eigen::VectorBlock, which allows mutation of the values, but does not
>   /// allow resizing the vector itself.
> ```

nit: to be precise this should say "does not allow `resize()` to be called on the vector". It actually is possible to resize the original Vector (and destroy everything) using the little-known `block.nestedExpression()` method.
___
*[systems/framework/discrete_values.h, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg3AG6cE8xXvy7hxpmR:-Mg3AG6cE8xXvy7hxpmS:bx18be0) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L172)):*
> ```objc
>   /// group.
>   Eigen::VectorBlock<const VectorX<T>> get_value(int index) const {
>     DRAKE_THROW_UNLESS(index >= 0 && index < num_groups());
> ```

BTW more clear IMO to write `0 <= index && index < num_groups()` since that reads more like what we really want, `0 <= index < num_groups()`. Feel free to ignore!
___
*[systems/framework/discrete_values.h, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg3A8w9D29qpVBI7Atz:-Mg3A8w9D29qpVBI7Au-:bme9v6f) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L178)):*
> ```objc
>   /// Returns the entire vector for the indicated group as a mutable
>   /// Eigen::VectorBlock, which allows mutation of the values, but does not
>   /// allow resizing the vector itself.
> ```

nit: see comment above re resize()

**Review by ggould-tri — COMMENTED** [review]
I went back and forth a few times on whether the uses of `auto mumble = thing.get_mutable_value()` violate the spirit of https://drake.mit.edu/styleguide/cppguide.html#Type_deduction .  I have come down on the side of saying this is allowable:
 * The type of the object whose method is being called is not `auto` so a reader can find the documentation, and
 * The code in question is examples or dev directory code; in examples it can be pedagogically useful to elide a type name, and dev code is not subject to these considerations.

However we are sailing quite close to the wind here and should be cautious.  `VectorBlock` has enough pitfalls without readers not even knowing that that's what's being passed around.

:lgtm: 

> Reviewed 5 of 5 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15539#-:-Mg6XGa40eEckKbYi_3x:bxf9qv1)* status: 3 unresolved discussions (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
I hear you @ggould-tri .  I've fixed the one instance that I introduced in this PR, but haven't cleaned up the existing uses of `auto`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15539#-:-Mg81G6yAcpSSbHUES_I:b1crxk5)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @ggould-tri and @sherm1)

___
*[systems/framework/discrete_values.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg39b-qBpnW5eJee8Bw:-Mg8218P8FU2sKSV7bht:b-ryb0vb) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L147)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: to be precise this should say "does not allow `resize()` to be called on the vector". It actually is possible to resize the original Vector (and destroy everything) using the little-known `block.nestedExpression()` method.
</blockquote></details>

Done.  (btw -- i took this language from BasicVector; i'll leave it to you to touch that up if you like!)
___
*[systems/framework/discrete_values.h, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg3AG6cE8xXvy7hxpmR:-Mg82Jyh3rkqGkSv7Whh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L172)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW more clear IMO to write `0 <= index && index < num_groups()` since that reads more like what we really want, `0 <= index < num_groups()`. Feel free to ignore!
</blockquote></details>

Done.
___
*[systems/framework/discrete_values.h, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15539#-Mg3A8w9D29qpVBI7Atz:-Mg82OXxBeucUQT8ajiQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/605822f57a543002ddc27aa351446cf456e474a4/systems/framework/discrete_values.h#L178)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: see comment above re resize()
</blockquote></details>

Done.

**Pull request merged**
