### PR TITLE
Fix 2PI constant in RotaryEncoders

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
... as discovered during transmogrification unit testing (to be PR'd later).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6729)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.
+@sammy-tri for platform review rotation, please.

**Comment by sherm1** [comment]
Any hope for a simple unit test that would have revealed this?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6729#-:-KqQyiaZOvfdxKnudrmc:b-bu1km8)*

**Comment by RussTedrake** [comment]
Lgtm

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6729#-:-KqRvWjQU-Z78GJ6CVU7:bb6zl5l)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6729#-:-KqRve1lvCp7cAqOXTrw:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6729#-:-KqTe4P1iTCxvV_0E4_A:bnfp4nl)*

**Pull request merged**
