### PR TITLE
Fix 9133

### LINKED ISSUE #9133: Remove 'manual' from 'joint_limits_test'
This test was set to 'manual' in #9132 because it was timing out in the mac tsan nightly builds.

This issue is to re-enable the test, which will likely involve breaking it up either in code, or with build system shards.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Attempt to fix #9133

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9170)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Comment by jwnimmer-tri** [comment]
You also need to remove the `"manual"` tag, in order for the test to be run again.  The Jenkins builds above didn't actually test if this got resolved.

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Comment by jwnimmer-tri** [comment]
@amcastro-tri When squashing, please use a meaningful commit message.  Issue numbers are not self-descriptive.

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Pull request merged**
