### PR TITLE
Renames state variable names (difference -> discrete, modal -> abstract)

### PR DESCRIPTION
**Pull request by edrumwri**
(to address issue #4373).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4430)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@liangfok for feature review please (you thumbs up'd the original issue :) and +@ggould-tri for platform review please (inline with regular rotation)

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-:-KYVWxH2gw8U4XI3ngx3:be0nzte)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
Completed first pass of review. Looks good overall. Just a few comments. PTAL.

---

Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZhwK1emg8tforSiO8:-KYZhwK1emg8tforSiO9:b-c3fb9y) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L29)):*
> ```cpp
>   // x[n+1] = x[n]^3
>   void DoEvalDiscreteVariableUpdates(
>       const drake::systems::Context<double> &context,
> ```

The `&` should go next to the data type.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZhryIudZuDtMVeL6L:-KYZhryJH411P4XDYPLD:bv0ot2m) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L30)):*
> ```cpp
>   void DoEvalDiscreteVariableUpdates(
>       const drake::systems::Context<double> &context,
>       drake::systems::DiscreteState<double> *updates) const override {
> ```

The `*` should go next to the data type.

---

*[drake/systems/framework/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZcuQeB7FXcWOMwQ2Q:-KYZcuQeB7FXcWOMwQ2R:b-vbs9nb) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/CMakeLists.txt#L7)):*
> ```CMake
>   context.cc
>   continuous_state.cc
>         discrete_state.cc
> ```

Odd indentation here and below.

---

*[drake/systems/framework/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZczBs18lZzotiybmu:-KYZczBs18lZzotiybmv:b4utaxn) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/CMakeLists.txt#L15)):*
> ```CMake
>   leaf_context.cc
>   leaf_system.cc
>         abstract_state.cc
> ```

Alpha sort here and below.

---

*[drake/systems/framework/leaf_system.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZnnErb-n5UP0Ci3qC:-KYZnnErb-n5UP0Ci3qD:bqgmfvp) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/leaf_system.h#L19)):*
> ```objc
> #include "drake/systems/framework/discrete_state.h"
> #include "drake/systems/framework/leaf_context.h"
> #include "drake/systems/framework/abstract_state.h"
> ```

alpha sort

---

*[drake/systems/framework/parameters.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZnuvpHLvn4OWvSvN3:-KYZnuvqfL-0Z9gK8vY_:bqgmfvp) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/parameters.h#L7)):*
> ```objc
> 
> #include "drake/systems/framework/discrete_state.h"
> #include "drake/systems/framework/abstract_state.h"
> ```

alpha sort

---

*[drake/systems/framework/state.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZeFiVefKsHKgKbSYA:-KYZeFiVefKsHKgKbSYB:b-4h0rp3) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/state.h#L7)):*
> ```objc
> #include "drake/systems/framework/continuous_state.h"
> #include "drake/systems/framework/discrete_state.h"
> #include "drake/systems/framework/abstract_state.h"
> ```

Alpha sort.

---

*[drake/systems/framework/state.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZeMMuIP2RjMmjpP10:-KYZeMMuIP2RjMmjpP11:b-umstgw) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/state.h#L80)):*
> ```objc
>  private:
>   std::unique_ptr<ContinuousState<T>> continuous_state_;
>   std::unique_ptr<DiscreteState<T>> discrete_state_;
> ```

BTW: consider alpha sorting these member variables and also sorting the constructor's initializer list.

---

*[drake/systems/framework/system.h, line 605 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZegoHZb8SKEdShD4y:-KYZegoIZIsx8Iv9XofB:bno6spp) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/system.h#L605)):*
> ```objc
>   /// context later.
>   virtual void DoEvalDiscreteVariableUpdates(
>       const Context<T> &context, DiscreteState<T> *discrete_state) const {}
> ```

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications

---

*[drake/systems/framework/primitives/affine_system.cc, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZodm28DoBbM1lmXzQ:-KYZodm28DoBbM1lmXzR:bkkt46) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/primitives/affine_system.cc#L127)):*
> ```cpp
> template <typename T>
> void AffineSystem<T>::DoEvalDiscreteVariableUpdates(
>     const drake::systems::Context<T> &context,
> ```

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications

(here and below)

---

*[drake/systems/framework/primitives/affine_system.h, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZohM1TTrtE6V4W4qv:-KYZohM1TTrtE6V4W4qw:b1xunu) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/primitives/affine_system.h#L79)):*
> ```objc
>   void DoEvalDiscreteVariableUpdates(
>       const drake::systems::Context<T> &context,
>       drake::systems::DiscreteState<T> *updates) const override;
> ```

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications

(here and above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-:-KYZphJBtXw9_CVjsjKW:bmbwf3o)*

**Comment by ggould-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuHEzKrkvbbUTFYQ6:-KYZuHEzKrkvbbUTFYQ7:b-eh856n) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L46)):*
> ```cpp
> using systems::Diagram;
> using systems::DiagramBuilder;
> using systems::DiscreteState;
> ```

This appears to be unused.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuOOe_QnadLRdl6jo:-KYZuOOe_QnadLRdl6jp:b-eh856n) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L53)):*
> ```cpp
> using systems::RigidBodyPlant;
> using systems::Simulator;
> using systems::SystemOutput;
> ```

This appears to be unused.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuOzOgEShJcNUvk9J:-KYZuOzOgEShJcNUvk9K:b-eh856n) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L54)):*
> ```cpp
> using systems::Simulator;
> using systems::SystemOutput;
> using systems::SystemPortDescriptor;
> ```

This appears to be unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-:-KYZySLe1EKv-Y7esUcx:buvdl6p)*

**Comment by edrumwri** [comment]
Review status: 31 of 38 files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZhwK1emg8tforSiO8:-KY_c_LOJXYsrofjorpE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The `&` should go next to the data type.
</blockquote></details>

Done.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZhryIudZuDtMVeL6L:-KY_c_kVkedwIUqTlWU2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L30)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The `*` should go next to the data type.
</blockquote></details>

Done.

---

*[drake/systems/framework/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZcuQeB7FXcWOMwQ2Q:-KY_cwoBRAG2UM7KZAb3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/CMakeLists.txt#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Odd indentation here and below.
</blockquote></details>

Done.

---

*[drake/systems/framework/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZczBs18lZzotiybmu:-KY_dBTjjfwQbiSlE6oN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/CMakeLists.txt#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Alpha sort here and below.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZnnErb-n5UP0Ci3qC:-KY_dJAFcUJa6a62j9sm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/leaf_system.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

alpha sort
</blockquote></details>

Done.

---

*[drake/systems/framework/parameters.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZnuvpHLvn4OWvSvN3:-KY_dPFV37tdz_eKKa87:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/parameters.h#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

alpha sort
</blockquote></details>

Done.

---

*[drake/systems/framework/state.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZeFiVefKsHKgKbSYA:-KY_dU_DCQpj9nYHthoX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/state.h#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Alpha sort.
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 605 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZegoHZb8SKEdShD4y:-KY_dnvvgN8hGU7yfN8r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/system.h#L605)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/affine_system.cc, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZodm28DoBbM1lmXzQ:-KY_dyx8CqEYOk46MhDs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/primitives/affine_system.cc#L127)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications

(here and below)
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/affine_system.h, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZohM1TTrtE6V4W4qv:-KY_h5sCNBBxFPgEU6dR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/systems/framework/primitives/affine_system.h#L79)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Style guide stipulates that the `&` and `*` go next to the type:

http://drake.mit.edu/code_style_guide.html#clarifications

(here and above)
</blockquote></details>

Done.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuHEzKrkvbbUTFYQ6:-KY_ck46jJaqOMDY57CN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This appears to be unused.
</blockquote></details>

Done.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuOOe_QnadLRdl6jo:-KY_cmrRr3hZeeiUZ-B6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L53)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This appears to be unused.
</blockquote></details>

Done.

---

*[drake/examples/schunk_wsg/schunk_wsg_simulation.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-KYZuOzOgEShJcNUvk9J:-KY_cnP4kI30WYV_RKR9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d038b997f36b2e8587c61818e0505697424e43fb/drake/examples/schunk_wsg/schunk_wsg_simulation.cc#L54)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This appears to be unused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4430)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4430#-:-KY_xxCUliQFv4RaJul5:bnfp4nl)*

**Pull request merged**
