### PR TITLE
Multilane clone from Monolane.

### PR DESCRIPTION
**Pull request by agalbachicar**
As part of #4934, this is the first step towards Multilane implementation. This PR introduces a clone of Monolane. Comments, namespaces, file names, etc. have been change in favor of Multilane.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6639)

### CODE REVIEW

**Comment by agalbachicar** [comment]
@maddog-tri for feature review please.

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kpp9IAiGtfot5aP4XSZ:bh3xfc)*

**Comment by stonier** [comment]
Matt is on holiday this week. @stonier for feature review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-KpptApm9Q3hsp_CVn5_:bam3cp)*

**Comment by stonier** [comment]
+@liangfok for feature review please.
-@maddog-tri 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-KpzuTduVbJFh5RTyoYP:bvyidvb)*

**Comment by liangfok** [comment]
:lgtm:

+@stonier for platform review please.

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-KpzvOV-og95ezliQ0hU:b1unkbm)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq-10SSJqYWMArDeetG:bbx48yi) (no related file):*
What's the plan for merging up fixes to `monolane` into this `multilane` copy?  PRs are going to keep touching `monolane` and there should be some process by which the same fixes are known to (eventually) make it into the `multilane` fork?

One easy answer is to change this PR to be a rename instead of a fork, along with adding a "TODO, no multilane yet", and then there is only one copy, so there is no divergence by definition.

Another answer is that someone is on the hook for periodically taking inventory of changes to monolane and PRing them into multilane.

Another answer is that someone is responsible for reviewing every PR that touches monolane and defecting if the author failed to make the matching fix to multilane.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by agalbachicar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq-W11xB7_6MoN1DuIy:b3t1jx2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What's the plan for merging up fixes to `monolane` into this `multilane` copy?  PRs are going to keep touching `monolane` and there should be some process by which the same fixes are known to (eventually) make it into the `multilane` fork?

One easy answer is to change this PR to be a rename instead of a fork, along with adding a "TODO, no multilane yet", and then there is only one copy, so there is no divergence by definition.

Another answer is that someone is on the hook for periodically taking inventory of changes to monolane and PRing them into multilane.

Another answer is that someone is responsible for reviewing every PR that touches monolane and defecting if the author failed to make the matching fix to multilane.
</blockquote></details>

Given the road map that has been stated in #4934 (and this [comment](https://github.com/RobotLocomotion/drake/issues/4934#issuecomment-315191868)), I would prefer to keep this fork of monolane since it will be deprecated in favor of multilane. We can keep something consistent and functional along the development process that way. Also, I believe that future PRs against monolane should follow the guidelines stated in #4934. I guess that the third option is the one that best fits our needs. We can get notified when there is a new change in monolane and raise our hands if that is against the multilane development.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq0O2ZrmsAn0_sG_Vey:b2xxbi6) (no related file):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

Given the road map that has been stated in #4934 (and this [comment](https://github.com/RobotLocomotion/drake/issues/4934#issuecomment-315191868)), I would prefer to keep this fork of monolane since it will be deprecated in favor of multilane. We can keep something consistent and functional along the development process that way. Also, I believe that future PRs against monolane should follow the guidelines stated in #4934. I guess that the third option is the one that best fits our needs. We can get notified when there is a new change in monolane and raise our hands if that is against the multilane development.
</blockquote></details>

Sure thing.  Next two questions:

(1) I can work on updating reviewable to add a rule "If a PR touches any file in the `monolane` subdirectory, then one of`@foo` or `@bar` people has to review it to confirm the matching change has also been implemented in multilane, marking the PR with a emoji like :monaco: to indicate the check has been completed".  What (who) should the value of foo (bar, etc.) be?  It could be several people, any one of which could mark the emoji in order to unblock the PR.  We will want to ensure we have enough people on-call for this watch to make PR review responsive (business hours M-F).

(2) For PRs that have landed since this PR was opened, is the plan to merge those updates into this PR, or do a follow-up to resync the two copies?  So far, I believe only #6651 needs repeating here, though other PRs may appear before this merges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by agalbachicar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq37gWLtdXumK2ZSvUB:bwyusl6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure thing.  Next two questions:

(1) I can work on updating reviewable to add a rule "If a PR touches any file in the `monolane` subdirectory, then one of`@foo` or `@bar` people has to review it to confirm the matching change has also been implemented in multilane, marking the PR with a emoji like :monaco: to indicate the check has been completed".  What (who) should the value of foo (bar, etc.) be?  It could be several people, any one of which could mark the emoji in order to unblock the PR.  We will want to ensure we have enough people on-call for this watch to make PR review responsive (business hours M-F).

(2) For PRs that have landed since this PR was opened, is the plan to merge those updates into this PR, or do a follow-up to resync the two copies?  So far, I believe only #6651 needs repeating here, though other PRs may appear before this merges.
</blockquote></details>

(1) I can do it (@agalbachicar) and I guess @maddog-tri would like to be part too. Moreover, it will be awesome if you can update  Reviewable rules.

(2) I can get rid of #6651 and any other that doesn't go against $4934 guidelines.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by agalbachicar** [comment]
I have updated this PR with changes introduced in #6651 into Monolane. PTAL.

---

Review status: 28 of 31 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq3JBt1KbzOcjGn54re:b5m4amx)*

**Comment by agalbachicar** [comment]
I guess this is a weird [error](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-open-source/5566/console) on Jenkins and a re-trigger is necessary.

@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please.

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by stonier** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq8ZZWoaw57NTWZwIKI:bnfp4nl)*

**Comment by stonier** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq8hzbnR9hzuYUKtf_9:bg03eir) (no related file):*
<details><summary><i>Previously, agalbachicar (Agustin Alba Chicar) wrote…</i></summary><blockquote>

(1) I can do it (@agalbachicar) and I guess @maddog-tri would like to be part too. Moreover, it will be awesome if you can update  Reviewable rules.

(2) I can get rid of #6651 and any other that doesn't go against $4934 guidelines.  
</blockquote></details>

@jwnimmer-tri do you wish to block on this PR till a reviewable rule is in place?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-Kq-10SSJqYWMArDeetF:-Kq8k57hPJLeFHoz9cer:bpoaz2o) (no related file):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

@jwnimmer-tri do you wish to block on this PR till a reviewable rule is in place?
</blockquote></details>

Nope, I was going to open an issue for it once this PR merges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639)*

**Comment by liangfok** [comment]
+@sherm1 for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq98PPMK9EjGftCLT1y:b-1udnfa)*

**Comment by sherm1** [comment]
This is a 4500 line PR, *way* outside our size limits. I presume there is something special about it that means it doesn't need a line-by-line platform review? If so I need some guidance. Is this merely a straight cloning of monolane, or is there new code that needs reviewing? I saw the discussion about keeping this synced with monolane -- how long do both have to be maintained? That seems very painful and error prone.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq9PnFrStC1-dD-P10G:b-kvlv4c)*

**Comment by agalbachicar** [comment]
Yes, you are right. This PR is longer that the standard but it is monolitic. It just makes a clone of monolane and changes two things:

1.- All the references to monolane by multilane to be consistent with namespaces, file names, comments etc. Consequently a diff should reflect these changes.
2.- Adds the changes introduced in PR #6651 into monolane to this clone. This PR has already been merged so the previous step should not reflect any difference in that sense.

Regarding lifespan of both implementations, once multilane is mature enough (all the intermediate steps described in issue #4934 are completed) the idea is to remove monolane in favor of multilane as @maddog-tri has stated in this [comment](https://github.com/RobotLocomotion/drake/issues/4934#issuecomment-315191868).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq9TcLICMwLT8iH_cmp:bhh91a7)*

**Comment by jwnimmer-tri** [comment]
FYI my 2c: the task for the platform reviewer on this PR is to manually (locally) diff _current master_ of `monolane` with _this PR's_ proposal for the `multilane` folder.  As noted above, they should be purely mechanical and rote (search-replace).

For the record, if the PR was curated in a first commit with the copy, and a second commit with the edits, the platform reviewer could use reviewable to perform the diff.  As it stands, it requires fetching the PR locally and performing a manual recursive diff.

**Comment by sherm1** [comment]
Thanks for the guidance! With a little help from meld and grep, I verified that this code is currently identical to the equivalent monolane code, with the exception of monolane->multilane name changes, and there are no residual "monos" in the multilane code. So, platform :lgtm:.

---

Reviewed 28 of 31 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6639#-:-Kq9wqCxGtUe4mXXCHZg:b5o5bx6)*

**Pull request merged**
