### PR TITLE
Reorganize inverseKinBackend to allow additional solvers

### PR DESCRIPTION
**Pull request by sammy-tri**
Create a wrapped for inverseKinBackend which will eventually allow use of the OptimizationProblem solver interface.  For now, it always delegates to the existing implementation which is coded directly to SNOPT.

Also cleans up some function signatures to match the style guide and fixed some doxygen issues.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2132)

### CODE REVIEW

**Comment by ggould-tri** [comment]
A number of style nits below; no substantive logical issues.

---

Reviewed 19 of 19 files at r1.
Review status: 18 of 19 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/plants/approximateIK.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFojR3T-Kw_GiWdAWeP:-KFojR3UntIUkuTnovBr:-1805232366) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/approximateIK.cpp#L17)):*
As long as you're already messing with `INFO`, how about naming it something more code-conventional than `INFO`?  I notice that it is `info` at the callsite in the next file.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFok5lVvWTsfyFwmmcn:-KFok5lVvWTsfyFwmmco:-1588570716) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.cpp#L17)):*
How very, very Eigen. ¯\_(ツ)_/¯
I guess this usage is conventional, so no defect.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFokd86F_3I5wlsNeJM:-KFokd86F_3I5wlsNeJN:1916694768) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.cpp#L45)):*
Doing the parameter wrapping/whitespace differently on these makes them very hard to compare visually.  I would prefer consistent whitespace here.

---

*[drake/systems/plants/inverseKinBackend.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFol6DU-6cM6vyETQoB:-KFol6DU-6cM6vyETQoC:-332944385) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.h#L13)):*
A documentation comment breadcrumb here would be good -- a lot of grepping for these incomprehensible argument piles will lead back to this file, and at minimum this should direct them to wherever documentation comments for this stuff actually are (RigidBodyIK.h?).

---

*[drake/systems/plants/inverseKinBackend.h, line 39 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFokvniQS_SNJAlZORp:-KFokvnj0L3jsOrsuIHT:1252278461) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.h#L39)):*
Prior comment about `INFO` as parameter name.

---

*[drake/systems/plants/inverseKinPointwise.cpp, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFolQhAMmqHMBnsMU3H:-KFolQhBe77n4lKUSatS:464875547) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinPointwise.cpp#L15)):*
See above comment about `INFO`

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 1030 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFolldiw69ewYUjDvF7:-KFolldiw69ewYUjDvF8:1525967294) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinSnoptBackend.cpp#L1030)):*
indentation inconsistent with two lines earlier

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 2198 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFom124BRQiP4L58sSE:-KFom124BRQiP4L58sSF:-630962453) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinSnoptBackend.cpp#L2198)):*
Inconsistent parameter wrapping makes visual comparison difficult.

---

*[drake/systems/plants/inverseKinTraj.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFom9hUpovjxF9rrJTp:-KFom9hUpovjxF9rrJTq:1884934686) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinTraj.cpp#L18)):*
See above remark about `INFO`.

---

*[drake/systems/plants/RigidBodyIK.h, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFomTmyt2n5lxvkwJ2R:-KFomTmyt2n5lxvkwJ2S:-275945729) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/RigidBodyIK.h#L23)):*
Thank you thank you thank you thank you

---

*[drake/systems/plants/test/testIK.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFonGxagcYZKTsQLVkk:-KFonGxb77Bf2aDRm-6Z:1873338500) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/test/testIK.cpp#L2)):*
unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-:-KFonS7riDKmI3bxdVxd:1746921989)*

**Comment by Lucy-tri** [comment]
Reviewed 17 of 19 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by sammy-tri** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/approximateIK.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFojR3T-Kw_GiWdAWeP:-KFtx2A-1q3jicd05apW:2085332769) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/approximateIK.cpp#L17)):*
INFO (all caps) is consistent with the SNOPT documentation (which also uses lower/mixed case for other variables.  I guess the lower case is the example that's wrong?

I guess this is really a layering violation that SNOPT error codes are being directly returned in this fashion anyway.  If I'm going to take is on, I'll junk INFO entirely.  Think it's worth doing as part of this PR?

---

*[drake/systems/plants/inverseKinBackend.cpp, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFokd86F_3I5wlsNeJM:-KFtzA12dkuBGVhSkWqV:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.cpp#L45)):*
Done.

---

*[drake/systems/plants/inverseKinBackend.h, line 39 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFokvniQS_SNJAlZORp:-KFtzCbAJ88uz-bvlZnG:-1806225806) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinBackend.h#L39)):*
Prior response.

---

*[drake/systems/plants/inverseKinPointwise.cpp, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFolQhAMmqHMBnsMU3H:-KFtzFiYthQ4mJXaraoE:1511772216) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinPointwise.cpp#L15)):*
See above response.

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 1030 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFolldiw69ewYUjDvF7:-KFtzZnH8T5eHoXhP5Co:881554077) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/inverseKinSnoptBackend.cpp#L1030)):*
Done, though emacs really wants it this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by ggould-tri** [comment]
Review status: 15 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/approximateIK.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFojR3T-Kw_GiWdAWeP:-KFu6J5lyY_gZmwyYlDV:-647400399) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/approximateIK.cpp#L17)):*
I'd be happy with a comment saying that `INFO` is per the SNOPT documentation and leaving things otherwise unchanged.

---

*[drake/systems/plants/test/testIK.cpp, line 2 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu6w-_ddw0FMcdPJ3_:-KFu6w-_ddw0FMcdPJ3a:2000600307) ([raw file](https://github.com/robotlocomotion/drake/blob/86e46d47b092bf5b56f75e012a4f1ba2d3ae1f65/drake/systems/plants/test/testIK.cpp#L2)):*
Uh, is this hanging `#` intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by sammy-tri** [comment]
Review status: 15 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/approximateIK.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFojR3T-Kw_GiWdAWeP:-KFuFyVHEX6haQuh9xmp:1940003887) ([raw file](https://github.com/robotlocomotion/drake/blob/80a746bb319bbc247b4a177d18a57b1030dacd3a/drake/systems/plants/approximateIK.cpp#L17)):*
I believe that this is documented in RigidBodyIK.h in the first doxygen comment (for inverseKin())

---

*[drake/systems/plants/test/testIK.cpp, line 2 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu6w-_ddw0FMcdPJ3_:-KFuFkcyscn8LoEELZ7X:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/86e46d47b092bf5b56f75e012a4f1ba2d3ae1f65/drake/systems/plants/test/testIK.cpp#L2)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 15 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-:-KFuYVjU57vNmKHO_zXD:1417088721)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 5 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 50 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu_8csyVd2Igf1U_ih:-KFu_8ctqgOU9MpuZcit:490181691) ([raw file](https://github.com/robotlocomotion/drake/blob/ab29154535ca47e58996a72bf9a124ce930a09ed/drake/systems/plants/inverseKinBackend.cpp#L50)):*
Did you want to add a blank line here also? It looks like you are adding blank lines above functions.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 74 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu_HB_Zee4gGgkQGA1:-KFu_HBb7LK2vKRa65HW:1882536737) ([raw file](https://github.com/robotlocomotion/drake/blob/ab29154535ca47e58996a72bf9a124ce930a09ed/drake/systems/plants/inverseKinBackend.cpp#L74)):*
Add a blank line above this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 50 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu_8csyVd2Igf1U_ih:-KFuetvP7FqNw3sox40U:217661456) ([raw file](https://github.com/robotlocomotion/drake/blob/ab29154535ca47e58996a72bf9a124ce930a09ed/drake/systems/plants/inverseKinBackend.cpp#L50)):*
The block of explicit template instantiations didn't have any blank lines in the original (now inverseKinSnoptBackend.cpp), so I didn't add them here.   I kinda feel like template instantiation is more like a statement than a function, but agreed it's a little odd.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 74 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2132#-KFu_HB_Zee4gGgkQGA1:-KFufAi3t7q4u7Qu16mI:1524178470) ([raw file](https://github.com/robotlocomotion/drake/blob/ab29154535ca47e58996a72bf9a124ce930a09ed/drake/systems/plants/inverseKinBackend.cpp#L74)):*
I think this is the same scenario as above with explicit templates?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2132)*

**Comment by jwnimmer-tri** [comment]
Reviewable and Jenkins are green.  Using override-merge because out-of-date with master.

**Comment by david-german-tri** [comment]
I'm going to create a rollback of this PR to see if it explains #2154 or the cpplint failures in inverseKinSnoptBackend.

**Pull request merged**
