### PR TITLE
Tinyobjloader, take 2

### PR DESCRIPTION
**Pull request by nkoenig**
This is a redo of pull request #3805.

This pull request:

1. Adds tinyobjloader submodule
2. Fixes a few compiler errors that I received when using gcc 5.4.0 on Xenial with gtest.
3. Modifies `Mesh::LoadObjFile` to use tinyobjloader.

Feature reviewer: +@liangfok
Platform reviewer: +@ggould-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4832)

### CODE REVIEW

**Comment by liangfok** [comment]
Completed first pass feature review.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/shapes/geometry.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-Kas9U7le7P-lqAksWXC:-Kas9U7le7P-lqAksWXD:bwb7tlx) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L2)):*
Per style guide, this needs to go after the C++ libraries:

> Use standard order for readability and to avoid hidden dependencies: Related header, C library, C++ library, other libraries' .h, your project's .h.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/multibody/shapes/geometry.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasCAwMo6gj29x0vSVh:-KasCAwMo6gj29x0vSVi:bfma9wq) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L11)):*
> ```cpp
> #include "spruce.hh"
> 
> using std::string;
> ```

BTW, this is not a defect, but it would be great to alpha sort this and the next sections.

---

*[drake/multibody/shapes/geometry.cc, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-Kas9lV3FQ2clITJ746l:-Kas9lV4IiOJIfRgLHk7:b-urbmbg) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L285)):*
> ```cpp
>       obj_file_name.c_str(), path.c_str(), true);
> 
>   // Use the boolean return value, and the error string to determine
> ```

BTW, I think this sentence is easier to read without the comma.

---

*[drake/multibody/shapes/geometry.cc, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasACamtpQmxkSGNGfi:-KasACamtpQmxkSGNGfj:bmjszzl) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L296)):*
> ```cpp
>     vertices->push_back(Vector3d(attrib.vertices[index],
>                                  attrib.vertices[index + 1],
>                                  attrib.vertices[index + 2]));
> ```

BTW, do we need a check prior to this line that `attrib.vertices[index + 1]` and `attrib.vertices[index + 2]` exist? Or, should the termination condition of the `for` loop be `index <= attrib.vertices.size() - 3`?

---

*[drake/multibody/shapes/geometry.cc, line 301 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBU-LbIyq9qjyYzfM:-KasBU-LbIyq9qjyYzfN:b-s4lkxk) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L301)):*
> ```cpp
>   // Iterate over the shapes.
>   for (auto const& shape : shapes) {
>     unsigned int indexOffset = 0;
> ```

Per style guide, `indexOffset` should be `index_offset`.

https://google.github.io/styleguide/cppguide.html#Variable_Names

---

*[drake/multibody/shapes/geometry.cc, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBAUK0MhGGVSnuxqS:-KasB7TNKvWVtX9xrqN_:b3jgjmg) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L306)):*
> ```cpp
>     for (unsigned int face = 0;
>          face < shape.mesh.num_face_vertices.size(); ++face) {
>       auto vertCount = shape.mesh.num_face_vertices[face];
> ```

Per style guide, `vertCount` should be `vertex_count` or `num_vertices`.

https://google.github.io/styleguide/cppguide.html#Variable_Names

---

*[drake/multibody/shapes/geometry.cc, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBM7iocbDCBVyD4Z5:-KasBM7iocbDCBVyD4Z6:b-vjxosf) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L306)):*
> ```cpp
>     for (unsigned int face = 0;
>          face < shape.mesh.num_face_vertices.size(); ++face) {
>       auto vertCount = shape.mesh.num_face_vertices[face];
> ```

BTW, consider making this `const` and spelling out the type instead of using `auto`.

---

*[drake/multibody/shapes/geometry.cc, line 316 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBqpQix8nqXCsOZy6:-KasBqpQix8nqXCsOZy7:ba38s20) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L316)):*
> ```cpp
>       }
> 
>       Vector3i faceIndices;
> ```

Per style guide, `faceIndices` should be `face_indices`.

https://google.github.io/styleguide/cppguide.html#Variable_Names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-:-KasC1_M9WsVNJ3A67eh:bcav7vr)*

**Comment by jwnimmer-tri** [comment]
Review status: 15 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KattnYok6nelGafEzHU:-KattnYpZvc7-TKC-2ob:b-tl8r3i) (no related file):*
Please opt-in to an OS X build before merging.  Ask on slack for the 'bot syntax for that, if its unfamiliar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by jamiesnape** [comment]
Review status: 15 of 16 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmake/packages.cmake, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KawKIHfK_YrUEe4VWJl:-KawKIHfK_YrUEe4VWJm:b37qr38) ([raw file](https://github.com/robotlocomotion/drake/blob/b5aca97b43eb79494571abbba86636c2c01f4e94/cmake/packages.cmake#L139)):*
> ```CMake
>     GTEST_DONT_DEFINE_TEST=1)
>   drake_find_package(GTest MODULE REQUIRED)
>   drake_find_package(tinyobjloader CONFIG REQUIRED)
> ```

Move this below the `set_property` call (which relates to GTest).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by nkoenig** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by nkoenig** [comment]
Review status: 15 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmake/packages.cmake, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KawKIHfK_YrUEe4VWJl:-KbWtfeRvGJgTFlSQLYy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5aca97b43eb79494571abbba86636c2c01f4e94/cmake/packages.cmake#L139)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Move this below the `set_property` call (which relates to GTest).
</blockquote></details>

Done.

---

*[drake/multibody/shapes/geometry.cc, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBAUK0MhGGVSnuxqS:-KbWtcRFypfXlq4VNOee:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L306)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Per style guide, `vertCount` should be `vertex_count` or `num_vertices`.

https://google.github.io/styleguide/cppguide.html#Variable_Names
</blockquote></details>

Done.

---

*[drake/multibody/shapes/geometry.cc, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBM7iocbDCBVyD4Z5:-KbWtdJo8ZXvfXBmjI3S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L306)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider making this `const` and spelling out the type instead of using `auto`.
</blockquote></details>

Done.

---

*[drake/multibody/shapes/geometry.cc, line 316 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KasBqpQix8nqXCsOZy6:-KbWtefDJpe4NbTm3hOy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64149f3fbf5799c3d365d90278bf2b0df8e3a21e/drake/multibody/shapes/geometry.cc#L316)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Per style guide, `faceIndices` should be `face_indices`.

https://google.github.io/styleguide/cppguide.html#Variable_Names
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by jamiesnape** [comment]
Reviewed 14 of 16 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[WORKSPACE, line 98 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-Kbjq_kCzxoAe1s0Z5wc:-Kbjq_kDJxfvMGJEKoWB:bcrl1zq) ([raw file](https://github.com/robotlocomotion/drake/blob/8f2891f4e44d6b451d99d520b68abf19165ead0d/WORKSPACE#L98)):*
> ```
> new_git_repository(
>     name = "tinyobjloader",
>     remote = "https://github.com/syoyo/tinyobjloader.git",
> ```

BTW, should this point to a fork on https://github.com/RobotLocomotion/ to ensure we have full control of the repository for future bisection operations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-:-Kbjr1D_rfUmb2_YgMlP:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[WORKSPACE, line 98 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-Kbjq_kCzxoAe1s0Z5wc:-KbjwTVUn1iTWG3PQyLO:bj6l4sl) ([raw file](https://github.com/robotlocomotion/drake/blob/8f2891f4e44d6b451d99d520b68abf19165ead0d/WORKSPACE#L98)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should this point to a fork on https://github.com/RobotLocomotion/ to ensure we have full control of the repository for future bisection operations?
</blockquote></details>

BTW, upstream has been very receptive to pull requests, so I do not see a reason to fork. It should be a last resort to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[WORKSPACE, line 98 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-Kbjq_kCzxoAe1s0Z5wc:-Kbk1gB43PDyzSSa8Amg:b-jufc4y) ([raw file](https://github.com/robotlocomotion/drake/blob/8f2891f4e44d6b451d99d520b68abf19165ead0d/WORKSPACE#L98)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW, upstream has been very receptive to pull requests, so I do not see a reason to fork. It should be a last resort to do so.
</blockquote></details>

OK. SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@nkoenig I'm curious what happening (or what this plan is) for this PR?

**Comment by nkoenig** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4832#-KattnYok6nelGafEzHU:-KedfTfrQGSYnTME1y80:b-xhpyf1) (no related file):*
> @drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4832)*

**Comment by stonier** [comment]
Superceded by #5631

**Pull request closed without merging**
