### PR TITLE
[primitives] Support sin/cos input features in MultilayerPerceptron.

### PR DESCRIPTION
**Pull request by RussTedrake**
I'm opening this PR for confirmation of the design.  @hongkai-dai -- WDYT?  The backend implementation is very narrow right now, but I tried to keep it behind a public API that I would be happy with looking forward.

If we like it I will cover it with unit tests.

fyi @AlexandreAmice

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.h, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw2ciUYA0YPl5PqaUYv:-Mw2ciUYA0YPl5PqaUYw:bzfz9bs) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.h#L120)):*
> ```objc
>    _each_ non-input layer of the network (including the last layer).
> 
>    `activation_type` should have one less element than `layers`.
> ```

BTW, I think the current documentation could confuse the readers. When we say use_sin_cos_for_input = true, it only means to transform a single scalar theta to two entries (sin(theta), cos(theta)), we don't change theta_dot. So I would suggest to remove mentioning theta_dot in the documentation. We don't have to provide theta_dot as an input to the neural network, and we might also provide other types of input (like xdot/ydot/zdot).



_Code quote:_
```objc

      const std::vector<bool>& use_sin_cos_for_input,
```
___
*[systems/primitives/multilayer_perceptron.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw2dPzJ39RpVfVQUXRv:-Mw2dPzJ39RpVfVQUXRw:b-cl6og8) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.h#L280)):*
> ```objc
>                   internal::CalcLayersData<T>* data) const;
> 
>   void CalcInputFeatures(const Eigen::Ref<const MatrixX<T>>& X,
> ```

Document this function? I think it is better to mention if the input size is batch_size * input_size or input_size * batch_size.
___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3N6GG3F_PTbhQoY33:-Mw3N6GG3F_PTbhQoY34:b-38gph9) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L117)):*
> ```cpp
>     : MultilayerPerceptron<T>(
>           std::vector<bool>(layers[0], false),
>           std::vector<int>(layers.begin() + 1, layers.end()),
> ```

Sorry I think I am confused by this. I thought this `layers` is actually the remaining_layers, since we don't provide the input features, so this should be `layers`, without removing the first entry?
___
*[systems/primitives/multilayer_perceptron.cc, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3Nz478WTOuD8sHcH_:-Mw3Nz478WTOuD8sHcHa:bo6ywo0) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L427)):*
> ```cpp
>         if (has_input_features_) {
>           data.dloss_dInputFeatures.noalias() =
>               GetWeights(context, i).transpose() * data.dloss_dWx_plus_b[i];
> ```

Can we write GetWeights(context, 0) here instead of GetWeights(context, 0)? When I first read this line (because reviewable doesn't show the if (i>0) branch above), I thought we are going to do this matrix product for every layer i.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

___
*[systems/primitives/multilayer_perceptron.h, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw2ciUYA0YPl5PqaUYv:-Mw4mmTE1l0JEb_A0frv:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.h#L120)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I think the current documentation could confuse the readers. When we say use_sin_cos_for_input = true, it only means to transform a single scalar theta to two entries (sin(theta), cos(theta)), we don't change theta_dot. So I would suggest to remove mentioning theta_dot in the documentation. We don't have to provide theta_dot as an input to the neural network, and we might also provide other types of input (like xdot/ydot/zdot).
</blockquote></details>

Done
___
*[systems/primitives/multilayer_perceptron.h, line 280 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw2dPzJ39RpVfVQUXRv:-Mw4nN2H9o6wvjBm1qKS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.h#L280)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document this function? I think it is better to mention if the input size is batch_size * input_size or input_size * batch_size.
</blockquote></details>

Done.
___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3N6GG3F_PTbhQoY33:-Mw3zkj-6OksBo7XUk3v:btpw1fo) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L117)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I think I am confused by this. I thought this `layers` is actually the remaining_layers, since we don't provide the input features, so this should be `layers`, without removing the first entry?
</blockquote></details>

The first element of layers in this constructor is the number of inputs.  But it is delegating to a constructor which takes the inputs and then the remaining layers.  I believe it's correct.
___
*[systems/primitives/multilayer_perceptron.cc, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3Nz478WTOuD8sHcH_:-Mw4-4yb8z-oh8ip7UhZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L427)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we write GetWeights(context, 0) here instead of GetWeights(context, 0)? When I first read this line (because reviewable doesn't show the if (i>0) branch above), I thought we are going to do this matrix product for every layer i.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for Thursday's platform review.

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605#-:-Mw4tlyg0YYyEycANyjK:bg7di0z)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3N6GG3F_PTbhQoY33:-Mw4rNotAxlO7EpGnqex:b-hsemka) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L117)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The first element of layers in this constructor is the number of inputs.  But it is delegating to a constructor which takes the inputs and then the remaining layers.  I believe it's correct.
</blockquote></details>

Ah I see.
___
*[systems/primitives/multilayer_perceptron.cc, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3Nz478WTOuD8sHcH_:-Mw4rVwx1m2SlfVrsZmR:b2k5bz4) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L427)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To be consistent, could you change data.dloss_dWx_plus_b[i] to data.dloss_dWx_plus_b[0] as well?
___
*[systems/primitives/test/multilayer_perceptron_test.cc, line 334 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw4tMKW56OziGvjinp6:-Mw4tMKW56OziGvjinp7:b-gsv73s) ([raw file](https://github.com/robotlocomotion/drake/blob/65e7b11f1be4ea0e6964239a9fa775cc73c0bd31/systems/primitives/test/multilayer_perceptron_test.cc#L334)):*
> ```cpp
> 
> GTEST_TEST(MultilayerPerceptronTest, SinCosFeatures) {
>   MultilayerPerceptron<double> mlp({true, false}, {3, 1},
> ```

nit. Is it OK if we change the first remaining layer to a value different from 3? After the sin/cos transformation, the input features also has size 3, I think it is better to test a different value for the first remaining layer here, to make sure that inside the code we don't  incorrectly use the wrong layer size.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai, @hongkai-dai, and @jwnimmer-tri)

___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3N6GG3F_PTbhQoY33:-Mw6LWI_1JfGaBbrL6R_:bg33s0x) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L117)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ah I see.
</blockquote></details>

(@hongkai -- I'll still  need you to resolve this)
___
*[systems/primitives/multilayer_perceptron.cc, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3Nz478WTOuD8sHcH_:-Mw6Lhde8GgiE3GrpkbS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L427)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

To be consistent, could you change data.dloss_dWx_plus_b[i] to data.dloss_dWx_plus_b[0] as well?
</blockquote></details>

Done.
___
*[systems/primitives/test/multilayer_perceptron_test.cc, line 334 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw4tMKW56OziGvjinp6:-Mw6Lr0x8lH_Os_kR4j0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65e7b11f1be4ea0e6964239a9fa775cc73c0bd31/systems/primitives/test/multilayer_perceptron_test.cc#L334)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit. Is it OK if we change the first remaining layer to a value different from 3? After the sin/cos transformation, the input features also has size 3, I think it is better to test a different value for the first remaining layer here, to make sure that inside the code we don't  incorrectly use the wrong layer size.
</blockquote></details>

Done.

**Comment by RussTedrake** [comment]
___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw3N6GG3F_PTbhQoY33:-Mw6MAuBAfy_NvzdsWNW:b-e3bono) ([raw file](https://github.com/robotlocomotion/drake/blob/d564a03194a93473935bdcfb4f31409fca013733/systems/primitives/multilayer_perceptron.cc#L117)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

(@hongkai -- I'll still  need you to resolve this)
</blockquote></details>

Oops, @hongkai-dai .  @hongkai -- apologies for summoning you here.  My mistake!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605#-:-Mw7gZJQC4aAJg1LkK_K:b-vtj4vo)* status: 10 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7dGOb0GlAZO9hRh2n:-Mw7dGOc07lWrrmOn_I4:bm80w30) (no related file):*
nit I am not a particular fan of `InputFeatures` as a GSG-nonconforming local variable name.  It's jarring when reading the code, trying to remember that it's data instead of a typename.

If you tried a bunch of other alternatives like `input_features` or `F` and found them less readable, then we can stick with the name as-is, but please do your best to see if there is any more readable option available.

---
___
*[systems/primitives/multilayer_perceptron.h, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7TH0V7wYEksfXkVYg:-Mw7TH0V7wYEksfXkVYh:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.h#L107)):*
> ```objc
>    passing `use_sin_cos_for_input = [true, false]`.
> 
>    Note that When this transformation is applied, `num_inputs() != layers()[0]`.
> ```

typo



_Suggestion:_
```objc
when
```
___
*[systems/primitives/multilayer_perceptron.h, line 124 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7es2h5RyAaZfW0bB9:-Mw7es2h5RyAaZfW0bBA:borg7hs) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.h#L124)):*
> ```objc
>   MultilayerPerceptron(
>       const std::vector<bool>& use_sin_cos_for_input,
>       const std::vector<int>& remaining_layers,
> ```

FYI An alternative API design would be to keep `layers` here with the same semantics as the other constructors (rather than `remaining_layers`), but then to have `const std::vector<int>& sin_cos_inputs` which just lists the input _indices_ that should have sin,cos applied instead of a dense list of True/False.

Possibly that would be easier to use, i.e., less of a variation from the other constructors.  I suspect the user will often know those indices first-hand, and is manually mapping them into a list of bools to make this call.

I am fine either way.
___
*[systems/primitives/multilayer_perceptron.h, line 284 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7cjUP0sccVefRNXtx:-Mw7cjUP0sccVefRNXty:b-w5um7v) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.h#L284)):*
> ```objc
>   // `layers()[0]`-by-`N`.
>   void CalcInputFeatures(const Eigen::Ref<const MatrixX<T>>& X,
>                          MatrixX<T>* Features) const;
> ```

nit Everywhere else in the code, we name this "InputFeatures" rather than just "Features".  Are we trying to draw some distinction between this argument vs the places where it's called, that the concept is somehow different in the Calc function vs elsewhere?  I couldn't find the distinction between the two.

I'll assume the variation is unintentional, in which case (and ditto in the cc file definition):



_Suggestion:_
```objc
InputFeatures
```
___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7VupH1ARzk-UYpC5g:-Mw7VupH1ARzk-UYpC5h:b-d2o6ww) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L117)):*
> ```cpp
>     : MultilayerPerceptron<T>(
>           std::vector<bool>(layers[0], false),
>           std::vector<int>(layers.begin() + 1, layers.end()),
> ```

Doing `layers[0]` or `layers.begin() + 1` would be UB if the layers vector were empty.  I think it's important to reject that invalid input directly, instead of segfaulting.

Here's one idea:

```c++
// in namespace anonymous
const std::vector<int>& RejectEmpty(const std::vector<int>& arg) {
  if (arg.empty()) {
    throw std::logic_error("The MultilayerPerceptron's layers constructor argument has too few elements.");
  }
  return arg;
}

// in this constructor
MultilayerPerceptron<T>(
    std::vector<bool>(RejectEmpty(layers)[0], false),
    std::vector<int>(RejectEmpty(layers).begin() + 1, layers.end()),
    // ...
```

It could also serve as `RejectEmpty(layers).size() - 1` in the other constructor above, taking the place of `SubtractFromSize(layers, 1)`.
___
*[systems/primitives/multilayer_perceptron.cc, line 129 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7_kJl1728HqfgsolV:-Mw7_kJm0wT7jkGh4MvP:blyy5vl) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L129)):*
> ```cpp
>       layers_(remaining_layers.size() + 1),
>       activation_types_(activation_types),
>       use_sin_cos_for_input_{use_sin_cos_for_input},
> ```

nit It's a bit jarring to switch between () and {} in the initializer list.



_Suggestion:_
```cpp
(
```
___
*[systems/primitives/multilayer_perceptron.cc, line 134 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7ZF57-Eq32RL8b_PL:-Mw7ZF583LQlL_JScuoz:bd5wz5b) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L134)):*
> ```cpp
>   for (bool use_sin_cos : use_sin_cos_for_input) {
>     if (use_sin_cos) {
>       layers_[0]++;
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement



_Suggestion:_
```cpp
++layers_[0]
```
___
*[systems/primitives/multilayer_perceptron.cc, line 317 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7gF3mB3oadA7Yksfh:-Mw7gF3mB3oadA7Yksfi:bcvec3u) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L317)):*
> ```cpp
>   // Forward pass:
>   if (has_input_features_) {
>     CalcInputFeatures(X, &data.InputFeatures);
> ```

nit Is the math in this branch sufficiently unit tested?  At first glance, I see only a test that this codepath doesn't segfault, not that the desired math is correctly written down.
___
*[systems/primitives/multilayer_perceptron.cc, line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7bO8d1cZxqrdr3Pm8:-Mw7bO8d1cZxqrdr3Pm9:bkt6s5d) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L431)):*
> ```cpp
>             GetWeights(context, i).transpose() * data.dloss_dWx_plus_b[i];
>       } else {
>         if (has_input_features_) {
> ```

nit On L346 above, we didn't add more nesting to the conditionals when dealing with the different situations within the loop.  We should be consistent here as well, I think?



_Suggestion:_
```cpp
      } else if (has_input_features_) {
```
___
*[systems/primitives/multilayer_perceptron.cc, line 443 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7aYfzDJE1l7xL1-tx:-Mw7aYfzDJE1l7xL1-ty:bd4a51q) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L443)):*
> ```cpp
>                       X.row(input_row).array().sin();
>               feature_row += 2;
>               input_row++;
> ```

nit GSG here needs either `++input_row;` or `input_row += 1;`.

https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7dGOb0GlAZO9hRh2n:-MwBnyET9OFgy_Tnunfh:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I am not a particular fan of `InputFeatures` as a GSG-nonconforming local variable name.  It's jarring when reading the code, trying to remember that it's data instead of a typename.

If you tried a bunch of other alternatives like `input_features` or `F` and found them less readable, then we can stick with the name as-is, but please do your best to see if there is any more readable option available.
</blockquote></details>

Done.

---
___
*[systems/primitives/multilayer_perceptron.h, line 124 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7es2h5RyAaZfW0bB9:-MwBofXzEyPOrGnIjVAH:bmqcipb) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.h#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI An alternative API design would be to keep `layers` here with the same semantics as the other constructors (rather than `remaining_layers`), but then to have `const std::vector<int>& sin_cos_inputs` which just lists the input _indices_ that should have sin,cos applied instead of a dense list of True/False.

Possibly that would be easier to use, i.e., less of a variation from the other constructors.  I suspect the user will often know those indices first-hand, and is manually mapping them into a list of bools to make this call.

I am fine either way.
</blockquote></details>

That was my first attempt, but it runs into problems.  When sin_cos_inputs are set, layers[0] != num_inputs.  And I wanted to avoid passing in a value for layers to the constructor and then having this->layers() return a different answer.
___
*[systems/primitives/multilayer_perceptron.h, line 284 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7cjUP0sccVefRNXtx:-MwBpDAGE752MV1phl3S:b-6e0h76) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.h#L284)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Everywhere else in the code, we name this "InputFeatures" rather than just "Features".  Are we trying to draw some distinction between this argument vs the places where it's called, that the concept is somehow different in the Calc function vs elsewhere?  I couldn't find the distinction between the two.

I'll assume the variation is unintentional, in which case (and ditto in the cc file definition):
</blockquote></details>

it was intentional, but only because it felt excessively verbose to say input_features, in CalcInputFeatures (the input is clear).  I've changed it back.
___
*[systems/primitives/multilayer_perceptron.cc, line 117 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7VupH1ARzk-UYpC5g:-MwBqRvqE31frm3Vgx1j:b2aetc9) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Doing `layers[0]` or `layers.begin() + 1` would be UB if the layers vector were empty.  I think it's important to reject that invalid input directly, instead of segfaulting.

Here's one idea:

```c++
// in namespace anonymous
const std::vector<int>& RejectEmpty(const std::vector<int>& arg) {
  if (arg.empty()) {
    throw std::logic_error("The MultilayerPerceptron's layers constructor argument has too few elements.");
  }
  return arg;
}

// in this constructor
MultilayerPerceptron<T>(
    std::vector<bool>(RejectEmpty(layers)[0], false),
    std::vector<int>(RejectEmpty(layers).begin() + 1, layers.end()),
    // ...
```

It could also serve as `RejectEmpty(layers).size() - 1` in the other constructor above, taking the place of `SubtractFromSize(layers, 1)`.
</blockquote></details>

Done.  I should have remembered that one!
___
*[systems/primitives/multilayer_perceptron.cc, line 129 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7_kJl1728HqfgsolV:-MwBpiGrE9DVL0xKUBIq:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It's a bit jarring to switch between () and {} in the initializer list.
</blockquote></details>

done.
___
*[systems/primitives/multilayer_perceptron.cc, line 134 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7ZF57-Eq32RL8b_PL:-MwBpnIw2WacN1HL_JWa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement
</blockquote></details>

Done.
___
*[systems/primitives/multilayer_perceptron.cc, line 317 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7gF3mB3oadA7Yksfh:-MwBxJ-Y80IW6xt16x89:b-1xuog2) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L317)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Is the math in this branch sufficiently unit tested?  At first glance, I see only a test that this codepath doesn't segfault, not that the desired math is correctly written down.
</blockquote></details>

I felt that the math needing coverage was inside CalcInputFeatures, and so was covered.  But I've gone ahead and added the test.
___
*[systems/primitives/multilayer_perceptron.cc, line 431 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16605#-Mw7bO8d1cZxqrdr3Pm8:-MwBrIFQAa9hRzoxxsLa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/721ea9e6a24f64ed4691205b4062705e0f2717eb/systems/primitives/multilayer_perceptron.cc#L431)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit On L346 above, we didn't add more nesting to the conditionals when dealing with the different situations within the loop.  We should be consistent here as well, I think?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16605)* status: needs at least two assigned reviewers (waiting on @RussTedrake)

**Pull request merged**
