### PR TITLE
Split install of source and binary distribution prereqs on Ubuntu

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7857)

### CODE REVIEW

**Comment by jamiesnape** [comment]
The regular install script needs to reference this script rather than duplicate it.

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iKD5UumrdVOkPzJGZ:-L3iKD5UumrdVOkPzJG_:ba3dfmt) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L30)):*
> ```Shell
> # LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
> # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
> # EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> ```

Remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iN-VX0AU0fm_RkJ8N:-L3iN-VX0AU0fm_RkJ8O:by1upnv) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L40)):*
> ```Shell
> 
> apt update -y
> apt install --no-install-recommends -y software-properties-common curl
> ```

`curl` could go in the main block, though quite possibly we switch to `wget` since `install_prereq.sh` uses it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iNYOXZaSBk6W89MBC:-L3iNYOXZaSBk6W89MBD:b-u5bsf5) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L53)):*
> ```Shell
> libboost-all-dev
> libexpat1
> libgflags2v5
> ```

We need headers for this target to work: https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/drake.cps#L90, https://github.com/RobotLocomotion/drake/blob/master/common/text_logging_gflags.h#L7

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iRL3gYSMRbMnR7ZNh:-L3iRL3gYSMRbMnR7ZNi:bujozju) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L76)):*
> ```Shell
> libyaml-cpp0.5v5
> openjdk-8-jre
> pkg-config
> ```

@soonho-tri, according to @m-chaturvedi this is needed only as dependency of `dreal`. Is `pkg-config` actually needed to use `dreal` (the simple presence of `.pc` does not typically induce a dependency on `pkg-config` unless there is some deeper integration).

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iOI5WOeFV0trmUXlO:-L3iOI5WOeFV0trmUXlP:b-jilteh) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L77)):*
> ```Shell
> openjdk-8-jre
> pkg-config
> python-gtk2
> ```

What needs this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iRL3gYSMRbMnR7ZNh:-L3ihVWLoR8BsHJIDvKp:b-plkm0m) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L76)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

@soonho-tri, according to @m-chaturvedi this is needed only as dependency of `dreal`. Is `pkg-config` actually needed to use `dreal` (the simple presence of `.pc` does not typically induce a dependency on `pkg-config` unless there is some deeper integration).
</blockquote></details>

No, it's only a build-dep. shouldn't be a dep in general.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iRL3gYSMRbMnR7ZNh:-L3ihlHU3RsO0XQKr5Ni:b-ecbrww) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L76)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

No, it's only a build-dep. shouldn't be a dep in general.
</blockquote></details>

Does the same apply for `bison` and/or `flex`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iRL3gYSMRbMnR7ZNh:-L3ihrXJoAa-K81etwj6:b-de0iry) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L76)):*
> Does the same apply for bison and/or flex?

Yes.

To generate dreal's `deb` file, I'm using bazel's `pkg_deb` (https://docs.bazel.build/versions/master/be/pkg.html#pkg_deb)  which does not support `Build-Depends` yet. Anyway, I'll fix dreal's deb manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iOI5WOeFV0trmUXlO:-L3itGG5aOyxHvcdB3km:ba3dfob) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L77)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

What needs this?
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iKD5UumrdVOkPzJGZ:-L3itJdZTG5kdJHJUqUP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L30)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iN-VX0AU0fm_RkJ8N:-L3itLgTlDZJlc61e-Bn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L40)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`curl` could go in the main block, though quite possibly we switch to `wget` since `install_prereq.sh` uses it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iNYOXZaSBk6W89MBC:-L3itNfw9J3w4FtZlk5X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L53)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We need headers for this target to work: https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/drake.cps#L90, https://github.com/RobotLocomotion/drake/blob/master/common/text_logging_gflags.h#L7
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
*[setup/ubuntu/16.04/install_prereqs_installed.sh, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L3iRL3gYSMRbMnR7ZNh:-L3itPLM4X_QLVxZprIJ:b-yvs1n3) ([raw file](https://github.com/robotlocomotion/drake/blob/2281610ef594344320eb088e0dc7c3ab45e54ee0/setup/ubuntu/16.04/install_prereqs_installed.sh#L76)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Does the same apply for bison and/or flex?

Yes.

To generate dreal's `deb` file, I'm using bazel's `pkg_deb` (https://docs.bazel.build/versions/master/be/pkg.html#pkg_deb)  which does not support `Build-Depends` yet. Anyway, I'll fix dreal's deb manually.
</blockquote></details>

Removed from `install_prereqs_installed.sh`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
If we are trying to carve out a shell script that users will be asked to run, `install_prereqs_installed.sh` is perhaps not the clearest name, if they don't know the history.

**Comment by jamiesnape** [comment]
> If we are trying to carve out a shell script that users will be asked to run, install_prereqs_installed.sh is perhaps not the clearest name, if they don't know the history.

Perhaps. We can fix that up once we have finished iterating.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-:-L4BWPexSsrLqhr8V1oJ:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
The commit message should be amended to mention that this PR also moves Ubuntu Drake to requiring a PPA -- it's a notable change.

I still disprefer forcing a PPA on users, on the basis of overstepping our bounds of what's reasonable to do to a host OS, but I guess we can live with it for now.  I'll (try to) submit a PR later to move kcov and dreal into the workspace instead, and remove the PPA requirement.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L4BZaXBwFgy-TRlP2SY:-L4BZaXCGu2DrbUl1CqH:bs2pcx7) ([raw file](https://github.com/robotlocomotion/drake/blob/49c42b00c8297d7bc0509b05baa50b579b6bad13/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L24)):*
> ```Shell
> cmake
> coinor-libipopt1v5
> dreal
> ```

With this PR, dreal and ibex have lost deterministic versioning locked to the git commit.

We've allowed for Ubuntu security or point releases to bump system packages outside of the list here (i.e., we treated Ubuntu packages as unversioned), but for things like ibex and dreal that will definitely be meaningfully evolved within the lifetime of Drake's Xenial support, we need to pin their versions in this setup script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-:-L4B_3uJ-nQxpwCVh7hS:b-y21ak7)*

**Comment by jamiesnape** [comment]
We used to "force" a PPA on them for compilers, so personally I think it is reasonable, and we are installing into `/opt`, which is what that directory exists for. Also, you can have as many versions of those packages as you like since we version the directories. I think this is an improvement rather than a defect, to be honest, and my opinion would be installing `.deb`s into the workspace would be a regression.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L4BZaXBwFgy-TRlP2SY:-L4BakD-cII4qSTHJMxK:b-e8hkls) ([raw file](https://github.com/robotlocomotion/drake/blob/49c42b00c8297d7bc0509b05baa50b579b6bad13/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

With this PR, dreal and ibex have lost deterministic versioning locked to the git commit.

We've allowed for Ubuntu security or point releases to bump system packages outside of the list here (i.e., we treated Ubuntu packages as unversioned), but for things like ibex and dreal that will definitely be meaningfully evolved within the lifetime of Drake's Xenial support, we need to pin their versions in this setup script.
</blockquote></details>

I will fix up the script with the `==<version>` for those calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-:-L4Bal3ICvofcbd_-CO7:bew2yjy)*

**Comment by jwnimmer-tri** [comment]
> Also, you can have as many versions of those packages as you like since we version the directories...

For dreal and ibex, we can't install different versions at the same time, because the package names are the same across versions.

**Comment by jamiesnape** [comment]
OK, we will rollback the apt repo part because I don't want this blocked. I will put on record that I consider installing raw `.deb` packages highly defective. `apt` exists for a reason.

**Comment by jwnimmer-tri** [comment]
In case it helps, I didn't intend to imply that this PR should be blocked by using the PPA.  The only blocker I have is the discussion comment about pinning.

**Comment by jwnimmer-tri** [comment]
> I will put on record that I consider installing raw .deb packages highly defective. apt exists for a reason.

I agree we should prefer apt over dpkg, and work to remove raw dpkg calls.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: pending resolution of dreal/ibex version issues.

---

Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-:-L4BoKwPamH705qrUyTK:bi2czrm)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs_binary_distribution.sh, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-L4BZaXBwFgy-TRlP2SY:-L4Bztw2JokkWbGlzNBB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49c42b00c8297d7bc0509b05baa50b579b6bad13/setup/ubuntu/16.04/install_prereqs_binary_distribution.sh#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I will fix up the script with the `==<version>` for those calls.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857#-:-L4C-m6eNmdtzPVFJurR:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7857)*

**Comment by basicNew** [comment]
Just saw that this PR removed gcc from the prereqs install and was wondering: is Drake planning to drop support for gcc? Thanks!

**Comment by jwnimmer-tri** [comment]
We'll always support the OS's default compiler.

**Comment by m-chaturvedi** [comment]
I guess `build-essential` takes care of it? https://packages.ubuntu.com/xenial/build-essential

**Comment by basicNew** [comment]
Got it, thanks

**Pull request merged**
