### PR TITLE
Hotfix for buildcop failure from PR #9766

### PR DESCRIPTION
**Pull request by edrumwri**
Temporarily disables a python test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10245)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
There is no mac build running.  For starters, the bot command was posted on the broken commit, instead of the most recent commit.  Also, the bot command was posted from reviewable, which doesn't work -- you need to post from GitHub comment bot, or use the tiny "post a single comment" reviewable button, not the big green one at top.  Also, macOS builds are slow.  You should just test this PR on macsim and then merge to master.  Otherwise, you won't be in time for the macOS nightlies.

**Comment by sherm1** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by sherm1** [comment]
We are having trouble getting macsim access now. May just have to wait for CI build.

**Comment by soonho-tri** [comment]
I'm running it on my local mac.

**Comment by sherm1** [comment]
Awesome, thanks @soonho-tri !

**Comment by sherm1** [comment]
I'm going to wait a few more minutes to merge to see if other Mac tests are close to completion.

**Comment by jwnimmer-tri** [comment]
I tested in release mode, but can also confirm that master is broken and the PR works:
```console
SimulationMacPro:drake jwnimmer$ git fetch upstream master
SimulationMacPro:drake jwnimmer$ git checkout FETCH_HEAD
...
HEAD is now at 3946f5546 attic: Move RBT inverse_dynamics test_utilities to attic (#10237)
SimulationMacPro:drake jwnimmer$ bazel test --nocache_test_results //bindings/pydrake/systems:py/custom_test
...
FAIL: //bindings/pydrake/systems:py/custom_test (see /private/var/tmp/_bazel_jwnimmer/a587c8d01a07ed3300fa926f67fd6552/execroot/drake/bazel-out/darwin-opt/testlogs/bindings/pydrake/systems/py/custom_test/test.log)
INFO: From Testing //bindings/pydrake/systems:py/custom_test:
==================== Test output for //bindings/pydrake/systems:py/custom_test:
........F.
======================================================================
FAIL: test_leaf_system_overrides (custom_test.TestCustom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bindings/pydrake/systems/test/custom_test.py", line 301, in test_leaf_system_overrides
    simulator.StepTo(0.1)
  File "./bindings/pydrake/systems/test/custom_test.py", line 217, in _DoPublish
    LeafSystem._DoPublish(self, context, events)
  File "./bindings/pydrake/systems/test/custom_test.py", line 265, in _on_periodic
    test.assertFalse(self.called_periodic)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 10 tests in 0.014s

FAILED (failures=1)
================================================================================
Target //bindings/pydrake/systems:py/custom_test up-to-date:
  bazel-bin/bindings/pydrake/systems/py/custom_test
INFO: Elapsed time: 611.956s, Critical Path: 223.98s
INFO: 765 processes: 765 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 1195 total actions
...
SimulationMacPro:drake jwnimmer$ git fetch upstream pull/10245/head && git checkout FETCH_HEAD
HEAD is now at 3e4b1e03e Removed mistakenly committed code.
...
SimulationMacPro:drake jwnimmer$ git merge upstream/master
Already up to date.
SimulationMacPro:drake jwnimmer$ bazel test --nocache_test_results //bindings/pydrake/systems:py/custom_test
...
Target //bindings/pydrake/systems:py/custom_test up-to-date:
  bazel-bin/bindings/pydrake/systems/py/custom_test
INFO: Build completed successfully, 2 total actions
```

**Comment by sherm1** [comment]
Thanks, everyone. I'm going to merge this now and go home.

**Pull request merged**
