### PR TITLE
Fix CI test on quardratic_form_test

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17144)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17144#-:-N1gFb1oEqpAFe5IitT1:ba7uda8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17144#-:-N1gG4u16oq1qA4fOLKM:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
I tested locally that this fixes the problem.  We don't need to wait for the macOS CI to finish, we can merge once enough Ubuntu builds have passed.

**Pull request merged**
