### PR TITLE
Factor {github,bitbucket}_archive into bzl helpers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We can confirm that the selected versions are the same using this:

```sh
cat this-commit.patch |
  egrep '^[+-][^+-].*(sha256|commit)' |
  perl -pe 's|#.*||g; s|^.\s*||g;' |
  sort | uniq -c
```

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7755)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for all review per schedule, please.  Though let me know if you'd like a second pair of eyes assigned.

**Comment by sherm1** [comment]
This is very nice -- much improved over the previous mega-WORKSPACE. I'm assuming you've checked for cut-and-paste-safety with the regex pipeline you showed above; I didn't run it. If so I think one reviewer is plenty for this change. :lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/github.bzl, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7755#-L2h6Bm3B6mtT5UB-pTZ:-L2h6Bm3B6mtT5UB-pT_:b-z2cskv) ([raw file](https://github.com/robotlocomotion/drake/blob/8bbdec2e4713fb362d7b306ae610de092cf5536e/tools/workspace/github.bzl#L5)):*
BTW I read this as "github_archive is a function supporting temporary local repos". But I saw later that it is the macro used for all github externals. Consider starting with something like 
> \# (See doc string below for the normal use of github_archive.) If you
> \# have a need for a temporary local copy of an archive ... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7755#-:-L2h7b7fcWEIuis1-7A-:b-hxs93p)*

**Comment by sherm1** [comment]
P.S. One BTW ...

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7755#-:-L2h8f4YfTEaidRBXR_t:b-dl9ccp)*

**Comment by jwnimmer-tri** [comment]
Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/github.bzl, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7755#-L2h6Bm3B6mtT5UB-pTZ:-L2hBnq0QJOzDNC3o24-:b997utd) ([raw file](https://github.com/robotlocomotion/drake/blob/8bbdec2e4713fb362d7b306ae610de092cf5536e/tools/workspace/github.bzl#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I read this as "github_archive is a function supporting temporary local repos". But I saw later that it is the macro used for all github externals. Consider starting with something like 
> \# (See doc string below for the normal use of github_archive.) If you
> \# have a need for a temporary local copy of an archive ... 
</blockquote></details>

Done.  I decided that in this file the API docs are good enough; I've instead amended the overall workspace README with more details.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7755)*

**Comment by jwnimmer-tri** [comment]
Confirmed that the shell step is reporting success in the latest rebase:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake$ cat this-commit.patch |
>   egrep '^[+-][^+-].*(sha256|commit)' |
>   perl -pe 's|#.*||g; s|^.\s*||g;' |
>   sort | uniq -c
      1 about a checksum mismatch.  Paste the new checksum into the `sha256` argument
      1 commit = "0123456789abcdef0123456789abcdef01234567",
      2 commit = "2.3.1",
      2 commit = "2.86.1",
      2 commit = "3.0.1",
      2 commit = "3.3.3",
      2 commit = "392237e10ba4",
      2 commit = "3aae9224376b5e1a23fd824f19d9501162620b53",
      2 commit = "43048336c34a01156dc216e8534ffb2788675ddf",
      2 commit = "48999b69bde29cdf8d616d4fbd3d6ab1c561027d",
      2 commit = "544c1ded81b926a05b3dedb06504bd17bc8d0a95",
      2 commit = "5677d384315d64c41a9e1dabe6a531f10ffbb7fb",
      2 commit = "87866bd0dbb1f9d5a0f662a6f5caecf469fd42d2",
      2 commit = "8aea7a94d53dea01bfceba5f3cbe8e8cc9fb0244",
      2 commit = "99676541398749c2aab4b5b2c38be77d268085cc",
      2 commit = "b0d633570966e08b8915dee0867747596839d06c",
      2 commit = "bac3dfb42cc7",
      2 commit = "e416b34c132e05487ef8d7fd197f4513d6535c1d",
      2 commit = "f9fb031554d398431bc0efcb511102d41bbed089",
      2 commit = "ignition-rndf_0.1.5",
      2 commit = "release-1.8.0",
      2 commit = "v0.13.0",
      2 commit = "v1.0.6",
      2 commit = "v1.2.6",
      2 commit = "v1.8.1",
      1 different revision, then comment out the `sha256` argument and run `bazel
      1 Removing the `local_repository_override` reverts to using the given `commit`
      1 sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",  
      2 sha256 = "0b97cbaae107e5ddbe89073b6e42b679130f1eb81b913aa93da9e72e032a137b",  
      2 sha256 = "19ee82cd201761954dd833de551edb570e33b320d6027e0d91455faf7cd4c341",  
      2 sha256 = "1e40f4595406e208de8bde66bc3425e6c0dce4ea96254cc2c7e4105316df9a31",  
      2 sha256 = "212211eddd9fa010b4b61a2dae87cd84a66a8b78ed302612d214b7388f9bc198",  
      2 sha256 = "26a534bef07e9e0b7c9bfa4dc0ae0b154e4a5ad8d71a2487f6e33d6e3ca0dadc",  
      2 sha256 = "2ea18adfb608948cab1b5978081dc8c318ed47573ccd66f1603a37fbdbfc56da",  
      2 sha256 = "3b37ef4555d087f7abb6aa59c3b5cecb96410ea10e95a086ef2771569fb6fdfb",  
      2 sha256 = "44068bb91c07c9305213057cad801ae5b689ac1a5f37cd8330dd6e729df8f5b0",  
      2 sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8",  
      2 sha256 = "5f7f46273f36073dc15191fe37dc538b4b23eaeaae63de153abeaa61d1134ad6",  
      2 sha256 = "896fd3edf87c7dfaae378af12d52d233577cc495ae96b5076c48b5b9ca700b4a",  
      2 sha256 = "8b18ef7693e87f1400b9a8bc41f86e3b28259ac98c0b458037232652380aa6af",  
      2 sha256 = "94878cbfa27b0d0fbc64c00d4aafa137f678d5315ae62ba4aecddbd4269ae75f",  
      2 sha256 = "b4bebb43a1257b6e88a5f97c855c0559d6c8a8c0548d3156fc5a28d82bb9533f",  
      2 sha256 = "c058b2e4321ba6adaa656976c1a138c07b18fc03b29f5b82880d5d8228fbf059",  
      2 sha256 = "d798a6ca19165f0a18a43938859359269f5a07fd8e0eb83ab8674739c9e8f361",  
      2 sha256 = "dce62ab75a161dd4353a98364feb166d35e7eea382169d59d9ce842c49c55bad",  
      2 sha256 = "e9fc1ca3fd85648f45c0d2e33591b608a17d8b9b78e22c5f898e831351bacb03",  
      2 sha256 = "f23a143d7865ea4f6cd9aeb2211fe36e20712a39d439cf16fea2b11685f29b61",  
      2 sha256 = "fa1033be146ff51f3b2c679ff160838c1e3ca736c565b19510a5c9b6d352fbaf",  
      2 sha256 = "fa7eec0baaa5f6c57df1a38b064ec3a4f098f477f0a64d97c646a4470ffdd3b6",  
      2 sha256 = "fd0afaf29954c26a725626b7bd24e873e303e84bb62dfcc05162be3f5ae30cd1",  
      2 sha256 = "fd74916b92ed58e77c06097dc18f545462417daa8c96fa8ea2a5c81cd3205917",  
      1 To use a new upstream revision, change the `commit` argument to refer to a
```

---

Review status: 24 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7755#-:-L2hCAV_Ml1-3N9reoCt:brtbd9z)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7755)*

**Comment by jwnimmer-tri** [comment]
The macOS builds passed (the rebase dropped them from the status box):
- https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-bazel-experimental/69/
- https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-cmake-experimental-matlab/29/  (a few minutes remaining, but passing so far)
- https://drake-jenkins.csail.mit.edu/view/Mac%20High%20Sierra/job/mac-highsierra-clang-bazel-experimental-everything/29/
- https://drake-jenkins.csail.mit.edu/view/Mac%20High%20Sierra/job/mac-highsierra-clang-cmake-experimental/18/

**Pull request merged**
