### PR TITLE
[geometry] MeshcatVisualizer can filter geometry via property

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/pull/19210.

This commit takes the hacky version of a prototype patch I'd previously donated to that PR and turns it into a more carefully-spelled change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@trowell-tri and +@SeanCurtis-TRI for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-:-NTKzMyl7XXCxnmpBf59:b2gqxwt)* status: 1 unresolved discussion, LGTM missing from assignees trowell-tri,SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @trowell-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTKzLO7CeKTo4NPNrJC:-NTKzLO7CeKTo4NPNrJD:bj1uxj7) (no related file):*
Working

Needs platform reviewer assigned.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some superficial things.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-:-NTL4eg06Jkf3avb_XCG:b-9vgrih)* status: 4 unresolved discussions, LGTM missing from assignee trowell-tri (waiting on @jwnimmer-tri and @trowell-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL1beKBg5Bs_AyiTpb:-NTL1beKBg5Bs_AyiTpc:b-4b4ee) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L78)):*
BTW The "canonical" way to refer properties is as the property  (meshcat, accepting). (Note: inclusion of double quotes seems more sporadic). Furthermore, I'd go a bit more direct:

> If the GeometryProperies for our `role` has the property (meshcat, accepting), the visualizer will show the geometry if the property's value matches our `prefix`. If the property is absent, the geometry will only be shown if `publish_untagged_geometry` is `true`.
___
*[`geometry/meshcat_visualizer_params.h` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL0ymSAIUN0ssg71vB:-NTL0ymSAIUN0ssg71vC:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L82)):*
> ```objc
>    set on a given geometry, then the visualizer will show that geometry if and
>    only if the property value exactly matches our `prefix`. If such a property
>    has not been set, then this flag determines when happens: when true, the
> ```

nit: typo



_Suggestion:_
```objc
what
```
___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTL2Iu7EIBh4Zc7OEl1:b-oo6b3t) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
> ```objc
>    has not been set, then this flag determines when happens: when true, the
>    geometry will be shown anyway; when false, it will not be shown. */
>   bool publish_untagged_geometry{true};
> ```

BTW You've got two words "accepting" and "tagged" that would benefit from being unified.

While "accepting" matches the rendering property, given the word "tagged" here, the property might be better as (meshcat, tag) or (meshcat, accepting_tag).

Alternatively, this could be: `publish_noaccepting_geometry` -- although that has pretty awful semantics. It doesn't scan well.

Another alternative, (meshcat, whitelist) and `publish_unlisted_geometries`. Or, reverse semantics as `only_whitelisted{false}`.

Unifying the terms so the property and this flag go better together is the ultimate goal, but I'm open to alternate paths for achieving that.

**Review by trowell-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-:-NTLDGEx4eIBUJZxFrM_:bg7igkv)* status: 4 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTLB_Ru8-aXIboKtXMZ:biu9soz) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You've got two words "accepting" and "tagged" that would benefit from being unified.

While "accepting" matches the rendering property, given the word "tagged" here, the property might be better as (meshcat, tag) or (meshcat, accepting_tag).

Alternatively, this could be: `publish_noaccepting_geometry` -- although that has pretty awful semantics. It doesn't scan well.

Another alternative, (meshcat, whitelist) and `publish_unlisted_geometries`. Or, reverse semantics as `only_whitelisted{false}`.

Unifying the terms so the property and this flag go better together is the ultimate goal, but I'm open to alternate paths for achieving that.
</blockquote></details>

BTW fwiw "tag" works well for me, conceptually. If this has already been settled then I am OK with what's currently here, although my eyes aren't fresh w.r.t. this concept.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-:-NTLM8Xe8rdLArWA8ALu:bcpz082)* status: 2 unresolved discussions (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @trowell-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTLJbzC4Yz4_3D6M0MQ:-NTLJbzC4Yz4_3D6M0MR:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/45faeb1d9cf8f718003af8e17134381f6f57b335/geometry/meshcat_visualizer_params.h#L78)):*
> ```objc
>   bool show_hydroelastic{false};
> 
>   /** (Advanced) For a given geometry, if the GeometryProperies for our `role`
> ```

typo



_Suggestion:_
```objc
GeometryProperties
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI and @trowell-tri)

**Review by trowell-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTLnl_-4ffap0JdUip9:bu4u4vn) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... would benefit from being unified.

I took a swing to hopefully bring us closer to the mark.
</blockquote></details>

It doesn't feel any closer. "unspecified destination" and "accepting" doesn't feel any closer than "tagged" and "accepting". But my wish was largely an aesthetic one.

If I had to choose between the former state and the current state, I'd split the distance with `include_untagged_geometry`. It's shorter and "untagged" is no more suggestive than "unspecified destination.".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @SeanCurtis-TRI, @trowell-tri, and @xuchenhan-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTOrvTh5483uNFeuxeP:b-ypua9r) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It doesn't feel any closer. "unspecified destination" and "accepting" doesn't feel any closer than "tagged" and "accepting". But my wish was largely an aesthetic one.

If I had to choose between the former state and the current state, I'd split the distance with `include_untagged_geometry`. It's shorter and "untagged" is no more suggestive than "unspecified destination.".
</blockquote></details>

I tried a different tack.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTP2A8OD81DVtPSZEP5:bgfrg8x) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I tried a different tack.
</blockquote></details>

I think this constitutes a net improvement.

Once I saw this, a couple of thoughts came to mind:

The concept of "default accepting" sounds like it "accepts by default" which isn't quite the semantics. So, maybe we could be more direct.

How about`include_unspecified_accepting`. That is a compact encoding of what is literally in the documentation and the magical property name appears. What gets included? Geometries  that don't have the accepting property specified.  Tada!

However, if you don't want to thrash all of the sites again, I can consider myself content.

**Review by trowell-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTPF79UE4myDmO6CWjJ:b-odwfwm) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think this constitutes a net improvement.

Once I saw this, a couple of thoughts came to mind:

The concept of "default accepting" sounds like it "accepts by default" which isn't quite the semantics. So, maybe we could be more direct.

How about`include_unspecified_accepting`. That is a compact encoding of what is literally in the documentation and the magical property name appears. What gets included? Geometries  that don't have the accepting property specified.  Tada!

However, if you don't want to thrash all of the sites again, I can consider myself content.
</blockquote></details>

BTW I also think this is better.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19220)* status: :shipit: complete! all discussions resolved, LGTM from assignees trowell-tri,SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer_params.h` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19220#-NTL2Iu6DvOgH7uvG-NX:-NTPt1Va6QPRJf-grHA-:bc2wmg0) ([raw file](https://github.com/RobotLocomotion/drake/blob/adecb2a38ac56511ad083d0a91b6749e03f996e3/geometry/meshcat_visualizer_params.h#L84)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

BTW I also think this is better.
</blockquote></details>

You, sir, are a gentleman and a scholar.

**Pull request merged**
