### PR TITLE
[meshcat] Implement Meshcat::PlotSurface()

### PR DESCRIPTION
**Pull request by RussTedrake**
This is a handy plotting helper, providing an interface like matplotlib's plot_surface. I've been using a python version of it for years in my course notes, but now I find myself wanting it in C++.

+@xuchenhan-tri for feature review, please?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done.

I'm on Focal and the PR doesn't build for me, see below.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPYX4ZV57voIxYf01Wt:b-zcvil1)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/meshcat.h` line 302 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYSUWa5hKAfCNtzKjk:-NPYSUWa5hKAfCNtzKjl:bollm9g) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L302)):*
> ```objc
>   method.
> 
>   @param X 2D array of `x` coordinate values.
> ```

I had to read the implementation to understand the semantic of `X`, `Y` and `Z`.

In particular, the variable themselves don't need to be 2D, but rather they need to encode the x,y,z coordinates so that they correspond to vertices of the mesh to be plotted row by row (or column by column) when processed in column-major order.

I think a clarification along that line would be helpful.



_Code quote:_
```objc
 @param X 2D array of `x` coordinate values.
```
___
*[`geometry/meshcat.h` line 303 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYPp5P7doW5eJfQJUT:-NPYPp5P7doW5eJfQJUU:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L303)):*
> ```objc
> 
>   @param X 2D array of `x` coordinate values.
>   @param Y 2D array fo `y` coordinate values.
> ```

typo



_Suggestion:_
```objc
 @param Y 2D array of `y` coordinate values.
```
___
*[`geometry/meshcat.h` line 312 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYWNjH2O8yKSOcxgG-:-NPYWNjH2O8yKSOcxgG0:b-pcrk6w) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L312)):*
> ```objc
>                               regardless of the set value.
> 
>   @pre X,Y, and Z must be the same shape. */
> ```

minor, missing space



_Suggestion:_
```objc
 @pre X, Y, and Z must be the same shape.
```
___
*[`geometry/meshcat.cc` line 2122 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYPE-lDTmDXZa7xt_Y:-NPYPE-m1ZCZKH25HeGT:b-md9eo5) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.cc#L2122)):*
> ```cpp
> 
>   Eigen::Matrix3Xd vertices(3, rows * cols);
>   vertices.row(0) = X.reshaped(1, rows * cols);
> ```

It appears that the "reshaped" function is only introduced in Eigen 3.4, thus causing focal CI failures.
___
*[`geometry/test/meshcat_manual_test.cc` line 183 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYTmjy0o6u7b8-kLrY:-NPYTmjy0o6u7b8-kLrZ:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/test/meshcat_manual_test.cc#L183)):*
> ```cpp
>   - the same purple triangle mesh drawn as a wireframe.
>   - the same triangle mesh drawn in multicolor.
>   - a blue mesh plot of the function y = sin(5*x).
> ```

typo



_Suggestion:_
```cpp
a blue mesh plot of the function z = y*sin(5*x).
```

**Review by RussTedrake — COMMENTED** [review]
Ah.  I was seduced by the better Eigen 3.4 workflow.  Fixed now.

I also addressed a nagging issue about some of our surfaces being rendered from both sides, but not all of them.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPauXiF4SnXYw10yO2k:b-4jh7yo)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`geometry/meshcat.h` line 302 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYSUWa5hKAfCNtzKjk:-NPauV-R25w84iql2CoK:bl8nhr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L302)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I had to read the implementation to understand the semantic of `X`, `Y` and `Z`.

In particular, the variable themselves don't need to be 2D, but rather they need to encode the x,y,z coordinates so that they correspond to vertices of the mesh to be plotted row by row (or column by column) when processed in column-major order.

I think a clarification along that line would be helpful.
</blockquote></details>

Done. I thought it would be clearest with the code snippets.  PTAL.
___
*[`geometry/meshcat.h` line 303 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYPp5P7doW5eJfQJUT:-NPauehH2o3dL6qVaZ7q:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L303)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`geometry/meshcat.h` line 312 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYWNjH2O8yKSOcxgG-:-NPauiOLAaMg8zWNoKv1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.h#L312)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, missing space
</blockquote></details>

Done.
___
*[`geometry/meshcat.cc` line 2122 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYPE-lDTmDXZa7xt_Y:-NPaujw96ZiLM3VYImYF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/meshcat.cc#L2122)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It appears that the "reshaped" function is only introduced in Eigen 3.4, thus causing focal CI failures.
</blockquote></details>

Done.
___
*[`geometry/test/meshcat_manual_test.cc` line 183 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPYTmjy0o6u7b8-kLrY:-NPaumTz2WtMVkD3GD0G:b-pu7a8a) ([raw file](https://github.com/RobotLocomotion/drake/blob/46d3470827a6a2f46c1eda73eb296effe3a46b0c/geometry/test/meshcat_manual_test.cc#L183)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done. :facepalm:

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: pending one CI failure.

FYI, I ran the manual test up until the gamepad test. I don't have the gamepad with me currently.

+@SeanCurtis-TRI for platform review on Monday per rotation please.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPdukRN07hCvEYSodLl:b-tgkqcf)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_test.cc` line 364 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPdqIr53kLug9ohlOpq:-NPdqIr53kLug9ohlOpr:b5gj0ay) ([raw file](https://github.com/RobotLocomotion/drake/blob/08fc4a964513cffea9ce66d3c45d6219afca875d/geometry/test/meshcat_test.cc#L364)):*
> ```cpp
>   constexpr int nx = 15, ny = 11;
>   Eigen::MatrixXd X =
>       Eigen::RowVector<double, nx>::LinSpaced(0, 1).replicate<ny, 1>();
> ```

nit focal CI doesn't like this spelling.

**Review by RussTedrake — COMMENTED** [review]
Thanks @xuchenhan-tri .  Sounds like we need to get you a gamepad and get you on Jammy.  ;-)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPm6NAn4Uug0ZvF3YMF:b-7a583l)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[`geometry/test/meshcat_test.cc` line 364 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPdqIr53kLug9ohlOpq:-NPm7sEF7q4CPgHRxv24:bmfxq1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/08fc4a964513cffea9ce66d3c45d6219afca875d/geometry/test/meshcat_test.cc#L364)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit focal CI doesn't like this spelling.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Like @xuchenhan-tri I had a gamer pad problem -- I'm WFH today but my gamepad is at the office. So, that hasn't been tested, but, otherwise:

:LGTM:

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPse-uKDkos_4x1uJCb:bx39rky)* status: 2 unresolved discussions (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPsW05Q5kVTGZXhnTcr:-NPsW05Q5kVTGZXhnTcs:bxvb24g) (no related file):*
BTW 

When drawing the plot with a wireframe, it might be nice not to introduce triangle artifacts:

So, go from *this*:



to *this*:




If you like that, here's the code:

```c++
void Meshcat::PlotSurface(std::string_view path,
                          const Eigen::Ref<const Eigen::MatrixXd>& X,
                          const Eigen::Ref<const Eigen::MatrixXd>& Y,
                          const Eigen::Ref<const Eigen::MatrixXd>& Z,
                          const Rgba& rgba, bool wireframe,
                          double wireframe_line_width) {
  DRAKE_DEMAND(Y.rows() == X.rows() && Y.cols() == X.cols());
  DRAKE_DEMAND(Z.rows() == X.rows() && Z.cols() == X.cols());
  const int rows = X.rows(), cols = X.cols();

  if (wireframe) {
    int count = -1;
    Eigen::Matrix3Xd vertices(3, rows * cols * 2);
    // Sweep back and forth along rows.
    for (int r = 0; r < rows; ++r) {
      const int c0 = (r & 0x1) ? cols - 1 : 0;
      const int c_delta = (r & 0x1) ? -1 : 1;
      for (int j = 0, c = c0; j < cols; ++j, c += c_delta) {
        vertices.col(++count) << X(r, c), Y(r, c), Z(r, c);
      }
    }
    // Sweep back and forth along columns.
    const int c0 = (rows & 0x1) ? cols - 1 : 0;
    const int c_delta = (rows & 0x1) ? -1 : 1;
    for (int j = 0, c = c0; j < cols; ++j, c += c_delta) {
      const int r0 = (j & 0x1) ? 0 : rows - 1;
      const int r_delta = (j & 0x1) ? 1 : -1;
      for (int i = 0, r = r0; i < rows; ++i, r += r_delta) {
        vertices.col(++count) << X(r, c), Y(r, c), Z(r, c);
      }
    }

    impl().SetLine(path, vertices, wireframe_line_width, rgba);
  } else {
    using MapRowVector = const Eigen::Map<const Eigen::RowVectorXd>;

    Eigen::Matrix3Xd vertices(3, rows * cols);
    vertices.row(0) = MapRowVector(X.data(), rows * cols);
    vertices.row(1) = MapRowVector(Y.data(), rows * cols);
    vertices.row(2) = MapRowVector(Z.data(), rows * cols);

    // Make a regular grid as in https://stackoverflow.com/q/44934631.
    const int num_boxes = (rows - 1) * (cols - 1);
    Eigen::Matrix3Xi faces(3, 2 * num_boxes);
    Eigen::MatrixXi ids(rows, cols);
    // Populate ids with [0, 1, ..., num vertices-1]
    std::iota(ids.data(), ids.data() + rows * cols, 0);

    // Upper left triangles.
    int count = 0;
    for (int i = 0; i < rows - 1; ++i) {
      for (int j = 0; j < cols - 1; ++j) {
        faces.col(count++) << ids(i, j), ids(i + 1, j), ids(i, j + 1);
        faces.col(count++) << ids(i + 1, j), ids(i + 1, j + 1), ids(i, j + 1);
      }
    }

    impl().SetTriangleMesh(path, vertices, faces, rgba, wireframe,
                           wireframe_line_width,
                           SideOfFaceToRender::kDoubleSide);
  }
}
```

___
___
*[`geometry/meshcat.cc` line 2146 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-NPsPEJF2uo6CQcBVhET:-NPsPEJF2uo6CQcBVhEU:b3y5mei) ([raw file](https://github.com/RobotLocomotion/drake/blob/1552b6f3295f5f199b0f5f7cd071b000800b11ec/geometry/meshcat.cc#L2146)):*
> ```cpp
>   // Lower right triangles.
>   for (int i = 0; i < rows - 1; ++i) {
>     for (int j = 0; j < cols - 1; ++j) {
> ```

nit: Two `for` loops truly aren't necessary

```c++
  for (int i = 0; i < rows - 1; ++i) {
    for (int j = 0; j < cols - 1; ++j) {
      // Upper triangle of box.
      faces.col(count++) << ids(i, j), ids(i + 1, j), ids(i, j + 1);
      // Lower triangle of box.
      faces.col(count++) << ids(i + 1, j), ids(i + 1, j + 1), ids(i, j + 1);
    }
  }
```

(Alternatively, see my code snippet above.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Ok, followed up in the office; game pad functionality is still there.

BTW This is actually the first time I did the gamepad functionality. Is anyone else of the opinion that "push a gamepad button in the browser to activate gamepad support" but receive *no feedback* is a bit lacking. Some kind of response from Meshcat that the gamepad is active would be nice.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPwrsDb7YNWrmJg9bUj:b-x0kyng)* status: 2 unresolved discussions (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
> Is anyone else of the opinion that "push a gamepad button in the browser to activate gamepad support" but receive no feedback is a bit lacking. Some kind of response from Meshcat that the gamepad is active would be nice.

My recollection from last time I looked into this is that we could _either_ wait on the gamepad _or_ the terminal's RETURN key, but not both.

We could improve the prompting at the terminal ("Note: there is no visual feedback for the gamepad becoming active.").  Or we could use a Meshcat button for the "continue" in this case, instead of RETURN.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Actually, I was hoping for something *in meshcat GUI* that would indicate that a gamepad is active. But I haven't explored the logic at all to find out how doable that is.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924#-:-NPwxa0030XJFIACKmT7:bjojshe)* status: 2 unresolved discussions (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
Ah, interesting.  Yeah, in the js it should be possible to notice when its active and show a little gamepad icon in the corner or something.  That probably merits a tracking issue reminder, if you're game to write one up.  Or, you could tack it onto #18766 if you like.

**Comment by SeanCurtis-TRI** [comment]
I'll happily add the issue.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18924)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
