### PR TITLE
Run buildifier

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5688)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5688#-:-Kgb-Ub-huuek7UB2VHN:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5688#-:-Kgb08zZ3rQDQXQFuJ6n:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car: :musical_note:

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5688#-:-Kgb2cKX-LPw7BUQHpLr:bnfp4nl)*

**Pull request merged**
