### PR TITLE
Split core/Gradient.h contents into new files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This PR splits `core/Gradient.h` contents into new files.  Code that only relates to `AutoDiff` moves to `math/autodiff.h`; code that relates `AutoDiff` to `Gradient` moves to `math/autodiff_gradient.h`.

The relocated code is unchanged except that:
- a few more things move into `internal` (with call-site changes to match);
- a clang-format pass.

This is the last thing in `drake-distro/drake/core`, so that directory and its build system is also removed here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3121)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@david-german-tri for feature review, please, since you also did #3041.  Low priority.

**Comment by david-german-tri** [comment]
Woohoo!  Another heroic @jwnimmer-tri cleanup. :lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/autodiff.h, line 202 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3121#-KP-RHYVNe4QoF-76WB0:-KP-RHYVNe4QoF-76WB1:b-7nfued) ([raw file](https://github.com/robotlocomotion/drake/blob/a8781ea9db9a94ebc0d050598b486fa1e3641b67/drake/math/autodiff.h#L202)):*
> ```objc
>   }
> };
> }  // namespace internal
> ```

BTW (since I know you dislike these comments) I found this one extremely helpful in Reviewable just now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3121#-:-KP-Q5jnEzWHRWeOZBic:b-8z51qn)*

**Comment by jwnimmer-tri** [comment]
*[drake/math/autodiff.h, line 202 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3121#-KP-RHYVNe4QoF-76WB0:-KP-nIIceuvoZdimrGN3:bjqdzpr) ([raw file](https://github.com/robotlocomotion/drake/blob/a8781ea9db9a94ebc0d050598b486fa1e3641b67/drake/math/autodiff.h#L202)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW (since I know you dislike these comments) I found this one extremely helpful in Reviewable just now.
</details>
FYI I love them in the middle of files (always interesting).  I hate them at the end (always perfunctory and meaningless).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3121)*

**Comment by jwnimmer-tri** [comment]
Over to +@sherm1 for platform review on Monday -- waiting since he did platform on the earlier half of this one.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3121#-:-KP-nVvuBU-hqkMCT1i4:b-hnvs14)*

**Comment by sherm1** [comment]
Platform review: sweet! It's really nice to see `core` vaporized. :lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3121#-:-KP0YQedGdzhXxYaOnak:brdqw7v)*

**Pull request merged**
