### PR TITLE
Add UBSan blacklist file

### PR DESCRIPTION
**Pull request by m-chaturvedi**
May be useful for #8572

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8596)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
@jwnimmer-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUlmVEfGG3hdaoQxU:-LADUlmVEfGG3hdaoQxV:b-tdkk6b) (no related file):*
Needs platform review assigned.

---

*[tools/dynamic_analysis/bazel.rc, line 217 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUM8aAxgarZpHOdeL:-LADUM8aAxgarZpHOdeM:b-mzxwsr) ([raw file](https://github.com/robotlocomotion/drake/blob/80f67d545c5be9d65e5c0277aa4875c6118f9aa1/tools/dynamic_analysis/bazel.rc#L217)):*
> ```
> build:ubsan_everything --copt -O1
> build:ubsan_everything --copt -fno-omit-frame-pointer
> build:ubsan_everything --copt -fsanitize-blacklist=tools/dynamic_analysis/ubsan.blacklist #noqa
> ```

BTW We don't need `# noqa` here, I don't think?  This file isn't linted.  I guess `#noqa` appears in several other places within this file, but those also seem wrong.

---

*[tools/dynamic_analysis/ubsan.blacklist, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUa0TEPfgojDlKKgz:-LADUa0TEPfgojDlKKh-:bn9ryg) ([raw file](https://github.com/robotlocomotion/drake/blob/80f67d545c5be9d65e5c0277aa4875c6118f9aa1/tools/dynamic_analysis/ubsan.blacklist#L1)):*
> ```
> 
> ```

This needs an overview comment (inline, probably) explaining its purpose / how to use it -- doubly so since its a no-op right now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-:-LADUlZc7kwVcb2iBH5o:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
*[tools/dynamic_analysis/ubsan.blacklist, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUa0TEPfgojDlKKgz:-LAE1A3s6h6lH_xyiBhz:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/80f67d545c5be9d65e5c0277aa4875c6118f9aa1/tools/dynamic_analysis/ubsan.blacklist#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This needs an overview comment (inline, probably) explaining its purpose / how to use it -- doubly so since its a no-op right now.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by m-chaturvedi** [comment]
*[tools/dynamic_analysis/bazel.rc, line 217 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUM8aAxgarZpHOdeL:-LAE1Ojs4DyeGHjHWRwn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/80f67d545c5be9d65e5c0277aa4875c6118f9aa1/tools/dynamic_analysis/bazel.rc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW We don't need `# noqa` here, I don't think?  This file isn't linted.  I guess `#noqa` appears in several other places within this file, but those also seem wrong.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by m-chaturvedi** [comment]
*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LADUlmVEfGG3hdaoQxU:-LAE1QseCev_wrc2Pf7u:bvtjo57) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs platform review assigned.
</blockquote></details>

+@ericcousineau-tri for platform review, please.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending some minor discussion items

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/dynamic_analysis/ubsan.blacklist, line 1 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LAEyU8w812FYfjRzmBk:-LAEyU8w812FYfjRzmBl:b-k6ph9g) ([raw file](https://github.com/robotlocomotion/drake/blob/06177207c699c5cf0bb25daa9f1f4e33782169f6/tools/dynamic_analysis/ubsan.blacklist#L1)):*
> ```
> # Blacklist file for UBSan
> ```

Can you add a comment  mentioning that this file is currently a no-op on purpose? (At least, that's my understanding atm.)

---

*[tools/dynamic_analysis/ubsan.blacklist, line 2 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LAEyOuqB-zNGqJo8Y2C:-LAEyOuqB-zNGqJo8Y2D:b-u4f0li) ([raw file](https://github.com/robotlocomotion/drake/blob/06177207c699c5cf0bb25daa9f1f4e33782169f6/tools/dynamic_analysis/ubsan.blacklist#L2)):*
> ```
> # Blacklist file for UBSan
> # http://releases.llvm.org/4.0.1/tools/clang/UndefinedBehaviorSanitizer.html
> ```

Would http://releases.llvm.org/4.0.1/tools/clang/SanitizerSpecialCaseList.html be a better reference for blacklist files?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-:-LAEygI9ARwzb7qTgKk1:b-h4rc1b)*

**Comment by m-chaturvedi** [comment]
*[tools/dynamic_analysis/ubsan.blacklist, line 1 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LAEyU8w812FYfjRzmBk:-LAK7N7hAkgT1ARJYytD:bcj0wmh) ([raw file](https://github.com/robotlocomotion/drake/blob/06177207c699c5cf0bb25daa9f1f4e33782169f6/tools/dynamic_analysis/ubsan.blacklist#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you add a comment  mentioning that this file is currently a no-op on purpose? (At least, that's my understanding atm.)
</blockquote></details>

I am going to make a PR blacklisting a file to resolve https://github.com/RobotLocomotion/drake/issues/8572 next. 
Please let me know if you still want a comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by m-chaturvedi** [comment]
*[tools/dynamic_analysis/ubsan.blacklist, line 2 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LAEyOuqB-zNGqJo8Y2C:-LAK7psr1ToAjYHQYb_7:b29640j) ([raw file](https://github.com/robotlocomotion/drake/blob/06177207c699c5cf0bb25daa9f1f4e33782169f6/tools/dynamic_analysis/ubsan.blacklist#L2)):*
Done. 
For some reason that page doesn't list UBSan, though.
> User of sanitizer tools, such as AddressSanitizer, ThreadSanitizer or MemorySanitizer may want [...]

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/dynamic_analysis/ubsan.blacklist, line 1 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596#-LAEyU8w812FYfjRzmBk:-LAKAvCn45paxxhBNdLo:bgzymu8) ([raw file](https://github.com/robotlocomotion/drake/blob/06177207c699c5cf0bb25daa9f1f4e33782169f6/tools/dynamic_analysis/ubsan.blacklist#L1)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

I am going to make a PR blacklisting a file to resolve https://github.com/RobotLocomotion/drake/issues/8572 next. 
Please let me know if you still want a comment.
</blockquote></details>

OK Nope, that's good!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8596)*

**Pull request merged**
