### PR TITLE
Use DejaVu Sans fonts for Doxygen and pydrake Sphinx documentation

### LINKED ISSUE #10352: Some Unicode characters on Mac do not render properly
Moving over an email thread from a few months back to track this issue. 
/cc @RussTedrake @sherm1 

> There are an appreciable number of unicode subscripts that don't render on the two Macbooks we tested on. These include lower case h, k, l, m, n, p, s, t. We also found that Firefox seems to do a better job at rendering known unicode characters than Safari or Chrome (specifically, there are superscripts that are aligned poorly in Safari/Chrome). We also convinced ourselves that this is a system wide font issue (not just browsers), that affect all text editors we tried (e.g., vim, emacs, TextEdit, and the Mac mail client). My suspicion is that there are probably other rendering issues lurking throughout the documentation when viewed on a Mac.

> The recommendation for Mac users would be:
> 1. Install the Symbola font (font linked [here](https://fontlibrary.org/assets/downloads/symbola/cf81aeb303c13ce765877d31571dc5c7/symbola.zip), taken from [this](https://fontlibrary.org/en/font/symbola) website). This only takes a few seconds.
> 2. Verify the Symbola font is enabled. Do this by running the "Font Book" application (go to spotlight, search for "Font Book" and open it). On the left column, select "User", right click on the "Symbola" font and if "Enable Symbola Family" appears as an option, select it. Otherwise, it was automatically enabled by the installation.
> 3. Restart your web browser
> 4. For best results, use Firefox to browse Drake doxygen

> Here's another surprising data point. On a mac you can invoke the system character map by doing "cntrl+cmd+spacebar". By default, the unicode tables are not listed, but you can add them by clicking on the small gear on the top left of the application, select "Customize List...", scroll down to "Code Tables" and expand the menu, and select "Unicode". On the left panel select the "Unicode" character set, which allows you to see the currently recognized unicode characters.

> If you scroll down to the Unicode set starting at 2070 (Superscripts and Subscripts) you'll see that out of the box Mac doesn't recognized the subscripts I pointed out in my earlier email. After installation of the Symbola font, the subscripts show up. It seems that those unicode characters are just not there to begin with.

> Before installing the Symbola font:
image

> After installing the Symbola font:
image

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #10352. FYI @sherm1.

Note Ubuntu users can optionally use local versions of the fonts via `sudo apt install fonts-dejavu` and Mac users can optionally use local versions via ` brew tap homebrew/cask-fonts && brew cask install font-dejavu-sans`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10628)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@jamiesnape would you like to assign a reviewer?  If not, please apply the "do not review" label for now to make that clear.

**Comment by jamiesnape** [comment]
The one question is whether to add the fonts to the source distribution `source_distribution/install_prereqs.sh`.

**Comment by jamiesnape** [comment]
+@sherm1 for feature review.

**Comment by sherm1** [comment]
Awesome -- thanks, @jamiesnape. I'll try this on an unadulterated Mac.

**Comment by sherm1** [comment]
Status report: @jamiesnape, it took me most of the day to get my virgin Mac updated enough to get Drake able to build doxygen. The Drake installation was still running when I left. So tomorrow's the day!

**Comment by sherm1** [comment]
Finally got my Mac upgraded and tried this. It works! I generated Drake doxygen in master and looked at the class doc for drake::systems::Simulator, which uses many of the forbidden Unicode subscripts. It was a bunch of ugly blocks. Switched to this branch, rebuilt doxygen, then everything looked great. I did get the following warnings from Doxygen though, which did not come out in master:
```
Building C++ Doxygen documentation...
warning: Tag `CLANG_ASSISTED_PARSING' at line 157 of file `/Users/sherm/Documents/GitHub/RobotLocomotion/drake/build/drake/doc/Doxyfile_CXX' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag `CLANG_OPTIONS' at line 158 of file `/Users/sherm/Documents/GitHub/RobotLocomotion/drake/build/drake/doc/Doxyfile_CXX' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
Building C++ Doxygen documentation...
warning: Tag `CLANG_ASSISTED_PARSING' at line 157 of file `/Users/sherm/Documents/GitHub/RobotLocomotion/drake/build/drake/doc/Doxyfile_CXX' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag `CLANG_OPTIONS' at line 158 of file `/Users/sherm/Documents/GitHub/RobotLocomotion/drake/build/drake/doc/Doxyfile_CXX' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.

```

**Comment by sherm1** [comment]
> The one question is whether to add the fonts to `source_distribution/install_prereqs.sh`.

Yes, I think we should do that. The current change is just local to the displayed pages. So while everything looked great in Doxygen, when I pulled up the header file (in vi) from which that Doxygen was generated the comments were still a bunch of blocks rather than proper subscripts. If the font had been installed when I ran install_prereqs, I presume it would have been available for vi also?

**Comment by jamiesnape** [comment]
Depends on your settings in `vi`, but it is possible.

**Comment by jamiesnape** [comment]
> Finally got my Mac upgraded and tried this. It works! I generated Drake doxygen in master and looked at the class doc for drake::systems::Simulator, which uses many of the forbidden Unicode subscripts. It was a bunch of ugly blocks. Switched to this branch, rebuilt doxygen, then everything looked great. I did get the following warnings from Doxygen though, which did not come out in master:

A rebase would fix that.

**Comment by jamiesnape** [comment]
Sphinx (non-Python) documentation is currently not changed. It could do, but does it need to?

**Comment by sherm1** [comment]
Ah, no I don't think we need to change it -- I don't know of any Unicode problems there.

**Comment by sherm1** [comment]
(Rebase did fix the earlier doxygen warning.)

Next, trying to build Python documentation on the Mac, I'm getting this error:
```
clang: error: unknown argument: '-fno-canonical-system-headers'
Target //bindings/pydrake/doc:serve_sphinx failed to build
```
Suggestions?

**Comment by jamiesnape** [comment]
Do not set `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1`.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please

**Comment by sherm1** [comment]
Status: I had no trouble seeing that the C++ doxygen is fixed, but I've given up trying to get the Python documentation built on the Mac. It wants to build all of Drake first and I can't get that to work (not even with Drake master and `bazel build //...`). I've spent two days now installing, hanging during install_prereqs, reinstalling, upgrading, etc. and have gotten an amazing assortment of error messages at different points.

Does anyone else have a Mac that shows ugly Unicode blocks in Python docs currently (look at the documentation for the Simulator class)? If so, can you try @jamiesnape's PR, regenerate the Python docs and see if they turn into beautiful subscripts? @RussTedrake do you still have a Mac without fancy fonts installed?

**Comment by jwnimmer-tri** [comment]
One option is to compile the docs on your workstation, and then copy them to your pristine Mac to view in a browser.  I believe this PR's bugfix is independent of which platform you compile with.

**Comment by jamiesnape** [comment]
> I believe this PR's bugfix is independent of which platform you compile with.

Indeed. Would even work on Windows...

**Comment by jamiesnape** [comment]
> I've spent two days now installing, hanging during install_prereqs, reinstalling, upgrading, etc. and have gotten an amazing assortment of error messages at different points.

Any chance you can create issues for any of these?

**Comment by sherm1** [comment]
> Any chance you can create issues for any of these?

I think I'm on the home stretch now: see issue #10688

**Comment by sherm1** [comment]
I succeeded in building the Python documentation on the Mac in master. Unfortunately(?) all the subscripts in the documentation for systems.analysis.Simulator looked perfect! I suspect that a good font got installed during that process because now even if I look at old C++ doxygen it looks fine.

So my Mac is now corrupted and no longer able to reproduce the problem fixed here. But I did see it work properly for C++ doxygen earlier, and I've verified that the Python docs generated from this branch are good.

**Comment by sherm1** [comment]
(Sorry, hit the wrong button)

**Comment by jamiesnape** [comment]
I am going to kill the expensive rebuild of `mac-high-sierra-unprovisioned-clang-cmake-experimental-release` that the close-reopen triggered, so it will show as failed.

**Pull request merged**
