### PR TITLE
models: Have all models use SDFormat 1.7

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires:

- [x] #13768 Sweeping xmllint application
- [x] #13774 Removal of small things (e.g. remove identity <pose/> elements, empty frame="")
- ~floating-point tuple formatting (remove loading / trailing whitespace)~ Nvm. `libsdformat` doesn't preserve precision atm, so this would still require hand-curation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13758)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Will go ahead and try the "break it down" approach.

**Comment by EricCousineau-TRI** [comment]
Will wait for all builds to complete, tho.

**Comment by jwnimmer-tri** [comment]
IMO if the intent is to merge as curated, then that label needs to be added prior to review, so that the reviewers can also review the details of the curation.

**Comment by EricCousineau-TRI** [comment]
Aye, SGTM!

**Pull request merged**
