### PR TITLE
[multibody] Move ContactResultsToMeshcat into meshcat directory

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
... and rename it to ContactVisualizer for simplicity.

We should not contaminate the MultibodyPlant library with an unconditional dependency on MeshCat.

Relates to #15968 and #16216.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.  Note that there are two curated commits (and plan to merge that way).  The first commit is r_bottom..r1, which makes the move.  The second commit is r1..r3, which backfills the deprecations.  I think it's probably clearest to review them one by one.  When the removal date is reached, we can revert the second commit.

\CC @RussTedrake FYI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437#-:-MuI7FLb6KVULD_pbKzY:bb602ou)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/multibody/_plant_extra.py, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuI7aCl8TRs5kPcyKW0:-MuI7aCl8TRs5kPcyKW1:b-fe84tq) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/bindings/pydrake/multibody/_plant_extra.py#L10)):*
> ```Python
> 
> 
> @_deprecated("Spell as ContactVisualizerParams instead", date="2022-05-01")
> ```

+@EricCousineau-TRI if you are able to offer a review of this file, I'd welcome any feedback.

I have a class in C++ that I've renamed.  I didn't find a good example in the deprecation_example.  This one is also more difficult because the new home for the class is in a _higher layer_ package that depends on the plant, so I need to defer the loading.

**Comment by jwnimmer-tri** [comment]
Actually, per the Thursday schedule, I'll plan on +@EricCousineau-TRI for platform review in any case.  Waiting for feature review to finish first is fine.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 9 of 16 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437#-:-MuIJLCi5m1kTzhbRiG1:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with suggestion to use `ModuleShim` for more "true" aliasing.

> Reviewed 9 of 16 files at r1, 3 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437#-:-MuLu1J2346sgcPh5kY1:b-apfau)* status: 3 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[multibody/plant/contact_results_to_meshcat.h, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuLsAgoBNjgkIbOZ54t:-MuLsAgp9rPSoH30uSxc:bpvct5g) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/multibody/plant/contact_results_to_meshcat.h#L12)):*
> ```objc
> template <typename T>
> using ContactResultsToMeshcat
>     DRAKE_DEPRECATED("2022-05-01", "Spell as ContactVisualizer instead.")
> ```

nit This name could be ambiguous.

Consider qualifying, e.g., `meshact::ContactVisualizer` or `drake::multibody::meshcat::ContactVisualizer`
___
*[multibody/plant/contact_results_to_meshcat_params.h, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuLsRZs9Fe-PP5BoRr2:-MuLsRZt5ueWHeha5CJb:b-j99t8y) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/multibody/plant/contact_results_to_meshcat_params.h#L10)):*
> ```objc
> 
> using ContactResultsToMeshcatParams
>     DRAKE_DEPRECATED("2022-05-01", "Spell as ContactVisualizerParams instead.")
> ```

nit Same as above - may be ambiguous.
___
*[bindings/pydrake/multibody/_plant_extra.py, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuI7aCl8TRs5kPcyKW0:-MuLsdVS16KljBc0oEt5:b-tjnhq) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/bindings/pydrake/multibody/_plant_extra.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

+@EricCousineau-TRI if you are able to offer a review of this file, I'd welcome any feedback.

I have a class in C++ that I've renamed.  I didn't find a good example in the deprecation_example.  This one is also more difficult because the new home for the class is in a _higher layer_ package that depends on the plant, so I need to defer the loading.
</blockquote></details>

For items like this, it may be best to use `ModuleShim` so you can intercept the import name.
#15409 provides an example of using it.

There, you can intercept `ContactResultsToMeshcat` and `ContactResultsToMeshcat_`, and do a deferred import.

That way, you can pass in the aliased *type*, so `isinstance(ContactResultsToMeshcat, type)` is true
in this case, it is not true since you're mocking a type and `cpp_template` using a function

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/multibody/_plant_extra.py, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuI7aCl8TRs5kPcyKW0:-MuM4WHsARp4t7rGHSqQ:bhurm79) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/bindings/pydrake/multibody/_plant_extra.py#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For items like this, it may be best to use `ModuleShim` so you can intercept the import name.
#15409 provides an example of using it.

There, you can intercept `ContactResultsToMeshcat` and `ContactResultsToMeshcat_`, and do a deferred import.

That way, you can pass in the aliased *type*, so `isinstance(ContactResultsToMeshcat, type)` is true
in this case, it is not true since you're mocking a type and `cpp_template` using a function
</blockquote></details>

Thanks for the pointer, I looked it over.  It seems like it requires a large, non-local disruption to the gross module structure.  To me, that doesn't seem worthwhile for solving only the `isinstance` use case on a recently-introduced, rarely-used system.

The other option I considered was to just keep the C++ bindings for the old name in place (adding deprecation markers).  That would duplicate the object code, but would be more straightforward.

Any votes?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

___
*[bindings/pydrake/multibody/_plant_extra.py, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuI7aCl8TRs5kPcyKW0:-MuM5R_f8iZeUSeciGUo:b-78vgsu) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/bindings/pydrake/multibody/_plant_extra.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Thanks for the pointer, I looked it over.  It seems like it requires a large, non-local disruption to the gross module structure.  To me, that doesn't seem worthwhile for solving only the `isinstance` use case on a recently-introduced, rarely-used system.

The other option I considered was to just keep the C++ bindings for the old name in place (adding deprecation markers).  That would duplicate the object code, but would be more straightforward.

Any votes?
</blockquote></details>

My prefs are "what you have now" > :module shim" > "duplicating code"

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform), base commit is latest master (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/_plant_extra.py, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16437#-MuI7aCl8TRs5kPcyKW0:-MuM6vng3f-8jB0JSos1:bx1qqag) ([raw file](https://github.com/robotlocomotion/drake/blob/032884ba0aa903d82972661f5c3be022ec286d35/bindings/pydrake/multibody/_plant_extra.py#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My prefs are "what you have now" > :module shim" > "duplicating code"
</blockquote></details>

OK I'll do +(release notes: breaking change) so that we can properly document the inheritance change and call it good enough.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16437)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform), base commit is latest master (waiting on @jwnimmer-tri)

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/multibody/_plant_extra.py, line 19 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16437#-Mu_mw4UAo1NKPDWwiis:-Mu_mw4UAo1NKPDWwiit:b-htxlgu) ([raw file](https://github.com/robotlocomotion/drake/blob/8b96d899578e5d7f2059e9a991ecc9e4b1a393ea/bindings/pydrake/multibody/_plant_extra.py#L19)):*
> ```Python
> def ContactResultsToMeshcat(T=float, *args, **kwargs):
>     from pydrake.multibody.meshcat import ContactVisualizer_ as real
>     return real[T](*args, **kwargs)
> ```

This deprecation was not sufficient.  The most common use case broke hard in all of my notebooks:
```
    contact_vis = ContactResultsToMeshcat.AddToBuilder(
AttributeError: 'function' object has no attribute 'AddToBuilder'
```

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2283 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16437#-Mu_o8_a5M2fp34Bp2Jj:-Mu_o8_a5M2fp34Bp2Jk:bobjqp3) ([raw file](https://github.com/robotlocomotion/drake/blob/8b96d899578e5d7f2059e9a991ecc9e4b1a393ea/bindings/pydrake/multibody/test/plant_test.py#L2283)):*
> ```Python
>         self.assertIsNotNone(params)
>         with catch_drake_warnings(expected_count=1):
>             vis = ContactResultsToMeshcat_[T](meshcat=meshcat, params=params)
> ```

this deprecation test coverage was obviously insufficient, too.

**Pull request merged**
