### PR TITLE
Adds an SDF That Defines A World With Two iiwa Robots Ready for Bimanual Manipulation Task

### PR DESCRIPTION
**Pull request by liangfok**
# How to Load The SDF Into Gazebo

```
$ cd drake-distro/drake/examples/kuka_iiwa_arm/models
$ gazebo dual_iiwa_manipulators/dual_iiwa_manipulators.sdf --pause
```

# What You Should See
Here's what the model looks like when loaded into Gazebo:

screenshot from 2017-02-27 09-37-53

Notice the individual models on the left panel in the GUI.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5332)

### CODE REVIEW

**Comment by naveenoid** [comment]
Maybe a passive demo can be added within the iiwa_world folder? It should only be few lines..alternately, I can add one as a followup PR..BTW A passive demo naturally allows specifying a unit test for the consistency of a model (if it loads, the model is valid)..

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5332#-:-Ke-4QMdhKZe_Ilxlov4:b-visfou)*

**Comment by liangfok** [comment]
Yes, I agree it should only be a few lines of code if we programmatically initialize the demo by calling the SDF parser multiple times (as we've been doing). What this PR shows is how to specify a world containing multiple models in a single SDF file. Note how this one SDF file includes other SDF and URDF files. Once Drake supports this capability, we can initialize a `RigidBodyTree` (soon to be `MultiBodyTree`) using a single call the SDF parser.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5332#-:-Ke-6NgaT7WdRfiuRbdx:b81fh98)*

**Comment by naveenoid** [comment]
I havent tried loading this model into gazebo on my machine, but otherwise :lgtm:

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5332#-:-Ke-9k2Fq7GSQqLReJin:b-xeqkag)*

**Comment by liangfok** [comment]
Thanks :smile:. Unfortunately, this PR is blocked on #5317 before it can be reviewed / merged.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5332#-:-Ke-BaMwteSYDN-dRL32:be9ptxn)*

**Comment by liangfok** [comment]
I'm going to close this PR since it's going to take more work to update Drake's SDF parser to allow the inclusion of other SDF and URDF files. Perhaps this PR can, at best, provide an example of the inclusion syntax.

**Pull request closed without merging**
