### PR TITLE
Add StateVectorInterface::CopyToVector.

### PR DESCRIPTION
**Pull request by david-german-tri**
@sherm1 for feature and platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2515)

### CODE REVIEW

**Comment by david-german-tri** [comment]
This is a small PR and would be useful to other stuff both you and I have pending.

**Comment by sherm1** [comment]
Feature: :lgtm: with a few minor comments.
Platform: waiting for ci.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This is a small PR and would be useful to other stuff both you and I have pending.
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/state_vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgs2raePchLskhhi3_:-KJgs2raePchLskhhi3a:1833141773) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L45)):*
> ```objc
>   /// Implementations should ensure this operation is O(N) in the size of the
>   /// value and allocates no memory.
>   virtual void SetFromVector(const Eigen::Ref<VectorX<T>>& value) = 0;
> ```

For symmetry, this might now be better named `CopyFromVector`.

---

*[drake/systems/framework/state_vector_interface.h, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgshjx0_QOjOhQiKY7:-KJgsHRHUWcUewB4OXjz:-1819248714) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L46)):*
> ```objc
>   /// value and allocates no memory.
>   virtual void SetFromVector(const Eigen::Ref<VectorX<T>>& value) = 0;
> ```

BTW, that `Eigen::Ref` trick here did not work for me for expression types. I suggest a TODO here to revisit this.

---

*[drake/systems/framework/state_vector_interface.h, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgrtTV8gjh5ti9D8ty:-KJgrtTV8gjh5ti9D8tz:236876942) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L47)):*
> ```objc
>   virtual void SetFromVector(const Eigen::Ref<VectorX<T>>& value) = 0;
> 
>   /// Copies the entire state to a no-semantics vector.
> ```

Should specify O(N) time to match earlier methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-:-KJgtjoIdlkAewunUJwa:-1859481210)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/state_vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgs2raePchLskhhi3_:-KJgyxiuu-vVX_Enc7nI:1567678786) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> For symmetry, this might now be better named `CopyFromVector`.
</details>
I don't think so.  To my ear, `Copy` implies allocating new memory.

---

*[drake/systems/framework/state_vector_interface.h, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgrtTV8gjh5ti9D8ty:-KJgyvGoYQGdzc4wVbDD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should specify O(N) time to match earlier methods.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515)*

**Comment by liangfok** [comment]
just left some minor comments :lgtm: 

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Feature: :lgtm: with a few minor comments.
> Platform: waiting for ci.
</details>


---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/basic_state_vector.h, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh2g-MgsEqbKzZFhva:-KJh2g-MgsEqbKzZFhvb:-381955697) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L13)):*
> ```objc
> 
> /// BasicStateVector is a concrete class template that implements
> /// StateVectorInterface in a convenient manner for leaf Systems,
> ```

BTW, should "leave Systems" be "Systems that have no component systems"?

---

*[drake/systems/framework/basic_state_vector.h, line 28 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1l2kQOy0n_q5TT6C:-KJh1l2kQOy0n_q5TT6D:-1758309289) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L28)):*
> ```objc
>     if (index >= size()) {
>       throw std::out_of_range("Index " + std::to_string(index) +
>                               "out of bounds for state vector of size " +
> ```

BTW I think there is a space missing in front of "out".

---

*[drake/systems/framework/basic_state_vector.h, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1sojT_aRHAYXRF9W:-KJh1sojT_aRHAYXRF9X:-1758309289) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L37)):*
> ```objc
>     if (index >= size()) {
>       throw std::out_of_range("Index " + std::to_string(index) +
>                               "out of bounds for state vector of size " +
> ```

BTW I think there is a space missing in front of "out".

---

*[drake/systems/framework/basic_state_vector.h, line 47 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1zWE6Ak0ZsUDE8v-:-KJh1zWE6Ak0ZsUDE8v0:-385862112) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L47)):*
> ```objc
>   }
> 
>   VectorX<T> CopyToVector() override {
> ```

BTW couldn't this result in a dual-copy operation if the callee saves it to a local `VectorX<T>`? Why not take as a pointer to `VectorX<t>` as a parameter that this method saves `vector_->get_value()` to?

---

*[drake/systems/framework/state_subvector.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh2QUsUm3M86MDhWso:-KJh2QUsUm3M86MDhWsp:-1965804781) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/state_subvector.h#L72)):*
> ```objc
>   }
> 
>   VectorX<T> CopyToVector() override {
> ```

Same comment here about the potential for a double-copy if callee saves the return value to a local variable of type `VectorX<T>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-:-KJh342e8lGlsQklpvR5:-1697145387)*

**Comment by sherm1** [comment]
Liang found a couple of error message formatting problems.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> just left some minor comments :lgtm: 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/basic_state_vector.h, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh2g-MgsEqbKzZFhva:-KJhDJ4n5yyGdta_OHN-:-1327108035) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should "leave Systems" be "Systems that have no component systems"?
</details>
Liang, we battled long and hard to get "leaf Systems" into the lexicon! We're definitely keeping it. Might be courteous to add a parenthetical definition afterwards though, and yours seems right. (Although clearly you understood the term "leaf System"!)

---

*[drake/systems/framework/basic_state_vector.h, line 28 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1l2kQOy0n_q5TT6C:-KJhDhxzr_kO-8-7in6t:-502048313) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW I think there is a space missing in front of "out".
</details>
These shouldn't be "BTW"s, Liang -- that's a bug!

---

*[drake/systems/framework/basic_state_vector.h, line 47 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1zWE6Ak0ZsUDE8v-:-KJhB77eTx0vltQl-eIC:614654130) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L47)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW couldn't this result in a dual-copy operation if the callee saves it to a local `VectorX<T>`? Why not take as a pointer to `VectorX<t>` as a parameter that this method saves `vector_->get_value()` to?
</details>
No. C++11 [copy elision](http://en.cppreference.com/w/cpp/language/copy_elision) makes this work perfectly and eliminates the former need for parameter list contortions and associated ugliness.

---

*[drake/systems/framework/state_subvector.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh2QUsUm3M86MDhWso:-KJhBbK97Rh_Hyk_AHmV:80060833) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/state_subvector.h#L72)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Same comment here about the potential for a double-copy if callee saves the return value to a local variable of type `VectorX<T>`.
</details>
Nope. No problem.

---

*[drake/systems/framework/state_vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJgs2raePchLskhhi3_:-KJhBh70NZHsaT0SivLf:787323803) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd3105826f28a8b6a9e5f7d08a4ad7bb8e45c94/drake/systems/framework/state_vector_interface.h#L45)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I don't think so.  To my ear, `Copy` implies allocating new memory.
</details>
I see. SetFromVector() works only on the existing memory, but CopyToVector() might allocate new memory. OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-:-KJhE0MfY191tkC5T-xU:23918014)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/basic_state_vector.h, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh2g-MgsEqbKzZFhva:-KJhFTsb6TptGAuT5Jtv:1882424191) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Liang, we battled long and hard to get "leaf Systems" into the lexicon! We're definitely keeping it. Might be courteous to add a parenthetical definition afterwards though, and yours seems right. (Although clearly you understood the term "leaf System"!)
</details>
Oh, in this case, the comment below should be updated.

---

*[drake/systems/framework/state_vector_interface.h, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJhFd8WnF7PZz_fUjjS:-KJhFd8WnF7PZz_fUjjT:1054130158) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/state_vector_interface.h#L12)):*
> ```objc
> /// StateVectorInterface is an interface template for vector quantities within
> /// the state of a System.  Both composite Systems (Diagrams) and Systems that
> /// have no component systems have state that satisfies StateVectorInterface.
> ```

BTW, should "Systems that have o component systems" be "leaf systems"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/basic_state_vector.h, line 28 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1l2kQOy0n_q5TT6C:-KJkiD-3QnaItf3h0xvN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These shouldn't be "BTW"s, Liang -- that's a bug!
</details>
Done.

---

*[drake/systems/framework/basic_state_vector.h, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJh1sojT_aRHAYXRF9W:-KJkiFRQXl-PRndsoqkz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/basic_state_vector.h#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW I think there is a space missing in front of "out".
</details>
Done.

---

*[drake/systems/framework/state_vector_interface.h, line 12 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2515#-KJhFd8WnF7PZz_fUjjS:-KJkiPf66JWAtm2ep-GS:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc47858b7a32aa2dc622cf35bb6180a211d655de/drake/systems/framework/state_vector_interface.h#L12)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should "Systems that have o component systems" be "leaf systems"?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515)*

**Comment by liangfok** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2515)*

**Comment by david-german-tri** [comment]
jenkins: retest this please

(seems wedged for some reason)

**Comment by david-german-tri** [comment]
@drake-jenkins-bot: retest this please

**Comment by david-german-tri** [comment]
I'm going to merge this despite the win32 network flake since it passed on win64 (and everywhere else).

**Pull request merged**
