### PR TITLE
Only retrieve Mosek dual solution when there is no integer variables.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #14336

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-bionic-clang-bazel-continuous-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-continuous-everything-debug please

**Review by hongkai-dai — COMMENTED** [review]
+@betsymcphail for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338#-:-MMHEpgH61UCEyormC1B:by2kq0g)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338#-:-MMHPqHeDo8gkqKJfKse:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by BetsyMcPhail — COMMENTED** [review]
+@seancurtis-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338#-:-MMHR-EcCBYV1Z5JevnN:b-uqsdyx)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one quick question about the formulation of the test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338#-:-MMHtlGS9xEnjzt-JWHC:b-g0u3zm)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),BetsyMcPhail

___
*[solvers/mosek_solver.cc, line 1438 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14338#-MMHtEp_63Vqi3LWXmtd:-MMHtEp_63Vqi3LWXmte:b1vhtvn) ([raw file](https://github.com/robotlocomotion/drake/blob/3a29bcc1e0299f22787fbbc663177bf379892c8b/solvers/mosek_solver.cc#L1438)):*
> ```cpp
>   // constraint, second order cone constraint, etc.
>   MSKrescodee rescode{MSK_RES_OK};
>   if (which_sol == MSK_SOL_BAS || which_sol == MSK_SOL_ITR) {
> ```

BTW What's the reasoning for phrasing the test like this instead of:

```c++
if (which_sol != MSK_SOL_ITG) {
```

As is, it's difficult to connect the test to the comment (after all, `MSK_SOL_ITG` doesn't appear anywhere in the test. In the current configuration of mosek, they *seem* to be equivalent. So, is there a reason to explicitly enumerate the set `NOT {MSK_SOL_ITG}` instead of just declaring it as such? If so, could you provide that justification here in the comment?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail)

___
*[solvers/mosek_solver.cc, line 1438 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14338#-MMHtEp_63Vqi3LWXmtd:-MMHwUaf8JB2ZByASH3e:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/3a29bcc1e0299f22787fbbc663177bf379892c8b/solvers/mosek_solver.cc#L1438)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW What's the reasoning for phrasing the test like this instead of:

```c++
if (which_sol != MSK_SOL_ITG) {
```

As is, it's difficult to connect the test to the comment (after all, `MSK_SOL_ITG` doesn't appear anywhere in the test. In the current configuration of mosek, they *seem* to be equivalent. So, is there a reason to explicitly enumerate the set `NOT {MSK_SOL_ITG}` instead of just declaring it as such? If so, could you provide that justification here in the comment?

</blockquote></details>

Done, good call.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14338)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),BetsyMcPhail

**Pull request merged**
