### PR TITLE
Remove unused MATLAB-only external dependencies

### PR DESCRIPTION
**Pull request by jamiesnape**
Depends in part on #6369. Relates to #6369. Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6439)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
We'll do +@RussTedrake feature review to confirm nothing here needs to stay.

:lgtm: platform from me.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/CMakeLists.txt, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-Knfus2PlO3ao-kNqQ0D:-Knfus2PlO3ao-kNqQ0E:b-v172nr) ([raw file](https://github.com/robotlocomotion/drake/blob/a7ca4ef88064e64acf8de2f2d26bdce28782c871/drake/matlab/util/CMakeLists.txt#L85)):*
> ```CMake
> endif()
> 
> # Mex debugging tools:
> ```

This seemed plausibly useful still?  Or is it going to stop working.  Might want to ping Russ if he still wants it.

---

*[drake/matlab/util/CMakeLists.txt, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-KnfukuGvXWc0Dn-zmyj:-KnfukuHsMkBh0PbVL5S:bvmu9ti) ([raw file](https://github.com/robotlocomotion/drake/blob/a7ca4ef88064e64acf8de2f2d26bdce28782c871/drake/matlab/util/CMakeLists.txt#L87)):*
> ```CMake
> # Mex debugging tools:
> if(0)
>   drake_add_mex(drake_debug_mex EXECUTABLE drakeDebugMex.cpp)
> ```

_If_ this block of code disappears, than this `cpp` file should also be removed as part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-:-Knfv5EYcxKU0XXQnZOv:b-1ajov7)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/CMakeLists.txt, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-KnfukuGvXWc0Dn-zmyj:-KngAXgqDkSt9VN-bFWG:bgenfaa) ([raw file](https://github.com/robotlocomotion/drake/blob/a7ca4ef88064e64acf8de2f2d26bdce28782c871/drake/matlab/util/CMakeLists.txt#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_If_ this block of code disappears, than this `cpp` file should also be removed as part of this PR.
</blockquote></details>

it would be safe to delete that file, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-:-KngAbNnMKn7fp19MCA5:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 15 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/CMakeLists.txt, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6439#-KnfukuGvXWc0Dn-zmyj:-KnijsIDz3CW-Z5VyM8a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a7ca4ef88064e64acf8de2f2d26bdce28782c871/drake/matlab/util/CMakeLists.txt#L87)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it would be safe to delete that file, too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6439)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6439)*

**Pull request merged**
