### PR TITLE
Add and use github.bzl with github_archive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Upstream suggests this in bazelbuild/bazel#1194.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4975)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-:-KboooaX6pujrK3enF9U:bdph6cr)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-:-KbootoclZ8YpCBpnVIu:b-vawmhb)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a comment)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-Kbp4eCU2DJitsPMCnH2:-Kbp4eCU2DJitsPMCnH3:b8ln3kh) ([raw file](https://github.com/robotlocomotion/drake/blob/15705c93f05f64dd351d5fa42b52c5cc95b70e43/WORKSPACE#L25)):*
> ```
>     repository = "google/googletest",
>     commit = "release-1.7.0",
>     sha256 = "f73a6546fdf9fce9ff93a5015e0333a8af3062a152a9ad6bcb772c96687016cc",
> ```

`sha256` changed. Is it intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-:-Kbp4vsyiX4qwW3kMtG2:btfj096)*

**Comment by david-german-tri** [comment]
:lgtm: cool!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-:-Kbp8McTY7-gnaPJQSUG:b-84whef)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-Kbp4eCU2DJitsPMCnH2:-Kbp96jtG9ktg-gYSQ_y:b-tgz338) ([raw file](https://github.com/robotlocomotion/drake/blob/15705c93f05f64dd351d5fa42b52c5cc95b70e43/WORKSPACE#L25)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`sha256` changed. Is it intended?
</blockquote></details>

Yes, the file used to be `.zip` flavor but is now `.tar.gz` flavor, so the checksum has changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[WORKSPACE, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4975#-Kbp4eCU2DJitsPMCnH2:-Kbp9K-qiWML7rTTSugx:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/15705c93f05f64dd351d5fa42b52c5cc95b70e43/WORKSPACE#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, the file used to be `.zip` flavor but is now `.tar.gz` flavor, so the checksum has changed.
</blockquote></details>

Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4975)*

**Pull request merged**
