### PR TITLE
Buildcop:  Disable tests failing due to #15229

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15230)

### CODE REVIEW

**Comment by ggould-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(priority: emergency) +(status: single reviewer ok) +@jwnimmer-tri 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15230#-:-McoqBQP6VHYWJuED5V6:b-po4byd)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[solvers/test/ipopt_solver_test.cc, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15230#-McoqTQ46pocFu3g4FAX:-McoqTQ46pocFu3g4FAY:b-mgfldf) ([raw file](https://github.com/robotlocomotion/drake/blob/95c058ccd5a8dcae25e8aece27c68bd889888438/solvers/test/ipopt_solver_test.cc#L112)):*
> ```cpp
> };
> 
> GTEST_TEST(DISABLED_IpoptSolverTest, AcceptableResult) {
> ```

nit Shouldn't the `DISABLED` go on `AcceptableResult`, not the suite name?  Making a new suite just to disable it's only case strikes me as off.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15230)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15230)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
