### PR TITLE
CamelCase to snake_case, cpp to cc in drake/multibody files

### LINKED ISSUE #4082: Refactor `drake/multibody` files to follow style guide
Refactor files from CamelCase to snake_case, cpp to cc.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Closes #4082.

This depends on RobotLocomotion/director#368 and thus the "do not merge" label.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4098)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for platform/feature review please? (I am assigning the platform for Thursday here) and since this relates to your issue #1965. I think this is much easier to review than the previous PR #4058.

---

Review status: 0 of 175 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-:-KWAVT2iXI9TL0Kk8Sdd:bs28mw0)*

**Comment by jwnimmer-tri** [comment]
Starting review now.

---

Reviewed 2 of 235 files at r1.
Review status: 2 of 175 files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitmodules, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-KWBHHjSKyEJWwI6Op6w:-KWBHHjTZRpsHDzZEhq0:bj87qmk) ([raw file](https://github.com/robotlocomotion/drake/blob/f6883e68d0998da99a5979e9e5d703e7c920d8df/.gitmodules#L21)):*
> ```
> [submodule "externals/director"]
> 	path = externals/director
> 	url = https://github.com/amcastro-tri/director.git
> ```

Marking this DNM until this is updated after the director PR merges.

---

*[externals/director, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-KWBHSwLRQEaQtS1-8a1:-KWBHSwLRQEaQtS1-8a2:bj87qmk) ([raw file](https://github.com/robotlocomotion/drake/blob/f6883e68d0998da99a5979e9e5d703e7c920d8df/externals/director#L1)):*
> ```
> Subproject commit cf2607756e2c87c41d4a7265a444fed419731aaa
> ```

Marking this DNM until this is updated after the director PR merges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-:-KWBHXy4gArcsNMy1FWt:b-brdniz)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 233 of 235 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-KWBKRyzBSFxkzvVjF9z:-KWBKRz0ZG5-H7ieKghk:brp953v) (no related file):*
This new blocking discussion will remind us (me) to double-check that the number of tests run by the matlab pre-merge build is correct (unchanged), in the final rebuild prior to merging this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-:-KWBKegWeajFmp2Bl6vc:bnfp4nl)*

**Comment by amcastro-tri** [comment]
RobotLocomotion/director#368 was merged in Director and I updated the hash in this PR. PTAL.

---

Review status: 173 of 174 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-:-KWDvKBm7LyxhWWMh7Gv:b-w9n9q9)*

**Comment by jwnimmer-tri** [comment]
Code changes are all good now.  Just need to wait for CI and then count that all the tests ran.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-:-KWDwAs6efkdew4kMUev:b9ukkks)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4098#-KWBKRyzBSFxkzvVjF9z:-KWE-Iu73gg8YqW0eMM6:bp14pi6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This new blocking discussion will remind us (me) to double-check that the number of tests run by the matlab pre-merge build is correct (unchanged), in the final rebuild prior to merging this PR.
</details>
Actually, the CMake changes were benign; this is unlikely to accidentally lose tests.  Marking as withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4098)*

**Pull request merged**
