### PR TITLE
Finally remove pods_find_pkg_config and pods_use_pkg_config_packages

### PR DESCRIPTION
**Pull request by jamiesnape**
Depends on #4413.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4416)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
:confetti_ball: :tada: :balloon: :+1: 

I'll go review #4413 pronto

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/packages.cmake, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbBGUGjcK-uIAjEg0:-KYUbBGV2v3amznpnZA6:b-hqroq0) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L87)):*
> ```CMake
>     find_library(${PACKAGE}_${_library}_LIBRARY
>       NAMES ${_library} HINTS ${${PACKAGE}_LIBRARY_DIRS})
>     list(APPEND _libraries ${${PACKAGE}_${_library}_LIBRARY})
> ```

Should this check that the library actually exists? (Probably we don't want things linking to `<name>-NOTFOUND`...)

Also, I wondered if we should enforce that the library exists in the specified `DIRS`, but I guess not doing so is consistent with the behavior if you were just using `pkg-config` straight up.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUbo1_F_FJZQw9Hro0:b-y1khb0) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
> ```CMake
> 
>     if(${PACKAGE}_INCLUDE_DIRS)
>       set_property(TARGET ${PACKAGE} PROPERTY
> ```

...something wrong with `target_include_directories`? :wink:

---

*[cmake/packages.cmake, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbuaful-q1V8yxZVv:-KYUbuaful-q1V8yxZVw:bg0j33s) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L105)):*
> ```CMake
> 
>     if(_libraries)
>       set_property(TARGET ${PACKAGE} PROPERTY
> ```

...something wrong with `target_link_libraries`? :wink:

---

*[cmake/packages.cmake, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUc4vC69HjqtreXjSS:-KYUc4vC69HjqtreXjST:bvnd0zq) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L110)):*
> ```CMake
> 
>     if(${PACKAGE}_CFLAGS_OTHER)
>       set_property(TARGET ${PACKAGE} PROPERTY
> ```

...something wrong with `target_compile_options`? :wink:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUcYO2vdBSAw6zhj4F:b-rt5o8a) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...something wrong with `target_include_directories`? :wink:
</blockquote></details>

...also, `target_include_directories` can (and should be?) `SYSTEM`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/packages.cmake, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbBGUGjcK-uIAjEg0:-KYUd67ql1OcMBGrzme8:b-z1r3b6) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L87)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Should this check that the library actually exists? (Probably we don't want things linking to `<name>-NOTFOUND`...)

Also, I wondered if we should enforce that the library exists in the specified `DIRS`, but I guess not doing so is consistent with the behavior if you were just using `pkg-config` straight up.
</blockquote></details>

Exactly, and it would break drake.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUcWZHjhJqna4-WzkV:b-mafv4b) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...also, `target_include_directories` can (and should be?) `SYSTEM`
</blockquote></details>

It is an imported target so you can use target_include_directories, and no, definitely not SYSTEM.

---

*[cmake/packages.cmake, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbuaful-q1V8yxZVv:-KYUd1jRUpfNOBtCI2IM:ba2inra) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L105)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...something wrong with `target_link_libraries`? :wink:
</blockquote></details>

Imported target.

---

*[cmake/packages.cmake, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUc4vC69HjqtreXjSS:-KYUd4lDEMqFAG8Ri3Th:ba2inra) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L110)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...something wrong with `target_compile_options`? :wink:
</blockquote></details>

Imported target.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUdMF4dFYZWamOEcXI:bmdcrb3) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It is an imported target so you can use target_include_directories, and no, definitely not SYSTEM.
</blockquote></details>

Cannot use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUq48azHKY4VZcjgiL:b-v9caou) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Cannot use.
</blockquote></details>

...but `pods_use_pkg_config_packages` used `include_directories(SYSTEM ${__inc_dir})`; therefore, isn't this a behavior change? (We *don't* want externals to be treated as `SYSTEM` headers? :confused:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/packages.cmake, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbo1ZQUkR_LBybbzq:-KYUqsrTaqGvgjXFkks9:b5v6kqe) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L100)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...but `pods_use_pkg_config_packages` used `include_directories(SYSTEM ${__inc_dir})`; therefore, isn't this a behavior change? (We *don't* want externals to be treated as `SYSTEM` headers? :confused:)
</blockquote></details>

Not with the current install tree layout of Drake and not while Xcode does not respect SYSTEM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/packages.cmake, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYUbBGUGjcK-uIAjEg0:-KYUrFnmj0b9hbOdx7Rt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/44be1b34c422d9f7cfd15055f1da0558bb99b720/cmake/packages.cmake#L87)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Exactly, and it would break drake.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-:-KYUs0eSl-cd0vqMoyJW:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/packages.cmake, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYVKaG-mkSKZQXSBM12:-KYVKaG0qsffkbQvNZB5:b-jrw56d) ([raw file](https://github.com/robotlocomotion/drake/blob/964b4251c22d326143a27641ecf0afc20cf15788/cmake/packages.cmake#L79)):*
> ```CMake
> # Create an imported target from information from pkg_check_modules.
> #
> # TODO(jamiesnape): Fix the version upstream.
> ```

Could you include more information in this TODO, like a CMake bug report?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-:-KYVMHbBLUhsqCAfwlTw:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/packages.cmake, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-KYVKaG-mkSKZQXSBM12:-KYVTPOt3lHAFwJ94d8S:bes53sd) ([raw file](https://github.com/robotlocomotion/drake/blob/964b4251c22d326143a27641ecf0afc20cf15788/cmake/packages.cmake#L79)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Could you include more information in this TODO, like a CMake bug report?
</blockquote></details>

Clarified. Looking again, it could be more a philosophical difference of opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4416#-:-KYVa8Uhf6JtpkMgRmOv:bnfp4nl)*

**Pull request merged**
