### PR TITLE
Move deprecated System 1.0 infrastructure to drake/system1

### LINKED ISSUE #3901: Move deprecated System 1.0 infrastructure to drake/system1
We should physically separate deprecated System 1.0 infrastructure, both so that the new world is cleaner, and so that we can trivially identify in-tree code that's using deprecated APIs (e.g., `rgrep system1/`).

I have a branch ready at https://github.com/jwnimmer-tri/drake/tree/build-system1 with this change, and will PR once #3861 lands.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #3901.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3902)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +@sammy-tri for all review, please.

---

Review status: 0 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-:-KUxQrUMzIypb35moemK:b-8k1tb3)*

**Comment by sherm1** [comment]
:+1: Thanks, Jeremy!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-:-KUxSaxNKV0NKdK60niv:biv13xl)*

**Comment by sammy-tri** [comment]
I only read a subset of the files in this PR (along with the less mechanical looking commits themselves).  That being said, :lgtm:.

---

Reviewed 33 of 80 files at r1.
Review status: 22 of 58 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/inverseKinTrajBackend.cpp, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-KUxdKc4U4sMT54zU72L:-KUxdKc4U4sMT54zU72M:b-uqwz97) ([raw file](https://github.com/robotlocomotion/drake/blob/591801acd525b4182944291ffeee4340d2161a1f/drake/systems/plants/inverseKinTrajBackend.cpp#L19)):*
> ```cpp
> #include <drake/systems/plants/IKoptions.h>
> #include <drake/systems/plants/RigidBodyTree.h>
> #include <drake/system1/vector.h>
> ```

FYI I think this is actually unused, but I don't think auditing for this case is really within the scope of this PR.

---

*[drake/systems/plants/test/testIK.cpp, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-KUxdhIGOe8k9UF5_QaA:-KUxdhIGOe8k9UF5_QaB:b-uqwz97) ([raw file](https://github.com/robotlocomotion/drake/blob/591801acd525b4182944291ffeee4340d2161a1f/drake/systems/plants/test/testIK.cpp#L12)):*
> ```cpp
> #include "drake/systems/plants/RigidBodyTree.h"
> #include "drake/systems/plants/constraint/RigidBodyConstraint.h"
> #include "drake/system1/vector.h"
> ```

FYI I think this is actually unused, but I don't think auditing for this case is really within the scope of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-:-KUxdn9fZ60aSDGKpUrS:b-qcsi5a)*

**Comment by jwnimmer-tri** [comment]
Review status: 22 of 58 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/inverseKinTrajBackend.cpp, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3902#-KUxdKc4U4sMT54zU72L:-KUxj-wKlALyMkwxhkiy:b-vus3b2) ([raw file](https://github.com/robotlocomotion/drake/blob/591801acd525b4182944291ffeee4340d2161a1f/drake/systems/plants/inverseKinTrajBackend.cpp#L19)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI I think this is actually unused, but I don't think auditing for this case is really within the scope of this PR.
</details>
Ok, thanks.  Will address these in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3902)*

**Comment by jwnimmer-tri** [comment]
For the record -- I take it back.  I don't have easy access to licenses to compile all of the IK code, so I'm not going to screw with it.  Whoever purges System 1.0 from IK can fix it.

**Comment by jwnimmer-tri** [comment]
Oops, this broke the ROS builds (hello, #2116).  I will fix before tomorrow morning.

**Pull request merged**
