### PR TITLE
manipulation_station: Add LCM cameras to mock simulation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a warm-up exercise before the next step of publishing the cameras' point clouds (#14985).

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14982)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake in case you'd like to weigh in, or review.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14982#-:-MZhKW4V4g3Ed2Dgr-3I:btapcqv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule on Monday, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14982#-:-MZmwqQ7Do6RyCNIKBxQ:bmxilld)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@russtedrake (for retroactive feature review.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14982#-:-MZmx0VxBIzD_JWlZFzX:b-y1yco9)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
