### PR TITLE
Update pycps to support pkgconfig

### PR DESCRIPTION
**Pull request by fbudin69500**
Requires:
- [x] https://github.com/mwoehlke/pycps/pull/15

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9399)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Thanks! If this resolves #7355, can put `Closes #7355` in your description?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
FYI @EricCousineau-TRI is otherwise occupied for another week or so.  If you'd like me to feature review instead, you can send it over to me.  (However, this doesn't seem urgent though either, so waiting is probably fine too.)

**Comment by jwnimmer-tri** [comment]
FYI @fbudin69500 There are merge conflicts now.  Needs a refresh.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI should this PR still remain open?  It seems to be stalled.  Maybe just rescue the Eigen3 portion and get that into master?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI re-ping.  Should this PR still remain open? It seems to be stalled. Maybe just rescue the Eigen3 portion and get that into master?

**Comment by jamiesnape** [comment]
We can close. I can pick it up in a different PR.

**Pull request closed without merging**
