### PR TITLE
[hardware_sim] Switch demo to use IIWA instead of UR3e

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We don't have any ID control / communication code for UR3e's in Drake.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@SeanCurtis-TRI for platform review, please.

\CC @zachfang @calderpg-tri FYI

In the future we can add dual-arm demos or demos with Jaco arms, but for now I just want to get the UR3e out of the way.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one question about the design intention of the example.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693#-:-N8eR8rd5LFilm6Bw3dl:b-c81uoz)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`examples/hardware_sim/example_scenarios.yaml` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17693#-N8eQ7E-8wrfrBCKcueQ:-N8eQ7E02FjQlIcRkTFb:bns0tyo) ([raw file](https://github.com/robotlocomotion/drake/blob/a27e4d8d6ba99b0b7234091074a7786d28f80ea2/examples/hardware_sim/example_scenarios.yaml#L1)):*
> ```YAML
> # This simulation loads an IIWA and WSG.
> ```

While this is admittedly expedient, one of the things we lose in this example is the illustration of hierarchical decomposition of the simulation specification.

Is this a short enough stop-gap that we'll end up bringing that decomposition back in a reasonable timeline? Or is it worth introducing a modicum of that now (even if it seems a trifle overwrought) for pedagogical reasons?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`examples/hardware_sim/example_scenarios.yaml` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17693#-N8eQ7E-8wrfrBCKcueQ:-N8ecDDHCfv5PUa1uHZI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a27e4d8d6ba99b0b7234091074a7786d28f80ea2/examples/hardware_sim/example_scenarios.yaml#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

While this is admittedly expedient, one of the things we lose in this example is the illustration of hierarchical decomposition of the simulation specification.

Is this a short enough stop-gap that we'll end up bringing that decomposition back in a reasonable timeline? Or is it worth introducing a modicum of that now (even if it seems a trifle overwrought) for pedagogical reasons?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693#-:-N8iVwYRCV2FRkZRAT_P:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I adjusted the unit test to avoid Debug timeouts.  PTAL.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17693)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
