### PR TITLE
 Use CMake build directory for output_user_root where possible

### PR DESCRIPTION
**Pull request by jamiesnape**
Otherwise use a unique directory based on the name of the binary directory (rather than source directory) to avoid conflicting with a conventional Bazel build.

Relates #7835. FYI @RussTedrake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8353)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-L7We_WUmUWYaIx_qFHL:-L7We_WWvaabvdim9awJ:b-w6bt28) ([raw file](https://github.com/robotlocomotion/drake/blob/0a750243f0551cae832f617688ff93bcbf0ef66a/CMakeLists.txt#L75)):*
> ```CMake
> if(STRING_FIND_RESULT_VARIABLE EQUAL 0)
>   if(APPLE)
>     set(BAZEL_OUTPUT_USER_ROOT "/var/tmp")
> ```

Per discussion in https://github.com/RobotLocomotion/spartan/issues/265, would it be possible to make this command-line configurable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-L7We_WUmUWYaIx_qFHL:-L7Wm5M7V2hgJD5m360E:bnyrw9r) ([raw file](https://github.com/robotlocomotion/drake/blob/0a750243f0551cae832f617688ff93bcbf0ef66a/CMakeLists.txt#L75)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Per discussion in https://github.com/RobotLocomotion/spartan/issues/265, would it be possible to make this command-line configurable?
</blockquote></details>

No, they should choose an appropriate CMAKE_BINARY_DIR instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353)*

**Comment by fbudin69500** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-L7a507T9WRTekRyYzjX:-L7a507UhUbV8IC8qCck:b-bjj1gu) ([raw file](https://github.com/robotlocomotion/drake/blob/0a750243f0551cae832f617688ff93bcbf0ef66a/CMakeLists.txt#L73)):*
> ```CMake
> )
> 
> if(STRING_FIND_RESULT_VARIABLE EQUAL 0)
> ```

It would be good to document what this does, i.e. if the binary folder is a subfolder of the source folder... and why

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-L7a507T9WRTekRyYzjX:-L7duzRuUshRCT-aNeQc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a750243f0551cae832f617688ff93bcbf0ef66a/CMakeLists.txt#L73)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

It would be good to document what this does, i.e. if the binary folder is a subfolder of the source folder... and why
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-L7e2yb9LAbbcPxMoPTZ:-L7e2yb9LAbbcPxMoPT_:bhkcc6s) ([raw file](https://github.com/robotlocomotion/drake/blob/34d876b50d2757602c00ab18cd252fa7a237fee4/CMakeLists.txt#L89)):*
> -output_user_r

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-:-L7e3xG-pQek_Y0kqnhu:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm: Nice!

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8353#-:-L7e_svGw1sNfMnEITS_:b-8gk8uj)*

**Pull request merged**
