### PR TITLE
Add symbolic support to Maliput lane

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7658)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jadecastro for feature-review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L0uG5tRJcv3Y5jd1eV7:b2q2fko)*

**Comment by jadecastro** [comment]
Pass complete.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/maliput/dragway/lane.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rozdApQWVhkp4IocQ:-L1rozdApQWVhkp4IocR:bqsi157) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/lane.cc#L191)):*
> ```cpp
>     // have the same value. As a result, one should not change the order of the
>     // arguments in the max function below. For more information, see
>     // https://github.com/RLovelett/eigen/blob/7a40ad2b1d1e3d18949e38cccba140ca7b8aa5a5/unsupported/Eigen/src/AutoDiff/AutoDiffScalar.h#L552-L556
> ```

Actually, don't we provide the `max` overload in our own file here (included in `common/autodiff.h`): https://github.com/RobotLocomotion/drake/blob/master/common/autodiffxd.h#L409 ?

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 829 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1roXG-Urqi0t7G2K7f:-L1roXG-Urqi0t7G2K7g:b-ltz814) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L829)):*
> ```cpp
> }
> 
> TEST_F(MaliputDragwayLaneTest, AutoDiffMaxTest) {
> ```

Is `ImplDoToLanePositionT` the only place where ordering matters in the event that the values are equal, or do we expect this behavior to hold true elsewhere also?  If so, then perhaps this test goes in https://github.com/RobotLocomotion/drake/blob/master/common/test/autodiffxd_max_test.cc, along with the reference to `ImplDoToLanePositionT`?

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 850 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rzCN2YXlLJXVxtSCs:-L1rzCN2YXlLJXVxtSCt:b2kr36n) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L850)):*
> ```cpp
>   const double v_x = 1.0;
>   const double v_y = 2.0;
>   const double v_z = -0.5;
> ```

BTW, these values lie outside the lane, where you get nonzero distance, and `symbolic_gp != api::GeoPositionT<symbolic::Expression>{x, y, z}`.  Consider also checking values inside the lane, where you would expect `distance = 0.`,  `symbolic_gp == api::GeoPositionT<symbolic::Expression>{x, y, z}`.  You might also consider taking advantage of `GetExpectedLaneParameters` to ensure that the range conditions are met.

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 868 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rvXEBC-3F7X0VenMW:-L1rvXEBC-3F7X0VenMX:b-xa89la) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L868)):*
> ```cpp
>   EXPECT_EQ(symbolic_gp.y().Evaluate(env), gp.y());
>   EXPECT_EQ(symbolic_gp.z().Evaluate(env), gp.z());
>   EXPECT_EQ(symbolic_distance.Evaluate(env), distance);
> ```

BTW, consider adding a test comparing the return values of `Lane::ToLanePositionT<symbolic>`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L1s-LnYdtz_3OEfnLeY:bilrup7)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/maliput/dragway/lane.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rozdApQWVhkp4IocQ:-L1sDbdJWDGo8PpHVEXw:b9cedjm) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/lane.cc#L191)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Actually, don't we provide the `max` overload in our own file here (included in `common/autodiff.h`): https://github.com/RobotLocomotion/drake/blob/master/common/autodiffxd.h#L409 ?
</blockquote></details>

Done. Thanks for catching it!

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 829 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1roXG-Urqi0t7G2K7f:-L1sF3JKkDGHl_Sp-87r:bi4h2ij) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L829)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Is `ImplDoToLanePositionT` the only place where ordering matters in the event that the values are equal, or do we expect this behavior to hold true elsewhere also?  If so, then perhaps this test goes in https://github.com/RobotLocomotion/drake/blob/master/common/test/autodiffxd_max_test.cc, along with the reference to `ImplDoToLanePositionT`?
</blockquote></details>

Done. (moved to `common/test/autodiffxd_max_test.cc`)

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 850 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rzCN2YXlLJXVxtSCs:-L1sOefM1aLzTg9ThSmm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L850)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, these values lie outside the lane, where you get nonzero distance, and `symbolic_gp != api::GeoPositionT<symbolic::Expression>{x, y, z}`.  Consider also checking values inside the lane, where you would expect `distance = 0.`,  `symbolic_gp == api::GeoPositionT<symbolic::Expression>{x, y, z}`.  You might also consider taking advantage of `GetExpectedLaneParameters` to ensure that the range conditions are met.
</blockquote></details>

Done.

---

*[automotive/maliput/dragway/test/dragway_test.cc, line 868 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1rvXEBC-3F7X0VenMW:-L1sOexVefS2n9vkqb1R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97957332646c5a17696a7816a723e264b240e250/automotive/maliput/dragway/test/dragway_test.cc#L868)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, consider adding a test comparing the return values of `Lane::ToLanePositionT<symbolic>`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658)*

**Comment by jadecastro** [comment]
:lgtm: !

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L1sbFQYv5bAbNGUWPnC:b593w5u)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L1sbRHi5gr-ENnl50yo:b-3ojlqy)*

**Comment by sammy-tri** [comment]
Sorry, ended up being AFK in meetings/lab for much of the afternoon.  Will review tomorrow.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L1t9jOHNsCbgTJ-xHK3:b-ainsrg)*

**Comment by sammy-tri** [comment]
One minor comment-related BTW, otherwise :lgtm: 

---

Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/autodiffxd_max_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1wXVRapYaDr7qF-DU6:-L1wXVRbMfG84nbXNW7H:bakc8z7) ([raw file](https://github.com/robotlocomotion/drake/blob/28e19a7b5af8e2172eaa0735778c953915bf8074/common/test/autodiffxd_max_test.cc#L17)):*
> ```cpp
> TEST_F(AutoDiffXdTest, TieBreakingCheck) {
>   // Given `max(v1, v2)`, Eigen autodiff's implementation of the max function
>   // and our overload return the first argument `v1`. In Drake, we rely on this
> ```

BTW the fact that the test is called `TieBreakingCheck` is a pretty good clue, but this text reads a little like `max(v1, v2)` unconditionally returns the first argument `v1` (which would not really make sense).  It might be helpful to state the specific condition being tested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-:-L1wYUjcV5hcOvkIgbFn:b-835r44)*

**Comment by soonho-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/autodiffxd_max_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7658#-L1wXVRapYaDr7qF-DU6:-L1wa6pFv__jZiTNqiLz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28e19a7b5af8e2172eaa0735778c953915bf8074/common/test/autodiffxd_max_test.cc#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW the fact that the test is called `TieBreakingCheck` is a pretty good clue, but this text reads a little like `max(v1, v2)` unconditionally returns the first argument `v1` (which would not really make sense).  It might be helpful to state the specific condition being tested.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7658)*

**Pull request merged**
