### PR TITLE
developers: Update platform reviewer list

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Was reviewing docs for third-party updates (for #16140); while doing so, i think our platform reviewer list is out of date.

FYI @soonhokong (in case y'all have already discussed this and I missed it)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16141)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16141#-:-MpIKX4W8rikoAOS6jJf:bclzdmo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
+@sherm1 drive by :lgtm: in case you want it

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16141#-:-MpJAOHuCB-eMSfS-Xof:b-wom6u4)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by EricCousineau-TRI** [comment]
Thanks! Will await second review, then merge if it's OK.

**Review by jwnimmer-tri — COMMENTED** [review]
I think it would have been a kindness if you had talked to @soonhokong about this first, but I suppose in any case the @soonho-tri account should not be on this list.  We can separate the question of adding back @soonhokong into a separate PR.

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16141#-:-Mpw6ctY3x9GDpoYXMfr:b-azp60h)* status: missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Good point, will do so in the future - thanks!

**Comment by soonhokong** [comment]
No problem with me. Thanks for updating the list!

**Pull request merged**
