### PR TITLE
Instantiation of RigidBodyTree<AutoDiffXd>

### PR DESCRIPTION
**Pull request by amcastro-tri**
Cross your fingers. First instantiation of `RBT<AutoDiffXd>`!!!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4419)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
This is a small PR but a big milestone for RBT.
+@ggould-tri for platform/feature review please?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-:-KYTtgg6iKLgRQ2jlIn5:bq8c14r)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-KYTu1jWdP15Xo3phNy_:-KYTu1jWdP15Xo3phNya:ba03r3) (no related file):*
cc'ing @sherm1, @seancurtis-tri 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-KYTu1jWdP15Xo3phNy_:-KYTxcN3CzpEnhcmA5fH:basjcnd) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

cc'ing @sherm1, @seancurtis-tri 
</blockquote></details>

:LGTM: A tiny change that decouples the cache from the `RigidBody`.  Elegant and concise.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-KYTu1jWdP15Xo3phNy_:-KYU-vRnESs1yFZEf0Nm:b-d21ufm) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

:LGTM: A tiny change that decouples the cache from the `RigidBody`.  Elegant and concise.  
</blockquote></details>

Thanks man! I see you are up in PA time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419)*

**Comment by ggould-tri** [comment]
Bravo!

Can any of the tests in `multibody/tests` be duplicated or switched to `AutoDiffXd`?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-:-KYU0y9Ni0ZQeMeId5d_:bgry8ud)*

**Comment by amcastro-tri** [comment]
It wouldn't be very meaningful at this stage since all methods in RBT still are "template-methods-on-Scalar" (different from the class T parameter).
All code usages of RBT still call template methods like so: `RBT<double>::MyQuery(KinematicsCache<Scalar>&)`.

The next stage from this PR is transmogrification from `RBT<double>` (as already done in #4426, but needs cleanup), essentially the equivalent to `System<T>::ToAutoDiffXd()`. 

Once `RBT<T>::ToAutoDiffXd()` lands and I start switching from `RBT<double>::MyQuery(KinematicsCache<Scalar>&)` to `RBT<T>::MyQuery(KinematicsCache<T>&)` those tests will start making sense.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-:-KYU1mgi-zxv3zsJBDVV:borxkkl)*

**Comment by ggould-tri** [comment]
That makes sense.

:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4419#-:-KYU3iZxEE40SGhCo9n8:b-nkrucl)*

**Comment by sherm1** [comment]
Congratulations, @amcastro-tri! Great milestone!

**Comment by liangfok** [comment]
:champagne:

**Pull request merged**
