### PR TITLE
Add a simple 1D bouncing ball scenario

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This will serve as the initial example of using `GeometrySystem` in a Drake diagram. Currently, it does not *depend* on `GeometrySystem`. As that class's implementation increases in master, this example will expand to incorporate that functionality.

The scenario is that of a ball with a single degree of freedom (z-position). It interacts with an implicitly defined half space (`z = 0`). It bounces on that half plane based on a complaint contact model. Currently, 
there is no visualization or other feedback. This will come into place as the various `GeometrySystem` features come online.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6582)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@avalenzu for feature review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpGSjKbGNBh3GxbRJNi:b-fcohnv)*

**Comment by avalenzu** [comment]
Review pass done. PTAL.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/geometry_world/bouncing_ball_plant.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpH4mTbJAqZkLa6I5sF:-KpH4mTbJAqZkLa6I5sG:b-c425fu) ([raw file](https://github.com/robotlocomotion/drake/blob/f39486b728152d486dcf5041a7410a7544dacb3d/drake/examples/geometry_world/bouncing_ball_plant.cc#L57)):*
> ```cpp
> 
>   const T& x = -state.z();  // Penetration depth, > 0 at penetration.
>   const T& xdot = -state.zdot();  // Penetration rate, > 0 during penetration.
> ```

The penetration rate can't always be positive during penetration. That ball's gotta start moving upwards if it's going to bounce!

---

*[drake/examples/geometry_world/bouncing_ball_run_dynamics.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpH4-c9AKZqomit6GTR:-KpH4-c9AKZqomit6GTS:b4lqt6j) ([raw file](https://github.com/robotlocomotion/drake/blob/f39486b728152d486dcf5041a7410a7544dacb3d/drake/examples/geometry_world/bouncing_ball_run_dynamics.cc#L21)):*
> ```cpp
> 
>   systems::Simulator<double> simulator(*diagram);
>   auto init_ball = [&](BouncingBallPlant<double>* system,
> ```

Is this function defined here for use in later versions of this example? In the current version, it seems like you could just do the steps included in the body of the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpH5mfBcUBjDs7hJOk5:b837gv3)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed. PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/geometry_world/bouncing_ball_plant.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpH4mTbJAqZkLa6I5sF:-KpHVsj77BvrRF7ezQEm:b-whz6zl) ([raw file](https://github.com/robotlocomotion/drake/blob/f39486b728152d486dcf5041a7410a7544dacb3d/drake/examples/geometry_world/bouncing_ball_plant.cc#L57)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

The penetration rate can't always be positive during penetration. That ball's gotta start moving upwards if it's going to bounce!
</blockquote></details>

Done 

Comment corrected.

---

*[drake/examples/geometry_world/bouncing_ball_run_dynamics.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpH4-c9AKZqomit6GTR:-KpHVzmuI_Ewf-wwopE8:b-g4ruzb) ([raw file](https://github.com/robotlocomotion/drake/blob/f39486b728152d486dcf5041a7410a7544dacb3d/drake/examples/geometry_world/bouncing_ball_run_dynamics.cc#L21)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Is this function defined here for use in later versions of this example? In the current version, it seems like you could just do the steps included in the body of the function.
</blockquote></details>

Yes indeed. I toyed with *completely* simplifying this, but decided that this could stay. If you'd rather see this cleaned up, let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpHW7pP1Ee8pvLVInG1:baz6201)*

**Comment by avalenzu** [comment]
LGTM. +@sammy-tri for platform review.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/geometry_world/bouncing_ball_run_dynamics.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpH4-c9AKZqomit6GTR:-KpMJXQp7s4x9ZE_61Gn:b-b3ywtm) ([raw file](https://github.com/robotlocomotion/drake/blob/f39486b728152d486dcf5041a7410a7544dacb3d/drake/examples/geometry_world/bouncing_ball_run_dynamics.cc#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Yes indeed. I toyed with *completely* simplifying this, but decided that this could stay. If you'd rather see this cleaned up, let me know.
</blockquote></details>

LGTM. I'm fine with leaving it here to decrease the churn in future PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpMJgavu5zQAcN08jbD:bojjc0n)*

**Comment by SeanCurtis-TRI** [comment]
Thanks @avalenzu.  I *think* you need to surround your LGTM with ":" to work.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpMNujt8RIrK_UN5ury:bejmt6c)*

**Comment by sammy-tri** [comment]
First pass complete, just a couple minor nitpicks

---

Reviewed 3 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/geometry_world/BUILD, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpM_jcwlCh9_1cEeCKE:-KpM_jcyMQL0DYnTUYgb:b-dcrvil) ([raw file](https://github.com/robotlocomotion/drake/blob/e6db6e1f91616224449a7aad9595f19ffb6c23e5/drake/examples/geometry_world/BUILD#L5)):*
> ```Python
> 
> load("//tools:cpplint.bzl", "cpplint")
> load("//tools:drake.bzl", "drake_cc_googletest", "drake_cc_library", "drake_cc_binary")
> ```

long line

---

*[drake/examples/geometry_world/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpMa-N8AFpyvvse_131:-KpMa-N9zDjC7DraYqkJ:b-oz6omy) ([raw file](https://github.com/robotlocomotion/drake/blob/e6db6e1f91616224449a7aad9595f19ffb6c23e5/drake/examples/geometry_world/BUILD#L22)):*
> ```Python
>     deps = [
>         ":bouncing_ball_vector",
>         "//drake/systems/framework",
> ```

BTW you could consider a narrower dependency here (I think you only directly use leaf_system?  Though that still pulls in most of framework, so up to you)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpMbFV1bHzpjmYG8uKT:b4ou4k8)*

**Comment by SeanCurtis-TRI** [comment]
nits addressed. +(status: curate commits before merging) 

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/geometry_world/BUILD, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpM_jcwlCh9_1cEeCKE:-KpMcK4RY1dJGKkacWWb:bgyqpz8) ([raw file](https://github.com/robotlocomotion/drake/blob/e6db6e1f91616224449a7aad9595f19ffb6c23e5/drake/examples/geometry_world/BUILD#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done

This one jumped out at me as well. I ran it through buildifier and it was untouched. Kind of surprised me. So, I've modified it by hand to match `common` (https://github.com/RobotLocomotion/drake/blob/master/drake/common/BUILD).

---

*[drake/examples/geometry_world/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-KpMa-N8AFpyvvse_131:-KpMh8Fu9zv0yqjZMPzl:ba38zbp) ([raw file](https://github.com/robotlocomotion/drake/blob/e6db6e1f91616224449a7aad9595f19ffb6c23e5/drake/examples/geometry_world/BUILD#L22)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW you could consider a narrower dependency here (I think you only directly use leaf_system?  Though that still pulls in most of framework, so up to you)
</blockquote></details>

Done 

Reducing the slice is always nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpMhHA2VvkaY-3-UGXz:bf9g83o)*

**Comment by sammy-tri** [comment]
:lgtm: (pending CI)

---

Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpMkHnjIObsuLiw8E2u:b-lj32db)*

**Comment by SeanCurtis-TRI** [comment]
Thanks

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpQ3riIxTB6NpD7Is3C:b-zcjvte)*

**Comment by avalenzu** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpQ4AXrIoE9e4XglIww:bnfp4nl)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6582#-:-KpQ4JuYJeTctC0SKIyE:b-l70wzf)*

**Pull request merged**
