### PR TITLE
doc: Remove unused visual_studio_build_targets image

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This file has been dead code since #4656.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14580)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule, please.  A tasty morsel to enjoy for your on-call day.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14580#-:-MS40obY07EEwOZo6H7g:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14580)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
