### PR TITLE
[parsing] Use DiagnosticPolicy in ResolveUri

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(I'll assign to feature review once a few more of the in-flight parser PRs have merged, just to avoid rebase churn.)

Towards #16784.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The mirrors.bazel.build flaked out again:
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820#-:-MyihQD07JpZtLiEuqBP:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_parser.cc, line 1381 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16820#-MyiTJvB8mZqRYvH4b7X:-MyiTJvB8mZqRYvH4b7Y:bebkmgw) ([raw file](https://github.com/robotlocomotion/drake/blob/54ebc3a4aab7e0157548dd4e8e367e0b588ec653/multibody/parsing/detail_sdf_parser.cc#L1381)):*
> ```cpp
>     [=](const std::string &_input) {
>       // This callback uses an empty return value to denote errors. We'll punt
>       // our detail messages into a debug-only loc.
> ```

typo? `loc` -- perhaps `log`?

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
I'm a little tied up today. I'll review this tomorrow.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820#-:-MyiiXwg7ysy1CvYBwO6:b-p67w5q)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 7 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820#-:-MymT2hM2EEFMqGVzC3K:bzus18)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_path_utils.cc, line 44 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16820#-MymOTsi5aenweTKzhA4:-MymOTsj4YOCeb6VBL1k:b1wd5fo) ([raw file](https://github.com/robotlocomotion/drake/blob/582256c60d71a689f740609f98a242cdb2d7d7fc/multibody/parsing/detail_path_utils.cc#L44)):*
> ```cpp
>         return {};
>       }
>       const std::string package_path = package_map.GetPath(uri_package);
> ```

nit do we need a copy here?
___
*[multibody/parsing/detail_sdf_parser.cc, line 1381 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16820#-MymQ2p1BshAMILghK6u:-MymQ2p1BshAMILghK6v:bb7lc4s) ([raw file](https://github.com/robotlocomotion/drake/blob/582256c60d71a689f740609f98a242cdb2d7d7fc/multibody/parsing/detail_sdf_parser.cc#L1381)):*
> ```cpp
>     [=](const std::string &_input) {
>       // This callback uses an empty return value to denote errors, and then
>       // it's caller reports it's own "no such file" error directly. We'll
> ```

nit 



_Suggestion:_
```cpp
its caller reports its own "no such file" error directly.
```
___
*[multibody/parsing/detail_urdf_geometry.cc, line 142 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16820#-MymQn916lrlbWW3x8z6:-MymQn916lrlbWW3x8z7:bpxrsy1) ([raw file](https://github.com/robotlocomotion/drake/blob/582256c60d71a689f740609f98a242cdb2d7d7fc/multibody/parsing/detail_urdf_geometry.cc#L142)):*
> ```cpp
>       texture_path = ResolveUri(
>           diagnostic, texture_name, package_map, root_dir);
>       DRAKE_THROW_UNLESS(!texture_path->empty());
> ```

BTW, do we actually expect  an empty `texture_path` if `diagnostic` doesn't complain? If so, the throw message probably should be more informative.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16820)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
