### PR TITLE
Provide hash and equality functions for Monomial

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5053)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-Kc5GANGcqf6eYwnPbIU:-Kc5GANGcqf6eYwnPbIV:b-a1sfw5) ([raw file](https://github.com/robotlocomotion/drake/blob/ba7dcd0dffed0c8653bfe267f8b5d88b0fc0dbac/drake/common/monomial.h#L208)):*
> ```objc
>  * \pre{All exponents in @p map_var_to_expnt are positive integers.}
>  */
> Expression Monomial(
> ```

@hongkai-dai , I think we need to rename this method otherwise we have a class `internal::Monomial` and this method `Monomial`.

Any suggestion for the new method name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-Kc5GANGcqf6eYwnPbIU:-KcJbT7LS38ukLA-u-HJ:b-av30dg) ([raw file](https://github.com/robotlocomotion/drake/blob/ba7dcd0dffed0c8653bfe267f8b5d88b0fc0dbac/drake/common/monomial.h#L208)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai , I think we need to rename this method otherwise we have a class `internal::Monomial` and this method `Monomial`.

Any suggestion for the new method name?
</blockquote></details>

Maybe `GetMonomial`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-:-KcJbaVkArYZvy3Nqd9k:bc8zi0o)*

**Comment by sherm1** [comment]
Platform: a couple of BTWs to address, then :lgtm:.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJxeP-x_N7dPuT6TAD:-KcJxeP-x_N7dPuT6TAE:bzbd4td) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.cc#L39)):*
> ```cpp
> 
> size_t Monomial::GetHash() const {
>   return hash_value<map<Variable::Id, int>>{}(powers_);
> ```

BTW, this needs some documentation. I was confused at first because it seemed like a recursive invocation of `hash_value()` but now I see this is a hash_value from a different type that you are making use of (I think!).

---

*[drake/common/monomial.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJuK5lidNbBggWEFwZ:-KcJuK5lidNbBggWEFw_:bba4pon) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.h#L51)):*
> ```objc
>   Expression ToExpression(
>       const std::unordered_map<Variable::Id, Variable>& id_to_var_map) const;
>   bool operator==(const Monomial& m) const;
> ```

BTW, this public method needs a doxygen description. Should say what it means for two Monomials to be equal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-:-KcJxvLCkG9PefwPSJCC:b3xuk0e)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJxeP-x_N7dPuT6TAD:-KcPIPg9m29T4nIusudo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.cc#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this needs some documentation. I was confused at first because it seemed like a recursive invocation of `hash_value()` but now I see this is a hash_value from a different type that you are making use of (I think!).
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-Kc5GANGcqf6eYwnPbIU:-KcPKv5wNcpiMST9YQKp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba7dcd0dffed0c8653bfe267f8b5d88b0fc0dbac/drake/common/monomial.h#L208)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe `GetMonomial`?
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJuK5lidNbBggWEFwZ:-KcPJuJR8Wq2Rmi2tWMz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.h#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this public method needs a doxygen description. Should say what it means for two Monomials to be equal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by sherm1** [comment]
Thanks for the update, @soonho-tri. I didn't find those comments illuminating, possibly due to ignorance on my part. But I made some suggestions about what could have been more helpful for me, in case people like me are in your target demographics for this API.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/common/monomial.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJxeP-x_N7dPuT6TAD:-KcPMctkArnBBMYqpsel:b-6edpzr) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.cc#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, that comment didn't really help me as an ignorant reader. I could see that powers_ is the argument, but not why you were doing that. Something more strategic would have helped, like "To get a hash value for a Monomial, we re-use the hash value for [what?] which is guaranteed to be suitable because [why?]."

---

*[drake/common/monomial.h, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcPNndKlskTFJD-RTjI:-KcPNndLfghykgvkvCYR:b-om6lrw) ([raw file](https://github.com/robotlocomotion/drake/blob/846a2d698fab0f11245789a3f69cceca94847c0f/drake/common/monomial.h#L54)):*
> ```objc
>    * checks if the two monomials have the same map from a variable ID to its
>    * exponent. */
>   bool operator==(const Monomial& m) const;
> ```

BTW, this is a functional description but doesn't answer the question (for me at least) of what it means for two monomials to be equal here. I don't know what it means for them to have "the same map". Is it saying that two monomials are equal iff they contain the same variable raised to the same exponent? Can there be different variables with the same name and if so could they ever be considered equal? Does it ignore the constant term?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-:-KcPPgDnXEiUPblxgeas:bced4ks)*

**Comment by soonho-tri** [comment]
Thanks for the points! I'll refine them soon.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-:-KcPTNdlmNFFu3c54cy-:b-rwi7ie)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.h, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcPNndKlskTFJD-RTjI:-KcPVUE6uhMsqxMvlEn7:bmwjwbt) ([raw file](https://github.com/robotlocomotion/drake/blob/846a2d698fab0f11245789a3f69cceca94847c0f/drake/common/monomial.h#L54)):*
>  Is it saying that two monomials are equal iff they contain the same variable raised to the same exponent?

Yes, this is the case. I will put this into the documentation.

> Can there be different variables with the same name and if so could they ever be considered equal? 

No. The `powers_` in a monomial maps a variable *ID* to its corresponding exponent. Name is not a part of a Monomial. 

> Does it ignore the constant term?

Yes. This class only keeps the non-constant part (i.e. `x^2y^3`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJxeP-x_N7dPuT6TAD:-KcQ5AJU49h0AtCUHjbM:bkdxuer) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.cc#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, that comment didn't really help me as an ignorant reader. I could see that powers_ is the argument, but not why you were doing that. Something more strategic would have helped, like "To get a hash value for a Monomial, we re-use the hash value for [what?] which is guaranteed to be suitable because [why?]."
</blockquote></details>

How is it?

---

*[drake/common/monomial.h, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcPNndKlskTFJD-RTjI:-KcQ5UsemHB355YpNt1N:biusdzy) ([raw file](https://github.com/robotlocomotion/drake/blob/846a2d698fab0f11245789a3f69cceca94847c0f/drake/common/monomial.h#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

>  Is it saying that two monomials are equal iff they contain the same variable raised to the same exponent?

Yes, this is the case. I will put this into the documentation.

> Can there be different variables with the same name and if so could they ever be considered equal? 

No. The `powers_` in a monomial maps a variable *ID* to its corresponding exponent. Name is not a part of a Monomial. 

> Does it ignore the constant term?

Yes. This class only keeps the non-constant part (i.e. `x^2y^3`).
</blockquote></details>

Is it good?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcJxeP-x_N7dPuT6TAD:-KcT_zbg2z06IFbyURM9:bo8g7m8) ([raw file](https://github.com/robotlocomotion/drake/blob/a3cbd7fb4b5f0674fd36600f23cccab4ef90ae5e/drake/common/monomial.cc#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How is it?
</blockquote></details>

Great -- thanks!

---

*[drake/common/monomial.h, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcPNndKlskTFJD-RTjI:-KcTaCK_rlasKy3d7QSM:bniemlh) ([raw file](https://github.com/robotlocomotion/drake/blob/846a2d698fab0f11245789a3f69cceca94847c0f/drake/common/monomial.h#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is it good?
</blockquote></details>

Will it be obvious to the reader that there is no constant in a Monomial? I didn't realize that until you said it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Comment by soonho-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/common/monomial.h, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5053#-KcPNndKlskTFJD-RTjI:-KcTacLgg703qhPYlOWa:b-8my2ni) ([raw file](https://github.com/robotlocomotion/drake/blob/846a2d698fab0f11245789a3f69cceca94847c0f/drake/common/monomial.h#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Will it be obvious to the reader that there is no constant in a Monomial? I didn't realize that until you said it.
</blockquote></details>

I see. I think that's actually important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5053)*

**Pull request merged**
