### PR TITLE
Fixes bug in System<T>::DeclareOutputPort.

### PR DESCRIPTION
**Pull request by amcastro-tri**
The port type was incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3486)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@david-german-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KRq73k1WLm6Nrv1zCl7:blpvwg6)*

**Comment by amcastro-tri** [comment]
+@sherm1 for platform plase

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS1_BW2Wi4ItufJIl4j:b-jo6ry7)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1_vbqpENwmxpgTsWA:-KS1_vbqpENwmxpgTsWB:b-beubcc) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L125)):*
> ```objc
>         try {
>           output_vector = output->get_vector_data(i);
>         } catch (std::bad_cast& e) {
> ```

Catching exceptions (in non-test code) is forbidden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1_vbqpENwmxpgTsWA:-KS1nbSymtdGlV_HfYrO:bkookpo) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Catching exceptions (in non-test code) is forbidden.
</details>
I agree, catching exceptions is scary and we shouldn't do it, even if the `catch` branch immediately aborts, as it does here.  However, this code makes me wonder if there are use cases `drake_assert.h` isn't currently meeting, and if so, how we should meet them.  Opened #3504.

---

*[drake/systems/framework/system.h, line 398 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1nsmMQnUuqYp4tftO:-KS1nsmMQnUuqYp4tftP:b-z82v2x) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L398)):*
> ```objc
>     int port_number = get_num_output_ports();
>     output_ports_.emplace_back(
>         this, kOutputPort, port_number, type, size, sampling);
> ```

Good catch.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1_vbqpENwmxpgTsWA:-KS1qpk3z-UEGAJRxBU0:bms6ifc) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I agree, catching exceptions is scary and we shouldn't do it, even if the `catch` branch immediately aborts, as it does here.  However, this code makes me wonder if there are use cases `drake_assert.h` isn't currently meeting, and if so, how we should meet them.  Opened #3504.
</details>
I thought that also but I also wanted to provide some useful throw when this situation occurred. What do you guys propose for this PR? Should I just remove the try/catch block? 

---

*[drake/systems/framework/system.h, line 398 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1nsmMQnUuqYp4tftO:-KS1r6PuEYwGPZrmrGAz:b-90rxni) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L398)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Good catch.  Thanks!
</details>
of course!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1_vbqpENwmxpgTsWA:-KS2K4ZQM_R_ptnybCyH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > Should I just remove the try/catch block?
> 
> Yes, that's what I'd propose.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Comment by jwnimmer-tri** [comment]
Thanks for the fixup.

FWIW -- the change looks good to me now, though (apparently) lacks unit test coverage.  That's for the feature / platform reviewer to decide though.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS2MaBYrNk5CLzdmZ-6:b-mpaqlq)*

**Comment by david-german-tri** [comment]
I agree, test coverage would be good.  I'd be fine with adding it to`constant_value_source_test.cc`, where it should be a one-liner.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS2dYW7Bp2WNCMK6O8s:b-w6tn86)*

**Comment by sherm1** [comment]
Platform review: Needs a tiny unit test addition; otherwise :lgtm:.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 383 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS3ZZJIWsKDJK_Xfvgk:-KS3ZZJJg7qP0n_VOnGF:b6piz8d) ([raw file](https://github.com/robotlocomotion/drake/blob/017d5acf2bbb4766bd296f03b6f1890a43b6e5c1/drake/systems/framework/system.h#L383)):*
> ```objc
>   /// to the output topology.
>   /// @return descriptor of declared port.
>   const SystemPortDescriptor<T>& DeclareOutputPort(PortDataType type, int size,
> ```

Please add a unit test that declares an output port with given parameters and verifies that they were all passed through correctly. David suggested just adding it to `constant_value_source_test.cc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS3Zx3cI_weWy8Zv8mn:b-yssoet)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Comment by amcastro-tri** [comment]
I just added the appropriate checks in `ConstantValueSource<T>::EvalOutput()` that would otherwise fail in Debug builds (I checked) if it wasn't for the fix in this PR. PTAL.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 383 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS3ZZJIWsKDJK_Xfvgk:-KS4JGnaWtMpMJDzrfIy:b-omovm4) ([raw file](https://github.com/robotlocomotion/drake/blob/017d5acf2bbb4766bd296f03b6f1890a43b6e5c1/drake/systems/framework/system.h#L383)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Please add a unit test that declares an output port with given parameters and verifies that they were all passed through correctly. David suggested just adding it to `constant_value_source_test.cc`.
</details>
Added checks in `ConstantValueSource<T>::EvalOutput()`. Those checks fail in Debug builds without the fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS4J5P3xBHI9dehcTxz:b-nxrqp9)*

**Comment by sherm1** [comment]
:lgtm: -- waiting for @david-german-tri acks.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/system.h, line 383 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS3ZZJIWsKDJK_Xfvgk:-KS4oTaon0hAJjonrghV:brujztc) ([raw file](https://github.com/robotlocomotion/drake/blob/017d5acf2bbb4766bd296f03b6f1890a43b6e5c1/drake/systems/framework/system.h#L383)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Added checks in `ConstantValueSource<T>::EvalOutput()`. Those checks fail in Debug builds without the fix.
</details>
OK, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-:-KS4oYbiLZB0s2Ly0XFc:b-yhmnve)*

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3486#-KS1_vbqpENwmxpgTsWA:-KS7fLLvZKAUqwQLXNdZ:b1n7n2f) ([raw file](https://github.com/robotlocomotion/drake/blob/a8744841e9b6fa68832868f5dc4fbb73e4b003c5/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Done.
</details>
@david-german-tri?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3486)*

**Pull request merged**
