### PR TITLE
Python bindings for LcmPublisherSystem and Simulator

### PR DESCRIPTION
**Pull request by mposa**
Add python bindings for `LcmPublisherSystem` with `TriggerTypeSet` and `Simulator.set_publish_at_initialization`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)

### CODE REVIEW

**Comment by mposa** [comment]
@EricCousineau-TRI  for review, if you could

**Review by mposa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/_lcm_extra.py, line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16762#-MxtZeIyCu39XlKaNJSD:-MxumydIAl4_zfvsqNKg:bucky0h) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac87b8a3d9c5a1ec53c83a1e8695839c4521141/bindings/pydrake/systems/_lcm_extra.py#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Confirmed that in C++ it is an overload:
https://github.com/RobotLocomotion/drake/blob/9849045c07b73e9b0b023599f99d53a122d87254/systems/lcm/lcm_publisher_system.h#L110-L119

To that extent, I believe we should try to reflect that this is an overload and keep this option with `LcmPublisherSystem.Make()`.

Options:
- Require `publish_triggers` be kwargs-only for now - my recommendation
- Somehow expose the overload using `@overload` (which TBH I've never used, not sure if it's functional or just for `typing`, and not sure if we have example in Drake)
- Do manual overloading in pure Python (e.g. use `Make(*args...)`, and check `isinstance(args[4], ...)`) - eww

For first option, I'd recommend adding `*, publish_triggers=None`. Then inside code, use `if publish_trigger is not None: ... else: ...`
(ideally, we'd be able to use `*args, **kwargs` to directly pass... however, `use_cpp_serializer` is not kwargs-only :crying_cat_face:)

WDYT?
</blockquote></details>

Done (I think).
___
*[bindings/pydrake/systems/analysis_py.cc, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16762#-Mxt_0Kk77lWBxsNhdSt:-MxunzOG7J9Hvo7qWcW2:b1a2eif) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac87b8a3d9c5a1ec53c83a1e8695839c4521141/bindings/pydrake/systems/analysis_py.cc#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Existing defect: Surround bindings need `py::arg()` - no need to fix that here unless you want.

New defect: `set_publish_at_initialization` should have `py::arg("publish")`, and that should be used in unittest (change test code to use `simulator.set_publish_at_initialization(publish=True)`).

Can you add that in?
</blockquote></details>

Added the `py::arg`, but not sure what you meant about a unittest. I hope this binding doesn't also require a unit test.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @mposa)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16762#-MxvFXMLC7fMcqT4n049:-MxvFXMMCaNS2Rfh_rHJ:bua8v2c) (no related file):*
Working: Will make meta-PR w/ suggested changes.

---
___
*[bindings/pydrake/systems/_lcm_extra.py, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16762#-MxvEv8T3si8HHCfj2Ld:-MxvEv8T3si8HHCfj2Le:bxgfidk) ([raw file](https://github.com/robotlocomotion/drake/blob/3816ab8e9604f0d93ea738d7313305574d212cee/bindings/pydrake/systems/_lcm_extra.py#L57)):*
> ```Python
> def _make_lcm_publisher(
>         channel, lcm_type, lcm, publish_period=0.0, use_cpp_serializer=False,
>          publish_triggers=None):
> ```

nit It may be a bit odd to have `publish_triggers` after `use_cpp_serializer`.

Can you make this kwarg only? e.g.



_Suggestion:_
```Python
def _make_lcm_publisher(
        channel, lcm_type, lcm, publish_period=0.0, use_cpp_serializer=False,
        *, publish_triggers=None):
```
___
*[bindings/pydrake/systems/analysis_py.cc, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16762#-Mxt_0Kk77lWBxsNhdSt:-MxvFSCDC3fJ4WISvKZk:b-9k97f4) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac87b8a3d9c5a1ec53c83a1e8695839c4521141/bindings/pydrake/systems/analysis_py.cc#L178)):*
<details><summary><i>Previously, mposa (Michael Posa) wrote…</i></summary><blockquote>

Added the `py::arg`, but not sure what you meant about a unittest. I hope this binding doesn't also require a unit test. 
</blockquote></details>

By convention, we place `py::arg` immediately after bound functions; see examples in:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html
Can you move it there?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @mposa)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16762#-MxvFXMLC7fMcqT4n049:-MxvI2JR-NhwojWzdpPK:b-7swx1) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will make meta-PR w/ suggested changes.
</blockquote></details>

See: https://github.com/mposa/drake/pull/31

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @mposa)

___
*[bindings/pydrake/systems/_lcm_extra.py, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16762#-MxvEv8T3si8HHCfj2Ld:-MxvI6nS4qDQOIZKI2lm:b-f0muof) ([raw file](https://github.com/robotlocomotion/drake/blob/3816ab8e9604f0d93ea738d7313305574d212cee/bindings/pydrake/systems/_lcm_extra.py#L57)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It may be a bit odd to have `publish_triggers` after `use_cpp_serializer`.

Can you make this kwarg only? e.g.
</blockquote></details>

FYI I handled this (and testing) in meta-PR.
___
*[bindings/pydrake/systems/analysis_py.cc, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16762#-Mxt_0Kk77lWBxsNhdSt:-MxvI9h7AtW5aOB3wZGc:b-f0muof) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac87b8a3d9c5a1ec53c83a1e8695839c4521141/bindings/pydrake/systems/analysis_py.cc#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

By convention, we place `py::arg` immediately after bound functions; see examples in:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html
Can you move it there?
</blockquote></details>

FYI I handled this (and testing) in meta-PR.

**Review by mposa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/analysis_py.cc, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16762#-Mxt_0Kk77lWBxsNhdSt:-MyDIHFm59qFIrm75Gb2:b-3ab0va) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac87b8a3d9c5a1ec53c83a1e8695839c4521141/bindings/pydrake/systems/analysis_py.cc#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI I handled this (and testing) in meta-PR.
</blockquote></details>

I merged your PR in, thank you!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, thanks! (sorry for delay, was out last week)
+@ggould-tri for platform review, please!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762#-:-MyhGakg3iPKNQmtzn5N:b-bzsr16)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+(release notes: yes) +(component: pydrake)
:lgtm: 

> Reviewed 1 of 3 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16762#-:-MyhnB431vWp_xa1Z5QA:by7oc77)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mposa)

**Pull request merged**
