### PR TITLE
Determine if a polynomial is even or odd.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021#-:-N0WRYcM-QyauHCuaCPo:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm: with a few minor comments

+@sammy-tri for platform review please

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021#-:-N0bPllh6A58B5m94yqe:b-c9ik07)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai and @sammy-tri)

___
*[`common/symbolic_polynomial.cc` line 780 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0b-jF9-zKfW6C6l009:-N0b-jF9-zKfW6C6l00A:bjatg3f) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L780)):*
> ```cpp
>     // If we check p is even/odd, then we only need to check monomials with
>     // odd/even-degrees have coefficient = 0
>     if (monomial.total_degree() % 2 == check_even ? 1 : 0) {
> ```

Minor, isn't this equivalent to `if (monomial.total_degree() % 2 == check_even)`?



_Code quote:_
```cpp
if (monomial.total_degree() % 2 == check_even ? 1 : 0)
```
___
*[`common/symbolic_polynomial.cc` line 782 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0aX8663-gs02QGqx7w:-N0aX8663-gs02QGqx7x:bqq5mef) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L782)):*
> ```cpp
>     if (monomial.total_degree() % 2 == check_even ? 1 : 0) {
>       const symbolic::Expression& coeff_expanded =
>           coeff.is_expanded() ? coeff : coeff.Expand();
> ```

BTW, I think [the Expand() method](https://github.com/RobotLocomotion/drake/blob/256d7f6a3b73485f8795113b005b4b81cbe7bf54/common/symbolic_expression.cc#L210) already does this check.
___
*[`common/test/symbolic_polynomial_test.cc` line 1161 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0b786DADOgLyyitK_4:-N0b786DADOgLyyitK_5:b1amkta) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/test/symbolic_polynomial_test.cc#L1161)):*
> ```cpp
>   EXPECT_FALSE(p.IsOdd());
> 
>   // 1 -> a+1
> ```

Minor: I find this notation a little confusing. Would `p = (a+1)` or `p = (a+1) * x^0` be equivalent/better?



_Code quote:_
```cpp
  // 1 -> a+1
```
___
*[`common/test/symbolic_polynomial_test.cc` line 1166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0b7XLkASDCGbBpAU35:-N0b7XLkASDCGbBpAU36:bsrmc4g) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/test/symbolic_polynomial_test.cc#L1166)):*
> ```cpp
>   EXPECT_FALSE(p.IsOdd());
> 
>   // x - > 1
> ```

Minor: as above, how about `p = x`?

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.cc` line 780 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0b-jF9-zKfW6C6l009:-N0bopqC7hEXnTvqXJla:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L780)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Minor, isn't this equivalent to `if (monomial.total_degree() % 2 == check_even)`?
</blockquote></details>

Done, good call.
___
*[`common/symbolic_polynomial.cc` line 782 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0aX8663-gs02QGqx7w:-N0bnPiWBbyAPurJTIXG:bi23k97) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L782)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, I think [the Expand() method](https://github.com/RobotLocomotion/drake/blob/256d7f6a3b73485f8795113b005b4b81cbe7bf54/common/symbolic_expression.cc#L210) already does this check.
</blockquote></details>

Right, but if I call `coeff_expanded = coeff.Expand()` I think it would involve a copy constructor as `Expand()` function doesn't return a reference. While by using this ternary operator here, when `coeff.is_expanded() = true`, `coeff_expanded` is a reference to `coeff`, thus avoiding the copy

**Comment by aykut-tri** [comment]
*[`common/symbolic_polynomial.cc` line 782 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0aX8663-gs02QGqx7w:-N0bpQj50ysvCu2itPrK:b-1lje8n) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L782)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Right, but if I call `coeff_expanded = coeff.Expand()` I think it would involve a copy constructor as `Expand()` function doesn't return a reference. While by using this ternary operator here, when `coeff.is_expanded() = true`, `coeff_expanded` is a reference to `coeff`, thus avoiding the copy
</blockquote></details>

Gotcha, thanks for the explanation.

**Comment by jwnimmer-tri** [comment]
*[`common/symbolic_polynomial.cc` line 782 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0aX8663-gs02QGqx7w:-N0bpWrpENtWGHs5t-AY:b-a1nyye) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L782)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Gotcha, thanks for the explanation.
</blockquote></details>

Calling `Expression::Expand` on an already-expanded Expression copies only the `shared_ptr` to the cell (in other words, it increases the cell's ref count).  Incrementing the ref count isn't free, but it _should_ be relatively fast.  It's definitely not duplicating the entire expression tree.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021#-:-N0buP7g3o3YzXdFHqYI:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17021)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.cc` line 782 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17021#-N0aX8663-gs02QGqx7w:-N0c4xTZ2Vy8gi3DgH7O:b-ag72f1) ([raw file](https://github.com/robotlocomotion/drake/blob/5f598ddb0471b8c82094def34e4bf93155b41fee/common/symbolic_polynomial.cc#L782)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Calling `Expression::Expand` on an already-expanded Expression copies only the `shared_ptr` to the cell (in other words, it increases the cell's ref count).  Incrementing the ref count isn't free, but it _should_ be relatively fast.  It's definitely not duplicating the entire expression tree.
</blockquote></details>

I see, I forgot that `Expression` only stores the shared pointer to the cell, thanks for the explanation.

**Pull request merged**
