### PR TITLE
Add C++ protocol buffers to Drake. Use them for alias groups.

### PR DESCRIPTION
**Pull request by david-german-tri**
Migrate QPInverseDynamicsForHumanoids off of CMake, so that we don't have to figure out how to get protobufs into the CMake build.

@siyuanfeng-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5014)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Recommended order of review: 

1. `alias_groups.proto`
2. `valkyrie.alias_groups`
3. `rigid_body_tree_alias_groups.{cc,h}`
4. `rigid_body_tree_alias_groups_test`
5. The remaining `.cc` call sites.
6. All the BUILD files

**Comment by siyuanfeng-tri** [comment]
looks so much simpler. thanks david! 
i tried the qp locally with gurobi, and it seems fine. i haven't tried to bazel examples/Valkyrie or kuka yet. so i have not tried it with snopt. 
:lgtm: 

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/alias_groups.proto, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcK2gUEZyAfD5PEnxE7:-KcK2gUEZyAfD5PEnxE8:bsyq88w) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/alias_groups.proto#L27)):*
> ```protobuf
>     // appear twice in a given group, but a member may appear in multiple
>     // different groups.
>     repeated AliasGroup body_group = 2;
> ```

Is the uniqueness of member within a group enforced by proto? or do I need to check it on my side? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcK3H0wyNKfevmJbsBJ:biyncgc)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/alias_groups.proto, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcK2gUEZyAfD5PEnxE7:-KcKOSOBAhG3_GHwfc6S:btlr3no) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/alias_groups.proto#L27)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Is the uniqueness of member within a group enforced by proto? or do I need to check it on my side? 
</blockquote></details>

It is not enforced by proto.  I don't think I deleted any enforcement logic from the C++ side, though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review.  Jumping the queue for a somewhat complicated piece of Bazel.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcKOuGm_UsrbeW0By5X:b-4wzzwp)*

**Comment by jwnimmer-tri** [comment]
Small checkpoint.

---

Reviewed 16 of 23 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOhk5StLzoIejLwXv8:-KcOhk5StLzoIejLwXv9:b6czj11) ([raw file](https://github.com/robotlocomotion/drake/blob/9ce009877661c163727ae1c2be75e9112e06f89e/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L1)):*
> ```CMake
> add_library(drakeQPControllerCommon qp_controller_common.cc)
> ```

People may wonder why CMake infrastructure is absent from this example.  Maybe add a README.md note?

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOj9qjDVovguO0Puio:-KcOj9qjDVovguO0Puip:bm944pa) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc#L12)):*
> ```cpp
> namespace param_parsers {
> 
> const char* kTestDir =
> ```

Missing a const : `const char* const kFoo = "";`, otherwise this is a write-able global.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcOizKwM5J6jutpmCqY:bkqwryg)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 23 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOn0O4WyaomjpDq0qO:-KcOn0O5LUFX2y9UqCFx:bts0kc5) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc#L3)):*
> ```cpp
> #include "drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.h"
> 
> #include <fcntl.h>
> ```

BTW Gross, but whatever I guess.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOmch6fMzU9py_mM8w:-KcOmch6fMzU9py_mM8x:b-lk9qs5) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc#L112)):*
> ```cpp
>     const std::string& config) {
>   AliasGroups alias_groups;
>   google::protobuf::io::FileInputStream istream(open(config.data(), O_RDONLY));
> ```

BTW really, protobufs?  We have to use a filedes, and you don't even RAII close it for us?  Maybe these three lines deserve a wrapper-helper function, if we want people to use textconfig files more widely in Drake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014)*

**Comment by jwnimmer-tri** [comment]
First pass done.

---

Reviewed 5 of 23 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/BUILD, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOnt2SwMwctTaccdR8:-KcOnt2SwMwctTaccdR9:b-sajnks) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/BUILD#L24)):*
> ```Python
> exports_files(
>     ["config/valkyrie.alias_groups"],
>     visibility = [":__subpackages__"],
> ```

Unclear why sometimes we `visibility=subpackages` on certain targets here, but not others, when the BUILD-file default is already subpackages?

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOorJxTgef6z78DTRL:-KcOorJxTgef6z78DTRM:b4uqjck) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD#L23)):*
> ```Python
>     linkstatic = 1,
>     deps = [
>         "@yaml_cpp//:lib",
> ```

BTW Is this still true?  I guess yes, because only one of the parses is ported so far?

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOoKbvQSZVXZsc1Tl3:-KcOoKbvQSZVXZsc1Tl4:b-akgqsf) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD#L34)):*
> ```Python
>         "alias_groups.proto",
>     ],
> )
> ```

BTW I think its correct that we don't use drake_cc... here, because mostly we don't want extra warning flags.  But are there any meaningful flags that we're losing (or will lose) because of it?  Is there doc on drake.bzl saying to add only diagnostic flags there, not things like `-g` or whatever?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcP8NqY0IpqOi53cX64:b-te4kzy)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOorJxTgef6z78DTRL:-KcP9ZHiuTI5gEx4ephO:btp60nh) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this still true?  I guess yes, because only one of the parses is ported so far?
</blockquote></details>

you are correct. i will port the other later. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014)*

**Comment by david-german-tri** [comment]
Review status: 21 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/BUILD, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOnt2SwMwctTaccdR8:-KcPu02FrNY1kmoKN7Ro:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/BUILD#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why sometimes we `visibility=subpackages` on certain targets here, but not others, when the BUILD-file default is already subpackages?
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOhk5StLzoIejLwXv8:-KcPuIE5sOvXHwmYv0RT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ce009877661c163727ae1c2be75e9112e06f89e/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

People may wonder why CMake infrastructure is absent from this example.  Maybe add a README.md note?
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOoKbvQSZVXZsc1Tl3:-KcPuM9p80ONK0X849el:bkzs6km) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/BUILD#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think its correct that we don't use drake_cc... here, because mostly we don't want extra warning flags.  But are there any meaningful flags that we're losing (or will lose) because of it?  Is there doc on drake.bzl saying to add only diagnostic flags there, not things like `-g` or whatever?
</blockquote></details>

Yeah, flags that should apply to externals and external rules should flow from the CROSSTOOL, as `-g` for instance does (controlled by e.g. `-c dbg`).  I'll document that in `drake.bzl` in a follow-up PR.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOmch6fMzU9py_mM8w:-KcPvF9jaegDYcQxUL6V:buikbwh) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/rigid_body_tree_alias_groups.cc#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW really, protobufs?  We have to use a filedes, and you don't even RAII close it for us?  Maybe these three lines deserve a wrapper-helper function, if we want people to use textconfig files more widely in Drake.
</blockquote></details>

Agreed -> #5094.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-KcOj9qjDVovguO0Puio:-KcPwN3mOUKVFEYUB9Zk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d58b7d73be2f760726189161b6c6d029e6112f4c/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/rigid_body_tree_alias_groups_test.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing a const : `const char* const kFoo = "";`, otherwise this is a write-able global.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014)*

**Comment by jwnimmer-tri** [comment]
My first pass was slightly rushed; I will do another read this evening and post back soon.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcQ07Tn4lZZJTV-AUv9:bs7iz7l)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

On second read, what would have made this PR less confusing for me was if the pre-existing code was Bazel'ified in a first PR, and then the TextFormat feature was in a second PR.  Teasing apart the bazelification from the feature ended up as a mental tax.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5014#-:-KcQ9gG4EY4QcB-HClQ_:bcts7r9)*

**Comment by jwnimmer-tri** [comment]
"UNSTABLE DUE TO GIT FAILURES"
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Pull request merged**
