### PR TITLE
Replace Isometry3<T>::rotation() with Isometry3<T>::linear() everywhere

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR replaces all calls `Isometry3<T>::rotation()` with `Isometry3<T>::linear()`.
It happens that `Isometry3<T>::rotation()`  seems to be **computing** the rotational part of a general isometry (which could include for instance shear ans scaling) and therore incurs in unnecessary overhead for our typical transformations.

Whether we like it or not, the zero-cost accessor to our "rotational part" is `Isometry3<T>::linear()`.

In the MultibodyTree code this lead to a 3x speed up. I didn't check in other places.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6989)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-KtTYf7loXS1B-oxovz_:b-4269ug)*

**Comment by sherm1** [comment]
> In the MultibodyTree code this lead to a 3x speed up.

Wow!

**Comment by amcastro-tri** [comment]
@ericcousineau-tri, any ideas on why this small change would affect the results of `articulated_icp_test.cc`?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-KtThqsOISSa01T2nsYh:b-cn4omz)*

**Comment by SeanCurtis-TRI** [comment]
If I were to have any concern about this, it's that using `linear()` in place of `rotation()` is akin to assuming that an input vector is normalized. Obviously, if the assumption is correct, you save redundant renormalization. However, if the assumption is wrong, then your downstream code loses an invariant.

In this case, you've exchanged the calls, but I don't particularly see any mechanisms in the code that guarantee that using `linear()` satisfies the requirement to be a rotation matrix. I'd feel *a lot* more comfortable if there was, at least, a `DRAKE_ASSERT` coupled with these changes that confirmed the orthonormality of `linear()`.

That said, I couldn't resist peeking into `articulated_icp_test.cc`. What's interesting is that the `rotmat2rpy()` and `rpy2rotmat()` methods are nicely invertible (at least for the values provided in the failing test). However, when passing in the rotation matrix created by `rotation()`, the resulting rpy value varies in the y- and z-values to the order of 1e-16 and 1e-17, respectively. This is because the rotation matrices differ ever so slightly. However, both matrices would pass any reasonable test of orthonormality, so such a guard may not produce significant value.

Thoughts?

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-KtWyDij5EbOqc_qtkOu:b2anpq7)*

**Comment by sherm1** [comment]
It seems safe to me to assume that an Isometry3 contains an orthogonal unit rotation, if it is being used correctly, since that is an inherent property of an isometry. So as long as we only do isometry.linear() and not general transform.linear() I think we are OK.

> Thoughts?

You mean in general? OK, since you asked ... I despise Eigen's Isometry class and its lack of rotation matrix and unit vector classes. I think we should consider writing our own Transform and Rotation classes that behave in a civilized fashion instead, with appropriate behavior contracts that guarantee preservation of orthogonality and unity, and lovely interaction with our spatial vector classes. However I don't think these are going to get to the top of anyone's priority list in the near future so using isometry.linear() at least will allow us to get reasonable performance out of this clunky object.  

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-KtXpMjGdfXBt-me69Lb:bhu0shu)*

**Comment by EricCousineau-TRI** [comment]
Sorry for the late follow-up, but given Sean and Sherm's analysis, it seems like it'd be appropriate to just increase the tolerance on the test for the time being, if using `math::rotmat2rpy(setup.X_WB.linear())`. On line 102, you can double the cost, from `zero_cost_tolerance_ = 1e-4` to `2e-4`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-Ku4xiCUOmKaCwuJp1yc:b-lrf6fz)*

**Comment by sherm1** [comment]
Plaform :lgtm: pending successful CI. @ericcousineau-tri's proposed fix would be fine with me.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-Ku58QuU3bjrcxPyWoEg:b6mntpb)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Pending CI fix as per @ericcousineau-tri's recommendation.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-Ku59ZIj84AWq6TYSamA:b-4xyo2i)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6989#-:-KuQ5Tp6t_MvotGqfBzf:b-s794vx)*

**Pull request merged**
