### PR TITLE
Add torque values to iiwa commands

### PR DESCRIPTION
**Pull request by sammy-tri**
Add fields to the iiwa command lcm message to (optionally) specify joint torque.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2790)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@liangfok for feature review
+@david-german-tri for platform review (happy Tuesday!)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-:-KMVOZViijsOEMvc_Hj1:1347531549)*

**Comment by liangfok** [comment]
Done with initial review. Just a few comments / questions.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcmtypes/lcmt_iiwa_command.lcm, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-KMVY6jrym6Lu7_Yz0-v:-KMVY6jrym6Lu7_Yz0-w:1252518710) ([raw file](https://github.com/robotlocomotion/drake/blob/f370eceb886401a2ecddf73644f69a96488979bf/drake/lcmtypes/lcmt_iiwa_command.lcm#L12)):*
> ```
>   double joint_position[num_joints];
> 
>   // Torque values should only be sent when the arm is in torque command mode.
> ```

I believe "torque control mode" is a more commonly used terminology.

Also, to be consist with the joint positions comment above, consider changing "Torque values" to be "Joint torques".

---

*[drake/lcmtypes/lcmt_iiwa_command.lcm, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-KMV__Q4RmjOf-QxC60k:-KMV__Q4RmjOf-QxC60l:1100102741) ([raw file](https://github.com/robotlocomotion/drake/blob/f370eceb886401a2ecddf73644f69a96488979bf/drake/lcmtypes/lcmt_iiwa_command.lcm#L13)):*
> ```
> 
>   // Torque values should only be sent when the arm is in torque command mode.
>   int32_t num_torques;
> ```

On the IIWA robot, will the number of torques ever differ from the number of joints? If not, consider combining `num_joints` with `num_torques` to be a single `num_states`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-:-KMVa0oZZ77ljHOtv086:1438491754)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcmtypes/lcmt_iiwa_command.lcm, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-KMVY6jrym6Lu7_Yz0-v:-KMVxVOA86ONfjE2kqW5:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f370eceb886401a2ecddf73644f69a96488979bf/drake/lcmtypes/lcmt_iiwa_command.lcm#L12)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I believe "torque control mode" is a more commonly used terminology.
> 
> Also, to be consist with the joint positions comment above, consider changing "Torque values" to be "Joint torques".
</details>
Done.

---

*[drake/lcmtypes/lcmt_iiwa_command.lcm, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-KMV__Q4RmjOf-QxC60k:-KMVxWAcDMyvOxr4_xey:-1396019247) ([raw file](https://github.com/robotlocomotion/drake/blob/f370eceb886401a2ecddf73644f69a96488979bf/drake/lcmtypes/lcmt_iiwa_command.lcm#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> On the IIWA robot, will the number of torques ever differ from the number of joints? If not, consider combining `num_joints` with `num_torques` to be a single `num_states`.
</details>
Clarified comment to indicate when num_torques and num_joints would be different.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2790)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-:-KMWULjO_YSE8ueqSGnz:-1868698381)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2790#-:-KMZRRfNrNzGV0PboxY6:1417088721)*

**Pull request merged**
