### PR TITLE
Fix some integer size mismatch warnings on Windows.

### PR DESCRIPTION
**Pull request by sherm1**
These warnings were bothering me on Windows. I made minimal changes to make the warnings go away.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2815)

### CODE REVIEW

**Comment by sherm1** [comment]
+@ggould-tri for feature and platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-:-KMh99l32jxcIhYe06wU:1175901599)*

**Comment by ggould-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/inverseKin.cpp, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYLnNpughA8sPDm0-:-KMiYLnNpughA8sPDm00:1453674055) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/inverseKin.cpp#L51)):*
> ```cpp
>   auto results = IKResults();
>   results.q_sol.resize(q_nom.size());
>   int num_constraints = (int)constraint_array.size();
> ```

C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 947 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYXrc9WCS0dw3NX6v:-KMiYXrc9WCS0dw3NX6w:1453674055) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L947)):*
> ```cpp
>   double m = 0.0;
> 
>   for (int i = 0; i < (int)bodies.size(); i++) {
> ```

C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1675 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYYLIzKVnXuy-4ouI:-KMiYYLJwCNzYM6PEIbO:1453674055) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1675)):*
> ```cpp
>   int match_index = -1;
> 
>   for (int ii = 0; ii < (int)bodies.size(); ++ii) {
> ```

C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1741 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYZK4B4TOVFKTMY0E:-KMiYZK4B4TOVFKTMY0F:1453674055) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1741)):*
> ```cpp
>   int match_index = -1;
> 
>   for (int ii = 0; ii < (int)frames.size(); ++ii) {
> ```

C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 262 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMimQhzvqIKWBFlG1Ap:-KMimQhzvqIKWBFlG1Aq:-1560912647) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodySystem.cpp#L262)):*
> ```cpp
> 
>   y.segment(0, getNumStates()) << x;
>   Eigen::Index index = getNumStates();
> ```

`getNumStates` is not an Eigen method, and does not return an `Eigen::Index` (it returns `size_t`), so abusing that type here to mean "large integer" is inappropriate.  One appropriate fix is to cast to int, as with other places in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/inverseKin.cpp, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYLnNpughA8sPDm0-:-KMj4kTiUrNuovcpVYM9:-313365898) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/inverseKin.cpp#L51)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.
</details>
I know that but I want to attempt an argument that we should use C-style casts specifically in these integer-to-integer lossy conversion cases. The meaning is cliched and very clear to readers, I think. IMO the static_cast here adds noise and obfuscation but no clarity and no useful static verification. It is particularly ugly in the common loop index use:
```c++
for (int i=0; i < static_cast<int>(mything.size(); ++i) {}
// vs
for (int i=0; i < (int)mything.size(); ++i) {}
```
I will change this if you or anyone else feels strongly about it, but I think it might be a case of pedantic adherence to the style guide that actually makes the code harder to read.

I am in total agreement that `static_cast<SomeClass>(thing)` should be used always rather than `(SomeClass)thing` but I think C is OK for integers. OK, argument made. Your thoughts?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 947 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYXrc9WCS0dw3NX6v:-KMj8Ua0Uqy8feYAGRYe:1080885666) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L947)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.
</details>
see attempted rebuttal above ...

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1675 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYYLIzKVnXuy-4ouI:-KMj8_5dRtSrLk9DqaqN:1080885666) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1675)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.
</details>
see attempted rebuttal above ...

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1741 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYZK4B4TOVFKTMY0E:-KMj8_r7eIKe7rhi5ihI:1080885666) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1741)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> C-style casts are dis-preferred by the style guide; prefer `static_cast<int>`.
</details>
see attempted rebuttal above ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/inverseKin.cpp, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYLnNpughA8sPDm0-:-KMj9LaqNC_Whb9SMdXf:-1752284388) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/inverseKin.cpp#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I know that but I want to attempt an argument that we should use C-style casts specifically in these integer-to-integer lossy conversion cases. The meaning is cliched and very clear to readers, I think. IMO the static_cast here adds noise and obfuscation but no clarity and no useful static verification. It is particularly ugly in the common loop index use:
> ```c++
> for (int i=0; i < static_cast<int>(mything.size(); ++i) {}
> // vs
> for (int i=0; i < (int)mything.size(); ++i) {}
> ```
> I will change this if you or anyone else feels strongly about it, but I think it might be a case of pedantic adherence to the style guide that actually makes the code harder to read.
> 
> I am in total agreement that `static_cast<SomeClass>(thing)` should be used always rather than `(SomeClass)thing` but I think C is OK for integers. OK, argument made. Your thoughts?
</details>
https://google.github.io/styleguide/cppguide.html#Casting

I think it is clear on the debate, and I don't think this example merits overruling it.

If int-vs-size_t `for` loops are more gross looking because of this, I am glad.  We should strongly prefer for-range loops when possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815)*

**Comment by sherm1** [comment]
All reviewer comments addressed, PTAL.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/inverseKin.cpp, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYLnNpughA8sPDm0-:-KMjHRES3IK8uk7I5ZLE:-524620829) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/inverseKin.cpp#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> https://google.github.io/styleguide/cppguide.html#Casting
> 
> I think it is clear on the debate, and I don't think this example merits overruling it.
> 
> If int-vs-size_t `for` loops are more gross looking because of this, I am glad.  We should strongly prefer for-range loops when possible.
</details>
Done. While I love range-for, it isn't helpful when you need an index, which is a common occurrence. But I stand reformed on the C-style int casts!

---

*[drake/systems/plants/RigidBodySystem.cpp, line 262 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMimQhzvqIKWBFlG1Ap:-KMj84DOTMIUS-wTbXSN:490766442) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodySystem.cpp#L262)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `getNumStates` is not an Eigen method, and does not return an `Eigen::Index` (it returns `size_t`), so abusing that type here to mean "large integer" is inappropriate.  One appropriate fix is to cast to int, as with other places in this PR.
</details>
Done. The warning wasn't actually on this line, it comes from the `index +=` three lines later. `int` here causes that warning. However, `size_t` is silent in Win64 -- apparently even microsoft doesn't feel compelled to warn about squeezing a ptrdiff_t into a size_t (I guess because all the bits will fit even if they change meaning). 

---

*[drake/systems/plants/RigidBodyTree.cpp, line 947 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYXrc9WCS0dw3NX6v:-KMjK4BZhyoA7TyEgZle:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L947)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> see attempted rebuttal above ...
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1675 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYYLIzKVnXuy-4ouI:-KMjK5otgXzQEVtyfFns:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1675)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> see attempted rebuttal above ...
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1741 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-KMiYZK4B4TOVFKTMY0E:-KMjK7jHEem3yS7-_UmG:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8e73b464d29376bb1e429d794d19f9bc73c662fe/drake/systems/plants/RigidBodyTree.cpp#L1741)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> see attempted rebuttal above ...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-:-KMjKJ4zZDhwNJIIpaSB:-1030920307)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2815#-:-KMjKnDhP9GFp6hbYtuz:1417088721)*

**Pull request merged**
