### PR TITLE
Revert "fastQP test"

### PR DESCRIPTION
**Pull request by jamiesnape**
Dear @RussTedrake,

The on-call build cops believe that your PR #3501 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
*  [linux-gcc-continuous-matlab-open-source](https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-matlab-open-source/804/) (Jenkins)
* [linux-gcc-continuous-matlab-open-source](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-gcc-continuous-matlab-open-source-804&field2=buildstarttime&compare2=84&value2=now) (CDash)
* [linux-gcc-ninja-continuous-matlab-open-source](https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-ninja-continuous-matlab-open-source/710/) (Jenkins)
* [linux-gcc-ninja-continuous-matlab-open-source](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-gcc-ninja-continuous-matlab-open-source-710&field2=buildstarttime&compare2=84&value2=now) (CDash)

Therefore, the build cops have created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now (12:15 PM ET). You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cops for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cops to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
@jamiesnape on behalf of Your Friendly Oncall Build Cops

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3716)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
I will let build cops @siyuanfeng-tri and @liangfok decide if/when to merge.

FYI @david-german-tri.

**Comment by david-german-tri** [comment]
Trying to reproduce locally now.  I'm guessing this is because IPOPT doesn't converge as well as SNOPT.

**Comment by david-german-tri** [comment]
Didn't get the chance to finish reproducing this, but didn't fail to reproduce either.

Since it's a post-merge build failing on a Friday night, it won't really impact anyone until next week.  Let's hold the revert until Monday morning.

**Comment by RussTedrake** [comment]
resolved by #3712

**Comment by jamiesnape** [comment]
@david-german-tri Ok, but in future I think we should follow the build cop procedures and merge reverts in an hour. It blocked me most of Friday.

**Comment by david-german-tri** [comment]
Fair enough, I didn't consider that it would block people running specialized builds on a one-off basis.

**Comment by jamiesnape** [comment]
Not to worry. My builds would have failed anyway, unfortunately. 😭

**Pull request closed without merging**
