### PR TITLE
Add README for build-wheels

### LINKED ISSUE #16105: Document new build-wheels script
Per #16094, we need to add more detailed documentation on how to use the new Python `build-wheels` script, probably to an accompanying (i.e. in `tools/wheel`) README.

We should also consider migrating some of the "how to release wheels" instructions to this new document.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add a brief document explaining the build-wheels tool. This includes both some basic usage information, particularly more detailed descriptions and rationale for some of the arguments, as well as some brief information on the script's internal operation.

Fixes #16105.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16417)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review please.

**Comment by mwoehlke-kitware** [comment]
Rendered version may be seen [here](https://github.com/RobotLocomotion/drake/blob/220e36215e24783e146bb05ec62de799e7aa0351/tools/wheel/README.rst).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +(status: single reviewer ok) +(release notes: none).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16417#-:-Mu1S2gk43y_xTbyVFrl:bsfln9q)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[tools/wheel/README.rst, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16417#-Mu1SBUP6BR4kJXx7_qx:-Mu1SBUQ9V_Je7gkgT8E:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/220e36215e24783e146bb05ec62de799e7aa0351/tools/wheel/README.rst#L47)):*
> ```reStructuredText
>     current working directory (i.e. ``.``).
> 
> ``-n``, ``--no-extrack``
> ```

typo



_Suggestion:_
```reStructuredText
--no-extract
```

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/README.rst, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16417#-Mu1SBUP6BR4kJXx7_qx:-MuBiV8e4Ai0m9k5vei6:b8g6wuy) ([raw file](https://github.com/robotlocomotion/drake/blob/220e36215e24783e146bb05ec62de799e7aa0351/tools/wheel/README.rst#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Fixed. Good catch; thanks!

**Comment by jwnimmer-tri** [comment]
Since this changes only a README, I'll force-merge it now without waiting for CI.

**Pull request merged**
