### PR TITLE
Minor changes to inverse dynamics controller.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Attempted to template InverseDynamicsController / InverseDynamics on AutoDiffXd, but didn't quite make it all the way due to RigidBodyTree can't template on AutoDiffXd. This PR mostly removed RBT parsing from InverseDynamicsController constructors to call sites.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6363)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@liangfok for feature review, +@sherm1 for platform review. thanks! This should be fairly quick. 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6363#-:-KmmWdg-wLFy6K61Dtul:b-8kc7u7)*

**Comment by sherm1** [comment]
CI is not happy. I'll wait for feature review before looking at this.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6363#-:-Kmmf3rClEekllU7euiz:btmjkh3)*

**Comment by siyuanfeng-tri** [comment]
yeah... I just realized I can't actually template AutoDiff on RBT.... 
O well, at least I made sure all the controller code should be able to. I left some TODO there. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6363#-:-KmmjIBhntlC-SxFyeaQ:bkwcko3)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6363#-:-Kmv84Yf5HuTbua68nZt:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm: but please revise the PR description in GitHub before merging -- I don't think it is right now.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6363#-:-KnMS5Dz-LgtJnnVv0-B:b-kpuqgy)*

**Pull request merged**
