### PR TITLE
Minor clean up for Isometry3 (remove unused imports / aliases)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Related to #10982

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for both reviews, please (low priority)
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098#-:-N1AxAy52C6weoI8mbXf:b-4y5orc)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(release notes: none).

CI shows a build error.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098#-:-N1BNhRy0RMSjAmtdKaE:bx4gapp)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17098#-N1BP1TQ9Q3zUKxYoGPh):*
nit There's only one Vecor3 change in the entire PR.

(Maybe just easier to leave it alone, and keep the alias?)



_Suggestion:_
```
  Also replace one Vector3 alias with fully qualified name.
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17098#-N1BP1TQ9Q3zUKxYoGPh):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit There's only one Vecor3 change in the entire PR.

(Maybe just easier to leave it alone, and keep the alias?)
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17098)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
