### PR TITLE
Point cloud conversion

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Implemented a static member function which converts depth image from RgbdCamera to point cloud.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6055)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok feature review please. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-KjdYq3lxyCkkKUuXWmL:b-de0lq9)*

**Comment by liangfok** [comment]
Checkpoint. Before proceeding, I left some questions in the `.h` file. PTAL.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.h, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje-UqRc-Q9i9WAeDox:-Kje-UqRc-Q9i9WAeDoy:b2zxju9) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L67)):*
> ```objc
>   /// pixel in the depth image has InvalidDepth::kError depth value, all the
>   /// `(x, y, z)` values in the converted point will be InvalidDepth::kError.
>   /// Similary, if a pixel has either InvalidDepth::kTooFar or
> ```

typo: "Similarly".

---

*[drake/systems/sensors/rgbd_camera.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0-0lRfi01t-ZTbqm:-Kje0-0m_JG2qa-KaiCh:b-ovz4x0) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L69)):*
> ```objc
>   /// Similary, if a pixel has either InvalidDepth::kTooFar or
>   /// InvalidDepth::kTooClose, the converted point will be
>   /// InvalidDepth::kTooFar.
> ```

Instead of including the `kTooFar` point in the resulting point cloud, why not omit the measurement from the point cloud?

---

*[drake/systems/sensors/rgbd_camera.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje-lgIuKj5KPDHtiZN:-Kje-lgIuKj5KPDHtiZO:b-vlncyg) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L77)):*
> ```objc
>   ///
>   /// @param[out] point_cloud The pointer of output point cloud. The number of
>   /// column must be the same as the size of the input depth image.
> ```

"column" should be "columns".

---

*[drake/systems/sensors/rgbd_camera.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0I-35Uxu0Olofx10:-Kje0I-4o_stpPLey6Cn:be05b9s) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L77)):*
> ```objc
>   ///
>   /// @param[out] point_cloud The pointer of output point cloud. The number of
>   /// column must be the same as the size of the input depth image.
> ```

Since this is a mutable parameter, why not allow this method to resize it based on the number of valid points in the point cloud?

---

*[drake/systems/sensors/rgbd_camera.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje1GWAALML-Jh88DTq:-Kje1GWAALML-Jh88DTr:b-ns17bz) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L78)):*
> ```objc
>   /// @param[out] point_cloud The pointer of output point cloud. The number of
>   /// column must be the same as the size of the input depth image.
>   static void ConvertDepthImageToPointCloud(const Image<float>& depth_image,
> ```

Would it make more sense to provide this method inside `drake::systems::sensors::Image`? That would be more consistent with https://github.com/RobotLocomotion/drake/blob/21feadc14e5be6369eb6ef0f61d81e565dd54c55/drake/systems/sensors/depth_sensor_output.h#L75.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-Kje1cF86Gc28vzegsI6:b-qoozja)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/rgbd_camera.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0-0lRfi01t-ZTbqm:-Kje5V3VazHnHW2b6GIL:b3z1tx) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Instead of including the `kTooFar` point in the resulting point cloud, why not omit the measurement from the point cloud?
</blockquote></details>

It's a very good point. 

I'm not 100% sure if handling both Nan (kError) and Inf (kTooFar and kTooClose) would be really useful, but PCL is handling both [1], so I followed that convention since PCL is a defacto standard library for point cloud operation.

I tried finding why PCL is handling both cases, but couldn't find out any related documents.

[1] http://pointclouds.org/documentation/tutorials/basic_structures.php

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055)*

**Comment by kunimatsu-tri** [comment]
Thanks for reviewing. Addressed or responded your comments. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.h, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje-UqRc-Q9i9WAeDox:-Kje9l7SPr1bDMHxxccV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L67)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

typo: "Similarly".
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje-lgIuKj5KPDHtiZN:-Kje9lz8QVBoyjJYHsP6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L77)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"column" should be "columns".
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0I-35Uxu0Olofx10:-KjeBpTqBD4D2KABU-dI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L77)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Since this is a mutable parameter, why not allow this method to resize it based on the number of valid points in the point cloud?
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje1GWAALML-Jh88DTq:-KjeBq0LHknJcR9s5wwY:bmxxn0h) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L78)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Would it make more sense to provide this method inside `drake::systems::sensors::Image`? That would be more consistent with https://github.com/RobotLocomotion/drake/blob/21feadc14e5be6369eb6ef0f61d81e565dd54c55/drake/systems/sensors/depth_sensor_output.h#L75.
</blockquote></details>

I understand your point, but I hesitate to do so because this conversion is valid only for depth image while `Image` can contain any images, e.g. rgb image, label image which are unrelated to the conversion. 

That's the main difference from the case of `DepthSensorOutput`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-KjeE5FEJtRFU5Pv-qoA:b-bh9a5n)*

**Comment by liangfok** [comment]
:lgtm: My remaining comments & questions are non-blocking.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0-0lRfi01t-ZTbqm:-KjeH4HPUSknjGhH77Wk:b-8oycp0) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L69)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

It's a very good point. 

I'm not 100% sure if handling both Nan (kError) and Inf (kTooFar and kTooClose) would be really useful, but PCL is handling both [1], so I followed that convention since PCL is a defacto standard library for point cloud operation.

I tried finding why PCL is handling both cases, but couldn't find out any related documents.

[1] http://pointclouds.org/documentation/tutorials/basic_structures.php


</blockquote></details>

Consider updating the above comment to include this reasoning. Something like "Note that this matches the convention used by the Point Cloud Library (PCL)."

---

*[drake/systems/sensors/rgbd_camera.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje1GWAALML-Jh88DTq:-KjeFDwWvzax7C-9l5BG:b3zts9a) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L78)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I understand your point, but I hesitate to do so because this conversion is valid only for depth image while `Image` can contain any images, e.g. rgb image, label image which are unrelated to the conversion. 

That's the main difference from the case of `DepthSensorOutput`.
</blockquote></details>

How general are `Image` and `CameraInfo`? If they will be used by other non-`RgbdCamera` sensors, should this method be a free-floating method instead of a static member of `RgdbCamera`?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIJWVzW1DLBU8qqUq:-KjeIJWVzW1DLBU8qqUr:b-vwu1fb) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L32)):*
> ```cpp
> class DepthImageToPointCloudConversionTest : public ::testing::Test {
>  public:
>   const double kFocal = 500.f;
> ```

BTW, is that "f" necessary?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIYTVddQKc_aLx6ca:-KjeIYTVddQKc_aLx6cb:b2qdj4f) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L43)):*
> ```cpp
> 
>  protected:
>   void SetUp() override {}
> ```

BTW, is this method necessary?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIzS7V0YyFOYhKGhN:-KjeIzS7V0YyFOYhKGhO:b-k9meyh) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L55)):*
> ```cpp
> };
> 
> // Verifies output point cloud when pixel values in depth image are normal.
> ```

BTW, when I first read "normal", I was confused because I thought "how and why should they be normalized"? Consider using "valid".

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeJ6NS4ZmT4AP7invf:-KjeJ6NS4ZmT4AP7invg:bs3w1xu) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L55)):*
> ```cpp
> };
> 
> // Verifies output point cloud when pixel values in depth image are normal.
> ```

BTW, "output" is a loaded term in Drake since it's a systems framework concept. Consider replacing it with "computed".

(Same comment below.)

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeL4PxgM6GnGqGL80L:-KjeL4PxgM6GnGqGL80M:brzv8ul) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L63)):*
> ```cpp
>                                             &actual_point_cloud_);
> 
>   const float kDistanceTolerance = 1e-9;
> ```

BTW, consider adding a comment explaining how this tolerance was chosen. For example, "This tolerance was determined empirically using Drake's supported platforms."

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeK2ezRrfDozSZW-6N:-KjeK2ezRrfDozSZW-6O:b-e623wn) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L95)):*
> ```cpp
>       EXPECT_TRUE(std::isnan(actual(0)));
>       EXPECT_TRUE(std::isnan(actual(1)));
>       EXPECT_TRUE(std::isnan(actual(2)));
> ```

BTW, the documentation of `RgbdCamera::ConvertDepthImageToPointCloud()` states that the resulting point cloud will contain `InvalidDepth::kError` whereas `std::isnan()` is used here. Can this discrepancy be avoided?

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 149 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeKoUb1KRPDh7VuHTK:-KjeKoUb1KRPDh7VuHTL:bjdj6cw) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L149)):*
> ```cpp
> const double kDepthTolerance = 1e-4;
> const double kFovY = M_PI_4;
> const bool kShowWindow = false;
> ```

BTW, this looks like an important change. Should it be in its own dedicated PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-KjeLWYyqwS1rTJY-rFp:bh5tx4z)*

**Comment by kunimatsu-tri** [comment]
Addressed or responded to all the comments.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.h, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje0-0lRfi01t-ZTbqm:-Kjf_W7Cj63ypQctfSPY:bt4ox1i) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider updating the above comment to include this reasoning. Something like "Note that this matches the convention used by the Point Cloud Library (PCL)."
</blockquote></details>

Done. Thanks for the suggestion.

---

*[drake/systems/sensors/rgbd_camera.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-Kje1GWAALML-Jh88DTq:-Kjf_h2LHTpD5tio4zoO:bzc5pxi) ([raw file](https://github.com/robotlocomotion/drake/blob/8608834b5e6fc6d42444be85d92d96e8a21ebd3b/drake/systems/sensors/rgbd_camera.h#L78)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

How general are `Image` and `CameraInfo`? If they will be used by other non-`RgbdCamera` sensors, should this method be a free-floating method instead of a static member of `RgdbCamera`?
</blockquote></details>

Yes, you're right. This conversion function is general to any depth image.

The reason I place it here is:
1) there is no plan to implement other type of sensors that output depth image for now, and
2) I couldn't come up with where this should be placed if this would become just a function instead of a member function.

One idea I have in mind is to implement PointCloud class in the future and to let the class have this static member function or to move this to be the class ctor.

However, it seems too much for now, so I concluded that being `RgbdCamera`'s static member function is a good solution at this moment.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIJWVzW1DLBU8qqUq:-KjfXH5RSqeneGzvjHIf:b-8b7dn3) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L32)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is that "f" necessary?
</blockquote></details>

I meant `float` instead of `double`.

I believe adding `.f` for `float` value is acceptable.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIYTVddQKc_aLx6ca:-KjfYv89fvZt4TZrR2nh:bfbdchc) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is this method necessary?
</blockquote></details>

Yes, I think so.

If I removed that part, I've got this compile error:

```
/home/kunimatsu/work/kuni-drake/drake/build/install/include/gtest/gtest.h:430:16: error: ‘virtual void testing::Test::SetUp()’ was hidden [-Werror=overloaded-virtual]
   virtual void SetUp();
                ^
/home/kunimatsu/work/kuni-drake/drake/drake/systems/sensors/test/rgbd_camera_test.cc:44:8: error:   by ‘void drake::systems::sensors::{anonymous}::DepthImageToPointCloudConversionTest::SetUp(float)’ [-Werror=overloaded-virtual]
   void SetUp(float depth_value) {
        ^
```

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIzS7V0YyFOYhKGhN:-KjfVnnE-PsgLeV5lr5P:b-i21bbo) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, when I first read "normal", I was confused because I thought "how and why should they be normalized"? Consider using "valid".
</blockquote></details>

Thanks. Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeJ6NS4ZmT4AP7invf:-KjfcXk_E-z9R-xiZZ9G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "output" is a loaded term in Drake since it's a systems framework concept. Consider replacing it with "computed".

(Same comment below.)
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeL4PxgM6GnGqGL80L:-KjfVUEA4auv2ILZnW4H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L63)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a comment explaining how this tolerance was chosen. For example, "This tolerance was determined empirically using Drake's supported platforms."
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeK2ezRrfDozSZW-6N:-KjfUq6oSFTfNqScVZjO:bb9pl0z) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L95)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, the documentation of `RgbdCamera::ConvertDepthImageToPointCloud()` states that the resulting point cloud will contain `InvalidDepth::kError` whereas `std::isnan()` is used here. Can this discrepancy be avoided?
</blockquote></details>

Good point.

The reason I did so is that NaN is not comparable, so I changed the doc and removed InvalidDepth::kError since it's useless.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 149 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeKoUb1KRPDh7VuHTK:-KjerP-NJs1pky60liJp:bs2gbz8) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L149)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this looks like an important change. Should it be in its own dedicated PR?
</blockquote></details>

No, this isn't an important change at all.

This is just to hide screens during the test execution since they were just annoying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-Kjfe2bJ9WKxClGSqN-D:bqjlan2)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIYTVddQKc_aLx6ca:-KjgwEJ3VcaykHNr_uNj:b-uagmx5) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L43)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Yes, I think so.

If I removed that part, I've got this compile error:

```
/home/kunimatsu/work/kuni-drake/drake/build/install/include/gtest/gtest.h:430:16: error: ‘virtual void testing::Test::SetUp()’ was hidden [-Werror=overloaded-virtual]
   virtual void SetUp();
                ^
/home/kunimatsu/work/kuni-drake/drake/drake/systems/sensors/test/rgbd_camera_test.cc:44:8: error:   by ‘void drake::systems::sensors::{anonymous}::DepthImageToPointCloudConversionTest::SetUp(float)’ [-Werror=overloaded-virtual]
   void SetUp(float depth_value) {
        ^
```
</blockquote></details>

BTW, you can omit this method if you rename `SetUp(float depth_value)` to be something other than "SetUp", for example,`Initialize(float depth_value)`.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjgxQ9FxroFOfNj8okA:-KjgxQ9FxroFOfNj8okB:b-ir2hp5) ([raw file](https://github.com/robotlocomotion/drake/blob/989774d11317cfe70eadcdad442e6aec5722c946/drake/systems/sensors/test/rgbd_camera_test.cc#L30)):*
> ```cpp
> namespace {
> 
> class DepthImageToPointCloudConversionTest : public ::testing::Test {
> ```

BTW, consider moving this test suite below the `RgbdCameraTest` test suite.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055)*

**Comment by kunimatsu-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjeIYTVddQKc_aLx6ca:-KjhdYk5XyMRmnBVAdFT:b-vtfzkw) ([raw file](https://github.com/robotlocomotion/drake/blob/f04a4e97a09acc10383f064b44350ae6b75395da/drake/systems/sensors/test/rgbd_camera_test.cc#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, you can omit this method if you rename `SetUp(float depth_value)` to be something other than "SetUp", for example,`Initialize(float depth_value)`.
</blockquote></details>

Oh, you're right.  I was somehow believing calling SetUp was necessary, but it isn't.

Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-KjgxQ9FxroFOfNj8okA:-KjhdQMa29e2sIoFLtnq:b68gn9l) ([raw file](https://github.com/robotlocomotion/drake/blob/989774d11317cfe70eadcdad442e6aec5722c946/drake/systems/sensors/test/rgbd_camera_test.cc#L30)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider moving this test suite below the `RgbdCameraTest` test suite.
</blockquote></details>

Agreed. This is less important than `RgbdCamereTest`.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055)*

**Comment by kunimatsu-tri** [comment]
+@sammy-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-KjhgP351MQ84y23fX8_:b3j5bdc)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055)*

**Comment by sammy-tri** [comment]
:lgtm:  +(status: curate commits before merging) 

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6055#-:-KjhuiV_qFG-3rNtDtIR:b-340e89)*

**Pull request merged**
