### PR TITLE
Allows IiwaStatusSender to populate the joint_torque_commanded variable

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7629)

### CODE REVIEW

**Comment by rcory** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0RktM7eunmb9ax_In8:bjquaum)*

**Comment by sammy-tri** [comment]
First pass complete (the CI issues seem to imply more changes are coming).  Also I was surprised not to see `kuka_simulation.cc` modified.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0eS8EMzc4TU9DIaF78:-L0eS8EN73Xt5LkYGTqi:bucr1s5) ([raw file](https://github.com/robotlocomotion/drake/blob/fb261efa6d9ce27558b1df0dd9cdd553b14ccb26/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L134)):*
> ```objc
>   }
> 
>   const systems::OutputPort<T> &get_output_port_computed_torque(
> ```

The '&' operator should be next to the type, not the function name (see declaration above).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0eSfyprl8es-IDrENl:b-rsmbt8)*

**Comment by rcory** [comment]
PTAL. I missed some files (as you pointed out), so these should address the CI issues.

---

Review status: 6 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0eS8EMzc4TU9DIaF78:-L0f7hcULxRQr05wbebp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb261efa6d9ce27558b1df0dd9cdd553b14ccb26/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L134)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The '&' operator should be next to the type, not the function name (see declaration above).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0f7imciXdDxpOT4HCo:b-ytrdmz)*

**Comment by sammy-tri** [comment]
:lgtm: assuming CI passes.  +@ericcousineau-tri for platform review

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0fB0X8oSFJa6xACAnz:b-acoexv)*

**Comment by EricCousineau-TRI** [comment]
First pass done, PTAL.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/iiwa_lcm.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fIVltWM2DVdYgOy0I:-L0fIVltWM2DVdYgOy0J:bvi016j) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/iiwa_lcm.cc#L220)):*
> ```cpp
>     status.joint_velocity_estimated[i] = state->GetAtIndex(i + num_joints_);
>     status.joint_position_commanded[i] = command->GetAtIndex(i);
>     status.joint_torque_commanded[i] = commanded_torque->GetAtIndex(i);
> ```

I spoke to Sammy about the slack convo y'all had; would it be possible to set `joint_torque_measured` to equal `*_commanded` and add a quick note to change this once `RigidBodyPlant` supports obtaining measured torque values?

---

*[examples/kuka_iiwa_arm/iiwa_lcm.h, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fIu5MxtLm6R3wJPPm:-L0fIu5NRbsKrkXHEf7d:bc7i19c) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/iiwa_lcm.h#L152)):*
> ```objc
> /// systems::Value object templated on type `lcmt_iiwa_status`. For an example
> /// of this, see iiwa_wsg_simulation.cc.
> class IiwaStatusSender : public systems::LeafSystem<double> {
> ```

Could you add a note that this is presently only used for simulation (as drivers tend to publish directly to LCM)?

---

*[examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fGuMv9RCsKT5h_se4:-L0fGuMv9RCsKT5h_se5:bckvzy2) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L191)):*
> ```cpp
>     EXPECT_EQ(status.joint_position_measured[i], state(i));
>     EXPECT_EQ(status.joint_velocity_estimated[i], state(i + kNumJoints));
>   }
> ```

Could a check on `status.joint_torque_commanded` be placed here?
(and other values, if they are introduced?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0fH9IiahmDA3iYuNhD:b-v6sck1)*

**Comment by rcory** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/kuka_iiwa_arm/iiwa_lcm.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fIVltWM2DVdYgOy0I:-L0jlZbQ-00FPkU1cnIx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/iiwa_lcm.cc#L220)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I spoke to Sammy about the slack convo y'all had; would it be possible to set `joint_torque_measured` to equal `*_commanded` and add a quick note to change this once `RigidBodyPlant` supports obtaining measured torque values?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/iiwa_lcm.h, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fIu5MxtLm6R3wJPPm:-L0jeYPP8iLvm-oVQeYK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/iiwa_lcm.h#L152)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could you add a note that this is presently only used for simulation (as drivers tend to publish directly to LCM)?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-L0fGuMv9RCsKT5h_se4:-L0jf6WtTly6ddzxXhw5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c838b925989d06a13090e789f9ce32842ff42d25/examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc#L191)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could a check on `status.joint_torque_commanded` be placed here?
(and other values, if they are introduced?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629)*

**Comment by rcory** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

---

Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0k0I63oeBjvzJrSfFV:b-j9ui69)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 4 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7629#-:-L0kHz6gC3yFlQ-yTnLz:bnfp4nl)*

**Pull request merged**
