### PR TITLE
Uniform pts on sphere

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5853)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please. The test failures are due to the gurobi license issue on TRI gurobi license server.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-:-KhsDvoizOIyn9Nn_18I:bckuhuv)*

**Comment by sherm1** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/evenly_distributed_pts_on_sphere.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsCRAIiTrVLEfHed8c:-KhsCRAIiTrVLEfHed8d:b-ycugj4) ([raw file](https://github.com/robotlocomotion/drake/blob/ec7875d68dae1d35f08ea41c0781e3eb1c583180/drake/math/evenly_distributed_pts_on_sphere.h#L9)):*
> ```objc
>  * sphere. This method uses Fibonacci number. For the detailed math, please
>  * refer to http://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere
>  * This algorithm works good for large number of samples ( > 50).
> ```

BTW good -> well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/evenly_distributed_pts_on_sphere.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsCRAIiTrVLEfHed8c:-KhsFjfKX9j-6EY5tpv8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec7875d68dae1d35f08ea41c0781e3eb1c583180/drake/math/evenly_distributed_pts_on_sphere.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW good -> well
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/math/evenly_distributed_pts_on_sphere.cc, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsJjk0XVQKW4_PjoSC:-KhsJjk0XVQKW4_PjoSD:btcq4uo) ([raw file](https://github.com/robotlocomotion/drake/blob/3e2fc0e4ea3321825a1449a09bbb523052c75d50/drake/math/evenly_distributed_pts_on_sphere.cc#L13)):*
> ```cpp
>   double golden_angle = M_PI * (3 - std::sqrt(5));
>   for (int i = 0; i < num_samples; ++i) {
>     double y = ((i * offset) - 1) + (offset / 2);
> ```

BTW, `y, r, phi, x, z` can be `const`.

---

*[drake/math/evenly_distributed_pts_on_sphere.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsJryMgBAXT_bkJY7c:-KhsJryN2ECCXZm99jxV:bie6xkb) ([raw file](https://github.com/robotlocomotion/drake/blob/3e2fc0e4ea3321825a1449a09bbb523052c75d50/drake/math/evenly_distributed_pts_on_sphere.cc#L14)):*
> ```cpp
>   for (int i = 0; i < num_samples; ++i) {
>     double y = ((i * offset) - 1) + (offset / 2);
>     double r = std::sqrt(1 - y * y);
> ```

BTW, 

1) Need `#include <cmath>`
2) Need to have `std::` in front of `cos` and `sin` for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-:-KhszagFbvtVD9CHsroX:bvi7gqa)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/evenly_distributed_pts_on_sphere.cc, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsJjk0XVQKW4_PjoSC:-KhtDRFX_xkYEP9xsh6y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e2fc0e4ea3321825a1449a09bbb523052c75d50/drake/math/evenly_distributed_pts_on_sphere.cc#L13)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `y, r, phi, x, z` can be `const`.
</blockquote></details>

Done.

---

*[drake/math/evenly_distributed_pts_on_sphere.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhsJryMgBAXT_bkJY7c:-KhtDRpvhO2hQZYUm6M-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e2fc0e4ea3321825a1449a09bbb523052c75d50/drake/math/evenly_distributed_pts_on_sphere.cc#L14)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, 

1) Need `#include <cmath>`
2) Need to have `std::` in front of `cos` and `sin` for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by soonho-tri** [comment]
:lgtm: (aside minor comments).
+@sherm1 , platform review please.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/math/test/evenly_distributed_pts_on_sphere_test.cc, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhvHOYDaMaj0DonnVin:-KhvHOYDaMaj0DonnVio:b-ii6by5) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/test/evenly_distributed_pts_on_sphere_test.cc#L35)):*
> ```cpp
>       M_PI / 4);
>   for (const auto& cone : cones) {
>     const auto& a = cone.first;
> ```

BTW, I think it's better to check the following here?
```c++
    EXPECT_NEAR(a.norm(), 1.0, 1E-6);
```

---

*[drake/math/test/evenly_distributed_pts_on_sphere_test.cc, line 42 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhvHUVD0N67HBLO2tOZ:-KhvHUVD0N67HBLO2tO_:b-tf9xdv) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/test/evenly_distributed_pts_on_sphere_test.cc#L42)):*
> ```cpp
>       num_pts_in_cone += static_cast<int>(a.dot(pts.col(i)) >= cos_theta);
>     }
>     // The area of the intersection region is 2π(1-cosθ)
> ```

Could you elaborate the connection between the comment including `2π(1-cosθ)` and what we're actually checking in the code `#pts_in_cone / #samples = (1 - cosθ) / 2`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-:-KhvI4065lCSqZ3cBRTy:be7slw5)*

**Comment by sherm1** [comment]
:lgtm: (pending a BTW and @soonho-tri's comments)

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/math/evenly_distributed_pts_on_sphere.h, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhwcldRSTO6zzlmlIYb:-KhwcldRSTO6zzlmlIYc:b-rihtix) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/evenly_distributed_pts_on_sphere.h#L10)):*
> ```objc
>  * sphere. This method uses Fibonacci number. For the detailed math, please
>  * refer to http://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere
>  * This algorithm works well for a large number of samples ( > 50).
> ```

BTW, can you say what happens with a smaller number of samples? If I use 10 samples for example will something bad happen or would it still provide 10 evenly-distributed points? Please clarify whether this refers to an algorithmic failing or whether you are just advising people that a small number of points doesn't approximate a sphere well. If it is an algorithmic problem, consider enforcing a larger minimum.

Also, this comment should give some performance guidance -- looks like it is O(n) in the number of samples which is a nice feature!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-:-KhwggjoWz1kjxmDOcjt:b-vvrvwk)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/evenly_distributed_pts_on_sphere.h, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhwcldRSTO6zzlmlIYb:-Khx0g7IH_-TGynZ0Wp9:b-4asjsa) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/evenly_distributed_pts_on_sphere.h#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, can you say what happens with a smaller number of samples? If I use 10 samples for example will something bad happen or would it still provide 10 evenly-distributed points? Please clarify whether this refers to an algorithmic failing or whether you are just advising people that a small number of points doesn't approximate a sphere well. If it is an algorithmic problem, consider enforcing a larger minimum.

Also, this comment should give some performance guidance -- looks like it is O(n) in the number of samples which is a nice feature!
</blockquote></details>

Done. Sorry I was wrong, it actually performs well for even small number of points. I plotted the generated points on the unit sphere, and they look reasonably uniform to my eyes.

---

*[drake/math/test/evenly_distributed_pts_on_sphere_test.cc, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhvHOYDaMaj0DonnVin:-KhwkuIF878lTAy5SNYC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/test/evenly_distributed_pts_on_sphere_test.cc#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's better to check the following here?
```c++
    EXPECT_NEAR(a.norm(), 1.0, 1E-6);
```
</blockquote></details>

Done.

---

*[drake/math/test/evenly_distributed_pts_on_sphere_test.cc, line 42 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5853#-KhvHUVD0N67HBLO2tOZ:-Khwkump0R8Q9fA_xjUB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/569cccef23510ec3716711c93e1e91b57b222ab0/drake/math/test/evenly_distributed_pts_on_sphere_test.cc#L42)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you elaborate the connection between the comment including `2π(1-cosθ)` and what we're actually checking in the code `#pts_in_cone / #samples = (1 - cosθ) / 2`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5853)*

**Comment by RussTedrake** [comment]
i would have thought that the file should be called "uniform" instead of "evenly".  and that the interface should return a single random point, instead of a collection?  that would be more consistent with other random number generators...?

**Comment by hongkai-dai** [comment]
@RussTedrake This is not a random number generator. Instead, it tries to solve this problem: how to deterministically put N points on the sphere, such that they are (approximately) uniformly distributed. There are a lot of approaches on this problem. I implemented one of the approach to use Fibonacci number.

**Comment by RussTedrake** [comment]
Got it.  Ok

**Pull request merged**
