### PR TITLE
Revert to cmake hash before cygwin macro logic was removed. I was a b…

### PR DESCRIPTION
**Pull request by jonathan-owens**
…it over-zealous in my removal and some macros were deleted that were necessary. This is a temporary fix.

See #1747 and #2365.

@billhoffman can you take a look?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2401) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>

### CODE REVIEW

**Comment by jamiesnape** [comment]
@jonathan-owens I will review it.

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> @jonathan-owens I will review it.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2401#-:-KI8pMTNQ5vXc7VtRCCB:1417088721)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2401)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

I wish the cmake code was just in the main repo.

**Comment by david-german-tri** [comment]
:lgtm: I suspect the cmake code is shared with other RobotLocomotion projects, but I'll look into it.

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> +@david-german-tri for platform review.
> 
> 
> 
> I wish the cmake code was just in the main repo.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2401#-:-KI8xXplZDgR2wQ6Mono:2127313311)*

**Pull request merged**
