### PR TITLE
Add 7dof jaco urdf

### PR DESCRIPTION
**Pull request by sammy-tri**
I'm not thrilled with how the fingers are modeled and we're going to need to decide what to do about that, but the 6dof currently has the same finger model so I think we can defer that and fix both later.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7161)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review.  cc @rcory 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-KvTlqrF5PkCW2uQnzqj:b-dw5dl7)*

**Comment by naveenoid** [comment]
Could you perhaps add a sanity check unit test with this PR? For instance just instantiate a tree and check dofs or something elementary..

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-KvcQfnGhEHiTWDoiv9J:b-7mnnm0)*

**Comment by sammy-tri** [comment]
Done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-Kvh7Z0sZ64KmPu3-Nev:b-896fix)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-Kvh8MldzOhvka45r66G:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@soonho-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-Kvh9IR8IP3NdwCuYcD4:bcjsslk)*

**Comment by soonho-tri** [comment]
Platform :lgtm: (aside minor typo)

I trust @naveenoid 's judgement on the changes in `.urdf` files.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-KvhBctge8AFF-AX0_q1:-KvhBctge8AFF-AX0_q2:brp2soz) ([raw file](https://github.com/robotlocomotion/drake/blob/142e59e725d4764e73a84848b85a11bddbcbdb53/drake/manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc#L37)):*
> ```cpp
> }
> 
> // Tests that j2n6s300.urdf can be loaded into a
> ```

BTW, `j2n6s300` -> `j2s7s300`?
Also please try to reflow the paragraph. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-:-KvhBvmFZOM6k0twj63n:b-6vzxq3)*

**Comment by sammy-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7161#-KvhBctge8AFF-AX0_q1:-Kvhd3PiGttCVOVtETqT:bkf7szj) ([raw file](https://github.com/robotlocomotion/drake/blob/570a641d6e7a0d7d8a6607ab87945f0365e009e9/drake/manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc#L37)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `j2n6s300` -> `j2s7s300`?
Also please try to reflow the paragraph. 
</blockquote></details>

Fixed, comment text reflowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7161)*

**Pull request merged**
