### PR TITLE
Exclude //drake:* from //drake:libdrake.so 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Things like `//drake:gurobi_deps` are private visibility, intended only for Drake-internal uses, but the `bazel query` recipe was including them anyway.

Also sync up with the latest `build_components_refresh.py` output on master.

Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7287)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@ggould-tri for platform review please, per rotation.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7287#-:-KwjZe2ZqORFnPa1stph:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7287)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7287#-:-Kwk7BatfsOFRLmeTnQ5:bnfp4nl)*

**Pull request merged**
