### PR TITLE
Fix segfault in SAP when caching is disabled

### LINKED ISSUE #20103: Misordering of function calls in SapDriver::CalcContactSolverResults may cause undefined behavior
In SapDriver::CalcContactSolverResults,
```cpp
const ContactProblemCache<T>& contact_problem_cache = EvalContactProblemCache(context);
const SapContactProblem<T>& sap_problem = *contact_problem_cache.sap_problem;
const SapSolverResults<T>& sap_results = EvalSapSolverResults(context);
```

`EvalContactProblemCache` is called before `EvalSapSolverResults`. If `CalcSapSolverResults` is called by `EvalSapSolverResults` (e.g. when I disable cache), this will reset contact problem, so the previously obtained `const ContactProblemCache<T>& contact_problem_cache` will be undefined.

Should swap the order of function calls as 
```cpp
const SapSolverResults<T>& sap_results = EvalSapSolverResults(context);
const ContactProblemCache<T>& contact_problem_cache = EvalContactProblemCache(context);
const SapContactProblem<T>& sap_problem = *contact_problem_cache.sap_problem;
```

@xuchenhan-tri

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #20103

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-:-NeAui4f9UntPOHOI_sC:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/sap_driver.cc` line 789 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-Nei8bo1AafCk0iKDJYf:-Neihs_mBA_jAMoBHQ56:b1fp1rk) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L789)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/drake/issues/13591
</blockquote></details>

After f2f w/Alejandro I think I understand the problem as keeping references to an object whose address may change due to reallocation. The usual fix for that is to add a level of indirection, e.g. only keep a reference to the _pointer_ to the object, not to the object itself. You could also make a little "handle" struct that would be the object in the cache; the handle would be persistent but would contain the ephemeral pointer.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/sap_driver.cc` line 789 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-Nei8bo1AafCk0iKDJYf:-NejPHTp0FxpnLk7ExxP:b-8tpzz6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L789)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

After f2f w/Alejandro I think I understand the problem as keeping references to an object whose address may change due to reallocation. The usual fix for that is to add a level of indirection, e.g. only keep a reference to the _pointer_ to the object, not to the object itself. You could also make a little "handle" struct that would be the object in the cache; the handle would be persistent but would contain the ephemeral pointer.
</blockquote></details>

To be more specific, we even discussed making `ContactProblemCache` a class that essentially has two methods:
 1. `ResetContactProblem(std::unique_ptr<SapContactProblem> problem)`
 2. `const SapContactProblem& operator*() const` and maybe `operator->()`

Non-blocking though. 
___
*[`multibody/plant/sap_driver.cc` line 807 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-NejR9cz4k6JjDe3dp3K:-NejR9cz4k6JjDe3dp3L:b-kl36jn) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L807)):*
> ```cpp
>   // Next time step state.
>   const contact_solvers::internal::SapContactProblem<T>& problem =
>       *EvalContactProblemCache(context).sap_problem;
> ```

same problem here right?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/sap_driver.cc` line 789 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-Nei8bo1AafCk0iKDJYf:-NejSUTg2ePOfvRyK06H:bp41bw2) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L789)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

To be more specific, we even discussed making `ContactProblemCache` a class that essentially has two methods:
 1. `ResetContactProblem(std::unique_ptr<SapContactProblem> problem)`
 2. `const SapContactProblem& operator*() const` and maybe `operator->()`

Non-blocking though.
</blockquote></details>

It seems to me that the problem is not the timing of the `Eval`, rather the timing of forming the reference `*contact_problem_cache.sap_problem`.  If you formed a reference to `contact_problem_cache.R_WC.front()` you would likewise be hosed, even with no unique_ptr in sight.

I think the code should do this:

```
const ContactProblemCache<T>& contact_problem_cache =
      EvalContactProblemCache(context);
```

and then call

```
  PackContactSolverResults(context, *contact_problem_cache.sap_problem,
      num_contacts, sap_results, results);
```

The rule of thumb should be when you call Eval, keep the returned reference (only) around.  Don't assume that the reference points to an immutable object, because it doesn't.  The only guarantee is that it's an up-to-date object.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/sap_driver.cc` line 789 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-Nei8bo1AafCk0iKDJYf:-NekW1jk5_4KUeg_lOa_:b-m901wf) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L789)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me that the problem is not the timing of the `Eval`, rather the timing of forming the reference `*contact_problem_cache.sap_problem`.  If you formed a reference to `contact_problem_cache.R_WC.front()` you would likewise be hosed, even with no unique_ptr in sight.

I think the code should do this:

```
const ContactProblemCache<T>& contact_problem_cache =
      EvalContactProblemCache(context);
```

and then call

```
  PackContactSolverResults(context, *contact_problem_cache.sap_problem,
      num_contacts, sap_results, results);
```

The rule of thumb should be when you call Eval, keep the returned reference (only) around.  Don't assume that the reference points to an immutable object, because it doesn't.  The only guarantee is that it's an up-to-date object.
</blockquote></details>

okay, yes, I definitelly like this spelling better

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/sap_driver.cc` line 789 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-Nei8bo1AafCk0iKDJYf:-NeoOCdQB72np-BP1j_f:b-axo9dx) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L789)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

okay, yes, I definitelly like this spelling better
</blockquote></details>

Done. Thanks for the input!
___
*[`multibody/plant/sap_driver.cc` line 807 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-NejR9cz4k6JjDe3dp3K:-NeoODXKC2LfXtu5AMYd:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8e5e4c3b01f276657162ffeb550a7791212653b/multibody/plant/sap_driver.cc#L807)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

same problem here right?
</blockquote></details>

Done

**Review by amcastro-tri — COMMENTED** [review]
Thank you @xuchenhan-tri, :lgtm: 

+@ggould-tri for platform review please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-:-NfCVsNGBoSxVUlb5RLU:b4kfeyn)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-:-NfCb_DeEzXihRZ5wLUX:bnfp4nl)* status: 1 unresolved discussion

___
*[`multibody/plant/sap_driver.cc` line 804 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-NfCbMQCB4TaVIoT8YkW:-NfCbMQCB4TaVIoT8YkX:b63sde8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c43d7952c44f713d976f275787911c14380227f1/multibody/plant/sap_driver.cc#L804)):*
> ```cpp
>   // Next time step state.
>   const ContactProblemCache<T>& contact_problem_cache =
>       EvalContactProblemCache(context);
> ```

BTW:  It might be easier to follow if this line were moved to line 832 or so, since this value is only used there.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri

___
*[`multibody/plant/sap_driver.cc` line 804 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20177#-NfCbMQCB4TaVIoT8YkW:-NfD7YzL2K-Q7R5qp8gX:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/c43d7952c44f713d976f275787911c14380227f1/multibody/plant/sap_driver.cc#L804)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  It might be easier to follow if this line were moved to line 832 or so, since this value is only used there.
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20177)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri

**Pull request merged**
