### PR TITLE
controllers: add python bindings for finite-horizon LQR

### PR DESCRIPTION
**Pull request by RussTedrake**
as discussed on slack, this uses a work-around to binding the std::unique_ptr member variables in FiniteLQRResult.

also includes a few small improvements to finite-horizon LQR, in preparation for the supporting discrete-time systems.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13145)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
The use of `unique_ptr` in a parameter struct still seems a bit sketchy, as it may complicate things like #13058 / #8904.

Will commend directly in code as well.

**Comment by jwnimmer-tri** [comment]
Maybe `const unique_ptr<Foo>` makes more sense?  If it's only populated from C++, and not resettable in pydrake, does that simplify?

**Comment by jwnimmer-tri** [comment]
___
*[systems/controllers/finite_horizon_linear_quadratic_regulator.h, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13145#-M5vzXkA48zm4yFzAZxk:-M5yRrwh8hTBHG21MTZP:b-hxg5d) ([raw file](https://github.com/robotlocomotion/drake/blob/1f5395f936ab2bf44c82b4b1a818698eeb63df43/systems/controllers/finite_horizon_linear_quadratic_regulator.h#L57)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

(I should have written my comment here)
I’m struggling a bit with this.  How do I return a structure from a function when that structure has const std::unique_ptr members?
https://stackoverflow.com/questions/29194304/move-constructor-involving-const-unique-ptr

</blockquote></details>

I think you can't used a named return value, so would need to `return FiniteHorizonLinearQuadraticRegulatorResult(move(x0), move(u0), move(K), move(S))`.

**Comment by EricCousineau-TRI** [comment]
___
*[systems/controllers/finite_horizon_linear_quadratic_regulator.h, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13145#-M5vzXkA48zm4yFzAZxk:-M5yTecR6nijrfsMhfSY:b-u43ykq) ([raw file](https://github.com/robotlocomotion/drake/blob/1f5395f936ab2bf44c82b4b1a818698eeb63df43/systems/controllers/finite_horizon_linear_quadratic_regulator.h#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think you can't used a named return value, so would need to `return FiniteHorizonLinearQuadraticRegulatorResult(move(x0), move(u0), move(K), move(S))`.
</blockquote></details>

Aye, there's that too. However, it does seem like you'll no longer be able return that intermediate struct as a result - which is probably not too great a deal, but still.

After tinkering with the `const ParamStruct` formulation, I myself would err towards the simple-C++ solution, and an explicitly non-writable Python version.

**Comment by RussTedrake** [comment]
Thanks!

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/common/test/wrap_pybind_test.py, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13145#-M671XNN3FxH9n_VG7WK:-M67AgWR0WidZIcjMxiM:bl106s8) ([raw file](https://github.com/robotlocomotion/drake/blob/92cc65ed6cff3aee00ac5cd11c6084043b734c7a/bindings/pydrake/common/test/wrap_pybind_test.py#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW @EricCousineau-TRI in a future PR should we test here that "readonly" is actually in effect?
</blockquote></details>

Actually, will do a quick follow-up; I, uh, skimmed this part (saw the words `gc` and `alive` and marked myself satisfied); didn't look closely enough at the C++ code. It needs a quick fix.
Sorry about that, @russtedrake!

FYI Basically, primitive types in `pybind11` happen through *type-conversion*:
https://pybind11.readthedocs.io/en/stable/advanced/cast/index.html
Because of that, you can't share references to C++ / Python native types when converting.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/common/test/wrap_pybind_test.py, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13145#-M671XNN3FxH9n_VG7WK:-M67C4bl8yjeCIw4uswW:btkg5yl) ([raw file](https://github.com/robotlocomotion/drake/blob/92cc65ed6cff3aee00ac5cd11c6084043b734c7a/bindings/pydrake/common/test/wrap_pybind_test.py#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Actually, will do a quick follow-up; I, uh, skimmed this part (saw the words `gc` and `alive` and marked myself satisfied); didn't look closely enough at the C++ code. It needs a quick fix.
Sorry about that, @russtedrake!

FYI Basically, primitive types in `pybind11` happen through *type-conversion*:
https://pybind11.readthedocs.io/en/stable/advanced/cast/index.html
Because of that, you can't share references to C++ / Python native types when converting.
</blockquote></details>

(Will also rename it to reflect read-only)

**Pull request merged**
