### PR TITLE
Fix LinearDistanceAndInterpolationProvider vs removed joint

### LINKED ISSUE #21860: SceneGraphCollisionChecker refers to removed joint index after RemoveJoint() function has been called on the plant
### What happened?

When working with `MultibodyPlant`, after calling `plant.RemoveJoint()` method, the joint index is removed and not replaced (as expected). Thus, there would be a skip of integer number at the point where the removed joint's index was numerically assigned. When this plant (via its `RobotDiagram`) is then passed to the `SceneGraphCollisionChecker`, the following error is given: `RuntimeError: The JointIndex(26) has been removed`. Essentially, `SceneGraphCollisionChecker` is not working on a plant for which joints have been removed and new joints/ welds have been added at the end, creating a discontinuity in the integer index of joints. 

### Version

1.32.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by agarwal-abhinav**
Adding a test case and changing for loop to fix the issue documented here #21860.

Closes #21860.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This seems like a bug that was missed during #21397 review, so +@joemasterjohn for feature review or delegation, please.

**Review by joemasterjohn — COMMENTED** [review]
Got it. Curious that this loop didn't get tickled by [the hack to offset all joint indices](https://github.com/RobotLocomotion/drake/pull/21397#pullrequestreview-2041137505) from #21397? But either way, looks like the correct coverage is added here. :lgtm: 

+@xuchenhan-tri for platform review tomorrow, please.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-:-O5sxbDh1pMqT8WwVmp8:b34b1x0)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @agarwal-abhinav)

___
*[`planning/test/linear_distance_and_interpolation_provider_test.cc` line 458 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-O5t6DsC1vSjxLh4KufR:-O5t6DsC1vSjxLh4KufS:b-5ta4pj) ([raw file](https://github.com/RobotLocomotion/drake/blob/44c713a118b19eefdb95c72cdca9d238bad6e844/planning/test/linear_distance_and_interpolation_provider_test.cc#L458)):*
> ```cpp
>   auto& plant = builder->plant();
> 
>   JointIndex joint_index(
> ```

nit: missing `const`



_Suggestion:_
```cpp
  const JointIndex joint_index(
```
___
*[`planning/test/linear_distance_and_interpolation_provider_test.cc` line 462 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-O5t6Jtt4dHvDf1loqMd:-O5t6Jtt4dHvDf1loqMe:b-5ta4pj) ([raw file](https://github.com/RobotLocomotion/drake/blob/44c713a118b19eefdb95c72cdca9d238bad6e844/planning/test/linear_distance_and_interpolation_provider_test.cc#L462)):*
> ```cpp
>   const Joint<double>& joint = plant.get_joint(joint_index);
> 
>   JointActuatorIndex joint_actuator_index(
> ```

nit: missing `const`



_Suggestion:_
```cpp
const JointActuatorIndex joint_actuator_index(
```
___
*[`planning/test/linear_distance_and_interpolation_provider_test.cc` line 471 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-O5tbSY1BqhkheBV_E7L:-O5tbSY1BqhkheBV_E7M:btgrghv) ([raw file](https://github.com/RobotLocomotion/drake/blob/44c713a118b19eefdb95c72cdca9d238bad6e844/planning/test/linear_distance_and_interpolation_provider_test.cc#L471)):*
> ```cpp
>   const auto model = builder->Build();
> 
>   const LinearDistanceAndInterpolationProvider provider(model->plant());
> ```

With this test serving as a regression test for changes made in #21397, this is the actual line that would fail. For that reason, it makes more sense to me to spell this out surrounded by `gtest` predicates. It articulates the bug a bit better, and without it the unit test will just fail due to a c++ exception (rather than an gtest assertion failing). I might be wrong about this, so perhaps @jwnimmer-tri or @xuchenhan-tri could weigh in. 



_Suggestion:_
```cpp
  std::unique_ptr<LinearDistanceAndInterpolationProvider> provider;

  EXPECT_NO_THROW(provider =
                      std::make_unique<LinearDistanceAndInterpolationProvider>(
                          model->plant()));
```

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-:-O5uEXWJ0N1XHvf0kBA6:bcpz082)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @agarwal-abhinav)

___
*[`planning/test/linear_distance_and_interpolation_provider_test.cc` line 471 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-O5tbSY1BqhkheBV_E7L:-O5uCNYJ5D1re4kY86mE:b-hxcjjy) ([raw file](https://github.com/RobotLocomotion/drake/blob/44c713a118b19eefdb95c72cdca9d238bad6e844/planning/test/linear_distance_and_interpolation_provider_test.cc#L471)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

With this test serving as a regression test for changes made in #21397, this is the actual line that would fail. For that reason, it makes more sense to me to spell this out surrounded by `gtest` predicates. It articulates the bug a bit better, and without it the unit test will just fail due to a c++ exception (rather than an gtest assertion failing). I might be wrong about this, so perhaps @jwnimmer-tri or @xuchenhan-tri could weigh in.
</blockquote></details>

If the intention is the confirm that the constructor doesn't throw, then wrapping the constructor under `EXPECT_NO_THROW` is good enough.
```
EXPECT_NO_THROW(LinearDistanceAndInterpolationProvider(model->plant())); 
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @agarwal-abhinav)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @agarwal-abhinav)

___
*[`planning/test/linear_distance_and_interpolation_provider_test.cc` line 471 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-O5tbSY1BqhkheBV_E7L:-O6RF_zq-gfGPCvQs9g5:besihm1) ([raw file](https://github.com/RobotLocomotion/drake/blob/44c713a118b19eefdb95c72cdca9d238bad6e844/planning/test/linear_distance_and_interpolation_provider_test.cc#L471)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If the intention is the confirm that the constructor doesn't throw, then wrapping the constructor under `EXPECT_NO_THROW` is good enough.
```
EXPECT_NO_THROW(LinearDistanceAndInterpolationProvider(model->plant())); 
```
</blockquote></details>

Hi @agarwal-abhinav, just wanted to check in on this PR, see if you needed any clarifications from us? Should just require adding the one line that @xuchenhan-tri provided above. I'm marking myself neutral on this so my comment won't block this getting merged.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @agarwal-abhinav)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21867#-:-O6SWyvS1H7UpkDsEbUp:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees joemasterjohn,xuchenhan-tri(platform)

**Pull request merged**
