### PR TITLE
Helper methods to sanity check SystemOutput and Context.

### LINKED ISSUE #3158: Implement helper methods to sanity check SystemOutput and Context.
Implement methods `System<T>::IsOutputValid(SystemOutput<T>& output)` and `System<T>::IsContextValid(ContextBase<T>& context)` that check the consistency of systems' outputs and contexts when passed to methods `EvalOutput` and `EvalTimeDerivatives` since right now we are copying these code for each primitive.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Closes #3158.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3173)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for platform please.
+@david-german-tri for feature please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPOiHUO9SYCtojY3gV6:bx50mke)*

**Comment by jwnimmer-tri** [comment]
@amcastro-tri Do you want my review in particular?  Otherwise today is @sammy-tri on call.

**Comment by amcastro-tri** [comment]
I am sorry @jwnimmer-tri. My brain was on Thursday mode. 
-@jwnimmer-tri 
+@sammy-tri for platform please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPOjtFoaFi-NXVqunu2:b-3bl1ld)*

**Comment by sammy-tri** [comment]
Is the idea that every system should assert on these sanity check functions in every implementation of EvalOutput()?  Like, would we defect code under review which implements a new EvalOutput() and doesn't call the asserts?  Mandatory boilerplate seems like a bad smell, but I'm not sure I'm grasping the idea correctly.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPOsmigVVH-raUbpbtR:-KPOsmihHaKzuNIm3l2h:b-s8eqb1) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac57a97303164c571d7fc91bfd395f12260adb9/drake/systems/framework/system.h#L97)):*
> ```objc
> 
>   /// Checks that @p context is consistent with the number and size of input and
>   /// output ports declared by the system.
> ```

This doesn't seem to check anything about output ports (though the comment indicates that it does)

---

*[drake/systems/framework/primitives/adder.cc, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPOtooRlKrGeIBHc__S:-KPOtooRlKrGeIBHc__T:b-ihz3d5) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac57a97303164c571d7fc91bfd395f12260adb9/drake/systems/framework/primitives/adder.cc#L31)):*
> ```cpp
> 
>   // Checks that the output is consistent with the definition of this system.
>   DRAKE_ASSERT(System<T>::IsValidOutput(*output));
> ```

Why do we say System<T>:: here?  isn't that our parent class?  Or is this just intended to make clear that we're calling a method defined on a parent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPOuNAOqi6fe9gzLlAK:b-qu1njs)*

**Comment by amcastro-tri** [comment]
So far all the `EvalOutput`'s implemented for primitives in System 2.0 do these tests. This PR just puts them in a `System<T>` method so that we don't have to write them every time.  So yes, the idea would be to call these on every EvalOutput. 
Though probably a better idea would be the user to write `CalcOutput` as discussed in #3155 and which would get called from `EvalOuput` having the appropriate sanity checks. 
What do you thin @david-german-tri and @sherm1 about this? @sammy-tri has a good point here.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPOsmigVVH-raUbpbtR:-KPP8KIrWxTLIkTxwcxu:b45mkno) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac57a97303164c571d7fc91bfd395f12260adb9/drake/systems/framework/system.h#L97)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> This doesn't seem to check anything about output ports (though the comment indicates that it does)
</details>
Good point. You are right, there is now way to do any sanity check on outputs on the context. I updated the comment to not be that specific since users actually don't have to know what we have in the context.

---

*[drake/systems/framework/primitives/adder.cc, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPOtooRlKrGeIBHc__S:-KPP8ZTvCx3jrzO-rB0b:bobtubr) ([raw file](https://github.com/robotlocomotion/drake/blob/6ac57a97303164c571d7fc91bfd395f12260adb9/drake/systems/framework/primitives/adder.cc#L31)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Why do we say System<T>:: here?  isn't that our parent class?  Or is this just intended to make clear that we're calling a method defined on a parent?
</details>
That is because both this class and its parent are templates and if it wasn't for the scoped call the compiler would not be able to compile this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPP6h8GL4JEw0FbH2Yk:b-5ekebw)*

**Comment by sammy-tri** [comment]
At any rate, this still seems strictly better to me than the pile of duplicated asserts we had before. :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPPAMAah9qvd8NUFqjD:be5jc61)*

**Comment by david-german-tri** [comment]
Yeah, this is a compelling reason for the NVI from #3155.  Also, :lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[drake/systems/framework/system.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPB2oXRNxEvtBUDlyx:-KPPB2oXRNxEvtBUDlyy:blt9qbu) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/system.h#L84)):*
> ```objc
>       // once abstract ports are implemented in 3164.
>       if (get_output_port(i).get_data_type() == kVectorValued) {
>         const VectorInterface<T> *output_vector =
> ```

nit: `<T>* `

---

*[drake/systems/framework/system.h, line 111 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPBCVb6yCUSC5aEKz_:-KPPBCVcO-Esnt4H984d:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/system.h#L111)):*
> ```objc
>       // once abstract ports are implemented in 3164.
>       if (this->get_input_port(i).get_data_type() == kVectorValued) {
>         const VectorInterface<T> *input_vector = context.get_vector_input(i);
> ```

ditto

---

*[drake/systems/framework/primitives/adder.cc, line 30 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPBLCQFdKkxAR_55tZ:-KPPBLCQFdKkxAR_55t_:bma9b2k) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/primitives/adder.cc#L30)):*
> ```cpp
>   // coverage, and should not run in release builds.
> 
>   // Checks that the output is consistent with the definition of this system.
> ```

BTW, I don't really think these comments add much (all files)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPPBWLQaMuYZIuY3q6U:b-7l56te)*

**Comment by amcastro-tri** [comment]
Addressed reviewers comments. 
Also I made some last minute changes. PTAL.

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[drake/systems/framework/system.h, line 84 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPB2oXRNxEvtBUDlyx:-KPPE249VfqKNeQdF9TX:b88kbwa) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/system.h#L84)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: `<T>* `
</details>
nice catch. Thank you

---

*[drake/systems/framework/system.h, line 111 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPBCVb6yCUSC5aEKz_:-KPPE4AUt14PP2WmTtmI:b-k73z76) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/system.h#L111)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ditto
</details>
thanks

---

*[drake/systems/framework/primitives/adder.cc, line 30 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-KPPBLCQFdKkxAR_55tZ:-KPPE7y32z-o7ZhRgnJG:b111kaw) ([raw file](https://github.com/robotlocomotion/drake/blob/0152f10f9c99a09f65ca8aa2e5ed6a74dd95bf55/drake/systems/framework/primitives/adder.cc#L30)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I don't really think these comments add much (all files)
</details>
agree, the method name is pretty explicit. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPPHd8wTp3tZBUG8_Qr:bv51qkd)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3173#-:-KPPPfwsvUlboz8vCs2X:bnfp4nl)*

**Pull request merged**
