### PR TITLE
Replaced ulong typecast with size_t, to satisfy Mac CI build

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7139)

### CODE REVIEW

**Comment by rcory** [comment]
+@sherm1 for platform review please.
/cc @jwnimmer-tri and @jamiesnape 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvDxcXhqz4dk_B0dNb3:bo116c6)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-KvE4TLat0v00_DSZkdI:-KvE4TLat0v00_DSZkdJ:b-eqxo94) ([raw file](https://github.com/robotlocomotion/drake/blob/625a0280e64718740422f0e9a7eea644d9923126/drake/examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc#L78)):*
> ```cpp
> 
>   const int N = static_cast<int>(allKeyFrames.rows());
>   std::vector<double> times((size_t)N);
> ```

BTW Google Style Guide [requires](https://google.github.io/styleguide/cppguide.html#Casting) static_cast for this conversion:
```c++
std::vector<double> times(static_cast<size_t>(N));
```
(can't use braced initializer syntax because this is a "narrowing" conversion due to potential sign loss).

Of course you are in a dev directory here and can ignore this comment, but in case you want to be compliant ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE43xx2JSu7-iOXIXi:bnfp4nl)*

**Comment by rcory** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE70rkDll6_FFzExNp:b-hu0ug7)*

**Comment by rcory** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE86s1r0nZYutN16uO:b2xqtn3)*

**Comment by jamiesnape** [comment]
Tested this locally on my Mac and it fixes the issue.  Since the builds are broken, I don't think you need to run Mac CI jobs and wait three hours for them to finish.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE7sHItnP1w4KZl2tg:b-bf1lh5)*

**Comment by rcory** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-KvE4TLat0v00_DSZkdI:-KvE8NqL3CtWhmPvcQb4:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/625a0280e64718740422f0e9a7eea644d9923126/drake/examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Google Style Guide [requires](https://google.github.io/styleguide/cppguide.html#Casting) static_cast for this conversion:
```c++
std::vector<double> times(static_cast<size_t>(N));
```
(can't use braced initializer syntax because this is a "narrowing" conversion due to potential sign loss).

Of course you are in a dev directory here and can ignore this comment, but in case you want to be compliant ...
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139)*

**Comment by rcory** [comment]
Got it. Thanks. Is there a way to untrigger them (I just triggered them again after making a small change).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE97HIQbu5T9exJnPA:bsoo5mv)*

**Comment by jamiesnape** [comment]
I can kill them once you merge this.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvE9VVCGrN13kFRyxN6:bbkg3o6)*

**Comment by sherm1** [comment]
I'll override merge this.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7139#-:-KvECtSZqHXYpspl1359:b-tl51m7)*

**Pull request merged**
