### PR TITLE
workspace: Upgrade fmt,spdlog,dReal to latest releases

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9232)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
It looks like dReal's binary release [depends on spdlog](https://github.com/dreal/dreal4/blob/master/dreal/workspace.bzl), and so we have to rebuild dReal in concert with this PR.  FYI @soonho-tri.  It looks like dReal master already switched to spdlog 1.0.0, so we just need new binary release(s) created?

**Comment by soonho-tri** [comment]
@jwnimmer-tri , I'll prepare one and send it to @jamiesnape.

**Comment by soonho-tri** [comment]
> send it to @jamiesnape.

Sent. I think we might need to bump dReal in this PR together.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , could you cherry-pick this commit, https://github.com/soonho-tri/drake/commit/560d9d35e2c0edbedc48ad69cd91aed18740229e?

**Comment by jwnimmer-tri** [comment]
FYI As of the most recent push, the changes to the list of installed files looks like this:
```diff
--- nightly.txt	2018-08-09 12:28:28.417487575 -0400
+++ pr.txt	2018-08-09 12:30:34.528434631 -0400
@@ -1341,16 +1341,13 @@
 ./include/eigen3/unsupported/Eigen/src/Splines/Spline.h
 ./include/fmt
 ./include/fmt/fmt
-./include/fmt/fmt/container.h
-./include/fmt/fmt/format.cc
+./include/fmt/fmt/core.h
 ./include/fmt/fmt/format.h
-./include/fmt/fmt/ostream.cc
+./include/fmt/fmt/format-inl.h
 ./include/fmt/fmt/ostream.h
-./include/fmt/fmt/posix.cc
 ./include/fmt/fmt/posix.h
-./include/fmt/fmt/printf.cc
 ./include/fmt/fmt/printf.h
-./include/fmt/fmt/string.h
+./include/fmt/fmt/ranges.h
 ./include/fmt/fmt/time.h
 ./include/ibex
 ./include/ibex/3rd
@@ -1857,25 +1854,24 @@
 ./include/pybind11/pybind11/stl.h
 ./include/spdlog
 ./include/spdlog/spdlog
+./include/spdlog/spdlog/async.h
 ./include/spdlog/spdlog/async_logger.h
 ./include/spdlog/spdlog/common.h
-./include/spdlog/spdlog/contrib
-./include/spdlog/spdlog/contrib/README.md
-./include/spdlog/spdlog/contrib/sinks
-./include/spdlog/spdlog/contrib/sinks/.gitignore
-./include/spdlog/spdlog/contrib/sinks/step_file_sink.h
 ./include/spdlog/spdlog/details
 ./include/spdlog/spdlog/details/async_logger_impl.h
-./include/spdlog/spdlog/details/async_log_helper.h
+./include/spdlog/spdlog/details/circular_q.h
+./include/spdlog/spdlog/details/console_globals.h
 ./include/spdlog/spdlog/details/file_helper.h
+./include/spdlog/spdlog/details/fmt_helper.h
 ./include/spdlog/spdlog/details/logger_impl.h
 ./include/spdlog/spdlog/details/log_msg.h
 ./include/spdlog/spdlog/details/mpmc_blocking_q.h
 ./include/spdlog/spdlog/details/null_mutex.h
 ./include/spdlog/spdlog/details/os.h
-./include/spdlog/spdlog/details/pattern_formatter_impl.h
+./include/spdlog/spdlog/details/pattern_formatter.h
+./include/spdlog/spdlog/details/periodic_worker.h
 ./include/spdlog/spdlog/details/registry.h
-./include/spdlog/spdlog/details/spdlog_impl.h
+./include/spdlog/spdlog/details/thread_pool.h
 ./include/spdlog/spdlog/fmt
 ./include/spdlog/spdlog/fmt/fmt.h
 ./include/spdlog/spdlog/fmt/ostr.h
@@ -1885,18 +1881,21 @@
 ./include/spdlog/spdlog/sinks/android_sink.h
 ./include/spdlog/spdlog/sinks/ansicolor_sink.h
 ./include/spdlog/spdlog/sinks/base_sink.h
+./include/spdlog/spdlog/sinks/basic_file_sink.h
+./include/spdlog/spdlog/sinks/daily_file_sink.h
 ./include/spdlog/spdlog/sinks/dist_sink.h
-./include/spdlog/spdlog/sinks/file_sinks.h
 ./include/spdlog/spdlog/sinks/msvc_sink.h
 ./include/spdlog/spdlog/sinks/null_sink.h
 ./include/spdlog/spdlog/sinks/ostream_sink.h
+./include/spdlog/spdlog/sinks/rotating_file_sink.h
 ./include/spdlog/spdlog/sinks/sink.h
+./include/spdlog/spdlog/sinks/stdout_color_sinks.h
 ./include/spdlog/spdlog/sinks/stdout_sinks.h
 ./include/spdlog/spdlog/sinks/syslog_sink.h
 ./include/spdlog/spdlog/sinks/wincolor_sink.h
-./include/spdlog/spdlog/sinks/windebug_sink.h
 ./include/spdlog/spdlog/spdlog.h
 ./include/spdlog/spdlog/tweakme.h
+./include/spdlog/spdlog/version.h
 ./include/stx
 ./include/stx/stx
 ./include/stx/stx/optional.hpp
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review per schedule, please.

**Pull request merged**
