### PR TITLE
yaml: Allow for operating on non-default MaxRows or MaxCols storage

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Similar patches have been floating around in other PRs like #14318, #14611, etc.  It seems like it's time to land a polished version into master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14618)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14618#-:-MSdm0N23QnIqoAz7mJL:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/yaml/test/example_structs.h, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14618#-MSdkblu16V-KmwgMU_v:-MSdkblwChAHfmqaE9K7:b6cp7eh) ([raw file](https://github.com/robotlocomotion/drake/blob/7acb07f4b6a45bac0c69f6507883d91e70d00277/common/yaml/test/example_structs.h#L187)):*
> ```objc
>       : value(value_in) {}
> 
>   static constexpr int Options = (MaxRows != Rows) ? Eigen::DontAlign : 0;
> ```

This bit with DontAlign is tricky. Can you add a clarifying comment?

**Review by jwnimmer-tri — COMMENTED** [review]
+@soonho-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14618#-:-MSdneCMCqijTWE4dx3R:by9x1z2)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[common/yaml/test/example_structs.h, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14618#-MSdkblu16V-KmwgMU_v:-MSdnh4LAeGb70JCCOnO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7acb07f4b6a45bac0c69f6507883d91e70d00277/common/yaml/test/example_structs.h#L187)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This bit with DontAlign is tricky. Can you add a clarifying comment?
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14618#-:-MSdphhO3H6MnLNNNtd1:bnfp4nl)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

**Pull request merged**
