### PR TITLE
[setup] Remove errors on Ubuntu arm64

### PR DESCRIPTION
**Pull request by adeeb10abbas**
Relates to #13514. Removes `libquadmath0` as a package since it gets pulled in via `libgfortran5` anyway and is redundant. 
 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)

### CODE REVIEW

**Comment by adeeb10abbas** [comment]
@jwnimmer-tri / @EricCousineau-TRI

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @adeeb10abbas)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-MXRD2O17Odw6Rnct:-NG-MXRD2O17Odw6Rncu:bem70yj) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/source_distribution/install_prereqs.sh#L175)):*
> ```Shell
> 
> if [[ $(arch) = "aarch64" ]]; then
>   wget https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-linux-arm64
> ```

Ick, I'd forgotten that Bazel upstream doesn't provide debian packages for arm64 as part of their release process.

It's not OK for Drake setup scripts to install things into /usr/local/.

To split the difference, what we could do here for aarch64 is:

(1) Use something like `which bazel` to see if bazel on the `$PATH` already.  If so, do nothing.

(2) Otherwise, print a warning "You need to manually install Bazel somehow; see https://bazel.build/ for details.".

That at least would let arm64 users run this setup script without errors.  It would just be up to them to install Bazel on their own, instead of automating it.  Down the road, hopefully we could automate it (probably with "bazelisk").

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-MXRD2O17Odw6Rnct:-NG-NuNc4xVTqM8omfj5:b-u0fu3r) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/source_distribution/install_prereqs.sh#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ick, I'd forgotten that Bazel upstream doesn't provide debian packages for arm64 as part of their release process.

It's not OK for Drake setup scripts to install things into /usr/local/.

To split the difference, what we could do here for aarch64 is:

(1) Use something like `which bazel` to see if bazel on the `$PATH` already.  If so, do nothing.

(2) Otherwise, print a warning "You need to manually install Bazel somehow; see https://bazel.build/ for details.".

That at least would let arm64 users run this setup script without errors.  It would just be up to them to install Bazel on their own, instead of automating it.  Down the road, hopefully we could automate it (probably with "bazelisk").
</blockquote></details>

Yeah, I was pretty confused about how to go about this. I'd go with 2 if that's okay with you. Bazelisk works flawlessly so, I don't think they (aarch64) users would mind going through that installation process.

**Review by jwnimmer-tri — COMMENTED** [review]
For the record (PR history): libquadmath0 does not exist on arm64.  The easiest solution is to skip it on amd64 as well, since it's redundant.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261#-:-NG-ODS1BAHyZBrV_Wqd:brpnndj)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @adeeb10abbas)

___
*[`setup/ubuntu/binary_distribution/packages-focal.txt` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-Nr3X7baHT8_bugsk:-NG-Nr3X7baHT8_bugsl:b9ui412) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/binary_distribution/packages-focal.txt#L14)):*
> ```help
> libfreetype6
> libgflags2.2
> libgfortran5
> ```

FYI I confirmed on Focal that `libquadmath0` is redundant: 

```console
jwnimmer@call-cps:~$ lsb_release -r
Release:	20.04

jwnimmer@call-cps:~$ dpkg -s libgfortran5 | grep Depend
Depends: gcc-10-base (= 10.3.0-1ubuntu1~20.04), libc6 (>= 2.29), libgcc-s1 (>= 4.3), libquadmath0 (>= 4.6)
```
___
*[`setup/ubuntu/binary_distribution/packages-jammy.txt` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-O0vp0sk7inbiOvuv:-NG-O0vp0sk7inbiOvuw:b3k0pk8) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/binary_distribution/packages-jammy.txt#L14)):*
> ```help
> libfreetype6
> libgflags2.2
> libgfortran5
> ```

FYI I confirmed on Jammy that `libquadmath0` is redundant:

```console
(jammy)jwnimmer@call-cps:~$ lsb_release -r
Release:	22.04
(jammy)jwnimmer@call-cps:~$ dpkg -s libgfortran5 | grep Depend
Depends: gcc-12-base (= 12-20220319-1ubuntu1), libc6 (>= 2.34), libgcc-s1 (>= 4.3), libquadmath0 (>= 4.6)
```
___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-MXRD2O17Odw6Rnct:-NG-OQCl04BR-bgwi2Vw:bokhlo2) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/source_distribution/install_prereqs.sh#L175)):*
<details><summary><i>Previously, adeeb10abbas (Adeeb Abbas) wrote…</i></summary><blockquote>

Yeah, I was pretty confused about how to go about this. I'd go with 2 if that's okay with you. Bazelisk works flawlessly so, I don't think they (aarch64) users would mind going through that installation process. 
</blockquote></details>

My suggestion was intended to be both (1) and (2) -- in other words, at most print a warning but _only_ if bazel isn't installed already (i.e., avoid spurious warnings).

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-MXRD2O17Odw6Rnct:-NG-PlIw7gtVpwl_KwJQ:b-xot3d5) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/source_distribution/install_prereqs.sh#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My suggestion was intended to be both (1) and (2) -- in other words, at most print a warning but _only_ if bazel isn't installed already (i.e., avoid spurious warnings).
</blockquote></details>

I totally misread that sorry, it's a bit late :) Yep, that makes sense will do that!

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`setup/ubuntu/binary_distribution/packages-jammy.txt` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NG-O0vp0sk7inbiOvuv:-NG-QZty1FcilhF_yL9f:bh7hg9g) ([raw file](https://github.com/robotlocomotion/drake/blob/0e3c04cf1e7fcc65f8aafbfe8eae2a7acf8731c8/setup/ubuntu/binary_distribution/packages-jammy.txt#L14)):*
> libgfortran5
more package details here - https://packages.ubuntu.com/jammy/libs/libgfortran5

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review +(release notes: fix).

+@EricCousineau-TRI would you like to platform review?

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261#-:-NG1zW9i5LAB524D-hz2:b-3synyq)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Review by adeeb10abbas — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform, thanks! Just a nit on error message.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261#-:-NGIdtwQ6NVLK6aAOuUv:b-evrk2g)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @adeeb10abbas)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 178 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NGIcluZ8YAizS21fBQn:-NGIcluZ8YAizS21fBQo:b-un06is) ([raw file](https://github.com/robotlocomotion/drake/blob/e34f69d8b1edef7a0a60262d441c2d6ea2a6afae/setup/ubuntu/source_distribution/install_prereqs.sh#L178)):*
> ```Shell
>     echo "Bazel is already installed." >&2
>   else
>     echo "You need to manually install Bazel somehow; see https://bazel.build/ for details." >&2
> ```

nit Motivation for error message may not be evident to users.

Consider rewording error message:
```
cat >&2 <<EOF
WARNING: Drake currently does not support installing Bazel on arm64 systems.
You will need to manually install a Drake compatible version.
For some options, review https://bazel.build/install/ubuntu
EOF
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 178 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NGIcluZ8YAizS21fBQn:-NGIf1NI6c0Utn_3kDvo:bssursq) ([raw file](https://github.com/robotlocomotion/drake/blob/e34f69d8b1edef7a0a60262d441c2d6ea2a6afae/setup/ubuntu/source_distribution/install_prereqs.sh#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Motivation for error message may not be evident to users.

Consider rewording error message:
```
cat >&2 <<EOF
WARNING: Drake currently does not support installing Bazel on arm64 systems.
You will need to manually install a Drake compatible version.
For some options, review https://bazel.build/install/ubuntu
EOF
```
</blockquote></details>

If we're wordsmithing dead code, I'll offer my counter-take:

_WARNING: On Ubuntu arm64 systems, Drake's install_prereqs does not automatically install Bazel on your behalf. You will need to install Bazel yourself. See https://bazel.build` for instructions._

(1) Saying "does not support installing Bazel" isn't really the point, and "support" in there sends potentially confusing messages.

(2) I think we need to link to the root of their website, not a sub-page.  There's no telling when they might switch up their URLs for specific pages, and we'd never notice here.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 178 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NGIcluZ8YAizS21fBQn:-NGIigOk6gxWSb6us1a7:b-ba7jdc) ([raw file](https://github.com/robotlocomotion/drake/blob/e34f69d8b1edef7a0a60262d441c2d6ea2a6afae/setup/ubuntu/source_distribution/install_prereqs.sh#L178)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we're wordsmithing dead code, I'll offer my counter-take:

_WARNING: On Ubuntu arm64 systems, Drake's install_prereqs does not automatically install Bazel on your behalf. You will need to install Bazel yourself. See https://bazel.build` for instructions._

(1) Saying "does not support installing Bazel" isn't really the point, and "support" in there sends potentially confusing messages.

(2) I think we need to link to the root of their website, not a sub-page.  There's no telling when they might switch up their URLs for specific pages, and we'd never notice here.
</blockquote></details>

Sounds good to me!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @adeeb10abbas)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @adeeb10abbas)

___
*[`setup/ubuntu/source_distribution/install_prereqs.sh` line 178 at r5](https://reviewable.io/reviews/robotlocomotion/drake/18261#-NGMjdB24xbeLJFuGtvk:-NGMjdB30CUzGL5b74ST:bp7ixny) ([raw file](https://github.com/robotlocomotion/drake/blob/e97f7f4fa353a862b91c8629e38b7a82b0e1c3bf/setup/ubuntu/source_distribution/install_prereqs.sh#L178)):*
> ```Shell
>     echo "Bazel is already installed." >&2
>   else
>     echo
> ```

This can't possibly work, can it?  The string being echoed is on a different line than the `echo` statement.

See [here](https://github.com/RobotLocomotion/drake/blob/54b0625e0152ed40cfaad90e577b2887ae56c460/setup/ubuntu/install_prereqs.sh#L20-L21) for an example of how to line-wrap a long literal error message string.  In essence, each line has its own `""` string and we have `\` at end end of each line to make them be a single command.

**Comment by adeeb10abbas** [comment]
@jwnimmer-tri it does work for me (although the formatting seems a bit off) but I'll update it with the said format. thanks! 
```
./setup/ubuntu/source_distribution/install_prereqs.sh: line 181: WARNING: On Ubuntu arm64 systems, Drake's install_prereqs does not
    automatically install Bazel on your behalf. You will need to install
    Bazel yourself. See https://bazel.build for instructions.: No such file or directory

```

**Comment by jwnimmer-tri** [comment]
That's your bash prompt trying to execute the string as a command name, and failing (and so, the setup script is failing, defeating the purpose of this PR).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18261)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @adeeb10abbas)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Pull request merged**
