### PR TITLE
Add support for Jekyll Framework

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Working toward #13832 (bullet 4)

Generates or serves "getting_help.html" as an example page.

`bazel run //doc:serve_jekyll` will serve page locally at http://127.0.0.1:4000/getting_help.html

`bazel run //doc:gen_jekyll -- --out_dir <output directory>` will create page in specified `<output directory>`

Note: It is not necessary to build drake prior to running either command above.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri  for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488#-:-MQEGtJGAijQCnAE1OII:bfqt9h8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Ah, I see the confusion now.  The first commit 41d12ffa4af5f51f22212323dd58a414db3180a1 documents that it's a subset of the files from the contractors, but in fact some of _those_ were generated code.  For files like images that they created de-novo, saying "from contractors" is sufficient, but for files they created with tooling, we need to retcon how to do it so we know how everything came about, and that we can reproduce the work.  I was assuming that we'd go back from scratch and reproduce the bootstrapping infrastructure of that work, rather than re-using it.  We should probably pause here and have a telecon to make sure we have consensus on a smart plan before doing more work.

**Review by BetsyMcPhail — COMMENTED** [review]
Oh okay, glad this cleared things up (or showed the mis-match anyway). I've been using the contractors' work as a base - not re-generating unless absolutely necessary. I'm not sure what they created from scratch vs. used tools.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488#-:-MQEOJzE2AsmMNou-O4k:bt4cdm6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Review by BetsyMcPhail — COMMENTED** [review]
@jwnimmer-tri this is ready for another look when you have a chance. I'm happy to split into multiple PRs if that makes reviewing more straightforward.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488#-:-MQTQCvf1VSHKejHPnzc:b-7pc08i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jamiesnape** [comment]
Maybe split out https://github.com/RobotLocomotion/drake/pull/14488/commits/3d389c5e7a1742ddf1816d541b54693484bbf624 and get that into `master` ASAP, and also squash https://github.com/RobotLocomotion/drake/pull/14488/commits/92fb718450e8280eea0b5ef1373dbfcfae361058 and https://github.com/RobotLocomotion/drake/pull/14488/commits/c1fba5af88f5f676de6c07e5a4a8291e29d177bc.

**Comment by jamiesnape** [comment]
Actually, probably split c1fba5a and merge the obvious party with https://github.com/RobotLocomotion/drake/commit/3d389c5e7a1742ddf1816d541b54693484bbf624 before squashing.

**Comment by jamiesnape** [comment]
(Aside: When documentation builds switch exclusively to Focal, life gets a little easier. There were a lot of plugins added in 20.04. For whatever reason, there is only a bare minimum in Bionic, and we were very close to not being able to do this with Ubuntu packages.)

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_data/settings.yml, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14488#-MQYsIVX0E8APaYtbHKJ:-MQYsIVX0E8APaYtbHKK:b-izzayw) ([raw file](https://github.com/robotlocomotion/drake/blob/8f9e057cd8e94df532b9311ca4d4df3c01d66f2a/doc/_data/settings.yml#L169)):*
> ```YAML
> advanced_settings:
>   ajax_loading: true
>   analytics_code: ""
> ```

FYI If this gets enabled the site needs certain legal text adding.
___
*[doc/_layouts/default.html, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14488#-MQYo_nz5HbSaIEXLe78:-MQYo_nz5HbSaIEXLe79:bth364d) ([raw file](https://github.com/robotlocomotion/drake/blob/8f9e057cd8e94df532b9311ca4d4df3c01d66f2a/doc/_layouts/default.html#L27)):*
> ```HTML
> 		content="{% if page.url == "/" %}{{ site.data.settings.basic_settings.site_title }} – {{ page.title }}{% else %}{{ page.title }} – {{ site.data.settings.basic_settings.site_title }}{% endif %}" />
> 	<meta property="og:description" content="{{ page.description | strip_html | xml_escape }}" />
> 	<meta property="og:image" content="{{ page.featured_image | absolute_url }}" />
> ```

BTW Looks like all the Twitter and Facebook markup is going to need removing or fixing. We will not have the data to populate it, especially as having an image is required for it to validate, and most of our pages do not have that.

**Review by BetsyMcPhail — COMMENTED** [review]
ping @jwnimmer-tri  for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488#-:-MQwyxWJDfueLGILnvGz:b-6r9gmn)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I did start to look, but this is still a monster.  I need to start from zero locally and build an understanding of what all these files are for, whether it makes sense to treat them as primary sources, where they came from, and what license they are under.  Having 56 files in a "bootstrap the infrastucture PR" is still overwhelming.

To do that, I need to find a chunk of ~4 uninterrupted hours to work on developing and understanding and retrofitting documentation, which realistically looks like next Tuesday.

If we just want to get the tooling over the finish line, we need a "hello world" jekyll that isn't anything like the real Drake website, but literally just one or two files with no content nor function.  Having the drake and github styles, a 404 page, and real content here are not prereqs for bootstrapping a deploy and preview pipeline.

**Comment by jamiesnape** [comment]
@BetsyMcPhail `jekyll create <path> will get a basic Jekyll config. You may want to add some JavaScript for uglify to chew on (maybe we can still keep the JS that is added to `third_party`).

**Review by BetsyMcPhail — COMMENTED** [review]
Sounds good - I'll work on creating a "hello world" PR

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14488#-:-MQxBmdy4oi2GMIqq_8Y:b-l57irx)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jamiesnape** [comment]
Note that since we are using the Ubuntu packages, there is no layout at all included, and Jekyll needs at least one, which while simpler than the drake one, won't exactly be one or two files, unfortunately.

**Comment by jamiesnape** [comment]
@jwnimmer-tri Would it help you to get the files in `third_party` in first in a different PR. That can be multiple PR's for each addition too, if you prefer?

**Comment by jwnimmer-tri** [comment]
I don't think third-party files are of any particular concern.  Yes, they are easy to rubber stamp from a review perspective, with the only question being _why_ we are adding them, but the "why" is induced by the overall project and reproducing the site locally, so we can't just merge them first, and me testing the site takes time.

The _only_ thing I wanted to delegate to Kitware on this project is setting up the deployment pipeline / Jenkins integration.  The actual website content, style, license review, etc., I want to be on TRI's plate.  Get me a working preview / deploy pipeline for a boring hello world with no bells, whistles, third-party add ons, etc, and then on the TRI side I will iterate the PRs to get the website contents to where we want them.  It's only because Jenkins is behind the curtain where I have zero access, that I need to delegate that portion to y'all.  I need an MVP deployment pipeline with local preview, and can iterate from there.

A lot of stuff is on my plate this week and next, and I'm on the critical path for most of these reviews.  I can plausibly fit in a review of a hello world site PR + a python deployment tool PR, but also trying to incorporate the new website asses themselves is a bridge too far.

If there is a small PR that demonstrates hello world, let's keep going and do that.  If that is impractical given how Jekyll works, then let's suspend website work for a couple weeks, and instead try to get `apt` packages over the finish line.  That has been higher priority for a long time now, and seems like I'm not yet on the critical path to getting it done.

**Comment by jamiesnape** [comment]
Actually you don't need Jenkins access at all for this, but, anyway, we can strip out the content.

**Comment by jwnimmer-tri** [comment]
That's true, yes.  I think my real hesitation was trying to work through the https://github.com/RobotLocomotion/drake-ci/blob/master/driver/configurations/bazel/step-build-documentation.cmake changes on my own.

**Comment by jamiesnape** [comment]
> The only thing I wanted to delegate to Kitware on this project is setting up the deployment pipeline / Jenkins integration. The actual website content, style, license review, etc., I want to be on TRI's plate. Get me a working preview / deploy pipeline for a boring hello world with no bells, whistles, third-party add ons, etc, and then on the TRI side I will iterate the PRs to get the website contents to where we want them. It's only because Jenkins is behind the curtain where I have zero access, that I need to delegate that portion to y'all. I need an MVP deployment pipeline with local preview, and can iterate from there.

I re-read the issue and I missed any indication there that Kitware was to stop halfway through, and I don't think it was mentioned in any meeting?

**Comment by jwnimmer-tri** [comment]
I should have communicated more clearly.  I gave step 4 to you in the meeting (and noted at https://github.com/RobotLocomotion/drake/issues/13832#issuecomment-696819833), and I assumed we'd do only that much and stop, at which point I could take over again, but I probably never said that aloud.  I should have split the tasks into issues to make this more clear.

**Comment by jamiesnape** [comment]
Regarding the third-party libraries, they are look-and-feel or compatibility things, not tooling. I doubt they are optional given the theme.

Betsy will have the "hello world" for you tomorrow, the CI infrastructure can merge, and then you can reassign the issue. The `apt` packaging is a parallel task, as is keeping CI running.

**Comment by BetsyMcPhail** [comment]
Replaced by #14531

**Pull request closed without merging**
