### PR TITLE
geometry: Support Convex mesh.

### LINKED ISSUE #9443: geometry: support Convex Shape
Add `Convex` to the list of supported `Shape` (shape_specification.h) in `geometry`.  Currently we support `Sphere`, `Cylinder`, `Box`, and `HalfSpace` with limited support for `Mesh`.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Fix #9443 
1. Add Convex to shape_specification.
2. Skeleton code of ImplementGeometry(Convex) in ReifierTest and ShapeToLcm.
3. ImplementGeometry(Convex) in ProximityEngine by reading Obj file.

WIP.  I still need to set up unit tests and to complete the ImplementGeometry(Convex) in ReifierTest and ShapeToLcm.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9471)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
It's still WIP.  Please help me check on style compliance before I put more code.

@sherm1 for feature review, please.
@SeanCurtis-TRI for feature review, please.

**Comment by DamrongGuoy** [comment]
A design question to @SeanCurtis-TRI.  Since `fcl::Convex` does not take ownership of vertices and faces, and my `drake::geometry::Convex` only stores file name.  Who should own the vertices and faces?  In the future, we won't have this problem because [fcl#338](https://github.com/flexible-collision-library/fcl/pull/338) would make `fcl::Convex` own the vertices and faces via `shared_ptr`.

We only need a temporary solution before the new FCL is available.

**Comment by DamrongGuoy** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9471#-LMjBkYW1z6Xd27G0VO7:-LMjhKLV-NLoezBROROn:bq6zwg) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Sorry.  I forgot to run Lint.  CI showed me a few style errors from cpplint.  I'll update the files soon.
</blockquote></details>

CI is ok now. Thanks.

---

**Comment by jwnimmer-tri** [comment]
The reviewable assignments post missed the `+` ahead of the `@user`, so didn't change the "Assignees" field.  I'll add those folks by hand now.

**Pull request merged**
