### PR TITLE
Port PidController to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This adds `AutoDiffXd` support as a side-effect.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6749)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.

**Comment by siyuanfeng-tri** [comment]
I am a bit lost here. Is the high level goal to do DoToSymbolic() with a new scalar conversion mechanism? 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controller.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-KqYkb46skz97OY8S52u:-KqYkb46skz97OY8S52v:b-woc2dk) ([raw file](https://github.com/robotlocomotion/drake/blob/69ce66ee6dd48b80c198f460e7f450e99e238487/drake/systems/controllers/pid_controller.cc#L25)):*
> ```cpp
>                                 const Eigen::VectorXd& ki,
>                                 const Eigen::VectorXd& kd)
>     : LeafSystem<T>(SystemTypeTag<controllers::PidController>{}),
> ```

BTW I have no idea what's going on here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqYkIiYV7tLzT7_iGQ_:b-lxxeci)*

**Comment by jwnimmer-tri** [comment]
Yes.  Previously, the framework advised System authors to override `DoToSymbolic` and/or `DoToAutoDiffXd` in order to support converting the System to a new ScalarType.  As of #6684, the framework now recommends a new mechanism (that is less repetitive).  This PR is part of a series that ports the whole tree to use the new APIs, so that we can eventually remove the old ones.

The LeafSystem constructor being used now is documented at http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#af841e40eab7643924a2a39f9cdf9cbab.

Does that help?  Part of what I'm looking for here is to find where the docs are lacking.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqZ2LQfVM1s5nLMYE0x:b-sezclc)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqZ5CkhYcf3_UWgjd3k:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@ggould-tri for final platform review.

Incidentally, it doesn't seem we have testing on `PidController<symbolic::Expression>`.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqZCBzzFG9knMUwY4hw:bw6hacd)*

**Comment by jwnimmer-tri** [comment]
The `TEST_F(PidControllerTest, DirectFeedthrough)` covers symbolic form -- at least insofar as (non-)zero gains toggle the feedthrough though symbolic simplifications.  And the explicit template instantiation covers that it all compiles.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqZDiStwmRJYysaKtIl:bbeppzr)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6749#-:-KqZDdoy4hOgYtPjFQl3:bnfp4nl)*

**Pull request merged**
