### PR TITLE
Bazel build uses gtest-1.8.0 instead of gtest-1.7.0

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5569)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@david-german-tri , both reviews please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5569#-:-KfgvcPJRyGfLeG6dX1J:b-1p43ur)*

**Comment by hongkai-dai** [comment]
I built this PR with #5546 , the bazel + gcc 5 is happy. Thanks @soonho-tri for the quick fix!

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5569#-:-KfhQE4hRMh68-Fpjqg4:bnfp4nl)*

**Comment by david-german-tri** [comment]
Awesome find, @soonho-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5569#-:-KfhQElTUIh0zeXGAv9h:bd697hr)*

**Pull request merged**
