### PR TITLE
Fix mosek valgrind issue.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Still issues.

Locally, add `--gen-suppressions=all \` here https://github.com/RobotLocomotion/drake/blob/b563541e91f9242ae658a34ae6dd8a66af163e91/tools/dynamic_analysis/valgrind.sh#L15
and rerun and Valgrind will tell you what to add to the suppressions file.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705#-:-LB7Scs29wUub8M_9VEj:bx32gaj)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705#-:-LB7jE0o2-4PYwPN3hKY:b6vi582)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705)*

**Comment by sherm1** [comment]
Yuck! Please post these problems upstream to put the Mosek folks to work. Then, platform :lgtm:.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705#-:-LB7wcsx8mrQ3lFphBS0:brccsxf)*

**Comment by hongkai-dai** [comment]
Yes, as @m-chaturvedi pointed out, the CI takes 2.5 hours with memcheck, I will send a follow-up PR, to combine the suppression with regexp `...`. I will do that over the weekend.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8705#-:-LB7zfRU-U9k4r9g3Czd:berh37b)*

**Comment by jamiesnape** [comment]
> the CI takes 2.5 hours with memcheck

Our Clang builds are just horrendously slow under Valgrind for some reason compared to GCC. It is somewhere on my TODO list to investigate...

**Pull request merged**
