### PR TITLE
[ad] Fix gradients of in-place x*x and x/x

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #17622.  Towards #17492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656#-:-N8P6l-08wovtnHG8XcD:bmxilld)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW I really had to wrestle with the tests to convince myself they provided the coverage suggested. Ultimately, I did convince myself. But it was via the medium of removing the fixes and watching the tests fail and reasoning about the reported failure.

That said, I didn't have any concrete recommendation on helping future readers of the code grok those tests, so didn't say anything. It also wasn't clear to me how many times, after review, those tests would ever be read again.

Just wanted to share this passing thought.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656#-:-N8PJ24WDDqVcYoGuYIx:bp2l81c)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
What he said -- I'm having some trouble proving the tests to myself here.  I've commented my particular trouble.
That said, yes, I'm pretty sure it's all correct and :lgtm: apart from that.

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656#-:-N8PLAli6qsTDDsn2DSj:b-8dt5yq)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/ad/test/standard_operations_mul_test.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17656#-N8PJ0f-6uOuUXItf_Dv:-N8PJ0f-6uOuUXItf_Dw:bjf34ga) ([raw file](https://github.com/robotlocomotion/drake/blob/b98f695470e9100da40447a0d7f8225f5ffc7b2a/common/ad/test/standard_operations_mul_test.cc#L22)):*
> ```cpp
>   x *= y;
>   EXPECT_EQ(x.value(), 0.25);
>   EXPECT_EQ(x.derivatives(), Eigen::Vector3d::Unit(0));
> ```

If you mean to prove that a particular aliasing of the partials did or didn't occur, an operation that leaves the partials unchanged doesn't seem to me to prove it.

I think you probably need a value other than {0, 1} in your partials and likewise to explain whether you do or do not expect it to be changed (I assume the answer is "do"?) when accessed through x or y (both, I guess, although y being const may confuse the compiler?).

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656)* status: 1 unresolved discussion (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`common/ad/test/standard_operations_mul_test.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17656#-N8PJ0f-6uOuUXItf_Dv:-N8Pe2uOE-zHmtodKY8r:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/b98f695470e9100da40447a0d7f8225f5ffc7b2a/common/ad/test/standard_operations_mul_test.cc#L22)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

If you mean to prove that a particular aliasing of the partials did or didn't occur, an operation that leaves the partials unchanged doesn't seem to me to prove it.

I think you probably need a value other than {0, 1} in your partials and likewise to explain whether you do or do not expect it to be changed (I assume the answer is "do"?) when accessed through x or y (both, I guess, although y being const may confuse the compiler?).
</blockquote></details>

Done?

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17656)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
