### PR TITLE
[setup] Add bootstrap support for Noble

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This get us to the point of seeing the compilation errors.

There are still plenty of problems and failures building on Noble.  The objective here is just to get the point of seeing more of those errors.  To me, the review criteria should just be (1) does everything here seem like a strict improvement and (2) is the code sufficiently clear / documented.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20956)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs or +@mwoehlke-kitware for feature review, please.

**Comment by mwoehlke-kitware** [comment]
Seems reasonable without actually attempting to build in Noble (docker or otherwise).

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks!  I think it's OK to merge without testing in Docker.  CI will tell us (eventually) if we missed things.

Could I get an LGTM?  Then I'll assign a platform reviewer.

(Removing -@svenevs; we can use @mwoehlke-kitware as feature reviewer.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20956#-:-NqhyCJD27ngLicfQdTD:b-z3xcd6)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by mwoehlke-kitware** [comment]
Sure, I was sort-of feeling you out for how you'd feel about just an eyeball review.

Said eyeball review :lgtm:!

**Comment by jwnimmer-tri** [comment]
Yup, exactly, and thanks.

There's always a bit of chicken-and-egg spinning up a new platform. Eventually we'll have the full CI suite up and running to catch anything that got overlooked during some of this bootstrapping. Hopefully we get all of the relevant touchpoints right in these early PRs, but sometimes it's easy to overlook something.

+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20956#-:-NqisbpQBfdskVwml875:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),mwoehlke-kitware

**Pull request merged**
