### PR TITLE
Porting RenderEngineGl Step 1 - copy code to dev

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
We're porting code from another source into Drake. This is "step 1" (slightly muddied because we'd started with an alternate strategy). This copies the code over into a dev folder with private settings. The second commit in the PR updates the references to acknowledge that they exist in the dev folder; it updates headers to reference /dev/ and puts everything in the dev namespace.

Otherwise, there is (more or less) no new code from how it was in the originating source.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13129)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13129#-M5i_MfN1bA-SlBNwQfO:-M60F_4_9R9xfLuWngCL:bjhy3aw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Once all fixes are in, we should https://drake.mit.edu/jenkins.html#scheduling-an-on-demand-build for macOS to double check before merging.  Feel free to dismiss this discussion once that passes.
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

---

**Comment by SeanCurtis-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13129#-M5i_MfN1bA-SlBNwQfO:-M60FiOC3m8T4IyxOrcf:bjhy3aw) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
</blockquote></details>

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

---

**Comment by jwnimmer-tri** [comment]
I am going to cancel the macOS build, because master is broken on macOS currently so it will be nonsense anyway.

**Comment by jwnimmer-tri** [comment]
Also :lgtm: platform on the small non-dev BUILD file change.

**Pull request merged**
