### PR TITLE
Promote DRAKE_EXPECT_THROWS_MESSAGE et al. from geometry to common

### LINKED ISSUE #8003: Promote `geometry/test_utils/expect_error_message.h` to `drake/common`
There are some really useful testing utilities there that are worth promoting so everyone can benefit from them.
Now in use by:
 - `drake/geometry/` code.
 - `drake/multibody/multibody_tree` code, #7995.
 - `drake/systems/framework/test/diagram_builder_test.cc`

### PR DESCRIPTION
**Pull request by sherm1**
This PR replaces an assortment of bespoke macros for verifying in unit tests that an error message contains the expected text. Call sites are updated to use the now-standardized signatures. 

Semantics of the "IS_ARMED" forms has changed: as before the message is only _required_ in Debug
(actually `DRAKE_ENABLE_ASSERTS`), but is now _optional_ in Release (previously it was _forbidden_ in Release). _If_ the Release build actually throws, the error message must meet the same requirements as in Debug.

Renamed from EXPECT_ERROR_MESSAGE to DRAKE_EXPECT_THROWS_MESSAGE.

Prompted by [reviewer request](https://reviewable.io/reviews/robotlocomotion/drake/8372#-L7o6Anm1opaM6EjAmVz) in #8372.

I am not adding standalone unit tests for these macros but they are tested extensively by the many unit tests in which they are used.

Resolves #8003.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8396)

### CODE REVIEW

**Comment by sherm1** [comment]
+@amcastro-tri for feature review please, since this was your idea!
+@ericcousineau-tri for platform review please, per rotation.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-:-L7vVHv-2cbd9elGQaD-:bdzic2y)*

**Comment by sherm1** [comment]
/cc @seancurtis-tri if you want to review this as well or instead, please do.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-:-L7vX7PcBSuTHwyZ1e68:bk3j4aq)*

**Comment by SeanCurtis-TRI** [comment]
With @amcastro-tri travelling, feel free to swap me for him.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7vakiEt0wDx5BbidvI:b-o2y7jo)*

**Comment by sherm1** [comment]
OK, thanks: -@amcastro-tri +@seancurtis-tri for feature review.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7vevIB2xIx6HGPDSbE:b-ju6jtk)*

**Comment by amcastro-tri** [comment]
Excellent! :lgtm: 

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yPBsa5Lo012JIx0nj:-L7yPBsa5Lo012JIx0nk:b-bz4ym9) (no related file):*
BTW. Probably it'd be a good idea to mirror `drake_asserth.h` regarding how to document these with Doxygen.

---

*[geometry/BUILD.bazel, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yPsaHXwKkvfc4GeAd:-L7yPsaHXwKkvfc4GeAe:btrj642) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/geometry/BUILD.bazel#L195)):*
> ```Python
>     deps = [
>         ":frame_kinematics",
>         "//common/test_utilities",
> ```

BTW maybe `common/test_utilities:expect_error_message` alone is enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7yP9lnx5lSya4wsh9m:b-6d87ss)*

**Comment by EricCousineau-TRI** [comment]
First pass done with a suggestion on naming, and a request for some basic testing since it's now in `common`.

---

Reviewed 19 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[common/test/type_safe_index_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yhFbao10_oTEBgNZ0:-L7yhFbao10_oTEBgNZ1:byrvog1) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test/type_safe_index_test.cc#L44)):*
> ```cpp
>   AIndex invalid;  // Default constructor.
>   EXPECT_FALSE(invalid.is_valid());
>   DRAKE_EXPECT_ERROR_MESSAGE_IF_ARMED(
> ```

Given that this is specifically for catching exception, can we mirror the naming for `EXPECT_THROWS` / `ASSERT_THROWS` and rename this to `DRAKE_EXPECT_THROWS_MESSAGE*``?

---

*[common/test_utilities/expect_error_message.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yiDOwwK4Y1gj5MR2c:-L7yiDOwwK4Y1gj5MR2d:b-cbzg49) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test_utilities/expect_error_message.h#L46)):*
> ```objc
> #else
> 
> #define DRAKE_EXPECT_ERROR_MESSAGE_IF_ARMED(expression, exception, regexp) \
> ```

Should all of these macros be tested? e.g. making `test/expect_error_message_test.h`, and give the test two flavors: with and without `DRAKE_ASSERT_IS_DISARMED`? (Nothing upstream has to be changed, as simple guards could be used.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7yimyJ-VscDCiLUe3V:brpn7ib)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: 

With agreement on various comments:

1. Doxygenation that mirrors `drake_assert.h` (strong agree)
2. Unit tests on armed/disarmed (mild agree -- I do find the argument, that they are currently being exercised, a compelling one.)
3. `DRAKE_EXPECT_THROWS_MESSAGE` change (mild agree)

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7ynX7b0bKNNyVdocNN:bmh1pr5)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[common/test_utilities/expect_error_message.h, line 46 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-L7yiDOwwK4Y1gj5MR2c:-L7ypU4y9sZu6gW1hN8o:b-c5wgtm) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test_utilities/expect_error_message.h#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should all of these macros be tested? e.g. making `test/expect_error_message_test.h`, and give the test two flavors: with and without `DRAKE_ASSERT_IS_DISARMED`? (Nothing upstream has to be changed, as simple guards could be used.)
</blockquote></details>

BTW Agreed that having them used in testing is great for positive tests. However, negative tests are another story.

If there is a way to meta-test GTest, that'd be great (e.g. `EXPECT_GTEST_FAILURE`); if not, then sure, we can just stick to positive tests (and use manual inspection to ensure that it fails as expected for negative cases).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396)*

**Comment by sherm1** [comment]
Added good doxygen, renamed macros, per f2f with @seancurtis-tri changed semantics of the "IS_ARMED" versions to allow Release builds to _optionally_ throw, but if they do it still has to be the right message. I added a TODO regarding unit tests but that's too much for me to tackle now. This PR is a substantial improvement over the status quo already. If anyone else wants to attempt those tricky tests, please do! (In a separate PR) 

I substantially re-engineered the macros in the header to avoid duplication -- ptal.

---

Review status: 9 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yPBsa5Lo012JIx0nj:-L7zMWxBISpqyZM-3GJQ:bfdmcx0) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. Probably it'd be a good idea to mirror `drake_asserth.h` regarding how to document these with Doxygen.
</blockquote></details>

Done, ptal.

---

*[common/test/type_safe_index_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yhFbao10_oTEBgNZ0:-L7zNR91m4WjSWDqUCYT:b-jsrqj9) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test/type_safe_index_test.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Given that this is specifically for catching exception, can we mirror the naming for `EXPECT_THROWS` / `ASSERT_THROWS` and rename this to `DRAKE_EXPECT_THROWS_MESSAGE*``?
</blockquote></details>

Done. Great idea.

---

*[common/test_utilities/expect_error_message.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yiDOwwK4Y1gj5MR2c:-L7zNUrw8Cli4j6ENSvn:b-8gpzim) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test_utilities/expect_error_message.h#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#catching-failures
</blockquote></details>

Added a TODO but I don't want to attempt these tricky tests. This PR is a side project to improve the status quo which I think it has done -- I want to get back to the caching PR. Love to see someone add unit tests to improve it further, in a separate PR please.

---

*[geometry/BUILD.bazel, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yPsaHXwKkvfc4GeAd:-L7zO-P6UE3gzv97DRVV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/geometry/BUILD.bazel#L195)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW maybe `common/test_utilities:expect_error_message` alone is enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7zMavDScWmEfRsE8hN:b-jzsoga)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor comment on file naming to reflect macro names.

---

Reviewed 2 of 20 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[common/test_utilities/expect_error_message.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7yiDOwwK4Y1gj5MR2c:-L7zPLp8KIV8ZDi2ccs5:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test_utilities/expect_error_message.h#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Added a TODO but I don't want to attempt these tricky tests. This PR is a side project to improve the status quo which I think it has done -- I want to get back to the caching PR. Love to see someone add unit tests to improve it further, in a separate PR please.
</blockquote></details>

OK Sounds good!

---

*[common/test_utilities/expect_error_message.h, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7zPPz4vBRZn11mQQFb:-L7zPPz6CiaiSHQfuchw:b1xrtme) ([raw file](https://github.com/robotlocomotion/drake/blob/32081bac17c1a8e52b89b33fa8f1bee0c3405755/common/test_utilities/expect_error_message.h#L6)):*
> ```objc
> #include <string>
> 
> // TODO(sherm1) Add unit tests for these macros.
> ```

BTW Should this file be renamed to `exepect_throws_message` or something to that effect?

---

*[common/test_utilities/expect_error_message.h, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L7zPeiQlPo3-VMew_M1:-L7zPeiQlPo3-VMew_M2:bizjjxt) ([raw file](https://github.com/robotlocomotion/drake/blob/32081bac17c1a8e52b89b33fa8f1bee0c3405755/common/test_utilities/expect_error_message.h#L11)):*
> ```objc
> /** Unit test helper macro for "expecting" an exception to be thrown but also
> testing the error message against a provided regular expression. This is
> like Gtest's `EXPECT_THROW` but is fussier about the particular error message.
> ```

BTW capitalization nit Most occurrences of Google Test abbreviations tends to use `GTest` over `Gtest` for mixed case:
https://github.com/google/googletest#related-open-source-projects

Can that be changed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L7zQLgrpfqUDTBHXhM2:byydafh)*

**Comment by sherm1** [comment]
Thanks @amcastro-tri, @seancurtis-tri, @ericcousineau-tri. All comments addressed. Just waiting for CI now.

---

Review status: 5 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[common/test_utilities/expect_error_message.h, line 46 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-L7yiDOwwK4Y1gj5MR2c:-L8--gnC5TrVvy8wrC5v:bu7tdfu) ([raw file](https://github.com/robotlocomotion/drake/blob/ae06269fda520ce45345d48b181c6d2663fc3fbd/common/test_utilities/expect_error_message.h#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Sounds good!
</blockquote></details>

Thanks for creating an issue. I modified the TODO to reference it.

---

*[common/test_utilities/expect_error_message.h, line 6 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-L7zPPz4vBRZn11mQQFb:-L8--1cLDaKJ7PJWOWGC:b-v39q9g) ([raw file](https://github.com/robotlocomotion/drake/blob/32081bac17c1a8e52b89b33fa8f1bee0c3405755/common/test_utilities/expect_error_message.h#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Should this file be renamed to `exepect_throws_message` or something to that effect?
</blockquote></details>

Done. Yep -- I should have caught that myself. Thanks!

---

*[common/test_utilities/expect_error_message.h, line 11 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-L7zPeiQlPo3-VMew_M1:-L8--7fZ1c8OW81WzBJF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32081bac17c1a8e52b89b33fa8f1bee0c3405755/common/test_utilities/expect_error_message.h#L11)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW capitalization nit Most occurrences of Google Test abbreviations tends to use `GTest` over `Gtest` for mixed case:
https://github.com/google/googletest#related-open-source-projects

Can that be changed here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396#-:-L8--pUm4lq2NIxCXmCl:b-2e6rqy)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 16 files at r3.
Review status: 6 of 19 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8396)*

**Comment by SeanCurtis-TRI** [comment]
The CI gods are angry...

---

Reviewed 1 of 21 files at r1, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-Ba2Ry7qLCrIyFs5D:b-ocrwaq) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
> ```Python
> install(
>     name = "install",
>     allowed_externals = [DRAKE_RESOURCE_SENTINEL],
> ```

BTW Did you mean to commit reformatting changes? It is a bit of a torment to reviewers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L8-DOgwZHTaoDo9Sbck:buxh8zg)*

**Comment by jwnimmer-tri** [comment]
*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-ENigeiP_3iG_wQ5H:bjorqez) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Did you mean to commit reformatting changes? It is a bit of a torment to reviewers.
</blockquote></details>

I suspect #8381 contributed to the problem.  In any case, since BUILD files have exactly one allowed whitespace formatting, this will be fixed in order for CI to pass, so I wouldn't sweat it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396)*

**Comment by sherm1** [comment]
Trying again with BUILD file unscrambled.

---

Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-KjyKZ_etATeC_aEw:b-84i4p6) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I suspect #8381 contributed to the problem.  In any case, since BUILD files have exactly one allowed whitespace formatting, this will be fixed in order for CI to pass, so I wouldn't sweat it.
</blockquote></details>

Done. Argggh! Some tool secretly shuffles those whenever I edit that BUILD file. I forgot to fix it with buildifier before commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-:-L8-LFBWjKf5roRreCoM:b-gx8u5g)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-OzWZDq_JDxoXfRbb:b-wj9en7) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. Argggh! Some tool secretly shuffles those whenever I edit that BUILD file. I forgot to fix it with buildifier before commit.
</blockquote></details>

I figured that was the CI error.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396)*

**Comment by jwnimmer-tri** [comment]
*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-PtLg38-8Um2tEAAP:bl5epl2) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I figured that was the CI error.  
</blockquote></details>

Yeah, that's CLion.  If you don't want it to do that, you can turn off its auto-formatting per the linked issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[common/BUILD.bazel, line 422 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8396#-L8-Ba2Ry7qLCrIyFs5C:-L8-W-UnV-odfldnKP-H:b-xf3y25) ([raw file](https://github.com/robotlocomotion/drake/blob/7889d9b3ffc9780f0bf2a59a16271655f9a7e821/common/BUILD.bazel#L422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, that's CLion.  If you don't want it to do that, you can turn off its auto-formatting per the linked issue.
</blockquote></details>

Done -- disabled autoformatting in CLion. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8396)*

**Pull request merged**
