### PR TITLE
Upgrade meshcat to latest commit

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Make the environment background fix available to Drake (meshcat PR [#152](https://github.com/meshcat-dev/meshcat/pull/152)).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+(status: single reviewer ok) 
+(status: do not merge) 
+@RussTedrake for both reviews

This is waiting on https://github.com/rdeits/meshcat/pull/152. Once that merges, we'll update things here. In the meantime, this allows you to see the effects of that PR in drake.



The left column is the result of this fix. The right column is the state of master due to the bug introduced in https://github.com/rdeits/meshcat/pull/150.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021#-:-Nc621zx6OkZV6yJWyax:blrw02r)* status: LGTM missing from assignee RussTedrake(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) Meshcat PR has merged. We're ready to go on this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021#-:-NcHONrS6fQlZrwV_17s:bhu5yd5)* status: LGTM missing from assignee RussTedrake(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@RussTedrake +@xuchenhan-tri for on-call platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021#-:-NcPubzBEc9AtLre1Y7-:b-ojgwv4)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@xuchenhan-tri +@jwnimmer-tri for tuesday on-call platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021#-:-NcQajaa6hrw40gptEQ2:b-tcas8h)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.  Tested with meshcat_manual_test (sans joystick).

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20021#-:-NcSfOS4D7ClkNyn_WAN:bir7zay)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Pull request merged**
