### PR TITLE
pydrake: Add guidance that types should be bound before use in functions

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up from #15410

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-Mf-N1mfCoKnWTKITfgN:b-t5m2ip)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Quick request for elaboration.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-Mf-QIUFDlaJq1Q1lYXB:b4id738)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15429#-Mf-Py8DATV3leH9pIWd:-Mf-Py8E4urkpRL8jPKR:b-ci7ypi) ([raw file](https://github.com/robotlocomotion/drake/blob/e0ff0cb91162f0cc32c782558f08c86aeb6ebfe7/bindings/pydrake/pydrake_doxygen.h#L201)):*
> ```objc
> anonymous namespaces. Avoid `using namespace` directives otherwise.
> - For function / method docstrings, please ensure that any types used in your
> function signature are already bound. Otherwise, the generated docstring from
> ```

nit: I need you to elaborate on "already bound". You don't mean "already" in the historical sense (i.e., it's been bound for years), but already bound in the sense that by the time you get to your bindings, we've already parsed the headers of all dependencies' bindings, right? This directly affects ordering of contents in the file. I think that's a key issue that can't be implied; it should be spelled out explicitly.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15429#-Mf-Py8DATV3leH9pIWd:-Mf-R8eVAXDJSzA67S3S:b-h0z45k) ([raw file](https://github.com/robotlocomotion/drake/blob/e0ff0cb91162f0cc32c782558f08c86aeb6ebfe7/bindings/pydrake/pydrake_doxygen.h#L201)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I need you to elaborate on "already bound". You don't mean "already" in the historical sense (i.e., it's been bound for years), but already bound in the sense that by the time you get to your bindings, we've already parsed the headers of all dependencies' bindings, right? This directly affects ordering of contents in the file. I think that's a key issue that can't be implied; it should be spelled out explicitly.
</blockquote></details>

Done. Definitely in the latter, expand to "have already had their binding code executed"
(used passive tense, but I think this hopefully disambiguates?)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15429#-Mf-Py8DATV3leH9pIWd:-Mf-RTUN0f9ggm3uG6Yl:bediwbk) ([raw file](https://github.com/robotlocomotion/drake/blob/e0ff0cb91162f0cc32c782558f08c86aeb6ebfe7/bindings/pydrake/pydrake_doxygen.h#L201)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Definitely in the latter, expand to "have already had their binding code executed"
(used passive tense, but I think this hopefully disambiguates?)
</blockquote></details>

Can't say I'm a big fan of "binding code executed" as being particularly descriptive. What does it mean for "code to be executed"?  Not exactly a technical term. I can't offer up something more complex, because I can only speculate about the issue.

For example, I assume the scope of the issue is limited to a single compilation unit. (For example, `mbp` depends on `geometry`, but we certainly don't include the `geometry_py.cc` file in the `plant_py.cc` file. And your fix for mathematical program was about re-ordering a single file.

So, for all of those meander-y, speculative-y reasons, I feel you could hold your readers had a bit more. I, for a fact, know that there are members of the dynamics team that won't have a clue what you mean with this text.

**Comment by jwnimmer-tri** [comment]
The most recent wording seems like it might help at least 50% of the total audience for these notes, even if it still leaves some developers behind.  That seems like a monotonic improvement, so maybe we can just merge this as-is and improve it later again if need be?  Having a reminder that >80% of the platform review team would understand seems better than allowing this idea to be completely forgotten.  WDYT?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I can contentedly get out of the way. Sadly, I feel I'm on the wrong side of the 50% divider. I don't have a sense of what it means for "binding code to be executed". Or, more particularly, how to judge the *order* of binding code execution. If I had to look at some code and determine if this guidance has been satisfied, I couldn't do it.

That said, at the very least, the presence of the paragraph would tell readers to be aware that there is some order of operations that matters. Even if they aren't sure what it is, they at least know there's a question to ask and that does represented an improvement.

Perhaps it would be simplest if we swapped assignment. You obviously feel good about merging it, and I feel fine about not interfering (a lesser level of enthusiasm).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-MoZWRvm8GBh0n8M2R2K:b-q5sudz)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
How about "Bindings should import their dependencies prior to binding code that uses them"?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I was thinking that might be the key. The whole thing is murky because you have to think about python code executing, even though you're only writing C++ code (similar to when I got burned by folder entanglement). This also helps clarify in my mind why we have `import` declarations in our binding definitions.

Certainly, it's true, that omitting a required `import` can lead to straight out failures in tests. But this particular requirement is more subtle. In the case of docstrings, if the *only* reason a module needs to be imported is to get the write type definition, then there will be no *failure* in anything except the documentation. Admittedly, it seems that would only come about if the tests were incomplete which is a defect in its own right.

On the other hand, this guidance is probably offered because we had such a scenario in which "completing" the unit tests was still insufficient for leading to the necessary import.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-MoZYZp4CozIgMGLG4zD:b-otykxr)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
(The other observation worth noting here is that documentation is not really the right way to solve this.  We should have a documentation regression test, that asserts that neither type-mumbo-jumbo nor hex-pointer-repr-mumbo-jumbo make it into the help strings.  That linter error message would prescribe the correct fix -- "import what you use" or "default arguments must have a repr".)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Always love the idea of correctness being automatically validated.  :)

So, then as I get this, the guidance is:

For every type referenced in a particular set of bindings, the type must either be bound there (with that binding evaluated before the reference), or there must be an invocation like `py::module::import("pydrake.math");` of the binding module in which the type *is* bound.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-MoZbvKS-OX8mSNZI2dY:b4zlie5)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
That sounds correct to me.

**Review by SeanCurtis-TRI — COMMENTED** [review]
We can do one of the following: I can push a change and you can review, of you could push a change and I could stick with my review assignment. Preference?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-MoZtY0-2XAWyxix5eLZ:bsgf7v5)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
If you can push a fix, I'm happy to review and then we can leave it to Eric to complete a final review during his on-call day this Wednesday.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll do so later this morning.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-MoczeP28f7kgt1TSFc2:b-voxdn8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've tweaked the language based on what was there and the discussion above. I didn't include a specific example in the code because there was no obvious, compact mechanism that would create a nice link. I *could* simply reference a file by name (as in "see `bindings/pydrake/systems/framework_py.cc` as an example").

-@seancurtis-tri 
+@jwnimmer-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-ModFNrvDvosetomJhBQ:bi2cb7o)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for platform review

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-ModKUEr37JZ9aN11usH:b-6jso97)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/pydrake_doxygen.h, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15429#-Mf-Py8DATV3leH9pIWd:-ModKOZI1a16WZD6Rcid:bvo7wnq) ([raw file](https://github.com/robotlocomotion/drake/blob/e0ff0cb91162f0cc32c782558f08c86aeb6ebfe7/bindings/pydrake/pydrake_doxygen.h#L201)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Can't say I'm a big fan of "binding code executed" as being particularly descriptive. What does it mean for "code to be executed"?  Not exactly a technical term. I can't offer up something more complex, because I can only speculate about the issue.

For example, I assume the scope of the issue is limited to a single compilation unit. (For example, `mbp` depends on `geometry`, but we certainly don't include the `geometry_py.cc` file in the `plant_py.cc` file. And your fix for mathematical program was about re-ordering a single file.

So, for all of those meander-y, speculative-y reasons, I feel you could hold your readers had a bit more. I, for a fact, know that there are members of the dynamics team that won't have a clue what you mean with this text.
</blockquote></details>

OK Sorry for the delay on my part, but this text looks better!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

FYI As I understand it, failure to import-what-you-use can sometimes also lead to runtime errors (not just docstring errors), but I don't know that it's worth saying so in the text here.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-ModeIw3ER4ycLHRs4Qg:b-s8m218)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: as platform, reviewing text.

> FYI As I understand it, [...]

Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-ModnMET0Vr-eBjHdf7_:b-pl26y9)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15429#-:-ModniWb-IXK6u-IX_tm:b-uwkowd)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
Forced in docs-only change.

**Pull request merged**
