### PR TITLE
Fix tolerances for test to pass Macintosh Continuous Integration

### PR DESCRIPTION
**Pull request by mitiguy**
… Macintosh build

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7065)

### CODE REVIEW

**Comment by mitiguy** [comment]
@drake-jenkins-bot  mac-clang-bazel-continuous-release-bazel   please

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-KuW3HZHpswXWXNoSqGa:-KuW3HZHpswXWXNoSqGb:b-7c08x5) ([raw file](https://github.com/robotlocomotion/drake/blob/a7143d0cb2a5c303f8657008623fb999a6b6ff90/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L114)):*
> ```cpp
> //
> // TODO(liang.fok) Re-enable this test. This test was disabled because it was
> // causing the Mac CI pipelines to fail. See #7056.
> ```

BTW, this PR should include removal of the above TODO comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-clang-bazel-continuous-everything-release please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by mitiguy** [comment]
Feature review: @liangfok 
Platform review: @seancurtis-tri 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-:-KuWhaDv9Ixn1gu9shU6:b-tfgkqa)*

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.
@drake-jenkins-bot mac-clang-bazel-experimental-everything please.

**Comment by liangfok** [comment]
:lgtm: assuming the Macintosh CI pipelines pass.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-:-KuZZc7FU_JiDHJHrMSz:bo2ktvr)*

**Comment by liangfok** [comment]
+@liangfok and +@seancurtis-tri  so they appear as assignments in Reviewable.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-:-KuZ_DEJrjy0B0rLIvI0:b56bax8)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-Ku_7UAxVAlbJEho3tM7:-Ku_7UAxVAlbJEho3tM8:b-iy4n5k) ([raw file](https://github.com/robotlocomotion/drake/blob/84dcf1caa6a6b4dccea31942fc01a9b746dbebb5/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L62)):*
> ```cpp
>   // the multipliers were made significantly less strict.
>   const double absError = MG_chaotic_babyboot.absError;
>   const double multiplier = 7.0E3;
> ```

BTW this seems too heavy of a hammer. Previously the tolerances are increasingly relaxed for the higher derivatives (which seems right!) but now they are all the same. Assuming this works on Mac, please consider backing off so that the tolerances make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065)*

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.
@drake-jenkins-bot mac-clang-bazel-experimental-everything please.

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: pending CI and additional TODO.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-Kua_TemAZAxhTANXbwb:-Kua_TemAZAxhTANXbwc:b6sghel) ([raw file](https://github.com/robotlocomotion/drake/blob/0f736b8fea7080f01e83db5602d5d11d37839ae8/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L60)):*
> ```cpp
>   // Note: After passing pre-merge CI (continuous integration) and merging this
>   // test to master, the test failed post-merge CI on a Macintosh build (for
>   // qBDt), so the qADt and qBDt multipliers were made less strict.
> ```

BTW Please include a TODO about removing this factor. Let the current CI round finish (as well as the mac experimental stuff). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-:-Kua_mxZLdogkj2EsBvu:b76h3cq)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7065#-:-Kuaetlv4eGo4nMoMd22:bnfp4nl)*

**Pull request merged**
