### PR TITLE
Remove System1 flavor of SimpleCar and TrajectoryCar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3474)

### CODE REVIEW

**Comment by liangfok** [comment]
+@liangfok 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-:-KRmiVQBsgM52l6SqLbi:b-gyxe3j)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for concurrent platform review, please.  (Trying to get merged this morning.)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-:-KRn8wbV3j0QdWjHYGSd:b51cvc6)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by liangfok** [comment]
Done with first pass. PTAL.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/automotive/simple_car-inl.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnA0eNYchkFJhkCnIL:-KRnA0eNYchkFJhkCnIM:b-juivig) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L43)):*
> ```objc
>   DRAKE_ASSERT_VOID(systems::System<T>::CheckValidOutput(output));
> 
>   // Obtain the state.
> ```

BTW: nit: optional: replace "Obtain" with "Obtains".

---

*[drake/automotive/simple_car-inl.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAAf2iqyp31hXwtsw:-KRnAAf2iqyp31hXwtsx:b-juivig) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L50)):*
> ```objc
>   DRAKE_ASSERT(state);
> 
>   // Obtain the output pointer.
> ```

BTW: nit: optional: replace "Obtain" with "Obtains".

---

*[drake/automotive/simple_car-inl.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnANvexGBx3NkCOvdh:-KRnANvexGBx3NkCOvdi:b-juivig) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L70)):*
> ```objc
>   DRAKE_ASSERT_VOID(systems::System<T>::CheckValidContext(context));
> 
>   // Obtain the state.
> ```

BTW: nit: optional: replace "Obtain" with "Obtains".

---

*[drake/automotive/simple_car-inl.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAOLmP8eSKZnoCO-N:-KRnAOLmP8eSKZnoCO-O:b-juivig) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L77)):*
> ```objc
>   DRAKE_ASSERT(state);
> 
>   // Obtain the input.
> ```

BTW: nit: optional: replace "Obtain" with "Obtains".

---

*[drake/automotive/simple_car-inl.h, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAP2AaVzTJ_UDst7c:-KRnAP2AaVzTJ_UDst7d:b-juivig) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L85)):*
> ```objc
>   DRAKE_ASSERT(input);
> 
>   // Obtain the result structure.
> ```

BTW: nit: optional: replace "Obtain" with "Obtains".

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnATMxE_KmPZCdThY9:-KRnATMxE_KmPZCdThYA:b-ncnmor) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
> ```objc
>                                          const DrivingCommand<T>& input,
>                                          SimpleCarState<T>* rates) const {
>   // Apply simplistic throttle.
> ```

BTW: nit: optional: replace "Apply" with "Applies".

Also consider removing the word "simplistic" since that is already implied given the fact that this is within a class called `SimpleCar`.

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBIcLRbstN8PPRwdQ:-KRnBIcLRbstN8PPRwdR:bboemj7) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
> ```objc
>                                          const DrivingCommand<T>& input,
>                                          SimpleCarState<T>* rates) const {
>   // Apply simplistic throttle.
> ```

Missing "a" before "throttle".

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBYGF3kvBq1HWc9e7:-KRnBYGF3kvBq1HWc9e8:bwons9q) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
> ```objc
>                                          const DrivingCommand<T>& input,
>                                          SimpleCarState<T>* rates) const {
>   // Apply simplistic throttle.
> ```

BTW, the code executes through applying both the throttle _and_ brake, which seems odd. Just wanted to make sure this is in intended logic. An alternative would be to disable the throttle if `input.throttle() != 0` and only apply the brake.

---

*[drake/automotive/simple_car-inl.h, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAVe5MjUAcAgufpgo:-KRnAVe5MjUAcAgufpgp:b-ncnmor) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L107)):*
> ```objc
>   new_velocity = std::min(new_velocity, static_cast<T>(config_.max_velocity));
> 
>   // Apply simplistic brake.
> ```

BTW: nit: optional: replace "Apply" with "Applies".

Also consider removing the word "simplistic" since that is already implied given the fact that this is within a class called `SimpleCar`.

---

*[drake/automotive/simple_car-inl.h, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAXa1h802Bym95JAR:-KRnAXa1h802Bym95JAS:bi2g47o) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L107)):*
> ```objc
>   new_velocity = std::min(new_velocity, static_cast<T>(config_.max_velocity));
> 
>   // Apply simplistic brake.
> ```

Missing "a" before "simplistic"

---

*[drake/automotive/simple_car-inl.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAWIHgb88metzl7rp:-KRnAWIHgb88metzl7rq:b-ui7mo5) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L112)):*
> ```objc
>   new_velocity = std::max(new_velocity, static_cast<T>(0.));
> 
>   // Apply steering.
> ```

BTW: nit: optional: replace "Apply" with "Applies".

---

*[drake/automotive/simple_car-inl.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBCIau3Qc3J0F6-Ck:-KRnBCIau3Qc3J0F6-Cl:blizcqf) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L112)):*
> ```objc
>   new_velocity = std::max(new_velocity, static_cast<T>(0.));
> 
>   // Apply steering.
> ```

Missing "a" before "steering" and "angle" after "steering".

---

*[drake/automotive/simple_car-inl.h, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnCXAozCgmYI7xcYOb:-KRnCXAozCgmYI7xcYOc:b-xwg24f) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L113)):*
> ```objc
> 
>   // Apply steering.
>   T sane_steering_angle = input.steering_angle();
> ```

BTW: nit: Is this as opposed to an `insane_steering_angle`? I don't see such a variable in scope.

Consider `bounded_steering_angle`.

---

*[drake/automotive/simple_car.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnDFwWIwgaMWs39lEN:-KRnDFwWIwgaMWs39lEO:b-pmka5r) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car.h#L60)):*
> ```objc
>  public:
>   explicit SimpleCar(const drake::lcmt_simple_car_config_t& config =
>                          SimpleCarDefaults::kDefaultConfig);
> ```

Awkward spacing. `clang-format`?

---

*[drake/automotive/trajectory_car.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnDbPVTDxotQQAFSem:-KRnDbPVTDxotQQAFSen:b2g55da) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/trajectory_car.h#L63)):*
> ```objc
>  private:
>   void DoEvalOutput(double time, SimpleCarState<T>* output) const {
>     // Trace the curve at a fixed speed.
> ```

BTW: nit: optional: Replace "Trace" with "traces".

---

*[drake/automotive/trajectory_car.h, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnDhM-HpcUy0H9Opgl:-KRnDhM-HpcUy0H9Opgm:byhkh72) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/trajectory_car.h#L67)):*
> ```objc
>     const Curve2<double>::PositionResult pose = curve_.GetPosition(distance);
> 
>     // Convert pose to output type.
> ```

BTW: nit: optional: Replace "Convert" with "Converts".

---

*[drake/automotive/trajectory_car.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnE7tXOAZvWTri1SAK:-KRnE7tYurthYPs24ai1:bdp6bbw) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/trajectory_car.h#L70)):*
> ```objc
>     output->set_x(pose.position[0]);
>     output->set_y(pose.position[1]);
>     output->set_heading(std::atan2(pose.position_dot[1], pose.position_dot[0]));
> ```

BTW: Should there be special logic here to handle the case when `pose.position_dot[0] == 0`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-:-KRnFQEGHN_klZLDNwId:b2maxaj)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/simple_car-inl.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnA0eNYchkFJhkCnIL:-KRnGpTA72PRMO6zV1uW:b-aaz1d2) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: optional: replace "Obtain" with "Obtains".
</details>
I will refuse, forevermore, to write implementation comments in present tense.  Imperative is what all the cool kids use.

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBIcLRbstN8PPRwdQ:-KRnHf8ueYY_pPPT84XO:bus09pi) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing "a" before "throttle".
</details>
I don't see why this is a defect.  It seems grammatical to me.

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBYGF3kvBq1HWc9e7:-KRnHkMDJ3SVAYc7KOCT:bhwcxy9) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, the code executes through applying both the throttle _and_ brake, which seems odd. Just wanted to make sure this is in intended logic. An alternative would be to disable the throttle if `input.throttle() != 0` and only apply the brake.
</details>
This implementation avoids conditional branching, which might end up being useful for some kinds of analysis.  It is what Rick originally came up with, and I guess my default is to leave it alone until we have a motivating example to do otherwise.

---

*[drake/automotive/simple_car-inl.h, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAXa1h802Bym95JAR:-KRnHSyn5DVmDGiacZtD:bus09pi) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L107)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing "a" before "simplistic"
</details>
I don't see why this is a defect.  It seems grammatical to me.

---

*[drake/automotive/simple_car-inl.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBCIau3Qc3J0F6-Ck:-KRnH9gr7yAXyQxjlVrT:b-qh5qwj) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L112)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing "a" before "steering" and "angle" after "steering".
</details>
The use here is to apply "steering" as a physical concept, not the literal "steering_angle" variable.

---

*[drake/automotive/simple_car.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnDFwWIwgaMWs39lEN:-KRnGcgqWHJR1N80T4Xg:b-l2g66z) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car.h#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Awkward spacing. `clang-format`?
</details>
That is what clang-format does; the default argument assignment is indented versus the variable type and name.

---

*[drake/automotive/trajectory_car.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnE7tXOAZvWTri1SAK:-KRnGI02eN7FkxUGZGfD:b-64fopj) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/trajectory_car.h#L70)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: Should there be special logic here to handle the case when `pose.position_dot[0] == 0`?
</details>
That should never happen.  Added assert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474)*

**Comment by liangfok** [comment]
Done with second pass. :lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car-inl.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnA0eNYchkFJhkCnIL:-KRnKWrOHEQhM8UvH2i0:b-btxyt) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I will refuse, forevermore, to write implementation comments in present tense.  Imperative is what all the cool kids use.
</details>
Then let's formalize it by placing it in the style guide.

Marking this as "satisfied".

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBIcLRbstN8PPRwdQ:-KRnKaX20OPqFsq_U46j:bahwree) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't see why this is a defect.  It seems grammatical to me.
</details>
Sorry, I meant there's a missing "a" before "simplistic". 

I'll mark this as "satisfied" since I'm no grammar expert.

---

*[drake/automotive/simple_car-inl.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBYGF3kvBq1HWc9e7:-KRnKrhFAq1gFpq7ttcE:bl00cea) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This implementation avoids conditional branching, which might end up being useful for some kinds of analysis.  It is what Rick originally came up with, and I guess my default is to leave it alone until we have a motivating example to do otherwise.
</details>
OK SGTM.

---

*[drake/automotive/simple_car-inl.h, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnAXa1h802Bym95JAR:-KRnKwCGdiVzdWzQQsIy:b-ke1631) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L107)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't see why this is a defect.  It seems grammatical to me.
</details>
I'll mark this as "satisfied" since I'm no grammar expert.

---

*[drake/automotive/simple_car-inl.h, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnBCIau3Qc3J0F6-Ck:-KRnL-RS2OBKVTbkw_u2:bl00cea) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The use here is to apply "steering" as a physical concept, not the literal "steering_angle" variable.
</details>
OK SGTM.

---

*[drake/automotive/simple_car.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnDFwWIwgaMWs39lEN:-KRnL3RvxrahwG5X07gQ:bnla4dy) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car.h#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> That is what clang-format does; the default argument assignment is indented versus the variable type and name.
</details>
OK TIL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-:-KRnLAByByrxCH61Emn_:b-o0guw4)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/simple_car-inl.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnA0eNYchkFJhkCnIL:-KRnLZnSjer4gbCgGey8:bt7c9zn) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Then let's formalize it by placing it in the style guide.
> 
> Marking this as "satisfied".
</details>
The `cppguide` says that for function APIs to use "descriptive" (not imperative), but doesn't not speak to implementation comments. 

Do you mean to add Drake style text that imperative for implementation comments is allowed, or that it is required?  I don't think we should require it, and I don't think we need to list out everything that is allowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/simple_car-inl.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-KRnA0eNYchkFJhkCnIL:-KRnNyXX8E7pN2bjSMqg:b-qt9uh7) ([raw file](https://github.com/robotlocomotion/drake/blob/a2bf38d7a4363ecbfa903c1e3ac8b6ec323645fa/drake/automotive/simple_car-inl.h#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `cppguide` says that for function APIs to use "descriptive" (not imperative), but doesn't not speak to implementation comments. 
> 
> Do you mean to add Drake style text that imperative for implementation comments is allowed, or that it is required?  I don't think we should require it, and I don't think we need to list out everything that is allowed.
</details>
Required since I believe being consistent is important.

I already created a PR: https://github.com/RobotLocomotion/drake/pull/3479.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3474#-:-KRo3ckQeNRiQK5ZydCS:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Pull request merged**
