### PR TITLE
Enable linearization of discrete-time systems

### PR DESCRIPTION
**Pull request by jadecastro**
Linearize systems that are composed of purely continuous or discrete states.  If discrete, then the discrete states must be of a single state group, and the discrete update events must be periodic.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6935)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@russtedrake for feature review, please (since I think you had authored `Linearize()`).

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-:-KsjP3L5xhYrcdjmURaP:b-n6zso0)*

**Comment by RussTedrake** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmvpwcWShNsbVX4eJq:-KsmvpwcWShNsbVX4eJr:b-6x2zbi) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/linear_system.cc#L85)):*
> ```cpp
> 
>   // Verify that the system has only one discrete, periodic update event.
>   // TODO(jadecastro) Clean up this implementation upon resolution of #6878.
> ```

FYI - thanks for finding #6878.  cc @edrumwri 

---

*[drake/systems/primitives/linear_system.cc, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmwHYVsVrUMTBZZ66w:-KsmwHYVsVrUMTBZZ66x:b-vxeyop) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/linear_system.cc#L135)):*
> ```cpp
> 
>   // Ensure that x1 = f(x0,u0) == x0.
>   if (!is_approx_equal_abstol(math::autoDiffToValueMatrix(autodiff_x1_vec),
> ```

for the sake of consistency, either the above method (for derivatives) should also use is_approx_equal_abstol or this should call isZero on f(x0,u0) - x0.

---

*[drake/systems/primitives/linear_system.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmwugnaySSY61wWBRT:-KsmwugnaySSY61wWBRU:bl28ek8) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/linear_system.cc#L185)):*
> ```cpp
>   const Eigen::VectorXd x0 = (context.has_only_continuous_state())
>       ? context.get_continuous_state_vector().CopyToVector()
>       : context.get_discrete_state()->get_vector()->CopyToVector();
> ```

prefer get_discrete_state(0)->get_vector()->get_value()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/test/linear_system_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmxYG7j8Tlzinpw7f-:-KsmxYG7j8Tlzinpw7f0:b-4linu) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/test/linear_system_test.cc#L192)):*
> ```cpp
>                               MatrixCompareType::absolute));
>   EXPECT_TRUE(CompareMatrices(D, linearized_system->D(), tol,
>                               MatrixCompareType::absolute));
> ```

please also check that the time period was set correctly.

and really, we should check that if you create a system with a more complicated discrete time event handler, that it throws.  (and change the DRAKE_DEMAND to DRAKE_THROW_UNLESS).  But I can see waiting on that pending resolution of #6878, and letting that PR handle it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935)*

**Comment by jadecastro** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmwHYVsVrUMTBZZ66w:-KsnaSfh0f-QlWNxj-jI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/linear_system.cc#L135)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

for the sake of consistency, either the above method (for derivatives) should also use is_approx_equal_abstol or this should call isZero on f(x0,u0) - x0.
</blockquote></details>

Done.

---

*[drake/systems/primitives/linear_system.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmwugnaySSY61wWBRT:-Ksnav6rK6wvKjpZrkdK:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/linear_system.cc#L185)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

prefer get_discrete_state(0)->get_vector()->get_value()
</blockquote></details>

Done. 

---

*[drake/systems/primitives/test/linear_system_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-KsmxYG7j8Tlzinpw7f-:-KsncTpSGp6d9wkcn8iG:b88ok5p) ([raw file](https://github.com/robotlocomotion/drake/blob/24768a502ddd81ddd6c88276d870d5c5ffc4a23e/drake/systems/primitives/test/linear_system_test.cc#L192)):*
> please also check that the time period was set correctly.

Absolutely - thanks.  

BTW, I've added a small exception-checking test when used on a simple discrete system without a periodic update. We should enrich the test once we have a solution to #6878, so that we can exception-handle more complex setups, e.g. multi-rate systems whose rates might not be integer multiples of one another.  I have expanded the TODO in the code to mention this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935)*

**Comment by RussTedrake** [comment]
:lgtm:  nice.  thanks.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-:-KspZe9QfNb63f4kDLbb:b-eny3nf)*

**Comment by jadecastro** [comment]
+@seancurtis-tri for platform review -- thanks.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-:-KsphFQH6xKsiHe1KnmG:bd9cr8i)*

**Comment by SeanCurtis-TRI** [comment]
-@SeanCurtis-TRI +@soonho-tri for platform review

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-:-KssWhwLBQ5oS2Ly5p-H:b-1woh1s)*

**Comment by soonho-tri** [comment]
:lgtm: 

Happy to see 100% test coverage!

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6935#-:-KssrOZizbbMKhBann5S:blzetw)*

**Pull request merged**
