### PR TITLE
Remove support for clang 3.9

### PR DESCRIPTION
**Pull request by jamiesnape**
Looks like possibly there were some regressions introduced during the switchover to clang 4.0 relating to flags, so it will be interesting to see if there are any breakages on this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7812)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm: feature and platform.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7812#-L3FKND8W5plo9HBwaSk:-L3FKND9yLvwskxpY3g9:bhlzwrv) ([raw file](https://github.com/robotlocomotion/drake/blob/bbb43b0ec51c3146f269786b33f6ccb33a033203/setup/ubuntu/16.04/install_prereqs.sh#L25)):*
> ```Shell
> 
> apt update
> apt install --no-install-recommends lsb-release wget
> ```

BTW Do you want to move `wget` down into the long list below now?  I could see arguments either way.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7812#-L3FKodZijUsJXcNNn10:-L3FKodZijUsJXcNNn11:b-7udc7r) ([raw file](https://github.com/robotlocomotion/drake/blob/bbb43b0ec51c3146f269786b33f6ccb33a033203/setup/ubuntu/16.04/install_prereqs.sh#L30)):*
> ```Shell
> 
> # Install the APT dependencies.
> apt update -y
> ```

BTW Is this line needed anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7812#-:-L3FMRNHx1N92p4zE-ca:b-1i7w6f)*

**Comment by jamiesnape** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7812#-L3FKND8W5plo9HBwaSk:-L3FVFcrVcB6MdoY0T3A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bbb43b0ec51c3146f269786b33f6ccb33a033203/setup/ubuntu/16.04/install_prereqs.sh#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do you want to move `wget` down into the long list below now?  I could see arguments either way.
</blockquote></details>

Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7812#-L3FKodZijUsJXcNNn10:-L3FVG8eur-aqkDlw3ey:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bbb43b0ec51c3146f269786b33f6ccb33a033203/setup/ubuntu/16.04/install_prereqs.sh#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this line needed anymore?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7812)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7812)*

**Pull request merged**
