### PR TITLE
framework_py: Bind and test Parameters

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
\cc @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8092)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-:-L5VJ7dwD9FL2L_I84rz:b-hod6u6)*

**Comment by RussTedrake** [comment]
yeah!  thanks!

**Comment by sherm1** [comment]
:lgtm:, one FYI ...

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py.cc, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-L5VkdSjCx1cstEWDgGH:-L5VkdSktlBaxS3SgShr:bjxqkhj) ([raw file](https://github.com/robotlocomotion/drake/blob/87cac0530037699487a99ff5808f4ce518f2495d/bindings/pydrake/systems/framework_py.cc#L621)):*
> ```cpp
> 
>   // TODO(eric.cousineau): Determine what the use case is for non-owned
>   // AbstractValues. Seems like a potentially confusing asymmetry right now
> ```

FYI, do you mean non-owned in the sense that a Diagram's abstract values are just a bunch of pointers to abstract values owned by the LeafSystems?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-:-L5VlQ_iveHePxGBqEJt:bwlodol)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-L5VkdSjCx1cstEWDgGH:-L5ZbLdRsjmrzRphTjAg:bi3bk10) ([raw file](https://github.com/robotlocomotion/drake/blob/87cac0530037699487a99ff5808f4ce518f2495d/bindings/pydrake/systems/framework_py.cc#L621)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI, do you mean non-owned in the sense that a Diagram's abstract values are just a bunch of pointers to abstract values owned by the LeafSystems?
</blockquote></details>

OK Ah, yes -- though it still seems kind of confusing that this is exposed in user-visible code. Is there a way that we can constrain this case to only be available to sharing between `Diagram` and `LeafSystem`s?

I ask because it seems like we have three flavors of handling non-slicing `Clone`able data types:

* Pass in `unique_ptr<T>` - model values, etc.
* Pass in `const T&` - something that will be `Clone`d or copied in some way
* Pass in `const T*` - non-owned reference.

Given that we have the second case, I'm not sure what the third case really buys us - is there a way that we can hide it?

---

*[bindings/pydrake/systems/test/value_test.py, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-L5Vm5vtzu22Lgxn-c_e:-L5ZdiBSFnbkAGhK959Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87cac0530037699487a99ff5808f4ce518f2495d/bindings/pydrake/systems/test/value_test.py#L164)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, consider also checking that the parameter value is actually a string?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8092)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/systems/framework_py.cc, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8092#-L5VkdSjCx1cstEWDgGH:-L5Zi_g10_9xq14it1tJ:b-4f4lw2) ([raw file](https://github.com/robotlocomotion/drake/blob/87cac0530037699487a99ff5808f4ce518f2495d/bindings/pydrake/systems/framework_py.cc#L621)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK Ah, yes -- though it still seems kind of confusing that this is exposed in user-visible code. Is there a way that we can constrain this case to only be available to sharing between `Diagram` and `LeafSystem`s?

I ask because it seems like we have three flavors of handling non-slicing `Clone`able data types:

* Pass in `unique_ptr<T>` - model values, etc.
* Pass in `const T&` - something that will be `Clone`d or copied in some way
* Pass in `const T*` - non-owned reference.

Given that we have the second case, I'm not sure what the third case really buys us - is there a way that we can hide it?
</blockquote></details>

Oops - I'll table this discussion for slack so this PR can make it in. (Simplified comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8092)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8092)*

**Pull request merged**
