### PR TITLE
Remove DRAKE_EXPORT from examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove DRAKE_EXPORT from a examples. This is a portion of #3973.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4073)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri has accepted my invitation to review these.  Thanks!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-:-KW3fCr036vpzl33vY1v:bji7e5x)*

**Comment by sammy-tri** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Atlas/atlasUtil.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47XtYvy8FBUCZui2T:-KW47XtYvy8FBUCZui2U:by9gvg6) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/Atlas/atlasUtil.h#L3)):*
> ```objc
> #pragma once
> 
> #include "drake/common/drake_export.h"
> ```

Remove this too?

---

*[drake/examples/Pendulum/pendulum_swing_up.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47gAf1HRq_cVJal2s:-KW47gAf1HRq_cVJal2t:bcankia) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/Pendulum/pendulum_swing_up.h#L5)):*
> ```objc
> #include <memory>
> 
> #include "drake/common/drake_export.h"
> ```

Remove include as well?

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47oDfJFE8cOJ2vcJ7:-KW47oDfJFE8cOJ2vcJ8:b-mz62on) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/schunk_gripper/simulated_schunk_system.cc#L3)):*
> ```cpp
> #include "drake/examples/schunk_gripper/simulated_schunk_system.h"
> 
> #include "drake/common/drake_export.h"
> ```

Remove include also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4073)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4073)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Atlas/atlasUtil.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47XtYvy8FBUCZui2T:-KW49HjTr3xzvvvYrCvU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/Atlas/atlasUtil.h#L3)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Remove this too?
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_swing_up.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47gAf1HRq_cVJal2s:-KW49GaAeFfu4KT2hfdf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/Pendulum/pendulum_swing_up.h#L5)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Remove include as well?
</details>
Done.

---

*[drake/examples/schunk_gripper/simulated_schunk_system.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-KW47oDfJFE8cOJ2vcJ7:-KW49GrBZxwv90mcoskI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc0fe4a5214cdffd1c4975768a7c6fc1c58f57c7/drake/examples/schunk_gripper/simulated_schunk_system.cc#L3)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Remove include also?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4073)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4073#-:-KW4CMXP5drS1UthzWdh:bnfp4nl)*

**Pull request merged**
