### PR TITLE
Adds the steady-state Kalman filter and an Acrobot example using it

### PR DESCRIPTION
**Pull request by RussTedrake**
Note: this inevitably includes #4254, #4256, and #4257, which is a pain (all my reviewers are on vacation!).  The commits are separated and clean, so I should be able to break this up into smaller PRs as necessary once those are merged.  (I also need to add a little more documentation)

Also adds controllability/observability tests for linear systems, and cleans up the LQR API, per the discussion in #4260.  

For fun, here's a shot of my screen while graphically debugging my kalman-filter-based balancing, using signallogger and lcm_call_matlab to make my plots.
screen shot 2016-11-26 at 11 43 50 pm

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4261)

### CODE REVIEW

**Comment by naveenoid** [comment]
Thanks for this..I will give it a pass once the do-no-review tag is removed.

**Comment by RussTedrake** [comment]
@naveenoid -- i've added the documentation.  the review will become much easier when the other PRs are merged, and as I said I could potentially break this up into smaller pieces, but I consider it viable.

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/controllers/linear_quadratic_regulator.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4261#-KXfJkRpxy3ou81kHoo3:-KXfJkRpxy3ou81kHoo4:bzgkjsz) ([raw file](https://github.com/robotlocomotion/drake/blob/bbcae9dde0b824d21a74bcb54652057c9f93993a/drake/systems/controllers/linear_quadratic_regulator.cc#L19)):*
> ```cpp
>   const Eigen::MatrixXd K = R_cholesky.solve(B.transpose() * S);
> 
>   return K;
> ```

can we return s as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4261)*

**Comment by RussTedrake** [comment]
closing this and will PR it in small chunks.

**Pull request closed without merging**
