### PR TITLE
Remove PID controller from iiwa_controller.

### PR DESCRIPTION
**Pull request by sammy-tri**
Recent fixes in drake-iiwa-driver pretty much mean it's worse than useless.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5657)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5657#-:-KgQDD_iBnr3YHokUAXL:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5657#-:-KgQ_6ai2QR03pNi0ukP:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5657#-:-KgQqHuQLIcHBAi6MD5M:b-gbk9vg)*

**Comment by ggould-tri** [comment]
Definitely does exactly what it says; I assume feature review has verified that this intention is sane :)
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5657#-:-KgULv2GX6jAsoaZF6G4:b64kvrr)*

**Pull request merged**
