### PR TITLE
tutorials: Show derivatives of basic mbp computations w.r.t. mass

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
nbviewer preview: https://nbviewer.jupyter.org/github/EricCousineau-TRI/drake/blob/feature-tutorial-mbp-inertial-diff/tutorials/multibody_plant_autodiff_mass.ipynb

Context:
- StackOverflow: https://stackoverflow.com/q/67754125/7829525
- [Drake Slack](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1622172889020700)

\cc @RussTedrake @sadraddini 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@joemasterjohn for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103#-:-MatDbWtEwVCUOim3aL7:b7bdkxp)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Comment by EricCousineau-TRI** [comment]
Ping?

**Review by joemasterjohn — COMMENTED** [review]
Sorry this one slipped by me. Looking now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103#-:-MbN6jFI682rizrWB-Rk:b-rv7gn1)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few suggestions.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103#-:-MbNHN4-1iHw64Hhb_NG:b3u5n0x)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbN740X8Vy0VSJ_lbHS:-MbN740X8Vy0VSJ_lbHT:b-yk5w2b) ([raw file](https://github.com/robotlocomotion/drake/blob/d6e113e3b8be80a0249dbc9f7ac38463ef9efb52/tutorials/multibody_plant_autodiff_mass.ipynb#L14)):*
> ```
>     "We create a simple `MultibodyPlant` (`MultibodyPlant_[float]`). This means you *could*\n",
>     "parse it from an URDF / SDFormat file.\n",
>     "We then convert the system to `AutoDiffXd`, and set the parameters we desire. In this case,\n",
> ```

nit: "set the values and partial derivatives of the parameters we desire."
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbN7Mij9e8CYvfiCjTw:-MbN7Mij9e8CYvfiCjTx:b-uhw61w) ([raw file](https://github.com/robotlocomotion/drake/blob/d6e113e3b8be80a0249dbc9f7ac38463ef9efb52/tutorials/multibody_plant_autodiff_mass.ipynb#L15)):*
> ```
>     "parse it from an URDF / SDFormat file.\n",
>     "We then convert the system to `AutoDiffXd`, and set the parameters we desire. In this case,\n",
>     "we want $\\frac{\\partial{f}}{\\partial{m}}$, where $f$ is just some arbitrary expression.\n",
> ```

I would be more specific here. \mathbf{f} is a vector valued function of \mathbf{m} = (m_1, m_2) and we want the Jacobian of that function.

For a symbol for that Jacobian I would use the bold f and m in the partial derivative notation you have or put brackets around it and use i,j indices.
i.e:
```
$[ \\frac{\\partial{f_i}}{\\partial{m_j}} ]$
```

 
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbNDH3E7LYP-_90D9oh:-MbNDH3E7LYP-_90D9oi:b-alivhx) ([raw file](https://github.com/robotlocomotion/drake/blob/d6e113e3b8be80a0249dbc9f7ac38463ef9efb52/tutorials/multibody_plant_autodiff_mass.ipynb#L18)):*
> ```
>     "\n",
>     "In our case, we choose $f$ to be generalized forces at the default / home configuration.\n",
>     "Also in this case, we choose $m \\in \\mathbb{R}^2$ just to show how to choose gradients for\n",
> ```

nit: technically ℝ₊² since we don't currently support negative mass.
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbNELXBAXXS1KAzulwc:-MbNELXBAXXS1KAzulwd:bxmz1z3) ([raw file](https://github.com/robotlocomotion/drake/blob/d6e113e3b8be80a0249dbc9f7ac38463ef9efb52/tutorials/multibody_plant_autodiff_mass.ipynb#L52)):*
> ```
>     "        mass=2.0,\n",
>     "        p_PScm_E=[0, 0, 0],\n",
>     "        # N.B. This value may not be physically \"useful\". I just guessed.\n",
> ```

nit: Guess might imply that there are correct values. I would just say that the rotational inertia is unimportant for this calculation and thus arbitrarily chosen.
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbNFVwKDzwIxom1egfS:-MbNFVwKDzwIxom1egfT:b-bj2viq) ([raw file](https://github.com/robotlocomotion/drake/blob/d6e113e3b8be80a0249dbc9f7ac38463ef9efb52/tutorials/multibody_plant_autodiff_mass.ipynb#L81)):*
> ```
>     "For forward-mode automatic differentiation, we must ensure that specify our gradients\n",
>     "according to our desired independent variables. In this case, we want $m_1$ and $m_2$\n",
>     "to be independent, so we ensure their gradients are distinct unit vectors. (You could\n",
> ```

nit: Mention that every other quantity in the plant (state, other parameters, etc.) are considered constants wrt mass and thus have 0 valued gradients (which AutoDiffXd defaults to).

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Neat! Platform :lgtm_strong: with a few nits.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103#-:-MbgVHmd2CRTWmXmEgKF:b-5o1m9s)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgQpD2B5ViU8i40blz:-MbgQpD2B5ViU8i40bm-:bugg373) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L13)):*
> ```
>     "\n",
>     "We create a simple `MultibodyPlant` (`MultibodyPlant_[float]`). This means you *could*\n",
>     "parse it from an URDF / SDFormat file.\n",
> ```

BTW I would have written "_a_ URDF" because I pronounce it in my head as "you are dee eff". I'm not sure the "urrr diff" pronunciation is common.
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgRkjvEY86UYqs7bMp:-MbgRkjvEY86UYqs7bMq:b-89rdc6) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L24)):*
> ```
>     "- [Underactuated: System Identification](http://underactuated.csail.mit.edu/sysid.html) - at present, this only presents the symbolic approach for `MultibodyPlant`.\n",
>     "- [`Modeling Dynamical Systems`](./dynamical_systems.ipynb)\n",
>     "- [`Mathematical Program MultibodyPlant Tutorial`](./mathematical_program_multibody_plant.ipynb)"
> ```

The above two links didn't work for me when I ran this locally. Should they have?
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgTcNZ2DXvkTELc2xN:-MbgTcNZ2DXvkTELc2xO:b-73hqqv) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L81)):*
> ```
>    "metadata": {},
>    "source": [
>     "Here we now populate the parameters we wish to take the gradient with respect to.\n",
> ```

nit: this sentence achieved escape velocity. Consider "Now populate the parameters with respect to which we wish to take gradients." or "We need to take gradients with respect to particular parameters. Populate those parameters now."
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgUJ0D5566BSAadmEJ:-MbgUJ0D5566BSAadmEK:bb9jtgb) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L142)):*
> ```
>    "outputs": [],
>    "source": [
>     "@np.vectorize\n",
> ```

nit: this is mysterious (to me anyway). Please consider a comment saying why you need this decorator.

**Review by sherm1 — COMMENTED** [review]
Dumb question: should I be concerned that executing the notebook modified my local copy of the .ipynb file? It seems to have updated the execution_counts from null to a number.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103#-:-MbgVptW05QcgszrKQEK:bc8sumq)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @joemasterjohn and @sherm1)

___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgQpD2B5ViU8i40blz:-Mbgr_CR3bnK85T05YeI:bqsss3p) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I would have written "_a_ URDF" because I pronounce it in my head as "you are dee eff". I'm not sure the "urrr diff" pronunciation is common.
</blockquote></details>

Done. I like the "urrr diff" pronunciation, but I won't die on that hill ;)
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgRkjvEY86UYqs7bMp:-Mbgh62w78ARQpXwuRcK:b9ctlf5) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The above two links didn't work for me when I ran this locally. Should they have?
</blockquote></details>

OK Nah, they won't; they should only work if you run it via `nbviewer` or `binder`, or some other workflows.

I'll submit a quick follow-up PR to try expand on that expectation.
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgTcNZ2DXvkTELc2xN:-Mbgrcdu2ypVyst85z3q:b-1gt7y8) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this sentence achieved escape velocity. Consider "Now populate the parameters with respect to which we wish to take gradients." or "We need to take gradients with respect to particular parameters. Populate those parameters now."
</blockquote></details>

Done. Took second with some minor smoothing - thanks!
___
*[tutorials/multibody_plant_autodiff_mass.ipynb, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15103#-MbgUJ0D5566BSAadmEJ:-MbgrfOE42TWvRfiOzPs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52a9eef0a9dcfcc48e5aea6db53d9c95d6100075/tutorials/multibody_plant_autodiff_mass.ipynb#L142)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this is mysterious (to me anyway). Please consider a comment saying why you need this decorator.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
> Dumb question: should I be concerned that executing the notebook modified my local copy of the .ipynb file? It seems to have updated the execution_counts from null to a number.

Yes, that's par for the course for python notebooks.

In the menu, there is a "Clear all output cells" command that will undo those changes.  If you had purposefully edited the source code and wanted to preserve those edits, but undo the chaff, you'd want to that option before committing your changes to git.  Since you were only running without making edits, you can also just revert the file.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15103)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Thank y'all!

**Comment by EricCousineau-TRI** [comment]
> I'll submit a quick follow-up PR to try expand on that expectation.

I'm going to punt on this. Extra time budget burned out on Anzu stuff.

**Pull request merged**
