### PR TITLE
add velocity to iiwa_status_message.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7040)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. +@sammy-tri for platform review. thanks! 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKYxANvVBGOXdESagZ:bh96pee)*

**Comment by sammy-tri** [comment]
Is there a corresponding change to drake-iiwa-driver in the works to populate this message?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKfL_56hHHqWPLccTL:b-f11eik)*

**Comment by siyuanfeng-tri** [comment]
yes. 
although i am planning to wait on for the spartan's drake master pr to go in first. Otherwise I need to patch the old drake master with this. what do you think? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKgXt3rFoBYESn4nbA:b-2uu7nt)*

**Comment by sammy-tri** [comment]
I'm becoming less happy with the driver depending on drake, and drake having the authoritative copy of the LCM definition...  I like what happened with https://github.com/RobotLocomotion/optitrack-driver better where drake depends on that small package which has the LCM type.

Anyway, afaict the current situation seems to me like:
 * drake-iiwa-driver needs to find drake using CMake to get the lcmtypes
 * only spartan knows how to configure drake-iiwa-driver's build environment to actually make that work
 * as a result, drake-iiwa-driver and spartan need to be updated at the same time anyway
 * but there's a catch!  Some people are building iiwa_controller on drake master and using it with spartan's build of drake-iiwa-driver

So, uh...  I don't actually know how to change the iiwa lcm messages without breaking something if drake-iiwa-driver continues to depend on drake for the message definition.

Maybe I should start working on inverting the dependency?  Other ideas?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKlSvMFq_dgXIpz6fQ:bwscmuw)*

**Comment by naveenoid** [comment]
+1 for Sammy's comments on cross dependence. Can we simply exactly copy the optitrack way of doing things? What prevents us?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKpN11Ven7bwsoUguI:b2eudyv)*

**Comment by sammy-tri** [comment]
The only speed bump I can think of is that I'm not totally sure how to let other users replace the FRI submodule from within a bazel build...  I think the current hack of asking users who don't have access to our copy to just untar theirs into the source dir would still work as long as we could figure out how to properly deal with getting a BUILD file into the right place.  (oh, and writing a BUILD file for the FRI stuff which shouldn't be too bad)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7040#-:-KuKsKNX-LudE2J2V8Vc:b-s0xox3)*

**Comment by siyuanfeng-tri** [comment]
closing, should resolve #7045 first

**Pull request closed without merging**
