### PR TITLE
[workspace] Remove drake_visualizer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Concludes #16215.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@DamrongGuoy for feature review of the files in `//examples/...`, please.

+@rpoyner-tri for feature review of the files in `//tools/...`, please.

+@SeanCurtis-TRI  for platform review per schedule, please, as well feature review of the remaining code:
- `//bindings/...`
- `//geometry/...`
- `//multibody/...`
- `//visualization/...`

(If you'd like a second set of eyes on any of the pieces, feel free to ping one of the other reviewers to also take a look.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-:-NqrxmVN5pP071GmioLW:bgnz48r)* status: LGTM missing from assignees DamrongGuoy,rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 51 of 70 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-:-NqtU3LsEsZWAYJGw7YC:bnfp4nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),DamrongGuoy

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some tiny things.

> Reviewed 70 of 70 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-:-Nr1X9BX4gwolg1-6M1R:b8zx4ei)* status: 3 unresolved discussions, LGTM missing from assignee DamrongGuoy

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1Seb25fHTnDv3yg6C:-Nr1Seb25fHTnDv3yg6D:b-hn6no6) (no related file):*
Extant references to `drake_visualizer`:

 - `/drake/BUILD.bazel`
    - This one actually configured the build to apparently accommodate `drake_visualizer`. Perhaps the act is still necessary, but then, at least, the justification should change.
- `/drake/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc`
    - Outdated instructions.
- `/drake/geometry/meshcat.html`
   - Another case of deprecated justification. Might as well kill text.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1TcGZ3W04Q_GORqz0:-Nr1TcG_EojWPYRIgtI2:b1qpoa4) (no related file):*
BTW It occurs to me that `DrakeVisualizer` might benefit from an eventual rename. Something more directly reflecting the underlying technology as `MeshcatVisualizer` has. `LcmVisualizer`? Or some such thing.

___
___
*[`geometry/profiling/README.md` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1VBfA5aAREZtHsihR:-Nr1VBfA5aAREZtHsihS:b-aycl1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f0d7b69874a6b9a15e97373ffe6e89236c8a92b/geometry/profiling/README.md#L17)):*
> ```Markdown
> contact model.
> 
> To visualize the contact surface and pressure, you're out of luck because we
> ```

btw: The SOL resolution here feels dissatisfying. Certainly, we can visualize hydroelastic contact surfaces. Perhaps a TODO suggesting the binary get updated accordingly? (It would mean it's not necessarily meldis friendly, but I shouldn't think it needs to be.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1TcGZ3W04Q_GORqz0:-Nr1dqaL9OIwhhRyQXy8:b-x1t8qq) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It occurs to me that `DrakeVisualizer` might benefit from an eventual rename. Something more directly reflecting the underlying technology as `MeshcatVisualizer` has. `LcmVisualizer`? Or some such thing.
</blockquote></details>

I think the overriding concern would be whether we juts get rid of it entirely (by enhancing Meshcat to encompass its use cases).

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1Seb25fHTnDv3yg6C:-Nr1fHLh6kdTXywAeHVb:bvmnc1f) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Extant references to `drake_visualizer`:

 - `/drake/BUILD.bazel`
    - This one actually configured the build to apparently accommodate `drake_visualizer`. Perhaps the act is still necessary, but then, at least, the justification should change.
- `/drake/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc`
    - Outdated instructions.
- `/drake/geometry/meshcat.html`
   - Another case of deprecated justification. Might as well kill text.
</blockquote></details>

(1) Done.

(2) Done.

(3) I think the text is right and proper as-is.  The reason we have those values is to be consistent with what Drake has always looked like for many years.  If there are wording clarifications necessary to highlight that point, just let me know.

___
___
*[`geometry/profiling/README.md` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1VBfA5aAREZtHsihR:-Nr1e_0u0Qgjy51idc0O:b-9dxa1) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f0d7b69874a6b9a15e97373ffe6e89236c8a92b/geometry/profiling/README.md#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: The SOL resolution here feels dissatisfying. Certainly, we can visualize hydroelastic contact surfaces. Perhaps a TODO suggesting the binary get updated accordingly? (It would mean it's not necessarily meldis friendly, but I shouldn't think it needs to be.)
</blockquote></details>

I added some more text in the spirit you were looking for, I hope.  I can see the point of giving more actionable advice.

(In my mind, whatever disaster has hit this code already happened a year ago or more.  This PR is just surfacing the existing condition, so I'm trying to do as little work as possible.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963)* status: LGTM missing from assignee DamrongGuoy

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1TcGZ3W04Q_GORqz0:-Nr1gnIhDBBUv_UxwrD9:b604djx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the overriding concern would be whether we juts get rid of it entirely (by enhancing Meshcat to encompass its use cases).
</blockquote></details>

I'm open to that as well. But it can all be deferred.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1Seb25fHTnDv3yg6C:-Nr1guvXCwFjqXK67Hkb:b-o4mflx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1) Done.

(2) Done.

(3) I think the text is right and proper as-is.  The reason we have those values is to be consistent with what Drake has always looked like for many years.  If there are wording clarifications necessary to highlight that point, just let me know.
</blockquote></details>

I'm good.

___
___
*[`geometry/profiling/README.md` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1VBfA5aAREZtHsihR:-Nr1ga5J6TIIbYZj86PU:bncward) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f0d7b69874a6b9a15e97373ffe6e89236c8a92b/geometry/profiling/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I added some more text in the spirit you were looking for, I hope.  I can see the point of giving more actionable advice.

(In my mind, whatever disaster has hit this code already happened a year ago or more.  This PR is just surfacing the existing condition, so I'm trying to do as little work as possible.)
</blockquote></details>

Your solution looks good to me. It's clear what action to take if this ever becomes an issue and available to anyone who cares.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: for `//examples/...`, thanks.

> Reviewed 8 of 70 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-:-Nr1rm4u2a9In8nJ3fv-:bmh9sab)* status: 1 unresolved discussion

___
*[`examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc` line 257 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20963#-Nr1rAPh8j5g_hxUCz93:-Nr1rAPh8j5g_hxUCz94:bvj0zlk) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f798fc7ab0eddc5c3f3b1d90350ec1c875ae00d/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc#L257)):*
> ```cpp
>       "rotational slip of the spatula while maintaining the spatula in\n"
>       "the gripper's grasp. Launch meldis before running this\n"
>       "example. See the README.md file for more information.\n");
> ```

BTW, the README.md suggested using the MeshCat URL, so we can do animation playback.



_Suggestion:_
```cpp
      "the gripper's grasp. Use the MeshCat URL from the console log\n"
      "messages for visualization. See the README.md file for more\n"
      "information.\n");
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20963)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),DamrongGuoy

**Pull request merged**
