### PR TITLE
Added advice on how to install CMake 3.5 in Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2502)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added advice on how to install CMake 3\.5 in Ubuntu 14\.04\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-:-KJGf6Dg6nBrbMfbMQAi:-274331639)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-KJGfuSUOsZ-UUz79cS3:-KJGfuSUOsZ-UUz79cS4:159895977) ([raw file](https://github.com/robotlocomotion/drake/blob/b75cd5a05d712ba0ad4e55808b87bc3d190ac104/drake/doc/ubuntu.rst#L60)):*
> ```reStructuredText
>     tar zxvf cmake-3.5.2-Linux-x86_64.tar.gz
>     cd cmake-3.5.2-Linux-x86_64/bin
>     sudo ln -s `pwd`/ccmake /usr/local/bin/ccmake
> ```

I'm not quite sure what to do about the `sudo ln` stuff in terms of platform review.  I have a deep distrust of anything that touches the root filesystem that isn't `dpkg`, but I know that not everyone shares that view.

What about instead recommending an addition to one of the user's dotfiles, that puts `tools/cmake-3.5.2-Linux-x86_64/bin` on the `$PATH`, which is what the paragraph above already recommends?  That seems like fewer steps, because each program doesn't have to get symlinked individually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-KJGfuSUOsZ-UUz79cS3:-KJGhZqp8BBPU01YHu9c:-485248553) ([raw file](https://github.com/robotlocomotion/drake/blob/b75cd5a05d712ba0ad4e55808b87bc3d190ac104/drake/doc/ubuntu.rst#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I'm not quite sure what to do about the `sudo ln` stuff in terms of platform review.  I have a deep distrust of anything that touches the root filesystem that isn't `dpkg`, but I know that not everyone shares that view.
> 
> What about instead recommending an addition to one of the user's dotfiles, that puts `tools/cmake-3.5.2-Linux-x86_64/bin` on the `$PATH`, which is what the paragraph above already recommends?  That seems like fewer steps, because each program doesn't have to get symlinked individually.
</details>
OK I agree and will update this PR accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-KJGfuSUOsZ-UUz79cS3:-KJH49FGyOSrlju_OQ6t:-938671458) ([raw file](https://github.com/robotlocomotion/drake/blob/b75cd5a05d712ba0ad4e55808b87bc3d190ac104/drake/doc/ubuntu.rst#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK I agree and will update this PR accordingly.
</details>
Done. PTAL. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri for both levels of review.
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-:-KJH753G3Eo3o2TkeWg0:1417088721)*

**Comment by jwnimmer-tri** [comment]
/cc @jamiesnape In case anyone from kitware would like to review this also.  I think it's fine as-is, but please weight in if I've missed something.

If I don't hear anything, I'll plan to merge today.

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> /cc @jamiesnape In case anyone from kitware would like to review this also.  I think it's fine as-is, but please weight in if I've missed something.
> 
> 
> 
> If I don't hear anything, I'll plan to merge today.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2502#-:-KJHZSGyrW4c9gFCBIVC:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
