### PR TITLE
Add mac setup script

### PR DESCRIPTION
**Pull request by jamiesnape**
I will setup a CI job to test this each night when I have a little more time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6530)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-KoTIWreUYeEJkgTbkoQ:-KoTIWreUYeEJkgTbkoR:b-qwmquz) ([raw file](https://github.com/robotlocomotion/drake/blob/b74e0362626112db86e79c2cec3d4c9a16d5ce4c/setup/mac/install_prereqs.sh#L29)):*
> ```Shell
> brew install $(tr '\n' ' ' <<EOF
> 
> bazel
> ```

We need `jpeg` and `libpng` for `drake_visualizer`.
We need `patchutils` for `drake/tools/prstat`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-KoTIWreUYeEJkgTbkoQ:-KoTNOC-zusK73k_65ia:b-7obupc) ([raw file](https://github.com/robotlocomotion/drake/blob/b74e0362626112db86e79c2cec3d4c9a16d5ce4c/setup/mac/install_prereqs.sh#L29)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We need `jpeg` and `libpng` for `drake_visualizer`.
We need `patchutils` for `drake/tools/prstat`.
</blockquote></details>

`jpeg` and `libpng` are implicit dependencies only ever used through VTK. I will add `patchutils`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-KoTIWreUYeEJkgTbkoQ:-KoTNxOFMYaBJy4WLpFE:b-uyn4p4) ([raw file](https://github.com/robotlocomotion/drake/blob/b74e0362626112db86e79c2cec3d4c9a16d5ce4c/setup/mac/install_prereqs.sh#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`jpeg` and `libpng` are implicit dependencies only ever used through VTK. I will add `patchutils`. 
</blockquote></details>

We are missing a `zlib`, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-KoTIWreUYeEJkgTbkoQ:-KoTOmUj5ldPcP5zQJSn:b-gdm3vu) ([raw file](https://github.com/robotlocomotion/drake/blob/b74e0362626112db86e79c2cec3d4c9a16d5ce4c/setup/mac/install_prereqs.sh#L29)):*
> jpeg and libpng are implicit dependencies only ever used through VTK. 

Got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-:-KoTOyKYdBHlppN9AiSp:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-:-KoTbk2yoNwcPlMu-BTZ:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6530#-:-KoTtlA9wA86I0_Bu4rW:bnfp4nl)*

**Pull request merged**
