### PR TITLE
Refactor relational operator overloading between symbolic eigen array

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5521)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@sammy-tri , platform-review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5521#-:-KfNJ_DzsQSKV2HMu4aR:b-5evm6d)*

**Comment by hongkai-dai** [comment]
:lgtm: I would suggest we add a test on these functions. For example, in symbolic_formula_test, we compare two Eigen::Arrays, one being static sized, one being dynamic sized, and then check the type of the return value.
```C++
Eigen::Array<symbolic::Variable, 2, Eigen::Dynamic> m1(2, 2);
m1 << var_x_, var_y_, var_x_, var_y_;
Eigen::Array<symbolic::Variable, Eigen::Dynamic, 2> m2(2, 2);
m2 <<< var_x_, var_x_, var_y_, var_y_;
auto m1_lt_m2 = m1 < m2;
EXPECT_TRUE(std::is_same<decltype(m1_lt_m2), Eigen::Array<symbolic::Formula, 2, 2>>::value, true);
```

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5521#-:-KfNLu8dqtT6wx4WYwxE:bygn1d4)*

**Comment by soonho-tri** [comment]
Thank you! I actually found a bug in `EigenSizeMinPreferFixed`.
I've added more tests, PTAL. 

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5521#-:-KfNeys3E_CrFqvVt3_J:but90tk)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5521)*

**Comment by sammy-tri** [comment]
Nice!  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5521#-:-KfRb6V2wdw9e4mo6syL:b-ypbbbp)*

**Pull request merged**
