### PR TITLE
Add SpatialInertia::ThinRodWithMassAboutEnd()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18950 is work to helping resolve part of issue https://github.com/RobotLocomotion/drake/pull/18891.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-:-NPtSMRq4a_U4EbDoPeB:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:
+@jwnimmer-tri for platform review per rotation, please

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-:-NPyM-3J6tvJVh9bEF86:b-blmt2e)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri -@jwnimmer-tri (timed out, after 3pm PT).

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with minor comments.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-:-NQ1LGoZAS42XRJR-xuC:b-2mmrj3)* status: 4 unresolved discussions (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NQ1Kaos2jUoJ1yzafks:-NQ1Kaos2jUoJ1yzafkt:b-i8j9rg) (no related file):*
BTW, do we want python bindings for the new function?

___
___
*[`multibody/tree/spatial_inertia.h` line 237 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NQ1LCcz4WGqGVX4xyu3:-NQ1LCcz4WGqGVX4xyu4:bh0o5gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.h#L237)):*
> ```objc
>   /// expressed in B.
>   /// @retval M_BBp_B B's spatial inertia about Bp, expressed in B.
>   /// @note The position from Bp to Bcm is length / 2 *unit_vector.
> ```

nit missing space



_Suggestion:_
```objc
@note The position from Bp to Bcm is length / 2 * unit_vector.
```
___
*[`multibody/tree/spatial_inertia.h` line 243 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NPyk3T4B-jgyy5mYDrW:-NPyk3T4B-jgyy5mYDrX:b-cd62ma) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.h#L243)):*
> ```objc
>   /// the line that passes through Bp and is parallel to unit_vector.
>   /// @throws std::exception if mass or length is zero or negative.
>   /// @pre ‖unit_vector‖ ≈ 1.
> ```

nit, this precondition seems ambiguous to me because ≈ isn't well-defined. Obviously there's a good reason for this ambiguity since this is an existing pattern in this class. Could you explain?
___
*[`multibody/tree/spatial_inertia.cc` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NPyj3zK6LRRdPTbnihm:-NPyj3zK6LRRdPTbnihn:bwihkwc) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.cc#L178)):*
> ```cpp
>   // Ensure mass and length are positive.
>   if (mass <= 0 || length <= 0) {
>     std::string error_message = fmt::format(
> ```

nit, can we test this throw condition?

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 237 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NQ1LCcz4WGqGVX4xyu3:-NQ1fb302Z12S45egq23:b-1tmriw) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.h#L237)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit missing space
</blockquote></details>

Done (here and in another location).
___
*[`multibody/tree/spatial_inertia.h` line 243 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NPyk3T4B-jgyy5mYDrW:-NQ1fhG_90Av1Q6ju_Bt:bkqf2cz) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.h#L243)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this precondition seems ambiguous to me because ≈ isn't well-defined. Obviously there's a good reason for this ambiguity since this is an existing pattern in this class. Could you explain?
</blockquote></details>

OK -- changing this to  =, here and elsewhere.
___
*[`multibody/tree/spatial_inertia.cc` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NPyj3zK6LRRdPTbnihm:-NQ2DGNT80RqjU6YiiDZ:bkfxgom) ([raw file](https://github.com/RobotLocomotion/drake/blob/57ecd706327ff17519c88d6411a48ef85dc92dfb/multibody/tree/spatial_inertia.cc#L178)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, can we test this throw condition?
</blockquote></details>

per f2f.  Will create a better mechanism in subsequent PR.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-NQ1Kaos2jUoJ1yzafks:-NQ2HAXd3Bcme6E-qiax:bqs7okw) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, do we want python bindings for the new function?
</blockquote></details>

Yes -- will do later (all at once for all the new functions in SpatialInertia).

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18950#-:-NQ5zVaZAtv-SQbM3A3F:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

**Pull request merged**
