### PR TITLE
Prefix library names of vendored external shared libraries

### LINKED ISSUE #8143: homebrew bullet conflicts with Drake
Repro steps:
```
brew install bullet
bazel build //...
```

Message:
```
ImportError: dlopen(/private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/bazel-sandbox/3348516058086937316/execroot/drake/bazel-out/darwin-dbg/bin/bindings/pydrake/_isolated/symbolic_monomial_test.runfiles/drake/bindings/pydrake/_common_py.so, 2): Library not loaded: bazel-out/darwin-dbg/bin/external/bullet/libBulletCollision.so
  Referenced from: /private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/bazel-sandbox/3348516058086937316/execroot/drake/bazel-out/darwin-dbg/bin/bindings/pydrake/_isolated/symbolic_monomial_test.runfiles/drake/bindings/pydrake/_common_py.so
  Reason: image not found
```

Similar issue: https://github.com/RobotLocomotion/drake/issues/8137

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #8143. FYI @RussTedrake since you had issues with bullet.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8153)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
:lgtm: I'll do the local (mac) testing. Please feel free to assign another reviewer (who can test it on Ubuntu).

BTW, what's the meaning of the added digits in the end (such as `0` in `libdrake_ignition_rndf0.so`)?

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-:-L62JyXiXYVEK5z5hX0c:b-o0in4n)*

**Comment by jamiesnape** [comment]
Just thought I would match the target names since we are not tied to the upstream binary name.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-:-L62KWiMsMRxcza9XmO1:b-278w5b)*

**Comment by soonho-tri** [comment]
I see. Thank you.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-:-L62LHkVTYPzMfzHZUmY:b-fss59u)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for Ubuntu feature review.

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62ZB-GPfvCH58GTbQG:b-dnv12u) (no related file):*
I've tested it on my mac by installing `bullet` and `lcm` via homebrew and check `pydrake` targets (which caused problems before this PR). I think the homebrew `lcm` still causes a conflict with Drake. Here is the error that I got:
```
ERROR: /Users/soonhok/work/drake/examples/kuka_iiwa_arm/BUILD.bazel:21:1: C++ compilation of rule '//examples/kuka_iiwa_arm:iiwa_common' failed (Exit 1)
In file included from examples/kuka_iiwa_arm/iiwa_common.cc:1:
In file included from bazel-out/darwin-dbg/bin/examples/kuka_iiwa_arm/_virtual_includes/iiwa_common/drake/examples/kuka_iiwa_arm/iiwa_common.h:7:
In file included from bazel-out/darwin-dbg/genfiles/external/lcmtypes_robotlocomotion/lcmtypes/robotlocomotion/robot_plan_t.hpp:14:
In file included from bazel-out/darwin-dbg/genfiles/external/lcmtypes_bot2_core/lcmtypes/bot_core/robot_state_t.hpp:14:
bazel-out/darwin-dbg/genfiles/external/lcmtypes_bot2_core/lcmtypes/bot_core/position_3d_t.hpp:157:36: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'int64_t ()' (aka 'long long ()')
    const __lcm_hash_ptr cp = { p, position_3d_t::getHash };
                                   ^~~~~~~~~~~~~~~~~~~~~~
```
When I remove `lcm` via `brew rm lcm`, the problem goes away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62ZjGPEF7kXWzxB9Cs:b-bddunp) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I've tested it on my mac by installing `bullet` and `lcm` via homebrew and check `pydrake` targets (which caused problems before this PR). I think the homebrew `lcm` still causes a conflict with Drake. Here is the error that I got:
```
ERROR: /Users/soonhok/work/drake/examples/kuka_iiwa_arm/BUILD.bazel:21:1: C++ compilation of rule '//examples/kuka_iiwa_arm:iiwa_common' failed (Exit 1)
In file included from examples/kuka_iiwa_arm/iiwa_common.cc:1:
In file included from bazel-out/darwin-dbg/bin/examples/kuka_iiwa_arm/_virtual_includes/iiwa_common/drake/examples/kuka_iiwa_arm/iiwa_common.h:7:
In file included from bazel-out/darwin-dbg/genfiles/external/lcmtypes_robotlocomotion/lcmtypes/robotlocomotion/robot_plan_t.hpp:14:
In file included from bazel-out/darwin-dbg/genfiles/external/lcmtypes_bot2_core/lcmtypes/bot_core/robot_state_t.hpp:14:
bazel-out/darwin-dbg/genfiles/external/lcmtypes_bot2_core/lcmtypes/bot_core/position_3d_t.hpp:157:36: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'int64_t ()' (aka 'long long ()')
    const __lcm_hash_ptr cp = { p, position_3d_t::getHash };
                                   ^~~~~~~~~~~~~~~~~~~~~~
```
When I remove `lcm` via `brew rm lcm`, the problem goes away.
</blockquote></details>

Hopefully #8151 fixes that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62ZpFW4Qr_g7fYwUbm:bx1rslr) (no related file):*
> Hopefully #8151 fixes that.

FYI, when `lcm` generates a header, it include system headers such as `#include <lcm/lcm_coretypes.h>`. As a result, it still causes a problem:

```
ERROR: /Users/soonhok/work/drake/multibody/rigid_body_plant/BUILD.bazel:90:1: C++ compilation of rule '//multibody/rigid_body_plant:contact_results_to_lcm' failed (Exit 1)
In file included from multibody/rigid_body_plant/contact_results_to_lcm.cc:1:
In file included from bazel-out/darwin-dbg/bin/multibody/rigid_body_plant/_virtual_includes/contact_results_to_lcm/drake/multibody/rigid_body_plant/contact_results_to_lcm.h:6:
bazel-out/darwin-dbg/bin/lcmtypes/_virtual_includes/contact_results_for_viz/drake/lcmt_contact_results_for_viz.hpp:177:36: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'int64_t ()' (aka 'long long ()')
    const __lcm_hash_ptr cp = { p, lcmt_contact_results_for_viz::getHash };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62a0BVW-D2l-reFv-f:b-87bpp0) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Hopefully #8151 fixes that.

FYI, when `lcm` generates a header, it include system headers such as `#include <lcm/lcm_coretypes.h>`. As a result, it still causes a problem:

```
ERROR: /Users/soonhok/work/drake/multibody/rigid_body_plant/BUILD.bazel:90:1: C++ compilation of rule '//multibody/rigid_body_plant:contact_results_to_lcm' failed (Exit 1)
In file included from multibody/rigid_body_plant/contact_results_to_lcm.cc:1:
In file included from bazel-out/darwin-dbg/bin/multibody/rigid_body_plant/_virtual_includes/contact_results_to_lcm/drake/multibody/rigid_body_plant/contact_results_to_lcm.h:6:
bazel-out/darwin-dbg/bin/lcmtypes/_virtual_includes/contact_results_for_viz/drake/lcmt_contact_results_for_viz.hpp:177:36: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'int64_t ()' (aka 'long long ()')
    const __lcm_hash_ptr cp = { p, lcmt_contact_results_for_viz::getHash };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</blockquote></details>

I agree that this PR is a part of the solution and shouldn't be blocked by the above issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62bEXD_tSzEyicHjph:b3h9j8x) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I agree that this PR is a part of the solution and shouldn't be blocked by the above issue.
</blockquote></details>

Oh dear, I forgot about that. This gets more and more fun.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62c87dLXYZqd6uLGqs:bsxhfmb) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Oh dear, I forgot about that. This gets more and more fun.
</blockquote></details>

Thanks for all the works. Please let me know if you want me to open another issue for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62cHT2968b0ZagJwIs:b-7m32p5) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Thanks for all the works. Please let me know if you want me to open another issue for this.
</blockquote></details>

Yes, please do. I think it only documented here and on Slack otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L62ZB-GPfvCH58GTbQF:-L62dq39XH9N-qteCsl0:b-hfmx2c) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, please do. I think it only documented here and on Slack otherwise.
</blockquote></details>

=> https://github.com/RobotLocomotion/drake/issues/8155

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-L6CZRFbZTwsEiu1TyS_:-L6CZRFbZTwsEiu1TySa:b9x2hnk) (no related file):*
FYI At some point, all choices like this need to turn into policy or guidelines in https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md documentation.  Given that there's already a big TODO hole there where this note would live, its not a defect to omit it here, but consider if you want to write up something there anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8153#-:-L6CZdjuRF0CQFRoNtiA:bnfp4nl)*

**Comment by jamiesnape** [comment]
@jwnimmer-tri Does this need an additional platform review or are we good with the two reviews so far?

**Comment by jwnimmer-tri** [comment]
I think the two reviewers so far are sufficient.

**Pull request merged**
