### PR TITLE
No More Sed

### LINKED ISSUE #1445: Installation error: Can't find lcm files
First time installation, using the instructions for the "from source" procedure for a Win7 64-bit system running MATLAB  r2051b 64-bit and MSVC 2015. Have installed prerequisites and added paths and environment variables as necessary.  Getting errors when I run the initial make:

    "C:\work\drake\drake-distro\pod-build\ALL_BUILD.vcxproj" (default target) (1) ->
    "C:\work\drake\drake-distro\pod-build\drake.vcxproj" (default target) (10) ->
    (CustomBuild target) ->
      CUSTOMBUILD : ----- warning : bot2-lcmgl not found [C:\work\drake\drake-distro\pod-build\drake.vcxproj]

    "C:\work\drake\drake-distro\pod-build\ALL_BUILD.vcxproj" (default target) (1) ->
    "C:\work\drake\drake-distro\pod-build\drake.vcxproj" (default target) (10) ->
    (CustomBuild target) ->
      c1xx : fatal error C1083: Cannot open source file: 'C:\work\drake\drake-distro\drake\pod-build\lcmgen\lcmtypes\lcmt_body_motion_data.c': No such file or directory [C:\work\drake\drake-distro\drake\pod-build\drake_lcmtypes.vcxproj] [C:\work\drake\drake-distro\pod-build\drake.vcxproj]
      c1xx : fatal error C1083: Cannot open source file: 'C:\work\drake\drake-distro\drake\pod-build\lcmgen\lcmtypes\lcmt_body_wrench_data.c': No such file or directory [C:\work\drake\drake-distro\drake\pod-build\drake_lcmtypes.vcxproj] [C:\work\drake\drake-distro\pod-build\drake.vcxproj]

 full error log here:

https://drive.google.com/file/d/0B7-KdrI3pwWyN1ZWT2sxSmZfOUk/view?usp=sharing 

Thanks,
Paul

### PR DESCRIPTION
**Pull request by psiorx**
Updates the cmake submodule to include the following change:

Replaced sed call in lcmtypes.cmake with a more robust platform agnostic solution.

Resolves #1445

### CODE REVIEW

**Comment by RussTedrake** [comment]
Thanks John.  Looks like a reliable compile error.


On November 23, 2015 at 11:25:42 AM, John Carter (notifications@github.com) wrote:

Updates the cmake submodule to include the following change:

Replaced sed call in lcmtypes.cmake with a more robust platform agnostic solution.

Resolves #1445

You can view, comment on, or merge this pull request online at:

  https://github.com/RobotLocomotion/drake/pull/1463

Commit Summary

replaced lcmtypes sed call with a platform agnostic solution
File Changes

M CMakeLists.txt (2)
Patch Links:

https://github.com/RobotLocomotion/drake/pull/1463.patch
https://github.com/RobotLocomotion/drake/pull/1463.diff

**Comment by psiorx** [comment]
Looks like the failure is related to https://github.com/RobotLocomotion/cmake/commit/3d5f18fcf0cc36c830ac6f817449cd786d725a4b

Is there a reason why this was merged into the cmake pod but not included in drake?

**Comment by psiorx** [comment]
> Thanks John.  Looks like a reliable compile error.

Sorry for the compiler errors.  Didn't realize drake was behind the cmake master and ended up pulling in more changes than expected.

Spoke with @tkoolen and we both think these are good changes to bring in.

**Comment by RussTedrake** [comment]
totally agree.  we should be compiling against our installed libraries.  Thanks.

**Pull request merged**
