### PR TITLE
macOS-focused tweaks to pkg_config_repository

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8182)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and +@jwnimmer-tri for feature/platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm: nice.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pkg_config.bzl, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-L6IMdvYjuRuA24q1USu:-L6IMdvYjuRuA24q1USv:bvtr2mn) ([raw file](https://github.com/robotlocomotion/drake/blob/edcf11312f1d9d28fd3789732272b20c13fd9c78/tools/workspace/pkg_config.bzl#L88)):*
> ```Python
>                 suffix = ".so"
>             else:
>                 break
> ```

FYI Better to `fail()` here?  This should never be reached, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-:-L6IM_X3FqhxW7vV3qWX:b-7yytum)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pkg_config.bzl, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-L6ITedsVVSKVtRyAQfo:-L6ITedsVVSKVtRyAQfp:b9oy9n0) ([raw file](https://github.com/robotlocomotion/drake/blob/edcf11312f1d9d28fd3789732272b20c13fd9c78/tools/workspace/pkg_config.bzl#L157)):*
> ```Python
>             print("pkg-config of {} returned an include path that " +
>                   "contains {} that may contain unrelated headers".format(
>                       repository_ctx.attr.modname, item))
> ```

I'm afraid that `s1 + s2.format(...)` is parsed as `s1 + (s2.format(...))`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182)*

**Comment by soonho-tri** [comment]
:lgtm: other than one minor comment.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-:-L6ITta1yoFIpYKIZAVk:ban87zo)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/pkg_config.bzl, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-L6IMdvYjuRuA24q1USu:-L6IX9FfDtjVjWXqMMSJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edcf11312f1d9d28fd3789732272b20c13fd9c78/tools/workspace/pkg_config.bzl#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Better to `fail()` here?  This should never be reached, I think.
</blockquote></details>

Done.

---

*[tools/workspace/pkg_config.bzl, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8182#-L6ITedsVVSKVtRyAQfo:-L6IX9uXFQM2RL5agEQ1:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/edcf11312f1d9d28fd3789732272b20c13fd9c78/tools/workspace/pkg_config.bzl#L157)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm afraid that `s1 + s2.format(...)` is parsed as `s1 + (s2.format(...))`.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8182)*

**Pull request merged**
