### PR TITLE
[perception] Add PointCloud::Crop and Concatenate(vector<PointCloud>)

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards https://github.com/RussTedrake/manipulation/issues/130.

+@EricCousineau-TRI for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Nice! First pass done, PTAL!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829#-:-NBEFd8B7FLGVlQlsLLk:b-65rxtu)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`perception/point_cloud.h` line 307 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEEb_T5CbdqhLHXZ_6:-NBEEb_T5CbdqhLHXZ_7:b-h8dawr) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/point_cloud.h#L307)):*
> ```objc
> 
>   /// Returns a new point cloud containing only the points in `this` with xyz
>   /// values within the axis-aligned bounding box defined by `lower_xyz` and
> ```

nit Not sure if I understand why we should qualify this as `axis-aligned` when there is no rotation component specified.

Consider either (a) supporting rotation (with identity default), or (b) removing the qualifier and/or mentioning to users how to achieve this?
e.g.
```
@note If you need axis alignment, please rotate your point cloud.
```
___
*[`perception/point_cloud.cc` line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEEzee6ApPstO_CGEW:-NBEEzef0c9jqm9buuPz:buuw7z3) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/point_cloud.cc#L324)):*
> ```cpp
> PointCloud PointCloud::Crop(const Eigen::Ref<const Vector3<T>>& lower_xyz,
>                             const Eigen::Ref<const Vector3<T>>& upper_xyz) {
>   if (!has_xyzs()) {
> ```

nit Inputs not checked, could have negative volume.

Should this assert that `(lower_xyz.array() <= upper_xyz.array()).all()`?
___
*[`perception/test/point_cloud_test.cc` line 297 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEFIMfEUAU1zX0cHUv:-NBEFIMfEUAU1zX0cHUw:b-4zuer9) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/test/point_cloud_test.cc#L297)):*
> ```cpp
>   clouds.push_back(PointCloud(1, fields, true));
> 
>   clouds[0].mutable_xyzs() << 1, 2, 3, 4, 5, 6;
> ```

nit 2d values (xyz, rgb, normal) are a bit hard to interpret. Per examples above, consider using something like:
```
xyzs.transpose() <<
   x1, y1, z1,
   x2, y2, z2,
   ...
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[`perception/point_cloud.h` line 307 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEEb_T5CbdqhLHXZ_6:-NBKW8jQClogtVL-rVZI:b-8rzvux) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/point_cloud.h#L307)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not sure if I understand why we should qualify this as `axis-aligned` when there is no rotation component specified.

Consider either (a) supporting rotation (with identity default), or (b) removing the qualifier and/or mentioning to users how to achieve this?
e.g.
```
@note If you need axis alignment, please rotate your point cloud.
```
</blockquote></details>

Hrm.  I chose the term "axis-aligned" specifically *because* there is no rotation supported.  there is certainly a coordinate system implied by the xyzs in the cloud, and axis-aligned is exactly the box defined here.  (it also matches the language from open3d which defines axisalignedboundingbox and (separately) orientedboundingbox

http://www.open3d.org/docs/latest/python_api/open3d.geometry.html
___
*[`perception/point_cloud.cc` line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEEzee6ApPstO_CGEW:-NBKXU0_D1yx6-X-FOOe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/point_cloud.cc#L324)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Inputs not checked, could have negative volume.

Should this assert that `(lower_xyz.array() <= upper_xyz.array()).all()`?
</blockquote></details>

Done.
___
*[`perception/test/point_cloud_test.cc` line 297 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEFIMfEUAU1zX0cHUv:-NBKXga3-x0QCSQrZMwi:bws6d8d) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/test/point_cloud_test.cc#L297)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit 2d values (xyz, rgb, normal) are a bit hard to interpret. Per examples above, consider using something like:
```
xyzs.transpose() <<
   x1, y1, z1,
   x2, y2, z2,
   ...
```

</blockquote></details>

But the point is that they are arbitrary.  No interpretation is necessary (or even useful); the correctness of the tests does not depend on them in any way.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:
+@xuchenhan-tri for platform review, please!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829#-:-NBKdWGE0QSt-OeWq-mB:b-csuxt1)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`perception/point_cloud.h` line 307 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEEb_T5CbdqhLHXZ_6:-NBKdBVq4_FvMyGXZTs3:b-kl8o56) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/point_cloud.h#L307)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Hrm.  I chose the term "axis-aligned" specifically *because* there is no rotation supported.  there is certainly a coordinate system implied by the xyzs in the cloud, and axis-aligned is exactly the box defined here.  (it also matches the language from open3d which defines axisalignedboundingbox and (separately) orientedboundingbox

http://www.open3d.org/docs/latest/python_api/open3d.geometry.html
</blockquote></details>

OK Ah, thank you for pointing that out, and oops!
___
*[`perception/test/point_cloud_test.cc` line 297 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBEFIMfEUAU1zX0cHUv:-NBKdKql8TBsFAv_-S9n:bl00cdx) ([raw file](https://github.com/robotlocomotion/drake/blob/eaef5ef54963b71a404902830b0050aeb712fdf4/perception/test/point_cloud_test.cc#L297)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

But the point is that they are arbitrary.  No interpretation is necessary (or even useful); the correctness of the tests does not depend on them in any way.
</blockquote></details>

OK SGTM!

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829#-:-NBNkUTk9bCIZvxZ1u3l:bzus18)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`perception/point_cloud.h` line 338 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBNjMlS6JCJVN2J0I1s:-NBNjMlS6JCJVN2J0I1t:b-o0w4jm) ([raw file](https://github.com/robotlocomotion/drake/blob/de4bf5b2390a27cc43fdb5d0dc6588d3cef77cb4/perception/point_cloud.h#L338)):*
> ```objc
> /// Returns a new point cloud that includes all of the points from the point
> /// clouds in `clouds`. All of the `clouds` must have the same fields.
> /// @throws std::exception if the clouds have different fields defined.
> ```

nit consider also clarifying tthat `clouds` must be non-empty.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[`perception/point_cloud.h` line 338 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17829#-NBNjMlS6JCJVN2J0I1s:-NBO0zv3-nvzs0XMK-S6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de4bf5b2390a27cc43fdb5d0dc6588d3cef77cb4/perception/point_cloud.h#L338)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit consider also clarifying tthat `clouds` must be non-empty.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17829)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
