### PR TITLE
Check IsStabilizable and IsDetectable in ContinuousAlgebraicRiccatiEquation

### PR DESCRIPTION
**Pull request by hongkai-dai**
As discussed in #19191

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@cohnt for feature review please, thansk!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NU4IZs3AbYV2L6z23fS:bhsr3x7)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NU8FVieB_wRnZszR21o:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by cohnt** [comment]
Worth noting that this seems to be catching some errors in ZmpPlanner? Is that class inadvertently creating poorly-conditioned systems?

**Review by hongkai-dai — COMMENTED** [review]
@RussTedrake I suspect there is a problem in the zmp_planner_test.cc, could you confirm it?

The default `R` ZMPPlanner::Plan is just zero https://github.com/RobotLocomotion/drake/blob/9c687ba42fc55738f4907dea50d288f9028bc144/systems/controllers/zmp_planner.h#L95-L98
This is surprising to me as usually we want the R matrix to be positive definite.

With `R` being zero, the Q1 matrix inside `LinearQuadraticRegulator` becomes zero. This is because we have
Q₁=Q−NR₁⁻¹Nᵀ
And in `zmp_planner.cc` we set 
```
Q = CᵀQ_yC
R₁ = R + DᵀQ_yD
N = CᵀQ_yD
```
Now because D = z/g * I, and `R = 0`. we have 
```
Q₁=Q−NR₁⁻¹Nᵀ
     = CᵀQ_yC - CᵀQ_yD * (R + DᵀQ_yD)⁻¹*(CᵀQ_yD)ᵀ
     = 0
```

With Q1 being 0, the LQR problem is definitely not detectable.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NUTM6lZ63yxf0gE1l_z:beirk)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
Sorry for the delay.  I agree with you R should definitely not default to zero!  I would default it to the identity as well.  (BTW -- Drake's deprecation policy says it's ok for us to change the default values w/o deprecation).

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NVd9qu21RuI25sK9VPH:b-wrj7nc)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Thanks Russ, I changed the default R value.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NVhiXLd2v6BnDf6qtVI:b-21mnuj)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NVkWIqP1arTjizTx_rl:b-69uc1d)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NW24Xs6CLAvY5Ru3lJT:bnfp4nl)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

**Comment by RussTedrake** [comment]
(please consider my review the feature review)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-:-NW2jlfC1sGR6pYKhXUR:b-vtj4w1)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`math/continuous_algebraic_riccati_equation.cc` line 35 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19300#-NW2jORR8-q6i5SnIu2T:-NW2jORR8-q6i5SnIu2U:b98b1qs) ([raw file](https://github.com/RobotLocomotion/drake/blob/8103dc44fce2b18c24a3f2eea982d0df0c433235/math/continuous_algebraic_riccati_equation.cc#L35)):*
> ```cpp
>   // eigenvalues of H should have strictly negative real parts, and the other
>   // half have strictly positive real parts.
>   if (H.determinant() == 0) {
> ```

BTW Should this have a tolerance?

**Pull request merged**
