### PR TITLE
Run clang-format-includes --all

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5977)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977#-:-KiuVVBg6oO8x8nday8_:b-v3eqt6)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5977#-KizUk1gupPKIgRAEoBD:-KizUk1gupPKIgRAEoBE:b-ht35au) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b4f480dc0cf416ce21f22f9997f08fe0e65bcb/drake/examples/Valkyrie/valkyrie_simulation.cc#L7)):*
> ```cpp
> /// for more details.
> 
> #include "drake/examples/Valkyrie/valkyrie_simulator.h"
> ```

@jwnimmer-tri , what do you think about this case? `_simulator.h` is not matched with `_simulation.cc` but it's quite close.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5977#-KizUk1gupPKIgRAEoBD:-KizhsRXxFsu8AkD9FM8:bm9tz9l) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b4f480dc0cf416ce21f22f9997f08fe0e65bcb/drake/examples/Valkyrie/valkyrie_simulation.cc#L7)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@jwnimmer-tri , what do you think about this case? `_simulator.h` is not matched with `_simulation.cc` but it's quite close.
</blockquote></details>

I think if people want to use the "put the related header as the first include, to make sure it parses alone" best practice, then they can very well name files in a proper an obvious way to achieve that (see all of the `systems/framework` one-line `cc` files for this purpose).  When I looked at this file, it seemed pretty clear to me that it was a _use_ of the header, not a related-file implementation nor a unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5977#-KizUk1gupPKIgRAEoBD:-KizlNlfC8Trfrmlnzwr:b8jsit7) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b4f480dc0cf416ce21f22f9997f08fe0e65bcb/drake/examples/Valkyrie/valkyrie_simulation.cc#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think if people want to use the "put the related header as the first include, to make sure it parses alone" best practice, then they can very well name files in a proper an obvious way to achieve that (see all of the `systems/framework` one-line `cc` files for this purpose).  When I looked at this file, it seemed pretty clear to me that it was a _use_ of the header, not a related-file implementation nor a unit test.
</blockquote></details>

I see. Thank you for the explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5977#-:-KizlWmVKK_cWJxcwLek:bnfp4nl)*

**Pull request merged**
