### PR TITLE
Enable rgbd_* tests

### LINKED ISSUE #5227: RgbdCamera Unit Test Fails in CI
In the PR for [RgbdCamera](https://github.com/RobotLocomotion/drake/pull/5201), the unit test failed in CI. There is no failure in my local machine.

It seems this is due to the lack of `DISPLAY` environment variable. The actual error message is:
```
190: ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 539
190: vtkXOpenGLRenderWindow (0x1b820a0): bad X server connection. DISPLAY=ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 343
190: vtkXOpenGLRenderWindow (0x1b820a0): bad X server connection. DISPLAY=
250/263 Test #186: rotary_encoders_test ...............................   Passed   12.33 sec
251/263 Test #219: acrobot_run_passive ................................   Passed   10.31 sec
252/263 Test #190: rgbd_camera_test ...................................***Exception: SegFault 11.60 sec
Running main() from gtest_main.cc
[==========] Running 5 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from RgbdCameraTest
[ RUN      ] RgbdCameraTest.InstantiateTest
ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 539
vtkXOpenGLRenderWindow (0x1b820a0): bad X server connection. DISPLAY=ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 343
vtkXOpenGLRenderWindow (0x1b820a0): bad X server connection. DISPLAY=
```

`vtkXOpenGLRenderWindow.cxx` is calling `XOpenDisplay` [here](https://github.com/Kitware/VTK/blob/v5.10.0/Rendering/vtkXOpenGLRenderWindow.cxx#L338) and this needs `DISPLAY`.

In the #5210, @patmarion is suggesting to replace `xvfb-run` with `Xvfb` and this might solve this issue too, if the root cause is the same.

### LINKED ISSUE #7517: rgbd_renderer_test fails on macOS
Tolerances probably just need tweaking slightly.

```
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from RgbdRendererTest
[ RUN      ] RgbdRendererTest.InstantiationTest
[       OK ] RgbdRendererTest.InstantiationTest (482 ms)
[ RUN      ] RgbdRendererTest.NoBodyTest
[       OK ] RgbdRendererTest.NoBodyTest (119 ms)
[ RUN      ] RgbdRendererTest.TerrainTest
[       OK ] RgbdRendererTest.TerrainTest (6633 ms)
[ RUN      ] RgbdRendererTest.HorizonTest
[       OK ] RgbdRendererTest.HorizonTest (5359 ms)
[ RUN      ] RgbdRendererTest.BoxTest
[       OK ] RgbdRendererTest.BoxTest (5651 ms)
[ RUN      ] RgbdRendererTest.SphereTest
drake/systems/sensors/test/rgbd_renderer_test.cc:279: Failure
The difference between depth_.at(x, y)[0] and 2.f is 0.00010919570922851562, which exceeds kDepthTolerance, where
depth_.at(x, y)[0] evaluates to 2.0001091957092285,
2.f evaluates to 2, and
kDepthTolerance evaluates to 0.0001.
[  FAILED  ] RgbdRendererTest.SphereTest (4883 ms)
[ RUN      ] RgbdRendererTest.CylinderTest
[       OK ] RgbdRendererTest.CylinderTest (5000 ms)
[ RUN      ] RgbdRendererTest.MeshTest
[       OK ] RgbdRendererTest.MeshTest (5999 ms)
[----------] 8 tests from RgbdRendererTest (34126 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (34126 ms total)
[  PASSED  ] 7 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RgbdRendererTest.SphereTest

 1 FAILED TEST
```

Blocks #7516.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #5227 and closes #7517.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7516)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
mac-sierra-clang-bazel-experimental:
```
drake/systems/sensors/test/rgbd_renderer_test.cc:279: Failure
The difference between depth_.at(x, y)[0] and 2.f is 0.00010919570922851562, which exceeds kDepthTolerance, where
depth_.at(x, y)[0] evaluates to 2.0001091957092285,
2.f evaluates to 2, and
```
FYI @kunimatsu-tri @EricCousineau-TRI.

**Comment by jamiesnape** [comment]
Not much to go by, but apparently there are LeakSanitizer issues with both tests too:
```
=================================================================
==33204==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x5619f4993b4e  (/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-memcheck-lsan/_bazel_ubuntu/14b081bf825c73cab1654e615f0285b1/execroot/drake/bazel-out/clang-4.0-linux-dbg/bin/drake/systems/sensors/rgbd_camera_test+0x1673b4e)
    #1 0x7f5c8c1f9c1b  (<unknown module>)

Indirect leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x5619f4993b4e  (/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-memcheck-lsan/_bazel_ubuntu/14b081bf825c73cab1654e615f0285b1/execroot/drake/bazel-out/clang-4.0-linux-dbg/bin/drake/systems/sensors/rgbd_camera_test+0x1673b4e)
    #1 0x7f5c8c1f9c32  (<unknown module>)

SUMMARY: LeakSanitizer: 224 byte(s) leaked in 4 allocation(s).
```

```
=================================================================
==33172==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 336 byte(s) in 6 object(s) allocated from:
    #0 0x55cd5894308e  (/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-memcheck-lsan/_bazel_ubuntu/14b081bf825c73cab1654e615f0285b1/execroot/drake/bazel-out/clang-4.0-linux-dbg/bin/drake/systems/sensors/rgbd_renderer_test+0x14208e)
    #1 0x7f821d2d0c1b  (<unknown module>)

Indirect leak of 336 byte(s) in 6 object(s) allocated from:
    #0 0x55cd5894308e  (/home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-memcheck-lsan/_bazel_ubuntu/14b081bf825c73cab1654e615f0285b1/execroot/drake/bazel-out/clang-4.0-linux-dbg/bin/drake/systems/sensors/rgbd_renderer_test+0x14208e)
    #1 0x7f821d2d0c32  (<unknown module>)

SUMMARY: LeakSanitizer: 672 byte(s) leaked in 12 allocation(s).
```

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Comment by kunimatsu-tri** [comment]
Thank you @jamiesnape for this.

**Comment by jamiesnape** [comment]
TSan failure is unrelated to this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-asan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by jamiesnape** [comment]
+@kunimatsu-tri for feature review.

**Comment by kunimatsu-tri** [comment]
:lgtm:

Sorry for delayed reply.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7516#-:-L-kATYWrj3zzD9sOZop:b4as9u5)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7516#-:-L-lwbK2AIrethynmFjJ:bnfp4nl)*

**Pull request merged**
