### PR TITLE
dev/qp kuka1

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
0. first part of #4992. Contains essential changes to the inverse dynamics code so that it will for a fixed base arm. 
1. added a simple test 
2. some minor utility code to params and alias groups for better usability. 
3. added build file for examples/kuka_iiwa_arm/controlled_kuka

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5173)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@david-german-tri for platform review. 
+@sammy-tri for feature review. although sammy have seen most of the changes. my apologies for duplicated prs. 

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-:-KcyxJ6y6iFMXkJTStpG:b7xvcb0)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

Thanks for breaking this up!  This chunk was very readable.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1ClSylcX9ipwlppyU:-Kd1ClSylcX9ipwlppyV:b6zy1xe) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L12)):*
> ```Python
> )
> 
> package(default_visibility = ["//visibility:public"])
> ```

BTW is this really what you want?  It means any target anywhere in drake can depend on targets in this package.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DzsTEVViMXbGPOE7:-Kd1DzsTEVViMXbGPOE8:broicep) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc#L27)):*
> ```cpp
> 
>   // These are humanoid specific special group names, and they do not exsit
>   // for manupulators such as the iiwa arm.
> ```

BTW Is the directory name `QPInverseDynamicsForHumanoids` now out of date?  If so, consider updating it (and also making it style-guide compliant) in a follow-up PR.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DFPPP9q7bez1ypbw:-Kd1DFPPP9q7bez1ypbx:bj61tl2) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc#L120)):*
> ```cpp
> 
>       // H2 = transformation from sensor frame to a frame that is aligned with
>       // the
> ```

BTW weird line break

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1EiGDIFJmE_sinuRo:-Kd1ETzdLHsuI8f89Qkx:bhn59av) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc#L64)):*
> ```cpp
>     return false;
> 
>   // TODO(siyuan.feng): find a better to do this, right now all the other math
> ```

BTW +1 for this TODO.

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DhH31xcvBWjVvtqq:-Kd1DhH31xcvBWjVvtqr:b-qkcx4y) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc#L196)):*
> ```cpp
> 
>   // Dynamics
>   if (num_dynamics_equations_) {
> ```

`num_dynamics_equations_ > 0` for clarity, please

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller_common.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1FTafVDCDKcqiJSCN:-Kd1FTafVDCDKcqiJSCO:b-pw2qy2) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/qp_controller_common.h#L41)):*
> ```objc
>    * ConstraintType::Skip.
>    */
>   ConstrainedValues() {}
> ```

This comment doesn't go with this constructor (but documenting the default constructor would be a good idea)

---

*[drake/examples/QPInverseDynamicsForHumanoids/config/valkyrie.alias_groups, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1FjjdF-UuHSE6dX9Q:-Kd1FjjdF-UuHSE6dX9R:b-iyyzfe) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/config/valkyrie.alias_groups#L60)):*
> ```
> }
> 
> joint_group {
> ```

Is this change related?  I can't square it with the PR description.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.cc, line 458 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1PREPKgTp4t9y1fUV:-Kd1PREQnubPru_yENho:b-9k231x) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.cc#L458)):*
> ```cpp
> 
>   // Copies basis regularization weight.
>   qp_input.mutable_w_basis_reg() = get_basis_regularization_weight();
> ```

BTW (it's preexisting), the lhs name here is inscrutable.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1PZhhVAyoiaYgu2qU:-Kd1PZhhVAyoiaYgu2qV:b-x58o38) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h#L303)):*
> ```objc
>    * For each body of each group, a DesiredBodyMotion will be populated in the
>    * returned QpInput.
>    * @return QpInput.
> ```

BTW I think you could safely delete this line.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h, line 305 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1QOoSQ9CrJ4l0MdIk:-Kd1QOoSQ9CrJ4l0MdIl:b-3fj9x7) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h#L305)):*
> ```objc
>    * @return QpInput.
>    */
>   QpInput MakeQpInput(
> ```

This new code should have some kind of unit test.  Doesn't need to be much.

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1Pr1HlfQMqIzoZDsk:-Kd1Pr1HlfQMqIzoZDsl:b-adxghh) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc#L54)):*
> ```cpp
>   VectorX<double> v = VectorX<double>::Zero(robot->get_num_velocities());
> 
>   // Sets up a control policy to track q and v with .
> ```

Is this sentence missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-:-Kd1C_sXvXLiTonT54Yp:bv2p6ve)*

**Comment by sammy-tri** [comment]
:lgtm: pending existing issues + curation/squash

This was much more readable diff.  Thanks!

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-:-Kd1S6QCScXsErv_TBQR:bregte1)*

**Comment by siyuanfeng-tri** [comment]
Review status: 13 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1ClSylcX9ipwlppyU:-Kd1VgvMgvZJw59QkTPu:bisq5w0) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW is this really what you want?  It means any target anywhere in drake can depend on targets in this package.
</blockquote></details>

hmm. i copy pasted it from somewhere. probably not. 
can the sub directory see what's going on in parents' BUILD? 

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DzsTEVViMXbGPOE7:-Kd1VsDDmzWLFZqu9tSz:b8nyap1) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW Is the directory name `QPInverseDynamicsForHumanoids` now out of date?  If so, consider updating it (and also making it style-guide compliant) in a follow-up PR.
</blockquote></details>

yeah. i should probably renamed it to something more general. will do after this batch. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DFPPP9q7bez1ypbw:-Kd1W5wujZjrz_IwzqVx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.cc#L120)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW weird line break
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1DhH31xcvBWjVvtqq:-Kd1WAm9ZByVp8GNyJPc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc#L196)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

`num_dynamics_equations_ > 0` for clarity, please
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller_common.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1FTafVDCDKcqiJSCN:-Kd1f5d2MjeOhRO3MkpL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/qp_controller_common.h#L41)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This comment doesn't go with this constructor (but documenting the default constructor would be a good idea)
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/config/valkyrie.alias_groups, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1FjjdF-UuHSE6dX9Q:-Kd1XAkot_oQnDvYI1c_:b6nwyts) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/config/valkyrie.alias_groups#L60)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Is this change related?  I can't square it with the PR description.
</blockquote></details>

It is a minor detail for the val_balancing_test, where I perturbed the initial condition. I used to use a joint name specific to valkyrie, this would work for atlas as long as i have the right alias.  

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.cc, line 458 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1PREPKgTp4t9y1fUV:-Kd1XURNvDYI7hAjE6nm:b10mw9z) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.cc#L458)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW (it's preexisting), the lhs name here is inscrutable.
</blockquote></details>

yeah... i will leave it for another maybe. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1PZhhVAyoiaYgu2qU:-Kd1XnTO59f-6peA2b5N:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h#L303)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW I think you could safely delete this line.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h, line 305 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1QOoSQ9CrJ4l0MdIk:-Kd1eBcSj896XCuXq1yx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/param_parser.h#L305)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This new code should have some kind of unit test.  Doesn't need to be much.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1Pr1HlfQMqIzoZDsk:-Kd1XxomZrXmvN3kkFG2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/QPInverseDynamicsForHumanoids/test/iiwa_inverse_dynamics_test.cc#L54)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Is this sentence missing something?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1ClSylcX9ipwlppyU:-Kd1fpEbfxnSy6W7INrA:b-y75sol) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L12)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

hmm. i copy pasted it from somewhere. probably not. 
can the sub directory see what's going on in parents' BUILD? 
</blockquote></details>

i want most of it to be subpackages, but i want the models to be visible. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1ClSylcX9ipwlppyU:-Kd1qJPQjIpMZpyxY3og:bzf7w9t) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L12)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i want most of it to be subpackages, but i want the models to be visible. 
</blockquote></details>

Then set the default to be `:__subpackages__`, and add `visibility = ["//visibility:public"]` to the specific targets that are public.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/param_parser_test.cc, line 236 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1qopQQI8gqYALovzO:-Kd1qopRLlxTv07myPUT:b-piqh0r) ([raw file](https://github.com/robotlocomotion/drake/blob/f8017ef871e60bd3a4e81ab3d594b15502358a75/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/param_parser_test.cc#L236)):*
> ```cpp
> }
> 
> void TestDofMotionsParamsHelper(
> ```

Some kind of comment, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-:-Kd1qvNKxy_M9MQZu8h2:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173)*

**Comment by siyuanfeng-tri** [comment]
Review status: 17 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1ClSylcX9ipwlppyU:-Kd1vb2zEY47hFJRA27D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbde60273806b7ea0fda3612aa180aa32e386dc5/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Then set the default to be `:__subpackages__`, and add `visibility = ["//visibility:public"]` to the specific targets that are public.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/param_parser_test.cc, line 236 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-Kd1qopQQI8gqYALovzO:-Kd1w7S94S1r1_D5M8RQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8017ef871e60bd3a4e81ab3d594b15502358a75/drake/examples/QPInverseDynamicsForHumanoids/param_parsers/test/param_parser_test.cc#L236)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Some kind of comment, please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173)*

**Comment by david-german-tri** [comment]
-(status: curate commits before merging) :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5173#-:-Kd27i2QtARCpZfniek6:bmkuytt)*

**Pull request merged**
