### PR TITLE
Make Variables iterable in Python

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #8548

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8548)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri for feature-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-:-L9e4r4q6-9g_bLFOMUY:b-v5eaz3)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/symbolic_py.cc, line 143 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-L9ghtkY6xprm5Dw-Whi:-L9ghtkY6xprm5Dw-Whj:bxjld40) ([raw file](https://github.com/robotlocomotion/drake/blob/b9a2d4e5af8d97283b251b37afccceb46db554fd/bindings/pydrake/symbolic_py.cc#L143)):*
> ```cpp
>              return py::make_iterator(vars.begin(), vars.end());
>            },
>            py::keep_alive<
> ```

This has an odd linebreak; also, could you have the wording reflect that of the `systems` bindings?
```
// Keep alive, reference: `return` keeps `self` alive
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-:-L9giue4BPTr41Ttv3sI:b-2l0s3s)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 143 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-L9ghtkY6xprm5Dw-Whi:-L9jtbc8DbV_2lLb15jh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9a2d4e5af8d97283b251b37afccceb46db554fd/bindings/pydrake/symbolic_py.cc#L143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This has an odd linebreak; also, could you have the wording reflect that of the `systems` bindings?
```
// Keep alive, reference: `return` keeps `self` alive
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-:-L9jtcB6DPBwzM6gXN2L:b-3ojlqy)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8548#-:-L9kQdk6-fBlowl7JdgM:bnfp4nl)*

**Pull request merged**
