### PR TITLE
Add backward reachability example

### PR DESCRIPTION
**Pull request by jadecastro**
A "hello world" example for computing the backward reachable set for a simple system using occupation measures.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7850)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@soonho-tri feature review, +@ggould-tri platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-:-L3dbWcZc3AhPeRqXfcQ:b-bxb1es)*

**Comment by ggould-tri** [comment]
:lgtm:; some typos noted below.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dejjdwniZAgzt_xoa:-L3dejjdwniZAgzt_xob:b-tf48nd) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L90)):*
> ```cpp
> /// occupation measures capturing the reachable set.  By restricting the space
> /// of functions to polynomials and representing measures by their moments, we
> /// solve the dual relaxation over the space of nonegative functions in order to
> ```

FYI typo "nonegative"

---

*[examples/cubic_polynomial/backward_reachability.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3defTISUCq4WXtpYVa:-L3defTJo1MMMhA1lKQ6:b-qf7v5k) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L91)):*
> ```cpp
> /// of functions to polynomials and representing measures by their moments, we
> /// solve the dual relaxation over the space of nonegative functions in order to
> /// find a tight over-approximattion to the reachable set.
> ```

FYI typo "approximattion"

---

*[examples/cubic_polynomial/backward_reachability.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3derFNB7S1vtv6TrHr:-L3derFNB7S1vtv6TrHs:bisji9p) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L97)):*
> ```cpp
> /// B = {x | ‖x(0)‖ < 0.5}.
> void ComputeBackwardReachableSet() {
>   // Construct the system and .
> ```

FYI Not sure what this means; typo?

---

*[examples/cubic_polynomial/backward_reachability.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dferFTLIM4CEaRA8f:-L3dferFTLIM4CEaRA8g:b-gqycsg) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L121)):*
> ```cpp
>   const Polynomial gt = Polynomial{t * (T - t)};
> 
>   // Define the (symmeric) domain bounds on x: ‖x‖ ≤ x_bound (X = {x | gx ≥ 0}).
> ```

FYI typo "symmeric"

---

*[examples/cubic_polynomial/backward_reachability.cc, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dflnO-oM3Y3I1QnYj:-L3dflnO-oM3Y3I1QnYk:b-u9a3v6) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L125)):*
> ```cpp
>   const Polynomial gx = Polynomial{-(x - x_bound) * (x + x_bound)};
> 
>   // Define the terminal set: : ‖x(T)‖ ≤ 0.1 (X_T = {x | gxT ≥ 0}).
> ```

FYI typo -- double colon `: : `?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-:-L3dgFHsed1NZE91mttb:bnc1zjm)*

**Comment by jadecastro** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dejjdwniZAgzt_xoa:-L3dhD3KGbH7JA5ORZAH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L90)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "nonegative"
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3defTISUCq4WXtpYVa:-L3dhFQqdCFrTqp2lrh_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L91)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "approximattion"
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3derFNB7S1vtv6TrHr:-L3dhNXIUS3RTfQoj_rm:bhgzgz) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L97)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Not sure what this means; typo?
</blockquote></details>

Done. (D'oh!)

---

*[examples/cubic_polynomial/backward_reachability.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dferFTLIM4CEaRA8f:-L3dhPPeshidJYIYoPZc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L121)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "symmeric"
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dflnO-oM3Y3I1QnYj:-L3dhXifNGT2XYeJMqeL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L125)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo -- double colon `: : `?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Comment by soonho-tri** [comment]
:lgtm:; BTWs and minor suggestions. Also please check the CI failures.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dg1U-ecRu9EszReDh:-L3dg1U-ecRu9EszReDi:b-k8rw4n) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L60)):*
> ```cpp
> /// of coefficients of `p` and `l` is the corresponding vector of moments of the
> /// Lebesgue measure over the domain.
> Expression MakeVolumetricCost(const Polynomial& p, BoundingBox b) {
> ```

BTW, `BoundingBox b` -> `const BoundingBox& b`? Then we need to replace `b.{first,second}[var]` with `b.{first,second}.at(var)`.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dgGADv7sNWjZsjEFZ:-L3dgGADv7sNWjZsjEF_:bl3kcxl) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L65)):*
> ```cpp
> 
>   // Build a moment vector.
>   MapType map = p.monomial_to_coefficient_map();
> ```

BTW, this can be `const MapType& map = p.monomial_to_coefficient_map()` (because `monomial_to_coefficient_map()` returns a const-ref).

---

*[examples/cubic_polynomial/backward_reachability.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dljv_ruHbAup4YBAw:-L3dljv_ruHbAup4YBAx:b-6w6uo0) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L69)):*
> ```cpp
>   const Variables indeterminates = p.indeterminates();
>   for (const auto& monomial : map) {
>     std::map<Variable, int> powers = monomial.first.get_powers();
> ```

BTW, this can be `const std::map<Variable, int>& powers = monomial.first.get_powers();` (because `get_powers()` returns a const-ref). Then we need to replace `powers[var]` with `powers.at(var)`.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dhCJsPGDNlJIxuGrc:-L3dhCJsPGDNlJIxuGrd:b-ns2f3g) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L128)):*
> ```cpp
>   const Polynomial gxT{-(x - 0.1) * (x + 0.1)};
> 
>   // Define the ground-truth BRS (for plotting only): ‖x(0)‖ < 0.5 (a.k.a. X₀).
> ```

BTW, `BRS` -> `BRS (Backward Reachable Set)` at this first used here.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3di0yBqatIoHkP1rWN:-L3di0yBqatIoHkP1rWO:bj3gzm4) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L153)):*
> ```cpp
>   prog.AddSosConstraint(-Lv - qx * gx - qt * gt);
> 
>   // v(t=T, x) is sos for all x ∈ X_T.  Note that this constraint, coupled with
> ```

BTW, `sos` -> `SOS` in all comments?

---

*[examples/cubic_polynomial/backward_reachability.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3doFicpVuJ4K-dcZ4p:-L3doFicpVuJ4K-dcZ4q:bklqdk4) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L180)):*
> ```cpp
> 
>   const solvers::SolutionResult result{prog.Solve()};
>   DRAKE_DEMAND(result == solvers::SolutionResult::kSolutionFound);
> ```

Without passing `--config mosek`, this line still passes but we end up with an incorrect result/graph. I think it's better to check if Mosek is used in MP. How about something like,

```c++
  DRAKE_DEMAND(prog.GetSolverId() == solvers::MosekSolver::id());
```

or generating an error message?

---

*[examples/cubic_polynomial/backward_reachability.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dmitndbC5nCwSPYJs:-L3dmitndbC5nCwSPYJt:bbn5rgd) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L187)):*
> ```cpp
> 
>   Environment w_env;
>   for (const auto& it : w.decision_variables()) {
> ```

BTW, `it` sounds like this is an iterator while it's a variable. Probably better to rename it to `v` or `var`?

---

*[examples/cubic_polynomial/backward_reachability.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dk23r2QnEReue3x6f:-L3dk23skYzQz_3jYijR:by65qts) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L194)):*
> ```cpp
>   // Serialize the result and generate Python plots.  In particular, plot the
>   // true indicator function of B and w (its polynomial outer-approximation).
>   // To plot, execute:
> ```

BTW, worth asking users to run  `bazel run //examples/cubic_polynomial:backward_reachability -c dbg --config=mosek` first?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-:-L3domYBlUzugQ07qw2l:b-70dekg)*

**Comment by jadecastro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dg1U-ecRu9EszReDh:-L3e3QBV6BbPKevtruG0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L60)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `BoundingBox b` -> `const BoundingBox& b`? Then we need to replace `b.{first,second}[var]` with `b.{first,second}.at(var)`.
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dgGADv7sNWjZsjEFZ:-L3e3Xd3BKsm9jDGH2eY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L65)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this can be `const MapType& map = p.monomial_to_coefficient_map()` (because `monomial_to_coefficient_map()` returns a const-ref).
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dljv_ruHbAup4YBAw:-L3e3kAcnD5K8MMrRd1a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L69)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this can be `const std::map<Variable, int>& powers = monomial.first.get_powers();` (because `get_powers()` returns a const-ref). Then we need to replace `powers[var]` with `powers.at(var)`.
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dhCJsPGDNlJIxuGrc:-L3e3w7HSR04pwad_rL2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L128)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `BRS` -> `BRS (Backward Reachable Set)` at this first used here.
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3di0yBqatIoHkP1rWN:-L3e40yF0H2oVLsGZZ8t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L153)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `sos` -> `SOS` in all comments?
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3doFicpVuJ4K-dcZ4p:-L3e4RjLdNo2lWqy1god:bcvjgzp) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L180)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Without passing `--config mosek`, this line still passes but we end up with an incorrect result/graph. I think it's better to check if Mosek is used in MP. How about something like,

```c++
  DRAKE_DEMAND(prog.GetSolverId() == solvers::MosekSolver::id());
```

or generating an error message?
</blockquote></details>

Good idea. Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 187 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dmitndbC5nCwSPYJs:-L3e4ZYgV8curzKf_suF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L187)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `it` sounds like this is an iterator while it's a variable. Probably better to rename it to `v` or `var`?
</blockquote></details>

Done.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3dk23r2QnEReue3x6f:-L3e4b1EyXEPMTGULcjF:bt3r0ev) ([raw file](https://github.com/robotlocomotion/drake/blob/dcf9a034d7b5804b947b690c7925310e06818eea/examples/cubic_polynomial/backward_reachability.cc#L194)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, worth asking users to run  `bazel run //examples/cubic_polynomial:backward_reachability -c dbg --config=mosek` first?
</blockquote></details>

Yes, I like that. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3e8kqoNOd9md7VB2EF:-L3e8kqoNOd9md7VB2EG:b-7evfle) ([raw file](https://github.com/robotlocomotion/drake/blob/5106ef9f863425cce0756107518626a1df43fc11/examples/cubic_polynomial/backward_reachability.cc#L105)):*
> ```cpp
>   // Set up the optimization problem and declare the indeterminates.
>   solvers::MathematicalProgram prog;
>   DRAKE_DEMAND(prog.GetSolverId() == solvers::MosekSolver::id());
> ```

FYI, `GetSolverId()` should be called after calling `Solve()`.
```
  /**
   * Returns the ID of the solver that was used to solve this program.
   * Returns empty if Solve() has not been called.
   */
  optional<SolverId> GetSolverId() const { return solver_id_; }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Comment by jadecastro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/cubic_polynomial/backward_reachability.cc, line 105 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7850#-L3e8kqoNOd9md7VB2EF:-L3eAGj5KIyMGvfWhwXx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5106ef9f863425cce0756107518626a1df43fc11/examples/cubic_polynomial/backward_reachability.cc#L105)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `GetSolverId()` should be called after calling `Solve()`.
```
  /**
   * Returns the ID of the solver that was used to solve this program.
   * Returns empty if Solve() has not been called.
   */
  optional<SolverId> GetSolverId() const { return solver_id_; }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7850)*

**Pull request merged**
