### PR TITLE
Get the linear solver for generic A.

### PR DESCRIPTION
**Pull request by hongkai-dai**
When A contains double or symbolic::Expression, the linear solver matrix also contains the same scalar type. When A contains AutoDiffScalar, the linear solver matrix contains double scalar.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752#-:-MjIPLVa8EzDDdJ-w_X9:bkz6hi4)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjIPRzB7cX9QBCQfRHg:b-dpmqkc) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
> ```cpp
>         "The scalar type should be double");
>   }
>   static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime == 2,
> ```

@rpoyner-tri , I don't quite understand this compilation error here. Is it OK if you could help me out? Thanks a lot!

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjKfZh1D1Zf38ONQ40s:b1bbp9) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@rpoyner-tri , I don't quite understand this compilation error here. Is it OK if you could help me out? Thanks a lot!
</blockquote></details>

solved already?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjKgbk2BrYrmoMvbYsp:b-1078zh) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

solved already?
</blockquote></details>

Sorry, I mean if I change it to 
```cc
  static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime == DerivedA::RowsAtCompileTime,
                "The matrix rows don't match");
```
then I get a compilation error (with gcc-7)
```
math/test/linear_solve_test.cc:325:72: warning: comparison between 'enum Eigen::Matrix<double, 2, 2>::<unnamed>' and 'enum Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, 2, 2>::<unnamed>' [-Wenum-compare]
   static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime ==
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                  DerivedA::RowsAtCompileTime,
                  ~~~~~~~~
```
I don't understand where this `enum` come from.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjLS_Km8BQJrfu9m_h_:b-t9b3ew) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, I mean if I change it to 
```cc
  static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime == DerivedA::RowsAtCompileTime,
                "The matrix rows don't match");
```
then I get a compilation error (with gcc-7)
```
math/test/linear_solve_test.cc:325:72: warning: comparison between 'enum Eigen::Matrix<double, 2, 2>::<unnamed>' and 'enum Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, 2, 2>::<unnamed>' [-Wenum-compare]
   static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime ==
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                  DerivedA::RowsAtCompileTime,
                  ~~~~~~~~
```
I don't understand where this `enum` come from.
</blockquote></details>

Interesting. `clang` is fine with the comparison you want to use. `g++` is not. Right, and it is not complaining about value mismatch, it's warning about "enum comparison". A dive into Eigen source code does indeed show that `RowsAtCompileTime` is defined using an `enum` trick:

```
$ dpkg -L libeigen3-dev |xargs grep RowsAtCompileTime 2>/dev/null |grep enum
/usr/include/eigen3/Eigen/src/Core/MatrixBase.h:    enum { HomogeneousReturnTypeDirection = ColsAtCompileTime==1&&RowsAtCompileTime==1 ? ((internal::traits<Derived>::Flags&RowMajorBit)==RowMajorBit ? Horizontal : Vertical)
/usr/include/eigen3/Eigen/src/Core/util/Macros.h:  enum { RowsAtCompileTime = Eigen::internal::traits<Derived>::RowsAtCompileTime, \
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { ret = size_at_compile_time<traits<XprType>::RowsAtCompileTime,traits<XprType>::ColsAtCompileTime>::ret };
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { Rows = traits<T>::RowsAtCompileTime,
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { Rows = traits<T>::RowsAtCompileTime,
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { diag_size = EIGEN_SIZE_MIN_PREFER_DYNAMIC(ExpressionType::RowsAtCompileTime, ExpressionType::ColsAtCompileTime),
/usr/include/eigen3/Eigen/src/Geometry/Umeyama.h:  enum { Dimension = EIGEN_SIZE_MIN_PREFER_DYNAMIC(Derived::RowsAtCompileTime, OtherDerived::RowsAtCompileTime) };
/usr/include/eigen3/Eigen/src/SVD/JacobiSVD.h:  enum { a = MatrixType::RowsAtCompileTime != Dynamic &&
```

So, yes, the -Wenum-compare warning is legit (in compiler world), but also sorta nonsense. I'll see about a workaround.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjLWBrkCrOgaNrcCJpT:b-yo1yvp) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Interesting. `clang` is fine with the comparison you want to use. `g++` is not. Right, and it is not complaining about value mismatch, it's warning about "enum comparison". A dive into Eigen source code does indeed show that `RowsAtCompileTime` is defined using an `enum` trick:

```
$ dpkg -L libeigen3-dev |xargs grep RowsAtCompileTime 2>/dev/null |grep enum
/usr/include/eigen3/Eigen/src/Core/MatrixBase.h:    enum { HomogeneousReturnTypeDirection = ColsAtCompileTime==1&&RowsAtCompileTime==1 ? ((internal::traits<Derived>::Flags&RowMajorBit)==RowMajorBit ? Horizontal : Vertical)
/usr/include/eigen3/Eigen/src/Core/util/Macros.h:  enum { RowsAtCompileTime = Eigen::internal::traits<Derived>::RowsAtCompileTime, \
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { ret = size_at_compile_time<traits<XprType>::RowsAtCompileTime,traits<XprType>::ColsAtCompileTime>::ret };
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { Rows = traits<T>::RowsAtCompileTime,
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { Rows = traits<T>::RowsAtCompileTime,
/usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:  enum { diag_size = EIGEN_SIZE_MIN_PREFER_DYNAMIC(ExpressionType::RowsAtCompileTime, ExpressionType::ColsAtCompileTime),
/usr/include/eigen3/Eigen/src/Geometry/Umeyama.h:  enum { Dimension = EIGEN_SIZE_MIN_PREFER_DYNAMIC(Derived::RowsAtCompileTime, OtherDerived::RowsAtCompileTime) };
/usr/include/eigen3/Eigen/src/SVD/JacobiSVD.h:  enum { a = MatrixType::RowsAtCompileTime != Dynamic &&
```

So, yes, the -Wenum-compare warning is legit (in compiler world), but also sorta nonsense. I'll see about a workaround.
</blockquote></details>

Maybe something like this?

```
diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index f2e9d0de9c..f881f80f01 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -322,15 +322,17 @@ void CheckGetLinearSolver(const Eigen::MatrixBase<DerivedA>& A) {
                        double>,
         "The scalar type should be double");
   }
-  static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime == 2,
-                /* Not sure why, but if I use DerivedA::RowsAtCompileTime, and
-                   DerivedA is Eigen::Matrix<AutoDiffXd, 2, 2>, then the
-                   compiler throws error on comparing enum */
-                // DerivedA::RowsAtCompileTime,
-                "The matrix rows don't match");
-  static_assert(decltype(linear_solver)::MatrixType::ColsAtCompileTime == 2,
-                // DerivedA::ColsAtCompileTime,
-                "The matrix rows don't match");
+
+  // Cast away the enum types of the matrix metrics so we can compare without
+  // compiler warnings.
+  static constexpr int RowsSolver =
+      static_cast<int>(decltype(linear_solver)::MatrixType::RowsAtCompileTime);
+  static constexpr int RowsA = static_cast<int>(DerivedA::RowsAtCompileTime);
+  static_assert(RowsSolver == RowsA, "The matrix rows don't match");
+  static constexpr int ColsSolver =
+      static_cast<int>(decltype(linear_solver)::MatrixType::ColsAtCompileTime);
+  static constexpr int ColsA = static_cast<int>(DerivedA::ColsAtCompileTime);
+  static_assert(ColsSolver == ColsA, "The matrix rows don't match");
 }
 
 TEST_F(LinearSolveTest, GetLinearSolver) {
```

Will also mail you a patch file suitable for `git apply`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjLZ16P5d3OUH6oXhwb:b5zwuqr) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe something like this?

```
diff --git a/math/test/linear_solve_test.cc b/math/test/linear_solve_test.cc
index f2e9d0de9c..f881f80f01 100644
--- a/math/test/linear_solve_test.cc
+++ b/math/test/linear_solve_test.cc
@@ -322,15 +322,17 @@ void CheckGetLinearSolver(const Eigen::MatrixBase<DerivedA>& A) {
                        double>,
         "The scalar type should be double");
   }
-  static_assert(decltype(linear_solver)::MatrixType::RowsAtCompileTime == 2,
-                /* Not sure why, but if I use DerivedA::RowsAtCompileTime, and
-                   DerivedA is Eigen::Matrix<AutoDiffXd, 2, 2>, then the
-                   compiler throws error on comparing enum */
-                // DerivedA::RowsAtCompileTime,
-                "The matrix rows don't match");
-  static_assert(decltype(linear_solver)::MatrixType::ColsAtCompileTime == 2,
-                // DerivedA::ColsAtCompileTime,
-                "The matrix rows don't match");
+
+  // Cast away the enum types of the matrix metrics so we can compare without
+  // compiler warnings.
+  static constexpr int RowsSolver =
+      static_cast<int>(decltype(linear_solver)::MatrixType::RowsAtCompileTime);
+  static constexpr int RowsA = static_cast<int>(DerivedA::RowsAtCompileTime);
+  static_assert(RowsSolver == RowsA, "The matrix rows don't match");
+  static constexpr int ColsSolver =
+      static_cast<int>(decltype(linear_solver)::MatrixType::ColsAtCompileTime);
+  static constexpr int ColsA = static_cast<int>(DerivedA::ColsAtCompileTime);
+  static_assert(ColsSolver == ColsA, "The matrix rows don't match");
 }
 
 TEST_F(LinearSolveTest, GetLinearSolver) {
```

Will also mail you a patch file suitable for `git apply`.
</blockquote></details>

Ah cool! Thanks a lot Rico. I didn't realize the trick static constexpr int. BTW, I tried to remove `static` and only use `constexpr int`, the compiler still works. May I ask why we use `static constexpr` here?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjL_bzG4T2aNxFCEXpJ:b-3ta251) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ah cool! Thanks a lot Rico. I didn't realize the trick static constexpr int. BTW, I tried to remove `static` and only use `constexpr int`, the compiler still works. May I ask why we use `static constexpr` here?
</blockquote></details>

There are subtleties here, and I may not yet have them right. `static` in function scope is a lifetime specifier that means there will only ever be one storage address for the variable, it lasts for the whole life of the program, and it won't (say) be recreated every time the function is entered. The interesting bit here is that we only ever use the values at compile time, so we might be (a hair) better off omitting `static`, which would give the compiler the option of not emitting code or storage for those variable at all ; they would just vanish after compile time.

A quick experiment shows that `constexpr int` (no `static`) will also compile, and should allow the compiler to forget those variables after compile time.

A somewhat confusing discussion of the issues is here: https://stackoverflow.com/questions/13865842/does-static-constexpr-variable-inside-a-function-make-sense

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/linear_solve.h, line 264 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdYi0D0L2CIn1flvp:-MjLdYi0D0L2CIn1flvq:b-9oyzcx) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L264)):*
> ```
> used to solver
> ```
looks like `slover` is a typo there
___
*[math/linear_solve.h, line 297 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdtEZ4G-tOQEHbaJe:-MjLdtEZ4G-tOQEHbaJf:b-iqz697) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L297)):*
> ```
> GetLinearSolve<
> ```
typo
___
*[math/linear_solve.h, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdxkL1QELSVY-LOKl:-MjLdxkL1QELSVY-LOKm:b-iqz697) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L305)):*
> ```
> GetLinearSolve<
> ```
typo
___
*[math/linear_solve.h, line 308 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe1Ch5C6iWw_HaqQv:-MjLe1Ch5C6iWw_HaqQw:b-iqz697) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L308)):*
> ```
> GetLinearSolve<
> ```
typo
___
*[math/linear_solve.h, line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe5jmDxWJynDj5zcm:-MjLe5jmDxWJynDj5zcn:b-p0wzjf) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L338)):*
> ```objc
> /**
>  * Get the linear solver for a matrix A containing AutoDiffScalar.
>  * The returned linear solver will have matrix containing double.
> ```

I find this line confusing. I thought that the resulting solver would promote to ADS. What am I missing?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/linear_solve.h, line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe5jmDxWJynDj5zcm:-MjLfVBZ2VODx0sjlly2:b-5p4zj8) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L338)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I find this line confusing. I thought that the resulting solver would promote to ADS. What am I missing?
</blockquote></details>

Maybe I don't understand what the table int the big comment above means then.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[math/linear_solve.h, line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe5jmDxWJynDj5zcm:-MjLhu1wBft-lvsPfLso:b-p8fklf) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L338)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe I don't understand what the table int the big comment above means then.
</blockquote></details>

Ah, the scalar type of the *result* and of the solver matrix aren't necessarily the same. Is this actually confusing, or will I be the only one?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[math/linear_solve.h, line 264 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdYi0D0L2CIn1flvp:-MjMBqkz9SGZY400rCYq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L264)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> used to solver
> ```
looks like `slover` is a typo there
</blockquote></details>

Done.
___
*[math/linear_solve.h, line 297 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdtEZ4G-tOQEHbaJe:-MjMC5DjDLPYhMGMRMxD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L297)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> GetLinearSolve<
> ```
typo
</blockquote></details>

Done.
___
*[math/linear_solve.h, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLdxkL1QELSVY-LOKl:-MjMC5lC5J0Hu8s8xhhi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L305)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> GetLinearSolve<
> ```
typo
</blockquote></details>

Done.
___
*[math/linear_solve.h, line 308 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe1Ch5C6iWw_HaqQv:-MjMC69j-XX5tjrBhcTg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L308)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> GetLinearSolve<
> ```
typo
</blockquote></details>

Done.
___
*[math/linear_solve.h, line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjLe5jmDxWJynDj5zcm:-MjMC71gC9DF42uTa6ll:bauay4b) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7c217b931db7ffdafef90d5221b0aa3ca76287/math/linear_solve.h#L338)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ah, the scalar type of the *result* and of the solver matrix aren't necessarily the same. Is this actually confusing, or will I be the only one?
</blockquote></details>

Done. Good call. I updated the table. Now the table in `get_linear_solver` section indicates the scalar type in the matrix of the solver. The table in `linear_solve` section indicates the scalar type of the result x.
___
*[math/test/linear_solve_test.cc, line 325 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjIPRzB7cX9QBCQfRHf:-MjMBhQ_5DmaPyQEIawG:b-nzh4rv) ([raw file](https://github.com/robotlocomotion/drake/blob/37455b0c4e2ebe55e5332b7e7ceaae757ff8e4f2/math/test/linear_solve_test.cc#L325)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

There are subtleties here, and I may not yet have them right. `static` in function scope is a lifetime specifier that means there will only ever be one storage address for the variable, it lasts for the whole life of the program, and it won't (say) be recreated every time the function is entered. The interesting bit here is that we only ever use the values at compile time, so we might be (a hair) better off omitting `static`, which would give the compiler the option of not emitting code or storage for those variable at all ; they would just vanish after compile time.

A quick experiment shows that `constexpr int` (no `static`) will also compile, and should allow the compiler to forget those variables after compile time.

A somewhat confusing discussion of the issues is here: https://stackoverflow.com/questions/13865842/does-static-constexpr-variable-inside-a-function-make-sense
</blockquote></details>

I see, thanks a lot for the explanation.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@ggould-tri for Monday platform review.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752#-:-MjMESQT9ghu3-uWAyyC:byqxkgc)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752#-:-MjUTA7B0voPl40V7mJk:bnfp4nl)* status: 8 unresolved discussions (waiting on @hongkai-dai)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjUPkIM1-SB3ggVSdVo):*
minor:  This headline is a little bit cryptic.  `A` has no significance to most readers at this level of generality (and indeed would be prohibited outright as a name by our styleguide under most circumstances).
___
*[math/linear_solve.h, line 283 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjURgJc05wWN3nc3DXe:-MjURgJc05wWN3nc3DXf:b-d3oxm2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L283)):*
> ```objc
>  * Eigen::Vector2d b_val(3, 4);
>  * const Eigen::Vector2d x_val =
>  * LinearSolve(GetLinearSolver<Eigen::LLT>(A_val), A_val, b_val);
> ```

minor:  Should this be indented?
___
*[math/linear_solve.h, line 295 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjURoF54RFVMzx6_Zvy:-MjURoF54RFVMzx6_Zvz:b-d3oxm2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L295)):*
> ```objc
>  * // Solve A * x = b with A containing gradient.
>  * const Eigen::Matrix<AutoDiffXd, 2, 1> x_ad1 =
>  * LinearSolve(GetLinearSolver<Eigen::LLT>(A_ad), A_ad, b_val);
> ```

minor:  Should this be indented?
___
*[math/linear_solve.h, line 303 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjURpW_EpjwEQ9fR5Su:-MjURpW_EpjwEQ9fR5Sv:b-d3oxm2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L303)):*
> ```objc
>  * // Solve A * x = b with b containing gradient.
>  * const Eigen::Matrix<AutoDiffXd, 2, 1> x_ad2 =
>  * LinearSolve(GetLinearSolver<Eigen::LLT>(A_val), A_val, b_ad);
> ```

minor:  Should this be indented?
___
*[math/linear_solve.h, line 306 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjURqKd7_JsbUwHCLg9:-MjURqKd7_JsbUwHCLgA:b-d3oxm2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L306)):*
> ```objc
>  * // Solve A * x = b with both A and b containing gradient.
>  * const Eigen::Matrix<AutoDiffXd, 2, 1> x_ad3 =
>  * LinearSolve(GetLinearSolver<Eigen::LLT>(A_ad), A_ad, b_ad);
> ```

minor:  Should this be indented?
___
*[math/linear_solve.h, line 336 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjURDWV0JEoSJF2nFiN:-MjURDWW2e1bqmQAqu_X:b-p0yair) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L336)):*
> ```objc
> /**
>  * Get the linear solver for a matrix A containing AutoDiffScalar.
>  * The returned linear solver will have matrix containing double.
> ```

minor:   "will have matrix containing double" is somewhat strained and confusing grammar.  Given the complexity of the code, it might be simplest to write this in pseudocode C++ style rather than English; "the returned linear solver will be `LinearSolverType<Matrix<double>>`" or similar? 
___
*[math/linear_solve.h, line 376 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjUSbgO2NYQfywEx1Zn:-MjUSbgO2NYQfywEx1Zo:b-koyye9) ([raw file](https://github.com/robotlocomotion/drake/blob/9a281b5bfacbf5f1dec62f42672aa6726fc7a8c6/math/linear_solve.h#L376)):*
> ```objc
>  * | b ＼ | double | ADS | Expr |
>  * |------|--------|-----|----- |
>  * |double| double | ADS |  NA  |
> ```

minor:  It is not clear why `double` cannot be upconverted to `Expr` in this case. This should probably have some explanation, or a todo or issue if it's just a matter of convenience.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15752#-MjUPkIM1-SB3ggVSdVo):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This headline is a little bit cryptic.  `A` has no significance to most readers at this level of generality (and indeed would be prohibited outright as a name by our styleguide under most circumstances).
</blockquote></details>

I added explanation of A in the commit message. Is it more clear now?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15752)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
