### PR TITLE
[sensors] Validate CameraConfig substructs only as part of the whole

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17852.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17854)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17854)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`systems/sensors/test/camera_config_test.cc` line 399 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17854#-NBNf-SC-LlWXfbpjNg6:-NBNf-SD8VHVJrV_FxOn:b-iivtdn) ([raw file](https://github.com/robotlocomotion/drake/blob/68f7d20c03bd15030d90a46e4142250a2c0feb5b/systems/sensors/test/camera_config_test.cc#L399)):*
> ```cpp
>     config.focal = CameraConfig::FovDegrees{};
>     EXPECT_NO_THROW(config.ValidateOrThrow());
>     EXPECT_NO_THROW(SaveYamlString(config));
> ```

FYI This line is the test that shows the bug with the original implementation -- saving an invalid Fov to YAML when all cameras were disabled used to throw an exception,.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@xuchenhan-tri for platform review, please.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17854#-:-NBNnaWZ-QxvjpLXAH-_:b-s6ko0)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17854#-:-NBO5dp-5Ji8-0U3g_Lw:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
