### PR TITLE
Fixed typo in comment.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2381)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri Since this is such a simple fix, can you serve as both feature and platform reviewer?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Fixed typo in comment\.
> 
> 
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2381#-:-KHzUGZP7kxhrYPqAh2h:-661375773)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@david-german-tri Since this is such a simple fix, can you serve as both feature and platform reviewer?</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2381#-:-KHzUR9LerHDRpD9A3Km:980077401)*

**Comment by liangfok** [comment]
Just a sec. I found another problem in the same sentence. Fix coming soon.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2381#-:-KHzVh41lPwGH4SU0mjb:-226072116)*

**Comment by liangfok** [comment]
Done. Ready for another round of review. PTAL. Thanks!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Just a sec. I found another problem in the same sentence. Fix coming soon.</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2381#-:-KHzX6z-9JGcFQdZrT5h:862576864)*

**Comment by liangfok** [comment]
CI build `clang-mac` failed with the following error: "Agent went offline during the build"

https://drake-jenkins.csail.mit.edu/job/experimental/1518/compiler=clang,label=mac/console

Since I don't think this error is related to this PR, I think this PR is ready to be merged.

**Pull request merged**
