### PR TITLE
Adds Multi-Model Support for Drake

### PR DESCRIPTION
**Pull request by liangfok**
This builds upon #3064 by adding multi-model support to Drake.

Here's what you should see (it's 5 Prius vehicles being simulated):

drake_rviz_5_vehicles

# Update 2016/08/16: LIDAR Sensors Enabled

Here's what you should see with the LIDAR sensors enabled:

screenshot from 2016-08-16 10 39 55

# Update 2016/08/25 - Multi-Model Working But Is Slow

Here's a screenshot showing all five Prius vehicles after they have moved from their start locations. You can see the trailing odometry sensor visualizations following the vehicles (they are seen in red).

screenshot from 2016-08-25 16 50 08

Getting multi-model support to work was extraordinarily difficult due to the use of templates, which results in the number of vehicles supported being hard-coded. @david-german-tri: Hopefully this will not be a problem in System 2.0!

# Demo Execution Instructions

Here are instructions on how to run the multi-car demo.

## Start the Simulation:

```
$ roslaunch drake_cars_examples multi_cars_on_plane.launch
```

## Start the Driving Command Publishers

Open five terminals and execte the following commands, one in each:

```
$ rosrun ackermann_drive_teleop ackermann_drive_keyop.py 1.0 0.7 /drake/Prius_1/ackermann_cmd
$ rosrun ackermann_drive_teleop ackermann_drive_keyop.py 1.0 0.7 /drake/Prius_2/ackermann_cmd
$ rosrun ackermann_drive_teleop ackermann_drive_keyop.py 1.0 0.7 /drake/Prius_3/ackermann_cmd
$ rosrun ackermann_drive_teleop ackermann_drive_keyop.py 1.0 0.7 /drake/Prius_4/ackermann_cmd
$ rosrun ackermann_drive_teleop ackermann_drive_keyop.py 1.0 0.7 /drake/Prius_5/ackermann_cmd
``` 

You should now be able to command each car individually through these five terminals.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3103)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3103#-:-KOmiSuSB1pA55wLqV6T:bb329pf)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3103#-:-KOulyXQMOK3OJQgoPwb:bb329pf)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4194/ and is thus ready for review. Since this PR builds upon #3064:

+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3103#-:-KQMBjUsL_jsm_KDbIZO:bmydfto)*

**Comment by sherm1** [comment]
@liangfok, this is big so maybe hold off platform review assignment until feature reviewed? -@sherm1

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3103#-:-KQSI2PGFZ5cXNa_spWX:b25qyjb)*

**Comment by liangfok** [comment]
Alright. Based on feedback from @amcastro-tri I shall split this PR into small munchkin-sized pieces.

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3103#-:-KQSLS0pxL7ilwB5f0-g:b-tufunv)*

**Pull request closed without merging**
