### PR TITLE
framework_py: Add bindings for VectorSystem.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Got some bugfixes in, but end-user use should be straightforward (when `T = double`).

\cc @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7880)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@thduynguyen for feature review, please, if you feel comfortable with it.
+@sherm1 for platform review, please. (Let me know if you'd like me to defer this to Monday's reviewer.)

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L3onsl65_X_XM2BOHDA:b65sgpl)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by sherm1** [comment]
I'll wait until a feature review pass is done.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L3orkfEEmuiTL6LNnVL:bbew9sm)*

**Comment by RussTedrake** [comment]
Wow.  Amazing.  The user result is perfect.  I read through all of the lines, but don’t know enough pybind to really count as review.  Thanks for doing it!!

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L3ou7UvQqKEuFPBHaEP:bjbne5q)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by thduynguyen** [comment]
@EricCousineau-TRI: This will probably take me at least 2 days as I need to learn pybind. Please find another reviewer if you can't wait?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L41esCXps5whq_EtJkv:b5t252f)*

**Comment by EricCousineau-TRI** [comment]
Can do!
-@thduynguyen
+@jadecastro for feature review, please.

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L41n5LrTQ7kZjbT0AgU:b701vn0)*

**Comment by EricCousineau-TRI** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L41sGh2uQjLsSddy6dG:-L41sGh3aAtajy-pVKYS:b-cqxd5p) ([raw file](https://github.com/robotlocomotion/drake/blob/1d42169786ba5eb126871d03efa6de96cea1bffe/bindings/pydrake/systems/framework_py.cc#L76)):*
> ```cpp
> };
> 
> // Use CRTP to leverage prior binding information, per documentation:
> ```

Er... CRTP is incorrect here. Will change on next revision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by EricCousineau-TRI** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/framework_py.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L41sGh2uQjLsSddy6dG:-L47BjKGgK7KVJcHCnS2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1d42169786ba5eb126871d03efa6de96cea1bffe/bindings/pydrake/systems/framework_py.cc#L76)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Er... CRTP is incorrect here. Will change on next revision.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by RussTedrake** [comment]
ping @jadecastro -- you ok doing this review?  I'm waiting for it to land.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L489rZliZf0V4HpnaUu:br9de6q)*

**Comment by jadecastro** [comment]
@RussTedrake - on it as we speak. (sorry for the delay!)

---

Reviewed 2 of 9 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L48A5ruF-3VdBs6Ri8k:b-d692lr)*

**Comment by RussTedrake** [comment]
Thx!

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L48AhsUzzm_cOYLWXys:bb74ptu)*

**Comment by jadecastro** [comment]
:lgtm: on both Mac and Ubuntu

---

Reviewed 4 of 9 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test.py, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L48MFImS_wA6ESo8TjQ:-L48MFImS_wA6ESo8TjR:b-tn1o5p) ([raw file](https://github.com/robotlocomotion/drake/blob/65c3b414daff9597d2b803007d314c317be191cc/bindings/pydrake/systems/test/custom_test.py#L58)):*
> ```Python
>             self._DeclareDiscreteState(2)
>         else:
>             self._DeclareContinuousState(2)
> ```

BTW, it seems the bindings support several overloads of `DeclareContinuousState`, but only one is tested. Consider adding tests for the remaining ones?

---

*[bindings/pydrake/systems/test/vector_test.py, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L48P0JeC9RY9rXoxIMt:-L48P0JeC9RY9rXoxIMu:bze5nhh) ([raw file](https://github.com/robotlocomotion/drake/blob/65c3b414daff9597d2b803007d314c317be191cc/bindings/pydrake/systems/test/vector_test.py#L26)):*
> ```Python
>     def test_basic_vector_double(self):
>         # Test constructing vectors of sizes [0, 1, 2], and ensure that we can
>         # consruct from both lists and `np.array` objects with no ambiguity.
> ```

BTW typo: "consruct"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L48D_n9HwB1vYgmvzJA:b-kqaihe)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test.py, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L48MFImS_wA6ESo8TjQ:-L49mvxEJRvP_VGHRfh6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65c3b414daff9597d2b803007d314c317be191cc/bindings/pydrake/systems/test/custom_test.py#L58)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, it seems the bindings support several overloads of `DeclareContinuousState`, but only one is tested. Consider adding tests for the remaining ones?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/vector_test.py, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L48P0JeC9RY9rXoxIMt:-L49n4xOOPVcQhGOcNuf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65c3b414daff9597d2b803007d314c317be191cc/bindings/pydrake/systems/test/vector_test.py#L26)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW typo: "consruct"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by jadecastro** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 281 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L4Br9FNGK3I6RWEA_1V:-L4Br9FNGK3I6RWEA_1W:b-4tslyc) ([raw file](https://github.com/robotlocomotion/drake/blob/2686938654b87d7a78ef3b667cb08e9438445ed4/bindings/pydrake/systems/framework_py.cc#L281)):*
> ```cpp
>          &Context<T>::get_continuous_state_vector,
>          py_reference_internal)
>     .def("get_mutable_continuous_state_vector",
> ```

FYI, `get_mutable_continuous_state_vector` doesn't seem to have a unit test. Ditto for `get_mutable_discrete_state_vector`, `get_abstract_state`, and `get_mutable_abstract_state`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by EricCousineau-TRI** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L41sGh2uQjLsSddy6dG:-L4BynVRElFY4NfEY8nO:b-mgys91) ([raw file](https://github.com/robotlocomotion/drake/blob/1d42169786ba5eb126871d03efa6de96cea1bffe/bindings/pydrake/systems/framework_py.cc#L76)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW @jadecastro Could you acknowledge this convo? Reviewable is picky about self-comments for whatever reason.

---

*[bindings/pydrake/systems/framework_py.cc, line 281 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L4Br9FNGK3I6RWEA_1V:-L4Bz0KcR8HPntlKkpvg:b-mux695) ([raw file](https://github.com/robotlocomotion/drake/blob/2686938654b87d7a78ef3b667cb08e9438445ed4/bindings/pydrake/systems/framework_py.cc#L281)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

FYI, `get_mutable_continuous_state_vector` doesn't seem to have a unit test. Ditto for `get_mutable_discrete_state_vector`, `get_abstract_state`, and `get_mutable_abstract_state`.
</blockquote></details>

Done. Removed abstract state (need to do that in a follow-up PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by EricCousineau-TRI** [comment]
BTW I will be throwing in a few more methods (DeclarePeriodicDiscreteUpdate

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L4Bz9l4KXb6EeMeM-H6:b67movo)*

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI 
> Could you acknowledge this convo? Reviewable is picky about self-comments for whatever reason.

If you click the circle widget on the discussion box, you can explicitly mark yourself satisfied and then everything is good.

**Comment by jadecastro** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by EricCousineau-TRI** [comment]
Awesome, thank you for the tip!

-@sherm1 for platform review.
+@seancurtis-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L4Cafzp53Y0UrnAo8if:b4znxfe)*

**Comment by EricCousineau-TRI** [comment]
Added in `_DeclarePeriodicDiscreteUpdate` per Russ's request, and delegated testing to be general (rather than specific to `VectorSystem`).

Sorry for the scope creep - let me know if this should be split off into a separate PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L4Ciz54Mmi7LwSKhAnk:bans0pr)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with one small nit.

---

Reviewed 2 of 9 files at r1, 3 of 6 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/vector_test.py, line 35 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L4D7XSaYmZFB7iLvzzW:-L4D7XSb-xpTvYnkozID:b9c8zyi) ([raw file](https://github.com/robotlocomotion/drake/blob/8400600213824468a9c2c88c0226dee98834462a/bindings/pydrake/systems/test/vector_test.py#L35)):*
> ```Python
>                 # Ensure that we can get vectors templated on double by
>                 # reference.
>                 init = func(init)
> ```

BTW Given this is originally set in the parent scope, then over-writing it in each loop seems surprising. It has the flavor of muddying the test. While that is not *actually* the case, the suggestion is disconcerting.

I note that you don't do:

```py
after_add = func(after_add)
after_set = func(after_set)
```

So, the appearance of it here seems particularly odd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-:-L4D8e7Szj_X3tl9eEXo:b-59m7wt)*

**Comment by EricCousineau-TRI** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/vector_test.py, line 35 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7880#-L4D7XSaYmZFB7iLvzzW:-L4DBkEcYXH-doU0OCBa:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/8400600213824468a9c2c88c0226dee98834462a/bindings/pydrake/systems/test/vector_test.py#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given this is originally set in the parent scope, then over-writing it in each loop seems surprising. It has the flavor of muddying the test. While that is not *actually* the case, the suggestion is disconcerting.

I note that you don't do:

```py
after_add = func(after_add)
after_set = func(after_set)
```

So, the appearance of it here seems particularly odd.
</blockquote></details>

Done. Thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Comment by RussTedrake** [comment]
Looks ready to go?  I'm eager to consume it (hoping it goes in tonight's nightlies)!

**Comment by jadecastro** [comment]
Reviewed 3 of 4 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7880)*

**Pull request merged**
