### PR TITLE
[C-IRIS] add IsGeometrySeparable function.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Certifies if a single pair of geometry is separable or not.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18742)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18742#-:-NNU1k1qD_9Hx1xGGOoQ:b7vod24)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18742#-:-NNbVPWVABa7I0aWuHQw:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:, but since I made many of the changes myself perhaps you should also do a thorough review?

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18742#-:-NNlugz92uxPcw6CNwJu:bgz3d73)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Comment by hongkai-dai** [comment]
Just checked the commit, all look good.

**Pull request merged**
