### PR TITLE
call_python: Change tempfile to mktemp.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7623)

### CODE REVIEW

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7623#-:-L0QuE0FMEB6Sv5IzphN:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by soonho-tri** [comment]
I've checked that it works on my local macs (including `high sierra` and `sierra`). Please feel free to merge it without waiting for the outcome from `mac-sierra-clang-bazel-experimental`.

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri Would you be OK with merging this, given @soonho-tri's testing? (I also tested it on `high sierra` and confirmed that it works.)

**Comment by soonho-tri** [comment]
+1 for override-merge.

**Comment by jwnimmer-tri** [comment]
linux-xenial-gcc-bazel-experimental passed, good enough for me.

**Pull request merged**
