### PR TITLE
Update drake::Systems bindings

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This does two things:

1. Reorder the bindings of drake::System to match the declaration in the header.
2. Add missing keyword arguments.

#relates #19005

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19053)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
The commits are curated for review (to be squash merged)

R1: Simply re-ordering of existing bindings. No changes to the code.
R2: Changes to the bindings (adding keywords and updating tests).

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) 
+@EricCousineau-TRI for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19053#-:-NRAHmG61qQnF9Zc_KAY:boqvx45)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2, thanks!

> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19053#-:-NRE5ffa1YWoMKzeM-SL:b-9wquo5)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19053#-:-NREEN4VCn2UL7Kig2AE:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
