### PR TITLE
[osqp_solver] Allow for warm-starting

### LINKED ISSUE #10048: Warm start OSQP solver
OSQP supports warm-starting. We haven't used this feature yet, and we should support it.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Loosely drawing from
https://github.com/DAIRLab/dairlib/blob/0da42bc/solvers/fast_osqp_solver.cc#L402-L414

Resolves #10048 - but does not attempt to reuse the solver workspace
Relates #16811

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19498)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
@hongkai-dai / @jwnimmer-tri What do y'all think?
\cc @mposa @yangwill 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19498#-:-NWahByV5Sr1jDtwcTJr:bk2nfkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by xuchenhan-tri** [comment]
Per platform review checklist, this PR needs a reviewer.

I assume this is already trumped by #19499?

**Comment by EricCousineau-TRI** [comment]
> I assume this is already trumped by #19499?

This is an extension on top of that PR; dual warm-starting can yield better performance than primal-only warm-start.
I've set it as `do not review` for now.

**Comment by jwnimmer-tri** [comment]
Closing as abandoned. When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
