### PR TITLE
Generate Drake exports from CPS

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Clean up mechanism for wholesale file generation in Bazel. Add [PyCPS](https://github.com/mwoehlke/pycps) and dependency [semantic_version](https://pypi.python.org/pypi/semantic_version/). Move generation of `drake-config.cmake` via `drake.cps` from an offline step to a Bazel build rule.

Besides that generating files during the build rather than offline is better anyway, this will also help streamline things when stuff in the CPS changes, as it will no longer be necessary to manually regenerate `drake-config.cmake`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6014)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I will look late tonight or first thing tomorrow.

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjEEwlZ9ef0JHm_OQf0:bq9keg9) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
> ```Python
>     commit = "v2.6.0",
>     sha256 = "110d9c75dc9670a188ab820503c6b40ea4ab3f1450a0aee5a90a24fd60aef358",
>     build_file = "tools/semantic_version.BUILD",
> ```

Use the PyPI version:

```
    new_http_archive(
        name = "semantic_version",
        urls = [
          "https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://d2tbce6hkathzp.cloudfront.net/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://s3.amazonaws.com/drake-mirror/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
        ]
        sha256 = "2a4328680073e9b243667b201119772aefc5fc63ae32398d6afafff07c4f54c0",
        build_file = "tools/semantic_version.BUILD",
        strip_prefix = "semantic_version-2.6.0",
   )
```


---

*[WORKSPACE, line 307 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGIr6K4I66vhvm9Wg:-KjEGIr6K4I66vhvm9Wh:b-ozee16) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L307)):*
> ```Python
>     sha256 = "314cfbb3b2bf812bbbc9759171a91049a9f181a8aad90c258c182aa9be5eb4e6",
>     build_file = "tools/pycps.BUILD",
> )
> ```

This needs a `strip_prefix` too, but probably `github_archive` needs tweaking to use it.

---

*[tools/semantic_version.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEFzFXffOttsHVkGt5:-KjEFzFXffOttsHVkGt6:be4jc38) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L3)):*
> ```
> load("@//tools:drake.bzl", "drake_generate_file")
> 
> drake_generate_file(
> ```

The `strip_prefix` in the `WORKSPACE` file should make this redundant.

---

*[tools/semantic_version.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEG5BkrY3-BnvjwbNF:-KjEG5BkrY3-BnvjwbNG:b-ac9umt) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L11)):*
> ```
> py_library(
>   name = "semantic_version",
>   srcs = glob(["semantic_version/*.py"]) + ["__init__.py"],
> ```

Remove `+ ["__init__.py"]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/pycps.BUILD, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGd7NoZc1dOYjYAU_:-KjEGd7O8ZxJvdo6Xqu2:banvsyr) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L9)):*
> ```
> 
> py_library(
>   name = "pycps",
> ```

Probably should be named `cps`.

---

*[tools/pycps.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGjicd3lYjGKICKFS:-KjEGjicd3lYjGKICKFT:b2nhwq7) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L11)):*
> ```
>   name = "pycps",
>   srcs = ["cps.py"],
>   deps = ["@semantic_version//:semantic_version"]
> ```

`,`

---

*[tools/pycps.BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGW0yeTKY1t7wYbyo:-KjEGW0yeTKY1t7wYbyp:b-x263d7) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L15)):*
> ```
> 
> py_binary(
>   name = "cps2cmake_executable",
> ```

Should be named `cps2cmake` by convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjEH4H9s043nJnRi_7M:brav9b5) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
> urls = [
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>           "https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz",
>           "https://d2tbce6hkathzp.cloudfront.net/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
>           "https://s3.amazonaws.com/drake-mirror/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
>         ]
</details>

```
urls = [
          "https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://d2tbce6hkathzp.cloudfront.net/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://s3.amazonaws.com/drake-mirror/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
        ],
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjEMKGILJhjTyaZB0Ui:bgurd6m) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> urls = [
>           "https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz",
>           "https://d2tbce6hkathzp.cloudfront.net/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
>           "https://s3.amazonaws.com/drake-mirror/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
>         ]

```
urls = [
          "https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://d2tbce6hkathzp.cloudfront.net/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
          "https://s3.amazonaws.com/drake-mirror/pypi/semantic_version/semantic_version-2.6.0.tar.gz",
        ],
```
</blockquote></details>

Why? What is the advantage of PyPI vs. upstream?

---

*[WORKSPACE, line 307 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGIr6K4I66vhvm9Wg:-KjEMQJ-VLwfx8HBQQz6:b-3hgrh9) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L307)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This needs a `strip_prefix` too, but probably `github_archive` needs tweaking to use it.
</blockquote></details>

Um... why? It seems to be Doing The Right Thing without it...

---

*[tools/pycps.BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGW0yeTKY1t7wYbyo:-KjEM_Mr0wRh850AQZD2:b8vwj5b) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L15)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should be named `cps2cmake` by convention.
</blockquote></details>

Can't; conflicts with the source file. This is (IMHO) really, really ugly, but AFAICT Bazel forces me to add some junk to the target name to disambiguate.

If there's a better way to export a source file that is already an executable script (that also needs dependencies), I'd love to know! (Note: at least one person on bazel-discuss already implied that there is not... :cry:)

---

*[tools/semantic_version.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEG5BkrY3-BnvjwbNF:-KjENIchY7Pna8-CS4PT:b-vnq9bv) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove `+ ["__init__.py"]`.
</blockquote></details>

Is it picked up automatically?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/pycps.BUILD, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGd7NoZc1dOYjYAU_:-KjENy4pfB62elemBde_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Probably should be named `cps`.
</blockquote></details>

Done.

---

*[tools/pycps.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGjicd3lYjGKICKFS:-KjENyUZrk8qQVD50NTY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`,`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjEPn36vNM1kfmfLDur:b-g2gofi) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why? What is the advantage of PyPI vs. upstream?
</blockquote></details>

It is consistent with the other Python packages that we use (and I already mirrored the PyPI version).

---

*[WORKSPACE, line 307 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGIr6K4I66vhvm9Wg:-KjEQ6SRIwIKj9CzxMUq:b-rv7owi) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L307)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Um... why? It seems to be Doing The Right Thing without it...
</blockquote></details>

It see, you are copying to change the file extension. Nevermind.

---

*[tools/semantic_version.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEG5BkrY3-BnvjwbNF:-KjEQ_U9wooA-b7yUxlH:b-q76avl) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L11)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Is it picked up automatically?
</blockquote></details>

That level will be removed. If it were not, you would add an `imports = ["semantic_version-2.6.0"]` line instead in any case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/pycps.BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEGW0yeTKY1t7wYbyo:-KjERvErmxKdT9wElSPE:bttqxbz) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/pycps.BUILD#L15)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Can't; conflicts with the source file. This is (IMHO) really, really ugly, but AFAICT Bazel forces me to add some junk to the target name to disambiguate.

If there's a better way to export a source file that is already an executable script (that also needs dependencies), I'd love to know! (Note: at least one person on bazel-discuss already implied that there is not... :cry:)
</blockquote></details>

Not that I can think of at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjESPA1Tdxjo_VnZ3ut:b-95ugoa) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It is consistent with the other Python packages that we use (and I already mirrored the PyPI version).
</blockquote></details>

https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz → 404?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjEZz5NgKeMnwnTsWdi:b-al8mqa) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

https://pypi.python.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz → 404?
</blockquote></details>

https://files.pythonhosted.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz, I guess. Read https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package for why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjFppAUC63iJx1n3DEh:bns4vk6) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
> ```Python
> 
> github_archive(
>     name = "pycps",
> ```

`pycps` is GPL.  That is unacceptable for a dependency of Drake's core software.

We could probably live with LGPL 2+ or 3+, but really file-only-viral (MPL2) or non-viral would be best if possible.

It would also be a bonus if the tool's documentation explicitly disclaimed copyright on its outputs.

---

*[tools/pycps.BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFt6Ne0R6sRzdBbPx3:-KjFt6NfC5orf8mDo2vc:b-6wzr10) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/tools/pycps.BUILD#L6)):*
> ```
>   outs = ["cps2cmake.py"],
>   cmd = "cp \"$<\" \"$(@)\"",
> )
> ```

FYI Does this work instead?
```python
alias(
    name = "cps2cmake.py",
    actual = ":cps2cmake",
)
```

(I assume you already tried `cps2cmake` bare as the `py_binary`'s `srcs` and `main` and it failed because of the missing extension.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 298 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEEwlZ9ef0JHm_OQf-:-KjJCOxfExIsWkJLFdn6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/WORKSPACE#L298)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

https://files.pythonhosted.org/packages/source/s/semantic_version/semantic_version-2.6.0.tar.gz, I guess. Read https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package for why.
</blockquote></details>

Done.

---

*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjJCQqxxlP6kQgCkGlp:bxeuzps) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`pycps` is GPL.  That is unacceptable for a dependency of Drake's core software.

We could probably live with LGPL 2+ or 3+, but really file-only-viral (MPL2) or non-viral would be best if possible.

It would also be a bonus if the tool's documentation explicitly disclaimed copyright on its outputs.
</blockquote></details>

This shouldn't be a problem, any more than building Drake with GCC is a problem. We are not incorporating any code from PyCPS, and it is widely understood that the output of a GPL tool is not itself subject to GPL. (Also, for the record, the author hereby says as much.)

I'm not aware of any precedent for such disclaimers (e.g. this wasn't a problem when drake-config.cmake was generated by CMake). Do you have any recommendations?

(All that said, it does make sense on further reflection for PyCPS to be LGPL, but I don't think that should necessarily block this PR.)

---

*[tools/semantic_version.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEFzFXffOttsHVkGt5:-KjJCMdgphW7bB_Ku8rZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The `strip_prefix` in the `WORKSPACE` file should make this redundant.
</blockquote></details>

Done.

---

*[tools/semantic_version.BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjEG5BkrY3-BnvjwbNF:-KjJCLXywS_eMUhv6YRr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b83b6c93455d6e85c04307a19c1e5d45ae1a0e77/tools/semantic_version.BUILD#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

That level will be removed. If it were not, you would add an `imports = ["semantic_version-2.6.0"]` line instead in any case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjJIWSf47puEoLPrm3E:b-tz1gay) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
I added this to the README:

> It is generally recognized that the outputs of a software tool are not derivative works of that tool unless they contain substantial and creative parts of the tool's code. The author(s) explicitly affirm that the outputs of the PyCPS tools are not derivative works of PyCPS, and are accordingly not subject to the terms of PyCPS's license. Such outputs may, however, be derivative works of those CPS files which PyCPS processes as inputs.

---

*[tools/pycps.BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFt6Ne0R6sRzdBbPx3:-KjJIpVc11qlgClZAUIy:bw7dg0) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/tools/pycps.BUILD#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Does this work instead?
```python
alias(
    name = "cps2cmake.py",
    actual = ":cps2cmake",
)
```

(I assume you already tried `cps2cmake` bare as the `py_binary`'s `srcs` and `main` and it failed because of the missing extension.)
</blockquote></details>

Nope:

    ERROR: .../external/pycps/BUILD.bazel:15:10:
      in main attribute of py_binary rule @pycps//:cps2cmake_executable:
      file '@pycps//:cps2cmake' (aliased through '@pycps//:cps2cmake.py') is misplaced here (expected .py).

`py_binary` is ~evil~ fussy :frowning:, and alas, sees right through the attempt to pacify it.

In *my* opinion, the "right" thing to do here is to somehow just tell Bazel "hey, this source file is a Python script, it has some (run-time) dependencies but you don't need to do anything special with it". Alas, I don't know how to do that, and @laszlocsomor says this ugly hoop-jumping is the "right" thing to do. (FWIW, I'm more bothered that I can't use the script's real name as the Bazel target name :cry:.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Please update #4045 if/when this merges.

**Comment by jwnimmer-tri** [comment]
:lgtm: 

---

Reviewed 2 of 7 files at r3, 4 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjJxkbqViEMEmcPJGvk:b-ao7dns) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I added this to the README:

> It is generally recognized that the outputs of a software tool are not derivative works of that tool unless they contain substantial and creative parts of the tool's code. The author(s) explicitly affirm that the outputs of the PyCPS tools are not derivative works of PyCPS, and are accordingly not subject to the terms of PyCPS's license. Such outputs may, however, be derivative works of those CPS files which PyCPS processes as inputs.
</blockquote></details>

OK I will take a note to think about this further, and allow it for now.  I would be slightly happier if `cps2cmake_executable` just listed all sources, and there we no `py_library` that a Drake developer could accidentally link to.  (Or maybe just add a comment in the `py_library` about its private visibility being really important.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-:-KjJy3jlEi7bxIDECfvo:bg7igkv)*

**Comment by mwoehlke-kitware** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjK-Uu2BWMps8GTPrzC:b-q3ea1h) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
> I would be slightly happier if `cps2cmake_executable` just listed all sources [...]

I started to do that, but it just rubs me wrong :smile:. Conceptually, PyCPS consists of a) the `cps` Python module, and b) some CLI tools that make use of the same (currently just `cmake2cps`, but others are planned, eventually). Ergo...

> Or maybe just add a comment in the py_library about its private visibility being really important.

...I went with this. (It's private anyway, with no expectation that it would ever be used at other than build time in the worst case, but if it helps you feel better, I'm more than happy adding a comment *why* we want it private.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 2 of 7 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-:-KjK3uyyadAeFqYJpK4J:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-:-KjK6r69zQAxh0DVgrKz:b-s794vx)*

**Comment by stonier** [comment]
*[WORKSPACE, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6014#-KjFppAUC63iJx1n3DEg:-KjK9anpnWlyiB5Ya7NO:b-btxo4j) ([raw file](https://github.com/robotlocomotion/drake/blob/2997a8f2dd96d79cf583652a55c91902c5e26091/WORKSPACE#L302)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> I would be slightly happier if `cps2cmake_executable` just listed all sources [...]

I started to do that, but it just rubs me wrong :smile:. Conceptually, PyCPS consists of a) the `cps` Python module, and b) some CLI tools that make use of the same (currently just `cmake2cps`, but others are planned, eventually). Ergo...

> Or maybe just add a comment in the py_library about its private visibility being really important.

...I went with this. (It's private anyway, with no expectation that it would ever be used at other than build time in the worst case, but if it helps you feel better, I'm more than happy adding a comment *why* we want it private.)
</blockquote></details>

The GPL FAQ explicitly states that a GPL program cannot affect the output of a program. Basically what goes in, must come out. Just to be explicit:

https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL

So it really shouldn't be a problem here given that it's use is to generate drake-config.cmake from the drake repository files.

Nonetheless, nice to see it go LGPL and I like the private visibility (learn something new about bazel every day :)).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6014)*

**Comment by jwnimmer-tri** [comment]
Yup.  This is good.  In my earlier review, I'd only considered the "Everything in WORKSPACE under platform review must pass a licensing cross-check", but in this particular context the rules are different and I hadn't considered the tool output exception.

**Comment by laszlocsomor** [comment]
@mwoehlke-kitware : re:

> In my opinion, the "right" thing to do here is to somehow just tell Bazel "hey, this source file is a Python script, it has some (run-time) dependencies but you don't need to do anything special with it". Alas, I don't know how to do that, and @laszlocsomor says this ugly hoop-jumping is the "right" thing to do.

After reading this I thought more about the problem and realized, if all you want is to set the runtime dependencies of the python script but otherwise don't care about anything the py_* rules would add (compilation, type checking, whatever they might do, honestly I don't know for sure), then you can just create a `sh_binary` instead, it's less picky than the `py_binary`.

Here, "foo" is the python script, "shbin" can be built, "pybin" cannot:

```
sh_binary(
    name = "shbin",
    srcs = ["foo"],
    data = [...],
)

py_binary(
    name = "pybin",
    srcs = ["foo"],
    data = [...],
)
```

**Comment by mwoehlke-kitware** [comment]
@laszlocsomor, thanks for looking again. Alas, while I indeed don't care about compiling or whatnot, I *do* care about being able to bring in `py_library`s, as even best case, the script depends on an external Python module (namely semantic_version, as can be seen in the patch). It seems `sh_binary` doesn't like Python libraries as `deps`.

**Comment by jamiesnape** [comment]
> It seems sh_binary doesn't like Python libraries as `deps`.

You would specify it as `data` in this case.

**Comment by mwoehlke-kitware** [comment]
> You would have to specify it as `data` in this case.

That may or may not be following transitive dependencies, and in any case, it doesn't seem to work with external `py_library` dependencies; even with `data = ["@semantic_version//:semantic_version"]`, it fails to `import semantic_version`. (Provided I remember to `dnf remove python2-semantic_version` for testing purposes :wink:.)

**Pull request merged**
