### PR TITLE
Added RigidBodyDepthSensor::is_horizontal_scanner() and is_vertical_scanner()

### PR DESCRIPTION
**Pull request by liangfok**
These will be needed by an upcoming ROS system that publishes LIDAR data.

This PR is a subset of https://github.com/RobotLocomotion/drake/pull/2253, which I'm trying to break into smaller pieces.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2389) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by liangfok** [comment]
Perhaps:
+@jwnimmer-tri for feature review
+@david-german-tri for platform review
?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added RigidBodyDepthSensor::is\_horizontal\_scanner\(\) and is\_vertical\_scanner\(\)
> 
> These will be needed by an upcoming ROS system that publishes LIDAR data.
> 
> 
> 
> This PR is a subset of https://github.com/RobotLocomotion/drake/pull/2253, which I'm trying to break into smaller pieces.
> 
> 
> </details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI-aoTghRCT_vxesdVJ:2029780370)*

**Comment by liangfok** [comment]
Per F2F, -@jwnimmer-tri for feature review. (@david-german-tri will do both.)

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Perhaps:
> +@jwnimmer-tri for feature review
> +@david-german-tri for platform review
> ?</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI-bNXELqJSRvnysFBY:734325039)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Per F2F, -@jwnimmer-tri for feature review. (@david-german-tri will do both.)</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI-baRUiU93MxP0XPBx:1417088721)*

**Comment by jwnimmer-tri** [comment]
@liangfok The jenkins failure is mac, and seems like #2391.  I think if you merge up to head of master, this PR will likely pass and be ready to merge back.

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodySystem.h, line 498 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI89rUOdZW5wEY7bwmf:-KI89rUOdZW5wEY7bwmg:-571881620) ([raw file](https://github.com/robotlocomotion/drake/blob/27237b7540342ccc9da1e1e843940ce27969ad11/drake/systems/plants/RigidBodySystem.h#L498)):*
> ```objc
> 
>   /**
>    * Returns true if this sensor scans horizontally.
> ```

Use back quotes to describe the return like so: `true`. 

---

*[drake/systems/plants/RigidBodySystem.h, line 503 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI8A75mPH-Ygp2yarTe:-KI8A75mPH-Ygp2yarTf:-571881620) ([raw file](https://github.com/robotlocomotion/drake/blob/27237b7540342ccc9da1e1e843940ce27969ad11/drake/systems/plants/RigidBodySystem.h#L503)):*
> ```objc
> 
>   /**
>    * Returns true if this sensor scans vertically.
> ```

Use back quotes to describe the return like so: `true`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @liangfok The jenkins failure is mac, and seems like #2391.  I think if you merge up to head of master, this PR will likely pass and be ready to merge back.
</details>


---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.h, line 498 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI89rUOdZW5wEY7bwmf:-KI9EgVP9A1W11u1aalw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/27237b7540342ccc9da1e1e843940ce27969ad11/drake/systems/plants/RigidBodySystem.h#L498)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Use back quotes to describe the return like so: `true`. 
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.h, line 503 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI8A75mPH-Ygp2yarTe:-KI9EhpCXgzTJGbIcZoM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/27237b7540342ccc9da1e1e843940ce27969ad11/drake/systems/plants/RigidBodySystem.h#L503)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Use back quotes to describe the return like so: `true`. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI9EzWrJB-tQ8tci8Jn:701515998)*

**Comment by liangfok** [comment]
This PR passed [CI Build 1577](https://drake-jenkins.csail.mit.edu/job/experimental/1577/) and is thus ready for final review / merge.

+@jwnimmer-tri 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I addressed all reviewer comments. PTAL. Thanks!
</details>


---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI9m2VBOoeNv-kgSa1o:-2051074412)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/test/lidarTest.cpp, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI9oM15psT7CHqU53Bm:-KI9oM15psT7CHqU53Bn:206676692) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb025b9d3888cf43dfacf3083cf34ef7a4987f9/drake/systems/plants/test/lidarTest.cpp#L38)):*
> ```cpp
> 
>   if (!lidar_sensor->is_horizontal_scanner())
>     throw std::runtime_error(
> ```

Multi-line body requires curly braces.

---

*[drake/systems/plants/test/lidarTest.cpp, line 43 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI9oPW9GrIFaIxxNgrx:-KI9oPW9GrIFaIxxNgry:206676692) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb025b9d3888cf43dfacf3083cf34ef7a4987f9/drake/systems/plants/test/lidarTest.cpp#L43)):*
> ```cpp
>   if (lidar_sensor->is_vertical_scanner())
>     throw std::runtime_error(
>       "ERROR: LIDAR scanner says it is vertical but is not!");
> ```

Multi-line body requires curly braces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/test/lidarTest.cpp, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI9oM15psT7CHqU53Bm:-KI9p3K9rM581oIeJFjB:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb025b9d3888cf43dfacf3083cf34ef7a4987f9/drake/systems/plants/test/lidarTest.cpp#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Multi-line body requires curly braces.
</details>
Fixed. Thanks.

---

*[drake/systems/plants/test/lidarTest.cpp, line 43 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-KI9oPW9GrIFaIxxNgrx:-KI9p4Tb6D_eoC_eXS5u:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb025b9d3888cf43dfacf3083cf34ef7a4987f9/drake/systems/plants/test/lidarTest.cpp#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Multi-line body requires curly braces.
</details>
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This PR passed [CI Build 1577](https://drake-jenkins.csail.mit.edu/job/experimental/1577/) and is thus ready for final review / merge.
> 
> +@jwnimmer-tri 
</details>


---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI9pKD9R1_nDaPqp4gH:701515998)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I addressed all reviewer comments. PTAL. Thanks!
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI9pZLjSZqeEWjKCn_o:1417088721)*

**Comment by jwnimmer-tri** [comment]
Once cpplint and a single compiler pass, we can merge.

**Comment by liangfok** [comment]
`gcc+linux` and `cpplint` passed :smiley: 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Once cpplint and a single compiler pass, we can merge.
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2389#-:-KI9vFbhvaNQIaluuVhG:-2059213467)*

**Comment by jwnimmer-tri** [comment]
Using override-merge to get around 2 unresolved discussions; the last, lagging builder; and out-of-date-with-master.

**Pull request merged**
