### PR TITLE
Add crossroad road geometry

### PR DESCRIPTION
**Pull request by shensquared**
Adding an X-shaped multilane crossroad road geometry. Here's a [Demo](https://youtu.be/h6iarVjYZ3Q).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5434)

### CODE REVIEW

**Comment by shensquared** [comment]
@drake-jenkins-bot 
linux-clang-experimental-debug please

**Comment by shensquared** [comment]
@drake-jenkins-bot 
linux-gcc-experimental-matlab please

**Comment by shensquared** [comment]
+@liangfok for feature review since it's very similar to your `dragway` implementation, thanks.

**Comment by liangfok** [comment]
+@liangfok 

I'll review this soon! Sorry for the latency.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-KejdaUmm0gs9_zrZerS:bi2gp2m)*

**Comment by liangfok** [comment]
Before I get too far, I'd like to +@jwnimmer-tri for car review to see whether this code can / should reside on `master`, a `dev` directory, or a separate fork.

---

Reviewed 2 of 23 files at r1.
Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/BUILD, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-KekFwoCp4e56dGPz5tV:-KekFwoCp4e56dGPz5tW:b-fz4o4h) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b0a4c74490f367d1698691dce2c6705ac48fbd/drake/automotive/BUILD#L234)):*
> ```Python
>         ":automotive_simulator",
>         "//drake/automotive/maliput/dragway",
>         "//drake/automotive/maliput/crossroad",
> ```

BTW, consider alpha sorting.

---

*[drake/automotive/BUILD, line 263 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-KekFw3gAVecY_wO2wwH:-KekFw3gAVecY_wO2wwI:b-fz4o4h) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b0a4c74490f367d1698691dce2c6705ac48fbd/drake/automotive/BUILD#L263)):*
> ```Python
>         ":infinite_circuit_road",
>         "//drake/automotive/maliput/dragway",
>         "//drake/automotive/maliput/crossroad",
> ```

BTW, consider alpha sorting.

---

*[drake/automotive/CMakeLists.txt, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-KekFtCiQvOj4hWmq31v:-KekFtCiQvOj4hWmq31w:b-fz4o4h) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b0a4c74490f367d1698691dce2c6705ac48fbd/drake/automotive/CMakeLists.txt#L119)):*
> ```CMake
>       drakeLCMTypes
>       drakeMaliputDragway
>       drakeMaliputCrossroad)
> ```

BTW, consider alpha sorting.

---

*[drake/automotive/maliput/CMakeLists.txt, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-KekFr4PPxmqaKORgaOx:-KekEb7DSqwddAkASjxO:b-m0houe) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b0a4c74490f367d1698691dce2c6705ac48fbd/drake/automotive/maliput/CMakeLists.txt#L3)):*
> ```CMake
> add_subdirectory(api)
> add_subdirectory(dragway)
> add_subdirectory(crossroad)
> ```

BTW, alpha sort.

---

*[drake/automotive/maliput/crossroad/branch_point.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-KekG52fJY3d8YSw82vs:-KekG52fJY3d8YSw82vt:b-unlrb5) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b0a4c74490f367d1698691dce2c6705ac48fbd/drake/automotive/maliput/crossroad/branch_point.h#L20)):*
> ```objc
> 
> /// Crossroad's implementation of api::LaneEndSet. Since a Crossroad::Lane
> /// connects
> ```

BTW, odd newline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-KekG9EZGgy85sp59c5O:b-4if6wy)*

**Comment by jwnimmer-tri** [comment]
I'm trying to tease out the intent / design of this.  It seems to me like it's essentially just two multi-lane dragway geometries, but with one offset / rotated from the other so that they overlap in a sort-of intersection, and that the crossing lanes don't actually connect to the perpendicular ones (e.g., turns); they just drive over each other.  So let's take a step back...

If we want literally just this crossroad geometry as PR'd now (multiple lanes, crossroads, but naively overlapped in the center) then a more appropriate approach would be to modify dragway to have an origin position and heading, so that we could just instantiate two of them in this crossroad pattern.  Adding the ~200 lines into dragway to make that possible is superior to forking dragway into the 1400 new (copied) lines of code in this PR.

Alternatively, if we wanted a four-way intersection with only single-lane segments with nice round corners that connect to each other, or continue straight, or etc, then monolane can already do that today, and should be used instead.  (For example, a typically 4-way stop can be done this way, with 8 segments (8 lanes) coming in, and then having turns to the other directions.)

Alternatively, even if we _do_ want multiple lanes per direction of travel, monolane can still do that, but you just don't get the "which lane is on my left" query, because each lane is its own segment.  That support will be coming up in future PRs.

So I guess I'm not sure yet what capability this PR intends to add, beyond what's already in Drake.  If we could roll back to "what are the requirements", I can help guide what an appropriate design would be for code that ends up within Drake itself.

---

Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-KekXClGae0Wh1Li9NU_:bsv3jd6)*

**Comment by shensquared** [comment]
Thanks for the comments, @jwnimmer-tri . Ultimately, I'd like to add a crossroad that has multiple lanes, nice corners for turns, and support idm-planners. I know village-demo using monolane already does all of these today. I didn't choose monolane though for two reasons. First is the lack of 'which's my left lane' info, I didn't know it's coming soon and I'm glad to hear that. Second and more important reason is that I needed the capability of passing the number of lanes at each run as opposed to having it hard-coded in the monolane translator. (or did I understand the monolane wrong?) That leaves dragway as the perfect starting point. 
 
I chatted with @liangfok about the design of this relative to dragway, whether as a superclass of dragway or parallel to it and we chose the later because dragway is hard-coded as single segment. I have to change this single segment assumption, not just the orientation or placement, to build a crossroad. But that feels very unnatural - no dragway has/needs multiple segments, and it doesn't help I'm planning on adding corners too. That's why I left dragway untouched and had so many code for so trivial an extension for now.  

I opened the PR only because Drake doesn't do exactly that. I also do realize the what I intended to add ultimately may be a niche use case and does not reflect real world scenario well, so maybe it doens't belong in Drake master, and I'll happily close the PR too if that's the case. 

---

Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-Kel4D3m1x5cWQDJlbot:bojgsjl)*

**Comment by jwnimmer-tri** [comment]
> Second and more important reason is that I needed the capability of passing the number of lanes at each run as opposed to having it hard-coded in the monolane translator. (or did I understand the monolane wrong?)

Yes and no.  With a `yaml` file as the input, yes the Geometry is fully determined (no variability or parameterization).  But by using the C++ APIs that the yaml loader calls, we can create any monolane road network that we can think of, on the fly.

> I chatted with @liangfok about the design of this relative to dragway ...

Chatting without looping me in is no problem, but it has the risk of investing in preparing PRs that need substantial redesign work.  I read all github issues and slack channels, and I'm happy to weigh in on discussions there, especially when design questions come up.

> I have to change this single segment assumption, not just the orientation or placement, to build a crossroad.

I don't think that's true.  Assuming we added Dragway origin and bearing parameters to its constructor, we could instantiate two Dragways (and also two RoadGeometry objects), and they would be more or less the same as this.  (Or did you need them to be the same RoadGeometry?  Do your sensors operate in Cartesian space, or by using Lane IDs somehow?)  The two Dragways would be a bit of a hack, but would probably be okay while we build out more other capability.

> ... ultimately may be a niche use case and does not reflect real world scenario well, so maybe it doesn't belong in Drake master, and I'll happily close the PR too if that's the case.

 I think the concept is appropriate to put into Drake (not too niche), and I appreciate the effort.  However, I'm not sure its worth a 1000+ line PR with code that has lots of duplication of existing code.

If there was some way to reuse / refactor more of what's there already so that the crossroad code were smaller, that could be okay.  (I haven't looked to see whether or how this is possible.)  But we could chat about that if you were interested.  Or maybe we should just focus on #4934 and related improvements, or tools like ekumenlabs/terminus#200, so that we can easily build _any_ road network that we want.

I'm happy to hear more thoughts.

---

Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-KeudoqLdltgcXiYHIg_:b-bmmwvw)*

**Comment by liangfok** [comment]
@shensquared, is your objective to conduct complex planar intersection research? By that I mean the intersection is flat but may involve numerous multi-lane streets all coming together at various angular and translational offsets.

Thinking about this some more, I think an alternative design is to generalize dragway by modifying it to support multiple segments in which each segment has a different position and orientation within the road's plane. Bezier curves could then be used for the lanes in the segments that reside within the intersection itself. Of course, the pros & cons of this design must be compared against all of the other designs.

---

Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-Kf1ZSalwg1R27lA3HH3:b9jhg6o)*

**Comment by shensquared** [comment]
Thanks for the clarification, @jwnimmer-tri. I now realize there are multiple more elegant ways to achieve what this PR does, and so I'll close it and try a do-over. I'm thinking of modifying `dragway` first? exactly as what @liangfok was suggesting, because I'm more familiar with it, and learn the monolane `yaml` approach on the side?

As for future development, my own motivation /use case is this: I want to verify the safety of a large number of cars, but directly verifying them head-on is computationally very costly because the state is very high dimensional. So instead, I'd like to divide the cars into groups, and verify each individual group and then compose the certificates in some way to offer the same safety guarantee.

So it doesn't really matter what's exactly the road geometry, it's just essential to be able to generate lots of duplicates of the basis geometry on-line to visualize or present my algorithm. Flat and straight lane is an easy start, but I'm eager to learn more and hopefully also help with any development along that direction.  Maybe it's easier to talk in person to align the interest? I'm on slack too, drop me a msg when you're free to talk? 

---

Review status: 2 of 23 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5434#-:-KfDy6zkZEV3TNyOS6Uq:bchnx2k)*

**Pull request closed without merging**
