### PR TITLE
Upgrade documentation and add quality_factor to method that projects …

### PR DESCRIPTION
**Pull request by mitiguy**
…a rotation matrix to an orthonormal matrix

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7977)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@ggould-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-:-L4iGbM4VRfG7PGEaI99:bguppra)*

**Comment by ggould-tri** [comment]
:lgtm:; comment issues below.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 432 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-L4kXqLkOARoQPYSzLjB:-L4kXqLlAM_xxna9fLg1:b-suvu27) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L432)):*
> ```objc
>   // as large as 1.25 may result.  `quality_factor` = -1 means M relates two
>   // perfectly orthonormal bases, but one is right-handed whereas the other is
>   // left-handed (M is a "reflection").  ``quality_factor` = -0.8 means M
> ```

FYI the doubled backticks before `quality_factor` here will probably prevent correct doxygen rendering.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 436 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-L4kXcKUcNtV36raXN13:-L4kXcKVMTKYGoQYNwFV:b-emvedx) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L436)):*
> ```objc
>   // a unit vector, a vector of magnitude as small as 0.8 may result.
>   // @returns orthonormal matrix R that is close to M (note det(R) may be -1).
>   // Projects an  3x3 matrix @p M onto O(3), defined as
> ```

Did you delete a word here?  'an' seems like a typo, plus an extra space, plus the sentence trails off after 'as'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-:-L4kYX1OFyXaZ1cxNv0s:b-a4sfkk)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-L4lOb_h8Jxkjxw4F2i7:-L4lOb_h8Jxkjxw4F2i8:b-deikoc) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L332)):*
> ```objc
> 
>   /// Creates an orthonormal matrix R from a 3x3 matrix M by minimizing
>   /// `‖R - M‖²`  subject to  `R * Rᵀ = I`, where I is the 3x3 identity matrix.
> ```

I think we should point out what norm is used here. We can use both the Frobenius norm or the matrix l₂ norm. And also below

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 444 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-L4lPBnnplGyS5EZkm_p:-L4lPBnnplGyS5EZkm_q:b-un6wsg) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L444)):*
> ```objc
>     DRAKE_DEMAND(M.rows() == 3 && M.cols() == 3);
>     const auto svd = M.jacobiSvd(Eigen::ComputeFullU | Eigen::ComputeFullV);
>     // Singular values are always non-negative and sorted in decreasing order.
> ```

Starting from here, until the return argument, can all be put inside the if(quality_factor) branch. Namely
```
if (quality_factor) {
   const auto singular_values = svd.singularValues();
   const double s_max = singular_values(0);  // maximum singular value.
   const double s_min = singular_values(2);  // minimum singular value.
   const double s_f = (s_max != 0.0 && s_min < 1.0/s_max) ? s_min : s_max;
   const double det = M.determinant();
   const double sign_det = (det > 0.0) ? 1 : ((det < 0.0) ? -1 : det);
   *quality_factor = s_f * sign_det;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977)*

**Comment by mitiguy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 332 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977#-L4lOb_h8Jxkjxw4F2i7:-L4rbBI6zf94XN682PGU:b-gretxs) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L332)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think we should point out what norm is used here. We can use both the Frobenius norm or the matrix l₂ norm. And also below
</blockquote></details>

Done.  Feel free to suggest alternate language.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 436 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977#-L4kXcKUcNtV36raXN13:-L4rQdrvxBOz6ke3adh4:bxcqqsv) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L436)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Did you delete a word here?  'an' seems like a typo, plus an extra space, plus the sentence trails off after 'as'.
</blockquote></details>

Done.  Fixed documentation.  Good catch.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 444 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977#-L4lPBnnplGyS5EZkm_p:-L4rP__YKDk7xmfJHXIL:bw9w2cy) ([raw file](https://github.com/robotlocomotion/drake/blob/108bff2a6d28583297474e03ecfcd51c2f0b1fec/multibody/multibody_tree/math/rotation_matrix.h#L444)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Starting from here, until the return argument, can all be put inside the if(quality_factor) branch. Namely
```
if (quality_factor) {
   const auto singular_values = svd.singularValues();
   const double s_max = singular_values(0);  // maximum singular value.
   const double s_min = singular_values(2);  // minimum singular value.
   const double s_f = (s_max != 0.0 && s_min < 1.0/s_max) ? s_min : s_max;
   const double det = M.determinant();
   const double sign_det = (det > 0.0) ? 1 : ((det < 0.0) ? -1 : det);
   *quality_factor = s_f * sign_det;
}
```
</blockquote></details>

Done.  Thanks Hongkai.  Much better efficiency and clarity.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977)*

**Comment by mitiguy** [comment]
PTAL

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977#-:-L4sAHnt55tLFZ1QxO6-:bb71pro)*

**Comment by mitiguy** [comment]
PTAL - more documentation changes.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7977#-:-L4sVdG51IwmPRuaByOC:b9px871)*

**Comment by mitiguy** [comment]
Hongkai - please let me know if you like the new language.  Thanks  Paul.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-:-L4whEn75RZqAWotPnUb:b-3bu4bm)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977#-:-L580U3fNe2Q-Wv9vuFO:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7977)*

**Pull request merged**
