### PR TITLE
Add and use more DeclareContinuousState overloads

### LINKED ISSUE #5466: LeafSystem model-based continuous state declaration should use cref, not unique_ptr
In #5431, `DeclareVectorOutputPort` takes a `const BasicVector<T>&` as the model.  But in the pre-existing `DeclareContinuousState` that takes a model, the input is a `unique_ptr`.  I think its easier for callers to provide a value instead of a unique, so we should change continuous state to use that phrasing.

We should also probably add a simple overload where all state is assumed to be `z`.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #5466.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5494)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-:-KfEHOAd7f7x3WCNkp8Y:bltds52)*

**Comment by jwnimmer-tri** [comment]
:car: approved

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-:-KfEIJo0EQs_XDngzxGg:b-wrjbb8)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 471 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-KfEYKujPIyUr_lkgllM:-KfEYKujPIyUr_lkgllN:b6oes8m) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a7c7c7f3906a588e1c7aa182c50589cfc64660/drake/systems/framework/leaf_system.h#L471)):*
> ```objc
> 
>   /// Declares that this System should reserve continuous state with
>   /// @p model_vector.size() miscellaneous state variables, stored in the a
> ```

BTW, odd grammar: "the  a".

---

*[drake/systems/framework/leaf_system.h, line 482 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-KfEYWE76gVBNbxZoMRj:-KfEYWE76gVBNbxZoMRk:b6oes8m) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a7c7c7f3906a588e1c7aa182c50589cfc64660/drake/systems/framework/leaf_system.h#L482)):*
> ```objc
>   /// Declares that this System should reserve continuous state with @p num_q
>   /// generalized positions, @p num_v generalized velocities, and @p num_z
>   /// miscellaneous state variables, stored in the a vector Cloned from
> ```

BTW, odd grammar: "the  a".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-:-KfEZkiiTHVvFoYD3O3p:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-:-KfGfZalWtIyahPM_REm:bz1t39v)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5494#-:-KfHSSaghu-ycu2WHcl6:bnfp4nl)*

**Pull request merged**
