### PR TITLE
deprecate tkinter

### PR DESCRIPTION
**Pull request by bardkw**
Towards #14702.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
Can you please add the relevant issue number in the description so that the PR will be linked? 

> Reviewed 12 of 14 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-MwgKvyH5QdGGY1FYhk9:bs2zh68)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @bardkw and @BetsyMcPhail)

___
*[examples/manipulation_station/joint_teleop.py, line 93 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgYYLb8cRh-OCN_pu4:-MwgYYLb8cRh-OCN_pu5:b-4qtwdv) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/examples/manipulation_station/joint_teleop.py#L93)):*
> ```Python
>             pyplot_visualizer = ConnectPlanarSceneGraphVisualizer(
>                 builder, station.get_scene_graph(), geometry_query_port)
>     with catch_drake_warnings(expected_count=1):
> ```

As this is an example, not a test, using a testing utility here shouldn't be necessary.
___
*[manipulation/util/BUILD.bazel, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-Mwg_G6y1Bo6RZMWBnOF:-Mwg_G6z7f1ARheHIlcT:bj9719m) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/manipulation/util/BUILD.bazel#L52)):*
> ```Starlark
>     data = [
>         ":geometry_inspector",
>         "//bindings/pydrake",
> ```

These lines may be leftover from a previous revision?
___
*[bindings/pydrake/manipulation/simple_ui.py, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgQnd64QXhJeZn_5JB:-MwgQnd64QXhJeZn_5JC:b-2u911o) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/manipulation/simple_ui.py#L24)):*
> ```Python
> @deprecated_callable("pydrake.manipulation.JointSliders has been deprecated in"
>                      " favor of pydrake.multibody.meshcat.JointSliders",
>                      date="2022-02-10")
> ```

I couldn't find any documentation on this but the deprecation date is typically 3 months out, rounded to the beginning of the next month. So in this case, 2022-06-01
___
*[bindings/pydrake/manipulation/simple_ui.py, line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgS6naDcTbkESmm8ZR:-MwgS6naDcTbkESmm8ZS:by0183x) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/manipulation/simple_ui.py#L163)):*
> ```Python
> 
> @deprecated_callable("pydrake.manipulation.simple_ui.SchunkWsgButtons has been"
>                      " deprecated", date="2022-02-10")
> ```

Date should be changed here too
___
*[bindings/pydrake/systems/system_sliders.py, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgSIDe7Ee5jYoayYGD:-MwgSIDe7Ee5jYoayYGE:bdec0lb) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/systems/system_sliders.py#L13)):*
> ```Python
> 
> @deprecated_callable("pydrake.systems.system_sliders.SystemSliders has been"
>                      " deprecated", date="2022-02-10")
> ```

And one more date to update

**Review by bardkw — COMMENTED** [review]
understood

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-MwhFrPSD7n0DR43mJO6:biay1rk)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

___
*[examples/manipulation_station/joint_teleop.py, line 93 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgYYLb8cRh-OCN_pu4:-MwhFk7n5dsQhTYwieHU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/examples/manipulation_station/joint_teleop.py#L93)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

As this is an example, not a test, using a testing utility here shouldn't be necessary.
</blockquote></details>

Done.
___
*[bindings/pydrake/manipulation/simple_ui.py, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgQnd64QXhJeZn_5JB:-Mwh88qv5qtza16VQQyj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/manipulation/simple_ui.py#L24)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I couldn't find any documentation on this but the deprecation date is typically 3 months out, rounded to the beginning of the next month. So in this case, 2022-06-01
</blockquote></details>

Done.
___
*[bindings/pydrake/manipulation/simple_ui.py, line 163 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgS6naDcTbkESmm8ZR:-Mwh8BNK-mRLiqj0Xfuy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/manipulation/simple_ui.py#L163)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Date should be changed here too
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/system_sliders.py, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwgSIDe7Ee5jYoayYGD:-Mwh8Dp20_N-9tafMwqy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/bindings/pydrake/systems/system_sliders.py#L13)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

And one more date to update
</blockquote></details>

Done.
___
*[manipulation/util/BUILD.bazel, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16656#-Mwg_G6y1Bo6RZMWBnOF:-Mwh838S5e7yAgZihNmE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/765194f2afdffaa84c0164632ffaf3f219ccf715/manipulation/util/BUILD.bazel#L52)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

These lines may be leftover from a previous revision?
</blockquote></details>

Done.

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @bardkw)

**Review by bardkw — COMMENTED** [review]
+@jwnimmer-tri

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-MwkuWGL2ENDwTCrxK8l:b-3kogyb)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review +(release notes: yes).

> Can you please add the relevant issue number in the description so that the PR will be linked?

Done.

> Reviewed 8 of 14 files at r1, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-Mwlh3WZBpAcS1cnqG-2:b-vhc5or)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @bardkw)

___
*[examples/manipulation_station/joint_teleop.py, line 92 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwlgseV0IwXJP55H6XN:-MwlgseV0IwXJP55H6XO:blf5891) ([raw file](https://github.com/robotlocomotion/drake/blob/f1730c3e947ffa9e1bc95d3f75e386636f7cb38c/examples/manipulation_station/joint_teleop.py#L92)):*
> ```Python
>             pyplot_visualizer = ConnectPlanarSceneGraphVisualizer(
>                 builder, station.get_scene_graph(), geometry_query_port)
> ```

nit It would be better to leave this file completely alone (i.e., not delete this blank line), if we don't have anything meaningful to change within it.
___
*[bindings/pydrake/manipulation/simple_ui.py, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16656#-MwlhMel8PVBZ6wGU-1w:-MwlhMel8PVBZ6wGU-1x:b-54pi2l) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b68588c896afe04ac35644d50a2dbc84100a2f/bindings/pydrake/manipulation/simple_ui.py#L22)):*
> ```Python
> 
> 
> @deprecated_callable("pydrake.manipulation.JointSliders has been deprecated in"
> ```

nit The precise classname is `pydrake.manipulation.simple_ui.JointSliders`.



_Suggestion:_
```Python
pydrake.manipulation.simple_ui.JointSliders
```

**Review by jwnimmer-tri — COMMENTED** [review]
Oops, I should have done +(release notes: newly deprecated) not -(release notes: yes).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-MwlipkeEtnlw9MQ-R7S:b-zcjuss)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @bardkw)

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-Mx-nDkXDzJ_ZWwCKvet:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 14 files at r1, 1 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16656#-:-Mx-wf3o3KPX2PbysoHG:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @bardkw)

___
*[bindings/pydrake/manipulation/simple_ui.py, line 164 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16656#-Mx-wIAw0SzzhadcY98G:-Mx-wIAw0SzzhadcY98H:b-5huoln) ([raw file](https://github.com/robotlocomotion/drake/blob/659138b2019e0f1a908121d181f8cf6df620c5fb/bindings/pydrake/manipulation/simple_ui.py#L164)):*
> ```Python
> 
> @deprecated_callable("pydrake.manipulation.simple_ui.SchunkWsgButtons has been"
>                      " deprecated", date="2022-06-01")
> ```

minor:  Does this mean that it's deprecated without replacement, or is there a new meshcat-based affordance to mention?
___
*[bindings/pydrake/systems/system_sliders.py, line 13 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16656#-Mx-waDl0yJR0COArC4G:-Mx-waDl0yJR0COArC4H:b-5huoln) ([raw file](https://github.com/robotlocomotion/drake/blob/659138b2019e0f1a908121d181f8cf6df620c5fb/bindings/pydrake/systems/system_sliders.py#L13)):*
> ```Python
> 
> @deprecated_callable("pydrake.systems.system_sliders.SystemSliders has been"
>                      " deprecated", date="2022-06-01")
> ```

minor:  Does this mean that it's deprecated without replacement, or is there a new meshcat-based affordance to mention?

**Pull request merged**
