### PR TITLE
[framework] Add more by-name sugar to Diagram and DiagramBuilder

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18069.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

Python bindings coming in a moment, but the meat of the review is ready.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078#-:-NE75GdJ91wyATg6j2WB:b4mgq9h)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`systems/framework/diagram_builder.h` line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NE75DjQ-2AsvKG66ldI:-NE75DjQ-2AsvKG66ldJ:b-udy9yc) ([raw file](https://github.com/robotlocomotion/drake/blob/c304d7fc8f419de59bedb0ef508a9a5b1e48518e/systems/framework/diagram_builder.h#L283)):*
> ```objc
>   /// @see GetSubsystemByName()
>   /// @see GetMutableDowncastSubsystemByName()
>   System<T>& GetMutableSubsystemByName(std::string_view name);
> ```

Working

Add python bindings for the prior two functions.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`systems/framework/diagram_builder.h` line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NE75DjQ-2AsvKG66ldI:-NE7I6AX9cntCgSEq8ZT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c304d7fc8f419de59bedb0ef508a9a5b1e48518e/systems/framework/diagram_builder.h#L283)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Add python bindings for the prior two functions.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078#-:-NE7QIyx527kGUqzuKW7:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by jwnimmer-tri** [comment]
@sherm1 I have train of PRs waiting on this one.  Please put this at the front on your queue.

**Review by sherm1 — COMMENTED** [review]
Platform checkpoint (lunch)

> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078#-:-NECZwTr0BTPP46U9amS:bypd00n)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 8 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078#-:-NECtIkJ-czVvVaZ8p8h:b8qx53o)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram.h` line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NECoG7KAgnV9a56O4MM:-NECoG7LANOE89Wgbi0T:b-k4pqc9) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f10713cd1afb0963704bdd8d6842a7aa11b42e/systems/framework/diagram.h#L147)):*
> ```objc
>   /// @see GetDowncastSubsystemByName()
>   /// @see System<T>::get_name()
>   const System<T>& GetSubsystemByName(std::string_view name) const;
> ```

minor: IIRC we don't enforce name uniqueness (doc says "names should be unique" but doesn't make it so). If so please document what happens if there are multiple possibilities (here & for Downcast & DiagramBuilder). Or maybe uniqueness is just an unenforced prereq here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram.h` line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NECoG7KAgnV9a56O4MM:-NECuktF61RduICdpiUu:b-mnsebr) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f10713cd1afb0963704bdd8d6842a7aa11b42e/systems/framework/diagram.h#L147)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: IIRC we don't enforce name uniqueness (doc says "names should be unique" but doesn't make it so). If so please document what happens if there are multiple possibilities (here & for Downcast & DiagramBuilder). Or maybe uniqueness is just an unenforced prereq here?
</blockquote></details>

I was almost certain that we did.  (For the Diagram; maybe not during the DiagramBuilder phase.)

I'll investigate.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram.h` line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NECoG7KAgnV9a56O4MM:-NECvcbTArQ9qlei-5oj:bk7p1qj) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f10713cd1afb0963704bdd8d6842a7aa11b42e/systems/framework/diagram.h#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was almost certain that we did.  (For the Diagram; maybe not during the DiagramBuilder phase.)

I'll investigate.
</blockquote></details>

Yes, for Diagram we check `NamesAreUniqueAndNonEmpty` during construction, so it's moot on this file.

For the DiagramBuilder however, indeed we currently allow _temporary_ duplicate names as long as they are set to something unique prior to call `Build()`.

I'll rework the new DiagramBuilder getters to account for this (by throwing in case of duplicates).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/framework/diagram.h` line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18078#-NECoG7KAgnV9a56O4MM:-NECyaok4h6jZz5wIV-m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f10713cd1afb0963704bdd8d6842a7aa11b42e/systems/framework/diagram.h#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, for Diagram we check `NamesAreUniqueAndNonEmpty` during construction, so it's moot on this file.

For the DiagramBuilder however, indeed we currently allow _temporary_ duplicate names as long as they are set to something unique prior to call `Build()`.

I'll rework the new DiagramBuilder getters to account for this (by throwing in case of duplicates).
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18078)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
