### PR TITLE
replace DRAKE_ABORT_UNLESS with DRAKE_DEMAND

### LINKED ISSUE #3355: Some DRAKE_ABORT_UNLESS usages have poor readability
I just reviewed a PR with half a dozen instances of `DRAKE_ABORT_UNLESS(something != nullptr)`.  This is something like a quadruple negative "abort is bad... but unless means it's good, but `!=` means it's bad... but `nullptr` is also bad so it's good..."

This is obviously awful for readability, and makes my head hurt every time I have to puzzle it out.

A much clearer idiom would be `DRAKE_REQUIRE_NONNULL(something)` or just `DRAKE_REQUIRE(something != nullptr)`.

I propose adding one or both of those macros to our drake assertions.

By filing this issue I understand that I am throwing open the doors of the bikeshed; I'm just interested to see if there's any consensus possible.

### PR DESCRIPTION
**Pull request by ggould-tri**
Resolve #3355 by replacing DRAKE_ABORT_UNLESS with DRAKE_DEMAND and documenting the legality of testing ptr nullness as boolean.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3430)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@david-german-tri as on-call platform reviewer.
+@lucy-tri randomly selected for feature review.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-:-KRZVkPofoc94gJ5XKp9:b-8i9b6h)*

**Comment by Lucy-tri** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZikyLRw85-PfH8SzY:-KRZikyLRw85-PfH8SzZ:b-vwmlen) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L175)):*
>  * Use ``DRAKE_ASSERT`` for assertions that are only compiled and checked
>     in debug builds.
I think it might be more clear who is doing what if it were:
To compile and assert only in debug builds, use DRAKE _ASSERT. 
To assert in any kind of build (including release), use DRAKE_DEMAND.
Minor point, I found it odd to read.

---

*[drake/doc/code_style_guide.rst, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZnWECxhuhEpr3-HeT:-KRZnWECxhuhEpr3-HeU:b-wa4k7q) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L177)):*
> DRAKE_DEMAND(`` *condition* ``)
I guess you don't need to list the argument *condition*, since you don't list it for DRAKE_ASSERT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430)*

**Comment by ggould-tri** [comment]
Review status: 24 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZikyLRw85-PfH8SzY:-KRZonymNFHJ10QDgwIN:byn50ri) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L175)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> >  * Use ``DRAKE_ASSERT`` for assertions that are only compiled and checked
> >     in debug builds.
> I think it might be more clear who is doing what if it were:
> To compile and assert only in debug builds, use DRAKE _ASSERT. 
> To assert in any kind of build (including release), use DRAKE_DEMAND.
> Minor point, I found it odd to read.
</details>
Sounds good.  I rearranged your proposed sentences to put "DRAKE_ASSERT" / "DRAKE_DEMAND" at the beginning of the sentences, as I think it makes it a bit easier visually for someone casually perusing.

---

*[drake/doc/code_style_guide.rst, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZnWECxhuhEpr3-HeT:-KRZp1Cg2RGrA7XG9j_5:b-xjhxnm) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L177)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > DRAKE_DEMAND(`` *condition* ``)
> I guess you don't need to list the argument *condition*, since you don't list it for DRAKE_ASSERT.
</details>
I added the argument in the other case, rather than removing it, because I think it reads more clearly in comparison to "DRAKE_ABORT" which takes no arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZikyLRw85-PfH8SzY:-KRZpw5dBpjebCYZUYet:bttvtfg) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L175)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Sounds good.  I rearranged your proposed sentences to put "DRAKE_ASSERT" / "DRAKE_DEMAND" at the beginning of the sentences, as I think it makes it a bit easier visually for someone casually perusing.
</details>
Ok, that works too.

---

*[drake/doc/code_style_guide.rst, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZnWECxhuhEpr3-HeT:-KRZq0BFrBCaPp58mYlP:b-87j110) ([raw file](https://github.com/robotlocomotion/drake/blob/8cb45cd40eb28581a12e51f84d6c434f5b480dde/drake/doc/code_style_guide.rst#L177)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I added the argument in the other case, rather than removing it, because I think it reads more clearly in comparison to "DRAKE_ABORT" which takes no arguments.
</details>
Good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-:-KRZq4E7uOn6b2gYNM2Z:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri
:lgtm: modulo open discussions

---

Reviewed 24 of 25 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/drake_assert_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZpZj5SQMbRpQ5CTzX:-KRZpZj5SQMbRpQ5CTzY:bi4f628) ([raw file](https://github.com/robotlocomotion/drake/blob/ec8da12cb5d1414f58acb8fbe05eace4e76e6353/drake/common/test/drake_assert_test.cc#L17)):*
> ```cpp
> }
> 
> GTEST_TEST(DrakeAssertDeathTest, AbortUnlessTest) {
> ```

The test name is stale.

---

*[drake/solvers/system_identification.cpp, line 360 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZpou4taexWuHOWxUj:-KRZpou4taexWuHOWxUk:b-bx17ky) ([raw file](https://github.com/robotlocomotion/drake/blob/ec8da12cb5d1414f58acb8fbe05eace4e76e6353/drake/solvers/system_identification.cpp#L360)):*
> ```cpp
>         // the TrigPoly constructor.
>         DRAKE_DEMAND(k_v_pair.second.s ==
>                            original_sin_cos_map[k_v_pair.first].s);
> ```

Indentation is wrong now; same two lines below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-:-KRZq4dUvOWPWzT6CC0s:b-52jldk)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/drake_assert_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZpZj5SQMbRpQ5CTzX:-KRZqyWa_mQl63GiSThP:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/ec8da12cb5d1414f58acb8fbe05eace4e76e6353/drake/common/test/drake_assert_test.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The test name is stale.
</details>
Fixed.

---

*[drake/solvers/system_identification.cpp, line 360 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3430#-KRZpou4taexWuHOWxUj:-KRZqzcsjHtgmkxCXDKj:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/ec8da12cb5d1414f58acb8fbe05eace4e76e6353/drake/solvers/system_identification.cpp#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Indentation is wrong now; same two lines below.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3430)*

**Pull request merged**
