### PR TITLE
[geometry/dev] Add client-server round trip integration tests

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16822)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@zachfang for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16822#-:-MySFnA_7xjH2jUzLLMY:b-ftk99j)* status: 6 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[tools/workspace/vtk/repository.bzl, line 556 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySFrnhEgeLMwk97G3R:-MySFrniBWbuquw2jN2L:b-awyd8y) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/tools/workspace/vtk/repository.bzl#L556)):*
> ```Starlark
>             "vtkImageDifference.h",
>             "vtkImageExtractComponents.h",
>         ],
> ```

This change has to go through platform review.  I can cherry pick it out to a separate PR and just link to here saying "this is why we need it." ?
___
*[geometry/render/dev/BUILD.bazel, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySG0PyDovRVBKWqeoz:-MySG0PyDovRVBKWqep-:b78ns8w) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/BUILD.bazel#L147)):*
> ```Starlark
> # TODO(svenevs): install the final list of dependencies when decided.
> # Runs a flask server on 127.0.0.1:8000.  --host and --port are enabled as
> # command line overrides (e.g., if port 8000 is occupied).
> ```

We're blocked on this, tests are likely going to fail.  This will be another platform type thing needing to be done in a separate PR, we'll need to add `flask` to the testing requirements on linux and mac and rebuild the images.
___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySGFt985qZLdC9caHH:-MySGFt985qZLdC9caHI:buv9p7e) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L108)):*
> ```Python
>     method will stop the server, delete any files created, and unset the state
>     created in ``setUp``.
>     """
> ```

FYI I did the best I could in the time available to make this as clear as possible... It was a little awkward to get setup but TL;DR it is this way because in the test setup you have to spawn a server, so that's why I used a decorator, it is important to test alternative endpoints -- I wasn't sure if things were going to work sending to `/` (root endpoint) but fortunately they do!  
___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 238 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySI1ixEHoun0n-sj19:-MySI1ixEHoun0n-sj1A:brmpcc9) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L238)):*
> ```Python
>         #     drake/geometry/render/dev/test/
>         #       {test_method_name}_{timestamp}, e.g.
>         #       test_root_endpoint_2022-03-18_13-33-34-877389
> ```

FYI this gnarly path is how to view what the tests are doing.  I'm adding exports from a local run so you can see what they do.
___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySI9gBBS5puF-IozyB:-MySI9gBBS5puF-IozyC:bnn6cc1) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L399)):*
> ```Python
>         # a more intelligent comparison needs to be created.
>         # depth_pairs = self.gather_image_pairs("depth")
>         # self.compare_image_sha256_sums(depth_pairs)
> ```

FYI depth images are not verified.
___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 419 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySITHT2wHdVbRzNVrU:-MySITHU-fb67gn4Isxd:b-io9si1) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L419)):*
> ```Python
>     def test_render_server(self):
>         """Test the default endpoint with alternative image dimensions."""
>         self.simulate_and_compare()
> ```

I'm going to send you files over slack, i'm not allowed to upload zip :no_mouth:
___
*[geometry/render/dev/test/image_difference.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySGwg7BL094yd7D2mS:-MySGwg7BL094yd7D2mT:boe5d9o) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/image_difference.cc#L115)):*
> ```cpp
> 
>   // Compute the image difference and save to disk.
>   vtkNew<vtkImageDifference> image_difference;
> ```

I called out a comment in the test file for how to view things, putting a blocking comment here -- you will likely want to examine and play with the thresholds I did not have enough time.  [`vtkImageDifference::SetThreshold` in particular](https://vtk.org/doc/nightly/html/classvtkImageDifference.html#a0568fc4ecf97620077daf94f3a8a17da), it starts out fairly generous.  That said, using the sample images I gave in the responses above you should be able to just test against those images and decide what threshold you want.  Do note that if you compare `color_000.png` with say `color_001.png` you WILL get errors big enough to fail the tests.

Basically, some fiddling is a good idea but I did not have time.
___
*[geometry/render/dev/test/gltf_render_server.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySGc-f9n0gvSC_yWor:-MySGc-f9n0gvSC_yWos:b1leq7f) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/gltf_render_server.py#L15)):*
> ```Python
> 
> Tip:
>     While developing your server, it can be helpful to provide the ``--debug``
> ```

FYI I added a `--debug` at the bottom for `app.run(...)` and updated these docs.
___
*[geometry/render/dev/test/gltf_render_server.py, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySGh3m5r5tIJJj0EbK:-MySGh3m5r5tIJJj0EbL:bp3kdld) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/gltf_render_server.py#L95)):*
> ```Python
>     In your own server, just choose the endpoint and set it without any
>     variables e.g., ``app.route("/render")``, configurable endpoints is
>     generally bad practice but is useful for the tests.
> ```

FYI it's just good to caution the user "hey this is weird, don't do this in your actual server just choose an endpoint."
___
*[geometry/render/dev/test/run_simulation_and_render.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySHPSDAqfWv7W19B8Q:-MySHPSE42huFQCYC0Kw:b-vau5cr) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/run_simulation_and_render.cc#L33)):*
> ```cpp
> DEFINE_bool(label, true, "Sets the enabled camera to render label");
> // TODO(zachfang): disable drake visualizer when this is false.
> DEFINE_bool(drake_visualizer, true, "Attach to drake-visualizer publisher.");
> ```

The testing programs supply `--nodrake_visualizer` but it does not do anything, I deleted it all originally but it seems like it would be straightforward for you to fix this up to actually check `if (FLAGS_drake_visualizer)` ... and only connect things.  I don't know the publishing system well enough to know which bits can be removed.  It slows down the tests which are already a bit lengthy (maybe add a flag to remove the mustard bottle too?).
___
*[geometry/render/dev/test/run_simulation_and_render.cc, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySHkjU4gMnN1QIrEWg:-MySHkjU4gMnN1QIrEWh:b2g7j0w) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/run_simulation_and_render.cc#L294)):*
> ```cpp
>     params.url = FLAGS_url;
>     params.port = FLAGS_port;
>     params.render_endpoint = FLAGS_render_endpoint;
> ```

FYI did not ad `FLAGS_verbose` or `FLAGS_no_cleanup`, could be useful to add for people running the demo but not needed for the tests.
___
*[geometry/render/dev/test/run_simulation_and_render.cc, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySHsF29nd3k5pSI8Ok:-MySHsF29nd3k5pSI8Ol:b-v7sjd8) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/run_simulation_and_render.cc#L316)):*
> ```cpp
>     const ColorRenderCamera color_camera{
>         {render_name, {FLAGS_width, FLAGS_height, M_PI_4}, {0.01, 10.0}, {}},
>         false};
> ```

To keep the diff small I did not do it, but we should really run `clang-format` on this file :wink:

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16822)* status: 7 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySOTFh958fqoU1renT:-MySOTFh958fqoU1renU:b-1j8fi1) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L140)):*
> ```Python
>             # NOTE: checking instantly does not give flask enough time to crash
>             # so we must pause briefly before checking.
>             time.sleep(1)
> ```

this loop is why the tests are timing out most likely, it tries to do `run_server` which will fail every time because `flask` is not installed.  that needs to get added to the test requirements and images rebuilt.  possibly a good idea to `try:` to import `flask` and assert to fail the test early to distinguish between the failed port (occupied) vs "flask is not installed"



_Code quote (from tools/workspace/vtk/repository.bzl):_
```Starlark
            "vtkSmartPointerBase.h",
            "vtkStdString.h",
            "vtkSystemIncludes.h",
            "vtkThreads.h",
            "vtkTimeStamp.h",
            "vtkType.h",
            "vtkTypeInt32Array.h",
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16822)* status: 7 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MySOTFh958fqoU1renT:-MySOsjr3GbQ07UZdEIC:b-k56cio) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L140)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

this loop is why the tests are timing out most likely, it tries to do `run_server` which will fail every time because `flask` is not installed.  that needs to get added to the test requirements and images rebuilt.  possibly a good idea to `try:` to import `flask` and assert to fail the test early to distinguish between the failed port (occupied) vs "flask is not installed"
</blockquote></details>

ignore the code quote above, that was an accident sorry!

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16822)* status: 9 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-Mygm3QxAmzFh-0eTVBn:-Mygm3QxAmzFh-0eTVBo:bmj4492) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L45)):*
> ```Python
>     render_endpoint: str = "render",
>     host: str = "127.0.0.1",
>     port: int = 8000,
> ```

Default values for these should be removed, the `setUp()` always sets them (and should).
___
*[geometry/render/dev/test/client_server_round_trip_test.py, line 257 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16822#-MygmYw278J_mJmD40TB:-MygmYw278J_mJmD40TC:b-tr0x1t) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0bc25018daab52a758ff0c5fafbf2b44571414/geometry/render/dev/test/client_server_round_trip_test.py#L257)):*
> ```Python
>         # NOTE: this path is only valid in bazel, see data dependencies.
>         exe_path = this_file_dir.parent / "run_simulation_and_render"
>         subprocess.run([exe_path, *simulation_args])
> ```

Should change to `subprocess.check_call`

**Comment by zachfang** [comment]
Close this PR for now and revisit it during the second half of the RenderRpc PR train.

**Pull request closed without merging**
