### PR TITLE
[workspace] Build libpng_internal from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Deprecate libpng from the host OS and remove it from setup prereqs.

Towards #17231 in wheel builds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/libpng_internal/package.BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-NfXBWcy4XpfRj3_ysEx:-NfXBWcy4XpfRj3_ysEy:bfffjog) ([raw file](https://github.com/RobotLocomotion/drake/blob/2053c16bbde6ef5368681eb95aa83f5d9e4edde8/tools/workspace/libpng_internal/package.BUILD.bazel#L93)):*
> ```
>             # Use only the SSE2 instructions (not SSE3, AVX2, etc.)
>             # This matches the Debian default (i.e., the psABI baseline).
>             "-DPNG_INTEL_SSE_IMPLEMENTATION=1",
> ```

fwiw I think we would be fine having the baseline be SSE4 + POPCNT. That would cover everything released in the last decade from Intel (Sandy Bridge+ (2010), Silvermont+ (2013)) and AMD (Bulldozer+ (2011), Jaguar+ (2013)).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/libpng_internal/package.BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-NfXBWcy4XpfRj3_ysEx:-NfXjg-75LhqK8WydY7m:b2ody5s) ([raw file](https://github.com/RobotLocomotion/drake/blob/2053c16bbde6ef5368681eb95aa83f5d9e4edde8/tools/workspace/libpng_internal/package.BUILD.bazel#L93)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

fwiw I think we would be fine having the baseline be SSE4 + POPCNT. That would cover everything released in the last decade from Intel (Sandy Bridge+ (2010), Silvermont+ (2013)) and AMD (Bulldozer+ (2011), Jaguar+ (2013)).
</blockquote></details>

Good point.  Done.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-:-NfkjNCc4faC9WhFZwTZ:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth a question for my own edification about deprecation vs distribution.

> Reviewed 12 of 15 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-:-NflV_rW0nobWPPOq-6a:b-7ykdaq)* status: 1 unresolved discussion

___
*[`setup/ubuntu/binary_distribution/packages-focal.txt` line 25 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-NflUBrq-t0mzoAhMJPr:-NflUBrr38K8N9H4SfMg:b-v7a12p) ([raw file](https://github.com/RobotLocomotion/drake/blob/19632447460e8f951792ff944a11ee26e087b925/setup/ubuntu/binary_distribution/packages-focal.txt#L25)):*
> ```help
> libogg0
> libopengl0
> libpng16-16
> ```

In both of these distribution, what are the odds that the user *got* libpng because of drake? Admittedly, they'll still have it until they do an install on a new machine. Presumably, we don't make promises about our dependencies being stable (although, we did make the effort vis a vis VTK).

From source, it's not a problem. If they reference the deprecated target, they'll be warned, but it will continue to pull the dependency and use it, right? It's only people who use drake from install that would have the chance to trip over this?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)* status: 1 unresolved discussion

___
*[`setup/ubuntu/binary_distribution/packages-focal.txt` line 25 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-NflUBrq-t0mzoAhMJPr:-NflcwmLBmaPL__qdhpx:b-fvyo0r) ([raw file](https://github.com/RobotLocomotion/drake/blob/19632447460e8f951792ff944a11ee26e087b925/setup/ubuntu/binary_distribution/packages-focal.txt#L25)):*
> ... what are the odds that the user _got_ libpng because of drake? ..

There's no way to know.

> ... we don't make promises about our dependencies being stable ...

Correct. The https://drake.mit.edu/stable.html only promises that OS things we require will be installed by `install_prereqs`.  It doesn't mention how/when we remove things.  (Maybe it should explicitly disclaim stability for the package lists?)

>  ...although, we did make the effort vis a vis VTK ...

I don't believe we did.  The commit message for #19945 says:

> > The repository rules will continue to work during the deprecation
window, but Drake no longer installs their Ubuntu packages; if you
need the packages, ensure your project setup scripts install them.

> From source, it's not a problem. If they reference the deprecated target, they'll be warned, but it will continue to pull the dependency and use it, right? It's only people who use drake from install that would have the chance to trip over this?

I wouldn't phrase it that way.  Instead, I'd say the cases which might cause breakage are when the user was invoking Drake's `install_prereqs` as a subroutine (whether they are doing a source build or using our binaries), and assuming that it does anything more than prepare the system to build (or just run) Drake.  That's one reason why drake-external-examples exhibits vendored copies of Drake's package lists, and why Anzu likewise has vendored copies. A smart user should be inspecting and approving/rejecting any changes to those lists.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)* status: 1 unresolved discussion

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20276)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`setup/ubuntu/binary_distribution/packages-focal.txt` line 25 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20276#-NflUBrq-t0mzoAhMJPr:-Nfm2cAN4TECvVKUmbfC:be7wfx) ([raw file](https://github.com/RobotLocomotion/drake/blob/19632447460e8f951792ff944a11ee26e087b925/setup/ubuntu/binary_distribution/packages-focal.txt#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... what are the odds that the user _got_ libpng because of drake? ..

There's no way to know.

> ... we don't make promises about our dependencies being stable ...

Correct. The https://drake.mit.edu/stable.html only promises that OS things we require will be installed by `install_prereqs`.  It doesn't mention how/when we remove things.  (Maybe it should explicitly disclaim stability for the package lists?)

>  ...although, we did make the effort vis a vis VTK ...

I don't believe we did.  The commit message for #19945 says:

> > The repository rules will continue to work during the deprecation
window, but Drake no longer installs their Ubuntu packages; if you
need the packages, ensure your project setup scripts install them.

> From source, it's not a problem. If they reference the deprecated target, they'll be warned, but it will continue to pull the dependency and use it, right? It's only people who use drake from install that would have the chance to trip over this?

I wouldn't phrase it that way.  Instead, I'd say the cases which might cause breakage are when the user was invoking Drake's `install_prereqs` as a subroutine (whether they are doing a source build or using our binaries), and assuming that it does anything more than prepare the system to build (or just run) Drake.  That's one reason why drake-external-examples exhibits vendored copies of Drake's package lists, and why Anzu likewise has vendored copies. A smart user should be inspecting and approving/rejecting any changes to those lists.
</blockquote></details>

Thanks for the clarification.

(Sorry, I hadn't meant to make that blocking.)

**Pull request merged**
