### PR TITLE
Add error guidance to Get*ByName methods.

### LINKED ISSUE #14426: Multibody and System "there is no" exceptions should list valid values
All of the MBP by-name accessors have exceptions that say "there is no [thingy] named [mumble] in the model."

That's great and all but the only way for a user faced with this error to find out what you might have gotten wrong is to run a debug build, get a stack trace, find the enclosing call, and log the contents of the model right before the call.

The exception should list the available names to save the user from this hunt.

### PR DESCRIPTION
**Pull request by ggould-tri**
Along with #17255, resolves #14426

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@rpoyner-tri Companion to #17255.  This is a bit fiddly with unordered_multimap and our weird key type, so beware or delegate as you prefer.  Low priority.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259#-:-N2rVGVcDiNVSUK4jIyp:b-5xtjj)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by ggould-tri — COMMENTED** [review]
Sample output:
```
err.what() evaluates to "GetJointActuatorByName(): There is no JointActuator named 'InvalidName' anywhere in the model (valid names are: iiwa_actuator_7, iiwa_actuator_5, iiwa_actuator_4, iiwa_actuator_3, iiwa_actuator_2, iiwa_actuator_6, iiwa_actuator_1)"
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259#-:-N2rWRbjAh4LHNzIYzxv:b-fvrjk0)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by ggould-tri** [comment]
*[`multibody/tree/multibody_tree.cc` line 267 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17259#-N2rXTQcEKaM1j1SjB3u:-N2rXTQd2q7H2pLwNJq0:boweg5p) ([raw file](https://github.com/robotlocomotion/drake/blob/501712adb08eab886a55a76a56e3ad0a4ef6cac9/multibody/tree/multibody_tree.cc#L267)):*
> ```cpp
>   // instance was requested.
>   if (lower == upper) {
>     std::string all_keys = "";
> ```

working:  This will elicit the same objection as the prior PR.  Rewriting to be less quadratic.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: space

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259#-:-N2rZH6_6EjUuNZpJJ19:b-7w3fgp)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @rpoyner-tri)

___
*[`multibody/tree/multibody_tree.cc` line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17259#-N2rYP4k0Jd_IgGN27Z-:-N2rYP4l8a50s9jKaREV:b-1fez00) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a44a2f805692c206ae9275acdbdd035a78c87e/multibody/tree/multibody_tree.cc#L277)):*
> ```cpp
>     throw std::logic_error(fmt::format(
>         "Get{}ByName(): There is no {} named '{}' anywhere in the model "
>         "(valid names are:{})",
> ```

Looks to me like missing whitespace between `:` and `{`. Maybe fiddle the regex in the tests to detect this as well?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+@jwnimmer-tri  platform

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259#-:-N2rhP4W4baVbokOYgC1:b-lujbmo)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
+(release notes: yes) "Improve error messages for incorrect port names" is a notable UX improvement.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259#-:-N2rkOCJBRlpfDdSH14o:b-vtj4vo)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[`multibody/tree/multibody_tree.cc` line 273 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17259#-N2rjAl02XyG-F4MRYio:-N2rjAl15-_e92JSH0ay:b-fnqm88) ([raw file](https://github.com/robotlocomotion/drake/blob/5caa26ea02f5fba2f46f99a70c6a2d8e95135077/multibody/tree/multibody_tree.cc#L273)):*
> ```cpp
>          it != end;
>          it = name_to_index.equal_range(it->first).second) {
>       all_keys.push_back(it->first.view());
> ```

I think this adds names from unordered_map keys into a vector, and thus the displayed list of names will appear in a randomized, non-deterministic order?  Our output should always be deterministic.

Doing a `std::sort` before printing would be one solution.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`multibody/tree/multibody_tree.cc` line 273 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17259#-N2rjAl02XyG-F4MRYio:-N2rlh0h6K_OAhrkzjZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5caa26ea02f5fba2f46f99a70c6a2d8e95135077/multibody/tree/multibody_tree.cc#L273)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this adds names from unordered_map keys into a vector, and thus the displayed list of names will appear in a randomized, non-deterministic order?  Our output should always be deterministic.

Doing a `std::sort` before printing would be one solution.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17259)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
