### PR TITLE
Add serialization for GraphOfConvexSetsOptions

### PR DESCRIPTION
**Pull request by sadraddini**
Serializing only built-in types so users can save and load them as needed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Given design question, I think it'd be wise to have additional review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-:-Nqe-P2x0MYfbxeqiH8S:b-ekrq7m)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sadraddini)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-Nqe-IfmDCiQyZOcWHcW:-Nqe-IfmDCiQyZOcWHcX:b-a8h5r7) (no related file):*
Consider adding small test for expectations for saving / loading.

(I would suggest waiting until we have the go-ahead on the approach)

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqdzpdlCIOTftV3CQid:-NqdzpdlCIOTftV3CQie:b-qgu43t) ([raw file](https://github.com/RobotLocomotion/drake/blob/28480bd640089c2c8498555da340a95293315e47/geometry/optimization/graph_of_convex_sets.h#L75)):*
> ```objc
>   std::optional<solvers::SolverOptions> rounding_solver_options{std::nullopt};
> 
>   /** Passes this object to an Archive.
> ```

Hm... Expectations for partial saving / loading makes me a tad concerned.

@jwnimmer-tri Can I ask for your opinion?
Is this something we should do, or make an explicit `SavePartial` / `LoadPartial`?

@calderpg-tri mentioned we have `SingleSolverOptions` for solver options, but I'm still concerned about how to handle `solver`.

**Comment by EricCousineau-TRI** [comment]
*[`geometry/optimization/graph_of_convex_sets.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqdzpdlCIOTftV3CQid:-Nqe2b8D2A2SxOd7hBtD:b-90009k) ([raw file](https://github.com/RobotLocomotion/drake/blob/28480bd640089c2c8498555da340a95293315e47/geometry/optimization/graph_of_convex_sets.h#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... Expectations for partial saving / loading makes me a tad concerned.

@jwnimmer-tri Can I ask for your opinion?
Is this something we should do, or make an explicit `SavePartial` / `LoadPartial`?

@calderpg-tri mentioned we have `SingleSolverOptions` for solver options, but I'm still concerned about how to handle `solver`.
</blockquote></details>

Sorry, meant `SerializeDrakeSolverOptions` in Anzu

**Review by sadraddini — COMMENTED** [review]
FWIW, we have the same partial saving/loading in [IrisOptions](https://drake.mit.edu/doxygen_cxx/structdrake_1_1geometry_1_1optimization_1_1_iris_options.html#a8e8824802dedfbc36776227f7482b6bc)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-:-NqgJuPH8M4YIw0Ns_ZJ:buj7tsg)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-Nqe-IfmDCiQyZOcWHcW:-NqgK8WB8-EEDFRDmdv6:bk7qpfg) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Consider adding small test for expectations for saving / loading.

(I would suggest waiting until we have the go-ahead on the approach)
</blockquote></details>

Added a unit test. 

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: modulo open discussions.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-:-NqsK8ZsBIe2fSScCuZm:b962cgu)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqdzpdlCIOTftV3CQid:-NqsFyOo5RRQHtUIaCwN:b-bfb14b) ([raw file](https://github.com/RobotLocomotion/drake/blob/28480bd640089c2c8498555da340a95293315e47/geometry/optimization/graph_of_convex_sets.h#L75)):*
> Calder mentioned we have `SerializeDrakeSolverOptions` for solver options, ...

Yup, that Anzu code is basically a work-around for not having https://github.com/RobotLocomotion/drake/issues/20967 in Drake yet.

We should place a `TODO(#20967)` comment in Serialize() to remind us.  I'll incorporate that into my code suggestion below.

> ... but I'm still concerned about how to handle `solver`.

Simply from a readability / maintainer standpoint, when we do something subtle like omit field(s) from the `Serialize()` listing, we must make it 100% clear and obvious that we've done so, and why we've done it.  I'll incorporate that into my code suggestion below.  That's the minimum bar for this PR to merge -- that it doesn't make anything _worse_.

However, I'll also leave another comment on the `solver` member field itself.  That's a ticking bomb that will need to be fixed, possibly in another PR.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsGbzP0PEuaD4zeyL_:-NqsGbzP0PEuaD4zeyLa:b-qmsfhw) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L25)):*
> ```objc
> 
> struct GraphOfConvexSetsOptions {
>   GraphOfConvexSetsOptions() = default;
> ```

nit Delete this constructor line (and the blank line after it).  For structs, we should _always_ try to only use the implicitly-defined default constructor, so that aggregate initialization works correctly.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsHfB9DV24Zb6_X5jI:-NqsHfB9DV24Zb6_X5jJ:b1y419q) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L63)):*
> ```objc
>   solver cannot handle the type of optimization problem generated, the calling
>   solve method will throw. */
>   const solvers::SolverInterface* solver{nullptr};
> ```

Putting a bare pointer into an Options struct was a mistake in #17396 that apparently nobody noticed until now.

At the very minimum, it would need to be a `shared_ptr<const SolverInterface>` with the Python holder annotation for `SolverInterface` changing to be shared_ptr instead of unique_ptr.  Without that, Python GC will eventually blow our leg off with its shotgun.

Really, the `solver` shouldn't be a part of the options at all, since it's not serializable.  It should just be a sibling kwarg on the functions that take a `GraphOfConvexSetsOptions`, e.g. `SolveShortestPath(source=..., target=..., options=..., solver=...)`.

To get this PR merged, we'll either we need delete this field (if we deem it to be `@experimental` and therefore can remove it without deprecation), or else file an issue calling for its deletion and cite that new issue number from the comments inside `Serialize()`.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsGnJiB9STIXLLCTKc:-NqsGnJj3vSU-pnsBpdo:bc94nmd) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L86)):*
> ```objc
>     a->Visit(DRAKE_NVP(flow_tolerance));
>     a->Visit(DRAKE_NVP(rounding_seed));
>   }
> ```

nit When we omit member fields from visitation, we need to make it clear and obvious to the next person who comes by here to read the code that the omission is on purpose instead of accidental.



_Suggestion:_
```objc
  void Serialize(Archive* a) {
    a->Visit(DRAKE_NVP(convex_relaxation));
    a->Visit(DRAKE_NVP(max_rounded_paths));
    a->Visit(DRAKE_NVP(preprocessing));
    a->Visit(DRAKE_NVP(max_rounding_trials));
    a->Visit(DRAKE_NVP(flow_tolerance));
    a->Visit(DRAKE_NVP(rounding_seed));
    // N.B. We skip the DRAKE_NVP(solver), because it cannot be serialized.
    // TODO(#20967) Serialize the DRAKE_NVP(solver_options).
    // TODO(#20967) Serialize the DRAKE_NVP(rounding_solver_options).
  }
```

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsGbzP0PEuaD4zeyL_:-NqsZUoj7plfq7MaLlOV:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Delete this constructor line (and the blank line after it).  For structs, we should _always_ try to only use the implicitly-defined default constructor, so that aggregate initialization works correctly.
</blockquote></details>

Done
___
*[`geometry/optimization/graph_of_convex_sets.h` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsHfB9DV24Zb6_X5jI:-Nqs_EqbDCxKMnmkA9XC:b-tttgsf) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Putting a bare pointer into an Options struct was a mistake in #17396 that apparently nobody noticed until now.

At the very minimum, it would need to be a `shared_ptr<const SolverInterface>` with the Python holder annotation for `SolverInterface` changing to be shared_ptr instead of unique_ptr.  Without that, Python GC will eventually blow our leg off with its shotgun.

Really, the `solver` shouldn't be a part of the options at all, since it's not serializable.  It should just be a sibling kwarg on the functions that take a `GraphOfConvexSetsOptions`, e.g. `SolveShortestPath(source=..., target=..., options=..., solver=...)`.

To get this PR merged, we'll either we need delete this field (if we deem it to be `@experimental` and therefore can remove it without deprecation), or else file an issue calling for its deletion and cite that new issue number from the comments inside `Serialize()`.
</blockquote></details>

Opened an issue and referenced it
___
*[`geometry/optimization/graph_of_convex_sets.h` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsGnJiB9STIXLLCTKc:-Nqs_AWT7TGC6P9wqPHb:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/dbb2fcc53659eb3d4e6c36ad63fe3f2f67df7598/geometry/optimization/graph_of_convex_sets.h#L86)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When we omit member fields from visitation, we need to make it clear and obvious to the next person who comes by here to read the code that the omission is on purpose instead of accidental.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 598 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqsyN8J7lFN6TC04l0p:-NqsyN8J7lFN6TC04l0q:b-iztqt) ([raw file](https://github.com/RobotLocomotion/drake/blob/5bc993ae858ec2acad8418c2e60576dafd77f908/bindings/pydrake/geometry/geometry_py_optimization.cc#L598)):*
> ```cpp
>     py::class_<GraphOfConvexSetsOptions> gcs_options(
>         m, "GraphOfConvexSetsOptions", cls_doc.doc);
>     gcs_options.def(py::init<>(), cls_doc.doc)
> ```

nit This ends up with the class overview docs duplicated into the constructor docs.  Since there are no constructor docs anymore, we should just leave it blank.



_Suggestion:_
```cpp
gcs_options.def(py::init<>())
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-:-NqxyO4aEfg98-RCn6kr:bcpz082)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20946#-NqdzpdlCIOTftV3CQid:-Nqxx1Gr3RkIdMbujBkM:b-rb2tu8) ([raw file](https://github.com/RobotLocomotion/drake/blob/28480bd640089c2c8498555da340a95293315e47/geometry/optimization/graph_of_convex_sets.h#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Calder mentioned we have `SerializeDrakeSolverOptions` for solver options, ...

Yup, that Anzu code is basically a work-around for not having https://github.com/RobotLocomotion/drake/issues/20967 in Drake yet.

We should place a `TODO(#20967)` comment in Serialize() to remind us.  I'll incorporate that into my code suggestion below.

> ... but I'm still concerned about how to handle `solver`.

Simply from a readability / maintainer standpoint, when we do something subtle like omit field(s) from the `Serialize()` listing, we must make it 100% clear and obvious that we've done so, and why we've done it.  I'll incorporate that into my code suggestion below.  That's the minimum bar for this PR to merge -- that it doesn't make anything _worse_.

However, I'll also leave another comment on the `solver` member field itself.  That's a ticking bomb that will need to be fixed, possibly in another PR.
</blockquote></details>

Thanks! I've put a small note in next platform meeting to discuss parameter structs + serialization.

**Pull request merged**
