### PR TITLE
Remove MATLAB quadrotor examples; add READMEs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6243.
Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6305)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for confirmation on the concept -- also please review the two new README files' content.

/CC @rdeits I'm happy to take any suggestions on the wording here.  I did my best to capture with what little knowledge I have, but if you have more or different text, feel free to drop it in a review comment, PR into my branch, or post here.

+(status: do not merge) until I've assigned additional review after Russ.

**Comment by RussTedrake** [comment]
Reviewed 2 of 35 files at r1.
Review status: 2 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/README-MATLAB.md, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6305#-KmQnujioRuMjy_ZXr2G:-KmQnujioRuMjy_ZXr2H:bjt7cts) ([raw file](https://github.com/robotlocomotion/drake/blob/22cee89ba15c6d280c0d59f1c7c47af32cb92ce1/drake/examples/README-MATLAB.md#L13)):*
> ```Markdown
> https://github.com/RobotLocomotion/drake/tree/last_sha_with_original_matlab/drake/examples
> 
> In particular, these examples are no longer available in any form on master:
> ```

I prefer the "have not yet been reimplemented" language you used for the quadrotor... it's appropriate here, too.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/README-MATLAB.md, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6305#-KmQnujioRuMjy_ZXr2G:-KmRWRp7nWioCAzQswZ0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/22cee89ba15c6d280c0d59f1c7c47af32cb92ce1/drake/examples/README-MATLAB.md#L13)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I prefer the "have not yet been reimplemented" language you used for the quadrotor... it's appropriate here, too.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@soonho-tri for all review, please.  (I'm manually cycling the MATLAB PRs through platform review, off-schedule.)

---

Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305#-:-KmRYXmLNAhZH1wAYsLJ:b988208)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please

**Comment by soonho-tri** [comment]
Reviewed 33 of 35 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305#-:-KmnIF7fJEudSfAYnPGS:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6305#-:-KmnX4dWDIfzLdD2nD6G:bnfp4nl)*

**Pull request merged**
