### PR TITLE
Remove ccache from the Drake documentation.

### LINKED ISSUE #2478: Building with clang+ccache fails with -Wself-assign
On master, with clang 703 (OSX):

```
[ 97%] Building CXX object bindings/swig/CMakeFiles/_ikPython.dir/ikPYTHON_wrap.cxx.o
/Users/rdeits/locomotion/drake-distro/drake/pod-build/bindings/swig/ikPYTHON_wrap.cxx:2427:23: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
                  res = (res);
                  ~~~ ^  ~~~
/Users/rdeits/locomotion/drake-distro/drake/pod-build/bindings/swig/ikPYTHON_wrap.cxx:2430:23: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
                  res = (res);
                  ~~~ ^  ~~~
2 errors generated.
make[6]: *** [bindings/swig/CMakeFiles/_ikPython.dir/ikPYTHON_wrap.cxx.o] Error 1
make[5]: *** [bindings/swig/CMakeFiles/_ikPython.dir/all] Error 2
make[4]: *** [all] Error 2
```

This causes the build to fail because we have `-Werror` set. We can squash the warning with `-Wno-self-assign`, but there's probably a better way.

### PR DESCRIPTION
**Pull request by david-german-tri**
We shouldn't maintain documentation for an optional convenience tool that we don't test in CI.

Fixes #2478.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2511)

### CODE REVIEW

**Comment by liangfok** [comment]
*[drake/doc/from_source.rst, line 147 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-KJbyD2Q9uDvMNBoIcw5:-KJbyD2Q9uDvMNBoIcw6:1828554434) ([raw file](https://github.com/robotlocomotion/drake/blob/dedf3e5648117170e1dae44206e9788c1e2158ce/drake/doc/from_source.rst#L147)):*
> ```reStructuredText
> `ccache manual <https://ccache.samba.org/manual.html#_run_modes>`_ for
> instructions on enabling ``ccache``.  To prevent certain spurious compiler
> errors, make sure to set the environment variable ``CACHE_CPP2=yes``.
> ```

Consider deleting "make sure to"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2511)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri BTW the TRI wiki also should mention or cite the CCACHE_CPP2 environment variable; the relevant wiki page is at `/internal/using-ccache` relative to the wiki's root URI.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Document the ccache environment variable CACHE\_CPP2\.
> 
> Pull the ccache documentation up from `ubuntu` to `from_source`, and get the install instructions by reference instead of platform-specific value.
> 
> 
> 
> Fixes #2478.
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 145 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-KJcFhm94EIXGVNq-d2j:-KJcFhm94EIXGVNq-d2k:-22931612) ([raw file](https://github.com/robotlocomotion/drake/blob/dedf3e5648117170e1dae44206e9788c1e2158ce/drake/doc/from_source.rst#L145)):*
> ```reStructuredText
> 
> A program called ``ccache`` can be used to speed up (re)builds. Consult the
> `ccache manual <https://ccache.samba.org/manual.html#_run_modes>`_ for
> ```

This PR removes from `ubuntu.rst` the `$PATH` advice that is a best practice on Ubuntu.  (Possibly other platforms offer the same or similar directory, too.  I don't know.)

The new advice -- the link to the manual -- is inferior, because it encourages users to perform a manual "symlinks method" that is brittle with respect to evolving compiler executable names and toggling ccache on/off.  Because Ubuntu is a well-integrated distribution, it can offer something better.

The ubuntu package of `ccache` provides well-maintained solution -- the `/usr/lib/ccache/` directory to add to the front of our `$PATH` -- and we should do our best to encourage developers to use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-:-KJcDowy-6liMk29hgcs:-1721012088)*

**Comment by david-german-tri** [comment]
Done.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @david-german-tri BTW the TRI wiki also should mention or cite the CCACHE_CPP2 environment variable; the relevant wiki page is at `/internal/using-ccache` relative to the wiki's root URI.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 145 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-KJcFhm94EIXGVNq-d2j:-KJf2DjJkWU7AezlaqAW:-766794791) ([raw file](https://github.com/robotlocomotion/drake/blob/dedf3e5648117170e1dae44206e9788c1e2158ce/drake/doc/from_source.rst#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This PR removes from `ubuntu.rst` the `$PATH` advice that is a best practice on Ubuntu.  (Possibly other platforms offer the same or similar directory, too.  I don't know.)
> 
> The new advice -- the link to the manual -- is inferior, because it encourages users to perform a manual "symlinks method" that is brittle with respect to evolving compiler executable names and toggling ccache on/off.  Because Ubuntu is a well-integrated distribution, it can offer something better.
> 
> The ubuntu package of `ccache` provides well-maintained solution -- the `/usr/lib/ccache/` directory to add to the front of our `$PATH` -- and we should do our best to encourage developers to use that.
</details>
On further consideration, I don't think we should maintain documentation for a completely optional convenience tool that we don't test in CI, so I've revised this PR to purge all reference to `ccache` from sphinx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-:-KJf3oLW2OM9yt5U1Pzw:-499146009)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>


---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2511#-:-KJf8_qqMbvQGRmfOKQo:980077401)*

**Comment by sammy-tri** [comment]
Given the frequency with which I run 'git clean -fdx' and build again (like every time I get confused by cmake, which, to be honest, is a lot) I'm not sure I'd call ccache "completely optional".   I do agree that documenting the use of a development environment not tested in CI is probably not a good idea, so, strictly speaking, I guess this is an improvement...

**Comment by jwnimmer-tri** [comment]
FWIW, my rote answer for "We should really document this developer instruction, but it's difficult to be clear how to do it right!" is "Why not put it into `CMakeLists.txt` instead, and get it under jenkins purview?"  Possibly a future PR that does that would be to our advantage?

**Comment by david-german-tri** [comment]
Making Jenkins exercise `ccache` in interesting ways seems at least as tricky as documenting this correctly.  (Would the CI script delete some build artifacts and rebuild?)  

I'm sticking to my belief that `ccache` is out of scope.  It's not feasible for Drake documentation or CI to take responsibility for every tool installed on a developer's workstation, and if some people don't know that `ccache` could make their lives better it's not the end of the world.

**Comment by jamiesnape** [comment]
Jenkins is not going to make good use of `ccache`, since more often than not builds happen on a completely clean VM.

**Pull request merged**
