### PR TITLE
Fix Wunused-parameter in joints

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6010)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.  This is using the new `unused` helper function ([docs](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0)).

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/joints/fixed_joint.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6010#-KjDPGX0AFwTfN81THXN:-KjDPGX1wXG5ZLTYAXrv:bfgx9b0) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0cc4a356db52508ae5d0ed0ed974936727fab2/drake/multibody/joints/fixed_joint.cc#L7)):*
> ```cpp
> 
> std::string FixedJoint::get_position_name(int) const {
>   throw std::runtime_error("bad index");
> ```

BTW -- not your defect, but the unusedness highlights how much this is an impressively misleading message this is.  I was not able to figure out how the author is but if you happen to know do refer it to someone for prompt destruction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6010#-:-KjDQ1YYNqQYCOlXdjmk:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/joints/fixed_joint.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6010#-KjDPGX0AFwTfN81THXN:-KjDa7IMieaen9wzYgOD:b-wr8z1b) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0cc4a356db52508ae5d0ed0ed974936727fab2/drake/multibody/joints/fixed_joint.cc#L7)):*
> ... the unusedness highlights how much this is an impressively misleading message this is.

Hah, I didn't even notice that.

This code is scheduled for deletion once multibody_tree is done; it has no active maintainer TTBOMK, so I will simply ping here @sherm1 and @amcastro-tri in case they feel inspired to fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6010)*

**Comment by amcastro-tri** [comment]
Thank you for the ping, but really I don't think worth the (though small) effort.

**Pull request merged**
