### PR TITLE
Enable split debug symbols on Ubuntu

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
See also #16500.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

Works locally; let's see what CI makes of it...

**Comment by jwnimmer-tri** [comment]
The code change looks good, like what I was expecting.  Besides the pre-merge CI failures (somewhat surprising) we'll need to check all of the ASan, Memcheck, Coverage, etc. builds as well.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

Not sure what happened to these, both report "Cannot contact EC2 ... Server terminated abruptly".

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

**Comment by mwoehlke-kitware** [comment]
Well, all of the *san builds are broken. What's our confidence level that `--fission` works *at all* with clang?

**Comment by mwoehlke-kitware** [comment]
Okay, my bad, it's only the asan builds that are broken... that's odd.

So, `ld` is complaining about `--gdb-index`. I'm not sure why asan, specifically, is linking differently?

**Comment by jwnimmer-tri** [comment]
It seems like ASan specifically uses a different linker:

https://github.com/RobotLocomotion/drake/blob/2f75971b66ca59dc2c1dee4acd78952474936a79/tools/dynamic_analysis/bazel.rc#L46-L47

I think it'd be fine to add `build:asan --fission=no` there as well, to opt-out.  We don't run ASan pre-merge, so hopefully we can continue living without Fission on ASan builds indefinitely.

**Comment by jwnimmer-tri** [comment]
Also note this, a few lines later:

https://github.com/RobotLocomotion/drake/blob/2f75971b66ca59dc2c1dee4acd78952474936a79/tools/dynamic_analysis/bazel.rc#L76-L78

I think those are supposed to say `build:asan_everything` instead of `build:asan`; the fission change would need to apply to `asan_everything` as well, if it ends up with a different linker.

Or maybe, the requirement to use `ld` no longer matters, and we could nix those lines entirely?

**Comment by mwoehlke-kitware** [comment]
> maybe, the requirement to use `ld` no longer matters, and we could nix those lines entirely, for all asan builds?

So, `ld.gold` spits out a ton of:
```
warning: Cannot export local symbol '__asan_extra_spill_area'
```
It looks like gold upstream(?) [considers this spurious](https://sourceware.org/bugzilla/show_bug.cgi?id=25975#c22), so if we can just ignore/suppress those, `--fission` seems to otherwise work.

Preference?

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-everything-release please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

These passed previously, but it seems like they've been flaky, so I want to see them pass more than once...

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-everything-release please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature +(release notes: yes).

+@EricCousineau-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587#-:-MwSmFq65WyCdqzWvfbR:b-xi66gi)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-Mw7RLTP5vl-GccGoS_C:-MwSkZ4u25G0aQ4FiEqu:b-h97ipz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Jeremy to figure out if there is any CI performance test we could run, to ensure that this doesn't harm the speed of cached pre-merge incremental builds.
</blockquote></details>

Here's what I'd like to do.

I don't think there's any great way to test this for CI performance regressions ahead of time.  Thus, my advice is to land this and then monitor for any regressions in pre-merge build times.  I suggest monitoring these three builds:


```
linux-bionic-gcc-bazel-experimental-debug 
linux-focal-clang-bazel-experimental-leak-sanitizer 
linux-focal-gcc-bazel-experimental-release 
```

https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-bionic-gcc-bazel-experimental-debug/buildTimeTrend
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-clang-bazel-experimental-leak-sanitizer/buildTimeTrend
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-gcc-bazel-experimental-release/buildTimeTrend

So, wait until CI isn't on fire for any other reasons and you have time to monitor the time graphs for a couple days in a row.  Then you can go ahead and dismiss this discussion, merge the PR, and then keep an eye on the times.

If the times show any regressions, we'll either revert this PR entirely, or if it's only certain configs that are a problem, we can opt them out of fission in the rcfiles in a new PR.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with minor nit

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587#-:-MwSpoFO8lmCE7f6LNs2:b4c2uky)* status: 2 unresolved discussions (waiting on @mwoehlke-kitware)

___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwSpU2p8FgwJeBAdxNg:b-259pbj) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
> ```
> build:asan_everything --linkopt=-fsanitize-address-use-after-scope
> # ld.gold: warning: Cannot export local symbol __asan_extra_spill_area
> build:asan_everything --linkopt=-fuse-ld=ld
> ```

nit From inspecting PR overview and commit message, unclear why this is downscoped to `asan_everything`.

Can you add mention in commit message (perhaps when merging)? My guess from conversation:
```
dynamic_analysis/bazel.rc: Fix typo for errant `build:asan` (should have been `build:asan_everything`)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @mwoehlke-kitware)

___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwUH7AZCupL5gd_sl26:bxg3s03) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit From inspecting PR overview and commit message, unclear why this is downscoped to `asan_everything`.

Can you add mention in commit message (perhaps when merging)? My guess from conversation:
```
dynamic_analysis/bazel.rc: Fix typo for errant `build:asan` (should have been `build:asan_everything`)
```
</blockquote></details>

Given the potential revert hazards with this PR, I'd say let's carve out the typo fix for the pre-existing settings in a separate PR ahead of this one, merge that right away, and then we'll feel safe that this PR is only about one topic at a time.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwXSpEL21bVTQHpOSUM:b-iy885s) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given the potential revert hazards with this PR, I'd say let's carve out the typo fix for the pre-existing settings in a separate PR ahead of this one, merge that right away, and then we'll feel safe that this PR is only about one topic at a time.
</blockquote></details>

Okay, I missed this. See #16646. This can be rebased after that lands.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwXbu0HAbg_7AqxPq_F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay, I missed this. See #16646. This can be rebased after that lands.
</blockquote></details>

Done.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwXvLCd3V7CIbxFnifn:bncvegj) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rebased.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[tools/dynamic_analysis/bazel.rc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwSpU2p8FgwJeBAdxNf:-MwY19ph13FVVKUQIEMc:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/24cfd4c01cfd44a6194107f798a05a3a3344b9c2/tools/dynamic_analysis/bazel.rc#L79)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Rebased.
</blockquote></details>

OK Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwbGQHp80gTTi6zDdR6:-MwbGQHp80gTTi6zDdR7:bf7md6y) (no related file):*
Working

Does this break coverage builds?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 2 unresolved discussions (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwbGQHp80gTTi6zDdR6:-MwbN5o6Dm_cLM9k-If6:bunr3gd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Does this break coverage builds?
</blockquote></details>

Can I ask someone from Kitware to manually test the https://drake.mit.edu/bazel.html#kcov instructions, to make sure we still get coverage info versus this PR?

---

**Comment by mwoehlke-kitware** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwbGQHp80gTTi6zDdR6:-MxFxevL3qcbFpezPsSS:b-ft1bsz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can I ask someone from Kitware to manually test the https://drake.mit.edu/bazel.html#kcov instructions, to make sure we still get coverage info versus this PR?
</blockquote></details>

From `bazel test --config=kcov common:polynomial_test`:


---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-MwbGQHp80gTTi6zDdR6:-MxFyCp5-qdmM5L8PSyT:b9q2fmi) (no related file):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

From `bazel test --config=kcov common:polynomial_test`:


</blockquote></details>

OK Looks like it's working fine.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16587#-Mw7RLTP5vl-GccGoS_C:-MxugnotAvEwF2MUfsI_:b-sn3jyl) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here's what I'd like to do.

I don't think there's any great way to test this for CI performance regressions ahead of time.  Thus, my advice is to land this and then monitor for any regressions in pre-merge build times.  I suggest monitoring these three builds:


```
linux-bionic-gcc-bazel-experimental-debug 
linux-focal-clang-bazel-experimental-leak-sanitizer 
linux-focal-gcc-bazel-experimental-release 
```

https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-bionic-gcc-bazel-experimental-debug/buildTimeTrend
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-clang-bazel-experimental-leak-sanitizer/buildTimeTrend
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-gcc-bazel-experimental-release/buildTimeTrend

So, wait until CI isn't on fire for any other reasons and you have time to monitor the time graphs for a couple days in a row.  Then you can go ahead and dismiss this discussion, merge the PR, and then keep an eye on the times.

If the times show any regressions, we'll either revert this PR entirely, or if it's only certain configs that are a problem, we can opt them out of fission in the rcfiles in a new PR.
</blockquote></details>

@betsymcphail to monitor...

---

**Review by BetsyMcPhail — COMMENTED** [review]
> Dismissed @jwnimmer-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16587)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
