### PR TITLE
[workspace] Upgrade scs_internal to latest release 3.2.7

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
The commit message subject line should be the PR title.

The commit message body should be empty (except for any authorship credits).

Towards #21759.

This skips over 3.2.6, where we reported a bug upstream at https://github.com/cvxgrp/scs/issues/284.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21797)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please.

**Comment by jwnimmer-tri** [comment]
FYI I can look at this next week, unless someone else wants to beat me to it.  (I don't think it's any particular hurry.)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review please (in particular the `norm_inf.patch`).

+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21797)* status: LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai,xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21797)* status: LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai,xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21797)* status: LGTM missing from assignees hongkai-dai,xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21797#-:-O5EDh7JD_8Gk1Izqhj2:b-cxwtpw)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Comment by jwnimmer-tri** [comment]
-@hongkai-dai no longer needed, upstream has accepted the patch.

**Pull request merged**
