### PR TITLE
Suppresses console output of speed_bump.obj genrule.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5726)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Comment by liangfok** [comment]
I checked https://drake-jenkins.csail.mit.edu/job/linux-gcc-bazel-experimental/3475/consoleFull and verified that the "Loading road geometry" and "Generating OBJ" do not appear anymore.

Thus:

+@maddog-tri for feature review please.
+@ggould-tri for platform review please.
+@jwnimmer-tri for car review please.

Thanks.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzHgtacgIK4r7Ntla9:b-spe7g0)*

**Comment by ggould-tri** [comment]
Isn't this exactly the benefit that using different log levels should be giving us?  Why not drop the log level and have a general-purpose log level config flag?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzJsBnr9uT6DksSyDa:b-kg0vb3)*

**Comment by liangfok** [comment]
Good question. I'll increase the log levels of the errors to error level and increase the log level to warn (the level above info).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzKWGczMZtRmghdRGa:bx0jj34)*

**Comment by jwnimmer-tri** [comment]
The reason to change the genrule is that, per Bazel docs, a genrule should _never_ emit any text _no matter what_ unless the exitcode is non-zero.  So whether or not we change the program's output, the genrule fixup needs to go in.

**Comment by liangfok** [comment]
I tried changing the genrule but it did not work. Will try again.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzLeu9pMOVPNHAk0Su:bwkam8u)*

**Comment by ggould-tri** [comment]
So the command line flag should turn the spdlog level to near-total silence, presumably.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzLhnd0kHatKVtrsc6:b-jbyhjm)*

**Comment by jwnimmer-tri** [comment]
Oh, I didn't even read the PR before I posted -- sorry!  Yes, the current PR is weird, I agree with Grant.

**Comment by liangfok** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzOe_Blvd5tXw3npEj:b-896fix)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzOwJXCJMlisiqxRTH:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/yaml_to_obj.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-KgzSWi1wEEe-ZUupbF_:-KgzSWi2upbpVrC-Kdfn:boqi06) ([raw file](https://github.com/robotlocomotion/drake/blob/68c67db9d0e1223ebb246629ff7d2d6e2e361256/drake/automotive/maliput/utility/yaml_to_obj.cc#L28)):*
> ```cpp
>               " direction in the rendered mesh covering the road surface");
> DEFINE_bool(suppress_info_messages, false, "Whether to suppress the info "
>             "messages (error messages will still appear).");
> ```

Please use `drake/common/text_logging_gflags.h` for consistency in melding spdlog controls into a gflags command-line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-KgzSf89hOXEPfNr900j:b-8ewamd)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/yaml_to_obj.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-KgzSWi1wEEe-ZUupbF_:-KgzStCtrXvZzLm11x6U:b-4pdwgk) ([raw file](https://github.com/robotlocomotion/drake/blob/68c67db9d0e1223ebb246629ff7d2d6e2e361256/drake/automotive/maliput/utility/yaml_to_obj.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please use `drake/common/text_logging_gflags.h` for consistency in melding spdlog controls into a gflags command-line.
</blockquote></details>

Oh hey, I had no idea that existed!  Go Drake!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/yaml_to_obj.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-KgzSWi1wEEe-ZUupbF_:-KgzY7_FZcBkQixGzt9Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68c67db9d0e1223ebb246629ff7d2d6e2e361256/drake/automotive/maliput/utility/yaml_to_obj.cc#L28)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Oh hey, I had no idea that existed!  Go Drake!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-Kgza2Nv6FvJ4EP6HGPD:bnfp4nl)*

**Comment by liangfok** [comment]
I doubled checked that the following console log is clean of the info messages: https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/3436/consoleFull

**Comment by maddog-tri** [comment]
:lgtm:  (Though, I will say that with this setup (with the output being supressed at the source), if generation does fail with a non-zero exit code, then the suppressed output will not magically appear.  This is different from how compilation and tests operate, in which all the output is still produced but buffered off-screen until there is a failure, at which point all the gory details from that run are available to the user and/or the CI logs.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5726#-:-Kh2v9aqmz4txU8HQvHM:bng5fng)*

**Comment by liangfok** [comment]
I initially tried modifying the genrule's command to have `( realcommand 2>&1 > log.txt ) || (cat log.txt && false)` but that didn't work. I'm going to merge this now; maybe we can revisit in a future PR to get _all_ of the output if a non-zero return value occurs.

**Pull request merged**
