### PR TITLE
[doc] Clarify monthly upgrade procedure

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Inspired by #17119.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17135)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17135#-:-N1eV0P-6cRu-mD-en51:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/workspace/README.md` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17135#-N1eVUDM5e3riY_Ii_Be:-N1eVUDM5e3riY_Ii_Bf:bst844l) ([raw file](https://github.com/robotlocomotion/drake/blob/fba922fca1a02265dba584098db374b856399fb8/tools/workspace/README.md#L112)):*
> ```Markdown
> stay on top of problematic changes from upstream. If we discover such problems,
> we want to bring them to the attention of the feature owner; their steering
> should provide the most efficient path to resolve the problem.
> ```

minor:  This seemed a bit wall-of-text-y to me; see a proposed phrasing below to break it up and make it a bit more declarative.

Author's discretion -- the existing text isn't bad or confusing, I just found it a bit roundabout.



_Suggestion:_
```Markdown
For non-trivial changes (i.e., changes beyond version
numbers, checksums, or trivial fixups patching files or code spelling), do not
attempt to fix the problems just because you are accountable for the routine
upgrade procedure. Instead:
* open an issue about the need for an
  upgrade of that one specific external,
* assign it to the feature owner associated
  with that external (to find out who that is, you can ask for help in the drake
  developers slack channel for ``#build``), and
* omit it from the monthly upgrade
  pull request.
The main objective of the monthly upgrade is to ensure that we
stay on top of problematic changes from upstream. When we discover problems,
we want to bring them to the attention of the feature owner who can
find the most efficient path to resolve the problem.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17135)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),BetsyMcPhail (waiting on @ggould-tri)

___
*[`tools/workspace/README.md` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17135#-N1eVUDM5e3riY_Ii_Be:-N1eoz49DBGyqoKQy9p3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fba922fca1a02265dba584098db374b856399fb8/tools/workspace/README.md#L112)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This seemed a bit wall-of-text-y to me; see a proposed phrasing below to break it up and make it a bit more declarative.

Author's discretion -- the existing text isn't bad or confusing, I just found it a bit roundabout.
</blockquote></details>

Done.

**Pull request merged**
