### PR TITLE
Add more operator== overloading between symbolic matrix/array.

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5468)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-Keu582uOpI37pi-1cSx:b7riqq)*

**Comment by soonho-tri** [comment]
@RussTedrake , FYI, we can write the following when it's landed:
```c++
const symbolic::Formula f{x0_var == x0};
```

instead of 
```c++
const symbolic::Formula f{(x0_var).cast<symbolic::Expression>() == x0.cast<symbolic::Expression>()};
```

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-KeuAXx0eix6Cj-tOMBg:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review please.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-KeuAZ1sjTRFwwRabanq:b-irfx5k)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuJ1UMN-sLqAAqtwJI:-KeuJ1UNeSJ-_vy2mERU:b-6s7y8u) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L295)):*
> ```objc
> /// Eigen.
> ///
> ///    - Eigen::Array<Variable> == Eigen::Array<Variable>
> ```

This seems bad -- equality between `Variable`s isn't `bool`.  Am I misunderstanding?  It seems like a landmine.

---

*[drake/common/symbolic_formula.h, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuIkQBIws-5OgYPJgZ:-KeuIkQC8dmHmBM4iOpf:b-31sqwe) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L317)):*
> ```objc
>          // Case: EA<double> == EA<Var>
>          (std::is_same<typename DerivedA::Scalar, double>::value &&
>           std::is_same<typename DerivedB::Scalar, Variable>::value)),
> ```

This is both heroic and horrifying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuJ1UMN-sLqAAqtwJI:-KeuMfDcsilgxO92l_R2:b-qewcom) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L295)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems bad -- equality between `Variable`s isn't `bool`.  Am I misunderstanding?  It seems like a landmine.
</blockquote></details>

I think my comments in the code are not so much clear. We do have the following:
```c++
 operator== : Eigen::Array<Variable> x Eigen::Array<Variable> -> Eigen::Array<bool>
```
as we have it in the table above. It's just the case that Eigen already takes care of this by having the following rule: 
```c++
 operator== : Eigen::Array<T> x Eigen::Array<T> -> Eigen::Array<bool>
```
and what I'm adding here doesn't touch the existing one.

---

*[drake/common/symbolic_formula.h, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuIkQBIws-5OgYPJgZ:-KeuNFQTKrbiT7yGbCFo:b-63n59q) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L317)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is both heroic and horrifying.
</blockquote></details>

I agree that it's ugly and I'm trying to find a better alternative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by RussTedrake** [comment]
n.b. -- very very excited to see this. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-Kf1PC-so2loq4963J9d:b-dthi39)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuJ1UMN-sLqAAqtwJI:-Kf6fMTtrIB80eEnGh7y:bwrpq32) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L295)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think my comments in the code are not so much clear. We do have the following:
```c++
 operator== : Eigen::Array<Variable> x Eigen::Array<Variable> -> Eigen::Array<bool>
```
as we have it in the table above. It's just the case that Eigen already takes care of this by having the following rule: 
```c++
 operator== : Eigen::Array<T> x Eigen::Array<T> -> Eigen::Array<bool>
```
and what I'm adding here doesn't touch the existing one.
</blockquote></details>

I agree that's what we have; I'm not convinced it's correct -- I would have expected `Array<Formula>` because a single evaluation cannot tell you whether two variables are equal.

If you are confident that `Array<Variable> == Array<Variable>` *should* yield `Array<bool>` then I am wrong and the code above is correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuJ1UMN-sLqAAqtwJI:-Kf7-5g0h26PYAaiU4th:b-v2i0uq) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L295)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I agree that's what we have; I'm not convinced it's correct -- I would have expected `Array<Formula>` because a single evaluation cannot tell you whether two variables are equal.

If you are confident that `Array<Variable> == Array<Variable>` *should* yield `Array<bool>` then I am wrong and the code above is correct.
</blockquote></details>

I've thinking about it and now I agree with you. I'll push a new commit which changes this part. Thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by soonho-tri** [comment]
Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---

*[drake/common/symbolic_formula.h, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuIkQBIws-5OgYPJgZ:-Kf897AmdzcOoxiBjd4Y:b-ir8k53) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L317)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I agree that it's ugly and I'm trying to find a better alternative.
</blockquote></details>

FYI, now it's using `decltype` trick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Comment by soonho-tri** [comment]
So far we have the following operators for `symbolic::Variable` (a.k.a. DecisionVariable):

```c++
operator== : Variable x Variable -> bool   // checks two IDs
operator< : Variable x Variable -> bool   // compare two IDs
```

I understand that it's convenient to have the above, but it's not consistent with the corresponding operators of `symbolic::Expression`. I think it's important to have the consistency between the two since we have an implicit conversion from `symbolic::Variable` to `symbolic::Expression`.

In this PR, we have the following:

```c++
operator== : Variable x Variable -> Formula
operator< : Variable x Variable -> Formula

Variable::equal_to : Variable -> bool    // checks two IDs
Variable::less: Variable -> bool   // compare two IDs
```

I've updated the existing implementations/tests accordingly. PTAL.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-Kf89U0hYXao8X7ksgzW:b-hlb7e7)*

**Comment by ggould-tri** [comment]
I think this is right approach.  :lgtm: 

---

Reviewed 2 of 2 files at r2, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-KeuIkQBIws-5OgYPJgZ:-Kf8D4JM55lf6wCFAU10:bsdxnx9) ([raw file](https://github.com/robotlocomotion/drake/blob/4d21995e7d622bf7e54439cfe3016fe07baa4430/drake/common/symbolic_formula.h#L317)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, now it's using `decltype` trick.
</blockquote></details>

Wow!  Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-Kf8BmX010nbdZRkvVT0:b2py10w)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  linux-gcc-experimental-matlab please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468#-:-Kf8In8mHuOcAip2zoik:b-cfid6m)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r2, 14 of 14 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5468)*

**Pull request merged**
