### PR TITLE
render_vtk: Re-expose internal_render_engine_vtk.h

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Re-admits Anzu abuse

Per comment in #17812
For Anzu PR #9428

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17839)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for both reviews, please
Not pretty, but it unbreaks Anzu for the time being.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17839#-:-NBECyKHDnkparuvDCaN:b-qud5gi)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
According to Anzu CI, this doesn't actually resolve the problem?

**Comment by EricCousineau-TRI** [comment]
ooh, good point. I think I have a fix, but I like the solution / alternative you have as well! Down for either.

**Comment by EricCousineau-TRI** [comment]
closed in lieu of alternate

**Pull request closed without merging**
