### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/RobotLocomotion/models/pull/66

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

I did ` bazel run //tools:model_visualizer -- package://drake_models/franka_description/urdf/panda_arm_hand.urdf` for all four URDF files to confirm.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410#-:-NxP9YeO-tmRPjXFuBNx:beyfh12)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410#-:-NxPAQLTBt82GqHJr5bC:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21410#-NxPAOfs-kSC2L6Jy13L:-NxPAOft2-aXfDeEUO6U:b-ebd2w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/312f5a1917208840f5d0ca17ee233dc7b3f9ecbb/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "26a9827135e53c337daa8cb30c4cf1f14045b93b",
> ```

Working

Needs real sha

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending the real sha if that's not it

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410#-:-NxPXbM8959gC7Y0oLpS:b9tq48k)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21410#-NxPAOfs-kSC2L6Jy13L:-NxPnoqt-hy14Up8f5FY:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/241e276f59ab72346d670abed57aa458e62541a9/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs real sha
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21410)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

**Pull request merged**
