### PR TITLE
Move rotmat2quat from rotation_matrix_deprecated.h to RotationMatrix class

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8345)

### CODE REVIEW

**Comment by sherm1** [comment]
@kunimatsu-tri -- in this PR, Paul @mitiguy adds a check that a rotation matrix is valid. In CI it fails in debug builds because rgbd_camera_publish_lcm_test generates a bad rotation in ViewerDrawTranslator::Serialize() (line 64 ish). After some pain we figured out the rotation matrix was all-NaN. That was because the q's going into doKinematics() were all NaN. At that point we are stuck because we're not sure where those q's came from. Can you shed some light on this?

Thanks, Sherm & Paul

**Comment by kunimatsu-tri** [comment]
I'm happy to weigh in.

The places where `doKinematics()` is called are:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_camera.cc#L174
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_camera.cc#L189

and  the `q` should be coming from `RigidBodyTree` which is connected to `RgbdCameraDiscrete` system here:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_camera_publish_lcm_example.cc#L165

Does this help?

**Comment by sherm1** [comment]
Thanks, Kuni. We can see that the original Context is uninitialized here:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_camera_publish_lcm_example.cc#L193
but if we set it to q=0001000 v=000000 we still get NaNs. (Setting it to all zero did change the behavior but I think that's because 0000 is an illegal quaternion.)

The actual place where doKinematics() is fed NaNs is neither of the ones you pointed to. Instead it occurs here:
https://github.com/RobotLocomotion/drake/blob/master/multibody/rigid_body_plant/viewer_draw_translator.cc#L59

It is hard for us to figure out how the q's get from the test main program into that ViewerDrawTranslator::Serialize() method. Do they get passed through LCM first? Not clear how they end up NaN though it seems very reproducible in Debug build.

**Comment by kunimatsu-tri** [comment]
Confirmed that we are getting NaNs for the third objects in the scene. Let me dig in.

image

**Comment by mitiguy** [comment]
Kuni, I just reverted one line of viewer_draw_translater.cc so it calls  rotmat2quatOld  instead of rotmat2quat.
To see the error, just replace rotmat2quatOld with rotmat2quat.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-:-L7XFD7cZ2LVkaedak1t:bmury0h)*

**Comment by kunimatsu-tri** [comment]
Thanks Paul for the heads up!

**Comment by kunimatsu-tri** [comment]
The object that has NaNs for its pose is coming from `box.sdf` located [here](https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/test/models/box.sdf) and  loaded [here](https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_camera_publish_lcm_example.cc#L97).

But I don't still know why this happens. At the beginning of the simulation, its pose seems to be correct. Then, it becomes NaNs.

That LCM message is published by `DrakeVisualizer` and probably not related to `RgbdCamera`.

**Comment by kunimatsu-tri** [comment]
Sherm and Paul,

This issue might take time for me to investigate and find a solution.  So, please go ahead with the PR by leaving a TODO comment as well as the issue # at where rotmat2quatOld is called.

**Comment by sherm1** [comment]
Thanks, Kuni -- much appreciated!

**Comment by mitiguy** [comment]
Feature review: +@kunimatsu-tri 
Platform review +@sherm1 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 402 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-L7gFkLjYq8oG5-lF__6:-L7gFkLjYq8oG5-lF__7:bx6lw37) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix.h#L402)):*
> ```objc
>     return kInternalToleranceForOrthonormality_;
>   }
> ```

Note to reviewer: This code is mostly copy/paste from the function rotmat2pry that is in 
drake/math/rotation_matrix_deprecated.h.
There are some small changes, mostly due to returning a Eigen::Quaternion rather than a Vect4.

---

*[math/test/rotation_matrix_test.cc, line 415 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-L7gG3CoFm0BUsq6KM5N:-L7gG3CoFm0BUsq6KM5O:bl6cgwk) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/test/rotation_matrix_test.cc#L415)):*
> ```cpp
>   }
> }
> ```

Note to reviewer:
The following test is mostly copy/paste from drake/math/test/rotation_conversion_test.cc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-:-L7gHoBSWcAfWT2K_mGp:b-qforrt)*

**Comment by sherm1** [comment]
:lgtm: pending a few BTWs.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/rotation_matrix.h, line 403 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lH15m42seXEWLBDo9:-L7lH15m42seXEWLBDoA:blduu3o) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix.h#L403)):*
> ```objc
>   }
> 
>   /// Returns a quaternion q that represent `this` %RotationMatrix.  Since the
> ```

BTW represent->represents

---

*[math/rotation_matrix.h, line 420 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lHLnE2-gZQbWT4F_T:-L7lHLnE2-gZQbWT4F_U:b-v6bsma) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix.h#L420)):*
> ```objc
>       z = M(1, 0) - M(0, 1);
>     } else if (M(0, 0) >= M(1, 1) && M(0, 0) >= M(2, 2)) {
>       // This branch occurs if  R(0,0) is largest among the diagonal elements.
> ```

BTW R->M? (and below)

---

*[math/rotation_matrix.h, line 440 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lJthxCAMPg-_pfZC9:-L7lJthxCAMPg-_pfZCA:bizjxbf) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix.h#L440)):*
> ```objc
> 
>     // Create a quantity q (which is not yet a quaternion).
>     Eigen::Quaternion<T> q(w, x, y, z);
> ```

BTW consider saying explicitly that Eigen's constructor does not normalize.

---

*[math/rotation_matrix_deprecated.h, line 48 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lKfjd5sy-nPWvg6_x:-L7lKfjd5sy-nPWvg6_y:b-6h189x) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix_deprecated.h#L48)):*
> ```objc
>  */
> template <typename Derived>
> Vector4<typename Derived::Scalar> rotmat2quatOld(
> ```

BTW needs a comment explaining why this exists at all.
Consider making this DRAKE_DEPRECATED, then disabling the warning in the one place remaining that still has to use this method. That way no one else will accidentally call this, maybe due to copying from rgbd_camera.

---

*[math/test/rotation_matrix_test.cc, line 425 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lLLcZ56i0zZamaUVs:-L7lLLcZ56i0zZamaUVt:bez1zps) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/test/rotation_matrix_test.cc#L425)):*
> ```cpp
>   }
> 
>   void setupQuaternionTestCases() {
> ```

BTW -> SetUpQuaternionTestCases() per style guide

---

*[math/test/rotation_matrix_test.cc, line 463 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-L7lLtiL9JBd67O1t-Zq:-L7lLtiL9JBd67O1t-Zr:bz03pwa) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/test/rotation_matrix_test.cc#L463)):*
> ```cpp
>     const RotationMatrix<double> Ri(mi);
>     const Eigen::Quaterniond q_expected = Ri.ToQuaternion();
>     EXPECT_TRUE(AreQuaternionsEqualForOrientation(qi, q_expected, tolerance));
> ```

BTW The original quaternions are far from normalized (+/- 1e-3). I guess the test method is not sensitive to that. Would be good to add a comment explaining that -- I was confused for a while about why they would match.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8345#-:-L7lMPzL98XGblT3YQwR:b1favup)*

**Comment by kunimatsu-tri** [comment]
:lgtm: Thanks @mitiguy for making this change!

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[math/rotation_matrix.h, line 414 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-L7k_iX78ImZZP0_9TiY:-L7k_iX78ImZZP0_9TiZ:b-d0eevh) ([raw file](https://github.com/robotlocomotion/drake/blob/549de8db723e2a6dcca96ce964b39267cb62ab3d/math/rotation_matrix.h#L414)):*
> ```objc
>     const T trace = M.trace();
>     if (trace >= M(0, 0) && trace >= M(1, 1) && trace >= M(2, 2)) {
>       // This branch occurs if the trace is larger than any diagonal element.
> ```

BTW, thank you for adding these comments!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-:-L7lndl5pdSq87naDSpz:btckrhr)*

**Comment by sherm1** [comment]
Looks great -- thanks. One CI failure: python is claiming there were two "import warnings". Not sure if that's related to the new deprecated stuff?

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8345#-:-L8-b7M7GPEvwY7us-8q:bvuikgj)*

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by mitiguy** [comment]
Reviewed 1 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8345)*

**Pull request merged**
