### PR TITLE
Fix determination of MATLAB Java version for Windows

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3195)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPZ4fL5FRwI1fjMs-Uq:-KPZ4fL5FRwI1fjMs-Ur:br02sy2) ([raw file](https://github.com/robotlocomotion/drake/blob/949cca50cb8306341979292ab8fe8ae346755f32/cmake/config.cmake#L51)):*
> ```CMake
>     execute_process(
>       COMMAND ${MATLAB_EXECUTABLE} ${_args} -r "version -java,quit"
>       RESULT_VARIABLE _result
> ```

I take it the existence (and content) of the log file suffices as "success"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPZ6XHDM6sCFjH_xJ_m:bnfp4nl)*

**Comment by jamiesnape** [comment]
It does. I just followed FindMatlab.cmake.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPZ8VADT4DosfhqntAG:b-1zia4p)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
OS X errors are license server related.

**Comment by jamiesnape** [comment]
@mwoehlke-kitware feature review, @david-german-tri platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab-please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@mwoehlke-kitware feature review, @david-german-tri platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPmdzQIQ7FUFlNhzr4G:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 51 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPZ4fL5FRwI1fjMs-Uq:-KPmvwEBnf4E9SxKhMaE:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/949cca50cb8306341979292ab8fe8ae346755f32/cmake/config.cmake#L51)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I take it the existence (and content) of the log file suffices as "success"?
</details>
Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab pleas

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-32-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

**Comment by jamiesnape** [comment]
PTAL @david-german-tri. The output to look for is `The MATLAB JVM version is x.y.z` instead of `Could not determine MATLAB JVM version`.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPt2ocolvyz7iCMvOx_:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Arf, apparently github does not notify me of new commits...

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 42 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPt4bl4CpTJHUToFJtn:-KPt4bl4CpTJHUToFJto:b-rjsvwn) ([raw file](https://github.com/robotlocomotion/drake/blob/9c91d4ef600381ffcf12b7e6630fe67a778e624f/cmake/config.cmake#L42)):*
> ```CMake
> function(drake_setup_java_for_matlab)
>   if(NOT MATLAB_JVM_VERSION)
>     if(NOT MATLAB_EXECUTABLE)
> ```

Um... well, I guess it doesn't hurt, but `drake_setup_java_for_matlab` is only called from within a `if(MATLAB_EXECUTABLE)`...

---

*[cmake/config.cmake, line 60 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPt4t_eL1XGcx27puJS:-KPt4t_eL1XGcx27puJT:bk9zfxa) ([raw file](https://github.com/robotlocomotion/drake/blob/9c91d4ef600381ffcf12b7e6630fe67a778e624f/cmake/config.cmake#L60)):*
> ```CMake
>     execute_process(
>       COMMAND "${MATLAB_EXECUTABLE}" ${_args} -logfile "${_logfile}" -r "version -java,quit"
>       WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}" TIMEOUT 300
> ```

ack, must we have more than one parameter per line?

---

*[cmake/config.cmake, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPt51HBIHSb7F-W3QC5:-KPt51HCbtL6tEoeMux1:b-lurspr) ([raw file](https://github.com/robotlocomotion/drake/blob/9c91d4ef600381ffcf12b7e6630fe67a778e624f/cmake/config.cmake#L63)):*
> ```CMake
>       RESULT_VARIABLE _result OUTPUT_QUIET INPUT_FILE ${_input_file})
> 
>     if(NOT _result AND EXISTS ${_logfile})
> ```

...since I'm commenting anyway, I'd be less paranoid about `_result EQUAL 0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPt5VBFxcBF8HeQOKLY:bv5o9st)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmake/config.cmake, line 60 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPt4t_eL1XGcx27puJS:-KPt5p0UsZ-dKuNkNRTZ:b-ip33eu) ([raw file](https://github.com/robotlocomotion/drake/blob/9c91d4ef600381ffcf12b7e6630fe67a778e624f/cmake/config.cmake#L60)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> ack, must we have more than one parameter per line?
</details>
Since we have no style guide, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195)*

**Comment by mwoehlke-kitware** [comment]
:LGTM: TY!

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/config.cmake, line 58 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-KPt7gWm2WuVhJJ95EOM:-KPt7gWngnxHgUfNYlQY:b69kk3u) ([raw file](https://github.com/robotlocomotion/drake/blob/fe1433e1be76ca4e99e529c14760b17659b5d254/cmake/config.cmake#L58)):*
> ```CMake
>       RESULT_VARIABLE _result
>       OUTPUT_QUIET
>       INPUT_FILE ${_input_file})
> ```

TY :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3195#-:-KPt7plLULVsOKVYAsMZ:b-jhwd5f)*

**Pull request merged**
