### PR TITLE
Port TrajectoryCar to System2

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3204)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri for feature review, please.

@david-german-tri for review of the `leaf_system.h` changes, please.  If you'd also like to do platform please say so; otherwise I will kick it to on-call reviewer.

**Comment by david-german-tri** [comment]
:lgtm: for LeafSystem and platform review.  Woohoo!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/leaf_system.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmm6eIbtYkWPi4vXWn:-KPmm6eJAqbq_RXekWXs:b-j7qk9t) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/systems/framework/leaf_system.h#L49)):*
> ```objc
>   LeafSystem() {}
> 
>   /// Given a port descriptor, allocate the vector storage.  The default
> ```

Very nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-:-KPmmQH7ZuTD8OkVS0xR:b-qtk67j)*

**Comment by rpoyner-tri** [comment]
One casting grump, otherwise, looks great.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/examples/Cars/test/trajectory_car_test.cc, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmonPQjDFCQEtcbbBz:-KPmonPQjDFCQEtcbbC-:bt55l6y) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/examples/Cars/test/trajectory_car_test.cc#L101)):*
> ```cpp
>       ASSERT_EQ(1, all_output->get_num_ports());
>       const SimpleCarState<double>* output =
>           dynamic_cast<const SimpleCarState<double>*>(
> ```

I assume the system2 design requires casting like this? Bleh, but maybe the alternatives are worse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-:-KPmplXYjEwtch3L7tDe:bvocg9c)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/trajectory_car_test.cc, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmonPQjDFCQEtcbbBz:-KPmqEFM_47UiJH-FXfq:b-dhpcc6) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/examples/Cars/test/trajectory_car_test.cc#L101)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> I assume the system2 design requires casting like this? Bleh, but maybe the alternatives are worse.
</details>
Yes, I believe this is the current best mechanism; @david-german-tri to confirm?

You could imagine a template method sugar argument do this for us (including a `DRAKE_ASSERT`); I don't know if that's been discussed yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/trajectory_car_test.cc, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmonPQjDFCQEtcbbBz:-KPmrRGvtxx-QoVL3pdG:b-y82t2g) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/examples/Cars/test/trajectory_car_test.cc#L101)):*
> Yes, I believe this is the current best mechanism; @david-german-tri to confirm?
> 
> You could imagine a template method sugar argument do this for us (including a DRAKE_ASSERT); I don't know if that's been discussed yet.

It has been discussed, and as far as I know everyone is in favor.  It's just a question of getting around to it.  You're welcome to do so in this PR, or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/trajectory_car_test.cc, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmonPQjDFCQEtcbbBz:-KPmtNQG93qtVQtt7SA9:b-vst3xn) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/examples/Cars/test/trajectory_car_test.cc#L101)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > Yes, I believe this is the current best mechanism; @david-german-tri to confirm?
> > 
> > You could imagine a template method sugar argument do this for us (including a DRAKE_ASSERT); I don't know if that's been discussed yet.
> 
> It has been discussed, and as far as I know everyone is in favor.  It's just a question of getting around to it.  You're welcome to do so in this PR, or not.
</details>
@rpoyner-tri What do you think?  I can add to this PR if you prefer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/trajectory_car_test.cc, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-KPmonPQjDFCQEtcbbBz:-KPn0TACJqEzWTTkq2V_:b8fj6pr) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ca93794ea6922e14f62563c6016979c6ea8368/drake/examples/Cars/test/trajectory_car_test.cc#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @rpoyner-tri What do you think?  I can add to this PR if you prefer?
</details>
As long as people are aware that it's gross, I'm content not to tax this PR further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3204#-:-KPn0_VTE_kxafzo17or:bnfp4nl)*

**Pull request merged**
