### PR TITLE
Add PathParameterizedTrajectory

### PR DESCRIPTION
**Pull request by mpetersen94**
Adds a trajectory class that consists of a path and parameterization of the progress along that path.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@RussTedrake for delegation (or feature review?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816#-:-NAzMD6j0aM135cxKYIU:b38q02p)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Also beautiful.  One naming request and a few nits.  Otherwise :lgtm: 

+@xuchenhan-tri for platform review, please.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816#-:-NBMUo2KCvgbLRGMT7F_:b-3f4gdr)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`common/trajectories/path_parameterized_trajectory.h` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMS4lwDhT3CJo4oeip:-NBMS4lwDhT3CJo4oeiq:b-1avknp) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.h#L28)):*
> ```objc
>   @pre parameterization.rows() == parameterization.cols() == 1 */
>   PathParameterizedTrajectory(const Trajectory<T>& path,
>                               const Trajectory<T>& parameterization);
> ```

how about time_scaling as the name of the second argument?

since the class is called "pathparameterized", I would think "parameterization" is more linked to the path than the timing.
___
*[`common/trajectories/path_parameterized_trajectory.cc` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMTEkz5Y0DzGUwEHyX:-NBMTEkz5Y0DzGUwEHyY:b-lv2det) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.cc#L58)):*
> ```cpp
>     }
>     // Derivative is calculated using Faà di Bruno's formula with Bell
>     // polynomials: https://en.wikipedia.org/wiki/Fa%C3%A0_di_Bruno%27s_formula
> ```

btw -- nice.  TIL!



_Code quote:_
```cpp
https://en.wikipedia.org/wiki/Fa%C3%A0_di_Bruno%27s_formula
```
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMTV-6659ttiYkVDhE:-NBMTV-6659ttiYkVDhF:b-z386hp) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/test/path_parameterized_trajectory_test.cc#L24)):*
> ```cpp
> 
>     parameterization_ = PiecewisePolynomial<double>::CubicShapePreserving(
>         times, s_samples.transpose(), true);
> ```

nit -- cleaner to make s_samples a RowVectorXd?
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMU7LD3wJF2SBTOz-G:-NBMU7LD3wJF2SBTOz-H:b-kzwapo) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/test/path_parameterized_trajectory_test.cc#L66)):*
> ```cpp
>                              3 * path_.EvalDerivative(s, 2) * s_ddot * s_dot +
>                              path_.EvalDerivative(s, 3) * std::pow(s_dot, 3);
>     EXPECT_TRUE(CompareMatrices(dut_->EvalDerivative(t, 3), x_3dot, 1e-12));
> ```

btw -- nice!
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMUI0xBJ9mvftFfxuI:-NBMUI0xBJ9mvftFfxuJ:b-yq1r4n) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/test/path_parameterized_trajectory_test.cc#L76)):*
> ```cpp
>   EXPECT_TRUE(
>       dynamic_cast<const PiecewisePolynomial<double>&>(dut_->parameterization())
>           .isApprox(parameterization_, 1e-12));
> ```

nit -- these should hold with zero tolerance, no?  or is something strange happening in the isApprox method?

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @RussTedrake and @xuchenhan-tri)

___
*[`common/trajectories/path_parameterized_trajectory.h` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMS4lwDhT3CJo4oeip:-NBO7wu10oxsiSlnDdI6:b-chu8c2) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.h#L28)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

how about time_scaling as the name of the second argument?

since the class is called "pathparameterized", I would think "parameterization" is more linked to the path than the timing.
</blockquote></details>

Done! Love it!
___
*[`common/trajectories/path_parameterized_trajectory.cc` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMTEkz5Y0DzGUwEHyX:-NBOAOy172ZNjZWZwq7T:b-g67rde) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.cc#L58)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- nice.  TIL!
</blockquote></details>

Thanks! Did a bunch of digging to learn this.
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMTV-6659ttiYkVDhE:-NBOAmuFEEut-6xk3F8x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/test/path_parameterized_trajectory_test.cc#L24)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit -- cleaner to make s_samples a RowVectorXd?
</blockquote></details>

Done.
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBMUI0xBJ9mvftFfxuI:-NBOBfhfCnXiUFjRHKL5:bcstfod) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/test/path_parameterized_trajectory_test.cc#L76)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit -- these should hold with zero tolerance, no?  or is something strange happening in the isApprox method?
</blockquote></details>

Done. It was copypasta from another trajectory test.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with a few nits and two test coverage requests.

> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816#-:-NBOHbUb8yPkzx6VFdVI:bke9h9u)* status: 4 unresolved discussions (waiting on @mpetersen94)

___
*[`common/trajectories/path_parameterized_trajectory.h` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBO8HEX6HLZNdUCtxU3:-NBO8HEX6HLZNdUCtxU4:bm0utfe) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.h#L30)):*
> ```objc
>                               const Trajectory<T>& parameterization);
> 
>   PathParameterizedTrajectory(const PathParameterizedTrajectory<T>& other)
> ```

BTW, you could use copyable_unique_ptr for the member data and allow DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN. Otherwise, consider spelling out the move and assign semantics.
___
*[`common/trajectories/path_parameterized_trajectory.h` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOBGET-asjr6YxcRoe:-NBOBGET-asjr6YxcRof:b-dxgefi) ([raw file](https://github.com/robotlocomotion/drake/blob/161ee69e0b0556976a7d50a3fca7b30abf4225a3/common/trajectories/path_parameterized_trajectory.h#L75)):*
> ```objc
>   // Evaluates the Bell Polynomial B_n,k(x) for use in calculating the
>   // derivative.
>   T BellPolynomial(int n, int k, const VectorX<T> x) const;
> ```

nit, missing `&`
Also, are there any preconditions for n, k, and x?
___
*[`common/trajectories/path_parameterized_trajectory.cc` line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBODJP-6atXnFosRWud:-NBODJP-6atXnFosRWue:blrdrav) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa64fa7852b93eee4a345d484550b82da3e357b/common/trajectories/path_parameterized_trajectory.cc#L20)):*
> ```cpp
> template <typename T>
> std::unique_ptr<Trajectory<T>> PathParameterizedTrajectory<T>::Clone() const {
>   return std::make_unique<PathParameterizedTrajectory<T>>(*path_,
> ```

BTW you could invoke the copy constructor here to be more future-proof.
___
*[`common/trajectories/path_parameterized_trajectory.cc` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOHGPVD9g9MlB0L0Ma:-NBOHGPVD9g9MlB0L0Mb:bspiokq) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa64fa7852b93eee4a345d484550b82da3e357b/common/trajectories/path_parameterized_trajectory.cc#L26)):*
> ```cpp
> template <typename T>
> MatrixX<T> PathParameterizedTrajectory<T>::value(const T &time) const {
>   return path_->value(time_scaling_->value(time)(0, 0));
> ```

It's not immediately clear to me how the effect in the `warning` in the function doc is achieved. Could you add some local notes?
___
*[`common/trajectories/path_parameterized_trajectory.cc` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOENnQ32kMn44qfPgu:-NBOENnR-2kWh1PydnZ6:b-cnenl0) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa64fa7852b93eee4a345d484550b82da3e357b/common/trajectories/path_parameterized_trajectory.cc#L39)):*
> ```cpp
>   T polynomial = 0;
>   T a = 1;
>   for (int ii = 1; ii < n - k + 2; ii++) {
> ```

nit use preincrement instead (ditto throughout this file)
https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOFFu67s3BQKVaEH1L:-NBOFFu67s3BQKVaEH1M:b-z103cl) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa64fa7852b93eee4a345d484550b82da3e357b/common/trajectories/test/path_parameterized_trajectory_test.cc#L41)):*
> ```cpp
> 
> TEST_F(PathParameterizedTrajectoryTest, TestValue) {
>   for (double t = 1.0; t < 2.0; t += 0.12) {
> ```

Could you extend the test to cover time outside of the interval [start_time, end_time]?
___
*[`common/trajectories/test/path_parameterized_trajectory_test.cc` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOGUe7BDe2EgEGMYpN:-NBOGUe7BDe2EgEGMYpO:b-z103cl) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa64fa7852b93eee4a345d484550b82da3e357b/common/trajectories/test/path_parameterized_trajectory_test.cc#L48)):*
> ```cpp
> 
> TEST_F(PathParameterizedTrajectoryTest, TestDerivatives) {
>   for (double t = 1.0; t < 2.0; t += 0.12) {
> ```

Could you extend the test to cover time outside of the interval [start_time, end_time]?

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-release please

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @mpetersen94)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: 1 unresolved discussion (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`common/trajectories/path_parameterized_trajectory.cc` line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOmJdz-1OdXqMuDLao:-NBOmJdz-1OdXqMuDLap:bav6isx) ([raw file](https://github.com/robotlocomotion/drake/blob/1d6e360f0fe01e6d51a2ca223f2e87f6c58d5750/common/trajectories/path_parameterized_trajectory.cc#L4)):*
> ```cpp
> 
> #include <algorithm>
> #include <iostream>
> ```

nit not needed?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: 1 unresolved discussion (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @mpetersen94)

___
*[`common/trajectories/path_parameterized_trajectory.cc` line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17816#-NBOmJdz-1OdXqMuDLao:-NBT7Wwg04I5dqDyzg5n:bjpz51c) ([raw file](https://github.com/robotlocomotion/drake/blob/1d6e360f0fe01e6d51a2ca223f2e87f6c58d5750/common/trajectories/path_parameterized_trajectory.cc#L4)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit not needed?
</blockquote></details>

Done. Put it in for debugging and forgot to remove.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17816)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @mpetersen94)

**Pull request merged**
