### PR TITLE
Use static library for SDFormat and do not install

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #7874.

FYI @clalancette @stonier.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7905)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@clalancette for feature review.

**Comment by clalancette** [comment]
Sorry I didn't get to this yesterday, I'll take a look today.

**Comment by clalancette** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-L4HeHy7eKJnhQfvbUyJ:-L4HeHy7eKJnhQfvbUyK:b9iwuuk) ([raw file](https://github.com/robotlocomotion/drake/blob/28c48f3156cb53ed7038f88142735ee4dd0b43f5/tools/workspace/sdformat/package.BUILD.bazel#L22)):*
> ```
> package(default_visibility = ["//visibility:public"])
> 
> cc_library(
> ```

The quibble I have with doing this is that it seemed like we were trying to reduce the size of `libdrake.so` by making more libraries dynamic.  This is going the opposite way.

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-L4He1aibCtbg8YZADov:-L4He1aibCtbg8YZADow:b8wp0qu) ([raw file](https://github.com/robotlocomotion/drake/blob/28c48f3156cb53ed7038f88142735ee4dd0b43f5/tools/workspace/sdformat/package.BUILD.bazel#L156)):*
> ```
>     # compiled with different visibility settings."
>     copts = ["-w"],
>     # TODO(jamiesnape): Confirm that we actually need to install the data.
> ```

Confirmed, at least for now (see my long comment in https://github.com/RobotLocomotion/drake/issues/7874#issuecomment-362358725).  I think we can remove this TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-L4HeHy7eKJnhQfvbUyJ:-L4HiS-n53MTvOZm1Ezc:b-4j7ijr) ([raw file](https://github.com/robotlocomotion/drake/blob/28c48f3156cb53ed7038f88142735ee4dd0b43f5/tools/workspace/sdformat/package.BUILD.bazel#L22)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

The quibble I have with doing this is that it seemed like we were trying to reduce the size of `libdrake.so` by making more libraries dynamic.  This is going the opposite way.
</blockquote></details>

This is true and I don't have a good answer as to what the cutoff is between when we should make something static and when it should be shared. Since `ccd`, `fcl`, and `octomap` went in static, it kind of feels like this should be too, given the motivation is the same. I will try to get a before and after size of `libdrake.so` for release and debug for comparison.

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-L4He1aibCtbg8YZADov:-L4HiRVX022fFVyhKm2y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28c48f3156cb53ed7038f88142735ee4dd0b43f5/tools/workspace/sdformat/package.BUILD.bazel#L156)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Confirmed, at least for now (see my long comment in https://github.com/RobotLocomotion/drake/issues/7874#issuecomment-362358725).  I think we can remove this TODO.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905)*

**Comment by jamiesnape** [comment]
@clalancette Can you take another look at this? As far as size differences go, `libdrake.so` is about 0.36% bigger, so not much.

**Comment by clalancette** [comment]
Yeah, that's fine.  I wasn't *too* concerned about the increase in size; I was mostly trying to clarify the policy w.r.t. shared vs. static libraries.  Since it seems on a case-by-case basis, this is fine for now, and the code looks OK to me.  I'll mark it as LGTM.

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-:-L5np3r-I8KGfff1y9u3:bi8piy1)*

**Comment by clalancette** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-:-L5nped6d4oyQM-BWE0K:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7905#-:-L5oMj913Lqlf7Xhm--C:bnfp4nl)*

**Pull request merged**
