### PR TITLE
Simple script for doing local performance tests

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This script is a convenience utility to time a runnable bazel target across two different commits and compare the runtime. It is intended as a coarse utility to aid in evaluating efforts to improve performance.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13110)

### CODE REVIEW

**Comment by sherm1** [comment]
@EricCousineau-TRI I understand this as useful for performance work rather than trying to find a performance regression. That is, we've found a hot spot with cachegrind (e.g.) and are experimenting with various hacks to get it to run faster.

**Comment by jwnimmer-tri** [comment]
The key question for putting into master is whether >1 person plans to use (and support) it.  If no, we should not merge it.  If yes, then we should figure out how to formulate the code in an appropriate way for collaboration.

I am not doing benchmarking at this point, so I would not be a current user.

I agree with Eric that a more composable approach with more focused tools is probably better for collaboration.  The monolithic argv parsing here is already past of the point of being collaboratively maintainable.

**Comment by jwnimmer-tri** [comment]
> ...  bit of a chicken and egg problem ...

Certainly the threshold should not be that a second person is _already_ using it.  I would be content with a team member saying "I _would_ use that once its available" -- that the problem its solving, and the capabilities of the solution, are common to at least two people.

**Comment by DamrongGuoy** [comment]
I'll use it. It would save my time as I am working on profiling and speed-up contact-surface generation.

If it's not in Drake, could it be a stand-alone tool? Or it ties to Drake?

**Pull request closed without merging**
