### PR TITLE
adds multi-car simulation capabilities to automotive_demo

### PR DESCRIPTION
**Pull request by RussTedrake**
Even more fun when used with bot-lcm-tunnel so that multiple people can drive together in a demolition-derby style sim.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4516)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@liangfok for feature review
+@jwnimmer-tri for platform review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-:-KZ34aHhvJabq0QEkQZ0:b-udjeey)*

**Comment by liangfok** [comment]
:lgtm: Just a few BTW comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35H_Zx4AUVZY_bYEA:-KZ35H__WCrlTxnkO8hI:boqr4gr) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L72)):*
> ```cpp
>   if (!name.empty()) {
>     channel_name += "_";
>     channel_name += name;
> ```

BTW, the above two lines could be combined into one:

```
channel_name += "_" + name;
```

---

*[drake/automotive/automotive_simulator.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36K97ggF20pv_bL5D:-KZ36K97ggF20pv_bL5E:bckty48) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L91)):*
> ```cpp
>     // https://github.com/RobotLocomotion/drake/issues/3053 is resolved.
>     // For now, only the body names show up in the drake visualizer.
>     const auto& bodies = rigid_body_tree_->FindBaseBodies(model_instance_id);
> ```

BTW: nit: consider renaming `bodies` to be `body_indices` to more accurately reflect what it is.

---

*[drake/automotive/automotive_simulator.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35cv6Zs4yfnZyx26v:-KZ35cv6Zs4yfnZyx26w:baspnmo) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L92)):*
> ```cpp
>     // For now, only the body names show up in the drake visualizer.
>     const auto& bodies = rigid_body_tree_->FindBaseBodies(model_instance_id);
>     DRAKE_DEMAND(bodies.size() > 0);
> ```

BTW, I believe this could be made even more strict in this context since vehicle models should only have one base body:

```
DRAKE_DEMAND(bodies.size() == 1);
```

---

*[drake/automotive/automotive_simulator.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36Y5YBhj5ClhupYDa:-KZ36Y5ZWG9IuqpE4T3i:blis401) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L93)):*
> ```cpp
>     const auto& bodies = rigid_body_tree_->FindBaseBodies(model_instance_id);
>     DRAKE_DEMAND(bodies.size() > 0);
>     for (auto body : bodies) rigid_body_tree_->bodies[body]->set_name(name);
> ```

BTW: nit: consider renaming `body` to be `body_index` to more accurately reflect what it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-:-KZ362AYbTHoNHHfFAmj:b11hv8z)*

**Comment by jwnimmer-tri** [comment]
Checkpoint, since some of my comments overlap with Liang.  Still one file left.

---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36Gt0-sFI6UX7phaQ:-KZ36Gt3Nd-wjNRr8Is1:b74rx5a) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L91)):*
> ```cpp
>     // https://github.com/RobotLocomotion/drake/issues/3053 is resolved.
>     // For now, only the body names show up in the drake visualizer.
>     const auto& bodies = rigid_body_tree_->FindBaseBodies(model_instance_id);
> ```

This `auto` seems to be too obscuring of the return type, per https://google.github.io/styleguide/cppguide.html#auto.  I thought they were `RigidBody`s, not `int`s.

---

*[drake/automotive/automotive_simulator.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36ZYuPiTnCXqg2RhF:-KZ36ZYuPiTnCXqg2RhG:bfxuwgw) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L93)):*
> ```cpp
>     const auto& bodies = rigid_body_tree_->FindBaseBodies(model_instance_id);
>     DRAKE_DEMAND(bodies.size() > 0);
>     for (auto body : bodies) rigid_body_tree_->bodies[body]->set_name(name);
> ```

This accesses the `RBT::bodies` field directly; in new code, API like `get_body(int)` should be preferred.

---

*[drake/automotive/automotive_simulator.cc, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ37xuH3xtvUvnTZckR:-KZ37xuI-4gAN2UnPzT4:bw786bk) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L333)):*
> ```cpp
>   lcm_->StartReceiveThread();
> 
>   simulator_->set_target_realtime_rate(realtime_factor);
> ```

BTW I would support exposing the Simulator object outside of the AutomotiveSimulator fixture (via a getter), so that passthrough settings like this don't need to be intermediated by the AutomotiveSimulator.

(It seems like this value is okay to set even after Initialize has been called.)

---

*[drake/automotive/automotive_simulator.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35lyZgzguu4b4IRyJ:-KZ35ly_iIsXixPzE0Iv:b-wg93p9) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.h#L63)):*
> ```objc
>   /// the simulation.
>   int AddSimpleCarFromSdf(const std::string& sdf_filename,
>                           const std::string& name = "");
> ```

Missing API doc on what `name` means.

---

*[drake/automotive/automotive_simulator.h, line 126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ37k2SazXzqTVQRypb:-KZ37k2TzVqacJquyN1w:b-beg4tk) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.h#L126)):*
> ```objc
>   // AutomotiveSimulator, and our class should be AutomotiveSimulatorBuilder?
>   // Port a few more demo programs, then decide what looks best.
>   void Start(double realtime_factor = 0.0);
> ```

This should use the same name as the Simulator for this concept, which is `target_realtime_rate`.

---

*[drake/automotive/models/prius/package.xml, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35_hDz3TSemrTzIFY:-KZ35_hEoFlLoAloR-4l:b99tipd) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/models/prius/package.xml#L3)):*
> ```XML
> <package format="2">
>   <name>prius</name>
> </package>
> ```

BTW Other `package.xml` files have a lot more ROS goop in them.  Is it truly okay to use such a bare-bones one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-:-KZ38LGiu3TAsf8WF8wX:b-b8fdjp)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/models/prius/package.xml, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35_hDz3TSemrTzIFY:-KZ38wSNG2xODzWSjK4Q:b-idslav) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/models/prius/package.xml#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Other `package.xml` files have a lot more ROS goop in them.  Is it truly okay to use such a bare-bones one?
</blockquote></details>

For now, yes, since these aren't _real_ ROS packages. Other in-tree examples of such sparse `package.xml` files include:

* drake/examples/Atlas/package.xml
* drake/examples/IRB140/package.xml
* drake/examples/Valkyrie/package.xml

Once #4445 is resolved, we may need to add more info to these `package.xml` files to make them real ROS packages that are usable by other ROS packages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ38a_BrBUVJl2-RiIf:-KZ38a_BrBUVJl2-RiIg:b-beg4tk) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_demo.cc#L19)):*
> ```cpp
>               "DRIVING_COMMAND_Jeremy, and DRIVING_COMMAND_Liang)");
> DEFINE_int32(num_trajectory_car, 1, "Number of TrajectoryCar vehicles");
> DEFINE_double(realtime_factor, 1.0,
> ```

This should use the same name as the Simulator for this concept, which is `target_realtime_rate`.

---

*[drake/automotive/automotive_demo.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ39_1ZUKxxRdRC6Q5X:-KZ39_1ZUKxxRdRC6Q5Y:b74houo) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_demo.cc#L47)):*
> ```cpp
>   } else {
>     std::istringstream f(FLAGS_simple_car_names);
>     std::string s;
> ```

For both `f` and `s`; _Names should be descriptive; avoid abbreviation._
https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by RussTedrake** [comment]
Review status: 3 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ38a_BrBUVJl2-RiIf:-KZ3EH9pt_2lQYo17qmv:bexu6jy) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_demo.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should use the same name as the Simulator for this concept, which is `target_realtime_rate`.
</blockquote></details>

done.  but fwiw, this was copied from some of the other robot sims.  perhaps they should be updated, too.

---

*[drake/automotive/automotive_demo.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ39_1ZUKxxRdRC6Q5X:-KZ3FUfH4pHa2XhL5mDf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_demo.cc#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For both `f` and `s`; _Names should be descriptive; avoid abbreviation._
https://google.github.io/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35H_Zx4AUVZY_bYEA:-KZ3FbSx3k4rDD2I7MkZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L72)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, the above two lines could be combined into one:

```
channel_name += "_" + name;
```
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36Gt0-sFI6UX7phaQ:-KZ3FteNKJDXxP3zr2PV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This `auto` seems to be too obscuring of the return type, per https://google.github.io/styleguide/cppguide.html#auto.  I thought they were `RigidBody`s, not `int`s.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36K97ggF20pv_bL5D:-KZ3FuBjUIyueetXZN_L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L91)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: consider renaming `bodies` to be `body_indices` to more accurately reflect what it is.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35cv6Zs4yfnZyx26v:-KZ3G4uJtXZjR3dnmvna:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I believe this could be made even more strict in this context since vehicle models should only have one base body:

```
DRAKE_DEMAND(bodies.size() == 1);
```
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36Y5YBhj5ClhupYDa:-KZ3G67x2C4rJSIMp03v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L93)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: consider renaming `body` to be `body_index` to more accurately reflect what it is.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36ZYuPiTnCXqg2RhF:-KZ3GN4f851nmFY2F3Ja:bizdf44) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This accesses the `RBT::bodies` field directly; in new code, API like `get_body(int)` should be preferred.
</blockquote></details>

agreed, but we would need to add a get_mutable_body accessor.  i cannot use the const return.

---

*[drake/automotive/automotive_simulator.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ35lyZgzguu4b4IRyJ:-KZ3HJNbEpSjR54qdct3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.h#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing API doc on what `name` means.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ37k2SazXzqTVQRypb:-KZ3HihQTdfGNo_oldCg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.h#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should use the same name as the Simulator for this concept, which is `target_realtime_rate`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3IkEnyp1gydJdZK8u:-KZ3IkEnyp1gydJdZK8v:bbseiev) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.cc#L94)):*
> ```cpp
>     DRAKE_DEMAND(body_indices.size() == 1);
>     for (auto index : body_indices)
>       rigid_body_tree_->bodies[index]->set_name(name);
> ```

BTW, since there is only one index in `body_indices`, this `for` loop can be replaced with:

```
body_indices.at(0)->set_name(name);
```

---

*[drake/automotive/automotive_simulator.h, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3J5vkOxg6Gat_ybvZ:-KZ3J5vl_5OPMs-o4v1z:bmnotsh) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.h#L61)):*
> ```objc
>   /// @param name If this string is non-empty, then the simple car will
>   /// subscribe
>   /// to a channel DRIVING_COMMAND_[@p name] instead of the default
> ```

BTW, odd line break. Also consider deleting "a" before "channel".

---

*[drake/automotive/automotive_simulator.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3JIpTfJ9L0ENEs01E:-KZ3JIpTfJ9L0ENEs01F:b-tr9tbx) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.h#L62)):*
> ```objc
>   /// subscribe
>   /// to a channel DRIVING_COMMAND_[@p name] instead of the default
>   /// DRIVING_COMMAND
> ```

BTW, missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3IkEnyp1gydJdZK8u:-KZ3L5G4OOuteuJkRlkL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.cc#L94)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, since there is only one index in `body_indices`, this `for` loop can be replaced with:

```
body_indices.at(0)->set_name(name);
```
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3J5vkOxg6Gat_ybvZ:-KZ3L6r9NveqShL0rXVm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.h#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd line break. Also consider deleting "a" before "channel".
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ3JIpTfJ9L0ENEs01E:-KZ3L77MXCuz4Zmx1S7Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90c1bed9496aad89cd79d224d1b7a5743cff1fa/drake/automotive/automotive_simulator.h#L62)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing period at end of sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ38a_BrBUVJl2-RiIf:-KZ3MpJHiemarjFpXV4Y:b-pbdqz3) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_demo.cc#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

done.  but fwiw, this was copied from some of the other robot sims.  perhaps they should be updated, too.
</blockquote></details>

Agreed.

---

*[drake/automotive/automotive_simulator.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-KZ36ZYuPiTnCXqg2RhF:-KZ3NDSW2rk5NR11W9Si:b-oqsh5r) ([raw file](https://github.com/robotlocomotion/drake/blob/3fef6f7f58f0b9c5943d6a31bc0a4b99ecaf2f26/drake/automotive/automotive_simulator.cc#L93)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

agreed, but we would need to add a get_mutable_body accessor.  i cannot use the const return.
</blockquote></details>

Wow :facepalm:.  Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4516#-:-KZ3NvaQOocA3G3ymr1w:bnfp4nl)*

**Comment by david-german-tri** [comment]
Jenkins was lying to us: a test failed on this PR.  https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-experimental-release-1783&field2=buildstarttime&compare2=84&value2=now

Kudos to @liangfok for identifying this.  He is AFK at the moment so I'm going to look at fixing forward.

**Comment by liangfok** [comment]
I believe the problem is the use of relative paths to the model files here: https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/rigid_body_system1/test/CMakeLists.txt

One solution is to switch to a "SearchingInRosPackage()" parser method and to manually populate a PackageMap object using https://github.com/RobotLocomotion/drake/blob/master/drake/examples/examples_package_map.h.

**Comment by liangfok** [comment]
Another option would be to first determine the absolute path to the model file and then crawl up the directory tree using that absolute path.

**Comment by jwnimmer-tri** [comment]
Might as well just revert the model-edit part of this for now.  We don't _really_ need multiplayer objs rendering in director with any urgency.

**Comment by RussTedrake** [comment]
@liangfok -- would things have worked if we had simply added the package:// to the urdf as well as the sdf?

**Comment by liangfok** [comment]
Unfortunately, no. Currently, the filename is directly consumed by TinyXML's [XMLDocument::LoadFile()](https://github.com/RobotLocomotion/drake/blob/7c61bee382ff22982991829001f7c81162e5124b/drake/thirdParty/zlib/tinyxml2/tinyxml2.h#L1626), which does not understand the meaning of `package://`.

It's an interesting idea though. Let me look into this more to see if we want to support the `package://[package_name]/path/to/model/file` syntax for specifying a model file. One benefit of doing this is we'll no longer need the `WORKING_DIRECTORY` argument that's [currently being used](https://github.com/RobotLocomotion/drake/blob/51a30cbe62238d37f3398a80134bef2cfd0aee1b/drake/multibody/rigid_body_system1/test/CMakeLists.txt#L24) in the unit test's `CMakeLists.txt` entry. One challenge with doing this, however, is the `PackageMap` will need to be manually populated because the current "crawl-up" mechanism for automatically populating the `PackageMap` is based on the known location of the model file.

Given then above, I think I will approach the problem in at least two spirals. The first takes the easiest route of simply populating the `PackgeMap` using [AddExamplePackages()](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/examples_package_map.h). The second spiral will include something more automated.

**Comment by jwnimmer-tri** [comment]
I fail to see why `AddExamplePackages` would be needed.  We know the location of the SDF and the URDF, and so we should default-populate the package map from those starting points.

**Comment by jwnimmer-tri** [comment]
Also, I am unconvinced that fixing this now is of merit.  We will have a rendering API that will enable us to share models.  Why do we need to fix the visualizer for a a multi-computer game toy, using short-term hacks?

**Comment by liangfok** [comment]
Is there an officially approved way for a C++ program in Drake to query its current working directory?

**Comment by jwnimmer-tri** [comment]
The current working directory is known as `.`.

**Comment by liangfok** [comment]
How do I expand "." to the full path in C++ Drake?

**Comment by sherm1** [comment]
Since we don't support Windows, Posix standard `getcwd()` is available. It would be nice to have a layer of insulation from that though, which I believe C++17 will provide. So maybe getcwd + TODO would be adequate for now?

**Comment by liangfok** [comment]
Thanks. Per @jwnimmer-tri's comment in #4576, we're using [spruce::path::setAsCurrent()](https://github.com/RobotLocomotion/drake/blob/20073f05733c47086fe4104e542f160444f8735c/drake/thirdParty/bsd/spruce/spruce.hh#L65), which is based on [getcwd()](https://github.com/RobotLocomotion/drake/blob/20073f05733c47086fe4104e542f160444f8735c/drake/thirdParty/bsd/spruce/spruce.cc#L55).

**Comment by RussTedrake** [comment]
@jwnimmer-tri -- i agree it's not a priority.  but we should (at some point) decide on the appropriate action if a mesh (or other subfile) file appears in a urdf/sdf using a relative path.  seems like we have two viable options: 
1) assume it is relative to the location of the urdf/sdf 
2) say it's a defect. you must use package://  . 
I think 2 might be too strict since we want to make it easy to support urdf/sdf generated by others.

I would think that assuming the mesh is relative to the path from which the executable is launched is not a good option.

**Comment by jwnimmer-tri** [comment]
> assume it is relative to the location of the urdf/sdf

Isn't that how the code already works?  The `prius.sdf` says (said) `prius.dae` and it loaded fine (when running on a single host).

> I think 2 might be too strict since we want to make it easy to support urdf/sdf generated by others.

Agreed.

> I would think that assuming the mesh is relative to the path from which the executable is launched is not a good option.

Was that proposed somewhere?  I might have missed it.

**Comment by RussTedrake** [comment]
> Was that proposed somewhere? I might have missed it.

Apologies if it was not.  I admit I'm having trouble following this discussion since it's happening in so many places (and I'm on the road).  All of the talk about '.', getcwd, and WORKING_DIRECTORY, made be think it might have been.

**Comment by jwnimmer-tri** [comment]
I admit the discussion is kind of a disaster.

**Comment by liangfok** [comment]
> > I would think that assuming the mesh is relative to the path from which the executable is launched is not a good option.
> >
> Was that proposed somewhere? I might have missed it.

Maybe I can shed some light: Last Thursday @RussTedrake and I discovered that referencing a mesh using `package://[package name]/path/to/mesh/[mesh file name].dae` worked in `DrakeVisualizer` _even if it was not on the same computer as the URDF and SDF file containing the reference_. This is as opposed to simply sending `[mesh file name].dae`, which does not work.

It's important to note that `DrakeVisualizer` does not read or parse URDF or SDF models (or files). It simply receives `lcmt_viewer_load_robot` and `lcmt_viewer_draw` messages that contain visualization information (not the actual model). Thus it has no notion of a URDF or SDF "file".

One of the data structures contained within an `lcmt_viewer_load_robot ` message is `lcmt_viewer_geometry_data.lcm`. It contains a string that references a mesh file to be visualized. If this string is set to a value like `[file name].dae`, it will not know where to find the file (since it doesn't know the source URDF or SDF file), and will thus fail. However, if `DrakeVisualizer` receives a value like `package://[package name]/path/to/mesh`, it is able to find the file, presumably because it has internally crawled for `package.xml` files.

Given the above, it is undesirable to reference a mesh file relative to the location of the URDF or SDF file that contains the reference, since the visualizer does not know which file referenced the mesh.

As an aside, I believe the above semantics match that in ROS. In the ROS world, the content of the URDF or SDF file is loaded onto a ROS parameter server. This server is accessed by numerous nodes that can potentially be running on different machines (via a network connection). Thus, these ROS nodes also have no notion of a "file" since they access the model directly from a server.

**Comment by RussTedrake** [comment]
@liangfok -- the reason the drakevisualizer worked before (on a single machine) was because the parsers in drake would change the relative file name to an absolute filename.  are you proposing (1) or (2) from my list above, or something else?

**Comment by liangfok** [comment]
I propose supporting both (1) and (2) but with differing restrictions:

Restrictions on (1):
a. It will only work when everything is running on the same machine.
b. It will only work when the nodes have access to the file (and not just the text contained within the file).
b. All referenced meshes are within the same directory or sub-directories of the URDF / SDF file.

Restrictions on (2):
1. All nodes that make use of the URDF / SDF model must have access to local copies of the packages cited by the URDF / SDF.

**Comment by jwnimmer-tri** [comment]
That all seems sensible, and I think is how things operate right now.

I think we could relax some of the restrictions over time, but no need to worry about that for now.

**Comment by liangfok** [comment]
> I think is how things operate right now.

There is one scenario that currently doesn't work, which #4576 will fix: We currently cannot load a model file using a relative path when the model file contains references to mesh files using `package://` syntax. This is because the parsers are currently designed to crawl up the directory tree from the file name and fail to do this when it is provided a relative path.

**Pull request merged**
