### PR TITLE
Pymath w underscore2

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8076)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review, please.  This now supercedes #8069, (which I will close), and seems to be necessary given the latest findings on #8041.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8076#-:-L5Olz5x_iJxpsTsN1_d:bs3u6ll)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review, please.  (Eric already LGTM'd #8069 and recommended the name change, so I think it's safe to request these in parallel).

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8076#-:-L5OmNKuiolKx6DAuzg7:b-pp7891)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:
When I resolve #8041, I'll follow-up and rename `_math` to `math`.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8076#-:-L5Ow3TpJ-eHQUHGO9sV:b-mb7sp2)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8076#-:-L5Ow3m6ZDNSn5QOrSwO:bnfp4nl)*

**Pull request merged**
