### PR TITLE
Use [[ instead of [ in wheel scripts

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17884)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by mwoehlke-kitware** [comment]
+@EricCousineau-TRI for feature review, please

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, thanks!
+@ggould-tri for platform, please!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17884#-:-NBnEvtL6pZTanOWRS6v:bx4z9jx)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; good to be entering the post-1989 world :-)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17884#-:-NBnHrG24rlicvb88yKE:b-gfkhs)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
