### PR TITLE
Restore check that GRB_LICENSE_FILE and MOSEKLM_LICENSE_FILE are set

### PR DESCRIPTION
**Pull request by jamiesnape**
Commit https://github.com/RobotLocomotion/drake/commit/41ec0bfb9562635e9895a0fa32612288d1402436 from #8619, reverted by #8646, and a variation of https://github.com/RobotLocomotion/drake/pull/8647/commits/9c0fddda4dd225a0b71309cb5887b4ae79420d42 from #8647.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8649)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
+@hongkai-dai for feature review and +@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform :lgtm: with a couple of BTWs, ptal.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAZcbAr8N5eMx1SUUMN:busb7c2) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
> ```cpp
>   } catch (...) {
>     ADD_FAILURE() << "Expected exception of type std::runtime_error.";
>   }
> ```

BTW you can replace this entire try/catch/catch block with:
```c++
DRAKE_EXPECT_THROWS_MESSAGE(
    solver.Solve(program), std::runtime_error,
    "Could not locate Gurobi license key.*GRB_LICENSE_FILE.*not set.*");
```
(The message text is a regular expression that has to match the actual message.)

---

*[solvers/test/mosek_solver_moseklm_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZdmxoCGpHfc0Xokpb:-LAZdmxoCGpHfc0Xokpc:b-w3t6y9) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/mosek_solver_moseklm_license_file_test.cc#L50)):*
> ```cpp
>   } catch (...) {
>     ADD_FAILURE() << "Expected exception of type std::runtime_error.";
>   }
> ```

BTW see comment above

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-:-LAZdrlVEQVHbWZ7Bsyk:b-3x7a6x)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAZqp8N6R7HvZJ98N_i:b-molq2v) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW you can replace this entire try/catch/catch block with:
```c++
DRAKE_EXPECT_THROWS_MESSAGE(
    solver.Solve(program), std::runtime_error,
    "Could not locate Gurobi license key.*GRB_LICENSE_FILE.*not set.*");
```
(The message text is a regular expression that has to match the actual message.)
</blockquote></details>

BTW Maybe I am missing something, but if an exception other than `std::runtime_error` were thrown, it looks like we not check any `EXPECT_*` predicates and the cleanup would not happen since the exception would be uncaught.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-:-LAZrx9U481i-9qFaHjx:bnfp4nl)*

**Comment by sherm1** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAZxInnEEShLSVJQ4LT:b-2imxfi) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Maybe I am missing something, but if an exception other than `std::runtime_error` were thrown, it looks like we not check any `EXPECT_*` predicates and the cleanup would not happen since the exception would be uncaught.
</blockquote></details>

That macro should fail nicely if the wrong exception is thrown Jamie. You can try it just by changing the expected exception here to std::logic_error or whatever. Please let me know if it doesn't complain properly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by jwnimmer-tri** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAmptUV-c2Kcq7goulw:b-muwm11) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That macro should fail nicely if the wrong exception is thrown Jamie. You can try it just by changing the expected exception here to std::logic_error or whatever. Please let me know if it doesn't complain properly.
</blockquote></details>

@sherm1 I think you missed the point.  The test case does `unsetenv` and then as a cleanup action needs to do `setenv` to restore it.  If the test case execution halts because of an uncaught exception, the environment would not be restored and other tests in the same process would spuriously fail.  If the cleanup were phrased as a test fixture tear-down or a RAII within the local test case, only then could we use Drake's sugar.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by sherm1** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAn09H72qtZoob3HArf:b-lcme0c) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 I think you missed the point.  The test case does `unsetenv` and then as a cleanup action needs to do `setenv` to restore it.  If the test case execution halts because of an uncaught exception, the environment would not be restored and other tests in the same process would spuriously fail.  If the cleanup were phrased as a test fixture tear-down or a RAII within the local test case, only then could we use Drake's sugar.
</blockquote></details>

@jwnimmer-tri I think I'm still missing the point then. With DRAKE_EXPECT_THROWS_MESSAGE() the throwing of an incorrect exception would get reported and then execution would continue wouldn't it? (As opposed to `ASSERT`?) In that case the setenv repair would still occur.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by jwnimmer-tri** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAnA76c43a29t8ImQQ7:bqxkkjc) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@jwnimmer-tri I think I'm still missing the point then. With DRAKE_EXPECT_THROWS_MESSAGE() the throwing of an incorrect exception would get reported and then execution would continue wouldn't it? (As opposed to `ASSERT`?) In that case the setenv repair would still occur.
</blockquote></details>

To my read, the `catch` block in DRAKE_EXPECT_THROWS_MESSAGE_HELPER` only matches the desired exception subclass (`runtime_error`, in this case); if the device under test threw `logic_error` instead, it would percolate up into the GTEST_TEST and halt execution?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by sherm1** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAnG_BhAb2a292jGF9B:b-i4rmur) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To my read, the `catch` block in DRAKE_EXPECT_THROWS_MESSAGE_HELPER` only matches the desired exception subclass (`runtime_error`, in this case); if the device under test threw `logic_error` instead, it would percolate up into the GTEST_TEST and halt execution?
</blockquote></details>

Oh, crap -- you're right. That's a bug in that macro :( It should behave like GTEST's EXPECT_THROW which gives a message like:
```
Expected: system.AllocateContext() throws an exception of type std::runtime_error.
  Actual: it throws a different type.
```
and then continues on.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Comment by sherm1** [comment]
*[solvers/test/gurobi_solver_grb_license_file_test.cc, line 50 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM:-LAnLEvV-R1TvbDsTr7c:b-4qpajp) ([raw file](https://github.com/robotlocomotion/drake/blob/aa3511f80ae698bd603b536b46eb5bda8db5dee7/solvers/test/gurobi_solver_grb_license_file_test.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oh, crap -- you're right. That's a bug in that macro :( It should behave like GTEST's EXPECT_THROW which gives a message like:
```
Expected: system.AllocateContext() throws an exception of type std::runtime_error.
  Actual: it throws a different type.
```
and then continues on.
</blockquote></details>

Filed issue #8657.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649)*

**Pull request merged**
