### PR TITLE
Bind AddBilinearProductMcCormickEnvelopeSos2 and some MIP rotation constraint types

### PR DESCRIPTION
**Pull request by gizatt**
Been using these, figure they might be useful to someone!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121)

### CODE REVIEW

**Comment by gizatt** [comment]
@hongkai-dai, would you be comfortable feature reviewing this? There's one tricky bit concerning binding a struct of mutable `VectorXDecisionVariable` that I had trouble with that I'm curious if you've had have experience with.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:

 +@ericcousineau-tri for platform review please, thanks

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MojXgkpCDzXqrq-iPDr:b-p845us)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @gizatt)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MojXBNn3MIZzOoZxEdy:b-nl6im2) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
> ```cpp
>     using Struct = Class::ReturnType;
>     constexpr auto& struct_doc = cls_doc.ReturnType;
>     py::class_<Struct>(cls, "ReturnType", struct_doc.doc)
> ```

@ericcousineau-tri what is your recommendation for returning these readonly terms?
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXKpo9DyunAZxKnp7:-MojXKpo9DyunAZxKnp8:b7is1w) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L103)):*
> ```Python
>             binning = mip_util.IntervalBinning.kLinear
>             mip_util.AddBilinearProductMcCormickEnvelopeSos2(
>                 prog, x, y, w, phi_x, phi_y, Bx, By, binning
> ```

Could you use named variable as
`prog=prog, x=x, y=y, w=w, phi_x=phi_x, phi_y=phi_y, Bx=Bx, By=By, binning=binning`? We want to test if the keyword in the python binding are correct.

**Review by gizatt — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MojYNyF7BPkFpKXCauY:b-ucfknh)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MojY10_Cbi9Ry352g0p:bmvojmf) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@ericcousineau-tri what is your recommendation for returning these readonly terms?
</blockquote></details>

If I read the source file right, they're not actually readonly on the C side -- I bound them this way since I think it forces a copy (to appease numpy), and I don't see a use case for writing back to the struct.
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXKpo9DyunAZxKnp7:-MojYKxp6o_32SaYVCOj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L103)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you use named variable as
`prog=prog, x=x, y=y, w=w, phi_x=phi_x, phi_y=phi_y, Bx=Bx, By=By, binning=binning`? We want to test if the keyword in the python binding are correct.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, with minor nit on comment accuracy. Lemme know if you'd like me to push changes!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MokDjbr3wodITAa3HI_:b-hp5kv9)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @gizatt and @hongkai-dai)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MokAUemDTUXAlZNNKIq:b-v5ex21) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

If I read the source file right, they're not actually readonly on the C side -- I bound them this way since I think it forces a copy (to appease numpy), and I don't see a use case for writing back to the struct.
</blockquote></details>

OK Yup, looks good to me!

Perhaps there's a simpler spelling if `.def_property*()` could handle `py_rvp::copy`, but I can't quickly verify that it's the correct solution. In fact, this code leads me to believe that it may not work:
https://github.com/RobotLocomotion/pybind11/blob/c39ede1eedd4f39aa167d7b30b53ae45967c39b7/include/pybind11/pybind11.h#L1746-L1751
___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokB3nY3nEe1oWU-iTn:-MokB3nY3nEe1oWU-iTo:bqain3e) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L50)):*
> ```cpp
>         // Massage these types to return copies to appease numpy.
>         // If we don't do this, numpy complains on accessing either field:
>         //   "dtype=object arrays must be copied, and cannot be referenced."
> ```

nit Comment isn't entirely accurate; consider removing "If we don't do this", and instead reference #8116, e.g.:
```
// Massage these return types return copies, not references (#8116).
```

The error message you have is actually from our fork of `pybind11`, not NumPy:
```diff
$ cd pybind11
$ git diff $(git merge-base upstream/master HEAD) HEAD -- include/pybind11/eigen.h
diff --git a/include/pybind11/eigen.h b/include/pybind11/eigen.h
index e8c6f633..39839530 100644
...
-        switch (policy) {
-            case return_value_policy::take_ownership:
-            case return_value_policy::automatic:
-                return eigen_encapsulate<props>(src);
-            case return_value_policy::move:
-                return eigen_encapsulate<props>(new CType(std::move(*src)));
-            case return_value_policy::copy:
-                return eigen_array_cast<props>(*src);
-            case return_value_policy::reference:
-            case return_value_policy::automatic_reference:
-                return eigen_ref_array<props>(*src);
-            case return_value_policy::reference_internal:
-                return eigen_ref_array<props>(*src, parent);
-            default:
-                throw cast_error("unhandled return_value_policy: should not happen!");
-        };
+        constexpr bool is_pyobject = is_pyobject_dtype<Scalar>::value;
+        if (!is_pyobject) {
+            switch (policy) {
+                case return_value_policy::take_ownership:
+                case return_value_policy::automatic:
+                    return eigen_encapsulate<props>(src);
+                case return_value_policy::move:
+                    return eigen_encapsulate<props>(new CType(std::move(*src)));
+                case return_value_policy::copy:
+                    return eigen_array_cast<props>(*src);
+                case return_value_policy::reference:
+                case return_value_policy::automatic_reference:
+                    return eigen_ref_array<props>(*src);
+                case return_value_policy::reference_internal:
+                    return eigen_ref_array<props>(*src, parent);
+                default:
+                    throw cast_error("unhandled return_value_policy: should not happen!");
+            };
+        } else {
+            // For arrays of `dtype=object`, referencing is invalid, so we should squash that as soon as possible.
+            switch (policy) {
+                case return_value_policy::automatic:
+                case return_value_policy::move:

```
___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokAh7R62MUv_BmSvVR:-MokAh7R62MUv_BmSvVS:b-ul4d34) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L52)):*
> ```cpp
>         //   "dtype=object arrays must be copied, and cannot be referenced."
>         .def_property_readonly(
>             "B_",
> ```

BTW Pre-existing defect w/ C++: `struct`s do not have fields that end with `_`:
https://drake.mit.edu/styleguide/cppguide.html#Variable_Names

No action necessary in this PR, as deprecating public fields in a C++ struct can be a wee bit hairy.
___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokAZeRDKBANjerjcv6:-MokAZeRDKBANjerjcv7:bf7wue1) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L54)):*
> ```cpp
>             "B_",
>             [](Struct* self)
>                 -> const std::array<std::array<VectorXDecisionVariable, 3>, 3> {
> ```

BTW I believe you could shorten this (and below) to simply `-> const auto`.
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokA1IdBRQohEhhJbFU:-MokA1IeAsw99g0sGGaD:bhcyzct) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L77)):*
> ```Python
> 
>     def test_AddBilinearProductMcCormickEnvelopeSos2(self):
>         # Test that this constraint works when using a linear binning option.
> ```

BTW It's OK (possibly better?) to use docstrings when mentioning what a `unittest` case does, as that can be used in output and programmatically.
https://docs.python.org/3.6/library/unittest.html#unittest.TestCase.shortDescription

**Review by gizatt — COMMENTED** [review]
Pushed fixes now, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MokG_eu-X6XfTOh95ez:b-505s2b)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MokGJa88KVTpKtdzMcs:b-r5sjp0) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup, looks good to me!

Perhaps there's a simpler spelling if `.def_property*()` could handle `py_rvp::copy`, but I can't quickly verify that it's the correct solution. In fact, this code leads me to believe that it may not work:
https://github.com/RobotLocomotion/pybind11/blob/c39ede1eedd4f39aa167d7b30b53ae45967c39b7/include/pybind11/pybind11.h#L1746-L1751
</blockquote></details>

Leaving as-is since it seems to be working well, unless you have something else in mind. (Not sure exactly which you're referring to, but neither `.def_property` nor `def_readonly` compile if I swap them out.)
___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokB3nY3nEe1oWU-iTn:-MokEfM25ReP0Z2WJ0BV:btnswo9) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Comment isn't entirely accurate; consider removing "If we don't do this", and instead reference #8116, e.g.:
```
// Massage these return types return copies, not references (#8116).
```

The error message you have is actually from our fork of `pybind11`, not NumPy:
```diff
$ cd pybind11
$ git diff $(git merge-base upstream/master HEAD) HEAD -- include/pybind11/eigen.h
diff --git a/include/pybind11/eigen.h b/include/pybind11/eigen.h
index e8c6f633..39839530 100644
...
-        switch (policy) {
-            case return_value_policy::take_ownership:
-            case return_value_policy::automatic:
-                return eigen_encapsulate<props>(src);
-            case return_value_policy::move:
-                return eigen_encapsulate<props>(new CType(std::move(*src)));
-            case return_value_policy::copy:
-                return eigen_array_cast<props>(*src);
-            case return_value_policy::reference:
-            case return_value_policy::automatic_reference:
-                return eigen_ref_array<props>(*src);
-            case return_value_policy::reference_internal:
-                return eigen_ref_array<props>(*src, parent);
-            default:
-                throw cast_error("unhandled return_value_policy: should not happen!");
-        };
+        constexpr bool is_pyobject = is_pyobject_dtype<Scalar>::value;
+        if (!is_pyobject) {
+            switch (policy) {
+                case return_value_policy::take_ownership:
+                case return_value_policy::automatic:
+                    return eigen_encapsulate<props>(src);
+                case return_value_policy::move:
+                    return eigen_encapsulate<props>(new CType(std::move(*src)));
+                case return_value_policy::copy:
+                    return eigen_array_cast<props>(*src);
+                case return_value_policy::reference:
+                case return_value_policy::automatic_reference:
+                    return eigen_ref_array<props>(*src);
+                case return_value_policy::reference_internal:
+                    return eigen_ref_array<props>(*src, parent);
+                default:
+                    throw cast_error("unhandled return_value_policy: should not happen!");
+            };
+        } else {
+            // For arrays of `dtype=object`, referencing is invalid, so we should squash that as soon as possible.
+            switch (policy) {
+                case return_value_policy::automatic:
+                case return_value_policy::move:

```
</blockquote></details>

Done, & super helpful, thanks for clarifying!
___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokAZeRDKBANjerjcv6:-MokFV6fCOlsMzbxKFoK:b-6k9vo8) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L54)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I believe you could shorten this (and below) to simply `-> const auto`.
</blockquote></details>

Yup, much shorter!
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MokA1IdBRQohEhhJbFU:-MokFRGE2nc366ySeRjT:b-wjlkf8) ([raw file](https://github.com/robotlocomotion/drake/blob/6296263aa02fb32e3ce4906e8ed8a150b036bac6/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L77)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It's OK (possibly better?) to use docstrings when mentioning what a `unittest` case does, as that can be used in output and programmatically.
https://docs.python.org/3.6/library/unittest.html#unittest.TestCase.shortDescription
</blockquote></details>

Swapped over to a docstring, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MokHz5s6gfa-qtyDCel:bxjh10n) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

Leaving as-is since it seems to be working well, unless you have something else in mind. (Not sure exactly which you're referring to, but neither `.def_property` nor `def_readonly` compile if I swap them out.)
</blockquote></details>

OK Ah, I meant doing something like
```
.def_readonly("B_", &Struct::B_, py_rvp::copy, struct_doc.B_.doc
```
but NBD!

**Review by gizatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MokJjHI21sctf3Ux-o9:blf1s5o) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, I meant doing something like
```
.def_readonly("B_", &Struct::B_, py_rvp::copy, struct_doc.B_.doc
```
but NBD!
</blockquote></details>

That appears to work and sidesteps whatever weird const error I just got on CI but not locally, so let's go with that :)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> Dismissed @hongkai-dai from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @gizatt)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16121#-MojXBNn3MIZzOoZxEdx:-MokMhkp3YWmmUgo_H96:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake/blob/d340e0fea10f48d6d1e9eb31c06b1af22d564356/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L47)):*
<details><summary><i>Previously, gizatt (Greg Izatt) wrote…</i></summary><blockquote>

That appears to work and sidesteps whatever weird const error I just got on CI but not locally, so let's go with that :)
</blockquote></details>

OK Sweet, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MokPCRfDJl4pU_EYdD6:b-c7f1bi)* status: needs at least two assigned reviewers (waiting on @gizatt)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai (needed assignment to appease Reviewable completion condition)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16121#-:-MokPFX72xYnPUnefSxK:b2h5voy)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @gizatt)

**Pull request merged**
