### PR TITLE
Change Doxygen comments to normal ones (#12843).

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
…/* */) for code in internal namespace and in .cc files under drake/geometry (#12843).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13680)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I called out `@pre` and `@param` as examples of things that are beneficial; I did not intend to imply that those were the only two.

On specific files and lines in the review, I called out objective defects as nits.  For example, escaping `%MyClass` in a non-Doxygen comment interrupts the flow with no benefit; simply saying `MyClass` with no escape is strictly superior.

I agree in principle that developers are already familiar with the markup, and we should continue to use it where it adds value.  But this PR removes _literally none_ of the extra markup, and I find it implausible that _all_ of the extra markup benefits us in non-rendered form.  There must be at least _some_ that would be improved by removing the extra syntax, no?

**Comment by jwnimmer-tri** [comment]
Really, my point is that the author seems to have overlooked this question entirely.  If the answer is "I read through every use of markup in these blocks and they are all wonderful; I would have written it that way from the beginning even given our modern understanding of the internal namespace, and given that I cannot render the results to see if I have correctly used the syntax in the first place" then I will accept that.  But it seemed pretty clear to me that the question was ignored prior to submitting the PR.

**Comment by jwnimmer-tri** [comment]
... and rolling that back into my original post on this: We should probably merge this PR as-is because its a conflict monster, but the issue just needs a tiny edit first to note the remaining work, which at minimum would be concluding this discussion.

**Comment by sherm1** [comment]
Congratulations on PR #1, @xuchenhan-tri !

**Pull request merged**
