### PR TITLE
Fix PyPI download URL in pypi_archive macro

### PR DESCRIPTION
**Pull request by jamiesnape**
At least I now know that the mirroring of packages works....

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6048)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@sherm1 for feature and platform review.

**Comment by sherm1** [comment]
@jamiesnape, I don't know how to feature review this. If it is at all dangerous, please have someone else look at it. But for platform review, :lgtm:.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6048#-:-KjPODtGCzrIVWBudq6D:bww8z5k)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

I have been thinking anyway that we want a nightly CI that forces only one of the `urls` to be used, so that we get an early warning if one of them stops working or is malformed somehow.

**Comment by jamiesnape** [comment]
Not a bad idea. I could also probably get Amazon to sound an alarm if the mirror is hit too many times. I noticed this from the usage report.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6048#-:-KjPQtp8eIZnLkJev93p:b-r1x41n)*

**Comment by jamiesnape** [comment]
FWIW Excluding `semantic_version` and `six`, the mirrors have had 19 valid hits in the last 24 hours.

**Pull request merged**
