### PR TITLE
Introduce MinCliqueCoverSolver

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@wernerpe for feature review please. Towards more flexible IrisFromCliqueCover.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O6WgSTm1H8x0rvcL8yb:bwsy9t8)* status: LGTM missing from assignee wernerpe, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by wernerpe — COMMENTED** [review]
Asside from the wording in the docstring for minclique solver I think this is pretty much good to go.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O7eRx7g5RotMeDnyswF:bekto7z)* status: 2 unresolved discussions, LGTM missing from assignee wernerpe, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/min_clique_cover_solver_base.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7eRDof19vHd8g4A6hq:-O7eRDof19vHd8g4A6hr:b-c5me4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/6475144a33a3607418281ddef02a415f2b60b265/planning/graph_algorithms/min_clique_cover_solver_base.h#L19)):*
> ```objc
> 
>   /**
>    * Given the adjacency matrix of an undirected graph, find the minimum clique
> ```

I wonder if we should be a bit more careful with the wording here. We will be computing minimal / small clique covers. Only in the case of the horrendous MILP can we get the minimum.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892)* status: 3 unresolved discussions, LGTM missing from assignee wernerpe, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`planning/graph_algorithms/min_clique_cover_solver_base.h` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7jqpO71PVV5_43FaJh:-O7jqpO71PVV5_43FaJi:b-rci3jw) ([raw file](https://github.com/RobotLocomotion/drake/blob/6475144a33a3607418281ddef02a415f2b60b265/planning/graph_algorithms/min_clique_cover_solver_base.h#L46)):*
> ```objc
>   [[nodiscard]] std::vector<std::set<int>> SolveMinCliqueCover(
>       const Eigen::SparseMatrix<bool>& adjacency_matrix,
>       bool partition = false);
> ```

For the platform reviewer. Would it be better to make this method `const` and force concrete implementations to mark their members as `mutable` or is it better to leave this as is?

Note that many graph algorithms are randomized, hence the reasoning for this choice.



_Code quote:_
```objc
   * Note that this method is intentionally not-const because some solvers may
   * use randomized algorithms.
   */
  [[nodiscard]] std::vector<std::set<int>> SolveMinCliqueCover(
      const Eigen::SparseMatrix<bool>& adjacency_matrix,
      bool partition = false);
```

**Review by wernerpe — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O7jrLer4naDLys0iT-E:bnfp4nl)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@sammy-tri for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O7jrK2v3Cq9GA53IzGA:b-bh03fb)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/min_clique_cover_solver_base.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7eRDof19vHd8g4A6hq:-O7jrDdX5kBrJoA7QynS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6475144a33a3607418281ddef02a415f2b60b265/planning/graph_algorithms/min_clique_cover_solver_base.h#L19)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

I wonder if we should be a bit more careful with the wording here. We will be computing minimal / small clique covers. Only in the case of the horrendous MILP can we get the minimum.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with some nits

> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O7kXhp465_rqSTUlkNA:b-af439h)* status: 7 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/min_clique_cover_solver_base.h` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7jqpO71PVV5_43FaJh:-O7kWgdJ0BxoqbeLfUKU:b-mp26il) ([raw file](https://github.com/RobotLocomotion/drake/blob/6475144a33a3607418281ddef02a415f2b60b265/planning/graph_algorithms/min_clique_cover_solver_base.h#L46)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

For the platform reviewer. Would it be better to make this method `const` and force concrete implementations to mark their members as `mutable` or is it better to leave this as is?

Note that many graph algorithms are randomized, hence the reasoning for this choice.
</blockquote></details>

I think it's better like this unless we wind up with a case where we need to call this from some other `const` function in an owning class.  It's generally better for the function signature to be honest IMO.
___
*[`planning/graph_algorithms/min_clique_cover_solver_base.h` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kOuKc0jrByoUnoJdF:-O7kOuKc0jrByoUnoJdG:b-qchem1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/min_clique_cover_solver_base.h#L19)):*
> ```objc
> 
>   /**
>    * Given the adjacency matrix of an undirected graph, finds a (pontentially
> ```

nit: typo "pontentially"
___
*[`planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kRTihCGqC6xWJeUT8:-O7kRTihCGqC6xWJeUT9:b-3m39r3) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc#L88)):*
> ```cpp
>   auto solver_clone_mip =
>       dynamic_cast<MaxCliqueSolverViaMip*>(solver_clone.get());
>   EXPECT_FALSE(solver_clone_mip == nullptr);
> ```

nit: this should probably be `ASSERT_FALSE` so there isn't a chance of dereferencing the pointer in the next line)
___
*[`planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kStWq7SokSyBr4mzn:-O7kStWq7SokSyBr4mzo:beght5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc#L146)):*
> ```cpp
>   solution.clear();
>   solution.insert(std::initializer_list<int>{0, 3, 4});
>   solution.insert(std::initializer_list<int>{1, 2});
> ```

nit: this line and the two above it don't do anything (`solution` is cleared below)
___
*[`planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc` line 157 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kT-JIBorikhnZdkkk:-O7kT-JIBorikhnZdkkl:b-19e77c) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc#L157)):*
> ```cpp
>   possible_solutions.push_back(solution);
>   solution.clear();
>   solution.insert(std::initializer_list<int>{0, 3, 4});
> ```

nit: this line and the one above it don't do anything (`solution` is never used again)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kStWq7SokSyBr4mzn:-O7nltWU2RBG6WSXWzGg:b-qm9frr) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc#L146)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: this line and the two above it don't do anything (`solution` is cleared below)
</blockquote></details>

I forgot to insert the solution into the possible solution. Good catch!
___
*[`planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc` line 157 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-O7kT-JIBorikhnZdkkk:-O7nmMIu85fVM4FFwRoO:b-qm9frr) ([raw file](https://github.com/RobotLocomotion/drake/blob/e95d467f7acae9264cc43459c9efe7f607ed1f83/planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc#L157)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: this line and the one above it don't do anything (`solution` is never used again)
</blockquote></details>

I forgot to insert the solution into the possible solution. Good catch!

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O824y2cAcVe56uZVqEO:bm9o57a)* status: 3 unresolved discussions, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Dismissed @wernerpe from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21892#-:-O82CafN9_MCj20GKKgr:b-l8xbmn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),wernerpe

**Pull request merged**
