### PR TITLE
Adds optional argument to ExtractGradient to make return value statically allocated

### PR DESCRIPTION
**Pull request by edrumwri**
This simple PR adds an optional integer template argument to drake::math::ExtractGradient to allow it to allocate returned higher-derivative matrices (e.g., Hessians) on the stack.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16304)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16304#-:-MsbUv7PD-Iah0lP2nCb:b-f384lj)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
WDYT of Jeremy's proposal @edrumwri ? Two questions come to mind for me:
- does removing the num_derivatives argument cause a need for deprecation?
- does this affect Python bindings at all?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16304#-:-MwY1Noq5U5pVD3KtROg:b-xnjckl)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
I _think_ the template matching rules are such that all existing call sites would end up resolving to use the existing overload, no deprecation needed.

**Comment by jwnimmer-tri** [comment]
@sherm1 could you please help either move this forward, or it not then close it for lack of interest?

**Comment by sherm1** [comment]
@edrumwri is this still active? There are some pending comments but no responses for 2 months.

**Pull request closed without merging**
