### PR TITLE
Updates to Drake to allow it to work with ROS.

### LINKED ISSUE #2259: Unit test ros_test needs to be updated to use rostest
See: http://wiki.ros.org/rostest

This will avoid needing to manually start `roscore` before running the unit test.

### PR DESCRIPTION
**Pull request by liangfok**
This actually supersedes  #2763.

Closes #2259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2764)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMFUDdYlyXA7sH0itoU:-563954976)*

**Comment by jhoare** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source_ros.rst, line 43 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPqn1BHzrIqEIHdg7n:-KMPqn1CS2sE7dPaQcY4:1522375936) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L43)):*
> ```reStructuredText
> the instructions
> `here <http://catkin-tools.readthedocs.io/en/latest/installing.html>`_.
> We use ``catkin_tools`` instead of the normal ``catkin_build`` because Drake
> ```

I would just say we use ``catkin_tools`` due to its better support  building pure cmake packages alongside catkin packages. 

---

*[drake/doc/from_source_ros.rst, line 107 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPsNDUVHgGjMblb8Zl:-KMPsNDUVHgGjMblb8Zm:-1819709186) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L107)):*
> ```reStructuredText
> 
>     cd ~/dev/drake_catkin_workspace
>     rm -rf build devel install logs
> ```

``catkin clean`` Will also do this.

---

*[drake/doc/from_source_ros.rst, line 112 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPsR6lHIjDmuM_DD1g:-KMPsR6lHIjDmuM_DD1h:-825154018) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L112)):*
> ```reStructuredText
>     cd ~/dev/drake_catkin_workspace
>     source /opt/ros/indigo/setup.bash
>     catkin init
> ```

You shouldn't need to init every time, only the very first time. It creates a ``.catkin_tools`` folder and ``.catkin_workspace`` file at the root of the workspace. 

---

*[drake/doc/from_source_ros.rst, line 124 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMProQ3gM3_vIx8GR7n:-KMProQ4Rrd0rhHGRaEY:1973981774) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L124)):*
> ```reStructuredText
>     cd ~/dev/drake_catkin_workspace
>     source devel/setup.bash
>     catkin build --verbose --no-deps drake_ros_systems --make-args run_tests
> ```

This command should actually run the tests, the following command just runs a single test, ``ros_test.test`` . 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source_ros.rst, line 43 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPqn1BHzrIqEIHdg7n:-KMPxypPa60KK80sd0Sk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L43)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> I would just say we use ``catkin_tools`` due to its better support  building pure cmake packages alongside catkin packages. 
</details>
Done.

---

*[drake/doc/from_source_ros.rst, line 107 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPsNDUVHgGjMblb8Zl:-KMPy6TEn2G3mVnoHaNw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L107)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> ``catkin clean`` Will also do this.
</details>
Done.

---

*[drake/doc/from_source_ros.rst, line 112 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMPsR6lHIjDmuM_DD1g:-KMPyAkwasmCxaDPQp7j:2009724631) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L112)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> You shouldn't need to init every time, only the very first time. It creates a ``.catkin_tools`` folder and ``.catkin_workspace`` file at the root of the workspace. 
</details>
OK. Removed `catkin init`.

---

*[drake/doc/from_source_ros.rst, line 124 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMProQ3gM3_vIx8GR7n:-KMPyOVhaAbuttoZtEaQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a87c23ac70f6693ecbfcf51d9027abf6dc63ccf0/drake/doc/from_source_ros.rst#L124)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> This command should actually run the tests, the following command just runs a single test, ``ros_test.test`` . 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMPykI9h6OcXoFO5ADy:701515998)*

**Comment by jhoare** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMPz5TnjYrwdw8jZZyC:980077423)*

**Comment by liangfok** [comment]
+@sherm1 for platform review since it's Monday.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMPzANa-by0XqwN_qM4:-395381907)*

**Comment by liangfok** [comment]
The non-execution of the `clang-mac` CI (in https://drake-jenkins.csail.mit.edu/job/experimental/2581/) appears to be a flake. All other CI platform configurations passed. Thus, I believe this PR is ready for platform review / merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMQ9Ihiwm0oVL_UjtGK:-2092841841)*

**Comment by jhoare** [comment]
Yes, the mac builders are still down due to some hardware downtime.

**Comment by sherm1** [comment]
Platform review: just one comment.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source_ros.rst, line 74 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMQZNgaRApxoAvjCfwB:-KMQZNgaRApxoAvjCfwC:-338486353) ([raw file](https://github.com/robotlocomotion/drake/blob/eb36d641eb5be03a646e11a4c7e291821f4c1b1f/drake/doc/from_source_ros.rst#L74)):*
> ```reStructuredText
>     cd ~/dev/drake_catkin_workspace/src
>     git clone git@github.com:RobotLocomotion/drake.git
>     git clone git@github.com:liangfok/drake_ros_integration.git
> ```

It doesn't seem like a good idea to have your personal fork here, @liangfok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMQ_1ee3kAc7uk6RH4_:-1334164841)*

**Comment by liangfok** [comment]
I responded to the comment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source_ros.rst, line 74 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMQZNgaRApxoAvjCfwB:-KMQiILhqmllrHXo_-91:-61878685) ([raw file](https://github.com/robotlocomotion/drake/blob/eb36d641eb5be03a646e11a4c7e291821f4c1b1f/drake/doc/from_source_ros.rst#L74)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> It doesn't seem like a good idea to have your personal fork here, @liangfok.
</details>
I agree. Once this PR is merged, I will follow up with another PR that avoids my fork by merging `drake_ros_integration` with the core Drake repository using Option 3, which is described here: https://github.com/RobotLocomotion/drake/issues/2259#issuecomment-231789510.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMQibf4pte8sgnwYf4u:-1301350245)*

**Comment by liangfok** [comment]
I added a link to the promised follow-up PR that does not reference my personal `drake_ros_integration` repository. PTAL.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source_ros.rst, line 74 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-KMQZNgaRApxoAvjCfwB:-KMQoubdl9oV3sw22V0n:1929215497) ([raw file](https://github.com/robotlocomotion/drake/blob/eb36d641eb5be03a646e11a4c7e291821f4c1b1f/drake/doc/from_source_ros.rst#L74)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I agree. Once this PR is merged, I will follow up with another PR that avoids my fork by merging `drake_ros_integration` with the core Drake repository using Option 3, which is described here: https://github.com/RobotLocomotion/drake/issues/2259#issuecomment-231789510.
</details>
As promised, the in-flight follow up PR is here: https://github.com/robotlocomotion/drake/pull/2778.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMQozmF4t7X24Mev1r6:-1018484505)*

**Comment by sherm1** [comment]
Does this work on Windows?

**Comment by liangfok** [comment]
It does not because ROS Indigo only officially supports Ubuntu:  http://wiki.ros.org/indigo/Installation

The instructions that are part of this PR specify that users who want to use Drake with ROS need Ubuntu 14.04 and ROS Indigo.

**Comment by liangfok** [comment]
I should note that even though the Drake-ROS integration only works on Ubuntu, it does not prevent Drake from being used on OS X and Windows. Once ROS 2.0 is more mature and officially released, the plan is to migrate to ROS 2.0, which should support all three platforms: https://github.com/ros2/ros2/wiki/Installation#building-from-source.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2764#-:-KMS3TN47Tb40iYEjggN:1417088721)*

**Pull request merged**
