### PR TITLE
Change Compiler Flags

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3997)

### CODE REVIEW

**Comment by ggould-tri** [comment]
:lgtm:; minor comments below.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_yRhI6UjmeSc_0UiW:-KV_yRhI6UjmeSc_0UiX:bgbk1a0) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/CMakeLists.txt#L67)):*
> ```CMake
> include_directories(BEFORE ${PROJECT_SOURCE_DIR}/..)
> 
> if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
> ```

FYI -- I believe this is now unconditionally true and can be removed.

---

*[drake/systems/plants/joints/FixedAxisOneDoFJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_wozZIKlG7DrsAb41:-KV_wozZIKlG7DrsAb42:b-9344do) ([raw file](https://github.com/robotlocomotion/drake/blob/0ed1a05118498fea502be3df8cb224e6873b7649/drake/systems/plants/joints/FixedAxisOneDoFJoint.h#L81)):*
> ```objc
>     }
>   }
> ```

FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.

---

*[drake/systems/plants/joints/HelicalJoint.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_x953SCDHEueltEGS:-KV_x954_qJcAJ7CS4YQ:bmf1spo) ([raw file](https://github.com/robotlocomotion/drake/blob/0ed1a05118498fea502be3df8cb224e6873b7649/drake/systems/plants/joints/HelicalJoint.h#L9)):*
> ```objc
> 
> class DRAKE_EXPORT HelicalJoint
>     : public FixedAxisOneDoFJoint<HelicalJoint> {
> ```

FYI -- I don't understand why this whitespace change is in this PR.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xOeH70F266NACkgT:-KV_xOeH70F266NACkgU:b-9344do) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/QuaternionFloatingJoint.h#L74)):*
> ```objc
>     }
>   }
> ```

FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.

---

*[drake/systems/plants/joints/RevoluteJoint.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xUOd3Tt5ZNVMYA8D:-KV_xUOd3Tt5ZNVMYA8E:bmf1spo) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/RevoluteJoint.h#L11)):*
> ```objc
> #include "drake/systems/plants/joints/FixedAxisOneDoFJoint.h"
> 
> class DRAKE_EXPORT RevoluteJoint : public FixedAxisOneDoFJoint<RevoluteJoint> {
> ```

FYI -- I don't understand why this whitespace change is in this PR.

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xa8yXq6zEGeRND15:-KV_xa8yXq6zEGeRND16:b-9344do) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L39)):*
> ```objc
>     Eigen::Transform<typename DerivedQ::Scalar, 3, Eigen::Isometry> ret;
>     auto pos = q.template middleRows<drake::kSpaceDimension>(0);
>     auto rpy = q.template middleRows<drake::kRpySize>(drake::kSpaceDimension);
> ```

FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-:-KV_xf0PPqmvwx3-yked:b-g4cmgo)*

**Comment by soonho-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/CMakeLists.txt, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_yRhI6UjmeSc_0UiW:-KVa9Lh_1uvHAvkyzFMl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/CMakeLists.txt#L67)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I believe this is now unconditionally true and can be removed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by soonho-tri** [comment]
@ggould-tri, the rest of changes are here due to clang-format. Do you think it's better to remove them from this PR?

---

Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-:-KVa9PHVCoLWlyisMEri:b-426nen)*

**Comment by ggould-tri** [comment]
In general changes that are not relevant to the commit message will only serve to confuse anyone who uses `git annotate` in the future.  They aren't harmful, though, except insofar as they will cause anyone who has trouble with the code in question to come to you first.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-:-KVaYLz2_E_oOFsa12_F:bhjw4fo)*

**Comment by soonho-tri** [comment]
Removed those changes from this PR.

---

Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-:-KVacGhlRlgNUXj6uqpI:b-8b355h)*

**Comment by soonho-tri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/joints/FixedAxisOneDoFJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_wozZIKlG7DrsAb41:-KVacOQzZTt2EaBPKf3F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ed1a05118498fea502be3df8cb224e6873b7649/drake/systems/plants/joints/FixedAxisOneDoFJoint.h#L81)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.
</details>
Done.

---

*[drake/systems/plants/joints/HelicalJoint.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_x953SCDHEueltEGS:-KVacPIitpWmJSPCQShi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0ed1a05118498fea502be3df8cb224e6873b7649/drake/systems/plants/joints/HelicalJoint.h#L9)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I don't understand why this whitespace change is in this PR.
</details>
Done.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xOeH70F266NACkgT:-KVacQelB5a-vPaHg8uy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/QuaternionFloatingJoint.h#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.
</details>
Done.

---

*[drake/systems/plants/joints/RevoluteJoint.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xUOd3Tt5ZNVMYA8D:-KVacRFlDLS3Yq2PTEwl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/RevoluteJoint.h#L11)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I don't understand why this whitespace change is in this PR.
</details>
Done.

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KV_xa8yXq6zEGeRND15:-KVacRpi9GFMiKshBgXK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25f3178627b898a6d50caf39e087e396df6f97de/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- The changes below this point seem to be neutral whitespace changes.  I don't understand why they are part of this PR.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by soonho-tri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVacTuK5JfuzMNyz0sP:-KVacTuK5JfuzMNyz0sQ:baxac4r) (no related file):*
+@jwnimmer-tri, platform-review please. 

---

*[drake/bindings/swig/CMakeLists.txt, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVacd1jQaY-UFeLF08r:-KVacd1jQaY-UFeLF08s:bujq4rk) ([raw file](https://github.com/robotlocomotion/drake/blob/6745e7bfd8e93abb03026d36b5459b503c10f7c1/drake/bindings/swig/CMakeLists.txt#L29)):*
> ```CMake
>   # Swig emits code which appears to have misleading indentations.
>   # Err on the side of swig being correct.
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-misleading-indentation")
> ```

@ggould-tri, this is newly added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by ggould-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/swig/CMakeLists.txt, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVacd1jQaY-UFeLF08r:-KVadE8z0M0fopO6K3nv:b-5kbax0) ([raw file](https://github.com/robotlocomotion/drake/blob/6745e7bfd8e93abb03026d36b5459b503c10f7c1/drake/bindings/swig/CMakeLists.txt#L29)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> @ggould-tri, this is newly added.
</details>
Thanks for the pointer!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-:-KVadTrPness5F_KxY-5:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by soonho-tri** [comment]
*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVeZeG66w0a-JjDSuOc:-KVeZeG66w0a-JjDSuOd:b-cxmxx6) ([raw file](https://github.com/robotlocomotion/drake/blob/6745e7bfd8e93abb03026d36b5459b503c10f7c1/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L27)):*
> ```objc
>   virtual ~RollPitchYawFloatingJoint() {}
> 
>   using DrakeJointImpl<RollPitchYawFloatingJoint>::jointTransform;
> ```

/cc @ggould-tri,

FTR, I had f2f with @jwnimmer-tri. Here is the summary:

1. This fix causes segmentation faults. For example, `rigid_body_tree_test` test keeps calling `DrakeJointImpl::jointTransform` repeatedly. It is because this `using` statement enables non-template `jointTransform` functions defined in the base class (`DrakeJointImpl`), and hides the template function defined below. 

2.  Actually, clang does not give a warning even if we don't have a `using` statement here. Now I think that it's actually gcc's bug to emit a warning here when we don't have `using` statement. The given template definition should cover the ones defined in the base class (an infinite-loop is an evidence).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by ggould-tri** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/joints/DrakeJointImpl.h, line 110 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVf82BczoPc09SF6T4w:-KVf82BczoPc09SF6T4x:bk4okgs) ([raw file](https://github.com/robotlocomotion/drake/blob/d87342d7a8c22df20a0d5be241afe922d403fd2c/drake/systems/plants/joints/DrakeJointImpl.h#L110)):*
> ```objc
>   Derived& derived_;
> };
> #pragma GCC diagnostic pop
> ```

FYI -- You have commented the other instances of this but not this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by soonho-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/joints/DrakeJointImpl.h, line 110 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3997#-KVf82BczoPc09SF6T4w:-KVfDMWzQDjKLhYpwdoe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d87342d7a8c22df20a0d5be241afe922d403fd2c/drake/systems/plants/joints/DrakeJointImpl.h#L110)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- You have commented the other instances of this but not this one.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 8 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3997)*

**Pull request merged**
