### PR TITLE
Throw an error when getting dual solution for a QCP in gurobi.

### LINKED ISSUE #14281: GetDualSolution returns 0 for Gurobi when QCPDual=0
The dual solution for all constraints are 0 in Gurobi if the option `QCPDual=0`. Currently we only throw an error if the user wants to retrieve the dual solution for (rotated) Lorentz cone constraint if QCPDual=0. https://github.com/RobotLocomotion/drake/blob/886bd27e3dadae613c4d599490063f4b595b93d7/solvers/mathematical_program_result.h#L310-L320 For other constraints (like linear constraints), Gurobi doesn't compute its dual solution, but instead of throwing an error, we currently happily returned 0 as its dual solution, which is wrong dual solution. We should throw an error whenever the users call `GetDualSolution` for a gurobi solver with (rotated) Lorentz cone constraint.

cc @TobiaMarcucci

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #14281

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

cc @tobiamarcucci 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285#-:-MLFkKoA5xK4eFocV2Yo:b-pmv5yb)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm: with some minor comments inline. +@ggould-tri for platform review.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285#-:-MLNqUBM752kfIwY5KXR:bl2y4g4)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

___
*[solvers/mathematical_program_result.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNoIPL-GoECMLyDCkQ:-MLNoIPL-GoECMLyDCkR:b-v7b9m9) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L310)):*
minor: Consider replacing

> Throws a more meaningful error message when the user wants to retrieve dual solution from Gurobi result when the program contains second order cone constraint, but forgot to explicitly turn on the flag to compute gurobi qcp dual.

with

> Throws a more meaningful error message when the user wants to retrieve a dual solution from a Gurobi result for a program containing second order cone constraints, but forgot to explicitly turn on the flag to compute Gurobi QCP dual.
___
*[solvers/mathematical_program_result.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNp9s48XFjcIb4D6xT:-MLNp9s48XFjcIb4D6xU:bjj633k) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L314)):*
> ```objc
>         throw std::invalid_argument(fmt::format(
>             "You used {} to solve this optimization problem. If the problem is "
>             "solved to optimaility and doesn't contain binary/integer "
> ```

nit: s/optimaility/optimality
___
*[solvers/mathematical_program_result.h, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNptPPEYWJXuEBYqcF:-MLNptPPEYWJXuEBYqcG:b-jxzjvk) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L316)):*
> ```objc
>             "solved to optimaility and doesn't contain binary/integer "
>             "variables, but you failed to get the dual solution, "
>             "it is because you have to explicitly tell Gurobi solver to "
> ```

minor: Consider replacing "it is because you have to explicitly tell Gurobi solver" with "check that you have explicitly told Gurobi"

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; notes below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285#-:-MLOKBJmA8bsXxT2KYPs:b-38fvta)* status: 6 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 1112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOJHLH2uyhdmjYYnsd:-MLOJHLH2uyhdmjYYnse:b-jmr1id) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1112)):*
> ```cpp
>       // variables are not computed.
>       int qcp_dual;
>       error = GRBgetintparam(model_env, "QCPDual", &qcp_dual);
> ```

Capturing and immediately discarding the error here seems wrong.  If you don't care about the error return then don't capture it; if you do then `DRAKE_DEMAND(!error)` or similar.

(same issue two lines below this as well)
___
*[solvers/gurobi_solver.cc, line 1118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOIMjMDd3Ah4YE5UwZ:-MLOIMjMDd3Ah4YE5Uw_:b3yxzj6) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1118)):*
> ```cpp
> 
>       const bool compute_dual =
>           (num_q_constrs > 0 && qcp_dual == 0) ? false : true;
> ```

minor:  `? false : true` is a fairly roundabout way of saying `!`, which might be clearer.
___
*[solvers/gurobi_solver.cc, line 1131 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOK-c23EXwrMSmCRCQ:-MLOK-c3CsMGzr1aMGcm:bxawq7) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1131)):*
> ```cpp
>                                    result);
> 
>       Eigen::VectorXd gurobi_dual_solutions(num_gurobi_linear_constraints);
> ```

minor:  The indentation of this line and the six following is wrong.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),avalenzu

___
*[solvers/gurobi_solver.cc, line 1112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOJHLH2uyhdmjYYnsd:-MLOMoMy9xmlFn9IW_ao:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1112)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Capturing and immediately discarding the error here seems wrong.  If you don't care about the error return then don't capture it; if you do then `DRAKE_DEMAND(!error)` or similar.

(same issue two lines below this as well)
</blockquote></details>

Done, good call.
___
*[solvers/gurobi_solver.cc, line 1118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOIMjMDd3Ah4YE5UwZ:-MLOMvXv9A4a5qepG2Wm:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1118)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  `? false : true` is a fairly roundabout way of saying `!`, which might be clearer.
</blockquote></details>

Done. 
___
*[solvers/gurobi_solver.cc, line 1131 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLOK-c23EXwrMSmCRCQ:-MLON1Tq1jhMMlH8N3mM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/gurobi_solver.cc#L1131)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The indentation of this line and the six following is wrong.
</blockquote></details>

Done.
___
*[solvers/mathematical_program_result.h, line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNoIPL-GoECMLyDCkQ:-MLONJkm4teLo0ZdzQ1g:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L310)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

minor: Consider replacing

> Throws a more meaningful error message when the user wants to retrieve dual solution from Gurobi result when the program contains second order cone constraint, but forgot to explicitly turn on the flag to compute gurobi qcp dual.

with

> Throws a more meaningful error message when the user wants to retrieve a dual solution from a Gurobi result for a program containing second order cone constraints, but forgot to explicitly turn on the flag to compute Gurobi QCP dual.
</blockquote></details>

Done.
___
*[solvers/mathematical_program_result.h, line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNp9s48XFjcIb4D6xT:-MLONO5GAt4SzPbTwMfs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L314)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: s/optimaility/optimality
</blockquote></details>

Done.
___
*[solvers/mathematical_program_result.h, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14285#-MLNptPPEYWJXuEBYqcF:-MLONTaECi7vJk-NvuzL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec57173eb2212787fe1c2e556e0425ed15900ef7/solvers/mathematical_program_result.h#L316)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

minor: Consider replacing "it is because you have to explicitly tell Gurobi solver" with "check that you have explicitly told Gurobi"
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14285)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),avalenzu

**Pull request merged**
