### PR TITLE
Add RenderEngineGltfClient to the rendering documentation

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20248)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) 

+@RussTedrake for single review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-:-NfBi6g_-qXxje-ABvpw:b-aa6sef)* status: LGTM missing from assignee RussTedrake(platform)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  Thanks.

Not a blocker for this issue, but it strikes me now that RenderEngineGltfClient is possibly confusing as a name, if Vtk, etc also support gltf.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-:-NfBizVk8RnrJ2P03iym:b-uha7sk)* status: 1 unresolved discussion

___
*[`geometry/render/render_doxygen.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-NfBjHJ51e9EzxtRDg85:-NfBjHJ51e9EzxtRDg86:bgmg7f8) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e067afd37d7d0dd4d70b8aaf3e7a0a1d8605d88/geometry/render/render_doxygen.h#L26)):*
> ```objc
>    - RenderEngineGltfClient - An implementation of a client-server RPC renderer
>                               that broadcasts Drake's visual state in a glTF
>                               file.
> ```

Could we make these link to `MakeRenderEngineGl`, etc?  I've always found it surprisingly difficult to figure out how to actually use them, even after landing here.

The fundamental problem, I think, is that I open Doxygen and start typing Render and while I *do* find this page, I don't see the Vtk, Gl, etc variants.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I know what you mean. I believe the name was selected with care. It's not the definitive client, but it's a client that very explicitly communicates via glTF. So, the name carves out a corner of RPC but doesn't do so in any way that would conflict with any other client design we might select. I didn't participate in the discussion, but it seems the most likely inference.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-:-NfC0OlFD3fplcDkbhOP:brsiriw)* status: 1 unresolved discussion

___
*[`geometry/render/render_doxygen.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-NfBjHJ51e9EzxtRDg85:-NfC5co-EpMl_48_Y4SH:bmt6rsy) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e067afd37d7d0dd4d70b8aaf3e7a0a1d8605d88/geometry/render/render_doxygen.h#L26)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Could we make these link to `MakeRenderEngineGl`, etc?  I've always found it surprisingly difficult to figure out how to actually use them, even after landing here.

The fundamental problem, I think, is that I open Doxygen and start typing Render and while I *do* find this page, I don't see the Vtk, Gl, etc variants.
</blockquote></details>

An excellent point. I've tried to beef it up a bit more with more cross references.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: x2  thanks.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20248#-:-NfGK5BpCRf2CQAULa6I:b-6cyv2c)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

**Pull request merged**
