### PR TITLE
Alpha-sort the using statements

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6404)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by ggould-tri** [comment]
That is definitely sorted; :lgtm:.  That said, the using-versus-alias-versus-explicit tradeoffs in this file seem rather arbitrary.  If there's going to be much future work in this file going forward, they should be revisited in the interests of sanity.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6404#-:-KnFMDLaB51yZ9H1G71L:bjve536)*

**Comment by jwnimmer-tri** [comment]
Sure thing.  I'll consider that next time I touch this file (in a week or few).

**Pull request merged**
