### PR TITLE
LCM types build updates

### LINKED ISSUE #3683: Race Condition Between Generated C Language LCM Message Dependencies
# Problem Definition

There are often dependencies between Drake's LCM messages. For example, [lcmt_qp_controller_input](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_qp_controller_input.lcm) depends on [lcmt_zmp_data](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_zmp_data.lcm). If the dependencies are not correctly specified, race conditions can occur where an LCM message is compiled before all of its dependent LCM messages are generated. An example race condition is here: 

https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab-open-source/782/console

The relevant part of the log file is copied below:

```
10:34:20 /home/ubuntu/workspace/linux-gcc-continuous-matlab-open-source/build/drake/lcmtypes/drake_lcmt_qp_controller_input.h:18:33: fatal error: drake_lcmt_zmp_data.h: No such file or directory
10:34:20  #include "drake_lcmt_zmp_data.h"
10:34:20                                  ^
10:34:20 compilation terminated.
10:34:21 make[2]: Entering directory `/home/ubuntu/workspace/linux-gcc-continuous-matlab-open-source/build/drake'
10:34:21 [  7%] Generating drake_lcmt_zmp_data.h, drake_lcmt_zmp_data.c, drake/lcmt_zmp_data.hpp, drake/lcmt_zmp_data.py, drake/lcmt_zmp_data.java
```

The above console output snippet indicates that the compiler tried to find `drake_lcmt_zmp_data.h` before it was generated. Looking in [drake-distro/drake/lcmtypes/CMakeLists.txt](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/CMakeLists.txt), there is apparently code that ensures the C++ code is generated before building compiled:

https://github.com/RobotLocomotion/drake/blob/4937726eca3dd48dea702479f87c54c8031d42d1/drake/lcmtypes/CMakeLists.txt#L49

However, no such logic appears to exist for the generated C code. Maybe similar logic must be provided for the C code?

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove superfluous dependencies on `drake_lcmtypes_hpp` (which no longer exists). Update how we build our LCM types library to use all the shiny new stuff from LCM upstream.

Fixes #3683.

@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3962)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@sherm1 for platform review

**Comment by sherm1** [comment]
Platform :lgtm: (pending CI) but needs a good feature review since I am woefully unqualified to understand the implications of these changes.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-:-KVQ_uuhFpKLAtHRsCX-:bha4l24)*

**Comment by jwnimmer-tri** [comment]
As a best practice, I thought that Kitware-originated build system PR's were going to have a Kitware domain expert as feature reviewer from now on, before TRI even got involved?  Did I misunderstand my chat with @david-german-tri?

**Comment by mwoehlke-kitware** [comment]
> As a best practice, I thought that Kitware-originated build system PR's were going to have a Kitware domain expert as feature reviewer from now on, before TRI even got involved?

Sure, although for LCM stuff, that person would normally be me :smile:. Given the changes are mostly to do with LCM specific CMake stuff, I'm not sure if anyone (else) here adds much more expertise than anyone there. (For *most* CMake changes it would be different.)

+@jamiesnape for additional feature review, anyway :smile:.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-:-KVQeZPd2zZK_cqUCdYu:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
> I am woefully unqualified to understand the implications of these changes.

Really, the only impact should be that `drake_lcmtypes` now has an explicit dependency on its sources being generated first (i.e. #3683). Also, if `BUILD_SHARED_LIBS` in `ON`, it will now be a shared library instead of always a static library. (Previously it needed to be static for Windows and/or hidden symbol visibility.)

**Comment by liangfok** [comment]
:lgtm: Just one BTW question.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/CMakeLists.txt, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-KVRJVkJFT14owduyimd:-KVRJVkJFT14owduyime:byq2ccj) ([raw file](https://github.com/robotlocomotion/drake/blob/8094948fb80aac1ea8c99f6606b46fb37ce11a29/drake/lcmtypes/CMakeLists.txt#L1)):*
> ```CMake
> include(GenerateExportHeader)
> ```

BTW, where is `GenerateExportHeader` defined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-:-KVRJZYeJAGPjkdvE5Pk:bx0rm4u)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/CMakeLists.txt, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-KVRJVkJFT14owduyimd:-KVRJrGB5KVMxSQ0e-yG:b-tk39h) ([raw file](https://github.com/robotlocomotion/drake/blob/8094948fb80aac1ea8c99f6606b46fb37ce11a29/drake/lcmtypes/CMakeLists.txt#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, where is `GenerateExportHeader` defined?
</details>
https://github.com/Kitware/CMake/blob/master/Modules/GenerateExportHeader.cmake

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3962)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/CMakeLists.txt, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3962#-KVRJVkJFT14owduyimd:-KVRcfzRgGmQUezPl3vX:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/8094948fb80aac1ea8c99f6606b46fb37ce11a29/drake/lcmtypes/CMakeLists.txt#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> https://github.com/Kitware/CMake/blob/master/Modules/GenerateExportHeader.cmake
</details>
Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3962)*

**Pull request merged**
