### PR TITLE
Add a bowling ball demo

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Sends a bowling ball down a lane towards pin.  The ball's initial velocity
is parallel with the lane, but the spin on the ball causes it to break
into the pins.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5399)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@liangfok for feature review -- I'm sure you're not getting sick of these.  :)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-KeL5RKkTQ67gZPvrVxZ:b-4457kh)*

**Comment by liangfok** [comment]
Done with first pass. PTAL.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMRo9X_wC4BjjwbIhG:-KeMRo9X_wC4BjjwbIhH:b26mz6u) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L18)):*
> ```cpp
>  This doesn't model the change in the coefficient of friction due to position; a
>  real bowling lane is oiled in for the first 2/3 of its length.
>  As such, the parameters has to be tweaked to get the desired outcome.
> ```

BTW, "has" --> "have"?

_(Optional; marking myself satisfied.)_

---

*[drake/examples/contact_model/bowling_ball.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMSNpaNxfoXlOecNAC:-KeMSNpaNxfoXlOecNAD:b-u9r8z) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L87)):*
> ```cpp
>   // Create RigidBodyTree.
>   auto tree_ptr = make_unique<RigidBodyTree<double>>();
>     drake::parsers::urdf::AddModelInstanceFromUrdfFile(
> ```

Odd indentation. `clang-format`?

---

*[drake/examples/contact_model/bowling_ball.cc, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMSYGpvKHdhSe4CRsK:-KeMSYGpvKHdhSe4CRsL:b-ynh326) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L102)):*
> ```cpp
>   // Instantiate a RigidBodyPlant from the RigidBodyTree.
>   auto& plant = *builder.AddSystem<RigidBodyPlant<double>>(move(tree_ptr));
>   // Contact parameters set arbitrarily.
> ```

BTW, consider replacing "arbitrarily" with "based on the command line parameters".

_(Optional; marking myself satisfied.)_

---

*[drake/examples/contact_model/bowling_ball.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMQjgBPSQd66mLqc0T:-KeMQjgBPSQd66mLqc0U:bw8mfsj) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.urdf#L30)):*
> ```XML
>       <inertia ixx="0.033" ixy="0" ixz="0" iyy="0.031" iyz="0" izz="0.033"/>
>

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/contact_model/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMTr3k2bYUov_LyA5-:-KeMTr3k2bYUov_LyA50:b-s1ye1q) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/BUILD#L34)):*
> ```Python
>     data = [
>         ":bowling_models",
>     ],
> ```

BTW, consider making this a unit test.

_(Optional; marking myself satisfied.)_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMRo9X_wC4BjjwbIhG:-KeZRfj5YOUQTmJ6SujN:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "has" --> "have"?

_(Optional; marking myself satisfied.)_
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMSNpaNxfoXlOecNAC:-KeZSMCRuIFLtY3Lql1_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L87)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Odd indentation. `clang-format`?
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.cc, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMSYGpvKHdhSe4CRsK:-KeZSUXAbvLX_ok-4nlE:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.cc#L102)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "arbitrarily" with "based on the command line parameters".

_(Optional; marking myself satisfied.)_
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.urdf, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMQjgBPSQd66mLqc0T:-KeZSaOhAtwL_SMExshD:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/bowling_ball.urdf#L30)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider removing this commented out XML code.

_(Optional; marking myself satisfied.)_
</blockquote></details>

Done

---

*[drake/examples/contact_model/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMTr3k2bYUov_LyA5-:-KeZSbyGKqrig8soZNRh:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/BUILD#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider making this a unit test.

_(Optional; marking myself satisfied.)_
</blockquote></details>

Done

---

*[drake/examples/contact_model/BUILD, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-KeMR2rJOfDybxfKlnOz:-KeZShJh_8d9m-FgORQd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/479ca382e66e6a74a11fe9e7a10f25cce90df8fd/drake/examples/contact_model/BUILD#L39)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider alpha sorting.

_(Optional; marking myself satisfied.)_
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-KeZSiM7Gw0PV-L8ozLn:bu9a4i4)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-KeZTsI2xz_UNX0tDtQZ:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
+@sherm1 and +@soonho-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-KeZXQ1PRsM1m1X28Rxi:b-4ma82c)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 6 files at r1, 1 of 4 files at r2, 2 of 2 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_8H05VKZujHiA5q7i:-Ke_8H06DvpJWcsCWSPZ:b-oi5p8m) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L26)):*
> ```cpp
> #include <iomanip>
> #include <limits>
> #include <memory>
> ```

Consider including `#include <cmath>` to cover the use of `std::cos` / `std:sin`.

---

*[drake/examples/contact_model/bowling_ball.cc, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_5N9uhINkeb4X2ryA:-Ke_5N9uhINkeb4X2ryB:b2ik2h4) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L65)):*
> ```cpp
> // Bowling ball rolled down a conceptual lane to strike pins.
> int main(int argc, char**argv) {
>   using std::cerr;
> ```

BTW, I think it's good to have `using std::cout;` here since we use it a lot below.

---

*[drake/examples/contact_model/bowling_ball.cc, line 152 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_8OaGnU5jxHU7CX-0:-Ke_8OaHtmwFiiBw1oOT:b-2pkaoq) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L152)):*
> ```cpp
>   const double kPinZ = 0.109;
>   const double kCos60 = std::cos(60.0 / 180 * M_PI) * 12 * 0.0254;
>   const double kSin60 = std::cos(60.0 / 180 * M_PI) * 12 * 0.0254;
> ```

I think this is a typo of `std::sin(...)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Comment by SeanCurtis-TRI** [comment]
Comments addressed; PTAL.

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_8H05VKZujHiA5q7i:-Ke_NBFzvWs9NY0wr9Kc:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L26)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Consider including `#include <cmath>` to cover the use of `std::cos` / `std:sin`.
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.cc, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_5N9uhINkeb4X2ryA:-Ke_NSQfa-sYUrc7wEXi:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L65)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's good to have `using std::cout;` here since we use it a lot below.
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.cc, line 152 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_8OaGnU5jxHU7CX-0:-Ke_NTgxOK6WdGe0QEm0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/83579c494e9260bdc8d18c8d2be6ee32dabd99da/drake/examples/contact_model/bowling_ball.cc#L152)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think this is a typo of `std::sin(...)`.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-Ke_Nl0DESOQnBcT6fag:b-bb0f0y)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Comment by soonho-tri** [comment]
:lgtm:

@sherm1 , could you take a look at this PR?

---

Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-Ke_n0nMbcHkwMU1okjG:b4i4t0g)*

**Comment by sherm1** [comment]
:lgtm: with a few minor BTWs.

---

Reviewed 2 of 6 files at r1, 1 of 4 files at r2, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 103 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_tazNA718Nep4RV9M:-Ke_tazOkQbPPb-lJBym:bpv4hos) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.cc#L103)):*
> ```cpp
>   auto& plant = *builder.AddSystem<RigidBodyPlant<double>>(move(tree_ptr));
> 
>   plant.set_normal_contact_parameters(FLAGS_stiffness, FLAGS_dissipation);
> ```

BTW, not sure if you want to mention here that this causes the pin, lane, and bowling ball all to have the same properties :(.

---

*[drake/examples/contact_model/bowling_ball.cc, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_ttD55vLJQVF4CsEs:-Ke_ttD55vLJQVF4CsEt:b-dumii8) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.cc#L155)):*
> ```cpp
>   const double kCos60 = std::cos(60.0 / 180 * M_PI) * 12 * 0.0254;
>   const double kSin60 = std::sin(60.0 / 180 * M_PI) * 12 * 0.0254;
>   double pins_pos[] = { 0, 0,
> ```

BTW, const?

---

*[drake/examples/contact_model/bowling_ball.urdf, line 23 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_rDfay5JCE2NVehM7:-Ke_rDfay5JCE2NVehM8:b-t8lnux) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.urdf#L23)):*
> ```XML
>         Ixx = Izz = 0.033 kg⋅m²
>         Iyy = 0.031 kg⋅m²
>  -->
> ```

BTW, this is really nice!

---

*[drake/examples/contact_model/bowling_ball.urdf, line 32 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_s-hPz6Lztx56jjNq:-Ke_s-hPz6Lztx56jjNr:b-vg0ow3) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.urdf#L32)):*
> ```XML
>     <visual>
>       <geometry>
>         <sphere radius=".1085" />
> ```

BTW, @soonho-tri pointed out that this constant appears in the code. Should there be a comment here warning some future urdf hacker that changes here must be reflected in the code? (The code does say that about the urdf.)
(Ideally it would appear in only one location and get used twice but ... that seems somewhat unreasonable at the moment!)

---

*[drake/examples/contact_model/pin.urdf, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_qxkg9iDb3puyYqgS:-Ke_qxkg9iDb3puyYqgT:b-8czc6r) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/pin.urdf#L1)):*
> ```XML
> <?xml version="1.0"?>
> ```

BTW, maybe a little comment here saying what this is for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-Ke_ujLbFNPzBFdzbnqY:b6uxo1v)*

**Comment by SeanCurtis-TRI** [comment]
Made some changes as per BTWs.

---

Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/contact_model/bowling_ball.cc, line 103 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_tazNA718Nep4RV9M:-KeeguPZLrhzC_VTWome:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.cc#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, not sure if you want to mention here that this causes the pin, lane, and bowling ball all to have the same properties :(.
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.cc, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_ttD55vLJQVF4CsEs:-Keeh2hLDbrHuSGjkMbO:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.cc#L155)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, const?
</blockquote></details>

Done

---

*[drake/examples/contact_model/bowling_ball.urdf, line 23 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_rDfay5JCE2NVehM7:-KeehD9Mg1khWTcqj9-D:buucly5) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.urdf#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this is really nice!
</blockquote></details>

BTW Thanks.  +1 for unicode.

---

*[drake/examples/contact_model/bowling_ball.urdf, line 32 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_s-hPz6Lztx56jjNq:-KeehIJgIQCq9RRGPvlT:b7yfogu) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/bowling_ball.urdf#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, @soonho-tri pointed out that this constant appears in the code. Should there be a comment here warning some future urdf hacker that changes here must be reflected in the code? (The code does say that about the urdf.)
(Ideally it would appear in only one location and get used twice but ... that seems somewhat unreasonable at the moment!)
</blockquote></details>

BTW *Technically*, it appears three times.  Twice in the urdf (vis and collision) and once in the code.  The code *could* be eliminated if I were willing to dig into the rigid body's collision element and grab the sphere radius.  Given this won't be changing much, I'll just add some safety notes.  :)

---

*[drake/examples/contact_model/pin.urdf, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-Ke_qxkg9iDb3puyYqgS:-KeehuM_Td6CGsayQT1u:b-6yw40i) ([raw file](https://github.com/robotlocomotion/drake/blob/dd32ef25713d0c45a776c9e4fe8e6fa946683139/drake/examples/contact_model/pin.urdf#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, maybe a little comment here saying what this is for?
</blockquote></details>

I would hope that the comment: `<!-- Bowling pin -->` would suffice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399#-:-Keei-HFRB3AmbfDE3PK:b-7vkyku)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5399)*

**Pull request merged**
