### PR TITLE
Initialize time_sec, which matters when T is AutoDiff.

### PR DESCRIPTION
**Pull request by david-german-tri**
Supersedes #4438.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4440)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-minimal please

**Comment by david-german-tri** [comment]
@sherm1 fyi

**Comment by jwnimmer-tri** [comment]
Screw you, Eigen.  `T{}` shouldn't ever leave the value as garbage.  Arrgh!

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4440#-:-KYZF3NGaZO6gk-uzoR3:b-bfijvp)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4440#-:-KYZFGCYO4wR1fKMALDu:bnfp4nl)*

**Comment by david-german-tri** [comment]
Mac build passed, not waiting for the one Linux build that went out to lunch.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4440#-:-KYZMekE-Ybf2Qu695hR:b-2n4cm)*

**Pull request merged**
