### PR TITLE
Use ScopeExit to free ScsSolver resource.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please.

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for both reviews please since we just used ScopeExit in the other PR on MosekSolver. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423#-:-Mex1ApGBnEwdAviSNFG:b-obfwyk)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I think we need to tweak the `ScopeExit` a bit more.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423#-:-Mez0a6SAnj_nW4W6UAs:bpfimwf)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15423#-Mez-iAG08DtxwTJRsuJ:-Mez-iAH9GW331QZRqGH:b-kx8cfw) (no related file):*
Met issue: `scs_solver.cc` has 11 calls to `scs_calloc()`. It has three instances of `ScopeExit`. I convinced myself that the 8 invocations don't *require* unique `ScopeExit` instances because of the nature of `scs_free_foo`. I'd propose the following:

1. Everywhere you use `scs_calloc` that doesn't get partnered with a `ScopeExit` instance should have a comment indicating that this memory gets cleaned up by the recursively by the call to `scs_free_foo` on the containing scs data type. (It need not be one comment *per* invocation; where you set multiple fields of an scs struct in sequence, one comment can encompass the entire "paragraph".
2. You *might* consider a note at the `ScopeExit` definition emphasizing that it frees the  indicated object and, recursively, all of its instantiated members.

---
___
*[solvers/scs_solver.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15423#-MeyzMVc8XIp1ih5mpOv:-MeyzMVc8XIp1ih5mpOw:bbs7zjm) ([raw file](https://github.com/robotlocomotion/drake/blob/6a271285c53caa09ee40c53b88c0300a061a17cc/solvers/scs_solver.cc#L690)):*
> ```cpp
> 
>   // cone stores all the cones K in the problem.
>   ScsCone* cone = static_cast<ScsCone*>(scs_calloc(1, sizeof(ScsCone)));
> ```

I have an issue here. This should also get its own `ScopeExit`. You allocate this memory here and make numerous calls to other methods which *could* throw before you get down below to allocating `problem_data_guard`. It feels like the cone isn't properly guarded.

I think this is easily resolved. As I read the code for [`scs_free_data`](https://github.com/cvxgrp/scs/blob/master/src/util.c#L155-L171), I notice while it takes points to both data and cone, they are freed independently and either can be null.

I'd suggest providing a unique guard for cone (where the program data is null in the call to `scs_free_data`, and likewise set the cone pointer to null in the program data's guard.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15423#-Mez-iAG08DtxwTJRsuJ:-MezmOdY5YEOcGuQ71C6:b-56754c) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Met issue: `scs_solver.cc` has 11 calls to `scs_calloc()`. It has three instances of `ScopeExit`. I convinced myself that the 8 invocations don't *require* unique `ScopeExit` instances because of the nature of `scs_free_foo`. I'd propose the following:

1. Everywhere you use `scs_calloc` that doesn't get partnered with a `ScopeExit` instance should have a comment indicating that this memory gets cleaned up by the recursively by the call to `scs_free_foo` on the containing scs data type. (It need not be one comment *per* invocation; where you set multiple fields of an scs struct in sequence, one comment can encompass the entire "paragraph".
2. You *might* consider a note at the `ScopeExit` definition emphasizing that it frees the  indicated object and, recursively, all of its instantiated members.
</blockquote></details>

Done. Good call. I added the documentation.

---
___
*[solvers/scs_solver.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15423#-MeyzMVc8XIp1ih5mpOv:-MezmRt3-I4AsEiNA62D:b-o08w3a) ([raw file](https://github.com/robotlocomotion/drake/blob/6a271285c53caa09ee40c53b88c0300a061a17cc/solvers/scs_solver.cc#L690)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I have an issue here. This should also get its own `ScopeExit`. You allocate this memory here and make numerous calls to other methods which *could* throw before you get down below to allocating `problem_data_guard`. It feels like the cone isn't properly guarded.

I think this is easily resolved. As I read the code for [`scs_free_data`](https://github.com/cvxgrp/scs/blob/master/src/util.c#L155-L171), I notice while it takes points to both data and cone, they are freed independently and either can be null.

I'd suggest providing a unique guard for cone (where the program data is null in the call to `scs_free_data`, and likewise set the cone pointer to null in the program data's guard.
</blockquote></details>

I am a bit hesitant here. If SCS upstream changes in the future, that the upstream code doesn't free up `scs_problem_data` and `cone` independently, then we will run into problem.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/scs_solver.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15423#-MeyzMVc8XIp1ih5mpOv:-Mezuu8p0dUYsuA11PYp:b-y92fi7) ([raw file](https://github.com/robotlocomotion/drake/blob/6a271285c53caa09ee40c53b88c0300a061a17cc/solvers/scs_solver.cc#L690)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am a bit hesitant here. If SCS upstream changes in the future, that the upstream code doesn't free up `scs_problem_data` and `cone` independently, then we will run into problem.
</blockquote></details>

I appreciate your point. However, it seems like your worried about a possible problem in the future and incurring a definite problem now.

I'd suggest creating its own `ScopeExit` and putting a TODO that we should keep an eye on `scs_free_data()` to make sure the independent clean up of cone and data remains acceptable.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/scs_solver.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15423#-MeyzMVc8XIp1ih5mpOv:-Mf4314f2wU-UlF0iYHO:b5v90tx) ([raw file](https://github.com/robotlocomotion/drake/blob/6a271285c53caa09ee40c53b88c0300a061a17cc/solvers/scs_solver.cc#L690)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I appreciate your point. However, it seems like your worried about a possible problem in the future and incurring a definite problem now.

I'd suggest creating its own `ScopeExit` and putting a TODO that we should keep an eye on `scs_free_data()` to make sure the independent clean up of cone and data remains acceptable.
</blockquote></details>

Here's the logical compromise.  Bring the `scs_problem_data` instantiation up here with the code and guard them both at the same time. It would remove the problem of having `cone` running around without any scope guard. And instantiating the data early won't hurt you.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[solvers/scs_solver.cc, line 690 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15423#-MeyzMVc8XIp1ih5mpOv:-Mf4SInv31gyMXnMbTva:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/6a271285c53caa09ee40c53b88c0300a061a17cc/solvers/scs_solver.cc#L690)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Here's the logical compromise.  Bring the `scs_problem_data` instantiation up here with the code and guard them both at the same time. It would remove the problem of having `cone` running around without any scope guard. And instantiating the data early won't hurt you.
</blockquote></details>

Done. Thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@sherm1 for platform review.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423#-:-Mf4YsCl63DarGYjyMXd:b-cyxhbg)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15423#-:-Mf4ucM53G7YmKJ7A5rG:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
