### PR TITLE
Add bindings for SceneGraph::ChangeShape()

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19278)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19278#-:-NTtjFHJAwFvqYRojfdM:b-pvz8jw)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19278#-:-NTtjIUpA_nvXeAxcfm4:b-6es8oq)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19278#-:-NTuWYCIDQ0lQ37vajyW:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
Backfill bindings are generally +(release notes: fix) -(release notes: none).

**Pull request merged**
