### PR TITLE
systems/traj opt: Return multiple shooting constraints for AddConstraintToAllKnotPoints and AddEqualTimeIntervalsConstraints

### LINKED ISSUE #13213: AddEqualTimeConstraints()  should return (a vector of) Bindings
Having proclaimed the usefulness of naming constraints with e.g.
```
AddConstraint(...).evaluator().set_description('equal_time')
```
I got the natural question about naming the equal time constraints.  I believe this one is my fault; and that the method should return those values.

### PR DESCRIPTION
**Pull request by mpetersen94**
Stumbled across the relevant issue and realized I had already made the fix in my own branch so thought I'd upstream.

Closes #13213

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake for feature review

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thanks!
+@ggould-tri for platform review, please.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340#-:-MMTHhfU274saOHTWWC2:bp1ai6o)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; a couple of notes below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340#-:-MMW2B9W20pX6anKaIEH:b7e4vfe)* status: 2 unresolved discussions (waiting on @mpetersen94)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14340#-MMVzLUw-phQpNiScVIs:-MMVzLUx3IBlG-A1uwYh:bxlad3l) (no related file):*
minor:  You should capture and make a trivial assertion on these new return values in `trajectory_optimization_test.py` to help ensure that we don't have any keepalive issues in the bindings (I'm pretty sure we don't, but it's good hygeine).

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14340#-MMW1mvT-o2hoF-FNLuk:-MMW1mvT-o2hoF-FNLul:brw62bc) (no related file):*
minor:  There are other methods of `multiple_shooting` that could return their added constraints like this and don't.  If this issue closes #13213 then there should probably be a new issue for those.  I've added that as a comment on #13213 and @russtedrake can decide what makes sense for that.

---

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14340#-MMVzLUw-phQpNiScVIs:-MMWCese7i_CIlhb3SUz:b-qobc84) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  You should capture and make a trivial assertion on these new return values in `trajectory_optimization_test.py` to help ensure that we don't have any keepalive issues in the bindings (I'm pretty sure we don't, but it's good hygeine).
</blockquote></details>

(per f2f with Jeremy:  It is enough to just assign the return values.  No assertions are needed.)

---

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @ggould-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14340#-MMW1mvT-o2hoF-FNLuk:-MMqEsyN5bkDzdz_Nlxo:b-896fix) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  There are other methods of `multiple_shooting` that could return their added constraints like this and don't.  If this issue closes #13213 then there should probably be a new issue for those.  I've added that as a comment on #13213 and @russtedrake can decide what makes sense for that.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14340#-MMVzLUw-phQpNiScVIs:-MMqVMDt1K3pSyaA1IUG:bwfu313) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

(per f2f with Jeremy:  It is enough to just assign the return values.  No assertions are needed.)
</blockquote></details>

Done.  I checked the returns to make sure there weren't any returning None.

---

**Review by RussTedrake — COMMENTED** [review]
awesome.  thanks.  :lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340#-:-MMwEfPfEEH3vmLaFzm8:bsdl1pd)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform)

**Review by mpetersen94 — COMMENTED** [review]
Repaired the test failure!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340#-:-MN7GgUXESpDF8BgzPqd:bf4s2qv)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14340)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @mpetersen94)

**Pull request merged**
