### PR TITLE
Add specific language about where and which unsigned types may be used

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add specific language about where and which unsigned types may be used.  This is the unsigned-related part of #2514 .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2686)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review
+@david-german-tri for platform review

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-:-KLN_XgxtPAUC3ojOM44:-1868698381)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-KLNawBlq1TXh2SyeEI5:-KLNawBlq1TXh2SyeEI6:-203458378) ([raw file](https://github.com/robotlocomotion/drake/blob/0ec52105c21c856888d35981701d7d0d4ec1b803/drake/doc/code_style_guide.rst#L72)):*
> ```reStructuredText
>     type during Drake's interactions with the non-Drake API would obscure the
>     readability of our code, and (3) subtraction underflow below zero is
>     obviously not at risk -- then ``size_t`` may be used.
> ```

BTW, I find the `--` punctuation of these two bullet points hard to read.  Consider rephrasing along the lines of:

unsigned types are forbidden, with the following exceptions:

* types X, Y are allowed under conditions foo.
* type Z is allowed under conditions bar. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-:-KLNbSkgWLGBJ6Axqw4D:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/doc/code_style_guide.rst, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-KLNawBlq1TXh2SyeEI5:-KLNe1WhyqnOHzh8F8jM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0ec52105c21c856888d35981701d7d0d4ec1b803/drake/doc/code_style_guide.rst#L72)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I find the `--` punctuation of these two bullet points hard to read.  Consider rephrasing along the lines of:
> 
> unsigned types are forbidden, with the following exceptions:
> 
> * types X, Y are allowed under conditions foo.
> * type Z is allowed under conditions bar. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2686)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-:-KLNfO9-ZJBjK8Pu9Jgs:1417088721)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2686#-:-KLNk3Pke8dfxJ965o_v:1417088721)*

**Pull request merged**
