### PR TITLE
Fix python version on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
This is far from the whole story, i.e., necessary, but not sufficient.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8228)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/python_bindings.rst, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-L6cLrs2F8wyUg3soEm0:-L6cLrs35tpJFG-VOeW5:bh3kik0) ([raw file](https://github.com/robotlocomotion/drake/blob/d61a71987f960aec648795e53cf8af4d55ffe4ea/doc/python_bindings.rst#L69)):*
> from ``brew info python``
BTW, => `brew info python@2`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228)*

**Comment by soonho-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/python_bindings.rst, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-L6cNV4rRt7gUUBBkw58:-L6cNV4rRt7gUUBBkw59:bnfpq7l) ([raw file](https://github.com/robotlocomotion/drake/blob/d61a71987f960aec648795e53cf8af4d55ffe4ea/doc/python_bindings.rst#L77)):*
> ``pip install jupyter``

Assuming a user ran `brew install python`, this will invoke `/usr/local/bin/pip` which is homebrew's pip3. Do we need to change this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228)*

**Comment by jamiesnape** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/python_bindings.rst, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-L6cNV4rRt7gUUBBkw58:-L6cOT7jAbvbwYemX_-h:b-ohofeu) ([raw file](https://github.com/robotlocomotion/drake/blob/d61a71987f960aec648795e53cf8af4d55ffe4ea/doc/python_bindings.rst#L77)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> ``pip install jupyter``

Assuming a user ran `brew install python`, this will invoke `/usr/local/bin/pip` which is homebrew's pip3. Do we need to change this line?
</blockquote></details>

I just did, though even `pip2` may be broken at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/python_bindings.rst, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-L6cNV4rRt7gUUBBkw58:-L6cOgpQcRSnZvaQfFi8:bm8f2uu) ([raw file](https://github.com/robotlocomotion/drake/blob/d61a71987f960aec648795e53cf8af4d55ffe4ea/doc/python_bindings.rst#L77)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I just did, though even `pip2` may be broken at the moment.
</blockquote></details>

Yup. I understand this is a part of the complete solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228)*

**Comment by soonho-tri** [comment]
Still testing it (and building `vtk@8.0` from source) but :lgtm: so far.

Will remove +(status: do not merge)  tag when my test passes.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-:-L6cQGM7XuFrBdNAtDcX:b-zb1n4v)*

**Comment by soonho-tri** [comment]
Among the ones in `//bindings/pydrake`, the following ones failed:
```
//bindings/pydrake/util:_isolated/cpp_param_pybind_test                  FAILED in 0.5s
//bindings/pydrake/util:_isolated/cpp_template_pybind_test               FAILED in 0.3s
//bindings/pydrake/util:cpp_param_pybind_test                            FAILED in 0.5s
//bindings/pydrake/util:cpp_template_pybind_test                         FAILED in 0.3s
```

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-:-L6cX4eoHdMeRQI-wkAx:bvhf00x)*

**Comment by soonho-tri** [comment]
-(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-:-L6cjX3TMnDnDan3q4Nr:b-b9fcpn)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
:lgtm:, though that is not saying much in my case. I'm comfortable knowing that @soonho-tri reviewed this, but if you think this needs another Mac-savvy reviewer please assign one. Otherwise, merge.

---

Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-:-L6cn32yHb83n2EZIw-s:bbh2o39)*

**Comment by soonho-tri** [comment]
I think this is good to go. @jamiesnape , I think it's not going to cause any problems in Mac CI. But I'd like to have your confirmation. If you think so, please merge this.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8228#-:-L6cwH593XYEemdegA1t:b87fqlp)*

**Pull request merged**
