### PR TITLE
[multibody] Move DeformableModel out of internal

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18307)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@russtedrake for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18307#-:-NGdDO0j3WUhAPBxdYkk:b-sriflu)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 
This one is small enough that I could do both reviews, if you like.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18307#-:-NGdd2Ul9-rLyEyBiqik:b-nvqa2d)* status: needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_model.h` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18307#-NGdcm_V0DhKAt7tX1xr:-NGdcm_V0DhKAt7tX1xs:bgszeg) ([raw file](https://github.com/robotlocomotion/drake/blob/4ed70e6b46385786deadbf162ebeb3e2f894fc07/multibody/plant/deformable_model.h#L104)):*
> ```objc
>   DeformableBodyId GetBodyId(DeformableBodyIndex index) const;
> 
>   /** (Internal) Returns the DeformableBodyIndex of the body with the given id.
> ```

btw -- I had to look at the code a bit to understand why you marked this one internal.  Perhaps you can add a note to say that "most users should be using DeformableBodyId", or a similar justification?

**Review by xuchenhan-tri — COMMENTED** [review]
That'd be great. Thanks!
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18307#-:-NGdim4q3thLRejs9UYW:b9wo8dy)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_model.h` line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18307#-NGdcm_V0DhKAt7tX1xr:-NGdjLl3AlTHltHAvmNF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ed70e6b46385786deadbf162ebeb3e2f894fc07/multibody/plant/deformable_model.h#L104)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- I had to look at the code a bit to understand why you marked this one internal.  Perhaps you can add a note to say that "most users should be using DeformableBodyId", or a similar justification?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18307)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
