### PR TITLE
[WIP] System3: an alternate approach to System2

### PR DESCRIPTION
**Pull request by sherm1**
I am not yet convinced that the current System2 architecture is the best way to achieve the many goals we have for Simulink-like dynamic system capability in C++ Drake. For discussion, here is an alternate implementation approach that I think will be easier to complete, and which I believe leads to a simpler API that is easier to explain. I'm calling it "System3" for now and all the new classes and files have a "3" in their names so that it can peacefully coexist with System2. Here is a quick summary of the major differences:
- Uses a flat class hierarchy with no multiple inheritance.
- Execution order is controlled by a dataflow approach (like VTK) rather than an attempt to precalculate an optimal ordering. This allows computation of only those quantities that are actually used, and fits very nicely with the proposed caching scheme.
- Supports both abstract and vector-valued input and output.
- Any System can have sub-Systems and thus be a system diagram.
- No State or Output classes need be defined to create a new System; only the System class is required.
- Views system diagram as a tree-structured object reflecting *ownership*: the top level system owns all its sub-Systems and self-manages lifetime issues. The input/output connection graphs operate on sibling nodes of the tree, with higher level systems able to inherit ports from their children.
- Every System can create a matching-but-independent Context. The Context is a tree of sub-Contexts with one-to-one correspondence to sub-Systems. There are no cross-pointers between the const System and mutable Context.
- Systems have input and output ports that are independent of Context.
- Output ports are properly cached.
- Uses non-virtual public interface (NVI) design pattern. That separates the end-user API from the System-extending developer API and allows injection of useful boilerplate code and default implementations in the base class. Virtual method implementations are shorter and simpler to write.

(I'm not sure how well this can be conveyed in text -- a whiteboard talk would likely be more effective.)

If you want to look at this, I suggest starting with the test cases. I think the API can be simplified further but the tests show the basic structure.
- [adder3_test](https://github.com/sherm1/drake/blob/System3-an-alternate-System2/drake/systems/framework/primitives/test/adder3_test.cc) builds a diagram with several system primitives.
- [system3_test](https://github.com/sherm1/drake/blob/System3-an-alternate-System2/drake/systems/framework/test/system3_test.cc) shows an example of non-numeric input and output ports used to create a fanciful string-processing diagram.

The fundamental classes are [`AbstractSystem3`](https://sherm1.github.io/drake-System3-doxygen/classdrake_1_1systems_1_1_abstract_system3.html) / [`System3<T>`](https://sherm1.github.io/drake-System3-doxygen/classdrake_1_1systems_1_1_system3.html), [`AbstractContext3`](https://sherm1.github.io/drake-System3-doxygen/classdrake_1_1systems_1_1_abstract_context3.html) / [`Context3<T>`](https://sherm1.github.io/drake-System3-doxygen/classdrake_1_1systems_1_1_context3.html), (links are to doxygen) and `AbstractValue/Value<T>` (same as in System2). The "Abstract" level is the base class and supports all operations that can be performed without knowing the underlying Scalar type T. That includes a very large fraction of the important functions such as: input and output, building diagrams, managing "out of date" values in the cache.

The implementation so far has lots missing pieces and extra junk I used to get it working. The cache is present and used in the dataflow calculations but the invalidation mechanism is not hooked up so the values are always getting recalculated. Unit testing is inadequate-to-nonexistent. But I wanted to get this posted for discussion purposes; please review only architectural features. Questions and comments welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2825)

### CODE REVIEW

**Comment by sherm1** [comment]
BTW, this currently works only for stateless System3's. I am trying to figure out how to make continuous and discrete state variables for a top-level diagram contiguous in memory so that they can be returned as VectorX's and worked with efficiently in the Solver.

**Comment by liangfok** [comment]
I haven't had time to carefully study System 3.0 or compare it with System 2.0 yet. In fact, I may need to wait for System 2.0's diagram to be implemented before doing a direct comparison.

Regardless, while we are on the topic of alternate designs, one paper that may be relevant is the following, which presents Robot Task Commander (RTC):

> Stephen Hart, Paul Dinh, John D. Yamokoski3, Brian Wightman2, and Nicolaus Radford, "[Robot Task Commander: A framework and IDE for robot application development](http://dx.doi.org/10.1109/IROS.2014.6942761)", IROS 2014.

In addition to SimuLink and possibly RTC, what other related systems should we be studying? Is there a good survey paper that already answers this question?

**Comment by sherm1** [comment]
In addition to the Simulink documentation which has lots of information but spread very widely, I really like [this paper](http://link.springer.com/chapter/10.1007%2F978-3-540-31954-2_2) (book chapter):
> Hybrid Systems: Computation and Control
Volume 3414 of the series Lecture Notes in Computer Science pp 25-53
Operational Semantics of Hybrid Systems
Edward A. Lee, Haiyang Zheng

That's a nice introduction to hybrid simulation, but no paper is going to help with the architecture and API design here. What we're attempting is unique; people will be reading *our* papers about it later!

**Comment by david-german-tri** [comment]
@liangfok - A System2 diagram implementation is here: https://github.com/david-german-tri/drake/commit/dd4764f6cffdfee4cddb99a315736196b8f59656#diff-b6d218b96e2188d55fbc73e8638d2e6f

**Comment by david-german-tri** [comment]
I've taken an initial look at this, and figured a quick response would be useful.  The high-order bit of my reaction is that System3 meets all the same needs as System2, and neither one has compelling advantages or disadvantages relative to the other.

In particular, I think System3 is less different from System2 than your list above would suggest.  From that list, the only differences that I agree are major are:

* Execution order is controlled by a dataflow approach (like VTK) rather than an attempt to pre-calculate an optimal ordering.

* Systems have input and output ports that are independent of Context.

In my opinion, these changes make framework code harder to understand, and user code harder to debug - I'm particularly uncomfortable with all the substantive computation living in closures that belong to `CacheEntry` - but it's just an opinion and we can bikeshed it indefinitely.  

The rest of your list strikes me as either implementation details about which I have no strong opinion (NVI, class hierarchy) or not actually differences at all (one-to-one correspondence of System and Context, caching of outputs, abstract-valued ports, and diagram ownership of subsystems).

**Comment by amcastro-tri** [comment]
I just did a very quick pass on this. Initially I like the API looks simple in the examples. However, I would like to see more realistic examples. Something I can think of is a simple 1D car example with a PID controller so the car reaches a specified x location. The car itself then would be a simple `F=m*a` system and the PID controller could be made off out of simpler gain+integral+derivative blocks. 
I still have to study the context design and also study how this would allow more complex types like autodiffs and polynomials. 

---

Reviewed 1 of 40 files at r1.
Review status: 1 of 40 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/system3.cc, line 39 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ipvxaY_86jIz6WbF:-KN2ipvxaY_86jIz6WbG:-1480011564) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.cc#L39)):*
> ```cpp
> 
>   const AbstractContext3& subcontext = owner.first->find_my_subcontext(context);
> ```

There's got to be a better way to do this. Glad you called it find_something so I would spot it right away. Probably the context itself could hold a vector subcontext entries indexed by a global system id? that would be the fastest but not sure if it goes along with your design.

---

*[drake/systems/framework/system3.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZBdywqao1Ofctl5Y:-KN2ZBdywqao1Ofctl5Z:-1714581237) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L51)):*
> ```objc
> among the subsystems' inputs and outputs. A system that contains subsystems
> is called a "system diagram", one without subsystems is called a "leaf system",
> and the topmost system diagram is the "root system".
> ```

Consider: "root system" or "model"

---

*[drake/systems/framework/system3.h, line 77 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZcMQRie9teK4_RRu:-KN2ZcMRoZ2rCQFs5Hcr:-607976479) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L77)):*
> ```objc
>   // TODO(sherm1) Consider requiring this to be unique among sibling subsystems
>   // so that we can construct a unique pathname to any subsystem.
>   std::string get_name() const {return name_;}
> ```

I used the concept of `resolved_name` in the past when writing a "tree of systems" concept. So a method `get_resolved_name` would return the whole path to this system from the root system. I used `::` to separate names, something like `root_system::child_node::grand_child::greatgrand_child::this_system_name`. While `get_name` would only return `this_system_name`. That allowed me to have systems with the same names though they had unique resolved names.

---

*[drake/systems/framework/system3.h, line 114 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2dIKOSgr-S_znygOE:-KN2dIKOSgr-S_znygOF:161554223) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L114)):*
> ```objc
>   number. **/
>   const InputPort3& get_input_port(int port_num) const {
>     return *get_input_port_finder(port_num).port;
> ```

I really like how you solved this. Simple, efficient and gets the job done.

---

*[drake/systems/framework/system3.h, line 194 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2e8aIgFNrelm1lt-c:-KN2e8aJIL4Bq2uwFExw:-2099450718) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L194)):*
> ```objc
>   general be different from the input port number in the subsystem from
>   which it was inherited. **/
>   int InheritInputPort(AbstractSystem3* child_subsystem, int input_port_num) {
> ```

Here I would change the API so that the user can do `my_sys.InheritInputPort(child_sys.input(32))`. I guess this goes again along my preference of working with ports. To me they look like plug and sockets and conceptually easy to understand.

---

*[drake/systems/framework/system3.h, line 230 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2aiTOwFMs1zUxAAjW:-KN2aiTOwFMs1zUxAAjX:1298213193) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L230)):*
> ```objc
>     const OutputPort3& out = source_subsystem->get_output_port(output_port_num);
>     InputPort3* in = sink_subsystem->get_mutable_input_port(input_port_num);
>     in->ConnectTo(&out);
> ```

I like this! why not to let the use call the `Connect` methods on ports? IMO that seems more natural to me. But I would simplify by renaming `get_ouput_port`-->`ouput` and `get_mutable_input_port` --> `input`. Const or mutable versions will depend on the scope they are called (good to me).

---

*[drake/systems/framework/system3.h, line 268 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2et62q7AFFaZtOzfN:-KN2et62q7AFFaZtOzfO:-422868410) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L268)):*
> ```objc
>   `/rootname/parentname/myname`. This name will be unique if sibling subsystems
>   have unique names within their parent system. **/
>   std::string GetSubsystemPathName() const {
> ```

Nice! this is what I was talking about with the `resolved_name` before.

---

*[drake/systems/framework/primitives/test/adder3_test.cc, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2TYBELcwtDjAdqwJS:-KN2TYBELcwtDjAdqwJT:87006270) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/primitives/test/adder3_test.cc#L51)):*
> ```cpp
>   // AddSubsystem returns raw pointers of concrete type to the contained
>   // subsystem objects in the diagram.
>   auto adder = diagram.AddSubsystem(
> ```

I'd prefer here to see the actual type typed instead of `auto`.

---

*[drake/systems/framework/primitives/test/adder3_test.cc, line 60 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2SkkrxgTif5uEBdJ0:-KN2SkkspOioH26JVYD0:-1773924299) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/primitives/test/adder3_test.cc#L60)):*
> ```cpp
>       make_unique<VectorConstant3<double>>("vec1", vec1));
> 
>   diagram.Connect(cascade, 0, adder, 0);
> ```

I like this example. Would it be possible to make the API look something like `adder.input(0).connect(cascade.output(0))`?
where `adder.input(0)` returns the 0-th `InputPort` and `cascade.output(0)` returns the 0-th `OutputPort`.  In my mind (as a user) that looks more like making connections between male/female sockets. 

---

*[drake/systems/framework/test/system3_test.cc, line 34 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2WA4AN1mmmMb1kt9t:-KN2WA4BNbKYVSMhylAJ:1569317095) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/test/system3_test.cc#L34)):*
> ```cpp
> // TODO(sherm1) Should be able to derive this from AbstractSystem3. Currently
> // the primitives like Cascade are System3 so won't work with AbstractSystems.
> class SourceForStrings: public System3<double> {
> ```

I guess related to you TODO here but inheriting from `System3<double>` doesn't seem right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-:-KN2jTOxYlMhYHsoxiU_:-216520627)*

**Comment by sherm1** [comment]
Thanks very much for the review, @amcastro-tri. Great comments - responses below. I will see about making those changes next time I make a pass through this code.

---

Review status: 1 of 40 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/system3.cc, line 39 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ipvxaY_86jIz6WbF:-KN2sGbt5zvbsRuzEgQf:-584826363) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.cc#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> There's got to be a better way to do this. Glad you called it find_something so I would spot it right away. Probably the context itself could hold a vector subcontext entries indexed by a global system id? that would be the fastest but not sure if it goes along with your design.
</details>
Yes, there is an easy way to do this. After the system diagram is complete, assign a unique integer to each subsystem (root gets 0, its children get 1,2,3, next layer gets 4,5,6,..., etc.). An std::vector maps those integers to pointers to the subsystems. A parallel index in Context maps the same integers to the subcontext. That will provide essentially perfect access time from subcontext->subsystem and subsystem->subcontext yet avoids any cross-pointers between System and Context (which would be very bad since these are supposed to be independent).

---

*[drake/systems/framework/system3.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZBdywqao1Ofctl5Y:-KN2tGooC3EXlcs87EtX:732192214) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L51)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider: "root system" or "model"
</details>
Not sure what you meant here. "root" and "leaf" seem like the standard terms for those positions in a tree.

---

*[drake/systems/framework/system3.h, line 77 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZcMQRie9teK4_RRu:-KN2tZtnr6ID5LFKV_sh:995120598) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I used the concept of `resolved_name` in the past when writing a "tree of systems" concept. So a method `get_resolved_name` would return the whole path to this system from the root system. I used `::` to separate names, something like `root_system::child_node::grand_child::greatgrand_child::this_system_name`. While `get_name` would only return `this_system_name`. That allowed me to have systems with the same names though they had unique resolved names.
</details>
Done. See `GetSubystemPathName()` below. But what I meant was that siblings in the tree must have unique names -- otherwise the resolved name is not unique. If a node N has two children, both named C, then they would both have resolved names N/C. They need to be something like N/C1 and N/C2.

---

*[drake/systems/framework/system3.h, line 114 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2dIKOSgr-S_znygOE:-KN2u7zcUf0ZmGKB0l0Q:-1834867277) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L114)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I really like how you solved this. Simple, efficient and gets the job done.
</details>
Thanks!

---

*[drake/systems/framework/system3.h, line 194 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2e8aIgFNrelm1lt-c:-KN2uBWk2DN98UFIAlrG:678254422) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L194)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Here I would change the API so that the user can do `my_sys.InheritInputPort(child_sys.input(32))`. I guess this goes again along my preference of working with ports. To me they look like plug and sockets and conceptually easy to understand.
</details>
I agree with you. I think David's connections work that way and I like that better than using port numbers.

---

*[drake/systems/framework/system3.h, line 230 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2aiTOwFMs1zUxAAjW:-KN2uXjzWIyhJth89R3N:-149888029) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L230)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I like this! why not to let the use call the `Connect` methods on ports? IMO that seems more natural to me. But I would simplify by renaming `get_ouput_port`-->`ouput` and `get_mutable_input_port` --> `input`. Const or mutable versions will depend on the scope they are called (good to me).
</details>
+1 for Connect on ports. Not on the implicit mutable though -- here requesting mutable access can trigger a flood of invalidation activity; I want that to be explicit and not happen by accident.

---

*[drake/systems/framework/system3.h, line 268 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2et62q7AFFaZtOzfN:-KN2uuRLZI02sFIrZYTX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L268)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Nice! this is what I was talking about with the `resolved_name` before.
</details>
Done.

---

*[drake/systems/framework/primitives/test/adder3_test.cc, line 60 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2SkkrxgTif5uEBdJ0:-KN2v8U1q6x4zCg2x-C2:-1669000358) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/primitives/test/adder3_test.cc#L60)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I like this example. Would it be possible to make the API look something like `adder.input(0).connect(cascade.output(0))`?
> where `adder.input(0)` returns the 0-th `InputPort` and `cascade.output(0)` returns the 0-th `OutputPort`.  In my mind (as a user) that looks more like making connections between male/female sockets. 
</details>
I like that.

---

*[drake/systems/framework/test/system3_test.cc, line 34 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2WA4AN1mmmMb1kt9t:-KN2vUY2rVyXtPkrGnkU:-1530771663) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/test/system3_test.cc#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I guess related to you TODO here but inheriting from `System3<double>` doesn't seem right.
</details>
Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-:-KN2vXx97ipurCdNIdPs:1862926583)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 40 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/system3.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZBdywqao1Ofctl5Y:-KN34SnDBaaLMyipNK3q:-145850868) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Not sure what you meant here. "root" and "leaf" seem like the standard terms for those positions in a tree.
</details>
I agree root/leaf  are the standard terms for trees. What I was suggesting is to **also** call the root system "model". I believe that's what the Simulink called their most external block.

---

*[drake/systems/framework/system3.h, line 194 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2e8aIgFNrelm1lt-c:-KN34y6_V8hyNTtv0TqY:-1948090778) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L194)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I agree with you. I think David's connections work that way and I like that better than using port numbers.
</details>
I am not talking about port numbers here but about the argument ot `InheritInputPort` being the actual port. To get a given port from a system you'd still do `sys.input(input_port_number)`. Another option for the user's API would be that each port had a string name and then the user could do `my_sys.input("port_name")`. The latter is just an addition we could implement later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2825)*

**Comment by sherm1** [comment]
Review status: 1 of 40 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/system3.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2ZBdywqao1Ofctl5Y:-KN3SL2N-8Na9jqq2QZQ:-1592583992) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L51)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree root/leaf  are the standard terms for trees. What I was suggesting is to **also** call the root system "model". I believe that's what the Simulink called their most external block.
</details>
Got it. I'm reluctant to re-use the overloaded "model" word. I think we should limit that to just the world/model distinction borrowed from sdf files.

---

*[drake/systems/framework/system3.h, line 194 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2825#-KN2e8aIgFNrelm1lt-c:-KN3SasbhwpcxYtdjRiN:355189900) ([raw file](https://github.com/robotlocomotion/drake/blob/f92f66eecfb0dae630f48b1ba99ba56309c65293/drake/systems/framework/system3.h#L194)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I am not talking about port numbers here but about the argument ot `InheritInputPort` being the actual port. To get a given port from a system you'd still do `sys.input(input_port_number)`. Another option for the user's API would be that each port had a string name and then the user could do `my_sys.input("port_name")`. The latter is just an addition we could implement later.
</details>
+1 for port names!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2825)*

**Comment by jamiesnape** [comment]
Ignore the "default" and "continuous-integration/jenkins/pr/mac" builds.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@sherm1 Is there any reason to keep this open?

**Comment by sherm1** [comment]
> Is there any reason to keep this open?

No, I think it has served its purpose.

**Pull request closed without merging**
