### PR TITLE
geometry:optimization: Python bindings for convex sets and Iris

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, +@soonho-tri for platform review, please (trying to get this in before your platform day ends!).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333#-:-Me1IFsPBH-HGQgA1y6S:b-r3h4lm)* status: LGTM missing from assignees hongkai-dai,soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: needs a lint brush.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333#-:-Me1Jg4vCysz0IQj9wIv:b-50d84g)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/test/geometry_test.py, line 964 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15333#-Me1jic_-F9CBUpZFJG4:-Me1jic_-F9CBUpZFJG5:b-4i78pl) ([raw file](https://github.com/robotlocomotion/drake/blob/e580fe0907965701ff059819b6f4fbfb9027640f/bindings/pydrake/test/geometry_test.py#L964)):*
> ```Python
>         self.assertEqual(vpoly.ambient_dimension(), 2)
>         np.testing.assert_array_equal(vpoly.vertices(), vertices)
>         self.assertTrue(vpoly.PointInSet(x=[1.0, 5.0], tol=0.0))
> ```

FYI,

```
[2021-07-07T20:27:35.925Z]   File "/media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-experimental-everything-release/_bazel_ubuntu/6909c5ca3eec693d3f125c1bc6ffbd37/sandbox/linux-sandbox/13664/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/test/geometry_test.py", line 964, in test_optimization
[2021-07-07T20:27:35.925Z]     self.assertTrue(vpoly.PointInSet(x=[1.0, 5.0], tol=0.0))
[2021-07-07T20:27:35.925Z] AssertionError: False is not true
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/test/geometry_test.py, line 964 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15333#-Me1jic_-F9CBUpZFJG4:-Me1q0ze7saMBWrp222i:b-bxmum6) ([raw file](https://github.com/robotlocomotion/drake/blob/e580fe0907965701ff059819b6f4fbfb9027640f/bindings/pydrake/test/geometry_test.py#L964)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI,

```
[2021-07-07T20:27:35.925Z]   File "/media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-experimental-everything-release/_bazel_ubuntu/6909c5ca3eec693d3f125c1bc6ffbd37/sandbox/linux-sandbox/13664/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/test/geometry_test.py", line 964, in test_optimization
[2021-07-07T20:27:35.925Z]     self.assertTrue(vpoly.PointInSet(x=[1.0, 5.0], tol=0.0))
[2021-07-07T20:27:35.925Z] AssertionError: False is not true
```
</blockquote></details>

Yes.  Sorry!  The test was passing on my mac, but needed a tolerance on ubuntu.  Should be good now.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15333#-:-Me1vsQpBnT8WcpR7dOb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
