### PR TITLE
[py solvers] Bind ClarabelSolver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19449.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20569)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

**Comment by jwnimmer-tri** [comment]
\CC @hongkai-dai FYI

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: testing nit

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20569#-:-Njn2v4bCWgkohmbFtIn:bceyat6)* status: 1 unresolved discussion

___
*[`bindings/pydrake/solvers/solvers_py_clarabel.cc` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20569#-Njn2flxCZN8N5MIOzrX:-Njn2flxCZN8N5MIOzrY:b-1qcqcu) ([raw file](https://github.com/RobotLocomotion/drake/blob/5669fac7dc7cbd461f5fb2e915e984157a35f563/bindings/pydrake/solvers/solvers_py_clarabel.cc#L22)):*
> ```cpp
> 
>   py::class_<ClarabelSolverDetails>(
>       m, "ClarabelSolverDetails", doc.ClarabelSolverDetails.doc)
> ```

nit no test prevents this string from containing typos.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20569#-:-NjnrSbH40KlghFTRHFj:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
