### PR TITLE
show_images: Handle case where no depth points are valid.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8021)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.
+@sherm1 for platform review, please.

The failure on LSan is due to `dreal`, not this PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-:-L4wCSTg8symZ-fe6qXO:b-e5mtnj)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[systems/sensors/visualization/show_images.py, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L4wG_f2rzApBMHby_kQ:-L4wG_f2rzApBMHby_kR:bzc781f) ([raw file](https://github.com/robotlocomotion/drake/blob/639d3b6528113b8e7759fbb539048ceec0f45495/systems/sensors/visualization/show_images.py#L143)):*
> ```Python
>             good = np.isfinite(data[:])
>             if np.any(good):
>                 upper_depth = np.max(data[good])
> ```

I might be missing something, but `good` wouldn't be array of booleans?

---

*[systems/sensors/visualization/show_images.py, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L4wHqimUX6IF1GH0wNS:-L4wHqimUX6IF1GH0wNT:bsy3yq9) ([raw file](https://github.com/robotlocomotion/drake/blob/639d3b6528113b8e7759fbb539048ceec0f45495/systems/sensors/visualization/show_images.py#L145)):*
> ```Python
>                 upper_depth = np.max(data[good])
>             else:
>                 upper_depth = -1
> ```

You don't need this because you are under the condition `upper_depth == -1` already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021)*

**Comment by kunimatsu-tri** [comment]
*[systems/sensors/visualization/show_images.py, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L4wG_f2rzApBMHby_kQ:-L4wJfkK6JoQKApzl-2V:b-i6vl8u) ([raw file](https://github.com/robotlocomotion/drake/blob/639d3b6528113b8e7759fbb539048ceec0f45495/systems/sensors/visualization/show_images.py#L143)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I might be missing something, but `good` wouldn't be array of booleans?
</blockquote></details>

Never mind. I was testing `data` as a list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/visualization/show_images.py, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L4wHqimUX6IF1GH0wNS:-L4wNuMrcO0JJ-n9noDh:b-qhumv0) ([raw file](https://github.com/robotlocomotion/drake/blob/639d3b6528113b8e7759fbb539048ceec0f45495/systems/sensors/visualization/show_images.py#L145)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

You don't need this because you are under the condition `upper_depth == -1` already.
</blockquote></details>

Done. D'oh, thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-:-L4wPqu94otDDjdz2sHV:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by sherm1** [comment]
:lgtm: with one FYI just in case.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/visualization/show_images.py, line 143 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L5L672nk7slrO7dc-iP:-L5L672nk7slrO7dc-iQ:bi4rqbv) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd64039d41a8df12297dda984e33ea4aa45b7a8/systems/sensors/visualization/show_images.py#L143)):*
> ```Python
>             good = np.isfinite(data[:])
>             if np.any(good):
>                 upper_depth = np.max(data[good])
> ```

FYI definitely good to skip the NaNs! But this also eliminates `inf` which under some circumstances might be the right value for max. Just wanted to mention that in case this is one of those circumstances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-:-L5L6_hwoaGEmVheu3Cw:b1egg5k)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/visualization/show_images.py, line 143 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8021#-L5L672nk7slrO7dc-iP:-L5LHOK0j-DRDqVGytaN:b-402nw7) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd64039d41a8df12297dda984e33ea4aa45b7a8/systems/sensors/visualization/show_images.py#L143)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI definitely good to skip the NaNs! But this also eliminates `inf` which under some circumstances might be the right value for max. Just wanted to mention that in case this is one of those circumstances.
</blockquote></details>

OK Thanks for the info! We actually do want to skip `inf`, as it's for scaling the depth colors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8021)*

**Pull request merged**
