### PR TITLE
Add gripper buttons to toolbar

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4966)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for both levels of review (chosen for knowledge of the wsg's LCM protocol)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-:-KbkklvFvlK3n8MlbmuA:bhgol93)*

**Comment by ggould-tri** [comment]
:lgtm: pending style issues.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-Kbl-QSAYgUSjoQ24J2l:-Kbl-QSAYgUSjoQ24J2m:b-nxuyxh) ([raw file](https://github.com/robotlocomotion/drake/blob/3f1c5bc710e0d5437dda62758b2cdecb428961ac/drake/examples/kuka_iiwa_arm/director_ik_app.py#L49)):*
> ```Python
> def sendGripperCommand(targetPositionMM, force):
>     msg = lcmdrake.lcmt_schunk_wsg_command()
>     msg.utime = int(time.time()*1e6)
> ```

IIRC our coding style wants spaces around the `*`.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-Kbl-6yD-TPyEiUgXfM1:-Kbl-6yD-TPyEiUgXfM2:bwb9jml) ([raw file](https://github.com/robotlocomotion/drake/blob/3f1c5bc710e0d5437dda62758b2cdecb428961ac/drake/examples/kuka_iiwa_arm/director_ik_app.py#L65)):*
> ```Python
> def setupToolbar():
>     toolBar = applogic.findToolBar('Main Toolbar')
>     app.app.addToolBarAction(toolBar, 'Gripper Open', icon='', callback=gripperOpen)
> ```

Long line (and the next one)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-:-Kbl-IP-1DJAH1QtbsPR:basqp9p)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-Kbl-QSAYgUSjoQ24J2l:-Kbl74eZgiV_92QDQi8O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f1c5bc710e0d5437dda62758b2cdecb428961ac/drake/examples/kuka_iiwa_arm/director_ik_app.py#L49)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

IIRC our coding style wants spaces around the `*`.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4966#-Kbl-6yD-TPyEiUgXfM1:-Kbl75cZoOzXIYF13eqp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f1c5bc710e0d5437dda62758b2cdecb428961ac/drake/examples/kuka_iiwa_arm/director_ik_app.py#L65)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Long line (and the next one)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4966)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4966)*

**Pull request merged**
