### PR TITLE
faq: Add entry regarding #7991.

### LINKED ISSUE #7991: install_prereqs.sh Error
Before running this script i ran sudo apt update; sudo apt upgrade; sudo apt dist-upgrade
Then when following the build process I experienced this error.

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 coinor-libipopt1v5 : Depends: libmumps-seq-4.10.0 but it is not going to be installed
 dreal : Depends: coinor-libclp-dev but it is not going to be installed
 libboost-all-dev : Depends: libboost-date-time-dev but it is not going to be installed
                    Depends: libboost-filesystem-dev but it is not going to be installed
                    Depends: libboost-iostreams-dev but it is not going to be installed
                    Depends: libboost-log-dev but it is not going to be installed
                    Depends: libboost-python-dev but it is not going to be installed
                    Depends: libboost-system-dev but it is not going to be installed
                    Depends: libboost-thread-dev but it is not going to be installed
                    Depends: libboost-wave-dev but it is not going to be installed
 libhdf5-10 : Depends: libgfortran3 (>= 4.3) but it is not going to be installed
 libibex-dev : Depends: coinor-libclp-dev but it is not going to be installed
               Depends: zlib1g-dev but it is not going to be installed
 liblapack3 : Depends: libgfortran3 (>= 4.6) but it is not going to be installed
 libprotobuf-dev : Depends: zlib1g-dev but it is not going to be installed
 python-scipy : Depends: libgfortran3 (>= 4.6) but it is not going to be installed
 qtbase5-dev : Depends: libgl1-mesa-dev but it is not going to be installed or
                        libgl-dev
               Depends: libgles2-mesa-dev but it is not going to be installed or
                        libgles2-dev but it is not installable
               Depends: libglu1-mesa-dev but it is not going to be installed or
                        libglu-dev
               Depends: libqt5core5a (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5dbus5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5gui5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5network5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5printsupport5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5sql5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5test5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5widgets5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
               Depends: libqt5xml5 (= 5.5.1+dfsg-16ubuntu7) but 5.5.1+dfsg-16ubuntu7.5 is to be installed
E: Unable to correct problems, you have held broken packages.
The Drake source distribution prerequisite setup script has experienced an error on line 15 while running the command source "${BASH_SOURCE%/*}/install_prereqs_binary_distribution.sh"
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #7991.

\cc @airfield20

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8007)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8007#-:-L4rAOMYHe1H6yqz-2po:bcbis2v)*

**Comment by jwnimmer-tri** [comment]
I doubt that `xenial-backports` needs to be enabled, and in general it is not a thing we should tell people to do.

**Comment by EricCousineau-TRI** [comment]
Removed.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8007#-:-L4rB5yZlCto3k_15cYW:bss4a2b)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8007#-L4rB_4kGYSLsiN0arGW:-L4rB_4kGYSLsiN0arGX:b-ajscb9) ([raw file](https://github.com/robotlocomotion/drake/blob/3a4ba462a6763e6253574f2b165f3369d60a21a3/doc/faq.rst#L136)):*
> ```reStructuredText
> 
> **Symptom**: You have a fresh install of Ubuntu 16.04 (Xenial), and have run ``sudo apt upgrade; sudo apt dist-upgrade``.
> When you try to run ``install_prereqs.sh`` from Drake, you get errors such as::
> ```

BTW, is the solution really required for a fresh installation of Ubuntu 16.04? (i.e. what's the default settings for the source lists?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8007)*

**Comment by jamiesnape** [comment]
Presumably, you would get the same error running `install_prereqs_binary_distribution.sh` directly, or more importantly `install_prereqs` in the binary packages.

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8007#-L4rB_4kGYSLsiN0arGW:-L4rCqJOiEA1cKAo2k-F:b-vaqr65) ([raw file](https://github.com/robotlocomotion/drake/blob/3a4ba462a6763e6253574f2b165f3369d60a21a3/doc/faq.rst#L136)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, is the solution really required for a fresh installation of Ubuntu 16.04? (i.e. what's the default settings for the source lists?)
</blockquote></details>

BTW Installing with all the defaults, I have:
```
#deb cdrom:[Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)]/ xenial main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb http://security.ubuntu.com/ubuntu xenial-security main restricted
# deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
# deb-src http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
# deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8007)*

**Comment by jamiesnape** [comment]
I don't see anything that needs `multiverse` enabled, nor `restricted` for that matter.

**Comment by jwnimmer-tri** [comment]
I guess I'm a little hesitant to add an Answer (as in FAQ) until we've understood the problem and tested that the solution is correct.  @EricCousineau-TRI were you able to repro the problem and observe that this was a fix?

**Comment by EricCousineau-TRI** [comment]
No, I had been unable to reproduce this on a Docker image of `ubuntu:16.04`, but that's probably because either (a) the default packages aren't affected by the `dist upgrade` or (b) the Docker image is more up-to-date, so I worded it as a "maybe" with a non-conservative possible solution.
I can label this as a "do not merge" until I get a better reproduction.

I would like to have some concrete goal to close the issue.

**Comment by jwnimmer-tri** [comment]
In your shoes, I would just close #7991 as "user can no longer reproduce the problem" and wait until it happens again.

**Comment by EricCousineau-TRI** [comment]
Closing per discussion.

**Pull request closed without merging**
