### PR TITLE
[sensors] Add depth image conversion helpers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19437.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a grab bag of design and implementation questions.

> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-:-NW2z2s7-S5tYR-88t3O:bjazedn)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`-- commits` line 6 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2_C3T51dQlmqreOPX):*
nit typo



_Suggestion:_
```
it's
```
___
*[`systems/sensors/image.cc` line 24 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2aFxP7tYoX7y21NOj:-NW2aFxP7tYoX7y21NOk:b-p9e1xo) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L24)):*
> ```cpp
>     return;
>   }
>   const typename InputImage::T* in = input.at(0, 0);
> ```

BTW The contrast between `in` and `out` would read a bit better if the differences between them were only the significant ones. 



_Suggestion:_
```cpp
const typename InputImage::T* const in = input.at(0, 0);
```
___
*[`systems/sensors/image.cc` line 32 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2yHX8EcYDpH-aUlFb:-NW2yHX8EcYDpH-aUlFc:b-3yw3ah) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L32)):*
> ```cpp
> }  // namespace
> 
> void ConvertDepth32FTo16U(const ImageDepth32F& input, ImageDepth16U* output) {
> ```

BTW Is there a strong reason to prefer `void` with an output parameter instead of simply returning the other type? Images are very amenable to move semantics.
___
*[`systems/sensors/image.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2kJ-N1xLQ_1D4ZtSj:-NW2kJ-N1xLQ_1D4ZtSk:b-i6wp8i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L38)):*
> ```cpp
>         // Start by scaling from meters to millimeters, using 64-bit doubles to
>         // mitigate roundoff errors.
>         double result = pixel * 1000.0;
> ```

BTW I've been trying to craft some value of `pixel` for which this matters and I have failed. In principle, I get it. However, my mental model of how single-precision math gets done made me curious to see if this really mattered. My mental model consists of two principles:

1. On modern 64-bit processors, single-precision math is done with double-precision math and the answer is reduced in precision subsequently.
2. 1000.0 is perfectly represented by single-precision float.
3. 32-bit float has 24 bits of mantissa which is eventually reduced to 16 bits. It has more than enough bits to handle any precision errors out at what would be the 25th bit.

So, with those thoughts in mind, it's difficult to see how this `double` detour matters. And in the limited tests I did, I couldn't get it to matter.

Am I missing something?
___
*[`systems/sensors/image.cc` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2oKD3BN0P-g7hkMQL:-NW2oKD3BN0P-g7hkMQM:b-3yap4r) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L41)):*
> ```cpp
>         // Clamp too-far values (including +Inf and NaN) to the 16-bit constant.
>         result = std::min<double>(ImageDepth16U::Traits::kTooFar, result);
>         // Clamp too-close values (including -Inf) to the 16-bit constant.
> ```

BTW Several questions:

1. Do we have a formal definition of what a "valid" depth image is?
    - The 16-bit depth image suggests that valid returns are strictly positive.
    - Presumably we would say the same thing about the 32-bit depth image.
2. Are these functions operating under the assumption that the input depth images are "valid" (in the sense of question 1)?
3. Do they get to have knowledge of how 'too close" is implemented (as the value zero)?

I'm sure you can see where this is going, if the answers to those questions are yes, then clamping at "too close" (i.e., `max(too_close, result)`) is redundant. If not, we should probably put some notes to future developers about this being isolated from those other concepts by design.

I note your conversion in the other direction does nail down the implementation of too close.
___
*[`systems/sensors/test/image_test.cc` line 222 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2xZcA9SDJxYXP1EOy:-NW2xZcBBhyOk9oUgjYk:b-8s2b13) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/test/image_test.cc#L222)):*
> ```cpp
>   EXPECT_EQ(image_out.width(), 0);
>   EXPECT_EQ(image_out.height(), 0);
> }
> ```

BTW To be pedantic, these tests would still pass if, instead of a for loop iterating over all pixels, you only ever converted the first pixel.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`systems/sensors/image.cc` line 32 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2yHX8EcYDpH-aUlFb:-NW37HEM58dL_ITJNH2c:b-esrpwi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  In the systems framework, outputs are pre-allocated and we want to scribble into them.  Even with move semantics, we'd still be allocating here, copying into the context buffer elsewhere, and then freeing the allocation.

In my next push I'll add a comment somewhere explaining the thought process.
</blockquote></details>

As I saw it, the allocation was purely in the vector that contained the pxiel data. That would simply be passed around. But, meh.
___
*[`systems/sensors/image.cc` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2oKD3BN0P-g7hkMQL:-NW37V6Z8J9YiOXkorvY:b-5qyw27) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Do we have a formal definition of what a "valid" depth image is?

Yes, that's a correct definition.  It's not valid for a float image to have negatives, infinities, or nans.

> Are these functions operating under the assumption that the input depth images are "valid" (in the sense of question 1)?

No.  We should be behave sensibly in case the user provides us with an invalid image. Converting negative values to valid-range integer depths would not be doing the user any favors.
</blockquote></details>

And given the promotion to a public API, being more defensive seems good.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`systems/sensors/image.cc` line 32 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2yHX8EcYDpH-aUlFb:-NW38ZyY6qzo0n7bGCOL:b-fxkr78) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As I saw it, the allocation was purely in the vector that contained the pxiel data. That would simply be passed around. But, meh.
</blockquote></details>

Also...do we do conversion as part of the system framework? Or are we anticipating that conversion might be done in such a system and are leaving the door open? (And, I'm particularly thinking of python bindings here...that is the tricky domain, isn't it?)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/sensors/image.cc` line 32 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2yHX8EcYDpH-aUlFb:-NW384WQ1pSXsZOx69fV:b-ji89qz) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L32)):*
> As I saw it, the allocation was purely in the vector that contained the pixel data. That would simply be passed around. But, meh.

Yes, it would be the vector where things allocated.

Still, as written there will be zero allocations (very cpu-cache-friendly), but with a return value there would always be one allocation (less friendly).

> Do we do conversion as part of the system framework?

Yes, in `RgbdSensor::CalcDepthImage16U`.

> (And, I'm particularly thinking of python bindings here...that is the tricky domain, isn't it?)

I don't understand what you're getting at.  The python bindings here are pretty vanilla and not particularly hazardous.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`systems/sensors/image.cc` line 32 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2yHX8EcYDpH-aUlFb:-NW3DoYvE4xy0LJIRb-C:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> As I saw it, the allocation was purely in the vector that contained the pixel data. That would simply be passed around. But, meh.

Yes, it would be the vector where things allocated.

Still, as written there will be zero allocations (very cpu-cache-friendly), but with a return value there would always be one allocation (less friendly).

> Do we do conversion as part of the system framework?

Yes, in `RgbdSensor::CalcDepthImage16U`.

> (And, I'm particularly thinking of python bindings here...that is the tricky domain, isn't it?)

I don't understand what you're getting at.  The python bindings here are pretty vanilla and not particularly hazardous.
</blockquote></details>

Done.
___
*[`systems/sensors/image.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2kJ-N1xLQ_1D4ZtSj:-NW3JJVqAtI5iOVMZX5f:b-jb6su4) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L38)):*
Done.

The space of 32-bit floats in the 0m-66m range are few enough that it's plausible to just brute force search them.  I did that, and added a test case to cover an edge case I found.

As it turns out, to avoid roundoff errors in this direction it's actually better to stick with **floats**.

Here's the python reproducer for where the multiplication varies:

```
>>> np.float64(65.531)*np.float64(1000)
65531.00000000001
>>> np.float32(65.531)*np.float32(1000)
65531.0
>>> np.float32(65.531)*np.float64(1000)
65530.99822998047
```

In the last case, truncating to 65530 is unwanted.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 10 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-:-NW3m2S82I4KOKa2qWnl:bnfp4nl)* status: 2 unresolved discussions

___
*[`systems/sensors/test/image_test.cc` line 214 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW3lDbK2drkjtzxgJXJ:-NW3lDbK2drkjtzxgJXK:b-do2v7a) ([raw file](https://github.com/RobotLocomotion/drake/blob/446dc2a81a499386a508ed5f10c0c5378f02d12b/systems/sensors/test/image_test.cc#L214)):*
> ```cpp
>   using InPixel = ImageDepth32F::Traits;
>   using OutPixel = ImageDepth16U::Traits;
>   const std::vector<std::pair<float, uint16_t>> test_cases{
> ```

BTW:  Yay!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19436)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

___
*[`systems/sensors/image.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19436#-NW2kJ-N1xLQ_1D4ZtSj:-NW3p7dJAzwfhLrH_14I:bw0ango) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a2df6dd063c57baac901d7918e04c6af4d35b31/systems/sensors/image.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

The space of 32-bit floats in the 0m-66m range are few enough that it's plausible to just brute force search them.  I did that, and added a test case to cover an edge case I found.

As it turns out, to avoid roundoff errors in this direction it's actually better to stick with **floats**.

Here's the python reproducer for where the multiplication varies:

```
>>> np.float64(65.531)*np.float64(1000)
65531.00000000001
>>> np.float32(65.531)*np.float32(1000)
65531.0
>>> np.float32(65.531)*np.float64(1000)
65530.99822998047
```

In the last case, truncating to 65530 is unwanted.
</blockquote></details>

That's kind of cool. And disappointing.

**Pull request merged**
