### PR TITLE
Add ParameterizedTypeMap

### PR DESCRIPTION
**Pull request by tkoolen**
Adds ParameterizedTypeMap, basically a map from a type `T` to (a `shared_ptr` to) an instance of `ValueType<T>`. This will come in very handy when using the `jacobian`/`hessian` functionality introduced in https://github.com/RobotLocomotion/drake/pull/3321. It may also be useful for https://github.com/RobotLocomotion/drake/issues/1763 and https://github.com/RobotLocomotion/drake/issues/2235.

See the change in `rigid_body_tree_inverse_dynamics_test.cc` for an example use case. The point is that if lambda `qd_to_coriolis_term` is called a second time with an argument that has the same scalar type, then the preexisting `KinematicsCache` is used instead of a new one, greatly reducing allocations. This will be important to achieve efficient trajectory optimization, for example.

If anyone has a better name for this map, let me know.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3567)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Thank you for your interest in contributing to Drake!  This PR has seen no updates in over one month, so I am going to close it.  Please feel free to re-open (or open a fresh PR) if there are new updates to consider.

**Pull request closed without merging**
