### PR TITLE
Refactor convex optimization test

### PR DESCRIPTION
**Pull request by hongkai-dai**
Separates the test in `convex_optimization_program_test` so that they are called in the test for each solver. This is a preparation step to add the test for SCS on second order conic program and SDP.

There is no real change in the code, just moving the original code from one file to the other.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7489)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-:-Kz1tlCSVE6BlsNqlT3R:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor BTWs on existing code.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9qaR2fzUHWZ4u6pLv:-Kz9qaR2fzUHWZ4u6pLw:b-fanhnb) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L21)):*
> ```cpp
> TestEllipsoidsSeparation::TestEllipsoidsSeparation() {
>   switch (GetParam()) {
>     case EllipsoidsSeparationProblem::kProblem0:
> ```

BTW minor nit Could you place these in curly braces? No fall through will happen at present, but I tend to like having them just in case.
http://drake.mit.edu/styleguide/cppguide.html#Loops_and_Switch_Statements

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9r1BGbTF-kxQ5rtY9:-Kz9r1BHXbtKC8RSSe5b:b-sjcfwv) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L51)):*
> ```cpp
>       R2_ << 0.1, 0.2, -0.1, 0.01, -0.2, 0.1;
>       break;
>   }
> ```

BTW Can you add a `default: { DRAKE_ASSERT(false); }` here, just for consistency?

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9rBDYXPoKSRQ0ycgB:-Kz9rBDYXPoKSRQ0ycgC:b-63bwt6) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L78)):*
> ```cpp
>   Eigen::VectorXd b_lorentz1 = Eigen::VectorXd::Zero(1 + R1_.cols());
>   Eigen::VectorXd b_lorentz2 = Eigen::VectorXd::Zero(1 + R2_.cols());
>   auto lorentz_cone1 = prog_
> ```

BTW minor nit Clang format looks a tad odd; could this be reformatted to something like?
```
auto lorentz_cone2 =
    prog_A_lorentz2, b_lorentz2, {t.segment<1>(1), a_}).constraint();
```

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sQhANwwSQM8VrW2D:-Kz9sQhANwwSQM8VrW2E:b-xefuoe) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L234)):*
> ```cpp
>   RunSolver(&prog_socp_, solver);
>   const auto& x_socp_value = prog_socp_.GetSolution(x_socp_);
>   double objective_value_socp =
> ```

BTW super minor Can `objective_value_socp` be `const`?
(Same for some of the other values near here.)

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sbPC8QIofxdW5O30:-Kz9sbPC8QIofxdW5O31:b-hte9bm) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L240)):*
> ```cpp
>   const int kXdim = Q_.rows();
>   const Eigen::MatrixXd Q_symmetric = 0.5 * (Q_ + Q_.transpose());
>   Eigen::LLT<Eigen::MatrixXd, Eigen::Upper> lltOfQ(Q_symmetric);
> ```

BTW super minor Can these be `const` too?

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 268 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9siaXLAVW71qEC_qv:-Kz9siaXLAVW71qEC_qw:b-lm860e) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L268)):*
> ```cpp
> TestFindSpringEquilibrium::TestFindSpringEquilibrium() {
>   switch (GetParam()) {
>     case FindSpringEquilibriumProblem::kProblem0:
> ```

BTW minor nit Same as above; can this `switch` statement have a `break`, and be surrounded with curly braces `{}`?

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 280 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sv5ZRD4NTZ-d9nxU:-Kz9sv5_T19jXTeHqfcE:b-r2i99h) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L280)):*
> ```cpp
>   y_ = prog_.NewContinuousVariables(num_nodes, "y");
>   t_ = prog_.NewContinuousVariables(num_nodes - 1, "t");
>   prog_.AddBoundingBoxConstraint(end_pos1_, end_pos1_,
> ```

BTW Hmm... Didn't realize we didn't have a simple equality constraint. Should we add that in to the API?

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9u7B9-u9Es9BrBvwV:-Kz9u7BATDr8479eUIG6:b2dcgw0) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L303)):*
> ```cpp
>     A_lorentz1(2, 3) = -1;
>     Eigen::Vector3d b_lorentz1(spring_rest_length_, 0, 0);
>     prog_.AddLorentzConeConstraint(
> ```

BTW Could this use the symbolic version of the formulation? (for readability, possibly eliminating the need for the comment if the expressions (linear / quadratic) are labeled?)

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeObd5sOX9Zqo_dV-:-KzAeObd5sOX9Zqo_dV0:b-h48309) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L363)):*
> ```cpp
>                            right_spring_length;
>     }
>     Eigen::Vector2d weight_i(0, -weight_(i));
> ```

BTW super minor `const`? (here and a few other places)

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeiY8kqUQbM7LAX9O:-KzAeiY8kqUQbM7LAX9P:bbn96cn) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L22)):*
> ```cpp
> 
>   auto S = prog.NewSymmetricContinuousVariables<2>("S");
> ```

BTW super minor Odd line spacing?

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAey80PLlBxsUqTsuz:-KzAey80PLlBxsUqTsv-:b-56cfpm) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L152)):*
> ```cpp
>       0.2, 2, -0.1,
>       0.3, -0.1, 4;
>   // clang-format on
> ```

BTW Consider turning off `clang-format` for this entire block?

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAfCtkTTDUIISIHWHe:-KzAfCtkTTDUIISIHWHf:brenajx) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L171)):*
> ```cpp
>   RunSolver(&prog, solver);
> 
>   double z_value = prog.GetSolution(z(0));
> ```

BTW minor `const`?

---

*[drake/solvers/test/semidefinite_program_examples.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAf1aOkyt_cUq-47XH:-KzAf1aOkyt_cUq-47XI:b-1er6c0) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.h#L26)):*
> ```objc
> void FindCommonLyapunov(const MathematicalProgramSolverInterface& solver);
> 
> /*
> ```

BTW super minor Consistency, `/*` and `//` used for non-public Doxygen?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-:-KzAgyK6apTsdz7HeisY:bf8td0b)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please. Sorry to add this to your pile. No need to rush, this PR is not urgent.

---

Review status: 5 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9qaR2fzUHWZ4u6pLv:-KzBXl1BdHL0R2Eb0KSW:b-ycw6ux) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Could you place these in curly braces? No fall through will happen at present, but I tend to like having them just in case.
http://drake.mit.edu/styleguide/cppguide.html#Loops_and_Switch_Statements
</blockquote></details>

Done. Thanks! I didn't know this.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9r1BGbTF-kxQ5rtY9:-KzBXpoCekcwPHzqtVa1:bzd07vq) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L51)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you add a `default: { DRAKE_ASSERT(false); }` here, just for consistency?
</blockquote></details>

I think the compiler will throw an error, if the `switch` loop does not go through every item in `EllipsoidsSeparationProblem`. If we add `default`, then the compiler won't throw that error. I would prefer to let the compiler catch that, in case we add another item to `EllipsoidsSeparationProblem` in the future, and forgot to add the case in the `switch` loop.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9rBDYXPoKSRQ0ycgB:-KzBZIQY7_3RzHxVdaLI:bkwytml) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L78)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Clang format looks a tad odd; could this be reformatted to something like?
```
auto lorentz_cone2 =
    prog_A_lorentz2, b_lorentz2, {t.segment<1>(1), a_}).constraint();
```
</blockquote></details>

Done. I changed these constraints to symbolic form, to make it easier for the user to understand.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sQhANwwSQM8VrW2D:-KzB__q5_d9vVyY5na2S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L234)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor Can `objective_value_socp` be `const`?
(Same for some of the other values near here.)
</blockquote></details>

Done.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sbPC8QIofxdW5O30:-KzB_eKHKv6Jyg01y_XN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L240)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor Can these be `const` too?
</blockquote></details>

Done.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 268 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9siaXLAVW71qEC_qv:-KzB_jLSflyik_7BsRO4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L268)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Same as above; can this `switch` statement have a `break`, and be surrounded with curly braces `{}`?
</blockquote></details>

Done.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 280 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9sv5ZRD4NTZ-d9nxU:-KzB_kqcb2vknakd2tNE:b-kni9j9) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L280)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Hmm... Didn't realize we didn't have a simple equality constraint. Should we add that in to the API?
</blockquote></details>

Totally agree, I actually have a TODO in `scs_solver`, that requires us adding a `FixValueConstraint`. https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/scs_solver.cc#L136

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9u7B9-u9Es9BrBvwV:-KzBa8uxvzC9zeJ5suRm:b-23t6eo) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L303)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this use the symbolic version of the formulation? (for readability, possibly eliminating the need for the comment if the expressions (linear / quadratic) are labeled?)
</blockquote></details>

Great catch. I have added this in my another branch, which enables SCS for SOCP.  https://github.com/hongkai-dai/drake/blob/scs_socp_solver/drake/solvers/test/second_order_cone_program_examples.cc#L293~L295. Will send a PR on enabling SCS for SOCP soon.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 363 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeObd5sOX9Zqo_dV-:-KzBaaTJn63HYAnP_dCg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L363)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor `const`? (here and a few other places)
</blockquote></details>

Done.

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeiY8kqUQbM7LAX9O:-KzBahaS0DWjSKpg_vQI:bensfze) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor Odd line spacing?
</blockquote></details>

Could you be more specific? Do you mean I have an empty line between two lines of code? Does style guide require us to eliminate the empty lines?

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAey80PLlBxsUqTsuz:-KzBb6N0BZErX8KUzJKM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L152)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Consider turning off `clang-format` for this entire block?
</blockquote></details>

Done.

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAfCtkTTDUIISIHWHe:-KzBb9GOmYW9CEYHPFWR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L171)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor `const`?
</blockquote></details>

Done.

---

*[drake/solvers/test/semidefinite_program_examples.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAf1aOkyt_cUq-47XH:-KzBbIJETriPYBXw_G0D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor Consistency, `/*` and `//` used for non-public Doxygen?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-:-KzBcI-YoNYVC-qfHJ_1:bugq7v5)*

**Comment by sherm1** [comment]
Nice -- I really like these examples. :lgtm:
(Later I want to ask you about some problems we have that I think might be solvable as SOCPs)

---

Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/second_order_cone_program_examples.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzBhiiIQFE1kIVN4YEf:-KzBhiiIQFE1kIVN4YEg:b7rotxp) ([raw file](https://github.com/robotlocomotion/drake/blob/8d6964747babee86d215e53a0a7de5adeef95231/drake/solvers/test/second_order_cone_program_examples.h#L23)):*
BTW 

> https://inst.eecs.berkeley.edu/~ee127a/book/login/exa_ell_sep.html

This link didn't work for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-:-KzBih8iEvNR94RfGn43:b6bcjlf)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/second_order_cone_program_examples.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzBhiiIQFE1kIVN4YEf:-KzCGH3-UHMVSu8ONzSb:b3omzed) ([raw file](https://github.com/robotlocomotion/drake/blob/8d6964747babee86d215e53a0a7de5adeef95231/drake/solvers/test/second_order_cone_program_examples.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW 

> https://inst.eecs.berkeley.edu/~ee127a/book/login/exa_ell_sep.html

This link didn't work for me.
</blockquote></details>

Done. It was the online course notes of EE127A in Berkeley. They just used a new online book as the notes, which requires login. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/second_order_cone_program_examples.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-Kz9r1BGbTF-kxQ5rtY9:-KzQsrcjd01j7ayu_-05:b-13rs8z) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/second_order_cone_program_examples.cc#L51)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the compiler will throw an error, if the `switch` loop does not go through every item in `EllipsoidsSeparationProblem`. If we add `default`, then the compiler won't throw that error. I would prefer to let the compiler catch that, in case we add another item to `EllipsoidsSeparationProblem` in the future, and forgot to add the case in the `switch` loop.
</blockquote></details>

OK I'm fine with that.
The only caveat is that this is compile-time only; nothing is there to check if there is some sort of run-time corruption (e.g. someone uses `reinterpret_cast` to create a value that is not in the `enum`, or if there is ABI mismatch; granted, these are edge cases).

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeiY8kqUQbM7LAX9O:-KzQttatEFxfB8UMhDnR:b-k6cn0o) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you be more specific? Do you mean I have an empty line between two lines of code? Does style guide require us to eliminate the empty lines?
</blockquote></details>

The style guide is not strict on line spacing, but I am commenting on it because this style seems inconsistent with the other pieces of code in this file, and it's not clear why the line spacing is as it is (e.g. topic separation?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489)*

**Comment by hongkai-dai** [comment]
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/solvers/test/semidefinite_program_examples.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7489#-KzAeiY8kqUQbM7LAX9O:-KzS8c6qjBno86SUdBIZ:b-gp61s2) ([raw file](https://github.com/robotlocomotion/drake/blob/7936213b348e4554b41cb2b8a71aee07ee2be9a2/drake/solvers/test/semidefinite_program_examples.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

The style guide is not strict on line spacing, but I am commenting on it because this style seems inconsistent with the other pieces of code in this file, and it's not clear why the line spacing is as it is (e.g. topic separation?).
</blockquote></details>

Done. I added some comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7489)*

**Pull request merged**
