### PR TITLE
jupyter: Add joint sliders using publishing callback.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@avalenzu for feature review (please kick to platform if appropriate).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBE2xN19vvyuMpdJgs:b-9jfc06)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
`inspector()` comes to Jupyter! :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBesp2-0zCYR3MctA0:b-vvkjkx)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBdq047ifYbuLR4vlb:-MHBdq047ifYbuLR4vlc:bvrom1g) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L200)):*
> ```Python
>     slider_widgets = []
>     k = 0
>     for i in range(0, plant.num_joints()):
> ```

nit: Any reason not to just have `range(plant.num_joints())`? Same comment for `joint.num_positions()` loop below.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBfKlRBkHp_b_5fQE8:-MHBfKlRBkHp_b_5fQE9:ba6ecj) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L97)):*
> ```
>     "builder = DiagramBuilder()\n",
>     "plant, scene_graph = AddMultibodyPlantSceneGraph(builder, time_step=0.0)\n",
>     "Parser(plant, scene_graph).AddModelFromFile(FindResourceOrThrow(\n",
> ```

nit: Passing `scene_graph` to the parser is unnecessary. If you omit it, the parser will automatically use the one for which `plant` is registered as a source.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBelXNAIwOE0rjUMyx:-MHBelXNAIwOE0rjUMyy:b8dxuwm) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L147)):*
> ```
>  "nbformat": 4,
>  "nbformat_minor": 4
> }
> ```

nit: Missing newline at the end of this file

**Review by avalenzu — COMMENTED** [review]
+@ericcousineau-tri for platform review. Speed enhancing image:
```
       _                        
       \`*-.                    
        )  _`-.                 
       .  : `. .                
       : _   '  \               
       ; *` _.   `*-._          
       `-.-'          `-.       
         ;       `       `.     
         :.       .        \    
         . \  .   :   .-'   .   
         '  `+.;  ;  '      :   
         :  '  |    ;       ;-. 
         ; '   : :`-:     _.`* ;
[bug] .*' /  .*' ; .*`- +'  `*' 
      `*-*   `*-*  `*-*'
```
(ASCII art credit: Blazej Kozlowski, https://www.asciiart.eu/animals/cats)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBg1348Hwqc8SIFr1K:b-9id0q7)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
Speed enhancement activated!

Preview link:
https://mybinder.org/v2/gh/RussTedrake/drake/make_joint_sliders_callback?filepath=bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBoomx2vVh6OG4RYrc:bz3bz23)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @avalenzu and @RussTedrake)

___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBelXNAIwOE0rjUMyx:-MHBn6vxABwIcvyVgdec:b5xq3yg) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L147)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Missing newline at the end of this file
</blockquote></details>

FWIW It's an auto-generated JSON, so I'm fine either way here.

**Review by EricCousineau-TRI — COMMENTED** [review]
Er, meant `nbviewer`:
https://nbviewer.jupyter.org/github/RussTedrake/drake/blob/make_joint_sliders_callback/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBpJkz6G0DnxZFhk0p:bxpnis2)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @avalenzu and @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)* status: 7 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @avalenzu and @RussTedrake)

___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 211 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBq33W7oeljh1Ve5_k:-MHBq33W7oeljh1Ve5_l:b-2l5gnc) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L211)):*
> ```Python
>                 max=min(upp[j], upper_limit[k]),
>                 step=resolution[k],
>                 continuous_update=True,
> ```

Can you expose this as an option?

If a user has a callback that is more involved, e.g. rendering an image from a camera and displaying it in a widget, it will really slow down the notebook if the callback is continuous.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpWJM8DMYf3JEzvfL:-MHBpWJM8DMYf3JEzvfM:b-zcq2fj) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L35)):*
> ```
>     "# JointSliders\n",
>     "\n",
>     "Running this cell should allow you to control the joints of the IIWA in drake visualizer.  You must set `running_as_notebook` to `True` in the cell above."
> ```

To preface with a distinction, can you mention that this is intended for use with the Systems framework?

It's a bit odd to see a generic "joint sliders" utility, which means systems, and then a super verbose name which means non-systems.

I fine with it being as-is, but would be nice to preface in this example.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpn9A7c9WkV6HEXhX:-MHBpn9A7c9WkV6HEXhY:btpkora) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L107)):*
> ```
>     "context = diagram.CreateDefaultContext()\n",
>     "\n",
>     "callback_output = Text(value=\"\", description=\"Callback output: \", \n",
> ```

nit This is a bit of overkill for updating text.

I have the following code in Anzu:
```


# Adapted from `ipywidets.widgets.interaction`
@contextmanager
def interactive_update(out):
    with out:
        clear_output(wait=True)
        yield
        show_inline_matplotlib_plots()


def with_interactive_update(out):
    """Wrapper sugar for `interactive_update`."""

    def decorator(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            with interactive_update(out):
                return f(*args, **kwargs)

        return wrapped

    return decorator
```

Which then allows me to do stuff like:
```
my_output = widgets.Output()

@with_interactive_update(my_output)
def my_callback():
    print("This is my new text")  # This will appear in the output widget.
    plt.plot(...)  # Will be slower than interactive plotting, but wayyyy easier to prototype with.

display(my_sliders)
display(my_output)
```

I think this (and other things) would greatly benefit from having this option.

Do you want to add this here, or do you want me to add it in a follow-up PR?
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpuiZ9IIOren9UaZ0:-MHBpuiZ9IIOren9UaZ1:b-dmswpg) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L111)):*
> ```
>     "                       style={'description_width':'initial'})\n",
>     "def callback_test(context):\n",
>     "    callback_output.value = \"Successfully called callback\"\n",
> ```

Rather than just showing "Hey, this has been called", it would be nice to show "This has been called X times."

Can you add a counter to this?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with some comments

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059#-:-MHBtVaS62Fj1kqulFbV:b-wkd30r)* status: 12 unresolved discussions (waiting on @avalenzu and @RussTedrake)

___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBrcaZ1tRmzqOzJHkl:-MHBrcaZ1tRmzqOzJHkm:b-ftuo2) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L152)):*
> ```Python
>         my_callback:  An optional additional callback function that will be
>                       called once immediately and again whenever the sliders
>                       are moved, using ``my_callback(plant_context)``.
> ```

As a point of inspiration, can you add two examples?

e.g. "for outputting the text of joint positions, or showing a rendered image from a camera"?
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBs1V5404PCwMU0l7G:-MHBs1V5404PCwMU0l7H:bwqni0p) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L162)):*
> ```Python
>                       Joint.
>         resolution:   A scalar or vector of length robot.num_positions()
>                       that specifies the discretization of the slider.
> ```

nit "discretization" is ambiguous to me: it could mean number of steps, or step size.

Can you either use a better variable name (`num_steps` or `step_size`), or add better text ("specifies the discretization of the slider as step size of the joint's generalized coordinate")?
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBrsbDAJpQS4a5OS4I:-MHBrsbDAJpQS4a5OS4J:b14er5o) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L163)):*
> ```Python
>         resolution:   A scalar or vector of length robot.num_positions()
>                       that specifies the discretization of the slider.
>         length:       The length of the sliders.
> ```

Units? Is this supposed to be a string?

(Also, can you xref the Jupyter widgets documentation, here or at the top of this file, explicitly for relevant to something as ambiguous as "length" for the widget?)
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBtL6DBHRkeeJIicTF:-MHBtL6DBHRkeeJIicTG:b-hh4qsq) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L173)):*
> ```Python
>     """
> 
>     def _reshape(x, num):
> ```

nit `_reshape` usually just changes the shape tuple, but does not inject new data.

`_broadcast` seems like a better term for this operation.
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBt8qT0WEj71DRxDsT:-MHBt8qT0WEj71DRxDsU:broxm2n) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L199)):*
> ```Python
> 
>     slider_widgets = []
>     k = 0
> ```

nit `k` is a bit of an ambiguous variable name, especially since it has state across the iterations of these loops.

Can you rename this to `joint_index_offset` or something like that?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)* status: 6 unresolved discussions (waiting on @avalenzu and @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBrcaZ1tRmzqOzJHkl:-MHLJeLvCq-1VILwVTLo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L152)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

As a point of inspiration, can you add two examples?

e.g. "for outputting the text of joint positions, or showing a rendered image from a camera"?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBs1V5404PCwMU0l7G:-MHLJzDD4431M_nqMDe-:b-wjkicb) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L162)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "discretization" is ambiguous to me: it could mean number of steps, or step size.

Can you either use a better variable name (`num_steps` or `step_size`), or add better text ("specifies the discretization of the slider as step size of the joint's generalized coordinate")?
</blockquote></details>

Done. I don't want to change the name because it matches the JointSlider implementation. 
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBrsbDAJpQS4a5OS4I:-MHLKuCB5o5MOtRitbnq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L163)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Units? Is this supposed to be a string?

(Also, can you xref the Jupyter widgets documentation, here or at the top of this file, explicitly for relevant to something as ambiguous as "length" for the widget?)
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBtL6DBHRkeeJIicTF:-MHLLEiw1jWuOkK45OM3:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L173)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `_reshape` usually just changes the shape tuple, but does not inject new data.

`_broadcast` seems like a better term for this operation.
</blockquote></details>

Done
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBt8qT0WEj71DRxDsT:-MHLLWdM9l3JFhSU0kX0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L199)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `k` is a bit of an ambiguous variable name, especially since it has state across the iterations of these loops.

Can you rename this to `joint_index_offset` or something like that?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBdq047ifYbuLR4vlb:-MHLLbN06QyWusHje-qO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L200)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Any reason not to just have `range(plant.num_joints())`? Same comment for `joint.num_positions()` loop below.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/jupyter_widgets.py, line 211 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBq33W7oeljh1Ve5_k:-MHLMOUlAd9fmt6dAGJI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/jupyter_widgets.py#L211)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you expose this as an option?

If a user has a callback that is more involved, e.g. rendering an image from a camera and displaying it in a widget, it will really slow down the notebook if the callback is continuous.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpWJM8DMYf3JEzvfL:-MHLO9qG0UujS0afzlFC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L35)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

To preface with a distinction, can you mention that this is intended for use with the Systems framework?

It's a bit odd to see a generic "joint sliders" utility, which means systems, and then a super verbose name which means non-systems.

I fine with it being as-is, but would be nice to preface in this example.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBfKlRBkHp_b_5fQE8:-MHLODCT2oV3OtmwU3Cd:bm8ppsw) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L97)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Passing `scene_graph` to the parser is unnecessary. If you omit it, the parser will automatically use the one for which `plant` is registered as a source.
</blockquote></details>

Done.  TIL.  It makes total sense, but I've been using this pattern everywhere.
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpn9A7c9WkV6HEXhX:-MHLOayr5q5XtoonjJ1s:beb9q2s) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L107)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is a bit of overkill for updating text.

I have the following code in Anzu:
```


# Adapted from `ipywidets.widgets.interaction`
@contextmanager
def interactive_update(out):
    with out:
        clear_output(wait=True)
        yield
        show_inline_matplotlib_plots()


def with_interactive_update(out):
    """Wrapper sugar for `interactive_update`."""

    def decorator(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            with interactive_update(out):
                return f(*args, **kwargs)

        return wrapped

    return decorator
```

Which then allows me to do stuff like:
```
my_output = widgets.Output()

@with_interactive_update(my_output)
def my_callback():
    print("This is my new text")  # This will appear in the output widget.
    plt.plot(...)  # Will be slower than interactive plotting, but wayyyy easier to prototype with.

display(my_sliders)
display(my_output)
```

I think this (and other things) would greatly benefit from having this option.

Do you want to add this here, or do you want me to add it in a follow-up PR?
</blockquote></details>

If you want to PR it, I will definitely give it a spin.  FTR -- I *think* there is a meaningful distinction between the Text widget vs the Output widget here.   I often only want the most recent value to be displayed.  (one of my demos died when diff IK started spewing output so fast that the "Stop Simulation" button would roll off the screen).
___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpuiZ9IIOren9UaZ0:-MHLQQs_4Fhi8EL_e62Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L111)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than just showing "Hey, this has been called", it would be nice to show "This has been called X times."

Can you add a counter to this?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpn9A7c9WkV6HEXhX:-MHQqSdp3WcgRxAqwoIc:bv55ypu) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L107)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

If you want to PR it, I will definitely give it a spin.  FTR -- I *think* there is a meaningful distinction between the Text widget vs the Output widget here.   I often only want the most recent value to be displayed.  (one of my demos died when diff IK started spewing output so fast that the "Stop Simulation" button would roll off the screen).
</blockquote></details>

Yuppers, that's what the above code would do. It clears the output cell before.

I use it for printing text from a multi-model-instance plant (that can then be fed back in code cells), for showing images, or even for dynamically updating GUI elements (e.g. for labeling). I'll briefly ponder how to best present those items.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,EricCousineau-TRI(platform)

___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpn9A7c9WkV6HEXhX:-MHQym0F52cIQ6QVQhqG:bg6cz05) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L107)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yuppers, that's what the above code would do. It clears the output cell before.

I use it for printing text from a multi-model-instance plant (that can then be fed back in code cells), for showing images, or even for dynamically updating GUI elements (e.g. for labeling). I'll briefly ponder how to best present those items.
</blockquote></details>

OK I've filed #14082. Looks like I've been spoiled by newer ipywidgets; the version on Bionic's apt isn't up to speed. Will handle in that PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14059)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,EricCousineau-TRI(platform)

___
*[bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14059#-MHBpn9A7c9WkV6HEXhX:-MHQyxfS6oBrHPLcVkku:b-dwf1em) ([raw file](https://github.com/robotlocomotion/drake/blob/fa2b126f0944eb878710a159b0edf72e44c07b67/bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb#L107)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK I've filed #14082. Looks like I've been spoiled by newer ipywidgets; the version on Bionic's apt isn't up to speed. Will handle in that PR.
</blockquote></details>

(But for the record, the text output works!)

**Pull request merged**
