### PR TITLE
common: Move and polish yaml_read_archive out of dev

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #10869.

Note that this does _not_ yet mark it public.  That will be a follow-up, installation-related PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10919)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sammy-tri curious to get your thoughts here on naming.

I've put this into a `//common/yaml` subdirectory, because I'd like to keep the `yaml-cpp` dependency out of `//common:common`.

The class is named `YamlReadArchive`, so the header has to be named `yaml_read_archive.h` so we have `#include "drake/common/yaml/yaml_read_archive.h"` and `drake::yaml::YamlReadArchive`.

Should I rename the class to `class ReadArchive` and so `drake::yaml::ReadArchive` and `#include "drake/common/yaml/read_archive.h"`.  I am not sure the extra "yaml" is buying us anything.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

(Platform review will be as-new for the full 1000+ LOC, but it seems like that will be tractable.)

**Comment by jwnimmer-tri** [comment]
@soonho-tri please note that this is moving code from `dev` into non-dev, and so you'll need to review  the entire full files in the PR, not just the diffs.

**Comment by jwnimmer-tri** [comment]
@sherm1 note this needs a full platform review of all 1200 lines.  If that's too big to fit into your on-call day, we can spill to a volunteer instead.

**Comment by sherm1** [comment]
> note this needs a full platform review of all 1200 lines.

All I'm seeing is about 100 lines. Is something important missing?

**Comment by jwnimmer-tri** [comment]
Sorry, I guess this keeps getting lost in the noise of the top-level thread:

> Please note that this is moving code from dev into non-dev, and so you'll need to review the entire full files in the PR, not just the diffs.

**Pull request merged**
