### PR TITLE
Updating valgrind.sh file for Bazel

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Adding options from tools.cmake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5829)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/valgrind.sh, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5829#-KhdfSIxpuoEvE5pTk8b:-KhdfSIyhtBdMgskOAer:b-qxam4m) ([raw file](https://github.com/robotlocomotion/drake/blob/8d1b295ad26a212391f59e94aea42dde65643ca7/tools/valgrind.sh#L13)):*
> ```Shell
>     --track-origins=yes \
>     --show-leak-kinds=definite,possible \
>     --gen-suppressions=all \
> ```

Remove --gen-suppressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5829)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind.sh, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5829#-KhdfSIxpuoEvE5pTk8b:-Khh4M16ib0dwcy87B5F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d1b295ad26a212391f59e94aea42dde65643ca7/tools/valgrind.sh#L13)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove --gen-suppressions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5829)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5829#-:-KhhAIU0YhRG7DfbNNfC:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5829#-:-KhhEuMI-WZE7o6-uYzH:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5829#-:-KhhF4G2MbOM-jzuzwPQ:b-yug89b)*

**Pull request merged**
