### PR TITLE
[geometry/dev] Add RenderEngineGltfClient unit tests.

### PR DESCRIPTION
**Pull request by svenevs**
- [X] Prerequisite: #16802 merges and this is rebased.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@zachfang for review please.  Full coverage (via `kcov`), these tests do have validation that a "round trip" with a fake server work as expected (piggy-backing off of the similar `TestPng` and `TestTiff` image patterns) but nothing with an actual server.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793#-:-MyCWhEF6H-f2kZm--1F:b-qry717)* status: 3 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/render_engine_gltf_client.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCWozCCcW8pl9g65rI:-MyCWozCCcW8pl9g65rJ:b3ku0uj) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/render_engine_gltf_client.cc#L20)):*
> ```cpp
> namespace render {
> 
> namespace fs = drake::filesystem;
> ```

FYI I updated the usage of `drake::filesystem` to just be `fs` everywhere for consistency with the other files.  Update in the future when `std::filesystem` can be used becomes easier, those changes just become `namespace fs = std::filesystem`.
___
*[geometry/render/dev/render_engine_gltf_client.cc, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCX2jf4KESXyCutCLA:-MyCX2jf4KESXyCutCLB:b6oweij) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/render_engine_gltf_client.cc#L132)):*
> ```cpp
> void DeleteFileAndLogIfVerbose(const std::string& path, bool verbose) {
>   try {
>     fs::remove(path);
> ```

FYI using `std::filesystem::remove` is a better approach than using the older `std::remove`, it's otherwise doing the same thing just with better error handling / message propagation.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCXaMP8W2KA4Fj6NlU:-MyCXaMP8W2KA4Fj6NlV:b-gwsx9v) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L180)):*
> ```cpp
>    via transpose, and inverting the translation.  We do not need to be concerned
>    about non-uniform scaling on the diagonal. */
>   auto pseudo_inverse = [](const Eigen::Matrix4d& mat) {
> ```

FYI doing a full matrix inverse is less reliable for numerical testing.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 208 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCXeu86dwsM0iYf8Vw:-MyCXeu86dwsM0iYf8Vx:b-8u49jb) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L208)):*
> ```cpp
>      Compare this to the declared `translation` vector used to create X_WB,
>      GLTF is correct. */
>     EXPECT_TRUE(translation.isApprox(gltf.topRightCorner<3, 1>(), tolerance));
> ```

I'm going to mark this as a blocking comment, I included tests here because this method is somewhat awkward (the `UpdateViewpoint` method), but I do not believe it is a good use of time to figure out what is going on with the translation vector.  Perhaps platform review will decide otherwise, but it is not clear to me why this happens.  If you recall, if the `UpdateViewpoint` just calls `RenderEngineVtk::UpdateViewpoint` without hacking the transformation, nothing is in view due to the bug in vtk not exporting the right matrix for glTF.  So if anything, the would-be render acceptance tests are a better test than this?

Either way, this test is strange enough to call out directly, but the fact that the rotations are inversions of each other as expected indicates to me that we're probably good enough.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCYaiU0S48OyKLfXQg:-MyCYaiU0S48OyKLfXQh:bjijaek) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L286)):*
> ```cpp
>       files[0].extension() == ".gltf" && files[1].extension() == ".png";
>   bool png_gltf =
>       files[1].extension() == ".gltf" && files[0].extension() == ".png";
> ```

TODO: `const`
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCYhGQ8suFIdm29YvY:-MyCYhGQ8suFIdm29YvZ:bjijaek) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L323)):*
> ```cpp
>   bool gltf_tiff =
>       files[0].extension() == ".gltf" && files[1].extension() == ".tiff";
>   bool tiff_gltf =
> ```

TODO: `const`

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793)* status: 4 unresolved discussions, LGTM missing from assignee zachfang (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_engine_gltf_client.cc, line 360 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyDIEYaDH276HL24vYf:-MyIZrCW-f-ytGcK0rHQ:b-4ekr2z) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/render_engine_gltf_client.cc#L360)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done.  Unfortunately, it cannot be.  `GetModelViewTransformMatrix()` is not a `const` method, it returns the pointer directly and technically you can modify the object.  That said, it throws a giant warning about how this is deprecated behavior and will be removed at some point in the future (why we have to do the `hacked_matrix` in `UpdateViewpoint`).
</blockquote></details>

OK. Thanks!
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 208 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCXeu86dwsM0iYf8Vw:-MyIcetn0ebxSNkfxzcy:bac2oi7) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L208)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Update: I added additional comments explaining why we expect the matrix to be inverted, I tried a quick test to compare against `X_WB` but it did not work as expected.  I think the comment explaining the translation makes more sense now, but it is dubious that `RenderEngineVtk::UpdateViewpoint` is not working correctly and perhaps there is something wrong with the test setup.
</blockquote></details>

Thanks for updating the comments.

Now I think about it more on this test. In terms of the matrix inversion, should the translation be `-inv_RT` rather than just `-T`?
https://mathematica.stackexchange.com/questions/106257/how-do-i-get-the-inverse-of-a-homogeneous-transformation-matrix
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 399 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyDqsQA8mKk_kASWNtg:-MyIYRKCCYqWcwYoZ78q:b-1ehfk0) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/test/render_engine_gltf_client_test.cc#L399)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Yes and no, the file has contents but it isn't meaningful:

```json
{                                                                                                                                                       
   "accessors" : null,                                                                                                                                  
   "asset" :                                                                                                                                            
   {                                                                                                                                                    
      "generator" : "VTK",                                                                                                                              
      "version" : "2.0"                                                                                                                                 
   },                                                                                                                                                   
   "bufferViews" : null,                                                                                                                                
   "buffers" : null,                                                                                                                                    
   "cameras" : null,                                                                                                                                    
   "materials" : null,                                                                                                                                  
   "meshes" : null,                                                                                                                                     
   "nodes" : null,                                                                                                                                      
   "scene" : 0,                                                                                                                                         
   "scenes" :                                                                                                                                           
   [                                                                                                                                                    
      {                                                                                                                                                 
         "name" : "Layer 0",                                                                                                                            
         "nodes" : null                                                                                                                                 
      }                                                                                                                                                 
   ]                                                                                                                                                    
}
```
</blockquote></details>

OK, thanks. Just out of curiosity. 
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 409 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyDtts51nQw8p0hDPR3:-MyIZ98J5zKPGNKex0N9:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/test/render_engine_gltf_client_test.cc#L409)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, removed and agreed.
</blockquote></details>

OK.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 416 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyDuIi55PCMhH8yWqI2:-MyIZGZhD1SwGvmh1RkX:b-wn458j) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/test/render_engine_gltf_client_test.cc#L416)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, good call.  I made `params.verbose = true` and got rid of the loop.  I _believe_ it is important that the coverage for the logging gets hit in tests because AFAIU the debug builds actually use spdlog, so any errors such as `drake::log()->debug("{} {}", only_one_parameter_should_have_been_two)` will crash.  The logging output would have to have a sink and other stuff to validate its contents, I think it is enough to make sure they run.
</blockquote></details>

OK. Agreed and the intent is clearer now.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 130 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyHbbiu4155AL-PV8zV:-MyIbKpOEmbTDedSOwxp:b-7vw46n) ([raw file](https://github.com/robotlocomotion/drake/blob/aef867194d4995bbda1740869ab14aa004647de7/geometry/render/dev/test/render_engine_gltf_client_test.cc#L130)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Calling out for review, the `DoRender*Image` tests all changed to have a loop

```cpp
for (const bool no_cleanup : {true, false}) {
  // ...
}
```

Inspired by some of your other review comments, this one is worth testing explicitly that `CleanupFrame` is being called and our temporary directory is getting freed up.  It also reduces the amount of copy-pasted code between the test cases.

Question: style wise, should I move these down to below the `class FakeServer : HttpService { ... };` since they are not used until later?   
</blockquote></details>

OK. Agree to move the function closer to the `DoRender*Image` test body. At least for me, it's easier to follow.

**Review by svenevs — COMMENTED** [review]
Ok, `UpdateViewpoint` method has been fixed up to do the correct transformation comparison.  Adding a mac CI test to make sure our comparisons are thresholded appropriately on other platforms.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793#-:-MyKaF1qDp039HdB1pDb:bth5m8o)* status: 2 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 208 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCXeu86dwsM0iYf8Vw:-MyK_9nU0MKua6FnaENH:b8yjznl) ([raw file](https://github.com/robotlocomotion/drake/blob/63ad09808ad626691108c0ccd236941b7b6fc580/geometry/render/dev/test/render_engine_gltf_client_test.cc#L208)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Thanks for updating the comments.

Now I think about it more on this test. In terms of the matrix inversion, should the translation be `-inv_RT` rather than just `-T`?
https://mathematica.stackexchange.com/questions/106257/how-do-i-get-the-inverse-of-a-homogeneous-transformation-matrix
</blockquote></details>

Done (!!!!!!), you are exactly correct -- I was not fully inverting the VTK matrix.  The test has been updated now, you have to rotate the negated translation (not just negate the translation :dodo:).  They are validated separately with more useful error messages (in the event the test fails) rather than just a statement that `true` was expected but got `false`.
___
*[geometry/render/dev/test/render_engine_gltf_client_test.cc, line 130 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyHbbiu4155AL-PV8zV:-MyK_5OBArLQr1NJB9kn:b-ec3baa) ([raw file](https://github.com/robotlocomotion/drake/blob/aef867194d4995bbda1740869ab14aa004647de7/geometry/render/dev/test/render_engine_gltf_client_test.cc#L130)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. Agree to move the function closer to the `DoRender*Image` test body. At least for me, it's easier to follow.
</blockquote></details>

OK, works for me -- moved! :slightly_smiling_face:

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793)* status: 1 unresolved discussion, LGTM missing from assignee zachfang (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793)* status: 1 unresolved discussion, LGTM missing from assignee zachfang (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCbzKsAb_q9OFBqJqp:-MyKgB2o4cZsNhtMg_Mz:ba5v8on) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/BUILD.bazel#L192)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

```
=================================================================
==20==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6280 byte(s) in 3 object(s) allocated from:
    #0 0x55af7105e440 in calloc (/path/to/render_engine_gltf_client_test+0x51a440)
    #1 0x151167cd814f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6614f)

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x55af7105e52a in realloc (/path/to/render_engine_gltf_client_test+0x51a52a)
    #1 0x151167cd738a  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6538a)

Indirect leak of 143712 byte(s) in 449 object(s) allocated from:
    #0 0x55af7105e440 in calloc (/path/to/render_engine_gltf_client_test+0x51a440)
    #1 0x151167cd814f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6614f)

Indirect leak of 5066 byte(s) in 371 object(s) allocated from:
    #0 0x55af7105e2d5 in malloc (/path/to/render_engine_gltf_client_test+0x51a2d5)
    #1 0x151167cd7cbc  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe65cbc)

Indirect leak of 752 byte(s) in 6 object(s) allocated from:
    #0 0x55af7105e52a in realloc (/path/to/render_engine_gltf_client_test+0x51a52a)
    #1 0x151167cd738a  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6538a)

SUMMARY: LeakSanitizer: 156834 byte(s) leaked in 830 allocation(s).
================================================================================
```

It comes from the `DoRenderColorImage`, `DoRenderDepthImage`, and `DoRenderLabelImage` tests specifically.  I think it is alright to mark this as skipped for `lsan` (via `vtk_test_tags()`) but wanted to get confirmation.  It makes sense, it calls the vtk rendering pipeline updates behind the scenes.
</blockquote></details>

Let's add something like this (feel free to tweak to be accurate).

```
Found leakage potentially from RenderEngineVtk::PerformUpdate(). Mark it as skipped now, and will revisit during the platform review.

Example log from LeakSanitizer:
==20==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6280 byte(s) in 3 object(s) allocated from:
    #0 0x55af7105e440 in calloc (/path/to/render_engine_gltf_client_test+0x51a440)
    #1 0x151167cd814f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6614f)
...
```

**Review by svenevs — COMMENTED** [review]
Mac job was a success, this :lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793#-:-MyN-xrN5ywxXXVoYGDJ:b-6xavju)* status: LGTM missing from assignee zachfang (waiting on @svenevs)

___
*[geometry/render/dev/BUILD.bazel, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16793#-MyCbzKsAb_q9OFBqJqp:-MyN-s8k7PgIqHtGKFW7:b-5ys02d) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb9beb19f42c3c5aa2c8a1a026c7c84f096cb46/geometry/render/dev/BUILD.bazel#L192)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Let's add something like this (feel free to tweak to be accurate).

```
Found leakage potentially from RenderEngineVtk::PerformUpdate(). Mark it as skipped now, and will revisit during the platform review.

Example log from LeakSanitizer:
==20==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6280 byte(s) in 3 object(s) allocated from:
    #0 0x55af7105e440 in calloc (/path/to/render_engine_gltf_client_test+0x51a440)
    #1 0x151167cd814f  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.47.03+0xe6614f)
...
```

</blockquote></details>

Done, added comment for it to stick out in platform review :+1:

**Review by svenevs — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793#-:-MyN0DKQDaTrZ0c5HdC0:bnfp4nl)* status: LGTM missing from assignee zachfang (waiting on @svenevs)

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16793#-:-MyN1KJw5Ua3dIrM8xJc:b-uwkowd)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

**Pull request merged**
