### PR TITLE
[py/systems] Add bindings for UnrestrictedUpdate and DeclareForced*Event

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16266)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
Another round of missing system bindings.
+@sherm1 for (both?) reviews, if your comfortable with it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16266#-:-MrQ0Uq3EiNJHhhrTAJ0:buit7wf)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 904 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16266#-MrQ2MWi7NWcd8DUxSNN:-MrQ2MWi7NWcd8DUxSNO:b71rxaq) ([raw file](https://github.com/robotlocomotion/drake/blob/750dd54641591bd94a3838ef58bc6572914ec606/bindings/pydrake/systems/framework_py_systems.cc#L904)):*
> ```cpp
>             &LeafSystemPublic::DoCalcDiscreteVariableUpdates,
>             doc.LeafSystem.DoCalcDiscreteVariableUpdates.doc)
>         .def("DoCalcUnrestrictedUpdate",
> ```

btw -- we could avoid binding this, if we want to encourage people to **only** use `DeclareForcedUnrestrictedUpdateEvent`, but I've added it here to keep parity with the DiscreteUpdates , etc.  WDYT?

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 
:lgtm: x 2 with one comment

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16266#-:-MrTAoM9BVrljpfHQOKo:b-qwts05)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 904 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16266#-MrQ2MWi7NWcd8DUxSNN:-MrT97KV6W5UxUJt3Zk3:bbdyu53) ([raw file](https://github.com/robotlocomotion/drake/blob/750dd54641591bd94a3838ef58bc6572914ec606/bindings/pydrake/systems/framework_py_systems.cc#L904)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- we could avoid binding this, if we want to encourage people to **only** use `DeclareForcedUnrestrictedUpdateEvent`, but I've added it here to keep parity with the DiscreteUpdates , etc.  WDYT?
</blockquote></details>

BTW My preference would be to deprecate and remove the other handler as well to avoid having Python users override handlers when they should just add an event. But I don't know enough about Python usage to know whether there is some legitimate circumstance in which the handlers have to be overridden?

If you don't know of any such requirement, I'd suggest _not_ adding this binding for completeness but rather adding a TODO to the DoCalcDiscreteVariableUpdates() binding saying it should be removed.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16266)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 904 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16266#-MrQ2MWi7NWcd8DUxSNN:-MrTDH2r6DxdIsjlbURe:b7gucrf) ([raw file](https://github.com/robotlocomotion/drake/blob/750dd54641591bd94a3838ef58bc6572914ec606/bindings/pydrake/systems/framework_py_systems.cc#L904)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW My preference would be to deprecate and remove the other handler as well to avoid having Python users override handlers when they should just add an event. But I don't know enough about Python usage to know whether there is some legitimate circumstance in which the handlers have to be overridden?

If you don't know of any such requirement, I'd suggest _not_ adding this binding for completeness but rather adding a TODO to the DoCalcDiscreteVariableUpdates() binding saying it should be removed.
</blockquote></details>

SGTM.  I added the TODO in your name... I'm happy to do some service here, but also happy to let you own it.  I think we have a number of uses that will need to change.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16266)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @RussTedrake)

**Pull request merged**
