### PR TITLE
Fix mujoco parser joint kinematics.

### LINKED ISSUE #20367: MuJoCo imports differ from MuJoCo in placement of joints
### What happened?

It seems that MuJoCo imports both joints and inertial masses as an offset from the body it is nested in. Drake on the other hand seems to compute the joint location with respect to the previous body.

For example:
```xml
<body name='link1' pos="0 0.1 0.6" >
            <joint name="joint1" axis="1 0.1 0.1" pos="0.00 0.12 0.62"/>
```

Drake will currently interpret this as the joint1 frame being offset from link1 frame by [0.0, 0.02, 0.02]:
On the other hand, MuJoCo would interpret it as and offset of [0.0 0.12 0.62] a very significant difference.

This example is not a great way to specify body/joint locations, but it is incorrect nonetheless and could lead to some significant issues. Interestingly, Drake seems to import the geometry objects and inertial masses correctly parented to the parent body frame, but gets the joint position wrong. I assume this has to do with how the parenting works in other formats, where the joint is the parent of the body instead of the other way around.

I hope that makes sense. I can provide a sample xml and minimal Drake code / MuJoCo code to see the difference if it is helpful.

Here is a (very gross) xml to demonstrate this:

```xml
<mujoco model="Planar3Link">

  <worldbody>
      
        <body name='link1' pos="0 0.1 0.6" >
            <joint name="joint1" axis="1 0.1 0.1" pos="0.00 0.12 0.62"/>
            <inertial mass="0.1" pos="0 0.3 0" fullinertia="0.01 0.01 0.01 0.001 0.001 0.001"/>
            
            <geom type="sphere" size="0.15" pos="0.0 0.02 0.02" material="red"/>
            <geom type="sphere" size="0.11" pos="0.0 0.3 0" material="blue"/>
            <geom type="cylinder" size="0.1 0.1" fromto="0 0.0 0.0 0 0.5 0" material="white"/>
            
            <body name="link2" pos = "0 0.5 0">
                <joint name="joint2" type="hinge" axis="1 0.2 0" pos="0.03 0.52 0.0"/>
                <inertial mass="0.1" pos="0 0.1 0" fullinertia="0.02 0.02 0.02 0.002 0.002 0.002"/>
                
                <geom type="sphere" size="0.15" pos="0.03 0.02 0" material="red"/>
                <geom type="sphere" size="0.11" pos="0 0.1 0" material="blue"/>
                <geom type="cylinder" size="0.1 0.1" fromto="0 0 0 0 0.75 0" material="white"/>
                                
                <body name="link3" pos = "0.0 0.75 0.0">
                    <joint name="joint3" type="hinge" axis="1 0.03 0.05" pos="0.04 0.78 0.0" />
                    <inertial mass="0.1" pos="0.0 0.2 0.0" fullinertia="0.03 0.03 0.03 0.002 0.002 0.002"/>
                    <geom type="sphere" size="0.15" pos="0.04 0.03 0" material="red"/>
                    <geom type="sphere" size="0.11" pos="0.0 0.2 0" material="blue"/>
                    <geom type="cylinder" size="0.1 0.1" fromto="0 0 0 0 0.5 0" material="white"/>
                    
                </body>
                
            </body>
        </body>

  </worldbody>

  <actuator>
    <!-- <motor name="cart-motor" joint="cart"/> -->
    <motor name="motor1" joint="joint1"/>
    <motor name="motor2" joint="joint2"/>
    <motor name="motor3" joint="joint3"/>
  </actuator>

</mujoco>
```
It will throw a few unsupported material warnings but load fine so you can move the joints in meshcat, and just to make things easy on you, here's minimal code to load this in MuJoCo (python):

```python
import mujoco
import mujoco.viewer
import time
import numpy as np

MODEL_XML = """
<?xml version="1.0" ?>
<mujoco model="Planar3Link">
    <compiler autolimits="true"/>

    <option gravity="0 0 0" timestep="0.02" />
    <asset>
        <material name="blue" rgba="0 0 1 1" />
        <material name="green" rgba="0 1 0 1" />
        <material name="red" rgba="1 0 0 1" />
        <material name="white" rgba="1 1 1 1" />
    </asset>
    <worldbody>
        <geom type="plane" size="10 10 0.01" pos="0 0 0.0" rgba=".9 0 0 1" />
        <light diffuse=".5 .5 .5" pos="3 3 3" dir="-1 -1 -1" />      
        
        <body name='link1' pos="0 0.1 0.6" >
            <joint name="joint1" axis="1 0.1 0.1" pos="0.00 0.12 0.62" stiffness="100"  damping="10"/>
            <inertial mass="0.1" pos="0 0.3 0" fullinertia="0.01 0.01 0.01 0.001 0.001 0.001"/>
            <geom type="sphere" size="0.15" pos="0.0 0.02 0.02" material="red"/>
            <geom type="sphere" size="0.11" pos="0.0 0.3 0" material="blue"/>
            <geom type="cylinder" size="0.1 0.1" fromto="0 0.0 0.0 0 0.5 0" material="white"/>

            <body name="link2" pos = "0 0.5 0">
                <joint name="joint2" type="hinge" axis="1 0.2 0" pos="0.03 0.52 0.0" stiffness="100"  damping="10"/>
                <inertial mass="0.1" pos="0 0.1 0" fullinertia="0.02 0.02 0.02 0.002 0.002 0.002"/>
                <geom type="sphere" size="0.15" pos="0.03 0.02 0" material="red"/>
                <geom type="sphere" size="0.11" pos="0 0.1 0" material="blue"/>
                <geom type="cylinder" size="0.1 0.1" fromto="0 0 0 0 0.75 0" material="white"/>
                
                <body name="link3" pos = "0 0.75 0">
                    <joint name="joint3" type="hinge" axis="1 0.03 0.05" pos="0.04 0.78 0.0" stiffness="100"  damping="10"/>
                    <inertial mass="0.1" pos="0.0 0.2 0.0" fullinertia="0.03 0.03 0.03 0.002 0.002 0.002"/>                    <geom type="sphere" size="0.12" pos="0.0 0.4 0" material="red"/>
                    <geom type="sphere" size="0.15" pos="0.04 0.03 0" material="red"/>
                    <geom type="sphere" size="0.11" pos="0.0 0.2 0" material="blue"/>
                    <geom type="cylinder" size="0.1 0.1" fromto="0 0 0 0 0.5 0" material="white"/>
                </body>
                
            </body>
    
        </body>
  </worldbody>

  <actuator>
    <position name="motor1" joint="joint1" gear="10 10 10" ctrlrange="-20 20"/>
    <position name="motor2" joint="joint2" gear="10 10 10" ctrlrange="-20 20"/>
    <position name="motor3" joint="joint3" gear="10 10 10" ctrlrange="-20 20"/>
  </actuator>

</mujoco>
"""

model = mujoco.MjModel.from_xml_string(MODEL_XML)
data = mujoco.MjData(model)

# create the viewer object
#viewer = mujoco_viewer.MujocoViewer(model, data, width=800, height=600, hide_menus=True)
renderer = mujoco.Renderer(model, 400, 600)
viewer = mujoco.viewer.launch_passive(model, data)
viewer.cam.distance = model.stat.extent * 2

data.qpos = [1,1,1]
data.qvel = [0,0,0]
mujoco.mj_forward(model, data)

M = np.zeros((3,3))
mujoco.mj_fullM(model, M, data.qM)
print(M)

# simulate and render
while viewer.is_running():
    step_start = time.time()
    mujoco.mj_step(model, data)
    viewer.sync()

    # Rudimentary time keeping, will drift relative to wall clock.
    time_until_next_step = model.opt.timestep - (time.time() - step_start)
    if time_until_next_step > 0:
      time.sleep(time_until_next_step)

# close
viewer.close()
```
That mass matrix printed above will, naturally, be quite different than the one printed in Drake.

### Version

_No response_

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20367. (a bug fix)
Also adds support for joint defaults. (a new feature)

Together these support new tests confirming that the acrobot and cartpole models from dm_control have the expected kinematics.

The MuJoCo XML documentation specifies the position of a joint as being "specified in the frame of the parent body". But this apparently needs to be interpretted as the current body, not the parent of the current body.

+@drewhamiltonasdf for initial review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414)

### CODE REVIEW

**Review by drewhamiltonasdf — COMMENTED** [review]
Yep, I believe this is this issue. I'm not sure I have the time just now to check the new merge, but I am fairly confident this was the issue. Thanks for the quick fix!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhMsHSHCYT_R3_robKQ:b-h9to89)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by drewhamiltonasdf — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhMsmb5E-h7Vcg87cGr:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhNEOGK6TPpUEw5mh4Q:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
-@rpoyner-tri .  +@joemasterjohn for feature review, please.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhUN5jT1B7RajfA_NH2:b3usaso)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
In my opinion, the MuJoCo docs for the "pos" attribute are just wrong. Other places in the doc affirm the same terminology of a joint defining DoFs between "its parent body" and "its child body". The description of their free joint seems to be evidence that when they talk about the joint's "pos", it is the pose of the joint in the child body frame:

https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-joint:~:text=type%3A%20%5Bfree,cannot%20have%20limits.

i.e. "pos" == X_CJ

If by "parent" in the docs they really do mean "the body xml node that is the parent of this joint xml node", I think they need to be a lot more explicit. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhXKEvc27SLfBzqBo4q:bgfiwtc)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXJQCV5Qtk3yBg7bFj:-NhXJQCV5Qtk3yBg7bFk:birbhcy) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L273)):*
> ```cpp
>     ParseVectorAttribute(node, "pos", &pos);
>     // Drake wants the joint position in the parent frame, but MuJoCo specifies
>     // it in the current body frame.
> ```

nit: I would only use the parent-child terminology we have in Drake.



_Suggestion:_
```cpp
    // Drake wants the joint position in the parent frame, but MuJoCo specifies
    // it in the child body frame.
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXO4afDfrCuq13TU6P:-NhXO4afDfrCuq13TU6Q:b5crhjc) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L281)):*
> ```cpp
>     // Drake wants the axis in the parent frame, but MuJoCo specifies it in the
>     // current body frame. But, by definition, these are always the same (the
>     // axis is the constraint that defines the joint).
> ```

nit: ditto: current->child



_Suggestion:_
```cpp
    // Drake wants the axis in the parent frame, but MuJoCo specifies it in the
    // child body frame. But, by definition, these are always the same (the
    // axis is the constraint that defines the joint).
```
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 174 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXOZyEDlgVBTVLCz0q:-NhXOZyEDlgVBTVLCz0r:bbyqjaa) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/test/detail_mujoco_parser_test.cc#L174)):*
> ```cpp
>   // Check the kinematics. Passing this test requires a correct parsing of the
>   // joint position being defined in the current body frame, not the parent
>   // body frame.
> ```

nit: ditto current->child



_Suggestion:_
```cpp
  // Check the kinematics. Passing this test requires a correct parsing of the
  // joint position being defined in the child body frame, not the parent
  // body frame.
```

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: +@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhXP2nI8MQNgkZXa94D:b7oglfi)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

**Comment by yuvaltassa** [comment]
@joemasterjohn 

> If by "parent" in the docs they really do mean "the body xml node that is the parent of this joint xml node", I think they need to be a lot more explicit.

This is a great comment! (the answer is "yes")

Please feel free to [drop us a line](https://github.com/google-deepmind/mujoco/issues) whenever you have questions and/or if you think the documentation is unclear. We love to answer questions like this and improve our documentation 🤓

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhXqzexDPrpra1csEgf:b-cxwtpw)* status: 5 unresolved discussions

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXie1J2b91_M6BYe5e:-NhXie1K3xWyrWuH5a11:b-enykhg) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L281)):*
> ```cpp
>     // Drake wants the axis in the parent frame, but MuJoCo specifies it in the
>     // current body frame. But, by definition, these are always the same (the
>     // axis is the constraint that defines the joint).
> ```

nit consider a bit more elaboration



_Suggestion:_
```cpp
    // Drake wants the axis in the parent frame, but MuJoCo specifies it in the
    // current body frame. But, by definition, these are always the same for
    // revolute(hinge) joint and prismatic(slide) joint because the axis is the
    // constraint that defines the joint. For ball joint and free joint, the axis
    // attribute is ignored.
```
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 1034 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXqXC24h8TKo7CcJ9i:-NhXqXC30MQ8KS59L8yg:bbx1gsh) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/test/detail_mujoco_parser_test.cc#L1034)):*
> ```cpp
>       hinge_w_joint_defaults_joint.frame_on_child()
>           .CalcPoseInBodyFrame(*context)
>           .IsNearlyEqualTo(RigidTransformd(Vector3d{-.1, -.2, -.3}), 1e-14));
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```cpp
.IsNearlyEqualTo(RigidTransformd(Vector3d{-0.1, -0.2, -0.3}), 1e-14));
```

**Review by joemasterjohn — COMMENTED** [review]
Hi @yuvaltassa, thanks for the clarification! And sure thing, I submitted google-deepmind/mujoco#1127 asking for the doc change.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-:-NhXw6s8DOvqvUuIs6dS:b-fqwrri)* status: 5 unresolved discussions

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20414)* status: 1 unresolved discussion

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXJQCV5Qtk3yBg7bFj:-NhZJRJt72qgurpSg7pl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L273)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I would only use the parent-child terminology we have in Drake.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXO4afDfrCuq13TU6P:-NhZJVSQ4LUH1c48ED6F:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L281)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: ditto: current->child
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXie1J2b91_M6BYe5e:-NhZJl3K8KJgLOG3NJYk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/detail_mujoco_parser.cc#L281)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit consider a bit more elaboration
</blockquote></details>

Done.
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 174 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXOZyEDlgVBTVLCz0q:-NhZJrMD-5aHQISdey08:b-89aich) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/test/detail_mujoco_parser_test.cc#L174)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: ditto current->child
</blockquote></details>

Dibe,
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 1034 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXqXC24h8TKo7CcJ9i:-NhZJvrW2WpABvbjC0nT:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/test/detail_mujoco_parser_test.cc#L1034)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals
</blockquote></details>

Done.

**Comment by RussTedrake** [comment]
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 174 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20414#-NhXOZyEDlgVBTVLCz0q:-NhZOhl0A-Bd5UQw6vAg:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/57cbebe312eebff1db3d388416f93a1fbfdbcf7e/multibody/parsing/test/detail_mujoco_parser_test.cc#L174)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Dibe,
</blockquote></details>

Done

**Pull request merged**
