### PR TITLE
[planning] ConvexSet::AddPointInSetConstraints returns the new variables

### LINKED ISSUE #19585: Document Constraints that May Add Decision Variables, and Return Those Decision Variables
When constructing mathematical programs, the `AddPointInSetConstraints` method of `ConvexSet` may add additional decision variables to the program. A concrete example of this is for the `CartesianProduct` class, as can be seen [here](https://github.com/RobotLocomotion/drake/blob/37d6c59a13431956d82123de6cda24cfa765c50d/geometry/optimization/cartesian_product.cc#L173). This can cause problems down the line if the user is relying on the structure of the variables they've constructed. In my case, this became an issue when using the `initial_guess` parameter for `Solve`. It would be helpful to document that such functions can add new decision variables, and also to return those variables to the user, so they can use the `SetInitialGuess` methods.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #19585

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@cohnt could you take a look at this PR and make sure it is want you want? Thanks a lot!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYMDQToBIft2158EZXt:bvhxyby)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by cohnt — COMMENTED** [review]
This is exactly what I was looking for, thanks! I just have one minor comment on documentation.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYODwTVAZbEJ9Y_bs2d:bibxcqx)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/convex_set.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYODUiJClHpRpwhWabO:-NYODUiJClHpRpwhWabP:btv6drc) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf8618df56de72ee50158464771cb9861359fde/geometry/optimization/convex_set.h#L123)):*
> ```objc
>   @return new_vars Some of the derived class will add new decision variables to
>   enforce this constraint, we return all the newly added decision variables. The
>   meaning of these new decision variables differs in each subclass.
> ```

Small change, but I think it would help to mention that derived classes which don't create new decision variables will return an empty list.

**Review by hongkai-dai — COMMENTED** [review]
+@cohnt for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYP8vKT6dpiZIrv3KVQ:bhsqy6j)* status: 1 unresolved discussion, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/convex_set.h` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYODUiJClHpRpwhWabO:-NYP8zAT7Jf7Vd5mm833:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ecf8618df56de72ee50158464771cb9861359fde/geometry/optimization/convex_set.h#L123)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Small change, but I think it would help to mention that derived classes which don't create new decision variables will return an empty list.
</blockquote></details>

Done.

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYPJUm95LPtpUA_XdVD:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for a platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYPVFphD2tlS4bT12ts:b-qhld66)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 6 of 21 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/convex_set.h` line 126 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYPVbqGAVpFuylDeEhL:-NYPVbqGAVpFuylDeEhM:b-i63tv8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e676967edc36562cec01c1280aaac5a5f93ee9b7/geometry/optimization/convex_set.h#L126)):*
> ```objc
>   variables are added, then we return an empty Eigen vector.
>   @throws std::exception if ambient_dimension() == 0 */
>   VectorX<symbolic::Variable> AddPointInSetConstraints(
> ```

For consistency with other Add___Constraint methods, I would expect the return type (if there is one) from this method to be the list of Bindings to the newly added constraints.  More thoroughly, it could be the std::pair with the added variable + the list of added constraints.  E.g. as done in https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html#a6060c77125050d8c1b479a83d983a569 

I worry that adding only the variable return values would make the API inconsistent and annoying to change later?

**Comment by jwnimmer-tri** [comment]
FYI I'm going to pause my review until Russ' question is resolved.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes

___
*[`geometry/optimization/convex_set.h` line 126 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYPVbqGAVpFuylDeEhL:-NYR5iiLDMzV_aXs3tLS:b-hjs3mm) ([raw file](https://github.com/RobotLocomotion/drake/blob/e676967edc36562cec01c1280aaac5a5f93ee9b7/geometry/optimization/convex_set.h#L126)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

For consistency with other Add___Constraint methods, I would expect the return type (if there is one) from this method to be the list of Bindings to the newly added constraints.  More thoroughly, it could be the std::pair with the added variable + the list of added constraints.  E.g. as done in https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html#a6060c77125050d8c1b479a83d983a569 

I worry that adding only the variable return values would make the API inconsistent and annoying to change later?
</blockquote></details>

Done. I changed the return type to a std::pair of added variable and constraints.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/convex_set.h` line 126 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYPVbqGAVpFuylDeEhL:-NYSMPXr3q9s9fXBAUa7:b-c6eh91) ([raw file](https://github.com/RobotLocomotion/drake/blob/e676967edc36562cec01c1280aaac5a5f93ee9b7/geometry/optimization/convex_set.h#L126)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I changed the return type to a std::pair of added variable and constraints.
</blockquote></details>

That was a lot of work.  Thank you!  I'll leave it to the reviewers to check more carefully for correctness / test coverage.

**Review by cohnt — COMMENTED** [review]
Not sure if I'm still the assigned reviewer, but I'll throw in a 
:lgtm:

> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYThPec9tcvUuzM7vNw:b-v4zmze)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: feature) to indicate the new feature.

+(release notes: breaking change) due to the return type change.  If a user had written their own ConvexSet subclass, this would break them.

I've started the platform review, but need a break for meetings.  I've posted one small comment in the meantime.

> Reviewed 1 of 21 files at r1, 12 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYTm4LU9TMnmBpqPYDq:btlujr7)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYTlNfyEHWHkWmTyCVB:-NYTlNfz8kio40d5LLL_:b-x0cya) ([raw file](https://github.com/RobotLocomotion/drake/blob/43354ca500251910a841e5babd0448d755ccfd22/bindings/pydrake/geometry/test/optimization_test.py#L65)):*
> ```Python
>         self.assertTrue(hpoly.PointInSet(x=[0, 0, 0], tol=0.0))
>         self.assertFalse(hpoly.IsBounded())
>         new_vars_and_constraints = hpoly.AddPointInSetConstraints(
> ```

nit This is non-idiomatic Python.  We should use structured names for the return values, not arcane `[0]` and `[1]` magic.



_Suggestion:_
```Python
new_vars, new_constraints = hpoly.AddPointInSetConstraints(
```

**Review by jwnimmer-tri — COMMENTED** [review]
See https://github.com/hongkai-dai/drake/pull/31 for some cleanups.  Feel free to squash it in here, no need to stay separate other than for you to look it over.

> Reviewed 1 of 23 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYUAu1t6ZTRp8PMRQMv:b-603nin)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUBNxY07eF_D1cQ65W):*
nit Fit to length, remove stray capitaliztion, and update for recent changes:



_Suggestion:_
```
[planning] ConvexSet::AddPointInSetConstraints returns the new constraints
```
___
*[`geometry/optimization/convex_set.h` line 146 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYU10mg27c2JhJby0Uv:-NYU10mg27c2JhJby0Uw:b-hb2odi) ([raw file](https://github.com/RobotLocomotion/drake/blob/87d2e7048e87bc5f26c1e45a1bdf83d525e4de5e/geometry/optimization/convex_set.h#L146)):*
> ```objc
>   t = 0, we have only x ∈ rec(S).
>   @throws std::exception if ambient_dimension() == 0 */
>   std::vector<solvers::Binding<solvers::Constraint>>
> ```

BTW I assume we switch to `std::pair<VectorX<symbolic::Variable>,` to this function as well as the one below (to return the newly-added variables)?  I don't see a reason why these functions should be different that the one we're changing here.

Do you want to add a TODO (or issue) to that effect somewhere?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUBNxY07eF_D1cQ65W):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Fit to length, remove stray capitaliztion, and update for recent changes:
</blockquote></details>

Done.

By Fit to length, you mean the first line is within 72 characters?
___
*[`geometry/optimization/convex_set.h` line 146 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYU10mg27c2JhJby0Uv:-NYUH5naCQIetaIBUI-6:b-wficnx) ([raw file](https://github.com/RobotLocomotion/drake/blob/87d2e7048e87bc5f26c1e45a1bdf83d525e4de5e/geometry/optimization/convex_set.h#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I assume we switch to `std::pair<VectorX<symbolic::Variable>,` to this function as well as the one below (to return the newly-added variables)?  I don't see a reason why these functions should be different that the one we're changing here.

Do you want to add a TODO (or issue) to that effect somewhere?
</blockquote></details>

I added a TODO here. It will be a breaking change.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 3 of 23 files at r4, 8 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-:-NYUJ43k5nezgN1N-DMx:b-vtj4vo)* status: 5 unresolved discussions

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUBNxY07eF_D1cQ65W):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.

By Fit to length, you mean the first line is within 72 characters?
</blockquote></details>

Yes, but after the ` (#17634)` gets tacked on automatically.
___
*[`geometry/optimization/convex_set.h` line 146 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYU10mg27c2JhJby0Uv:-NYUIvJzBK8r-k0SJqHI:b-8gqk6a) ([raw file](https://github.com/RobotLocomotion/drake/blob/87d2e7048e87bc5f26c1e45a1bdf83d525e4de5e/geometry/optimization/convex_set.h#L146)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added a TODO here. It will be a breaking change.
</blockquote></details>

Yup.  This PR is already breaking though, so two breaks in one release cycle isn't too terrible, I hope.
___
*[`geometry/optimization/intersection.cc` line 113 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUI0aK1zrIT9JS_wCf:-NYUI0aK1zrIT9JS_wCg:b7vzre) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/intersection.cc#L113)):*
> ```cpp
>   VectorX<Variable> new_vars_vec =
>       Eigen::Map<VectorX<Variable>>(new_vars.data(), new_vars.size());
>   return {std::move(new_vars_vec), std::move(new_constraints)};
> ```

The return value logic here is non-trival.  I think we need a unit test to check it specifically?
___
*[`geometry/optimization/spectrahedron.cc` line 97 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUHjwK-QlqHVx1OiSc:-NYUHjwK-QlqHVx1OiSd:b2bufzi) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/spectrahedron.cc#L97)):*
> ```cpp
>   std::vector<Binding<Constraint>> new_constraints;
>   for (const auto& binding : sdp_->GetAllConstraints()) {
>     new_constraints.push_back(prog->AddConstraint(
> ```

I think its important to have a spectrahedron unit test that counts the >1 number of `new_constraints` that get returned.
___
*[`geometry/optimization/test_utilities.cc` line 39 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUHHJR4QSY1a45sKTT:-NYUHHJR4QSY1a45sKTU:bdtoocz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/test_utilities.cc#L39)):*
> ```cpp
>   const auto [new_vars, new_constraints] =
>       set.AddPointInSetConstraints(&prog, x);
>   EXPECT_EQ(prog.num_vars(), x.rows() + new_vars.rows());
> ```

nit A lot of the subclasses don't have unit tests of the `new_constraints` return value.  I think we could solve that with a simple change here:

```c++
EXPECT_FALSE(new_constraints.empty());
```
___
*[`geometry/optimization/test/minkowski_sum_test.cc` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIFKQ7CipZchY3uOt:-NYUIFKQ7CipZchY3uOu:b-ddtjse) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/test/minkowski_sum_test.cc#L51)):*
> ```cpp
>     auto [new_vars, new_constraints] = S.AddPointInSetConstraints(&prog, x);
>     EXPECT_EQ(new_vars.rows(), 4);
>     EXPECT_FALSE(new_constraints.empty());
> ```

nit I think its not too much of a maintenance burden to check an exact number here, and provides a real improvement to the level of implementation correctness we're checking for?



_Suggestion:_
```cpp
EXPECT_EQ(new_constraints.size(), ...);
```
___
*[`geometry/optimization/test/vpolytope_test.cc` line 132 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIWWRDXUgLlt1ppVz:-NYUIWWRDXUgLlt1ppW-:b-ddtjse) ([raw file](https://github.com/RobotLocomotion/drake/blob/25bd29508991724c353cf0ef988045367b6e6930/geometry/optimization/test/vpolytope_test.cc#L132)):*
> ```cpp
>     auto [new_vars, new_constraints] = V.AddPointInSetConstraints(&prog, x);
>     EXPECT_EQ(new_vars.rows(), V.vertices().cols());
>     EXPECT_FALSE(new_constraints.empty());
> ```

nit I think its not too much of a maintenance burden to check an exact number here, and provides a real improvement to the level of implementation correctness we're checking for?



_Suggestion:_
```cpp
 EXPECT_EQ(new_constraints.size(), ...);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 5 unresolved discussions

___
*[`geometry/optimization/test/minkowski_sum_test.cc` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIFKQ7CipZchY3uOt:-NYUJkCCEqp9vpBQ5miL:b-tzdksk) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/test/minkowski_sum_test.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think its not too much of a maintenance burden to check an exact number here, and provides a real improvement to the level of implementation correctness we're checking for?
</blockquote></details>

I actually initially checked `EXPECT_EQ(new_constraints.size(), ...)`, and then realized the check is too brittle. There are many ways to write the constraints, with different number of solvers::Binding objects. For example in https://github.com/RobotLocomotion/drake/blob/d1a5989a5f0f21d823c3743f44a6ff86ce41f6ed/geometry/optimization/minkowski_sum.cc#L146-L150, it adds the equality constraint for each row separately. It is not hard to imagine that we can combine this for loop into just one single constraint, that adds the equality constraint for all rows simultaneously. Hence I think checking the exact number would be a brittle test.
___
*[`geometry/optimization/test/vpolytope_test.cc` line 132 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIWWRDXUgLlt1ppVz:-NYUKKkgBxaxNVW8Oz1S:b-a2pn5t) ([raw file](https://github.com/RobotLocomotion/drake/blob/25bd29508991724c353cf0ef988045367b6e6930/geometry/optimization/test/vpolytope_test.cc#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think its not too much of a maintenance burden to check an exact number here, and provides a real improvement to the level of implementation correctness we're checking for?
</blockquote></details>

Same as in the `minkowski_sum_test` case, checking the number of new constraints will be very brittle. For example it adds these two constraints separately https://github.com/RobotLocomotion/drake/blob/d1a5989a5f0f21d823c3743f44a6ff86ce41f6ed/geometry/optimization/vpolytope.cc#L352-L358, but one can also imagine to write it as a single linear equality constraint.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 5 unresolved discussions

___
*[`geometry/optimization/test/minkowski_sum_test.cc` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIFKQ7CipZchY3uOt:-NYULNusDVtmG_0Qkc4m:b-14unnj) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/test/minkowski_sum_test.cc#L51)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I actually initially checked `EXPECT_EQ(new_constraints.size(), ...)`, and then realized the check is too brittle. There are many ways to write the constraints, with different number of solvers::Binding objects. For example in https://github.com/RobotLocomotion/drake/blob/d1a5989a5f0f21d823c3743f44a6ff86ce41f6ed/geometry/optimization/minkowski_sum.cc#L146-L150, it adds the equality constraint for each row separately. It is not hard to imagine that we can combine this for loop into just one single constraint, that adds the equality constraint for all rows simultaneously. Hence I think checking the exact number would be a brittle test.
</blockquote></details>

Perhaps is there a lower bound we can test for?  I'm worried that `>= 1` is too loose?  Maybe its fine.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: 3 unresolved discussions

___
*[`geometry/optimization/intersection.cc` line 113 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUI0aK1zrIT9JS_wCf:-NYUcvOc8fDiSDmilgrF:b-ki5kr2) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/intersection.cc#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The return value logic here is non-trival.  I think we need a unit test to check it specifically?
</blockquote></details>

Done. I added a test on the size of new_constraints.
___
*[`geometry/optimization/spectrahedron.cc` line 97 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUHjwK-QlqHVx1OiSc:-NYUeMQQ7IFCh7jcQmTP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/spectrahedron.cc#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think its important to have a spectrahedron unit test that counts the >1 number of `new_constraints` that get returned.
</blockquote></details>

Done.
___
*[`geometry/optimization/test/minkowski_sum_test.cc` line 51 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIFKQ7CipZchY3uOt:-NYUeUY7Cyym_1LmDBJC:b-oz8tym) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5cb33ce1f328ae70724d4dd2ad0dbf7912c3cb5/geometry/optimization/test/minkowski_sum_test.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Perhaps is there a lower bound we can test for?  I'm worried that `>= 1` is too loose?  Maybe its fine.
</blockquote></details>

Good call.
___
*[`geometry/optimization/test/vpolytope_test.cc` line 132 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19634#-NYUIWWRDXUgLlt1ppVz:-NYUfJSe470NuuRSoRgV:bmzkm0b) ([raw file](https://github.com/RobotLocomotion/drake/blob/25bd29508991724c353cf0ef988045367b6e6930/geometry/optimization/test/vpolytope_test.cc#L132)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Same as in the `minkowski_sum_test` case, checking the number of new constraints will be very brittle. For example it adds these two constraints separately https://github.com/RobotLocomotion/drake/blob/d1a5989a5f0f21d823c3743f44a6ff86ce41f6ed/geometry/optimization/vpolytope.cc#L352-L358, but one can also imagine to write it as a single linear equality constraint.
</blockquote></details>

Done, I added a test.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19634)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),cohnt

**Pull request merged**
