### PR TITLE
Make multibody/plant clang-format compliant

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20349)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok)

+@sherm1 for both reviews per rotation please. This is the second half to #20306 and fixes clang-formats for all files under `multibody/plant/test` and opt into clang-format in the bazel file.

> Reviewed 42 of 42 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-:-NgRI-v23d9Gq2humzHB:b-ohoety)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with a few minor reformat requests

> Reviewed 41 of 42 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-:-NgUwWP0Bw88DA1hm_5z:b-kmbs0d)* status: 3 unresolved discussions

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3779 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUmQEt7WfoS52d-TMb:-NgUmQEt7WfoS52d-TMc:bs4fril) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3779)):*
> ```cpp
>   // clang-format off
>   analytic_mass_matrix << I1 + I2 + m2 * l1 * l1 + 2 * m2 * l1 * lc2, I2 + m2 * l1 * lc2, // NOLINT
>                                                   I2 + m2 * l1 * lc2,                 I2; // NOLINT
> ```

minor: the formatting here seems to have gotten messed up despite all the directives
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3803 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUm_ml6e4wyCc1vaet:-NgUm_ml6e4wyCc1vaeu:bkn9kxq) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3803)):*
> ```cpp
>   analytic_mass_matrix_partial_m2
>       << (1.0 / 3.0) * l2 * l2 + l1 * l1 + 2 * l1 * lc2, (1.0 / 3.0) * l2 * l2 + l1 * lc2, // NOLINT
>                        (1.0 / 3.0) * l2 * l2 + l1 * lc2,            (1.0 / 3.0) * l2 * l2; // NOLINT
> ```

minor: messed up formatting. I don't think the extra spaces around `*` or `/` are necessary
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3830 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUvxqQEKHxQpE63LNc:-NgUvxqQEKHxQpE63LNd:b-i8w79o) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3830)):*
> ```cpp
>             (2.0 / 3.0) * m2 * l2 + m2 * l1, (2.0 / 3.0) * m2 * l2 + 0.5 * m2 * l1, // NOLINT
>       (2.0 / 3.0) * m2 * l2 + 0.5 * m2 * l1,                 (2.0 / 3.0) * m2 * l2; // NOLINT
>   // clang-format on
> ```

minor: same here

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20349)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3779 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUmQEt7WfoS52d-TMb:-NgUxdowDsRG-biNxb5I:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3779)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the formatting here seems to have gotten messed up despite all the directives
</blockquote></details>

Done
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3803 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUm_ml6e4wyCc1vaet:-NgUxqoEBTMMsAItmSTT:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3803)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: messed up formatting. I don't think the extra spaces around `*` or `/` are necessary
</blockquote></details>

Done
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3830 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20349#-NgUvxqQEKHxQpE63LNc:-NgUygkE6kLHXGyYOAJz:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/596977edacdeed30d209cfd1f00e606312f78948/multibody/plant/test/multibody_plant_test.cc#L3830)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: same here
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20349)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
