### PR TITLE
Add CheckSatisfiability and Minimize in DrealSolver

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7330)

### CODE REVIEW

**Comment by soonho-tri** [comment]
This PR will not pass the CI since dReal is not added to the CI servers yet.

To review this locally, please run `setup/ubuntu/16.04/install_prereqs.sh` (or `setup/mac/install_prereqs.sh`) which will install dReal.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7330#-:-KxJUQP4wSq2Z0VMSQBT:b-fd3kun)*

**Comment by soonho-tri** [comment]
@nikos-tri , can you feature-review this PR?

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7330#-:-KxJUy49RfoYL25PYVgV:bkxhori)*

**Comment by soonho-tri** [comment]
Closing this PR for now. @jwnimmer-tri taught me how to proceed with this kind of PR adding dependencies to Drake. I need to open 1) prolog PR changing scripts in `setup` directory and 2) the main dish. I'll do them.

**Comment by jwnimmer-tri** [comment]
FYI We also spoke about moving the not-from-Ubuntu `*.deb` libraries into `WORKSPACE` downloads instead of `install_prereqs.sh`.  Then, our install step would publish them into the install prefix, instead of asking users to install them as runtime-library debs.

Mu guess that would be an easier workflow.  Certainly for core developers, where it will Just Work as the dReal version evolves.  I suspect also for users, where "install a few runtime libraries from Ubuntu" has been pretty easy, but "install these other carefully-matched runtime libraries from bespoke debs" will be hard without `install_prereqs.sh` or a similar script.  I believe some downstreams of Drake right now have their own fork of `install_prereqs.sh`, so the less complexity we put there, probably the better?

**Comment by jwnimmer-tri** [comment]
> FYI We also spoke about moving the not-from-Ubuntu *.deb libraries into WORKSPACE downloads instead of install_prereqs.sh.

Prototype posted at https://github.com/jwnimmer-tri/drake/tree/bazel-debs.

> Then, our install step would publish them into the install prefix, instead of asking users to install them as runtime-library debs.

I didn't prototype this yet.

**Pull request closed without merging**
