### PR TITLE
Add VisitExpression

### PR DESCRIPTION
**Pull request by soonho-tri**
This is an extension to https://github.com/RobotLocomotion/drake/pull/5182 which added `VisitPolynomial`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5195)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai, feature-review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-:-Kd7Fw3wDSt_LVJLcRND:b-6u9ibl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-:-Kd9PwZJ14d6qv4CVYzF:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@ggould-tri , platform-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-:-KdAPyUiFsrbpf4W8F9a:bv9ldi0)*

**Comment by ggould-tri** [comment]
:lgtm:.  I have two suggestions for future boilerplate-reduction work below, which you are free to disregard.

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-KdBVUBKhJp-pYQiXwKv:-KdBVUBKhJp-pYQiXwKw:b-v5yhov) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0f8d498f856e2f3ad631be7e8f0048aaf4c31f/drake/common/symbolic_expression_cell.cc#L1700)):*
> ```cpp
>   return static_pointer_cast<ExpressionMax>(expr_ptr);
> }
> shared_ptr<ExpressionMax> to_max(const Expression& e) { return to_max(e.ptr_); }
> ```

FYI -- The level of duplication here is worrying -- it would be quite easy for a typo to slip in.  However it is not obvious to me how to deboilerplate it.  Here is a thought to consider in the future (not this PR, I'm afraid).

(1) `is_whatever` could move into the `ExpressionFoo` classes themselves as a static non-virtual `ExpressionWhatever::is_this()`
(2) Having done that, `to_whatever` can be moved into the expression class.  In ExpressionCell `typedef ThisClass ExpressionCell` and define `static shared_ptr<ThisClass> Expression::from(...ExpressionCell...)`.  Then override `ThisClass` in each child.

I *think* that would work under the type covariance rules.  Not sure.  Investigate it if you like -- this accumulation of copypasta is worrisome but this is not the PR to fix it.

---

*[drake/common/symbolic_expression_visitor.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-KdBXUL6FYS8Kc1nTuHU:-KdBXUL6FYS8Kc1nTuHV:b-gninx2) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0f8d498f856e2f3ad631be7e8f0048aaf4c31f/drake/common/symbolic_expression_visitor.h#L60)):*
> ```objc
> template <typename Result, typename Visitor, typename... Args>
> Result VisitExpression(const Visitor& v, const Expression& e, Args&&... args) {
>   switch (e.get_kind()) {
> ```

FYI, and probably not for this PR, this could be made slightly less verbose by moving to a map, `std::map<>{{ExpressionKind::Whatever, to_whatever}, {...}, {...}}[e]` or similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-:-KdBYa63OLyTbT7lk4kV:bf1i9w6)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-KdBVUBKhJp-pYQiXwKv:-KdBZaI9MGnIg0xoNUwS:b-9fxhyi) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0f8d498f856e2f3ad631be7e8f0048aaf4c31f/drake/common/symbolic_expression_cell.cc#L1700)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- The level of duplication here is worrying -- it would be quite easy for a typo to slip in.  However it is not obvious to me how to deboilerplate it.  Here is a thought to consider in the future (not this PR, I'm afraid).

(1) `is_whatever` could move into the `ExpressionFoo` classes themselves as a static non-virtual `ExpressionWhatever::is_this()`
(2) Having done that, `to_whatever` can be moved into the expression class.  In ExpressionCell `typedef ThisClass ExpressionCell` and define `static shared_ptr<ThisClass> Expression::from(...ExpressionCell...)`.  Then override `ThisClass` in each child.

I *think* that would work under the type covariance rules.  Not sure.  Investigate it if you like -- this accumulation of copypasta is worrisome but this is not the PR to fix it.
</blockquote></details>

Thank you! It sounds better than the current boilerplate. I'll open another PR doing this.

---

*[drake/common/symbolic_expression_visitor.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-KdBXUL6FYS8Kc1nTuHU:-KdBacJJorIMT-dJydZJ:b809e47) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0f8d498f856e2f3ad631be7e8f0048aaf4c31f/drake/common/symbolic_expression_visitor.h#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, and probably not for this PR, this could be made slightly less verbose by moving to a map, `std::map<>{{ExpressionKind::Whatever, to_whatever}, {...}, {...}}[e]` or similar.
</blockquote></details>

Probably even better if I move this non-member function into a member method in `Expression` and `ExpressionCell` classes? I'll investigate that direction and open another PR. Thank you for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_visitor.h, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5195#-KdBXUL6FYS8Kc1nTuHU:-KdBb3rDusif16JEu3tF:behkvrq) ([raw file](https://github.com/robotlocomotion/drake/blob/7a0f8d498f856e2f3ad631be7e8f0048aaf4c31f/drake/common/symbolic_expression_visitor.h#L60)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Probably even better if I move this non-member function into a member method in `Expression` and `ExpressionCell` classes? I'll investigate that direction and open another PR. Thank you for the suggestion!
</blockquote></details>

Even better, if you can somehow get from `ExpressionKind` to subtype, yes!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5195)*

**Pull request merged**
