### PR TITLE
[tools] Handle unusual `readelf` output in exported_symbols_test

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews.
+(status: single reviewer ok) 
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-:-NgL25qIDy2netdYa_69:bd9v96r)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`tools/install/libdrake/test/exported_symbols_test.py` line 135 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-NgL4Xa3EoKEIMnZxqeF:-NgL4Xa3EoKEIMnZxqeG:b-q2ys00) ([raw file](https://github.com/RobotLocomotion/drake/blob/b31b11654cc8f5d88e183deda90ac68a406ef549/tools/install/libdrake/test/exported_symbols_test.py#L135)):*
> ```Python
>         # %d" output that could occur in the symbol binding or type
>         # columns. See (for example):
>         # https://github.com/bminor/binutils-gdb/blob/binutils-2_40/binutils/readelf.c#L12695-L12704  # noqa
> ```

nit This citation isn't very helpful.  What would help a lot more is to copy-paste an exact line (or two) from mold+readelf output to show unambiguously what we are trying to regex ourselves around.
___
*[`tools/install/libdrake/test/exported_symbols_test.py` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-NgL4rfN2-29M6nEQowD:-NgL4rfOD7gPlwO7VEbp:bmfwlty) ([raw file](https://github.com/RobotLocomotion/drake/blob/b31b11654cc8f5d88e183deda90ac68a406ef549/tools/install/libdrake/test/exported_symbols_test.py#L143)):*
> ```Python
>             if not line or line.startswith("Symbol table"):
>                 continue
>             line = specific.sub('SPECIFIC', line)
> ```

nit Is there a way that we can better segregate this code that mitigates an unsupported toolchain, to get it out of the way of the sunny day code path that the rest of us care about?

I'm thinking something like a `def` helper function with all of the new code and comments, and then in this function just two new lines:

```py
...
...
lines = output.splitlines()

# Work around the broken mold linker.
lines = _demoldify_lines(lines)

# Now we get to parse the readelf output.  The lines look like this:
#
...
...
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-NgLVfW13uyYyd3JZqZN:-NgLVfW13uyYyd3JZqZO:b-rk3wii) (no related file):*
I'm still debating whether we're working around a quirk in `readelf` or a bug in `mold`. I suppose we could avoid the whole issue by reading symbol tables directly, perhaps with something like `pyelftools` (?? I have no idea if there is a good-enough library or tool available).

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-:-NgLYdGQElNN9zFpMKpG:bb6yyy8)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20334#-NgLVfW13uyYyd3JZqZN:-NgLXHX29cLFxk52969c:b-imcl3q) (no related file):*
My hypothesis when I selected readelf output scraping instead of pyelftools was that output scraping would be less work to maintain over time.  It's not too difficult to adjust our regexes to tweak the scraping, but OTOH if pyelftools doesn't recognize some rare elf token, we're totally hosed and nothing works.

> I'm still debating whether we're working around a quirk in `readelf` or a bug in `mold`.

That might affect the comment phrasing a bit, but I don't think it matters much?  The key observation is that your build configuration is _unsupported_ (i.e., not covered by CI).  Possibly phrasing the comments as "unsupported combination" rather than placing blame on one too or the other would help move ahead.

In any case, I am OK with the code & comments as-is now.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20334)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
