### PR TITLE
Controlled IIWA World demo

### PR DESCRIPTION
**Pull request by naveenoid**
Controlled IIWA demo added along with a corresponding diagram builder. 

The demo looks like this : https://youtu.be/kuw0kVqMBOY

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4629)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@sammy-tri for feature review

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5_zkrz5J0_PI0Hdbq:-K_5_zkrz5J0_PI0Hdbr:b-y049a2) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L10)):*
> ```cpp
> 
> #include <gflags/gflags.h>
> #include <chrono>
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5a0QzjcXOBkK1cnZf:-K_5a0QzjcXOBkK1cnZg:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L11)):*
> ```cpp
> #include <gflags/gflags.h>
> #include <chrono>
> #include <thread>
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aBwwRkTt8kwQa-nD:-K_5aBwxhUpRMwB-fcLs:b-lo106o) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L44)):*
> ```cpp
> 
> int DoMain() {
>   DRAKE_DEMAND(FLAGS_simulation_sec > 0);
> ```

include-what-you-use for drake_assert.h?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aFwQWnE44R9VghXz:-K_5aFwQWnE44R9VghY-:bnfq691) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L50)):*
> ```cpp
>   // subsequently added to the world. kRobotName alone is declared independently
>   // since it is needed again later.
>   // const string kRobotName = "/examples/kuka_iiwa_arm/urdf/iiwa14.urdf";
> ```

leftover debug code?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aVXM6sKFzdvHgIsU:-K_5aVXM6sKFzdvHgIsV:bxj52tc) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L142)):*
> ```cpp
>   CreateTreedFromFixedModelAtPose(kRobotName, &robot_tree, kRobotBase);
> 
>   unique_ptr<PiecewisePolynomialTrajectory> ppt =
> ```

BTW I wouldn't be surprised if your platform reviewer complains about non-standard abbreviations here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5-tFA0Y3PJnqXw_Ky:-K_5-tFBtXIOVcevko_G:b74ujcz) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L42)):*
> ```cpp
> using systems::System;
> using systems::TrajectorySource;
> using systems::MatrixGain;
> ```

BTW Alpha sort these?  (I can't find anywhere it's explicitly required but I've gotten comments about it on my PRs)

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5_ftBXz4HR7f-3cJY:-K_5_ftBXz4HR7f-3cJZ:b-m4lv4q) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L167)):*
> ```cpp
>       VectorX<T>::Zero(num_robot_velocities));
> 
>   input_mux_ = builder.template AddSystem<Multiplexer<T>>(
> ```

BTW iiwa_wsg_simulation reordered/commented the declaration of the input_mux and the zero_source to attempt to improve readability.  We could copy that style here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5-fkKsD98P7SHIyrb:-K_5-fkKsD98P7SHIyrc:b2o5oj9) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L84)):*
> ```objc
>   systems::DrakeVisualizer* drake_visualizer_{nullptr};
>   systems::RigidBodyPlant<T>* rigid_body_plant_{nullptr};
>   std::unique_ptr<PiecewisePolynomialTrajectory> poly_trajectory_{nullptr};
> ```

FYI I don't think unique_ptr benefits from explicit null initialization (but I don't think it would do any harm)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629)*

**Comment by naveenoid** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5_zkrz5J0_PI0Hdbq:-K_8WNQLXBGPQZY69m_D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5a0QzjcXOBkK1cnZf:-K_8WNpaCsXDxe_k8j30:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L11)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aBwwRkTt8kwQa-nD:-K_8WeOex9zud2DUVa-8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L44)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

include-what-you-use for drake_assert.h?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aFwQWnE44R9VghXz:-K_8WewxrNi9PAKETZOM:bq3sxgx) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

leftover debug code?
</blockquote></details>

Done. Yikes!

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5aVXM6sKFzdvHgIsU:-K_8WoRbcd0NcW5B4Zaz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L142)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I wouldn't be surprised if your platform reviewer complains about non-standard abbreviations here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5-tFA0Y3PJnqXw_Ky:-K_8XMQfFTJunJflKvm9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L42)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Alpha sort these?  (I can't find anywhere it's explicitly required but I've gotten comments about it on my PRs)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5_ftBXz4HR7f-3cJY:-K_8YlH40XwJKeuI7dsM:b-s5h53t) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L167)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW iiwa_wsg_simulation reordered/commented the declaration of the input_mux and the zero_source to attempt to improve readability.  We could copy that style here.
</blockquote></details>

Done. Also reordered their declarations since it fits the logic you talk about. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_5-fkKsD98P7SHIyrb:-K_8XYyObNG9F90QJuFL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a386ecdff9f1bb010cc3f6dbd0551113a934f11/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L84)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

FYI I don't think unique_ptr benefits from explicit null initialization (but I don't think it would do any harm)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI and platform review +(status: curate commits before merging) 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-:-K_AELJZzzkhklVxSTOs:bxj3gw2)*

**Comment by naveenoid** [comment]
+@ggould-tri for platform review.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-:-K_BJLmQSKd8aVm9jBZ9:b-8qo47q)*

**Comment by ggould-tri** [comment]
Looks good.  :lgtm: pending comments below.

---

Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BMSh1nmaFC0jRfhma:-K_BMSh3HkC9hqpM7pMr:b-q59bdi) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_common.h#L61)):*
> ```objc
>   Kp << 100, 100, 100, 20, 10, 20, 1;
>   for (int i = 0; i < Kp.size(); i++) {
>     Kd[i] = std::sqrt(Kp[i]);
> ```

BTW, is there a theoretical basis for using square root here?  I cannot seem to derive one.  If so, a comment might be nice.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOONAbdxQwvpEwnNd:-K_BOONAbdxQwvpEwnNe:b-mcylkv) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L24)):*
> ```cpp
> DEFINE_double(simulation_sec, 4.5, "Number of seconds to simulate.");
> 
> using Eigen::Vector3d;
> ```

`Vector3d` is used qualified in most cases; unqualify it or qualify it and remove this using.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOaCSRphaqBtQDKow:-K_BOaCSRphaqBtQDKox:busvwd5) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L25)):*
> ```cpp
> 
> using Eigen::Vector3d;
> using std::make_unique;
> ```

`make_unique` is used qualified in all cases in this file; this using is unused.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOiYjGr0hc3MFn9rp:-K_BOiYjGr0hc3MFn9rq:b3fpc72) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L26)):*
> ```cpp
> using Eigen::Vector3d;
> using std::make_unique;
> using std::move;
> ```

`move` is used qualified in all cases in this file; this using is unused.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BQEhf6lBCNlkbuxWa:-K_BQEhf6lBCNlkbuxWb:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L40)):*
> ```cpp
> using systems::DiagramBuilder;
> using systems::DrakeVisualizer;
> using systems::InputPortDescriptor;
> ```

Unused.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BQGFirUMu1yK0WSJv:-K_BQGFirUMu1yK0WSJw:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L41)):*
> ```cpp
> using systems::DrakeVisualizer;
> using systems::InputPortDescriptor;
> using systems::MatrixGain;
> ```

Unused.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 84 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BPkltVw986B3tondh:-K_BPkluxBVpLuiJyX3C:b-cii4ms) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L84)):*
> ```objc
>   systems::DrakeVisualizer* drake_visualizer_{nullptr};
>   systems::RigidBodyPlant<T>* rigid_body_plant_{nullptr};
>   std::unique_ptr<PiecewisePolynomialTrajectory> poly_trajectory_;
> ```

BTW, can the content of this `unique_ptr` be const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-:-K_BQQf07pxhLXcJH2NM:bk4nrbg)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629)*

**Comment by naveenoid** [comment]
Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_common.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BMSh1nmaFC0jRfhma:-K_ERjsMHxUC5827niDH:bxmpc1h) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_common.h#L61)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW, is there a theoretical basis for using square root here?  I cannot seem to derive one.  If so, a comment might be nice.
</blockquote></details>

Done. I put in a few comments here regarding the choice of gains.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 24 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOONAbdxQwvpEwnNd:-K_DpvTX1Oz3ujhfFHDL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

`Vector3d` is used qualified in most cases; unqualify it or qualify it and remove this using.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOaCSRphaqBtQDKow:-K_DpvsyNqiddlm4CVXC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L25)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

`make_unique` is used qualified in all cases in this file; this using is unused.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BOiYjGr0hc3MFn9rp:-K_DpwSlmNcXIgM4DOYq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/controlled_iiwa_world_demo.cc#L26)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

`move` is used qualified in all cases in this file; this using is unused.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BQEhf6lBCNlkbuxWa:-K_Dq1pzMXKkkpjlINnc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L40)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BQGFirUMu1yK0WSJv:-K_Dq3ZPCkg4Qfcvsu28:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.cc#L41)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 84 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-K_BPkltVw986B3tondh:-K_ERgqVO6-WkwIs6vWl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8583b5c4063c515a6130a1fb4c3d7bf7a3910ba0/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L84)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW, can the content of this `unique_ptr` be const?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629)*

**Comment by naveenoid** [comment]
-(status: curate commits before merging) 
moving to squash and merge

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4629#-:-K_YFCdCw1IcUeKf18Eb:b-vdj596)*

**Pull request merged**
