### PR TITLE
[fem] Add Dirichlet boundary conditions

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review or delegation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-MynNhdc18VJb7W_ZJ6R:b-drvk2m)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This PR has been rebased on top of master and is ready for review again.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-Mz0dxR124pgWfcRJLUT:b-78r4c7)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm:, minor comments.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-Mz147kY6NOip8YrRb6O:b13auei)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/dirichlet_boundary_condition.h, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz0zG5E-rj49aGYYByw:-Mz0zG5FAJWvx1HXZBlJ:bb7lc54) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L24)):*
> ```objc
>  model under the stored BC.
>  @tparam_nonsymbolic_scalar */
> template <class T>
> ```

nit,



_Suggestion:_
```objc
typedef T
```
___
*[multibody/fem/dirichlet_boundary_condition.h, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz1-A2k1JxSPbOg5hK9:-Mz1-A2k1JxSPbOg5hKA:bw6oc7k) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L52)):*
> ```objc
>    @pre fem_state is an "owned" FEM state (see FemState).
>    @throw std::exception if any dof index specified by `this` boundary
>    conditioner is greater than or equal to the `fem_state->num_dofs()`. */
> ```

nit, s/conditioner/condition
___
*[multibody/fem/dirichlet_boundary_condition.h, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz1-PO04qN3R0TYH2T-:-Mz1-PO04qN3R0TYH2T0:bw6oc7k) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L63)):*
> ```objc
>    @pre tangent_matrix->rows() == tangent_matrix->cols().
>    @throw std::exception if any dof index specified by `this` boundary
>    conditioner is greater than or equal to the `tangent_matrix->cols()`. */
> ```

nit, s/conditioner/condition
___
*[multibody/fem/dirichlet_boundary_condition.h, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz1-PmJ3lIkzTUoCwq7:-Mz1-PmJ3lIkzTUoCwq8:bw6oc7k) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L72)):*
> ```objc
>    @pre residual != nullptr.
>    @throw std::exception if any dof index specified by `this` boundary
>    conditioner is greater than or equal to the `residual->size()`. */
> ```

nit, s/conditioner/condition
___
*[multibody/fem/dirichlet_boundary_condition.h, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz13cj894Di_UlXVQ0a:-Mz13cj894Di_UlXVQ0b:bvnq9j2) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L73)):*
> ```objc
>    @throw std::exception if any dof index specified by `this` boundary
>    conditioner is greater than or equal to the `residual->size()`. */
>   void ApplyBoundaryConditionToResidual(EigenPtr<VectorX<T>> residual) const;
> ```

nit, probably this method could be used to zero-out BC dofs in any other vector besides the residual? Also, in some FEM codes the residual actually contains the BC values.
So, to make things very clear, what about naming this something like `ZeroOutEntriesWithBoundaryCondition()` or `ApplyHomogeneousDirichletBoundaryCondition()` or similar?
___
*[multibody/fem/dirichlet_boundary_condition.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz10wBA3nOMUIOfCjPU:-Mz10wBBBi7d00viCJ5E:bcbnniq) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.cc#L21)):*
> ```cpp
>   VerifyIndexes(fem_state->num_dofs());
> 
>   VectorX<T> q = fem_state->GetPositions();
> ```

to avoid copy, I recommend having `FemState::GetMutablePositions()`.
___
*[multibody/fem/dirichlet_boundary_condition.cc, line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz11t0I6y7Jona3iO6m:-Mz11t0J0iecMSBH2put:bph3vnp) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.cc#L71)):*
> ```cpp
>   const auto& last_bc = index_to_boundary_state_.crbegin();
>   if (last_bc->first >= size) {
>     throw std::out_of_range(
> ```

per [Drake GSG](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) since we do not catch exceptions, there is no reason to specify a particular subclass. We prefer `std::logic_error` unless there is a good reason.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/dirichlet_boundary_condition.cc, line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz11t0I6y7Jona3iO6m:-Mz19-v060PIVemrG7eY:b-jw67x5) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.cc#L71)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per [Drake GSG](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) since we do not catch exceptions, there is no reason to specify a particular subclass. We prefer `std::logic_error` unless there is a good reason.
</blockquote></details>

`out_of_range` is a kind of logic_error. (See full hierarchy [here](https://en.cppreference.com/w/cpp/error/exception).) It's not required to be this specific but is fine.

**Review by xuchenhan-tri — COMMENTED** [review]
@sherm1 do you feel like platform reviewing since you are already looking at the PR? Otherwise, I'll assign the Monday on deck reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-Mz1B-V17zDVexTF3vby:b9wpse7)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/fem/dirichlet_boundary_condition.h, line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz13cj894Di_UlXVQ0a:-Mz1AETq5ivYILK4MYv1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.h#L73)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, probably this method could be used to zero-out BC dofs in any other vector besides the residual? Also, in some FEM codes the residual actually contains the BC values.
So, to make things very clear, what about naming this something like `ZeroOutEntriesWithBoundaryCondition()` or `ApplyHomogeneousDirichletBoundaryCondition()` or similar?
</blockquote></details>

Done.
___
*[multibody/fem/dirichlet_boundary_condition.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz10wBA3nOMUIOfCjPU:-Mz18J5Q2PLsHqtO_JC3:b-ofjgya) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.cc#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

to avoid copy, I recommend having `FemState::GetMutablePositions()`.
</blockquote></details>

Right now this is only done once per time step so the cost of copying isn't too bad. 
Added a TODO for now and will revisit when this copy becomes an issue.
___
*[multibody/fem/dirichlet_boundary_condition.cc, line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16839#-Mz11t0I6y7Jona3iO6m:-Mz17_cB2lVwhGPn25lo:b-tfs6ba) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f82900deaf097b488f8eaa07cc322f31db46eb/multibody/fem/dirichlet_boundary_condition.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

`out_of_range` is a kind of logic_error. (See full hierarchy [here](https://en.cppreference.com/w/cpp/error/exception).) It's not required to be this specific but is fine.
</blockquote></details>

Throwing a particular subclass isn't a defect. Per GSG, we just don't guarantee the exception type.

**Review by sherm1 — COMMENTED** [review]
Not sure I would be able to get to this today.
+@ggould-tri for platform review (Monday) per rotation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-Mz1GN-A0bMZKhP9wGnz:b-drrmxq)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @amcastro-tri and @ggould-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; some small documentation and testing issues.

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-MzFhFox85cERfxeOMp2:blegszq)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/dirichlet_boundary_condition.h, line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFW7rX8YrNM80Q5CcF:-MzFW7rX8YrNM80Q5CcG:bfxugz8) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/dirichlet_boundary_condition.h#L15)):*
> ```objc
> namespace internal {
> 
> /* DirichletBoundaryCondition provides functionalities related to Dirichlet
> ```

FYI:  This is internal and so author's discretion on detailed comments, but if we ever expect to expose this a brief explanation of Dirichlet BCs or at least a link to the wikipedia page would probably be appreciated by future readers who have to chase bugs through this class.
___
*[multibody/fem/dirichlet_boundary_condition.h, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFZI5T7cGdm2g-s26P:-MzFZI5U0mb_qN-g95sm:b-7z9ky0) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/dirichlet_boundary_condition.h#L67)):*
> ```objc
>       PetscSymmetricBlockSparseMatrix* tangent_matrix) const;
> 
>   /* Modifies the given vector `v` that arises from an FEM model without BC into
> ```

minor
"the... vector `v` that arises from an FEM model" is quite cryptic.  I spent most of an hour trying to figure out what this means, which of the various things called `v` in this part of the code this might be referring to, what vectors could reasonably be set to zero under homogenous dirichlet boundary conditions, etc.
As best I can understand, `v` here is meant to apply to a residual?  If so, the word "residual" should probably appear somewhere in this comment, or possibly `v` should be renamed `residual`.
___
*[multibody/fem/test/dirichlet_boundary_condition_test.cc, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFgtD_2f3qbf3W_wer:-MzFgtD_2f3qbf3W_wes:bge9xuw) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/test/dirichlet_boundary_condition_test.cc#L17)):*
> ```cpp
> 
> /* An arbitrary number of degree of freedom made up for testing purpose. */
> static constexpr int kNumDofs = 3;
> ```

minor:  3 is a bad choice here since with each condition itself being of size 3 (q, v, a) you could have a transposition error and not catch it.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839)* status: 2 unresolved discussions (waiting on @amcastro-tri and @ggould-tri)

___
*[multibody/fem/dirichlet_boundary_condition.h, line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFW7rX8YrNM80Q5CcF:-MzGYD53-TEb0aKh05FB:bry9c4d) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/dirichlet_boundary_condition.h#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI:  This is internal and so author's discretion on detailed comments, but if we ever expect to expose this a brief explanation of Dirichlet BCs or at least a link to the wikipedia page would probably be appreciated by future readers who have to chase bugs through this class.
</blockquote></details>

Done, added a reference.
___
*[multibody/fem/dirichlet_boundary_condition.h, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFZI5T7cGdm2g-s26P:-MzGNT_NAsd9hV9FGi4E:b-ukckwg) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/dirichlet_boundary_condition.h#L67)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor
"the... vector `v` that arises from an FEM model" is quite cryptic.  I spent most of an hour trying to figure out what this means, which of the various things called `v` in this part of the code this might be referring to, what vectors could reasonably be set to zero under homogenous dirichlet boundary conditions, etc.
As best I can understand, `v` here is meant to apply to a residual?  If so, the word "residual" should probably appear somewhere in this comment, or possibly `v` should be renamed `residual`.
</blockquote></details>

Other stuff could also be zeroed out with this boundary condition like @amcastro-tri pointed out in the comment below. I added some doc in hope of more clarity.
___
*[multibody/fem/test/dirichlet_boundary_condition_test.cc, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16839#-MzFgtD_2f3qbf3W_wer:-MzGPJZdDJyHbnZGSDUm:b-xalway) ([raw file](https://github.com/robotlocomotion/drake/blob/63e1c8d8ff30edeb22a7532702ea45cf02717918/multibody/fem/test/dirichlet_boundary_condition_test.cc#L17)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  3 is a bad choice here since with each condition itself being of size 3 (q, v, a) you could have a transposition error and not catch it.
</blockquote></details>

You are right. I was lazy to go up to 6 (it has to be a multiple of 3).

**Review by amcastro-tri — COMMENTED** [review]
@xuchenhan-tri, I see you replied a few comments from @ggould-tri but I don't see the updates. Did you push the latest changes of still working?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-MzGzkMc6haL6dACG8F6:bs08axg)* status: 1 unresolved discussion (waiting on @ggould-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Ah thanks! I pushed now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839#-:-MzH9Lmh7K3EmIcT3MOS:b-o30cqc)* status: 1 unresolved discussion (waiting on @amcastro-tri and @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16839)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
