### PR TITLE
Implements MultibodyPlant::GetConstraintIds()

### LINKED ISSUE #21482: Getters for MultibodyConstraintId for constraints added by the Parser
**Is your feature request related to a problem? Please describe.**
#21397 added `MultibodyPlant::RemoveJoint`, but throws if there are _any_ constraints registered with the plant.  We have `MultibodyPlant::RemoveConstraint(MultibodyConstraintId)`, but if constraints are added by the Parser, then there is no way from python to get the `MultibodyConstraintId`.

**Describe the solution you'd like**
The minimal API which would unblock this issue is to add `std::vector<MultibodyConstraintId> MultibodyPlant::GetConstraintIds()`.

**Describe alternatives you've considered**
The existing accessor methods, like `get_coupler_constraint_specs`, could serve this purpose, but they are currently marked as internal and are not bound in pydrake. We could change this decision. Even if we implement `GetConstraintIds()`, we don't currently have any pydrake methods to introspect even what type of constraint is associated with the `MultibodyConstraintId`.

We could add `MultibodyPlant::RemoveAllConstraints()`.

cc @amcastro-tri , @joemasterjohn

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #21482. At minimum, this enables one to remove constraints from the plant that might have been added during parsing, without using internal methods (which are not bound in pydrake).

+@amcastro-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)* status: 9 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-Nyzi-p-ANBx4Emh1_lP:-Nz_2NlyCZ6PXkhcMGJI:b-qr03ag) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd like to understand better how this aids in resolving #21482.
That is, what would the workflow look like for your particular problem @RussTedrake? in #21482 you even mention that just having `GetConstraintIds()` alone would not solve your problem. Is this a first PR from a train of PRs?
Is the idea that you'd use `GetConstraintIds()` and `RemoveConstraint()` to remove all joints so that way you'd be able to remove joints? would that still solve your problem?
</blockquote></details>

you still working on this @RussTedrake?

___

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,joemasterjohn, needs platform reviewer assigned

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-Nyzi-p-ANBx4Emh1_lP:-NzmDWFh71KeDzA_vozl:b-6jxj7l) (no related file):*
> you still working on this [@RussTedrake](https://github.com/RussTedrake)?

ofc. just got busy. is it blocking you?


Re: what does this enable?  In order to load the PR2 for my workflow, I have code that looks like this...

```
   # Remove mimic constraints:
    for id in plant.GetConstraintIds():
         plant.RemoveConstraint(id)
    # Remove some superfluous joints
    ReplaceJointWithWeld(plant, plant.GetJointByName("head_pan_joint"))
    ReplaceJointWithWeld(plant, plant.GetJointByName("head_tilt_joint"))
```

___
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-NyzXyY76BtABfF-CNxz:-NzmFkjOEDk6eVvdrPuc:buv1qo3) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e101cba1d05accd652409780c353f8357ef2903/multibody/plant/test/multibody_plant_test.cc#L4175)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: You can use this convenient gmock container matcher instead of creating a vector and sorting yourself:
</blockquote></details>

Done.  Nice! 
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4176 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-NyzYQgN2xdbclX87_kK:-NzmGOMcCySCE0gFsbal:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e101cba1d05accd652409780c353f8357ef2903/multibody/plant/test/multibody_plant_test.cc#L4176)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Could you also remove 1-2 constraints and then check that the returned Ids reflect the removal?
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2647 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-Nyzj27d3gqKTogCpSLn:-NzmGs-rCEKoHP1b6Zhy:bp7q0tn) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e101cba1d05accd652409780c353f8357ef2903/bindings/pydrake/multibody/test/plant_test.py#L2647)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this is pretty much a copy of the test right below `test_constraint_active_status_api`. 
Why not instead to piggyback on that test?
</blockquote></details>

Done.  Fine by me.  I thought that was dispreferred.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-Nyzi-p-ANBx4Emh1_lP:-O-1_jUW4YIpQTgKKSbD:b-651sry) (no related file):*
> just got busy. is it blocking you?

no, quite the opposite, double checking nothing was blocking you.


> I have code that looks like this...

I see thanks, that helps. Even though the coment in your code says "remove mimic constraints", it seems from it that you are okay with removing **all consraint types**, at least for now.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1bsoL9wfzRj-HAS9u:-O-1bsoL9wfzRj-HAS9v:b-eor15x) (no related file):*
Thanks for the snippet example Russ.
:lgtm: for me.

___
___
*[`multibody/plant/multibody_plant.h` line 1560 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1aICc3tSZLof56U9a:-O-1aICc3tSZLof56U9b:b-4bnrpl) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/multibody_plant.h#L1560)):*
> ```objc
> 
>   /// Returns a list of all constraint identifiers. The returned vector becomes
>   /// invalid after any calls to Add*Constraint() or RemoveConstraint().
> ```

minor, personal preference



_Suggestion:_
```objc
  /// Returns a list of all constraint identifiers. The returned vector becomes
  /// outdated after any calls to Add*Constraint() or RemoveConstraint().
```
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1ayGF-UePpu6GV1RU:-O-1ayGF-UePpu6GV1RV:b-a799lk) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/test/multibody_plant_test.cc#L4142)):*
> ```cpp
> }
> 
> GTEST_TEST(MultibodyPlantTests, GetConstraintIds) {
> ```

not your fault, but as far as I can tell, there is no good reason to piggy back on this already giant file for constraint related tests.
I'd place this and ConstraintActiveStatus and RemoveConstraint in their own separate file. Maybe `multibody_plant_constraints_test.cc`?
If you prefer I can open a separate PR for this.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2647 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-Nyzj27d3gqKTogCpSLn:-O-1bSrD5DboS4l6fRQU:b-2ebmvj) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e101cba1d05accd652409780c353f8357ef2903/bindings/pydrake/multibody/test/plant_test.py#L2647)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Fine by me.  I thought that was dispreferred.
</blockquote></details>

This might depend on the reviewer, and often times like  in this case there is a trade off. I personally tend to write the minimium amount of code that gets the job done, unless there is a good reason to do it another way. The platform reviewer might add more on this.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: thanks! +@SeanCurtis-TRI for platform review, please.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-:-O-2KiKIC9Ynth6EdxLZ:becm17f)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-:-O-2oAGA88ud9aMyPUvk:bmxilld)* status: 5 unresolved discussions

___
*[`multibody/plant/multibody_plant.h` line 1560 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1aICc3tSZLof56U9a:-O-2mwE84ZjjctEs5bL3:b-h8pgv4) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/multibody_plant.h#L1560)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, personal preference
</blockquote></details>

"invalid" is more of a C++ term of art. Like hanging onto an iterator after mutating the underlying object.
___
*[`multibody/plant/multibody_plant.cc` line 450 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-2nWEf9CzeWUMaE2-w:-O-2nWEf9CzeWUMaE2-x:byy63o2) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/multibody_plant.cc#L450)):*
> ```cpp
> std::vector<MultibodyConstraintId> MultibodyPlant<T>::GetConstraintIds() const {
>   std::vector<MultibodyConstraintId> ids;
>   // This list must be kept up to date with the types of user - addable
> ```

nit: Weird typography.



_Suggestion:_
```cpp
 user-addable
```
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1ayGF-UePpu6GV1RU:-O-2nxZy1EKiHN-jCxma:bml9i7p) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/test/multibody_plant_test.cc#L4142)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not your fault, but as far as I can tell, there is no good reason to piggy back on this already giant file for constraint related tests.
I'd place this and ConstraintActiveStatus and RemoveConstraint in their own separate file. Maybe `multibody_plant_constraints_test.cc`?
If you prefer I can open a separate PR for this.
</blockquote></details>

I agree with the end goal and would advocate the follow up PR.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)* status: 1 unresolved discussion

___
*[`multibody/plant/multibody_plant.h` line 1560 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1aICc3tSZLof56U9a:-O-7EP1YAlVGHsVbVhz5:b3qceld) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/multibody_plant.h#L1560)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

"invalid" is more of a C++ term of art. Like hanging onto an iterator after mutating the underlying object.
</blockquote></details>

I definitely like "invalid" if the return type was a reference or iterator. But here the object  still is valid in the C++ sense, and therefore my preference for a term like "outdated".
Again, this is flagged as "minor" and I'd be okay with either option. 
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4142 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-1ayGF-UePpu6GV1RU:-O-7EiN5BR0pzxVIF4rA:b-1cq1ku) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/test/multibody_plant_test.cc#L4142)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I agree with the end goal and would advocate the follow up PR.
</blockquote></details>

Yes, I think that's better. 
Let me know if you'd prefer me to create that PR @RussTedrake .

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21483)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`multibody/plant/multibody_plant.cc` line 450 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21483#-O-2nWEf9CzeWUMaE2-w:-O-7Fjni3OX11wdMCtvs:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b43a064d5d39032f61dd90cf0cb08136daa734a5/multibody/plant/multibody_plant.cc#L450)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Weird typography.
</blockquote></details>

Done

**Pull request merged**
