### PR TITLE
[geometry] Bury fcl dependency into implementation deps

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI All of the "exclude" attributes for internal libraries are a bit verbose at the moment.  I have a follow-up PR on deck that will add sugar to make that pattern easier.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17188)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both reviews, please.  (No rush; waiting until Wednesday is fine.)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2 Thanks for the clean up.

I suppose this is a +(release notes: none) ?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17188#-:-N2E4lJa3ucZJvnZeen_:b-1rflhc)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/proximity/BUILD.bazel` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E3h3V9GiPC6njb2ds:-N2E3h3V9GiPC6njb2dt:bdqq9fk) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L128)):*
> ```Starlark
>         "collisions_exist_callback.h",
>     ],
>     tags = [
> ```

BTW, could you explain the distinction between `install_hdrs_exclude` and the `exclude_from_package` tag? Should they always show up in tandem?
___
*[`geometry/proximity/BUILD.bazel` line 702 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E4KutBtnDFWBRdN1-:-N2E4KuuEs6hZAx7HN38:b8ruszc) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L702)):*
> ```Starlark
>         # into one place with no rhyme nor reason, leading to dependency graph
>         # nightmares. Thus, we need a visibility wart here for now.
>         "//multibody/fixed_fem/dev:__pkg__",
> ```

BTW, this can soon be retired. @damrongguoy and I are actively working on getting the last bits of the `fixed_fem/dev` out of dev.

**Review by jwnimmer-tri — COMMENTED** [review]
> I suppose this is a (release notes: none)?

Yes!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17188#-:-N2E5EUm6e7P3qA2GNVp:bn86t7k)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/proximity/BUILD.bazel` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E3h3V9GiPC6njb2ds:-N2E5HZO0kxpLyudnUvJ:b5nu39t) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, could you explain the distinction between `install_hdrs_exclude` and the `exclude_from_package` tag? Should they always show up in tandem?
</blockquote></details>

Not necessarily.  The follow-up PR will make this cleaner, though.

The install-exclude affects whether the header is part of the install.

The exclude-package affects whether `//geometry/proximity` should roll this module into the overall package shortcut.  Sometimes this is useful, even for installed components:

https://github.com/RobotLocomotion/drake/blob/e92a2961ce6b45386b59e5bb84be1383b27a8697/multibody/plant/BUILD.bazel#L208-L213
___
*[`geometry/proximity/BUILD.bazel` line 702 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E4KutBtnDFWBRdN1-:-N2E5gEyC3tgE3ITac5c:b-9c1b9i) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L702)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this can soon be retired. @damrongguoy and I are actively working on getting the last bits of the `fixed_fem/dev` out of dev.
</blockquote></details>

Hah!  I forgot this comment was in here. I wrote it weeks ago when first prototyping this patch.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17188)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`geometry/proximity/BUILD.bazel` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E3h3V9GiPC6njb2ds:-N2E6szfB3UubYrslkAz:b-o01tmf) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Not necessarily.  The follow-up PR will make this cleaner, though.

The install-exclude affects whether the header is part of the install.

The exclude-package affects whether `//geometry/proximity` should roll this module into the overall package shortcut.  Sometimes this is useful, even for installed components:

https://github.com/RobotLocomotion/drake/blob/e92a2961ce6b45386b59e5bb84be1383b27a8697/multibody/plant/BUILD.bazel#L208-L213
</blockquote></details>

Are packages automatically "installed"? (I guess I don't fully understand the term "installed") . As a result, is it true that if a header shouldn't be installed, then we should always exclude it from the package?

**Comment by jwnimmer-tri** [comment]
*[`geometry/proximity/BUILD.bazel` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E3h3V9GiPC6njb2ds:-N2E84_524NZP3I2NsUv:b-oz1024) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Are packages automatically "installed"? (I guess I don't fully understand the term "installed") . As a result, is it true that if a header shouldn't be installed, then we should always exclude it from the package?
</blockquote></details>

The "package" as used here is just a shorthand for the cc_library shortcut that is named the same thing as its directory, so `//geometry/proximity`.

By default, we do want to install all package libraries which public visibility.  That means if a package has private visibility, we might need to exclude it's headers from the install, but would not need to exclude_from_package.  (The header install follows the transitive closure of hdrs across interface_deps, which would reach into private packages by default.)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17188)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`geometry/proximity/BUILD.bazel` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17188#-N2E3h3V9GiPC6njb2ds:-N2EAi9P9QnnyednxrkB:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/be92bcef1a8f6c349aee87ae23660d9e395e7736/geometry/proximity/BUILD.bazel#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The "package" as used here is just a shorthand for the cc_library shortcut that is named the same thing as its directory, so `//geometry/proximity`.

By default, we do want to install all package libraries which public visibility.  That means if a package has private visibility, we might need to exclude it's headers from the install, but would not need to exclude_from_package.  (The header install follows the transitive closure of hdrs across interface_deps, which would reach into private packages by default.)
</blockquote></details>

Got it, thanks!

**Pull request merged**
