### PR TITLE
Fix test failures in RgbdCamera

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Relates: #5721, #5866

Note: The unit test for `RgbdCamera` is not included to CI yet. See #5227 for the detail.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5952)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@siyuanfeng-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-:-Kig3N-42tCb_NRPN1e9:b-jqru8h)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-Kig4Erqu7bSsbdZiHwe:-Kig4Erqu7bSsbdZiHwf:b-nvki85) ([raw file](https://github.com/robotlocomotion/drake/blob/68de33958d116179764f453803a805f854ac112b/drake/systems/sensors/test/rgbd_camera_test.cc#L56)):*
> ```cpp
> 
>     // The expected focal value is calculated by hand.
>     const double kExpectedFocal = 579.41125496954282;
> ```

BTW, it shouldn't have different focal length for x and y, right? if it's not too long, might paste the whatever code you generated this number with here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-:-Kig4gYKWN054SbN41iO:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
+@ggould-tri platform review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-Kig4Erqu7bSsbdZiHwe:-KigNzTT37379wwZmjpA:b-q07icn) ([raw file](https://github.com/robotlocomotion/drake/blob/68de33958d116179764f453803a805f854ac112b/drake/systems/sensors/test/rgbd_camera_test.cc#L56)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, it shouldn't have different focal length for x and y, right? if it's not too long, might paste the whatever code you generated this number with here. 
</blockquote></details>

Added a comment.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-:-KigOEysQPGs9aP4Jc83:bdmqfp3)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-:-Kijb8w5Mb81LGvAiMwn:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/test/rgbd_camera_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5952#-Kig4Erqu7bSsbdZiHwe:-KijhwMXKNuq0VbpIi46:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68de33958d116179764f453803a805f854ac112b/drake/systems/sensors/test/rgbd_camera_test.cc#L56)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Added a comment.

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5952)*

**Pull request merged**
