### PR TITLE
Update valgrind builds to use Focal

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update valgrind wrapper scripts to account for the name of the distro-provided Python suppressions file changing between Bionic and Focal. Update Jenkins job name in documentation.

See also #14928. Supersedes #16223.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16557)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please.

**Comment by jwnimmer-tri** [comment]
Given some of the huge variances in runtime across the different test case within `iris_test`, we could imagine changing some of the the very-slow tests within it to do `if (std::getenv("VALGRIND_OPTS") != nullptr) { return; }` and bail out (with a trivial pass) when valgrind is enabled.  Hopefully the narrower tests would still demonstrate any memory violations.

**Comment by mwoehlke-kitware** [comment]
> we could imagine changing some of the the very-slow tests within it to do if `(std::getenv("VALGRIND_OPTS") != nullptr) { return; }` and bail out (with a trivial pass) when valgrind is enabled

Is that going to help ASAN?

**Comment by jwnimmer-tri** [comment]
Per f2f meeting: the slow tests are being annoying enough that we should split `iris_test` cases in twain (`iris_test`, `iris_slow_test`) based upon the test case timings -- and then mark the `iris_slow_test` with `no_asan` etc. tags to skip those variants in CI.

**Comment by mwoehlke-kitware** [comment]
#16567 should address the `iris_test` failures.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please.

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews, you can merge when you like.

**Pull request merged**
