### PR TITLE
Add python binding for ComputeNumericalGradient

### PR DESCRIPTION
**Pull request by hongkai-dai**
Asked on stackoverflow https://stackoverflow.com/questions/73196013/troubleshooting-optimization-for-finding-a-robot-pose-in-equilibrium#comment129285124_73198325

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684#-:-N8ZeteD0M993VviXGfL:bhru7xi)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, nice!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684#-:-N8ZxEbuDkvNln0BD_nq:by8c39b)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[`bindings/pydrake/test/math_test.py` line 484 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17684#-N8ZxG9z3Mu33JDfCC63:-N8ZxG9z3Mu33JDfCC64:b-eq45oq) ([raw file](https://github.com/robotlocomotion/drake/blob/102c3f104c00b41b03ca4d8e287d26c8fb3f11b1/bindings/pydrake/test/math_test.py#L484)):*
> ```Python
> 
>         grad = mut.ComputeNumericalGradient(
>             calc_fun=foo, x=np.array([1., 2.]), option=option)
> ```

BTW `fun` as an abbreviation sounds more funky than `func`, but I see precedent for it.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot retest this, please

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[`bindings/pydrake/test/math_test.py` line 484 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17684#-N8ZxG9z3Mu33JDfCC63:-N8_M6YlCm6dFK3fLHNY:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/102c3f104c00b41b03ca4d8e287d26c8fb3f11b1/bindings/pydrake/test/math_test.py#L484)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `fun` as an abbreviation sounds more funky than `func`, but I see precedent for it.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17684#-N8_w2En4NIMfMsQbyWq:-N8_w2En4NIMfMsQbyWr:bixck98) (no related file):*
FYI CI is failing b/c of partial rename (sorry about that!).

___

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17684)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17684#-N8_w2En4NIMfMsQbyWq:-N8aBvO0-NrFnpmF1-do:b-hr33d9) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI CI is failing b/c of partial rename (sorry about that!).
</blockquote></details>

My bad, I should have tested it locally before pushing to the remote.

___

**Pull request merged**
