### PR TITLE
[release] Update release playbook for new staging jobs

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[`doc/_pages/release_playbook.md` line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-QQOEydRs7oSp3iO:-NEr-QQOEydRs7oSp3iP:b-cd2h3d) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L149)):*
> ```Markdown
>    2. Repeat steps 2-5 exactly as you did for the wheel to run the packaging staging
>       builds for both focal and jammy.
>    3. Wait for those two build jobs to succeed.
> ```

Working, is this sufficient?  My understanding is the release manager will be running the staging job, even if we're going to be running `push_release` (for now).
___
*[`tools/release_engineering/download_release_candidate.py` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-kP_A4EQdJkP9Xgy:-NEr-kP_A4EQdJkP9Xgz:b-ujs9p0) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L138)):*
> ```Python
>     # and VERSION.TXT match.  `ar x <file>` then `control.tar.xz` extracted
>     # has control file with a Version line.  `data.tar.xz` will have the
>     # VERSION.TXT member.
> ```

Working, it should be possible to validate the `.deb` files.
___
*[`tools/release_engineering/download_release_candidate.py` line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-qs43LM6xvo5qWyo:-NEr-qs43LM6xvo5qWyp:bg121ii) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L200)):*
> ```Python
>         "--version", type=str,
>         help="Release version in vX.Y.Z format.")
>     args = parser.parse_args()
> ```

Working, if the release flow is indeed (a) release manager runs debian staging and (b) finishes up and verifies, then

1. Something in the `.md` somewhere should explicitly state to **NOT** upload the `.deb` files to GitHub downloaded by this script?
2. It might be nice to add a pass-through `--debian-only` to just download the staged `.deb` files.  At least it would be convenient for whoever is running `push_release`.

Or just don't download the `.deb` files?

**Comment by jwnimmer-tri** [comment]
*[`doc/_pages/release_playbook.md` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4TRX54a0-rolj45W_:-NF4TRX54a0-rolj45Wa:b-hu69hv) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L184)):*
> ```Markdown
>       ``/tmp/drake-release/v1.N.0`` (the 4 tarballs, and their 8 checksums).
>       * Do not attach the ``whl``-related binary artifacts; we'll upload those
>         pypi a bit later on.
> ```

I've been considering for a while anyway that the GH release page should just have all of the binaries, even if we also push them elsewhere.  (At the moment, it only has the tgz binaries).

WDYT about changing this text to say that _everything_ that it downloaded should be attached to the release page (i.e., adding debs and whls to the attachments)?

Maybe I'll ping @rpoyner-tri as well for any input on the idea.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[`doc/_pages/release_playbook.md` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4T7Ux7yn3h3uE8NXm:-NF4T7Ux7yn3h3uE8NXn:bntbgza) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L127)):*
> ```Markdown
>       source code:
>       [download_release_candidate.py](https://github.com/RobotLocomotion/drake/blob/master/tools/release_engineering/download_release_candidate.py).)
> 2. Launch the wheel staging builds for that git commit sha:
> ```

nit (see further below for discussion)



_Suggestion:_
```Markdown
the staging builds
```
___
*[`doc/_pages/release_playbook.md` line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4XkxJ-JarGL4A0eWX:-NF4XkxJ-JarGL4A0eWY:b-z37gtx) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L129)):*
> ```Markdown
> 2. Launch the wheel staging builds for that git commit sha:
>    1. For both macOS and linux, open the jenkins build page from
>       this list:
> ```

nit (see further discussion below)



_Suggestion:_
```Markdown
   1. Open the following four Jenkins jobs (e.g., each in its own
      new browser tab):
```
___
*[`doc/_pages/release_playbook.md` line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-QQOEydRs7oSp3iO:-NF4Srq183yQFHHRP0kP:bhuzh6s) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L149)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, is this sufficient?  My understanding is the release manager will be running the staging job, even if we're going to be running `push_release` (for now).
</blockquote></details>

I think it's fine, yes.

What do you think about rolling this into the previous step, though?  The "wait for all staging jobs succeed" would make most sense as a single pause, not twice back-to-back.

I think with a tweaks to the wording we can make it happen.
___
*[`tools/release_engineering/download_release_candidate.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4UB8XBhTyms9xUgSv:-NF4UB8YDiBDWLmRrpeK:b-ydk4l8) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L97)):*
> ```Python
>             f"drake-{version[1:]}-cp310-cp310-manylinux_2_31_x86_64.whl",
>             f"drake-{version[1:]}-cp310-cp310-macosx_11_0_x86_64.whl",
>             # TODO(18145): do not download the staged .tar.gz, just .deb.
> ```

nit I think the phrasing here is a little misleading.



_Suggestion:_
```Python
# TODO(18145): Download staging .tar.gz once it's ready.
```
___
*[`tools/release_engineering/download_release_candidate.py` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-kP_A4EQdJkP9Xgy:-NF4UZ3pDdHpJJJcYAIL:bq9yqgq) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L138)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, it should be possible to validate the `.deb` files.
</blockquote></details>

To read files within a `*.deb`, shell out to `dpkg-deb -x` not `ar`.

Don't validate the control file; the only goal of this function is to validate the git sha (from the data file).  I think the debs _do_ have the git sha in VERSION so this shouldn't be too difficult.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @svenevs)

___
*[`doc/_pages/release_playbook.md` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4TRX54a0-rolj45W_:-NF9bgXo4Ryl7kIknuIF:b2wea3r) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L184)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I've been considering for a while anyway that the GH release page should just have all of the binaries, even if we also push them elsewhere.  (At the moment, it only has the tgz binaries).

WDYT about changing this text to say that _everything_ that it downloaded should be attached to the release page (i.e., adding debs and whls to the attachments)?

Maybe I'll ping @rpoyner-tri as well for any input on the idea.
</blockquote></details>

I can see some utility for direct-download access to debs. Not sure who is using whls directly, or if there are problems with the ever-evolving tooling.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri and @svenevs)

___
*[`doc/_pages/release_playbook.md` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4TRX54a0-rolj45W_:-NFiGIk03WXISX1iGYfC:bm5ae0f) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L184)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I can see some utility for direct-download access to debs. Not sure who is using whls directly, or if there are problems with the ever-evolving tooling.
</blockquote></details>

Yeah, I think it's probably worth uploading them all.  Debs are certainly useful.  The whl files can be installed directly `pip install /path/to/foo.whl` or `pip install https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-foo.whl` and in any case is a nice "offsite backup" versus pypi.

**Review by svenevs — COMMENTED** [review]
OK, mostly ready to go with some questions and review / restructure needed for `.deb` version validation.

FYI I ran the staging build arbitrarily as `v4.5.6` for all 5 to test things out, `bazel run //tools/release_engineering:download_release_candidate --       --timestamp 20221102 --version v4.5.6`

When we are done with this PR I will delete those from s3.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148#-:-NFtwd9h-ZQvQJnllUPG:b-8bir6l)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @svenevs)

___
*[`doc/_pages/release_playbook.md` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4T7Ux7yn3h3uE8NXm:-NFsRbppAm5R6ipTn4Y7:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit (see further below for discussion)
</blockquote></details>

Done
___
*[`doc/_pages/release_playbook.md` line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4XkxJ-JarGL4A0eWX:-NFsRdF88jbyr8RI1NEB:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit (see further discussion below)
</blockquote></details>

Done
___
*[`doc/_pages/release_playbook.md` line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-QQOEydRs7oSp3iO:-NFsUxxoCk7YCc_VzR3c:b7dxfr) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it's fine, yes.

What do you think about rolling this into the previous step, though?  The "wait for all staging jobs succeed" would make most sense as a single pause, not twice back-to-back.

I think with a tweaks to the wording we can make it happen.
</blockquote></details>

Done, much better all in one section.
___
*[`doc/_pages/release_playbook.md` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4TRX54a0-rolj45W_:-NFtwH505sjVT7OjBvxv:b-pg29wm) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L184)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, I think it's probably worth uploading them all.  Debs are certainly useful.  The whl files can be installed directly `pip install /path/to/foo.whl` or `pip install https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-foo.whl` and in any case is a nice "offsite backup" versus pypi.
</blockquote></details>

See newest draft -- that will be 33 artifacts total in the current world order.  Is this what we want?
___
*[`doc/_pages/release_playbook.md` line 132 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFtwVXM6pyV-jbrXE12:-NFtwVXM6pyV-jbrXE13:b4qawll) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/doc/_pages/release_playbook.md#L132)):*
> ```Markdown
>       - [Linux Jenkins Wheel Staging](https://drake-jenkins.csail.mit.edu/view/Staging/job/linux-focal-unprovisioned-gcc-wheel-staging-snopt-mosek-release/)
>       - [macOS x86 Jenkins Wheel Staging](https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-x86-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/)
>       - [macOS arm Jenkins Wheel Staging](https://drake-jenkins.csail.mit.edu/view/Staging/job/mac-arm-monterey-unprovisioned-clang-wheel-staging-snopt-mosek-release/)
> ```

FYI I added macOS arm here since it is available right now.  We can remove it if the next release does not intend to cut this.
___
*[`tools/release_engineering/download_release_candidate.py` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4UB8XBhTyms9xUgSv:-NFsoJfpCg8cEvTEtQlG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think the phrasing here is a little misleading.
</blockquote></details>

Done.
___
*[`tools/release_engineering/download_release_candidate.py` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-kP_A4EQdJkP9Xgy:-NFtvLOy9VdpkJqvPwph:b-90e101) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L138)):*
> the only goal of this function is to validate the git sha

See added changes.  That's in there now, I also added additional logic since extracting the version is straightforward with `dpkg-deb -f <path/to/file.deb> Version`.  I'm not exactly satisfied with where it takes place in the script / could be its own function if we want to keep it.
___
*[`tools/release_engineering/download_release_candidate.py` line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-qs43LM6xvo5qWyo:-NFtvcFR0iHEHWG5fU9H:b-qwqkws) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L200)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, if the release flow is indeed (a) release manager runs debian staging and (b) finishes up and verifies, then

1. Something in the `.md` somewhere should explicitly state to **NOT** upload the `.deb` files to GitHub downloaded by this script?
2. It might be nice to add a pass-through `--debian-only` to just download the staged `.deb` files.  At least it would be convenient for whoever is running `push_release`.

Or just don't download the `.deb` files?
</blockquote></details>

Alright, there is a new `--deb-only` flag being added.  This is helpful for Kitware, our part of the release process is now restricted to just needing the `.deb` files.  It only works when `--version` is applied, if `--find-git-sha` is provided it is _ignored_.  (Didn't seem worth adding in a bunch of logic to error if it's provided for the "wrong mode").

Is this acceptable?

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`doc/_pages/release_playbook.md` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NF4TRX54a0-rolj45W_:-NFty3kd0JG8xUPjVn6c:b-gd0z17) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/doc/_pages/release_playbook.md#L184)):*
FYI [from GH](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas):

> ## Storage and bandwidth quotas
>
> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

___
*[`doc/_pages/release_playbook.md` line 132 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFtwVXM6pyV-jbrXE12:-NFusHKeEX7pDiTRzPW4:bbk6fdq) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/doc/_pages/release_playbook.md#L132)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI I added macOS arm here since it is available right now.  We can remove it if the next release does not intend to cut this.
</blockquote></details>

Let's keep it.  If it doesn't make sense for the release, we have just have the release manager skip that step.
___
*[`doc/_pages/release_playbook.md` line 145 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFusWsR1t0bXWq8lmiR:-NFusWsR1t0bXWq8lmiS:bipu7l4) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/doc/_pages/release_playbook.md#L145)):*
> ```Markdown
>    7. Wait for all staging jobs to succeed.  It's OK to work on release notes
>       finishing touches in the meantime, but do not merge the release notes nor
>       tag the release until the wheel builds have succeeded.
> ```

nit clarity



_Suggestion:_
```Markdown
all five builds
```
___
*[`tools/release_engineering/download_release_candidate.py` line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-qs43LM6xvo5qWyo:-NGIVa_h-PjhV9zoYwZD:b-p8uy4l) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L200)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Alright, there is a new `--deb-only` flag being added.  This is helpful for Kitware, our part of the release process is now restricted to just needing the `.deb` files.  It only works when `--version` is applied, if `--find-git-sha` is provided it is _ignored_.  (Didn't seem worth adding in a bunch of logic to error if it's provided for the "wrong mode").

Is this acceptable?
</blockquote></details>

The Kitware process should not be to download from staging.  It should be to download from the GitHub releases page.  Downloading from staging hazards the possibly of mismatches.
___
*[`tools/release_engineering/download_release_candidate.py` line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutPXq01MyMnrAaCVm:-NFutPXq01MyMnrAaCVn:b-654mcw) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L65)):*
> ```Python
>                 text = f.read().decode("utf8")
>         _, commit = text.split()
>     else:  # is_deb_file
> ```

nit We can make the comment machine-checkable



_Suggestion:_
```Python
    else:
        assert is_deb_file
```
___
*[`tools/release_engineering/download_release_candidate.py` line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutZ_a6svhvCMVDklk:-NFutZ_a6svhvCMVDkll:bu3eaow) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L71)):*
> ```Python
>             version_txt_path = Path(td) / "opt" / "drake" / "share" / "doc" / \
>                 "drake" / "VERSION.TXT"
>             assert version_txt_path.is_file()
> ```

nit Doesn't `open` on the next line already effectively do this for us, with a better error message?
___
*[`tools/release_engineering/download_release_candidate.py` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutlmJ9Nwy621r7ypt:-NFutlmJ9Nwy621r7ypu:b-z0s0wa) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L92)):*
> ```Python
> 
> def _check_urls(*, urls):
>     """Check all urls exist using.  Fail if any do not exist with an error
> ```

"using..." what?



_Code quote:_
```Python
using.
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`doc/_pages/release_playbook.md` line 145 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFusWsR1t0bXWq8lmiR:-NGMdS-gE6A4bOlA7MAY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/doc/_pages/release_playbook.md#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit clarity
</blockquote></details>

Done.
___
*[`tools/release_engineering/download_release_candidate.py` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-kP_A4EQdJkP9Xgy:-NGMnCknARx8r67O31rd:b-b9le29) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L138)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

> the only goal of this function is to validate the git sha

See added changes.  That's in there now, I also added additional logic since extracting the version is straightforward with `dpkg-deb -f <path/to/file.deb> Version`.  I'm not exactly satisfied with where it takes place in the script / could be its own function if we want to keep it.
</blockquote></details>

Done, moved it to its own location.
___
*[`tools/release_engineering/download_release_candidate.py` line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NEr-qs43LM6xvo5qWyo:-NGMf6OE2iQP8rCqKYWf:b6xv01w) ([raw file](https://github.com/robotlocomotion/drake/blob/aa120ceff96306a3ce8ee1daf40fcfc43ce47080/tools/release_engineering/download_release_candidate.py#L200)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The Kitware process should not be to download from staging.  It should be to download from the GitHub releases page.  Downloading from staging hazards the possibly of mismatches.
</blockquote></details>

Done, removed -- right makes sense.  Since everything is added to the GH release artifacts it will be easy for us to snag the `.deb`s.  The overall for the diff is much less intrusive now.
___
*[`tools/release_engineering/download_release_candidate.py` line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutPXq01MyMnrAaCVm:-NGMd_mW4jVxzf-z3t8_:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We can make the comment machine-checkable
</blockquote></details>

Done, good call.
___
*[`tools/release_engineering/download_release_candidate.py` line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutZ_a6svhvCMVDklk:-NGMeEMm8kfheaEL5h3S:b-kh23ks) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Doesn't `open` on the next line already effectively do this for us, with a better error message?
</blockquote></details>

Done, removed, yes it does :+1:

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/drake-release-tmp-19k1ju21/opt/drake/share/doc/drake/VERSION.TXTasdf'`
___
*[`tools/release_engineering/download_release_candidate.py` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NFutlmJ9Nwy621r7ypt:-NGMeRFG3GvRABPDcD7K:b-ijru5n) ([raw file](https://github.com/robotlocomotion/drake/blob/0295b2b3c093c59c2184c30e4657254816243b70/tools/release_engineering/download_release_candidate.py#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

"using..." what?
</blockquote></details>

Done, removed, "``using `wget --spider`.``" was the original sentence which was intended to be deleted (it's a few lines down...)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge"

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature -(status: do not merge).  I pushed some small fixes from local testing.

+@rpoyner-tri for platform review, please.

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148#-:-NGOH3ZR2bHLrHPaOleI:b-jaj6dm)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`tools/release_engineering/download_release_candidate.py` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NGOBjA_51DgrVbO6cIq:-NGOBjA_51DgrVbO6cIr:b-sssq0h) ([raw file](https://github.com/robotlocomotion/drake/blob/9f32ccb3e39e0593bd134af22d609cd6e9580334/tools/release_engineering/download_release_candidate.py#L22)):*
> ```Python
> 
> import argparse
> from ensurepip import version
> ```

nit Is `ensurepip.version` used anywhere?  I didn't immediately find any.

In any case importing something named `version` into a script where a dozen local variables are also named `version` is too difficult to read.  We should spell it out as `ensurepip.vesrion()` at the call site in case we do use it.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`tools/release_engineering/download_release_candidate.py` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18148#-NGOBjA_51DgrVbO6cIq:-NGOHCGz6TTSpKkkj6l5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f32ccb3e39e0593bd134af22d609cd6e9580334/tools/release_engineering/download_release_candidate.py#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Is `ensurepip.version` used anywhere?  I didn't immediately find any.

In any case importing something named `version` into a script where a dozen local variables are also named `version` is too difficult to read.  We should spell it out as `ensurepip.vesrion()` at the call site in case we do use it.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148#-:-NGOXpOA-wgORQnlu98b:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18148#-:-NGOXtkVAqfgAyuSrSIG:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @svenevs)

**Comment by svenevs** [comment]
> nit Is ensurepip.version used anywhere? I didn't immediately find any.

Ugh, I'm so sorry -- I normally catch that but I just disabled auto import for my editor.  I also pushed the dummy testing code for error checking by fudging `focal` numbers...

Anyway, thanks for fixing up / finalizing this!

**Pull request merged**
