### PR TITLE
Interface for Lcm message <=> arbitrary data types

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Part 0 of https://github.com/RobotLocomotion/drake/pull/6192, contains the translator API and a System block, and some tests for the TranslatorSystem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6360)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for feature review. You have seen everything.
+@sherm1 for platform review. 
thanks!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-:-KmmEwt33OH9DrXpQZ8C:btiqei2)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360)*

**Comment by sherm1** [comment]
Nice! Platform :lgtm: pending a few BTWs.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/lcm/translator_base.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmWOav8z6O1XiMnZQK:-KmmWOav8z6O1XiMnZQL:b-j39k2m) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L12)):*
> ```objc
>  * Base API for a translator between arbitrary data of DataType and a Lcm
>  * message of MsgType. This class is intended to facilitate Lcm communication
>  * under the System framework. Within the System frame, time can be acquired
> ```

BTW frame -> framework

---

*[drake/lcm/translator_base.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmWZdYBFD2lhBj1paz:-KmmWZdYBFD2lhBj1pb-:b-ta0op0) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L23)):*
> ```objc
>  *   DataType and time -> MsgType,
>  *   MsgType -> DataType and time
>  * </pre>
> ```

BTW That looks symmetric to me (comment says it is asymmetric).

---

*[drake/systems/lcm/translator_system.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmdSM1NbJnNNgkyoqV:-KmmdSM1NbJnNNgkyoqW:bcn1le6) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L14)):*
> ```objc
> namespace lcm {
> 
> namespace translator_system_detail {
> ```

BTW consider hiding this detail namespace and its contents from doxygen. One way that works is to surround it by `/** @cond */` and `/** @endcond */`.

---

*[drake/systems/lcm/translator_system.h, line 98 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmcJv4opGQWz9CyqXN:-KmmcJv4opGQWz9CyqXO:b-9dy6z0) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L98)):*
> ```objc
>             typename = typename std::enable_if<!std::is_base_of<
>                 systems::VectorBase<double>, DataType1>::value>::type,
>             typename = void>
> ```

BTW is this third typename needed?

---

*[drake/systems/lcm/translator_system.h, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeG7Uo9uAnrbwU7P1:-KmmeG7Uo9uAnrbwU7P2:b-toau8u) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L141)):*
> ```objc
>   /**
>    * Constructor when DataType is derived from systems::VectorBase<double>.
>    * An abstract input port and a vector valued output port are declared. The
> ```

BTW "... are declared" -> "Declares an abstract input port ..." (per styleguide)
META

---

*[drake/systems/lcm/translator_system.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeX6CG0b_cxTL77zY:-KmmeX6CG0b_cxTL77zZ:bi5vhdh) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L142)):*
> ```objc
>    * Constructor when DataType is derived from systems::VectorBase<double>.
>    * An abstract input port and a vector valued output port are declared. The
>    * model values for the input and output ports are set to @p translator
> ```

BTW "... are set to" -> "Sets the model values ..." (META)

---

*[drake/systems/lcm/translator_system.h, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-Kmme1jGX8W-QLPtNp6f:-Kmme1jGX8W-QLPtNp6g:b-9dy6z0) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L169)):*
> ```objc
>             typename = typename std::enable_if<!std::is_base_of<
>                 systems::VectorBase<double>, DataType1>::value>::type,
>             typename = void>
> ```

BTW is this third typename needed?

---

*[drake/systems/lcm/test/translator_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmZTU0vISEyEGcAmm3:-KmmZTU1dpXk4wFBCa8h:b1gp7zo) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/test/translator_test.cc#L24)):*
> ```cpp
> 
> // A derived BasicVector that holds the same amount of information as a
> // lcmt_drake_signal message.
> ```

BTW I'm not sure what you mean by "same amount of information". This and the previous struct comment both say that but they don't have the same amount of information as each other so can't both have the same amount of information as lcmt_drake_signal. Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-:-KmmepxEUo8jolw6ZxKt:b-ywwl94)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending a minor BTWs. Thanks!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/lcm/translator_base.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeY4fUOKKgObDnl0o:-KmmeY4gY4OhBFxg5k15:b32tzh7) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L14)):*
> ```objc
>  * under the System framework. Within the System frame, time can be acquired
>  * directly from the Context, so it is not uncommon to omit time from state
>  * representations (DataType). Meanwhile, a well defined Lcm message (MsgType)
> ```

BTW Does it matter if it's `Lcm` vs. `LCM`? Other points in the code mention `LCM` (`drake/automotive/README.md`).

---

*[drake/systems/lcm/translator_system.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmgMdVEk5hrD08Ex5R:-KmmgMdVEk5hrD08Ex5S:b-i99y8t) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L53)):*
> ```objc
> 
> /**
>  * An encoding systems that converts data of DataType to a Lcm message of
> ```

BTW Grammar `s/systems/system`

---

*[drake/systems/lcm/translator_system.h, line 98 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmcJv4opGQWz9CyqXN:-KmmfQ0_i8kStHWWpMaG:b-5oibxv) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L98)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this third typename needed?
</blockquote></details>

BTW I believe so - in order to prevent the need for partial specialization in the constructor / member function (which I think C++ will throw a fit over).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-:-KmmgEQhDjhRq8noHVl0:b-okgudc)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/lcm/translator_base.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmWOav8z6O1XiMnZQK:-KmmmcBBUlVGngzQKWh2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW frame -> framework
</blockquote></details>

Done.

---

*[drake/lcm/translator_base.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeY4fUOKKgObDnl0o:-Kmmma8-11jgeu4Zsgil:b-wm2gat) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L14)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Does it matter if it's `Lcm` vs. `LCM`? Other points in the code mention `LCM` (`drake/automotive/README.md`).
</blockquote></details>

idk.. probably at some point. 

---

*[drake/lcm/translator_base.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmWZdYBFD2lhBj1paz:-KmmmmQ79Aq04EgpmVs2:b7pbf6h) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/lcm/translator_base.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW That looks symmetric to me (comment says it is asymmetric).
</blockquote></details>

Yeah this is the most confusing part. What I wanted to say is MsgType + time = DataType, and time is the asymmetry. I removed the <pre> part. It would be more clear once I pr the other example. 

---

*[drake/systems/lcm/translator_system.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmdSM1NbJnNNgkyoqV:-KmmqYOJ2ekdPRhziMBc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider hiding this detail namespace and its contents from doxygen. One way that works is to surround it by `/** @cond */` and `/** @endcond */`.
</blockquote></details>

Done.

---

*[drake/systems/lcm/translator_system.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmgMdVEk5hrD08Ex5R:-Kmmqc9BT4OKRGewm5P5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L53)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Grammar `s/systems/system`
</blockquote></details>

Done.

---

*[drake/systems/lcm/translator_system.h, line 98 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmcJv4opGQWz9CyqXN:-KmmqeT4HIzWVUrFiWe3:be36js8) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L98)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I believe so - in order to prevent the need for partial specialization in the constructor / member function (which I think C++ will throw a fit over).
</blockquote></details>

yeah.. 

---

*[drake/systems/lcm/translator_system.h, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeG7Uo9uAnrbwU7P1:-KmmqqHID33dKvtIpLog:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L141)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "... are declared" -> "Declares an abstract input port ..." (per styleguide)
META
</blockquote></details>

Done.

---

*[drake/systems/lcm/translator_system.h, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmeX6CG0b_cxTL77zY:-KmmrLzN3VJ65875di4M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L142)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "... are set to" -> "Sets the model values ..." (META)
</blockquote></details>

Done.

---

*[drake/systems/lcm/translator_system.h, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-Kmme1jGX8W-QLPtNp6f:-KmmrNQ_VHTCjxVJjmqr:brx2yk6) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/translator_system.h#L169)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this third typename needed?
</blockquote></details>

same as above. 

---

*[drake/systems/lcm/test/translator_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-KmmZTU0vISEyEGcAmm3:-KmmrgP7DmGAlb3wZB84:b-drg3gj) ([raw file](https://github.com/robotlocomotion/drake/blob/30a2688b745c82adaf8abe295ee4acf762292a82/drake/systems/lcm/test/translator_test.cc#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm not sure what you mean by "same amount of information". This and the previous struct comment both say that but they don't have the same amount of information as each other so can't both have the same amount of information as lcmt_drake_signal. Please clarify.
</blockquote></details>

why not? they both hold N numbers and N strings? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360)*

**Comment by siyuanfeng-tri** [comment]
@sherm1 can you check the 1 blocking thing real quick when you get a chance, thanks much!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-:-Kn2QHD-8O3FsSp3RRij:bbsxk47)*

**Comment by sherm1** [comment]
I'm not blocking anything now @siyuanfeng-tri.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6360#-:-Kn5-RYcXLpFZsniU3NO:bvswvrt)*

**Pull request merged**
