### PR TITLE
GurobiSolver supports L2NormCost

### LINKED ISSUE #20552: AddL2NormCost is a footgun
**Is your feature request related to a problem? Please describe.**
Despite the warning attached to the docs, I have seen several people mistakenly assume that `AddL2NormCost` will add a convex cost and then not realize that Drake will attempt to solve the program using a generic non-linear solver. 

From an optimization standpoint, I cannot think of a time when the 2-norm squared is not an equally good substitute to the 2-norm. 

**Describe the solution you'd like**
Deprecated `AddL2NormCost` and replace it with `AddL2NormSquaredCost` which would simply be a wrapper to the currently implemented `AddL2NormCostUsingConicConstraint`.

@RussTedrake for discussion based on experience teaching Underactuated and Manipulation
@hongkai-dai for thoughts.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Partially resolves #20552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-:-Nu_uphPDOz3rpwV7CCB:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/gurobi_solver_internal.cc` line 135 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nu_v086051VhIhhQto_:-Nu_v086051VhIhhQtoa:b-5t6m9u) ([raw file](https://github.com/RobotLocomotion/drake/blob/e86e50c7b6a6fcc62a626e41e46306803db65e9b/solvers/gurobi_solver_internal.cc#L135)):*
> ```cpp
> }
> 
> namespace {
> ```

To reviewers: all the code inside this anonymous namespace is just moved out from `AddSecondOrderConeConstraints`, so that we can re-use the code. There is no real change within the functions inside this anonymous namespace.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 15 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/aggregate_costs_constraints.h` line 346 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nuad6Uq97UWwbHnG8Yr:-Nuad6Uq97UWwbHnG8Ys:b201qzn) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/aggregate_costs_constraints.h#L346)):*
> ```objc
>     std::vector<Eigen::Triplet<double>>* A_triplets, std::vector<double>* b,
>     int* A_row_count, std::vector<int>* psd_cone_length);
> ```

nit: spurious whitespace change.
___
*[`solvers/gurobi_solver.cc` line 759 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuadKQOAZLa1k2T_4rO:-NuadKQOAZLa1k2T_4rP:b201r04) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver.cc#L759)):*
> ```cpp
>   static never_destroyed<std::shared_ptr<void>> local_host_holder{
>       IsGrbLicenseFileLocalHost() ? GetScopedSingleton<GurobiSolver::License>()
>                                   : nullptr};
> ```

nit: spurious whitespace change?
___
*[`solvers/gurobi_solver.cc` line 905 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuadXMxDo4xwd-7IDkJ:-NuadXMxDo4xwd-7IDkK:b-kt44zf) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver.cc#L905)):*
> ```cpp
>                                      l2norm_costs_lorentz_cone_variable_indices,
>                                      model, &num_gurobi_linear_constraints);
>   }
> ```

nit: switch the order here to avoid breaking up the declaration of the variable `num_gurobi_linear_constraints` from its use



_Suggestion:_
```cpp
  if (!error) {
    error = internal::AddL2NormCosts(prog,
                                     l2norm_costs_lorentz_cone_variable_indices,
                                     model, &num_gurobi_linear_constraints);
  }
  int num_gurobi_linear_constraints = 0;
```
___
*[`solvers/gurobi_solver_internal.h` line 112 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nuady7m6W7Gm_DuSHHY:-Nuady7m6W7Gm_DuSHHZ:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.h#L112)):*
> ```objc
> // @param[in/out] num_gurobi_vars Number of variables in Gurobi model.
> // @param[out] lorentz_cone_variable_indices lorentz_cone_variable_indices[i] is
> // the indices of variable z for l2_norm_costs[i] in the Gurobi model.
> ```





_Suggestion:_
```objc
the indices of the variable
```
___
*[`solvers/gurobi_solver_internal.cc` line 136 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuaeH6BDfvSw2cLfii8:-NuaeH6BDfvSw2cLfii9:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L136)):*
> ```cpp
> 
> namespace {
> // Drake's MathematicalProgram imposes the second order cone constraint in this
> ```

nit:



_Suggestion:_
```cpp
the
```
___
*[`solvers/gurobi_solver_internal.cc` line 173 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nuaepi_E_41tHPJMxr_:-Nuaepi_E_41tHPJMxra:bvrx8vx) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L173)):*
> ```cpp
> //     [0  0 0 1 ... 0]
> //           ...
> //     [0  0 0 0 ... 1]
> ```

Shouldn't the top left corner of Q be `[[0, -1/2],[-1/2,0]]`? Otherwise `Q` isn't symmetric? Does Gurobi just not care?



_Suggestion:_
```cpp
// Q = [0 -1/2 0 0 ... 0]
//     [-1/2  0 0 0 ... 0]
//     [0  0 1 0 ... 0]
//     [0  0 0 1 ... 0]
//           ...
//     [0  0 0 0 ... 1]
```
___
*[`solvers/gurobi_solver_internal.cc` line 178 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudK-imEkeLBl3zSIT2:-NudK-imEkeLBl3zSIT3:bodksth) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L178)):*
> ```cpp
> // qrow stores the row    indices of the non-zero entries of Q.
> // qcol stores the column indices of the non-zero entries of Q.
> // qval stores the value          of the non-zero entries of Q.
> ```

Btw: why not use `Eigen::SparseMatrix` or `std::vector<Eigen::Triplet>` for this?

EDIT: The reason is because `GRBaddqconstr` expects this format. It might be worth documenting that? Not that important if you choose not to.



_Code quote:_
```cpp
// qrow stores the row    indices of the non-zero entries of Q.
// qcol stores the column indices of the non-zero entries of Q.
// qval stores the value          of the non-zero entries of Q.
```
___
*[`solvers/gurobi_solver_internal.cc` line 202 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuafSCI6H9_Y6vrf1EL:-NuafSCI6H9_Y6vrf1EM:b-989zju) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L202)):*
> ```cpp
>     qrow->push_back(z0_index);
>     qcol->push_back(z1_index);
>     qval->push_back(-1);
> ```

Ditto about Q being symmetric?



_Code quote:_
```cpp
    qrow->push_back(z0_index);
    qcol->push_back(z1_index);
    qval->push_back(-1);
```
___
*[`solvers/gurobi_solver_internal.cc` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudGuvY2_mH4sL-vAUb:-NudGuvY2_mH4sL-vAUc:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L379)):*
> ```cpp
>   int error = GRBgetintattr(model, "NumVars", &num_gurobi_vars);
>   DRAKE_ASSERT(!error);
>   // We declare the vector here outside of the for loop, so that we can re-use
> ```





_Suggestion:_
```cpp
the vectors
```
___
*[`solvers/gurobi_solver_internal.cc` line 388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudJap81s-eTXvlaXQp:-NudJap81s-eTXvlaXQq:b94hg81) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L388)):*
> ```cpp
>   std::vector<int> xz_indices;
>   std::vector<Eigen::Triplet<double>> M_triplets;
>   std::vector<char> sense;
> ```

Sorry could you describe this variable? The name isn't obvious to me

EDIT: I see that this is the nomenclature used by GRB. 



_Suggestion:_
```cpp
// This is used to when adding the linear constraints to the Gurobi model to indicate that we are adding equality constraints.
std::vector<char> sense;
```
___
*[`solvers/gurobi_solver_internal.cc` line 400 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudIzyt5NtHvznLs0br:-NudIzyt5NtHvznLs0bs:b3027v6) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L400)):*
> ```cpp
>     // Add the constraint z[1:]-C*x=d
>     xz_indices.clear();
>     xz_indices.reserve(num_x + num_z - 1);
> ```

nit: This might not actually be an optimization and we may be better off letting the vector naturally double in size.



_Code quote:_
```cpp
    xz_indices.reserve(num_x + num_z - 1);
```
___
*[`solvers/gurobi_solver_internal.cc` line 410 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudJTAI3PsrTM78WaL4:-NudJTAI3PsrTM78WaL5:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L410)):*
> ```cpp
>     // z[1:]-Cx will be written as M * [x;z[1:]], where M=[-C I].
>     ConvertSecondOrderConeLinearConstraint(C, xz_indices, &M_triplets);
>     // Gurobi expects matrix in the sparse row format.
> ```

nit:



_Suggestion:_
```cpp
// Gurobi expects the matrix in the sparse row format.
```
___
*[`solvers/test/gurobi_solver_test.cc` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudUxcaD88EMf94Al_q:-NudUxcb0_wwn9IXluD9:b85w3n5) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/test/gurobi_solver_test.cc#L317)):*
> ```cpp
>   GurobiSolver solver;
>   ShortestDistanceToThreePoints tester{};
>   tester.CheckSolution(solver);
> ```

The default tolerance of the test is `1E-5` which feels very low for such an easy problem and Gurobi. I recommend we either turn up the default accuracy and relax it for the bad solvers (my preference) , or at least ask for higher accuracy for Gurobi.



_Code quote:_
```cpp
tester.CheckSolution(solver);
```
___
*[`solvers/test/l2norm_cost_examples.cc` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudW-8v2qYwZIkWb5_Q:-NudW-8v2qYwZIkWb5_R:b-msxm2) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/test/l2norm_cost_examples.cc#L33)):*
> ```cpp
>         cos(M_PI / 3 * 2)) {
>       throw std::runtime_error(
>           "The angle at pts_[0] is less than 120 degrees.");
> ```

I worry that this would not be a sufficiently expressive message if anyone were to hit this error.



_Code quote:_
```cpp
      throw std::runtime_error(
          "The angle at pts_[0] is less than 120 degrees.");
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 11 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/gurobi_solver.cc` line 759 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuadKQOAZLa1k2T_4rO:-Nudw8ON1M4GJgLjSFr7:bnrhjoy) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver.cc#L759)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: spurious whitespace change?
</blockquote></details>

clang decides to reformat this line.
___
*[`solvers/gurobi_solver.cc` line 905 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuadXMxDo4xwd-7IDkJ:-NudwNzeAgnFsWUWZzg_:bvvnarh) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver.cc#L905)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: switch the order here to avoid breaking up the declaration of the variable `num_gurobi_linear_constraints` from its use
</blockquote></details>

This call to `AddL2NormCosts` will pass `num_gurobi_linear_constraints` as an argument, so I need to declare the variable before calling the function.
___
*[`solvers/gurobi_solver_internal.h` line 112 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nuady7m6W7Gm_DuSHHY:-NudxLOu-IEc-Bqe3luK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.h#L112)):*
> ```objc
> // @param[in/out] num_gurobi_vars Number of variables in Gurobi model.
> // @param[out] lorentz_cone_variable_indices lorentz_cone_variable_indices[i] is
> // the indices of variable z for l2_norm_costs[i] in the Gurobi model.
> ```

Done.
___
*[`solvers/gurobi_solver_internal.cc` line 173 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nuaepi_E_41tHPJMxr_:-NudxWn_0zLD1KT0vuUW:b-ubrpeb) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L173)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Shouldn't the top left corner of Q be `[[0, -1/2],[-1/2,0]]`? Otherwise `Q` isn't symmetric? Does Gurobi just not care?
</blockquote></details>

Right, Gurobi does not care if it is symmetric or not. See https://www.gurobi.com/documentation/current/examples/qcp_c_c.html for Gurobi's own example on imposing the rotated Lorentz cone.
___
*[`solvers/gurobi_solver_internal.cc` line 202 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuafSCI6H9_Y6vrf1EL:-NudyoJP952jrC6fRlKw:bqdjup) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L202)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto about Q being symmetric?
</blockquote></details>

As explained in the previous comment.
___
*[`solvers/gurobi_solver_internal.cc` line 379 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudGuvY2_mH4sL-vAUb:-Nudz2So7YWO5QKpgPqK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L379)):*
> ```cpp
>   int error = GRBgetintattr(model, "NumVars", &num_gurobi_vars);
>   DRAKE_ASSERT(!error);
>   // We declare the vector here outside of the for loop, so that we can re-use
> ```

Done.
___
*[`solvers/gurobi_solver_internal.cc` line 388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudJap81s-eTXvlaXQp:-NudzItO3M9GtUZmAPxU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L388)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Sorry could you describe this variable? The name isn't obvious to me

EDIT: I see that this is the nomenclature used by GRB.
</blockquote></details>

Done.
___
*[`solvers/gurobi_solver_internal.cc` line 400 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudIzyt5NtHvznLs0br:-NudzRoeDMc5lYIL2-VP:b-2lqvm8) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L400)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: This might not actually be an optimization and we may be better off letting the vector naturally double in size.
</blockquote></details>

Sorry, why we don't do it here? We did it in the previous PR https://github.com/RobotLocomotion/drake/pull/21117#pullrequestreview-1971716080
___
*[`solvers/test/gurobi_solver_test.cc` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudUxcaD88EMf94Al_q:-Nue-WJm7WkUNx4vOEa6:b-1wqanu) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/test/gurobi_solver_test.cc#L317)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The default tolerance of the test is `1E-5` which feels very low for such an easy problem and Gurobi. I recommend we either turn up the default accuracy and relax it for the bad solvers (my preference) , or at least ask for higher accuracy for Gurobi.
</blockquote></details>

Using the default tolerance of Gurobi, this problem can only be solved to the accuracy of 1E-5.

Gurobi doesn't usually solve second order cone programs to high accuracy, as they claim here https://www.gurobi.com/documentation/10.0/refman/constraints.html#subsubsection:QuadraticConstraints:~:text=Quadratic%20constraints%20are%20often%20much%20more%20challenging%20to%20satisfy%20than%20linear%20constraints%2C%20so%20tightening%20the%20parameter%20may%20increase%20runtimes%20dramatically.

I don't think it is helpful to increase the accuracy of Gurobi. The intention of the test is to check whether the L2 norm cost is transcribed to Gurobi correctly. Even if the accuracy is 1E-5, we can still definitively say that the problem is transcribed correctly.
___
*[`solvers/test/l2norm_cost_examples.cc` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudW-8v2qYwZIkWb5_Q:-Nue0KTl6e7KQBL91jrc:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/test/l2norm_cost_examples.cc#L33)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I worry that this would not be a sufficiently expressive message if anyone were to hit this error.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-:-Nue6B7s9O4OhvNEwqO1:bg7igkv)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/gurobi_solver.cc` line 905 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NuadXMxDo4xwd-7IDkJ:-Nue5QZo9Uu4zRbjioNY:b-6zc9jz) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver.cc#L905)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This call to `AddL2NormCosts` will pass `num_gurobi_linear_constraints` as an argument, so I need to declare the variable before calling the function.
</blockquote></details>

Ah I missed that
___
*[`solvers/gurobi_solver_internal.cc` line 400 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NudIzyt5NtHvznLs0br:-Nue64qp9HO8cCETdQRu:b-ie6h6y) ([raw file](https://github.com/RobotLocomotion/drake/blob/0895ebd06359696d006ec3b828d2264a6a1c99bf/solvers/gurobi_solver_internal.cc#L400)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, why we don't do it here? We did it in the previous PR https://github.com/RobotLocomotion/drake/pull/21117#pullrequestreview-1971716080
</blockquote></details>

You're right. My mistake.
___
*[`solvers/gurobi_solver_internal.cc` line 392 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-Nue5c5SAhpO8KBV2PA0:-Nue5c5SAhpO8KBV2PA1:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/1911dc28532e4d5494d3663260cceb04f8795cd1/solvers/gurobi_solver_internal.cc#L392)):*
> ```cpp
>   std::vector<int> xz_indices;
>   std::vector<Eigen::Triplet<double>> M_triplets;
>   // This is used when adding linear constraints to the Gurobi to indicate that
> ```

nit



_Suggestion:_
```cpp
 the Gurobi model
```

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-:-Nue97-V2mXgrsZbtg_T:b-69uc1d)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform! Just some minor spellings nits

> Reviewed 5 of 10 files at r1, 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-:-NugM9TKAqT9wFdECiuj:bir0xnp)* status: 5 unresolved discussions

___
*[`solvers/test/l2norm_cost_examples.cc` line 26 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NugLNY_AqX4f_-NaQRF:-NugLNY_AqX4f_-NaQRG:bw3x1kh) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc9444b52ef4623397024eb80849160de96ef99f/solvers/test/l2norm_cost_examples.cc#L26)):*
> ```cpp
>     const Eigen::Vector3d x_sol = result.GetSolution(x_);
>     // The solution of x is the Fermat point of the triangle. If the triangle
>     // has an angle greater than 120 degrees, then the Fermat point is sited at
> ```

nit "sited" => "situated"
___
*[`solvers/test/l2norm_cost_examples.cc` line 27 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NugLRK47WVy8vBhRPw5:-NugLRK47WVy8vBhRPw6:bahix42) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc9444b52ef4623397024eb80849160de96ef99f/solvers/test/l2norm_cost_examples.cc#L27)):*
> ```cpp
>     // The solution of x is the Fermat point of the triangle. If the triangle
>     // has an angle greater than 120 degrees, then the Fermat point is sited at
>     // the obtuse-angled vertex. Here we construected pts_[0] to be such vertex.
> ```

nit "constructed"

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 4 unresolved discussions

___
*[`solvers/test/l2norm_cost_examples.cc` line 26 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NugLNY_AqX4f_-NaQRF:-NugMuXxCQwqYnenswmm:b-qu1j12) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc9444b52ef4623397024eb80849160de96ef99f/solvers/test/l2norm_cost_examples.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "sited" => "situated"
</blockquote></details>

I actually copied it from wikipedia https://en.wikipedia.org/wiki/Fermat_point#:~:text=the%20Fermat%20point%20is%20sited%20at%20the%20obtuse%2Dangled%20vertex, they use sited.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 3 unresolved discussions

___
*[`solvers/test/l2norm_cost_examples.cc` line 26 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21256#-NugLNY_AqX4f_-NaQRF:-NugQITwCVOVwyofsggS:b-ipg5mq) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc9444b52ef4623397024eb80849160de96ef99f/solvers/test/l2norm_cost_examples.cc#L26)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I actually copied it from wikipedia https://en.wikipedia.org/wiki/Fermat_point#:~:text=the%20Fermat%20point%20is%20sited%20at%20the%20obtuse%2Dangled%20vertex, they use sited.
</blockquote></details>

Ah, sorry, and thanks!

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21256)* status: 1 unresolved discussion

**Pull request merged**
