### PR TITLE
Re-implement the uniformly random rotation.

### LINKED ISSUE #10319: Uniform random rotations (bug?)
Was curious about the mathematical justification for the uniform random rotations so I looked at the justification/reference here: 
https://github.com/RobotLocomotion/drake/blob/master/math/random_rotation.h#L20
But that reference only tells me how to sample uniformly from the sphere; nothing about rotations.  

According to 
http://en.wikipedia.org/wiki/Rotation_matrix#Uniform_random_rotation_matrices
Our implementation is actually wrong.  The angle of axis angle should not be uniformly distributed.

Proposal:
`UniformlyRandomQuaternion` should just sample from the unit sphere (4D), via four Gaussian random variables normalized.  `UniformlyRandomAxisAngle` (and others) should use the `UniformlyRandomQuaternion`.

Cc @hongkai-dai

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #10319 

@soonho-tri , could you please take a look at this PR? I found that now UniformlyRandomAngleAxis<T>() doesn't work for T = symbolic::Expression. You could uncomment the line https://github.com/hongkai-dai/drake/blob/61ec160b2ad50381124e2ac7a7153d4cbbca104b/math/test/random_rotation_test.cc#L76-L77, the code throws an error
```
unknown file: Failure
C++ exception with description "The following environment does not have an entry for the variable random_uniform_0

" thrown in the test body.
```
And I checked that the environment is empty. On the contrary, we could still use `UniformlyRandomRotationMatrix<symbolic::Expression>()`. Both `UniformlyRandomRotationMatrix` and `UniformlyRandomAngleAxis` calls `UniformlyRandomQuaternion`. I suspect the reason why the rotation matrix works, while angle axis doesn't, is that converting quaternion to angle axis requires an "if" statement, and when we use symbolic expression with if statement, it somehow generates a symbolic formula, and the symbolic engine doesn't work (I don't fully understand why symbolic formula doesn't work here). On the other hand, converting a quaternion to a rotation matrix doesn't require any if statement.

I am OK to forbid instantiating `UniformlyRandomAngleAxis<symbolic::Expression>`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12562)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> ... now UniformlyRandomAngleAxis() doesn't work for T = symbolic::Expression.

If you look at Eigen::AngleAxis conversion from Quaternion, most of the if-branches relate to dealing with Quaternions whose norm is very small or zero.  If I am reading your formula correctly, its norm is always one.  So, you could create AngleAxis values directly along the lines of
```
AngleAxis result;
result.angle() = T(2.0) * atan2(T(1.0), abs(quaternion.w()));
result.axis() = if_then_else(quaternion.w() < 0, -quaternion.vec(), quaternion.vec());
return result;
```

**Comment by soonho-tri** [comment]
FYI, https://github.com/eigenteam/eigen-git-mirror/blob/master/Eigen/src/Geometry/AngleAxis.h#L162-L191

When `T = symbolic::Expression`, those conditionals cause a problem. For example, in `if (e < Scalar(0))`, it constructs a logical formula `e < 0` and evaluate it with an empty environment, which throws the exception.

**Comment by sherm1** [comment]
For good numerics when extracting the angle from the quaternion you'll want to use both cos(theta/2) and sin(theta/2) in the atan2 call, that is, something like atan2(||q.xyz||, q.w).

@mitiguy do we have a numerically sound quaternion to angle-axis conversion somewhere?

**Comment by jwnimmer-tri** [comment]
While we wait for the Quaterion->AxisAngle math to settle down, I wonder if we could merge a partial fix in the meantime?

The bug I care most about is UniformlyRandomQuaternion, since that is what MultibodyPlant uses.

We could leave UniformlyRandomAngleAxis unchanged, and only fix the other two in this PR, leaving the bug open to track finishing up the work.

Thoughts?

**Comment by sherm1** [comment]
Fine with me.

**Comment by jwnimmer-tri** [comment]
Sherm's suggestions differ how Eigen does it:

from https://github.com/eigenteam/eigen-git-mirror/blob/36b95962756c1fce8e29b1f8bc45967f30773c00/Eigen/src/Geometry/AngleAxis.h#L168-L191 

Given the open question, I'd like to merge just the Quaternion part then then do Q->AA as a separate PR?

**Pull request merged**
