### PR TITLE
Rename inverseKinBackend.cpp to allow later filename reuse.

### PR DESCRIPTION
**Pull request by sammy-tri**
This rename is in its own commit to allow later creation of a new file
called inverseKinBackend.cpp without producing confusing diffs.

An additional PR will be created after this one lands which will have better formatting than my initial attempt at a combined PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2123)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Conditionally :LGTM: provided the subsequent PR corrects the class name to match the file name.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2123#-:-KFk9ektKO7RDT-Mizuf:881146378)*

**Comment by sammy-tri** [comment]
It does, yes.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2123#-:-KFkAIkhBhapNM4LsIGf:2046916196)*

**Comment by david-german-tri** [comment]
test :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2123#-:-KFkN2KJhId4ephj71Uk:1145885365)*

**Comment by david-german-tri** [comment]
:lgtm_cancel: to prove Grant's was sufficient

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2123#-:-KFkNJ5AOIPdsgm3MpWZ:-1103997472)*

**Comment by jwnimmer-tri** [comment]
The 2addb53 was green in CI and passed both layers of code review.  Going to override-merge this one, instead of waiting for a338abb to pass CI.

**Pull request merged**
