### PR TITLE
Fix cpplint runtime/int

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix or nolint all cpplint runtime/int warnings, and stop suppressing the warning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2070)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/testIKoptionsmex.cpp, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-KF9lF8BJdmAtMJsds1K:-KF9lF8BJdmAtMJsds1L:132059903) ([raw file](https://github.com/robotlocomotion/drake/blob/637655569ceb7f78cacd7542829f033c1e64a964/drake/systems/plants/test/testIKoptionsmex.cpp#L21)):*
Took me a little while to prove to myself that there is no weird numeric types behaviour of auto in this case, but it appears to be safe since C++11.

---

*[drake/util/LCMScope.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-KF9mIJ9AW0Xlciwr9VH:-KF9mIJ9AW0Xlciwr9VI:690839178) ([raw file](https://github.com/robotlocomotion/drake/blob/637655569ceb7f78cacd7542829f033c1e64a964/drake/util/LCMScope.h#L25)):*
Need documentation that the returned value is in milliseconds as that is standard in neither timeval nor drake generally.

(yeah, it's a pre-existing bug, I know.  But it reads like a landmine to me.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2070)*

**Comment by jwnimmer-tri** [comment]
@ggould-tri Do you want to double-check my fix?  Reassign back to once if you're satisfied / if you don't care.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/LCMScope.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-KF9mIJ9AW0Xlciwr9VH:-KFEkl2_Xsv98DmauD6h:2008824444) ([raw file](https://github.com/robotlocomotion/drake/blob/637655569ceb7f78cacd7542829f033c1e64a964/drake/util/LCMScope.h#L25)):*
You document it as "seconds".  The return variable is named "msec".  One of these is still wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2070)*

**Comment by jwnimmer-tri** [comment]
*[drake/util/LCMScope.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-KF9mIJ9AW0Xlciwr9VH:-KFFL9zuB1rH1pUc2dya:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/637655569ceb7f78cacd7542829f033c1e64a964/drake/util/LCMScope.h#L25)):*
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2070)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-:-KFFS13MMB4ho_wCSX-O:1417088721)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Looks like msvc64 was a fluke.  Want to override-merge this for us?

**Comment by david-german-tri** [comment]
Huh, that's a new fluke.  @jwnimmer-tri, did you intentionally abort Jenkins?

**Comment by david-german-tri** [comment]
Also...why not actually switch to stdint.h, instead of suppressing the lint?

https://google.github.io/styleguide/cppguide.html#Integer_Types

I mean, suppressing the lint and enabling the check is still an improvement, so :lgtm:, just curious about the reasoning.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2070#-:-KFGg9g-_DeEOzKspWW3:360976315)*

**Comment by jwnimmer-tri** [comment]
>Huh, that's a new fluke. @jwnimmer-tri, did you intentionally abort Jenkins?

I did abort some CI builds today, but I didn't think they were on this PR?  In any case, I wouldn't worry about it.  It's possible I hit the red [x] button.

> Also...why not actually switch to stdint.h, instead of suppressing the lint?

My guess[1] was that `<mex.h>` declares its API methods using e.g. `long int*` as arguments -- which TTBOMK I cannot replace at call sites with `intfoo`_t`, because the API width is not fixed to a certain number of bytes.  In other words, we need to track the way matlab declares its variables, not the googlestyle way.

[1] Until #2080 is fixed, I'm not going to install matlab on my machine, so I couldn't easily tell whether my API guess was correct.

**Comment by david-german-tri** [comment]
Merging despite win64 abort (as discussed above) and drake005 Gurobi issues.

**Pull request merged**
