### PR TITLE
Use symbolic sparsity for direct-feedthrough analysis

### PR DESCRIPTION
**Pull request by david-german-tri**
Define the System::HasDirectFeedthrough API, which is pure virtual.  Implement it in LeafSystem using conservative values by default, symbolic analysis if available, and manual overrides if provided.  Implement it in Diagram using the same crude subsystem-level analysis we've always used.  

All the building blocks are now in place to do port-level Diagram sparsity analysis in a follow-up PR, although we will not be able to make use of it for DiagramBuilder-time algebraic loop detection until #2890 is resolved.

Migrate Integrator to the new API, which it satisfies using symbolic analysis with zero extra code.

@jadecastro for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5199)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri volunteering for platform review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-:-Kd8ay1-ZpOLrWZJqVjS:b-p7iy6j)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8ZnTvzXSyubAOvG1J:-Kd8ZnTw0qWpiWYzld49:bcbcpgi) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/diagram.h#L186)):*
> ```objc
>   /// Returns `true` as a conservative default.
>   bool has_any_direct_feedthrough() const override {
>     return true;
> ```

BTW So `true` here unconditionally (whereas before it used to be computed_ is possibly an API semantics regression, right?  We change the contract and using-code breaks silently?  I guess it's okay if CI likes it, but it seems possibly at least to have a compat workaround for now, where both public APIs share a common private implementation, but the new public API does a compat-check with the old public API, as in:
```c++
  has_any... { return PrivateHasAny(); }
  PrivateHasAny () { for ... HasAny(i); }
  HasAny...() {
    if (!has_any()) return false
    else return PrivateHasAny(); }
```
... or even just duplicate the implementations since they are so thin?

---

*[drake/systems/framework/diagram.h, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8au3s-BA8y5ATFUig:-Kd8au3twfRTuhqUtacX:b-nu0ubz) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/diagram.h#L196)):*
> ```objc
>   bool HasAnyDirectFeedthrough() const final {
>     // Respect legacy overrides.
>     if (!has_any_direct_feedthrough()) return false;
> ```

BTW These two lines don't change the behavior, but are OK as documentation if you like.

---

*[drake/systems/framework/diagram_builder.h, line 254 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8WOE9FNlSplP8wxyu:-Kd8WOE9FNlSplP8wxyv:b-cz56at) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/diagram_builder.h#L254)):*
> ```objc
>       // Systems, not of ports, and we must restrict ourselves to considering
>       // an entire System direct-feedthrough if it has direct feedthrough from
>       // any input to any output.
> ```

OK :sadpanda:

---

*[drake/systems/framework/test/leaf_system_test.cc, line 441 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8UNElek6SQIJpJghQ:-Kd8UNEmWw77-tj8UHNy:b-uxl5hx) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L441)):*
> ```cpp
>   system.AddAbstractInputPort();
>   system.AddAbstractOutputPort();
>   EXPECT_TRUE(system.HasAnyDirectFeedthrough());
> ```

BTW Consider `EXPECT_TRUE(system.HasAnyDirectFeedthrough(0));` for completeness?

---

*[drake/systems/framework/test/leaf_system_test.cc, line 454 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8UWD0crnhfC2zO-Mo:-Kd8UWD0crnhfC2zO-Mp:b-uvzg9o) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L454)):*
> ```cpp
>   DefaultFeedthroughSystem output_only;
>   output_only.AddAbstractOutputPort();
>   EXPECT_FALSE(output_only.HasAnyDirectFeedthrough());
> ```

BTW Consider `EXPECT_FALSE(system.HasAnyDirectFeedthrough(0));` for completeness?

---

*[drake/systems/framework/test/leaf_system_test.cc, line 495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8Uhafy2SjpLa1V6Px:-Kd8Uhafy2SjpLa1V6Py:bsduhzq) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L495)):*
> ```cpp
> }
> 
> const int kSize = 1;
> ```

BTW Should this be moved within the class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-:-Kd8bXNVd1eK3Np7ea0W:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8ZnTvzXSyubAOvG1J:-KdBhlyBG_xrrt6TqOVP:bimmy2f) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/diagram.h#L186)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW So `true` here unconditionally (whereas before it used to be computed_ is possibly an API semantics regression, right?  We change the contract and using-code breaks silently?  I guess it's okay if CI likes it, but it seems possibly at least to have a compat workaround for now, where both public APIs share a common private implementation, but the new public API does a compat-check with the old public API, as in:
```c++
  has_any... { return PrivateHasAny(); }
  PrivateHasAny () { for ... HasAny(i); }
  HasAny...() {
    if (!has_any()) return false
    else return PrivateHasAny(); }
```
... or even just duplicate the implementations since they are so thin?
</blockquote></details>

Yeah, I considered this, but since `grep` reveals no substantive call sites except  the ones migrated in this PR, and CI passes, I think it's safe, and clearer, as-is.

---

*[drake/systems/framework/diagram.h, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8au3s-BA8y5ATFUig:-KdBhyNeVoMCvuACSlYe:b-auo1nb) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/diagram.h#L196)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW These two lines don't change the behavior, but are OK as documentation if you like.
</blockquote></details>

I might be missing something obvious, but I don't think I agree with this claim.  Let's discuss f2f.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 441 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8UNElek6SQIJpJghQ:-KdBiO09Pv1XVRuRjx_-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L441)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider `EXPECT_TRUE(system.HasAnyDirectFeedthrough(0));` for completeness?
</blockquote></details>

Done.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 454 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8UWD0crnhfC2zO-Mo:-KdBiNi8i4qNwAg2aAlL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L454)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider `EXPECT_FALSE(system.HasAnyDirectFeedthrough(0));` for completeness?
</blockquote></details>

Done.

---

*[drake/systems/framework/test/leaf_system_test.cc, line 495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-Kd8Uhafy2SjpLa1V6Px:-KdBi_K6uwecJDULvA-v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b1c9977adde2b7ef4100d8389292f68a1a62de5/drake/systems/framework/test/leaf_system_test.cc#L495)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this be moved within the class?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jadecastro** [comment]
Sorry for the delay, done with my pass. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDbEBLVSD3NpetdjPw:-KdDbEBMglfUKzxOxfRj:b-ylbkxf) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram.h#L191)):*
> ```objc
>   /// Returns true if any output of the Diagram might have direct-feedthrough
>   /// from any input of the Diagram. The implementation is quite conservative,
>   /// because it does not actually inspect the fine-grained sparsity of
> ```

It should be explained what it means for a system to be "sparse" in this particular context. Moreover, I am not following what is meant by "fine-grained sparsity".

---

*[drake/systems/framework/diagram_builder.h, line 247 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDfas5SONYtEZB5qRJ:-KdDfas8mU5vWiP-Yst8:bh4ieue) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram_builder.h#L247)):*
> ```objc
>       // However, this observation does us no good without per-port evaluation
>       // from #2890, because #3455 made the execution order implicit instead of
>       // explicit. When we need to compute input A0, we will pull on output B0,
> ```

Consider replacing "pull" with "poll" (since you're checking the status of it.)

---

*[drake/systems/framework/diagram_builder.h, line 249 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDg6imetmDxXTkNGGU:-KdDg6imetmDxXTkNGGV:bo4f7cg) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram_builder.h#L249)):*
> ```objc
>       // explicit. When we need to compute input A0, we will pull on output B0,
>       // which will pull on both outputs of A. Pulling on output A0 in
>       // particular will spuriously pull on input A0, yielding an infinite loop.
> ```

BTW, Perhaps I'm missing the point, but why can't you simply bound this unrolling to be some large depth, and then report that we have an algebraic loop if it ever reaches this depth? 

(Alternatively, it's possible to check for a strongly-connected component in the i/o graph labeled with subsystems along the edges, and terminate once all subsystems of the SCC have been traversed at least once. This is less easy to do, but I think it's complete and guaranteed to terminate. Just an idea :)

---

*[drake/systems/framework/leaf_system.h, line 280 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdENSuVgCjdfsggC8SR:-KdENSuVgCjdfsggC8SS:bps9n53) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/leaf_system.h#L280)):*
> ```objc
>   ///
>   /// - Override this function directly, reporting manual sparsity. This method
>   ///   is recommended when ToSymbolic is infeasible or unreliable. Manually
> ```

infeasibility and unreliability are implementation-dependent, a detail we need not sort out here. Indeed the user could have other reasons. Why not just say:
```
This method is recommended when ToSymbolic has not been implemented.
```

---

*[drake/systems/framework/leaf_system.h, line 284 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdG5UiUJNwiLHHkjHNU:-KdG3u7dX0mBcLy_LhdL:b-59nk2x) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/leaf_system.h#L284)):*
> ```objc
>   ///   which an input port is direct-feedthrough to an output port, this
>   ///   function must return true for those two ports.
>   virtual bool DoHasDirectFeedthrough(const SparsityMatrix* sparsity,
> ```

It seems that for systems with direct feedthrough but with no means to compute the SparsityMatrix must still include the SparsityMatrix parameter and must also `#include "drake/systems/framework/sparsity_matrix.h", per style guide?

Consider overloading this function with a lower-overhead one with only `input_port` and `output_port` as the arguments (setting `sparsity` to `nullptr` under the hood) that LeafSystems can use if their authors so choose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-:-KdG8qK2xoWvXvxfNf3T:b1az5gy)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/diagram_builder.h, line 249 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDg6imetmDxXTkNGGU:-KdGEAjJGE2C0FnAmNbd:b-bltliu) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram_builder.h#L249)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Perhaps I'm missing the point, but why can't you simply bound this unrolling to be some large depth, and then report that we have an algebraic loop if it ever reaches this depth? 

(Alternatively, it's possible to check for a strongly-connected component in the i/o graph labeled with subsystems along the edges, and terminate once all subsystems of the SCC have been traversed at least once. This is less easy to do, but I think it's complete and guaranteed to terminate. Just an idea :)
</blockquote></details>

David and I would both agree that solving this possible (and relatively easy) in theory, but in practice until the System API is fixed per #2890 we cannot do it in code.  As soon as we call `EvalInputValue` on one of the above systems, the call will cycle through the forever until the stack explodes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jwnimmer-tri** [comment]
This PR provides high leverage to test that the `symbolic::Expression` scalartype works for various Systems that we've implemented.  (I have a PR in the wings that cherry-picked this to prove it.)  I hope we can get this PR in soon!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-:-KdTMtIpQO_N6cQyuGsn:bquac4a)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDbEBLVSD3NpetdjPw:-KdWBWfF6C8E9GgMSdQT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram.h#L191)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

It should be explained what it means for a system to be "sparse" in this particular context. Moreover, I am not following what is meant by "fine-grained sparsity".
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram_builder.h, line 247 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDfas5SONYtEZB5qRJ:-KdWBZBux6RQi4pgOi_p:b-c1n1ef) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram_builder.h#L247)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Consider replacing "pull" with "poll" (since you're checking the status of it.)
</blockquote></details>

No, "pull" is what I mean here (as contrasted with "push").

---

*[drake/systems/framework/diagram_builder.h, line 249 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdDg6imetmDxXTkNGGU:-KdWBfVKAQ8zvFoWOB7Y:bufgr29) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/diagram_builder.h#L249)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

David and I would both agree that solving this possible (and relatively easy) in theory, but in practice until the System API is fixed per #2890 we cannot do it in code.  As soon as we call `EvalInputValue` on one of the above systems, the call will cycle through the forever until the stack explodes.
</blockquote></details>

What @jwnimmer-tri said.

---

*[drake/systems/framework/leaf_system.h, line 280 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdENSuVgCjdfsggC8SR:-KdWBq0Mz_jH8rfhFwG0:ba58xvi) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/leaf_system.h#L280)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

infeasibility and unreliability are implementation-dependent, a detail we need not sort out here. Indeed the user could have other reasons. Why not just say:
```
This method is recommended when ToSymbolic has not been implemented.
```
</blockquote></details>

ToSymbolic could be implemented, and yet not provide the correct result for this purpose because of C++ native conditionals.  Rewrote to clarify, PTAL.

---

*[drake/systems/framework/leaf_system.h, line 284 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdG5UiUJNwiLHHkjHNU:-KdWF-D1qXgD7Y__Lt8M:b-aeu8w) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/leaf_system.h#L284)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

It seems that for systems with direct feedthrough but with no means to compute the SparsityMatrix must still include the SparsityMatrix parameter and must also `#include "drake/systems/framework/sparsity_matrix.h", per style guide?

Consider overloading this function with a lower-overhead one with only `input_port` and `output_port` as the arguments (setting `sparsity` to `nullptr` under the hood) that LeafSystems can use if their authors so choose.
</blockquote></details>

I understand where this request is coming from, but it's tough to square with the requirement that manual overrides trump the symbolic analysis.  I'd like to leave as-is, at least for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/framework/leaf_system.h, line 284 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-KdG5UiUJNwiLHHkjHNU:-KdWHLD6_9f-dSdlltCS:b6kkeyr) ([raw file](https://github.com/robotlocomotion/drake/blob/1594889fc336b3fd675ed441c6600e969c662131/drake/systems/framework/leaf_system.h#L284)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I understand where this request is coming from, but it's tough to square with the requirement that manual overrides trump the symbolic analysis.  I'd like to leave as-is, at least for now.
</blockquote></details>

BTW 
I see what you mean. It's reasonable, and the options are all well documented, so I don't foresee any confusion, only a bit of additional overhead for the corner case for systems that cannot do symbolic analysis. I guess it's fine the way it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5199#-:-KdWIoNJX7rd4xpBFoRz:bnfp4nl)*

**Pull request merged**
