### PR TITLE
Prototype for in-memory Mesh

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
@rpoyner-tri I've flagged a number of places down below.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-:-O3j7FBn6TEMrcox_YK0:b-cntd6h)* status: 8 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`common/file_contents.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j2kvp3_m5A_vwPpY1:-O3j2kvp3_m5A_vwPpY2:bcgdft3) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L37)):*
> ```objc
> 
>   /** The contents of a nominal file. */
>   const std::string& contents() const { return contents_; }
> ```

@rpoyner-tri Naming question. 

`FileContents::contents()` seems painfully redundant. Something needs to give. Possible options:

- Alternate member name
    - `FileContents::value()`
    - `FileContents::string()`
- Alternate class name
    - `MemoryFile::contents()`

Vote?
___
*[`common/file_contents.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j37rZBZjmNHWX75It:-O3j37rZBZjmNHWX75Iu:b-1bi7t1) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L54)):*
> ```objc
>   Sha256 sha256_;
> 
>   // TODO(jwnimmer-tri) In the future, we might want to track additional
> ```

@rpoyner-tri  Meta data

For my purposes, extension or mimetype is critical. Mimetype is a bit more problematic because not all of our used file types have registered mimetypes (e.g., .mtl, .vtk, .bin). We'd have to introduce Drake-specific values.

The extensions are more standardized and printing them would probably make more sense to the user than mime type (e.g., `gltf+json` (from [list of registered mimetypes](https://www.iana.org/assignments/media-types/media-types.xhtml#model)).

So, as we include meta data, whence comes it? If we have two different ways of saying the same thing (mimetype `obj` and extension `.obj`) do we reconcile and bark if they don't match.

Also soliciting any and all other thoughts.
___
*[`geometry/in_memory_mesh.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j4pz69_AtYE-8XReM:-O3j4pz69_AtYE-8XReN:b5k6ffn) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L32)):*
> ```objc
> };
> 
> /** Provides an general abstraction to the definition of a mesh. A mesh
> ```

@rpoyner-tri 

Right now I've got these two structs mashed into one file...that doesn't feel *wholly* unreasonable, but I'm open to counter arguments. Feel free to make some.
___
*[`geometry/in_memory_mesh.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j50qV7RVKdGxdfWbn:-O3j50qV7RVKdGxdfWbo:b-9gnkus) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L39)):*
> ```objc
>   /** Constructs from a file path. This explicitly allows for implicit
>    conversion from std::filesystem::path. */
>   // NOLINTNEXTLINE(runtime/explicit) This conversion is desirable.
> ```

@rpoyner-tri I found implicit conversions very convenient. The `MeshSource` is essentially a kind of `variant` with sugar, so it felt nice to get that `variant`-like behavior. Is that too much? Is that not enough (e.g., I can't *assign* a file path to a `MeshSource`; should I?)
___
*[`geometry/in_memory_mesh.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6nUC6n2JC6KYC0qZ:-O3j6nUC6n2JC6KYC0q_:b-dz3p5j) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L54)):*
> ```objc
> 
>   /** Reports `true` if this source is a filesystem path. */
>   bool IsPath() const {
> ```

@rpoyner-tri I stole this spelling from `DataSource` -- I'm not sure why the predicates are CamelCase while the getters are snake_case. In that case, the actual cost of the predicate is simply an int compare. This seems to be about the same. THoughts on whether the predicate should likewise be snake case?
___
*[`geometry/in_memory_mesh.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6dypDORBLkhL_yYF:-O3j6dypDORBLkhL_yYG:ba24mai) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.cc#L25)):*
> ```cpp
> 
> MeshSource::MeshSource(InMemoryMesh mesh, std::string extension)
>     : source_(std::move(mesh)), extension_(std::move(extension)) {}
> ```

nit: I need to confirm that the extension is of the correct form ".lower".
___
*[`geometry/shape_specification.h` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j465R4-83BnklqvQU:-O3j465R4-83BnklqvQV:b1r0lzf) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/shape_specification.h#L491)):*
> ```objc
>    @param mesh_contents      The key in `mesh_data` that corresponds to the mesh
>                              file data (and not ancillary data).
>    @param name               A name to associate with the mesh file. This will
> ```

@rpoyner-tri This is how I'm currently getting the extension for the *main* file name. Would it be better to ask for the extension explicitly?

Also, none of the supporting files would end up with extensions in this way.

This signature is sugar, would it be better if I simply said, "You declare the `InMemoryMesh` (or `MeshSource`), and I'll simply use it."
___
*[`geometry/shape_specification.h` line 507 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j4g09-PRzPbzhPcpM:-O3j4g09-PRzPbzhPcpN:bq8zg5m) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/shape_specification.h#L507)):*
> ```objc
> 
>   /** Returns the source for this specification's mesh data. */
>   const MeshSource& source() const { return source_; }
> ```

@rpoyner-tri 

Would it be better to deprecate all of the other names in favor of just directly talking to the `MeshSource`? Probably.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/in_memory_mesh.h` line 22 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3mjYd5CZscRlu-1avC:-O3mjYd5CZscRlu-1avD:byxv0nm) ([raw file](https://github.com/RobotLocomotion/drake/blob/2be683e82d8027723647a378006cf8d2aa335cd6/geometry/in_memory_mesh.h#L22)):*
> ```objc
>  contents. Failure to provide the supporting files may or may not lead to
>  errors; it depends on the context in which the mesh data is used. */
> struct InMemoryMesh {
> ```

@rpoyner-tri 

It would be good if `InMemeoryMesh` could provide a unique hash that is a composite of the main mesh file and the supporting files. Given a bunch of shas, is there an accepted way to simply "merge" them?  A hash of hashes?

Admittedly, we have all of the bytes upon construction, so we could simply shove *all* bytes into a single hash anew.

However it's done,  it seems this would move from `struct` to `class`. We really don't want contents changing after construction and invalidating the sha.

**Review by rpoyner-tri — COMMENTED** [review]
Added some thoughts, before I do a complete study of the changes.

Weirdly, not all conversations offered me the "pondering" disposition.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-:-O3nS50z4BflRJDtu5p8:bhemgfl)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`common/file_contents.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j37rZBZjmNHWX75It:-O3nLQk0Af4HMT2LzEVM:b-ngoefv) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri  Meta data

For my purposes, extension or mimetype is critical. Mimetype is a bit more problematic because not all of our used file types have registered mimetypes (e.g., .mtl, .vtk, .bin). We'd have to introduce Drake-specific values.

The extensions are more standardized and printing them would probably make more sense to the user than mime type (e.g., `gltf+json` (from [list of registered mimetypes](https://www.iana.org/assignments/media-types/media-types.xhtml#model)).

So, as we include meta data, whence comes it? If we have two different ways of saying the same thing (mimetype `obj` and extension `.obj`) do we reconcile and bark if they don't match.

Also soliciting any and all other thoughts.
</blockquote></details>

I'm a ilttle hazy on the value of doing `mimetype` -- are there interfaces where having it would be better than extension?

Aside from that, if we have two notions of "file type" data, we probably will need a (maybe documentation only) mapping between the two. 

If one is a clear superset of the other, you could imagine that the stored value is the "better" one, and the getter for the other one just does a lookup in a static table.
___
*[`geometry/in_memory_mesh.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j4pz69_AtYE-8XReM:-O3nPmR39tX1j2K3navL:by1l751) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri 

Right now I've got these two structs mashed into one file...that doesn't feel *wholly* unreasonable, but I'm open to counter arguments. Feel free to make some.
</blockquote></details>

It would certainly not be the first file in Drake that had more than one abstraction in it, so maybe a good question is: what is the user experience of finding documentation and necessary include statements?

Generally I'm not a one-struct/class-per-file purist (Java can carry that torch without me, thanks). I suppose the more interesting question is whether these two things are components of a single abstraction in a way that makes keeping them together a good idea.
___
*[`geometry/in_memory_mesh.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6nUC6n2JC6KYC0qZ:-O3nQywD0yZMKHs9_JQk:b2ia460) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri I stole this spelling from `DataSource` -- I'm not sure why the predicates are CamelCase while the getters are snake_case. In that case, the actual cost of the predicate is simply an int compare. This seems to be about the same. THoughts on whether the predicate should likewise be snake case?
</blockquote></details>

DataSource may benefit from the "if it's internal, then no apologies are necessary" syndrome. I don't recall either the source code bulk or runtime complexity of those, nor do I recall any review conversations. In any case, I think CamelCase promises less than snake_case. If things underneath might change later, that's a consideration.
___
*[`geometry/in_memory_mesh.h` line 22 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3mjYd5CZscRlu-1avC:-O3nP4GSA8n38XVNu6vy:b-7drs7j) ([raw file](https://github.com/RobotLocomotion/drake/blob/2be683e82d8027723647a378006cf8d2aa335cd6/geometry/in_memory_mesh.h#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri 

It would be good if `InMemeoryMesh` could provide a unique hash that is a composite of the main mesh file and the supporting files. Given a bunch of shas, is there an accepted way to simply "merge" them?  A hash of hashes?

Admittedly, we have all of the bytes upon construction, so we could simply shove *all* bytes into a single hash anew.

However it's done,  it seems this would move from `struct` to `class`. We really don't want contents changing after construction and invalidating the sha.
</blockquote></details>

FWIW, combining hashes seems to be a current open question for c++ (other systems/languages maybe have different answers?):
* https://htmlpreview.github.io/?https%3A%2F%2Fgithub.com%2FHowardHinnant%2Fpapers%2Fblob%2Fmaster%2Fhashing.html=
* https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3333.html
* https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3876.pdf

Certainly, shoving all of the bytes into the hash seems like it should be both simple and sound.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`common/file_contents.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j2kvp3_m5A_vwPpY1:-O3nQkIq-ic2kAE5CIAs:bm7m73g) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri Naming question. 

`FileContents::contents()` seems painfully redundant. Something needs to give. Possible options:

- Alternate member name
    - `FileContents::value()`
    - `FileContents::string()`
- Alternate class name
    - `MemoryFile::contents()`

Vote?
</blockquote></details>

I'll need to read the whole thing and mess about a bit to have an informed opinion.
___
*[`geometry/in_memory_mesh.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j50qV7RVKdGxdfWbn:-O3nQa3a2bTgS19_w5Ga:bdbuif8) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri I found implicit conversions very convenient. The `MeshSource` is essentially a kind of `variant` with sugar, so it felt nice to get that `variant`-like behavior. Is that too much? Is that not enough (e.g., I can't *assign* a file path to a `MeshSource`; should I?)
</blockquote></details>

I may have to write some throwaway code to form an opinion here.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`common/file_contents.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j2kvp3_m5A_vwPpY1:-O3nrp3-6RJMTCWw7MM5:b-q5j1yc) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L37)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll need to read the whole thing and mess about a bit to have an informed opinion.
</blockquote></details>

vote: MemoryFile. The object is not just the contents, but also metadata, name, hash, etc.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.h` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j465R4-83BnklqvQU:-O3nwCQ099gCmqWEi0Yi:bm97084) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/shape_specification.h#L491)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri This is how I'm currently getting the extension for the *main* file name. Would it be better to ask for the extension explicitly?

Also, none of the supporting files would end up with extensions in this way.

This signature is sugar, would it be better if I simply said, "You declare the `InMemoryMesh` (or `MeshSource`), and I'll simply use it."
</blockquote></details>

Still studying the surroundings, but why wouldn't this constructor take a FileContents (or MemoryFile) for all of the files, not just the supporting files?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.h` line 507 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j4g09-PRzPbzhPcpM:-O3szGUGA8Uo_maX6rzk:bhphf76) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/shape_specification.h#L507)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri 

Would it be better to deprecate all of the other names in favor of just directly talking to the `MeshSource`? Probably.
</blockquote></details>

Yes, deprecation, please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 10 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`tools/workspace/tinyobjloader_internal/repository.bzl` line 8 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4HCruQBCF53aK-uhho:-O4HCruR4fprO9cawlO7:b-yqiljg) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3724779feae1d8b4979c23a5733f0e7adc118b0/tools/workspace/tinyobjloader_internal/repository.bzl#L8)):*
> ```Starlark
>     github_archive(
>         name = name,
>         local_repository_override = "/home/seancurtis/code/tinyobjloader",
> ```

Any chance of converting this magic to patches?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 10 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`tools/workspace/tinyobjloader_internal/repository.bzl` line 8 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4HCruQBCF53aK-uhho:-O4HTMCB46gW7zvNFMso:b-ms1dsr) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3724779feae1d8b4979c23a5733f0e7adc118b0/tools/workspace/tinyobjloader_internal/repository.bzl#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Any chance of converting this magic to patches?
</blockquote></details>

Of course -- that's part of the newest commit. If you look in the commit message, it talks about doing that conversion. I usually stall to make sure it does what I need it to do. Easier to correct that way than as a patch.

That's the downside of my routinely pushing to a WIP PR. I sometimes push things in an intermediate state. But I anticipate the patch will appear today or tomorrow at the latest.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/in_memory_mesh.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6dypDORBLkhL_yYF:-O4LOyxo7kcClmg-TfFK:b-d86gp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.cc#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I need to confirm that the extension is of the correct form ".lower".
</blockquote></details>

maybe set this one to "working" disposition?

**Comment by SeanCurtis-TRI** [comment]
*[`multibody/parsing/detail_mesh_parser.cc` line 50 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4q40aO16V3vjjcwcpY:-O4q40aO16V3vjjcwcpZ:bveb78j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1b1312d79ed5605f5084e2b19b5d1ca6c9a88dc/multibody/parsing/detail_mesh_parser.cc#L50)):*
> ```cpp
>                                                  mtl_basedir,
>                                                  {.diagnostic = diagnostic,
>                                                   .allowed_shape_count = 1});
> ```

@rpoyner-tri I removed the "allowed shape count" entirely. I assumed that was an old legacy thing and not specifically designed.

It does have the implication that the "name" returned, I believe, defaults to the last object name encountered. Let me know what you think about that.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/in_memory_mesh.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6nUC6n2JC6KYC0qZ:-O5ElaWy0_B4_eve7R_v:b-g47rpq) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

How about from a pure matching perspective. Shall I push the getters to match the tests in spelling?
</blockquote></details>

If you want them to match case, and you don't expect this class to get any more complex, I suppose they could all be snake_case.
___
*[`common/file_contents.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j37rZBZjmNHWX75It:-O5EmgfV7CH4LSsEGdVt:b-6w3psk) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/common/file_contents.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I generally favor extension over mimetype. There are applications where we use mimetype (e.g., encoding URIs). I figure we can provide some code that maps Drake's known extensions to Drake's known mime types. It would also provide a central location for Drake-specific mime type definitions (as necessary).
</blockquote></details>

That sounds good to me.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/in_memory_mesh.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j50qV7RVKdGxdfWbn:-O5FN0zd8zxDmSWwTu-O:b-k13zki) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L39)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I may have to write some throwaway code to form an opinion here.
</blockquote></details>

Having fiddled with `explicit` on these, I agree. Implicit is OK.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`multibody/parsing/detail_mesh_parser.cc` line 50 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4q40aO16V3vjjcwcpY:-O5FRj_9CuCS4VqCV24H:b-umwm5k) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1b1312d79ed5605f5084e2b19b5d1ca6c9a88dc/multibody/parsing/detail_mesh_parser.cc#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@rpoyner-tri I removed the "allowed shape count" entirely. I assumed that was an old legacy thing and not specifically designed.

It does have the implication that the "name" returned, I believe, defaults to the last object name encountered. Let me know what you think about that.
</blockquote></details>

So, let me see if I understand the consequences. The old way was "multi-mesh obj file bad, no biscuit." The new way (so far) is multi-mesh obj file accepted, and we silently only use the lexically last mesh and name, and ignore the rest of the file.  Strictly speaking, I think that violates the parsing goal of "every input is one of: used in a model, causes a diagnostic, or is ignored for some documented reason".

I'm generally in favor of accepting more examples of files if we can do something principled, or at least documented. Do we have multi-mesh obj file examples from the wild to use in thinking this through?

**Comment by SeanCurtis-TRI** [comment]
*[`multibody/parsing/detail_mesh_parser.cc` line 50 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4q40aO16V3vjjcwcpY:-O5FVBu9CyBUK6JCZLag:b-wdvyjh) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1b1312d79ed5605f5084e2b19b5d1ca6c9a88dc/multibody/parsing/detail_mesh_parser.cc#L50)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, let me see if I understand the consequences. The old way was "multi-mesh obj file bad, no biscuit." The new way (so far) is multi-mesh obj file accepted, and we silently only use the lexically last mesh and name, and ignore the rest of the file.  Strictly speaking, I think that violates the parsing goal of "every input is one of: used in a model, causes a diagnostic, or is ignored for some documented reason".

I'm generally in favor of accepting more examples of files if we can do something principled, or at least documented. Do we have multi-mesh obj file examples from the wild to use in thinking this through?
</blockquote></details>

Half right. We'll use the whole mesh, but its *name* will be the lexically last name.

We could modify that in some way:

1. Re-introduce the *very* artificial constraint on the number of objects (this would be bad, in my estimation).
2. Define the name some other way.
   - base it on file name. (This gets my vote as the average roboticist doesn't play around with the *insides* of .obj files, but will recognize a filename when they see it).
   - base it on a combination of object names.

As I see it, the name has no load-bearing significance and has the most flexibility.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`multibody/parsing/detail_mesh_parser.cc` line 50 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4q40aO16V3vjjcwcpY:-O5FicDOA69qIjFCdUYx:bdlxrmh) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1b1312d79ed5605f5084e2b19b5d1ca6c9a88dc/multibody/parsing/detail_mesh_parser.cc#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Half right. We'll use the whole mesh, but its *name* will be the lexically last name.

We could modify that in some way:

1. Re-introduce the *very* artificial constraint on the number of objects (this would be bad, in my estimation).
2. Define the name some other way.
   - base it on file name. (This gets my vote as the average roboticist doesn't play around with the *insides* of .obj files, but will recognize a filename when they see it).
   - base it on a combination of object names.

As I see it, the name has no load-bearing significance and has the most flexibility.
</blockquote></details>

Ah. So, yeah, if we are using all of the geometry, I'm fairly unconcerned about what we do with names.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21792)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/in_memory_mesh.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O3j6nUC6n2JC6KYC0qZ:-O5txne4EZ8Jgf1fPI93:b-6ps9dy) ([raw file](https://github.com/RobotLocomotion/drake/blob/898d8abc0958b5e39a1fce581a4aebc221c3c33e/geometry/in_memory_mesh.h#L54)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

If you want them to match case, and you don't expect this class to get any more complex, I suppose they could all be snake_case.
</blockquote></details>

I've submitted a [draft PR](https://github.com/RobotLocomotion/drake/pull/21875) including `MemoryFile` and `FileSource`. As this is just a special kind of `FileSource` I'll see what the consensus view on that API is and make this conform.
___
*[`multibody/parsing/detail_mesh_parser.cc` line 50 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21792#-O4q40aO16V3vjjcwcpY:-O5ty0Wt1oYynSUyY6gG:bgjpk8r) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1b1312d79ed5605f5084e2b19b5d1ca6c9a88dc/multibody/parsing/detail_mesh_parser.cc#L50)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ah. So, yeah, if we are using all of the geometry, I'm fairly unconcerned about what we do with names.
</blockquote></details>

SOunds good. I'll leave it as it *currently* is.

**Comment by SeanCurtis-TRI** [comment]
This has grown stale and doesn't reflect the PR strategy. The PR #21881 supplants this.

**Pull request closed without merging**
