### PR TITLE
Temporarily disable one more test that requires Gurobi.

### PR DESCRIPTION
**Pull request by david-german-tri**
See #5862.

@soonho-tri for all review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5865)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-release please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5865)*

**Comment by david-german-tri** [comment]
Bazel builds pass; merging.

**Pull request merged**
