### PR TITLE
[doc] Add release notes v1.12.0

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
*[`doc/_release-notes/v1.12.0.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLN7cMN4VUH0f_0jiln:-NLN7cMN4VUH0f_0jilo:b7oyiy1) ([raw file](https://github.com/robotlocomotion/drake/blob/ad36610218aea486a3443d0fcce4c04d63f961db/doc/_release-notes/v1.12.0.md#L11)):*
> ```Markdown
> # Breaking changes since v1.11.0
> 
> * `InputPort::Allocate` (introduced in v1.11.0) has been relocated to
> ```

nit Is this a breaking change?

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.12.0.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLN7cMN4VUH0f_0jiln:-NLN87svBhBwSlzrX2VW:b-4kxp3e) ([raw file](https://github.com/robotlocomotion/drake/blob/ad36610218aea486a3443d0fcce4c04d63f961db/doc/_release-notes/v1.12.0.md#L11)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is this a breaking change?
</blockquote></details>

Something went wrong with the note curation here.  I have on my TODO list to circle back here and push new text.

**Comment by ggould-tri** [comment]
*[`doc/_release-notes/v1.12.0.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLN7cMN4VUH0f_0jiln:-NLN8oJ44yeBcXFWqIuW:b-ox94up) ([raw file](https://github.com/robotlocomotion/drake/blob/ad36610218aea486a3443d0fcce4c04d63f961db/doc/_release-notes/v1.12.0.md#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Something went wrong with the note curation here.  I have on my TODO list to circle back here and push new text.
</blockquote></details>

It was flagged as breaking by the tool; I reworded it a bit to express the API change but I agree it didn't seem breaking to me in any plausible way.  I'll relocate it down to nonbreaking when I next update.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`doc/_release-notes/v1.12.0.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLN7cMN4VUH0f_0jiln:-NLN9bPR7N5z4HM_8g7U:b8dfeg5) ([raw file](https://github.com/robotlocomotion/drake/blob/ad36610218aea486a3443d0fcce4c04d63f961db/doc/_release-notes/v1.12.0.md#L11)):*
> I'll relocate it down to nonbreaking when I next update.

No, that would be incorrect.  Easiest to just let me fix it as I've offered.

The breaking change is to the constructor signature and documentation.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`doc/_release-notes/v1.12.0.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLN7cMN4VUH0f_0jiln:-NLNgfOK4uPaUvUOsQWa:b-7m2yh6) ([raw file](https://github.com/robotlocomotion/drake/blob/ad36610218aea486a3443d0fcce4c04d63f961db/doc/_release-notes/v1.12.0.md#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I'll relocate it down to nonbreaking when I next update.

No, that would be incorrect.  Easiest to just let me fix it as I've offered.

The breaking change is to the constructor signature and documentation.
</blockquote></details>

Done.

The second sentence of the commit message described the break ("Demote InputPortBase constructor out of the Stable API (a breaking change).")  It probably got lost in the noise somewhere.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.12.0.md` line 56 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLNjV23ANZe9gbQBRAD:-NLNjV23ANZe9gbQBRAE:b-t14fma) ([raw file](https://github.com/robotlocomotion/drake/blob/52863c77c14a00f9e76036aa4d368fc427358289/doc/_release-notes/v1.12.0.md#L56)):*
> ```Markdown
> 
> * Add `ComputeQ` to rational forward kinematics ([#18476][_#18476])
> * Add ability to construct an `HPoyhedron` from a VPolytope ([#18493][_#18493])
> ```

nit (on 18493) the tool mis-files certain categories.  Changes to geometry/optimization should be in "Mathematical Program" not "Multibody".
___
*[`doc/_release-notes/v1.12.0.md` line 73 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLNiLpIDUjBQPj90MR_:-NLNiLpJDwHNWjoiAXkZ:bds88ny) ([raw file](https://github.com/robotlocomotion/drake/blob/52863c77c14a00f9e76036aa4d368fc427358289/doc/_release-notes/v1.12.0.md#L73)):*
> ```Markdown
> New features
> 
> * Add `CollisionCheckerContext` ([#18428][_#18428]) ([#18428][_#18428])
> ```

nit It looks like multi-commit PRs in this section ended up with duplicated parenthetical numbers on each line.
___
*[`doc/_release-notes/v1.12.0.md` line 91 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLNidHX24kilwXnIGYt:-NLNidHX24kilwXnIGYu:bb7lc4s) ([raw file](https://github.com/robotlocomotion/drake/blob/52863c77c14a00f9e76036aa4d368fc427358289/doc/_release-notes/v1.12.0.md#L91)):*
> ```Markdown
> 
> 
> * Remove uses of unsupported NumPy aliases ([#18486][_#18486])
> ```

nit 



_Suggestion:_
```Markdown
Drake is now compatible with NumPy 1.24
```
___
*[`doc/_release-notes/v1.12.0.md` line 117 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLNj1xj5ZAG7S-xvOpE:-NLNj1xk9900b-Uh1x4B:b9u8lwm) ([raw file](https://github.com/robotlocomotion/drake/blob/52863c77c14a00f9e76036aa4d368fc427358289/doc/_release-notes/v1.12.0.md#L117)):*
> ```Markdown
> Fixes
> 
> * Upgrade `rules_python` to latest release 0.16.1 ([#18524][_#18524])
> ```

nit 18524 should be in the next section ("Build dependencies")

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.12.0.md` line 73 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLNiLpIDUjBQPj90MR_:-NLR9e9PEbqBErtyp5cP:b7grt0d) ([raw file](https://github.com/robotlocomotion/drake/blob/52863c77c14a00f9e76036aa4d368fc427358289/doc/_release-notes/v1.12.0.md#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It looks like multi-commit PRs in this section ended up with duplicated parenthetical numbers on each line.
</blockquote></details>

That error was mine, I consolidated the multiple lines relating to the same added class without noticing that their PR number was the same.  Fixed.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by ggould-tri — COMMENTED** [review]
Release notes for review by feature owners:

+@EricCousineau-TRI
+@SeanCurtis-TRI
+@joemasterjohn
+@sammy-tri
+@rpoyner-tri
+@hongkai-dai

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556#-:-NLaM16p7KDG6E-zUoLS:b-1zmkpm)* status: LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform),SeanCurtis-TRI(platform),joemasterjohn,sammy-tri(platform),rpoyner-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @jwnimmer-tri, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLaUG5TDVbr6rFSmRCm:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @jwnimmer-tri, @rpoyner-tri, and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @ggould-tri, @hongkai-dai, @joemasterjohn, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.12.0.md` line 182 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-NLaUCEVA2JNgRbuY5p1:-NLaUCEW7GSAdGoTpisr:bgxhu6y) ([raw file](https://github.com/RobotLocomotion/drake/blob/aac71a93a6b2734257e970c87540139e3881b338/doc/_release-notes/v1.12.0.md#L182)):*
> ```Markdown
> 
> This release provides [pre-compiled binaries](https://github.com/RobotLocomotion/drake/releases/tag/v1.12.0) named
> ``drake-YYYYMMDD-{focal|jammy|mac|mac-arm64}.tar.gz``. See [Stable Releases](/from_binary.html#stable-releases) for instructions on how to use them.
> ```

Needs an update.



_Code quote:_
```Markdown
YYYYMMDD
```

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @jwnimmer-tri, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.12.0.md` line 182 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-NLaUCEVA2JNgRbuY5p1:-NLaVT1Q8rnfgj6bgKK3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/aac71a93a6b2734257e970c87540139e3881b338/doc/_release-notes/v1.12.0.md#L182)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs an update.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLabUwq749x7H0ZiqzZ:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @jwnimmer-tri, @sammy-tri, and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLadpBA-S0LWvtGwpWK:bnfp4nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @sammy-tri, and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @sammy-tri, and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a one line tweak request (I figure it's simpler for you to copy-and-paste the suggested line) than for me to do the requisite jumps to push my own single line.

> Reviewed 1 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLao1E785LNTFpPzXqD:b-aaj0a0)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),joemasterjohn,hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @hongkai-dai, @joemasterjohn, and @sammy-tri)

___
*[`doc/_release-notes/v1.12.0.md` line 150 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-NLanquX6tpDVjSRHSFB:-NLanquX6tpDVjSRHSFC:b64l26y) ([raw file](https://github.com/RobotLocomotion/drake/blob/e87bb4a47d453289f2206b6637391a91d7f3aec3/doc/_release-notes/v1.12.0.md#L150)):*
> ```Markdown
>   `pydrake.geometry.Convex()` has been renamed `pathname` ([#18536][_#18536])
> * Deprecate "register w.r.t. geometry" SceneGraph APIs ([#18448][_#18448])
>   * `geometry::SceneGraph.RegisterGeometry` three- and four-parameter overloads.
> ```

It's not the *number* of parameters that distinguish the deprecated overloads, but it's the ability to register a geometry with another *geometry* as parent.

Suggested:

```md
  * `geometry::SceneGraph.RegisterGeometry` (the geometry-as-parent overloads)
```

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.12.0.md` line 150 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-NLanquX6tpDVjSRHSFB:-NLaozIsERWRJ3cvjdNf:b-cvhs38) ([raw file](https://github.com/RobotLocomotion/drake/blob/e87bb4a47d453289f2206b6637391a91d7f3aec3/doc/_release-notes/v1.12.0.md#L150)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It's not the *number* of parameters that distinguish the deprecated overloads, but it's the ability to register a geometry with another *geometry* as parent.

Suggested:

```md
  * `geometry::SceneGraph.RegisterGeometry` (the geometry-as-parent overloads)
```
</blockquote></details>

FYI If you go to https://github.com/ggould-tri/drake/blob/release_notes-v1.12.0/doc/_release-notes/v1.12.0.md you can click the edit pencil icon, type in what you want, and commit.  It won't let you preview, but for tiny changes it's the easiest way to edit.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLapq2w7sReiJ5P9G55:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @sammy-tri, and @SeanCurtis-TRI)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @sammy-tri, and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @jwnimmer-tri, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.12.0.md` line 150 at r9](https://reviewable.io/reviews/robotlocomotion/drake/18556#-NLanquX6tpDVjSRHSFB:-NLb3VPfEwHlo4Ku-qYV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e87bb4a47d453289f2206b6637391a91d7f3aec3/doc/_release-notes/v1.12.0.md#L150)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If you go to https://github.com/ggould-tri/drake/blob/release_notes-v1.12.0/doc/_release-notes/v1.12.0.md you can click the edit pencil icon, type in what you want, and commit.  It won't let you preview, but for tiny changes it's the easiest way to edit.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @sammy-tri, and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with small edit commit, thanks!

> Reviewed 1 of 1 files at r1, 1 of 2 files at r7, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLbEqoP2QHEIGLpILsy:b-i4umud)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @sammy-tri, and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.12.0.md` line 163 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-NLbENCS0hPn2OIHxgka:-NLbENCT2rzbg5wxV8Kt:b-lsra28) ([raw file](https://github.com/RobotLocomotion/drake/blob/f65833fbf495ebfca645e8307cc2a6763482cfed/doc/_release-notes/v1.12.0.md#L163)):*
> ```Markdown
> * The `@json` external ([#18532][_#18532])
> * The `@nlopt` external ([#18532][_#18532])
> * Require finalize before state counts are available (remove previous
> ```

FYI Changed this line per Jeremy's editing suggestion.

**Review by jwnimmer-tri — COMMENTED** [review]
FYI @ggould-tri I am pretty confident in my review of the Mathematical Program notes curation.  I think it would be safe to unassign Hongkai; he can always suggest edits in a follow-up.

> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> Dismissed @SeanCurtis-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLbFVMA94VMKWp-r8pe:bur6e89)* status: LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @sammy-tri)

**Review by ggould-tri — COMMENTED** [review]
SGTM.  -@hongkai-dai 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556#-:-NLbHqdw0xqWh6-DBhNO:bisf2u5)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18556#-:-NLbIQ7P5qt0JVXJoann:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn (waiting on @EricCousineau-TRI, @joemasterjohn, @rpoyner-tri, and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18556)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn (waiting on @sammy-tri)

**Comment by ggould-tri** [comment]
FYI @BetsyMcPhail , this release is now up at https://github.com/RobotLocomotion/drake/releases/tag/v1.12.0 and is ready for you to tag docker images and upload.
* The release date is 2023-01-12
* The SHA is 643caa184dc645cf47775ed75d7a2052ab723dc7
* The release tag is v1.12.0

**Pull request merged**
