### PR TITLE
Set the initial guess for a single variable.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8173)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-:-L6EvRC7_pq5e39QF-qa:bvhsv4m)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.h, line 1947 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6I75dlJdR9x2gczD16:-L6IqO6uK45pq3yBcvzf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8cfec40e2604412a81d7f1652a0ff39c086fab/solvers/mathematical_program.h#L1947)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Should be descriptive, not imperative: `Gets the initial guess...`
http://drake.mit.edu/styleguide/cppguide.html#Function_Comments

Same for other comments below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-:-L6IqfMxyUbmWa8a58Oe:b-qxjhdt)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 699 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6Iug4GXI7-UCizqYg7:-L6Iug4HZhMbNzpV7F6r:b-fhjn35) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.cc#L699)):*
> ```cpp
> double MathematicalProgram::GetInitialGuess(
>     const symbolic::Variable& decision_variable) const {
>   return x_initial_guess_[FindDecisionVariableIndex(decision_variable)];
> ```

FYI The error message for these, when an index is not found, says "when calling GetSolution".  I don't particularly mind, but perhaps it should be adjusted to be more general, or have a detail string passed in, or etc.

---

*[solvers/mathematical_program.h, line 1988 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6IriuL6C_qA_MgEVdB:-L6IriuL6C_qA_MgEVdC:b-e6fotp) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.h#L1988)):*
> ```objc
> 
>   /**
>    * Sets the initial guess for the decision variables stored in @p var to be
> ```

BTW `@p var` seems stale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-:-L6Ivm_q1jcLnQt2gsII:bwkpaz3)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 699 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6Iug4GXI7-UCizqYg7:-L6J5KHIwh69PqwKnHvc:b-g6hep4) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.cc#L699)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The error message for these, when an index is not found, says "when calling GetSolution".  I don't particularly mind, but perhaps it should be adjusted to be more general, or have a detail string passed in, or etc.
</blockquote></details>

Hmm, I think the error message says that the decision variable is not in the program? Here is one instance the error is thrown
```
unknown file: Failure
C++ exception with description "y is not a decision variable in the mathematical program, when calling GetSolution.
" thrown in the test body.
```

This error message is in https://github.com/RobotLocomotion/drake/blob/master/solvers/mathematical_program_api.cc#L21-L27

---

*[solvers/mathematical_program.h, line 1988 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6IriuL6C_qA_MgEVdB:-L6J61yUajaCSISKm4DS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.h#L1988)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `@p var` seems stale.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8173)*

**Comment by jwnimmer-tri** [comment]
*[solvers/mathematical_program.cc, line 699 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8173#-L6Iug4GXI7-UCizqYg7:-L6JMb5aBVgc9JASMdvk:b-5et0bb) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.cc#L699)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Hmm, I think the error message says that the decision variable is not in the program? Here is one instance the error is thrown
```
unknown file: Failure
C++ exception with description "y is not a decision variable in the mathematical program, when calling GetSolution.
" thrown in the test body.
```

This error message is in https://github.com/RobotLocomotion/drake/blob/master/solvers/mathematical_program_api.cc#L21-L27
</blockquote></details>

That paste as "when calling GetSolution" in it, as I observed.  I don't think GetSolution has anything to do with GetInitialGuess?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8173)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.cc, line 699 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-L6Iug4GXI7-UCizqYg7:-L6JY3vp-H9Mccg1l8qj:bu680r) ([raw file](https://github.com/robotlocomotion/drake/blob/d1d07212485629a398a145d882cd7194e45f1a14/solvers/mathematical_program.cc#L699)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That paste as "when calling GetSolution" in it, as I observed.  I don't think GetSolution has anything to do with GetInitialGuess?
</blockquote></details>

Done. Good catch. That was probably due to a careless copy-and-paste.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8173#-:-L6Jji1o_us6v3KW0PEi:b-l70wzf)*

**Pull request merged**
