### PR TITLE
Add discrete contact pairs cache entry

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15225)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
Very nice, thanks. :lgtm: 

+@soonho-tri for platform review please.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15225#-:-MctIyjmD_JhHCeikM5P:b-2burdi)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
We introduce the following methods in this PR without adding a test case. Can you write a short test case per each?

```c++
DiscreteUpdateManager::EvalDiscreteContactPairs
MultibodyPlant::EvalDiscreteContactPairs
MultibodyPlantDiscreteUpdateManagerAttorney::EvalDiscreteContactPairs
```

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15225#-:-MctNG2V7VtyAeb8cLvZ:bzi8wy4)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
Many tests in master already depend on the correct results from `MultibodyPlant::EvalDiscreteContactPairs()`, everything contact dynamics depends on it. The fact CI passes is not enough? that is,caching is only an optimization on previously tested code.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15225#-:-MctU1RbADSQ4ciHO5v7:b-nimkog)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @xuchenhan-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

OK. I confirmed that the existing test cases covered newly added lines.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15225#-:-MctVi6KEluVb6V4D40K:bxrso7n)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,soonho-tri(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
