### PR TITLE
Port controllers to default_scalars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7100)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7100#-:-KuuazP_jODIOZLv8XZZ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Oops, this depends on #7091 before it will pass CI.  Sorry!  I think still its okay to review.  I'll have Jenkins rebuild it once 7091 merges.

**Comment by jadecastro** [comment]
:lgtm:  aside from the possible macro name typo (per #7101).

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7100#-:-Kuud9CotHRdYFGKCedt:bjopiye)*

**Pull request merged**
