### PR TITLE
examples/Cars refactorings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Collect examples/Cars refactorings, toward merging the various demos:
- Extract function CreateSimpleCarVisualizationAdapter.
- Extract function CreateTrajectoryCarSystem.
- Use unique robotnums, not unique link names, for the boxcar visualizations.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2526)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review please.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### examples/Cars refactorings
> 
> Collect examples/Cars refactorings, toward merging the various demos:
> 
> - Extract function CreateSimpleCarVisualizationAdapter.
> 
> - Extract function CreateTrajectoryCarSystem.
> 
> - Use unique robotnums, not unique link names, for the boxcar visualizations.
> 
> 
> 
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-:-KJpjQQjpc9JkLU3KDmg:546338502)*

**Comment by rpoyner-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@rpoyner-tri for feature review please.
</details>


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-:-KJq8a7J2yCy4S--vX5h:1417088721)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri for platform review please -- low priority.

**Comment by david-german-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/car_simulation.cc, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqagXAPP3mJgSTeFKK:-KJqagXAPP3mJgSTeFKL:-439965199) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L13)):*
> ```cpp
> using Eigen::Matrix;
> using Eigen::VectorXd;
> using Drake::AffineSystem;
> ```

nit: consider alphabetizing

---

*[drake/examples/Cars/car_simulation.cc, line 235 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqbzBZMndKjdPUNCvM:-KJqbzBZMndKjdPUNCvN:1532625920) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L235)):*
> ```cpp
> }  // namespace anonymous
> 
> std::shared_ptr<TrajectoryCar> CreateTrajectoryCarSystem(int index) {
> ```

This is only called from `demo_multi_car`, and it has multi-car assumptions baked in (e.g. `kNumCopies = 100`).  Why extract it?

---

*[drake/examples/Cars/car_simulation.cc, line 252 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqcHxrZVrwF2-2kR7Q:-KJqcHxrZVrwF2-2kR7R:-688563434) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L252)):*
> ```cpp
> std::shared_ptr<AffineSystem<
>   NullVector, SimpleCarState, EulerFloatingJointState>>
> CreateSimpleCarVisualizationAdapter() {
> ```

unit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/car_simulation.cc, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqagXAPP3mJgSTeFKK:-KJuV6s-vDzLhoqgjvzr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: consider alphabetizing
</details>
Done.

---

*[drake/examples/Cars/car_simulation.cc, line 235 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqbzBZMndKjdPUNCvM:-KJuVGK8zr4zuB1DZTy5:-681474012) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L235)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This is only called from `demo_multi_car`, and it has multi-car assumptions baked in (e.g. `kNumCopies = 100`).  Why extract it?
</details>
It's being extracted so that other (forthcoming) main programs will be able to use it.

kNumCopies is how many times to circulate around the loop, not how many cars should circulate (i.e., it's 100 is not the same as num_cars 100 in demo_multi_car).  I am not immediately seeing any other unwanted coupling between the demo_multi_car and this function.

---

*[drake/examples/Cars/car_simulation.cc, line 252 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJqcHxrZVrwF2-2kR7Q:-KJuZihe-n-77g9711Wc:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5093f1af9c6e32cfcef3945904227303b1df5c1e/drake/examples/Cars/car_simulation.cc#L252)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> unit test?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by rpoyner-tri** [comment]
causing more trouble...

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @david-german-tri for platform review please -- low priority.
</details>


---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 3 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuh7sGLwemKYbY3YwF:-KJuh7sH5QCB4SqsXedd:-1043449755) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/car_simulation_test.cc#L3)):*
> ```cpp
> #include "drake/examples/Cars/car_simulation.h"
> 
> #include "gtest/gtest.h"
> ```

perhaps out of scope for this, but should gtest includes be spelled with <> ?

---

*[drake/examples/Cars/test/CMakeLists.txt, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuhZ_4wKTxGM5W3ZLh:-KJuhZ_4wKTxGM5W3ZLi:-131036406) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/CMakeLists.txt#L18)):*
> ```CMake
>   add_executable(car_simulation_test car_simulation_test.cc)
>   target_link_libraries(car_simulation_test ${GTEST_BOTH_LIBRARIES} drakeCars)
>   add_test(NAME car_simulation_test COMMAND car_simulation_test)
> ```

I just noticed this -- why do we link 4 separate gtest executables? Is there any harm in linking them all into one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-:-KJuhn-DpLWap0vsMmnr:-1460751645)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/test/CMakeLists.txt, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuhZ_4wKTxGM5W3ZLh:-KJujFXqa8tEhX8yYul-:1672604233) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/CMakeLists.txt#L18)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> I just noticed this -- why do we link 4 separate gtest executables? Is there any harm in linking them all into one?
</details>
Are you asking why `target_link_libraries()` is called four times? Is there a better way to do that? Looking at [this page](https://cmake.org/cmake/help/v3.5/command/target_link_libraries.html) of the CMake 3.5 manual, I'm not seeing more than one target can be specified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/test/CMakeLists.txt, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuhZ_4wKTxGM5W3ZLh:-KJunX6o3N0GAoSJOQa8:-2019382081) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/CMakeLists.txt#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Are you asking why `target_link_libraries()` is called four times? Is there a better way to do that? Looking at [this page](https://cmake.org/cmake/help/v3.5/command/target_link_libraries.html) of the CMake 3.5 manual, I'm not seeing more than one target can be specified.
</details>
From offline... it was following prior convention, but we agree to leave it to author's discretion, so I might combine them in a future PR (or this one, if I get ambitious).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/test/CMakeLists.txt, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuhZ_4wKTxGM5W3ZLh:-KJun8IEzonm7QvUwyMD:908093293) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/CMakeLists.txt#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> From offline... it was following prior convention, but we agree to leave it to author's discretion, so I might combine them in a future PR (or this one, if I get ambitious).
</details>
Resolved f2f with jnimmer and dgerman. The original question was a test physical design question -- prefer N tests in one executable, or prefer N tests in N executables.  The answer is (as always) "depends" -- if builds are highly parallelizable (picture Google -- machine instances are free!), then maybe N-to-N is faster to build. If builds are mostly serial, then N-to-1 is probably preferred. As jnimmer says, the resolution is author's discretion, but I wanted to record the full context and nature of the question.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by liangfok** [comment]
*[drake/examples/Cars/test/CMakeLists.txt, line 18 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuhZ_4wKTxGM5W3ZLh:-KJuo8_YV2xpq9zfBFHJ:-626667794) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/CMakeLists.txt#L18)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Resolved f2f with jnimmer and dgerman. The original question was a test physical design question -- prefer N tests in one executable, or prefer N tests in N executables.  The answer is (as always) "depends" -- if builds are highly parallelizable (picture Google -- machine instances are free!), then maybe N-to-N is faster to build. If builds are mostly serial, then N-to-1 is probably preferred. As jnimmer says, the resolution is author's discretion, but I wanted to record the full context and nature of the question.
</details>
Got it. Thanks. Marking this as resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> causing more trouble...
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 3 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuh7sGLwemKYbY3YwF:-KJvZ8_AFrKBmz-g9ezj:995728895) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/car_simulation_test.cc#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> perhaps out of scope for this, but should gtest includes be spelled with <> ?
</details>
For everything except standard library includes, `<>` versus `""` appears to be author's discretion under the style guide.  There was some excessively long conversation about this a few months ago, but I don't think it was written down.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

I have been grudgingly writing `<Eigen/Foo>` since everyone else does, and using quotes for all other includes.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 15 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJv_Xdpr2UxRae8YvPr:-KJv_Xdpr2UxRae8YvPs:-1056372613) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/car_simulation_test.cc#L15)):*
> ```cpp
> namespace {
> 
> // Empty curves are rejected.
> ```

I don't understand this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-:-KJv_eHTkWBtAr1z-Nby:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 3 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJuh7sGLwemKYbY3YwF:-KJxfeHc-ZRvFvWilmrJ:97468907) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/car_simulation_test.cc#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> For everything except standard library includes, `<>` versus `""` appears to be author's discretion under the style guide.  There was some excessively long conversation about this a few months ago, but I don't think it was written down.
> 
> https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
> 
> I have been grudgingly writing `<Eigen/Foo>` since everyone else does, and using quotes for all other includes.
</details>
FTR: https://github.com/RobotLocomotion/drake/pull/1977

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by rpoyner-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-:-KJvre72tiLPE7DpquLx:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/car_simulation_test.cc, line 15 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KJv_Xdpr2UxRae8YvPr:-KJw2SncRw4vCMCwFxjs:1029040021) ([raw file](https://github.com/robotlocomotion/drake/blob/66123543ef0fe787fceb3bdf7caf7ad4e30b1c2a/drake/examples/Cars/test/car_simulation_test.cc#L15)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I don't understand this comment.
</details>
Ah, it's a pasto-o.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/examples/Cars/demo_multi_car.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KKCIh9NgVHZqAWbTomZ:-KKCIh9NgVHZqAWbTom_:-1055281972) ([raw file](https://github.com/robotlocomotion/drake/blob/675b7d6841f1532a0a1a7f8ae999d19c1687622a/drake/examples/Cars/demo_multi_car.cc#L71)):*
> ```cpp
>                                  DrakeJoint::ROLLPITCHYAW,
>                                  nullptr /*weld_to_frame*/);
>     world_tree->bodies.back()->robotnum = i + 1;
> ```

I'm not sure this is sufficient when the model has more than one rigid body.  Doesn't `robotnum` need to be set in _all_ of the bodies that belong to a particular model?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by jwnimmer-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/demo_multi_car.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KKCIh9NgVHZqAWbTomZ:-KKDbXIJnxwTO3d5jf0x:716521936) ([raw file](https://github.com/robotlocomotion/drake/blob/675b7d6841f1532a0a1a7f8ae999d19c1687622a/drake/examples/Cars/demo_multi_car.cc#L71)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'm not sure this is sufficient when the model has more than one rigid body.  Doesn't `robotnum` need to be set in _all_ of the bodies that belong to a particular model?
</details>
(1) I have no idea -- it's not documented or encapsulated.  I will consider it when I have time to review #2426.

(2) On the other hand, the robotnum here can't be any worse than only renaming the one joint, as was the case prior to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/demo_multi_car.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2526#-KKCIh9NgVHZqAWbTomZ:-KKDh0qur4UkqMPuq9Xs:-1264699416) ([raw file](https://github.com/robotlocomotion/drake/blob/675b7d6841f1532a0a1a7f8ae999d19c1687622a/drake/examples/Cars/demo_multi_car.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> (1) I have no idea -- it's not documented or encapsulated.  I will consider it when I have time to review #2426.
> 
> (2) On the other hand, the robotnum here can't be any worse than only renaming the one joint, as was the case prior to this PR.
</details>
Yes I agree its an incremental improvement over renaming the last link in the model.

FWIW, changing `robotnum` of just the last body of a multi-body model will definitely break [RigidBodyTree::findLink(std::string name, int robot)](https://github.com/RobotLocomotion/drake/blob/b1a10841d642c70bf824043f57286d60de4272d8/drake/systems/plants/RigidBodyTree.h#L666) when the same model is added multiple times since there will be multiple links in the rigid body tree with the same name and number.

Consider adding a comment saying the above is just a quick hack that only works for models with a single link.

I'll leave it to your discretion. Marking my status on this as "satisfied".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2526)*

**Comment by jwnimmer-tri** [comment]
Two LGTMs and jenkins loves it.  Merging with the green button ZOMG!

**Pull request merged**
