### PR TITLE
Define RoadRulebook abstract interface for modeling 'rules of the road'

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8261)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.

@rpoyner-tri for eyeballs.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L6tPPNglmZGmBN0Rg7X:b-ewr2g5)*

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-mVIBZPxESKekoOtN:-L7-mVIBZPxESKekoOtO:bab98v) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L39)):*
> ```objc
>   /// applicable to the provided `ranges`.
>   QueryResults FindRules(
>       const std::vector<LaneSRange>& ranges) const {
> ```

BTW, why are you not using `LaneSRoute` here?

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L7-lxxKVbCTnXzPZ2xM:b-jgly2z) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
Private methods should not be documented using Doxygen format.

> Only use Doxygen special comment blocks (comments declared with /// or /**) on published APIs (public or protected classes and methods). Code with private access or declared in .cc files should not use the Doxygen block format.

http://drake.mit.edu/styleguide/cppguide.html#Doxygen

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L7-oTLS5kLYQooV5_5B:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@ggould-tri for platform review.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L70bGNJQwHqkvkO6iUc:b-8qo47q)*

**Comment by maddog-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-mVIBZPxESKekoOtN:-L70bMZCGf7HrUWCYpRs:b-7vbbpv) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L39)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, why are you not using `LaneSRoute` here?
</blockquote></details>

Because `LaneSRoute` represents a route or path (e.g., it has the contiguity constraint).  The `ranges` parameter here is simply a bag of lane-ranges that are of interest to the caller. `FindRules()` doesn't need the ranges to be related to each other in any way and doesn't care about any such relations.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L70c2-GqK3sGr869egl:b-yv8ek7) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Private methods should not be documented using Doxygen format.

> Only use Doxygen special comment blocks (comments declared with /// or /**) on published APIs (public or protected classes and methods). Code with private access or declared in .cc files should not use the Doxygen block format.

http://drake.mit.edu/styleguide/cppguide.html#Doxygen
</blockquote></details>

Done.  Technically, these private methods _are_ part of the published API:  they are the methods which must be provided by a concrete implementation of the interface.  But they do get ignored by Doxygen, and if the rule is "Don't use doxygen blocks for blocks ignored by doxygen.", then that's the thing to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by maddog-tri** [comment]
(@liangfok 's comments addressed.)

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L70dPVI1psWKZ1N7xRU:b-37g1l4)*

**Comment by ggould-tri** [comment]
Is there a reason that you've put your test in the parent directory's tests dir?  We generally prefer putting them in a tests subdir or the same dir per http://drake.mit.edu/styleguide/cppguide.html#File_Names

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8261#-:-L70eIWN9FGUvR2H8iOY:beaq88w)*

**Comment by liangfok** [comment]
We had a similar discussion here: https://reviewable.io/reviews/robotlocomotion/drake/8156#-L6I3-xcI5g0P5BswwJ8

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L71LHGXAl0LwRH1gsBL:bkbr0q7)*

**Comment by maddog-tri** [comment]
Yeah -- I intend to do a fixup/move-files-around PR after this one (which is the last of a series of PR's populating `api/rules/`).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L71c5Qk4f93BU5LSqMi:b-jlwlh7)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L72lCBuVtAh5oxbn47Z:bimqvi6) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.  Technically, these private methods _are_ part of the published API:  they are the methods which must be provided by a concrete implementation of the interface.  But they do get ignored by Doxygen, and if the rule is "Don't use doxygen blocks for blocks ignored by doxygen.", then that's the thing to do.
</blockquote></details>

Good point. @sherm1, as the original proposer of the above-cited rule, should private pure virtual methods be an exception to the rule?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by jwnimmer-tri** [comment]
*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L72mLv0ftQ0Qh8AlQtL:b-5j6bn5) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Good point. @sherm1, as the original proposer of the above-cited rule, should private pure virtual methods be an exception to the rule?
</blockquote></details>

I'm not sure how making your pure virtual APIs for subclasses to override be private is ever going to work.  Can a subclass actually override these?

In any case, I'd say its defective for this API not to be part of Doxygen, even if I'm misremembering how C++ works and this actually compiles.

Make this section protected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by jwnimmer-tri** [comment]
*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L72svdEFnLlNOgpJiDN:bisnahc) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure how making your pure virtual APIs for subclasses to override be private is ever going to work.  Can a subclass actually override these?

In any case, I'd say its defective for this API not to be part of Doxygen, even if I'm misremembering how C++ works and this actually compiles.

Make this section protected.
</blockquote></details>

Wow, after reading more... yeah, I guess you can override them, you just can't call them.  And I see that in the class overview Doxygen we hint that these exist.  I guess its plausible to have methods not in Doxygen that all users have to override.  That's what IDE auto-complete is for, I guess?  So I withdraw from definitely-a-defect and I'll replace it with "yuck!" but not block anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L72wzznWBj--zjEGryk:b-ovvlza) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Wow, after reading more... yeah, I guess you can override them, you just can't call them.  And I see that in the class overview Doxygen we hint that these exist.  I guess its plausible to have methods not in Doxygen that all users have to override.  That's what IDE auto-complete is for, I guess?  So I withdraw from definitely-a-defect and I'll replace it with "yuck!" but not block anymore.
</blockquote></details>

For NVI, 
- the non-virtual interface should be `public` (of course), with user-oriented Doxygen,
- the _virtual_ methods (whether pure or not) should be `protected`, with Doxygen comments directed to the person who must override them, and
- the _override_ or _final_ implementations can be anywhere you like, but are best placed in private with developer `//` comments (if needed), unless there is some good reason they must be called directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by maddog-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L73GqeK-8OLbqB0DSJ5:bvnt5ts) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

For NVI, 
- the non-virtual interface should be `public` (of course), with user-oriented Doxygen,
- the _virtual_ methods (whether pure or not) should be `protected`, with Doxygen comments directed to the person who must override them, and
- the _override_ or _final_ implementations can be anywhere you like, but are best placed in private with developer `//` comments (if needed), unless there is some good reason they must be called directly.
</blockquote></details>

Everyone is a critic, but none of us is Herb Sutter:  http://www.gotw.ca/publications/mill18.htm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-:-L74lODEFGy1Bv2e1sD8:bnfp4nl)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/maliput/api/rules/road_rulebook.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8261#-L7-lxxKVbCTnXzPZ2xL:-L75PxivtqBCcrZaq98S:b-twly8t) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d3ce784db97cc3123e9cf41f1d51f26900ea0a/automotive/maliput/api/rules/road_rulebook.h#L64)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Everyone is a critic, but none of us is Herb Sutter:  http://www.gotw.ca/publications/mill18.htm
</blockquote></details>

That's where I learned about NVI! Making the virtuals protected is a concession to our use of Doxygen but otherwise I think Sutter's 17-year-old advice still applies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8261)*

**Pull request merged**
