### PR TITLE
Promote SimIiwaDriver to public API

### PR DESCRIPTION
**Pull request by nepfaff**
Moves `AddSimIiwaDriver` into `SimIiwaDriver` and binds `SimIiwaDriver`.
Adds a test case for `AddSimIiwaDriver`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)

### CODE REVIEW

**Comment by RussTedrake** [comment]
based on your "segfaults and many tests fail", I've added the do not review tag.

**Comment by nepfaff** [comment]
@RussTedrake It is ready for review now. Would you mind removing the do not review tag?

**Comment by jwnimmer-tri** [comment]
@nepfaff I think I just gave you permissions to edit the labels yourself (assuming I clicked the right buttons).  Can you give it a try?

**Comment by nepfaff** [comment]
It looks like the test fails because `There were tests whose specified size is too big`. What is our policy in this case? Can we increase the maximum size or should I make sure that the test is smaller?

**Comment by jwnimmer-tri** [comment]
If you pull up the full (unabbreviated) build log, it's actually a Clang-specific compiler error that's the problem:

```
[4:45:04 PM]  manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc:101:27: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
[4:45:04 PM]          builder.AddSystem(std::move(System<double>::Clone(*sim_plant_)));
```

**Comment by nepfaff** [comment]
I see. Thanks!
That test passed locally when running `bazel test //manipulation/kuka_iiwa/...`. Is there anything that I can do to spot this locally?

**Comment by jwnimmer-tri** [comment]
The very bottom of each CI log provides the flags necessary to match what it's doing.  In this case, I'd guess it would be something like `bazel test --config=clang //manipulation/kuka_iiwa/...`.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for review, either feature or platform.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-Nrg9WzCBXkv2u5-UMf9:b749h93)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

**Review by rpoyner-tri — COMMENTED** [review]
checkpoint, with some questions about documentation and tests. 

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-NrgGceqANYBQrjVRDnC:bw7iwzv)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-Nrg9cUH2pDMqifSQWfV:-Nrg9cUH2pDMqifSQWfW:b-g4ser) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L16)):*
> ```objc
> namespace kuka_iiwa {
> 
> /* SimIiwaDriver simulates the IIWA control and status interface using a
> ```

These comments should get promoted to be real Doxygen comments, now that they are leaving the internal namespace. So `/* */` ==> `/** */`.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-Nrg9rDX1ERA5SqLidjq:-Nrg9rDY9OHQeYwCOpvY:b-tbmgfl) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L61)):*
> ```objc
>   explicit SimIiwaDriver(const SimIiwaDriver<U>&);
> 
>   /// Given a @p plant (and associated @p iiwa_instance) and a @p builder,
> ```

minor: The comment style in the whole file should be consistent, either `///` or `/** */`. I believe we mildly prefer `/** */`.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 62 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrgAWvM5jI77VXW3lZR:-NrgAWvM5jI77VXW3lZS:bgcczy4) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L62)):*
> ```objc
> 
>   /// Given a @p plant (and associated @p iiwa_instance) and a @p builder,
>   /// installs in that builder the @p SimIiwaDriver system to control and
> ```

minor: I can't find where it's written down, but we are transitioning from `@p variable` to just `\`variable\``. See for example #20213.
___
*[`bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc` line 167 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrgDSm260rsUoHXKhWF:-NrgDSm260rsUoHXKhWG:b6zvuqi) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc#L167)):*
> ```cpp
>   }
> 
>   {
> ```

These new bindings should have some tests in tests/kuka_iiwa_test.py. Bindings tests don't need to re-test all the logic, but they should make sure the bindings work. What does that mean?
* (required) the entry points should get called at all
* (required) all of the items that are strings in this file should get spelled out in the test -- importantly, the argument names: `foo(my_argument=thing)`
* (maybe??, probably not) It's possible, but tedious,  to test the keep-alive clauses. From f2f with bindings expert @EricCousineau-TRI , it appears we only do it in a very narrow set of cases.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:, pending resolution of questions below.

I generated the pydrake documentation (with a version of the comment changes requested), and it looks at least as good as other existing docs.

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-NrgOeTV1QICOyum12vg:b-jqzux1)* status: 4 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 4 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 4 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

**Review by nepfaff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes

___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-Nrg9rDX1ERA5SqLidjq:-NrghRWPDgzpdHhiWhP3:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L61)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: The comment style in the whole file should be consistent, either `///` or `/** */`. I believe we mildly prefer `/** */`.
</blockquote></details>

done
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 62 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrgAWvM5jI77VXW3lZR:-NrghTcf4Fiia13NuBV4:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L62)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: I can't find where it's written down, but we are transitioning from `@p variable` to just `\`variable\``. See for example #20213.
</blockquote></details>

done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

**Review by nepfaff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-Nrg9cUH2pDMqifSQWfV:-NrghhTzCQj8dnsaFnDv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/manipulation/kuka_iiwa/sim_iiwa_driver.h#L16)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

These comments should get promoted to be real Doxygen comments, now that they are leaving the internal namespace. So `/* */` ==> `/** */`.
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc` line 167 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrgDSm260rsUoHXKhWF:-NrgrwPcAbeRSdZee0ml:bd5u1oj) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0d19a4a0d2e15f6d746f1140a3d8395cf4d750/bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc#L167)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

These new bindings should have some tests in tests/kuka_iiwa_test.py. Bindings tests don't need to re-test all the logic, but they should make sure the bindings work. What does that mean?
* (required) the entry points should get called at all
* (required) all of the items that are strings in this file should get spelled out in the test -- importantly, the argument names: `foo(my_argument=thing)`
* (maybe??, probably not) It's possible, but tedious,  to test the keep-alive clauses. From f2f with bindings expert @EricCousineau-TRI , it appears we only do it in a very narrow set of cases.
</blockquote></details>

Done. Thanks for the details!

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review, Wednesday schedule.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-NrgnwJRA2jex9Z1B3bS:b4wgpwe)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @nepfaff)

**Review by rpoyner-tri — COMMENTED** [review]
Hm, python linters got grumpy. You can reproduce and check quickly with:
```
$ bazel test --config=lint //...
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-NrhAG6U1BWI2f7LI97g:bj2snpq)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @nepfaff)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @nepfaff)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-:-NrlYGM-3MpIHsNvka_A:bcpz082)* status: 11 unresolved discussions, missing label for release notes (waiting on @nepfaff)

___
*[`manipulation/kuka_iiwa/build_iiwa_control.cc` line 17 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlUqrN-uN1evyMkKNq:-NrlUqrN-uN1evyMkKNr:b-hipcki) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/build_iiwa_control.cc#L17)):*
> ```cpp
> 
> using drake::lcm::DrakeLcmInterface;
> using kuka_iiwa::SimIiwaDriver;
> ```

nit Given the change to namespaces, this line is unnecessary and should be removed.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 4 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlUOIGEBU9t8kgbS0v:-NrlUOIGEBU9t8kgbS0w:b-sprlzr) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L4)):*
> ```objc
> 
> #include <optional>
> #include <string>
> ```

nit Unused include `<string>`.

(Nothing in this header file deals with strings, so we should remove this include statement.  Since the `sim_iiwa_driver.cc` file _does_ use strings, the include should relocate there.)
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 63 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlTNhd7BFzi1o5fobl:-NrlTNhd7BFzi1o5fobm:boj9p1s) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L63)):*
> ```objc
>   /** Given a `plant` (and associated `iiwa_instance`) and a `builder`,
>   installs in that builder the `SimIiwaDriver` system to control and
>   monitor an iiwa described by `controller_plant` in that plant.
> ```

nit I can't figure out what the meaning of "in that plant" is supposed to be here.  Is there some grammatical error maybe?
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 65 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlTZUh1tDBpdmjWj28:-NrlTZUh1tDBpdmjWj29:b2l011i) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L65)):*
> ```objc
>   monitor an iiwa described by `controller_plant` in that plant.
> 
>   The installed plant will connect itself to the actuation input port, state
> ```

nit I don't know what "installed plant" means here.  We're adding a `SimIiwaDriver` to the diagram (i.e., a controller), not a plant.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlSDJ-8o-vROzbo5GL:-NrlSDJ-8o-vROzbo5GM:bhcizo7) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L74)):*
> ```objc
>   `controller_plant`, so you must ensure that `controller_plant` has a
>   longer lifetime than the Diagram. */
>   static const systems::System<double>& AddSimIiwaDriver(
> ```

Drake's conventional name for a static member function that constructs and connects an instance of its enclosing class is `AddToBuilder`.  We should use that same name here, for consistency.



_Suggestion:_
```objc
AddToBuilder
```
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlT8MU9OFCyXjonrGE:-NrlT8MU9OFCyXjonrGF:b-i8zgfh) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L74)):*
> ```objc
>   `controller_plant`, so you must ensure that `controller_plant` has a
>   longer lifetime than the Diagram. */
>   static const systems::System<double>& AddSimIiwaDriver(
> ```

By convention, the first argument to `AddToBuilder` should always be the `builder` that's being added to.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.cc` line 168 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlU22D3bN7SVUAo8pP:-NrlU22E5Aua5xDhktlQ:b-qm7lv9) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.cc#L168)):*
> ```cpp
>     const std::optional<Eigen::VectorXd>& desired_iiwa_kp_gains,
>     IiwaControlMode control_mode) {
>   const std::string inner_name =
> ```

nit I'm not sure what the "inner" adjective is supposed to be telling me here.  Inner with respect to what?
___
*[`bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc` line 176 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlVwKr3yfirO8_cTza:-NrlVwKr3yfirO8_cTzb:bq9aybb) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc#L176)):*
> ```cpp
>             py::arg("ext_joint_filter_tau"), py::arg("kp_gains"),
>             // Keep alive, ownership: `return` keeps `controller_plant` alive.
>             py::keep_alive<0, 2>(), cls_doc.ctor.doc)
> ```

To my eye, we want `<1, 3>` here not `<0, 2>`.

0: return
1: self
2: control_mode
3: controller_plant
4: ...

https://pybind11.readthedocs.io/en/stable/advanced/functions.html#keep-alive

@rpoyner-tri please confirm
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 26 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlXkg12jf1jmonB5l4:-NrlXkg12jf1jmonB5l5:bc3u82l) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L26)):*
> ```Python
> 
> class TestKukaIiwa(unittest.TestCase):
>     def get_builder_plant_controller_plant(self):
> ```

nit I think usual verb for this operation would be "make..." not "get...".
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlXwiR2UnCW6lZ2Z1F:-NrlXwiSA8VXba7bcBmk:bbx1gsh) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L28)):*
> ```Python
>     def get_builder_plant_controller_plant(self):
>         builder = DiagramBuilder()
>         plant = builder.AddSystem(MultibodyPlant(1.))
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```Python
1.0
```
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 34 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlY2Nd8atIdI-gVth0:-NrlY2Nd8atIdI-gVth1:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L34)):*
> ```Python
>         models_from_directives = ProcessModelDirectives(directives, parser)
>         plant.Finalize()
>         controller_plant = MultibodyPlant(1.)
> ```

nit



_Suggestion:_
```Python
(1.0)
```

**Review by nepfaff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 4 unresolved discussions, missing label for release notes

___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 63 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlTNhd7BFzi1o5fobl:-Nrlan2REdfv6vHIbi6k:bhkvnql) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I can't figure out what the meaning of "in that plant" is supposed to be here.  Is there some grammatical error maybe?
</blockquote></details>

I can't figure it out either. I re-used the existing documentation without properly scrutinizing it. It seems correct if we simply remove that part. 
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlSDJ-8o-vROzbo5GL:-NrlcHAY85zPrmr1DPhb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Drake's conventional name for a static member function that constructs and connects an instance of its enclosing class is `AddToBuilder`.  We should use that same name here, for consistency.
</blockquote></details>

Done.
___
*[`manipulation/kuka_iiwa/sim_iiwa_driver.h` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlT8MU9OFCyXjonrGE:-NrldR01-9IlRx9Bp9Lw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/manipulation/kuka_iiwa/sim_iiwa_driver.h#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

By convention, the first argument to `AddToBuilder` should always be the `builder` that's being added to.
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc` line 176 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlVwKr3yfirO8_cTza:-NrletXWEYFyBAhLsG12:b-yokk09) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc#L176)):*
I agree based on the docs:
> For consistency, the argument indexing is identical for constructors. Index `1` still refers to the implicit `this` pointer, i.e. the object which is being constructed. Index `0` refers to the return type which is presumed to be `void` when a constructor is viewed like a function.

I changed this.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: 4 unresolved discussions, missing label for release notes (waiting on @nepfaff)

___
*[`bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc` line 176 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21040#-NrlVwKr3yfirO8_cTza:-NrltpeM2flsRO1SATUl:bg7igkv) ([raw file](https://github.com/RobotLocomotion/drake/blob/97bf9cec129c38a6761fb11b2676ddce3603d311/bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc#L176)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

I agree based on the docs:
> For consistency, the argument indexing is identical for constructors. Index `1` still refers to the implicit `this` pointer, i.e. the object which is being constructed. Index `0` refers to the return type which is presumed to be `void` when a constructor is viewed like a function.

I changed this.
</blockquote></details>

:lgtm:

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21040)* status: missing label for release notes (waiting on @nepfaff)

**Pull request merged**
