### PR TITLE
Add .md capability to relnotes.py

### PR DESCRIPTION
**Pull request by ggould-tri**
* .rst remains the default until #14708 lands

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@jwnimmer-tri
template is a minimal port of the rst template.
manually verified that the emitted rst is unchanged for current master.
manually verified that the emitted md renders sanely in jekyll.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVH_Iq_2DWiNGH48Gum:bm14nxx)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14746#-MVHb0sP9Yv-mWf5f0wh:-MVHb0sP9Yv-mWf5f0wi:b-rdob7i) (no related file):*
I think the formatting-language conditionals within the relnotes program are unnecessary complexity.

In the unlikely event that we need rst formatting for the next release, we can temporarily revert this commit on the notes branch to access the old revision of the tool.  At that point, we're already in a hellworld of formatting the notes twice -- we should really either pull the trigger on the website swap, or delay the release, instead of trying to do a release with both formats in flight.

I'd like to see this patch implement a flag-day swap to md formatting, so that the flow of the program remains clear and direct.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVHieGu3-cH-brOkBIR:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[tools/release_engineering/relnotes.py, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14746#-MVHi9W709JMi6jLqRcS:-MVHi9W709JMi6jLqRcT:bvawf2b) ([raw file](https://github.com/robotlocomotion/drake/blob/647c23e61fa7236c13b84d1c6ff9b2c44af79f6e/tools/release_engineering/relnotes.py#L58)):*
> ```Python
> 
> 
> def _format_pr_link(pr_num):
> ```

nit Given that there are only two callers of this helper, and each caller uses a different half of the result tuple, I wonder it if would be clearer for callers if we declare this a two separate functions instead of a tuple-returning one?  (The two functions could still be nearby each other atop the file here to help keep the `_#pr` token in sync.)  Up to you.
___
*[tools/release_engineering/relnotes.py, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14746#-MVHgjmI0U3JL0utVB56:-MVHgjmJ8Xl4dmMrFvp1:b-aq15pk) ([raw file](https://github.com/robotlocomotion/drake/blob/647c23e61fa7236c13b84d1c6ff9b2c44af79f6e/tools/release_engineering/relnotes.py#L238)):*
> ```Python
>     # .. <end issue links>
>     begin = lines.index(_format_comment("<begin issue links>") + "\n")
>     end = lines.index(_format_comment("<end issue links>") + "\n")
> ```

nit For both of these lines, I think the clarity benefit of having the exact needle text shown inline here (as we used to) outweighs the DRY benefit of a helper function (as it stands now).  How about nixing the function and having simple literals here?

**Review by ggould-tri — COMMENTED** [review]
+@SeanCurtis-TRI platform.

+(status: do not merge) waiting on #14708 ; we want to have this ready to go as soon as that lands.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVHltYi6IXm4OP4xh52:bjo8c7t)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
In my estimation, we should not wait to merge this on #14708.  We want to be able to create draft _markdown_ release notes soon for the upcoming release, while the website deployment works in parallel on its own schedule.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVHmbMACQ2oYYGCVLck:b-3p9e6a)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
And the implicit assumption there being that the upcoming release will be in happy markdown land?

:LGTM:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVHoj2I1YD9s7EcAbl3:b3dz6s2)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @ggould-tri)

___
*[tools/release_engineering/relnotes.py, line 55 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14746#-MVHoA5l0UwuYsMWHm3a:-MVHoA5l0UwuYsMWHm3b:b-z51xjk) ([raw file](https://github.com/robotlocomotion/drake/blob/e587002e93b49cc0356c5f530498b2d9e9ac93d8/tools/release_engineering/relnotes.py#L55)):*
> ```Python
>     `_format_ref_pr_link` text must appear later in the file."""
>     return f"[#{pr_num}][_#{pr_num}]"
> ```

nit: This is where the extra line is requested.

**Review by ggould-tri — COMMENTED** [review]
As the release owner I will absolutely run this locally to generate markdown release notes this cycle.
I just don't want to be in a silly situation if 14708 does not land before the release.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVHnUO67u84643pSviv:b-2iepj8)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @ggould-tri, @jwnimmer-tri, and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746)* status: labeled "do not merge"

**Review by ggould-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14746#-:-MVRFzqfCah9EjGTrt58:b-b9fcpn)* status: labeled "do not merge" (waiting on @ggould-tri)

**Pull request merged**
