### PR TITLE
Remove useless allocations in MinDistanceConstraint.

### PR DESCRIPTION
**Pull request by avalenzu**
This PR modifies some truly unfortunate code that I wrote during grad school. Said code allocated dense matrices for the gradients of some intermediate quantities inside the `MinDistanceConstraint::eval()`. Those matrices were diagonal, and one of them was a scalar times the identity matrix. This PR puts the methods that previously allocated these matrices under test and modifies the methods to output a vector or scalar rather than a full matrix.

Here are screenshots of the Callgrind output before and after the change. 

Before  (30847fa67c4eeec253aaf80443a77ea4b638e0e5): ~67% of time spent *outside* of `RBT::collisionDetect()` calls
Before

After (this PR) ~3% of time spent *outside* of `RBT::collisionDetect()` calls
After

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8652)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAZWGo98wGjQFkNa-on:bp61js4)*

**Comment by avalenzu** [comment]
+@sherm1  for platform review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAZZBWA5-feh0jK-y6P:bsmjgg)*

**Comment by sammy-tri** [comment]
:lgtm:  ("use symbolic for lambda" is an interesting approach...)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/rigid_body_constraint.h, line 888 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZ_Qrp-2pYo_lUhNAP:-LAZ_Qrp-2pYo_lUhNAQ:b-ls8c9f) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L888)):*
> ```objc
>                             double* dscaled_distance_ddistance);
>   static void Penalty(const Eigen::VectorXd& dist, Eigen::VectorXd* cost,
>                Eigen::VectorXd* dcost_ddist);
> ```

BTW odd indent (though it was already like that)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAZayW_49s269_FKTzN:b4hmkr2)*

**Comment by avalenzu** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[multibody/rigid_body_constraint.h, line 888 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZ_Qrp-2pYo_lUhNAP:-LAZfGKB80gKUeA2xf_B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L888)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW odd indent (though it was already like that)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652)*

**Comment by sherm1** [comment]
Platform pass: Nice improvement! A few minor issues below, ptal.

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[multibody/rigid_body_constraint.h, line 886 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZfs9S7umt8TbLsbOV:-LAZfs9S7umt8TbLsbOW:b-356frf) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L886)):*
> ```objc
>                             double min_distance,
>                             Eigen::VectorXd* scaled_distance,
>                             double* dscaled_distance_ddistance);
> ```

BTW the above method seems to have grown a new min_distance parameter in the API, in addition to the perform improvement you mentioned in the intro. That needs some documentation and an explanation somewhere.

BTW I am also concerned that min_distance might be misnamed; see comment below. But I can't tell since there's no documentation!

---

*[multibody/rigid_body_constraint.h, line 888 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZg5YV2ggZ8OrBKdv1:-LAZg5YV2ggZ8OrBKdv2:b-9vroz7) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L888)):*
> ```objc
>                             double* dscaled_distance_ddistance);
>   static void Penalty(const Eigen::VectorXd& dist, Eigen::VectorXd* cost,
>                Eigen::VectorXd* dcost_ddist);
> ```

BTW the above two methods are public -- now that you've cleaned them up, please also add some doxygen for them.

---

*[multibody/rigid_body_constraint.cc, line 2040 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZgQfv-eHaNdJbg7bM:-LAZgQfv-eHaNdJbg7bN:b-ogfqdr) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.cc#L2040)):*
> ```cpp
>     // Compute Jacobian of closest distance vector
>     double dscaled_dist_ddist{0};
>     ScaleDistance(dist, 1 / min_distance_, &scaled_dist, &dscaled_dist_ddist);
> ```

The new parameter name is "min_distance" (units of length) but it appears here that you are passing in "1/min_distance" (units of 1/length). What gives?

---

*[multibody/test/rigid_body_constraint_test.cc, line 48 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZhC7wB88xf67O20M1:-LAZhC7xA2j2tgOq7K7M:b-ww6oo7) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/test/rigid_body_constraint_test.cc#L48)):*
> ```cpp
>   //    f(x) = ⎨
>   //           ⎪            0, x ≥ 0
>   //           ⎩
> ```

BTW awesome Unicode bracket!

---

*[multibody/test/rigid_body_constraint_test.cc, line 87 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZo6EZ2jmJh8X_Pf7P:-LAZo6EZ2jmJh8X_Pf7Q:bympgtm) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/test/rigid_body_constraint_test.cc#L87)):*
> ```cpp
>   symbolic::Variable scaling_factor_symbolic{"c"};
>   symbolic::Expression scaled_distance_symbolic{
>       scaling_factor_symbolic * distance_symbolic - 1};
> ```

BTW cool, but seems like overkill here since there is no differentation to do. Consider a simpler numeric evaluation.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAZoO7i4VMHULgWb7FD:b-cdu0ub)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652)*

**Comment by avalenzu** [comment]
Addressed platform review comments. @sherm1, PTAL.

As part of this, I moved the computation that was being done in `ScaleDistance()` into `Penalty()`. I did this because a) it was actually an affine transformation rather than a scaling and b) I only care about the result of the composition of the two operations (affine transformation and smooth hinge-loss). 

I also re-organized the commit history so that the new test is added before most of the changes are made to the code under test. The commit history is curated.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/rigid_body_constraint.h, line 886 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZfs9S7umt8TbLsbOV:-LAnzRI99FOdRa4mJdCn:bnns8n7) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L886)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the above method seems to have grown a new min_distance parameter in the API, in addition to the perform improvement you mentioned in the intro. That needs some documentation and an explanation somewhere.

BTW I am also concerned that min_distance might be misnamed; see comment below. But I can't tell since there's no documentation!
</blockquote></details>

This parameter was exposed so that `ScaleDistance` could be made `static` (previously it was reading a member variable for this value). I have deleted this method, as I never actually cared about it on its own, only when composed with `Penalty()`.

---

*[multibody/rigid_body_constraint.h, line 888 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZg5YV2ggZ8OrBKdv1:-LAnzwi517WZvLyBAFiR:b-app235) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.h#L888)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the above two methods are public -- now that you've cleaned them up, please also add some doxygen for them.
</blockquote></details>

Doxygen added.

---

*[multibody/rigid_body_constraint.cc, line 2040 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZgQfv-eHaNdJbg7bM:-LAo-05I3mtr8GSfIRlU:btahr7n) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/rigid_body_constraint.cc#L2040)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The new parameter name is "min_distance" (units of length) but it appears here that you are passing in "1/min_distance" (units of 1/length). What gives?
</blockquote></details>

In r1 of this PR, the parameter was actually a scaling factor (units of 1/length). The header file had the wrong parameter name. However, in r3 the corresponding parameter of `Penalty()`, `distance_threshold`, is a distance. Hopefully this is clearer with the new documentation in the header. PTAL.

---

*[multibody/test/rigid_body_constraint_test.cc, line 87 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-LAZo6EZ2jmJh8X_Pf7P:-LAo-dGC5fX9P2-tbvau:boujuxi) ([raw file](https://github.com/robotlocomotion/drake/blob/844d131b36e54be73af5ff57e62eeb76d2720144/multibody/test/rigid_body_constraint_test.cc#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW cool, but seems like overkill here since there is no differentation to do. Consider a simpler numeric evaluation.
</blockquote></details>

Moved the scaling/shifting into `Penalty()` and removed this test.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAo0BQiBVXXiDLMV5ZS:bggcu2v)*

**Comment by sherm1** [comment]
Looks great -- platform :lgtm:. However, that's a lot of changes so should get a quick revisit from your feature reviewer @sammy-tri before merging.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8652#-:-LAo7JG12KlBSQz1aU3R:b-f6kuum)*

**Pull request merged**
