### PR TITLE
Support newest versions of MATLAB

### PR DESCRIPTION
**Pull request by jamiesnape**
Also remove patches to `ExternalProject_Add` that are no longer required.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7184)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7184#-:-KvcfruNVoQYFkftUWmG:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7184#-:-KvcgtFeIJtey6LR81c4:bnfp4nl)*

**Pull request merged**
