### PR TITLE
Adds Context<T>::to_string()

### PR DESCRIPTION
**Pull request by RussTedrake**
GIves a very useful lens into where/what states and parameters have been allocated in complex systems (and their current values).

Example:
```
from pydrake.examples.manipulation_station import ManipulationStation

station = ManipulationStation()
station.Finalize()

context = station.CreateDefaultContext()
print(context)
```

Outputs
```
::manipulation_station Context (of a Diagram)
----------------------------------------------------------------
7 total continuous states
26 total discrete states in 3 groups
2 total abstract states
7 total numeric parameters in 1 groups

::manipulation_station::multibody_plant Context
------------------------------------------------------------------
Time: 0
States:
  1 discrete state groups with
     18 states
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


::manipulation_station::scene_graph Context
------------------------------------------------------------------
Time: 0
States:
  1 abstract states


::manipulation_station::iiwa_controller Context (of a Diagram)
----------------------------------------------------------------
7 total continuous states
7 total numeric parameters in 1 groups

::manipulation_station::iiwa_controller::drake/systems/controllers/PidController@0000558d0d2068d8 Context
------------------------------------------------------------------
Time: 0
States:
  7 continuous states
    [0, 0, 0, 0, 0, 0, 0]


::manipulation_station::iiwa_controller::drake/systems/ConstantVectorSource@0000558d0d52db90 Context
------------------------------------------------------------------
Time: 0
Parameters:
  1 numeric parameter groups with
     7 parameters
       [0, 0, 0, 0, 0, 0, 0]

::manipulation_station::desired_state_from_position Context
------------------------------------------------------------------
Time: 0
States:
  1 discrete state groups with
     7 states
       [0, 0, 0, 0, 0, 0, 0]


::manipulation_station::wsg_controller Context
------------------------------------------------------------------
Time: 0
States:
  1 discrete state groups with
     1 states
       [0]


::manipulation_station::dev_scene_graph_for_rendering Context
------------------------------------------------------------------
Time: 0
States:
  1 abstract states
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10072)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Needs a rebase for pydrake formatter changes.

**Pull request merged**
