### PR TITLE
Refined  ModelElementId class description

### PR DESCRIPTION
**Pull request by liangfok**
I clarified the description of what I plan on implementing next.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2976)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this is a tweak of #2919:
+@amcastro-tri for feature review.
+@sherm1 for platform review.
Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-:-KNqbLn4Q0xSZCkf37TA:277897252)*

**Comment by amcastro-tri** [comment]
minor comment. Otherwise :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/model_element_id.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNqrkEnixWRftsq4j3t:-KNqrkEnixWRftsq4j3u:1756623383) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L12)):*
> ```objc
> 
> /**
>  * Identifies a unique modeling element within a `RigidBodySystem`. Modeling
> ```

RBS or RBT? the two are so intertwined right now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-:-KNqrr1I3RS8gOkc8iT6:-1115640921)*

**Comment by liangfok** [comment]
Now waiting on a platform review from @sherm1.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/model_element_id.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNqrkEnixWRftsq4j3t:-KNqyrmSjTFgeTVtxtkD:539392891) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L12)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> RBS or RBT? the two are so intertwined right now!
</details>
It's currently RBS, but I created #2979 to track this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-:-KNqyx6EaAaWiVNl-LFh:1327366501)*

**Comment by sherm1** [comment]
Platform: one question, otherwise :lgtm:.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNrS1YwrMZyNBUmrCMU:-1624621395) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
> ```objc
>  * queries like "find all modeling elements that belong to a particular instance
>  * of a model." Drake guarantees that the union of an `instance_name` and
>  * `element_name` uniquely identifies a particular modeling element within the
> ```

Is this really true? It depends on all element names being in the same "name space" so that a joint or link can never have the same name as an actuator or sensor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-:-KNrSL0Fa4cR0WeCJbI3:-1828905244)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNrcy2pem4BTtso68gm:257819939) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Is this really true? It depends on all element names being in the same "name space" so that a joint or link can never have the same name as an actuator or sensor.
</details>
That's a good point. URDF and SDF do not enforce that modeling elements of different types have different names.

However, Drake _could_ enforce that it be true by throwing an error if somebody attempted to load a URDF or SDF where, for example, a body and joint both have the same name.

I created #2981 to track the generalization of this class to support identically named modeling elements that are distinguished by type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNreB7iIXuKp10Xj6H5:-1911191653) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> That's a good point. URDF and SDF do not enforce that modeling elements of different types have different names.
> 
> However, Drake _could_ enforce that it be true by throwing an error if somebody attempted to load a URDF or SDF where, for example, a body and joint both have the same name.
> 
> I created #2981 to track the generalization of this class to support identically named modeling elements that are distinguished by type.
</details>
Waiting on @sherm1  to ack this before I can merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNryTAiy0vDC1aBJFDy:77683006) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Waiting on @sherm1  to ack this before I can merge.
</details>
Now I'm wondering whether this whole class is ill-conceived. It seems as though it fails to achieve its basic purpose, which as I understand it is to uniquely identify particular elements in a model instance. If it can't reliably do that, why is it a good thing to add to Drake? Perhaps some others who were involved in the original conversation could explain that? (@jwnimmer-tri , @amcastro-tri, ?) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNsAMzY9EstaB2HEBVE:1560833511) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Now I'm wondering whether this whole class is ill-conceived. It seems as though it fails to achieve its basic purpose, which as I understand it is to uniquely identify particular elements in a model instance. If it can't reliably do that, why is it a good thing to add to Drake? Perhaps some others who were involved in the original conversation could explain that? (@jwnimmer-tri , @amcastro-tri, ?) 
</details>
The purpose of this class is to aggregate related variables. We currently have variables like [RigidBody::name_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L238), [RigidBody::model_name_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L241), [RigidBody::model_id_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L241) all as separate member variables of a modeling element. This class simply aggregates them into a single class for organizational purposes.

I can (and will) easily generalize this class to include a `modeling_element_type` value, and will do so as a resolution of #2981.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976)*

**Comment by liangfok** [comment]
*[drake/systems/plants/model_element_id.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2976#-KNrS1YwrMZyNBUmrCMT:-KNtJn6moC9msioTyOPB:-877566906) ([raw file](https://github.com/robotlocomotion/drake/blob/b7e3805c1d60155939ac025dc9f29204164fa4bb/drake/systems/plants/model_element_id.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The purpose of this class is to aggregate related variables. We currently have variables like [RigidBody::name_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L238), [RigidBody::model_name_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L241), [RigidBody::model_id_](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L241) all as separate member variables of a modeling element. This class simply aggregates them into a single class for organizational purposes.
> 
> I can (and will) easily generalize this class to include a `modeling_element_type` value, and will do so as a resolution of #2981.
</details>
This is a friendly ping to @sherm1, @jwnimmer-tri, @amcastro-tri, and @maddog-tri regarding this blocking thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2976)*

**Comment by liangfok** [comment]
I'm closing this PR because we've decided not to use the `ModelElementId` class. Instead, we've decided to rename `model_id` to be `model_instance_id` and to expose it to the application.

**Pull request closed without merging**
