### PR TITLE
Renamed a few more "number_of_foo" local variables to be "num_foo".

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3613)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3613#-:-KSpSeLqsUlyG-ZLdTWF:bcv4nxl)*

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel: this is a waste of time; on no axis of evaluation is this an improvement.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3613#-:-KSqJ0mJnrpAbBr7PNNo:b-qsjkq9)*

**Comment by liangfok** [comment]
How about the "few keystrokes" and "greater nomenclature consistency across code base" axes?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3613#-:-KSqJWj6IdKhRVZZnFqy:by70xm)*

**Comment by jwnimmer-tri** [comment]
(1) Not changing anything (canceling this PR) takes 0 keystrokes.  Can't beat that as a minimum!
(2) This makes the code _more_ inconsistent; the methods being called use "Number" and not "Num".

**Comment by liangfok** [comment]
I would classify the method names as being defective. But OK. I'll close the PR.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3613#-:-KSqKB43ScaiS9zD4TSk:b-h6etlv)*

**Comment by jwnimmer-tri** [comment]
There is no rule that says "Number" is verboten as a name.

**Comment by liangfok** [comment]
You're right. It's not verboten. However, the style guide does say the following [here](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules):

> "num" is a widespread convention.

Thus, I believe the use of "num" should be at the author's discretion.

**Comment by jwnimmer-tri** [comment]
Absolutely.  So when you write code, you can choose.  Repaving existing code inconsistently doesn't heop.

**Comment by liangfok** [comment]
:+1:

**Pull request closed without merging**
