### PR TITLE
Added Missing #include to Drake/ROS car example

### PR DESCRIPTION
**Pull request by liangfok**
This is towards the "include what you use" rule.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2935)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review please.
+@david-german-tri for platform review please.

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2935#-:-KN_P7rZFpqfc16noaja:-1199182518)*

**Comment by jhoare** [comment]
Lets experiment a bit, shall we? 

@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by liangfok** [comment]
I believe the results of the aforementioned tests are being displayed here:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-ros/19/

**Comment by jhoare** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2935#-:-KNbGzn8hGO8mVPx5tRR:1417088721)*

**Comment by liangfok** [comment]
Thanks. Now waiting on @david-german-tri  for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2935#-:-KNbHf4SvdI14J7H7P3C:1611779193)*

**Comment by david-german-tri** [comment]
:lgtm:, will override merge because CI failure is obviously unrelated

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2935#-:-KNbOmflD3WRdMJMdEjU:1371987731)*

**Pull request merged**
