### PR TITLE
Deprecate math::saturate which is identical to std::clamp

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Prefer C++17 `clamp` over a pair of `min`,`max`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Generally, I'm fine with this. `std::clamp` certainly hews to the spirit of the `min(max(...))` shenanigans.

Generally, the two formulations are only equivalent under a subdomain of possible values for `x`, `lo`, and `hi`.  Specifically, where `lo <= hi`. At some call sites, this condition is guaranteed, even if indirectly (e.g., `bspline_trajectory.h` gets its clamping range from `BsplineBasis` which does its own guarantees about its interval). In other cases, the guarantees are more remote. For example, `PathParameterizedTrajectory` simply relies on a `Trajectory` of time scaling  which seems to provide no guarantees about time running forwards. So, there's the potential for a behavior change.

Specifically, consider the following:

```
    0       hi            1         lo        2
<------------|----------------------|----------------->


 X in region  |  min(max(x, lo), hi) | clamp(x, lo, hi)
 ------------ | -------------------- | ----------------
      0       |          hi          |         x
      1       |          hi          |         x
      2       |          hi          |         hi
```

In the weird case where `hi < lo`, the min-max spelling always returns `hi`. But clamp doesn't.

So, how confident are we that the *context* in which we're making these changes precludes the `hi < lo` case?

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCLWevqEWN8QLuvLesj:b-1szbi)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> In other cases, the guarantees are more remote. For example, PathParameterizedTrajectory simply relies on a Trajectory of time scaling which seems to provide no guarantees about time running forwards.

It doesn't matter whether or not the first argument to clamp (`v`) is monotonic.  As long as `lo <= hi` we're fine, and in this case lo and hi are constants (the start and end times), not varying.

So, I don't understand your concern?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Now *I'm* confused.

I'm talking about [this code](https://github.com/RobotLocomotion/drake/blob/master/common/trajectories/path_parameterized_trajectory.cc#L29-L30):

```c++
  const T time =
      clamp(t, time_scaling_->start_time(), time_scaling_->end_time());
```

Here, lo and hi aren't constants. They are drawn from a `Trajectory` which has those methods completely virtual. So, in this context, there doesn't seem to be guarantees at all about `time_scaling_->start_time() <= time_scaling_->end_time()`.  So, if *this* class has been used with a time scaling trajectory for which `end_time() > start_time()`, then changing to `clamp()` will change the behavior of that particular invocation.

However, my mentioning `PathParameterizedTrajectory` was merely intended as an example. This PR changes the `min(max())` spelling in a number of places. I didn't go spelunking into all of them to investigate the guarantees. I looked at the first two which were sufficient for me to feel like the topic was worth broaching.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCLeh2u8Z5J28hNcoSf:btxkwfo)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
BTW note that [std::clamp](https://en.cppreference.com/w/cpp/algorithm/clamp)'s behavior when hi < lo is explicitly undefined. Also, the documentation says "... if NaN is avoided, T can be a floating-point type." which implies (but doesn't say explicitly) UB for NaNs. From the given "possible implementation" we can infer behavior in the hi < lo & NaN cases, but actual implementations would be free to do some other bizarre things.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCLxoEs4BmjZiDPFFqe:b3gm37q)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
An excellent point. Nevertheless, we've gone from "defined behavior" to "undefined behavior".

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCM6UOS0aF-NCCJMzqj:b739ykr)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/symbolic/expression/test/expression_test.cc` line 1748 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17942#-NCM6h8oB9pZ0XOotdGV:-NCM6h8oB9pZ0XOotdGW:b9ucr9g) ([raw file](https://github.com/robotlocomotion/drake/blob/1f267b6ad7848616ec0f97886271f26efca85096/common/symbolic/expression/test/expression_test.cc#L1748)):*
> ```cpp
>   EXPECT_EQ(e.Evaluate({{var_x_, 12.3}, {var_lo, 3}, {var_hi, 10}}), 10);
> 
>   // The contract of std::clamp is very particular. When we have the absurd
> ```

BTW This is the comment that led me down my rabbit hole. But, as @sherm1 points out, cppreference suggests that this situation leads to undefined behavior. Should that be under test?

**Review by jwnimmer-tri — COMMENTED** [review]
> ... there doesn't seem to be guarantees at all about time_scaling_->start_time() <= time_scaling_->end_time().

If someone makes a trajectory like that, they can keep the pieces; they are doing something insane.  When I said "constant" I meant that the start and end times are not time-varying (like the path-parameterized trajectory's time). Everything else in Drake will crash on a trajectory with end < start.  Yes, the Trajectory documentation should explain that invariant, but _shrug_.

> note that std::clamp's behavior when hi < lo is explicitly undefined

Huh.  Somehow I missed that when reading the page!  I read the (1) and (2) but not the little sentence tucked underneath them.

I checked both of our two standard libraries -- each one has a (libstdcxx-debug-mode-only) assertion that `!(hi < lo)` and uses the same pseudo-code as the "possible implementation" from cppreference.

I will try to update symbolic::Expression to better capture those semantics (where hi < lo is an error).

> Nevertheless, we've gone from "defined behavior" to "undefined behavior".

No.  The `(lo <= hi)` was already a precondition of math::saturate.  Violating it _does_ lead to an ill-behaved program, but not UB in the sense of nasal demons.  The same is still true after this change.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCM0PZfDz0gcrAlve6e:b-by2pak)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/symbolic/expression/test/expression_test.cc` line 1748 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17942#-NCM6h8oB9pZ0XOotdGV:-NCM8Q__1Ad91vuo2qTP:ba4ht1g) ([raw file](https://github.com/robotlocomotion/drake/blob/1f267b6ad7848616ec0f97886271f26efca85096/common/symbolic/expression/test/expression_test.cc#L1748)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This is the comment that led me down my rabbit hole. But, as @sherm1 points out, cppreference suggests that this situation leads to undefined behavior. Should that be under test?
</blockquote></details>

Working

Yes, this comment is incorrect.  I'll see what I can do.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> No. The (lo <= hi) was already a precondition of math::saturate.

My apologies, I wasn't clear. I didn't mean vis a vis `math::saturate`, I meant relative to `min(max(...))`. 

But if the basic assumption is that those call sites that have been swapped from `min(max())` to `clamp` have a (minimally implicit) contract that people won't do that unless they look to reap the apocalypse, then I'm fine.  I just wanted to make sure that it had been explicitly considered.

> Somehow I missed that when reading the page! I read the (1) and (2) but not the little sentence tucked underneath them.

I had done the *exact same thing*.  :-/

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCMJhogBM2hOCqqW1NM:bpshztu)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Yes, I think the Trajectories are fine to assume start <= end.

+@sherm1 for platform review please, since you're already spun up and I'm on call.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCMyIR1DpPDsOn5wVOX:b-f8hmfi)* status: LGTM missing from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`common/symbolic/expression/test/expression_test.cc` line 1748 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17942#-NCM6h8oB9pZ0XOotdGV:-NCMyS8f6CqtuWIVkoYX:b-pgvudg) ([raw file](https://github.com/robotlocomotion/drake/blob/1f267b6ad7848616ec0f97886271f26efca85096/common/symbolic/expression/test/expression_test.cc#L1748)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Yes, this comment is incorrect.  I'll see what I can do.
</blockquote></details>

Done.  Best to just not violate the precondition, rather than try to test it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCQ0t5zD40Mzu1_hWRU:bmxilld)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 11 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942#-:-NCRzn1GCfqE8piqgUUc:b8qx53o)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/symbolic/expression/expression.cc` line 734 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17942#-NCRzCQA7I7fK_B-PNL2:-NCRzCQA7I7fK_B-PNL3:b-9z8bck) ([raw file](https://github.com/robotlocomotion/drake/blob/7763bb011bbb779713bf99b9274f2088eba46afa/common/symbolic/expression/expression.cc#L734)):*
> ```cpp
> Expression clamp(const Expression& v, const Expression& lo,
>                  const Expression& hi) {
>   return min(hi, max(lo, v));
> ```

BTW from your description of the library implementations, it would be more consistent if this clamp() implementation has a lo <= hi precondition. In case lo & hi are constants that could be enforced here also.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[`common/symbolic/expression/expression.cc` line 734 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17942#-NCRzCQA7I7fK_B-PNL2:-NCS18KT60OiAvhnapl8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7763bb011bbb779713bf99b9274f2088eba46afa/common/symbolic/expression/expression.cc#L734)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW from your description of the library implementations, it would be more consistent if this clamp() implementation has a lo <= hi precondition. In case lo & hi are constants that could be enforced here also.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17942)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
