### PR TITLE
[doc] Add required "feature or fix" release notes tagging

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/reviewable.md` line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17345#-N3yaCa47pPPc0_vlpoi:-N3ydaGt7Ut4TtofqR9M:byn1uu4) ([raw file](https://github.com/robotlocomotion/drake/blob/c9f4ba87b9266ade08e372364d30587c03e48b8f/doc/_pages/reviewable.md#L113)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  This language ("primarily") discourages but does not explicitly forbid applying both tags.  I think that's the correct tone, but wanted to be sure that matches your intention and/or the intended capabilities of the script.
</blockquote></details>

My intent is that _at most one_ of (feature, fix, none) is marked.  We only want to place the release note in _one_ place within the subject matter area.  I'll work on clarifying the wording.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @ggould-tri and @rpoyner-tri)

___
*[`doc/_pages/reviewable.md` line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17345#-N3yaCa47pPPc0_vlpoi:-N3z-G4I7NvwcBG3egFZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9f4ba87b9266ade08e372364d30587c03e48b8f/doc/_pages/reviewable.md#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My intent is that _at most one_ of (feature, fix, none) is marked.  We only want to place the release note in _one_ place within the subject matter area.  I'll work on clarifying the wording.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N3z1Wvu7M6pr6p6KT_K:bnfp4nl)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
All platform reviewers +@EricCousineau-TRI +@sammy-tri +@sherm1 +@xuchenhan-tri +@RussTedrake +@SeanCurtis-TRI for for review of policy change, please.  I'll leave this open until June 14th for your comments.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N3z5uj5DpF2S1c0nwyN:bpqxd5f)* status: LGTM missing from assignees sammy-tri(platform),SeanCurtis-TRI,sherm1(platform),RussTedrake(platform),xuchenhan-tri(platform) (waiting on @RussTedrake, @sammy-tri, @SeanCurtis-TRI, @sherm1, and @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N3zQl0jEJ_eWdW-onpy:bmxilld)* status: LGTM missing from assignees sammy-tri(platform),sherm1(platform),RussTedrake(platform) (waiting on @RussTedrake, @sammy-tri, and @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N3zZKCS7g4FHAn8H4MD:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),RussTedrake(platform) (waiting on @RussTedrake and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N42ZdcAEB-dTMF4IQZE:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[`doc/_pages/reviewable.md` line 108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17345#-N42ZJW74McHqIjR8vFy:-N42ZJW74McHqIjR8vFz:bmaxt5b) ([raw file](https://github.com/robotlocomotion/drake/blob/1f071a621bc4545f393d0f2668eca8eed538999c/doc/_pages/reviewable.md#L108)):*
> ```Markdown
> 
> **release notes: feature**<br/>
> &nbsp;and<br/>
> ```

nit: seems like it would be better to use "OR" here instead of "and"?  I think it follows both from the logic of the cases and from the context for this subsection.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17345#-:-N44GKdr51-9QdB9JHl1:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform),sammy-tri(platform),SeanCurtis-TRI,EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
