### PR TITLE
Added dependency list to build targets carSimLCM and publishDrivingCommand

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2139

@rpoyner-tri, can you feature review this please?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2141)

### CODE REVIEW

**Comment by liangfok** [comment]
@david-german-tri: what is the best practice here regarding whether I should update this PR with the latest on master and trigger another round of CI? Note that [CI Build #968](https://drake-jenkins.csail.mit.edu/job/experimental/968/) passed.

**Comment by jamiesnape** [comment]
You should not need to retest. There is no plausible way the intervening merge could affect this (or practically anything). Jenkins is busy, so best to save resources.

**Comment by liangfok** [comment]
@jwnimmer-tri, this was reviewed by @billhoffman. Would appreciate if you could override the out-of-date-with-base-branch issue and merge.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2141#-:-KFuu1ObBl26o-uUAF14:1417088721)*

**Comment by jwnimmer-tri** [comment]
Jenkins green, Reviewable green, drake005 is still in-progress.  Going to override-merge to get around out-of-date branch.

**Comment by jwnimmer-tri** [comment]
I'm glad to have the dependencies fixed.  In the medium term, I'd love the required incantations for CMakeLists to be less error-prone, but I'll take a incrementally-more-correct build any day of the week.

**Pull request merged**
