### PR TITLE
[examples] Add a deformable simulation example

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NErJi5O3K9ldiRXPaRx:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the review and tips on damping. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NFAH9rw3rQ_cktlM1DP:bemb5nh)* status: 6 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @DamrongGuoy)

___
*[`examples/multibody/deformable_box/box.vtk` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9XDckBeBOxlc2yVEd:-NFADQTfDrdz_sUAVt-D:b-m8q7ia) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/box.vtk#L2)):*
> I thought we had methods to create these meshes?

We don't have it for boxes just yet. Right now the only supported primitive shape is sphere. I think @damrongguoy has plans to enrich the set of supported shapes.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9Yceu5MUOP-ihO_OB:-NFAECDw7Y3u3YPK63-e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L106)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, consider another symbol instead of T, given we use it so much for our scalar types.
</blockquote></details>

Done.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 137 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9eidW2064-ZY1IJZS:-NFAED6q5mlNIj1ZiUcF:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L137)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

people usually like their PD controllers close to critically damped (even a bit underdamped for faster response, but I won't get picky). Here, for our 1 kg gripper, that'd be with `kd=2*sqrt(mass*kp)` which is more or less 125. With `kd=150` the oscillations on the gripper are nicely damped. 
</blockquote></details>

Done, thanks.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 153 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9ZUJl5TDL73yq9x9d:-NFAFbsCEFIE34-bYq3Z:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L153)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, given the pedagogic value of this example, explain that for interaction with deformable bodies even rigid bodies must be discretized.
</blockquote></details>

Done, thanks.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 155 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9ZAcg2aV_zdq-1oK-:-NFAEG121efqkhIAxY5C:b8w8ova) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L155)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

usually 1.5 is a **very** large value of friction. Consider explaining why this choice (e.g. maybe because it's a rubber box against a rubber gripper and you expect large friction between those two surfaces)
</blockquote></details>

I changed it to a smaller value and added some explanation.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9_4JA7KaEaMgvL4Zv:-NFAEyFD6K6Dj8q8Nx_a:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L200)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you explain here why the need of this 20% factor? why not to create a mesh with a size of 7.2 cm sides?
</blockquote></details>

Done, thanks.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9_K2f3WTBv5nOtfLF:-NFAEqG181goa0Ts5yqK:b-vgztgw) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L222)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

can this be NAN if not used?
</blockquote></details>

Unfortunately it can't at the moment. Added a TODO.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 225 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9_UpdC6TmU_DtuG9P:-NFAAVXaCugfncMEKWvc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L225)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, my preference is to use `owned_deformable_mode` for the (temporary in scope) unique pointer and `deformable_model` for the raw pointer that persists in the scope to keep using it.
</blockquote></details>

Done.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9eCUy-yOotGQFOPlK:-NFAAAG0-1C_kEXquTvU:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L232)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

These fingers are very light and thefore the PD controller is borderline unstable, as revealed by the oscillations.
In reality these fingers have a pretty hefty gear box and therefore modeling dissipation and reflected inertia will help with that.
Here I did:
```c++
PrismaticJoint<double>& left_slider =
      plant.GetMutableJointByName<PrismaticJoint>("left_slider");
left_slider.set_default_damping(50.0);
```
and same for right finger, and the problem is gone.

</blockquote></details>

Done, thanks!
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9_zDZ82bpfKZTuHdN:-NFAH6pA8b7leBGuJRB-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/deformable_box.cc#L286)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, consider expanding on this message to explain bare mininum things like:
 1. what the example is about
 2. mention that you'd want meldis running in the background
 3. Minimum set of options
 4. Point to README.md for more info and in particular to run meldis

</blockquote></details>

Done.
___
*[`examples/multibody/deformable_box/README.md` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9UmYB44GTetnSeu4_:-NFA9lJP1x_c5Anz2vko:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/README.md#L3)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, consider "simulation of deformable bodies", even though in informal speech we often say "deformables' simulation"
</blockquote></details>

Done, thanks.
___
*[`examples/multibody/deformable_box/README.md` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9V48h4y6Z70K0MKB0:-NFA9eHA1vesCFSivj5B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/README.md#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, "dynamics of **a** doformable body" or "dynamics of deformable bodies"
</blockquote></details>

Done.
___
*[`examples/multibody/deformable_box/README.md` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9VOhD7ARkwPeNlXUe:-NFA9aYE-4-I1Uav5kj7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/README.md#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, consider "set" or "adjust" instead of "tune", that feels more like a trick, IMO.
</blockquote></details>

Done.
___
*[`examples/simple_gripper/simple_gripper.sdf` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9aQ339JswamVXNS8V:-NFACqcY4enOpORCRuPn:bb2le2w) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/simple_gripper/simple_gripper.sdf#L3)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, consider updating visuals to have other colors. For this example everything looks grey and it's even confusing to tell what is what (specially the first time you run it)
</blockquote></details>

Done. I turned it into a much darker grey. IMO, it also makes the "simple_gripper" example look a lot nicer.

**Review by amcastro-tri — COMMENTED** [review]
So good! :lgtm_strong: 

+@ggould-tri for platform review please.

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NFAZvsv7VQIviNmb_B0:b6csros)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[`examples/multibody/deformable_box/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAZqAR6CzQCGxgyAyf:-NFAZqAR6CzQCGxgyAyg:b1rgfy3) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/BUILD.bazel#L7)):*
> ```Starlark
>     "drake_cc_binary",
>     "drake_cc_googletest",
>     "drake_cc_library",
> ```

do we need `drake_cc_library` and `drake_cc_google_test`?
___
*[`examples/multibody/deformable_box/BUILD.bazel` line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAZndy73gFCWTR4xii:-NFAZndy73gFCWTR4xij:b-5t30i2) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/BUILD.bazel#L28)):*
> ```Starlark
>         "//systems/framework:diagram",
>         "//systems/primitives:adder",
>         "//systems/primitives:constant_vector_source",
> ```

nit, primitives not used
___
*[`examples/multibody/deformable_box/box.vtk` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9XDckBeBOxlc2yVEd:-NFAY8yG-9sb0xrd5_wZ:b96camy) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/box.vtk#L2)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> I thought we had methods to create these meshes?

We don't have it for boxes just yet. Right now the only supported primitive shape is sphere. I think @damrongguoy has plans to enrich the set of supported shapes.
</blockquote></details>

ah, I see. If we will load a vtk for this example (which I think is a great idea since that's what most users will want to do anyway), then consider having a more clomplex object to show off the capability: arbitrary geometries, non-convex.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAYddFC-YnJm-pGTlm:-NFAYddFC-YnJm-pGTln:b-whs5vy) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/deformable_box.cc#L153)):*
> ```cpp
>    deformable bodies.
>    1. A valid Coulomb friction coefficient, and
>    2. A resolution hint (because similar to hydroelastics, rigid bodies need to
> ```

minor, that might be missleading. Consider simply "Rigid bodies need to be tesselated so that..."



_Code quote:_
```cpp
 similar to hydroelastics,
```
___
*[`examples/simple_gripper/simple_gripper.sdf` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9aQ339JswamVXNS8V:-NFAZbDI7j69vWg4cq6O:bnq95dc) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/simple_gripper/simple_gripper.sdf#L3)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done. I turned it into a much darker grey. IMO, it also makes the "simple_gripper" example look a lot nicer.
</blockquote></details>

excellent!

**Review by ggould-tri — COMMENTED** [review]
It is too late in the day for me to plausibly finish an 800 line review.  @rpoyner-tri , can you take this one for tomorrow?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NFA_JRJ6vTz9VpafI1I:b-bw8qbv)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
+(priority: low)

**Review by xuchenhan-tri — COMMENTED** [review]
-@ggould-tri +@rpoyner-tri for platform review per rotation please. (More than half of the LOC is a new data file, so it's not as intimidating as it may seem.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NFBaGnOB6eMCgg8HhEW:b8e94e1)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`examples/multibody/deformable_box/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAZqAR6CzQCGxgyAyf:-NFB_ORMBzeL1VBT6unk:b-r7x8pj) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/BUILD.bazel#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we need `drake_cc_library` and `drake_cc_google_test`?
</blockquote></details>

Done, removed.
___
*[`examples/multibody/deformable_box/BUILD.bazel` line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAZndy73gFCWTR4xii:-NFB_QC329YB6bPbZVpb:b-r7x8pj) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/BUILD.bazel#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, primitives not used
</blockquote></details>

Done, removed.
___
*[`examples/multibody/deformable_box/box.vtk` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NF9XDckBeBOxlc2yVEd:-NFB_m503J1z1dOXkf82:b-dykajr) ([raw file](https://github.com/robotlocomotion/drake/blob/9ced63903a6722f3638b0bc6913e209d57f41242/examples/multibody/deformable_box/box.vtk#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ah, I see. If we will load a vtk for this example (which I think is a great idea since that's what most users will want to do anyway), then consider having a more clomplex object to show off the capability: arbitrary geometries, non-convex.
</blockquote></details>

I added a TODO in the .cc file
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFAYddFC-YnJm-pGTlm:-NFBa-Ew9k6EyrPHFbRy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adc3c61e32034df521237c9c2e53dff1e54299e7/examples/multibody/deformable_box/deformable_box.cc#L153)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, that might be missleading. Consider simply "Rigid bodies need to be tesselated so that..."
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139#-:-NFEyCYK0_dlJAXCJ_ui:bnfp4nl)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`examples/multibody/deformable_box/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEwnmvALmzIUKi-Yh8:-NFEwnmvALmzIUKi-Yh9:b-hft15e) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/BUILD.bazel#L9)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> drake_cc_binary(
> ```

There is no test as yet to keep this from bitrot. Consider adding `add_test_rule = 1,` to the binary build rule.

Probably a good idea to add `test_rule_args = ["-realtime_rate=0.0"],`, to let the simulation in the test run at full speed. It may also make sense to limit the simulation time, to minimize the (surprisingly large) risk of timeouts in CI. If you search the examples/ tree for `test_rule_args`, you will find other programs that use this test technique.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEqbQ-BHWWFMJHb-J4:-NFEqbQ-BHWWFMJHb-J5:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L28)):*
> ```cpp
> DEFINE_double(density, 1e3, "Mass density of the deformable body [kg/m³].");
> DEFINE_double(beta, 0.005,
>               "Stiffness damping coeffcient for the deformable body [1/s].");
> ```

typo



_Suggestion:_
```cpp
coefficient
```
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 150 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEqxaj23iUV4oDNec_:-NFEqxaj23iUV4oDNeca:bnawv01) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L150)):*
> ```cpp
>   auto [plant, scene_graph] = AddMultibodyPlant(plant_config, &builder);
> 
>   /* Minimumly required proximity properties for rigid bodies to interact with
> ```

Not a word. Pehaps "minimum", "minimally"?



_Suggestion:_
```cpp
Minimally
```
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 156 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFErFNh77G9V0ivuE5t:-NFErFNh77G9V0ivuE5u:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L156)):*
> ```cpp
>    queries can be performed against deformable geometries.) */
>   ProximityProperties rigid_proximity_props;
>   /* Set the friction coeffcient close to that of rubber against rubber. */
> ```

typo



_Suggestion:_
```cpp
coefficient
```
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 227 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFErixB1czM8P7_GCmV:-NFErixB1czM8P7_GCmW:b5yoc7y) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L227)):*
> ```cpp
>    hint parameter that dictates how the shape is tesselated. In the case of a
>    `Mesh` shape, the resolution hint is unused because the shape is already
>    tesellated. */
> ```

typo.

TIL either "tesselate" or "tessellate" are OK. Having only one 's' is not.

Consider standardizing on one spelling for the file, at least. The two-'l' form wins googlefight by a large margin.



_Suggestion:_
```cpp
tessellated
```
___
*[`examples/simple_gripper/simple_gripper.sdf` line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEt0D0180VCywYqMU_:-NFEt0D0180VCywYqMUa:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/simple_gripper/simple_gripper.sdf#L3)):*
> ```
> <?xml version="1.0"?>
> <sdf version="1.7">
>

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: 7 unresolved discussions (waiting on @amcastro-tri, @rpoyner-tri, and @xuchenhan-tri)

___
*[`examples/multibody/deformable_box/deformable_box.cc` line 235 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFGy8sD3xel05THWH1J:-NFGy8sD3xel05THWH1K:b-ppqls6) ([raw file](https://github.com/robotlocomotion/drake/blob/75941ddea13b7c854682baebdfb4b76bd59c98f0/examples/multibody/deformable_box/deformable_box.cc#L235)):*
> ```cpp
>   const DeformableModel<double>* deformable_model =
>       owned_deformable_model.get();
>   plant.AddPhysicalModel(std::move(owned_deformable_model));
> ```

I'm curious. Is this the only block without Python binding?



_Code quote:_
```cpp
  const double unused_resolution_hint = 1.0;
  owned_deformable_model->RegisterDeformableBody(
      std::move(box_instance), deformable_config, unused_resolution_hint);
  const DeformableModel<double>* deformable_model =
      owned_deformable_model.get();
  plant.AddPhysicalModel(std::move(owned_deformable_model));
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: 1 unresolved discussion (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`examples/multibody/deformable_box/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEwnmvALmzIUKi-Yh8:-NFGa7Re8jtKnvPwVoaS:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/BUILD.bazel#L9)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

There is no test as yet to keep this from bitrot. Consider adding `add_test_rule = 1,` to the binary build rule.

Probably a good idea to add `test_rule_args = ["-realtime_rate=0.0"],`, to let the simulation in the test run at full speed. It may also make sense to limit the simulation time, to minimize the (surprisingly large) risk of timeouts in CI. If you search the examples/ tree for `test_rule_args`, you will find other programs that use this test technique.
</blockquote></details>

Done, thanks!
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 150 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEqxaj23iUV4oDNec_:-NFGaHKO-OK1wd2_vMd0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L150)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Not a word. Pehaps "minimum", "minimally"?
</blockquote></details>

Done.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 227 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFErixB1czM8P7_GCmV:-NFGaSYpE9MLrn4Hu-_w:ba4di8c) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/deformable_box.cc#L227)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo.

TIL either "tesselate" or "tessellate" are OK. Having only one 's' is not.

Consider standardizing on one spelling for the file, at least. The two-'l' form wins googlefight by a large margin.
</blockquote></details>

Done thanks.
___
*[`examples/multibody/deformable_box/deformable_box.cc` line 235 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFGy8sD3xel05THWH1J:-NFJtDIr71IKku4rjEup:b-tlr4l9) ([raw file](https://github.com/robotlocomotion/drake/blob/75941ddea13b7c854682baebdfb4b76bd59c98f0/examples/multibody/deformable_box/deformable_box.cc#L235)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm curious. Is this the only block without Python binding?
</blockquote></details>

No, anything related to deformable is not Python bound.

Particular to this example, `DeformableBodyConfig` and `DeformableModel` are not bound.
___
*[`examples/simple_gripper/simple_gripper.sdf` line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEt0D0180VCywYqMU_:-NFGaWDL8nQHT0bnIykA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/simple_gripper/simple_gripper.sdf#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18139)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[`examples/multibody/deformable_box/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18139#-NFEwnmvALmzIUKi-Yh8:-NFLRpsq6g7B2EYhj7bf:bse1iur) ([raw file](https://github.com/robotlocomotion/drake/blob/7f6088b18783d470dd8a11bd698b9fa80c718c20/examples/multibody/deformable_box/BUILD.bazel#L9)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done, thanks!
</blockquote></details>

Actually caught a bug, thanks!

**Pull request merged**
