### PR TITLE
Introduce a prerequisites installer for Xenial.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@jamiesnape, +@BetsyMcPhail for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3322)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Once this is in, we should set up a nightly Drake build with a 16.04 AMI that is as close to clean as possible, and have it run this script before the superbuild.

**Comment by jamiesnape** [comment]
Probably not a good option to run a clean image. Many of the dependencies are needed by Jenkins or to run the CTest script and we have MATLAB and commercial solvers to support.

**Comment by jamiesnape** [comment]
In the very early days of Drake we did this and it was forever breaking the JVM.

**Comment by david-german-tri** [comment]
> Probably not a good option to run a clean image. Many of the dependencies are needed by AWS, Jenkins or to run the CTest script and we have MATLAB and commercial solvers to support.

Yes - this is the kind of stuff I meant to exclude from "as close to clean as possible".

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_z5XFyn8fczpnLJRx:-KQ_z5XFyn8fczpnLJRy:b-5icsqx) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L20)):*
> ```Shell
> # TODO(david-german-tri): Reorganize these by the external that requires them.
> 
> SCM_TOOLS=(git subversion)
> ```

Do we still need subversion?

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-HQjmadIsxBP1XMB:-KQa-HQjmadIsxBP1XMC:b-k7xqq8) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L24)):*
> ```Shell
> DRAKE_BUILD_TOOLS=(cmake cmake-curses-gui ninja-build make pkg-config)
> EXTERNAL_BUILD_TOOLS=(autoconf automake libtool swig unzip)
> EXTERNAL_COMPILERS=(g++-5-multilib gfortran)
> ```

gfortran-5 to be consistent 

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-r6BMBt9whaUhs-Q:-KQa-r6BMBt9whaUhs-R:b-3h4hv9) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L25)):*
> ```Shell
> EXTERNAL_BUILD_TOOLS=(autoconf automake libtool swig unzip)
> EXTERNAL_COMPILERS=(g++-5-multilib gfortran)
> PERL_DEPS=(perl libhtml-form-perl libwww-perl libterm-readkey-perl)
> ```

Do we still need perl? It was there for MATLAB previously, but that is all cmake code.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-mELM1_c5MS9dYOn:-KQa-mELM1_c5MS9dYOo:brui05y) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L26)):*
> ```Shell
> EXTERNAL_COMPILERS=(g++-5-multilib gfortran)
> PERL_DEPS=(perl libhtml-form-perl libwww-perl libterm-readkey-perl)
> VTK_DEPS=(libvtk-java libvtk5-dev libvtk5-qt4-dev)
> ```

Is libvtk-java required?

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-4bhMS0yIhz9_aEB:-KQa-4bhMS0yIhz9_aEC:bvfhoyr) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L29)):*
> ```Shell
> QT_DEPS=(libqt4-dev libqt4-opengl-dev libqwt-dev)
> DOCS_DEPS=(doxygen graphviz)
> PYTHON_DEPS=(python python-bs4 python-dev python-gtk2 python-html5lib python-numpy python-sphinx python-vtk)
> ```

python is not needed, just python-dev.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_zaK90k6KVY8EuBfY:-KQ_zaK90k6KVY8EuBfZ:b-5krrur) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L30)):*
> ```Shell
> DOCS_DEPS=(doxygen graphviz)
> PYTHON_DEPS=(python python-bs4 python-dev python-gtk2 python-html5lib python-numpy python-sphinx python-vtk)
> MISC_DEPS=(libgtk2.0-dev libmpfr-dev libpng12-dev bison flex)
> ```

bison and flex should be in EXTERNAL_BUILD_TOOLS

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 33 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_ziYe2jXffJR8F1UV:-KQ_ziYe2jXffJR8F1UW:bmxombd) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L33)):*
> ```Shell
> DEBUG_TOOLS=(valgrind gdb)
> 
> apt install --assume-yes \
> ```

Install with --no-install-recommends. If that means you are missing a tool, it should be added explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa1iGI42nmhtgSchgq:-KQa1iGI42nmhtgSchgr:b-j67mn2) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L21)):*
> ```Shell
> 
> SCM_TOOLS=(git subversion)
> COMPILERS=(g++-5 clang default-jdk)
> ```

DRAKE_COMPILERS?

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa1HZT6PxLkSsx0uXN:-KQa1HZT6PxLkSsx0uXO:b-cc62rm) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L29)):*
> ```Shell
> QT_DEPS=(libqt4-dev libqt4-opengl-dev libqwt-dev)
> DOCS_DEPS=(doxygen graphviz)
> PYTHON_DEPS=(python python-bs4 python-dev python-gtk2 python-html5lib python-numpy python-sphinx python-vtk)
> ```

python-sphinx is strictly a documentation dependency.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-4bhMS0yIhz9_aEB:-KQa1pkVupFeB5jvRc5Y:bwws4b4) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> python is not needed, just python-dev.
</details>
And I would put python-vtk in with VTK dependencies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri For this similar thing on other projects, I've found that grouping dependency lists into buckets leads to endless confusion ("into which bucket should the new thing go?") and bikeshedding ("this other way makes more sense to me").  Is there a reason why a single alpha-list of dependencies would be inferior to the semantic grouping proposed here?

**Comment by jamiesnape** [comment]
Personally, I would just split between runtime and dev dependencies.

**Comment by david-german-tri** [comment]
Done.

---

Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_z5XFyn8fczpnLJRx:-KQaAySj50r4Rn-20r19:b-7yd1q4) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L20)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Do we still need subversion?
</details>
Added a TODO.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa1iGI42nmhtgSchgq:-KQaAxo3uv40ItwE9hru:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> DRAKE_COMPILERS?
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-HQjmadIsxBP1XMB:-KQaJoSsVRJ2AXMfuVKz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> gfortran-5 to be consistent 
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-r6BMBt9whaUhs-Q:-KQaB8yJuWcsynBbib9g:bed4i9n) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Do we still need perl? It was there for MATLAB previously, but that is all cmake code.
</details>
I hit a PCRE-related failure before adding it.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-mELM1_c5MS9dYOn:-KQaLDUE_j8_uzBZXRXJ:b-7yd1q4) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L26)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Is libvtk-java required?
</details>
Added a TODO.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa-4bhMS0yIhz9_aEB:-KQaBFPkq99gwXzWMXED:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> And I would put python-vtk in with VTK dependencies.
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQa1HZT6PxLkSsx0uXN:-KQaBInLxv56HiQbzt1T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> python-sphinx is strictly a documentation dependency.
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_zaK90k6KVY8EuBfY:-KQaBKaw2TNQZdYZJBFd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L30)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> bison and flex should be in EXTERNAL_BUILD_TOOLS
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 33 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQ_ziYe2jXffJR8F1UV:-KQaBNGcsjwKLC3LXNSP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32ef65e3ff206b444df4c2f7184f54e9bab6c3b0/setup/ubuntu/16.04/install_prereqs.sh#L33)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Install with --no-install-recommends. If that means you are missing a tool, it should be added explicitly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-:-KQaLGAnBeihJBD1qpeb:b-896fix)*

**Comment by jamiesnape** [comment]
:lgtm: 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-:-KQaepvQFVytxg15qf-Q:bg7igkv)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-:-KQagjWuxXO0njWdMrmK:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu_trusty.rst, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQajT77MkTBA6dn-o3x:-KQajT77MkTBA6dn-o3y:b7ib98z) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/drake/doc/ubuntu_trusty.rst#L5)):*
> ```reStructuredText
> *************************
> 
> The following instructions are written for the officially supported version of
> ```

BTW Supported by whom?  Consider `written for Drake's supported version` or similar.

---

*[drake/doc/ubuntu_xenial.rst, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQajyYMPE4FB-5SLEmI:-KQajyYNFWCoduiK9r32:b5t9x3x) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/drake/doc/ubuntu_xenial.rst#L6)):*
> ```reStructuredText
> 
> The following instructions are written for Ubuntu 16.04 LTS (Xenial), which
> is not yet officially supported.
> ```

BTW Consider `supported by Drake`.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQalkHsFPejW7sm49pq:-KQalkHsFPejW7sm49pr:b3n6276) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/setup/ubuntu/16.04/install_prereqs.sh#L19)):*
> ```Shell
> # Install the APT dependencies.
> # TODO(david-german-tri): Can we remove libvtk-java, subversion?
> apt install --assume-yes --no-install-recommends \
> ```

I am skeptical of `--assume-yes`, because it can answer yes to questions other than the obvious ones we're used to.  See related discussion in #2223.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322)*

**Comment by jamiesnape** [comment]
BTW Looks like the perl dependency is for the interactive Gurobi downloader, hence there is no CI coverage. Given you have to manually install a license anyway, not sure how much advantage there is there, but that is a matter for another ticket.

**Comment by david-german-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu_trusty.rst, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQajT77MkTBA6dn-o3x:-KQbPl40AxulZJX9q6Hf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/drake/doc/ubuntu_trusty.rst#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Supported by whom?  Consider `written for Drake's supported version` or similar.
</details>
Done.

---

*[drake/doc/ubuntu_xenial.rst, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQajyYMPE4FB-5SLEmI:-KQbPrBo-AwI74emFhIG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/drake/doc/ubuntu_xenial.rst#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider `supported by Drake`.
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-KQalkHsFPejW7sm49pq:-KQbQ9hDoFJ1i4US6jBc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28db5972742cd34683cb2c4bfdd151ed87deb10c/setup/ubuntu/16.04/install_prereqs.sh#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am skeptical of `--assume-yes`, because it can answer yes to questions other than the obvious ones we're used to.  See related discussion in #2223.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3322#-:-KQbe4F6hoKaYq3Oz2Ep:bnfp4nl)*

**Pull request merged**
