### PR TITLE
jaco: Add and test for package.xml

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per discussion here:
https://github.com/RobotLocomotion/drake/pull/14038#pullrequestreview-497707499

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for feature review, please.
+@ggould-tri for platform review, please.

FYI @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKcm8691LUH1SX6STR:b-d5lrp8)* status: LGTM missing from assignees sammy-tri(platform),ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @sammy-tri)

**Comment by jwnimmer-tri** [comment]
Should this have the "status: commits are properly curated" label (i.e., do you plan to keep both commits during merge)?

**Comment by EricCousineau-TRI** [comment]
Yup!

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKgcUtAvAc6Rik7kfX:bnfp4nl)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Should we also remove the special handling of `jaco_description` from `ProcessModelDirectivesImpl`?  Or leave a note if we've got some legacy code around depending on that which needs to be removed in the future?

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKh7995mEIoLuBt_r-:b-dg512r)* status: LGTM missing from assignee sammy-tri(platform)

**Comment by EricCousineau-TRI** [comment]
I'm down for removing it from `dev/` code if it's tested. If not, is it OK if I leave that up to you, Grant?

**Review by ggould-tri — COMMENTED** [review]
This looks to me likely to land before I even finish reading the comments that accumulated on that PR in my vacation week :-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKhNKlD5602vs3vSKV:buftml7)* status: LGTM missing from assignee sammy-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
Yes, dev is not tested so land this if it passes CI; I'll make the change in the PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKh_nmEbP6rexKgj7Z:bqmx4sd)* status: LGTM missing from assignee sammy-tri(platform)

**Comment by EricCousineau-TRI** [comment]
Sweet! Yeah, also confirmed that it's not tested, at least in `process_model_directives_test`.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14134#-:-MIKiKVTC8HaC098HpFs:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform)

**Comment by EricCousineau-TRI** [comment]
Rebasing commits, then will do a forced merge-commit.

**Comment by EricCousineau-TRI** [comment]
Er, already on latest master. Merging legitmately.

**Pull request merged**
