### PR TITLE
[doc] Add release notes v1.25.0

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-Nnteybb42Mlh5GZa19Q:b-om6exd)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.25.0.md` line 138 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-NoHk9VG3v7BAFVUyuhx:-NoHk9VG3v7BAFVUyuhy:bwn5ynb) ([raw file](https://github.com/RobotLocomotion/drake/blob/076d2c3c50826d59c02de3f2c9d4394f2e42a558/doc/_release-notes/v1.25.0.md#L138)):*
> ```Markdown
> * `drake/multibody/tree/body.h` include path ([#20676][_#20676])
> * `pydrake.multibody.tree.BodyFrame_` ([#20676][_#20676])
> * `pydrake.multibody.tree.BodyFrame` ([#20676][_#20676])
> ```

nit The C++ `drake::multibody::BodyFrame<T>` is also deprecated by 20676.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-NoI7Ji81c7_Nhfx45iT:bnfp4nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with question on breaking changes for `Transform`

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-NoITjT04RrooPcudOhI:bkwhg9h)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.25.0.md` line 13 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-NoIT2fs6RjGH04l6itr:-NoIT2ftEl6rzgZ0Whcz:bfjeoj9) ([raw file](https://github.com/RobotLocomotion/drake/blob/34b8de8188b09a1959b1e9feed132e7769e1a87e/doc/_release-notes/v1.25.0.md#L13)):*
> ```Markdown
> # Breaking changes since v1.24.0
> 
> * None
> ```

nit Changes in `Transform::Sample()` behavior broke Anzu briefly; should that be mentioned here?
\cc @ggould-tri

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.25.0.md` line 13 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-NoIT2fs6RjGH04l6itr:-NoIU1Z220kue4-FkU5R:brq58cr) ([raw file](https://github.com/RobotLocomotion/drake/blob/34b8de8188b09a1959b1e9feed132e7769e1a87e/doc/_release-notes/v1.25.0.md#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Changes in `Transform::Sample()` behavior broke Anzu briefly; should that be mentioned here?
\cc @ggould-tri
</blockquote></details>

In #20775, I nerfed the exception back down to a deprecation warning, so I think it's moot now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-NoIdOocDr4lMqQi_-_c:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Thanks all! Will finish this today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-NoIdXcW-JOU2T68NYOa:bu6el7m)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20769#-:-NoJJce0DAiJZ6Y8WHNU:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
