### PR TITLE
Modified allURDFs() to be more robust against the user cloning drake into a directory whose path includes "*/dev/*"

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2194.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2356) &emsp; Multiple assignees:&emsp;@RussTedrake&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/RussTedrake">RussTedrake</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
May I suggest:

+@russtedrake for feature review.
+@jwnimmer-tri for platform review.

(Please feel free to reassign or bounce back to me as appropriate.)

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Modified allURDFs\(\) to be more robust against the user cloning drake into a directory whose path includes &quot;\*/dev/\*&quot;
> 
> Closes https://github.com/RobotLocomotion/drake/issues/2194.
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-:-KHmFNUCoP9wHQ5U43An:1744737180)*

**Comment by liangfok** [comment]
This PR passed [Build #1431](https://drake-jenkins.csail.mit.edu/job/experimental/1431/) and is thus ready for review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> May I suggest:
> 
> +@russtedrake for feature review.
> +@jwnimmer-tri for platform review.
> 
> (Please feel free to reassign or bounce back to me as appropriate.)</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-:-KHmnz-AxOUuNCJoHDjV:1295598800)*

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/allURDFs.m, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-KHqQJKM-_-DioboU4s5:-KHqQJKM-_-DioboU4s6:768236551) ([raw file](https://github.com/robotlocomotion/drake/blob/da50e083f6790f1c41de0517c5371ad8c19a045c/drake/util/allURDFs.m#L37)):*
> ```objc
>   error_msg = ['ERROR: drake/util/allURDFs.m: Failed to find any URDFs! '];
>   error_msg = [error_msg, 'Ensure program `find` is installed and available.'];
>   error(error_msg);
> ```

You've dropped the MissingDependency tag, which is a keyword that is checked by the ctest logic.  This will cause ctests to fail if find is not present instead of passing with a missing dependency, and i suspect will cause failures on the windows ci?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/allURDFs.m, line 11 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-KHtI25QoQWXrqG4hkM9:-KHtI25QoQWXrqG4hkMA:1862622974) ([raw file](https://github.com/robotlocomotion/drake/blob/da50e083f6790f1c41de0517c5371ad8c19a045c/drake/util/allURDFs.m#L11)):*
> ```objc
> urdfs = {};
> 
> % Creates a command that finds all URDFs within [drake-distro]. It uses the
> ```

Misleading comment; the `rootdir` is not necessarily the _`[drake-distro]`_; it can be overridden by passing in a different `rootdir`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/allURDFs.m, line 11 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-KHtI25QoQWXrqG4hkM9:-KHtKapKNOj-NPEzl15i:-1667357556) ([raw file](https://github.com/robotlocomotion/drake/blob/da50e083f6790f1c41de0517c5371ad8c19a045c/drake/util/allURDFs.m#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Misleading comment; the `rootdir` is not necessarily the _`[drake-distro]`_; it can be overridden by passing in a different `rootdir`.</details>
Fixed. I changed it `[drake distro]` to be `rootdir`.

---

*[drake/util/allURDFs.m, line 37 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-KHqQJKM-_-DioboU4s5:-KHtKsU2720uagCQHAA1:2050261978) ([raw file](https://github.com/robotlocomotion/drake/blob/da50e083f6790f1c41de0517c5371ad8c19a045c/drake/util/allURDFs.m#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> You've dropped the MissingDependency tag, which is a keyword that is checked by the ctest logic.  This will cause ctests to fail if find is not present instead of passing with a missing dependency, and i suspect will cause failures on the windows ci?</details>
This is strange, [CI build 1431](https://drake-jenkins.csail.mit.edu/job/experimental/1431/) passed despite missing the tag. We may need to look more into why.

In the mean time, I restored the missing tag for this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This PR passed [Build #1431](https://drake-jenkins.csail.mit.edu/job/experimental/1431/) and is thus ready for review.</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-:-KHtMo4s1ljRQiRo8P6s:1417088721)*

**Comment by liangfok** [comment]
This PR passed [CI Build #1448](https://drake-jenkins.csail.mit.edu/job/experimental/1448/) and is thus ready for platform review. +@sherm1 for platform review.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm:</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-:-KHuGDLxWZtHxv7XIMRN:-154334030)*

**Comment by sherm1** [comment]
Also need @russtedrake to acknowledge MissingDependency fix.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Just waiting for CI. :lgtm:</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2356#-:-KHuIO_ZjalgKoef5xKA:-302346720)*

**Comment by jwnimmer-tri** [comment]
Reviewable is showing all discussions resolved now.  Using override-merge to get around 'out of date with master'.

**Pull request merged**
