### PR TITLE
Build Python bindings using Bazel

### LINKED ISSUE #5430: Build python bindings in Bazel
Opening this as an issue to track development of the pydrake python bindings in the Bazel build.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #5430. Toward #3129.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5700)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Looks like IPOPT is not being built with PIC.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
gfortran is not PIC either, it seems.

**Comment by jamiesnape** [comment]
@david-german-tri Any reason that we cannot link to `libgfortran.{dylib|so}` instead of `libgfortran.a`?

**Comment by david-german-tri** [comment]
> @david-german-tri Any reason that we cannot link to libgfortran.{dylib|so} instead of libgfortran.a?

Not to my knowledge, feel free to try it.

**Comment by jamiesnape** [comment]
Will do. I feel like I may have opened a Pandora's box here.

**Comment by jwnimmer-tri** [comment]
Did you see https://github.com/jwnimmer-tri/drake/tree/bazel-force-pic that I mentioned in slack?  It switches ipopt and gfortran to shared libraries on Xenial and 100% works.  It needs OSX fixups though (`dylib` as the extension, etc).  Chat me in `#bazel` if you want.

**Comment by jamiesnape** [comment]
Missed that, but looks like it should be what we need.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
`undefined symbol: xargc` on Python tests that use MOSEK.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Looks like the culprit is SNOPT: https://github.com/RobotLocomotion/snopt/pull/20

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@david-german-tri and +@jwnimmer-tri for review (unless Mac fails in 3+ hours).

**Comment by jamiesnape** [comment]
Missing a `python_lint()` at the end of the `drake/bindings/BUILD` file. Will add after the Mac builds complete.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by david-german-tri** [comment]
-@jwnimmer-tri (OOO)

cc @rdeits FYI

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-:-Khi4xVYVqyoAcROz4pK:b4irlso)*

**Comment by david-german-tri** [comment]
Awesome!  By rummaging around in the runfiles, I was able to start up the python interpreter and construct a `RigidBodyTree`.  We'll have to think more about how to package this, but that's for a follow-up.  :lgtm:

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/bazel.rc, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-Khi78lsf9lM-IuDDVVy:-Khi78lsf9lM-IuDDVVz:bb6mt9b) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/bazel.rc#L6)):*
> ```
> 
> # Default build options.
> build --force_pic
> ```

:+1:

---

*[tools/numpy.bzl, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-KhiCCr5vWfFYJP8-G1J:-KhiCCr5vWfFYJP8-G1K:boxlg4d) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/numpy.bzl#L5)):*
> ```Python
> 
> """
> Finds local system NumPy headers and makes them available to be used as a
> ```

BTW, this doesn't look like a header-only library, and I have `.so` files in `/usr/lib/python2.7/dist-packages/numpy`.  Why don't we need them?

---

*[tools/pybind11.BUILD, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-KhiBPaVkuWRWBmqYy6i:-KhiBPaWaWWrNRXM4xg9:b1hh5br) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/pybind11.BUILD#L26)):*
> ```
>     includes = ["include"],
>     visibility = ["//visibility:public"],
>     deps = [
> ```

BTW - yikes!  We never would have been able to generate actual bindings without this, right?

---

*[tools/python.bzl, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-Khi8aCZoeMH_PIFxGwt:-Khi8aCZoeMH_PIFxGwu:b-exhbg3) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/python.bzl#L5)):*
> ```Python
> 
> """
> Finds local system Python headers and libraries using python-config and
> ```

BTW, why was this necessary?  What was `pkg-config` getting wrong?

---

*[tools/python.bzl, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-Khi9Xtg27svyG3wbw6x:-Khi9Xtg27svyG3wbw6y:b-47970u) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/python.bzl#L51)):*
> ```Python
> 
>     for cflag in cflags:
>         if cflag.startswith("-I"):
> ```

BTW when is this not true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-:-KhiI2f4XHrtG2uhGnwY:b-gmmvn1)*

**Comment by david-german-tri** [comment]
The BTW threads are nonblocking questions to help me understand what's going on - some of them might point to a need for comments, but I leave that to your judgment.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-:-KhiIN7C-WQstJdWl4Y6:b-cfky8g)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/numpy.bzl, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-KhiCCr5vWfFYJP8-G1J:-KhivHdqWNCEzIj3HUiX:b-gqdi5) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/numpy.bzl#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, this doesn't look like a header-only library, and I have `.so` files in `/usr/lib/python2.7/dist-packages/numpy`.  Why don't we need them?
</blockquote></details>

I only see  `.so` files that are used at runtime here. It is more obvious on Mac where Python C extensions and regular libraries have different file extensions.

---

*[tools/pybind11.BUILD, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-KhiBPaVkuWRWBmqYy6i:-Khine6LuV7sjzdepHM5:biwhc1d) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/pybind11.BUILD#L26)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW - yikes!  We never would have been able to generate actual bindings without this, right?
</blockquote></details>

Indeed. See `pybind11/eigen.h` and `pybind11/numpy.h`.

---

*[tools/python.bzl, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-Khi8aCZoeMH_PIFxGwt:-KhiktonFhPxMXRCNvct:b-in9d27) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/python.bzl#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, why was this necessary?  What was `pkg-config` getting wrong?
</blockquote></details>

I was getting a mismatch between Python executable and library. Using `pyenv` or the system Python on Mac also caused a breakage. Partially depends on your `PATH` and `PKG_CONFIG_PATH` and how many Pythons and pkg-configs you have installed (I have three Pythons and two pkg-configs).

---

*[tools/python.bzl, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5700#-Khi9Xtg27svyG3wbw6x:-KhikIhjIN2XNNIpFlCP:b6fzpqq) ([raw file](https://github.com/robotlocomotion/drake/blob/e777b3b46b85656b776919f9273267616ff07504/tools/python.bzl#L51)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW when is this not true?
</blockquote></details>

On Mac,
```
$/usr/bin/python-config --cflags
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE

$ /usr/local/bin/python-config --cflags
-I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7
-I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7
-fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
```
Quite ugly, really.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5700)*

**Comment by rdeits** [comment]
Possibly stupid question: how would one actually use these python bindings from outside of the drake build?

**Comment by david-german-tri** [comment]
Not a stupid question!  Right now, the best (terrible, brittle, no-good) answer I have is something like this:

```
$ cd ./bazel-bin/drake/bindings/pydrake_urdf_parser_test.runfiles/drake/drake/bindings/python
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrake.rbtree
>>> 
```

I think what we should actually do is include them in the `package_drake.sh` output.  Hence #5843.

**Comment by rdeits** [comment]
Ah, makes sense. Thanks!

**Comment by david-german-tri** [comment]
On a related note, @mwoehlke-kitware is working on a CMake superbuild install step for the `package_drake.sh` output.  That's probably more principled, and friendlier to director/spartan, than the #5797 prototype.

**Pull request merged**
