### PR TITLE
Update hash for bullet-pod to use bullet that does not require patch.

### PR DESCRIPTION
**Pull request by billhoffman**
This updates the hash for bullet and should fix the windows build errors on Jenkins.

### CODE REVIEW

**Comment by RussTedrake** [comment]
@billhoffman -- real compile error.

**Comment by billhoffman** [comment]
Not sure how to reproduce...  The error seems to be in the matlab only section.

There are several errors in the build log:


error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gurobipy/gurobipy.so (No such file or directory)

/usr/local/bin/ginstall: cannot stat '/tmp/drake-1825-18812/externals/swig_matlab/swig-matlab/CCache/ccache-swig.1': No such file or directory
make[8]: *** [install] Error 1
make[7]: *** [install-ccache] Error 2


/usr/local/bin/ginstall: cannot stat '/tmp/drake-1825-18812/externals/swig_matlab/swig-matlab/CCache/ccache-swig.1': No such file or directory
make[9]: *** [install] Error 1
make[8]: *** [install-ccache] Error 2


Although, I suspect these are the ones that have to do with this change.  However, I did not change btConvexHullShape.  @RussTedrake any ideas?

Undefined symbols for architecture x86_64:
  "btConvexHullShape::btConvexHullShape(float const*, int, int)", referenced from:
      ptToPolyBullet(double*, unsigned long, unsigned long) in isCollisionFree_mex.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [../systems/trajectories/isCollisionFree_mex.mexmaci64] Error 1
make[5]: *** [systems/trajectories/CMakeFiles/isCollisionFree_mex.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
Linking CXX shared module ../../../systems/trajectories/ptToPolyBullet_mex.mexmaci64
Linking CXX shared module ../../util/resolveCenterOfPressuremex.mexmaci64
Undefined symbols for architecture x86_64:
  "btConvexHullShape::btConvexHullShape(float const*, int, int)", referenced from:
      _mexFunction in ptToPolyBullet_mex.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [../systems/trajectories/ptToPolyBullet_mex.mexmaci64] Error 1
make[5]: *** [systems/trajectories/CMakeFiles/ptToPolyBullet_mex.dir/all] Error 2
Linking CXX shared module ../../../systems/trajectories/shiftFunnel_snopt_mex.mexmaci64
[ 68%] Built target resolveCenterOfPressuremex
Linking CXX shared module ../../../systems/trajectories/replanFunnels_mex.mexmaci64
Undefined symbols for architecture x86_64:
  "btConvexHullShape::btConvexHullShape(float const*, int, int)", referenced from:
      ptToPolyBullet(double*, unsigned long, unsigned long, mxArray_tag*) in shiftFunnel_snopt_mex.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "btConvexHullShape::btConvexHullShape(float const*, int, int)", referenced from:
      ptToPolyBullet(double*, unsigned long, unsigned long, mxArray_tag*) in replanFunnels_mex.cpp.o
ld: symbol(s) not found for architecture x86_64
make[6]: *** [../systems/trajectories/shiftFunnel_snopt_mex.mexmaci64] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [systems/trajectories/CMakeFiles/shiftFunnel_snopt_mex.dir/all] Error 2
make[6]: *** [../systems/trajectories/replanFunnels_mex.mexmaci64] Error 1
make[5]: *** [systems/trajectories/CMakeFiles/replanFunnels_mex.dir/all] Error 2

**Comment by rdeits** [comment]
The error messages that mention swig are likely unrelated: the Swig build process tries to use `yodl2man` to generate its manpages, but installing `yodl2man` is difficult on OSX, and the man pages are irrelevant for our use. The hack-y solution is that in `swig_matlab/CMakeLists.txt` I set the `INSTALL_COMMAND` to `make install || true` since the failing `yodl2man` step happens after all the necessary files are installed. We should probably come up with a less hack-y solution...

**Comment by billhoffman** [comment]
@RussTedrake somehow the double thing must be broken.
I went onto one of the build machines and found this:
 T btConvexHullShape::btConvexHullShape(double const*, int, int)
However, your code is looking for:
"btConvexHullShape::btConvexHullShape(float const, int, int)", referenced from:
ptToPolyBullet(double, unsigned long, unsigned long, mxArray_tag) in shiftFunnel_snopt_mex.cpp.o
ld: symbol(s) not found for architecture x86_64

Any idea how this can happen?

**Comment by RussTedrake** [comment]
might drake be compiling using a bullet header file that did not get the patch applied?

**Comment by RussTedrake** [comment]
based on a quick look at your last commit, it does not implement the same functionality provided by the patch logic before.  The patch logic inserted the double precision #defines only if the proper cmake flag was passed in.  your commit inserts them always.

i would have thought that this would cause the opposite problem (everyone expects doubles) than what you have (drake thinks it should ask for float).  but the bug must be in that logic.

**Comment by RussTedrake** [comment]
ah.  it's probably because you've "patched" btScalar.h , and are then copying btScalar.h.in over it with the configure line.  or that's my guess, just from looking at 
https://github.com/RobotLocomotion/bullet-pod/blob/master/bullet_double_precision_patch.diff

**Pull request closed without merging**
