### PR TITLE
pydrake util: Simplify `alias_cc_test`. Remove ASan

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Works around #10025

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10026)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Confirmed that this passes locally with `clang` + `asan`. We can still wait for CI to pass if so desired.

@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please.

**Comment by jamiesnape** [comment]
Needs buildifier running on it.

**Comment by EricCousineau-TRI** [comment]
Done.

**Comment by jamiesnape** [comment]
I would say merge when the cached builds finish so I can get the nightly builds re-running before much else merges.

**Comment by jwnimmer-tri** [comment]
The two cache builds just finished.  Forcing in now.

**Pull request merged**
