### PR TITLE
Rename all drake-distro/drake/foo to drake-distro/foo

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is the committed result of running `tools/dev/6996-move`.

For now, this is just CI testing.

Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7503)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7503#-KzAqn9uw8j5oaxoZOS-:-KzAqn9vpDpRHJoYIr8T:b-hh9q1z) (no related file):*
This is an admin block on merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7503)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
For reviewers:
- The one-line change is at https://github.com/RobotLocomotion/drake/blob/b8d8c47ffed1a3bb968defa74f8a71f3fb18b736/tools/skylark/6996.bzl#L10 changing False to True.
- The removes lines are deleting, rather than moving, https://github.com/RobotLocomotion/drake/blob/master/drake/BUILD.bazel.

**Comment by EricCousineau-TRI** [comment]
+@ericcousineau-tri for feature and platform review.

---

Review status: 0 of 2823 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7503#-:-L-mpkrqDRFscW3ppBdQ:bnax1v0)*

**Comment by sammy-tri** [comment]
Works for me!

Specifically, I tested with `bazel test -k --config mosek --config snopt //...` and the only test which failed was `//bindings/pydrake:pydrake_common_install_test` which seems to be a known issue.

:lgtm:

**Comment by SeanCurtis-TRI** [comment]
I invoked a simpler set of test and got this a timeout on `//common/proto:call_python_full_test`. Is that surprising?

**Comment by jwnimmer-tri** [comment]
When I merged #7574, github closed this for me accidentally.  I've opened #7575 with a new take.

**Comment by EricCousineau-TRI** [comment]
@seancurtis-tri Hm... Yes, that is surprising for a non-threaded test. Is that reproducible?

**Pull request closed without merging**
