### PR TITLE
Quadrotor LQR demo

### PR DESCRIPTION
**Pull request by naveenoid**
Mimicks the style of the Acrobot LQR demo. 

Marking at do-not-review until #4540 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4588)

### CODE REVIEW

**Comment by naveenoid** [comment]
Ready for review!
+@RussTedrake For feature review.

**Comment by RussTedrake** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Quadrotor/CMakeLists.txt, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9L2bGLGdgKRN8S9Xq:-K_9L2bGLGdgKRN8S9Xr:b-jvl3bb) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/CMakeLists.txt#L41)):*
> ```CMake
>       drakeSystemPrimitives
>       gflags)
>   drake_add_test(NAME run_quadrotor_lqr COMMAND run_quadrotor_lqr -simulation_trials 2)
> ```

set realtime rate to zero for faster build server tests.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9J2_YfFwDodFdBcJC:-K_9J2_YfFwDodFdBcJD:b-ssusup) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L109)):*
> ```cpp
> 
>   // Steady state hover input.
>   quad_context_goal->FixInputPort(0, Eigen::VectorXd::Zero(4));
> ```

remove this (it gets immediate overwritten below)

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9Lwo44PLGO4GOT0IE:-K_9Lwo44PLGO4GOT0IF:bz3d8h7) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L114)):*
> ```cpp
>   x0.topRows(3) = nominal_position;
> 
>   Eigen::VectorXd u0 = Eigen::VectorXd::Ones(4);
> ```

Better to use Eigen::VectorXd::Constant(m*g/4) to combine this and the next line.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JcvWWFcedvXFohFH:-K_9JcvWWFcedvXFohFI:b-q8vpdv) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L124)):*
> ```cpp
>   // Setup LQR Cost matrices (penalize position error 10x more than velocity.
>   Eigen::MatrixXd Q = Eigen::MatrixXd::Identity(12, 12);
>   Q *= 10;
> ```

this multiplies both positions and velocities.  (inconsistent with the comment).  having position gain 10* more than velocities is often a good thing.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JwlEWBM46A4q_fym:-K_9JwlEWBM46A4q_fyn:b-fw75f7) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.h#L38)):*
> ```objc
>   }
> 
>   double get_m() const { return m; }
> ```

we've been recommending just m() and g() for trivial accessor methods now.

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9KqogejUVFoTnYP4B:-K_9KqogejUVFoTnYP4C:b12qes5) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L4)):*
> ```cpp
> ///
> /// This demo sets up a controlled Quadrotor that uses a Linear Quadratic
> /// Regulator to fly towards a pre-defined target from random chosen initial
> ```

that might be a bit of an overstatement. :)  it (locally) stabilizes a nominal hover.  

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9LHGJNRVkfaDHZT7E:-K_9LHGJNRVkfaDHZT7F:b6w20oe) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L72)):*
> ```cpp
>     simulator.Initialize();
>     simulator.set_target_realtime_rate(FLAGS_simulation_real_time_rate);
>     simulator.StepTo(FLAGS_trial_duration);
> ```

add a check here that the quadrotor achieved the nominal position within some tolerance to improve the value of the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by naveenoid** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Quadrotor/CMakeLists.txt, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9L2bGLGdgKRN8S9Xq:-K_AZlSg5g7xwa5yRo2B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/CMakeLists.txt#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

set realtime rate to zero for faster build server tests.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9J2_YfFwDodFdBcJC:-K_A_-YXTpTpoppR-hkz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L109)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

remove this (it gets immediate overwritten below)
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9Lwo44PLGO4GOT0IE:-K_A_Juti9yFkiRxbU88:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L114)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Better to use Eigen::VectorXd::Constant(m*g/4) to combine this and the next line.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JcvWWFcedvXFohFH:-K_AaArjQ1UYwD3WJgif:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.cc#L124)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this multiplies both positions and velocities.  (inconsistent with the comment).  having position gain 10* more than velocities is often a good thing.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JwlEWBM46A4q_fym:-K_AjNvuJsssTx_z0R9S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/quadrotor_plant.h#L38)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we've been recommending just m() and g() for trivial accessor methods now.
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9KqogejUVFoTnYP4B:-K_AsuFOfq_Fu35xyukS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L4)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that might be a bit of an overstatement. :)  it (locally) stabilizes a nominal hover.  
</blockquote></details>

Done.

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9LHGJNRVkfaDHZT7E:-K_B8om69PABIin7Kb8i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/620c4fab83ad32429fba2369399305b6217738e9/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L72)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

add a check here that the quadrotor achieved the nominal position within some tolerance to improve the value of the test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by RussTedrake** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JcvWWFcedvXFohFH:-K_CG3G2W_BeFREQXKU-:b-5imo78) ([raw file](https://github.com/robotlocomotion/drake/blob/0a36319f1a900f53c93e95d4ff28efa012daa8e1/drake/examples/Quadrotor/quadrotor_plant.cc#L124)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The line below has 16 instead of 6.  (I'm surprised it even works without throwing a runtime error)

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_CGXr2kP3y8l1AFn4S:-K_CGXr2kP3y8l1AFn4T:b-vo7wbn) ([raw file](https://github.com/robotlocomotion/drake/blob/903564391868181faaf05d3d638bd853d9ad2974/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L88)):*
> ```cpp
>     const VectorX<double>& position_vector = state->CopyToVector();
> 
>     if (!CompareMatrices(position_vector, kNominalState, 1e-4)) {
> ```

@jwnimmer-tri produced a lighter-weight version of this intended to be used in non-unit tests.  He might recommend you use that version instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by naveenoid** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Quadrotor/quadrotor_plant.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_9JcvWWFcedvXFohFH:-K_C_0PptCSXiUDoU5jO:b-e6roi3) ([raw file](https://github.com/robotlocomotion/drake/blob/0a36319f1a900f53c93e95d4ff28efa012daa8e1/drake/examples/Quadrotor/quadrotor_plant.cc#L124)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The line below has 16 instead of 6.  (I'm surprised it even works without throwing a runtime error)
</blockquote></details>

Done. Wow I didnt get any runtime errors.. CI seems to have though!

---

*[drake/examples/Quadrotor/run_quadrotor_lqr.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_CGXr2kP3y8l1AFn4S:-K_CeyEJTwq8bfgCW5c3:b-bnx6a8) ([raw file](https://github.com/robotlocomotion/drake/blob/903564391868181faaf05d3d638bd853d9ad2974/drake/examples/Quadrotor/run_quadrotor_lqr.cc#L88)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@jwnimmer-tri produced a lighter-weight version of this intended to be used in non-unit tests.  He might recommend you use that version instead.
</blockquote></details>

Done. I assume you meant is_approx_equal_abstol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by naveenoid** [comment]
+@ggould-tri for platform review

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-:-K_D-bvLGVXZTuQHEiYA:b-gbk9vg)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-:-K_FVArAV8RZ84nJAd-W:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm: pending minor items below.

---

Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_UxrADhxZCfyf1MMKY:-K_UxrADhxZCfyf1MMKZ:byweb5a) ([raw file](https://github.com/robotlocomotion/drake/blob/fbb00284dd854aa6e8e27244818b61385bbff8e5/drake/examples/Quadrotor/quadrotor_plant.h#L56)):*
> ```objc
>       L_{0.175},          // Length of the arms (m).
>       kF_{1.0},           // Force input constant.
>       kM_{0.0245};        // Momment input constant.
> ```

FYI typo "momment"

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_UxxyudcZKfZRJhf_a:-K_UxxyudcZKfZRJhf_b:b-bv1psz) ([raw file](https://github.com/robotlocomotion/drake/blob/fbb00284dd854aa6e8e27244818b61385bbff8e5/drake/examples/Quadrotor/quadrotor_plant.h#L67)):*
> ```objc
> /// @see systems::LinearQuadraticRegulator.
> std::unique_ptr<systems::AffineSystem<double>> StabilizingLQRController(
>     const QuadrotorPlant<double>* acrobot, Eigen::Vector3d nominal_position);
> ```

"acrobot" seems odd here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-:-K_UyaDf2CGRu2UBCtLG:b-nx7600)*

**Comment by naveenoid** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_UxrADhxZCfyf1MMKY:-K_YFgR-724YjBqS-xY8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbb00284dd854aa6e8e27244818b61385bbff8e5/drake/examples/Quadrotor/quadrotor_plant.h#L56)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "momment"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by naveenoid** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Quadrotor/quadrotor_plant.h, line 67 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-K_UxxyudcZKfZRJhf_a:-K_YH_0F6PcWHVcJbLrG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbb00284dd854aa6e8e27244818b61385bbff8e5/drake/examples/Quadrotor/quadrotor_plant.h#L67)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

"acrobot" seems odd here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588)*

**Comment by naveenoid** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4588#-:-K_Zy4o06eHK5TPNrUzM:b-3f2dwx)*

**Pull request merged**
