### PR TITLE
Add comment that IrisInConfigurationSpaceFromCliqueCover does not obe…

### PR DESCRIPTION
**Pull request by AlexandreAmice**
…y collision checker padding

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@sadraddini for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033#-:-NrMRhYZ9OnC_3_TghRp:b-u7dhg2)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
The way this API comment is worded is a _promise_ that we will _never_ obey the padding in any future release (unless we deprecate and transition gradually to use it).

In case your thought is that we should obey it eventually, then the comment should be rephrased more like "warning: padding is currently ignored, but we hope to obey it later on".  That keep the door open for implementing it without deprecation hassles.

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/iris/iris_from_clique_cover.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21033#-NrMSEAp62r-xt7eg-Is:-NrMSEAp62r-xt7eg-It:b-4yst68) ([raw file](https://github.com/RobotLocomotion/drake/blob/d43ab62f3b665614c13e88ca2f1090a2d775619a/planning/iris/iris_from_clique_cover.h#L112)):*
> ```objc
>  * is faster than solving the max clique problem to global optimality.
>  *
>  * The final regions do NOT respect the padding in the collision checker.
> ```

nit  "The final regions may NOT respect the paddings set by the @p collision_checker, as they are not currently passed in to the algorithm".

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033#-:-NraQUkk3iV4DohJM-cR:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@sherm1 for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033#-:-NrbJbWdBHZrFNNzhwvY:b-ksuhyg)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21033#-:-NrbWLlz8EulaNlxRYJ1:b8qx53o)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
+(release notes: none)

**Pull request merged**
