### PR TITLE
Implement nonsymmetric AddToBlock

### PR DESCRIPTION
**Pull request by anrp-tri**
Note: part of https://github.com/vincekurtz/drake/tree/traj_opt/traj_opt

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20048)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
+@xuchenhan-tri I can serve as feature reviewer.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20048)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @anrp-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20048#-NccSf1K0lRiO0FyNXRA:-NccSf1LEDmtk7lMs4sr:bst1deg) (no related file):*
There are a few issues with the PR, but before going into details, I have question about the goal of the PR. From the PR message, it appears that this is a step towards the TrajOpt project. I'd like to understand the intended use of this class there. 

FYI, 

1. This class was designed specifically for tangent matrices from an (isotropic hyperelastic) FEM system so the matrix is always guaranteed to be symmetric.
2. We plan to deprecate this soon in favor of `BlockSparseLowerTriangularOrSymmetricMatrix`.

Let's discuss how to best move forward given those two points.

___

**Comment by anrp-tri** [comment]
@amcastro-tri per our discussion, any update re if we even need petsc?

**Comment by jwnimmer-tri** [comment]
This PR seems somewhat stale.  Shall we close it?  The class it's enhancing has been deleted in the first place.

**Review by xuchenhan-tri — COMMENTED** [review]
I think we can safely close the PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20048#-:-NsoQBoc4l2Y2iuhV0MI:b-ew5nsp)* status: 1 unresolved discussion, LGTM missing from assignees amcastro-tri,xuchenhan-tri(platform), missing label for release notes (waiting on @anrp-tri)

**Pull request closed without merging**
