### PR TITLE
[bindings] Drop the render qualifier for render-related symbols

### LINKED ISSUE #19088: Namespace for render-related Python bindings
In #18877, we make efforts for the namespaces in three `RenderEngine` implementations to be consistent. We should also revisit render-related Python bindings due to the changes on the C++ side.

CC\ @jwnimmer-tri

### PR DESCRIPTION
**Pull request by zachfang**
Everything in `pydrake.geometry.render` should be imported from `pydrake.geometry` module path now.

Toward #12055 
Close #19088

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, thanks!

This is the example deprecation message for my local testing:
```
.../drake/examples/hardware_sim/hardware_sim.py:56: DrakeDeprecationWarning: Please import the render-related symbols from pydrake.geometry instead of the deprecated pydrake.geometry.render submodule. The deprecated code will be removed from Drake on or after 2023-08-01.
  from pydrake.geometry.render import RenderEngineVtkParams, MakeRenderEngineVtk
``` 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-:-NTWJTF83EGA1nh8u6vG:b-p3t27z)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTWJ4Ik1PR19KfOGH01:-NTWJ4Il8nfUR1sliEoY:b-xqrg6s) (no related file):*
Working. Making corresponding changes in Anzu.

___

**Review by jwnimmer-tri — COMMENTED** [review]
Tested locally:

```console
jwnimmer@call-cps:~/tmp$ PYTHONPATH=install/lib/python3.10/site-packages python3 -c 'from pydrake.geometry.render import RenderLabel; print(RenderLabel)'
<string>:1: DrakeDeprecationWarning: Please import the render-related symbols from pydrake.geometry instead of the deprecated pydrake.geometry.render submodule. The deprecated code will be removed from Drake on or after 2023-08-01.
<class 'pydrake.geometry.RenderLabel'>
```

:lgtm:

I think "single reviewer ok" is probably fine in this case, but I'll let you decide.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-:-NTZ8Qwo5mn12vzRQ-_T:biucaxv)* status: 8 unresolved discussions, needs at least two assigned reviewers (waiting on @zachfang)

___
*[`tutorials/rendering_multibody_plant.ipynb` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ45du34qWi5Dd8H3z:-NTZ45du34qWi5Dd8H4-:btt62yx) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/tutorials/rendering_multibody_plant.ipynb#L59)):*
> ```
>     "    StartMeshcat,\n",
>     ")\n",
>     "from pydrake.geometry import (\n",
> ```

nit There are two groups of `pydrake.geometry` imports now.  They should mix together into just one group.
___
*[`bindings/pydrake/geometry/BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ6gm6456t3xe5z3ZI:-NTZ6gm6456t3xe5z3ZJ:b-a9hc01) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/BUILD.bazel#L58)):*
> ```Starlark
>     ],
>     py_srcs = [
>         # 2023-08-01 Remove this source file upon completion of deprecation.
> ```

nit The placement of comment as-written leaves room for doubt about what exactly should be removed.

Changing the ordering helps clarify:



_Suggestion:_
```Starlark
        "_geometry_extra.py",
        # 2023-08-01 Remove this source file upon completion of deprecation.
        "render.py",
```
___
*[`bindings/pydrake/geometry/geometry_py.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ6CHUD8eQQfIJigEb:-NTZ6CHUD8eQQfIJigEc:bchh1nw) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/geometry_py.h#L26)):*
nit I think we can be more precise with the language here.

> Binds the public API of the `drake/geometry/render/` and `drake/geometry/render_*/` directories. See geometry_py_render.cc.
___
*[`bindings/pydrake/geometry/geometry_py_render.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ534LDIZNWAE8CUNr:-NTZ534LDIZNWAE8CUNs:b-rxrbzo) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/geometry_py_render.cc#L3)):*
nit I think we can be more precise with the language here.

> This contains the bindings for the public API of the `drake/geometry/render/` and `drake/geometry/render_*/` directories. They can be found in the pydrake.geometry module.
___
*[`bindings/pydrake/geometry/test/render_engine_gl_test.py` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ6yZJ5jnZ5K9UfwB_:-NTZ6yZJ5jnZ5K9UfwBa:baaefpj) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/test/render_engine_gl_test.py#L21)):*
> ```Python
>         else:
>             scene_graph.AddRenderer("gl_renderer",
>                                     mut.MakeRenderEngineGl(
> ```

nit This can pack better now.



_Suggestion:_
```Python
                                    mut.MakeRenderEngineGl(params=params))
```
___
*[`bindings/pydrake/geometry/test/render_test.py` line 251 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ7Yf_8kcq4NKfxQ8B:-NTZ7Yf_8kcq4NKfxQ8C:baaefpj) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/test/render_test.py#L251)):*
> ```Python
>         params = mut.RenderEngineGltfClientParams()
>         scene_graph.AddRenderer("gltf_renderer",
>                                 mut.MakeRenderEngineGltfClient(
> ```

nit This can pack better now.



_Suggestion:_
```Python
                                mut.MakeRenderEngineGltfClient(params=params))
```
___
*[`bindings/pydrake/geometry/test/scene_graph_test.py` line 448 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ7DvJ9nhPk1Dy0Vc8:-NTZ7DvKDpD9rFkcGS4v:baaefpj) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/test/scene_graph_test.py#L448)):*
> ```Python
>         scene_graph.AddRenderer(renderer_name,
>                                 mut.MakeRenderEngineVtk(
>                                     params=render_params))
> ```

nit This can pack better now.



_Suggestion:_
```Python
                                mut.MakeRenderEngineVtk(params=render_params))
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241)* status: 9 unresolved discussions, needs at least two assigned reviewers (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ92gg0e8ioxslRHOq:-NTZ92gg0e8ioxslRHOr:b-x8c149) (no related file):*
BTW also `drake/bindings/pydrake/test/all_test.py` needs an edit.  Delete these two lines:

```python
            # - render
            "ColorRenderCamera",
```

The purpose of that list is to check one class from every module.  Since we already check SceneGraph, we don't need anything render-specific anymore.

___

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTWJ4Ik1PR19KfOGH01:-NTZfsJLD_FmKzEC-lG-:b-wq4ccx) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Working. Making corresponding changes in Anzu.
</blockquote></details>

An Anzu PR is created, pending CI results.

___
___
*[`tutorials/rendering_multibody_plant.ipynb` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ45du34qWi5Dd8H3z:-NTZfY6R94U2zGE14ZHI:b-macmrm) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/tutorials/rendering_multibody_plant.ipynb#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit There are two groups of `pydrake.geometry` imports now.  They should mix together into just one group.
</blockquote></details>

Done. Missed this one.
___
*[`bindings/pydrake/geometry/BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ6gm6456t3xe5z3ZI:-NTZfbW49eSLKxU99cEG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/BUILD.bazel#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The placement of comment as-written leaves room for doubt about what exactly should be removed.

Changing the ordering helps clarify:
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/geometry_py.h` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ6CHUD8eQQfIJigEb:-NTZfeLd0OvgSQNfVjpX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/geometry_py.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think we can be more precise with the language here.

> Binds the public API of the `drake/geometry/render/` and `drake/geometry/render_*/` directories. See geometry_py_render.cc.
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/geometry_py_render.cc` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19241#-NTZ534LDIZNWAE8CUNr:-NTZfiVfCQHFihCffXwk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/140fb807ded92489f20e65fb14e9b55e37defb91/bindings/pydrake/geometry/geometry_py_render.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think we can be more precise with the language here.

> This contains the bindings for the public API of the `drake/geometry/render/` and `drake/geometry/render_*/` directories. They can be found in the pydrake.geometry module.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19241)* status: needs at least two assigned reviewers (waiting on @zachfang)

**Comment by RussTedrake** [comment]
FYI - My course CI caught fire with errors of the form
```
    pydrake.geometry.render.RenderLabel.kDoNotRender,
AttributeError: module 'pydrake.geometry' has no attribute 'render'
```
This was, admittedly, some old a slightly crushy library code that was doing
```
import pydrake.all
reserved_labels = [
    pydrake.geometry.render.RenderLabel.kDoNotRender,
    pydrake.geometry.render.RenderLabel.kDontCare,
    pydrake.geometry.render.RenderLabel.kEmpty,
    pydrake.geometry.render.RenderLabel.kUnspecified,
]
```
and i'm ok with saying that this was not a proper import and should not need to be caught in the deprecation warnings.  But reporting it here just in case.

**Comment by zachfang** [comment]
I am still learning the Python deprecation process, but after looking into relevant files, I think the behavior is expected and documented [here](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/all.py#L14-L18). I.e.,

```
* The downsides of importing an `.all` module are ...
  (c) deprecated symbols could get removed without warning from `all` modules.
* Deprecated modules will *not* be incorporated in `all` modules, because
  otherwise, `all` would emit noisy deprecation warnings, or if they are
  suppressed, subseqeuent imports of those deprecated modules will not trigger
  warnings.
```

**Pull request merged**
