### PR TITLE
Implement DoToRoadPosition for monolane

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6020)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@maddog-tri for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KjHdCWgdlDwzJnyK7GY:b-5klkw7)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by maddog-tri** [comment]
Review pass done.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3NYzkekiStC5_ECQ:-Kjj3NZ-p5hkq0aWUVNt:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L1)):*
> ```cpp
> #include <limits>
> ```

Unused.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3QDnl9IbBxgNoAS8:-Kjj3QDnl9IbBxgNoAS9:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L2)):*
> ```cpp
> #include <limits>
> #include <tuple>
> ```

Unused.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj26C6SkIpw6fGDB2Q:-Kjj26C7dIlA_KlxY8Qe:bezu9y4) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L90)):*
> ```cpp
>         const api::LaneEndSet* ends = hint->lane->GetOngoingBranches(
>             static_cast<api::LaneEnd::Which>(iter));
>         if (ends == nullptr) continue;
> ```

Did some backend return a `nullptr`?  (The return value of `Lane::GetOngoingBranches()` is not supposed to be null.  I.e., such a test should not be necessary.)

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 594 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3iOLrbt-VgIGweIa:-Kjj3iOM_fVaZqFp-_iW:b-gsaa8x) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L594)):*
> ```cpp
> 
> 
> GTEST_TEST(MonolaneLanesTest, DoToRoadPosition) {
> ```

This test belongs in a different/new file.  `monolane_lanes_test.cc` is intended to be unit-tests specific to `monolane::Lane` and its subclasses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KjjNgEqOVR4XUDUQ7m2:b-l0f5b4)*

**Comment by maddog-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjjO_XqMK-6uBiU4Im8:-KjjO_Xr89PK6wWbjP8S:biu6967) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L86)):*
> ```cpp
>       // the position associated with the first found containing lane or the
>       // distance-minimizing position.
>       for (int iter = api::LaneEnd::kStart; iter <= api::LaneEnd::kFinish;
> ```

I believe that nowadays you can do this a lot more elegantly with something like:
```
  for (const auto which_end : {api::LaneEnd::kStart, api::LaneEnd::kFinish}) {
    ...
  }
```
No `static_cast` required on `which_end`, either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by jadecastro** [comment]
Comments addressed.  

I have made a few changes to the unit test: 1) the new code is now contained within its own `.cc` file, and 2) I have added a new unit test to verify the case where there are no ongoing lanes to provide coverage of an untested code path - one of your comments brought this to light.

---

Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3NYzkekiStC5_ECQ:-Kjo7YDBZ2g0y8un7kh5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L1)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3QDnl9IbBxgNoAS8:-Kjo7YTNP3vW1PTnkzBq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L2)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjjO_XqMK-6uBiU4Im8:-Kjo8W86UbIylGC75APC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L86)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I believe that nowadays you can do this a lot more elegantly with something like:
```
  for (const auto which_end : {api::LaneEnd::kStart, api::LaneEnd::kFinish}) {
    ...
  }
```
No `static_cast` required on `which_end`, either.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj26C6SkIpw6fGDB2Q:-Kjo9vWMsRGPi7kk_nU2:b-u31r8a) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/road_geometry.cc#L90)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Did some backend return a `nullptr`?  (The return value of `Lane::GetOngoingBranches()` is not supposed to be null.  I.e., such a test should not be necessary.)
</blockquote></details>

Nope, no `nullptr` detected!  (Added a unit test to confirm).  I've removed this check here.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 594 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3iOLrbt-VgIGweIa:-Kjo9-H3SP9c0IJrCfeh:b-tft9zq) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L594)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

This test belongs in a different/new file.  `monolane_lanes_test.cc` is intended to be unit-tests specific to `monolane::Lane` and its subclasses.
</blockquote></details>

Yeah, good point. I've moved it, and spinning off a few dependencies into a common file header file (called `monolane_test_utils.h` -- I'm not tied to the name, so please offer an alternative if you have a better one to suggest here). PTAL.

In an effort to prevent further confusion, I have also moved the `#include` for the `.../monolane/lane.h` within `monolanes_lanes_test.cc` - the class which concerns the subsequent unit tests - to the top of that file (as is customary for Drake unit tests). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-Kjp-ofU-a1gxw-lHl1H:bp3t3vw)*

**Comment by maddog-tri** [comment]
Nice.  Two small comments; otherwise :LGTM: .

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 594 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3iOLrbt-VgIGweIa:-KjtVVMe0y6qQi6wPa2X:b-oh6e6) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L594)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Yeah, good point. I've moved it, and spinning off a few dependencies into a common file header file (called `monolane_test_utils.h` -- I'm not tied to the name, so please offer an alternative if you have a better one to suggest here). PTAL.

In an effort to prevent further confusion, I have also moved the `#include` for the `.../monolane/lane.h` within `monolanes_lanes_test.cc` - the class which concerns the subsequent unit tests - to the top of that file (as is customary for Drake unit tests). 
</blockquote></details>

Oooh, good point.  The `arc_lane.h` and `line_lane.h` includes should probably go up there, too!

---

*[drake/automotive/maliput/monolane/test/monolane_road_geometry_test.cc, line 199 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjtWwP8EmhomP03_HBV:-KjtWwP8EmhomP03_HBW:b-ry9api) ([raw file](https://github.com/robotlocomotion/drake/blob/5e56c62bde45fd384e7ce0a094e9237307a8665e/drake/automotive/maliput/monolane/test/monolane_road_geometry_test.cc#L199)):*
> ```cpp
>   EXPECT_NO_THROW(actual_position =
>       rg->ToRoadPosition(geo_pos, &hint, nullptr, &distance));
>   EXPECT_NE(actual_position.lane->id().id, "l:lane0");  // Point is in lane0,
> ```

Is there a reason this couldn't be phrased in the affirmative, `EXPECT_EQ(actual_position.lane->id().id, "l:lane1")` ?  (I think that would be a bit more straightforward for the reader, and a tighter test of the expected behavior.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KjtXXC-t0eHUCms-yn8:b-nw2m94)*

**Comment by jadecastro** [comment]
+@sherm1 for platform review -- thanks!

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 594 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjj3iOLrbt-VgIGweIa:-Kjx44z5n5BwgQr6hP38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa174c459950b22f3d35ff6fcb084b69619ce73d/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L594)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Oooh, good point.  The `arc_lane.h` and `line_lane.h` includes should probably go up there, too!
</blockquote></details>

Done.

---

*[drake/automotive/maliput/monolane/test/monolane_road_geometry_test.cc, line 199 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjtWwP8EmhomP03_HBV:-Kjx43xZRHPo24RC3okb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e56c62bde45fd384e7ce0a094e9237307a8665e/drake/automotive/maliput/monolane/test/monolane_road_geometry_test.cc#L199)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Is there a reason this couldn't be phrased in the affirmative, `EXPECT_EQ(actual_position.lane->id().id, "l:lane1")` ?  (I think that would be a bit more straightforward for the reader, and a tighter test of the expected behavior.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-Kjx9FeRmo2kkrAWbFqP:b-60vr5i)*

**Comment by sherm1** [comment]
Platform :lgtm: after a couple of BTWs, ptal.

---

Reviewed 1 of 4 files at r1, 2 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjyhUuZ20dLcN2fIJuZ:-KjyhUuZ20dLcN2fIJu_:b-v1nprl) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/road_geometry.cc#L104)):*
> ```cpp
>     // the position associated with the first found containing lane or the
>     // distance-minimizing position.
>     const api::Lane* lane = this->junction(0)->segment(0)->lane(0);
> ```

BTW I guess we're guaranteed by some enforced invariant to have at least one junction/segment/lane so this doesn't have to be checked?

---

*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 18 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjyk-sehKYs5w-YGHza:-Kjyk-sehKYs5w-YGHzb:bqplomf) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L18)):*
> ```objc
>     EXPECT_NEAR(_actual.x(), _expected.x(), _tolerance);     \
>     EXPECT_NEAR(_actual.y(), _expected.y(), _tolerance);     \
>     EXPECT_NEAR(_actual.z(), _expected.z(), _tolerance);     \
> ```

BTW, generally variable names beginning with "_" are trouble.  C++ reserves all names beginning with "_" followed by a capital letter. In a global namespace, *all* names beginning with "_" are reserved ([ref](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)). Somewhat unclear whether the GSG [allows them](https://google.github.io/styleguide/cppguide.html#Variable_Names); I think probably not.

In any case, best practice: don't begin any variable names with "_".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KjymMJwYt_4hjh2cDF4:b-umhbyz)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 18 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjyk-sehKYs5w-YGHza:-KjymZ8U6dlA8abDlOvG:b-5ojd86) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, generally variable names beginning with "_" are trouble.  C++ reserves all names beginning with "_" followed by a capital letter. In a global namespace, *all* names beginning with "_" are reserved ([ref](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)). Somewhat unclear whether the GSG [allows them](https://google.github.io/styleguide/cppguide.html#Variable_Names); I think probably not.

In any case, best practice: don't begin any variable names with "_".
</blockquote></details>

BTW Oops -- Markdown messed with my underscores. Let me try that again:
Generally variable names beginning with `_` are trouble.  C++ reserves all names beginning with `_` followed by a capital letter. In a global namespace, *all* names beginning with `_` are reserved ([ref](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)). Somewhat unclear whether the GSG [allows them](https://google.github.io/styleguide/cppguide.html#Variable_Names); I think probably not.

In any case, best practice: don't begin any variable names with `_`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by jadecastro** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjyhUuZ20dLcN2fIJuZ:-KkAiVr6fo1s5Osr6mu2:b-i00gqb) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/road_geometry.cc#L104)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I guess we're guaranteed by some enforced invariant to have at least one junction/segment/lane so this doesn't have to be checked?
</blockquote></details>

Good point, @sherm1. No such invariant exists, so I've added some `DRAKE_DEMAND`s here.

---

*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 18 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-Kjyk-sehKYs5w-YGHza:-KkAuhhTN0SwzxH5UwHh:bb5bsz6) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Oops -- Markdown messed with my underscores. Let me try that again:
Generally variable names beginning with `_` are trouble.  C++ reserves all names beginning with `_` followed by a capital letter. In a global namespace, *all* names beginning with `_` are reserved ([ref](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)). Somewhat unclear whether the GSG [allows them](https://google.github.io/styleguide/cppguide.html#Variable_Names); I think probably not.

In any case, best practice: don't begin any variable names with `_`.
</blockquote></details>

Done.  Good to know! Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by jadecastro** [comment]
Comments addressed (@sherm1, I think you're blocking on one of them).

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KkB702TqPRVupy37CKu:b1xqp5s)*

**Comment by maddog-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/monolane/road_geometry.cc, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KjyhUuZ20dLcN2fIJuZ:-KkBLkA2plR8eWSpir-E:be4cz) ([raw file](https://github.com/robotlocomotion/drake/blob/ec60849e7803299a72c3521a069b9ea2c46513c8/drake/automotive/maliput/monolane/road_geometry.cc#L104)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Good point, @sherm1. No such invariant exists, so I've added some `DRAKE_DEMAND`s here.
</blockquote></details>

(BTW:  These same bounds-checks occur in the `junction(i)`, `segment(i)`, `lane(i)` accessors, FWIW.)

---

*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KkBMGAbai0TqgIq3ImG:-KkBMGAbai0TqgIq3ImH:b-8c0akn) ([raw file](https://github.com/robotlocomotion/drake/blob/1e7ec02ae8fc016a706e60dcd18f251369949c0a/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L11)):*
> ```objc
> namespace monolane {
> 
> #define EXPECT_GEO_NEAR(actual_arg, expected_arg, tolerance_arg) \
> ```

FYI:  the original rationale for using "forbidden" underscores was to avoid conflicts between the expansions of the macro args (i.e., what is passed in by the macro caller) and variable names in the macro code.  I should have mentioned this earlier.  Perhaps there was/is a better way to do this than the underscores.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KkBMGAbai0TqgIq3ImG:-KkBOAFzTyIiLCeJj-RC:bx8m9bj) ([raw file](https://github.com/robotlocomotion/drake/blob/1e7ec02ae8fc016a706e60dcd18f251369949c0a/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L11)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

FYI:  the original rationale for using "forbidden" underscores was to avoid conflicts between the expansions of the macro args (i.e., what is passed in by the macro caller) and variable names in the macro code.  I should have mentioned this earlier.  Perhaps there was/is a better way to do this than the underscores.
</blockquote></details>

FYI The better way to do it us to use GTest features in lieu of a macro.

If you want to stack with macro hell, you can make the names really long (e.g., `monolane_test_util_expect_geo_near_actual`), or token-paste `__LINE__` onto the names, or etc.

But really, learning how to use GTest is well worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by sherm1** [comment]
Unblocked.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KkBMGAbai0TqgIq3ImG:-KkBh4LB5sPJxEy82eDg:bmccfoq) ([raw file](https://github.com/robotlocomotion/drake/blob/1e7ec02ae8fc016a706e60dcd18f251369949c0a/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The better way to do it us to use GTest features in lieu of a macro.

If you want to stack with macro hell, you can make the names really long (e.g., `monolane_test_util_expect_geo_near_actual`), or token-paste `__LINE__` onto the names, or etc.

But really, learning how to use GTest is well worth it.
</blockquote></details>

In any case the `do{ ... }while(0)` provides a local scope so the variable names here won't conflict with anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-:-KkBhR1NRF7l9TTp0h__:bno4da8)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KkBMGAbai0TqgIq3ImG:-KkBiAgwWv8r2zfmJ0AP:b-jp6v30) ([raw file](https://github.com/robotlocomotion/drake/blob/1e7ec02ae8fc016a706e60dcd18f251369949c0a/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

In any case the `do{ ... }while(0)` provides a local scope so the variable names here won't conflict with anything.
</blockquote></details>

They do run the risk of _shadowing_ the names referred to by the `foo_arg` expressions.  Probably a compiler error would result, but not guaranteed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Comment by sherm1** [comment]
*[drake/automotive/maliput/monolane/test/monolane_test_utils.h, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6020#-KkBMGAbai0TqgIq3ImG:-KkC-4ZBu61LXN-5Y187:b-g0t8ju) ([raw file](https://github.com/robotlocomotion/drake/blob/1e7ec02ae8fc016a706e60dcd18f251369949c0a/drake/automotive/maliput/monolane/test/monolane_test_utils.h#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

They do run the risk of _shadowing_ the names referred to by the `foo_arg` expressions.  Probably a compiler error would result, but not guaranteed.
</blockquote></details>

Oh, good point. I hadn't though of those arguments as expressions. Then ugly names would be best.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6020)*

**Pull request merged**
