### PR TITLE
Update and move FindMatlab

### PR DESCRIPTION
**Pull request by billhoffman**
This commit updates FindMatlab to match what will be in upstream cmake.
It also moves the files out of the cmake submodule into the drake
cmake directory.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3339)

### CODE REVIEW

**Comment by billhoffman** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
You can also remove the cmake submodule. Nothing is left there that we use.

**Comment by billhoffman** [comment]
@jamiesnape git grep seems to say something different:
```
drake/CMakeLists.txt:include(../cmake/config.cmake)
drake/CMakeLists.txt:include(../cmake/pods.cmake)
drake/CMakeLists.txt:include(../cmake/mex.cmake)
drake/CMakeLists.txt:include(../cmake/procman.cmake) 
```

**Comment by jamiesnape** [comment]
The submodule is drake/cmake/.

**Comment by jamiesnape** [comment]
See #3185 and #3190.

**Comment by billhoffman** [comment]
OK, I think I will leave that as a separate PR after I get FindMatlab working and upstreamed in CMake.

**Comment by billhoffman** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
Superseded by #3586.

**Pull request closed without merging**
