### PR TITLE
[doc,geometry,multibody] Add refs to Hydroelastic User Guide

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #15743

The module ... it is written.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@damrongguoy for feature review.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549#-:-MvQMQct0ZHVEwdAAlnf:b-j4o4i9)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
There're lint errors, but I'll start reviewing, anyway.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549#-:-MvQYVT19BtJS4C4TxWG:b-7trxpl)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549#-:-MvQbUzS7SbtDAmxxg96:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQZAUlDZMrdF5Knd0J:-MvQZAUlDZMrdF5Knd0K:b9wv34u) (no related file):*
Since `proximity_properties.h` declares its content in `internal`, I suppose it won't show up in Doxygen, right?

---
___
*[multibody/parsing/parsing_doxygen.h, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQaSbwACCczz_kBadj:-MvQaSbwACCczz_kBadk:b-6tfoyd) ([raw file](https://github.com/robotlocomotion/drake/blob/276ca362bbd67808fddf7b805ce6bd40ba836705/multibody/parsing/parsing_doxygen.h#L388)):*
> ```objc
> 
> @see drake::geometry::ProximityProperties,
> @ref mbp_hydroelastic_materials_properties "Hydroelastic contact",
> ```

Now that we have `hug_properties` in the next line, do we still want "Hydroelastic contact" here?  I would think `hug_properties` is more direct to the point. 

Optional. Remove it?

~~ref mbp_hydroelastic_materials_properties "Hydroelastic contact",~~

I'm fine with keeping it too.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQbmjK92Lt2g_ewiBK:-MvQbmjL9tUBs1L49G_b:b-gn522) (no related file):*
I used `bazel run //doc/doxygen_cxx:build -- --serve --quick drake.{geometry,multibody}`, and it looked good.

---

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQZAUlDZMrdF5Knd0J:-MvQc2ke-H87MF9ajBf0:b-5j26f1) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Since `proximity_properties.h` declares its content in `internal`, I suppose it won't show up in Doxygen, right?
</blockquote></details>

I meant the content where this PR changes.

---

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQZAUlDZMrdF5Knd0J:-MvQcPQl7OCUrXMCzOHg:buxt9ap) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I meant the content where this PR changes.
</blockquote></details>

There is no reference to `@ref creating_hydro_reps` or `@ref hug_properties` showing up on this web page.



---

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQbmjK92Lt2g_ewiBK:-MvQdDJp3HRAfKzqUe_Q:bwm851t) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I used `bazel run //doc/doxygen_cxx:build -- --serve --quick drake.{geometry,multibody}`, and it looked good.
</blockquote></details>



---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQZAUlDZMrdF5Knd0J:-MvQdWmg0-pCo_vm3oR3:b984af8) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

There is no reference to `@ref creating_hydro_reps` or `@ref hug_properties` showing up on this web page.



</blockquote></details>

You need to click through to the individual function descriptions on that page to see the references. For example:



There is one change within the internal:: namespace. I figure that's just a freebie for people reading the code directly, and a hedge against future copy-paste.

---

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review, Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549#-:-MvQfNLa6iJcuThSCXXV:b2hrd0d)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @DamrongGuoy and @xuchenhan-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQZAUlDZMrdF5Knd0J:-MvQi__x0xtUShiIZvcn:ba9yak) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

You need to click through to the individual function descriptions on that page to see the references. For example:



There is one change within the internal:: namespace. I figure that's just a freebie for people reading the code directly, and a hedge against future copy-paste.
</blockquote></details>

I see. Thanks for the explanation!  Indeed I misunderstood which one is `internal` which one is not.

---

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549#-:-MvQltsl6zlem4hT34iP:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform) (waiting on @rpoyner-tri)

___
*[geometry/proximity_properties.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQiRfiDexF6FbWMCK-:-MvQiRfiDexF6FbWMCK0:bc9x2k6) ([raw file](https://github.com/robotlocomotion/drake/blob/98cb81bf4718e5803b879c3e97f9129828db02a0/geometry/proximity_properties.h#L57)):*
> ```objc
>        - accounting for differences between tessellated meshes and half spaces.
> 
>  For the full discussion of preparing geometry for use in the
> ```

BTW, odd line break.
___
*[geometry/proximity_properties.h, line 130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQm0XL3xD92d-mY3Yw:-MvQm0XMDk3rAcMNoWmv:b-tweupi) ([raw file](https://github.com/robotlocomotion/drake/blob/98cb81bf4718e5803b879c3e97f9129828db02a0/geometry/proximity_properties.h#L130)):*
> ```objc
> /** Overload, intended for shapes that don't get tessellated in their
>  hydroelastic representation (e.g., HalfSpace and Mesh).
>  See @ref hug_properties.  */
> ```

BTW, is "hug" short for "hydro user guide"? Took me a long while to figure that out.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: :shipit: complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform) (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[geometry/proximity_properties.h, line 130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16549#-MvQm0XL3xD92d-mY3Yw:-MvQzNblDZeucKN9mrm8:b-r2s92n) ([raw file](https://github.com/robotlocomotion/drake/blob/98cb81bf4718e5803b879c3e97f9129828db02a0/geometry/proximity_properties.h#L130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is "hug" short for "hydro user guide"? Took me a long while to figure that out.
</blockquote></details>

yeahh. :)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16549)* status: :shipit: complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
