### PR TITLE
Add SpatialInertia::PointMass()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18864)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR #18864 is work to helping resolve part of issue #18416.

**Review by mitiguy — COMMENTED** [review]
Feature review +@SeanCurtis-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-:-NP-xmPg-G8KQ8s-MW8l:b-j0fgx5)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two small editorial tweaks.

+@ggould-tri for platform review, please.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-:-NPILPFW9fZCqkxD-rK2:bg75ut7)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 129 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPIJDu2-FKbhZGGcht4:-NPIJDu2-FKbhZGGcht5:bscdhrn) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/spatial_inertia.h#L129)):*
> ```objc
> 
>   /// Creates the spatial inertia for a particle Q of mass m about a point P.
>   /// @param[in] mass mass of the single particle (i.e., the point mass).
> ```

nit: Please add `kg` units.

(In a "not a defect" way, I thought it would be worth noting that the word "mass" literally appears three times on this single line. Make of that what you will).
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPIKn7-4DTqwmDe-TD8:-NPIKn7-4DTqwmDe-TD9:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/test/spatial_inertia_test.cc#L87)):*
> ```cpp
> 
>   // Verify PointMass() with a zero position vector produces the same spatial
>   // inertia s shifting the spatial inertia from M_BBp_B to M_BBcm_B.
> ```

nit: typo



_Suggestion:_
```cpp
inertia as shifting
```

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-:-NPIzKeu63RxrEvmFSjt:bnfp4nl)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPJ1qyCEMgOzCzUCR25:-NPJ1qyCEMgOzCzUCR26:b-xdaxsq) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/spatial_inertia.cc#L23)):*
> ```cpp
>   // Ensure mass is non-negative.
>   if (mass < 0) {
>     std::string error_message = fmt::format("{}(): The mass of a particle is "
> ```

nit, author's discretion, this might be more readable reflowed.



_Suggestion:_
```cpp
    std::string error_message = fmt::format(
      "{}(): The mass of a particle is negative: {}.", __func__, mass);
```

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-:-NPKAZBP-INTDyYEVB4d:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`multibody/tree/spatial_inertia.h` line 129 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPIJDu2-FKbhZGGcht4:-NPK-oim8LsT_cXTI53R:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/spatial_inertia.h#L129)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Please add `kg` units.

(In a "not a defect" way, I thought it would be worth noting that the word "mass" literally appears three times on this single line. Make of that what you will).
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPJ1qyCEMgOzCzUCR25:-NPK0L9VBzSpw0OM3WFj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/spatial_inertia.cc#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit, author's discretion, this might be more readable reflowed.
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18864#-NPIKn7-4DTqwmDe-TD8:-NPK0aFk7J78iuuFLtKj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a013e46804966ee469524212caa17fcad59cd896/multibody/tree/test/spatial_inertia_test.cc#L87)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done.

**Pull request merged**
