### PR TITLE
Replace SetSolverResult with SetSolverId

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6514)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6514#-:-KoO0hWwi7UECcq6NgAb:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6514#-:-KoO15iqkJuFjO4B-8ZS:b-vt9vbo)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6514#-:-KoTYjkiUTPFEWtmrrER:bnfp4nl)*

**Pull request merged**
