### PR TITLE
adds draft policy on directory structure

### PR DESCRIPTION
**Pull request by RussTedrake**
@jwnimmer-tri and @david-german-tri for reviews, please.  I've tried to capture our hallway conversations.  Please feel free to edit/revise.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4455)

### CODE REVIEW

**Comment by liangfok** [comment]
I left some minor comments after a quick scan.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/doc/directory_structure.rst, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNB3BIoWSoKOgkp8R:-KYfNB3BIoWSoKOgkp8S:b-nnbqrb) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L7)):*
> ```reStructuredText
> *******************
> 
> The current directory structure in drake is organized to group functional
> ```

BTW: nit: "drake" should be "Drake".

---

*[drake/doc/directory_structure.rst, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNQsXLx1ZAF9cW0A_:-KYfNQsXLx1ZAF9cW0Aa:bt13b96) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L8)):*
> ```reStructuredText
> 
> The current directory structure in drake is organized to group functional
> components and limit dependencies.
> ```

BTW, should we add "and prevent circular dependencies" to the list?

---

*[drake/doc/directory_structure.rst, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNbRzbOZdhv3kdo7L:-KYfNbRzbOZdhv3kdo7M:b-88vntu) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L14)):*
> ```reStructuredText
> 
> All code that implements core functionality in Drake must adhere to the strict
> code standards described in these documents, and must have unit test coverage
> ```

BTW, "these documents" implies there is more than one document. Is there presently more than this one?

---

*[drake/doc/directory_structure.rst, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNu0Yp9EYH6Uj1qgR:-KYfNu0Yp9EYH6Uj1qgS:brwgq4i) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L20)):*
> ```reStructuredText
> In order to promote rapid development of research ideas within the code base,
> we allow for some exceptions to this rule for experimental code.  This includes
> any subdirectory labeled ``dev`` and directories with a special ``Readme.md``
> ```

BTW, I believe we've been calling it `README.md` (all caps).

---

*[drake/doc/directory_structure.rst, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfMN_tPXVDKqt8Pnp3:-KYfMN_tPXVDKqt8Pnp4:b-fogj0y) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L23)):*
> ```reStructuredText
> file describing the protocol for that directory.  For PRs that affect only these
> experimental directories, one feature review is sufficient; platform review is
> not required.  If build or test targets in this directory break, and the PR
> ```

BTW, to be consistent with preceding sentences, consider replacing "this directory" with "these directories".

---

*[drake/doc/directory_structure.rst, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfOMVWiQsoT5RBtXoV:-KYfOMVWiQsoT5RBtXoW:bfejppv) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L24)):*
> ```reStructuredText
> experimental directories, one feature review is sufficient; platform review is
> not required.  If build or test targets in this directory break, and the PR
> author or oncall buildcop cannot trivially resolve them, a GitHub issue will
> ```

BTW, should "oncall" be "on call"?

---

*[drake/doc/directory_structure.rst, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfMeYGZmwCM8lCftAM:-KYfMeYGZmwCM8lCftAN:b-40142l) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L37)):*
> ```reStructuredText
> 
> The ``drake/examples`` directories are logically after all of the core libraries
> in ``drake``.  ``test`` directories located throughout the code are logically last
> ```

BTW, > 80 char wide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYfOW8tsQDG_IDA5PvF:b34ds3t)*

**Comment by RussTedrake** [comment]
Liang - please edit in place

**Comment by liangfok** [comment]
Done!

---

Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/doc/directory_structure.rst, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNB3BIoWSoKOgkp8R:-KYfZmsagqlf7ESVVnZe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: "drake" should be "Drake".
</blockquote></details>

Done.

---

*[drake/doc/directory_structure.rst, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNQsXLx1ZAF9cW0A_:-KYfZrp-9TcZAOPqcyKA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should we add "and prevent circular dependencies" to the list?
</blockquote></details>

Done.

---

*[drake/doc/directory_structure.rst, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNbRzbOZdhv3kdo7L:-KYf_YZrSxzKd4jC5t9K:boaxx0m) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "these documents" implies there is more than one document. Is there presently more than this one?
</blockquote></details>

Done. I replaced it with a link to Developer Notes.

---

*[drake/doc/directory_structure.rst, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfNu0Yp9EYH6Uj1qgR:-KYf_eVIanGl9XNSw9Gi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I believe we've been calling it `README.md` (all caps).
</blockquote></details>

Done.

---

*[drake/doc/directory_structure.rst, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfMN_tPXVDKqt8Pnp3:-KYf_j4d6y93yHtRmY0B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, to be consistent with preceding sentences, consider replacing "this directory" with "these directories".
</blockquote></details>

Done.

---

*[drake/doc/directory_structure.rst, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfOMVWiQsoT5RBtXoV:-KYf_kwyqYqM9Sm_Ph7-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should "oncall" be "on call"?
</blockquote></details>

Done.

---

*[drake/doc/directory_structure.rst, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYfMeYGZmwCM8lCftAM:-KYf_nRU3xHf5Q7sc-2w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d45bebf47bbe50033fad1a92fed1e1413135ac0/drake/doc/directory_structure.rst#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, > 80 char wide.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYfa-aAoemprI1dkhFD:b-896fja)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/directory_structure.rst, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhrevn0mBHwURBDZC8:-KYhrevn0mBHwURBDZC9:b-1fzpxh) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L1)):*
> ```reStructuredText
> .. _directory_structure:
> ```

BTW I think Sphinx generates a warning when a document is not linked in any toctree.

---

*[drake/doc/directory_structure.rst, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhq-K-NyjSZwa9lpYW:-KYhq-K-NyjSZwa9lpYX:b-qljt3f) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L44)):*
> ```reStructuredText
> last in the dependency tree -- they are allowed to depend on any of the other
> directories.  For example, ``test`` code **is** allowed to use models/code from
> the ``examples`` directories to test core functionality.
> ```

What if we did "_is allowed to use models/code from the examples directories to test core functionality_, as long as that dependency is explicitly declared in the build system rules for that test."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYhpJIM3K-UL2jUnb5X:b-kmrewj)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/directory_structure.rst, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhrevn0mBHwURBDZC8:-KYhsWoZolfVgZyg3uM7:bpqgurv) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think Sphinx generates a warning when a document is not linked in any toctree.
</blockquote></details>

it is linked in the developers.rst toctree, no?  my sphinx didn't generate any warnings.

---

*[drake/doc/directory_structure.rst, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhq-K-NyjSZwa9lpYW:-KYhsd7aabMxeqwF83t6:b-31uasr) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What if we did "_is allowed to use models/code from the examples directories to test core functionality_, as long as that dependency is explicitly declared in the build system rules for that test."?
</blockquote></details>

i'm fine with that.  (please edit in place.).  But how do we explicitly declare a .urdf dependency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/directory_structure.rst, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhrevn0mBHwURBDZC8:-KYht82PuIet2qXXzYzw:b86q8v9) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it is linked in the developers.rst toctree, no?  my sphinx didn't generate any warnings.
</blockquote></details>

Oh sorry.  I didn't notice that other file in reviewable (with liangfok already marking it as reviewed, I have to remember to show-all explicitly).  Withdrawn.

---

*[drake/doc/directory_structure.rst, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhq-K-NyjSZwa9lpYW:-KYhtet8QRPP1tjiO3VK:b-wv4tji) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L44)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i'm fine with that.  (please edit in place.).  But how do we explicitly declare a .urdf dependency?
</blockquote></details>

The `data` attribute in the linked test here is one way: https://github.com/RobotLocomotion/drake/blob/b4d8da6f48ced081f50500407abece9badfff41b/drake/multibody/BUILD#L198

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/directory_structure.rst, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-KYhq-K-NyjSZwa9lpYW:-KYhuUfsxdTRinESucSz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d92a9a9f16a641fa90a464ae8f0e44dbacf2138/drake/doc/directory_structure.rst#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `data` attribute in the linked test here is one way: https://github.com/RobotLocomotion/drake/blob/b4d8da6f48ced081f50500407abece9badfff41b/drake/multibody/BUILD#L198
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYnb19WfjcC9C9Mg2AN:bnfp4nl)*

**Comment by david-german-tri** [comment]
Could I ask that no one merge this for a little bit?  Reviewable seems to have stopped enforcing the "curate commits before merging" label and I'd like to use this PR to debug.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYnbAHymuSe5z-cXXRb:b-197w67)*

**Comment by david-german-tri** [comment]
> Reviewable seems to have stopped enforcing the "curate commits before merging" label

OK, fixed.  I'll leave this for @russtedrake to squash and merge, since others have pushed changes to the branch.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4455#-:-KYnbv7ZNw5zfOZMThS2:bkxgwr9)*

**Comment by david-german-tri** [comment]
Russ said f2f this was ready to go, so I'll squash and merge.

**Pull request merged**
