### PR TITLE
[tools] Improve release tooling for wheels

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Launch the wheel jobs prior to finalizing the tagging

Teach download_release_candidate to download and check the wheels.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050#-:-NDiOjdp8Tsi2pGtGqVK:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with question about script uploading stuff, nice!

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050#-:-NDigOZQCGRkFa0Apqgn:b66o4e7)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`doc/_pages/release_playbook.md` line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18050#-NDiftEo1T_NQIE-KQ33:-NDiftEp3xX-fvV2ZPUb:b9rtafm) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5d1d1f50e1dda355c78a2db69254b0348c95ba/doc/_pages/release_playbook.md#L198)):*
> ```Markdown
> 1. Nagivate to the web page for the two Jenkins wheel builds you launched
>    above, under the "Launch the wheel staging builds ..." paragraph.
> 2. Open the "Console Output" and scroll to the bottom to
> ```

My understanding is that script will download wheels to local machine; however, this wants the user to re-download them.

Why can't we direct users to the tmp dir the script downloads them to?
___
*[`doc/_pages/release_playbook.md` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18050#-NDigDfqATy8srBj0uzy:-NDigDfr7WR7eRDanGa_:b-256wnb) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5d1d1f50e1dda355c78a2db69254b0348c95ba/doc/_pages/release_playbook.md#L204)):*
> ```Markdown
>    - One wheel file for macOS.
>    - Three wheel files for Ubuntu (3.8, 3.9, 3.10).
> 4. Run ``twine upload a.whl b.whl c.whl (etc)``, replacing the ``a.whl``
> ```

nit Can we provide more explicit glob that people could just copy and paste? e.g.
```
twine upload /tmp/drake_release/v1.N.0/*.whl
```
___
*[`tools/release_engineering/download_release_candidate.py` line 183 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18050#-NDifZJyD1KCmlerlsdg:-NDifZJyD1KCmlerlsdh:b8go3ti) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5d1d1f50e1dda355c78a2db69254b0348c95ba/tools/release_engineering/download_release_candidate.py#L183)):*
> ```Python
>     action = parser.add_mutually_exclusive_group(required=True)
>     action.add_argument(
>         "--find-git-sha", action="store_true",
> ```

BTW Do we care if we consistently use `--two_words` (bazel-ish) or `--two-words` (posix-ish)?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[`doc/_pages/release_playbook.md` line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18050#-NDiftEo1T_NQIE-KQ33:-NDiiZzc-VOnKx4YAGzC:bh0l3k3) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5d1d1f50e1dda355c78a2db69254b0348c95ba/doc/_pages/release_playbook.md#L198)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My understanding is that script will download wheels to local machine; however, this wants the user to re-download them.

Why can't we direct users to the tmp dir the script downloads them to?
</blockquote></details>

Oops.   That was the whole point here and I failed to finish updating the docs.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18050)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`doc/_pages/release_playbook.md` line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18050#-NDiftEo1T_NQIE-KQ33:-NDj8ZAD9WHxoM07lFHJ:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5d1d1f50e1dda355c78a2db69254b0348c95ba/doc/_pages/release_playbook.md#L198)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.   That was the whole point here and I failed to finish updating the docs.
</blockquote></details>

OK Sweet, thanks!

**Pull request merged**
