### PR TITLE
Add LCM types for point, orientation, pose, header and pose_stamped

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6155)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@siyuanfeng-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklL9EtIl8NRynyHy7o:b-jqru8h)*

**Comment by siyuanfeng-tri** [comment]
I believe the bot_core equivalent doesn't really provide the information Hashimoto san needs, hence the PR.  
The pr looks fine to me. On the other hand, I'd like to loop in more people @jwnimmer-tri @manuelli @russtedrake @sammy-tri @naveenoid. 

There are a couple high level questions that I don't know the answer to.
0) How much drake code should be dependent on any particular lcm messages, are lcm message def first class citizen? 
1) If so, this PR is the first step towards formalizing lcm message def within in drake, especially for primitive types. A good start to is to mimic ros' messages. 

My hunch is that the answer to 0 is no. In the idealized world, drake is an external library in some bigger project, which has there own transport / message def. This seems to be the cleanest way. However, since there is no clear ETA on when that's going to happen, we are semi-randomly dumping intermediate messages in drake/lcmtype, and / or pulling bot_core / robotlocomotion. The current situation is far from ideal, and clearly somewhat chaotic. 

If we want 0 and 1, I need to spend some time clean up the current code base. It also means that we need to replicate robotlocomotion_types to truly get rid of external dependencies. Ideally, we also need to provide various translator to / from lcm messages. 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklM5wad7nIBklm9do_:b-b5fagp)*

**Comment by kunimatsu-tri** [comment]
Thank you for your comment, siyuan.

> 0) How much drake code should be dependent on any particular lcm messages, are lcm message def first class citizen?

My first hope was having well-defined and widely-used common lcmtypes somewhere close to LCM library itself outside Drake (like ROS), but this is not the case for LCM.

My second hope was putting my new lcmtypes to somewhere common in local community e.g. bot_core_lcmtypes or https://github.com/RobotLocomotion/lcmtypes, but bot_core_lcmtypes are not well-defined and robotlocomotion_lcmtypes already depend on bot_core.

So, I was no choice other than putting these to Drake's lcmtypes where I think it's relatively safe. One of the lcmtypes here is also depending on bot_core, but it looks easier to get rid of it than those of robotlocomotion_lcmtypes.

I seriously think the current messy condition is going to be problematic, because the pollution easily spreads and that makes replacing lcmtypes harder and harder as time goes by.

Again, I'm OK to depend on external lcmtypes. My concern is simply those are not well-defined.

> Ideally, we also need to provide various translator to / from lcm messages.

Yes, I totally agree. Unless we provide these functionalities, we won't be able to get rid of bot_core dependency in Drake since outside Drake is uncontrollable to us.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklQWToHLQuzZf9JEDj:b6dei8t)*

**Comment by sammy-tri** [comment]
My first thought would have been to put these into RobotLocomotion/lcmtypes instead of drake/lcmtypes since it seems like they could be generally useful outside of drake specifically.

I agree the scope of that repository is not well defined.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklqrAHhQbd5_nOydAt:b-dsb48y)*

**Comment by manuelli** [comment]
I think it's great to standardize the lcm types. I think we have lots of very similar and/or overlapping lcmtypes at the moment so making a standard set would be a good direction to go.

I would vote for having them live in a separate repository, either RobotLocomotion/lcmtypes or a new repo, i.e. drake-lcmtypes. The logic being that if I want to use drake as a library (maybe I am using a drake binary) and I want to interact with some drake program that consumes lcm then I should have access to those lcmtypes without necessarily having to build drake from source as part of my project.

**Comment by kunimatsu-tri** [comment]
I agree that having lcmtypes repository separated from Drake in general.

However, again, the reason I didn't put this PR to RobotLocomotion/lcmtypes is that some lcmtypes there are dpending on bot_core: https://github.com/RobotLocomotion/lcmtypes/search?utf8=%E2%9C%93&q=bot_core&type= which is I think bad idea.

If those dependencies on bot_core_lcmtypes in RobotLocomotion/lcmtypes would be removed in near future, I'm ok to move to RobotLocomotion/lcmtypes . Otherwise, I really really hesitate to do so.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklsPJXBcBZ27AhqZXI:b-sb0m77)*

**Comment by sammy-tri** [comment]
I think the only way that RobotLocomotion/lcmtypes is going to stop depending on bot_core_lcmtypes is if we duplicate the types it uses a third time (`position_3d_t` (which drake/lcmtypes also uses) and `robot_state_t`, the latter of which even more stuff).  This might be harmless?  I guess the other option would be to port those types to use the primitives in this PR which would require director to update for compatibility...  which would probably be fine if a bit of a headache. 

I guess I'm not clear on why the dependency on bot_core_lcmtypes is problematic.  Is it just that the collection seems too random?  It doesn't feel any more arbitrary than the contents of drake/lcmtypes or RobotLocomotion/lcmtypes to me.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklvA6XfC0DM3dHmtNu:bh1opc7)*

**Comment by kunimatsu-tri** [comment]
Thanks sammy for the suggestions.

I don't want to duplicate position_3d_t because that's one of the things I want to change.  And, yes it is a headache to modify all the codes which are using bosition_3d_t and robot_state_t.  That's why I chose Drake's lcmtypes directory.

> I guess I'm not clear on why the dependency on bot_core_lcmtypes is problematic.

It's simply because bot_core_lcmtypes are not well-defined (= not polished well). For example,

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_pose_t.lcm>pose_t</a> contains much more information than the meaning of "pose".

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_position_3d_t.lcm>position_3d_t</a> sounds like 3D position, but it is actually 6D pose.

- In the comment of <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_vector_3d_t.lcm>vector_3d_t</a>, it says "When defining new types don't used this type", but it's used in some bot_core_lcmtypes already including position_3d_t.

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_images_t.lcm>images_t</a>'s image_types are just messy. It's mixing pixel format, compression, and camera type. All of the information should be defined in image_t instead of images_t.

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_rigid_transform_t.lcm>rigid_transform_t</a> contains very similar information to position_3d_t, but defined very differently. This is confusing.

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_utime_t.lcm>utime_t</a> is defined, but not used by other lcmtypes at all. And lacking the way to standardize timestamp and frame information (like lcmt_header in this PR). Basically, all the lcmtypes related to sensor output must have header information, otherwise we won't be able to know at what frame it's data is obtained.

- <a href=https://github.com/openhumanoids/bot_core_lcmtypes/blob/99676541398749c2aab4b5b2c38be77d268085cc/lcmtypes/bot_core_force_torque_t.lcm>force_torque_t</a> sounds like generic type, but this is actually robot specific type. Also, I don't understand why six_axis_force_torque_t.lcm or six_axis_force_torque_array_t.lcm are not used inside the force_torque_t?

I guess these lcmtypes were created in a hurry for DRC or other demos. I understand that, but I want everyone to understand the pain I have here.. It's time to leave from bot_core_lcmtypes.


I'm aware that position_3d_t is used also in drake/lcmtypes, but that's the only one and it looks easy replacement.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KklzFWXQAaBLAhrGIv6:b-abtiux)*

**Comment by manuelli** [comment]
Ok that makes sense Kunimatsu. I understand that bot_core is a mess and not having frame information in the sensor messages does seem problematic. I think the main pain point is probably going to be updating director to use the new types if that's something that is desired. Specifically the types related to sensor output. Maybe @patmarion has some thoughts.

**Comment by siyuanfeng-tri** [comment]
Alright, it seems that we all want a nice self contained lcm message repo, at least for the primitive data types. I think this PR is a good step towards that direction. 
The main pain points are 1. what do we do about everything else in the world (i.e. director) 2. where to put these new lcm stuff.

I don't know for 1. 
For 2, I'd suggest we put them in drake/lcmtypes for now, but use a different package, drake.common or something like that. When the time comes, it would be easier to separate these into their own repo. What do you think? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkmDtY6Ia6kFRatEw0d:b-s0nm5g)*

**Comment by manuelli** [comment]
I would separate them into their own repo from the getgo. That way it's easy to create standalone drivers for sensors that use these types. Also we can create a director branch that updates to the new types.

**Comment by siyuanfeng-tri** [comment]
So same setup as bot_core? in external? What should we call it? drake_basic_lcmtypes? 
Now I am confused about what's supposed to be in drake/lcmtypes...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkmGSCsS7U274aNUony:bvxvl2f)*

**Comment by kunimatsu-tri** [comment]
Probably, the first thing is to investigate how widely RobotLocomotion/lcmtypes which depends on bot_core_lcmtypes are used. If it's influence is not so large, then just 1) moving this PR to RobotLocomotion/lcmtypes and 2) removing bot_core dependency solve our problem.

My question is how we can investigate such a thing? Just searching in RobotLocomotion github is enough? Is there any other software that might be using RobotLocomotion/lcmtypes ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkmH7JafXT_-u6-5ecW:bgzek5e)*

**Comment by siyuanfeng-tri** [comment]
director speaks in bot_core. So if you change RobotLocomotion/lcmtypes, we need to update director. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkmKZx4nGLmhpGNwop2:bv13zbv)*

**Comment by kunimatsu-tri** [comment]
I know that director is depending on bot_core. My quick grep search gave me this result:

```
unimatsu@kunimatsu-HP-Z640-Workstation:~/work/director[master]$ grep -r robotlocomotion src/
src/python/tests/CMakeLists.txt:# need this special case until robotlocomotion/lcmtypes are added to openhumanoids
src/python/tests/testTreeViewerInterface.py:import robotlocomotion as lcmrl
src/python/director/robotplanlistener.py:    import robotlocomotion as lcmrl
src/python/director/pydrakeik.py:    from robotlocomotion import robot_plan_t
src/python/director/treeviewer.py:import robotlocomotion as lcmrl
src/python/director/drakevisualizerapp.py:# does not yet have robotlocomotion/lcmtypes
src/python/director/drakevisualizerapp.py:    import robotlocomotion as lcmrl
src/python/director/drakevisualizer.py:# robotlocomotion-lcmtypes, but drake only builds bot_core_lcmtypes.
src/python/director/drakevisualizer.py:# When drake starts using robotlocomotion-lcmtypes, then the following
src/python/director/drakevisualizer.py:#import robotlocomotion as lcmrl
src/python/director/viewerclient.py:from robotlocomotion import viewer2_comms_t
kunimatsu@kunimatsu-HP-Z640-Workstation:~/work/director[master]$ grep -r robotlocomotion distro/
distro/superbuild/cmake/externals.cmake:  ExternalProject_Add(robotlocomotion-lcmtypes
distro/superbuild/cmake/externals.cmake:    GIT_REPOSITORY https://github.com/robotlocomotion/lcmtypes
distro/superbuild/cmake/externals.cmake:    list(APPEND lcm_depends bot_core_lcmtypes robotlocomotion-lcmtypes)
```

Most of them are using lcmtypes for viewer which don't depend on bot_core. In this sense, it's manageable if I could build director.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkmLJUE7K9N--dfpCjB:b994rku)*

**Comment by patmarion** [comment]
> In the comment of vector_3d_t, it says "When defining new types don't used this type", but it's used in some bot_core_lcmtypes already including position_3d_t.

I believe this is because there was a preference toward defining messages that allowed data access as `pt[0], pt[1], pt[2]` rather than `pt.x, pt.y, pt.z`.   This is probably why `rigid_transform_t` exists.  It is a replacement for `position_3d_t` that uses indexing rather than named attributes.

I sympathize with the motivation for wanting to start fresh with a better layout.  But take caution and consider the effort level and backward compatibility headaches.

I think storing types outside of the the main project build is a wise thing to do.

**Comment by kunimatsu-tri** [comment]
Thanks Pat! I'm glad to hear from you.

> I believe this is because there was a preference toward defining messages that allowed data access as pt[0], pt[1], pt[2] rather than pt.x, pt.y, pt.z.

I don't think that is true because 1) only position_3d_t is used rather than rigid_transform_t in Drake for now (both are used in director) 2) position_3d_t was added to the repository on 2016/02/27 which is slightly later than rigid_transform_t's addition (2016/02/22).

Also, from the point of interface usability, variable name access is better than indexing unless there exists non-negligible computational performance disadvantage. This is simply because names have a clearer meaning than indices. e.g. people might be confused whether quaternion's first element is w or x in case of indexing which is not good.

> But take caution and consider the effort level and backward compatibility headaches.

Yes, thanks. I will do my best.

Please let me know if there would be any concerns from director's point of view.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkpcAhHz9C81pj8Mh81:bhj7iq3)*

**Comment by sammy-tri** [comment]
Ok, I'm sold on phasing out bot_core_lcmtypes, there's more of a mess there than I realized.  Getting rid of all of the users of robot_state_t (which depends the most on bot_core_lcmtypes of anything in RobotLocomotion/lcmtypes) would require a good bit of work in director+drake, so I don't want to block this PR on it.

I suppose the drake lcmtypes (as opposed to the rest of drake) have a minimal dependency on bot_core_lcmtypes and none on RobotLocomotion/lcmtypes.  If the idea is to preserve purity in that specific subdirectory then fine we can drop these new types there and clean that up.  Since drake+director will continue to depend on bot_core_lcmtypes (via RobotLocomotion/lcmtypes) until robot_state_t is cleaned up, I'm not sure what the practical advantage is of not putting these types there now.  We'll need them there eventually to clean up the other types anyway.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkpqYfnAzfN7Mj8i3JZ:b6lvgmw)*

**Comment by kunimatsu-tri** [comment]
Alright, then I will close this PR and open a new PR to RobotLocomotion/lcmtypes instead.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-KkqjICITRQ0-AIx-Fvs:b587m6m)*

**Comment by patmarion** [comment]
> I don't think that is true because 1) only position_3d_t is used rather than rigid_transform_t in Drake for now (both are used in director) 2) position_3d_t was added to the repository on 2016/02/27 which is slightly later than rigid_transform_t's addition (2016/02/22).

That's when the types were copied into the new repo.  These types have existed since before I started working on the project in 2013.  I think many are from the DARPA Urban Challenge.

**Comment by kunimatsu-tri** [comment]
I see. Thanks for the info.

I still believe using explicit variable names is better rather than indexing for this purpose because:

1) variable name access has been used yet by position_3d_t. This evidence shows it's acceptable.

2) when you do some computations, the most likely use case is first to convert lcm messages to other types like vtkMatrix, Eigen::Isometry3d whatever.  In that sense, once you write the converter, you don't need to care about the way of accessing, rather it'll give clearer meanings for readers (developers).

If there would be any concerns that I'm not aware yet, please let me know.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-Kl-W71NgWddmkLBDDPC:b-t59ktu)*

**Comment by patmarion** [comment]
I hear your points but they are personal opinion.  I think it would be hard to convince everyone that one method is better than the other method.  I don't have a strong opinion on the topic, but I tend to prefer indexing since it is more compatible, and, I will argue less error prone.  You can access values using a for loop or by passing a pointer, whereas with named fields you have to type a lot more `msg.x, msg.y, msg.z` and it's therefore I think it's easier to have copy and paste errors that are hard to notice.

**Comment by manuelli** [comment]
As evidence that it's hard to convince everyone I prefer the msg.x style access. For me it avoids confusion at the cost of being a bit more verbose. But again I don't have strong opinions either way.

**Comment by kunimatsu-tri** [comment]
I agree that it's hard to convince everyone.

I'd like to share this saying with you guys:

"Code is read much more often than it is written, so plan accordingly"

https://blogs.msdn.microsoft.com/oldnewthing/20070406-00/?p=27343/

My belief is coming from this spirit. So, in that sense, it's not my personal opinion, rather it's widely accepted concept I think?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-Kl-hjOa2AFEcI_ltkxK:b-kkdzkr)*

**Comment by patmarion** [comment]
Yes, readable code is very important.  I think both styles are readable.

ROS messages declare the quaternion fields in [x, y, z, w ordering](http://docs.ros.org/kinetic/api/geometry_msgs/html/msg/Quaternion.html).  Your LCM type declares the quaternion fields with w, x, y, z ordering.  So to a reader, which one is the most readable:

`Eigen::Quaterniond(msg.quat.x, msg.quat.y, msg.quat.z, msg.quat.w)`

or

`Eigen::Quaterniond(msg.quat.w, msg.quat.x, msg.quat.y, msg.quat.z)`

or

`Eigen::Quaterniond(msg.quat)`

I would argue that the last one is more readable, but to a reader none of these forms are obviously correct, the only way to verify is to read the docs of the Eigne::Quaternion constructor.

**Comment by kunimatsu-tri** [comment]
Thank you for showing good examples!

In the first and second examples, readers have to read Eigen's document here: https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html#a1d3761ef35c66dd7bbe423dc0b018a83
and got to know No.1 is wrong, No.2 is correct.

while the third example, the readers have to read both Eigen's document and lcmtype's document.

Also, how can you know in what order the elements of quaternion are stored e.g. (x, y, z, w) v.s. (w, x, y, z) in the case of indexing if there is no comment like this:
https://github.com/RobotLocomotion/lcmtypes/blob/master/lcmtypes/viewer_geometry_data_t.lcm ?

That's the major pain point of indexing!

So to answer to your question, the most readable one is No.1 or No.2 (although No.1 is wrong but you can easily notice it).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-Kl-rD2YoqGCGKaL7CLQ:b-px7div)*

**Comment by kunimatsu-tri** [comment]
(To be fair, the reader has to read both lcmtype's and Eigen's docs in either example though if they don't know that lcmtype is variable name access or indexing access.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-Kl-wNgicPBQT6SUkTTn:b-klxgh4)*

**Comment by patmarion** [comment]
I agree,  double quaternion[4] is quite ambiguous, i'm not defending that.  My point was just that, whether or not your quaternion type uses fields or an array, you often interact with apis that use positional arguments, so you still have an ordering problem.  Even if your type uses fields, you will often see users writing code like this:

```
double pt[3] = {msg.x, msg.y, msg.z};
```

So my only point was that using fields doesn't totally solve the problem.  It's very easy to make typos like this:

```
double pt[3] = {msg.x, msg.y, msg.y};
```

**Comment by kunimatsu-tri** [comment]
I see your point, but I think that's why we are writing unit tests despite the fact that it's not fun ;)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6155#-:-Kl0-O-qlnMpuoyqr-5A:bii4vo3)*

**Pull request closed without merging**
