### PR TITLE
pydrake: Add repr for RotationMatrix, RigidTransform

### LINKED ISSUE #13987: pydrake doc's default arguments have memory hex addresses
A few places in our generated docs have hex memory addresses from `__str__` or `__repr__` embedded in the API signature:
- [FiniteHorizonLinearQuadraticRegulator](https://drake.mit.edu/pydrake/pydrake.systems.controllers.html#pydrake.systems.controllers.FiniteHorizonLinearQuadraticRegulator)
- [RgbdSensor](https://drake.mit.edu/pydrake/pydrake.systems.sensors.html?r#pydrake.systems.sensors.RgbdSensor.__init__)
- [RegionOfAttraction](https://drake.mit.edu/pydrake/pydrake.systems.analysis.html#pydrake.systems.analysis.RegionOfAttraction)
- etc.

It's usually from pybound C++ structs that don't have good `__str__` or `__repr__`.

We should make the objects print correctly, so the docs don't have line noise.  (The line noise churns our deployment diffs, also.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13987.  Relates #8586.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI would you like to weigh in here?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: feature with some minor BTWs!
+@seancurtis-tri for platform review, please!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993#-:-MZmAVQ2C_vuy0uspN50:b-fzot1o)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmAC9s4GYTm75eWCq2:-MZmAC9s4GYTm75eWCq3:b-9vzzm2) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ca13bf4ed7d45b217633125d37f962a31cbaa/bindings/pydrake/_math_extra.py#L51)):*
> ```Python
> def _rotation_matrix_repr(R):
>     M = R.matrix().tolist()
>     M0 = repr(M[0]).replace("\n", "\n  ")
> ```

BTW Objective for `.replace(...)` initially unclear; consider commenting `# Simple alternative to textwrap.indent().`

Or make a small func `_psuedo_indent()`, that does this, given that you use this spelling in 5 places.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmAC9s4GYTm75eWCq2:-MZm_ddp1YHaoi28bq6r:b-u926ju) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ca13bf4ed7d45b217633125d37f962a31cbaa/bindings/pydrake/_math_extra.py#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Objective for `.replace(...)` initially unclear; consider commenting `# Simple alternative to textwrap.indent().`

Or make a small func `_psuedo_indent()`, that does this, given that you use this spelling in 5 places.
</blockquote></details>

Working I'll look into how I can clarify this.

Note that it's not `textwrap.indent` though -- we leave the first and last lines unchanged.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmAC9s4GYTm75eWCq2:-MZmaVnz4klM1T0V7Uao:bog78n8) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ca13bf4ed7d45b217633125d37f962a31cbaa/bindings/pydrake/_math_extra.py#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working I'll look into how I can clarify this.

Note that it's not `textwrap.indent` though -- we leave the first and last lines unchanged.
</blockquote></details>

Yup yup, perhaps just clarify w/ comment?

Alternatives:
- Update your template to not indent first line, then `textwrap.indent` is usable in that case
- Do something silly like `indent(blurb).lstrip()`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmAC9s4GYTm75eWCq2:-MZmaxzG4cUlEzy0LcE9:bw6l7ym) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ca13bf4ed7d45b217633125d37f962a31cbaa/bindings/pydrake/_math_extra.py#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup yup, perhaps just clarify w/ comment?

Alternatives:
- Update your template to not indent first line, then `textwrap.indent` is usable in that case
- Do something silly like `indent(blurb).lstrip()`
</blockquote></details>

Done.

Option 1 doesn't work with `R={R}`.

The helper function seemed clear enough.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmAC9s4GYTm75eWCq2:-MZmrRmEBSs2VSuSpSxf:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/8f4ca13bf4ed7d45b217633125d37f962a31cbaa/bindings/pydrake/_math_extra.py#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

Option 1 doesn't work with `R={R}`.

The helper function seemed clear enough.
</blockquote></details>

OK Thanks!
___
*[bindings/pydrake/_math_extra.py, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZmrV1T8QHWO0OfAICr:-MZmrV1T8QHWO0OfAICs:bxma4fe) ([raw file](https://github.com/robotlocomotion/drake/blob/b7bb8a469809ee12c8268b0d3f4dcaf3e9a5aa46/bindings/pydrake/_math_extra.py#L50)):*
> ```Python
> 
> def _indented_repr(o):
>     """Returns repr(o), with any lines beyond the first one indendented +2."""
> ```

BTW "indendented" => "indented"

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Review by SeanCurtis-TRI — COMMENTED** [review]
Quick question about `__repr__` vs #14699.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993#-:-MZns2D_4jVR82wBvtTk:bvtawe3)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_math_extra.py, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnqxdg0Cgj_DY0-OyL:-MZnqxdg0Cgj_DY0-OyM:b-ychovt) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L67)):*
> ```Python
>     return (
>         "RigidTransform(\n"
>         f"  R={_indented_repr(X.rotation())},\n"
> ```

I'm unsure how to reconcile this choice with issue #14699 and pr #14910.  Is it that that is more a `__str__` concept and this is `__repr__`? Or pure C++ vs python? Or do we need to still make an effort to reconcile them?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnqxdg0Cgj_DY0-OyL:-MZntAcU4yXYTJ7KEnUy:b-en5le2) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L67)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm unsure how to reconcile this choice with issue #14699 and pr #14910.  Is it that that is more a `__str__` concept and this is `__repr__`? Or pure C++ vs python? Or do we need to still make an effort to reconcile them?
</blockquote></details>

https://docs.python.org/3.6/reference/datamodel.html#object.__repr__

The #14699 could / would / should be bound for `str()`.  The ideal choice for `repr()` is such that `eval(repr(o)) == o`, so it has to be more detailed than might be wanted for str, and must use the Python typenames, kwarg names, etc.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnvTt0COvnsAII89Gf:-MZnvTt0COvnsAII89Gg:brbylqq) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L66)):*
> ```Python
> def _rigid_transform_repr(X):
>     return (
>         "RigidTransform(\n"
> ```

Hmm.  I just realized that the scalar type suffix here is wrong.  I need to improve the tests.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_math_extra.py, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnqxdg0Cgj_DY0-OyL:-MZnv_Xy3aDpbC_Avc8z:bqwe36w) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://docs.python.org/3.6/reference/datamodel.html#object.__repr__

The #14699 could / would / should be bound for `str()`.  The ideal choice for `repr()` is such that `eval(repr(o)) == o`, so it has to be more detailed than might be wanted for str, and must use the Python typenames, kwarg names, etc.
</blockquote></details>

I'd considered that. We do have a `RigidTransform` constructor that takes rpy = blah, blah, blah. So, if we went that route, the `eval` would work and they'd match.

(However, as someone who does *not* think in terms of rpy, I'm perfectly content to not have it here.  :D)

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/_math_extra.py, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnqxdg0Cgj_DY0-OyL:-MZnw2Jq2vGqx3SRupam:b-e2lc13) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L67)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd considered that. We do have a `RigidTransform` constructor that takes rpy = blah, blah, blah. So, if we went that route, the `eval` would work and they'd match.

(However, as someone who does *not* think in terms of rpy, I'm perfectly content to not have it here.  :D)
</blockquote></details>

To my understanding, going to from R=>rpy=>R doesn't guarantee a bit-identical rotation matrix -- or does it?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_math_extra.py, line 67 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnqxdg0Cgj_DY0-OyL:-MZnwjTU7rM2jdmID_Rz:baebdol) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To my understanding, going to from R=>rpy=>R doesn't guarantee a bit-identical rotation matrix -- or does it?
</blockquote></details>

I'd be surprised if it were bit identical. So, from that perspective, I'm good with just dumping the rotation matrix.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_math_extra.py, line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnvTt0COvnsAII89Gf:-MZnwzMe48fKJDeRz-kj:b2pijm2) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  I just realized that the scalar type suffix here is wrong.  I need to improve the tests.
</blockquote></details>

Oh yeah, that too.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_math_extra.py, line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnvTt0COvnsAII89Gf:-MZnxPnF4MvSDv5wtCpc:bkf3syv) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oh yeah, that too.
</blockquote></details>

FWIW `type(X).__name__` should do what you want.

**Review by jwnimmer-tri — COMMENTED** [review]
(Please re-affirm the reviews, now that I've changed the code a bit.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993#-:-MZo1SUd77QsI-LnHe9p:b-esntgh)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[bindings/pydrake/_math_extra.py, line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZnvTt0COvnsAII89Gf:-MZo1QS_52ekapzbL68O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f005abed7099e298a1689ec6284caa8732489328/bindings/pydrake/_math_extra.py#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW `type(X).__name__` should do what you want.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993#-:-MZo3asN6tl071Ys__Ru:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo4_jh1jeNlWf_1fob:b-3ihdma) (no related file):*
Working: Confirming default args on Sphinx doc generation (timeboxing to ~5min)

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo5gpREYEBxe-OTdvC:b-24d0z5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Confirming default args on Sphinx doc generation (timeboxing to ~5min)
</blockquote></details>

The line breaks seem to be not-ideal, in the docs.  Is there a convention for line breaks in reprs or not?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo6bvOAIG3Tt91Ks9J:b-4w5blb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The line breaks seem to be not-ideal, in the docs.  Is there a convention for line breaks in reprs or not?
</blockquote></details>

FYI I'm using http://127.0.0.1:8000/pydrake/pydrake.multibody.plant.html#pydrake.multibody.plant.MultibodyPlant_.MultibodyPlant_[float].WeldFrames as one example from Sphinx where this is in play.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo6TwJCUjW0AP1x92_:bcbh93u) (no related file):*
Not sure TBH; and yeah lol, using the same.
Lemme try my hand at some quick google/stackoverflow/ddg-fu

For others:

```
$ git fetch upstream pull/14993/head
$ git checkout FETCH_HEAD
$ bazel run //doc:build -- --serve pydrake.multibody.plant
```

`{base}/pydrake/pydrake.multibody.plant.html?#pydrake.multibody.plant.MultibodyPlant_.MultibodyPlant_[float].WeldFrames`
Old:
> 
New:
> 

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo7C1Y4ey0s88p7jFy:bac96mn) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not sure TBH; and yeah lol, using the same.
Lemme try my hand at some quick google/stackoverflow/ddg-fu

For others:

```
$ git fetch upstream pull/14993/head
$ git checkout FETCH_HEAD
$ bazel run //doc:build -- --serve $(echo "^C
$ git fetch upstream pull/14993/head^C
$ baze^Ctest --config=lint ...
$ bazel run //doc:build -- --serve pydrake.multibody.plant
```

`{base}/pydrake/pydrake.multibody.plant.html?#pydrake.multibody.plant.MultibodyPlant_.MultibodyPlant_[float].WeldFrames
Old:
> 
New:
> 
</blockquote></details>

I could spend about ~15-30min tomorrow hacking w/ our Sphinx plugins to try and smooth it over, if you'd like?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo7Ree1h281VP2ne_E:b-phrsgv) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I could spend about ~15-30min tomorrow hacking w/ our Sphinx plugins to try and smooth it over, if you'd like?
</blockquote></details>

I'm also totes fine with it as-is; we can always tackle it as follow-up PR, as I believe this is strictly better than hex-address garbage.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo7fPK4aX68mTyk8du:bp0uwzl) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm also totes fine with it as-is; we can always tackle it as follow-up PR, as I believe this is strictly better than hex-address garbage.
</blockquote></details>

I am content to wait, since this is not terribly urgent.  I'm also content to capture some ground and improve more later.

I think the most important thing in my mind is to decide what we _want_ to see here when we use a repr during debugging.  (I care less about the API docs; if we need to repair Sphinx there later, so be it.)

In that light, I think I'd like to understand the best practices here before we merge, in case this way is wrong.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZo9zQO8fvu04WsOPrn:b-p2202g) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am content to wait, since this is not terribly urgent.  I'm also content to capture some ground and improve more later.

I think the most important thing in my mind is to decide what we _want_ to see here when we use a repr during debugging.  (I care less about the API docs; if we need to repair Sphinx there later, so be it.)

In that light, I think I'd like to understand the best practices here before we merge, in case this way is wrong.
</blockquote></details>

Looking at `repr(np.eye(3))`, there are embedded newlines.  So my tentative proposal is that this PR is correct, and we might want to fix Sphinx later on.

A future enhancement could also be to have the `RotationMatrix` repr check for identity, and if so return the string for the default constructor, instead of printing out the whole eye.  It's probably common to have identity rotations, and compacting them could be nice.  Out of my scope for now, though.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14993)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14993#-MZo4_jh1jeNlWf_1foa:-MZoAmIR7qxa5vI3yRZn:bdqpz10) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Looking at `repr(np.eye(3))`, there are embedded newlines.  So my tentative proposal is that this PR is correct, and we might want to fix Sphinx later on.

A future enhancement could also be to have the `RotationMatrix` repr check for identity, and if so return the string for the default constructor, instead of printing out the whole eye.  It's probably common to have identity rotations, and compacting them could be nice.  Out of my scope for now, though.
</blockquote></details>

OK Sounds great to me!

---

**Comment by jwnimmer-tri** [comment]
Onward!

**Pull request merged**
