### PR TITLE
Change DrivingCommand to single acceleration

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5676)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/car_sim_lcm_common.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXCUpR59Wa2RFjJiXI:-KgXCUpR59Wa2RFjJiXJ:b-c83pq2) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/car_sim_lcm_common.cc#L204)):*
> ```cpp
>   //
>   // -------------------------------------------------
>   // Index |   kSteeringAngle   |   kAccleration
> ```

typo: `kAcceleration`

---

*[drake/automotive/test/idm_controller_test.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXDnAmPeWzjP7IwkRx:-KgXDnAmPeWzjP7IwkRy:b-5gzbxh) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L120)):*
> ```cpp
>   const double closing_accel = command->acceleration();  // A negative number.
> 
>   // Expect the car to brake in this configuration, and therefore zero throttle.
> ```

BTW, consider updating this comment to use "acceleration" instead of "brake" and "throttle".

---

*[drake/automotive/test/idm_controller_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXDa4Kdg31hfkS2QF4:-KgXDa4Kdg31hfkS2QF5:b-qsck6) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L137)):*
> ```cpp
>   dut_->CalcOutput(*context_, output_.get());
> 
>   // Expect the magnitude of the braking to be smaller when the ego is not
> ```

ditto regarding "braking".

---

*[drake/automotive/test/idm_controller_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXF_YQ72H49DTCUQce:-KgXF_YQ72H49DTCUQcf:b-2bk3f4) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L146)):*
> ```cpp
>   dut_->CalcOutput(*context_, output_.get());
> 
>   // Expect no braking or throttling (input velocity is at the desired
> ```

ditto regarding "braking" and "throttling".

---

*[drake/automotive/test/idm_controller_test.cc, line 155 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXFmD-xZqQ4ZnSSETk:-KgXFmD-xZqQ4ZnSSETl:b-9ze88w) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L155)):*
> ```cpp
>   dut_->CalcOutput(*context_, output_.get());
> 
>   // Expect a throttle input in this configuration (no brake).
> ```

ditto regarding "throttle".

---

*[drake/automotive/test/idm_controller_test.cc, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXFsnDDysscGPKeO1c:-KgXFsnDDysscGPKeO1d:b-5wwhqr) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L162)):*
> ```cpp
>   dut_->CalcOutput(*context_, output_.get());
> 
>   // Expect an enormous brake input.
> ```

ditto regarding "brake".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-:-KgXG8tNb_tdmfL9Gj4s:bl4rucz)*

**Comment by jwnimmer-tri** [comment]
Review status: 15 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/car_sim_lcm_common.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXCUpR59Wa2RFjJiXI:-KgXHHMi4PnPWajTK7FC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/car_sim_lcm_common.cc#L204)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

typo: `kAcceleration`
</blockquote></details>

Done.

---

*[drake/automotive/test/idm_controller_test.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXDnAmPeWzjP7IwkRx:-KgXHT3dvso-9YeY2-PS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L120)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider updating this comment to use "acceleration" instead of "brake" and "throttle".
</blockquote></details>

Done.

---

*[drake/automotive/test/idm_controller_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXDa4Kdg31hfkS2QF4:-KgXHX8cueThdw1cg2qj:b-fmlys3) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L137)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

ditto regarding "braking".
</blockquote></details>

I think this one correct?  We're actually braking (i.e., decelerating), even though that's not the variable name.

---

*[drake/automotive/test/idm_controller_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXF_YQ72H49DTCUQce:-KgXHjdmg7ZUO0CKlPQR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L146)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

ditto regarding "braking" and "throttling".
</blockquote></details>

Done.

---

*[drake/automotive/test/idm_controller_test.cc, line 155 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXFmD-xZqQ4ZnSSETk:-KgXHnobQmHXIOIY-MAF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L155)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

ditto regarding "throttle".
</blockquote></details>

Done.

---

*[drake/automotive/test/idm_controller_test.cc, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXFsnDDysscGPKeO1c:-KgXHymw8Uy033DvxitV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L162)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

ditto regarding "brake".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/idm_controller_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgXDa4Kdg31hfkS2QF4:-KgXIbKMwraXGybniJsL:b-hd3mey) ([raw file](https://github.com/robotlocomotion/drake/blob/dff3f4669b24e4638b4f31b988256abf7e2bf116/drake/automotive/test/idm_controller_test.cc#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this one correct?  We're actually braking (i.e., decelerating), even though that's not the variable name.
</blockquote></details>

You're right. I just wanted to avoid confusion and make it easier for readers to map the comment text with the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-:-KgXIwXzdlZlVZMRjh1F:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-:-KgZe66lTpN-41HrUSiA:bppyoqq)*

**Comment by sherm1** [comment]
Platform: :lgtm: pending a few BTWs.

---

Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/car_sim_lcm_common.cc, line 198 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZx-Dcd-L3NhIuGsmW:-KgZx-Dcd-L3NhIuGsmX:b-2ktf6l) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/car_sim_lcm_common.cc#L198)):*
> ```cpp
>   // The user's steering angle position command can be passed straight
>   // through using a gain of 1. The user's throttle and brake commands need to
>   // be multiplied by a gain of 1 / kWheelRadius and -1. / kWheelRadius to get
> ```

BTW, comment still talks about throttle and brake here.

---

*[drake/automotive/steering_command_driver.py, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZy7fpYVbqkCH6MUlV:-KgZy7fpYVbqkCH6MUlW:b-it9bkq) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/steering_command_driver.py#L22)):*
> ```Python
> from drake.lcmt_driving_command_t import lcmt_driving_command_t as lcm_msg
> SteeringThrottleBrake = collections.namedtuple(
>     'SteeringThrottleBrake', ['steering_angle', 'throttle', 'brake'])
> ```

BTW, is this right? I was expecting just acceleration now.

---

*[drake/automotive/dev/endless_road_car.cc, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZyKfG0rhUxsYCSzOi:-KgZyKfG0rhUxsYCSzOj:b-lsgoh9) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/dev/endless_road_car.cc#L153)):*
> ```cpp
>     const EndlessRoadCarConfig<T>& config) const {
> 
>   // Simplistic throttle and brake yields longitudinal acceleration.
> ```

BTW comment still says "throttle and brake"

---

*[drake/automotive/test/automotive_simulator_test.cc, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZyTr3SLx2Wis746Tg:-KgZyTr3SLx2Wis746Th:b-heb1sp) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/test/automotive_simulator_test.cc#L72)):*
> ```cpp
>   // Set full throttle.
>   DrivingCommand<double> command;
>   command.set_acceleration(9.8);  // Arbitrary large positive.
> ```

BTW doesn't look so arbitrary -- is it a coincidence that it is g-ish? 10 would look arbitrary.

---

*[drake/automotive/test/simple_car_test.cc, line 288 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZys01xwBGXLnFY-q2:-KgZys01xwBGXLnFY-q3:b-n9kk1x) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/test/simple_car_test.cc#L288)):*
> ```cpp
>   EXPECT_NEAR(-0.001 * default_params.velocity_limit_kp(),
>               result->velocity(), kTolerance);
>   // ... but not when the brake is larger.
> ```

BTW comment out of date?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-:-KgZz1q6C5yCBsGwX3L3:bhatge2)*

**Comment by jwnimmer-tri** [comment]
Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/car_sim_lcm_common.cc, line 198 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZx-Dcd-L3NhIuGsmW:-Kg_ACozDx2aJ3taPVgu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/car_sim_lcm_common.cc#L198)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, comment still talks about throttle and brake here.
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZy7fpYVbqkCH6MUlV:-Kg_AFclGrbCMA9PDiTX:b-rd8y0) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/steering_command_driver.py#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, is this right? I was expecting just acceleration now.
</blockquote></details>

Yes.  The UI is still the three elements; this program combines throttle + brake into a net acceleration when transmitting the command to the simulator.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-KgZyTr3SLx2Wis746Tg:-Kg_Afu6cGZSpzbg0SQ3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0addb0891096756b3352e64a6e9841678da502e1/drake/automotive/test/automotive_simulator_test.cc#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW doesn't look so arbitrary -- is it a coincidence that it is g-ish? 10 would look arbitrary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/BUILD, line 150 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-Kg_GO2kWZvDSiGrDVLR:-Kg_GO2kWZvDSiGrDVLS:b-cvjyga) ([raw file](https://github.com/robotlocomotion/drake/blob/8c7fb4bf2dba1f6a57c45212ec037780bc692fe0/drake/automotive/BUILD#L150)):*
> ```Python
>         ":generated_vectors",
>         ":infinite_circuit_road",
>         "//drake/math:saturate",
> ```

BTW is this used?

---

*[drake/automotive/car_sim_lcm_common.cc, line 191 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-Kg_FVWNTLsMmtWe4CVj:-Kg_FVWNTLsMmtWe4CVk:b-twhtv) ([raw file](https://github.com/robotlocomotion/drake/blob/8c7fb4bf2dba1f6a57c45212ec037780bc692fe0/drake/automotive/car_sim_lcm_common.cc#L191)):*
> ```cpp
>   // The user's steering angle position command can be passed straight
>   // through using a gain of 1. The user's acceleration command needs to
>   // be multiplied by a gain of 1 / kWheelRadius and -1. / kWheelRadius to get
> ```

BTW, I think this is slightly wrong -- isn't the acceleration command signed and thus the gain is just 1/kWheelRadius?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676)*

**Comment by jwnimmer-tri** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/BUILD, line 150 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-Kg_GO2kWZvDSiGrDVLR:-Kg_Hphix43H_TigaTIL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c7fb4bf2dba1f6a57c45212ec037780bc692fe0/drake/automotive/BUILD#L150)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this used?
</blockquote></details>

Done.

---

*[drake/automotive/car_sim_lcm_common.cc, line 191 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5676#-Kg_FVWNTLsMmtWe4CVj:-Kg_HRFcGvuzoDNsETAt:b-e47szz) ([raw file](https://github.com/robotlocomotion/drake/blob/8c7fb4bf2dba1f6a57c45212ec037780bc692fe0/drake/automotive/car_sim_lcm_common.cc#L191)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I think this is slightly wrong -- isn't the acceleration command signed and thus the gain is just 1/kWheelRadius?
</blockquote></details>

Done.

Ah, yes.  I had fixed the code but this particular comment got lost.  Sigh.  _So_ much brittle-duplicative comments in this file.  (It's scheduled for deletion though, so I'm not much worrying about it.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5676)*

**Comment by jwnimmer-tri** [comment]
:car: screech

**Pull request merged**
