### PR TITLE
Removes get_name() from sensors.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5946)

### CODE REVIEW

**Comment by liangfok** [comment]
+@kunimatsu-tri for feature review please. Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KicBKNCkRlZIGYJfS6m:bk1y2no)*

**Comment by liangfok** [comment]
Mysterious error:

```
ERROR: _bazel_ubuntu/5460cdb50e13911cc038e45ecc2ad46b/external/io_bazel_rules_go/go/toolchain/BUILD:5:1: no such package '@io_bazel_rules_go_toolchain//': no such package '@golang_linux_amd64//': Error downloading [https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz] to /.../_bazel_ubuntu/5460cdb50e13911cc038e45ecc2ad46b/external/golang_linux_amd64/go1.7.4.linux-amd64.tar.gz: Checksum was b602e62293225664b06c2eae92b73633110ada15404e9ec1309cd3648399b092 but wanted 47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b and referenced by '@io_bazel_rules_go//go/toolchain:toolchain'.
```

@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot  linux-gcc-experimental-matlab please.

**Comment by soonho-tri** [comment]
I guess the error is due to a network glitch:

```bash
wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
shasum -a 256 go1.7.4.linux-amd64.tar.gz
47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b  go1.7.4.linux-amd64.tar.gz
```

If it turns out a real problem, https://github.com/RobotLocomotion/drake/pull/5943 should fix this anyway.

**Comment by kunimatsu-tri** [comment]
Left a comment. PTAL!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KieNjI04iOzgSq3y1Aj:bhtcqhs) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
> ```objc
> 
>   /// Returns the name of this sensor. The name can be any user-specified value.
>   const std::string& get_sensor_name() const { return name_; }
> ```


The name of method is not conflicted now, but it seems the functionality is still duplicated.
Is there any reason that you want to keep this method instead of just getting rid of it?

Same comment for all the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KieOZKC_uGtc8CCREWP:b-ad6dsc)*

**Comment by liangfok** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KiePmWL9kB-clzCzfSy:bbqd3gf) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>


The name of method is not conflicted now, but it seems the functionality is still duplicated.
Is there any reason that you want to keep this method instead of just getting rid of it?

Same comment for all the changes.
</blockquote></details>

Previously I decided that a "sensor's name" is distinct from a "system's name": https://drakedevelopers.slack.com/archives/C2CHRT98E/p1481921297000126. I'm not totally confident this should be true. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KieaBZcIMnMNcU8WKoI:bxfr3q2) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Previously I decided that a "sensor's name" is distinct from a "system's name": https://drakedevelopers.slack.com/archives/C2CHRT98E/p1481921297000126. I'm not totally confident this should be true. Thoughts?
</blockquote></details>

Hmm.  I guess the reason having two different setters and getters for name is to decouple Systems's specification from SDF / URDF's specification. Is this correct?

Is there any actual problems you faced related to this?

If not, how about adding those accessors only when we face actual problems?

since this is a little bit confusing when to use `System`'s and inherited system's.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by liangfok** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KieiJQQpyJtHBBeLfjG:b-x3hble) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Hmm.  I guess the reason having two different setters and getters for name is to decouple Systems's specification from SDF / URDF's specification. Is this correct?

Is there any actual problems you faced related to this?

If not, how about adding those accessors only when we face actual problems?

since this is a little bit confusing when to use `System`'s and inherited system's.


</blockquote></details>

Yes, consider the following scenario: Suppose I have a Toyota Prius URDF that contains a forward-facing LIDAR sensor named "front_lidar_sensor". Suppose I load two instances of this URDF into a simulation. If the sensor's name is the `System`'s name, the simulation will abort when`Diagram` is initialized because there will be two systems in the `Diagram` named "front_lidar_sensor".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KiejwPTix94yla1Uy4E:b-9t3zby) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, consider the following scenario: Suppose I have a Toyota Prius URDF that contains a forward-facing LIDAR sensor named "front_lidar_sensor". Suppose I load two instances of this URDF into a simulation. If the sensor's name is the `System`'s name, the simulation will abort when`Diagram` is initialized because there will be two systems in the `Diagram` named "front_lidar_sensor".
</blockquote></details>

But nobody is parsing URDF names into these fields anyway (as evidenced by the fact that only direct unit tests had to change).  Why not just delete the code until we need it?  Maybe system name meets the need and you don't know it yet, because you haven't done the integration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by liangfok** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KiekOAfQ4oipgp0tD7k:b-pav9e1) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

But nobody is parsing URDF names into these fields anyway (as evidenced by the fact that only direct unit tests had to change).  Why not just delete the code until we need it?  Maybe system name meets the need and you don't know it yet, because you haven't done the integration.
</blockquote></details>

SGTM. Will update this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-Kiekg54DsRU0m5Btw77:b-vk207s) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

SGTM. Will update this PR.
</blockquote></details>

SGTM too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/accelerometer.h, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-KieNjI04iOzgSq3y1Ai:-KifkCA9nrxyAV4ff4gH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c615901760e4ccce1b60338b1b1f9322977b9748/drake/systems/sensors/accelerometer.h#L159)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

SGTM too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KigLOx-6IathUjdtJeV:bnfp4nl)*

**Comment by liangfok** [comment]
+@ggould-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KigRdMR0sX-Kfn--4SG:b-irfx5k)*

**Comment by ggould-tri** [comment]
I don't think that the commit message matches the content of this PR.  I am adding the +(status: curate commits before merging) tag to note that you should consider rewording it.

The contents of the change seem sound -- in fact, having `get_name` be public and non-virtual was nearly guaranteed to lead to bugs in the future, so removing the non-virtual "overrides" here is a significant win in its own right.  I will lgtm this once you have considered the commit message.

---

Reviewed 3 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KijZh2CX9jbXxr7LuC2:b-xtk57p)*

**Comment by liangfok** [comment]
Oops! Great catch. Thanks. Done.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-Kijp3-kvtvFXQr0QXjB:b-moc9ky)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5946#-:-KijrRiNpDW4yWBNo_cn:bnfp4nl)*

**Pull request merged**
