### PR TITLE
Fix sign-compare warnings in plants/test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2876)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri for feature review please -- plants is a home for only loosely-related code, so there's not one author or subteam to kick this to.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2876#-:-KNCiExBWhk8tb6WulEF:1417088721)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri for platform review and merge, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2876#-:-KND9eGq290ciPEIfPhU:1417088721)*

**Pull request merged**
