### PR TITLE
Add unnamed namespace to prevent kcov issue #339

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17835)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  x2 (the change is certainly good... though I admit I don't know why it would make kcov fail).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17835#-:-NB8vU1E6DpJ4Lin2_Mr:bhvehe3)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This is a known kcov issue that we run into occasionally: see https://github.com/SimonKagstrom/kcov/issues/339.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17835#-:-NB8wSKi6MvOtCQcnRYi:b-ssbevm)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
+@russtedrake for both reviews.

**Pull request merged**
