### PR TITLE
Shave away a bit more of System1 from automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3519)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by liangfok** [comment]
+@liangfok 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-:-KS4RHaYpTSUutCKE7IL:b-gyxe3j)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-:-KS7O8XD1xOsF4nohgaA:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-:-KS7nl8lmZiCgomucFAy:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Just waiting on @liangfok review now.  Tagging DNM to remove the green button until that's completed.

**Comment by liangfok** [comment]
:lgtm: Just one BTW comment.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_simulation.h, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-KS80ZH0-Vn1zzd-A_zm:-KS80ZH0-Vn1zzd-A_zn:b-peymsi) ([raw file](https://github.com/robotlocomotion/drake/blob/78bd81bd49be273ad3ba10bbca4b82552c52188f/drake/automotive/car_simulation.h#L163)):*
> ```objc
> // TODO(jwnimmer-tri) Remove me.
> template <typename ScalarType>
> bool encode(const double& t, const DrivingCommand<ScalarType>& wrap,
> ```

BTW: nit: optional: "wrap" is such a strange name for this variable!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-:-KS81C3qqiwSOpFAdx2f:blu91d5)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_simulation.h, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3519#-KS80ZH0-Vn1zzd-A_zm:-KS81sKbpz5bErHGwicv:b2usxsy) ([raw file](https://github.com/robotlocomotion/drake/blob/78bd81bd49be273ad3ba10bbca4b82552c52188f/drake/automotive/car_simulation.h#L163)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: optional: "wrap" is such a strange name for this variable!
</details>
Yeah.  But we'll just delete it instead of fix here, and not re-trigger Jenkins.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3519)*

**Pull request merged**
