### PR TITLE
Bind images in Python.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Sorry for the delay, first step for #7753.

This binds `Image<>` in Python for commonly used `PixelType`'s.
~(Currently non-functional, but starting somewhere :) )~

~Should use #7790 once it's merged.~

\cc @gizatt @kunimatsu-tri @ChristopherSweeney

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7811)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.
+@sammy-tri for platform review, please. (Since I am scheduled for Monday.)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-:-L3FjMHonyGBxQurlAR6:bpigfdy)*

**Comment by EricCousineau-TRI** [comment]
Had gotten an error about `py` being ambiguous: 
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=937142
If this keeps up, will see if moving the `py` alias to global scope will fix things.

\cc @soonho-tri

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3FuPLFjBh0pZxWltSu:-L3FuPLFjBh0pZxWltSv:bkjwb4o) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L14)):*
> ```cpp
> #include "drake/systems/sensors/pixel_types.h"
> 
> namespace py = pybind11;
> ```

I think a solution is to remove this line? (because `drake::pydrake::py` should be already aliased)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by jwnimmer-tri** [comment]
That `namespace py = pybind11;` is in a header was a sketchy choice; that it merged to master with a "Let's try it and see what happens" was fine, but now that we see its trouble, we should go back to following GSG and not use the alias in a header.

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3FuPLFjBh0pZxWltSu:-L3Fw7X9SPWWXw3IPVWc:b-z3fw0p) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L14)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think a solution is to remove this line? (because `drake::pydrake::py` should be already aliased)
</blockquote></details>

An end-user of Drake can still have `namespace py = pybind11` in her/his code which will trigger the same problem. I think removing `drake::pydrake::py` alias is a better solution than providing a global alias `::py`. Please feel free to start a discussion on #Platform channel in Slack if you think it's worth collecting other reviewers' opinion on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by EricCousineau-TRI** [comment]
Addressed in #7818... why GCC, why?
(Though is that GCC adhering to the standard, and clang kind of side-stepping it?)

**Comment by kunimatsu-tri** [comment]
*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3Q9g5OxtzWJXQie5dY:b-1b7guy) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
> ```cpp
>           .def("size", &ImageT::size)
>           .def("resize", &ImageT::resize)
>           .def("at", [=](const ImageT* self, int x, int y, int c) {
> ```

Hmm, `at` is taking the arguments in order of `(width, height, channel)` while `get_shape` is returning `(height, width, channel)` which is counterintuitive and confusing.  And I agree that we should take`(height, width, channel)` in Python world to be consistent to the convention of Numpy. Do you want me to change `Image` class's APIs ? What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by kunimatsu-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/test/sensors_test.py, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3RO30nBfKRV6dkWLgR:-L3RO30nBfKRV6dkWLgS:b-9k26mn) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/test/sensors_test.py#L123)):*
> ```Python
>                 for ih in range(h):
>                     for ic in range(nc):
>                         assert data[ih, iw, ic] == image.at(iw, ih, ic)
> ```

BTW, is there any reason that `assert` is used instead of `assertEquals` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3TQDI-NmpPFBniXp0l:b-qsl8iq) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Hmm, `at` is taking the arguments in order of `(width, height, channel)` while `get_shape` is returning `(height, width, channel)` which is counterintuitive and confusing.  And I agree that we should take`(height, width, channel)` in Python world to be consistent to the convention of Numpy. Do you want me to change `Image` class's APIs ? What do you think?
</blockquote></details>

True - but should we look at OpenCV or any `numpy`-related image processing stuff, and see what coordinate ordering they might use for their per-pixel access in Python?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by jwnimmer-tri** [comment]
*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3TSPccPS0wqGn7CoBV:b-n7h8tc) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

True - but should we look at OpenCV or any `numpy`-related image processing stuff, and see what coordinate ordering they might use for their per-pixel access in Python?
</blockquote></details>

FYI If there any room for doubt, is there a way instead to force callers to always use named arguments (kwargs)?  To me, saying `x=` and `y=` at the call site is very cheap compared to coordinate confusions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3Tb3Qem5oI0tBonwur:b-n4dwf3) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If there any room for doubt, is there a way instead to force callers to always use named arguments (kwargs)?  To me, saying `x=` and `y=` at the call site is very cheap compared to coordinate confusions.
</blockquote></details>

Thanks! I can expose named arguments, but I'm a little tentative on always requiring them (as it makes implementation messy, or requires a decorator of sorts).

After looking around it briefly, seems like OpenCV(-Python) and scikit-image just use the matrix coordinates `(row, col, channel)` when accessing pixels:
https://docs.opencv.org/2.4/doc/user_guide/ug_mat.html#accessing-pixel-intensity-values
http://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by kunimatsu-tri** [comment]
*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3TerMVk5Dpzri-KVex:b-36c4eh) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Thanks! I can expose named arguments, but I'm a little tentative on always requiring them (as it makes implementation messy, or requires a decorator of sorts).

After looking around it briefly, seems like OpenCV(-Python) and scikit-image just use the matrix coordinates `(row, col, channel)` when accessing pixels:
https://docs.opencv.org/2.4/doc/user_guide/ug_mat.html#accessing-pixel-intensity-values
http://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions
</blockquote></details>

Yes, those (open are using `(row, col, channel)` because they are "matrices" while `drake::sensors::Image` class is "image" which seems to me that it's reasonable to take `(width, height, channel)`.  Also, I was not thinking about python wrapper when I wrote the `Image` class. Perhaps this is the right time to rethink about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by kunimatsu-tri** [comment]
*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3TfwAG7G_z_o3T0mDS:b-hhrtr7) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Yes, those (open are using `(row, col, channel)` because they are "matrices" while `drake::sensors::Image` class is "image" which seems to me that it's reasonable to take `(width, height, channel)`.  Also, I was not thinking about python wrapper when I wrote the `Image` class. Perhaps this is the right time to rethink about it.
</blockquote></details>

Oops, I meant OpenCV and scikit-image by those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3UXyhxFUZxocHbDXZn:bks3o0o) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Oops, I meant OpenCV and scikit-image by those.
</blockquote></details>

Gotcha. I think using `(row, col, channel)` would make most sense, along with having `Image` more or less represent a wrapper for a matrix (making the motivation for coordinate conventions easier to understand) - perhaps this could return a tensor with the same shape as NumPy, if `Eigen::Map<Eigen::Tensor<...>>` is actually a thing? :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/sensors_py.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3FuPLFjBh0pZxWltSu:-L3WhixXxRFoxmR_Gk8z:bd4zyn8) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L14)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

An end-user of Drake can still have `namespace py = pybind11` in her/his code which will trigger the same problem. I think removing `drake::pydrake::py` alias is a better solution than providing a global alias `::py`. Please feel free to start a discussion on #Platform channel in Slack if you think it's worth collecting other reviewers' opinion on this.
</blockquote></details>

Done. Removed global `py` and placed module code in `drake::pydrake` in lieu of #7829.

---

*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3WhuY0ifomrI-ihdq8:b-az4t2w) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Gotcha. I think using `(row, col, channel)` would make most sense, along with having `Image` more or less represent a wrapper for a matrix (making the motivation for coordinate conventions easier to understand) - perhaps this could return a tensor with the same shape as NumPy, if `Eigen::Map<Eigen::Tensor<...>>` is actually a thing? :D
</blockquote></details>

Done. For now, I have bound the same ordering as what's in `Image`.

If you want, I can change this ordering in Python, and then we can remove the shim once the C++ catches up. If we do that, I would also prefer to change the constructor ordering to `Image(height, width)` to also match `cv::Mat` (would prefer a consistent interpretation of an image as a matrix for consistency).

---

*[bindings/pydrake/systems/test/sensors_test.py, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3RO30nBfKRV6dkWLgR:-L3Wi_PCEWEiP9tLuj6F:bhc7y01) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/test/sensors_test.py#L123)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, is there any reason that `assert` is used instead of `assertEquals` here?
</blockquote></details>

Done. Oops! Had been using `pytest` in `pybind11`, had gotten confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by kunimatsu-tri** [comment]
*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3YkCeIcdDlCPBr717N:b-1ldwxd) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. For now, I have bound the same ordering as what's in `Image`.

If you want, I can change this ordering in Python, and then we can remove the shim once the C++ catches up. If we do that, I would also prefer to change the constructor ordering to `Image(height, width)` to also match `cv::Mat` (would prefer a consistent interpretation of an image as a matrix for consistency).
</blockquote></details>

I agree. Let's make that change happen. I mark this as satisfied since we agreed on the final goal. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by kunimatsu-tri** [comment]
Thanks!
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-:-L3Yn00G2HMczKdh7sJ7:bgeu3ur)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-L3Q9g5OxtzWJXQie5dX:-L3Z70or5ltJZ9Xy00_4:bshmljs) ([raw file](https://github.com/robotlocomotion/drake/blob/ed339152e83f8259bce37ec3458580ca0d5a630a/bindings/pydrake/systems/sensors_py.cc#L142)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I agree. Let's make that change happen. I mark this as satisfied since we agreed on the final goal. 
</blockquote></details>

OK Awesome! To clarify for Sammy, the intent here is to keep C++ and Python signatures the same, and change both in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811)*

**Comment by sammy-tri** [comment]
First pass complete.  Waiting on CI.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-:-L3ZWwfrbUGI_3ie7Fji:bnot52t)*

**Comment by EricCousineau-TRI** [comment]
Oops! Was a old error from `cpp_template`. Fixed it in a new commit.
(Somehow wasn't caught in CI... or it's been broken this whole time?)

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-:-L3ZhXywBVH0l_WLk01C:bmf8pb8)*

**Comment by sammy-tri** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7811#-:-L3Zv8LeGPK3mYJSqF1U:bg7igkv)*

**Pull request merged**
