### PR TITLE
Rewrite buildifier wrapper as bazel-bin/tools/lint/buildifier

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

Details:
- Add `tools/lint:find_data` and unit test.
- Add `tools/lint:util` and unit test.
- Rewrite `buildifier.sh` in python, now `bazel-bin/tools/lint/buildifier`:
  - Add explicit opt-in for `--all`.
  - Improve the command-line processing and help.
  - List out specific files that fail, instead of all.
- Port automated linting to use the new tool.
- Update docs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7175)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-:-KvbmtX6nI5_Sc_0JoZg:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm: (aside two minor suggestions)

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/bazel.rst, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvbr3Do0uOBGn0q7cnJ:-Kvbr3Do0uOBGn0q7cnK:b-83hlbf) ([raw file](https://github.com/robotlocomotion/drake/blob/399436a4ed1cffc1609a46fbbe80b6d06d0cf3b2/drake/doc/bazel.rst#L129)):*
> ```reStructuredText
> 
>   cd /path/to/drake-distro
>   bazel-bin/tools/lint/buildifier --all               # Reformat all Bazel files.
> ```

Do you think it's good to have the following line?
```bash
bazel build //tools/lint:buildifier
```

---

*[tools/lint/util.py, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-KvbzeLuIZKx5426euOu:-KvbzeLuIZKx5426euOv:b-povcdh) ([raw file](https://github.com/robotlocomotion/drake/blob/399436a4ed1cffc1609a46fbbe80b6d06d0cf3b2/tools/lint/util.py#L48)):*
> ```Python
>     for abs_dirpath, dirs, files in os.walk(workspace_root):
>         assert abs_dirpath.startswith(workspace_root)
>         rel_dirpath = abs_dirpath[len(workspace_root) + 1:]
> ```

BTW, how about the following (which might be more readable)?

```python
rel_dirpath = os.path.relpath(abs_dirpath, workspace_root)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-:-Kvc-6Z7yq1IUdyOs-qm:b-arayo6)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per rotation, please.

---

Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/bazel.rst, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvbr3Do0uOBGn0q7cnJ:-Kvc5AYGi9O-9egw8-Lq:b-1qm9q6) ([raw file](https://github.com/robotlocomotion/drake/blob/399436a4ed1cffc1609a46fbbe80b6d06d0cf3b2/drake/doc/bazel.rst#L129)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Do you think it's good to have the following line?
```bash
bazel build //tools/lint:buildifier
```
</blockquote></details>

Done, thanks for the reminder.  I'd had this text in an original draft but lost it during rebasing.

---

*[tools/lint/util.py, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-KvbzeLuIZKx5426euOu:-Kvc4S7wUiooUAivL2o8:btg4oek) ([raw file](https://github.com/robotlocomotion/drake/blob/399436a4ed1cffc1609a46fbbe80b6d06d0cf3b2/tools/lint/util.py#L48)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, how about the following (which might be more readable)?

```python
rel_dirpath = os.path.relpath(abs_dirpath, workspace_root)
```
</blockquote></details>

OK I hadn't of that, but I just tried it, and it leaves `./` at the start of all paths, which I would have to then strip off.  I would still have to keep the assertion around, so I guess I think this parallel construction is clearest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-:-Kvc5QD8cnLL4x-XZ7oY:b-83e1e5)*

**Comment by jwnimmer-tri** [comment]
FYI /CC @SeanCurtis-TRI in case you want to jump in as a user representative.  (I don't think CLion cares much about this one; in next PRs where I update cpplint and clang-format-includes similarly, I will be sure to tag you.)

**Comment by soonho-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lint/util.py, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-KvbzeLuIZKx5426euOu:-Kvc6jPH5-iEso0tZPHK:b-iuo5ro) ([raw file](https://github.com/robotlocomotion/drake/blob/399436a4ed1cffc1609a46fbbe80b6d06d0cf3b2/tools/lint/util.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I hadn't of that, but I just tried it, and it leaves `./` at the start of all paths, which I would have to then strip off.  I would still have to keep the assertion around, so I guess I think this parallel construction is clearest.
</blockquote></details>

OK. I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lint/BUILD.bazel, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvc95CNOp5bVTKR5yji:-Kvc95CNOp5bVTKR5yjj:bnl3ltz) ([raw file](https://github.com/robotlocomotion/drake/blob/e4d7eae8c6d4d4c724738a5de5d31ee02875ea9c/tools/lint/BUILD.bazel#L22)):*
> ```
> )
> 
> py_binary(
> ```

Is there a way to prevent this from being invoked via `bazel run`?  I suspect that editing bazel files from within a bazel command is hazardous.

---

*[tools/lint/find_data.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvc7SHQxkAQYcPyPaDk:-Kvc7SHQxkAQYcPyPaDl:b-ltj25m) ([raw file](https://github.com/robotlocomotion/drake/blob/e4d7eae8c6d4d4c724738a5de5d31ee02875ea9c/tools/lint/find_data.py#L1)):*
> ```Python
> """Helper for locating data=[] resources from a py_binary.
> ```

It is not clear from context that "data" and "py_binary" refer to the bazel concepts.  Mention that this is is concerning itself with Bazel lint data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lint/BUILD.bazel, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvc95CNOp5bVTKR5yji:-KvcN4cABz7ofR_zFjjb:b-cp0918) ([raw file](https://github.com/robotlocomotion/drake/blob/e4d7eae8c6d4d4c724738a5de5d31ee02875ea9c/tools/lint/BUILD.bazel#L22)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Is there a way to prevent this from being invoked via `bazel run`?  I suspect that editing bazel files from within a bazel command is hazardous.
</blockquote></details>

Done.

In 'check' and 'diff' mode we should allow it, but in other modes now we fail.

---

*[tools/lint/find_data.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-Kvc7SHQxkAQYcPyPaDk:-KvcLVpmTPKAujRNOpTZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4d7eae8c6d4d4c724738a5de5d31ee02875ea9c/tools/lint/find_data.py#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It is not clear from context that "data" and "py_binary" refer to the bazel concepts.  Mention that this is is concerning itself with Bazel lint data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 11 of 14 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-:-KvcNvkwFybXaXrLX0dx:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
FYI I'm assuming that CLion will be untouched by this.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7175#-:-KvcOkGmh_mHmNeBTSgG:b-sz79gs)*

**Comment by jwnimmer-tri** [comment]
Yeah.  And also I left a deprecation shim in place, so if you somehow see deprecation warnings, then we'll have to find what's going on.

**Pull request merged**
