### PR TITLE
[workspace] remove scipy.interpolate dependency

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #14691

There are no known examples that hit this code **and** actually validate / use it for plotting or animation.  As such I have introduced a minimal set of tests.

https://github.com/RobotLocomotion/drake/issues/14691#issuecomment-1034257884

The underactuated pendulum example in `trajopt.ipynb` will hit `elif isinstance(log, Trajectory)`.

~~Unresolved:~~

~~Can `sample_log.data()` be anything other than a 2D array?  E.g., 3D data?  There is nothing that tests for this right now.~~

Yes, we have test case for this now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
Will be shopping for a feature reviewer tomorrow.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MwTHqm-2q-VzpJAuFp0:boa7fo2)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 131 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwTI62c-npM-Ptce764:-MwTI62d87Bct-jfJZ5q:b22n9l5) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/pyplot_visualizer.py#L131)):*
> ```Python
>                 samples more consistent in time. This can be disabled if you
>                 know the draw_period passed into the constructor exactly
>                 matches the sample timestep of the log.
> ```

It could possibly be worth actually creating an example jupyter notebook that uses this with `resample=True` and plots the animation.  In the `_resample_log_interp1d_test.py` file here I just stole the `SimpleContinuousTimeSystem(VectorSystem)` class from the `pyplot_visualizer_test.py`.  Is there value in creating a simple `PyPlotVisualizer` example notebook that calls `animate()` with a vector log that gets resampled?  That would make it possible to verify the results visually before / after this change, right now I've manually tested things to compare to scipy's implementation but the tests are more or less manufactured to be "correct" without any actual basis for the expected truth values other than "that's what they are"...

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MwX_U9o2pk07rgd-wpR:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail and @svenevs)

___
*[bindings/pydrake/systems/_resample_log_interp1d.py, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwXYnyQ1u2t7NNwxmTN:-MwXYnyQ1u2t7NNwxmTO:bso1cnx) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/_resample_log_interp1d.py#L53)):*
> ```Python
>     Args:
>         log: The drake systems.primitives.VectorLog to resample.
>         timestep: The simulation timestep, used to resample log.sample_times()
> ```

Nit: Mention in the docstring that the log sample times are not required to be sorted and that the returned (times, data) will be sorted.
___
*[bindings/pydrake/systems/test/_resample_log_interp1d_test.py, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwX_FkUC_QNu2sHZfJS:-MwX_FkUC_QNu2sHZfJT:bnh8eg0) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/test/_resample_log_interp1d_test.py#L59)):*
> ```Python
> 
>         # Resample [0, .1] by step=0.03125 => 4 data points.
>         t_expected = np.array([0.0, 0.03125, 0.0625, 0.09375])
> ```

BTW have you compared these values to scipy's output?

**Review by svenevs — COMMENTED** [review]
Status remains do not merge pending internal discussion on the remaining scipy bits.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MwYKkOZ4f9YYWjX649K:brr70ae)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail)

___
*[bindings/pydrake/systems/_resample_log_interp1d.py, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwXYnyQ1u2t7NNwxmTN:-MwYJO1YAMQrqDBYj0gI:b8wkisk) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/_resample_log_interp1d.py#L53)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit: Mention in the docstring that the log sample times are not required to be sorted and that the returned (times, data) will be sorted.
</blockquote></details>

Done, good call!  I also updated the verbiage on `Returns` to explain that `(rows of t and cols of x are equivalent)` where dimensions are concerned.
___
*[bindings/pydrake/systems/test/_resample_log_interp1d_test.py, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwX_FkUC_QNu2sHZfJS:-MwYJfMuBSdkmNckKPAk:b-oybvzq) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/test/_resample_log_interp1d_test.py#L59)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW have you compared these values to scipy's output?
</blockquote></details>

OK, yes the following diff adding tests against scipy's actual return values at the bottom of `validate_resample` all succeed locally.  Note that there is a much tighter threshold for comparing to "real scipy" results of `1e-7` via `assert_allclose`'s default tolerance.  As a side note, it's worth explaining that the reduced tolerance of `1e-03` is being used for the other tests because when I printed the original values they were truncated via numpy's formatting so we lost some precision.

Putting the diff here for the record in case we introduce additional tests, while `scipy` is still a dependency this is a valuable sanity check to add back in.

```diff
diff --git a/bindings/pydrake/systems/test/_resample_log_interp1d_test.py b/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
index 9d9d893601..4594c19aae 100644
--- a/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
+++ b/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
@@ -95,3 +95,34 @@ class TestResampleLogInterp1d(unittest.TestCase):
         assert_allclose(
             x, x_expected, rtol=tolerance,
             err_msg="Resampled data are not as expected.")
+
+        # Test against original scipy values.  We must sort first, original
+        # code assumed sorted but one of our test cases deliberately reverses.
+        orig_sample_times = np.array(log.sample_times(), copy=True)
+        orig_data = np.array(log.data(), copy=True)
+        sort_indices = np.argsort(orig_sample_times, kind="mergesort")
+        orig_sample_times = orig_sample_times[sort_indices]
+        orig_data = np.take(orig_data, sort_indices, axis=1)
+        t_resample = np.arange(0, orig_sample_times[-1], timestep)
+        from scipy.interpolate import interp1d
+        x_resample = interp1d(
+            orig_sample_times, orig_data, kind="linear", axis=1)(t_resample)
+        # Verify our version and scipy give same dimensions.
+        self.assertTrue(
+            t.shape == t_resample.shape,
+            msg=(
+                f"Expected t.shape={t.shape} to match t_resample.shape="
+                f"{t_resample.shape}"))
+        self.assertTrue(
+            x.shape == x_resample.shape,
+            msg=(
+                f"Expected x.shape={x.shape} to match x_resample.shape="
+                f"{x_resample.shape}"))
+        # Verify our version and scipy give equitable results.
+        # We give a tighter tolerance bound (1e-7).
+        assert_allclose(
+            t, t_resample,
+            err_msg="Vendored impl and scipy results for t not equivalent!")
+        assert_allclose(
+            x, x_resample,
+            err_msg="Vendored impl and scipy results for x not equivalent!")
```

**Comment by RussTedrake** [comment]
fwiw -- don't worry about the change to underactuated's pendulum example.  i'm sure i can patch that up.

**Review by svenevs — COMMENTED** [review]
:LGTM: thanks @alesgenova for finishing this off and fixing the tolerance issues!

@RussTedrake sorry for missing your response, AFAICT this change should not have any affect on your pendulum example code (it does not use `VectorLog`).

+@sammy-tri for platform review (Monday) please.

For reference, if you want to verify the results locally, you can add the following diff to compare against the `scipy` code we are vendoring now:

```diff
diff --git a/bindings/pydrake/systems/test/_resample_log_interp1d_test.py b/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
index e30c76bad4..17b9c2dcd6 100644
--- a/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
+++ b/bindings/pydrake/systems/test/_resample_log_interp1d_test.py
@@ -181,3 +181,16 @@ class TestResampleLogInterp1d(unittest.TestCase):
         assert_allclose(
             x, x_expected,
             err_msg="Resampled data are not as expected.")
+
+        from scipy import interpolate
+        t_orig, x_orig = log.sample_times(), log.data()
+        f = interpolate.interp1d(
+            t_orig, x_orig, kind='linear', assume_sorted=False)
+        t_new = np.arange(np.min(t_orig), np.max(t_orig), timestep)
+        x_new = f(t_new)
+        assert_allclose(
+            t, t_new,
+            err_msg="Expected final times did not match reference solution.")
+        assert_allclose(
+            x, x_new,
+            err_msg="Expected final data did not match reference solution.")
```

> Reviewed 1 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MxGjiy02lSYL424sAS5:b-x5vfrz)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 131 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MwTI62c-npM-Ptce764:-MxGkJVQ6FlV1NXqZG9E:bi7cwen) ([raw file](https://github.com/robotlocomotion/drake/blob/8c9c39fb559befcc987187f80ea13e35735f17a1/bindings/pydrake/systems/pyplot_visualizer.py#L131)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

It could possibly be worth actually creating an example jupyter notebook that uses this with `resample=True` and plots the animation.  In the `_resample_log_interp1d_test.py` file here I just stole the `SimpleContinuousTimeSystem(VectorSystem)` class from the `pyplot_visualizer_test.py`.  Is there value in creating a simple `PyPlotVisualizer` example notebook that calls `animate()` with a vector log that gets resampled?  That would make it possible to verify the results visually before / after this change, right now I've manually tested things to compare to scipy's implementation but the tests are more or less manufactured to be "correct" without any actual basis for the expected truth values other than "that's what they are"...
</blockquote></details>

Done, I do not believe this is necessary.

**Review by sammy-tri — COMMENTED** [review]
Unfortunately I hit the end of my platform review day without being able to start this one.  -@sammy-tri +@rpoyner-tri per rotation.

Apologies!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MxabrIZ-CJDshwH6u5h:b-abi6qq)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MxeIBcm2sQuGBujYPJH:-MxeIBcm2sQuGBujYPJI:b-tfb42m) (no related file):*
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

---

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MxeIBcm2sQuGBujYPJH:-MxeoJUc0d09CzBWu698:b53j8k9) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.
</blockquote></details>

LGTM once the job finishes, I just logged into mac stadium and did some voodoo and this and a number of other mac jobs are now getting started again.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending mac build

> Reviewed 1 of 4 files at r5, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MxewLLaAgjTNIjwhBsa:bvo985h)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16592#-:-MxfAlcW3SwUeX6lvfXT:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @svenevs)

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16592#-MxeIBcm2sQuGBujYPJH:-MxfJ3Ng8Gs_SwuJL_ji:b-6fpx3g) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

LGTM once the job finishes, I just logged into mac stadium and did some voodoo and this and a number of other mac jobs are now getting started again.
</blockquote></details>

Thanks! I really dislike relying on mac stadium jobs, but our in-house macs have been replaced and are not fully configured for development yet.

---

**Pull request merged**
