### PR TITLE
Add never_destroyed.h

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The discussions in #4627 made me dust off this branch again and completely rewrite it with some new inspiration.  The old version sucked; this version I think is very nice and we should keep it around.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4628)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-:-K_2lCXdbA3Q74Np81Lx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Thanks!

+@ggould-tri for platform please sometime this week +(priority: low).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-:-K_2m1tMSMbMRZAO2jdP:b-vi7wcb)*

**Comment by RussTedrake** [comment]
fwiw -- i've got another use case for you here:
https://github.com/RobotLocomotion/drake/blob/master/drake/lcm/lcm_call_matlab.cc#L70

**Comment by ggould-tri** [comment]
One comment below.  Otherwise :lgtm_strong: 

---

Reviewed 4 of 7 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/lcm_call_matlab.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_4sZMNSs9ANbhlGRRl:-K_4sZMNSs9ANbhlGRRm:b-y36bzq) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/lcm/lcm_call_matlab.cc#L68)):*
> ```cpp
> void internal::PublishLcmCallMatlab(const drake::lcmt_call_matlab& msg) {
>   static never_destroyed<::lcm::LCM> lcm;
> ```

The text that you deleted here had a style guide reference to https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.  If we really consider adhering to the current style guide documented approach to be defective, there should be a corresponding update to our local style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-:-K_4svPCel9zkOkNU-IF:b-j9qlrd)*

**Comment by jwnimmer-tri** [comment]
*[drake/lcm/lcm_call_matlab.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_4sZMNSs9ANbhlGRRl:-K_4u6mZWBuRappUSwc2:b-mac6qm) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/lcm/lcm_call_matlab.cc#L68)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The text that you deleted here had a style guide reference to https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.  If we really consider adhering to the current style guide documented approach to be defective, there should be a corresponding update to our local style guide.
</blockquote></details>

The cppguide says "consider" a raw pointer.  I am happy to leave it to authors' discretion whether they use `never_destroyed` or a bare leaked pointer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/lcm_call_matlab.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_4sZMNSs9ANbhlGRRl:-K_4usjA6kfNk8WQZs9k:b7ld3vq) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/lcm/lcm_call_matlab.cc#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The cppguide says "consider" a raw pointer.  I am happy to leave it to authors' discretion whether they use `never_destroyed` or a bare leaked pointer?
</blockquote></details>

OK.  I guess `never_destroyed` isn't really a "smart pointer" and so is not covered by the prohibition on smart pointers for statics.  Works for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/common/never_destroyed.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-IrFYMc686keJSho:-K_5-IrGxSW0Oue-WMzn:b6at9c9) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/never_destroyed.h#L15)):*
> static initialization fiasco

I didn't find this mentioned in the cppguide (did you mean google style guide?). Or where else?

---

*[drake/common/nice_type_name.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-RXcqtUjVP0zn5vl:-K_5-RXcqtUjVP0zn5vm:b-hsski9) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/nice_type_name.h#L42)):*
> ```objc
>   the same on all platforms, using Canonicalize(). This is an expensive
>   operation but is only done once per instantiation of NiceTypeName::Get<T>()
>   for a given type `T`. The returned reference will not be deleted even at
> ```

Should this documentation change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/never_destroyed.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-IrFYMc686keJSho:-K_5-lnplUfxOQqaKdQF:bavmyxy) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/never_destroyed.h#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> static initialization fiasco

I didn't find this mentioned in the cppguide (did you mean google style guide?). Or where else?
</blockquote></details>

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables is the guide reference.  The quoted term is more of a google search keyword.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by amcastro-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/never_destroyed.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-IrFYMc686keJSho:-K_50T8vrTVO5RMkhHkS:bnb2yun) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/never_destroyed.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables is the guide reference.  The quoted term is more of a google search keyword.
</blockquote></details>

Ah, thanks. Maybe worth mentioning that link?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/never_destroyed.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-IrFYMc686keJSho:-K_50YYJPEgfWqVAxE9R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/never_destroyed.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables is the guide reference.  The quoted term is more of a google search keyword.
</blockquote></details>

Done.

---

*[drake/common/nice_type_name.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4628#-K_5-RXcqtUjVP0zn5vl:-K_5-yaUTkFVMxO42aiE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e372422d43c0298580cbfd11cb7cbccc73828567/drake/common/nice_type_name.h#L42)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Should this documentation change?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4628)*

**Pull request merged**
