### PR TITLE
Disable VTK Python bindings in wheel

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Disable VTK Python bindings for the wheel build. We don't need them in this configuration, and this allows us to shuffle around the order of setting up dependencies such that builds for different versions of Python can share a VTK build.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16199)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Comment by mwoehlke-kitware** [comment]
Confirming that the Jenkins job built VTK *then* installed Python (n.b. Docker stages 14 vs. 15-16).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16199#-:-MqVAaNs7zuHj06LiAYw:bnfp4nl)* status: 1 unresolved discussion, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/dev/Dockerfile, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16199#-MqVANLPBYywnsBiql1I:-MqVANLQ7u0O9K5C1jG2:b-dq0wmq) ([raw file](https://github.com/robotlocomotion/drake/blob/329ea73a75a94e4181f7acf69221d5d875d56579/tools/wheel/dev/Dockerfile#L53)):*
> ```Dockerfile
> 
> RUN --mount=type=ssh \
>     --mount=type=cache,target=/var/cache/bazel \
> ```

I'm not sure why this PR is removing this line?

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/dev/Dockerfile, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16199#-MqVANLPBYywnsBiql1I:-MqVHqH95TTMt10wb6B6:b308ujh) ([raw file](https://github.com/robotlocomotion/drake/blob/329ea73a75a94e4181f7acf69221d5d875d56579/tools/wheel/dev/Dockerfile#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure why this PR is removing this line?
</blockquote></details>

Ah, sorry... I had an out-of-date version open in my editor that overwrote the version in the repo, and didn't catch this when committing the changes. Thanks for noticing!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16199)* status: missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Pull request merged**
