### PR TITLE
fix names shown off-by-one in RationalForwardKinematics var names

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Found this one while debugging some of my own code.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N_V_0w62nv5_W4PpHfZ:be5vags)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N_WGRN3BbiqeT-EzPPx:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N_WGe--4G2gQqBSOj3R:b-jarjz8)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @AlexandreAmice)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N_Z53t85oYYxqvb-aau:bg7igkv)* status: missing label for release notes (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
I'd suggest a more useful commit subject -- something like `Fix wrong variable names in RationalForwardKinematics`.  Users don't cares that it's a "string format"; that's an implementation detail.

**Review by AlexandreAmice — COMMENTED** [review]
my reason to avoid that would be that `Fix wrong variable names` might imply that this is fixing a bug rather than fixing something that is purely aesthetic.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N__8MKD-slaMc-FLKqA:btxr998)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Review by ggould-tri — COMMENTED** [review]
I think the lack of an issue number makes that clear, but I've offered some intermediate text below if you like.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N__FgBT8TTQgcMbcTLb:b45qv8g)* status: 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-N__Fqi7DLTd9c8ierq1):*
nit: suggested text per above; "shown" hints that this is an aesthetic change.



_Suggestion:_
```
fix names shown off-by-one in RationalForwardKinematics var names
```

**Comment by jwnimmer-tri** [comment]
To me, grossly misleading variable names are a real bug -- an actual defect -- not just "aesthetic".

**Review by ggould-tri — COMMENTED** [review]
For whatever reason this wasn't picking up the changed message.  I am changing it and merging this manually now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19797#-:-N_iQNlc1l8RuZOhns0V:b-tp2y24)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Pull request merged**
