### PR TITLE
Added Advice on How to Handle a Build Cop Revert

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2495)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added Advice on How to Handle a Build Cop Revert
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-:-KJCLe6HUgOMLCQliuM1:-274331639)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 99 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-KJChU_99DcrG-P8sfwz:-KJChU_99DcrG-P8sfx-:680894968) ([raw file](https://github.com/robotlocomotion/drake/blob/98e2c9250957758ce9e7f00a200329f95672e7df/drake/doc/buildcop.rst#L99)):*
> ```reStructuredText
> Here's one workflow:
> 
> 1. Checkout the master branch and create a new branch off of its ``HEAD``.
> ```

How about a phrasing like `Create a new development branch based off of the HEAD of master` or similar?  The first time I read this item, I missed the "create a new branch" facet and was confused why we were reverting on master.

---

*[drake/doc/buildcop.rst, line 110 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-KJCiBc4WtqxjD5fXqu0:-KJCiBc5mWajbN_Dn0T8:1340219241) ([raw file](https://github.com/robotlocomotion/drake/blob/98e2c9250957758ce9e7f00a200329f95672e7df/drake/doc/buildcop.rst#L110)):*
> ```reStructuredText
> 4. Commit your changes into your new branch.
> 
> 5. Issue a new PR containing your fixes.
> ```

BTW Consider adding "Be sure to link to the buildcop revert PR in your new PR", so that the reviewers can properly inspect the re-submitted code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2495)*

**Comment by liangfok** [comment]
Thanks for the review! PTAL.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri for both levels of review.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/buildcop.rst, line 99 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-KJChU_99DcrG-P8sfwz:-KJCxWpY-mS5QI9zG5kA:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/98e2c9250957758ce9e7f00a200329f95672e7df/drake/doc/buildcop.rst#L99)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> How about a phrasing like `Create a new development branch based off of the HEAD of master` or similar?  The first time I read this item, I missed the "create a new branch" facet and was confused why we were reverting on master.
</details>
Done.

---

*[drake/doc/buildcop.rst, line 110 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-KJCiBc4WtqxjD5fXqu0:-KJCy00VIjxwjvYwxo6z:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/98e2c9250957758ce9e7f00a200329f95672e7df/drake/doc/buildcop.rst#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider adding "Be sure to link to the buildcop revert PR in your new PR", so that the reviewers can properly inspect the re-submitted code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-:-KJCy146bm85-Dofryl7:130873936)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks for the review! PTAL.
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2495#-:-KJD0xRfU2PSYnstHkxg:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
