### PR TITLE
Fix CMake warning flags and package versions

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7401)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7401#-:-Ky1iWhYy1BaXNqXpD7W:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7401#-:-Ky2LGcYIEkbtIe4OII7:b8qx53o)*

**Pull request merged**
