### PR TITLE
[multibody] Add internal cross-check for default contact model

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This resolves a TODO related to software upkeep, from #15826.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15861)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews, please.

**Review by sherm1 — COMMENTED** [review]
Great -- thanks! :lgtm: x 2 pending one comment

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15861#-:-Mkt8YiUEyXZCtauwY8_:bqsw7wi)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[multibody/plant/multibody_plant.h, line 4801 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15861#-Mkt8J4n2PhR8RJ5SYT0:-Mkt8J4n2PhR8RJ5SYT1:b-jca594) ([raw file](https://github.com/robotlocomotion/drake/blob/b6d24faab28c40bd31d7327a9559b1a48f9b07d3/multibody/plant/multibody_plant.h#L4801)):*
minor: I think you still want to keep the line before the TODO here.
> // Keep this in sync with the default value in multibody_plant_config.h.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15861)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

___
*[multibody/plant/multibody_plant.h, line 4801 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15861#-Mkt8J4n2PhR8RJ5SYT0:-MktET796EyMjFpD-grx:b-77ym9f) ([raw file](https://github.com/robotlocomotion/drake/blob/b6d24faab28c40bd31d7327a9559b1a48f9b07d3/multibody/plant/multibody_plant.h#L4801)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think you still want to keep the line before the TODO here.
> // Keep this in sync with the default value in multibody_plant_config.h.


</blockquote></details>

Nope, _I_ actually don't still want to keep the line here; it does not help with anything, and misleads the reader into thinking they need to manually check the correspondence.  However, from your comment I'm inferring that you think it's valuable, so I've put it back along with a disclaimer to forestall the possible confusion.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15861)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
