### PR TITLE
add numeric tolerances to test

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Amends #20317.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@BetsyMcPhail for build cop.
+@hongkai-dai for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-Ngedopo-VXyVcOzU3yd:b-yvii4e)* status: LGTM missing from assignees BetsyMcPhail,hongkai-dai, needs platform reviewer assigned, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
[@drake-jenkins-bot](https://github.com/drake-jenkins-bot) mac-arm-ventura-clang-bazel-experimental-everything-release please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-Ngedx8n9_GLxIz327CJ:b-hupv8s)* status: LGTM missing from assignees hongkai-dai,BetsyMcPhail, needs platform reviewer assigned, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgeeGb7EiuInK0Aqdqu:b3dcro0)* status: LGTM missing from assignees hongkai-dai,BetsyMcPhail, needs platform reviewer assigned, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+[@xuchenhan-tri](https://github.com/xuchenhan-tri) for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgerXyD1THFM8NfyKLY:ba164up)* status: LGTM missing from assignees hongkai-dai,BetsyMcPhail, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
[@drake-jenkins-bot](https://github.com/drake-jenkins-bot) mac-arm-ventura-clang-bazel-experimental-everything-release please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-Ngerb5i68vNRdO7HccR:besmj92)* status: LGTM missing from assignees hongkai-dai,BetsyMcPhail, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm:  +(release notes: none) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgeypkjAoSrTLVIYo2Y:bhmf6da)* status: LGTM missing from assignees hongkai-dai,BetsyMcPhail, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgfPzm92-PQWSy8j--X:bg7igkv)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgibG8oBFiTCplDDFHe:bm9o57a)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned

**Review by AlexandreAmice — COMMENTED** [review]
-@hongkai-dai single reviewer is okay

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20369#-:-NgsaDnT2CVpgkr749e7:b-84iby7)* status: needs platform reviewer assigned

**Pull request merged**
