### PR TITLE
Upgrade Externals February 2024

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #20868.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20900)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by mwoehlke-kitware** [comment]
+@EricCousineau-TRI for both reviews per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20900#-:-Nq9g3RF-N37Uj6R8Doc:b-85g6de)* status: needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
Ready for rebase & push.

**Pull request merged**
