### PR TITLE
Separate InputPortDescriptor from OutputPortDescriptor

### LINKED ISSUE #3189: Split SystemPortDescriptor into InputPortDescriptor and OutputPortDescriptor
See discussion on #3188.

### PR DESCRIPTION
**Pull request by sherm1**
This is another name change in support of caching in #4364. We had to make this change anyway (see #3189). Changes `SystemPortDescriptor` to `InputPortDescriptor` or `OutputPortDescriptor` as appropriate.

Fixes #3189.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4602)

### CODE REVIEW

**Comment by sherm1** [comment]
+@russtedrake for feature & platform review if you are out there somewhere Russ. There are lots of files but the changes are few and just consist of renaming SystemPortDescriptor to {Input,Output}PortDescriptor as appropriate.

---

Review status: 0 of 60 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-:-KZnVN8Rb9SpXxwaM_ng:b-c8x4j4)*

**Comment by RussTedrake** [comment]
Reviewed 60 of 60 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/system_port_descriptor.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAXcbOp9KtMmD3gzS:-KZoAXcbOp9KtMmD3gzT:b4e4ryj) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L49)):*
> ```objc
>   int get_index() const { return index_; }
>   PortDataType get_data_type() const { return data_type_; }
>   int get_size() const {
> ```

BTW, I'm in favor of using size() consistently throughout.  right now we have a  mix-and-match of size() and get_size().

---

*[drake/systems/framework/system_port_descriptor.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAot6B7YJwqnKgRom:-KZoAot6B7YJwqnKgRon:b-ntjded) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L51)):*
> ```objc
>   int get_size() const {
>     if (size_ == kAutoSize) {
>       DRAKE_ABORT_MSG("Auto-size ports are not yet implemented.");
> ```

why is the accessor method the right place for this?  perhaps the constructor?

---

*[drake/systems/framework/system_port_descriptor.h, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAwRiNminDlq1uHWa:-KZoAwRiNminDlq1uHWb:bbbh61o) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L90)):*
> ```objc
>   int get_index() const { return index_; }
>   PortDataType get_data_type() const { return data_type_; }
>   int get_size() const {
> ```

same two comments as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4602)*

**Comment by sherm1** [comment]
Review comments resolved. I renamed `get_size()` to `size()`. That added a bunch more files with tiny changes, but the good news is that those appeared to be the last `get_size()`'s anywhere in the code base. Ready for another look, @russtedrake.

---

Review status: 42 of 81 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/system_port_descriptor.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAXcbOp9KtMmD3gzS:-KZrsigay10JyQk1DNvu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L49)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, I'm in favor of using size() consistently throughout.  right now we have a  mix-and-match of size() and get_size().
</blockquote></details>

Done.

---

*[drake/systems/framework/system_port_descriptor.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAot6B7YJwqnKgRom:-KZrsjxpSdJzqycJAuSF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L51)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why is the accessor method the right place for this?  perhaps the constructor?
</blockquote></details>

Done.

---

*[drake/systems/framework/system_port_descriptor.h, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAwRiNminDlq1uHWa:-KZrsmaX5hJbelHI1LJP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L90)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

same two comments as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-:-KZrsqmTcHL1MSraG2cV:b-zh56kt)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 38 of 39 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/system_port_descriptor.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAXcbOp9KtMmD3gzS:-KZrzyi6EDTMyUIBsDs5:b-qmh19m) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks for making the change!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-:-KZs-L2xpdJ9dUra1AUC:bnfp4nl)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_port_descriptor.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4602#-KZoAXcbOp9KtMmD3gzS:-KZs4oorEq-dRkp6_dVb:b-glhaf1) ([raw file](https://github.com/robotlocomotion/drake/blob/9e026863a9c1174004583404086a484c98b81566/drake/systems/framework/system_port_descriptor.h#L49)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

thanks for making the change!
</blockquote></details>

Merry Christmas!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4602)*

**Comment by david-german-tri** [comment]
Nice!  Thanks.

**Pull request merged**
