### PR TITLE
MosekSolver sets logging using CommonSolverOption

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15399)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please.

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri could you do a review again? I made just one line change.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15399#-:-MecakVm5WNYUusxcecF:b-kpqez5)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15399)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[solvers/mosek_solver.cc, line 1893 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15399#-Mecasev9J3YBZHFQHij:-Mecasev9J3YBZHFQHik:b-ofg7f9) ([raw file](https://github.com/robotlocomotion/drake/blob/0ba764f7bc4d3ba42513fdf7cdba87634816ab7c/solvers/mosek_solver.cc#L1893)):*
> ```cpp
>   // close it.
>   if (print_to_console && print_to_file) {
>     MSK_deletetask(&task);
> ```

BTW, this is only line of change from the previous review.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: and the sanitizer builds have run.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15399#-:-MeeLbZaAprv1vWrBqkN:b-uixr4y)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mosek_solver.cc, line 1893 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15399#-Mecasev9J3YBZHFQHij:-MeeLH5p7SCYdeYyFaPT:b-gmj9es) ([raw file](https://github.com/robotlocomotion/drake/blob/0ba764f7bc4d3ba42513fdf7cdba87634816ab7c/solvers/mosek_solver.cc#L1893)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, this is only line of change from the previous review.
</blockquote></details>

FYI @jwnimmer-tri possibly of interest re: our conversation about mosek leakiness -- might this apply to other suppressions as well?

**Pull request merged**
