### PR TITLE
Add SceneGraph::RemoveRenderer().

### PR DESCRIPTION
**Pull request by hongkai-dai**
Remove a renderer from SceneGraph.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20319)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-:-Ng1KUrY3a_G3ytFuUxk:bltfyse)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks so much for being willing to do this.

:LGTM:

+@ggould-tri for Monday's platform review, please.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-:-Ng4H44QAt8xae8qGj0d:b-b9gsus)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[`geometry/geometry_state.cc` line 1277 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-Ng4HkB_7oqikxKQmZWP:-Ng4HRCF1vESBfFy7ArH:b-v9afdj) ([raw file](https://github.com/RobotLocomotion/drake/blob/5347adef61bebb8e0c540ca338cfa0473103a654/geometry/geometry_state.cc#L1277)):*
> ```cpp
>   }
>   render_engines_.erase(name);
>   geometry_version_.modify_perception();
> ```

BTW Despite my original post in slack, I'm fine with modifying the version. it is simultaneously harmless, and probably pointless. But that's my fault in designing the versioning and not the fault of the usage here.
___
*[`geometry/scene_graph.h` line 712 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-Ng4I-J32jnbtaYfFbSO:-Ng4I-J32jnbtaYfFbSP:b-d4b474) ([raw file](https://github.com/RobotLocomotion/drake/blob/5347adef61bebb8e0c540ca338cfa0473103a654/geometry/scene_graph.h#L712)):*
> ```objc
>    @throws std::exception if this %SceneGraph doesn't have a renderer with the
>    specified name.
>    */
> ```

nit: The style of this file prefers putting the closing `*/` on the last line, if it fits.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri -@ggould-tri.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-:-Ng4L4oT9E7YQqNpvLUE:b-s64qm3)* status: 2 unresolved discussions

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks, @jwnimmer-tri.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20319#-:-Ng52-K3CR-3lgG5M82-:bkf9p8d)* status: 2 unresolved discussions

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Pull request merged**
