### PR TITLE
fix a end slope = 0 edge case for pchip

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
there was a sign comparison bug in 
ComputePchipEndSlope, which would cause undesired behavior when the last two knots, but not the second to last are the same (i.e. 1 2 2). The correct behavior is to have the end slope = 0, which the previous code violated. 

also changed magic number for dt comparison to 1e-10 defined in piecewise_function. 

@hongkai-dai for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4450)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/test/piecewise_polynomial_generation_test.cc, line 294 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYafxlPiNzMTA8uexu6:-KYafxlPiNzMTA8uexu7:b30ug91) ([raw file](https://github.com/robotlocomotion/drake/blob/f809f5f0594fd19aa6279861d15a3ce92f1cf4a9/drake/common/trajectories/test/piecewise_polynomial_generation_test.cc#L294)):*
> ```cpp
>   // Add special case for pchip to test for the last two knots being the same.
>   // There was a sign comparison bug in ComputePchipEndSlope when the end
>   // slope = 0.
> ```

BTW, consider referencing #4450 in this comment block so future readers can gain greater context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri platform :lgtm:.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/piecewise_function.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYag3dCrb5jTPFpEFrB:-KYag3dCrb5jTPFpEFrC:b-bpdd2k) ([raw file](https://github.com/robotlocomotion/drake/blob/f809f5f0594fd19aa6279861d15a3ce92f1cf4a9/drake/common/trajectories/piecewise_function.h#L12)):*
> ```objc
> 
>  public:
>   static constexpr double kEpsilonTime = 1e-10;
> ```

BTW This is public.  Is there a useful API comment it could have?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-:-KYaftRwITf0myyWI6lz:bwt0yrs)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/piecewise_function.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYag3dCrb5jTPFpEFrB:-KYamDozefZRduwl7o0c:b7mb2h9) ([raw file](https://github.com/robotlocomotion/drake/blob/f809f5f0594fd19aa6279861d15a3ce92f1cf4a9/drake/common/trajectories/piecewise_function.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This is public.  Is there a useful API comment it could have?
</blockquote></details>

Done. also you made me think a bit more about this, so i used it in the constructor to guard minimal dt increment as well now. 

---

*[drake/common/trajectories/test/piecewise_polynomial_generation_test.cc, line 294 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYafxlPiNzMTA8uexu6:-KYamOWgvy0vYMYMxJG6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f809f5f0594fd19aa6279861d15a3ce92f1cf4a9/drake/common/trajectories/test/piecewise_polynomial_generation_test.cc#L294)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider referencing #4450 in this comment block so future readers can gain greater context.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial.cc, line 417 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYe7xSiOXUAjSAMS-bI:-KYe7xSiOXUAjSAMS-bJ:b-ed1e42) ([raw file](https://github.com/robotlocomotion/drake/blob/043587e757b2098675d9249a1084d75925738e9e/drake/common/trajectories/piecewise_polynomial.cc#L417)):*
> ```cpp
> template <typename CoefficientType>
> static int sign(CoefficientType val, CoefficientType tol) {
>   if (val < -tol)
> ```

Throws an error if `val` is NaN or infinity?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-:-KYe8m5RSlOD9aVqbwin:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial.cc, line 417 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4450#-KYe7xSiOXUAjSAMS-bI:-KYeFSAi_ATuNuGIcpNs:bbanft1) ([raw file](https://github.com/robotlocomotion/drake/blob/043587e757b2098675d9249a1084d75925738e9e/drake/common/trajectories/piecewise_polynomial.cc#L417)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Throws an error if `val` is NaN or infinity?
</blockquote></details>

i realized last night there was a case that has infinity time. a constructor in piecewisepolynomial that takes only the coeffst. it defaults time to [0, inf]. 
so i am hesitant to check for that here. it's probably better to do this kind of stuff in a separate pass. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4450)*

**Pull request merged**
