### PR TITLE
Python bindings for SpatialInertia geometries.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-:-NSEByYs9G-mA-GAXGwD:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending one minor fix
+@xuchenhan-tri for platform review per rotation, please

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-:-NSHCEvf7hSqBzBUiCRp:b-8t9i2i)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`bindings/pydrake/multibody/tree_py.cc` line 1202 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-NSHC-Yl6Ag66zgt8vz8:-NSHC-Yl6Ag66zgt8vz9:b-xw8vb7) ([raw file](https://github.com/RobotLocomotion/drake/blob/73c06821778302e917463fd6cc837a2bb29cb36b/bindings/pydrake/multibody/tree_py.cc#L1202)):*
> ```cpp
>             cls_doc.SolidSphereWithDensity.doc)
>         .def_static("HollowSphereWithDensity", &Class::HollowSphereWithDensity,
>             py::arg("density"), py::arg("radius"),
> ```

minor: this parameter should be `area_density`
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 726 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-NSHCAOh2Zp_rLghleKe:-NSHCAOh2Zp_rLghleKf:bt5bmly) ([raw file](https://github.com/RobotLocomotion/drake/blob/73c06821778302e917463fd6cc837a2bb29cb36b/bindings/pydrake/multibody/test/plant_test.py#L726)):*
> ```Python
>             density=1000, radius=0.5)
>         SpatialInertia.HollowSphereWithDensity(
>             density=1000, radius=0.5)
> ```

BTW area_density

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm:
-(release notes: feature) +(release notes: fix) 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-:-NSHHtz4888iKlVvYPDe:bjgucrv)* status: 2 unresolved discussions (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`bindings/pydrake/multibody/tree_py.cc` line 1202 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-NSHC-Yl6Ag66zgt8vz8:-NSHlvIH92fdUp2jZlW6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/73c06821778302e917463fd6cc837a2bb29cb36b/bindings/pydrake/multibody/tree_py.cc#L1202)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this parameter should be `area_density`
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 726 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-NSHCAOh2Zp_rLghleKe:-NSHlwrH2RNnlmmnADxz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/73c06821778302e917463fd6cc837a2bb29cb36b/bindings/pydrake/multibody/test/plant_test.py#L726)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW area_density
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19134#-:-NSI0XzY5xX9nAiWfeVJ:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/19134 helps to resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Pull request merged**
