### PR TITLE
SnoptSolverDetails report solving time.

### PR DESCRIPTION
**Pull request by hongkai-dai**
From slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1722864395768569

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-:-O3_F3YAE7bKnHJPcbIl:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-:-O3cRjIU5dSiWORo703_:b-2hj6f6)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-:-O3csRV_A0Bbml42E7sL:bnfp4nl)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/snopt_solver.h` line 37 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-O3cagb01bIo6Lo3GOUD:-O3cagb01bIo6Lo3GOUE:b3nwz0g) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b1d256e488debbc8e70ba907f0a144641643b10/solvers/snopt_solver.h#L37)):*
> ```objc
>   Eigen::VectorXd Fmul;
> 
>   // The duration of the snopt solve in seconds.
> ```

minor:  Comment format inconsistent with the rest of this file, and is non-doxygen.
___
*[`solvers/snopt_solver.cc` line 1385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-O3csE-zE5H4DsvvBhWw:-O3csE-zE5H4DsvvBhWx:b-nn9m1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b1d256e488debbc8e70ba907f0a144641643b10/solvers/snopt_solver.cc#L1385)):*
> ```cpp
>   auto snopt_end = std::chrono::high_resolution_clock::now();
>   auto duration = std::chrono::duration<double>(
>       snopt_end - snopt_start);
> ```

nit:  `auto` seems unnecessary since you're explicitly specifying the type already?



_Suggestion:_
```cpp
  std::chrono::duration<double> duration = snopt_end - snopt_start;
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/snopt_solver.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-O3ctd6N0LkFO0yjkRsD:-O3ctd6N0LkFO0yjkRsE:bsgho7o) ([raw file](https://github.com/RobotLocomotion/drake/blob/4b1d256e488debbc8e70ba907f0a144641643b10/solvers/snopt_solver.h#L38)):*
> ```objc
> 
>   // The duration of the snopt solve in seconds.
>   double solve_time;
> ```

nit Uninitialized POD

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781)* status: missing label for release notes

**Review by ggould-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21781#-:-O3cxSLk9pHmLB3tKVjF:b-l8xbmn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
