### PR TITLE
List out specific runtime/references warnings in systems

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A (possibly-final?) portion of #2274.  The prior related PRs are #3896, #3897, #3898.
We want to mark all of these now, so that they don't get any worse.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3943)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.

I was hoping to wait for Jenkins on this before tagging for review, but Jenkins is slow today.  It passed for me locally.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-:-KVBZrUZkj3foMS_L6YY:b5aawzr)*

**Comment by ggould-tri** [comment]
A number of formatting issues flagged below.  For just comments I am happy to leave them all to author's discretion, so :lgtm: and make your own call.

---

Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBa37oH2T7_sIbfvTn:-KVBa37oH2T7_sIbfvTo:b-lrn490) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/controllers/InstantaneousQPController.cpp#L372)):*
> ```cpp
>     w_qdd(ind) = it->weight;
>   }
> }
> ```

FYI not sure why this whitespace went away.  I think it belonged.

---

*[drake/systems/plants/parser_urdf.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBaelkKmSbld5t4wJR:-KVBaelkKmSbld5t4wJS:b-a3twkv) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/parser_urdf.h#L201)):*
> ```objc
> ModelInstanceIdTable AddModelInstanceFromUrdfString(
>     const std::string& urdf_string,
>       // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> ```

FYI nonstandard indent

---

*[drake/systems/plants/parser_urdf.h, line 345 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBaimWZ7ayVMcamxWr:-KVBaimWZ7ayVMcamxWs:b-a3twkv) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/parser_urdf.h#L345)):*
> ```objc
> ModelInstanceIdTable AddModelInstanceFromUrdfFile(
>      const std::string& urdf_filename,
>     // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> ```

FYI nonstandard indent

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBbUOFXNgaiaKnYs4y:-KVBbUOFXNgaiaKnYs4z:b-it2fsi) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/constraint/RigidBodyConstraint.h#L6)):*
> ```objc
> // entirety.  When the file is next rewritten or updates, we should re-enable
> // cpplint accordingly.
> ```

FYI In my opinion, this is like a TODO comment and for the same reason deserves a username or issue number reference for future archaeologists.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBc0Ex6Fb10cq8f3ti:-KVBc0Ex6Fb10cq8f3tj:b-srhbp4) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/joints/QuaternionFloatingJoint.h#L64)):*
> ```objc
>           motion_subspace_dot_times_v.size(), get_num_velocities());
>     }
>   }
> ```

FYI not clear that removal of this whitespace was intentional.  I believe it was desirable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-:-KVBcmovm3j7qVVvIwwt:b-jiyhd)*

**Comment by jwnimmer-tri** [comment]
Review status: 34 of 39 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBa37oH2T7_sIbfvTn:-KVBe_Zv9rQzxVj_x1XX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/controllers/InstantaneousQPController.cpp#L372)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI not sure why this whitespace went away.  I think it belonged.
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBaelkKmSbld5t4wJR:-KVBeglR7j4hnF1I5Bjn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/parser_urdf.h#L201)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI nonstandard indent
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 345 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBaimWZ7ayVMcamxWr:-KVBejw2y_4iF7YHTME7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/parser_urdf.h#L345)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI nonstandard indent
</details>
Done.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBbUOFXNgaiaKnYs4y:-KVBf-TU4LUfVYFvxs15:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/constraint/RigidBodyConstraint.h#L6)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI In my opinion, this is like a TODO comment and for the same reason deserves a username or issue number reference for future archaeologists.
</details>
Done.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3943#-KVBc0Ex6Fb10cq8f3ti:-KVBfXp4yNBI_A36pjmN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/671eca5892b2112b6888799ca9c7875f87dce86a/drake/systems/plants/joints/QuaternionFloatingJoint.h#L64)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI not clear that removal of this whitespace was intentional.  I believe it was desirable.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3943)*

**Comment by ggould-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3943)*

**Pull request merged**
