### PR TITLE
Linearize MBP pendulum model

### PR DESCRIPTION
**Pull request by amcastro-tri**
Piggybacking on one @RussTedrake's recent PR.

Fixes MBP scalar conversion constructor and adds unit test linearizing a pendulum plant.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8294)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8294#-:-L71uuEe1lSXJk6nmWKu:bll7v0f)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8294#-:-L74pSZ8DqUiIDTOWsUk:b-vt9vbo)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8294#-:-L75BcltASYLRTzX9DUx:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8294#-:-L75RTFv5pF-RQk8bZbr:bnfp4nl)*

**Pull request merged**
