### PR TITLE
Start to prune references to MATLAB examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Switch gallery to link to a tag, not master.  (Also, fix a broken C++ link.)
- Remove from_source citation to MATLAB examples in "test your installation".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6273)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-Km2lzONxoqRRQ918Vgg:-Km2lzOODNFML_KgLjSS:bokxx6w) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L262)):*
> ```reStructuredText
>     addpath_drake
> 
> You should not see any error messages.
> ```

Should I ask the user to run `drake/matlab/solvers/test/testMathematicalProgram.m` here?  (And what would be the syntax if so?)

---

*[drake/doc/from_source.rst, line 263 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-Km2m82TXBCoMk45Cfnc:-Km2m82U5l344lcwuU9w:b1x4wrq) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L263)):*
> ```reStructuredText
> 
> You should not see any error messages.
>     
> ```

Oops, extra whitespace; will remove in next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 257 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-KmQnFMB6vdX078uuFCY:-KmQnFMB6vdX078uuFCZ:b19majz) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L257)):*
> ```reStructuredText
> --------------------------------
> 
> Start MATLAB, then at the MATLAB prompt do::
> ```

add a note above here saying that the matlab bindings are about to be replaced, and link to the matlab.rst you made last week?

---

*[drake/doc/from_source.rst, line 262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-Km2lzONxoqRRQ918Vgg:-KmQlXe-exvOZreO0bF4:b-6ga571) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L262)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should I ask the user to run `drake/matlab/solvers/test/testMathematicalProgram.m` here?  (And what would be the syntax if so?)
</blockquote></details>

syntax:
```
cd drake-distro/drake/
addpath_drake
cd matlab/solvers/test
testMathematicalProgram
```

(that should be sufficient, but not very interesting)

---

*[drake/doc/gallery.rst, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-KmQn7vx1rRHO2mm1--P:-KmQn7vx1rRHO2mm1--Q:b5yj12b) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/gallery.rst#L31)):*
> ```reStructuredText
> 	</div>
> 
> *Source Code:* `drake/examples/RimlessWheel <https://github.com/RobotLocomotion/drake/tree/last_sha_with_original_matlab/drake/examples/RimlessWheel>`_
> ```

good.  thanks for updating these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 257 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-KmQnFMB6vdX078uuFCY:-KmRXY04JA82mFeBI1YB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L257)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

add a note above here saying that the matlab bindings are about to be replaced, and link to the matlab.rst you made last week?
</blockquote></details>

Done.

---

*[drake/doc/from_source.rst, line 262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-Km2lzONxoqRRQ918Vgg:-KmRX-jm-UjtpUzGZq90:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13e745fb2edac41a34e47c8ce7499c1650f16118/drake/doc/from_source.rst#L262)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

syntax:
```
cd drake-distro/drake/
addpath_drake
cd matlab/solvers/test
testMathematicalProgram
```

(that should be sufficient, but not very interesting)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@sherm1 for all review, please.  (I'm manually cycling the MATLAB PRs through platform review, off-schedule.)

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-:-KmRYrzu6VhAlyfMCV6G:b-ortea)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-:-KmRwxrHyE2pMXfsdxWm:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@RussTedrake PTAL and add LGTM if you're all set.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-:-KmYyzJRa-z0UYaijBtF:bmdalc2)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6273#-:-KmczZ9iE6SFXZnLv42q:bnfp4nl)*

**Pull request merged**
