### PR TITLE
Fix to schedule a "now" event, until #5725 is resolved.

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8465)

### CODE REVIEW

**Comment by rcory** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8465#-:-L8cc1OIDWlPJ-Pm6h0w:b-a98c4g)*

**Comment by edrumwri** [comment]
notifying @siyuanfeng-tri and @sherm1 on this. I'm snowed under at the moment, but will be seeing whether existing changes allow me to resolve #5725 before reviewing this one.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8465#-:-L8cdgSqDoEDSj8UtH1r:bam2fwp)*

**Comment by sherm1** [comment]
Seems like a good idea to me. CI failed though.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8465#-:-L8iNbzE3dxtCNUToYu2:byfs3y5)*

**Comment by edrumwri** [comment]
I think you can kill this PR now, Rick. Thanks for submitting it in the first place!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8465#-:-L97QCwW9nw344mHAo_W:b4nikyr)*

**Comment by rcory** [comment]
Closing. Issue fixed in #8486

**Pull request closed without merging**
