### PR TITLE
[perception] Improve PointCloud::VoxelizedDownSample speed

### PR DESCRIPTION
**Pull request by Brian-Acosta**
Per [slack discussion](https://drakedevelopers.slack.com/archives/C3GG2R4JY/p1699026841343839),  Profiling shows the current implementation can be sped up significantly by avoiding accessor methods with `has_xyz()`, `has_rgb()`, etc. 

Results of rough benchmark on a 1,000,000 point random point cloud
**Current implementation:** XYZ only | `1.19128 seconds wall clock time`
**Current implementation:** XYZ, RGB, Normal, Curvature | `2.447968 seconds wall clock time`
**PR:**  XYZ only | `0.6267832 wall clock time`
**PR:** XYZ, RGB, Normal, Curvature | `1.331862 seconds wall clock time`

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks for this!

It's in pretty good shape, but see a few notes below.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-:-NibDmQH4SdX81PCdxAI:b-s7cb6p)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

___
*[`perception/BUILD.bazel` line 118 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NiaGSpc1Iy-edodxqWi:-NiaGSpc1Iy-edodxqWj:bbd48h3) ([raw file](https://github.com/RobotLocomotion/drake/blob/070992283affe931ffd99846363e85924292a939/perception/BUILD.bazel#L118)):*
> ```Starlark
> )
> 
> drake_cc_binary(
> ```

This diverges from how we usually write benchmarks.  See https://github.com/Brian-Acosta/drake/pull/1 for the fix.  If you like, it click the "merge" button there.
___
*[`perception/point_cloud.cc` line 522 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NibEZ6G3Ux5EyEv0FT-:-NibEZ6HATbvPPaUM9ss:b-m8ty3z) ([raw file](https://github.com/RobotLocomotion/drake/blob/5087287dff2fa7e5c7f64dc6503be415b9137bfe/perception/point_cloud.cc#L522)):*
> ```cpp
>   // Helper lambda to process a single voxel cell.
>   const auto process_voxel =
>       [this, &down_sampled_xyzs, &down_sampled, &my_xyzs, this_has_normals,
> ```

As I understand it, the claim here is that checked accessors like `this->has_normals()` are too slow to run on every voxel.

To help enforce that, we can insist at compile time that _no_ functions on `this` can be called within the lambda, by capturing on the `this->storage_` instead of all of `this`.

Here's what it looks like.  WDYT?

```patch
--- a/perception/point_cloud.cc
+++ b/perception/point_cloud.cc
@@ -518,8 +518,9 @@ PointCloud PointCloud::VoxelizedDownSample(
   auto down_sampled_xyzs = down_sampled.mutable_xyzs();
 
   // Helper lambda to process a single voxel cell.
+  Storage& storage = *storage_;
   const auto process_voxel =
-      [this, &down_sampled_xyzs, &down_sampled, &my_xyzs, this_has_normals,
+      [&storage, &down_sampled_xyzs, &down_sampled, &my_xyzs, this_has_normals,
        this_has_rgbs, this_has_descriptors](
            int index_in_down_sampled, const std::vector<int>& indices_in_this) {
     // Use doubles instead of floats for accumulators to avoid round-off errors.
@@ -527,23 +528,23 @@ PointCloud PointCloud::VoxelizedDownSample(
     Eigen::Vector3d normal{Eigen::Vector3d::Zero()};
     Eigen::Vector3d rgb{Eigen::Vector3d::Zero()};
     Eigen::VectorXd descriptor{Eigen::VectorXd::Zero(
-        this_has_descriptors ? storage_->descriptors().rows() : 0)};
+        this_has_descriptors ? storage.descriptors().rows() : 0)};
     int num_normals{0};
     int num_descriptors{0};
 
     for (int index_in_this : indices_in_this) {
       xyz += my_xyzs.col(index_in_this).cast<double>();
       if (this_has_normals &&
-          storage_->normals().col(index_in_this).array().isFinite().all()) {
-        normal += storage_->normals().col(index_in_this).cast<double>();
+          storage.normals().col(index_in_this).array().isFinite().all()) {
+        normal += storage.normals().col(index_in_this).cast<double>();
         ++num_normals;
       }
       if (this_has_rgbs) {
-        rgb += storage_->rgbs().col(index_in_this).cast<double>();
+        rgb += storage.rgbs().col(index_in_this).cast<double>();
       }
       if (this_has_descriptors &&
-          storage_->descriptors().col(index_in_this).array().isFinite().all()) {
-        descriptor += storage_->descriptors().col(index_in_this).cast<double>();
+          storage.descriptors().col(index_in_this).array().isFinite().all()) {
+        descriptor += storage.descriptors().col(index_in_this).cast<double>();
         ++num_descriptors;
       }
     }
```
___
*[`perception/point_cloud.cc` line 565 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NibFQB8EsHRB0e1qn7P:-NibFQB8EsHRB0e1qn7Q:bpmzux1) ([raw file](https://github.com/RobotLocomotion/drake/blob/5087287dff2fa7e5c7f64dc6503be415b9137bfe/perception/point_cloud.cc#L565)):*
> ```cpp
>     }
>   };
> ```

nit A spurious extra line got added here.
___
*[`perception/test/downsample_benchmark.cc` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NiaFqnv8J5kHLSBj-0x:-NiaFqnv8J5kHLSBj-0y:b-bndox8) ([raw file](https://github.com/RobotLocomotion/drake/blob/070992283affe931ffd99846363e85924292a939/perception/test/downsample_benchmark.cc#L18)):*
> ```cpp
> 
>   // make the spatial coordinates the same to avoid time differences due to
>   // spatial hashing
> ```

nit Capitalize and punctuate full sentences.

https://drake.mit.edu/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar

**Review by Brian-Acosta — COMMENTED** [review]
Very educational, thanks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-:-NibggOE7PjOtcHC6H0A:b-c9rv0d)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

___
*[`perception/point_cloud.cc` line 522 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NibEZ6G3Ux5EyEv0FT-:-NibeEON0GebQpNcGbIn:b-xa18ht) ([raw file](https://github.com/RobotLocomotion/drake/blob/5087287dff2fa7e5c7f64dc6503be415b9137bfe/perception/point_cloud.cc#L522)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As I understand it, the claim here is that checked accessors like `this->has_normals()` are too slow to run on every voxel.

To help enforce that, we can insist at compile time that _no_ functions on `this` can be called within the lambda, by capturing on the `this->storage_` instead of all of `this`.

Here's what it looks like.  WDYT?

```patch
--- a/perception/point_cloud.cc
+++ b/perception/point_cloud.cc
@@ -518,8 +518,9 @@ PointCloud PointCloud::VoxelizedDownSample(
   auto down_sampled_xyzs = down_sampled.mutable_xyzs();
 
   // Helper lambda to process a single voxel cell.
+  Storage& storage = *storage_;
   const auto process_voxel =
-      [this, &down_sampled_xyzs, &down_sampled, &my_xyzs, this_has_normals,
+      [&storage, &down_sampled_xyzs, &down_sampled, &my_xyzs, this_has_normals,
        this_has_rgbs, this_has_descriptors](
            int index_in_down_sampled, const std::vector<int>& indices_in_this) {
     // Use doubles instead of floats for accumulators to avoid round-off errors.
@@ -527,23 +528,23 @@ PointCloud PointCloud::VoxelizedDownSample(
     Eigen::Vector3d normal{Eigen::Vector3d::Zero()};
     Eigen::Vector3d rgb{Eigen::Vector3d::Zero()};
     Eigen::VectorXd descriptor{Eigen::VectorXd::Zero(
-        this_has_descriptors ? storage_->descriptors().rows() : 0)};
+        this_has_descriptors ? storage.descriptors().rows() : 0)};
     int num_normals{0};
     int num_descriptors{0};
 
     for (int index_in_this : indices_in_this) {
       xyz += my_xyzs.col(index_in_this).cast<double>();
       if (this_has_normals &&
-          storage_->normals().col(index_in_this).array().isFinite().all()) {
-        normal += storage_->normals().col(index_in_this).cast<double>();
+          storage.normals().col(index_in_this).array().isFinite().all()) {
+        normal += storage.normals().col(index_in_this).cast<double>();
         ++num_normals;
       }
       if (this_has_rgbs) {
-        rgb += storage_->rgbs().col(index_in_this).cast<double>();
+        rgb += storage.rgbs().col(index_in_this).cast<double>();
       }
       if (this_has_descriptors &&
-          storage_->descriptors().col(index_in_this).array().isFinite().all()) {
-        descriptor += storage_->descriptors().col(index_in_this).cast<double>();
+          storage.descriptors().col(index_in_this).array().isFinite().all()) {
+        descriptor += storage.descriptors().col(index_in_this).cast<double>();
         ++num_descriptors;
       }
     }
```
</blockquote></details>

I like this better, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.

+@rpoyner-tri for platform review per schedule (tomorrow), please.

> Reviewed 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-:-NibjfuO6xfelnto3GpU:b-ubjc67)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

**Review by rpoyner-tri — COMMENTED** [review]
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-:-NifSYfz1mnCGHtOYBYl:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-NifP4waB9l1RgiuSMrm):*
btw  We are starting to try to be more consistent with commit messages, to help `git` tooling, and release notes authors. I can squash the commits and use the top comment in the main thread as a basis for the commit message. The only reason you (author) would need to take action is if the proposed message below is somehow stale or incomplete.

Here is what I propose:
```
[perception] Improve PointCloud::VoxelizedDownSample speed                                                                                                                                    
                                                                                                                                                                                              
The patch speeds up point cloud down-sampling, and provides a benchmark                                                                                                                        
program for wall-clock speed measurements.                                                                                                                                                    
                                                                                                                                                                                              
Per slack discussion, profiling shows the current implementation can be                                                                                                                       
sped up significantly by avoiding accessor methods with has_xyz(),                                                                                                                            
has_rgb(), etc.                                                                                                                                                                               
                                                                                                                                                                                              
Results of rough benchmark on a 1,000,000 point random point cloud                                                                                                                            
(numbers are all seconds of wall clock time):                                                                                                                                                 
* Current implementation: XYZ only | 1.19128                                                                                                                                                  
* Current implementation: XYZ, RGB, Normal, Curvature | 2.447968                                                                                                                              
* PR:  XYZ only | 0.6267832                                                                                                                                                                   
* PR: XYZ, RGB, Normal, Curvature | 1.331862
```

If the above is good, just resolve this thread, Otherwise, let me know how to improve things.


<!-- Sent from Reviewable.io -->

**Review by Brian-Acosta — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Brian-Acosta)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20476#-:-NifaVMi5_iLptGtChKC:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
