### PR TITLE
Remove deprecated 2021-11 tools, setup

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16018)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews per schedule, please.

**Comment by jwnimmer-tri** [comment]
(No need for "retest this please" on this one -- no C++ nor Python code changes.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16018#-:-MnRz7ELDSST68Zd1H5h:bxqo58p)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
