### PR TITLE
add python binding for computePositionNameToIndexMap method 

### PR DESCRIPTION
**Pull request by kuindersma**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9242)

### CODE REVIEW

**Comment by sherm1** [comment]
@kuindersma did you want to assign a feature reviewer for this PR?

**Comment by mpetersen94** [comment]
@EricCousineau-TRI for feature review.

**Comment by SeanCurtis-TRI** [comment]
It's been a while -- is this still active?

**Comment by kuindersma** [comment]
Sorry, I've been busy and this has been low in my stack. Feel free to close it for now if no one else wants to write these tests

**Comment by SeanCurtis-TRI** [comment]
I'll leave it up to @EricCousineau-TRI  when he's back.

**Comment by EricCousineau-TRI** [comment]
If it's not super useful to current projects, and given #4697, I'll close this for the time being.

Thanks!

**Pull request closed without merging**
