### PR TITLE
Revert "Parallelize the generic method for checking boundedness of a convex set."

### PR DESCRIPTION
**Pull request by nicolecheetham**
Reverts RobotLocomotion/drake#22084

Dear Thomas,

 The on-call build cop, Nicole C., believes that your PR 22084 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failure under investigation is:
https://drake-jenkins.csail.mit.edu/job/linux-jammy-clang-bazel-nightly-everything-valgrind-memcheck/367/

 This is testing to see which change PR 22084 or 22117 caused the failure.
 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22135)

### CODE REVIEW

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-nightly-everything-valgrind-memcheck please

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-nightly-everything-valgrind-memcheck please

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please

**Review by cohnt — COMMENTED** [review]
I'm almost 100% sure that PR caused the test failure, and I can replicate the issue locally.

:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22135#-:-OB1WFESDygu6pU4XYF7:b-sliwsd)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@sherm1 for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22135#-:-OB1l0HzEe91Xjy25iD8:bu0bkqk)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @nicolecheetham)

**Comment by jwnimmer-tri** [comment]
It looks like #22140 will fix this without a revert.  We can close once we're sure.

**Comment by BetsyMcPhail** [comment]
The failing nightly job passed after the other fix was merged, closing this.

**Pull request closed without merging**
