### PR TITLE
dynamic_analysis: Comment on memcheck's exception for sh filtering

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
See Slack conversation:
https://drakedevelopers.slack.com/archives/C270MN28G/p1610544838306100?thread_ts=1610539112.305300&cid=C270MN28G

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Simple PR: +@sammy-tri for both reviews, please?

FYI @jwnimmer-tri @jamiesnape 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523#-:-MQvxRdkBbuwA3-GcFrU:brbi9rz)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Comment by jamiesnape** [comment]
We deliberately don't ignore shell. There are a fair number of C++ bugs that got through when the configuration excluded shell. If it is one test, exclude it with the tag.

**Comment by jamiesnape** [comment]
(The ultimate goal is that Python would be clean enough to get through Valgrind, but running debug packages and the recommended suppressions is still not getting us there.)

**Comment by EricCousineau-TRI** [comment]
Gotcha! Closing.

**Comment by EricCousineau-TRI** [comment]
Actually, reopening based on the defect that your above comments are (to me) tribal knowledge. Rescoping PR to document this, Encoded here in a comment so someone in the future has more direct traceability.

**Comment by jamiesnape** [comment]
The point here is that Python is excluded, not that shell is not. Whether or not that is tribal knowledge, I am not sure, but most people that use Valgrind are familiar with the whole Python mess.

**Comment by jamiesnape** [comment]
(This is all in the open in the Valgrind runner. `--trace-children` is the relevant option should you really need to mention shell.)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523#-:-MQx-ZCFCHbGFDa8ocNA:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Comment by jwnimmer-tri** [comment]
PRs that document best practices should not skip feature review.  If we don't ask the SMEs for best practices, what good is the advice?

+@jamiesnape for feature review.

**Review by jamiesnape — COMMENTED** [review]
:lgtm: It is a little sweeping the advice, and I am not sure it will really get read until after something fails, but it is fine. My push on having all the tooling work on almost all targets stalled out anyway.

(Maybe the big doc rewrite issue will encapsulate some of the comments and READMEs at some point, though.)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523#-:-MQx1UUpBykVigXxPS9P:b-bemw0y)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jamiesnape

___
*[tools/dynamic_analysis/bazel.rc, line 223 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14523#-MQx0JrK5fHl_qUYJHwH:-MQx0JrK5fHl_qUYJHwI:bvblu9r) ([raw file](https://github.com/robotlocomotion/drake/blob/841942036f623fd3e7548d202e29d48dfc6f63fb/tools/dynamic_analysis/bazel.rc#L223)):*
> ```
> # We explicitly do not filter `sh` targets because some C++ binaries are tested
> # using this mechanism. Any Python code that is run through a `sh` target
> # should use `tags = ["no_memcheck"]`.
> ```

FYI We have some Python code that runs through Valgrind fine (though admittedly not much), so `may need `tags` = ["no_memcheck"]` would be more accurate.

You could say something like "We recommend testing such code using Valgrind before merging", but, really, prose that long should be in the docs, not in a comment.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jamiesnape (waiting on @jamiesnape and @sammy-tri)

___
*[tools/dynamic_analysis/bazel.rc, line 223 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14523#-MQx0JrK5fHl_qUYJHwH:-MQx9iD3CisyP_A6Z-Ak:b-i1pyqi) ([raw file](https://github.com/robotlocomotion/drake/blob/841942036f623fd3e7548d202e29d48dfc6f63fb/tools/dynamic_analysis/bazel.rc#L223)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI We have some Python code that runs through Valgrind fine (though admittedly not much), so `may need `tags` = ["no_memcheck"]` would be more accurate.

You could say something like "We recommend testing such code using Valgrind before merging", but, really, prose that long should be in the docs, not in a comment.
</blockquote></details>

OK Done - thanks!

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14523)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jamiesnape

**Pull request merged**
