### PR TITLE
Use dpkg_install_from_wget for dreal/ibex

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7628)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for all reviews, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7628#-:-L0RbMOZ1U9bUkt6APjF:b-g6fe9u)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7628#-:-L0Rbx8SsQMMT1bYFbea:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
`unprovisioned` passed.

**Pull request merged**
