### PR TITLE
[Multilane] ArcLane and LineLane removal

### PR DESCRIPTION
**Pull request by agalbachicar**
This PR removes `ArcLane` and `LineLane` classes so as to make use of `RoadCurve` implementations. `Lane` objects will consume a `RoadCurve` pointer which is provided by the parent `Segment` at construction time. 

PR #6822 introduced `RoadCurves` implementations for line and arc reference curves. Now those are consumed by `Lane` objects, so it is not necessary anymore to have classes like `ArcLane` or `LineLane`. The way to add a new geometry to Multilane is to provide an implementation of `RoadCurve` interface.

In addition, tests where modified so as to create `LineRoadCurve` or `ArcRoadCurve` objects instead of calling old `Segment::NewLineLane()` or `Segment::NewArcLane()` methods. The new replacement is `Segment::NewLane()`.

This PR completes the proposed discussion in #6754 and relates to issue #4934.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6934)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+maddog.tri for feature review please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KsihQq4AllxL5kD6p86:b7g5fzi)*

**Comment by agalbachicar** [comment]
+@maddog-tri for feature review please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Ksihm0_6YDb2bTsWDQt:b-5klkw7)*

**Comment by agalbachicar** [comment]
CC to @liangfok

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KsihxnHeQt1jSAiYIBv:b-oem1et)*

**Comment by maddog-tri** [comment]
Hi, Agustin --- do you have a branch already available for the *next* PR after this one?  I'm curious to get a better idea of the trajectory after this, and if there is code, that is the simplest way....

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Ksk-r0ASGI4zVfYgH3v:b-ra2o1u)*

**Comment by maddog-tri** [comment]
First pass complete, please take a look.  (Only one comment!  But, it's a META....)

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/multilane/lane.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KslZfu4KBkUpFik8ret:-KslZfu5TNL3WM_qZkWC:b-gaa3s8) ([raw file](https://github.com/robotlocomotion/drake/blob/05f3c2438c367522b1bac10ad9135689fb76f5f3/drake/automotive/maliput/multilane/lane.cc#L37)):*
> ```cpp
> 
> 
> double Lane::do_length() const {
> ```

META:  It occurs to me that the loss of `p_scale_` as a variable name makes the math a bit more opaque (as if it is not opaque enough already).  It is the length of the planar reference curve... but it's function as a scale-factor is more important (because that plays into how it propagates through the equations).

Suggested resolution:  simply rename `RoadCurve::length()` to `RoadCurve::p_scale()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Kslc-zwkyMjGAAOw_kn:bz6t9dv)*

**Comment by agalbachicar** [comment]
Hi Matt. [Here](https://github.com/ekumenlabs/drake/tree/test/Multilane_RoadCurve_Lateral_Offset/drake/automotive/maliput/multilane) is the test branch with the next PR (I still need to rebase comments from previous PRs).

The main idea behind this PR is the following:

- A new interface is created: `C2ScalarFunction`. It provides the necessary interface to define what's necessary from the Lane's internal implementation of an elevation and superelevation function. Mainly the function evaluation and its derivatives.
- `CubicPolynomial` inherits from `C2ScalarFunction` and changes its methods to be overriding the interface.
- A new class is introduced, it is called `Elevation` (I was thinking of changing the name to `ComposedElevation` or similar). This function implements `C2ScalarFunction` and it is composed of both `CubicPolynomials` (for reference elevation and superelevation) as well as the offset distance `r` at which the `ComposedElevation` is evaluated. The idea behind this class is to keep the elevation composition transparent for `Lane` class as much as possible.
- `RoadCurve` consumes a `ComposedElevation`/`Elevation` instead of a `CubicPolynomial`.
- `RoadCurve` adds a new method, `Offset`. This method should provide the facilities to offset the reference curve (over z=0 plane) and to create an new `ComposedElevation` object based on the previous displacement.

So, all in all, the idea behind this is that a `Segment` handles a reference trajectory (`RoadCurve` implementation). Each new Lane will consume an offset of the reference trajectory at `r` distance what will ease the process of keeping several Lanes inside a Segment and manage the offset at the `Segment` level pushing that down to `Lane`'s implementation.

Up to now I have some tests for geometry and I was planning to make a sample implementation of the integration with the `Segment::NewLane()`. Something left out of the implementation is lane bounds and driveable bounds management. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KsnTUl5bKN5hyIYJgTG:bwibgft)*

**Comment by agalbachicar** [comment]
Comment was addressed. PTAL.

---

Review status: 12 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/multilane/lane.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KslZfu4KBkUpFik8ret:-Ksnkkt2EMPpVqaysOUU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/05f3c2438c367522b1bac10ad9135689fb76f5f3/drake/automotive/maliput/multilane/lane.cc#L37)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  It occurs to me that the loss of `p_scale_` as a variable name makes the math a bit more opaque (as if it is not opaque enough already).  It is the length of the planar reference curve... but it's function as a scale-factor is more important (because that plays into how it propagates through the equations).

Suggested resolution:  simply rename `RoadCurve::length()` to `RoadCurve::p_scale()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Ksnkqlnm7rpRInsDRhp:b-rjngbt)*

**Comment by maddog-tri** [comment]
:lgtm:   

(Thanks for the pointer to the next PR branch, though I won't be able to look at it until much later today.)

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Kso4zqD5jlP-2-0VK_s:b-2fe5rr)*

**Comment by agalbachicar** [comment]
+@seancurtis-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Kso7B1mjkPAi7Uum5vJ:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

:LGTM: with some cosmetic issues:

1. multilane_lanes_test.cc could use some clang-format love on the sections of code that were modified.
2. There is some new doxygen that is a bit confusing -- I'd like explicit confirmation from the feature reviewer that we're all god.

---

Reviewed 12 of 13 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/maliput/multilane/segment.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoLbvXa_7tu4xqbAsB:-KsoLbvXa_7tu4xqbAsC:b-dri7yz) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/segment.h#L49)):*
> ```objc
>   /// @param id Lane's ID.
>   /// @param lane_bounds Lateral extents of the Lane's frame in which the car is
>   /// supposed to be inside the lane.
> ```

FYI Very confusing comments. THe distinction between `lane_bounds` and `drivable_bounds` is unclear. @maddog-tri Did you look at the doxygen for these two parameters? If you're happy with them, I'll be content. But I find them difficult to parse.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 373 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoN9wmf5c1n3Iv3tN-:-KsoN9wmf5c1n3Iv3tN0:b9cw7k8) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L373)):*
> ```cpp
>                                     zp, zp);
>   Segment* s4 = rg.NewJunction({"j4"})->NewSegment({"s4"},
>       std::move(road_curve_4));
> ```

BTW Suspicious indentation.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 376 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNg6KCFR0DyrMdvJA:-KsoNg6KCFR0DyrMdvJB:bfiwb8n) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L376)):*
> ```cpp
>   Lane* l2_wrap = s4->NewLane(
>       {"l2_wrap"},
>       {-5., 5.}, {-kHalfWidth, kHalfWidth}, {0., kMaxHeight});
> ```

FYI Could use some clang format love.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 458 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNd1C64AY9xAw1Mbi:-KsoNd1C64AY9xAw1Mbj:b2lcs6e) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L458)):*
> ```cpp
>       std::make_unique<ArcRoadCurve>(Vector2<double>(100., -75.), 100.0,
>           0.25 * M_PI, 1.5 * M_PI, zp,
>           CubicPolynomial((kTheta) / (100. * 1.5 * M_PI), 0., 0., 0.));
> ```

BTW Suspicious indentation

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 460 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNsTt3kHdJBKnKj8f:-KsoNsTt3kHdJBKnKj8g:b-ywu266) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L460)):*
> ```cpp
>           CubicPolynomial((kTheta) / (100. * 1.5 * M_PI), 0., 0., 0.));
>   Segment* s1 = rg.NewJunction({"j1"})->NewSegment({"s1"},
>       std::move(road_curve_1));
> ```

FYI clang-format

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 463 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNu3sMPH6WRAjED7z:-KsoNu3sMPH6WRAjED8-:b-tref0t) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L463)):*
> ```cpp
>   Lane* l2 = s1->NewLane(
>       {"l2"},
>       {-5., 5.}, {-10., 10.}, {0., 5.});
> ```

BTW clang-format

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 583 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoO2MaPsb8kka6md-l:-KsoO2MaPsb8kka6md-m:b-tref0t) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L583)):*
> ```cpp
>   std::unique_ptr<RoadCurve> road_curve_1 =
>       std::make_unique<ArcRoadCurve>(Vector2<double>(-100., -100.), 100.,
>           theta0, d_theta, kHillPolynomial, zp);
> ```

BTW clang-format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KsoGdMyaWrJ64qAAYPq:b-i66pp4)*

**Comment by SeanCurtis-TRI** [comment]
MOre generally, you should clang format all of the sections you edited. I hadn't labeled *all* of the indentation issues; it became repetitive. You still have some left and I've pointed out a couple of them.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-Ksol_m9CI6uqECOBC9T:-Ksol_m9CI6uqECOBC9U:b-yrp19) ([raw file](https://github.com/robotlocomotion/drake/blob/287b7197c486e0072d4107325e156f4f0ef748c1/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L46)):*
> ```cpp
>   std::unique_ptr<RoadCurve> road_curve_1 =
>       std::make_unique<LineRoadCurve>(Vector2<double>(100., -75.),
>                                      Vector2<double>(100., 50.),
> ```

BTW meta: I placed too many specific comments. You need to do clang format on *all* the regions you've edited. This, for example, has alignment issues.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-Ksollr7_kxRimoVLxIa:-Ksollr7_kxRimoVLxIb:byvirtd) ([raw file](https://github.com/robotlocomotion/drake/blob/287b7197c486e0072d4107325e156f4f0ef748c1/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L50)):*
> ```cpp
>                                      zp);
>   Segment* s1 = rg.NewJunction({"j1"})->NewSegment({"s1"},
>       std::move(road_curve_1));
> ```

BTW format issues, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Ksom-AzUmZDrQkTjruX:bk7tcn7)*

**Comment by maddog-tri** [comment]
I'm willing to admit that there is a bit of the supernatural in all of us.  And, yes, the noted doxygen is acceptable.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/automotive/maliput/multilane/segment.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoLbvXa_7tu4xqbAsB:-Kst2e0sQPhxTUGSfY3u:b-70qiiq) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/segment.h#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Very confusing comments. THe distinction between `lane_bounds` and `drivable_bounds` is unclear. @maddog-tri Did you look at the doxygen for these two parameters? If you're happy with them, I'll be content. But I find them difficult to parse.
</blockquote></details>

I'm okay with them --- they are pretty much terms-of-art in the maliput world, and the maliput design doc and API docstrings explain lane-bounds and driveable-bounds in greater detail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-Kst3KzRg9BEA4vNIfwt:b-kgonfb)*

**Comment by SeanCurtis-TRI** [comment]
Ba dum, CHING!

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/automotive/maliput/multilane/segment.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoLbvXa_7tu4xqbAsB:-KstBDmhAqUR2mPcmek0:b-8wvhc2) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/segment.h#L49)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

I'm okay with them --- they are pretty much terms-of-art in the maliput world, and the maliput design doc and API docstrings explain lane-bounds and driveable-bounds in greater detail.
</blockquote></details>

Groovy, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KstBHcgdhZNDCmYeOoa:bdb9mgo)*

**Comment by agalbachicar** [comment]
New revision submitted. PTAL.

---

Review status: 19 of 20 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 373 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoN9wmf5c1n3Iv3tN-:-KsxbGteH7O-35_gchjR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L373)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Suspicious indentation.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 376 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNg6KCFR0DyrMdvJA:-KsxbJZYc39YaiNTQbG2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L376)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Could use some clang format love.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 458 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNd1C64AY9xAw1Mbi:-KsoTIcK8xv9_9Y8f87O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L458)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Suspicious indentation
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 460 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNsTt3kHdJBKnKj8f:-KsxbOnT00-N6jMGm_dm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L460)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI clang-format
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 463 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoNu3sMPH6WRAjED7z:-KsxbRHhQD5UftFvg3Ew:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L463)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW clang-format
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 583 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-KsoO2MaPsb8kka6md-l:-KsxbTul_t02X1BlqN_T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fee5aa0b32cb8654a11477b3cb0ab1e226d96ae/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L583)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW clang-format
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-Ksol_m9CI6uqECOBC9T:-KsxY4v51zSMGlDl3O-x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/287b7197c486e0072d4107325e156f4f0ef748c1/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L46)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW meta: I placed too many specific comments. You need to do clang format on *all* the regions you've edited. This, for example, has alignment issues.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/multilane/test/multilane_lanes_test.cc, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-Ksollr7_kxRimoVLxIa:-KsxY9zcYvO9pY0bHvjE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/287b7197c486e0072d4107325e156f4f0ef748c1/drake/automotive/maliput/multilane/test/multilane_lanes_test.cc#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW format issues, etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6934#-:-KsomOkqU746vJVcZ9uY:bh36bzm)*

**Pull request merged**
