### PR TITLE
call_matlab_client: add instructions and reduce erroneous errors to quiet returns

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6962)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-:-KtEOrIRSVD5_Aq03rUm:b-fcupkv)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/call_matlab_client.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtEbTozGoFIQ3Dwol_o:-KtEbTozGoFIQ3Dwol_p:b-owre17) ([raw file](https://github.com/robotlocomotion/drake/blob/1dcebd974151e3499042de04e1e152b1059b1841/drake/matlab/util/call_matlab_client.cc#L67)):*
> ```cpp
>     drake::common::MatlabRPC message;
>     if (!message.MergePartialFromCodedStream(&input)) {
>       mexErrMsgTxt("Failed to read from coded stream");
> ```

For my educational purpose, why we stop throwing the error here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-:-KtEbCROnqYh2s_m23lE:b-mkkz8q)*

**Comment by RussTedrake** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/call_matlab_client.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtEbTozGoFIQ3Dwol_o:-KtEczPvzHnSxxhUEqjA:b-g58hnm) ([raw file](https://github.com/robotlocomotion/drake/blob/1dcebd974151e3499042de04e1e152b1059b1841/drake/matlab/util/call_matlab_client.cc#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For my educational purpose, why we stop throwing the error here?
</blockquote></details>

it was being thrown consistently at the end of file, and i found examples using this as a return condition on the protobuf docs.   i would love to understand it more completely, but for now just need it to work better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/call_matlab_client.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtEbTozGoFIQ3Dwol_o:-KtEoaQUWgzLxqIem8zW:b-wsvasg) ([raw file](https://github.com/robotlocomotion/drake/blob/1dcebd974151e3499042de04e1e152b1059b1841/drake/matlab/util/call_matlab_client.cc#L67)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it was being thrown consistently at the end of file, and i found examples using this as a return condition on the protobuf docs.   i would love to understand it more completely, but for now just need it to work better.
</blockquote></details>

Thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/matlab_bindings.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHanAu3KXs2ikpUoom:-KtHanAu3KXs2ikpUoon:b-qxjay1) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/doc/matlab_bindings.rst#L30)):*
> ```reStructuredText
> with::
> 
>   cd /usr/local/MATLAB/R2017a/sys/os/glnxa64
> ```

Q: do we support Matlab2017a? I thought that our support is up to 2016a.

---

*[drake/doc/matlab_bindings.rst, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbKE4jv32UFPqZOiJ:-KtHbKE4jv32UFPqZOiK:b3ep0w8) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/doc/matlab_bindings.rst#L45)):*
> ```reStructuredText
> 
> Restart MATLAB if you had any sessions open for the changes to take effect.
>   
> ```

BTW, trailing whitespaces.

---

*[drake/matlab/util/call_matlab_client.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbN6Q1bkUTSOEkd-D:-KtHbN6Q1bkUTSOEkd-E:b3ep0w8) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/matlab/util/call_matlab_client.cc#L68)):*
> ```cpp
>     drake::common::MatlabRPC message;
>     if (!message.MergePartialFromCodedStream(&input)) {
>       return;  
> ```

BTW, trailing whitespaces.

---

*[drake/matlab/util/call_matlab_client.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbNXFcH-9a-pn6uFQ:-KtHbNXFcH-9a-pn6uFR:b3ep0w8) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/matlab/util/call_matlab_client.cc#L71)):*
> ```cpp
>     }
>     if (!input.ConsumedEntireMessage()) {
>       return;  
> ```

BTW, trailing whitespaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-:-KtHbO9yzy9mveuCKibR:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/matlab_bindings.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHanAu3KXs2ikpUoom:-KtI2XRUq964UDnvosk-:bh82nch) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/doc/matlab_bindings.rst#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Q: do we support Matlab2017a? I thought that our support is up to 2016a.
</blockquote></details>

We do, but someone needs to update the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/matlab_bindings.rst, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHanAu3KXs2ikpUoom:-KtJWs8ILuFXiX0SV-Mh:b7k322f) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/doc/matlab_bindings.rst#L30)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We do, but someone needs to update the documentation.
</blockquote></details>

Doh.  i went to find that spot in the documentation, and found the matching instructions already available in ubuntu_trusty.rst.  am reverting this file.

i've also updated the installation doc.  @jamiesnape -- please check me on the CI version note.

---

*[drake/doc/matlab_bindings.rst, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbKE4jv32UFPqZOiJ:-KtJZe2kBcnyiBIWM6Lc:b2nhjff) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/doc/matlab_bindings.rst#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, trailing whitespaces.
</blockquote></details>

N/A

---

*[drake/matlab/util/call_matlab_client.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbN6Q1bkUTSOEkd-D:-KtJZbbgwi3eLsAO76pF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/matlab/util/call_matlab_client.cc#L68)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, trailing whitespaces.
</blockquote></details>

Done.

---

*[drake/matlab/util/call_matlab_client.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-KtHbNXFcH-9a-pn6uFQ:-KtJZcvmQia2gyPZmjW-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/26c1ab81b7441de3981056b81eb09fbb3899881c/drake/matlab/util/call_matlab_client.cc#L71)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, trailing whitespaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962)*

**Comment by RussTedrake** [comment]
+@jamiesnape for additional feature review.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-:-KtL1gPqdbra-9csBDsu:b-ek5rsp)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6962#-:-KtMLLRa30E9K5Hje7RD:bnfp4nl)*

**Pull request merged**
