### PR TITLE
Explicitly set font-family for all monospaced HTML elements

### LINKED ISSUE #13950: CalcJacobianSpatialVelocity documentation render badly on mac
image

It seems that our previous font gymnastics did not work for this one?  (some of the other jacobian methods are borked, too)

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #13950.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13952)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@RussTedrake for review.

**Comment by RussTedrake** [comment]
I've tried to test this locally, but for some reason that I cannot explain... running doxygen locally on mac produces a `MultibodyPlant` page that does not even include `CalcJacobianSpatialVelocity` and friends.  This is true on master as well as on your feature branch.

I spent a time on it (building even just `multibody` doxygen locally here takes forever), but am afraid I don't have time today to continue to debug.

**Comment by jwnimmer-tri** [comment]
If +@soonho-tri can confirm that this resolves the n subscript problem he saw, then that's probably good enough evidence to merge this, and afterwards continue to debug if Russ continues to sees problems once deployed.

**Comment by soonho-tri** [comment]
I have the same issue that @RussTedrake reported above. I ran `bazel-bin/doc/doxygen`, but the generated doc does not include `CalcJacobianSpatialVelocity`:

Screen Shot 2020-08-29 at 1 33 48 PM

My env:
- macOS-10.15.6
- Doxygen-1.8.20

**Comment by jwnimmer-tri** [comment]
On Ubuntu, it creates the doc for me.  In the log there is (just one) warning related to this method: `multibody_plant.h:2782: warning: argument 'J𝑠_V_ABp_E' of command @param is not found in the argument list`.

The `@param` must use the C++ variable name, not the unicode.  I don't know if that's what is confusing macOS, but it might be worth a shot.

**Comment by RussTedrake** [comment]
but as you can see from @soonho-tri 's screenshot, actually *none* of the jacobian methods are getting through...

**Comment by soonho-tri** [comment]
> If soonho-tri can confirm that this resolves the n subscript problem he saw, then that's probably good enough evidence to merge this, and afterwards continue to debug if Russ continues to sees problems once deployed.

FYI, Safari still has an issue rendering the subscript `_n`.

**Comment by jamiesnape** [comment]
> FYI, Safari still has an issue rendering the subscript _n.

It did fix the issue for me. I will double check later.

**Comment by jamiesnape** [comment]
`S_n` renders fine for me in the generated docs with Safari on iOS and macOS: https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#a5f39a8f68fae3de53767a281503a3313

**Comment by soonho-tri** [comment]
Screen Shot 2020-09-01 at 11 55 53 AM

OK. I can confirm that.

**Pull request merged**
