### PR TITLE
Sherm intrinsics+rico

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Ongoing work to help with integrating Sherm's intrinsics-based speedups. Not meant to be merged or reviewed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @sherm1  -- a few fixes in here, and a thread safety test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611#-:-MSUMLTc6F91eX34dxdI:bj0l896)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sherm1 — COMMENTED** [review]
Looks good -- any word on whether it's fast yet?

Per discussion in #14603, we may want to restrict enabling AVX to just places where we are explicitly using the instructions. Here that would require moving some of the PoolVector inline methods into the cc file. I don't _think_ that would affect performance noticeably since we tend to move hefty chunks of data per call.

BTW the latest proposal for flags is to use `-march=broadwell` as the only additional flag.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611#-:-MS__4BM9W4-lH5eZSVl:b-buu4g)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[multibody/tree/multibody_forces.h, line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MS_Zm6zDaBlE1ol79cU:-MS_Zm6zDaBlE1ol79cV:b51wxtc) ([raw file](https://github.com/robotlocomotion/drake/blob/e226799576577afebed804f4a55c23779b0eae6e/multibody/tree/multibody_forces.h#L42)):*
> ```objc
>   ///
>   ///
>   /// --eful for constructing the MultibodyForces structure
> ```

nit edit mangle

**Review by sherm1 — COMMENTED** [review]
In addition to thread safety, we would have to allow for an assortment of pool sizes and some bit hacks to grab the right power-of-2 given a size request. That would also cost some cpu cycles, though I think only a few instructions. Only worth doing if the current version (or some tweak of it) is fast now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611#-:-MS_aNEn5RjiooFADPJR:bkghbp8)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
FWIW, the pool sizes and thread safety were probably what sunk my dense pool PR train. Perhaps we can do better this time?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611#-:-MSdLA2N61HeijPkUc69:b-q5s3uc)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Oh ick. I may have overwritten changes from your r3. Investigating.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611#-:-MSdeLz5DiO0wFLqE_mZ:b-7qj2gh)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MSdetCy8ctp6pkNihMN:-MSdetCy8ctp6pkNihMO:b799n3w) (no related file):*
I ran a comparison from master at 606ea96a4a to what I think is r4. Results so far are disappointing, but perhaps I'm missing some compile flags or something.

```
               -0.3170         -0.3170       4038009       2758156       4037792       2757986
rico@Puget-161804-10:~/checkout/drake$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-606ea96a4a/results.json intrinsics-rebase-onto-606ea96a4a/results.json |grep _m
CassieDoubleFixture/DoubleMassMatrix_mean                           +0.0218         +0.0218         14323         14635         14322         14634
CassieDoubleFixture/DoubleMassMatrix_median                         +0.0218         +0.0218         14314         14626         14313         14626
CassieDoubleFixture/DoubleMassMatrix_min                            +0.0183         +0.0183         14177         14437         14177         14436
CassieDoubleFixture/DoubleMassMatrix_max                            +0.0467         +0.0467         14542         15221         14541         15221
CassieDoubleFixture/DoubleInverseDynamics_mean                      -0.0041         -0.0041         21097         21010         21096         21009
CassieDoubleFixture/DoubleInverseDynamics_median                    -0.0021         -0.0021         21049         21006         21048         21005
CassieDoubleFixture/DoubleInverseDynamics_min                       -0.0072         -0.0071         20779         20631         20778         20630
CassieDoubleFixture/DoubleInverseDynamics_max                       -0.0171         -0.0171         22003         21626         22002         21625
CassieDoubleFixture/DoubleForwardDynamics_mean                      +0.0648         +0.0648         44624         47515         44622         47513
CassieDoubleFixture/DoubleForwardDynamics_median                    +0.0647         +0.0647         44622         47508         44620         47506
CassieDoubleFixture/DoubleForwardDynamics_min                       +0.0625         +0.0625         44055         46807         44053         46805
CassieDoubleFixture/DoubleForwardDynamics_max                       +0.0642         +0.0642         45307         48215         45304         48213
CassieAutodiffFixture/AutodiffMassMatrix_mean                       -0.2494         -0.2494       1911292       1434595       1911199       1434531
CassieAutodiffFixture/AutodiffMassMatrix_median                     -0.2426         -0.2426       1901311       1439994       1901189       1439944
CassieAutodiffFixture/AutodiffMassMatrix_min                        -0.2884         -0.2884       1877191       1335772       1877092       1335747
CassieAutodiffFixture/AutodiffMassMatrix_max                        -0.2614         -0.2614       1976290       1459715       1976155       1459627
CassieAutodiffFixture/AutodiffInverseDynamics_mean                  -0.3991         -0.3990       2804290       1685235       2804154       1685163
CassieAutodiffFixture/AutodiffInverseDynamics_median                -0.3940         -0.3940       2780317       1684969       2780204       1684910
CassieAutodiffFixture/AutodiffInverseDynamics_min                   -0.3884         -0.3884       2752057       1683197       2751850       1683114
CassieAutodiffFixture/AutodiffInverseDynamics_max                   -0.4296         -0.4296       2983321       1701565       2983164       1701474
CassieAutodiffFixture/AutodiffForwardDynamics_mean                  -0.3060         -0.3060       3897507       2704811       3897316       2704695
CassieAutodiffFixture/AutodiffForwardDynamics_median                -0.3043         -0.3043       3892470       2708079       3892315       2707948
CassieAutodiffFixture/AutodiffForwardDynamics_min                   -0.3112         -0.3112       3843602       2647648       3843526       2647517
CassieAutodiffFixture/AutodiffForwardDynamics_max                   -0.3170         -0.3170       4038009       2758156       4037792       2757986
```

Roughly 3% wins are nothing to write home about. Did I mess up the experiment somewhere?

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MSdetCy8ctp6pkNihMN:-MSeDJgD3feX-dceJjnZ:b-gu6l) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I ran a comparison from master at 606ea96a4a to what I think is r4. Results so far are disappointing, but perhaps I'm missing some compile flags or something.

```
               -0.3170         -0.3170       4038009       2758156       4037792       2757986
rico@Puget-161804-10:~/checkout/drake$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-606ea96a4a/results.json intrinsics-rebase-onto-606ea96a4a/results.json |grep _m
CassieDoubleFixture/DoubleMassMatrix_mean                           +0.0218         +0.0218         14323         14635         14322         14634
CassieDoubleFixture/DoubleMassMatrix_median                         +0.0218         +0.0218         14314         14626         14313         14626
CassieDoubleFixture/DoubleMassMatrix_min                            +0.0183         +0.0183         14177         14437         14177         14436
CassieDoubleFixture/DoubleMassMatrix_max                            +0.0467         +0.0467         14542         15221         14541         15221
CassieDoubleFixture/DoubleInverseDynamics_mean                      -0.0041         -0.0041         21097         21010         21096         21009
CassieDoubleFixture/DoubleInverseDynamics_median                    -0.0021         -0.0021         21049         21006         21048         21005
CassieDoubleFixture/DoubleInverseDynamics_min                       -0.0072         -0.0071         20779         20631         20778         20630
CassieDoubleFixture/DoubleInverseDynamics_max                       -0.0171         -0.0171         22003         21626         22002         21625
CassieDoubleFixture/DoubleForwardDynamics_mean                      +0.0648         +0.0648         44624         47515         44622         47513
CassieDoubleFixture/DoubleForwardDynamics_median                    +0.0647         +0.0647         44622         47508         44620         47506
CassieDoubleFixture/DoubleForwardDynamics_min                       +0.0625         +0.0625         44055         46807         44053         46805
CassieDoubleFixture/DoubleForwardDynamics_max                       +0.0642         +0.0642         45307         48215         45304         48213
CassieAutodiffFixture/AutodiffMassMatrix_mean                       -0.2494         -0.2494       1911292       1434595       1911199       1434531
CassieAutodiffFixture/AutodiffMassMatrix_median                     -0.2426         -0.2426       1901311       1439994       1901189       1439944
CassieAutodiffFixture/AutodiffMassMatrix_min                        -0.2884         -0.2884       1877191       1335772       1877092       1335747
CassieAutodiffFixture/AutodiffMassMatrix_max                        -0.2614         -0.2614       1976290       1459715       1976155       1459627
CassieAutodiffFixture/AutodiffInverseDynamics_mean                  -0.3991         -0.3990       2804290       1685235       2804154       1685163
CassieAutodiffFixture/AutodiffInverseDynamics_median                -0.3940         -0.3940       2780317       1684969       2780204       1684910
CassieAutodiffFixture/AutodiffInverseDynamics_min                   -0.3884         -0.3884       2752057       1683197       2751850       1683114
CassieAutodiffFixture/AutodiffInverseDynamics_max                   -0.4296         -0.4296       2983321       1701565       2983164       1701474
CassieAutodiffFixture/AutodiffForwardDynamics_mean                  -0.3060         -0.3060       3897507       2704811       3897316       2704695
CassieAutodiffFixture/AutodiffForwardDynamics_median                -0.3043         -0.3043       3892470       2708079       3892315       2707948
CassieAutodiffFixture/AutodiffForwardDynamics_min                   -0.3112         -0.3112       3843602       2647648       3843526       2647517
CassieAutodiffFixture/AutodiffForwardDynamics_max                   -0.3170         -0.3170       4038009       2758156       4037792       2757986
```

Roughly 3% wins are nothing to write home about. Did I mess up the experiment somewhere?
</blockquote></details>

:facepalm: misread the numbers. The wins are more like 30 or 40%.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MSdetCy8ctp6pkNihMN:-MSiD4YD5YJwj2WyyYJU:b54hle5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

:facepalm: misread the numbers. The wins are more like 30 or 40%.
</blockquote></details>

Another experiment -- how much does pool allocation matter? I just commented out the magic preprocessor symbol and did another comparison against (newer) master:

<pre><font color="#8AE234"><b>rico@Puget-161804-10</b></font>:<font color="#729FCF"><b>~/checkout/drake</b></font>$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-c3e739095b/results.json intrinsics-rebased-onto-c3e739095b-no-pool/results.json |grep _m
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>ean                  <font color="#EEEEEC">         +0.0288         +0.0288</font>         14257         14668         14257         14668
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>edian                <font color="#EEEEEC">         +0.0281         +0.0281</font>         14254         14655         14254         14655
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>in                   <font color="#EEEEEC">         +0.0272         +0.0272</font>         14122         14506         14121         14506
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>ax                   <font color="#EF2929">         +0.0516         +0.0516</font>         14411         15155         14410         15154
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ean             <font color="#EEEEEC">         -0.0023         -0.0023</font>         21157         21108         21156         21107
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>edian           <font color="#EEEEEC">         -0.0041         -0.0041</font>         21152         21065         21151         21064
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>in              <font color="#EEEEEC">         -0.0012         -0.0012</font>         20907         20881         20906         20880
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ax              <font color="#EEEEEC">         -0.0035         -0.0035</font>         21673         21596         21672         21595
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ean             <font color="#EF2929">         +0.0670         +0.0670</font>         44804         47804         44801         47802
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>edian           <font color="#EF2929">         +0.0667         +0.0667</font>         44817         47808         44815         47805
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>in              <font color="#EF2929">         +0.0647         +0.0647</font>         44122         46976         44120         46976
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ax              <font color="#EF2929">         +0.0715         +0.0716</font>         45441         48691         45438         48690
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>ean              <font color="#EF2929">         +3.8100         +3.8100</font>       1905324       9164588       1905234       9164183
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>edian            <font color="#EF2929">         +3.8082         +3.8081</font>       1897118       9121701       1897052       9121198
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>in               <font color="#EF2929">         +3.7227         +3.7227</font>       1871404       8838038       1871370       8837949
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>ax               <font color="#EF2929">         +3.6284         +3.6284</font>       2092579       9685354       2092455       9684670
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ean         <font color="#EF2929">         +3.2183         +3.2183</font>       2798402      11804388       2798271      11803888
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>edian       <font color="#EF2929">         +3.2449         +3.2449</font>       2779572      11798947       2779458      11798539
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>in          <font color="#EF2929">         +3.2661         +3.2664</font>       2724789      11624180       2724581      11624052
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ax          <font color="#EF2929">         +2.9826         +2.9824</font>       3011886      11995040       3011837      11994379
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ean         <font color="#EF2929">         +3.3753         +3.3753</font>       3937147      17226239       3936965      17225480
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>edian       <font color="#EF2929">         +3.3647         +3.3646</font>       3933341      17167759       3933137      17166634
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>in          <font color="#EF2929">         +3.2235         +3.2237</font>       3894985      16450566       3894752      16450385
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ax          <font color="#EF2929">         +3.5142         +3.5142</font>       4010389      18103725       4010170      18102849
</pre>

Three times slower was a bit of a surprise to me. I'd like to know why.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MSdetCy8ctp6pkNihMN:-MT379AH2AeybaqX_oe4:bbjgv7u) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Another experiment -- how much does pool allocation matter? I just commented out the magic preprocessor symbol and did another comparison against (newer) master:

<pre><font color="#8AE234"><b>rico@Puget-161804-10</b></font>:<font color="#729FCF"><b>~/checkout/drake</b></font>$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-c3e739095b/results.json intrinsics-rebased-onto-c3e739095b-no-pool/results.json |grep _m
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>ean                  <font color="#EEEEEC">         +0.0288         +0.0288</font>         14257         14668         14257         14668
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>edian                <font color="#EEEEEC">         +0.0281         +0.0281</font>         14254         14655         14254         14655
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>in                   <font color="#EEEEEC">         +0.0272         +0.0272</font>         14122         14506         14121         14506
<font color="#8AE234">CassieDoubleFixture/DoubleMassMatrix</font><font color="#EF2929"><b>_m</b></font>ax                   <font color="#EF2929">         +0.0516         +0.0516</font>         14411         15155         14410         15154
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ean             <font color="#EEEEEC">         -0.0023         -0.0023</font>         21157         21108         21156         21107
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>edian           <font color="#EEEEEC">         -0.0041         -0.0041</font>         21152         21065         21151         21064
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>in              <font color="#EEEEEC">         -0.0012         -0.0012</font>         20907         20881         20906         20880
<font color="#8AE234">CassieDoubleFixture/DoubleInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ax              <font color="#EEEEEC">         -0.0035         -0.0035</font>         21673         21596         21672         21595
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ean             <font color="#EF2929">         +0.0670         +0.0670</font>         44804         47804         44801         47802
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>edian           <font color="#EF2929">         +0.0667         +0.0667</font>         44817         47808         44815         47805
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>in              <font color="#EF2929">         +0.0647         +0.0647</font>         44122         46976         44120         46976
<font color="#8AE234">CassieDoubleFixture/DoubleForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ax              <font color="#EF2929">         +0.0715         +0.0716</font>         45441         48691         45438         48690
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>ean              <font color="#EF2929">         +3.8100         +3.8100</font>       1905324       9164588       1905234       9164183
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>edian            <font color="#EF2929">         +3.8082         +3.8081</font>       1897118       9121701       1897052       9121198
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>in               <font color="#EF2929">         +3.7227         +3.7227</font>       1871404       8838038       1871370       8837949
<font color="#8AE234">CassieAutodiffFixture/AutodiffMassMatrix</font><font color="#EF2929"><b>_m</b></font>ax               <font color="#EF2929">         +3.6284         +3.6284</font>       2092579       9685354       2092455       9684670
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ean         <font color="#EF2929">         +3.2183         +3.2183</font>       2798402      11804388       2798271      11803888
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>edian       <font color="#EF2929">         +3.2449         +3.2449</font>       2779572      11798947       2779458      11798539
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>in          <font color="#EF2929">         +3.2661         +3.2664</font>       2724789      11624180       2724581      11624052
<font color="#8AE234">CassieAutodiffFixture/AutodiffInverseDynamics</font><font color="#EF2929"><b>_m</b></font>ax          <font color="#EF2929">         +2.9826         +2.9824</font>       3011886      11995040       3011837      11994379
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ean         <font color="#EF2929">         +3.3753         +3.3753</font>       3937147      17226239       3936965      17225480
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>edian       <font color="#EF2929">         +3.3647         +3.3646</font>       3933341      17167759       3933137      17166634
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>in          <font color="#EF2929">         +3.2235         +3.2237</font>       3894985      16450566       3894752      16450385
<font color="#8AE234">CassieAutodiffFixture/AutodiffForwardDynamics</font><font color="#EF2929"><b>_m</b></font>ax          <font color="#EF2929">         +3.5142         +3.5142</font>       4010389      18103725       4010170      18102849
</pre>

Three times slower was a bit of a surprise to me. I'd like to know why.
</blockquote></details>

So, yes, adding thread-safety (a fairly simple way) is expensive. Kill more than half of the wins from careful assembly crafting of the arithmetic. Here are numbers comparing a thread-safe version with the master it was branched from:
```
rico@Puget-161804-10:~/checkout/drake$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-dc9403e55d/results.json intrinsics-from-master-dc9403e55d-threadsafe2/results.json |grep _m
CassieDoubleFixture/DoubleMassMatrix_mean                           +0.1233         +0.1233         14246         16003         14246         16002
CassieDoubleFixture/DoubleMassMatrix_median                         +0.1219         +0.1219         14254         15991         14253         15991
CassieDoubleFixture/DoubleMassMatrix_min                            +0.1227         +0.1227         14137         15872         14136         15871
CassieDoubleFixture/DoubleMassMatrix_max                            +0.1348         +0.1348         14346         16279         14345         16278
CassieDoubleFixture/DoubleInverseDynamics_mean                      -0.0397         -0.0397         21307         20461         21306         20460
CassieDoubleFixture/DoubleInverseDynamics_median                    -0.0378         -0.0378         21237         20434         21236         20434
CassieDoubleFixture/DoubleInverseDynamics_min                       -0.0403         -0.0403         21065         20216         21064         20215
CassieDoubleFixture/DoubleInverseDynamics_max                       -0.0467         -0.0467         21839         20819         21839         20818
CassieDoubleFixture/DoubleForwardDynamics_mean                      +0.0889         +0.0889         43793         47684         43791         47682
CassieDoubleFixture/DoubleForwardDynamics_median                    +0.0904         +0.0904         43709         47659         43707         47657
CassieDoubleFixture/DoubleForwardDynamics_min                       +0.0878         +0.0878         43216         47011         43214         47008
CassieDoubleFixture/DoubleForwardDynamics_max                       +0.0769         +0.0768         45095         48562         45095         48560
CassieAutodiffFixture/AutodiffMassMatrix_mean                       -0.0157         -0.0157       1892574       1862778       1892495       1862703
CassieAutodiffFixture/AutodiffMassMatrix_median                     -0.0134         -0.0134       1888183       1862841       1888113       1862753
CassieAutodiffFixture/AutodiffMassMatrix_min                        +0.0005         +0.0005       1860660       1861514       1860565       1861405
CassieAutodiffFixture/AutodiffMassMatrix_max                        -0.0469         -0.0469       1955731       1864027       1955619       1863988
CassieAutodiffFixture/AutodiffInverseDynamics_mean                  -0.1528         -0.1528       2800037       2372274       2799910       2372183
CassieAutodiffFixture/AutodiffInverseDynamics_median                -0.1453         -0.1453       2775533       2372155       2775453       2372041
CassieAutodiffFixture/AutodiffInverseDynamics_min                   -0.1378         -0.1378       2748954       2370168       2748766       2370030
CassieAutodiffFixture/AutodiffInverseDynamics_max                   -0.1881         -0.1881       2923814       2373897       2923672       2373866
CassieAutodiffFixture/AutodiffForwardDynamics_mean                  -0.0837         -0.0837       3913004       3585639       3912827       3585502
CassieAutodiffFixture/AutodiffForwardDynamics_median                -0.0833         -0.0833       3911322       3585495       3911130       3585409
CassieAutodiffFixture/AutodiffForwardDynamics_min                   -0.0715         -0.0715       3858342       3582393       3858114       3582351
CassieAutodiffFixture/AutodiffForwardDynamics_max                   -0.0977         -0.0977       3976066       3587788       3976005       3587745
rico@Puget-161804-10:~/checkout/drake$ 
```

We still have gains of 8-15% over master, but that was little enough to sink prior optimization efforts. And this patch still didn't address the fixed size of derivative vectors.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14611)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14611#-MSdetCy8ctp6pkNihMN:-MT38o7cCx2cMjUSHvO1:b-omywq2) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, yes, adding thread-safety (a fairly simple way) is expensive. Kill more than half of the wins from careful assembly crafting of the arithmetic. Here are numbers comparing a thread-safe version with the master it was branched from:
```
rico@Puget-161804-10:~/checkout/drake$ bazel-drake/external/googlebenchmark/tools/compare.py benchmarks master-dc9403e55d/results.json intrinsics-from-master-dc9403e55d-threadsafe2/results.json |grep _m
CassieDoubleFixture/DoubleMassMatrix_mean                           +0.1233         +0.1233         14246         16003         14246         16002
CassieDoubleFixture/DoubleMassMatrix_median                         +0.1219         +0.1219         14254         15991         14253         15991
CassieDoubleFixture/DoubleMassMatrix_min                            +0.1227         +0.1227         14137         15872         14136         15871
CassieDoubleFixture/DoubleMassMatrix_max                            +0.1348         +0.1348         14346         16279         14345         16278
CassieDoubleFixture/DoubleInverseDynamics_mean                      -0.0397         -0.0397         21307         20461         21306         20460
CassieDoubleFixture/DoubleInverseDynamics_median                    -0.0378         -0.0378         21237         20434         21236         20434
CassieDoubleFixture/DoubleInverseDynamics_min                       -0.0403         -0.0403         21065         20216         21064         20215
CassieDoubleFixture/DoubleInverseDynamics_max                       -0.0467         -0.0467         21839         20819         21839         20818
CassieDoubleFixture/DoubleForwardDynamics_mean                      +0.0889         +0.0889         43793         47684         43791         47682
CassieDoubleFixture/DoubleForwardDynamics_median                    +0.0904         +0.0904         43709         47659         43707         47657
CassieDoubleFixture/DoubleForwardDynamics_min                       +0.0878         +0.0878         43216         47011         43214         47008
CassieDoubleFixture/DoubleForwardDynamics_max                       +0.0769         +0.0768         45095         48562         45095         48560
CassieAutodiffFixture/AutodiffMassMatrix_mean                       -0.0157         -0.0157       1892574       1862778       1892495       1862703
CassieAutodiffFixture/AutodiffMassMatrix_median                     -0.0134         -0.0134       1888183       1862841       1888113       1862753
CassieAutodiffFixture/AutodiffMassMatrix_min                        +0.0005         +0.0005       1860660       1861514       1860565       1861405
CassieAutodiffFixture/AutodiffMassMatrix_max                        -0.0469         -0.0469       1955731       1864027       1955619       1863988
CassieAutodiffFixture/AutodiffInverseDynamics_mean                  -0.1528         -0.1528       2800037       2372274       2799910       2372183
CassieAutodiffFixture/AutodiffInverseDynamics_median                -0.1453         -0.1453       2775533       2372155       2775453       2372041
CassieAutodiffFixture/AutodiffInverseDynamics_min                   -0.1378         -0.1378       2748954       2370168       2748766       2370030
CassieAutodiffFixture/AutodiffInverseDynamics_max                   -0.1881         -0.1881       2923814       2373897       2923672       2373866
CassieAutodiffFixture/AutodiffForwardDynamics_mean                  -0.0837         -0.0837       3913004       3585639       3912827       3585502
CassieAutodiffFixture/AutodiffForwardDynamics_median                -0.0833         -0.0833       3911322       3585495       3911130       3585409
CassieAutodiffFixture/AutodiffForwardDynamics_min                   -0.0715         -0.0715       3858342       3582393       3858114       3582351
CassieAutodiffFixture/AutodiffForwardDynamics_max                   -0.0977         -0.0977       3976066       3587788       3976005       3587745
rico@Puget-161804-10:~/checkout/drake$ 
```

We still have gains of 8-15% over master, but that was little enough to sink prior optimization efforts. And this patch still didn't address the fixed size of derivative vectors.
</blockquote></details>

The patch at https://github.com/robotlocomotion/drake/commit/a6d495d0c7e5de981f1b2e03314c8a38ee3e76bb shows the very simple thread safety changes I made.

---

**Pull request closed without merging**
