### PR TITLE
[multibody] Add ScopedName as a first-class citizen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Deprecate some now-unnecessary functions that were trying to accommodate its absence.

I have the Anzu upgrade PR ready in the wings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17482)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This work is nearly finished now.

FYI @amcastro-tri @calderpg-tri @EricCousineau-TRI @rpoyner-tri @SeanCurtis-TRI @sherm1

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/tree/scoped_name.h` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOaQ5KR8QgIy-gaWheh:-NOaQ5KR8QgIy-gaWhei:bee6zmi) ([raw file](https://github.com/RobotLocomotion/drake/blob/507e132d383dbdae4590d6f931b074a5418d3003/multibody/tree/scoped_name.h#L23)):*
> ```objc
> The namespace name typically refers to the model instance name that contains the
> element. Some elements live at global scope, in which case the namespace is
> empty. The namespace name will never start or end with "::".
> ```

My plan is that namespace_name will typically be "world" for world bodies.

Only in domain-specific uses (like sdformat parsing of cross-references) would be used an empty namespace to indicate the world.



_Suggestion:_
```objc
element. Some elements live at global scope, in which case the namespace
can be empty. The namespace name will never start or end with "::".
```

**Review by rpoyner-tri — COMMENTED** [review]
Passes my first smoke test; it is LOC-negative.

> Reviewed 2 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NOeaSJG4JTD5wVD9nAa:b7u1ewr)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
I'm not seeing the net-negative aspect here, but still looks good.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NOjkYe-4sFCq9KNM7LX:bqfg1r4)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`multibody/tree/scoped_name.h` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOjj_bU662NPZe6dMCA:-NOjj_bU662NPZe6dMCB:b543pwf) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ea802cf93a4934bf044fcfc1e568d9d6ed09a36/multibody/tree/scoped_name.h#L64)):*
> ```objc
> 
>   /** Parses the given `scoped_name` string. Any leading or trailing "::" on the
>   name are automatically removed. */
> ```

BTW "automatically" here isn't helping. Consider removing here and above.

**Comment by jwnimmer-tri** [comment]
> I'm not seeing the net-negative aspect here, ...

I assume Rico took a measurement from _after_ the deprecation removals would happen.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 29 of 32 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NOospqM7RI7YSbBmzku:bg7igkv)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/planning/planning_py_collision_checker.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOlMIT-2rnT_TbQrYtd:-NOlMIT-2rnT_TbQrYte:b-fhpq0) ([raw file](https://github.com/RobotLocomotion/drake/blob/239f0a4016bfcdcdefa8dd5ef1759a2a4fabe391/bindings/pydrake/planning/planning_py_collision_checker.cc#L38)):*
> ```cpp
>         .def("get_body", &Class::get_body, py::arg("body_index"),
>             py_rvp::reference_internal, cls_doc.get_body.doc)
>         .def("GetScopedName",
> ```

Do these need deprecation?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

___
*[`bindings/pydrake/planning/planning_py_collision_checker.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOlMIT-2rnT_TbQrYtd:-NOotrVtCpqATTjS8rwJ:b-l44ce9) ([raw file](https://github.com/RobotLocomotion/drake/blob/239f0a4016bfcdcdefa8dd5ef1759a2a4fabe391/bindings/pydrake/planning/planning_py_collision_checker.cc#L38)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do these need deprecation?
</blockquote></details>

If this PR lands in the next 3 weeks, deprecation is not mandatory.  They were first introduced in v1.13.0, so they are not Stable API until v1.13.0.

We could still deprecate out of kindness, but I expect nobody is actually using them.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

___
*[`bindings/pydrake/planning/planning_py_collision_checker.cc` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOlMIT-2rnT_TbQrYtd:-NOou6lu-PYGskFmbT3G:b4eww6u) ([raw file](https://github.com/RobotLocomotion/drake/blob/239f0a4016bfcdcdefa8dd5ef1759a2a4fabe391/bindings/pydrake/planning/planning_py_collision_checker.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If this PR lands in the next 3 weeks, deprecation is not mandatory.  They were first introduced in v1.13.0, so they are not Stable API until v1.13.0.

We could still deprecate out of kindness, but I expect nobody is actually using them.
</blockquote></details>

(... until v.14.0, that is.)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/tree/scoped_name.h` line 28 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17482#-NOpaA0VA84OBy4bCtqQ:-NOpaA0VA84OBy4bCtqR:b-wxwail) ([raw file](https://github.com/robotlocomotion/drake/blob/29fa2d49b6f58946a734f4b3eeb7bb776519a3d5/multibody/tree/scoped_name.h#L28)):*
> ```objc
> or moved-from. The element name will never contain the delimiter string "::".
> 
> When there is no namespace, the scoped name does not contain a leading "::",
> ```

no namespace means "default model instance"? or "world model instance"?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/tree/scoped_name.h` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOpaA0VA84OBy4bCtqQ:-NOpcDcv3INa7bFm7FGN:b-1zapaj) ([raw file](https://github.com/RobotLocomotion/drake/blob/29fa2d49b6f58946a734f4b3eeb7bb776519a3d5/multibody/tree/scoped_name.h#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

no namespace means "default model instance"? or "world model instance"?
</blockquote></details>

For MbT, every scoped name would have a namespace, which might be "world" or "DefaultModelInstance".

Sometimes during parsing, we can have a ScopedName without a namespace (yet).

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/tree/scoped_name.h` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOpaA0VA84OBy4bCtqQ:-NOycQQWCX7p0cR2DCz3:b-6xeinu) ([raw file](https://github.com/RobotLocomotion/drake/blob/29fa2d49b6f58946a734f4b3eeb7bb776519a3d5/multibody/tree/scoped_name.h#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For MbT, every scoped name would have a namespace, which might be "world" or "DefaultModelInstance".

Sometimes during parsing, we can have a ScopedName without a namespace (yet).
</blockquote></details>

I see, thanks.

**Review by jwnimmer-tri — COMMENTED** [review]
@rpoyner-tri please have another look.  I've made some clean-ups and improvements.

Once you're happy, we can send it to platform review.

\CC @EricCousineau-TRI for awareness.

-(status: do not merge) -(status: do not review)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NPQKgbg1X2JdXwzTQPE:bphyl9a)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @amcastro-tri, @rpoyner-tri, and @sherm1)

___
*[`multibody/tree/scoped_name.h` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NOpaA0VA84OBy4bCtqQ:-NPQI87vDwKv67yGXi7Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/29fa2d49b6f58946a734f4b3eeb7bb776519a3d5/multibody/tree/scoped_name.h#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see, thanks. 
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
Looking. Apparently the build failures are undamped deprecation noise.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NPSs6Nr3B5r496CzSni:b-om4vow)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

**Comment by jwnimmer-tri** [comment]
Oh no!  There is a deprecation pole on the right-half plane!  Run away!

(But yes, I'll look at the deprecation stuff now; thanks.)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NPStNld1Yn_hVWaTQZt:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_urdf_parser.cc` line 918 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTCwoGDjQAYmGMk46Z:-NPTCwoH3n41yYVtP7dN:b-y84107) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae16ea20982086c4db39eebd85278d3a59d7c67a/multibody/parsing/detail_urdf_parser.cc#L918)):*
> ```cpp
> 
>   model_name = ScopedName(
>       parent_model_name_.value_or(""), model_name).to_string();
> ```

Working

Some Anzu people use colons in their `model_name`, so this crashes.  I need to change this to `Join`, and add more Drake CI tests that would have caught this.

Ditto for SDFormat and other places that used this pattern.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1251 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTDUbl0yEl2kI5mZqB:-NPTDUbm4DlLJDfIhVUY:b-oxf2wa) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae16ea20982086c4db39eebd85278d3a59d7c67a/multibody/parsing/detail_mujoco_parser.cc#L1251)):*
> ```cpp
>     }
>     model_name =
>         ScopedName::Join(parent_model_name.value_or(""), model_name).get_full();
> ```

Working

Needs to use Join, and unit test.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1251 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTDUbl0yEl2kI5mZqB:-NPTDjOZAL8fCmgu7rqC:b-qnnr6y) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae16ea20982086c4db39eebd85278d3a59d7c67a/multibody/parsing/detail_mujoco_parser.cc#L1251)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs to use Join, and unit test.
</blockquote></details>

Derp.  This is already a join.  Only URDF was broken.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[`multibody/parsing/detail_urdf_parser.cc` line 918 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTCwoGDjQAYmGMk46Z:-NPTFk6JCIAEazb0iQNl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae16ea20982086c4db39eebd85278d3a59d7c67a/multibody/parsing/detail_urdf_parser.cc#L918)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Some Anzu people use colons in their `model_name`, so this crashes.  I need to change this to `Join`, and add more Drake CI tests that would have caught this.

Ditto for SDFormat and other places that used this pattern.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor suggestions and some ignorable rambling thoughts

> Reviewed 18 of 32 files at r2, 2 of 4 files at r4, 11 of 13 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NPTkBN11PjXB4euDw6r:bb98xj8)* status: 12 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_collision_filter_group_resolver.cc` line 125 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTg4Jt26-cRPGJcGFX:-NPTg4Jt26-cRPGJcGFY:b-98t0zp) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/parsing/detail_collision_filter_group_resolver.cc#L125)):*
> ```cpp
>   }
>   const std::string& model_name = plant_->GetModelInstanceName(*model_instance);
>   return std::string{ScopedName::Join(model_name, name).to_string()};
> ```

nit: to_string() already returns std::string so shouldn't need this constructor
___
*[`multibody/parsing/detail_dmd_parser.cc` line 121 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPThLBY1U1hdGhnUgA4:-NPThLBY1U1hdGhnUgA5:bt4v7ca) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/parsing/detail_dmd_parser.cc#L121)):*
> ```cpp
>         parsed.set_namespace(
>             ScopedName::Join(model_namespace, parsed.get_namespace())
>                 .get_full());
> ```

BTW see my comment on Join() -- I was surprised by this use case where the "element" field is temporarily used as a namespace segment. No complaint about the use, should just be acknowledged as an acceptable use of Join().
___
*[`multibody/tree/body.h` line 194 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTjHbyDcdx9BDcKG_U:-NPTjHbyDcdx9BDcKG_V:blyql61) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/body.h#L194)):*
> ```objc
> 
>   /// Returns scoped name of this frame. Neither of the two pieces of the name
>   /// will be empty (the scope name and the element name).
> ```

BTW can this be the World Body and if so is there still a non-empty namespace name for it?
___
*[`multibody/tree/body.cc` line 57 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTjmXMBQNdqxGzBu8y:-NPTjmXMBQNdqxGzBu8z:b8nivam) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/body.cc#L57)):*
> ```cpp
> // GSG best practices that trying to do the entire class here doesn't work.
> DRAKE_DEFINE_FUNCTION_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS((
>     &drake::multibody::Body<T>::scoped_name
> ```

BTW sad to see this non-T-dependent function have to be instantiated multiple times :(
___
*[`multibody/tree/scoped_name.h` line 24 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTOwASBTXlUOL8VT0Q:-NPTOwASBTXlUOL8VT0R:byp0xtk) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L24)):*
> ```objc
> element. Some temporary scoped names do not use a namespace (e.g., temporary
> values created during input file parsing), in which case the namespace name can
> be empty. The namespace name will never start or end with "::".
> ```

BTW I gather it is permissible for namespace segments and element names to contain a single ":"? That seems unfortunate if so but if it has to be that way I think it is worth mentioning explicitly here. 

I suppose the horse is already out of the barn, but a single identifier-forbidden delimiter could be nicer. Did you consider "robot1/torso" or "robot1.torso"? (I don't know if those are really forbidden in sdf identifiers though.)
___
*[`multibody/tree/scoped_name.h` line 47 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTQZf9A5_Gupb9m0oE:-NPTQZf9A5_Gupb9m0oF:bfc5nuy) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L47)):*
> ```objc
>   @throws std::exception if `element_name` contains "::" or is empty.
>   @see ScopedName::Make() to use a null return value instead of exceptions.
>   @see ScopedName::Join() for automatic coalescing of "::" tokens. */
> ```

BTW "coalescing" doesn't quite capture what Join is doing. Maybe "cleanup"?
___
*[`multibody/tree/scoped_name.h` line 61 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTgoCS2KbOZL9BvGxj:-NPTgoCS2KbOZL9BvGxk:b5pgmn8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L61)):*
> ```objc
>   or trailing "::" on the names are removed before joining. After joining, the
>   final word after all "::"s is the element name, and everything prior is the
>   namespace name. */
> ```

BTW I saw at least one use case in parsing where Join is used to build up a multi-segment namespace (that is, both name1 and name2 are namespaces). Consider mentioning here that that is an acceptable use case, where the last segment will be treated here as though it is an element name but might turn out later to be a namespace segment.
___
*[`multibody/tree/scoped_name.h` line 65 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPT_1j47ZAA6j2zKz93:-NPT_1j47ZAA6j2zKz94:bh1was6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L65)):*
> ```objc
> 
>   /** Parses the given `scoped_name` string. Any leading or trailing "::" on the
>   name are removed. */
> ```

nit: are -> is

Also de-dups extra "::::" delims like Join; should say so.
___
*[`multibody/tree/scoped_name.h` line 69 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPT_CCF7vEqXaginU-o:-NPT_CCF7vEqXaginU-p:b50cd7m) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L69)):*
> ```objc
> 
>   /** Returns the namespace portion of this scoped name, e.g., "robot1". This is
>   typically the model instance name. It is typically not empty. */
> ```

BTW not sure what to do with "It is typically not empty". Maybe "This is typically the model instance name but can be empty (see class documentation)."
___
*[`multibody/tree/scoped_name.h` line 79 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTa4FiCvgZR3D0Pq0l:-NPTa4FiCvgZR3D0Pq0m:b-qggceg) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L79)):*
> ```objc
>   /** Returns the full %ScopedName as a string, e.g., "robot1::torso". It is
>   never empty unless this %ScopedName was default-constructed or moved-from. */
>   std::string_view get_full() const;
> ```

BTW consider dropping `get_` from these accessor-like functions.
___
*[`multibody/tree/scoped_name.h` line 92 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTaclH1i8O6OHDaiDr:-NPTaclH1i8O6OHDaiDs:b-u4947x) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L92)):*
> ```objc
>   unchanged.
>   @throws std::exception if `element_name` contains "::" or is empty. */
>   void set_element(std::string_view element_name);
> ```

BTW ignorable thought - an alternative would be to have these do a Join-like cleanup of any ignorable "::"s so they wouldn't throw and the caller wouldn't be obligated to do their own cleanup before calling. (I'm saying that in ignorance of the intended use cases so might well be better as you have them.)
___
*[`multibody/tree/scoped_name.cc` line 36 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTbsoC3X-uaTTZa5f2:-NPTbsoC3X-uaTTZa5f3:b60to16) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.cc#L36)):*
> ```cpp
> 
> namespace {
> // TODO(jwnimmer-tri) Use the C++ built-in starts_with when we drop C++17.
> ```

BTW and `ends_with`

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks for the careful review!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-:-NPU7fWL2fBJRLnG8cj1:b-6v7toj)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

___
*[`multibody/parsing/detail_dmd_parser.cc` line 121 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPThLBY1U1hdGhnUgA4:-NPU7eYa0Y2c0lhNfcS3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/parsing/detail_dmd_parser.cc#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW see my comment on Join() -- I was surprised by this use case where the "element" field is temporarily used as a namespace segment. No complaint about the use, should just be acknowledged as an acceptable use of Join().
</blockquote></details>

Done.
___
*[`multibody/tree/body.h` line 194 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTjHbyDcdx9BDcKG_U:-NPU2nrJAtGX9sHoic4l:bceeadu) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/body.h#L194)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can this be the World Body and if so is there still a non-empty namespace name for it?
</blockquote></details>

Yes, and yes.

Do you think that's worth somehow noting in the comment?  I'm not sure what I would say.
___
*[`multibody/tree/scoped_name.h` line 24 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTOwASBTXlUOL8VT0Q:-NPU5X46EqRpB2BjgVJ_:bvn7lar) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L24)):*
> I gather it is permissible for namespace segments and element names to contain a single ":"? That seems unfortunate if so but if it has to be that way I think it is worth mentioning explicitly here.

Done.  (See a few lines later down in the overview.)

> I suppose the horse is already out of the barn, but a single identifier-forbidden delimiter could be nicer. Did you consider "robot1/torso" or "robot1.torso"? (I don't know if those are really forbidden in sdf identifiers though.)

This PR is refactoring a bunch of scattered and under-documented uses of `::` into a consistent and well-documented class.  Later on we could change the delimiter, if we decided to take on that challenge.  But not here.
___
*[`multibody/tree/scoped_name.h` line 61 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTgoCS2KbOZL9BvGxj:-NPU6aM73DcPoDs_0yIv:bkmecza) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I saw at least one use case in parsing where Join is used to build up a multi-segment namespace (that is, both name1 and name2 are namespaces). Consider mentioning here that that is an acceptable use case, where the last segment will be treated here as though it is an element name but might turn out later to be a namespace segment.
</blockquote></details>

That code is ... let's say "special and unique in a way that no Drake user should try to replicate".

I'm choosing to not advertise it here.
___
*[`multibody/tree/scoped_name.h` line 65 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPT_1j47ZAA6j2zKz93:-NPU4LlF60Z8BxQWepmX:b3jia1b) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L65)):*
> Also de-dups extra "::::" delims like Join; should say so.

Yes.  That's why the verb was plural =P.

In any case, I added more clarity.
___
*[`multibody/tree/scoped_name.h` line 79 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTa4FiCvgZR3D0Pq0l:-NPU5OcB4ZzIU2d9b_ix:b-3s72e4) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L79)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider dropping `get_` from these accessor-like functions.
</blockquote></details>

The word `namespace` is not a valid function name.
___
*[`multibody/tree/scoped_name.h` line 92 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTaclH1i8O6OHDaiDr:-NPU4gU27MKFBMEkjF4H:b42bsrn) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW ignorable thought - an alternative would be to have these do a Join-like cleanup of any ignorable "::"s so they wouldn't throw and the caller wouldn't be obligated to do their own cleanup before calling. (I'm saying that in ignorance of the intended use cases so might well be better as you have them.)
</blockquote></details>

My posture is that every use of auto-cleanup is an admission of defeat.  Parsers are supposed to be written carefully, not just making guesses.  I would have preferred not to even write "Join", but that was a bridge too far for this PR; we needed it to make a suitable graceful transition to sanity.
___
*[`multibody/tree/scoped_name.cc` line 36 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTbsoC3X-uaTTZa5f2:-NPU55J73ttc0fu5qCB6:bvjy8of) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.cc#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW and `ends_with`
</blockquote></details>

That's right.  I think it's sufficiently obvious to not spell it out.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: 1 unresolved discussion (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17482)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/tree/body.h` line 194 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTjHbyDcdx9BDcKG_U:-NPUPwV34XwzVEjgmdFx:bcgcovs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/body.h#L194)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, and yes.

Do you think that's worth somehow noting in the comment?  I'm not sure what I would say.
</blockquote></details>

Nope, just wanted to check. Nothing to say here.
___
*[`multibody/tree/scoped_name.h` line 79 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/17482#-NPTa4FiCvgZR3D0Pq0l:-NPUPM8R9V2-KfTv89Re:b2ni98j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad69a902ee71bbd624ac07d9d9debdcbab11ae8b/multibody/tree/scoped_name.h#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The word `namespace` is not a valid function name.
</blockquote></details>

oh!

**Comment by jwnimmer-tri** [comment]
Oops!  I totally forgot to add Python bindings for the new feature.  I'll do that today.

**Pull request merged**
