### PR TITLE
MathematicalProgram ignores the constraint if it were empty.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in https://github.com/RobotLocomotion/drake/pull/16761#pullrequestreview-911095580

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MyYQEc80dBID3PNFREs:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 906 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16825#-Myboq8BDzFGrmkXYEgV:-Myboq8BDzFGrmkXYEgW:bns98oa) ([raw file](https://github.com/robotlocomotion/drake/blob/acb0e33293114f3c2ac6570adabe3ee65d98e375/solvers/mathematical_program.cc#L906)):*
> ```cpp
> 
> Binding<LorentzConeConstraint> MathematicalProgram::AddConstraint(
>     const Binding<LorentzConeConstraint>& binding) {
> ```

This is a public function, but omitted the check.  I guess the `LorentzConeConstraint` constructor cannot create zero-sized constraints, but I still worry about us being able to remember to add `num_constraints` checks as we modify the code.

What do you think of https://github.com/hongkai-dai/drake/pull/25 as the approach instead?  (Re-using CheckBinding to also check the number of outputs.)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 906 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16825#-Myboq8BDzFGrmkXYEgV:-MyhJ_nQ2Scp3zx4cNwG:b-c267eq) ([raw file](https://github.com/robotlocomotion/drake/blob/acb0e33293114f3c2ac6570adabe3ee65d98e375/solvers/mathematical_program.cc#L906)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is a public function, but omitted the check.  I guess the `LorentzConeConstraint` constructor cannot create zero-sized constraints, but I still worry about us being able to remember to add `num_constraints` checks as we modify the code.

What do you think of https://github.com/hongkai-dai/drake/pull/25 as the approach instead?  (Re-using CheckBinding to also check the number of outputs.)
</blockquote></details>

I think that PR can work.

BTW, for Cost class, its num_output is fixed to 1 at the construction https://github.com/RobotLocomotion/drake/blob/3d86fa4e13481ee890f0d58ddb511bb74820c7a6/solvers/cost.h#L34. So I think we don't have to check the number of outputs (but the check doesn't hurt either).

**Review by jwnimmer-tri — COMMENTED** [review]
This is ready for a rebase/squash now.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MyhrQprEgUSYF6zgOTs:b3wklsq)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 906 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16825#-Myboq8BDzFGrmkXYEgV:-MyhrXrs0egheTfsX8Qu:b-dxbntz) ([raw file](https://github.com/robotlocomotion/drake/blob/acb0e33293114f3c2ac6570adabe3ee65d98e375/solvers/mathematical_program.cc#L906)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think that PR can work.

BTW, for Cost class, its num_output is fixed to 1 at the construction https://github.com/RobotLocomotion/drake/blob/3d86fa4e13481ee890f0d58ddb511bb74820c7a6/solvers/cost.h#L34. So I think we don't have to check the number of outputs (but the check doesn't hurt either).
</blockquote></details>

Right.  That's why my PR did `DRAKE_DEMAND` for the costs -- to encode that assumption into an assertion.

I suppose that here we should do `DRAKE_DEMAND(CheckBinding(...))` for the lorentz constraints as well, since we'll never be able to reach the "return binding" failsafe in any unit test.

**Review by hongkai-dai — COMMENTED** [review]
Just re-based the PR. I will do a squash before the merge.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MyiBnjY1uwrUdVuHCx9:b-4xin7n)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 906 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16825#-Myboq8BDzFGrmkXYEgV:-MyiCkh58ako3KBIgmFI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/acb0e33293114f3c2ac6570adabe3ee65d98e375/solvers/mathematical_program.cc#L906)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right.  That's why my PR did `DRAKE_DEMAND` for the costs -- to encode that assumption into an assertion.

I suppose that here we should do `DRAKE_DEMAND(CheckBinding(...))` for the lorentz constraints as well, since we'll never be able to reach the "return binding" failsafe in any unit test.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 4 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MyiH00fEsY8HZAG57fV:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.cc, line 1027 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MyiIi2d4MYXkkc-IQC0:-MyiIi2d4MYXkkc-IQC1:b-bhzqtq) ([raw file](https://github.com/robotlocomotion/drake/blob/d45f76bf332490dd12484bef6587144a41c62223/solvers/mathematical_program.cc#L1027)):*
> ```cpp
>     const Binding<PositiveSemidefiniteConstraint>& binding) {
>   if (!CheckBinding(binding)) {
>     return binding;
> ```

nit kcov is showing this line as untested in `mathematical_program_test`.  Is it tested anywhere else?
___
*[solvers/mathematical_program.cc, line 1236 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MyiIlRy3dhz-zlSrYnV:-MyiIlRy3dhz-zlSrYnW:b-bhzqtq) ([raw file](https://github.com/robotlocomotion/drake/blob/d45f76bf332490dd12484bef6587144a41c62223/solvers/mathematical_program.cc#L1236)):*
> ```cpp
>     const Binding<ExponentialConeConstraint>& binding) {
>   if (!CheckBinding(binding)) {
>     return binding;
> ```

nit kcov is showing this line as untested in `mathematical_program_test`.  Is it tested anywhere else?

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MyiqFQW-XltMkU0pHhi:b8asji7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[solvers/mathematical_program.cc, line 1027 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MyiIi2d4MYXkkc-IQC0:-MyiptY08wai0K3aWXMo:buezrfq) ([raw file](https://github.com/robotlocomotion/drake/blob/d45f76bf332490dd12484bef6587144a41c62223/solvers/mathematical_program.cc#L1027)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit kcov is showing this line as untested in `mathematical_program_test`.  Is it tested anywhere else?
</blockquote></details>

Good call, I added the test.
___
*[solvers/mathematical_program.cc, line 1236 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MyiIlRy3dhz-zlSrYnV:-MyipwcuCiRodkwGgMAQ:b-3f1qbo) ([raw file](https://github.com/robotlocomotion/drake/blob/d45f76bf332490dd12484bef6587144a41c62223/solvers/mathematical_program.cc#L1236)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit kcov is showing this line as untested in `mathematical_program_test`.  Is it tested anywhere else?
</blockquote></details>

It is impossible to create an ExponentialConeConstraint with no output (by construction it must have 2 constraints, so I change it to DRAKE_DEMAND(CheckBinding(binding))

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
FYI There is a debug-mode assertion with Eigen size mismatch in CI.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825#-:-MymFWf-EqpNlr3dTLBr:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[solvers/test/mathematical_program_test.cc, line 989 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MymFFVXD4mVbZXU6DA8:-MymFFVXD4mVbZXU6DA9:bg1lmy6) ([raw file](https://github.com/robotlocomotion/drake/blob/9236f5a0fd6b938a2269eba103b1a4bebe265462/solvers/test/mathematical_program_test.cc#L989)):*
> ```cpp
>   auto binding6 = prog.AddConstraint(internal::CreateBinding(
>       std::make_shared<PositiveSemidefiniteConstraint>(0),
>       MatrixXDecisionVariable(0, 0)));
> ```

This patch "fixed" it. You tell me it if looks legit:

```
diff --git a/solvers/test/mathematical_program_test.cc b/solvers/test/mathematical_program_test.cc
index 6a27d0c3e6..4b56aab2fd 100644
--- a/solvers/test/mathematical_program_test.cc
+++ b/solvers/test/mathematical_program_test.cc
@@ -986,7 +986,7 @@ GTEST_TEST(TestMathematicalProgram, AddEmptyConstraint) {
 
   auto binding6 = prog.AddConstraint(internal::CreateBinding(
       std::make_shared<PositiveSemidefiniteConstraint>(0),
-      MatrixXDecisionVariable(0, 0)));
+      MatrixXDecisionVariable(0, 1)));
   EXPECT_TRUE(prog.GetAllConstraints().empty());
 
   auto binding7 =
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[solvers/test/mathematical_program_test.cc, line 989 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MymFFVXD4mVbZXU6DA8:-Mynt9In4H1cY16SjZda:b-582oic) ([raw file](https://github.com/robotlocomotion/drake/blob/9236f5a0fd6b938a2269eba103b1a4bebe265462/solvers/test/mathematical_program_test.cc#L989)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This patch "fixed" it. You tell me it if looks legit:

```
diff --git a/solvers/test/mathematical_program_test.cc b/solvers/test/mathematical_program_test.cc
index 6a27d0c3e6..4b56aab2fd 100644
--- a/solvers/test/mathematical_program_test.cc
+++ b/solvers/test/mathematical_program_test.cc
@@ -986,7 +986,7 @@ GTEST_TEST(TestMathematicalProgram, AddEmptyConstraint) {
 
   auto binding6 = prog.AddConstraint(internal::CreateBinding(
       std::make_shared<PositiveSemidefiniteConstraint>(0),
-      MatrixXDecisionVariable(0, 0)));
+      MatrixXDecisionVariable(0, 1)));
   EXPECT_TRUE(prog.GetAllConstraints().empty());
 
   auto binding7 =
```
</blockquote></details>

That looks correct to me.  If you'd like to push a fix (or edit the file online), then I think we can merge this.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[solvers/test/mathematical_program_test.cc, line 989 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MymFFVXD4mVbZXU6DA8:-Myo7yvP3QToABwTG2A6:b-gzsh7h) ([raw file](https://github.com/robotlocomotion/drake/blob/9236f5a0fd6b938a2269eba103b1a4bebe265462/solvers/test/mathematical_program_test.cc#L989)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That looks correct to me.  If you'd like to push a fix (or edit the file online), then I think we can merge this.
</blockquote></details>

Thanks Rico for the patch!

I think it is a bit strange to pass in a matrix of size (0, 1). Supposedly the matrix should be a square matrix. I will see if I can fix the problem without changing the matrix size.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16825)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[solvers/test/mathematical_program_test.cc, line 989 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16825#-MymFFVXD4mVbZXU6DA8:-MyoYU1fAvgkmzLZJda0:b-o56r9c) ([raw file](https://github.com/robotlocomotion/drake/blob/9236f5a0fd6b938a2269eba103b1a4bebe265462/solvers/test/mathematical_program_test.cc#L989)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks Rico for the patch!

I think it is a bit strange to pass in a matrix of size (0, 1). Supposedly the matrix should be a square matrix. I will see if I can fix the problem without changing the matrix size.
</blockquote></details>

I take it back. Rico's patch is correct, the binding's variable is always a column vector, not a matrix.

**Pull request merged**
