### PR TITLE
Removed LcmSubscriberSystem::SetMessage() methods.

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #3779.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3807)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@ggould-tri for platform review please.

Thanks.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-:-KU3Shk2xRku1AuIvN7u:bu7u2dk)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UG749UsYvV0zzSiQ:-KU3UG749UsYvV0zzSiR:boofvf7) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/automotive/test/automotive_simulator_test.cc#L68)):*
> ```cpp
>                                      message_bytes.size());
> 
>   // Confirm that the RigidBodyTree has been appropriately amended.
> ```

BTW Would the test be clearer if the order instead were?:
- Start
- Confirm RBT (vv | swapped vs what's there now)
- Set full throttle (^^ | swapped vs what's there now)
- StepBy / not moved much

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-:-KU3USI516Ct9pmiOkqH:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3TvfeJxiNXOOOd6L3:-KU3TvfeJxiNXOOOd6L4:b-f6tj53) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/lcm_subscriber_system.h#L72)):*
> ```objc
> 
>   /**
>    * Returns the subscriber used by this publisher.
> ```

This says it returns a subscriber but returns a translator, which is not obviously a kind of subscriber.

More generally, you have removed detailed docstrings that clearly described use cases and left behind a one-liner that leaves very little idea of how one uses this method.  I would prefer a docstring of similar clarity to the ones removed.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UOt_yxvEWB7LlLn4:-KU3UOt_yxvEWB7LlLn5:bs2lxa3) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L192)):*
> ```cpp
>   }
> 
>   // Induce a message message transmission so we can evaluate wither the LCM
> ```

FYI typo "message message"; typo "wither"

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UWgeZ1--VdNW4YBQ:-KU3UWgeZ1--VdNW4YBR:b3dkyfq) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L195)):*
> ```cpp
>   // subscriber was able to successfully decode the message.
>   // const double time = 0;
>   // dut.SetMessage(time, sample_vector);
> ```

FYI Commented out code here; remove or TODO this please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UG749UsYvV0zzSiQ:-KU3pQ3y8F9G5OAf_vRb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/automotive/test/automotive_simulator_test.cc#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Would the test be clearer if the order instead were?:
> - Start
> - Confirm RBT (vv | swapped vs what's there now)
> - Set full throttle (^^ | swapped vs what's there now)
> - StepBy / not moved much
</details>
Done.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3TvfeJxiNXOOOd6L3:-KU3pd_I7LHzszT0GEft:b-ddm2j1) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/lcm_subscriber_system.h#L72)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> This says it returns a subscriber but returns a translator, which is not obviously a kind of subscriber.
> 
> More generally, you have removed detailed docstrings that clearly described use cases and left behind a one-liner that leaves very little idea of how one uses this method.  I would prefer a docstring of similar clarity to the ones removed.
</details>
Done.

I added some sentences describing how this method is typically used. I also added a similar description to LcmPublisherSystem.h.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UOt_yxvEWB7LlLn4:-KU3p3iCuRovSkf2ZI4o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L192)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI typo "message message"; typo "wither"
</details>
Done.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-KU3UWgeZ1--VdNW4YBQ:-KU3p4dfwsKxn38Ls9MW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9219db522a28220d3321c286ed9ee194804c5e7f/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L195)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI Commented out code here; remove or TODO this please.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-:-KU3rC9g_sDjQElTkU1K:bblnx7i)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-:-KU3sn5B6_ccJkNo_Bk9:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Just waiting on CI now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3807#-:-KU3zsIsWd7nGpvyfghW:b9otovs)*

**Pull request merged**
