### PR TITLE
Change Diagram API for GetSubsystemStuff.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Change the GetSubsystemStuff family of methods to comply with style guide....

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6466)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by siyuanfeng-tri** [comment]
+@sherm1 +@seancurtis-tri for reviews thanks!

---

Review status: 0 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6466#-:-Knm7cnOulYG_zFnijSA:b-y3x3tg)*

**Comment by sherm1** [comment]
Platform :lgtm:. That was a lot of work! Thanks very much, @siyuanfeng-tri.

---

Reviewed 41 of 43 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6466#-:-KnmDyY7ZugvNvuirzH_:b-7wv4tu)*

**Comment by SeanCurtis-TRI** [comment]
Feature :LGTM: That was just a tedious piece of work for all. Thanks for slogging through it.

---

Reviewed 41 of 43 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 493 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6466#-Kno7wYecj23QqqImZ_g:-Kno7wYecj23QqqImZ_h:b-4hx43s) ([raw file](https://github.com/robotlocomotion/drake/blob/d07f74822cc7e9618ff9bf26dce36ebbc5f193e0/drake/systems/framework/diagram.h#L493)):*
> ```objc
>   const Context<T>& GetSubsystemContext(const System<T>& subsystem,
>                                         const Context<T>& context) const {
>     auto ret = DoGetTargetSystemContext(subsystem, &context);
> ```

BTW Given *this* PR, it's probably worth raising an issue for methods like `DoGetTargetSystemContext` which takes a const pointer as well.  I'd definitely say *outside* the scope of this PR. But since it's staring me in the eye, and we've deemed this work worth doing, it's probably worth capturing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6466#-:-KnoBoqUzsuoBndrHUg4:bqzihrj)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 493 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6466#-Kno7wYecj23QqqImZ_g:-KnoEGjlCYISUDhqI1D5:b3cdlra) ([raw file](https://github.com/robotlocomotion/drake/blob/d07f74822cc7e9618ff9bf26dce36ebbc5f193e0/drake/systems/framework/diagram.h#L493)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given *this* PR, it's probably worth raising an issue for methods like `DoGetTargetSystemContext` which takes a const pointer as well.  I'd definitely say *outside* the scope of this PR. But since it's staring me in the eye, and we've deemed this work worth doing, it's probably worth capturing.
</blockquote></details>

The DoGetTargetSystemContext thing taking a const pointer instead of & make my life easier doing to the crazy template stuff, because the counterpart is Context<T>* DoGetMutableTargetSystemContext(const System<T>&, Context<T>*). If someone wants to throw more template stuff at it, we can make it work. But my argument is the DoGetTarget... is supposedly "protected", so I would let it slip this time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6466)*

**Pull request merged**
