### PR TITLE
Fix index query bug in PairwiseIntersectionsContinuousJoints

### PR DESCRIPTION
**Pull request by sadraddini**
Avoid calling indices that may not exist that led to default zeros (and absence of proper wrapping) when `continuous_revolute_joints` did not start with 0 (or had gaps between the smallest and largest index).  

Added a unit test that would not pass otherwise.

@cohnt for feature review

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857)

### CODE REVIEW

**Review by cohnt — COMMENTED** [review]
Good catch! :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-:-NpWM6rJ2TWF6le8soO3:bhfe2ig)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @sadraddini)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-:-NpW_ZiT6yNoZK6-stcq:bfvx2sg)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-NpX5FbVBH54I9k2n-wA:-NpXOLOC6R5mRhwDIbYk:b-cyc42h) ([raw file](https://github.com/RobotLocomotion/drake/blob/6bc73848342d18882f5a8fca23754fa1b2220f66/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L118)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just wanted to verify that you are intentionally adding a runtime cost now to check the index validity. (`at(i)` is more expensive than `[i]` in release builds, but won't index bad memory). No objection from me, you are the judge of the tradeoff in this context!
</blockquote></details>

We were bitten by not using `.at(i)` and not capturing faulty `[i]` queries in the unit tests. 

That being said, this particular for loop looks safe with `[i]` as` i =0, ..., size(convex_sets)-1` so I reverted these two changes, but kept `at(i)` elsewhere so a bad memory bug would be immediately detected in the tests. I don't know what the standard C++ practice is. Should we revert them to `[i]` once the developer is confident that the code is sound?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-NpX5FbVBH54I9k2n-wA:-Np_d7kr0S9NpXSuE_GM:b-do8f7i) ([raw file](https://github.com/RobotLocomotion/drake/blob/6bc73848342d18882f5a8fca23754fa1b2220f66/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L118)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

We were bitten by not using `.at(i)` and not capturing faulty `[i]` queries in the unit tests. 

That being said, this particular for loop looks safe with `[i]` as` i =0, ..., size(convex_sets)-1` so I reverted these two changes, but kept `at(i)` elsewhere so a bad memory bug would be immediately detected in the tests. I don't know what the standard C++ practice is. Should we revert them to `[i]` once the developer is confident that the code is sound?
</blockquote></details>

I can't answer that in general. Using `at(i)` is like adding DRAKE_DEMANDs -- makes it easier to debug programming errors in released code by catching problems early rather than letting them cascade into a mysterious downstream seg fault. Fine to leave them in when the cost doesn't matter. But when is that? It depends on the context. I wouldn't leave at() or DRAKE_DEMANDs in a known-critical inner loop; I'd use DRAKE_ASSERT there since it is only present in Debug builds.

The resulting program death from at() or DRAKE_DEMAND failures is unlikely to be helpful to end users. These should only be used to catch programming errors by _us_. For user errors we have to generate more helpful, user-relevant, error messages.

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-NpX5FbVBH54I9k2n-wA:-Np_zOwn59aRr_i_wWFL:b-8ppykr) ([raw file](https://github.com/RobotLocomotion/drake/blob/6bc73848342d18882f5a8fca23754fa1b2220f66/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L118)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I can't answer that in general. Using `at(i)` is like adding DRAKE_DEMANDs -- makes it easier to debug programming errors in released code by catching problems early rather than letting them cascade into a mysterious downstream seg fault. Fine to leave them in when the cost doesn't matter. But when is that? It depends on the context. I wouldn't leave at() or DRAKE_DEMANDs in a known-critical inner loop; I'd use DRAKE_ASSERT there since it is only present in Debug builds.

The resulting program death from at() or DRAKE_DEMAND failures is unlikely to be helpful to end users. These should only be used to catch programming errors by _us_. For user errors we have to generate more helpful, user-relevant, error messages.
</blockquote></details>

I see. I don't think this code is super-critical at run-time as it is mostly a pre-processing step. So I would like to merge it as it is, especially as it fixes a current bug. @cohnt any thoughts?

**Review by cohnt — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20857)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20857#-NpX5FbVBH54I9k2n-wA:-Npa1f724vWfXT9yXgsO:bvv8ycl) ([raw file](https://github.com/RobotLocomotion/drake/blob/6bc73848342d18882f5a8fca23754fa1b2220f66/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L118)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

I see. I don't think this code is super-critical at run-time as it is mostly a pre-processing step. So I would like to merge it as it is, especially as it fixes a current bug. @cohnt any thoughts?
</blockquote></details>

I concur with Sadra -- let's merge as-is. `at(i)` vs `[i]` will not have a significant effect on the runtime in this instance, since solving the intersection programs (and the later online GCS problems) take many orders of magnitude longer.

**Pull request merged**
