### PR TITLE
Purge IdmWithTrajectoryAgent (replaced with diagram in #4081)

### PR DESCRIPTION
**Pull request by jadecastro**
Port numeric Parameters introduced in #3991 to IdmPlanner.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4172)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@ggould-tri for platform review.
+@david-german-tri for feature review.

**Comment by david-german-tri** [comment]
:lgtm: nice!

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-:-KWtQJfhemjRXqqY3z-w:b-7yytuz)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri -@ggould-tri platform :lgtm:.

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/idm_planner.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-KWu7SL-e-vVCVrhFj31:-KWu7SL0lEGAnDv6GRxW:b6knlg2) ([raw file](https://github.com/robotlocomotion/drake/blob/25cf801af49e6cf72d9aad02043124ac96c91189/drake/automotive/idm_planner.h#L33)):*
> ```objc
>  public:
>   /// @p v_ref desired velocity of the ego car in units of m/s.
>   explicit IdmPlanner(const T& v_ref);
> ```

BTW I think in a future PR this should disappear from the ctor, so that it's only set (by users) via the context parameters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-:-KWu6KkkozW91RJ9k_jZ:b-lviclp)*

**Comment by jadecastro** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/idm_planner.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-KWu7SL-e-vVCVrhFj31:-KWuJcjanoYdKlxeeCEI:b9pf404) ([raw file](https://github.com/robotlocomotion/drake/blob/25cf801af49e6cf72d9aad02043124ac96c91189/drake/automotive/idm_planner.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I think in a future PR this should disappear from the ctor, so that it's only set (by users) via the context parameters?
</details>
Yeah, I wasn't too sure what to do with it. It seemed to me less like a user-defined parameter and more of a parameter that's a function of either the road or a high-level decision on whether to move or to stop. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4172)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/idm_planner.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-KWu7SL-e-vVCVrhFj31:-KWuOcNDFlOvK_0LG5Ce:b-xbx0h9) ([raw file](https://github.com/robotlocomotion/drake/blob/25cf801af49e6cf72d9aad02043124ac96c91189/drake/automotive/idm_planner.h#L33)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary>
> Yeah, I wasn't too sure what to do with it. It seemed to me less like a user-defined parameter and more of a parameter that's a function of either the road or a high-level decision on whether to move or to stop. 
</details>
Right.  But there's a general problem with having `T` as a member field -- in that setting up the appropriate value for non-`double` types of `T` might become difficult (e.g., how many partials in an autodiff) -- versus exposing the values through structured interfaces like the `Parameters` only.

Marking resolved since this is a fine step, but FYI for future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4172)*

**Comment by jadecastro** [comment]
Review status: 22 of 23 files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/idm_planner.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4172#-KWu7SL-e-vVCVrhFj31:-KWuPz-6v0r9nm2RbwfR:b-8g7b0v) ([raw file](https://github.com/robotlocomotion/drake/blob/25cf801af49e6cf72d9aad02043124ac96c91189/drake/automotive/idm_planner.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Right.  But there's a general problem with having `T` as a member field -- in that setting up the appropriate value for non-`double` types of `T` might become difficult (e.g., how many partials in an autodiff) -- versus exposing the values through structured interfaces like the `Parameters` only.
> 
> Marking resolved since this is a fine step, but FYI for future.
</details>
Ah, I see. I've added a TODO, and will revisit later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4172)*

**Pull request merged**
