### PR TITLE
Store FEM tangent matrix in block sparse matrix

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

This PR is a follow-up to #19545. It addresses 3 related topics on FEM tangent matrices: allocation, assembly, and applying BCs. Each closely resembles their PETSc counterparts (which is the current data structure we use to hold FEM tangent matrices). The plan is to retire PETSc once the transition to the new data structure is done.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-:-NXN179Z39ddMWotbqEB:bgst6yh)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
Altogether :lgtm:. I had a few thoughts and clarifications below, but nothing difficult. +@EricCousineau-TRI for platform review, please.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-:-NXzIJ84AiUO41zSCN10:bbkbefs)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/fem/fem_model.h` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz4qpu0Hzu051AECQH:-NXz4qpu0Hzu051AECQI:bmkjet8) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model.h#L186)):*
> ```objc
>    which is set to a scalar multiple of identity.
>    @param[in] fem_state        The FemState used to evaluate the tangent matrix.
>    @param[in] weights          The weights used to combine stiffness, damping,
> ```

nit: Any pre-condition on weights? Even if they're validated somewhere down the line it would be nice to fail fast here.
___
*[`multibody/fem/fem_model_impl.h` line 215 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz95d7A--OF6wTe2pS:-NXz95d7A--OF6wTe2pT:b-kxsxrc) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L215)):*
> ```objc
>         for (int a = 0; a < Element::num_nodes; ++a) {
>           for (int b = 0; b <= a; ++b) {
>             const int i = element_node_indices[a];
> ```

nit: you can move this out of the inner loop.



_Code quote:_
```objc
            const int i = element_node_indices[a];
```
___
*[`multibody/fem/fem_model_impl.h` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzE9Am-WGvhMCFPlpD:-NXzE9Am-WGvhMCFPlpE:b-g2773b) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L257)):*
> ```objc
>             const int i =
>                 std::max(element_node_indices[a], element_node_indices[b]);
>             neighbor_nodes[j].insert(i);
> ```

nit: I'm missing the context for why these indices are inserted into sets first and then into their eventual vector form.You're already sorting and removing duplicates in `BlockSparsityPattern`, why do extra work here?



_Code quote:_
```objc
            neighbor_nodes[j].insert(i);
```
___
*[`multibody/fem/test/fem_model_test.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzHLaW6Ne0a-2CACE0:-NXzHLaW6Ne0a-2CACE1:b-7r5ll2) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/fem_model_test.cc#L53)):*
> ```cpp
> }
> 
> GTEST_TEST(FemModelTest, CalcTangentMatrix) {
> ```

nit: Missing coverage for the exception thrown for `T != double`. Do we have a policy on how strict we are for testing unsupported numeric types?
___
*[`multibody/fem/test/fem_model_test.cc` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz3i4hEwAJbQXh3UKG:-NXz3i4hEwAJbQXh3UKH:bi5ohug) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/fem_model_test.cc#L93)):*
> ```cpp
>       std::numeric_limits<double>::epsilon(), MatrixCompareType::relative));
> 
>   /* Test the Block3x3SparseSymmetricMatrix variant of tangent matrix. */
> ```

nit: comment inconsistent with the petsc testing below it.



_Code quote:_
```cpp
  /* Test the Block3x3SparseSymmetricMatrix variant of tangent matrix. */
```

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks! Just some small nits / BTWs

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-:-NXzWlP-6i3d8Otud79F:brpkys6)* status: 7 unresolved discussions

___
*[`multibody/fem/BUILD.bazel` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzSYh_7orWIBMvfpgx:-NXzSYha1QwIc7FFUYZ-:b3qfkvp) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/BUILD.bazel#L162)):*
> ```Starlark
> 
> # Alias to avoid the "line too long" linter complaint.
> MATRIX_PATH = "//multibody/contact_solvers"
> ```

nit For consistency + readability, I believe this should use `#noqa` to squelch those errors, e.g.
https://github.com/RobotLocomotion/drake/blob/f429ca1c743e85f28f7456d67c0ed7f68c643031/examples/kuka_iiwa_arm/BUILD.bazel#L185
___
*[`multibody/fem/dirichlet_boundary_condition.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzTRWK157FWcbOhsGj:-NXzTRWK157FWcbOhsGk:bgvr307) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/dirichlet_boundary_condition.cc#L66)):*
> ```cpp
>    DoFs under the BC (except the diagonal blocks which is set to be diagonal).
>   */
>   std::vector<int> node_indices(index_to_boundary_state_.size());
> ```

BTW Is it OK to reallocate each time? Or should this be stored in scratch variable?
___
*[`multibody/fem/fem_model_impl.h` line 240 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzUXk04VqORTlHiyAM:-NXzUXk04VqORTlHiyAN:bgvr307) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L240)):*
> ```objc
>      constexpr` here is still needed to make the compiler happy. */
>     if constexpr (std::is_same_v<T, double>) {
>       std::vector<std::unordered_set<int>> neighbor_nodes(this->num_nodes());
> ```

BTW Is it OK to reallocate each time? Or should this be stored in scratch variable?
___
*[`multibody/fem/test/dirichlet_boundary_condition_test.cc` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzUg8e0F1HnAe2oXuh:-NXzUg8e0F1HnAe2oXui:b-7traq9) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/dirichlet_boundary_condition_test.cc#L26)):*
> ```cpp
> 
> // clang-format off
> const Matrix3d A00 = (Eigen::Matrix3d() <<  3,   1,    0.5,
> ```

nit Even though this is a test, this global has a non-trivial destructor

Should this be wrapped in a function, or be wrapped with `never_destroyed<>`?
___
*[`multibody/fem/test/fem_model_test.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzHLaW6Ne0a-2CACE0:-NXzV4npBXCPs_n_lQ-z:b-tg9juj) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/fem_model_test.cc#L53)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Missing coverage for the exception thrown for `T != double`. Do we have a policy on how strict we are for testing unsupported numeric types?
</blockquote></details>

Not that I'm aware of. However, if it doesn't take too much effort to make one such test point, I think it would be useful.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the reviews. Comments addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-:-NXztJ6_61laW2z_4dvA:b-4f09rl)* status: 2 unresolved discussions

___
*[`multibody/fem/BUILD.bazel` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzSYh_7orWIBMvfpgx:-NXznmVe0KyHa3_1U_7Z:b-r95bp6) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/BUILD.bazel#L162)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For consistency + readability, I believe this should use `#noqa` to squelch those errors, e.g.
https://github.com/RobotLocomotion/drake/blob/f429ca1c743e85f28f7456d67c0ed7f68c643031/examples/kuka_iiwa_arm/BUILD.bazel#L185
</blockquote></details>

Done. TIL, thanks!
___
*[`multibody/fem/dirichlet_boundary_condition.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzTRWK157FWcbOhsGj:-NXzpUxa9tcePMN47-7J:b-iry7x8) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/dirichlet_boundary_condition.cc#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Is it OK to reallocate each time? Or should this be stored in scratch variable?
</blockquote></details>

Done, thanks
___
*[`multibody/fem/fem_model.h` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz4qpu0Hzu051AECQH:-NXzqACiCBHlkuVr4nlI:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model.h#L186)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Any pre-condition on weights? Even if they're validated somewhere down the line it would be nice to fail fast here.
</blockquote></details>

Done, thanks.
___
*[`multibody/fem/fem_model_impl.h` line 215 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz95d7A--OF6wTe2pS:-NXzqEKN5a_24gjFtibl:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L215)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: you can move this out of the inner loop.
</blockquote></details>

Done
___
*[`multibody/fem/fem_model_impl.h` line 240 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzUXk04VqORTlHiyAM:-NXzqJrq79pEnnlPj0Nt:b8ycb6a) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L240)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Is it OK to reallocate each time? Or should this be stored in scratch variable?
</blockquote></details>

This is fine. The tangent matrix is only allocated once per sim.
___
*[`multibody/fem/fem_model_impl.h` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzE9Am-WGvhMCFPlpD:-NXzqjd9199aEyYDwlqD:bojwski) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L257)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I'm missing the context for why these indices are inserted into sets first and then into their eventual vector form.You're already sorting and removing duplicates in `BlockSparsityPattern`, why do extra work here?
</blockquote></details>

I'd imagine having duplicates in `neighbor_nodes[j]` is a bit counter-intuitive and confusing. The tangent matrices are allocated once per sim so the cost here should be negligible.
___
*[`multibody/fem/test/dirichlet_boundary_condition_test.cc` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzUg8e0F1HnAe2oXuh:-NXzszKd95YvR8XOQ5AI:bozjmsh) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/dirichlet_boundary_condition_test.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Even though this is a test, this global has a non-trivial destructor

Should this be wrapped in a function, or be wrapped with `never_destroyed<>`?
</blockquote></details>

I'm not sure why a fixed size matrix would have a non-trivial destructor. Do you have some evidence?
___
*[`multibody/fem/test/fem_model_test.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzHLaW6Ne0a-2CACE0:-NXzyKZe5b7fyh0lNkmu:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/fem_model_test.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not that I'm aware of. However, if it doesn't take too much effort to make one such test point, I think it would be useful.
</blockquote></details>

Done.
___
*[`multibody/fem/test/fem_model_test.cc` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXz3i4hEwAJbQXh3UKG:-NXztH0t7HaQIIim0e1c:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/fem_model_test.cc#L93)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: comment inconsistent with the petsc testing below it.
</blockquote></details>

Done, thanks.

**Review by joemasterjohn — COMMENTED** [review]
Looks good, thanks!

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-:-NY-GK3g2LN89hcMEKbk:br06oxi)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

___
*[`multibody/fem/fem_model_impl.h` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzE9Am-WGvhMCFPlpD:-NY-EODe-AwvDu8dJeW5:b-1pgsef) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L257)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'd imagine having duplicates in `neighbor_nodes[j]` is a bit counter-intuitive and confusing. The tangent matrices are allocated once per sim so the cost here should be negligible.
</blockquote></details>

Fair enough. Although `neighbor_nodes` only exists for this short time between constructing it and then passing it to the `BlockSparsityPattern`. Maybe consider making the sorted and unique property of the `neighbors` argument to `BlockSparsityPattern's constructor` a precondition instead of doing the actual work. Helps to streamline that class's responsibility and prevents duplicate work from being done.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559)* status: 1 unresolved discussion

___
*[`multibody/fem/fem_model_impl.h` line 257 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzE9Am-WGvhMCFPlpD:-NY-MiTs6dD7mY_JVtbU:b-cm7jpf) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/fem_model_impl.h#L257)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Fair enough. Although `neighbor_nodes` only exists for this short time between constructing it and then passing it to the `BlockSparsityPattern`. Maybe consider making the sorted and unique property of the `neighbors` argument to `BlockSparsityPattern's constructor` a precondition instead of doing the actual work. Helps to streamline that class's responsibility and prevents duplicate work from being done.
</blockquote></details>

The requirements used to be a unchecked precondition, but I got burned once by the precondition failing during development (when called from the SAP side of things as we use the data structure for both SAP and FEM) so I now choose to be more conservative in the constructor.

The freedom of not having to worry if things are sorted is also nice at certain SAP call sites.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19559)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

___
*[`multibody/fem/test/dirichlet_boundary_condition_test.cc` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19559#-NXzUg8e0F1HnAe2oXuh:-NY-oXQMBPSxfyUM3XfY:b9gp49y) ([raw file](https://github.com/RobotLocomotion/drake/blob/79bbaad0aed94846e571da97442ee332d209562d/multibody/fem/test/dirichlet_boundary_condition_test.cc#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure why a fixed size matrix would have a non-trivial destructor. Do you have some evidence?
</blockquote></details>

Ah, nuts, read it as `MatrixXd` for some reason - sorry about that!

**Pull request merged**
