### PR TITLE
Add of_dynamic

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5703)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , all reviews please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgmzSF2t7NsjMKfBuy9:b-tejcfb)*

**Comment by SeanCurtis-TRI** [comment]
BTW Given that the majority of the code is all about crafting an error message, it would be nice if the message is tested as well. (I can think of one way of testing it...)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-Kgo4b1q28qgHoDe9j4J:b-1y1joh)*

**Comment by jwnimmer-tri** [comment]
`NiceTypeName` makes every effort to be consistent across platforms, but its results are best-effort and not a guarantee.  So any test of the error message would have to be careful to fuzz out possible `NiceTypeName` burps.  From platform review perspective, I think having a a small (boring) implementation of the error message, combined with manual testing, should be good enough versus the difficulty of fuzzing.

:lgtm: platform & feature

This is interesting enough though, that we should seek a second reviewer so +(status: do not merge) label until a second reviewer is assigned (and then we can remove the label).

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo7lFwOcMP_BpddYFm:-Kgo7lFwOcMP_BpddYFn:b-o5grgc) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L23)):*
> ```objc
> /// EXPECT_TRUE(dynamic_cast<Camry>(ptr) != nullptr)
> ///
> /// // The following assertion fails *with* diagnostic info.
> ```

In this case, doesn't `of_dynamic` return `false, and so the `EXPECT_FALSE` passes (but the diagnostic is still emitted)?  I think "assertion fails" is not a great explanation for that effect.

---

*[drake/common/test/of_dynamic.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo813qCAf_3f3N1KG2:-Kgo813raRtv5v0ZPSEY:bhix3if) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L29)):*
> ```objc
> /// @endcode
> template <typename Derived, typename Base>
> bool of_dynamic(const Base* const ptr) {
> ```

Per Drake convention, don't put (the second) `const` on parameters, because its an implementation detail yet Doxygen snarfs it up into the API.

---

*[drake/common/test/of_dynamic.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo8FwX-LOq17MQjaZx:-Kgo8FwYKGCZQ_2ZWtnY:bfu1dzs) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L31)):*
> ```objc
> bool of_dynamic(const Base* const ptr) {
>   if (dynamic_cast<const Derived* const>(ptr) == nullptr) {
>     const std::string base_name{NiceTypeName::Demangle(typeid(Base).name())};
> ```

FYI I think `NiceTypeName` has `Get<Base>()` sugar when the type is known at compile time (for `Base` and `Derived`).

---

*[drake/common/test/of_dynamic_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo8vVtywAq5Ed8SnM0:-Kgo8vVtywAq5Ed8SnM1:b-amwqum) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic_test.cc#L19)):*
> ```cpp
> class Camry : public Car {
>  public:
>   virtual ~Camry() {}
> ```

_Meta_ `override` not `virtual`.

---

*[drake/common/test/of_dynamic_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo9EkMEiQ5eO0bD6WI:-Kgo9EkMEiQ5eO0bD6WJ:b-gs8c8o) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic_test.cc#L38)):*
> ```cpp
>   delete prius;
>   delete car;
> }
> ```

Please add cases for `of_dynamic<Car>(...)` for each of the three objects, for completeness / clarity.

Ditto for the `SharedPtr` test below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-Kgo9j46F2gVydF-eY1w:btzofuh)*

**Comment by soonho-tri** [comment]
Currently, it outputs a diagnostic message into `std::cerr` and it makes it difficult to write a test to capture and check the message.

An alternative is to change the return type of `of_dynamic` to `void` and make it throw a `std::runtime_error` when dynamic casting fails.

There are pros/cons of this approach:
pros: I can catch an exception and check its `.what()`.
cons1: Users need to write `EXPECT_NO_THROW()` or `EXPECT_THROW(..., std::runtime_error)`
cons2: Running a test doesn't print out a diagnostic message to the output stream when `of_dynamic` fails, which makes it useless. See

```
drake/common/test/of_dynamic_test.cc:30: Failure
Expected: of_dynamic<Camry>(car) doesn't throw an exception.
  Actual: it throws.
```

I'm wondering if there is another alternative which solves both of testability and usability issues.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-Kgo8B85DwTxPHUcgMvV:b-bvejn)*

**Comment by soonho-tri** [comment]
@seancurtis-tri , I just had f2f with Jeremy who taught me how to solve my problem.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgoEkUnmbSwUKTSOwRr:b-imwyjc)*

**Comment by soonho-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo7lFwOcMP_BpddYFm:-KgoI1vHWCsmIZILQL8x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In this case, doesn't `of_dynamic` return `false, and so the `EXPECT_FALSE` passes (but the diagnostic is still emitted)?  I think "assertion fails" is not a great explanation for that effect.
</blockquote></details>

Done.

---

*[drake/common/test/of_dynamic.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo813qCAf_3f3N1KG2:-KgoFpb3viCQSDrHYAkj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Per Drake convention, don't put (the second) `const` on parameters, because its an implementation detail yet Doxygen snarfs it up into the API.
</blockquote></details>

Done.

---

*[drake/common/test/of_dynamic.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo8FwX-LOq17MQjaZx:-KgoGW2oBYEGQxyDzdn2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think `NiceTypeName` has `Get<Base>()` sugar when the type is known at compile time (for `Base` and `Derived`).
</blockquote></details>

Done.

---

*[drake/common/test/of_dynamic_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo8vVtywAq5Ed8SnM0:-KgoG_WC3tbOhyKQHjik:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic_test.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ `override` not `virtual`.
</blockquote></details>

Done.

---

*[drake/common/test/of_dynamic_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgo9EkMEiQ5eO0bD6WI:-KgoI3HzqbXOb1W9G606:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b2fa2102fea753efccb59a259801c563ee858af/drake/common/test/of_dynamic_test.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add cases for `of_dynamic<Car>(...)` for each of the three objects, for completeness / clarity.

Ditto for the `SharedPtr` test below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by SeanCurtis-TRI** [comment]
Niiiiice.  `::testing::AssertionSuccess/Failure`  That gets filed away.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgoUFqimrsVEM2V8Yj6:b-gyl5t6)*

**Comment by soonho-tri** [comment]
+@seancurtis-tri , could you do feature review this PR? (I'd like to have an explicit LGTM).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgorwikEe-mKHKv39rG:bny5gw9)*

**Comment by SeanCurtis-TRI** [comment]
You've opened pandora's box.  Now i have to look at the code with a different mindset.  I've got a couple of cosmetic comments and a mildly bigger issue.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgosNsZZucZ4Pe4Jjpx:-KgosNs_j3iE87SHWUzJ:b-3u9l3r) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L9)):*
> ```objc
> 
> namespace drake {
> /// Checks if @ptr, a pointer to `Base` class, can be safely downcasted to a
> ```

1) I believe you meant `@p ptr` and not `@ptr`
2) BTW A minor grammar point. "downcasted" could/should be "downcast". (http://grammarist.com/usage/casted/) With the "should" depending on what side of the religious war a particular reader lives. I'll accept either.

---

*[drake/common/test/of_dynamic.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-KgouV_V77dFdj3xIGON:bc45pl) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L32)):*
> ```objc
> /// @endcode
> template <typename Derived, typename Base>
> ::testing::AssertionResult of_dynamic(const Base* ptr) {
> ```

BTW When I read the usage:

`EXPECT_TRUE(of_dynamic<Derived>(thing));`

doesn't parse very cleanly.

Why not something that reads more obviously:

`EXPECT_TRUE(can_downcast<Derived>(thing));`

---

*[drake/common/test/of_dynamic.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgotRCpf5QVaPRMms1Y:-KgotRCpf5QVaPRMms1Z:b-ihzz6d) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L45)):*
> ```objc
> }
> 
> /// Checks if @ptr, a shared pointer to `Base` class, can be safely downcasted
> ```

Same notes as above.

---

*[drake/common/test/of_dynamic.h, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgotVPT65JxuTw0yoy_:-KgotVPT65JxuTw0yoya:bj7zx8s) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L47)):*
> ```objc
> /// Checks if @ptr, a shared pointer to `Base` class, can be safely downcasted
> /// to a shared pointer to `Derived` class. Our motivation is to provide a good
> /// diagnostic for what @p ptr _actually_ was when a test fails.
> ```

typo: "...was when __*the*__ test fails."

---

*[drake/common/test/of_dynamic_test.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgotv_8hVXLX9EN_7G-:-Kgotv_8hVXLX9EN_7G0:b62si6d) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic_test.cc#L46)):*
> ```cpp
>   EXPECT_TRUE(of_dynamic<Camry>(camry));
> 
>   delete camry;
> ```

BTW This may be the first time I've seen "delete" in drake-related code.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgouhexSK0KSTauRICC:b-7b6fzn)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-Kgp6eYmdg_-vJHH5z3H:b-h62zhu) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW When I read the usage:

`EXPECT_TRUE(of_dynamic<Derived>(thing));`

doesn't parse very cleanly.

Why not something that reads more obviously:

`EXPECT_TRUE(can_downcast<Derived>(thing));`
</blockquote></details>

I think it was my mistake to (only) mention "downcast" in the documentation. While checking downcast-ability covers most of our use cases, technically `dynamic_cast` can be used in upcasting and sidecasting (w/ multiple inheritance) as well. I'll update the documentation and add more tests. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-Kgp7YqsE9zh6tWDu7G9:b-hvir3y) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L32)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it was my mistake to (only) mention "downcast" in the documentation. While checking downcast-ability covers most of our use cases, technically `dynamic_cast` can be used in upcasting and sidecasting (w/ multiple inheritance) as well. I'll update the documentation and add more tests. 
</blockquote></details>

True. The real point is "of_dynamic" doesn't read easily as a boolean idea. So, while `can_downcast` is too specific, we still want something more readable: `can_be_cast_as` perhaps? For the pedant, `can_be_dynamic_cast_as` is an option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/of_dynamic.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-KgpDSV0n-9hC7vHXyu5:bvu41sd) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

True. The real point is "of_dynamic" doesn't read easily as a boolean idea. So, while `can_downcast` is too specific, we still want something more readable: `can_be_cast_as` perhaps? For the pedant, `can_be_dynamic_cast_as` is an option.
</blockquote></details>

I'm thinking about either `is_dynamic_convertible` or `is_dynamic_castable`. Do you have any preference?

@jwnimmer-tri , what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by jwnimmer-tri** [comment]
`is_dynamic_castable` seems both precise and meaning-is-obvious, so the best answer?

**Comment by soonho-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/test/is_dynamic_castable.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgosNsZZucZ4Pe4Jjpx:-KgpGF0jKhineSj-lGzk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/is_dynamic_castable.h#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

1) I believe you meant `@p ptr` and not `@ptr`
2) BTW A minor grammar point. "downcasted" could/should be "downcast". (http://grammarist.com/usage/casted/) With the "should" depending on what side of the religious war a particular reader lives. I'll accept either.
</blockquote></details>

Done.

---

*[drake/common/test/is_dynamic_castable.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-KgpGJO3qdV2nsQFrc-P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/is_dynamic_castable.h#L32)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm thinking about either `is_dynamic_convertible` or `is_dynamic_castable`. Do you have any preference?

@jwnimmer-tri , what do you think?
</blockquote></details>

Done.

---

*[drake/common/test/is_dynamic_castable.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgotRCpf5QVaPRMms1Y:-KgpGKCHq4gQM_i1UW2m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/is_dynamic_castable.h#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Same notes as above.
</blockquote></details>

Done.

---

*[drake/common/test/is_dynamic_castable.h, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgotVPT65JxuTw0yoy_:-KgpGKovrvxMrLv-TWtt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/is_dynamic_castable.h#L47)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

typo: "...was when __*the*__ test fails."
</blockquote></details>

Done.

---

*[drake/common/test/of_dynamic_test.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-Kgotv_8hVXLX9EN_7G-:-KgpGM0oMUjF6gkK2Zti:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/of_dynamic_test.cc#L46)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This may be the first time I've seen "delete" in drake-related code.  :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: I concur.

---

Reviewed 2 of 9 files at r3.
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/is_dynamic_castable.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-KgouV_V77dFdj3xIGOM:-KgpLa11AThHLyYB-8DM:btf0acq) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5f44d2e2ec1e940f3733b14b636caea11cf5ce/drake/common/test/is_dynamic_castable.h#L32)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Both work for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgpLzfq2RnEcz6pk-Vk:biv6h3e)*

**Comment by jwnimmer-tri** [comment]
Awesome!  Hooray for peer review!

---

Reviewed 7 of 9 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703#-:-KgpRGbTIUeS81N12Utq:b-p1blvn)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 9 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5703)*

**Pull request merged**
