### PR TITLE
pydrake.{autodiff, solvers.ik}: Change old-style placement constructors to new-style constructors

### LINKED ISSUE #8386: pybind: Clean up old `__init__` constructors
As @soonho-tri pointed out, when you build with `-c dbg` and import `pydrake.autodiffutils` or another offending module, you will get warnings about old placement-new style constructors:
https://github.com/pybind/pybind11/blob/master/docs/upgrade.rst#new-api-for-defining-custom-constructors-and-pickling-functions

The fix is relatively simple to switch to a new style (factory) constructor.

\cc @soonho-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #8386

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8387)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8387#-:-L7jQerUsEl_gkOCSctf:blbs4su)*

**Comment by soonho-tri** [comment]
:lgtm: Thank you!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/autodiffutils_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8387#-L7jTNI_9980Off1U5hM:-L7jTNI_9980Off1U5hN:b7mz3ze) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf708f01903d1676e9410375ff9f8cf17379e3/bindings/pydrake/autodiffutils_py.cc#L30)):*
> ```cpp
> 
>   py::class_<AutoDiffXd>(m, "AutoDiffXd")
>     .def(py::init<const double&, const Eigen::VectorXd&>())
> ```

BTW, just for my edification, is an `AutoDiffXd` constructed and moved to self in this new version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8387#-:-L7jTdNShH5x8ZyPhSTG:b-ae66e1)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/autodiffutils_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8387#-L7jTNI_9980Off1U5hM:-L7jkh4nNGvOS9fqr8Rv:btl1cyl) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf708f01903d1676e9410375ff9f8cf17379e3/bindings/pydrake/autodiffutils_py.cc#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, just for my edification, is an `AutoDiffXd` constructed and moved to self in this new version?
</blockquote></details>

OK Yup. This new-style construction is effectively handled by `pybind11/detail/init.h`; this returns a new (on the heap) instance, and passes that to the `holder` of the `pybind11::detail::instance` (via `value_and_holder`):
https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/init.h#L169-L209

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8387)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/autodiffutils_py.cc, line 30 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8387#-L7jTNI_9980Off1U5hM:-L7jo_Rk9ZHwsSC-8QkR:b-tyz9hs) ([raw file](https://github.com/robotlocomotion/drake/blob/61cf708f01903d1676e9410375ff9f8cf17379e3/bindings/pydrake/autodiffutils_py.cc#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK Yup. This new-style construction is effectively handled by `pybind11/detail/init.h`; this returns a new (on the heap) instance, and passes that to the `holder` of the `pybind11::detail::instance` (via `value_and_holder`):
https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/init.h#L169-L209
</blockquote></details>

Got it. Thank you for the clarification!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8387)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8387#-:-L7kqwSN2-QNfEmQsS8I:bnfp4nl)*

**Pull request merged**
