### PR TITLE
Separate GetDrakePath vs @PROJECT_SOURCE_DIR@

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This logically separates three distinct concepts:
- (1) The CMakeProjectSourceDir;
- (2) The GetDrakePath logic when compiling from CMake;
- (3) The GetDrakePath logic when compiling from Bazel.

This is a non-functional change; just shuffling the APIs.  Future edits will update the implementation logic.

The long-since-deprecated getDrakePath spelling is also removed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6188)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape do you have time today to feature-review this?

**Comment by jamiesnape** [comment]
Definitely.

**Comment by jamiesnape** [comment]
Nice. :lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6188#-:-Kl4k1V7mUy4H5TeO0p6:bxsbkqo)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review on-call, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6188#-Kl4w0TjtygwBHqkfYhQ:-Kl4w0TjtygwBHqkfYhR:b-wa9k9u) ([raw file](https://github.com/robotlocomotion/drake/blob/67e78f7cad07f58eb5bc4e50e3510714685fc4a2/drake/common/CMakeLists.txt#L10)):*
> ```CMake
> set(cmake_project_source_dir_cc ${PROJECT_BINARY_DIR}/generated/drake/common/cmake_project_source_dir.cc)
> set(THIS_FILE_IS_USED_BY_CMAKE_TO_CREATE_GENERATED_CODE
>     "This file is auto-generated by CMAKE.  Do not edit.")
> ```

BTW, aww -- that's cute!

---

*[drake/common/drake_path.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6188#-Kl4wL-DhbztY-ylOZXU:-Kl4wL-DhbztY-ylOZXV:bpk3hjl) ([raw file](https://github.com/robotlocomotion/drake/blob/67e78f7cad07f58eb5bc4e50e3510714685fc4a2/drake/common/drake_path.h#L5)):*
> ```objc
> #include <string>
> 
> #include "drake/common/drake_compat.h"
> ```

BTW unused? (Fine with me if you want it here prophylactically.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6188#-:-Kl4x0S47VNSiaaGZWvb:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_path.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6188#-Kl4wL-DhbztY-ylOZXU:-Kl56fVkDVUYSgS6Po-S:bomzdy) ([raw file](https://github.com/robotlocomotion/drake/blob/67e78f7cad07f58eb5bc4e50e3510714685fc4a2/drake/common/drake_path.h#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unused? (Fine with me if you want it here prophylactically.)
</blockquote></details>

OK Yup, my general idea is that headers (especially those in in `drake/common`) that include nothing else must include compat, as a way to (help) ensure it's always available, without needing to splatter it e.g. in every file that we say `make_unique`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6188)*

**Pull request merged**
