### PR TITLE
[multibody] Correct documentation of default set_contact_model()

### PR DESCRIPTION
**Pull request by DamrongGuoy**
I should have done this in #16569.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for both reviewers, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705#-:-MxDDJPJAaevQlvYYp9h:b-m80ccp)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/plant/multibody_plant.h, line 4882 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16705#-MxDDpQ82vstSwo-TFsI:-MxDDpQ82vstSwo-TFsJ:b-8ymm7j) ([raw file](https://github.com/robotlocomotion/drake/blob/06e1deb12539f05eff968c5bd9e11d259916f268/multibody/plant/multibody_plant.h#L4882)):*
> ```objc
>   // with the default value in multibody_plant_config.h; there are already
>   // assertions in the cc file that enforce this.
>   ContactModel contact_model_{ContactModel::kHydroelasticWithFallback};
> ```

This line shows that the default in the master is already hydroelastic contact with fallback.

**Review by DamrongGuoy — COMMENTED** [review]
CC: @sherm1 @rpoyner-tri @amcastro-tri @joemasterjohn

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705#-:-MxDEIzp1YHDFB1IoreM:b-kc5r3j)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705#-:-MxFEnIIBd1GOzgxHHzA:bg7igkv)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @jwnimmer-tri)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16705#-MxFEIvw0Dzp2kpvUTcE):*
minor, "correct" sounds weird to me. Maybe "fix"?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: but I would vote "release notes: none".  The documentation isn't part of the installation.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705#-:-MxFVXsJ5bmPd5M5kxS0:b-g1otm9)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16705)* status: needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16705#-MxFEIvw0Dzp2kpvUTcE):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, "correct" sounds weird to me. Maybe "fix"?
</blockquote></details>

I'll fix that in the merge message.

**Comment by DamrongGuoy** [comment]
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16705#-MxFEIvw0Dzp2kpvUTcE):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'll fix that in the merge message.
</blockquote></details>

Done in master. Thanks!

```
commit 42bc5850654e4264a4078d376c98fa5482ca5121 (HEAD -> master, upstream/master)
Author: Damrong Guoy <42557859+DamrongGuoy@users.noreply.github.com>
Date:   Thu Mar 3 08:14:14 2022 -0800

    [multibody] Fix documentation of default set_contact_model() (#16705)

```

**Pull request merged**
