### PR TITLE
Rename drake/examples/Cars to drake/automotive

### LINKED ISSUE #3406: Rename drake-distro/drake/examples/Cars to drake-distro/drake/automotive
I think the library of vehicular and/or automotive systems (and related toolkit elements) should be an in-tree tookit as part of Drake.  It will very soon outgrow a simple example, if it hasn't already.  Let's agree to move it into a new home at the `drake-distro/drake/mysomething` top level.  If there are any objections to that, speak up now.

(I will debate the name for `mysomething` in a second message, to better allow for voting and/or discussion.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #3406.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3436)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
This PR moves the files and updates all path references.  A subsequent PR will deal with updating the C++ namespaces and any other loose ends.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.
(Doing the reviews concurrently to get this in ASAP; it's very conflict-prone.)

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

otherwise :lgtm:

---

Review status: 0 of 78 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3436#-:-KR_6xE3nYCYITUNMkVf:b-7czelr)*

**Comment by david-german-tri** [comment]
Reviewed 148 of 148 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3436)*

**Comment by rpoyner-tri** [comment]
Ah, just saw your comment above about further loose ends, such as "drakeCars" and "drake_cars" in various places.

:lgtm: 

---

Reviewed 148 of 148 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3436#-:-KR_7bjl3ajxsb8WTN3R:ber686y)*

**Comment by jwnimmer-tri** [comment]
Ah bummer, of course the ROS build is going to fail.  I _always_ forget that.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3436)*

**Comment by jwnimmer-tri** [comment]
Wow.  Three hours from starting typing to a merge.  Possibly a new personal best.

**Pull request merged**
