### PR TITLE
framework: Add DiagramBuilder::GetSystems

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14066)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one question.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14066#-:-MHEzYj58wDJrwjMC71M:b-hryn1j)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/framework_py_semantics.cc, line 443 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14066#-MHEzAGC6r0mCdJb_7YZ:-MHEzAGC6r0mCdJb_7Y_:b6nji8o) ([raw file](https://github.com/robotlocomotion/drake/blob/45b19e6aaa453a6b5b79a209d2416524ed7a9f79/bindings/pydrake/systems/framework_py_semantics.cc#L443)):*
> ```cpp
>         .def("empty", &DiagramBuilder<T>::empty, doc.DiagramBuilder.empty.doc)
>         .def(
>             "GetSystems",
> ```

BTW in Python is GetSystems() identical to GetMutableSystems()? If so consider forwarding the implementation of one to the other rather than repeating it.

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14066#-:-MHH3Y5cC9-xHJNaTJly:bcav8r0)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[bindings/pydrake/systems/framework_py_semantics.cc, line 443 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14066#-MHEzAGC6r0mCdJb_7YZ:-MHH3DxG5ZUmdaSoqirE:b2qlhut) ([raw file](https://github.com/robotlocomotion/drake/blob/45b19e6aaa453a6b5b79a209d2416524ed7a9f79/bindings/pydrake/systems/framework_py_semantics.cc#L443)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in Python is GetSystems() identical to GetMutableSystems()? If so consider forwarding the implementation of one to the other rather than repeating it.
</blockquote></details>

OK They differ in terms of which method on DiagramBuilder they call.  It's possible that one vs the other implementation could have side-effects that we don't want to avoid (or must avoid).  I could factor the lambda both out into keep_alive helper, but for only two copies I think this is clearer.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14066#-:-MHH6cKyDfAjjjFpHKy4:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram_builder.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14066#-MHH5iEnCgS2YJ7V2lrq:-MHH5iEnCgS2YJ7V2lrr:b-gt4fin) ([raw file](https://github.com/robotlocomotion/drake/blob/45b19e6aaa453a6b5b79a209d2416524ed7a9f79/systems/framework/diagram_builder.h#L124)):*
> ```objc
>   bool empty() const { return registered_systems_.empty(); }
> 
>   /// Returns the list of contained Systems.
> ```

minor:  The unit test also appears to be checking that they come out in insert order.  Consider documenting that fact here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14066)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

___
*[systems/framework/diagram_builder.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14066#-MHH5iEnCgS2YJ7V2lrq:-MHHaSMq8E-yDV94Gu5C:bx9fhsp) ([raw file](https://github.com/robotlocomotion/drake/blob/45b19e6aaa453a6b5b79a209d2416524ed7a9f79/systems/framework/diagram_builder.h#L124)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The unit test also appears to be checking that they come out in insert order.  Consider documenting that fact here?
</blockquote></details>

OK I'm on the fence about whether the docs are missing that detail, or the test is too specific.  I'll punt for now leaving the mismatch unchanged.  I'm about to add Disconnect and RemoveSystem in a next PR, so might make sense to revisit then.

**Pull request merged**
