### PR TITLE
[fem] Add VolumetricModel

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881#-:-MzI0DJ5ENNGPoDNEslU:bgvwxyh)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
feature pass done.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881#-:-MzVTvly38hlB_GE2EcT:b9atdu4)* status: 18 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/test/volumetric_model_test.cc, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVS-xv-Ep_1GufygAu:-MzVS-xv-Ep_1GufygAv:b4m31by) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/test/volumetric_model_test.cc#L104)):*
> ```cpp
> 
>   /* Returns an arbitrary FEM data whose generalized positions are different
>    from reference positions and whose velocities and acclerations are nonzero.
> ```

nit, acclerations
___
*[multibody/fem/test/volumetric_model_test.cc, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVT1LYD-sHFBYihWyk:-MzVT1LYD-sHFBYihWyl:b-wtlbyi) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/test/volumetric_model_test.cc#L155)):*
> ```cpp
> /* Tests that the tangent matrix of the model is the derivative of the residual
>  with respect to the change in a. */
> TEST_F(VolumetricModelTest, TangentMatrixIsResidualDerivative) {
> ```

nit, consider adding this is only true for the linear model used in this test (since in general the contribution from damping terms is only an approximation).
___
*[multibody/fem/test/volumetric_model_test.cc, line 177 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVTYIv1wNYiz8JxT43:-MzVTYIv1wNYiz8JxT44:bgit6uo) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/test/volumetric_model_test.cc#L177)):*
> ```cpp
>      VectorX<AutoDiffXd>. */
>     EXPECT_TRUE(CompareMatrices(residual(i).derivatives(),
>                                 tangent_matrix_dense.col(i),
> ```

fyi, you can use `math::ExtractGradient()` to get the full dense gradient and compare it against `tangent_matrix_dense` with a single call to `CompareMatrices()` 
___
*[multibody/fem/test/volumetric_model_test.cc, line 194 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVTsoH1o-1z8dgVtid:-MzVTsoH1o-1z8dgVtie:bjpg1q9) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/test/volumetric_model_test.cc#L194)):*
> ```cpp
>   EXPECT_EQ(fem_state->num_dofs(), 2 * kNumDofs);
> }
> ```

don't we need a test for `CalcElasticEnergy()`?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 18 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881#-:-MzWoKLq6IydYpirhcpv:bg7igkv)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/fem/fem_model_impl.h, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVJC1d9eTVudYQRSDW:-MzWpLzrEP2mwVDyMU2b:b-6owu9d) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/fem_model_impl.h#L119)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why do you think we still need the `if` statement?
</blockquote></details>

Otherwise the compiler isn't happy. In particular, our Petsc matrix class only supports double and 

`tangent_matrix->AddToBlock(block_indices, element_tangent_matrix);` 

causes trouble.
___
*[multibody/fem/volumetric_model.h, line 103 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVNudzD2Y2cRLqj182:-MzWqpiHBRmpq6Hqp3vo:bt6dap0) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't see any future where Eigen would support this. IMO this line is misleading. The copy will always happen and that should be reflected.
</blockquote></details>

See reference below.
___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzWpgy87Le1UOp5Ra3o:bmqsdl6) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

that a big file. Where should I look?
</blockquote></details>

Search for "EIGEN_HAS_RVALUE_REFERENCES"
___
*[multibody/fem/test/volumetric_model_test.cc, line 203 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzWo9MN1SLN3URJjI-V:-MzWpiroC4iaLHruRu9E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a5c706e5dcca02c8d0cd22270ea895357c8b709c/multibody/fem/test/volumetric_model_test.cc#L203)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you document why the expected volume is 0.1^3?
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/fem_model_impl.h, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVJC1d9eTVudYQRSDW:-Mz_HC8UCrHDP5HmpOZc:b-f2krql) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/fem_model_impl.h#L119)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Otherwise the compiler isn't happy. In particular, our Petsc matrix class only supports double and 

`tangent_matrix->AddToBlock(block_indices, element_tangent_matrix);` 

causes trouble.
</blockquote></details>

I see thanks. consider adding note capturing this discussion.
___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-Mz_Gy1T3b-NQB1WCU59:ba85qrs) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Search for "EIGEN_HAS_RVALUE_REFERENCES"
</blockquote></details>

In that file? I couldn't find it. Is this behavior documented?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/volumetric_model.h, line 125 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVPwZn82x0h5Wzk22n:-MzoqM1C2PGVHhR2cCwD:b-kayj40) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L125)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There is separate offsets for elements that are already in the builder but still not yet in the model.
</blockquote></details>

oh, I see. Could I suggest the offseting happens only in a single location? say in the AddLinearTetrahedralElements()? by defining `node_index_offset = model_->num_nodes() + reference_positions_.size() / 3`. That way you can document in a single spot this offset logic.
Is there is another reason to split this offseting between these two locations, then I'd ask you to find a way to document how they sync with each other.
___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-Mzoo4Wa58kBNvDijPfs:b-m4l5so) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Eigen supports move semantics:


See /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:L370 and related.

```c++
#if EIGEN_HAS_RVALUE_REFERENCES
    EIGEN_DEVICE_FUNC
    DenseStorage(DenseStorage&& other) EIGEN_NOEXCEPT
      : m_data(std::move(other.m_data))
      , m_rows(std::move(other.m_rows))
      , m_cols(std::move(other.m_cols))
    {
      other.m_data = nullptr;
      other.m_rows = 0;
      other.m_cols = 0;
    }
```

and

```c++
#if EIGEN_HAS_RVALUE_REFERENCES
    EIGEN_DEVICE_FUNC
    PlainObjectBase(PlainObjectBase&& other) EIGEN_NOEXCEPT
      : m_storage( std::move(other.m_storage) )
    {
    }
```

and

```c++
#if EIGEN_HAS_RVALUE_REFERENCES
    EIGEN_DEVICE_FUNC
    Matrix(Matrix&& other) EIGEN_NOEXCEPT_IF(std::is_nothrow_move_constructible<Scalar>::value)
      : Base(std::move(other))
    {
      Base::_check_template_params();
    }
```
</blockquote></details>

That code above is to move the entire object? as expected?

ok, sorry if slow. Maybe my dominion of the C++ language often times fails me.
I am of course familiar with the move semantics of "entire" objects and I would of course be surprised if Eigen didn't support it.
Now, here we are moving into just a small portion of a second object (it's tail in this case), and that's strange to me.

When I do `std::move(some_container_obj)` I'd expect the entire object to be moved. However, how should I understand this particular line? like each individual entry of the container gets moved? what happens with the memory of the object itself? is that the right way to think about it?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzorZuu2k9DOiOTwI7A:b-y2fmx3) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

That code above is to move the entire object? as expected?

ok, sorry if slow. Maybe my dominion of the C++ language often times fails me.
I am of course familiar with the move semantics of "entire" objects and I would of course be surprised if Eigen didn't support it.
Now, here we are moving into just a small portion of a second object (it's tail in this case), and that's strange to me.

When I do `std::move(some_container_obj)` I'd expect the entire object to be moved. However, how should I understand this particular line? like each individual entry of the container gets moved? what happens with the memory of the object itself? is that the right way to think about it?



</blockquote></details>

To help you understand my surprise. For a container like `std::vector`, I have very special semantics to accomplish this, namely `std::make_move_iterator`. In that case I'd do something like `a.insert(a.end(), std::make_move_iterator(b.begin()), std::make_move_iterator(b.end()));`. The very awckard semantics makes me think twice and then after a few seconds I do realize what's going on. 

The same thing does not happen to me when I read `eigen_vector.tail() = std::move(some_other_eigen_vector`.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/fem/fem_model_impl.h, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVJC1d9eTVudYQRSDW:-Mzq8sCnCHRnyDdc9jYg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/fem_model_impl.h#L119)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see thanks. consider adding note capturing this discussion.
</blockquote></details>

Done.
___
*[multibody/fem/volumetric_model.h, line 125 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVPwZn82x0h5Wzk22n:-MzpQEok7t-oK-V4gRf5:b-1m0yvj) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L125)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

oh, I see. Could I suggest the offseting happens only in a single location? say in the AddLinearTetrahedralElements()? by defining `node_index_offset = model_->num_nodes() + reference_positions_.size() / 3`. That way you can document in a single spot this offset logic.
Is there is another reason to split this offseting between these two locations, then I'd ask you to find a way to document how they sync with each other.

</blockquote></details>

I moved the offset logic to `DoBuild` PTAL, thanks.
___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzpO2wMCWZo0xgsCBqK:b-15apb4) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
> The same thing does not happen to me when I read eigen_vector.tail() = std::move(some_other_eigen_vector).

If you look at the implementation of move assignment operator in `Eigen::DenseStorage`, it simply swaps the pointer to the underlying storage (`m_data`).

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881#-:-MzqD71703va91Yk_wYb:b-w5mc00)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor kcov questions

> Reviewed 1 of 4 files at r2, 1 of 6 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881#-:-MzqKE3h-NwUAvTj9_3h:bwxj5uu)* status: 3 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/volumetric_model.h, line 124 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzqIsWD7wsaMSwrK3UO:-MzqIsWD7wsaMSwrK3UP:b-xsbop1) ([raw file](https://github.com/robotlocomotion/drake/blob/d854722f8959e0b8b7f17ce92a30fdc221bbc6a5/multibody/fem/volumetric_model.h#L124)):*
> ```objc
>       std::vector<int> node_index_offsets(num_new_meshes, 0);
>       for (int m = 1; m < num_new_meshes; ++m) {
>         node_index_offsets[m] = elements_[m - 1].size();
> ```

minor this loop body is not reached by tests. Should I worry?
___
*[multibody/fem/volumetric_model.h, line 131 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzqIyxh86Km68g41_xt:-MzqIyxh86Km68g41_xu:b-xsbop1) ([raw file](https://github.com/robotlocomotion/drake/blob/d854722f8959e0b8b7f17ce92a30fdc221bbc6a5/multibody/fem/volumetric_model.h#L131)):*
> ```objc
>       std::vector<int> dof_offsets(num_new_meshes, 0);
>       for (int m = 1; m < num_new_meshes; ++m) {
>         dof_offsets[m] = reference_positions_[m - 1].size();
> ```

minor this loop body is not reached by tests. Should I worry?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzqOR2c01hY5WvDGUCQ:b-498ybt) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> The same thing does not happen to me when I read eigen_vector.tail() = std::move(some_other_eigen_vector).

If you look at the implementation of move assignment operator in `Eigen::DenseStorage`, it simply swaps the pointer to the underlying storage (`m_data`).
</blockquote></details>

I think I understand that. My question is, is the result of `tail()` an `Eigen::DenseStorage()`?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzqV2VCDWKI9dHBoieQ:bymzmb7) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think I understand that. My question is, is the result of `tail()` an `Eigen::DenseStorage()`?
</blockquote></details>

A little digging in Eigen seems to suggest that.
___
*[multibody/fem/volumetric_model.h, line 124 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzqIsWD7wsaMSwrK3UO:-MzqUx2S09MBi3jpQk4d:b1zgp6y) ([raw file](https://github.com/robotlocomotion/drake/blob/d854722f8959e0b8b7f17ce92a30fdc221bbc6a5/multibody/fem/volumetric_model.h#L124)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor this loop body is not reached by tests. Should I worry?
</blockquote></details>

I think we should. Working.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/fem/volumetric_model.h, line 124 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzqIsWD7wsaMSwrK3UO:-MzqjEu9BXCOmam-KEyj:b-6erwie) ([raw file](https://github.com/robotlocomotion/drake/blob/d854722f8959e0b8b7f17ce92a30fdc221bbc6a5/multibody/fem/volumetric_model.h#L124)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think we should. Working.
</blockquote></details>

Done. Feel free to merge if you think the PR is ready.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16881)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri

___
*[multibody/fem/volumetric_model.h, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16881#-MzVQWxt0lQL1W836tw5:-MzzCG3sACL37AWQO-4n:b-viackp) ([raw file](https://github.com/robotlocomotion/drake/blob/7701cd233855fa094106d1deb35df44baca6d3af/multibody/fem/volumetric_model.h#L135)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

A little digging in Eigen seems to suggest that.
</blockquote></details>

I still don't understand how this is even possible. I'll ask you f2f.

**Pull request merged**
