### PR TITLE
Test eigen RC 3.4

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This is the canary branch for #14968.

Known issues:
- [x] #15065
- [x] #15298
  - [x] [Eigen MR 562](https://gitlab.com/libeigen/eigen/-/merge_requests/562)
- [x] #15323
- [x] #15335 (TypeSafeIndex)
- [x] #15401
  - [x] #15495
- [x] #15444
  - [x] #15453
- [x] #15449
- [x] #15450
- [x] #15451
- [x] #15452
- [x] #15486
- [x] #15498
  - [x] #15517
- [x] #15499
- [x] #15556
- [x] #15579
  - [x] #15580

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15142)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please.
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please.

**Comment by jamiesnape** [comment]
@BetsyMcPhail Can you try the head of the 3.4 branch too and see if there is any difference?

**Comment by BetsyMcPhail** [comment]
Re-testing now with branch 3.4

**Comment by jamiesnape** [comment]
Cool. Not necessarily expecting it to be different, but it would be nice if the some of the issues were fixed bugs in Eigen.

**Comment by jwnimmer-tri** [comment]
I've merged this up to Drake master now, so we can continue to narrow this down.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
Update: Great progress here.

As best I can tell, the two apparent CMake pre-merge failures are just CTest / CDash being uppity about some regex from the build's console output.  It does not appear that the install is actually failing in any way.  Tough to tell for sure, though.

Thus, Drake master passes all pre-merge tests, with the only patch being an Eigen upstream merge request that hasn't landed in Eigen 3.4 yet.

I'm trying all of the post-merge builds now.  Good luck, Jenkins.

**Comment by jwnimmer-tri** [comment]
Full CI results showed one additional memcheck problem (now fixed via #15499), and one unfixed problem (#15498) related to new Eigen + Apple Clang + std::function.  So, we are pretty close.

**Comment by jwnimmer-tri** [comment]
There seem to be some new problems now with `numext::equal_to` vs the STL vs Formula / bool.  I haven't tried to root cause it yet.

**Comment by jwnimmer-tri** [comment]
Everything is passing now!  The only CI errors are CDash ignore exit codes in lieu of console scraping.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-coverage please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
Wow.  _Everything_ passed.

**Comment by jwnimmer-tri** [comment]
I guess just to save some CI cycles / CI clarity, I'll close this out for now.

Once Eigen releases an official rc2, we should probably re-test then.

**Pull request closed without merging**
