### PR TITLE
Simple test of calling MathematicalProgram from matlab via the python interface

### PR DESCRIPTION
**Pull request by RussTedrake**
It's clunky, but it does work.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5980)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-:-KiwL_BavqqFki2So0xH:b-85dizs)*

**Comment by EricCousineau-TRI** [comment]
Aside from some minor comments here and there, looks awesome!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/CMakeLists.txt, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwMUQJjVtIKMuYF3B1:-KiwMUQK6RVeyEBifSBj:b-p0fofu) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/CMakeLists.txt#L37)):*
> ```CMake
>   endif()
> 
>   drake_add_matlab_test(NAME pydrake.test.testMathematicalProgram.m
> ```

Would it be possible to add a quick comment that this is only in CMake since MATLAB-testing is not possible via Bazel? And maybe a quick cross-reference in corresponding `BUILD`file?

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwMvjByUAghemmQebU:-KiwMvjByUAghemmQebV:buae7np) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L8)):*
> ```objc
> % QP test
> prog = py.pydrake.solvers.mathematicalprogram.MathematicalProgram();
> x = prog.NewContinuousVariables(int32(2),'x');
> ```

BTW I can see that needing to explicitly cast to `int32` or what not might be annoying for future use.
I've added a separate issue to consider this: #5981

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwMmTgnZyCFtlQGlSV:-KiwMmThmUhyF8kFl3yq:b-m5q4ub) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L11)):*
> ```objc
> prog.AddLinearConstraint(x.item(0) >= 1);
> prog.AddLinearConstraint(x.item(1) >= 1);
> prog.AddQuadraticCost(py.numpy.eye(2), py.numpy.zeros(2), x);
> ```

Instead of using `numpy`, could we use MATLAB directly? `eye(2)` and `zeros(2)`?

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwLzi686mKt5YiRa1k:-KiwLzi7yqNBu_gHwH2m:bumsest) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L14)):*
> ```objc
> result = prog.Solve()
> 
> % Note: int32(0) is kSolutionFound; can't reference it directly.
> ```

BTW I believe we can bind the enumerations: http://pybind11.readthedocs.io/en/master/classes.html#enumerations-and-internal-types
Would you like me to add this as a new issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-:-KiwR_1NQ1VM8aDuO5JD:b-xn9h15)*

**Comment by EricCousineau-TRI** [comment]
*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwLzi686mKt5YiRa1k:-KizcqMkOSKjcKDJHX53:b-xypg12) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L14)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I believe we can bind the enumerations: http://pybind11.readthedocs.io/en/master/classes.html#enumerations-and-internal-types
Would you like me to add this as a new issue?
</blockquote></details>

BTW Sorry, just realized that we already have `kSolutionFound` bound in `pybind11`. I will try this out later to see what limitations there presently are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980)*

**Comment by RussTedrake** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/bindings/python/CMakeLists.txt, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwMUQJjVtIKMuYF3B1:-Kj2jt-NOwqfHGpgVKaa:b-r5doxm) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/CMakeLists.txt#L37)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be possible to add a quick comment that this is only in CMake since MATLAB-testing is not possible via Bazel? And maybe a quick cross-reference in corresponding `BUILD`file?
</blockquote></details>

I think that the cmakelists.txt comment is implied, but i've added the note to the BUILD file. 

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwMmTgnZyCFtlQGlSV:-Kj2n5MWONCzdMc8N0O4:bdv9fvk) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L11)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Instead of using `numpy`, could we use MATLAB directly? `eye(2)` and `zeros(2)`?
</blockquote></details>

i definitely tried it, but no dice.  i found a useful discussion (and conversion utility) here: https://www.mathworks.com/matlabcentral/answers/157347-convert-python-numpy-array-to-double

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.m, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-KiwLzi686mKt5YiRa1k:-Kj2nR4wMRjSgAieuUKq:b-gkjg59) ([raw file](https://github.com/robotlocomotion/drake/blob/b552649e255498cc560471de4d8dbec50401af35/drake/bindings/python/pydrake/test/testMathematicalProgram.m#L14)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Sorry, just realized that we already have `kSolutionFound` bound in `pybind11`. I will try this out later to see what limitations there presently are.
</blockquote></details>

it's possible there is a way to instantiate it, but I could not find it in my quick attempts.  ironically, the display routine for the variable returned from Solve() prints kSolutionFound just fine.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-:-Kj3Q-exEUTLEn8ysj5X:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-:-Kj3T-JollWjihSlshX7:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-Kj3WNOjhaRtncSq6nsu:-Kj3WNOk1EFV1xGhA57f:b-ox7tss) (no related file):*
Prior to this PR, we had a nice physical separation going, where matlab-dependent code was isolated into one folder (modulo examples) so that physical dependencies were clear and we didn't need one-off build-system comments like the note added here to `drake/bindings/BUILD`.

Is there a way this test can move into another folder, either e.g. in `drake/matlab` or `drake/bindings/matlab`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-Kj3WNOjhaRtncSq6nsu:-Kj3iZdewKimx5HqZP9p:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Prior to this PR, we had a nice physical separation going, where matlab-dependent code was isolated into one folder (modulo examples) so that physical dependencies were clear and we didn't need one-off build-system comments like the note added here to `drake/bindings/BUILD`.

Is there a way this test can move into another folder, either e.g. in `drake/matlab` or `drake/bindings/matlab`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5980#-:-Kj3rTGt4pZikSoQGvLr:bnfp4nl)*

**Pull request merged**
