### PR TITLE
Add lcm_vector_gen support for bounds and use in BicycleCar and IdmPlanner

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5667)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-:-KgUIgCUxus1vNAg-7qB:b-3uz9w8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-:-KgUNF9OEV0B-Qqup5Gs:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car: ready once other reviews complete

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-:-KgUTIr4ys-hsTZObzu5:b-onbywl)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-KgWUYrYC473Srgzy5ZI:-KgWUYrYC473Srgzy5ZJ:bi22lsz) (no related file):*
This PR kind of skirts around `>= 0` vs `> 0` bounds (by only doing `>=` and `<=`).  It wouldn't be too hard to make the named_vector provide `min_value_inclusive` `min_value_exclusive` `max_value_inclusive` `max_value_exclusive`, if we thought that would be more meaningful to the the optimizers.  Would it be worth it?  @jadecastro @RussTedrake?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667)*

**Comment by jadecastro** [comment]
Reviewed 13 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-KgWUYrYC473Srgzy5ZI:-KgWWxHk9EEHJxDLWBAc:b-lp3a9l) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR kind of skirts around `>= 0` vs `> 0` bounds (by only doing `>=` and `<=`).  It wouldn't be too hard to make the named_vector provide `min_value_inclusive` `min_value_exclusive` `max_value_inclusive` `max_value_exclusive`, if we thought that would be more meaningful to the the optimizers.  Would it be worth it?  @jadecastro @RussTedrake?
</blockquote></details>

My take is that it's fine as is since non-strict inequalities are usually used to form bounding box constraints on the variables. I think strict inequalities are usually converted to non-strict inequalities anyway before being passed to optimizers, but I am not sure whether or not this occurs within the solver.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-KgWUYrYC473Srgzy5ZI:-KgW_Vu6mcW78VF7FBmK:bg7igkv) (no related file):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

My take is that it's fine as is since non-strict inequalities are usually used to form bounding box constraints on the variables. I think strict inequalities are usually converted to non-strict inequalities anyway before being passed to optimizers, but I am not sure whether or not this occurs within the solver.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667)*

**Comment by jadecastro** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667)*

**Comment by RussTedrake** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5667#-KgWUYrYC473Srgzy5ZI:-KgYsHJbAPtpM4RRF6pq:b-xfrjj3) (no related file):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

i agree w/ jon.  numerical solvers generally do not have any support for strict inequalities; it's not clear that they even make sense.  the only way to get them is to do e.g. >= tolerance.   So i think it's perhaps most correct for us to also support only <= and >=.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5667)*

**Pull request merged**
