### PR TITLE
workspace: Upgrade meshcat_python to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14417)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14417#-:-MNyGOzp1T3xO1TigypM:bxpoy3v)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14417#-:-MNyKgqg5fXXVwirGZ74:bnfp4nl)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14417#-MNyKKzW6-t4x0uUvj_8:-MNyKKzY3ucB4uhMnIGu:b-g03wop) (no related file):*
Built drake :heavy_check_mark: 
Ran tests :heavy_check_mark: 
Manually fiddled with `examples/manipulation_station/end_effector_teleop_sliders`

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14417)* status: needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: for basic platform (sorry for delay!)

Trusting Rico's feature review for usability testing

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14417#-:-MO-aDvx5lFJqd788ZS4:b-lscgsg)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
