### PR TITLE
Scale decision variables

### PR DESCRIPTION
**Pull request by yminchen**
Added a feature for scaling decision variables so that users don't need to scale the variables every time they appears in cost and constraints. 

This feature is only implemented for snopt currently.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12576)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by yminchen** [comment]
> _[solvers/mathematical_program.cc, line 1195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12576#-LybrIIQ0go_E-j6mH0a:-LybrIIQ0go_E-j6mH0b:b77mz24) ([raw file](https://github.com/robotlocomotion/drake/blob/9f1d91ed407d59ddef971fc0b74bce6279fabf2a/solvers/mathematical_program.cc#L1195)):_
> 
> > ```c++
> >   for (int i = idx_start; i <= idx_end; i++) {
> >     // Check if the scaling has been set already
> >     DRAKE_DEMAND(var_scaling_map_.find(i) == var_scaling_map_.end());
> > ```
> 
> Why we don't allow to reset the variable scaling factor?

I think it's a rare case that users want to reset the scaling factor. Also, it's easy to use wrong indices accidentally.
I added `ResetVariableScaling` beside the original `SetVariableScaling` in case users want to reset.

**Comment by yminchen** [comment]
> PTAL
> 
> > Reviewed 4 of 4 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12576#-:-LybtkNS3CRyOQKmbV28:bb71pro)_ status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @yminchen)
> 

Do I need to do anything if I opt for squash and merge?

@hongkai-dai I've updated the code according to your comments. Let me know if I should change anything else. Thanks!

**Comment by yminchen** [comment]
@hongkai-dai I combined the two functions and added the unit tests.

**Comment by yminchen** [comment]
> _[solvers/mathematical_program.h, line 2775 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12576#-LyfEsYv-AtXF05CDlMC:-LyfEsYv-AtXF05CDlMD:b6f2c30) ([raw file](https://github.com/robotlocomotion/drake/blob/3173ba6f09f48425e99e184e8333254200e4c883/solvers/mathematical_program.h#L2775)):_
> 
> > ```objc
> >    * @param s scaling factor (must be positive).
> >    * @param idx index of the decision variable.
> >    * @param is_update a boolean whose value is true if users want to reset the
> > ```
> 
> I don't think we have to provide `is_update` as an input. I think we can always do is_update= True. The logic is that if the variable doesn't have a scaling factor yet, then we add the scaling factor to that variable; if the variable has a scaling factor already, then we just update the scaling factor.
> 

One purpose of the flag was to check whether the scaling of the variable has already been set or not in case the user didn't intend to overwrite it. I removed the flag, but also created another function `IsVariableScalingUnset` which does the checking job. 

> _[solvers/test/mathematical_program_test.cc, line 2937 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12576#-LyfFgJg-c5bO4Rt-Rr4:-LyfFgJg-c5bO4Rt-Rr5:b-p2vk6f) ([raw file](https://github.com/robotlocomotion/drake/blob/3173ba6f09f48425e99e184e8333254200e4c883/solvers/test/mathematical_program_test.cc#L2937)):_
> 
> > ```c++
> >   EXPECT_EQ(prog.GetVariableScaling().size(), 0);
> > 
> >   prog.NewContinuousVariables(4, "x");
> > ```
> 
> BTW, in case you don't know yet, you could do prog.NewContinuousVariables<4>("x"), this returns a static-sized Eigen vector; while prog.NewContinuousVariables(4, "x) returns a dynamic-sized Eigen vector. Sometimes it is preferrable to use the static sized one (no dynamic memory allocation, faster in computation, etc).
> 

Thanks! I didn't know this before.

> 
> _[solvers/test/snopt_solver_test.cc, line 383 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12576#-LyfGc5i8pvhlV6lbfUV:-LyfGc5i8pvhlV6lbfUW:b8vgtce) ([raw file](https://github.com/robotlocomotion/drake/blob/3173ba6f09f48425e99e184e8333254200e4c883/solvers/test/snopt_solver_test.cc#L383)):_
> 
> > ```c++
> > }
> > 
> > GTEST_TEST(SnoptTest, VariableScaling) {
> > ```
> 
> This only tests the linear cost and bounding box constraint. Could you also add a nonlinear constraint/cost, and also a linear constraint?

I added another test which contains quadratic cost and both linear and quadratic constraints.

**Comment by yminchen** [comment]
> _[solvers/mathematical_program.h, line 2791 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12576#-Lykjtyc7PM0r1DQnJLT:-Lykjtyc7PM0r1DQnJLU:bervmwm) ([raw file](https://github.com/robotlocomotion/drake/blob/9dcc5a07cc23695e5860c8c40d22eeae31cdb3ff/solvers/mathematical_program.h#L2791)):_
> 
> > ```objc
> >    * See @ref variable_scaling "Variable scaling" for more information.
> >    */
> >   bool IsVariableScalingUnset(int idx_start, int idx_end);
> > ```
> 
> Do you want the external user to call this function often? If not, we can remove this function, and it is easy for the user to tell whether the scaling factor has been set or not, by query the map returned from`GetVariableScaling`. MathematicalProgram class now has too many public functions, and I hope we don't add more to it.
> 

I use this almost every time before I call `SetVariableScaling`. I think it will be helpful for the users. Do you still think we should remove it?

**Comment by yminchen** [comment]
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12576)_ status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @yminchen)
> 
> _[solvers/mathematical_program.h, line 2791 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12576#-Lykjtyc7PM0r1DQnJLT:-LyopmCE0jFKPKhhcLdf:b-288522) ([raw file](https://github.com/robotlocomotion/drake/blob/9dcc5a07cc23695e5860c8c40d22eeae31cdb3ff/solvers/mathematical_program.h#L2791)):_
> Previously, yminchen (Yu-Ming Chen) wrote…
> 
> May I ask why you call this function before calling SetVariableScaling? If the variable scaling has been set already, and then you call `SetVariableScaling` again, what is the disadvantage?
>

I found that it was easy to use the wrong variable indices when there are many decision variables. Checking the scaling factor has not been set before calling the setter helps to eliminate some of the bugs.   
 
> _[solvers/test/snopt_solver_test.cc, line 423 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12576#-Lykku2cAhO8VqrgDjYU:-LyopZ7S-LzNgwR6Avkg:b5d9ezo) ([raw file](https://github.com/robotlocomotion/drake/blob/9dcc5a07cc23695e5860c8c40d22eeae31cdb3ff/solvers/test/snopt_solver_test.cc#L423)):_
> Previously, hongkai-dai (Hongkai Dai) wrote…
> 
> I don't see using the initial guess yet? You could change `solver.Solve(prog, {}, {});` to `solver.Solve(prog, initial_guess, {});` where `initial_guess` is an Eigen::VectorXd containing the initial guess.

That's strange. I added it in the latest commit. 
https://github.com/RobotLocomotion/drake/pull/12576/files#diff-43c4017e7f08a3a926c2f182554a294aR423

**Comment by yminchen** [comment]
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12576)_ status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @yminchen)
> 
> _[solvers/mathematical_program.h, line 2791 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12576#-Lykjtyc7PM0r1DQnJLT:-LypbM_XAdYFT178Q5M4:b9pkcov) ([raw file](https://github.com/robotlocomotion/drake/blob/9dcc5a07cc23695e5860c8c40d22eeae31cdb3ff/solvers/mathematical_program.h#L2791)):_
> 
> > I found that it was easy to use the wrong variable indices when there are many decision variables.
> 
> Maybe it is easier to change the API to
> 
> ```
> void SetVariableScaling(const symbolic::Variable& var, double scaling_factor);
> ```
> 
> The user have easy access to a variable (as returned from NewContinuousVariable()), but don't quite have access to the variable index. I believe it is less likely to incorrectly set the scaling for the wrong variable using this API, than using variable index?
> 
> And I think we can also remove `SetVariableScaling(double scaling_factor, int start_idx, int end_idx)`. The user only need to know about decision variables. The indices of these variables is an implementation detail, and the user shouldn't need to care about the indices (the variables returned from NewContinuousVariables() don't have to have contiguous indices, we implemented it to have contiguous indices, but we don't have to).
> 

Yes, using symbolic::Variable is a good suggestion! I also moved `IsVariableScalingUnset` to dairlib, since it's only one line code after using symbolic::Variable

**Comment by jwnimmer-tri** [comment]
The text warnings should be limited to once per process, otherwise they would spam the user and slow down the program.  See https://github.com/RobotLocomotion/drake/blob/9f5eb7e7556c17d587da9ff2c90c7a3a8eb76c7d/common/text_logging.h#L177-L198 for now.

The text warnings should not brittlely repeat the list of which solver(s) support this feature; they should just say that the requested solver did not support the feature.

**Comment by yminchen** [comment]
> The text warnings should be limited to once per process, otherwise they would spam the user and slow down the program. See
> 
> https://github.com/RobotLocomotion/drake/blob/9f5eb7e7556c17d587da9ff2c90c7a3a8eb76c7d/common/text_logging.h#L177-L198
> for how.
> 

I'm not quite sure where you want to implement the text warning?

**Comment by jwnimmer-tri** [comment]
Ah, yes.  Limiting to once per process would end up needing a helper function shared by all solvers, and then we could not easily say which solvers in use were deficient.

I'll revise my suggestion to once _per solver type_ per process, like this example:

```c++
void CsdpSolver::DoSolve(const MathematicalProgram& prog,
                         const Eigen::VectorXd&, const SolverOptions&,
                         MathematicalProgramResult* result) const {
  if (!prog.GetVariableScaling().empty()) {
    static const logging::Warn log_once(
        "CsdpSolver doesn't support the feature of variable scaling.");
  }
  // ...
```

**Pull request merged**
