### PR TITLE
[bindings] Add env var DRAKE_PYTHON_LOGGING to disable redirect

### LINKED ISSUE #19680: [pydrake] Disable spdlog redirection when using multithreaded C++ code?
**Is your feature request related to a problem? Please describe.**
I am writing Python bindings in a downstream project (Anzu) that does work in a multithreaded fashion, and calls `drake::log()->info()`, `->debug()`, `->trace()`, etc., in those separate threads.

Even though this code doesn't explicitly call Python code in those other threads (e.g. not via `std::function<>` or C++ <-> Python polymorphism), it still seemed to deadlock.

If I commented out this line, my multithreaded code seemed to work fine:
https://github.com/RobotLocomotion/drake/blob/b9813a712454580cd6bc0724f8d2506d85412e58/bindings/pydrake/common/module_py.cc#L103

**Describe the solution you'd like**
Perhaps an environment variable, like `PYDRAKE_NO_SPDLOG_REDIRECT`, or a function to call from pydrake that undoes the effects of `MaybeRedirectPythonLogging()` and related methods.

**Describe alternatives you've considered**
(1) Writing a C++ pybind11 module as follows, then importing it before `pydrake`, fixes the "seems to deadlock" issue:
https://gist.github.com/EricCousineau-TRI/ff52a8e3be0ca5fd085307c16ff09dbc

(2) Set spdlog's debugging level such that no messages are printed

(3) Add an option to only redirect to Python if it's the main thread. If it isn't the main thread, it should ideally emit directly to `stderr` as the nominal sink would.

**Additional context**
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1687807563590549

\cc @jwnimmer-tri @dmcconachie-tri @sammy-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #19680

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri Would you be up for feature review on this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-:-NYxNtXv42kobw0I4vby:bzdudz4)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
Sure.

The implementation looks fine; I'll need to circle back a little later to grok the tests.

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-:-NYxPaUeBFX13I4-uicH:bqzikfz)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYxOsXR765C2XnFhEir:-NYxOsXSD_hooqVSXAgn:b8dwj3m) (no related file):*
Users will need documentation of this new variable to make use of it.

The https://drake.mit.edu/doxygen_cxx/group__environment__variables.html page should list this variable in the inventory, and then either explain what it does inline or else link to somewhere that explains what it does (e.g., the pydrake docs).

___

**Review by jwnimmer-tri — COMMENTED** [review]
https://github.com/EricCousineau-TRI/drake/pull/17 with suggestions.

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-:-NYxuY3a1cuaAvdwqSx3:bbcznqs)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYxOsXR765C2XnFhEir:-NYyu1neALdAqlBSFf2c:b-41t7rf) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Users will need documentation of this new variable to make use of it.

The https://drake.mit.edu/doxygen_cxx/group__environment__variables.html page should list this variable in the inventory, and then either explain what it does inline or else link to somewhere that explains what it does (e.g., the pydrake docs).
</blockquote></details>

Attempted in latest revision, but I'm not immediately able to figure out why `doxygen.h` can't resolve to groups in `pydrake_doxygen.h`.

Is there any chance you see something obvious that I missed?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYxOsXR765C2XnFhEir:-NYz-1fz1Eqti3BaOF8z:b3pnexc) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Attempted in latest revision, but I'm not immediately able to figure out why `doxygen.h` can't resolve to groups in `pydrake_doxygen.h`.

Is there any chance you see something obvious that I missed?
</blockquote></details>

For reasons I don't understand, that particular file has always been _very_ fussy about triple backticks.  A newline and removing the `sh` hint seems to fix it:

```patch
--- a/bindings/pydrake/pydrake_doxygen.h
+++ b/bindings/pydrake/pydrake_doxygen.h
@@ -646,7 +646,8 @@ then logging will not be redirected.
 
 For example, to disable logging redirect, you can set the following in
 your terminal before you run your process that uses pydrake:
-```sh
+
+```
 export PYDRAKE_PYTHON_LOGGING=0
 ```
 
```
```


___
___
*[`bindings/pydrake/pydrake_doxygen.h` line 641 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYz-HuxB4enLrgX3A7-:-NYz-HuxB4enLrgX3A70:b1ukuz7) ([raw file](https://github.com/RobotLocomotion/drake/blob/a8aa4031ecbfffd99125a1f3f406a92350fee31d/bindings/pydrake/pydrake_doxygen.h#L641)):*
> ```objc
> @addtogroup environment_variables
> @{
> @defgroup pydrake_python_logging PYDRAKE_PYTHON_LOGGING
> ```

nit The name is `DRAKE_PYTHON_LOGGING`.

Ditto below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYxOsXR765C2XnFhEir:-NZ1t7zR6ovVR_dZUFdZ:b-qcv5w1) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For reasons I don't understand, that particular file has always been _very_ fussy about triple backticks.  A newline and removing the `sh` hint seems to fix it:

```patch
--- a/bindings/pydrake/pydrake_doxygen.h
+++ b/bindings/pydrake/pydrake_doxygen.h
@@ -646,7 +646,8 @@ then logging will not be redirected.
 
 For example, to disable logging redirect, you can set the following in
 your terminal before you run your process that uses pydrake:
-```sh
+
+```
 export PYDRAKE_PYTHON_LOGGING=0
 ```
 
```
```

</blockquote></details>

Done - thanks! (I was able to get it work by only removing `sh`)

___
___
*[`bindings/pydrake/pydrake_doxygen.h` line 641 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NYz-HuxB4enLrgX3A7-:-NZ1t6Mc-9y8XAW5VtYD:b-opq3hi) ([raw file](https://github.com/RobotLocomotion/drake/blob/a8aa4031ecbfffd99125a1f3f406a92350fee31d/bindings/pydrake/pydrake_doxygen.h#L641)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The name is `DRAKE_PYTHON_LOGGING`.

Ditto below.
</blockquote></details>

Done, derp

**Review by jwnimmer-tri — COMMENTED** [review]
Oops, I'd mean to :lgtm:.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-:-NZ26kbJ7nMJeIbJl-_L:b-tc74ce)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
I'll propose +@xuchenhan-tri for platform review, unless you had some other plan.

**Comment by EricCousineau-TRI** [comment]
Yup, works for me - thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with one question.

> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-:-NZ75NFF6uGx7z6EwMRj:b-j6g7ls)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/test/text_logging_test.py` line 158 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NZ74EGODSVaoiTUTFih:-NZ74EGODSVaoiTUTFii:b-901sgb) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae7a482aaf0f57e7ae5ec0595004aead9f95fcc3/bindings/pydrake/common/test/text_logging_test.py#L158)):*
> ```Python
>         env["DRAKE_PYTHON_LOGGING"] = "0"
>         # Configure the Python logging to not print anything.
>         python_level = CRITICAL + 1
> ```

BTW, I'm confused by the contradiction between this comment and my perceived testing strategy: My understanding is that we want to set the python level so that things are logged in python if the environment variable had not been set. Therefore, when the logging doesn't go through to python but instead shows up in the c++ logger, we know that the environment variable has an effect.

If my understanding is correct, shouldn't we configure python logging to print whatever is redirected by c++ logger?



_Code quote:_
```Python
        # Configure the Python logging to not print anything.
        python_level = CRITICAL + 1
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/test/text_logging_test.py` line 158 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NZ74EGODSVaoiTUTFih:-NZ7Si7_6mvMUWtH10HL:bvw7sr1) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae7a482aaf0f57e7ae5ec0595004aead9f95fcc3/bindings/pydrake/common/test/text_logging_test.py#L158)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm confused by the contradiction between this comment and my perceived testing strategy: My understanding is that we want to set the python level so that things are logged in python if the environment variable had not been set. Therefore, when the logging doesn't go through to python but instead shows up in the c++ logger, we know that the environment variable has an effect.

If my understanding is correct, shouldn't we configure python logging to print whatever is redirected by c++ logger?
</blockquote></details>

Here's how I see it.  Maybe you can help us figure out how to better explain it?

(1) We set the env var so that Python logging and C++ logging are independent.
(2) We do not specifically change anything about C++ logging level.
(3) We set the Python logging level to "no logging at all".
(4) The do_log_test function invokes a bunch of C++ log statements.

The test predicate is that the C++ log statements made it out to stderr.

If step (1) didn't happen, then step (3) would mean that no messages would ever appear, so the test predicate would fail (the output would be empty).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/test/text_logging_test.py` line 158 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19685#-NZ74EGODSVaoiTUTFih:-NZ7XuJjDV9oOYyXdR2p:bggs7i) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae7a482aaf0f57e7ae5ec0595004aead9f95fcc3/bindings/pydrake/common/test/text_logging_test.py#L158)):*
I see, that makes sense! Can we just use this as-is for the doc-string? It's abundantly clear.

> (1) We set the env var so that Python logging and C++ logging are independent.  
(2) We do not specifically change anything about C++ logging level.  
(3) We set the Python logging level to "no logging at all".  
(4) The do\_log\_test function invokes a bunch of C++ log statements.
The test predicate is that the C++ log statements made it out to stderr.
If step (1) didn't happen, then step (3) would mean that no messages would ever appear, so the test predicate would fail (the output would be empty).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19685)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Pull request merged**
