### PR TITLE
Add common/pointer_cast utilities

### LINKED ISSUE #8570: Need drake/common utility for base-to-derived unique_ptr downcast
The following pattern occurs often enough to warrant automating: a base class method (e.g. Clone()) returns `unique_ptr<Base>`. A derived class would like to provide a more-specific version of the same method, returning `unique_ptr<Derived>`, by invoking the base class method and then "downcasting" it. We have to verify along the way that the object returned by the Base method actually has the right Derived type, and be sure not to lose ownership in the case that fails.

Here are a couple of examples. 
```c++
// Context<T> derives from ContextBase.
std::unique_ptr<Context<T>> Context<T>::Clone() const {
  std::unique_ptr<ContextBase> clone_base(ContextBase::Clone());
  DRAKE_DEMAND(dynamic_cast<Context<T>*>(clone_base.get()) != nullptr);
  return std::unique_ptr<Context<T>>(
      static_cast<Context<T>*>(clone_base.release()));
}

// System<T> derives from SystemBase.
std::unique_ptr<Context<T>> System<T>::AllocateContext() const {
  std::unique_ptr<ContextBase> context_base(SystemBase::AllocateContext());
  DRAKE_DEMAND(dynamic_cast<Context<T>*>(context_base.get()) != nullptr);
  return std::unique_ptr<Context<T>>(
      static_cast<Context<T>*>(context_base.release()));
}
``` 

A few thoughts:
- Consider whether the aborts() above should instead be throws.
- Are there cases where the static_cast won't produce the same result as the dynamic_cast did? I think that's true for some kinds of multiple inheritance though perhaps the static_cast wouldn't compile.

Suggested by @jwnimmer-tri in PR #8420 who volunteered to accept assignment. From the PR:
> I would love to see this as a helper function in common (unique_ptr_cast) to do this for us, though perhaps that's best as a TODO for now, because the edge cases for a generic routine are brutal (StackOverflow has some tips). Maybe open an issue (you can assign to me)?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #8570.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDgpblC5qyZZgZZxcPj:-LDgpblC5qyZZgZZxcPk:b-7zggae) (no related file):*
Will need platform review.

---

*[tools/install/libdrake/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDgpTQ56JJtzj71jjYg:-LDgpTQ78Y7JkolhbbbD:b-fj4qvr) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/tools/install/libdrake/BUILD.bazel#L1)):*
> ```Python
> # -*- python -*-
> ```

Please ignore changes to this file; they are part of #8892, which will merge first.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889#-:-LDgp_NsB2rxmbuLRPvC:b7dve2f)*

**Comment by rpoyner-tri** [comment]
Review status: 1 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[common/pointer_cast.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDgsMyg4x_6IAeiCF3p:-LDgsMyg4x_6IAeiCF3q:bgbnctj) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/common/pointer_cast.h#L60)):*
> ```objc
>   if (!result) {
>     throw std::logic_error(fmt::format(
>         "Cannot downcast unique_ptr containing {} from {} to {}.",
> ```

Saying "downcast" here (and above) seems like more information than you actually know.  Why not just say "cast" ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[common/BUILD.bazel, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDh-gJMA6YmN7kNEp7f:-LDh-gJNCRHlpjsmB-aT:b5rn17m) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/common/BUILD.bazel#L41)):*
> ```Python
>         ":nice_type_name",
>         ":number_traits",
>         ":pointer_cast",
> ```

BTW Given that this is included in a sizable number of locations in the systems framework, and the functionality looks relatively lightweight, perhaps this could be included into `essential`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by rpoyner-tri** [comment]
Reviewed 13 of 17 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by sherm1** [comment]
Nice! Feature :lgtm: with a few comments.

One related issue we've had TODOs about for ages, is a performance-tweaked dynamic_cast that does an actual dynamic_cast in Debug (or ASSERT_ARMED) but does a static_cast otherwise. I _think_ as we start working on performance we'll find that there are places where the dynamic_casts are too expensive. I'm not suggesting you address that now, but I think it is worth thinking about it briefly to consider whether and how we would extend these utilities to provide that functionality. `debug_dynamic_pointer_cast()`? Use a macro?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/pointer_cast.h, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhgbCx-3olKrntZsqu:-LDhgbCx-3olKrntZsqv:b-s94xsx) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L29)):*
> ```objc
> /// On success, `other`'s managed value is transferred to the result and
> /// `other` is empty; on failure, `other` will retain its original managed
> /// value and the result is empty.
> ```

BTW should mention that if the original is nullptr the result will also be nullptr (so nullptr return doesn't always mean failure).

---

*[common/pointer_cast.h, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhfmtj-lasR0EXOewA:-LDhfmtk5InxY72R7TFq:b-3a3bio) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L36)):*
> ```objc
> /// Note that this function only supports default deleters.
> template <class T, class U>
> std::unique_ptr<T> dynamic_pointer_cast(std::unique_ptr<U>&& other) noexcept {
> ```

BTW why take an rvalue reference here but not in static_pointer_cast?

---

*[common/pointer_cast.h, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhh1OP4sIV6VjGOCRu:-LDhh1OP4sIV6VjGOCRv:b-sdiwh1) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L44)):*
> ```objc
> 
> /// Casts the object owned by the std::unique_ptr `other` from type `U` to `T`;
> /// if `other` is nullptr or the cast fails, throws a std::logic_error.
> ```

BTW consider making this method and dynamic_pointer_cast behave similarly for nullptr (i.e. quietly succeed but return with an empty pointer). That seems more in keeping with dynamic_cast and std::dynamic_pointer_cast.

---

*[common/pointer_cast.h, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhkS6bDb4RKbFNedZm:-LDhkS6bDb4RKbFNedZn:b-vwa6j) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L64)):*
> ```objc
>   if (!result) {
>     throw std::logic_error(fmt::format(
>         "Cannot cast unique_ptr containing {} from {} to {}.",
> ```

BTW consider:
```
Cannot cast a unique_ptr<{U}> containing an object 
of type {other} to unique_ptr<{T}>.
```

---

*[systems/framework/test/diagram_context_test.cc, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhC9EDEb54SFnrTv0x:-LDhC9EDEb54SFnrTv0y:bmv6zse) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/systems/framework/test/diagram_context_test.cc#L275)):*
> ```cpp
> 
>   std::unique_ptr<DiagramContext<double>> clone =
>       dynamic_pointer_cast<DiagramContext<double>>(context_->Clone());
> ```

FYI I'd rather see `auto` here (as we do with make_unique) than a long line with the type repeated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889#-:-LDhi6Dx6ntqgn2aFi9X:b6qhzfi)*

**Comment by jwnimmer-tri** [comment]
Yup.  For that, I would probably keep it a plain function (with some debug-conditioned goop inside), not a macro.  Off the top of my head, I'd name it `debug_checked_static_cast` for bare pointers / references and `debug_checked_static_pointer_cast` for managed pointers.  (I think a long name is correct, because it should be used only after due consideration.)

---

Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/BUILD.bazel, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDh-gJMA6YmN7kNEp7f:-LDhnENJ9WrPIKpDYY9o:bpiperm) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/common/BUILD.bazel#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Given that this is included in a sizable number of locations in the systems framework, and the functionality looks relatively lightweight, perhaps this could be included into `essential`?
</blockquote></details>

I think not, for two reasons.

I think systems/framework will have the preponderance of pointer_cast uses (since it is what does type erasure), and so other code is unlikely to have so many deps changes.  I also think its okay to finely craft dependencies of system/framework since it is such a core piece.

I think we can easily promote pointer_cast to essential anytime, but breaking it out to be separate later is more difficult.  For anything in essential, I'd say we start with it outside, and then after a dozen PRs if we are sick of typing it we can promote it.

---

*[common/pointer_cast.h, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhgbCx-3olKrntZsqu:-LDhqRPWCtfAOMg3WMzy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should mention that if the original is nullptr the result will also be nullptr (so nullptr return doesn't always mean failure).
</blockquote></details>

Done.

---

*[common/pointer_cast.h, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhfmtj-lasR0EXOewA:-LDhsiErCSefwE8oe6u_:b-lujwet) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why take an rvalue reference here but not in static_pointer_cast?
</blockquote></details>

Hmm.  For some reason I had meant the by-value above as "there is no way you are getting this value back, ever" but that doesn't really make sense.  I've changed the static cast to use rvalue ref to match these.  (That matches what, e.g., unique_ptr constructors take.)

---

*[common/pointer_cast.h, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhh1OP4sIV6VjGOCRu:-LDhqWx39JAT8Efr5poj:b-hm5qwj) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider making this method and dynamic_pointer_cast behave similarly for nullptr (i.e. quietly succeed but return with an empty pointer). That seems more in keeping with dynamic_cast and std::dynamic_pointer_cast.
</blockquote></details>

I can see that argument, but in almost all cases in Drake, it seems like we also want to reject nulls, so I figured we might as well put all the sugar together in once convenient place?  I am a little sad that the name doesn't quite highlight that nullptr input means throw, but on the other hand a user will find out pretty quickly, since this is only a stronger guard than they might have expected.

---

*[common/pointer_cast.h, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhkS6bDb4RKbFNedZm:-LDhpR-69amB9avEIvGb:b556ppv) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider:
```
Cannot cast a unique_ptr<{U}> containing an object 
of type {other} to unique_ptr<{T}>.
```
</blockquote></details>

Awesome, thanks.

---

*[systems/framework/test/diagram_context_test.cc, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhC9EDEb54SFnrTv0x:-LDhmznV3uv9jd-cVJcQ:btvyrbc) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/systems/framework/test/diagram_context_test.cc#L275)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI I'd rather see `auto` here (as we do with make_unique) than a long line with the type repeated.
</blockquote></details>

Do we want to assume that the reader knows that `dynamic_pointer_cast` returns a managed pointer?  I think for `make_unique` that's fine to assume, but for our artisinal function it seemed a bit much to expect of a casual reader to have that signature in their brain.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889#-:-LDhmLdK5SZHeLTY4o4h:b-59r1x4)*

**Comment by jwnimmer-tri** [comment]
Review status: 14 of 16 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDgpblC5qyZZgZZxcPj:-LDhteNHBjdp6ARrgU3J:b4mx0my) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Will need platform review.
</blockquote></details>

+@ggould-tri for platform review per schedule, please.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by sherm1** [comment]
I like those debug names (possibly modified per comment below).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/pointer_cast.h, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhh1OP4sIV6VjGOCRu:-LDi5-DM7CR8BKuIwdbc:broflfb) ([raw file](https://github.com/robotlocomotion/drake/blob/a8c66bb14c226abd2ac601f9d334b3bee849f7ff/common/pointer_cast.h#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can see that argument, but in almost all cases in Drake, it seems like we also want to reject nulls, so I figured we might as well put all the sugar together in once convenient place?  I am a little sad that the name doesn't quite highlight that nullptr input means throw, but on the other hand a user will find out pretty quickly, since this is only a stronger guard than they might have expected.
</blockquote></details>

Good point -- I buy that!

---

*[systems/framework/test/diagram_context_test.cc, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhC9EDEb54SFnrTv0x:-LDi5N387d-L26Byyv0T:b-ajns8j) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/systems/framework/test/diagram_context_test.cc#L275)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do we want to assume that the reader knows that `dynamic_pointer_cast` returns a managed pointer?  I think for `make_unique` that's fine to assume, but for our artisinal function it seemed a bit much to expect of a casual reader to have that signature in their brain.
</blockquote></details>

Hmmm ... I'd like to avoid the repetition. One possibility would be to swipe make_unique's naming scheme rather than overload the shared pointer utilities. What do you think about `dynamic_cast_unique` etc. rather than "pointer"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889#-:-LDi6Hfu1O3phrpdOdc-:b-1vkeod)*

**Comment by jwnimmer-tri** [comment]
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/test/diagram_context_test.cc, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8889#-LDhC9EDEb54SFnrTv0x:-LDi8N943VWwXeJgUIrc:b-qbzk8f) ([raw file](https://github.com/robotlocomotion/drake/blob/14ee180fc6237ebc60b236f026511fbcf1ea0f32/systems/framework/test/diagram_context_test.cc#L275)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Hmmm ... I'd like to avoid the repetition. One possibility would be to swipe make_unique's naming scheme rather than overload the shared pointer utilities. What do you think about `dynamic_cast_unique` etc. rather than "pointer"?
</blockquote></details>

Done.  I can live with `auto` here.  I think the names are good as-is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8889#-:-LDl1RR4Ce_ziSVOAJDc:bnfp4nl)*

**Pull request merged**
