### PR TITLE
[hydro, multibody] Add public API to choose triangles or polygons.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #15796

- Add C++ API get/set_contact_surface_representation().
- Update MultibodyPlantConfig
- Add python bindings
- Add tests for above

co-authored by: DamrongGuoy

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@damrongguoy for feature review.
+(release notes: yes)  combine into hydro one-liner

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr4Pc7fBZuUzOJBFAiL:b-q8qcly)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you. I close the draft PR #16228 now. We'll work on this 16238 instead.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr4ZwXUBnIzzC9aUSHX:b-q19k9c)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
CC: @amcastro-tri 

> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr4xvWq1d7r4ZS9ugjl:b949cmd)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr8Xuw_-Q5e1eXFOluo:bnfp4nl)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[multibody/plant/multibody_plant_config_functions.cc, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8G5uuD-S0aG-8yB6M:-Mr8G5uuD-S0aG-8yB6N:b-el1jlu) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L60)):*
> ```cpp
> // Use a switch() statement here, to ensure the compiler sends us a reminder
> // when somebody add a new value to the enum. New values must be listed here
> // as well as in the list of kReps below.
> ```

It took me a while to understand what `kReps` here meant. How about saying more like this?

```
as well as in the Rep-to-string table `kReps` below. 
```
___
*[multibody/plant/multibody_plant_config_functions.cc, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8QNRs3w3IHHgwYDO8:-Mr8QNRs3w3IHHgwYDO9:b-ulm1tn) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L74)):*
> ```cpp
> }
> 
> constexpr std::array<std::pair<Rep, const char*>, 2> kReps{{
> ```

Consider `kContactReps` to be consistent with the existing `kContactModels`?
___
*[multibody/plant/multibody_plant_config_functions.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8M-PKCX1KlMeeWf9V:-Mr8M-PKCX1KlMeeWf9W:b-deett9) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L77)):*
> ```cpp
>   MakeRepPair(Rep::kTriangle),
>   MakeRepPair(Rep::kPolygon),
> }};
> ```

Would `std::map<Rep, const char*> kReps` work? Or looking up `array` is faster than `map` because there're only two entires. (O(n^2) bubble-sort is faster than O(n log n) quicksort for a very small list.)

I also see the same pattern for ContactModel, so I think we should keep it as `array` for consistency.

No need to change anything. I'm just curious.
___
*[multibody/plant/multibody_plant_config_functions.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8O7z_EsSH4pm7tuTi:-Mr8O7z_EsSH4pm7tuTj:bmif0p8) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L120)):*
> ```cpp
>   }
>   DRAKE_UNREACHABLE();
> }
> ```

Can we use `RepToChars` directly?
```
std::string GetStringFromContactSurfaceRepresentation(
    Rep contact_representation) {
  return RepToChars(contact_representation);
}
```
On the other hand, I see this pattern was already used for `GetStringFromContactModel()`, so there might be good reasons that I didn't know.
___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8Sqp46tGmq76AWrZR:-Mr8Sqp5ERTWFV3-brdt:bjpiag3) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/test/multibody_plant_config_functions_test.cc#L72)):*
> ```cpp
> }
> 
> GTEST_TEST(MultibodyPlantConfigFunctionsTest, ContactRepTest) {
> ```

`ContactRepresentationTest`?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[multibody/plant/multibody_plant_config_functions.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8M-PKCX1KlMeeWf9V:-Mr8cUrg83SwW8pgAKEi:bpsdpy3) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L77)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Would `std::map<Rep, const char*> kReps` work? Or looking up `array` is faster than `map` because there're only two entires. (O(n^2) bubble-sort is faster than O(n log n) quicksort for a very small list.)

I also see the same pattern for ContactModel, so I think we should keep it as `array` for consistency.

No need to change anything. I'm just curious.
</blockquote></details>

std:map<> would work, but it's a mountain of  memory allocation and pointer chasing for such a small data structure.

There are a few things to notice here:

* the array of pairs is entirely `constexpr` -- it's all constructed a compile time.
* since we support lookups in both directions (enum --> str, str --> enum), a single `std::map` would be bad at one of those directions.
* for such small N, linear searches that fit in cache are probably way faster than any data structure with cache misses.
___
*[multibody/plant/multibody_plant_config_functions.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8O7z_EsSH4pm7tuTi:-Mr8dqsS6RWTIYXpCsNq:b9j1qnz) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L120)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Can we use `RepToChars` directly?
```
std::string GetStringFromContactSurfaceRepresentation(
    Rep contact_representation) {
  return RepToChars(contact_representation);
}
```
On the other hand, I see this pattern was already used for `GetStringFromContactModel()`, so there might be good reasons that I didn't know.
</blockquote></details>

RepToChars is undefined (for good reason) if the argument happens to be one we haven't supported. The good reason is that there really isn't an easy/compatible way to throw or abort from a `constexpr` function.  We "know" that RepToChars is total because the compiler checks the switch statement and gives errors if branches are missing. However, that is no defense against either clever or inadvertent means of inserting a wrong value in the argument at runtime.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[multibody/plant/multibody_plant.h, line 1624 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8i6zMBW54bRKqwYQz:-Mr8i6zN2H5SmX__M3yq:b-dizvcu) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.h#L1624)):*
> ```objc
>   /// Sets the representation of contact surfaces to be used by `this`
>   /// %MultibodyPlant for discrete systems only. Continuous systems ignore this
>   /// setting.
> ```

minor, probably worth mentioning here the default for continuous systems if not something a user can set?
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr8icB_2Y2QpHSEuBXE:b9x6133) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
> ```cpp
>           get_contact_surface_representation(), &data->contact_surfaces,
>           &data->point_pairs);
>     } else {  // Continuous system has only one choice: kTriangle.
> ```

we taught the HydroelasticTractionCalculator how to work with the polygonal representation, why is it that we cannot let the user choose here? Maybe add TODO explaining what the blocker is?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr8jJDk3Wmy8nOejiPy:b-yi9atm) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we taught the HydroelasticTractionCalculator how to work with the polygonal representation, why is it that we cannot let the user choose here? Maybe add TODO explaining what the blocker is?
</blockquote></details>

specifically in #16175,  not sure why we are not making sure of this feature. Blame changes on ComputeSpatialForcesAtCentroidFromHydroelasticModel() to see the update to work with the polygonal representation.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri, @DamrongGuoy, and @rpoyner-tri)

___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr8kWuD42heAbkYeMQ9:brz5ogm) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

specifically in #16175,  not sure why we are not making sure of this feature. Blame changes on ComputeSpatialForcesAtCentroidFromHydroelasticModel() to see the update to work with the polygonal representation.
</blockquote></details>

I was unaware that continuous support for polygons was ready. Let me try it and see.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @rpoyner-tri)

___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr8l1hY5TTsr33NxBj1:bhj88by) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I was unaware that continuous support for polygons was ready. Let me try it and see.
</blockquote></details>

I didn't know that either, despite reviewing #16175 before. It would be nice to have the polygon/triangle for both continuous/discrete.

I thought Continuous System would need multiple quadrature points per polygon through barycentric coordinates, which we do not support for polygons.

Does this mean Continuous System now uses only one quadrature point at the centroid of the polygon?  Is it also using only one quadrature point at the centroid of the triangle too? (I thought it has been using three quadrature points per triangle.)
___
*[multibody/plant/multibody_plant_config_functions.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8M-PKCX1KlMeeWf9V:-Mr8laiK0nzBjqFjPozz:b-9755fn) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L77)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

std:map<> would work, but it's a mountain of  memory allocation and pointer chasing for such a small data structure.

There are a few things to notice here:

* the array of pairs is entirely `constexpr` -- it's all constructed a compile time.
* since we support lookups in both directions (enum --> str, str --> enum), a single `std::map` would be bad at one of those directions.
* for such small N, linear searches that fit in cache are probably way faster than any data structure with cache misses.
</blockquote></details>

Thank you!
___
*[multibody/plant/multibody_plant_config_functions.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8O7z_EsSH4pm7tuTi:-Mr8lsU_1uNqM2TvEosG:b-o2rbey) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant_config_functions.cc#L120)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

RepToChars is undefined (for good reason) if the argument happens to be one we haven't supported. The good reason is that there really isn't an easy/compatible way to throw or abort from a `constexpr` function.  We "know" that RepToChars is total because the compiler checks the switch statement and gives errors if branches are missing. However, that is no defense against either clever or inadvertent means of inserting a wrong value in the argument at runtime.
</blockquote></details>

I see. You meant if an adversary/hacker passes an unsupported value to `Rep contact_representation`, then we want to throw, which is impossible in `constexpr` function.  The `throw` is run-time.  The `constexpr` is compile-time.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @DamrongGuoy)

___
*[multibody/plant/multibody_plant.h, line 1624 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8i6zMBW54bRKqwYQz:-Mr92XBWCGlh7NcOyQ43:b-g60cfq) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.h#L1624)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, probably worth mentioning here the default for continuous systems if not something a user can set?
</blockquote></details>

I went the whole way and supported continuous system configuration fully. Whether continuous/poly results make sense (I will claim) is beyond the scope of this PR. 
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr92qXu5aV4Hcj6RGqE:b-s0fi9a) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I didn't know that either, despite reviewing #16175 before. It would be nice to have the polygon/triangle for both continuous/discrete.

I thought Continuous System would need multiple quadrature points per polygon through barycentric coordinates, which we do not support for polygons.

Does this mean Continuous System now uses only one quadrature point at the centroid of the polygon?  Is it also using only one quadrature point at the centroid of the triangle too? (I thought it has been using three quadrature points per triangle.)
</blockquote></details>

As noted above, this now supports fully arbitrary {continuous, discrete}/{triangle, poly} configurations, with the appropriate default policy. Whether some or all of those give bogus integration results is beyond the scope of this PR, and can be fixed separately if needed. It is my belief that the defaults (continuous/triangle, discrete/poly) do work correctly.

**Review by rpoyner-tri — COMMENTED** [review]
Comments addressed.
+@ggould-tri  for platform review, Monday schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr93tu9DTyBTAIWo0W0:b5fh9io)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @amcastro-tri, @DamrongGuoy, and @ggould-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @DamrongGuoy and @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238#-:-Mr9GRBNCGKshtOOh1Xd:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),DamrongGuoy (waiting on @rpoyner-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16238)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),DamrongGuoy

___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr9GK_G1S4hs49oUJE1:b-yqif5q) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

As noted above, this now supports fully arbitrary {continuous, discrete}/{triangle, poly} configurations, with the appropriate default policy. Whether some or all of those give bogus integration results is beyond the scope of this PR, and can be fixed separately if needed. It is my belief that the defaults (continuous/triangle, discrete/poly) do work correctly.
</blockquote></details>

Very nice. I believe the hydroelastic calculator is properly unit tested. So for  this PR to be complte we'd need to unit test the wiring of individual components is correct?
E.g. we could parameterize fixture `HydroelasticModelTests` in `multibody_plan_hydroelastic_test.cc ` with the representation and test that accelerations are correct (as in HydroelasticModelTests__ContactDynamics). Though this could be a separate PR

**Comment by rpoyner-tri** [comment]
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr9HP1iAbGJj3_F7VZG:b6i1s3v) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Very nice. I believe the hydroelastic calculator is properly unit tested. So for  this PR to be complte we'd need to unit test the wiring of individual components is correct?
E.g. we could parameterize fixture `HydroelasticModelTests` in `multibody_plan_hydroelastic_test.cc ` with the representation and test that accelerations are correct (as in HydroelasticModelTests__ContactDynamics). Though this could be a separate PR 
</blockquote></details>

Yes, something like that. @damrongguoy , do you think that is worth doing?

**Comment by DamrongGuoy** [comment]
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr9NuGC97a06btEtHE4:b-95d5h8) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Yes, something like that. @damrongguoy , do you think that is worth doing?
</blockquote></details>

Sorry for late reply.  I think it would be nice if @amcastro-tri will work on that kind of unit tests.

@amcastro-tri, please let me know the new PR number if you do it.

**Comment by DamrongGuoy** [comment]
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr9TEj_4Iz4SGk-5tOI:ba04e33) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Sorry for late reply.  I think it would be nice if @amcastro-tri will work on that kind of unit tests.

@amcastro-tri, please let me know the new PR number if you do it.
</blockquote></details>

I did find an example that crashed when we use Continuous System, hydroelastics, and kPolygon contact surfaces. I'll create an issue for everybody to look at. Stay tuned.

**Comment by DamrongGuoy** [comment]
___
*[multibody/plant/multibody_plant.cc, line 2016 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16238#-Mr8icB_2Y2QpHSEuBXD:-Mr9ZEfgCqwFS4-KfKNT:b-zgq5hc) ([raw file](https://github.com/robotlocomotion/drake/blob/4955578712df7c8f8cc39ae69993ae919d6db5b5/multibody/plant/multibody_plant.cc#L2016)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I did find an example that crashed when we use Continuous System, hydroelastics, and kPolygon contact surfaces. I'll create an issue for everybody to look at. Stay tuned.
</blockquote></details>

#16244 PTAL

**Pull request merged**
