### PR TITLE
manipulation: Check for whole default message, not just utime==0

### LINKED ISSUE #9859: using utime==0 as the check for lcm message arrivals
@sammy-tri -- when I feature reviewed the lines like:
https://github.com/RobotLocomotion/drake/blob/master/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L44
(and the repeat logic a few lines below) a few days ago, I thought it was ok (thinking that properly initialized utime is always >> 0).  Now I'm questioning that decision.

When sending lcm traffic from sim to sim, we get utime=0 at context.get_time()==0.  Which means the initial_position inputs will take precedence over any actual data published at time 0.  Was that your intention?  I can't immediately think of a better solution, but it feels sub-optimal.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #9859

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13311)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
This is an incredibly naive first attempt (that will fail, hopefully?).
Ultimately, the goal is to check "did I get something", so it's basically looking for a default-constructed LCM message. Alternatives:

    Pipe in receive message count. (Yuck, more ports.)
    Check the whole message (utime, joints, torques, etc.)

Will see how this fails, then try out Option 2.

**Comment by jwnimmer-tri** [comment]
The most recent consensus in the issue was that these message decoders should just lose their "default value" semantics, and so nuke the if-guards in their Calc methods.  Would that solve your problem? If so, why not use that approach? If not, what are the problems of that solution?

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri This solution solves the underlying issue of "a valid message with utime == 0 is ignored", and is simple as dirt (no downstream changes, self-contained).

Removing `if` guards in the systems and coordinating that with upstream ports sound like more pain than I would like to experience atm (coordinating the "default value" semantics and ensuring they somehow encode the initial positions to hold that position from the controlletr, etc).

I happy to replace "Resolves <issue>" with "Towards <issue>" if that makes you happier?

**Comment by jwnimmer-tri** [comment]
The problems with this PR are that
(1) it reinforces the wrong approach -- that users should be expected to rely on messages scooting through or not, and sometimes having defaults or not;
(2) the (0,0,0) wsg message is semantically valid and should is not a durable sentinel

The first step along the correct solution is actually easy -- offer a new zero-argument constructor (with no defaults).  When the user calls that constructor, the Calc methods don't have any if-checks and simply pass through the input to the output.  That's what we want eventually, solves your problem, and doesn't involved any additional deprecation headaches.  Or am I missing something?

**Comment by jwnimmer-tri** [comment]
Hm, that's the right intent for the solution but I wrote it out incorrectly.

For Iiwa and Jaco the defaults come from a setter, not from the constructor.  So if nobody ever calls the setter, don't check the utime.

For the Schunk, it does involve some constructor shuffling and deprecation, but it's still super easy.

**Comment by EricCousineau-TRI** [comment]
While your faults are true, I would say this PR is still *strictly* better; I would prefer to not defer on this change.
As far as the "better solution", I'm happy to get out of the way after this lands?

**Comment by EricCousineau-TRI** [comment]
> No, it's not strictly better because it adds dozens of lines of code [...]

I disagree? It's not that many lines of code, and it would have prevented me from spending more than 3 hours chasing this issue down.

**Comment by jwnimmer-tri** [comment]
> It's not that many lines of code, ...

Well, you haven't actually added any tests that represent your use case yet, so it's going to grow.

> ... prevented me from spending more than 3 hours chasing this issue down.

I'm not saying the issue isn't important.  I'm saying that if its important enough to fix, it's important enough to do it correctly rather that the exact opposite of correctly.

**Comment by EricCousineau-TRI** [comment]
> Well, you haven't actually added any tests that represent your use case yet [...]

Happy to address that!

> [...] I'm saying that if its important enough to fix, it's important enough to do it correctly rather that the exact opposite of correctly.

I don't disagree with the whole statement, but I don't agree with the whole statement either. For that reason, I've scoped this down to "Towards", not "Resolves".

**Comment by jwnimmer-tri** [comment]
The PR has shrunk considerably in recent pusheds, so the "worse because of extra baggage" complaint is less now.

The only problem now is that `IsDefaultValueInitializedMessage` is brittle and copypasta -- messages definitions can change, and it promotes a bad pattern and hits rule-of-three.

It's easy to write a helper function to compare two lcm message for equality -- just serialize them and memcmp their bytestrings.  (We might have this lying around already.)  Or alternatively, a helper to compare a message to its default value (using the same bytestream technique.)

With that change, this PR is probably narrow enough to squeak by as small enough to stomach.

**Comment by EricCousineau-TRI** [comment]
SGTM! Starting that now.

**Comment by EricCousineau-TRI** [comment]
Will rebase on latest master, then force-merge.

**Comment by EricCousineau-TRI** [comment]
Rebased, merging.

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri To follow-up, not sure I if I did this right; I was expecting a fast-forward, but I guess GitHub still makes the merge commit:
```sh
$ git log --graph --oneline --no-decorate -n 4 2f435b4778
*   2f435b4778 Merge pull request #13311 from EricCousineau-TRI/issue-9859
|\  
| * 9c077197d5 manipulation: Check for whole default message, not just utime==0
| * 7fc64729ac lcm: Add lcm_messages target
|/  
* 99aa8349b0 autodiffutils_test: Use numpy version check for error message (#13318)
```

Was there something else I should've done to preserve curated commits, but with linear history?

**Comment by jwnimmer-tri** [comment]
Nope, that's as good as we ever get.  Maybe "linear" was not the right term, I think what I actually have in mind is "there exists a total ordering of all commits".  Looks the same in gitk as other recent merges:

image

**Pull request merged**
