### PR TITLE
Create a minimal rendering example for RenderEngineVtk

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@seancurtis-tri  for review, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145#-:-MpYe71L4WwzZPClFc_G:b-40oce8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpggSl54qp4gbP3unpq:-MpggSl54qp4gbP3unpr:bcab0pl) (no related file):*
The one major thing I would suggest is an enumeration of what this *still* needs to do. Some weeks ago, we sat down and discussed all of the various things that such an example should do (to fully exercise the current API). To my best understanding you made note of that in some google documents. That list should go into a big comment in this file so it serves as a local checklist that can easily be resolved.

---
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-Mpgeona28irUcrKQaSH:-Mpgeona28irUcrKQaSI:b-9b22zg) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L38)):*
> ```cpp
> 
> using Eigen::Vector3d;
> using geometry::DrakeVisualizerd;
> ```

nit: All of the aliases starting with `geometry::` are redundant. This code is already part of the `drake::geometry::render` namespace.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpgfZTx0s-qEDHDmuwm:-MpgfZTx0s-qEDHDmuwn:bgfe6s4) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L61)):*
> ```cpp
>   // Declare builder, plant, and scene_graph.
>   systems::DiagramBuilder<double> builder;
>   MultibodyPlant<double>* plant = nullptr;
> ```

BTW Generally, the dependency on MBP here provides little value. You've welded everything to the world frame, so there are no meaningful dynamics (or movement) taking place. However, eventually, we want to make sure that the new render engine implementation handles moving objects correctly, so we'll eventually need *some* mechanism that is responsible for moving objects. For that reason, I'm content to leave MBP and the dependency in place.

If this proves particularly problematic in the future, we can address this.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpgfIXe7NFPta3iqI3O:-MpgfIXe7NFPta3iqI3P:bh6oo5q) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L87)):*
> ```cpp
>       X_WCrackerBox);
> 
>   const auto sugar_box = parser.AddModelFromFile(
> ```

nit: After the first sdf, I don't believe the next three sdfs provide any real value. They're all simply textured meshes. I'm willing to stipulate that if one works, they'll all work. Probably worth removing the next three.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpggSl54qp4gbP3unpq:-MpkVHRj-ikHnqYdSD3r:baz6201) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The one major thing I would suggest is an enumeration of what this *still* needs to do. Some weeks ago, we sat down and discussed all of the various things that such an example should do (to fully exercise the current API). To my best understanding you made note of that in some google documents. That list should go into a big comment in this file so it serves as a local checklist that can easily be resolved.
</blockquote></details>

Comments addressed. PTAL.

---
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpkVAQvESoDKBw3Lj4B):*
Will squash the commit after the review.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-Mpgeona28irUcrKQaSH:-MpkUqGe7hhHCt5TIdsK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: All of the aliases starting with `geometry::` are redundant. This code is already part of the `drake::geometry::render` namespace.
</blockquote></details>

Done.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpgfZTx0s-qEDHDmuwm:-MpkUtXw7MDBeLyYTXDy:bj1thyg) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L61)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Generally, the dependency on MBP here provides little value. You've welded everything to the world frame, so there are no meaningful dynamics (or movement) taking place. However, eventually, we want to make sure that the new render engine implementation handles moving objects correctly, so we'll eventually need *some* mechanism that is responsible for moving objects. For that reason, I'm content to leave MBP and the dependency in place.

If this proves particularly problematic in the future, we can address this.
</blockquote></details>

OK. Will leave it as is for now.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpgfIXe7NFPta3iqI3O:-MpkV2QyEiUE97hhVF7Y:bumlhkq) ([raw file](https://github.com/robotlocomotion/drake/blob/207e13e08ef2616fce22e5038d734715ccca66cb/geometry/render/dev/render_engine_vtk_minimal_example.cc#L87)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: After the first sdf, I don't believe the next three sdfs provide any real value. They're all simply textured meshes. I'm willing to stipulate that if one works, they'll all work. Probably worth removing the next three.
</blockquote></details>

Done. Remove all the other models except one.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpkUaoD6hir_VT_QDXP:-MpkUaoE1IlNW-6anI2s:b-bw8ytp) ([raw file](https://github.com/robotlocomotion/drake/blob/072b173df2e80578c6357ad6ed5c7135cd4ce5b0/geometry/render/dev/render_engine_vtk_minimal_example.cc#L37)):*
> ```cpp
> namespace {
> 
> /** This example serves as the baseline demonstration of all the features
> ```

I imagine there will be some back and forth about the list and the wording, but this is my first attempt to summarize what we have discussed.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MplMI3XDd6x0LikSOTn:-MplMI3XDd6x0LikSOTo:bswhruo) ([raw file](https://github.com/robotlocomotion/drake/blob/072b173df2e80578c6357ad6ed5c7135cd4ce5b0/geometry/render/dev/BUILD.bazel#L11)):*
> ```Starlark
> load("//tools/skylark:test_tags.bzl", "vtk_test_tags")
> 
> package(default_visibility = ["//visibility:public"])
> ```

nit `dev` folders should not have `public` visibility.  Most likely `private` is the best choice for this.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @zachfang)

___
*[geometry/render/dev/BUILD.bazel, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MplMI3XDd6x0LikSOTn:-Mpmo28S8w-Edbx9l9Tl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/072b173df2e80578c6357ad6ed5c7135cd4ce5b0/geometry/render/dev/BUILD.bazel#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `dev` folders should not have `public` visibility.  Most likely `private` is the best choice for this.
</blockquote></details>

Done.
___
*[geometry/render/dev/render_engine_vtk_minimal_example.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16145#-MpkUaoD6hir_VT_QDXP:-Mpmo40SEbgWxbaPzn9V:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/072b173df2e80578c6357ad6ed5c7135cd4ce5b0/geometry/render/dev/render_engine_vtk_minimal_example.cc#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd swap your list with this list. I wanted to clarify some of the text here.

```
   - Render each supported shape type (see shape_specification.h)
     - Once with arbitrary RGBA color (unique for each object)
     - Once with diffuse texture
       - textures should have asymmetric features so that the application of
         the texture is clearly correct -- not flipped, rotated, etc.
   - Mesh texture specified in two different ways
     - obj/png file name replacement
     - specified in PerceptionProperties (this is the *only* mechanism for
       applying a diffuse texture to other shapes).
    - Camera functionality
     - Exercise full intrinsic and extrinsic properties. Two separate cameras
       would be sufficient.
    - Moving objects (showing object pose updated -- this should include
      translation and rotation).
    - Clipping range across all output image types
      - make sure there are objects at the limits of the clipping range that
        will get clipped (such that the image would be different if they
        weren't clipped).
    - Depth range
      - Similar to clipping range -- make sure we have objects near the limits
        of the depth range such that if the depth range were incorrect, we'd
        produce a different image.
    - render labels
      - Exercise all five types of labels (empty, don't care, don't render,
        unspecified, user-defined)
    - (optional) Confirm that occluding *transparent* objects are rendered the
      same. 
```
</blockquote></details>

Done. PTAL.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145#-:-MprXjyECkLuxpecrfOP:bmxilld)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> Dismissed @zachfang from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145#-:-MprXtUu6fBbgcj4JAG1:bm9o57a)* status: missing label for release notes (waiting on @zachfang)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16145#-:-MprXwSQ7bDUi6KAN0aG:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform), exempt from platform review (waiting on @zachfang)

**Pull request merged**
