### PR TITLE
ELF strict linking

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Turn on ELF hidden visibility by default, and turn on link flags to disallow unresolved symbols. Among other advantages¹, this makes the behavior on other platforms closer to that of Windows, which can help catch link problems when developing on other platforms (as opposed to them showing up for the first time in a Windows build).

(¹ https://gcc.gnu.org/wiki/Visibility)

Implements #3059.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3065)

### CODE REVIEW

**Comment by david-german-tri** [comment]
I circulated this idea within TRI today.  The consensus is that it might be worthwhile if there is really no divergence between the gcc/clang behavior and the MSVC behavior.  One-off platform-specific hacks scattered around the code would not be a good outcome.  That will be easier to judge once you've resolved the failures that CI caught.

Also, the zlib license makes it tricky to modify tinyxml2. +@jwnimmer-tri, who has done the most thinking about that issue.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOMCBppIQyaWFlRcl5c:-1616399751)*

**Comment by sherm1** [comment]
Zlib is one of the most [open licenses](https://opensource.org/licenses/Zlib) in existence -- comparable to BSD. If that creates any impediments for us, we are doing something wrong!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOMPimrihjr0YLIFYLu:-279811948)*

**Comment by david-german-tri** [comment]
I guess we'd have to ensure our alteration is "plainly marked", whatever that means.  I could be misremembering or misrepresenting Jeremy's concern.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOMksu29zPr2FpgMfUD:1914044895)*

**Comment by sherm1** [comment]
A comment like
```c++
// TRI added this line to make sure this symbol is visible.
```
or, at the top of the file:
```c++
// TRI has mercilessly hacked this code so it should not be mistaken for the original tinyxml2.
// Anything good here comes from tinyxml2, flaws are TRI's fault.
```
or anything else reasonable would be sufficient. We aren't trying to get away with anything and are using the code exactly as its authors were hoping when they chose such a permissive license. It would be frustrating for them if their choice of  the *most permissive license possible* still stopped us from making good use of their software. I know this because I have been on the producing end of open source for a long time and it is very frustrating to try to license the code so that people will actually feel comfortable using it!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOMvc0mmfdZ_MwiLuzi:142679263)*

**Comment by david-german-tri** [comment]
Seems reasonable to me.  I didn't mean to suggest licensing made this change impossible; I just want to make sure it gets addressed.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KON2iwS7M1WKwEXtlIF:-1093229265)*

**Comment by mwoehlke-kitware** [comment]
>  One-off platform-specific hacks scattered around the code would not be a good outcome.

I'm not sure I understand this? ELF symbol visibility is not a hack, nor "platform specific" (no more than `__declspec(dllexport)` anyway). Correct definitions of export symbols is not a hack. What exactly is the problem?

> ...the failures that CI caught

Ooh, bugs! :yum: Previously existing, latent, and uncovered by this PR bugs, I mean; at least that's my initial take. Certainly, let's fix those in this PR... looks like `--no-undefined` is doing its job, though :grin:.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOPnTA8zdMFQWaIpqvY:b-13uuof)*

**Comment by mwoehlke-kitware** [comment]
Can someone familiar with (and who has access to) gurobi take a look at the link errors? It looks like `drakeQPCommon` is missing a link to something gurobi-related, but my naïve attempt to fix it apparently didn't work...

**Comment by jwnimmer-tri** [comment]
FTR -- The `tinyxml2` (zlip) approach taken here looks good to me.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOeNby-eJWmDB8M6_Wq:b-z5gote)*

**Comment by david-german-tri** [comment]
> Can someone familiar with (and who has access to) gurobi take a look at the link errors? It looks like drakeQPCommon is missing a link to something gurobi-related, but my naïve attempt to fix it apparently didn't work.

That's pretty weird, since you have the `-lgurobi60` flag.  @naveenoid, @sammy-tri, does this ring any bells for you?

https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=71512

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOed_ElaJJsqxaDLYOx:b-zdye1g)*

**Comment by mwoehlke-kitware** [comment]
FYI I've also [pinged upstream](https://github.com/leethomason/tinyxml2/issues/461) about this. Hopefully at some point we'll be able to slurp in a newer upstream that fixes the issue "the right way" without running afoul of distributing a modified copy.

**Comment by mwoehlke-kitware** [comment]
Oh, bother... on closer inspection, at least some of the problems are symbols from `drakeQP`... which aren't export decorated... I can try to muddle through fixing that, but I'm not sure I can test other than submitting to CI. (Is Kitware licensed to use gurobi? If yes, what if anything do I need to do to get access?)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOegOjx2n5BP-Um01ac:b-qt8k2m)*

**Comment by david-german-tri** [comment]
Yeah, and ditto `drakeYAMLUtil`.  I suppose we got away with this previously because we don't test Gurobi on Windows.

https://github.com/RobotLocomotion/drake-ci/blob/master/ctest_driver_script.cmake#L771

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOekd1-U7dOMGVN12FL:b1mdu4s)*

**Comment by david-german-tri** [comment]
> I'm not sure I can test other than submitting to CI. (Is Kitware licensed to use gurobi? If yes, what if anything do I need to do to get access?)

We don't have licenses at TRI yet, and all I know about the license terms is that they're restrictive and incredibly expensive.  My guess is that testing on CI is the best option you have.  :-/

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOelPi7nJ7XdIbCfdkc:b1upmww)*

**Comment by mwoehlke-kitware** [comment]
Okay, I think I fixed at least one batch of missing export decorations. (And, yeah, this code would be broken on Windows if it was being built there. So both `--no-undefined` *and* hidden-visibility-by-default are doing their jobs :tada: :grin:)

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOenOaHZyDBS4x_bMuC:b-5b37e8)*

**Comment by david-german-tri** [comment]
Windows build failures appear genuine

---

Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOevgUnF7gfVEV4rBkL:b-mcgpt9)*

**Comment by mwoehlke-kitware** [comment]
> Windows build failures appear genuine

Ack... when I was copy/pasting export symbols, I missed the space after... I caught some of them pre-commit, but missed one :blush:.

---

Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOf7emibMdl3kPWTvvK:bvfhoxl)*

**Comment by mwoehlke-kitware** [comment]
Well... fun. The matlab errors don't look like this PR caused them(?), and the cpplint errors are bogus. I should be able to suppress the latter, at least.

**Comment by david-german-tri** [comment]
> The (remaining) matlab errors don't look like this PR caused them(?)

I don't know the mechanism, but I suspect this PR is at fault somehow just because `linux-gcc-continuous-matlab-release` is clean:

https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-matlab-release/

**Comment by mwoehlke-kitware** [comment]
> I suspect this PR is at fault somehow

I don't understand how that could be, unless the code generation differs somehow. The build flags for that file are the same in both builds (besides the expected `-fvisibility` bits, which shouldn't be causing a difference in code warnings).

I don't see how anything in the PR should be affecting swig code generation?

**Comment by david-german-tri** [comment]
This could be a red herring, but it looks to me like the following step happens in this PR, but not at HEAD.

```
Preprocessing /home/ubuntu/workspace/experi/home/ubuntu/workspace/experimental/06107e1d/drake/build/bindings/matlab/autodiffutils_matlabMATLAB_wrap.cxx
```

**Comment by david-german-tri** [comment]
I can repro the problem locally with this patch.  I can also confirm that the generated code in `build/drake/bindings/matlab/autodiffutils_matlabMATLAB_wrap.cxx` is identical with or without this patch.  Which leads me to suspect this PR turned on `-Werror=maybe-uninitialized` for that file when it was previously off.

**Comment by mwoehlke-kitware** [comment]
@david-german-tri, can you send me a copy of `autodiffutils_matlabMATLAB_wrap.cxx`? I'm going to maybe try to fix the code generation, since I can't think of what else to do... (If it's going to be inconvenient, let me know; I can spin up an AWS instance to play on instead.)

**Comment by david-german-tri** [comment]
https://gist.github.com/david-german-tri/2d11646fac0b17262af99a3a0289a84e

**Comment by david-german-tri** [comment]
However, even if SWIG generation can be fixed, I think the change in build behavior needs to be identified and explained before we can merge this PR.

**Comment by mwoehlke-kitware** [comment]
> I think the change in build behavior needs to be identified and explained

Um... you know, I think I might know what's going on, actually...

If you recall, one of the benefits of hidden visibility is it allows the compiler to optimize better. Specifically, I bet because the compiler (newly) knows that `SWIG_Matlab_NewPointer` can't be called externally, it is being inlined in the build of this PR, where currently it is not inlined. As a result, the compiler is able to reason "better" about whether or not `swig_ptr` is initialized...

If you have a working local build, I think you can test this by adding `inline static` to the definition of `SWIG_Matlab_NewPointer` and rebuilding it. If that triggers the same error, I'll be sufficiently convinced that the above explanation is correct.

This also makes me wonder if SWIG generated code is missing ABI export decoration...

**Comment by david-german-tri** [comment]
> If you have a working local build, I think you can test this by adding inline static to the definition of SWIG_Matlab_NewPointer and rebuilding it. If that triggers the same error, I'll be sufficiently convinced that the above explanation is correct.

Confirmed, that reproduces the error.

**Comment by mwoehlke-kitware** [comment]
Thanks, @david-german-tri... looking at the code it looks like a legitimate warning (which is a little scary), and I'm fairly confident that the optimization enabled by `-fvisibility=hidden` (see previous explanation) is why it's newly popping up. That being the case, I'll look into fixing swig.

**Comment by jwnimmer-tri** [comment]
The line 922 `swig_ptr` warning is a false positive.  Why not just suppress (even more) warnings on swig-generated code?  We already suppress several.

**Comment by mwoehlke-kitware** [comment]
jaeandersson/swig#73
rdeits/swig-matlab-pod#2

@jwnimmer-tri, I'm not sure I agree it is a false positive? `swig_ptr` may not be initialized, and I don't see that `mexErrMsgIdAndTxt` is something which (at least to the compiler's knowledge) causes the caller to cease execution. AFAICT the compiler is correct to issue the warning.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 3 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOkrscbcV4GaH4QgbaZ:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm_cancel:  looks like there were other MATLAB build failures hidden behind that one?

---

Review status: 3 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOks9VovtG7aWJu0eUs:b-ctr5bk)*

**Comment by mwoehlke-kitware** [comment]
Other failures in the matlab build, yes. I found more inadequate export declarations; we'll see if I got the last of them...

---

Review status: 3 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KOkvLUcNo9nPe95MRR3:b-hbk2qv)*

**Comment by mwoehlke-kitware** [comment]
I just added a commit to fix cpplint; it was being overly obnoxious as to trying to shut up the incorrect warnings it was producing for C++11 attributes.

We may want to take a different approach or create a fork in RobotLocomotion instead, or maybe we'll luck out and google/styleguide#166 will be merged in a timely manner.

**Comment by mwoehlke-kitware** [comment]
> I just added a commit to fix cpplint

Hmm, and apparently CI doesn't use the version in the repo :cry:

**Comment by jwnimmer-tri** [comment]
> Hmm, and apparently CI doesn't use the version in the repo

Sorry!  #2539 isn't quite done yet.  (Warning divergence is a great reason to have cpplint come from the superbuild, with a specific hash, rather than a system-image program.)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:tada: Looks like disabling hidden visibility for mex took care of the last errors... and suggests that trying to port to `FindMatlab.cmake` is going to be interesting.

**Comment by mwoehlke-kitware** [comment]
CI is clean, can I get someone to feature review, please?

**Comment by david-german-tri** [comment]
Yes, I'll get to it today.  Sorry for the lag.

**Comment by jwnimmer-tri** [comment]
For clarity, please submit the TinyXML vendoring bump as a separate PR first.

**Comment by david-german-tri** [comment]
LGTM aside from the one question

---

Review status: 1 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZEg_bUpmiqjat1ncp:bvmdd5z) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
> ```
> [submodule "externals/google_styleguide"]
> 	path = externals/google_styleguide
> 	url = https://github.com/mwoehlke-kitware/styleguide.git
> ```

Can we move this into RobotLocomotion?  I vaguely recall a thread somewhere in which you were asking for a repo for this purpose, so apologies for the lag on that.  Will `styleguide` do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KPZGBa2-coqnvzgSh0f:baa8zo6)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZIPSgL0nldN48m-Sx:b-p1u5i9) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Can we move this into RobotLocomotion?  I vaguely recall a thread somewhere in which you were asking for a repo for this purpose, so apologies for the lag on that.  Will `styleguide` do?
</details>
You may be thinking of #3171. There was also talk of moving `cpplint.py` into drake itself, which we should probably do (eventually¹), but I think that will also need (further) CI changes? @jwnimmer-tri might know more.

I have no objection making a fork of  google/styleguide into RobotLocomotion, but I don't have permission to do that.

(¹ A major advantage of doing so is that I believe it will make it possible for the cpplint build to actually *not build anything*, or indeed even configure anything, which would avoid the issue of the various work-arounds we keep having to implement for that build.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 10 of 12 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZ_hQh4bdujhoOVTQ-:b-81nlyc) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> You may be thinking of #3171. There was also talk of moving `cpplint.py` into drake itself, which we should probably do (eventually¹), but I think that will also need (further) CI changes? @jwnimmer-tri might know more.
> 
> I have no objection making a fork of  google/styleguide into RobotLocomotion, but I don't have permission to do that.
> 
> (¹ A major advantage of doing so is that I believe it will make it possible for the cpplint build to actually *not build anything*, or indeed even configure anything, which would avoid the issue of the various work-arounds we keep having to implement for that build.)
</details>
SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-:-KPZZHdIv-2toh2pbLWo:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZ_WYYSKFllXwCbUSS:bx5r250) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> SGTM.
</details>
What code was tripping up on the visibility marker, such that we have to fork cpplint?  Both the externals and `thirdParty` should be suppressed from cpplint already.

Perhaps is was the line in `MexWrapper.h` (and our one other mex header)?  Why not just `//NOLINTNEXTLINE` that (while possibly contributing the fix to upstream in the meantime)?  Forking the tool is a pretty severe reaction unless the false positive is very pervasive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065)*

**Comment by jwnimmer-tri** [comment]
Reviewed 10 of 12 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZbKoS1OQD3Ygm3V4c:b-qbljof) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
> What code was tripping up on the visibility marker, such that we have to fork cpplint?

I don't recall, but there were at least two files... three, I think.

> Why not just //NOLINTNEXTLINE that

For one, I didn't know about the `NEXTLINE` form at the time. Also, because in this case cpplint is clearly *wrong*. I don't mind using `NOLINT` when the tool is doing its job and we just don't care or want to ignore it for whatever reason. I mind more using it to work around the tool itself being broken.

> while possibly contributing the fix to upstream in the meantime

google/styleguide#166?

>  Forking the tool is a pretty severe reaction

OTOH there are good reasons to at least copy `cpplint.py` into the drake repo, at which case the question of forking becomes less interesting. (And if upstream hadn't ignored the PR for nine days already :cry:, this would be moot...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065)*

**Comment by jwnimmer-tri** [comment]
*[.gitmodules, line 95 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3065#-KPZEg_bUpmiqjat1nco:-KPZrizRR4U6_W6GFsAB:b-e6rqol) ([raw file](https://github.com/robotlocomotion/drake/blob/b774e56c88291d6d755b6c1c305c7ff78358ec28/.gitmodules#L95)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> > What code was tripping up on the visibility marker, such that we have to fork cpplint?
> 
> I don't recall, but there were at least two files... three, I think.
> 
> > Why not just //NOLINTNEXTLINE that
> 
> For one, I didn't know about the `NEXTLINE` form at the time. Also, because in this case cpplint is clearly *wrong*. I don't mind using `NOLINT` when the tool is doing its job and we just don't care or want to ignore it for whatever reason. I mind more using it to work around the tool itself being broken.
> 
> > while possibly contributing the fix to upstream in the meantime
> 
> google/styleguide#166?
> 
> >  Forking the tool is a pretty severe reaction
> 
> OTOH there are good reasons to at least copy `cpplint.py` into the drake repo, at which case the question of forking becomes less interesting. (And if upstream hadn't ignored the PR for nine days already :cry:, this would be moot...)
</details>
I guess using a personal fork of cpplint is not defective, if you prefer that approach.  If we need to bump to a newer release of cpplint and they haven't merged the fixup yet, we can just add the `NOLINTNEXTLINE` to Drake in a few places later on.  Marking as satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3065)*

**Pull request merged**
