### PR TITLE
Enable clang_format for multibody/topology directory

### PR DESCRIPTION
**Pull request by sherm1**
Sets `enable_clang_format_lint` to `True`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@SeanCurtis-TRI for both reviews per schedule, please (tiny)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801#-:-Nom93pW48BESWhP3Xei:bqw6xmv)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by sherm1 — COMMENTED** [review]
BTW multibody_graph will be replaced shortly in this directory by the new graphing code so I'm not making any changes to it other than what clang_format did to it. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801#-:-Nom9NjQ4bPHcDvj9MJz:b-8drnfa)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801#-:-NomhdyQ9tEOOUry4BGM:bxqo58p)* status: 1 unresolved discussion

___
*[`multibody/topology/BUILD.bazel` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20801#-NomhYI0EdI1v2BxkNPa:-NomhYI0EdI1v2BxkNPb:b-foreyc) ([raw file](https://github.com/RobotLocomotion/drake/blob/8eb9e1d5f0afc5eace9e9bec0d5121e394fa9452/multibody/topology/BUILD.bazel#L35)):*
> ```Starlark
> )
> 
> add_lint_tests(enable_clang_format_lint = True)
> ```

nit: I believe just omitting the parameter would be the preferred spelling.



_Suggestion:_
```Starlark
add_lint_tests()
```

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[`multibody/topology/BUILD.bazel` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20801#-NomhYI0EdI1v2BxkNPa:-Nomm_uF6JVMggOmPW6K:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/8eb9e1d5f0afc5eace9e9bec0d5121e394fa9452/multibody/topology/BUILD.bazel#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I believe just omitting the parameter would be the preferred spelling.
</blockquote></details>

Done, thanks.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20801)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
