### PR TITLE
split mixed_integer_rotation_constraint_test

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix a timeout issue on CI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBv_kkb9txEIvXDdfOM:b5jxaoc)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
 @drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
 @drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBvdAbEAqJIgtud7YF4:b-cyn7x6)*

**Comment by hongkai-dai** [comment]
+@jadecastro for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBvqn_d13l_PwewBGPQ:b-d80zvv)*

**Comment by jadecastro** [comment]
:lgtm:, pending the results of CI/Experimental.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBvsJeQ0PWgy0zuoOEm:b-t2ufc1)*

**Comment by jwnimmer-tri** [comment]
Confirmed that other than the include / using statements, the new test code is just copied or moved from the old one.

:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[solvers/test/mixed_integer_rotation_constraint_corner_test.cc, line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8766#-LBvwOucCJMgY8KZgbQI:-LBvwOucCJMgY8KZgbQJ:b7mapr3) ([raw file](https://github.com/robotlocomotion/drake/blob/1b8531a0dc3e8a9ba9fb8088990529c71e13166b/solvers/test/mixed_integer_rotation_constraint_corner_test.cc#L198)):*
> ```cpp
>   ::testing::InitGoogleTest(&argc, argv);
>   return RUN_ALL_TESTS();
> }
> ```

FYI We're past the rule-of-three on copying this `main` stanza into different tests.  It should be factored into a helper.  However, because this is emergency PR, that refactoring should happen in a follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBvvw9i8c-k1Q4p9CsX:b-bz7vh2)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBvxTKNBV7WkJyaRRIy:b5jxaoc)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBwp_8AD51QDkbaE15s:bu3g30e)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[solvers/test/mixed_integer_rotation_constraint_corner_test.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8766#-LBxTpHc01n0QW2amHOK:-LBxTpHc01n0QW2amHOL:b-cnqg05) ([raw file](https://github.com/robotlocomotion/drake/blob/156c0f5df789c0a99e626d980138357e539348a3/solvers/test/mixed_integer_rotation_constraint_corner_test.cc#L49)):*
> ```cpp
>         r_interval_binning_ == RotationMatrixIntervalBinning::kLogarithmic) {
>       const IntervalBinning interval_binning =
>           r_interval_binning_ == RotationMatrixIntervalBinning::kLinear
> ```

FYI, we have build failures as `kLinear` is removed from`enum RotationMatrixIntervalBinning` by this PR but still used here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/mixed_integer_rotation_constraint_corner_test.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8766#-LBxTpHc01n0QW2amHOK:-LBy04rTE-ebFZTHxLdW:bkf9efk) ([raw file](https://github.com/robotlocomotion/drake/blob/156c0f5df789c0a99e626d980138357e539348a3/solvers/test/mixed_integer_rotation_constraint_corner_test.cc#L49)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we have build failures as `kLinear` is removed from`enum RotationMatrixIntervalBinning` by this PR but still used here.
</blockquote></details>

Thanks! I should have build this before pushing the commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBy03SH-et6AuC55k46:bu3g30e)*

**Comment by soonho-tri** [comment]
- `//solvers:mixed_integer_rotation_constraint_corner_test` timed out in `linux-xenial-gcc-bazel-experimental-everything-debug`.
 - I've also found that the same test times out on a mac (> `900`s)

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LBz7oep-_G7rnDm6NBU:b1sziz1)*

**Comment by jwnimmer-tri** [comment]
Perhaps running all of the test cases in debug mode isn't going to be practical.  Maybe consider turning off some or all of the cases under `-c dbg`.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LC-Mr2TEIPpz2OcDJc2:bu3g30e)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766)*

**Comment by jadecastro** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8766#-:-LC-ghQ92G_vPOR5X8_R:b-l70wzf)*

**Pull request merged**
