### PR TITLE
[parsing] Port to parser.AddModels, part 4

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This is another file that was missed in prior passes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18372)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri  for both reviews.
+(release notes: none)
FYI: @damrongguoy 

For context, this is helping to drain the call-site noise from #18157, which proposes more Parser API design changes.

See also prior steps at #18277, #18266, #18343.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18372#-:-NI-_8twE9FMLgCWHu3D:bntgijk)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(priority: low) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18372#-:-NI-_RtR7yMA5WhT6Cj4:b-nzc0ap)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) 
:lgtm: both.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18372#-:-NI-b-yg7cYHCF_AZSOe:b-8mi2ml)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18372)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
