### PR TITLE
Control precision/offset of vertex data in maliput OBJ generation.

### PR DESCRIPTION
**Pull request by maddog-tri**
The two changes here:
 1. Explicitly set the fixed-point precision of vertex coordinates printed into an OBJ file by `maliput::utility::GenerateObj()`, based on the declared `linear_tolerance()` of the `RoadGeometry`.
 2. Add an `origin` parameter to OBJ generation, and translate vertex output relative to the origin.

This (particularly #2) is useful when, for example, the RoadGeometry's world-frame is expressed in UTM coordinates.  UTM coordinates are typically enormous numbers, which end up getting truncated by rendering engines with single-precision `float` implementations.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5915)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-:-KiGw5lVq73r3tpm0l1C:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@jwnimmer-tri  for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-:-KiGyjtyaekxtpkdP6Gy:b59ib8v)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiHlY3H6C4aJ2pocq9P:b-y5bpc3) (no related file):*
It seems like there should be unit test changes for this feature?  It is somehow already covered?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiHutU8Z-IHM-j6zW98:b5a3aww) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like there should be unit test changes for this feature?  It is somehow already covered?
</blockquote></details>

(Technically two features -- origin and precision.)

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHtOs2l6dReoQazIRS:-KiHtOs3i9gLMtKhjiQD:bsgxr56) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L212)):*
> ```cpp
>   EmitObj(std::ostream& os, const std::string& material,
>           int vertex_index_offset, int normal_index_offset,
>           int precision,
> ```

Unclear (no API doc) what `precision` means specifically.  I'm guessing its the number of digits after the decimal point, but I'd have to dig into `fmt` docs to know for sure.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHt4hH4RnqC49pU04X:-KiHt4hIwqMJrXLv9Rt0:b-wvoda6) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L213)):*
> ```cpp
>           int vertex_index_offset, int normal_index_offset,
>           int precision,
>           const api::GeoPosition& origin) {
> ```

Unclear (no API doc) what the effect of `origin` is.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 625 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHudCPdX7RpPUSEuCX:-KiHudCPdX7RpPUSEuCY:b1qks49) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L625)):*
> ```cpp
>     DRAKE_DEMAND(rg->linear_tolerance() > 0.);
>     const int precision =
>         std::max(0., 1. - std::floor(std::log10(rg->linear_tolerance())));
> ```

I'm guessing the `1` is something like "use one more digit beyond what the tolerance would suggest, so that roundoff doesn't change the value"?  In any case, please clarify why there is a `1` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by maddog-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiHwzi5uf7HKlB2UJq0:bkuj4u5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(Technically two features -- origin and precision.)
</blockquote></details>

Hmm, true --- the only unit-test for any of this is a "yes, files are written to disk" test, as the only public methods are `GenerateObj()` and `GenerateUrdf()`.  A unit-test on the public methods would thus take the form of string-matching on the emitted OBJ file contents, which no one was very interested in the first time around.  But, it can be done.  Or, any alternative suggestions?

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHtOs2l6dReoQazIRS:-KiIpUo0FaFWc3Y_cRZb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear (no API doc) what `precision` means specifically.  I'm guessing its the number of digits after the decimal point, but I'd have to dig into `fmt` docs to know for sure.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHt4hH4RnqC49pU04X:-KiIpVY6sfwHhxrT63iD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L213)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear (no API doc) what the effect of `origin` is.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 625 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHudCPdX7RpPUSEuCX:-KiIpW9JXayFbmQmDHFw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L625)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm guessing the `1` is something like "use one more digit beyond what the tolerance would suggest, so that roundoff doesn't change the value"?  In any case, please clarify why there is a `1` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiKTfzZjdDwfkLMi65S:b-62yy0m) (no related file):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Hmm, true --- the only unit-test for any of this is a "yes, files are written to disk" test, as the only public methods are `GenerateObj()` and `GenerateUrdf()`.  A unit-test on the public methods would thus take the form of string-matching on the emitted OBJ file contents, which no one was very interested in the first time around.  But, it can be done.  Or, any alternative suggestions?
</blockquote></details>

This PR's changes don't relate on a file coming out, just the contents of the file.  One way to test that would be to expose new public APIs that generates the OBJ and/or URDF into a string (or ostream), and then inspect the contents of that string (probably with just a golden-wall-of-text test).

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 625 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHudCPdX7RpPUSEuCX:-KiKTZSoCnk-oq4vfONQ:b-6nintu) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L625)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm.  The comment is much better, but I don't see where the `1.25` comes from now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by maddog-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiMem_AIf0PY3rpAVZb:bx1x7wg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR's changes don't relate on a file coming out, just the contents of the file.  One way to test that would be to expose new public APIs that generates the OBJ and/or URDF into a string (or ostream), and then inspect the contents of that string (probably with just a golden-wall-of-text test).
</blockquote></details>

It turns out `generate_urdf_test.cc` was already reading URDF file output and comparing that to a "golden-wall-of-text", so I reused that (with some cleanup) into a `generate_obj_test.cc`.  This implicitly exercises the numeric-precision code, and explicitly tests the origin-shifting code.

It didn't seem worthwhile at this point to create extra new public API's to just feed content to ostream's:  there is no immediate user for such API's, and they are a little messy in that there is both the OBJ content and the MTL content (e.g., two ostreams involved), and the former references the filename of the latter.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 625 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHudCPdX7RpPUSEuCX:-KiMg2HbcQ7AdoIO0M4T:b-42cf26) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L625)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hm.  The comment is much better, but I don't see where the `1.25` comes from now?
</blockquote></details>

Done, again, hopefully.  Yeah, I'm not sure where the `.25` in particular came from.  I have notes, but at some point I typed an expression into python and ended up writing down an incorrect value in the notes.  So, screw that, I will let C++ do the work now.  (The correct value is actually more like `0.9375306316958499`, maybe.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHlY3GBrjDsIrx9z77:-KiMvgDxq0cy5SKHvwVa:b-o5rub0) (no related file):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

It turns out `generate_urdf_test.cc` was already reading URDF file output and comparing that to a "golden-wall-of-text", so I reused that (with some cleanup) into a `generate_obj_test.cc`.  This implicitly exercises the numeric-precision code, and explicitly tests the origin-shifting code.

It didn't seem worthwhile at this point to create extra new public API's to just feed content to ostream's:  there is no immediate user for such API's, and they are a little messy in that there is both the OBJ content and the MTL content (e.g., two ostreams involved), and the former references the filename of the latter.
</blockquote></details>

OK Reading back the file is great too.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 625 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiHudCPdX7RpPUSEuCX:-KiMyzv5ovbA11A9v8vd:b-mjhl89) ([raw file](https://github.com/robotlocomotion/drake/blob/ff9d7ffd45bde9bc370514769450abd607e6a7dc/drake/automotive/maliput/utility/generate_obj.cc#L625)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done, again, hopefully.  Yeah, I'm not sure where the `.25` in particular came from.  I have notes, but at some point I typed an expression into python and ended up writing down an incorrect value in the notes.  So, screw that, I will let C++ do the work now.  (The correct value is actually more like `0.9375306316958499`, maybe.)
</blockquote></details>

OK Great, I definitely could follow it now.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 632 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiMwkN172TYcsNHfT2F:-KiMwkN2c3OaMp0bLRHT:bbn9ufo) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/generate_obj.cc#L632)):*
> ```cpp
>     // times the per-component error.  The `10` is a fudge-factor to ensure
>     // that the error in a rendered vertex with respect to the true position
>     // (underlying the value expressed by maliput) is within 110% of ε.
> ```

FYI It seems to me like the `/ 10` gives "within 10%" error, not sure where 110% comes from.   I don't know that its worth quibbling about though, or I may be misreading it.

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiMzYIk4GMJ7tZAfcqe:-KiMzYIk4GMJ7tZAfcqf:bntomy0) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/test/generate_obj_test.cc#L61)):*
> ```cpp
>  protected:
>   static constexpr double kLinearTolerance = 0.01;
>   static constexpr double kAngularTolerance = 0.01 * M_PI;
> ```

BTW I think these both need ODR storage (putting `constexpr double GenerateObjBasicDutTest::kAngularTolerance;` outside of the class declaration.

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 692 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiN-Jocr-b8Jp8ZYMmx:-KiN-Jocr-b8Jp8ZYMmy:b-c3gebo) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/test/generate_obj_test.cc#L692)):*
> ```cpp
> f 143//3 150//3 144//3
> f 143//3 148//3 150//3
> )R", actual_obj_contents);
> ```

BTW Is this string identical to the prior test case?  Perhaps it should be defined once and then reused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-:-KiN-UTszzXdj-gMvZLQ:bnfp4nl)*

**Comment by maddog-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 632 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiMwkN172TYcsNHfT2F:-KiNGBG99QIQG4RYLoAP:b-2hkjs5) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/generate_obj.cc#L632)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It seems to me like the `/ 10` gives "within 10%" error, not sure where 110% comes from.   I don't know that its worth quibbling about though, or I may be misreading it.
</blockquote></details>

What I am trying to express:  maliput guarantees that it expresses (at runtime) positions within 100% ε of the ground-truth, but when emitting those values as fixed-point strings we add rounding errors on top of that, so we limit the rounding error to an additional 10% ε.

I've edited the comment to try to clear this up.

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiMzYIk4GMJ7tZAfcqe:-KiNgrVPDIzbYcIcODtR:b-3hqvxl) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/test/generate_obj_test.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think these both need ODR storage (putting `constexpr double GenerateObjBasicDutTest::kAngularTolerance;` outside of the class declaration.
</blockquote></details>

Done, as in "Meh, I don't care about figuring out the optimal form of storage, but I do want the values to be defined within the class, so plain old `const` works for me."

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 692 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-KiN-Jocr-b8Jp8ZYMmx:-KiNhHCPN3I3VDui4EfP:b3j1fzw) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc4670abc750dbb77864afb9abf0cdccc0d0d3e/drake/automotive/maliput/utility/test/generate_obj_test.cc#L692)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this string identical to the prior test case?  Perhaps it should be defined once and then reused?
</blockquote></details>

Almost - I think the only difference is in the embedded filename for the MTL file.  I'm not going to futz with it now.

A better tack is probably just to have golden-files in the test directory, instead of embedded strings --- it will be a lot easier to assess test failures and perform future test updates that way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-:-KiNn5rLZRgVaeDaGY0z:b-s794vx)*

**Comment by maddog-tri** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5915#-:-KiNzAE9tW_Gz72UIG-n:b-l70wzf)*

**Pull request merged**
