### PR TITLE
Adds multi-lane road tests to Multilane Loader test suite

### PR DESCRIPTION
**Pull request by hidmic**
Connected to #8899. This pull requests adds another test case to the Multilane Loader test suite that checks for proper construction of multi-lane roads with nonzero elevation and superelevation, while making use of the `explicit_end` specifications along with `reverse` endpoint semantics.

A render of the road under test is added below for completeness:

funky_road00

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9302)

### CODE REVIEW

**Comment by hidmic** [comment]
cc @basicNew and @agalbachicar to track progress.

**Comment by hidmic** [comment]
+@maddog-tri for feature review please.

**Comment by hidmic** [comment]
@drake-jenkins-bot test this please

**Comment by hidmic** [comment]
Thanks for the review @jadecastro.

+@soonho-tri for platform review please.

**Comment by jwnimmer-tri** [comment]
When CI hasn't run on a PR since 25 days ago (or really, more than a day or two), its probably worth forcing a retest before merging.

**Comment by soonho-tri** [comment]
My bad (The PR was five days old).

**Comment by jwnimmer-tri** [comment]
Ah yes.  I see the 5-day jenkins results now.

**Pull request merged**
