### PR TITLE
Yaml cpp bazel

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4494)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
lousy mosek... revising.

**Comment by rpoyner-tri** [comment]
Ok. Ready for a look: usual suspects +@jwnimmer-tri +@sammy-tri -(status: do not merge) -(status: do not review) 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4494#-:-KYxc9oFVuUJGunEC7Bj:bz4yno5)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/BUILD, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4494#-KYxl5mAMtcjmtfBh2oe:-KYxl5mAMtcjmtfBh2of:b47p4f4) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4698d9eb58d6bcea136c63a7bd3ff3493847ea/drake/automotive/BUILD#L137)):*
> ```Python
>         "//drake/systems/primitives:multiplexer",
> 
>         # TODO(rpoyner-tri): testing; remove once maliput is integrated.
> ```

BTW this could probably be slightly clearer than it only exists to create any dependency on yaml_cpp to keep it building until maliput (the actual final user) starts depending on it.

Such a clarification is probably more important if the summary above was wrong.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4494)*

**Comment by rpoyner-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/BUILD, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4494#-KYxl5mAMtcjmtfBh2oe:-KYxq1QGRZ1_AQ5etWWu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4698d9eb58d6bcea136c63a7bd3ff3493847ea/drake/automotive/BUILD#L137)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this could probably be slightly clearer than it only exists to create any dependency on yaml_cpp to keep it building until maliput (the actual final user) starts depending on it.

Such a clarification is probably more important if the summary above was wrong.  :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4494)*

**Comment by jwnimmer-tri** [comment]
:lgtm: 

Consider updating the OP text to auto-close the issue when this is merged.

---

Reviewed 2 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4494#-:-KYxq9c-YchZm68gUWe7:b-beywrg)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4494#-:-KYxqOlircpjTDOH3AgQ:bnfp4nl)*

**Pull request merged**
