### PR TITLE
[workspace] Switch conex to use hidden namespace

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

See also https://github.com/ToyotaResearchInstitute/conex/pull/6.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

___
*[`multibody/contact_solvers/conex_supernodal_solver.cc` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NalR-e6DXFXgliwy-cx:-NalR-e72Qy36FiIdonE:b-jkfuao) ([raw file](https://github.com/RobotLocomotion/drake/blob/4520279de8a7a68a7459d2cab78ed8b95dabf1e4/multibody/contact_solvers/conex_supernodal_solver.cc#L7)):*
> ```cpp
> 
> #include "drake/common/drake_export.h"
> #include "drake_vendor/conex/clique_ordering.h"
> ```

Working

I might try not adding the `drake_vendor` prefix to see if it works better.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: 
+@rpoyner-tri for platform review please.

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-:-NamR_r0C4a15hSdhSg1:b-pgkvtj)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/BUILD.bazel` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamPKns8We6sPfTEt9L:-NamPKns8We6sPfTEt9M:bb6ssgc) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/BUILD.bazel#L49)):*
> ```Starlark
>     srcs = ["vendor_cxx.py"],
>     visibility = [
>         # These should all be of the form "@foo_internal//:__subpackages__".
> ```

BTW,
___
*[`tools/workspace/conex_internal/vendor.bzl` line 16 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamLEFO4oKEcOeHDzQh:-NamLEFP8dzrftsJMsPi:b-b7y19q) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/vendor.bzl#L16)):*
> ```Starlark
>     For "supernodal_solver", declares a cc_library in the usual sense, except
>     rewrites the source code so that it uses a `drake_vendor` inline hidden
>     namespace wrapper so that the library's linker symbols are private.
> ```

BTW, understanding check, the namespace wrapper is applied by `vendor_cxx` and this bazel function simply routes to `cc_library_vendored`?



_Code quote:_
```Starlark
    rewrites the source code so that it uses a `drake_vendor` inline hidden
    namespace wrapper so that the library's linker symbols are private.
```
___
*[`tools/workspace/conex_internal/vendor.bzl` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamLhFV2bgWgqolZNvo:-NamLhFV2bgWgqolZNvp:b-42eunn) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/vendor.bzl#L49)):*
> ```Starlark
>     ]
>     edit_include = None
>     strip_include_prefix = "/conex/drake_vendor"
> ```

BTW, I don't understand how this works. Don't the vendored sources and headers have prefix `drake_vendor/conex`?



_Code quote:_
```Starlark
strip_include_prefix = "/conex/drake_vendor"
```
___
*[`tools/workspace/conex_internal/patches/eigen_namespace_pollution.patch` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamRRU22u5AM8Kz7ND1:-NamRRU22u5AM8Kz7ND2:b-yhfbai) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/patches/eigen_namespace_pollution.patch#L1)):*
> ```Diff
> [conex] Fix RLDLT to live in the conex namespace
> ```

BTW, is there a path towards merging the PR upstream? Do we really need the patch?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/BUILD.bazel` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamPKns8We6sPfTEt9L:-NamTlug3B0I_76voqLn:b-896fig) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/BUILD.bazel#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW,
</blockquote></details>

Done?
___
*[`tools/workspace/conex_internal/vendor.bzl` line 16 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamLEFO4oKEcOeHDzQh:-NamU8Dr7APpz1xxXK20:bavkn03) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/vendor.bzl#L16)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, understanding check, the namespace wrapper is applied by `vendor_cxx` and this bazel function simply routes to `cc_library_vendored`?
</blockquote></details>

Yes.  I've amended the comment a bit, too.
___
*[`tools/workspace/conex_internal/vendor.bzl` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamLhFV2bgWgqolZNvo:-NamSzDJEko0Pl9UPLWs:b-x3e4t8) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/vendor.bzl#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I don't understand how this works. Don't the vendored sources and headers have prefix `drake_vendor/conex`?
</blockquote></details>

The [semantics](https://bazel.build/reference/be/c-cpp#cc_library.strip_include_prefix) of this string differ depending on whether or not it opens with a `/`.  It will probably be clearest, though, to use the spelling without the slash.
___
*[`tools/workspace/conex_internal/patches/eigen_namespace_pollution.patch` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamRRU22u5AM8Kz7ND1:-NamTFxh-fYJLzGu_zsZ:b-5u3w9) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/patches/eigen_namespace_pollution.patch#L1)):*
> Do we really need the patch?

Yes.  Otherwise we end up vendoring the class as `drake_vendor::Eigen::RLDLT` which doesn't work at all.  (It can't find the _real_ Eigen symbols.)

> Is there a path towards merging the PR upstream?

See the link below on line 7.  I've submitted this patch upstream as a pull request.

From past experience, though, upstream is dead.  There are trivial open PRs there that are 6+ months old with no reply.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/BUILD.bazel` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamPKns8We6sPfTEt9L:-NameTGwACjSNAmRS8E5:b-c69vfg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/BUILD.bazel#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

I was able to figure this one out but forgot to deleted the half finished thought. Apologies.
___
*[`tools/workspace/conex_internal/vendor.bzl` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-NamLhFV2bgWgqolZNvo:-NamekvY5dbmrRq9Z1Ae:bg8qwk4) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc812ea6faf671623823ba1635c6f1ea8074fe03/tools/workspace/conex_internal/vendor.bzl#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The [semantics](https://bazel.build/reference/be/c-cpp#cc_library.strip_include_prefix) of this string differ depending on whether or not it opens with a `/`.  It will probably be clearest, though, to use the spelling without the slash.
</blockquote></details>

Oh I see. Thanks for the reference.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19892#-:-NanVYe-AstuN2z8NfsD:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Comment by ggould-tri** [comment]
FYI, this PR is the primary suspect in two CI failures,

* [linux-focal-gcc-bazel-nightly-coverage/1164](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-gcc-bazel-nightly-coverage/1164/consoleFull)
* [linux-focal-clang-bazel-nightly-coverage/1159](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-clang-bazel-nightly-coverage/1159/consoleFull)

At @svenevs request we (#buildcop) are holding off on reverting this in hope of a fix-forward.

**Pull request merged**
