### PR TITLE
Fix bug in glTF depth and label representations

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
When glTF objects were rendered in depth or label images, they would be (at least) rotated from where they should be. In fact, if a non-unit scale factor was applied, they'd also be scaled too much (the scale factor squared).

This is because the creation of the color representation would modify the reference version before the depth and label versions were created. So, those later representations would accumulate an extra concatenation of the T_GF transform (the one that related the glTF file frame with the Drake geometry frame -- this transform incorporated both the 90-degree rotation from y-up to z-up and the Mesh/Convex scale factor).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+@zachfang for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-NpVQ22tBWhXDRl1i_uf:b-d3odka)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@zachfang due to suffering from a bout of taking time off.
+@jwnimmer-tri for feature review due to suffering from having looked at VTK in the past.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-NpVsTcX-bnpgisFmO3P:b-niph3w)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-Np_VvAL3t44Vm6xkozS:b-n37teh)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1005 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_L_O4CVwVdOPSn1Bf:-Np_L_O4CVwVdOPSn1Bg:b-ltp63i) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1005)):*
> ```cpp
> }
> 
> // Colors the 32-bit depth image as a 8-bit luminance image. This allows humans
> ```

nit This seems like its duplicating most of the logic of `ColorizeDepthImage::Calc`, and it seems a shame to bloat an already huge unit test file with this utility.

Also because this version only uses grayscale, we've lost the ability to easily recognize the too-near and too-far special values while debugging.  I think it would be noticeably better to use our standard visualization capability when making debug images, since that's the visual format our developers will already be familiar with.  (It also standardizes on whether the pixels closest to the camera should be brightest or darkest, which this new code does the opposite of the existing code.)

If we need to set a prescribed dynamic range instead of a inferring it, that could happen via a new constructor overload on `ColorizeDepthImage` to take a DepthRange.

Or at the minimum, we need a TODO here noting the duplication for future refactoring to use shared code.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1015 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_UI4X48fdSPZyLvpK:-Np_UI4X48fdSPZyLvpL:bv9thl2) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1015)):*
> ```cpp
>       original_depth.at(0, 0), original_depth.size());
>   for (int i = 0; i < clamped.size(); ++i) {
>     clamped[i] = std::clamp(clamped[i], min_value, max_value);
> ```

nit The `std::clamp` might leave a NaN value intact, which would then be UB during the cast to Byte.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1065 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_Sr7rE3L5jqTPrTdz:-Np_Sr7rE3L5jqTPrTe-:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1065)):*
> ```cpp
> 
>   ImageDepth32F depth32_image(size, size);
>   // Depth ranged centered on the Wx = 0 plane. The pyramid should extend less
> ```

typo



_Suggestion:_
```cpp
Depth range
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1085 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_XB_vAmlvmu14LTL8:-Np_XB_w0c_vkd7-7uCW:bywkzu2) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1085)):*
> ```cpp
>         // anti-aliasing, it would NOT be true that everywhere the color image
>         // is NOT the background color, we should have a non-background depth or
>         // label reading.
> ```

BTW When we have a pixel with infinite depth, I agree with the comment here about the color image having AA, but it leaves me wondering...

I expect the _label_ image should not have AA enabled, so it seems like we _could_ be testing the label values here in an `else` branch?  Any reason to do that (or not to do it)?  Maybe the comment could say more about it.  Not worth it, since the test is already good enough to detect any reasonable pose errors?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-Np_pPDgAlMCvR-k-bUN:b-zcjvte)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1005 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_L_O4CVwVdOPSn1Bf:-Np_jbh_55AykY4WCjfF:biefvxn) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1005)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This seems like its duplicating most of the logic of `ColorizeDepthImage::Calc`, and it seems a shame to bloat an already huge unit test file with this utility.

Also because this version only uses grayscale, we've lost the ability to easily recognize the too-near and too-far special values while debugging.  I think it would be noticeably better to use our standard visualization capability when making debug images, since that's the visual format our developers will already be familiar with.  (It also standardizes on whether the pixels closest to the camera should be brightest or darkest, which this new code does the opposite of the existing code.)

If we need to set a prescribed dynamic range instead of a inferring it, that could happen via a new constructor overload on `ColorizeDepthImage` to take a DepthRange.

Or at the minimum, we need a TODO here noting the duplication for future refactoring to use shared code.
</blockquote></details>

I wasn't realized we had the system.  Thanks.

I'm happy to swap, are you concerned at all about the dependencies between `visualization` and `geometry`?  I assume not since you suggested it.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1015 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_UI4X48fdSPZyLvpK:-Np_kzAY43fWpb7whQS8:b-akqlpd) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1015)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The `std::clamp` might leave a NaN value intact, which would then be UB during the cast to Byte.
</blockquote></details>

Moot as we've killed the bespoke function.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1085 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_XB_vAmlvmu14LTL8:-Np_lZqV9p1DxKd5e61G:b-9nz43m) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1085)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW When we have a pixel with infinite depth, I agree with the comment here about the color image having AA, but it leaves me wondering...

I expect the _label_ image should not have AA enabled, so it seems like we _could_ be testing the label values here in an `else` branch?  Any reason to do that (or not to do it)?  Maybe the comment could say more about it.  Not worth it, since the test is already good enough to detect any reasonable pose errors?
</blockquote></details>

There are several relationships we could assert:

1. non-infinite depth --> non-background color
2. non-infinite depth --> pyramid label
3. pyramid label --> non-infinite depth

We are explicitly testing (1) and (2) but not (3). It's true the test could be foiled by, say, the label representation not being scaled. With that bug, this test wouldn't catch that (that might also be enough to mask translation errors as well).

In writing all of that, I've decided to make the test more robust to transformations. FTR, this specific test will be subsumed by the test in #20701. But I've made the effort to make *this* test more robust, so that in replacing it there, I have to explicitly account for the factors that made this test more robust.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854)* status: needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1005 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-Np_L_O4CVwVdOPSn1Bf:-Np_pZqC6xSdu2W6gM_F:b-ki05vf) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd99b74860784e20bac17f23ac495ac7779a9f08/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1005)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I wasn't realized we had the system.  Thanks.

I'm happy to swap, are you concerned at all about the dependencies between `visualization` and `geometry`?  I assume not since you suggested it.
</blockquote></details>

Generally I think it's fine for tests to bring in extra packages.  (It's a different story for the library, non-test code.)

The question here is less about a general policy, and more about in practice is it ever too annoying to rebuild any particular test as you iterate on changes.  In other words, less about the packages we're touching and more about the exact dependencies and if they need to rebuild when the DUT changes.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for irregular platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-Np_qtIN6IjT5eswrldn:bpzfs3a)* status: LGTM missing from assignee rpoyner-tri(platform)

**Comment by SeanCurtis-TRI** [comment]
Grazi.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20854#-:-Np_twII7ys_CKdYnFr3:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
