### PR TITLE
Adds clarification on the usage of EigenPtr

### LINKED ISSUE #7944: Mutable arguments of type EigenPtr do not allow resizing
Consider a method with signature:
```c++
CalcSomeMatrix(EigenPtr<MatriX<T>> output_matrix) {
  DRAKE_THROW_UNLESS(output_matrix != nullptr);
  if (output_matrix->rows() != 4 || output_matrix->cols() != 3) {
    output_matrix->resize(4, 3);  // This fails at runtime!!!
  }
  // Perform computation safely knowing output_matrix now has the right size...
}
```

The idea here is that we'd guarantee users of these methods that if they provide a matrix with the wrong size, then we'd resize it for them. However, per Eigen's docs, the `resize()` method is only valid for plain matrices/arrays, i.e. `Matrix::resize()` and `Array::resize()`. Since `EigenPtr::opertor->()` returns an `Eigen::Ref`, we cannot resize our input argument, even when it is meant to be mutable.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Updates `EigenPtr` doc per discussion in #7944.

Closes #7944.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7957)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for feature review please.
+@ericcousineau-tri for platform please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7957#-:-L4arPfu3iLJT6b3XVnj:b-glhx44)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/eigen_types.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7957#-L4bJd0SVTC4_MCZ_Wqg:-L4bJd0ULmFRTR3UBhMv:bgwsbh6) ([raw file](https://github.com/robotlocomotion/drake/blob/248d01f0e74fea039d74f13f02e862100577f2b2/common/eigen_types.h#L282)):*
> ```objc
> ///   DRAKE_THROW_UNLESS(M != nullptr);
> ///   // In this case this method only works with 4x3 matrices.
> ///   if (M->rows() !=4 && M->cols() != 3) {
> ```

BTW whitespace around `!=`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7957#-:-L4bK5EkqHJS5E8QLwed:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7957#-:-L4bMdT0kBvZdbhiICjY:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7957)*

**Pull request merged**
