### PR TITLE
Revert "MosekSolver sets logging using CommonSolverOption (#15382)"

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This reverts commit c2a218e3d3a3ed1d680cb49db29330629744909a.

Caused failures with address-sanitizer and leak-sanitizer.

 Dear Hongkai,

 The on-call build cop, rpoyner-tri, believes that your PR 15382 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:
 https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/3639/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-leak-sanitizer/351/

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15388)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please.

**Review by rpoyner-tri — COMMENTED** [review]
+@hongkai-dai for author revert review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15388#-:-MeViEl27Hhk_KUoIwYe:b-h84mkw)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
+(priority: emergency) +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15388#-:-MeVim_WBNMFkNlIgNLR:bn5qb37)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15388#-:-MeVm8mw2DlIgVVoZLZq:bg7igkv)* status: needs platform reviewer assigned (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review (is there another way to clear the bit for emergency reverts?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15388#-:-MeVmvdCAcnrL8YK0ZlS:be7ung6)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm:

You can assign to yourself and self-lgtm -- nothing in the interlocks prevents that.

**Pull request merged**
