### PR TITLE
remove enable_if<is_arithmetic> Pow from polynomial

### PR DESCRIPTION
**Pull request by RussTedrake**
We've overloaded `pow` for autodiff in common now, so can remove the special case implementation here. 

Also suspicious:  `Pow` was being called (from the friend class) with the Polynomial type (not it's coefficient) as the template argument... which of course was never `is_arithmetic`.  I believe this is the correct solution?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6974)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6974#-:-KtLOKgk2DvMKuH-JAlx:b-k8t9z5)*

**Comment by soonho-tri** [comment]
:lgtm:

+@ggould-tri , platform-review please!

> Also suspicious: Pow was being called (from the friend class) with the Polynomial type (not it's coefficient) as the template argument... which of course was never is_arithmetic.

That sounds strange. It is the case that we have `is_arithmetic<Polynomial<T>>::value == false`. @ggould-tri , do you have an idea what happened?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6974#-:-KtMoIttBc-mSDva4TDt:bdv09l3)*

**Comment by ggould-tri** [comment]
I'm not sure which call site you are saying is suspicious.  Can you give me a line number?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6974#-:-KtMs8tokkO3iu-6cu7q:b-5lxyt4)*

**Comment by RussTedrake** [comment]
Upon reflection, there was nothing really wrong except that the comment suggested a different use than was actually happening in the code.  After reading the comment above the Pow method, I understood the intent of the enable_if on Pow was to handle doubles differently than autodiff.  But the old line 481 (the last deleted line in this PR) was passing an object of type Polynomial to the Pow method (not a scalartype at all).  

At any rate, i think the new version is cleaner.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6974#-:-KtOn1KYFAqO73zv7iSs:bigk0at)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6974#-:-KtRTUFUvO_vsUVqHzIV:bnfp4nl)*

**Pull request merged**
