### PR TITLE
Call scaling() before solving in ClpSolver.

### LINKED ISSUE #15341: Clp gives the wrong answer (claiming success) for a trivial LP
This one was tough to find! 

```
import numpy as np
from pydrake.all import MathematicalProgram, le, Solve, IpoptSolver, ClpSolver, SolverOptions, CommonSolverOption

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
ipopt = IpoptSolver()
clp = ClpSolver()

A = np.array([[1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0],
 [-1.0, -0.0, -0.0],
 [-0.0, -1.0, -0.0],
 [-0.0, -0.0, -1.0],
[ 9.99400723e-01, -1.75186298e-21,  3.46149414e-02],
 [ 9.82328785e-01,  1.82238474e-20, -1.87163452e-01],
 [ 9.68599420e-01, -2.48626556e-01, -1.27003703e-12],
 [ 9.68599420e-01,  2.48626556e-01 ,-1.27003703e-12]])
b = np.array([1.0, 0.5, 1.0, -0.0, 0.5, -0.0, 0.46783912,  0.39023174,  0.50647967,  0.50647967])

prog = MathematicalProgram()
x = prog.NewContinuousVariables(3)
r = prog.NewContinuousVariables(1)[0]

A_row_norm = np.linalg.norm(A, axis=1)
lhs = A.dot(x) + A_row_norm * r
prog.AddLinearConstraint(le(lhs, b))
prog.AddLinearConstraint(r >= 0)
prog.AddLinearCost(-r)

result1 = ipopt.Solve(prog)
assert result1.is_success()
print(result1.get_solver_id().name())
print(result1.GetSolution(x))
print(result1.is_success())
print(result1.get_solution_result())

options = SolverOptions()
options.SetOption(CommonSolverOption.kPrintToConsole, 1)
prog.SetSolverOptions(options)

result2 = clp.Solve(prog)
assert result1.is_success()
print(result2.get_solver_id().name())
print(result2.GetSolution(x))
print(result2.is_success())
print(result2.get_solution_result())
print(result2.get_solver_details().status)
```

gives 
```
IPOPT
[0.23 -0.00 0.33]
True
SolutionResult.kSolutionFound
CLP
[0.00 0.00 0.00]
True
SolutionResult.kSolutionFound
```

The answer from Ipopt is correct,.  

Note that the small numerical values in the coefficients seem to have something to do with it.  If I set the two coefficients that are ~ `1e-21` to zero, then CLP once again gives the correct answer.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This handles the poor scaling in the problem data.

Resolves #15341

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYG58mCXYStaaO9EVA:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Nice!  I was thinking of my numbers as 0, and hadn't thought that the fact that they were more like `eps` could be causing problems.  Thanks for tracking it down!
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYJanE055ilNOVOT1H:bxrp7uf)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
@russtedrake I have to change `graph_of_convex_sets_test` to pass the test. Now setting the scaling option to 1 will change the solution a bit. 

Is it possible to pass in `std::optional<SolverOption> solver_options=std::nullopt` as an argument to `GraphOfConvexSet::SolveShortestPath`? Currently the mathematical program is completely wrapped within this function, we can't change it and cannot pass in solver options.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYQ8QpAA3HMpY_NOdo:b-npnlx3)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYW91w8HHicaDtII5P:b-c9pjop)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @RussTedrake and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
I definitely agree that we want to have the ability to configure the solver through the graph of convex sets.  I only waited on it because I knew you were working on the solver options at the time I was writing it:
https://github.com/RobotLocomotion/drake/blob/master/geometry/optimization/graph_of_convex_sets.h#L296

I will add it the next time it rears it's head for me, but would of course welcome the contribution if you want to change it!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYj-3YCtF9PuE5hv4t:bojofbd)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @RussTedrake and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai and @sammy-tri)

___
*[solvers/test/clp_solver_test.cc, line 212 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16281#-MrYk1JD8cQZSEZF5nBR:-MrYk1JD8cQZSEZF5nBS:b-jietks) ([raw file](https://github.com/robotlocomotion/drake/blob/e120d83ad78727bd6ff6ac4ed2b1b8f2599c877d/solvers/test/clp_solver_test.cc#L212)):*
> ```cpp
>   TestLPPoorScaling1(solver, 1E-14, solver_options);
>   TestLPPoorScaling2(solver);
>   TestLPPoorScaling2(solver, 1E-4, solver_options);
> ```

Can you make at least one of these run with `scaling != 1`?

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
I will add solver_options as an argument in a separate PR, as I try to merge this PR in before the break.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYyooh-xdAH5W2UyX6:b-3stm5f)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @RussTedrake and @sammy-tri)

___
*[solvers/test/clp_solver_test.cc, line 212 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16281#-MrYk1JD8cQZSEZF5nBR:-MrYyhRJ405hF2AN0Hou:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e120d83ad78727bd6ff6ac4ed2b1b8f2599c877d/solvers/test/clp_solver_test.cc#L212)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can you make at least one of these run with `scaling != 1`?
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrYzAkB3Bar-hCEUV0G:bnfp4nl)* status: 1 unresolved discussion, missing label for release notes (waiting on @RussTedrake)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16281#-:-MrZNKuy-M6GrKs93lPk:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this, please
(since I just merged the qhull PR, which did have some LPs inside it... just to be safe).

**Pull request merged**
