### PR TITLE
Adds a "Message Passing" Doxygen group containing LCM systems.

### LINKED ISSUE #6355: LCM and ROS systems should appear in doxygen groups
http://drake.mit.edu/doxygen_cxx/group__systems.html

I would like to see a subgroup for "Message Passing" that contains the leaf systems in 
https://github.com/RobotLocomotion/drake/tree/159b31408998aea34299913843d12f49e81e3d45/drake/systems/lcm

and (if it makes sense)
https://github.com/RobotLocomotion/drake/tree/159b31408998aea34299913843d12f49e81e3d45/ros/drake_ros_systems/src

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #6355. Here is what the generated Doxygen website looks like:

screenshot from 2017-06-16 12-31-01

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6356)

### CODE REVIEW

**Comment by liangfok** [comment]
+@russtedrake for feature review please. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-:-Kmki6Z2WJjRp2mtpqXt:b-wh7wot)*

**Comment by RussTedrake** [comment]
one comment below.  otherwise :lgtm:  thanks!  (caveat... i did not try building it locally).  

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/system_groups.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-KmkoQTi_JeCecgjkX4f:-KmkoQTi_JeCecgjkX4g:b5dt64t) ([raw file](https://github.com/robotlocomotion/drake/blob/e996a5f1206552098fc73e4681ddd59b00af3b17/drake/systems/system_groups.h#L1)):*
> ```objc
> /** @defgroup message_passing Message Passing
> ```

call this file message_passing.h ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-:-KmkoVoMnDO4IZ74vrht:by0426r)*

**Comment by liangfok** [comment]
+@sherm1 for platform review please. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/system_groups.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-KmkoQTi_JeCecgjkX4f:-KmkrKLcq9wAZ0ArLEpv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e996a5f1206552098fc73e4681ddd59b00af3b17/drake/systems/system_groups.h#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

call this file message_passing.h ? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-:-KmkrO6SebQeSDmcGCf0:b-1udnex)*

**Comment by jwnimmer-tri** [comment]
Suggestion: move `systems/framework/systems.h` up one level, and then add the new group declaration there.

**Comment by liangfok** [comment]
Done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-:-KmlZIdCLswFksTOE5t9:b-896fix)*

**Comment by sherm1** [comment]
I did try building it on my Xenial VM and it looks great. :lgtm:

---

Reviewed 2 of 3 files at r1, 7 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6356#-:-Kmm7YMUrY-8tqzMfHq9:b21dqq5)*

**Pull request merged**
