### PR TITLE
Refactor member/method names in symbolic expression classes

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4839)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4839#-:-KawShTIhyBb063YZ357:b-utjvo1)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4839#-:-KaxZHP6RjIdI9F5GhoI:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@ggould-tri , platform-review please.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4839#-:-Kaxbsh4QAoK8uyhJqlF:bv9ldi0)*

**Comment by soonho-tri** [comment]
FYI, this PR is related to https://github.com/RobotLocomotion/drake/issues/4824.

**Comment by ggould-tri** [comment]
This does seem much clearer.  :lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4839#-:-KaxggRbeox9EP1KIK3n:b-4k1czb)*

**Pull request merged**
