### PR TITLE
[fem] Move LinearConstitutiveModel out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586#-:-MvtRg-mEQ0-aLkjJrsl:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
+@sherm1 for platform review please. 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586#-:-MvyVrZ13C_q-bR04V5A:bamhkmw)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-MvyVK9I7bPsiWPduNyj:-MvyVK9J72Y-AB1oCZb7:bk60rkn) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L170)):*
> ```cpp
> 
> template void TestParameters<LinearConstitutiveModel<double, 1>>();
> template void TestParameters<LinearConstitutiveModel<AutoDiffXd, 1>>();
> ```

sorry for being slow, how was it possible for this to compile (or rather `linear_constitutive_model_test.cc`) without these instantiations?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-MvyVK9I7bPsiWPduNyj:-MvybN2R8O9vk7u1YVYu:b-n2i1cs) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L170)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sorry for being slow, how was it possible for this to compile (or rather `linear_constitutive_model_test.cc`) without these instantiations?
</blockquote></details>

I assume the question is "why did `linear_constitutive_model_test.cc` used to compile in dev without these instantiations".

The answer to that question is... it didn't. Notice the diff in BUILD.bazel in the dev folder. These tests were disabled there when I move the test utilities out of dev.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-MvyVK9I7bPsiWPduNyj:-Mvz66ZX-qtvgAk92rRt:bp23q9k) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L170)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I assume the question is "why did `linear_constitutive_model_test.cc` used to compile in dev without these instantiations".

The answer to that question is... it didn't. Notice the diff in BUILD.bazel in the dev folder. These tests were disabled there when I move the test utilities out of dev.
</blockquote></details>

ah, the problem is that I cannot see the diffs here but I need to go back to #16562 for context. I see now. Thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-MvyVK9I7bPsiWPduNyj:-MvzLQWMB9P_JOrRWY0I:b-dncsgj) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L170)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ah, the problem is that I cannot see the diffs here but I need to go back to #16562 for context. I see now. Thanks.
</blockquote></details>

The fact that `linear_constitutive_model_test` shows up in the BUILD file out of dev but didn't disappear from the BUILD file in dev is a slight hint :).

**Review by sherm1 — COMMENTED** [review]
Platform review checkpoint.

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586#-:-Mw2fxYR-9S-O3k214SH:bazo95y)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw2eHxJAw0sqp9WLPLa:-Mw2eHxJAw0sqp9WLPLb:bpnqb1e) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model.h#L49)):*
> ```objc
>    @pre youngs_modulus >= 0.
>    @pre -1 < poisson_ratio < 0.5. */
>   LinearConstitutiveModel(const T& youngs_modulus, const T& poisson_ratio);
> ```

nit: as before it is "Poisson's" like "Young's" (throughout)
___
*[multibody/fem/linear_constitutive_model.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw2fR2h1FmcLyAUN3L5:-Mw2fR2h1FmcLyAUN3L6:boqh12l) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model.cc#L32)):*
> ```cpp
>     the jl-th block corresponds to the value dPᵢⱼ/dFₖₗ.  */
>   /* First term. */
>   dPdF_ = lame_params.mu * Eigen::Matrix<T, 9, 9>::Identity();
> ```

nit: probably should continue to use `mu_` here since it is already set and it is used below. In any case should be consistent within this function.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: LGTM missing from assignee sherm1(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw2eHxJAw0sqp9WLPLa:-Mw2vi_QBp949fur6uSB:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: as before it is "Poisson's" like "Young's" (throughout)
</blockquote></details>

Done, thanks.
___
*[multibody/fem/linear_constitutive_model.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw2fR2h1FmcLyAUN3L5:-Mw2wjwSDupFWBZ50L16:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model.cc#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: probably should continue to use `mu_` here since it is already set and it is used below. In any case should be consistent within this function.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor comments.

> Reviewed 3 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586#-:-Mw3OdW_6TcC7eZ8QszN:bu95ptd)* status: 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model_data.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NNF8BORgIrDVNqAL:-Mw3NNF93EZ0lwAz-dP0:bwtt1pj) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model_data.h#L19)):*
> ```objc
>  See LinearConstitutiveModel for how the data is used. See
>  DeformationGradientData for more about constitutive model data.
>  @tparam_nonsymbolic_scalar T.
> ```

minor: this directive does not take an argument -- it assumes that "T" is the name

[Here](https://github.com/RobotLocomotion/drake/blob/master/doc/doxygen_cxx/Doxyfile_CXX.in#L44) is the definition.
___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NmHo2e0ooJqFrPMZ:-Mw3NmHo2e0ooJqFrPM_:b-y88j96) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L177)):*
> ```cpp
> template void TestPIsDerivativeOfPsi<LinearConstitutiveModel<AutoDiffXd, 1>>();
> 
> template void TestdPdFIsDerivativeOfP<LinearConstitutiveModel<AutoDiffXd, 1>>();
> ```

nit: indent 4 for line continuation
___
*[multibody/fem/linear_constitutive_model.h, line 56 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3Mdx2DjRoeJ7uv2NB:-Mw3Mdx2DjRoeJ7uv2NC:bhyu2yj) ([raw file](https://github.com/robotlocomotion/drake/blob/084bc92d205077a012ecce67994602e97b3e6311/multibody/fem/linear_constitutive_model.h#L56)):*
> ```objc
> 
>   /* Returns the shear modulus (Lame's second parameter) which is given by
>    `E/(2*(1+nu))` where `E` is the Young's modulus and `nu` is the Poisson
> ```

nit: Poisson's

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: 1 unresolved discussion (waiting on @amcastro-tri and @sherm1)

___
*[multibody/fem/linear_constitutive_model_data.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NNF8BORgIrDVNqAL:-Mw3QC4A5rZ8bxlF-6fl:b-dwgqr8) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model_data.h#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this directive does not take an argument -- it assumes that "T" is the name

[Here](https://github.com/RobotLocomotion/drake/blob/master/doc/doxygen_cxx/Doxyfile_CXX.in#L44) is the definition.
</blockquote></details>

Done. Although I'm only using the implied semantic here instead of rely on the actual definition because it's not doxygen comment.
___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NmHo2e0ooJqFrPMZ:-Mw3QewX1hN3u9PbPbj7:bft0j15) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L177)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: indent 4 for line continuation
</blockquote></details>

I'm not sure what the comment means. Could you say more?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: 1 unresolved discussion (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model_data.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NNF8BORgIrDVNqAL:-Mw3ZKKw4UvsfoIeiN0b:b-fpb8ls) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model_data.h#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done. Although I'm only using the implied semantic here instead of rely on the actual definition because it's not doxygen comment.
</blockquote></details>

The idea of putting Doxygen directives in code that isn't actually processed by Doxygen is to make use of programmers' already-trained understanding of these directives in documenting internal code. That's best achieved if we stick to the same patterns we would use in Doxygen-processed code, unless there is a good reason not do so.

BTW we normally wouldn't put a period after the directive either.
___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NmHo2e0ooJqFrPMZ:-Mw3YZqYAly9OKN47tW3:b-9vbhuo) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/test/constitutive_model_test_utilities.cc#L177)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure what the comment means. Could you say more?
</blockquote></details>

Uh, could have been a formatting problem on my screen in Reviewable. Part of the line wrapped. But now it looks perfect! Sorry -- retracted!

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16586)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform)

___
*[multibody/fem/linear_constitutive_model_data.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16586#-Mw3NNF8BORgIrDVNqAL:-Mw3anYl7veS-AiyvWQe:b-zhmdn0) ([raw file](https://github.com/robotlocomotion/drake/blob/41f11c123500c986a8bdc3b3bfd1735171d2b8f2/multibody/fem/linear_constitutive_model_data.h#L19)):*
> The idea of putting Doxygen directives in code that isn't actually processed by Doxygen is to make use of programmers' already-trained understanding of these directives in documenting internal code. That's best achieved if we stick to the same patterns we would use in Doxygen-processed code, unless there is a good reason not do so.

Agreed.

> BTW we normally wouldn't put a period after the directive either.
 
Yeah I inferred that from the definition you linked.

**Pull request merged**
