### PR TITLE
Add a script to control the Schunk WSG from drake_visualizer

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8391)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-:-L7jlR2TA0P8rDkYLh5c:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-:-L7k1D7X7FRjEyzr2Im3:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-:-L7kSdRZ0uA6Ts2ODkp2:buasbda)*

**Comment by sherm1** [comment]
:lgtm:, one BTW.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manipulation/schunk_wsg/schunk_buttons.py, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-L7krkhA6WYjMv7jOV3X:-L7krkhA6WYjMv7jOV3Y:be2slqa) ([raw file](https://github.com/robotlocomotion/drake/blob/5a182779296776a39f968404e8041edc644bf62b/manipulation/schunk_wsg/schunk_buttons.py#L33)):*
> ```Python
> 
> def gripperOpen():
>     sendGripperCommand(100, 40)
> ```

BTW please consider giving these magic numbers some names (and below).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-:-L7ks5Q02d8hoYuxuEnW:bwiev48)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_buttons.py, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391#-L7krkhA6WYjMv7jOV3X:-L7yNYYnCSkXrqU5QVIE:b-1c7402) ([raw file](https://github.com/robotlocomotion/drake/blob/5a182779296776a39f968404e8041edc644bf62b/manipulation/schunk_wsg/schunk_buttons.py#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider giving these magic numbers some names (and below).
</blockquote></details>

Done (also changed the closing position).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8391)*

**Pull request merged**
