### PR TITLE
Made RigidBody::model_name_ private. Renamed accessor to be get_model_name()

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #2900 by making `RigidBody::model_name_` private with get/set accessors.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2902)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2955/ and is thus ready for feature review. +@amcastro-tri for feature review since this touches `RigidBody*`.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2902#-:-KNS6cbI8jlC4o34Uc7X:-321862283)*

**Comment by amcastro-tri** [comment]
Thank you @liangfok. However I see the diffs of #2900 here. I will wait for that to get merged to review this one (and only see the new changes).

**Comment by liangfok** [comment]
SGTM. -@amcastro-tri until after #2900 is merged.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2902#-:-KNT2Dy8hJmffgb-Cynf:102393675)*

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2902#-:-KNYAOyY-Hpj3UK_XRu8:-1516772162)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 11 of 15 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2902#-:-KNYLx3Fflq1JZDQJiLE:1058782226)*

**Comment by liangfok** [comment]
Thanks @sherm1. Waiting on @amcastro-tri for feature review.

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 11 of 15 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2902#-:-KNYS_pDOgzH-oFGV4g1:1417088721)*

**Pull request merged**
