### PR TITLE
doc: Update Markdown to ensure Jekyll preview can work

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Fix some minor styling

Towards #14657

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14659)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok) -- bash on regardless.

(I'll leave it to your discretion when to merge this, though.)

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14659#-:-MTkTNhj1oJB4cwhVrzW:bkqxwr9)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @EricCousineau-TRI)

___
*[doc/_release-notes/v0.18.0.md, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14659#-MTkTDzU0ZfW1mj_Tz1p:-MTkTDzU0ZfW1mj_Tz1q:b3ntrfj) ([raw file](https://github.com/robotlocomotion/drake/blob/664260f20c6c4798268ecd7ae623be3ae0384728/doc/_release-notes/v0.18.0.md#L8)):*
> ```Markdown
> 
> <div class="warning" markdown="1">
> On macOS, Drake now only supports Python 3.8.  Users **must** read
> ```

nit Did you mean to add "now" here?  It came over from the v0.17 text, but was not in v0.18 text originally.
___
*[doc/_release-notes/v0.19.0.md, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14659#-MTkTL1wDxFDmGnnKYwq:-MTkTL1x-Ajlhl1wfDaO:b-ctsyiq) ([raw file](https://github.com/robotlocomotion/drake/blob/664260f20c6c4798268ecd7ae623be3ae0384728/doc/_release-notes/v0.19.0.md#L8)):*
> ```Markdown
> 
> <div class="warning" markdown="1">
> On macOS, Drake now only supports Python 3.8.  Users **must** read
> ```

nit Did you mean to add "now" here?  It came over from the v0.17 text, but was not in v0.19 text originally.

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! I think I can merge it whenevs - will try hehe

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14659#-:-MTkToTN2hnpnTK1eXqS:b6d3da)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.18.0.md, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14659#-MTkTDzU0ZfW1mj_Tz1p:-MTkUBA29kz4R_Zn0NAt:b-376vyo) ([raw file](https://github.com/robotlocomotion/drake/blob/664260f20c6c4798268ecd7ae623be3ae0384728/doc/_release-notes/v0.18.0.md#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Did you mean to add "now" here?  It came over from the v0.17 text, but was not in v0.18 text originally.
</blockquote></details>

Done. Good catch!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 9 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14659)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds

**Pull request merged**
