### PR TITLE
add (almost all) missing py scenegraph inspector bindings

### PR DESCRIPTION
**Pull request by RussTedrake**
---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for both reviews, please, in case you disagree with my use if `id` instead of `frame_id`.  I aimed for parity with c++, not with the existing bindings.  See #14258 .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKinUi2-7XrGBltYYUR:b-1vqkzw)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for both reviews, and -@ericcousineau-tri since we're gated on #14258 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKkVPVUD4beyBBYpoqc:b-lwvi7o)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKl1zWJ2g9p3-FbjmGb:-MKl1zWJ2g9p3-FbjmGc:b-qx6f1e) (no related file):*
Is it  OK if this lands after Sean's PR?
https://github.com/RobotLocomotion/drake/pull/14247

That may simplify order of operations, since #14258 is also relevant there.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've advocated a plan of attack and would suggest that categories 1 and 2 ([documented here](https://github.com/RobotLocomotion/drake/issues/14258#issuecomment-718219774)) should be resolved in this PR.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKl6XZU-WN1YntdHlzw:b7c5rmv)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKl1zWJ2g9p3-FbjmGb:-MKl6PDD1C5COB0Ret3O:by7yj3x) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it  OK if this lands after Sean's PR?
https://github.com/RobotLocomotion/drake/pull/14247

That may simplify order of operations, since #14258 is also relevant there.
</blockquote></details>

I think it makes sense for this to go ahead and handle *that*. I'll handle the merge conflict, and that small patch is better suited here.

---
___
*[bindings/pydrake/test/geometry_test.py, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKl7jmn6y-WyKJPx7pe:-MKl7jmn6y-WyKJPx7pf:b-bacsn5) ([raw file](https://github.com/robotlocomotion/drake/blob/9e08b052fc7eb301cb84a4a27112e2df2a4b1a06/bindings/pydrake/test/geometry_test.py#L122)):*
> ```Python
>         self.assertEqual(inspector.GetFrameId(global_geometry), global_frame)
>         self.assertEqual(
>             inspector.GetName(geometry_id=global_geometry), "sphere1")
> ```

nit I note that we don't invoke `GetShape()` in this test anywhere.  Feel like adding that while we're here?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKl1zWJ2g9p3-FbjmGb:-MKlBfeSCvfpvjqNBAQl:bl00cdx) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think it makes sense for this to go ahead and handle *that*. I'll handle the merge conflict, and that small patch is better suited here.
</blockquote></details>

OK SGTM!

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW @russtedrake If you're slammed, I can finish this off (re: the recommendations). I was planning on doing the follow-up PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKp-I9m9AHUU447Pn16:b-rc9443)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
hoping i got it right.  ptal.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKqU1Gg4Aq2bp1Wabrz:b-pq2duj)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/test/geometry_test.py, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKl7jmn6y-WyKJPx7pe:-MKqIEsJ9eOPmmmrFT-c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e08b052fc7eb301cb84a4a27112e2df2a4b1a06/bindings/pydrake/test/geometry_test.py#L122)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit I note that we don't invoke `GetShape()` in this test anywhere.  Feel like adding that while we're here?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Almost there.  See the notes. Also, I've created a merge conflict for you. My `DrakeVisualizer` PR merged and already touched the `Get*Properties()` methods (#14247).

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKqX_VOAmKbfbogQEyL:b-kjsxra)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 460 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqWVjr-fvESQTvkk_y:-MKqWVjr-fvESQTvkk_z:bgre4l1) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L460)):*
> ```cpp
>         .def("GetSourceName", &Class::GetSourceName, py::arg("id"),
>             cls_doc.GetSourceName.doc)
>         .def("NumFramesForSource", &Class::NumFramesForSource, py::arg("id"),
> ```

nit `source_id`
___
*[bindings/pydrake/geometry_py.cc, line 462 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqWXFT5XvWq3ulv3Kz:-MKqWXFT5XvWq3ulv3L-:bf0md1j) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L462)):*
> ```cpp
>         .def("NumFramesForSource", &Class::NumFramesForSource, py::arg("id"),
>             cls_doc.NumFramesForSource.doc)
>         .def("FramesForSource", &Class::FramesForSource, py::arg("id"),
> ```

nit: `source_id`
___
*[bindings/pydrake/geometry_py.cc, line 473 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqW_qX-pUooSU6tuS_:-MKqW_qX-pUooSU6tuSa:b-f3u2gj) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L473)):*
> ```cpp
>             overload_cast_explicit<const std::string&, FrameId>(
>                 &Class::GetOwningSourceName),
>             py_rvp::reference_internal, py::arg("id"),
> ```

nit: `frame_id`
___
*[bindings/pydrake/geometry_py.cc, line 480 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqWcQjEjvojX_roWJB:-MKqWcQjEjvojX_roWJC:bx2fdpb) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L480)):*
> ```cpp
>             py_rvp::reference_internal, py::arg("frame_id"),
>             cls_doc.GetName.doc_1args_frame_id)
>         .def("GetFrameGroup", &Class::GetFrameGroup, py::arg("id"),
> ```

nit `frame_id`
___
*[bindings/pydrake/geometry_py.cc, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqWf577eFDaUdmMxj4:-MKqWf577eFDaUdmMxj5:b-f3u2gj) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L483)):*
> ```cpp
>             cls_doc.GetFrameGroup.doc)
>         .def("NumGeometriesForFrame", &Class::NumGeometriesForFrame,
>             py::arg("id"), cls_doc.NumGeometriesForFrame.doc)
> ```

nit: `frame_id`
___
*[bindings/pydrake/geometry_py.cc, line 485 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqWhIW8NIN3HPhmTs2:-MKqWhIW8NIN3HPhmTs3:bx2fdpb) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L485)):*
> ```cpp
>             py::arg("id"), cls_doc.NumGeometriesForFrame.doc)
>         .def("NumGeometriesForFrameWithRole",
>             &Class::NumGeometriesForFrameWithRole, py::arg("id"),
> ```

nit `frame_id`
___
*[bindings/pydrake/geometry_py.cc, line 527 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqX2Jl2I6OY9lnsYVk:-MKqX2Jl2I6OY9lnsYVl:b-pxzug4) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/bindings/pydrake/geometry_py.cc#L527)):*
> ```cpp
>             py_rvp::reference_internal, py::arg("geometry_id"),
>             cls_doc.GetPerceptionProperties.doc)
>         .def("CollisionFiltered", &Class::CollisionFiltered, py::arg("id1"),
> ```

nit `geometry_id1` and `geometry_id2`
___
*[geometry/scene_graph_inspector.h, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqVFY_5pfNcbzlNE58:-MKqVFY_5pfNcbzlNE59:b8gpx0a) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/geometry/scene_graph_inspector.h#L155)):*
> ```objc
>   //@{
> 
>   /** Reports `true` if the given `source_id` maps to a registered source.  */
> ```

nit You've included changes to two methods that are classified as "category 3" in the issue: `SourceIsRegistered`, `GetSourceName`. The only issue with that is that you have *introduced* the disagreement of parameter names (now `id` in python and `source_id` in C++). Probably better to undo those changes and defer to the follow up PR to clean them up as per spec.

**Review by RussTedrake — COMMENTED** [review]
oops.  I had made those changes, but they were sitting unsaved in my editor.   :facepalm:  apologies.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKr7j7g4qygW8DzscBM:b-on7xfp)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[geometry/scene_graph_inspector.h, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKqVFY_5pfNcbzlNE58:-MKr91Yi6QU2LurvI2zO:bk3qr8v) ([raw file](https://github.com/robotlocomotion/drake/blob/a0e7a8383be986f6c7a07deaf4c819d218db7626/geometry/scene_graph_inspector.h#L155)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit You've included changes to two methods that are classified as "category 3" in the issue: `SourceIsRegistered`, `GetSourceName`. The only issue with that is that you have *introduced* the disagreement of parameter names (now `id` in python and `source_id` in C++). Probably better to undo those changes and defer to the follow up PR to clean them up as per spec.
</blockquote></details>

Done.  I had knowingly ad-libbed, reasoning that no harm would come of having this change and it takes us closer to the goal.  but i'll stick to the script.

**Review by SeanCurtis-TRI — COMMENTED** [review]
One last piece of residue left over (`SourceIsRegistered` in `geometry_py.cc`) and Reviewable would like you to respond to the nits.  :)

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKrTbWk80Wgp1WIy8d3:b-tq5psy)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 460 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14259#-MKrT3e-E2eicAvpeWCD:-MKrT3e-E2eicAvpeWCE:bt2h4ze) ([raw file](https://github.com/robotlocomotion/drake/blob/48322d8dda6011f218f6bb3531cec9a81feaaf8a/bindings/pydrake/geometry_py.cc#L460)):*
> ```cpp
>         // Sources and source-related data.
>         .def("SourceIsRegistered", &Class::SourceIsRegistered,
>             py::arg("source_id"), cls_doc.SourceIsRegistered.doc)
> ```

nit: This shouldn't be changed. It should state "id" for now.

**Review by RussTedrake — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKtw_5w9UCisgGy-r_L:b-896fix)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14259#-:-MKtybHsBQRw0amkfBXb:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
