### PR TITLE
Update versions of ccd, fcl and octomap. Avoid their installation and hide their binary symbols from libdrake

### PR DESCRIPTION
**Pull request by j-rivero**
~~Following @stonier [instructions](https://github.com/RobotLocomotion/drake/issues/7412#issuecomment-342547439) this PR changes the build system to use the latest commit in the recently created fork.~~

~~The automated testing has been waiting in the OSRF buildfarm for some hours but it should appear at: https://build.osrfoundation.org/job/drake-ci-pr_any-xenial-amd64/42/ when launched.~~

**Update 11/28**:

The PR affects to the libccd, libfcl and octomap versions present in Drake: 
 
  * **libccd** version has been updated to current tip in upstream repo from current v2 in Drake ([full list of changes](https://github.com/danfis/libccd/compare/v2.0...master)) The list shows that most of the changes are related to build system. As far as I can see, https://github.com/danfis/libccd/pull/14 is the only PR affecting features behaviour.

  * **octomap** has been updated from v1.7.2 to v1.8.1 ([full list of changes](https://github.com/OctoMap/octomap/compare/v1.7.2...v1.8.1) and [changelog](https://github.com/OctoMap/octomap/blob/v1.8.1/octomap/CHANGELOG.txt)) which is the version in ROS Kinetic.

 * **libfcl** has been updated from an upstream commit done after 0.5 release done in Jan 2017 to current master ([full list of changes](https://github.com/flexible-collision-library/fcl/compare/06d48b3b6f3605b8caf119d5208d8156eb64fe0d...master)). Most of the changes seems related to build system and tests but there are at least two of them affecting code behaviour: [correct nearest points from distance()](https://github.com/flexible-collision-library/fcl/pull/215) and [problem in signed distance for the geometry shape](https://github.com/flexible-collision-library/fcl/commit/cd2c6a111c90c59d023d1a67942ce91168c703d1)

All installations of the three libraries have been removed from the code. The binary symbols are totally removed from the public ABI for libfcl and libccd (using the visibility mechanism implemented upstream). Octomap symbols are still in there but should match the ones present in ROS. This PR does not fix the case of mixing libdrake with other octomap versions different than 1.8.1 in a third party software.

Tested in the OSRF buildfarm: https://build.osrfoundation.org/view/All/job/drake-ci-pr_any-xenial-amd64/76/consoleFull

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7417)

### CODE REVIEW

**Comment by stonier** [comment]
*[WORKSPACE, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-KyO-uVOHRXjIXjUrd2l:-KyO-uVOHRXjIXjUrd2m:bf4kj7c) ([raw file](https://github.com/robotlocomotion/drake/blob/8ec37efbf60c8d11b1666c770eca2722c2a92026/WORKSPACE#L195)):*
> ```Python
>     repository = "RobotLocomotion/libccd",
>     commit = "64f02f741ac94fccd0fb660a5bffcbe6d01d9939",
>     sha256 = "d028cf9ee11b996c71589a5c78590a5e2edc2df2ef7d3915daa250e9856ea6c1",  #noqa
> ```

Missing space causing havoc with the bazel codestyle check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by jamiesnape** [comment]
Are upstream not responsive to patches anymore?

**Comment by j-rivero** [comment]
> Are upstream not responsive to patches anymore?

Last PR merge is from May and there were only two merges during this year, the repo seems not to have too much activity. We can try to ask Daniel Fiser if he needs help maintaining the repo, if TRI is interested into getting the changes quickly into upstream.

**Comment by jamiesnape** [comment]
I had no issues with getting some changes in quickly a while back. There are just not too many people making PRs, that is all.

**Comment by jwnimmer-tri** [comment]
With my platform reviewer hat on, indeed I would want to see affirmative evidence of upsteam being intransigent (i.e., either ignoring or rejecting pull requests) before I approved using a RobotLocomotion-specific fork.

**Comment by j-rivero** [comment]
Please ignore the last two commits. I will check with @stonier if we want to use the fork or wait for upstream to incorporate changes.

**Comment by stonier** [comment]
The fork is not because upstream is necessarily intransigent.

My usual process through years of working with many open source projects whilst trying to maintain velocity on a product has been:

* fork
* patch
* test
* sync local workspaces to the fork so we get more extensive testing of the patch
* send upstream PR
* resync local workspaces to upstream (eventually)
* delete fork if it is unused

Sending upstream a PR might often move up the list if I want to elicit feedback from upstream earlier.

Resync might occur much later if I want to delay handling/testing against additional updates coming in from elsewhere in the interim. If so, pull the review modifications back into the fork.

The primary point here is to not bottleneck development and allows more extensive local testing against the changes.

Do we have any reason to bottleneck development while we wait an indeterminate amount of time for review?

**Comment by jamiesnape** [comment]
About two years ago almost everything that was external was on a fork and as projects diverged we spent inordinate amounts of time to get back on master. We have almost done that save for libbot and pybind11. The pybind11 example is reasonable one as that diverged and we have had to re-write everything and it has taken probably four times as long as it would have. Forks also do not exist in a vacuum that prevents others using that fork. In the other remaining fork that we have libbot2, other projects picked up the fork, nothing ever got upstreamed, and removing the fork would cause much pain, so we are probably stuck with it, which is unfortunate.

**Comment by stonier** [comment]
The problem with divergence is not the fork itself. It is in the diligence by the group managing the fork. Whilst we we were building a fleet of robots with a software ecosystem far vaster than Drake, we typically had 10-20 forks of open source software at any time. The prospect of maintaining those in perpetuity was enough to motivate changes going back upstream and required little nagging and only minimal guidance from myself.

When you work on the bleeding edge with deadlines and require critical fixes there is no other way. Perhaps the only thing that is permitting it here is that Drake development is meandering along with no critical deadlines. At some point this will/should become necessary and we should have a habit for  good practice then.

**Comment by jwnimmer-tri** [comment]
Jamie's history is on point.  I think there is definitive historical evidence of developer drag from maintaining and (trying to) merge up a RobotLocomotion fork for all time.

To the question of bottlenecks, I have no goal of slowing down development.  A personal fork of Drake can refer to a personal fork of ccd.  A shared feature branch of Drake can point to a shared feature branch of ccd.  All of that can get CI testing.  I don't think there is friction there.

In the unusual and to-be-shunned event that manual testing is required, interested parties can check out and explore the branch.  But really, CI is king.  If CI is passing, that should really be good enough.  If its not, then we need to enhance CI.  (At some point, UIs and things aren't covered by CI, but relatively few of our externals relate to UIs; CCD certainly does not.)

In the event that we need a small tweak on a few-hours timeline instead of few-days that upstream might be to accept a PR, we have allowed Drake to point off-master of upstream in the past, and I think we could do so again.  In those cases, there is an upstream PR filed to point at, and if its not merged in a timely manner _then_ we can react and use off-master of upstream, while reviewing the patch ourselves.

**Comment by stonier** [comment]
(once again) there is a universe outside of Drake and it is these people that will be bottlenecked.

**Comment by jwnimmer-tri** [comment]
Can you expand on that?  I don't understand.  How does having a RL fork of CCD help potential Drake contributors or users?

**Comment by stonier** [comment]
The goal of this work is to enable Drake-ROS compatibility. There are groups that need to create their own plans around this and have even started work on it already. I would prefer to give them a deterministic ETA on when they can expect it to arrive rather than 'unknown pending assistance from people outside our group'.

I would also like to see this get more rigorous testing sooner than later.

Managing resync with upstream is not a difficult, nor time consuming process so long as you do not let it slide. I have done this many, many times in the past.

**Comment by jwnimmer-tri** [comment]
> 'unknown pending assistance from people outside our group'.

This is a strawman argument.  I said that if upstream is too slow to get things onto master, we can fall back to using our own fork, either in the short term for a hotfix, or to a RL fork if its an ongoing pain point.  My request (and I think Jamie's) is that we treat that as a second-best choice, and at least try to upstream changes immediately.

There is an argument for doing upstream PRs in parallel to Drake moving ahead with the external edits, to reduce development long poles, but we have to do all of the same work anyway so the total effort is similar, possibly more when dealing with parallelization.  And the difference will be minimal when upstream is fast.

> I would also like to see this get more testing ...

What testing can or cannot happen is orthogonal to our git structure choices.

**Comment by stonier** [comment]
> What testing can or cannot happen is orthogonal to our git structure choices.

If this can be integrated and picked up by users, they are going to discover unanticipated problems earlier rather than later. This, in my experience, has saved having to make repeat upstream patches.

**Comment by jwnimmer-tri** [comment]
That is certainly a possibility.  I am willing to take that gamble and trust our CI.

**Comment by jamiesnape** [comment]
> My request (and I think Jamie's) is that we treat that as a second-best choice, and at least try to upstream changes immediately.

Yes, I concur.

**Comment by stonier** [comment]
@j-rivero if it hasn't been picked up by Monday next week (don't have high hopes given that their a 1+ month old pull requests hanging) then let's merge here and review next steps with respect to upstream.

**Comment by jwnimmer-tri** [comment]
The only meaningful effect of this PR is to pull in ~30-40 new commits from upstream.  If we change this PR to point at upstream github (danfis/libccd at commit 64f02f741ac94fccd0fb660a5bffcbe6d01d9939), it will have the same effect as currently, and could go in immediately.

**Comment by jamiesnape** [comment]
> @j-rivero if it hasn't been picked up by Monday next week (don't have high hopes given that their a 1+ month old pull requests hanging) then let's merge here and review next steps with respect to upstream.

The more pressing problem is that PR breaks two thirds of their builds. Not necessarily anything to do with intransigence.

**Comment by stonier** [comment]
> The more pressing problem is that PR breaks two thirds of their builds. Not necessarily anything to do with intransigence.

Aye, agreed.

**Comment by j-rivero** [comment]
> The more pressing problem is that PR breaks two thirds of their builds. Not necessarily anything to do with intransigence.

My PR was merged upstream and the visibility support is now in ccd repository. The ccd maintainer contacted with me last week and I think that the situation is good enough to try to avoid the use of the fork and manage patches upstream.

I've modified this PR to use latest commit on upstream repository. The [list of changes since v2](https://github.com/danfis/libccd/compare/v2.0...master) mostly contains changes to the build system and documentation. The only change in code was done in https://github.com/danfis/libccd/pull/14.

This PR removes the generation of dynamic libraries for ccd and fcl. Removes all cmake support and installation of libccd headers. I've [tested the compilation and execution](https://build.osrfoundation.org/job/drake-ci-pr_any-xenial-amd64/70/consoleFull) of third party code (drake-shambala), no problems appeared. In the test build there is also a check for fcl and ccd (search for `grep ' ccd'`) binary symbols. fcl symbols are still there (removed in a new PR) but ccd are no longer found in libdrake.

**Comment by jamiesnape** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/ccd/ccd.BUILD.bazel, line 68 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-Kz4Cd19rZzLPJfTaELl:-Kz4Cd1AZPl3_6xriDU2:b-4emmws) ([raw file](https://github.com/robotlocomotion/drake/blob/1055358c73656dd69f74c1389765d13e8edd0035/tools/workspace/ccd/ccd.BUILD.bazel#L68)):*
> ```
>     hdr_dest = "include/ccd",
>     hdr_strip_prefix = ["**/"],
>     docs = ["BSD-LICENSE"],
> ```

BTW We are still using the code, so do we still need to install the license?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by jamiesnape** [comment]
Can you update the PR title and description to something more descriptive now that libccd is not being forked and this also touches FCL. I would also argue that #7492 should be rolled into this PR.

**Comment by jamiesnape** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/workspace/fcl/fcl.BUILD.bazel, line 79 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-L-7jV7OQYXvpbMnt4WV:-L-7jV7OQYXvpbMnt4WW:b-6x8ihx) ([raw file](https://github.com/robotlocomotion/drake/blob/a833ead84edbf8846e401bd57620f144fb69ae18/tools/workspace/fcl/fcl.BUILD.bazel#L79)):*
> ```
>     hdr_strip_prefix = ["include/fcl"],
>     guess_hdrs = "PACKAGE",
>     docs = ["LICENSE"],
> ```

Still need to install license?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by j-rivero** [comment]
After upgrading fcl [one of the tests is failing](https://drake-cdash.csail.mit.edu/testDetails.php?test=16214274&build=920440):

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from FCLModelTest
[ RUN      ] FCLModelTest.SphereSphereDistance
drake/multibody/collision/test/fcl_model_test.cc:39: Failure
      Expected: -5.0
      Which is: -5
To be equal to: distance_result.min_distance
      Which is: -4.8559909986053462
[  FAILED  ] FCLModelTest.SphereSphereDistance (0 ms)
[----------] 1 test from FCLModelTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FCLModelTest.SphereSphereDistance
```
I can not say if the difference in the value makes sense and we need to update the value in the test or it is a regression. In our meetings with @stonier he proposed to @SeanCurtis-TRI in order to evaluate the changes in FCL (some infomration is in the description of this pull request) and he might be able to provide feedback on this failure too.

**Comment by jamiesnape** [comment]
I seem to remember https://github.com/flexible-collision-library/fcl/commit/cd2c6a111c90c59d023d1a67942ce91168c703d1 causing issues once before when I was working with FCL, though I forget where.

**Comment by SeanCurtis-TRI** [comment]
In this particular case, @avalenzu may have more particular insight.

**Comment by j-rivero** [comment]
> BTW We are still using the code, so do we still need to install the license?

Good catch. I think that we need to install them yes. I've fixed the PR and the licenses for ccd, fcl and octomap are now being installed.

**Comment by j-rivero** [comment]
> In this particular case, @avalenzu may have more particular insight.

Thanks @SeanCurtis-TRI . @avalenzu anything I can do to help you to reproduce the error? Thanks.

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

Sorry I missed this in the GH noise. I haven't been able to reproduce this on my machine.

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L0v2-GTSaRBvYQJ88Ma:b-95q3kx)*

**Comment by avalenzu** [comment]
I'll take a closer look at this tomorrow if the `linux-xenial-gcc-bazel-experimental` job fails again.

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L0v4zR-CzQScbv-ha4D:b-p69zwo)*

**Comment by avalenzu** [comment]
OK, I've been able to reproduce this locally (I was mistakenly running `model_test` rather than `fcl_model_test` earlier).   This does appear to be a regression due to flexible-collision-library/fcl@cd2c6a1. Prior to that commit, the `fcl::distance()` function would perform a penetration depth query in order to compute a signed distance for intersecting geometries. After that commit (and the subsequent fixes in flexible-collision-library/fcl@5230025) it performs the penetration depth query only when using the INDEP solver. When using the LIBCCD solver (as in `fcl_model_test`) it does ... something else. That "something else" returns the erroneous values we're seeing. We aren't actually using `fcl::distance()` in our codebase yet (outside of this test), so my inclination would be to remove `fcl_model_test` (we do have test coverage of FCL's collision queries in `model_test`). The behavior noted here can be added to the list of things that need to be addressed in #7656 . Does that sound reasonable @seancurtis-tri, @j-rivero, and @jamiesnape (since your name is on the TODO's in `fcl_model_test`) ?

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L0zQGpsY65wGb0fi6E5:b-mavfx2)*

**Comment by SeanCurtis-TRI** [comment]
@avalenzu I can agree with that. I think I'll be spending *a lot* more time in FCL in the coming quarter....

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L1r_mFEDwrilxMWIb1C:biyk8dy)*

**Comment by j-rivero** [comment]
> Does that sound reasonable @SeanCurtis-TRI, @j-rivero, and @jamiesnape (since your name is on the TODO's in fcl_model_test) ?

The reasoning makes sense to me. I've removed the test, let's see the result of the CI. Thanks Andres.

**Comment by j-rivero** [comment]
The CI looks good now. I've reported the bug upstream https://github.com/flexible-collision-library/fcl/issues/244

**Comment by stonier** [comment]
@jose Ready for feature review? @jamiesnape is a good candidate.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L2M1twzyOiiOnuaRZWJ:bqg2qmt)*

**Comment by j-rivero** [comment]
> @jose Ready for feature review? @jamiesnape is a good candidate.

Ready. Excuse me if the question is to stupid but Do I need to interact with `Reviewable` or wait until @jamiesnape comments or actions?

**Comment by jamiesnape** [comment]
> Ready. Excuse me if the question is to stupid but Do I need to interact with Reviewable or wait until @jamiesnape comments or actions?


You should assign me via the GitHub interface (I have self-assigned now).

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 13 files at r4, 5 of 12 files at r5, 3 of 5 files at r7, 2 of 6 files at r8, 2 of 3 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/generate_export_header.bzl, line 30 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-L2QGSW98yGXQfc05Q6k:-L2QGSW98yGXQfc05Q6l:b-dhrg25) ([raw file](https://github.com/robotlocomotion/drake/blob/73e0b49fbd81453939ea61b0b2fefa89833bfddc/tools/workspace/generate_export_header.bzl#L30)):*
> ```Python
>         "#endif",
>         "",
>         "#ifndef %s_EXPORT" % ctx.attr.deprecated_macro_name,
> ```

Should `_EXPORT` be hardcoded? It probably should match the naming convention of `ctx.attr.export_macro_name`.

---

*[tools/workspace/fcl/fcl.BUILD.bazel, line 60 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-L2QHCtniJQhtT_2q5ZJ:-L2QHCtniJQhtT_2q5ZK:b-v8ftkl) ([raw file](https://github.com/robotlocomotion/drake/blob/73e0b49fbd81453939ea61b0b2fefa89833bfddc/tools/workspace/fcl/fcl.BUILD.bazel#L60)):*
> ```
>         ":config",
>         ":fcl_h_genrule",
>         "include/fcl/export.h",
> ```

This is not captured by the glob?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L2QHclMfjWpNkz3Gmeg:bnfp4nl)*

**Comment by j-rivero** [comment]
> tools/workspace/generate_export_header.bzl, line 30 at r9 (raw file):
> 
>             "#endif",
>             "",
>             "#ifndef %s_EXPORT" % ctx.attr.deprecated_macro_name,
> 
> Should _EXPORT be hardcoded? It probably should match the naming convention of ctx.attr.export_macro_name.

Good catch. The problem is that ctx.attr.export_macro_name default value include the name of the library so we can not use it directly. What I did in https://github.com/RobotLocomotion/drake/pull/7417/commits/d6490283080307ce909eb8b080b269b47609be13 was to implement `ctx.attr.export_deprecated_macro_name` so it can customized and defaults to the same value that the cmake export header function.

> tools/workspace/fcl/fcl.BUILD.bazel, line 60 at r9 (raw file):
> 
>             ":config",
>             ":fcl_h_genrule",
>             "include/fcl/export.h",
> 
> This is not captured by the glob?

Looking at the code I agree with you but for some reason I'm getting [this error](https://build.osrfoundation.org/view/All/job/drake-ci-pr_any-xenial-amd64/93/consoleFull#-9656530066185e384-b484-4c9d-8597-4b38c89303d8
) if I remove the explicit line and just leave the glob.

**Comment by jamiesnape** [comment]
I see, it is because it is a generated file. Either pass the label instead of the file name or add a comment.

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
:LGTM:
+(status: curate commits before merging) 

---

Reviewed 2 of 13 files at r4, 4 of 12 files at r5, 3 of 5 files at r7, 2 of 6 files at r8, 2 of 3 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-:-L2VinNfQPaxHLYKyouZ:bv5uey7)*

**Comment by j-rivero** [comment]
> I see, it is because it is a generated file. Either pass the label instead of the file name or add a comment.

Comment added in e152671b44c81b79616521b0ebf679cd2fe735c1

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/fcl/fcl.BUILD.bazel, line 54 at r11](https://reviewable.io:443/reviews/robotlocomotion/drake/7417#-L2W9e3nVdACP-AG3q1z:-L2W9e3nVdACP-AG3q2-:bmf2aa) ([raw file](https://github.com/robotlocomotion/drake/blob/e152671b44c81b79616521b0ebf679cd2fe735c1/tools/workspace/fcl/fcl.BUILD.bazel#L54)):*
> ```
> 
> # The globbed srcs= and hdrs= matches upstream's explicit globs of the same.
> # fcl/export.h it is a generated file so it is not automatically included by
> ```

BTW typo: drop "it".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by j-rivero** [comment]
> BTW typo: drop "it".

ouch, thanks b508052f28435eca712788410dd4dacbd1a58fa0

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7417)*

**Pull request merged**
