### PR TITLE
Adds support for systems with their dynamics in implicit form (specif…

### PR DESCRIPTION
**Pull request by RussTedrake**
…ically, the "mass matrix form").  And a first example of using it in AcrobotPlant.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12828)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@sherm — since it’s friday i wanted to open this for discussion.  I will clean up the eigen ptrs, add the diagram implementation, add tests, etc... but wanted to check on the basic design first.

**Comment by RussTedrake** [comment]
(Obviously a goal would be to have multibody plant implement this method, too)

**Comment by sherm1** [comment]
@RussTedrake can you say more about what you're aiming to accomplish with this? MBP can already formulate a system in implicit form -- the generalized forces returned by inverse dynamics are the implicit equation residual = M vdot  + Cv - rhs.

cc @amcastro-tri

**Comment by RussTedrake** [comment]
I am trying to write code that evaluates systems, but exposes the fact that some of our most important systems (e.g. MBPs) have extra structure.  

For example, I could write 
`RegionOfAttraction(MultibodyPlant&, Context&)`
but that wouldn't be very useful -- i would only be able to study passive systems.  What I want is to evaluate the region of attraction of an MBP in closed-loop (e.g. a diagram) with a feedback controller, and understand it's region of attraction.   But I need to get the closed-loop dynamics in their implicit form because the explicit form is not polynomial (nor available via symbolic).

**Comment by sherm1** [comment]
Per discussion with @RussTedrake we want to expose an implicit form of the System (Diagram) equations. Currently the _explicit_ form that we support is:
```
ẋc = fₑ(t,p,u,x)
```
The System-level API that corresponds to is `CalcTimeDerivatives(context, &xcdot)` where time t, parameter values p, input port values u, and the current state x (=[xc xd xa]) are taken from the context. (At the Diagram level the inputs u come from setting fixed values for the inputs.)

The corresponding implicit form would look like this:
```
0 = fᵢ(t,p,u,x; ẋcₑₛₜ)
```
An implementation must return the residual, that is, the value of fᵢ() given an estimate ẋcₑₛₜ so that a solver can drive that residual to zero. So the System-level API would be something like 
`CalcImplicitEquations(context, xcdot_estimate, &residual)`. As before t,p,u,x come from the Context. The residual must have the same size as xc, but doesn't necessarily correspond elementwise to state variables.

We can provide a default implementation for the implicit form: `fᵢ = ẋcₑₛₜ − fₑ`.

@RussTedrake what do you think of that API for your purposes?

**Comment by RussTedrake** [comment]
@sherm1 -- this is great.  How about
```
CalcTimeDerivativesImplicit(context, xcdot, &residual)
```
for two reasons.  
- i've removed the "estimate" connotation from xcdot; that makes sense for your use case, but not mine.
- we should have "TimeDerivatives" in the method name because we can also write the discrete updates in implicit form (and might want to soon)... defined with a similar `f(context, xn) = 0`.

Shall I close this PR and open an issue?  Are you offering to write the code?  ;-)

**Comment by sherm1** [comment]
Yes, please open an issue. I'll take a shot at the code this week and have you feature review (very quiet around here anyway!). I want to attempt the modern version of the LeafSystem overload-free function spec.

**Pull request closed without merging**
