### PR TITLE
[parsing] Rename detail_scene_graph ==> detail_sdf_geometry

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Marginally relevant to: #16229

Whatever sense the orginal name made, it no longer expresses what is in
the module, nor how it differs from other modules here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 
+@joemasterjohn for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610#-:-Mw3anau7NX6MMKaefmd:b6cqf2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by rpoyner-tri — COMMENTED** [review]
FYI @jwnimmer-tri  -- any objections?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610#-:-Mw4kLs2EwTzwBNQR8GI:b-ah46zf)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Comment by jwnimmer-tri** [comment]
Seems reasonable.

**Review by rpoyner-tri — COMMENTED** [review]
needs rebase -- working.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610#-:-Mw7SDvBEySs4pLAA4gv:b-emnw5z)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: +@ericcousineau-tri for platform review, please.

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610#-:-MwPbJtH9CWgZw_Fkao_:b5fdysl)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16610#-:-MwRhyYO8ID6tBOITVZn:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @rpoyner-tri)

**Pull request merged**
