### PR TITLE
direct trajectory optimization cleanup

### PR DESCRIPTION
**Pull request by RussTedrake**
remove all methods in direct trajectory optimization that accept a cost/constraint without an explicit declaration of the associated variables.  these methods assumed the user understood the correct variable order in the mathematical program, which is far too fragile.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6837)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-:-KrTs3Uu9WvrT6mCOwIr:b-81zjv5)*

**Comment by hongkai-dai** [comment]
:lgtm: besides one minor comment. +@jwnimmer-tri for platform review please.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrXPuIl8mI4SbDlY6h7:-KrXPuIl8mI4SbDlY6h8:bjvyr21) ([raw file](https://github.com/robotlocomotion/drake/blob/b10ba2456ffafe141a81bd60114918b8cdc49f69/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L89)):*
> ```cpp
>     for (int t = 0; t < N_; ++t) {
>       guess_u.segment(num_inputs_ * t, num_inputs_) =
>           traj_init_u.value(timespan_init[t]);
> ```

This line is redundant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-:-KrXTiY2enPImPyoqr8u:b-8z4jcg)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrXPuIl8mI4SbDlY6h7:-KrXbpdB_sCgizOMTEiN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b10ba2456ffafe141a81bd60114918b8cdc49f69/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L89)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This line is redundant?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_swing_up.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYOFrQqY0dN3GlksMK:-KrYOFrQqY0dN3GlksML:b-4b4mhk) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/examples/acrobot/acrobot_swing_up.cc#L30)):*
> ```cpp
>     systems::DircolTrajectoryOptimization* dircol) {
> 
>   // Current limit for MIT's acrobot is 7-9 Amps, according to Michael Posa.
> ```

FYI With the intervening blank, line this comment versus the kConstant = 8 below are ever so slightly confusing.  I easily figured it out quickly though, so no defect.

---

*[drake/examples/pendulum/test/pendulum_trajectory_optimization_test.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYOiZOLHzgCCX0ODr9:-KrYOiZOLHzgCCX0ODrA:b-6n8smn) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/examples/pendulum/test/pendulum_trajectory_optimization_test.cc#L51)):*
> ```cpp
>       CompareMatrices(x0, states.col(0), 1e-10, MatrixCompareType::absolute));
>   EXPECT_TRUE(CompareMatrices(xG, states.col(kNumTimeSamples - 1), 1e-10,
>                               MatrixCompareType::absolute));
> ```

FYI This `clang-format` re-flowing is less readable.  The prior version had symmetry between the x0 and xG lines.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 289 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYQ6JHrR0LjGx8E2Sm:-KrYQ6JHrR0LjGx8E2Sn:b-gai6rq) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L289)):*
> ```objc
>    * Replaces e.g. placeholder_x_var_ with x_vars_ at time interval
>    * @p interval_index, for all placeholder variables.
>    */
> ```

FYI This class is schizophrenic about `/** */` vs `///` on methods.  This use of `/** */` is maximally consistent with its neighbors, but not with the rest of the file.  Please do (or delegate) a follow-up PR that refactors all of the Doxygen in this file to use a consistent style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-:-KrYRUsSn6lJQq_u7-L4:bcpz082)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_swing_up.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYOFrQqY0dN3GlksMK:-KrYSRCXblGMeNdWNebM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/examples/acrobot/acrobot_swing_up.cc#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI With the intervening blank, line this comment versus the kConstant = 8 below are ever so slightly confusing.  I easily figured it out quickly though, so no defect.
</blockquote></details>

Done.

---

*[drake/examples/pendulum/test/pendulum_trajectory_optimization_test.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYOiZOLHzgCCX0ODr9:-KrYScw8IUhVHBVrsAud:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/examples/pendulum/test/pendulum_trajectory_optimization_test.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This `clang-format` re-flowing is less readable.  The prior version had symmetry between the x0 and xG lines.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 289 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYQ6JHrR0LjGx8E2Sm:-KrYTlhaIC7Qsppk2Nlm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6e0df2c61234b3a09e052acbe6547f0d58dd177/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L289)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This class is schizophrenic about `/** */` vs `///` on methods.  This use of `/** */` is maximally consistent with its neighbors, but not with the rest of the file.  Please do (or delegate) a follow-up PR that refactors all of the Doxygen in this file to use a consistent style.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 285 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYUqoG_GtmK_3KKzj7:-KrYUqoHZ1MCpta974Vl:b-854z0h) ([raw file](https://github.com/robotlocomotion/drake/blob/af41d07c6dd71108e6fefaad14cc8d06adb26968/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L285)):*
> ```objc
>   /// @param traj_init_x Initial guess for trajectory for state
>   /// input. The number of rows for each segment in @p traj_init_x must
>   /// be equal to num_states (the second param of the constructor).
> ```

FYI This should be `//` since its private; the prior `/** */` was also wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Comment by RussTedrake** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 285 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6837#-KrYUqoG_GtmK_3KKzj7:-KrY_khJ5a1rpKiV5FLo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af41d07c6dd71108e6fefaad14cc8d06adb26968/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L285)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This should be `//` since its private; the prior `/** */` was also wrong.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6837)*

**Pull request merged**
