### PR TITLE
[bindings] Update memory leak test

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Convert the test to unittest format, rewrite the instrumentation, and track the current numbers of leaks, with the goal of reaching 0 once fixes are landed.

As leaks are fixed, the test will complain about allowing more leaks than actually occurred, prompting update or removal of the leaks allowed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review.

The results show that some tests miss the mark, and (perhaps) others may be missing. I don't know that we need to address that in this PR. YMMV.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-:-O9RXGjU52EYZ9y-4mgs:b-2qqi0t)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 117 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9Rl8h3-UIaNPwGwBaK:-O9Rl8h3-UIaNPwGwBaL:bkfyc6e) ([raw file](https://github.com/RobotLocomotion/drake/blob/c93622ea13a82d6e8e8552a708f1b51f8f42c2d0/bindings/pydrake/test/memory_leak_test.py#L117)):*
> ```Python
>                 if key != 'self'
>                 and not any(isinstance(value, typ) for typ in [list, str])}
> ```

Everything from `class Sentinel` up above through here is quite opaque to me, and indeed has few to no comments.  We will need a lot more explanatory text in the first 100 lines to hand-hold drake developers through what all is happening.
___
*[`bindings/pydrake/test/memory_leak_test.py` line 299 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9RkgcF-vcD0et6lnhC:-O9RkgcF-vcD0et6lnhD:bmx37uq) ([raw file](https://github.com/RobotLocomotion/drake/blob/c93622ea13a82d6e8e8552a708f1b51f8f42c2d0/bindings/pydrake/test/memory_leak_test.py#L299)):*
> ```Python
>                 f" leaks_allowed count is stale, please update the test.")
> ```

nit Lint is here (blank line).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9V_PhT6pgxLikj_SZS:-O9V_PhT6pgxLikj_SZT:b-7j964s) ([raw file](https://github.com/RobotLocomotion/drake/blob/c93622ea13a82d6e8e8552a708f1b51f8f42c2d0/bindings/pydrake/test/memory_leak_test.py#L2)):*
> ```Python
> """Eventually this program might grow up to be an actual regression test for
> memory leaks, but for now it merely serves to demonstrate such leaks.
> ```

stale
___
*[`bindings/pydrake/test/memory_leak_test.py` line 117 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9Rl8h3-UIaNPwGwBaK:-O9V_Xsi1La9FaeU1Zq6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c93622ea13a82d6e8e8552a708f1b51f8f42c2d0/bindings/pydrake/test/memory_leak_test.py#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Everything from `class Sentinel` up above through here is quite opaque to me, and indeed has few to no comments.  We will need a lot more explanatory text in the first 100 lines to hand-hold drake developers through what all is happening.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 99 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9V_p0Y6Mq-K_XYwj7m:-O9V_p0Y6Mq-K_XYwj7n:b-iywae2) ([raw file](https://github.com/RobotLocomotion/drake/blob/8535a92d5daa64598e40bf6bb33e3cf11d93a861/bindings/pydrake/test/memory_leak_test.py#L99)):*
> ```Python
> def _counts_for_cycle_parts(o, name):
>     """Print relevant reference counts for the objects expected if `o`
>     participates in a cycle created by drake::pydrake::internal::ref_cycle.
> ```

anachronism

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 62 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9axKX69veKUeVu1jbK:-O9axKX69veKUeVu1jbL:b6n7lyj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ad502b81993d29d41f59f04eafd8cdb7691e41b/bindings/pydrake/test/memory_leak_test.py#L62)):*
> ```Python
> 
> def _object_generation(o) -> int | None:
>     """Return the garbage collection generation of the passed object, or None
> ```

nit GSG mood.

Ditto throughout this file.



_Suggestion:_
```Python
Returns
```
___
*[`bindings/pydrake/test/memory_leak_test.py` line 71 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9ayQMa5vyb6zWyQ7xW:-O9ayQMa5vyb6zWyQ7xX:bp12a4j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ad502b81993d29d41f59f04eafd8cdb7691e41b/bindings/pydrake/test/memory_leak_test.py#L71)):*
> ```Python
>         gen_id_list = [id(x) for x in gen_list]
>         if id(o) in gen_id_list:
>             return gen
> ```

BTW The way this is spelled seems odd to me. It is weird for performance reasons?  Seems like this is simpler and more clear:

```py
if any([x is o for x in gen_list]):
    return gen
```



_Code quote:_
```Python
        gen_id_list = [id(x) for x in gen_list]
        if id(o) in gen_id_list:
            return gen
```
___
*[`bindings/pydrake/test/memory_leak_test.py` line 128 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9azykw0F1rok1Oe4Fd:-O9azykw0F1rok1Oe4Fe:b9h6n6j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ad502b81993d29d41f59f04eafd8cdb7691e41b/bindings/pydrake/test/memory_leak_test.py#L128)):*
> ```Python
>             verbose: if True, print additional debug information.
>         """
>         self._verbose = verbose
> ```

I can't understand why this is a member field.  It seems like it's only ever changed by hand, by editing the code, and never just for one dut, rather for everything at once?

Under that premise, a test-wide global `VERBOSE = False` would be much easier to read and understand even just for the `if VERBOSE` logic, but then would _also_ allow us to split DutRepeater into pieces.  Right now it's doing too many jobs at once, and is very difficult to follow and reason about.

Once "verbose" is make into a global, then `make_sentinel` no longer needs a `self`, and so it can be hoisted up right next to `class Sentinel` for cohesiveness.  Its helper `make_sentinels_from_locals` would also move up there for the same reasons (dropping `self`).

After that, the `dut` functions don't need to be member functions, so would go back to also being little _stateless_ free functions.  Having them be member functions with `self._leaks` in their scope is very confusing.

After all of that, _possibly_ it makes sense for `DutRepeater` to just merge into the `class TestMemoryLeaks`?  Hard to say w/o seeing the next draft, but I'm struggling to understand what it's supposed to be _encapsulating_ as a class.  Possibly it still makes sense as a standalone thing.  LMK.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 71 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9ayQMa5vyb6zWyQ7xW:-O9jyWke9A1b0Ds52E9M:b-qmw1hg) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ad502b81993d29d41f59f04eafd8cdb7691e41b/bindings/pydrake/test/memory_leak_test.py#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The way this is spelled seems odd to me. It is weird for performance reasons?  Seems like this is simpler and more clear:

```py
if any([x is o for x in gen_list]):
    return gen
```
</blockquote></details>

I was trying not to bump ref counts of stuff on the verge of GC, but maybe it doesn't matter.  We'll try it your way.
___
*[`bindings/pydrake/test/memory_leak_test.py` line 128 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9azykw0F1rok1Oe4Fd:-O9jymi45fMNeMuNe_Cz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ad502b81993d29d41f59f04eafd8cdb7691e41b/bindings/pydrake/test/memory_leak_test.py#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can't understand why this is a member field.  It seems like it's only ever changed by hand, by editing the code, and never just for one dut, rather for everything at once?

Under that premise, a test-wide global `VERBOSE = False` would be much easier to read and understand even just for the `if VERBOSE` logic, but then would _also_ allow us to split DutRepeater into pieces.  Right now it's doing too many jobs at once, and is very difficult to follow and reason about.

Once "verbose" is make into a global, then `make_sentinel` no longer needs a `self`, and so it can be hoisted up right next to `class Sentinel` for cohesiveness.  Its helper `make_sentinels_from_locals` would also move up there for the same reasons (dropping `self`).

After that, the `dut` functions don't need to be member functions, so would go back to also being little _stateless_ free functions.  Having them be member functions with `self._leaks` in their scope is very confusing.

After all of that, _possibly_ it makes sense for `DutRepeater` to just merge into the `class TestMemoryLeaks`?  Hard to say w/o seeing the next draft, but I'm struggling to understand what it's supposed to be _encapsulating_ as a class.  Possibly it still makes sense as a standalone thing.  LMK.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-:-O9klUyG8-gV9XhEQv4K:bnfp4nl)* status: 7 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/test/memory_leak_test.py` line 163 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kiyyYE1iqZWAT5o23:-O9kiyyYE1iqZWAT5o24:b-2onwum) ([raw file](https://github.com/RobotLocomotion/drake/blob/b0ce33ae649e212deed9475d756cf5f64878f4b7/bindings/pydrake/test/memory_leak_test.py#L163)):*
> ```Python
>     if VERBOSE:
>         for key, value in locals().copy().items():
>             _counts_for_cycle_parts(value, key)
> ```

BTW Using `value, key` here comes across as a bit unusual, things are typically "key, value" the other way around.  Probably the "counts for ..." should require calling by kwargs, and so have `name=key, o=value` or `key=key, value=value` here at the caller.
___
*[`bindings/pydrake/test/memory_leak_test.py` line 294 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kjKkn8xUV3lfub01F:-O9kjKkn8xUV3lfub01G:b-79c53g) ([raw file](https://github.com/RobotLocomotion/drake/blob/b0ce33ae649e212deed9475d756cf5f64878f4b7/bindings/pydrake/test/memory_leak_test.py#L294)):*
> ```Python
>     diagram.SetRandomContext(simulator.get_mutable_context(), random)
>     simulator.AdvanceTo(0.5)
>     return _make_sentinels_from_locals("full_simulator", locals())
> ```

nit This string doesn't match the function name, which is "full_example".  I imagine we want them to be 100% identical?
___
*[`bindings/pydrake/test/memory_leak_test.py` line 300 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kjX_84FjZIrWxbnuG:-O9kjX_84FjZIrWxbnuH:btko4z) ([raw file](https://github.com/RobotLocomotion/drake/blob/b0ce33ae649e212deed9475d756cf5f64878f4b7/bindings/pydrake/test/memory_leak_test.py#L300)):*
> ```Python
>     """Calls dut() for count times in a row, performing a full garbage
>     collection before and after each call. Tracks memory leaks of interest; the
>     count of leaks is returned.  if `VERBOSE=True`, additional debug
> ```

typo s/if/If/
___
*[`bindings/pydrake/test/memory_leak_test.py` line 310 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kjlRj1h5JmHQvuMgT:-O9kjlRj1h5JmHQvuMgU:b728ckc) ([raw file](https://github.com/RobotLocomotion/drake/blob/b0ce33ae649e212deed9475d756cf5f64878f4b7/bindings/pydrake/test/memory_leak_test.py#L310)):*
> ```Python
> 
>     Returns:
>         int: the total number of leaks detected by examining returned
> ```

BTW When I read this docstring, I took it to be the number of leaked objects, not the number of `dut()` calls which leaked anything.
___
*[`bindings/pydrake/test/memory_leak_test.py` line 330 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kjuK6EGP635t8fHmE:-O9kjuK6EGP635t8fHmF:bfpxqp5) ([raw file](https://github.com/RobotLocomotion/drake/blob/b0ce33ae649e212deed9475d756cf5f64878f4b7/bindings/pydrake/test/memory_leak_test.py#L330)):*
> ```Python
> class TestMemoryLeaks(unittest.TestCase):
>     def do_test(self, *, dut, count, leaks_allowed=0):
>         """Run the requested `dut` (see _repeat() above) for `count`
> ```

nit GSG "Runs"
___
*[`bindings/pydrake/test/memory_leak_test.py` line 123 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9klAuXCgg6dTXgOp6p:-O9klAuXCgg6dTXgOp6q:b-nv8o2u) ([raw file](https://github.com/RobotLocomotion/drake/blob/63810098963ab0a64bc30826c78b65a0a0d6a7d9/bindings/pydrake/test/memory_leak_test.py#L123)):*
> ```Python
> # TODO(rpoyner-tri): update or delete this when ref_cycle is adopted, changed,
> # or abandoned.
> def _counts_for_cycle_parts(o, name):
> ```

nit This needs a verb.  Maybe "_print_counts...etc"?  Currently "counts" seems like it's supposed to be the verb, which is somewhat confusing.

Actually, without any of the 22022 infra landed, this function seems somewhat premature to land now?
___
*[`bindings/pydrake/test/memory_leak_test.py` line 360 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9kkJd-AUEeJG2x5kkn:-O9kkJd-AUEeJG2x5kko:bxvka0t) ([raw file](https://github.com/RobotLocomotion/drake/blob/63810098963ab0a64bc30826c78b65a0a0d6a7d9/bindings/pydrake/test/memory_leak_test.py#L360)):*
> ```Python
>         # TODO(rpoyner-tri): investigate platform differences, if leaks persist
>         # after fixing.
>         leaks_by_platform = {
> ```

BTW This kind of thing is why I'm a little bit hesitant to have the "fail if the allowed number is too high".  For my taste, grooming that number should be mostly manual, without CI failures nagging us about it.  Since the goal number our work on this ticket is necessarily zero, I don't know that we need a lot of hand-holding to remind us to keep lowering it.

Our C++ limit_malloc has `min_num_allocations` but it is rarely used.  If you do want to keep the lower bound as part of this test, maybe "leaks_required=1" is a better phrasing that equating leaks_allowed to leaks_required implicitly?

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for next not-me platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-:-O9lAD1933AVxqRoA3-l:bv1iq81)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-:-O9qRv3m-jYwhOQqGl5x:b-cxwtpw)* status: 3 unresolved discussions

___
*[`bindings/pydrake/test/memory_leak_test.py` line 99 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qOdOJ4Kugt7qTR68u:-O9qOdOJ4Kugt7qTR68v:b-8vgbzc) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L99)):*
> ```Python
>         print(f"sentinel alive? {finalizer.alive}")
>         if finalizer.alive:
>             o = finalizer.peek()[0]
> ```

BTW a comment on this line would be helpful for me. Would a more Python-savvy person automatically understand this? Here's my (likely wrong) guess after a lot of staring at the code: `peek()` applied to a function returns a list of its arguments and then `[0]` grabs the first one, which in this case is known to be the object of interest?
___
*[`bindings/pydrake/test/memory_leak_test.py` line 283 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qQfJM6ShicceVquxD:-O9qQfJM6ShicceVquxE:b-o613le) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L283)):*
> ```Python
> 
>     Returns:
>         int: the total number of leaked objectss detected by examining returned
> ```

typo: objectss
___
*[`bindings/pydrake/test/memory_leak_test.py` line 297 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qR5_128Y0aXqPSNOb:-O9qR5_128Y0aXqPSNOc:bn7p7b5) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L297)):*
> ```Python
>             _report_sentinels(sentinels, "after collect")
>         leaks += any(
>             [sentinel.finalizer.alive for sentinel in sentinels])
> ```

BTW IIUC this adds 1 to `leaks` if _any_ of this batch of sentinels is still active; it does not add 1 for each active sentinel. Is that the intention?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 3 unresolved discussions

___
*[`bindings/pydrake/test/memory_leak_test.py` line 99 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qOdOJ4Kugt7qTR68u:-O9qSYAf1Yz4VafceWIX:b-xs5c5g) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L99)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a comment on this line would be helpful for me. Would a more Python-savvy person automatically understand this? Here's my (likely wrong) guess after a lot of staring at the code: `peek()` applied to a function returns a list of its arguments and then `[0]` grabs the first one, which in this case is known to be the object of interest?
</blockquote></details>

Does this API reference help?

https://docs.python.org/3/library/weakref.html#weakref.finalize.peek

The `finalizer: weakref.finalize` field is annotated as being of type `weakref.finalize`, and that's the API docs for its `peek()` method.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 2 unresolved discussions

___
*[`bindings/pydrake/test/memory_leak_test.py` line 99 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qOdOJ4Kugt7qTR68u:-O9qX7P63HXzmhTMO88N:b-k9j84z) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L99)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does this API reference help?

https://docs.python.org/3/library/weakref.html#weakref.finalize.peek

The `finalizer: weakref.finalize` field is annotated as being of type `weakref.finalize`, and that's the API docs for its `peek()` method.
</blockquote></details>

Yep, thanks. I tried googling "python what does peek do" but that returned info about something else with the same name.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22059)* status: 2 unresolved discussions

___
*[`bindings/pydrake/test/memory_leak_test.py` line 297 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/22059#-O9qR5_128Y0aXqPSNOb:-O9qqQSD7ywiEBUSvdR4:bvukiqw) ([raw file](https://github.com/RobotLocomotion/drake/blob/090ef376b258243da70f8dab19eafe0af02f6e74/bindings/pydrake/test/memory_leak_test.py#L297)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW IIUC this adds 1 to `leaks` if _any_ of this batch of sentinels is still active; it does not add 1 for each active sentinel. Is that the intention?
</blockquote></details>

Ah, yes, the code and documentation are at odds. Will fix.

**Pull request merged**
