### PR TITLE
Optimization debug assertion

### PR DESCRIPTION
**Pull request by sammy-tri**
Fix debug assertion which started appearing in https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-debug/53/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2133)

### CODE REVIEW

**Comment by ggould-tri** [comment]
bbeffce looks fine; I can't judge the correctness of 1292df9 in the time I have left today; I will review more tomorrow if this is still outstanding.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2133#-:-KFpSfKNNwppdjrB1m43:914654383)*

**Comment by ggould-tri** [comment]
:lgtm: :shipit:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2133#-:-KFpUltgEQU4Oz_MQP2L:-1040131160)*

**Comment by ggould-tri** [comment]
Marking ready-to-accept as CI passed (except for spurious win64 nonsense) on a previous version.

**Comment by jwnimmer-tri** [comment]
I agree that the [prior build 951](https://drake-jenkins.csail.mit.edu/job/experimental/951/) was a pass -- just a msvc64 flake.  It is unclear to me, though, why having withdrawn some code from the PR that the next-Jenkins must necessarily pass as well.  We'll wait to merge until Jenkins passes on bbeffce by itself.

LGTM on the code itself, though, so really just waiting on build servers.

**Comment by liangfok** [comment]
> It is unclear to me, though, why having withdrawn some code from the PR that the next-Jenkins must necessarily pass as well.

Here's one possibility: Suppose we add methods A and B where A calls B and it passes the CI tests. Now suppose we delete B without modifying A. This would represent an error introduced by the withdrawal of code that the next round of CI tests will catch.

**Comment by jwnimmer-tri** [comment]
Jenkins passed, code review done x2.  I am going to merge now.  (The drake005 just woke up and started building, but I'm going to ignore it.)

**Pull request merged**
