### PR TITLE
Upgrade gz_math_internal and sdformat_internal to latest

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21669

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21674)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri please take a look and push a fix, when you have time.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21674#-:-O1SxOfM8l05Ac_fN5lp:bg7igkv)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21674#-:-O1T8ViF04J_lXaL2NUM:bt1x5ma)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform +(status: squashing now) 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21674#-:-O1TDwW0D_JV8vAo8dHw:bk6m0t)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
