### PR TITLE
Add initial pydrake bindings for maliput

### PR DESCRIPTION
**Pull request by jadecastro**
Add just enough to get up and running with an IDM/MOBIL system.

/cc @maddog-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8091)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@ericcousineau-tri for feature review, please. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5VIwmnzK_-wQ_pqjDb:bly9xky)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 5 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 13 unresolved discussions.

---

*[bindings/pydrake/maliput/__init__.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VKBlOJN6G0bkZqa-k:-L5VKBlPDWlhUX38DOWI:b-r28dmr) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/__init__.py#L1)):*
> ```Python
> # Blank Python module.
> ```

BTW @sherm1 We have other modules that are inconsistent with `lcmtypes/__init__.py` (more descriptive info).
Will chase this PR with a follow-up to make them consistent.

---

*[bindings/pydrake/maliput/api_py.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VKgG3iJ5oIoGg7EdB:-L5VKgG3iJ5oIoGg7EdC:bqean4e) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/api_py.cc#L21)):*
> ```cpp
> 
>   py::class_<GeoPosition> (m, "GeoPosition")
>       .def(py::init<double, double, double>())
> ```

BTW Can you add `py::arg` for each of these arguments?
An example is the bindings for `Eigen::Quaternion`:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/util/eigen_geometry_py.cc#L171

---

*[bindings/pydrake/maliput/BUILD.bazel, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLpG5-jO90vjElB1h:-L5VLpG5-jO90vjElB1i:b36ecxi) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/BUILD.bazel#L42)):*
> ```Python
>     name = "api_py",
>     cc_deps = [
>         "//automotive/maliput/api",
> ```

Same as below.

---

*[bindings/pydrake/maliput/BUILD.bazel, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLfuyHo9G-cVw0rH7:-L5VLfuyHo9G-cVw0rH8:b-hv5dyb) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/BUILD.bazel#L55)):*
> ```Python
>     name = "dragway_py",
>     cc_deps = [
>         "//automotive/maliput/dragway",
> ```

`cc_deps` should only include libraries which are robust against ODR-violations (and not already in `drake_shared_library`).
(See documentation for `drake_pybind_library`)

---

*[bindings/pydrake/maliput/dragway_py.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VL-RjQcXJ6mfcfbFM:-L5VL-RjQcXJ6mfcfbFN:bc33e68) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L20)):*
> ```cpp
> 
>   py::class_<dragway::RoadGeometry>(m, "RoadGeometry")
>       .def(py::init<api::RoadGeometryId, int, double, double, double, double,
> ```

BTW Same as above - can you name these arguments?

---

*[bindings/pydrake/maliput/dragway_py.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VL4y1I1Uv3md8sXDV:-L5VL4y1I1Uv3md8sXDW:bbv80oo) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L36)):*
> ```cpp
>            py::keep_alive<0, 1>());
> 
>   // SHould this be in the api?
> ```

BTW Can this be changed to a `TODO`?

---

*[bindings/pydrake/maliput/dragway_py.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VL8fn0dklDOARv9I8:-L5VL8fn0dklDOARv9I9:bef3iog) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L40)):*
> ```cpp
>       .def("ToLanePosition", &dragway::Lane::ToLanePosition)
>       .def("ToGeoPosition", &dragway::Lane::ToGeoPosition);
> ;
> ```

Extra `;`

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLAkyvGtRQoIHVr6b:-L5VLAkyvGtRQoIHVr6c:br66wec) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

BTW Shebang not necessary.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLGJWi6pJRBiAcCEp:-L5VLGJWi6pJRBiAcCEq:b-20ur5j) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L23)):*
> ```Python
>         srh = [4., 5., 6.]
>         lane_pos = LanePosition(srh[0], srh[1], srh[2])
>         self.assertTrue(len(lane_pos.srh()) == 3)
> ```

BTW When you add the names, could you test that constructor flavor?

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLLM1JBMoGn3PFb-S:-L5VLLM2c_XFO8DSWWiU:byjvreu) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L29)):*
> ```Python
>         geo_pos = GeoPosition(xyz[0], xyz[1], xyz[2])
>         self.assertTrue(len(geo_pos.xyz()) == 3)
>         for i in [0, 1, 2]:
> ```

Rather than this, you can use `self.assertTrue(np.allclose(geo_pos.xyz(), xyz))`

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLS2yN6IK3lG4P4oe:-L5VLS2yN6IK3lG4P4of:bc5smbo) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L53)):*
> ```Python
>         geo_pos_result = lane_0.ToGeoPosition(lane_pos)
>         geo_pos_expected = GeoPosition(0., -kLaneWidth / 2., 0.)
>         for i in [0, 1, 2]:
> ```

BTW Same as above, using `np.allclose`

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLWNEM1xoWnjvYcZJ:-L5VLWNEM1xoWnjvYcZK:bc5smbo) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L63)):*
> ```Python
>             lane_1.ToLanePosition(geo_pos, nearest_pos, distance)
>         lane_pos_expected = LanePosition(1., 0., 3.)
>         for i in [0, 1, 2]:
> ```

BTW Same as above, using `np.allclose`

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5VLYgpQm8K2wMJnGj_:-L5VLYgpQm8K2wMJnGja:bhlyxf8) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L67)):*
> ```Python
>                             lane_pos_expected.srh()[i])
>             self.assertTrue(nearest_pos.xyz()[i] == geo_pos.xyz()[i])
>             self.assertTrue(distance == 0.)
> ```

BTW This shouldn't be in the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5VLwmDCYO1H-ku_iBz:b-2l0s3s)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
Review status: 1 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 21 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VKgG3iJ5oIoGg7EdB:-L5ViyNH-e_5znclCkw9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/api_py.cc#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you add `py::arg` for each of these arguments?
An example is the bindings for `Eigen::Quaternion`:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/util/eigen_geometry_py.cc#L171
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/BUILD.bazel, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLpG5-jO90vjElB1h:-L5VNG0Kq2X-1URPOlJd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/BUILD.bazel#L42)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same as below.
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/BUILD.bazel, line 55 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLfuyHo9G-cVw0rH7:-L5VNGCpprdG3eqvIjHI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/BUILD.bazel#L55)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

`cc_deps` should only include libraries which are robust against ODR-violations (and not already in `drake_shared_library`).
(See documentation for `drake_pybind_library`)
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/dragway_py.cc, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VL-RjQcXJ6mfcfbFM:-L5Vj-sF6ey-7NUoJuC6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Same as above - can you name these arguments?
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/dragway_py.cc, line 36 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VL4y1I1Uv3md8sXDV:-L5VMZKf9TVgtd9p1ETJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can this be changed to a `TODO`?
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/dragway_py.cc, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VL8fn0dklDOARv9I8:-L5VMWsIk8nYGZskEJA-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/dragway_py.cc#L40)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Extra `;`
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLAkyvGtRQoIHVr6b:-L5VNMl8e2Logo3QBRaw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Shebang not necessary.
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 23 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLGJWi6pJRBiAcCEp:-L5Vj11-4vTejskuCZdN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW When you add the names, could you test that constructor flavor?
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 29 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLLM1JBMoGn3PFb-S:-L5VOR59yMsczg3rfDHO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L29)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Rather than this, you can use `self.assertTrue(np.allclose(geo_pos.xyz(), xyz))`
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLS2yN6IK3lG4P4oe:-L5VOReRX5S70J8sHx95:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L53)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Same as above, using `np.allclose`
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 63 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLWNEM1xoWnjvYcZJ:-L5VOS2uJoyPGBF2EQFc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L63)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Same as above, using `np.allclose`
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/test/maliput_test.py, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5VLYgpQm8K2wMJnGj_:-L5VOSZanuHFqLDtMhd8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e4ae7066e157637a9a825cb235d09d486de1419/bindings/pydrake/maliput/test/maliput_test.py#L67)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This shouldn't be in the loop?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
+@sherm1 platform review, please.

---

Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-:-L5VjA469erBQf1n4IH0:b8g60cr)*

**Comment by sherm1** [comment]
Apologies, but I don't think I can adequately platform review this because I am too unfamiliar with Python wrapping and with our Python conventions in general. @ericcousineau-tri, your review looked like a solid platform review to me. Do you think it was also an adequate feature review? If not, maybe this needs a feature review from @jadecastro's team. -@sherm1

---

Reviewed 1 of 5 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5Vn9MsPVGfYq6dYvoW:bkij34m)*

**Comment by jadecastro** [comment]
No problem, @sherm1, and I agree about @EricCousineau-TRI for platform. 
+@liangfok for feature review, please. 

---

Review status: 5 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5Vo5J7p6xFcv0a1c-2:bqc4nko)*

**Comment by maddog-tri** [comment]
*[bindings/pydrake/maliput/dragway_py.cc, line 30 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5W4KMrof3lj2esBGKD:-L5W4KMrof3lj2esBGKE:bh1kxug) ([raw file](https://github.com/robotlocomotion/drake/blob/dc5c97ec3cd5f6467347e7842764b52ad32cf708/bindings/pydrake/maliput/dragway_py.cc#L30)):*
> ```cpp
> 
>   // TODO(jadecastro) Revisit whether or not the following belong instead as api
>   // bindings.
> ```

FYI:  They _should_ be API bindings.  In fact, it is kind of odd that `dragway` exposes its `RoadGeometry` constructor.  `dragway` should have some kind of `CreateDragway(...)` static function that just returns a `unique_ptr<api::RoadGeometry>` and keeps all the implementation details stashed under the covers as implementation details.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
-@liangfok 
+@maddog-tri for feature review (since you've already started) 

---

Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[bindings/pydrake/maliput/dragway_py.cc, line 30 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5W4KMrof3lj2esBGKD:-L5WfvPV50w5RXsHx909:b4ylgo8) ([raw file](https://github.com/robotlocomotion/drake/blob/dc5c97ec3cd5f6467347e7842764b52ad32cf708/bindings/pydrake/maliput/dragway_py.cc#L30)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

FYI:  They _should_ be API bindings.  In fact, it is kind of odd that `dragway` exposes its `RoadGeometry` constructor.  `dragway` should have some kind of `CreateDragway(...)` static function that just returns a `unique_ptr<api::RoadGeometry>` and keeps all the implementation details stashed under the covers as implementation details.
</blockquote></details>

Nice. Yeah, the `dragway` gloop should definitely not be user-facing. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5WgEmQIfToYHp4FShu:baqmg5k)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 36 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5l3wIo7UFMH3amnZlM:-L5l3wIpBccThwXHei4w:b-nnexjw) ([raw file](https://github.com/robotlocomotion/drake/blob/c4399b78a008e6c31fdb376a38ebd164faac0403/bindings/pydrake/maliput/api_py.cc#L36)):*
> ```cpp
>       .def("junction", &RoadGeometry::junction, py_reference_internal,
>            // Keep alive, reference: `return` keeps `self` alive.
>            py::keep_alive<0, 1>());
> ```

`py::keep_alive<0, 1>` is redundant when `py_reference_internal` is already used.

Can you just use `py_reference_internal`? (no need to specify a comment in this case.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 36 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091#-L5l3wIo7UFMH3amnZlM:-L5naTxx6SS_eC9bPmYh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4399b78a008e6c31fdb376a38ebd164faac0403/bindings/pydrake/maliput/api_py.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

`py::keep_alive<0, 1>` is redundant when `py_reference_internal` is already used.

Can you just use `py_reference_internal`? (no need to specify a comment in this case.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8091)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 26 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5oj8-zubDw7CaPPIcx:-L5p-rmEhGK-NXDwy1EW:b-dijf4w) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L26)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

For this accessor (and the similar, LanePosition::srh()), as I (am starting to) understand pydrake/pybind11, these will return numpy-wrapped copies of the original Eigen vectors.

The C++ accessors return const-references (i.e., view semantics) --- so perhaps it would be better if the pydrake wrappers did the same?  I think adding `py_reference_internal` will accomplish that.

Opinions, @ericcousineau-tri ?
</blockquote></details>

Yes, I believe `py_reference_internal` may work, though you may have to wrap it to return something like `Eigen::Ref<>`.

I'd say it doesn't matter if there's no explicit use case for referencing, and would be relatively easy to change if needed.

One additional word of caution is that I need to resolve (with Kitware's help) whether we can maintain reference semantics with AutoDiff / Symbolic:
https://github.com/RobotLocomotion/drake/issues/8116
If we have to go with (b), then we'd have to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 26 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5oj8-zubDw7CaPPIcx:-L5parzN7tCwKa2C5gSB:bvzd7ny) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yes, I believe `py_reference_internal` may work, though you may have to wrap it to return something like `Eigen::Ref<>`.

I'd say it doesn't matter if there's no explicit use case for referencing, and would be relatively easy to change if needed.

One additional word of caution is that I need to resolve (with Kitware's help) whether we can maintain reference semantics with AutoDiff / Symbolic:
https://github.com/RobotLocomotion/drake/issues/8116
If we have to go with (b), then we'd have to change it.
</blockquote></details>

Done. `py_reference_internal` added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by maddog-tri** [comment]
Pass complete; PTAL.

---

Reviewed 1 of 5 files at r1, 1 of 5 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 18 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5pa7QlPq1cXRmXF8nV:-L5pa7QlPq1cXRmXF8nW:bq473ii) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L18)):*
> ```cpp
>   using namespace drake::maliput::api;
> 
>   m.doc() = "Bindings for the Maliput API.";
> ```

Probably a good idea to add a TODO indicating that these bindings are a work-in-progress, and referencing #7918 as tracking the progress (kind of).

---

*[bindings/pydrake/maliput/api_py.cc, line 21 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5peok9UR6qzWVeWekV:-L5peok9UR6qzWVeWekW:b-cdj8ri) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L21)):*
> ```cpp
> 
>   py::class_<RoadGeometryId>(m, "RoadGeometryId")
>       .def(py::init<std::string>());
> ```

The `string()` accessor should also be exposed; that's kinda the absolute minimum to do anything useful with `RoadGeometryId`. (And, then, exercise it in the unit-tests, too.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5pg6wIimqAu1qMdpsK:bg781dj)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 26 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5oj8-zubDw7CaPPIcx:-L5piGHRYTWUr3FZVqx1:brdfix6) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L26)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Done. `py_reference_internal` added.
</blockquote></details>

BTW You may need to ensure this returns `Ref<>`. At present it's untested? (if there's little motivation to test this, then it should be fine if it just returns a copy?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/maliput/api_py.cc, line 26 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5oj8-zubDw7CaPPIcx:-L5pmEx7V938f5N-C5Oi:bi18np9) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW You may need to ensure this returns `Ref<>`. At present it's untested? (if there's little motivation to test this, then it should be fine if it just returns a copy?)
</blockquote></details>

BTW After checking the code, I was wrong, you shouldn't actually need `Ref<>` - sorry about that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by jadecastro** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/maliput/api_py.cc, line 18 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5pa7QlPq1cXRmXF8nV:-L5q8RrREgTfRnwdmC-M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L18)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Probably a good idea to add a TODO indicating that these bindings are a work-in-progress, and referencing #7918 as tracking the progress (kind of).
</blockquote></details>

Done.

---

*[bindings/pydrake/maliput/api_py.cc, line 21 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-L5peok9UR6qzWVeWekV:-L5q8CPWI5VNoSWXbctK:blgbb35) ([raw file](https://github.com/robotlocomotion/drake/blob/979a6869fbd87dbc9fca1333de5320589b89fffc/bindings/pydrake/maliput/api_py.cc#L21)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

The `string()` accessor should also be exposed; that's kinda the absolute minimum to do anything useful with `RoadGeometryId`. (And, then, exercise it in the unit-tests, too.)
</blockquote></details>

Done. (unit test added also)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8091#-:-L5qVtvWL5hsx6idCODv:bnfp4nl)*

**Pull request merged**
