### PR TITLE
Minor cleanup of pkg_config.bzl

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9197)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
(Aside: Looks like maybe the `-pthread` in `protobuf.pc` may be the cause of all the `-Wunused-command-line-argument` warnings on Mac. This does not fix that.)

**Comment by jwnimmer-tri** [comment]
I am OK to count for both reviews.

**Pull request merged**
