### PR TITLE
[ad] Add support for comparison operations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor bits

> Reviewed 6 of 8 files at r2, 33 of 33 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636#-:-N89h-d46UosqOWP4f5E:b-czal6o)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/ad/test/standard_operations_cmp_test.cc` line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17636#-N89g1nq9V4tMb-UbNKp:-N89g1nq9V4tMb-UbNKq:b-7ph9p7) ([raw file](https://github.com/robotlocomotion/drake/blob/f5ebe0a1bf39157bcf318740c9e9acf0ef527164/common/ad/test/standard_operations_cmp_test.cc#L14)):*
> ```cpp
>   EXPECT_EQ(1 cmp 0, AutoDiffDut{1} cmp AutoDiffDut{0}); \
>   EXPECT_EQ(1 cmp 1, AutoDiffDut{1} cmp AutoDiffDut{1}); \
>   EXPECT_EQ(0 cmp 1, AutoDiffDut{0} cmp 1); /* NOLINT */ \
> ```

FYI I looked into this a little. Bleh, but carry on.
___
*[`common/ad/test/standard_operations_max_test.cc` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17636#-N89gMgX41hi8tALWuu1:-N89gMgX41hi8tALWuu2:b-vpbd8o) ([raw file](https://github.com/robotlocomotion/drake/blob/f5ebe0a1bf39157bcf318740c9e9acf0ef527164/common/ad/test/standard_operations_max_test.cc#L9)):*
> ```cpp
> 
> TEST_F(StandardOperationsTest, MaxBothAds) {
>   CHECK_BINARY_FUNCTION_ADS_ADS(max, x, y, 0.5);
> ```

nit is there a reason this value doesn't follow the pattern elsewhere? if so, readers should know why.



_Code quote:_
```cpp
0.5)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`common/ad/test/standard_operations_max_test.cc` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17636#-N89gMgX41hi8tALWuu1:-N89hAbY4WPCdYwfAEle:b-2psubh) ([raw file](https://github.com/robotlocomotion/drake/blob/f5ebe0a1bf39157bcf318740c9e9acf0ef527164/common/ad/test/standard_operations_max_test.cc#L9)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit is there a reason this value doesn't follow the pattern elsewhere? if so, readers should know why.
</blockquote></details>

OK Hah, I have no idea!  Dates back to ca2e2dcf56727a4e7f66a2b3232729a477a433d3 with no explanation.  I've updated to match with the rest, the test still passe.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

FYI, meta:
(1) You are an absolute PR machine!
(2) All of these things with "[ad]" in the subject line keep making me reach for the spam-bucket button
:-)

> Reviewed 4 of 8 files at r2, 1 of 33 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636#-:-N8PqtkqDbGtz-2MXd9B:bqaym3q)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/ad/test/standard_operations_test.h` line 173 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17636#-N8PqdzO1ZvV0d15Hwzs:-N8PqdzO1ZvV0d15Hwzt:b-s6pgkc) ([raw file](https://github.com/robotlocomotion/drake/blob/8c2970fbdd3d100cb8df35faf5c8a2a5eee51828/common/ad/test/standard_operations_test.h#L173)):*
> ```objc
>   CHECK_EXPR(f(-x, c) + y);
> 
> // The additive factor 5.0 let us call functions whose arguments must be
> ```

minor:  "Additive factor" is not a thing?  Wikipedia suggests, "...called addends or summands"; "additive element" would be fine if you prefer not to send the reader to the reference books?



_Code quote:_
```objc
additive factor
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17636)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[`common/ad/test/standard_operations_test.h` line 173 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17636#-N8PqdzO1ZvV0d15Hwzs:-N8Q-2xx69_CsDFpeONn:blbnx2q) ([raw file](https://github.com/robotlocomotion/drake/blob/8c2970fbdd3d100cb8df35faf5c8a2a5eee51828/common/ad/test/standard_operations_test.h#L173)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  "Additive factor" is not a thing?  Wikipedia suggests, "...called addends or summands"; "additive element" would be fine if you prefer not to send the reader to the reference books?
</blockquote></details>

Done.  In #17650 we decided to nix the comments entirely.  I think they were copy-pasta from Expression tests.  Unlike AutoDiff, Expression _throws_ on domain errors (instead of returning NaN), so the domain was very important.  Here, it's not really an issue.

**Pull request merged**
