### PR TITLE
maliput::api: Fix contracts for RoadGeometry::ToRoadPosition() and Lane::ToLanePosition()

### PR DESCRIPTION
**Pull request by maddog-tri**
Clarify/enhance the contracts for api::RoadGeometry::ToRoadPosition() and
api::Lane::ToLanePosition() --- yielding a net reduction of 4 TODO's.

Neither of these methods has a functional implementation yet in the codebase.
The key aspects of these changes:
 1) These methods always return a result.
 2) If the input `geo_position` is not actually within the volume of
    the RoadGeometry or Lane, then the methods do the sensible thing
    of returning the closest point,  which is on the boundary of the volume.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5302)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review. +@jwnimmer-tri for automotive review (and platform review?).

Liang, this is a different from the direction we considered yesterday morning.  Instead of possibly returning "NO ANSWER", it occurred to me that it would be more robust to follow the model of classic geometry operations like "find closest point on circle" and "find closest point on line".  I.e., if the input point is not in the RoadGeometry, find the closest point that is and describe that.

It also spells out the basic desired behavior for `ToRoadPosition()`, which amounts to "find the Lane (among adjacent Lanes in any given Segment) that best contains the input point".

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-Kdj8qtCy3vRc25R4Xbh:b-6n0i2b)*

**Comment by RussTedrake** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/api/lane.h, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk8aJnLIlCiIt8y5zI:-Kdk8aJnLIlCiIt8y5zJ:by5t1o5) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/lane.h#L106)):*
> ```objc
>   LanePosition ToLanePosition(const GeoPosition& geo_position,
>                               GeoPosition* nearest_point,
>                               double* distance) const {
> ```

fyi -- this contract lgtm .  i think it will serve as the cost function for an initial trajectory optimization demo (that i'd love to start this weekend)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by liangfok** [comment]
Checkpoint.

---

Reviewed 2 of 14 files at r1.
Review status: 2 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/api/lane.h, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk5qjamZmOTB46b822:-Kdk5qjamZmOTB46b823:b-puvi1k) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/lane.h#L106)):*
> ```objc
>   LanePosition ToLanePosition(const GeoPosition& geo_position,
>                               GeoPosition* nearest_point,
>                               double* distance) const {
> ```

BTW, consider adding `= nullptr` to the last two parameters so call sites​ will not need to do so when they are not interested in getting the nearest geo point and the distance.

---

*[drake/automotive/maliput/api/road_geometry.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk6q-kvBykFnFUouI5:-Kdk6q-kvBykFnFUouI6:b6busk6) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L76)):*
BTW, what does "not onto" mean into this context? Do you mean "not one-to-one" or "not trivial"?

Alternatively, consider:

> The RoadGeometry coordinate system does not map onto the Cartesian world frame coordinate system since the former is bounded while the latter is not.

---

*[drake/automotive/maliput/api/road_geometry.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk8JKLLDUJCyqMRId9:-Kdk8JKLLDUJCyqMRIdA:b-whywf8) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L91)):*
> ```objc
>   /// Lanes, then ToRoadPosition() will choose a Lane which contains
>   /// @p geo_position within its `lane_bounds()` if possible, and if that is
>   /// still ambiguous, will further select a Lane which minimizes the absolute
> ```

BTW, missing "it" before "will".

---

*[drake/automotive/maliput/api/road_geometry.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk8Qg33hFVjWfCcPx_:-Kdk8Qg33hFVjWfCcPxa:b-ukghap) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L102)):*
> ```objc
>   //                          might expect an updated RoadPosition which is
>   //                          nearby (e.g., on the same Lane).
>   RoadPosition ToRoadPosition(const GeoPosition& geo_position,
> ```

BTW, did you consider the possibility of having this method return a set of `RoadPosition` values that all correspond to the same `@p geo_position` and allowing the user to decide which `RoadPosition` is best for its needs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-Kdk8ioFpLzAHuDAnIlg:by96gdd)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-KdkBOB_9S8pfhvW-8ia:bnfp4nl)*

**Comment by liangfok** [comment]
Completed first pass of feature review.

---

Reviewed 12 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-KdkE1GJQkGPXQTc7JA1:bvr2qvc)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/api/road_geometry.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk6q-kvBykFnFUouI5:-KdkhO2gHSUvfd_D3n3O:b-lggeup) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, what does "not onto" mean into this context? Do you mean "not one-to-one" or "not trivial"?

Alternatively, consider:

> The RoadGeometry coordinate system does not map onto the Cartesian world frame coordinate system since the former is bounded while the latter is not.
</blockquote></details>

https://en.wikipedia.org/wiki/Surjective_function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/api/road_geometry.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk6q-kvBykFnFUouI5:-Kdkhrc92655xkEg4ERA:b-u05vp2) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://en.wikipedia.org/wiki/Surjective_function
</blockquote></details>

Thanks, consider:

```
/// The map from RoadGeometry to world frame is not
/// [surjective](https://en.wikipedia.org/wiki/Surjective_function).
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by maddog-tri** [comment]
Comments from first pass addressed.

---

Review status: 7 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/api/road_geometry.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk6q-kvBykFnFUouI5:-KdkqHukdVWxvswFrGJf:b-yijqa5) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Thanks, consider:

```
/// The map from RoadGeometry to world frame is not
/// [surjective](https://en.wikipedia.org/wiki/Surjective_function).
```
</blockquote></details>

Done (by rewording the parenthetical).

---

*[drake/automotive/maliput/api/road_geometry.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk8JKLLDUJCyqMRId9:-KdkliS3HrUMhyWNSz4m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L91)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing "it" before "will".
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/road_geometry.h, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-Kdk8Qg33hFVjWfCcPx_:-KdklsKxW0GIpyElOvkC:b-z6xcw3) ([raw file](https://github.com/robotlocomotion/drake/blob/303155a7df2c1846e7e612980313db01d9648f0d/drake/automotive/maliput/api/road_geometry.h#L102)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, did you consider the possibility of having this method return a set of `RoadPosition` values that all correspond to the same `@p geo_position` and allowing the user to decide which `RoadPosition` is best for its needs?
</blockquote></details>

Yah, I pondered it.  If that turns out to be a needed feature, it could be an additional method.  I expect that a single result will typically be good enough:  the `hint` is intended to help preselect the desired result, and with any result, the caller will still have to "look at other segments in the same junction" to decide if any other things are nearby (if the caller is looking for objects in LANE-space).  Returning all possible results could also be a more expensive operation.

Oooh... it occurs to me just now that `hint` should be optional!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-KdksNNhlmUH9mheldCB:bsiobqj)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by liangfok** [comment]
:lgtm: 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzDu1NLaPu7iAdkRp:-KdkzDu1NLaPu7iAdkRq:b-1x5120) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
> ```objc
>   /// Determines the RoadPosition corresponding to GeoPosition @p geo_position.
>   ///
>   /// If @p hint in non-null, its value is used to help guide the search and
> ```

"in" should be "is".

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzYqsYN7_ChXppdQX:-KdkzYqsYN7_ChXppdQY:b-rwh52j) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
> ```objc
>   /// Determines the RoadPosition corresponding to GeoPosition @p geo_position.
>   ///
>   /// If @p hint in non-null, its value is used to help guide the search and
> ```

BTW, "search and select the result" may cause some confusion. Consider "determination" to or "resolution".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-KdkzSnsG5Au_P_LhWGv:bg7igkv)*

**Comment by maddog-tri** [comment]
Comments addressed.

---

Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzDu1NLaPu7iAdkRp:-KdlFnqjBK_U3JCpExH3:bhgzs6) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"in" should be "is".
</blockquote></details>

Done. (D'oh.)

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzYqsYN7_ChXppdQX:-KdlG-XfF1haks7IGVj7:b-evu5xs) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "search and select the result" may cause some confusion. Consider "determination" to or "resolution".
</blockquote></details>

Done. (I expect this text, and this aspect of the contract, to evolve once we have a couple of implementations, hence the TODO.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-:-KdlGux06Tak-G8y1dsG:bel95ya)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzYqsYN7_ChXppdQX:-KdlNm_HqI4A1W1Zrndj:b2fr6sq) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done. (I expect this text, and this aspect of the contract, to evolve once we have a couple of implementations, hence the TODO.)
</blockquote></details>

BTW: nit: missing "the" before "result".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by maddog-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzYqsYN7_ChXppdQX:-KdlOMdu4GGffHA8CX_l:bpk4if3) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: missing "the" before "result".
</blockquote></details>

Done. (I have probably misspelled "the" now.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/automotive/maliput/api/road_geometry.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5302#-KdkzYqsYN7_ChXppdQX:-KdlOqG2oF29YLWVdZIJ:blf9xo4) ([raw file](https://github.com/robotlocomotion/drake/blob/c4dcf47d889134eeb14e009c31a7a97cc451b8ba/drake/automotive/maliput/api/road_geometry.h#L64)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done. (I have probably misspelled "the" now.)
</blockquote></details>

:laughing:  :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5302)*

**Pull request merged**
