### PR TITLE
[common] Make reset_after_move be conditionally noexcept

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15362)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one suggestion and a question.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15362#-:-MeRtxbWCJfju2DbKFHx:b-3zf0y5)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/reset_after_move.h, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15362#-MeRu2Zk0Aqp-9qFDJmO:-MeRu2Zk0Aqp-9qFDJmP:bult5h2) ([raw file](https://github.com/robotlocomotion/drake/blob/08f267f8b4977bcc567196530f1ed29a86245fbf/common/reset_after_move.h#L7)):*
> ```objc
> namespace drake {
> 
> // TODO(sherm1) Upgrade this to match reset_on_copy (e.g. noexcept).
> ```

There are still a number of ways this doesn't match reset_on_copy:
- conditional noexcept for default & copy constructor and copy assignment
- restriction to is_scalar types

If you're going to remove this TODO can you argue that there is no need to modify reset_after_move any further in the direction of reset_on_copy?
___
*[common/reset_after_move.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15362#-MeRss39CIfUFWOLlswf:-MeRss39CIfUFWOLlswg:bu2mrwv) ([raw file](https://github.com/robotlocomotion/drake/blob/f1842fa95188cb276c82bd35032ddcbf381909f8/common/reset_after_move.h#L67)):*
> ```objc
>   reset_after_move& operator=(const reset_after_move&) = default;
>   reset_after_move(reset_after_move&& other) noexcept(
>       std::is_nothrow_constructible_v<T> &&
> ```

BTW consider `std::is_nothrow_default_constructible_v<T>` instead as slightly more clear (same below).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15362)* status: needs at least two assigned reviewers (waiting on @sherm1)

___
*[common/reset_after_move.h, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15362#-MeRu2Zk0Aqp-9qFDJmO:-MeS2v725G--gz2mrZO-:bha25xj) ([raw file](https://github.com/robotlocomotion/drake/blob/08f267f8b4977bcc567196530f1ed29a86245fbf/common/reset_after_move.h#L7)):*
Done.

> conditional noexcept for default constructor

Good point, I might as well add that one while I'm here.  Done.

> conditional noexcept for copy constructor and copy assignment

Both this class and `reset_on_copy` use `= default` on those, which I believe is correct (the noexcept is computed based on the generated function).  I added test cases to confirm.

I also fixed the copy-from-unwrapped-rvalue constructor, with test.
___
*[common/reset_after_move.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15362#-MeRss39CIfUFWOLlswf:-MeS2YLf1R3F6KNBa6zd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1842fa95188cb276c82bd35032ddcbf381909f8/common/reset_after_move.h#L67)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `std::is_nothrow_default_constructible_v<T>` instead as slightly more clear (same below).
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15362)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15362#-:-MeVNzGWDmwWbucWWbpn:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri)

**Pull request merged**
