### PR TITLE
Improve default install destinations

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add logic to allow use of `@WORKSPACE@` placeholder in install destinations. Leverage this to simplify many install rules.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6411)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install.bzl, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-KnGX-btyiKUb_yyMFqO:-KnGX-btyiKUb_yyMFqP:bopvjs1) ([raw file](https://github.com/robotlocomotion/drake/blob/375582925d6a8431fdcc5c15ab5eec000a2cdfe5/tools/install.bzl#L357)):*
> ```Python
> whose files it is okay to install, which will suppress the warning.
> 
> Destination paths may include the placeholder ``@WORKSPACE``, which is replaced
> ```

Typo `@WORKSPACE@` (missing trailing @).

---

*[tools/yaml_cpp.BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-KnGX__4IQEzL0y-XMIo:-KnGX__4IQEzL0y-XMIp:b-hsoc2i) ([raw file](https://github.com/robotlocomotion/drake/blob/375582925d6a8431fdcc5c15ab5eec000a2cdfe5/tools/yaml_cpp.BUILD#L42)):*
> ```
>     license_docs = ["LICENSE"],
>     targets = [":yaml_cpp"],
>     workspace = "yaml-cpp",
> ```

BTW Should this become a named variable `CMAKE_PACKAGE` and reuse that in the prior two instances above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-:-KnGXjwsF8JiLs7IZ_2w:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-:-KnGeBFDluzftrbVqHUq:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 15 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install.bzl, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-KnGX-btyiKUb_yyMFqO:-KnKv4TTim29JRZU7Zxk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/375582925d6a8431fdcc5c15ab5eec000a2cdfe5/tools/install.bzl#L357)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Typo `@WORKSPACE@` (missing trailing @).
</blockquote></details>

Done.

---

*[tools/yaml_cpp.BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6411#-KnGX__4IQEzL0y-XMIo:-KnKv-7GaktB1o4L4Bk3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/375582925d6a8431fdcc5c15ab5eec000a2cdfe5/tools/yaml_cpp.BUILD#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this become a named variable `CMAKE_PACKAGE` and reuse that in the prior two instances above?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6411)*

**Comment by jamiesnape** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6411)*

**Pull request merged**
