### PR TITLE
Removes separate storage for outputs in favor of in-cache memory.

### PR DESCRIPTION
**Pull request by sherm1**
This is the next incremental extraction of caching code from #7668. PR #8920 ensured that every output port has in-Context memory allocated for it (in the Cache). This PR deletes all the old out-of-Context, uncacheable infrastructure for output port values, using the cached memory instead. 

With this PR SystemOutput becomes an unimportant sugar class for collecting output values; it is no longer part of the framework guts. These classes are gone: DiagramOutput, LeafSystemOutput, OutputPortValue.
AllocateOutput() no longer takes a context as input (there is still a soon-to-be-deprecated stub).

There should be no visible change to the API, and caching is still suppressed so although the cache memory is used every evaluation is a recalculation.

This PR is mostly code deletion:
```
Category            added  modified  removed  
----------------------------------------------
code                36     67        233      
comments            27     44        61       
blank               3      0         44       
----------------------------------------------
TOTAL               66     111       338      
```

Then a second commit renames `output_port_value*` files to `system_output*` with no further changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)

### CODE REVIEW

**Comment by sherm1** [comment]
+@jwnimmer-tri for feature review and +@sammy-tri for platform review, please.
This is a small one and mostly deletes a bunch of framework code that wasn't doing anything useful!

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LFPFoW999NuGaTa7hlV:b-847h78)*

**Comment by sherm1** [comment]
Reviewers: a second commit has only the file rename stuff. You could review that separately but Reviewable seems to have understood that so the diffs are sensible either way.

---

Review status: all discussions resolved, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LFPiJDxDWpqJxeS6Xr1:bixir80)*

**Comment by jwnimmer-tri** [comment]
Reviewed 9 of 11 files at r1, 16 of 16 files at r2.
Review status: 12 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[systems/framework/diagram_context.h, line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ9Y_456ydjzK1q1tI:-LFQ9Y_456ydjzK1q1tJ:b-et92tf) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/diagram_context.h#L181)):*
> ```objc
>   ///
>   /// User code should not call this method. It is for use during Diagram
>   /// context allocation only.
> ```

BTW The below method says "and cloning"; is that not also true for this method?

---

*[systems/framework/system.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRnEb4Wcz6IbPYihv:-LFPRnEb4Wcz6IbPYihw:brgjkt6) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L138)):*
> ```objc
>   /// for that port.
>   std::unique_ptr<SystemOutput<T>> AllocateOutput() const {
>     std::unique_ptr<SystemOutput<T>> output(new SystemOutput<T>);
> ```

nit prefer `make_unique` by convention.

---

*[systems/framework/system.h, line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRsm8Bbnw66XMkGge:-LFPRsm8Bbnw66XMkGgf:b560z8i) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L143)):*
> ```objc
>       output->add_port(port.Allocate());
>     }
>     return std::move(output);
> ```

nit `std::move` not required.

---

*[systems/framework/test/diagram_context_test.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ0nWh1OL1W-HqZsK4:-LFQ0nWh1OL1W-HqZsK5:b-sjc5lh) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/diagram_context_test.cc#L107)):*
> ```cpp
>   void AddSystem(const System<double>& sys, SubsystemIndex index) {
>     auto subcontext = sys.CreateDefaultContext();
>     context_->AddSystem(SubsystemIndex(index), std::move(subcontext));
> ```

nit The copying of `index` here is unnecessary.

---

*[systems/framework/output_port_value.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPSSa_1qtwln1FK-cU:-LFPSSaaAowC--WHGM8a:brkq2n1) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/output_port_value.h#L12)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/systems/framework/basic_vector.h"
> #include "drake/systems/framework/framework_common.h"
> ```

nit Unused?

---

*[systems/framework/output_port_value.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU6A5EoAX6X-faECy:-LFPU6A5EoAX6X-faECz:b2k8pue) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/output_port_value.h#L14)):*
> ```objc
> #include "drake/systems/framework/framework_common.h"
> #include "drake/systems/framework/value.h"
> #include "drake/systems/framework/value_checker.h"
> ```

nit Unused now.

---

*[systems/framework/output_port_value.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU9xM00I7HlDBHZ7p:-LFPU9xM00I7HlDBHZ7q:brm97x) ([raw file](https://github.com/robotlocomotion/drake/blob/51f582908bc572ed6cc086c7a923779e33db7f5e/systems/framework/output_port_value.h#L180)):*
> ```objc
>     // This check will mostly occur only once per System.
>     DRAKE_ASSERT_VOID(detail::CheckVectorValueInvariants<T>(
>         port->get_abstract_data()));
> ```

This removes the `detail::CheckVectorValueInvariants` check.  Is there some already intact call that takes its place?  I couldn't immediately tell for sure.

The intent here was that we do the very expensive clones-as-self test once early on.  Since OutputPortValue no longer exists and SystemOutput is now a toy rather than a core feature, it seems like this will need to find a better home now.

---

*[systems/framework/system_output.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPzqMuDJqHkxxy9i-1:-LFPzqMuDJqHkxxy9i-2:b57blxp) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L1)):*
> ```objc
> #pragma once
> ```

For the rename, the moderate amount of fallout in this PR (changing include statements tracking the rename of this file) is a signal that downstream code will likely also be impacted.  I would advocate that we keep flag days in core classes to a minimum.

Please consider adding back in a file with the old name, whose contents are (1) an include of the new name and (2) a `#warning` about deprecation.  It can be part of the same (now-renamed) `drake_cc_library` that this file appears in.

---

*[systems/framework/system_output.h, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ7fVB27Epd-7nbaCK:-LFQ7fVB27Epd-7nbaCL:b-v1vrc2) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L81)):*
> ```objc
>   void add_port(std::unique_ptr<AbstractValue> model_value) {
>     port_values_.emplace_back(std::move(model_value));
>   }
> ```

I'm slightly sad that this internal method leaks out to users.  I think I can live with it, but want to briefly discuss alternatives.

Initially, I didn't see a good answer.  However, maybe now I do...  What do you think about changing the SystemOutput ctor to take a `ModelValues` object, and then removing the ability here to dynamically add more ports (aka values)?  The single call site seems like it'd be ported easily enough.

---

*[systems/framework/system_output.h, line 84 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ5NDJEWu-ZGFo1lBy:-LFQ5NDKEzzPEIHtrll7:br7igpj) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L84)):*
> ```objc
> 
>   /** (Internal use only) Add a suitable BasicVector object to hold values for
>   the next output port. Still stored as an AbstractValue internally. */
> ```

This overload looks like dead code, even on the WIP branch.

---

*[systems/framework/test/system_output_test.cc, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ1itr8UHLBhHROKjQ:-LFQ1itr8UHLBhHROKjR:b7q7jwy) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L15)):*
> ```cpp
> namespace systems {
> ```

nit Extra blank line.

---

*[systems/framework/test/system_output_test.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2PGw2rvGwOklWBI0:-LFQ2PGw2rvGwOklWBI1:btggbmy) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L62)):*
> ```cpp
> // Tests that a copy of a SystemOutput has a deep copy of the data.
> TEST_F(SystemOutputTest, Copy) {
>   auto clone(output_);
> ```

nit `auto` is too-obscuring of the variable's type.

---

*[systems/framework/test/system_output_test.cc, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2aHT6SIego9c3roz:-LFQ2aHT6SIego9c3rp-:b-kmpqml) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L76)):*
> ```cpp
>   const BasicVector<double>* basic = clone.get_vector_data(1);
>   auto* my_vec = dynamic_cast<const MyVector<3, double>*>(basic);
>   ASSERT_NE(my_vec, nullptr);
> ```

FYI `is_dynamic_castable` from //common/test_utilities is nice.

---

*[systems/framework/test/system_output_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2iUxAJU6JGw7uti5:-LFQ2iUxAJU6JGw7uti6:b-xaznaw) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L82)):*
> ```cpp
>   EXPECT_EQ(expected, my_vec->get_value());
> 
>   EXPECT_EQ(clone.get_data(2)->GetValueOrThrow<std::string>(), "foo");
> ```

nit I'm unclear on what this is testing, beyond what L71 already did.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 11 files at r1, 16 of 16 files at r2.
Review status: 12 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by sherm1** [comment]
Checkpoint -- most review comments addressed.

---

Review status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[systems/framework/diagram_context.h, line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ9Y_456ydjzK1q1tI:-LFZ8loT6A_T9UV4U-Cj:b-xy5kii) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/diagram_context.h#L181)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The below method says "and cloning"; is that not also true for this method?
</blockquote></details>

Done. None of these are used in cloning because the dependency graph is copyable.

---

*[systems/framework/output_port_value.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPSSa_1qtwln1FK-cU:-LFZB6tF2e8xVdF8lMjZ:b-74c05d) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/output_port_value.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused?
</blockquote></details>

Done. Several of the STL includes were spurious also.

---

*[systems/framework/output_port_value.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU6A5EoAX6X-faECy:-LFZBC2l0MzKwJLxfKt4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/output_port_value.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused now.
</blockquote></details>

Done.

---

*[systems/framework/system.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRnEb4Wcz6IbPYihv:-LFZ8vkGBUCXqOUKkzzq:bjgqho) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit prefer `make_unique` by convention.
</blockquote></details>

Done. I searched for more of these in the framework and made a few opportunistic fixes. When constructors are protected, make_unique doesn't have access unless it is friended so it is not always possible to substitute :(

---

*[systems/framework/system.h, line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRsm8Bbnw66XMkGge:-LFZ9u8r6flrOhLUkL3x:b-e3iuj9) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `std::move` not required.
</blockquote></details>

Done. I searched for more of these in framework and nuked them also.

---

*[systems/framework/system_output.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPzqMuDJqHkxxy9i-1:-LFZA9Zi2IT6knGj9n2i:b-7axv9s) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For the rename, the moderate amount of fallout in this PR (changing include statements tracking the rename of this file) is a signal that downstream code will likely also be impacted.  I would advocate that we keep flag days in core classes to a minimum.

Please consider adding back in a file with the old name, whose contents are (1) an include of the new name and (2) a `#warning` about deprecation.  It can be part of the same (now-renamed) `drake_cc_library` that this file appears in.
</blockquote></details>

Done. For lack of a standard period I put a TODO there to nuke the file in 3 months.

---

*[systems/framework/test/system_output_test.cc, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ1itr8UHLBhHROKjQ:-LFZBTIM-ECZhplLcyTo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Extra blank line.
</blockquote></details>

Done.

---

*[systems/framework/test/system_output_test.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2PGw2rvGwOklWBI0:-LFZByLj8GZ96oPi8yi9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `auto` is too-obscuring of the variable's type.
</blockquote></details>

Done.

---

*[systems/framework/test/system_output_test.cc, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2aHT6SIego9c3roz:-LFZi3klCb2aicC7NWQg:bi2s5l1) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `is_dynamic_castable` from //common/test_utilities is nice.
</blockquote></details>

Done. Not quite as beautiful in practice here as I hoped!

---

*[systems/framework/test/system_output_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ2iUxAJU6JGw7uti5:-LFZipYsBaLcrIqQusko:b-2z0lv8) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/system_output_test.cc#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm unclear on what this is testing, beyond what L71 already did.
</blockquote></details>

Done. Looked vestigal.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LFZjuNpE0_rC7cDCRH7:b-clfuxd)*

**Comment by sherm1** [comment]
Tightened up SystemOutput so it can only be created by Systems now, PTAL.

---

Review status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[systems/framework/output_port_value.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU9xM00I7HlDBHZ7p:-LF_p4H0ChM1jvlHi2Cx:bqpvqfx) ([raw file](https://github.com/robotlocomotion/drake/blob/51f582908bc572ed6cc086c7a923779e33db7f5e/systems/framework/output_port_value.h#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This removes the `detail::CheckVectorValueInvariants` check.  Is there some already intact call that takes its place?  I couldn't immediately tell for sure.

The intent here was that we do the very expensive clones-as-self test once early on.  Since OutputPortValue no longer exists and SystemOutput is now a toy rather than a core feature, it seems like this will need to find a better home now.
</blockquote></details>

OK, now that this method is private this can only get a bad vector if the System's output port was already broken -- that should have been caught long before.

---

*[systems/framework/system_output.h, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ7fVB27Epd-7nbaCK:-LF_o8cr3OI0sG6fuonm:br5eghr) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm slightly sad that this internal method leaks out to users.  I think I can live with it, but want to briefly discuss alternatives.

Initially, I didn't see a good answer.  However, maybe now I do...  What do you think about changing the SystemOutput ctor to take a `ModelValues` object, and then removing the ability here to dynamically add more ports (aka values)?  The single call site seems like it'd be ported easily enough.
</blockquote></details>

Done. Construction is now private with System a friend. I like this better than the ModelValues constructor because users shouldn't be creating these objects anyway. If they want their own container of AbstractValues, they can use ModelValues directly. SystemOutput should always be produced by a System (or copied from one of those).

---

*[systems/framework/system_output.h, line 84 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ5NDJEWu-ZGFo1lBy:-LF_oqXI0VKihhTx2iHR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/system_output.h#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This overload looks like dead code, even on the WIP branch.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LF_pVT60beV6MLOfpmf:b2ffrce)*

**Comment by sherm1** [comment]
All review comments addressed -- ready for another look, @sammy-tri .

---

Review status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[systems/framework/test/diagram_context_test.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFQ0nWh1OL1W-HqZsK4:-LF_qUbg8ryKuxrIyRhz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c902772f0adfccea86bb34901e439887821e9e1/systems/framework/test/diagram_context_test.cc#L107)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The copying of `index` here is unnecessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LF_qZRi-Shlbn9gIb-i:b7g590m)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r3, 4 of 4 files at r4.
Review status: 3 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM from [jwnimmer-tri]

---

*[systems/framework/diagram.h, line 255 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_BiQM3WWMNDOJTVHD:-LF_BiQM3WWMNDOJTVHE:b-ncnn4b) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/diagram.h#L255)):*
> ```objc
>       sub_derivatives.push_back(system->AllocateTimeDerivatives());
>     }
>     return std::unique_ptr<ContinuousState<T>>(
> ```

FYI Explicitly naming the conversion ctor is unnecessary.

---

*[systems/framework/diagram.h, line 268 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_Ba992hW5QDNRhp3Y:-LF_Ba9A3MDv90SX6Sgg:b-ncnn4b) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/diagram.h#L268)):*
> ```objc
>       sub_discretes.push_back(system->AllocateDiscreteVariables());
>     }
>     return std::unique_ptr<DiscreteValues<T>>(
> ```

FYI Explicitly naming the conversion ctor is unnecessary.

---

*[systems/framework/output_port_value.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU9xM00I7HlDBHZ7p:-LFbD56gCZhJL2r7JjFc:br9k1tz) ([raw file](https://github.com/robotlocomotion/drake/blob/51f582908bc572ed6cc086c7a923779e33db7f5e/systems/framework/output_port_value.h#L180)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

OK, now that this method is private this can only get a bad vector if the System's output port was already broken -- that should have been caught long before.
</blockquote></details>

I think this check was slightly different that what I recall setting within the framework changes, e.g., the new SystemBase checks.  I'll go looking / test locally a bit later on this morning.

---

*[systems/framework/output_port_value.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_Bph45MoIUsgskb7A:-LF_Bph45MoIUsgskb7B:bgf8pl6) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/output_port_value.h#L1)):*
> ```objc
> // TODO(sherm1) Remove this file after 10/1/2018 (3 months).
> ```

nit Missing `#pragma once`.

---

*[systems/framework/test/system_output_test.cc, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFbCShXCFekxEBrBV1x:-LFbCShXCFekxEBrBV1y:b-6zx1sn) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/test/system_output_test.cc#L16)):*
> ```cpp
> namespace systems {
> 
> class SystemOutputTest : public ::testing::Test {
> ```

FYI Jenkins is upset that this line got lost.

---

*[systems/framework/test/system_output_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_C7Yx2Daq_vKMhXCP:-LF_C7Yx2Daq_vKMhXCQ:b-pgn2e4) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/test/system_output_test.cc#L76)):*
> ```cpp
>   const BasicVector<double>* basic = copy.get_vector_data(1);
>   ASSERT_TRUE((is_dynamic_castable<const MyVector<3, double>>(basic)));
>   auto& my_vec = dynamic_cast<const MyVector<3, double>&>(*basic);
> ```

nit Downcasting here seems unnecessary?  The only thing we call is `get_value`, which can be called on`basic` already.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LF_CV0g7zCDn-Q64kj0:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, platform LGTM from [jwnimmer-tri], commit history needs curation

---

*[systems/framework/output_port_value.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPU9xM00I7HlDBHZ7p:-LFbng_wDisQDUzmBMTu:b-i60zpy) ([raw file](https://github.com/robotlocomotion/drake/blob/51f582908bc572ed6cc086c7a923779e33db7f5e/systems/framework/output_port_value.h#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this check was slightly different that what I recall setting within the framework changes, e.g., the new SystemBase checks.  I'll go looking / test locally a bit later on this morning.
</blockquote></details>

OK So in a61ceda I added this invariant checker with unit test, but no integration test.  From looking locally, this change is indeed a regression but as they say, _"If you liked it, then you should have put a test on it "_.  I'll submit that test as well as the fix in my own future PR.  (I think the best new place for this check is going to be in the CacheEntry constructor.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by sammy-tri** [comment]
:lgtm: (pending CI)

---

Reviewed 12 of 15 files at r3, 4 of 4 files at r4.
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri, sammy-tri], commit history needs curation

---

*[systems/framework/system.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRnEb4Wcz6IbPYihv:-LFbtM5z9fI_ZNuLse3e:b-tccsam) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L138)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. I searched for more of these in the framework and made a few opportunistic fixes. When constructors are protected, make_unique doesn't have access unless it is friended so it is not always possible to substitute :(
</blockquote></details>

Is this convention documented somewhere?  (I for one have no objections to this style, and even less objection to how the code below in `system_base.h` was written which used `new` to initialize `copyable_unique_ptr`)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028#-:-LFbuU_T7rfkYbway51E:b-lj32db)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri, sammy-tri], commit history needs curation

---

*[systems/framework/system.h, line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFPRnEb4Wcz6IbPYihv:-LFbums7Bf4PXkJb2nm5:b-auxml6) ([raw file](https://github.com/robotlocomotion/drake/blob/00f8de2b53e605c2b96fc20a724710a08b937e3a/systems/framework/system.h#L138)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this convention documented somewhere?  (I for one have no objections to this style, and even less objection to how the code below in `system_base.h` was written which used `new` to initialize `copyable_unique_ptr`)
</blockquote></details>

This particular change I would say is author's discretion -- I didn't realize that the constructor wasn't public (or maybe it wasn't, when I posted).  My interpretation of the correct convention is "every single instance of directly calling `new` is suspicious by rote, and deserves a comment unless the rationale is already obvious".

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by sherm1** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, sammy-tri]

---

*[systems/framework/diagram.h, line 255 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_BiQM3WWMNDOJTVHD:-LFc72B-12lHVaZfksLe:b-65e5pe) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/diagram.h#L255)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Explicitly naming the conversion ctor is unnecessary.
</blockquote></details>

Done -- thanks. Someday I'll get these right without you having to point them out :(

---

*[systems/framework/diagram.h, line 268 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_Ba992hW5QDNRhp3Y:-LFc79OYEkWOm0e86uv3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/diagram.h#L268)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Explicitly naming the conversion ctor is unnecessary.
</blockquote></details>

Done.

---

*[systems/framework/output_port_value.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_Bph45MoIUsgskb7A:-LFc4ciH4p8kTr-PADJo:bnplcr7) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/output_port_value.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing `#pragma once`.
</blockquote></details>

Done. I removed it intentionally to ensure that an annoying warning would appear for each inclusion. It is a styleguide violation though so I added an explanation.

---

*[systems/framework/test/system_output_test.cc, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LFbCShXCFekxEBrBV1x:-LFc7D7X6zuBItNNG87b:b-h41l8) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/test/system_output_test.cc#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Jenkins is upset that this line got lost.
</blockquote></details>

Done. "But I only added a comment! No need to retest before pushing." :man_facepalming: 

---

*[systems/framework/test/system_output_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9028#-LF_C7Yx2Daq_vKMhXCP:-LFc8PhF11EBh14NlDsa:b-oizqfr) ([raw file](https://github.com/robotlocomotion/drake/blob/6432f042b87c6e56474cf764dfe2577764585581/systems/framework/test/system_output_test.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Downcasting here seems unnecessary?  The only thing we call is `get_value`, which can be called on`basic` already.
</blockquote></details>

Done -- now the `is_dynamic_castable` does look better!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9028)*

**Comment by sherm1** [comment]
Thanks @jwnimmer-tri and @sammy-tri !

**Pull request merged**
