### PR TITLE
[py math] Start to split bindings into separate files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This resets the git history for our `matmul` binding, but it's fairly new (so not too much is lost) and tracing it across the file shuffle isn't too difficult, anyway.

The only change to the cut-and-paste code is the namespace and matching new the `math_py.h` declared function names.

Towards #20491.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20490)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.  (To avoid overloading Rico today.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

With a couple of cosmetic thoughts.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-:-Nig4V422d23HdGhH1j0:b5sows)* status: 2 unresolved discussions

___
*[`bindings/pydrake/math/math_py.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-Nig3FpIDyUJG1XMzG2q:-Nig3FpIDyUJG1XMzG2r:b-zhurfl) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae6550ef8aabac794f2e8db1283b59830f7966c0/bindings/pydrake/math/math_py.h#L25)):*
> ```objc
> 
> /* Defines bindings per math_py_monolith.cc. */
> void DefineMathMonolith(py::module m);
> ```

BTW The implicit convention I've used and seen is that the declarations tend to be in the same order as they'd be executed. That isn't the case here. Is that something we want to encourage? Enforce? Ignore?
___
*[`bindings/pydrake/math/math_py_operators.cc` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-Nig4Fzf3DD8Jv8Jc9d2:-Nig4Fzf3DD8Jv8Jc9d3:b-49zy68) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae6550ef8aabac794f2e8db1283b59830f7966c0/bindings/pydrake/math/math_py_operators.cc#L12)):*
> ```cpp
> void DefineMathOperators(py::module m) {
>   // Define math operations for all three scalar types.
>   // See TODO in corresponding header file - these should be removed soon!
> ```

BTW "corresponding header file" may now be a big vague. Presumably, this refers to `math_operators_pybind.h`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20490)* status: 1 unresolved discussion

___
*[`bindings/pydrake/math/math_py.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-Nig3FpIDyUJG1XMzG2q:-NigAewV3fGsDvYefeco:bpqd448) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae6550ef8aabac794f2e8db1283b59830f7966c0/bindings/pydrake/math/math_py.h#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The implicit convention I've used and seen is that the declarations tend to be in the same order as they'd be executed. That isn't the case here. Is that something we want to encourage? Enforce? Ignore?
</blockquote></details>

All the other ones I can find are in alpha-order.  Can you given an example of topo-order?  (My vote would be to always use alpha-order in these files, so that the topo-order is only ever encoded in _one_ place -- the place where the actual loading code is being run.)
___
*[`bindings/pydrake/math/math_py_operators.cc` line 12 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-Nig4Fzf3DD8Jv8Jc9d2:-NigB8iw9E1kEN3NFhV7:b-ou1e0c) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae6550ef8aabac794f2e8db1283b59830f7966c0/bindings/pydrake/math/math_py_operators.cc#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "corresponding header file" may now be a big vague. Presumably, this refers to `math_operators_pybind.h`.
</blockquote></details>

Yes, I _think_ that's probably what it was referring to -- but in any case, having a TODO in one place is plenty.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20490)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[`bindings/pydrake/math/math_py.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20490#-Nig3FpIDyUJG1XMzG2q:-NijNEQh7bdhmqY_qwDH:b-ra7vx8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae6550ef8aabac794f2e8db1283b59830f7966c0/bindings/pydrake/math/math_py.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

All the other ones I can find are in alpha-order.  Can you given an example of topo-order?  (My vote would be to always use alpha-order in these files, so that the topo-order is only ever encoded in _one_ place -- the place where the actual loading code is being run.)
</blockquote></details>

Excellent point. Happily retracted.

**Pull request merged**
