### PR TITLE
[examples] Deleting the particles example

### LINKED ISSUE #17649: particles example doesn't visualize because it incorrectly uses AllocateContext
### What happened?

As I have raised in https://github.com/RobotLocomotion/drake-external-examples/issues/233, I found that the particle example did not draw in the visualizer. The example in the drake-external-examples repo is the same as that in the drake repo: https://github.com/RobotLocomotion/drake/tree/master/examples/particles.

I was noticing that neither the OutputPose callback of the geometry nor the OutputState callback of the particle system (connected to geometry) was being called during the simulation.
Besides, a simple anchored geometry registered to the scene_graph is also not showing.
However, the state of the particle and the calculating of the time derivative is working properly. 
 
After some diggings and comparison with the scene_graph [examples](https://github.com/RobotLocomotion/drake/tree/master/examples/scene_graph), I finally managed to have the particle moved and shown correctly by replacing `builder.BuildInto(this);` in the constructor of UniformlyAcceleratedParticle with `builder.Build();` (and having the simulation inside the constructor).

It seems that the BuildInto method might have some problems in handling stuff with scene_graph.

### Version

_No response_

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

apt install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
While the particles example illustrates the absolutely simplest possible dynamics system (with a non-zero acceleration), that is its *only* value. Visualizing it shows a sphere instantly racing out of view and the
code manifests an anti-pattern (using `AllocateContext()` instead of `CreateDefaultContext()`).

As there are other examples that introduce bespoke continuous systems (e.g., pendulum), this examples contribution is not justified.

closes #17649

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17653)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

+@ggould-tri for both reviews on Monday.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17653#-:-N89gm6_3YuqYfsjoRXz:b-ko2wz9)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: breaking change) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17653#-:-N89gt1e1-on_z1P6hPO:b-39summ)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Comment by jwnimmer-tri** [comment]
Per https://drake.mit.edu/stable.html#c, I don't think this is "breaking change" (because it's in the `examples` directory).

**Comment by SeanCurtis-TRI** [comment]
I had a hard time wrestling with that. Given that release notes *explicitly* have a "Tutorial and examples" section and we document changes to examples in the release notes, it seemed the removal of an example would count. I'd read the `reviewable.md` documentation to get that, but, you're right, the `stable.md` documentation is much more to point.

However, while that's an argument for why it's not "breaking", "none" feels wrong because it seems we *should* have some mention of the fact that we've removed an example in the release notes. Is this a "fix"?

-(release notes: breaking change)

**Comment by jwnimmer-tri** [comment]
Right, if you think it's notable, but neither breaking nor deprecation, that leaves either "feature" or "fix".  Dealer's choice.  It doesn't matter.

**Comment by SeanCurtis-TRI** [comment]
+(release notes: fix)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: and I concur that 'fix' is appropriate and probably won't too badly befuddle the release engineer :-)

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17653#-:-N8OeG787xSNH-lt-Ffn:b4klpiv)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
