### PR TITLE
Add std::experimental::optional to third party

### LINKED ISSUE #5526: Introduce `optional<T>.` functionality
The C++17 specification includes the `std::optional<T>` class.  It allows functions return values that sometimes have values and sometimes don't.  This is of definite use.  We can't wait on having a compliant compiler so we need to introduce this ourselves.

The simplest way is to draw from this repo: https://github.com/akrzemi1/Optional

It should be added to `drake/thirdParty/boost` (as it uses a boost license).  The first person to hit the point where they need this should add it.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This takes the code from https://github.com/akrzemi1/Optional and adds it to `drake/thirdParty`; it is drawn from commit `25713110f55813b2c5619ec1230edf8d3b00bdde`.

resolves #5526

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5574)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@soonho-tri for platform review.  I suspect that no feature reviewer is required as this just adds third party code.

/cc @jwnimmer-tri @amcastro-tri 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-KfhNcIcT40ebXIj4DZW:b-yra5js)*

**Comment by jwnimmer-tri** [comment]
This appers to omit some of the bookkeeping tasks that I explained to @amcastro-tri, such as tracking the upstream `URL` and `commit` that the code was copied from.

**Comment by SeanCurtis-TRI** [comment]
I was wondering about that.  I missed the details of the explanation about what it takes to introduce third party software, and the `README.md` didn't indicate any additional details.

When you get a better look, I can correct the PR *and* update the readme to reflect instructions for the future.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-KfhQZykcXlG5xCi5J9q:bi9e7y3)*

**Comment by amcastro-tri** [comment]
What we discussed with @jwnimmer-tri is that code in `thirdParty` should be pushed within a single PR that has message like so: "Code obtained from https://github.com/akrzemi1/Optional with commit hash 25713110f55813b2c5619ec1230edf8d3b00bdde"

Where the URL specifies the repository where this code is taken from and we also provide the full commit hash of the version we copied. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-KfhWUWe_QxSiTlFXclk:b9ctqvx)*

**Comment by SeanCurtis-TRI** [comment]
Ah...so the message goes in the PR description?

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-Kfhas-8erzfppzwwvLN:b98013r)*

**Comment by SeanCurtis-TRI** [comment]
Although, I should probably pull the PR to satisfy the two-stage: "add-third-party-code", "modify-drake" (although, in this case, the modification consists of adding it to bazel).  I'll wait for @jwnimmer-tri to give the official world and otherwise just let it hang out.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-KfhbN_5x6GoyGB4TWEL:b-a6bmu5)*

**Comment by amcastro-tri** [comment]
> Ah...so the message goes in the PR description?

That is what I understood from our f2f with @jwnimmer-tri. I was trying to find a similar message with previous third parties but it seems like they all got added in the past before TRI and they do not abide by this practice.

> I should probably pull the PR to satisfy the two-stage: "add-third-party-code", "modify-drake" (although, in this case, the modification consists of adding it to bazel).

I think with the above message is ok. But yes, lets wait to hear from @jwnimmer-tri 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-KfhgK0ySB6d9Z32n71q:br8bn85)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri , sounds like it's more reasonable for you to platform-review this :-)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-Kfhmeh-CX0eUCBRuhx9:b-e3sb8e)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri -@soonho-tri
Oops, it was never tagged to me so wasn't in my dashboard.  I will start on it in a bit.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , thank you!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-Kflv_1Fv09tAvoW1Jms:bpn644e)*

**Comment by SeanCurtis-TRI** [comment]
I think you can defer this to your normal day.  I've shifted what I'm working on so it's not particularly critical.  

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-Kfly_TfdN9BXdejTGCR:b-qo0dbk)*

**Comment by amcastro-tri** [comment]
I am glad you are working on integrating this @SeanCurtis-TRI. I am only one PR away from start testing it (namely #5583). With frames in we can start thinking about connecting bodies in a more meaningful way and then `optional` will make it into the topology structures.

**Comment by jwnimmer-tri** [comment]
So in researching this, I instead came up with #5593 which is perhaps better.  Let's see if we like that PR (maybe test it for your needs locally?) and then we could close this one.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5574#-:-Kfrkm4tDuLx7dK6M7v0:b-5ddems)*

**Comment by jwnimmer-tri** [comment]
Looks like #5593 is good, this one can probably close.

**Comment by SeanCurtis-TRI** [comment]
Replaced by the more elegant #5593

**Pull request closed without merging**
