### PR TITLE
[parsing] Switch drake_models to a remote package

### LINKED ISSUE #15774: pip install: Fetch platform-independent data
Working towards #1183

Follow up to #15628

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15774.

---

Local testing of a CMake install:

```console
$ bazel run //:install -- /home/jwnimmer/tmp/install
$ cd ~/tmp
$ env PYTHONPATH=install/lib/python3.10/site-packages python3
>>> from pydrake.all import PackageMap
>>> PackageMap().GetPath("drake_models")
INFO:drake:PackageMap: Downloading https://github.com/RobotLocomotion/models/archive/6751ba850fd46fee789a095edba7ad9fc99cd188.tar.gz
'/home/jwnimmer/.cache/drake/package_map/dc38658f7acb4d07442e6dae4d18818d31ac6cc6d66bf16913ef1b208692627c'
```

---

Local testing of an Ubuntu Wheel install:

```console
$ cd tmp
$ python3 -m venv env && env/bin/pip install 'https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2023.3.24.16.25.24%2Bgit0cd06a59-cp310-cp310-manylinux_2_31_x86_64.whl'
$ env/bin/python3
>>> from pydrake.all import *
>>> path = PackageMap().GetPath("drake_models")
INFO:drake:PackageMap: Downloading https://github.com/RobotLocomotion/models/archive/6751ba850fd46fee789a095edba7ad9fc99cd188.tar.gz
>>> with open(f"{path}/README.md") as f: f.read()
'# models\n\nShareable large model files ...'
```

---

Local testing of a macOS Wheel install:

```console
% cd tmp
% python3 -m venv env && env/bin/pip install 'https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2023.3.24.12.26.16%2Bgit0cd06a59-cp311-cp311-macosx_12_0_arm64.whl'
% env/bin/python3
>>> from pydrake.all import *
>>> path = PackageMap().GetPath("drake_models")
INFO:drake:PackageMap: Downloading https://github.com/RobotLocomotion/models/archive/6751ba850fd46fee789a095edba7ad9fc99cd188.tar.gz
>>> with open(f"{path}/README.md") as f: f.read()
... 
'# models\n\nShareable large model files ...'
```

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19046)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19046)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19046#-NRJIsnZ43z3Fv5ox0P4:-NRJtQQaCxnh2atk2RX7:b-3izg2t) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Wheel testing.  (Pending #19059.)
</blockquote></details>

Seems OK.  I pasted the results into the PR overview.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 16 files at r2, 1 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19046#-:-NRZh9Kg9pO04J3PkF-Q:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 114 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19046#-NRZFkT30CJRcEWTxFbN:-NRZFkT30CJRcEWTxFbO:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6752e6176ce3fd30f9dd85a334d8683c377bba7/tools/install/bazel/test/drake_bazel_installed_test.py#L114)):*
> ```Python
>     with open(join(scratch_dir, "package_map_test.py"), "w") as f:
>         f.write("""
> # The install_test runner provides a prepoulated XDG_CACHE_HOME.
> ```

typo



_Suggestion:_
```Python
pre-populated
```
___
*[`tools/wheel/image/build-wheel.sh` line 101 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19046#-NRZH4HP58vQoK4q0cV7:-NRZH4HP58vQoK4q0cV8:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/e6752e6176ce3fd30f9dd85a334d8683c377bba7/tools/wheel/image/build-wheel.sh#L101)):*
> ```Shell
> 
> # TODO(jwnimmer-tri) We need to remove this to keep the wheel from being too
> # large, but atlas's meshes should move drake_models anyway.
> ```

typo?



_Suggestion:_
```Shell
move into drake_models
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (CI issues appear to be unrelated)

> Reviewed 9 of 16 files at r2, 1 of 2 files at r3, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19046#-:-NRZse8OBB3aC87fqeu1:bofmmad)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Pull request merged**
