### PR TITLE
Additional optimization (QP) problem added

### PR DESCRIPTION
**Pull request by naveenoid**
Towards integrating Gurobi, it would be good to have additional QP problems in the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2529)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Aside from two trivial comments below, I'll wait for @lucy-tri to do the feature review.

<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> #### Additional optimization \(QP\) problem added
> 
> Towards integrating Gurobi, it would be good to have additional QP problems in the tests.
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/NoGurobi.cpp.cpp, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuR5EbfGP3Mq1ryrbF:-KJuR5EbfGP3Mq1ryrbG:499486912) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L1)):*
> ```cpp
> //
> ```

Even if we accept the other things out of style in this filename (as we have been in `drake/solvers`), it definitely has one too many `.cpp`s.  ;-)

https://google.github.io/styleguide/cppguide.html#File_Names

---

*[drake/solvers/NoGurobi.cpp.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuRFl9LP7qa-aFeZOd:-KJuRFl9LP7qa-aFeZOe:1705974081) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L2)):*
> ```cpp
> //
> // Created by Naveen Kuppuswamy on 09/06/16.
> ```

We haven't been using comments like this elsewhere in Drake, and it seems redundant with the data git will store.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KJuQmD1ilJ5dbcJMIrz:1815805725)*

**Comment by naveenoid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/NoGurobi.cpp.cpp, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuR5EbfGP3Mq1ryrbF:-KJuSBrbjQd4M3vFD9Ot:-11215972) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Even if we accept the other things out of style in this filename (as we have been in `drake/solvers`), it definitely has one too many `.cpp`s.  ;-)
> 
> https://google.github.io/styleguide/cppguide.html#File_Names
</details>
This file should not be part of this commit...fixing asap. Its from my next PR

---

*[drake/solvers/NoGurobi.cpp.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuRFl9LP7qa-aFeZOd:-KJuSWvwQB83HOg1sIWo:-1140650836) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L2)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> We haven't been using comments like this elsewhere in Drake, and it seems redundant with the data git will store.
</details>
Again..should not have been part of this PR. Fixing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by Lucy-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Aside from two trivial comments below, I'll wait for @lucy-tri to do the feature review.
</details>


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KJw3HeMPfoobf2TTnuR:1417088721)*

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> jenkins: retest this please
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 232 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJw4ubXAgEG5T7HW7YR:-KJw4ubXAgEG5T7HW7YS:-1697614740) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L232)):*
> ```cpp
> 
> GTEST_TEST(testOptimizationProblem, testProblem2) {
> OptimizationProblem prog;
> ```

nit: +2 indent, and also some other whitespace oddities farther down.  Consider running clang-format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KJw5UONdL9PZY1iQfn1:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK-WpRcrUKMI3JGPb4_:-KK-WpRdnwJto31I2ndH:2093130472) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
> ```cpp
> 
> // This test comes from Section 2.3 of "Handbook of Test Problems in
> // Local and Global Optimization"
> ```

BTW: nit: missing period at end of sentence.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 266 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3QWLGCtQm4mMONJYU:-KK3QWLGCtQm4mMONJYV:2093130472) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L266)):*
> ```cpp
> 
> // This test comes from Section 3.4 of "Handbook of Test Problems in
> // Local and Global Optimization"
> ```

BTW: nit: missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK3ldgHgtUnZ_mf-LrU:-1661225937) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
> ```cpp
> 
> // This test comes from Section 2.3 of "Handbook of Test Problems in
> // Local and Global Optimization"
> ```

Consider: it'd be really useful (and neat) to have a [Latex description](http://www.stack.nl/~dimitri/doxygen/manual/formulas.html)  of the problem being solved for those not having the book. 

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 259 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3nnKoshlPeauXueBA:-KK3nnKpXEtOxzb0dyD4:-1073380999) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L259)):*
> ```cpp
> 
> RunNonlinearProgram(prog, [&]() {
> EXPECT_TRUE(CompareMatrices(x.value(), expected, 1e-10,
> ```

BTW: why this tolerance? does it have to do with the solver's default tolerance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by liangfok** [comment]
*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK46YHlCfI1clRNXhrj:-189769641) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider: it'd be really useful (and neat) to have a [Latex description](http://www.stack.nl/~dimitri/doxygen/manual/formulas.html)  of the problem being solved for those not having the book. 
</details>
Is there a concern about copyright?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK4KMmlVN6fC8D1fo1o:266668868) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Is there a concern about copyright?
</details>
Honestly dont know..and verifying right now. I dont see how replicating a mathematical problem can be a copyright violation..but IANAL. @sammy-tri or @ggould-tri any info on this?

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 232 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJw4ubXAgEG5T7HW7YR:-KK4KasfWgIHd0h9sXYN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L232)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: +2 indent, and also some other whitespace oddities farther down.  Consider running clang-format.
</details>
Done.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 259 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3nnKoshlPeauXueBA:-KK4KeNA_CAKjVz78Vgy:-56345941) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L259)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW: why this tolerance? does it have to do with the solver's default tolerance?
</details>
@sammy-tri could you maybe answer this? Since I guess, it relates to the expected solution accuracy for SNOPT and NlOpt ..

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 266 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3QWLGCtQm4mMONJYU:-KK4Kjw25o0l9LETJY70:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L266)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing period at end of sentence.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK5mcnA9PI85pcKMk2Z:-55506731) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Honestly dont know..and verifying right now. I dont see how replicating a mathematical problem can be a copyright violation..but IANAL. @sammy-tri or @ggould-tri any info on this?
</details>
No copyright worries -- even if you copied it exactly it would be fair use. But if you produce your own version it isn't even clear that you are using copyrighted material. No one owns a particular equation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK5u79dKeH5Unnu7yVj:-1847879760) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> No copyright worries -- even if you copied it exactly it would be fair use. But if you produce your own version it isn't even clear that you are using copyrighted material. No one owns a particular equation.
</details>
SGTM. +1 for a LaTeX document spelling out the optimization problem being evaluated here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK88zLs_TeB3icE1tju:-1247420486) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> SGTM. +1 for a LaTeX document spelling out the optimization problem being evaluated here.
</details>
Even though most tests dont seem to be doxygen'ated should I just go ahead and add doxygen style latex equations here for the optimization problem?

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 259 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3nnKoshlPeauXueBA:-KK89D9OFVcMp9QSkzeM:-1244238122) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L259)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> @sammy-tri could you maybe answer this? Since I guess, it relates to the expected solution accuracy for SNOPT and NlOpt ..
</details>
FYI tests showed that obtained accuracy is just below that value (a variable supposed to be 0 at min was computed as ~1.5e-11

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by Lucy-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK8yeLUqqD2a7NkI3TK:-1133565486) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Even though most tests dont seem to be doxygen'ated should I just go ahead and add doxygen style latex equations here for the optimization problem?
</details>
Consider making a new Issue/PR to add descriptions of the equations used in tests, if indeed we have not yet documented the actual equations. 

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 101 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK8xtYgd8EIQXmuwCqe:-KK8xtYgd8EIQXmuwCqf:-1820465102) ([raw file](https://github.com/robotlocomotion/drake/blob/9b3fd99307c14efeac88e0f0c4aa0ab601945c32/drake/solvers/test/testOptimizationProblem.cpp#L101)):*
> ```cpp
>     SolutionResult result = SolutionResult::kUnknownError;
>     ASSERT_NO_THROW(result = solver.second->Solve(prog)) << "Using solver: "
>                                                          << solver.first;
> ```

It should be solver.second, right?  You are using solver.second. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KK9-HB6kmUx5ldZ6z9u:1417088721)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KK9FrVWecTp5A35R_SI:99199190) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Consider making a new Issue/PR to add descriptions of the equations used in tests, if indeed we have not yet documented the actual equations. 
</details>
https://github.com/RobotLocomotion/drake/issues/2549

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 101 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK8xtYgd8EIQXmuwCqe:-KK9FDaZkpvO2sJ9ulFq:794908477) ([raw file](https://github.com/robotlocomotion/drake/blob/9b3fd99307c14efeac88e0f0c4aa0ab601945c32/drake/solvers/test/testOptimizationProblem.cpp#L101)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> It should be solver.second, right?  You are using solver.second. 
</details>
I guess it should be solver.first since its the name of the selected solver..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 101 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK8xtYgd8EIQXmuwCqe:-KK9QRWTwLnfvDlAmNbG:677266559) ([raw file](https://github.com/robotlocomotion/drake/blob/9b3fd99307c14efeac88e0f0c4aa0ab601945c32/drake/solvers/test/testOptimizationProblem.cpp#L101)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> I guess it should be solver.first since its the name of the selected solver..
</details>
Yup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 266 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3QWLGCtQm4mMONJYU:-KK9UKVWDHu0uTp1j7Qe:-1956713963) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L266)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Done.
</details>
No change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 266 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3QWLGCtQm4mMONJYU:-KKAfAPVDZ7AvGRSO8Jh:-307188120) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L266)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> No change?
</details>
Fixed in latest commit. Additional changes will be addressed in new PR to fit https://github.com/RobotLocomotion/drake/issues/2549

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by liangfok** [comment]
:lgtm:

<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 266 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3QWLGCtQm4mMONJYU:-KKAfWoLQNv75SXfH1pk:-317356635) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L266)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Fixed in latest commit. Additional changes will be addressed in new PR to fit https://github.com/RobotLocomotion/drake/issues/2549
</details>
Looks good. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KKAfhEEihOhIK2jpJ8f:980077401)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 213 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK3ldgHgtUnZ_mf-LrT:-KKAfweXPpq3yduCuX85:1625410702) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L213)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> https://github.com/RobotLocomotion/drake/issues/2549
</details>
To be taken up in new PR

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 232 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJw4ubXAgEG5T7HW7YR:-KKAgOT5o-8pWqcOk_cY:5173697) ([raw file](https://github.com/robotlocomotion/drake/blob/1de7de2618e65db2f5ab6e490700436fc217c469/drake/solvers/test/testOptimizationProblem.cpp#L232)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Done.
</details>
Ok

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 101 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK8xtYgd8EIQXmuwCqe:-KKAfs0d0oWbInIfGGUW:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9b3fd99307c14efeac88e0f0c4aa0ab601945c32/drake/solvers/test/testOptimizationProblem.cpp#L101)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Yup.
</details>
Done.

---

*[drake/solvers/NoGurobi.cpp.cpp, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuR5EbfGP3Mq1ryrbF:-KKAh19AVTT8n8dF5izt:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L1)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> This file should not be part of this commit...fixing asap. Its from my next PR
</details>
Done.

---

*[drake/solvers/NoGurobi.cpp.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KJuRFl9LP7qa-aFeZOd:-KKAh2LusRl6rKRJbvS_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/289b92b1b4dd4a50ed7190eee07e085981a0203c/drake/solvers/NoGurobi.cpp.cpp#L2)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Again..should not have been part of this PR. Fixing
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 101 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-KK8xtYgd8EIQXmuwCqe:-KKAi7heGFad8mz3Jjgp:873629628) ([raw file](https://github.com/robotlocomotion/drake/blob/9b3fd99307c14efeac88e0f0c4aa0ab601945c32/drake/solvers/test/testOptimizationProblem.cpp#L101)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Done.
</details>
Can I close this @lucy-tri ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2529#-:-KKEV28AzcRFCAA-FNdo:1417088721)*

**Pull request merged**
