### PR TITLE
 solvers: Deprecate the mutable Solve() APIs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
~This is just a CI testing branch for now.~ 

~_Edit: Waiting on #10420 and #10709 to merge first, but the final commit here (the only one that will remain once other PRs merge) is ready to go._~

Relates #9633.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10681)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[attic/multibody/global_inverse_kinematics.cc, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10681#-LZ5fBB12Yy50A95Rv6a:-LZ5fBB12Yy50A95Rv6b:brtew9h) ([raw file](https://github.com/robotlocomotion/drake/blob/74b398611f8342f20ef250f6cfc49d0a2055498c/attic/multibody/global_inverse_kinematics.cc#L172)):*
> ```cpp
> }
> 
> void GlobalInverseKinematics::ReconstructGeneralizedPositionSolutionForBody(
> ```

FYI For RBT global IK, in this PR we do not provide an API path forward for the user.  I think we should deprecate this class (3 month window) and then plan to remove it, instead of porting it + all of its tests.  What do you think @hongkai-dai @RussTedrake @avalenzu?

(If we do want to keep maintaining this class instead of removing it, perhaps that could be in a future PR anyway.)

**Comment by hongkai-dai** [comment]
I think we should port `GlobalInverseKinematics` to use MBP and also change to use the const Solve method. I will do it in the 3 months window in a separate PR.

**Comment by jwnimmer-tri** [comment]
> In the `Solve` method, we already add the argument `initial_guess`. The rationale is to allow different initial guesses for each thread.

Correct.

> If we store the initial guess inside `MathematicalProgram`, we cannot change the initial guess for a different thread (but on the same MathematicalProgram).

This doesn't follow.  If the `Solve(...)` call is provided a guess by the user (in one of many threads), that guess will be used, even if there is a "default" guess in the program itself.

> Would you think it makes sense to deprecate `GetInitialGuess` as well?

Because the user might be confused that it only returns the default initial guess, instead of a guess passed specifically to some Solve call?  I could see us adding more API text, but it seems like if allow the user to place a default guess into the MP, we should let they ask what it was.

And keeping a default guess in the MP seems like a good thing to stay around, in nothing else for the single-threaded use cases.

**Comment by jwnimmer-tri** [comment]
> I don't think we ever used `solver_data_` in `MathematicalProgram`. Can we remove this as well?

I think this PR already does that?  Or did I fail to remove some code?

**Comment by jwnimmer-tri** [comment]
> I think in many cases, the program can be complicated, with different decision variables ...

That sounds like a request for some `SetInitialGuess` overloads that modify an `EigenPtr`, when the user only has a `const MP&`.  I agree with that.

I still think the existing guess setters & getters should stay intact, for the single-threaded case.  I do _not_ think we should force single-threaded users to launder the guess themselves into the Solve call.  I still thing `Solve(prog)` on its own should be enough.

In any case, since we offer const `FindDecisionVariableIndex`, the user for now could work around this problem.  I think if we (immediately) work on offering the `SetInitialGuess const` sugar, it should not block this PR?  What do you think?

**Comment by jwnimmer-tri** [comment]
I've filed #10722 as the feature request for const SetInitialGuess sugar.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule (tomorrow), please.

**Comment by jwnimmer-tri** [comment]
> I think we should port `GlobalInverseKinematics` to use MBP and also change to use the const Solve method. I will do it in the 3 months window in a separate PR.

Filed as #10724 now.

**Pull request merged**
