### PR TITLE
adds van der Pol oscillator example

### PR DESCRIPTION
**Pull request by RussTedrake**
first example is only plotting the limit cycle.  many more coming soon.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6964)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@edrumwri for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-:-KtEP1MmCKH76_6ZBdNu:b-p4pzus)*

**Comment by edrumwri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtEwOqd-U2uKCSvgrUk:-KtEwOqd-U2uKCSvgrUl:b-hsxkvo) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L20)):*
> ```cpp
> // TODO(russt): Move the computation of the cycle to a method in van_der_pol.cc
> // (once the boilerplate and dependencies are reduced.
> void do_main() {
> ```

I die a little bit inside that I'm having to  say this, but: I don't think the name of this function is style guide compliant.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtHJy_Ph7vtCEQG9hVO:-KtHJy_Ph7vtCEQG9hVP:bw7g98r) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L25)):*
> ```cpp
>   auto vdp = builder.AddSystem<VanDerPolOscillator<double>>();
>   auto logger = builder.AddSystem<systems::SignalLogger<double>>(2);
>   builder.Connect(vdp->get_output_port(1), logger->get_input_port(0));
> ```

BTW replacing all of these magic numbers with named constants would document this block of code, which is currently wanting.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF31Yc8ycUnh5wiQcN:-KtF31Yc8ycUnh5wiQcO:bh4qdzf) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L32)):*
> ```cpp
>   // Initialize with pre-computed initial conditions on the limit cycle
>   // for μ=1.
>   Eigen::Vector2d initial_state(-0.1144, 2.0578);
> ```

FYI Good practice to mark this `const` so that the reader can be told explicitly that this variable will not be changed.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3JMKHw59_ltXydMO:-KtF3JMLUdj2SnuIUCLX:bfdtgzt) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L32)):*
> ```cpp
>   // Initialize with pre-computed initial conditions on the limit cycle
>   // for μ=1.
>   Eigen::Vector2d initial_state(-0.1144, 2.0578);
> ```

How are these values pre-computed? (i.e., the reader does not how what setting the state to these particular values implies).

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3aqUnjDRqVZ62Cu4:-KtF3aqUnjDRqVZ62Cu5:baaflb7) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L38)):*
> ```cpp
>   vdp_state->SetFromVector(initial_state);
> 
>   // Simulate for the known duration of the cycle for μ=1.
> ```

BTW duration -> period ?

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtEwimpiyabojQiIP4a:-KtEwimpiyabojQiIP4b:b1ow1ik) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L42)):*
> ```cpp
> 
>   using common::CallMatlab;
>   CallMatlab("plot", logger->data().row(0), logger->data().row(1), "k",
> ```

FYI META As someone who has now lived to see a longterm cycle of commercial software lock in (MS Windows) just finally starting to diminish: can we look at default options other than Matlab for stuff like this? @pmitiguy's knowledge of mechanical engineering at Stanford leads him to think that Python (for which one can use matplotlib) is on the ascendance and Matlab is on its way down. Another alternative: Octave provides 99% of non-toolbox Matlab and is free. 

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3qH1je7x38tQOi50:-KtF3qH1je7x38tQOi51:btxli6n) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L51)):*
> ```cpp
>   // Check that the final state is very close to the initial state.
>   DRAKE_DEMAND(
>       is_approx_equal_abstol(vdp_state->CopyToVector(), initial_state, 1e-2));
> ```

Why such a loose tolerance?

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3wG86VmOGmfnKeQn:-KtF3wG86VmOGmfnKeQo:bem55hr) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L60)):*
> ```cpp
> 
> int main() {
>   drake::examples::van_der_pol::do_main();
> ```

Why can't the caller pass in their own initial values?

---

*[drake/examples/van_der_pol/van_der_pol.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF1Cnd69IH63jhDDLs:-KtF1Cnd69IH63jhDDLt:b-dwvzcz) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.cc#L1)):*
> ```cpp
> #include "drake/examples/van_der_pol/van_der_pol.h"
> ```

BTW Wow, this is pretty much the minimal number of comments one could get away with. Yet it still works. Good job!

---

*[drake/examples/van_der_pol/van_der_pol.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF00xwpoWFttkXjbdU:-KtF00xxqzLribbxadGB:bizywj7) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.cc#L42)):*
> ```cpp
> 
>   using std::pow;
>   const T qddot = -mu * (pow(q, 2) - 1) * qdot - q;
> ```

Do you have a good reason for doing pow(q, 2)? q*q is at least as fast and doesn't make me hope for magic from the compiler optimization gods. Not that speed is paramount in this example, but I cringe whenever I see pow(*, 2).

---

*[drake/examples/van_der_pol/van_der_pol.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF2IJrTuSrP-FgMTtR:-KtF2IJsgHWQBWkmtDHr:b-7rhae9) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.h#L9)):*
> ```objc
> namespace van_der_pol {
> 
> /// van der Pol oscillator
> ```

Ok, this is where you need more documentation. Why does this example exist? What does it serve to illustrate?  Why should the user benefit from the presence of this example?--- Too many examples can be worse than too few. 

The examples are going to be form the first impression for potential drake users, and you answering the questions above will hopefully lead these potential users to the conclusion, "This is a well thought out piece of software."

---

*[drake/examples/van_der_pol/van_der_pol.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtHLRD_HoomeHUtVION:-KtHLRD_HoomeHUtVIOO:bb4ivrc) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.h#L13)):*
> ```objc
> ///   y₁ = q
> ///   y₂ = [q,q̇]'
> template <typename T>
> ```

You're missing the boilerplate documentation on what template types are supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtEwOqd-U2uKCSvgrUk:-KtcK9A2Oz7c-lSkkwtd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I die a little bit inside that I'm having to  say this, but: I don't think the name of this function is style guide compliant.
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtHJy_Ph7vtCEQG9hVO:-Ktd6v3qlk7C-BQ249Vn:bxyut7f) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L25)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW replacing all of these magic numbers with named constants would document this block of code, which is currently wanting.
</blockquote></details>

added some sugar to vdp and signal logger to make this nicer.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF31Yc8ycUnh5wiQcN:-Ktd73LJj46h_d5F1j25:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L32)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI Good practice to mark this `const` so that the reader can be told explicitly that this variable will not be changed.
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3JMKHw59_ltXydMO:-Ktd7Aloa_jOKtXNwbuU:b-5gxb4i) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L32)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

How are these values pre-computed? (i.e., the reader does not how what setting the state to these particular values implies).
</blockquote></details>

i guess i thought it was clear.  i've updated the comment.  is it better now?

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3aqUnjDRqVZ62Cu4:-Ktd8FskFXNWKEmpGCFS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L38)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW duration -> period ?
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtEwimpiyabojQiIP4a:-Ktd8d1TWo3Wvij-S9_5:b-grgfx1) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L42)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI META As someone who has now lived to see a longterm cycle of commercial software lock in (MS Windows) just finally starting to diminish: can we look at default options other than Matlab for stuff like this? @pmitiguy's knowledge of mechanical engineering at Stanford leads him to think that Python (for which one can use matplotlib) is on the ascendance and Matlab is on its way down. Another alternative: Octave provides 99% of non-toolbox Matlab and is free. 
</blockquote></details>

see #3647.  i agree, but until a better solution emerges it should not block this PR.  

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3qH1je7x38tQOi50:-Ktd9eh8FHdcq7c-Mvst:b-kr5hc8) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L51)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why such a loose tolerance?
</blockquote></details>

added a note.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3wG86VmOGmfnKeQn:-KtdAZhK1gKzoGMCbbH1:bntn8bg) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L60)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why can't the caller pass in their own initial values?
</blockquote></details>

Then it would not plot the cycle (but an arbitrary trajectory).  the initial values have to be on the cycle.

---

*[drake/examples/van_der_pol/van_der_pol.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF00xwpoWFttkXjbdU:-KtdArP-8rMqvcpiWX9j:bn7lwpa) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.cc#L42)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Do you have a good reason for doing pow(q, 2)? q*q is at least as fast and doesn't make me hope for magic from the compiler optimization gods. Not that speed is paramount in this example, but I cringe whenever I see pow(*, 2).
</blockquote></details>

Done.  (I wish I could write q^2, and feel like pow(q,2) is a little closer that q*q, but don't have a strong preference)

---

*[drake/examples/van_der_pol/van_der_pol.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF2IJrTuSrP-FgMTtR:-KtcIbNJkaaAfpuDycCB:b-ilf7vi) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.h#L9)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Ok, this is where you need more documentation. Why does this example exist? What does it serve to illustrate?  Why should the user benefit from the presence of this example?--- Too many examples can be worse than too few. 

The examples are going to be form the first impression for potential drake users, and you answering the questions above will hopefully lead these potential users to the conclusion, "This is a well thought out piece of software."
</blockquote></details>

Done.   Although most of it is promises of forthcoming benefits (because I'm submitting in chunks)

---

*[drake/examples/van_der_pol/van_der_pol.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtHLRD_HoomeHUtVION:-KtcIbm8IWtdSrEWLUEo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/van_der_pol.h#L13)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You're missing the boilerplate documentation on what template types are supported.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by edrumwri** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3wG86VmOGmfnKeQn:-Ktdvo_TqlMa6UN670bg:b-aqvfzk) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L60)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Then it would not plot the cycle (but an arbitrary trajectory).  the initial values have to be on the cycle.
</blockquote></details>

I'm trying to suss out where this example is going: if I wanted to repeat your process with a different mu (I realize that's not really supported yet), it would be neat to be able to plot my values similarly without a recompile. Or, is this example destined to be minimalist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by RussTedrake** [comment]
Review status: 1 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/van_der_pol/plot_limit_cycle.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtF3wG86VmOGmfnKeQn:-KtevNIC0RV9ZriuDUbU:b-tw2wo8) ([raw file](https://github.com/robotlocomotion/drake/blob/63cf500863174d0e01d969ff517e2f031b6ca6c6/drake/examples/van_der_pol/plot_limit_cycle.cc#L60)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm trying to suss out where this example is going: if I wanted to repeat your process with a different mu (I realize that's not really supported yet), it would be neat to be able to plot my values similarly without a recompile. Or, is this example destined to be minimalist?
</blockquote></details>

Part of where it is going is back to where it came from:
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/examples/VanDerPol.m
That example didn't even have μ, but I'm planning to do even more in c++ going forward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by edrumwri** [comment]
Reviewed 5 of 8 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmgHZZGrxFVRQKk094:-KtmgHZ_j34Ag7gx1R8g:bez9z5c) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L108)):*
> ```cpp
>   auto x_logger = LogOutput(acrobot_w_encoder->get_output_port(1), &builder);
>   x_logger->set_name("x_logger");
>   auto xhat_logger = LogOutput(observer->get_output_port(0), &builder);
> ```

FYI Please consider replacing the magic numbers with named constants here too. That way, changing the code is easy if the port layout changes.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmfMaJhCEeYbgj6Unk:-KtmfMaJhCEeYbgj6Unl:b-szsryr) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc#L90)):*
> ```cpp
> }
> 
> class TestRbtCloneDiagram : public Diagram<double> {
> ```

Would you mind adding a comment describing this class's purpose? I'm finding myself jumping back and forth throughout the test file to suss it out, which is less than optimal from a maintenance perspective.

---

*[drake/systems/primitives/signal_logger.h, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmfuUiRn1ewb7u2Qta:-KtmfuUiRn1ewb7u2Qtb:b-j7ngix) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/systems/primitives/signal_logger.h#L69)):*
> ```objc
> /// the correct size, and connected to another output in a DiagramBuilder.
> ///
> /// @code
> ```

This example code block is great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-:-KtmgXRGVsBuGaXULqBz:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@sammy-tri for platform review.  
(@edrumwri, you have a few blocking comments below)

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmgHZZGrxFVRQKk094:-KtnpbbFctdZ4DCqnisj:b-hz1y8g) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/acrobot/acrobot_run_lqr_w_estimator.cc#L108)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI Please consider replacing the magic numbers with named constants here too. That way, changing the code is easy if the port layout changes.
</blockquote></details>

I'll be cleaning up the entire acrobot example directory soon.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmfMaJhCEeYbgj6Unk:-KtnppjMfTR7J4dnZapN:by8j8o2) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc#L90)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Would you mind adding a comment describing this class's purpose? I'm finding myself jumping back and forth throughout the test file to suss it out, which is less than optimal from a maintenance perspective.
</blockquote></details>

this is not my code.  i simply touched the logger line to use my new helper api below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-:-Ktnq6tDeIM3bsz7e0KR:btwougf)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/van_der_pol/BUILD, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqXtHexfitvbssWI-Q:-KtqXtHgsyw3TXnywlsM:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L4)):*
> ```Python
> # This file contains rules for Bazel; see drake/doc/bazel.rst.
> 
> load("//tools:cpplint.bzl", "cpplint")
> ```

unused?

---

*[drake/examples/van_der_pol/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqXuq3EcCnFvSLiM3V:-KtqXuq4VMM0H5AZ2mYn:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L7)):*
> ```Python
> load(
>     "//tools:drake.bzl",
>     "drake_cc_googletest",
> ```

unused?

---

*[drake/examples/van_der_pol/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqYFeFygZr4Kuy5mNz:-KtqYFeFygZr4Kuy5mO-:b6agyz2) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L19)):*
> ```Python
>     visibility = ["//visibility:public"],
>     deps = [
>         "//drake/systems/framework",
> ```

BTW this dep is a little broad when listing the dependencies explicitly would only involve `leaf_system` and `vector` (then again, changing anything in `systems/framework` is gonna trigger a hell of a recompile anyway, so perhaps optimizing for that case isn't really worthwhile)

---

*[drake/examples/van_der_pol/van_der_pol.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-Ktq_VwB3fPC67zgilpJ:-Ktq_VwCa0p0FMGLso3S:buuvaaf) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/van_der_pol.cc#L27)):*
> ```cpp
>   this->DeclareNumericParameter(systems::BasicVector<T>(Vector1<T>(1.0)));
> 
>   // TODO(russt): Declare μ>0 constraint when #6923 lands.
> ```

#6923 has been merged...  Is this TODO still accurate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtmfMaJhCEeYbgj6Unk:-KtsRqfiHEn-2puYXFF7:bsgnbu) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc#L90)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this is not my code.  i simply touched the logger line to use my new helper api below.
</blockquote></details>

Fair enough. I try to maintain a balance between "leave every bit of code better than you found it" and "focus only on the elements strictly related to a PR's purpose within that PR" but the point is moot since RBT is on its way out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/van_der_pol/BUILD, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqXtHexfitvbssWI-Q:-Ku-IXLQm8pexlcvFPY_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqXuq3EcCnFvSLiM3V:-Ku-IXr4p7Nh8P5gWMNk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-KtqYFeFygZr4Kuy5mNz:-Ku-Ik_V_9omsdNEgCS5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/BUILD#L19)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this dep is a little broad when listing the dependencies explicitly would only involve `leaf_system` and `vector` (then again, changing anything in `systems/framework` is gonna trigger a hell of a recompile anyway, so perhaps optimizing for that case isn't really worthwhile)
</blockquote></details>

Done.

---

*[drake/examples/van_der_pol/van_der_pol.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-Ktq_VwB3fPC67zgilpJ:-Ku-LEz6tH2VMNuNyt2l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7776111e7638b22475dc9cfd62ceb9c15d3b74f9/drake/examples/van_der_pol/van_der_pol.cc#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

#6923 has been merged...  Is this TODO still accurate?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Comment by sammy-tri** [comment]
:lgtm: (once CI is happy)

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964#-:-Ku-hxtQ3JMHZcnpbe9o:b-te5chh)*

**Comment by RussTedrake** [comment]
oops.  forgot to commit my final edits before running out the door this morning.  this should do it.

**Comment by RussTedrake** [comment]
@sammy-tri -- all green.  want to check the last few changes and click it through?  thanks!

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6964)*

**Pull request merged**
