### PR TITLE
fix math::jacobian() segfault when evaluated on constant AutoDiffXd function

### PR DESCRIPTION
**Pull request by antequ**
Fix math::jacobian() segfault when evaluated on constant AutoDiffXd function

When math::jacobian() is ran on an f(x) with a return scalar type of AutoDiffXd, it will segfault if f(x) does not depend on x. This is because the derivative of the result has size 0, while math::jacobian() tries to index into the f(x) result derivative vector to set its final vector.

This commit:
1. Adds a test into jacobian_test.cc to reproduce this bug, which creates a constant f(x) = 0 of scalar type AutoDiffXd for it to differentiate.
2. Fixes this issue by having the inner for loop stop early, and setting the rest of the derivative vector to 0.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12999)

### CODE REVIEW

**Comment by antequ** [comment]
___
*[math/test/jacobian_test.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12999#-M4FBh8O2deFqVubQyAc:-M4_yt_bEKUNT7v9kdxa:bkkvyoh) ([raw file](https://github.com/robotlocomotion/drake/blob/b3c354d2322fdf351874ede2c8b7be293ab83825/math/test/jacobian_test.cc#L81)):*
<details><summary><i>Previously, antequ (Ante Qu) wrote…</i></summary><blockquote>

Decided not to change this -- it takes too much template logic to support both. The main change we would want is something that uses std::is_same on the following line
  using ChunkArgDerType =
      Matrix<ArgScalar, Eigen::Dynamic, 1, 0, MaxChunkSize, 1>;

to check whether the first argument of f is const VectorX<AutoDiffXd>&, and if so make it dynamic. I couldn't get this to work.
</blockquote></details>

*const VectorX<AutoDiffXd>&

**Comment by jwnimmer-tri** [comment]
I don't think this fix is moving in the correct direction.

Using a chunking-based jacobian when we're anyway hitting the heap for Xd values all over the place is nonsense.  If our function is Xd based, then we should just do a single pass with full-sized partials.

For now, the chunk-based `math::jacobian` should probably static_assert fail if used against AutoDiffXd.

We can add an alternative method (or overload?) that works with AutoDiffXd, which is what it sounds like #12967 wants anyway.

**Comment by jwnimmer-tri** [comment]
To the extent that this function operates chunk-wise (MaxChunkSize), I don't think it makes sense to have the F function operate on AutoDiffXd intermediates.  At that point we might as well just have the loop you note that computes it all in one go.

This PR could try to add that loop as a nice subroutine.

There might still be a defect in the current subroutine -- if the F function uses a fixed-maximum-size autodiff but with a dynamic actual size, then chunking still makes sense but might still access technically-out-of-bounds partials (even though the memory is there, the data is garbage).

**Comment by jwnimmer-tri** [comment]
@antequ Is this PR still underway?  Or should we close it?

**Comment by antequ** [comment]
I have no plans to continue work on this PR. Thanks for asking!

**Pull request closed without merging**
