### PR TITLE
[planning] Further improve welded body check

### PR DESCRIPTION
**Pull request by calderpg-tri**
Alternative approach to #18718

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723)

### CODE REVIEW

**Review by calderpg-tri — COMMENTED** [review]
@jwnimmer-tri @sherm1 I think this approach is a bit simpler, and probably more efficient (one call to `FindSubgraphsOfWeldedBodies` versus multiple calls to `GetBodiesWeldedTo`). The only concern is what the appropriate means of exposing `FindSubgraphsOfWeldedBodies` for this PR would be:
1. "Internal only" access to a plant's `MultibodyGraph` (as implemented in r1)
2. MbP provides an "internal only" `FindSubgraphsOfWeldedBodies` method
3. MbP provides a `FindSubgraphsOfWeldedBodies` method, which gets documented/tested/bound as normal

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NNE8AJB7qHiNiTWWOx4:bhqmbkc)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by sherm1 — COMMENTED** [review]
My preference would be a first class MbP::FindSubgraphsOfWeldedBodies() -- that seems generally useful. Pending that, an internal-use-only method of that name (option 2) would be my preference rather than exposing the whole MultibodyGraph class which doesn't seem ready for prime time yet.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NNEBcfr7nwrNqz1ipE5:b-fazd6e)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Comment by calderpg-tri** [comment]
+@jwnimmer-tri for review, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
I am OK to LGTM on the planning code, but I can't be the one to feature-review the MbP changes, that's beyond my expertise.

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NNJ8AlUBNy1ppi1-Eh9:b9lwc1o)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`planning/collision_checker.cc` line 952 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-NNJ7hiSBRH0kd0-hs2x:-NNJ7hiSBRH0kd0-hs2y:b-pl110l) ([raw file](https://github.com/RobotLocomotion/drake/blob/9293a37b1b2ebaba3a7ec754dfbff7445eab0133/planning/collision_checker.cc#L952)):*
> ```cpp
>       body_subgraph_mapping.at(body_id) = static_cast<int>(subgraph_id);
>     }
>   }
> ```

If any `-1` values remain here, then the `bodies_welded_together` check below will be incorrect.

We don't _expect_ the MbP to do that to us, but there are enough moving parts there that I think it's not quite safe to rely on.

I think we need to fail-fast in case of a lingering `-1`, either here or at the `bodies_welded_together` point of use.

Similarly we could imagine that `body_subgraph_mapping.at(body_id) = static_cast<int>(subgraph_id);` could fail-fast in case the value was _not_ still `-1`, though that failure mode seems less likely.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by calderpg-tri — COMMENTED** [review]
+@sherm1 for multibody_plant.{cc, h} changes (or feel free to delegate), thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NNJBd5P2ISAhOkJsoYA:b-2uijmp)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @sherm1)

___
*[`planning/collision_checker.cc` line 952 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-NNJ7hiSBRH0kd0-hs2x:-NNJBef278G-5MIO0sIR:b-3u7u59) ([raw file](https://github.com/RobotLocomotion/drake/blob/9293a37b1b2ebaba3a7ec754dfbff7445eab0133/planning/collision_checker.cc#L952)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If any `-1` values remain here, then the `bodies_welded_together` check below will be incorrect.

We don't _expect_ the MbP to do that to us, but there are enough moving parts there that I think it's not quite safe to rely on.

I think we need to fail-fast in case of a lingering `-1`, either here or at the `bodies_welded_together` point of use.

Similarly we could imagine that `body_subgraph_mapping.at(body_id) = static_cast<int>(subgraph_id);` could fail-fast in case the value was _not_ still `-1`, though that failure mode seems less likely.
</blockquote></details>

Check added

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: for the multibody plant changes, pending hiding the new function from doxygen (or making it a full-fledged, documented, tested feature). See comment below.

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NOH7gT564pAZI4HB-zo:b-z9bda1)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`multibody/plant/multibody_plant.h` line 4440 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-NOH6cfP0KtBa71n32vi:-NOH6cfP0KtBa71n32vj:bwk4cxv) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5b848a74f9340df42ebcf95f06bec940e45f745/multibody/plant/multibody_plant.h#L4440)):*
> ```objc
>   // Internal-only access to MultibodyGraph::FindSubgraphsOfWeldedBodies();
>   // TODO(calderpg-tri) Properly expose this method (docs/tests/bindings).
>   std::vector<std::set<BodyIndex>> FindSubgraphsOfWeldedBodies() const;
> ```

minor: this now shows up in doxygen as a public member:


If it isn't intended for general use, either it has to be given doxygen documentation beginning with "(Internal use only)" or (better) exclude it from Doxygen altogether for now by surrounding it with
```
#ifndef DRAKE_DOXYGEN_CXX
...
#endif
```

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[`multibody/plant/multibody_plant.h` line 4440 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-NOH6cfP0KtBa71n32vi:-NOHEc0s7bjY4Q4rwXDf:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b5b848a74f9340df42ebcf95f06bec940e45f745/multibody/plant/multibody_plant.h#L4440)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this now shows up in doxygen as a public member:


If it isn't intended for general use, either it has to be given doxygen documentation beginning with "(Internal use only)" or (better) exclude it from Doxygen altogether for now by surrounding it with
```
#ifndef DRAKE_DOXYGEN_CXX
...
#endif
```
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: on planning.

> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NOHEogoEVo3C6Qwk33n:b-tyxdb5)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
+@rpoyner-tri for platform review, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NOHKDvf9QCxjt54gtuy:brsnuvz)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18723#-:-NOKvVdq9SFfiWMDy3sj:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Pull request merged**
