### PR TITLE
Add gfortran for 16.04

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2868)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews (I believe the other other reviewer running 16.04).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2868#-:-KN95pmqyUFXGaM0QaMv:1729141261)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2868#-:-KN9Dzs_kPgeX9Qn7Q9r:1417088721)*

**Comment by liangfok** [comment]
FTR. I experimented with Drake on Ubuntu 16.04 and noticed the need for this `gfortran` package.

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2868)*

**Comment by ggould-tri** [comment]
This appears correct and safe to me after playing around with builds with and without gfortran. :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2868#-:-KNCmu6iayCMVcJthnUk:230687168)*

**Pull request merged**
