### PR TITLE
Mbt GetByName() heap alloc fix

### PR DESCRIPTION
**Pull request by edrumwri**
This PR removes an unnecessary piece of code that was resulting in a heap allocation in MBP/MBT GetXByName(.) functions. It also adds a heap allocation tripwire to the unit tests for those functions in MBT.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for feature review or delegation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303#-:-MsaM5D801b5aUV0Bud0:b-ymd4d7)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: needs buildifier fixup, squash, and commit log message
+@sherm1 for platform review

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303#-:-Msamhys3U0h3-IKcBRA:b9ico5w)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/tree/BUILD.bazel, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaibkY52GigfPGcDRg:-MsaibkZ2fuWg3cnxdFl:b-w21il) ([raw file](https://github.com/robotlocomotion/drake/blob/affed8d01fc59420c5987f16003a65254aac4a7c/multibody/tree/BUILD.bazel#L327)):*
> ```Starlark
>     deps = [
>         ":tree",
>         "//common/test_utilities:limit_malloc",
> ```

BTW The build failures are likely unapproved sorting of these deps lines. Running buildifier should clear it up.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303#-:-MsanLML0wJ150qWtnKx:b-safpmt)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsaoBWS6uW4ziJl1ezd:b-a47cf) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
> ```cpp
>   // We fetch the model instance name as the first operation in this function
>   // (even though we'll only need it for error messages) because it throws an
>   // exception when the model_instance index is invalid.
> ```

This was a chesterton's fence comment -- it claimed that fetching the name of the the model_instance here was done in order to cause an exception to be thrown when the user provided an invalid instance (i.e., an instance that does not exist at all, rather than merely not finding a match).

Was the comment incorrect?  Is the validity of the instance already checked elsewhere?  From a quick scan of the code, it looks like not.

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsazAnY83OHzf6lzQgA:b92618w) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This was a chesterton's fence comment -- it claimed that fetching the name of the the model_instance here was done in order to cause an exception to be thrown when the user provided an invalid instance (i.e., an instance that does not exist at all, rather than merely not finding a match).

Was the comment incorrect?  Is the validity of the instance already checked elsewhere?  From a quick scan of the code, it looks like not.
</blockquote></details>

The blank version of this string was unused. My guess is that a previous version of this code used it and then evolved to no longer need it.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-Msb5SfS3LJMZuA7prrW:bnsnvz9) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The blank version of this string was unused. My guess is that a previous version of this code used it and then evolved to no longer need it.  
</blockquote></details>

Do we have a test that attempts to use an invalid index?

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-Msb5uWN0AEpzSF3gHJI:bw9igpj) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do we have a test that attempts to use an invalid index?
</blockquote></details>

I'm recovering from covid and am generally not thinking clearly, but I read the author's comment as saying that they get the string here to avoid having to produce reproducing all of this logic below. Which, looking again now, doesn't actually make sense.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsbA98H7Qd98trtuNt-:b-ttp6ec) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Sorry to hear you were sick. Get well soon!
</blockquote></details>

If you like, I can propose something here to avoid heap and still  do the error checking.

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsbBHT_Cl0SZgX0V_Fv:b-g2r4um) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

If you like, I can propose something here to avoid heap and still  do the error checking.
</blockquote></details>

Please!

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[multibody/tree/BUILD.bazel, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaibkY52GigfPGcDRg:-MsbGSDi-7SesaALqxuQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/affed8d01fc59420c5987f16003a65254aac4a7c/multibody/tree/BUILD.bazel#L327)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW The build failures are likely unapproved sorting of these deps lines. Running buildifier should clear it up.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri, @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsbSPgxBz_utyHHd8lo:b9nnnwl) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please!
</blockquote></details>

Here's one way to go (short of rewriting this function -- whee ;) ). I keep the exception-checking call, but defer the string storage part:

```
diff --git a/multibody/tree/multibody_tree.cc b/multibody/tree/multibody_tree.cc
index 17f680bfad..84d5e86a04 100644
--- a/multibody/tree/multibody_tree.cc
+++ b/multibody/tree/multibody_tree.cc
@@ -248,12 +248,14 @@ const auto& GetElementByName(
     const MultibodyTree<T>& tree, std::string_view name,
     std::optional<ModelInstanceIndex> model_instance,
     const NameToIndex<ElementIndex>& name_to_index) {
-  // We fetch the model instance name as the first operation in this function
-  // (even though we'll only need it for error messages) because it throws an
-  // exception when the model_instance index is invalid.
-  const std::string& model_instance_name =
-      model_instance ? tree.GetModelInstanceName(*model_instance)
-                     : std::string();
+  // We check the model instance name as the first operation in this function
+  // because it throws an exception when the model_instance index is invalid.
+  // However, we don't store any string values here to avoid heap
+  // transactions. If this function needs it later for error messages, we will
+  // look it up again.
+  const bool is_model_instance_valid =
+      model_instance ? !tree.GetModelInstanceName(*model_instance).empty()
+                     : false;
   const std::string_view element_classname =
       GetElementClassname<ElementIndex>();
 
@@ -279,6 +281,10 @@ const auto& GetElementByName(
     }
     const std::string known_instances =
         GetElementModelInstancesByName(tree, name, name_to_index);
+    const std::string& model_instance_name =
+        (model_instance && is_model_instance_valid)
+        ? tree.GetModelInstanceName(*model_instance)
+        : "";
     throw std::logic_error(fmt::format(
         "Get{}ByName(): There is no {} named '{}' in the model instance named"
         " '{}', but one does exist in other model instances ({}).",

```

The above diff is from master.
___
*[multibody/tree/test/multibody_tree_test.cc, line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsbSLqoA5rxd5lnnYxT:-MsbQwaSCL1TdtOcZu80:b-dzh046) ([raw file](https://github.com/robotlocomotion/drake/blob/fc49335c09836986d5ea9c11e802ab22b755c60e/multibody/tree/test/multibody_tree_test.cc#L136)):*
> ```cpp
>       model.GetBodyByName(kLinkNames[0], world_model_instance()),
>       std::logic_error,
>       ".*There is no Body.*but one does exist in other model instances.*");
> ```

Part of why we missed the purpose of the original code (index bounds checking) was that we lacked a test. Maybe something like this could be inserted here:

```
+  const ModelInstanceIndex kInvalidIndex(1<<30);
+  DRAKE_EXPECT_THROWS_MESSAGE(
+      model.GetBodyByName(kLinkNames[0], kInvalidIndex), std::logic_error,
+      ".*There is no model instance.*in the model.*");
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri, @jwnimmer-tri, and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri, @jwnimmer-tri, and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsbTbuT3XxLIWluEXSV:b38hpm4) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's one way to go (short of rewriting this function -- whee ;) ). I keep the exception-checking call, but defer the string storage part:

```
diff --git a/multibody/tree/multibody_tree.cc b/multibody/tree/multibody_tree.cc
index 17f680bfad..84d5e86a04 100644
--- a/multibody/tree/multibody_tree.cc
+++ b/multibody/tree/multibody_tree.cc
@@ -248,12 +248,14 @@ const auto& GetElementByName(
     const MultibodyTree<T>& tree, std::string_view name,
     std::optional<ModelInstanceIndex> model_instance,
     const NameToIndex<ElementIndex>& name_to_index) {
-  // We fetch the model instance name as the first operation in this function
-  // (even though we'll only need it for error messages) because it throws an
-  // exception when the model_instance index is invalid.
-  const std::string& model_instance_name =
-      model_instance ? tree.GetModelInstanceName(*model_instance)
-                     : std::string();
+  // We check the model instance name as the first operation in this function
+  // because it throws an exception when the model_instance index is invalid.
+  // However, we don't store any string values here to avoid heap
+  // transactions. If this function needs it later for error messages, we will
+  // look it up again.
+  const bool is_model_instance_valid =
+      model_instance ? !tree.GetModelInstanceName(*model_instance).empty()
+                     : false;
   const std::string_view element_classname =
       GetElementClassname<ElementIndex>();
 
@@ -279,6 +281,10 @@ const auto& GetElementByName(
     }
     const std::string known_instances =
         GetElementModelInstancesByName(tree, name, name_to_index);
+    const std::string& model_instance_name =
+        (model_instance && is_model_instance_valid)
+        ? tree.GetModelInstanceName(*model_instance)
+        : "";
     throw std::logic_error(fmt::format(
         "Get{}ByName(): There is no {} named '{}' in the model instance named"
         " '{}', but one does exist in other model instances ({}).",

```

The above diff is from master.
</blockquote></details>

The above code is slightly wrong in that it implies (but doesn't actually rely on) that model names are always non-empty -- I don't see any reason in the surrounding code prevents it being empty, but I think it is unlikely.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri, @jwnimmer-tri, and @sherm1)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-MsbbT_k13hY8kNN_VXO:b-o569zr) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The above code is slightly wrong in that it implies (but doesn't actually rely on) that model names are always non-empty -- I don't see any reason in the surrounding code prevents it being empty, but I think it is unlikely.
</blockquote></details>

Here's a less gross attempt:

```
diff --git a/multibody/tree/multibody_tree.cc b/multibody/tree/multibody_tree.cc
index 17f680bfad..c40c553854 100644
--- a/multibody/tree/multibody_tree.cc
+++ b/multibody/tree/multibody_tree.cc
@@ -248,12 +248,13 @@ const auto& GetElementByName(
     const MultibodyTree<T>& tree, std::string_view name,
     std::optional<ModelInstanceIndex> model_instance,
     const NameToIndex<ElementIndex>& name_to_index) {
-  // We fetch the model instance name as the first operation in this function
-  // (even though we'll only need it for error messages) because it throws an
-  // exception when the model_instance index is invalid.
-  const std::string& model_instance_name =
-      model_instance ? tree.GetModelInstanceName(*model_instance)
-                     : std::string();
+  const std::string* model_instance_name_maybe{};
+  if (model_instance.has_value()) {
+    // We fetch the model instance name as the first operation in this function
+    // (even though we'll only need it for error messages) because it throws an
+    // exception when the model_instance index is invalid.
+    model_instance_name_maybe = &tree.GetModelInstanceName(*model_instance);
+  }
   const std::string_view element_classname =
       GetElementClassname<ElementIndex>();
 
@@ -279,10 +280,11 @@ const auto& GetElementByName(
     }
     const std::string known_instances =
         GetElementModelInstancesByName(tree, name, name_to_index);
+    DRAKE_DEMAND(model_instance_name_maybe != nullptr);
     throw std::logic_error(fmt::format(
         "Get{}ByName(): There is no {} named '{}' in the model instance named"
         " '{}', but one does exist in other model instances ({}).",
-        element_classname, element_classname, name, model_instance_name,
+        element_classname, element_classname, name, *model_instance_name_maybe,
         known_instances));
   }
```

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few open feature review items.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303#-:-MsbpBlc9G9IcBU7ddyS:brpirf6)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

___
*[multibody/tree/multibody_tree.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsaoBWR5TMgMjTYAJZB:-Msc0-S4EoHD24WfJ4vc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a56634055b6192ad51ac03d9128e837b7ee10107/multibody/tree/multibody_tree.cc#L253)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's a less gross attempt:

```
diff --git a/multibody/tree/multibody_tree.cc b/multibody/tree/multibody_tree.cc
index 17f680bfad..c40c553854 100644
--- a/multibody/tree/multibody_tree.cc
+++ b/multibody/tree/multibody_tree.cc
@@ -248,12 +248,13 @@ const auto& GetElementByName(
     const MultibodyTree<T>& tree, std::string_view name,
     std::optional<ModelInstanceIndex> model_instance,
     const NameToIndex<ElementIndex>& name_to_index) {
-  // We fetch the model instance name as the first operation in this function
-  // (even though we'll only need it for error messages) because it throws an
-  // exception when the model_instance index is invalid.
-  const std::string& model_instance_name =
-      model_instance ? tree.GetModelInstanceName(*model_instance)
-                     : std::string();
+  const std::string* model_instance_name_maybe{};
+  if (model_instance.has_value()) {
+    // We fetch the model instance name as the first operation in this function
+    // (even though we'll only need it for error messages) because it throws an
+    // exception when the model_instance index is invalid.
+    model_instance_name_maybe = &tree.GetModelInstanceName(*model_instance);
+  }
   const std::string_view element_classname =
       GetElementClassname<ElementIndex>();
 
@@ -279,10 +280,11 @@ const auto& GetElementByName(
     }
     const std::string known_instances =
         GetElementModelInstancesByName(tree, name, name_to_index);
+    DRAKE_DEMAND(model_instance_name_maybe != nullptr);
     throw std::logic_error(fmt::format(
         "Get{}ByName(): There is no {} named '{}' in the model instance named"
         " '{}', but one does exist in other model instances ({}).",
-        element_classname, element_classname, name, model_instance_name,
+        element_classname, element_classname, name, *model_instance_name_maybe,
         known_instances));
   }
```
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[multibody/tree/test/multibody_tree_test.cc, line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsbSLqoA5rxd5lnnYxT:-Msf4KnH3vBambzRF1aN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc49335c09836986d5ea9c11e802ab22b755c60e/multibody/tree/test/multibody_tree_test.cc#L136)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Part of why we missed the purpose of the original code (index bounds checking) was that we lacked a test. Maybe something like this could be inserted here:

```
+  const ModelInstanceIndex kInvalidIndex(1<<30);
+  DRAKE_EXPECT_THROWS_MESSAGE(
+      model.GetBodyByName(kLinkNames[0], kInvalidIndex), std::logic_error,
+      ".*There is no model instance.*in the model.*");
```
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[multibody/tree/test/multibody_tree_test.cc, line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16303#-MsbSLqoA5rxd5lnnYxT:-Msf93VZ4xWZoZD0ol03:b9qxh62) ([raw file](https://github.com/robotlocomotion/drake/blob/fc49335c09836986d5ea9c11e802ab22b755c60e/multibody/tree/test/multibody_tree_test.cc#L136)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You beat me to it Rico!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

**Review by sherm1 — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16303#-:-MsfKx5w3Ulj_S_-Flbv:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @edrumwri)

**Pull request merged**
