### PR TITLE
 pydrake systems lcm: Enable publishers and subscribers 

### LINKED ISSUE #8912: Create Python bindings for LcmPublisherSystem and LcmSubscriberSystem

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8912

Took a tad bit longer than 30min, but it works at present, and keeps things closer to the C++ API while still (IMO) providing of just providing an LCM type for the serializer.

\cc @thduynguyen 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8914)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review if you have time, please.

This enables the workflow you mentioned (just use whatever Python LCM type), but also paves the way towards connecting C++ LCM types if/when we get there.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8914#-:-LDtbjiT15McUzS_ZvMY:bazikuk)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/lcm_py.cc, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvFtVD-jZh7dp2yTFB:-LDvFtVEE1AQWMt2vvXo:bd8sh7n) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/lcm_py.cc#L16)):*
> ```cpp
> namespace pydrake {
> ```

Stray vertical whitespace.

---

*[bindings/pydrake/lcm_py.cc, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvGkIS5oXvnLxMJPaD:-LDvGkIT-nzgL1mmAqyp:b-mkp1yk) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/lcm_py.cc#L36)):*
> ```cpp
>                 [handler](const void* data, int size) {
>                   // TODO(eric.cousineau): This may wreak havoc if called from
>                   // a different thread. Disable this in `DrakeLcm`?
> ```

Since the non-mock use of this method always does use a different thread, I agree this method seems like playing with fire.

What do you think about only binding it for the mock subclass -- since its only used for testing?

---

*[bindings/pydrake/lcm_py.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvGxZkEFheQ5U_Usza:-LDvGxZkEFheQ5U_Uszb:b5n34yc) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/lcm_py.cc#L44)):*
> ```cpp
>               py::bytes buffer, optional<double> time_sec) {
>             // TODO(eric.cousineau): See if there is a way to get raw data? Use
>             // `py::buffer`?
> ```

BTW Does this mean "get raw data _without copying_"?

---

*[bindings/pydrake/systems/BUILD.bazel, line 209 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvISx28YPrDUOupKOK:-LDvISx28YPrDUOupKOL:b-3fhwsn) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/BUILD.bazel#L209)):*
> ```Python
>         ":framework_py",
>         ":module_py",
>         "//bindings/pydrake:lcm_py",
> ```

I don't immediately see where this is being used?

---

*[bindings/pydrake/systems/lcm.py, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvULKpB5q3nRVVJuQC:-LDvULKq1P4wNFFZYpNk:b-h5mdey) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/lcm.py#L6)):*
> ```Python
> 
> 
> class PySerializer(SerializerInterface):
> ```

Missing class overview doc.

---

*[bindings/pydrake/systems/lcm.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvSrun0i1q3SKR9F3p:-LDvSrun0i1q3SKR9F3q:b-eeuvu9) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/lcm.py#L15)):*
> ```Python
> 
>     def Deserialize(self, buffer, value):
>         msg = self._lcm_type.decode(buffer)
> ```

Abbreviation `msg`.  Ditto below.

---

*[bindings/pydrake/systems/lcm_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LE9xjqhBZAQzjwJG9MM:-LE9xjqhBZAQzjwJG9MN:bndnvfm) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/lcm_py.cc#L18)):*
> ```cpp
> using systems::AbstractValue;
> 
> class PySerializerInterface : public py::wrapper<SerializerInterface> {
> ```

Missing overview doc.  (I think the purpose of this class is the pybind11'ic way to wrap a pure virtual C++ interface; if so, maybe say so, with a link to pybind11 manual?  I wasn't able to find it in 10 seconds of searching.)

---

*[bindings/pydrake/systems/lcm_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LE9ysUOBmrUvzkIe9-A:-LE9ysUOBmrUvzkIe9-B:bjdkocl) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/lcm_py.cc#L18)):*
> ```cpp
> using systems::AbstractValue;
> 
> class PySerializerInterface : public py::wrapper<SerializerInterface> {
> ```

Should be in anon namespace, I think?

---

*[bindings/pydrake/systems/lcm_py.cc, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvIdqeAc77JjbZnzqj:-LDvIdqeAc77JjbZnzqk:b-se5tgn) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/lcm_py.cc#L55)):*
> ```cpp
>     std::string str = wrapped();
>     message_bytes->resize(str.size());
>     std::memcpy(message_bytes->data(), str.data(), str.size());
> ```

FYI My impression of general advice is to use `std::copy` over `std::memcpy`, even for bytes.

---

*[bindings/pydrake/systems/test/lcm_test.py, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvUV7C2-wQ287FDEgm:-LDvUV7C2-wQ287FDEgn:b-h8so84) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/test/lcm_test.py#L11)):*
> ```Python
> 
> # Create a simple template message.
> MSG = quaternion_t()
> ```

Abbreviation `MSG`.

---

*[bindings/pydrake/systems/test/lcm_test.py, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvVrH9CiOQwEKPtHxc:-LDvVrH9CiOQwEKPtHxd:bfrxcei) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/test/lcm_test.py#L22)):*
> ```Python
>         self.assertNotEqual(value.get_value().encode(), MSG.encode())
>         dut.Deserialize(MSG.encode(), value)
>         self.assertEqual(value.get_value().encode(), MSG.encode())
> ```

BTW For the two assertions of "does the quaternion_t have the right fields set" in this test, I found it difficult to follow when the assertion was phrased as an encode-match -- I had to do some mental gymnastics to figure out which ones were testing the encoding by the DUT, vs which ones were testing for struct-equality.  Consider making them tuple-equality checks of the wxyz instead?

FYI If you like, you could also just steal `format_lcm_message` from my Anzu PR and using the repr-like string to test for message contents.

---

*[bindings/pydrake/systems/test/lcm_test.py, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8914#-LDvl4qR9Lx73clP9fYR:-LDvl4qS-fF3XoOYUJaZ:b-p85ix1) ([raw file](https://github.com/robotlocomotion/drake/blob/70507830419f7f0e7eda6f150efa9a26870c635b/bindings/pydrake/systems/test/lcm_test.py#L36)):*
> ```Python
>         dut.CalcOutput(context, output)
>         actual = output.get_data(0).get_value()
>         self.assertEqual(actual.encode(), MSG.encode())
> ```

BTW Ditto as above (about abusing encode to test for value-quality).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8914)*

**Comment by mpetersen94** [comment]
Having merged this into my own fork to use, I can't import `LcmPublisherSystem` or `LcmSubscriberSystem`, instead getting the error `No module named lcm` when I import from `pydrake.systems.lcm`.  This is in a project with drake as an external.

**Comment by EricCousineau-TRI** [comment]
> Having merged this into my own fork to use, I can't import LcmPublisherSystem or LcmSubscriberSystem [...]

Thanks for catching that! I had not included it in the install; will fix that.

**Comment by EricCousineau-TRI** [comment]
@mpetersen94 The install problem should be fixed; ran the install, and ensure that `pydrake/system/lcm.py` was there.

**Pull request merged**
