### PR TITLE
WIP: MBT methods to work with State<T>

### PR DESCRIPTION
**Pull request by amcastro-tri**
These are required to start building systems based on MBT.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7542)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sherm1 for platform review please

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-DOuBqxoWkKTHRgYd9:bu0bkqk)*

**Comment by sherm1** [comment]
:lgtm: with a few BTWs to look at.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 322 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-Im2-hH6A1HNWvSPbj:-L-Im2-hH6A1HNWvSPbk:bac7xy4) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/mobilizer.h#L322)):*
> ```objc
>   /// Sets `context` to a _zero configuration_ as defined by set_zero_state().
>   /// See set_zero_state() for details.
>   virtual void set_zero_configuration(systems::Context<T>* context) const = 0;
> ```

BTW does this need to be virtual now? From the description I would expect it just to be 
```c++
void set_zero_configuration((systems::Context<T>* context) const {
  set_zero_state(*context, &context->get_mutable_state());
}
```
or something like that.

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-ImSl_EGQvU-MS1hIX:-L-ImSl_EGQvU-MS1hIY:b-17ll) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/mobilizer_impl.h#L57)):*
> ```objc
>   /// the state in `context` according to set_zero_state().
>   void set_zero_configuration(systems::Context<T>* context) const override {
>     set_zero_state(*context, &context->get_mutable_state());
> ```

BTW oh yeah -- like that! Can't this just be an implementation in the base class, no virtual anything needed?

---

*[drake/multibody/multibody_tree/space_xyz_mobilizer.h, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-I6quBOFIzwvvDhyF_:-L-I6quBOFIzwvvDhyFa:b95arm3) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/space_xyz_mobilizer.h#L174)):*
> ```objc
>   ///   frame M.
>   /// @param[in] w_FM
>   ///   A vector in ℝ³ with the desired angular velocity of the outboard frame M
> ```

BTW line too long?

---

*[drake/multibody/multibody_tree/space_xyz_mobilizer.h, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-I6b6lcSYz7Kp83Iyn:-L-I6b6lcSYz7Kp83Iyo:bwwribn) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/space_xyz_mobilizer.h#L179)):*
> ```objc
>   const SpaceXYZMobilizer<T>& set_angular_velocity(
>       const systems::Context<T>& context, systems::State<T>* state,
>       const Vector3<T>& w_FM) const;
> ```

BTW per styleguide the output parameter `state` should come last.

---

*[drake/multibody/multibody_tree/test/free_rotating_body_plant.h, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-I87vQaZntDxfNZiAS:-L-I87vQaZntDxfNZiAT:bf8nfqu) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/test/free_rotating_body_plant.h#L71)):*
> ```objc
>   /// Returns the default value of the angular velocity set by default by
>   /// SetDefaultState().
>   Vector3<double> get_default_initial_angular_velocity() const;
> ```

BTW maybe worth mentioning that it is non-zero? I was surprised by that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-Imtqj72aM4d1IK7eT:b5v96m7)*

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-J8DtcZ3GwZXOwoEhP:b-a98c4g)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 322 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-Im2-hH6A1HNWvSPbj:-L-J9AOSZVIyJ_CGrlsU:bqtclf) ([raw file](https://github.com/robotlocomotion/drake/blob/a0aba96c4c91287ef05e60a4d1f0acc181af0de2/drake/multibody/multibody_tree/mobilizer.h#L322)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this need to be virtual now? From the description I would expect it just to be 
```c++
void set_zero_configuration((systems::Context<T>* context) const {
  set_zero_state(*context, &context->get_mutable_state());
}
```
or something like that.
</blockquote></details>

I agree. Good observation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542)*

**Comment by edrumwri** [comment]
Alejandro, I'm not seeing any means for dealing with mobilizers that have discrete state instead (though the current lack of distinction between discrete configuration and velocity variables makes this hard). What if the system using MBT is discretized a la RigidBodyPlant? 

---

Reviewed 2 of 9 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 302 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JUoZgKFxBpxk4mgWO:-L-JUoZhuUwj2NTRtNbZ:b8rnmc) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer.h#L302)):*
> ```objc
>   /// `X_FM = Id` is the identity pose. In the general case however, the zero
>   /// configuration will correspond to a value of the generalized positions for
>   /// which `X_FM = X_FM_ref` where `X_FM_ref` will generally be different from
> ```

BTW I think this description would be (very slightly) improved by changing one of the 'will's to a 'may'.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 308 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JV-PtPc0RGvC8uc6x:-L-JV-PtPc0RGvC8uc6y:b-pblzqn) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer.h#L308)):*
> ```objc
>   /// `set_zero_configuration(&ref_context)`.
>   /// In addition, all generalized velocities are set to zero in the _zero_
>   /// configuration.
> ```

Don't you mean "state"?

---

*[drake/multibody/multibody_tree/mobilizer.h, line 320 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVHQueYAr1uxSaVlJ:-L-JVHQueYAr1uxSaVlK:b-pblzqn) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer.h#L320)):*
> ```objc
>                               systems::State<T>* state) const = 0;
> 
>   /// Sets `context` to a _zero configuration_ as defined by set_zero_state().
> ```

Don't you mean "state"?

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVSainNB4PRDUMrjr:-L-JVSajXMdN6NPMt8tn:b-96g8qd) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L56)):*
> ```objc
>   /// Default implementation to Mobilizer::set_zero_state() that sets all
>   /// generalized positions and generalized velocities related to this mobilizer
>   /// to zero. Be aware however that this default does not apply in general to
> ```

The default still "applies"- it's just no longer correct! 

Also, do your existing mobilizers catch this problem?

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVdGcS1NG9V_9NFL2:-L-JVdGcS1NG9V_9NFL3:b8zc28x) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L57)):*
> ```objc
>   /// generalized positions and generalized velocities related to this mobilizer
>   /// to zero. Be aware however that this default does not apply in general to
>   /// all mobilizers and specific subclasses (for instance for quaternions) must
> ```

Nit: "unit quaternions"

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JXD0ipatsVPkZerqe:-L-JXD0ipatsVPkZerqf:bv9d6kl) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L107)):*
> ```objc
>     // If we do return xc.segment() directly, we would instead get a
>     // Block<Block<VectorX>>, which is very different from Block<VectorX>.
>     return xc.nestedExpression().template segment<kNq>(
> ```

Just to clarify (not 100% clear from the comment): the nested expression is used just to avoid returning a Block<...>?

---

*[drake/multibody/multibody_tree/test/free_rotating_body_plant.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JWsuU4lmYN5Rw1Y2a:-L-JWsuU4lmYN5Rw1Y2b:b-va7iq7) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/test/free_rotating_body_plant.h#L48)):*
> ```objc
> 
>   /// Sets `state` to a default value corresponding to a configuration in which
>   /// the free body frame B is coincident with the world frame W.
> ```

What is the velocity set to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-JXTyk8iGi9vevOj2_:bge4oen)*

**Comment by amcastro-tri** [comment]
You are making a really good point @edrumwri, to be honest I hadn't considered that option. Talking this morning with @sherm1 we realized (I think you know about this) that probably the real problem is the distinction we have right now between continuous and discrete state. This would not be a problem if such a distinction didn't exist (and most likely it won't in the future).
I think working with `State<T>` is the right abstraction. Most likely when working "a la time stepping RBP" we'll need to come up with a temporary work around, but I still think the abstraction is correct. `State<T>` right now contains both continuous and discrete and then we should be able to pull the correct one if the MBT "knows" we are using a time stepping approach (that'd be the provisional work around until we fix the state).

---

Review status: 4 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 308 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JV-PtPc0RGvC8uc6x:-L-Xrn-Js-ApPDnYMULu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer.h#L308)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Don't you mean "state"?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/mobilizer.h, line 320 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVHQueYAr1uxSaVlJ:-L-XsEhMceHpvX8I2HFB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer.h#L320)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Don't you mean "state"?
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVSainNB4PRDUMrjr:-L-Y2BO6N4HUh0u0B_M3:brlaevq) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L56)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The default still "applies"- it's just no longer correct! 

Also, do your existing mobilizers catch this problem?
</blockquote></details>

That is a good point. I created a (protected) `set_default_zero_state()` and made this method pure virtual which then forces each mobilizer to implement it, possibly calling set_default_zero_state()`. PTAL.

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JVdGcS1NG9V_9NFL2:-L-Y2bljc_BqtLJzEE8n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L57)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit: "unit quaternions"
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/mobilizer_impl.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JXD0ipatsVPkZerqe:-L-Y2iAQnSfQXJHwEYmz:b-j98emu) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/mobilizer_impl.h#L107)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Just to clarify (not 100% clear from the comment): the nested expression is used just to avoid returning a Block<...>?
</blockquote></details>

yes, to avoid returning the strange chaining of `Block<Block<VectorX>>`.

---

*[drake/multibody/multibody_tree/test/free_rotating_body_plant.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-JWsuU4lmYN5Rw1Y2a:-L-Y3PNox9-DsSXL0-NG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/df90f85f7a8e8da9f521efcf28dee7fa137a4d32/drake/multibody/multibody_tree/test/free_rotating_body_plant.h#L48)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What is the velocity set to?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-Xp9KSxdbqKsCWy0QP:bgrzb21)*

**Comment by edrumwri** [comment]
:lgtm: (I raised the issue about discrete state not to block this PR but more to make sure that you are anticipating the problem).

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/space_xyz_mobilizer.h, line 181 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-L-byBQVVuUl-Ex1XG9V:-L-byBQWE7qgXV51I2sZ:b-nohjyb) ([raw file](https://github.com/robotlocomotion/drake/blob/6fb7f3293bdc53ace8abee316c151d732562bbaf/drake/multibody/multibody_tree/space_xyz_mobilizer.h#L181)):*
> ```objc
>       systems::State<T>* state) const;
> 
>   /// Sets `state` to store zero space x-y-z angles θ₁, θ₂, θ₃ and zero across
> ```

FYI Nit: I would say "zero across-mobilizer" since it's not clear that the words belong together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7542#-:-L-byWC7A1-p-BmuOaUZ:b-efck9u)*

**Pull request merged**
