### PR TITLE
Change Valgrind opt level to -O2

### PR DESCRIPTION
**Pull request by m-chaturvedi**
[Relevant](https://sourceforge.net/p/valgrind/mailman/valgrind-developers/?viewmonth=201806&viewday=11&style=flat)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8968)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
| Build  |`-O1` (before)  |`-O2` (after)   |
|---|---|---|
|`clang-valgrind`   | [`02:10`](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/412/) |[`01:01`](https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind/49/)   |
| `clang-valgrind-everything`  |  [`02:57`](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/410/) |[`01:05`](https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything/64/)   |
| `gcc-valgrind`  | [`01:00`](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-gcc-bazel-nightly-memcheck-valgrind/400/)   | [`01:03`](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental-memcheck-valgrind/27/)  |
| `gcc-valgrind-everything`  | [`01:10`](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-gcc-bazel-nightly-memcheck-valgrind-everything/403/) | [`01:22`](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything/29/)  |

**Comment by jamiesnape** [comment]
Can you reduce any test timeouts now? If so, it would be good to do so in this PR (maybe in a second commit).

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8968#-:-LFO0SWPAV_l_565tBZS:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8968#-:-LFOPy02BpDNWdX6jlM6:bnfp4nl)*

**Pull request merged**
