### PR TITLE
Made RigidBody:visualization_elements private.

### PR DESCRIPTION
**Pull request by liangfok**
Modified its name to be `RigidBody::visualization_elements_`. Renamed accessors to conform to style guide.

Builds upon #2907.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2908)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-:-KNtgmJhU17Fp-1dyTvh:-1516772162)*

**Comment by sherm1** [comment]
Platform review done. Needs one name adjustment.

---

Reviewed 11 of 27 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 81 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-KNuRONyody-clmBcArA:-KNuRONyody-clmBcArB:1084538593) ([raw file](https://github.com/robotlocomotion/drake/blob/4e11d67df9d3c0b47533b6520ea6a4214613d660/drake/systems/plants/RigidBody.cpp#L81)):*
> ```cpp
> }
> 
> const DrakeShapes::VectorOfVisualElements& RigidBody::getVisualElements()
> ```

Since this is just an accessor, it would be better named `get_visual_elements()`. (I'm happy with `AddVisualElement()` though since it could do a heap reallocation and move.)

---

*[drake/systems/plants/RigidBody.h, line 146 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-KNuR_5YjFHriCflGScC:-KNuR_5YjFHriCflGScD:-250987395) ([raw file](https://github.com/robotlocomotion/drake/blob/4e11d67df9d3c0b47533b6520ea6a4214613d660/drake/systems/plants/RigidBody.h#L146)):*
> ```objc
>   void addVisualElement(const DrakeShapes::VisualElement& elements);
> 
>   const DrakeShapes::VectorOfVisualElements& getVisualElements() const;
> ```

Since this is just an accessor, it would be better named `get_visual_elements()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-:-KNuRzRttchPb_8ui3xg:277834365)*

**Comment by liangfok** [comment]
@sherm1 I addressed your comments. PTAL. Thanks!

---

Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 81 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-KNuRONyody-clmBcArA:-KNvXCjdz2wAcSacpHS0:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4e11d67df9d3c0b47533b6520ea6a4214613d660/drake/systems/plants/RigidBody.cpp#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Since this is just an accessor, it would be better named `get_visual_elements()`. (I'm happy with `AddVisualElement()` though since it could do a heap reallocation and move.)
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 146 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-KNuR_5YjFHriCflGScC:-KNvXEwVlJZ0P6C7EnnN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4e11d67df9d3c0b47533b6520ea6a4214613d660/drake/systems/plants/RigidBody.h#L146)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Since this is just an accessor, it would be better named `get_visual_elements()`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-:-KNvXGnSokHB6O-QU7wE:1448456807)*

**Comment by sherm1** [comment]
Thanks, :lgtm:. I'm going to declare this sufficiently reviewed and mergeable. -@amcastro-tri.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2908#-:-KNxKHbxtudymsqIozW-:-565572660)*

**Pull request merged**
