### PR TITLE
Add LCM simulation of the iiwa arm 

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3936)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KV6XpLwquAQvRlyq3br:b-psw9ws)*

**Comment by naveenoid** [comment]
Echoing comments from #3928 : a detailed description of what kuka_simulation does might be vital. Especially since its probably going to be the entry point for anyone looking to simulate the IIWA and try out various things. Also as noted in comments below, please consider moving some of the code into its own header / library. Sooner this is done, the easier it gets to manage the IIWA code base.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAPRRr80CXyCgMLbfa:-KVAPRRr80CXyCgMLbfb:b-ffq741) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L42)):*
> ```cpp
> 
> template <typename T>
> class IiwaCommandReceiver : public systems::LeafSystem<T> {
> ```

BTW: Might be useful to consider moving this to a "System" folder. Its a good wrapper for all LCM controlled fully-actuated kinematic chains; not just the IIWA. Perhaps you could leave a TODO to that effect? <just a suggestion!>

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAPqq7d8xCvvRZbAGp:-KVAPqq7d8xCvvRZbAGq:bihai4v) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L76)):*
> ```cpp
> class IiwaStatusSender : public systems::LeafSystem<T> {
>  public:
>   IiwaStatusSender() {
> ```

BTW: Would be useful to have a comment in here stating that this port is for the state and the next DeclareInputPort is for the received command 

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVAP0zqM0SVPp0tiI15:b-frma96) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
> ```cpp
> // TODO(sam.creasey) De-duplicate this with kuka_demo.cc.
> template<typename T>
> class SimulatedKuka : public systems::Diagram<T> {
> ```

Why not factor out this class into its own header / library? It would make sense that this system underlies all the Kuka examples / unit test executables (Echoing your comment above this class a bit).

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAQODGCj27HyXJh0mE:-KVAQODGCj27HyXJh0mF:bbn8a9o) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L144)):*
> ```cpp
>                  plant_->get_num_positions());
> 
>     // Create and add PID controller.
> ```

This should state PD controller  + gravity compensation. 

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVATKuNFuZSTXipGxtp:-KVATKuOkOeyDJBJ8QQE:bx63jfi) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L177)):*
> ```cpp
> 
>     // Generates an error signal for the PID controller by subtracting the
>     // desired plan state from the RigidBodyPlant's (iiwa arm) state.
> ```

BTW: Im not sure I understand the next couple of lines. Where is the error signal being generated? I dont obviously see the "subtraction"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVA_QlSGNdBigStPG_C:b-5u85ju)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAPRRr80CXyCgMLbfa:-KVAm2OOONuwIEx933oq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L42)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Might be useful to consider moving this to a "System" folder. Its a good wrapper for all LCM controlled fully-actuated kinematic chains; not just the IIWA. Perhaps you could leave a TODO to that effect? <just a suggestion!>
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAPqq7d8xCvvRZbAGp:-KVAmNL_2eH1EH4R1vUE:bm3rljy) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L76)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Would be useful to have a comment in here stating that this port is for the state and the next DeclareInputPort is for the received command 
</details>
Cleaned up the class comment a bit.  Is that sufficient?

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAQODGCj27HyXJh0mE:-KVAmUvHhNEXXVhpyXMT:bn0ebbj) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L144)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> This should state PD controller  + gravity compensation. 
</details>
The comments were copied from kuka_demo.cc.  Removed.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVATKuNFuZSTXipGxtp:-KVAn9ExAbITsaIMah2Y:bn0ebbj) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L177)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Im not sure I understand the next couple of lines. Where is the error signal being generated? I dont obviously see the "subtraction"
</details>
The comments were copied from kuka_demo.cc.  Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVBMXtjyLBjAcvDY9bQ:b-vv7rp9) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Why not factor out this class into its own header / library? It would make sense that this system underlies all the Kuka examples / unit test executables (Echoing your comment above this class a bit).
</details>
I agree we should do this, but I'm not actually sure that the common structure from thie class and kuka_demo.cc is going to turn out to be the right thing to do for one of my upcoming goals, which is to demonstrate a system with a iiwa + schunk gripper (which will, at the least, require a different RigidBodyTree/Plant which I'm not sure what it looks like yet (or quite how to build it, but I've managed to spike something close-ish).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVBNI1-_m0H2Y9Nn0b9:blac7yk) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I agree we should do this, but I'm not actually sure that the common structure from thie class and kuka_demo.cc is going to turn out to be the right thing to do for one of my upcoming goals, which is to demonstrate a system with a iiwa + schunk gripper (which will, at the least, require a different RigidBodyTree/Plant which I'm not sure what it looks like yet (or quite how to build it, but I've managed to spike something close-ish).
</details>
I could still do this now and reduce the existing duplication, which I am pondering going ahead with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVBTLbtMGikMeNhNmzL:b-gbk9vg)*

**Comment by ggould-tri** [comment]
This looks broadly reasonable to me.

It is not clear to me where the guarantee comes from that the fields of the RBP output are in the same order as the fields in the LCM message.  Does the URDF parser provide such a guarantee in this case?  Or does this just happen to be true?  It seems like `kuka_simulation` sneaks in this assumption without comment, and I think it deserves a mention.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBVeHxvJOCG8wS6cvU:-KVBVeHxvJOCG8wS6cvV:bv2srxh) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L50)):*
> ```cpp
> // TODO(sam.creasey) If this could be made slightly more generic, it
> // could be a good wrapper/template for LCM controlled robots.
> template <typename T>
> ```

Can this `T` ever be other than `double` and still work?  I don't think `lcmt_iiwa_command` below would work well with that.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBWZ1NDVUJibCXIY1f:-KVBWZ1NDVUJibCXIY1g:b-e244t0) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L83)):*
> ```cpp
> // current state of the plant and input port one for the most recently
> // received command.
> template <typename T>
> ```

Can this `T` ever be other than `double` and still work?  I don't think `lcmt_iiwa_status` below would work well with that.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 175 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBYUoyuuTZIR2vXDQK:-KVBYUoyuuTZIR2vXDQL:bs868rd) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L175)):*
> ```cpp
>         plant_->get_num_states(), plant_->get_num_positions());
> 
>     // Splits the RBP output into positions (q) and velocities (v).
> ```

It is not clear to me how the line below does what this comment says.  Can you clarify?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVBZ66Z0m4xZ9TFlTmy:by62qtf)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by sammy-tri** [comment]
Added a function to verify that the joint positions of the constructed tree match the expectations of the system being constructed.

---

Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBVeHxvJOCG8wS6cvU:-KVBdTqr-yzfxcVqIvHT:bhd7tyf) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L50)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Can this `T` ever be other than `double` and still work?  I don't think `lcmt_iiwa_command` below would work well with that.
</details>
Nope, I can't see how it would work.  Changed to double.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBWZ1NDVUJibCXIY1f:-KVBdZAjYu3oQptaLTue:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L83)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Can this `T` ever be other than `double` and still work?  I don't think `lcmt_iiwa_status` below would work well with that.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 175 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVBYUoyuuTZIR2vXDQK:-KVBdj3LlLTxRgeuy6Ss:b-jzhz6q) ([raw file](https://github.com/robotlocomotion/drake/blob/1162392749968cbaa6d1c7fe45f6632d8a8fa18f/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L175)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> It is not clear to me how the line below does what this comment says.  Can you clarify?
</details>
Removed.  I think the comment above describes rbp_state_demux_ better (I hope)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVBlW4vXAmclDwRTMJD:b84lgar)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVBnFVS77_DUt0Om_2D:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVCAa9P90vbAzI3M3N_:byi18wl) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I could still do this now and reduce the existing duplication, which I am pondering going ahead with.
</details>
I'd be ok with a TODO now to speed it up. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by naveenoid** [comment]
Im good with your choice on the TODO as noted in the comments below. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVCAnXxzZ6NIHRIdtM7:b-ls23m5) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> I'd be ok with a TODO now to speed it up. 
</details>
A slightly improved TODO would be  fine too..I leave it to you. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVCB0xrXlE-1VPcwZVe:b5mwhut)*

**Comment by sammy-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVAP0zqM0SVPp0tiI14:-KVCCyD1TyKSV0LZQ2y5:b27inbk) ([raw file](https://github.com/robotlocomotion/drake/blob/e549e0cf1acaa5764b909ecae17acb3b2352098a/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L119)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> A slightly improved TODO would be  fine too..I leave it to you. 
</details>
Done.  (improved TODO)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
Reviewed 2 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 260 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVQh7SFFkc_wWcguSx1:-KVQh7SGAT_2psvaWVDb:b3afto9) ([raw file](https://github.com/robotlocomotion/drake/blob/21aec7c207c2def7a4541059d3f79d653eab16e8/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L260)):*
> ```cpp
> 
>   // Simulate for a very long time.
>   simulator.StepTo(1e6);
> ```

BTW, can we make this a command line option that defaults to inifinity? See example here:

https://github.com/liangfok/drake/blob/feature/sys2_car_sim/drake/automotive/car_sim_lcm.cc#L247

That way we can add it as a unit test:

https://github.com/liangfok/drake/blob/feature/sys2_car_sim/drake/automotive/CMakeLists.txt#L84

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
I left one BTW comment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVQi-Lo7MLUY0grgGgt:btfgztt)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by sammy-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 260 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVQh7SFFkc_wWcguSx1:-KVQnsF_PfMSLDQJh4Uz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/21aec7c207c2def7a4541059d3f79d653eab16e8/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L260)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, can we make this a command line option that defaults to inifinity? See example here:
> 
> https://github.com/liangfok/drake/blob/feature/sys2_car_sim/drake/automotive/car_sim_lcm.cc#L247
> 
> That way we can add it as a unit test:
> 
> https://github.com/liangfok/drake/blob/feature/sys2_car_sim/drake/automotive/CMakeLists.txt#L84
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by ggould-tri** [comment]
Nice!

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVQovl0jizHLNg_23iG:b-83sjoh)*

**Comment by sammy-tri** [comment]
Fairly late in the development of this patch, I finally noticed a debug build failure where I wasn't correctly providing target velocities to the PidControlledSystem.  As we don't have a way to determine the correct target velocities, I disabled the D term in the simulation and added a multiplexer to feed in zeros in r9.  @naveenoid (and @ggould-tri if you're so inclined) PTAL.

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVRT4rY0xZO1pm66eNo:bf6spu1)*

**Comment by naveenoid** [comment]
I agree wth the need to modify the controller to only feed in desired positions, however I wonder if without a Derivative term in the controller, if there might be too many oscillations. A small D might still be useful in order to accurately settle in the goal position. 

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 183 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVUhA47Hqpn1NBlrpMW:-KVUhA47Hqpn1NBlrpMX:bms5de) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L183)):*
> ```cpp
>     // want target velocities to calculate the D term.  Since we don't
>     // have any logic to calculate the desired target velocity (yet!)
>     // set the D term to zero above and feed in zero inputs.
> ```

As noted above..please consider a small D term in anycase (thus targetting settling at a position with 0 velocity). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVUgdonafY6-fx72Xev:b-pavkuf)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 179 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVUydV9EYxmZs4liGia:-KVUydV9EYxmZs4liGib:by1mhor) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L179)):*
> ```cpp
> 
>     // The iiwa's control protocol doesn't have any way to express the
>     // desired value for the arm, so this simulation doesn't take
> ```

FYI -- "the desired value for the arm" here is a little vague.  Do you mean "the desired velocity" perhaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 183 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVV9XdMeZDxw7cZ6J00:-KVV9XdMeZDxw7cZ6J01:b-q9sje5) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L183)):*
> ```cpp
>     // want target velocities to calculate the D term.  Since we don't
>     // have any logic to calculate the desired target velocity (yet!)
>     // set the D term to zero above and feed in zero inputs.
> ```

BTW, I think it would be clearer to change "feed in zero inputs" to be "feed in a zero desired velocity vector."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 183 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVV9XdMeZDxw7cZ6J00:-KVVB1ZT1A5PtA7Yrn1H:b-irdfir) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L183)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I think it would be clearer to change "feed in zero inputs" to be "feed in a zero desired velocity vector."
</details>
Or maybe "feed in a desired velocity of zero."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by sammy-tri** [comment]
I actually ended up going back to the previous D value of 1.0 for now since the oscillation looked fairly significant (qualitatively, watching the model in the visualizer).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 179 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVUydV9EYxmZs4liGia:-KVVMFkKz8igFy9K8N3r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L179)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- "the desired value for the arm" here is a little vague.  Do you mean "the desired velocity" perhaps?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 183 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVUhA47Hqpn1NBlrpMW:-KVVMQV2hmACQychpm_D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L183)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> As noted above..please consider a small D term in anycase (thus targetting settling at a position with 0 velocity). 
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 183 at r9](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVV9XdMeZDxw7cZ6J00:-KVVMfpHZni0c3Q7znSG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef60d48de4fbfcb4710b884ef9799cdd59f661e2/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L183)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Or maybe "feed in a desired velocity of zero."?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVVPFOZznYFXzerDQ6E:b-wj8fk4)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 184 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVVU5ndlbuV2Jj5H-Nz:-KVVU5neGRoQc7KwG1bL:b-ugmu1q) ([raw file](https://github.com/robotlocomotion/drake/blob/560f49982e1dc43702855f6b76d5cf806d8f9d88/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L184)):*
> ```cpp
>     // want target velocities to calculate the D term.  Since we don't
>     // have any logic to calculate the desired target velocity (yet!)
>     // set the D term to a small value (to stabilize the arm near the
> ```

BTW, consider replacing "a small value" with "a value of 1". IMHO, a value is 1 is relatively large compared to `Kp = 2`!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by sammy-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 184 at r10](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-KVVU5ndlbuV2Jj5H-Nz:-KVVwW5ZSnF6a5I3A8SM:b-2ja5th) ([raw file](https://github.com/robotlocomotion/drake/blob/560f49982e1dc43702855f6b76d5cf806d8f9d88/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L184)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider replacing "a small value" with "a value of 1". IMHO, a value is 1 is relatively large compared to `Kp = 2`!
</details>
Done. (removed explicit reference to value)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3936#-:-KVVxoTuFqK70oUTinrB:bnfp4nl)*

**Pull request merged**
