### PR TITLE
py mathematical_program: Cleanup and enable non-everything testing

### LINKED ISSUE #10062: pybind11: Update fork
As evidenced in https://github.com/RobotLocomotion/pybind11/pull/26, the staleness of this fork is affecting ease of interpreting CI results.

Current PRs in flight are:
- [x] ~https://github.com/RobotLocomotion/drake/pull/9368~ #10061
- [x] https://github.com/RobotLocomotion/pybind11/pull/20

\cc @jamiesnape

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
~Resolves #10062~
Issue resolved by #10061

Requires:
- [x] RobotLocomotion/pybind11#20

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9368)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Something magical is dying in `--everything`, which is causing all returned `Binding<>` classes to be effectively empty?

**Comment by SeanCurtis-TRI** [comment]
@EricCousineau-TRI assigned to you for the sake of PR hygiene.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Is the first commit required for the second commit? I was just expecting a SHA bump here.

**Comment by EricCousineau-TRI** [comment]
It's not, but it's a nice-to-have such that we can get more testing even if Gurobi is not present.
Would you like me to strip it out and submit it as a separate PR?

**Comment by EricCousineau-TRI** [comment]
Cool, going to merge as-is, no squash, since the upstream `pybind` commit is a merge and thus will be present.

**Comment by jwnimmer-tri** [comment]
>  _COMMIT = "c3fddfd8b73c370d5f760e0c1b19212ea84cec36" 

I would really like to discourage using non-mainline commits from externals, even if they are guaranteed not to be pruned because they are a child of something on the default branch.  Using only the mainline of the default branch (merge or squash commits) means we have a total order on sha's, and it's clear which prior-dated commits are in play.  Using child commits of the merge commit confuses the issue of what exactly is being pulled in.

**Comment by EricCousineau-TRI** [comment]
Sounds good. Will update to use mainline commit then.

**Comment by EricCousineau-TRI** [comment]
I've incorporated the upstream updates into #10061 since it had passing CI, so I've simplified the scope of this PR to just be the minor update to increase testing on `mathematicalprogram` without needing `--config=everything`.

**Pull request merged**
