### PR TITLE
python3 prep, unittest: Remove deprecated test methods (`assert*Equals` => `assert*Equal`)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Simple fix towards #8352

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8607)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for all review, please.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8607#-:-LAG22kzEjVg_9JhWXlQ:b885tgx)*

**Comment by sammy-tri** [comment]
:lgtm: once the linter is happy.

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8607#-:-LAJNHBa4fA3WNK4qjYQ:byhrnf7)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8607)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8607)*

**Pull request merged**
