### PR TITLE
[workspace] Build libtiff_internal from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Deprecate libtiff from the host OS and remove it from setup prereqs.

Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20331)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review of the TIFF configuration, please.  (Specifically, I mean the settings of `FOO_SUPPORT` macros scattered throughout `package.BUILD.bazel`, e.g., for LZW vs CCITT vs JPEG etc.)

+@rpoyner-tri for feature review of the build system stuff, please -- and also for platform review per schedule (tomorrow).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: for both requests to me.

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20331#-:-NgPMP5G2Tlr75o98Uze:bnk43ys)* status: LGTM missing from assignee zachfang

**Review by zachfang — COMMENTED** [review]
:lgtm: 

From my understanding, the motivation to build internally is to carve out the files/dependencies we don't need so we have a smaller footprint?

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20331#-:-NgPq7A-9h3s6k5JsgSB:b-p062c6)* status: 1 unresolved discussion

___
*[`tools/workspace/libtiff_internal/repository.bzl` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20331#-NgPocfiA3z09YqF726f:-NgPocfiA3z09YqF726g:b-gmu6cc) ([raw file](https://github.com/RobotLocomotion/drake/blob/88542318ece12fac6cf7720407672fee65315a58/tools/workspace/libtiff_internal/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         # N.B. Upstream is https://gitlab.com/libtiff/libtiff but this github
>         # mirror seems to be kept up to date.
> ```

BTW. Is this because we prefer a GitHub source to Gitlab? 



_Code quote:_
```Starlark
        # N.B. Upstream is https://gitlab.com/libtiff/libtiff but this github
        # mirror seems to be kept up to date.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> From my understanding, the motivation to build internally is to carve out the files/dependencies we don't need so we have a smaller footprint?

There are several reasons.  That's one of them, but there are more also:

(2) Have the normal builds and wheel builds use the same tiff build system, to reduce the possibility that wheels are broken and we don't notice it quickly enough.

(3) Per #17231, ensure that we don't impose any particular version of libtiff on our users, in case they want a different one.

(4) When debugging, gdb will have line numbers & local variables & etc for libtiff in case we need to step into it.  Ditto for ASan, etc.

(5) We can fix bugs in libtiff without waiting for anyone else to make new binaries for us.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20331#-:-NgPs5SsEB4G__aLRLDa:b-pembj3)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),zachfang

___
*[`tools/workspace/libtiff_internal/repository.bzl` line 9 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20331#-NgPocfiA3z09YqF726f:-NgPtJPn3QFZGXUBQgvZ:ba71xbo) ([raw file](https://github.com/RobotLocomotion/drake/blob/88542318ece12fac6cf7720407672fee65315a58/tools/workspace/libtiff_internal/repository.bzl#L9)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Is this because we prefer a GitHub source to Gitlab?
</blockquote></details>

Yes.  We have repository rule sugar ("github_archive") for downloading code from github, keeping a mirror of it, and noticing when a new release has been posted so that we can upgrade.  We don't have that infrastructure built up for gitlab.

**Comment by zachfang** [comment]
Thanks for the clarifications!

**Pull request merged**
