### PR TITLE
[doc] Withdraw tutorials from Colab

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #13683.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16568)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
I think this requires more thoughtful discussion of the pros and cons.  Perhaps we can f2f.

Currently, Colab is the only jupyter-in-the-sky provider I know that offers GPU support in the free tier.  For e.g. pytorch + drake examples, it has a significant advantage.  Many people still like prefer various workflows.

I definitely understand not wanting to carry bionic along just for this.  I also appreciate the goal of having a hard linear for "it's supported or it's not supported".  But perhaps there is a compromise that avoids going nuclear on every mention of colab in the repo?

cc @peteflorence 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16568#-:-MwBlZniCGE74CVgoYc1:bxlgbn8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Sure, I'm happy to chat when we have time.  We can talk though the details then, but I'll try to clarify my big picture in the PR here for starters:

I'd be fine to wordsmith some of the documentation and comments here to retain mention of Colab, maybe I did remove too much. My primary objective is that our new-user tutorials page (drake/tutorials/README) should not steer users to run the tutorials on Colab. I'd like Drake's developers who PR tutorials to only need to manually test them in two places (once with Jupyter locally, once on the online host).  With Deepnote as our target for tutorial hosting, that means removing Colab from the tutorials instructions, so that we don't need to worry specifically about whether our tutorials run correctly there or not.

**Comment by jwnimmer-tri** [comment]
I've pushed a more surgical change, which should serve as a better basis for discussion.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  +@rpoyner-tri for platform review (or pass to tomorrow's platform)

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16568#-:-MwYX379CnE7Y6ZVzmre:bqj7tl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16568#-:-MwYY3MaBIn7EHNWzfNU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform) (waiting on @jwnimmer-tri)

**Comment by peteflorence** [comment]
Hey folks! Just seeing this now.  I don't personally know too much about the colab roadmap.  I'll see if I can connect Russ directly with someone who would know more.

**Comment by jwnimmer-tri** [comment]
For reference, the Colab issue is https://github.com/googlecolab/colabtools/issues/1880 and in particular see https://github.com/googlecolab/colabtools/issues/1880#issuecomment-944319649 and related discussions.  The entire "scientic python" ecosystem (including Drake, after about ~3 weeks from today) has stopped supporting Python 3.7 per NEP-29.

**Comment by peteflorence** [comment]
Thanks Jeremy!  Yeah I hope the Colab team is able to provide an update.

**Pull request merged**
