### PR TITLE
Rename RigidTransform::IsIdentityToEpsilon to IsNearlyIdentity

### LINKED ISSUE #16524: refactor RigidTransform IsIdentityToEpsilon => IsNearlyIdentity?
Currently `RigidTransform` has 
- `IsExactlyEqualTo`
- `IsNearlyEqualTo`
- `IsExactlyIdentity`, and...
- `IsIdentityToEpsilon` 

I find myself often typing `IsNearlyIdentity` and getting reminded by the compiler.  Can we pick one and stick?

### PR DESCRIPTION
**Pull request by mitiguy**
Closes #16524.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvMAcVt7tAoARYG_NxE:b-59nlc1)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Jenkins is calling out some linter errors.

(Remember to run `bazel test --config lint //...` before opening a PR.)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvMG0cKD0kzQINAFlV9:b-hqa67p)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

___
*[math/rigid_transform.h, line 404 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMDueQ4fgwtIvm4FkK:-MvMDueQ4fgwtIvm4FkL:b-cmb9mt) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/rigid_transform.h#L404)):*
> ```objc
>   }
> 
>   /// Returns `true` if the RotationMatrix portion of `this` satisfies
> ```

The original code's doc began with a nice summary "Returns true if this is within tolerance of the identity RigidTransform" (see [link](https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_rigid_transform.html#ae4c29dcfbeeb594af24ae82cff87f35f)).  That summary shows up in the class's overview table (see [link](https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_rigid_transform.html#pub-methods)).

The new text is substantially longer and more difficult to understand at a glance:


Was removing the brief summary a purposeful change?  It seems worse to me.
___
*[math/rigid_transform.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMF-i57ZMbyFaXDKAE:-MvMF-i57ZMbyFaXDKAF:brw3qvx) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/rigid_transform.h#L427)):*
> ```objc
>   /// (e.g., RotationMatrix::get_internal_tolerance_for_orthonormality()).
>   /// @see IsExactlyIdentity().
>   DRAKE_DEPRECATED("2022-06-01","Use RigidTransform::IsNearlyIdentity()")
> ```



This does not render well in Doxygen (for example, the confusing "See also" callout).  Usually, we will nuke the documentation for the deprecated function.  If you insist in keeping it, add the word "(Deprecated.)" to the start of the comment here so that it shows up in the brief that way, and add some line breaks or something here so that the "(Deprecated.") text that comes from the macro isn't tacked onto the "See also" callout.
___
*[math/test/rigid_transform_test.cc, line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMFdEM8GF-_bLgYl-b:-MvMFdEM8GF-_bLgYl-c:b-la5nn9) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/test/rigid_transform_test.cc#L402)):*
> ```cpp
>   EXPECT_FALSE(X2.IsNearlyIdentity(3.99));
>   EXPECT_TRUE(X2.IsNearlyIdentity(4.01));
> #pragma GCC diagnostic push
> ```

FYI You don't need to duplicate _every_ test case.  The old function name calls the new function, so a single test call to the old function name would have been sufficient.  Fine to leave it alone now, though, since it's already written.

**Review by mitiguy — COMMENTED** [review]
Thank you for that important reminder.
I added it to my notes on python deprecation.

> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvQV29lBLlwb5pUJsq3:bumw4wn)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[math/rigid_transform.h, line 404 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMDueQ4fgwtIvm4FkK:-MvQUNrvBrJLf3hNEuBm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/rigid_transform.h#L404)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The original code's doc began with a nice summary "Returns true if this is within tolerance of the identity RigidTransform" (see [link](https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_rigid_transform.html#ae4c29dcfbeeb594af24ae82cff87f35f)).  That summary shows up in the class's overview table (see [link](https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_rigid_transform.html#pub-methods)).

The new text is substantially longer and more difficult to understand at a glance:


Was removing the brief summary a purposeful change?  It seems worse to me.
</blockquote></details>

Done.
___
*[math/rigid_transform.h, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMF-i57ZMbyFaXDKAE:-MvPsF16D5bQpLZWee5k:b-onrqmc) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/rigid_transform.h#L427)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>



This does not render well in Doxygen (for example, the confusing "See also" callout).  Usually, we will nuke the documentation for the deprecated function.  If you insist in keeping it, add the word "(Deprecated.)" to the start of the comment here so that it shows up in the brief that way, and add some line breaks or something here so that the "(Deprecated.") text that comes from the macro isn't tacked onto the "See also" callout.
</blockquote></details>

Done.  Removed old documentation.
Also, I added that to my notes on python deprecation.
___
*[math/test/rigid_transform_test.cc, line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvMFdEM8GF-_bLgYl-b:-MvPpq4q5VL09XOkcyDR:bt521tr) ([raw file](https://github.com/robotlocomotion/drake/blob/7283f75ffa9337774f29a6daa27a04b6d40b8279/math/test/rigid_transform_test.cc#L402)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI You don't need to duplicate _every_ test case.  The old function name calls the new function, so a single test call to the old function name would have been sufficient.  Fine to leave it alone now, though, since it's already written.
</blockquote></details>

Done.  I'll leave them as is.  
However, I added that to my notes on python deprecation.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@xuchenhan-tri for platform review per schedule, please.

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvQjOXkCtfhKcHg50SX:brw9p00)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvQoDf_ARqsMkq3jsno:b-vtj4vo)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[math/test/rigid_transform_test.cc, line 614 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvQn8d1-5jvz53EzvCs:-MvQn8d24m0_08zfebEF:b50addh) ([raw file](https://github.com/robotlocomotion/drake/blob/c70c04d30aa803253db504b2aefd2d0b5f52e274/math/test/rigid_transform_test.cc#L614)):*
nit is verifying a subtype of the exception necessary here?

Quote from GSG https://drake.mit.edu/styleguide/cppguide.html#Exceptions:
> Only test for a specific subtype of std::exception when the subtype is necessary to determine whether the code behaved correctly, e.g., in cases where the code may throw several different types of exception and the subtype fully disambiguates which condition was triggered. (This is rare.) 
___
*[bindings/pydrake/math_py.cc, line 110 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvQnVh-BZgYekQSOE2x:-MvQnVh-BZgYekQSOE2y:b-wiotaw) ([raw file](https://github.com/robotlocomotion/drake/blob/c70c04d30aa803253db504b2aefd2d0b5f52e274/bindings/pydrake/math_py.cc#L110)):*
> ```cpp
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>     cls  // BR
> ```

BTW, beautifully deprecated!

**Review by mitiguy — COMMENTED** [review]
status +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16541#-:-MvQrEo7-87pYV55ykBs:bjcgzrm)* status: missing label for release notes (waiting on @mitiguy)

**Comment by jwnimmer-tri** [comment]
___
*[math/test/rigid_transform_test.cc, line 614 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16541#-MvQn8d1-5jvz53EzvCs:-MvQtSRW4MOSEpMge_9j:b7dpxuq) ([raw file](https://github.com/robotlocomotion/drake/blob/c70c04d30aa803253db504b2aefd2d0b5f52e274/math/test/rigid_transform_test.cc#L614)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit is verifying a subtype of the exception necessary here?

Quote from GSG https://drake.mit.edu/styleguide/cppguide.html#Exceptions:
> Only test for a specific subtype of std::exception when the subtype is necessary to determine whether the code behaved correctly, e.g., in cases where the code may throw several different types of exception and the subtype fully disambiguates which condition was triggered. (This is rare.) 

</blockquote></details>

It's true that this check for `runtime_error` (vs mere `exception`) is against the GSG rule.  However, under the premise of "duplicating an already-written unit test for purposes of retaining deprecation test coverage", I think it was okay to leave it unchanged within this PR.

**Pull request merged**
