### PR TITLE
[parsing] Support actuator/motor tags in MuJoCo parser

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #16369

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@joemasterjohn for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630#-:-MwHW0_d7jhhvWF8mY_V:b7bdkx2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a small request. +@rpoyner-tri for platform review, please.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630#-:-MwY36kl4RtUQdgS0h_c:b-7mhpek)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY1tt7DOtXHsGEnRA-:-MwY1tt7DOtXHsGEnRA0:b-vjwzwh) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/detail_mujoco_parser.cc#L170)):*
> ```cpp
>       Vector2d ctrl_range;
>       if (ParseVectorAttribute(node, "ctrlrange", &ctrl_range)) {
>         effort_limit = std::max(ctrl_range[1], -ctrl_range[0]);
> ```

We should enforce `ctrl_range[0] <= ctrl_range[1]` here. If a user accidentally inputs "1 -1" the effort_limit will be negative and the plant will bark when adding the joint actuator.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY2Bzi4EcqwjzGMraX:-MwY2Bzi4EcqwjzGMraY:b55b1kn) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/detail_mujoco_parser.cc#L187)):*
> ```cpp
>       if (ParseVectorAttribute(node, "forcerange", &force_range)) {
>         effort_limit =
>             std::min(effort_limit, std::max(force_range[1], -force_range[0]));
> ```

Ditto for enforcing `force_range[0] <= force_range[1]`.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 735 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY2wIpEUf-9wvH-7no:-MwY2wIpEUf-9wvH-7np:bjl7kbg) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/test/detail_mujoco_parser_test.cc#L735)):*
> ```cpp
> </mujoco>
> )""";
> ```

nit: please add test coverage for malformed `ctrlrange/forcerange`.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630#-:-MwY9tvP0jGBBTWsi8GO:bnfp4nl)* status: 3 unresolved discussions (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630)* status: 3 unresolved discussions (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630)* status: 2 unresolved discussions (waiting on @joemasterjohn and @rpoyner-tri)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY1tt7DOtXHsGEnRA-:-MwYzKACA9QJGoqt9FxW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/detail_mujoco_parser.cc#L170)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

We should enforce `ctrl_range[0] <= ctrl_range[1]` here. If a user accidentally inputs "1 -1" the effort_limit will be negative and the plant will bark when adding the joint actuator.
</blockquote></details>

Done.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY2Bzi4EcqwjzGMraX:-MwYzKif8uZ7sSIEMmRA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/detail_mujoco_parser.cc#L187)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Ditto for enforcing `force_range[0] <= force_range[1]`.
</blockquote></details>

Done.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 735 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16630#-MwY2wIpEUf-9wvH-7no:-MwZ0Kzp2ZMgfshOykPg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab531de8feeee360a172087f719afaa1dda35ba/multibody/parsing/test/detail_mujoco_parser_test.cc#L735)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: please add test coverage for malformed `ctrlrange/forcerange`.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630)* status: 2 unresolved discussions (waiting on @joemasterjohn)

**Review by RussTedrake — COMMENTED** [review]
@joemasterjohn -- still waiting on you...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630#-:-MwZ51e902tfM-WmjtRf:b-80l3wt)* status: 2 unresolved discussions (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16630)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @RussTedrake)

**Pull request merged**
