### PR TITLE
Set sparsity pattern in the cost in snopt solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8409)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-L83b66UaLK8WxdC94TN:-L83b66UaLK8WxdC94TO:b-rvf923) ([raw file](https://github.com/robotlocomotion/drake/blob/e789b6b2b91da4e31cd3a76f8ede945760e39623/solvers/snopt_solver.cc#L352)):*
> ```cpp
>     }
>   }
>   for (const auto cost_gradient_index : UpdateCostNonzeroGradients(prog)) {
> ```

@sammy-tri , there is a caveat in this implementation, that I need to call `UpdateCostNonzeroGradients` in every call to `EvaluateAllCosts()`, which is called inside `snopt_userfun`, in every iteration of the solver. `UpdateCostNonzeroGradient` finds out the sparsity pattern in the cost function, which is unchanged across the iteration, so recomputing it in each iteration is redundant and wasteful. I did it this way because in `snopt_userfun`, we just pass in the information on `MathematicalProgram`, but we do not pass in additional information, such as the sparsity pattern. Do you think there is a better way to this problem?

One approach I thought is to store the sparsity pattern in some static variable in the file "snopt_solver.cc", so that we only call `UpdateCostNonzeroGradient` for once to set the sparsity pattern, and re-use it afterwards.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-L83b66UaLK8WxdC94TN:-L83dyczlomcG454LKFt:bz7n9lk) ([raw file](https://github.com/robotlocomotion/drake/blob/e789b6b2b91da4e31cd3a76f8ede945760e39623/solvers/snopt_solver.cc#L352)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@sammy-tri , there is a caveat in this implementation, that I need to call `UpdateCostNonzeroGradients` in every call to `EvaluateAllCosts()`, which is called inside `snopt_userfun`, in every iteration of the solver. `UpdateCostNonzeroGradient` finds out the sparsity pattern in the cost function, which is unchanged across the iteration, so recomputing it in each iteration is redundant and wasteful. I did it this way because in `snopt_userfun`, we just pass in the information on `MathematicalProgram`, but we do not pass in additional information, such as the sparsity pattern. Do you think there is a better way to this problem?

One approach I thought is to store the sparsity pattern in some static variable in the file "snopt_solver.cc", so that we only call `UpdateCostNonzeroGradient` for once to set the sparsity pattern, and re-use it afterwards.
</blockquote></details>

You could add the sparsity information to the `SNOPTData` structure in `Solve` and then call `GetSolverData` on  the `MathematicalProgram` inside `snopt_userfun`?  It looks like `SNOPTData` is currently write-once read-never since it's only really accessed here: https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L552

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409)*

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-L83b66UaLK8WxdC94TN:-L83i1H2qArcPJOYlA7J:b-nebef4) ([raw file](https://github.com/robotlocomotion/drake/blob/e789b6b2b91da4e31cd3a76f8ede945760e39623/solvers/snopt_solver.cc#L352)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

You could add the sparsity information to the `SNOPTData` structure in `Solve` and then call `GetSolverData` on  the `MathematicalProgram` inside `snopt_userfun`?  It looks like `SNOPTData` is currently write-once read-never since it's only really accessed here: https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L552
</blockquote></details>

If we don't want to use `GetSolverData` another approach would be to pass in a pointer to a struct holding the mathematical program pointer and the sparsity info at https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L165 and then get the struct pointer back at https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L318

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-L83b66UaLK8WxdC94TN:-L84GqRTzbG1GjqvBXtu:bbilr9h) ([raw file](https://github.com/robotlocomotion/drake/blob/e789b6b2b91da4e31cd3a76f8ede945760e39623/solvers/snopt_solver.cc#L352)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

If we don't want to use `GetSolverData` another approach would be to pass in a pointer to a struct holding the mathematical program pointer and the sparsity info at https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L165 and then get the struct pointer back at https://github.com/RobotLocomotion/drake/blob/master/solvers/snopt_solver.cc#L318
</blockquote></details>

Thanks @sammy-tri , I used the second approach as you suggested, to use a pointer to hold the mathematical program and a pointer to a sparsity pattern. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409)*

**Comment by hongkai-dai** [comment]
-(status: do not review)  +@sammy-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-:-L84H5FwJ7kZ5pZPR7o1:b-vvx3e8)*

**Comment by sammy-tri** [comment]
:lgtm: with one minor comment question.  Confirimed that `snopt_solver_test` still passes locally under valgrind.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-L884a9pcvSuF8qAKKGr:-L884a9qZirerowz1x9K:b-cz2jez) ([raw file](https://github.com/robotlocomotion/drake/blob/17988949e980e2ae602218718b85cf99b7477040/solvers/snopt_solver.cc#L163)):*
> ```cpp
>     snInit();
> 
>     // Set the "maxcu" value to tell snopt to reserve one 8-char entry of user
> ```

Is this now two 8-char entries?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-:-L887ZcQB_b5w2kFQYXq:b9yh1cp)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review.  (using `std::copy` struck me as a hell of a way to move individual pointer values around, but I decided it wasn't worth raising as a defect at this time.  You may or may not agree.)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-:-L889KhTJlwjf_-oqg0U:b-jrkdhs)*

**Comment by hongkai-dai** [comment]
@sammy-tri I think your original suggestion, to use one struct that contains both MathematicalProgram* and the pointer to the sparsity pattern, is more maintainable than passing two pointers separately in the SNOPT workspace, I will change the PR to use your approach.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-:-L88AnaC72C2J3CatBWS:b-k91b6n)*

**Comment by ggould-tri** [comment]
This is all the sort of miserable code I expect at the snopt boundary.  If Valgrind likes it, it probably knows better than we do. :lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/snopt_solver.cc, line 168 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-L88HvQd8Q49OhIsypBW:-L88HvQd8Q49OhIsypBX:bnylui3) ([raw file](https://github.com/robotlocomotion/drake/blob/17988949e980e2ae602218718b85cf99b7477040/solvers/snopt_solver.cc#L168)):*
> ```cpp
>     // instance pointer and cost sparsity pattern to our userfun.
>     snSeti("User character workspace", snopt_mincw + 2);
>     {
> ```

BTW -- Would it be cleaner to make a struct for our userdata and only play pointer arithmetic games once?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-:-L88APZbE-sdtmm2bd9H:bxp76pe)*

**Comment by ggould-tri** [comment]
Ah, I see you independently arrived at the same struct conclusion I did.  Seems like consensus :-)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-:-L88JICQ4FIMtoDPsGxp:b-6ai9uy)*

**Comment by hongkai-dai** [comment]
@sammy-tri, could you help me understand this?
> (using std::copy struck me as a hell of a way to move individual pointer values around, but I decided it wasn't worth raising as a defect at this time. You may or may not agree.)

Is there an easier way to pass that struct pointer and copy it to the snopt workspace?

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/snopt_solver.cc, line 163 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-L884a9pcvSuF8qAKKGr:-L88PHNXAQASLEN9tt4I:b-stbt9) ([raw file](https://github.com/robotlocomotion/drake/blob/17988949e980e2ae602218718b85cf99b7477040/solvers/snopt_solver.cc#L163)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this now two 8-char entries?
</blockquote></details>

Done. Changed to pass one struct pointer.

---

*[solvers/snopt_solver.cc, line 168 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-L88HvQd8Q49OhIsypBW:-L88PL662pvnZD-EmnzI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17988949e980e2ae602218718b85cf99b7477040/solvers/snopt_solver.cc#L168)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Would it be cleaner to make a struct for our userdata and only play pointer arithmetic games once?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8409#-:-L88PMgpCJZOHH-cNCeC:byd3won)*

**Comment by sammy-tri** [comment]
I guess the alternative would probably be some variation on `reinterpret_cast` + assignment.  Writing a pointer in to the memory which a `char*` is pointing to probably can't be done in a non-ugly way.  I probably would have gone with something like (this is untested and doesn't have enough consts to compile exactly in the code as it reads in this pr.  also it might be wrong.):
```
  char* cu_snopt_userfun_info = d->cw.data() + 8 * snopt_mincw;
  *(reinterpret_cast<SnoptUserFunInfo**>(cu_snopt_userfun_info)) = snopt_userfun_info;
```
and to fetch
```
  char* cu_snopt_userfun_info = cu + 8 * snopt_mincw;
  SnoptUserFunInfo* snopt_userfun_info = *(reinterpret_cast<SnoptUserFunInfo**>(cu_snopt_userfun_info));
```

I don't think it's necessary to make that change at this time (or maybe ever, to some extent it's a matter of taste I suppose).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-:-L88xjdlAu8zE4auLf0-:b-lw8mhb)*

**Comment by hongkai-dai** [comment]
Thanks for the explanation! I will merge the PR in its current form then.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8409#-:-L892xzwo0Krwh98-NlY:b8itipr)*

**Pull request merged**
