### PR TITLE
Computes per node geometric Jacobian H_PB_W

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR implements the computation of the geometric Jacobian `H_PB_W` which relates to the spatial velocity of a body B in its parent body P by `V_PB_W = H_PB_W * v(B)`, where `v(B)` are the generalized velocities associated with body B.

This PR does not introduce any new public API in MBT, it only introduces the computation of `H_PB_W` which will be used in the computation of MBT Jacobian matrices. 
`H_PB_W`  can (and is) be reused to compute the velocity kinematics. Therefore this PR updates `CalcVelocityKinematicsCache` to use `H_PB_W`. The new implementation gets appropriately unit tested through the velocity kinematics tests already in master, which still pass after these updates.

In a future with caching, `H_PB_W` will become a cache entry.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7469)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-KyvUabeOsisr8DpUuxd:b-a98c4g)*

**Comment by amcastro-tri** [comment]
-@edrumwri is out of office.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-KyvVXVzUw6vz8LowOCw:b2a2w7g)*

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-KyvVc9MFHdcL7Hiv4kp:bltox9h)*

**Comment by hongkai-dai** [comment]
Very clear documentation! I have a few comments.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/body_node.h, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxrkD-nAY3DhrFtz9n:-KyxrkD-nAY3DhrFtz9o:b-ko1go1) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/body_node.h#L245)):*
> ```objc
>       const MultibodyTreeContext<T>& context,
>       const PositionKinematicsCache<T>& pc,
>       const Eigen::Ref<const MatrixUpTo6<T>>& H_PB_W,
> ```

Add @param H_PB_W in the documentation?

---

*[drake/multibody/multibody_tree/body_node.h, line 832 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxvIePKHFhpzW3qXlj:-KyxvIePKHFhpzW3qXlk:b27ibu4) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/body_node.h#L832)):*
> ```objc
>   ///   matrix has size `6 x nm` with `nm` the number of mobilities of the node.
>   ///   `H_array` stores the columns of these matrices and therefore it consists
>   ///   of a `std::vector` of spatial velocities with as many entries as number
> ```

Should you add `the` before `number of generalized velocities`?

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 234 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxwpP98Acg77GQlA5a:-KyxwpP98Acg77GQlA5b:b-mupmu3) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/multibody_tree.cc#L234)):*
> ```cpp
> 
>       Eigen::Map<const MatrixUpTo6<T>> H_PB_W =
>           node.GetJacobianFromArray(H_PB_W_cache);
> ```

`const Eigen::Map<const MatrixUpTo6<T>>`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-Kyxz0SSY5LluQzm0QjC:bse3kj7)*

**Comment by amcastro-tri** [comment]
Thank you for the review @hongkai-dai. I did a lil change under the hood. I decided it is better to store these Jacobian matrices (H_PB_W) as a `std::vector<Vector6<T>>` rather than `std::vector<SpatialVelocity<T>>`. The reason being that these Jacobian matrices can also appear in expressions involving accelerations and thus storing them as SpatialVelocity columns would hinder their use in those cases. The changes are very small though, pretty much find/replace SpatialVelocty/Vector6. PTAL.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/body_node.h, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxrkD-nAY3DhrFtz9n:-KyzwpTYPPFdGQXvq51O:bxppgvc) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/body_node.h#L245)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add @param H_PB_W in the documentation?
</blockquote></details>

woops, I forgot to add it. Done.

---

*[drake/multibody/multibody_tree/body_node.h, line 832 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxvIePKHFhpzW3qXlj:-Kyzx6Wtb0UfIZLhsWyQ:bqdlpy1) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/body_node.h#L832)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should you add `the` before `number of generalized velocities`?
</blockquote></details>

humm.... not sure really. But definite the extra `the` doesn't hurt. Done.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 234 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxwpP98Acg77GQlA5a:-KyzyEBrFUXQPGvpzr7y:b-lbm7mc) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/multibody_tree.cc#L234)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const Eigen::Map<const MatrixUpTo6<T>>`?
</blockquote></details>

Oh! I wrote a "clarifying" comment for this and I realized you were referring to the extra `const`, right? 
I thought the same, but apparently the map objects sort of "inherit" (bad overload) the constness from their template argument. See [Eigen's doc here](http://eigen.tuxfamily.org/dox/group__TutorialMapClass.html).
Here is a screenshot of an example in that page (look at the third line):


I guess it would not hurt adding the extra `const` but it'd be redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-Kyzv6AvDRkyJ088oRRB:bw55q3d)*

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-Kz-2T3BzKYj06hw4axB:b-irfx5k)*

**Comment by ggould-tri** [comment]
:lgtm:; some notes on interfaces and docs below.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/multibody_tree/body_node.h, line 779 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-6AQeXJo3ACxbf6Ad:-Kz-6AQeXJo3ACxbf6Ae:b-a14og1) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L779)):*
> ```objc
>   ///
>   /// @pre The position kinematics cache `pc` was already updated to be in sync
>   /// with `context` by MultibodyTree::CalcPositionKinematicsCache().
> ```

Does anything in the code below check this prerequisite?  I was not able to locate it if so.  I would expect it to be at the top of the method body.

Also this comment looks redundant with the parameter comment for `pc`; consider combining them.

---

*[drake/multibody/multibody_tree/body_node.h, line 787 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-5rhKkWwQjuWsbXtb:-Kz-5rhKkWwQjuWsbXtc:b3q1oe8) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L787)):*
> ```objc
>     DRAKE_ASSERT(topology_.body != world_index());
>     // Checks on the input arguments.
>     DRAKE_DEMAND(topology_.body != world_index());
> ```

Why do you assert and then demand the same thing?

---

*[drake/multibody/multibody_tree/body_node.h, line 801 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-6KBmPbP1Xi9U7iud:-Kz-6KBmPbP1Xi9U7iue:b-q6mdnx) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L801)):*
> ```objc
> 
>     // Pose of the parent body P in world frame W.
>     // Available since we are called within a base-to-tip recursion.
> ```

An assumption by a method about how it will be called should be documented (and, if possible, asserted), especially for a public method; it is not clear that future callers will know this is a requirement.

---

*[drake/multibody/multibody_tree/body_node.h, line 882 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-7kaglsQzUEDekDs8:-Kz-7kaglsQzUEDekDs9:bj4g88h) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L882)):*
> ```objc
>   }
> 
>   // Returns the index to the parent body of the body associated with this node.
> ```

Since this and the next few methods have just been made protected, please promote their comments to doxygen comment style like the methods above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-Kz-8S15vSnJ_6chWEv8:bbii1dr)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/multibody_tree/body_node.h, line 779 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-6AQeXJo3ACxbf6Ad:-Kz-HAEpfOfgms4GwSrf:buq86bh) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L779)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Does anything in the code below check this prerequisite?  I was not able to locate it if so.  I would expect it to be at the top of the method body.

Also this comment looks redundant with the parameter comment for `pc`; consider combining them.
</blockquote></details>

There is no way to check for this prerequisite at this level and we can only document this. However, this is an `internal::` class used by `MultibodyTree`. All these methods taking a cache struct will eventually get called from within MBT `Eval` methods that will ultimately take care of cache updates appropriately using our soon to arrive caching infrastructure. Since this infrastructure is not in place yet, I just focus on writing down the math in methods that might have these kind of prerequisites and I focus on documenting them. 
The plan is that MBT methods calling these methods will first `Eval()` whichever cache entry they need to pass down (like in this case the `PositionKinematics`) to these calls. As you can see in the MBT code (in `multibody_tree.cc`) I placed TODO's (saying to call `Eval()`) whenever this is the case.
Hopefully that answers your question?
Ah, users do not have access to theses `BodyNode` class at all, only MBT developers.

---

*[drake/multibody/multibody_tree/body_node.h, line 787 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-5rhKkWwQjuWsbXtb:-Kz-ITVsIIXFbfBcSfR7:b-1lnhei) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L787)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Why do you assert and then demand the same thing?
</blockquote></details>

no reason. Good catch.

---

*[drake/multibody/multibody_tree/body_node.h, line 801 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-6KBmPbP1Xi9U7iud:-Kz-Id4VWLsnhEvH-QRs:b-t0voxs) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L801)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

An assumption by a method about how it will be called should be documented (and, if possible, asserted), especially for a public method; it is not clear that future callers will know this is a requirement.
</blockquote></details>

Good catch! that comment is actually a bad copy/pasta. We are not required to be in a base-to-tip recursion here and that is no longer a requirement. 
FYI, notice I have the convention of appending `_BaseToTip` or `_TipToBase` to method's name when that does happens to be a requirement. 

---

*[drake/multibody/multibody_tree/body_node.h, line 882 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-7kaglsQzUEDekDs8:-Kz-JmQ0doeQbzGfzXG1:bfaa9f0) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L882)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Since this and the next few methods have just been made protected, please promote their comments to doxygen comment style like the methods above.
</blockquote></details>

Good catch. A left over change from my experiments in my dev branch. I reverted it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_tree/body_node.h, line 779 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-Kz-6AQeXJo3ACxbf6Ad:-Kz-QyyS9rCoCtIVNAgO:b4gdet2) ([raw file](https://github.com/robotlocomotion/drake/blob/e8efb57fb26850fdf4b270bab22dfa721db64a03/drake/multibody/multibody_tree/body_node.h#L779)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

There is no way to check for this prerequisite at this level and we can only document this. However, this is an `internal::` class used by `MultibodyTree`. All these methods taking a cache struct will eventually get called from within MBT `Eval` methods that will ultimately take care of cache updates appropriately using our soon to arrive caching infrastructure. Since this infrastructure is not in place yet, I just focus on writing down the math in methods that might have these kind of prerequisites and I focus on documenting them. 
The plan is that MBT methods calling these methods will first `Eval()` whichever cache entry they need to pass down (like in this case the `PositionKinematics`) to these calls. As you can see in the MBT code (in `multibody_tree.cc`) I placed TODO's (saying to call `Eval()`) whenever this is the case.
Hopefully that answers your question?
Ah, users do not have access to theses `BodyNode` class at all, only MBT developers.
</blockquote></details>

OK, I suppose that will have to do for now.

Our caching seems have a recurring pattern of these sorts of uncheckable stateful dependencies, but perhaps as you say it will all clear up eventually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 234 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-KyxwpP98Acg77GQlA5a:-Kz-UpBsl4pVZbQSk-th:b9zqi8o) ([raw file](https://github.com/robotlocomotion/drake/blob/7abc2a47609b1495ee7f591b8f95f9538b831d65/drake/multibody/multibody_tree/multibody_tree.cc#L234)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Oh! I wrote a "clarifying" comment for this and I realized you were referring to the extra `const`, right? 
I thought the same, but apparently the map objects sort of "inherit" (bad overload) the constness from their template argument. See [Eigen's doc here](http://eigen.tuxfamily.org/dox/group__TutorialMapClass.html).
Here is a screenshot of an example in that page (look at the third line):


I guess it would not hurt adding the extra `const` but it'd be redundant.

</blockquote></details>

I see, thanks for the clarification! I learned something today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7469#-:-Kz-V3YFPLmip2gM47wy:bnfp4nl)*

**Pull request merged**
