### PR TITLE
[workspace]  Improve new_release script to handle rust_toolchain

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21669

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please. These are the changes generated by the `new_release` script. It looks like whitespace and commas only. Is this expected?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O0p_csL0RkgggY7j1Dk:bkkz98i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
When I run the command, I don't get any changes:

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ ./tools/workspace/rust_toolchain/upgrade.py 
INFO: Downloading ALL Rust toolchains via `bazel sync`.
Starting local Bazel server and connecting to it...
 checking cached actions
INFO: Copying lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable.bazel
INFO: Copying lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable_tools.bazel
INFO: Copying lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable.bazel
INFO: Copying lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable_tools.bazel
INFO: Copying lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable.bazel
INFO: Copying lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools.bazel
INFO: Copying lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable.bazel
INFO: Copying lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools.bazel
INFO: Writing lock/archives.bzl
INFO: Invocation ID: cc053f1a-dbed-4129-945a-f689b95b14e3
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
bazel: Entering directory `/media/sdb/cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/drake/'
Analyzing: target //tools/lint:buildifier (0 packages loaded, 0 targets configured)
Analyzing: target //tools/lint:buildifier (0 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
Analyzing: target //tools/lint:buildifier (4 packages loaded, 0 targets configured)
[1 / 1] checking cached actions
INFO: Analyzed target //tools/lint:buildifier (4 packages loaded, 8 targets configured).
INFO: Found 1 target...
bazel: Leaving directory `/media/sdb/cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/drake/'
Target //tools/lint:buildifier up-to-date:
  bazel-bin/tools/lint/buildifier
[6 / 6] checking cached actions
INFO: Elapsed time: 4.370s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

The line [here](https://github.com/RobotLocomotion/drake/blob/74ad572e5df4dcfca4dd432f020b7b20e88b9236/tools/workspace/rust_toolchain/upgrade.py#L90) is supposed to run buildifier to format the files properly, but it seems like it did not work for you.

Did you see any error messages at all?  Or any console output different than mine?

**Review by BetsyMcPhail — COMMENTED** [review]
Running the command above, I get the same results as you. No errors, no changes. Running `bazel run //tools/workspace:new_release -- --lint --commit rust_toolchain`, however, does result in an error running buildifier:

```Target //tools/lint:buildifier up-to-date:
  bazel-bin/tools/lint/buildifier
INFO: Elapsed time: 0.599s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
buildifier: open lock/archives.bzl: no such file or directory
...
subprocess.CalledProcessError: Command '['../../../bazel-bin/tools/lint/buildifier', PosixPath('lock/archives.bzl')]' returned non-zero exit status 3.
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O0tbUR60-ZNCKGVOqBw:b-cp30f2)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please. With these changes, `bazel run //tools/workspace:new_release -- --lint --commit rust_toolchain` and `bazel run //tools/workspace:new_release -- --lint --commit rules_rust` should both complete without errors (with or without changes) and print a reasonable message. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O1N5ttv2eKJmaztv6m7:b-v69rox)* status: LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware, missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-O1X3glf7TP8ot6t6cLa):*
nit:



_Suggestion:_
```
  Otherwise, this will fail when called from the new_release script.
```
___
*[`tools/workspace/new_release.py` line 563 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-O1X4xr-91BcSD_p6eS8:-O1X4xr-91BcSD_p6eS9:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/7983d0f00de0f2146be2a558714a6635d6218423/tools/workspace/new_release.py#L563)):*
> ```Python
>     if not modified_workspace_names:
>         # Nothing was updated
>         names = ', '.join(workspace_names)
> ```

nit:



_Suggestion:_
```Python
        names = ", ".join(workspace_names)
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware, missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O1Xj03G0aLqowRwlce7:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
@jwnimmer-tri would you like to do platform review on this one?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O1XjCTyDtHc6Zuy23l-:bcm2fyo)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21672#-:-O2QWeK71kalTPPfgsdd:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mwoehlke-kitware

**Pull request merged**
