### PR TITLE
examples: Add/update doxygen block diagrams

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #9496

Also:
 * add port names to a Diagram
 * fix a doxygen comment separated from its class declaration
 * fix inconsistent variable subscripts found in comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(priority: low) +@RussTedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204#-:-Mqa9xtaANyblejv6fkr:b-53jbcg)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204#-:-MrSh9Gv7TJ1yEKiVyxv:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSfOD7C5wD7X02hvBX:-MrSfOD8-Mz7mqV45wia:baolsrn) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/kuka_iiwa_arm/kuka_torque_controller.h#L27)):*
> ```objc
>  * name: KukaTorqueController
>  * input_ports:
>  * - u0
> ```

These don't look right.  I see multiple `ExportInput` calls in the constructor?  And these are sort of begging to be named (since they have methods to access them by a name)
___
*[examples/scene_graph/bouncing_ball_plant.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSg_b9EGcyDwSk5pdP:-MrSg_b9EGcyDwSk5pdQ:b-w325cp) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/scene_graph/bouncing_ball_plant.h#L27)):*
> ```objc
> output_ports:
> - y0
> - y1
> ```

btw -- i feel that all of these changes that document the default names mean that we should probably properly deprecate them when we assign proper names.
___
*[examples/van_der_pol/van_der_pol.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSh-Xz0qJ3iHLcYMUV:-MrSh-Xz0qJ3iHLcYMUW:bl57m4y) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/van_der_pol/van_der_pol.h#L30)):*
> ```objc
> /// @endsystem
> ///
> /// Ports `y0` and `y1` emit y₀ and y₁, respectively.
> ```

btw -- this seems unnecessary?

**Review by RussTedrake — COMMENTED** [review]
(with one possible correction required).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204#-:-MrShC0G-7HJFi0RtJgw:b-9hbchk)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSfOD7C5wD7X02hvBX:-MrSsTsMBqx_AIkjRoK3:bpm1jxq) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/kuka_iiwa_arm/kuka_torque_controller.h#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

These don't look right.  I see multiple `ExportInput` calls in the constructor?  And these are sort of begging to be named (since they have methods to access them by a name)
</blockquote></details>

I'll look again, at both current conditions and possible better names. If you like, please propose names, and I'll delay this until string name deprecation is merged.
___
*[examples/scene_graph/bouncing_ball_plant.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSg_b9EGcyDwSk5pdP:-MrSsevF0E6eYN11eKKY:bkac29i) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/scene_graph/bouncing_ball_plant.h#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i feel that all of these changes that document the default names mean that we should probably properly deprecate them when we assign proper names.
</blockquote></details>

Shall we delay until deprecation, and work on names? Feel free to propose some if good ones are not obvious.
___
*[examples/van_der_pol/van_der_pol.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSh-Xz0qJ3iHLcYMUV:-MrSsq1Z13_JCi3u59-k:bjkotkt) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/van_der_pol/van_der_pol.h#L30)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- this seems unnecessary?
</blockquote></details>

Probably right, but I did discover a typo in the .cc comment while trying to write it. Will remove.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri and @RussTedrake)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSfOD7C5wD7X02hvBX:-MrU5qIYAqyBr_yS5PkG:b8jm5ip) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/kuka_iiwa_arm/kuka_torque_controller.h#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll look again, at both current conditions and possible better names. If you like, please propose names, and I'll delay this until string name deprecation is merged.
</blockquote></details>

:facepalm:  got fooled by an internal LeafSystem -- fixing.

This is another diagram that would benefit from better names (and hence deprecation of old default names). I'll add it to the rename/deprecate list.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[examples/scene_graph/bouncing_ball_plant.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSg_b9EGcyDwSk5pdP:-MrUnu6L2ezskcxlg4CW:bgjs34v) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/scene_graph/bouncing_ball_plant.h#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Shall we delay until deprecation, and work on names? Feel free to propose some if good ones are not obvious.
</blockquote></details>

I don't think we need to wait.  I think this is still a step in the right direction.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri and @RussTedrake)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrSfOD7C5wD7X02hvBX:-MrY-3ZI4f2QmWfhJhKF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0cbfffb55d69e1c760022b1a7ae0146a45aa92d1/examples/kuka_iiwa_arm/kuka_torque_controller.h#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

:facepalm:  got fooled by an internal LeafSystem -- fixing.

This is another diagram that would benefit from better names (and hence deprecation of old default names). I'll add it to the rename/deprecate list.
</blockquote></details>

Done.
___
*[examples/kuka_iiwa_arm/kuka_torque_controller.cc, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY-9pj9ctge7lAUCLy:-MrY-9pj9ctge7lAUCLz:bad551y) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/kuka_torque_controller.cc#L137)):*
> ```cpp
>   // Connects the estimated state to the gravity compensator.
>   input_port_index_estimated_state_ = builder.ExportInput(
>       gravity_comp->get_input_port_estimated_state(), "estimated_state");
> ```

@russtedrake has claimed elsewhere (#16193) that this is a breaking change, even though status quo ante was a hex-spammy name.
___
*[examples/kuka_iiwa_arm/lcm_plan_interpolator.cc, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY7Zec7FnHY67Gbo-6:-MrY7ZedB5i7YRBbVs7N:bbi20b0) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/lcm_plan_interpolator.cc#L47)):*
> ```cpp
>   const auto& command_port = command_sender->get_output_port();
>   output_port_iiwa_command_ = builder.ExportOutput(
>       command_port, command_port.get_name());
> ```

Whoops, this one actually is a breaking change, at least for the output port. Here's a picture from master:



Here's a picture from `r3`:


I think the right move may actually be to name more of the internal systems. I'll look and propose something.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri and @RussTedrake)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.cc, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY-9pj9ctge7lAUCLy:-MrYBPwGAiAy_5iZNMVa:bfya0jc) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/kuka_torque_controller.cc#L137)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@russtedrake has claimed elsewhere (#16193) that this is a breaking change, even though status quo ante was a hex-spammy name.
</blockquote></details>

Drive-by opinion FWIW: Names that contained random hex addresses before do not need to be deprecated when replaced with civilized names. No one could be depending on the previous names since they are unpredictable. And if they were somehow depending on the _format_ of the name ... sympathy is in order, but not deprecation.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[examples/kuka_iiwa_arm/lcm_plan_interpolator.cc, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY7Zec7FnHY67Gbo-6:-MrYE25h3qhELea_qyyE:b-hu69cn) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/lcm_plan_interpolator.cc#L47)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Whoops, this one actually is a breaking change, at least for the output port. Here's a picture from master:



Here's a picture from `r3`:


I think the right move may actually be to name more of the internal systems. I'll look and propose something.
</blockquote></details>

Here's the picture for `r4`.


Feel free to quibble with the input names, if you like.

This change now also incurs the breaking change claim raised by @russtedrake in #16193.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @RussTedrake)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.cc, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY-9pj9ctge7lAUCLy:-MrYPkeZEIdJ1SkpPPWn:b-pmcxun) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/kuka_torque_controller.cc#L137)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Drive-by opinion FWIW: Names that contained random hex addresses before do not need to be deprecated when replaced with civilized names. No one could be depending on the previous names since they are unpredictable. And if they were somehow depending on the _format_ of the name ... sympathy is in order, but not deprecation.
</blockquote></details>

I'm coming around to @sherm1's thinking on this, but I'm just one voice. Perhaps @jwnimmer-tri will address this in the deprecations policy for #16159.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[examples/kuka_iiwa_arm/kuka_torque_controller.cc, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY-9pj9ctge7lAUCLy:-MrYoGEg6Hsvesc2isFb:b-65o1xs) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/kuka_torque_controller.cc#L137)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm coming around to @sherm1's thinking on this, but I'm just one voice. Perhaps @jwnimmer-tri will address this in the deprecations policy for #16159.
</blockquote></details>

I would completely agree that for default names that were previously memory address garbage, no deprecation is required.
___
*[examples/kuka_iiwa_arm/lcm_plan_interpolator.cc, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrY7Zec7FnHY67Gbo-6:-MrYo_TCEvVj4w7oXJH7:bb5i1uz) ([raw file](https://github.com/robotlocomotion/drake/blob/74d2c58a9eec45551007eadba60ccce979a8d661/examples/kuka_iiwa_arm/lcm_plan_interpolator.cc#L47)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's the picture for `r4`.


Feel free to quibble with the input names, if you like.

This change now also incurs the breaking change claim raised by @russtedrake in #16193.
</blockquote></details>

aok for me.  i think this directory is on it's way out, so don't spend too much time on it!

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for feature review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204#-:-MrYyLbd0SQiTeFyc5Oy:bkmndnw)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 12 of 16 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri)

___
*[examples/planar_gripper/planar_manipuland_lcm.h, line 76 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrZ1WF_DwlBVgR1YA43:-MrZ1WF_DwlBVgR1YA44:bls7ko) ([raw file](https://github.com/robotlocomotion/drake/blob/8306d78f137406a2b9c3016d21050fe41f77eed9/examples/planar_gripper/planar_manipuland_lcm.h#L76)):*
> ```objc
>  * - u0
>  * output_ports:
>  * - y0
> ```

I think the output port should be called something like `manipuland_state` to match the decoder version above?  (It's the same LCM type as the decoder input port)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[examples/planar_gripper/planar_manipuland_lcm.h, line 76 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16204#-MrZ1WF_DwlBVgR1YA43:-MrZNy1MC4QTnHGBTJux:br5vfrg) ([raw file](https://github.com/robotlocomotion/drake/blob/8306d78f137406a2b9c3016d21050fe41f77eed9/examples/planar_gripper/planar_manipuland_lcm.h#L76)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think the output port should be called something like `manipuland_state` to match the decoder version above?  (It's the same LCM type as the decoder input port)
</blockquote></details>

I don't disagree. However, at this point we've agreed to document existing conditions, and maybe do naming improvements later based on the resolution of port name deprecation discussions. The only exception I've made to that is replacing Diagram hex-spam names with stable/readable names.

What is here matches what's in the .cc file.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16204#-:-MrZQG7w6RZM9a8_FpL8:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

**Pull request merged**
