### PR TITLE
quiets sign errors on mac.

### PR DESCRIPTION
**Pull request by RussTedrake**
per https://google.github.io/styleguide/cppguide.html#Integer_Types , we should only use int.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4603)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@amcastro-tri for feature review.  anybody listening for platform.  :)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4603#-:-KZnPvH45v8wmf5q_NKN:be0zsyv)*

**Comment by sherm1** [comment]
+@sherm1 for feature and platform: :lgtm: pending CI completion. -@amcastro-tri as a Xmas special.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4603#-:-KZnUXuKyPKfYsOh3mPL:b-60xiw6)*

**Comment by jwnimmer-tri** [comment]
For implicit integer type conversion across a return statement or assignment, I would prefer disabling the mac warning instead of adding more casting syntax.  (For the compare-signed-and-unsigned, I think fixing them is fine.)

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4603#-:-KZxRPvBpGgQFwdmsmd_:bnfp4nl)*

**Pull request merged**
