### PR TITLE
Initial guess variables initialized to NaN and utilized in Gurobi Solver

### PR DESCRIPTION
**Pull request by gizatt**
I switched the initialization of `x_initial_guess_` to `NaN` so it was clear which entries contained real guesses, and which entries contained no valid guess. I've also included the code to hand these variables off to Gurobi to chew on, and a small test checking that does a [relatively shallow] check of this functionality.

I've been using this in some of my mixed integer perception work, and it's been pretty useful! 

@hongkai-dai, probably of interest to you.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5605)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KfwqQp0ivJfH_FiXcrG:-KfwqQp0ivJfH_FiXcrH:bfmb2n2) ([raw file](https://github.com/robotlocomotion/drake/blob/d0289b9dab9646f1df4567c8ed19669f7af5f8bb/drake/solvers/test/gurobi_solver_test.cc#L85)):*
> ```cpp
>     EXPECT_EQ(result, SolutionResult::kSolutionFound);
>     const auto& x_value = prog.GetSolution(x);
>     EXPECT_TRUE(CompareMatrices(x_value, x_expected, 1E-6,
> ```

If you remove the `SetInitialGuess`, will the test also pass? If so, this function does not really test `SetInitialGuess`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-KfwqbHr0ucO6FUEjlGg:bl5ccwd)*

**Comment by gizatt** [comment]
Thanks!

If you know, could you explain the current build server fail? It looks like just warnings to me.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KfwqQp0ivJfH_FiXcrG:-KfwsHSxDS-S1D996dSK:b-ggskr0) ([raw file](https://github.com/robotlocomotion/drake/blob/d0289b9dab9646f1df4567c8ed19669f7af5f8bb/drake/solvers/test/gurobi_solver_test.cc#L85)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If you remove the `SetInitialGuess`, will the test also pass? If so, this function does not really test `SetInitialGuess`.
</blockquote></details>

Agreed -- the only  form of test I can think of to fit that requirement would be to test a problem complicated enough that setting the initial guess causes a significant speedup. I was a little scared to add something intentionally long-running but can try it if you think it's important to have this feature exhaustively tested in that way. (Are there any existing testing utilities that spawn "hard"  MI optimization problems I can borrow from?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-KfwsGUdfwIQPyh-CbQa:bybeft5)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-KfwuOogQDOuFWxWMdJ9:b1l9vrf)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KfwqQp0ivJfH_FiXcrG:-KfwucoLCMUkUBHF5eJk:b-x23izh) ([raw file](https://github.com/robotlocomotion/drake/blob/d0289b9dab9646f1df4567c8ed19669f7af5f8bb/drake/solvers/test/gurobi_solver_test.cc#L85)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Agreed -- the only  form of test I can think of to fit that requirement would be to test a problem complicated enough that setting the initial guess causes a significant speedup. I was a little scared to add something intentionally long-running but can try it if you think it's important to have this feature exhaustively tested in that way. (Are there any existing testing utilities that spawn "hard"  MI optimization problems I can borrow from?)
</blockquote></details>

The test I can think of is for a convex optimization problem without a cost. You can set the initial guess to be some interior point `x_0` inside the feasible set. The solution should be exactly that initial guess. On the other hand, if we do not set the initial guess, since the solution usually lies on the boundary of the feasible set, I think it is unlikely that the solution will be equal to `x_0`. So we can guarantee that setting the initial guess makes a difference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by gizatt** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KfwqQp0ivJfH_FiXcrG:-Kg00kAsgqCIzvHomiA_:brglmow) ([raw file](https://github.com/robotlocomotion/drake/blob/d0289b9dab9646f1df4567c8ed19669f7af5f8bb/drake/solvers/test/gurobi_solver_test.cc#L85)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The test I can think of is for a convex optimization problem without a cost. You can set the initial guess to be some interior point `x_0` inside the feasible set. The solution should be exactly that initial guess. On the other hand, if we do not set the initial guess, since the solution usually lies on the boundary of the feasible set, I think it is unlikely that the solution will be equal to `x_0`. So we can guarantee that setting the initial guess makes a difference.
</blockquote></details>

Good idea! I'm most interested in making sure this works for MIP, so I implemented a variation of this for a costless, unconstrained single-binary-variable case. That test is in here now. (I needed to massage gurobi a little bit to get it to pay attention to an initial guess for such a simple problem at all.)

I tried your tactic directly, and it doesn't work out of the box -- it looks like gurobi is outright ignoring the initial guess for the single continuous variable. I'd believe it if the initial guess was only relevant to the MIP solving bnb steps... but I haven't investigated this much further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by gizatt** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please!

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-Kg0R_V4gbIjf3JYHl4o:b-69uchh)*

**Comment by hongkai-dai** [comment]
Almost :lgtm:, could you check if the `mosek_solver.cc` also handles the initial guess?

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0PtADUOoZPtRUOKRN:-Kg0PtADUOoZPtRUOKRO:b-eo2ozz) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L576)):*
> ```cpp
>   }
> 
>   for (int i = 0; i < prog.initial_guess().rows(); i++) {
> ```

use `prog.num_vars()` instead of `prog.initial_guess().rows()`?

---

*[drake/solvers/gurobi_solver.cc, line 577 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0RaoR_aNZEgH2vmug:-Kg0RaoR_aNZEgH2vmuh:bp9x7hw) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L577)):*
> ```cpp
> 
>   for (int i = 0; i < prog.initial_guess().rows(); i++) {
>     if (!std::isnan(prog.initial_guess()(i))) {
> ```

Out of curiosity, what if `prog.initial_guess()(i)` is infinity? Can the solver still handle that? This may be outside of the scope of this PR, so feel free to leave it as a TODO here.

---

*[drake/solvers/mathematical_program.h, line 2388 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0SLp1eOI8_dd-bYI4:-Kg0SLp1eOI8_dd-bYI5:bxzbw5s) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/mathematical_program.h#L2388)):*
> ```objc
>     x_initial_guess_.conservativeResize(num_vars_);
>     x_initial_guess_.tail(num_new_vars).fill(
>       std::numeric_limits<double>::quiet_NaN());
> ```

Some documentation would be needed for `MathematicalProgram::SetInitialGuess()`, that if `SetInitialGuess` is not called, then the initial value is default to NaN. Also it would be great if you could say it in the documentation for `NewContinuousVariables` and `NewBinaryVariable`, that the default value of these newly added variables are NaN.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KfwqQp0ivJfH_FiXcrG:-Kg0UQd7ukFN_xB48NRe:b-4v3hbb) ([raw file](https://github.com/robotlocomotion/drake/blob/d0289b9dab9646f1df4567c8ed19669f7af5f8bb/drake/solvers/test/gurobi_solver_test.cc#L85)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Good idea! I'm most interested in making sure this works for MIP, so I implemented a variation of this for a costless, unconstrained single-binary-variable case. That test is in here now. (I needed to massage gurobi a little bit to get it to pay attention to an initial guess for such a simple problem at all.)

I tried your tactic directly, and it doesn't work out of the box -- it looks like gurobi is outright ignoring the initial guess for the single continuous variable. I'd believe it if the initial guess was only relevant to the MIP solving bnb steps... but I haven't investigated this much further.
</blockquote></details>

Ah, very smart! I did not realize `gurobi` would ignore my initial guess, great that you make it working for the binary variable.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0T85DJ4802EugtIwY:-Kg0T85EmmbOr6XG22Qk:be3hlxl) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/test/gurobi_solver_test.cc#L89)):*
> ```cpp
>     prog.SetSolverOption(SolverType::kGurobi, "Heuristics", 0.0);
> 
>     double x_expected_to_test[] = {0.0, 1.0};
> ```

Better to rename this variable as `x_expected0_to_test`, since you only modify `x_expected[0]`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-Kg0UlSJeMKU9xypaW1q:bjryxoh)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ggould-tri for platform review.

---

Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0PtADUOoZPtRUOKRN:-Kg0u1-a1NgrBm9y_beI:b-ydk1wl) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

use `prog.num_vars()` instead of `prog.initial_guess().rows()`?
</blockquote></details>

Thanks for changing this, but I think drake style guide prefers to use `int` rather than `size_t`, so maybe you can change it to
```C++
for (int i = 0; i < static_cast<int>(prog.num_vars()); ++i)
```
https://google.github.io/styleguide/cppguide.html#Integer_Types

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-Kg0ukGu2GOohF0BeFYM:b-u268)*

**Comment by gizatt** [comment]
It does not, currently -- I wasn't planning on addressing that but we ought to open an issue for it.

---

Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0PtADUOoZPtRUOKRN:-Kg0pLqPpiU61qCVt6SZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

use `prog.num_vars()` instead of `prog.initial_guess().rows()`?
</blockquote></details>

Done.

---

*[drake/solvers/gurobi_solver.cc, line 577 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0RaoR_aNZEgH2vmug:-Kg0sk-UgKaT5r5PcpG0:b-swzpbs) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L577)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Out of curiosity, what if `prog.initial_guess()(i)` is infinity? Can the solver still handle that? This may be outside of the scope of this PR, so feel free to leave it as a TODO here.
</blockquote></details>

Just tried it -- it looks like it doesn't bother gurobi as a binary variable guess (it claims to have used it to load a reasonable MIP start... maybe it's rounding it down to "1" for the binary variable)?

Can note as a TODO, though it might be an issue for each solver to handle in its own way. Got a spot for that in mind?

---

*[drake/solvers/mathematical_program.h, line 2388 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0SLp1eOI8_dd-bYI4:-Kg0sgMXmZkR5uE8LUcM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/mathematical_program.h#L2388)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Some documentation would be needed for `MathematicalProgram::SetInitialGuess()`, that if `SetInitialGuess` is not called, then the initial value is default to NaN. Also it would be great if you could say it in the documentation for `NewContinuousVariables` and `NewBinaryVariable`, that the default value of these newly added variables are NaN.
</blockquote></details>

Done.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0T85DJ4802EugtIwY:-Kg0pg05DfK4tXaGL-zD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/test/gurobi_solver_test.cc#L89)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Better to rename this variable as `x_expected0_to_test`, since you only modify `x_expected[0]`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-Kg0pARPuPHEwXNOS_zI:b-6py5p9)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 577 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0RaoR_aNZEgH2vmug:-Kg0vN8lBC7ESep_PgGX:b12425r) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L577)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Just tried it -- it looks like it doesn't bother gurobi as a binary variable guess (it claims to have used it to load a reasonable MIP start... maybe it's rounding it down to "1" for the binary variable)?

Can note as a TODO, though it might be an issue for each solver to handle in its own way. Got a spot for that in mind?
</blockquote></details>

Good to know. If it is not a binary variable, but a continuous variable, is Gurobi still happy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by gizatt** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0PtADUOoZPtRUOKRN:-Kg0vY-VUxo-moko1zwE:b-ql9mcn) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, asychronous commenting, size_t's are switched back.

---

*[drake/solvers/gurobi_solver.cc, line 577 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0RaoR_aNZEgH2vmug:-Kg0whhOx-Xp_gV1OZnW:b-xf2ez1) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L577)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good to know. If it is not a binary variable, but a continuous variable, is Gurobi still happy?
</blockquote></details>

Looks like supply inf as a continuous var guess doesn't break it either. It's hard to distinguish these two as they result in the same solution, but I think the inf guesses are being either totally ignored as guesses, or treated as guesses of `0`, as they result in the same output as if I supplied guesses of 0. 

Code I've been using is a modification of the test I'm adding:
```GTEST_TEST(GurobiTest, TestInitialGuess) {
  GurobiSolver solver;
  if (solver.available()) {
    // Formulate a simple problem with multiple optimal
    // solutions, and solve it twice with two different
    // initial conditions. The resulting solutions should
    // match the initial conditions supplied. Doing two
    // solves from different initial positions ensures the
    // test doesn't pass by chance.
    MathematicalProgram prog;
    auto x = prog.NewBinaryVariables<1>("x");
    auto y = prog.NewContinuousVariables<1>("y");
    // Presolve and Heuristics would each independently solve
    // this problem inside of the Gurobi solver, but without
    // consulting the initial guess.
    prog.SetSolverOption(SolverType::kGurobi, "Presolve", 0);
    prog.SetSolverOption(SolverType::kGurobi, "Heuristics", 0.0);
    prog.SetSolverOption(SolverType::kGurobi, "OutputFlag", 1);
    prog.SetSolverOption(SolverType::kGurobi, "LogToConsole", 1);
    prog.SetSolverOption(SolverType::kGurobi, "DisplayInterval", 5);

    std::vector<double> x_expected0_to_test = {
        0.0,
        1.0,
        std::numeric_limits<double>::infinity()
      };
    for (const auto item_to_test : x_expected0_to_test) {
      Eigen::VectorXd x_expected(1);
      x_expected[0] = item_to_test;
      prog.SetInitialGuess(x, x_expected);
      prog.SetInitialGuess(y, x_expected);
      SolutionResult result = solver.Solve(prog);
      EXPECT_EQ(result, SolutionResult::kSolutionFound);
      const auto& x_value = prog.GetSolution(x);
      EXPECT_TRUE(CompareMatrices(x_value, x_expected, 1E-6,
                                  MatrixCompareType::absolute));
      std::cout << "x: " << prog.GetSolution(x) << ", y: " << prog.GetSolution(y) << std::endl;
    }
  }
}```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 577 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-Kg0RaoR_aNZEgH2vmug:-Kg1-kbgJQi21gKHgJjP:bkx6rx1) ([raw file](https://github.com/robotlocomotion/drake/blob/18acc7da8c565f1946347cf1d99399b976ffe8e4/drake/solvers/gurobi_solver.cc#L577)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Looks like supply inf as a continuous var guess doesn't break it either. It's hard to distinguish these two as they result in the same solution, but I think the inf guesses are being either totally ignored as guesses, or treated as guesses of `0`, as they result in the same output as if I supplied guesses of 0. 

Code I've been using is a modification of the test I'm adding:
```GTEST_TEST(GurobiTest, TestInitialGuess) {
  GurobiSolver solver;
  if (solver.available()) {
    // Formulate a simple problem with multiple optimal
    // solutions, and solve it twice with two different
    // initial conditions. The resulting solutions should
    // match the initial conditions supplied. Doing two
    // solves from different initial positions ensures the
    // test doesn't pass by chance.
    MathematicalProgram prog;
    auto x = prog.NewBinaryVariables<1>("x");
    auto y = prog.NewContinuousVariables<1>("y");
    // Presolve and Heuristics would each independently solve
    // this problem inside of the Gurobi solver, but without
    // consulting the initial guess.
    prog.SetSolverOption(SolverType::kGurobi, "Presolve", 0);
    prog.SetSolverOption(SolverType::kGurobi, "Heuristics", 0.0);
    prog.SetSolverOption(SolverType::kGurobi, "OutputFlag", 1);
    prog.SetSolverOption(SolverType::kGurobi, "LogToConsole", 1);
    prog.SetSolverOption(SolverType::kGurobi, "DisplayInterval", 5);

    std::vector<double> x_expected0_to_test = {
        0.0,
        1.0,
        std::numeric_limits<double>::infinity()
      };
    for (const auto item_to_test : x_expected0_to_test) {
      Eigen::VectorXd x_expected(1);
      x_expected[0] = item_to_test;
      prog.SetInitialGuess(x, x_expected);
      prog.SetInitialGuess(y, x_expected);
      SolutionResult result = solver.Solve(prog);
      EXPECT_EQ(result, SolutionResult::kSolutionFound);
      const auto& x_value = prog.GetSolution(x);
      EXPECT_TRUE(CompareMatrices(x_value, x_expected, 1E-6,
                                  MatrixCompareType::absolute));
      std::cout << "x: " << prog.GetSolution(x) << ", y: " << prog.GetSolution(y) << std::endl;
    }
  }
}```
</blockquote></details>

Awesome! Thanks a lot for doing this test!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*
<!-- Sent from Reviewable.io -->

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Comment by gizatt** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-Kg1MK_ZY2LpnfMGhn6j:b-69uchh)*

**Comment by ggould-tri** [comment]
+(status: curate commits before merging) 
:lgtm:

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 80 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KgEqlSAjKnnruqVvN03:-KgEqlSAjKnnruqVvN04:b-nxd620) ([raw file](https://github.com/robotlocomotion/drake/blob/4833dfeacaa9e9d53c88c7afd309de8d89684ad6/drake/solvers/test/gurobi_solver_test.cc#L80)):*
> ```cpp
>     // match the initial conditions supplied. Doing two
>     // solves from different initial positions ensures the
>     // test doesn't pass by chance.
> ```

This is an excellent test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-:-KgEnt4sTCLthrTs2Pkd:b-kmrex5)*

**Comment by gizatt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 80 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5605#-KgEqlSAjKnnruqVvN03:-KgGBfx6iJSOE_VZUaXi:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/4833dfeacaa9e9d53c88c7afd309de8d89684ad6/drake/solvers/test/gurobi_solver_test.cc#L80)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is an excellent test.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5605)*

**Pull request merged**
