### PR TITLE
Remove some matlab/util mex code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is to minimize dependencies from MATLAB onto Drake's C++ libraries as well as other externals, in order to make the build system swap as simple as practical.

Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6430)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Just testing in CI for now.

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.

(Do not merge until I've assigned additional review.)

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6430#-:-Knb2FvWkdfHIPZKJBPo:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review please, per on-call rotation (tomorrow).

**Comment by sammy-tri** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/baseParameters.m, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6430#-Knf2KRa5I2i6GuS-sdC:-Knf2KRbMsVZ50qiv8Su:bhaeikf) ([raw file](https://github.com/robotlocomotion/drake/blob/acd5b7a4d6ee901511211fe2b8e9599da26c3ca3/drake/matlab/util/baseParameters.m#L61)):*
> ```objc
>   W_data = reshape(W_data,m,r*r_orig)'; % [m x r*r_orig]
>   [beta, independent_idx] = baseParameters(W_data);
> else
> ```

Should this last `else` statement actually stay in the file?  It looks like we're only deleting `TrigPoly` but this change would also nerf `msspoly`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6430)*

**Comment by jwnimmer-tri** [comment]
Review status: 31 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/baseParameters.m, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6430#-Knf2KRa5I2i6GuS-sdC:-KnfFqX0kwnVAF3eVn_J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/acd5b7a4d6ee901511211fe2b8e9599da26c3ca3/drake/matlab/util/baseParameters.m#L61)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this last `else` statement actually stay in the file?  It looks like we're only deleting `TrigPoly` but this change would also nerf `msspoly`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6430)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6430#-:-KnfIudted4FzJpovFjK:bnfp4nl)*

**Pull request merged**
