### PR TITLE
Implements DerivativeTrajectory.

### LINKED ISSUE #20982: Allow `TrajectorySource` with `output_derivative_order` > 0 without requiring `MakeDerivative`
**Is your feature request related to a problem? Please describe.**
The current implementation of `TrajectorySource` requires the trajectory to implement `MakeDerivative` (see [here](https://github.com/RobotLocomotion/drake/blob/master/systems/primitives/trajectory_source.cc#L30)). However, there are cases when it is more natural/ easier to provide `DoEvalDerivative` only. An example is `PathParameterizedTrajectory`. I had a similar situation with one of my custom trajectories, where providing `DoMakeDerivative` added unnecessary overhead while `DoEvalDerivative` was `O(1)` anyways.

**Describe the solution you'd like**
Allow `TrajectorySource` with `output_derivative_order` > 0 without requiring `MakeDerivative`. In particular, it should support `PathParameterizedTrajectory`.

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20982.

+@nepfaff for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036)

### CODE REVIEW

**Review by nepfaff — COMMENTED** [review]
Looks great. Thanks for implementing this! 

Based on [Jeremy's comment](https://github.com/RobotLocomotion/drake/issues/20982#issuecomment-1953434784), the python [trajectory subclassing test](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/test/trajectories_test.py#L51) is wrong in that it returns true for `do_has_derivative` while not providing an implementation for `DoMakeDerivative`. This is not a problem for the test, but some people might use it as an example for their own code. Should we change/ fix this as part of this PR? We could also use `DerivativeTrajectory` to provide a default implementation for `DoMakeDerivative` if `DoEvalDerivative` is implemented.

:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-:-NrQcaYr7fDPFaXYcSze:b-e1fbg6)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/derivative_trajectory.cc` line 62 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrQaOTPDW5-pL8VZVEh:-NrQaOTPDW5-pL8VZVEi:b-ijp5pp) ([raw file](https://github.com/RobotLocomotion/drake/blob/f668cd2d4b403162f12b3dba197904f4f3683d66/common/trajectories/derivative_trajectory.cc#L62)):*
> ```cpp
>     int derivative_order) const {
>   return std::make_unique<DerivativeTrajectory<T>>(
>       *nominal_, derivative_order_ + derivative_order);
> ```

nit: Inconsistency in that `DoEvalDerivative` adds `derivative_order` and `derivative_order_` in the opposite ordering as `DoMakeDerivative`. Using `derivative_order_` + `derivative_order` seems slightly nicer in that we are adding the new order on top of the existing one.

**Review by nepfaff — COMMENTED** [review]
We could also use `DerivativeTrajectory` to provide a default implementation for `DoMakeDerivative` if `DoEvalDerivative` is implemented.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-:-NrQePJa8QX-P65-OlLu:b-ph36pq)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
ok, i've fixed the CustomTrajectory class in the test, too.

+@jwnimmer-tri -- are you willing to do a weekend platform review, since you proposed this solution?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-:-NrR91Oy8cJUveM-CBod:b-ee229u)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`common/trajectories/derivative_trajectory.cc` line 62 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrQaOTPDW5-pL8VZVEh:-NrR7OKp9xHIlNpktyD9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f668cd2d4b403162f12b3dba197904f4f3683d66/common/trajectories/derivative_trajectory.cc#L62)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

nit: Inconsistency in that `DoEvalDerivative` adds `derivative_order` and `derivative_order_` in the opposite ordering as `DoMakeDerivative`. Using `derivative_order_` + `derivative_order` seems slightly nicer in that we are adding the new order on top of the existing one.
</blockquote></details>

Done.

**Review by nepfaff — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-:-NrRfUmD-3ukqC0cUzHm:bnfp4nl)* status: 7 unresolved discussions

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRaAv86WLcIbPi-S6Q):*
nit Having both notes labels "feature" and "fix" but no commit body will probably stymie the notes author.

I assume the reason for "fix" is the path parameterized trajectory portion, in which case the commit body here should communicate that detail.  I suppose the citation to 20982 might be enough for them to discover the idea, but I think it's worth being more explicit with a little sentence here.
___
*[`common/trajectories/derivative_trajectory.h` line 4 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRd1986uXB0ooTK6cP:-NrRd199AcLoADBRetZu:b-xc2n41) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.h#L4)):*
> ```objc
> 
> #include <memory>
> #include <vector>
> ```

nit Unused `<vector>`
___
*[`common/trajectories/derivative_trajectory.h` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRdCj03arVYBjbN1A5:-NrRdCj16Dei_QLSqZJE:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.h#L23)):*
> ```objc
> efficient to use `DoEvalDerivative` even in repeated evaluations of the
> derivative. The %DerivativeTrajectory class helps with this case -- given a
> `nominal` Trajectotry, it provides a Trajectory interface that calls
> ```

typo



_Suggestion:_
```objc
Trajectory
```
___
*[`common/trajectories/derivative_trajectory.h` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRdKPE69kJQ96rxcNU:-NrRdKPF2_KW9PkDQMcy:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.h#L33)):*
> ```objc
> 
>   /** Creates a DerivativeTrajectory representing the `derivative_order`
>   derivatives of `nominal_traj`.
> ```

typo



_Suggestion:_
```objc
`nominal`
```
___
*[`common/trajectories/derivative_trajectory.h` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRdQwz-wrsL8A9DlSm:-NrRdQwz-wrsL8A9DlSn:b-rrp1e9) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.h#L36)):*
> ```objc
> 
>   @throws std::exception if `!nominal.has_derivative()`. */
>   explicit DerivativeTrajectory(const Trajectory<T>& nominal,
> ```

BTW For C++ veterans its going to be obvious, possibly for newbies or Python folks it would be worth to add a sentence to the API docs saying that we copy `nominal`, not alias it.  Any subsequent mutations to to `nominal` will not affect this object.
___
*[`common/trajectories/derivative_trajectory.cc` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRe5zoAo0o5QWvYhnp:-NrRe5zp5siiZ4C-Txgs:b-1ti4ku) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.cc#L14)):*
> ```cpp
>   // of this new object. (See PiecewiseQuaternion, for example, whose nominal
>   // value has 4 rows, but whose derivative has only 3).
>   MatrixX<T> v = nominal.EvalDerivative(nominal.start_time(), derivative_order);
> ```

nit The order argument to `nominal.EvalDerivative` is required to be non-negative per its API doc.  We need to guard something like `DRAKE_THROW_UNLESS(derivative_order_ >= 0);` before we make this call.

(In the alternative, another way to align all of the code would be to change the contract of the base class `Trajectory::EvalDerivative` to not have any pre-condition, and instead to promise as a post-condition to throw when the order is negative.  Then the NVI in the Trajectory base class would perform that check, and we don't necessarily need to change this code here at all, although we could still imagine providing a more focused error message here anyway.)
___
*[`common/trajectories/test/derivative_trajectory_test.cc` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRf44G6XDJ07A_r2IB:-NrRf44G6XDJ07A_r2IC:bvdmibs) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/test/derivative_trajectory_test.cc#L32)):*
> ```cpp
>     EXPECT_EQ(dut.rows(), nominal.rows());
>     EXPECT_EQ(dut.cols(), nominal.cols());
>     EXPECT_TRUE(nominal.has_derivative());
> ```

nit I guess this isn't _wrong_ per se, but it makes me wonder if you meant to check `dut.has_derivative()` instead, and this is a typo?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),nepfaff

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRaAv86WLcIbPi-S6Q):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Having both notes labels "feature" and "fix" but no commit body will probably stymie the notes author.

I assume the reason for "fix" is the path parameterized trajectory portion, in which case the commit body here should communicate that detail.  I suppose the citation to 20982 might be enough for them to discover the idea, but I think it's worth being more explicit with a little sentence here.
</blockquote></details>

Done.  I removed the "fix".  I think the additional feature is the important aspect for the release notes.  I've added a bit more detail to the commit message, too. 
___
*[`common/trajectories/derivative_trajectory.h` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRdQwz-wrsL8A9DlSm:-NrRuIDtBNblBB3F09N4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.h#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For C++ veterans its going to be obvious, possibly for newbies or Python folks it would be worth to add a sentence to the API docs saying that we copy `nominal`, not alias it.  Any subsequent mutations to to `nominal` will not affect this object.
</blockquote></details>

Done.
___
*[`common/trajectories/derivative_trajectory.cc` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21036#-NrRe5zoAo0o5QWvYhnp:-NrS895Q0byOfMBJ3dC7:b-l8zsdj) ([raw file](https://github.com/RobotLocomotion/drake/blob/798481f0383cd8f3ab8e3982a4a3b01c14e55860/common/trajectories/derivative_trajectory.cc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The order argument to `nominal.EvalDerivative` is required to be non-negative per its API doc.  We need to guard something like `DRAKE_THROW_UNLESS(derivative_order_ >= 0);` before we make this call.

(In the alternative, another way to align all of the code would be to change the contract of the base class `Trajectory::EvalDerivative` to not have any pre-condition, and instead to promise as a post-condition to throw when the order is negative.  Then the NVI in the Trajectory base class would perform that check, and we don't necessarily need to change this code here at all, although we could still imagine providing a more focused error message here anyway.)
</blockquote></details>

Done. I went ahead and made the change upstream.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21036)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),nepfaff

**Pull request merged**
