### PR TITLE
Renames "compliant" models to "continuous" models and "time stepping" models to "discretized" models.

### PR DESCRIPTION
**Pull request by edrumwri**
This change is necessary to eliminate confusion: the time stepping approach also supports compliant contact.

This PR also removes the no-longer-necessary TimeSteppingRigidBodyPlant from the multibody/dev branch.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8551)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@rcory for feature review please

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9fRHbo7OOpyXW2IXJL:bx4gwfw)*

**Comment by sherm1** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by rcory** [comment]
:lgtm: with some minor comments.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qIXcg2qXgqiyHs66D:-L9qIXcg2qXgqiyHs66E:b-ojmgt9) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/contact_model/sliding_bricks.cc#L53)):*
> ```cpp
> DEFINE_bool(playback, true,
>             "If true, enters looping playback after sim finished");
> DEFINE_string(simulation_type, "continuous", "The type of simulation to use: "
> ```

BTW, perhaps rename this gflag to `system_type` instead (based on our discussion earlier)?

---

*[examples/rod2d/rod2d.h, line 172 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qd8If7TFayQ6Pi_uo:-L9qd8If7TFayQ6Pi_up:b3bb67g) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d.h#L172)):*
> ```objc
>     /// and ordinary differential equations.
>     kContinuous
>   };
> ```

BTW, it would be great to document the types of contact simulation supported. According to the options above we support, (PieceWiseDAE, rigid), (Discretized, rigid), and (Continuous, compliant). Are there others, e.g., (Discretized, compliant)?

---

*[examples/rod2d/rod2d-inl.h, line 1056 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qfJ0f1Vq5h6glrV0H:-L9qfJ0f1Vq5h6glrV0I:bojh7dm) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d-inl.h#L1056)):*
> ```objc
>     return std::make_unique<systems::AbstractValues>();
>   } else {
>     // Discretized and compliant approaches need no abstract variables.
> ```

BTW, do you mean "Discretized and **continuous** approaches..."?

---

*[examples/rod2d/rod2d_sim.cc, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qfh73Ail1amBMip3z:-L9qfh73Ail1amBMip4-:bjvzcf3) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d_sim.cc#L42)):*
> ```cpp
> 
> // Simulation parameters.
> DEFINE_string(simulation_type, "discretized",
> ```

BTW, perhaps this this gflag should be `system_type` (instead of `simulation_type`)?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9qs_-pCgI9vAO1djKa:brciwku)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qIXcg2qXgqiyHs66D:-L9v4AX66utH9BZvnrpP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/contact_model/sliding_bricks.cc#L53)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW, perhaps rename this gflag to `system_type` instead (based on our discussion earlier)?
</blockquote></details>

Done.

---

*[examples/rod2d/rod2d.h, line 172 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qd8If7TFayQ6Pi_uo:-L9v677r7vJQWcl2rV3X:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d.h#L172)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW, it would be great to document the types of contact simulation supported. According to the options above we support, (PieceWiseDAE, rigid), (Discretized, rigid), and (Continuous, compliant). Are there others, e.g., (Discretized, compliant)?
</blockquote></details>

PTAL.

---

*[examples/rod2d/rod2d-inl.h, line 1056 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qfJ0f1Vq5h6glrV0H:-L9v6NJ32cWVbSgIFg65:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d-inl.h#L1056)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW, do you mean "Discretized and **continuous** approaches..."?
</blockquote></details>

Done.

---

*[examples/rod2d/rod2d_sim.cc, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qfh73Ail1amBMip3z:-L9v7yOl4gjVtVg9GCqh:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/rod2d/rod2d_sim.cc#L42)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW, perhaps this this gflag should be `system_type` (instead of `simulation_type`)?
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by edrumwri** [comment]
+@soonho-tri for platform review please

---

Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9v8phkCwBRh-zmm_M6:b-10xzum)*

**Comment by soonho-tri** [comment]
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vCpRAEq5OR3_Y2qp1:-L9vCpRAEq5OR3_Y2qp2:b-8men6y) (no related file):*
FYI, CI is unhappy:
```
ERROR: /home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-cache/src/multibody/constraint/BUILD.bazel:37:1: Couldn't build file multibody/constraint/_objs/constraint_solver_test/multibody/constraint/test/constraint_solver_test.pic.o: C++ compilation of rule '//multibody/constraint:constraint_solver_test' failed (Exit 1)
multibody/constraint/test/constraint_solver_test.cc:27:24: error: no member named 'SimulationType' in 'drake::examples::rod2d::Rod2D<double>'
        Rod2D<double>::SimulationType::kPiecewiseDAE, 0);
        ~~~~~~~~~~~~~~~^
1 error generated.
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by soonho-tri** [comment]
Checkpoint. All the changes look good to me, but I am afraid that we need more changes to be consistent.

---

Reviewed 3 of 11 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qIXcg2qXgqiyHs66D:-L9vT4fB4oKFbc_KACG6:befdqtp) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/contact_model/sliding_bricks.cc#L53)):*
> "The type of simulation to use: "

It sounds like the description part needs to be updated as well, such as `The type of system model and approach for simulating the system:`?

---

*[examples/rod2d/rod2d.h, line 185 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vTcZeDe5nwbhyj2fw:-L9vTcZeDe5nwbhyj2fx:b-hfifs8) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/rod2d.h#L185)):*
> ```objc
>   ///         kDiscretized or @p dt is not zero and simulation_type is
>   ///         kPiecewiseDAE or kContinuous.
>   explicit Rod2D(SystemType simulation_type, double dt);
> ```

BTW, META, `simulation_type` => `system_type`.

---

*[examples/rod2d/rod2d.h, line 389 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vTiYzA6qOeZXS2HZm:-L9vTiYzA6qOeZXS2HZn:bs8blya) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/rod2d.h#L389)):*
> ```objc
> 
>   /// Gets the model and simulation type for this system.
>   SystemType get_simulation_type() const { return system_type_; }
> ```

BTW, `get_simulation_type` => `get_system_type`?

---

*[examples/rod2d/test/rod2d_test.cc, line 874 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vSqSR-uZWQHj3fjm9:-L9vSqSR-uZWQHj3fjmA:bxe0skf) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/test/rod2d_test.cc#L874)):*
> ```cpp
>   context_pdae->FixInputPort(0, std::move(ext_input));
> 
>   // Init the simulator for the time stepping system.
> ```

BTW,  => `discretized system`?

---

*[examples/rod2d/test/rod2d_test.cc, line 1143 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vRSFK9sW0AWU0WcL6:-L9vRSFK9sW0AWU0WcL7:b-ecb7kq) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/test/rod2d_test.cc#L1143)):*
> one time stepping,

I guess this comment needs to be updated?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9vUYM11wN8fPOptAwN:bwcced1)*

**Comment by edrumwri** [comment]
I did some better grepping here and think I properly identified all of the relevant cases to change.

---

Review status: 9 of 16 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9vYiAl0SbBXhSJW4ky:b-ul5fpz)*

**Comment by edrumwri** [comment]
Review status: 9 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9qIXcg2qXgqiyHs66D:-L9vlv5z6yCsSSFDgyiM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b93642adfc1b7c85effc96c282d858f666d1a04/examples/contact_model/sliding_bricks.cc#L53)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> "The type of simulation to use: "

It sounds like the description part needs to be updated as well, such as `The type of system model and approach for simulating the system:`?
</blockquote></details>

Done.

---

*[examples/rod2d/rod2d.h, line 185 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vTcZeDe5nwbhyj2fw:-L9vm-V9CRtOW35_Ahnt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/rod2d.h#L185)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, META, `simulation_type` => `system_type`.
</blockquote></details>

Done.

---

*[examples/rod2d/rod2d.h, line 389 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vTiYzA6qOeZXS2HZm:-L9vm2wzD7B14iKVUe2G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/rod2d.h#L389)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `get_simulation_type` => `get_system_type`?
</blockquote></details>

Done.

---

*[examples/rod2d/test/rod2d_test.cc, line 874 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vSqSR-uZWQHj3fjm9:-L9vmDPW3-Fl8cxS8gFM:bj5avwx) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/test/rod2d_test.cc#L874)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW,  => `discretized system`?
</blockquote></details>

PTAL- I'm trying to keep the word "time stepping" in use for this test so that I don't have to change names from "_ts" to "_discretized".

---

*[examples/rod2d/test/rod2d_test.cc, line 1143 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9vRSFK9sW0AWU0WcL6:-L9vmSGX7LyDYVgAC2Uy:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/bed27c849013e038a7c0869bdf0a82d9e9645636/examples/rod2d/test/rod2d_test.cc#L1143)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> one time stepping,

I guess this comment needs to be updated?
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by soonho-tri** [comment]
:lgtm: 

@rcory , could you check the recent changes?

---

Reviewed 6 of 7 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9w-vSO1L204_uPuTIm:-L9w-vSO1L204_uPuTIn:by0u7pn) ([raw file](https://github.com/robotlocomotion/drake/blob/7a08752ad7e7693d41504ef91e19c27c79f8b212/examples/contact_model/sliding_bricks.cc#L53)):*
> ```cpp
> DEFINE_bool(playback, true,
>             "If true, enters looping playback after sim finished");
> DEFINE_string(system_type, "continuous", "The type of system model to use "
> ```

BTW, we have `"The type of system to use: "` in other files.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-L9w-nGkCLox-UQy2Xl9:b-96af80)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/contact_model/sliding_bricks.cc, line 53 at r5](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-L9w-vSO1L204_uPuTIm:-L9w4du64q9ol7T351cD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a08752ad7e7693d41504ef91e19c27c79f8b212/examples/contact_model/sliding_bricks.cc#L53)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, we have `"The type of system to use: "` in other files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551)*

**Comment by rcory** [comment]
:lgtm:

---

Reviewed 6 of 11 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 6 of 7 files at r4, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8551#-:-LA--QNI0BiDmulEKOxu:bnfp4nl)*

**Pull request merged**
