### PR TITLE
Add names to systems in drake/automotive.

### PR DESCRIPTION
**Pull request by david-german-tri**
@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5836)

### CODE REVIEW

**Comment by liangfok** [comment]
Review pass complete. Just one comment.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-KhhyTs7ZNktVQ1T3Y1t:-KhhyTs7ZNktVQ1T3Y1u:b-b6bn0h) ([raw file](https://github.com/robotlocomotion/drake/blob/25ec615e8e52c10cbcadbdabe7c858c804aa4deb/drake/automotive/automotive_simulator.h#L212)):*
> ```objc
>   // Takes ownership of the given @p system.
>   // @pre Start() has NOT been called.
>   void AddSystem(std::unique_ptr<systems::System<T>> system);
> ```

This should be removed as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-:-KhhygmXrMutF0AmrKr7:bra5ihy)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-KhhyTs7ZNktVQ1T3Y1t:-Khi3lWGeAkNbImgCpQd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25ec615e8e52c10cbcadbdabe7c858c804aa4deb/drake/automotive/automotive_simulator.h#L212)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This should be removed as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836)*

**Comment by david-german-tri** [comment]
+@soonho-tri for platform review.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-:-Khi3wg0w0W9SuufyoUP:bxw8cpy)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-:-Khi5ZcFTq-VNLNzhMji:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a question)

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 269 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-KhlNAayi-arkis_ff6I:-KhlNAayi-arkis_ff6J:b-utj209) ([raw file](https://github.com/robotlocomotion/drake/blob/d06b0bbdcbc59ee665b37e6a987561a6de9cddcc/drake/automotive/automotive_simulator.cc#L269)):*
> ```cpp
>   const std::string channel =
>       std::to_string(vehicle_number) + "_MALIPUT_RAILCAR_STATE";
>   auto publisher =  builder_->template AddSystem<LcmPublisherSystem>(
> ```

BTW, just want to check if you want to call `set_name` for those `publisher` objects (this one and the followings).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-:-KhlNdl-MK9hAAjScX9Z:b-fs3k2l)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/automotive/automotive_simulator.cc, line 269 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5836#-KhlNAayi-arkis_ff6I:-KhlPdy24cFV7zMcdYBm:b6ibrqc) ([raw file](https://github.com/robotlocomotion/drake/blob/d06b0bbdcbc59ee665b37e6a987561a6de9cddcc/drake/automotive/automotive_simulator.cc#L269)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, just want to check if you want to call `set_name` for those `publisher` objects (this one and the followings).
</blockquote></details>

Never mind. I just checked that LcmPublisherSystem code has the following in it:
```c++
  set_name(make_name(channel_));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5836)*

**Pull request merged**
