### PR TITLE
setup/ubuntu: Install `libtbb2`

### LINKED ISSUE #8964: drake_visualizer import error: no module named vtkRenderingOSPRayPython
## Description

Hi, I am new to drake and am trying to run the kuka_iiwa example here: https://github.com/RobotLocomotion/drake/tree/master/examples/kuka_iiwa_arm.
I build drake using bazel then follow the instructions in the example. However, when I try to launch drake_visualizer, there is an 

> Traceback (most recent call last):
  File "\<string>\", line 1, in \<module>\
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/drakevisualizerapp.py", line 3, in \<module>\
    from director import mainwindowapp
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/mainwindowapp.py", line 2, in \<module>\
    from director.componentgraph import ComponentFactory
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/componentgraph.py", line 2, in \<module>\
    from director.fieldcontainer import FieldContainer
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/fieldcontainer.py", line 1, in \<module>\
    import vtk
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/execroot/drake/bazel-out/k8-opt/bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib/python2.7/site-packages/vtk/__init__.py", line 97, in \<module>\
    from .vtkRenderingOSPRay import *
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/execroot/drake/bazel-out/k8-opt/bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib/python2.7/site-packages/vtk/vtkRenderingOSPRay.py", line 9, in \<module>\
    from vtkRenderingOSPRayPython import *
ImportError: No module named vtkRenderingOSPRayPython

It seems that a vtkRenderingOSPRayPython.py is missing? I found a vtkRenderingOSPRayPython.so in that path.

And it seem that the pre-compiled package has the same problem. 

## Reproduction

I build the drake_visualizer with
> cd drake
> bazel build //tools:drake_visualizer

And I build the python bindings

then set PYTHONPATH using 
> cd drake-build
> export PYTHONPATH=${PWD}/install/lib/python2.7/site-packages:${PYTHONPATH}

then run the drake_visualizer with
> cd drake
> bazel-bin/tools/drake_visualizer

## Debug Information

* What operating system are you running Drake on?
(e.g. Ubuntu 16.04, macOS 10.13)

    > Ubuntu 16.04

* Is this an issue with (a) C++, (b) Python, or (c) the distributed tools
(e.g. `drake-visualizer`)?

    > drake-visualizer

* Are you (a) building `drake` from source, or (b) from a binary release?

    > I am building drake from source.

* What version of `python` are you using?

    > Python 2.7.12

my PYTHONPATH

    > '/home/shawn/open-source/drake-build/install/lib/python2.7/site-packages', '/home/shawn/open-   source/drake', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0'

* If you are building from source or using the `drake` C++ library as an
external:

    * What version of Bazel and CMake are you using?

        > bazel 0.12.0
        >cmake 3.5.1

    * If you are using Bazel, please provide the host settings in your present
    project workspace:

        > clang version 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1)
        >Target: x86_64-pc-linux-gnu
        >Thread model: posix
        >InstalledDir: /usr/bin

* If you are building `drake`
[from source](http://drake.mit.edu/from_source.html):

    * What git commit of `drake` are you using?

        > a1c5fde

    * Are you building `drake` with Bazel or CMake?

        > Bazel

    * Are you using `drake` directly, or consuming it as an external?

        > directly, through python binding?

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8964

(Assuming `libtbb2` was the only missing dependency.)

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFYYRci2hm1DJSZsmOA:b-mchllo)*

**Comment by jamiesnape** [comment]
`libtbb2` on both platforms.

---

Reviewed 2 of 2 files at r1.
Review status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFYcald5lhdGYIyecTp:b1ofgms)*

**Comment by EricCousineau-TRI** [comment]
D'oh! Done.

---

Review status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFdDHjR6yEakM6HkF4S:b1rg8a4)*

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for platform review, please.

---

Review status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFdDSzXD9ijQIcMspEG:bppyoqq)*

**Comment by sherm1** [comment]
Platform :lgtm:. @jamiesnape I presume you feature reviewed this but there isn't an LGTM from you.

---

Reviewed 2 of 2 files at r2.
Review status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM from [sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFdJmn2CTSxlp1L-gpw:b-h8t2d5)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9042#-:-LFddhoWEAXwZ28tjN4p:bnfp4nl)*

**Pull request merged**
