### PR TITLE
Do not create and install many redundant pkg-config files

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3827)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Oh hey, we can do this?  That's great!  My #3253 PR will be much simpler without this stuff.

**Comment by jamiesnape** [comment]
Possibly. Drake does not need them, nor does Director. The one question mark is OpenHumanoids, though they appear to have forked Drake.

**Comment by wxmerkt** [comment]
We do require (at least - to the best of my knowledge):

- drake-ik
- drake-rbm
- drake-rigid-body-plant
- drake-qp-common

I do understand your interest in nuking pods.cmake bit by bit - is there a way to add a backwards-compatible version, e.g. a similar ``drake_add_pkg_config_file`` function?

**Comment by jamiesnape** [comment]
@wxmerkt We may as well keep `pods_add_pkg_config_file` if we really need `pkg-config` files, but it looks like your project uses CMake, so are they really essential?

**Comment by wxmerkt** [comment]
I do not have the full insight over every single CMakeLists - so yes, we could carry through ``target_link_libraries`` etc.  - the beauty of using the pkg-config at the present stage was that we could simply find the module and it would use include paths and linker flags and work - are there equivalent files yet to do ``find_package(drake REQUIRED drakeIK)`` for instance? Or would we need to manually do the include_directories etc.? Is there a maintenance issue with keeping the pkg config files around for now or is this a change for change/CMake-pureness sake?

**Comment by jamiesnape** [comment]
We can setup something like `find_package(drake REQUIRED COMPONENTS drakeIK)` and you just need a call similar to `target_link_libraries(<target> drakeIK)`. That would set everything that you need, including the include directories (`target_link_libraries` does much more than link libraries now). That is a work in progress, but we would not remove the pkg-config files that you need until that is in place.

**Comment by jamiesnape** [comment]
There is a maintenance issue and they are not currently tested at all. We would need to maintain and test two different paths to using drake.

**Comment by jamiesnape** [comment]
Closing until we have an alternative setup.

**Comment by wxmerkt** [comment]
Thanks for the update and clarification @jamiesnape - much appreciated

**Pull request closed without merging**
