### PR TITLE
bind linearize and linear systems inspection methods.  …

### PR DESCRIPTION
**Pull request by RussTedrake**
move primitives testing to its own file

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8110)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for both reviews, please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8110#-:-L5o-hzeAQcb9rck-iGL:borg022)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0UhgqlCT8wnYx0b1:-L5o0UhgqlCT8wnYx0b2:b-jjlljw) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L77)):*
> ```Python
>         self.assertEqual(system.time_period(), .1)
> 
>         linearized = pydrake.systems.primitives.Linearize(system)
> ```

BTW Can these be directly imported, similar to the other symbols above?

---

*[bindings/pydrake/systems/test/primitives_test.py, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o03Jz-YogT2xJRbsD:-L5o03K-kgpRmyeoZWSd:b-pa2yzm) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L89)):*
> ```Python
>         self.assertEqual(Ob.shape[0], 2)
>         self.assertEqual(Ob.shape[1], 2)
>         self.assertFalse(pydrake.systems.primitives.IsObservable(system))
> ```

This should have the following concluding clause:
```
if __name__ == '__main__':
    unittest.main()
```

Otherwise, I believe it will pass without running the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-:-L5o0JJbsvgMFeCPOGnG:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0x7MVia7RrktjUWO:-L5o0x7NZwTq-wh3XVk0:b-38s5w1) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L83)):*
> ```Python
> 
>         Co = pydrake.systems.primitives.ControllabilityMatrix(system)
>         self.assertEqual(Co.shape[0], 2)
> ```

BTW, you can compare tuples (and lists) directly:
```
self.assertEqual(Co.shape, (2, 2))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0UhgqlCT8wnYx0b1:-L5o3Q_ih58bWyP00LbL:bwhhxmj) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L77)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can these be directly imported, similar to the other symbols above?
</blockquote></details>

i feel that it would be strictly worse to do that?  no?  (less controlled scope)?  and as we start having many one-offs, this seems more appropriate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0UhgqlCT8wnYx0b1:-L5o3xO5R-H-MXcNFk-D:bqmq193) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L77)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i feel that it would be strictly worse to do that?  no?  (less controlled scope)?  and as we start having many one-offs, this seems more appropriate?
</blockquote></details>

In that case, could this be shortened to use `from pydrake.systems import primitives` (for readability), or even (`import pydrake.systems.primitives as mut` for module-under-test), and could all symbols be made consistent?

(One-off to me would make sense if it came from another module, but since it's the module the module under test, it'd be nice to have it all be consistent).

If you'd like, I can handle this in a follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by RussTedrake** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0UhgqlCT8wnYx0b1:-L5o93XDcG25CFQgmtHG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L77)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

In that case, could this be shortened to use `from pydrake.systems import primitives` (for readability), or even (`import pydrake.systems.primitives as mut` for module-under-test), and could all symbols be made consistent?

(One-off to me would make sense if it came from another module, but since it's the module the module under test, it'd be nice to have it all be consistent).

If you'd like, I can handle this in a follow-up PR.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o0x7MVia7RrktjUWO:-L5o944vEpyltAhCwvKS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L83)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW, you can compare tuples (and lists) directly:
```
self.assertEqual(Co.shape, (2, 2))
```

</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/primitives_test.py, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o03Jz-YogT2xJRbsD:-L5o94ax87hdt4EdQB7C:bhpxs43) ([raw file](https://github.com/robotlocomotion/drake/blob/c882761aa5939213e0b973c99f3d2c69b67c594e/bindings/pydrake/systems/test/primitives_test.py#L89)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

This should have the following concluding clause:
```
if __name__ == '__main__':
    unittest.main()
```

Otherwise, I believe it will pass without running the tests.
</blockquote></details>

Done.  And caught a few mistakes in the process.  :man_facepalming: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by RussTedrake** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/primitives_py.cc, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o9HjN11PZM0vmfDha:-L5o9HjN11PZM0vmfDhb:b-hxv3qu) ([raw file](https://github.com/robotlocomotion/drake/blob/d48d5147f4d8420251f9f524d8b7098509b51fbe/bindings/pydrake/systems/primitives_py.cc#L78)):*
> ```cpp
> 
>   m.def("Linearize", &Linearize, py::arg("system"), py::arg("context"),
>         py::arg("equilibrium_check_tolerance") = 1e-6);
> ```

BTW, wanted to pass in Eigen::Default, by that didn't get through.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by jwnimmer-tri** [comment]
FYI I have a WIP linter branch that abstracts / enforces the dunder-main unittest boilerplate, since I as well have forgotten to add it sometimes.  I'll try to get that PR'd in the next few weeks.

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/primitives_py.cc, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8110#-L5o9HjN11PZM0vmfDha:-L5oAAmpRjNaorGsDK39:b-6rti8s) ([raw file](https://github.com/robotlocomotion/drake/blob/d48d5147f4d8420251f9f524d8b7098509b51fbe/bindings/pydrake/systems/primitives_py.cc#L78)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, wanted to pass in Eigen::Default, by that didn't get through.
</blockquote></details>

OK Er, I'm not sure what you meant by this - which arguments are default in `Linearize`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by EricCousineau-TRI** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8110)*

**Pull request merged**
