### PR TITLE
Pile of misc clang-format-includes fixups

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Some commits are machine, some are manual.  Use the reviewable file matrix to tease them apart if need be.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5599)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+(priority: low) +@sammy-tri for all review, please, because this starts by reverting #5590 (sorry!).  I am somehow unable to reproduce the clang-format behavior that led to #5590 (yikes!).

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5599#-:-KfusaJUNXreLos1P-rO:b-ytnfhe)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 13 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 12 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5599#-:-KfvSBkOkvYhQUM9bLd7:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car:

**Pull request merged**
