### PR TITLE
Disable hidden visibility on OS X

### LINKED ISSUE #3250: Hidden Visibility, Implicit Instantiation, and the Mach-O Linker/Loader
As discussed on #3236 and #3247, when running with `-fvisibility=hidden`, the Mach-O linker will create non-external typeinfo symbols for implicit template instantiations in _every_ shared library where that particular instantiation occurs.  These typeinfo are not equal, so if you then pass a template object across dylib boundaries, `dynamic_cast` will spuriously fail.  

This is a time bomb that will lurk in your code unnoticed until you actually instantiate `Foo<T> : public Bar` in two different dylibs, and then try to `dynamic_cast` a `Bar` from one to a `Foo<T>` in the other.  When it goes off, it will be very hard to debug: `dynamic_cast` will silently return `nullptr`, on Mac only.

This article provides lots of helpful background, although it doesn't predict our exact issue: http://www.russellmcc.com/posts/2013-08-03-rtti.html

In Drake, we could work around this by taking care to explicitly instantiate, extern, and export all the template instantiations that would otherwise be implicit.  To comply with ODR, this export should be done in the library at the lowest level of physical layering that uses the template.  That is a lot of finicky bookkeeping: I expect people will get it wrong, and plant more time bombs, since there would be no real tooling to make you get it right.

Additionally, the workaround is awkward because GCC and MSVC do not agree on the appropriate syntax for both externing and exporting a symbol.  GCC wants the annotations on the extern declaration in the `.h` (`Wattributes`), whereas MSVC wants them on the explicit instantiation in the `.cc` (Warning `C4910`).  As Drake is currently configured, that's an error on GCC and merely a warning on MSVC, so for the short-term fix in #3247, GCC won.

Alternatively, we could decide that the Mach-O linker's interpretation of `-fvisibility=hidden` is so pedantic that we shouldn't even bother with it.  Hiding the typeinfo seems pretty extreme!  Under this proposal, we'd just drop the flag from the Mac build and delete the #3247 workarounds.

I know that both of those ideas have multiple opponents.  Other suggestions are welcome!

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fixes #3250. See also #3236 and #3247.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3259)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3259#-:-KQ1sSwCJefqYKSwpKu-:bnfp4nl)*

**Comment by david-german-tri** [comment]
thanks!  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3259#-:-KQ1wBlMO53Vh0a1SNAt:b-r70y3l)*

**Comment by jwnimmer-tri** [comment]
This probably needs an opt-in to post-merge apple builds before merging?

@david-german-tri should this PR also remove the extern work-around, or will you do that separately?

**Comment by jwnimmer-tri** [comment]
Oops, too late.  I guess `Continuous` will let us know.

**Comment by david-german-tri** [comment]
> @david-german-tri should this PR also remove the extern work-around, or will you do that separately?

I'll do that separately.

**Comment by mwoehlke-kitware** [comment]
> This probably needs an opt-in to post-merge apple builds before merging?

Ack... good point; sorry. OTOH I'd be fairly surprised if it breaks anything; after all, no hidden visibility was the status quo before #3065.

**Pull request merged**
