### PR TITLE
Make constraint bounds private data members

### LINKED ISSUE #3062: solvers::Constraint has protected data members
The lower_bound_ and upper_bound_ members are protected, and are accessed by derived classes directly.  This originally came up during https://github.com/robotlocomotion/drake/blob/94784a441628a7815772cb99214ba8475e603e2d/drake/systems/plants/inverseKinTrajBackend.cpp#L326

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #3062

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3120)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@hongkai-dai for feature review
+@jwnimmer-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-:-KOufwlTdnRnR-v-eosP:buadczj)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/inverseKinTrajBackend.cpp, line 325 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-KOugvDFbUWG4330Rabu:-KOugvDFbUWG4330Rabv:bk700pd) ([raw file](https://github.com/robotlocomotion/drake/blob/96438e0fbe05353d19046af128f62250de7b54cd/drake/systems/plants/inverseKinTrajBackend.cpp#L325)):*
> ```cpp
>     DRAKE_ASSERT(lb.size() == ub.size());
>     int prev_size = lower_bound().size();
>     Eigen::VectorXd new_lb(prev_size + lb.size());
> ```

I think we should add this `AppendBounds` function to `OptimizationProblem` class. Also we incur additional copy here by not using conservativeResize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-KOugcxZABQtk3JYs9_B:-KOugcxZABQtk3JYs9_C:b-7x5f3w) ([raw file](https://github.com/robotlocomotion/drake/blob/96438e0fbe05353d19046af128f62250de7b54cd/drake/solvers/constraint.h#L72)):*
> ```objc
>     lower_bound_ = lower_bound;
>     upper_bound_ = upper_bound;
>     DRAKE_ASSERT(lower_bound.size() == upper_bound.size());
> ```

BTW A bit odd to have the precondition check last, instead of first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-:-KOui7Z2q2-H43rrRMxb:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/inverseKinTrajBackend.cpp, line 325 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-KOugvDFbUWG4330Rabu:-KOuhlCyEMIsrO-hzgIY:b-8hyj4y) ([raw file](https://github.com/robotlocomotion/drake/blob/96438e0fbe05353d19046af128f62250de7b54cd/drake/systems/plants/inverseKinTrajBackend.cpp#L325)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I think we should add this `AppendBounds` function to `OptimizationProblem` class. Also we incur additional copy here by not using conservativeResize.
</details>
conservativeResize doesn't publish any guarantee that it doesn't copy the data (I'd be surprised if memory layout was usually such that it was possible to do the resize without a new allocation and a copy when growing the array...   though I've not looked into Eigen's allocator...)

Did you mean to move AppendBounds to Constraint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/inverseKinTrajBackend.cpp, line 325 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-KOugvDFbUWG4330Rabu:-KOukMGLDK1x6jNNMNlG:b-cybxst) ([raw file](https://github.com/robotlocomotion/drake/blob/96438e0fbe05353d19046af128f62250de7b54cd/drake/systems/plants/inverseKinTrajBackend.cpp#L325)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> conservativeResize doesn't publish any guarantee that it doesn't copy the data (I'd be surprised if memory layout was usually such that it was possible to do the resize without a new allocation and a copy when growing the array...   though I've not looked into Eigen's allocator...)
> 
> Did you mean to move AppendBounds to Constraint?
</details>
On a second thought, just adding `AppendBounds` to a constraint is error-prone, as the dimension of the bounds and the `eval` result should always change together. I am satisfied with `AppendBounds` being here now. I have implemented a function to `AppendConstraint` to a linear constraint, that grows the linear matrix `A` and its bounds together. I will include that function in my next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-:-KOul-6StIaB3RMdTg5M:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/constraint.h, line 72 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3120#-KOugcxZABQtk3JYs9_B:-KOulQ2MZps74imYLst6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b11f63ad306d1927eb421dd5d6a52028c7f704a1/drake/solvers/constraint.h#L72)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW A bit odd to have the precondition check last, instead of first.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3120)*

**Pull request merged**
