### PR TITLE
[workspace] Bump VGT to support hidden visibility

### PR DESCRIPTION
**Pull request by calderpg-tri**
Equivalent to #19893 for VGT, towards #17231

+@jwnimmer-tri for review, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20387)

### CODE REVIEW

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20387)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20387#-Nh-NVVM8JhI1TDwqhQ_:-Nh-NVVM8JhI1TDwqhQa:b-3rybiv) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cc4c159ece1638255c86ecbd3bfd379d0cd5f3b/tools/workspace/voxelized_geometry_tools/repository.bzl#L8)):*
> ```Starlark
>     github_archive(
>         name = name,
>         repository = "calderpg/voxelized_geometry_tools",
> ```

working Return to TRI mirror once VGT#49 lands

**Review by jwnimmer-tri — COMMENTED** [review]
Looks good.  Will await the final git sha pin before I emojiate here.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20387#-:-Nh-O3TJ2NZ35u8HaNoq:ba3co2s)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20387)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20387#-Nh-NVVM8JhI1TDwqhQ_:-Nh-PA-o1LL-mCvYc3BF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cc4c159ece1638255c86ecbd3bfd379d0cd5f3b/tools/workspace/voxelized_geometry_tools/repository.bzl#L8)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

working Return to TRI mirror once VGT#49 lands
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) +(release notes: fix) 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20387#-:-Nh-mnw5-lpaSa1IgExx:b-29nyiz)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
