### PR TITLE
[pydrake] Fold pydrake.solvers into a single module

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change allows for shorter module names during import.  (The old names continue to work, without warning.)

Examples of how users could change their import statements after this patch:

Old spelling:
```py
from pydrake.solvers.mathematicalprogram import MathematicalProgram
from pydrake.solvers.snopt import SnoptSolver
```

New spelling (option 1):
```python
from pydrake.solvers import MathematicalProgram
from pydrake.solvers import SnoptSolver
```

New spelling (option 2):
```python
from pydrake.solvers import MathematicalProgram, SnoptSolver
```

---

The shorter import path and consolidated API docs are more typical of Python modules than deeply-nested paths, and so are easier for users.

The single shared library also reduces the zipped size of our whl releases by approximately 7 MiB by reducing the zipped size of the `pydrake.solvers` directory by 78%. This is a very meaningful difference, given that we have a 100 MiB hard limit for our wheels.

Add shim modules so that the old, longer module names continue to work. Leave the unit tests for `pydrake.solvers` unchanged (using the old names) to confirm that the shim modules are operating correctly.

Update tutorials to prefer the new, shorter names. Update tests for other (non-solvers) modules to prefer the new, shorter names.

Also delete the `//bindings/pydrake/solvers:solvers_pybind` library target. This not a breaking change because it's not part of the Stable API.

Towards #11802.

Relates to #15631 and #15628.

See #17454 for the similar treatment of `pydrake.examples`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17453)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+(status: do not review) Let's review #17454 first to prove out the pattern, then we'll return here.

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai could I ask you for a feature review of the big-picture (user-visible) changes, please?  Reviewing the PR overview text and the edits to the `tutorials/**` notebooks should suffice.  The bottom line is a flattening of the `pydrake.solvers...` into a single imported module.

The build system pattern has already been proven out in #17454.  I think we can ask the platform reviewer to do the detailed pass over the build system edits.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 52 of 62 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17453#-:-N6n5lcb-D935y3zPhhx:bnfp4nl)* status: LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  I reviewed the commit message and the tutorials, I like the change.

Do you think it is worthwhile to mention some examples on changing the code after the PR, for example
```
Change from pydrake.solvers.mathematicalprogram import MathematicalProgram to from pydrake.solvers import MathematicalProgram
```
?  I imagine the downstream users might not immediately catch how to modify their python code after this PR, so it might be good to provide some guidelines.

> Reviewed 11 of 62 files at r1, 1 of 2 files at r2, 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17453#-:-N6n5ipg48dQd1NmZLII:bfb3jni)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Do you think it is worthwhile to mention some examples on changing the code after the PR ...

Good idea, I updated the PR overview to give some examples, and I'll see what I can do for release notes later on.

I'm waiting to make a wider announcement until _all_ of our modules have been cleaned up this same way (`pydrake.multibody.*`, `pydrake.systems.*`, so that users can update all of their imports at once instead of piecemeal.

**Pull request merged**
