### PR TITLE
Clean up CspaceFreePolytope.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Move some functions to CspaceFreePolytopeBase.

#19895 is too large, so I split that PR into two. This is the first PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-:-Naj8ePeDm75nuV5jV7-:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 428 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-ipsmA2RBbsNFMc_r:-Nb-ipsn8PB74ppbZz4C:bdi0tcj) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope.cc#L428)):*
> ```cpp
> 
>         DRAKE_THROW_UNLESS(rationals.size() == lagrangians_vec.size());
>         for (int i = 0; i < ssize(rationals); ++i) {
> ```

BTW: what is `ssize`?
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 304 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-jWPd7FHslXvZMycU:-Nb-jWPd7FHslXvZMycV:b-f43ghj) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope_base.h#L304)):*
> ```objc
> 
> namespace internal {
> // Return the total size of the lower triangular variables in the Gram
> ```

May be out of scope, but perhaps all of this should move to `cspace_free_internal.h`
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-jNjTBewD7wTR89nr:-Nb-jNjTBewD7wTR89ns:bfd7zts) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope_base.h#L360)):*
> ```objc
> // feasible set. This helps the next iteration of the bilinear alternation.
> // @note that `prog` will be mutated after this function call if it has a cost.
> solvers::MathematicalProgramResult SolveWithBackoff(
> ```

I would suggest putting this in `cspace_free_internal` as it needs to know nothing about `cspace_free_polytope_base`.
___
*[`multibody/rational/rational_forward_kinematics.h` line 173 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-kCu67_GM1HJTWhkX:-Nb-kCu67_GM1HJTWhkY:bx5nw5v) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/multibody/rational/rational_forward_kinematics.h#L173)):*
> ```objc
>    have (θ−θ*)/2 ≥ π/2 (or ≤ −π/2), we return ∞ (or −∞) for the corresponding s.
>    */
>   [[nodiscard]] Eigen::VectorXd ComputeSValueInfAbovePiOver2(
> ```

Should we just make this an optional argument in `ComputeSValue`? Perhaps add a bool such as `angles_wrap_to_infity`?
___
*[`multibody/rational/rational_forward_kinematics.cc` line 120 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-kdhjBChN8SNv3Y6T:-Nb-kdhjBChN8SNv3Y6U:brjv9ts) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/multibody/rational/rational_forward_kinematics.cc#L120)):*
> ```cpp
> }
> 
> Eigen::VectorXd RationalForwardKinematics::ComputeSValueInfAbovePiOver2(
> ```

This is very repeated code. I advocate either using the existing `ComputeSValue` or adding an optional argument to `ComptueSValue`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 428 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-ipsmA2RBbsNFMc_r:-Nb1yyPC7mivxiSTnuCL:b58l2o1) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope.cc#L428)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: what is `ssize`?
</blockquote></details>

`ssize` is the syntax sugar for `static_cast<int>(rationals.size())`
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 304 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-jWPd7FHslXvZMycU:-Nb1zjHMDzqySCYungFW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope_base.h#L304)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

May be out of scope, but perhaps all of this should move to `cspace_free_internal.h`
</blockquote></details>

Done.
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-jNjTBewD7wTR89nr:-Nb21kPx4v-fqRqTiYY6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/geometry/optimization/cspace_free_polytope_base.h#L360)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would suggest putting this in `cspace_free_internal` as it needs to know nothing about `cspace_free_polytope_base`.
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics.h` line 173 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-kCu67_GM1HJTWhkX:-Nb23g458RaEuUqm44sK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/multibody/rational/rational_forward_kinematics.h#L173)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Should we just make this an optional argument in `ComputeSValue`? Perhaps add a bool such as `angles_wrap_to_infity`?
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics.cc` line 120 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-Nb-kdhjBChN8SNv3Y6T:-Nb23git6xLbbuEugL2b:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72a2998c9fad45765c5c297c2428204b8635bccc/multibody/rational/rational_forward_kinematics.cc#L120)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is very repeated code. I advocate either using the existing `ComputeSValue` or adding an optional argument to `ComptueSValue`.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-:-NbCeQz9CUOP3qgo4x0z:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-:-NbD_Txk0irgj70FjXny:buer3go)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes

___
*[`geometry/optimization/cspace_free_internal.h` line 110 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbG-jh14jy16-xUC_V-:-NbG-jh14jy16-xUC_V0:b-xm2bj2) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.h#L110)):*
> ```objc
>     SeparationCertificateResultBase* result);
> 
> // Return the total size of the lower triangular variables in the Gram
> ```

Changes in this file was copy-moved from other files that were in Drake already.
___
*[`geometry/optimization/cspace_free_internal.cc` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbG0-BP2VFuubM5Ed0-:-NbG0-BP2VFuubM5Ed00:bsyugne) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.cc#L88)):*
> ```cpp
> }
> 
> // TODO(hongkai.dai): move this function to a header file for general usage.
> ```

`SymmetricMatrixFromLowerTriangularPart` and `AddPsdConstraint` are copy-moved from elesewhere.
___
*[`geometry/optimization/cspace_free_internal.cc` line 338 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbG07ygDMMfVWZcFbju:-NbG07ygDMMfVWZcFbjv:b9v3wvc) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.cc#L338)):*
> ```cpp
> }
> 
> int GetGramVarSize(
> ```

GetGramVarSize was copy-moved from elsewhere.
___
*[`geometry/optimization/cspace_free_internal.cc` line 371 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbG0FhY2nh5JxORUjdV:-NbG0FhY2nh5JxORUjdW:b-risgvc) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.cc#L371)):*
> ```cpp
> }
> 
> GramAndMonomialBasis::GramAndMonomialBasis(
> ```

Functions in GramAndMonomialBasis are copy-moved from elsewhere.
___
*[`geometry/optimization/cspace_free_internal.cc` line 444 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbG0KQC8QgM8LWJ-ETx:-NbG0KQC8QgM8LWJ-ETy:bhcfn4w) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.cc#L444)):*
> ```cpp
> }
> 
> solvers::MathematicalProgramResult SolveWithBackoff(
> ```

SolveWithBackoff was copy-moved from elsewhere.

**Review by sherm1 — COMMENTED** [review]
Thanks -- very helpful. Looks like +(release notes: none)  -- is that right? 
Platform :lgtm:

> Reviewed 3 of 10 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-:-NbGkgJQ9W4HlG7oMHr1:b8emcra)* status: 3 unresolved discussions

___
*[`geometry/optimization/cspace_free_internal.h` line 110 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbGKp9t6cSbwK-SBj3M:-NbGKp9t6cSbwK-SBj3N:b-7ikie) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.h#L110)):*
> ```objc
>     SeparationCertificateResultBase* result);
> 
> // Return the total size of the lower triangular variables in the Gram
> ```

nit: Return -> Returns
___
*[`geometry/optimization/cspace_free_internal.cc` line 106 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbGLIx_4LvzPygBcB4B:-NbGLIx_4LvzPygBcB4C:b70qglk) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/geometry/optimization/cspace_free_internal.cc#L106)):*
> ```cpp
> }
> 
> // TODO(hongkai.dai): move this change to MathematicalProgram.
> ```

BTW I don't understand the meaning of "this change" here -- can you clarify?
___
*[`multibody/rational/rational_forward_kinematics.h` line 111 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-NbGNVlU1UtkuG0ycR0A:-NbGNVlU1UtkuG0ycR0B:b-kbak3l) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd5c27133fa626791b2d7e9c9262bff3cced8415/multibody/rational/rational_forward_kinematics.h#L111)):*
> ```objc
>    q(i)).
>    @param angles_wrap_to_inf If set to True, then for a revolute joint whose (θ
>    −θ*) >=π/2 (or <= −π.2), we set the corresponding s to ∞ (or −∞), @default is
> ```

typo: π.2 -> π/2

**Review by hongkai-dai — COMMENTED** [review]
Yes, the release notes is none. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19900#-:-NbGw1Ng5ny78MAS47Jx:b-sknbvv)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),AlexandreAmice

**Pull request merged**
