### PR TITLE
Add tester/getter functions to symbolic::Formula class

### PR DESCRIPTION
**Pull request by soonho-tri**
- Add tester functions such as is_true, is_conjunction.
 - Add getter functions such as get_lhs_expression, get_quantified_formula.
 - Refactor existing code to use those tester/getter functions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4957)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@david-german-tri , could you review this PR please?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4957#-:-KbjNAyTtWir_whh9HWr:b-uny8b6)*

**Comment by david-german-tri** [comment]
:lgtm: Out of curiosity, does this have applications beyond the refactor?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4957#-:-Kblq9kftiUh7hvj1T8e:b-8xmhpy)*

**Comment by soonho-tri** [comment]
Thank you!

> does this have applications beyond the refactor?

Here it is (on my repo): https://github.com/soonho-tri/drake/blob/pr-use-formula-for-AddLinearConstraint/drake/solvers/mathematical_program.cc#L532-L551

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4957#-:-KblqibnuLIKurFM6K4S:bkw04j)*

**Comment by david-german-tri** [comment]
> Here it is (on my repo): https://github.com/soonho-tri/drake/blob/pr-use-formula-for-AddLinearConstraint/drake/solvers/mathematical_program.cc#L532-L551

Ooh, shiny!

**Pull request merged**
