### PR TITLE
More signed-unsigned fixes to keep Xcode happy

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4396)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
Please merge if no changes are needed.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4396#-:-KYLSnZ30awoDDXn9kR5:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
In the past I've written a version of EXPECT_EQ for unit testing that DTRT no matter what integral types you pass into it.  I wonder if I should do that again?  Decorating stuff like this in test code seems of low value.

**Comment by liangfok** [comment]
Yes!

**Pull request merged**
