### PR TITLE
Throw an error when Riccati equation is not solved for continuous time system.

### LINKED ISSUE #19191: Segmentation Fault in ContinuousAlgebraicRiccatiEquation
### What happened?

The following code produces a segmentation fault in `ContinuousAlgebraicRiccatiEquation`. I encountered this problem when trying to construct an LQR controller of a quadrotor, leashed to the origin by a spring. I think the problem has to do with the low rank of Q, since upping the number of nonzero diagonal entries past 3 leads to the system functioning fine.

```
import numpy as np
from pydrake.all import ContinuousAlgebraicRiccatiEquation

count = 3

A = np.array([
	[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[-12, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])
B = np.array([
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[0, 0, 0, 0],
	[1, 1, 1, 1],
	[7, -7, 7, -7],
	[-59, 0, 59, 0],
	[0, 99, 0, -99]
])
Q = np.diag([10] * count + [0] * (12 - count))
R = np.eye(4)

ContinuousAlgebraicRiccatiEquation(A, B, Q, R)
```

I've run the code through GDB, and it reports an error in `Eigen::SVDBase<Eigen::JacobiSVD`. I've included that log output below.

### Version

_No response_

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using CMake

### Relevant log output

```shell
(gdb) run test.py 
Starting program: /usr/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff45ff640 (LWP 68367)]
[New Thread 0x7ffff3dfe640 (LWP 68368)]
[New Thread 0x7fffeb5fd640 (LWP 68369)]
[New Thread 0x7fffe2dfc640 (LWP 68370)]
[New Thread 0x7fffda5fb640 (LWP 68371)]
[New Thread 0x7fffd9dfa640 (LWP 68372)]
[New Thread 0x7fffc15f9640 (LWP 68373)]
[New Thread 0x7fffc0df8640 (LWP 68374)]
[New Thread 0x7fffb85f7640 (LWP 68375)]
[New Thread 0x7fffafdf6640 (LWP 68376)]
[New Thread 0x7fff9f5f5640 (LWP 68377)]
[New Thread 0x7fff9edf4640 (LWP 68378)]
[New Thread 0x7fff965f3640 (LWP 68379)]
[New Thread 0x7fff8ddf2640 (LWP 68380)]
[New Thread 0x7fff855f1640 (LWP 68381)]
[New Thread 0x7fff7cdf0640 (LWP 68382)]
[New Thread 0x7fff6c5ef640 (LWP 68383)]
[New Thread 0x7fff63dee640 (LWP 68384)]
[New Thread 0x7fff5b5ed640 (LWP 68385)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff4f424e22 in void Eigen::SVDBase<Eigen::JacobiSVD<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 2> >::_solve_impl<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1>&) const () from /home/tommy/opt/rlg/drake-build/install/lib/python3.10/site-packages/pydrake/common/../../../../libdrake.so
```

### PR DESCRIPTION
**Pull request by hongkai-dai**
Riccati equation might not have a finite solution if the system is not stabilizable, or Q and R matrices are not positive definite.

Resolves #19191 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTL7qUv1aadbiNhUnvr:b-7vq6ss)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
@RussTedrake currently I check if the Hamiltonian is invertible. Ideally I want to compute the eigen value of Hamiltonian `H`, and check if half of its eigen values have negative real part, while the other half have positive real parts. But I don't know how stable is this computation, what do you think?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTLvMYF7o-LvI2iRtu_:b-4xm71t)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
I'm not the expert on numerical stability of that eigenvalue computation... maybe @sherm1 could weigh in?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTLyJoiDklkms96Vm1F:b-jqd1ut)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLwEMD3q48LAuuaM_g):*
nit: Riccat => Riccati
___
*[`math/continuous_algebraic_riccati_equation.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLwgNi23rzH00Gbq6K:-NTLwgNi23rzH00Gbq6L:b4ji3dk) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L25)):*
> ```cpp
> 
>   H << A, B * R_cholesky.solve(B.transpose()), Q, -A.transpose();
>   // The Hamiltonian H should have half of its eigen values with negative real
> ```

nit: eigen values => eigenvalues.
Here and 2 more times just below.
___
*[`math/continuous_algebraic_riccati_equation.cc` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLxwLr8MRewUctccxp:-NTLxwLr8MRewUctccxq:b-9km2bb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L27)):*
> ```cpp
>   // The Hamiltonian H should have half of its eigen values with negative real
>   // part, and half of its eigen values with positive real part, see
>   // https://stanford.edu/class/ee363/lectures/clqr.pdf for more discussion on
> ```

The hamiltonian in those notes has negatives on the off diagonal compared to your H above...?

And I didn't see anything about the positive/negative real parts of the eigenvalues in that pdf?
___
*[`math/continuous_algebraic_riccati_equation.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLwRmb5OqYGgUhp9yx:-NTLwRmb5OqYGgUhp9yy:b84wqi0) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L81)):*
> ```cpp
>         "ContinuousAlgebraicRiccatiEquation: svd is unsuccessful. Check your "
>         "input: is your (A, B) controllable? Is your Q matrix positive "
>         "semidefinite? Is your R matrix positive "
> ```

nit: unnecessary line break?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`math/continuous_algebraic_riccati_equation.cc` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLwgNi23rzH00Gbq6K:-NTMJE6j4a7ltod2Jlzw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L25)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: eigen values => eigenvalues.
Here and 2 more times just below.
</blockquote></details>

Done.
___
*[`math/continuous_algebraic_riccati_equation.cc` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLxwLr8MRewUctccxp:-NTMJGty8TGx9aw-cnLR:bco0xq8) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L27)):*
> The hamiltonian in those notes has negatives on the off diagonal compared to your H above...?

Good observation! But the sign of the off-diagonal terms doesn't matter. Here is a quick proof (following page 24 of that pdf file):

```
[I  0] * [A  BR⁻¹Bᵀ] * [I  0] = [A+BK  BR⁻¹Bᵀ]
[P  I]   [Q     -Aᵀ]   [-P I]   [0    (A+BK)ᵀ]
```
On the left hand side, since the matrix `[I 0; P I]` (on the left side of `H`) is the inverse of the matrix `[I 0; -P I]` (on the right hand side of `H`), the left-hand side of the equation is a similarity transform of `H`. This similarity transformed matrix has the same eigenvalues as `H`. On the right handside of the equation, the eigenvalues of this matrix is just the eigenvaues of (A+BK) and the eigenvalues of -(A+BK)ᵀ, which is the negation of λ(A+BK). Hence if we denote the eigenvalues of A+BK as λ₁,...,λₙ, the eigenvalues of `H` is just λ₁,...,λₙ and -λ₁,...,-λₙ. Because we know that LQR will stabilize the closed-loop system ẋ = (A+BK)x, hence the eigenvalues λ₁,...,λₙ should all have strictly negative real parts. As a result, half of the eigenvalues of H has negative real parts, while the other half has positive real parts.

> And I didn't see anything about the positive/negative real parts of the eigenvalues in that pdf?

It is mentioned in page 25 of the pdf
___
*[`math/continuous_algebraic_riccati_equation.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTLwRmb5OqYGgUhp9yx:-NTMM1U85M0nTlSp1Crp:byfykya) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e85a4c06c809d94c0b01db9f68172250dde75c4/math/continuous_algebraic_riccati_equation.cc#L81)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: unnecessary line break?
</blockquote></details>

I removed this error message. The svd should always be successful (unless there are nan in `lhs`, which has been ruled out by the check above)

**Review by hongkai-dai — COMMENTED** [review]
Thinking more deeply, I think we only need to rule out the case that the Hamiltonian `H` has some eigenvalue equal to 0, which means its determinant is 0. So I think the current check is sufficient, we don't need to compute the eigenvalues.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTMMSpu4o0Ucg1x4w3F:b-801lh8)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
> Thinking more deeply, I think we only need to rule out the case that the Hamiltonian H has some eigenvalue equal to 0, which means its determinant is 0. So I think the current check is sufficient, we don't need to compute the eigenvalues.

I take it back. We might still need to compute the eigenvalues and check if half of them are negative. I will think more carefully tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTNEIyiAHu7Z01Qxtx9:b-ggan1v)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
cc @cohnt 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTRP26gB5obmucr-9ZQ:bqcbeqr)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Comment by cohnt** [comment]
The more detailed comments in the code are much clearer about the requirements for the method to succeed. Do those automatically appear in the Doxygen documentation?

I'll note that the system from #19191 is stabilizable, so the comment for that test case should emphasize that this is expected to fail because it's not detectable, even though it is stabilizable.

It would be interesting to add another test case for a stabilizable linear system that is detectable but not observable, but I don't know any examples.

**Review by hongkai-dai — COMMENTED** [review]
@cohnt Thanks a lot!

I added new tests. One test an unstabilizable system. Another one test a stabilizable but uncontrollable system.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTVM0nM1PbS80Xfg6-7:brtti90)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Comment by cohnt** [comment]
@hongkai-dai I found a nice, easy example of a system which is stabilizable, detectable and unobservable, which you could add as a test case:

```
import numpy as np
from pydrake.all import ContinuousAlgebraicRiccatiEquation

A = np.array([[0, 1, 0], [0, 0, 1], [-1, -1, -1]])
B = np.array([[0], [0], [1]])
Q = np.array([[1, 1, 0], [1, 1, 0], [0, 0, 0]])
R = np.eye(1)

# Verifies that (A, B) is stabilizable
evals, evecs = np.linalg.eig(A)
for l in evals:
	if np.real(l) >= 0:
			mat = np.hstack((l*np.eye(A.shape[0])-A, B))
			print(np.linalg.matrix_rank(mat))

# Verifies that (A, Q) is unobservable
Gram = np.concatenate([Q @ np.linalg.matrix_power(A, i) for i in range(12)], axis=0)
print(np.linalg.matrix_rank(Gram))

# Verifies that (A, Q) is detectable
AT, QT = A.T, Q.T
evals, evecs = np.linalg.eig(AT)
for l in evals:
	if np.real(l) >= 0:
			mat = np.hstack((l*np.eye(AT.shape[0])-AT, QT))
			print(np.linalg.matrix_rank(mat))

ContinuousAlgebraicRiccatiEquation(A, B, Q, R) # Will succeed, as expected
```

**Review by hongkai-dai — COMMENTED** [review]
Excellent, thanks a lot for the example!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTVWBPZAsb2afm3kO3l:b-40edmr)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Nice.  Thanks for working all this out @cohnt and @hongkai-dai !  You guys are great!  
:lgtm: 
+@ggould-tri for platform review, please.

> Reviewed 2 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NThqyZk1B5Rk-35dFAh:bi4da6q)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri and @hongkai-dai)

___
*[`math/continuous_algebraic_riccati_equation.cc` line 27 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NThqMlz6OOF3eAhpsT6:-NThqMlz6OOF3eAhpsT7:b-votc8i) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/continuous_algebraic_riccati_equation.cc#L27)):*
> ```cpp
>   // For the closed-loop system ẋ = (A+BK)x (where K is the LQR controller
>   // gain), we denote the eigenvalues of A+BK as λ₁, ..., λₙ, then with Q
>   // satisfying the algebraic Riccati equation, the eigenvalues of H is λ₁, ...,
> ```

nit: "the eigenvalues of H is" => "then the eigenvalues of H are"
___
*[`math/continuous_algebraic_riccati_equation.cc` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NThqdiq1LScXwNbl1PY:-NThqdiq1LScXwNbl1PZ:bvyzs7m) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/continuous_algebraic_riccati_equation.cc#L30)):*
> ```cpp
>   // λₙ and -λ₁,
>   // ..., -λₙ (refer to https://stanford.edu/class/ee363/lectures/clqr.pdf for
>   // more details). Since LQR gain should stabilize the closed-loop system, we
> ```

nit: Since the LQR gains

**Comment by cohnt** [comment]
Also thank you to @sageshoyu for originally identifying the issue. Looking forward to seeing these fixes in drake master.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; mostly very minor rewording nits.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-:-NTnPIwh2pQnESTxd71K:b450r26)* status: 7 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`math/continuous_algebraic_riccati_equation.h` line 16 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnQGf5Ab9NaHMpKb7-:-NTnQGf5Ab9NaHMpKb70:byq54eg) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/continuous_algebraic_riccati_equation.h#L16)):*
> ```objc
> ///
> /// @note (A, B) should be stabilizable, (Q, A) should be detectable.
> /// @throws std::exception if R is not positive definite.
> ```

minor:  Should the (A, B) and (Q, A) requirements be in `@throws` instead?  I think this PR expands the set of circumstances where we throw beyond just requirements on R alone.



_Code quote:_
```objc
/// @note (A, B) should be stabilizable, (Q, A) should be detectable.
/// @throws std::exception if R is not positive definite.
```
___
*[`math/test/continuous_algebraic_riccati_equation_test.cc` line 67 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnP16U7YADDyJWXgaA:-NTnP16U7YADDyJWXgaB:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/test/continuous_algebraic_riccati_equation_test.cc#L67)):*
> ```cpp
> // https://github.com/RobotLocomotion/drake/issues/19191
> GTEST_TEST(CARE, TestUndetectable) {
>   // The pair (Q, A) is not detectable. Hence continuous algebraic riccati
> ```

typo



_Suggestion:_
```cpp
Hence the continuous algebraic Riccati
```
___
*[`math/test/continuous_algebraic_riccati_equation_test.cc` line 90 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnPlGL1KP-uR04krun:-NTnPlGL1KP-uR04kruo:b-ryncv3) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/test/continuous_algebraic_riccati_equation_test.cc#L90)):*
> ```cpp
>                               "ContinuousAlgebraicRiccatiEquation fails.*");
> 
>   // Test an example that (A, B) is stabilizable, (Q, A) is detectable but (Q,
> ```

typo awkward grammar



_Suggestion:_
```cpp
  // Test an example in which (A, B) is stabilizable and (Q, A) is detectable but (Q,
```
___
*[`math/test/continuous_algebraic_riccati_equation_test.cc` line 91 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnPZmG54ML-RvXke2C:-NTnPZmG54ML-RvXke2D:by7zxow) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/test/continuous_algebraic_riccati_equation_test.cc#L91)):*
> ```cpp
> 
>   // Test an example that (A, B) is stabilizable, (Q, A) is detectable but (Q,
>   // A) is not observable. The example is created by Thomas Cohn in
> ```

typo grammar



_Suggestion:_
```cpp
was
```
___
*[`math/test/continuous_algebraic_riccati_equation_test.cc` line 126 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnQ1xHDTxHXMuZy1RI:-NTnQ1xHDTxHXMuZy1RJ:b-ryncv3) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/test/continuous_algebraic_riccati_equation_test.cc#L126)):*
> ```cpp
> 
>   // The pair (A, B) is stabilizable (but not controllable), the Riccati
>   // solution should have a solution.
> ```

typo awkward grammar



_Suggestion:_
```cpp
  // The pair (A, B) is stabilizable (but not controllable), so the Riccati
  // equation should have a solution.
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222)* status: 1 unresolved discussion, missing label for release notes (waiting on @ggould-tri)

___
*[`math/continuous_algebraic_riccati_equation.h` line 16 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnQGf5Ab9NaHMpKb7-:-NToGOaeDX3JG0gCQ-ls:b-iizb00) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/continuous_algebraic_riccati_equation.h#L16)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Should the (A, B) and (Q, A) requirements be in `@throws` instead?  I think this PR expands the set of circumstances where we throw beyond just requirements on R alone.
</blockquote></details>

It is a little bit tricky here. Currently we throw when certain matrix is not invertible, which is a sufficient condition for (A, B) being not stabilizable, or (Q, A) being not detectable. This sufficient condition is quite technical, which I wouldn't expect the user to have that background and put it in the class documentation.

 So I am not sure if we should say we throw when (A, B) is not stabilizable or (Q, A) is not detectable. I think a `@note` here means that the users should be responsible for providing stabilizable (A, B) and detectable (Q, A). Do you think I should use `@pre` here instead of `@note`?

**Comment by cohnt** [comment]
> > Reviewed 2 of 2 files at r6, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222)_ status: missing label for release notes (waiting on @hongkai-dai)
> 
> _[`math/continuous_algebraic_riccati_equation.h` line 16 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19222#-NTnQGf5Ab9NaHMpKb7-:-NToZqIn4v7km3Sqn5GW:bokl704) ([raw file](https://github.com/RobotLocomotion/drake/blob/59789bbf9435bb85e13cfb785d8c7acf8f9c1ec9/math/continuous_algebraic_riccati_equation.h#L16)):_
> Previously, hongkai-dai (Hongkai Dai) wrote…
> 
> Ah, an interesting point. Doxygen does allow multiple `@throws` lines, so how about something like this:
> 
> ```
> @throws std::exception if R is not positive definite.
> @throws std::exception if the Hamiltonian matrix is not invertible.
> @note The Hamiltonian is guaranteed to be invertible if (A, B) is
>       stabilizable and (Q, A) is detectable; see
>       https://stanford.edu/class/ee363/lectures/clqr.pdf
> ```
> 
> I'm marking this review as 'satisfied' so you can put in whatever wording you think best.

I'm a fan of this wording as well. Although as a reference to those conditions, we should point to a resource such as this one: https://www.egr.msu.edu/classes/me851/mukherji/09-LQR.pdf

Alternatively, if you want a more official reference than these lecture slides I found on Google, you could refer to pages 526-527 of _Linear systems_, by Thomas Kailath.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19222)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
