### PR TITLE
Teach drake bazel rules to play nicely when drake is an external bazel project

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change would permit `drake` to be used as an external in a Bazel project, and would permit `drake`'s `tools/...` to be usable outside of `drake`.

This follows the workaround listed [here](https://github.com/bazelbuild/bazel/issues/2757#issuecomment-290448615).

* ~Move all non-rule externals to `@drake//tools:externals.bzl`~
* Replace `@//` with `@drake//`
* Replace `tools/*.BUILD` with `@drake//tools:*.BUILD`

Worked with @stonier to whip up an example project:
* [drake_external/](https://github.com/EricCousineau-TRI/drake_external#testing)
    * This consumes `@drake//drake/automotive:curve2` `@drake//drake/solvers:mathematical_program` externally

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6190)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@sherm1 for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4N35glFjJDkseBk7e:bdkf0gx)*

**Comment by jamiesnape** [comment]
Maybe in future for fundamental changes like this that are going to create a lot of conflicts, send out some advanced warning.

**Comment by jwnimmer-tri** [comment]
Can we trickle this in, maybe?  Just do the `@//` to `@drake//` in the BUILD file citations in a first PR?

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iIsxUNjfxJ-1pFCK:-Kl4iIsxUNjfxJ-1pFCL:bld78id) (no related file):*
Sorry, I should have opened a discussion thread:

Can we trickle this in, maybe? Just do the `@//` to `@drake//` rename in the BUILD file citations in a first PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4iJG6AOCU-OB4N-3C:byycx8c) (no related file):*
I'm also curious to know what external project we are targeting.  I am hesitant to try to support anything like this until and unless we add Drake CI support for a downstream project using us in this fashion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Sorry about that, this seemed like a relatively small change that would enable devs / external users to easily consume drake as an external in Bazel. If this inhibits / conflicts with someone else's PR in flight, we could always block this one until the others go in, and let that serve as the warning.
That being said, I would like to get this in, as it would make things a little simpler for prototyping work.

Are there any PRs in particular that you are concerned about? VTK and install script stuff?

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iIsxUNjfxJ-1pFCK:-Kl4kZKqgKj1HkuZ42Kf:bqchezw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry, I should have opened a discussion thread:

Can we trickle this in, maybe? Just do the `@//` to `@drake//` rename in the BUILD file citations in a first PR?
</blockquote></details>

Yup, shall do.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4k_Zgm4DIKWnbZtnT:bi0nskc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm also curious to know what external project we are targeting.  I am hesitant to try to support anything like this until and unless we add Drake CI support for a downstream project using us in this fashion.
</blockquote></details>

Right now, I am thinking of my own projects for one-off prototypes to inform design decisions.

Could we not use a  dummy external in CI to get this workflow started as soon as possible?
(It could also be used to test CMake / pkg-config / cps integration as well.)

And this is not critical to be in `master`, but if it were not to make it into `master` at this point, I would probably maintain my own `devel` branch and merge things into it so I could use this setup, as it is quite useful to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4jtg-Zmm1TPd2PoCt:b-i24q61)*

**Comment by sherm1** [comment]
Sorry, @ericcousineau-tri -- this is too far outside my area of expertise to be an effective platform reviewer for it.
-@sherm1

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4kr-MaJ2mjUQO8tY0:bdb93wx)*

**Comment by jwnimmer-tri** [comment]
I will wear the platform hat; just fine a second for feature review too, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4lbQcP7NBtCuly9LJ:bdevpjt)*

**Comment by EricCousineau-TRI** [comment]
@sherm1 @jwnimmer-tri sounds good!

+@jamiesnape for feature review, if you are available?
If this messes up any PRs in flight for VTK / install, could you just block on this PR?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4mgC07iL8vtY-9Ic1:bphaelk)*

**Comment by jamiesnape** [comment]
I am. No need to block if this makes your life easier.

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4lMDwPN9KGALlSqw-:b-d0041h)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4liDv4ATJ0R7u4g1F:b-gpdfar) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Right now, I am thinking of my own projects for one-off prototypes to inform design decisions.

Could we not use a  dummy external in CI to get this workflow started as soon as possible?
(It could also be used to test CMake / pkg-config / cps integration as well.)

And this is not critical to be in `master`, but if it were not to make it into `master` at this point, I would probably maintain my own `devel` branch and merge things into it so I could use this setup, as it is quite useful to me.
</blockquote></details>

I definitely agree this moves us toward a better long-term goal.  I am fine for a small dummy in CI to prove this works.  (I didn't mean to imply that Spartan or something big or difficult should go into our CI).

I would just ask to see the dummy stood up soonish, secured onto this PR train.  If it were prototyped such that I could test it locally outside of CI while reviewing the WORKSPACE part of the next PR, all the better.  It sound like you have a small downstream project working locally; getting (a cut-down version of that) into `RobotLocomotion` would be excellent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4npArP3D-rLOJIivn:b-3m435w) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I definitely agree this moves us toward a better long-term goal.  I am fine for a small dummy in CI to prove this works.  (I didn't mean to imply that Spartan or something big or difficult should go into our CI).

I would just ask to see the dummy stood up soonish, secured onto this PR train.  If it were prototyped such that I could test it locally outside of CI while reviewing the WORKSPACE part of the next PR, all the better.  It sound like you have a small downstream project working locally; getting (a cut-down version of that) into `RobotLocomotion` would be excellent.
</blockquote></details>

Awesome. I actually have a simple external based here:
https://github.com/EricCousineau-TRI/drake_external#testing

It has a minimal set of bash commands to clone the repository, and build what is needed.
It could be extended to use whatever the Bazel-only dependencies of `install` is, such that everything exposed externally is built.

Would that work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4p2NtflqKeAb0HyP7:b-ynr8jr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Awesome. I actually have a simple external based here:
https://github.com/EricCousineau-TRI/drake_external#testing

It has a minimal set of bash commands to clone the repository, and build what is needed.
It could be extended to use whatever the Bazel-only dependencies of `install` is, such that everything exposed externally is built.

Would that work?
</blockquote></details>

Using Matt's `//drake:install` dependency, getting some failures in the external. Will see if I can fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4oyL21C--Mks4m9UH:bktu5zg) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Using Matt's `//drake:install` dependency, getting some failures in the external. Will see if I can fix that.
</blockquote></details>

A `RobotLocomotion/drake-examples` repo that Jenkins just clones and then runs `bazel test ...` and `mkdir build && cmake .. && make && ctest .` would work for me. It would be easy to run on continuous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4nuYhhMYgDg7jB9zi:bnfp4nl)*

**Comment by stonier** [comment]
> That being said, I would like to get this in, as it would make things a little simpler for prototyping work.

Similar - I started doing this (i.e. a bazel workspace chained drake) just to write some simple drake experiments to understand the code and learn a bit of bazel free of all the drake noise. That's turned into unofficially starting work on a canonical set of simple *user* projects ([shambhala](https://github.com/stonier/shambhala)) that can be a template (and possibly a CI test later) for others.

This use case should be both the simplest, and a very standard use case. I think it's a good baseline requirement to help drive conventions for our bazel layout in way that helps users (and that requirement won't change). i.e. it's not a parallel support case and better now than a major refactor later.

Aside from the dependencies, be nice to also have access to some of the other bazel infra drake is building - e.g. github.bzl, bitbucket.bzl, install.bzl.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4lpsjXUFgsIUnXF4w:bmnjzy0)*

**Comment by jwnimmer-tri** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4pqpwGpFOytx2-fM-:bhkfjo6) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

A `RobotLocomotion/drake-examples` repo that Jenkins just clones and then runs `bazel test ...` and `mkdir build && cmake .. && make && ctest .` would work for me. It would be easy to run on continuous.
</blockquote></details>

Yes, it has to be an RL repository not personal repo.

We've talked about writing up canonical examples of how to integrate Drake into downstream projects.  I _think_ we should probably have one CMake example and one Bazel-only example, completely separate, and that this PR is towards the latter (Bazel-only).  So `RobotLocomotion/drake-example-bazel` maybe?

I don't think it needs to do `bazel run -- :install`; just having some sample C++ code that `deps` on Drake libraries should be good enough for now.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl4p_lz7aS8UxjjeLYX:b-m4siv0) (no related file):*
Please take a look at the bzl files in `./third_party/kythe/tools/build_rules/config`; I think a few of them also need a `@drake//` change.

---

*[tools/gtest.BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4nx69BsOf0G44iAcI:-Kl4nx69BsOf0G44iAcJ:bfkp7b6) ([raw file](https://github.com/robotlocomotion/drake/blob/9d16d995aa61b18a5d22e800201771634bb90a6d/tools/gtest.BUILD#L34)):*
> ```
>     linkopts = select({
>         "@drake//tools:linux": ["-pthread"],
>         "@//conditions:default": [],
> ```

_Meta_ Could you explain why the `@//conditions:default` doesn't turn into `@drake//conditions:default`?  (Same for spdlog.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
Looks cool. Just let me know if/when you want a Jenkins job setting up. Should be pretty easy.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4r1KsbAEdyGV7u7Hr:bqabby4)*

**Comment by stonier** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4iJG6AOCU-OB4N-3B:-Kl4qnhZWjgcfOO6wFWc:bnncrpp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, it has to be an RL repository not personal repo.

We've talked about writing up canonical examples of how to integrate Drake into downstream projects.  I _think_ we should probably have one CMake example and one Bazel-only example, completely separate, and that this PR is towards the latter (Bazel-only).  So `RobotLocomotion/drake-example-bazel` maybe?

I don't think it needs to do `bazel run -- :install`; just having some sample C++ code that `deps` on Drake libraries should be good enough for now.
</blockquote></details>

I wasn't intending to drop [shambhala](https://github.com/stonier/shambhala) into RobotLocomotion and CI just yet, but that was the goal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl4qpUZ2VzWZjEcBt8H:b-i2r1uk) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please take a look at the bzl files in `./third_party/kythe/tools/build_rules/config`; I think a few of them also need a `@drake//` change.
</blockquote></details>

Looking at that now - I feel a little dirty dropping `@drake//` in a third party, even if it is relatively small.
I will see if I can proxy `pkg_config_package` to explicitly specify `build_file_template` as `@drake//...`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl4sRaOSQ5MR6M6ECpw:bcgtduh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Looking at that now - I feel a little dirty dropping `@drake//` in a third party, even if it is relatively small.
I will see if I can proxy `pkg_config_package` to explicitly specify `build_file_template` as `@drake//...`.
</blockquote></details>

If you `git blame` those lines, IIRC you'll see I've already had to fork them to change their paths for Drake's use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl4sf_wJSeX8uXwpBrZ:b-xl733f) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you `git blame` those lines, IIRC you'll see I've already had to fork them to change their paths for Drake's use.
</blockquote></details>

Oh lol, well, then I'll add that in.

However, it seems that we can provide an upstream update to `kythe` in much the same way - make its paths robust against being used as an external.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
:lgtm: I've pulled and tested this locally with TRI-internal users of Drake, and all seems fine.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl4tONy99yrUZfAgEyH:b-iurf42) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Oh lol, well, then I'll add that in.

However, it seems that we can provide an upstream update to `kythe` in much the same way - make its paths robust against being used as an external.
</blockquote></details>

Fine by me.  I was like "meh" at the time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-Kl4t2bIPrVu_Qyd1rRQ:bhgrzde)*

**Comment by EricCousineau-TRI** [comment]
Review status: 11 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl55E3O2f9aBqTM6Ufz:b-auw110) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fine by me.  I was like "meh" at the time.
</blockquote></details>

Hmm... Just successfully ported `kythe` to its own package, but now it makes me kinda meh as well.
Let me know if you'd like me to roll that change back.

I've updated the example to consume `@drake//drake:libdrake.so` (as `data`), and it seems to work out, at least the for the targets that it consumes:
https://github.com/EricCousineau-TRI/drake_external/commit/2e6e75a5bbadbd15a56709ca322d9ce811e1437a

---

*[tools/gtest.BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4nx69BsOf0G44iAcI:-Kl4s6XJ1aW8rqplqBwr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d16d995aa61b18a5d22e800201771634bb90a6d/tools/gtest.BUILD#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Could you explain why the `@//conditions:default` doesn't turn into `@drake//conditions:default`?  (Same for spdlog.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl59vhJGmataTvbsLOP:b-cw9z6o) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Hmm... Just successfully ported `kythe` to its own package, but now it makes me kinda meh as well.
Let me know if you'd like me to roll that change back.

I've updated the example to consume `@drake//drake:libdrake.so` (as `data`), and it seems to work out, at least the for the targets that it consumes:
https://github.com/EricCousineau-TRI/drake_external/commit/2e6e75a5bbadbd15a56709ca322d9ce811e1437a
</blockquote></details>

OK The kythe thing is fine.

FYI I think the Bazel example we end up putting in RobotLocomotion should _not_ use `libdrake.so` but rather the regular Bazel cc_library stuff via labels.

---

*[WORKSPACE, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl59eXqBkuIr1F_5nhg:-Kl59eXrgA4CpHPL0mVj:b-x9ld3s) ([raw file](https://github.com/robotlocomotion/drake/blob/9b75766abe22fab62037bf6a0859195262fb3f66/WORKSPACE#L19)):*
> ```Python
> workspace(name = "drake")
> ```

BTW Is this two blank lines now?  Seems excessive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5Atv4mm9yjYMAhHI8:brxp9sd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK The kythe thing is fine.

FYI I think the Bazel example we end up putting in RobotLocomotion should _not_ use `libdrake.so` but rather the regular Bazel cc_library stuff via labels.
</blockquote></details>

Sounds good!

---

*[WORKSPACE, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl59eXqBkuIr1F_5nhg:-Kl5BAfJGVxgFnYJC269:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b75766abe22fab62037bf6a0859195262fb3f66/WORKSPACE#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this two blank lines now?  Seems excessive.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5Ayks5KvjQyTrRHh3:b-ree4jq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK The kythe thing is fine.

FYI I think the Bazel example we end up putting in RobotLocomotion should _not_ use `libdrake.so` but rather the regular Bazel cc_library stuff via labels.
</blockquote></details>

A `cc_library(name = "drake")` or all the component libraries?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5CBYlCumnKun1ubql:bvau3ll) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

A `cc_library(name = "drake")` or all the component libraries?
</blockquote></details>

Seems like a good idea to me! Threw it in here for grins, but can defer that to some other PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5BoxgEly-RA_17lHA:b-y1n75i) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

A `cc_library(name = "drake")` or all the component libraries?
</blockquote></details>

FYI I think doing an example like this would be best:
```python
cc_binary(
    ....
    deps = [
        "@drake//drake/systems/analysis",
        "@drake//drake/systems/framework",
        "@drake//drake/systems/primitives:constant_value_source",
    ],
)
```

So using per-directory rollup libraries where appropriate, and small libraries otherwise.

---

*[drake/BUILD, line 27 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl5CGY08m9mvVuxEDO6:-Kl5CGY1Xo4h5N-eY5SN:b-sr15o3) ([raw file](https://github.com/robotlocomotion/drake/blob/14029d5c5637481ef98a24ac94b342a169d2327d/drake/BUILD#L27)):*
> ```Python
>     name = "drake",
>     deps = _LIBDRAKE_COMPONENTS,
> )
> ```

Nope.  The uberlibrary should _only_ be for CMake export / binary installation.  It should not be a public Bazel export.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5DHVg2GsiV9PfTAgT:b-tvqud3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think doing an example like this would be best:
```python
cc_binary(
    ....
    deps = [
        "@drake//drake/systems/analysis",
        "@drake//drake/systems/framework",
        "@drake//drake/systems/primitives:constant_value_source",
    ],
)
```

So using per-directory rollup libraries where appropriate, and small libraries otherwise.
</blockquote></details>

True, for external projects, but for the test, would it be more useful to include the megalib?

Added an example of Jamie's suggestion on the downstream thing (adding `//drake/solvers`):
https://github.com/EricCousineau-TRI/drake_external/commit/07b0e288fe4389e56c632f21fafcde9d473d43a1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
*[drake/BUILD, line 27 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl5CGY08m9mvVuxEDO6:-Kl5DjoL6hgO9ffDCRMJ:by13wgb) ([raw file](https://github.com/robotlocomotion/drake/blob/14029d5c5637481ef98a24ac94b342a169d2327d/drake/BUILD#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nope.  The uberlibrary should _only_ be for CMake export / binary installation.  It should not be a public Bazel export.
</blockquote></details>

For external testing with Bazel, it'd still be nice to get to all of the projects, and not have to sync it.

Mayhaps, in something like `//tools/library.bzl`, we can define something like `libdrake_components()`, such that they could be imported, via:
```
load("@drake//tools:libdrake.bzl", "libdrake_components")
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5F7oOYc_OQ6Eoq_pp:bepjj3z) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

True, for external projects, but for the test, would it be more useful to include the megalib?

Added an example of Jamie's suggestion on the downstream thing (adding `//drake/solvers`):
https://github.com/EricCousineau-TRI/drake_external/commit/07b0e288fe4389e56c632f21fafcde9d473d43a1

</blockquote></details>

We should be exposing the same interface regardless of the build system someone is using to consume it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5MHbpIUp7NiwC1ufD:b-jgiv9e) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We should be exposing the same interface regardless of the build system someone is using to consume it.
</blockquote></details>

Let's have that debate somewhere else?  `libdrake.so` is not the final answer, so I don't want to export it publicly from Bazel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl4p_lyKmt2DDZkDr7p:-Kl5NUw3P7nq1RB7Asik:b2nhll9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Let's have that debate somewhere else?  `libdrake.so` is not the final answer, so I don't want to export it publicly from Bazel.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/BUILD, line 27 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-Kl5CGY08m9mvVuxEDO6:-Kl5Nei8L6j3GsKRSlEp:bto6hj8) ([raw file](https://github.com/robotlocomotion/drake/blob/14029d5c5637481ef98a24ac94b342a169d2327d/drake/BUILD#L27)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

For external testing with Bazel, it'd still be nice to get to all of the projects, and not have to sync it.

Mayhaps, in something like `//tools/library.bzl`, we can define something like `libdrake_components()`, such that they could be imported, via:
```
load("@drake//tools:libdrake.bzl", "libdrake_components")
```
</blockquote></details>

Reverted. Will create a separate issue on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jamiesnape** [comment]
Reviewed 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190)*

**Comment by jwnimmer-tri** [comment]
"unstable due to git failures" flake
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
FYI I just dismissed @stonier's blocking discussion comment, which I presume was accidental.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6190#-:-KlQFuO1T93g-DIHwH9H:b-8vh0ul)*

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

**Pull request merged**
