### PR TITLE
Variable discrete update

### PR DESCRIPTION
**Pull request by edrumwri**
Adds time as a discrete state variable to RigidBodyPlant to permit variable step time-stepping (which will be used for robust contact determination between triangle soups).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7816)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3G2Vg6QtRNxzDlL7hg:brbsdox)*

**Comment by amcastro-tri** [comment]
I need more context (no pun intended) to review this @edrumwri. I really have no idea why you'd save any time here or when you'd be updating this time variable.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3TA2HofocIU8zRZqMZ:b-1mw3yh)*

**Comment by amcastro-tri** [comment]
Thank you for the VC Evan, now I understand why you need to save your last time step value in the context. However I should point out that it does seem strange that the system itself should know about this. As is, the RBP is playing more and more the role of a solver rather than just being what it is supposed to be, a system. I feel like all the code now here in RBP should live in an external solver, not in the plant. In the same way we have RK2, RK4 and so on I think we should be able to write time stepping solvers. That, of course, would require the system to be able to answer more questions about their structure. For instance, if I write : 
```
Mv̇=F+Gᵀλ
G(q)v=0
```
even though suggestive of a mechanical system, nothing tells me that it MUST be a mechanical system but it could in general represent a class of dynamical systems with that structure. Just passing my thoughts, @sherm1, @mitiguy, what do you think?

In any case, for the purpose of this PR, and being that our framework doesn't yet support something like what I am talking about, what it is here implemented is the only way to do it right now. Thus :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/dev/test/quadrotor_test.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UmLB_92ygmSugtcau:-L3UmLB_92ygmSugtcav:bausr5t) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/dev/test/quadrotor_test.cc#L115)):*
> ```cpp
>   Context<double>& discrete_context = discrete_model.GetMutableSubsystemContext(
>       discrete_plant, &discrete_sim.get_mutable_context());
>   discrete_context.get_mutable_discrete_state(0).
> ```

this is not documented anywhere for user to guess there should be a `(0)` argument. Maybe have a method `BasicVector<T>& RBP::GetContinuousStateVector(Context<T>* context) const`?

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UlLy-3we1IORdtFP6:-L3UlLy0AJy2pCKR_EoX:b-kyx8gj) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/rigid_body_plant/rigid_body_plant.cc#L355)):*
> ```cpp
>       make_unique<BasicVector<T>>(get_num_states()));
> 
>   // Time.
> ```

I'd improve on this comment. Per our discussion I believe this state would hold the value of the time in the last time step that was taken? Is that accurate? could you add comment/doc somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3UmgZS5NSlKtIDvjzA:btlune4)*

**Comment by sherm1** [comment]
@amcastro-tri, because of the inequality constraints and system-dependent solution tricks (like discretized friction cone) it's hard to characterize the system in general for an external solver. There is an advantage to using the existing discrete update method in that case -- it is very flexible and allows for easy experimentation with different discrete formulations for solving particular problems. It is much easier to characterize the continuous problem since there is only one correct way to advance time. But even there we have events like impacts where we might use a discrete solver - and then we don't try to do that in general but let the system handle it instead (using an impact event handler).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3Uy86iU9CPqKPpYMEA:bhbwtlm)*

**Comment by edrumwri** [comment]
Alejandro, your suggestion to the change of quadrotor_test instigated me to move it out of the dev branch and into the main one so that we had a test case that covered RigidBodyPlant produced consistent results whether simulated using continuous or discrete methods. That simultaneously allowed me to remove dev/TimeSteppingRigidBodyPlant, which has been fully superseded by RigidBodyPlant. The combination of all of these changes is still very small.

---

Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UlLy-3we1IORdtFP6:-L3Vbc_3zBvqsZtup0MN:b8kyb0z) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/rigid_body_plant/rigid_body_plant.cc#L355)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd improve on this comment. Per our discussion I believe this state would hold the value of the time in the last time step that was taken? Is that accurate? could you add comment/doc somewhere?
</blockquote></details>

Just added documentation on this in the header file.

---

*[multibody/dev/test/quadrotor_test.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UmLB_92ygmSugtcau:-L3VdzInzf_LEp8cdeub:b5b3ks) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/dev/test/quadrotor_test.cc#L115)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this is not documented anywhere for user to guess there should be a `(0)` argument. Maybe have a method `BasicVector<T>& RBP::GetContinuousStateVector(Context<T>* context) const`?
</blockquote></details>

Done. Note that while I was operating on this class, I moved it out of /dev and to multibody/rigid_body_plant/test proper in order to allow me to simultaneously remove timesteppingrigidbodyplant (overdue). See my note above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3Vhzs_O2NYJy3kUfS0:b2umqwf)*

**Comment by amcastro-tri** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UlLy-3we1IORdtFP6:-L3YXdpKnM7pePMLEk3B:b-j6f0cg) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/rigid_body_plant/rigid_body_plant.cc#L355)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Just added documentation on this in the header file.
</blockquote></details>

Thanks! that looks great. Would you also add about two lines for the developer here improving upon the (quite brief really) "// Time" comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816)*

**Comment by edrumwri** [comment]
+@sammy-tri for platform review please (per regular rotation)

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 355 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3UlLy-3we1IORdtFP6:-L3ZPuidvcxnsGNH_ZFe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db18e3b289012deda649dd78b9057c3d3d927524/multibody/rigid_body_plant/rigid_body_plant.cc#L355)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thanks! that looks great. Would you also add about two lines for the developer here improving upon the (quite brief really) "// Time" comment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3ZQ0DiUZEmwmddcn3k:b-ugdwr5)*

**Comment by amcastro-tri** [comment]
Reviewed 4 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant.h, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3Zbe6v2-Q5Nx9vE1EH:-L3Zbe6v2-Q5Nx9vE1EI:bhgc3xm) ([raw file](https://github.com/robotlocomotion/drake/blob/cbd1a61d48c55ccee429a3ce54a3252f07f214e0/multibody/rigid_body_plant/rigid_body_plant.h#L86)):*
> ```objc
> /// RigidBodyLoop instances in the multibody model. Even though loop constraints
> /// are a particular case of holonomic constraints, general holonomic
> /// constraints are not yet supported. For %RigidBodyPlant systems simulated
> ```

BTW, I actually liked this here. I just wanted a developer's comment next to the discrete state declaration so that actual code and brief comment were not that far apart. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816)*

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 1 of 5 files at r1, 4 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-:-L3ZgFrz4l0Hx2wIgOKD:b-pu9q93)*

**Comment by edrumwri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/rigid_body_plant.h, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7816#-L3Zbe6v2-Q5Nx9vE1EH:-L3ZsDUA8NCqr_lCSne0:b833bj4) ([raw file](https://github.com/robotlocomotion/drake/blob/cbd1a61d48c55ccee429a3ce54a3252f07f214e0/multibody/rigid_body_plant/rigid_body_plant.h#L86)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I actually liked this here. I just wanted a developer's comment next to the discrete state declaration so that actual code and brief comment were not that far apart. 
</blockquote></details>

Strange. That wasn't due to be eliminated. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7816)*

**Pull request merged**
