### PR TITLE
[geometry] Adjust test tolerances for mac arm64

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #17009

+@sherm1 for feature review, please.
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207)

### CODE REVIEW

**Comment by RussTedrake** [comment]
-@sherm1 +@DamrongGuoy for feature review, please.

**Comment by RussTedrake** [comment]
To be clear, the M1 CI tests are not expected to pass.  A summary of the failures is in #17009.  If the feature review can just focus on the code change, I can work with platform to get the M1 CI correct.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with one optional request.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207#-:-N2Clw4K4EzYUQp-59x3:brf5zve)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/proximity/test/penetration_as_point_pair_callback_test.cc` line 240 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17207#-N2Cj99z0YCtrnMSDbSG:-N2Cj99z0YCtrnMSDbSH:bwm8sci) ([raw file](https://github.com/robotlocomotion/drake/blob/2a12ae70982d5f6fc0768b72472f6d762677bc87/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L240)):*
> ```cpp
>       ASSERT_EQ(point_pairs_double.size(), 1u);
>       EXPECT_NEAR(ExtractDoubleOrThrow(first_result.depth),
>                   point_pairs_double[0].depth, 3e-16);
> ```

Optional.  How about we use `2*kEps` to be consistent with other lines in the same file?

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207#-:-N2CqJYZDJTYFpqV_-9z:b-ruv0ff)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @DamrongGuoy and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @DamrongGuoy and @RussTedrake)

___
*[`geometry/proximity/test/penetration_as_point_pair_callback_test.cc` line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17207#-N2Crh9e74fWXqPqKq0R:-N2CtOwL462v4DTjwAn9:b-50haqh) ([raw file](https://github.com/robotlocomotion/drake/blob/ee833d1256afa79dca7a10656767205775b1b8e6/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L225)):*
> We we intent ...

typo; Should be "If we intend..."

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/proximity/test/penetration_as_point_pair_callback_test.cc` line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17207#-N2Crh9e74fWXqPqKq0R:-N2CwzsL4UliqA9Cf5Tt:b-cqkzgf) ([raw file](https://github.com/robotlocomotion/drake/blob/ee833d1256afa79dca7a10656767205775b1b8e6/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L225)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> We we intent ...

typo; Should be "If we intend..."
</blockquote></details>

Thanks for asking @jwnimmer-tri .  It is true that originally the intention of the test is to show that `double` and `AutodDiff.value()` should be bitwise identical.

However, as we do more and more checks on more platforms, we found that it's not true to the last bit.

I think we can change the comment slightly like this:
```
      // Make sure that callback with T=AutoDiffXd and T=double produces the
      // same result within numerical noise.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`geometry/proximity/test/penetration_as_point_pair_callback_test.cc` line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17207#-N2Crh9e74fWXqPqKq0R:-N2CziW3CUwP_hSE3iZp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee833d1256afa79dca7a10656767205775b1b8e6/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L225)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thanks for asking @jwnimmer-tri .  It is true that originally the intention of the test is to show that `double` and `AutodDiff.value()` should be bitwise identical.

However, as we do more and more checks on more platforms, we found that it's not true to the last bit.

I think we can change the comment slightly like this:
```
      // Make sure that callback with T=AutoDiffXd and T=double produces the
      // same result within numerical noise.
```

</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

Once CI finishes, we'll squash this in.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207#-:-N2Czwrx8Ps1jnV3gXa1:bcwlbhh)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17207)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
