### PR TITLE
[IN_PROGRESS]Allow the Quadrotor example to build on Windows

### PR DESCRIPTION
**Pull request by sherm1**
Quadrotor appears to have been disabled for historical reasons that no longer apply.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/1849)

### CODE REVIEW

**Comment by sherm1** [comment]
Windows build failed because the Quadrotor program failed to link due to unresolved symbol `AdditiveGaussianNoiseModel`. That is a templatized class but had been marked with `DRAKERBSYSTEM_EXPORT` which implies that its definition can be found already instantiated in a shared library. I removed that from `NoiseModel` and `AdditiveGaussianNoiseModel`.

The export macro shouldn't be used on templatized classes unless all possible combinations of template arguments are instantiated somewhere in library code.

**Comment by RussTedrake** [comment]
@sherm1 -- you need to change https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Quadrotor/runLQR.cpp#L18 to use the aligned_allocator (or just call `shared_ptr(new Quadrotor)`).

**Comment by sherm1** [comment]
> you need to change ... to use the aligned_allocator (or just call shared_ptr(new Quadrotor)).

Thanks, Russ -- fixed, pending build. I'm sure you don't need me to point this out, but that is not a good solution! It violates encapsulation because the class user must know its implementation in order to use it. A later addition of an aligned Eigen type as a private member of a previously Eigen-free class could break a lot of working user code. I'll file a separate issue for discussion.

**Comment by sherm1** [comment]
@RussTedrake -- while Quadrotor builds fine in Win64 I haven't been able to get it through the VS 2015 Win32 compiler (not related to the make_shared problem). This may be why this test was disabled on Windows; it would be great to fix it. I don't think the problem is unique to Quadrotor. I have been digging into Eigen for several hours now and am running out of ideas. Details below -- does this ring any bells?

[This line](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Quadrotor/runLQR.cpp#L34) fails to compile (`auto c = timeInvariantLQR(*quad, xG, uG, Q, R);`) when it instantiates `Drake::totalSizeAtCompileTime()`. The error is
```
eigen3\eigen\src/Core/CwiseBinaryOp.h(54): error C2719: 'unnamed-parameter': 
formal parameter with requested alignment of 16 won't be aligned
```
Microsoft describes that error as:
```
'parameter': formal parameter with __declspec(align('#')) won't be aligned
The align __declspec modifier is not permitted on function parameters. Function parameter alignment is controlled by the calling convention used. For more information, see Calling Conventions.
The following sample generates C2719 and shows how to fix it:
    void func(int __declspec(align(32)) i);   // C2719
    // try the following line instead
    // void func(int i);
```
Of course there is nothing so obvious in the code. It occurs in an instantiation of Eigen's `result_of` struct
```c++
template<typename BinaryOp, typename Lhs, typename Rhs>
struct Eigen::internal::traits<CwiseBinaryOp<BinaryOp, Lhs, Rhs> >
{ // ...
  typedef typename result_of<
                     BinaryOp(      // this is line 54
                       typename Lhs::Scalar, // unnamed formal parameters
                       typename Rhs::Scalar
                     )
                   >::type Scalar;
};
```
Presumably one or both of the arguments to BinaryOp has an alignment requirement that triggers the error at the (unevaluated) function call. But I don't understand why the same error doesn't occur for Win64 when the same 16-byte alignment would presumably be enforced.

**Comment by sherm1** [comment]
Here is the full compiler traceback of the instantiation failure:
```
1>------ Build started: Project: runQuadrotorLQR, Configuration: Debug Win32 ------
1>  runLQR.cpp
1>c:\users\sherm\documents\github\sherm1\drake\build\include\eigen3\eigen\src/Core/CwiseBinaryOp.h(54): 
error C2719: 'unnamed-parameter': formal parameter with requested alignment of 16 won't be aligned
1>  c:\users\sherm\documents\github\sherm1\drake\build\include\eigen3\eigen\src/Core/CwiseBinaryOp.h(149): 
note: see reference to class template instantiation 'Eigen::internal::traits<Derived>' being compiled
1>          with
1>          [
1>              Derived=Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>>,const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>,const Eigen::Product<Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,3,0,3,3>,Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>,0>>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\build\include\eigen3\eigen\src/Core/CwiseBinaryOp.h(83): 
note: see reference to class template instantiation 'Eigen::CwiseBinaryOpImpl<BinaryOp,LhsType,RhsType,Eigen::internal::cwise_promote_storage_type<Eigen::internal::traits<Derived>::StorageKind,Eigen::Dense,BinaryOp>::ret>' being compiled
1>          with
1>          [
1>              BinaryOp=Eigen::internal::scalar_sum_op<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>>,
1>              LhsType=Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>,
1>              RhsType=Eigen::Product<Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,3,0,3,3>,Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>,0>,
1>              Derived=Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>
1>          ]
1>  C:\Users\Sherm\Documents\GitHub\sherm1\drake\drake/examples/Quadrotor/Quadrotor.h(169):
 note: see reference to class template instantiation 'Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>>,const Derived,const Eigen::Product<Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,3,0,3,3>,Derived,0>>' being compiled
1>          with
1>          [
1>              Derived=Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>,3,1,0,3,1>
1>          ]
1>  C:\Users\Sherm\Documents\GitHub\sherm1\drake\drake/systems/controllers/LQR.h(35): note:
 see reference to function template instantiation 'QuadrotorState<AutoDiffType> Quadrotor::dynamics<Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>>(const Scalar &,const QuadrotorState<AutoDiffType> &,const QuadrotorInput<AutoDiffType> &) const' being compiled
1>          with
1>          [
1>              Scalar=Eigen::AutoDiffScalar<Eigen::Matrix<double,16,1,0,16,1>>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\drake\core\Gradient.h(169):
 note: see reference to class template instantiation 'Drake::internal::TotalSizeAtCompileTime<Derived>' being compiled
1>          with
1>          [
1>              Derived=Eigen::Matrix<double,4,1,0,4,1>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\drake\core\Gradient.h(167): 
note: while compiling class template member function 'int Drake::internal::TotalSizeAtCompileTime<Derived,Eigen::Matrix<double,4,1,0,4,1>>::eval(void)'
1>          with
1>          [
1>              Derived=Eigen::Matrix<double,12,1,0,12,1>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\drake\core\Gradient.h(189): 
note: see reference to function template instantiation 'int Drake::internal::TotalSizeAtCompileTime<Derived,Eigen::Matrix<double,4,1,0,4,1>>::eval(void)' being compiled
1>          with
1>          [
1>              Derived=Eigen::Matrix<double,12,1,0,12,1>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\drake\core\Gradient.h(189): 
note: see reference to class template instantiation 'Drake::internal::TotalSizeAtCompileTime<Derived,Eigen::Matrix<double,4,1,0,4,1>>' being compiled
1>          with
1>          [
1>              Derived=Eigen::Matrix<double,12,1,0,12,1>
1>          ]
1>  c:\users\sherm\documents\github\sherm1\drake\drake\core\Gradient.h(265): 
note: see reference to function template instantiation 'int Drake::totalSizeAtCompileTime<Derived,Eigen::Matrix<double,4,1,0,4,1>>(void)' being compiled
1>          with
1>          [
1>              Derived=Eigen::Matrix<double,12,1,0,12,1>
1>          ]
1>  C:\Users\Sherm\Documents\GitHub\sherm1\drake\drake\examples\Quadrotor\runLQR.cpp(36): 
note: see reference to function template instantiation 'std::shared_ptr<Drake::AffineSystem<NullVector,StateVector,InputVector>> Drake::timeInvariantLQR<_Ty>(const System &,const QuadrotorState<double> &,const QuadrotorInput<double> &,const Eigen::MatrixXd &,const Eigen::MatrixXd &)' being compiled
1>          with
1>          [
1>              _Ty=Quadrotor,
1>              System=Quadrotor
1>          ]
```

**Comment by sherm1** [comment]
As a datapoint, not a recommendation: disabling alignment in Eigen (via `#define EIGEN_DONT_ALIGN`) does allow this to build on Win32.

**Comment by tkoolen** [comment]
Related to http://eigen.tuxfamily.org/bz/show_bug.cgi?id=96, which I also ran into earlier. Unfortunately the fix for that issue didn't make it into Eigen 3.2.8. One option is to patch Eigen as in https://bitbucket.org/eigen/eigen/commits/f2e6b911501d/, but with all these alignment issues on 32 bit windows, I'm actually in favor of disabling alignment on that platform. I think that people who really care about performance won't be running 32 bit Windows machines at this point in time.

**Comment by RussTedrake** [comment]
@tkoolen -- i agree.  If we disabled alignment on win32, would that actually allow us to go back theough and remove all of the alignment-specific code/ mods in the codebase?  A quick look at the eigen documentation about alignment does not say that it is only relevant on 32-bit platforms.

**Comment by RussTedrake** [comment]
... But i certainly agree that's the only place we've ever seen it cause an issue.

**Comment by sherm1** [comment]
> Related to http://eigen.tuxfamily.org/bz/show_bug.cgi?id=96, which I also ran into earlier. Unfortunately the fix for that issue didn't make it into Eigen 3.2.8.

Thanks Twan! I do see that fix in the default branch that is the Eigen 3.3 beta, so it should be coming soon.

**Comment by sherm1** [comment]
> A quick look at the eigen documentation about alignment does not say that it is only relevant on 32-bit platforms.

Yeah, it's not just for 32 bit. I think 64 bit just requires less explicit alignment for SSE so doesn't cause so much trouble. I think that will change in Eigen 3.3 because of support for AVX instructions, which allegedly function best with 32-byte alignment -- Eigen's 3.3 doc says that will be the default for AVX-enabled compiles. (And AVX is a *huge* improvement over SSE so we'll want that.)

Disabling alignment in Eigen causes an ABI change that means every method to which any Eigen data structure is passed must also have alignment off.

**Comment by RussTedrake** [comment]
right.  as much as it's easy to feel like win32 support is pulling us down, i've actually been under the impression that it was saving us from making subtle non-alignment mistakes that could be impacting things on 64-bit but weren't being caught.

**Comment by jwnimmer-tri** [comment]
@sherm1 How would you feel about closing this PR until the merge conflicts & alignment questions are corrected?  (I ask, because having it in the open PRs list seems like an ongoing distraction.)

**Comment by sherm1** [comment]
>  How would you feel about closing this PR until the merge conflicts & alignment questions are corrected?

How about if I fix it so that it is only enabled on Win64? That seems better than nothing and wouldn't cause test failures.

**Comment by jwnimmer-tri** [comment]
My only complaint is having a zomble PR hanging around.  If getting it merged somehow is an option, all the better than closing it.

**Comment by sherm1** [comment]
Replaced by #2107.

**Pull request closed without merging**
