### PR TITLE
Upgrade Externals March 2023

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #18914.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18926)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please

**Comment by mwoehlke-kitware** [comment]
+@SeanCurtis-TRI for feature review, please.

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for platform review and merge-override, please.

**Comment by jwnimmer-tri** [comment]
For boilerplate PRs, one reviewer is plenty -@jwnimmer-tri.

I can still force the merge once enough CI has passed.

**Pull request merged**
