### PR TITLE
Updated documentation build instructions

### PR DESCRIPTION
**Pull request by liangfok**
Updates documentation build instructions support `ninja` / `out-of-source` build tool / style.

Closes https://github.com/RobotLocomotion/drake/issues/2641.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2648)

### CODE REVIEW

**Comment by liangfok** [comment]
Since the next business day is Monday and this is a documentation-only change, +@sherm1 for both levels of review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KL6k23PsJ1KS5Ncd1KX:82479805)*

**Comment by sherm1** [comment]
One review pass done. I did not try to generate the documentation yet.

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEFT-dCtIB26CT5z55:-KLEFT-dCtIB26CT5z56:1159050392) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L4)):*
> ```reStructuredText
> 
> *************************************
> Documentation Generation Instructions
> ```

These instructions seem to depend on some previous actions having been completed, such as a successful superbuild step. Does this appear in a context where that has already been explained? It would be good to mention here what assumptions are being made, and ideally provide a link to the instructions that explain what has to be done before this step.

---

*[drake/doc/documentation_instructions.rst, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEG52N_spF7hh1JoqV:-KLEG52N_spF7hh1JoqW:-67828870) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L18)):*
> ```reStructuredText
> first be enabled prior to documentation generation. This process depends
> on whether Drake is being built in-source our out-of-source, and which build
> system is being used, e.g., ``make``, ``ninja``, or ``MSVC``. The following
> ```

The Windows instructions appear to assume Visual Studio. If that's correct, it would be better to say `Visual Studio` here rather than `MSVC` since CMake doesn't provide an `MSVC` Generator.

---

*[drake/doc/documentation_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEBemLTkXfiV7ywmbk:-KLEBemLTkXfiV7ywmbl:-2130882827) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L20)):*
> ```reStructuredText
> system is being used, e.g., ``make``, ``ninja``, or ``MSVC``. The following
> subsections describe the process for the officially-supported configurations.
> Please jump to the subsection that matches the build style and tool employed.
> ```

Can you provide links to click on here to facilitate that jumping?

---

*[drake/doc/documentation_instructions.rst, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEGSj4ChTCQmLS6lPN:-KLEGSj4ChTCQmLS6lPO:-169070190) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L74)):*
> ```reStructuredText
> .. _documentation-out-of-source-msvc:
> 
> Out-of-source Builds Using ``MSVC``
> ```

MSVC->Visual Studio?

---

*[drake/doc/documentation_instructions.rst, line 80 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEG_kQnRWbWtDK3fQQ:-KLEG_kQnRWbWtDK3fQR:1103085589) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L80)):*
> ```reStructuredText
> 
>     $ cd drake-build/drake
>     $ cmake -DBUILD_DOCUMENTATION=ON .
> ```

Why `$` here? Are you assuming a bash shell? If this is intended to be used with Command Prompt then using `>` would be better. 

---

*[drake/doc/documentation_instructions.rst, line 80 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEHxkmVkqvQfBRNOxY:-KLEHxkmVkqvQfBRNOxZ:1277645983) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L80)):*
> ```reStructuredText
> 
>     $ cd drake-build/drake
>     $ cmake -DBUILD_DOCUMENTATION=ON .
> ```

Currently I think this also requires `-DDISABLE_MATLAB=ON` (for those unfortunates like me who have Matlab installed but don't want to use it or have no license); see #2650. I suspect that is true on non-Windows platforms also.

I see from your instruction here that I may have been doing the wrong thing: I have been running the CMake GUI in the source `drake-distro/drake` directory rather than the `build/drake` binary directory. Should that work? 

---

*[drake/doc/documentation_instructions.rst, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEH-bA3QniwaVKALUG:-KLEH-bA3QniwaVKALUH:943412597) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L113)):*
> ```reStructuredText
> - Drake website: ``drake-distro/drake/pod-build/doc/sphinx/index.html``
> - Doxygen C++ website: ``drake-distro/drake/pod-build/doc/doxygen_cxx/html/index.html``
> - Doxygen Matlab website: ``drake-distro/drake/pod-build/doc/doxygen_matlab/html/index.html``
> ```

no newline at eof

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLEJ-oJ36z6ZGLUXMQj:30674181)*

**Comment by sherm1** [comment]
@liangfok, please see issue #2650 and PR #2655 -- that PR should change these instructions (for the better!).

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLHZE_jmHYDlhVD7WjL:899995864)*

**Comment by liangfok** [comment]
OK I will wait for #2655 to be merged before updating this PR.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLHxfRcF6POSL45n_Cn:-1604138596)*

**Comment by david-german-tri** [comment]
FYI, #2655 has been merged.

**Comment by liangfok** [comment]
Thanks for the note. Updating this PR now.

**Comment by liangfok** [comment]
I addressed all reviewer comments. This is ready for another round of review.

---

Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEFT-dCtIB26CT5z55:-KLIhBY6H0_IJNYtu2CY:31703832) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These instructions seem to depend on some previous actions having been completed, such as a successful superbuild step. Does this appear in a context where that has already been explained? It would be good to mention here what assumptions are being made, and ideally provide a link to the instructions that explain what has to be done before this step.
</details>
Done. I added a sentence at the very beginning stating that Drake must first be built from source. This statement includes a link to the build instructions.

---

*[drake/doc/documentation_instructions.rst, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEG52N_spF7hh1JoqV:-KLIhXv7f97tcTY3f4F4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The Windows instructions appear to assume Visual Studio. If that's correct, it would be better to say `Visual Studio` here rather than `MSVC` since CMake doesn't provide an `MSVC` Generator.
</details>
Done.

---

*[drake/doc/documentation_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEBemLTkXfiV7ywmbk:-KLIhiId-XzcDlHFS_F2:2109517944) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Can you provide links to click on here to facilitate that jumping?
</details>
Yes. Done.

---

*[drake/doc/documentation_instructions.rst, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEGSj4ChTCQmLS6lPN:-KLIhnBkr1CoQ0kFCyQg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L74)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> MSVC->Visual Studio?
</details>
Done.

---

*[drake/doc/documentation_instructions.rst, line 80 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEG_kQnRWbWtDK3fQQ:-KLIhpbZX27rGYOuDYKt:-1792180423) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L80)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Why `$` here? Are you assuming a bash shell? If this is intended to be used with Command Prompt then using `>` would be better. 
</details>
Yes, I was using a bash shell within Windows.  Note that in the [officially documented instructions](http://drake.mit.edu/windows.html#compile-drake), it specifies the use of a bash shell.

Given this, do you still want to change `$` to be `>`?

---

*[drake/doc/documentation_instructions.rst, line 80 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEHxkmVkqvQfBRNOxY:-KLIiKdzt3mDOX6g1WYl:1199159509) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L80)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Currently I think this also requires `-DDISABLE_MATLAB=ON` (for those unfortunates like me who have Matlab installed but don't want to use it or have no license); see #2650. I suspect that is true on non-Windows platforms also.
> 
> I see from your instruction here that I may have been doing the wrong thing: I have been running the CMake GUI in the source `drake-distro/drake` directory rather than the `build/drake` binary directory. Should that work? 
</details>
I believe this was address by #2655. There's no longer any need to enable documentation since it's on by default. I've updated this PR to reflect this.

---

*[drake/doc/documentation_instructions.rst, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEH-bA3QniwaVKALUG:-KLIjfiGUcG4ZmpDKRaZ:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> no newline at eof
</details>
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLIkBq6BzFFT4aNzodm:-1280828387)*

**Comment by sherm1** [comment]
A few more comments.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEBemLTkXfiV7ywmbk:-KLIydIiK_LpkQoMRPA2:-1459686006) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes. Done.
</details>
Nice! But when I view this it has four entries -- the last is "view the generated documentation" which doesn't match the "please jump" instructions above.

---

*[drake/doc/documentation_instructions.rst, line 80 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEG_kQnRWbWtDK3fQQ:-KLIyvzQlmysD4J4fz6n:-304858637) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L80)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes, I was using a bash shell within Windows.  Note that in the [officially documented instructions](http://drake.mit.edu/windows.html#compile-drake), it specifies the use of a bash shell.
> 
> Given this, do you still want to change `$` to be `>`?
</details>
OK, `$` makes sense if they are supposed to be using the bash shell.

---

*[drake/doc/documentation_instructions.rst, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLIyjYi5Sp3F-zZ_v9o:-KLIyjYi5Sp3F-zZ_v9p:551233671) ([raw file](https://github.com/robotlocomotion/drake/blob/33841e112b8759adb28932455d6d2f95ffebd574/drake/doc/documentation_instructions.rst#L21)):*
> ```reStructuredText
> 
> Drake's documentation is built using the ``documentation`` build target. It must
> first be enabled prior to documentation generation. This process depends
> ```

I'm not sure this is accurate any more since the target is now built by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLIzI_tp93EVx7WTm2T:2106259963)*

**Comment by liangfok** [comment]
Ready for another round of review.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEBemLTkXfiV7ywmbk:-KLJJ-0j1jpN_GMtY0-j:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Nice! But when I view this it has four entries -- the last is "view the generated documentation" which doesn't match the "please jump" instructions above.
</details>
Fixed.

---

*[drake/doc/documentation_instructions.rst, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLIyjYi5Sp3F-zZ_v9o:-KLJIyLPtAdfI4fXE4Bb:970109704) ([raw file](https://github.com/robotlocomotion/drake/blob/33841e112b8759adb28932455d6d2f95ffebd574/drake/doc/documentation_instructions.rst#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm not sure this is accurate any more since the target is now built by default.
</details>
You're right. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLJJ2suzlfA5HCuWGuf:-1455727467)*

**Comment by sherm1** [comment]
:lgtm: -- there is one missing newline. Resolve & merge.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLEBemLTkXfiV7ywmbk:-KLJRHDkVqg5fQwkXq5f:-2141036513) ([raw file](https://github.com/robotlocomotion/drake/blob/6375d6202caa8a7bba81d985346976ba8e1469f4/drake/doc/documentation_instructions.rst#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Fixed.
</details>
LGTM now.

---

*[drake/doc/documentation_instructions.rst, line 87 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLJQcOM7JNfVYQzH0Cv:-KLJQcOM7JNfVYQzH0Cw:1030243629) ([raw file](https://github.com/robotlocomotion/drake/blob/b35dab60d2f69b83ba849e5b90e7dc5c1c2a5d77/drake/doc/documentation_instructions.rst#L87)):*
> ```reStructuredText
> - Drake website: ``drake-build/drake/doc/sphinx/index.html``
> - Doxygen C++ website: ``drake-build/drake/doc/doxygen_cxx/html/index.html``
> - Doxygen Matlab website: ``drake-build/drake/doc/doxygen_matlab/html/index.html``
> ```

Looks like the trailing newline got lost.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLJRSFs4-RCtVn6ljfH:-788045939)*

**Comment by liangfok** [comment]
I've added the missing new line. Waiting for CI now.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 87 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-KLJQcOM7JNfVYQzH0Cv:-KLJa5TWTwZWx3w8Z127:-938671458) ([raw file](https://github.com/robotlocomotion/drake/blob/b35dab60d2f69b83ba849e5b90e7dc5c1c2a5d77/drake/doc/documentation_instructions.rst#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Looks like the trailing newline got lost.
</details>
Done. PTAL. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648#-:-KLJa8O-sRdKPoyvaVKX:279567019)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2648)*

**Comment by sherm1** [comment]
Windows builds seem stuck but inspection shows they completed successfully so I'm going to force-merge this.

**Comment by jwnimmer-tri** [comment]
For the record:
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/experimental/2331/ was the penultimate build, without the newline fixed; it passed on all platforms.
- https://drake-jenkins.csail.mit.edu/view/Experimental/job/experimental/2332/ was the ultimate build, with the newline fixed; it did not even start to run on Windows -- the dimmed blue bubble with hovertext "Success - pending" is misleading, but the "pending" hovertext means "not yet started"

Given that documentation is only tested by the `linux` target of pre-merge CI, though, ignoring windows for the purposes of merging is just fine.

**Pull request merged**
