### PR TITLE
[pydrake] Bind fixed-size DistributionVector classes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/pull/18581 for https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLc0yV-BhvAN1KQzJam:-NLc0yV-BhvAN1KQzJan:b-12s8qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
> ```objc
> 
> namespace internal {
> template <typename Singular>
> ```

FYI This was required so that the `DistributionVectorVariant` did not have any repeated types.  When a `std::variant` has repeated types, the `operator=` can be ambiguous as to which one to use, which `pybind11` was choking on.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2 with ignorable nit on using templated type registration vs. modified name

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-:-NLcLT0l78mVcyOnHkp4:begfixo)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLc0yV-BhvAN1KQzJam:-NLcLy0a8toCvGAT0ynJ:bj3luwu) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This was required so that the `DistributionVectorVariant` did not have any repeated types.  When a `std::variant` has repeated types, the `operator=` can be ambiguous as to which one to use, which `pybind11` was choking on.
</blockquote></details>

Huh, that smells kind odd b/c the types are only involved in branching - but thanks for the info!
___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcM4HRA1SljpMIhNKY:-NLcM4HRA1SljpMIhNKZ:bz75ubv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
> ```objc
> 
> namespace internal {
> template <typename Singular>
> ```

nit Can you encode your above comment here?
___
*[`bindings/pydrake/common/schema_py.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcKsln7OUxDgsTH2cn:-NLcKsloD_Yj4Fethpma:b-fvto8e) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L145)):*
> ```cpp
>   // offer a type array, e.g., 'DeterministicVector[i]' to look up a fixed-size
>   // vector type.
>   auto bind_distribution_vectors = [&]<int Size>(
> ```

BTW ooooh! Didn't realize we had templated lambdas already! I thought that was C++20.
___
*[`bindings/pydrake/common/schema_py.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcLFdD1EtCxfFsoWeD:-NLcLFdD1EtCxfFsoWeE:bgfycr9) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L180)):*
> ```cpp
> 
>     {
>       using Class = UniformVector<Size>;
> ```

nit Rather than manually munging the class name based on param, and then having a TODO on providing sugared value, I'd recommend just going straight for defining the templated type, using `TemporaryClassName()` and `AddTemplateClass()`.

(If you are concerned about override of `cls.__name__`, then yeah, feel free to dismiss this.)

**Comment by jwnimmer-tri** [comment]
*[`bindings/pydrake/common/schema_py.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcLFdD1EtCxfFsoWeD:-NLcOcxf-Io4u-CTF1mu:bpmzdlk) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L180)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than manually munging the class name based on param, and then having a TODO on providing sugared value, I'd recommend just going straight for defining the templated type, using `TemporaryClassName()` and `AddTemplateClass()`.

(If you are concerned about override of `cls.__name__`, then yeah, feel free to dismiss this.)
</blockquote></details>

Working

I'm actually going to try this.  The lack of a "real" template class is being somewhat annoying as I'm writing the full suite of YAML coverage tests now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLc0yV-BhvAN1KQzJam:-NLcO1Ta1rrejDwVpftk:b-tue2eh) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Huh, that smells kind odd b/c the types are only involved in branching - but thanks for the info!
</blockquote></details>

The pybind11 treatment of `std::variant` compiles the assignment operator for all 6 variation options seen  below (even though in Drake it would be a runtime error to call one of `internal` assignment overloads); trying to compile all six overloads means the last 3 types ended up all being ambiguous with themselves, when they were the same thing.

This doesn't compile, for example:

```c++
std::variant<std::string, int, int> foo{"foo"};
foo = 22;  // ambiguous
```
___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcM4HRA1SljpMIhNKY:-NLcOBFs7Prnzjz2erfm:bxj2dbs) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you encode your above comment here?
</blockquote></details>

To me, those details are remarkable during PR review (where the _change_ is presented on its own) but would be useless and confusing for anyone who would encounter such a comment in the wild.  I think if anyone tried to undo this, they would quickly see why the compiler was angry.

On the other hand, I should probably document what this template argument signifies -- done now.
___
*[`bindings/pydrake/common/schema_py.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcKsln7OUxDgsTH2cn:-NLcOXJ5EV6vpzluqtiC:b-wv0czv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L145)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW ooooh! Didn't realize we had templated lambdas already! I thought that was C++20.
</blockquote></details>

Officially it is C++20, but our mainstream compilers gave it to us early.
___
*[`bindings/pydrake/common/schema_py.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcLFdD1EtCxfFsoWeD:-NLcfGmeE5yXFF42Mka1:biczgf9) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'm actually going to try this.  The lack of a "real" template class is being somewhat annoying as I'm writing the full suite of YAML coverage tests now.
</blockquote></details>

Done.  Much nicer.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcM4HRA1SljpMIhNKY:-NLfWYSE1eRtUIFDck8i:b-14vvna) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To me, those details are remarkable during PR review (where the _change_ is presented on its own) but would be useless and confusing for anyone who would encounter such a comment in the wild.  I think if anyone tried to undo this, they would quickly see why the compiler was angry.

On the other hand, I should probably document what this template argument signifies -- done now.
</blockquote></details>

OK Aye, makes sense, and thanks!
___
*[`common/schema/stochastic.h` line 450 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLc0yV-BhvAN1KQzJam:-NLfXEFy7rmulrPFUhuq:by5s5kf) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/common/schema/stochastic.h#L450)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The pybind11 treatment of `std::variant` compiles the assignment operator for all 6 variation options seen  below (even though in Drake it would be a runtime error to call one of `internal` assignment overloads); trying to compile all six overloads means the last 3 types ended up all being ambiguous with themselves, when they were the same thing.

This doesn't compile, for example:

```c++
std::variant<std::string, int, int> foo{"foo"};
foo = 22;  // ambiguous
```
</blockquote></details>

Gotcha, thanks!
___
*[`bindings/pydrake/common/schema_py.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcKsln7OUxDgsTH2cn:-NLfWScgAIb10tptXLMj:b-5b1d1n) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Officially it is C++20, but our mainstream compilers gave it to us early.
</blockquote></details>

OK Good to know!
___
*[`bindings/pydrake/common/schema_py.cc` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLcLFdD1EtCxfFsoWeD:-NLfWMKRCqwsPrVIaUcB:b-ieyay5) ([raw file](https://github.com/RobotLocomotion/drake/blob/6378a86c466eb3bece587aaa45c97ece87232c0f/bindings/pydrake/common/schema_py.cc#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  Much nicer.
</blockquote></details>

OK Sweet, thanks!
___
*[`bindings/pydrake/common/test/schema_test.py` line 113 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLfWKuT2LrT9fO_kWx_:-NLfWKuUBW6SNvaZm2MN:b-a4tu2i) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e8e918276e68a8a2291f95e3c47ee42c5ced33e/bindings/pydrake/common/test/schema_test.py#L113)):*
> ```Python
>                 name = f"{key}Vector[{size}]"
>                 with self.subTest(name=name):
>                     dut_cls = getattr(mut, name)
> ```

nit Use `getattr` a bit obtuse, maybe not necessary now that templates are used?
Consider changing, e.g.

```
for template in  [DeterministicVector, GaussianVector, UniformVector]:
    dut_cls = template[size]
    if template == DeterministicVector:
        ...
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/test/schema_test.py` line 113 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18567#-NLfWKuT2LrT9fO_kWx_:-NLfZlb37AZudozq1UPH:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4e8e918276e68a8a2291f95e3c47ee42c5ced33e/bindings/pydrake/common/test/schema_test.py#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Use `getattr` a bit obtuse, maybe not necessary now that templates are used?
Consider changing, e.g.

```
for template in  [DeterministicVector, GaussianVector, UniformVector]:
    dut_cls = template[size]
    if template == DeterministicVector:
        ...
```
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18567)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
