### PR TITLE
[geometry] De-template Meshcat's mesh loading code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Compiling the mesh loading code twice offends my sensibilities.

+@SeanCurtis-TRI for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20771)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
I was expecting simply passing in filename, extension, and scale and eliminate the template completely. But, meh.

:LGTM: X2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20771#-:-NntrSxJ4aqwxe7MEpCN:b-i3zr3s)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Ya, I thought about that but the code for handling scale is (and should be) file-agnostic, so it seemed better to not repeat it over and over again (once per file type).

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by SeanCurtis-TRI** [comment]
The scale *is* file agnostic. That doesn't come from file, it simply comes from `geometry::Mesh` and `geometry::Convex`.

**Comment by jwnimmer-tri** [comment]
Ah, I see.  The scale implementation _was_ duplicated per-file-type (which we both agree was wrong), and I fixed that by moving up into the templated method.  Better would be to do it at the end of the common method.  Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I apologize, my comments are leading you to do work that isn't strictly necessary. And it's not even what I'd intended.  What I'd *actually* had in mind was:

```c++
void ImplementMesh(const std::string& filename, const std::string& extension,
                   double scale, void* data) {
   ...
}
```

(with the appropriate changes to the two call sites). This would get rid of the template entirely without introducing the second function. But I will emphasize, I'm not advocating that over this, it's just what I considered doing in the past.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20771#-:-NntudE-4pPA0yo7fydf:b-r4ad6f)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Comment by SeanCurtis-TRI** [comment]
*[`geometry/meshcat.cc` line 436 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20771#-NntwB_T7OuX6J5A6ZAw:-NntwB_T7OuX6J5A6ZAx:b-ajzf2m) ([raw file](https://github.com/RobotLocomotion/drake/blob/425e4eb287d1a90800c1af3878fe5d9290391980/geometry/meshcat.cc#L436)):*
> ```cpp
> 
>     // Set the scale.
>     std::visit(
> ```

BTW And to explicit, this is definitely a better handling of scaling the lumped data than what it replaced.  :)

**Comment by jwnimmer-tri** [comment]
CI flaked out, so I had to re-push anyway.  The simplicity of your suggestion won out.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20771)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20771#-:-Nnu7C8A2yL4g9IYyR-9:b-vtj4w1)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
