### PR TITLE
pydrake: Expose subset of `*_pybind.h` headers for downstream consumption

### LINKED ISSUE #9009: pydrake: Permit consuming consuming `*_pybind.h` headers in downstream projects
Per @mposa's request, to enabling binding code such as:
https://github.com/DAIRLab/dairlib-public/tree/4e8464a/systems/trajectory_optimization

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9009

\cc @mposa

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9010)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for both reviews, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9010#-:-LF4-dC-EbV6odcp-QBj:bbdyukq)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[bindings/pydrake/BUILD.bazel, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4ckY50MhgLxIz2j2X:-LF4ckY50MhgLxIz2j2Y:b-el7ehj) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/BUILD.bazel#L124)):*
> ```Python
> )
> 
> # TODO(eric.cousineau): Make private.
> ```

This comment seems at odds with declaring public visibility ?

---

*[bindings/pydrake/BUILD.bazel, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4cxEsBjub1ftJfSSZ:-LF4cxEsBjub1ftJfSS_:bgkhc77) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/BUILD.bazel#L129)):*
> ```Python
>     hdrs = ["symbolic_types_pybind.h"],
>     visibility = ["//visibility:public"],
> )
> ```

Its slightly unclear for a future maintainer to know what visibility marking to assigning to rules in this package.

The rule seems to be that header-only `drake_cc_library` in this package should be public.  If this is true (rather than, say, considering them one by one anew each time), please say so in a comment somewhere in this file.  (Brief is fine.)  Or, if this rule is true for all pydrake subpackages, perhaps a comment elsewhere (pydrake_pybind.h) would suit better.

If that's not true, then I guess we'll also need more comment(s) to advice on how to decide on a case-by-case basis.

---

*[bindings/pydrake/util/BUILD.bazel, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4dum_DPQQqyaB4qWd:-LF4dum_DPQQqyaB4qWe:bub4h00) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/util/BUILD.bazel#L45)):*
> ```Python
>     name = "wrap_function",
>     hdrs = ["wrap_function.h"],
> )
> ```

Unclear why this one isn't public.  (It has symbols not in a `detail` namespace.)

Ditto for lots of the cc_library ones below -- eigen, geometry, optional, etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9010)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[bindings/pydrake/BUILD.bazel, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4ckY50MhgLxIz2j2X:-LFdJOGb-S-MEMUiR5dY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/BUILD.bazel#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment seems at odds with declaring public visibility ?
</blockquote></details>

Done.

---

*[bindings/pydrake/BUILD.bazel, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4cxEsBjub1ftJfSSZ:-LFdJKFBE-axqde6PG85:b-kw6f7q) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/BUILD.bazel#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its slightly unclear for a future maintainer to know what visibility marking to assigning to rules in this package.

The rule seems to be that header-only `drake_cc_library` in this package should be public.  If this is true (rather than, say, considering them one by one anew each time), please say so in a comment somewhere in this file.  (Brief is fine.)  Or, if this rule is true for all pydrake subpackages, perhaps a comment elsewhere (pydrake_pybind.h) would suit better.

If that's not true, then I guess we'll also need more comment(s) to advice on how to decide on a case-by-case basis.
</blockquote></details>

Done. Updated doxygen to reflect conventions.

---

*[bindings/pydrake/util/BUILD.bazel, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9010#-LF4dum_DPQQqyaB4qWd:-LFdJDZf-JjwR-O56OEm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a77ab67737428897ff6427f2c44a57eb6da49f68/bindings/pydrake/util/BUILD.bazel#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this one isn't public.  (It has symbols not in a `detail` namespace.)

Ditto for lots of the cc_library ones below -- eigen, geometry, optional, etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9010)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9010#-:-LFdK1cgBO71Wf6DKjtN:bnfp4nl)*

**Pull request merged**
