### PR TITLE
doc/developers: Mention leaving review unassigned for feature review

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per @zachfang's DM question regarding review for #14494

In the case that the author does not know who the most appropriate
feature reviewer may be.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14495)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@zachfang for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14495#-:-MQKdJ5e-9JZAen-hWGU:brpbnlw)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: Thanks for adding the instruction.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14495#-:-MQKfTSo3CH1jMtvpI-e:bi495gv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review, please! (given that I am Wednesday's)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14495#-:-MQKgj8s9q9yk5jmFQZp:bpfn2ta)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I think if the submitter is unsure about review, then shots in the dark (even with git history hints) would not be what I advise.  Per https://drake.mit.edu/platform_reviewer_checklist.html, the on-call platform reviewer should pick up the PR and offer to help guide the PR through review.

**Comment by EricCousineau-TRI** [comment]
Ooh, yeah, that may be a bit more intelligent hehe. WIll update it.

**Comment by EricCousineau-TRI** [comment]
Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: this a good improvement.

The whole section (and document) is still weirdly mis-voiced for an open source project -- it's mostly recipes to be used by the Drake core team, versus the world at large, but small improvements like this are still valuable.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14495#-:-MQNlqwRB7r-f5wRKzhp:bdpkxma)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
