### PR TITLE
[geometry] Hydroelastic callback for compliant-compliant contact.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Related to #16040.

This PR is supposed to rebase on PR #16365.

Once #16365 merges, this PR will change only four files: hydroelastic_callback.h, hydroelastic_callback_test.cc, proximity_engine_test.cc, and compliant_contact_manager_test.cc.  Please do not review other files.

This PR is a part of a multi-PRs strategy. They should merge in a consistent order.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 
+@rpoyner-tri for feature review, please.

Please review only `hydroelastic_callback.h, hydroelastic_callback_test.cc, proximity_engine_test.cc, and compliant_contact_manager_test.cc.`  The other files belong to the prequel #16365.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-Mu88WOsAsLAw9weK-2-:b8c9th9)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: needs an error message fixup, some comments

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuDWrLd4lhpUifV1cvm:b9gj05q)* status: 3 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDU6pg7q9zOEFTHwP_:-MuDU6pg7q9zOEFTHwPa:bzi9k4d) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L142)):*
> ```objc
> 
> // TODO(DamrongGuoy): Take care of exceptions to soft half spaces in a better
> //  way.
> ```

nit: maybe this TODO is done if you resolve the half-space situation noted below?
___
*[geometry/proximity/hydroelastic_callback.h, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDPrfXCvYrt1-Vukka:-MuDPrfXCvYrt1-Vukkb:bp0rmtu) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L203)):*
> ```objc
>       const SoftGeometry& soft1 = data->geometries.soft_geometry(id1);
>       if (soft0.is_half_space() || soft1.is_half_space()) {
>         return CalcContactSurfaceResult::kSameCompliance;
> ```

This branch seems like it leads to a misleading error message; what users will see is something like "can't do compliant-compliant", when the real problem is "can't do compliant-compliant involving halfspaces". I think it should be fine to extend the enum and add an accurate error message.

Also, I believe this branch is not covered by a test currently.
___
*[geometry/test/proximity_engine_test.cc, line 1998 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDWW4j3FCiiRb1J1jB:-MuDWW4j3FCiiRb1J1jC:b5xf6g1) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/test/proximity_engine_test.cc#L1998)):*
> ```cpp
>       HydroelasticContactRepresentation::kTriangle, poses_, &surfaces1,
>       &points1);
>   const size_t num_point_contacts = 2;
> ```

minor: These counts (`num_point_contacts`, `num_patch_contacts`) could benefit from some comments relating them to the geometry explanations above.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDU6pg7q9zOEFTHwP_:-MuEGaZM1fFKSsagpbTq:blatnri) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L142)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit: maybe this TODO is done if you resolve the half-space situation noted below?
</blockquote></details>

That is correct. I remove the TODO.
___
*[geometry/proximity/hydroelastic_callback.h, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDPrfXCvYrt1-Vukka:-MuEBFZq5wIbgxH7Uf8a:b-8da37d) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L203)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This branch seems like it leads to a misleading error message; what users will see is something like "can't do compliant-compliant", when the real problem is "can't do compliant-compliant involving halfspaces". I think it should be fine to extend the enum and add an accurate error message.

Also, I believe this branch is not covered by a test currently.
</blockquote></details>

Working.  I'll check how `kSameCompliance` is used in various places (6 places). I might just rename it to `kCompliantMeshCompliantHalfspace` and update the error message.
___
*[geometry/test/proximity_engine_test.cc, line 1998 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDWW4j3FCiiRb1J1jB:-MuEGAco8xmDduUsk-QG:bf6urrr) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/test/proximity_engine_test.cc#L1998)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: These counts (`num_point_contacts`, `num_patch_contacts`) could benefit from some comments relating them to the geometry explanations above.
</blockquote></details>

Done. Does it help?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/test/proximity_engine_test.cc, line 1998 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDWW4j3FCiiRb1J1jB:-MuEPKrvAJSziLAB37TC:b-al1gx0) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/test/proximity_engine_test.cc#L1998)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done. Does it help?
</blockquote></details>

Looks great, thanks. not a blocker for this pass, but a later pass should s/soft/compliant/ a bunch more places.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDPrfXCvYrt1-Vukka:-MuIlg-x8kj6n42E5Rww:b-9qygs9) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L203)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Working.  I'll check how `kSameCompliance` is used in various places (6 places). I might just rename it to `kCompliantMeshCompliantHalfspace` and update the error message.
</blockquote></details>

Done.  I hope I didn't go overboard with so many lines.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuDPrfXCvYrt1-Vukka:-MuItYYo-Gz0uMf8r1_S:boljcf2) ([raw file](https://github.com/robotlocomotion/drake/blob/0cdf2993289527edfcd09731fb9eb71a3dce5697/geometry/proximity/hydroelastic_callback.h#L203)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I hope I didn't go overboard with so many lines.
</blockquote></details>

I also ran kcov to be sure.

**Review by rpoyner-tri — COMMENTED** [review]
another pass done. error message wording questions mostly.

> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuMBR39EZKeScV7hBzN:bs4bxch)* status: 3 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 101 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuMAD190kgrSP6-sJv5:-MuMAD190kgrSP6-sJv6:b6z5240) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6fc4b192203e1b44463f935efaff6762efe7b8/geometry/proximity/hydroelastic_callback.h#L101)):*
> ```objc
>   kRigidRigid,          //< Contact between two rigid geometries; not allowed.
>   kCompliantHalfSpaceCompliantMesh,  //< Contact between a compliant mesh and a
>                                      //< compliant half space; not allowed.
> ```

nit: "not allowed" or "not supported"? It seems clear that two half-spaces colliding are mathematically a problem. Seems like mesh-halfspace *could* be supported, we just aren't going to support it now.
___
*[geometry/proximity/hydroelastic_callback.h, line 312 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuMAxJRB0Td01XfJECK:-MuMAxJRB0Td01XfJECL:bqdd6jg) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6fc4b192203e1b44463f935efaff6762efe7b8/geometry/proximity/hydroelastic_callback.h#L312)):*
> ```objc
>         throw std::logic_error(fmt::format(
>             "Requested contact between two rigid objects ({} with id "
>             "{}, {} with id {}); that is not allowed",
> ```

nit: This message seems like it should maybe give the user a hint about using fallback?
___
*[geometry/proximity/hydroelastic_callback.h, line 319 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuMB2F1C7WGOCviyv5u:-MuMB2F1C7WGOCviyv5v:b-h9c2fy) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6fc4b192203e1b44463f935efaff6762efe7b8/geometry/proximity/hydroelastic_callback.h#L319)):*
> ```objc
>             "Requested contact between a compliant half space and another "
>             "compliant object ({} with id {}, {} with id {}); "
>             "that is not allowed",
> ```

nit: seems like the language here should be "not supported" rather than "not allowed"? See also comment above near the enum def.

**Review by rpoyner-tri — COMMENTED** [review]
from f2f: "allowed" is the language in use previously. Comments retracted.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuMNuNlDdUaNxR0QSZc:b-q3ot8a)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 312 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuMAxJRB0Td01XfJECK:-MuMUGuaDAGzvdpic8jT:b-c9fgph) ([raw file](https://github.com/robotlocomotion/drake/blob/0a6fc4b192203e1b44463f935efaff6762efe7b8/geometry/proximity/hydroelastic_callback.h#L312)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit: This message seems like it should maybe give the user a hint about using fallback?
</blockquote></details>

Does it look better now?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
+@ericcousineau-tri for platform review tomorrow (Thursday), please; no hurry. Today platform reviewer is @rpoyner-tri who already feature reviewed it.

Please review only `hydroelastic_callback.h`, `hydroelastic_callback_test.cc`, and `compliant_contact_manager_test.cc`.  The other files belong to the prequel PR #16365 (still under review by @joemasterjohn .)

CC: @joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuMY_cuCMVR1Q5pqIZ4:b-q7wtyl)* status: LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
And `proximity_engine_test.cc` too. Sorry for confusion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuMZxYH-n82Z9-Mv51J:b-v7g0cp)* status: LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, reviewing only files mentioned

> Reviewed 1 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuRSY0-EibA6m60rFXe:b-7xjmp4)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @EricCousineau-TRI, and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 322 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuRR4Ps712kLjZgOPYW:-MuRR4Ps712kLjZgOPYX:b-230mrp) ([raw file](https://github.com/robotlocomotion/drake/blob/a27c924b6bc7b28f966104ccb5b460a0b6205454/geometry/proximity/hydroelastic_callback.h#L322)):*
> ```objc
>         throw std::logic_error(fmt::format(
>             "Requested contact between a compliant half space and another "
>             "compliant object ({} with id {}, {} with id {}); "
> ```

nit (minor) Users may get confused about which is a half space which is not.

Consider updating message to mention it's an unordered pair, sorta?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 322 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuRR4Ps712kLjZgOPYW:-MuSWrTM-sEKI7LAVKT3:b57ynmv) ([raw file](https://github.com/robotlocomotion/drake/blob/a27c924b6bc7b28f966104ccb5b460a0b6205454/geometry/proximity/hydroelastic_callback.h#L322)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (minor) Users may get confused about which is a half space which is not.

Consider updating message to mention it's an unordered pair, sorta?
</blockquote></details>

I'm sorry for not understanding it.  Are you talking about changing the message to be like this?
```
Requested hydroelastic contact between two compliant geometries, one of which
is a half space ({} with id, {} with id {}); that is not allowed
```

Does it look better?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy, @EricCousineau-TRI, and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 322 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuRR4Ps712kLjZgOPYW:-MuS_PzWEq_OAzB5mbrD:by8vwle) ([raw file](https://github.com/robotlocomotion/drake/blob/a27c924b6bc7b28f966104ccb5b460a0b6205454/geometry/proximity/hydroelastic_callback.h#L322)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm sorry for not understanding it.  Are you talking about changing the message to be like this?
```
Requested hydroelastic contact between two compliant geometries, one of which
is a half space ({} with id, {} with id {}); that is not allowed
```

Does it look better?
</blockquote></details>

Yup, that'd be awesome!

**Review by DamrongGuoy — COMMENTED** [review]
Got :lgtm: both feature and plaform now; however, please do not merge into master yet. We need to wait for the prequel PR #16365 to merge first.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuSbLau2xIi9THHtUnb:b-lmhh4m)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[geometry/proximity/hydroelastic_callback.h, line 322 at r7](https://reviewable.io/reviews/robotlocomotion/drake/16366#-MuRR4Ps712kLjZgOPYW:-MuSbJ6w4XvrBbs-PXdF:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/a27c924b6bc7b28f966104ccb5b460a0b6205454/geometry/proximity/hydroelastic_callback.h#L322)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup, that'd be awesome!
</blockquote></details>

Done. Thanks!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by sherm1 — COMMENTED** [review]
CI is red.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuSgUNu7cGNDnz10ZeZ:bo1jshq)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you!  I'll check that.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuT-F88004jywmNXuKt:b-uxc5au)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Done.  It should pass this time.  I forgot to change the checking for the error message (see r8-r9 diff).

I forgot to run the test last time when I changed the error message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuT0LeU3YFpMItakXD3:b-jkj1lk)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Propagate the update from upstream PRs to this PR.  You'll notice that none of the relevant files (hydroelastic_callback.h,  hydroelastic_callback_test.cc, proximity_engine_test.cc, compliant_contact_mananger_test.cc) change in r9-r12 diff.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MuZXQWqDLPBTcqrPmAO:b-xbpk3f)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
Yet another update from #16365, which I hope will merge soon.

You'll notice the r9-r14 diff does not change the four relevant files of this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-Mud0SMR03OG_DR44hIb:b-o4l69v)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 5 files at r18.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
The prequel PR #16365 has merged. Rebase on `master`, so all files from 16365 are in `Reverted` group now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-Mum0A3n5vg8ytxgkssa:b-q4nty5)* status: labeled "do not merge" (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 5 files at r18, 6 of 6 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: labeled "do not merge" (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
I assume -(status: do not merge) ? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-Mum3cubE5bmQ8-BqEjc:b-r9nixz)* status: labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 9 files at r17, 1 of 5 files at r18, 6 of 6 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r18.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Yes, it's ready for merging now!

Could the platform reviewer @ericcousineau-tri do that, please? (Is that the protocol now, the platform reviewer is the one to merge, right?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MumF3PO5FoxHkqy9P4C:bs0scw4)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
I'm not sure why Reviewable still says "Awaiting my action" though.


> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MumFy4k-YM7v_bCUbp0:b3r2yng)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

**Review by sherm1 — COMMENTED** [review]
Anyone with the right bits (including the author) can merge once Reviewable is a full green circle. Me, for example!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16366#-:-MumKcU18JvFSmnJV-dW:b1p8the)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

**Pull request merged**
