### PR TITLE
[multibody] Add unit inertia for ellipsoid

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #16342.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16349)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: in case you want to assign me.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16349#-:-Mt5kzVr9OW6Absf-q1B:b-hlqoyz)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/tree/unit_inertia.h, line 236 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16349#-Mt5jHRp7-ZEIHM-4y76:-Mt5jHRp7-ZEIHM-4y77:btxq8li) ([raw file](https://github.com/robotlocomotion/drake/blob/22666a4b2e0aa0e1c60c12fa1d00bb96130a8d2d/multibody/tree/unit_inertia.h#L236)):*
> ```objc
> 
>   /// Computes the unit inertia for a unit-mass solid ellipsoid of uniform
>   /// density and semi-axes `a`, `b`, and `c` taken about its center.
> ```

minor: important to relate these to the frame axes -- see SolidBox below. Presumably a is the semi-axis in the x direction, b in y, and c in z but should be explicit.

**Review by xuchenhan-tri — COMMENTED** [review]
I was going to assign @mitiguy but thanks!

+@rpoyner-tri for platform review on Tuesday per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16349#-:-Mt5gZNbBn-iOV9Vzlmb:bp5m0wv)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[multibody/tree/unit_inertia.h, line 236 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16349#-Mt5jHRp7-ZEIHM-4y76:-Mt5sVLv0rTBM_fiknDw:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/22666a4b2e0aa0e1c60c12fa1d00bb96130a8d2d/multibody/tree/unit_inertia.h#L236)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: important to relate these to the frame axes -- see SolidBox below. Presumably a is the semi-axis in the x direction, b in y, and c in z but should be explicit.
</blockquote></details>

Done, thanks!

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for feature review

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16349#-:-Mt5vpL-1fW7Um0BJfVf:b-f384lj)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16349#-:-Mt9jYRA6i6e3dxrAFlP:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
