### PR TITLE
Added missing documentation of some preconditions in System

### PR DESCRIPTION
**Pull request by sherm1**
The NVI pattern allows the public method to pre-check arguments before invoking the virtual method so can promise the implementer that the arguments are good. We are doing that in System but I forgot to say so for some of the virtuals.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4725)

### CODE REVIEW

**Comment by sherm1** [comment]
+@naveenoid for review, please (documentation only).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-:-Ka50t4cbW0co97dXxFU:b-r2bzuh)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-:-Ka78uZUnKbZ3N9U1Lvs:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 755 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7Hbm_9HsRxdfAzkHJ:-Ka7Hbm_9HsRxdfAzkHK:bca0k24) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L755)):*
> ```objc
>   /// the supplied argument, based on the contents of the given Context.
>   ///
>   /// This method is called from the public non-virtual CalcOutput()
> ```

BTW, consider replacing "from" with "by". (Same comment below.)

---

*[drake/systems/framework/system.h, line 757 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7IEMFosInHW7G1IQF:-Ka7IEMFosInHW7G1IQG:b2sh9ya) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L757)):*
> ```objc
>   /// This method is called from the public non-virtual CalcOutput()
>   /// which will already have error-checked the parameters so you don't have to.
>   /// In particular, implementations may assume that the given Context is valid
> ```

BTW, I noticed you're using "the given Foo" instead of "@p foo".  OK, but it would be nice if this were done consistently throughout Drake's code. Tagging #2051.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-:-Ka7HYT9E_ylve9Mqxzi:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725)*

**Comment by sherm1** [comment]
Thanks, Naveen & Liang. Polished the doorknobs a little more.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 755 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7Hbm_9HsRxdfAzkHJ:-Ka8GXKVJ2Ug6jj3r2rY:b7ttqf2) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L755)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "from" with "by". (Same comment below.)
</blockquote></details>

Done. I modified this to "called only from" which is what I was trying to say. I mildly prefer "from" over "by" here because I'm thinking of a location (that has error checks) rather than a logical connection.

---

*[drake/systems/framework/system.h, line 757 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7IEMFosInHW7G1IQF:-Ka8H3G5BXmJcQVCTYU7:b1nzhcm) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L757)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I noticed you're using "the given Foo" instead of "@p foo".  OK, but it would be nice if this were done consistently throughout Drake's code. Tagging #2051.
</blockquote></details>

Done. Tried to be more consistent. I want to say "the given Foo" when I'm referring to the object contents, and `foo` when I'm talking about the argument (e.g. `foo` is non-null, but the given Foo is compatible with this System). I suspect this doesn't create any confusion either way though. Personally I hate `@p foo` as clumsy and hard to read smoothly so I use 'foo' (but with backtics) instead which doxygen formats the same way but is easy to read in the header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-:-Ka8JKqT9qusfa8VyA6i:b-dz3t6s)*

**Comment by liangfok** [comment]
*[drake/systems/framework/system.h, line 757 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7IEMFosInHW7G1IQF:-Ka8KnMX0PcgM7YCN8UR:bfqaagf) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L757)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. Tried to be more consistent. I want to say "the given Foo" when I'm referring to the object contents, and `foo` when I'm talking about the argument (e.g. `foo` is non-null, but the given Foo is compatible with this System). I suspect this doesn't create any confusion either way though. Personally I hate `@p foo` as clumsy and hard to read smoothly so I use 'foo' (but with backtics) instead which doxygen formats the same way but is easy to read in the header.
</blockquote></details>

Looks good. I'll try to tone down my use of `@p foo` in future PRs. Tagging @siyuanfeng-tri since I recall recently pointing him down the `@p foo` path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/framework/system.h, line 757 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4725#-Ka7IEMFosInHW7G1IQF:-Ka8QSgETkrKru9WIXYB:b9w0y7k) ([raw file](https://github.com/robotlocomotion/drake/blob/734b1662059604f0dc27b435f4c68d683fd43ba5/drake/systems/framework/system.h#L757)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Looks good. I'll try to tone down my use of `@p foo` in future PRs. Tagging @siyuanfeng-tri since I recall recently pointing him down the `@p foo` path.
</blockquote></details>

Definitely an author's choice/bike shed kind of thing though!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4725)*

**Comment by sherm1** [comment]
Override-merging for comment-only change.

**Pull request merged**
