### PR TITLE
bind set_publish_every_time_step

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7845)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for both reviews.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7845#-:-L3a3PJxNrtnAmkIMcZD:b-aei43i)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending CI.

That being said, I still have some old work in #5629, in which I'd like to actually remove `set_publish_every_time_step`, and instead have systems declare this themselves. That work was held up on the `LcmDrivenLoop`, and its analogous mechanism, and how the Systems framework should handle external triggers.

Can I ask if you need this feature, or if we could delegate publishing every time step to systems?

My old feature branch (which I can revive, if need be):
https://github.com/EricCousineau-TRI/drake/compare/master...EricCousineau-TRI:issue/5629_default_publish
It just removes `Simulator::set_publish_every_time_step` in Simulator, and adds `System::set_publish_every_step`

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/systems/analysis_py.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7845#-L3ajQho6HXccuwQe34h:-L3ajQho6HXccuwQe34i:bemmrbm) ([raw file](https://github.com/robotlocomotion/drake/blob/78c8c499a057002792c7947ccc5358b1e860a299/bindings/pydrake/systems/analysis_py.cc#L32)):*
> ```cpp
>     .def("get_context", &Simulator<T>::get_context, py_iref)
>     .def("get_mutable_context", &Simulator<T>::get_mutable_context, py_iref)
>     .def("set_publish_every_time_step", &Simulator<T>::set_publish_every_time_step)
> ```

Line length > 80?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7845#-:-L3ajDhSD3PvFf3yk4l8:b-deb2ty)*

**Comment by RussTedrake** [comment]
I was about to open a bug this morning to say that this parameter should be set at the system level, not at the simulator level.  Your other PR will be very welcome.  But I'd still like this now, because otherwise matplotlib chokes trying to draw the visualization on every integrator timestep.  
(btw - probably we're sending a comical number of lcm messages to DrakeVisualizer, too?)

**Comment by RussTedrake** [comment]
@EricCousineau-TRI -- +1 to reviving that old feature branch.  Currently having `Simulator:: set_publish_every_time_step` instead of `System:: set_publish_every_time_step` means that I effectively cannot have a visualization run during the simulation, and then plot the results afterwords.  The visualizer in the diagram animates incorrectly (and too slowly) if `set_publish_every_time_step(true)`, but the signal logger gets no data if `set_publish_every_time_step(false)`.

**Comment by RussTedrake** [comment]
@EricCousineau-TRI -- +2 about that old feature branch.  Do we have a github issue about it that I can reference?

**Comment by RussTedrake** [comment]
Not urgent.  But every time i hit it, it hurts.  ;-)  Just had to write two separate python scripts for the compass gait -- one for running the animation and a separate one for making the limit cycle plot, because setting the publishing rate is required for simulation, but then misses the impact events for the plotting.  (https://github.com/RussTedrake/underactuated/compare/compass_gait?expand=1)

**Pull request merged**
