### PR TITLE
[optimization] Simply Hyperellipsoid to use the default solver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This enables use of newly-added solvers like ClarabelSolver.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20663)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20663#-:-NlVgYaj1h9xEp8u8gPP:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Sigh.  Focal is being finicky.  Possibly just adding `ClarabelSolver::id()` to the middle of the hard-coded list for now would be better, leaving the TODO intact.

**Comment by jwnimmer-tri** [comment]
Closing as impractical as of today.  Apparently `ChooseBestSolver` isn't yet quite smart enough to supplant the list of hard-coded solvers in this function.

**Comment by sadraddini** [comment]
Why not just implement this:

> Possibly just adding ClarabelSolver::id() to the middle of the hard-coded list for now would be better, leaving the TODO intact.

**Comment by jwnimmer-tri** [comment]
That's fine.  It would be a different PR though, and I'm out of time.

**Pull request closed without merging**
