### PR TITLE
Implement SapLimitConstraint in terms of new APIs introduced in #19402

### PR DESCRIPTION
**Pull request by amcastro-tri**
Follow up to https://github.com/RobotLocomotion/drake/pull/19402, this PR implements the SAP limit constraints in terms of the newly introduced APIs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
*[`multibody/contact_solvers/sap/validate_constraint_gradients.h` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW2rE_R8-ip8snCZY5B:-NW3gxD75t4PYR5EZ9aO:b-bpglt4) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/validate_constraint_gradients.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

FYI, this small testing tool is being reviewed in #19429 as well @xuchenhan-tri. I'll rebase accordingly depending on which PR lands first.
cc'ing @joemasterjohn 
</blockquote></details>

Does that mean I should skip this .h and associated .cc file while reviewing?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/validate_constraint_gradients.h` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW2rE_R8-ip8snCZY5B:-NW3liRhEzhf2_SnkDrt:b-fdoni0) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/validate_constraint_gradients.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Does that mean I should skip this .h and associated .cc file while reviewing?
</blockquote></details>

feel free to do so. If for some reason the previous PR get blocked, then I''ll let you know.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: 
I sprinkled a few minor comments. Probably worth resolving those before assigning platform.
-(component: multibody plant) as the component tags are reserved for issues.

> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-:-NW3rfv77r6o_PSwh6Cn:bj8ktt7)* status: 10 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 254 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3fOrk1R_u8Yiwd7PR:-NW3fOrk1R_u8Yiwd7PS:b-fujt2y) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_constraint.h#L254)):*
> ```objc
>    of the cost, impulses and Hessian into `data` to be reused.
>    @pre vc.size() equals num_constraint_equations().
>    @pre data does not equal nullptr. */
> ```

BTW, for these functions that take AbstractValues as parameters, an implicit pre-condition is that the values wrapped by AbstractValue is consistent with the concrete subclass that's used to process the type-erased value. An exception is thrown if there's a mismatch.

Since all these are internal, I'll simply leave this for your consideration as a BTW.
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3KKs26RIkPPH-XNql:-NW3KKs26RIkPPH-XNqm:b-jtxnho) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.h#L16)):*
> ```objc
> 
> /* Structure to store data needed for SapLimitConstraint computations. */
> template <typename T>
> ```

BTW, could you add a note on the accepted template parameters?
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3KPbc53Tv5Plz_yRd:-NW3KPbc53Tv5Plz_yRe:b3hzgqo) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.h#L22)):*
> ```objc
> 
>   /* Constructs data for a SapLimitConstraint.
>      @param R Regularization parameters.
> ```

BTW, is it worth adding a reference for where one can find the definition/meaning of regularization parameters and bias terms?
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3Kb1n3O7BXZOnCNNX:-NW3Kb1n3O7BXZOnCNNY:b-ouui9e) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.h#L24)):*
> ```objc
>      @param R Regularization parameters.
>      @param v_hat Bias term. */
>   SapLimitConstraintData(VectorX<T> R, VectorX<T> v_hat) {
> ```

minor, it's weird to see parameters passed by value but not moved from. Do you intend to move from them but forgot?
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3Ku2g9_V_P4PEJE47:-NW3Ku2g9_V_P4PEJE48:b-4wd534) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.h#L28)):*
> ```objc
>     parameters_.R.resize(nk);
>     parameters_.R_inv.resize(nk);
>     parameters_.v_hat.resize(nk);
> ```

BTW these resizes seems unnecessary to me.



_Code quote:_
```objc
    parameters_.R.resize(nk);
    parameters_.R_inv.resize(nk);
    parameters_.v_hat.resize(nk);
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3La_x3B2kHBwINQob:-NW3La_x3B2kHBwINQoc:b-l7uk0n) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.h#L71)):*
> ```objc
>   VectorX<T> y_;      // Un-projected impulse y = −R⁻¹⋅(vc−v̂)
>   VectorX<T> gamma_;  // Impulse.
>   MatrixX<T> dPdy_;   // Gradient of the projection γ = P(y) w.r.t. y.
> ```

BTW reorganizing the comment a bit might make parsing easier



_Suggestion:_
```objc
  VectorX<T> gamma_;  // Projected impulse γ = P(y).
  MatrixX<T> dPdy_;   // Gradient of the projection P(y) w.r.t. y.
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.cc` line 130 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3e_di5Jb_APHOvFLq:-NW3e_di5Jb_APHOvFLr:bcuxkf6) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.cc#L130)):*
> ```cpp
>   // Make data.
>   SapLimitConstraintData<T> data(std::move(R), std::move(v_hat));
>   return AbstractValue::Make(data);
> ```

minor, should we move construct the data instead? See slack discussion: https://drakedevelopers.slack.com/archives/C2CHRT98E/p1684187239037089
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.cc` line 174 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3l9EB2MSHhpUZbv76:-NW3l9EB2MSHhpUZbv77:b-g6xi47) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.cc#L174)):*
> ```cpp
>   if (ql > -kInf) {
>     if (y(i) > 0.0) (*G)(i, i) = R_inv(i);
>     i++;
> ```

nit use preincrement per GSG



_Suggestion:_
```cpp
 ++i;
```
___
*[`multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc` line 222 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3obwT7p6tnW0hec1J:-NW3obwT7p6tnW0hec1K:bit1z4h) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc#L222)):*
> ```cpp
>       abstract_data->get_value<SapLimitConstraintData<AutoDiffXd>>();
> 
>   // Helper to make a new vector v such that v < x componentwise.
> ```

BTW this comment isn't strictly true when a component of x is 0.
___
*[`multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc` line 270 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3qWMQ3UZChI_hU1tf:-NW3qWMR39NEn1xGsCai:b6lb4r) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc#L270)):*
> ```cpp
>     const VectorXd gamma = validate_gradients(vc);
>     // We expect non-zero impulses.
>     EXPECT_TRUE((gamma.array() > 0.0).all());
> ```

BTW, related to the comment above: this might fail if the position is right at the boundary of limit.

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation please.

> Reviewed 1 of 8 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-:-NW8VRTL5nJLRCz4r_MX:b-w5mc00)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 255 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW8UXRnCOG8LoObGgS9:-NW8UXRnCOG8LoObGgSA:b-amp4ov) ([raw file](https://github.com/RobotLocomotion/drake/blob/64b20b03ca76af9fa9a67a7618413ad62df69189/multibody/contact_solvers/sap/sap_constraint.h#L255)):*
> ```objc
>    @pre vc.size() equals num_constraint_equations().
>    @pre data does not equal nullptr.
>    @pre data was created via MakeData() on `this` class and therefore the type
> ```

BTW Do you mean the `SapConstraint` "object" instead of the "class"?



_Code quote:_
```objc
class
```
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.cc` line 130 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3e_di5Jb_APHOvFLq:-NW8UuJv7HqqG4VCj7hH:bcxeg6q) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.cc#L130)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would love to do that! Ideally I would love the rvalue signature. Lets see what others have to say in that discussion, I could push the feature myself.
</blockquote></details>

Consider putting a TODO here for reminder if we want to come back to improve on this later.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nit

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-:-NW9lKgy9u5j4aPLQg98:b4xzb62)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW8hH4T3F5aA4VO5AXW:-NW8hH4T3F5aA4VO5AXX:b8fqx4l) ([raw file](https://github.com/RobotLocomotion/drake/blob/64b20b03ca76af9fa9a67a7618413ad62df69189/multibody/contact_solvers/sap/sap_limit_constraint.h#L19)):*
> ```objc
>  @tparam_nonsymbolic_scalar */
> template <typename T>
> struct SapLimitConstraintData {
> ```

nit I'm curious why this is `struct` and not `class`. At this point with methods, access control, value semantics, etc., I don't see why we wouldn't say `class`.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452)* status: needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_limit_constraint.h` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW8hH4T3F5aA4VO5AXW:-NWCkjUA70kc_BLEs6sX:b4bsh8k) ([raw file](https://github.com/RobotLocomotion/drake/blob/64b20b03ca76af9fa9a67a7618413ad62df69189/multibody/contact_solvers/sap/sap_limit_constraint.h#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I'm curious why this is `struct` and not `class`. At this point with methods, access control, value semantics, etc., I don't see why we wouldn't say `class`.
</blockquote></details>

ah... it's the latest in the C++39 standard (yet to be released) where you write your prototype and GPT-51 fixes it for you
___
*[`multibody/contact_solvers/sap/sap_limit_constraint.cc` line 130 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-NW3e_di5Jb_APHOvFLq:-NWCqcA74YWpKzzJEIGU:b-hqqsfy) ([raw file](https://github.com/RobotLocomotion/drake/blob/00d4af296fbda181e5facc60ada02cebaea44490/multibody/contact_solvers/sap/sap_limit_constraint.cc#L130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Consider putting a TODO here for reminder if we want to come back to improve on this later.
</blockquote></details>

See if you like this solution better.

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri apparently not assigned before?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19452#-:-NWDKGAU7rRkK3yBdVvJ:brx74wz)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
