### PR TITLE
Add RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld().

### PR DESCRIPTION
**Pull request by mitiguy**
Add RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld() towards adding the missing method Multibody::CalcCenterOfMassTranslationalAcceleration() to resolve issue #14269.  To see how this PR fits into bigger plan, see PR #21519.

Note: The related velocity function RigidBody::CalcCenterOfMassTranslationalVelocityInWorld() does not have a python binding.   For consistency, it seems reasonable that neither should have a Python binding or both should.  If it makes sense for these to have Python bindings (and release notes), we'll proceed in a subsequent PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
Feature pass done, PTAL.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O05H9a25oR9VdoYuFhu:b-7uzwif)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O059IF78Tbk1vylzAf-:-O059IF78Tbk1vylzAf0:b-wn863g) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L43)):*
> ```cpp
> // Note: The applied forces (such as gravity) on this system are irrelevant as
> // this text fixture is currently only used to test kinematics for an
> // instantaneous given state.  The mass/inertia properties of this plant are
> ```

It seems like this fixture (and the test name) is maybe outgrowing it's original purpose since we're not just doing kinematics testing here. We should update this comment at least, and maybe consider a rename for the test.



_Code quote:_
```cpp
// Note: The applied forces (such as gravity) on this system are irrelevant as
// this text fixture is currently only used to test kinematics for an
// instantaneous given state.  The mass/inertia properties of this plant are
```
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O053DFb9HfDtmYkS7-s:-O053DFb9HfDtmYkS7-t:bavm9x0) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L145)):*
> ```cpp
>   // Calculate and return [ẇAz, ẇBz], the time derivative of [wAz, wBz].
>   Vector2<double> CalcVdotForNoAppliedForces() {
>     // The calculation below was generated by MotionGenesis.
> ```

I think having the analytic dynamics coming from the symbolic generation is very cool, but I'm wondering if it's the best choice for this test fixture. 

1) There is an immediate maintainability issue because most developers will not have access to MotionGenesis, making it difficult to regenerate these if the setup of the fixture changes. And even if the symbolic expressions for the dynamics were deemed necessary, they could be easily regenerated with a `MultibodyPlant<symbolic::Expression>` version of this system (with gravity turned off).

2) We could just turn gravity off in `plant_` and just eval the `generalized_acceleration` output port of the plant to get Vdot, also eliminating the maintenance requirement on this calculation.



_Code quote:_
```cpp
    // The calculation below was generated by MotionGenesis.
```
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 466 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O05BTycD6RX2BSIaopv:-O05BTycD6RX2BSIaopw:bczdnri) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L466)):*
> ```cpp
>   // Calculate Bcm's spatial acceleration in world W, expressed in world W.
>   const Vector3<double> a_WBcm_W =
>       bodyB_->CalcCenterOfMassTranslationalAccelerationInWorld(*context_);
> ```

Since we are only considering CoM's that are coincident with body origins, we aren't really getting full coverage in testing `CalcCenterOfMassTranslationalAccelerationInWorld()`.

This test wouldn't detect a sign error or expressed-in error in computing `p_BoBcm_W` for instance. You can verify this by setting 

```
p_BoBcm_W = p_BoBcm_B
```

in `RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld()` and this test will still pass. Or even a typo like:

```
  const Vector3<T>& w_WB_W = V_WBo_W.translational();
```

will still pass this test.

I think we need to make body origins and CoM points non-coincident to really give this test some legs.



_Code quote:_
```cpp
  // Point Bcm is link B's center of mass, colocated with Bo (B's centroid).
  // Calculate Bcm's spatial acceleration in world W, expressed in world W.
  const Vector3<double> a_WBcm_W =
      bodyB_->CalcCenterOfMassTranslationalAccelerationInWorld(*context_);
```

**Review by mitiguy — COMMENTED** [review]
Thanks Joe.  Changes made.   PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O0kvUtt572H_FS9znjk:b-kos5fp)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O059IF78Tbk1vylzAf-:-O0kK2DS2wZ0-ri3PXoE:ba5pl7j) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L43)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

It seems like this fixture (and the test name) is maybe outgrowing it's original purpose since we're not just doing kinematics testing here. We should update this comment at least, and maybe consider a rename for the test.
</blockquote></details>

Done.  Comment updated.  Perhaps sufficient?
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O053DFb9HfDtmYkS7-s:-O0kfakdC2OH-Z0QSlm7:b2sfqae) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L145)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I think having the analytic dynamics coming from the symbolic generation is very cool, but I'm wondering if it's the best choice for this test fixture. 

1) There is an immediate maintainability issue because most developers will not have access to MotionGenesis, making it difficult to regenerate these if the setup of the fixture changes. And even if the symbolic expressions for the dynamics were deemed necessary, they could be easily regenerated with a `MultibodyPlant<symbolic::Expression>` version of this system (with gravity turned off).

2) We could just turn gravity off in `plant_` and just eval the `generalized_acceleration` output port of the plant to get Vdot, also eliminating the maintenance requirement on this calculation.
</blockquote></details>

Done.  I simplified the problem so the analysis could be done by-hand and also verified using your suggestion in #2.  Let me know if you prefer to remove the by-hand analysis.
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 466 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O05BTycD6RX2BSIaopv:-O0kg1ba4YF_FYolb_0t:btjtu71) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L466)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Since we are only considering CoM's that are coincident with body origins, we aren't really getting full coverage in testing `CalcCenterOfMassTranslationalAccelerationInWorld()`.

This test wouldn't detect a sign error or expressed-in error in computing `p_BoBcm_W` for instance. You can verify this by setting 

```
p_BoBcm_W = p_BoBcm_B
```

in `RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld()` and this test will still pass. Or even a typo like:

```
  const Vector3<T>& w_WB_W = V_WBo_W.translational();
```

will still pass this test.

I think we need to make body origins and CoM points non-coincident to really give this test some legs.
</blockquote></details>

Done.  I moved the center of mass to the distal end of each link.  Let me know what you think.

**Review by mitiguy — COMMENTED** [review]
@joemasterjohn  PR #21599 seems ready for your review.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O0p99l21m3OujJbJ-oT:b-1esu6z)* status: 3 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature, thanks for the changes Paul! +@rpoyner-tri for platform review, please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O0pMt-10GwN4pUptNzV:bfud4z0)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O059IF78Tbk1vylzAf-:-O0pMDdB4vzwJBtp9oDc:b-vs1prh) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L43)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  Comment updated.  Perhaps sufficient?
</blockquote></details>

Looks good!
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O053DFb9HfDtmYkS7-s:-O0pMN9OBSmRbw3ns4DV:bud05a0) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L145)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  I simplified the problem so the analysis could be done by-hand and also verified using your suggestion in #2.  Let me know if you prefer to remove the by-hand analysis.
</blockquote></details>

OK thanks, I still like having the by-hand math there as a sanity check.
___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 466 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O05BTycD6RX2BSIaopv:-O0pMonE7bHxw_XBKd9C:b-g1it74) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cbec0f01e28736d3be8bf6fcb78fb21a4720d80/multibody/plant/test/multibody_plant_kinematics_test.cc#L466)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  I moved the center of mass to the distal end of each link.  Let me know what you think.
</blockquote></details>

This is great, thanks!

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O1I8oNIDYh5-l_MBnb-:bb7ao1f)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_kinematics_test.cc` line 473 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-O1I6xbcBVYm7SUFsTLh:-O1I6xbcBVYm7SUFsTLi:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/bcf216531ffc5af07d672538156bef2828a1fb14/multibody/plant/test/multibody_plant_kinematics_test.cc#L473)):*
> ```cpp
>   // Verify results from CalcCenterOfMassTranslationalAccelerationInWorld()
>   // match test_utilities::CalcSpatialAccelerationViaAutomaticDifferentiation().
>   const Vector3<double> p_AoAcm_A = p_AoAf_A_;  // Af is colocated with Acm.
> ```

typo



_Suggestion:_
```cpp
collocated
```

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21599#-:-O1JRDYR6zoUJSi6_WU8:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn

**Comment by jwnimmer-tri** [comment]
The first line (subject line) of a commit message should be less than 70 characters, and should not mention the issue number.

**Pull request merged**
