### PR TITLE
Split MinimumDistanceConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Create MinimumDistanceLowerBoundConstraint and MinimumDistanceUpperBoundConstraint. They should use different influence_distance.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
To reviewers: sorry for the giant PR, but this PR doesn't contain a new feature. It splits the MinimumDistanceConstraint into two classes, MinimumDistanceLowerBoundConstraint and MinimumDistanceUpperBoundConstraint. I also split the their test files.

+@calderpg-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfIhadDEoIeH34Q8mtZ:beb293t)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfMXiAi9AZ-oTY_gsz_:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-NfMUXt21MB-mGmg2RGo:-NfMUXt21MB-mGmg2RGp:b4uxksk) ([raw file](https://github.com/RobotLocomotion/drake/blob/63d236bce4cd76c9c55d7817831ac1ea8c21ca7e/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L84)):*
> ```cpp
>                   Eigen::Matrix<AutoDiffXd, kNumPositionsForTwoFreeBodies, 1>*
>                       q_autodiff) const {
>     const Eigen::Quaterniond sphere1_quaternion(1, 0, 0, 0);
> ```

nit It might be clearer for these to be written as `const auto sphere1_quaternion = Eigen::Quaterniond::Identity();` rather than providing the identity quaternion by hand

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfMb0zv3Cj2J8Hg4Wdd:buer3go)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 85 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-NfNYvPo6oC8txDRv6kJ:-NfNYvPo6oC8txDRv6kK:b6l1fmo) ([raw file](https://github.com/RobotLocomotion/drake/blob/efc6fed41d18a4483d91262bc22de3a38dca538c/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L85)):*
> ```cpp
>                       q_autodiff) const {
>     const Eigen::Quaterniond sphere1_quaternion = Eigen::Quaterniond::Identity();
>     const Eigen::Quaterniond sphere2_quaternion = Eigen::Quaterniond::Identity();
> ```

minor: CI is failing because these two lines are too long.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor comments

Per f2f, if feasible please split each constraint into its own .h and .cc. I think it still makes sense to combine the unit tests into a single file though since they share much code and need parallel lower/upper tests.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfNlFt3DL-ZZFG94yzK:b-co0v46)* status: 4 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 394 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-NfNhdKY92AHlJqJM4mP:-NfNhdKY92AHlJqJM4mQ:b-8hrpas) ([raw file](https://github.com/RobotLocomotion/drake/blob/efc6fed41d18a4483d91262bc22de3a38dca538c/multibody/inverse_kinematics/minimum_distance_constraint.h#L394)):*
> ```objc
> 
>   const planning::CollisionChecker* collision_checker_;
>   planning::CollisionCheckerContext* collision_checker_context_;
> ```

nit: should initialize these pointers to null here with `{}`
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 426 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-NfNZ_-hAeQEQraIAJ1n:-NfNZ_-hAeQEQraIAJ1o:b-s59ixg) ([raw file](https://github.com/RobotLocomotion/drake/blob/efc6fed41d18a4483d91262bc22de3a38dca538c/multibody/inverse_kinematics/minimum_distance_constraint.h#L426)):*
> ```objc
>   /** Constructs a MinimumDistanceUpperBoundConstraint.
>   @param plant The multibody system on which the constraint will be evaluated.
>   @param minimum_distance_upper The upper bound minimum signed
> ```

BTW consider upper bound **(ub)** to connect with the math above (as you did for lb)
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 536 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-NfNhl9C7pl3r7oXNp6Y:-NfNhl9C7pl3r7oXNp6Z:b-8hrpas) ([raw file](https://github.com/RobotLocomotion/drake/blob/efc6fed41d18a4483d91262bc22de3a38dca538c/multibody/inverse_kinematics/minimum_distance_constraint.h#L536)):*
> ```objc
> 
>   const planning::CollisionChecker* collision_checker_;
>   planning::CollisionCheckerContext* collision_checker_context_;
> ```

nit: should initialize these pointers to null here with `{}`

**Review by hongkai-dai — COMMENTED** [review]
Done. I have split minimum_distance_constraint.h/cc into separate files.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfO6K0GE9shkrFwd9dx:bhxtnmv)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Great, thanks Hongkai. One more request -- if you haven't already, please generate the doxygen and see if it comes out as you expected. Or I can do that in the morning.

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfP9eQ_AEEvVrjGEZBT:b-xv667d)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Good call. I have checked the generated doxygen and it looks good to me.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfPEVYX1eChKX1mQ2YD:bl79ax0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
The `using` statements in the two new headers are pretty weird, and now there are three copies of those aliases with identical names and documentation, across three different IK header files?  I don't see any obvious reason why we're copying all of that around, instead of just saying `solvers::MinimumValuePenaltyFunction penalty_function = {},` in the function signature.  Probably deserves a second look.

**Review by sherm1 — COMMENTED** [review]
Hongkai is planning to deprecate and remove the original MinimumDistanceConstraint after this lands, so there would only be two copies of that documentation. However, I agree that it would be better in one place with a reference to it in the documentation for the two new constraints.

How about moving the `solver::` type declarations (currently at the top of the to-be-deprecated minimum_value_constraint.h file) to distant_constraint_utilities.h, documenting only once there?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfR_yRq04XunaHQ26sN:b-lmfnrf)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
> How about moving the solver:: type declarations (currently at the top of the to-be-deprecated minimum_value_constraint.h file) to distant_constraint_utilities.h, documenting only once there?

That solves the problem of two copies, but does not explain why we need to have a `using` statement in a header file.  Why can't we just keep the stuff in `solvers` and cite it from there?  The primary defect is the using statement itself.

**Review by hongkai-dai — COMMENTED** [review]
Done. I removed the using statement and used solvers::MinimumValuePenaltyFunction. Thanks for looking into this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfReq_98rcstLlBQOwB:bqg0p31)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
LGTM

**Review by sherm1 — COMMENTED** [review]
:+1: 

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20266#-:-NfRjrrZ1zjB21k7mt0e:b-8fx2u7)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
