### PR TITLE
Fix acrobot traj opt

### LINKED ISSUE #6840: Acrobot swing up example with direct collocation trajectory generation broken
All acrobot examples as of May 4th worked fine. Now I upgraded to a commit as of this morning and rebuild everything. While I can get the basic examples with trajectory optimization to run and visualize, I can not get the trajectory optimization to work anymore: `acrobot_run_swing_up_traj_optimization.cc`
The default values are `kTrajectoryTimeLowerBound=2` and `kTrajectoryTimeUpperBound=10`, those previously generated a prolonged swing up with a couple back and fourths and overshoots before it would go upright: [Video of previously observed behaviour](https://www.dropbox.com/s/5f5i9uqiqoan43p/output_low2_up10.mp4?dl=0). Now, it compiles and runs with ipopt, but it only generates a trajectory that runs up to time `t = kTrajectoryTimeUpperBound` and it does not visualize the trajectory to drake_visualizer. It only shows the acrobot at the downhanging configuration, but it does not visualize a swing up motion. 
Also, if I adjust the lower and upper bounds for the direct collocation, it results in errors for parameter ranges that previously found feasible trajectories.  `kTrajectoryTimeLowerBound=1` and `kTrajectoryTimeUpperBound=5` would previously find a solution that requires only a single back and forth before upright, [Video of faster swing up](https://www.dropbox.com/s/3bvt7f7scmx4gsf/output_low2_up5.mp4?dl=0). Now, running it with those parameters now results in an error.
Naveen also confirmed that it is not working for both Ipopt and Snopt.
I am running `git bisect` to find the commit that broke this feature, will report soon the result. 

[Last Good Commit](https://github.com/RobotLocomotion/drake/commit/54867692bee6d6e8156592b7f375711694106e49)
> Update to address UBsan flag in implicit Euler integrator. (#6591)

[Culprit Commit](https://github.com/RobotLocomotion/drake/commit/f0491e77cda77194c99c1ccd30f878f453c10fa5
) by Evan Drumwright <edrumwri@hotmail.com> on Wed Jul 19 13:19:57 2017 -0500
> Fixes issue with integrators limiting rate of simulator time advancement even when no continuous state is present. (#6593)

Related to #6619, proper unit tests are missing for all Acrobot examples. This swing up example was introduced here:  #5093

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fixes #6840 and #6842

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6845)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrYEEbAxB5NKM7LUPWi:bs3tquo)*

**Comment by jwnimmer-tri** [comment]
I can do platform review; probably find some other interested party for feature review?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrYFRZ9fPYSLWoVyKsB:b-vva8u9) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
> ```cpp
>   systems::Simulator<double> simulator(*diagram);
> 
>   simulator.set_target_realtime_rate(1);
> ```

How long does this take?  If it's an annoying number of seconds, then ideally the unit test would play faster-than-realtime by default, instead of sleeping.

Perhaps instead of porting to gtest right now, do you just want `add_test_rule` on the `drake_cc_binary`?  Or perhaps keep the gtest argument parsing intact, and have Bazel run the test with `args=['--realtime_factor=0.0']`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrYF8SZ-Vp8s2odMhK2:bhmk7l2)*

**Comment by hongkai-dai** [comment]
+@naveenoid for feature review please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrYQ4Uw7aqPMMFMRmWG:b-jlfufc)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrYQCXrYmG3_wsvcyLq:b-xnsj1g) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

How long does this take?  If it's an annoying number of seconds, then ideally the unit test would play faster-than-realtime by default, instead of sleeping.

Perhaps instead of porting to gtest right now, do you just want `add_test_rule` on the `drake_cc_binary`?  Or perhaps keep the gtest argument parsing intact, and have Bazel run the test with `args=['--realtime_factor=0.0']`?
</blockquote></details>

It actually just plays back the state trajectory, so it is really quick, just a few seconds. Should we add `args=['--reltime_factor=0.0']` for this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-Kr_X6S2pPgGROlnmNZt:b-j6tfn9) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It actually just plays back the state trajectory, so it is really quick, just a few seconds. Should we add `args=['--reltime_factor=0.0']` for this case?
</blockquote></details>

OK I wasn't sure how long the trajectory was; a few seconds is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by amcastro-tri** [comment]
Great idea making this a unit test @hongkai-dai! and a good find that we switched the default constructor, I don't know if I had realized that myself. 
Please see note below regarding #6846.
+@amcastro-tri 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-Kra4h76q1q5myt3EjKZ:br2e3n) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
> ```cpp
>   simulator.set_target_realtime_rate(1);
>   simulator.Initialize();
>   simulator.StepTo(kTrajectoryTimeUpperBound);
> ```

Making this a unit test is great. But now we know this was so brittle lets add some `EXPECT_SOMETHING` to make sure we don't break it in the future. As is, simulation still doesn't run correctly due to #6846.
Once that's fixed, I'd add `EXPECT_EQ` for:
```
simulator.get_context().get_time());
simulator.get_num_steps_taken());
simulator.get_integrator()->supports_error_estimation());
simulator.get_integrator()->get_fixed_step_mode());
simulator.get_integrator()->get_maximum_step_size());
simulator.get_integrator()->get_largest_step_size_taken());
simulator.get_integrator()->get_num_steps_taken());
simulator.get_integrator()->get_num_step_shrinkages_from_error_control());
simulator.get_integrator()->get_num_step_shrinkages_from_substep_failures());
```
Also, probably a good idea to add `EXPECT_NEAR` for the polynomial coefficients in `pp_xtraj` so that we make sure future changes do not break this functionality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-Kra4HmhZ2wkv8FzlG4-:by5jk6x)*

**Comment by tarquasso** [comment]
I agree with @jwnimmer-tri to add `gflags` back in and use `args=['--realtime_factor=0.0']` for the googletest case, this way it does not hold up the unit tests too much (it takes around 4.7 seconds to simulate).
As @amcastro-tri proposes, adding `EXPECT_EQ` and `EXPECT_NEAR` checks makes sense!

Question: If we move `acrobot_run_swing_up_traj_optimization.cc` into the `test` folder and change it to a `drake_cc_googletest`, can we still run it like a binary with `bazel run` and how would we get the visualization from that?

**Comment by jwnimmer-tri** [comment]
*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KraFTMMUi9Wt_UyOWif:b-za1v7b) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Making this a unit test is great. But now we know this was so brittle lets add some `EXPECT_SOMETHING` to make sure we don't break it in the future. As is, simulation still doesn't run correctly due to #6846.
Once that's fixed, I'd add `EXPECT_EQ` for:
```
simulator.get_context().get_time());
simulator.get_num_steps_taken());
simulator.get_integrator()->supports_error_estimation());
simulator.get_integrator()->get_fixed_step_mode());
simulator.get_integrator()->get_maximum_step_size());
simulator.get_integrator()->get_largest_step_size_taken());
simulator.get_integrator()->get_num_steps_taken());
simulator.get_integrator()->get_num_step_shrinkages_from_error_control());
simulator.get_integrator()->get_num_step_shrinkages_from_substep_failures());
```
Also, probably a good idea to add `EXPECT_NEAR` for the polynomial coefficients in `pp_xtraj` so that we make sure future changes do not break this functionality.
</blockquote></details>

We have `kSolutionFound` in an EXPECT above.  This PR was intended to be as minimal as practical to unbreak master.  There is already a github issue open that we need to write real unit tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by jwnimmer-tri** [comment]
> ... can we still run it like a binary with `bazel run` and how would we get the visualization from that?

I haven't tested it locally, but from reading the code this PR makes no changed to either of those... you still `bazel run` the same label, and the visualization still happens exactly as before.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KraFh3k7cB5SDhCmgZg:b-tf6wac)*

**Comment by tarquasso** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KraGYTYg79VQ9neacCh:b-359zcq) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We have `kSolutionFound` in an EXPECT above.  This PR was intended to be as minimal as practical to unbreak master.  There is already a github issue open that we need to write real unit tests.
</blockquote></details>

with just `EXPECT_EQ(result, SolutionResult::kSolutionFound)` we are not be able to catch the error, since #6842 and #6840 were not detectable with a similar check: while it was not a unit test, the original code would return an error if no solution was found. Optimizer Ipopt still found a solution, even though it was garbage (only two steps). I would vote for adding at least some of those additional tests that @amcastro-tri proposes, keeping thios commit still somewhat minimal while ensuring any future changes that break this functionality are caught quicker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KraIk2Zys9OallXxQCv:b-vtwk77) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, tarquasso (Robert Katzschmann) wrote…</i></summary><blockquote>

with just `EXPECT_EQ(result, SolutionResult::kSolutionFound)` we are not be able to catch the error, since #6842 and #6840 were not detectable with a similar check: while it was not a unit test, the original code would return an error if no solution was found. Optimizer Ipopt still found a solution, even though it was garbage (only two steps). I would vote for adding at least some of those additional tests that @amcastro-tri proposes, keeping thios commit still somewhat minimal while ensuring any future changes that break this functionality are caught quicker.
</blockquote></details>

OK I'll let the author-feature team shave this yak however they like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KraZGoejSVQFeMXvEre:bv3ghjh) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
> since #6842 and #6840 were not detectable with a similar check

I think we can detect the error with `EXPECT_EQ(result, SolutionResult::kSolutionFound)`. In #6842 and #6840, the trajectory optimization will fail to find a solution, and the result would be `SolutionResult::kInfeasibleConstraints`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by tarquasso** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KrauqKltG7S3yZ1hBeP:b959e82) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> since #6842 and #6840 were not detectable with a similar check

I think we can detect the error with `EXPECT_EQ(result, SolutionResult::kSolutionFound)`. In #6842 and #6840, the trajectory optimization will fail to find a solution, and the result would be `SolutionResult::kInfeasibleConstraints`.
</blockquote></details>

Ok, if that is the case, i am happy with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by naveenoid** [comment]
aside from a minor BTW :lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrbAaehTOYYnt-e4tQX:-KrbAaehTOYYnt-e4tQY:b-scs4hp) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L32)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(AcrobotTest, SwingUpTrajectoryOptimization) {
> ```

BTW: A comment somewhere in here stating that this test is expected to run with the default solver (ipopt) would be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrbBFD6eqny1NUApU-j:b5uhr2y)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrbBaLWwoNUmbgOtset:bnfp4nl)*

**Comment by tarquasso** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrbD2CLfcTPeTR5lpvS:bnfp4nl)*

**Comment by amcastro-tri** [comment]
This :lgtm: to me. I just have a question regarding if we should unit test that we actually do use ipopt to ensure the unit test's results do not change in the future. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrbAaehTOYYnt-e4tQX:-KrbHLOWF2Moxe9AAqR7:b36mlk0) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L32)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: A comment somewhere in here stating that this test is expected to run with the default solver (ipopt) would be useful.
</blockquote></details>

Should we unit test that the solver being used is ipopt? if we do that then we could add tests on the polynomial coefficients and expect them not to change unless something clearly went wrong.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrbI5gRrYcc2p_owejr:brvs4pi) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I wasn't sure how long the trajectory was; a few seconds is fine.
</blockquote></details>

BTW it should take 10 seconds to be exact, but since this is now broken (see #6846) the "simulation" (actually just a playback as @hongkai-dai observes) takes zero seconds (no time steps are taken). The time spent in this case reduces to the trajectory optimization.  So when we fix this (later today, PR coming) it'd probably make sense to go back to `args=['--reltime_factor=0.0']`. I'd say yes @hongkai-dai, please go back to `args=['--reltime_factor=0.0']` if that's not a hole lot of trouble, otherwise I'll have to revert it in the fix PR.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KrbHeFbNw2CBj9GxdHX:b-l2qcli) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, tarquasso (Robert Katzschmann) wrote…</i></summary><blockquote>

Ok, if that is the case, i am happy with it.
</blockquote></details>

There are two problems here @hongkai-dai, see #6842. One is the one you are fixing by going back to the original plant with the acrobot's defaults, the second one is that the simulator in this example is running zero time steps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrbJ6NyDvloKLRxsnlR:b8ujtx0)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KrbLEx0G6DYWlA0DDvW:bhbl3d8) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

There are two problems here @hongkai-dai, see #6842. One is the one you are fixing by going back to the original plant with the acrobot's defaults, the second one is that the simulator in this example is running zero time steps.
</blockquote></details>

Yes. I agree there are two problems. I am not fixing the second problem. I am just saying that with this fix, we can catch the error, that the trajectory optimization fails. This error cannot be caught before, without `EXPECT_EQ(result, SolutionResult::kSolutionFound)`. So I think it still makes sense to bring in this PR.

Thanks for looking into the integration error. I think that can be included in a separate PR, what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Kra4h76q1q5myt3EjKY:-KrbOLxg5GZxnnPKvUNY:b-5ach76) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes. I agree there are two problems. I am not fixing the second problem. I am just saying that with this fix, we can catch the error, that the trajectory optimization fails. This error cannot be caught before, without `EXPECT_EQ(result, SolutionResult::kSolutionFound)`. So I think it still makes sense to bring in this PR.

Thanks for looking into the integration error. I think that can be included in a separate PR, what do you think?
</blockquote></details>

absolutely agree. That is why I marked myself satisfied here. I will push that ASAP.
What do you think about the ipopt comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by amcastro-tri** [comment]
I don't think it makes sense for me to make another PR, the fix is actually pretty simple. See commit [here](https://github.com/amcastro-tri/drake/commit/9b2a33ea981a5c61317292e280a16994a20073d2).  @hongkai-dai, would you add those few lines to this PR please? that fixes the problem with the drake visualizer not showing anything.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-:-KrbU2j7ucw2qwOxfJrV:b-h53rej)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrbAaehTOYYnt-e4tQX:-Krb_UdYoZd2QBSvQjnq:b-fh53cn) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L32)):*
> BTW: A comment somewhere in here stating that this test is expected to run with the default solver (ipopt) would be useful.

Both IPOPT and SNOPT work for this test. Do we want to restrict to IPOPT only?

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrbaXBwoL58El4HDeoj:b-qiedr9) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW it should take 10 seconds to be exact, but since this is now broken (see #6846) the "simulation" (actually just a playback as @hongkai-dai observes) takes zero seconds (no time steps are taken). The time spent in this case reduces to the trajectory optimization.  So when we fix this (later today, PR coming) it'd probably make sense to go back to `args=['--reltime_factor=0.0']`. I'd say yes @hongkai-dai, please go back to `args=['--reltime_factor=0.0']` if that's not a hole lot of trouble, otherwise I'll have to revert it in the fix PR.
</blockquote></details>

Done. I added `args=['--reltime_factor=0.0']` to the BUILD file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 210 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Krbbgmn37eesbV8Hz7f:-Krbbgmn37eesbV8Hz7g:bi23frd) ([raw file](https://github.com/robotlocomotion/drake/blob/788c881d5da7a4bfdeee626e9f0b021632367e77/drake/examples/acrobot/BUILD#L210)):*
> ```Python
> drake_cc_googletest(
>     name = "acrobot_urdf_dynamics_test",
>     args = ["--reltime_factor=0.0"],
> ```

This line has no effect, because this PR removes such an option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrbAaehTOYYnt-e4tQX:-KrbdyFAWewUjRnIIZzO:bjkcpll) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L32)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> BTW: A comment somewhere in here stating that this test is expected to run with the default solver (ipopt) would be useful.

Both IPOPT and SNOPT work for this test. Do we want to restrict to IPOPT only?
</blockquote></details>

woops, good point. Per Slack discussion then the plan is to check the end time is withing the user specified bounds and, possibly in this same PR, check for the satisfaction of the constraints. Marking myself satisfied on this regard, way more than what I was asking.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrbeH18-cpWMDYS2rA4:bwy0q65) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added `args=['--reltime_factor=0.0']` to the BUILD file.
</blockquote></details>

As @jwnimmer-tri pointed out, `FLAGS_realtime_factor` would be needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 210 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-Krbbgmn37eesbV8Hz7f:-KrbyHudddU_FztMeFuk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/788c881d5da7a4bfdeee626e9f0b021632367e77/drake/examples/acrobot/BUILD#L210)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This line has no effect, because this PR removes such an option.
</blockquote></details>

Done.

---

*[drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6845#-KrYFRZ9fPYSLWoVyKsA:-KrbyEmmmDwLjWVD16cl:b-kwvips) ([raw file](https://github.com/robotlocomotion/drake/blob/143133048204d8bdb9de71e65312b5aaf632f8ec/drake/examples/acrobot/test/acrobot_run_swing_up_traj_optimization.cc#L77)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

As @jwnimmer-tri pointed out, `FLAGS_realtime_factor` would be needed.
</blockquote></details>

Done. Thanks for pointing that out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6845)*

**Pull request merged**
