### PR TITLE
[fem] Modify NewmarkScheme to allow velocity as the unknown variable

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-Mgn_7tN87HH3hU1xb_c:b-hq4nxl)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri. Review done. Just a few comments. :lgtm: 

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-MhERcA977uOvUrT82A7:b-yxq83h)* status: 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEJz2234HexfQLqei8:-MhEJz2388vj3IyNzlDd:b-67v70q) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/newmark_scheme.h#L33)):*
> ```objc
>   /* Constructs a Newmark scheme with the provided timestep, `gamma` and `beta`.
>    @pre dt > 0.
>    @pre 0.5 <= gamma <= 1.
> ```

nit, In principle I could take gamma=0 for a fully explicit scheme. However stability analysis tells me I should probably make gamma>1/2.
Probably worth saying something in the class's documentation about the limits of stability, at least if only for linear elasticity.
___
*[multibody/fixed_fem/dev/velocity_newmark_scheme.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhELRhT38z74H3-QtOu:-MhELRhU7ty2KGP2euJq:b-did3wf) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/velocity_newmark_scheme.h#L12)):*
> ```objc
> 
> /* Implements the interface StateUpdater with Newmark-beta time integration
>  scheme with velocity being the known variable. Given the value for the current
> ```

nit, known -> unknown? 
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 207 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEPNbd7Mf13QkZvDSx:-MhEPNbd7Mf13QkZvDSy:bjfgsd1) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L207)):*
> ```cpp
>   EXPECT_EQ(current_positions[0].size(), kNumVertices * 3);
> 
>   const Vector3<double> expected_displacement(0, 0, 0.5 * kGravity * kDt * kDt);
> ```

nit, you might also want to update the comment instead of deleting it. 
___
*[multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEQwWo7V_XfIB_37eZ:-MhEQwWp2Mb94FFaI7VL:b-dybwf6) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc#L66)):*
> ```cpp
>   const int kTimeSteps = 10;
>   for (int i = 0; i < kTimeSteps; ++i) {
>     scheme.AdvanceOneTimeStep(state_n, qdot, &state_np1);
> ```

nit, constant qdot is a bit boring. Why not make a (constant) qddot and inside this loop do `qdot += dt * qddot` so that qdot is linear with time?

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed. In addition, I rolled the default integration scheme back to the previous acceleration based newmark scheme because I realize that 
1. The scheme used to advance the free motion state doesn't have to be the same as the one that solves for the contact, and more importantly,
2. if we switch to the velocity based newmark scheme, the contact tangent matrix will be off by a factor of `dt`. It would be easier to have the `DeformableRigidManager` own a `VelocityNewmarkScheme` and use it to update the post-contact velocity instead of having the `DeformableRigidManager` reach into each fem model to grab their own integration scheme.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-MhEvczQ6f56BkiBLtEx:b-ncbm6n)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEJz2234HexfQLqei8:-MhEsb-q9l5XLw62kFkV:bwpml2i) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/newmark_scheme.h#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, In principle I could take gamma=0 for a fully explicit scheme. However stability analysis tells me I should probably make gamma>1/2.
Probably worth saying something in the class's documentation about the limits of stability, at least if only for linear elasticity.
</blockquote></details>

I added a note in the class doc. PTAL, thanks!
___
*[multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEQwWo7V_XfIB_37eZ:-MhEvaLJ17Lc1SldOQB8:b-h23rtk) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, constant qdot is a bit boring. Why not make a (constant) qddot and inside this loop do `qdot += dt * qddot` so that qdot is linear with time?
</blockquote></details>

Done, thanks for the suggestion.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 207 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhEPNbd7Mf13QkZvDSx:-MhEt5JL7kZAYX4iXGoz:b-s5j77y) ([raw file](https://github.com/robotlocomotion/drake/blob/ea6e8d6e9c5154815aa5bb04b634b939b3f08f01/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L207)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, you might also want to update the comment instead of deleting it. 
</blockquote></details>

I rolled this change back because I switched back to midpoint rule as the default integration scheme.

**Review by amcastro-tri — COMMENTED** [review]
> The scheme used to advance the free motion state doesn't have to be the same as the one that solves for the contact

Mathematically, it must be the same. Bug I guess what you mean is that it doesn't have to be the same unknown? 

Per f2f I agree we would not need to fix this in this PR, but having open the option of an updater for free motion and a different (presumably even completely time scheme) updater in the contact manager could lead to a bug since now you have to somehow keeps those in sync. Ideally we'd like a single updater to avoid that problem.

At least I'd like to see an issue open regarding this problem (which is orthogonal to this PR). Probably the best option is what we talked yesterday? having the option of the model to multiply all equations by a single scalar (time step, 2*pi, etc)? a model parameter that by default is 1.0.

Besides this separate discussion, and possibly new issue, :lgtm:  for this PR as is.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-MhJNT1wAaSjIrroBcfi:bb4mjy6)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhJOb85CvQED2mU0KgB:-MhJOb85CvQED2mU0KgC:bjxbfkw) ([raw file](https://github.com/robotlocomotion/drake/blob/394f7d55ef4d54fe7ff7a2ebd6ec8d04cce8b9ef/multibody/fixed_fem/dev/newmark_scheme.h#L17)):*
> ```objc
>       v = vₙ + dt ⋅ (γ ⋅ a + (1−γ) ⋅ aₙ)
>       x = xₙ + dt ⋅ vₙ + dt² ⋅ [β ⋅ a + (0.5−β) ⋅ aₙ].
>  
> ```

nit, I see two red dots in Reviewable. Could you double check what it is about?
___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhJOfeXCkvvvDLrhGQ_:-MhJOfeXCkvvvDLrhGQa:b-dpdotf) ([raw file](https://github.com/robotlocomotion/drake/blob/394f7d55ef4d54fe7ff7a2ebd6ec8d04cce8b9ef/multibody/fixed_fem/dev/newmark_scheme.h#L18)):*
> ```objc
>       x = xₙ + dt ⋅ vₙ + dt² ⋅ [β ⋅ a + (0.5−β) ⋅ aₙ].
>  
>  Note that we require γ >= 0.5 for (conditional) stability.
> ```

humm.... "conditional" stability is predicated on the value of beta also. 
I'd probably just say, "The scheme is unconditionally unstable for gamma < 0.5 and therefore we require gamma >=0.5".

**Review by xuchenhan-tri — COMMENTED** [review]
> But I guess what you mean is that it doesn't have to be the same unknown?

Yes.

I opened a PR to track the issue, but I don't see why "the best option" is to having the model multiply all equations by a single scalar. All we need to scale is the tangent matrix, and we can easily do that at the call site (in this case the manager who knows how to convert units between the free motion solver and contact solver). Perhaps you are trying to solve a bigger issue we haven't run into yet?

In addition, I don't see having to coordinate two integration schemes as a defect. The manager owns both the free motion solver and the contact solver, so it inevitably has to keep them in sync, whether through keeping track of a factor of dt or through keeping the integration scheme in sync. One could imagine the manager having a single entry point where one can configure the integration scheme (per body if useful?), and then the manager ensures that the schemes used for free motion and post contact solve updates are compatible. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-MhJzxAoC3OK29DzeLEW:btbg8uy)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhJOb85CvQED2mU0KgB:-MhK-N-57XqncXn2LAKO:b-guf1jt) ([raw file](https://github.com/robotlocomotion/drake/blob/394f7d55ef4d54fe7ff7a2ebd6ec8d04cce8b9ef/multibody/fixed_fem/dev/newmark_scheme.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I see two red dots in Reviewable. Could you double check what it is about?
</blockquote></details>

I think it's indicating redundant whitespace. Fixed.
___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15593#-MhJOfeXCkvvvDLrhGQ_:-MhK0ZI34l6EkPA75rxC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/394f7d55ef4d54fe7ff7a2ebd6ec8d04cce8b9ef/multibody/fixed_fem/dev/newmark_scheme.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

humm.... "conditional" stability is predicated on the value of beta also. 
I'd probably just say, "The scheme is unconditionally unstable for gamma < 0.5 and therefore we require gamma >=0.5".
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
BTW, the new issue is #15620.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593#-:-MhK8TbN16QII4ZwnPDm:b-q4qxij)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15593)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

**Pull request merged**
