### PR TITLE
[workspace] Upgrade sdformat_internal to latest release sdformat13_13.6.0

### PR DESCRIPTION
**Pull request by azeey**
Mainly fixes an issue with deeply nested merge-includes for custom parsed files needed by #16727 .

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20195)

### CODE REVIEW

**Comment by azeey** [comment]
@EricCousineau-TRI PTAL

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@EricCousineau-TRI for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20195#-:-NecdNQ93hncIYQaPLXx:bo0g27y)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @azeey)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks!
+@SeanCurtis-TRI for platform review, please!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20195#-:-NecfkeV0Rl4DFJcQ2W4:b-kllwxe)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @azeey)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20195#-:-Ned5hVi3zYxnr-m0g1H:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
