### PR TITLE
[fem] Calculate tangent matrix for contact

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
* Calculate the free motion tangent matrix for all deformable bodies in
DeformableRigidManager.
* Permute the free motion tangent matrix to group dofs in contact.
* Calculate the Schur complement of the free motion tangent matrix based
on contact participation.
* Assemble the tangent matrix for contact with full mass matrix for
rigid dofs and the Schur complements of the free motion tangent matrices
for participating deformable bodies.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417)* status: 1 unresolved discussion, needs at least one assigned reviewer, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 398 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15417#-MelX5cFBQ2N3KKMMXMT:-MelX5cFBQ2N3KKMMXMU:bnivojj) ([raw file](https://github.com/robotlocomotion/drake/blob/f031e199abd044981aecd470ce0ecc2b29a0fff4/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L398)):*
> ```cpp
> 
> template <typename T>
> void DeformableRigidManager<T>::CalcFreeMotionTangentMatrixSchurComplement(
> ```

This needs a unit test.

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417#-:-Melx5RZ4cD9H1eDD5FT:b-hq4nxl)* status: LGTM missing from assignee amcastro-tri, labeled "do not merge" (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
first pass.

> Reviewed 1 of 7 files at r1, 4 of 9 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417#-:-Mf30Jnx6SZIK40ACCVE:ba1eduw)* status: 10 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2xcBj-TiHxz1AC6Gx:-Mf2xcBj-TiHxz1AC6Gy:b-4ooj5d) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.h#L53)):*
> ```objc
>     const math::RigidTransform<T>& X_WB);
> 
> /* Note that this method is copypasted from mesh_intersection_test.cc. */
> ```

I couldn't find the specific test. Could you say more?
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 74 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2xyXj8Q4-G_yXzX8Y:-Mf2xyXj8Q4-G_yXzX8Z:b-9qfut2) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.h#L74)):*
> ```objc
> 
> /* Generates a deformable geometry whose underlying mesh is given by
>  MakeOctahedronVolumeMesh().
> ```

please document we specify a discrete field approximation of the signed distance field to the surface.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 152 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2zzidCzjqrRq3Livu:-Mf2zzidCzjqrRq3Livv:b-dqw6au) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.cc#L152)):*
> ```cpp
>       {0, 2, 3, 5},
>       {0, 3, 4, 5},
>       {0, 4, 1, 5},
> ```

I see all of  these tets follow a convention. The first three define the "bottom" face, and the fourth one is in the direction of the right hand rule. Is this intentional? please add note if so.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2qhuN03lr1yIfezEn:-Mf2qhuN03lr1yIfezEo:b-wu07i8) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L16)):*
> ```objc
> 
> /* Reindexes the deformable dofs so that the tangent matrix assumes a block
>  structure associated with the contact pattern.
> ```

nit, more generally this docs could be written independent of the intended application for SoftSim?
That is, this method applies a purely mathematical operation on a (sparse) matrix, i.e. a permutation.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2r11BD5agN7jK93Vf:-Mf2r11BD5agN7jK93Vg:bj6g65o) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L18)):*
> ```objc
>  structure associated with the contact pattern.
> 
>  In the context of deformable contact, we may reindex the deformable dofs so
> ```

nit, these comments are useful but consider moving them in a context where the method gets used, which does have to do with sim of deformable objects.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2rZjTE_6Z_Txfz0P3:-Mf2rZjTE_6Z_Txfz0P4:b-b9qamp) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L24)):*
> ```objc
>  correspond to dofs `3*i`, `3*i+1`, and `3*i+2`.
> 
>  For example, suppose the input `tangent matrix is given by
> ```

another way to put it, your matrix has a block structure with 3x3 block entries Bij. Then given a permutation P (which you can define as the bijection of ℕ₀ into itself), this method builds the permuted matrix `C_{ij} = B_{P(i),P(j)}`
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2q_eG343iFW8MOFLJ:-Mf2q_eG343iFW8MOFLK:byjn2rt) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L49)):*
> ```objc
>  {0, 1, ..., tangent_matrix.cols()/3-1}. */
> template <typename T>
> Eigen::SparseMatrix<T> PermuteTangentMatrix(
> ```

nit, probably more generally we can call this `PermuteSparseMatrixOfMatrix3Blocks()`?
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2u80uDuhRVwat82c-:-Mf2u80uDuhRVwat82c0:b-sjzqkn) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L22)):*
> ```cpp
>   for (int i = 0; i < tangent_matrix.outerSize(); ++i) {
>     for (InnerIterator it(tangent_matrix, i); it; ++it) {
>       const int row_dim = it.row() % 3;
> ```

maybe `block_row`? since it's the row index of a given 3x3 block (`dim` sounds like a "fixed" `dimension`).
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2tzkjDrvY10EOK8Rx:-Mf2tzkjDrvY10EOK8Ry:bz81v72) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L24)):*
> ```cpp
>       const int row_dim = it.row() % 3;
>       const int col_dim = it.col() % 3;
>       const int row_vertex = it.row() / 3;
> ```

nit, maybe `block_offset`? if we think about it as a block structured matrix made up of 3x3 blocks.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2uTnu6hK67t1DcjF3:-Mf2uTnu6hK67t1DcjF4:b-jt6efs) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L28)):*
> ```cpp
>       const int new_row_vertex = vertex_permutation[row_vertex];
>       const int new_col_vertex = vertex_permutation[col_vertex];
>       const int new_row = new_row_vertex * 3 + row_dim;
> ```

nit, maybe `permuted_row`?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417)* status: 8 unresolved discussions, LGTM missing from assignee amcastro-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2xcBj-TiHxz1AC6Gx:-Mf3ty8t6C6M2LTL3_lb:b-bhuwli) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.h#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I couldn't find the specific test. Could you say more?
</blockquote></details>

Looks like the original test was removed, so I removed this comment that's no longer true.
___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 74 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2xyXj8Q4-G_yXzX8Y:-Mf3uN-b5Iqez1WPbOsa:b7wpf41) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.h#L74)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

please document we specify a discrete field approximation of the signed distance field to the surface.
</blockquote></details>

I reworded the doc, PTAL. The return type `ReferenceDeformableGeometry` has an approximated SDF baked into it by definition.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 152 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2zzidCzjqrRq3Livu:-Mf3vFlfDviAchE5uMO3:b-29vh20) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/mesh_utilities.cc#L152)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see all of  these tets follow a convention. The first three define the "bottom" face, and the fourth one is in the direction of the right hand rule. Is this intentional? please add note if so.
</blockquote></details>

Yes, I added a reference to the convention in `geometry::VolumeMesh`.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2qhuN03lr1yIfezEn:-Mf3vTY9BQZUnQ7dqL1V:b3and6z) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, more generally this docs could be written independent of the intended application for SoftSim?
That is, this method applies a purely mathematical operation on a (sparse) matrix, i.e. a permutation.
</blockquote></details>

Yes the docs could be done that way. But considering how specific this permutation is and the method being in `fem::internal` namespace, the generalization doesn't go very far. Being specific to the deformable tangent matrix provides the documentation with more context and a more intuitive name at callsite. 

Can we put a TODO here for now and generalize when we need to?
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2r11BD5agN7jK93Vf:-Mf3w4l6-wUDUOzJLSZb:bc33icc) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, these comments are useful but consider moving them in a context where the method gets used, which does have to do with sim of deformable objects.
</blockquote></details>

I think this comment goes hand in hand with the previous one. Maybe a TODO for now and generalize later?
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2rZjTE_6Z_Txfz0P3:-Mf3wZXC652jHDm2DGKC:b-lcuqlg) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

another way to put it, your matrix has a block structure with 3x3 block entries Bij. Then given a permutation P (which you can define as the bijection of ℕ₀ into itself), this method builds the permuted matrix `C_{ij} = B_{P(i),P(j)}`
</blockquote></details>

ℕ₀ is usually used to denote all natural numbers and 0, so I'll stay away from that notation. But I took all the rest, thanks for the suggestion!
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2q_eG343iFW8MOFLJ:-Mf3woJ_EMD4ApsfizYM:bur4m3) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, probably more generally we can call this `PermuteSparseMatrixOfMatrix3Blocks()`?
</blockquote></details>

Without the generality, `PermuteSparseMatrixOfMatrix3Blocks()` seems to be less informative than `PermuteTangentMatrix()` at the call site.

Maybe a TODO for now?
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2u80uDuhRVwat82c-:-Mf3x79d958Il1IvR1bE:b6k3mph) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe `block_row`? since it's the row index of a given 3x3 block (`dim` sounds like a "fixed" `dimension`).
</blockquote></details>

Hmm, I actually imagined you would want `row_dim` would be renamed to `block_row_offset` and `row_vertex` to be renamed to `block_row`. See `BlockSparseMatrix` for example. There you used `block_row` to to denote the index *of* the block instead of the index *within* a block.

Is this a typo in the comment or are there other considerations?
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2tzkjDrvY10EOK8Rx:-Mf3xnhq3-kJENaFU_5s:b-q64pkt) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe `block_offset`? if we think about it as a block structured matrix made up of 3x3 blocks.
</blockquote></details>

See above.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2uTnu6hK67t1DcjF3:-Mf3y2USDDFruVXfX0hb:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L28)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe `permuted_row`?
</blockquote></details>

Done, thanks.

**Review by amcastro-tri — COMMENTED** [review]
Very nice, feature review done. I only have a few nits and easy to resolve comments on docs. :lgtm: 

> Reviewed 3 of 9 files at r2, 1 of 2 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417#-:-Mf8doZ82FqdcxvxSJwk:bbdhh3a)* status: 10 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 333 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8Sz1jAqNHBny9ofo2:-Mf8Sz1jAqNHBny9ofo3:bj9ceya) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/deformable_rigid_manager.h#L333)):*
> ```objc
>    Jacobian matrix (see CalcContactJacobian()). The result is guaranteed to be
>    symmetric positive definite. */
>   contact_solvers::internal::BlockSparseMatrix<T> CalcContactTangentMatrix(
> ```

nit, the docs here show in Calc() leaving Eval() empty. You do the opposite in the methods above.
My personal preference is to document `CalcFoo()` since it's the one doing the actual job and then in `EvalFoo()` I usually say something like "Eval version of CalcFoo()."
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 828 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8SYW_66S-PtGg07ky:-Mf8SYW_66S-PtGg07kz:b-7doof9) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L828)):*
> ```cpp
>     const internal::SchurComplement<T>& tangent_matrix_schur_complement =
>         EvalFreeMotionTangentMatrixSchurComplement(context, i);
>     builder.PushBlock(block_index, block_index,
> ```

btw, this method is beautifully written as a whole. Nice job!
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2qhuN03lr1yIfezEn:-Mf8HkN58UsyVt4qXVUh:bt2j69j) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L16)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes the docs could be done that way. But considering how specific this permutation is and the method being in `fem::internal` namespace, the generalization doesn't go very far. Being specific to the deformable tangent matrix provides the documentation with more context and a more intuitive name at callsite. 

Can we put a TODO here for now and generalize when we need to?
</blockquote></details>

I'm not asking for any generalization. I'd simply move the first two paragraphs of these docs where the method is locally used, and that's pretty much it. The rest is generally valid.
It's the kind of thing we'd need to go over when coming out of dev and it seems simple to resolve now.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2q_eG343iFW8MOFLJ:-Mf8I4ZVB2ZwDeRJCoCq:b-y8bnmu) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Without the generality, `PermuteSparseMatrixOfMatrix3Blocks()` seems to be less informative than `PermuteTangentMatrix()` at the call site.

Maybe a TODO for now?
</blockquote></details>

at the call site you can use the first two paragraphs of the docs you placed here. Plus, at call site your very specific sparse matrix most likely will be called something like `tangent_matrix`.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2u80uDuhRVwat82c-:-Mf8IUt09u7D3iwB7HsQ:bk76sci) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I actually imagined you would want `row_dim` would be renamed to `block_row_offset` and `row_vertex` to be renamed to `block_row`. See `BlockSparseMatrix` for example. There you used `block_row` to to denote the index *of* the block instead of the index *within* a block.

Is this a typo in the comment or are there other considerations?
</blockquote></details>

not a typo. The difference is that in BlockSparseMatrix I never needed the local index within the block itself and therefore there was no ambiguity. 
In retrospect, BlockSparseMatrix could probably benefit of using the notation `block_row_offset` as well.
`dim` to me still sounds like "dimension" as in "matrix dimension", so it seems strange.
Any other suggestions? 
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1022 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8WSaA6D2Q9oq8GD9f:-Mf8WSaA6D2Q9oq8GD9g:b480zmy) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1022)):*
> ```cpp
>     plant_->Finalize();
> 
>     auto deformable_rigid_manager =
> ```

nit, in general asking for trouble having `foo` and `foo_` in the same scope, even though here it's trivial.
Probably best in this case having `auto owned_deformable_rigid_manager = ...` for the unique pointer.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1040 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8WufHEnjQX6CKNbog:-Mf8WufHEnjQX6CKNboh:b-n0n21q) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1040)):*
> ```cpp
>   /* Calls DeformableRigidManager::EvalContactTangentMatrix() and returns the
>    tangent matrix for contact as a dense matrix. */
>   MatrixXd EvalContactTangentMatrix(const Context<double>& context) const {
> ```

I thought this was sugar for the `Eval` method. Probably best call it `CalcDenseTangentMatrix()` so that it is clear it does more than just an eval.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1048 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8X4ng6_9M9j2GzeAQ:-Mf8X4ng6_9M9j2GzeAR:b4eitpw) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1048)):*
> ```cpp
>   /* Calls DeformableRigidManager::EvalFreeMotionTangentMatrix() and returns the
>    free motion tangent matrix of the deformable body with the given `index` as a
>    dense matrix. */
> ```

ditto on Eval vs Calc.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1059 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8XOwC2t8WjV2dBMVx:-Mf8XOwC2t8WjV2dBMVy:bnlvvqe) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1059)):*
> ```cpp
>    and returns the Schur complement of the tangent matrix of the deformable body
>    with the given `index` as a dense matrix. */
>   MatrixXd EvalFreeMotionTangentMatrixSchurComplement(
> ```

nit, if you wanna leave the `Eval`, here you can return a reference.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1151 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8Znwe4Y0Q461iDWnX:-Mf8Znwe4Y0Q461iDWnY:b-5tdpid) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1151)):*
> ```cpp
> }
> 
> /* Verifies that the contact tangent matrix matches expection. */
> ```

nit, typo expection
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1152 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8dOC_75JfuxhDNu5c:-Mf8dOC_75JfuxhDNu5d:b-fuu0bp) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1152)):*

> SingleContactPair

nit, maybe call it something like `TangentMatrix`?

**Review by amcastro-tri — COMMENTED** [review]
Let me fix that, this truly deserves a :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417#-:-Mf8dxJE1fZvLLgVw4e2:b-ydymxe)* status: 10 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417)* status: 3 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 333 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8Sz1jAqNHBny9ofo2:-Mf90AYU7Cz_dimg4PrY:b-h23rtk) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/deformable_rigid_manager.h#L333)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, the docs here show in Calc() leaving Eval() empty. You do the opposite in the methods above.
My personal preference is to document `CalcFoo()` since it's the one doing the actual job and then in `EvalFoo()` I usually say something like "Eval version of CalcFoo()."
</blockquote></details>

Done, thanks for the suggestion.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1040 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8WufHEnjQX6CKNbog:-Mf8zPqgE3yx1-hhm0JV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1040)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I thought this was sugar for the `Eval` method. Probably best call it `CalcDenseTangentMatrix()` so that it is clear it does more than just an eval.
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, line 1048 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf8X4ng6_9M9j2GzeAQ:-Mf8zR-wDKMhCaagPB9u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e8f6a743cd25c60191fdb3ef72ebde009112b2f5/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L1048)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto on Eval vs Calc.
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2u80uDuhRVwat82c-:-Mf8y6hw-YZlp76HP3AP:b-xo8rdq) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not a typo. The difference is that in BlockSparseMatrix I never needed the local index within the block itself and therefore there was no ambiguity. 
In retrospect, BlockSparseMatrix could probably benefit of using the notation `block_row_offset` as well.
`dim` to me still sounds like "dimension" as in "matrix dimension", so it seems strange.
Any other suggestions? 
</blockquote></details>

I think `block_row` and `block_row_offset` are fine as long as it's consistent with the notation in `BlockSparseMatrix`. I can make a follow-up PR to change `block_row` to `block_row_offset` in BlockSparseMatrix.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2qhuN03lr1yIfezEn:-Mf9qTAH7wsjGWJGRouB:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'm not asking for any generalization. I'd simply move the first two paragraphs of these docs where the method is locally used, and that's pretty much it. The rest is generally valid.
It's the kind of thing we'd need to go over when coming out of dev and it seems simple to resolve now.
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/permute_tangent_matrix.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2q_eG343iFW8MOFLJ:-Mf9qWd58PFba_8zjb3G:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

at the call site you can use the first two paragraphs of the docs you placed here. Plus, at call site your very specific sparse matrix most likely will be called something like `tangent_matrix`.
</blockquote></details>

Done, thanks.

**Review by amcastro-tri — COMMENTED** [review]
beautiful. :lgtm: 

> Reviewed 6 of 8 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15417#-:-MfELC4R-vckFMamyiUM:blns9di)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/permute_tangent_matrix.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15417#-Mf2u80uDuhRVwat82c-:-MfEKr0U0QWoKndEdvea:b-6mv6g3) ([raw file](https://github.com/robotlocomotion/drake/blob/45b0c95f02c7fd73c54cbd1304fe1385fdd5ddbf/multibody/fixed_fem/dev/permute_tangent_matrix.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think `block_row` and `block_row_offset` are fine as long as it's consistent with the notation in `BlockSparseMatrix`. I can make a follow-up PR to change `block_row` to `block_row_offset` in BlockSparseMatrix.
</blockquote></details>

thanks! feel free to send it my way also.

**Pull request merged**
