### PR TITLE
Cleanup various CMake targets

### PR DESCRIPTION
**Pull request by jamiesnape**
In further preparation for packaging.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4720)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
Possibly this PR made a couple of tests disappear? https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-experimental-release-2371&field2=buildstarttime&compare2=84&value2=now

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4720#-:-Ka84UJs5qivv6-Ma8JJ:b-2jb2m1)*

**Comment by david-german-tri** [comment]
Specifically parsers_common_test and valkyrie_ik_test

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4720#-:-Ka85cgjr4npFIKevHPT:bxypuzy)*

**Comment by jamiesnape** [comment]
Seems I have now gained three tests:

https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-experimental-release-2416&field2=buildstarttime&compare2=84&value2=now

**Comment by david-german-tri** [comment]
Actually, four:  generate_urdf_test, infinite_circuit_road_test, parser_common_test, rigid_body_plant_that_publishes_xdot_test, valkyrie_ik_test, and yaml_to_obj_test

**Comment by david-german-tri** [comment]
:lgtm:

So, we once again got burned by CMake handling of uninitialized variables, leading to silent loss of test coverage?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4720#-:-Ka9dx_rV08KifHDq6hE:b-tj5t23)*

**Comment by david-german-tri** [comment]
-@mwoehlke-kitware I'm going to go ahead and merge this to restore test coverage.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4720#-:-Ka9fapHqIovoFmswuKR:bkrmuzv)*

**Comment by jamiesnape** [comment]
> So, we once again got burned by CMake handling of uninitialized variables, leading to silent loss of test coverage?

No, this was a logic error on my part.

**Pull request merged**
