### PR TITLE
Deprecate Polynomial::EqualToAfterExpansion

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202#-:-N285lRm1ldDDQiaXQaZ:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202#-:-N28IG4Y7CMSGA7PIERa:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`common/symbolic_polynomial.h` line 265 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17202#-N28HXTG8IrI9lW51ero:-N28HXTG8IrI9lW51erp:bvh22ra) ([raw file](https://github.com/robotlocomotion/drake/blob/00f002a09d7db7c235c25ec752b9a4a4bc31190d/common/symbolic_polynomial.h#L265)):*
> ```objc
>   DRAKE_DEPRECATED(
>       "2022-09-01",
>       "Use this.Expand().EqualTo(p.Expand() instead of EqualToAfterExpansion()")
> ```

two typos



_Suggestion:_
```objc
this->Expand().EqualTo(p.Expand())
```
___
*[`bindings/pydrake/test/symbolic_test.py` line 1339 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17202#-N28HrZr4uPQhINhGR-j:-N28HrZr4uPQhINhGR-k:b6ut7uk) ([raw file](https://github.com/robotlocomotion/drake/blob/e26674ac3edae171150a325a73f2e2eb8ec0b0a3/bindings/pydrake/test/symbolic_test.py#L1339)):*
> ```Python
>         p_expand = sym.Polynomial({sym.Monomial(): 0})
>         self.assertFalse(p_not_expand.EqualTo(p_expand))
>         self.assertTrue(p_not_expand.EqualToAfterExpansion(p_expand))
> ```

nit This test coverage should remain, guarded by a `catch_drake_warnings`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202#-:-N2CvmN30VveAZnz8uW4:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17202)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
