### PR TITLE
November external upgrades

### PR DESCRIPTION
**Pull request by nicolecheetham**
Upgrades externals for the month of November

Makes progress towards: #22087

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAx-EoD91SfRFIO5zUq:b-hnc6mz)* status: LGTM missing from assignee rpoyner-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 24 of 24 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAx0KqnElLPaOCo3XCd:bg7igkv)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
My bad. It is ready; I just forgot to mark it as such until now

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAx16pj1hSiljqoMvpt:bs0sach)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAx1bArCGRBT2T6OpTU:b-chsgxs)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
I think we're good to go now, except for the rebase dance. @nicolecheetham can you rebase this to current master, and then merge please? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAx28XOD9A128i4MzQk:bnogif)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
Sure! I just rebased it and working on merging it

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22119#-:-OAxAMg27BEvt8fdM97d:b-bbuhki)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform), base commit is latest master

**Comment by rpoyner-tri** [comment]
victory! Thanks.

**Pull request merged**
