### PR TITLE
MBP contact Jacobians

### PR DESCRIPTION
**Pull request by amcastro-tri**
contact Jacobians N and D needed for any time stepping method. This is required to implement time stepping with contact in MBP.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888#-:-LDbrPi06zWyup72OBFz:b-a98c4g)*

**Comment by sherm1** [comment]
A couple of random comments (not a review).

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/multibody_tree.h, line 1148 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDdy9C2-Bg4A8wtwUyC:-LDdy9C2-Bg4A8wtwUyD:bz949o) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_tree.h#L1148)):*
> ```objc
>   /// @param[in] frame_B
>   ///   Points `Qi` in the set instantaneously move with this frame.
>   /// @param[in] p_WQi_set
> ```

BTW it seems odd to ask for B-attached points to be given in the W frame. Why do it that way? The point set would be constant and reusable in the B frame.

---

*[multibody/multibody_tree/multibody_tree.h, line 1173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDdyjki4-5LH647qt6Q:-LDdyjki4-5LH647qt6R:b-ggbdha) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_tree.h#L1173)):*
> ```objc
>       const Frame<T>& frame_B, const Eigen::Ref<const MatrixX<T>>& p_WQi_set,
>       EigenPtr<MatrixX<T>> Jv_WQi) const;
> ```

BTW consider a TODO noting that most operations with a large point set would be more efficiently calculated as a matrix-vector product than as a separate Jacobian matrix.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1039 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDdzRU4BjiBjw60X0Jn:-LDdzRU4BjiBjw60X0Jo:bh1r62m) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1039)):*
> ```objc
>   // Given a set of point pairs in `point_pairs_set`, this method computes the
>   // Jacobian N(q) such that:
>   //   vn = N(q) v
> ```

BTW this equations is confusingly similar to the kinematic differential equation
`qdot = N(q )v`. Since you used`J` above I would think something like `Jn` would be better. But if we're stuck with this symbol please add a note to the reader saying they shouldn't confuse this N with the other one.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1056 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDe-BRUCjK3Wwq9nMyG:-LDe-BRUCjK3Wwq9nMyH:b-96nuyj) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1056)):*
> ```objc
>   // Given a set of nc point pairs in `point_pairs_set`, this method computes
>   // the tangential velocities Jacobian D(q) such that:
>   //   vt = D(q) v
> ```

BTW `Jd` ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888#-:-LDe-YNQ1nCxq0YK-xDY:bngxvmd)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/multibody_tree.h, line 1148 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDdy9C2-Bg4A8wtwUyC:-LDg00BW0cqxJhH72u0O:b-ylp3xt) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_tree.h#L1148)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it seems odd to ask for B-attached points to be given in the W frame. Why do it that way? The point set would be constant and reusable in the B frame.
</blockquote></details>

BTW It's for those scenarios in which you do have your points already expressed in the world frame. For those cases it'd be a waste to transform them to the B frame so that we can call the other signature of this method (which would actually transform them back to the W frame). This happens in this PR for the computation of N and D since the contact engine returns the contact pairs already expressed in the world frame.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1039 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDdzRU4BjiBjw60X0Jn:-LDg1dPk-k783FWSQfsY:bp78q7n) ([raw file](https://github.com/robotlocomotion/drake/blob/769ae6118030bc3b10b7a841603f7d8d53b7646a/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1039)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this equations is confusingly similar to the kinematic differential equation
`qdot = N(q )v`. Since you used`J` above I would think something like `Jn` would be better. But if we're stuck with this symbol please add a note to the reader saying they shouldn't confuse this N with the other one.
</blockquote></details>

BTW let me ponder on this. I think I do like `Jn` and `Jt`. What do you think @edrumwri?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh7sNw1asDrGkLJBpv:-LDh9FRr4v7-qwQ2UBTT:bpqhu0w) (no related file):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

First pass complete.
</blockquote></details>

Thanks @edrumwri, back to you.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1047 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh-cGHDa0wt5Sn9s-c:-LDhCB4rEw61OH5bQFoF:blrca34) ([raw file](https://github.com/robotlocomotion/drake/blob/b7eeefb7f4e5d35f2066c2b3f47e9645f22426a3/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1047)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It is note comparing them, it is just stating the relationship with the actual normal velocity. Also, it is meant as a note to developers. 
</blockquote></details>

I'm saying that I don't understand what information you're trying to convey.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1063 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh0sy7A2ziJX2rl10-:-LDhCgDx4MYpaWeyy35I:buwkfne) ([raw file](https://github.com/robotlocomotion/drake/blob/b7eeefb7f4e5d35f2066c2b3f47e9645f22426a3/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1063)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Since it is a note to developers, I like using symbols that relate more closely to the variables names in the code. I can change it though if you feel super strong about it. Personally I think it'd be a loss.
</blockquote></details>

I don't.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1063 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh19IB94MYB6vijWAq:-LDhCiq81p5zyl3m_R6h:byv4t1) ([raw file](https://github.com/robotlocomotion/drake/blob/b7eeefb7f4e5d35f2066c2b3f47e9645f22426a3/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1063)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

They have unit norm.
</blockquote></details>

I wasn't aware of this term.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888#-:-LDhCqL0CPR8BqQOsgfJ:bnfp4nl)*

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1047 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh-cGHDa0wt5Sn9s-c:-LDhEQEt78Yum8dDyrRA:b-xd47cl) ([raw file](https://github.com/robotlocomotion/drake/blob/b7eeefb7f4e5d35f2066c2b3f47e9645f22426a3/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1047)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm saying that I don't understand what information you're trying to convey.
</blockquote></details>

You know what, I realize it actually doesn't make any sense. It depends on what velocity I am looking at (v_AcBc or v_BcAc). So I just removed since, as you pointed out, it adds more confusion rather than clarifying anything.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888#-:-LDhEnHuEFsUWylM-_v1:b-irfx5k)*

**Comment by sherm1** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1063 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh19IB94MYB6vijWAq:-LDhO14AAwK8yUqrYk5Z:bctv4wt) ([raw file](https://github.com/robotlocomotion/drake/blob/b7eeefb7f4e5d35f2066c2b3f47e9645f22426a3/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1063)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I wasn't aware of this term.
</blockquote></details>

BTW probably not a good word to introduce -- apparently has many meanings: https://en.wikipedia.org/wiki/Versor_(disambiguation)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 907 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDhOB9TDVTU17v4rHGt:-LDhOB9TDVTU17v4rHGu:b-zhyi7k) ([raw file](https://github.com/robotlocomotion/drake/blob/15d1af51b00d1188c5930a4c1181e3f14caaa556/multibody/multibody_tree/multibody_plant/multibody_plant.h#L907)):*
> ```objc
> 
>   // Friend class to facilitate testing.
>   friend class MultibodyPlantTester;
> ```

FYI, I looked around for any way to avoid this `friend` without major surgery, and I couldn't find one.  I fear I must allow this as a "within reason" case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888#-:-LDhOVZ51WAyAYDiVPhv:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 907 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDhOB9TDVTU17v4rHGt:-LDhocPU-RS2LdzbMstt:b-s61je4) ([raw file](https://github.com/robotlocomotion/drake/blob/15d1af51b00d1188c5930a4c1181e3f14caaa556/multibody/multibody_tree/multibody_plant/multibody_plant.h#L907)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, I looked around for any way to avoid this `friend` without major surgery, and I couldn't find one.  I fear I must allow this as a "within reason" case.
</blockquote></details>

We've been adding these `Tester` friend classes in a number of places within Drake and then I just adopt it is as a "good practice". I'd love to hear what other ways to do this there are.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8888#-LDh7sNw1asDrGkLJBpv:-LDhpLlp7MQ3mHe3NjXM:bvsqsc8) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thanks @edrumwri, back to you.
</blockquote></details>

@edrumwri, it seems Reviewable now requires you to resolve every single thread you add. You have two unresolved discussions (including this one).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8888)*

**Pull request merged**
