### PR TITLE
Defer "gurobi not found" errors until build time

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is required for `bazel query` commands or `genquery()` rules to run without error.  We want users without Gurobi configured to still be able to use the query features of Bazel.  (This will soon become required for linters that inspect `libdrake.so` compositional correctness #6464.)

Do not merge until:
- [x] Passes macOS `-everything` CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8578)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm: (pending CI)

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/os.bzl, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-L9u0mVg7mbI1d_zEhRu:-L9u0mVg7mbI1d_zEhRv:bs8sfm1) ([raw file](https://github.com/robotlocomotion/drake/blob/147c05feb8d2c7e0a4b46db7c7d3aca999375d7e/tools/workspace/os.bzl#L116)):*
> ```Python
>         a struct, with attributes:
>         - error: str iff any error occurred, else None
>         - basic_os: str either "ubuntu" or "macos" if no error
> ```

BTW I think I would call this `distribution`, but I am not strongly against the current naming.

---

*[tools/workspace/gurobi/repository.bzl, line 22 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-L9u26A516mw7WGGv6h7:-L9u26A516mw7WGGv6h8:b-2b3tgg) ([raw file](https://github.com/robotlocomotion/drake/blob/147c05feb8d2c7e0a4b46db7c7d3aca999375d7e/tools/workspace/gurobi/repository.bzl#L22)):*
> ```Python
>         # unset, pass the empty string to our template() call, but symlink a
>         # dummy distro path since we can't symlink to the empty string.
>         gurobi_path = repo_ctx.os.environ.get("GUROBI_PATH", "")
> ```

BTW The Gurobi docs use `/opt/gurobi752/linux64`, so maybe in future this could look in that location as well and save an environment variable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-:-L9u2sPP0txJAodij2M-:b-lj32db)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

(Note that I'm going to wait for this to pass on macOS CI prior to merging.)

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/os.bzl, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-L9u0mVg7mbI1d_zEhRu:-L9u4Nc61KyxTRXb8C6N:bfgbu14) ([raw file](https://github.com/robotlocomotion/drake/blob/147c05feb8d2c7e0a4b46db7c7d3aca999375d7e/tools/workspace/os.bzl#L116)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I think I would call this `distribution`, but I am not strongly against the current naming.
</blockquote></details>

Awesome.  I didn't like basic_os but was stumped for a better name.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-:-L9u4T066U-Utex5tX8I:bly9key)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
FYI, mac CI is not happy:
```
ERROR: /Users/sierra/workspace/mac-sierra-clang-bazel-experimental-everything/src/tools/workspace/BUILD.bazel:60:1: Target '@gurobi//:install' is not visible from target '//tools/workspace:check_licenses'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /Users/sierra/workspace/mac-sierra-clang-bazel-experimental-everything/src/tools/workspace/BUILD.bazel:54:1: Target '@gurobi//:install' is not visible from target '//tools/workspace:install_external_packages'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578#-:-L9w0tNc1Gd6yFnHXSdk:b-rv8eu0)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

> FYI, mac CI is not happy ...

Yeah; that's the downside to having two separate BUILD files, instead of emitting them with string concatenation -- its easy to accidentally have them diverge if you're not careful.

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8578)*

**Pull request merged**
