### PR TITLE
[doc] Explain how to run Drake under Rosetta 2

### LINKED ISSUE #14555: Test on new Apple arm hardware
New Apple laptops ship with arm (not x86) processors.  There is an emulation layer (Rosetta 2) for x86 binaries to continue to run.

We should experiment and test how Drake behaves on this new hardware, at minimum so we can inform users what to expect, but ideally to inform a work plan to patch up any problems, so that at least _some_ installation method can work for users who want to run Drake on this platform.

Any work related to _native_ code support (arm), will be in a separate issue.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #14555.

~This PR also contains a small unrelated docs fixup for today's release notes.~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)

### CODE REVIEW

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

Might be worth noting somehow that `arch` (run with no arguments) will say `i386` if your shell is x86_64. (Yeah... `arch -i386` complains about an "unknown architecture", but `arch` reports x86_64 as "i386". Brilliant :stuck_out_tongue_closed_eyes:.)

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381#-:-MtOlJJB-SjO9oodb2Ys:b-s924qo)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[doc/_pages/rosetta2.md, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtOl8_XArifNLYVHk5q:-MtOl8_XArifNLYVHk5r:b6s39ol) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa1281120ae1c6a3add09ce9419891d16bb936/doc/_pages/rosetta2.md#L21)):*
> ```Markdown
> 1. Make sure there is not an ARM version of brew
>    (i.e., ``/opt/homebrew/bin/brew``) in your ``$PATH``.
>    * You can use ``echo $PATH`` to see what's there.
> ```

Okay. `which -a brew` could be another option, not sure if it's better or worse.

**Review by mwoehlke-kitware — COMMENTED** [review]
BTW... for the sake of explaining better how this "stuff" works (this is just informative, probably *not* anything that should go in the user doc)... AFAIUI, `arch` is the "magic Rosetta command" that does two things: report the current "arch environment" (no arguments) and selects which version of a multi-arch binary (e.g. `/bin/bash`, `/usr/bin/python`) to run.

When *not* run via `arch`, AFAICT macOS defaults to running in x86 mode if *any* parent process is an x86 process. For example, running `/opt/homebrew/bin/bash` once one is "in" x86 mode won't switch back to ARM mode. Also, once one has `/usr/local/bin/bash`, it is sufficient to just run that (no `arch` required).

Probably the important upshot is that if `arch` reports "i386", it seems actually fairly difficult to accidentally do anything in ARM mode, with the exception of running `/opt/homebrew/bin/brew`, as brew seems to hard-code what arch it wants to be.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381#-:-MtOmM065wtoGs7hgJpX:bx43o7r)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
FYI I added another tiny commit here for something I missed earlier today.  I'll have the platform reviewer double-check that piece.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381#-:-MtPEeqn2qlco35GfpG4:bwu1f6a)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[doc/_pages/rosetta2.md, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtOl8_XArifNLYVHk5q:-MtPEOaL7v3JXqKyr81_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa1281120ae1c6a3add09ce9419891d16bb936/doc/_pages/rosetta2.md#L21)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Okay. `which -a brew` could be another option, not sure if it's better or worse.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381#-:-MtPLfpi-RmW5uFCa02g:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[doc/_release-notes/v0.38.0.md, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPLFMxECLLZccfSw2Q:-MtPLFMxECLLZccfSw2R:bhn07xd) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_release-notes/v0.38.0.md#L20)):*
> ```Markdown
>   * macOS users already use Python 3.9, so will not be affected.
> * The use of ``drake-visualizer`` on macOS is deprecated and will be removed
>   from Drake on or after April 1st, 2022 ([#16215][_#16215]).
> ```

 I find it a bit surprising to notice that numeric links in Announcements are to open issues, rather than merged PRs. Is there some missing/undocumented style/practice here?

As for the present changes, yup, fine, approved.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[doc/_release-notes/v0.38.0.md, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPLFMxECLLZccfSw2Q:-MtPMBvm71-1xuujlPdf:beh8apn) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_release-notes/v0.38.0.md#L20)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

 I find it a bit surprising to notice that numeric links in Announcements are to open issues, rather than merged PRs. Is there some missing/undocumented style/practice here?

As for the present changes, yup, fine, approved.
</blockquote></details>

As of yet, this deprecation is only apparent as an announcement -- there is no warning in our software itself that provides any diagnostic.  I wanted to at least get this link in here, in case anyone wanted to read up on more information or to push back.

Once we have a warning printed by the code, I could add its PR number here.

(Yes, this all is a bit awkward.)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_pages/rosetta2.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPSUM61-LfTBbHZLXs:-MtPSUM61-LfTBbHZLXt:b-xwfx8f) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_pages/rosetta2.md#L29)):*
> ```Markdown
> 1. Install Drake as usual from the x86_64 shell.
> 
> # Additional information
> ```

Um... okay. I'm not sure this needs to be here. At least it could probably use some word-smithing as end user documentation.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware and @rpoyner-tri)

___
*[doc/_pages/rosetta2.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPSUM61-LfTBbHZLXs:-MtPTiT30rExrQFJt05k:b-u0nxb7) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_pages/rosetta2.md#L29)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Um... okay. I'm not sure this needs to be here. At least it could probably use some word-smithing as end user documentation.
</blockquote></details>

I think erring on the side of more information is for the better.  We have some battle experience, and our users might not grok any of this yet.

I had already tried to clean it up, and I just did one more pass.  If you see any remaining problems, please point them out specifically and/or push fixes to the branch.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware and @rpoyner-tri)

___
*[doc/_release-notes/v0.38.0.md, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPLFMxECLLZccfSw2Q:-MtPZPLOEQ4YIkZBNFH9:bqsi86n) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_release-notes/v0.38.0.md#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As of yet, this deprecation is only apparent as an announcement -- there is no warning in our software itself that provides any diagnostic.  I wanted to at least get this link in here, in case anyone wanted to read up on more information or to push back.

Once we have a warning printed by the code, I could add its PR number here.

(Yes, this all is a bit awkward.)
</blockquote></details>

OK The actual deprecation PR has merged now, so this PR doesn't touch this file anymore.  Sorry for the churn.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/_pages/rosetta2.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPSUM61-LfTBbHZLXs:-MtPViMS33Obq0yHLIUW:brbbn21) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_pages/rosetta2.md#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think erring on the side of more information is for the better.  We have some battle experience, and our users might not grok any of this yet.

I had already tried to clean it up, and I just did one more pass.  If you see any remaining problems, please point them out specifically and/or push fixes to the branch.
</blockquote></details>

Attempt at better wording:

The `arch` command serves two purposes; to report the "active" architecture (when given no arguments), or to run a selected architecture of a universal binary (e.g. `/bin/bash`, `/usr/bin/python`).

While the "active" architecture defaults to ARM, having any x86_64 process as an ancestor appears sufficient to change the "active" architecture, so long as `arch -arm64` is not used. Many programs will respect the reported architecture, but `brew` is an exception, and will always attempt to install software for the architecture of the `brew` executable that is executed; this is why it is important to ensure that `/opt/homebrew/bin` is not in your `$PATH` when attempting to install or run Drake using x86_64 emulation on ARM. Otherwise, once in x86_64 mode, things will tend to stay that way, such that accidentally switching back to ARM mode should be rare.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware (waiting on @rpoyner-tri)

___
*[doc/_pages/rosetta2.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPSUM61-LfTBbHZLXs:-MtPcXhs60d2msOHvLkm:b-pa6e8o) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_pages/rosetta2.md#L29)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Attempt at better wording:

The `arch` command serves two purposes; to report the "active" architecture (when given no arguments), or to run a selected architecture of a universal binary (e.g. `/bin/bash`, `/usr/bin/python`).

While the "active" architecture defaults to ARM, having any x86_64 process as an ancestor appears sufficient to change the "active" architecture, so long as `arch -arm64` is not used. Many programs will respect the reported architecture, but `brew` is an exception, and will always attempt to install software for the architecture of the `brew` executable that is executed; this is why it is important to ensure that `/opt/homebrew/bin` is not in your `$PATH` when attempting to install or run Drake using x86_64 emulation on ARM. Otherwise, once in x86_64 mode, things will tend to stay that way, such that accidentally switching back to ARM mode should be rare.
</blockquote></details>

Done.

Used as-is, thanks.

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16381)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware (waiting on @rpoyner-tri)

___
*[doc/_pages/rosetta2.md, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16381#-MtPSUM61-LfTBbHZLXs:-MtPefVRAd53dv6FKlkm:b-8fx2u7) ([raw file](https://github.com/robotlocomotion/drake/blob/e42475531fb4bfbc8e380a3612d6100595606301/doc/_pages/rosetta2.md#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

Used as-is, thanks.
</blockquote></details>

:+1:

**Pull request merged**
