### PR TITLE
[geometry/dev] Only use one endpoint between the client and server.

### LINKED ISSUE #16455: [geometry/dev] refactor client-server protocol to one curl transaction
Ref #16234 discussion, combine `UploadScene` and `RetrieveRender` into one curl transaction, send the scene sha256 hash in the form fields.

### LINKED ISSUE #16457: [geometry/dev] refactor python server to not repeat logic for validating form parameters
Ref #16234, current implementation is not DRY.  Refactor form validation logic after #16455.

### PR DESCRIPTION
**Pull request by svenevs**
- Remove `upload_endpoint_` and related fields from `RenderClient`,
  `RenderClientGltf`, and `RenderClientGltfParams`.
- Rename `RenderClient` method `RetrieveRender` to `RenderOnServer`, simplify
  parameters.
- Render server API updates:
    - `<input type="file">` form field `data` renamed to `scene`.
    - Field `id` renamed to `scene_sha256`.
    - Added additional documentation on README about the relationship between
      `"cameras"` and `"nodes"` arrays in the glTF specification.
- Render server implementation updates:
    - Only implement one endpoint for the client, /render.
    - Introduce `RenderRequest` and related helper classes / methods to simplify
      `<form>` validation code-reuse.
        - `RenderError` is the preferred form of communicating any problems.
    - Add `NO_CLEANUP` developer switch, make all other constants upper-case.
        - render_endpoint will delete the .gltf scene file after complete.
        - send_file prevents image file deletion, delete all files in cache
          older than five minutes upon new request.

Fixes #16455.  Fixes #16457.  Adding additional comments in review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16504)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
Thanks, Stephen! First pass done. PTAL!

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16504#-:-MvMIYIX0uqLo1jkQdeh:b-60kugv)* status: 7 unresolved discussions, LGTM missing from assignee zachfang (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_client.cc, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvLyyr0EBj198eQCBpK:-MvLyyr197mgkqIq6_dN:b-mlzfry) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_client.cc#L388)):*
> ```cpp
>   // Add the fields to the form.
>   AddFileField(form, "scene", scene_path, mime_type);
>   const std::string scene_sha256 = ComputeSha256(scene_path);
> ```

Do we still have `server_sha256 = post_response["sha256"];` check as was in UploadScene()? Or maybe this is checked somewhere else?
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvM-ndU5XcZK0RwN5Zl:-MvM-ndU5XcZK0RwN5Zm:b-6sfwoq) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L22)):*
> ```Python
> Tip:
>     While developing your server, it can be helpful to wield the ``FLASK_ENV``
>     environment variable.  It's default value is ``"production"``, but setting
> ```

nit: `It's` -> `Its`
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvM9ERgEQKhKxgZ7B-C:-MvM9CONAAlpjUIDR-Th:bdyi389) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L180)):*
> ```Python
>         self.code = code
>         # Do not allow successful HTTP codes to be used, this is an Error.
>         if self.code < 400:
> ```

nit: I wonder if we should log something if `code < 400` or just put an assertion.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 369 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMD1cZ8R-kqMbgSRDc:-MvMD1cZ8R-kqMbgSRDd:b-d5j6j) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L369)):*
> ```Python
>         # Cleanup any files older than 5 minutes.
>         if not NO_CLEANUP:
>             self._delete_cache_files_older_than(datetime.timedelta(minutes=5))
> ```

FYI, as we discussed in the last meeting, maybe the number of files or the total file size in the `temp_directory` would be a more meaningful criterion. We don't need to address this in the PR though.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 723 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMGM6Z8OdXlT5NxYJB:-MvMGM6Z8OdXlT5NxYJC:b-y12l2k) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L723)):*
> ```Python
>     output_path = str(render_request.scene_path)
>     if render_request.image_type in {"color", "label"}:
>         output_path += ".png"
> ```

nit: might be obvious but do we strip the `.gltf` file extension from the `scene_path` already?
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMHZ4h1Fy62pzeC0f6:-MvMHZ4h1Fy62pzeC0f7:b1qttah) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L873)):*
> ```Python
>                 mime_type = "image/tiff"
> 
>             # There is no way to delete the file or run code after send_file,
> ```

nit: `,` -> `.`
___
*[geometry/render/dev/render_server/README.md, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-Mv-rTSm0egMAVAtnl1F:-MvM3Skt4qf9m8q77Rch:b-awbd66) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/README.md#L188)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI this can be removed if it is too verbose, it took me a while to understand why things had to be inverted and it ultimately derives from a bit of ambiguity in the glTF specification.  I believe this information is valuable for users to understand that it is a "world transformation".  Otherwise, like myself, they will interpret it as a model view transformation when seeing "camera matrix".  There's nothing wrong in the glTF specification, it's just a bit vague.
</blockquote></details>

Ok. I think this is great. I thought the matrix is presented in `row-major` order and thus this is worth mentioning.
One suggestion is rather than use some random numbers, how about a very basic transformation as the example instead? Such as identity orientation + [0.1, 0.2, 0.3] (or similar) translation in XYZ. That would be [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.1, 0.2, 0.3, 1.].

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16504)* status: 5 unresolved discussions, LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/render_client.cc, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvLyyr0EBj198eQCBpK:-MvPQGA16QPto3Rb57oF:bvhoslo) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_client.cc#L388)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Do we still have `server_sha256 = post_response["sha256"];` check as was in UploadScene()? Or maybe this is checked somewhere else?
</blockquote></details>

No, the "server client sha256 handshake" must happen server side if there is only one curl call.  So the client transmits the `scene_sha256`, and officially it is up to the server whether they want to check its validity or not.  Our implementation does, but it is not a requirement of the API.  Just advisable.  Since the handshake no longer happens on the client side, I moved it down into `RenderClient` since `RenderClientGltf` no longer has any specific need to compute the `sha256` of the file being sent.  Marking as Done for reviewable.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvM-ndU5XcZK0RwN5Zl:-MvPXYy76NGexmPDjj6e:b-l2tt82) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L22)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: `It's` -> `Its`
</blockquote></details>

Done, good catch!
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvM9ERgEQKhKxgZ7B-C:-MvPXbbWB26oktSM8yiP:b8mjsqe) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L180)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: I wonder if we should log something if `code < 400` or just put an assertion.
</blockquote></details>

I would advise against it, this constructor should be thought of as `noexcept` -- if an error occurs while constructing the error, the message that will get transmitted back to the client is going to just be a vague `500` response claiming Internal error:

```py
try:
    # ... call all validation code and render_callback ...
except RenderError as re:
    return re.flask_json_code_response()
except Exception as e:
        # Similar to RenderError.flask_json_code_response(), see docs.
        return (
            {
                "error": True,
                "message": f"Internal server error: {e}",
                "code": 500,
            },
            500,
        )
```

So if we `assert`, then it will just say something like `Internal server error: assertion failed 200 < 400` or something.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 723 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMGM6Z8OdXlT5NxYJB:-MvPZX6FCpXDcJwraOts:b-99xsnb) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L723)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: might be obvious but do we strip the `.gltf` file extension from the `scene_path` already?
</blockquote></details>

No, currently we do not.  The server will ultimately have `[timestamp]-color.gltf` and `[timestamp]-color.gltf.png`.

1. File extensions do not matter, this is easier to implement.  Windows usually also is agnostic to `a.b.c.png` (ignores `.b.c` and just looks at `.png`.  On Linux, the file browser and image default image viewing programs all recognize it as an image file.
2. The client never gets told the file extension.  It receives binary data, and then tries to load it as either PNG or TIFF.  If those both fail, it may load it as text if the http response code was greater than 400.

I can modify the implementation to strip `.gltf`, but the client also does the same thing -- `XYZ-color.gltf`, and if success on loading as PNG renames it `XYZ-color.gltf.png`.  Since those files ultimately all will get deleted, it did not seem worth the effort.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 873 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMHZ4h1Fy62pzeC0f6:-MvP_vnMCt_4xidZxAMG:b-l2tt82) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L873)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: `,` -> `.`
</blockquote></details>

Done, good catch!
___
*[geometry/render/dev/render_server/README.md, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-Mv-rTSm0egMAVAtnl1F:-MvPb3n-CSct4UJVpEWK:b-aujia1) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/README.md#L188)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Ok. I think this is great. I thought the matrix is presented in `row-major` order and thus this is worth mentioning.
One suggestion is rather than use some random numbers, how about a very basic transformation as the example instead? Such as identity orientation + [0.1, 0.2, 0.3] (or similar) translation in XYZ. That would be [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.1, 0.2, 0.3, 1.].
</blockquote></details>

Done, yes I think that's much cleaner -- added that example instead!

**Review by zachfang — COMMENTED** [review]
:lgtm: Resolved all the discussion points.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16504#-:-MvRpUTf2N5iFFfeXmRY:bl4zo0q)* status: 2 unresolved discussions (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_client.cc, line 388 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvLyyr0EBj198eQCBpK:-MvRGFMcCONDgXZTXjN8:bh2nij6) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_client.cc#L388)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

No, the "server client sha256 handshake" must happen server side if there is only one curl call.  So the client transmits the `scene_sha256`, and officially it is up to the server whether they want to check its validity or not.  Our implementation does, but it is not a requirement of the API.  Just advisable.  Since the handshake no longer happens on the client side, I moved it down into `RenderClient` since `RenderClientGltf` no longer has any specific need to compute the `sha256` of the file being sent.  Marking as Done for reviewable.
</blockquote></details>

OK. So we compute the `scene_sha256` in `RenderClient` and send it to the server-side for the server to check. Thanks!
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvM9ERgEQKhKxgZ7B-C:-MvRoaSGBWnxwg5JHG3q:b-y7s7m6) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L180)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I would advise against it, this constructor should be thought of as `noexcept` -- if an error occurs while constructing the error, the message that will get transmitted back to the client is going to just be a vague `500` response claiming Internal error:

```py
try:
    # ... call all validation code and render_callback ...
except RenderError as re:
    return re.flask_json_code_response()
except Exception as e:
        # Similar to RenderError.flask_json_code_response(), see docs.
        return (
            {
                "error": True,
                "message": f"Internal server error: {e}",
                "code": 500,
            },
            500,
        )
```

So if we `assert`, then it will just say something like `Internal server error: assertion failed 200 < 400` or something.
</blockquote></details>

OK. I think an assertion is a bad example. My only concern is if a user supplies an error code less than 400, the error code gets modified without the user knowing that. However, we state that explicitly in the class documentation, so it's probably enough information for that case.
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 723 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-MvMGM6Z8OdXlT5NxYJB:-MvRZOIz7vKxoWFJJWBM:b-y7xiij) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L723)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

No, currently we do not.  The server will ultimately have `[timestamp]-color.gltf` and `[timestamp]-color.gltf.png`.

1. File extensions do not matter, this is easier to implement.  Windows usually also is agnostic to `a.b.c.png` (ignores `.b.c` and just looks at `.png`.  On Linux, the file browser and image default image viewing programs all recognize it as an image file.
2. The client never gets told the file extension.  It receives binary data, and then tries to load it as either PNG or TIFF.  If those both fail, it may load it as text if the http response code was greater than 400.

I can modify the implementation to strip `.gltf`, but the client also does the same thing -- `XYZ-color.gltf`, and if success on loading as PNG renames it `XYZ-color.gltf.png`.  Since those files ultimately all will get deleted, it did not seem worth the effort.
</blockquote></details>

OK. We usually handle that with `basename` and `extension`. Since they will be deleted in most cases, we can leave them that way. 
___
*[geometry/render/dev/render_server/gltf_render_server.py, line 883 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-Mv-pC-U0Uap_tVvFTW5:-MvRJHsr-5EESO60hZfv:bo2t1j0) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L883)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This is what we were discussing re: server cleanup.  The scene file has already been deleted at this point, we could instead load the image into memory and then delete it now and provide that to [flask.send_file](https://flask.palletsprojects.com/en/2.0.x/api/#flask.send_file).  There are some related configurations like `USE_X_SENDFILE` and other server side elements.  This is all beyond my understanding of the web stack, but from what I could gather online preferring to use `send_file` with a file path is the general advice because the backend stuff (apache, nginx, others) are very good at doing this efficiently.  If you switch to using an `io.BytesIO` as described, you (a) become memory bound and (b) may lose on transfer speeds.

BUT: the reality of our situation is that even high resolution images will be on the order of megabytes, if the server does not have enough RAM to do this then it has deeper philosophical problems.  I tend to think it would be alright, and if we go the in-memory route I can remove the `_delete_cache_files_older_than(datetime.timedelta(minutes=5))` rather than fixing it to be "remove if there are more than 100 files."  In either case, since there is no state, files can only be deleted when a new request is issued since there is no way to (reliably) wrap `send_file` or execute any code after it.
</blockquote></details>

OK. SGTM.
___
*[geometry/render/dev/render_server/README.md, line 188 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-Mv-rTSm0egMAVAtnl1F:-MvREsD-4jnXFNjnVZNW:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/README.md#L188)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, yes I think that's much cleaner -- added that example instead!
</blockquote></details>

Thanks!

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16504)* status: 2 unresolved discussions (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/render_server/gltf_render_server.py, line 173 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16504#-Mv-ideb8p_7ooqDRAeE:-MvRpc-O3ahCQnY1GxGe:b-85i63v) ([raw file](https://github.com/robotlocomotion/drake/blob/bda6ca29e4789d300e3689f83ef51d2e63317dfc/geometry/render/dev/render_server/gltf_render_server.py#L173)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Refactoring discussion thread.  When removing things, it seemed natural to just refactor the server code now.  The C++ changes were insignificant, I can undo this if it makes review easier and put these changes in a different PR, but deleting the upload method and refactoring was a fairly big diff using the "dumb" implementation so I fixed it together as I encountered issues (sorry, this makes it harder to review...).

What is here is the cleanest version I think I can make.  We had discussed processing fields in some kind of loop or something.  Introducing a `RenderRequest` class and `RenderError` felt the cleanest.  There is an issue of "scope awkwardness" as seen by the previous implementation with `json_code_response` and helper methods in processing form entries.

The diff as presented here becomes confused, because `class RenderRequest` is added at the top of the file and `render_callback` moved down toward the end.

When comparing with the file currently in drake, the real changes are:

- `json_code_response` gets folded into `RenderError`, this is for the `render_callback` method's convenience to make sure the right HTTP code is being returned when signaling error messages.
- `render_callback` now just gets a single input `render_request` which has already been validated.  If an error occurs, it should `raise RenderError("why...")`.
- `upload_endpoint` is removed
- Add `RenderRequest` and `RenderError` (and `FieldType` enum).
    - `gltf_path` helper method is removed, `RenderRequest` populates `self.scene_path` during construction.
- `compute_hash` raises on bad `block_size`, docs updated
- Added documentation describing usage information at the top of the file.
</blockquote></details>

LGTM.

**Pull request merged**
