### PR TITLE
Remove last few MATLAB examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In particular:
- FurutaPendulum
- IRB140 (retaining model files)
- KneedCompassGait
- UnderwaterAcrobot

Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6421)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.
+(status: do not merge) until I've assigned additional review.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 35 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6421#-:-KnZ2Ey8BkRGBfobRhY6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge)
+@sherm1 for all review, please.

**Comment by sherm1** [comment]
:lgtm: I see that the IRB40 has its own README but the others join the README-MATLAB bulk notice. Why are they treated differently?

---

Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6421#-:-KnZbjBa1eRIvmHdSQ5z:b3phcxs)*

**Comment by jwnimmer-tri** [comment]
Because for the IRB140 directory we sill still have the model files on master, but the other directories such as UnderwaterAcrobot are removed in their entirety.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6421#-:-KnZc9C0kT6cXyVXcvBG:b-vmwlc4)*

**Pull request merged**
