### PR TITLE
Fix HPolyhedron::UniformSample Test Failure on Mac Builds.

### PR DESCRIPTION
**Pull request by cohnt**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21717)

### CODE REVIEW

**Comment by cohnt** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-nightly-everything-release, please

**Comment by cohnt** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-nightly-everything-release please

**Comment by cohnt** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Comment by cohnt** [comment]
Calling Hpolyhedron::MaybeGetFeasiblePoint requires solving a linear program, which has looser numerical tolerances than HPolyhedron::PointInSet. Apparently, on a couple Mac builds, this was leading to one of the HPolyhedron::UniformSample tests failing. I've fixed it by manually specifying a feasible point.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21717#-:-O1rRFb6EbA7YqtuIAiC:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by AlexandreAmice — COMMENTED** [review]
+@AlexandreAmice for feature review.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21717#-:-O1rRMq50xphiV6kJVJF:bszgi7m)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review, per schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21717#-:-O1rbTRM5wJvDmt4CoMg:b-g16i9n)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21717#-:-O1rmfSM9LLoroUl3rG8:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),AlexandreAmice

**Pull request merged**
