### PR TITLE
Remove two controllers from the old System1 Pendulum example.

### PR DESCRIPTION
**Pull request by sammy-tri**
Neither of these is used anymore, and SimpleFeedbackTrajectoryController should probably have never existed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3854)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@lucy-tri for feature review 
+@david-german-tri for platform review (chosen arbitrarily, feel free to reassign to another platform reviewer)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3854#-:-KUYlnz6m1Wpgnpk4aZP:b-5rqsxv)*

**Comment by Lucy-tri** [comment]
@sammy-tri can you say more about why these should be removed? I get that they are not used anymore.  SimpleFeedbackTrajectoryController looks nice and simple, but is it useless? Wrong? 
Would it be a pain to convert to system 2 and then hook up to some example? 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3854#-:-KUYum14bobUxAsT8bZe:bxx05tg)*

**Comment by david-german-tri** [comment]
:lgtm: Git remembers: we can always get unused code back if we need it in the future.  In the meantime, less code makes reading easier, and refactoring easier.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3854#-:-KUYwQIoV2ZkPo3s9mWa:b-lkuqet)*

**Comment by Lucy-tri** [comment]
:lgtm:  OK then!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3854#-:-KUYx5d86EMTt9pbHNDn:bopjvn5)*

**Comment by sammy-tri** [comment]
Quick answers for posteriry.  OpenLoopTrajectoryController has been replaced in System2 with TimeVaryingPolynomialSource and has no remaining System1 users.

SimpleFeedbackTrajectoryController was an abuse of LQR which I understand never should have been done, and it fortunately has no users anymore either.  

And as David says, git remembers.  :)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3854#-:-KUZ-xzATXJV-Kd7Yne3:b-3bfm5n)*

**Pull request merged**
