### PR TITLE
Fix issues in SnoptSolver with generic objectives / constraints bound to subsets of variables.

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2089)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/SnoptSolver.cpp, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-KFK51UYXtCDNBZ_ggj4:-KFK51UZ8bUVc8gNr7jv:-1290681370) ([raw file](https://github.com/robotlocomotion/drake/blob/f5bf1d5e268f8e41f92623a6d9527c126264b0b1/drake/solvers/SnoptSolver.cpp#L215)):*
Doesn't this result in a constraint index being skilled between the  F[constraint_index++] above and the  F[constraint_index++] below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/SnoptSolver.cpp, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-KFK51UYXtCDNBZ_ggj4:-KFKM3DOvU_-nltLUpLC:-1185789754) ([raw file](https://github.com/robotlocomotion/drake/blob/f5bf1d5e268f8e41f92623a6d9527c126264b0b1/drake/solvers/SnoptSolver.cpp#L215)):*
I don't see a use of F[constraint_index++] above this line.  Line 207 has been explicitly changed to use F[0] to sum all costs in the same entry (IIRC, this was necessary to get the test to work with multiple objectives)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Comment by ggould-tri** [comment]
*[drake/solvers/SnoptSolver.cpp, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-KFK51UYXtCDNBZ_ggj4:-KFKNaDzc4LRdqxqLFbA:-1468871857) ([raw file](https://github.com/robotlocomotion/drake/blob/f5bf1d5e268f8e41f92623a6d9527c126264b0b1/drake/solvers/SnoptSolver.cpp#L215)):*
Now I feel doubly confused about what constraint_index is doing.  It is intialized to 0 at 183, with a comment saying it starts at 1, and then incremented here.  Wouldn't it be simpler to start it at 1 at 183?  Or am I missing something obvious here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/SnoptSolver.cpp, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-KFK51UYXtCDNBZ_ggj4:-KFKSlAj5vXajhRJawZr:-2083359464) ([raw file](https://github.com/robotlocomotion/drake/blob/f5bf1d5e268f8e41f92623a6d9527c126264b0b1/drake/solvers/SnoptSolver.cpp#L215)):*
I think the current declaration positions may be misleading.  going to look at moving things around a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Comment by sammy-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/SnoptSolver.cpp, line 215 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-KFK51UYXtCDNBZ_ggj4:-KFKUGdA_mlW8ntm8F0S:469111309) ([raw file](https://github.com/robotlocomotion/drake/blob/f5bf1d5e268f8e41f92623a6d9527c126264b0b1/drake/solvers/SnoptSolver.cpp#L215)):*
Moved declarations closer to usage and changed comments a bit.  seem better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089#-:-KFKXLkT_7tNOzcJ4Mq5:1417088721)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2089)*

**Pull request merged**
