### PR TITLE
Add polynomial::EvaluatePartial

### LINKED ISSUE #7771: Add EvaluatePartial method to symbolic::Polynomial
/cc @jadecastro

### PR DESCRIPTION
**Pull request by soonho-tri**
Closes #7771 

 - The first commit renames `Monomial::Substitute` to `Monomial::EvaluatePartial` to be consistent with other symbolic classes.
 - The second commit provides `polynomial::EvaluatePartial`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7780)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jadecastro for feature-review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-:-L33rQu88Gl65UB3tT_N:b2q2fko)*

**Comment by jadecastro** [comment]
Neat, thanks @soonho-tri!
:lgtm: pending some minor things.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[common/symbolic_polynomial.h, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L352HJl46RZEJOrOl4d:-L352HJl46RZEJOrOl4e:b-hy2smi) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/symbolic_polynomial.h#L109)):*
> ```objc
>   Polynomial EvaluatePartial(const Environment& env) const;
> 
>   /** Partially evaluates this polynomial using an environment, `var ↦ c`.
> ```

BTW, technically, the user isn't supplying an Environment but rather a substitution of `var` with `c`.

---

*[common/test/symbolic_monomial_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L34pXErimPEpX03p93X:-L34pXErimPEpX03p93Y:bhcumrd) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/test/symbolic_monomial_test.cc#L106)):*
> ```cpp
>   //
>   // In one direction (left-to-right), first we convert a Monomial to an
>   // Expression using Monomial::ToExpression and call Expression::Substitution
> ```

BTW, please update this to replace `Expression::Substitution` -> `EvaluatePartial`. Ditto on the line after next.

---

*[common/test/symbolic_polynomial_test.cc, line 698 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L351XH0YB6WyriUcGRw:-L351XH0YB6WyriUcGRx:blix0qa) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/test/symbolic_polynomial_test.cc#L698)):*
> ```cpp
> TEST_F(SymbolicPolynomialTest, PartialEvaluate2) {
>   // p1 = a*xy² - a*xy + c
>   // p2 = p1[y ↦ 2.0] = (4a*x - 2a)*x + c = 2ax + c
> ```

BTW, this should read `4ax - 2ax + c = 2ax + c`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-:-L34ru-kzO3AWGVFOgIX:bai3eey)*

**Comment by soonho-tri** [comment]
Thanks!

+@ericcousineau-tri , could you platform-review this? (I'm on call tomorrow)

---

Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/symbolic_polynomial.h, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L352HJl46RZEJOrOl4d:-L35DGNg-e3OEBwH6DjG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/symbolic_polynomial.h#L109)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, technically, the user isn't supplying an Environment but rather a substitution of `var` with `c`.
</blockquote></details>

Done.

---

*[common/test/symbolic_monomial_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L34pXErimPEpX03p93X:-L35DRFBiZtHT4lp6g3E:b-om7d) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/test/symbolic_monomial_test.cc#L106)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, please update this to replace `Expression::Substitution` -> `EvaluatePartial`. Ditto on the line after next.
</blockquote></details>

Done. (I've checked that there is no `Substitute` in this file.)

---

*[common/test/symbolic_polynomial_test.cc, line 698 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L351XH0YB6WyriUcGRw:-L35EBG-hvRxkouHwT7J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f9dc2e8c5f9fa848ad9222561088dd7879e2a13/common/test/symbolic_polynomial_test.cc#L698)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, this should read `4ax - 2ax + c = 2ax + c`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-:-L35ENabc7L_dpcmmaBX:bssdp1u)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor comments questions.

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[common/symbolic_polynomial.cc, line 483 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L39Dze2YqfyVkxJc8OT:-L39Dze3j49AHzpi4Vks:b-yzq7xe) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.cc#L483)):*
> ```cpp
>     auto it = new_map.find(monomial_from_subst);
>     if (it == new_map.end()) {
>       new_map.emplace_hint(it, monomial_from_subst, new_coeff_i);
> ```

BTW Just out of curiosity, is there a performance gain for using `emplace_hint(new_map.end(), ...)` vs just `emplace(...)`?

---

*[common/symbolic_polynomial.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L36zquGlGg2KMWMuLIz:-L36zquH7jmYCw-sAeyQ:b-fhitf0) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.h#L102)):*
> ```objc
>   }
> 
>   /** Partially evaluates this polynomial using an environment @p
> ```

BTW minor nit Consistency on variable names, using `@p env` here, but then `` `var` `` below.

---

*[common/symbolic_polynomial.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L39EKPVEne2kTyoytgR:-L39EKPVEne2kTyoytgS:b6nbu2p) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.h#L111)):*
> ```objc
>   /** Partially evaluates this polynomial by substituting `var` with `c`.
>    *
>    * @throws std::runtime_error if NaN is detected during evaluation.
> ```

BTW Does this mean it will throw an error if `NaN` is either (a) a constant term in the symbolic expression, (b) the result of partial evaluation (e.g. the `0 / 0` case tested below), or (c) if `c` is NaN?

Perhaps could this could be slightly expanded to say "if NaN is detected at any point during evaluation"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-:-L39IzMPSojuZvV2Udho:b-xk6d77)*

**Comment by soonho-tri** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/symbolic_polynomial.cc, line 483 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L39Dze2YqfyVkxJc8OT:-L39iQB0MeWu6GJMd0yP:b-largg9) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.cc#L483)):*
It's my habitual pattern of writing find-and-insert-if-fail code. I thought that `emplace_hint` is more efficient than `emplace` in general. But I just read a comment from S&O saying that it's not always the case:

> Apparently, both libc++ and stdlibc++ ignore the hint for std::unordered_map. Apparently, it is useless for this container.

From https://stackoverflow.com/questions/24209592/performance-of-emplace-is-worse-than-check-followed-by-emplace#comment37381070_24209592. But I think it should be as fast as `emplace` or the difference is negligible and I'd like to keep this one.

---

*[common/symbolic_polynomial.h, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L36zquGlGg2KMWMuLIz:-L39jW8lg_zHLoKzDcgG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.h#L102)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Consistency on variable names, using `@p env` here, but then `` `var` `` below.
</blockquote></details>

Done.

---

*[common/symbolic_polynomial.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7780#-L39EKPVEne2kTyoytgR:-L3ADL8YAtli3rWWew0n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2db59d68d6430178facd5d5bb7f640cb19479790/common/symbolic_polynomial.h#L111)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Does this mean it will throw an error if `NaN` is either (a) a constant term in the symbolic expression, (b) the result of partial evaluation (e.g. the `0 / 0` case tested below), or (c) if `c` is NaN?

Perhaps could this could be slightly expanded to say "if NaN is detected at any point during evaluation"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780)*

**Comment by jadecastro** [comment]
Reviewed 4 of 5 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780)*

**Comment by jadecastro** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7780)*

**Pull request merged**
