### PR TITLE
[fem] Move ConstitutiveModel out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@seancurtis-tri for feature review please.
Please do a full review for files out of `dev/`, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603#-:-Mgrmc3R5ZEXyyoJlzHv:beytqv3)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one editorial recommendation and one *very* subtle build tweak.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603#-:-MhEYFINE8MYWykCuGv6:biwhvjx)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/BUILD.bazel, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhERtIUB8okguVew7Gs:-MhERtIV5Bmp17llK5aL:b-kxhex0) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/BUILD.bazel#L34)):*
> ```Starlark
>     ],
>     deps = [
>         "//common:essential",
> ```

nit: "//common:nice_type_name"

This is actually *broken* without it. It took me a few minutes to figure out why it's not *obviously* broken.

1. We've got SFINAE stuff going on here.
2. The *one* place where you actually depend on the `CalcFooImpl` default implementations is in the unit tests for this class.
3. The unit test includes `deformation_gradient_data` which *does* bring in nice type name. So, the unit test is perfectly happy.
4. However, there is a workflow where someone could erroneously attempt to create a constitutive model, fail to  shadow the `*Impl()` methods and get build errors.
___
*[multibody/fem/test/constitutive_model_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEXRxe1GRxgN28nTIh:-MhEXRxe1GRxgN28nTIi:bev67nc) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/test/constitutive_model_test.cc#L27)):*
nit: "is missing" is not quite correct. Invoking a "missing" function would create a compile-time error. So, they're not "missing". Also, the first and second sentences are highly redundant. How about:

> ConstitutiveModel requires derived classes to shadow the Calc____Impl(), Calc___Impl(), and Calc___Impl() methods. Failure to do so should throw a helpful exception. This implementation doesn't shadow the messages and confirms the exceptions.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ggould-tri for platform review. Because it's coming out of dev, it needs platform review on all of non-dev file contents. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603#-:-MhEYZmw8i2cixYCe7T7:b-xqbn30)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[multibody/fem/constitutive_model.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEYrX-Bokvs2UqlmxP:-MhEYrX-Bokvs2UqlmxQ:bgcmiet) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/constitutive_model.h#L106)):*
> ```objc
>    through the constructors of the derived constitutive models. */
>   ConstitutiveModel() = default;
> ```

BTW I think it's worth putting a note to future developers on why these take output parameters instead of simply returning values. We reasoned it through in a previous PR and it would be unfair to make others do the same.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[multibody/fem/BUILD.bazel, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhERtIUB8okguVew7Gs:-MhEokMsBhaHz-7T3_lG:b-eboywo) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/BUILD.bazel#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "//common:nice_type_name"

This is actually *broken* without it. It took me a few minutes to figure out why it's not *obviously* broken.

1. We've got SFINAE stuff going on here.
2. The *one* place where you actually depend on the `CalcFooImpl` default implementations is in the unit tests for this class.
3. The unit test includes `deformation_gradient_data` which *does* bring in nice type name. So, the unit test is perfectly happy.
4. However, there is a workflow where someone could erroneously attempt to create a constitutive model, fail to  shadow the `*Impl()` methods and get build errors.
</blockquote></details>

Done, thanks for the catch!
___
*[multibody/fem/test/constitutive_model_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEXRxe1GRxgN28nTIh:-MhEpE4r4SxXB-zCNDIG:b-lzq4x8) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/test/constitutive_model_test.cc#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "is missing" is not quite correct. Invoking a "missing" function would create a compile-time error. So, they're not "missing". Also, the first and second sentences are highly redundant. How about:

> ConstitutiveModel requires derived classes to shadow the Calc____Impl(), Calc___Impl(), and Calc___Impl() methods. Failure to do so should throw a helpful exception. This implementation doesn't shadow the messages and confirms the exceptions.
</blockquote></details>

Very clear! Thanks for the suggestion.
___
*[multibody/fem/constitutive_model.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEYrX-Bokvs2UqlmxP:-MhEr92v2uzjza1xX-5_:b-tcl1ct) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/constitutive_model.h#L106)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I think it's worth putting a note to future developers on why these take output parameters instead of simply returning values. We reasoned it through in a previous PR and it would be unfair to make others do the same.
</blockquote></details>

I added a note. PTAL and see if it captures the gist of the discussion.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[multibody/fem/constitutive_model.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEYrX-Bokvs2UqlmxP:-MhEyMJ2DVUjaY_1vMsW:b-w1oz8j) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fem/constitutive_model.h#L106)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I added a note. PTAL and see if it captures the gist of the discussion.
</blockquote></details>

You've captured it well. I'm content.
___
*[multibody/fem/constitutive_model.h, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEyF-j23TJN39p0am_:-MhEyF-j23TJN39p0ama:blcaqsn) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L55)):*
> ```objc
>       ElasticityElement::DoComputeData()) and thus RVO can't be used.
>    2. The output value is of type `std::array` for which there is no helpful
>       move semantic.
> ```

nit: This is your CI error. You've lost the closing `*/`.

**Review by ggould-tri — COMMENTED** [review]
checkpoint...

> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603#-:-MhF1uBWCoXJNtP_rKYC:biih4ht)* status: 5 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhErNMi1G3hs5Qxde_x:-MhErNMi1G3hs5Qxde_y:bxxdrkr) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc#L12)):*
> ```cpp
> #include "drake/multibody/fixed_fem/dev/linear_constitutive_model.h"
> #include "drake/multibody/fixed_fem/dev/test/test_utilities.h"
> ```

Minor:   Confusing that this does not move out of dev in this PR.  This file needs a @file comment or something similar explaining its nature and purpose, ie, that it tests subclasses of ConstitutiveModel, not ConstitutiveModel itself.
___
*[multibody/fem/constitutive_model.h, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEsz9TCvovTgGO_UjD:-MhEsz9TCvovTgGO_UjE:b-2o2ex4) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L15)):*
> ```objc
> namespace internal {
> 
> /* A constitutive model relates the strain to the stress of the material and
> ```

Minor:  "the material" implies that the reader knows a particular material as the one under discussion.  Absent a readme or file comment, I don't see how they would know this.  What material, or is it just "a material" ?
___
*[multibody/fem/constitutive_model.h, line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEta88Ee6GTcixZlFt:-MhEta88Ee6GTcixZlFu:b-gsm5vm) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L48)):*
> ```objc
>    Methods for calculating the energy density and its derivatives given the
>    data required for these calculations. The constitutive model expects
>    that the input data are up-to-date, but cannot verify this prerequisite. It
> ```

minor:  "up-to-date" is a very wooly concept in the world of drake and contexts and whatnot.  It would be much clearer to explain what objects / arguments must be consistent with one another.
___
*[multibody/fem/constitutive_model.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEtxDBEYAoSZE43ve2:-MhEtxDBEYAoSZE43ve3:bx1nrkl) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L57)):*
> ```objc
>       move semantic.
> 
>   /* Calculates the energy density in reference configuration, in unit J/m³,
> ```

minor:  Open-comment symbol here is redundant as you never terminated the prior comment.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 5 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: 2 unresolved discussions (waiting on @ggould-tri)

___
*[multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhErNMi1G3hs5Qxde_x:-MhFM8wo2sXEU7dCzG_2:b-pp4qme) ([raw file](https://github.com/robotlocomotion/drake/blob/2665c19738515e4f67bcd98c2763a5dfa784df12/multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc#L12)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Minor:   Confusing that this does not move out of dev in this PR.  This file needs a @file comment or something similar explaining its nature and purpose, ie, that it tests subclasses of ConstitutiveModel, not ConstitutiveModel itself.
</blockquote></details>

Done, I added a comment in the `.h` file.
___
*[multibody/fem/constitutive_model.h, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEsz9TCvovTgGO_UjD:-MhFL7RfA6i-yGsew33c:b-mnvdk2) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Minor:  "the material" implies that the reader knows a particular material as the one under discussion.  Absent a readme or file comment, I don't see how they would know this.  What material, or is it just "a material" ?
</blockquote></details>

It doesn't refer to any particular material and like you said it should be "a material".
___
*[multibody/fem/constitutive_model.h, line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15603#-MhEta88Ee6GTcixZlFt:-MhFMtly-FtbA3w2TTDo:b-slmym) ([raw file](https://github.com/robotlocomotion/drake/blob/abee8e8c306513b023d5c1ac0661c9933f7e02d7/multibody/fem/constitutive_model.h#L48)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  "up-to-date" is a very wooly concept in the world of drake and contexts and whatnot.  It would be much clearer to explain what objects / arguments must be consistent with one another.
</blockquote></details>

Looking more closely at these comments again, I think it's best *not* to imply there's any potential caching mechanism going on in the background. PTAL at the updated language.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15603)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
