### PR TITLE
Move libdrake install into tools/install/libdrake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7322)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/BUILD.bazel, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7322#-KxDH52kPkOF60jllLPv:-KxDH52kPkOF60jllLPw:b-pkcjws) ([raw file](https://github.com/robotlocomotion/drake/blob/bf30514d0c9b0807ebce5162f92d53d2533e3e30/drake/bindings/BUILD.bazel#L131)):*
> ```
>     py_strip_prefix = ["python"],
>     visibility = ["//visibility:public"],
>     deps = ["//drake:install"],
> ```

FYI to reviewers...

Rather than being updated to the new path, this is removed because of our discussions in #6772 and related PRs -- we do not want to try to curate smaller separate `:install` targets that work on their own -- we merely want this target to name its own deps, and we'll let the root-level install target grab everything it needs.

---

*[tools/install/libdrake/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7322#-KxDIKGsQ3S1kg5ZlI-F:-KxDIKGsQ3S1kg5ZlI-G:b-1wgnoq) ([raw file](https://github.com/robotlocomotion/drake/blob/36087d7c767d5a429e181127336f418b41e952a8/tools/install/libdrake/BUILD.bazel#L1)):*
> ```
> # -*- python -*-
> ```

FYI to reviewers...

This file has mostly been moved, but GitHub isn't showing it as such.  Here's a [diff from gitk](https://gist.github.com/jwnimmer-tri/1997ed1340f2f45560dfa7d033496637), for reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7322)*

**Comment by jwnimmer-tri** [comment]
N.B.: `priority low`.

+@jamiesnape for feature review, please?
+@SeanCurtis-tri for platform review per rotation, please.

I am not a 100% fan of the folder name `libdrake`, but I figure at least putting it all into once place is a good start?  Open to suggestions, or design debates on the whole premise.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: for platform I don't have a strong opinion about `libdrake`; it's evocative.

---

Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7322#-:-KxJQvmSA0w1gjVmiQnL:bbj80h5)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7322#-:-KxJTJxOektH-JpHghkM:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 16 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7322)*

**Pull request merged**
