### PR TITLE
Added minimal configuration to supported list.

### PR DESCRIPTION
**Pull request by jhoare**
Towards #2962

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3092)

### CODE REVIEW

**Comment by jhoare** [comment]
+@jwnimmer-tri Please, as the owner of #2962

**Comment by jwnimmer-tri** [comment]
I think the changes to the configuration table look good.

I think the "Minimal" term used in the table needs some kind of legend entry or explanation, though -- clarifying what the scope of minimal means.  I don't think it's as simple as "turn off all _WITH_FOO_ options", because Eigen and googletest (and more?) are required, even though they have WITH options.

I'd be satisfied in this PR if there was merely some text in this document explaining what Minimal means specifically.  However in the future, I'd love to make this all more scripted -- in other words, some kind of "minimal toggle" in the setup scripts that gives a user one-stop-shopping to turn off all of the default-but-optional superbuild deps.  If adding that to the superbuild seems easier than listing the details here, I'm also fine with that solution.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3092#-:-KOjnQmWAE7V39hplzkK:bv6qtit)*

**Comment by jhoare** [comment]
You're right, I added some explanation as to what a "Minimal" configuration actually is, and how to configure it. 

I also agree that it should be more automated, but when that is done in the future the language in the document should be updated to reflect that. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3092#-:-KOkE2xiIns5CvwtWjip:byqz0qp)*

**Comment by jwnimmer-tri** [comment]
Feature :lgtm: Thanks for this.

I'll ask +@david-german-tri for platform review and merge.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3092#-:-KOkNS-KwOyWpQX1qJ1o:b3zo271)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/developers.rst, line 82 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3092#-KOkPVGpOn2Sh2RilD6g:-KOkPVGpOn2Sh2RilD6h:bh23msl) ([raw file](https://github.com/robotlocomotion/drake/blob/c1d1a3176465c1a5f974e23df5791545768e6362/drake/doc/developers.rst#L82)):*
> ```reStructuredText
> the superbuild. This is configured by turning off all externals using
> ``ccmake`` or ``cmake-gui`` except for ``WITH_EIGEN`` and ``WITH_GOOGLETEST``
> which should be set to ``ON``.
> ```

BTW, I guess this means #2626 was resolved at some point?  @liangfok 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3092#-:-KOkPiTkGKy8OvdH5slO:bnfp4nl)*

**Pull request merged**
