### PR TITLE
Use the new AddLorentzConeConstraint API

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5450)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-:-KejiQ2kCsS6BLgWagcc:b-e8hf3g)*

**Comment by RussTedrake** [comment]
much cleaner.  :lgtm: !

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-:-Kf1Jkx9zmerWBddGnAE:b-a5wqul)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-:-Kf55soKBHs97j7MalGX:b6vi582)*

**Comment by sherm1** [comment]
Platform: a couple BTWs, then :lgtm:.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-Kf8tLyKlAP3Bi03PJbj:-Kf8tLyKlAP3Bi03PJbk:b336c81) ([raw file](https://github.com/robotlocomotion/drake/blob/273094b3e117058bdc8662c8f28afe41d4a66981/drake/solvers/test/rotation_constraint_test.cc#L20)):*
> ```cpp
> 
> namespace drake {
> namespace solvers {
> ```

BTW, tests should be in an anonymous namespace.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-Kf8tZ_jbZdzfAseyQpw:-Kf8tZ_jbZdzfAseyQpx:b-o7mw8m) ([raw file](https://github.com/robotlocomotion/drake/blob/273094b3e117058bdc8662c8f28afe41d4a66981/drake/solvers/test/rotation_constraint_test.cc#L31)):*
> ```cpp
>       prog->NewContinuousVariables<1, 1>("sigma");
>   prog->AddLorentzConeConstraint(sigma(0),
>                                  (R_error.transpose() * R_error).trace());
> ```

BTW, it isn't obvious to me why this calculation and trace are the right constraint to use. Can you add an explanation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-:-Kf8tu7PosdMtf9FM0bO:b-9ibxh8)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-Kf8tLyKlAP3Bi03PJbj:-Kf9-klKlFxrgp00x8us:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/273094b3e117058bdc8662c8f28afe41d4a66981/drake/solvers/test/rotation_constraint_test.cc#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, tests should be in an anonymous namespace.
</blockquote></details>

Done.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5450#-Kf8tZ_jbZdzfAseyQpw:-Kf9-lFEzBAZw1RUMQ5W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/273094b3e117058bdc8662c8f28afe41d4a66981/drake/solvers/test/rotation_constraint_test.cc#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, it isn't obvious to me why this calculation and trace are the right constraint to use. Can you add an explanation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5450)*

**Pull request merged**
