### PR TITLE
Add lorentz cone

### LINKED ISSUE #3676: clean up SOCP
The current implementation of SOCP is for Mosek only. It also comes with a file `mosek_wrapper.h`. The goal is to

 - [x] Add `LorentzConeConstraint` and `RotatedLorentzConeConstraint`. These two constraints would enforce 
```
x_0 >= sqrt(x_1^2+...+x_N^2) // Lorentz cone constraint
x_0*x_1 >= x_2^2+...+x_N^2 , x_0>=0, x_1>=0 // rotated Lorentz cone constraint
```
for a second order cone problem. If the problem has other nonlinear nonconvex constraints, these two conic constraint will be enforced as general nonlinear constraints.
 - [x] Add support for Lorentz cone and rotated Lorentz cone constraints in Gurobi.
 - [x] Merge mosek_wrapper.h into mosek_solver.h.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Add `LorentzConeConstraint` and `RotatedLorentzCone` constraint to `constraint.h`. Partially resolves #3676

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3753)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@naveenoid for feature review, +@sherm1 for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KTkXhc0ywqyAsKTITPf:b-nf3r1r)*

**Comment by sherm1** [comment]
Punting to Tuesday's platform reviewer: +@david-german-tri -@sherm1

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KTlw1uoQDTPYaQ3mLzb:b-1xdukz)*

**Comment by david-german-tri** [comment]
I'll await feature review on this; please ping me once it's done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KTo48XDYsz-eG_2ahcP:bgtm0fz)*

**Comment by naveenoid** [comment]
Maybe you can already consider test coverage for this constraint using one of the generic nonlinear solver?

One pass completed, PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/constraint.h, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KTqcm2Xv8tRAvNySWVI:-KTqcm2YJ_QpYy_ALvJY:b-4pzc78) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd901a1b80489d864cb66a301fcaf990ed888c6/drake/solvers/constraint.h#L184)):*
> ```objc
>  x_1 >= 0 \\
>  x_1^2-x_2^2-...-x_n^2 >= 0
>  \f]
> ```

BTW : Consider including a reference to the comment above. (Boyd and Vandenberghe?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KTwMuxWyF4SoPBTQfCy:b-id5glt)*

**Comment by hongkai-dai** [comment]
@naveenoid I think adding the test using nonlinear solver is a great idea. I have tried to add it into this PR, but later I realized it is better to include it in my next PR, in which the Lorentz cone is handled by an SOCP solver. They both involve storing and parsing Lorentz cone in `mathematical_program.h`, by either solving it as a generic nonlinear optimization problem, or a convex SOCP problem; so it is better to handle the solver issue in one PR.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/constraint.h, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KTqcm2Xv8tRAvNySWVI:-KU-VlvmLrf6JqoNvty9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8bd901a1b80489d864cb66a301fcaf990ed888c6/drake/solvers/constraint.h#L184)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : Consider including a reference to the comment above. (Boyd and Vandenberghe?)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KU0Gxb2Gai79djLSTRZ:b-p88rib)*

**Comment by naveenoid** [comment]
BTW: Ok I agree but please leave a todo in mathematical_program_test or in the comments before the definition of the LorentzConeConstraint  noting that a test will be added by you in the future. In case of delays this is a same option.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KU0gSaH2bzTyh_hzscs:b-bxtxo6)*

**Comment by naveenoid** [comment]
:lgtm: Except for my comment above

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KU0hKJKbZ-BnLc4nHab:b-i2ffl5)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KU0qJRLh5fyFJ3u6OYv:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Thanks @naveenoid for feature review, @david-german-tri ready for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KU0wDLTdMx-zikMNMwS:bx3y376)*

**Comment by hongkai-dai** [comment]
-@david-german-tri for platform review, +@sherm1 for platform review since it is almost Monday

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KUFnTQjKIWhIpAKQNRZ:b-3s9dhh)*

**Comment by sherm1** [comment]
Platform: some minor BTWs to be addressed, then :lgtm:.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/constraint.h, line 187 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUISkc_q1fe6-03swGL:-KUISkc_q1fe6-03swGM:b-21szo) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/constraint.h#L187)):*
> ```objc
>  For more information and visualization, please refer to
>  https://inst.eecs.berkeley.edu/~ee127a/book/login/l_socp_soc.html
>  */
> ```

BTW, this is a great class comment! Very clear and helpful.

---

*[drake/solvers/constraint.h, line 224 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIUNBY4sZaJ-KZVSVK:-KUIUNBZdU9ZbGVzMZP6:b-fmlnwo) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/constraint.h#L224)):*
> ```objc
>  * \f[
>  * x_0 >= 0
>  * x_1 >=0
> ```

BTW, missing space

---

*[drake/solvers/constraint.h, line 225 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIUaHRJxDh4Z6KNxzQ:-KUIUaHRJxDh4Z6KNxzR:b7m5ljj) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/constraint.h#L225)):*
> ```objc
>  * x_0 >= 0
>  * x_1 >=0
>  * x_0*x_1 -x_2^2 - x_3^2 - .. - x_n^2 >=0
> ```

BTW, this looks like the same constraint as above, just with the RHS terms moved to the LHS. That wouldn't change gradient continuity. Is this right?

---

*[drake/solvers/test/constraint_test.cc, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVSVDr3Oe9TuqVf1x:-KUIVSVEGcqQlvILqnTJ:b-8rnnep) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L19)):*
> ```cpp
> namespace {
> 
> // Tests if the Lorentz Cone constraint is imposed correctly
> ```

BTW, missing period.

---

*[drake/solvers/test/constraint_test.cc, line 71 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVm7q9BTv-LfV8Ot4:-KUIVm7q9BTv-LfV8Ot5:b6xgruq) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L71)):*
> ```cpp
>   EXPECT_TRUE(is_in_cone == is_in_cone_expected);
> 
>   // Eval with taylor var
> ```

BTW, periods (also in other comments below).

---

*[drake/solvers/test/constraint_test.cc, line 92 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVusj3znwflLNCVtt:-KUIVusj3znwflLNCVtu:b8cqyw) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L92)):*
> ```cpp
> }
> 
> GTEST_TEST(testConstraint, testLorentaConeConstraint) {
> ```

BTW, typo in test name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KUIWYHvCBR_5u9BP5Mq:b-uygjrf)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/constraint.h, line 224 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIUNBY4sZaJ-KZVSVK:-KUI_yYuWAJg-GjC3fBh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/constraint.h#L224)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, missing space
</details>
Done.

---

*[drake/solvers/constraint.h, line 225 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIUaHRJxDh4Z6KNxzQ:-KUIaBps57w60v4dJg_G:b9nlb5d) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/constraint.h#L225)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this looks like the same constraint as above, just with the RHS terms moved to the LHS. That wouldn't change gradient continuity. Is this right?
</details>
Done. You are right. I delete this part to as it does not add any more information.

---

*[drake/solvers/test/constraint_test.cc, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVSVDr3Oe9TuqVf1x:-KUIaOybN-APlVGAHO0p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, missing period.
</details>
Done.

---

*[drake/solvers/test/constraint_test.cc, line 71 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVm7q9BTv-LfV8Ot4:-KUIaSTr2SlM8Lu5pG2d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, periods (also in other comments below).
</details>
Done.

---

*[drake/solvers/test/constraint_test.cc, line 92 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-KUIVusj3znwflLNCVtt:-KUIa_IkFbo5LV1Z0eTv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71f007d51c62746a248b487bb69ecc256a5b9cd2/drake/solvers/test/constraint_test.cc#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, typo in test name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3753#-:-KUJFpscyo6sEvE9hkc3:bnfp4nl)*

**Pull request merged**
