### PR TITLE
Attempting to fix Win32 SEH exception by disabling alignment.

### PR DESCRIPTION
**Pull request by liangfok**
I hope this resolves the following error on Win32 continuous:

```
12:50:15 [ RUN      ] SimulationTerminationTest.TerminationConditionDefault
12:50:15 unknown file: error: SEH exception with code 0xc0000005 thrown in SetUp().
12:50:15 [  FAILED  ] SimulationTerminationTest.TerminationConditionDefault (0 ms)
12:50:15 [ RUN      ] SimulationTerminationTest.TerminationConditionAfterHalfSecond
12:50:15 unknown file: error: SEH exception with code 0xc0000005 thrown in SetUp().
12:50:15 [  FAILED  ] SimulationTerminationTest.TerminationConditionAfterHalfSecond (0 ms)
12:50:15 [ RUN      ] SimulationTerminationTest.TerminationConditionTrue
12:50:15 unknown file: error: SEH exception with code 0xc0000005 thrown in SetUp().
12:50:15 [  FAILED  ] SimulationTerminationTest.TerminationConditionTrue (0 ms)
12:50:15 [----------] 3 tests from SimulationTerminationTest (0 ms total)
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2679)

### CODE REVIEW

**Comment by liangfok** [comment]
I started a Win32-continuous-debug test here: 

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/14/

**Comment by liangfok** [comment]
Trying `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/15/

**Comment by liangfok** [comment]
This PR passed the following Win32-continuous-debug test:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/15/console

Thus, once CI passes, I believe this PR is ready to be merged.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2679#-:-KLN5LqJIBB2y9zym_8b:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge.  Linux-matlab and osx aren't going to tell us anything new.

**Comment by sherm1** [comment]
This does argue in favor of @RussTedrake's contention that the Win32 build provides useful information, particularly about Eigen alignment problems. The alignment error was there in the other builds also but happens to work out OK on 64 bit platforms. When we switch to Eigen 3 with 32 byte alignment for AVX I *think* the 64 bit platforms will also show problems.

**Comment by mwoehlke-kitware** [comment]
https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=43109 "Second verse, same as the first..."

@liangfok, @amcastro-tri, can one of you take a look? Seems to be the same error that was just fixed. (And... I'm not spotting the PR that broke it?)

**Comment by liangfok** [comment]
Yup! @amcastro-tri should be submitting a PR shortly.

**Comment by liangfok** [comment]
I believe this is the PR that broke it: https://github.com/RobotLocomotion/drake/pull/2596

**Comment by amcastro-tri** [comment]
I just pushed #2684. PTAL

**Pull request merged**
