### PR TITLE
[plant] Enable AddMultibodyPlantSceneGraph for Expression

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #16571.  Towards #16476.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16585)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@joemasterjohn for feature review, please?

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with one small nit. +@ggould-tri for platform review, please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16585#-:-MvtNBa7ALUcNX508fmA:bcx1c4)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

___
*[multibody/plant/test/multibody_plant_scalar_conversion_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16585#-MvtMeLR4fjjK2oGgRPC:-MvtMeLR4fjjK2oGgRPD:bhim2w6) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc6d81f68302c42ea50840208018fcd33c8268e/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L158)):*
> ```cpp
> 
> using NonDoubleScalarTypes = ::testing::Types<AutoDiffXd, Expression>;
> INSTANTIATE_TYPED_TEST_SUITE_P(My, MultibodyPlantDefaultScalarsTest,
> ```

nit: Can the instantiation name be more informative? `My` -> `NonDoubleScalarTypesTest`.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16585)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

___
*[multibody/plant/test/multibody_plant_scalar_conversion_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16585#-MvtMeLR4fjjK2oGgRPC:-MvtSDt76gv-_qIxaG2z:b-7217do) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc6d81f68302c42ea50840208018fcd33c8268e/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L158)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The "My" is what [googletest docs](https://google.github.io/googletest/advanced.html#type-parameterized-tests) suggest.

Here's what `bazel-bin/multibody/plant/multibody_plant_scalar_conversion_test --gtest_list_tests` shows for the test case names:

```console
My/MultibodyPlantDefaultScalarsTest/0.  # TypeParam = Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1> >
  RevoluteJointAndSpring
  PortIndexOrdering
  DirectlyAdded
My/MultibodyPlantDefaultScalarsTest/1.  # TypeParam = drake::symbolic::Expression
  RevoluteJointAndSpring
  PortIndexOrdering
  DirectlyAdded
ScalarConversionTest.
  ExternalComponent
```

If we had multiple different packs all applied to the same test cases, then I think a more specific name might make sense, but in this case I think the brevity is nice?
</blockquote></details>

OK, since there is only one pack of types I'll concede that the brevity of the convention wins out.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16585#-:-MvtUqfP3iw6iHeRr9hf:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),joemasterjohn (waiting on @jwnimmer-tri)

**Pull request merged**
