### PR TITLE
Switch to ignition-math4.

### PR DESCRIPTION
**Pull request by clalancette**
This is going to be needed to move to newer versions of ignition
libraries, newer sdformat, and for delphyne going forward.  While
we are at it, make ignition-math a shared library.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7622)

### CODE REVIEW

**Comment by clalancette** [comment]
@caguero FYI

**Comment by nuclearsandwich** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by clalancette** [comment]
The macOS failures here were caused by #7439 , and fixed by 96d1681562dbdf8f58e952a929e93f5a6dd4fe4d , so unrelated to this PR.

**Comment by clalancette** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by clalancette** [comment]
Rebased onto the latest.

**Comment by clalancette** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by clalancette** [comment]
@drake-jenkins-bot retest this please

**Comment by clalancette** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by clalancette** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
+@jamiesnape for feature review.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-:-L0pkuSCZWqpnuzavBPK:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/ignition_math/ignition_math.BUILD.bazel, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-L0pqnFzb6ltCaP-Ud4d:-L0pqnG-t-QytagHEC3y:b-mde3y9) ([raw file](https://github.com/robotlocomotion/drake/blob/3f91c0adf17ef986873f7cc680039464a10ecd18/tools/workspace/ignition_math/ignition_math.BUILD.bazel#L54)):*
> ```
> )
> 
> public_headers_no_gen = [
> ```

I'm confused by this name.  Why do we call it `no_gen` but then add to it the `Export.hh` that we just genruled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622)*

**Comment by clalancette** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/workspace/ignition_math/ignition_math.BUILD.bazel, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-L0pqnFzb6ltCaP-Ud4d:-L1xInVCpFF-0WGKeIy8:b-yu4pcj) ([raw file](https://github.com/robotlocomotion/drake/blob/3f91c0adf17ef986873f7cc680039464a10ecd18/tools/workspace/ignition_math/ignition_math.BUILD.bazel#L54)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I'm confused by this name.  Why do we call it `no_gen` but then add to it the `Export.hh` that we just genruled?
</blockquote></details>

Yeah, good point.  I'll move the `Export.hh` out of there and into the list of generated files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622)*

**Comment by clalancette** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-:-L1xKWC54ggMAzvU1-sN:bnfp4nl)*

**Comment by clalancette** [comment]
This passed review, and passes all tests.  I'm not sure what the merge procedure is (@jwnimmer-tri has merged all of my PRs in the past).  Should I just go ahead and merge it?

**Comment by ggould-tri** [comment]
If the merge button in the upper right is green, go ahead and hit it.
If for some reason it is not, let me know and I will take care of it for you.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-:-L20RkFdu2LCTL3uHJ0z:b-llazj2)*

**Comment by clalancette** [comment]
I see the green button, so I'll merge.  Thanks @ggould-tri .

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7622#-:-L20SXpiGoL37ySrwh8q:b-2pz0ke)*

**Pull request merged**
