### PR TITLE
pydrake: Bind TrajectoryAffineSystem

### PR DESCRIPTION
**Pull request by avalenzu**
This is all pattern-matched off of the bindings for `AffineSystem()`. This also adds a binding for `PiecewisePolynomial` addition, which is useful when preparing the trajectories to be passed to `TrajectoryAffineSystem`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@ericcousineau-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009#-:-MGJdSbb3SBC1Gd1WkZa:b-7eskas)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/systems/primitives_py.cc, line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14009#-MGJeBP-5CpX1lGY42XE:-MGJhdjd9GNxZBGdAg4a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/575afc89e9a6e5e016337109df6f9e93bce8cb52/bindings/pydrake/systems/primitives_py.cc#L362)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Methods below here are missing tests.

Can you add basic acceptance tests?
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14009#-MGJe5h30Vkm3GVrOGMD:-MGJhefv6Dj7QAgyBlAF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/575afc89e9a6e5e016337109df6f9e93bce8cb52/bindings/pydrake/systems/test/primitives_test.py#L230)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For all functions / constructors that have named `py::arg`, can you ensure you test those?
e.g..
`configure_random_state(covariance=...)`
</blockquote></details>

Done.

**Review by avalenzu — COMMENTED** [review]
Comments addressed. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009#-:-MGJizTLBLkhPITlW3xV:baz6201)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:
I'm good to serve as platform for this small PR
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009#-:-MGJpUZnC7GGJlgk79lj:b-jurgqd)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by avalenzu — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14009#-:-MGJp_uS4GqEFP3FL-DG:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Comment by EricCousineau-TRI** [comment]
Uh oh! I should've let you assign the tag :P
Will stick with squashing then!

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds

**Comment by avalenzu** [comment]
Thanks!

**Pull request merged**
