### PR TITLE
Improves Compiler Version Error Message

### PR DESCRIPTION
**Pull request by liangfok**
Adds the version detected to the error message. This is useful for debugging.

Here's an example of what the user sees when the wrong compiler version is found:
```
$ ninja
[1/1] Re-running CMake...
FAILED: /home/liang/tools/cmake-3.5.2-Linux-x86_64/bin/cmake -H/home/liang/dev/drake-distro-2 -B/home/liang/dev/drake-distro-2/build
-- CMAKE_INSTALL_PREFIX=/home/liang/dev/drake-distro-2/build/install
CMake Error at cmake/config.cmake:21 (message):
  Clang version must be at least 3.9 (detected version 3.7.1)
Call Stack (most recent call first):
  cmake/config.cmake:143 (drake_check_compiler)
  cmake/config.cmake:248 (drake_setup_compiler)
  CMakeLists.txt:14 (drake_setup_platform)


-- Configuring incomplete, errors occurred!
See also "/home/liang/dev/drake-distro-2/build/CMakeFiles/CMakeOutput.log".
ninja: error: rebuilding 'build.ninja': subcommand failed
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4150)

### CODE REVIEW

**Comment by liangfok** [comment]
+@mwoehlke-kitware for feature review please.
+@david-german-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4150#-:-KWnteHe1jtD8dE0YOam:b-xssbo1)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:, provided it gets rebased/squashed/something before merge (unless the icky history is just github being stupid)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4150#-:-KWnv7h91Er0f3orl9t2:b4qn0gq)*

**Comment by david-german-tri** [comment]
:lgtm: with same caveat

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4150#-:-KWo4cd5hSXcnfEbIsBw:b-syb1bl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4150)*

**Pull request merged**
