### PR TITLE
Fix Wunused-parameter in automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5990)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5990#-:-Kj4dBDfwy53P4tcXJko:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per rotation, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5990#-:-Kj4gVRFhLh9O2ls6Qvl:b-eb2cxg)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5990#-:-Kj4pVhv4yeH0RK_6_XQ:bnfp4nl)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5990#-:-Kj53j666Ooax69UDMN1:bzdwe9o)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Pull request merged**
