### PR TITLE
[workspace] Build VTK-vendored third-party code with hidden symbols

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review (or delegation?), please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346#-:-NgUQ9Nl4YVda4bEkHEM:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346)* status: LGTM missing from assignee sherm1(platform)

___
*[`tools/install/libdrake/test/exported_symbols_test.py` line 44 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20346#-NgUnWLU2bWDEFxZsq1n:-NgUnWLU2bWDEFxZsq1o:b-2iq6td) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfa519d69694b8619979fec857afd1cc0b319e85/tools/install/libdrake/test/exported_symbols_test.py#L44)):*
> ```Python
>     # Symbols from Drake's vendored externals are fine. (It would be better
>     # for performance if they could be hidden, but they are not hazardous.)
>     "drake_vendor",
> ```

FYI This is for `glew` which uses C symbols (so no C++ "N12" mangling prefix).

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346#-:-NgVTy8-2FkfDFVhHDhk:b8qx53o)* status: 1 unresolved discussion

___
*[`tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20346#-NgVQ72R0AbvkRVERjFo:-NgVQ72R0AbvkRVERjFp:b-emiq3h) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfa519d69694b8619979fec857afd1cc0b319e85/tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch#L8)):*
> ```Diff
> +++ ThirdParty/doubleconversion/vtkdoubleconversion/double-conversion/utils.h
> @@ -31,7 +31,7 @@
>  // XXX(kitware): // include exports header
> ```

BTW is the "XXX" here a convention I'm unaware of?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20346)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

___
*[`tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20346#-NgVQ72R0AbvkRVERjFo:-NgVVzI45VbHOqf3pKcf:bohbrar) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfa519d69694b8619979fec857afd1cc0b319e85/tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is the "XXX" here a convention I'm unaware of?
</blockquote></details>

Sorry, no idea :man_shrugging:.  Possibly its a way for Kitware to mark places they changed the first-party code?  Anyway, its part of the upstream code (unified diff context), nothing we did in Drake.

**Pull request merged**
