### PR TITLE
multibody: Remove redundant syntax for DeclareCacheEntry

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Discovered as part of #15161 audit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15176)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.

Feel free to ping or delegate to @amcastro-tri or @sherm1 you're uncertain about any sections of this code.

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
Feel free to unassign yourself @xuchenhan-tri, I did a full pass. 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15176#-:-Mbv8tINC7Nz2RjcUrpO:bxgwr54)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/plant/multibody_plant.cc, line 2883 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15176#-Mbv8bgN65W8y6A1-FJi:-Mbv8bgN65W8y6A1-FJj:b-zbagn9) ([raw file](https://github.com/robotlocomotion/drake/blob/267829db3d41f235d6b80ab033744dd335efa76c/multibody/plant/multibody_plant.cc#L2883)):*
> ```cpp
>       is_discrete() ?
>           &MultibodyPlant<T>::CalcContactResultsDiscrete :
>           &MultibodyPlant<T>::CalcContactResultsContinuous,
> ```

btw, beautiful, I had no idea this would even compile.

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri thanks! -@xuchenhan-tri 
Looks like the only hold out that returns a value in MbP is gone now.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15176#-:-Mbw8pIbE1QaI-yKqK2k:b-kpipot)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15176)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule (on Monday), please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform - yay fewer overloads in use!
Also, woot for reusing memory!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15176#-:-McA_rbJ-nqB6EluZb78:bstfxpl)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
