### PR TITLE
release_playbook: Minor formatting fixes for URLs

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Use `<url>` instead of `[url](url)`
Ensure `<url>` is used instead of `url`; otherwise, URL may not render
Add backticks around GitHub username

Minor fixes to follow-up on #15207

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15236)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for both reviews, please!

+(priority: low) +(status: single reviewer ok) 

\cc @jwnimmer-tri @ggould-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15236#-:-Mcu0mf-C-T9-VRyCEoF:bjeybt1)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by EricCousineau-TRI** [comment]
Preview:
```
$ bazel run //doc:pages -- --serve
$ firefox http://127.0.0.1:8000/release_playbook.html  # zoom: 50%
```

Before:
> image
After:
> image

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15236#-:-Mcu42TM4rwjCAlXaH2y:bnfp4nl)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[doc/_pages/release_playbook.md, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15236#-Mcu3z9oCgoSUcT7GhbY:-Mcu3z9pD-8Wmpjq2cbG:b-3f2bz) ([raw file](https://github.com/robotlocomotion/drake/blob/aaca2ecb9c393f822604361c7d62302bbce71f48/doc/_pages/release_playbook.md#L123)):*
> ```Markdown
>    1. After merge, go to <https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-bionic-unprovisioned-gcc-bazel-nightly-documentation/> and push "Build now".
>       * If you don't have "Build now" click "Log in" first in upper right.
> 12. Open [https://github.com/RobotLocomotion/drake/releases](https://github.com/RobotLocomotion/drake/releases) and choose "Draft a
> ```

nit: you could also update this one for consistency.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15236)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[doc/_pages/release_playbook.md, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15236#-Mcu3z9oCgoSUcT7GhbY:-McutkS92rG97-c6bT2S:b-896fja) ([raw file](https://github.com/robotlocomotion/drake/blob/aaca2ecb9c393f822604361c7d62302bbce71f48/doc/_pages/release_playbook.md#L123)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: you could also update this one for consistency.
</blockquote></details>

Done!

**Comment by EricCousineau-TRI** [comment]
Skipping builds for trivial change

**Pull request merged**
