### PR TITLE
Add both static and dynamic sized variables

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously we have separate APIs to add static and dynamic sized variables. This causes issue if we have a function that adds new variables whose size depends on the input argument, that we cannot use a unified API to handle both cases. For example
```C++
template<Derived>
void foo(const Derived& x) {
  MathematicalProgram prog;
  auto y_static = prog.NewContinuousVariables<Derived::RowsAtCompileTime>(); // If Derived has a static size at compile time.
  auto y_dynamic = prog.NewContinuousVariables(x.rows()); // If Derived has a dynamic size at compile time.
}
```
Namely I cannot use one single API to handle both cases for static and dynamic size.
Now with the newly introduced API, we can do
```C++
template<typename Derived>
void foo(const Derived& x) {
  MathematicalProgram prog;
  auto y = prog.NewContinuousVariables<Derived::RowsAtCompileTime, Derived::ColsAtCompileTime>(x.rows(), x.cols()); // This works for both static-sized x and dynamic-sized x
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6516)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoLGiObkxNT4Dng3hCd:bpno49v)*

**Comment by soonho-tri** [comment]
Checkpoint.

BTW, please feel free to find another feature-reviewer for this PR. I can wear my platform-reviewer hat.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNGNEMlYgfqE51bZzC:-KoNGNEMlYgfqE51bZzD:b-v1lzua) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L201)):*
> ```objc
>    */
> template <int Size>
> struct NewVariableNameType {
> ```

FYI Usually typenames don't end in `Type` because it's redundant. (No defect though, if you feel strongly about it.)

---

*[drake/solvers/mathematical_program.h, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNJmxVpj4JGQZlrFgF:-KoNJmxVpj4JGQZlrFgG:bg8e4oq) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L219)):*
> ```objc
> template <typename Derived>
> void SetVariableNames(const std::string& name, int rows, int cols,
>                       Derived* names) {
> ```

How about having the following here? (or `DRAKE_ASSERT`). Also add a documentation such as `@pre The size of @p names is @p rows * @p cols.`?
```c++
DRAKE_DEMAND(static_cast<int>(names->size()) == rows * cols);
```

---

*[drake/solvers/mathematical_program.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNKUlYsdnaOgwasCkk:-KoNKUlYsdnaOgwasCkl:b-oqdxks) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L255)):*
> ```objc
>    * @tparam Rows  The number of rows in the new variables.
>    * @param name The name of the newly added variables
>    * @return The MatrixDecisionVariable of size rows x cols, containing the new
> ```

This part needs to be updated. For example `MatrixDecisionVariable` -> `VectorDecisionVariable`.

---

*[drake/solvers/mathematical_program.h, line 289 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNKrum8Rm_Cn6CSyAD:-KoNKrum8Rm_Cn6CSyAE:b9ehikl) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L289)):*
> ```objc
>    * Adds continuous variables, appending them to an internal vector of any
>    * existing vars.
>    * This is equivalent to NewContinuousVariables<Rows, Cols>(name). We create
> ```

BTW, this paragraph can be re-flowed:
```
   * This is equivalent to NewContinuousVariables<Rows, Cols>(name). We create
   * this function so that we can use NewContinuousVariables<Rows, Cols>(rows,
   * cols, name) for both static and dynamic sized new variables.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoNMgCBgpGDL3UBHM_Z:b-t3hq4g)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNGNEMlYgfqE51bZzC:-KoNhRXu57oYIaXUobIj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L201)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI Usually typenames don't end in `Type` because it's redundant. (No defect though, if you feel strongly about it.)
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNJmxVpj4JGQZlrFgF:-KoNhfTK7GQGAsHF4eN6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L219)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

How about having the following here? (or `DRAKE_ASSERT`). Also add a documentation such as `@pre The size of @p names is @p rows * @p cols.`?
```c++
DRAKE_DEMAND(static_cast<int>(names->size()) == rows * cols);
```
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNKUlYsdnaOgwasCkk:-KoNhxa646pmeBnRv6Ry:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L255)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This part needs to be updated. For example `MatrixDecisionVariable` -> `VectorDecisionVariable`.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 289 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-KoNKrum8Rm_Cn6CSyAD:-KoNi8dx51ves9skZrKE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6948e3bf7d175a5baebb825bdacbbe2ae4f55e4f/drake/solvers/mathematical_program.h#L289)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this paragraph can be re-flowed:
```
   * This is equivalent to NewContinuousVariables<Rows, Cols>(name). We create
   * this function so that we can use NewContinuousVariables<Rows, Cols>(rows,
   * cols, name) for both static and dynamic sized new variables.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516)*

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please when you come back.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoNuqhB-gkoFV4ToZDv:bypsfd6)*

**Comment by hongkai-dai** [comment]
-@soonho-tri for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoNuvkNGtCdxYE2txo_:b-8n3k1r)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoNuyaAxPYV_ttC6YRl:bxw8cpy)*

**Comment by soonho-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoOqyJYsCVru6ssC5c7:b-s794vx)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-KoTcDpVzKXg-V-0Wiob:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Added some initial comments. PTAL when you have the chance. Thanks!

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh1gYdFqHJT6sRTJWG:-Koh1gYegzWD6Ji8XfJo:b-myyxke) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L299)):*
> ```objc
>                           MatrixDecisionVariable<Rows, Cols>>::type
>   NewContinuousVariables(int, int, const std::string& name) {
>     std::array<std::string, Rows * Cols> names;
> ```

Could something like `drake::MultiplyEigenSizes<int, int>` be used here, in conjunction with `NewVariableName<int>`, to get rid of the extra `enable_if`s?

---

*[drake/solvers/mathematical_program.h, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh2yMRUFeRcjv28j0J:-Koh2yMRUFeRcjv28j0K:b-k8ecn4) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L314)):*
> ```objc
>    * SetInitialGuess() or SetInitialGuessForAllVariables().
>    * @param rows The number of rows in the new variables. When Rows is not
>    * Eigen::Dynamic, rows is ignored.
> ```

Could this instead require that `cols == ColsAtCompileTime` / `rows == RowsAtCompileTime`?
That way, a user can switch between fixed and dynamic sizes knowing that they will have similar run-time arguments.

---

*[drake/solvers/mathematical_program.h, line 317 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh3COuxxIKdAmg84D7:-Koh3COuxxIKdAmg84D8:bpkjj0g) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L317)):*
> ```objc
>    * @param cols The number of columns in the new variables. When Cols is not
>    * Eigen::Dynamic, cols is ignored.
>    * @param name All variables will share the same name, but different index.
> ```

BTW Is there a note somewhere in this infrastructure that states that variable names don't really mean anything in the context of creating variables?
Given that `Variable` relies on a GUID, you can only guarantee having an identical variable by referencing to the original one.

---

*[drake/solvers/mathematical_program.h, line 433 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4_bRt3e0vORD1rmo:-Koh4_bRt3e0vORD1rmp:b-pyevm) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L433)):*
> ```objc
>    * @return A matrix containing the newly added variables.
>    */
>   template <int rows, int cols>
> ```

nit Capitalization: `Rows, Cols`

---

*[drake/solvers/mathematical_program.h, line 446 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4N9axYTvBa-PS_LB:-Koh4N9bZM6R41-Ne6iZ:bb8u0xe) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L446)):*
> ```objc
>    * @return A vector containing the newly added variables.
>    */
>   template <int rows>
> ```

Rather than making a specialization for just `<rows>`, could you instead set a default parameter for the above overload, `template <int Rows, int Cols = 1>`?

---

*[drake/solvers/mathematical_program.h, line 2357 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh3hlsFezWht04liMe:-Koh3hltS7TtghyEduzr:b-kah8bl) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L2357)):*
> ```objc
>   MatrixDecisionVariable<Rows, Cols> NewVariables(
>       VarType type,
>       const typename NewVariableName<Rows == Eigen::Dynamic ||
> ```

Could `drake::MultiplyEigenSizes<>` also be used here?
Additionally, could you make a specialization of `NewVariableNames` that does this for you? e.g.,
```
template <int Rows, int Cols>
struct NewVariableName<Rows, Cols> : public NewVariableName<MultiplyEigenSizes<Rows, Cols>::value> {};
```
or something to that extent?

---

*[drake/solvers/mathematical_program.h, line 2378 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4EDfrNi6IJgc-72N:-Koh4EDgiwxWqAVshQ1r:bvia9yf) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L2378)):*
> ```objc
>       VarType type,
>       const typename NewVariableName<
>           Rows == Eigen::Dynamic ? Eigen::Dynamic : Rows*(Rows + 1) / 2>::type&
> ```

Could you make a new typedef, `NewSymmetricVariableNames`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-Koh50JCgVwqpjeJ_syT:b-vzutna)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh1gYdFqHJT6sRTJWG:-Kottu3SyGLjoAfq3TO0:byf3tkn) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L299)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could something like `drake::MultiplyEigenSizes<int, int>` be used here, in conjunction with `NewVariableName<int>`, to get rid of the extra `enable_if`s?
</blockquote></details>

Done. I still need the SFINAE, in the function `CreateNewVariableNames`, since if `names` is a `std::vector<std::string>`, created when `Size == Eigen::Dynamic`, we need to call the constructor as `names(size)` to set its size. But if `Size` is a compile time positive integer, then `names` is of type `std::array<std::string, Size>`, that we can do not need to set its size at runtime.

---

*[drake/solvers/mathematical_program.h, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh2yMRUFeRcjv28j0J:-Kotu0RoL9AM99ukQr7E:bguy5mj) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L314)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could this instead require that `cols == ColsAtCompileTime` / `rows == RowsAtCompileTime`?
That way, a user can switch between fixed and dynamic sizes knowing that they will have similar run-time arguments.
</blockquote></details>

If `cols` or `rows` have default input, then the compiler will be confused which function to call, when we have
```C++
prog.AddContinuousVariables<2, 3>()
```
Since we have another function declared as
```C++
template <int Rows, int Cols>
  MatrixDecisionVariable<Rows, Cols> NewContinuousVariables(
      const std::string& name = "X")
```
which is supposed to handle the fixed-size matrix.

---

*[drake/solvers/mathematical_program.h, line 317 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh3COuxxIKdAmg84D7:-KotuecTPCzLBuIxsrD6:b-tkhmdd) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L317)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Is there a note somewhere in this infrastructure that states that variable names don't really mean anything in the context of creating variables?
Given that `Variable` relies on a GUID, you can only guarantee having an identical variable by referencing to the original one.
</blockquote></details>

Yes, at the end of this documentation block, it says
```
The name of the variable is only used for the user in order to ease
readability.
```
Do you think we should make it more clear?

---

*[drake/solvers/mathematical_program.h, line 433 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4_bRt3e0vORD1rmo:-KotuxTLyvPQSdlHORid:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L433)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Capitalization: `Rows, Cols`
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 446 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4N9axYTvBa-PS_LB:-Kou-FBNzeCHS3FbWtYf:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L446)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Rather than making a specialization for just `<rows>`, could you instead set a default parameter for the above overload, `template <int Rows, int Cols = 1>`?
</blockquote></details>

Done. Good call.

---

*[drake/solvers/mathematical_program.h, line 2357 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh3hlsFezWht04liMe:-Kou-vMKOJjZ-p6kpEzO:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L2357)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could `drake::MultiplyEigenSizes<>` also be used here?
Additionally, could you make a specialization of `NewVariableNames` that does this for you? e.g.,
```
template <int Rows, int Cols>
struct NewVariableName<Rows, Cols> : public NewVariableName<MultiplyEigenSizes<Rows, Cols>::value> {};
```
or something to that extent?
</blockquote></details>

Done. Good call.

---

*[drake/solvers/mathematical_program.h, line 2378 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh4EDfrNi6IJgc-72N:-Koyr3aTh09IJqgX2eXP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L2378)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could you make a new typedef, `NewSymmetricVariableNames`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh1gYdFqHJT6sRTJWG:-Kp0z5YUEqfyQGRrG8Jz:bo31bpy) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L299)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I still need the SFINAE, in the function `CreateNewVariableNames`, since if `names` is a `std::vector<std::string>`, created when `Size == Eigen::Dynamic`, we need to call the constructor as `names(size)` to set its size. But if `Size` is a compile time positive integer, then `names` is of type `std::array<std::string, Size>`, that we can do not need to set its size at runtime.
</blockquote></details>

Makes sense, looks good!

---

*[drake/solvers/mathematical_program.h, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh2yMRUFeRcjv28j0J:-Kp1PsrYV5bG9p708BMp:bmnx245) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L314)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If `cols` or `rows` have default input, then the compiler will be confused which function to call, when we have
```C++
prog.AddContinuousVariables<2, 3>()
```
Since we have another function declared as
```C++
template <int Rows, int Cols>
  MatrixDecisionVariable<Rows, Cols> NewContinuousVariables(
      const std::string& name = "X")
```
which is supposed to handle the fixed-size matrix.
</blockquote></details>

Makes sense, thanks for clarifying!

---

*[drake/solvers/mathematical_program.h, line 317 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-Koh3COuxxIKdAmg84D7:-Kp0yuIZOCEsAVsi1ARB:b-9z6plm) ([raw file](https://github.com/robotlocomotion/drake/blob/d46ff3ac2a761f5fcc76e4b0acfbabdb9dc54649/drake/solvers/mathematical_program.h#L317)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, at the end of this documentation block, it says
```
The name of the variable is only used for the user in order to ease
readability.
```
Do you think we should make it more clear?
</blockquote></details>

BTW Ah, that makes sense - thank you for pointing it out!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-Kp1QYvSMnq_xmTYmErV:bpqxd5f)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6516#-:-Kp1YZ03qTESVLfOrifW:b-l70wzf)*

**Pull request merged**
