### PR TITLE
[parsing] Fix dangling reference to destroyed stack variable

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
With our particular usage pattern we're rescued by NRVO, but that's too brittle to rely on indefinitely.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16797)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: questions

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16797#-:-MyDpthlCfyCUWSxtD3P:b-rzcdaa)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_parser.cc, line 1284 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16797#-MyDhlE-7AjIbT-384k2:-MyDhlE-7AjIbT-384k3:bjrvcd1) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba4e0dc73c52f56fe94b02a935d76db5e10e378/multibody/parsing/detail_sdf_parser.cc#L1284)):*
> ```cpp
>     bool test_sdf_forced_nesting) {
> 
>   // TODO(marcoag) ensure that we propagate the right ParserConfig instance.
> ```

does this patch satisfy the TODO?
___
*[multibody/parsing/detail_sdf_parser.cc, line 1299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16797#-MyDpcF_0a2mCpZZxesq:-MyDpcF_0a2mCpZZxesr:b-jhvdkc) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba4e0dc73c52f56fe94b02a935d76db5e10e378/multibody/parsing/detail_sdf_parser.cc#L1299)):*
> ```cpp
>       [&package_map, plant, test_sdf_forced_nesting](
>           const sdf::NestedInclude& include, sdf::Errors& errors) {
>         sdf::ParserConfig inner_parser_config = CreateNewSdfParserConfig(
> ```

This appears to create an endless chain of deferred callbacks. I don't know that it's wrong, just want to be sure it's intentional.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16797)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[multibody/parsing/detail_sdf_parser.cc, line 1299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16797#-MyDpcF_0a2mCpZZxesq:-MyDwQ527oaLWKQIP_C0:bvzyjb6) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba4e0dc73c52f56fe94b02a935d76db5e10e378/multibody/parsing/detail_sdf_parser.cc#L1299)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure what you're getting at.
</blockquote></details>

So, we 'Create' a 'NewSdfParserConfig()', which hands our client a new config. Within that config, we have 'Register'ed a 'CustomModelParser', which (AFAICT) gets invoked on every include statement within some future parse. When we hit an include, we invoke the callback, which 'Create's an inner 'NewSdfParserConfig()', which itself contains a callback, which when invoked (on include), will create a new config, etc., etc. 

I assume this terminates because there are only so many include layers a sane model can contain. One hopes we don't have models with arbitrary include depth, but then again, I'm no expert on SDFormat. 

Or perhaps I've misunderstood, and the inner callbacks are not actually invoked, or something.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16797)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[multibody/parsing/detail_sdf_parser.cc, line 1299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16797#-MyDpcF_0a2mCpZZxesq:-MyDya-s5orF0IrNgQqr:b-pw7pi3) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba4e0dc73c52f56fe94b02a935d76db5e10e378/multibody/parsing/detail_sdf_parser.cc#L1299)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, we 'Create' a 'NewSdfParserConfig()', which hands our client a new config. Within that config, we have 'Register'ed a 'CustomModelParser', which (AFAICT) gets invoked on every include statement within some future parse. When we hit an include, we invoke the callback, which 'Create's an inner 'NewSdfParserConfig()', which itself contains a callback, which when invoked (on include), will create a new config, etc., etc. 

I assume this terminates because there are only so many include layers a sane model can contain. One hopes we don't have models with arbitrary include depth, but then again, I'm no expert on SDFormat. 

Or perhaps I've misunderstood, and the inner callbacks are not actually invoked, or something.
</blockquote></details>

I think you're right that each include statement within the parsed data ends up making a new config.  I don't think this change makes any stack or recursion depths any worse, though.  Whatever call pattern the file input induces, it's the same before and after this PR.

In any case, it is somewhat absurd to create a local constant here just to curry it into the helper function.  I've moved the creation into the helper function directly.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16797)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
