### PR TITLE
[tools] Prepare glob changing default to allow_empty=False

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In Bazel 8, glob lines that don't match anything are an error.  (If we have lines that are _expected_ to sometimes not match anything, then we need to mark that with `allow_empty = True` on the glob call.)

Towards #22182.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one policy question.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-:-OBzk9_P9xkRLySKtFRM:bti5qpr)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`examples/scene_graph/BUILD.bazel` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-OBzjOt44JAjRi_PfbrN:-OBzjOt44JAjRi_PfbrO:bn97a4i) ([raw file](https://github.com/RobotLocomotion/drake/blob/3949eff85182eb12267e323bdccb4b6e2e7cb4ec/examples/scene_graph/BUILD.bazel#L82)):*
> ```Starlark
> filegroup(
>     name = "models",
>     srcs = [
> ```

This update could have been affected a few ways:

  1) The curated list presented here.
  2) Adding `allow_empty = False`.
  3) Removing the glob lines that don't produce matches.

The choice of (1) seems to strongly imply a preference. Is that a formal policy? Is it documented? Will other developers know how to make this decisions or will we simply hope that cargo culting will be enough to propagate this pattern in the future?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`examples/scene_graph/BUILD.bazel` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-OBzjOt44JAjRi_PfbrN:-OBzo-XO9XXBiA-ZQCkE:bj54agx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3949eff85182eb12267e323bdccb4b6e2e7cb4ec/examples/scene_graph/BUILD.bazel#L82)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This update could have been affected a few ways:

  1) The curated list presented here.
  2) Adding `allow_empty = False`.
  3) Removing the glob lines that don't produce matches.

The choice of (1) seems to strongly imply a preference. Is that a formal policy? Is it documented? Will other developers know how to make this decisions or will we simply hope that cargo culting will be enough to propagate this pattern in the future?
</blockquote></details>

No policy.  My aim was only to do what's the most readable code in any given situation.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185)* status: needs at least two assigned reviewers

___
*[`examples/scene_graph/BUILD.bazel` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-OBzjOt44JAjRi_PfbrN:-OBzq21r52MbWBiTtNXp:b-qb81qi) ([raw file](https://github.com/RobotLocomotion/drake/blob/3949eff85182eb12267e323bdccb4b6e2e7cb4ec/examples/scene_graph/BUILD.bazel#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No policy.  My aim was only to do what's the most readable code in any given situation.
</blockquote></details>

I guess "most readable" is subjective.

I know I often use `scene_graph` examples as a playground for running scene graph tests. The old spelling was convenient for me as I could drop files in and have them available in the data. Now I'll have to take two steps instead of the one.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-:-OBzrwSW-b6BmfvOMDRB:b-1krawd)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`examples/scene_graph/BUILD.bazel` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-OBzjOt44JAjRi_PfbrN:-OBzrvCt7LByU_gbMiZL:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3949eff85182eb12267e323bdccb4b6e2e7cb4ec/examples/scene_graph/BUILD.bazel#L82)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I guess "most readable" is subjective.

I know I often use `scene_graph` examples as a playground for running scene graph tests. The old spelling was convenient for me as I could drop files in and have them available in the data. Now I'll have to take two steps instead of the one.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`examples/scene_graph/BUILD.bazel` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-OBzjOt44JAjRi_PfbrN:-OC-0EWi58ZoPMmMexYO:btv3tr4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3949eff85182eb12267e323bdccb4b6e2e7cb4ec/examples/scene_graph/BUILD.bazel#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Groovy. Thanks.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22185#-:-OC0SWuz0kGi9WtI5O5S:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
