### PR TITLE
Add Python bindings for mixed integer rotation constraint generator.

### PR DESCRIPTION
**Pull request by gizatt**
Been using this in my research code on the Python side for a little while -- been working great!

@hongkai-dai -- any chance you could help me get this through?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Good day, @gizatt . I’m assigning +@hongkai-dai as the most relevant team member to assist with this pull request. If you already had a different team member in mind, please let us know. To @hongkai-dai, feel free to delegate in case there is someone else more suitable.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  Sorry for the belated reply. I somehow missed this PR
+@ggould-tri for platform review please, thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678#-:-MiMgMs822WTIfYBuCJe:bkkyj3g)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @gizatt)

___
*[bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiMpAbJDbq_6cH5ki9K:-MiMpAbJDbq_6cH5ki9L:bmsby69) ([raw file](https://github.com/robotlocomotion/drake/blob/dfed53af712fe1d3152044110cde24f2993594c4/bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc#L50)):*
> ```cpp
>   }
> 
>   {
> ```

This block may belong in a separate file.
Because `MixedIntegerRotationConstraintGenerator` doesn't come from `mixed_integer_optimization_util.h` but from `mixed_integer_rotation_constraint.h`, I think it belongs in a separate file, `mixed_integer_rotation_constraint_py.cc` to maintain correspondence between the cc and py.cc files.
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiMndp0DDPZ9bB99M1l:-MiMndp0DDPZ9bB99M1m:bnvu54x) ([raw file](https://github.com/robotlocomotion/drake/blob/dfed53af712fe1d3152044110cde24f2993594c4/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L77)):*
> ```Python
>         prog = mp.MathematicalProgram()
> 
>         # Sanity check, remove me.
> ```

minor: This comment seems not helpful, and possibly you meant to remove it and its check?

**Review by gizatt — COMMENTED** [review]
Thanks both!

Manual squashing sort of confused reviewable, I think I'll leave it to merging reviewer next time...

I copied the bindings and test over to the new files with the only modification being inclusion of "IntervalBinning" in the same scope block as the rest of the rotation constraint stuff, since it's a tightly-related struct.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678#-:-MiN0OQL6yLm_sRGdrx2:bpy2t6n)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiMpAbJDbq_6cH5ki9K:-MiMzBej9Svur75Y-DXZ:b-zfwu4b) ([raw file](https://github.com/robotlocomotion/drake/blob/dfed53af712fe1d3152044110cde24f2993594c4/bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc#L50)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This block may belong in a separate file.
Because `MixedIntegerRotationConstraintGenerator` doesn't come from `mixed_integer_optimization_util.h` but from `mixed_integer_rotation_constraint.h`, I think it belongs in a separate file, `mixed_integer_rotation_constraint_py.cc` to maintain correspondence between the cc and py.cc files.
</blockquote></details>

Was hoping for some advice on that -- moved.
___
*[bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiMndp0DDPZ9bB99M1l:-MiMzFsyCjXpok-DIEec:b-tm0elr) ([raw file](https://github.com/robotlocomotion/drake/blob/dfed53af712fe1d3152044110cde24f2993594c4/bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py#L77)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor: This comment seems not helpful, and possibly you meant to remove it and its check?
</blockquote></details>

Yup, removed.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678#-:-MiN1TCbDidJci6FeuSP:bnfp4nl)* status: 1 unresolved discussion (waiting on @gizatt)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiN19kTEOe7E_7VSKlN:-MiN19kTEOe7E_7VSKlO:beqash4) ([raw file](https://github.com/robotlocomotion/drake/blob/a05a5a92d8bba8ffd506fc8ac2e4c012c519846f/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L23)):*
> ```cpp
>     py::enum_<IntervalBinning>(m, "IntervalBinning", doc.IntervalBinning.doc)
>         .value("kLogarithmic", IntervalBinning::kLogarithmic)
>         .value("kLinear", IntervalBinning::kLinear);
> ```

minor:  Since this is now in the "wrong" location relative to it c++ position, there should at least be comment explaining why.

**Review by gizatt — COMMENTED** [review]
Oh hold on merge, I missed that IntervalBinning is more generic / attached to the Sos constraints, thanks for pointing that out. Might save a move later if I put that back where it belongs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678#-:-MiN2_uyDlL2hKkV9-_N:bwhmf13)* status: 1 unresolved discussion (waiting on @gizatt)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678)* status: 1 unresolved discussion (waiting on @gizatt)

**Review by gizatt — COMMENTED** [review]
OK, moved that binding back. Should be done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678#-:-MiN4bTY-C1B155WCz31:b2am4lt)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc, line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15678#-MiN19kTEOe7E_7VSKlN:-MiN3Yq15Q5jcukklG1v:b-tpbnm5) ([raw file](https://github.com/robotlocomotion/drake/blob/a05a5a92d8bba8ffd506fc8ac2e4c012c519846f/bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Since this is now in the "wrong" location relative to it c++ position, there should at least be comment explaining why.
</blockquote></details>

Yeah, good point. This enum describes generic binning strategies for the constraints in the mip utils; if those eventually get used somewhere outside of the rotation constraint, it would be weird to have to import from the rotation constraint stuff.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15678)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @gizatt)

**Pull request merged**
