### PR TITLE
[common] Add Identifier support to NiceTypeName

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Update KinematicsVector to use it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17365)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a question.
+@ericcousineau-tri for platform review per rotation please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17365#-:-N48Z4S800u61qbXDmkt:b-oc4v9l)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/nice_type_name.cc` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17365#-N48YfYP6uOlcgJQxKzg:-N48YfYP6uOlcgJQxKzh:b7s994a) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0f85374d1e553fc107546a846d8cf0fe93222/common/nice_type_name.cc#L97)):*
> ```cpp
>     // Change e.g., "drake::Identifier<drake::package::FooTag>" to
>     // "drake::package::FooId".
>     SPair(std::regex("\\bdrake::Identifier<([^>]*)Tag>"), "$1Id"),
> ```

I'm not fluent with regex and I'm having a hard time understanding what's in the parentheses `[^>]*`. Is that supposed to capture "Foo"?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17365)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`common/nice_type_name.cc` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17365#-N48YfYP6uOlcgJQxKzg:-N48aHUi2DknGWUbkZys:bgroije) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0f85374d1e553fc107546a846d8cf0fe93222/common/nice_type_name.cc#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There a really cool online tool to help with this:
https://regex101.com/r/TJFdNk/1

Yes, the `()` is a capture group, which capture `drake::package::Foo`.  The `*` is a "zero or more" modifier on the the `[^>]` which is "anything except close-angle-bracket.
</blockquote></details>

Ok yeah that pretty much matches with my understanding.  Originally I thought `$1` gives `Foo` instead of `drake::package::Foo`, which confused me.

Thanks for the tool reference.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17365#-:-N49NrGq6duQULzxne4N:bb368ni)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Comment by sherm1** [comment]
*[`geometry/kinematics_vector.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17365#-N49vE2c4YTONuYAAkbp:-N49vE2c4YTONuYAAkbq:bk4f1lc) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0f85374d1e553fc107546a846d8cf0fe93222/geometry/kinematics_vector.cc#L76)):*
> ```cpp
>   throw std::runtime_error(fmt::format(
>       "No such {}: {}.",
>       NiceTypeName::RemoveNamespaces(NiceTypeName::Get<Id>()), to_string(id)));
> ```

BTW Beautiful!



_Suggestion:_
```cpp
throw std::runtime_error(fmt::format(
  "No such {}: {}.",
  NiceTypeName::RemoveNamespaces(NiceTypeName::Get<Id>()),
  to_string(id)));
```

**Pull request merged**
