### PR TITLE
Remove old TODO comments as CalcBiasAcceleration issues were addressed.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13652)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sherm1 When you use the GitHub page merge, please respect the merge strategy that Reviewable would otherwise be enforcing.  This PR should have been squashed, not create a merge commit.

**Comment by amcastro-tri** [comment]
I always squash merge with GitHub. What does Reviewable do? have I been doing it wrong all this time? I'd like to learn the difference if you guys don't mind.

**Comment by jwnimmer-tri** [comment]
We configure reviewable ourselves for how to do it.  We have it set to squash and merge by default, unless the PR is labeled "commits are properly curated" in which case it will create a merge commit.

Therefore, when developers merge using Reviewable, everything happens correctly automatically.  So, using Reviewable to merge is a best practice.  It's only when using the GitHub page to merge that mistakes can happen.

**Comment by amcastro-tri** [comment]
Ah! I actually didn't know that, thanks @jwnimmer-tri!

**Pull request merged**
