### PR TITLE
Add pip troubleshooting documentation

### LINKED ISSUE #17924: Troubleshooting too-old pip version
As documented at https://drake.mit.edu/pip.html, prior to `pip install drake` on Ubuntu Focal 20.04, the user needs to upgrade their pip.  If they forget to do this, the error message is very weird like "no candidate version for this platform".

Some users might not even find our `pip.html` page with those instructions.

For those users, perhaps if our pypi page https://pypi.org/project/drake/ overview had some mention of this problem, more users would find out about the requirement.

Maybe we want a section at https://drake.mit.edu/troubleshooting.html about this kind of problem, and then the pypi overview page could hyperlink to that and/or pip.html?

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fixes #17924.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18722)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@svenevs  for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18722#-:-NNHmKBlDK2YAFlXmfbv:b-vtj4vo)* status: LGTM missing from assignee svenevs (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18722)* status: 1 unresolved discussion, LGTM missing from assignee svenevs (waiting on @mwoehlke-kitware)

___
*[`doc/_pages/troubleshooting.md` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18722#-NNI7IKx2_gKH76QeZpb:-NNI7IKx2_gKH76QeZpc:b-rnygbf) ([raw file](https://github.com/RobotLocomotion/drake/blob/915a85ffe0b5a9de90df5702e91a8f883bdee8db/doc/_pages/troubleshooting.md#L154)):*
> ```Markdown
> `manylinux` platform used by Drake.
> This is remedied by installing a newer version of `pip`.
> (Use of a Python virtual environment may be required.)
> ```

I would like to improve this final sentence, suggested change:

```diff
--- a/doc/_pages/troubleshooting.md
+++ b/doc/_pages/troubleshooting.md
@@ -150,8 +150,9 @@ When installing Drake from PyPI on older platforms such as Ubuntu Focal,
 you may receive the error "no candidate version for this platform".
 This is caused by older versions of `pip` which do not recognize the
 `manylinux` platform used by Drake.
-This is remedied by installing a newer version of `pip`.
-(Use of a Python virtual environment may be required.)
+This is remedied by installing a newer version of `pip`.  Use of a Python
+virtual environment may be required in order to get a newer version of `pip`,
+see the instructions for [installing from pip](/pip.html#stable-releases).
 
 # Build problems
 
```

We already have examples for how to do this so we can just link there, those docs already advise `pip install --upgrade pip`, and currently I feel the user who is going to get stuck on this entry is going to equally have little to no idea of what "use a virtualenv and upgrade pip" will actually mean.

**Comment by mwoehlke-kitware** [comment]
> I would like to improve this final sentence

Done (with slight changes). Good suggestion, thanks!

...and Reviewable is now not working for me at all. Joy.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18722)* status: 1 unresolved discussion, LGTM missing from assignee svenevs (waiting on @svenevs)

___
*[`doc/_pages/troubleshooting.md` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18722#-NNI7IKx2_gKH76QeZpb:-NNIfDoc-BmwLOjugdf3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/915a85ffe0b5a9de90df5702e91a8f883bdee8db/doc/_pages/troubleshooting.md#L154)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I would like to improve this final sentence, suggested change:

```diff
--- a/doc/_pages/troubleshooting.md
+++ b/doc/_pages/troubleshooting.md
@@ -150,8 +150,9 @@ When installing Drake from PyPI on older platforms such as Ubuntu Focal,
 you may receive the error "no candidate version for this platform".
 This is caused by older versions of `pip` which do not recognize the
 `manylinux` platform used by Drake.
-This is remedied by installing a newer version of `pip`.
-(Use of a Python virtual environment may be required.)
+This is remedied by installing a newer version of `pip`.  Use of a Python
+virtual environment may be required in order to get a newer version of `pip`,
+see the instructions for [installing from pip](/pip.html#stable-releases).
 
 # Build problems
 
```

We already have examples for how to do this so we can just link there, those docs already advise `pip install --upgrade pip`, and currently I feel the user who is going to get stuck on this entry is going to equally have little to no idea of what "use a virtualenv and upgrade pip" will actually mean.
</blockquote></details>

Done.

**Review by svenevs — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18722#-:-NNIhNes6rIInYufYk-p:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),svenevs (waiting on @mwoehlke-kitware)

___
*[`doc/_pages/troubleshooting.md` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18722#-NNI7IKx2_gKH76QeZpb:-NNIhLG56Tq2NIB3Yiof:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/915a85ffe0b5a9de90df5702e91a8f883bdee8db/doc/_pages/troubleshooting.md#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
