### PR TITLE
Create an instance of PiecewisePolynomial using autodiff

### PR DESCRIPTION
**Pull request by sammy-tri**
This doesn't work as well as I would like.  Most critically, the roots solver is (occasionally!) broken for AutoDiffXd.  It's also unused, so *shrug*.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8562)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for feature review.   cc @russtedrake 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-:-L9jpWCI86MwlxtEqnM9:bovi7ks)*

**Comment by ggould-tri** [comment]
:lgtm:  This is excellent!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[common/trajectories/piecewise_polynomial.cc, line 902 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9jqkZPA0ARhY4XNtE5:-L9jqkZPA0ARhY4XNtE6:ba91fjr) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce0e780c4c798ade3b4f11cdc28033a24f10e5a/common/trajectories/piecewise_polynomial.cc#L902)):*
> ```cpp
> template class PiecewisePolynomial<AutoDiffXd>;
> // doesn't work yet
> // template class PiecewisePolynomial<std::complex<double>>;
> ```

BTW:  (1) This actually might work now, but (2) I don't think we have any intention of supporting complex in Drake so maybe kill this comment anyway, or (3) explain y u no symbolic instead.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-:-L9jrQHf993PjD2t9lFr:b-kq20q8)*

**Comment by sammy-tri** [comment]
+@seancurtis-tri for platform review per (tomorrow's) rotation.

---

Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/trajectories/piecewise_polynomial.cc, line 902 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9jqkZPA0ARhY4XNtE5:-L9kGNgS-bsggaLRrPUI:b7uq8zg) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce0e780c4c798ade3b4f11cdc28033a24f10e5a/common/trajectories/piecewise_polynomial.cc#L902)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  (1) This actually might work now, but (2) I don't think we have any intention of supporting complex in Drake so maybe kill this comment anyway, or (3) explain y u no symbolic instead.
</blockquote></details>

Killed the comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-:-L9kGeTW2eDs1urcaYCh:b5vkfy8)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/polynomial.h, line 196 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9mO2dBDDSO1IVPmfVj:-L9mO2dBDDSO1IVPmfVk:b-kwpm7m) ([raw file](https://github.com/robotlocomotion/drake/blob/7886043c91e814130509193e8c2d8776fe6ff890/common/polynomial.h#L196)):*
> ```objc
>     // which may not have an assignment from double
>     // (e.g. std::complex<AutoDiffXd>).
>     ProductType value = x - x;
> ```

BTW, Normally we use `T(0)`.  does that not work here, either?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by sammy-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, all discussions resolved.

---

*[common/polynomial.h, line 196 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9mO2dBDDSO1IVPmfVj:-L9oxRip2Hc2eQKqzn0x:bmqu3tm) ([raw file](https://github.com/robotlocomotion/drake/blob/7886043c91e814130509193e8c2d8776fe6ff890/common/polynomial.h#L196)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, Normally we use `T(0)`.  does that not work here, either?
</blockquote></details>

I would have sworn that I tried that and it failed to compile where `ProductType` was `std::complex<AutoDiffXd>`, but I would have been wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

---

Review status: 8 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-:-L9ppC-e9VlLl55jzH-O:b-rs4zsh)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with one passing thought.

---

Reviewed 5 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/polynomial.cc, line 494 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9pt7bL-9BgdyCYRkX7:-L9pt7bL-9BgdyCYRkX8:bn03w9u) ([raw file](https://github.com/robotlocomotion/drake/blob/c5066759c5d1def70e77ee27c5815dfc643646a5/common/polynomial.cc#L494)):*
> ```cpp
>         "Roots is only defined for univariate polynomials");
> 
>   if (typeid(CoefficientType) != typeid(double)) {
> ```

FYI I believe this could be a `static_cast` inside this method. So, that they'll get a compiler error instead of some subsequent run-time error. Obviously that would impact the unit test down below. I defer to you which way you want to go.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-:-L9pxRDHC76ONsStebq0:bn7l7bd)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/polynomial.cc, line 494 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9pt7bL-9BgdyCYRkX7:-L9q0_sD4dvjgA_JOcVe:b3rn0cz) ([raw file](https://github.com/robotlocomotion/drake/blob/be425a0a6b972616ae305bed47e4fdab9512c272/common/polynomial.cc#L494)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I believe this could be a `static_cast` inside this method. So, that they'll get a compiler error instead of some subsequent run-time error. Obviously that would impact the unit test down below. I defer to you which way you want to go.
</blockquote></details>

I'm not sure that would work...  Since the method is in the .cc file, it needs to compile for the AutoDiffXd scalar type even if it's never called, correct?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/polynomial.cc, line 494 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562#-L9pt7bL-9BgdyCYRkX7:-L9q5_hT8mxdFQnp_-Uz:b-c3tnjw) ([raw file](https://github.com/robotlocomotion/drake/blob/be425a0a6b972616ae305bed47e4fdab9512c272/common/polynomial.cc#L494)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure that would work...  Since the method is in the .cc file, it needs to compile for the AutoDiffXd scalar type even if it's never called, correct?
</blockquote></details>

Good point. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8562)*

**Pull request merged**
