### PR TITLE
ImageToLcmImageArrayT: Change each image input port to be optional

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
ImageToLcmImageArrayT system now accepts input ports for any images to be unconnected.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6499)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri feature review please. Thank you in advance! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KnwoTnC-ppxIQ31bqpN:b-1btewy)*

**Comment by kunimatsu-tri** [comment]
-@EricCousineau-TRI 

+@siyuanfeng-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoNM8gwu6TdDgMOARPB:bnzlryl)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoNPFr2KrPZSTm_Wz-5:-KoNPFr3E5hK6zBXSN3W:bqpz4uk) ([raw file](https://github.com/robotlocomotion/drake/blob/cc46bc2f79f1379be3d200b3af16b289b6d8d889/drake/systems/sensors/image_to_lcm_image_array_t.cc#L108)):*
> ```cpp
> void ImageToLcmImageArrayT::CalcImageArray(
>     const systems::Context<double>& context, image_array_t* msg) const {
>   const int64_t utime =
> ```

BTW you could just save this in msg->header.utime? 

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoNPaimlz2Gf4W4UR34:-KoNPaimlz2Gf4W4UR35:bn2lk3g) ([raw file](https://github.com/robotlocomotion/drake/blob/cc46bc2f79f1379be3d200b3af16b289b6d8d889/drake/systems/sensors/image_to_lcm_image_array_t.cc#L116)):*
> ```cpp
>   msg->images.clear();
> 
>   const auto color_image_value =
> ```

BTW I suggest you expand auto to AbstractValue*, the type is not obvious here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoNQ1NWrsMKtQ9eEbpr:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Thanks @siyuanfeng-tri for the review. Addressed all of your comments. PTAL.

+@soonho-tri platform review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoN_U72R_QZOE7SPPIr:b-jw34me)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoNPFr2KrPZSTm_Wz-5:-KoNXXB4_1Q9hqEePNam:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc46bc2f79f1379be3d200b3af16b289b6d8d889/drake/systems/sensors/image_to_lcm_image_array_t.cc#L108)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW you could just save this in msg->header.utime? 
</blockquote></details>

Done.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoNPaimlz2Gf4W4UR34:-KoN_SpEQQ8D1BH0BIm6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc46bc2f79f1379be3d200b3af16b289b6d8d889/drake/systems/sensors/image_to_lcm_image_array_t.cc#L116)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW I suggest you expand auto to AbstractValue*, the type is not obvious here. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by soonho-tri** [comment]
:lgtm: (aside BTWs)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-5eefYI319DRXcOh:-KoO-5eefYI319DRXcOi:b-qtun1g) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L109)):*
> ```cpp
>     const systems::Context<double>& context, image_array_t* msg) const {
>   msg->header.utime = static_cast<int64_t>(context.get_time() * kSecToMillisec);
>   msg->header.frame_name = "";
> ```

BTW, It's not a defect but I think it's slightly better to use `.clear()` here. See https://stackoverflow.com/a/35389067 for the details.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-P0APARqHq6zY6kt:-KoO-P0APARqHq6zY6ku:b-mwwraf) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L110)):*
> ```cpp
>   msg->header.utime = static_cast<int64_t>(context.get_time() * kSecToMillisec);
>   msg->header.frame_name = "";
>   msg->num_images = 0;
> ```

BTW, I think it's not a good design to keep `msg->num_images` field because the same information can be retrieved by `msg->images.size()` and maintaining the invariant `num_images == msg->images.size()` is error-prone.

It's definitely not the scope of this PR, but I'd like to suggest another PR to improve it -- 1) eliminate `num_images` field and 2) replace `msg->num_images` with `msg->images.size()`.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 122 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO0QOuhafevuvCebmL:-KoO0QOuhafevuvCebmM:b-7rptfm) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L122)):*
> ```cpp
>       this->EvalAbstractInput(context, label_image_input_port_index_);
> 
>   if (color_image_value != nullptr) {
> ```

BTW, you can write `if (color_image_value) {` to denote the same thing (not a defect though).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoO0kWptu9tsk-T8kxc:b5u6cca)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-P0APARqHq6zY6kt:-KoO1Qnjjfoy_Jtk30GC:b-q32vzb) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L110)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's not a good design to keep `msg->num_images` field because the same information can be retrieved by `msg->images.size()` and maintaining the invariant `num_images == msg->images.size()` is error-prone.

It's definitely not the scope of this PR, but I'd like to suggest another PR to improve it -- 1) eliminate `num_images` field and 2) replace `msg->num_images` with `msg->images.size()`.
</blockquote></details>

BTW, @soonho-tri it's not the author's fault. In this case, I think it's a artifact of lcm message defs, which requires the field num_images in addition to the vector. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-P0APARqHq6zY6kt:-KoO2PlsUXRnRhlqqsj6:b-kimwi9) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L110)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, @soonho-tri it's not the author's fault. In this case, I think it's a artifact of lcm message defs, which requires the field num_images in addition to the vector. 
</blockquote></details>

@siyuanfeng-tri , yes. @kunimatsu-tri and I are having a conversation and reached the same conclusion. I withdraw my suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by kunimatsu-tri** [comment]
Thanks for the review @soonho-tri! Addressed all the comments. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-5eefYI319DRXcOh:-KoO3B9WeEdfhn6Zw7iz:bb06ddc) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L109)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, It's not a defect but I think it's slightly better to use `.clear()` here. See https://stackoverflow.com/a/35389067 for the details.
</blockquote></details>

Good to know.  Done.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 122 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO0QOuhafevuvCebmL:-KoO3sX40pLti-CBnilm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L122)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, you can write `if (color_image_value) {` to denote the same thing (not a defect though).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoO48Runk05ciSRt4um:bqinxcf)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/image_to_lcm_image_array_t.cc, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-KoO-5eefYI319DRXcOh:-KoO4LkJQd1fHHLZHZVb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db197ec10f4974e630b1d117eba29ee80107b7b7/drake/systems/sensors/image_to_lcm_image_array_t.cc#L109)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Good to know.  Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499)*

**Comment by jwnimmer-tri** [comment]
FYI -- This should have been "curate commits before merging" and squash-merged.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , my bad. I'll make sure that.

**Comment by kunimatsu-tri** [comment]
That's right and I should also have left meaningful comments just in case.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6499#-:-KoP9WpaEaitr44MQFgR:bp21wia)*

**Pull request merged**
