### PR TITLE
Add EqualTo methods to symbolic classes in Python bindings

### LINKED ISSUE #8505: Add missing EqualTo to Python symbolic classes
From https://github.com/RobotLocomotion/drake/pull/8500#issuecomment-378270113

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #8505
Related issue: #8500

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8510)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@gizatt , could you feature-review this one?

**Comment by gizatt** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8510#-:-L9Bp4zLBmfKiCQNAxVy:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8510#-:-L9ButvdDamzean8CaAS:bnfp4nl)*

**Pull request merged**
