### PR TITLE
Factor vector_gen to allow non-Drake named_vectors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Builds on #8617.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8633)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.
+@EricCousineau-TRI for platform review, please.

**Comment by jwnimmer-tri** [comment]
Oops, +@soonho-tri for platform review, please.  Forgot what day it was.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8633#-:-LATsYTT340Pol7bb5s5:bnfp4nl)*

**Comment by soonho-tri** [comment]
Nice! :lgtm: + tested on :apple: (only `//examples/...` portion).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8633#-:-LAU4eRP1HMId614sDqC:b-3cdy28)*

**Pull request merged**
