### PR TITLE
[parsing] Don't warn on equivalent package.xml files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19111)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@EricCousineau-TRI for feature review: :lgtm_strong:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-:-NRtC_kM3xk768HSaj4z:b-egcbd2)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-NRtCgMG4u9HZATT-OtZ:-NRtCgMG4u9HZATT-Ot_:b-mq1n8o) (no related file):*
BTW Is it worth generating a test for this?

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-:-NS6N-ybCM2vza9ZacMQ:bfqkacy)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-:-NS7OGXJ54eqYnUmxq81:bg7igkv)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-NS7O7UJ3rtXnWqIJDJu):*
BTW



_Suggestion:_
```
symlinks to other locations but where the directory is just a bucket of
```

**Comment by jwnimmer-tri** [comment]
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19111#-NS7O7UJ3rtXnWqIJDJu):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW
</blockquote></details>

OK fixed during squash.

**Pull request merged**
