### PR TITLE
[yaml] Improve error message for parsing a non-Mapping root node

### LINKED ISSUE #19725: LoadModelDirectives gives unhelpful message when one forgets the "directives:"
I often write model directives directly in my code:  e.g.
```
      model_directives = R"""( 
directives:

# Add shelves
- add_model:
    name: shelves
    file: package://gcs/models/shelves/shelves.sdf
...
)""";
      parser.AddModelsFromString(model_directives, ".dmd.yaml");
```
One time I forgot to add the `directives:` signature at the top... an honest mistake!  I was rewarded with the output:
```
abort: Failure at common/yaml/yaml_read_archive.cc:270 in MaybeGetSubNode(): condition 'root_->IsMapping()' failed.)
```

I had to step into the debugger to figure out what I had done wrong. 

Request: Drake provides a more helpful error message for this case.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19725.

I didn't actually check if this solves the repro from the original issue, but I assume it will.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19730)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19730#-:-NZgY896D81SKl29y_G_:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19730#-:-NZgabM87BSxa8wygXRr:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
