### PR TITLE
[tutorials] Move some hydro model files to drake_models

### LINKED ISSUE #13942: Move sdformats and urdfs adjacent to external meshes
See https://drake.mit.edu/model_version_control.html for background.

We are storing models' meshes, textures, and other large files in https://github.com/RobotLocomotion/models, so that a `git clone` of Drake does not grow inordinately large.  In the procedures for that, we say:

> Please do not commit files that are generally small, like *.sdf or *.urdf files, in RobotLocomotion/models; instead, please commit those directly.

The thought was that these small text files might change or fork frequently (e.g., to change collision models, or other contact properties), and so laundering those changes through an external repository would be cumbersome.  Furthermore, within Drake we have CI that can validate that the files are well-formed, can be loaded by our parser, etc.  If we stored the text files along with the meshes, we would need to modify those procedures.

On the other hand, it is also awkward to add new models, or preview the current models, with the files split between git repositories.

Relatedly, it's not unusual for us to inherit the models from a third-party repository, which means we must propagate the licensing information.  Pushing it to two places is awkward, and having third-party code (e.g., urdf) committed into drake in the manipulation/models folder (instead of third_party) makes license sanity checking for distribution and release more awkward.

We should consider changing the policy, and moving the sdformat and urdf files into the external repository, in cases where they have large files associated with them.

---

Edited to add:

Remaining checklist:
- [x] drake/examples/manipulation_station/models
- [x] drake/examples/pr2
- [x] drake/examples/quadrotor
- [x] drake/examples/hydroelastic/spatula_slip_control/models
- [x] drake/manipulation/models
- [x] drake/examples/hydroelastic/ball_plate/plate_8in
- [x] drake/examples/hydroelastic/python_nonconvex_mesh/bowl
- [x] drake/examples/hydroelastic/python_nonconvex_mesh/pepper
- [ ] tutorials/hydroelastic_contact_nonconvex_mesh

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Load the models from drake_models and then display them inline anyway, so users can still read them easily. Add XML syntax highlighting.

Tidy up the test_mode toggle a little bit.

Remove calls to ModelVisualizer.parser(); best practice is to always call ModelVisualizer.AddModels() directly.

Twin PR: https://github.com/RobotLocomotion/models/pull/60

Closes #13942, at long last.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NubBALD9ynsGGUUCZ4_:-NubBALE9RY8C8MiBJLC:b-ebd2w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "bca285305201523d5070da95bc52d3d0b65b28c4",
> ```

Working

Needs real sha

**Comment by jwnimmer-tri** [comment]
FYI Just like I mentioned in the models PR, you are welcome to push patches here if you prefer that to posting review comments.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueBKoMD1mS1p_5VOMm:-NueBKoN01QbNnr33Wns:bje6amv) (no related file):*
Working

Hmm, the debug build timed out.  I must have made some mistake rewriting how the test-mode stuff happens.  I'll investigate after I hear back about other review comments.

___

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-:-NueW5yzBxhKC3leKprI:bnfp4nl)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueBKoMD1mS1p_5VOMm:-NueVpa4DDgF1p89Y12n:bbzem9i) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Hmm, the debug build timed out.  I must have made some mistake rewriting how the test-mode stuff happens.  I'll investigate after I hear back about other review comments.
</blockquote></details>

It timed out because ModelVisualizer used the fine mesh in the debug build.

___
___
*[`tutorials/hydroelastic_contact_nonconvex_mesh.ipynb` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueIkzv6EMHHPXxWko8:-NueIkzv6EMHHPXxWko9:b2nhbfk) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L71)):*
> ```
>     "*Make sure you have the MeshCat tab opened in your browser; the link is shown immediately above.*\n",
>     "\n",
>     "We will load a compliant-hydroelastic bell pepper from an SDFormat file. We will show the file for you to read, and then use `ModelVisualizer` display it.\n",
> ```

BTW



_Suggestion:_
```
use `ModelVisualizer` to display it
```
___
*[`tutorials/hydroelastic_contact_nonconvex_mesh.ipynb` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueJKlM6WtXryW-S203:-NueJKlM6WtXryW-S204:b2nhbfk) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L112)):*
> ```
>     "## Create compliant-hydroelastic bowl in URDF\n",
>     "\n",
>     "We will load a compliant-hydroelastic bowl with URDF file. We will show the file for you to read, and then use `ModelVisualizer` display it.\n",
> ```

BTW



_Suggestion:_
```
use `ModelVisualizer` to display it
```
___
*[`tutorials/hydroelastic_contact_nonconvex_mesh.ipynb` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueU2Do3X6I_3UxjvSy:-NueU2Do3X6I_3UxjvSz:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L127)):*
> ```
>    "outputs": [],
>    "source": [
>     "# Show the contents of the SDFormat file.\n",
> ```

nit



_Suggestion:_
```
URDF
```
___
*[`tutorials/hydroelastic_contact_nonconvex_mesh.ipynb` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueUIO11gAsgQOU2Fft:-NueUIO11gAsgQOU2Ffu:bpwm14m) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L158)):*
> ```
>     "                                \"evo_bowl_coarse3k.vtk\")"
>    ]
>   },
> ```

BTW, ModelVisualizer should use the coarser mesh in debug CI to avoid time out.  That's what we did in r0.



_Suggestion:_
```
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# (Drake users can ignore this cell. When Drake regression testing runs in CI,\n",
    "# we need to use a coarser tetrahedral mesh to improve debug performance.)\n",
    "test_mode = \"TEST_SRCDIR\" in os.environ\n",
    "if test_mode:\n",
    "    bowl_str = bowl_str.replace(\"evo_bowl_fine44k.vtk\", \n",
    "                                \"evo_bowl_coarse3k.vtk\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualize the URDF file.\n",
    "visualizer = ModelVisualizer(meshcat=meshcat)\n",
     visualizer.parser().AddModelsFromString(bowl_str, "urdf")
    "visualizer.Run(loop_once=True)"
   ]
  },
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-:-Nuemst612M3ngUduxCN:b-syrr9x)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueBKoMD1mS1p_5VOMm:-NueqZ733p44mV9rcjY-:b1ba8v4) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

It timed out because ModelVisualizer used the fine mesh in the debug build.
</blockquote></details>

I'm astonished that even visualizing the fine mesh times out.

___
___
*[`tutorials/hydroelastic_contact_nonconvex_mesh.ipynb` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-NueUIO11gAsgQOU2Fft:-NuenU5p98XCmVH9leIu:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a039d3efef2cd30f6de07448dfdaf7b972a018a9/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L158)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, ModelVisualizer should use the coarser mesh in debug CI to avoid time out.  That's what we did in r0.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258#-:-Nuf-Rx19Np0iHx6BbRd:bnfp4nl)* status: 2 unresolved discussions

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21258)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy

**Comment by DamrongGuoy** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm astonished that even visualizing the fine mesh times out.
</blockquote></details>

Perhaps this helps explain it.  

On my Puget:
ModelVisualizer of the fine mesh in optimized build took about 1.4 seconds.
ModelVisualizer of the fine mesh in debug build took about 300 seconds.
ModelVisualizer of the coarse mesh in optimized build took about 0.1 second.
ModelVisualizer of the coarse mesh in debug build took about 10 seconds.

|                    |   coarse |    fine  |
|--------------- | ----------- | ----------|
| optimized |     0.1      |    1.4    |
| debug        |    10       |    300    |

Going from optimized to debug increases the running time by 100 - 200X.
Going from coarse to fine meshes increases the running time by 14 - 30X.
The fine mesh is about ten times larger than the coarse mesh.

I'm guessing the debug timed out on the fine mesh because Eigen was about 100X slower in debug mode, and ModelVisualizer needed to compute the pressure field.

**Pull request merged**
