### PR TITLE
Fixes defects in Affine/Linear System PR

### PR DESCRIPTION
**Pull request by naveenoid**
The issues noted in the reviewable discussion here : 
https://reviewable.io/reviews/RobotLocomotion/drake/3828#-KV10uHtxEQcwx3ViLBD
were fixed. 

+@jwnimmer-tri for feature review
+@liangfok too if you would like.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3929)

### CODE REVIEW

**Comment by liangfok** [comment]
I completed my round 1 feature review.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/affine_system.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV647jWQZIsBDXnxZQF:-KV647jWQZIsBDXnxZQG:byl7ia0) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/affine_system.h#L13)):*
> ```objc
> /// derivative `xDot0` and intial output `y0`, this system
> /// implements the following equations:
> /// @f[\dot{x} = Ax + Bu + \dot{x}_0 @f] \newline
> ```

BTW, is this `\newline` necessary?

---

*[drake/systems/framework/primitives/linear_system.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64GwxCzW3DgwImXlb:-KV64GwxCzW3DgwImXlc:b-nu4yai) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L8)):*
> ```objc
> namespace systems {
> 
> /// A continuous linear system that is a specialization of an affine system
> ```

BTW, consider changing "affine system" to be "AffineSystem" so it appears as a link in the rendered Doxygen website.

---

*[drake/systems/framework/primitives/linear_system.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64PbiI9Emp_4kXSWz:-KV64PbiI9Emp_4kXSX-:b-2r6vj5) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L11)):*
> ```objc
> /// where the inital time derivative of the system state `xDot0`
> /// and the initial system output `y0` are both zero. Given an input
> /// signal `u` and a state `x` the output of this sytem 'y' is:
> ```

Typo: "sytem"

---

*[drake/systems/framework/primitives/linear_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64_PtkiZh6TNOpjP5:-KV64_PuaczXBCfvuh_s:b-ig998r) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L27)):*
> ```objc
> class LinearSystem : public AffineSystem<T> {
>  public:
>   /// Constructs a Linear system with a fixed set of coefficient matrices `A`,
> ```

BTW, consider replacing "Linear system" with "%LinearSystem".

---

*[drake/systems/framework/primitives/linear_system.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64W4ytgpSbutFBXPo:-KV64W4ytgpSbutFBXPp:b-uig3m2) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L29)):*
> ```objc
>   /// Constructs a Linear system with a fixed set of coefficient matrices `A`,
>   /// `B`,`C`, and `D`.
>   /// The coefficient matrices must obey the following dimensions :
> ```

Extra space before ":".

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64jI98ewPGsyOcJL7:-KV64jI98ewPGsyOcJL8:b-sd5dw1) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L14)):*
> ```objc
>  public:
>   // Setup an arbitrary AffineSystem.
>   AffineLinearSystemTest(double xDot0_0, double xDot0_1, double Y0_0,
> ```

To be consistent with AffineSystem, shouldn't `Y0_0` be `y0_0`?

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64qVi3RDTZgfhCZko:-KV64qVi3RDTZgfhCZkp:b-x7u0cv) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L15)):*
> ```objc
>   // Setup an arbitrary AffineSystem.
>   AffineLinearSystemTest(double xDot0_0, double xDot0_1, double Y0_0,
>                          double Y0_1)
> ```

To be consistent with AffineSystem, shouldn't `Y0_1` be `y0_1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KV65Fn8zKrqFesC805H:b-lhsuu0)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/primitives/affine_system.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV647jWQZIsBDXnxZQF:-KV662KJnAAwiSrXtkYg:b-hqvnqx) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/affine_system.h#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, is this `\newline` necessary?
</details>
Done. Removed..

---

*[drake/systems/framework/primitives/linear_system.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64GwxCzW3DgwImXlb:-KV66Aco2d8jhc9oVlWH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider changing "affine system" to be "AffineSystem" so it appears as a link in the rendered Doxygen website.
</details>
Done.

---

*[drake/systems/framework/primitives/linear_system.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64PbiI9Emp_4kXSWz:-KV66CUFMG7NQ7wQxGcB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L11)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Typo: "sytem"
</details>
Done.

---

*[drake/systems/framework/primitives/linear_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64_PtkiZh6TNOpjP5:-KV66JWaXQWtCx1IVzd7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider replacing "Linear system" with "%LinearSystem".
</details>
Done.

---

*[drake/systems/framework/primitives/linear_system.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64W4ytgpSbutFBXPo:-KV66IzAbD2PibthGI1d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/linear_system.h#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Extra space before ":".
</details>
Done.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64jI98ewPGsyOcJL7:-KV66ZEIlN3eaCXfNzwa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> To be consistent with AffineSystem, shouldn't `Y0_0` be `y0_0`?
</details>
Done.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64qVi3RDTZgfhCZko:-KV66Zu9afM0Tm-YczVm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> To be consistent with AffineSystem, shouldn't `Y0_1` be `y0_1`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929)*

**Comment by naveenoid** [comment]
rebased and addressed your issues. PTAL.

---

Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KV6DBDy93vaytFZxQuj:b-rrdqxr)*

**Comment by liangfok** [comment]
I completed my round 2 feature review.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64jI98ewPGsyOcJL7:-KV6FfUxCzQSSzLQ4f_h:b-wcz65n) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L14)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Done.
</details>
No change?

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64qVi3RDTZgfhCZko:-KV6FhrS2jX1TtCzrIGc:b-wcz65n) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L15)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Done.
</details>
No change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KV6FnzrbgcFabVEDU4V:bvx9m1)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by naveenoid** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64jI98ewPGsyOcJL7:-KV9KcbJOtDNyD7GuP2v:b1819qc) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> No change?
</details>
Fixed now! 

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV64qVi3RDTZgfhCZko:-KV9Kuv3kAHzA3hBihUP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ba4729df164e79428f9456a60a9c5afa611348a/drake/systems/framework/primitives/test/affine_linear_test.h#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> No change?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KV9qEXXoUOrtnVnoSyb:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV9rSPkCis83Q9SNs7Y:-KV9rSPlIMwAt__GRLk_:bjua01a) ([raw file](https://github.com/robotlocomotion/drake/blob/efa368b0622cac0e96e206d0000c45db98f089e3/drake/systems/framework/primitives/test/affine_linear_test.h#L45)):*
> ```objc
>   std::unique_ptr<SystemOutput<double>> system_output_;
> 
>   ContinuousState<double>* state_;
> ```

Missing `{}`.
http://drake.mit.edu/code_style_guide.html#additional-rules second bullet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KV9sKyNNbnOvhduTbRe:bnfp4nl)*

**Comment by naveenoid** [comment]
Shall I go ahead with merge? The minor defect is fixed.

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/affine_linear_test.h, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-KV9rSPkCis83Q9SNs7Y:-KVAGwSBO8dSIecDwnLl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/efa368b0622cac0e96e206d0000c45db98f089e3/drake/systems/framework/primitives/test/affine_linear_test.h#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing `{}`.
> http://drake.mit.edu/code_style_guide.html#additional-rules second bullet
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KVAGxmVhEHMPnhkuvOV:b-jvlh1b)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KVAL6nGBcTMEO2QlmSs:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
> Shall I go ahead with merge? The minor defect is fixed.

FTR, I would be been okay if you had marked my comment as resolved and thus merged, since that it was fixed was obvious and uncontroversial.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3929#-:-KVAY1WVq7swTrYqiQ1-:brptxa3)*

**Pull request merged**
