### PR TITLE
Add local_repository_override to github_archive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This allows users to easily test-build different revisions of WORKSPACE externals.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5628)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer for review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-:-KgFCKKe3fPHVXlGE_CS:bhtg28)*

**Comment by jwnimmer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/github.bzl, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-KgFDJauuT0AVduW01HX:-KgFDJauuT0AVduW01HY:b-otsc41) ([raw file](https://github.com/robotlocomotion/drake/blob/11675dc0cc3a906fc6ceb9363e5cf252b0542436/tools/github.bzl#L12)):*
> ```Python
>         **kwargs):
>     """A macro to be called in the WORKSPACE that adds an external from github
>     using a workspace rule.
> ```

FYI This is a repository rule, not a workspace rule, I think?

---

*[tools/github.bzl, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-KgFD72Evlh12Z7ISA5w:-KgFD72Evlh12Z7ISA5x:b95t2w3) ([raw file](https://github.com/robotlocomotion/drake/blob/11675dc0cc3a906fc6ceb9363e5cf252b0542436/tools/github.bzl#L28)):*
> ```Python
>     external.  When omitted, the BUILD file(s) within the archive will be used.
> 
>     The optional local_repository_override= can be used for temporary locale
> ```

BTW `locale` should be `local`.

---

*[tools/github.bzl, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-KgFDEuqOJZCJ17ornSj:-KgFDEuqOJZCJ17ornSk:b5594qr) ([raw file](https://github.com/robotlocomotion/drake/blob/11675dc0cc3a906fc6ceb9363e5cf252b0542436/tools/github.bzl#L65)):*
> ```Python
>                 build_file=build_file,
>                 path=local_repository_override)
>             return
> ```

Both branches should early-return, not just the second one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/github.bzl, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-KgFD72Evlh12Z7ISA5w:-KgFE6nOEgpgJZsZJ1NI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11675dc0cc3a906fc6ceb9363e5cf252b0542436/tools/github.bzl#L28)):*
<details><summary><i>Previously, jwnimmer wrote…</i></summary><blockquote>

BTW `locale` should be `local`.
</blockquote></details>

Done.

---

*[tools/github.bzl, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-KgFDEuqOJZCJ17ornSj:-KgFEAMbC4L_7EAVtf9Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11675dc0cc3a906fc6ceb9363e5cf252b0542436/tools/github.bzl#L65)):*
<details><summary><i>Previously, jwnimmer wrote…</i></summary><blockquote>

Both branches should early-return, not just the second one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628)*

**Comment by jwnimmer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628)*

**Comment by jwnimmer** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-:-KgFEuAtRT5o6pxtEreo:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review.

(Two reviewers have already looked at an earlier version of this that differs only in its comments.)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-:-KgGlf56Ai3dKkOYuz2o:b-k8wi0y)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5628#-:-KgKI-1pL0dYMe3wH8_U:bnfp4nl)*

**Pull request merged**
