### PR TITLE
[tools] Enable OpenMP in Ubuntu binaries

### LINKED ISSUE #18828: Enable OpenMP in monthly releases
Towards #14431 and #14858, we should enable OpenMP in our packaged binaries.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18828.

Requires
- [x] #18842

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18849)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Tested locally:

```console
jwnimmer@call-cps:~/tmp$ python3 -m venv env
jwnimmer@call-cps:~/tmp$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2023.2.23.19.20.54%2Bgitd6e4a328-cp310-cp310-manylinux_2_31_x86_64.whl
...
jwnimmer@call-cps:~/tmp$ env/bin/python3
>>> import numpy as np
>>> from pydrake.all import *
>>> builder = RobotDiagramBuilder()
>>> iiwa, = builder.parser().AddModelsFromUrl("package://drake/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf")
>>> model = builder.Build()
>>> def configuration_distance(q1, q2):
...   return np.linalg.norm(q1 - q2)
>>> cc = SceneGraphCollisionChecker(model=model, robot_model_instances=[iiwa], configuration_distance_function=configuration_distance,edge_step_size=0.0125)
INFO:drake:Allocating contexts to support 48 parallel queries given omp_num_threads 48 omp_max_threads 48 and omp_thread_limit 2147483647 OpenMP enabled in build? true
```

**Comment by jwnimmer-tri** [comment]
Looking at `drake.libs` and the readelf output, there is just one new library:

```
 0x0000000000000001 (NEEDED)             Shared library: [libgomp-b6de5f8b.so.1.0.0]
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
Weird lint errors, which I sincerely hope are transient. They could hardly be from this patch.

otherwise, :lgtm: 

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18849#-:-NPNUWce80KJc_69ZiTW:b-ervuu)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review (Thursday), please.

I'll re-trigger CI for the flakes once we're ready to merge, and as a final sanity check vs any new code added in the meantime.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18849#-:-NPYAteN-6ZrO6fUNl0Z:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
I'll let you do any remaining pre-merge checks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18849#-:-NPYAwZB-0jF4bz_TQkj:b-p8uokf)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I think we're good now.  We'll see what post-merge has to say.

**Pull request merged**
