### PR TITLE
Update LCM for sanitizer fixes

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update LCM, bringing in changes to more aggressively disable sanitizers when building lcmgen. This should help with some of our CI problems on builds with sanitizers enabled.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4661)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4661#-:-K__qwUICgOuRI1TRrEY:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Since no one answered so far in slack, I am semi-arbitrarily going to pick on +@david-german-tri for feature review... (please reassign if you know someone better!)

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4661#-:-K_a9yBVBFlQr_QtWFjm:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
SHA bumps should hit both CMake and Bazel builds.  I'll fix in another PR.

**Pull request merged**
