### PR TITLE
Modified matlab tests

### PR DESCRIPTION
**Pull request by jonathan-owens**
Just for testing right now, don't merge

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2054)

### CODE REVIEW

**Comment by jonathan-owens** [comment]
Try again

**Comment by jonathan-owens** [comment]
Training again with more verbose

**Comment by billhoffman** [comment]
We need to add a timeout to the add_matlab_test.   The new test stuff has a default of 180 seconds.

**Comment by jonathan-owens** [comment]
@billhoffman Easy enough to do since it's already in the cake portion of stuff. What do you think we should up the default for the drake to be? I set it to 400 seconds for now. See: https://github.com/RobotLocomotion/drake/pull/2054/commits/97777a01adf6cb0ae732ebda86952e9769b42e97

**Comment by billhoffman** [comment]
Seems to be setting timeout to TIMEOUT TIMEOUT, and the 180 is back.   
/home/ubuntu/workspace/experimental/06107e1d/build/matlab;/home/ubuntu/workspace/experimental/06107e1d/drake/systems/test
timeout = TIMEOUT;TIMEOUT;180
CMake Error at /home/ubuntu/workspace/experimental/06107e1d/drake/cmake/MatlabTestsRedirect.cmake:92 (execute_process):
  execute_process given unknown argument "180".

**Comment by billhoffman** [comment]
I have moved this to a branch on my clone, so I am closing this one.

**Pull request closed without merging**
