### PR TITLE
Attempt to get Jenkins to test my IPOPT changes

### PR DESCRIPTION
**Pull request by sammy-tri**
This isn't for merge.  This is because (1) I wanna test something on Mac and (2), I'm really confused by what happened on my previous two attempts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2434)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request closed without merging**
