### PR TITLE
pybind: Synchronize with RobotLocomotion/pybind11#14

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
See RobotLocomotion/pybind11#14

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8434)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for all review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8434#-:-L8DsAL4lYd-9xDRPCuh:b-83dehw)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8434#-:-L8DsL0gMcOYTr3Shjrs:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Upstream fork PR has merged. Will merge once CI passes.

**Comment by soonho-tri** [comment]
@ericcousineau-tri , FYI, this is ready.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8434#-:-L8HlMXx82vN9cZYJM0f:b-1l3xd1)*

**Comment by soonho-tri** [comment]
CI is all happy. Merging it on behalf of Eric.

**Pull request merged**
