### PR TITLE
Add cond/if-then-else expressions for eigen::AutoDiffScalar and double

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4203)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , could you do the both reviews please?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-:-KX7oAGjzaYOF8U7T-17:b-xcjnv6)*

**Comment by soonho-tri** [comment]
*[drake/common/autodiff_overloads.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7oQDbmG2fhaZl6iWv:-KX7oQDbmG2fhaZl6iWw:br1699j) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/autodiff_overloads.h#L120)):*
> ```objc
>   static_assert(std::is_same<ADS1, ADS2>::value,
>                 "The derivative types must match.");
>   return f_cond ? ADS1(x) : ADS2(y);
> ```

To support eigen generic expressions (i.e. `if_then_else(x >= y, x * x, y * x * x)`), this type_traits trick is necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

> Could you do the both reviews please?

Possibly we should get an AutoDiff expert user to feature-review the autodiff_overloads.h changes.  IIRC perhaps @hongkai-dai fits that bill?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/autodiff_overloads.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7oQDbmG2fhaZl6iWv:-KX7tCDF61C_asr8uxtP:b-6ej3nz) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/autodiff_overloads.h#L120)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> To support eigen generic expressions (i.e. `if_then_else(x >= y, x * x, y * x * x)`), this type_traits trick is necessary.
</details>
Sounds like good info.  Add it to a comment here?

---

*[drake/common/double_overloads.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7q35e30wPSvdfVhWY:-KX7q35fyreCgktK29Kw:bedbobb) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/double_overloads.h#L1)):*
> ```objc
> /// @file Provides necessary operations on double to have it as a ScalarType in
> ```

BTW Check the doxygen output?  I thought `@file` had to go on a line by itself.

---

*[drake/common/double_overloads.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7qaz44MvP-FmwR6k9:-KX7qaz44MvP-FmwR6kA:bqrd3eu) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/double_overloads.h#L7)):*
> ```objc
> 
> namespace drake {
> /// Provides if-then-else expression for double.
> ```

BTW Consider adding a bit more context, like a citation to some if-then-else primitive definition?

---

*[drake/common/test/autodiff_overloads_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7rzXcY1AbK57suIVX:-KX7rzXd6p2W2LiNGynU:b1ystef) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/test/autodiff_overloads_test.cc#L70)):*
> ```cpp
>   Eigen::AutoDiffScalar<DerType> y{if_then_else(x >= 0, x * x, x * x * x)};
>   EXPECT_DOUBLE_EQ(y.derivatives()[0], 2 * x.value());
> }
> ```

Most of the ITE tests only look at the derivatives, not the value.  Is that good enough?  If so, perhaps explain why in a comment for future readers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-:-KX7txHJw32C3AEKsEC6:b-y9pjil)*

**Comment by soonho-tri** [comment]
@hongkai-dai , could you do the feature-review?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-:-KX7upNNRmrAJGynk75B:bcjrfyh)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-:-KX93pBg1T3XOXOQuu5i:b-fcupkv)*

**Comment by hongkai-dai** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/autodiff_overloads.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7oQDbmG2fhaZl6iWv:-KX9e_rpKFkTYABLQR7F:b-2k089u) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/autodiff_overloads.h#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Sounds like good info.  Add it to a comment here?
</details>
That is great! I did not know this trick to support the Eigen expression. Thanks!

---

*[drake/common/test/autodiff_overloads_test.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX9dJp-TvGDMhz0Wav4:-KX9dJp0vHxg4VwblTDp:b32085c) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/test/autodiff_overloads_test.cc#L67)):*
> ```cpp
> GTEST_TEST(AutodiffOverloadsTest, IfThenElse1) {
>   using DerType = Eigen::Vector2d;
>   Eigen::AutoDiffScalar<DerType> x{10.0, DerType{1, 0}};
> ```

Maybe use a non-zero value for the derivative? How about `DerType{1, 2}`? A lot of computation with value 0 remains 0, so we do not know if the result is correct.

---

*[drake/common/test/autodiff_overloads_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7rzXcY1AbK57suIVX:-KX9d3WoGHeFc6T5oOeQ:b-o6wdxa) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/test/autodiff_overloads_test.cc#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Most of the ITE tests only look at the derivatives, not the value.  Is that good enough?  If so, perhaps explain why in a comment for future readers?
</details>
Also check `y.derivatives()[1]`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203)*

**Comment by soonho-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/autodiff_overloads.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7oQDbmG2fhaZl6iWv:-KX8BKOPPEXRCjFDUNV6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/autodiff_overloads.h#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Sounds like good info.  Add it to a comment here?
</details>
Done.

---

*[drake/common/double_overloads.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7q35e30wPSvdfVhWY:-KX8BMLbA1914qCPo_Wh:b-gonbul) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/double_overloads.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Check the doxygen output?  I thought `@file` had to go on a line by itself.
</details>
Done. (You're right)

---

*[drake/common/double_overloads.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7qaz44MvP-FmwR6k9:-KX8BO59rnGuR7n6HbIZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/double_overloads.h#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider adding a bit more context, like a citation to some if-then-else primitive definition?
</details>
Done.

---

*[drake/common/test/autodiff_overloads_test.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX9dJp-TvGDMhz0Wav4:-KX9kX335yUgU1f-5gFl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/test/autodiff_overloads_test.cc#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Maybe use a non-zero value for the derivative? How about `DerType{1, 2}`? A lot of computation with value 0 remains 0, so we do not know if the result is correct.
</details>
Done.

---

*[drake/common/test/autodiff_overloads_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-KX7rzXcY1AbK57suIVX:-KX9kXgU9poyYB2U-xRL:bly20h4) ([raw file](https://github.com/robotlocomotion/drake/blob/cf40e4b4b9153f06277a5b99d89446daba5cebf0/drake/common/test/autodiff_overloads_test.cc#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Also check `y.derivatives()[1]`?
</details>
Done. (also check `y.value()`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203#-:-KX9rStsguD5jmptzT9x:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4203)*

**Comment by soonho-tri** [comment]
Thank you, @jwnimmer-tri !

**Pull request merged**
