### PR TITLE
Release notes v0.16.1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The proposed tag is `b2293bc15d192473dbe76e48e9861c860c739549`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12856)

### CODE REVIEW

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12856#-M2ECsDCDQp23L-tYA4p:-M2EI9qd7_w9SVvSgdfh:bofotct) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I will add it to the commit message, but I'm curious about unwarranted.  Just because hotfixes should be more minimal?  Or because prior relnotes should never be changed?  Or ...?
</blockquote></details>

OK my view is that it's too trivial a change to merit "changing history" (adding mysterious `git log` results, eg) in this regard.  Like putting unrelated whitespace changes in a code PR.

But this discussion has already consumed more developer time than any imaginable cost of such a change so I'm okay with any result.

---

**Comment by SeanCurtis-TRI** [comment]
___
*[doc/release_notes/v0.16.1.rst, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12856#-M2EIN1i7NfWtGa6x0hT:-M2EIN1j5gq9IZdEn0bp:bllzue3) ([raw file](https://github.com/robotlocomotion/drake/blob/16d5946a12bc6b21786a09821306eb6330c65de2/doc/release_notes/v0.16.1.rst#L24)):*
> ```reStructuredText
> `Mathematical Program toolbox
> <https://drake.mit.edu/doxygen_cxx/group__solvers.html>`__. Thanks to
> Philip E. Gill and Elizabeth Wong for their kind support.
> ```

BTW Including the last commit that this builds on is a real aid to building the next release -- it's what I would feed into the `relNotes`.

**Comment by SeanCurtis-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12856#-M2ECsDCDQp23L-tYA4p:-M2EIqRBAOHR2YSO-otC:bl1294t) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

OK my view is that it's too trivial a change to merit "changing history" (adding mysterious `git log` results, eg) in this regard.  Like putting unrelated whitespace changes in a code PR.

But this discussion has already consumed more developer time than any imaginable cost of such a change so I'm okay with any result.
</blockquote></details>

BTW I thought it made sense as that particular code to the release notes is largely copied and pasted. Might as well make it correct everywhere so we don't have to worry about where it was copied from.

---

**Comment by SeanCurtis-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12856#-M2ECsDCDQp23L-tYA4p:-M2EJ-FB5nw1pSo8eLHT:bd5j40a) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I thought it made sense as that particular code to the release notes is largely copied and pasted. Might as well make it correct everywhere so we don't have to worry about where it was copied from.
</blockquote></details>

s/code/coda

---

**Comment by jwnimmer-tri** [comment]
___
*[doc/release_notes/v0.16.1.rst, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12856#-M2EIN1i7NfWtGa6x0hT:-M2ESe_iC9WucXAVKJK7:bm7kjho) ([raw file](https://github.com/robotlocomotion/drake/blob/16d5946a12bc6b21786a09821306eb6330c65de2/doc/release_notes/v0.16.1.rst#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Including the last commit that this builds on is a real aid to building the next release -- it's what I would feed into the `relNotes`.
</blockquote></details>

Yeah.  Question is whether 0.17.0 relnotes should explain the differences since 0.16.0 or 0.16.1.  Either way, nothing in the .0->.1 commits was relnoteable, so it's moot for now.

**Pull request merged**
