### PR TITLE
[workspace] Upgrade rust_toolchain, rules_rust to latest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
- Upgrade rust_toolchain to latest
- Upgrade rules_rust to latest release 0.52.0

Towards #21979.

When merging, we should squash this (nixing the irrelevant second-and-following commit messages). The release note we want is just the version bump (the first commit message, including the details from its body).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21996)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews (off schedule), please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-noble-gcc-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21996#-:-O8cVVKQ0YA_JT-XQgj8:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21996#-:-O8cVZeG33BiHwsNMwT3:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
