### PR TITLE
Add bazel install rules for protobuf

### PR DESCRIPTION
**Pull request by fbudin69500**
Toward #3129.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6339)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/install/protobuf/BUILD, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfu8uNz6TjKhsda1DE:-Kmfu8uNz6TjKhsda1DF:b9jdgu6) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L7)):*
> ```Python
> package(default_visibility = ["//visibility:public"])
> 
> cmake_config(
> ```

Maybe add a comment about the version embedded in the CPS file.

---

*[tools/install/protobuf/BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmft66cOM3caJHNW32c:-Kmft66cOM3caJHNW32d:bksuqjc) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L14)):*
> ```Python
> install_cmake_config(package = "protobuf")  # Creates :install_cmake_config
> 
> excluded_headers = [
> ```

A comment how you derived this list?

---

*[tools/install/protobuf/BUILD, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfuv7jyULVH_EINaoE:-Kmfuv7jyULVH_EINaoF:b-u75arv) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L154)):*
> ```Python
>     guess_hdrs = "PACKAGE",
>     guess_hdrs_exclude = excluded_headers,
>     hdr_dest = "include",
> ```

This is the default.

---

*[tools/install/protobuf/protobuf.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftTdvt3FGxoREwHNG:-KmftTdvt3FGxoREwHNH:b-xxcarq) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L4)):*
> ```delphi
>   "Cps-Version": "0.8.0",
>   "Name": "protobuf",
>   "Description": "Protocol Buffers - Google's data interchange format",
> ```

I would just say "Language-neutral, platform-neutral, extensible mechanism for serializing structured data", or at least a summary of that.

---

*[tools/install/protobuf/protobuf.cps, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfu4-DLfZ7jr-vXK47:-Kmfu4-DLfZ7jr-vXK48:b-tcw8hd) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L5)):*
> ```delphi
>   "Name": "protobuf",
>   "Description": "Protocol Buffers - Google's data interchange format",
>   "License": "BSD-2-Clause",
> ```

BSD-3-Clause, I think.

---

*[tools/install/protobuf/protobuf.cps, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftNUy7SyLky0waqVR:-KmftNUy7SyLky0waqVS:b-9dmcca) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L7)):*
> ```delphi
>   "License": "BSD-2-Clause",
>   "Version": "3.1.0",
>   "Default-Components": [":protobuf", ":protobuf_lite", ":protoc_lib"],
> ```

Is this correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/install/protobuf/BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmft66cOM3caJHNW32c:-Kmg8hzlkL3jNASBQd4F:bc60ov1) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

A comment how you derived this list?
</blockquote></details>

Indeed. Moreover, can some/all of this be replaced with a `glob`?

Better still, is the list of *public* headers not shorter? `protobuf-devel-2.6.1-5.fc25.x86_64` seems to imply that it is...

---

*[tools/install/protobuf/BUILD, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgAIYM4FuKq9BboW-v:-KmgAIYOhpRoSCoKtxBI:b-wb041f) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L157)):*
> ```Python
>     hdr_strip_prefix = ["src"],
>     license_docs = ["@protobuf//:LICENSE"],
>     runtime_dest = "bin",
> ```

Also default

---

*[tools/install/protobuf/protobuf.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftTdvt3FGxoREwHNG:-KmgAbvrxcOleSpukBak:b3xiwny) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I would just say "Language-neutral, platform-neutral, extensible mechanism for serializing structured data", or at least a summary of that.
</blockquote></details>

Note: although I'm not in love with this text either, it *is* the description in Fedora's package, and may be "canonical" in some sense...

---

*[tools/install/protobuf/protobuf.cps, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgBXh2iG1P1Mwnz44H:-KmgBXh4Pxs131ja1k02:bexayb6) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L6)):*
> ```delphi
>   "Description": "Protocol Buffers - Google's data interchange format",
>   "License": "BSD-2-Clause",
>   "Version": "3.1.0",
> ```

Please add a note in `WORKSPACE` to keep this in sync. (I'm assuming that this is impossible to derive, like with gflags?)

---

*[tools/install/protobuf/protobuf.cps, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftNUy7SyLky0waqVR:-KmgB1M8zLpNr6i3AbUv:btm1q03) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Is this correct?
</blockquote></details>

Probably not; aren't these all — or at least, `protobuf` and `protobuf_lite` (is `protoc_lib` the compiler library? Or the C library?) — mutually exclusive?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by fbudin69500** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/install/protobuf/BUILD, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfu8uNz6TjKhsda1DE:-KmgAI9VGyzTW_HlbJK3:b-da7ipw) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Maybe add a comment about the version embedded in the CPS file.
</blockquote></details>

Comment added in WORKSPACE to update protobuf.cps when updating the version of protobuf. Is that enough?

---

*[tools/install/protobuf/BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmft66cOM3caJHNW32c:-KmgAJBYdOjqLzYlOS6-:bctio3d) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Indeed. Moreover, can some/all of this be replaced with a `glob`?

Better still, is the list of *public* headers not shorter? `protobuf-devel-2.6.1-5.fc25.x86_64` seems to imply that it is...
</blockquote></details>

Because it is a bazel BUILD project for which we add an install rule, bazel does not accept a list of public headers to be installed. The number of files that would be listed in a public_headers variable would be roughly the same (about 140) compared to 130 in this case.

---

*[tools/install/protobuf/BUILD, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfuv7jyULVH_EINaoE:-Kmg7uveIr8kCCDQ8iMI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L154)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This is the default.
</blockquote></details>

Done.

---

*[tools/install/protobuf/BUILD, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgAIYM4FuKq9BboW-v:-KmgEv-NUXH4HI9Ye8Ku:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L157)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Also default
</blockquote></details>

Done.

---

*[tools/install/protobuf/protobuf.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftTdvt3FGxoREwHNG:-Kmg7WCgNPq9-6GDPjFb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I would just say "Language-neutral, platform-neutral, extensible mechanism for serializing structured data", or at least a summary of that.
</blockquote></details>

Done.

---

*[tools/install/protobuf/protobuf.cps, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmfu4-DLfZ7jr-vXK47:-Kmg7Weyz6VDeaAwT3LO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BSD-3-Clause, I think.
</blockquote></details>

Done.

---

*[tools/install/protobuf/protobuf.cps, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgBXh2iG1P1Mwnz44H:-KmgFBICDgVwh7YNuX2N:bjcs5dc) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L6)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Please add a note in `WORKSPACE` to keep this in sync. (I'm assuming that this is impossible to derive, like with gflags?)
</blockquote></details>

Indeed. Done.

---

*[tools/install/protobuf/protobuf.cps, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmftNUy7SyLky0waqVR:-Kmg7XFOt6Fl-wGqoprV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/protobuf.cps#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Is this correct?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/install/protobuf/BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmft66cOM3caJHNW32c:-KmgSdT-0NqWSNArtl2e:b-dflpu6) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L14)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Because it is a bazel BUILD project for which we add an install rule, bazel does not accept a list of public headers to be installed. The number of files that would be listed in a public_headers variable would be roughly the same (about 140) compared to 130 in this case.
</blockquote></details>

Ah, right. At any rate, can you comment how this was derived?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by fbudin69500** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/install/protobuf/BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-Kmft66cOM3caJHNW32c:-KmgVMSai4PEmRFRNu8s:b-4kznfi) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1271cbe7f9034e713860c923887beda73a91e5/tools/install/protobuf/BUILD#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Ah, right. At any rate, can you comment how this was derived?
</blockquote></details>

I added a comment in my last commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-KmgW2hyEIhbFcV2vOU8:bdrx3jg) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
> ```delphi
> {
>   "Cps-Version": "0.8.0",
>   "Name": "protobuf",
> ```

Should this be `Protobuf` and `Protobuf.cps` as you updated the package name above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-Kmgdg_dy-vvBDBvuAjI:bmbhisw) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should this be `Protobuf` and `Protobuf.cps` as you updated the package name above?
</blockquote></details>

In the config file generated by CMake, the namespace is protobuf, not Protobuf:

from protobuf-targets.cmake:
set_target_properties(protobuf::libprotoc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "protobuf::libprotobuf"
)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-KmgeJv2E74LTsFAAuEW:b-rp37n2) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

In the config file generated by CMake, the namespace is protobuf, not Protobuf:

from protobuf-targets.cmake:
set_target_properties(protobuf::libprotoc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "protobuf::libprotobuf"
)

</blockquote></details>

So change the package name back to `protobuf`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-KmgfITU8EWnSy42O2zM:b-cvkd6q) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So change the package name back to `protobuf`.
</blockquote></details>

What @jamiesnape said. The `.cps` file name should match the CPS package name. (Also, file a bug against upstream if their package name and namespace name don't match.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-Kmgee5J5njlO-5ZBT9Q:bd01lgl) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What @jamiesnape said. The `.cps` file name should match the CPS package name. (Also, file a bug against upstream if their package name and namespace name don't match.)
</blockquote></details>

Their project is in lowercase:
https://github.com/google/protobuf/blob/master/cmake/CMakeLists.txt#L12
And their namespace is also lowercase:
https://github.com/google/protobuf/blob/master/cmake/install.cmake#L98

I was trying to match the `find_package(` that I found for Protobuf, and it seemed inconsistent:

lowercase here:
https://github.com/google/protobuf/blob/efec7571047c680e11354bd30bf8bd3dfda15ff0/examples/CMakeLists.txt#L8

Expecting uppercase?
https://github.com/RobotLocomotion/drake/blob/master/cmake/modules/3.8/FindProtobuf.cmake#L415

Switching everything back to lowercase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/protobuf/protobuf.cps, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-KmgW2hyEIhbFcV2vOU7:-KmgiFBWVeV4yzuIoptS:b-do9npj) ([raw file](https://github.com/robotlocomotion/drake/blob/1a250ac4a34e95c2efc691f65c1458e3bab80017/tools/install/protobuf/protobuf.cps#L3)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Their project is in lowercase:
https://github.com/google/protobuf/blob/master/cmake/CMakeLists.txt#L12
And their namespace is also lowercase:
https://github.com/google/protobuf/blob/master/cmake/install.cmake#L98

I was trying to match the `find_package(` that I found for Protobuf, and it seemed inconsistent:

lowercase here:
https://github.com/google/protobuf/blob/efec7571047c680e11354bd30bf8bd3dfda15ff0/examples/CMakeLists.txt#L8

Expecting uppercase?
https://github.com/RobotLocomotion/drake/blob/master/cmake/modules/3.8/FindProtobuf.cmake#L415

Switching everything back to lowercase.
</blockquote></details>

The upstream `protobuf-config.cmake` is also lower case (whew, no mismatch there), so lower case is correct. Upper case appears to be the legacy find module; I'm much less worried about compatibility with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-:-KmgjZlv2EPaqlSFXUib:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-:-Kmgm9uUhEpWHcK-yNFq:bnfp4nl)*

**Comment by fbudin69500** [comment]
+@soonho-tri platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-:-Kmgnp2EeyZYC2w3eM4P:bc1ylfv)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6339#-:-KmmDhKdn3ugGrcGBCv-:bnfp4nl)*

**Pull request merged**
