### PR TITLE
Modifying Attribute for GCC < 4.9.x

### PR DESCRIPTION
**Pull request by m-chaturvedi**
To address https://github.com/RobotLocomotion/drake/issues/6853

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6856)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
+@jamiesnape for feature review, please.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please.

**Comment by jamiesnape** [comment]
:lgtm, though really we need documentation as to why this is needed given our supported platforms.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6856#-:-KrguOR83Qxcw0Ek5myg:b-58dgcs)*

**Comment by jamiesnape** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6856#-:-Krguhlqbt3H25M_V9-4:bg7igkv)*

**Comment by m-chaturvedi** [comment]
+@jwnimmer-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Pull request merged**
