### PR TITLE
adds the discrete time simple examples in system2.0 to c++

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4183)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@david-german-tri for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-:-KX1cikuqxZgogTxkDXO:b-ntsnry)*

**Comment by sherm1** [comment]
(+@sherm1 for platform review) There are some consistency problems in the API among EvalTimeDerivatives/EvalDifferenceUpdates/EvalOutputs but there are already several related issues filed and these can be addressed while getting caching operational for them. So, :lgtm:.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/simple_continuous_time_system.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_TYaze9lGSzLf-fl:-KX2_TYaze9lGSzLf-fm:b-4jxld4) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_continuous_time_system.cc#L58)):*
> ```cpp
> 
>   // make sure the simulation converges to the stable fixed point at x=0
>   DRAKE_ASSERT(xc[0] < 1.0e-4);
> ```

BTW, `DRAKE_DEMAND` would be better here since there is no reason to remove this in Release builds.

---

*[drake/examples/simple_discrete_time_system.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_cfOQjUrpQj-cm7a:-KX2_cfOQjUrpQj-cm7b:b-6fyrer) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_discrete_time_system.cc#L58)):*
> ```cpp
> 
>   // make sure the simulation converges to the stable fixed point at x=0
>   DRAKE_ASSERT(xd.get_difference_state(0)->GetAtIndex(0) < 1.0e-4);
> ```

BTW, prefer `DRAKE_DEMAND` here.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2V0gOdujrYY6JrUPa:-KX2V0gP3rxbQT4F4YzQ:bduu3xf) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L27)):*
> ```cpp
>     this->DeclareDifferenceState(kSize);
>   }
>   ~SimpleMixedContinuousTimeDiscreteTimeSystem() override{};
> ```

BTW, not needed. If kept nit: needs a space before `{}`.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_hjcwDc_r3HzmF2Z:-KX2_hjcwDc_r3HzmF2_:b-6fyrer) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L78)):*
> ```cpp
>   // make sure the simulation converges to the stable fixed point at x=0
>   DRAKE_ASSERT(xd.get_difference_state(0)->GetAtIndex(0) < 1.0e-4);
>   DRAKE_ASSERT(xc[0] < 1.0e-4);
> ```

BTW, prefer `DRAKE_DEMAND` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-:-KX2ZPsZnirAAqjUciGq:b-3zng0)*

**Comment by RussTedrake** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/simple_continuous_time_system.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_TYaze9lGSzLf-fl:-KX3YSFGG9jCb1DvYOER:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_continuous_time_system.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `DRAKE_DEMAND` would be better here since there is no reason to remove this in Release builds.
</details>
Done.

---

*[drake/examples/simple_discrete_time_system.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_cfOQjUrpQj-cm7a:-KX3YVaQQPiPaYzZ0_Qs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_discrete_time_system.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, prefer `DRAKE_DEMAND` here.
</details>
Done.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2V0gOdujrYY6JrUPa:-KX3YXb0RchFXQwmQYQH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, not needed. If kept nit: needs a space before `{}`.
</details>
Done.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX2_hjcwDc_r3HzmF2Z:-KX3YYYY9HUlfxa6YnID:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6cea42a64568dcf7ddb0bf161afdd84ebd6661d6/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, prefer `DRAKE_DEMAND` here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/simple_discrete_time_system.cc, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6f5r9Yzdecg91-tKS:-KX6f5r9Yzdecg91-tKT:b-bs8qjr) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L18)):*
> ```cpp
>   SimpleDiscreteTimeSystem() {
>     const int kSize = 1;  // The dimension of both output (y) and state (x).
>     this->DeclarePeriodicUpdate(1.0, 0.0);
> ```

would be clearer with the single-argument version: `DeclareUpdatePeriodSec(1.0)`.

---

*[drake/examples/simple_discrete_time_system.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6fwh7tma8PyQnQkHu:-KX6fwh7tma8PyQnQkHv:b-quiuid) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L28)):*
> ```cpp
>       const drake::systems::Context<double>& context,
>       drake::systems::DifferenceState<double>* updates) const override {
>     double x = context.get_difference_state(0)->GetAtIndex(0);
> ```

btw you can use `[]` instead of GetAtIndex/SetAtIndex if you like

---

*[drake/examples/simple_discrete_time_system.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gJ88CTJ0zDPJpwQR:-KX6gJ88CTJ0zDPJpwQS:bomdcfh) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L36)):*
> ```cpp
>   void EvalOutput(const drake::systems::Context<double>& context,
>                   drake::systems::SystemOutput<double>* output) const override {
>     double x = context.get_difference_state(0)->GetAtIndex(0);
> ```

btw, could use SetFromVector here

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gQLxFXUnbs7fVK_d:-KX6gQLxFXUnbs7fVK_e:b-x5j923) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L21)):*
> ```cpp
>   SimpleMixedContinuousTimeDiscreteTimeSystem() {
>     const int kSize = 1;
>     this->DeclarePeriodicUpdate(1.0, 0.0);
> ```

consider `DeclareUpdatePeriodSec`

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gjGXKiSF1ged_HcO:-KX6gjGXKiSF1ged_HcP:bw9jp4z) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L32)):*
> ```cpp
>       const drake::systems::Context<double>& context,
>       drake::systems::DifferenceState<double>* updates) const override {
>     double x = context.get_difference_state(0)->GetAtIndex(0);
> ```

btw `const`?  Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-:-KX6hDU2aWsYoOdXWsa1:bnfp4nl)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-:-KX6hImB0IxuwLOMtsdq:b-s794vx)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/simple_discrete_time_system.cc, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6f5r9Yzdecg91-tKS:-KX8WPXCb3OpUPtm7XAF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> would be clearer with the single-argument version: `DeclareUpdatePeriodSec(1.0)`.
</details>
Done.

---

*[drake/examples/simple_discrete_time_system.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6fwh7tma8PyQnQkHu:-KX8WSdW-5-RUz58UGGy:bv8yy3z) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L28)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw you can use `[]` instead of GetAtIndex/SetAtIndex if you like
</details>
thx.  i would if I was making a local variable, but for these one liners, I think this version is easier.

---

*[drake/examples/simple_discrete_time_system.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gJ88CTJ0zDPJpwQR:-KX8XLfvAxzmm5ALqLvm:b2znf10) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_discrete_time_system.cc#L36)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw, could use SetFromVector here
</details>
Done.  Not sure if it's actually better (since the output is a scalar), but i like that it's more general.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gQLxFXUnbs7fVK_d:-KX8XZXLD3NDm1_5kfD9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> consider `DeclareUpdatePeriodSec`
</details>
Done.

---

*[drake/examples/simple_mixed_continuous_and_discrete_time_system.cc, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-KX6gjGXKiSF1ged_HcO:-KX8Xus4WNYGo7_01bTb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c5bb140892ad33a29a69e7668408a3a97649e/drake/examples/simple_mixed_continuous_and_discrete_time_system.cc#L32)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw `const`?  Throughout.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4183#-:-KX8Zb80usZukKAWdH8f:bnfp4nl)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
