### PR TITLE
Deprecate CalcCenterOfMassPosition() in favor of CalcCenterOfMassPositionInWorld().

### PR DESCRIPTION
**Pull request by mitiguy**
Resolves issue #14537

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@ericcousineau-tri 
Hi Eric -- I was hoping you might review this hopefully straight-forward PR.
It is mostly a "cut and paste", with a small effect on python, so I was hoping you might take a look.
 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MR7x0cxDmnKbqSkUsmS:b-3c204k)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Yup, sounds good! Just needs Python deprecations.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MRARCvF1XbqetL0yM9_:b3wbbl9)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRAQu2lC3d5_uTyLFF1:-MRAQu2lC3d5_uTyLFF2:bx85qu2) ([raw file](https://github.com/robotlocomotion/drake/blob/e1dab8b3fac68115b8e5176a37eff5909ed11033/bindings/pydrake/multibody/plant_py.cc#L286)):*
> ```cpp
>         // overload that (a) services MBP directly and (b) uses body
>         // association that is less awkward than implicit BodyNodeIndex.
>         .def("CalcCenterOfMassPositionInWorld",
> ```

This is not backwards compatible; it requires deprecation in Python too.

See:
https://drake.mit.edu/code_review_checklist.html#is-the-code-the-minimal-set-of-what-you-want


https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeDeprecation

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRRlALz4R49Q4LeW4sC:bbmft58) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
> ```cpp
>             py::arg("context"), py::arg("model_instances"),
>             cls_doc.CalcCenterOfMassPosition.doc_2args)
> #pragma GCC diagnostic pop
> ```

@ericcousineau-tri 

 I looked at the deprecation_example, but it was not immediately obvious how to apply it to what might be a simpler problem.  Here is my first guess, but it does not pass CI and it is unclear how many guesses I will make before converging. 

I just talked to Sherm and he said you might be able to help get me back on track. 

Do you have a simple example in which a single method (rather than parts of an entire class) are deprecated?   Or perhaps you can point me to a tiny PR that accomplishes what I am trying to do.

Note:  Perhaps a simpler deprecation example would be helpful to understand what needs to be added to the file (perhaps some #includes) and the strategy to place some #pragmas, and any other pitfalls.  It is difficult to see how this specific problem gets fixed as the example addresses a more complicated problem.  

Once I get the simplest concept down, and see how to extend it a little, I usually can extrapolate from there.  I have a more difficult time trying to a generalization and making it more specific.  I blame my elementary math teachers who taught me how to add 3 + 5 rather than matrices -- hopefully your Mathworks background made you smile :).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRS3bLm2mZdOPyuEINQ:b-h33vn4) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
Did you see these two examples and the preceding comments, and review the documentation that exists regarding docstrings (e.g. `.doc_deprecated`)?
https://github.com/RobotLocomotion/drake/blob/f20d6761e8c30433fce022cfba2b78f832213329/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L62-L78

> [...] is unclear how many guesses I will make before converging.

The fact that your write "guess" given that docs and code exist is part of the problem ;)

But yeah, let's address the general readability of this example in a separate PR that I will start, and then you can take lessons learned and apply it here.

Sound good?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRS5dBQ66VgqDsNzyDC:ba3ennh) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Did you see these two examples and the preceding comments, and review the documentation that exists regarding docstrings (e.g. `.doc_deprecated`)?
https://github.com/RobotLocomotion/drake/blob/f20d6761e8c30433fce022cfba2b78f832213329/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L62-L78

> [...] is unclear how many guesses I will make before converging.

The fact that your write "guess" given that docs and code exist is part of the problem ;)

But yeah, let's address the general readability of this example in a separate PR that I will start, and then you can take lessons learned and apply it here.

Sound good?
</blockquote></details>

Correction: [...] given that docs, code, and compiler errors exist [...]

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRSIRVACKohoAT4fZWj:b-7c1808) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Correction: [...] given that docs, code, and compiler errors exist [...]
</blockquote></details>

See minimum-effort PR here for easier-to-cargo-cult examples:
https://github.com/RobotLocomotion/drake/pull/14546

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRU_umfBL5wVeetqxLh:b-9pq8dd) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
> hopefully your Mathworks background made you smile :)

And hehe, yup!

**Review by mitiguy — COMMENTED** [review]
@ericcousineau-tri   Thanks for taking time for the f2f.  I updated multibody_plant.h.
Thanks for agreeing to showing me how to deprecate the API in the Python/C++ bindings.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MRb2JeM1D8LNR_j_X4B:b5ewxc1)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRbEtjH8XowluaOWJxZ:b-jolt7c) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> hopefully your Mathworks background made you smile :)

And hehe, yup!
</blockquote></details>

See PR that fixes the deprecation:
https://github.com/mitiguy/drake/pull/4/files
___
*[multibody/plant/test/multibody_plant_com_test.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRbBMq73vh3vhIdI-7N:-MRbBMq73vh3vhIdI-7O:b-n15d4f) ([raw file](https://github.com/robotlocomotion/drake/blob/d8612d3751bad884260fb34c331e7f2273845440/multibody/plant/test/multibody_plant_com_test.cc#L24)):*
> ```cpp
>   auto context_ = plant.CreateDefaultContext();
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       plant.CalcCenterOfMassPositionInWorld(*context_),
> ```

This file still needs to do a basic test of the deprecated API.

Please test that the deprecated API still exists within a `#pragma...` block.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRRlALz4R49Q4LeW4sB:-MRbGAkt04nK7Eak4HW4:b-vb0ur4) ([raw file](https://github.com/robotlocomotion/drake/blob/b76d38298f21c059213b017463e7dbe44f8ad460/bindings/pydrake/multibody/plant_py.cc#L299)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

See PR that fixes the deprecation:
https://github.com/mitiguy/drake/pull/4/files
</blockquote></details>

(You'll want to merge it in here, of course!)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRvBVDQDWMzp-dxtI08:-MRAQqwa3jm2fPHvQwja:bx53knc) (no related file):*
FYI Requires a deps update:
https://drake-cdash.csail.mit.edu/test/109660810

---

**Review by mitiguy — COMMENTED** [review]
@ericcousineau-tri 
Ugh -- I am sure I am doing something silly, but this does not pass CI.
From the error stack on CI,  it seems like the error points to:

File: plant_test.py, line 76 which is:
from pydrake.common.test_utilities.deprecation import catch_drake_warnings

ModuleNotFoundError: No module named 'pydrake.common.test_utilities.deprecation'

I looked for ModuleNotFoundError with Drake and found these issues -- but am unsure if they are relevant.
https://github.com/RobotLocomotion/drake/issues/11005
https://stackoverflow.com/questions/62292888/building-and-using-pydrake-from-source

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MRvA3Pi8RrYYg1hCvMy:bhzhkr0)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[multibody/plant/test/multibody_plant_com_test.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRbBMq73vh3vhIdI-7N:-MRgk0DQEzwQTtlmYaya:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8612d3751bad884260fb34c331e7f2273845440/multibody/plant/test/multibody_plant_com_test.cc#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This file still needs to do a basic test of the deprecated API.

Please test that the deprecated API still exists within a `#pragma...` block.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
Just missing Bazel deps:
https://github.com/RobotLocomotion/drake/commit/61d53483f8#diff-e7881d2775f3e47f7b244280446b48d080e23710d79a218171114ad447578870R477

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MRvJvSZAwgM2Y5Xyml7:b-hiv1va)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRvBVDQDWMzp-dxtI08:-MRvJblb84kSgC8cAqBz:b-a9l39p) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Requires a deps update:
https://drake-cdash.csail.mit.edu/test/109660810
</blockquote></details>

@mitiguy Did you see this comment?

Per prior PR: 

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MRvBVDQDWMzp-dxtI08:-MRvJzy6AGaqbXRSGW2-:b-btenuo) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@mitiguy Did you see this comment?

Per prior PR: 
</blockquote></details>

OK Oops. Sorry, meant to strike out this message.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@ericcousineau-tri   
This is nearing completion and may (or may not) just have a single typo.
Thank you for your help thus far.  PTAL.

> Reviewed 5 of 9 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MRveAMfAPUHpSW_wmON:bvm6j1v)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MS0X9Z1EaMZfPhgrxX0:-MS0X9Z1EaMZfPhgrxX1:b923vxt) ([raw file](https://github.com/robotlocomotion/drake/blob/0ae86b8b0c1b63d30caa85519fdba81e3b1a39bb/bindings/pydrake/multibody/plant_py.cc#L299)):*
> ```cpp
>                 overload_cast_explicit<Vector3<T>, const Context<T>&,
>                     const std::vector<ModelInstanceIndex>&>(
>                     &Class::CalcCenterOfMassPositionInWorld)),
> ```

@ericcousineau-tri   
I cut and paste from your _very_ helpful example from:
https://github.com/mitiguy/drake/pull/4/files

I was wondering if the previous line should instead be:
&Class::CalcCenterOfMassPosition)),

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

+@sammy-tri for platform review, please!

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MS2sDAG2Ocn7MOdH9wl:b-3v5my6)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sammy-tri)

___
*[bindings/pydrake/multibody/plant_py.cc, line 299 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14538#-MS0X9Z1EaMZfPhgrxX0:-MS2s94FCgkHEzV17RdI:b-o63gc8) ([raw file](https://github.com/robotlocomotion/drake/blob/0ae86b8b0c1b63d30caa85519fdba81e3b1a39bb/bindings/pydrake/multibody/plant_py.cc#L299)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

@ericcousineau-tri   
I cut and paste from your _very_ helpful example from:
https://github.com/mitiguy/drake/pull/4/files

I was wondering if the previous line should instead be:
&Class::CalcCenterOfMassPosition)),
</blockquote></details>

Ah, yup, that was a typo on my part! It should be the deprecated overload, yes.

**Review by mitiguy — COMMENTED** [review]
@sammy-tri    I fixed typo and if this passes CI, it is ready for your platform review.

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MS3bv0q-sFK1R3XvE4P:bhe5m8p)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MS41lqe5DXI6CP_rHes:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14538#-:-MS41w485l0hYNU5Lyvb:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Remember to round up all deprecation dates to the first of the month, otherwise we tend to miss when they come due (#15050).

**Comment by EricCousineau-TRI** [comment]
Ah, sorry for missing that!

**Pull request merged**
