### PR TITLE
Iris in rational configuration space

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18492)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@russtedrake for feature review please! I could use some advice on a good testing strategy for IrisInRationalConfigurationSpace.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18492#-:-NK0XnUI2OWMJN2kLeon:b8p9a8x)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Checkpoint.  I haven't reviewed the the tests/testing strategy yet. PTAL.

> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18492#-:-NKp3PZlAE4A4ZfKXtxc:b-1q0xvy)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`-- commits` line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKor7b5A7IWqi6vwWHc):*
we'll need a single clear commit message when we're ready to commit.
___
*[`geometry/optimization/BUILD.bazel` line 205 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKouax97x0XLgn0G-Xv:-NKouax97x0XLgn0G-Xw:b-6rpgen) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/BUILD.bazel#L205)):*
> ```Starlark
>     timeout = "moderate",
>     data = ["//multibody/parsing:test_models"],
>     shard_count = 8,
> ```

this was due to the iris_in_configuration_space setup.  we need to revisit it when you've finalized your testing strategy.
___
*[`geometry/optimization/iris.h` line 176 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKoto03CP31qLs-uIEI:-NKoto03CP31qLs-uIEJ:b-eyybkh) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.h#L176)):*
> ```objc
>     const IrisOptions& options = IrisOptions());
> 
> /** A variation of the Iris (Iterative Region Inflation by Semidefinite
> ```

i probably should have put IrisInConfigurationSpace in it's own header; this is pushing it even further.  ideally we'd have iris_in_configuration_space.h/.cc and iris_in_rational_configuration_space.h/.cc . wdyt?  (i do see that you're sharing some of the functionality between the two; we would have to handle that).

Another alternative would be to use IrisInConfigurationSpace as the entry point for your method, too... and just enable/disable the rational version with an IrisOption.
___
*[`geometry/optimization/iris.h` line 179 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKowfiW-zFzeRwriFrS:-NKowfiW-zFzeRwriFrT:blkd9hg) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.h#L179)):*
> ```objc
> programming) algorithm which finds collision-free regions in the *rational
> parametrization of the configuration space* of @p plant. @see Iris for details
> on the original algorithm.
> ```

it would help to have a little more here. I didn't realize until reading the code that this is NOT the SOS version; but is really the same IrisInConfigurationSpace algorithm, with only the parameterization changed.  Presumably it is meant primarily for compatibility / comparison with the SOS version, but it would be good to make that clear here.  (e.g. if a user stumbles upon this method, why would they want to use it? or should they use the other version).

Now that i understand this, I'm much more inclined to use the existing IrisInConfigurationSpace entry point and just add the rational parameterization as an IrisOption.
___
*[`geometry/optimization/iris.cc` line 219 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKoxOGPArWu4vULGeXm:-NKoxOGQ7QhLxVxnYZXm:bj5rsvd) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6cd7b7aa85a6de51b4495f84aefafcac363908/geometry/optimization/iris.cc#L219)):*
> ```cpp
> namespace {
> 
> // Takes q, p_AA, and p_BB and enforces that p_WA == p_WB.
> ```

i think this comment was still helpful?  (even if needs to be slightly updated)
___
*[`geometry/optimization/iris.cc` line 317 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKp2LpG0DyVDpkR9NEe:-NKp2LpG0DyVDpkR9NEf:b72doks) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L317)):*
> ```cpp
>     Eigen::Matrix3Xd Jcspace_variable_v_WA(3, plant_->num_positions()),
>         Jcspace_variable_v_WB(3, plant_->num_positions());
>     for (int i = 0; i < plant_->num_positions(); i++) {
> ```

This is going to slow down the main IrisInConfigurationSpace algorithm. (hopefully not by much, but this function gets called A LOT; @mpetersen94 and I have started trying to optimize it).  is there a way to avoid that added cost?
___
*[`geometry/optimization/iris.cc` line 318 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKoyu2TE0TMNpaXFKMS:-NKoyu2TE0TMNpaXFKMT:b-kgzkje) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L318)):*
> ```cpp
>         Jcspace_variable_v_WB(3, plant_->num_positions());
>     for (int i = 0; i < plant_->num_positions(); i++) {
>       // dX_t_wa = J_q_WA * dq_dt
> ```

This comment is definitely wrong. dX would be a matrix; you presumably mean that Jcspace_variable_v_WA is dp_WA/dcspace_variable.

the right hand side should be Jq_v_WA.

but then we should have dp_WA/dcspace_variable = dp_WA/dqdot * dqdot/dcspace_variable .  but that's not what you have in q(i).derivatives? So I'm worried the math is wrong, too?
___
*[`geometry/optimization/iris.cc` line 703 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKp3-LB8DqVW-9MXgjy:-NKp3-LB8DqVW-9MXgjz:bdnalrv) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L703)):*
> ```cpp
> //  @return
> HPolyhedron _DoIris_(const multibody::MultibodyPlant<double>& plant,
>                      const systems::Context<double>& context,
> ```

not sure why you needed multibody:: and systems:: here.  
___
*[`geometry/optimization/iris.cc` line 811 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18492#-NKp3BVR9FFWdiqHbgyy:-NKp3BVR9FFWdiqHbgyz:b3ztjc4) ([raw file](https://github.com/robotlocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L811)):*
> ```cpp
>     // Handle bounding box and linear constraints as a special case (extracting
>     // them from the additional_constraint_bindings).
>     auto AddConstraint = [&](const Eigen::MatrixXd& new_A,
> ```

might as well remove the Eigen:: here, too, for consistency.

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-:-NM0jefY-8Mp4avTARWf:b7ovtzr)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

___
*[`-- commits` line 111 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-NKor7b5A7IWqi6vwWHc):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we'll need a single clear commit message when we're ready to commit.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18492)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.cc` line 703 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-NKp3-LB8DqVW-9MXgjy:-NMA3hILAR2-b2K3YgLJ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L703)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

not sure why you needed multibody:: and systems:: here.  
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 811 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-NKp3BVR9FFWdiqHbgyy:-NMA3hb82-0yHNUZ-7Pc:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L811)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

might as well remove the Eigen:: here, too, for consistency.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
-(status: do not review) 

Still no tests but a math question.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-:-NMA3ny3A6ksZeqBBXEO:bg7lcyj)* status: 9 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18492)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`-- commits` line 111 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-NKor7b5A7IWqi6vwWHc):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

uh... maybe not done?
___
*[`geometry/optimization/iris.cc` line 318 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18492#-NKoyu2TE0TMNpaXFKMS:-NMYpGR0CuToQyPfGXf4:bq5rc9q) ([raw file](https://github.com/RobotLocomotion/drake/blob/e85c3898a535f80e8e880e3fedddf7d601c74638/geometry/optimization/iris.cc#L318)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Letting `cspace_variable` be `s` shouldn't this be:
`dp_WA/dsdot =  dp_WA/dqdot * dqdot/dcspace_variable`

If `q = g(s)`, then `qdot = dg/ds * ds/dt = dg/ds*sdot` and so `dqdot/ds_dot = dg/ds` which should be `q(i).derivatives`?

</blockquote></details>

Do you mean for the first equation to be `dp_WA/dsdot = dp_WA/dqdot * dqdot/dsdot` ?  I didn't realize you were using sdot here... I think that was my oversight.

On the entry to the function, s(i).derivatives() will be dsi_danything (typically the solver calls it with the autodiff initialized to dsi_ddecisionvars).  q(i).derivatives() will be dg/ds * ds / danything; that's how the forward mode autodiff works.

**Pull request closed without merging**
