### PR TITLE
Generalize lcm_vector_gen, and apply it to Pendulum.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for feature review, @sammy-tri for platform review

@RussTedrake FYI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3690)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHE1LkXdBoCVaUeWs:-KTLHE1M1mPujnmTfyfC:b-tmnm79) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L14)):*
> ```Shell
> source $drake/tools/lcm_vector_gen.sh
> 
> gen_vector "pendulum state" theta thetadot
> ```

Until the System1 Pendulum.h gets removed, there's another class PendulumState in there...  I am hoping to remove it in the near-ish future, but for now I worry this could be a confusing duplication.

---

*[drake/tools/lcm_vector_gen.py, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHXnSLNVKXawXKpQ6:-KTLHXnSLNVKXawXKpQ7:b-km9fmc) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L325)):*
> ```Python
> 
>     with open(os.path.join(cxx_dir, "%s.h" % snake), 'w') as hh:
>         print "generating %s" % hh.name
> ```

BTW no objection to this print, just making sure it's deliberate and not a leftover debug print.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 10 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/simple_car_gen.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJHPY0Aso6l2ayHqg:-KTLJHPY0Aso6l2ayHqh:bwd5z1n) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/automotive/simple_car_gen.sh#L6)):*
> ```Shell
> # SimpleCar.
> 
> me=$(readlink -f $0)
> ```

BTW All of these should be double-quoted `"$0"`, etc., I think (sorry!).

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJB_8TCoJxtXHg9on:-KTLJB_8TCoJxtXHg9oo:b-xfuvcc) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L5)):*
> ```Shell
> # Generates the source files for the PendulumStateVector.
> 
> me=$(readlink -f $0)
> ```

BTW All of these should be double-quoted `"$0"`, etc., I think.

---

*[drake/tools/lcm_vector_gen.py, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHa5oZjOnSW7f7u1V:-KTLHa5oZjOnSW7f7u1W:bhacaub) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L293)):*
> ```Python
>     drake_dist_dir = subprocess.check_output(
>         "git rev-parse --show-toplevel".split()).strip()
>     relative_cxx_dir = cxx_dir.replace(os.path.join(drake_dist_dir, ''), '')
> ```

I can't figure out what `os.path.join(drake_dist_dir, '')` is accomplishing above and beyond what a plain `drake_dist_dir` would do?

---

*[drake/tools/lcm_vector_gen.py, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHGSS17iVFi-dL13g:-KTLHGSTg9pJwJZ5_lCM:bf3xgld) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L372)):*
> ```Python
>         '--cxx-dir', help="output directory for cxx files", default=".")
>     parser.add_argument(
>         '--namespace', help="comma-delimited enclosing namespace",
> ```

BTW Perhaps `::`-delimited lists would be a more obvious mnemonic for users?

---

*[drake/tools/lcm_vector_gen.sh, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLISa-wi4iOxcSTZBn:-KTLISa-wi4iOxcSTZBo:b-v2x8zi) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.sh#L8)):*
> ```Shell
> # translators between the two.
> 
> # Requires that the variables drake, mydir, and namespace are already defined.
> ```

BTW Fail-fast if they are not?

---

*[drake/tools/lcm_vector_gen.sh, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJ0CMSpMQq6-HnwYn:-KTLJ0CNFKoJ4iLxtnBA:b-azxq1t) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.sh#L32)):*
> ```Shell
>         --namespace="$namespace" \
>         --title="$title" "$@"
>     $CLANG_FORMAT --style=file -i $mydir/gen/$snake*.h $mydir/gen/$snake*.cc
> ```

BTW Missing quotes on `"$mydir"/gen/...`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by david-german-tri** [comment]
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/simple_car_gen.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJHPY0Aso6l2ayHqg:-KTLL-3VZPzPZRU9zGUX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/automotive/simple_car_gen.sh#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW All of these should be double-quoted `"$0"`, etc., I think (sorry!).
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJB_8TCoJxtXHg9on:-KTLL-m_mIzoD7DLeA6m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW All of these should be double-quoted `"$0"`, etc., I think.
</details>
Done.

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHE1LkXdBoCVaUeWs:-KTLIFi776IqH95u0jju:bayheti) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L14)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Until the System1 Pendulum.h gets removed, there's another class PendulumState in there...  I am hoping to remove it in the near-ish future, but for now I worry this could be a confusing duplication.
</details>
Sadness.  Done.

---

*[drake/tools/lcm_vector_gen.py, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHa5oZjOnSW7f7u1V:-KTLL46pwsL77sZih9B2:b-eakgnt) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L293)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I can't figure out what `os.path.join(drake_dist_dir, '')` is accomplishing above and beyond what a plain `drake_dist_dir` would do?
</details>
Drops the leading `/`.

---

*[drake/tools/lcm_vector_gen.py, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHXnSLNVKXawXKpQ6:-KTLIAfAOfs4-Kriv-uq:b-du1e7d) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L325)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW no objection to this print, just making sure it's deliberate and not a leftover debug print.
</details>
Yep, I intended to leave it in.

---

*[drake/tools/lcm_vector_gen.py, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHGSS17iVFi-dL13g:-KTLKh5OXx5_LXvy7PMy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L372)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Perhaps `::`-delimited lists would be a more obvious mnemonic for users?
</details>
Done.

---

*[drake/tools/lcm_vector_gen.sh, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLISa-wi4iOxcSTZBn:-KTLLy1KpO-vOhB9QqdA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.sh#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Fail-fast if they are not?
</details>
Done.

---

*[drake/tools/lcm_vector_gen.sh, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJ0CMSpMQq6-HnwYn:-KTLKoaozLQTs2TEWuuo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.sh#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Missing quotes on `"$mydir"/gen/...`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by sammy-tri** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHE1LkXdBoCVaUeWs:-KTLM6hVhp0xC8plp9K4:b31dnlz) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Sadness.  Done.
</details>
BTW, You could even TODO it and I could fix it later.  Or not.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-:-KTLMHMbAo8dU0_2H5a3:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/tools/lcm_vector_gen.py, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHa5oZjOnSW7f7u1V:-KTLMYum4l_NuLncbWsl:bbosjt5) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L293)):*
?
```
>>> os.path.join('/home/jwnimmer', '')
'/home/jwnimmer/'
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by jwnimmer-tri** [comment]
*[drake/tools/lcm_vector_gen.py, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHa5oZjOnSW7f7u1V:-KTLMlfJ7Aj2Hm94Rdnx:baxqosk) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L293)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> ?
> ```
> >>> os.path.join('/home/jwnimmer', '')
> '/home/jwnimmer/'
> ```
</details>
Ah.  It adds a trailing slash, so that the replace removes it.  Tricky, but okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by david-german-tri** [comment]
Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---

*[drake/tools/lcm_vector_gen.py, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLHa5oZjOnSW7f7u1V:-KTLNJDpXCQQDqRRaWbH:b-lrd0md) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/tools/lcm_vector_gen.py#L293)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Ah.  It adds a trailing slash, so that the replace removes it.  Tricky, but okay.
</details>
I cribbed it from a few lines below.  ¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-:-KTLNOtlOpNZY9OK8Y0x:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/examples/Pendulum/pendulum_gen.sh, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3690#-KTLJB_8TCoJxtXHg9on:-KTLUBmAWxNMoZkSTAMp:b-ps2gbl) ([raw file](https://github.com/robotlocomotion/drake/blob/0bd641598e0415f4b9f6cebb07fc5bb609950153/drake/examples/Pendulum/pendulum_gen.sh#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
fwiw, i don't think double-quoting results of a $() makes any difference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3690)*

**Pull request merged**
