### PR TITLE
Update LCM

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards https://github.com/RobotLocomotion/drake/issues/7253

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7266)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7266#-:-Kwa0OQTvJwnw75_6rZQ:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@EricCousineau-TRI for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7266#-:-Kwa2qh0uW8zbS-bCmD2:b-r34yat)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7266#-:-KwaTIJRmdqL-Y9uSV6B:bnfp4nl)*

**Pull request merged**
