### PR TITLE
Add BsplineWeights for MPM

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review please.
@amcastro-tri FYI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-:-ODiEWPy9gLd3CdQMUlL:bg5zvlr)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few requests for more comments

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-:-ODmdJJ91AOxNiXNbLr7:b-y5iti0)* status: 8 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/mpm/test/bspline_test.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmc6uM4YVbs4e3BR7h:-ODmc6uM4YVbs4e3BR7i:bkif4zv) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/test/bspline_test.cc#L21)):*
> ```cpp
> 
> /* BsplineWeights should create a partition of unity; i.e. All weights should
>  sum up to 1.0. */
> ```

minor: that's cool but this is the first mention of this fact -- I didn't realize from the BsplineWeights class documentation that the weights would sum to 1. That should be claimed in the class docs so the test here is verifying an expected property.
___
*[`multibody/mpm/bspline.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlk3lB9KSsl3eLe94h:-ODlk3lB9KSsl3eLe94i:bi6bcfh) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L19)):*
> ```objc
> template <typename T>
> int ComputeBaseNode(const T& x) {
>   return static_cast<int>(std::floor(x + static_cast<T>(0.5)));
> ```

BTW could you use [`std::round()`](https://en.cppreference.com/w/cpp/numeric/math/round) instead? There is a subtle difference for negative values of x exactly halfway between integers (round away from zero vs round up). Does that matter here? If so consider explaining why `std::round()` is no good here.
___
*[`multibody/mpm/bspline.h` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlmktn4cQzfwgdczwZ:-ODlmktn4cQzfwgdczw_:b-k0di1s) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L40)):*
> ```objc
>            0.5 * (1.5 - |d|)²,  if 0.5 < |d| <= 1.5
> 
>  where d is the distance between the point and the grid node in the reference
> ```

d appears to be unitless. Is it scaled by dx? Also it's apparently signed so isn't just a distance. Please clarify.
___
*[`multibody/mpm/bspline.h` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODllpXXE0Ys8kHsarz9:-ODllpXXE0Ys8kHsarzA:bkeo2mq) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L41)):*
> ```objc
> 
>  where d is the distance between the point and the grid node in the reference
>  frame. The kernel is non-zero in the interval [-1.5, 1.5] (in reference frame).
> ```

nit: it's zero when |d|=1.5



_Suggestion:_
```objc
(-1.5, 1.5)
```
___
*[`multibody/mpm/bspline.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlouspAYgOR2A3f_56:-ODlouspAYgOR2A3f_57:blcs374) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L57)):*
> ```objc
>    dx (meter). */
>   BsplineWeights(const Vector3<T>& x, const T& dx) {
>     const Vector3<T> x_reference = x / dx;
> ```

BTW is this what you called d above?
___
*[`multibody/mpm/bspline.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlpAOZ-SbzZ4qfrRD9:-ODlpAOZ-SbzZ4qfrRDA:b-gfidqj) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L61)):*
> ```objc
>     Compute(x_reference[0], base_node[0], &data_[0]);
>     Compute(x_reference[1], base_node[1], &data_[1]);
>     Compute(x_reference[2], base_node[2], &data_[2]);
> ```

BTW `Compute()` seems too generic, especially next to `ComputeBaseNode()`. Consider `ComputeWeight()`.
___
*[`multibody/mpm/bspline.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlpYZnD3wg2sbFxZ5M:-ODlpYZnD3wg2sbFxZ5N:b-87iouw) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L64)):*
> ```objc
>   }
> 
>   /* Returns between the point and the ijk-th grid node in its support.
> ```

typo: Returns between -> Returns weight between
___
*[`multibody/mpm/bspline.h` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmTJUj0lgHKL9Th_JJ:-ODmTJUj0lgHKL9Th_JK:b-ftd236) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L76)):*
> ```objc
>    @param[out] result      the weights between the point and the three grid
>                            nodes in its support in a single dimension. */
>   void Compute(const T& x_reference, int base_node, Vector3<T>* result) const {
> ```

minor: per f2f this needs a little algebra in the comments to relate this optimized code to the beautiful N(d) function documented above. The code computes three d values. d0 is one of them (with |d0| <= .5) but d1 and d2 in the code are offset from the actual d values. I found it confusing that they were called "d". The actual |d| values (I think) would be d₋₁=1+d₀ and d₊₁=1−d₀ (swapping places if d₀ < 0)

I checked the arithmetic with those substitutions for the d's and it looks good! Just needs some explaining. I presume you are taking advantage of the fact that it doesn't matter whether the result is ordered from left to right or right to left so that you don't have to calculate absolute values -- should mention that too.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the quick review! Comments addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-:-ODmsWl-5ohAWeEgIjlh:b45whdu)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/mpm/bspline.h` line 19 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlk3lB9KSsl3eLe94h:-ODmnkPw70PRHV7HMGRI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could you use [`std::round()`](https://en.cppreference.com/w/cpp/numeric/math/round) instead? There is a subtle difference for negative values of x exactly halfway between integers (round away from zero vs round up). Does that matter here? If so consider explaining why `std::round()` is no good here.
</blockquote></details>

Done.
___
*[`multibody/mpm/bspline.h` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlmktn4cQzfwgdczwZ:-ODmoAIu9csZRexbVebv:b-vpvlmc) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

d appears to be unitless. Is it scaled by dx? Also it's apparently signed so isn't just a distance. Please clarify.
</blockquote></details>

I made an attempt. PTAL and see if it's better.
___
*[`multibody/mpm/bspline.h` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODllpXXE0Ys8kHsarz9:-ODmoFmf0g1j0m8JKiil:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: it's zero when |d|=1.5
</blockquote></details>

Done
___
*[`multibody/mpm/bspline.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlouspAYgOR2A3f_56:-ODmpEgi1gUT9ybPQeLF:b-vhxd8g) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this what you called d above?
</blockquote></details>

No, I added a comment to clarify.
___
*[`multibody/mpm/bspline.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlpAOZ-SbzZ4qfrRD9:-ODmp_fC3fnPf4CfZzpj:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `Compute()` seems too generic, especially next to `ComputeBaseNode()`. Consider `ComputeWeight()`.
</blockquote></details>

Done
___
*[`multibody/mpm/bspline.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODlpYZnD3wg2sbFxZ5M:-ODmpfpw5oyC-32Vhcns:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: Returns between -> Returns weight between
</blockquote></details>

Done
___
*[`multibody/mpm/bspline.h` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmTJUj0lgHKL9Th_JJ:-ODmqk9fA70yZGj9TE_u:bx9unft) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/bspline.h#L76)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: per f2f this needs a little algebra in the comments to relate this optimized code to the beautiful N(d) function documented above. The code computes three d values. d0 is one of them (with |d0| <= .5) but d1 and d2 in the code are offset from the actual d values. I found it confusing that they were called "d". The actual |d| values (I think) would be d₋₁=1+d₀ and d₊₁=1−d₀ (swapping places if d₀ < 0)

I checked the arithmetic with those substitutions for the d's and it looks good! Just needs some explaining. I presume you are taking advantage of the fact that it doesn't matter whether the result is ordered from left to right or right to left so that you don't have to calculate absolute values -- should mention that too.
</blockquote></details>

I made some clarifying comments and redfined d to be more intuitive.
___
*[`multibody/mpm/test/bspline_test.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmc6uM4YVbs4e3BR7h:-ODmsRnrBtMjsBHPh3vm:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a1ad6684c9b1275b729089fd8bb01ce4437543b5/multibody/mpm/test/bspline_test.cc#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: that's cool but this is the first mention of this fact -- I didn't realize from the BsplineWeights class documentation that the weights would sum to 1. That should be claimed in the class docs so the test here is verifying an expected property.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/mpm/bspline.h` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmuuvA3Bav62kRQBNw:-ODmuuvA3Bav62kRQBNx:bntu3gy) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f706bfa56ef67fae829adb364c8b33cd0690d2c/multibody/mpm/bspline.h#L43)):*
BTW it's still not obvious to me that being in the point's reference frame means that d has units of grid spacing. Maybe that's a convention defined elsewhere? Consider something more specific about it here, something like
> where d is the signed offset from a nearby grid point, in units of the grid spacing dx.
___
*[`multibody/mpm/bspline.h` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmw8Vl2prx-uUVQDbv:-ODmw8Vl2prx-uUVQDbw:ba7weuu) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f706bfa56ef67fae829adb364c8b33cd0690d2c/multibody/mpm/bspline.h#L93)):*
> ```objc
>     /* 1+d is the _distance_ between the right most grid node and point x. */
>     const T d2 = static_cast<T>(0.5) - d;          // d2 = 1.5 - (1 + d).
>     (*result)(2) = static_cast<T>(0.5) * d2 * d2;  // using eq(2).
> ```

BTW awesome! These comments are great, thanks. One quibble: d can be positive or negative. Right and left as used above switch places when d is negative. I'd suggest leaving these comments as-is but add one noting that right and left swap when d < 0, and that it doesn't matter!

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review on Thursday per rotation please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-:-ODn1GWyD8sc_nzCroWe:b-b01ib5)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`multibody/mpm/bspline.h` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmuuvA3Bav62kRQBNw:-ODn0_NKEiFxv_LuFQ57:b-dtkds3) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f706bfa56ef67fae829adb364c8b33cd0690d2c/multibody/mpm/bspline.h#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it's still not obvious to me that being in the point's reference frame means that d has units of grid spacing. Maybe that's a convention defined elsewhere? Consider something more specific about it here, something like
> where d is the signed offset from a nearby grid point, in units of the grid spacing dx.
</blockquote></details>

Done, thanks!
___
*[`multibody/mpm/bspline.h` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODmw8Vl2prx-uUVQDbv:-ODn0dRvDci_JEkVLxkP:b-cvprzg) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f706bfa56ef67fae829adb364c8b33cd0690d2c/multibody/mpm/bspline.h#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW awesome! These comments are great, thanks. One quibble: d can be positive or negative. Right and left as used above switch places when d is negative. I'd suggest leaving these comments as-is but add one noting that right and left swap when d < 0, and that it doesn't matter!
</blockquote></details>

Per f2f, there's no left/right swapping -- 1-d always gives the distance between the left grid node and point x, and 1+d always gives the distance between the right grid node and point x.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-:-ODrDJB10qAMx51IZMwt:bnfp4nl)* status: 3 unresolved discussions

___
*[`multibody/mpm/bspline.h` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODrATYU9IEd8Qau8YkD:-ODrATYU9IEd8Qau8YkE:b-fxjlnn) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/bspline.h#L52)):*
> ```objc
>  @tparam T Scalar type; can be double or float. */
> template <typename T>
> class BsplineWeights {
> ```

Are there more bspline-related classes on their way to be added into this file?  If not, then the filename should match the classname -- `bspline_weights.h`.

(I checked the (very old?) WIP PR and didn't see any more bspline things pending.)
___
*[`multibody/mpm/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODr6WtK7JMATJtkoAaa:-ODr6WtK7JMATJtkoAab:bdonmgv) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/BUILD.bazel#L10)):*
> ```Starlark
> )
> 
> package(default_visibility = ["//visibility:public"])
> ```

BTW Since this package is public, we should should have a `drake_cc_package_library` stanza in this file at some point soon.
___
*[`multibody/mpm/test/bspline_test.cc` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODrCtoyCZ67GIBsdrNA:-ODrCtoyCZ67GIBsdrNB:b-bafvry) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/test/bspline_test.cc#L22)):*
> ```cpp
> /* BsplineWeights should create a partition of unity; i.e. All weights should
>  sum up to 1.0. */
> TYPED_TEST(BsplineWeightsTest, PartitionOfUnity) {
> ```

BTW For my taste, I would have done `using T = TypeParam;` so that these test bodies matched what the header file looks like.  (Maybe that has some compilation shadowing problem though?)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[`multibody/mpm/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODr6WtK7JMATJtkoAaa:-ODrVCkK50xrRpg626fc:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/BUILD.bazel#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Since this package is public, we should should have a `drake_cc_package_library` stanza in this file at some point soon.
</blockquote></details>

Done
___
*[`multibody/mpm/bspline.h` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODrATYU9IEd8Qau8YkD:-ODrU44Z50F5-FnXRa6E:b-3y7gnl) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/bspline.h#L52)):*
Done

> Are there more bspline-related classes on their way to be added into this file? 
No.
___
*[`multibody/mpm/test/bspline_test.cc` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22289#-ODrCtoyCZ67GIBsdrNA:-ODrUO5G1LXpofUxSLgl:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/f55969ea3dd5cd466fb9c7d887fe33f49ec53ef9/multibody/mpm/test/bspline_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For my taste, I would have done `using T = TypeParam;` so that these test bodies matched what the header file looks like.  (Maybe that has some compilation shadowing problem though?)
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22289)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Pull request merged**
