### PR TITLE
File naming conventions compliance in drake/solvers

### PR DESCRIPTION
**Pull request by ggould-tri**
`drake/solvers` was one of our major reservoirs of noncompliant file naming. This PR stomps on it, correcting the naming of every non-mex cpp file in the solvers directory and its test subdirectory (but not its other subdirs).

This PR is very large, but all of the changes were done by script.  Once it passes CI it is likely correct, so review should focus on whether it was a good idea in the first place.

Marking do-not-review until CI passes, as this has major configuration-specific changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3010)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@liangfok feature
+@sherm1 platform

Last big automated move/rename PR for at least the next month, I promise!

---

Review status: 0 of 51 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-:-KO5cj2hJvxwDllYIrN3:1340439389)*

**Comment by liangfok** [comment]
:lgtm: Just one question.

---

Reviewed 78 of 78 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mosek_solver.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO5f9ZOp5s2Aw0tq_1a:-KO5f9ZOp5s2Aw0tq_1b:640312318) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/drake/solvers/mosek_solver.h#L1)):*
> ```objc
> // Copyright 2016, Alex Dunyak
> ```

BTW. I just noticed that these `Mosek` files are copyrighted by Alex Dunyak. Are we sure it's OK to modify them? Should changing the files result in any change in the copyright notice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-:-KO5fYXzqpsl_3tx_kEV:169546089)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mosek_solver.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO5f9ZOp5s2Aw0tq_1a:-KO5k5_q3wE-fh3DuTzP:-486510577) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/drake/solvers/mosek_solver.h#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I believe that with the `LICENSE.txt` we have, the copyright header is functionally irrelevant.  But it certainly is inconsistent.
> 
> This is not an issue for this PR, but I will put header rectification on my to-do list.
</details>
SGTM!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010)*

**Comment by sherm1** [comment]
Platform review: yes, good idea; CI worked; one minor change needed and a few BTWs for your consideration. :lgtm:

---

Reviewed 78 of 78 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO6I5UjOrxaIpRwbAj9:-KO6I5UjOrxaIpRwbAjA:-1094056546) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/CHANGELOG.md#L48)):*
> ```Markdown
>  - [#2779][] Move some rotation functions from drakeGeometryUtil to drake/math.
>  - [#2963][] Rename RigidBody::CollisionElement to RigidBodyCollisionElement.
>  - [#3010][] All header file names under `solvers` are now spelled with lower case and underscore names.
> ```

You have to add the actual URL at the bottom of this file.

---

*[CHANGELOG.md, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO6IlFBehI_-n4TFknh:-KO6IlFBehI_-n4TFkni:-1737620788) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/CHANGELOG.md#L49)):*
> ```Markdown
>  - [#2963][] Rename RigidBody::CollisionElement to RigidBodyCollisionElement.
>  - [#3010][] All header file names under `solvers` are now spelled with lower case and underscore names.
> ```

BTW, the ordering within the changelog seems random. I think it was reverse-chronological for a while but then a few changes got tacked on to the end. I suggest moving yours and the other late-bloomers to the top.

---

*[drake/solvers/mosek_solver.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO5f9ZOp5s2Aw0tq_1a:-KO6JkP2yb0rtzVH9IkW:-226877706) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/drake/solvers/mosek_solver.h#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> SGTM!
</details>
BTW, since the code doesn't refer to the LICENSE.txt file, this is currently saying the code is non-open source and can only be used with Alex's permission. We should ask him to agree to license under Drake's terms or remove the code from Drake.

---

*[drake/solvers/qp.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO6KbiH9R-ss2CaXuVf:-KO6KbiH9R-ss2CaXuVg:1801560449) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/drake/solvers/qp.cc#L1)):*
> ```cpp
> #include <math.h>
> ```

BTW, should be `<cmath>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-:-KO6LFJgccROGlo6IteU:-865820031)*

**Comment by ggould-tri** [comment]
Review status: 43 of 51 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO6I5UjOrxaIpRwbAj9:-KO6Nr0PTeFtoJ4o0QjE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/CHANGELOG.md#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> You have to add the actual URL at the bottom of this file.
</details>
Done.

---

*[CHANGELOG.md, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO6IlFBehI_-n4TFknh:-KO6NrriqTIz_l8ADkVF:1713340829) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/CHANGELOG.md#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, the ordering within the changelog seems random. I think it was reverse-chronological for a while but then a few changes got tacked on to the end. I suggest moving yours and the other late-bloomers to the top.
</details>
Moved mine and one other I know to be recent (because I reviewed it).

---

*[drake/solvers/mosek_solver.h, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-KO5f9ZOp5s2Aw0tq_1a:-KO6O31qU6z2mi5FcHWy:833317210) ([raw file](https://github.com/robotlocomotion/drake/blob/17f636ae843a7c19c618b389084cf52741c0d63f/drake/solvers/mosek_solver.h#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, since the code doesn't refer to the LICENSE.txt file, this is currently saying the code is non-open source and can only be used with Alex's permission. We should ask him to agree to license under Drake's terms or remove the code from Drake.
</details>
I am relaying this to Russ, as Alex is one of his.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010)*

**Comment by sherm1** [comment]
:lgtm: -- all good.

---

Reviewed 3 of 78 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-:-KO6kVHWRSz9yQs6m3uX:-628726207)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 4 of 78 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3010#-:-KO6p3DPbv_F50MxCqtk:1417088721)*

**Pull request merged**
