### PR TITLE
doc: Add in novel Drake images for newer website

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14657

\cc @BetsyMcPhail @jwnimmer-tri 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@iantheengineer for both reviews, please!
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613#-:-MSUcEX33rd5Kpq4vKM8:bfzugox)* status: LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned (waiting on @IanTheEngineer)

**Comment by jwnimmer-tri** [comment]
FYI @IanTheEngineer isn't officially a platform reviewer, yet.  You'll want to tag the on-call platform reviewer once it's through feature.

**Review by EricCousineau-TRI — COMMENTED** [review]
Ah, gotcha!
-(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613#-:-MSUdotGBVGqiDwaWdlD:b-yl1in2)* status: LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Things look good overall. Just a few small nits and questions

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613#-:-MSclXH39a2MdrYtxYY3:bt234q3)* status: 2 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[doc/images/drake-dragon.svg, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MScl0XZ9fVEga6FZg1R:-MScl0X_4xPA0toFz3E8:b-adk6pu) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.svg#L2)):*
> ```SVG
> <?xml version="1.0" encoding="utf-8"?>
> 
> ```

Nit: Do we care that this was exported from Illustrator? I imagine that doesn't impact the license, but it's worth noting, I suppose.
___
*[doc/images/drake-dragon.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MScjL-f5BoxqVbkvw3v:-MScjL-f5BoxqVbkvw3w:b4en7bc) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L3)):*
> ```Markdown
> This SVG does not render well in Firefox (nor in Inkscape), so we rasterize it.
> 
> Steps used to generate the accompanying PNG:
> ```

FYI: I followed these steps after removing the PNG, and the output looked correct. Even better: git can't tell that I ever removed the initial image.

Ditto for the favicon :thumbsup: 
___
*[doc/images/drake-dragon.README.md, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MSckX6Y0QawyBkpFHat:-MSckX6Y0QawyBkpFHau:b-pv3qo8) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L23)):*
> ```Markdown
> 
>

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

___
*[doc/images/drake-dragon.svg, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MScl0XZ9fVEga6FZg1R:-MScmJB22F1I7OLjmHRh:b-ulpsqh) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.svg#L2)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: Do we care that this was exported from Illustrator? I imagine that doesn't impact the license, but it's worth noting, I suppose.
</blockquote></details>

OK I don't think so, at least not yet. Licensing won't be an issue (generated from tool). On the technical side, we may not have access to all the bells and whistles that illustrator had, and there is the SVG rendering issues on Firefox etc., but we can always address those in a better form in the future.

(Per the contract, I don't believe we made stipulations on "editability" of these artifacts, so I think this was sufficient bang-for-buck.)
___
*[doc/images/drake-dragon.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MScjL-f5BoxqVbkvw3v:-MScmDNp8uZ09rMz50eW:bhzrt4d) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

FYI: I followed these steps after removing the PNG, and the output looked correct. Even better: git can't tell that I ever removed the initial image.

Ditto for the favicon :thumbsup: 
</blockquote></details>

OK Sweet! Yeah, that's what the `-strip` step was for!
___
*[doc/images/drake-dragon.README.md, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MSckX6Y0QawyBkpFHat:-MScm5TB8WnRiZzmPpN2:boxkazt) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L23)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Do you want these informational comments to be committed, or were they just for your debugging?
</blockquote></details>

OK Yup, I would like them to remain, as I would hate for someone to waste their time duplicating my attempts.

I can hoist them outside of the comment if you like.

**Review by IanTheEngineer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[doc/images/drake-dragon.README.md, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MSckX6Y0QawyBkpFHat:-MScpwSU4KxT2ZgUA87l:bappf0z) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup, I would like them to remain, as I would hate for someone to waste their time duplicating my attempts.

I can hoist them outside of the comment if you like.
</blockquote></details>

I think hoisting them to normal text makes sense as a "Note", particularly as your intent is to avoid duplicate work. Otherwise, it'll be easy to miss these comments when viewing in rendered form only.

**Comment by jamiesnape** [comment]
If we are not careful `drake-dragon.README.md` will be converted to HTML by Jekyll (need to make sure it is not in the Bazel source code list, under normal circumstances it would definitely be converted.

**Comment by EricCousineau-TRI** [comment]
Yuppers. I will most likely be doing the glue work, so I'll address it then if it becomes a problem. (in the WIP integ branch for #14610), I haven't seen it crop up yet.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

___
*[doc/images/drake-dragon.README.md, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14613#-MSckX6Y0QawyBkpFHat:-MTkW2rF-KAMFZ64oQ1u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55ab822976144e301a68b5ad4cb190727aebd95e/doc/images/drake-dragon.README.md#L23)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

I think hoisting them to normal text makes sense as a "Note", particularly as your intent is to avoid duplicate work. Otherwise, it'll be easy to miss these comments when viewing in rendered form only.
</blockquote></details>

Done.

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: Thanks for the updates. +@jwnimmer-tri for Platform Review tomorrow please.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613#-:-MTmHmkS9rNI-7ovZ5qT:byo3z45)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

Beauty is truth.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14613#-:-MTmKaD73bd1xWGnZXCH:bj541lt)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),IanTheEngineer

**Comment by EricCousineau-TRI** [comment]
Hm... these two are 404...
image
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-experimental-leak-sanitizer/12952/
https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-experimental-debug/6918/

@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Do you need debug builds? We are having webdav server issues at the moment.

**Comment by EricCousineau-TRI** [comment]
Nah, was initially concerned that it implied a breakage. But I'm cool with non-debug.

**Comment by jamiesnape** [comment]
We may as well wait until the release builds pass again, since they will be quick, and then force it in. There is nothing here that would depend on the type of job.

**Comment by jamiesnape** [comment]
HTTP 404 is almost always an infrastructure issue, though many years ago a very verbose PR did almost kill Jenkins.

**Comment by EricCousineau-TRI** [comment]
Skipping slower builds

**Pull request merged**
