### PR TITLE
set unrecognized elements to warning

### PR DESCRIPTION
**Pull request by marcoag**
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

After this changes it should start printing warnings for unrecognized elements as required in https://github.com/RobotLocomotion/drake/issues/15018.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@ericcousineau-tri for feature review or delegation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MdyMQSkEaAKDTtUoLjI:b-kjvxjf)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks good for implementation, but can we make the testing active?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MeSR2fN39dhc71VM7BX:b-jvv1d0)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 531 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSQLjyCabTjzIBCNEq:-MeSQLjyCabTjzIBCNEr:b-3lle7m) ([raw file](https://github.com/robotlocomotion/drake/blob/7f0c396729af4941fd9f4f3ccc307805ac14cbc0/multibody/parsing/detail_sdf_parser.cc#L531)):*
> ```cpp
>   // TODO(#15018): Later, we should change unrecognized elements policy to
>   // become an error.
>   DRAKE_DEMAND(
> ```

Is it possible to test this using SDFormat's warning console redirection?

e.g.
https://github.com/ignitionrobotics/sdformat/blob/4e9f2eb3244e1c218f9fe31284ecf92a93379bff/test/integration/deprecated_specs.cc#L69-L102

\cc @azeey

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 531 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSQLjyCabTjzIBCNEq:-MeSRKqO86F2OB_KBaPk:b4thw0l) ([raw file](https://github.com/robotlocomotion/drake/blob/7f0c396729af4941fd9f4f3ccc307805ac14cbc0/multibody/parsing/detail_sdf_parser.cc#L531)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it possible to test this using SDFormat's warning console redirection?

e.g.
https://github.com/ignitionrobotics/sdformat/blob/4e9f2eb3244e1c218f9fe31284ecf92a93379bff/test/integration/deprecated_specs.cc#L69-L102

\cc @azeey 
</blockquote></details>

Possible implementation (inlining `RedirectConsoleStream`)
```
std::stringstream buffer;
Console::ConsoleStream old_stream = Console::Instance()->GetMsgStream();
ScopeExit revert_stream([&old_stream]() { Console::Instance()->GetMsgStream() = old_stream; });
Console::Instance()->GetMsgStream() = ConsoleStream(buffer);
...
```

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSSm_-1iQxB5FbZz18:-MeSSm_-1iQxB5FbZz19:b-w40tnm) (no related file):*
nit When next editing the commit message (either when rebasing, or when squash-merging), please remove the "Signed-off-by" line from the commit message body.  Drake neither requires nor infers any meaning from those kinds of lines, so they only serve to pollute the commit logs.

---

**Review by marcoag — COMMENTED** [review]
Just added tests for warnings for deprecated and unrecognized elements.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MeiuVxH6GhgTvzdoPw9:bzii0ax)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @marcoag)

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey, @EricCousineau-TRI, and @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 531 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSQLjyCabTjzIBCNEq:-MeiuzMCDbAaI7K5O3O-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7f0c396729af4941fd9f4f3ccc307805ac14cbc0/multibody/parsing/detail_sdf_parser.cc#L531)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Possible implementation (inlining `RedirectConsoleStream`)
```
std::stringstream buffer;
Console::ConsoleStream old_stream = Console::Instance()->GetMsgStream();
ScopeExit revert_stream([&old_stream]() { Console::Instance()->GetMsgStream() = old_stream; });
Console::Instance()->GetMsgStream() = ConsoleStream(buffer);
...
```
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey, @EricCousineau-TRI, and @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 531 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MekmNqNCct8wyvIuwbN:-MekmNqOA-RstsfjMILa:b-vahusf) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/detail_sdf_parser.cc#L531)):*
> ```cpp
>   // TODO(#15018): Later, we should change unrecognized elements policy to
>   // become an error.
>   DRAKE_DEMAND(
> ```

nit When the unrecognized elements policy was implicit in the default `parser_config` (i.e., before this PR added the explicit setting in L524 ), then this `DRAKE_DEMAND` made sense, as a reinforcement of what the implicit default was.  Now that we're setting the policy directly, checking the setting with an assertion seems like overkill.

I think we should remove this statement (but keep the TODO comment, and the new unit test).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey and @marcoag)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeknSPg8U2V4_dMzbP1:-MeknSPhCdVpsAAze0DL:b3a4sx2) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/test/detail_sdf_parser_test.cc#L1142)):*
> ```cpp
>   EXPECT_TRUE(std::regex_match(buffer.str(), std::regex(
>     R"([\s\S]*Warning[\s\S]*XML Element\[bad_element\], child of )"
>     R"(element\[model\], not defined in SDF[\s\S]*)")));
> ```

FYI The report from a failed regex test will be _much_ better if you use `MatchesRegex`.

https://github.com/google/googletest/blob/master/docs/advanced.md#more-string-assertions

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey, @EricCousineau-TRI, @jwnimmer-tri, and @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 531 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MekmNqNCct8wyvIuwbN:-MeoDGRYCMh-7wUoqO9W:bvkz3se) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/detail_sdf_parser.cc#L531)):*
> DRAKE_DEMAND
Agree, remove the `DRAKE_DEMAND` and moved the TODO comment next to the relevant policy setting line.
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeknSPg8U2V4_dMzbP1:-MeoBSTh2xrtwednEQr5:bgkhg0g) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/test/detail_sdf_parser_test.cc#L1142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The report from a failed regex test will be _much_ better if you use `MatchesRegex`.

https://github.com/google/googletest/blob/master/docs/advanced.md#more-string-assertions
</blockquote></details>

In fact I was using that one initially but then I saw that `std::regex` was the one used by `DRAKE_EXPECT_THROWS_MESSAGE` so I switched for consistency. I can easy switch back if it seems better.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, thanks!
+@seancurtis-tri for platform review, please!

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MfVkiM96GU4QJJUXJM0:b-vc73hk)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @marcoag, and @SeanCurtis-TRI)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeknSPg8U2V4_dMzbP1:-MfVkYLkD06P_vuev8RC:bnbrs4k) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/test/detail_sdf_parser_test.cc#L1142)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

In fact I was using that one initially but then I saw that `std::regex` was the one used by `DRAKE_EXPECT_THROWS_MESSAGE` so I switched for consistency. I can easy switch back if it seems better.
</blockquote></details>

Aye, if you can switch back, that'd be good! (debugging failures like this can be a bit cumbersome)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Quick pass done -- one question and waiting to go back to `MatchesRegex` as per reviewer comments.

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MfYDsDB6_IfO4WnC8iW:b-z5gk4i)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 526 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MfYD94J4PvkNrfrmKNn:-MfYD94J4PvkNrfrmKNo:bvkqb5h) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee5968f22bbe9cd569e41f7633d71b570c4720e/multibody/parsing/detail_sdf_parser.cc#L526)):*
> ```cpp
>   // TODO(#15018): Later, we should change unrecognized elements policy to
>   // become an error.
>   parser_config.SetUnrecognizedElementsPolicy(sdf::EnforcementPolicy::WARN);
> ```

For my own edification -- does this mean we'll get a warning to the console for every custom drake tag?
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 1142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeknSPg8U2V4_dMzbP1:-MfYDb_p3F2KfG7FqjX9:b-u6s1m7) ([raw file](https://github.com/robotlocomotion/drake/blob/6f70d77f30f41bdfbc7dbd67d0fbaff87978bf7e/multibody/parsing/test/detail_sdf_parser_test.cc#L1142)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Aye, if you can switch back, that'd be good! (debugging failures like this can be a bit cumbersome)
</blockquote></details>

Thirded (It's "seconded" for those of us late to the party.)

**Review by marcoag — COMMENTED** [review]
> MatchesRegex

switched as requested.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MgBG40FAlOya7a1Sy-B:b-cp5c4)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @marcoag, and @SeanCurtis-TRI)

___
*[multibody/parsing/detail_sdf_parser.cc, line 526 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MfYD94J4PvkNrfrmKNn:-MgAWdlIBCGqTC7zAoQG:b-7f380v) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee5968f22bbe9cd569e41f7633d71b570c4720e/multibody/parsing/detail_sdf_parser.cc#L526)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

For my own edification -- does this mean we'll get a warning to the console for every custom drake tag?
</blockquote></details>

As per changes in https://github.com/ignitionrobotics/sdformat/pull/402 custom elements don't get any warnings from sdformat. To make sure I tested it myself and it doesn't seem to throw any.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MgBLYY80OLnc_Muz3Wm:bmxilld)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

___
*[multibody/parsing/detail_sdf_parser.cc, line 526 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MfYD94J4PvkNrfrmKNn:-MgBLGWwAhOh5QCHg6bb:bky89do) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee5968f22bbe9cd569e41f7633d71b570c4720e/multibody/parsing/detail_sdf_parser.cc#L526)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

As per changes in https://github.com/ignitionrobotics/sdformat/pull/402 custom elements don't get any warnings from sdformat. To make sure I tested it myself and it doesn't seem to throw any.
</blockquote></details>

Ah...I see. An attribute with `:` in the string is not considered "unrecognized". Is that right?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317#-:-MgBQ8c0BNg1_rAgfgJY:bm9o57a)* status: 1 unresolved discussion (waiting on @marcoag)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSSm_-1iQxB5FbZz18:-MgBQK7W4gkz-kzWyaKJ:b-kjvqe7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When next editing the commit message (either when rebasing, or when squash-merging), please remove the "Signed-off-by" line from the commit message body.  Drake neither requires nor infers any meaning from those kinds of lines, so they only serve to pollute the commit logs.
</blockquote></details>

Oops. I can't squash until @marcoag has acknowledged this -- unless I dismiss @jwnimmer-tri from this discussion.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15317#-MeSSm_-1iQxB5FbZz18:-MgBQTf8-6f2qDu2iQkh:b-uh09iz) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oops. I can't squash until @marcoag has acknowledged this -- unless I dismiss @jwnimmer-tri from this discussion.
</blockquote></details>

Nope. Just needed *someone* to be satisfied.  :)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15317)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @marcoag)

**Comment by EricCousineau-TRI** [comment]
FYI I've updated the overview with release notes.

**Pull request merged**
