### PR TITLE
[geometry/optimization] actually remove the ipopt shortest path problem test.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15514)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15514#-:-MfjmrL2-Q_JLcc4WBic:bjhy3aw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
+@soonho-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15514#-:-MfjnVeGC4LWrc0JaN0o:b-v3eqt6)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15514#-:-MfjnYv-9VfbgEXCIN3p:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Pull request merged**
