### PR TITLE
Adds controllability and observability to linear systems

### PR DESCRIPTION
**Pull request by RussTedrake**
@hongkai-dai for feature review
@sammy-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4307)

### CODE REVIEW

**Comment by sherm1** [comment]
A few random comments below.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/linear_system.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXq5fTBuOGeGvlivbqL:-KXq5fTBuOGeGvlivbqM:b-pjkahl) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L124)):*
> ```cpp
> /// Returns true iff the controllability matrix is full row rank.
> bool IsControllable(const LinearSystem<double>& sys, double threshold) {
>   const auto& R = ControllabilityMatrix(sys);
> ```

BTW this shouldn't be a reference, just a local R.

---

*[drake/systems/framework/primitives/linear_system.cc, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXq5lg_JLdM-89Ab276:-KXq5lg_JLdM-89Ab277:b-pjkak6) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L144)):*
> ```cpp
> /// Returns true iff the observability matrix is full column rank.
> bool IsObservable(const LinearSystem<double>& sys, double threshold) {
>   const auto& O = ObservabilityMatrix(sys);
> ```

BTW this shouldn't be a reference, just a local O.

---

*[drake/systems/framework/primitives/test/linear_system_test.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXqBiSPp7nPwwNaYIKr:-KXqBiSPp7nPwwNaYIKs:blldh2f) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/test/linear_system_test.cc#L129)):*
> ```cpp
> }
> 
> // Test that linearizing an affine system returns the original A,B,C,D matrices.
> ```

BTW, comment needs updating (and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-:-KXqBzPjF40n2VbCzvSC:b-oif7t4)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/linear_system.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXq5fTBuOGeGvlivbqL:-KXqS_vyN2p5eS_j2Wpd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L124)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this shouldn't be a reference, just a local R.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/linear_system.cc, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXq5lg_JLdM-89Ab276:-KXqSavzRUFhEphhDQsJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this shouldn't be a reference, just a local O.
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/test/linear_system_test.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXqBiSPp7nPwwNaYIKr:-KXqSwSLebLwhH7SYLoN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/test/linear_system_test.cc#L129)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, comment needs updating (and below).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/primitives/linear_system.cc, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXqVn_E2OMxzRU8XeLA:-KXqVn_FndBMl0NRbOvj:bei260s) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L125)):*
> ```cpp
> bool IsControllable(const LinearSystem<double>& sys, double threshold) {
>   const auto& R = ControllabilityMatrix(sys);
>   Eigen::FullPivLU<Eigen::MatrixXd> lu_decomp(R);
> ```

According to Eigen https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html, `ColPivHouseholderQR` is faster than `FullPivLU`, and is as accurate as `FullPivLU`. It also has a `rank` function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-:-KXqAtYI36u7WydfQAi1:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/primitives/linear_system.cc, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-KXqVn_E2OMxzRU8XeLA:-KXqs3IbuKkLjRvkygzY:b-fhfgqn) ([raw file](https://github.com/robotlocomotion/drake/blob/4feaeb2da1c8df49afb2a631201005a05082cd41/drake/systems/framework/primitives/linear_system.cc#L125)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

According to Eigen https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html, `ColPivHouseholderQR` is faster than `FullPivLU`, and is as accurate as `FullPivLU`. It also has a `rank` function.
</blockquote></details>

good call.  i've made the switch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-:-KXsvNbQTiamoNkmVZDd:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4307#-:-KXupJ1xrtRvT93uo3eb:bnfp4nl)*

**Pull request merged**
