### PR TITLE
Adds FAQ entry explaining why drake-visualizer segfaults upon start on systems with VTK6.

### LINKED ISSUE #5280: drake-visualize segfaults on ubuntu 16.10 and 17.04
I have seen a QT linking issue in both 16.10 built with ninja and 17.04 built with make,
In both cases the system had vtk6 installed and vtk5 was checked out and built during the drake build process.

gdb crash output
```
Thread 1 "drake-visualize" received signal SIGSEGV, Segmentation fault.
0x00007fff6d2cd387 in QMetaObject::className() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

output from ldd drake-visualizer | grep libQt
```
	libQtGui.so.4 => /usr/lib/x86_64-linux-gnu/libQtGui.so.4 (0x00007fcfbf176000)
	libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007fcfbec82000)
	libQtOpenGL.so.4 => /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4 (0x00007fcfbe019000)
	libQtPropertyBrowser.so => /home/maiden/Projects/drake-distro/build/install/lib/libQtPropertyBrowser.so (0x00007fcfbdd26000)
	libQtWebKit.so.4 => /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4 (0x00007fcfb28af000)
	libQtSql.so.4 => /usr/lib/x86_64-linux-gnu/libQtSql.so.4 (0x00007fcfb266e000)
	libQtNetwork.so.4 => /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4 (0x00007fcfb2319000)
```

I have checked that "/usr/lib/x86_64-linux-gnu/libQtCore.so.4" actually exists so it should not link against libQt5Core as the ldd output states libQtCore.. strange

Building with debug and running gdb gives:

```
Starting program: /home/maiden/Projects/drake-distro/build/install/bin/drake-visualizer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd16c3700 (LWP 15067)]
[New Thread 0x7fffd0ec2700 (LWP 15068)]
[New Thread 0x7fffcbfff700 (LWP 15069)]
[New Thread 0x7fffbffff700 (LWP 15070)]
[New Thread 0x7fffbf7fe700 (LWP 15071)]
[Thread 0x7fffbffff700 (LWP 15070) exited]

Thread 1 "drake-visualize" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:294
294	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
```

drake on 16.10 is built from git commit: a814c2fabb2fffbb2f09eb97609472b40899c933
drake on 17.04 is built from git commit: d96b2c113b083a2a5bdb2848369eb142f47b0165

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5280.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5925)

### CODE REVIEW

**Comment by liangfok** [comment]
+@patmarion for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5925#-:-KiN9yjdmsHPXzlnKI1j:b-9qa6iu)*

**Comment by patmarion** [comment]
Seems fine to me if you want to update the docs to include this information.  It's possible that I have fixed this issue with this PR to director a few weeks back.  Not sure if drake has updated to director/master since then?

https://github.com/RobotLocomotion/director/pull/499

**Comment by liangfok** [comment]
Drake's master branch is currently pinned to https://github.com/RobotLocomotion/director/commit/aefc0632e648629a94fc9614567784fa9759113e, which does _not_ have RobotLocomotion/director#499. I manually updated my local clone of Drake to use Director's current master (https://github.com/RobotLocomotion/director/commit/cf6148643ffc3103668a523071a5822809e0795d), which does include the packaging fix, but the segfault  persisted. Modifying the `LD_LIBRARY_PATH` and `PYTHONPATH` environment variables successfully worked around the problem. Thus, I think it remains necessary to document this potential pitfall.

**Comment by jwnimmer-tri** [comment]
:lgtm: Fine, but I would in general be much more interested in _fixing_ the problem rather then documenting it.  I am sure that more hands on the VTK / Bazel prebuilt / etc. work would get it done faster.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5925#-:-KiVLx-krOj8EcKkx3UV:bcmw0gw)*

**Pull request merged**
