### PR TITLE
Fix decimal-point matching across Mac/Ubuntu platforms

### PR DESCRIPTION
**Pull request by mitiguy**
Closes #16186.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16188)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16188#-:-MqLgQyy0j-Diljb0K6p:b-iibo1m)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16188)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy and @sherm1)

___
*[multibody/tree/test/spatial_inertia_test.cc, line 346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16188#-MqLiZDc3ZSBM8OyBpKo:-MqLiZDc3ZSBM8OyBpKp:b-mso3rn) ([raw file](https://github.com/robotlocomotion/drake/blob/67c50d7b6783a608ac9d6a4f1c3e0159cf293fa0/multibody/tree/test/spatial_inertia_test.cc#L346)):*
> ```cpp
>   std::string expected_msg =
>     "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n"
>     " mass = 1.0\n"
> ```

This is also going to fail since the Mac put out "mass = 1" (next case also)
___
*[multibody/tree/test/spatial_inertia_test.cc, line 347 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16188#-MqLjDRgBX_XVEEGLfhF:-MqLjDRgBX_XVEEGLfhG:b-u0qws0) ([raw file](https://github.com/robotlocomotion/drake/blob/67c50d7b6783a608ac9d6a4f1c3e0159cf293fa0/multibody/tree/test/spatial_inertia_test.cc#L347)):*
> ```cpp
>     "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n"
>     " mass = 1.0\n"
>     " Center of mass = \\[0\\.?0?  0\\.?0?  0\\.?0?\\]\n"
> ```

minor: this isn't quite right. You want an optional ".0" but the pattern there would match just a dot or just a zero. That is, if the answer is "1" this would also match "10" since the dot is optional. Since parentheses are a grouping character, you could write this `1(\\.0)?` which matches a "1" optionally followed by ".0".

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending green Ubuntu & Mac CI
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16188#-:-MqLo-TD9smd1NmNbig-:b-a0204q)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Comment by mitiguy** [comment]
@drake-jenkins-bot  linux-bionic-clang-bazel-experimental-everything-release
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot  linux-bionic-gcc-bazel-experimental-debug 
@drake-jenkins-bot  linux-bionic-gcc-bazel-experimental-release please

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release  please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug  please

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @sherm1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16188)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/test/spatial_inertia_test.cc, line 346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16188#-MqLiZDc3ZSBM8OyBpKo:-MqMFinh8gxTDAvueygy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67c50d7b6783a608ac9d6a4f1c3e0159cf293fa0/multibody/tree/test/spatial_inertia_test.cc#L346)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is also going to fail since the Mac put out "mass = 1" (next case also)
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
Skipping slow builds and forcing in now, to unbreak CI.

**Pull request merged**
