### PR TITLE
Run buildifier

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Looks like a few recent PRs (two of which were mine) forgot to run buildifier for reformatting after their final edits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4683)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4683)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4683#-:-K_gIGSQjXMgFocauv8p:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by jwnimmer-tri** [comment]
Some builds still in progress, but bazel builds have passed.  Using override-merge.

**Pull request merged**
