### PR TITLE
Clean up PR2 model

### PR DESCRIPTION
**Pull request by RussTedrake**
- Minor collision geometries (often described by seemingly arbitrary small boxes) have been commented out; they were causing self-collisions even in the default configuration.
- Additional Drake collision-filtering tags have been added to remove remaining self-collisions in the default position.
- The finger tip collision mesh geometry has been replaced by simple box geometry, with additional Drake tags to support hydroelastic contact.
- Long comments we reflowed to fit in Drake's preferred 80 character line limit.

+@cohnt for feature review, please?

Note that there is a version of the urdf (with the original mimic joints which have been restored) here: https://github.com/sehoonha/pydart2/blob/master/examples/data/urdf/PR2/pr2.urdf

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588)

### CODE REVIEW

**Review by cohnt — COMMENTED** [review]
Couple small comments/questions, but they aren't blocking.

:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-:-NkH-65i6k6eGZ1PWlTM:b-ftmkyd)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf` line 2154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkGziTZ5T1qdXN9HRnr:-NkGziTZ5T1qdXN9HRns:bqoh6iu) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2154)):*
> ```XML
>       <drake:proximity_properties>
>         <drake:compliant_hydroelastic/>
>         <drake:hydroelastic_modulus value="1e6"/>
> ```

Is there a reason for this particular choice of modulus value? (Is it documented somewhere that this is a reasonable default value?)

(Similar comment for the other three places this value is used.)
___
*[`examples/pr2/test/load_pr2_simplified_test.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkH-1_H0fZtRTzZAFQj:-NkH-1_H0fZtRTzZAFQk:b-nq529x) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/test/load_pr2_simplified_test.cc#L11)):*
> ```cpp
> namespace pr2 {
> 
> // Tests if the model from pr2_simplified.urdf loads with no errors.
> ```

I don't know the Drake standards for this, but are there any other things that we test programmatically for models? I manually inspected the model, and also confirmed that it works for the mobile base IK problem we have for manipulation.

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please (since we discussed it).  Feel free to punt to tomorrow's reviewer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-:-NkSYTp23LNv3xtdhVhS:b1jfbbt)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf` line 2154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkGziTZ5T1qdXN9HRnr:-NkSYIN1-wNvDc0UakzJ:b4u3unv) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2154)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Is there a reason for this particular choice of modulus value? (Is it documented somewhere that this is a reasonable default value?)

(Similar comment for the other three places this value is used.)
</blockquote></details>

1e7 and 1e8 are relatively common; i chose 1e6 because the fingers should be a little squishy.
___
*[`examples/pr2/test/load_pr2_simplified_test.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkH-1_H0fZtRTzZAFQj:-NkSXic56r0-mdbYZ2zD:b-1rh9kg) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/test/load_pr2_simplified_test.cc#L11)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I don't know the Drake standards for this, but are there any other things that we test programmatically for models? I manually inspected the model, and also confirmed that it works for the mobile base IK problem we have for manipulation.
</blockquote></details>

It's true that this is a bare minimum test coverage, and I'm not proud.  But we adding comprehensive test coverage of the model is not a goal (especially since it's in the examples directory).

**Review by jwnimmer-tri — COMMENTED** [review]
-(release notes: none) +(release notes: fix) This model is installed, so we should mention changes to it as part of the release notes.  (It doesn't matter that its not part of the stable API.)

:lgtm: platform.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-:-NkSr1Hp5QNudEqHi97s:b-t4ogla)* status: 5 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSphWm5ojFefIdsnBx:-NkSphWm5ojFefIdsnBy:b4x4656) (no related file):*
As is typical for most of our vendored models, the nearby README.md contains an inventory of our changes compared to the original.  I see that the URDF file itself also contains an inventory.  The two sources of truth is unfortunate, but that's a pre-existing condition so we can excuse it from the scope of this PR.

However, the README does still says this:

> The description also contains fully actuated finger joints, instead of a single prismatic joint that closes and opens finger joints that mimic each other.

Is that still fully accurate?  It seems at minimum we should make sure both places are all true.

If you wanted to combine the two lists, my vote would be for the URDF to have the inventory, and the README should just say a simple overview "refer to the list in the URDF comments for specific details".

___
___
*[`examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSqcBNCXfbD-tvlx54:-NkSqcBNCXfbD-tvlx55:b-wjq7jp) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L8)):*
> ```XML
> 
>

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588)* status: 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSphWm5ojFefIdsnBx:-NkSvR6C3vCO52K3y5ZQ:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As is typical for most of our vendored models, the nearby README.md contains an inventory of our changes compared to the original.  I see that the URDF file itself also contains an inventory.  The two sources of truth is unfortunate, but that's a pre-existing condition so we can excuse it from the scope of this PR.

However, the README does still says this:

> The description also contains fully actuated finger joints, instead of a single prismatic joint that closes and opens finger joints that mimic each other.

Is that still fully accurate?  It seems at minimum we should make sure both places are all true.

If you wanted to combine the two lists, my vote would be for the URDF to have the inventory, and the README should just say a simple overview "refer to the list in the URDF comments for specific details".
</blockquote></details>

Done.

___
___
*[`examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSqcBNCXfbD-tvlx54:-NkSvIqwDOY23w-jrFu-:b-pni7qr) ([raw file](https://github.com/RobotLocomotion/drake/blob/0dc499fa5cb314d5c0853a8d6c7a24a0c529ce37/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like this PR also introduces new mimic constraints?  That seems like one of the more important changes, and so should be part of the inventory here.
</blockquote></details>

The previous inventory listed the _removal_ of the original mimic joints.  I've simply put them back.
___
*[`examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf` line 2372 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSst4BEHt0BlfLcAOG:-NkSvXjg5lJg_NrZaujF:bet89uh) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe8de5f4a9bbff9a4e8fa1e2be9e5ea646d8df7f/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2372)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW We seem to have been pretty consistent about commenting out transmissions that we don't want, instead of deleting them entirely.  (Both in prior PRs, and in other places in this one.)  Is there a reason for this instance to use a different mechanism?
</blockquote></details>

These transmissions were introduced by us, solely because we didn't have mimic joint support before.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588)* status: 3 unresolved discussions

___
*[`examples/pr2/README.md` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSwSg56_PvpXnh7oNd:-NkSwhziARFwvmdMzu4O:b-hzw6r7) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe8de5f4a9bbff9a4e8fa1e2be9e5ea646d8df7f/examples/pr2/README.md#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> In addition, some tags unsupported by Drake have been removed, to reduce the
burden of warning output.

This sentence is I think still true and important, but I don't see it in the URDF.  I think we need another bullet in that file with this information.
</blockquote></details>

(I don't find the second sentence with the URL particularly helpful, so I'm OK if you want to ditch it.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588)* status: 2 unresolved discussions

___
*[`examples/pr2/README.md` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-NkSwSg56_PvpXnh7oNd:-NkSx9Uy9oAwBv_YVQ0-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe8de5f4a9bbff9a4e8fa1e2be9e5ea646d8df7f/examples/pr2/README.md#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(I don't find the second sentence with the URL particularly helpful, so I'm OK if you want to ditch it.)
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
@cohnt said explicitly "not blocking" above.  I'm going to push it through to make the nightly release.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20588#-:-NkT3hfRDmRPLa6GVm-W:b-5fopjw)* status: 2 unresolved discussions

**Comment by cohnt** [comment]
Regardless, Russ' answers make sense. Thanks! Glad to see we could get this merged quickly.

**Pull request merged**
