### PR TITLE
Move internal static RotationMatrix::NormalizeOrThrow() to unit_vector.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 -- for both reviews.

P.s.  The linking problem on Tuesday night also had to do with the missing &NormalizeOrThrow<T> in:

DRAKE_DEFINE_FUNCTION_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
    (&NormalizeOrThrow<T>, &ThrowIfNotUnitVector<T>, &WarnIfNotUnitVector<T>))

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-:-NhZMUNq13WO0q5fBQ4S:bejujw)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423)* status: 2 unresolved discussions

___
*[`math/unit_vector.cc` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-Nhc6eKE5yLtvgNN_Vdz:-Nhc6eKE5yLtvgNN_Ve-:b-jbdooc) ([raw file](https://github.com/RobotLocomotion/drake/blob/08e97af32b00e9289d282a1029179d98cdca6026/math/unit_vector.cc#L109)):*
> ```cpp
>     if (!(isfinite(norm) && norm >= kMinMagnitude)) {
>       throw std::logic_error(fmt::format(
>           "RotationMatrix::{}() cannot normalize the given vector.\n"
> ```

nit Why does the error message still hard-code "RotationMatrix" here?  This function is _not_ documented as being appropriate only for rotation matrices.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423)* status: 2 unresolved discussions

___
*[`math/unit_vector.cc` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-Nhc6eKE5yLtvgNN_Vdz:-NhcaVM78JZ-ul-Atxf6:b-d39zuw) ([raw file](https://github.com/RobotLocomotion/drake/blob/08e97af32b00e9289d282a1029179d98cdca6026/math/unit_vector.cc#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Why does the error message still hard-code "RotationMatrix" here?  This function is _not_ documented as being appropriate only for rotation matrices.
</blockquote></details>

I missed that! Thanks, Jeremy.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-:-NhdQJuQ8G-E1YgOhF2n:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`math/unit_vector.h` line 67 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-NhbiO0G29Ujv8SJbyFU:-NhcpDID8ilbtsDt0ZsG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/76d1c0206c2140a066743f33123cb7c929d2d5ff/math/unit_vector.h#L67)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "_v_ is a symbolic type" -> "_T_ is a symbolic type"
</blockquote></details>

Done.
___
*[`math/unit_vector.cc` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20423#-Nhc6eKE5yLtvgNN_Vdz:-NhcoVCw1PTNWHIgu3px:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/76d1c0206c2140a066743f33123cb7c929d2d5ff/math/unit_vector.cc#L109)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I missed that! Thanks, Jeremy.
</blockquote></details>

Done.

**Pull request merged**
