### PR TITLE
Revert "Cache contact computations. (#10783)"

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This reverts commit 9ddeef8201fc57d2a9c016f9a188e00992c17925 from #10783, as a temporary mitigation for #10860.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10875)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews, please.  I figure if the regression isn't resolved by mid-morning, we should merge this.

**Comment by amcastro-tri** [comment]
My plan is to push a PR today for a solution implementing what is discussed in #10879. Ideally I'd prefer to wait if you guys can hold it for an extra day and if you are willing to accept the slow down 1.8X to 1.2X until the real issue #10878.

**Comment by jwnimmer-tri** [comment]
1.2x is fine, but having a broken master for extra days is not fine.  If there's not already a PR ready to merge with the fix, then it's time we pull the trigger on this PR.

**Comment by EricCousineau-TRI** [comment]
Aye, SGTM on the merit of moving forward and reducing time pressure on the solution (but with slightly more fiddly merge issues in the future).

**Comment by amcastro-tri** [comment]
> If there's not already a PR ready to merge with the fix, then it's time we pull the trigger on this PR.

#10879 was that PR. We had just discussed in the dynamics team meeting that we'd merge it as is. Sighs...

**Pull request merged**
