### PR TITLE
add minimum pybind to query hydroelastic_contact_info from ContactResults

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)

### CODE REVIEW

**Review by siyuanfeng-tri — COMMENTED** [review]
+@ericcousineau-tri for feature review. 
since i only added getters, not sure what's the best way to smoke test.. any ideas? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKKZ-xA-buKAofoWcLk:bl45hf4)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @siyuanfeng-tri)

___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKeiys7-U7ZpzRoyS7:b-dx3iay) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
> ```cpp
>         .def("id_M", &Class::id_M, doc.ContactSurface.id_M.doc)
>         .def("id_N", &Class::id_N, doc.ContactSurface.id_N.doc)
>         .def("mesh_W", &Class::mesh_W, doc.ContactSurface.mesh_W.doc);
> ```

BTW Presumably, `ContactSurface` itself has not been bound. So, what do you intend to do with the returned value from this method?

**Comment by siyuanfeng-tri** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKi1227Xb8hdExTHK3:bo94hmb) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Presumably, `ContactSurface` itself has not been bound. So, what do you intend to do with the returned value from this method?
</blockquote></details>

all i really want is to call contact_results.hydroelastic_contact_info(0).contact_surface().mesh_W().centroid() to compute point c in W.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @siyuanfeng-tri)

___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKjc8r3TZthnc5u8_F:b-9ofo92) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

all i really want is to call contact_results.hydroelastic_contact_info(0).contact_surface().mesh_W().centroid() to compute point c in W. 
</blockquote></details>

Sorry, I meant `SurfaceMesh` (not `ContactSurface`). I see that the class *is* bound, but not the `centroid()` method.

**Comment by siyuanfeng-tri** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKlUda2Wpin0K7O1uw:b-9hmubf) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Sorry, I meant `SurfaceMesh` (not `ContactSurface`). I see that the class *is* bound, but not the `centroid()` method.
</blockquote></details>

i think i added it, the last thing.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKo_wfB1s4e9I9OrDO:b-88d82v) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i think i added it, the last thing. 
</blockquote></details>

Ah yes....I'll go away and shut up.

**Comment by siyuanfeng-tri** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 851 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKKeiyr3xjFicohGBJ6:-MKKs7ZC9dmVfteWyBiA:bxl1nv6) ([raw file](https://github.com/robotlocomotion/drake/blob/48fabadfebf5bf45bcdece7eb4fb3002d3d78278/bindings/pydrake/geometry_py.cc#L851)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ah yes....I'll go away and shut up.
</blockquote></details>

wait, can you platform review then? hehe

**Review by SeanCurtis-TRI — COMMENTED** [review]
As for testing, simply call the bound APIs and confirm the type of the returned value, that kind of thing. The call is what matters most.

If you go ahead and add the tests, I'm even willing to serve as sole reviewer.

+@seancurtis-tri 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKKtxrY3uiX7uk9HGKZ:bhvl1je)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by siyuanfeng-tri** [comment]
the catch is that i can't construct these guys in python.. since i haven't binded the ctors.. any suggestions?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I haven't looked, but how far down the rabbit hole does binding the constructors go?

Failing that, you'd actually have to construct a contact scenario so you can pull all the appropriate ports. If that's a comparable amount of work, I'd strongly advocate the constructor rabbit hole. Although, that may be quite murky as well.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKKym032q5pdHOq0tLS:b-wcjpch)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by siyuanfeng-tri** [comment]
i need to make a SurfaceMeshFieldLinear at some point.. either way seem too much for me to do tonight.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Life would be simpler if we could default construct a ContactSurface that reported as empty. I've got some changes I need to make to those interfaces. I might do that really quickly and see if we can't simplify your life. I'll ping you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKL1sn79GaibQ2qB4qq:b-3pq9y0)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks great as a start, and yeah, tests would be awesome!

If it's easy to construct a hydroelastic scene (e.g a box and a cylinder contacting), query that info, and just say that it reports something of the right type, then I'd be 10000% down for that.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKL61Xl671srJqBNnVP:bixhb6t)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @siyuanfeng-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKL6-Q10YayQ4D3uhnj:-MKL6-Q2AeDm5_x4xmVJ:bremqqy) (no related file):*
Blocking: For tests

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
That's a lot of down. Far more than the government required 1000% down.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MKL8dXd16rAxMHOIRXl:b7x3p3h)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKL6-Q10YayQ4D3uhnj:-MKY1t2a1p449rL9j2Xo:breqw0p) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Blocking: For tests
</blockquote></details>

added a smoke test. 

---

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a minor configuration nit.

I suspect your CI failure was a flake so I've retriggered to be certain.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MK_5Ya-8wKrpi2zvp0p:bs4y21z)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @siyuanfeng-tri)

___
*[bindings/pydrake/multibody/test/two_bodies.sdf, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MK_5-Ue03acQ6gF-Y1m:-MK_5-Ue03acQ6gF-Y1n:b-kfqhr6) ([raw file](https://github.com/robotlocomotion/drake/blob/65244e5b991d802cd4cfa1644e4acc53db54577c/bindings/pydrake/multibody/test/two_bodies.sdf#L29)):*
> ```
>           <drake:mu_dynamic>0.5</drake:mu_dynamic>
>           <drake:mu_static>0.5</drake:mu_static>
>           <drake:mesh_resolution_hint>0.01</drake:mesh_resolution_hint>
> ```

nit: The resolution hint (0.01) is needlessly tesselating the sphere here (and even more so below) leading to a test that's more expensive than it needs to be. Setting the resolution hint to `2R` will give you a minimal octohedral representation of the sphere but still provide contact.

Same on body2.

**Comment by siyuanfeng-tri** [comment]
hmm. looks like ik test maybe isn't a fake. it's also using the same sdf. so i think i am just going to decouple the sdfs..

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @siyuanfeng-tri)

**Comment by siyuanfeng-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14244#-MKL6-Q10YayQ4D3uhnj:-MK_Iw2W3a3k5j8iFva3:b-896fix) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

added a smoke test. 
</blockquote></details>

Done.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14244#-:-MK_JOVL7aF93rkFgc1T:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
