### PR TITLE
Define GTEST_DONT_DEFINE_TEST

### LINKED ISSUE #2181: Define GTEST_DONT_DEFINE_TEST and others
As discussed on #2172.  Requires migrating existing uses of TEST(...).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #2181.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2431) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review.
+@rpoyner-tri for feature review.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Define GTEST\_DONT\_DEFINE\_TEST
> 
> Closes #2181.
> 
> 
> 
</details>


---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2431#-:-KITcSGpOP0Va_8UhB-g:1458409991)*

**Comment by sherm1** [comment]
Platform: :lgtm:

<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2431#-:-KITi-CTuiPwqVOSo_Ox:-1446635318)*

**Comment by jwnimmer-tri** [comment]
I'll work on conflict resolution now.

**Comment by jwnimmer-tri** [comment]
@sherm1 The jenkins mac was a flake.  Given the GCC pass in the post-conflict-resolution-merge, and the all-pass in the pre-conflict-resolution-merge, I suggest this can be override-merged.

**Comment by sherm1** [comment]
> The jenkins mac was a flake. 

Now I'm seeing one linux/clang failure but mac success. PTAL; if you think that's a flake or unrelated I'll override.

**Comment by jwnimmer-tri** [comment]
Oops, I misspoke.  I think the one open failure is a flake, and is well-covered by the other passes.

**Comment by jwnimmer-tri** [comment]
Do not merge until #2435 is fixed.  Jenkins didn't actually build this PR; it build master by accident.

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Given that (1) this passed yesterday, (2) the only change since then was `s/TEST/GTEST_TEST/;` and (3) the gcc builder successfully built the latest copy of this PR, I believe that's good enough to call this passed-in-jenkins, so I'm going to override-merge to get around "waiting for jenkins".

**Comment by jwnimmer-tri** [comment]
Oops; wrong issue.  Not actually merging yet.

**Comment by jwnimmer-tri** [comment]
Passed on linux: https://drake-jenkins.csail.mit.edu/job/experimental/1718/
Passed on windows: https://drake-jenkins.csail.mit.edu/job/experimental/1729/
All mac nodes are offline, so I'll wait until tomorrow before we revisit this.

**Comment by jwnimmer-tri** [comment]
Passed on linux: https://drake-jenkins.csail.mit.edu/job/experimental/1718/
Passed on windows: https://drake-jenkins.csail.mit.edu/job/experimental/1729/
Passed on mac: https://drake-jenkins.csail.mit.edu/job/experimental/1732/

Using override-merge to get around jenkins not understanding that this has passed.

**Pull request merged**
