### PR TITLE
[doc] Add release instructions for Drake-owned externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjV-lpeBvMMB4wTc0ea:-MjV-lpeBvMMB4wTc0eb:b7ivkki) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
> ```Markdown
>          and check whether that commit already has an associated release tag.
>       2. If not, then create a new release named ``v0.0.foo`` where ``foo`` is
>       	 the 8-digit datestamp associated with the ``commit`` in question.
> ```

Why wouldn't drake tag first and release from the tag?

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

\CC @EricCousineau-TRI @ggould-tri you are welcome to add review comments as well if you are interested.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjV-lpeBvMMB4wTc0ea:-MjV0G1q9DWf4HEVyP97:boxpnax) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Why wouldn't drake tag first and release from the tag?
</blockquote></details>

Our https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/new_release.py has a heuristic:

* If our repostory.bzl uses commit sha, then notify when we see a new commit.
* If our repository.bzl uses a tag, then notify only when we see a new tag.

Think about the case where we PR a change to models (or styleguide).  How do we bring that change into Drake master, so that it bakes before a release?  We'd switch `repository.bzl` to back the new commit sha to bake it, and then back to a (new) tag once its baked.  That's a lot of ping pong.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770#-:-MjV7ieX-CVN3FQkOlSb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks good to me!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770#-:-MjVIOSG99M_pmZpheCn:b9j9n3q)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVICF089R6ERAHYOPb:-MjVICF1-BlqSacTECD3:b-8v3enp) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
> ```Markdown
>          and check whether that commit already has an associated release tag.
>       2. If not, then create a new release named ``v0.0.foo`` where ``foo`` is
>       	 the 8-digit datestamp associated with the ``commit`` in question.
> ```

nit Tab whitespace?
___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVIIQsAxpt3d5-2SWB:-MjVIIQt-kzDB4-Oqxr7:bzei1w0) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
> ```Markdown
>          and check whether that commit already has an associated release tag.
>       2. If not, then create a new release named ``v0.0.foo`` where ``foo`` is
>       	 the 8-digit datestamp associated with the ``commit`` in question.
> ```

nit Instead of 8-digit, can you instead write out `YYYYMMDD`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVIIQsAxpt3d5-2SWB:-MjVJqzs1jydMdRkrhIe:b-upkj5w) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Instead of 8-digit, can you instead write out `YYYYMMDD`?
</blockquote></details>

No, because "YYYYMMDD" has a special meaning in this document (the Drake version number).  I still tried to clarify the desired format here, though.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVICF089R6ERAHYOPb:-MjVTM6SAQdkfFQu1zrU:b6pubgn) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Tab whitespace?
</blockquote></details>

There's still Still a tab whitespace in r2.
___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVIIQsAxpt3d5-2SWB:-MjVTRYs2l-BdxRuw8vR:b-kagoss) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No, because "YYYYMMDD" has a special meaning in this document (the Drake version number).  I still tried to clarify the desired format here, though.
</blockquote></details>

I think you could still distinguish by saying "in `YYYYMMDD` format - but not necessarily the same date as the release" -- but this is still better.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15770)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[doc/_pages/release_playbook.md, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15770#-MjVICF089R6ERAHYOPb:-MjVU8Yw0c4hO_ySua_6:bk6bhmr) ([raw file](https://github.com/robotlocomotion/drake/blob/26b0108a08d25a8992db71630a3a389ce472e6ad/doc/_pages/release_playbook.md#L158)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

There's still Still a tab whitespace in r2.
</blockquote></details>

OK Oops.  Fixed one, but added another.  Both are fixed now.

**Comment by jwnimmer-tri** [comment]
Skipping slow builds; forcing in.

**Pull request merged**
