### PR TITLE
Add visual materials to MBP/SG parsing from SDF

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Extend the parser to extract the material and diffuse tags from the SDF. (Will be replaced when sdformat API updates.)
2. Add unit tests
3. Modify upstream multibody parser and multibody plant to handle the visual material.
4. Modify the acrobot.sdf file used in the MBP examples to illustrate color parsing. Run examples/multibody/acrobot:run_lqr

```
Category            added  modified  removed  
----------------------------------------------
code                69     17        0        
comments            60     2         2        
blank               15     0         0        
----------------------------------------------
TOTAL               144    19        2  
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@amcastro-tri for feature review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGCKZz_A58BYvDGtmFz:b5xll3r)*

**Comment by amcastro-tri** [comment]
Thanks @seancurtis-tri. :lgtm:
+@jwnimmer-tri for platform pretty please.

---

Reviewed 7 of 7 files at r1.
Review status: 2 unresolved discussions, platform LGTM missing

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQghG2RgOHXJxvuyQ:-LGQQghG2RgOHXJxvuyR:b2exak8) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L384)):*
> ```cpp
>               detail::MakeCoulombFrictionFromSdfCollisionOde(sdf_collision);
>           plant->RegisterCollisionGeometry(
>               body, X_LG, *shape, coulomb_friction, scene_graph);
> ```

nit: currently SG shows both visuals and collision. In my dev branch I show collision geometry in orange translucent color. What do you think about doing that here? (I am open on the choice of color). The idea being able to see collision geometry as well. 

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQ3D29F8Jys2d712n:-LGQQ3D29F8Jys2d712o:btv66n9) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L53)):*
> ```objc
> /// If there is no material tag, the supported material tags are missing, or
> /// there is an error parsing the supported values, the instantiated
> /// VisualMaterial will use default values.
> ```

BTW could you document what those default values are or where they are defined?

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQHBF0fHHxKsfQe5S:-LGQQHBF0fHHxKsfQe5T:b-dcai39) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L70)):*
> ```objc
> /// `<mu>` as the static coefficient of friction and `<mu2>` as the dynamic
> /// coefficient of friction. Consider the example below:
> /// ```xml
> ```

BTW sweet! no idea you could do that.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQPnl0-v48khkak3ww:-LGQPnl1BYJkXpbBTIVp:b-oji7st) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L342)):*
> ```cpp
>   // Case: No diffuse defined -- default visual material.
>   // Case: Malformed diffuse value -- default visual material.
>   // Case: Valid diffuse material -- visual material as specified.
> ```

is this meant to be a TODO? or you forgot to push the code?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGQRmTK6d61v2IzkInG:b-oyvrrl)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 5 of 7 files at r1.
Review status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQajur4L9ouJi8erFj:-LGQajur4L9ouJi8erFk:b-ie5680) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L192)):*
> ```cpp
>   // extended to support more data representation types.
> 
>   VisualMaterial material = MakeVisualMaterialFromSdfVisual(sdf_visual);
> ```

nit `const` for clarity.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaoey8Z5vRUp21kRJ:-LGQaoey8Z5vRUp21kRK:bj8yjpl) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L192)):*
> ```cpp
>   // extended to support more data representation types.
> 
>   VisualMaterial material = MakeVisualMaterialFromSdfVisual(sdf_visual);
> ```

This hunk interrupts the comment block above from the if-branch its describing.

GSG also says that variables should be declared near their point of use.  It seems like this should be the second-last statement in the file, moreso since the TODO there is describing this code.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 263 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaC3L6knICuxawqrf:-LGQaC3M-tzrxYWE1R6N:b-ie5680) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L263)):*
> ```cpp
> 
>   using ignition::math::Color;
>   std::pair<Color, bool> value_pair =
> ```

nit `const` for clarity.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaTB0CQG9qRBcmkZ0:-LGQaTB0CQG9qRBcmkZ1:b33m4jq) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L270)):*
> ```cpp
>   Vector4<double> diffuse{sdf_diffuse.R(), sdf_diffuse.G(), sdf_diffuse.B(),
>                           sdf_diffuse.A()};
>   return VisualMaterial(diffuse);
> ```

The constructor being called here does not state that the constructor takes in RGBA.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 338 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQbJ7K3gj3qOfeolQ5:-LGQbJ7K3gj3qOfeolQ6:bt19570) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L338)):*
> ```cpp
>     VisualMaterial material = MakeVisualMaterialFromSdfVisual(*sdf_visual);
>     EXPECT_TRUE(CompareMatrices(material.diffuse(), default_material.diffuse(),
>     0.0, MatrixCompareType::absolute));
> ```

nit Bad indentation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGQbegs0py49B6hIL59:by96gdd)*

**Comment by jwnimmer-tri** [comment]
First pass complete.

---

Reviewed 2 of 7 files at r1.
Review status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 670 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQcUi4AEApPoDCAsKe:-LGQcUi4AEApPoDCAsKf:b-w7gl1o) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.h#L670)):*
> ```objc
>   /// @throws if called post-finalize.
>   /// @throws if `scene_graph` does not correspond to the same instance with
>   /// which RegisterAsSourceForSceneGraph() was called.
> ```

This API documentation is copy-paste from the above, which might lead to maintenance headaches.  Is the pre-existing overload going to be removed later?

(Personally, I think the pre-existing overload's only benefit is to avoid a flag-day transition (which is good); I don't think it has lasting value -- making callers explicitly state their choice to use a default material seems like a positive.)

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQdV6R6GHtsqBvv0Vg:-LGQdV6SBD7HwZscdqvo:bffn8uf) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L108)):*
> ```cpp
>     id = RegisterAnchoredGeometry(X_BG, shape, material, scene_graph);
>   } else {
>     id = RegisterGeometry(body, X_BG, shape, material, scene_graph);
> ```

What test coverage confirms that the two `material` additions here are correct?  I did not immediately see any.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGQdfqO-u2xQ6Rmgeu-:bvb1a6z)*

**Comment by SeanCurtis-TRI** [comment]
Accidentally missing some tests....
+(status: do not review)  (Sorry for the belated tag.)

---

Review status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQ3D29F8Jys2d712n:-LGQ_nWE6ho-PhATsKyq:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW could you document what those default values are or where they are defined?
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQPnl0-v48khkak3ww:-LGQXXtX8jm5LdYzW_mr:bfrg04d) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L342)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this meant to be a TODO? or you forgot to push the code?
</blockquote></details>

Oops...I was apparently horribly distracted and never finished....

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGQioBD7reI8gJdNOEw:b-mubphy)*

**Comment by SeanCurtis-TRI** [comment]
-(status: do not review) 

Tests fleshed out and comments addressed.  PTAL

---

Review status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 670 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQcUi4AEApPoDCAsKe:-LGQqC-q3O3aci1ImJyt:b-b9farj) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.h#L670)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This API documentation is copy-paste from the above, which might lead to maintenance headaches.  Is the pre-existing overload going to be removed later?

(Personally, I think the pre-existing overload's only benefit is to avoid a flag-day transition (which is good); I don't think it has lasting value -- making callers explicitly state their choice to use a default material seems like a positive.)
</blockquote></details>

Your inference is correct.

Ultimately, the whole of this API should go away (when the parsing activities are more generalized). For now, I opted to reconcile the documentation.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQdV6R6GHtsqBvv0Vg:-LGQqRd1Avn3zjnNIG_S:b-oqqbj6) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What test coverage confirms that the two `material` additions here are correct?  I did not immediately see any.
</blockquote></details>

I admit to cheating on this one.

I didn't introduce a unit test because testing this *particular* functionality is rather finicky. Furthermore, it should be retired when (as my previous response indicated) the parsing for SceneGraph is generalized. In lieu of such a test, I merely decorated a previously-existing example with colors.

If you feel strongly about this, I'll dig up some tests.

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQghG2RgOHXJxvuyQ:-LGQr0fb6HaBLee7VJy_:bldpo4o) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L384)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit: currently SG shows both visuals and collision. In my dev branch I show collision geometry in orange translucent color. What do you think about doing that here? (I am open on the choice of color). The idea being able to see collision geometry as well. 
</blockquote></details>

Do you really want that part of *this* PR?

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQajur4L9ouJi8erFj:-LGQr77eAJPKkyDirI7T:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `const` for clarity.
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaoey8Z5vRUp21kRJ:-LGQrIuKCtHaT6l_9K_0:b-nkezmi) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This hunk interrupts the comment block above from the if-branch its describing.

GSG also says that variables should be declared near their point of use.  It seems like this should be the second-last statement in the file, moreso since the TODO there is describing this code.
</blockquote></details>

I missed the todo previously. I've moved this where it *should be.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 263 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaC3L6knICuxawqrf:-LGQrbBCC76X2sOYpk9F:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L263)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `const` for clarity.
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQaTB0CQG9qRBcmkZ0:-LGQrtyX59vu4krHHIKY:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L270)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The constructor being called here does not state that the constructor takes in RGBA.
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 338 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQbJ7K3gj3qOfeolQ5:-LGQrzRS6uXUqnBv9Tzl:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L338)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Bad indentation.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGQuAsS1r-qTijzsHWy:b-82ntii)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQdV6R6GHtsqBvv0Vg:-LGR-u9J0vEJzvrdZ8v5:bzdygg0) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I admit to cheating on this one.

I didn't introduce a unit test because testing this *particular* functionality is rather finicky. Furthermore, it should be retired when (as my previous response indicated) the parsing for SceneGraph is generalized. In lieu of such a test, I merely decorated a previously-existing example with colors.

If you feel strongly about this, I'll dig up some tests.
</blockquote></details>

Since the failure mode(s) are relatively uniform, I don't see a need for lots of test cases, but a single "did a non-default material come out at all, ever" acceptance test seems worthwhile.  I would hope that would apply equally as well after the implementation gets refactored?

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQQghG2RgOHXJxvuyQ:-LGQzyq9BAzNejm7VuJy:b-k33c30) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L384)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Do you really want that part of *this* PR?
</blockquote></details>

(No; definitely not.)

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQznzz6c0UMpBV8VcL:-LGQzo--BstsgfiU62n8:bsmjwak) ([raw file](https://github.com/robotlocomotion/drake/blob/3e10a4d57aa970b707cbf7dc4a382667e659e63a/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L191)):*
> ```cpp
>   // TODO(amcastro-tri): Cleanup usage of sdf::ElementPtr once sdformat gets
>   // extended to support more data representation types.
> ```

nit Spurious newline added here.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGR-Yi_Ayk8PEbgY1_U:-LGR-Yi_Ayk8PEbgY1_V:b-ceinwq) ([raw file](https://github.com/robotlocomotion/drake/blob/3e10a4d57aa970b707cbf7dc4a382667e659e63a/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L376)):*
> ```cpp
>         "  </geometry>"
>         "  <material>"
>         "    <diffuse>" + diffuse_str + "</diffuse>"
> ```

FYI It's a bit weird to write out a very long to_string thing for this one, but in the below case to just hard-code the same values in both the string and the expected result.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQdV6R6GHtsqBvv0Vg:-LGSBvho2HGDiPmJLR1_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e0162ee153d47a6cb054ed0d5d0a9d48ba1c08fa/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since the failure mode(s) are relatively uniform, I don't see a need for lots of test cases, but a single "did a non-default material come out at all, ever" acceptance test seems worthwhile.  I would hope that would apply equally as well after the implementation gets refactored?
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGQznzz6c0UMpBV8VcL:-LGRwsMoAde_KFtTYNl4:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3e10a4d57aa970b707cbf7dc4a382667e659e63a/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L191)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Spurious newline added here.
</blockquote></details>

Done

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 376 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGR-Yi_Ayk8PEbgY1_U:-LGRwzNp4xqnLrPyRVHm:b-dvo27z) ([raw file](https://github.com/robotlocomotion/drake/blob/3e10a4d57aa970b707cbf7dc4a382667e659e63a/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L376)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It's a bit weird to write out a very long to_string thing for this one, but in the below case to just hard-code the same values in both the string and the expected result.
</blockquote></details>

Agreed; I had the ambition to have the xml and the test value intrinsically linked; but then it got so ugly that I decided to stop doing it. PTAL

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri]

---

*[geometry/geometry_state.h, line 236 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGSNFdRDj36kOXioJaH:-LGSNFdRDj36kOXioJaI:b-sd34uv) ([raw file](https://github.com/robotlocomotion/drake/blob/e9091a60db28bba095f86cbfd83c1227efe44dda/geometry/geometry_state.h#L236)):*
> ```objc
>                             GeometryInstance. */
>   optional<std::reference_wrapper<const VisualMaterial>> get_visual_material(
>       GeometryId geometry_id) const;
> ```

An optional reference is also known a pointer.  Why choose this formulation?  The using-code doesn't seem to treat this is any way beyond as-if it were a pointer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083#-:-LGSOR5qB0cT2--TPIiS:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 5 files at r2, 9 of 9 files at r3.
Review status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri]

---

*[geometry/geometry_state.h, line 236 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGSNFdRDj36kOXioJaH:-LGVHgh4AYyxlBRP3SJU:b9334qp) ([raw file](https://github.com/robotlocomotion/drake/blob/e9091a60db28bba095f86cbfd83c1227efe44dda/geometry/geometry_state.h#L236)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

An optional reference is also known a pointer.  Why choose this formulation?  The using-code doesn't seem to treat this is any way beyond as-if it were a pointer.
</blockquote></details>

yes, quite an interesting choice. Just as a user, this is quite a mouthful to parse. You might want to consider other options.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri]

---

*[geometry/geometry_state.h, line 236 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9083#-LGSNFdRDj36kOXioJaH:-LGVNckhDs5c_YvARRqf:b-q9us9m) ([raw file](https://github.com/robotlocomotion/drake/blob/e9091a60db28bba095f86cbfd83c1227efe44dda/geometry/geometry_state.h#L236)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

yes, quite an interesting choice. Just as a user, this is quite a mouthful to parse. You might want to consider other options.
</blockquote></details>

For Pratchett fans, that's *exactly* how you end up with a tree-swing where the swing passes through the trunk. Siiiigh.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r4.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9083)*

**Comment by jwnimmer-tri** [comment]
@amcastro-tri I'm not sure that Sean wanted this squashed?  Oh well.

**Pull request merged**
