### PR TITLE
Remove MATLAB Doxygen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This removes the links to the documentation from the main website, instructions for regenerating the documentation, the rules in CMake, and the underlying tool support.

The tooling will remain in git history in case we choose to resurrect it, but for now our priority is going to be on bindings directly into the new C++ APIs (not the older hand-written interface) and this `.m`-file documentation style does not support that goal.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6232)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This will be squash-merged, but is left for now as separate commits in case that's easier for reviewers.

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.  I'll wait to assign feature / platform review until after that.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6232#-KleL8nYgiCEqexQYzlY:-KleL8nYgiCEqexQYzlZ:b-w4scup) ([raw file](https://github.com/robotlocomotion/drake/blob/a3182d289809c54a5c4f474f8047af090fb32cf3/drake/doc/documentation_instructions.rst#L51)):*
> ```reStructuredText
> 
> - Drake website: ``drake-distro/build/drake/doc/sphinx/index.html``
> - Doxygen C++ website: ``drake-distro/build/drake/doc/doxygen_cxx/html/index.html``
> ```

FYI  - I thought about recommending we change "Doxygen C++" to simply "Doxygen", but have convinced myself that it's best as is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6232#-:-KleLWu9a_5KB1S9fT_1:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) 
+@ggould-tri for all review, please.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6232#-:-KleY9jaiaHn3ZiFIdxv:b2dgxg8)*

**Comment by ggould-tri** [comment]
This is a very large commit (>1000 lines of diff); please break it up into smaller pieces and try again.
...Or not. :stuck_out_tongue: :lgtm:  Congrats on on >1000 net negative! :confetti_ball:

**Comment by ggould-tri** [comment]
Hm, my lgtm there had no effect.  Trying again.
:lgtm:

**Pull request merged**
