### PR TITLE
Better handle LCM message publication time

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In its original form, it was repeated-everywhere default value of 0.0, but GSG forbids default arguments in virtual methods.  Here, we change it to be an `optional<>`.

This patch also contains a hodge-podge of related cleanups.  Along with #8421 and #8425, this cleans up #7178.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8450)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

**Comment by sammy-tri** [comment]
:lgtm:  I guess +@seancurtis-tri for platform review since he's the next person on the rotation which isn't myself or Jeremy.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8450#-:-L8XhRzk97cy6cnwE266:b73wa5q)*

**Comment by jwnimmer-tri** [comment]
Probably Wednesday is fine.  At least, at this moment my next draft PR's in this train don't depend on this one.  I'll let you know if I end up needing it sooner.

**Comment by SeanCurtis-TRI** [comment]
Sounds good.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8450#-:-L8XuLV6MWjfNpTtMCfR:brxp9sq)*

**Pull request merged**
