### PR TITLE
SceneGraph modifies/access renderer in the context.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously we only provide API to modify/query the renderer in the SceneGraph
 model. Now we provide API to modify/query the renderer in the context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-:-NgVc_DGAklZQDKbRLgy:bltfyse)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@sherm1 for platform review, please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-:-NgVel-YBaGQTn39pJp4:b-kfdtai)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few missing tests and minor comments

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-:-NgVn5wYCHhWWNaKioM1:bi1mrtp)* status: 4 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/test/scene_graph_test.cc` line 519 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVlgXf4Y2yslrzCpGh:-NgVlgXf4Y2yslrzCpGi:b-7hre6w) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/geometry/test/scene_graph_test.cc#L519)):*
> ```cpp
>   EXPECT_EQ(scene_graph_.RendererCount(), 1);
>   EXPECT_EQ(scene_graph_.RegisteredRendererNames()[0], kRendererName);
>   EXPECT_TRUE(scene_graph_.HasRenderer(kRendererName));
> ```

minor: tests needed for RemoveRenderer() and GetRendererTypeName()  (here and in the Context)
___
*[`geometry/test/scene_graph_test.cc` line 523 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVkqpx-hLwKp6CfBrc:-NgVkqpx-hLwKp6CfBrd:b-6ve3z2) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/geometry/test/scene_graph_test.cc#L523)):*
> ```cpp
> 
> TEST_F(SceneGraphTest, RendererInContextSmokeTest) {
>   // Test the renderer added to the SceneGraph
> ```

nit: SceneGraph->Context
___
*[`geometry/test/scene_graph_test.cc` line 536 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVkwkzC96GFW2pm3Iv:-NgVkwkzC96GFW2pm3Iw:b-vi4eyj) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/geometry/test/scene_graph_test.cc#L536)):*
> ```cpp
>   EXPECT_EQ(scene_graph_.RendererCount(*context_), 1);
>   EXPECT_EQ(scene_graph_.RegisteredRendererNames(*context_)[0], kRendererName);
>   EXPECT_TRUE(scene_graph_.HasRenderer(*context_, kRendererName));
> ```

BTW consider adding a check that there are still zero renderers in the scene_graph_ (as opposed to the context_).
___
*[`bindings/pydrake/geometry/geometry_py_scene_graph.cc` line 277 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVmsPK4sxilVGVAY_y:-NgVmsPK4sxilVGVAY_z:b-a0vgve) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/bindings/pydrake/geometry/geometry_py_scene_graph.cc#L277)):*
> ```cpp
>             overload_cast_explicit<int, const systems::Context<T>&>(
>                 &Class::RendererCount),
>             py::arg("context"), cls_doc.RendererCount.doc_1args)
> ```

BTW  GetRendererTypeName() is not wrapped (for either SceneGraph or Context). That's fine, just want to make sure that was your intention.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355)* status: missing label for release notes

___
*[`geometry/test/scene_graph_test.cc` line 519 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVlgXf4Y2yslrzCpGh:-NgVrXk1CSxD6zxOf8-L:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/geometry/test/scene_graph_test.cc#L519)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: tests needed for RemoveRenderer() and GetRendererTypeName()  (here and in the Context)
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/geometry_py_scene_graph.cc` line 277 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgVmsPK4sxilVGVAY_y:-NgWE1KA9vnfJrjDAbTQ:bkowx56) ([raw file](https://github.com/RobotLocomotion/drake/blob/208792ec1c3066a401c720a71da9070685fcd27a/bindings/pydrake/geometry/geometry_py_scene_graph.cc#L277)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW  GetRendererTypeName() is not wrapped (for either SceneGraph or Context). That's fine, just want to make sure that was your intention.
</blockquote></details>

Done, I added the binding.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/test/scene_graph_test.cc` line 547 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgWP3KxAFUawerC08bA:-NgWP3KyEUsy6IQ8B9wi:bwciu31) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1319cc54f1c6e5c01a0d3619d0a0874b0d9464f/geometry/test/scene_graph_test.cc#L547)):*
> ```cpp
>       scene_graph_.RemoveRenderer(context_.get(), kRendererName));
>   EXPECT_EQ(scene_graph_.RendererCount(*context_), 0);
>   EXPECT_FALSE(scene_graph_.HasRenderer(*context_, kRendererName));
> ```

minor: new tests look good; still not seeing C++ tests for GetRendererTypeName() ?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355)* status: missing label for release notes

___
*[`geometry/test/scene_graph_test.cc` line 547 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-NgWP3KxAFUawerC08bA:-NgWT181DKrrfiuGDVYg:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1319cc54f1c6e5c01a0d3619d0a0874b0d9464f/geometry/test/scene_graph_test.cc#L547)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: new tests look good; still not seeing C++ tests for GetRendererTypeName() ?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355)* status: missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20355#-:-NgZ57GtCD5mpOX4arg5:b-l8xbmn)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
