### PR TITLE
add helper method to set publish period on signal logger. 

### PR DESCRIPTION
**Pull request by RussTedrake**
mirrors the implementation on the lcm publisher system

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sammy-tri for feature review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990#-:-LExYE_l0DluZdhj0nE8:b-1h8soq)*

**Comment by sammy-tri** [comment]
:lgtm: with some formatting nits.   +@soonho-tri for platform review

---

Reviewed 4 of 4 files at r1.
Review status: 1 unresolved discussion, platform LGTM from [sammy-tri]

---

*[systems/primitives/test/signal_logger_test.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8990#-LEz8so2A1lEu8YIpW5G:-LEz8so3EWMYjd2VwSTv:b-l8zvfe) ([raw file](https://github.com/robotlocomotion/drake/blob/c8a932e0bc1b0f1d2931f727cb97de785fec3fb6/systems/primitives/test/signal_logger_test.cc#L41)):*
> ```cpp
>   // Simulate the simple system from x(0) = 1.0.
>   Simulator<double> simulator(*diagram);
>   Context<double> &context = simulator.get_mutable_context();
> ```

http://drake.mit.edu/styleguide/cppguide.html#Pointer_and_Reference_Expressions specifies that the `&` should be next to the type, not the variable name.  Also below at `t` and `x`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990#-:-LEz94529-6yIMijU4Vd:brlupih)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: 2 unresolved discussions, platform LGTM from [sammy-tri, soonho-tri]

---

*[systems/primitives/signal_logger.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8990#-LEzHWg663zp_Ud5zmu-:-LEzHWg76AT6wYB2tWXG:bowokl9) ([raw file](https://github.com/robotlocomotion/drake/blob/c8a932e0bc1b0f1d2931f727cb97de785fec3fb6/systems/primitives/signal_logger.h#L45)):*
> LeafSystem::DeclarePublishPeriodSec() for details about the semantics

Nit, I think it's a typo of `DeclarePeriodicPublish()`.

https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a1adf7020dee795fd1b34b023c447eb6f

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990#-:-LEzHg_iAnZFVY7JoDOU:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: 2 unresolved discussions, platform LGTM from [sammy-tri, soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990)*

**Comment by RussTedrake** [comment]
Review status: 2 unresolved discussions, platform LGTM from [sammy-tri, soonho-tri]

---

*[systems/primitives/signal_logger.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8990#-LEzHWg663zp_Ud5zmu-:-LF2M_wMBwrPfDGiEfQq:b-pib3ij) ([raw file](https://github.com/robotlocomotion/drake/blob/c8a932e0bc1b0f1d2931f727cb97de785fec3fb6/systems/primitives/signal_logger.h#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> LeafSystem::DeclarePublishPeriodSec() for details about the semantics

Nit, I think it's a typo of `DeclarePeriodicPublish()`.

https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a1adf7020dee795fd1b34b023c447eb6f
</blockquote></details>

good catch.  fixed here, and the place I copied it from.  ;-)

---

*[systems/primitives/test/signal_logger_test.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8990#-LEz8so2A1lEu8YIpW5G:-LF2Msb65olfi5tKMDiZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c8a932e0bc1b0f1d2931f727cb97de785fec3fb6/systems/primitives/test/signal_logger_test.cc#L41)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

http://drake.mit.edu/styleguide/cppguide.html#Pointer_and_Reference_Expressions specifies that the `&` should be next to the type, not the variable name.  Also below at `t` and `x`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: 1 unresolved discussion, platform LGTM from [sammy-tri, soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri, soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8990)*

**Pull request merged**
