### PR TITLE
Updated MATLAB C++ standard library hacks to latest versions.

### PR DESCRIPTION
**Pull request by liangfok**
This is what works on my Ubuntu 14.04.4 system using the lastest version of MATLAB.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2220)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-KGYtg0V64sfltaZ4mJy:-KGYtg0V64sfltaZ4mJz:2048919569) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d975dc0f7a76d88524a020eb178580d693a65e/drake/doc/ubuntu.rst#L38)):*
R2016a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-:-KGYtj10o7v-FZfShv9X:1417088721)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-KGYtg0V64sfltaZ4mJy:-KGYvO4e03V1od9roNI_:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d975dc0f7a76d88524a020eb178580d693a65e/drake/doc/ubuntu.rst#L38)):*
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/ubuntu.rst, line 42 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-KGZIJjuEfhkdAbETHOy:-KGZIJjuEfhkdAbETHOz:632129195) ([raw file](https://github.com/robotlocomotion/drake/blob/56837279b6dcb28726a673cb27f9776536c8bd90/drake/doc/ubuntu.rst#L42)):*
Actually, 4.9 (a symlink to 4.9.3) was the correct answer here.  If Ubuntu publishes an updated compiler, 4.9.3 will go away, but the 4.9 symlink would change to the correct location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 42 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-KGZIJjuEfhkdAbETHOy:-KGZqydkdUeRi-uh2T3M:-1213985015) ([raw file](https://github.com/robotlocomotion/drake/blob/56837279b6dcb28726a673cb27f9776536c8bd90/drake/doc/ubuntu.rst#L42)):*
Good catch. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220)*

**Comment by liangfok** [comment]
Looks like this PR is ready to be merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2220#-:-KGZxFxdcCZhT1dlC_Cy:1103427915)*

**Pull request merged**
