### PR TITLE
Add test size of examples/kuka_iiwa_arm/dev:iiwa_ik_test

### PR DESCRIPTION
**Pull request by soonho-tri**
Fix CI timeout problem introduced by https://github.com/RobotLocomotion/drake/commit/95aab090c60718d54fe203f882201c23436a9454

/cc @siyuanfeng-tri , @kunimatsu-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5319)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-bazel-continuous-debug please.
@drake-jenkins-bot linux-gcc-bazel-continuous-debug please.
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-debug please.
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-debug please.
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-everything-debug please.

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , both reviews please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5319#-:-KdppGlpr2rrEagwwDa3:b-mbs47t)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5319#-:-KdpqGtTYG28fU-l74Uw:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
