### PR TITLE
[optimization] Adjust "cspace free" to use the Parallelism helper

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Inspired by #20759.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20776)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 17 of 31 files at r1, 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20776)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@AlexandreAmice for feature review, please?

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

Note to platform reviewer to check that the deprecation policy is being followed as I am unfamiliar with that process

> Reviewed 11 of 31 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20776#-:-NoKJ9Jx3NjlDpJghYpI:bdma8yf)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.  As noted upthread, please have a careful look at the deprecations & related.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 11 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20776)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
The Pydrake deprecation looks good to me. I don't see any C++ deprecation for the renamed field and assume that's what the `release notes: breaking change` is for. Assuming that's correct, platform :lgtm:

> Reviewed 11 of 31 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20776#-:-NoONsN298PSEGwFXteu:b-q14wvd)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),AlexandreAmice

**Comment by jwnimmer-tri** [comment]
> I don't see any C++ deprecation for the renamed field and assume that's what the release notes: breaking change is for.

Yes, that's correct.  Hopefully the commit message will be clear enough for the release manager, but if not I'll be sure to adjust there when the time comes.

**Pull request merged**
