### PR TITLE
Restore hidden tkinter dependency via matplotlib / pyplot

### PR DESCRIPTION
**Pull request by svenevs**
Partially reverts #17295.

pydrake.systems.planar_scenegraph_visualizer imports matplotlib.pyplot which in turn tries to import tkinter and fails for lack of any other plotting backends being available.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17305)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-bazel-experimental-release please.

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for review please.  Additional consideration is [the matplotlib backends](https://matplotlib.org/3.5.0/users/explain/backends.html#the-builtin-backends), doesn't need to block this for the sake of keeping things functional.  I added two jobs (docs one we know failed, mac for posterity) but really that's just to make sure the installation works.  I don't think we necessarily need to wait for the full jobs to finish, just confirm they install `python-tk`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17305#-:-N3UYQ8MBXi6n_lw19rU:b-poxam9)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by svenevs** [comment]
Partial update: linux build [successfully installs `python3-tk`](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-documentation/11/console):

```
[10:02:26 AM]  Selecting previously unselected package python3-tk:amd64.
[10:02:26 AM]  Preparing to unpack .../197-python3-tk_3.8.10-0ubuntu1~20.04_amd64.deb ...
[10:02:26 AM]  Unpacking python3-tk:amd64 (3.8.10-0ubuntu1~20.04) ...
```

**Comment by jwnimmer-tri** [comment]
Tentatively, I think that this PR should have also reverted the `pip.md` instructions changes from #16656.  Due to the indirect Ubuntu pyplot => tk dependency, I think `import pydrake.all` still needs Tk (due to, e.g., planar_scenegraph_visualizer).

**Pull request merged**
