### PR TITLE
[geometry] Make deformable mesh from VTK in mesh specification.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Towards #16875.

Still a draft since it's waiting for #17820.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+(status: do not review) +(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBUU1NoC44918Jt0SPk:bii7ohl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
CC: @xuchenhan-tri 

We'll start the review when #17820 is merged.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBYdSZh9PXz8ItN5QJn:b7z43y8)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not merge) -(status: do not review) 
#17820 has been merged into the master.  We'll start the review now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBn11b8ADt67XjsgKxv:b-jzyqbh)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBn1Fic7o0o949A9-SW:b7bdky2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: +@ggould-tri for a short platform review, please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBnBVLCAzQSrKKz3XQz:blmm6jp)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by DamrongGuoy — COMMENTED** [review]
That's one of the fastest reviews I've seen.  Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBnEvMzBxSc1c-eLDu4:b-6wf0dz)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
I can keep it fast :-)
:lgtm: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880#-:-NBnGjge8dYjfQ-tnSHQ:bll4oma)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[`geometry/make_mesh_for_deformable.cc` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17880#-NBnG0s980nJTyYbeRA2:-NBnG0s980nJTyYbeRA3:bhw24y0) ([raw file](https://github.com/robotlocomotion/drake/blob/61f1fa40101ee22097660d860ce8b157d1aa3e47/geometry/make_mesh_for_deformable.cc#L33)):*
> ```cpp
> void MeshBuilderForDeformable::ImplementGeometry(const Mesh& mesh_spec,
>                                                  void* user_data) {
>   ReifyData& data = *static_cast<ReifyData*>(user_data);
> ```

minor:  This could be a null pointer dereference; you should `DRAKE_DEMAND` nonnull first for a clearer message.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17880)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),joemasterjohn (waiting on @ggould-tri and @joemasterjohn)

___
*[`geometry/make_mesh_for_deformable.cc` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17880#-NBnG0s980nJTyYbeRA2:-NBnXlNh73nwxxSIjiL-:b-mr0yyv) ([raw file](https://github.com/robotlocomotion/drake/blob/61f1fa40101ee22097660d860ce8b157d1aa3e47/geometry/make_mesh_for_deformable.cc#L33)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This could be a null pointer dereference; you should `DRAKE_DEMAND` nonnull first for a clearer message.
</blockquote></details>

Done for both Sphere and Mesh. Thanks.

**Pull request merged**
