### PR TITLE
Added continuity constraints

### PR DESCRIPTION
**Pull request by wrangelvid**
This adds continuity constraints on r(t), which enables a better distribution of grid points for smoother trajectories where Toppra can enforce acceleration constraints.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441)

### CODE REVIEW

**Comment by wrangelvid** [comment]
@RussTedrake for feature review please.

**Review by RussTedrake — COMMENTED** [review]
Replaces #20243 (as discussed with @sadraddini )
Will check the math in the morning!

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-:-NhyGwfnBYmwH6YmS1zs:b3ibgkj)* status: 5 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyH3tXBvhy4EkfKh5p:-NhyH3tXBvhy4EkfKh5q:b-y9a8kn) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L32)):*
> ```objc
> regions since non-convex continuity constraints are not supported yet. However,
> it supports continuity on the path r(s) for arbitrary degree. The resulting
> trajectories can descaled @see
> ```

"can descaled" => "can be descaled".  though I'm not sure I like the term "descaled".  how about something more like "NormalizeTimeScaling" or "MakeUniformTimeScaling"?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHott709ZbH6T-rNQ:-NhyHott709ZbH6T-rNR:b-n47s19) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L129)):*
> ```objc
>                            const Eigen::Ref<const Eigen::VectorXd>& ub);
> 
>     /** Enforces higher order continuity constraints on the subgraph.
> ```

higher than what?  maybe say derivative continuity constraints?  or say explicitly that the path continuity is enforced by default.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 144 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHcZE2gVIJcjvkXiA:-NhyHcZE2gVIJcjvkXiB:b-cokl4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L144)):*
> ```objc
>     @throws std::exception if the continuity order is less than one.
>     */
>     void AddContinuityConstraints(int continuity_order);
> ```

Can we call it `AddPathContinuityConstraints` to make sure the r(s) vs q(t) distinction is super clear?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyI6nZ3QOLAhn0vV6m:-NhyI6nZ3QOLAhn0vV6n:b-x5kckg) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L209)):*
> ```objc
> 
>     /** Enforces higher order continuity constraints on the edges between the
>     subgraphs.
> ```

same as above. also below.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHlKO5bfECSAgCkZM:-NhyHlKO5bfECSAgCkZN:bl8c4n9) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L224)):*
> ```objc
>     @throws std::exception if the continuity order is less than one.
>     */
>     void AddContinuityConstraints(int continuity_order);
> ```

AddPathContinuityConstraints

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441)* status: 5 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyH3tXBvhy4EkfKh5p:-Ni1KpSH8M0c5Ca_1eLz:b-97plgm) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L32)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"can descaled" => "can be descaled".  though I'm not sure I like the term "descaled".  how about something more like "NormalizeTimeScaling" or "MakeUniformTimeScaling"?
</blockquote></details>

What do you think about `ReconstructGcsPathTrajectory`? I want to be clear that r(t) will be obtained from the trajectory returned by the SolvePath
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHott709ZbH6T-rNQ:-Ni1O8Na9Wm2RUeAtYR6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L129)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

higher than what?  maybe say derivative continuity constraints?  or say explicitly that the path continuity is enforced by default.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 144 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHcZE2gVIJcjvkXiA:-Ni1IcC-7EEAEeXFtUzO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L144)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can we call it `AddPathContinuityConstraints` to make sure the r(s) vs q(t) distinction is super clear?
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyI6nZ3QOLAhn0vV6m:-Ni1IbvLEk7PQ4kvnCQ6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L209)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

same as above. also below.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyHlKO5bfECSAgCkZM:-Ni1ROHXAnfbuHFVOsLy:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L224)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

AddPathContinuityConstraints
</blockquote></details>

Done.

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441)* status: 5 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

**Review by RussTedrake — COMMENTED** [review]
math looks good! just a few more comments...

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-:-NiR69uGBmz-xi85RGYO:b-cioo9d)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NhyH3tXBvhy4EkfKh5p:-NiR1XGt1sJa4DSKuyDE:b-qo1z5l) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab87ee11b46fad392d226e79ad12f1b5aaa5827/planning/trajectory_optimization/gcs_trajectory_optimization.h#L32)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

What do you think about `ReconstructGcsPathTrajectory`? I want to be clear that r(t) will be obtained from the trajectory returned by the SolvePath
</blockquote></details>

Will comment below.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 503 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NiR3Bd53c6uPUbMv4zV:-NiR3Bd53c6uPUbMv4zW:bfv2mxm) ([raw file](https://github.com/RobotLocomotion/drake/blob/b86e2fd298d1911dc184d5b175928d159ab04649/planning/trajectory_optimization/gcs_trajectory_optimization.h#L503)):*
> ```objc
> */
> trajectories::CompositeTrajectory<double> ReconstructGcsPathTrajectory(
>     const trajectories::CompositeTrajectory<double>& gcs_trajectory);
> ```

I don't love PathTrajectory; it's either a path OR a trajectory.

I think we could make this a static method of the GcsTrajectoryOptimization class.  It does not depend on the GcsTrajOpt data, but does depend on the GcsTrajOpt concept.

Then I would think we could call it ReconstructPath(...)
But I think it would be even clearer to call it NormalizeSegmentTimes(...) ?
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 802 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NiR5zhX6dE87BVe1Sap:-NiR5zhX6dE87BVe1Saq:b-7a1myl) ([raw file](https://github.com/RobotLocomotion/drake/blob/b86e2fd298d1911dc184d5b175928d159ab04649/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L802)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(traj.value(traj.end_time()), goal, 1e-6));
> 
>   auto descaled_traj = ReconstructGcsPathTrajectory(traj);
> ```

btw - maybe descaled => normalized?

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 503 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NiR3Bd53c6uPUbMv4zV:-NijJyAQ6Dwrr2ErfT5M:b7tmi7s) ([raw file](https://github.com/RobotLocomotion/drake/blob/b86e2fd298d1911dc184d5b175928d159ab04649/planning/trajectory_optimization/gcs_trajectory_optimization.h#L503)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't love PathTrajectory; it's either a path OR a trajectory.

I think we could make this a static method of the GcsTrajectoryOptimization class.  It does not depend on the GcsTrajOpt data, but does depend on the GcsTrajOpt concept.

Then I would think we could call it ReconstructPath(...)
But I think it would be even clearer to call it NormalizeSegmentTimes(...) ?
</blockquote></details>

Haha fair, there is no such thing as `PathTrajectory` :-D
I like the static method idea!
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 802 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NiR5zhX6dE87BVe1Sap:-NijLu5W8BZV1fpNYEFI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b86e2fd298d1911dc184d5b175928d159ab04649/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L802)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw - maybe descaled => normalized?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

+@sammy-tri for platform review, please.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-:-NilpliW21PE2dYBvaPG:bx1aas5)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 33 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NilojzZ0IvkmuPP51lH:-NilojzZ0IvkmuPP51lI:b-4xfzmf) ([raw file](https://github.com/RobotLocomotion/drake/blob/2ee3f84195a2a6f7a71c6be5e0e98ef0037677cb/planning/trajectory_optimization/gcs_trajectory_optimization.h#L33)):*
> ```objc
> it supports continuity on the path r(s) for arbitrary degree. The path
> r(s) can be reconstructed from the gcs solution q(t) with @see
> `planning::trajectory_optimization::GcsTrajectoryOptimization::NormalizeSegmentTimes()`
> ```

nit: you can just write NormalizeSegmentTimes() here, I believe. Since this docstring is associated with the class.  When in doubt, build the documentation locally to test.
https://drake.mit.edu/documentation_instructions.html

here and throughout.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 481 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NilpI19CqOLg90hLPsa:-NilpI19CqOLg90hLPsb:b-oquo8v) ([raw file](https://github.com/RobotLocomotion/drake/blob/2ee3f84195a2a6f7a71c6be5e0e98ef0037677cb/planning/trajectory_optimization/gcs_trajectory_optimization.h#L481)):*
> ```objc
>   */
>   static trajectories::CompositeTrajectory<double> NormalizeSegmentTimes(
>       const trajectories::CompositeTrajectory<double>& gcs_trajectory);
> ```

nit: i would say the gcs is implied?  `traj` or `trajectory` would be sufficient.  (I see examples of both in other parts of the code.)

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 33 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NilojzZ0IvkmuPP51lH:-Nioxshy4ieemGCQpfQO:bp0n4gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/2ee3f84195a2a6f7a71c6be5e0e98ef0037677cb/planning/trajectory_optimization/gcs_trajectory_optimization.h#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: you can just write NormalizeSegmentTimes() here, I believe. Since this docstring is associated with the class.  When in doubt, build the documentation locally to test.
https://drake.mit.edu/documentation_instructions.html

here and throughout.
</blockquote></details>

Ahh that is handy! I cleaned up some other weird formatting as well .
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 481 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-NilpI19CqOLg90hLPsa:-NioxrVb0HzZpfg9PKgP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2ee3f84195a2a6f7a71c6be5e0e98ef0037677cb/planning/trajectory_optimization/gcs_trajectory_optimization.h#L481)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: i would say the gcs is implied?  `traj` or `trajectory` would be sufficient.  (I see examples of both in other parts of the code.)
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
+(release notes: feature) :lgtm:

> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20441#-:-NiplB8JDLtzSwd_Qomy:b-f5k3mb)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Pull request merged**
