### PR TITLE
patching drake_lcm_log.cc

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
fix a timer thing in mac.
fix a dead lock in lcm_subscriber_system.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7217)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please

**Comment by siyuanfeng-tri** [comment]
+@m-chaturvedi for reviews. thanks! 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-:-KvwR-rsrpj_HUqNq8EY:b-hig4hr)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-:-KvxEGmJvv1uxmfBMvKu:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217)*

**Comment by siyuanfeng-tri** [comment]
+@jwnimmer-tri for platform review, thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-:-Kw09pja9lbspT9gg31K:bswklqh)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/lcm/lcm_subscriber_system.cc, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-Kw0HPPC9gTMMD_9qBb2:-Kw0HPPC9gTMMD_9qBb3:bo0uh5x) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7dd9ca66dfb91d20741e34e13959393d4228dd/drake/systems/lcm/lcm_subscriber_system.cc#L151)):*
> ```cpp
>   std::unique_lock<std::mutex> lock(received_message_mutex_);
>   const int received_message_count = received_message_count_;
>   lock.unlock();
> ```

This explicit release of a lock -- where the lock variable's scope extends throughout the (long) method but doesn't actually hold the lock -- is too confusing and brittle.

One possible fix:
```c++
const int received_message_count = [this]() {
    std::unique_lock<std::mutex> lock(received_message_mutex_);
    return received_message_count_;
}();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/lcm/lcm_subscriber_system.cc, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-Kw0HPPC9gTMMD_9qBb2:-Kw0k2hkvOQE_cE4DohH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2c7dd9ca66dfb91d20741e34e13959393d4228dd/drake/systems/lcm/lcm_subscriber_system.cc#L151)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This explicit release of a lock -- where the lock variable's scope extends throughout the (long) method but doesn't actually hold the lock -- is too confusing and brittle.

One possible fix:
```c++
const int received_message_count = [this]() {
    std::unique_lock<std::mutex> lock(received_message_mutex_);
    return received_message_count_;
}();
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7217#-:-Kw0kaCTHwLwP7bRs3cu:bnfp4nl)*

**Pull request merged**
