### PR TITLE
Kuka ik planning

### PR DESCRIPTION
**Pull request by patmarion**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4118)

### CODE REVIEW

**Comment by patmarion** [comment]
+@sammy-tri for feature review

opening this PR now so we can start review and discuss how this should land.  I think the new director app and related files in examples/kuka dir will continue evolving, but enough people are using it now that it should probably be in master.

This PR mostly just adds new files to support the director ik app, but it also makes some changes to existing files:

  - changes published time in LCM to microseconds
  - changes the base link name in the urdf

**Comment by patmarion** [comment]
Oops, looks like my change to the urdf may have broken this matlab test:

https://drake-cdash.csail.mit.edu/testDetails.php?test=4431030&build=192017

@liangfok are you familiar with this test?  Do you know why renaming the base joint from "world" to "base" would break this test?

**Comment by liangfok** [comment]
Looking in https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/systems/plants/test/compareParsers.m#L23, there is logic that skips comparing the parsers using URDFs that contain world links. Since you've modified `iiwa14_no_collision.urdf` to not contain a `world` link, it is now trying to run a comparison using it.

This looks relevant: https://github.com/RobotLocomotion/drake/issues/2175

**Comment by sammy-tri** [comment]
(still need to do some more review of a couple files, checkpointing current thoughts)

---

Reviewed 5 of 10 files at r1.
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJjPgkh5aLSlLqvr2u:-KWJjPgkh5aLSlLqvr2v:b-p881gz) (no related file):*
For the time unit change, should we also rename to utime when we change the units?  We should definitely update the comments in the lcm files to match (they currently say milliseconds).  We'll need to make a corresponding update to https://github.com/RobotLocomotion/drake-iiwa-driver, but I don't think anything will actually break if Drake and the driver disagree on the units temporarily.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJkVpw53rvrAdoy9P_:-KWJkVpxHdLPiCyKA7P_:b-2ykmbh) (no related file):*
Do we think in the future each robot will need it's own python "main" to launch a slightly custom director?

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJk639oGpftvY_RtGj:-KWJk63Almd7-ZUF9YAC:bvgjoll) ([raw file](https://github.com/robotlocomotion/drake/blob/230ae5e2e99889fb9d51b0ea30577e2d3fd7f9ee/drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf#L40)):*
> ```XML
>   </material>
>   
>   <link name="base"/>
> ```

Does this make the comment above out of date?  Also it would make this file out of sync with iiwa14.urdf.

What's the practical effect of renaming the link?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-:-KWJkg99Mh8tYVvQGhrg:bio04d5)*

**Comment by liangfok** [comment]
I now recall some more historical details...

Originally, Drake's C++ and MATLAB URDF parsers did _not_ support URDFs containing `world` bodies. This became a problem when PR #2163 included a URDF with a `world` body. To resolve this issue, I generalized Drake's C++ URDF parser to support world bodies in #2171, but did not generalize Drake's MATLAB URDF parser. Instead, #2171 simply modifies the MATLAB URDF parser to throw an exception if the URDF contains a `world` link. I did this because our goal was to migrate to C++ Drake and to provide thin MATLAB wrappers.

All this being said, I suspect the change in https://github.com/RobotLocomotion/drake/pull/4118/files#diff-60904d20644bd50d71e5c49ae546700f may have introduced a bug where `base_joint` is still connected to  `world` rather than `base`.

**Comment by patmarion** [comment]
Oops, duh, yeah i forgot to update the parent link in the base_joint tag.  I'll push an update and maybe that will resolve the problem.

**Comment by patmarion** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJjPgkh5aLSlLqvr2u:-KWJqIn7PvmTeWyVxbnq:bn6qerg) (no related file):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> For the time unit change, should we also rename to utime when we change the units?  We should definitely update the comments in the lcm files to match (they currently say milliseconds).  We'll need to make a corresponding update to https://github.com/RobotLocomotion/drake-iiwa-driver, but I don't think anything will actually break if Drake and the driver disagree on the units temporarily.
</details>
yes, i think it's worth rename the field to utime instead of timestamp. thanks.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJkVpw53rvrAdoy9P_:-KWJqaUczSpsCo0DCZ9r:b5ss5ch) (no related file):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Do we think in the future each robot will need it's own python "main" to launch a slightly custom director?
</details>
Ideally, no.  The main reason for the custom app is to add the code for the kuka status message to display sim time in the status bar.  Otherwise, the app is generic.  Eventually all the custom kuka features can be moved into a module, and enabled within a generic application using the json config file.  But for now, this app file will be a nice sandbox, a place to insert more code that is specific to our custom application, for example, the schunk driver.

The way things are handled in openhumanoids is: director runs a startup.py which contains *everything* and the config file switch certain features on/off.  With this method, the app supports all kinds of robots, but it's still improving.  Drake can't launch this app though, because it has more dependencies than drake has available.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJk639oGpftvY_RtGj:-KWJqRgcM7gUgI_1Wboy:b-17hxkp) ([raw file](https://github.com/robotlocomotion/drake/blob/230ae5e2e99889fb9d51b0ea30577e2d3fd7f9ee/drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf#L40)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Does this make the comment above out of date?  Also it would make this file out of sync with iiwa14.urdf.
> 
> What's the practical effect of renaming the link?
</details>
i pushed a commit to fix the parent link name and remove the comment.

I explained the reason for the name change in my commit message.  The commit message is:


    change name of base link and joint in iiwa urdf file
    
    By convention, director wants the base joint to be named 'base'.
    In the future we could add code to director to support arbitrary names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
@sammy-tri I pushed more changes so I think I've addressed everything from your review.  I know you have other meetings going on today, but if you get a chance I think you could complete your review now, thanks!

**Comment by sammy-tri** [comment]
Reviewed 1 of 10 files at r1, 9 of 10 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJkVpw53rvrAdoy9P_:-KWZoPSshh5wSi94VStV:bsdmx7m) (no related file):*
<details><summary><i>Previously, patmarion (Pat Marion) wrote…</i></summary>
> Ideally, no.  The main reason for the custom app is to add the code for the kuka status message to display sim time in the status bar.  Otherwise, the app is generic.  Eventually all the custom kuka features can be moved into a module, and enabled within a generic application using the json config file.  But for now, this app file will be a nice sandbox, a place to insert more code that is specific to our custom application, for example, the schunk driver.
> 
> The way things are handled in openhumanoids is: director runs a startup.py which contains *everything* and the config file switch certain features on/off.  With this method, the app supports all kinds of robots, but it's still improving.  Drake can't launch this app though, because it has more dependencies than drake has available.
</details>
OK.  It might be worth adding a comment to this effect to director_ik_app.py so anyone who takes a look has a better idea of the longer term goal.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZp4UBW3dEetV5xAwL:-KWZp4UBW3dEetV5xAwM:b-jo2r46) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L64)):*
> ```cpp
>     int cur_plan_number = plan_number_;
>     int64_t cur_time_ms = -1;
>     int64_t start_time_ms = -1;
> ```

start_time_ms really has microseconds now, I think?

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZowY2zHGYzPc-uWsk:-KWZowY2zHGYzPc-uWsl:bfykmap) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L68)):*
> ```cpp
>     // Initialize the timestamp to an invalid number so we can detect
>     // the first message.
>     iiwa_status_.utime = cur_time_ms;
> ```

cur_time_ms doesn't describe the contents of the variable very well anymore

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZosXxonWYKnI1oc4e:-KWZosXy7Ia3lpHnXPHg:b-5nyw3o) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L96)):*
> ```cpp
> 
>         const double cur_traj_time_s =
>             static_cast<double>(cur_time_ms - start_time_ms) / 1e3;
> ```

I think this 1e3 is probably wrong now?

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJk639oGpftvY_RtGj:-KWZpaPYKTWap1oagy72:blvxxad) ([raw file](https://github.com/robotlocomotion/drake/blob/230ae5e2e99889fb9d51b0ea30577e2d3fd7f9ee/drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf#L40)):*
<details><summary><i>Previously, patmarion (Pat Marion) wrote…</i></summary>
> i pushed a commit to fix the parent link name and remove the comment.
> 
> I explained the reason for the name change in my commit message.  The commit message is:
> 
> 
>     change name of base link and joint in iiwa urdf file
>     
>     By convention, director wants the base joint to be named 'base'.
>     In the future we could add code to director to support arbitrary names.
</details>
We should still probably keep the two urdf's in sync?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
Review status: 11 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZp4UBW3dEetV5xAwL:-KW_tRM-jfy_j4JgqiJ3:babd9e4) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L64)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> start_time_ms really has microseconds now, I think?
</details>
fixed, thanks

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZowY2zHGYzPc-uWsk:-KW_tTaNCcohkrpWlfTj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L68)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> cur_time_ms doesn't describe the contents of the variable very well anymore
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWZosXxonWYKnI1oc4e:-KW_ta-lOHlz0_ge5Lch:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b0a3bd0bf471be5d722f6d573ffbf9c972fbd4f7/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L96)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think this 1e3 is probably wrong now?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWJk639oGpftvY_RtGj:-KW_umSS23oCqjnQA2lq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/230ae5e2e99889fb9d51b0ea30577e2d3fd7f9ee/drake/examples/kuka_iiwa_arm/urdf/iiwa14_no_collision.urdf#L40)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> We should still probably keep the two urdf's in sync?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
@sammy-tri if you have some time today to swing through this one more time that would be great, thank you!

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWmxniZZpc4mW4kifNa:-KWmxni_dS3LsRMLO441:b-2nzed1) ([raw file](https://github.com/robotlocomotion/drake/blob/0a2d8ea9a260072c88428e15f716b3e8d546c4dd/drake/examples/kuka_iiwa_arm/director_ik_app.py#L1)):*
> ```Python
> from director import mainwindowapp
> ```

This could probably use a comment about how to correctly run it...  I was initially confused by the lack of a #! line until I realized it probably only works under directorPython.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWmxIyZ-LaaPQSTrd4Z:-KWmxIy_YoxZAjPmtABg:bnvyg88) ([raw file](https://github.com/robotlocomotion/drake/blob/0a2d8ea9a260072c88428e15f716b3e8d546c4dd/drake/examples/kuka_iiwa_arm/director_ik_app.py#L19)):*
> ```Python
>         statusBar.addPermanentWidget(self.label)
> 
>         self.sub = lcmUtils.addSubscriber('IIWA_STATUS', lcmdrake.lcmt_iiwa_status, self.onIiwaStatus)
> ```

BTW Drake doesn't appear to have an official python style guide yet (odd), but PEP8 specifiec a 79 character line limit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWmxniZZpc4mW4kifNa:-KWn2COwULTFygquaS3q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a2d8ea9a260072c88428e15f716b3e8d546c4dd/drake/examples/kuka_iiwa_arm/director_ik_app.py#L1)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> This could probably use a comment about how to correctly run it...  I was initially confused by the lack of a #! line until I realized it probably only works under directorPython.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWmxIyZ-LaaPQSTrd4Z:-KWn2EE0cF167hFqQvei:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a2d8ea9a260072c88428e15f716b3e8d546c4dd/drake/examples/kuka_iiwa_arm/director_ik_app.py#L19)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW Drake doesn't appear to have an official python style guide yet (odd), but PEP8 specifiec a 79 character line limit.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
thanks @sammy-tri all fixed.  ready when you are.

**Comment by liangfok** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn4dpvl9TcZ3NNv5gV:-KWn4dpwjszaweJiU6sX:bqsl4xe) (no related file):*
We may have previously discussed the questions below, but just to be sure:

Since Director depends on Drake, does it make sense for Director's configuration files to be in Drake's repository? Wouldn't it be cleaner for Director's configuration files to be in Director's repository, maybe in an examples sub-directory?

Note that the new code introduced by this PR is not covered by Drake's unit tests. Is it covered by Director's unit tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn4dpvl9TcZ3NNv5gV:-KWn6-XcBczVfSUvn2gX:b1iymi2) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> We may have previously discussed the questions below, but just to be sure:
> 
> Since Director depends on Drake, does it make sense for Director's configuration files to be in Drake's repository? Wouldn't it be cleaner for Director's configuration files to be in Director's repository, maybe in an examples sub-directory?
> 
> Note that the new code introduced by this PR is not covered by Drake's unit tests. Is it covered by Director's unit tests?
</details>
No, I don't think it makes sense to put kuka specific files into Director, at least not yet.  I think it makes sense for it to be in the examples/kuka directory in drake.

No, the director_ik_app.py is not covered by director's unit tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
waiting on @liangfok and @sammy-tri to return for review, thanks!

**Comment by liangfok** [comment]
Reviewed 2 of 10 files at r1, 8 of 10 files at r2, 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn4dpvl9TcZ3NNv5gV:-KWn7f5Eh381DyiCpmLG:bjubwsk) (no related file):*
<details><summary><i>Previously, patmarion (Pat Marion) wrote…</i></summary>
> No, I don't think it makes sense to put kuka specific files into Director, at least not yet.  I think it makes sense for it to be in the examples/kuka directory in drake.
> 
> No, the director_ik_app.py is not covered by director's unit tests.
</details>
@patmarion: Thanks for the response. Can you provide more details on why it makes sense for Director-specific configuration files to be located in `drake/examples/kuka_iiwa_arm`? Is it because the code in this directory is already dependent on Drake (i.e., not part of Drake) so it's not too much of a stretch to make it also dependent on Director? I'm just concerned that we're creating a cyclic dependency where code in Drake depends on Director and vice versa.

Maybe one solution is to pull out Drake's examples into a separate project that's dependent on both Drake and Director? This may be the cleanest solution and it would generalize to support other externals like ROS.

---

*[drake/examples/kuka_iiwa_arm/director_config.json, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn66Qkga-NNhnOJPYd:-KWn66Qkga-NNhnOJPYe:b-6mvt3a) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_config.json#L13)):*
> ```JSON
> 
>   "teleopJointGroups" : [
>     { "name" : "Left Arm",
> ```

BTW, is there an issue tracking the generalization of this to support just "Arm" since the KUKA IIWA is just one arm? Or, maybe just add a TODO comment?

---

*[drake/examples/kuka_iiwa_arm/director_config.json, line 55 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6OCCFsnu5uB8T59Q:-KWn6OCCFsnu5uB8T59R:b-6xg1dg) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_config.json#L55)):*
> ```JSON
>   "fixedPointFile" : "kuka_iiwa_fp.csv",
>   "postureDatabaseFile" : "stored_poses.json",
> ```

BTW, why is there an extra blank line here?

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 8 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6WsAcdfGJvBtp82x:-KWn6WsAcdfGJvBtp82y:b-sxf179) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_ik_app.py#L8)):*
> ```Python
> from director import mainwindowapp
> from director import robotsystem
> from director import applogic
> ```

BTW, can this section be alphabetically sorted?

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_signal_scope.py, line 4 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6sZxqTk07Q5tBgJE:-KWn6sZxqTk07Q5tBgJF:b-445ffk) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/kuka_iiwa_signal_scope.py#L4)):*
> ```Python
> import colorsys
> ```

BTW, why so many blank lines here?

(Same comment below.)

---

*[drake/examples/kuka_iiwa_arm/kuka_sim.pmd, line 14 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn77DH2VpyNiSJvVW1:-KWn77DH2VpyNiSJvVW2:bnt62r0) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/kuka_sim.pmd#L14)):*
> ```
> 
>   cmd "2.state_lcm_translator" {
>     exec = "DRC_BASE=/none build/install/bin/directorPython drake/examples/kuka_iiwa_arm/kuka_iiwa_state_translator.py --director_config drake/examples/kuka_iiwa_arm/director_config.json";
> ```

BTW, what is "DRC_BASE"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
Can we please merge this PR now, and then address all the remaining issues over the next several months?  I expect there will be a lot of active development here, so there's no need to nitpick every bit of it right now.  I think all of this code in examples/kuka is work in progress.

If you don't think that is practical, I will close this PR and I will develop my work outside of drake.

**Comment by patmarion** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/director_config.json, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn66Qkga-NNhnOJPYd:-KWn_xc0zpq6MSSmcJZz:buuvdo4) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_config.json#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, is there an issue tracking the generalization of this to support just "Arm" since the KUKA IIWA is just one arm? Or, maybe just add a TODO comment?
</details>
no there isn't a tracking issue

---

*[drake/examples/kuka_iiwa_arm/director_config.json, line 55 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6OCCFsnu5uB8T59Q:-KWna1Cyk9h-nVorLsoa:b-71odim) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_config.json#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, why is there an extra blank line here?
</details>
just a break between sections for readability

---

*[drake/examples/kuka_iiwa_arm/director_ik_app.py, line 8 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6WsAcdfGJvBtp82x:-KWnaDGr3YfgewUXV6SF:b1i4qwy) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/director_ik_app.py#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, can this section be alphabetically sorted?
</details>
maybe that can be done in future PRs

---

*[drake/examples/kuka_iiwa_arm/kuka_sim.pmd, line 14 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn77DH2VpyNiSJvVW1:-KWnaY6FXYvvDvA0R96s:bcqklfh) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/kuka_sim.pmd#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, what is "DRC_BASE"?
</details>
an environment variable used by openhumanoids

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_signal_scope.py, line 4 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-KWn6sZxqTk07Q5tBgJE:-KWnanqrd6YIcnS0XgnD:b5nm8b8) ([raw file](https://github.com/robotlocomotion/drake/blob/452d4eb0f2fa293a8eea3fdac29993762321cac6/drake/examples/kuka_iiwa_arm/kuka_iiwa_signal_scope.py#L4)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, why so many blank lines here?
> 
> (Same comment below.)
</details>
just spacing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118)*

**Comment by patmarion** [comment]
ok for platform review?

**Comment by liangfok** [comment]
Yes, after a F2F discussion with @david-german-tri, we agree to allow this PR to merge. This is in part because (1) the cyclic-dependencies reside only in Python files that are not installed and (2) this code is in `drake/examples/`.

@sammy-tri, what do you think?

**Comment by patmarion** [comment]
Thanks for understanding.  I think examples/kuka should be treated like an experimental sandbox.  This folder will accumulate code that is designed to work in simulation and on hardware.  It's going to take a lot of work-in-progress commits to make that happen, and I think it will be best if we allow for incremental progress to be merged.

The examples/kuka folder is the only instance I know of where we explore how drake-distro standalone can be used to operate a hardware robot (as opposed to using tools like openhumanoids or ROS).  It's possible that we will eventually decide it is not practical, and then these files can be moved outside of drake and into a different repo.

**Comment by patmarion** [comment]
I think there was a proposal that the development of the Valkyrie controller could be moved inside drake, but the larger operational stack for valkyrie requires other pieces from openhumanoids.

**Comment by liangfok** [comment]
Got it. Thanks.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4118#-:-KWnoyY8cE8gs0N7hBXo:bnfp4nl)*

**Pull request merged**
