### PR TITLE
[framework] Add System::Clone

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18212.

\CC @adeeb10abbas @EricCousineau-TRI FYI

+@rpoyner-tri for feature review, please.
+@sherm1 for platform review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-:-NN3W3vg1MqE_OkEdtoV:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[`systems/framework/system.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3VmNZE-VfNFUnwNsL:-NN3VmNZE-VfNFUnwNsM:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/ec41ed505917486c4688f13b06e5a51b712385f2/systems/framework/system.cc#L46)):*
> ```cpp
>   }
> 
>   // In any anything went wrong, throw exception.
> ```

typo?



_Suggestion:_
```cpp
If
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-:-NN3l5d-8aLLhc7KhHBh:b8qx53o)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`systems/framework/system.h` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3cQQP7CW-bZQGIcJR:-NN3cQQP7CW-bZQGIcJS:bqtr67s) ([raw file](https://github.com/RobotLocomotion/drake/blob/7521396ea1dab1b87881d1fa931af6f5320793c4/systems/framework/system.h#L62)):*
> ```objc
> 
>   Even though the cloned system is functionally identical, any contexts created
>   for this system are not compatible with the cloned system, and vice versa.
> ```

BTW probably worth mentioning  `Context::SetTimeStateAndParametersFrom()` here. I expect that transferring the Context would be a common desire.

(We could also consider a `context.CloneForNewSystem(const System&)` that would call context.Clone() and context.set_system_id() after some size checks.)
___
*[`systems/framework/system.h` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3bA9_-OvuPbMinj4E:-NN3bA9_-OvuPbMinj4F:b6jkbx2) ([raw file](https://github.com/RobotLocomotion/drake/blob/7521396ea1dab1b87881d1fa931af6f5320793c4/systems/framework/system.h#L76)):*
BTW the concrete System type is preserved by the member function also (presumably), though we get a base System handle to it. Consider something like 
> In contrast with the instance member function which returns a base class-typed pointer to the cloned object, the pointer returned here retains the type of the cloned object.
___
*[`systems/framework/system.h` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3jFmk1A4xgEigBBjG:-NN3fkCo6QmiX8_QBI1g:b-e99a9x) ([raw file](https://github.com/RobotLocomotion/drake/blob/7521396ea1dab1b87881d1fa931af6f5320793c4/systems/framework/system.h#L76)):*
> ```objc
>   In contrast with the instance member function `sys.Clone()`, this static
>   member function `Clone(sys)` is useful for C++ users to preserve the static
>   type of the system being cloned.
> ```

FYI Oh rats I was going to say we could do this with a covariant override but that doesn't work since `unique_ptr<Derived>` isn't covariant with `unique_ptr<Base>` :(

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/framework/system.h` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3cQQP7CW-bZQGIcJR:-NN3rb5zEYmncsHOlNHl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7521396ea1dab1b87881d1fa931af6f5320793c4/systems/framework/system.h#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW probably worth mentioning  `Context::SetTimeStateAndParametersFrom()` here. I expect that transferring the Context would be a common desire.

(We could also consider a `context.CloneForNewSystem(const System&)` that would call context.Clone() and context.set_system_id() after some size checks.)


</blockquote></details>

Done.
___
*[`systems/framework/system.h` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18687#-NN3bA9_-OvuPbMinj4E:-NN3rc0iE0wRPR5-9Q8C:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7521396ea1dab1b87881d1fa931af6f5320793c4/systems/framework/system.h#L76)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the concrete System type is preserved by the member function also (presumably), though we get a base System handle to it. Consider something like 
> In contrast with the instance member function which returns a base class-typed pointer to the cloned object, the pointer returned here retains the type of the cloned object.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18687)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
