### PR TITLE
Move endless and infinite code fully into dev

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The "endless" and "infinite" concepts are not useful long-term except insofar as a starting point for new PRs that do it correctly, and to run demos in the meantime.

Some was already in dev; the portions that were non-dev were too optimistic that they would need future needs, and were overly coupled to demo-only considerations.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5237)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review please.  Probably doesn't need feature review since its mostly just build system edits and related detritus.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5237#-:-KdTIU-NJaozegmjff1e:b-axq85i)*

**Comment by jwnimmer-tri** [comment]
Also +@soonho-tri for mentoring.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5237#-:-KdVsWJC0mWE-GjYt9cz:bpjta2j)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5237#-:-KdW6avIVP7Pil2903NA:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5237#-:-KdW70W8zq3MhmRDAaHS:bnfp4nl)*

**Pull request merged**
