### PR TITLE
[geometry] Move render_gl into new directory structure

### LINKED ISSUE #17379: Reorganize geometry/render_gl
As we created more RenderEngine implementations over time, we decided on an updated naming convention and factory pattern.  We should update `drake/geometry/render/gl_renderer` to conform to the new pattern.

By way of example, in #17169 and #17377 we did this task for the VTK render engine.  The GL change will be a simpler still, because we have already marked enough of it "internal", so fewer deprecation shims will be required.

Goals:
- `drake/render_gl/render_engine_gl_params.h` is a move from its prior home.
- `drake/render_gl/factory.h` is the new filename for the factory function.
- `drake/render_gl/internal_...` is everything else (prepend "internal" to the name).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17379.

I've confirmed locally that a full Anzu build and test passes vs this PR.

Note that this PR will be a merge commit, not squashed -- in order to preserve git history.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17410)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2 with minor nits about additional deprecations

> Reviewed 30 of 34 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17410#-:-N4niTeT1k1TWrT3XLOA:bii9dy7)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`geometry/render/gl_renderer/BUILD.bazel` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nh7OhEnmeiIIGpO3J:-N4nh7Oi8g-IL3EPcZFO:b-p3pcva) ([raw file](https://github.com/robotlocomotion/drake/blob/d6cdc7ebd13bd877b3d1926032ec2175a4549d3f/geometry/render/gl_renderer/BUILD.bazel#L11)):*
> ```Starlark
> 
> drake_cc_package_library(
>     name = "gl_renderer",
> ```

nit Unclear if this should be marked as deprecated.
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nhnqD1aLf3EJrNv-l:-N4nhnqD1aLf3EJrNv-m:b-1iy6o2) ([raw file](https://github.com/robotlocomotion/drake/blob/d6cdc7ebd13bd877b3d1926032ec2175a4549d3f/geometry/render_gl/internal_render_engine_gl.h#L27)):*
> ```objc
> namespace geometry {
> namespace render {
> namespace internal {
> ```

nit `RenderEngineGl` was previously public; unclear if public alias should be deprecated, or PR should be marked as breaking, or neither?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI)

___
*[`geometry/render/gl_renderer/BUILD.bazel` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nh7OhEnmeiIIGpO3J:-N4njvfIDFmEvETW0_5_:burebcf) ([raw file](https://github.com/robotlocomotion/drake/blob/d6cdc7ebd13bd877b3d1926032ec2175a4549d3f/geometry/render/gl_renderer/BUILD.bazel#L11)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear if this should be marked as deprecated.
</blockquote></details>

OK typically for C++ code we only deprecate the typenames or header files, not the bazel targets.  The C++ messages are sufficient on their own; bazel messages would be superfluous.
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nhnqD1aLf3EJrNv-l:-N4nkJpKDL77iizValtN:b-c14sb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d6cdc7ebd13bd877b3d1926032ec2175a4549d3f/geometry/render_gl/internal_render_engine_gl.h#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `RenderEngineGl` was previously public; unclear if public alias should be deprecated, or PR should be marked as breaking, or neither?
</blockquote></details>

On master currently, the `render_engine_gl.h` header file is not installed and the `:render_engine_gl` bazel target is `visibility:private`.  I don't think this is public in any other sense?  It's true that it's namespace has changed, but I don't think anyone had access to it anyway.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17410)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform), base commit is latest master (waiting on @jwnimmer-tri)

___
*[`geometry/render/gl_renderer/BUILD.bazel` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nh7OhEnmeiIIGpO3J:-N4nm9JHAPb-_iZ18cTJ:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/b76b519a18bedbd4e8aec4a965380db6af5bbb5f/geometry/render/gl_renderer/BUILD.bazel#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK typically for C++ code we only deprecate the typenames or header files, not the bazel targets.  The C++ messages are sufficient on their own; bazel messages would be superfluous.
</blockquote></details>

OK Sounds good!
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nhnqD1aLf3EJrNv-l:-N4nmIIG3Se9eE1C5Dw5:b-xo5ou3) ([raw file](https://github.com/robotlocomotion/drake/blob/b76b519a18bedbd4e8aec4a965380db6af5bbb5f/geometry/render_gl/internal_render_engine_gl.h#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On master currently, the `render_engine_gl.h` header file is not installed and the `:render_engine_gl` bazel target is `visibility:private`.  I don't think this is public in any other sense?  It's true that it's namespace has changed, but I don't think anyone had access to it anyway.
</blockquote></details>

OK Ah, missed that it wasn't public via install.

It looks publicly accessible via Bazel via transitive dep `:render_engine_gl_factory => :render_engine_gl`; it looks like header was still public in Bazel.
But yeah, fine going with "meant to be private".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17410)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform), base commit is latest master (waiting on @jwnimmer-tri)

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17410#-N4nhnqD1aLf3EJrNv-l:-N4nnlZ48sMxIfl87vCD:bdnz3hu) ([raw file](https://github.com/robotlocomotion/drake/blob/b76b519a18bedbd4e8aec4a965380db6af5bbb5f/geometry/render_gl/internal_render_engine_gl.h#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, missed that it wasn't public via install.

It looks publicly accessible via Bazel via transitive dep `:render_engine_gl_factory => :render_engine_gl`; it looks like header was still public in Bazel.
But yeah, fine going with "meant to be private".
</blockquote></details>

Even in that case, I think `interface_deps` vs `deps` was actively preventing mis-use.  Anyway, seems fine either way.

**Pull request merged**
