### PR TITLE
Reverse the suffix semantics of DrakeLcm::SubscribeAllChannels

### PR DESCRIPTION
**Pull request by ggould-tri**
This PR proposes to reverse the semantics of DrakeLcm::SubscribeAllChannels
with resepect to channel suffixes.  As documented and tested by my previous
PR, SubscribeAllChannels prior to this PR provides the full, suffix-included
name of the channel.

I assert the prior behaviour was wrong for two reasons:

* First, a caller likely suspects that the channel passed to Subscribe
  and the channel received by SubscribeAllChannels are the same entity.
  For one to be qualified and the other not is a surprise.

* Second, this is very troublesome for clients that receive a DrakeLcm as a
  DrakeLcmInterface, as they cannot determine the suffix with which the
  DrakeLcm was constructed (nor could they even if we added an accessor on
  the subclass).  Thus they cannot know the publisher's intended channel
  name.

This is of course a fairly marginal use case:  SubscribeAllChannels is used
mostly in meta-LCM applications such as logging all messages (or, in my case,
a crude active proxy).  However these meta-LCM applications do care about
the detailed semantics.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think this is basically correct, except that discarding wrongly-titled messages should be an expected condition (no warning; could debug-log if we like).

(Also needs a little bit of tune-ups for test coverage and substr OOB checking.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

___
*[`lcm/drake_lcm.cc` line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6KMGc4Asa56BeQuhAA:-N6KMGc4Asa56BeQuhAB:b6madkw) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd397a121fdc79e38ef8ab0b2dad8fe82822a99/lcm/drake_lcm.cc#L294)):*
> ```cpp
>                            const void* data, int length) {
>           // TODO(ggould-tri) Use string_view::suffix() once we have C++20.
>           if (channel.substr(channel.length() - suffix.length()) == suffix) {
> ```

nit This has OOB issues when the rx'd channel name is shorter than the suffix.  Needs a few unit tests to that end.
___
*[`lcm/drake_lcm.cc` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6KLo5U-llf2u2STWMK:-N6KLo5VDEADYstJaBUX:b-ni9600) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd397a121fdc79e38ef8ab0b2dad8fe82822a99/lcm/drake_lcm.cc#L299)):*
> ```cpp
>             drake::log()->warn("DrakeLcm with suffix {} received message on"
>                                " channel {}, which lacks the suffix.",
>                                suffix, channel);
> ```

nit I can see the point of not being completely silent here, but warning on every message runs the risk of flooding the user with console log messages at 200Hz or worse.

One easy resolution would be to demote this to debug-only.

If you want to get fancy, you could `static const logging::Warn log_once(...);` with the same(ish) message, i.e., just giving the first example of a problem.

Another option would be to throw an exception, if we think this is a severe enough misconfiguration and not a valid use case.
___
*[`lcm/drake_lcm_params.h` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6KMcQmEz5JSX9xG4JG:-N6KMcQn7N7l1qkyVENC:b-c5yye) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd397a121fdc79e38ef8ab0b2dad8fe82822a99/lcm/drake_lcm_params.h#L28)):*
> ```objc
>   The callback of DrakeLcm::SubscribeAllChannels() will receive the "base"
>   channel name WITHOUT this suffix; messages received without the configured
>   suffix will generate a warning.
> ```

nit (per cc file discusison)



_Suggestion:_
```objc
debug log message
```

**Review by ggould-tri — COMMENTED** [review]
Yeah, it's clear I'm not getting back to this PR for a little while, so you can take it .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470#-:-N6Oy5SM9lSEtujbpl6F:b1dauv4)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`lcm/drake_lcm.cc` line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6KMGc4Asa56BeQuhAA:-N6j6a6P72kNYThC6KKt:b-f0x5jo) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd397a121fdc79e38ef8ab0b2dad8fe82822a99/lcm/drake_lcm.cc#L294)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This has OOB issues when the rx'd channel name is shorter than the suffix.  Needs a few unit tests to that end.
</blockquote></details>

Done.  (Unit testing is difficult, not worth it.)
___
*[`lcm/drake_lcm.cc` line 299 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6KLo5U-llf2u2STWMK:-N6j6dI_5-8XlqPogrkW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fd397a121fdc79e38ef8ab0b2dad8fe82822a99/lcm/drake_lcm.cc#L299)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I can see the point of not being completely silent here, but warning on every message runs the risk of flooding the user with console log messages at 200Hz or worse.

One easy resolution would be to demote this to debug-only.

If you want to get fancy, you could `static const logging::Warn log_once(...);` with the same(ish) message, i.e., just giving the first example of a problem.

Another option would be to throw an exception, if we think this is a severe enough misconfiguration and not a valid use case.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. Something doesn't look quite right to me (see below).

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470#-:-N6jJ686Cx-2H1YzPrKQ:b-3lj7wf)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`lcm/drake_lcm.cc` line 302 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jIdL816hepYFehTQj:-N6jIdL816hepYFehTQk:b-96m1a8) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/drake_lcm.cc#L302)):*
> ```cpp
>                                 suffix, channel);
>           }
>           handler(channel, data, length);
> ```

nit; The documentation on the params suggests that if I have a suffix and the channel doesn't, that the message "will be discarded". This doesn't look like discarding.

Either the doc is wrong, this code, or my understanding.

Resolving this may require extending the unit test to confirm discarding.
___
*[`lcm/drake_lcm_params.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jGcPhA2D86gnBdYzL:-N6jGcPiD96KkfMHkyxV:b-rwv6mp) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/drake_lcm_params.h#L27)):*
BTW I have an editorial concern about this phrasing. Part of it comes from not being LCM savvy, so I don't have much experience to project the current text onto.

1. The first clause says the suffix belongs to a "channel". The second suggests that a *message* has the suffix.
2. The first clause talks about what the callback will see. The second seems to be a description of `DrakeLcm`. The exact implications for the callback have to be inferred (e.g., should the callback be discarding things?)

I'd propose:

> The callback of DrakeLcm::SubscribeAllChannels() will receive the *base" channel name WITHOUT this suffix. The callback will only be invoked for messages coming from channels with this suffix; messages from other channels will be discarded.
___
*[`lcm/test/drake_lcm_test.cc` line 391 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jEjWAAGjqVz_MIdRv:-N6jEjWBDsCenM7wb-pg:bwwhqhw) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/test/drake_lcm_test.cc#L391)):*
> ```cpp
>   dut_ = std::make_unique<DrakeLcm>(params);
> 
>   // SubscribeAll using Drake LCM, expecting to see the fully qualified
> ```

nit: This comment appears to have degraded in value.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`lcm/drake_lcm.cc` line 302 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jIdL816hepYFehTQj:-N6jPqQ4BP42SP5zxu8D:b-4292bl) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/drake_lcm.cc#L302)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit; The documentation on the params suggests that if I have a suffix and the channel doesn't, that the message "will be discarded". This doesn't look like discarding.

Either the doc is wrong, this code, or my understanding.

Resolving this may require extending the unit test to confirm discarding.
</blockquote></details>

Oops.  Definitely wrong.

I'd tried adding a unit test for this before, but failed.  (Sending malformed traffic is not easy!)

I'll give it another whirl, but might still have to give up again.
___
*[`lcm/drake_lcm_params.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jGcPhA2D86gnBdYzL:-N6jS_L21Tsl2Wqg9EIL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/drake_lcm_params.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I have an editorial concern about this phrasing. Part of it comes from not being LCM savvy, so I don't have much experience to project the current text onto.

1. The first clause says the suffix belongs to a "channel". The second suggests that a *message* has the suffix.
2. The first clause talks about what the callback will see. The second seems to be a description of `DrakeLcm`. The exact implications for the callback have to be inferred (e.g., should the callback be discarding things?)

I'd propose:

> The callback of DrakeLcm::SubscribeAllChannels() will receive the *base" channel name WITHOUT this suffix. The callback will only be invoked for messages coming from channels with this suffix; messages from other channels will be discarded.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`lcm/drake_lcm.cc` line 302 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17470#-N6jIdL816hepYFehTQj:-N6jUvQB2TFDa_vN77Fz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cefd0007fa779b505406b51648ae5df790fcedf0/lcm/drake_lcm.cc#L302)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  Definitely wrong.

I'd tried adding a unit test for this before, but failed.  (Sending malformed traffic is not easy!)

I'll give it another whirl, but might still have to give up again.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot  linux-focal-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
:lgtm: from me.

\CC @ggould-tri you might want to peek at this again.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17470#-:-N6mzRA79seYEzCA2ryN:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Pull request merged**
