### PR TITLE
solvers: Remove f2c build flavor of SNOPT solver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This has reached its 2019-11-01 deprecation removal date.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12299)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
(I can PR the CMake changes against this branch if you would prefer.)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (tomorrow), please.

@jamiesnape would you like me to let you push the merge button on this (after Sam is done), in order to coordinate with any `drake-ci` changes?

**Comment by jamiesnape** [comment]
CI should be happy already, so you can merge whenever reviews are done.

**Pull request merged**
