### PR TITLE
Remove CostShim, introduce Polynomial- and FunctionEvaluator. Add Eva…

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
…luatorBase tests.

This clears up a little bit of technical debt, and is a step towards enabling easier definition of Constraints / Costs composed of multiple evaluators (in a cleaner fashion).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6818)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrCh93o0g_SSDFQqxKl:b-81zjv5)*

**Comment by hongkai-dai** [comment]
:lgtm: Thanks for the patience.

It would be great if you could add a test on `EvaluatorConstraint` in `constraint_test.cc`.

---

Reviewed 10 of 18 files at r1.
Review status: 10 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrICy1HAxfXEVZl_nBN:-KrICy1HAxfXEVZl_nBO:b-m13wm8) ([raw file](https://github.com/robotlocomotion/drake/blob/d0217c98059ab7c67a59f800890a3e0909bb1e04/drake/solvers/constraint.h#L38)):*
> ```objc
>  * should also be some notion of parameterized constraints:  e.g. the
>  * acceleration constraints in the rigid body dynamics are constraints
>  * on vdot and f, but are "parameterized" by q and v.
> ```

This looks great. I am not sure about adding slack variables, but excited if that works!

---

*[drake/solvers/evaluator_base.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrClDW--MBJDVwqH5NL:-KrClDW--MBJDVwqH5NM:bw06etl) ([raw file](https://github.com/robotlocomotion/drake/blob/d0217c98059ab7c67a59f800890a3e0909bb1e04/drake/solvers/evaluator_base.h#L139)):*
> ```objc
>  * An evaluator that may be specified using a callable object.
>  * @tparam F The function / functor's type.
>  * @tparam Base The base class. By default, this is EvaluatorBase, but could be
> ```

No `Base` in the template parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrIEEKcQ5eUZV1wcFMu:bqsjyq6)*

**Comment by EricCousineau-TRI** [comment]
Added the tests in, thanks!

+@sherm1 for platform review, please.

---

Review status: 8 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrICy1HAxfXEVZl_nBN:-KrIH4de0lATdIrHwFxw:b-h51n0n) ([raw file](https://github.com/robotlocomotion/drake/blob/d0217c98059ab7c67a59f800890a3e0909bb1e04/drake/solvers/constraint.h#L38)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This looks great. I am not sure about adding slack variables, but excited if that works!
</blockquote></details>

That was actually carry-over from the previous comments. I've turned them into possible TODOs.

---

*[drake/solvers/evaluator_base.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrClDW--MBJDVwqH5NL:-KrIHgWyYBcxHSk8KDd-:bf7zv3f) ([raw file](https://github.com/robotlocomotion/drake/blob/d0217c98059ab7c67a59f800890a3e0909bb1e04/drake/solvers/evaluator_base.h#L139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No `Base` in the template parameter?
</blockquote></details>

Removed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrIPFbr7uFoS4WLd4mF:bdcvr97)*

**Comment by hongkai-dai** [comment]
Reviewed 8 of 18 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818)*

**Comment by sherm1** [comment]
Platform pass done, PTAL. There are some style guide violations here that I think flow from FunctionTraits (numOutputs, etc.). This PR propagates those to new code. Can those be fixed here instead?

---

Reviewed 16 of 18 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[drake/solvers/constraint.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_2PiB6zeWjsQX_w2:-KrI_2PiB6zeWjsQX_w3:ba35ir9) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L35)):*
> ```objc
>  * problem.
>  *
>  * Constraint is not copyable, nor movable.
> ```

FYI redundant due to macro

---

*[drake/solvers/constraint.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_EikkLF5EdzMGPj5:-KrI_EikkLF5EdzMGPj6:b3xy2va) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L46)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(Constraint)
> 
>   /// Constructs a constraint which has \p num_constraints rows, with input
> ```

BTW can't use backslash for doxygen keywords, please use `@p`. Also, consider using surrounding backticks instead of `@p` to make text easier to read in header.

---

*[drake/solvers/constraint.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_ZxRX30r9BE_-ZX-:-KrI_ZxRX30r9BE_-ZX0:b-cvmbkm) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L67)):*
> ```objc
>   }
> 
>   Constraint(int num_constraints, int num_vars)
> ```

BTW public API needs Doxygen.

---

*[drake/solvers/constraint.h, line 329 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_iNNr5g8ofy2ObBb:-KrI_iNNr5g8ofy2ObBc:b-42m0jx) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L329)):*
> ```objc
> /**
>  * A constraint that may be specified using a callable object.
>  * @tparam F The function / functor's type.
> ```

BTW no such tparam

---

*[drake/solvers/constraint.h, line 338 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_oCRJDcEj10dGCZ4:-KrI_oCRJDcEj10dGCZ5:b-dy3vau) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L338)):*
> ```objc
> 
>   template <typename... Args>
>   EvaluatorConstraint(const std::shared_ptr<EvaluatorType>& evaluator,
> ```

BTW public API needs doxygen.

---

*[drake/solvers/constraint.h, line 346 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_wRwFKFJkkDpICUe:-KrI_wRwFKFJkkDpICUf:bqj2wi9) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L346)):*
> ```objc
>  protected:
>   const EvaluatorType& evaluator() const { return *evaluator_; }
>   void DoEval(const Eigen::Ref<const Eigen::VectorXd>& x,
> ```

BTW better to make these private IMO. Hides them from doxygen.

---

*[drake/solvers/evaluator_base.h, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIShvSBMBStGYOzfNZ:-KrIShvSBMBStGYOzfN_:b-16jffy) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L27)):*
> ```objc
>  * of variables using the Binding<> class.
>  *
>  * EvaluateBase is not copyable, nor movable.
> ```

FYI this is redundant since the macro generates doxygen that says this. Consider removing.

---

*[drake/solvers/evaluator_base.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITPnigq9bQA6KSBqI:-KrITPnigq9bQA6KSBqJ:bw9xj5) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L37)):*
> ```objc
>   // TODO(bradking): consider using a Ref for `y`.  This will require the client
>   // to do allocation, but also allows it to choose stack allocation instead.
>   void Eval(const Eigen::Ref<const Eigen::VectorXd>& x,
> ```

BTW these public interface methods need some Doxygen documentation.

---

*[drake/solvers/evaluator_base.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIV1ft4lce1oJlbIVo:-KrIV1ft4lce1oJlbIVp:bv74yur) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L39)):*
> ```objc
>   void Eval(const Eigen::Ref<const Eigen::VectorXd>& x,
>             // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
>             Eigen::VectorXd& y) const {
> ```

BTW are you violating the GSG here because of a compatibility requirement with something else?

---

*[drake/solvers/evaluator_base.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITYXEYap3PdaRKsPC:-KrITYXEYap3PdaRKsPD:ba2hfi) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L43)):*
> ```objc
>     DoEval(x, y);
>   }
>   // Move this to DifferentiableConstraint derived class if/when we
> ```

BTW TODO needed here?

---

*[drake/solvers/evaluator_base.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITrGWdSsIpyD5k5fR:-KrITrGWdSsIpyD5k5fS:b-5zs74) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L67)):*
> ```objc
> 
>  protected:
>   /// Constructs a evaluator which has \p num_constraints rows, with input
> ```

BTW no parameter named num_constraints

---

*[drake/solvers/evaluator_base.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIU5k1Zk6sJfWpsfhR:-KrIU5k1Zk6sJfWpsfhS:b2pi6x0) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L68)):*
> ```objc
>  protected:
>   /// Constructs a evaluator which has \p num_constraints rows, with input
>   /// variables to Eval a \p num_vars x 1 vector.
> ```

BTW we don't allow backslash for doxygen keywords, please use `@p`. Also, consider using surrounding backtics rather than `@p` to make text easier to read in header (same outcome in doxygen either way).

---

*[drake/solvers/evaluator_base.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVDECf1bMZEK14-OL:-KrIVDECf1bMZEK14-OM:b-ib1oo) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L83)):*
> ```objc
>   virtual void DoEval(const Eigen::Ref<const Eigen::VectorXd>& x,
>                       // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
>                       Eigen::VectorXd& y) const = 0;
> ```

BTW even if Eval() has to use a mutable reference for compatibility, DoEval() doesn't have to -- this should be a pointer.

---

*[drake/solvers/evaluator_base.h, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVR0-Zxtf4UCFrTv8:-KrIVR0-Zxtf4UCFrTv9:be9yhuf) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L94)):*
> ```objc
>   std::string description_;
> };
> /*
> ```

BTW consider a blank line between these classes.

---

*[drake/solvers/evaluator_base.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVj6-AGCmX6kEbmCb:-KrIVj6-AGCmX6kEbmCc:bsl9jel) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L107)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(PolynomialEvaluator)
> 
>   PolynomialEvaluator(const VectorXPoly& polynomials,
> ```

BTW public methods need Doxygen (unless *very* obvious).

---

*[drake/solvers/evaluator_base.h, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIXCneOX--T-0HNZCr:-KrIXCneOX--T-0HNZCs:b9o6x5n) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L133)):*
> ```objc
>   // TODO(eric.cousineau): Consider removing this for thread safety?
>   mutable std::map<Polynomiald::VarType, double> double_evaluation_point_;
>   mutable std::map<Polynomiald::VarType, AutoDiffXd> taylor_evaluation_point_;
> ```

BTW are these just temp variables used within a single function call? If so, that's reasonable but you should make that very clear in the comment. I would suggest giving them uglier names like `double_evaluation_point_temp_` and strictly admonishing future programmers that they must never assume these will persist between method invocations.

---

*[drake/solvers/evaluator_base.h, line 147 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIWR5NymUxKfd1p8-5:-KrIWR5NymUxKfd1p8-6:b-dy3vau) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L147)):*
> ```objc
> 
>   // Construct by copying from an lvalue or rvalue.
>   template <typename TF, typename... Args>
> ```

BTW public API needs doxygen.

---

*[drake/solvers/evaluator_base.h, line 180 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIXxHLLXI9ncTUc3s8:-KrIXxHLLXI9ncTUc3s9:b-l0lr1y) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L180)):*
> ```objc
> 
> template <typename F>
> std::shared_ptr<EvaluatorBase> MakeFunctionEvaluator(F&& f) {
> ```

BTW needs doxygen, ideally including `@relates FunctionEvaluator` so that this shows up in the FunctionEvaluator class doc. Also, FunctionEvaluator class comment should mention that this free function exists and give an example of how to use it.

---

*[drake/solvers/test/evaluator_base_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIYxWd12XHXwhxWQ7k:-KrIYxWd12XHXwhxWQ7l:bnwth01) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/test/evaluator_base_test.cc#L59)):*
> ```cpp
> 
>   int numInputs() const { return 3; }
>   int numOutputs() const { return 3; }
> ```

BTW these are not style guide compatible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrIbfvubxQ6ZWCc1jro:b60btcf)*

**Comment by EricCousineau-TRI** [comment]
I'd prefer to defer refactoring these GSG violations for another PR (as it would touch many files) - I have created #6839 to track that.

---

Review status: 15 of 19 files reviewed at latest revision, 19 unresolved discussions.

---

*[drake/solvers/constraint.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_2PiB6zeWjsQX_w2:-KrWNK3wKHU47JRARM4Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI redundant due to macro
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_EikkLF5EdzMGPj5:-KrWNKziz-QxyXDJrAma:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can't use backslash for doxygen keywords, please use `@p`. Also, consider using surrounding backticks instead of `@p` to make text easier to read in header.
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_ZxRX30r9BE_-ZX-:-KrWNNFbK1XGTSmnv2Qp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L67)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW public API needs Doxygen.
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 329 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_iNNr5g8ofy2ObBb:-KrWNQRTkj7_QOh-iOnQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L329)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW no such tparam
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 338 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_oCRJDcEj10dGCZ4:-KrWPrJRBq_xNLtTR_qg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L338)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW public API needs doxygen.
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 346 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrI_wRwFKFJkkDpICUe:-KrWNv_ZxRgr5HblVnCd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/constraint.h#L346)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW better to make these private IMO. Hides them from doxygen.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIShvSBMBStGYOzfNZ:-KrWO-vw5y3luVp6NOMW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI this is redundant since the macro generates doxygen that says this. Consider removing.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITPnigq9bQA6KSBqI:-KrWO11aSx2w1nrBKqwB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW these public interface methods need some Doxygen documentation.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIV1ft4lce1oJlbIVo:-KrWO1iMAhMTten08Q5w:byw3707) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW are you violating the GSG here because of a compatibility requirement with something else?
</blockquote></details>

Yes, this is for compatibility with the existing code. I will create an issue to remove GSG violations, and follow up on it once we converge on an `EigenPtr<>` convention.

---

*[drake/solvers/evaluator_base.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITYXEYap3PdaRKsPC:-KrWOEbxH1vK34ebp-7v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW TODO needed here?
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrITrGWdSsIpyD5k5fR:-KrWOG9tVkAQ2QN48gII:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L67)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW no parameter named num_constraints
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIU5k1Zk6sJfWpsfhR:-KrWOGqTZAoBQJL5xnNK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW we don't allow backslash for doxygen keywords, please use `@p`. Also, consider using surrounding backtics rather than `@p` to make text easier to read in header (same outcome in doxygen either way).
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVDECf1bMZEK14-OL:-KrWOHo1_klgoS-gbGO3:bloe4ik) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW even if Eval() has to use a mutable reference for compatibility, DoEval() doesn't have to -- this should be a pointer.
</blockquote></details>

I would prefer to minimize the refactoring necessary in this PR. I will incorporate this in the follow-up issue.

---

*[drake/solvers/evaluator_base.h, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVR0-Zxtf4UCFrTv8:-KrWOPfR_lE4I9Z87sRI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider a blank line between these classes.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIVj6-AGCmX6kEbmCb:-KrWOQtHsLrh8zHBuKn_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L107)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW public methods need Doxygen (unless *very* obvious).
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIXCneOX--T-0HNZCr:-KrWORiVVid41inj2AVl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L133)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW are these just temp variables used within a single function call? If so, that's reasonable but you should make that very clear in the comment. I would suggest giving them uglier names like `double_evaluation_point_temp_` and strictly admonishing future programmers that they must never assume these will persist between method invocations.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 147 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIWR5NymUxKfd1p8-5:-KrWOTZxbI78PfPpi1Rt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L147)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW public API needs doxygen.
</blockquote></details>

Done.

---

*[drake/solvers/evaluator_base.h, line 180 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIXxHLLXI9ncTUc3s8:-KrWPfbJDVuMfTSBynbo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/evaluator_base.h#L180)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW needs doxygen, ideally including `@relates FunctionEvaluator` so that this shows up in the FunctionEvaluator class doc. Also, FunctionEvaluator class comment should mention that this free function exists and give an example of how to use it.
</blockquote></details>

Done.

---

*[drake/solvers/test/evaluator_base_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrIYxWd12XHXwhxWQ7k:-KrWOfgi9y7qSi3s9_1z:b-lhdpp8) ([raw file](https://github.com/robotlocomotion/drake/blob/654f82b08ddee21d3faae7c0ef1c41821e9061f4/drake/solvers/test/evaluator_base_test.cc#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW these are not style guide compatible.
</blockquote></details>

These presently satisfy the `detail::FunctionTraits<>` template contract.
Will address in the separate issue on GSG violations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrWQ0CAuCUWUUsF2Dfk:b-v3s8ec)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818)*

**Comment by sherm1** [comment]
Thanks, Eric! Platform :lgtm:.

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 345 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrXMhWsph5TfXNPS7QD:-KrXMhWsph5TfXNPS7QE:bp9dmyr) ([raw file](https://github.com/robotlocomotion/drake/blob/69fac003bf0e99e4f024bc48c0dac134cd31a997/drake/solvers/constraint.h#L345)):*
> ```objc
> 
>   /**
>    * Constructs a evaulator constraint, given the EvaluatorType instance
> ```

BTW evaulator -> evaluator

---

*[drake/solvers/evaluator_base.h, line 229 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrXU8JiiMCk4VoFEWHF:-KrXU8JiiMCk4VoFEWHG:bu1n9hh) ([raw file](https://github.com/robotlocomotion/drake/blob/69fac003bf0e99e4f024bc48c0dac134cd31a997/drake/solvers/evaluator_base.h#L229)):*
> ```objc
> 
> /**
>  * Creates an FunctionEvaluator instance bound to a given callable object.
> ```

BTW an -> a

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-:-KrXUcTdjv7BQCir_THt:bipeblp)*

**Comment by EricCousineau-TRI** [comment]
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/constraint.h, line 345 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrXMhWsph5TfXNPS7QD:-KrXg2kM3ECI4VUPfBFo:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/69fac003bf0e99e4f024bc48c0dac134cd31a997/drake/solvers/constraint.h#L345)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW evaulator -> evaluator
</blockquote></details>

Done. Thanks!

---

*[drake/solvers/evaluator_base.h, line 229 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6818#-KrXU8JiiMCk4VoFEWHF:-KrXg0YW-lG7G44zzq1J:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/69fac003bf0e99e4f024bc48c0dac134cd31a997/drake/solvers/evaluator_base.h#L229)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW an -> a
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6818)*

**Pull request merged**
