### PR TITLE
Add stl2obj to deal with robot stl meshes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI Just to be sure, I tested this on macOS and is passed.

I need to finish writing more docs and a test, but before I go that far let me ask ...

@EricCousineau-TRI and @SeanCurtis-TRI do you support this general direction?  In short, that when we have third-party models with `*.stl` meshes, instead of manually converting to obj and committing the objs, we add a BUILD rule that calls this tool to automatically convert them during `bazel build //...`.

**Review by sherm1 — COMMENTED** [review]
This may also be a good model for how we can do mesh preprocessing in general. We are likely to need to perform operations like: tetrahedralization, computation of pressure fields, convexification, catching non-manifold surfaces, etc. at some point, which are very expensive and better to do once during build than on the fly.

BTW stl->obj is not an entirely straightforward conversion because stl has independent vertices for every triangle which have to be merged to produce an obj. VTK does that by default but doesn't specify a tolerance so could result in leaky objs. But I still think doing this automatically is a good idea, esp. if we can catch bad meshes downstream.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219#-:-MJmEMP14w5n09-NpVjU:b-igjzv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by EricCousineau-TRI** [comment]
Yuppers, this is what we use in Anzu, so I am 100% in support of this at the high-level!

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a vague wish for a bit more user guidance. There are some non-obvious implications on the use of this tool. 

> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219#-:-MK0ucJrDNwZ8YAzSxwv:b-yp1nw7)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK0tvxj7lqrRxWwx-el:b-nqns85) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
> ```cpp
> 
> DEFINE_string(input, "", "STL filename to read");
> DEFINE_string(output, "", "OBJ filename to write");
> ```

BTW There's some part of my soul that hopes for further guidance in using this. Given STL is the source, the OBJ produced will have a *limited* scope of utility. I.e., there are no texture coordinates (so texturing is out), the resulting is a triangle soup (so probably  not useful for some geometric operations that require water-tight meshes without post-processing, etc.)

Right now this looks a bit too "magic-wandish".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK108eI0ro8K8dofdLL:bkzqtqn) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW There's some part of my soul that hopes for further guidance in using this. Given STL is the source, the OBJ produced will have a *limited* scope of utility. I.e., there are no texture coordinates (so texturing is out), the resulting is a triangle soup (so probably  not useful for some geometric operations that require water-tight meshes without post-processing, etc.)

Right now this looks a bit too "magic-wandish".
</blockquote></details>

If you want to provide some text, I'll paste it in.  For my own part, the PR2 looks great in drake_visualizer, and I have no idea what to say about the topics you allude to.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK10TZmBnuSumMf_Y-s:bxy6aic) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you want to provide some text, I'll paste it in.  For my own part, the PR2 looks great in drake_visualizer, and I have no idea what to say about the topics you allude to.
</blockquote></details>

Maybe the question to focus on is: If a user knows they have an stl, and knows they want an obj, in what way will the output of this tool not be what they want?  I don't immediately see how they would get into trouble.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK12Aa60-_X0TmOMc8X:bnw42yz) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe the question to focus on is: If a user knows they have an stl, and knows they want an obj, in what way will the output of this tool not be what they want?  I don't immediately see how they would get into trouble.
</blockquote></details>

In that context, are you assuming they understand what it means to have an STL? Let me try some concrete examples:

If the user had an STL file of a convex shape, attempted to pass it to Drake as a Convex shape, in the near future, the fact that it isn't a water tight representation will cause an exception to be thrown (despite the fact that the geometry is, in some sense, equivalent to a watertight mesh).

Another, currently, they color the stl by providing diffuse information in the urdf/sdf. If they attempted to assign a texture instead of an rgba value, the texture would not appear in rendering.

Using such an obj for hydroelastic contact (rigid surface) would *probably* work. I'd have to ponder that. The triangle-soup-iness definitely has some undesirable implications, but, it may be that those implications disappear into the noise for a typical user.

So, you decide what the significance of those kinds of things are. If you don't feel it's worth some educational text, we'll go as is. If you think it is, I'll write up some text emphasizing the difference between STL and OBJ and how those differences might affect downstream Drake OBJ consumers.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK1DG9G0vmJMkbuCJt-:b-81j41g) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In that context, are you assuming they understand what it means to have an STL? Let me try some concrete examples:

If the user had an STL file of a convex shape, attempted to pass it to Drake as a Convex shape, in the near future, the fact that it isn't a water tight representation will cause an exception to be thrown (despite the fact that the geometry is, in some sense, equivalent to a watertight mesh).

Another, currently, they color the stl by providing diffuse information in the urdf/sdf. If they attempted to assign a texture instead of an rgba value, the texture would not appear in rendering.

Using such an obj for hydroelastic contact (rigid surface) would *probably* work. I'd have to ponder that. The triangle-soup-iness definitely has some undesirable implications, but, it may be that those implications disappear into the noise for a typical user.

So, you decide what the significance of those kinds of things are. If you don't feel it's worth some educational text, we'll go as is. If you think it is, I'll write up some text emphasizing the difference between STL and OBJ and how those differences might affect downstream Drake OBJ consumers.
</blockquote></details>

@seancurtis-tri from reading the vtk api docs for the STL reader it looked to me that they attempt to combine vertices by default. In that case the obj wouldn't be a triangle soup, right?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK1H6fGDLVVhllDX_kX:b-mcz9mu) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
Good catch. I glanced at the documentation here:

https://vtk.org/doc/nightly/html/classvtkSTLReader.html#details

I stopped reading at: 

> By setting the Merging boolean you can control whether the point data is merged after reading.

Of course, the very next sentence is, "Merging is performed by default."  :-/  That's some inconsistent rhetoric.

So, soup is *probably* not a problem. But texture coordinates is definitely out.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK1Hm6B-UAitDAFmV17:b-5qrkzf) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Good catch. I glanced at the documentation here:

https://vtk.org/doc/nightly/html/classvtkSTLReader.html#details

I stopped reading at: 

> By setting the Merging boolean you can control whether the point data is merged after reading.

Of course, the very next sentence is, "Merging is performed by default."  :-/  That's some inconsistent rhetoric.

So, soup is *probably* not a problem. But texture coordinates is definitely out.
</blockquote></details>

Done. 

The relevant issue wrt this tool seems to be the user blithely assuming that the conversion will be satisfactory, vs the guts of the tool which just delegate all responsibility to VTK.  I think a reminder of that (added here as a NOTE) should be a sufficient tickle to make them think twice.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule (tomorrow), please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[manipulation/util/stl2obj.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14219#-MK0tvxi1YdoiEVY-GMn:-MK1Tzcq4G_9Vgagcvp2:b-j6u9bs) ([raw file](https://github.com/robotlocomotion/drake/blob/c101fff563b68ec2566402fc1d15bfbac55f4eaa/manipulation/util/stl2obj.cc#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done. 

The relevant issue wrt this tool seems to be the user blithely assuming that the conversion will be satisfactory, vs the guts of the tool which just delegate all responsibility to VTK.  I think a reminder of that (added here as a NOTE) should be a sufficient tickle to make them think twice.
</blockquote></details>

Perfect

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 42 of 43 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14219#-:-MK5avAY0NPYaOcsdNV5:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
