### PR TITLE
Add LinearConstraint::RemoveTinyCoefficient

### LINKED ISSUE #17103: Tiny coefficients in constraint matrix causes the solver to fail.
I have some optimization problem containing constraints with tiny coefficients
```
2.4980018054066e-16 *X0(0, 0) + 2.08166817117217e-16 * X0(1, 0) = 0
2.4980018054066e-16 *X0(1, 0) + 2.08166817117217e-16 * X0(1, 1) = 0
```
The solvers (Mosek, CSDP) fails to solve the problem. If I remove these problematic linear constraints, the solvers are happy.

So I think we should provide the capability to "prune" our constraints. For example, in a linear constraint, if the coefficient/bounds contain tiny values, then we should set that entry to actually 0.

Currently to prune the coefficients, I do it manually like this
```cc
const double tol = 1E-15;
for (int i = 0; i < constraint.get_sparse_A().cols(); ++i) {
  for (Eigen::SparseMatrix<double>::InnerIterator it(constraint.get_sparse_A(), i); it; ++it) {
    if (std::abs(it.value()) < tol) {
      it.valueRef() = 0;
    }
  }
}
```

I think it would be valuable to add this function to Drake, something like
```cc
void LinearConstraint::prune(double tol);
void LinearEqualityConstraint::prune(double tol);
void LorentzCone::prune(double tol);
void RotatedLorentzCone::prune(double tol);
```

@frankpermenter is this generally a good idea to remove the tiny coefficients in the constraint matrices?

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #17103

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182#-:-N1uaZvkBE7mtkwPNOHD:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm: with some nits

+@jwnimmer-tri for platform review please, thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182#-:-N2CB-zF8xNCegnmLtFw:bngqxor)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`solvers/constraint.h` line 631 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2C6h0nDkciRbHrmWtI:-N2C6h0nDkciRbHrmWtJ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L631)):*
> ```objc
>   /**
>    * Set A(i, j) to zero if abs(A(i, j)) < tol.
>    * Oftencases the coefficient A is computed numerically with roundoff errors.
> ```

typo



_Code quote:_
```objc
Oftencases
```
___
*[`solvers/constraint.h` line 631 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2C7GvW2-zdFnl4aJPg:-N2C7GvW2-zdFnl4aJPh:b-qq7nak) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L631)):*
> ```objc
>   /**
>    * Set A(i, j) to zero if abs(A(i, j)) < tol.
>    * Oftencases the coefficient A is computed numerically with roundoff errors.
> ```

round-off?
___
*[`solvers/constraint.h` line 632 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2C7NUm4N4MVQHcG9ys:-N2C7NUm4N4MVQHcG9yt:b9aeu5o) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L632)):*
> ```objc
>    * Set A(i, j) to zero if abs(A(i, j)) < tol.
>    * Oftencases the coefficient A is computed numerically with roundoff errors.
>    * Such small roundoff errors can cause numerical issue for certain
> ```

typo: "a numerical issue" / "numerical issues"



_Code quote:_
```objc
can cause numerical issue
```
___
*[`solvers/constraint.h` line 635 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2C82WI50lCyHG_9Z1W:-N2C82WI50lCyHG_9Z1X:bjd7kls) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L635)):*
> ```objc
>    * optimization solvers. Hence it is recommended to remove the tiny
>    * coefficients to achieve numerical robustness.
>    * @param tol The entries in A with absolute value <= tol will be set to 0.
> ```

Consider noting tol > 0



_Code quote:_
```objc
 * @param tol The entries in A with absolute value <= tol will be set to 0.
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182#-:-N2CDB0E7rU1GAv9t3fY:b-vtj4vo)* status: 6 unresolved discussions (waiting on @hongkai-dai)

___
*[`solvers/constraint.h` line 630 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CBbHcDesz7ht2HtUL:-N2CBbHcDesz7ht2HtUM:b-3btgih) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L630)):*
> ```objc
> 
>   /**
>    * Set A(i, j) to zero if abs(A(i, j)) < tol.
> ```

nit GSG verb mood



_Suggestion:_
```objc
Sets
```
___
*[`solvers/constraint.h` line 630 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CBmT17fflMy83S_gy:-N2CBmT17fflMy83S_gz:bw4v496) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L630)):*
> ```objc
> 
>   /**
>    * Set A(i, j) to zero if abs(A(i, j)) < tol.
> ```

I think the implementation uses `<=` not `<`?



_Suggestion:_
```objc
 abs(A(i, j)) <= tol
```
___
*[`solvers/constraint.cc` line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CC8dn7R8Yprm8v7n9:-N2CC8dn7R8Yprm8v7nA:bfodkw5) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.cc#L437)):*
> ```cpp
> }
> 
> void BoundingBoxConstraint::RemoveTinyCoefficient(double) {
> ```

There is actually no need to define (provide a body for) this function, nor document that is throws an exception.  Nobody will be able to call it in the first place, due to the private visibility.
___
*[`solvers/test/constraint_test.cc` line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CD7fm7xoKzfuHif4d:-N2CD7fm7xoKzfuHif4e:bbx1gsh) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/test/constraint_test.cc#L168)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(dut.upper_bound(), ub));
> 
>   DRAKE_EXPECT_THROWS_MESSAGE(dut.RemoveTinyCoefficient(-1.),
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals



_Suggestion:_
```cpp
-1
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`solvers/constraint.h` line 630 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CBmT17fflMy83S_gy:-N2CyHq_3dT3DmKbc-yC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.h#L630)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the implementation uses `<=` not `<`?
</blockquote></details>

Done.
___
*[`solvers/constraint.cc` line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17182#-N2CC8dn7R8Yprm8v7n9:-N2Cz9rvADxOHdd20LMi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba5639dd4738d8e2d0046426c9967fcc382b28ea/solvers/constraint.cc#L437)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is actually no need to define (provide a body for) this function, nor document that is throws an exception.  Nobody will be able to call it in the first place, due to the private visibility.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17182)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
