### PR TITLE
Ensure that Add.*(Cost|Constraint) does not allow invalid decision variables.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses #6870, and checks each constraint type.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6881)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please.

**Comment by soonho-tri** [comment]
@ericcousineau-tri , could you check the CI failures?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9QpMvFCH2uMm6R6Pk:bky1xqp)*

**Comment by soonho-tri** [comment]
FYI, I have:

```
[ RUN      ] testMathematicalProgram.testBadBindingVariable
abort: Failure at ./drake/solvers/constraint.h:155 in check(): condition 'static_cast<size_t>(lower_bound_.size()) == num_constraints && "Size of lower bound must match number of constraints."' failed.
external/bazel_tools/tools/test/test-setup.sh: line 169: 35055 Abort trap: 6           "${TEST_PATH}" "$@"
```

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/mathematical_program.h, line 2377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SK-EWeEGOsdTKkNl:-Ks9SK-EWeEGOsdTKkNm:b-2cwoow) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2377)):*
> ```objc
>    * Ensure a binding is valid *before* adding it to the program.
>    *
>    * @pre The binding has not yet been registered.
> ```

Do we (if not, can we) check if this is the case?

---

*[drake/solvers/mathematical_program.h, line 2383 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SYhWXYCfVb_PvtLx:-Ks9SYhWXYCfVb_PvtLy:b-f6rk73) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2383)):*
> ```objc
>   void CheckBinding(const Binding<C>& binding) const {
>     // TODO(eric.cousineau): Once bindings have identifiers (perhaps
>     // retrofitting `description`), ensure that they have unique names.
> ```

OK, I guess this is how we might check if a biding is not registered later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9TdbbyyXX31raG5Ad:b-d4nh6i)*

**Comment by EricCousineau-TRI** [comment]
Sorry, forgot to fix up bound sizes. Fixed that in the most recent push.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/mathematical_program.h, line 2377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SK-EWeEGOsdTKkNl:-Ks9UlxEZZnRerkLItDT:b-afqzwd) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2377)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Do we (if not, can we) check if this is the case?
</blockquote></details>

In addition to the answer below, we could probably "hash" a binding by the constraint it holds and the variables that it's bound to, to prevent the same binding from being registered.

Would you want that as an additional check?

---

*[drake/solvers/mathematical_program.h, line 2383 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SYhWXYCfVb_PvtLx:-Ks9UafqEFQPecOq5ERj:bora3my) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2383)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK, I guess this is how we might check if a biding is not registered later?
</blockquote></details>

Yup. The best solution would be to have a UID on the `Binding`, and I was thinking to use the name as the UID (permitting human-readable, or automatically indexed by type).

Have you been encountering issues with re-registering bindings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9U0Z56FnNk3NE469v:b-ux906l)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/mathematical_program.h, line 2377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SK-EWeEGOsdTKkNl:-Ks9VoA0z4glv7Nm6bL1:b-u7i4l9) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2377)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

In addition to the answer below, we could probably "hash" a binding by the constraint it holds and the variables that it's bound to, to prevent the same binding from being registered.

Would you want that as an additional check?
</blockquote></details>

I just thought that what we have in the documentation is slightly stronger than what we have in the code. Feel free to add the check this time or add a TODO.

---

*[drake/solvers/mathematical_program.h, line 2383 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SYhWXYCfVb_PvtLx:-Ks9W0v-WZtXPYtZ6fbF:bl32fnw) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2383)):*
> Have you been encountering issues with re-registering bindings?

Not yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881)*

**Comment by soonho-tri** [comment]
:lgtm: I've checked that the failed test passed this time, in a local machine.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9WGgfPoizr-GZDdt9:b8rvo4d)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/solvers/mathematical_program.h, line 2377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-Ks9SK-EWeEGOsdTKkNl:-Ks9YVur9Q9qyAGlNrtM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47961f99e387a4dfbad9b9a2a7800b9f5396d5ed/drake/solvers/mathematical_program.h#L2377)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I just thought that what we have in the documentation is slightly stronger than what we have in the code. Feel free to add the check this time or add a TODO.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9YcYNGq3cVnyUv4OS:bz1t39v)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6881#-:-Ks9zh-ENZgganiPi1bn:bnfp4nl)*

**Pull request merged**
