### PR TITLE
[workspace] Remove bionic support for ros_xacro.

### PR DESCRIPTION
**Pull request by svenevs**
Update to v1.14.13 noetic version.

Relates: #13391, #16931.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: +@BetsyMcPhail for feature review please.

FWIW the patch files are formatted slightly differently, however if you check out this PR locally and `bazel build //tools/workspace/ros_xacro/...` you can confirm it works as expected.  If you modify the patch file to have e.g., `--- a/src/xacro/__init__.py` and `+++ b/src/xacro/__init__.py` (with a leading `a/` and `b/`) it will fail.  AKA the patches still work even though there are some changes beyond just updating the line numbers, I'm not sure how the original author was creating their patch files so I just patched in the new patches :slightly_smiling_face:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967#-:-N-crO_74H-x_e84kHR_:bfey6n2)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

___
*[tools/workspace/ros_xacro/repository.bzl, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-cr67WErjpYnFwOVPB:-N-cr67WErjpYnFwOVPC:bv875jv) ([raw file](https://github.com/robotlocomotion/drake/blob/60d5b7baa2a61064d994b8657e7b5e00475735b1/tools/workspace/ros_xacro/repository.bzl#L13)):*
> ```Starlark
>         # N.B. Even though 1.14.x series is not the highst-numbered release, we
>         # are using it here because it aligns with the ROS Noetic version
>         # released for Ubuntu 20.04.
> ```

FYI currently 1.14.13 **is** the latest release, but the comment stays as it is for now since over time it will likely be the case that noetic releases stop happening.  https://index.ros.org/p/xacro/github-ros-xacro/#noetic

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967#-:-N-d5dIZDxoe8ft2ymxp:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967#-:-N-d6-O70yTj2YJzUiMA:b-ykw85)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @svenevs)

___
*[tools/workspace/ros_xacro/disable-console-print.patch, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-dBiUo3zhJ8InShuMx:-N-dBiUo3zhJ8InShuMy:b-3rxbwu) ([raw file](https://github.com/robotlocomotion/drake/blob/c61aa519a6176cef1428f4eb67653d49c63b59cb/tools/workspace/ros_xacro/disable-console-print.patch#L1)):*
> ```Diff
> Disable a stray console print, unwanted while in -o mode.
> ```

The build works a-ok for me, without changing these patch files.  (No errors, no warnings).

Why do we need to change them at all?
___
*[tools/workspace/ros_xacro/repository.bzl, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-cr67WErjpYnFwOVPB:-N-d9_BO90wYXv1Mi1SK:bfmyp1) ([raw file](https://github.com/robotlocomotion/drake/blob/60d5b7baa2a61064d994b8657e7b5e00475735b1/tools/workspace/ros_xacro/repository.bzl#L13)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI currently 1.14.13 **is** the latest release, but the comment stays as it is for now since over time it will likely be the case that noetic releases stop happening.  https://index.ros.org/p/xacro/github-ros-xacro/#noetic
</blockquote></details>

Should we add that link into a comment here?
___
*[tools/workspace/ros_xacro/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-d9S-bA1lPG0VvQG2y:-N-d9S-bA1lPG0VvQG2z:bqe6no5) ([raw file](https://github.com/robotlocomotion/drake/blob/c61aa519a6176cef1428f4eb67653d49c63b59cb/tools/workspace/ros_xacro/repository.bzl#L11)):*
> ```Starlark
>         name = name,
>         repository = "ros/xacro",
>         # N.B. Even though 1.14.x series is not the highst-numbered release, we
> ```

nit We should probably be precise here, per the FYI below:



_Suggestion:_
```Starlark
might not be the
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16967)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @svenevs)

___
*[tools/workspace/ros_xacro/repository.bzl, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-cr67WErjpYnFwOVPB:-N-dGXn54cxRQTcDkZEP:b-meyba7) ([raw file](https://github.com/robotlocomotion/drake/blob/60d5b7baa2a61064d994b8657e7b5e00475735b1/tools/workspace/ros_xacro/repository.bzl#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should we add that link into a comment here?
</blockquote></details>

OK works for me, added!
___
*[tools/workspace/ros_xacro/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-d9S-bA1lPG0VvQG2y:-N-dGGPO-sQLQkESNwmQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c61aa519a6176cef1428f4eb67653d49c63b59cb/tools/workspace/ros_xacro/repository.bzl#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We should probably be precise here, per the FYI below:
</blockquote></details>

Done.
___
*[tools/workspace/ros_xacro/disable-console-print.patch, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16967#-N-dBiUo3zhJ8InShuMx:-N-dH4RP5YVC-8Tz9La5:b-5tgryh) ([raw file](https://github.com/robotlocomotion/drake/blob/c61aa519a6176cef1428f4eb67653d49c63b59cb/tools/workspace/ros_xacro/disable-console-print.patch#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The build works a-ok for me, without changing these patch files.  (No errors, no warnings).

Why do we need to change them at all?
</blockquote></details>

OK, I removed the changes from the most recent commit.  I updated them because the diff application uses both (a) line numbers as well as (b) `@@ def main():` + surrounding line context.  Right now these patches only work because of (b) since the line numbers have changed.

It doesn't make a big difference either way, the patches still apply so it's OK to leave it to me.

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Pull request merged**
