### PR TITLE
Symbolic system constraints

### PR DESCRIPTION
**Pull request by RussTedrake**
parse system constraints into `SystemSymbolicInspector`.
(continued progress on #6858; the next PR will use these constraints in multiple shooting)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6976)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-:-KtLcvsKg-tVUrEsT51y:bgbmm3h)*

**Comment by hongkai-dai** [comment]
+@soonho-tri as feature reviewer also. I am about to fly back to China, and might be offline for a day or two. So pardon me for not responding emails.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/system_constraint.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtN-OzQBl2PjeY7Wtft:-KtN-OzQBl2PjeY7Wtfu:bvd2qke) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L55)):*
> ```objc
>   /// the constraint function f:
>   ///   value = f(context)
>   /// where value has the same number of elements as lower_bound and
> ```

This line should be removed?

---

*[drake/systems/framework/system_constraint.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtMzPgPuvNEsZAmqqZR:-KtMzPgPuvNEsZAmqqZS:b-lkte8g) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L62)):*
> ```objc
>       std::function<void(const Context<T>& context, VectorX<T>* value)>;
> 
>   /// Constructs the SystemConstraint.
> ```

Document the input parameters?

If a constraint contains both inequality and equality constraint, should we declare it as inequality constraint? Or suggest the user to separate it into the inequality part, and the equality part?

Do we consider to provide some mechanism, to automatically determine if a constraint is equality or inequality? Theoretically we can check the lower and upper bound.

We should also mention that a equality constraint is of the form
```
f(x) = 0
```
Namely the right-hand side is 0. An the inequality constraint is of the form
```
g(x) >= 0
```
Both `f(x)` and `g(x)` can be vector-valued functions.

---

*[drake/systems/framework/test/system_constraint_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtN0tJ3Dzhf3yYaJgm9:-KtN0tJ4qNB7A83cjCMK:bosto9z) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/test/system_constraint_test.cc#L60)):*
> ```cpp
> 
>   EXPECT_EQ(inequality_constraint.size(), 1);
>   EXPECT_EQ(inequality_constraint.description(), "inequality constraint");
> ```

Add some test that `constraint.size()` is larger than 1, to make sure it also works for vector-valued constraint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-:-KtN1YRsZN1T1Vf42_Gs:b9vh3u6)*

**Comment by soonho-tri** [comment]
:lgtm:

+@ggould-tri , platform-review please.

---

Reviewed 5 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-:-KtNLPG-Sum443whN2a9:b-u727j0)*

**Comment by ggould-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/system_constraint.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtMzPgPuvNEsZAmqqZR:-KtNd5Q6Qxltb1HmEdDJ:bglxfbh) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L62)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document the input parameters?

If a constraint contains both inequality and equality constraint, should we declare it as inequality constraint? Or suggest the user to separate it into the inequality part, and the equality part?

Do we consider to provide some mechanism, to automatically determine if a constraint is equality or inequality? Theoretically we can check the lower and upper bound.

We should also mention that a equality constraint is of the form
```
f(x) = 0
```
Namely the right-hand side is 0. An the inequality constraint is of the form
```
g(x) >= 0
```
Both `f(x)` and `g(x)` can be vector-valued functions.
</blockquote></details>

Yes, these parameters are not clear from context and must be documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-:-KtNe6O4sEmetmybSpDh:buvdl6p)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/system_constraint.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtN-OzQBl2PjeY7Wtft:-KtOvDsJn-eAQSVdK_LU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This line should be removed?
</blockquote></details>

Done.

---

*[drake/systems/framework/system_constraint.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtMzPgPuvNEsZAmqqZR:-KtOvJ0EaluuxhISqjMe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L62)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Yes, these parameters are not clear from context and must be documented.
</blockquote></details>

Done.

---

*[drake/systems/framework/system_constraint.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtNIkS5i8aEHTC_8ZFV:-KtOvXY_uqhfcfE7AurQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L65)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, you can change this line to
```c++
calc_function_(std::move(calc_function)),
```
or make the above signature to
```c++
SystemConstraint(const CalcCallback& calc_function, ...
```
to reduce the number of copies. I prefer the `std::move` one.
</blockquote></details>

Done.

---

*[drake/systems/framework/system_constraint.h, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtNK3WNXG4ialZ4QQPD:-KtOvfs32eSPcz98OG5k:b-o38pul) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_constraint.h#L88)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, `const double tol` -> `double tol` per our style-guide.
</blockquote></details>

fixed here (and in Constraint)

---

*[drake/systems/framework/system_symbolic_inspector.h, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtNGTnjzWp08dCsC4lo:-KtOwMTeyFRPBYsVO0aU:b7uixvn) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/system_symbolic_inspector.h#L146)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

In case you wanted to use `std::unordered_set`, you can have:
```c++
 std::unordered_set<symbolic::Formula, hash_value<symbolic::Formula>>
      constraints_;
```
</blockquote></details>

i chose std::set because that is what the AddLinearConstraint can consume..?

---

*[drake/systems/framework/test/system_constraint_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-KtN0tJ3Dzhf3yYaJgm9:-KtOxrINs4Sivy3TV75X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/396e0c6a55e2127424e0681465dbc74680acc597/drake/systems/framework/test/system_constraint_test.cc#L60)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add some test that `constraint.size()` is larger than 1, to make sure it also works for vector-valued constraint?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976)*

**Comment by soonho-tri** [comment]
-@hongkai-dai 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6976#-:-KtRVdxccGn5MynAtP2i:b-uz7c1m)*

**Pull request merged**
