### PR TITLE
Made LcmPublisherSystem and LcmSubscriberSystem leaf systems. Used new APIs for declaring input and output ports.

### PR DESCRIPTION
**Pull request by liangfok**
This PR should not be reviewed / merged until after #3202 is merged since that PR introduces the new `System::Publish()` API.

# Deprecated Description 1
This PR was created as an example for #3202.
#3202 will most likely subsume this PR since it has the newer `System::Publish()` API.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3283)

### CODE REVIEW

**Comment by liangfok** [comment]
This builds upon initial changes to `Lcm*System` in #3202 based on "sugar" added to System 2.0. Thus:

+@sherm1 for feature review please.
+@david-german-tri for platform review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3283#-:-KQHAArxERF_Es_F-6Y7:b-ywblog)*

**Comment by jwnimmer-tri** [comment]
Swapping -@sherm1 +@jwnimmer-tri for feature review.  Without this, I can't use LCM in a Diagram.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3283#-:-KQIttfJidrNaXKkIwwl:b-r0l1c0)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3283#-:-KQIuvqiAptCCDGwiJJp:bnfp4nl)*

**Comment by sherm1** [comment]
In that case +@sherm1 -@david-german-tri for platform review.

Platform review: :lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3283#-:-KQIzr96jJX8aWU6HGgo:b-tyvri9)*

**Pull request merged**
