### PR TITLE
Remove superfluous pthread flag on OS X.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #5183.

@liangfok for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5333)

### CODE REVIEW

**Comment by liangfok** [comment]
When I first tested this using a dirty workspace, the `pthread` warnings persisted. However, after cleaning the workspace using `bazel clean --expunge`, the warnings continued to show up. Did I do something wrong? I am using 559ee999fe20c5a8fb0ce39794a2aba06ff6d8fd.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke-XE7ISxQUUpHVAVw8:b59ehol)*

**Comment by liangfok** [comment]
Here is what I see: https://gist.github.com/liangfok/c194d35efff74d8249ff2c5ad6a9d5c3

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke-e55C0R_GWkZ9iuwI:bagb03w)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333)*

**Comment by david-german-tri** [comment]
Yep, I missed some - thanks!  done.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke05JqzRFaUH8SpUDlt:b-zgtjgo)*

**Comment by liangfok** [comment]
:lgtm: I tested this on my OSX machine and it works perfectly. Thanks!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke0IiTPMPmwisty5Zev:b426h6t)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri platform

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke0JeVVlgBHT4t9ewTF:bnhsbnq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-Ke0PRzRYT5ZTKOJOf5-:-Ke0PRzS-RoopNvjt2N-:b-vnrz2q) (no related file):*
BTW So this is fine, but now that `tools/otherlib.BUILD` files are using `@//tools:linux` conditions, they are not really separable from Drake anyway, so I wonder if a `deps = ["@//tools:pthread"]` (and a `cc_library` rule with the flag in`tools/BUILD`) in lieu of `linkopts=...` would be worth it to de-dup the select logic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5333#-:-Ke0Qz_S4P160w1iL_jn:bnfp4nl)*

**Pull request merged**
