### PR TITLE
Refactor rendering pipeline

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Refactor rendering pipeline for `RgbdRendererVTK` to make use of shaders.

There is no functionality change included in this PR except mesh scale handling in `RgbdRendererVTK::Impl::ImplRegisterVisual`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7706)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@thduynguyen feature review please.
+@sherm1 platform review please.

/cc @seancurtis-tri 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L27mBTA88gsfvuxa_H3:b-mn7g4i)*

**Comment by sherm1** [comment]
Platform review: there is a lot of tricky code here without much documentation. I would like to see any non-obvious sequences of shader and vtk code have at least a brief comment saying what your intent is, so that some future programmer can get some guidance when fixing bugs or making changes. Also a few BTWs below.

Pending the BTWs and more documentation, :lgtm:.  
(Still needs a careful feature review.)

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/sensors/depth_shaders.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27uGUDaVxGEeGPHlke:-L27uGUDaVxGEeGPHlkf:b16opvd) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/depth_shaders.h#L8)):*
> ```objc
> namespace shaders {
> 
> constexpr char kDepthVS[] =
> ```

BTW should add doxygen comments for these global variables to say what the shader does.

---

*[systems/sensors/depth_shaders.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27uaafDPsBTZ_jeaOP:-L27uaafDPsBTZ_jeaOQ:b-geu3ug) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/depth_shaders.h#L9)):*
> ```objc
> 
> constexpr char kDepthVS[] =
>     "//VTK::System::Dec\n"  // always start with this line
> ```

BTW cap punc

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27t8GS8XrXrSbHvYQc:-L27t8GS8XrXrSbHvYQd:b-6iywda) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/rgbd_renderer_vtk.cc#L116)):*
> ```cpp
> }
> 
> class vtkShaderCallback : public vtkCommand {
> ```

BTW can this class use our naming convention rather than vtk's? As named it looks like part of vtk rather than part of Drake. (OK if there is a good reason to copy the vtk style here.)

---

*[systems/sensors/test/rgbd_renderer_vtk_test.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27twAkRsH9J_D7KNbO:-L27twAkRsH9J_D7KNbP:b4r14vj) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/test/rgbd_renderer_vtk_test.cc#L30)):*
> ```cpp
>   for (int y = 0; y < kHeight; ++y) {
>     for (int x = 0; x < kWidth; ++x) {
>       ASSERT_TRUE(std::isinf(depth_.at(x, y)[0]));
> ```

BTW as before probably good to put a comment here explaining why the ASSERT here is preferable to EXPECT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L27vDuF9sXVBMusiH1y:b-6pbnvl)*

**Comment by kunimatsu-tri** [comment]
Thanks sherm!

Addressed all the comments and added documentation.
PTAL and let me know if you still find peaces of code that I need to add document.

---

Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[systems/sensors/depth_shaders.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27uGUDaVxGEeGPHlke:-L2LsUOYuGdCCftP6PW3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/depth_shaders.h#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should add doxygen comments for these global variables to say what the shader does.
</blockquote></details>

Done.

---

*[systems/sensors/depth_shaders.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27uaafDPsBTZ_jeaOP:-L2LsT5ExlLyv7lfEiKH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/depth_shaders.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW cap punc
</blockquote></details>

Done.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27t8GS8XrXrSbHvYQc:-L2M1LUJGAVfsYP8S8VB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/rgbd_renderer_vtk.cc#L116)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can this class use our naming convention rather than vtk's? As named it looks like part of vtk rather than part of Drake. (OK if there is a good reason to copy the vtk style here.)
</blockquote></details>

Done.

---

*[systems/sensors/test/rgbd_renderer_vtk_test.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L27twAkRsH9J_D7KNbO:-L2M1witpCW8nf5FS_0X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c46bb6830346d2ab17a2bc56aa3fda645c4e5ff1/systems/sensors/test/rgbd_renderer_vtk_test.cc#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW as before probably good to put a comment here explaining why the ASSERT here is preferable to EXPECT.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L27nguwt2p2Mt96AJve:btj3f8b)*

**Comment by sherm1** [comment]
This is great, Kuni -- thanks! :lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2N4l6YtGWmDE61UlFo:b-nzpbtr)*

**Comment by thduynguyen** [comment]
Feature review done with some minor BTWs. LGTM.

---

Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2RyQjUA_WETcNhL4sr:be13pss) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
> ```objc
>     "uniform float z_far;\n"
>     "\n"
>     "vec3 PackFloatToVec3i(float value) {\n"
> ```

BTW It's best to document the magic maths here (or somewhere) so future people don't have to reverse-engineering it. The website doesn't explain the maths in detail.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 183 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MkiiPSRSfduACHLBN:-L2MkiiPSRSfduACHLBO:bi9x5al) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L183)):*
> ```cpp
>   vtkNew<vtkActor> terrain_actor_;
>   vtkNew<vtkActor> terrain_depth_actor_;
>   std::array<std::unique_ptr<RenderingPipeline>, 3> pipelines_;
> ```

BTW Add a comment on the purpose of each pipeline so we know, e.g., pipeline 0 is for RGB, 1 for depth, 2 for ground-truth label rendering?
Even better, should it be a map from ImageType to RenderingPipeline?

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MkL6G5s6ZQleFd9Ps:-L2MkL6G5s6ZQleFd9Pt:bkbc0g2) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L187)):*
> ```cpp
>   // A map which takes pairs of a body index in RBT and three vectors of
>   // vtkSmartPointer to vtkActor for color, depth and label rendering
>   // respectively. The each vtkActor corresponds to an visual
> ```

"The each" --> "Each".

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MlDdf_scKeAP5cdNX:-L2MlDdf_scKeAP5cdNY:b-kax3ym) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L191)):*
> ```cpp
>   std::map<int, std::array<ActorCollection, 3>> id_object_maps_;
> 
>   vtkNew<ShaderCallback> callback_;
> ```

BTW Add a comment for this variable, or using a more meaningful name indicating its purpose, e.g. vtk_uniform_setting_callback?

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 472 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MqRa9qdzN0nNk31Q6:-L2MqRa9qdzN0nNk31Q7:b-t5ltlj) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L472)):*
> ```cpp
>       mesh_reader->Update();
> 
>       // Changing the scale of the loaded mesh.
> ```

BTW why do we need to do this whereas previously we don't?

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 525 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2Mj4b6x1g7gg35WApB:-L2Mj4b6x1g7gg35WApC:b-q12ebb) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L525)):*
> ```cpp
>     auto& color_actor = actors[ImageType::kColor];
>     if (color_actor->GetProperty()->GetNumberOfTextures() == 0) {
>        const auto color = visual.getMaterial();
> ```

Inconsistent indentation.

---

*[systems/sensors/test/rgbd_renderer_vtk_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2Mie-nK_KkxJdkanNB:-L2Mie-nK_KkxJdkanNC:b-b1kifz) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/test/rgbd_renderer_vtk_test.cc#L43)):*
> ```cpp
>   const auto& kTerrain = renderer_->color_palette().get_terrain_color();
>   // At two different distances.
>   for (auto depth : std::array<float, 2>({{2.f, 4.9999f}})) {
> ```

BTW What's the reason for this change?

---

*[systems/sensors/test/vtk_util_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MiiF96Q_zjaxjp68L:-L2MiiFAk7iNVNyNSj7j:b-oayxd) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/test/vtk_util_test.cc#L19)):*
> ```cpp
> namespace {
> 
> const double kTolerance = 1e-15;
> ```

BTW, make sure this threshold works on all supported OS/platforms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2RzeDGWPT5e_JAr1_B:b-d02j7s)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2SNnbs3LtAAeWReKxb:b-u0va29)*

**Comment by kunimatsu-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 183 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MkiiPSRSfduACHLBN:-L2S7rIHmKklRzZ8cTjU:b-cgqd2x) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L183)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW Add a comment on the purpose of each pipeline so we know, e.g., pipeline 0 is for RGB, 1 for depth, 2 for ground-truth label rendering?
Even better, should it be a map from ImageType to RenderingPipeline?
</blockquote></details>

Done.

I've just added the comment for now.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MkL6G5s6ZQleFd9Ps:-L2S4779N6Mfg3A2Bi0k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L187)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

"The each" --> "Each".
</blockquote></details>

Done.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 191 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MlDdf_scKeAP5cdNX:-L2S4M4h1NnXmE7R8fdV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L191)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW Add a comment for this variable, or using a more meaningful name indicating its purpose, e.g. vtk_uniform_setting_callback?
</blockquote></details>

Done.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 472 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MqRa9qdzN0nNk31Q6:-L2S5EL5MVgIbIUW5Okz:bfyslv) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L472)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW why do we need to do this whereas previously we don't?
</blockquote></details>

Just because I've noticed that the scale information from `.obj` file was not handled.

---

*[systems/sensors/rgbd_renderer_vtk.cc, line 525 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2Mj4b6x1g7gg35WApB:-L2S5qhsy5YrVOToPh7E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/rgbd_renderer_vtk.cc#L525)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

Inconsistent indentation.
</blockquote></details>

Done.

---

*[systems/sensors/test/rgbd_renderer_vtk_test.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2Mie-nK_KkxJdkanNB:-L2S851-6ruXeQDa3JVG:bpnhhwg) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/test/rgbd_renderer_vtk_test.cc#L43)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW What's the reason for this change?
</blockquote></details>

Because it's easier (thus simpler) to implement by excluding the boundary of upper limit of depth measurement when thinking about normalizing depth value to be [0, 1] [here](https://github.com/RobotLocomotion/drake/pull/7706/files#diff-e60ff593134c65bdb4ff87fbddd60bd4R60).

---

*[systems/sensors/test/vtk_util_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2MiiF96Q_zjaxjp68L:-L2SNtCz9udL8blmGZLv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/test/vtk_util_test.cc#L19)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW, make sure this threshold works on all supported OS/platforms.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by kunimatsu-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2WzrnNral1skWHGLAl:bw1tarv) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW It's best to document the magic maths here (or somewhere) so future people don't have to reverse-engineering it. The website doesn't explain the maths in detail.
</blockquote></details>

Done.

I added the comment but am not sure if this is good enough. PTAL.

When I tried describing the detail more, it turned out just repeating what the code does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2X44juQ1SBKcugco0F:b-7cgy91)*

**Comment by kunimatsu-tri** [comment]
@thduynguyen Addressed or answered all of your comments. PTAL. Thanks!

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2X47EU0WcjW-Dt9K8u:b3nq7mi)*

**Comment by thduynguyen** [comment]
Thanks Kuni! :lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2XJkR789pbFYP-eoBp:bc1xhhv) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Done.

I added the comment but am not sure if this is good enough. PTAL.

When I tried describing the detail more, it turned out just repeating what the code does.


</blockquote></details>

BTW I think the current comment is better than having nothing, although an intuitive example in base 100 like what you've explained to me would be much more helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2XKg7hf_8KIZFLWRsJ:b-2u2b6m)*

**Comment by kunimatsu-tri** [comment]
*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2XLRWaPDLe2izyDdLX:b-z8cvah) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW I think the current comment is better than having nothing, although an intuitive example in base 100 like what you've explained to me would be much more helpful.
</blockquote></details>

OK, that's a good point. I'll add that comment too. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by kunimatsu-tri** [comment]
*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2XVVwqe68uWSR5fHZ2:bgz2sfy) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

OK, that's a good point. I'll add that comment too. 
</blockquote></details>

Added the comment. PTAL, my English expression in particular. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by kunimatsu-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2atiIcNYEDweOB8y9M:berwktj) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Added the comment. PTAL, my English expression in particular. 
</blockquote></details>

I hope it's better now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by thduynguyen** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/depth_shaders.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-L2RyQjUA_WETcNhL4sq:-L2aXaEdb6QW4WZ1XqIJ:bwo8o61) ([raw file](https://github.com/robotlocomotion/drake/blob/e0a75565d074f668fa77a61e111fa38bf3479482/systems/sensors/depth_shaders.h#L49)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I hope it's better now.
</blockquote></details>

Yes, it's much clearer now. Thanks a lot Kuni!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706)*

**Comment by thduynguyen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7706#-:-L2b0ikS2sZiDpeDUU-S:bnfp4nl)*

**Pull request merged**
