### PR TITLE
manipulation: Rewrite and test kuka_iiwa LCM systems 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #10567.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10584)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri and +@sammy-tri could you review this?

What I've done here is an intermediate draft -- I've disarmed the deprecation warnings with `#if 0` so that everything still compiles, and we can prove that all applications work even without modifications.  Once you are happy with the PR so far, I will re-arm the warnings and update all of the kuka examples to use the new port names.

**Comment by siyuanfeng-tri** [comment]
___
*[manipulation/kuka_iiwa/iiwa_status_receiver.cc, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10584#-LXzE--o9VzTFlwF1TPe:-LXzMPIY-dkjZsAA-ELO:b9emji4) ([raw file](https://github.com/robotlocomotion/drake/blob/5adb5bef343aa9c206ff21fd47ca5147c4e1aeec/manipulation/kuka_iiwa/iiwa_status_receiver.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The methods can't be snake_case if they were to call `GetJoint(string name)`, since that is not a constant-time method (places that already do that in Drake are defective).  I was content with the magic numbers here because the unit test would fail if someone forgot to keep them in sync, and it shouldn't be too much of a burden for a future author to visually match the prior 20 lines with these 20 lines.  What do you think?
</blockquote></details>

i don't understand the first half. 
i am happy with magic number index if there are like < 3. i guess you can argue that these decode / encoder is simple enough that i think you can get away with magic numbers... in any case i'd like to understand the first half of your argument.

**Comment by jwnimmer-tri** [comment]
___
*[manipulation/kuka_iiwa/iiwa_status_receiver.cc, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10584#-LXzE--o9VzTFlwF1TPe:-LXzQ8AY8bn-sxHn9taj:b809hah) ([raw file](https://github.com/robotlocomotion/drake/blob/5adb5bef343aa9c206ff21fd47ca5147c4e1aeec/manipulation/kuka_iiwa/iiwa_status_receiver.cc#L51)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i don't understand the first half. 
i am happy with magic number index if there are like < 3. i guess you can argue that these decode / encoder is simple enough that i think you can get away with magic numbers... in any case i'd like to understand the first half of your argument. 
</blockquote></details>

OK We spoke f2f; `snake_case` methods are required to be constant-time, and the `GetInputPort(string)` docs say "The current implementation performs a linear search over strings; prefer get_input_port() when performance is a concern.".

**Comment by jwnimmer-tri** [comment]
Self-reminder for future work: systems/primitives has StateInterpolatorWithDiscreteDerivative, which is likely what we should replace a lot of the LCM iiwa velocity ports with.

**Comment by jwnimmer-tri** [comment]
@siyuanfeng-tri please have another look (blocking on you).

**Pull request merged**
