### PR TITLE
Re-format mathematical_program code using clang-format-5.0.0

### PR DESCRIPTION
**Pull request by soonho-tri**
No semantic changes. Result of running `clang-format-5.0.0`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5743)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri , feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5743#-:-Kh1CbeBpoFMNz1zxtX9:bcq2m3k)*

**Comment by soonho-tri** [comment]
+@hongkai-dai , another feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5743#-:-Kh1EEP8OBCc-n54p8Ut:b-2xw504)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5743#-:-Kh2zIrojQztSYYv0NfJ:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5743#-:-Kh3-QEmb2OuPf4jRUPo:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5743#-:-Kh3-YJ7lCGOI1Rrv4yV:bg7igkv)*

**Pull request merged**
