### PR TITLE
[doc] Improve 1.16 release notes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19431)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy and +@SeanCurtis-TRI for review, please.

\CC @RussTedrake @wrangelvid in case you'd like to adjust the GCS overview text (probably in a follow-up PR, I assume this PR will merge somewhat quickly).

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19431#-:-NVkYwOs8gqa-k6vTIg7:bmxilld)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.16.0.md` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19431#-NVkYqsn4NwluZvcfC3V:-NVkYqsn4NwluZvcfC3W:b-ba9gls) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96a352f8b4d210f0ff19562d24b105ea0e2e5de/doc/_release-notes/v1.16.0.md#L18)):*
> ```Markdown
>   can be used with Drake's `RenderEngineGltfClient`.
> * Symbolic matrix multiplication in pydrake runs faster now if you call the
>   `pydrake.math.matmul` function instead of the `@` operator.
> ```

BTW Arguably, you have a verb-object dissonance here.

"Call the function", yes.

"Call the @ operator", not so much.



_Suggestion:_
```Markdown
* Symbolic matrix multiplication in pydrake runs faster now if you call the
  `pydrake.math.matmul` function instead of using the `@` operator.
```

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19431#-:-NVl0zmq1i7ZTYMGcCKU:bnfp4nl)* status: 1 unresolved discussion

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19431)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19431)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),DamrongGuoy

___
*[`doc/_release-notes/v1.16.0.md` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19431#-NVkYqsn4NwluZvcfC3V:-NVl4-5_8jJnP_wr2C_O:b8pg1ky) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96a352f8b4d210f0ff19562d24b105ea0e2e5de/doc/_release-notes/v1.16.0.md#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Arguably, you have a verb-object dissonance here.

"Call the function", yes.

"Call the @ operator", not so much.
</blockquote></details>

To me, `call the @ operator` is not grammatically problematic.  It is still a function call in fact.

**Pull request merged**
