### PR TITLE
Dummy template RigidBody on <T>

### PR DESCRIPTION
**Pull request by amcastro-tri**
Second check-box in #3987. More work towards full templatization of RBT. Essentially just a simple refactor that changes `RigidBody` by `RigidBody<double>`. `RigidBody<T>` is only used withing implementations already templated on `<T>` such as the automotive simulator and RigidBodyPlant.

This depends on RobotLocomotion/director#373 for CI testing of this PR and therefore the "do not merge label".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4124)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@ggould-tri for platform/feature review please since it is your day. We could have a feature review but this is just a simple refactor. 

---

Review status: 0 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-:-KWKJPEcW8peKc_kqvod:b-dc8ts1)*

**Comment by ggould-tri** [comment]
Small comments; :lgtm: once these are resolved.

---

Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.gitmodules, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOWUsQhUUWwc_9ryFB:-KWOWUsQhUUWwc_9ryFC:brja730) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/.gitmodules#L21)):*
> ```
> [submodule "externals/director"]
> 	path = externals/director
> 	url = https://github.com/amcastro-tri/director.git
> ```

Is this just a temporary change?  I would rather be pointing to a ref in a RobotLocomotion than to a personal repo.

---

*[drake/multibody/rigid_body.cc, line 326 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOY6a7mraNyY1OsOht:-KWOY6a8xTz1v8pfRYGU:bohxi5k) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/rigid_body.cc#L326)):*
> ```cpp
> }
> 
> // Explicitly instantiates on the most common scalar types.
> ```

yaaaay!  So glad to see things reaching this point.

---

*[drake/multibody/test/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOZaBFOksQOQ-efzyu:-KWOZaBFOksQOQ-efzyv:b5dhufa) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/test/CMakeLists.txt#L7)):*
> ```CMake
> 
> #add_executable(benchmark_rigid_body_tree benchmark_rigid_body_tree.cc)
> #target_link_libraries(benchmark_rigid_body_tree drakeRBM)
> ```

Commented out code -- please remove (if this should be gone) or add a TODO (if this is temporary for the duration of the refactor process).

---

*[drake/multibody/test/rigid_body_tree/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOZmv57BfOy1HVwgbn:-KWOZmv57BfOy1HVwgbo:bonkrq8) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/test/rigid_body_tree/CMakeLists.txt#L13)):*
> ```CMake
> 
> #drake_add_cc_test(rigid_body_tree_inverse_dynamics_test)
> #target_link_libraries(rigid_body_tree_inverse_dynamics_test drakeRBM)
> ```

Commented-out code; remove or add explanatory comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-:-KWO_PPQUw1BMTWNNRPe:b-3l88dx)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124)*

**Comment by amcastro-tri** [comment]
I addressed your comments @ggould-tri, thank you. PTAL

---

Review status: 52 of 54 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitmodules, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOWUsQhUUWwc_9ryFB:-KWmpjAR5_2Y-MP067zd:b-jb8saz) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/.gitmodules#L21)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Is this just a temporary change?  I would rather be pointing to a ref in a RobotLocomotion than to a personal repo.
</details>
Yes, it is a temporary change only together with the change to the external hash for Director. This is done in order to test director as well as drake within CI. As described [here](https://github.com/RobotLocomotion/drake/pull/4124#issue-188837137) this PR depends on RobotLocomotion/director#373 and therefore the "do not merge" label. 
Once I get the LGTM for this PR + CI passes we will get RobotLocomotion/director#373 merged, I will revert the change on  `.gitmodules` and update the hash to point to the new head in Director's repository.
We followed a similar procedure for #3940 and #4098 to make sure we can test both Drake and Director before merging these changes to master.

---

*[drake/multibody/rigid_body.cc, line 326 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOY6a7mraNyY1OsOht:-KWmqo0W-04zC1l0hd76:b3g3cau) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/rigid_body.cc#L326)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> yaaaay!  So glad to see things reaching this point.
</details>
I know right? and I can't wait to get rid of these awful explicit instantiations! it will happen in this quarter! Stay tuned. 

---

*[drake/multibody/test/CMakeLists.txt, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOZaBFOksQOQ-efzyu:-KWmviSOV2d4l1v_qsdd:bbzp2yi) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/test/CMakeLists.txt#L7)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Commented out code -- please remove (if this should be gone) or add a TODO (if this is temporary for the duration of the refactor process).
</details>
Oh wow, good catch! I commented those out while testing but should definitely not be there. Fixed.

---

*[drake/multibody/test/rigid_body_tree/CMakeLists.txt, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWOZmv57BfOy1HVwgbn:-KWmwSnBh--FAuDJ4mQ_:buq70ur) ([raw file](https://github.com/robotlocomotion/drake/blob/667ac66a02f0027e669cf81a6984c52c55367c0a/drake/multibody/test/rigid_body_tree/CMakeLists.txt#L13)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Commented-out code; remove or add explanatory comment.
</details>
Another good catch! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-:-KWmwt2ygAaBWWB0_pFZ:b-mnlvxa)*

**Comment by amcastro-tri** [comment]
@ggould-tri, RobotLocomotion/director#373 was merged and this PR is now passing CI. PTAL.

---

Review status: 50 of 53 files reviewed at latest revision, 4 unresolved discussions.

---

*[externals/director, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-KWnAl6_gb5gJK7LqtlR:-KWnAl6aKmoDo7W3JJDa:bs2b6m6) ([raw file](https://github.com/robotlocomotion/drake/blob/438c8f66adbc49315dad27e0a5a299384daea4a9/externals/director#L1)):*
> ```
> Subproject commit 807ba39190392343718461ce3113c9b83e3d0285
> ```

BTW, @ggould-tri notice I intentionally updated the hash here since RobotLocomotion/director#373 was merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124#-:-KWnKzsmYLI53bK1iJZ8:bn95pod)*

**Comment by ggould-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124)*

**Comment by patmarion** [comment]
fyi @amcastro-tri my PR was merged, so now your branch has a conflict because it is touching the director submodule.  sorry about that!  You branch sets the director submodule to the correct version, so you don't need to change that, but you need to rebase or merge master.

**Comment by amcastro-tri** [comment]
Yes, I just saw it, no worries. However, doesn't that PR then break Drake?

**Comment by ggould-tri** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4124)*

**Comment by patmarion** [comment]
> However, doesn't that PR then break Drake?

no, it set the director submodule to a version before I merged your `RigidBody<double>` change.

**Pull request merged**
