### PR TITLE
pycode tags

### PR DESCRIPTION
**Pull request by drewhamiltonasdf**
Seeing that I clearly have quite a bit to learn about contributing. I thought I'd start very conservatively. I have a bunch of these examples already cooked up.  Was planning on adding quite a few of these, and maybe tidying up any other funny stuff I run across in the docs like bad latex etc. but otherwise just trying to reproduce the c++ snippets.

@jwnimmer-tri  If there's anything you want me to know about this before I get carried away, do let me know.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri Would you be up for feature review?
+@EricCousineau-TRI for platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-:-NiFIjd-Avhgru3vu8p5:b-vd9glz)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @drewhamiltonasdf)

___
*[`math/barycentric.h` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFIobUBBmzC2zmCZzX:-NiFIobUBBmzC2zmCZzY:b-8sijlx) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L168)):*
> ```objc
>   /// @python_details_begin
>   /// @code{.py}
>   /// # Create an input grid as a list of sets
> ```

It's probably best to keep this code the exact same as the above C++ snippet.

My recommendation is to keep a bit more terse, and reflect the existing C++ code in Python, e.g.,
```
mesh_values = bary.MeshValuesFrom(lambda x: np.sin(x))
```
___
*[`math/barycentric.h` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFJ2JS1sQ8TeBPYRU9:-NiFJ2JT7ZEsaqJjSr3Q:bzi1488) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L178)):*
> ```objc
>   /// def mesh_value_function(x):
>   /// return np.sin(x)
>   /// 
> ```

nit Trailing whitespace.

If you are using VSCode, see https://stackoverflow.com/a/30884298/7829525
___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFJHxp8Ny0XrcTF3fC:-NiFJHxp8Ny0XrcTF3fD:budlfoh) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/bindings/pydrake/symbolic/_symbolic_extra.py#L33)):*
> ```Python
> 
> def to_sympy(
>     x: typing.Union[float, int, bool, Variable, Expression, Formula],
> ```

This seems to be carryover from another branch (same for below)

Can you remove this from the current PR?

**Comment by drewhamiltonasdf** [comment]
> +@jwnimmer-tri Would you be up for feature review? +@EricCousineau-TRI for platform
> 
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-:-NiFIjd-Avhgru3vu8p5:b-vd9glz)_ status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @drewhamiltonasdf)
> 
> _[`math/barycentric.h` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFIobUBBmzC2zmCZzX:-NiFIobUBBmzC2zmCZzY:b-8sijlx) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L168)):_
> 
> > ```objc
> >   /// @python_details_begin
> >   /// @code{.py}
> >   /// # Create an input grid as a list of sets
> > ```
> 
> It's probably best to keep this code the exact same as the above C++ snippet.
> 
> My recommendation is to keep a bit more terse, and reflect the existing C++ code in Python, e.g.,
> 
> ```
> mesh_values = bary.MeshValuesFrom(lambda x: np.sin(x))
> ```
> 
> _[`math/barycentric.h` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFJ2JS1sQ8TeBPYRU9:-NiFJ2JT7ZEsaqJjSr3Q:bzi1488) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L178)):_
> 
> > ```objc
> >   /// def mesh_value_function(x):
> >   /// return np.sin(x)
> >   /// 
> > ```
> 
> nit Trailing whitespace.
> 
> If you are using VSCode, see https://stackoverflow.com/a/30884298/7829525
> 
> _[`bindings/pydrake/symbolic/_symbolic_extra.py` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFJHxp8Ny0XrcTF3fC:-NiFJHxp8Ny0XrcTF3fD:budlfoh) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/bindings/pydrake/symbolic/_symbolic_extra.py#L33)):_
> 
> > ```python
> > def to_sympy(
> >     x: typing.Union[float, int, bool, Variable, Expression, Formula],
> > ```
> 
> This seems to be carryover from another branch (same for below)
> 
> Can you remove this from the current PR?

Yikes, smh. I must have branched from the Sympy updates. I'll address all this, but it may all show up in a new branch.

**Comment by EricCousineau-TRI** [comment]
If you're concerned about messing with Git history / diffs, you can always simplify what you revert, e.g.:
```sh
# be sure you've already committed / stashed everything you have in your working tree
git checkout $(git merge-base upstream/master HEAD) -- bindings/pydrake
# commit the reverted changes
```

This will generate an extra commit, but not a big deal if we're going to squash it upon merge.

**Review by jwnimmer-tri — COMMENTED** [review]
Sure, I can help review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-:-NiFrzr9-oqHQvjVeByq:b-9aas2c)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

___
*[`math/barycentric.h` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFIobUBBmzC2zmCZzX:-NiFs1-P313D3r4jbjNH:b-chw256) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L168)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's probably best to keep this code the exact same as the above C++ snippet.

My recommendation is to keep a bit more terse, and reflect the existing C++ code in Python, e.g.,
```
mesh_values = bary.MeshValuesFrom(lambda x: np.sin(x))
```
</blockquote></details>

I would perhaps clarify this as two different topics:

(1) For documentation where we provide both C++ sample code and Python sample code, they should be the _same_ sample.  The only differences should be things that are intrinsic to the two different languages (e.g., the syntax for a lambda, or where the sin function is imported from, etc.)  Providing two _different_ examples reduces clarity by conflating syntax changes with semantic exposition.

(2) For MeshValuesFrom in particular, what is the most useful sample code?  Do we need to show how to construct the `BaryCentricMesh` in the first place, or can we assume a local variable named `bary` (or maybe `barycentric_mesh`) already exists, and we only need to demonstrate how to operate this one function on it.

**Comment by drewhamiltonasdf** [comment]
> If you're concerned about messing with Git history / diffs, you can always simplify what you revert, e.g.:
> 
> ```shell
> # be sure you've already committed / stashed everything you have in your working tree
> git checkout $(git merge-base upstream/master HEAD) -- bindings/pydrake
> # commit the reverted changes
> ```
> 
> This will generate an extra commit, but not a big deal if we're going to squash it upon merge.

Well, I had a hell of a time with this, but the sympy stuff is gone. Somehow I have 1400+ changes to the commit history probably do to merging the drake master?

**Comment by drewhamiltonasdf** [comment]
> Sure, I can help review.
> 
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-:-NiFrzr9-oqHQvjVeByq:b-9aas2c)_ status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)
> 
> _[`math/barycentric.h` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFIobUBBmzC2zmCZzX:-NiFs1-P313D3r4jbjNH:b-chw256) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L168)):_
> Previously, EricCousineau-TRI (Eric Cousineau) wrote…
> 
> I would perhaps clarify this as two different topics:
> 
> (1) For documentation where we provide both C++ sample code and Python sample code, they should be the _same_ sample. The only differences should be things that are intrinsic to the two different languages (e.g., the syntax for a lambda, or where the sin function is imported from, etc.) Providing two _different_ examples reduces clarity by conflating syntax changes with semantic exposition.
> 
> (2) For MeshValuesFrom in particular, what is the most useful sample code? Do we need to show how to construct the `BaryCentricMesh` in the first place, or can we assume a local variable named `bary` (or maybe `barycentric_mesh`) already exists, and we only need to demonstrate how to operate this one function on it.

I think my experience as a user is a little different. I'd like to be able to very quickly copy and paste something with all the right types and extra machinery. A great example of the kind of browser-tab madness that can ensue if you are learning drake would be, say, constructing a Spatialinertia. In all likelihood, you will possibly have tabs open for SpatialInertia, UnitInertia, RotationalInertia, RotationMatrix, possibly RollPitchYaw etc. etc. It can take quite a while to build a pretty simple structure. 

It's possibly too patronizing for the typical Drake user, but I think scipy is great in this respect.

Take scipy.fft for example:

```python
from scipy.fft import fft, fftfreq, fftshift
import matplotlib.pyplot as plt
t = np.arange(256)
sp = fftshift(fft(np.sin(t)))
freq = fftshift(fftfreq(t.shape[-1]))
plt.plot(freq, sp.real, freq, sp.imag)
plt.show()
```
So much extra junk. They even include matplotlib so you can plop it down, probably into a notebook, get a quick visual and start tinkering. 

The alternative is to dig through the python tests in the github repo or page between manipulation/underactuated/jupyter tutorials/etc. Believe me, us new users have many many many tabs open.

Hope that wasn't too opinionated but that's sort of my new-user perspective. Just kicking up dust here in the beginning to see what you guys think.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[`math/barycentric.h` line 168 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20468#-NiFIobUBBmzC2zmCZzX:-NiLtW3PDMzO-jeiWPwa:b-vnx88i) ([raw file](https://github.com/RobotLocomotion/drake/blob/1eab23996c665bd8c0d41d41440206798ad98f1d/math/barycentric.h#L168)):*
I think this PR in its current state does not provide a good basis for back-and-forth discussion.  I'll bet that all of us reading it are extrapolating (i.e., imagining) different outcomes for how this documentation might look after a few more iterations of adding more content, e.g., if we wanted to provide examples for all functions on this entire class.

For example, if we extend this idea to other functions on this class, and the snippets are somewhat similar / redundant with each other, perhaps it'd be even _more_ clear to put a fully-worked example snippet in the class overview, instead of a medium-size snippets on each individual function one by one?  If the goal is to provide a cheat sheet all in one place for easy reference, I would imagine that a demo for the for the whole class is nicer than a demo of each function one by one.

To move this forward, I suggest that you rework this PR to propose how the docs for _all_ functions on this class should be updated (as well as the class overview), with whatever code snippets or extra text should be added.  That will provide us with a wider picture of what you have in mind as and end goal, which should lead to a more fruitful discussion.

> ... will possibly have tabs open for SpatialInertia, UnitInertia, RotationalInertia, RotationMatrix, possibly RollPitchYaw etc. etc.

Those classes are out of scope for this PR.  They have their own acute challenges with bad API design that also then make the documentation likewise bad.  This PR is _only_ about `class BarycentricMesh` and we shouldn't move the goalposts by referencing unrelated code in our discussion of what good or bad about _this_ particular class.

The only two things in scope here are:
- https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_barycentric_mesh.html
- https://drake.mit.edu/pydrake/pydrake.math.html#pydrake.math.BarycentricMesh

**Comment by drewhamiltonasdf** [comment]
> > Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20468)_ status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

@jwnimmer-tri After the above discussion I've decided to tuck away my larger ambitions for the moment. I'm going to just update pycode tags one by one to exactly match the c++ tags. I'm going to close this PR and re-open when I have a significant number of them done. Apologies for the headaches.

**Pull request closed without merging**
