### PR TITLE
Templatize DoEval in cost/constraint

### LINKED ISSUE #9068: Implement DoEvalGeneric for constraints and costs to factor out duplicates
From https://github.com/RobotLocomotion/drake/pull/9056#issuecomment-400732835

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #9068

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084#-:-LGGqd4s1AYPqB8_XpIh:bpno49v)*

**Comment by soonho-tri** [comment]
:lgtm:

+@jwnimmer-tri for platform-review, please.

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084#-:-LGQb3gO9JpQ2iaBktXE:bxptz4s)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [soonho-tri]

---

*[solvers/constraint.h, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQey4K5PGzxUVZaQr1:-LGQey4K5PGzxUVZaQr2:bfh7es8) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L247)):*
> ```objc
> 
>  private:
>   template <typename DerivedX, typename U>
> ```

_Meta_ Unclear why this is named `U` / what `U` means.  The usual shorthand for a Drake scalar is `T`.  (Another option would be `ScalarY`, for example.)

---

*[solvers/constraint.h, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQg1m-Dad2I9iR7IMj:-LGQg1m05SzDUyDUl8IJ:b-s2tmaq) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L620)):*
> ```objc
>  protected:
>   template <typename DerivedX, typename U>
>   void DoEvalGeneric(const Eigen::MatrixBase<DerivedX>& x, VectorX<U>* y) const;
> ```

Unclear why this is protected (vs private).

---

*[solvers/constraint.h, line 661 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQg9X22ikf-fckLl2i:-LGQg9X22ikf-fckLl2j:bsh66t9) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L661)):*
> ```objc
>   /** Return Mx + q (the value of the slack variable). */
>   template <typename DerivedX, typename U>
>   void DoEvalGeneric(const Eigen::MatrixBase<DerivedX>& x, VectorX<U>* y) const;
> ```

Unclear why this is protected.

---

*[solvers/test/constraint_test.cc, line 439 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQh3kJ3qT8iw9HxEz-:-LGQh3kK3sQODRLCje_q:b-7ui5jw) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/constraint_test.cc#L439)):*
> ```cpp
>                      VectorX<U>* y) const {
>     *y = c_ * x.template cast<U>();
>   }
> ```

nit Unclear why this is protected.

---

*[solvers/test/generic_trivial_constraints.h, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQgrpSB3TGu_g3-tv4:-LGQgrpSB3TGu_g3-tv5:b-7ui5jw) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/generic_trivial_constraints.h#L39)):*
> ```objc
>     (*y)(0) = x(0) * x(1) + x(2) / x(0) * private_val_;
>     (*y)(1) = x(1) * x(2) - x(0);
>   }
> ```

nit Unclear why this is protected.

---

*[solvers/test/generic_trivial_costs.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQgi6o0tche1RWTdW9:-LGQgi6o0tche1RWTdWA:b-7ui5jw) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/generic_trivial_costs.h#L34)):*
> ```objc
>     y->resize(1);
>     (*y)(0) = x(0) * x(1) + x(2) / x(0) * private_val_;
>   }
> ```

nit Unclear why this is protected.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by hongkai-dai** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [soonho-tri]

---

*[solvers/constraint.h, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQey4K5PGzxUVZaQr1:-LGQtmq97vo_z0CyPYIi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L247)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Unclear why this is named `U` / what `U` means.  The usual shorthand for a Drake scalar is `T`.  (Another option would be `ScalarY`, for example.)
</blockquote></details>

Done.

---

*[solvers/constraint.h, line 620 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQg1m-Dad2I9iR7IMj:-LGQtnyQ62mrk7fUmbUG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L620)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this is protected (vs private).
</blockquote></details>

Done.

---

*[solvers/constraint.h, line 661 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQg9X22ikf-fckLl2i:-LGQtpTBBv5Pm73SeEF0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/constraint.h#L661)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this is protected.
</blockquote></details>

Done.

---

*[solvers/test/constraint_test.cc, line 439 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQh3kJ3qT8iw9HxEz-:-LGQu1-a4LdYtq1eLCtx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/constraint_test.cc#L439)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why this is protected.
</blockquote></details>

Done.

---

*[solvers/test/generic_trivial_constraints.h, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQgrpSB3TGu_g3-tv4:-LGQuFOb2IGkQnF5jm3O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/generic_trivial_constraints.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why this is protected.
</blockquote></details>

Done.

---

*[solvers/test/generic_trivial_costs.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQgi6o0tche1RWTdW9:-LGQuOphEmNY2ywLGW4D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/495cd60d641b694bce9508062144940e64595cfb/solvers/test/generic_trivial_costs.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why this is protected.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: 1 unresolved discussion, platform LGTM from [soonho-tri, jwnimmer-tri]

---

*[solvers/constraint.h, line 684 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQytbs1rA7QUfPbHNs:-LGQytbs1rA7QUfPbHNt:bosafr5) ([raw file](https://github.com/robotlocomotion/drake/blob/ae255b9ad363a5f26f0f961cb0042477730b8647/solvers/constraint.h#L684)):*
> ```objc
> 
>  private:
>   /** Return Mx + q (the value of the slack variable). */
> ```

nit Don't use `/**` on non-Doxygen comments.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084#-:-LGQz7HE4MNuhsjNFaqx:bwkpaz3)*

**Comment by hongkai-dai** [comment]
Review status: all discussions resolved, platform LGTM from [soonho-tri, jwnimmer-tri], commit history needs curation

---

*[solvers/constraint.h, line 684 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9084#-LGQytbs1rA7QUfPbHNs:-LGS0pHs5mtkvWP-OPDg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae255b9ad363a5f26f0f961cb0042477730b8647/solvers/constraint.h#L684)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Don't use `/**` on non-Doxygen comments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all discussions resolved, platform LGTM from [soonho-tri, jwnimmer-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all discussions resolved, platform LGTM from [soonho-tri, jwnimmer-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all discussions resolved, platform LGTM from [soonho-tri, jwnimmer-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9084#-:-LGSOKLN1gs1MivVSYie:b-l70wzf)*

**Pull request merged**
