### PR TITLE
Add CalcJacobianPositionVector

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@seancurtis-tri 
Note: I may add some additional tests.
 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1I0a49NJ_DhMM5NYe:b-sikmgk)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I think we should have more people weigh in.

1. `multibody_plant.h` is a huge file already.
2. This is very much sugar -- `CalcJacobianTranslationalVelocity` already documents that `Jq̇_v_ABi = Jq_p_AoBi`.

So, this API would best serve someone like me that didn't have that thought in mind. Is it justified? Is it the case that an expected "typical" Drake user who is interested in computing Jacobians would need/benefit from this sugar?

cc @amcastro-tri @sherm1 @xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1JuywBU0b_RTkbgOC:b-40d6cg)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by mitiguy — COMMENTED** [review]
@seancurtis-tri  I appreciate that others should weigh in.

My opinion is that this is _not_ sugar.  ```Jq̇_v_ABi = Jq_p_AoBi``` does not seem obvious to me (and I would guess not for you) and its proof requires differentiation in a reference frame -- something that is not always well understood or done well.  Moreover, the code is clearer when the _function name_  in the call matches the _intent_ in that algorithm.  

A "typical" Drake user should not have to parse ≈ 38 lines in the following ``CalcJacobianTranslationalVelocity()``` documentation to uncover Jq̇_v_ABi = Jq_p_AoBi (which occurs at line ≈33).

```
  /// For each point Bi affixed/welded to a frame B, calculates J𝑠_v_ABi, Bi's
  /// translational velocity Jacobian in frame A with respect to "speeds" 𝑠.
  /// <pre>
  ///      J𝑠_v_ABi ≜ [ ∂(v_ABi)/∂𝑠₁,  ...  ∂(v_ABi)/∂𝑠ₙ ]    (n is j or k)
  ///      v_ABi = J𝑠_v_ABi ⋅ 𝑠          v_ABi is linear in 𝑠 ≜ [𝑠₁ ... 𝑠ₙ]ᵀ
  /// </pre>
  /// `v_ABi` is Bi's translational velocity in frame A and "speeds" 𝑠 is either
  /// q̇ ≜ [q̇₁ ... q̇ⱼ]ᵀ (time-derivatives of j generalized positions) or
  /// v ≜ [v₁ ... vₖ]ᵀ (k generalized velocities).
  ///
  /// @param[in] context The state of the multibody system.
  /// @param[in] with_respect_to Enum equal to JacobianWrtVariable::kQDot or
  /// JacobianWrtVariable::kV, indicating whether the Jacobian `J𝑠_v_ABi` is
  /// partial derivatives with respect to 𝑠 = q̇ (time-derivatives of generalized
  /// positions) or with respect to 𝑠 = v (generalized velocities).
  /// @param[in] frame_B The frame on which point Bi is affixed/welded.
  /// @param[in] p_BoBi_B A position vector or list of p position vectors from
  /// Bo (frame_B's origin) to points Bi (regarded as affixed to B), where each
  /// position vector is expressed in frame_B.
  /// @param[in] frame_A The frame that measures `v_ABi` (Bi's velocity in A).
  /// Note: It is natural to wonder why there is no parameter p_AoAi_A (similar
  /// to the parameter p_BoBi_B for frame_B).  There is no need for p_AoAi_A
  /// because Bi's velocity in A is defined as the derivative in frame A of
  /// Bi's position vector from _any_ point affixed to A.
  /// @param[in] frame_E The frame in which `v_ABi` is expressed on input and
  /// the frame in which the Jacobian `J𝑠_v_ABi` is expressed on output.
  /// @param[out] J𝑠_v_ABi_E Point Bi's velocity Jacobian in frame A with
  /// respect to speeds 𝑠 (which is either q̇ or v), expressed in frame E.
  /// `J𝑠_v_ABi_E` is a `3*p x n` matrix, where p is the number of points Bi and
  /// n is the number of elements in 𝑠.  The Jacobian is a function of only
  /// generalized positions q (which are pulled from the context).
  /// @throws std::exception if `J𝑠_v_ABi_E` is nullptr or not sized `3*p x n`.
  /// @note When 𝑠 = q̇, `Jq̇_v_ABi = Jq_p_AoBi`.  In other words, point Bi's
  /// velocity Jacobian in frame A with respect to q̇ is equal to point Bi's
  /// position Jacobian from Ao (A's origin) in frame A with respect to q. <pre>
  /// [∂(v_ABi)/∂q̇₁,  ...  ∂(v_ABi)/∂q̇ⱼ] = [∂(p_AoBi)/∂q₁,  ...  ∂(p_AoBi)/∂qⱼ]
  /// </pre>
  /// Note: Each partial derivative of p_AoBi is taken in frame A.
'''
```


> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1OfCv4ylq--Qr2xMN:blij4tn)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
I pinged @SeanCurtis-TRI about this.  Apparently this was motivated by some maybe-confusing code in Anzu.  This PR would be better-justified if the overview here cited the Anzu PR which ports Anzu to use this improved API.  Trying to review the API in a vacuum leads to confusion.

**Review by sherm1 — COMMENTED** [review]
I agree with Paul that this non-obvious sugar method is worthwhile. I don't think the vast length of MbP's API is actually a problem -- every multibody code I'm familiar with is like this and users are generally relieved to find the API they need in there somewhere. Important to have good naming and documentation, with "see also"s.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1Vrp3138xiCFjgQIR:bcuayqa)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @mitiguy and @SeanCurtis-TRI)

___
*[`multibody/plant/multibody_plant.h` line 3471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1UPkk80DUBy5Wc_mc:-NC1UPkk80DUBy5Wc_md:bybr5iy) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3471)):*
> ```objc
>   /// For each point Bi affixed/welded to a frame B, calculates Jq_p_AoBi, Bi's
>   /// position vector Jacobian in frame A with respect to the generalized
>   /// positions q ≜ [q₁ ... qₙ]ᵀ as
> ```

nit: although this looks nicer, I think it is best to start the math with 0 as we do in the actual code, to avoid trouble: q ≜ [q₀ ... qₙ₋₁]ᵀ
___
*[`multibody/plant/multibody_plant.h` line 3499 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1VWnm54zgvYhlVDJD:-NC1VWnm54zgvYhlVDJE:bgai7dv) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3499)):*
> ```objc
>   /// [∂(v_ABi)/∂q̇₁, ... ∂(v_ABi)/∂q̇ₙ] = [ᴬ∂(p_AoBi)/∂q₁, ... ᴬ∂(p_AoBi)/∂qₙ]
>   /// </pre>
>   /// Note: Jq_p_AaBi = Jq_p_AoBi, where point Aa is 𝑎𝑛𝑦 point fixed/welded to
> ```

nit: italics in Doxygen code should be done with `_any_` rather than Unicode 𝑎𝑛𝑦 to let Doxygen format it in the appropriate font.

**Review by mitiguy — COMMENTED** [review]
Related tangent: I agree that multibody_plant.h is large/huge.  However, this fact seems superfluous for determining whether or not this (or any) function belongs.  The hugeness is more of a developer problem and less of an end-user problem (particularly for Python users).  The logic suggests that the larger a file is, the more restriction to later addition of new functions (sounds NIMPY in an established neighborhood).  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1TdPo3ihs48GvK9Pn:b-rqvoxb)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @mitiguy and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm happy to defer to Sherm's opinion. He's a superior feature reviewer for this than I am, so I'm going to swap.

-@seancurtis-tri +@sherm1 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC1cXShBpnp5dabZUVf:bd9tklw)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @mitiguy and @sherm1)

**Review by mitiguy — COMMENTED** [review]
@sherm1   There is some copy/paste differences now in multibody_plant_jacobians_test.cc along with some new checks that specifically test the CalcJacobianPositionVector() against partial derivatives of position vectors with respect to generalized positions q (which is how we initially verified CalcJacobianTranslationalVelocity(), etc.).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC2B3bnCPNTI8bmxHG7:but9fai)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/plant/multibody_plant.h` line 3471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1UPkk80DUBy5Wc_mc:-NC291kb298CBtas7Zar:bzi3b0z) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3471)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: although this looks nicer, I think it is best to start the math with 0 as we do in the actual code, to avoid trouble: q ≜ [q₀ ... qₙ₋₁]ᵀ
</blockquote></details>

The notation for ```q ≜ [q₁ ... qₙ]ᵀ```  and their associated partial derivatives ```[ ᴬ∂(p_AoBi)/∂q₁,  ...  ᴬ∂(p_AoBi)/∂qₙ ]``` was chosen to be consistent with all the other CalcJacobian methods in multibody_plant.h., which includes copious documentation for:  ```CalcJacobianSpatialVelocity()```, ```CalcJacobianAngularVelocity()```,  and ```CalcJacobianTranslationalVelocity().```
___
*[`multibody/plant/multibody_plant.h` line 3499 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1VWnm54zgvYhlVDJD:-NC28uujEeI5-WoWWeJi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3499)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: italics in Doxygen code should be done with `_any_` rather than Unicode 𝑎𝑛𝑦 to let Doxygen format it in the appropriate font.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:
+@jwnimmer-tri for platform review please, per rotation (if you still have time today)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC2HAbO23Xaz0gXHm2Q:bbfxowt)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.h` line 3471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1UPkk80DUBy5Wc_mc:-NC2G7R357U084lvYEsg:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3471)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

The notation for ```q ≜ [q₁ ... qₙ]ᵀ```  and their associated partial derivatives ```[ ᴬ∂(p_AoBi)/∂q₁,  ...  ᴬ∂(p_AoBi)/∂qₙ ]``` was chosen to be consistent with all the other CalcJacobian methods in multibody_plant.h., which includes copious documentation for:  ```CalcJacobianSpatialVelocity()```, ```CalcJacobianAngularVelocity()```,  and ```CalcJacobianTranslationalVelocity().```
</blockquote></details>

OK

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

MbP is one of the classes where we want every public function to have pydrake bindings.  Please plan to add the bindings in a follow-up PR (or ask for help delegating that work to someone else); we don't want to forget to bind this function.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17920#-:-NC2JBXzEyg9R4KAB5kX:b7kgf5w)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/multibody_plant.h` line 3471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17920#-NC1UPkk80DUBy5Wc_mc:-NC2IArI5Kp5OOhzJJU0:b-5ms8sr) ([raw file](https://github.com/robotlocomotion/drake/blob/9a476142419115d11c1ce18ffb50ca6a595f1e24/multibody/plant/multibody_plant.h#L3471)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

OK
</blockquote></details>

I can get on board with "consistently wrong is better than occasionally correct" for now, but please do fix this across the board in a follow-up PR.  Sherm is correct that the "indices start from 1" is a real problem.

**Comment by mitiguy** [comment]
I am starting a new PR to work on Python bindings.

**Pull request merged**
