### PR TITLE
Move some more rotation conversions from drakeGeometryUtil into drake/math.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@sherm1 for feature and platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2779)

### CODE REVIEW

**Comment by sherm1** [comment]
Review pass done -- this is *so* much nicer! I made lots of by-the-way comments pointing out possible bugs and where eigen_types could be used to improve the code. I know you are just relocating code so if you don't feel like fixing these, please create an issue instead if you agree there are problems.

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[drake/math/axis_angle.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRC6F-WGZNMNns_uoC:-KMRC6F-WGZNMNns_uoD:-836938742) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L16)):*
> ```objc
> namespace math {
> template <typename Derived>
> Eigen::Vector4d axis2quat(const Eigen::MatrixBase<Derived>& a) {
> ```

It looks like a bug to me that this returns Vector4d. I would have expected Vector4<typename Derived::Scalar> like the other routines.

---

*[drake/math/axis_angle.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRCnAKYmW1jrbWjHUL:-KMRCnAL-nU8tkkkjuQE:637591852) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L29)):*
> ```objc
> 
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 3, 3> axis2rotmat(
> ```

BTW, this would be a great time to convert to `eigen_types` abbreviations. Here it would be `Matrix3<typename Derived::Scalar>` (that abbreviation might be missing currently).

---

*[drake/math/axis_angle.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRDKiT7FCOeTqgNvnm:-KMRDKiUD-addP-rbuqr:-64768344) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L49)):*
> ```objc
> 
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 3, 1> axis2rpy(
> ```

BTW, `Vector3<typename Derived::Scalar>`

---

*[drake/math/cylindrical.cc, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRDei9Ru0LuWFAAsfj:-KMRDei9Ru0LuWFAAsfk:124424283) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.cc#L12)):*
> ```cpp
> namespace internal {
> 
> Matrix3d rotz(double theta) {
> ```

BTW, odd that these are hard coded to `double`. But they are self-consistent.

---

*[drake/math/cylindrical.h, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRDuoDzqS0SHx_UYMY:-KMRDuoDzqS0SHx_UYMZ:-1675704433) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L34)):*
> ```objc
>                            drake::Vector6<Scalar>& x_cartesian,
>                            drake::Vector6<Scalar>& v_cartesian,
>                            Eigen::Matrix<Scalar, 6, 6>& J,
> ```

BTW, 6x6 matrix is very common in mechanical sim for the same reason that 6-vector is. Would be good to have `Matrix6<Scalar>`.

---

*[drake/math/cylindrical.h, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMREO75L0bdXOJ5Ye4z:-KMREO75L0bdXOJ5Ye5-:211075458) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L47)):*
> ```objc
>   double theta = x_cylinder(1);
>   double c_theta = cos(theta);
>   double s_theta = sin(theta);
> ```

BTW, I think this method should have local `using std::sin; using std::cos;` to ensure ADL works properly. I guess it is finding the C ones OK though.

---

*[drake/math/cylindrical.h, line 59 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRFQzHSApg1DFzWEPe:-KMRFQzHSApg1DFzWEPf:710888520) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L59)):*
> ```objc
>       radius * c_theta * theta_dot + radius_dot * s_theta, height_dot;
>   v_pos_cartesian = R_cylinder2cartesian * v_pos_cartesian;
>   Eigen::Vector3d x_rpy_cylinder = x_cylinder.block(3, 0, 3, 1);
> ```

BTW, is this `Vector3d` a bug? The source is a `Scalar` not a `double`.

---

*[drake/math/cylindrical.h, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRF8DUD6_-IrY-F76_:-KMRF8DUD6_-IrY-F76a:1038487914) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L60)):*
> ```objc
>   v_pos_cartesian = R_cylinder2cartesian * v_pos_cartesian;
>   Eigen::Vector3d x_rpy_cylinder = x_cylinder.block(3, 0, 3, 1);
>   Eigen::Matrix<Scalar, 3, 3> R_tangent = rpy2rotmat(x_rpy_cylinder);
> ```

BTW, `Matrix3<Scalar>`.

---

*[drake/math/cylindrical.h, line 112 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRFmTSch3ilSIUIOKb:-KMRFmTSch3ilSIUIOKc:-659237052) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L112)):*
> ```objc
>   drake::Vector3<Scalar> cylinder_x_dir =
>       m_cylinder_x_dir / m_cylinder_x_dir.norm();
>   Eigen::Matrix<Scalar, 3, 3> R_cylinder2cartesian;
> ```

BTW, `Matrix3<Scalar>`

---

*[drake/math/cylindrical.h, line 134 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRG1aDnJ6c-5atKMiW:-KMRG1aDnJ6c-5atKMiX:2077760363) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L134)):*
> ```objc
>                      radius_square;
>   double height = x_pos_cylinder(2);
>   double height_dot = v_pos_cylinder(2);
> ```

BTW, are all these `double` variables right? Should the input arguments be cast from `Scalar` to `double`? That would invoke built-in sqrt,pow,atan2; here I think the Scalar's methods of those names are invoked but the result converted to double. Also, I think the method should have local `using std::sqrt, std::pos, std::atan2` for tidy ADL.

---

*[drake/math/quaternion.h, line 135 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRHCLPD92ma3Tb0gkH:-KMRHCLPD92ma3Tb0gkI:-538127044) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/quaternion.h#L135)):*
> ```objc
> 
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 4, 1> quat2axis(
> ```

BTW, `Vector4 ...`. Many more such improvements possible below but I'll stop pointing them out.

---

*[drake/math/quaternion.h, line 140 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRHHhy3s4A00IxsE1s:-KMRHHhzsZpKBksye35N:397173049) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/quaternion.h#L140)):*
> ```objc
>   auto q_normalized = q.normalized();
>   auto s = std::sqrt(1.0 - q_normalized(0) * q_normalized(0)) +
>            std::numeric_limits<typename Derived::Scalar>::epsilon();
> ```

BTW, what's going on here with the conversions from Scalar to double? Is this right? Won't this break an attempt to AutoDiff this thing?

---

*[drake/math/quaternion.h, line 149 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRHvBtvERMETqDujsf:-KMRHvBuM1CJhaR84xGo:-513363061) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/quaternion.h#L149)):*
> ```objc
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 3, 3> quat2rotmat(
>     const Eigen::MatrixBase<Derived>& q) {
> ```

BTW, in constrast this method carefully preserves Scalar all the way through.

---

*[drake/math/quaternion.h, line 181 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRI1-jZ9KwIuAkMNpR:-KMRI1-jZ9KwIuAkMNpS:963677000) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/quaternion.h#L181)):*
> ```objc
>   ret << std::atan2(2.0 * (w * x + y * z), w * w + z * z - (x * x + y * y)),
>       std::asin(2.0 * (w * y - z * x)),
>       std::atan2(2.0 * (w * z + x * y), w * w + x * x - (y * y + z * z));
> ```

BTW, weird mix of double and Scalar again.

---

*[drake/math/roll_pitch_yaw.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRIO3qOzEAtOnGAbrl:-KMRIO3qOzEAtOnGAbrm:700784506) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/roll_pitch_yaw.h#L20)):*
> ```objc
>   auto c = rpy_2.cos();
> 
>   Eigen::Vector4d q;
> ```

BTW, double?

---

*[drake/math/rotation_matrix.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRIeZeNHb7-930vgMc:-KMRIeZeNHb7-930vgMd:-1228297485) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/rotation_matrix.h#L17)):*
> ```objc
>   EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE(Eigen::MatrixBase<Derived>, 3, 3);
> 
>   typename Derived::Scalar theta = std::acos((R.trace() - 1.0) / 2.0);
> ```

BTW, I think this wrecks AutoDiff by working in double, then converting to a virgin AutoDiffScalar which won't have any of the derivative part.

---

*[drake/math/rotation_matrix.h, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRJADgyiaeTubk2LRl:-KMRJADgyiaeTubk2LRm:-2096202137) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/rotation_matrix.h#L93)):*
> ```objc
>     const Eigen::MatrixBase<Derived>& R) {
>   EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE(Eigen::MatrixBase<Derived>, 3, 3);
>   using namespace std;
> ```

BTW, should just list the 3 required methods. But I do think this is the correct way to ensure proper ADL when the methods are invoked below.

---

*[drake/math/test/rotation_conversion_test.cc, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRJn5rhJK8QWu4R4It:-KMRJn5rhJK8QWu4R4Iu:1572384087) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/test/rotation_conversion_test.cc#L43)):*
> ```cpp
>   auto a = quat2axis(q_);
>   auto q_back = axis2quat(a);
>   EXPECT_NEAR(acos(std::abs(q_.transpose() * q_back)), 0.0, 1e-6);
> ```

Can you make the tolerances here more like 1e-14? That's about what these should give in double precision. Simbody has a constant called "SignificantReal" that has that value in double -- any analytic calculation that doesn't involve big matrices should be able to deliver that much (relative) precision since individual operations make errors around 2e-16. 1e-6 leaves 8 orders of magnitude in which bugs can hide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMRLWuBK5m4X3iILhhD:-176052274)*

**Comment by sherm1** [comment]
CI failed, possibly with real errors.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMRMLmAr_zvsT0ZIY_x:-495575002)*

**Comment by david-german-tri** [comment]
Review status: 28 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/axis_angle.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRC6F-WGZNMNns_uoC:-KMUEcZLd6aXMtpJp0HK:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> It looks like a bug to me that this returns Vector4d. I would have expected Vector4<typename Derived::Scalar> like the other routines.
</details>
Done.

---

*[drake/math/axis_angle.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRCnAKYmW1jrbWjHUL:-KMUGAl70exPX5JQqiwr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this would be a great time to convert to `eigen_types` abbreviations. Here it would be `Matrix3<typename Derived::Scalar>` (that abbreviation might be missing currently).
</details>
Done.

---

*[drake/math/axis_angle.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRDKiT7FCOeTqgNvnm:-KMUGEGMZp0oR08noRSN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/axis_angle.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `Vector3<typename Derived::Scalar>`
</details>
Done.

---

*[drake/math/cylindrical.h, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRDuoDzqS0SHx_UYMY:-KMUGJrre6JEy1XQ92XM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, 6x6 matrix is very common in mechanical sim for the same reason that 6-vector is. Would be good to have `Matrix6<Scalar>`.
</details>
Done.

---

*[drake/math/cylindrical.h, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMREO75L0bdXOJ5Ye4z:-KMUGKAle2sFx1Fhowih:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I think this method should have local `using std::sin; using std::cos;` to ensure ADL works properly. I guess it is finding the C ones OK though.
</details>
Done.

---

*[drake/math/cylindrical.h, line 59 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRFQzHSApg1DFzWEPe:-KMUGWnnk8_8aGDbV8X0:667368042) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, is this `Vector3d` a bug? The source is a `Scalar` not a `double`.
</details>
I don't know, so I'm going to leave it untouched for the time being.

---

*[drake/math/cylindrical.h, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRF8DUD6_-IrY-F76_:-KMUGNILtJuG09V8Bstw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `Matrix3<Scalar>`.
</details>
Done.

---

*[drake/math/cylindrical.h, line 112 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRFmTSch3ilSIUIOKb:-KMUGZGB7aujBLA2KRGi:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L112)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `Matrix3<Scalar>`
</details>
Done.

---

*[drake/math/cylindrical.h, line 134 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRG1aDnJ6c-5atKMiW:-KMUGycryeCR_zsqYjgM:356806829) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/cylindrical.h#L134)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, are all these `double` variables right? Should the input arguments be cast from `Scalar` to `double`? That would invoke built-in sqrt,pow,atan2; here I think the Scalar's methods of those names are invoked but the result converted to double. Also, I think the method should have local `using std::sqrt, std::pos, std::atan2` for tidy ADL.
</details>
Done the `std` part.  Leaving the doubles for now for the same reason as above.

---

*[drake/math/quaternion.h, line 135 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRHCLPD92ma3Tb0gkH:-KMUHD7RgQBoZVxDUvCx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/quaternion.h#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `Vector4 ...`. Many more such improvements possible below but I'll stop pointing them out.
</details>
Done.

---

*[drake/math/test/rotation_conversion_test.cc, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMRJn5rhJK8QWu4R4It:-KMUF-W_pmlpImC3LYCn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec2a490a3c145b94809fe6806b02de8478a763d/drake/math/test/rotation_conversion_test.cc#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Can you make the tolerances here more like 1e-14? That's about what these should give in double precision. Simbody has a constant called "SignificantReal" that has that value in double -- any analytic calculation that doesn't involve big matrices should be able to deliver that much (relative) precision since individual operations make errors around 2e-16. 1e-6 leaves 8 orders of magnitude in which bugs can hide.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779)*

**Comment by sherm1** [comment]
:lgtm:, pending CI. I agree with your decision not to mess with the potential double/Scalar bugs now but I'm wondering if there is a practical way to make a note of them for addressing in the future. TODOs in code? A separate issue? It seems unlikely that we'll notice them again otherwise and I suspect they will break derivatives (possibly very subtly) at some point in the future.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMU_epcmKj-85KUpk2o:-1394481712)*

**Comment by david-german-tri** [comment]
Interestingly, the `rotation_conversion_test` fails with the 1e-14 tolerances.  The errors seem to be on the order of 1e-8.  I have no idea if that's a real bug or not, but I've switched back to 1e-6 for now.

---

Review status: 36 of 38 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMUaj3JzmYLEnf332kB:1977959222)*

**Comment by david-german-tri** [comment]
Opened issue #2786 for the double/Scalar bugs.

---

Review status: 36 of 38 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMUdZzJZbQiFgqKBlmm:338041632)*

**Comment by david-german-tri** [comment]
I'm now debugging a Windows-specific error in that same test: "SEH exception with code 0xc0000005".  

https://drake-jenkins.csail.mit.edu/job/experimental/2614/compiler=msvc-ninja-32,label=windows/console

#2501

---

Review status: 36 of 38 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMUj_RtePNOtnArwypt:-1746742755)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for additional platform review.

---

Review status: 36 of 38 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMV0Pw28k1GzsTTUtXa:1275137336)*

**Comment by jwnimmer-tri** [comment]
Reviewed 28 of 36 files at r1, 8 of 9 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[drake/math/rotation_matrix.h, line 110 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVGt6RdajbC_4rT362:-KMVGt6RdajbC_4rT363:-1384825877) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/math/rotation_matrix.h#L110)):*
> ```objc
>   typedef typename Derived::Scalar Scalar;
>   switch (rotation_type) {
>     case 0:
> ```

BTW Slightly sad about the magic numbers here.  Existing conditions, though.

---

*[drake/systems/plants/test/testAccelerometer.cpp, line 29 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEGJcCpMDQyNxqC_d:-KMVEGJdehN3e_0tGjXZ:1715061627) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/testAccelerometer.cpp#L29)):*
> ```cpp
>   auto const& tree = sys->getRigidBodyTree();
>   x0.head(tree->number_of_positions()) = tree->getZeroConfiguration();
>   x0.segment(3, 4) = ::drake::math::rpy2quat(rpy);
> ```

BTW is the odd leading `::` really required?

---

*[drake/systems/plants/test/testMagnetometer.cpp, line 29 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEJQY9m4sJQ-ZEfEb:-KMVEJQY9m4sJQ-ZEfEc:1715061627) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/testMagnetometer.cpp#L29)):*
> ```cpp
>   auto const& tree = sys->getRigidBodyTree();
>   x0.head(tree->number_of_positions()) = tree->getZeroConfiguration();
>   x0.segment(3, 4) = ::drake::math::rpy2quat(rpy);
> ```

BTW is the odd leading `::` really required?

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEMnTz1E-elk6Vnnl:-KMVEMnUIWETBsesqNNB:1715061627) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L71)):*
> ```cpp
>     rpy = Eigen::Vector3d::Zero();
>     T_second_model_to_world.matrix()
>         << ::drake::math::rpy2rotmat(rpy), xyz, 0, 0, 0, 1;
> ```

BTW is the odd leading `::` really required?

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 97 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEPNOY_VHIstYOJx6:-KMVEPNPqZV30FSH76tw:-1296462680) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L97)):*
> ```cpp
>     rpy = Eigen::Vector3d::Zero();
>     T_r1and2_to_world.matrix()
>         << ::drake::math::rpy2rotmat(rpy), xyz, 0, 0, 0, 1;
> ```

BTW is the odd leading `::` really required (META in this file)?

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 163 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVFaT_5oOA4YVirJaL:-KMVFaTajhoo0-WA5hDU:1703111186) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/util/test/testDrakeGeometryUtil.cpp#L163)):*
> ```cpp
> }
> 
> GTEST_TEST(DrakeGeometryUtilTest, drpy2rotmat) {
> ```

Unclear to my why this test didn't get relocated?  Isn't it only testing functions that have been relocated?  (Maybe I'm missing something.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779)*

**Comment by david-german-tri** [comment]
Review status: 32 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/testAccelerometer.cpp, line 29 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEGJcCpMDQyNxqC_d:-KMVMcSh97y_6Y6N1fhZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/testAccelerometer.cpp#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW is the odd leading `::` really required?
</details>
Done.

---

*[drake/systems/plants/test/testMagnetometer.cpp, line 29 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEJQY9m4sJQ-ZEfEb:-KMVMdjamTvgE6NfRpIs:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/testMagnetometer.cpp#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW is the odd leading `::` really required?
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEMnTz1E-elk6Vnnl:-KMVMhFnDeqpwqianUUL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW is the odd leading `::` really required?
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 97 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVEPNOY_VHIstYOJx6:-KMVMiET3QbWXsIGlOC8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW is the odd leading `::` really required (META in this file)?
</details>
Done.

---

*[drake/util/test/testDrakeGeometryUtil.cpp, line 163 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-KMVFaT_5oOA4YVirJaL:-KMVM5LoQHwrg95WKzEF:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/e27c732c5bd59304694d05ddfc277d810ca5b9f5/drake/util/test/testDrakeGeometryUtil.cpp#L163)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unclear to my why this test didn't get relocated?  Isn't it only testing functions that have been relocated?  (Maybe I'm missing something.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779#-:-KMVNM7ggkhZtSsSGwB_:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2779)*

**Pull request merged**
