### PR TITLE
Bump snopt to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates RobotLocomotion/snopt#21.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7554)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review per schedule, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7554#-L-YhzHhVjtGHSFbcMvT:-L-YhzHhVjtGHSFbcMvU:b-luwpg6) ([raw file](https://github.com/robotlocomotion/drake/blob/253b253f022bd4ce67e18200d5479e4d32c65920/WORKSPACE#L314)):*
> ```Python
> )
> 
> git_repository(
> ```

BTW I ran into an issue with this on a flight - is there a reason why we use `git_repository` rather than `github_archive` here? I was building this with crappy internet access, and could not do a clean build because this was not using `--experimental_repository_cache`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7554#-:-L-YinKC4Vt3kp9x2nHL:b-2zsnay)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7554#-L-YhzHhVjtGHSFbcMvT:-L-YlTFl__WxkTfgZnkM:b4syvhi) ([raw file](https://github.com/robotlocomotion/drake/blob/253b253f022bd4ce67e18200d5479e4d32c65920/WORKSPACE#L314)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I ran into an issue with this on a flight - is there a reason why we use `git_repository` rather than `github_archive` here? I was building this with crappy internet access, and could not do a clean build because this was not using `--experimental_repository_cache`.
</blockquote></details>

The repository is not public; it requires authentication.  Our `github_archive` doesn't (yet, easily) support that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7554)*

**Comment by EricCousineau-TRI** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[WORKSPACE, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7554#-L-YhzHhVjtGHSFbcMvT:-L-YmaVi7n8A3Ob0bL13:b-k6dfi) ([raw file](https://github.com/robotlocomotion/drake/blob/253b253f022bd4ce67e18200d5479e4d32c65920/WORKSPACE#L314)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The repository is not public; it requires authentication.  Our `github_archive` doesn't (yet, easily) support that.
</blockquote></details>

Gotcha. Could this be added as a comment here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7554)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7554#-L-YhzHhVjtGHSFbcMvT:-L-YnVkR8U9PavWUXYlB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/253b253f022bd4ce67e18200d5479e4d32c65920/WORKSPACE#L314)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Gotcha. Could this be added as a comment here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7554)*

**Pull request merged**
