### PR TITLE
[parsing] Add warning for unsupported joint actuators

### LINKED ISSUE #17179: Universall and Ball joint parsed from a SDF do not create actuators when effort>0 and ignore the limits
Universall and Ball joint parsed from a SDF do not create actuators when effort>0. 
In addition, the limits are ignored. There is an SDF for testing:
https://github.com/JoseBarreiros-TRI/drake/blob/e19141ff36a102d52cef29f10dc3424a39cbb853/examples/ruxid/python_humanoid_sim/models/humanoid_v1_copy.sdf

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17179.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17178)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please (low priority).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@rpoyner-tri for platform review (Tuesday rotation, today is @jwnimmer-tri )

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17178#-:-N2C6IVa81O_yyxEpE16:b-7td6k5)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo maybe

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17178#-:-N2CdQNeB3YJ3r4ldVjS:b37lge3)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 347 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17178#-N2Cb3Ag8jnFSp2yeaWG:-N2Cb3Ag8jnFSp2yeaWH:b-7ilvfu) ([raw file](https://github.com/robotlocomotion/drake/blob/b52e4149583eac5efee4dee5ef644ac973e0b7b7/multibody/parsing/detail_sdf_parser.cc#L347)):*
> ```cpp
>       joint_spec.Type() == sdf::JointType::BALL);
> 
>   // If the axis is missing, we'll rely on ExtractJointAxis to report her.
> ```

typo?



_Code quote:_
```cpp
her
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17178)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17178)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
