### PR TITLE
Include underactuated and manipulation in "Search all of Drake"

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds underactuated.csail.mit.edu and manipulation.csail.mit.edu to the search provided by duckduckgo. According to online discussions (like https://www.reddit.com/r/duckduckgo/comments/gcabk5/multiple_site_search_not_working/) and my testing, I believe using the OR is the recommended syntax.

+@jwnimmer-tri for feature review, please?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Do you have some example search terms where the additional search scope helps the results?

I liked this idea in theory, but in practice it doesn't seem great for some things I tried:

I tried searching for these, and the results with the new search are much worse than the old search:
- context
- inverse kinematics
- scene graph

These were possibly slightly improved, but kind of a wash:
- motion planning
- trajectory optimization

I wonder if we'd do better by adding more links from our existing website docs into the courses -- maybe in some class overviews (to cite examples of how to use it), or even in the https://drake.mit.edu/doxygen_cxx/modules.html overview, where we link directly to the course book materials that are relevant for that specific topic.

**Comment by RussTedrake** [comment]
i agree with you.  google does much better with the same search

https://www.google.com/search?q=spline+site:drake.mit.edu+OR+site:underactuated.csail.mit.edu+OR+site:manipulation.csail.mit.edu

https://www.google.com/search?q=inverse+kinematics+site%3Adrake.mit.edu+OR+site%3Aunderactuated.csail.mit.edu+OR+site%3Amanipulation.csail.mit.edu

I'm afraid to ask, but is there a reason to not use google over duckduckgo?

**Comment by jwnimmer-tri** [comment]
The main reason was to avoid the administrative headache of creating and maintaining the custom search auth token.  The ddg search was OK without any special auth, but as I understand it for google we need to do extra steps to enable it, and document & track those steps in our CI bookkeeping.  All do-able, but so far that hadn't been any reason to switch.

**Comment by RussTedrake** [comment]
This appears to work (without any additional infrastructure? perhaps I am missing something:
```

  <form id="searchform" action="https://google.com/search" method="get">
    <input type="text" name="q" id="box" placeholder="Search these notes..." />
  </form>
  <script>
    searchform.addEventListener('submit', function() {
      box.value = box.value + ' site:manipulation.csail.mit.edu';
    })
  </script>
  ```

**Comment by RussTedrake** [comment]
I put it here: https://manipulation.csail.mit.edu/index.html

**Comment by RussTedrake** [comment]
I've pushed a version using google as a second commit, for your consideration

**Comment by jwnimmer-tri** [comment]
> This appears to work (without any additional infrastructure? perhaps I am missing something ...

The discussions at https://github.com/RobotLocomotion/drake/issues/7559#issuecomment-351731534 led me to think site search _required_ a cse, but reading again now that was never directly stated.  So probably this does work OK.

With my schedule this week I won't be able to review until next week.  If you're interesting in landing it sooner, maybe @sherm1 or someone would like to take over review.  The review here doesn't require any special expertise, just a willingness to rebuild the new website locally and take it for a spin.

**Review by sherm1 — COMMENTED** [review]
I'll take it for a spin. +@sherm1

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNbuZItC_jm_LXXsz53:b-vyl8pu)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
So far the search looks OK but the search box has some odd behavior:


Part of the search code is showing up in the search box (that's after I've searched for something and then used the back arrow to return to the main page. In order to do another search I have to select that code to replace it with my search terms.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNcHCIpAyW90hKXQ_6c:b-99xrqy)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by RussTedrake — COMMENTED** [review]
Yes, that's expected (but I thought tolerable) behavior?  I didn't find a better way to send to google's search on my initial inspection.

I do think that the quality of the search results, w/ or w/o underactuated and manipulation is much better than with duckduckgo.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNceyxr36burLNCs40R:b-xhlq30)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

**Comment by jwnimmer-tri** [comment]
I don't think the stray text in the box is acceptable.  Searching multiple times with the back button seems like a common operation, and the stray text remaining there is confusing.  At worst, we should add a javascript to manually strip it out when the user returns to the page.

On another tack, this answer https://stackoverflow.com/a/42926071 suggests that `<input name="sitesearch" type="hidden" value="example.com">` might also work, without changing `q`.

**Review by sherm1 — COMMENTED** [review]
I agree the search is much better. The duckduckgo version does manage to avoid leaving junk around in the search box though. Would be good to fix that if possible. Otherwise :lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNcgqoh6WYV0jnhZbiN:b-d150tk)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I found a syntax that works; I just pushed it for the main site for now.  I can cycle back later and do the two API sites if nobody beats me to it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNhs4Ew-c7fbAgdoSCa:b7v0znw)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by RussTedrake — COMMENTED** [review]
Thanks Jeremy.  Should be all set now.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNiaF4h0qfLgo6GmZhS:b6hdmqg)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-:-NNid18X9w-TMwKhmMX9:b-vtj4vo)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`doc/doxygen_cxx/header.html.patch` line 70 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-NNicqRYAb2lpnkEybn4:-NNicqRZ5L2e8CuJAsMH:bs76f10) ([raw file](https://github.com/RobotLocomotion/drake/blob/14b74842c7e81a4ead1fceb8ac60c33504eb5e10/doc/doxygen_cxx/header.html.patch#L70)):*
> ```Diff
> +  </form>
> +  <script>
> +    search_form_cpp.addEventListener('submit', function() {
> ```

nit It will be a bit before I can test this locally, but to check -- should this still be javascript?  I can't quite tell.

Feel free to dismiss if its working well for you.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/doxygen_cxx/header.html.patch` line 70 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18737#-NNicqRYAb2lpnkEybn4:-NNijval45FmD0T_kahT:b-46lkrp) ([raw file](https://github.com/RobotLocomotion/drake/blob/14b74842c7e81a4ead1fceb8ac60c33504eb5e10/doc/doxygen_cxx/header.html.patch#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It will be a bit before I can test this locally, but to check -- should this still be javascript?  I can't quite tell.

Feel free to dismiss if its working well for you.
</blockquote></details>

Done.  You're right, I missed that one.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18737)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
