### PR TITLE
Polished a comment for increased clarity.

### PR DESCRIPTION
**Pull request by liangfok**
This is a useful reference: http://stackoverflow.com/a/1143272

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4707)

### CODE REVIEW

**Comment by liangfok** [comment]
Trivial documentation-only change. 

+@sherm1 for both levels of review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4707#-:-K_vybjI49_P-kU2Uxzn:b-nmgj0q)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4707#-:-K_zjEtaMmMW0Hc9OeNJ:bnfp4nl)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4707)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Pull request merged**
