### PR TITLE
Add instructions to upgrade crate_universe monthly

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add a paragraph to the monthly upgrades documentation that describes how to perform the crate_universe upgrade. Note that this should be done as a 'cohort' with clarabel_cpp if/when that is upgraded.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20815)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for (feature? both?) review, please. (Probably doesn't need platform as it's just documentation / internal process changes.)

**Comment by mwoehlke-kitware** [comment]
+(status: do not merge) until we figure out why `upgrade.sh` seems to be not working. (See also #20815.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: this procedure is fine by me.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20815#-:-NoyqSzS7177uM-7ufuo:bbud1ul)* status: labeled "do not merge" (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
-(status: do not merge)

**Pull request merged**
