### PR TITLE
[examples] Add bell pepper to hardware_sim

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a nice example of the syntax for posing a free body, towards #19651.

(It also serves as a more useful test case for #21512.)

image

(Note that due to https://github.com/RobotLocomotion/drake/issues/16538#issuecomment-2019190414 you can't see the contact force arrow unless you look under the table.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21558)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI FYI about something I'm considering.  Happy to take your thoughts.

Possibly we want to land this until we are further on the RTR exploration, but having our demo show a free body seems like a nice win on its own, even without any RTR-demo implications.

**Review by SeanCurtis-TRI — COMMENTED** [review]
"The syntax" in this case, referring to the posing of a "free" body w.r.t. another body, yes? A comment in the scenario file calling that out would serve a greater pedagogical role.

I also am unclear on the reasons to delay this vis a vis RTR. Introducing a free body to `HardwareSim` seems a perfectly laudable thing to do, independent of what games we might play with the behavior of GUI elements.

So, as to that. :LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21558#-:-O-3XQzZDk1QxX2aVUKw:bw7d5ac)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
To help play with RTR feedback, we might choose to use a different body (e.g. plate instead of pepper), or have more than one body, or etc.  We can always circle back and open a new PR, but possibly we could just keep this one open and tweak it in concert with RTR debugging.  There's no great rush on improving this syntax demo.

Anyway, I'll plan to add some more comment(s) and then probably land this sooner than later.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21558#-:-O-7Mta8DhoVYULHIhVh:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21558)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
