### PR TITLE
Use DRAKE_THROW_UNLESS in cost/constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned by Jeremy in his comment https://github.com/RobotLocomotion/drake/issues/21578#issuecomment-2174242791

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-:-O0jGce-1ZdBsZSeZr4W:be2t5nx)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
BTW would be nice if these error conditions were documented in the API Doxygen comments. However, they weren't documented before and this is a definite improvement, so :lgtm: x 2.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-:-O0jJHzp5o3guwRglpUn:bv7nl8r)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Review by hongkai-dai — COMMENTED** [review]
Done, I added the documentation.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-:-O0kjuwy4aEoxCMHBcEh:bknkcxh)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Thanks, @hongkai-dai! There is a specific format for those `@throw`s -- PTAL below.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-:-O0kvICLDkpHp0Kmj28Z:bqpytr4)* status: 1 unresolved discussion

___
*[`solvers/constraint.h` line 95 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-O0kugZECGkk2oRneVTy:-O0kugZECGkk2oRneVTz:bf9wm9i) ([raw file](https://github.com/RobotLocomotion/drake/blob/d31c90edbd635f9f9887a81b3044cdc6629c8794/solvers/constraint.h#L95)):*
> ```objc
>    * Return whether this constraint is satisfied by the given value, `x`.
>    * @param x A `num_vars` x 1 vector. @throws an exception if the size isn't
>    * correct.
> ```

minor: the `@throw` or `@throws` Doxygen command should be on a separate line, and has a specified syntax to use:


For example:
```
@throws std::exception if the size isn't correct
```

Same comment for the other `@throws` here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`solvers/constraint.h` line 95 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-O0kugZECGkk2oRneVTy:-O0oA1iMBb1dbGx0qT4H:boyexb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/d31c90edbd635f9f9887a81b3044cdc6629c8794/solvers/constraint.h#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the `@throw` or `@throws` Doxygen command should be on a separate line, and has a specified syntax to use:


For example:
```
@throws std::exception if the size isn't correct
```

Same comment for the other `@throws` here.
</blockquote></details>

Done. Thanks!

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21654#-:-O0oGuD46BLzUwJHnZlG:b4xzgsb)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
