### PR TITLE
workspace: warn instead of error for macOS Big Sur

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #13648. I am not doing anything to fix the several errors anytime soon, unfortunately, but this at least does not put up an artificial block if someone wants to help me out.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14391)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14391)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14391#-:-MNPycXf-tdEyLER2Jtd:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  Seems reasonable.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14391#-:-MNQ4DOO6hJhZSwJFnSB:balees8)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),soonho-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
