### PR TITLE
[pydrake] Breakout core geometry elements

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Moves a portion of the bindings in `geometry_py_all.cc` into `geometry_py_core.cc`. The unit tests for those bindings move into a parallel test (`geometry_core_test.py`).

The "core" elements include the various types in the drake::geometry namespace that represent the "core" geometry concepts: instances, frames, properties. These don't depend on any of geometry's computational structure, but, instead, represent the input values to all of those computations.

Relates #15858

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri with the hiccup in the previous effort, I feel I didn't gain much momentum in making sure things were working quite right. You game for another feature review. This time, I've left the final commit all as a single commit. No "copy and then modify". Copy and modification is done simultaneously.  Let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881#-:-MlGM5qO8cmIA445aRS6:b-tu88vj)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'm happy to check on the commit curation, but you should probably find someone else to move this along faster, I'm timing out for today.

Aside: a "core" is what you end up with when your program segfaults; this is "common" code.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll be content if you check the commit curation (and I'll change core --> common). 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881#-:-MlGq9UQ-bXahZvq-pqB:b-vnmnq2)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Curation seems fine.  (The only real thing to check is that `gitk` isn't spaghetti and that `git blame` on the cc files shows more than just Sean.  Both pass, when I pull this locally.)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

Wasn't sure how to interpret curation myself; I just reviewed the moves using:
```
git diff --ignore-space-change --color-moved $(git merge-base upstream/master HEAD) HEAD
```

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881#-:-MlHWl5U-trnjn3MV443:bsf7rfo)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
Needs release notes tag? (I assume `release notes: none`?)

**Comment by jwnimmer-tri** [comment]
FYI For these "I just moved code" PRs, I'd advocate for "single reviewer" always.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by sherm1 — COMMENTED** [review]
I find the commit curation mostly useless and difficult to review. I'm not at all convinced this kind of git trickery is worth what appears to be a large effort. I suspect a little lost history would be a small price to pay for faster progress.

The final result looks great, though -- thanks for doing this! Platform :lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881#-:-MlLcJ6H0nmw_9usCR3s:b1c9fwk)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15881#-MlLSz0J9XsRHllMEmvq:-MlLdTpU4raqUryWq17H:b-7nv3v0) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is magical voodoo that drags the *history* of the source file into the new file. For your reading:

https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904

The merge is the magic that allows you to simultaneously `git mv` and *not* `git mv`. That simultaneous quantum behavior is what allows the two files to share the same history.
</blockquote></details>

@ericcousineau-tri the PR is blocking on this. I'm removing you and merging this. But the information is still worth reading.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Dismissed @EricCousineau-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: commits are properly curated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15881#-:-MlLddDs3xvucbYTzgT8:b-qv2c28)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform), base commit is latest master (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
> Can you put a comment here on what you do to validate commit curation?

I did that upthread.  Here's the link: https://github.com/RobotLocomotion/drake/pull/15881#issuecomment-934695048

**Pull request merged**
