### PR TITLE
[systems/analysis] Deprecate InitialValueProblem OdeContext

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, InitialValueProblem and its wrappers
(ScalarInitialValueProblem, AntiderivativeFunction) all invented new
structures called __Context to accept their arguments.  But these
structures do not provide the Context API.  Furthermore, they are
trivially small wrappers which aren't needed and required a bunch of
error checking.

This has always bugged me, but I decided to fix it now before adding
python bindings for InitialValueProblem and friends -- I'd rather not
let the OdeContext, etc, sneak into the pydrake API if I planned to
deprecate it eventually.

Discussed previously in #12857.

+@ggould-tri for feature review, please?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739)

### CODE REVIEW

**Comment by RussTedrake** [comment]
___
*[systems/analysis/antiderivative_function.h, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MxjFrml2vnTbATxfim_:-MxjFrmm72Nfgq8QVi8U:b-c8t4o1) ([raw file](https://github.com/robotlocomotion/drake/blob/708ccddcf7be78e55f9aeb6506e482556838b45a/systems/analysis/antiderivative_function.h#L112)):*
> ```objc
> 
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> ```

btw -- clang was much more impressive than gcc in it's use of the the deprecated flag.  Making sure it compiled on gcc made me have to sprinkle these throughout, and deprecate the OdeContext constructors instead of the structure itself.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:
This looked awfully long before I realized the tests were copypasta :-/
A few minor issues.  I'm on vacation after today so feel free to resolve/dismiss me if this doesn't land today.

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-Mxo5VQQ0GzL6Se0ksyb:bvx26cp)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[systems/analysis/antiderivative_function.h, line 223 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo1tHkExc7PrWKBVOr:-Mxo1tHkExc7PrWKBVOs:b-jan8nl) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/antiderivative_function.h#L223)):*
> ```objc
>   ///          dense output would result if v = @p w.
>   /// @returns A dense approximation to F(u; 𝐤) (that is, a function), defined
>   ///          for v ≤ u ≤ w.
> ```

nit:  Here and the lines above, inconsistent use of 'v' vs '@p v'.  I'm not sure it matters much -- the difference in doxygen output is nearly invisible at my current glasses prescription -- but it's surprising.
___
*[systems/analysis/antiderivative_function.h, line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo3d2oEeQmonBgk6Jh:-Mxo3d2oEeQmonBgk6Ji:b-ed8gql) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/antiderivative_function.h#L227)):*
> ```objc
>   ///       interval will be. See documentation of the specific dense output
>   ///       technique in use for reference on performance impact as this
>   ///       interval grows.
> ```

minor: (because I'll be on vacation from tomorrow so you may want to be able to self-resolve this)

I tried following this "see documentation" advice and my path went from this method docs -> this class docs -> ScalarIntialValueProblem -> InitialValueProblem -> "See documentation of the internally held IntegratorBase subclass instance"

It would be shorter and clearer for subsequent readers to just tell them to look in the IntegratorBase directly rather than this documented-goose chase.
___
*[systems/analysis/test/antiderivative_function_test.cc, line 349 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo6tu2-jS_8YFTSfxK:-Mxo6tu2-jS_8YFTSfxL:b-65v5pp) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/antiderivative_function_test.cc#L349)):*
> ```cpp
> 
> INSTANTIATE_TEST_SUITE_P(IncreasingAccuracyAntiderivativeFunctionTests,
>                         AntiderivativeFunctionAccuracyTest,
> ```

nit:  This indent looks like it's off by once space.
___
*[systems/analysis/test/initial_value_problem_test.cc, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MxoAFLI0pe-a6abHNjj:-MxoAFLI0pe-a6abHNjk:bjy06z7) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef5eb637c193f3ba8033c34b5434fa4260a8a32/systems/analysis/test/initial_value_problem_test.cc#L146)):*
> ```cpp
>   // solve for that's in the past with respect to the IVP initial
>   // time.
>   const double kInvalidTime = kDefaultInitialTime - 10.0;
> ```

BTW:  I don't really understand why this validity checking on the deprecated interface is going away -- does setting the default integrator remove the validity check?  I'd generally expect deprecated interface tests to remain largely unchanged.

(likewise in the files below)
___
*[systems/analysis/test/initial_value_problem_test.cc, line 233 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo7FJG5Xrnbfy1WBNB:-Mxo7FJG5Xrnbfy1WBNC:b-p6iyw0) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/initial_value_problem_test.cc#L233)):*
> ```cpp
> 
> INSTANTIATE_TEST_SUITE_P(IncreasingAccuracyInitialValueProblemTests,
>                         InitialValueProblemAccuracyTest,
> ```

nit: indentation off by one?
___
*[systems/analysis/test/initial_value_problem_test.cc, line 275 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo7ST33Gfu2qsORDSg:-Mxo7ST33Gfu2qsORDSh:b-kqhcij) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/initial_value_problem_test.cc#L275)):*
> ```cpp
>   const double t1 = kDefaultInitialTime + 1.0;
>   EXPECT_TRUE(CompareMatrices(
>       ivp.Solve(t0, t1), k1 + (x0 - k1) * std::exp(-(t1 - t0)), kAccuracy));
> ```

minor:  Why are you taking care to call the new non-deprecated Solve from within the test of the deprecated form?  This seems odd to me.
___
*[systems/analysis/test/initial_value_problem_test.cc, line 610 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo8epmCjPEJ8bkLyfm:-Mxo8epmCjPEJ8bkLyfn:b-p6iyw0) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/initial_value_problem_test.cc#L610)):*
> ```cpp
> 
> INSTANTIATE_TEST_SUITE_P(DeprecatedInitialValueProblemAccuracyTest,
>                         DeprecatedInitialValueProblemAccuracyTest,
> ```

nit: indentation off by one?
___
*[systems/analysis/test/scalar_initial_value_problem_test.cc, line 264 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo8xRb3HREaZLxdOH3:-Mxo8xRb3HREaZLxdOH4:b-kqhcij) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/scalar_initial_value_problem_test.cc#L264)):*
> ```cpp
> 
>   const double t1 = kDefaultInitialTime + 1.0;
>   EXPECT_NEAR(ivp.Solve(t0, t1), k1[0] + (x0 - k1[0]) * std::exp(-(t1 - t0)),
> ```

minor:  Why are you taking care to call the new non-deprecated Solve from within the test of the deprecated form?  This seems odd to me.

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-MxzqmiC0GkF9XZCgKqZ:b-ruv0ff)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

___
*[systems/analysis/test/initial_value_problem_test.cc, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MxoAFLI0pe-a6abHNjj:-MxzltCG912TpoHFw-V5:btvwgxp) ([raw file](https://github.com/robotlocomotion/drake/blob/0ef5eb637c193f3ba8033c34b5434fa4260a8a32/systems/analysis/test/initial_value_problem_test.cc#L146)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  I don't really understand why this validity checking on the deprecated interface is going away -- does setting the default integrator remove the validity check?  I'd generally expect deprecated interface tests to remain largely unchanged.

(likewise in the files below)
</blockquote></details>

Done.  This was from an intermediate version, and I should have changed it back.
___
*[systems/analysis/test/initial_value_problem_test.cc, line 275 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16739#-Mxo7ST33Gfu2qsORDSg:-MxzleQg6257wBILcN9g:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/e4b8ae74b1058e018ab6e896d609caa03e988081/systems/analysis/test/initial_value_problem_test.cc#L275)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Why are you taking care to call the new non-deprecated Solve from within the test of the deprecated form?  This seems odd to me.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
Jenkins is not happy yet.

**Review by RussTedrake — COMMENTED** [review]
hopefully now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-My0DEAu4t4gEbAu9mzO:b6df2un)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint on the library changes.  I'll come back and reviews the tests later on.

> Reviewed 3 of 10 files at r1, 2 of 3 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-My3MapXCKq8-BPhRqZ9:bxn54z1)* status: 10 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri and @RussTedrake)

___
*[systems/analysis/antiderivative_function.h, line 131 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3LA9t4P44LAXzLY-I:-My3LA9t4P44LAXzLY-J:b-4xshyb) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/antiderivative_function.h#L131)):*
> ```objc
>   }
> 
>   AntiderivativeFunction(const IntegrableFunction& integrable_function,
> ```

Non-deprecated constructor should have a docstring.
___
*[systems/analysis/antiderivative_function.h, line 220 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3M7O4B_E2dgTQ2RnA:-My3M7O4B_E2dgTQ2RnB:b-mq07yp) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/antiderivative_function.h#L220)):*
> ```objc
>   ///
>   /// @param v The lower integration bound.
>   /// @param w The uppermost integration bound. Usually, v < @p w as an empty
> ```

For the upper bound of the integral, the class overview and the unicode in this function's documentation both name it `u`, not `w`.
___
*[systems/analysis/initial_value_problem.h, line 83 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3Iypk6CQ0XAVDv4vt:-My3Iypl3P9jRU55j2_Y:b1kl1fe) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L83)):*
> ```objc
>   /// to become an initial value problem).  This places the same role as
>   /// systems::Context, but is intentionally much simpler.
>   struct DRAKE_DEPRECATED(
> ```

nit Missing `#include "drake/common/drake_deprecated.h"` atop this file.
___
*[systems/analysis/initial_value_problem.h, line 188 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3FfIj2otdjJD37Q7W:-My3FfIj2otdjJD37Q7X:ba7dvp9) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L188)):*
> ```objc
> 
>   /// Constructs an IVP described by the given @p ode_function, using given @p
>   /// t0 and @p x0 as initial conditions, and parameterized with @p k.
> ```

nit There is no such parameter "the given t0".
___
*[systems/analysis/initial_value_problem.h, line 204 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3G70M5pRZeD-acZpp:-My3G70M5pRZeD-acZpq:b1nirjg) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L204)):*
> ```objc
> 
>   /// Solves and yields an approximation of the IVP solution x(t; 𝐤) for the
>   /// closed time interval between the initial time @p t0 and the given final
> ```

nit consistency



_Suggestion:_
```objc
the given initial time
```
___
*[systems/analysis/initial_value_problem.cc, line 138 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3HtgB8zPqq4fS_SSo:-My3HtgB8zPqq4fS_SSp:b-wlsppm) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.cc#L138)):*
> ```cpp
> 
> template <typename T>
> InitialValueProblem<T>::InitialValueProblem(
> ```

This non-deprecated constructor definition should not be covered by an `ignored "-Wdeprecated-declarations"` stanza.  We want any new deprecations of other APIs to show up here.
___
*[systems/analysis/initial_value_problem.cc, line 141 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3HYBl7-J0xWpr-inY:-My3HYBl7-J0xWpr-inZ:bawkvsf) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.cc#L141)):*
> ```cpp
>     const OdeFunction& ode_function, const Eigen::Ref<const VectorX<T>>& x0,
>     const Eigen::Ref<const VectorX<T>>& k) {
>   // Instantiates the system using the given defaults as models.
> ```

nit Does the phrase "the given default" still make sense?  It used to be an object named `default_values_`, but that's no longer here.
___
*[systems/analysis/initial_value_problem.cc, line 145 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3HfUhCLZ1qkSsGxIR:-My3HfUhCLZ1qkSsGxIS:btjhkyq) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.cc#L145)):*
> ```cpp
> 
>   // Allocates a new default integration context with the
>   // given default initial time.
> ```

nit There is no "initial time" anywhere in this function.
___
*[systems/analysis/scalar_initial_value_problem.h, line 126 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3K4NO-L9PY0zJLvxR:-My3K4NPEnrWRfItsihX:b7oyo8e) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/scalar_initial_value_problem.h#L126)):*
> ```objc
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>   /// Constructs a scalar IVP described by the given @p scalar_ode_function,
>   /// using given @p t0 and @p x0 as initial conditions, and parameterized with
> ```

nit There is no such parameter "given t0".
___
*[systems/analysis/scalar_initial_value_problem.h, line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3Jqel5C2cVZ2sgqzC:-My3Jqel5C2cVZ2sgqzD:b7m0ncr) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/scalar_initial_value_problem.h#L133)):*
> ```objc
>   /// @param x0 The initial state 𝐱₀ ∈ ℝ.
>   /// @param k The parameter vector 𝐤 ∈ ℝᵐ.  By default m=0 (no parameters).
>   ScalarInitialValueProblem(
> ```

This non-deprecated constructor declaration should not be covered by an `ignored "-Wdeprecated-declarations"` stanza.  We want any new deprecations of other APIs to show up here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My56UIl78y1dqJzNZR9:-My56UIl78y1dqJzNZRA:bbdenfu) (no related file):*
The mechanism used here to twin the unit tests for deprecated vs non-deprecated API is too time-consuming to code review and will destroy the git history of the test code when the deprecation removals happen.

Please do the following instead for each of the three unit tests:

Create `foo_deprecated_test.cc` as an exact copy of the original test from master.  It will be trivial for a reviewer to pull the PR locally and confirm that the file is an exact copy of master.  Duplicate the test case BUILD rule for the new name, and add `copts = ["-Wno-deprecated-declarations"]` to suppress warnings.

Keep `foo_test.cc` as the revised test cases for the non-deprecated code, which should be basically removing the code within the current pragma's push / pop.  Clean up any unintentional diffs vs master -- there will be a smattering of changes throughout but they should all be directly due to the API update, not unrelated churn.

---
___
*[systems/analysis/initial_value_problem.cc, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My58iAr6gNvLa2UN3SE:-My58iAr6gNvLa2UN3SF:buqnfjr) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.cc#L294)):*
> ```cpp
> template <typename T>
> VectorX<T> InitialValueProblem<T>::Solve(const T& t0, const T& tf) const {
>   DRAKE_DEMAND(tf >= t0);
> ```

nit The original (deprecated) implementation was kind to the user and raised an exception if the two times were out-of-order.  Here, we just coredump the program when they feed us bad input.  Consider at least a `DRAKE_THROW_UNLESS` here to be more gentle with our users.

Ditto in `DenseSolve` below.
___
*[systems/analysis/test/antiderivative_function_test.cc, line 97 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My54wLk8YV5cW6GBVtl:-My54wLk8YV5cW6GBVtm:b-boxkoh) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/test/antiderivative_function_test.cc#L97)):*
> ```cpp
>     IntegratorBase<double>& inner_integrator =
>         antiderivative_function.get_mutable_integrator();
>     inner_integrator.set_target_accuracy(integration_accuracy_);
> ```

nit In the master version of this test case, the antiderivative_function appears outside of the loop.  Since it does not depend on `a` at all, I'm not sure why it's moved inside of the loop here?  In general, defining constants outside of the loop improves readability.

Ditto (x4) for all of the test cases below.

**Comment by RussTedrake** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My56UIl78y1dqJzNZR9:-My5GSaz0IBgPmc5XDnI:b-qc114g) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The mechanism used here to twin the unit tests for deprecated vs non-deprecated API is too time-consuming to code review and will destroy the git history of the test code when the deprecation removals happen.

Please do the following instead for each of the three unit tests:

Create `foo_deprecated_test.cc` as an exact copy of the original test from master.  It will be trivial for a reviewer to pull the PR locally and confirm that the file is an exact copy of master.  Duplicate the test case BUILD rule for the new name, and add `copts = ["-Wno-deprecated-declarations"]` to suppress warnings.

Keep `foo_test.cc` as the revised test cases for the non-deprecated code, which should be basically removing the code within the current pragma's push / pop.  Clean up any unintentional diffs vs master -- there will be a smattering of changes throughout but they should all be directly due to the API update, not unrelated churn.
</blockquote></details>

That's a reasonable suggestion.  But to be clear, the approach I've taken here is the approach we've always recommended for deprecations in the past, no?  Was there something in particular about this PR changed that recommendation?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @ggould-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My56UIl78y1dqJzNZR9:-My5H0Kc6H5efRy7Tmoc:b-7z8jll) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

That's a reasonable suggestion.  But to be clear, the approach I've taken here is the approach we've always recommended for deprecations in the past, no?  Was there something in particular about this PR changed that recommendation?
</blockquote></details>

When we just deprecate or rename one function, copying one test case within the same file is pretty easy and works fine.  When the copying is so substantial, however, the technique doesn't scale.  We have used the two-file approach in the past in similar cases.

I am OK with any solution that's amenable to code review.  The one I outlined above seemed like the easiest path.

---

**Review by jwnimmer-tri — COMMENTED** [review]
I pushed the test file change.  We'll plan to squash when merging.

> Reviewed 4 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-My8YdPk7VJ0DH82zf4z:b-6ochfj)* status: 12 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My56UIl78y1dqJzNZR9:-My8YhlI1hsBbHEQfhL3:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When we just deprecate or rename one function, copying one test case within the same file is pretty easy and works fine.  When the copying is so substantial, however, the technique doesn't scale.  We have used the two-file approach in the past in similar cases.

I am OK with any solution that's amenable to code review.  The one I outlined above seemed like the easiest path.
</blockquote></details>

Done.

---

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My56UIl78y1dqJzNZR9:-MyA8GymDWwbJuLI3g-F:b-r3y163) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome. Thanks.

---
___
*[systems/analysis/antiderivative_function.h, line 131 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3LA9t4P44LAXzLY-I:-MyA92y253QzOZOxcPv0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/antiderivative_function.h#L131)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Non-deprecated constructor should have a docstring.
</blockquote></details>

Done.
___
*[systems/analysis/antiderivative_function.h, line 220 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3M7O4B_E2dgTQ2RnA:-MyA9WDc6dYFiajpEe5o:b-z9ua7n) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/antiderivative_function.h#L220)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For the upper bound of the integral, the class overview and the unicode in this function's documentation both name it `u`, not `w`.
</blockquote></details>

I believe the way I have it is correct (it is copied from the deprecated version).  The original author's intent was using the notation that many integrals are computed (all over the interval v to u), with w being the largest value of u obtained.
___
*[systems/analysis/initial_value_problem.h, line 83 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3Iypk6CQ0XAVDv4vt:-MyAADyt6AZBlj9lucxK:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing `#include "drake/common/drake_deprecated.h"` atop this file.
</blockquote></details>

Done. 
___
*[systems/analysis/initial_value_problem.h, line 188 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3FfIj2otdjJD37Q7W:-MyAATVL9UCj3bLIEh30:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit There is no such parameter "the given t0".
</blockquote></details>

Done.
___
*[systems/analysis/initial_value_problem.h, line 204 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3G70M5pRZeD-acZpp:-MyAAYjVBwjH7G6zeb9T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.h#L204)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit consistency
</blockquote></details>

Done.
___
*[systems/analysis/initial_value_problem.cc, line 138 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3HtgB8zPqq4fS_SSo:-MyAAp3L0n0PpGUwu0H6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/initial_value_problem.cc#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This non-deprecated constructor definition should not be covered by an `ignored "-Wdeprecated-declarations"` stanza.  We want any new deprecations of other APIs to show up here.
</blockquote></details>

Done.
___
*[systems/analysis/scalar_initial_value_problem.h, line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3Jqel5C2cVZ2sgqzC:-MyABUW54aExau5H4dqF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/scalar_initial_value_problem.h#L133)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This non-deprecated constructor declaration should not be covered by an `ignored "-Wdeprecated-declarations"` stanza.  We want any new deprecations of other APIs to show up here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 3 of 7 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16739#-:-MyAGjZ30cujtkIbiIHV:b-vtj4vo)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[systems/analysis/antiderivative_function.h, line 220 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16739#-My3M7O4B_E2dgTQ2RnA:-MyAFIt24-z4gimi5hBp:b-xpsecw) ([raw file](https://github.com/robotlocomotion/drake/blob/82d46eec8e6427a6dc442128e80e3e4f3f5ce35e/systems/analysis/antiderivative_function.h#L220)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I believe the way I have it is correct (it is copied from the deprecated version).  The original author's intent was using the notation that many integrals are computed (all over the interval v to u), with w being the largest value of u obtained.
</blockquote></details>

OK got it.
___
*[systems/analysis/test/initial_value_problem_test.cc, line 108 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MyAGQ-294A91ku22ehg:-MyAGQ-294A91ku22ehh:bemzgpl) ([raw file](https://github.com/robotlocomotion/drake/blob/bf24192a293e6d1e91a4e9b143c8a3d1514de065/systems/analysis/test/initial_value_problem_test.cc#L108)):*
> ```cpp
>     for (double m = kLowestParticleMass; m <= kHighestParticleMass;
>          m += kParticleMassStep) {
>       const Eigen::Vector2d kParameters{mu, m};
> ```

nit GSG cannot use `kParameters` constant naming for a varying value.
___
*[systems/analysis/test/initial_value_problem_test.cc, line 184 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MyAGaJ7AXF6eJP2rBAq:-MyAGaJ7AXF6eJP2rBAr:bemzgpl) ([raw file](https://github.com/robotlocomotion/drake/blob/bf24192a293e6d1e91a4e9b143c8a3d1514de065/systems/analysis/test/initial_value_problem_test.cc#L184)):*
> ```cpp
>     for (double m = kLowestParticleMass; m <= kHighestParticleMass;
>          m += kParticleMassStep) {
>       const Eigen::Vector2d kParameters{mu, m};
> ```

nit GSG cannot use `kParameters` constant naming for a varying value.
___
*[systems/analysis/test/scalar_initial_value_problem_test.cc, line 114 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16739#-MyAGgFWEfAnAismOeAF:-MyAGgFWEfAnAismOeAG:bemzgpl) ([raw file](https://github.com/robotlocomotion/drake/blob/bf24192a293e6d1e91a4e9b143c8a3d1514de065/systems/analysis/test/scalar_initial_value_problem_test.cc#L114)):*
> ```cpp
>     for (double Cs = kLowestCapacitance; Cs <= kHighestCapacitance ;
>          Cs += kCapacitanceStep) {
>       const Eigen::Vector2d kParameters{Rs, Cs};
> ```

nit GSG cannot use `kParameters` constant naming for a varying value.

**Pull request merged**
