### PR TITLE
final matlab purge.  we build back up from here.

### PR DESCRIPTION
**Pull request by RussTedrake**
as proposed in #6716

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6725)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jamiesnape for feature review

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqQMpj1sJqmPS0_3H8o:b9itq1i)*

**Comment by jamiesnape** [comment]
Should we consider moving the remaining MATLAB to `drake/bindings/matlab`?

:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/addpath_drake.m, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-KqSw2qJHMvVc2riOcW9:-KqSw2qJHMvVc2riOcWA:b-sllmkq) ([raw file](https://github.com/robotlocomotion/drake/blob/e160a534575c52bc571f556c2a3a36f19d50f8da/drake/matlab/addpath_drake.m#L25)):*
> ```objc
>       display('Please see bug report and solution here: https://github.com/RobotLocomotion/drake/issues/558.')
>       display('(It just involves adding one line to your java.opts file for Matlab.)')
>       display('Make sure to restart Matlab after editing your java.opts file.')
> ```

FYI I think we should create a section in the docs and just say here in one line: `WARNING: Your JVM may crash if you do not set it to prefer IPv4 over IPv6, see <link to section in docs>.` The docs should include a link to https://www.mathworks.com/help/matlab/matlab_env/java-opts-file.html. On that note, I think most of `matlab_faq.rst` can be removed. We do not use the MEX compiler wrapper, the versions of Xcode referenced are very old, and we already support newer Java.

---

*[drake/matlab/CMakeLists.txt, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-KqSxlucOTJ_YY7QY0kz:-KqSxlucOTJ_YY7QY0l-:beuwm7u) ([raw file](https://github.com/robotlocomotion/drake/blob/45813ce24408b32484d8ced2bec77f1eafa27672/drake/matlab/CMakeLists.txt#L28)):*
> ```CMake
> endif()
> 
> add_subdirectory(solvers/test)
> ```

FYI This line should have been wrapped in `if(BUILD_TESTING) ... endif()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqSxhHGd6n-TFYpVX2v:bkjtdbr)*

**Comment by jamiesnape** [comment]
Also, do we want to remove 

* https://github.com/RobotLocomotion/drake/blob/master/addpath_pods.m
* https://github.com/RobotLocomotion/drake/blob/master/drake/runAllTests.m

?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqT24shIfjj-YAV0fD3:bk3rnu3)*

**Comment by jamiesnape** [comment]
And https://github.com/RobotLocomotion/drake/blob/master/drake/Contents.m ?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqT2dILjOfsqZabot1K:b-29q6fh)*

**Comment by RussTedrake** [comment]
happy to consider moving `matlab` to `bindings/matlab`, but will wait for this to gel with the other open matlab purge PR.  zapped the three other files that you found.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqbuaHkfyiRv5_jPWsg:b-5hqdma)*

**Comment by RussTedrake** [comment]
Review status: 12 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/addpath_drake.m, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-KqSw2qJHMvVc2riOcW9:-KqbvCbvlLl8avVpofpp:b-ckgfm1) ([raw file](https://github.com/robotlocomotion/drake/blob/e160a534575c52bc571f556c2a3a36f19d50f8da/drake/matlab/addpath_drake.m#L25)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI I think we should create a section in the docs and just say here in one line: `WARNING: Your JVM may crash if you do not set it to prefer IPv4 over IPv6, see <link to section in docs>.` The docs should include a link to https://www.mathworks.com/help/matlab/matlab_env/java-opts-file.html. On that note, I think most of `matlab_faq.rst` can be removed. We do not use the MEX compiler wrapper, the versions of Xcode referenced are very old, and we already support newer Java.
</blockquote></details>

agreed.  can you file an issue?

---

*[drake/matlab/CMakeLists.txt, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-KqSxlucOTJ_YY7QY0kz:-KqbvauFj1pzSDcX-pTe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/45813ce24408b32484d8ced2bec77f1eafa27672/drake/matlab/CMakeLists.txt#L28)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI This line should have been wrapped in `if(BUILD_TESTING) ... endif()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/addpath_drake.m, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-KqSw2qJHMvVc2riOcW9:-KqcCX0-nsvGXCUxj4mw:b1n4s22) ([raw file](https://github.com/robotlocomotion/drake/blob/e160a534575c52bc571f556c2a3a36f19d50f8da/drake/matlab/addpath_drake.m#L25)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

agreed.  can you file an issue?
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/6761

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqcCb6rnaNBkMu0bFsR:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

FYI, the `testMathematicalProgram` is not working on Mac because of the same reason that I reported in https://github.com/RobotLocomotion/drake/issues/6686.

---

Reviewed 10 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725#-:-KqcXDCCISkrfmGwIOrJ:b2jhkgn)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6725)*

**Pull request merged**
