### PR TITLE
Fix a memory leak in rigid_body_tree_test.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #3662.  +@amcastro-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3664)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform :lgtm:.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-KTBqCsO6ltLofOGQKGl:-KTBqCsPXfBsff6HedqV:b-oi5osd) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc61abd53db8c230948c252d418934a1b8ecc6a/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L67)):*
> ```cpp
>   // RigidBodyTree takes ownership of these bodies.
>   // User still has access to these bodies through the raw pointers.
>   RigidBody* r1b1 = tree->add_rigid_body(std::move(r1b1_));
> ```

FYI Accidentally-awesome that the member fields were spelled wrong before, so that this refactor  touches fewer lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-:-KTBpryh_UrfvMDXI_me:b3qelfj)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-:-KTBv1OhPSgE0C0YB7I5:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.h, line 921 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-KTBvDikR9X_H_jvLODU:-KTBvDikR9X_H_jvLODV:b-ktteeq) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc61abd53db8c230948c252d418934a1b8ecc6a/drake/systems/plants/RigidBodyTree.h#L921)):*
> ```objc
>    *
>    * @param[in] body The rigid body to add to this rigid body tree.
>    * @return A bare, unowned pointer to the @p body.
> ```

BTW: nit: Remove "the" since `body` is a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664)*

**Comment by amcastro-tri** [comment]
Excellent!, I definitely like the `RigidBody*` return better. However, was there here a memory leak valgrind complained about? I still don't see it even when in my face, sorry. Or was it just that valgrid complains there is a `new` with no `delete`? In any case, this :lgtm: 

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.h, line 921 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-KTBvDikR9X_H_jvLODU:-KTEym26QZ7-w079N2Pc:bgjaa1p) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc61abd53db8c230948c252d418934a1b8ecc6a/drake/systems/plants/RigidBodyTree.h#L921)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: Remove "the" since `body` is a parameter.
</details>
BTW, nice! Why didn't we do this before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-:-KTEzNsM1p2bdaXN6GpN:bzdl6lk)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.h, line 921 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-KTBvDikR9X_H_jvLODU:-KTF-gfSpgklzzjOCE_V:b49l2hj) ([raw file](https://github.com/robotlocomotion/drake/blob/ebc61abd53db8c230948c252d418934a1b8ecc6a/drake/systems/plants/RigidBodyTree.h#L921)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, nice! Why didn't we do this before?
</details>
Changing customs informed by the wisdom gained through experience? :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664)*

**Comment by jwnimmer-tri** [comment]
> However, was there here a memory leak valgrind complained about? I still don't see it even when in my face, sorry.

For one thing: test cases that only added some of the four bodies to the tree leaked the remainder of the bodies.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-:-KTF3QxEKm5dfbj2SiyT:bb8n23)*

**Comment by amcastro-tri** [comment]
Good observation, thank you!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664#-:-KTF9UwsaqtuGHTG9r9A:b-use85i)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3664)*

**Pull request merged**
