### PR TITLE
[symbolic] Add BoxedCell helper class

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is in preparation for refactoring Expression to use nanboxing (#17544).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri and +@ggould-tri for reviews please, because you've already seen most of this in #17544.  If you'd like to push the unit test reviews off other review(s), that's fine too.
 
I'm happy for you to post review comments either here or in the other PR, I think either way works well for me.

**Review by ggould-tri — COMMENTED** [review]
Thanks for breaking this out; it is at least a cleaner history and attribution.

:lgtm_strong:  

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612#-:-N7Vh79G7t6BKyCUv-ej:b-lg5bx5)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`common/symbolic/expression/boxed_cell.h` line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7VhhuV8fmFpTD2H2k-:-N7VhhuV8fmFpTD2H2k0:b34tt2h) ([raw file](https://github.com/robotlocomotion/drake/blob/20b8573dd28eaf07691976b545a58e22d5512152/common/symbolic/expression/boxed_cell.h#L118)):*
> ```objc
>  https://www.amd.com/system/files/TechDocs/24593.pdf
> for details. The same is true of the nominal AArch64 virtual addresses used on
> macOS (running `sysctl machdep.virtual_address_size` reports 47 on Apple M1),
> ```

BTW Good catch!



_Code quote:_
```objc
sysctl machdep.virtual_address_size
```
___
*[`common/symbolic/expression/boxed_cell.h` line 306 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7Vkc0p6FEGD8MaLWix:-N7Vkc0p6FEGD8MaLWiy:bz47xn3) ([raw file](https://github.com/robotlocomotion/drake/blob/20b8573dd28eaf07691976b545a58e22d5512152/common/symbolic/expression/boxed_cell.h#L306)):*
> ```objc
>   }
> 
>   /** Returns a const reference to the owned cell.
> ```

nit:  This declaration comment is the only one that's doxygen formatted.
___
*[`common/symbolic/expression/test/boxed_cell_test.cc` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7VlnN22OIFaN3PkyXU:-N7VlnN22OIFaN3PkyXV:bk802qs) ([raw file](https://github.com/robotlocomotion/drake/blob/20b8573dd28eaf07691976b545a58e22d5512152/common/symbolic/expression/test/boxed_cell_test.cc#L107)):*
> ```cpp
> TEST_F(BoxedCellTest, SetGetCell) {
>   BoxedCell dut;
>   dut.SetSharedCell(MakeVarCell());
> ```

BTW:  I am surprised that valgrind doesn't flag this as a leak, since the cell shouldn't be legible to valgrind as a pointer.

I would expect that at some point in all of this you're going to need to add a valgrind exclusion, but I guess it's not here :man_shrugging:

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[`common/symbolic/expression/test/boxed_cell_test.cc` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7VlnN22OIFaN3PkyXU:-N7WAv3F9n6-FzPaWxuG:bwyr883) ([raw file](https://github.com/robotlocomotion/drake/blob/20b8573dd28eaf07691976b545a58e22d5512152/common/symbolic/expression/test/boxed_cell_test.cc#L107)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  I am surprised that valgrind doesn't flag this as a leak, since the cell shouldn't be legible to valgrind as a pointer.

I would expect that at some point in all of this you're going to need to add a valgrind exclusion, but I guess it's not here :man_shrugging: 
</blockquote></details>

At the conclusion of any of these test cases, all of the BoxedCell instances go out of scope, which means that all of their cells go down to use_count == 0 and are free'd.  I don't think anything is "still reachable".

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[`common/symbolic/expression/test/boxed_cell_test.cc` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7VlnN22OIFaN3PkyXU:-N7X3hLC2ViJAswWW8P5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b8573dd28eaf07691976b545a58e22d5512152/common/symbolic/expression/test/boxed_cell_test.cc#L107)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I was a tripped up by this as well. Consider making a note here (or in front of the Release test).
</blockquote></details>

Done.
___
*[`common/symbolic/expression/test/boxed_cell_test.cc` line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17612#-N7WwQIK5aKZIniJph5R:-N7X2fOEB61XGgAX8B4-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/29c414809f72299f8631fc0148f0b56f3e783295/common/symbolic/expression/test/boxed_cell_test.cc#L114)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit consider adding a test for `trivially_equals` against a different nonconstant cell, (e.g. sqrt cell).
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
I've run the new unit test in Debug mode locally on both Mac x86 and Mac M1, and it passed.  I think that's good enough to merge without extra CI here.  If any post-merge CI testing fails, we can `tags = manual` on the new unit test for now.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17612)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
