### PR TITLE
[workspace] Build msgpack privately from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

This avoid ODR problems when users link their own msgpack library.

Improve vendor_cxx to be able to re-vendor msgpack's already-vendored copy of Boost.Preprocessor:
- Allow for empty preprocessor directives.
- Allow for arcane whitespace indentation.

Deprecate the public (from the host OS) msgpack repository rule.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18559)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please

I cannot reproduce the failure locally.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18559)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18559#-:-NLNpKG45Wo0H-fcoT6w:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.  It's OK to wait until Wednesday.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18559#-:-NLSw2cu7m1tPl_VtXWC:bzus18)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/workspace/default.bzl` line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18559#-NLSulq2DIOBHsEcZiO9:-NLSulq2DIOBHsEcZiOA:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/d0282c51245e8e0fa3f4086f8efbc6c55bb36e4b/tools/workspace/default.bzl#L232)):*
> ```Starlark
>     if "msgpack" not in excludes:
>         # N.B. This repository is deprecated for removal on 2023-05-01.
>         # For details see https://github.com/RobotLocomotion/drake/pull/XXXXX.
> ```

nit



_Suggestion:_
```Starlark
18559
```

**Pull request merged**
