### PR TITLE
[fem] Move LinearConstitutiveModelData out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for feature review please, thank you.

The new out-of-dev files (`linear_constitutive_model(.h/.cc/_test.cc)`) require a full review. 
There's no rush for this PR, but feel free to let me know if this is too much burden and I can reassign.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgHTfiiESHVugv74cEq:b-wl88eq)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: documentation stuff

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgN2KR37kcKjmgA23st:bd2ftj3)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model_data.h, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgMyOrg52MPzPQa8HYw:-MgMyOrh5uXZqfEKS286:brpk7ua) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L13)):*
> ```objc
> namespace internal {
> 
> /* Data supporting calculations in LinearConstitutiveModel.
> ```

Having read the rest of the class definition, it seems to me that this class comment should be fairly explicit about the math objects captured here, and could still refer to the client modules for how it will be used.
___
*[multibody/fem/linear_constitutive_model_data.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgMzzQb3FFAvKFKLm21:-MgMzzQb3FFAvKFKLm22:b2wezqg) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L36)):*
> ```objc
> 
>   /* Returns the traces of the infinitesimal strains evaluated at the
>    quadrature locations for the associated element. */
> ```

On about the third reading of this comment I realized that we're using trace(X) in the linear algebra sense here. Maybe make that more clear?
___
*[multibody/fem/linear_constitutive_model_data.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN-Ip904xTeuh9FffY:-MgN-Ip904xTeuh9FffZ:b5oi2ir) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L51)):*
> ```objc
>   void UpdateFromDeformationGradient();
> 
>   /* Infinitesimal strain = 0.5 * (F + Fᵀ) - I. */
> ```

Maybe hoist this comment into the class-public API documentation comments?
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgN18jq7DXXqtw8SvT4:bjex1f4) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
> ```cpp
> namespace {
> 
> constexpr int kNumLocations = 1;
> ```

How hard would it be to increase this to 2 or 3? It would make the test feel more general.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the review! I addressed the comment. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgNBsNzCq0q45yHArau:b-382ve8)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[multibody/fem/linear_constitutive_model_data.h, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgMyOrg52MPzPQa8HYw:-MgNArhf3I9IajdpZL87:b-pii581) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Having read the rest of the class definition, it seems to me that this class comment should be fairly explicit about the math objects captured here, and could still refer to the client modules for how it will be used.
</blockquote></details>

I added some descriptions about what's the data being calculated/stored in the class. PTAL.
___
*[multibody/fem/linear_constitutive_model_data.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgMzzQb3FFAvKFKLm21:-MgN8HJX37nRvfRdRiQi:b-wxp4f7) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L36)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

On about the third reading of this comment I realized that we're using trace(X) in the linear algebra sense here. Maybe make that more clear?
</blockquote></details>

Ah that's a good point. I added some explanation here in addition to the class doc. PTAL.
___
*[multibody/fem/linear_constitutive_model_data.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN-Ip904xTeuh9FffY:-MgN8TqC0IrPUzlQrH--:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/linear_constitutive_model_data.h#L51)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe hoist this comment into the class-public API documentation comments?
</blockquote></details>

Done, thanks.
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgNBGVRC8k7PInsw3vi:bj7y7xo) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

How hard would it be to increase this to 2 or 3? It would make the test feel more general.
</blockquote></details>

Done, thanks.
Not hard, just need a new explicit instantiation.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model_data.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgNJa-J9-YSICt5bqBg:-MgNJa-J9-YSICt5bqBh:b-ty6w8m) ([raw file](https://github.com/robotlocomotion/drake/blob/5a3727a1fa3bdafb01a756a863d9686e660bee58/multibody/fem/linear_constitutive_model_data.cc#L28)):*
> ```cpp
> template class LinearConstitutiveModelData<double, 1>;
> template class LinearConstitutiveModelData<AutoDiffXd, 1>;
> template class LinearConstitutiveModelData<double, 2>;
> ```

Hm, maybe this is overdoing it -- see comments below.
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgNIfQr9sD6uXufjuzY:b-1fxszt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done, thanks.
Not hard, just need a new explicit instantiation.
</blockquote></details>

Ah, I missed the whole explicit instantiation thing on first read. If you don't actually have a use for more locations, maybe just add some commentary indicating that the current supported instantiations are are for 1 location only, but more could be added?

Elsewhere in Drake, I believe it is customary for the header file class comment to explain what cc file instantiations are supported, and under what circumstances others might be added.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgNK4Th13UijDCVjG8D:b-rbiub4) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ah, I missed the whole explicit instantiation thing on first read. If you don't actually have a use for more locations, maybe just add some commentary indicating that the current supported instantiations are are for 1 location only, but more could be added?

Elsewhere in Drake, I believe it is customary for the header file class comment to explain what cc file instantiations are supported, and under what circumstances others might be added.
</blockquote></details>

Working. Could you point me to such an example you have in mind? Something like [this](https://github.com/RobotLocomotion/drake/blob/dbb6f4edfefee96e20358a12055dd478820e5fe9/common/schema/stochastic.h#L365) perhaps? I want to make sure the language is somewhat consistent.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgNO0HF2Z18dxOD0-Mx:bqvgarr) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working. Could you point me to such an example you have in mind? Something like [this](https://github.com/RobotLocomotion/drake/blob/dbb6f4edfefee96e20358a12055dd478820e5fe9/common/schema/stochastic.h#L365) perhaps? I want to make sure the language is somewhat consistent.
</blockquote></details>

Probably closer to what I was remembering is drake::symbolic::GenericPolynomial. See its class comment [here](https://github.com/RobotLocomotion/drake/blob/master/common/symbolic_generic_polynomial.h#L29-L32).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[multibody/fem/linear_constitutive_model_data.cc, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgNJa-J9-YSICt5bqBg:-MgNQaQREBT1gtapMAvq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5a3727a1fa3bdafb01a756a863d9686e660bee58/multibody/fem/linear_constitutive_model_data.cc#L28)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, maybe this is overdoing it -- see comments below.
</blockquote></details>

Done.
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgN18jq7DXXqtw8SvT3:-MgNQbHF6ySpfZzYwN4m:b-smd5xt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b812adfcbbc10f8b4e87631f204bbb62beb3661/multibody/fem/test/linear_constitutive_model_data_test.cc#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Probably closer to what I was remembering is drake::symbolic::GenericPolynomial. See its class comment [here](https://github.com/RobotLocomotion/drake/blob/master/common/symbolic_generic_polynomial.h#L29-L32).
</blockquote></details>

Thanks for the reference! I mimicked the language.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review per rotation please, thank you.

Feel free to reassign if this is too late in the day.
Since this PR moves code out of `dev`, please review the entire files that are out of `dev`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgNRJuY9ndahYMRpvSR:b-ngstei)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Sorry, yes I'm well above 2000 lines reviewed today and timing out, so I'll going to defer here.  I've posted to slack for any weekend volunteer, otherwise you can tag the on-call on Monday.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for doing that. No rush on this PR. I see Sean is on call Monday. I'll tag him if no one volunteers.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgNTa0xCU8usZncWTrw:b-jgs5zc)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri for platform

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgQU-405KYB0lNIDKIP:b-drqrgr)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Mostly fine with some clean up requests.

> Reviewed 4 of 7 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MgQt-Tf1NtpupR_kU_G:byvfbs9)* status: 10 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/BUILD.bazel, line 64 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQssDNDEmNaRmVm9xN:-MgQssDNDEmNaRmVm9xO:b-63guy2) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/BUILD.bazel#L64)):*
> ```Starlark
>     deps = [
>         ":deformation_gradient_data",
>         "//common:default_scalars",
> ```

nit: As with the notes on the headers, change this to `"//common:autodiff"`.

Right now you're not using this and you're dragging in dependencies on `symbolic`.
___
*[multibody/fem/linear_constitutive_model_data.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQr3wP1shB2m6okRoq:-MgQr3wP1shB2m6okRor:bfhhswp) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.cc#L3)):*
> ```cpp
> #include "drake/multibody/fem/linear_constitutive_model_data.h"
> 
> #include "drake/common/default_scalars.h"
> ```

nit: This is misleading. You're not actually using the functionality in *this* header. You're really only benefitting from the indirect inclusion of:

`#include "drake/common/autodiff.h"`

Better to just include what you actually need (which has the nice byproduct of *not* dragging in all of symbolic.)
___
*[multibody/fem/linear_constitutive_model_data.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQrKoF-KQYTWrp1YVg:-MgQrKoF-KQYTWrp1YVh:bajoyec) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.cc#L12)):*
> ```cpp
> template <typename T, int num_locations>
> LinearConstitutiveModelData<T, num_locations>::LinearConstitutiveModelData() {
>   strain_.fill(Matrix3<T>::Zero());
> ```

nit: Worth putting a note that this is consistent as long as the deformation gradients are initialized to the identity matrix. Alternatively, you could simply invoke `UpdateFromDeformationGradient()` as we did in the test case.

The comment would suffice if you want to simply avoid the additional construction cost (and I'd mention that in the comment as well).

What's nice is that you've got a unit test to support this. :)
___
*[multibody/fem/linear_constitutive_model_data.h, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQp59cBIG_gjYpissB:-MgQp59d-qufpf0ciuUb:b29fpf4) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L5)):*
> ```objc
> #include <array>
> 
> #include "drake/common/eigen_types.h"
> ```

nit: unused
___
*[multibody/fem/linear_constitutive_model_data.h, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQpHNLAU1YTlE5A8Te:-MgQpHNLAU1YTlE5A8Tf:bmt2wv3) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L20)):*
> ```objc
>  See LinearConstitutiveModel for how the data is used. See
>  DeformationGradientData for more about constitutive model data.
>  @tparam_nonsymbolic_scalar T.
> ```

nit: Use of `@tparam_nonsymbolic_scalar` precludes use of `T`.
___
*[multibody/fem/linear_constitutive_model_data.h, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq1_c9bEegJyydift:-MgQq1_c9bEegJyydifu:b-jgjys2) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L35)):*
> ```objc
>   LinearConstitutiveModelData();
> 
>   /* Returns the infinitesimal strains (E = 0.5 * (F + Fᵀ) - I, see class
> ```

nit: Does the class documentation provide *any* additional insight into this quantity? I think not.
___
*[multibody/fem/linear_constitutive_model_data.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq8mx-dToPparjG80:-MgQq8mx-dToPparjG81:bjrlcja) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L36)):*
> ```objc
> 
>   /* Returns the infinitesimal strains (E = 0.5 * (F + Fᵀ) - I, see class
>    documentation) evaluated with the latest deformation gradient F. */
> ```

BTW: "...the latest deformation gradient F." 

You might choose to rephrase this in terms of APIs. What defines "the latest gradient"? It is, in fact, the gradient passed when `UpdateData()` was last invoked. Generally, it's a good idea to mention the mechanism (if it's not obvious) so that users know what cause to look for if their effect is not what they expect.

(Same applies below.)
___
*[multibody/fem/linear_constitutive_model_data.h, line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQqW3P0NQKLVVi3FYU:-MgQqW3P0NQKLVVi3FYV:b339zr1) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L48)):*
> ```objc
> 
>  private:
>   using Base =
> ```

BTW From a previous conversation, it's not clear that this alias particularly provides value in *this* instantiation either. We'd left this spelling in the base class's test to serve as a good example. Does it actually provide value anywhere or was the value documented in the test purely speculative?
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQsBHF44vahsBsww9_:-MgQsBHF44vahsBsww9a:b-f1t3nz) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/test/linear_constitutive_model_data_test.cc#L22)):*
> ```cpp
> }
> 
> GTEST_TEST(LinearConstitutiveModelDataTest, Initialization) {
> ```

nit: Can we get a comment here confirming that it is initialized with all of the values *consistent* (as documented in the constructor implementation)?
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQsIWt0TBRvbLEizUL:-MgQsIWt0TBRvbLEizUM:b-cm3ovp) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/test/linear_constitutive_model_data_test.cc#L35)):*
> ```cpp
>   LinearConstitutiveModelData<double, kNumLocations> linear_elasticity_data;
> 
>   const Matrix3<double> F = 3.0 * Matrix3<double>::Identity();
> ```

nit: As mentioned in previous PRs, let's move away from a diagonal matrix so we can confirm we're doing the full calculation (and not just on the diagonal). And an F that isn't symmetric would likewise be a good thing.

**Review by xuchenhan-tri — COMMENTED** [review]
@seancurtis-tri thanks for the review! Comments addressed. PTAL, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-Mgfr5XT2Hyi3ybjNLmW:b94yotn)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[multibody/fem/BUILD.bazel, line 64 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQssDNDEmNaRmVm9xN:-Mgfla460xaSE4H379gc:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/BUILD.bazel#L64)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As with the notes on the headers, change this to `"//common:autodiff"`.

Right now you're not using this and you're dragging in dependencies on `symbolic`.
</blockquote></details>

Done, thanks.
___
*[multibody/fem/linear_constitutive_model_data.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQr3wP1shB2m6okRoq:-MgfnlbZAyBHz8yrbD6z:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.cc#L3)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This is misleading. You're not actually using the functionality in *this* header. You're really only benefitting from the indirect inclusion of:

`#include "drake/common/autodiff.h"`

Better to just include what you actually need (which has the nice byproduct of *not* dragging in all of symbolic.)
</blockquote></details>

Done, thanks!
___
*[multibody/fem/linear_constitutive_model_data.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQrKoF-KQYTWrp1YVg:-Mgfpcib2L3cBNqNC-w3:ba4di7z) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.cc#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Worth putting a note that this is consistent as long as the deformation gradients are initialized to the identity matrix. Alternatively, you could simply invoke `UpdateFromDeformationGradient()` as we did in the test case.

The comment would suffice if you want to simply avoid the additional construction cost (and I'd mention that in the comment as well).

What's nice is that you've got a unit test to support this. :)
</blockquote></details>

Done thanks!
___
*[multibody/fem/linear_constitutive_model_data.h, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq1_c9bEegJyydift:-Mgfln9U4stpG1SbqpRp:bj16ue7) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Does the class documentation provide *any* additional insight into this quantity? I think not.
</blockquote></details>

It gives a preview of what to expect in this data class. Are you suggesting that the class documentation reads just
```
Data supporting calculations in LinearConstitutiveModel.
```
? I'm happy with that too.
___
*[multibody/fem/linear_constitutive_model_data.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq8mx-dToPparjG80:-MgfncNR7NmyKjQ_13DE:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L36)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW: "...the latest deformation gradient F." 

You might choose to rephrase this in terms of APIs. What defines "the latest gradient"? It is, in fact, the gradient passed when `UpdateData()` was last invoked. Generally, it's a good idea to mention the mechanism (if it's not obvious) so that users know what cause to look for if their effect is not what they expect.

(Same applies below.)
</blockquote></details>

Done, thanks!
___
*[multibody/fem/linear_constitutive_model_data.h, line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQqW3P0NQKLVVi3FYU:-MgfmjDy25ZuxJJuH3IG:b3rhmw2) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L48)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW From a previous conversation, it's not clear that this alias particularly provides value in *this* instantiation either. We'd left this spelling in the base class's test to serve as a good example. Does it actually provide value anywhere or was the value documented in the test purely speculative?
</blockquote></details>

You are right in that "the value documented in the test purely speculative". I found it to be useful in other CRTP classes but it turns out it's not used at all for all derived `DeformationGradientData`. I made a pass to remove the alias and squeezed it into this PR. Let me know if you want to see it in a separate one.
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQsBHF44vahsBsww9_:-Mgfpb3rEHgm4Ec1L3xX:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/test/linear_constitutive_model_data_test.cc#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Can we get a comment here confirming that it is initialized with all of the values *consistent* (as documented in the constructor implementation)?
</blockquote></details>

Done, thanks.
___
*[multibody/fem/test/linear_constitutive_model_data_test.cc, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQsIWt0TBRvbLEizUL:-MgfoWqo2svm32YEve14:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/test/linear_constitutive_model_data_test.cc#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As mentioned in previous PRs, let's move away from a diagonal matrix so we can confirm we're doing the full calculation (and not just on the diagonal). And an F that isn't symmetric would likewise be a good thing.
</blockquote></details>

Done, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some (hopefully helpful) further elaboration on a previous comment.

> Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566#-:-MggZ0xf-5CeheEj22K3:bl2lyx0)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/linear_constitutive_model_data.h, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq1_c9bEegJyydift:-MggXzkQEfjlEn645EgL:bh6dkpw) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It gives a preview of what to expect in this data class. Are you suggesting that the class documentation reads just
```
Data supporting calculations in LinearConstitutiveModel.
```
? I'm happy with that too.
</blockquote></details>

No, I mean the phrase "see class documentation" doesn't provide much value. The class documentation says exactly the same thing about this quantity as documented here. I won't gain any further insight into "infinitesimal strains" by reading the class documentation than be reading here already. In other words, you can just leave out that phrase entirely).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[multibody/fem/linear_constitutive_model_data.h, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15566#-MgQq1_c9bEegJyydift:-Mgg_oy49fVQIatZc6gp:by9m6zf) ([raw file](https://github.com/robotlocomotion/drake/blob/c736b0f341157693f842062ba9420b9d3a953419/multibody/fem/linear_constitutive_model_data.h#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

No, I mean the phrase "see class documentation" doesn't provide much value. The class documentation says exactly the same thing about this quantity as documented here. I won't gain any further insight into "infinitesimal strains" by reading the class documentation than be reading here already. In other words, you can just leave out that phrase entirely).
</blockquote></details>

I see. I misunderstood earlier. Done, thanks.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15566)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
