### PR TITLE
[render_vtk] Silence gltf basisu extension warnings by default

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add RenderVtkParams configuration for what to silence.

Fix serialize_pybind to admit the full vector and map template signatures.

Towards #20935.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

I imagine this is somewhat lacking in documentation, but I'm not exactly sure what's missing / where.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Documentation level seems reasonable to me.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-:-NtqKMa8-6gFEMCz1CwK:bdp1f5l)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-NtqIb3b2_frF1lVNL0J:-NtqIb3b2_frF1lVNL0K:b-sv904j) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a08c4d05870db4815a9605d79a1d7c57ff7dbe/geometry/render_vtk/render_engine_vtk_params.h#L78)):*
> ```objc
> https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#specifying-extensions
> */
> struct GltfExtension {
> ```

BTW This particular approach seems to imply the expectation that you're going to allow more per-extension configuration. Otherwise, I would've imagined a dictionary in the main configuration to a value indicating how it should be handled. Do you have a sense of what that might be?

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-:-NtrLOjBBSbZpMHcjSXq:b-z0s7k5)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-NtqIb3b2_frF1lVNL0J:-NtrKY1_74VS8kmobuqo:bggex88) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a08c4d05870db4815a9605d79a1d7c57ff7dbe/geometry/render_vtk/render_engine_vtk_params.h#L78)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This particular approach seems to imply the expectation that you're going to allow more per-extension configuration. Otherwise, I would've imagined a dictionary in the main configuration to a value indicating how it should be handled. Do you have a sense of what that might be?
</blockquote></details>

My main motivation was actually having the most readable naming scheme.  Something like `map<string, bool> gltf_extension_warn_unimplemented` seemed slightly more awkward.

But yes, possibly we add more settings in time.  I'm thinking of cases where "extensionsRequired" might have been mis-populated in the input file and we might want to work around that without making the user rewrite their file.

Or on the other hand, in case we ever have different builds of Drake with different extension support (e.g., Draco is only on Ubuntu, not macOS) we could promote "extensions used" warnings to errors, in case the user would rather fail-fast when a certain extension had not been compiled into VTK.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-NtqIb3b2_frF1lVNL0J:-NtrStkn08TvNeL2Mmd-:bbqpvay) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a08c4d05870db4815a9605d79a1d7c57ff7dbe/geometry/render_vtk/render_engine_vtk_params.h#L78)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My main motivation was actually having the most readable naming scheme.  Something like `map<string, bool> gltf_extension_warn_unimplemented` seemed slightly more awkward.

But yes, possibly we add more settings in time.  I'm thinking of cases where "extensionsRequired" might have been mis-populated in the input file and we might want to work around that without making the user rewrite their file.

Or on the other hand, in case we ever have different builds of Drake with different extension support (e.g., Draco is only on Ubuntu, not macOS) we could promote "extensions used" warnings to errors, in case the user would rather fail-fast when a certain extension had not been compiled into VTK.
</blockquote></details>

I was thinking that it led to some bloated yaml. (Each level incurring an additional cost of getting the incantation just right.)

Which makes me wonder if we shouldn't have an example *somewhere* of proper yaml configuration of this new field.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-NtqIb3b2_frF1lVNL0J:-NtsVVRJ4GBXleqzOP0H:bkyns19) ([raw file](https://github.com/RobotLocomotion/drake/blob/34a08c4d05870db4815a9605d79a1d7c57ff7dbe/geometry/render_vtk/render_engine_vtk_params.h#L78)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was thinking that it led to some bloated yaml. (Each level incurring an additional cost of getting the incantation just right.)

Which makes me wonder if we shouldn't have an example *somewhere* of proper yaml configuration of this new field.
</blockquote></details>

I added example yaml to the unit test.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21183#-:-Ntw7vmH-hT4VFylK5gB:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
