### PR TITLE
Fix submodule sync for AVL and XFOIL during Ninja builds of drake

### PR DESCRIPTION
**Pull request by jamiesnape**
Not sure this actually broke anything at present, but @mwoehlke-kitware points out that it is incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3448)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review and @david-german-tri for platform review.

**Comment by jamiesnape** [comment]
A one word pull request.

**Comment by mwoehlke-kitware** [comment]
> Not sure this actually broke anything at present

Well, `xfoil` and `avl` lost their dependency on `submodule-sync`... in a full build you *might* be okay, and/or if no externals need to be updated... but certainly those dependencies are supposed to exist.

**Comment by jamiesnape** [comment]
Not sure Reviewable syncs review approvals.

**Comment by mwoehlke-kitware** [comment]
Actually, maybe those aren't hitting the `elseif`... still, the check is wrong and makes me nervous that someone will hit the corner case and we'll end up with an obscure bug :smile:.

**Comment by mwoehlke-kitware** [comment]
> Not sure Reviewable syncs review approvals.

Probably not (hey, can we ditch reviewable now? :smile:), but @david-german-tri's counts for both anyway...

**Comment by david-german-tri** [comment]
Wait, GitHub has a notion of approval?  That's new.

**Comment by jamiesnape** [comment]
You can enforce it to an extent on protected branches, also.

**Comment by david-german-tri** [comment]
Ah, I see.  This quirk applies whenever the superbuild uses Ninja, regardless of what the external uses.  That makes sense.  

I remember looking at this in #3432 and thinking "oh, kudos to Jamie for catching that use."  Oh well.  ;-)

:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3448#-:-KReIn6bZuEDxalX5xrU:b-nhxe0u)*

**Comment by mwoehlke-kitware** [comment]
> Wait, GitHub has a notion of approval? That's new.

It is :grin:. I'd never seen it before; pretty sure it's less than a week old. I'd guess they don't have the notion of feature vs. platform review and the same control over who constitutes such, but otherwise it looks like they've possibly picked up much of what reviewable does...

> Ah, I see. This quirk applies whenever the superbuild uses Ninja, regardless of what the external uses.

Exactly.

**Pull request merged**
