### PR TITLE
Removing geometry/frame removal API

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The original geometry system API included the ability to remove geometry on-the-fly (in some sense). This PR removes that API for the following reasons:

1. The "remove geometry" API for geometry system was originally envisioned to support automotive's expected need to page in/out geometry during simulation. However, automotive is not an immediate target.
2. The System architecture doesn't have an infrastructure that allows one system to trigger events in another system -- a fundamental requirement in order to realize on-the-fly geometry modifications.
3. Removing this API reduces the burden to add additional features in the interim (thinking of a render engine here).

Therefore, we kill the API for now, decluttering as we go.

Almost without exception, the modification is 100% code deletion with a single exception:

`geometry_system_test.cc` - The transmogrification test indirectly used removal functionality to test the resultant transmogrified state. I changed that to a query.  That's the "new" code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7960)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@ericcousineau-tri for feature and platform review, please. Let me know if you'd prefer someone else for feature review -- but as it's basically a mowing down of code, CI passing should cover "feature" review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7960#-:-L4bGyv9_-gpjcd-KKlx:bqtsj74)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7960#-L4bLxdm6a0yTwliUwAn:-L4bLxdn5XI398BtsAjq:bjoy42f) (no related file):*
Will have f2f to discuss to figure out other impacts (e.g. can geometries still be dynamically added).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7960)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7960#-L4bLxdm6a0yTwliUwAn:-L4bYtriSYW_lOpEGFFN:bcnbkk4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Will have f2f to discuss to figure out other impacts (e.g. can geometries still be dynamically added).
</blockquote></details>

Discussed scope via f2f (there is no "asymmetry", in that geometries cannot be dynamically added, so removing dynamic removal will not create an imbalance).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7960)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7960#-:-L4bZ4LvHMCZazbvbHqC:bnfp4nl)*

**Pull request merged**
