### PR TITLE
Add a Stop Running button and Meshcat reuse to ModelVisualizer

### PR DESCRIPTION
**Pull request by trowell-tri**
These fixes are necessary in order to replace the model_inspector function in authoring_multibody_simulation with the ModelVisualizer class.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18284)

### CODE REVIEW

**Review by trowell-tri — COMMENTED** [review]
+@zachfang and +@jwnimmer-tri for feature review, please
FYI @jshep-tri

+(release notes: feature) for the new constructor argument to ModelVisualizer

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18284#-:-NGSKsWD02KxsgtfRkA2:b-vpb4db)* status: LGTM missing from assignees zachfang,jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @zachfang)

**Review by trowell-tri — COMMENTED** [review]
This is toward #17689

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18284#-:-NGSLbXf71941bKsaUvv:bntyl9a)* status: LGTM missing from assignees jwnimmer-tri(platform),zachfang (waiting on @jwnimmer-tri and @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform (and feature).

We'll let Zach review as well.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18284#-:-NGSTAzUBEcqusZvtjW6:b-z0i9ly)* status: LGTM missing from assignee zachfang (waiting on @zachfang)

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18284)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18284#-NGT-f99Ed9AH-hvNv72:-NGT0IAq8SL6EIA7_Nme:bcgm09o) ([raw file](https://github.com/robotlocomotion/drake/blob/d0d52977d6121c7f895313e73879ce0a0c415ddc/bindings/pydrake/visualization/_model_visualizer.py#L77)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Is the newline between `meshcat` and `pyplot` comments intended?
</blockquote></details>

It was intentional since it's a different sort of argument (to me) than the browser/pyplot args (which open new windows) which are different from the frame visualization stuff.

**Pull request merged**
