### PR TITLE
Added ability to compute generalized contact forces

### PR DESCRIPTION
**Pull request by edrumwri**
Transforms contact forces (from rigid contact) on a system into generalized forces. Uses this capability to add tests for the rigid contact solver.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6568)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-Kowm8aYeHmJb25CQ0ms:bgdoi2o)*

**Comment by siyuanfeng-tri** [comment]
BTW I have a tiny suggestion that have small functions to access / mutate cf, instead of having .segment everywhere in the code / tests. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-Kp0rx6VM1mhXNwo8SmU:bv13r04)*

**Comment by edrumwri** [comment]
Thinking about this (namely, whether I can address that through an upcoming PR). Thanks Siyuan!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-Kp1qwksM0kvyqoPG3OV:b-596pwz)*

**Comment by edrumwri** [comment]
+@jwnimmer-tri for feature review please (per regular rotation)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-Kp1xuzhTComQZQEnoyF:bw334f2)*

**Comment by edrumwri** [comment]
FYI, I'll be able to remove the cf.segment() stuff in my next PR, which converts the "packed" representation into contact frames and forces. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-Kp22Kz18jczYpF7HUZj:b-wejnkf)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFn9KS3mpXvTVPZQp6:-KpFn9KTrzh9z0yJUg8P:b-q8my01) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L54)):*
> ```objc
> 
>   /// Computes the generalized force on the system from the contact forces given
>   /// in packed storage. Aborts if @p generalized_force is null.
> ```

FYI _Meta_ Instead of (untestably) promising what happens when a parameter is `null`, I'd prefer to see the API say either "@throw error when foo is null" (so making a stronger promise, changing from DEMAND to THROW_UNLESS) or "@pre foo is non-null" (making a weaker promise).  No defect.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFoUsa7WWXo7dupMGq:-KpFoUsa7WWXo7dupMGr:b-7oguvs) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L68)):*
> ```objc
>   /// (stored in @p problem_data) and the contact forces. Aborts if
>   /// @p generalized_acceleration is null.
>   static void ComputeGeneralizedAcceleration(
> ```

It seems to me like the layout of `cf` needs to be explained here (even if by citation), similarly to the above method?

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFpCKhXLBbb3gC32oe:-KpFpCKhXLBbb3gC32of:b7yxlhr) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L251)):*
> ```objc
>   const int num_sliding = problem_data.sliding_contacts.size();
>   const int num_non_sliding = problem_data.non_sliding_contacts.size();
>   const int nc = num_sliding + num_non_sliding;
> ```

_Meta_ Please take a look at https://google.github.io/styleguide/cppguide.html#General_Naming_Rules and reconsider the short variable names in this PR.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFozRMKNfLip06QewT:-KpFozRNWhQt3R0K3hA3:bmokxj) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L255)):*
> ```objc
>                                  problem_data.r.end(), 0);
> 
>   /// Verify cf is the correct size.
> ```

_Meta_ Don't use Doxygen style _within_ a method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568)*

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFn9KS3mpXvTVPZQp6:-KpG8xRBMH9DjNn2fwo5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ Instead of (untestably) promising what happens when a parameter is `null`, I'd prefer to see the API say either "@throw error when foo is null" (so making a stronger promise, changing from DEMAND to THROW_UNLESS) or "@pre foo is non-null" (making a weaker promise).  No defect.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFoUsa7WWXo7dupMGq:-KpG9F1ShAkzbbvf6A-k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like the layout of `cf` needs to be explained here (even if by citation), similarly to the above method?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFpCKhXLBbb3gC32oe:-KpG8ygFPVzcxFLfkM-N:b-5jnl2v) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L251)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Please take a look at https://google.github.io/styleguide/cppguide.html#General_Naming_Rules and reconsider the short variable names in this PR.
</blockquote></details>

PTAL and see whether you feel this is better- I had put this modification in place before (and rejected it) because it makes the construction of MM and qq so much uglier (IMO).

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFozRMKNfLip06QewT:-KpG6tlNkMhHR3000j6v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L255)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Don't use Doxygen style _within_ a method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568)*

**Comment by jwnimmer-tri** [comment]
Once any churn settles down, be sure that feature review is caught up and still OK.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFpCKhXLBbb3gC32oe:-KpGG295VbXAiMsg-NON:b-88ydmf) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L251)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

PTAL and see whether you feel this is better- I had put this modification in place before (and rejected it) because it makes the construction of MM and qq so much uglier (IMO).
</blockquote></details>

OK I think this a great improvement for the new code in this PR; I'm marking myself satisfied.

If you don't like the MM/qq-related code now, then you should repair it.

I think there are creative ways to make the MM-related block / segment statements more succinct.  For example, declare more temporary ints for the repeated sub-expressions, possibly even abbreviating them to `i_foo` as bare indices, either declared in a batch up-front, or done with "+=" running counters, depending on the flow.  Alternatively, named blocks and sub-blocks might help.  I haven't studied the MM matrix being created to have a specific opinion.  Alternatively, for MM/qq you could have the long names appear atop the method, and then in the MM/qq block offsets use clearly articulated abbreviations as in `const int nc = num_contacts;` and then use `nc` for that math.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-KpGHjEL_F0t3kvHPp7w:brmj1ml)*

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-KpFpCKhXLBbb3gC32oe:-KpGYGkZgr48d0C0SSic:be988pw) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4cb5af668471accbbe759c8291f8561246d3b7/drake/multibody/rigid_contact/rigid_contact_solver.h#L251)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I think this a great improvement for the new code in this PR; I'm marking myself satisfied.

If you don't like the MM/qq-related code now, then you should repair it.

I think there are creative ways to make the MM-related block / segment statements more succinct.  For example, declare more temporary ints for the repeated sub-expressions, possibly even abbreviating them to `i_foo` as bare indices, either declared in a batch up-front, or done with "+=" running counters, depending on the flow.  Alternatively, named blocks and sub-blocks might help.  I haven't studied the MM matrix being created to have a specific opinion.  Alternatively, for MM/qq you could have the long names appear atop the method, and then in the MM/qq block offsets use clearly articulated abbreviations as in `const int nc = num_contacts;` and then use `nc` for that math.
</blockquote></details>

Done (your last suggestion)- this is a significant improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

:lgtm:, though make sure you see Siyan's face bubble for final feature review in the file matrix before merging.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-KpGg4gx0ZAd4brcLFM4:b-rg8vu4)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6568#-:-KpGy4eI-YfYomWcLnpb:bnfp4nl)*

**Pull request merged**
