### PR TITLE
Renames GeometrySystem to SceneGraph

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This is purely a cosmetic change requested in #8473.

In this case, the generically-named `GeometrySystem` is now called `SceneGraph` which is more suggestive of its role. Its done in two commits to (hopefully) facilitate review. The first commit is the file renaming (and all file name references) -- hopefully, reviewable will recognize that the file got moved and *then* edited and not treat the whole file as new.

The second commit the changes the name of the class in its usage, documentation, and local and class variable names.  

Ultimately, what you *should* see is a bunch of these:
  - s/GeometrySystem/SceneGraph
  - s/geometry_system/scene_graph
  - outlier variable names that weren't obviously `geometry_system`
  - re-ordering of references to reflect that `SceneGraph` > `GeometrySystem` in total ordering.

These changes are scattered over a *mess* of files. Sorry about that.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8639)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@soonho-tri for feature and platform review. Let me know if you want a feature review on this.

---

Review status: 0 of 60 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUEMUN5w2JbS4GaBjR:beyxu2x)*

**Comment by soonho-tri** [comment]
Checkpoint

---

Reviewed 4 of 65 files at r1.
Review status: 4 of 59 files reviewed at latest revision, all discussions resolved.

---

*[examples/geometry_world/bouncing_ball_plant.cc, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-LAUSevV32c-clHq5j6A:-LAUSevV32c-clHq5j6B:bc7nrao) ([raw file](https://github.com/robotlocomotion/drake/blob/3b63da27db6ef442bf55476336e111c2dcbba4f5/examples/geometry_world/bouncing_ball_plant.cc#L20)):*
> ```cpp
> using geometry::GeometryFrame;
> using geometry::GeometryInstance;
> using geometry::SceneGraph;
> ```

FYI, META, this replacement breaks the sortedness property. I suggest 1) running `git-clang-format HEAD~~` (assuming that this PR consists of two commits) and 2) adding it to this PR as 3rd commit (we can squash things later)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUT__D72EVN-3adXsF:b13s2ul)*

**Comment by soonho-tri** [comment]
:lgtm: 

BTW, do we still have `GeometryContext` and `GeometryState`. Do you plan to rename them as well in the future?

---

Reviewed 58 of 65 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUXyDZE9_66v-SttgU:b-jnsl08)*

**Comment by SeanCurtis-TRI** [comment]
I briefly considered changing them. But a) because of the size of this PR and b) because they are really "under-the-hood" details, I thought it wasn't as important. Plus "GeometryState" is pretty descriptive.  :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUtJqa8Sm5w8cSNnPl:bvcmr8e)*

**Comment by soonho-tri** [comment]
Good to know :-)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUtuU-ACB4WV0ZaQuo:b-4s3vqw)*

**Comment by SeanCurtis-TRI** [comment]
Good call on the git-clang-format. I'd caught *a lot* of things due to the renaming, but there were about a thousand other things that I hadn't.

---

Review status: 32 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/geometry_world/bouncing_ball_plant.cc, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-LAUSevV32c-clHq5j6A:-LAUtavA6y7copBGCurq:bunwre4) ([raw file](https://github.com/robotlocomotion/drake/blob/3b63da27db6ef442bf55476336e111c2dcbba4f5/examples/geometry_world/bouncing_ball_plant.cc#L20)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, META, this replacement breaks the sortedness property. I suggest 1) running `git-clang-format HEAD~~` (assuming that this PR consists of two commits) and 2) adding it to this PR as 3rd commit (we can squash things later)
</blockquote></details>

Done; I thought I'd caught them all, but I guess there's always one. I'll give `git-clang-format` a try.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAUv7iX6JOU2xSZy2La:b-uh1n4s)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 30 files at r2.
Review status: 33 of 59 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[examples/geometry_world/bouncing_ball_plant.cc, line 20 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-LAUSevV32c-clHq5j6A:-LAUxarKC5CKOQovPU4v:b-h29qfn) ([raw file](https://github.com/robotlocomotion/drake/blob/3b63da27db6ef442bf55476336e111c2dcbba4f5/examples/geometry_world/bouncing_ball_plant.cc#L20)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done; I thought I'd caught them all, but I guess there's always one. I'll give `git-clang-format` a try.
</blockquote></details>

Hmm. I'm wondering why there is no changes for this one. `git-clang-format` should give something like

```diff
 using geometry::FramePoseVector;
 using geometry::GeometryFrame;
 using geometry::GeometryInstance;
-using geometry::SceneGraph;
 using geometry::PenetrationAsPointPair;
+using geometry::SceneGraph;
 using geometry::SourceId;
 using geometry::Sphere;
+using std::make_unique;
 using systems::Context;
 using systems::Value;
-using std::make_unique;
```

The followings are what I ran:
```bash
git fetch --all
git rebase upstream/master
git-clang-format upstream/master  # This should call clang-format over the changes between HEAD and upstream/master
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639)*

**Comment by soonho-tri** [comment]
:lgtm: Thank you!

---

Reviewed 25 of 30 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAV0O4l9sUbaZsDRCyl:b-ae66e1)*

**Comment by SeanCurtis-TRI** [comment]
+(status: do not merge)  (A test...)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAV26UABbykQlBPPAZ7:b4cl7sr)*

**Comment by SeanCurtis-TRI** [comment]
-(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAV2DsRCmxiydFF_MMe:b-b9fcpn)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8639#-:-LAV2IVI30K0uBXdfZ54:b-l70wzf)*

**Pull request merged**
