### PR TITLE
update externals/bot_core_lcmtypes and switch url to upstream

### PR DESCRIPTION
**Pull request by patmarion**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4783)

### CODE REVIEW

**Comment by patmarion** [comment]
@mwoehlke-kitware let me know if you're already updating this external in another PR, I can close this if it will create conflicts with you.  Otherwise, would like to get this updated.

**Comment by mwoehlke-kitware** [comment]
:lgtm:
Surprisingly, I do not seem to have any branches that update bot_core_lcmtypes. (I say surprisingly because *I* have made changes to the bot_core_lcmtypes repo that are more recent than what is in drake... not sure why drake never got updated...)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4783#-:-KaOXEgUm51ae0vBPtNe:b-cdco5r)*

**Comment by ggould-tri** [comment]
+@ggould-tri  for platform review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4783#-:-Kax_80qMmSyI4oO3mSy:bpt25h4)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-xcode-experimental please

**Comment by jwnimmer-tri** [comment]
The `url` change seems appropriate, returning from a personal fork to upstream master.

I reviewed the diffs between the shas, and they seem reasonable, though have enough build-system changes that we need to reconfirm that the OS X builds work (launched now).

:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4783#-:-Kax_-bEtH4IX804knpy:b77rw1s)*

**Comment by ggould-tri** [comment]
@jwnimmer-tri anticipated my analysis.  I checked the same and reached the same conclusion.  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4783#-:-Kaxa09zUZA_zTib3zyU:bc9tne4)*

**Comment by patmarion** [comment]
hmm, the mac-clang-xcode-experimental build failed in a seemingly unrelated area:

https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=323471

**Comment by jwnimmer-tri** [comment]
Oh, my bad!  I forgot that xcode is not officially supported, and is currently broken.

**Pull request merged**
