### PR TITLE
pydrake: Add guidance for ambiguous const-vs-mutable overloads" (#15439)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This reverts commit 90469847 (#15439), and applies a workaround.
Effectively restores #15404

Came up during #15581

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for (re)review, please
+@jwnimmer-tri for platform (re)review, please

\cc @seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587#-:-MgglxWnAsa3WS_ZqVPS:blb0b69)* status: LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15587#-MgguQYF18zgWQhP_LXr:-MgguQYF18zgWQhP_LXs:b-mdi0dt) (no related file):*
I'm not particularly eager to re-review something I've already reviewed.  Could you rebase this PR to have the original (reverted) commit intact in the first commit, with your workaround in a second commit, so that we can acutely review the new diffs?  We'd still squash when we're done here, but for review it would help a lot.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15587#-Mggy2fD9UuYvc5MHt2f:-Mggy2fE0SQVERbErLWf:bg24c66) (no related file):*
Working: Mark post-revert.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15587#-MgguQYF18zgWQhP_LXr:-MggyjSFBpooTKc_6AkP:bfc3zl5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not particularly eager to re-review something I've already reviewed.  Could you rebase this PR to have the original (reverted) commit intact in the first commit, with your workaround in a second commit, so that we can acutely review the new diffs?  We'd still squash when we're done here, but for review it would help a lot.
</blockquote></details>

Done! (sorry, should've done that to start)

Since I always get confused by "review each commit separately", I just marked revisions.
- `base..r3` shows unrevert
- `r3..r4` shows fix

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15587#-Mggy2fD9UuYvc5MHt2f:-MggyiHu6DIGmKvrHTwC:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Mark post-revert.
</blockquote></details>

Done.

---

**Review by jwnimmer-tri — COMMENTED** [review]
Huh, I thought I tried removing the `{.cc}` and it didn't fix it.  Oh well, I must have PEBKAC'd.

:lgtm: platform.

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587#-:-MggyxbDAYjpYPhPQvEt:bcsanh6)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587#-:-MghBGM19UAo6HVZy6Yt:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15587#-MghAn577nqiVC3a-6YQ:-MghAn58CoLhBSk-UHQl:b-bfa34b) ([raw file](https://github.com/robotlocomotion/drake/blob/a1683f4e0ab00542a2b9b65894bbeccfe5e9e7fa/-- commits#L2)):*
BTW, I'm a fan of rewriting the "revert revert" gibberish from `git` with something like "Reapply fixed [some patch]" making sure to reference both the original patch and the revert commit.

Not sure what common practice is here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15587#-MghAn577nqiVC3a-6YQ:-MghLu2z2sy6yYRnLUTw:b7e78ir) ([raw file](https://github.com/robotlocomotion/drake/blob/a1683f4e0ab00542a2b9b65894bbeccfe5e9e7fa/-- commits#L2)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, I'm a fan of rewriting the "revert revert" gibberish from `git` with something like "Reapply fixed [some patch]" making sure to reference both the original patch and the revert commit.

Not sure what common practice is here.
</blockquote></details>

I don't think Eric's intention was to use that commit message as we reach master.  The original PR had the more preferred phrasing that we'd normally use.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15587)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15587#-MghAn577nqiVC3a-6YQ:-Mgkzz8y-XePXYs5opTK:b-b74gg3) ([raw file](https://github.com/robotlocomotion/drake/blob/a1683f4e0ab00542a2b9b65894bbeccfe5e9e7fa/-- commits#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think Eric's intention was to use that commit message as we reach master.  The original PR had the more preferred phrasing that we'd normally use.
</blockquote></details>

OK Yup! Will use prior PR as template for commit, w/ some extra description about restoring.

**Comment by SeanCurtis-TRI** [comment]
I'm late to this party, but I was surprised by the guidance here.

Why have two functions `Foo()` and `MutableFoo()` bound when they return the same thing? While it reduces ambiguity to the *system*, it lies to the pydrake user. Two methods imply differences, but they do exactly the same thing with the same semantics. Surely that clutters up the namespace in a non-helpful way?

**Comment by jwnimmer-tri** [comment]
Are you referring to the `MyOtherClassPreferred` example?  They are not the same semantics.  One will invalidate cache entries, the other will not.

**Pull request merged**
