### PR TITLE
bindings: Remove cpp_const

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This appears to be dead code.  By dropping it, we can also drop an awkward dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14270)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2 - sorry about that!

(Had prepped it for cache stuff, but seems like people have seemed good about not using stale / poisoined caches)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14270#-:-ML3r3BE7p3mDZZcGhXS:b-idudkb)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14270)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14270)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14270#-ML3rCebDLRhFM1FmPlT:-ML3rCebDLRhFM1FmPlU:b-8g5x56) (no related file):*
BTW This is a backwards-incompatible change - for whatever reason, someone could have been using `pydrake.common.cpp_const`; however, I'm totes fine with that.

---

**Pull request merged**
