### PR TITLE
Updated name of single-car Drake/ROS demo to make way for a multi-car version

### PR DESCRIPTION
**Pull request by liangfok**
This is mostly just renaming files and updating instructions to make way for a multi-car demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3019)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review please.
+@sherm1 for platform review please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO6WtYEBGHIYdCcRAZe:-1146658921)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jhoare** [comment]
Ran this and it appears to work. :lgtm:

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO6nMtmp7M3M3ztZZIg:1872321570)*

**Comment by liangfok** [comment]
Thanks. Now waiting on @sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO6oeenEcaz7VlvDbtc:1375646622)*

**Comment by sherm1** [comment]
Platform review pass done, minor stuff.

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage.launch, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6sdyi9in7k0wFIo7L:-KO6sdyjgNMKpitZHVq5:1687216346) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage.launch#L18)):*
> ```XML
> 
>   <include file="$(find drake_cars_examples)/launch/golfcart_adapter.launch" />
> </launch>
> ```

missing newline at eof

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_desc.xml, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6sglRpZ06pCdYsJpS:-KO6sglRpZ06pCdYsJpT:1687216346) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_desc.xml#L13)):*
> ```XML
>   <param name="world_description"
>          textfile="$(find drake_cars_examples)/models/stata_garage_p1.urdf" />
> </launch>
> ```

missing newline at eof

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6tuCZYRRyof8h21ex:-KO6tuCZYRRyof8h21ey:1625276062) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml#L5)):*
> ```XML
>   
>   <include file="$(find drake_cars_examples)/launch/rviz.xml">
>     <arg name="RVizConfigFile" value="$(find drake_cars_examples)/rviz/single_prius_in_stata_garage.rviz" />
> ```

BTW, everything else says `single_car_in_...` but this says `single_prius_in_...`. Is that right?

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6svwy16VWD8nzYyz3:-KO6svwy16VWD8nzYyz4:1687216346) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml#L7)):*
> ```XML
>     <arg name="RVizConfigFile" value="$(find drake_cars_examples)/rviz/single_prius_in_stata_garage.rviz" />
>   </include>
> </launch>
> ```

missing newline at eof

---

*[ros/drake_cars_examples/rviz/single_prius_in_stata_garage.rviz, line 499 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6th7o8rHH2sqigVHe:-KO6th7o8rHH2sqigVHf:20368812) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/rviz/single_prius_in_stata_garage.rviz#L499)):*
> ```YAML
>   Hide Right Dock: false
>   QMainWindow State: 000000ff00000000fd000000040000000000000238000004d4fc0200000008fb0000001200530065006c0065006300740069006f006e00000001e10000009b0000006400fffffffb0000001e0054006f006f006c002000500072006f007000650072007400690065007302000001ed000001df00000185000000a3fb000000120056006900650077007300200054006f006f02000001df000002110000018500000122fb000000200054006f006f006c002000500072006f0070006500720074006900650073003203000002880000011d000002210000017afb000000100044006900730070006c0061007900730100000028000004d4000000dd00fffffffb0000002000730065006c0065006300740069006f006e00200062007500660066006500720200000138000000aa0000023a00000294fb00000014005700690064006500530074006500720065006f02000000e6000000d2000003ee0000030bfb0000000c004b0069006e0065006300740200000186000001060000030c00000261000000010000010f00000582fc0200000003fb0000001e0054006f006f006c002000500072006f00700065007200740069006500730100000041000000780000000000000000fb0000000a00560069006500770073000000002800000582000000b000fffffffb0000001200530065006c0065006300740069006f006e010000025a000000b200000000000000000000000200000490000000a9fc0100000001fb0000000a00560069006500770073030000004e00000080000002e1000001970000000300000a1e0000004cfc0100000002fb0000000800540069006d0065010000000000000a1e000002f600fffffffb0000000800540069006d00650100000000000004500000000000000000000007e0000004d400000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
>   Selection:
> ```

BTW, this looks like some kind of machine-generated file. Is it supposed to be checked into the repo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO6uB6_Y3JpE5AMi42n:-234873046)*

**Comment by liangfok** [comment]
@sherm1 I addressed your comments. PTAL. Thanks!

---

Review status: 6 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage.launch, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6sdyi9in7k0wFIo7L:-KO8E0oi3GPfGdroNpXX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage.launch#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at eof
</details>
Done.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_desc.xml, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6sglRpZ06pCdYsJpS:-KO8DarcTTkwitVmpu1s:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_desc.xml#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at eof
</details>
Done.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml, line 5 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6tuCZYRRyof8h21ex:-KO8DsVZ5g7BL1j9FW26:126468990) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, everything else says `single_car_in_...` but this says `single_prius_in_...`. Is that right?
</details>
Done. I renamed it to be "single_car_in_stata_garage.rviz" for consistency.

---

*[ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6svwy16VWD8nzYyz3:-KO8Dz2VI8JoAKl9zQGn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/launch/single_car_in_stata_garage_rviz.xml#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> missing newline at eof
</details>
Done.

---

*[ros/drake_cars_examples/rviz/single_prius_in_stata_garage.rviz, line 499 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-KO6th7o8rHH2sqigVHe:-KO7tCWiPYT0yRJy11OP:721989759) ([raw file](https://github.com/robotlocomotion/drake/blob/395292d1c4fa701b5f22521d457486d8b3e00c84/ros/drake_cars_examples/rviz/single_prius_in_stata_garage.rviz#L499)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this looks like some kind of machine-generated file. Is it supposed to be checked into the repo?
</details>
Yes, this was auto-generated by [RViz](http://wiki.ros.org/rviz). However, it needs to be checked into the repository because it specifies things like which models, frames, and sensor visualizations to display.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO8EBSAeS3HaTn23Ggl:1448456807)*

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 1 of 14 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3019#-:-KO8OwcT8X-ekTfxdNZs:-1446635318)*

**Pull request merged**
