### PR TITLE
Adds DecodeLastPublishedMethodAs<T>() to DrakeMockLcm.

### LINKED ISSUE #4760: Consider Adding DrakeMockLcm::DecodeLastPublishedMessageAs<T>().
It'll be nice to add this method to simplify call sites. Instead of:

```
  lcmt_drake_signal transmitted_message;
  // Decodes message and checks that the correct number of bytes was processed.
  EXPECT_EQ(transmitted_message.decode(transmitted_message_bytes.data(), 0,
                           transmitted_message_bytes.size()),
            transmitted_message_bytes.size());
  EXPECT_EQ(transmitted_message.timestamp, timestamp);
```

call sites will have:

```
  EXPECT_EQ(lcm.DecodeLastPublishedMessageAs<lcmt_drake_signal>().timestamp, expected_time);
```

This issue was extracted from @jwnimmer-tri's here: 
https://reviewable.io/reviews/robotlocomotion/drake/4731#-KaFflRdzSJhvDvZw963

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4760.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4787)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please. Thanks!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-KaVbH8lBz1LQsyYkBmi:benp8iw)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNs_ojEAIQr0Rv0I4:-KaXNs_p6RpMe5NKURdj:b-faxrsc) (no related file):*
BTW Should #4731's changes be amended to use this new feature, also?  I guess #4775 isn't merged yet so we can't amend its uses as part of this PR.

---

*[drake/lcm/drake_mock_lcm.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXLGrCeZ2ei25-CNjA:-KaXLGrDtK1jX3FSrh8C:bcnzk7d) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/drake_mock_lcm.h#L51)):*
> ```objc
>   template<typename T>
>   T DecodeLastPublishedMessageAs(const std::string& channel) const {
>     const std::vector<uint8_t>&  message_bytes =
> ```

BTW I think this is a double space after the `&`?

---

*[drake/lcm/drake_mock_lcm.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXLQDgkNLe6kb5Goji:-KaXLQDgkNLe6kb5Gojj:b9nsq4k) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/drake_mock_lcm.h#L54)):*
> ```objc
>         get_last_published_message(channel);
> 
>     T transmitted_message;
> ```

BTW Probably doesn't matter, but consider adding `{}` to initialize the message, in case for some reason the decode doesn't set everything (it should, though).

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNcLrReLnsUql0Egc:-KaXNcLsZaBUoq_vqKWE:bqpzul4) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/test/drake_mock_lcm_test.cc#L55)):*
> ```cpp
>   const int message_size = original_message.getEncodedSize();
> 
>   vector<uint8_t> original_message_bytes;
> ```

BTW `original_` prefix here perhaps doesn't add much, since they are the only bytes in the test? -- we're not doing a readback-to-bytes test.  (Not a defect.)

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXMju9pMencd-tPzWJ:-KaXMju9pMencd-tPzWK:b-gise3t) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/test/drake_mock_lcm_test.cc#L73)):*
> ```cpp
>   EXPECT_EQ(last_published_message.coord.at(0), original_message.coord.at(0));
>   EXPECT_EQ(last_published_message.timestamp, original_message.timestamp);
> }
> ```

I think it would be easy and worthwhile to test that a decoding error throws an exception, since we will be relying on that behavior in unit tests that call this.

```
  dut.Publish(channel_name, &original_message_bytes[0], message_size - 1);
  EXPECT_THROW(dut.DecodeLastPublishedMessageAs<lcmt_drake_signal>(channel_name), std::runtime_error);

  original_message_bytes.push_back(0);
  dut.Publish(channel_name, &original_message_bytes[0], message_size + 1);
  EXPECT_THROW(dut.DecodeLastPublishedMessageAs<lcmt_drake_signal>(channel_name), std::runtime_error);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Comment by liangfok** [comment]
@jwnimmer-tri: I addressed your comments. PTAL. Thanks.

---

Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNs_ojEAIQr0Rv0I4:-KaZuF3dJ4H4_9l7gQ3q:b5iajx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should #4731's changes be amended to use this new feature, also?  I guess #4775 isn't merged yet so we can't amend its uses as part of this PR.
</blockquote></details>

Done. I'll also update #4775 if this PR is merged before it. (Or I'll update this PR if #4775 is merged before this one.)

---

*[drake/lcm/drake_mock_lcm.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXLGrCeZ2ei25-CNjA:-KaZlyOT4bCjR47xfiPS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/drake_mock_lcm.h#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think this is a double space after the `&`?
</blockquote></details>

Done.

---

*[drake/lcm/drake_mock_lcm.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXLQDgkNLe6kb5Goji:-KaZm1TsDvMZZUyWu-I2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/drake_mock_lcm.h#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Probably doesn't matter, but consider adding `{}` to initialize the message, in case for some reason the decode doesn't set everything (it should, though).
</blockquote></details>

Done.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNcLrReLnsUql0Egc:-KaZmVgGqmRTNr32oGR1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/test/drake_mock_lcm_test.cc#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `original_` prefix here perhaps doesn't add much, since they are the only bytes in the test? -- we're not doing a readback-to-bytes test.  (Not a defect.)
</blockquote></details>

Done.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXMju9pMencd-tPzWJ:-KaZtawf8bbHNSxIXt_V:bb0g700) ([raw file](https://github.com/robotlocomotion/drake/blob/2f4f3b072f1cda7f93789114ccb1da09d57f4d03/drake/lcm/test/drake_mock_lcm_test.cc#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it would be easy and worthwhile to test that a decoding error throws an exception, since we will be relying on that behavior in unit tests that call this.

```
  dut.Publish(channel_name, &original_message_bytes[0], message_size - 1);
  EXPECT_THROW(dut.DecodeLastPublishedMessageAs<lcmt_drake_signal>(channel_name), std::runtime_error);

  original_message_bytes.push_back(0);
  dut.Publish(channel_name, &original_message_bytes[0], message_size + 1);
  EXPECT_THROW(dut.DecodeLastPublishedMessageAs<lcmt_drake_signal>(channel_name), std::runtime_error);
```
</blockquote></details>

Done. Thanks for the code!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-KaZunjTBQAvEp6Oq7PZ:bmoyi5l)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-Ka_N0uiIbLFiNgYqg2j:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Since Tuesday is the next business day. +@david-german-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-Ka_fA1W8AXuHLoUQP4P:b-e7kwct)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks and is thus ready for review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-KadwPLH5Z6zhAxSPSF0:b-5rq8uy)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-:-Kah-csmmHR2X4_QR-15:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNs_ojEAIQr0Rv0I4:-Kah1Rth_QOSp9-RbD5b:b-c40k6o) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done. I'll also update #4775 if this PR is merged before it. (Or I'll update this PR if #4775 is merged before this one.)
</blockquote></details>

Now that #4775 is merged, I will update `DrakeVisualizer` to also use `DecodeLastPublishedMethodAs<T>()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Comment by liangfok** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNs_ojEAIQr0Rv0I4:-KahCj6PXdwUTvNFZz_m:b-896fix) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Now that #4775 is merged, I will update `DrakeVisualizer` to also use `DecodeLastPublishedMethodAs<T>()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4787#-KaXNs_ojEAIQr0Rv0I4:-KahjBqAi8uyBHM1UlrR:b47li7) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@jwnimmer-tri: PTAL when you get a chance. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4787)*

**Pull request merged**
