### PR TITLE
doc: Add example of searching for commits that modify deprecations

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Split off from #14546 

Relates https://github.com/RobotLocomotion/styleguide/pull/41

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for both reviews, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653#-:-MTffPdD9jI-vRRfcjLG:b-3q8wnk)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[doc/code_review_checklist.rst, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14653#-MTfnsorDD-qDxvH_Wk9:-MTfot5858El2B7Hu62w:bn2uyzz) ([raw file](https://github.com/robotlocomotion/drake/blob/ecff031724c40bcc8035166be5e634d2fe0e05fc/doc/code_review_checklist.rst#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I don't understand how this is an example of a `git diff` search? I tried it and it just provides a long list of commit shas and descriptions, but doesn't show any examples of actual DRAKE_DEPRECATED usage.

Wouldn't an example that shows actual DRAKE_DEPRECATED usage be more helpful to a person who wants to deprecate something?
</blockquote></details>

A pedagogical example is out of scope for this PR; this is only meant to to show people how to easily locate deprecations.

Do you have a better technique?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[doc/code_review_checklist.rst, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14653#-MTfnsorDD-qDxvH_Wk9:-MTfpPAf9PRmQuwFPge0:b1ja88h) ([raw file](https://github.com/robotlocomotion/drake/blob/ecff031724c40bcc8035166be5e634d2fe0e05fc/doc/code_review_checklist.rst#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

A pedagogical example is out of scope for this PR; this is only meant to to show people how to easily locate deprecations.

Do you have a better technique?
</blockquote></details>

Done. Improved wording.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Not seeing yet how these examples are helpful?

How do you independently find examples of prior deprecations, given that we don't have a deprecation playbook? (aside from pinging people like me or Jeremy or whomever)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653#-:-MTfpSwiAu8uQopNsGWK:b-9qnyrw)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Yeah, I agree it's tricky. This does help, so :lgtm: x 2.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14653#-:-MTkpeQk4Ja_3MhQqHx2:b-u4bgrs)* status: needs at least two assigned reviewers

**Pull request merged**
