### PR TITLE
Add CollisionObject for deformable simulation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Create a CollisionObject class that manages the geometric representations of rigid objects that are two-way coupled with deformable objects.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@seancurtis-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091#-:-MadLMlKB2OZbrQHK9l_:b-4269ug)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. For the various suggestions I've made, I'm open to the argument that this code is all intended to be transient -- ultimately, SceneGraph is supposed to own all of this geometry in support of contact queries. That said, we don't have a *plan* or intended timeline for that to happen, so, for the forseeable future, this is where these collision geometries will live -- probably leaving `dev` and entering `fixed_fem` directly some day, and that's what inspired my comments.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091#-:-MadXZJX1Tt5y-23Dz8H:b-fi23ny)* status: 14 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/collision_objects.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadQNLWCp4DMueArhXO:-MadQNLWCp4DMueArhXP:boh5qkp) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L2)):*
> ```objc
> #pragma once
> #include <map>
> ```

nit: One line of whitespace between pragma and include.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadQoR46vnqWgLO-peq:-MadQoR46vnqWgLO-per:b-p1np1o) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L18)):*
> ```objc
> namespace internal {
> /* Representation of a group of rigid collision objects, consisting of their
>  poses in the world, surface meshes and proximity properties. Collision objects
> ```

BTW As an advocate of the [oxford comma](https://en.wikipedia.org/wiki/Serial_comma), I'll mention it here. Feel free to ignore this if it's not to your liking. This note applies to multiple sections in documentation (and error messages).
___
*[multibody/fixed_fem/dev/collision_objects.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRHQj2-SaalgeQXe_:-MadRHQj2-SaalgeQXea:b-tiw5mc) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L40)):*
> ```objc
>       geometry::GeometryId id, const geometry::Shape& shape,
>       const geometry::ProximityProperties& proximity_properties) {
>     DRAKE_DEMAND(rigid_representations_.find(id) ==
> ```

BTW Another common way to spell this is:

```C++
DRAKE_DEMAND(rigid_representations_.count(id) == 0);
```
___
*[multibody/fixed_fem/dev/collision_objects.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadTuml2De6clAvWfab:-MadTuml2De6clAvWfac:b848mo1) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L44)):*
> ```objc
>     ReifyData data{id, proximity_properties};
>     shape.Reify(this, &data);
>     geometry_ids_.emplace_back(id);
> ```

BTW Any reason why adding `id` to `geometry_ids_` and the initial poses don't simply happen in `MakeRigidRepresentation`?
___
*[multibody/fixed_fem/dev/collision_objects.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRndV177DfY2MVg--:-MadRndV177DfY2MVg-0:b-l9pg5v) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L70)):*
> ```objc
>    @pre The geometry with `id` has been registered in `this` CollisionObject
>    with AddCollisionObject(). */
>   const math::RigidTransform<T>& pose(geometry::GeometryId id) const {
> ```

nit: `pose_in_world` would be a less ambiguous name.  (And goes well with `UpdatePoseInWorld()`.)
___
*[multibody/fixed_fem/dev/collision_objects.h, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRzc3Dgl1lyE2SQDf:-MadRzc3Dgl1lyE2SQDg:b-e5wkd1) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L80)):*
> ```objc
>    @pre The geometry with `id` has been registered in `this` CollisionObject
>    with AddCollisionObject(). */
>   void UpdatePoseInWorld(geometry::GeometryId id,
> ```

`pose()` and `UpdatePoseInWorld()` have bodies that are almost indistinguishable from each other, and yet one is named with cameal case and one with snake case. That seems....odd. I'd imagine if one deserved snake case, they both would: e.g., `set_pose_in_world()` would go really well with `pose_in_world()`.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadWhtIDa7ZT6bvinMH:-MadWhtIDa7ZT6bvinMI:b-txywb1) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L94)):*
> ```objc
> 
>  private:
>   friend class CollisionObjectsTest;
> ```

It seems that the sole reason you have this friend delcaration is to access the default resolution hint. If you just make it a public static member, you wouldn't need this at all (and the actual `CollisionObjectsTest` could be entirely contained in an anonymous namespace).
___
*[multibody/fixed_fem/dev/collision_objects.h, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadU6PE6RCq79WeVa7g:-MadU6PE6RCq79WeVa7h:b-ggtpft) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L111)):*
> ```objc
>     RigidRepresentation(std::unique_ptr<geometry::SurfaceMesh<double>> mesh,
>                         const geometry::ProximityProperties& props)
>         : surface_mesh(std::move(mesh)), properties(props) {}
> ```

FYI In the future, I'll be adding a `Bvh<Obb, SurfaceMesh<double>>` to this struct.

Currently, you've got methods mapping `GeometryId` with the various quantities associated (mesh, pose, properties). As this set grows in size, that practice can get overly heavy.

If, instead, you were to simply create the public struct: `CollisionObject` and returned a const reference to one based on `GeometryId`, then a single map look up would be sufficient to acquire all the information we're interested in and the aggregate container doesn't have to change its API to accommodate new, per-collision object quantities.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadT2Kn05iP1AqkAIua:-MadT2Kn05iP1AqkAIub:b-blsuv3) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L115)):*
> ```objc
>      constructed and copy assigned. */
>     copyable_unique_ptr<geometry::SurfaceMesh<double>> surface_mesh;
>     geometry::ProximityProperties properties;
> ```

 Why not include the world pose in this little struct?
___
*[multibody/fixed_fem/dev/collision_objects.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadSqlL3FCdS_PMsB1q:-MadSqlL3FCdS_PMsB1r:b-qp5xr6) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L147)):*
> ```objc
>   /* The default resolution hint for surface mesh representations of the rigid
>    geometries. */
>   double resolution_hint_{0.01};
> ```

As long as this isn't actually *settable* anywhere, you might just go with

`static constexpr double kDefaultResolutionHint{0.01};`
___
*[multibody/fixed_fem/dev/collision_objects.cc, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadTChzCh7LXgryw5OE:-MadTChzCh7LXgryw5OF:b9dp5ak) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.cc#L35)):*
> ```cpp
>       "Trying to make a rigid surface mesh for an unsupported type shape. "
>       "The types supported are: Sphere, Box, Cylinder, Capsule, Ellipsoid, "
>       "Mesh and Convex.");
> ```

nit: This error would be improved with a positive indicator of what shape type was actually given.
___
*[multibody/fixed_fem/dev/collision_objects.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadViil94byUS-5NfYL:-MadViil94byUS-5NfYM:bd4dbti) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.cc#L125)):*
> ```cpp
>   rigid_representations_[data.id] = {
>       std::make_unique<SurfaceMesh<double>>(
>           MakeRigidSurfaceMesh(shape, resolution_hint_)),
> ```

Have you thought about asking the properties for a resolution hint, using your default value as the fallback if none is given. You'd have two options:

1. Piggyback on the hydroelastic resolution hint
    - This gets you up and running immediately.
    - It ties you to hydro
2. Introduce your own expected property
    - This allows you to specify things on a per-geometry basis and can ultimately manifest as its own custom, soft-sim related, parseable property.

I haven't thought a great deal about this, but I'm *really* worried about this fixed resolution hint for arbitrarily sized geometries. :-O  Even if only as surface meshes.

Alternatively, you might consider having a function for resolution hint that depends on the measure/curvature of the geometry in question.
___
*[multibody/fixed_fem/dev/test/collision_objects_test.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadWzQmAPdCPWuDsmQm:-MadWzQmAPdCPWuDsmQn:b-ikzads) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/collision_objects_test.cc#L65)):*
> ```cpp
> namespace {
> TEST_F(CollisionObjectsTest, AddSphere) {
>   GeometryId id = GeometryId::get_new_id();
> ```

nit (meta) I'd salt this file up with a bunch of `const` declarations - ids, shapes, etc.
___
*[multibody/fixed_fem/dev/test/collision_objects_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadXTx84jFDgSmOB0pT:-MadXTx84jFDgSmOB0pU:b2hjdda) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/collision_objects_test.cc#L158)):*
> ```cpp
>   const auto identity = math::RigidTransform<double>();
>   EXPECT_TRUE(collision_objects_.pose(id).IsExactlyEqualTo(identity));
>   math::RigidTransform<double> arbitrary_pose(Vector3<double>(1., 2., 3.));
> ```

nit: Humor me and put in a non-Identity rotation as well. :)
___
*[multibody/fixed_fem/dev/test/non_convex_mesh.obj, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadUpqh9MFhjh6nZlqk:-MadUpqh9MFhjh6nZlql:by7keb5) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/non_convex_mesh.obj#L0)):*
These are files taken from geometry tests. All things being equal, it would be nice if we didn't duplicate.

Have you considered depending on `//geometry:test_obj_files` in your test?

**Review by xuchenhan-tri — COMMENTED** [review]
Addressed the comments, PTAL, thanks. (If only all reviews come as fast as this one :))

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091#-:-Madf27m4BiMWdeKfb5f:b-dm3uls)* status: 10 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[multibody/fixed_fem/dev/collision_objects.h, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadQoR46vnqWgLO-peq:-MadZHjbEoCQx_OGvDDC:byiqbwu) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As an advocate of the [oxford comma](https://en.wikipedia.org/wiki/Serial_comma), I'll mention it here. Feel free to ignore this if it's not to your liking. This note applies to multiple sections in documentation (and error messages).
</blockquote></details>

Huh, didn't know this. (I think) I was taught that ", and" is only used to connect two sentences.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRHQj2-SaalgeQXe_:-MadZXy_0SjJW6zriY0P:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L40)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Another common way to spell this is:

```C++
DRAKE_DEMAND(rigid_representations_.count(id) == 0);
```

</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadTuml2De6clAvWfab:-MadpWJR18byc8OVAjs0:b-cg26lg) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L44)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Any reason why adding `id` to `geometry_ids_` and the initial poses don't simply happen in `MakeRigidRepresentation`?
</blockquote></details>

This happened when I used this class, got a segfault, realized that ids are not added, stuffed it in while I was debugging, and then forgot all about it.

Fixed.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRndV177DfY2MVg--:-MadZggE1Re6rZ02ls5D:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L70)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: `pose_in_world` would be a less ambiguous name.  (And goes well with `UpdatePoseInWorld()`.)
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadRzc3Dgl1lyE2SQDf:-Mad_3Yy99AmJgn7WdS9:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L80)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

`pose()` and `UpdatePoseInWorld()` have bodies that are almost indistinguishable from each other, and yet one is named with cameal case and one with snake case. That seems....odd. I'd imagine if one deserved snake case, they both would: e.g., `set_pose_in_world()` would go really well with `pose_in_world()`.
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadWhtIDa7ZT6bvinMH:-MadfPui6IIla-IzsRxu:b-t5xuk4) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L94)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It seems that the sole reason you have this friend delcaration is to access the default resolution hint. If you just make it a public static member, you wouldn't need this at all (and the actual `CollisionObjectsTest` could be entirely contained in an anonymous namespace).
</blockquote></details>

Yes you are right. Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadU6PE6RCq79WeVa7g:-Madutiu53dLtc2Bo8rM:bs7xv4f) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L111)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI In the future, I'll be adding a `Bvh<Obb, SurfaceMesh<double>>` to this struct.

Currently, you've got methods mapping `GeometryId` with the various quantities associated (mesh, pose, properties). As this set grows in size, that practice can get overly heavy.

If, instead, you were to simply create the public struct: `CollisionObject` and returned a const reference to one based on `GeometryId`, then a single map look up would be sufficient to acquire all the information we're interested in and the aggregate container doesn't have to change its API to accommodate new, per-collision object quantities.
</blockquote></details>

I don't quite see this a huge issue.

1. I don't foresee too many other quantities to be added to this class. Is there anything else after bvh? And when that actually does happen, will this class still be in existence?
2. I like the nice syntax of `collision_objects.pose_in_world(id)`. If we were to keep this, the APIs have to be there anyway.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadT2Kn05iP1AqkAIua:-MadvkHFEuuD9RFcVDE4:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

 Why not include the world pose in this little struct?
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadSqlL3FCdS_PMsB1q:-MadfW5143g4etW9YMhl:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L147)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As long as this isn't actually *settable* anywhere, you might just go with

`static constexpr double kDefaultResolutionHint{0.01};`
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.cc, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadTChzCh7LXgryw5OE:-Madj4sN0WZCqy0Bd2b8:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.cc#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This error would be improved with a positive indicator of what shape type was actually given.
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/collision_objects.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadViil94byUS-5NfYL:-Mad_b-tDdiE5PbARajj:bm6acjl) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.cc#L125)):*
I considered both options you proposed and didn't like either.

1. I don't want to be tied to hydroelastics.
2. That seems like quite a bit of work and I was hoping that the geometry team would take care of it once scene graph takes control. In particular, this probably would require additional properties/tags on the sdf files if we want to just parse a robot and have it interact with something deformable.

> Alternatively, you might consider having a function for resolution hint that depends on the measure/curvature of the geometry in question.

This seems like a easier path, but probably not the best for a long term solution because in the end the resolution is still arbitrary and dictated by what **I** think is the best. I put down a TODO for this that I'll address soon.  Also, I'll have to pick your brain on how to determine the measure of a convex/mesh object. 
IMO, the best long term solution this your second proposed bullet point. 

BTW, in my demos, I was careful to avoid any rigid geometries that's not a box :).
___
*[multibody/fixed_fem/dev/test/collision_objects_test.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadWzQmAPdCPWuDsmQm:-MadcZAU5AoczGJzeid8:bv8ptf8) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/collision_objects_test.cc#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit (meta) I'd salt this file up with a bunch of `const` declarations - ids, shapes, etc.
</blockquote></details>

Salted, PTAL, thanks.
___
*[multibody/fixed_fem/dev/test/collision_objects_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadXTx84jFDgSmOB0pT:-Madeqys5t4ces_QV2vN:b-xr3xov) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/collision_objects_test.cc#L158)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Humor me and put in a non-Identity rotation as well. :)
</blockquote></details>

If it humors you, then sure. Done :).
___
*[multibody/fixed_fem/dev/test/non_convex_mesh.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadUpqh9MFhjh6nZlqk:-MaddyjX4kuPu7xwxSjd:b2ru4ii) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/non_convex_mesh.obj#L)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

These are files taken from geometry tests. All things being equal, it would be nice if we didn't duplicate.

Have you considered depending on `//geometry:test_obj_files` in your test?
</blockquote></details>

I tried that but didn't work. Figured it's not worth scratching my head over it for something to be deleted anyway. But still, it'd be nice to know 1. why it doesn't work and 2. what's the trick to let bazel see the data files declared in another package. Do you know off the top of your head?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Two small things left.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091#-:-Mae3OU0CIlOP-K8Es54:bwjwdcu)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/collision_objects.h, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadU6PE6RCq79WeVa7g:-Mae0PCo7RzjJ5h3LbW_:b-s58kw9) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.h#L111)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't quite see this a huge issue.

1. I don't foresee too many other quantities to be added to this class. Is there anything else after bvh? And when that actually does happen, will this class still be in existence?
2. I like the nice syntax of `collision_objects.pose_in_world(id)`. If we were to keep this, the APIs have to be there anyway.
</blockquote></details>

Not a huge issue. And I labeled this as FYI, so no action is required.

The *primary* benefit was resolved by eliminating the `poses` map (fewer maps and keys to coordinate).
___
*[multibody/fixed_fem/dev/collision_objects.h, line 121 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15091#-Mae0mZBAqEWb9dSEy3X:-Mae0mZBAqEWb9dSEy3Y:bk9htp1) ([raw file](https://github.com/robotlocomotion/drake/blob/dcab0bf55b08a9ccffcff9cf4bf87d776c408147/multibody/fixed_fem/dev/collision_objects.h#L121)):*
> ```objc
>     copyable_unique_ptr<geometry::SurfaceMesh<double>> surface_mesh;
>     geometry::ProximityProperties properties;
>     math::RigidTransform<T> pose_in_world{};
> ```

nit: No `{}`. Only for POD (plain old data).
___
*[multibody/fixed_fem/dev/collision_objects.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadViil94byUS-5NfYL:-Mae12Kc26vms-3xQE3a:b-nj2zgy) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/collision_objects.cc#L125)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I considered both options you proposed and didn't like either.

1. I don't want to be tied to hydroelastics.
2. That seems like quite a bit of work and I was hoping that the geometry team would take care of it once scene graph takes control. In particular, this probably would require additional properties/tags on the sdf files if we want to just parse a robot and have it interact with something deformable.

> Alternatively, you might consider having a function for resolution hint that depends on the measure/curvature of the geometry in question.

This seems like a easier path, but probably not the best for a long term solution because in the end the resolution is still arbitrary and dictated by what **I** think is the best. I put down a TODO for this that I'll address soon.  Also, I'll have to pick your brain on how to determine the measure of a convex/mesh object. 
IMO, the best long term solution this your second proposed bullet point. 

BTW, in my demos, I was careful to avoid any rigid geometries that's not a box :).
</blockquote></details>

Option 2 will eventually have to happen. Someone is going to have to say, "I have a sphere that's going to bang into some soft sim and it needs to be turned into a mesh, I care about what that tessellation looks like". That said, we can defer that conversation.
___
*[multibody/fixed_fem/dev/test/non_convex_mesh.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadUpqh9MFhjh6nZlqk:-Mae1nzXArVXkaFz4ydq:b-w3umeu) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/non_convex_mesh.obj#L)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I tried that but didn't work. Figured it's not worth scratching my head over it for something to be deleted anyway. But still, it'd be nice to know 1. why it doesn't work and 2. what's the trick to let bazel see the data files declared in another package. Do you know off the top of your head? 
</blockquote></details>

Worked for me:

The build looks like:

```py
drake_cc_googletest(
    name = "collision_objects_test",
    data = ["//geometry:test_obj_files"],
    deps = [
        ":collision_objects",
        "//common:find_resource",
        "//common/test_utilities:expect_throws_message",
    ],
)
```

And then you have to change the paths in your test:

```c++
  const Convex convex{drake::FindResourceOrThrow(
      "drake/geometry/test/quad_cube.obj")};
  const Mesh mesh{drake::FindResourceOrThrow(
      "drake/geometry/test/non_convex_mesh.obj")};
```

Probably better to make the change now -- it's easy to forget to de-duplicate later.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[multibody/fixed_fem/dev/collision_objects.h, line 121 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15091#-Mae0mZBAqEWb9dSEy3X:-Mae8LyL1Znpo41z4Kzx:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/dcab0bf55b08a9ccffcff9cf4bf87d776c408147/multibody/fixed_fem/dev/collision_objects.h#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: No `{}`. Only for POD (plain old data).
</blockquote></details>

Done, thanks.
___
*[multibody/fixed_fem/dev/test/non_convex_mesh.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadUpqh9MFhjh6nZlqk:-Mae8w-W8Hn-QytzeWvV:bzcc729) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/non_convex_mesh.obj#L)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Worked for me:

The build looks like:

```py
drake_cc_googletest(
    name = "collision_objects_test",
    data = ["//geometry:test_obj_files"],
    deps = [
        ":collision_objects",
        "//common:find_resource",
        "//common/test_utilities:expect_throws_message",
    ],
)
```

And then you have to change the paths in your test:

```c++
  const Convex convex{drake::FindResourceOrThrow(
      "drake/geometry/test/quad_cube.obj")};
  const Mesh mesh{drake::FindResourceOrThrow(
      "drake/geometry/test/non_convex_mesh.obj")};
```

Probably better to make the change now -- it's easy to forget to de-duplicate later.
</blockquote></details>

Yes this works, thanks. Not sure what I did wrong the first time around. This looks like the first thing one would try...

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15091#-:-MaeAOGzB3xu0NMUakc9:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform), exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/non_convex_mesh.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/15091#-MadUpqh9MFhjh6nZlqk:-MaeABmJ0OjHSapfYBr5:bgrsds9) ([raw file](https://github.com/robotlocomotion/drake/blob/bfbb786b72367d23216cb7dda65457b8ac9d7baa/multibody/fixed_fem/dev/test/non_convex_mesh.obj#L)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes this works, thanks. Not sure what I did wrong the first time around. This looks like the first thing one would try...
</blockquote></details>

You know how it is. You make two changes, a typo in one can mess you up when you become fixated at the *other* change.  :) Happens to me all the time.

**Pull request merged**
