### PR TITLE
Do not create empty.cc files on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
Bazel deals with empty `srcs` for us now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8132)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
:lgtm:

+@ggould-tri for platform-review, please.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8132#-:-L5tfUkgcQyc8De15ory:b-pah3al)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8132#-:-L5tmdptkiQMArDdKutX:bnfp4nl)*

**Pull request merged**
