### PR TITLE
Modified to specify simulation start time as a constant.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2453) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by liangfok** [comment]
Suggest: +@jwnimmer-tri for both feature and platform review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Modified to specify simulation start time as a constant\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2453#-:-KIdhMEsG3n-Y1wv9gzJ:-600605359)*

**Comment by jwnimmer-tri** [comment]
:lgtm: for both reviews.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Suggest: +@jwnimmer-tri for both feature and platform review.
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2453#-:-KIe02Ye_C4ybZvOpi06:-1805360500)*

**Comment by jwnimmer-tri** [comment]
@liangfok github says there are some merge conflicts to resolve.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2453)*

**Comment by liangfok** [comment]
+@jwnimmer-tri since I believe the merge conflicts are now resolved. (I didn't actually resolve any conflicts, just merged in the latest from master.)

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @liangfok github says there are some merge conflicts to resolve.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2453#-:-KIe1fpxamRhUiRM9Leb:1828638501)*

**Comment by jwnimmer-tri** [comment]
Merge commit passed on linux-clang; using override-merge so we don't have to wait for all the builders.  Also, cpplint builder flaked.

**Pull request merged**
