### PR TITLE
pydrake: Expose pybind11 version information

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Addresses part (b) of #7856, supersedes #8107.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8118)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8118#-:-L5pD019cF_1MXopIO6a:b-3u0d0w)*

**Comment by jwnimmer-tri** [comment]
The new `write_file.bzl` and the pre-existing `tools/workspace/generate_file.bzl` probably need some de-duplication.

**Comment by EricCousineau-TRI** [comment]
Done. Keeping `generate_file` where it is for now, can move it later if need be.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8118#-:-L5pJNEqQgrXyGuPINRq:b-kulq3h)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/test/pybind11_version_test.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8118#-L5pMLKKdOa94_Gi2ABu:-L5pMLKKdOa94_Gi2ABv:bi2ya93) ([raw file](https://github.com/robotlocomotion/drake/blob/c315cd5ae3f5263afc30023706ec1578d6a4ccf0/bindings/pydrake/util/test/pybind11_version_test.py#L7)):*
> ```Python
> from __future__ import print_function
> 
> import pydrake.util.pybind11_version as mut
> ```

BTW Not a great fan of `mut`, the meaning is not obvious without some thought, but I guess it is convention here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8118#-:-L5pLwfMwhqlnt3PeLU3:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/test/pybind11_version_test.py, line 7 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118#-L5pMLKKdOa94_Gi2ABu:-L5pOax72Tsp6vjT9JsC:br3gha7) ([raw file](https://github.com/robotlocomotion/drake/blob/c315cd5ae3f5263afc30023706ec1578d6a4ccf0/bindings/pydrake/util/test/pybind11_version_test.py#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Not a great fan of `mut`, the meaning is not obvious without some thought, but I guess it is convention here.
</blockquote></details>

OK I'd prefer to keep it for now, but will take note. Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118#-:-L5pOhYlBYhegP6AE-_l:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8118#-:-L5pRATRMDLgZ3PStpRl:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[bindings/pydrake/util/BUILD.bazel, line 146 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118#-L5phUeo07IMsskPAbed:-L5phUeo07IMsskPAbee:b72dvgi) ([raw file](https://github.com/robotlocomotion/drake/blob/281b9178d23980f0b079f7a254f747c4252ab9b1/bindings/pydrake/util/BUILD.bazel#L146)):*
> ```Python
>     name = "pybind11_version_py",
>     srcs = ["pybind11_version.py"],
>     # `ctx.actions.write` will always produce an exectuable file, regardless of
> ```

FYI @jwnimmer-tri  Can I ask what you'd like to do here? Just always `nolint` any generated `py` files?
I checked `genfiles`, and *all* generated files are executable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/BUILD.bazel, line 146 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118#-L5phUeo07IMsskPAbed:-L5phf4l19PBYE44eDlN:b-pri5fz) ([raw file](https://github.com/robotlocomotion/drake/blob/281b9178d23980f0b079f7a254f747c4252ab9b1/bindings/pydrake/util/BUILD.bazel#L146)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI @jwnimmer-tri  Can I ask what you'd like to do here? Just always `nolint` any generated `py` files?
I checked `genfiles`, and *all* generated files are executable.
</blockquote></details>

Er, that was grammatically unclear: "Should we always add `tags = ["nolint"]` for any generated `py` files?"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118)*

**Comment by jwnimmer-tri** [comment]
*[bindings/pydrake/util/BUILD.bazel, line 146 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118#-L5phUeo07IMsskPAbed:-L5pj6vT6rwhQr242rm5:bmo3x4v) ([raw file](https://github.com/robotlocomotion/drake/blob/281b9178d23980f0b079f7a254f747c4252ab9b1/bindings/pydrake/util/BUILD.bazel#L146)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, that was grammatically unclear: "Should we always add `tags = ["nolint"]` for any generated `py` files?"
</blockquote></details>

OK Yeah, genfiles are always executable for some reason.  Adding nolint is fine.  (The longer term game, which also applies to cxx files, is to teach the linter that things in genfules shouldn't have the shebang check applied.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8118)*

**Pull request merged**
