### PR TITLE
Enforce the invariant the that RigidBodyTree is a proper path

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
At the conclusion of RigidBodyTree::compile (after all structural changes
are affected), the RBT evaluates all the bodies and confirms that there
is a kinetic path from each body to the world.  See issue #3293.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4632)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@jwnimmer-tri for platform review +@sherm1 for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_6gqd3ZSGBell5EjYz:b-q1k2xz)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri Out of time for this week.  Over to +@ggould-tri who is on-call for the next two days, so can iterate on this.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_6hMfWK3MvUVGGdS5r:bookpth)*

**Comment by sherm1** [comment]
CI failed. Nice error message though:
```
C++ exception with description "ERROR: RigidBodyTree::TestConnectedToWorld(): 
Rigid body "body1" in model robot1 has no joint!" thrown in the test body.
```

**Comment by sherm1** [comment]
:lgtm:, pending CI fix and a few BTWs below.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 1065 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6uIN5CZGzvbHgwAYB:-K_6uIN5CZGzvbHgwAYC:b-5xuec9) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.cc#L1065)):*
> ```cpp
>                                             std::set<int>* connected) const {
>   int id = body.get_body_index();
>   if (id != 0) {  // The world node is connected by definition.
> ```

BTW, you could avoid this special case since you inserted 0 in the bodies_with_paths set already. The method documentation should add that as a requirement for the initial value of `connected` in that case.

---

*[drake/multibody/rigid_body_tree.cc, line 1081 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6urSHVtPZK1Ed9aZj:-K_6urSHVtPZK1Ed9aZk:bc6al3x) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.cc#L1081)):*
> ```cpp
>       const RigidBody<T>* parent = body.get_parent();
>       if (parent == nullptr) {
>         // We know this is *not* the world node because the id is not zero.
> ```

BTW, `// ... because it was not already in the connected set.` (if you make the above change)

---

*[drake/multibody/rigid_body_tree.h, line 1219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6tYRf_E-VsLIBkAuU:-K_6tYRf_E-VsLIBkAuV:b-ewrxf) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.h#L1219)):*
> ```objc
>   void updateCompositeRigidBodyInertias(KinematicsCache<Scalar>& cache) const;
> 
>   // Examines the state of the tree, and confirms that all nodes (i.e,,
> ```

BTW, extra comma.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6qPiZBLsyTLkuNtpJ:-K_6qPiZBLsyTLkuNtpK:b-gxawl) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L23)):*
> ```cpp
> // back to the world.
> 
> RigidBody<double>* MakeBody(int id, RigidBody<double>* parent) {
> ```

BTW, have MakeBody return a unique_ptr to reduce repetition below. Also generally good hygiene not to handle filthy raw pointers!

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6sEOod7WyKgAmi--7:-K_6sEOpUtKaKTXBEhph:b-d1p315) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L77)):*
> ```cpp
>         "ERROR: RigidBodyTree::TestConnectedToWorld(): Rigid body \"body4\" in "
>         "model robot is not connected to the world!";
>     ASSERT_EQ(e.what(), msg);
> ```

BTW, should use `EXPECT_EQ` so test can continue after failure. The `ASSERT` versions are use when there is no point in going further, like a pointer should have been nonnull but wasn't and the rest of the tests were going to dereference it.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6sby25pBXzTsIYXvQ:-K_6sby25pBXzTsIYXvR:bc6cd8l) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L111)):*
> ```cpp
>     std::string msg =
>         "ERROR: RigidBody<T>::getJoint(): Rigid body \"body3\" in "
>             "model robot does not have a joint!";
> ```

BTW, these tests with literal error string seem brittle. Do you really need to test that vs. just that an exception gets thrown?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_6vQ76z1VpzeHJJDsq:b-v233g8)*

**Comment by ggould-tri** [comment]
I will platform review this once it is passing CI.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_AAKhxuOU-sd7GqPgv:b-132ak2)*

**Comment by SeanCurtis-TRI** [comment]
Sorry about the CI gaff.  Corrected.  PTAL.  Commits have been curated.

---

Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 1065 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6uIN5CZGzvbHgwAYB:-K_AEKUzbG2nFsJo4LMd:b-owfxsg) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.cc#L1065)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, you could avoid this special case since you inserted 0 in the bodies_with_paths set already. The method documentation should add that as a requirement for the initial value of `connected` in that case.
</blockquote></details>

BTW I like that.  Thanks.

---

*[drake/multibody/rigid_body_tree.cc, line 1081 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6urSHVtPZK1Ed9aZj:-K_AEmTIZWhtEf1dkgOR:bd4vjxe) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.cc#L1081)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, `// ... because it was not already in the connected set.` (if you make the above change)
</blockquote></details>

BTW Yep.  Done.

---

*[drake/multibody/rigid_body_tree.h, line 1219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6tYRf_E-VsLIBkAuU:-K_AEqfC3NMMBYzzkvcQ:bgrrpfm) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/rigid_body_tree.h#L1219)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, extra comma.
</blockquote></details>

BTW done

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6qPiZBLsyTLkuNtpJ:-K_AFlt8fhml_UCrECvQ:bgr79uq) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, have MakeBody return a unique_ptr to reduce repetition below. Also generally good hygiene not to handle filthy raw pointers!
</blockquote></details>

BTW Done

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6sEOod7WyKgAmi--7:-K_AFpfAqJqM3KE7q7aE:beh0l0k) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L77)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, should use `EXPECT_EQ` so test can continue after failure. The `ASSERT` versions are use when there is no point in going further, like a pointer should have been nonnull but wasn't and the rest of the tests were going to dereference it.
</blockquote></details>

BTW Well, technically, this is the last thing.  There is no "continuing".  I thought picking `ASSERT_EQ` in place of `EXPECT_EQ` would communicate that unambiguously.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_6sby25pBXzTsIYXvQ:-K_AG70rlsFlfb6SjVTf:bdw7fwf) ([raw file](https://github.com/robotlocomotion/drake/blob/007de6ca73c370c640ad556685fc6fa8c753bb10/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L111)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, these tests with literal error string seem brittle. Do you really need to test that vs. just that an exception gets thrown?
</blockquote></details>

BTW I did put an explicit note about that.  I didn't want to simply test that an exception gets thrown; I also wanted to assert what the message is.  Over the years, I've seen exceptions copied and pasted such that the wrong message gets "thrown".  When that happens, it's better to have no message at all than the wrong message.  So, I figure, if the exception is going to pretend to "explain" the error, then that should be tested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_AGQnmo1IJ72JopPPv:bfnczqq)*

**Comment by SeanCurtis-TRI** [comment]
FTR I shouldn't have curated the commits...that made reviewable very cranky and lost the previous conversations.  Good to know.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_AHWPQKQodPsTo1bqa:b-e49k6t)*

**Comment by ggould-tri** [comment]
:lgtm: with two comment items to resolve below.

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body.h, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_AJNNnKvANeHxKHXBx:-K_AJNNoJqkogEttSQj_:b8cy5ta) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/rigid_body.h#L103)):*
> ```objc
> 
>   /**
>    * Reports if the body has a joint.
> ```

The joint referred to by `joint_` is called the "parent joint" elsewhere in this file's doxygen.  Consider using the same term here for consistency.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_ALIyG4ywcu5ivTK-5:-K_ALIyG4ywcu5ivTK-6:bqfblg7) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L137)):*
> ```cpp
>   // Using try/catch to test the exception message, confirming that the right
>   // information is being returned about the error.
>   // NOTE: This error message arises from the
> ```

...
...
The suspense is killing me!  Tell me how it all turns out!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_ALWfjmJjSQFhV2uB8:br5jwhi)*

**Comment by SeanCurtis-TRI** [comment]
Resolved.  PTAL

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body.h, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_AJNNnKvANeHxKHXBx:-K_ALq5b1TBCyZ_rIu2L:bgrrpfm) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/rigid_body.h#L103)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The joint referred to by `joint_` is called the "parent joint" elsewhere in this file's doxygen.  Consider using the same term here for consistency.
</blockquote></details>

BTW done

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_ALIyG4ywcu5ivTK-5:-K_AMLq4E5QO3Tsugz2z:bbn4jbu) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L137)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

...
...
The suspense is killing me!  Tell me how it all turns out!
</blockquote></details>

Done I think you'll only be disappointed by the ending.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-:-K_AMWf4FVxzhYbsvis6:b-2sxv4w)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_ALIyG4ywcu5ivTK-5:-K_ANGsDFWuTHpPYQ0Oe:b-f3l63w) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L137)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done I think you'll only be disappointed by the ending.
</blockquote></details>

Well, that's today's media for you.  All hype, but in the end if you've seen the trailer you can skip the event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4632#-K_ALIyG4ywcu5ivTK-5:-K_APxfHO8HkqL4Tzckf:b77hjc9) ([raw file](https://github.com/robotlocomotion/drake/blob/e76c536d4757863d3760147f417a9b09b09d37f0/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L137)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Well, that's today's media for you.  All hype, but in the end if you've seen the trailer you can skip the event.
</blockquote></details>

Exactly.  And Han shot first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4632)*

**Pull request merged**
