### PR TITLE
Removes Parser Logic From RigidBodyTree

### PR DESCRIPTION
**Pull request by liangfok**
This extracts from #4363 the changes to `RigidBodyTree`. It removes the parsing code from RigidBodyTree, which paves the way for moving the parsers into their own libraries, which will be done in a subsequent PR. This subsequent PR wil also move the parsers into their own directories per #4091.

I'm labeling this high priority because being able to decouple the parsers from the `RigidBodyTree` will enable @amcastro-tri to make faster progress renovating the `RigidBodyTree`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4386)

### CODE REVIEW

**Comment by liangfok** [comment]
I am going to apply the "do not merge" tag until after https://github.com/RobotLocomotion/director/pull/395 is merged and this PR is updated to point to the updated `RobotLocmotion/director`.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please.

**Comment by amcastro-tri** [comment]
Excellent! thank you @liangfok. Super happy to see these finally gone! :lgtm_strong: 

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitmodules, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4386#-KYJhp4j-zxZFmafZw7-:-KYJhp4jBB2gXQcg3W-L:bx5vy6c) ([raw file](https://github.com/robotlocomotion/drake/blob/78fef9c2a3553f6013120ef4d7ba6301c8e4e69e/.gitmodules#L21)):*
> ```
> [submodule "externals/director"]
> 	path = externals/director
> 	url = https://github.com/liangfok/director.git
> ```

This is just a reminder for myself to check it went back to normal before merging.

---

*[drake/multibody/rigid_body_tree.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4386#-KYJfSFYEXYy8NbgbHY6:-KYJfSFY77yPwpfyHmUC:b-4v4hbk) ([raw file](https://github.com/robotlocomotion/drake/blob/7c98d276ac8f3bce378a25b46a5b6f6fdb658961/drake/multibody/rigid_body_tree.cc#L25)):*
> ```cpp
> // TODO(liang.fok) Remove the following include once this file no longer
> // references `PackageMap`.
> #include "drake/multibody/xml_util.h"
> ```

BTW, nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4386#-:-KYJhbGc5OvHoxSWhX1R:bjs6zyb)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4386)*

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks and is thus ready for platform review.

**Comment by david-german-tri** [comment]
:lgtm: :confetti_ball: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4386#-:-KYLAqzvBtZ5WQSSQmp2:b-ljs6xb)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4386)*

**Pull request merged**
