### PR TITLE
dev rgbd_camera: Update docs to be more concise about coordinates

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per f2f with @thduynguyen

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11337)

### CODE REVIEW

**Comment by sherm1** [comment]
Wow! Awesome terminology treatise, @thduynguyen. Thanks!

**Comment by EricCousineau-TRI** [comment]
May update this pending discussion in dev-merge process:
https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc5gvl3ARaxUPfZOiR:-Lgc5gvm3Qga4pDVPRan:bywwayl

**Comment by EricCousineau-TRI** [comment]
I have a draft against Sean's PR that incorporates this and some of the above feedback:
https://github.com/SeanCurtis-TRI/drake/pull/5

Some notes:
- Some of the discussion points above disappear with Duy's treatise (I think) - yay!
- My current wording is very rough; I'd like to get high-level stuff before digging into grammar etc.

I am going to close this PR in lieu of continuing discussion in this meta-PR. If that discussion gets too complicated, then it gets deferred and the original PR lands.

---

@thduynguyen Some minor notes:

Some of your definitions seem to conflict with stated assumptions; e.g. you mention that "image coordinate systems" are 2D, but then go only to mention `(X, Y, Z)` as coordinates.
Additionally, you state that "image frame" is meaningless, but state that "frame" is defined a coordinate system, and give a meaningful definition to "image coordinate system".

You also state:
> We also don't need to redefine standard terms in the doc. For example, we don't need to invent "optical coordinate system" [...]

I take that to mean we shouldn't try inventing *new* terms; however, I would still like to define terms for some level of clarification (even if we refer to the Wikipedia article for more discussion).

My proposal is as follows:
- "image frame" is the same as the "camera frame", assuming that "image frame" is actually 3D
- I will add a lightweight clarification of terms (when appropriate)

I've tried to do this in the meta-PR.

**Comment by EricCousineau-TRI** [comment]
Per f2f with @SeanCurtis-TRI, @thduynguyen, @kunimatsu-tri on Wed (07/10):

* In our case, the image plane is "in front" of the aperature (like OpenCV), rather than behind + reversed (like WIkipedia article).
* Basic taxonomy:
    * sensor: measures the world
        * imager: measurement as image
            * camera: uses lens & image plane to make image
        * image: array of measurements
            * pixel coordinates `u, v`, in units of `px`
* Camera intrinsics defined by
    * image size `w, h`, units of `px`
    * focal length `fx, fy`, units of `px / (m/m)`
    * principal point, `cx, cy`, where the "viewing ray" intersects image
    plane, units of `px`
* Camera extrinsics defind by frame `C`
    * `Co` is aperature, per pin hole camera model
    * `Cz` directed along viewing ray (from aperature towards "scene" that the
    camera captures)
    * `Cx` along the `u` direction of image
    * `Cy` along the `v` direction of image

Some definitions are missing here, but will try to incorporate in superseding
PRs.

**Comment by EricCousineau-TRI** [comment]
Er, forgot what we had decided on "image frame". I think we mentioned that 2D image frame vs. 3D image frame might be hard to distinguish / describe in prose.

Also, we should avoid using the term "normalized coordinates", as it's ambiguous as to whether it means coordinates on `[-1, 1]` rather than `[0, w] | [0, h]`, or if it implies `x' = X / Z, y' = Y / Z`...

**Pull request closed without merging**
