### PR TITLE
Refactory installer.py

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Refactor the install helper script to encapsulate state information in a class instance. Mostly, this allows us to remove the ugly hack in the unit test which imports the installer and uses it multiple times.

While we're at it, simplify the implementation of `_may_be_binary`.

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17794)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: thanks for humoring me :)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17794#-:-NAjL9BS50PmnWgGh7nI:b8revv9)* status: needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17794)* status: needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
+@EricCousineau-TRI for platform review, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, nice!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17794#-:-NAkSulHBYoM3Mgzu985:by8c39b)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
