### PR TITLE
Clarify the policy on directories that are exempt from platform review.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for initial feature review, since I'm told you have a different opinion.

cc @maddog-tri FYI.

This PR will ultimately require Russ approval.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5050)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5050#-Kc6FY95pnNsH4IqleQ0:-Kc6FY95pnNsH4IqleQ1:b-poqhef) ([raw file](https://github.com/robotlocomotion/drake/blob/87427a2745f39541865fc7b9636118e56f646bb1/drake/doc/developers.rst#L179)):*
> ```reStructuredText
> All directories named ``dev`` are exempt from platform review, as are certain
> other directories, as documented in their ``README`` files.  If a pull request
> only modifies files in exempt directories, no platform review is required.
> ```

BTW, consider clarifying that while no platform review is required in this case,  either a platform reviewer must perform the merge, or LGTM the PR so that the author can perform the merge.

---

*[drake/doc/developers.rst, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5050#-Kc6GHMzxaz3t_nNqKjA:-Kc6GHMzxaz3t_nNqKjB:b-d431v5) ([raw file](https://github.com/robotlocomotion/drake/blob/87427a2745f39541865fc7b9636118e56f646bb1/drake/doc/developers.rst#L181)):*
> ```reStructuredText
> only modifies files in exempt directories, no platform review is required.
> However, other Drake contributors are free to merge PRs that break exempt
> directories, simply by removing the broken targets from the build. Therefore,
> ```

BTW, "other Drake contributors are free to merge PRs" implies that anyone can perform the merge. However isn't it true that a PR can only be merged by a platform reviewer or by a non-platform reviewer after it has been LGTM'ed by a platform reviewer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5050)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5050)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5050#-Kc6GHMzxaz3t_nNqKjA:-Kc6GwNGjgf77_qndDKi:bz667h5) ([raw file](https://github.com/robotlocomotion/drake/blob/87427a2745f39541865fc7b9636118e56f646bb1/drake/doc/developers.rst#L181)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "other Drake contributors are free to merge PRs" implies that anyone can perform the merge. However isn't it true that a PR can only be merged by a platform reviewer or by a non-platform reviewer after it has been LGTM'ed by a platform reviewer?
</blockquote></details>

Consider adding "(after the normal PR vetting process)" after "directories".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5050)*

**Comment by RussTedrake** [comment]
This is already documented here:
http://drake.mit.edu/directory_structure.html?highlight=dev
and I prefer the rules in the existing documentation (with the 24 hour rule), but am happy to discuss.

**Comment by david-german-tri** [comment]
> This is already documented here:

Oh, so it is.  Closing.

**Comment by jwnimmer-tri** [comment]
FTR, I agree with the pre-existing write-up and I apologize @maddog-tri if I was unclear in the rules when I suggested that you use the `dev` directory for the demo code.

**Comment by maddog-tri** [comment]
(Late to my own party... but if I consolidate the empties, maybe I'll get a whole bottle out of this anyhow.)

It's nice that the policy is already documented, albeit unfindably so.  However, I am still confused as to what it means.

>  "All code that implements core functionality in Drake must adhere to the strict code standards described in Developer Notes, and must have unit test coverage via code implemented in a test subdirectory immediately below the core implementation."

Ok, that I understand:  the baseline is strict adherence to code standards along with unit-tests.

>  "To promote rapid development of research ideas within the code base, we allow for some exceptions to this rule for experimental code."

Ok, we are going to allow for some exceptions to the baseline....

>  "This includes any subdirectory labeled dev and directories with a special README.md file describing the protocol for that directory."

Ok, the exceptions will apply to `dev` directories and specially documented directories....

>  "For PRs that affect only these experimental directories, one feature review is sufficient; platform review is not required.  If build or test targets in these directories break, and the PR author or on-call build cop cannot trivially resolve them, a GitHub issue will be assigned to the author of the code. If the issue is not resolved within 24 hours, the core development team may disable the offending targets."

Ok, only one feature review and no platform review is required.  And anyone is allowed to break/disable the code in such directories.

What about the exceptions?  Is the intended meaning "Neither strict adherence to the code standards, nor unit-tests, are required for code in such directories."?  And then, is the role of the Feature Review "inspecting for bugs, and for alignment with the team's goals" --- but not "for test coverage", and not "striv(ing) to minimize the number of changes that will be necessary in platform review"?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5050#-:-KcKapGQHBpr3odwokXH:b67kwyj)*

**Comment by jwnimmer-tri** [comment]
I would summarize the overall answer to that as "Convince at least one person that it is better to have this code on master (e.g., they will be able to use and continue developing it) than parked on a feature branch".  The specifics of that convincing will be specific to the code at hand.

**Pull request closed without merging**
