### PR TITLE
[planning] Update algorithms/planning module documentation

### LINKED ISSUE #18640: Reorg of planning-related code
As part of making our motion planning toolbox easier for everyone to understand, we are going to rework some directory/module names of the existing features, so it's easier for people to discover and browse through our tools.

Specifically, to relocate:

- [x] #18664
    -  From `manipulation/planner:robot_plan_interpolator` into `manipulation/util:robot_plan_interpolator`.
    -  From `manipulation/planner:constraint_relaxing_ik` into `multibody/inverse_kinematics:___` (i.e., with the same filename, just a new directory name).
- [x] #18715
    -  From `manipulation/planner:differential_inverse_kinematics` into `multibody/inverse_kinematics:___` (likewise).
    -  From `manipulation/planner:differential_inverse_kinematics_integrator` into `multibody/inverse_kinematics:___` (likewise).
- [x] #18697
    - From `systems/trajectory_optimization:*` into `planning/trajectory_optimization:*` (all files).

For any of these that are Stable API, we'd introduce deprecation shims to that the old include paths and namespaces continue to work during a transition period.

We'd like to enact this change prior to the next release in mid-February.

\CC @RussTedrake @calderpg-tri @SeanCurtis-TRI FYI

The google doc with a code manifest and discussions lives [here](https://docs.google.com/document/d/1foZ4Cg39mzYVUX-TRn3LubmuMAfUmFQbPFh5StHPa_w/edit#).

Relatedly, it might be a good time to:

- [ ] Update https://drake.mit.edu/doxygen_cxx/group__planning.html with more info.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Adds the new classes in drake/planning to the module.
2. Adds subgroups to the module to provide broad guidance on the classes.
3. Moves the planning module documentation into its own header.

resolves #18640

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-:-NOvEjgM41d4pr7McaYt:be5puew)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
so far so good. Going to generate the output and read it as well.

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-:-NOvJOGj7PkXzS3X6cTQ:b-rhm81t)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`planning/trajectory_optimization/integration_constraint.h` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-NOvHsZA84a-aANPAxCi:-NOvHsZBCtfUGNxLsDSq:bxc93wx) ([raw file](https://github.com/RobotLocomotion/drake/blob/deab729d0be922eb91aee254a4e5b22e52c9e20b/planning/trajectory_optimization/integration_constraint.h#L14)):*
> ```objc
>  * where the bounded variables are (xᵣ, xₗ, ẋᵣ, ẋₗ, dt)
>  *
>  * @ingroup solver_evaluators
> ```

nit curious why this file is filed differently -- physical layout and doxygen grouping appear to differ.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`planning/trajectory_optimization/integration_constraint.h` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-NOvHsZA84a-aANPAxCi:-NOvKUlJ94nWfe2bLsj6:bsqvyuw) ([raw file](https://github.com/RobotLocomotion/drake/blob/deab729d0be922eb91aee254a4e5b22e52c9e20b/planning/trajectory_optimization/integration_constraint.h#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit curious why this file is filed differently -- physical layout and doxygen grouping appear to differ.
</blockquote></details>

I saw other implementations of `solvers::Constraint` registered themselves to this group. And as the planning algorithms intro references that specific group, it made sense to dump them all in the same bin.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: took me a minute to find the Planning page under Algorithms. Aside from that (discoverability of doc is still a global problem), looks good.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-:-NOvMUPB39ZwJIe4X00m:b-7bz9ru)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@EricCousineau-TRI for feature review

(cc @jwnimmer-tri to make sure this is what you basically had in mind.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-:-NOvXiSq4NXiH4liUQaL:b-m3z5m1)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform (that's what I assumed ya meant)

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18854#-:-NOwYXdY0sVP0J9L8x-O:bsvvrcq)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
