### PR TITLE
[pydrake] Deprecate bindings of internal-use functions of PolygonSurfaceMesh

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Towards #17625.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@seancurtis-tri for feature (and platform) review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAC3Ax7-aNLQEJf7y99:b-63trfb)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Several thoughts:

1. This is technically a breaking change. Would deprecating these not be better? I'm open to the argument that there's no reasonable expectation that anyone is using them, but, perhaps, without a good reason to break, deprecate is better?
2. The C++ code should be marked in some way so someone down the road doesn't think, "Hey! The bindings are missing." You've got several options (I'd advocate both):
    - Insert the prefix `(Internal use only)` into the function documentation.
    - Surround them with a `#ifndef DRAKE_DOXYGEN_CXX`/`#endif` block so they're even omitted from the doxygen.
3. The same protection of `PolygonSurfaceMesh` APIs should be applied to `TriangleSurfaceMesh`. (Not necessarily in this PR, but we should make sure that they stay in sync.)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAFFl6K3kQz_Qc1mgrP:b57ybo7)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
I added `(Internal use only)` to both PolygonSurfaceMesh and TriangleSurfaceMesh.

I don't think deprecation is necessary.  

I'd like to keep them in Doxygen, so I can read the doc easier on the web browser instead of a code editor.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAFOsiT0Lmd4DrsZDrY:b8k1t1)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
re: deprecation

The [stable API](https://drake.mit.edu/stable.html) documentation makes promises about deprecation. It covers "all Python library code under import drake or import pydrake that is distributed in a Drake PyPI wheel". These two functions are part of that.

It carves out one explicit exception: 'code documented as “internal use only”.' However, since we're *adding* that designation in this PR, it doesn't seem to apply to the past.

The other exception would be: "On very rare occasions it is impractical, too expensive, or logically unsound to meet the full three month deprecation window." If this is the path we're taking, then we should document, at least in the PR, the justification for favoring a breaking change over a deprecating one.

That, at the very least, is how I read the page. It wouldn't be the first time that I've glossed over some relevant text. Take a look at the text and let me know if you feel I've missed something relevant here.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAG19fu3q97QFo8vxiK:bnqsgw5)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

**Comment by SeanCurtis-TRI** [comment]
BTW If you agree with my interpretation need any help on the actual deprecation mechanism, let me know.

**Review by DamrongGuoy — COMMENTED** [review]
If you could help me with coding the deprecation, that would be great!  Please let me know how to deprecate Python binding. With my limited Python skill, it's `impractical, too expensive`, but I guess you know a simple way to do it. 

Please feel free to grab the branch and give me a draft code.  That would help me learn Python.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAHMkr1D_Slb4qDi1fR:b-58gwz2)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

**Review by SeanCurtis-TRI — COMMENTED** [review]
No problem. I'll have something in a bit for you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAK1ydJ9p8QuQNumKEE:bdghpnk)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

**Review by SeanCurtis-TRI — COMMENTED** [review]
https://github.com/DamrongGuoy/drake/pull/1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAKJ6Rs5JBb4XY16Pns:bedw8v)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NASSm5AAY9Mmwo1t7Cr:b-9755fn)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: +@sammy-tri for platform review, please.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAfTVBa0NIjl1h6XMWW:b6ccful)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAfWQ3t2Ei2lAsm5hOj:bnfp4nl)* status: missing label for release notes (waiting on @DamrongGuoy)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: newly deprecated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17768#-:-NAfWTl2AIPY6qDbcFiT:b-dngdyv)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform) (waiting on @DamrongGuoy)

**Pull request merged**
