### PR TITLE
Rename monomial_*.{h,cc} to symbolic_monomial_*.{h,cc}

### PR DESCRIPTION
**Pull request by soonho-tri**
To be consistent with other `symbolic_*` files. FYI, `Monomial` class is already in `symbolic` namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6597)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri , feature-review please.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6597#-:-KpMHw9bc-c9rlA6Pc1U:bcq2m3k)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6597#-:-KpMhsuUgUU6I6LE8JCo:bpqxd5f)*

**Comment by soonho-tri** [comment]
@ggould-tri , may I have your platform-review (as a mentor of @ericcousineau-tri for tomorrow)? 

---

Review status: 18 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6597#-:-KpMnmzGPo1HYX1qu5a_:b-rj36r4)*

**Comment by ggould-tri** [comment]
+@ggould-tri 

---

Review status: 18 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6597#-:-KpPmWJKxQ-HcX-u2vKZ:b-who1rq)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 23 of 26 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6597#-:-KpQ8XwvlafCZj1PNDR3:bnfp4nl)*

**Pull request merged**
