### PR TITLE
[setup] Upgrade supported Clang to version 15

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21335.

Note that because this changes the setup scripts, all Provisioned jobs (pre-merge) will fail.  We need to deploy new images to get it passing.  During review, we'll use Unprovisioned jobs to test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
All unprovisioned jobs have passed.

+@mwoehlke-kitware for feature review, please.

\CC @BetsyMcPhail FYI once review is complete, we will need new provisioned images across the board -- Jammy, Ventura, Sonoma.  (But not macOS x86 of course.)

> Reviewed 24 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-:-NvsuX5e5lG4j6gwiptV:b-cpfnn8)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-NvsuLa7EE5oUt5cc4Nh:-NvsuLa7EE5oUt5cc4Ni:btmuxii) (no related file):*
Working

Do not merge yet -- we need to coordinate the merge with a swap-out of CI provisioned images.

___

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 22 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/geometry/geometry_py_visualizers.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-Nw5qguK42g5gEQF0GhQ:-Nw5qguK42g5gEQF0GhR:b-drk89m) ([raw file](https://github.com/RobotLocomotion/drake/blob/e42b82a53fc68768ee541360ae55fc9a9ce8c0fe/bindings/pydrake/geometry/geometry_py_visualizers.cc#L374)):*
> ```cpp
>     // the GIL.
>     auto wrap_get_packed_foo = []<typename... Args>(std::string (
>                                    Class::*member_function)(Args...) const) {
> ```

Whu? This doesn't look any form of reasonable... clang-format bug?

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri do you have cycles to platform review this sometime today?  Otherwise I'm happy to shop it around.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-:-Nw5zhv1C8XQgqUwtg3M:biid0dd)* status: 1 unresolved discussion, LGTM missing from assignees mwoehlke-kitware,rpoyner-tri(platform)

___
*[`bindings/pydrake/geometry/geometry_py_visualizers.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-Nw5qguK42g5gEQF0GhQ:-Nw5zOhC0ykg_ImSPks_:ba6f0jg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e42b82a53fc68768ee541360ae55fc9a9ce8c0fe/bindings/pydrake/geometry/geometry_py_visualizers.cc#L374)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Whu? This doesn't look any form of reasonable... clang-format bug?
</blockquote></details>

Done

In this case, shortening the variable name improves the formatting without harming clarity.

**Review by mwoehlke-kitware — COMMENTED** [review]
Code :lgtm:... I take it the CI dumpster fire is because CI doesn't have 15?

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-:-Nw6ALHm8RM_XBgXII9-:bihmaub)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`bindings/pydrake/geometry/geometry_py_visualizers.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-Nw5qguK42g5gEQF0GhQ:-Nw69qB3-0_fIOuhIfK4:bkwzcl2) ([raw file](https://github.com/RobotLocomotion/drake/blob/e42b82a53fc68768ee541360ae55fc9a9ce8c0fe/bindings/pydrake/geometry/geometry_py_visualizers.cc#L374)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done

In this case, shortening the variable name improves the formatting without harming clarity.
</blockquote></details>

Eep, and not being able to make up its mind about the space after the return type definitely smells like a bug. Well, the current state is okay; thanks!

**Comment by jwnimmer-tri** [comment]
> I take it the CI dumpster fire is because CI doesn't have 15?

Correct.  (See PR description.)

Once platform review is finished, I'll re-test all of the Unprovisioned, and then open a ticket requesting new Provisioned images.  I decided not to do it right away in case the setup scripts evolve during review.

**Review by rpoyner-tri — COMMENTED** [review]
I'll look.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-:-Nw6UTUQ3bPIshY-43M9:bkwx5zm)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 22 of 24 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-:-Nw6V4Vr1oPrjq8v58XL:bnfp4nl)* status: 1 unresolved discussion

**Comment by jwnimmer-tri** [comment]
Thanks!  Alright, let's buy a lot of coffees for CI:

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Sigh.  I think I ran the wrong clang-format locally when fixing the bindings thing.  I'll need to push a new version.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-NvsuLa7EE5oUt5cc4Nh:-Nw7BAAo7DbTANhNQARF:b-nx3h5g) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge yet -- we need to coordinate the merge with a swap-out of CI provisioned images.
</blockquote></details>

Pending in https://github.com/RobotLocomotion/drake/issues/21348.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21339)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21339#-NvsuLa7EE5oUt5cc4Nh:-NwLj5W08FNabuVo-tvI:bb6un1j) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Pending in https://github.com/RobotLocomotion/drake/issues/21348.
</blockquote></details>

Done

___

**Comment by jwnimmer-tri** [comment]
Forcing in now...

**Pull request merged**
