### PR TITLE
[doc] Fix staleness in from_source instructions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #20916, #18262.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20977)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review, please.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-:-Nr1Bg_nDcVg0XBn_GhH:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`doc/_pages/from_source.md` line 131 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BE-F1ts4-xRQbDy_:-Nr1BE-G1ohmslMASEqQ:b8oihfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L131)):*
> ```Markdown
> tweaking a source code file and repeatedly installing, without any changes to
> the build system. For any kind of larger change (e.g., upgrading to a newer
> Drake), we strongly advise that you delete the prior tree (within the `install`
> ```

FYI, this is *probably* okay, but the user *can* change the Drake install location. (`<build-dir>/install` is the default.)
___
*[`doc/_pages/from_source.md` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BZhtA5VS6DZFyOkA:-Nr1BZhuE7h_FkpkktVB:b-jvb24v) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L161)):*
> ```Markdown
> ```bash
> cd drake-build
> export PYTHONPATH=${PWD}/install/lib/python3.11/site-packages:${PYTHONPATH}
> ```

FYI, I wonder if there's a good place to leave a note to update this when the macOS Python version changes...

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20977)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`doc/_pages/from_source.md` line 131 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BE-F1ts4-xRQbDy_:-Nr1cULh04RI9B-Xe5Vv:bktg6et) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L131)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, this is *probably* okay, but the user *can* change the Drake install location. (`<build-dir>/install` is the default.)
</blockquote></details>

I think it's good enough as-is.
___
*[`doc/_pages/from_source.md` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BZhtA5VS6DZFyOkA:-Nr1caLd0j_rhmNSINIu:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L161)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, I wonder if there's a good place to leave a note to update this when the macOS Python version changes...
</blockquote></details>

Done

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-:-Nr1gHBt0F2sLoaLFk8M:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),mwoehlke-kitware

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/from_source.md` line 131 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BE-F1ts4-xRQbDy_:-Nr1xu5z915YAbs1mjCq:b-cz7nle) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L131)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it's good enough as-is.
</blockquote></details>

Right; if you changed it, hopefully you know where you put it. (And I don't know what else we'd say that wouldn't be overly wordy and likely not necessary for the people to whom it would apply.)

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/from_source.md` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1BZhtA5VS6DZFyOkA:-Nr1y8eZ4SIAbWpDqJ2X:b-q6gty1) ([raw file](https://github.com/RobotLocomotion/drake/blob/011b67ba5d0a5aae2d617b9a413be8631f958209/doc/_pages/from_source.md#L161)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Oh... I see now it was already there. Looks like it got missed when previously updated. :shrug:

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/python/repository.bzl` line 239 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1zdGl23yc97Jm7tq1:-Nr1zdGl23yc97Jm7tq2:b-koc2p5) ([raw file](https://github.com/RobotLocomotion/drake/blob/a09908888b099750749cc14d922fefb6a978d758/tools/workspace/python/repository.bzl#L239)):*
> ```Starlark
>     "macos_interpreter_path": attr.string(
>         # The version listed here should match what's listed in both the root
>         # CMakeLists.txt and doc/_pages/installation.md.
> ```

(Similar in other relevant places...)



_Suggestion:_
```Starlark
CMakeLists.txt, doc/_pages/installation.md, and doc/_pages/from_source.md
```

**Comment by jwnimmer-tri** [comment]
*[`tools/workspace/python/repository.bzl` line 239 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20977#-Nr1zdGl23yc97Jm7tq1:-Nr2-Br47CGWSnelflLk:b-s92svc) ([raw file](https://github.com/RobotLocomotion/drake/blob/a09908888b099750749cc14d922fefb6a978d758/tools/workspace/python/repository.bzl#L239)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

(Similar in other relevant places...)
</blockquote></details>

Not necessary IMO.  The installation.md text instructs us to grep _all_ other documentation files.  Trying to keep the list of all relevant documentation pages inside the build system is too much work.

**Pull request merged**
