### PR TITLE
Add [[nodiscard]] to symbolic::Polynomial functions.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
We should probably disable `Werror=unused-result` for unit test code.  It would be something of this sort:

https://github.com/RobotLocomotion/drake/blob/925e38254bb147172eed71e5658e632509c32ff2/tools/skylark/drake_cc.bzl#L62-L66

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy!

+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N3uLcILAMrmQl3RXVsm:b1nm89c)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

Probably worth a second platform reviewer once we clear feature review.  This is somewhat of a novel idea.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N3uP3Y77PXKrMRbaz1T:b-o974ac)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 1307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOIMy1KwSRCY4yn7X:-N3uOIMy1KwSRCY4yn7Y:bq1i43r) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/BUILD.bazel#L1307)):*
> ```Starlark
>     copts= [
>         # Allow some of the returned argument to be unused.
>         "-Wno-unused-result",
> ```

Working

This should probably be project-wide, not just for this one test file.  I'm polling on slack now.
___
*[`common/symbolic_polynomial.h` line 307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOiAh8neAn8gI4aZD:-N3uOiAh8neAn8gI4aZE:bdv1f9m) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/symbolic_polynomial.h#L307)):*
> ```objc
> 
> /// Unary minus operation for polynomial.
> Polynomial operator-(const Polynomial& p);
> ```

These (here and below .. down through `pow`) all should probably be `[[nodiscard]]` as well?  They all return a freshly-computed values, and therefore are useless to call for mutable side-effects.
___
*[`common/symbolic_polynomial.h` line 522 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uP-MS50h535tx5LHD:-N3uP-MT1CpdGj3gbzw_:bung4a0) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/symbolic_polynomial.h#L522)):*
> ```objc
>                   Derived::ColsAtCompileTime, 0, Derived::MaxRowsAtCompileTime,
>                   Derived::MaxColsAtCompileTime>>
> Evaluate(const Eigen::MatrixBase<Derived>& m, const Environment& env) {
> ```

nit `[[nodiscard]]`?
___
*[`common/symbolic_polynomial.h` line 531 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uP0l98hLwj6ZBTukS:-N3uP0l98hLwj6ZBTukT:bung4a0) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/symbolic_polynomial.h#L531)):*
> ```objc
> /// @pre {@p vars is non-empty}.
> /// @pydrake_mkdoc_identifier{polynomial}
> MatrixX<Polynomial> Jacobian(const Eigen::Ref<const VectorX<Polynomial>>& f,
> ```

nit `[[nodiscard]]`?

**Review by jwnimmer-tri — COMMENTED** [review]
Note that CI is failing on the bindings.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N3uhDOI4xr7E2oc1FVN:b-dtfiaw)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 1307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOIMy1KwSRCY4yn7X:-N3uh2qo-7wjTnMF4lXP:b-do024d) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/BUILD.bazel#L1307)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This should probably be project-wide, not just for this one test file.  I'm polling on slack now.
</blockquote></details>

After #17341 merges, this PR should drop this flag.  There will be one more EXPECT_THROW warning still remaining.  Adding `unused()` around that one site will fix the problem.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`common/BUILD.bazel` line 1307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOIMy1KwSRCY4yn7X:-N3vFPA23aYJtBuU39Nr:br20ssg) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/BUILD.bazel#L1307)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

After #17341 merges, this PR should drop this flag.  There will be one more EXPECT_THROW warning still remaining.  Adding `unused()` around that one site will fix the problem.
</blockquote></details>

That's merged.  Over to you for a rebase.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 1307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOIMy1KwSRCY4yn7X:-N3viO3A7Qy7zOnuEi9U:b-eqdmu4) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/BUILD.bazel#L1307)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That's merged.  Over to you for a rebase.
</blockquote></details>

Done. Thanks for filing the PR #17341
___
*[`common/symbolic_polynomial.h` line 307 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17330#-N3uOiAh8neAn8gI4aZD:-N3viMgkCMHe637_ziCX:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/b68ee700574d6f1c5c9411201c46068a7ed171c1/common/symbolic_polynomial.h#L307)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These (here and below .. down through `pow`) all should probably be `[[nodiscard]]` as well?  They all return a freshly-computed values, and therefore are useless to call for mutable side-effects.
</blockquote></details>

Done. Good call.

**Review by jwnimmer-tri — COMMENTED** [review]
-(release notes: none) +(release notes: yes) because users might notice new warnings from their own code.

> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N3vwDXOCIWNQmjppPiN:b-pmlqcv)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for Wednesday's platform review since Jeremy is Tuesday's platform reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N3wiNw_EJjWzJhuhz5f:b-bhytyv)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I'm curious what was the motivation for this change? 

But I have no objection -- platform :lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17330#-:-N43-k7J3dUnY6i7BrsZ:b-iiyuj5)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Comment by hongkai-dai** [comment]
> I'm curious what was the motivation for this change?

I was calling a function` Polynomial::RemoveSmallCoefficients(tol)` and forgot to return the value (I thought this function does changes the polynomial in-place).

**Comment by sherm1** [comment]
> I was calling a function Polynomial::RemoveSmallCoefficients(tol) and forgot to return the value (I thought this function does changes the polynomial in-place).

Thanks. Great idea to fix this and related functions prophylactically!

**Pull request merged**
