### PR TITLE
Modified drake::ros::WaitForParameter() to use wall clock time instead of ROS time

### PR DESCRIPTION
**Pull request by liangfok**
# Motivation

In #3583, `drake::ros::WaitForParameter()` used ROS time. When running in simulation mode, this results in a deadlock condition between:

1. the method waiting for the simulation clock to advance
2. the simulation not starting while it waits for the parameter to show up

# Justification

Since the process of obtaining parameters can be classified as happening _before_ the simulation starts, I believe it's OK to use wall clock time while obtaining the parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3588)

### CODE REVIEW

**Comment by liangfok** [comment]
Since I wasn't able to [chain](https://github.com/Reviewable/Reviewable/issues/253) this PR after #3583, I'm going to mark this as "do not review" until after #3583 is merged.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
+@jhoare for feature review please.
+@david-german-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSfSLurM3W9YPd1oFpW:bhpq74e)*

**Comment by david-german-tri** [comment]
Is this still "do not review"?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSgncCFrxzkfj6iLh4e:b-x306aq)*

**Comment by liangfok** [comment]
Oops! No. This is ready to be reviewed.  Thanks!

**Comment by david-german-tri** [comment]
This makes sense to me superficially, but I can't speak to whether it's the right way to use ROS or not.  :lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_common/src/parameter_server.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-KSgvZBV7w1N5bpa91a4:-KSgvZBV7w1N5bpa91a5:b-k34m4t) ([raw file](https://github.com/robotlocomotion/drake/blob/d5b56fe557ebb9c3a5642f10e05dd78617c5d1b2/ros/drake_ros_common/src/parameter_server.cc#L19)):*
> ```cpp
>   TimePoint start = TimeClock::now();
>   while (::ros::ok() && !::ros::param::has(parameter_name) &&
>       duration_cast<std::chrono::milliseconds>(TimeClock::now() - start).count()
> ```

BTW, this condition is pretty tough to read.  Consider moving it into the body of the loop using `break`, and splitting it up into multiple variables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSgvsxgy_Wu6nG6dTVu:b-oss8xp)*

**Comment by liangfok** [comment]
@david-german-tri, I addressed your comments.  Now waiting for CI to complete.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_common/src/parameter_server.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-KSgvZBV7w1N5bpa91a4:-KShDiQ3RatdKoYk7ktP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5b56fe557ebb9c3a5642f10e05dd78617c5d1b2/ros/drake_ros_common/src/parameter_server.cc#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this condition is pretty tough to read.  Consider moving it into the body of the loop using `break`, and splitting it up into multiple variables.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KShDlo3ulfFFqDSSobS:bud0py1)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
This PR passed all unit test and is thus ready for @jhoare's feature review. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KShNreirACCRVbHnt8Y:b-9qws06)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KShpQjKT3l7OXVRupfT:bnfp4nl)*

**Comment by liangfok** [comment]
*[ros/drake_ros_common/include/drake/ros/parameter_server.h, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-KSi2ePRwICKEgYChJmh:-KSi2ePTkynCZhn6qlgT:b98iygl) ([raw file](https://github.com/robotlocomotion/drake/blob/3dcdd339d23190daffb9d42b44cb646c80d210a2/ros/drake_ros_common/include/drake/ros/parameter_server.h#L20)):*
> ```objc
>  *
>  * @param[in] max_wait_time The maximum amount of wall clock time to wait for
>  * the parameter to become available before aborting.
> ```

Replace "aborting" with "returning".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_common/include/drake/ros/parameter_server.h, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-KSi2ePRwICKEgYChJmh:-KSiItp7ggVCSKL6PflW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3dcdd339d23190daffb9d42b44cb646c80d210a2/ros/drake_ros_common/include/drake/ros/parameter_server.h#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Replace "aborting" with "returning".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588)*

**Comment by jhoare** [comment]
This could be done the ROS way by changing instances of `Time` to `WallTime` and `Duration` to `WallDuration` which exist for this purpose. That said, I believe this would work fine as well, and won't hurt anything, it just a little strange to be mixing the two time APIs. 

See:
http://docs.ros.org/indigo/api/rostime/html/classros_1_1WallTime.html
http://docs.ros.org/indigo/api/rostime/html/classros_1_1WallDuration.html

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSkopNaQW0khftTGeeV:b57ctw1)*

**Comment by jhoare** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588)*

**Comment by liangfok** [comment]
@jhoare, thanks for the tip. I will update this PR to use ROS' `WallTime` and `WallDuration` APIs.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSkqXxPHB3DVNaPq8hL:bjex8nc)*

**Comment by liangfok** [comment]
@jhoare, I updated to this PR to use ROS's `WallDuration` and `WallTime` APIs. PTAL. Thanks!

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSl-avqFgWD2QQ-mjDb:bwlvws3)*

**Comment by jhoare** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSl5in4N_RkMwYgHtis:bg7igkv)*

**Comment by liangfok** [comment]
Thanks. Now waiting on CI.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3588#-:-KSl92M-4Qu2x8UysON2:b-mta4n0)*

**Comment by liangfok** [comment]
Strange, either CI did not start or the message telling github that CI started was lost.

@drake-jenkins-bot retest this please.
@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
Looks like the previous request for CI tests did not go through. I'm going to trigger it again.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
This PR passed all unit tests and received both levels of LGTMs. Proceeding to merge.

**Pull request merged**
