### PR TITLE
[workspace] Build vendored clp_internal from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 15 of 24 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 15 of 24 files at r1, 6 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-:-NbH2fzg7uemBEB54n2e:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/coinutils_internal/defs.bzl` line 182 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH23KK4OsxUCalLDhE:-NbH23KK4OsxUCalLDhF:bda5xp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/coinutils_internal/defs.bzl#L182)):*
> ```Starlark
>             outs = [vendor_src + ".patch"],
>             cmd = " ".join([
>                 "(diff -U0",
> ```

btw I'm curious what difference this makes.
___
*[`tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel` line 383 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH2Z2s9WJe6WB1A2b4:-NbH2Z2s9WJe6WB1A2b5:b-humdj4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel#L383)):*
> ```
>     ],
>     allowed_externals = [
>         "@drake//tools/workspace/ipopt_internal_fromsource:patches",
> ```

The changes in this file look like strays from other work, maybe?

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-:-NbH69QuB-OMMpFA_9Ya:bybe5xg)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`tools/workspace/coinutils_internal/defs.bzl` line 182 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH23KK4OsxUCalLDhE:-NbH5LInDb-joN7vntKn:b-qyteug) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/coinutils_internal/defs.bzl#L182)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw I'm curious what difference this makes.
</blockquote></details>

macOS rejects the `-u` spelling as deprecated.
___
*[`tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel` line 383 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH2Z2s9WJe6WB1A2b4:-NbH5VMDAnZ_DZQbDEnt:bv33imi) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel#L383)):*
This hunk is not stray:
> # The glob might be empty if we don't have any patches at the moment,
> # but we'll keep the boilerplate here as a fail-safe.

I'll edit the comment message to mention the AUTOCONF_UNDEFINES.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`tools/workspace/coinutils_internal/defs.bzl` line 182 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH23KK4OsxUCalLDhE:-NbH6nPu2AcE3wSlsGBb:bgneoq3) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/coinutils_internal/defs.bzl#L182)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

macOS rejects the `-u` spelling as deprecated.
</blockquote></details>

(Which wasn't a problem for Ipopt because we only build that from source on Ubuntu.  Now that we're building more Coin stuff from source for both platforms, it became relevant.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel` line 383 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-NbH2Z2s9WJe6WB1A2b4:-NbH7Tep6tqrgmo1l4KF:b-bthveg) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d3d790af98ac19abe7a0414c17367376d3788d/tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel#L383)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This hunk is not stray:
> # The glob might be empty if we don't have any patches at the moment,
> # but we'll keep the boilerplate here as a fail-safe.

I'll edit the comment message to mention the AUTOCONF_UNDEFINES.
</blockquote></details>

Wow.  That was supposed to be a quoted `#` comment, not NEW YORK CASE.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
There's a _lot_ of repetition and magical boilerplate here which makes me wonder if future upgrades will be difficult to do for the COIN packages. But ... I don't know of a better way. Platform :lgtm:

> Reviewed 15 of 24 files at r1, 6 of 10 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19928#-:-NbHQmrQ54cAHszMWQmm:brx51r3)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
