### PR TITLE
Deprecate Python default parameters for ScrewJoint

### PR DESCRIPTION
**Pull request by amcastro-tri**
There is no reason to have a different set of default parameters in Python than in C++.
This PR makes the ScrewJoint constructor consisten in both Python and C++ (i.e. removes default parameters from the python API)

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18122)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@rpoyner-tri for feature/platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18122#-:-NEbbh4l5XYAMqS6S02A:bamcvgw)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
> On very rare occasions it is impractical, too expensive, or logically unsound to meet the full three month deprecation window. In these cases the change will be announced in the “Breaking changes” section of the release notes.

-- https://drake.mit.edu/stable.html

Could you clarify whether it was too impractical, too expensive, or unsound to use deprecation here?

**Review by rpoyner-tri — COMMENTED** [review]
It wasn't clear to me how to deprecate these on first inspection. If it were C++, we could count on there only being a 4-arg form and a 3-arg form, and write those out explicitly with deprecation markings. How do we deprecate, say,
```
ScrewJoint("foo", some_frame, other_frame, damping=22)
```
?

I suppose deprecation is possible if we change the default values to something a user cannot spell, detect when those values are present, and then substitute the old default values, and issue a deprecation message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18122#-:-NEc0OQcAgpB-gQ6Q68L:bha8veg)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Yes, in the bindings you could change the default to `= none` and bind a lambda instead of the function pointer itself.  Then in case they were none within the lambda, issue the deprecation warning and call the C++ implementation using `.value_or(0.0)`.

Or, recall that `pybind11` overloads are processed in the order they are declared.  Possibly you could bind the no-defaults overload first, and the deprecated with-defaults overload second, and allow the function signature matching to choose which one the user spelled.

**Comment by jwnimmer-tri** [comment]
Either of those two should be easy (I hope), but otherwise in the alternative you could deprecate the default arguments _via documentation_ and release notes, without any runtime warning.  That one would _definitely_ be easy.

**Comment by jwnimmer-tri** [comment]
I'll push the fix shortly.

**Comment by jwnimmer-tri** [comment]
> @rpoyner-tri for feature/platform review please.

If you concur with wearing both hats @rpoyner-tri, then please add the "single reviewer" label.

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18122#-:-NEfoDbj0PL5tUT0-vSt:b3dcro0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18122#-:-NEfoM9BEQUpOJN711hi:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
