### PR TITLE
implements the linear programming approach to approximate dynamic programming

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8101)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.
cc @frankpermenter 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-:-L5gIk03VqVq4UQVe8Ex:brugbe7)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/controllers/dynamic_programming.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ghUqHFdK2DOIgCPJi:-L5ghUqHFdK2DOIgCPJj:b-fp5ju4) ([raw file](https://github.com/robotlocomotion/drake/blob/36bbd7c44ee390aadde3d29ffeafc5d93f974ec3/systems/controllers/dynamic_programming.h#L147)):*
> ```objc
>         const Eigen::Ref<const Eigen::VectorXd>& state,
>         const VectorX<symbolic::Variable>& parameters)>&
>         linearly_parameterized_cost_to_go_function,
> ```

Can we just pass in the parameters here, instead of `linearly_parameterized_cost_to_go_function`? The cost-to-go function should be in the form of `pᵀx`, where `p` is the parameters, and `x` is the state. We can ask the user to pass in `p` here, and internally we add the constraint ∀ x ∀ u, pᵀx ≤ g(x) + γ pᵀf(x, u)

The user could pass in a nonlinear function or affine function as `linearly_paramterized_cost_to_go_function`. If it were nonlinear function, then the error is only thrown when we call `AddLinearConstraint`, and it will not throw an error for affine cost.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-:-L5giugczlTgX7gcO5aU:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/controllers/dynamic_programming.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ghUqHFdK2DOIgCPJi:-L5h_jH_kkk8kD6c3ABo:b-xhp2ze) ([raw file](https://github.com/robotlocomotion/drake/blob/36bbd7c44ee390aadde3d29ffeafc5d93f974ec3/systems/controllers/dynamic_programming.h#L147)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we just pass in the parameters here, instead of `linearly_parameterized_cost_to_go_function`? The cost-to-go function should be in the form of `pᵀx`, where `p` is the parameters, and `x` is the state. We can ask the user to pass in `p` here, and internally we add the constraint ∀ x ∀ u, pᵀx ≤ g(x) + γ pᵀf(x, u)

The user could pass in a nonlinear function or affine function as `linearly_paramterized_cost_to_go_function`. If it were nonlinear function, then the error is only thrown when we call `AddLinearConstraint`, and it will not throw an error for affine cost.
</blockquote></details>

no, no.  This takes any function of the form p^T \phi(x).  it's very general!  i'll update the comment.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101)*

**Comment by soonho-tri** [comment]
+@soonho-tri for platform review.

---

Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-:-L5iOWCQn2RTkr9x4fI6:bxw8cpy)*

**Comment by RussTedrake** [comment]
fwiw....   this pdf shows a fun use case.
[PendulumApproximateDP.pdf](https://github.com/RobotLocomotion/drake/files/1737379/PendulumApproximateDP.pdf)

**Comment by soonho-tri** [comment]
Checkpoint. `dynamic_programming.{h, cc}` looks good to me and it matches with the DP chapter.

I'll finish the rest asap.

---

Reviewed 2 of 5 files at r2.
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 154 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5inHhPkWwQ58omLRmd:-L5inHhPkWwQ58omLRme:be0mdyg) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L154)):*
> ```cpp
>     const std::function<
>         symbolic::Expression(const Eigen::Ref<const Eigen::VectorXd>& state,
>                              const VectorX<symbolic::Variable>& parameters)>& J,
> ```

FYI, in the header file, this parameter is named as `linearly_parameterized_cost_to_go_function` while it uses `J` here.

---

*[systems/controllers/dynamic_programming.cc, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ijjbhWC5xiWb6s_zn:-L5ijjbhWC5xiWb6s_zo:b-qwbreg) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L230)):*
> ```cpp
>       // Filter out constraints that are trivially true (because
>       // AddConstraint throws).
>       if (f.get_kind() != symbolic::FormulaKind::True) {
> ```

BTW, `is_true(f)` should work as well.

---

*[systems/controllers/dynamic_programming.h, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ikcb3RSdNffmLmF9N:-L5ikcb3RSdNffmLmF9O:bljd22r) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.h#L127)):*
> ```objc
> /// a Context for that system, which may contain non-default Parameters, etc.
> /// The @p simulator is run for @p timestep seconds from every pair of
> /// input/state sample points in order to approximate the dynamics...
> ```

`...` in the end: let's zap it or expand?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-:-L5ios6T5aMVgnZFnamx:b-sg0iyc)*

**Comment by RussTedrake** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 154 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5inHhPkWwQ58omLRmd:-L5iqNcQ49RJKidOLsD1:bqqvyyk) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L154)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, in the header file, this parameter is named as `linearly_parameterized_cost_to_go_function` while it uses `J` here.
</blockquote></details>

that was intentional (i wanted the API variable name long and descriptive, but the implementation is much cleaner with this).  is it a style violation?

---

*[systems/controllers/dynamic_programming.cc, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ijjbhWC5xiWb6s_zn:-L5iqqzKXQGscUw3R9C3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L230)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `is_true(f)` should work as well.
</blockquote></details>

Done.

---

*[systems/controllers/dynamic_programming.h, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ikcb3RSdNffmLmF9N:-L5ir0NmIt34B2kwxMog:bnz4t6d) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.h#L127)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`...` in the end: let's zap it or expand?
</blockquote></details>

should have been ;.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 154 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8101#-L5inHhPkWwQ58omLRmd:-L5iuxHo3P_t4SAoc4KL:bxmkd6g) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L154)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that was intentional (i wanted the API variable name long and descriptive, but the implementation is much cleaner with this).  is it a style violation?
</blockquote></details>

I don't think we have a rule for that. But there are tools out there such as `clang-tidy` which will complain about the discrepancy when we start using it.

I understand that `J` is cleaner. I would either 1) change the header to use `J` with a comment, or 2) put a short comment in the `.cc` file.

---

*[systems/controllers/test/dynamic_programming_test.cc, line 218 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8101#-L5ixAKA8gK9n4N6HVZ7:-L5ixAKA8gK9n4N6HVZ8:bgdmrac) ([raw file](https://github.com/robotlocomotion/drake/blob/c0441d5ae7ad036dc4f49c2bd394d83dd6ce36f7/systems/controllers/test/dynamic_programming_test.cc#L218)):*
> ```cpp
>   const auto cost_function = [](const Context<double>& context) {
>     double x = context.get_continuous_state()[0];
>     return (std::abs(x) > 0.1) ? 1. : 0.;
> ```

BTW, to my education, the use of `> 0.1` is just to avoid numerical issues?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8101#-:-L5ixesD7J2Mp6-4cqkr:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/controllers/dynamic_programming.cc, line 154 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5inHhPkWwQ58omLRmd:-L5jKYbWHqgCzb9C4hVB:b-p3i70r) ([raw file](https://github.com/robotlocomotion/drake/blob/ed6c6bc43b2000f0a45623e2eec2803dc37324df/systems/controllers/dynamic_programming.cc#L154)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I don't think we have a rule for that. But there are tools out there such as `clang-tidy` which will complain about the discrepancy when we start using it.

I understand that `J` is cleaner. I would either 1) change the header to use `J` with a comment, or 2) put a short comment in the `.cc` file.
</blockquote></details>

decided to play by the books.  used the original argument name, then made an explicit alias (via const auto & J) in the implementation.

---

*[systems/controllers/test/dynamic_programming_test.cc, line 218 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8101#-L5ixAKA8gK9n4N6HVZ7:-L5jJz-TngdAuRQMAHnv:b-j3v0s9) ([raw file](https://github.com/robotlocomotion/drake/blob/c0441d5ae7ad036dc4f49c2bd394d83dd6ce36f7/systems/controllers/test/dynamic_programming_test.cc#L218)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, to my education, the use of `> 0.1` is just to avoid numerical issues?
</blockquote></details>

yes.  i only ever evaluate it at the integers, and want to make sure 0 is 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8101)*

**Pull request merged**
