### PR TITLE
Added SetPositions/Velocities/PositionsAndVelocities() to MultibodyPlant...

### PR DESCRIPTION
**Pull request by edrumwri**
...and added python bindings for position and velocity accessors and mutators too!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10017)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Personally, I would rather have the pydrake documentation mention the wrong overloads' parameters until someone happens to notice and fix it, than have `WARNING` on every single overloaded drake method ever (which is the logical conclusion of adding to the functions touched by this PR).  If we think overload documentation mixups are a problem worth worrying about, we should either fix #9599 item 16 (only about an hour of work), or else maybe just ping a reminder to all drake developers that overloads ordering generally affects pydrake docs -- we should not add copypasta to a PR just because it has overloaded methods.

**Comment by jwnimmer-tri** [comment]
@sherm1 There are at 200+ overloads bound into pydrake[1].  Do you _really_ want that warning copypast'd 200 times in the code?  I really, really don't.  Isn't sending a quick email to all of the reviewers good enough for now?

And really, the pydrake docs aren't _that_ important.  Sure we should care a bit about them, but that time should be spend on fixing mkdoc, not by a 1000+ line PR that adds the 200+ copypata instances you're asking for.

[1] `find drake -type f -print0 | xargs -0 grep -n -e 'doc_[0-9]'`

**Comment by jwnimmer-tri** [comment]
To be clear, nothing I've said above should be taken to block this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
