### PR TITLE
Add CLP to drake build.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Can you add clp explicitly to the prerequisites scripts? We don't need to update CI as it was a transitive dependency before, but it helps with bookkeeping if it is listed as a direct dependency.

**Comment by jwnimmer-tri** [comment]
It's there already, I think?

https://github.com/RobotLocomotion/drake/blob/faa2301c3715781b4b9cee0a70b62302a4fb95f3/setup/ubuntu/binary_distribution/packages-bionic.txt#L1

https://github.com/RobotLocomotion/drake/blob/faa2301c3715781b4b9cee0a70b62302a4fb95f3/setup/ubuntu/binary_distribution/packages-focal.txt#L1

https://github.com/RobotLocomotion/drake/blob/faa2301c3715781b4b9cee0a70b62302a4fb95f3/setup/ubuntu/source_distribution/packages-bionic.txt#L3

https://github.com/RobotLocomotion/drake/blob/faa2301c3715781b4b9cee0a70b62302a4fb95f3/setup/ubuntu/source_distribution/packages-focal.txt#L3

**Comment by jwnimmer-tri** [comment]
Maybe https://github.com/RobotLocomotion/drake/blob/faa2301c3715781b4b9cee0a70b62302a4fb95f3/setup/mac/binary_distribution/Brewfile is all that's missing.

**Comment by jamiesnape** [comment]
Yes, just missing on Mac then.

**Comment by jamiesnape** [comment]
The formula is `'clp'`

**Review by hongkai-dai — COMMENTED** [review]
Done, I just added the mac build. Thanks!

+@jamiesnape for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729#-:-MUt4jhJ2e2x3FQpRCCB:bxlk4or)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
All of this is dead code until you depend on it somewhere.  At minimum, you need to add a stub test that invoke CLP.

**Comment by jamiesnape** [comment]
I'd settle for a `cc_test` that simply creates some object from CLP, which tests compilation and linking, if the mathematical program part that uses it is going to follow soon. Otherwise whatever the most simple (part of a) unit test from CLP is the sort of think that works for me. In other words, something trivial that has `@clp` in its `deps`.

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[tools/workspace/clp/repository.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUu4kgZ1kYNd09u5C-l:-MUu4kgZ1kYNd09u5C-m:bdhtb9o) ([raw file](https://github.com/robotlocomotion/drake/blob/22bf8ea41e35366465ba499361164a22df4dcc1e/tools/workspace/clp/repository.bzl#L11)):*
> ```Starlark
>         name,
>         licenses = [
>             "reciprocal",  # CPL-1.0
> ```

BTW I make the license officially `EPL-1.0` (basically a rename of `CPL-1.0`), and will change to `EPL-2.0` on the next release
___
*[tools/workspace/clp/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUu5Fsp1bLW-Ha7AKhF:-MUu5Fsp1bLW-Ha7AKhG:bq62yoi) ([raw file](https://github.com/robotlocomotion/drake/blob/22bf8ea41e35366465ba499361164a22df4dcc1e/tools/workspace/clp/repository.bzl#L12)):*
> ```Starlark
>         licenses = [
>             "reciprocal",  # CPL-1.0
>             "unencumbered",  # Public-Domain
> ```

BTW Can you point me to the public domain code in CLP?

**Review by hongkai-dai — COMMENTED** [review]
Done, I added a simple test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729#-:-MUvdGdA-CxpyOg6M_Xo:bvjasfz)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

___
*[tools/workspace/clp/repository.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUu4kgZ1kYNd09u5C-l:-MUvdVha3ACXlIIFP-NM:b-rqfn8y) ([raw file](https://github.com/robotlocomotion/drake/blob/22bf8ea41e35366465ba499361164a22df4dcc1e/tools/workspace/clp/repository.bzl#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I make the license officially `EPL-1.0` (basically a rename of `CPL-1.0`), and will change to `EPL-2.0` on the next release
</blockquote></details>

Done, it is actually EPL-2.0 license.
___
*[tools/workspace/clp/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUu5Fsp1bLW-Ha7AKhF:-MUvdY_J7RHgSofxO-HS:bq6cum5) ([raw file](https://github.com/robotlocomotion/drake/blob/22bf8ea41e35366465ba499361164a22df4dcc1e/tools/workspace/clp/repository.bzl#L12)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Can you point me to the public domain code in CLP?
</blockquote></details>

I don't think there is public domain code in CLP. I just copied this licenses field from IPOPT. I removed the public domain license.

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729#-:-MUxlY564o8QqaBFQZNZ:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729#-:-MUyAxP5AmiMiRywIJyg:buxscyd)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: tested on macsim.

> Reviewed 5 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729#-:-MUyDFGeDFU5Qwb2PmEU:bohmcjp)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[tools/install/libdrake/BUILD.bazel, line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyCq6Q6NdHbaW9zH3a:-MUyCq6Q6NdHbaW9zH3b:bmz6ng) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L227)):*
> ```Starlark
>     name = "libdrake_runtime_so_deps",
>     deps = [
>         ":dreal_deps",
> ```

nit We need `":clp_deps"` here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[tools/install/libdrake/BUILD.bazel, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyO60C5iKbjGC4ZGgv:-MUyO60C5iKbjGC4ZGgw:b-mfmsh2) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L106)):*
> ```Starlark
> )
> 
> # Depend on CLP's shared library iff CLP is enabled.
> ```

nit This code serves no purpose (it's not used from anywhere).  Please remove it.
___
*[tools/install/libdrake/BUILD.bazel, line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyCq6Q6NdHbaW9zH3a:-MUyO2Mm-d6uEp4I8cMV:bwl0m4i) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We need `":clp_deps"` here.
</blockquote></details>

OK No actually I'm wrong, there is a different problem (noted above).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[tools/install/libdrake/BUILD.bazel, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyO60C5iKbjGC4ZGgv:-MUyOSNC9J1nY_PU-eNB:b-998pey) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This code serves no purpose (it's not used from anywhere).  Please remove it.
</blockquote></details>

OK Actually, I was right the first time.  We do need this, and should cite it below.
___
*[tools/install/libdrake/BUILD.bazel, line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyCq6Q6NdHbaW9zH3a:-MUyOWNK8G2ffKyxIwuy:ba3r2bv) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK No actually I'm wrong, there is a different problem (noted above).
</blockquote></details>

Actually, on third look -- yes, we do need clp_deps here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: 1 unresolved discussion (waiting on @jamiesnape and @jwnimmer-tri)

___
*[tools/install/libdrake/BUILD.bazel, line 227 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14729#-MUyCq6Q6NdHbaW9zH3a:-MUzuBCH9oPN3lOFZPqj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0dcb1c945e7319fb6d4469c11d0067c4284bd0e/tools/install/libdrake/BUILD.bazel#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually, on third look -- yes, we do need clp_deps here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14729)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),jamiesnape

**Pull request merged**
