### PR TITLE
Retire many more duplicated-word typos

### PR DESCRIPTION
**Pull request by rpoyner-tri**
These were harvested with `pcregrep`, which has perl-compatible regular
expressions. This command gives some raw data:

    $ git ls-files | egrep -v '\.(obj|mtl|sdf|urdf)' \
      | xargs pcregrep -Min --color=auto '\b([a-z][a-z]+)[[:space:]]+\1\b'

Results were curated by hand and many were left untouched, since the regex
filter was insensitive to transitions between comments and text, various
documentation conventions, etc. In some cases, word wrap was updated.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review, Monday schedule. It is fortunate that reviewable does a good job coloring these diffs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533#-:-Mfs9EB-90bGYRm-f0MA:bahwho5)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[tools/vector_gen/test/sample_test.cc, line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15533#-Mfs9bT28Y3BGoKn_ipJ:-Mfs9bT28Y3BGoKn_ipK:b-xrb2n7) ([raw file](https://github.com/robotlocomotion/drake/blob/fe9f84a4077af01d8d9069bdadc4b7ed2294928b/tools/vector_gen/test/sample_test.cc#L128)):*
> ```cpp
>   const double* const original_storage = &first.x();
> 
>   // Note that when we move-construct or move-assign from a prvalue, the size of
> ```

BTW this is the only case where I repaired surrounding words, since the existing text seemed obviously damaged.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: Nice to return from vacation to a fun review for once :-)

> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533#-:-Mg6DLtJE157BnRgETkF:b-3x7i5f)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[common/symbolic_expression_cell.h, line 300 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15533#-Mg6DXDQ3esID6RnHTZH:-Mg6DXDQ3esID6RnHTZI:bqzlbr5) ([raw file](https://github.com/robotlocomotion/drake/blob/fe9f84a4077af01d8d9069bdadc4b7ed2294928b/common/symbolic_expression_cell.h#L300)):*
> ```objc
>  private:
>   /* Adds constant to this factory.
>    * Adding constant into an add factory representing
> ```

minor:  The second "constant" here is a name for the constant mentioned below (`c0 + constant`).  Better to change it to `d` or something?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[common/symbolic_expression_cell.h, line 300 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15533#-Mg6DXDQ3esID6RnHTZH:-Mg6St7d6p7QtOfcUClT:b-dvwutj) ([raw file](https://github.com/robotlocomotion/drake/blob/fe9f84a4077af01d8d9069bdadc4b7ed2294928b/common/symbolic_expression_cell.h#L300)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The second "constant" here is a name for the constant mentioned below (`c0 + constant`).  Better to change it to `d` or something?
</blockquote></details>

Hm, maybe I'll restore it with whatever quoting is appropriate.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[common/symbolic_expression_cell.h, line 300 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15533#-Mg6DXDQ3esID6RnHTZH:-Mg6dGir3BdEczG22PER:bneorm7) ([raw file](https://github.com/robotlocomotion/drake/blob/fe9f84a4077af01d8d9069bdadc4b7ed2294928b/common/symbolic_expression_cell.h#L300)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, maybe I'll restore it with whatever quoting is appropriate.
</blockquote></details>

Using doxygen commands in a private section is :shrug: , but consistent with other blocks in private scope in this class. PTAL.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15533)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @rpoyner-tri)

___
*[common/symbolic_expression_cell.h, line 300 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15533#-Mg6DXDQ3esID6RnHTZH:-Mg6e7BM2ahA9yhQtC9Z:bc085t5) ([raw file](https://github.com/robotlocomotion/drake/blob/fe9f84a4077af01d8d9069bdadc4b7ed2294928b/common/symbolic_expression_cell.h#L300)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Using doxygen commands in a private section is :shrug: , but consistent with other blocks in private scope in this class. PTAL.
</blockquote></details>

You picked the right reviewer, since I thought we should use doxygen format in private sections as well :-)

**Pull request merged**
