### PR TITLE
Construct MinimumDistanceConstraint with a CollisionChecker.

### PR DESCRIPTION
**Pull request by hongkai-dai**
We can now compute the distance through CollisionChecker, and then impose bounds on the minimum distance.

This is a step towards #18830 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@calderpg-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-N_CDaUEAcfs3dUslAO8:b-g27em7)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
Please test using the `CollisionChecker` form of `MinimumDistanceConstraint` to replace the `CollisionAvoidanceConstraint` in anzu. That will also help check if any issues occur when using a different `CollisionChecker` implementation.

> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-N_F-98V4cimp9gnwmkV:b-j6bf77)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EwzdJ7fHjiVJpKZoC:-N_EwzdJ7fHjiVJpKZoD:b-u3irw3) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.h#L149)):*
> ```objc
>       double influence_distance);
> 
>   MinimumDistanceConstraint(const planning::CollisionChecker* collision_checker,
> ```

To support non-OpenMP parallelism, this constructor will need to take an explicit `planning::CollisionCheckerContext` and use that context for all collision checker queries.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EyScC9Dt25omKhtCW:-N_EyScC9Dt25omKhtCX:b-sya7j4) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.cc#L73)):*
> ```cpp
>                           const Eigen::Ref<const Eigen::VectorXd>& x,
>                           double influence_distance_val) {
>   return collision_checker.CalcRobotClearance(x, influence_distance_val)
> ```

Both of these functions will need to take the explicit `planning::CollisionCheckerContext` as well, and use the explicit-context form of collision checker queries, e.g.
```
return collision_checker.CalcContextRobotClearance(context, x, influence_distance_val);
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EwzdJ7fHjiVJpKZoC:-N_F2rtK2PXZnQBC8kcO:bsb5v9p) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.h#L149)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

To support non-OpenMP parallelism, this constructor will need to take an explicit `planning::CollisionCheckerContext` and use that context for all collision checker queries.
</blockquote></details>

Is this signature defective?  Or you are merely requesting that we add one more overload also?

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EwzdJ7fHjiVJpKZoC:-N_F3M_r1qSq4cqGOEQA:bs0h4ko) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.h#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is this signature defective?  Or you are merely requesting that we add one more overload also?
</blockquote></details>

Having both signatures is an option, we did initially provide for both implicit-context and explicit-context collision avoidance constraints in anzu. We then effectively got rid of the implicit-context collision avoidance constraint so there would only be one style of per-thread constraint+context handling. In large part, this came about because it's quite rare to have _only_ a collision avoidance constraint, and having it be possible to create a set of constraints (e.g. for IK) where the collision avoidance constraint used an implicit context while the other constraints used explicitly-provided contexts seemed like a trap.

I would lean towards only providing the explicit context form, and if a user is both very sensitive to the performance implications of creating standalone contexts and really knows what they are doing, there is a bit of an escape hatch/hack to treat a pool context as if it were standalone, e.g.
```
CollisionCheckerContext* pool_context = const_cast<CollisionCheckerContext*>(&collision_checker.model_context());
...
collision_checker.CheckContextConfigCollisionFree(pool_context, q);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EwzdJ7fHjiVJpKZoC:-N_GlJj68S--s3uzxlcW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.h#L149)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Having both signatures is an option, we did initially provide for both implicit-context and explicit-context collision avoidance constraints in anzu. We then effectively got rid of the implicit-context collision avoidance constraint so there would only be one style of per-thread constraint+context handling. In large part, this came about because it's quite rare to have _only_ a collision avoidance constraint, and having it be possible to create a set of constraints (e.g. for IK) where the collision avoidance constraint used an implicit context while the other constraints used explicitly-provided contexts seemed like a trap.

I would lean towards only providing the explicit context form, and if a user is both very sensitive to the performance implications of creating standalone contexts and really knows what they are doing, there is a bit of an escape hatch/hack to treat a pool context as if it were standalone, e.g.
```
CollisionCheckerContext* pool_context = const_cast<CollisionCheckerContext*>(&collision_checker.model_context());
...
collision_checker.CheckContextConfigCollisionFree(pool_context, q);
```
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/minimum_distance_constraint.cc` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-N_EyScC9Dt25omKhtCW:-N_GlKbk2yfdjZI6fHFM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/520bf8829cd3015ea7c7bcfa7c1dc44abc6661a5/multibody/inverse_kinematics/minimum_distance_constraint.cc#L73)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Both of these functions will need to take the explicit `planning::CollisionCheckerContext` as well, and use the explicit-context form of collision checker queries, e.g.
```
return collision_checker.CalcContextRobotClearance(context, x, influence_distance_val);
```
</blockquote></details>

Done.

**Review by calderpg-tri — COMMENTED** [review]
See anzu#10730 for trying this as a replacement for the existing anzu `CollisionAvoidanceConstraint`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NaDszB773L2XQkkQ-SV:b-ikfuov)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Thanks for the anzu PR! I somehow forgot to do this in the anzu side.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NaE-MFv1F2yEtbGw712:b-yk7s5k)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
@calderpg-tri thanks for filing the anzu PR. Now that we have tested it in anzu, shall we work on this Drake PR to get it merged?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-Nah7bZhAqUuYkeqF5hq:b16885j)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
Yes, I will continue my review today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NahBFXw5Ae0JiNBBHGB:b6hjbjt)* status: 3 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 162 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NahBOYP5QqV4yCcPgwt:-NahBOYP5QqV4yCcPgwu:b-e11h3k) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c42e43729bf1b4f3f6a417914f0dbbe9fa3bc42/multibody/inverse_kinematics/minimum_distance_constraint.h#L162)):*
> ```objc
>       planning::CollisionCheckerContext* collision_checker_context,
>       MinimumDistancePenaltyFunction penalty_function = {},
>       double influence_distance_offset = 1);
> ```

As noted in the anzu test PR, this default appears to be questionable. Should we offer some guidance here on what an appropriate value would be?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 3 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 162 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NahBOYP5QqV4yCcPgwt:-NalyGziE_DPp08KEsY4:b-iudpjk) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c42e43729bf1b4f3f6a417914f0dbbe9fa3bc42/multibody/inverse_kinematics/minimum_distance_constraint.h#L162)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

As noted in the anzu test PR, this default appears to be questionable. Should we offer some guidance here on what an appropriate value would be?
</blockquote></details>

Done. I added some documentation.

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 91 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NamCLwaCaI9JQKGCrYY:-NamCLwaCaI9JQKGCrYZ:b-jom4lx) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a444e5b3cb11f735ad819885fd384b8e684186f/multibody/inverse_kinematics/minimum_distance_constraint.h#L91)):*
> ```objc
>   it is used to scale the signed distances between pairs of geometries. Smaller
>   values may improve performance, as fewer pairs of geometries need to be
>   considered in each constraint evaluation. @default 1 meter. The
> ```

I think a better wording for this would be something like
```
The chosen influence_distance_offset can significantly affect the runtime and optimization performance of using
this constraint. Larger values result in more expensive collision checks (since more potential collision candidates
must be considered) and may result in worse optimization performance (the optimizer may not be able to find a
configuration that satisfies the constraint). In work at TRI, we have used much lower values (e.g. 1e-6) for
influence_distance_offset with good results.
```
I think it's important to point out both runtime and optimization consequences.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 91 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NamCLwaCaI9JQKGCrYY:-NamLYJi9WyJoLox82KW:boyexb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a444e5b3cb11f735ad819885fd384b8e684186f/multibody/inverse_kinematics/minimum_distance_constraint.h#L91)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

I think a better wording for this would be something like
```
The chosen influence_distance_offset can significantly affect the runtime and optimization performance of using
this constraint. Larger values result in more expensive collision checks (since more potential collision candidates
must be considered) and may result in worse optimization performance (the optimizer may not be able to find a
configuration that satisfies the constraint). In work at TRI, we have used much lower values (e.g. 1e-6) for
influence_distance_offset with good results.
```
I think it's important to point out both runtime and optimization consequences.
</blockquote></details>

Done. Thanks!

**Review by calderpg-tri — COMMENTED** [review]
:lgtm: feature

> Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NamSIJH2RCnyo55w2fU:bxmhyuf)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks! 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NamT6Ro1MeYxV863ASV:b-qtvf7j)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 
:lgtm: 

> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-Namd1nr4szutQ2zYn27:bdobo2z)* status: 3 unresolved discussions

___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 585 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NamcVjxE8U7fBJzZcbp:-NamcVjyCswv7dUDxH7s:b-1shf79) ([raw file](https://github.com/RobotLocomotion/drake/blob/c77e35f2cc6bc333d5ff23d4599acad07ef6597a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L585)):*
> ```cpp
> 
>   {
>     // Only specify minimum_distance_lower
> ```

btw this comment looks like it should end with a period.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 597 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-Namc_jJ2_zJ_u5guZvd:-Namc_jJ2_zJ_u5guZve:b-1shf79) ([raw file](https://github.com/RobotLocomotion/drake/blob/c77e35f2cc6bc333d5ff23d4599acad07ef6597a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L597)):*
> ```cpp
>                      false);
>     // The two spheres are separated, but the distance is smaller than
>     // minimum_distance_lower
> ```

btw this comment looks like it should end with a period.
___
*[`multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc` line 601 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-NamcbY-Ase_fTwORq04:-NamcbY-Ase_fTwORq05:b-1shf79) ([raw file](https://github.com/RobotLocomotion/drake/blob/c77e35f2cc6bc333d5ff23d4599acad07ef6597a/multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc#L601)):*
> ```cpp
>         dut, Eigen::Vector3d(0, 0, 0),
>         Eigen::Vector3d(0.9 * minimum_distance + 2 * radius_, 0, 0), false);
>     // The distance between the two spheres is above minimum_distance
> ```

btw this comment looks like it should end with a period.

**Comment by jwnimmer-tri** [comment]
What's the plan for python bindings?

**Review by hongkai-dai — COMMENTED** [review]
I will do it separately. I recently added several features into MinimumDistanceConstraint class in C++, will handle them in another pybind PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19760#-:-NanXhYW9xvK724hBnsK:b-ygt0vy)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),calderpg-tri

**Pull request merged**
