### PR TITLE
Add Formula isnan(const Expression& e)

### PR DESCRIPTION
**Pull request by soonho-tri**
Close https://github.com/RobotLocomotion/drake/issues/5415.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5439)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/symbolic_formula_cell.h, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-KeeMHCb8MpBFzImqrF4:-KeeMHCcoIZSrWsLBu73:b-i9vvu) ([raw file](https://github.com/robotlocomotion/drake/blob/385b05efe826a611bde1fa72106b8160ca41ebc8/drake/common/symbolic_formula_cell.h#L374)):*
> ```objc
> std::shared_ptr<FormulaForall> to_forall(const Formula& f);
> 
> /** Casts @p f_ptr of shared_ptr<FormulaIsnan> to @c shared_ptr<FormulaIsnan>.
> ```

I think the first `shared_ptr<FormulaIsnan>` was meant to match the argument type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-:-KeeO9yTnkREbd4xXpSN:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/symbolic_formula_cell.h, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-KeeMHCb8MpBFzImqrF4:-KeeOuXJQL-Kbzc25YnX:b-paz6tz) ([raw file](https://github.com/robotlocomotion/drake/blob/385b05efe826a611bde1fa72106b8160ca41ebc8/drake/common/symbolic_formula_cell.h#L374)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the first `shared_ptr<FormulaIsnan>` was meant to match the argument type.
</blockquote></details>

You mean it should be the following, right?
```
/** Casts @p f_ptr of shared_ptr<FormulaCell> to @c shared_ptr<FormulaIsnan>.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_formula_cell.h, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-KeeMHCb8MpBFzImqrF4:-KeePEbfTChCzUZcGfx3:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/385b05efe826a611bde1fa72106b8160ca41ebc8/drake/common/symbolic_formula_cell.h#L374)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

You mean it should be the following, right?
```
/** Casts @p f_ptr of shared_ptr<FormulaCell> to @c shared_ptr<FormulaIsnan>.
```
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by soonho-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula_cell.h, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-KeeMHCb8MpBFzImqrF4:-KeePeUx4zVXBNbc_xtB:bu9gagv) ([raw file](https://github.com/robotlocomotion/drake/blob/385b05efe826a611bde1fa72106b8160ca41ebc8/drake/common/symbolic_formula_cell.h#L374)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done. Thanks for catching this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by jwnimmer-tri** [comment]
The test failure is real; see `bazel test //drake/tools:sample_test`.

**Comment by soonho-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/tools/test/sample_test.cc, line 83 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5439#-KeeZMDVp28Y1Ofztdl4:-KeeZMDVp28Y1Ofztdl5:balqvve) ([raw file](https://github.com/robotlocomotion/drake/blob/7f987525b3770fcccba8d8e7cd66237db8d792b0/drake/tools/test/sample_test.cc#L83)):*
> ```cpp
>   dut.set_x(x);
>   dut.set_two_word(two_word);
>   EXPECT_TRUE(dut.IsValid().EqualTo(!isnan(x) && !isnan(two_word)));
> ```

Checking string equality was too fragile. Replaced with structural equality check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5439)*

**Pull request merged**
