### PR TITLE
Add Monomial::Evaluate() for a batch of data.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #16982

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984#-:-N-u8vNGBWNFYfFwkEOs:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984#-:-N026vRE7WJVWlT0ieE_:b-n37teh)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/symbolic_monomial.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N0248CBCiNScZ5W8SU4:-N0248CC6rl_Evb6LWxM:b-nt0wqd) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.h#L89)):*
> ```objc
>    * Evaluates the monomial for a batch of data.
>    * We return monomial_vals such that monomial_vals(j) is obtained by
>    * substituting `vars(i)` with `vars_val(i, j)`.
> ```

nit For clarity, is it worth mentioning that `monomial_vars.size()` (or `monomial_vars.rows()`?) will match the `vars_val.cols()`?
___
*[common/symbolic_monomial.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N025-UM9MQZ9ug5b9bR:-N025-UM9MQZ9ug5b9bS:b-yooy6g) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.h#L100)):*
> ```objc
>   Eigen::VectorXd Evaluate(
>       const Eigen::Ref<const VectorX<symbolic::Variable>>& vars,
>       const Eigen::Ref<const Eigen::MatrixXd>& vars_val) const;
> ```

nit I grepped Drake's headers for `'var[a-z]*_val[a-z]*'`.  It seems like `vars_values` might the most typical / most consistent name for this second argument.  What do you think?

My gut feeling is that making this argument name plural (either "vals" or "values") is important, to convey the "batch" nature of the values.
___
*[common/symbolic_monomial.cc, line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N025prH4MQXg2P1G29k:-N025prH4MQXg2P1G29l:b5fke9e) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.cc#L220)):*
> ```cpp
>     }
>   }
>   return monomial_vals.array();
> ```

nit I'm not sure what calling `.array()` on an `ArrayXd` accomplishes?  Does it reuse the storage or something?
___
*[bindings/pydrake/test/symbolic_test.py, line 1164 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N025Zjq6tNWSXsTVO0Z:-N025Zjq6tNWSXsTVO0_:b-o25r1q) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/bindings/pydrake/test/symbolic_test.py#L1164)):*
> ```Python
>         monomial_vals = m.Evaluate(
>             vars=[x, y], vars_val=[[1, 2, 3], [4, 5, 6]])
>         np.testing.assert_array_equal(monomial_vals, [4, 40, 27 * 6])
> ```

nit Maybe it's more obvious / consistent to spell this one out as well?



_Suggestion:_
```Python
8 * 5
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/symbolic_monomial.h, line 89 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N0248CBCiNScZ5W8SU4:-N02D4KyE489lrgg9c-8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.h#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For clarity, is it worth mentioning that `monomial_vars.size()` (or `monomial_vars.rows()`?) will match the `vars_val.cols()`?
</blockquote></details>

Done.
___
*[common/symbolic_monomial.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N025-UM9MQZ9ug5b9bR:-N02DQuV0OUUrOG3d5nv:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.h#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I grepped Drake's headers for `'var[a-z]*_val[a-z]*'`.  It seems like `vars_values` might the most typical / most consistent name for this second argument.  What do you think?

My gut feeling is that making this argument name plural (either "vals" or "values") is important, to convey the "batch" nature of the values.
</blockquote></details>

Done, good call.
___
*[common/symbolic_monomial.cc, line 220 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16984#-N025prH4MQXg2P1G29k:-N02Dno55cZVABU5Dkxd:bxpgao8) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ee8590703162aa7ac89766ad8f116fe5e93e/common/symbolic_monomial.cc#L220)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure what calling `.array()` on an `ArrayXd` accomplishes?  Does it reuse the storage or something?
</blockquote></details>

Done, I made a mistake.

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984#-:-N02EhSFEyJ_n9_6Zuam:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16984#-:-N02GKK4AQmx0IhPLBH_:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
