### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #13942.

Syncs up #21004 vs #21218.

Twin PR: https://github.com/RobotLocomotion/models/pull/56

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21241)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for both reviews per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21241#-:-NuV1e6aAtB55sIFyAIs:biwi6gj)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21241#-NuV1fmVAm9xy20OX06D:-NuV1fmX5too61FSTPF1:b-hll5u3) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f8ab112a284beb706681bde07eb1fa48a0462fd/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "db36e7f710accd86a098c0aa2d446976f975ad8d",
> ```

Working

Needs real sha.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21241#-:-NuVBiF29fbiGM53EYd8:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21241)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21241#-NuV1fmVAm9xy20OX06D:-NuVDMGq2IvCyWOxjx8X:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f8ab112a284beb706681bde07eb1fa48a0462fd/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs real sha.
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21241)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

**Pull request merged**
