### PR TITLE
Rename VectorInterface to VectorBase.

### PR DESCRIPTION
**Pull request by david-german-tri**
We will be adding non-abstract methods to VectorBase as part of #3208.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3214)

### CODE REVIEW

**Comment by david-german-tri** [comment]
+@amcastro-tri for feature review, +@sherm1 for platform review.  This is a boring PR and I would like to get it in as quickly as possible to minimize conflicts.

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-:-KPoA5kJhoOsa5pE1HHs:b-nsmjtq)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-:-KPoB5ZbLPczVNOwaWzB:bnfp4nl)*

**Comment by sherm1** [comment]
Platform: :lgtm: (a few BTWs).

---

Reviewed 51 of 51 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/state.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMOq2xlJCljb3QesA:-KPpMOq2xlJCljb3QesB:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state.h#L13)):*
> ```objc
> #include "drake/systems/framework/state_subvector.h"
> #include "drake/systems/framework/state_vector.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---

*[drake/systems/framework/state_subvector.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMN0tD0SG7xH1NC8h:-KPpMN0tD0SG7xH1NC8i:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_subvector.h#L9)):*
> ```objc
> 
> #include "drake/systems/framework/state_vector.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---

*[drake/systems/framework/state_supervector.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMLpCsdmxteL4F7a1:-KPpMLpCsdmxteL4F7a2:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_supervector.h#L11)):*
> ```objc
> 
> #include "drake/systems/framework/state_vector.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---

*[drake/systems/framework/state_vector.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMBFegj7UEskPYCb9:-KPpMBFegj7UEskPYCbA:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_vector.h#L9)):*
> ```objc
> 
> #include "drake/common/drake_assert.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---

*[drake/systems/framework/primitives/adder.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMjyS37vAIYUeczMV:-KPpMjyS37vAIYUeczMW:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/primitives/adder.h#L11)):*
> ```objc
> #include "drake/systems/framework/system.h"
> #include "drake/systems/framework/system_output.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---

*[drake/systems/framework/primitives/integrator.h, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMoY0RzF6ZZBQuPc9:-KPpMoY0RzF6ZZBQuPcA:bu8zul9) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/primitives/integrator.h#L10)):*
> ```objc
> #include "drake/systems/framework/leaf_system.h"
> #include "drake/systems/framework/system_output.h"
> #include "drake/systems/framework/vector_base.h"
> ```

BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-:-KPpNI11g_v_FbiuBwRv:b-fnjez8)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/state.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMOq2xlJCljb3QesA:-KPrcynV-8kZf-VALTmm:bvzdlu2) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Yes, but it will be used soon (since StateVector is collapsing into VectorBase), so I'll leave it.

---

*[drake/systems/framework/state_subvector.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMN0tD0SG7xH1NC8h:-KPrd2EgwV7blOOLgjLN:bvzdlu2) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_subvector.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Yes, but it will be used soon (since StateVector is collapsing into VectorBase), so I'll leave it.

---

*[drake/systems/framework/state_supervector.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMLpCsdmxteL4F7a1:-KPrdFVQMZpwV521XOge:bvzdlu2) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_supervector.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Yes, but it will be used soon (since StateVector is collapsing into VectorBase), so I'll leave it.

---

*[drake/systems/framework/state_vector.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMBFegj7UEskPYCb9:-KPrdG5_N2fTHm6tqQtm:bvzdlu2) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/state_vector.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Yes, but it will be used soon (since StateVector is collapsing into VectorBase), so I'll leave it.

---

*[drake/systems/framework/primitives/adder.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMjyS37vAIYUeczMV:-KPrdJyACN2DCSEukkSb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/primitives/adder.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Done.

---

*[drake/systems/framework/primitives/integrator.h, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3214#-KPpMoY0RzF6ZZBQuPc9:-KPrdMmxx5gniapwfE8K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edd6c408f3d6980bc175eebebc7e2df92afd1280/drake/systems/framework/primitives/integrator.h#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, you changed the header name but Reviewable says there are no other changes in this file. Does that mean it is unused?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3214)*

**Pull request merged**
