### PR TITLE
Mark lcm_driven_loop_test as flaky

### PR DESCRIPTION
**Pull request by jamiesnape**
See also #5936.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6160)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@siyuanfeng-tri for feature review.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review.

:lgtm:

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6160#-:-KkpmTAWOQc_7IAaskDx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6160)*

**Pull request merged**
