### PR TITLE
doc: Add release notes v0.28.0

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

___
*[doc/_release-notes/v0.28.0.md, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVSxsfiE_dUA41SqoOb:-MVSxsfjCpsKu1Bqsadw:b-78w6mo) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c84145b0140112b1d7afad215b35c9b6f8eb3/doc/_release-notes/v0.28.0.md#L17)):*
> ```Markdown
>   * With this change they will no longer miss those time steps, which may appear to the user as a performance regression or small behaviour change.
> * Disable Drake Visualizer on macOS ([#14605][_#14605])
>   * Drake Visualizer is disabled for at least as long as it takes to transition    Drake and VTK 8.2 to Python 3.9 or some alternative solution is found, see    [#14650][_#14650] for updates.
> ```

nit Weird >1 horizontal whitespace inline in the sentence here (twice).
___
*[doc/_release-notes/v0.28.0.md, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVSyEa2ChORU8yEo_FQ:-MVSyEa2ChORU8yEo_FR:bcdcty8) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c84145b0140112b1d7afad215b35c9b6f8eb3/doc/_release-notes/v0.28.0.md#L91)):*
> ```Markdown
> * None
> 
> ## Build system and dependencies
> ```

Working FYI I'm going to do a small cleanup pass on this section.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[doc/_release-notes/v0.28.0.md, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVSyEa2ChORU8yEo_FQ:-MVT9ZD3BTs1HFqWxsn8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c84145b0140112b1d7afad215b35c9b6f8eb3/doc/_release-notes/v0.28.0.md#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working FYI I'm going to do a small cleanup pass on this section.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
___
*[doc/_release-notes/v0.28.0.md, line 118 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTAnjdB-IxVrD2EMyh:-MVTAnjdB-IxVrD2EMyi:bq6j9wc) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L118)):*
> ```Markdown
> * Upgrade voxelized_geometry_tools to latest commit ([#14728][_#14728])
> 
> ## Newly-deprecated APIs
> ```

nit I think f13c731426fd6c3b20c6c644f8c7ffc695a58ec4 has`@tinyxml` deprecation which got overlooked here.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[doc/_release-notes/v0.28.0.md, line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTZeQy76SEl_52r4bh:-MVTZeQy76SEl_52r4bi:bc3cvvi) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L19)):*
> ```Markdown
>   * With this change they will no longer miss those time steps, which may appear to the user as a performance regression or small behaviour change.
> * Disable Drake Visualizer on macOS ([#14605][_#14605])
>   * Drake Visualizer is disabled for at least as long as it takes to transition Drake and VTK 8.2 to Python 3.9 or some alternative solution is found, see [#14650][_#14650] for updates.
> ```

The upgrade from libsdfromat 9.3.0 to 10.3.0 means that malformed `/sdf//pose` tags are now errors. See relevant changes to `*.sdf` files:
https://github.com/RobotLocomotion/drake/commit/f13c731426fd6c3b20c6c644f8c7ffc695a58ec4

This should be noted here.

On my side - should I've made that release portion more evident?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[doc/_release-notes/v0.28.0.md, line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTZeQy76SEl_52r4bh:-MVT_XFv0UKgWdL2q8oJ:bnnyz4n) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The upgrade from libsdfromat 9.3.0 to 10.3.0 means that malformed `/sdf//pose` tags are now errors. See relevant changes to `*.sdf` files:
https://github.com/RobotLocomotion/drake/commit/f13c731426fd6c3b20c6c644f8c7ffc695a58ec4

This should be noted here.

On my side - should I've made that release portion more evident?
</blockquote></details>

Suggested text:

```md
* The upgrade to libsdformat 10.3.0 means that malformed `<pose/>` elements will now throw an error rather than having erroneous values replaced with zero (e.g. you only specify 5 floats instead of the requires 6, or you use `${pi / 4}` which is not valid in raw SDFormat).
  * You will need to ensure that any malformed `<pose/>` elements are fixed.
```

(Note: The usage of `libsdformat` is intentional to disambiguate it (the software) from the spec, SDFormat)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVTa925EbYITb_Xsra1:b37xsw4) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
> ```Markdown
> Fixes
> 
> * Give better error when mobilizers clash ([#14655][_#14655])
> ```

nit "clash" isn't the most informative description (but does stick w/ PR title); as a naive user, I wouldn't know what a mobilizer is, but I'd know what a joint is.

Can this be made more informative?
e.g. "Improve error message for when there is more than one mobilizer / joint connects a pair of frames."

\cc @rpoyner-tri for better wording?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v0.28.0.md, line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTZeQy76SEl_52r4bh:-MVWQcLK-tWnW2PrF7K-:b-13d9ro) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Suggested text:

```md
* The upgrade to libsdformat 10.3.0 means that malformed `<pose/>` elements will now throw an error rather than having erroneous values replaced with zero (e.g. you only specify 5 floats instead of the requires 6, or you use `${pi / 4}` which is not valid in raw SDFormat).
  * You will need to ensure that any malformed `<pose/>` elements are fixed.
```

(Note: The usage of `libsdformat` is intentional to disambiguate it (the software) from the spec, SDFormat)
</blockquote></details>

Done (with typofix and added link)
___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWQwl6BDkZA8BNnAha:b-1aq11p) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "clash" isn't the most informative description (but does stick w/ PR title); as a naive user, I wouldn't know what a mobilizer is, but I'd know what a joint is.

Can this be made more informative?
e.g. "Improve error message for when there is more than one mobilizer / joint connects a pair of frames."

\cc @rpoyner-tri for better wording?
</blockquote></details>

The error requiring better description (#14641) was precisely for a situation where there were not multiple joints connecting two frames but rather because MBT introduced an extra mobilizer the user did not knowingly request.

So I'll try to reword this a bit, but not with sufficiently clear wording to obscure the nature of the issue :-)
___
*[doc/_release-notes/v0.28.0.md, line 118 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTAnjdB-IxVrD2EMyh:-MVWPkPf0PUFMuWwDcT2:bxdyash) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think f13c731426fd6c3b20c6c644f8c7ffc695a58ec4 has`@tinyxml` deprecation which got overlooked here.
</blockquote></details>

Yup, the deprecation date there was note one of the ones I searched for; good catch!

**Review by ggould-tri — COMMENTED** [review]
+@rpoyner-tri for feature review (next non-Nimmer release shepherd) 
+@ericcousineau-tri (Monday platform reviewer, since I'm today's)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762#-:-MVWThbo23WMfkiMFQ4S:bto9h6v)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762#-:-MVWeZkPB82FG0xQCHWb:bnfp4nl)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @ggould-tri, @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[doc/_release-notes/v0.28.0.md, line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTZeQy76SEl_52r4bh:-MVWbr4m7wgzwcoQQJO2:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Done (with typofix and added link)
</blockquote></details>

OK Thanks!
___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWbv1S0FRVjYDgnJjK:bw209z2) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The error requiring better description (#14641) was precisely for a situation where there were not multiple joints connecting two frames but rather because MBT introduced an extra mobilizer the user did not knowingly request.

So I'll try to reword this a bit, but not with sufficiently clear wording to obscure the nature of the issue :-)
</blockquote></details>

Better, and thanks for clarifying!

But "joint has multiple mobilizers" is still a bit imprecise (hard for me to quickly understand); "typo" is ambiguous.

My read:

* "typo" => "e.g. when users accidentally have the `world` as a child body for a weld joint"?
* "joint has multiple mobilizers" => "implicitly added mobilizers conflict with each other (when users accidentally ...)"? (a bit more precise than "clash"?)

@sherm1 Can you weigh in here?

(As always, feel free to dismiss)
___
*[doc/_release-notes/v0.28.0.md, line 132 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWdNzo8zMbSJegmhyX:-MVWdNzo8zMbSJegmhyY:b-meest7) ([raw file](https://github.com/robotlocomotion/drake/blob/6a36279187135dcd9a60558919950771d24f2647/doc/_release-notes/v0.28.0.md#L132)):*
> ```Markdown
> 
> This release provides [pre-compiled binaries](https://github.com/RobotLocomotion/drake/releases/tag/v0.27.0) named
> ``drake-YYYYMMDD-{bionic|focal|mac}.tar.gz``. See [Nightly Releases](/from_binary.html#nightly-releases) for instructions on how to use them.
> ```

Blocking: Requires date to be updated to release cut, and tag to be updated to 0.27.0.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWfz4_AdAGspoUyo6Y:b-eh71rp) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Better, and thanks for clarifying!

But "joint has multiple mobilizers" is still a bit imprecise (hard for me to quickly understand); "typo" is ambiguous.

My read:

* "typo" => "e.g. when users accidentally have the `world` as a child body for a weld joint"?
* "joint has multiple mobilizers" => "implicitly added mobilizers conflict with each other (when users accidentally ...)"? (a bit more precise than "clash"?)

@sherm1 Can you weigh in here?

(As always, feel free to dismiss)
</blockquote></details>

The way I have been thinking about release notes is that the bullet items should be enough of a teaser to key a user to click through to the pull request, in case they are curious about it.  The items do not need to stand on their own -- there's only so much you can say in a one sentence fragment.  Under that metric, I think the current text looks great.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWgn7I-w88dq2RWYG2:b-5lzu33) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The way I have been thinking about release notes is that the bullet items should be enough of a teaser to key a user to click through to the pull request, in case they are curious about it.  The items do not need to stand on their own -- there's only so much you can say in a one sentence fragment.  Under that metric, I think the current text looks great.
</blockquote></details>

OK SGTM. I guess it's more for the breaking changes to be more user-friendly?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWh6ai7nGgXF7Ck3GJ:b5jbx2u) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK SGTM. I guess it's more for the breaking changes to be more user-friendly?
</blockquote></details>

Yes, the content in the "Announcements" and "Breaking changes" sections should stand on its own more, and take the time to provide more details in this document directly.  It's these list-of-changes sections where I think it's better to stay brief.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVWhzpaEfCk4gup0SKk:blx2ylk) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, the content in the "Announcements" and "Breaking changes" sections should stand on its own more, and take the time to provide more details in this document directly.  It's these list-of-changes sections where I think it's better to stay brief.
</blockquote></details>

(The typo that triggered this for me was putting the arguments to a weld in the wrong order)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWiQdd3FgE98bRAbHS:-MVWiQde3eyyTi5vF4cM:b-vu9o6l) (no related file):*
Let's hold the release on #14769 if it can land in a reasonable timeframe.

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWiQdd3FgE98bRAbHS:-MVWjVF49__IziHcvXiU:bb6mt9b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Let's hold the release on #14769 if it can land in a reasonable timeframe.
</blockquote></details>

:+1:

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762#-:-MVXAS4-CmLEm9pKigZv:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWiQdd3FgE98bRAbHS:-MVYsPnr9LdoMdoQPvXN:b-a568l5) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

That PR has merged now, so when you next refresh this PR please also remove the Breaking Change notice for drake-visualizer.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWiQdd3FgE98bRAbHS:-MVbO9Fe093GbWTfUN8C:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That PR has merged now, so when you next refresh this PR please also remove the Breaking Change notice for drake-visualizer.
</blockquote></details>

Done.

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/_release-notes/v0.28.0.md, line 132 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWdNzo8zMbSJegmhyX:-MVqAenC6XrcQubwQf4L:bz805mn) ([raw file](https://github.com/robotlocomotion/drake/blob/be8b8e00e124249383aaadbc463dca3d911d07de/doc/_release-notes/v0.28.0.md#L132)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Blocking: Requires date to be updated to release cut, and tag to be updated to 0.27.0.
</blockquote></details>

Done (for today's RC)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[doc/_release-notes/v0.28.0.md, line 60 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVTa924C2LA0kapkXUZ:-MVqDrSV2Ba9Tfe4dpC0:bp0h6tz) ([raw file](https://github.com/robotlocomotion/drake/blob/3f29f5f0590e4137c0cbee2323c15d6228af6f27/doc/_release-notes/v0.28.0.md#L60)):*
> (The typo that triggered this for me was putting the arguments to a weld in the wrong order)

OK Yup, understood! The main defect was "how much effort does a user have to go through to figure that out", but that defect was invalidated per convo above. Thanks for clarifying!
___
*[doc/_release-notes/v0.28.0.md, line 132 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14762#-MVWdNzo8zMbSJegmhyX:-MVqDmN85XH-BVs_IA6b:b802lj6) ([raw file](https://github.com/robotlocomotion/drake/blob/be8b8e00e124249383aaadbc463dca3d911d07de/doc/_release-notes/v0.28.0.md#L132)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Done (for today's RC)
</blockquote></details>

OK Sweet!

Briefly verified on my side:
```
$ bazel-bin/tools/release_engineering/download_release_candidate \
...
All versions have the same commit: 306baa8e0fd2a600c7d07c99f85ca1b940877603
+ sha512sum -c *.sha512
drake-20210315-bionic.tar.gz: OK
drake-20210315-focal.tar.gz: OK
drake-20210315-mac.tar.gz: OK
```

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762#-:-MVqIGVMAHxykiVyekl4:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14762)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @ggould-tri)

**Comment by ggould-tri** [comment]
FYI @jamiesnape Release v0.28.0 of git SHA 306baa8 (nightly 20210315) is ready for docker image tag and upload.

**Pull request merged**
