### PR TITLE
Make PortDescriptor move-only

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up on #4616.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4626)

### CODE REVIEW

**Comment by sherm1** [comment]
I like this. You can make it simpler I think -- see BTWs below. :lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2rd1lg6PEjCuGHDrw:-K_2rd1lg6PEjCuGHDrx:bz9hv8p) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/controllers/pid_controlled_system.h#L145)):*
> ```objc
>   /// The return type of ConnectController.
>   struct ConnectResult {
>     /// The feed forward control input,
> ```

BTW, trailing comma.

---

*[drake/systems/framework/diagram.h, line 811 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2tOmExKpLOJ8tV6Gn:-K_2tOmExKpLOJ8tV6Go:b-rcwvn0) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/diagram.h#L811)):*
> ```objc
>         this, this->get_num_input_ports(),
>         subsystem_descriptor.get_data_type(), subsystem_descriptor.size());
>     this->DeclareInputPort(std::move(descriptor));
> ```

BTW, I believe you could just call the two-argument overload here and do away with the rvalue overload altogether:
```c++
DeclareInputPort(subsystem_descriptor.get_data_type(),
    subsystem_descriptor.size());
```
That appears to do the same thing with `this` and the index.

---

*[drake/systems/framework/system.h, line 708 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2txams_bA6WjS7sSQ:-K_2txams_bA6WjS7sSR:b-hrqr7u) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system.h#L708)):*
> ```objc
>   void DeclareInputPort(InputPortDescriptor<T>&& descriptor) {
>     DRAKE_DEMAND(descriptor.get_system() == this);
>     DRAKE_DEMAND(descriptor.get_index() == get_num_input_ports());
> ```

BTW, see my previous comment -- I think you can simply nuke this overload.

---

*[drake/systems/framework/system_port_descriptor.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2sRkDDQzGAerz4eCc:-K_2sRkDDQzGAerz4eCd:b-lxtd2x) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L26)):*
> ```objc
> /// System accepts, on a given port. It is not a mechanism for handling any
> /// actual input data.
> ///
> ```

BTW, API documentation should say `MoveConstructible` but not `MoveAssignable` (ditto for Output).

---

*[drake/systems/framework/system_port_descriptor.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2scTEff09BaLZCILb:-K_2scTEff09BaLZCILc:b-6cm0p5) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L62)):*
> ```objc
>   // semantics to populate a vector, but is non-copyable in order remain the
>   // "one true descriptor" after construction and non-assignable in order to
>   // remain const.  Code that wishes to refer to this descriptor after
> ```

BTW, I like this a lot but it does assume we adopt #4625.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-:-K_2uGxGTZBvxiRLaAtT:b7ohvx0)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_34pnqqU4D2-vOSqkY:bwykv2x) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
> ```objc
> 
>   // Default move-able.
>   InputPortDescriptor(InputPortDescriptor&&) = default;
> ```

BTW, using the default move constructor does not achieve the "one true descriptor" goal you set out below. It would be better to write one that sets the source system pointer to null and the index to something invalid to prevent inappropriate reuse of the moved descriptor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 feature.

---

Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 145 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2rd1lg6PEjCuGHDrw:-K_4pSSO8NM_R20FFIF_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/controllers/pid_controlled_system.h#L145)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, trailing comma.
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 811 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2tOmExKpLOJ8tV6Gn:-K_4vaLghAEXvH9rGQKy:bke8cye) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/diagram.h#L811)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I believe you could just call the two-argument overload here and do away with the rvalue overload altogether:
```c++
DeclareInputPort(subsystem_descriptor.get_data_type(),
    subsystem_descriptor.size());
```
That appears to do the same thing with `this` and the index.

</blockquote></details>

Done.

FTR, this also helped clear up some ambiguous overload resolution that I didn't understand in Valkyrie.  Even when passing two arguments, something didn't exactly match, and GCC was constructing a temporary port and moving it into the single-argument overload?  I don't understand why it was trying that.  The error messages were inscrutable, but are gone now.

---

*[drake/systems/framework/system.h, line 708 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2txams_bA6WjS7sSQ:-K_4vbFt0NnbdOBVWhaw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system.h#L708)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, see my previous comment -- I think you can simply nuke this overload.
</blockquote></details>

Done.

---

*[drake/systems/framework/system_port_descriptor.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2sRkDDQzGAerz4eCc:-K_4ulvR37XTbak93PE2:b-s47m2q) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, API documentation should say `MoveConstructible` but not `MoveAssignable` (ditto for Output).
</blockquote></details>

I tried this a slightly new way, that I think is awesome for both Doxygen format and direct C++ readers.

Also, cppguide steers us to put all ctor/copy/assign/dtor together atop the public section, so I've also done that.

---

*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_4qcDkVoIkOo_ihBOT:bxkndp) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, using the default move constructor does not achieve the "one true descriptor" goal you set out below. It would be better to write one that sets the source system pointer to null and the index to something invalid to prevent inappropriate reuse of the moved descriptor.
</blockquote></details>

Doing so would mean removing the `const` on the member fields.  I am okay with "use-after-move" bugs being the programmer's fault.  I suspect asan would flag it.

---

*[drake/systems/framework/system_port_descriptor.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2scTEff09BaLZCILb:-K_4qlZxYpPpVJETk4VO:b56hm70) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I like this a lot but it does assume we adopt #4625.
</blockquote></details>

Well, it means that we allow MoveConstructible-without-MoveAssignable.  This PR doesn't need to allow CopyConstructible-without-CopyAssignable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-:-K_4pFu64_Qv_V7CNPSD:b1984vs)*

**Comment by sherm1** [comment]
Nice. :lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/system_port_descriptor.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2sRkDDQzGAerz4eCc:-K_5a4yiVeO16eeDFkJw:bblx209) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I tried this a slightly new way, that I think is awesome for both Doxygen format and direct C++ readers.

Also, cppguide steers us to put all ctor/copy/assign/dtor together atop the public section, so I've also done that.
</blockquote></details>

Yeah, that's nice! I like seeing the full litany of potential compiler-generated junk listed explicitly.

---

*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_5aolQLii42TW5R_gl:bodobhb) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Doing so would mean removing the `const` on the member fields.  I am okay with "use-after-move" bugs being the programmer's fault.  I suspect asan would flag it.
</blockquote></details>

Oh I forgot those were const. Might be a good use to const_cast and nuke them here since the descriptor is permanently trashed by the move. But I'm fine with leaving it as more of a spiritual destruction than a physical one.

---

*[drake/systems/framework/system_port_descriptor.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_2scTEff09BaLZCILb:-K_5bEmgPTN7F7W_0-81:b-287k0j) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Well, it means that we allow MoveConstructible-without-MoveAssignable.  This PR doesn't need to allow CopyConstructible-without-CopyAssignable.
</blockquote></details>

Yes, but the style guide is equally obsessed with Move and Copy, so we still need to adopt that clarification.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-:-K_5bbxQxDd9F-bgiNNN:bxsbkqo)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform, please +(priority: low).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_5cD7399bUSPZ3da8c:brapp4) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oh I forgot those were const. Might be a good use to const_cast and nuke them here since the descriptor is permanently trashed by the move. But I'm fine with leaving it as more of a spiritual destruction than a physical one.
</blockquote></details>

I considered that, but had a difficult time convincing myself whether it was UB or not; stackoverflow argued it both ways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-:-K_5c5roQnfHP0kO-3Rf:bfafoh0)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_5daKRDw1_VyI7chIU:b-gg7wc9) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I considered that, but had a difficult time convincing myself whether it was UB or not; stackoverflow argued it both ways.
</blockquote></details>

You are an MMA, @jwnimmer-tri! We are strugging in PAL with "UB" -- translate please?

(Man of Many Acronyms)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_5eUqNB5w_cMX-wIPu:b37zoku) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You are an MMA, @jwnimmer-tri! We are strugging in PAL with "UB" -- translate please?

(Man of Many Acronyms)
</blockquote></details>

Heh, sorry!  Undefined Behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by sherm1** [comment]
*[drake/systems/framework/system_port_descriptor.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4626#-K_34pnqqU4D2-vOSqkX:-K_6Kxo1ds-_Bc5tMwXP:b-4mzeu5) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a3bce107150cb51ad6d58ed66573264fd7836a/drake/systems/framework/system_port_descriptor.h#L48)):*
> I considered that, but had a difficult time convincing myself whether it was UB or not

FWIW, I would do it based on this logic: 
- yes, it is UB but always works in practice
- it is UB of a much more subtle type for a user to re-use a dead descriptor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4626)*

**Comment by jwnimmer-tri** [comment]
The main reason I'm not worried is that it would be super-unusual for anyone to have a moveable descriptor reference.  Most user code only ever sees const-references.

**Pull request merged**
