### PR TITLE
Overloaded operator<< for BasicVector<T>.

### LINKED ISSUE #3884: Consider Making BasicVector Overload `operator<<(string)`.
I currently need to do:

```
std::cout << my_basic_vector.get_value() << std::endl;
```

I would be nice if could do:

```
std::cout << my_basic_vector << std::endl;
```

...by overloading [this method](http://www.cplusplus.com/reference/string/string/operator%3C%3C/).

### PR DESCRIPTION
**Pull request by liangfok**
Closes #3884.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3891)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsGK3GWagB5Ja8f6nm:b-jzcju5)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri :lgtm:.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsGy_ziKu6ov8qoAW0:-KUsGy_ziKu6ov8qoAW1:b-2a5ccg) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
> ```objc
> // debugging purposes.
> template <typename T>
> std::ostream & operator<< (std::ostream &os, BasicVector<T> const &vector) {
> ```

Lots of formatting errors.  The correct formatting is approximately:
`std::ostream& operator<<(std::ostream& os, const BasicVector<T>& vector) {`

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsH8J5ZaQcdDdGsYVW:-KUsH8J64tGrLATrpDCt:bfmoq1p) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
> ```objc
> // debugging purposes.
> template <typename T>
> std::ostream & operator<< (std::ostream &os, BasicVector<T> const &vector) {
> ```

BTW Avoid `vector` as a variable name, because it's also the name of an STL type and can sometimes thus be confusing.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsHLMP-voVs05p4D73:-KUsHLMQL6hJ2vDvZ50f:bhbfwfi) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
> ```objc
> // debugging purposes.
> template <typename T>
> std::ostream & operator<< (std::ostream &os, BasicVector<T> const &vector) {
> ```

Missing `<iostream>` include for `std::ostream`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsHRWG9j32sbaEo6XV:b5mt73j)*

**Comment by liangfok** [comment]
@jwnimmer-tri Thanks. I addressed your comments.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsGy_ziKu6ov8qoAW0:-KUsICBfNxXinRIBV5sB:beozy78) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Lots of formatting errors.  The correct formatting is approximately:
> `std::ostream& operator<<(std::ostream& os, const BasicVector<T>& vector) {`
</details>
Sorry. Fixed.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsH8J5ZaQcdDdGsYVW:-KUsIDHfnAVgpaH1HBs6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Avoid `vector` as a variable name, because it's also the name of an STL type and can sometimes thus be confusing.
</details>
Done.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsHLMP-voVs05p4D73:-KUsIK-0-qwEb4OIIqmA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing `<iostream>` include for `std::ostream`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsIzc_YlGsxjpPPB66:b-8g5dlu)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsGy_ziKu6ov8qoAW0:-KUsK6xMasjTSyyz5P3z:b-8rty11) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Sorry. Fixed.
</details>
Still needs the `const` to precede the `BasicVector`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/basic_vector.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsGy_ziKu6ov8qoAW0:-KUsKRGQb42opCjiSe1o:bc5a45h) ([raw file](https://github.com/robotlocomotion/drake/blob/dc820b4b87d780e551219f00c23caa0ddc29b047/drake/systems/framework/basic_vector.h#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Still needs the `const` to precede the `BasicVector`.
</details>
Oops! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/test/basic_vector_test.cc, line 155 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsKJxfAO1eaHpIrs8w:-KUsKJxgM_qDT49K9Yxj:b6wlc4i) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6840e12e11dc56e93a3b0e85e37f9ba03223ea/drake/systems/framework/test/basic_vector_test.cc#L155)):*
> ```cpp
>   std::stringstream s;
>   s << "hello " << vec << " world";
>   EXPECT_EQ(s.str(), "hello [  1 2.2 3.3] world");
> ```

BTW, consider adding symmetrical trailing space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsKU0BHoDbJPiEdarr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by liangfok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/basic_vector_test.cc, line 155 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsKJxfAO1eaHpIrs8w:-KUsP5KRgB2ox0aF4x7_:bl2tmy0) ([raw file](https://github.com/robotlocomotion/drake/blob/0d6840e12e11dc56e93a3b0e85e37f9ba03223ea/drake/systems/framework/test/basic_vector_test.cc#L155)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, consider adding symmetrical trailing space.
</details>
Done. I changed the way the string is created to avoid doing fancy string manipulation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/systems/framework/basic_vector.h, line 145 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsPKe2Efjt2EwOAGht:-KUsPKe3bynGEaJbdT5Z:b-fmyzdn) ([raw file](https://github.com/robotlocomotion/drake/blob/368f9047cd0e084e70a17c4e928d6cd673f19564/drake/systems/framework/basic_vector.h#L145)):*
> ```objc
> template <typename T>
> std::ostream& operator<<(std::ostream& os, const BasicVector<T>& vec) {
>   std::stringstream s;
> ```

I don't understand why we need a separate stringstream besides `os`?

---

*[drake/systems/framework/basic_vector.h, line 150 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsPURrrzUWlNxOhTeL:-KUsPURsuJOnAucrwQY4:biizkwe) ([raw file](https://github.com/robotlocomotion/drake/blob/368f9047cd0e084e70a17c4e928d6cd673f19564/drake/systems/framework/basic_vector.h#L150)):*
> ```objc
>   for (int i = 0; i < v.size(); ++i) {
>     s << v[i];
>     if (i < v.size() - 1)
> ```

BTW I often find "if (i > 0) { _add-comma_; } " inserted prior to the elemental value to be cleaner to read, instead of the trailing-comma approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsPp_SrwuxL9_dxbPB:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by liangfok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 145 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsPKe2Efjt2EwOAGht:-KUsQTxYZzm4hz_HKTv7:bmnd3zm) ([raw file](https://github.com/robotlocomotion/drake/blob/368f9047cd0e084e70a17c4e928d6cd673f19564/drake/systems/framework/basic_vector.h#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't understand why we need a separate stringstream besides `os`?
</details>
Good point. Removed.

---

*[drake/systems/framework/basic_vector.h, line 150 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-KUsPURrrzUWlNxOhTeL:-KUsQWHdTn5npRDDHnBP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/368f9047cd0e084e70a17c4e928d6cd673f19564/drake/systems/framework/basic_vector.h#L150)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I often find "if (i > 0) { _add-comma_; } " inserted prior to the elemental value to be cleaner to read, instead of the trailing-comma approach.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUsRbgKsImGjhfhT3vA:bnfp4nl)*

**Comment by sherm1** [comment]
@liangfok, when you added `BasicVector::operator<<()` is there a reason you formatted it explicitly rather than punt to the Eigen `operator<<()` for the underlying `Eigen::VectorX`?

**Comment by jwnimmer-tri** [comment]
An earlier version did it that way (check out reviewable).  That version had irregular whitespace in the output (two spaces prior to listing the elements).

**Comment by sherm1** [comment]
Oh, I see. That's because Eigen wants to output vectors in a neat column like Matlab does so it makes all the numbers the same width -- each entry is padded to the width of the widest one. Bracketing and turning it sideways does make it look odd. It's not obvious to me why we would want `operator<<()` to behave differently for BasicVector than it does for VectorX, though, which are also ubiquitous in Drake code. Is there some reason to distinguish them?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUyZHrnWOcMx7jFUKi2:b1wzzdt)*

**Comment by liangfok** [comment]
The only reason I can think of is to conserve vertical screen real estate by printing the vector as a row vector rather than a column vector.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3891#-:-KUygoJYS61uy_ee4W8y:bp1iakd)*

**Pull request merged**
