### PR TITLE
Add and use SingleOutputVectorSource

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a small first portion of #4448.

The base class isn't super-valuable (as discussed in 4448), but might consolidate a few more use cases in the future, and offers at least a little benefit for now.

Mostly, this PR serves as an early example of the other base class(es) I'm working on for 4448, and a way to iterate on the design pattern before scaling up to things like SisoVectorSystem that is much more wide-reaching.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4928)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbS_hsmMvs4c29TkpOT:-KbS_hsnOYwu66zvNace:btb0qvr) ([raw file](https://github.com/robotlocomotion/drake/blob/598e7c0dbc106784740f7a987d554debd6e3353d/drake/systems/primitives/constant_vector_source.h#L42)):*
> ```objc
>   ~ConstantVectorSource() override;
> 
>   using SingleOutputVectorSource<T>::DoCalcOutput;
> ```

This using-statement is required to placate the overloaded-virtual complaint, because there are two DoCalcOutput virtuals.  I had wanted to keep the name the same for clarity, but perhaps this is too high a price to pay?  Would renaming the VectorBlock overload to `DoCalcVectorOutput` be a better answer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for feature review, please.

/CC @russtedrake and @sherm1 if you care.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-:-KbSaPJYL_EbdyFzDu2E:b-olbym4)*

**Comment by david-german-tri** [comment]
I am in favor of this!

---

Reviewed 13 of 15 files at r1.
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/single_output_vector_source.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVN5N764s3gWC74OS1:-KbVN5N8dPOyP8ri0wa9:b-1dopxy) ([raw file](https://github.com/robotlocomotion/drake/blob/598e7c0dbc106784740f7a987d554debd6e3353d/drake/systems/framework/single_output_vector_source.h#L51)):*
> ```objc
>   void DoCalcOutput(const Context<T>& context,
>                     SystemOutput<T>* output) const final {
>     DRAKE_ASSERT_VOID(System<T>::CheckValidOutput(output));
> ```

This is redundant with `System<T>::CalcOutput`, I believe.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbS_hsmMvs4c29TkpOT:-KbVNSeBtKqHJjQ0EP0V:b-gwaw3w) ([raw file](https://github.com/robotlocomotion/drake/blob/598e7c0dbc106784740f7a987d554debd6e3353d/drake/systems/primitives/constant_vector_source.h#L42)):*
> Would renaming the VectorBlock overload to DoCalcVectorOutput be a better answer?

I think yes.

---

*[drake/systems/primitives/trajectory_source.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVNYy-J05tWPWgAkAI:-KbVNYy08boCt1mkGoXJ:bb7r2f0) ([raw file](https://github.com/robotlocomotion/drake/blob/b64822389045acf8941e8083557ff9d27680dae8/drake/systems/primitives/trajectory_source.cc#L4)):*
> ```cpp
> 
> #include "drake/common/drake_assert.h"
> #include "drake/systems/framework/context.h"
> ```

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-:-KbVNqwhuTH-CdWZfamC:b-hvv4ap)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928)*

**Comment by jwnimmer-tri** [comment]
Review status: 9 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/single_output_vector_source.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVN5N764s3gWC74OS1:-KbVQNqWt7xgzyDY9KUK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/598e7c0dbc106784740f7a987d554debd6e3353d/drake/systems/framework/single_output_vector_source.h#L51)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This is redundant with `System<T>::CalcOutput`, I believe.
</blockquote></details>

Done.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbS_hsmMvs4c29TkpOT:-KbVRKBazqJ1vh-ji63Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/598e7c0dbc106784740f7a987d554debd6e3353d/drake/systems/primitives/constant_vector_source.h#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> Would renaming the VectorBlock overload to DoCalcVectorOutput be a better answer?

I think yes.
</blockquote></details>

Done.

---

*[drake/systems/primitives/trajectory_source.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVNYy-J05tWPWgAkAI:-KbVQUWFrSna0prZYM8w:byyry3l) ([raw file](https://github.com/robotlocomotion/drake/blob/b64822389045acf8941e8083557ff9d27680dae8/drake/systems/primitives/trajectory_source.cc#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

why?
</blockquote></details>

DRAKE_DEMAND is used about 10 lines below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.

---

Review status: 9 of 15 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-:-KbVcYhdQPg_99dSHe1m:b-7fek4o)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/trajectory_source.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVNYy-J05tWPWgAkAI:-KbVgJQ70ndJyrYF6E3z:b-p3f56z) ([raw file](https://github.com/robotlocomotion/drake/blob/b64822389045acf8941e8083557ff9d27680dae8/drake/systems/primitives/trajectory_source.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

DRAKE_DEMAND is used about 10 lines below.
</blockquote></details>

No, I meant why the deletion of `context.h`?   (Apparently reviewable transplants previous-diff comments onto the current-diff in a confusing way.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-:-KbVgTin1_9_XBZcT9DF:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/trajectory_source.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVNYy-J05tWPWgAkAI:-KbVk7Ey_pu85LmMY1MA:bk7sabj) ([raw file](https://github.com/robotlocomotion/drake/blob/b64822389045acf8941e8083557ff9d27680dae8/drake/systems/primitives/trajectory_source.cc#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

No, I meant why the deletion of `context.h`?   (Apparently reviewable transplants previous-diff comments onto the current-diff in a confusing way.)
</blockquote></details>

I guess I should have let it alone since its unrelated to this PR.  But per IWYU the "related header" including a file means that the cc file does not also have to include that file (and ours does).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 9 of 15 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/single_output_vector_source.h, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVjufrfQqw_WDSi3sE:-KbVjufrfQqw_WDSi3sF:bef1qyf) ([raw file](https://github.com/robotlocomotion/drake/blob/fc37672be5ec528c456afd616054611f5f3f4284/drake/systems/framework/single_output_vector_source.h#L38)):*
> ```objc
> 
>   // Don't use the indexed get_output_port when calling this system directly.
>   void get_output_port(int) = delete;
> ```

FYI -- I was very surprised to discover that this was possible, and relatedly that this method of System is not virtual.  This seems to violate _is-a_ inheritance style and creates a nontrivial reliance on method non-staticness, which has a touch of code smell to it.  I wonder if it is really necessary.

If this is an intentional and well-considered design, close and dismiss this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-:-KbVuXSp_l65aBvsESZ7:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/single_output_vector_source.h, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4928#-KbVjufrfQqw_WDSi3sE:-KbVwbyr-64vchqibhVQ:bs76gcg) ([raw file](https://github.com/robotlocomotion/drake/blob/fc37672be5ec528c456afd616054611f5f3f4284/drake/systems/framework/single_output_vector_source.h#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- I was very surprised to discover that this was possible, and relatedly that this method of System is not virtual.  This seems to violate _is-a_ inheritance style and creates a nontrivial reliance on method non-staticness, which has a touch of code smell to it.  I wonder if it is really necessary.

If this is an intentional and well-considered design, close and dismiss this comment.
</blockquote></details>

Per f2f, we agree that removing part of the contract is a code smell, but on balance actively preventing people from leaking integers on the floor is a net win.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4928)*

**Pull request merged**
