### PR TITLE
Added Explanation Messages to Matrix Compare Tests.

### PR DESCRIPTION
**Pull request by liangfok**
This is to help diagnose unit test failures.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4038)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Sorry, I PEBKAC'd the close button!

**Comment by jwnimmer-tri** [comment]
What I was going to try to say was that the string error_message is gross.  Why not just write a proper googletest matcher?

**Comment by liangfok** [comment]
Here's to incremental progress....I'll eventually replace this phrasing with a proper GoogleTest matcher.

---

Review status: 0 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4038#-:-KVovnLeh69GGgSakPfV:b-hkdxlq)*

**Comment by jwnimmer-tri** [comment]
Instead of churning all of the call sites with boilerplate code (and thus encouraging new development to use the new boilterplate, to the determent of ongoing new development), how about this incremental improvement instead...

If the `explanation` is `nullptr`, emit the message into a `spdlog` error call.  That way, tests by default will have detailed messages, the required change in this PR is small, and a wide swath of old (and future new code) is left undisturbed?

**Comment by liangfok** [comment]
Great idea. I actually have another WIP branch that goes in that direction. I'll submit it as another PR.

**Pull request closed without merging**
