### PR TITLE
workspace: Add report for new upstream releases

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10573)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The code is pretty well done, but it still needs more documentation before review.

**Comment by jwnimmer-tri** [comment]
Sample output:
```
bullet needs upgrade from 2.87 to 2.88
ccd needs upgrade from 63d3a911f016465a2ecf169d0c8bff8b601f1715 to 7931e764a19ef6b21b443376c699bbc9c6d4fba8
clang_cindex_python3 needs upgrade from 6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5 to 304bfcde0b0284f87667c2444ee46321bc87b60b
fmt needs upgrade from 5.2.1 to 5.3.0
github3_py needs upgrade from 1.3.0 to 1.0.2
ignition_math version faa1749d56e4 needs manual inspection
ignition_rndf version 0e7c72e6f5f4 needs manual inspection
json needs upgrade from v3.4.0 to v3.5.0
meshcat needs upgrade from c7dcbca3af0e76f3c22573076a8d8e54b52dff67 to 33c1213a26d2e05a3b6ca95c7bcb94689f99e005
osqp needs upgrade from v0.4.1 to v0.5.0
sdformat version 2fed80e6bc44 needs manual inspection
spdlog needs upgrade from v1.2.1 to v1.3.1
```

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both feature and platform review, please.  (I'll also try to find a feature second reviewer.)

@jamiesnape Do you want to review this?  Not sure if you want to try to use it under Bionic or not.

Question for the peanut gallery: This doesn't have a regression test.  I could add one (`new_release --help`), but I'd have to guard it to run on Bionic only.  Is it worth it?  Or defer until we hit a pain point, since this is a manual tool anyway?

**Comment by jamiesnape** [comment]
> @jamiesnape Do you want to review this? Not sure if you want to try to use it under Bionic or not.

Sure. I figure we can at least run it in the same job that populates the mirrors once that is up and running (which I think will be soon-ish). That would be a single platform job, and it makes sense for that platform to be bionic.

I think it is fine not to have a regression test.

**Comment by jwnimmer-tri** [comment]
The -lsan and -debug builds are wedged, but shouldn't be relevant to this PR.  Forcing in anyway.

**Pull request merged**
