### PR TITLE
Stop using eigen_matrix_compare in non-test code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4221)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok feature +@david-german-tri platform, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-:-KXC3mgcWniKPWSAmGHx:bc639iy)*

**Comment by liangfok** [comment]
:lgtm: after addressing two minor comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-KXCB4cqKBWFdyavxZC0:-KXCB4cqKBWFdyavxZC1:b4wmwk0) ([raw file](https://github.com/robotlocomotion/drake/blob/c50dfbe5ce67252ae28b1cf53a2329fad323f52c/drake/systems/controllers/linear_optimal_control.cc#L75)):*
> ```cpp
>   DRAKE_DEMAND(Q.rows() == n && Q.cols() == n);
>   DRAKE_DEMAND(R.rows() == m && R.cols() == m);
>   DRAKE_DEMAND((Q - Q.transpose()).lpNorm<Eigen::Infinity>() < 1e-10);
> ```

`<` should be `<=`

---

*[drake/systems/controllers/linear_optimal_control.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-KXCB9pbz4bXGm9qyvuN:-KXCB9pbz4bXGm9qyvuO:b4wmwk0) ([raw file](https://github.com/robotlocomotion/drake/blob/c50dfbe5ce67252ae28b1cf53a2329fad323f52c/drake/systems/controllers/linear_optimal_control.cc#L76)):*
> ```cpp
>   DRAKE_DEMAND(R.rows() == m && R.cols() == m);
>   DRAKE_DEMAND((Q - Q.transpose()).lpNorm<Eigen::Infinity>() < 1e-10);
>   DRAKE_DEMAND((R - R.transpose()).lpNorm<Eigen::Infinity>() < 1e-10);
> ```

`<` should be `<=`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-:-KXCBC5a_NDcDb6x0NTv:b-w7alz8)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-KXCB4cqKBWFdyavxZC0:-KXCBvliP5HTbdfabqVO:b-ejba5g) ([raw file](https://github.com/robotlocomotion/drake/blob/c50dfbe5ce67252ae28b1cf53a2329fad323f52c/drake/systems/controllers/linear_optimal_control.cc#L75)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> `<` should be `<=`
</details>
Why?  (What's the defect?)  I agree that's what the prior code did, but I wouldn't think would matter either way?

---

*[drake/systems/controllers/linear_optimal_control.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-KXCB9pbz4bXGm9qyvuN:-KXCC0hVO7KvLx2Hv6I1:bs4q9op) ([raw file](https://github.com/robotlocomotion/drake/blob/c50dfbe5ce67252ae28b1cf53a2329fad323f52c/drake/systems/controllers/linear_optimal_control.cc#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> `<` should be `<=`
</details>
Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4221)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/linear_optimal_control.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-KXCB4cqKBWFdyavxZC0:-KXCCIW7qDBXbNDPbu6k:b-ctrxqw) ([raw file](https://github.com/robotlocomotion/drake/blob/c50dfbe5ce67252ae28b1cf53a2329fad323f52c/drake/systems/controllers/linear_optimal_control.cc#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Why?  (What's the defect?)  I agree that's what the prior code did, but I wouldn't think would matter either way?
</details>
Just to match the previous semantics. I'll mark as resolved and leave it to your discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4221)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4221#-:-KXCY3mprc4pkLfNz7kr:bnfp4nl)*

**Comment by RussTedrake** [comment]
why this change?  (I understand it's because of the dependency) Getting the matrix compare right is a bit subtle.  perhaps we should instead promote the tool up the dependency graph?

i really dislike the idea of trusting people to use lpNorm correctly everywhere.

**Comment by jwnimmer-tri** [comment]
Did I overlook some hazard of using lpNorm?

I'm happy to have a some helper in `drake/math` or something for doing absolute-tolerance-based comparisons of `Eigen<double, ...>` values.  But his helper was not that.  It computed and logged string error message output for the purposes of unit testing.  I'm also not sure that many of these call sites would have appreciated the "`nan`s compare as equal" in the same way that unit test code would want.

**Comment by RussTedrake** [comment]
the infinity norm is probably a reasonable norm, but do all of our developers understand that it's just a max of the difference?  and it's notationally heavy to invoke everywhere.

nans compare as equal doesn't seem so bad to me.  is there really never a case where the desired value it nan?

**Comment by jwnimmer-tri** [comment]
Alright, I will take another look at the three uses I touched in this PR, to see if either the semantics or mnemonics can be improved.

**Pull request merged**
