### PR TITLE
Helper function for reading protobuf files.

### LINKED ISSUE #5094: Find a neater way to read text-format protobufs
#5014 uses `fnctl.h` to obtain a raw file descriptor, and passes the file descriptor into `google::protobuf::io::FileInputStream`.  I strongly suspect there's a better answer within `google::protobuf` somewhere.  If so, we should find and use it.  If not, we should wrap the file-descriptor approach in a helper class.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #5094.

@siyuanfeng-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5876)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
:lgtm: thanks david! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5876#-:-Ki5mWSqGcVjJIj4lYkX:b-bk36hh)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5876)*

**Comment by david-german-tri** [comment]
+@ggould-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5876#-:-Ki5nkV5ncs0xo9AfQSE:b-gbk9vg)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5876#-:-Ki5ocHDp59giOfvoJcw:bp1lar6)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5876#-:-Ki5p_QXstn6Mqenm-fL:bnfp4nl)*

**Pull request merged**
