### PR TITLE
[workspace] Upgrade rules_python to latest release 0.16.1

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Not expected to pass tests (causes `//:py/install_test` to fail). Needs investigation (@jwnimmer-tri ?). Should be locally reproducible; unfortunately, all CI reports for that test is to see a more detailed log.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18524)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
The more specific failure appears to be:
```
======================================================================
ERROR: test_drake_bazel_installed_test (__main__.InstallTest)
partial(func, *args, **keywords) - new function with partial application
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/.cache/bazel/_bazel_matthew.woehlke/51e544cc7eefa21145ddf6fca5239e3e/sandbox/linux-sandbox/5558/execroot/drake/bazel-out/k8-opt/bin/py/install_test.runfiles/drake/tools/install/install_test.py", line 38, in _run_one_command
    install_test_helper.check_call(
  File "~/drake/tools/install/install_test_helper.py", line 130, in check_call
    return subprocess.check_call(args, cwd='/', env=env, *extra_args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by jwnimmer-tri** [comment]
The error was: `Download from https://github.com/bazelbuild/rules_python/archive/0.16.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 815e666b1e9560c959ca79f2e2c62dd138c73bd8e7d85551e00e136cfd9b6278 but wanted 497ca47374f48c8b067d786b512ac10a276211810f4a580178ee9b9ad139323a`.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

+@rpoyner-tri for both reviews, please.

**Comment by mwoehlke-kitware** [comment]
Sorry for the title churn, didn't notice you'd changed it and thought I'd forgotten the '[WIP]' 😳.

**Comment by mwoehlke-kitware** [comment]
D'oh! Obviously I typo'd the file that was hand-edited 😳. That being the case, should I perhaps put this back into the pile with #18516? Or do you prefer to keep it separate?

**Comment by jwnimmer-tri** [comment]
At this point I think it's easiest to just keep separate, to avoid more churn.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18524#-:-NKtuQ0g-YRIEq05ojhv:bnfp4nl)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-@jwnimmer-tri based on his assertion of SROK above.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18524#-:-NKtuZVc7DD1aU6a6OgR:b8kb3bs)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18524#-:-NKtuiNy7Vaopff4oGPy:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
