### PR TITLE
Add CheckConvexHullProperty to bezier curve

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19302)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
Great to have this test.  I suspect the current failures are due to https://github.com/RobotLocomotion/drake/issues/17197. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-:-NU9VzAy7L4jgc4AIGns:b-vo6cnz)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice and @RussTedrake)

___
*[`common/trajectories/test/bezier_curve_test.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-NU9WSR94tCKOxP9BuFK:-NU9WSR94tCKOxP9BuFL:bxfmty) ([raw file](https://github.com/RobotLocomotion/drake/blob/10af154b6d00ae3bd38d0b29f6058be9667099a2/common/trajectories/test/bezier_curve_test.cc#L21)):*
> ```cpp
>       num_samples, curve.start_time(), curve.end_time());
>   for (int i = 0; i < num_samples; ++i) {
>     EXPECT_TRUE(control_polytope.PointInSet(curve.value(samples(i))));
> ```

this is solving 1000 LPs for each call?  that seems a little much?
maybe worth converting it to HPolyhedron, then running the check on that?

**Review by AlexandreAmice — COMMENTED** [review]
Yes  I think you are right. I looked into the actual failures and they're usually right around 1e-9, but a few are a little higher than that so I added a tolerance to the check.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-:-NUE9G3t5fro16zrfz5r:bz3934n)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice and @RussTedrake)

___
*[`common/trajectories/test/bezier_curve_test.cc` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-NU9WSR94tCKOxP9BuFK:-NUE9PNTCxinUUo5gQTX:bnkc20g) ([raw file](https://github.com/RobotLocomotion/drake/blob/10af154b6d00ae3bd38d0b29f6058be9667099a2/common/trajectories/test/bezier_curve_test.cc#L21)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this is solving 1000 LPs for each call?  that seems a little much?
maybe worth converting it to HPolyhedron, then running the check on that?
</blockquote></details>

Usually converting to HPolyhedron here fails because the control polytope is low dimensional. In the case of a line, `qhull` doesn't have enough points to do the computations it needs to make the conversion.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@jwnimmer-tri for platform review, please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-:-NUPDM-H7BvgVT-YQBeu:b-el6yf3)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @AlexandreAmice and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +(release notes: none).

@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19302#-:-NURwV669cihtfB-r0x3:b-n60ihq)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

**Pull request merged**
