### PR TITLE
Conditionalize testGeometryGradientsComparison (#3224)

### PR DESCRIPTION
**Pull request by ggould-tri**
... because the bug has only occurred in debug.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3368)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@jwnimmer-tri (since he's the one who complained)

This is a sufficiently trivial change that I think we can one-review it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3368#-:-KR06s1BRtxuMwDAyNR_:bkclv2v)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/CMakeLists.txt, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3368#-KR07Gocp6MNrcW8gxFa:-KR07Gocp6MNrcW8gxFb:bsqx12v) ([raw file](https://github.com/robotlocomotion/drake/blob/db469b0fac186b6919c1e47313e48b7458ce1c74/drake/util/test/CMakeLists.txt#L66)):*
> ```CMake
> add_matlab_test(NAME util/test/testGeometryConversionFunctionsComparison COMMAND testGeometryConversionFunctionsComparison)
> # DISABLED due to #3224.
> if (NOT ${CMAKE_BUILD_TYPE} STREQUAL "Debug")
> ```

BTW No whitespace between `if (`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3368#-:-KR07KN72InpSd3Rh9Dz:bnfp4nl)*

**Comment by ggould-tri** [comment]
Well that's a record fast review :-)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/test/CMakeLists.txt, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3368#-KR07Gocp6MNrcW8gxFa:-KR07_bpG-0QY6KxViht:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/db469b0fac186b6919c1e47313e48b7458ce1c74/drake/util/test/CMakeLists.txt#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW No whitespace between `if (`.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3368#-:-KR07PLZSyoi_1g2mm59:b-vpsm8u)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3368)*

**Comment by jwnimmer-tri** [comment]
Tagging #3224 here explicitly; apparently using it in title doesn't make the link.

**Pull request merged**
