### PR TITLE
mkdoc: Enable the developer to specify docstring names

### LINKED ISSUE #12016: pydrake mkdoc: Overload disambiguation
Even with our improvements to mkdoc, there are still times where developers hit the "ambiguous" error message, with no great way forward.  The set of options to resolving the ambiguity is not capable enough.

I propose adding a new Doxygen macro, that allows the user to literally specify the `doc_foo` tag that will be used for that docstring.

For example `@pydrake_doc_name{foobar}` will scrape the docstring into a `doc_foobar` named constant.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #12016.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12081)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.
+@sherm1 for platform review per schedule, please.

**Comment by mpetersen94** [comment]
___
*[bindings/pydrake/systems/controllers_py.cc, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12081#-LpFbuXnDJUA6tvAlhje:-LpFbuXo5kWKmGkWt5oP:b-f9nobh) ([raw file](https://github.com/robotlocomotion/drake/blob/052c9427a67f53018c6f06f93475fb19ecb1ef1e/bindings/pydrake/systems/controllers_py.cc#L110)):*
> ```cpp
>   py::class_<PidControlledSystem<double>, Diagram<double>>(
>       m, "PidControlledSystem", doc.PidControlledSystem.doc)
>       // TODO(mpetersen94): Fix constructor docstrings once #12016 is resolved.
> ```

Can you also remove this todo since this pr addresses it?

**Comment by sherm1** [comment]
___
*[third_party/com_github_pybind_pybind11/mkdoc.py, line 791 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12081#-LpFpUUzAC0nMKd-RTjJ:-LpHOIGG3wde_pzWP-MC:b-v6owgj) ([raw file](https://github.com/robotlocomotion/drake/blob/290f2af61cde69c46a6fbe8df370cc0a0e46b651/third_party/com_github_pybind_pybind11/mkdoc.py#L791)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The point is to error out if the number of variables on the left is not congruent with the number of `(...)` groups within the regexp.  This is, in effect, a direct and robust way to give names to the matches within a regex.

For the assignment syntax, see "sequence unpacking" under https://docs.python.org/3/tutorial/datastructures.html.

`groups()` is https://docs.python.org/3/library/re.html#re.Match.groups, so "Return a tuple containing all the subgroups of the match...".

See also https://treyhunner.com/2018/03/tuple-unpacking-improves-python-code-readability/, which reminds me that I can use `()`s here, which is perhaps more clear that we expect exactly 1 item -- not just the first item.
</blockquote></details>

Thanks for the explanation. I get it now. That's obscure enough that it ought to have a comment in the code. Something like
```
# We're expecting a tuple with just one element; will fail if there are more.
```
would have avoided a lot of confusion.

**Comment by jwnimmer-tri** [comment]
___
*[third_party/com_github_pybind_pybind11/mkdoc.py, line 791 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12081#-LpFpUUzAC0nMKd-RTjJ:-LpIXrhCDnGqA27GGTJx:b-bqees3) ([raw file](https://github.com/robotlocomotion/drake/blob/290f2af61cde69c46a6fbe8df370cc0a0e46b651/third_party/com_github_pybind_pybind11/mkdoc.py#L791)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Thanks for the explanation. I get it now. That's obscure enough that it ought to have a comment in the code. Something like
```
# We're expecting a tuple with just one element; will fail if there are more.
```
would have avoided a lot of confusion.
</blockquote></details>

Do you want me to paste that comment in the 9 other places in Drake, too, and keep pasting it again every new time we use it?
```
./common/test_utilities/drake_py_unittest_main.py:33:    runfiles, test_package, _, test_name, = match.groups()
./common/test/resource_tool_test.py:93:        example_relpath, example_abspath = m.groups()
./tools/install/install.py.in:290:            soname, _, _ = re_result.groups()
./tools/clion/bazel_wrapper:81:            first, filename, rest = match.groups()
./tools/workspace/cmake_configure_file.py:48:        blank, maybe01, var, rest, newline = match.groups()
./tools/workspace/cmake_configure_file.py:62:        before, xvarx, after, newline = match.groups()
./tools/workspace/cmake_configure_file.py:93:    var, value = match.groups()
./tools/workspace/new_release.py:69:    _, git_user, http_user = match.groups()
./bindings/pydrake/doc/pydrake_sphinx_extension.py:96:        symbol, arg, retann = m.groups()
```

So far, the target audience (build system maintainers) seems to be OK without this kind of comment.

@EricCousineau-TRI @jamiesnape. The first time you saw this construct in Drake, did it present a confusion or speed bump?

**Comment by sherm1** [comment]
___
*[third_party/com_github_pybind_pybind11/mkdoc.py, line 791 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12081#-LpFpUUzAC0nMKd-RTjJ:-LpK36oS7C87U25sKmFW:b7unq79) ([raw file](https://github.com/robotlocomotion/drake/blob/290f2af61cde69c46a6fbe8df370cc0a0e46b651/third_party/com_github_pybind_pybind11/mkdoc.py#L791)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do you want me to paste that comment in the 9 other places in Drake, too, and keep pasting it again every new time we use it?
```
./common/test_utilities/drake_py_unittest_main.py:33:    runfiles, test_package, _, test_name, = match.groups()
./common/test/resource_tool_test.py:93:        example_relpath, example_abspath = m.groups()
./tools/install/install.py.in:290:            soname, _, _ = re_result.groups()
./tools/clion/bazel_wrapper:81:            first, filename, rest = match.groups()
./tools/workspace/cmake_configure_file.py:48:        blank, maybe01, var, rest, newline = match.groups()
./tools/workspace/cmake_configure_file.py:62:        before, xvarx, after, newline = match.groups()
./tools/workspace/cmake_configure_file.py:93:    var, value = match.groups()
./tools/workspace/new_release.py:69:    _, git_user, http_user = match.groups()
./bindings/pydrake/doc/pydrake_sphinx_extension.py:96:        symbol, arg, retann = m.groups()
```

So far, the target audience (build system maintainers) seems to be OK without this kind of comment.

@EricCousineau-TRI @jamiesnape. The first time you saw this construct in Drake, did it present a confusion or speed bump? 
</blockquote></details>

No. I've seen many of those other cases and didn't find them confusing. It is the particularly-odd "tuple of one" construct `identifier , =` that we had trouble grokking.

**Comment by jamiesnape** [comment]
> @EricCousineau-TRI @jamiesnape. The first time you saw this construct in Drake, did it present a confusion or speed bump?

Not in the slightest, to be honest.

**Comment by EricCousineau-TRI** [comment]
Yeah, I think once I grokked tuple oddness by itself in Python (e.g. `()` is a tuple, `(x)` isn't, but `(x,)` is), this was pretty straightforward due to iterative assignment.

**Comment by sherm1** [comment]
This makes me think I shouldn't be platform reviewing python code.

**Pull request merged**
