### PR TITLE
Allow mkdoc.py to be run from drake as a bazel external

### LINKED ISSUE #9548: AssertionError: mkdoc.py does NOT exist
PR #9510 broke bazel_drake_external workflows:

```console
ERROR: /home/ubuntu/.tmpfs/bazel_output_base/external/drake/bindings/pydrake/BUILD.bazel:33:1: Couldn't build file external/drake/bindings/pydrake/documentation_pybind.h: error executing shell command: 'bazel-out/host/bin/external/drake/tools/workspace/pybind11/mkdoc $@ > bazel-out/k8-opt/genfiles/external/drake/bindings/pydrake/documentation_pybind.h' failed (Exit 1)
Traceback (most recent call last):
  File "/home/ubuntu/.tmpfs/bazel_output_base/sandbox/linux-sandbox/1/execroot/enabling_anzu/bazel-out/host/bin/external/drake/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/run_mkdoc_with_python3.py", line 23, in <module>
    mkdoc_path = resolve_path('third_party/com_github_pybind_pybind11/mkdoc.py')
  File "/home/ubuntu/.tmpfs/bazel_output_base/sandbox/linux-sandbox/1/execroot/enabling_anzu/bazel-out/host/bin/external/drake/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/run_mkdoc_with_python3.py", line 7, in resolve_path
    assert os.path.exists(abspath), 'Path {} does NOT exist.'.format(abspath)
AssertionError: Path /home/ubuntu/.tmpfs/bazel_output_base/sandbox/linux-sandbox/1/execroot/enabling_anzu/bazel-out/host/bin/external/drake/tools/workspace/pybind11/mkdoc.runfiles/enabling_anzu/third_party/com_github_pybind_pybind11/mkdoc.py does NOT exist.
```

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #9548.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9550)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
I may need to punt that part across to +@EricCousineau-TRI.

**Comment by EricCousineau-TRI** [comment]
Should be handled by some form of d060a582 in #9542.

**Comment by jamiesnape** [comment]
#9542 is in now, so in theory this PR should be ready for review/testing again.

**Comment by jamiesnape** [comment]
Pinging @jwnimmer-tri for review.

**Pull request merged**
