### PR TITLE
Exceptions with improved error messages in SapSolver

### PR DESCRIPTION
**Pull request by amcastro-tri**
We replace DRAKE_DEMANDs with exceptions, with a more informative error messasge to users.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-NyW20V4E8k71HNsA9iG:b-51ktqu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint.  I pushed some fixes where it was easier to just fix style problems than explain it in the review.  I'll continue my review soon.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-NyWsdCEADwcac29pSey:bb37ir8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-NyX0dEX-tLTwpm3VCIb:bnfp4nl)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyX-skIEN7qmvLbrXcL:-NyX-skIEN7qmvLbrXcM:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1a0628e538acfc00b1da3e894a774e1a4e9e6cb/multibody/contact_solvers/sap/sap_solver.cc#L447)):*
> ```cpp
>           "might be negative but close to machine epsilon. Please contact the "
>           "Drake developers and/or open a Drake issue with a minimal "
>           "reproduciton example to help debug your problem.",
> ```

typo



_Code quote:_
```cpp
reproduciton
```
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 452 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyX0Vf83xT4YVlOWyjY:-NyX0Vf9B1ngojplkr_7:bgltcmi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1a0628e538acfc00b1da3e894a774e1a4e9e6cb/multibody/contact_solvers/sap/sap_solver.cc#L452)):*
> ```cpp
> 
>     DRAKE_DEMAND(d2ellA_dalpha2 > 0.0);
>     DRAKE_DEMAND(*d2ell_dalpha2 > 0);
> ```

BTW I don't understand the proof why `(*d2ell_dalpha2 > 0)` is always true?  Could you explain in a comment?
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 718 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyX04Wh-JJb752PcrPV:-NyX04Wh-JJb752PcrPW:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1a0628e538acfc00b1da3e894a774e1a4e9e6cb/multibody/contact_solvers/sap/sap_solver.cc#L718)):*
> ```cpp
>         "believe this is the root cause of your problem, please contact the "
>         "Drake developers and/or open a Drake issue with a minimal "
>         "reproduciton example to help debug your problem.",
> ```

typo



_Code quote:_
```cpp
reproduciton
```

**Review by amcastro-tri — COMMENTED** [review]
Thank you for the commits Jeremy! 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-Ny_PqaW2J4FtkDeisv7:b-ibns2p)* status: needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 452 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyX0Vf83xT4YVlOWyjY:-Ny_P4QH0_GFKsiEau-K:b-vcibw8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1a0628e538acfc00b1da3e894a774e1a4e9e6cb/multibody/contact_solvers/sap/sap_solver.cc#L452)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I don't understand the proof why `(*d2ell_dalpha2 > 0)` is always true?  Could you explain in a comment?
</blockquote></details>

Yes, added a comment. Would you say these DEMANDs serve any purpose? Only some serius bug could trigger them (I guess that'd be the purpose?)

**Review by jwnimmer-tri — COMMENTED** [review]
Okay, PTAL.  I didn't understand the code correctly in the first pass.  New suggestions below.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-NyaHVXz4zowsY9aU2vx:b-bw0etl)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 452 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyX0Vf83xT4YVlOWyjY:-NyaEUOD4E2VhKvnhPNm:b-3uow8y) ([raw file](https://github.com/RobotLocomotion/drake/blob/c1a0628e538acfc00b1da3e894a774e1a4e9e6cb/multibody/contact_solvers/sap/sap_solver.cc#L452)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Yes, added a comment. Would you say these DEMANDs serve any purpose? Only some serius bug could trigger them (I guess that'd be the purpose?)
</blockquote></details>

Thanks, I see now.  All of these variables have such similar names that I lost track of which is which.  (I'm nearly to the point of saying that we should use ℓ as the C++ variable name here; `ell` is extremely difficult to parse out, since it's supposed to act like a single letter, but isn't.)

I would keep the check.  It seems to me like we're validating a post-condition of our math, which our caller is going to rely on.  Better to catch any math errors here, instead of in our caller.  However, I would probably regroup the code to be more cohesive and explain it using that phrasing:

```c++
*d2ell_dalpha2 = d2ellA_dalpha2 + d2ellR_dalpha2;
// Per our API, we must output a strictly positive number. Since we're
// adding strictly positive to non-negative, this should always be true.
DRAKE_DEMAND(*d2ell_dalpha2 > 0);
```
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 432 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyaGAiP5VvpKAcMwIxs:-NyaGAiQ0coFacK4kNqp:b-32zdaq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1a9d9c5f7f7be55d470f27a7d71b6ecfd213cc3/multibody/contact_solvers/sap/sap_solver.cc#L432)):*
> ```cpp
>     *d2ell_dalpha2 = d2ellA_dalpha2 + d2ellR_dalpha2;
> 
>     // Sanity check these terms are all positive.
> ```

nit On a second reading, it feels weird to do the check on this intermediate term _after_ we've computed a silly answer using it.  That's part of what confused me about which check was for what variable.

Wouldn't it be more clear to check the `d2ellR_dalpha2` for sanity immediately after computing it, before we use it to compute `*d2ell_dalpha2`?
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 452 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-NyaE6M854ATQ81cixe2:-NyaE6M91Z4hKLBOUljX:b-1edrlv) ([raw file](https://github.com/RobotLocomotion/drake/blob/b1a9d9c5f7f7be55d470f27a7d71b6ecfd213cc3/multibody/contact_solvers/sap/sap_solver.cc#L452)):*
> ```cpp
> 
>     // N.B. d2ellA_dalpha2 coming as input in SearchDirectionData was already
>     // validated to be strictly positive by CalcSearchDirectionData().
> ```

nit I think this comment and sanity check are probably a benefit (even if only as documentation), but why is it here at this line of code?  If we're reaffirming a sanity check on our function's _input_ argument, then that should be much higher up in this function.  Maybe like this, around line 361:

```c++
const T& d2ellA_dalpha2 = search_direction_data.d2ellA_dalpha2;
// This was already validated to be strictly positive by CalcSearchDirectionData().
DRAKE_ASSERT(d2ellA_dalpha2 > 0.0);
```

Since the re-affirmation is of a fact so nearby (in the same file), using ASSERT feels sufficient to me.

**Comment by jwnimmer-tri** [comment]
BTW I just noticed a related typo during unrelated profiling, in case you want to toss it in here:

This code in `sap_driver.cc`:
```
  if (status != SapSolverStatus::kSuccess) {
    const std::string msg = fmt::format(
        "The SAP solver failed to converge at simulation time = {}. "
```

Some numbered list elements in the error text have newline (`\n`) but some are missing, so the error will be smooshed.

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21470#-:-Nz-R3tl9eNULnMPoPbd:b3dcro0)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
