### PR TITLE
rbtree_py: Add SDF parsing.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
\cc @gizatt

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7789)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@gizatt for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-:-L37-0qK_m82wlzdnb67:b-e4ru6b)*

**Comment by gizatt** [comment]
:lgtm: Thanks for getting this in so quickly! :)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-:-L395FMB8Zur9lajayyv:b-meu0p4)*

**Comment by soonho-tri** [comment]
:lgtm: pending a question.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/rbtree_py.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-L39BzjfgR3y9f-51c4N:-L39BzjfgR3y9f-51c4O:b-i13xop) ([raw file](https://github.com/robotlocomotion/drake/blob/c8950b3a50e1da13ec78af3e6de151968cff1858/bindings/pydrake/rbtree_py.cc#L210)):*
> ```cpp
>         &drake::parsers::urdf::\
>           AddModelInstanceFromUrdfStringSearchingInRosPackages);
>   m.def("AddModelInstancesFromSdfString",
> ```

Can we (or do we need) have a test for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-:-L39C90_yzmnN7XPAx84:b-jbcl3j)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/rbtree_py.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-L39BzjfgR3y9f-51c4N:-L39Lp0yjwkmrK2fo5dx:b-88879f) ([raw file](https://github.com/robotlocomotion/drake/blob/c8950b3a50e1da13ec78af3e6de151968cff1858/bindings/pydrake/rbtree_py.cc#L210)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can we (or do we need) have a test for this?
</blockquote></details>

Done. Went ahead and added, since it was simple. (These tests are more or less for locking in the API, less for doing a full unittest, as that is already done in C++.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7789)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/rbtree_py.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7789#-L39BzjfgR3y9f-51c4N:-L39MmZ_LzyWpv5tWIA2:b-v6rzhl) ([raw file](https://github.com/robotlocomotion/drake/blob/c8950b3a50e1da13ec78af3e6de151968cff1858/bindings/pydrake/rbtree_py.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. Went ahead and added, since it was simple. (These tests are more or less for locking in the API, less for doing a full unittest, as that is already done in C++.)
</blockquote></details>

Nice! Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7789)*

**Pull request merged**
