### PR TITLE
Use venv for Python dependencies (macOS)

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create a series of scripts to set up and manage a Python virtual environment that can be used to build (and test) Drake. Remove Python packages from macOS setup. Add dependencies to the virtual environment as needed. Adjust install test wrapper to use the virtual environment. Adjust macOS wheel builder to set up its own virtual environment only for additional wheel-only packages.

Towards #8392.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Note: this was previously opened as #21844. There is additional history/discussion there.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: small questions

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-:-O9FtudD4qjjaQ-zSV-m:b-36gdej)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`setup/mac/binary_distribution/install_prereqs.sh` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Ft89J8xKN8o7xyzOh:-O9Ft89J8xKN8o7xyzOi:b-mv3nhc) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/setup/mac/binary_distribution/install_prereqs.sh#L76)):*
> ```Shell
> 
> if [[ "${with_python_dependencies}" -eq 1 ]]; then
>   pip3.12 install --break-system-packages -r "${BASH_SOURCE%/*}/requirements.txt"
> ```

nit Is this versioned binary subject to change at relock time? 



_Code quote:_
```Shell
pip3.12
```
___
*[`tools/wheel/macos/build-wheel.sh` line 91 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Fq1hs5uSi79A4Oak-:-O9Fq1hs5uSi79A4Oak0:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/tools/wheel/macos/build-wheel.sh#L91)):*
> ```Shell
> "$python_executable" -m venv "$pyvenv_root"
> 
> # We also need pythonX.Y-config, which isn't created as of writing (see also
> ```

typo



_Suggestion:_
```Shell
of this writing
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`setup/mac/binary_distribution/install_prereqs.sh` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Ft89J8xKN8o7xyzOh:-O9FwBPT0nr_1w0Dfuza:b-wyumn) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/setup/mac/binary_distribution/install_prereqs.sh#L76)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Is this versioned binary subject to change at relock time?
</blockquote></details>

I can't quite follow what you're asking.  Running `venv_upgrade` doesn't interact with this stanza really at all.

The "3.12" here is congruent with our default interpreter which is selected here ...

https://github.com/RobotLocomotion/drake/blob/ec01fba1c950fb626ba90da14abf28c0ed186c3d/setup/mac/binary_distribution/Brewfile#L14

... and cited in many other places.

Or maybe you are asking, if we change to 3.13 as our default, must we run `venv_upgrade` just in case?  Probably yes.
___
*[`tools/workspace/python/repository.bzl` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Fw47c97MDT6yu5dT9:-O9Fw47c97MDT6yu5dTA:benxpkx) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/tools/workspace/python/repository.bzl#L227)):*
> ```Starlark
>     _impl,
>     attrs = interpreter_path_attrs,
>     local = True,
> ```

Working

I should comment why this is here, and/or possibly flip it.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)* status: 2 unresolved discussions, LGTM missing from assignees ggould-tri(platform),jwnimmer-tri(platform)

___
*[`setup/mac/binary_distribution/install_prereqs.sh` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Ft89J8xKN8o7xyzOh:-O9FxyDKDmtsj7MTg_fI:b1tjg9e) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/setup/mac/binary_distribution/install_prereqs.sh#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can't quite follow what you're asking.  Running `venv_upgrade` doesn't interact with this stanza really at all.

The "3.12" here is congruent with our default interpreter which is selected here ...

https://github.com/RobotLocomotion/drake/blob/ec01fba1c950fb626ba90da14abf28c0ed186c3d/setup/mac/binary_distribution/Brewfile#L14

... and cited in many other places.

Or maybe you are asking, if we change to 3.13 as our default, must we run `venv_upgrade` just in case?  Probably yes.
</blockquote></details>

It just looked to me like a buried magic number. I suppose `grep` is good enough for likely rate of change of these versions.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),jwnimmer-tri(platform)

___
*[`setup/mac/binary_distribution/install_prereqs.sh` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Ft89J8xKN8o7xyzOh:-O9G0g_3BVhTy51sNIsm:bfg93ye) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/setup/mac/binary_distribution/install_prereqs.sh#L76)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Perhaps it is "magic", but it isn't being changed by this PR. :shrug: As noted, this instance is synced with the Brew Python version.
</blockquote></details>

It ends up being copy-pasted into maybe 5-10 places, and there's not much we can do to fix that.  CI will yell at us in case it gets unsync'd.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)* status: LGTM missing from assignees ggould-tri(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/python/repository.bzl` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-O9Fw47c97MDT6yu5dT9:-O9GCVyl063mZOqhDJHC:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a44078571f1a02ddc5549dded3e3869e3274681d/tools/workspace/python/repository.bzl#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I should comment why this is here, and/or possibly flip it.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-:-O9GCeq40F16R7UzmNsy:bnfp4nl)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22036#-:-O9G80lH9IDt3ChAQN8d:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release please

**Pull request merged**
