### PR TITLE
[tutorials] Clarify that glTF is our preferred mesh format

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(We will squash this for merge.)

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21509)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I came across this stale doc when doing other work.  This was a good stab at fixing it, and I _think_ I found all of the tutorial bugs re: obj files, but someone should cross-check me.

So let's do +@SeanCurtis-TRI for feature review please, and maybe just push fixes for anything I missed?

**Comment by jwnimmer-tri** [comment]
On second look, maybe we should add a hyperlink to https://drake.mit.edu/doxygen_cxx/group__geometry__file__formats.html from somewhere in here?

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21509#-:-Nz_SuBg5jFOQxQikMO7:bmxilld)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've added some tweaks. PTAL.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21509#-:-Nz_TNot1tR3SwenmiHm:b-c5v6qg)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm: on the edits.

+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21509#-:-NzdXebyApHawXO5QANY:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
