### PR TITLE
Improve error message when MbP meets unknown geometries

### LINKED ISSUE #22164: DiscreteUpdateManager::AppendDiscreteContactPairsForPointContact assumes that it owns all of the geometry
### What happened?

After updating to the most recent Drake version (from 1.30 to 1.34), the example [here](https://github.com/RussTedrake/underactuated/blob/gcs_quadrotor_minimal/book/trajopt/gcs_quadrotor.ipynb) crashes with an extremely unhelpful
```
IndexError: _Map_base::at
```
After a few hours (!!) of printf debugging through building the python bindings, I've narrowed down the problem:
1) the example builds a diagram with both MultibodyPlant and a QuadrotorGeometry added to the same SceneGraph.
2) in `DiscreteUpdateManager::AppendDiscreteContactPairsForPointContact`, the raw calls to 
```
    const BodyIndex body_B_index = geometry_id_to_body_index().at(pair.id_B);
```
throw the error.  Basically, that method is tacitly assuming that all of the geometry belongs to the MbP.
Fyi @xuchenhan-tri , since your name is on those lines of code and @amcastro-tri to triage.

It would take more work for me to come up with a more minimal repro, and I'm afraid I'm out of time for this morning, but I think the incorrectness of this code is now clear? I also haven't bisected enough to know why this appeared for me switching from 1.30 => 1.34... these lines seem older than that, but presumably something upstream in the code path changed.

### Version

(this is reproducible from drake master)

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #22164.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: fix) +(priority: low) +@jwnimmer-tri for feature review when you have time.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-:-OBh2fjh5ZmGiVbZl2I3:bxqto1p)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/discrete_update_manager.h` line 247 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkhira95NepGfOC9Ru:-OBkhira95NepGfOC9Rv:bl4bjj) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/discrete_update_manager.h#L247)):*
> ```objc
> 
>   /* Private MultibodyPlant method, made public here. */
>   BodyIndex FindBodyByGeometryId(geometry::GeometryId geometry_id) const;
> ```

nit On a fresh reading, it seems to me like this declaration should live within the Doxygen group on lines 215-230?  (I think maybe the `EvalGeometryContactData` ended up in the wrong place earlier, too.)
___
*[`multibody/plant/test/discrete_update_manager_test.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkjc83-XiKpb-4ZNOr:-OBkjc83-XiKpb-4ZNOs:bjvvei6) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/test/discrete_update_manager_test.cc#L447)):*
> ```cpp
> 
>   Parser parser(&plant, &scene_graph);
>   parser.AddModelsFromUrl("package://drake_models/skydio_2/quadrotor.urdf");
> ```

I am little bit hesitant to use a model file that's not super related to this test.  If we ever change the model file for other reasons, this test could be unnecessarily affected.

WDYT about something like `multibody/models/box.urdf` instead?
___
*[`multibody/plant/multibody_plant.cc` line 1660 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkiLhQE8sQ2ZNTRmey:-OBkiLhQE8sQ2ZNTRmez:b-g8z2fw) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/multibody_plant.cc#L1660)):*
> ```cpp
>   if (!geometry_id.is_valid()) {
>     throw std::logic_error(
>         "MultibodyPlant::FindBodyByGeometryId received an invalid GeometryId");
> ```

I don't think using the name of a private method in exception text is particularly helpful to users (and usually we try to avoid doing that).

The existing message was not too bad so I would be OK leaving it alone.  If we wanted to try to improve its clarity, the things we could try to highlight more would be that the geometries we're talking about here are for collision pairs reported by the scene graph that's connected to our query input port.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/discrete_update_manager.h` line 247 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkhira95NepGfOC9Ru:-OBm1A5O1t373a0wF6TM:b-4qgxl0) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/discrete_update_manager.h#L247)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit On a fresh reading, it seems to me like this declaration should live within the Doxygen group on lines 215-230?  (I think maybe the `EvalGeometryContactData` ended up in the wrong place earlier, too.)
</blockquote></details>

Good call, Done.
___
*[`multibody/plant/multibody_plant.cc` line 1660 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkiLhQE8sQ2ZNTRmey:-OBm2ZRvBIZLyQ8PXimY:bevftus) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/multibody_plant.cc#L1660)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think using the name of a private method in exception text is particularly helpful to users (and usually we try to avoid doing that).

The existing message was not too bad so I would be OK leaving it alone.  If we wanted to try to improve its clarity, the things we could try to highlight more would be that the geometries we're talking about here are for collision pairs reported by the scene graph that's connected to our query input port.
</blockquote></details>

Done, PTAL.
___
*[`multibody/plant/test/discrete_update_manager_test.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkjc83-XiKpb-4ZNOr:-OBm0FJgBD9g-gUOdvjd:b-lummdp) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/test/discrete_update_manager_test.cc#L447)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am little bit hesitant to use a model file that's not super related to this test.  If we ever change the model file for other reasons, this test could be unnecessarily affected.

WDYT about something like `multibody/models/box.urdf` instead?
</blockquote></details>

My thought process was that `quadrotor.urdf` is a model of an actual hardware so it's less prone to significant hange (e.g. like iiwa and pandas). But after looking more closely, it seems like it's a crude model properly put together for demo purposes?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-:-OBmI8EW1QXHZs4ZJZhn:b-n37teh)* status: needs at least two assigned reviewers

___
*[`multibody/plant/test/discrete_update_manager_test.cc` line 447 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-OBkjc83-XiKpb-4ZNOr:-OBmHxle48BVkCKFwikL:b-s20whp) ([raw file](https://github.com/RobotLocomotion/drake/blob/25c83b494ec2c0c4f0372971a1688f8c04f8213c/multibody/plant/test/discrete_update_manager_test.cc#L447)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

My thought process was that `quadrotor.urdf` is a model of an actual hardware so it's less prone to significant hange (e.g. like iiwa and pandas). But after looking more closely, it seems like it's a crude model properly put together for demo purposes?
</blockquote></details>

I don't know that I can speak to the quadrotor's provenance, but in any case I think using a multibody-test-local model is a nice improvement anyway.

**Review by xuchenhan-tri — COMMENTED** [review]
+@sammy-tri for platform review on Monday per rotation please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-:-OBmZPu01EuleTG8LH7_:b-r70dux)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22178#-:-OC0KHWZEBpPTdlX35Rb:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
