### PR TITLE
Switch to using overloaded functions to add constraints/costs to an OptimizationProblem

### PR DESCRIPTION
**Pull request by sammy-tri**
The intent of this change is to allow (templated) callers which have
been passed a constraint of unknown type as a parameter to add
constraints (costs) to the proper list.

Example:

  template <typename ConstraintT>
  void AddStateConstraint(std::shared_ptr<ConstraintT> constraint,
                          const std::vector<int>& time_indices) {
    for (const int i: time_indices) {
      DRAKE_ASSERT(i < N_);
      opt_problem_.AddConstraint(
          constraint, {x_vars_.segment(i * num_states_, num_states_)});
    }
  }

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3073)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review.  Looking for volunteers for feature review, will add someone in a bit.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KOQjgapu7vlVJK9WCgl:b-1r67fe)*

**Comment by hongkai-dai** [comment]
I can do a feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KOQk0mfVPUrYAwV8GFF:b-22h0s6)*

**Comment by sammy-tri** [comment]
+@david-german-tri for feature review.   @hongkai-dai, your feedback is also (of course) welcome

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KOQk6kF2qL6h130NyK6:b-okusl6)*

**Comment by david-german-tri** [comment]
> The intent of this change is to allow (templated) callers which have
> been passed a constraint of unknown type as a parameter to add
> constraints (costs) to the proper list.

I don't understand how it has that effect.  I'll stop by your desk in a few minutes.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KOR3G0ucSzJFGUMjL49:b-q0q147)*

**Comment by david-german-tri** [comment]
Cleared up in f2f conversation - the key word is "templated".  Consider adding a test case illustrating this.  Otherwise :lgtm: aside from a couple of BTW nits

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/optimization.h, line 174 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-KORDgUTLC5xX0VScu1f:-KOR0vzF9pdWdSzOGBZl:bxr6jos) ([raw file](https://github.com/robotlocomotion/drake/blob/b5381fdaf6aca1c4ab4368a8d9d7e8414b57b997/drake/solvers/optimization.h#L174)):*
> ```objc
> 
>   /**
>    * Add a cost to the problem which covers all decision
> ```

nit: Adds

---

*[drake/solvers/optimization.h, line 288 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-KORDiFrQ0FgniqQWil1:-KOR27zmvkIDcpQYv2hD:b-j21vaa) ([raw file](https://github.com/robotlocomotion/drake/blob/b5381fdaf6aca1c4ab4368a8d9d7e8414b57b997/drake/solvers/optimization.h#L288)):*
> ```objc
> 
>   /**
>    * Add a constraint to the problem which covers all decision
> ```

nit: Adds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KORDXIpd9k1Xxad3Z6E:b-776etn)*

**Comment by sammy-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/optimization.h, line 174 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-KORDgUTLC5xX0VScu1f:-KORGoHVNvlDFVmF3Cqb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5381fdaf6aca1c4ab4368a8d9d7e8414b57b997/drake/solvers/optimization.h#L174)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: Adds
</details>
Done.

---

*[drake/solvers/optimization.h, line 288 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-KORDiFrQ0FgniqQWil1:-KORGpKP0RTXJ9vFwxWZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5381fdaf6aca1c4ab4368a8d9d7e8414b57b997/drake/solvers/optimization.h#L288)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: Adds
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073)*

**Comment by ggould-tri** [comment]
I love the amount of boilerplate-reduction this allows.  This is a big improvement to the API ergonomics.

I don't think a separate test case is needed, as your existing test case changes seem to span the use cases.

:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3073#-:-KOeDq74MD89QjcqLxJ9:bvj46qx)*

**Pull request merged**
