### PR TITLE
Fix sign-compare warnings in optimization_problem_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3083)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
This fixes-forward an "only shows up in minimal" build failure in #3073.

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3083#-:-KOec-KXQcJGhpxssLHv:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3083)*

**Pull request merged**
