### PR TITLE
Update CMakeLists.txt to allow Jammy

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
EWISOTT.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17480)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

I don't know if we have something else acting as the placeholder for "we added Jammy support", so I'm nominating this (hence `release notes: feature`). Feel free to drop the label / replace with `none` if something else is already handling that.

I'm also thinking we may not want to merge this until CI is ready, but it should be fine to go ahead and eyeball the changes, which are anyway pretty minimal.

**Review by jwnimmer-tri — COMMENTED** [review]
Yes, the release notes are good.

:lgtm: +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17480#-:-N5phGOT5-Rso6JXWHCi:b1g074n)* status: 3 unresolved discussions, labeled "do not merge" (waiting on @mwoehlke-kitware)

___
*[`CMakeLists.txt` line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pfOXa-jpkdgkUSkMQ:-N5pfOXa-jpkdgkUSkMR:bq90h2o) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/CMakeLists.txt#L87)):*
> ```CMake
>     message(FATAL_ERROR
>       "Release ${UNIX_DISTRIBUTION_CODENAME} is NOT supported. Please use "
>       "Ubuntu 20.04 (Focal)."
> ```

nit For completeness, both valid options should be echoed back in case of an error.



_Suggestion:_
```CMake
Ubuntu 20.04 (Focal) or Ubuntu 22.04 (Jammy)
```
___
*[`doc/_pages/from_source.md` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pg9e4CYM0uCGgECre:-N5pg9e5-goxE8jDzpbb:b1mlv6l) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L16)):*
> ```Markdown
>      CMakeLists.txt and tools/workspace/cc/repository.bzl. -->
> 
> | Operating System ⁽⁴⁾               | Architecture | Python   | Bazel | CMake | C/C++ Compiler ⁽⁵⁾                 | Java                          |
> ```

nit In the "Compiler" column, we seem to have grown ~3 more whitepsaces on the right than are required.
___
*[`doc/_pages/from_source.md` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pgkZL1Losbmp-jc5f:-N5pgkZL1Losbmp-jc5g:bm7dpo3) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L19)):*
> ```Markdown
> |------------------------------------|--------------|----------|-------|-------|------------------------------------|-------------------------------|
> | Ubuntu 20.04 LTS (Focal Fossa)     | x86_64 ⁽¹⁾   | 3.8 ⁽³⁾  | 5.1   | 3.16  | GCC 9.3 (default) or Clang 12      | OpenJDK 11                    |
> | Ubuntu 22.04 LTS (Jammy Jellyfish) | x86_64 ⁽¹⁾   | 3.10 ⁽³⁾ | 5.1   | 3.22  | GCC 11.2 (default) or Clang 12     | OpenJDK 11                    |
> ```

nit Somewhere on this Jammy line, we should have a footnote callout to highlight the fact that:

```
(⁶) Ubuntu 22.04 (Jammy Jellyfish) builds are only supported from source.
Drake does not yet publish binaries for this platform.
```



_Suggestion:_
```Markdown
(Jammy Jellyfish)⁶
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17480)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`CMakeLists.txt` line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pfOXa-jpkdgkUSkMQ:-N5uEePj12_JXz5YD6-I:b3k9jk6) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/CMakeLists.txt#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For completeness, both valid options should be echoed back in case of an error.
</blockquote></details>

Ack :flushed:. Fixed; thanks!
___
*[`doc/_pages/from_source.md` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pg9e4CYM0uCGgECre:-N5uEiiXEyEWncqX1kjN:b-i4j5c5) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In the "Compiler" column, we seem to have grown ~3 more whitepsaces on the right than are required.
</blockquote></details>

I didn't change that AFAICT. But yeah, probably we don't need that extra space. Removed.
___
*[`doc/_pages/from_source.md` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pgkZL1Losbmp-jc5f:-N5uF55G3BPMKtkPhdvD:b41k8ve) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Somewhere on this Jammy line, we should have a footnote callout to highlight the fact that:

```
(⁶) Ubuntu 22.04 (Jammy Jellyfish) builds are only supported from source.
Drake does not yet publish binaries for this platform.
```

</blockquote></details>

Is that not going to get reverted almost immediately?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17480)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @mwoehlke-kitware)

___
*[`doc/_pages/from_source.md` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pgkZL1Losbmp-jc5f:-N5uLRvhC2kFlnZ_sb9T:b-m4n22b) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L19)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Is that not going to get reverted almost immediately?
</blockquote></details>

_Hopefully_ that will happen within a few weeks, yes.  (At which point we still also add links to monthly binaries and update the supported platforms table at https://drake.mit.edu/installation.html.)

In the meantime, we do still need to keep our website accurate. Since we don't even have Jammy Packaging build defined in CI yet, I'm not comfortable putting inaccurate information on the website for an indefinite period of time.

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/from_source.md` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pgkZL1Losbmp-jc5f:-N5uOEEL0eaTFcOXjxaJ:bol1azb) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Hopefully_ that will happen within a few weeks, yes.  (At which point we still also add links to monthly binaries and update the supported platforms table at https://drake.mit.edu/installation.html.)

In the meantime, we do still need to keep our website accurate. Since we don't even have Jammy Packaging build defined in CI yet, I'm not comfortable putting inaccurate information on the website for an indefinite period of time.
</blockquote></details>

Okay. But the reason I ask goes to "I'm also thinking we may not want to merge this until CI is ready". IOW, can we live with CMake being broken for a week or so for the sake of less churn? (Do we really even "support" from-source builds with no CI?)

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/from_source.md` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17480#-N5pgkZL1Losbmp-jc5f:-N5uQ8GgBqhJXgd6tL03:buqjykg) ([raw file](https://github.com/robotlocomotion/drake/blob/a242587c0d15348d0297f7e3618a5b4af7378e56/doc/_pages/from_source.md#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's fine to stash the doc change until later.  The CMake changes should go in ASAP to that we can green CI so that we can can add Jammy to the Production tab.
</blockquote></details>

Okay, that was going to be my next suggestion. Pushing now...

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17480)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
