### PR TITLE
Improve documentation for RigidBody::SetCenterOfMassInBodyFrame()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18251)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18251 is part of resolution towards issue #17571.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18251#-:-NG-IZxf1SvfmMCD50zP:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature pass done with a few comments, ptal.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18251#-:-NG4-E9c6LRBPldhnfm2:bu9fr90)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 218 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18251#-NG3yTxJDkUaBFAASM4I:-NG3yTxJDkUaBFAASM4J:b-oxrgr0) ([raw file](https://github.com/robotlocomotion/drake/blob/9dab7055a49e6a5c6163a7073bb80e1e730f9436/multibody/tree/rigid_body.h#L218)):*
> ```objc
>   /// in B). If needed, use SetSpatialInertiaInBodyFrame().
>   void SetCenterOfMassInBodyFrame(systems::Context<T>* context,
>                                   const Vector3<T>& p_BoBcm_B) const {
> ```

minor: Parameter names become visible in the Python bindings and should be the same here and there so that the auto-generated documentation is right. Please check what the bindings look like. 

Also, consider whether putting the frame and point names in the parameter name is actually an improvement -- you recently went the other direction due to the problem at the calling site where the user may be using a different frame name. (Might not matter here since there is only a single frame involved so not hard to translate. And we already have M_Bo_B below. I'm just mentioning it to make sure you've thought it through.)
___
*[`multibody/tree/rigid_body.h` line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18251#-NG3zsLfEE3sS50l2ivD:-NG3zsLfEE3sS50l2ivE:b-3j7sgw) ([raw file](https://github.com/robotlocomotion/drake/blob/9dab7055a49e6a5c6163a7073bb80e1e730f9436/multibody/tree/rigid_body.h#L235)):*
> ```objc
> 
>   /// For `this` rigid body B, sets its spatial inertia that is stored in
>   /// @p context to @p M_BBo_B.
> ```

minor: this symbol doesn't match the parameter name M_Bo_B, which is entirely adequate here! If you do feel compelled to toss in a redundant "B", be sure to synchronize (and possible deprecate) the Python binding where the parameter name is a kwarg and hence part of the signature.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18251)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/tree/rigid_body.h` line 218 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18251#-NG3yTxJDkUaBFAASM4I:-NGJk2eNChvL88eZRxT1:b-hsjgxm) ([raw file](https://github.com/robotlocomotion/drake/blob/9dab7055a49e6a5c6163a7073bb80e1e730f9436/multibody/tree/rigid_body.h#L218)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: Parameter names become visible in the Python bindings and should be the same here and there so that the auto-generated documentation is right. Please check what the bindings look like. 

Also, consider whether putting the frame and point names in the parameter name is actually an improvement -- you recently went the other direction due to the problem at the calling site where the user may be using a different frame name. (Might not matter here since there is only a single frame involved so not hard to translate. And we already have M_Bo_B below. I'm just mentioning it to make sure you've thought it through.)
</blockquote></details>

Done.  Reverting to "com" so I do not need to deprecate Python bindings.
___
*[`multibody/tree/rigid_body.h` line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18251#-NG3zsLfEE3sS50l2ivD:-NGJiIXx76Jua_prc5Fh:b-y4vu5) ([raw file](https://github.com/robotlocomotion/drake/blob/9dab7055a49e6a5c6163a7073bb80e1e730f9436/multibody/tree/rigid_body.h#L235)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this symbol doesn't match the parameter name M_Bo_B, which is entirely adequate here! If you do feel compelled to toss in a redundant "B", be sure to synchronize (and possible deprecate) the Python binding where the parameter name is a kwarg and hence part of the signature.
</blockquote></details>

Done.  Best ROI here seems to be lose the redundant "B".

**Review by sherm1 — COMMENTED** [review]
Nice, thanks! :lgtm: x 2

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18251#-:-NGOBz0pEPXSSLbICS1G:b-i4r9po)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
