### PR TITLE
pydrake doc: Add `pydrake_system` directive to Sphinx

### LINKED ISSUE #12590: implement system diagrams for pydrake documentation
The nice html diagrams that we have for doxygen result in a totally scare mess for pydrake users.  
For example:
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html
vs 
https://drake.mit.edu/pydrake/pydrake.multibody.plant.html#pydrake.multibody.plant.MultibodyPlant_

The doxygen code for this is just a very simple set of (recursive) aliases here:
https://github.com/RobotLocomotion/drake/blob/master/doc/Doxyfile_CXX.in#L43

Presumably we could write a simple script that does this work somewhere around `generate_pybind_documentation_header`?

Also, note that we occasionally use html tags in our doxygen (including the multibodyplant example above) which, left unrendered, is not only messy but makes it impossible to parse ideas like "the green output ports do X".  Is there a better way for sphinx to handle those html tags?

Note: we regularly receive feedback (e.g. from students) that the pydrake documentation needs a lot of work.  I'll try to open some issues for ideas of possible "low hanging fruit" that might go a long way to improving that experience.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Have mkdoc_comment use this directive

Resolves #12590

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for feature review, please.
+@jwnimmer-tri for platform review, please.

Is it possible to make this just a high-level review? I kinda burned my time budget on this one.

FYI @russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500#-:-MQOyaOODFqJXbpQp2vz:b42a5tw)* status: LGTM missing from assignees jamiesnape,jwnimmer-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),jamiesnape (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQOz0o50qsgl_gchvI2:-MQOz0o64Z3ah3J9oLXT:b-eq0zce) (no related file):*
Working: Requires #14499 

---

**Comment by jwnimmer-tri** [comment]
The CI problems seem like they are a true positive, and not due the recent infrastructure hiccups.

**Comment by EricCousineau-TRI** [comment]
Fixed. There is probably a root cause to why an element from the total was dropped, unsure if it's good or bad, but I don't have sufficient time/stake to investigate.

Can defer to an issue if reviewers would like.

**Comment by jamiesnape** [comment]
Maybe I am misinterpreting the CSV column names, but I would expect one value to change (and it did), so the defect is either my understanding or in the coverage code, i.e., not this PR.

**Comment by jamiesnape** [comment]
That was assuming the code would pass. I think one value should change by one in the denominator is what I am saying I thought should happen.

**Comment by EricCousineau-TRI** [comment]
Derp :facepalm: Yeah, you're right. I updated the regression file.

**Review by jwnimmer-tri — COMMENTED** [review]
For the record, this PR does _not_ require macOS CI testing; doc builds are not supported on macOS anymore.

> Reviewed 5 of 6 files at r1, 6 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500#-:-MQSu8VP4wmW9IuUmQRf:b-81gmmo)* status: 7 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),jamiesnape (waiting on @EricCousineau-TRI and @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSxa7_EI4Zk6zylj7c:-MQSxa7_EI4Zk6zylj7d:b-jgtex0) (no related file):*
There are way too many lint errors on the lint-ignored file changed in this PR.  I was marking them all, but decided to just turn on the linter instead.

Please add this patch into this PR:

```patch
--- a/doc/BUILD.bazel
+++ b/doc/BUILD.bazel
@@ -105,8 +105,12 @@
     python_lint_exclude = [
         ":conf.py",
         # The following needs the executable flag to be run by doxygen, but the
-        # linter complains:
+        # linter complains.  We'll check separately via python_lint_extra_srcs,
+        # which doesn't apply the executable check.
+        ":system_doxygen.py",
+    ],
+    python_lint_extra_srcs = [
+        ":doxygen.py",
         ":system_doxygen.py",
     ],
-    python_lint_extra_srcs = [":doxygen.py"],
 )
```

---
___
*[bindings/pydrake/doc/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSsFyb8wrH-7DLrcma:-MQSsFyb8wrH-7DLrcmb:b-ihwl2r) ([raw file](https://github.com/robotlocomotion/drake/blob/be1b13953e58c2f55fd67b33619e1166c6d36125/bindings/pydrake/doc/BUILD.bazel#L37)):*
> ```Starlark
>         "//bindings/pydrake",  # We must import `pydrake` to document it.
>         "//doc:sphinx_base",
>         "//doc:system_doxygen",
> ```

nit It took me a few minutes to track this down.  This build file would much clearer if `pydrake_sphinx_extension` were a `py_library` with its own deps, which then `gen_sphinx` would declare as `data` or `deps`?
___
*[bindings/pydrake/doc/pydrake_sphinx_extension.py, line 392 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSvjNlCdQVP8ycvpm9:-MQSvjNlCdQVP8ycvpmA:bil6ue3) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/bindings/pydrake/doc/pydrake_sphinx_extension.py#L392)):*
> ```Python
>             raise self.severe(f"pydrake_system error: {e}")
>         raw_content = indent(system_html.strip(), '   ')
>         raw_rst = f".. raw:: html\n\n{raw_content}"
> ```

This seems to re-implement `system_yaml_to_rst_directive` instead of calling it, even though that function is unit tested and this one isn't?
___
*[doc/system_doxygen.py, line 95 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSyC1G6-thuqTRXEBw:-MQSyC1G6-thuqTRXEBx:bxcdm1s) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/doc/system_doxygen.py#L95)):*
> ```Python
> 
> 
> def process_doxygen_system_tags(s):
> ```

nit Missing docstring.  (This function name on its own is not clear enough to exist as a public symbol without an explanation of its semantics.  Either the function name needs more specificity, or we need a short docstring.)
___
*[tools/workspace/pybind11/test/mkdoc_comment_test.py, line 335 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSrwX342NsUyb9vIhW:-MQSrwX342NsUyb9vIhX:b-de4gpy) ([raw file](https://github.com/robotlocomotion/drake/blob/be1b13953e58c2f55fd67b33619e1166c6d36125/tools/workspace/pybind11/test/mkdoc_comment_test.py#L335)):*
> ```Python
> 
>     def test_doxygen_system_tags(self):
>         # First line is required to parse system tags correctly
> ```

nit Missing punctuation.
___
*[tools/workspace/pybind11/test/mkdoc_comment_test.py, line 337 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSrybBAqA1eMS5rid0:-MQSrybBAqA1eMS5rid1:bur57d9) ([raw file](https://github.com/robotlocomotion/drake/blob/be1b13953e58c2f55fd67b33619e1166c6d36125/tools/workspace/pybind11/test/mkdoc_comment_test.py#L337)):*
> ```Python
>         # First line is required to parse system tags correctly
>         # This line must be non-empty, or reflow logic does not work as
>         # intendend.
> ```

nit Typo `intendend`.
___
*[tools/workspace/pybind11/test/sample_header.h, line 365 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSrOWVCTyKr3yecwv5:-MQSrOWW05pzt59ebxjq:b-rqsk54) ([raw file](https://github.com/robotlocomotion/drake/blob/be1b13953e58c2f55fd67b33619e1166c6d36125/tools/workspace/pybind11/test/sample_header.h#L365)):*
> ```objc
> }
> 
> // N.B. Breaking commment styles will cause parsing to break (#14498).
> ```

nit Typo `commment`.

**Review by jamiesnape — COMMENTED** [review]
I am fine with this modulo all the open discussions. The non-typo nits I might have blocked on, but otherwise. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500#-:-MQTXeVS5Izz-4acEwsA:b-i47aom)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

___
*[tools/workspace/pybind11/test/generate_pybind_coverage_test.py, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQTXKReATTrRBAdP2S_:-MQTXKReATTrRBAdP2Sa:b-2f13qg) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/tools/workspace/pybind11/test/generate_pybind_coverage_test.py#L4)):*
> ```Python
> Regression tests for coverage.
> 
> To regenerate regression artifacts, run the following (after the test fails):
> ```

BTW That would be a test failing not due to a regression, of course.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSxa7_EI4Zk6zylj7c:-MQUCkbTDssr_oMYzGYI:b-klo5sx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There are way too many lint errors on the lint-ignored file changed in this PR.  I was marking them all, but decided to just turn on the linter instead.

Please add this patch into this PR:

```patch
--- a/doc/BUILD.bazel
+++ b/doc/BUILD.bazel
@@ -105,8 +105,12 @@
     python_lint_exclude = [
         ":conf.py",
         # The following needs the executable flag to be run by doxygen, but the
-        # linter complains:
+        # linter complains.  We'll check separately via python_lint_extra_srcs,
+        # which doesn't apply the executable check.
+        ":system_doxygen.py",
+    ],
+    python_lint_extra_srcs = [
+        ":doxygen.py",
         ":system_doxygen.py",
     ],
-    python_lint_extra_srcs = [":doxygen.py"],
 )
```
</blockquote></details>

Done. Took a different (more explicit) route, but to the same effect (file obeys pycodestyle).

---
___
*[bindings/pydrake/doc/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSsFyb8wrH-7DLrcma:-MQUCt-Y2s0iB1dIa6LY:b35wj23) ([raw file](https://github.com/robotlocomotion/drake/blob/be1b13953e58c2f55fd67b33619e1166c6d36125/bindings/pydrake/doc/BUILD.bazel#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a few minutes to track this down.  This build file would much clearer if `pydrake_sphinx_extension` were a `py_library` with its own deps, which then `gen_sphinx` would declare as `data` or `deps`?
</blockquote></details>

Done. Good point!
___
*[bindings/pydrake/doc/pydrake_sphinx_extension.py, line 392 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSvjNlCdQVP8ycvpm9:-MQUAuYZBQ1Fjj5wsb_x:b7z1pnm) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/bindings/pydrake/doc/pydrake_sphinx_extension.py#L392)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems to re-implement `system_yaml_to_rst_directive` instead of calling it, even though that function is unit tested and this one isn't?
</blockquote></details>

OK I don't think so?

`system_yaml_to_rst_directive` generates the `.. pydrake_system::` reST code.
This function, on the other hand, translates to `.. raw:: html` reST code.

Renamed the `system_yaml_...` to try and delineate that better, tho.
___
*[doc/system_doxygen.py, line 95 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQSyC1G6-thuqTRXEBw:-MQUD0CT1wNgxKKiYp0h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/doc/system_doxygen.py#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing docstring.  (This function name on its own is not clear enough to exist as a public symbol without an explanation of its semantics.  Either the function name needs more specificity, or we need a short docstring.)
</blockquote></details>

Done.
___
*[tools/workspace/pybind11/test/generate_pybind_coverage_test.py, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQTXKReATTrRBAdP2S_:-MQUD1jmC8XS05iOutcS:bzht8ec) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/tools/workspace/pybind11/test/generate_pybind_coverage_test.py#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW That would be a test failing not due to a regression, of course.
</blockquote></details>

OK Yuppers. Will leave that comment out, though, as I think that's obvious by the context?

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/pybind11/test/generate_pybind_coverage_test.py, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14500#-MQTXKReATTrRBAdP2S_:-MQXNRiBBcNDP_uXiuxh:buedgvj) ([raw file](https://github.com/robotlocomotion/drake/blob/a3480037a6fe59de83f2234e1bb2142203c09682/tools/workspace/pybind11/test/generate_pybind_coverage_test.py#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yuppers. Will leave that comment out, though, as I think that's obvious by the context?
</blockquote></details>

You would hope so....

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14500)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

Oops, I never badged this -- :lgtm: platform.  I'm not previewing locally, assuming feature review already did that.

**Comment by jamiesnape** [comment]
Somehow this put a build or test dependency on Sphinx, so CI has broken. I guess that is my fault for missing it in review.

**Pull request merged**
