### PR TITLE
MakeConvexHull now supports glTF files

### LINKED ISSUE #21091: Compute convex hull of glTF file
`PlanarSceneGraphVisualizer` visualizes complex meshes by computing their convex hull and projecting them onto a plane. As we upgrade our visualization geometries from .obj to .glTF the implementation that computes the convex hull is insufficient. `PlanarSceneGraphVisualizer` currently requires .obj files. glTF is not supported at all.

However, a utility function that can take a `Mesh("foo.gltf", scale)` and create a convex hull representation, bound in python, would be sufficient for `PlanarSceneGraphVisualizer` to be able to make use of glTF files.

Recent PRs (#21012 and #21066) created such a function (albeit in `internal::` namespace). That function operates on .obj and (volume) .vtk files. We just need to extend it to include .gltf files.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
We're using VTK to parse the glTF file. For VTK's parser to work, it needs VTK's OpenGl2 rendering artifacts initialized. This required moving VTK module initialization out of `internal_render_engine_vtk.cc` and into its own compilation unit to be shared.

The convex hull API is exercised in `planar_scenegraph_visualizer`.

While C++'s `MakeConvexHull()` could probably be promoted to part of the stable API, that decision is being deferred for now. It is bound as `_MakeConvexHull`.

Resolves #21091.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-NsoKu5_6A45jK6_u7fH:b-l8xbmn)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri, willing to do feature review?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-NsoKzqj3HdL1VL2v8oO:b-dxud5w)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
Sure.  FYI CI has some minor complaints (it doesn't look like they are relevant for review, so I'll start now).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-NsoRLLR4gSFSo8kSy3n:b-3n7c7t)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.  I'll wait to assign platform until after the unit test question.

I manually tested `bazel run //tools:model_visualizer -- --pyplot package://drake_models/tri_homecart/homecart.dmd.yaml` to see how the visualizer worked, and it looked fine.  (The chull of the homecart is somewhat hilarious, given that it's a big cage.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-NsoYGmN5325dMv8XnIS:b-2ek6nj)* status: 5 unresolved discussions, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-NsoVHuwCQNH8iv_5-v-:-NssOLtd25WySPCMgrkl:b-zfuggs) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed7859057ed65e475c28b7925c9d71d230dfd8e8/geometry/proximity/test/make_convex_hull_mesh_test.cc#L341)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll have to come around to the unit test.
</blockquote></details>

Test added and revealed bug resolved. Thanks for flagging that.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-NssXQIm1YhYXDrhn2Gh:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 361 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-NssVbse1VCGzLPu-rcA:-NssVbsfDcbgBNQXHenC:b-oiknvz) ([raw file](https://github.com/RobotLocomotion/drake/blob/045cdc0ba9f7a997f08dcfe50ee0d6ebb7f999dd/geometry/proximity/test/make_convex_hull_mesh_test.cc#L361)):*
> ```cpp
>   const fs::path bin_src =
>       FindResourceOrThrow("drake/geometry/test/cube_with_hole.bin");
>   const fs::path bin_tgt = dir_path / bin_src.filename();
> ```

nit I could maybe live with `src` as a common abbreviation (via Bazel) that's not GSG C++ compliant, but `tgt` seems a GSG bridge too far.

Ideas:
* source, in, orig
* target, out, edit, dest

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-Nssb23B1-wRsDCD2RK7:-NssdLABC__mHwBojbq7:b-u9gfci) (no related file):*
> ... delinter leaves it untouched ...

Actually it crashes with `Exception: geometry/vtk_opengl_init.cc: changes were not just a shuffle`, telling you that it doesn't know how to fix it.

The two outputs shown in the crash differ by the indentation of the end-of-line comments.

If you run `clang-format` on the file, everything will be happy.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-Nssb23B1-wRsDCD2RK7:-Nssn0rj7DjrjSDRBgP7:b-7j33fn) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... delinter leaves it untouched ...

Actually it crashes with `Exception: geometry/vtk_opengl_init.cc: changes were not just a shuffle`, telling you that it doesn't know how to fix it.

The two outputs shown in the crash differ by the indentation of the end-of-line comments.

If you run `clang-format` on the file, everything will be happy.
</blockquote></details>

Dur.

I'm almost embarrassed to admit to my particular sin. Thanks.

___

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: w one nit

> Reviewed 8 of 13 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-:-Nst71gHAS62KNoYzFkw:by9ouy2)* status: 1 unresolved discussion

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 229 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-Nssxy9MCTXPsIiWl7Q_:-Nssxy9MCTXPsIiWl7Qa:b-6tqbs6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e1f330cbbb13c492b0b32a324523bf1fef06451/geometry/proximity/make_convex_hull_mesh.cc#L229)):*
> ```cpp
>           dynamic_cast<vtkPolyData*>(actor->GetMapper()->GetInput());
>       DRAKE_DEMAND(poly_data != nullptr);
>       // 2. For each vertex, transform it to the file frame (based on the actors
> ```

nit: actors -> actor's

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21131#-Nssb23B1-wRsDCD2RK7:-NstZqqj71eB9tU_JbTD:b-bedczn) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Dur.

I'm almost embarrassed to admit to my particular sin. Thanks.
</blockquote></details>

Ya.  Ideally the auto-fixer would handle this, but it's not quite smart enough.  Once we finally purge `enable_clang_format_lint = False` from Drake, it will be moot, I guess.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21131)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Pull request merged**
