### PR TITLE
[doc] Add Jammy stable releases

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review (or delegation) of release artifacts, please.

+@rpoyner-tri for feature review of release playbook and scripts -- and also platform review, please.

**Review by svenevs — COMMENTED** [review]
:lgtm: we will need to look into the private apt script and make sure it's ready to handle jammy before signed releases will be possible

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737#-:-N9hHzh07G8wQrRLs7UL:b-plmf6j)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/installation.md` line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hHERd71kEd9A5YAIr:-N9hHERd71kEd9A5YAIs:b-sru1hv) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_pages/installation.md#L51)):*
> ```Markdown
> 
> ⁽⁵⁾ Ubuntu 22.04 (Jammy Jellyfish) pre-built binaries are not yet available
> for pip nor apt.
> ```

Minor, it is available for `apt` just not the signed repository (they can have the `.deb`).  Maybe spell out `drake-apt.csail.mit.edu`?  
___
*[`doc/_release-notes/v1.6.0.md` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hHkO93FTR7bXh7Oj-:-N9hHkO93FTR7bXh7Oj0:b560s0f) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_release-notes/v1.6.0.md#L10)):*
> ```Markdown
> * Drake now supports Ubuntu 22.04 ("Jammy Jellyfish") for stable releases via
>   the tar.gz binaries and Docker Hub.
>   * We anticipate adding pip and apt support in a future release.
> ```

Minor, related to the above -- they can get unsigned `.deb` packages for apt currently.  But it's not clear the distinction is worth making, it'll probably just confuse people more than help.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/docker.md` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hIX3qEj5c3SuF2up7:-N9hIX3qEj5c3SuF2up8:b-z6pgds) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_pages/docker.md#L63)):*
> ```Markdown
> * ``jammy-YYYYMMDD`` for the Ubuntu 22.04 image of Drake as of date YYYY-MM-DD.
> * ``focal`` is a synonym for the most recent ``focal-YYYYMMDD``.
> * ``jammy`` is a synonym for the most recent ``jammy-YYYYMMDD``.
> ```

FYI the docker tags are there as described, it's worth mentioning that somebody with write access to https://hub.docker.com/r/robotlocomotion/drake should update the description to remove bionic / add jammy

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri and @svenevs)

___
*[`doc/_pages/docker.md` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hIX3qEj5c3SuF2up7:-N9hfrHC9vAqv3v4ssAg:bokfipu) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_pages/docker.md#L63)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI the docker tags are there as described, it's worth mentioning that somebody with write access to https://hub.docker.com/r/robotlocomotion/drake should update the description to remove bionic / add jammy
</blockquote></details>

OK Unless the keys are noted in the "CI setup" documentation somewhere, then I think we no longer have any access.  I certainly don't have any.
___
*[`doc/_pages/installation.md` line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hHERd71kEd9A5YAIr:-N9hIjPM2IlrXU6HRLJo:bornyl2) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_pages/installation.md#L51)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Minor, it is available for `apt` just not the signed repository (they can have the `.deb`).  Maybe spell out `drake-apt.csail.mit.edu`?  
</blockquote></details>

Done.  The `apt.html` page can explain the caveats.
___
*[`doc/_release-notes/v1.6.0.md` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hHkO93FTR7bXh7Oj-:-N9hgLQt-uS13G91AzHu:brkpsll) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_release-notes/v1.6.0.md#L10)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Minor, related to the above -- they can get unsigned `.deb` packages for apt currently.  But it's not clear the distinction is worth making, it'll probably just confuse people more than help.
</blockquote></details>

OK The unsigned debs have the wrong version number, though.  (There is no v1.6.0 deb.)

**Review by svenevs — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

___
*[`doc/_pages/docker.md` line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17737#-N9hIX3qEj5c3SuF2up7:-N9hqUQI6g_BEiE8DRVH:be6i8t6) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee2d4ac1641aa04689f90a72aa3d1266412b114/doc/_pages/docker.md#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Unless the keys are noted in the "CI setup" documentation somewhere, then I think we no longer have any access.  I certainly don't have any.
</blockquote></details>

Ah I see, OK we will try and track that down.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri please take a look.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review of release playbook and scripts' code -- and also platform review, please (-@rpoyner-tri).

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; one discussion item below (but not necessarily blocking)

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737#-:-NA53lvUBrJFeT7fL56f:b1qw3r4)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17737#-NA537uXDMaP56NSCsK3:-NA537uXDMaP56NSCsK4:b8bm7gr) ([raw file](https://github.com/robotlocomotion/drake/blob/e860f3c6c9d7195c3e97399e55d565b5405ee25a/doc/_release-notes/v1.6.0.md#L10)):*
> ```Markdown
> * Drake now supports Ubuntu 22.04 ("Jammy Jellyfish") for stable releases via
>   the tar.gz binaries and Docker Hub.
>   * We anticipate adding pip and apt support in a future release.
> ```

BTW:  I'm not sure that retroactively editing release notes is entirely fair or kind to our users; presumably whoever cares enough to read our release notes has already done so.  Are we planning more of an announcement than this?  Should this note go in the 1.7.0 notes instead/in addition?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17737)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.6.0.md` line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17737#-NA537uXDMaP56NSCsK3:-NA59uVO7redhKMexHTu:bdmyb06) ([raw file](https://github.com/robotlocomotion/drake/blob/e860f3c6c9d7195c3e97399e55d565b5405ee25a/doc/_release-notes/v1.6.0.md#L10)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  I'm not sure that retroactively editing release notes is entirely fair or kind to our users; presumably whoever cares enough to read our release notes has already done so.  Are we planning more of an announcement than this?  Should this note go in the 1.7.0 notes instead/in addition?
</blockquote></details>

Sure, I'll add the same announcement to 1.7.0.

**Pull request merged**
