### PR TITLE
Add clone method to MathematicalProgram

### PR DESCRIPTION
**Pull request by hongkai-dai**
In branch-and-bound, we need to clone the mathematical program in the parent node to its child nodes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7667)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
-(status: do not review) +@ericcousineau-tri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L1pLWQkNyTMju2PglU-:b-omwr12)*

**Comment by EricCousineau-TRI** [comment]
:strong_lgtm:, with some minor discussion points. Nice!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[solvers/mathematical_program.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLUsaM-7EWDP-gLZg:-L1sLUsbeuO56CIP25p4:brajfmq) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L296)):*
> ```objc
> 
>   /** Clone an optimization program.
>    * Constructed a new optimization program to be identical to the old program.
> ```

BTW grammar nit Should be `Clones an...` and `Constructs ....`.

---

*[solvers/mathematical_program.h, line 529 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLdJL2b8etULll8If:-L1sLdJL2b8etULll8Ig:b-u05w5l) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L529)):*
> ```objc
> 
>   /**
>    * Append some new variables to the end of the existing variables.
> ```

BTW grammar nit Should be `Appends`

---

*[solvers/mathematical_program.h, line 529 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLhZ0sgsxQvvPpzGR:-L1sLhZ0sgsxQvvPpzGS:b-dj2tf8) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L529)):*
> ```objc
> 
>   /**
>    * Append some new variables to the end of the existing variables.
> ```

BTW consistency Some comments are `/** Text...`, others are `/**\n * Text...`.
Could these be made consistent?

---

*[solvers/mathematical_program.h, line 531 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sM1CDAApFWet_tKC3:-L1sM1CDAApFWet_tKC4:b-o81yzs) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L531)):*
> ```objc
>    * Append some new variables to the end of the existing variables.
>    * @param variables The newly added variables.
>    * @pre variables should not intersect with the existing variables in the
> ```

BTW Should `` `variables` `` have backticks for `@pre`?

---

*[solvers/mathematical_program.h, line 533 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLq9Zun6tBllrYMjk:-L1sLq9Zun6tBllrYMjl:bvku1r4) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L533)):*
> ```objc
>    * @pre variables should not intersect with the existing variables in the
>    * optimization program.
>    * @pre each entry in `variables` should not be a dummy variable.
> ```

BTW grammar nit Capitalization, here and in other places.

---

*[solvers/mathematical_program.h, line 534 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLt6bDpAUHMqFpDDP:-L1sLt6bDpAUHMqFpDDQ:bi1hzbs) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L534)):*
> ```objc
>    * optimization program.
>    * @pre each entry in `variables` should not be a dummy variable.
>    * @throw runtime_error if the preconditions are not satisfied.
> ```

FYI I like this!
(Should it be added to other sites?)

---

*[solvers/mathematical_program.h, line 714 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sMHkVxSDTg9HZnOzh:-L1sMHkVxSDTg9HZnOzi:b-epvaz5) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L714)):*
> ```objc
>                                          const std::string& name = "X");
> 
>   /** Adds indeterminates to this MathematicalProgram.
> ```

BTW `to this MathematicalProgram` seems a tad redundant.

---

*[solvers/test/mathematical_program_test.cc, line 389 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sMRypz6rfb_6lt9LU:-L1sMRypz6rfb_6lt9LV:b-ooiczi) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/test/mathematical_program_test.cc#L389)):*
> ```cpp
> }
> 
> GTEST_TEST(testWithVariable, testWithVariable1) {
> ```

Is this spillover from #7666?

---

*[solvers/test/mathematical_program_test.cc, line 2569 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sMXN1kJ3KFZQemUlN:-L1sMXN1kJ3KFZQemUlO:b-z6rzx2) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/test/mathematical_program_test.cc#L2569)):*
> ```cpp
> 
> // Determine if two bindings are the same. Two bindings are the same if
> // 1. Their contain the same constraint pointer.
> ```

BTW grammar nit "They ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L1sMjKk8u-4jdA1y5xR:bibg997)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sNI3Jnef98SalXtRL:-L1sNI3K6jkr0FXXoJ_e:bn9k7im) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.cc#L186)):*
> ```cpp
> }
> 
> void MathematicalProgram::WithVariables(
> ```

Spillover from #7666?

---

*[solvers/mathematical_program.h, line 529 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLdJL2b8etULll8If:-L1sNKpZQAa7JMm04F_h:b-i58t8i) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L529)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW grammar nit Should be `Appends`
</blockquote></details>

Er, just realized all of these are from the spillover. Will port these over there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667)*

**Comment by EricCousineau-TRI** [comment]
:lgtm_strong: - oops!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L1sOHIx7-zIYNSsNAox:b-mohze0)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sNI3Jnef98SalXtRL:-L1xIpHJ7F1UWi6EEmk3:b7un1cd) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.cc#L186)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Spillover from #7666?
</blockquote></details>

Done. I rebased the branch.

---

*[solvers/mathematical_program.h, line 296 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sLUsaM-7EWDP-gLZg:-L1xI4spAGo-DehoPRCo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/mathematical_program.h#L296)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW grammar nit Should be `Clones an...` and `Constructs ....`.
</blockquote></details>

Done.

---

*[solvers/test/mathematical_program_test.cc, line 389 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sMRypz6rfb_6lt9LU:-L1xI5zBomhTQ4OgkGyD:b-rschni) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/test/mathematical_program_test.cc#L389)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is this spillover from #7666?
</blockquote></details>

Done. Yes, I just rebased the branch.

---

*[solvers/test/mathematical_program_test.cc, line 2569 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1sMXN1kJ3KFZQemUlN:-L1xIo9xGkephItI_Hl-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6df9f6b61933fa0c9329faae048738ae5c3e3553/solvers/test/mathematical_program_test.cc#L2569)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW grammar nit "They ..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667)*

**Comment by hongkai-dai** [comment]
+@seancurtis-tri for platform review please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L1y0KOoSxitUsWk--Zd:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a bunch of cosmetic issues.

Something to ponder, if you make solver interface cloneable, you can swap the `std::unique_ptr` with `copyable_unique_ptr` and use a private default copy constructor in your `Clone()` method. Then you wouldn't have to worry about enumerating members.

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1y7pZP9Ene-tdMcixL:-L1y7pZP9Ene-tdMcixM:b-9lkkov) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.cc#L137)):*
> ```cpp
>   auto new_prog = std::make_unique<MathematicalProgram>();
>   // Add variables and indeterminates
>   new_prog->AddDecisionVariables(decision_variables_);
> ```

BTW The nature of this method looks like you're marching through all the members and simply copying them. But there are some that aren't obviously included:
- solvers (uniquely instantiated in the constructor)
- index maps (`decision_variable_index_` and `indeterminate_index_`)
- Stray values (`x_values_`, `x_initial_guess_`)

It might be worth putting in a note indicating that those members that are not explicitly listed here *are* accounted for.

---

*[solvers/mathematical_program.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yBXTOdDlqtYxFArzd:-L1yBXTOdDlqtYxFArze:b-qt3tee) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.cc#L141)):*
> ```cpp
>   // Add costs
>   new_prog->generic_costs_ = generic_costs_;
>   new_prog->linear_costs_ = linear_costs_;
> ```

FYI The order of assigning these don't always follow the order they've been declared in the header file. It might be easier for later coders to do reality checks if the assignments follow the ordering of the declarations. (Also applies to subsequent assignments.)

---

*[solvers/mathematical_program.h, line 296 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yD2Pn_A6XFWHBPNex:-L1yD2Pn_A6XFWHBPNey:b-nuhkqt) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L296)):*
BTW 
1. I'm not sure I like the term "identical". Given all the caveats below of how they're different, perhaps it would be better to say "a new optimization program which is functionally equivalent to the old program." (Or some such thing.)
2. Typo: s/Constructes/Constructs. 

Alternatively:

> /** Clones an optimization program
  The clone will be functionally equivalent to the source program with the same:
    - decision variables
    - constraints
    - costs
    - solver settings
    - initial guess
However, the clones x values will be initialize to NaN, an all internal solvers will be freshly constructed.
*/

---

*[solvers/mathematical_program.h, line 297 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yCXLxn8koSARdyaBG:-L1yCXLxn8koSARdyaBH:b-26g94t) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L297)):*
> ```objc
>   /** Clones an optimization program.
>    * Constructes a new optimization program to be identical to the old program.
>    * These two programs will have the same decision variables, constraints and
> ```

FYI For those of us who like the oxford comma: "...variables, constraints, and costs."

---

*[solvers/mathematical_program.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yCg4wbqpphb5I1EJM:-L1yCg4wbqpphb5I1EJN:b9dnnw0) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L299)):*
> ```objc
>    * These two programs will have the same decision variables, constraints and
>    * costs.
>    * They will also have the same solver settings, initial guess, and x_values_.
> ```

Several issues:

1. `x_values_` is the private name. Wouldn't it be better to use a string here that represents the math concept and not the implementation? (e.g., "decision variables").
2. isn't `x_values_` set to NaN? So, does that make this a lie?

---

*[solvers/test/generic_trivial_constraints.h, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yGCcX-9HmEOvbd3SJ:-L1yGCcX-9HmEOvbd3SK:b-3l03z4) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/generic_trivial_constraints.h#L20)):*
> ```objc
> 
> // A generic constraint derived from Constraint class. This is meant for testing
> // adding a constraint to optimization program
> ```

BTW
1. Missing ending period.
2. Can you say something about the math of this constraint?

---

*[solvers/test/mathematical_program_test.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yGpR5ATvfU9VoekBK:-L1yGpR5ATvfU9VoekBL:b538bz1) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L28)):*
> ```cpp
> #include "drake/math/matrix_util.h"
> #include "drake/solvers/constraint.h"
> #include "drake/solvers/test/generic_trivial_constraints.h"
> ```

FYI I'm assuming that there is a plan for future trivial constraints? Otherwise, this file seems misnamed (plural for a file which defines a single constraint).

---

*[solvers/test/mathematical_program_test.cc, line 2578 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yHCDfmBFBg1zzXKUZ:-L1yHCDfmBFBg1zzXKU_:btwjehr) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L2578)):*
> ```cpp
> bool IsBindingEqual(const Binding<Constraint>& binding1,
>                     const Binding<Constraint>& binding2) {
>   if (binding1.constraint() != binding2.constraint()) {
> ```

BTW If you change this to return `::testing::AssertionResult` instead of a bool, you can pass messages about the failure making the debug info more valuable. (See `eigen_matrix_compare.h` for an example.

Same for `IsVectorOfBindingEqual`

---

*[solvers/test/mathematical_program_test.cc, line 2611 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yLKHOPRysIGdTUJrv:-L1yLKHOPRysIGdTUJrw:b4a2oei) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L2611)):*
> ```cpp
>   auto y = prog.NewIndeterminates<2>("y");
>   auto X = prog.NewSymmetricContinuousVariables<3>("X");
> ```

BTW You should probably assert that the `x_values_` are `NaN`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L1yLWrwRQ85HXkXM9-A:b-3idm7o)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L22XH7o0bLazNgyZFYd:b-s794vx)*

**Comment by hongkai-dai** [comment]
Thanks @seancurtis-tri for the careful review. I think we will change to `copyable_unique_ptr` in the future, and either make `MathematicalProgramSolverInterface` copyable, or add `Clone` method to `MathematicalProgramSolverInterface` as well. We will do this in a future PR.

---

Review status: 1 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1y7pZP9Ene-tdMcixL:-L22P_nTZEVpvpMazbdg:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.cc#L137)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The nature of this method looks like you're marching through all the members and simply copying them. But there are some that aren't obviously included:
- solvers (uniquely instantiated in the constructor)
- index maps (`decision_variable_index_` and `indeterminate_index_`)
- Stray values (`x_values_`, `x_initial_guess_`)

It might be worth putting in a note indicating that those members that are not explicitly listed here *are* accounted for.
</blockquote></details>

Done. Good call.

---

*[solvers/mathematical_program.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yBXTOdDlqtYxFArzd:-L22Q_AV0AUtE7UmZI-u:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI The order of assigning these don't always follow the order they've been declared in the header file. It might be easier for later coders to do reality checks if the assignments follow the ordering of the declarations. (Also applies to subsequent assignments.)
</blockquote></details>

Done. Good call.

---

*[solvers/mathematical_program.h, line 296 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yD2Pn_A6XFWHBPNex:-L22RAbozw1Ng_sbSAkx:b-sa3q00) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L296)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW 
1. I'm not sure I like the term "identical". Given all the caveats below of how they're different, perhaps it would be better to say "a new optimization program which is functionally equivalent to the old program." (Or some such thing.)
2. Typo: s/Constructes/Constructs. 

Alternatively:

> /** Clones an optimization program
  The clone will be functionally equivalent to the source program with the same:
    - decision variables
    - constraints
    - costs
    - solver settings
    - initial guess
However, the clones x values will be initialize to NaN, an all internal solvers will be freshly constructed.
*/
</blockquote></details>

Done. Thanks for the rewording!

---

*[solvers/mathematical_program.h, line 297 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yCXLxn8koSARdyaBG:-L22T116fE0o-0MwG5pc:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L297)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI For those of us who like the oxford comma: "...variables, constraints, and costs."
</blockquote></details>

Done. Thanks!

---

*[solvers/mathematical_program.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yCg4wbqpphb5I1EJM:-L22T9K4NiQUfFciUQmE:bdtmer) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/mathematical_program.h#L299)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Several issues:

1. `x_values_` is the private name. Wouldn't it be better to use a string here that represents the math concept and not the implementation? (e.g., "decision variables").
2. isn't `x_values_` set to NaN? So, does that make this a lie?
</blockquote></details>

Done. You are right, x_values_ should be a NaN, and you caught me lying.

---

*[solvers/test/generic_trivial_constraints.h, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yGCcX-9HmEOvbd3SJ:-L22Tb53Rro5xkt5ILe-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/generic_trivial_constraints.h#L20)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW
1. Missing ending period.
2. Can you say something about the math of this constraint?
</blockquote></details>

Done.

---

*[solvers/test/mathematical_program_test.cc, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yGpR5ATvfU9VoekBK:-L22UQ3ZiqyhL-u3mV0W:b-fy309q) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'm assuming that there is a plan for future trivial constraints? Otherwise, this file seems misnamed (plural for a file which defines a single constraint).
</blockquote></details>

In case we want to test `MakeConstraint` function with a different generic trivial constraint, as we had with `MakeCost` function. This file is copied from `generic_trivial_costs.h` https://github.com/RobotLocomotion/drake/blob/master/solvers/test/generic_trivial_costs.h

---

*[solvers/test/mathematical_program_test.cc, line 2578 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yHCDfmBFBg1zzXKUZ:-L22Y6HlPCZHqFcM2RZ-:b9m5bjr) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L2578)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If you change this to return `::testing::AssertionResult` instead of a bool, you can pass messages about the failure making the debug info more valuable. (See `eigen_matrix_compare.h` for an example.

Same for `IsVectorOfBindingEqual`
</blockquote></details>

Done. Thanks! I also moved these two functions to `mathematical_program_test_util.h`, as I will use them elsewhere in the future.

---

*[solvers/test/mathematical_program_test.cc, line 2611 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L1yLKHOPRysIGdTUJrv:-L22a64L4HYqgKVjkqfK:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2d8fd8c73a806738e33e08dee1b7801b186bfd/solvers/test/mathematical_program_test.cc#L2611)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You should probably assert that the `x_values_` are `NaN`.
</blockquote></details>

Done. Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L22acAmS2fnbVXvsM5E:bj4tiay)*

**Comment by SeanCurtis-TRI** [comment]
Just about there -- one recommendation and one typo correction.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 303 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L25zvD8P8z5isd62VcW:-L25zvD9e015EaIHkwUy:bmk4957) ([raw file](https://github.com/robotlocomotion/drake/blob/8428eb238cf7d4c166c94bcfddd75faa534f7034/solvers/mathematical_program.h#L303)):*
> ```objc
>    * - solver settings
>    * - initial guess
>    * However, the clones x values will be initialize to NaN, and all internal
> ```

BTW I need to be more careful when I make suggestions such that they be error free. Otherwise, the errors probably come back to me:

s/clones/clone's
s/initialize/initialized

---

*[solvers/test/mathematical_program_test_util.h, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L26-ii_SiQyOJAuDSlo:-L26-ii_SiQyOJAuDSlp:b-1qj1bf) ([raw file](https://github.com/robotlocomotion/drake/blob/8428eb238cf7d4c166c94bcfddd75faa534f7034/solvers/test/mathematical_program_test_util.h#L58)):*
> ```objc
>   }
>   for (int i = 0; i < static_cast<int>(bindings1.size()); ++i) {
>     if (!IsBindingEqual(bindings1[i], bindings2[i])) {
> ```

FYI Doing it this way means you lose all of the messages you encoded in `IsBindingEqual()`. I'd recommend:

```C++
auto result = IsBindingEqual(bindings1[i], bindings2[i]);
if (!result) return result;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L2603bcrs2KgEFaMBvD:b-6mbfum)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 303 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L25zvD8P8z5isd62VcW:-L26CoNeq1df1iwdVTap:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/8428eb238cf7d4c166c94bcfddd75faa534f7034/solvers/mathematical_program.h#L303)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I need to be more careful when I make suggestions such that they be error free. Otherwise, the errors probably come back to me:

s/clones/clone's
s/initialize/initialized
</blockquote></details>

Done. Good catch

---

*[solvers/test/mathematical_program_test_util.h, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-L26-ii_SiQyOJAuDSlo:-L26DVfzGTV6AB0w1_YR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8428eb238cf7d4c166c94bcfddd75faa534f7034/solvers/test/mathematical_program_test_util.h#L58)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Doing it this way means you lose all of the messages you encoded in `IsBindingEqual()`. I'd recommend:

```C++
auto result = IsBindingEqual(bindings1[i], bindings2[i]);
if (!result) return result;
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7667#-:-L26Qnyl7YCu3RRjPQRo:b-l70wzf)*

**Pull request merged**
