### PR TITLE
Provide drake/common/autodiff.h

### PR DESCRIPTION
**Pull request by soonho-tri**
Related #7015

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7199)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Suggested review order:
 - `drake/common/autodiff.h`
 - `drake/common/{eigen_autodiff_limits,eigen_autodiff_types,autodiff_overloads,autodiffxd}.h`.
 - The rest.

@jwnimmer-tri , could you feature-review this one?

---

Review status: 0 of 109 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-KvhkjKlBiMQi3BcAjgQ:b-vem00e)*

**Comment by soonho-tri** [comment]
BTW, I haven't touched `drake/math/{autodiff,autodiff_gradient}.h` in this PR. I think we need to first move them to `drake/common` directory to include them in `drake/common/autodiff.h`.

---

Review status: 0 of 109 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kvhlo67hECwA3Bw5m9J:b-dbp8oz)*

**Comment by jwnimmer-tri** [comment]
Oh, you mentioned me but didn't assign me, so it slipped off my radar.

**Comment by soonho-tri** [comment]
Not a problem. I asked +@ericcousineau-tri to feature-review this PR.

---

Review status: 0 of 109 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kw0danwCHCwnUtAMuUS:b-swkqhj)*

**Comment by jwnimmer-tri** [comment]
I'll do platform review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 109 of 109 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kw18OJgo_VoeHN8irr-:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 28 of 109 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_autodiff_types.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-Kw1MxaUbUJ4fi0TK2t6:-Kw1MxaUbUJ4fi0TK2t7:brmrypu) ([raw file](https://github.com/robotlocomotion/drake/blob/a67229b838d3b66323e9e5270d4dc909af36c22f/drake/common/eigen_autodiff_types.h#L1)):*
> ```objc
> #pragma once
> ```

FYI _Meta_ Why change files so that `#pragma once` is not the very first line?  As it serves like a preprocessor guard, it seems appropriate to keep it as the very first thing, always.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kw1NVzg22SQtnFHT5Z-:by96gdd)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 82 of 109 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kw1PJAMuiTFaY3-GcCZ:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 102 of 108 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_autodiff_types.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-Kw1MxaUbUJ4fi0TK2t6:-Kw1Pdn3J6x1kC0x70Eb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a67229b838d3b66323e9e5270d4dc909af36c22f/drake/common/eigen_autodiff_types.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ Why change files so that `#pragma once` is not the very first line?  As it serves like a preprocessor guard, it seems appropriate to keep it as the very first thing, always.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199)*

**Comment by soonho-tri** [comment]
Fixing CI failures...

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199#-:-Kw1SmQpZSNtQGNz5QXT:bl3yh15)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7199)*

**Pull request merged**
