### PR TITLE
Improve the speed of Polynomial::EvaluatePartial

### LINKED ISSUE #17700: Improve speed of symbolic::Polynomial::EvaluatePartial
Currently computing `symbolic::Polynomial::EvaluatePartial` is very slow. I have a mathematical program that takes 6 minutes to solve, but it takes 10 minutes to retrieve the solution when I use `symbolic::Polynomial::EvaluatePartial`. 

Here is an example illustrating the issue.
1. I construct the polynomial as `p(x) = m(x)ᵀ * S * m(x)`, where `m(x)` is a vector containing all my monomial basis, `S` is a matrix of decision variables.
2. I create a `symbolic::Environment` object that contains the value of `S`, set to `S_val`.
3. I call `p(x).EvaluatePartial(env)`. This takes 10 minutes.
4. I tried the alternative approach to compute `m(x)ᵀ * S_val * m(x)`, which gives me the same result as in step 3, but only takes 16 seconds.

I do expect step 3 to be slower than step 4, but I didn't expect that much slow.

I put my example in the branch https://github.com/hongkai-dai/drake/tree/benchmark_polynomial. You could see the comparison in `bazel run common/symbolic/benchmarking:benchmark_polynomial`.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #17700

Also add benchmark Polynomial::EvaluatePartial.

Before this change
```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BenchmarkPolynomialEvaluatePartial  731970787 ns    731922688 ns            1
-----------------------------------------------------------------------------
```
After this change
```
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BenchmarkPolynomialEvaluatePartial    2896414 ns      2896364 ns          246
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701#-:-N8kTKQY-uJe7rKzs9ai:b-m0iajo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 575 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17701#-N8njAp-57-pGp9aEhWj:-N8njAp-57-pGp9aEhWk:b-m7gclh) ([raw file](https://github.com/robotlocomotion/drake/blob/97d504f09248f5fa3fe893113926f7d0aacf2a76/common/symbolic/polynomial.cc#L575)):*
> ```cpp
>   for (const auto& product_i : monomial_to_coefficient_map_) {
>     const Expression& coeff_i{product_i.second};
>     const Expression coeff_i_partial_evaluated{coeff_i.Substitute(subst)};
> ```

The root cause of the slow-down appears to be that re-creating the temporary `Substitution` inside of the call to `EvaluatePartial` here was very expensive.

We've resolved that by converting to a `Substitution` once, outside of the loop, and then calling `Substitute` instead.

That fixes this particular benchmark case, but leaves `EvaluatePartial` potentially being a performance landmine for any other repeated call sites, such as in user code.

Another possibility for solving this would be to make `Expression::EvaluatePartial` be as fast in all cases, by removing its internal map-copy.

Here's a first cut at that approach, by adding a new function `ExpressionCell::EvaluatePartial(const Environment&)`:

https://github.com/jwnimmer-tri/drake/commits/evaluate-partial

Could you check if it achieves the same speed-up, without any changes to `polynomial.cc`?

If so, I think it will a better answer for the long term.
___
*[`tools/performance/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17701#-N8ni__I6-RtTQ_AgS7M:-N8ni__I6-RtTQ_AgS7N:brnet2k) ([raw file](https://github.com/robotlocomotion/drake/blob/97d504f09248f5fa3fe893113926f7d0aacf2a76/tools/performance/BUILD.bazel#L14)):*
> ```Starlark
> 
> package(default_visibility = [
>     # All benchmarks should be in folders named "benchmarking".
> ```

We've established a convention that all benchmarks live in a second-level directory, i.e., `drake/common/benchmarking/` not `drake/common/symbolic/benchmarking/`.  (I should have been more clear in the comment here.)

One option is to move the new benchmark into `drake/common/benchmarking/`.

It would also be OK by me to move it into `drake/solvers/benchmarking` since this kind of operation would typically be associated with mathematical programming, even though the benchmark only involves Polynomial and not any solvers-directory code.

**Comment by jwnimmer-tri** [comment]
*[`common/symbolic/benchmarking/benchmark_polynomial.cc` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17701#-N8nzYQ6A948bKZZVP1D:-N8nzYQ70ufbw7hMLlYr:b-eoqpn5) ([raw file](https://github.com/robotlocomotion/drake/blob/97d504f09248f5fa3fe893113926f7d0aacf2a76/common/symbolic/benchmarking/benchmark_polynomial.cc#L47)):*
> ```cpp
> }
> 
> BENCHMARK(BenchmarkPolynomialEvaluatePartial);
> ```

nit For the slower benchmarks, IMO reporting nanoseconds in the output is difficult to understand.  Consider adding `->Unit(benchmark::kMicrosecond)` here for readability.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/symbolic/polynomial.cc` line 575 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17701#-N8njAp-57-pGp9aEhWj:-N8tOt8b5Vdr36ZCb4A3:b-i5q7un) ([raw file](https://github.com/robotlocomotion/drake/blob/97d504f09248f5fa3fe893113926f7d0aacf2a76/common/symbolic/polynomial.cc#L575)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The root cause of the slow-down appears to be that re-creating the temporary `Substitution` inside of the call to `EvaluatePartial` here was very expensive.

We've resolved that by converting to a `Substitution` once, outside of the loop, and then calling `Substitute` instead.

That fixes this particular benchmark case, but leaves `EvaluatePartial` potentially being a performance landmine for any other repeated call sites, such as in user code.

Another possibility for solving this would be to make `Expression::EvaluatePartial` be as fast in all cases, by removing its internal map-copy.

Here's a first cut at that approach, by adding a new function `ExpressionCell::EvaluatePartial(const Environment&)`:

https://github.com/jwnimmer-tri/drake/commits/evaluate-partial

Could you check if it achieves the same speed-up, without any changes to `polynomial.cc`?

If so, I think it will a better answer for the long term.
</blockquote></details>

Thanks Jeremy. I benchmarked your branch using the same test, here is the benchmark result
```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BenchmarkPolynomialEvaluatePartial    5184352 ns      5183993 ns          115
```
It is also a significant improvement over the code in master, but about 2 times slower than the current code in this branch.

I rebased my benchmark on top of your code, and put it in the branch https://github.com/hongkai-dai/drake/tree/evaluate_partial

**Comment by jwnimmer-tri** [comment]
Could you split a PR just to add the benchmark first, with no fixes?

I would like to dig into why the Substitute is faster, but I won't have time this week.

My intuition is that we land the benchmark first, then my patch next.  And then try to diagnose why Substitute is faster, and fix EvaluatePartial to be equally fast.

**Review by hongkai-dai — COMMENTED** [review]
I filed a new PR #17714 that just contains the benchmark.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701#-:-N99e1AG2Rm5XSaSraOL:b6g8e02)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Merging this branch up to `upstream/master` and running locally as  `bazel run //common/benchmarking:polynomial_experiment -- --output_dir=... --sleep 1 --cputask=4 -- --benchmark_repetitions=30`, with this change I see 4778±68 us measured CPU time and with #17727 I see 4049±64 us measured CPU time.  So on my computer, there is no 2x slower for #17727 vs this approach.

Could you share how you took your measurements?  We you using `polynomial_experiment`?  If you were running `benchmark_polynomial` directly, you'd be subject to CPU turbo scaling, which makes measurements inaccurate below ~5x relative scale.

**Review by hongkai-dai — COMMENTED** [review]
I reran the benchmark using your command and I don't see the 2X slower. Actually this branch takes 5518 us and #17727 takes 4676 us. I will close this PR and we can review #17727 instead.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17701#-:-N9YCRQlEn5i7sWZ-5Vb:bn85mwq)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Pull request closed without merging**
