### PR TITLE
CollisionChecker accounts for non-floating bodies with floating joints

### LINKED ISSUE #21215: SceneGraphCollisionChecker throws when models have a QuaternionFloatingJoint (for a non-floating body)
### What happened?

This was originally reported in https://stackoverflow.com/questions/78208761/drake-faking-attachment-between-floating-objects-with-locking-joints-is-it-po .

I've made a c++ reproduction that can be dropped in to `scene_graph_collision_checker_test.cc`:
```
// Reproduction of issue from
// https://stackoverflow.com/questions/78208761/drake-faking-attachment-between-floating-objects-with-locking-joints-is-it-po
GTEST_TEST(SceneGraphCollisionCheckerTest, QuaternionFloatingJoint) {
  RobotDiagramBuilder<double> builder;
  const std::string model_directives = R"""(
directives:
- add_model:
    name: arm
    file: package://drake/manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
- add_weld:
    parent: world
    child: arm::base
- add_model:
    name: cracker
    file: package://drake_models/ycb/003_cracker_box.sdf
)""";
  builder.parser().AddModelsFromString(model_directives, "dmd.yaml");
  
  auto joint = std::make_unique<multibody::QuaternionFloatingJoint<double>>(
    "lockable_floating_joint",
    builder.plant().GetFrameByName("iiwa_link_ee"),
    builder.plant().GetFrameByName("base_link_cracker"));
  builder.plant().AddJoint(std::move(joint));

  const auto& plant = builder.plant();
  CollisionCheckerParams params;
  params.model = builder.Build();
  params.robot_model_instances.push_back(plant.GetModelInstanceByName("arm"));
  params.edge_step_size = 0.05;
  SceneGraphCollisionChecker dut(std::move(params));

  // As constructed, collision filters must be consistent.
  EXPECT_NO_THROW(EnforceCollisionFilterConsistency(dut));
}
```
(you'll also need to `#include "drake/multibody/tree/quaternion_floating_joint.h"` at the top)

The result is 
```
abort: Failure at bazel-out/k8-dbg/bin/multibody/tree/_virtual_includes/multibody_tree_core/drake/multibody/tree/rigid_body.h:322 in floating_positions_start(): condition 'is_floating()' failed.
```

Running it through the debugger, the offending code is [here](https://github.com/RobotLocomotion/drake/blob/e41e11f560650c3b9ba805d4587adb6c42dc7b8b/planning/linear_distance_and_interpolation_provider.cc#L32).

I'll assign to @SeanCurtis-TRI , since his comments are all over this.  cc @joemasterjohn (since it's related to quaternionfloatingjoint / floating joints) and @calderpg-tri (for collision checker).

### Version

master

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
abort: Failure at bazel-out/k8-dbg/bin/multibody/tree/_virtual_includes/multibody_tree_core/drake/multibody/tree/rigid_body.h:322 in floating_positions_start(): condition 'is_floating()' failed.
```
```

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Fixes #21215

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21315)

### CODE REVIEW

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21315)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`planning/linear_distance_and_interpolation_provider.cc` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21315#-NvcJjzu2KSKwbMLFisy:-NvcJjzu2KSKwbMLFisz:b2ceewd) ([raw file](https://github.com/RobotLocomotion/drake/blob/7fb8603292b0251d4cf485b5474c1f7c86894c12/planning/linear_distance_and_interpolation_provider.cc#L27)):*
> ```cpp
>     const RigidBody<double>& body = plant.get_body(body_index);
>     // We only grab the quaternions for floating bodies .
>     if (body.is_floating() && body.has_quaternion_dofs()) {
> ```

This doesn't make sense to me. If you have a body with quaternion DoF that is not floating, this now guarantees that the interpolation and distance will be wrong.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21315)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`planning/linear_distance_and_interpolation_provider.cc` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21315#-NvcJjzu2KSKwbMLFisy:-NvcKBsz-4SGhwEoj3rk:bqog80t) ([raw file](https://github.com/RobotLocomotion/drake/blob/7fb8603292b0251d4cf485b5474c1f7c86894c12/planning/linear_distance_and_interpolation_provider.cc#L27)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

This doesn't make sense to me. If you have a body with quaternion DoF that is not floating, this now guarantees that the interpolation and distance will be wrong.
</blockquote></details>

Agreed

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21315)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`planning/linear_distance_and_interpolation_provider.cc` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21315#-NvcJjzu2KSKwbMLFisy:-NvcN5XZByoyHtm-MxKh:b-bprz8r) ([raw file](https://github.com/RobotLocomotion/drake/blob/7fb8603292b0251d4cf485b5474c1f7c86894c12/planning/linear_distance_and_interpolation_provider.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Oops. I pushed it the wrong direction. The goal wasn't to be more exclusive, it was to be more inclusive. My bad.

And the `RigidBody` api doesn't have an API for `positions_start()`.

But, in the meantime, you can steal the test and call it good.

**Comment by SeanCurtis-TRI** [comment]
This has served its purpose. I'm closing it.

**Pull request closed without merging**
