### PR TITLE
workspace: Bump pybind11 fork to latest commit

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Incorporates https://github.com/RobotLocomotion/pybind11/pull/52

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIgvzJ1l_nBo6yaisa:-MVIgvzKEp55jlH9xW1Y:bbh3bsx) (no related file):*
Working: Testing Mac via macsim.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIgvzJ1l_nBo6yaisa:-MVIj-fP455YDR62gDsB:b-sd3at6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing Mac via macsim.
</blockquote></details>

OK `//bindings/pydrake/...` all passed fine.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please (as part of platform review)
Feel free to punt to tomorrow too

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751#-:-MVIx3HdBiUbpOnSk81A:b-kwx1d)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIzFDC2dtB6z3yD8up:-MVIzFDC2dtB6z3yD8uq:b-up1ka2) (no related file):*
Need a mac build on this.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIzFDC2dtB6z3yD8up:-MVJ-Hc4-tx6WQvSDDt5:b-w8k3cj) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Need a mac build on this.
</blockquote></details>

FWIW I had tested on macsim (more expedient). Will do `bazel test //...` on macsim on latest commit (898911e)

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIzFDC2dtB6z3yD8up:-MVJ5eSG1EsE9S_rwOrW:b56ehvw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW I had tested on macsim (more expedient). Will do `bazel test //...` on macsim on latest commit (898911e)
</blockquote></details>

If I can "punt to tomorrow", it seems that time is not of the essence. Why not dispatch an official CI build and have that on the record?

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
For soothe!
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14751#-MVIzFDC2dtB6z3yD8up:-MVJL00J7Cd-gqFVg5TA:bkgsu5g) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

If I can "punt to tomorrow", it seems that time is not of the essence. Why not dispatch an official CI build and have that on the record?
</blockquote></details>

Aye: https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-catalina-clang-bazel-experimental-release/134/

Will mark this as resolved if/when CI passes.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14751#-:-MVNNj3x3qZIpiCFercn:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
