### PR TITLE
Add more direct test coverage of lcm_vector_gen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5354)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Here goes nothing...
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/tools/BUILD, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeATGxBqbpMffs8CMIy:-KeATGxCmFN6iV76KDGg:b-7db7h1) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

btw file meta: buildifier.sh whinged about some spare white space in this file. it's not from your patch, so fix or don't as you see fit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeATU6qW7-GCIMUd-9M:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri +@sammy-tri for platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeAX4I3_H2f2SGqO2gz:bixzo5q)*

**Comment by jwnimmer-tri** [comment]
Need to adjust OSX CI before merging.

**Comment by jwnimmer-tri** [comment]
@sammy-tri if you are overwhelmed with overflow reviews, we can kick the third review over to ggould-tri if you like.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeEJrf8BFshcyXVytZK:bmi0ssj)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
Reviewed 13 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeEmH7DO8FH0n7tbJrQ:-KeEmH7DO8FH0n7tbJrR:bu5kk3c) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L6)):*
> ```Shell
> set -ex
> 
> mkdir tmp
> ```

BTW, no need to use `mktemp` thanks to bazel-sandboxing?

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeEnTsMKCzWGPTq7U_T:-KeEnTsMKCzWGPTq7U_U:bguwglc) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L33)):*
> ```Shell
>     sed -i -e 's|include "tmp|include "drake/tools/test/gen|' tmp/"$item"
>     # The files should be identical now.
>     diff -u20 drake/tools/test/gen/"$item" tmp/"$item"
> ```

Do we want to detect the case when `diff -u20 ...` returns non-zero?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeEmH7DO8FH0n7tbJrQ:-KeEwDXUEc5uC9tyfITD:b-6kcums) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, no need to use `mktemp` thanks to bazel-sandboxing?
</blockquote></details>

I think that's true, yes.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeEnTsMKCzWGPTq7U_T:-KeEw58xcOkZiMdnkOHJ:bviuznd) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L33)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Do we want to detect the case when `diff -u20 ...` returns non-zero?
</blockquote></details>

That's what `set -e` does; _any_ command in this script that fails will bomb out the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeEnTsMKCzWGPTq7U_T:-KeExUjWi104XYBil-gP:b-4hvi0z) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That's what `set -e` does; _any_ command in this script that fails will bomb out the script.
</blockquote></details>

Got it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeExYjajUXpU35gvEj0:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-@sammy-tri +@ggould-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeEyv4LwVK02z4OCUeq:b3fsshu)*

**Comment by ggould-tri** [comment]
This is currently "do not merge" tagged.  Is that correct, and do you want me to review it anyway?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeEzWQPuEtWSYxC2jcG:bi84mb7)*

**Comment by jwnimmer-tri** [comment]
Yes, please review.  I want to wait for the OSX builder to finish before merging.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeEzn4xxHpr93r3Kbhs:bf6h5ci)*

**Comment by ggould-tri** [comment]
Pretty sure that once you've requested a build the button won't go green until it passes?  Anyway, will start review later this afternoon once I'm dug out of my current math-fest.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeF-T3DprtXPVWLEkMS:b-n2wrde)*

**Comment by jwnimmer-tri** [comment]
When a builder is not finished yet, the UI shows the outstanding build, but the merge button is still armed.  Also, new pushes to the branch kill the builder, so it's also a reminder to _me_ that I want to see OSX pass even if I push updates.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeF-s6HPi9GEB_VYvog:b2okgod)*

**Comment by ggould-tri** [comment]
Various nits below, mostly discretionary. :lgtm: pending open items.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFEqQwBkSZr7OJJrBZ:-KeFEqQwBkSZr7OJJrB_:b-gvsmpc) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L6)):*
> ```Shell
> set -ex
> 
> mkdir tmp
> ```

BTW -- You create `tmp` in a way that will error if it exists, but you never clean it up.  Is that a bazel best-practice due to sandboxing?

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFFYm31huovjVkKO6l:-KeFFYm31huovjVkKO6m:bt1yb94) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L29)):*
> ```Shell
> 
> # Insist that the generated output matches the current copy in git.
> for item in lcmt_sample_t.lcm sample.cc sample.h sample_translator.cc sample_translator.h; do
> ```

FYI -- long line.  We don't have any bash conventions to say that's wrong, so author's discretion.

---

*[drake/tools/test/gen/_regenerate.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFHOCwmXF_6mEMOp7s:-KeFHOCx3ftCT77ioofy:bitjv9t) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/_regenerate.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

BTW -- Is the leading underscore a documented convention?  I don't believe I've seen it before and I don't see it elsewhere in the tree.

---

*[drake/tools/test/gen/_regenerate.sh, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFHyQDBGThIiBr0sOW:-KeFHyQENsrGcNg3BmCF:b-267g1i) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/_regenerate.sh#L9)):*
> ```Shell
> set -e
> 
> mydir=$(python -c \
> ```

It is surprising that `mydir` names not the directory of the running script or the cwd but the parent directory of this script.  Would `testdir` or `parentdir` be clearer?

---

*[drake/tools/test/gen/sample.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFKcI5RzMMM1YKbTIB:-KeFKcI5RzMMM1YKbTIC:b-hxs6k9) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/sample.h#L31)):*
> ```objc
> class Sample : public systems::BasicVector<T> {
>  public:
>   // An abbreviation for our row index constants.
> ```

FYI The doxygen would be slightly clearer if you made this a doxygen comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeFSQJMiqMHNO0ecckH:b818wwe)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFEqQwBkSZr7OJJrBZ:-KeFUQ9rZWlS8v26WXK0:b-1cjnnc) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L6)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- You create `tmp` in a way that will error if it exists, but you never clean it up.  Is that a bazel best-practice due to sandboxing?
</blockquote></details>

Assuming a clean slate is a sandbox thing, and yes probably a best practice (though we've not discussed it I guess).

I guess I don't have strong thoughts on whether cleaning up when done is appropriate or not.  I guess my assumption is that the disk claim is low enough that I'm happy to let the sandbox own the cleanup at some future unspecified time?

---

*[drake/tools/test/gen/_regenerate.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFHOCwmXF_6mEMOp7s:-KeFUCg6gqrEbYeeJECO:blywo3y) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/_regenerate.sh#L2)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Is the leading underscore a documented convention?  I don't believe I've seen it before and I don't see it elsewhere in the tree.
</blockquote></details>

It's a new idea.  I was trying to find a way to put the regeneration script directly adjacent to the generated files, but still to have it `ls` alpha-sort separately from them for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/tools/test/lcm_vector_gen_test.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFEqQwBkSZr7OJJrBZ:-KeFWisct84t7ffvaX7R:b-vc5lko) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/lcm_vector_gen_test.sh#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Assuming a clean slate is a sandbox thing, and yes probably a best practice (though we've not discussed it I guess).

I guess I don't have strong thoughts on whether cleaning up when done is appropriate or not.  I guess my assumption is that the disk claim is low enough that I'm happy to let the sandbox own the cleanup at some future unspecified time?
</blockquote></details>

Fine by me; I am still learning bazel convetions :-)

If disk is plentiful, it is probably best *not* to clean up, in order to leave debuggable state if the script blows up.

---

*[drake/tools/test/gen/_regenerate.sh, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFHOCwmXF_6mEMOp7s:-KeFX0DWU5OsWqTryVG6:b-ummnv6) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/_regenerate.sh#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's a new idea.  I was trying to find a way to put the regeneration script directly adjacent to the generated files, but still to have it `ls` alpha-sort separately from them for clarity.
</blockquote></details>

Clever!  If you do it twice more it will be a best practice :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/test/gen/_regenerate.sh, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFHyQDBGThIiBr0sOW:-KeFbKnKQdJUWiyzvbPG:blcgmca) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/_regenerate.sh#L9)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It is surprising that `mydir` names not the directory of the running script or the cwd but the parent directory of this script.  Would `testdir` or `parentdir` be clearer?
</blockquote></details>

Done (TODO).

---

*[drake/tools/test/gen/sample.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFKcI5RzMMM1YKbTIB:-KeFbiCAq3oUTxCqzKW_:blcgmca) ([raw file](https://github.com/robotlocomotion/drake/blob/4bd281f9ab5e9071fa7dc3cb9d5bd772c623f1a0/drake/tools/test/gen/sample.h#L31)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI The doxygen would be slightly clearer if you made this a doxygen comment.
</blockquote></details>

Done (TODO).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/test/gen/_regenerate.sh, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFf_wXjGRmAx8QVTSa:-KeFf_wY2HvmT84Vgmca:br701p1) ([raw file](https://github.com/robotlocomotion/drake/blob/170dcb03bffa8bd81c243319e048731479ab797d/drake/tools/test/gen/_regenerate.sh#L7)):*
> ```Shell
> # This program's changes to the generated source files should be committed.
> 
> # Our weird filename (leaing underscore) is to help disambuguate (i.e., sort)
> ```

FYI typos "leaing" "disambuguate" (although disambuguate _should_ be a word!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge) OS X is all set -- the new test passed on the prior run, and the most recent push was a comments-only-change.

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/test/gen/_regenerate.sh, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-KeFf_wXjGRmAx8QVTSa:-KeG0SP-ssLbUYSrYmSw:b-68oo51) ([raw file](https://github.com/robotlocomotion/drake/blob/170dcb03bffa8bd81c243319e048731479ab797d/drake/tools/test/gen/_regenerate.sh#L7)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typos "leaing" "disambuguate" (although disambuguate _should_ be a word!)
</blockquote></details>

Done.

(Darn it; I have spell checking turned on for C++ but not Bash.  I guess I'll fix that now, too.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5354#-:-KeG0iRFldus5zrCeAaH:b-peihps)*

**Comment by jwnimmer-tri** [comment]
:lgtm: automotive

**Pull request merged**
