### PR TITLE
Introduce shadow maps in RenderEngineVtk

### LINKED ISSUE #20486: RenderEngineVtk needs to render shadows
Shadows provide invaluable clues to the spatial relationship of objects. If we hope to create synthetic data for training, shadows increase the fidelity of our images and increase their verisimilitude. VTK generally supports casting shadows but `RenderEngineVtk` doesn't yet implement them.

An example of this can be found in [this VTK example](https://examples.vtk.org/site/Cxx/Rendering/Shadows/).

Essentially, it requires changing the rendering pipeline to include "passes" for computing the shadow depth maps and to apply them.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Meta note: this entailed efforts in three types of changes:

  - Designed changes to Drake
  - Bug fixes for VTK
  - Regrettable hack around VTK to accommodate for bugs that could not otherwise be resolved yet.

Designed changes for Drake:
 - RenderEngineVtkParams has three new properties: exposure, cast_shadow, and shadow_map_size.
 - RenderEngineVtk
   - Replace the hard-coded VTK OpenGL render pipeline with a custom sequence of render passes.
       - Note: tests on the engine show that the hard-coded pipeline has correctly been reproduced given the default engine parameters.
   - The new pipeline includes shadow maps and tone mapping.
   - Incidentally, modernize the technique for initializing VTK's OpenGL infrastructure.
   - Testing has been updated to exercise the new parameters and confirm effect.
     - It also expanded the single-image tests to include transparent objects.
     - The reference images have all changed:
       - the rows have moved to better accommodate additional geometry
       - added new geometry to test of transparent objects
       - shadows enabled
       - adding the "ground" last changed label assignment

VTK bug fixes
  The details are in the .patch files. But we correct camera copying and various details of the shadow map shader implementations.

VTK hacks
  There is a known bug in VTK where shadow maps on a render window that isn't square, gets incorrectly mapped to the world. The cause is still unknown. So, when enabling shadows, we render to a square window and then extract the original image dimensions. 

(Depends on #20930.)

Resolves #20486

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
The reference images changed as follows (old image on left, new image on right).

In all cases, the rows of shapes have been brought closer together and three slabs have been added to exercise transparent objects (and their relationship to shadows). Any changes attributable to any other property are noted below.


[Default color]


[Custom color: directional light re-oriented (for shadow instead of rim light), shadows added, tone mapping with reduced exposure added

Because the ground is now added *last* instead of in the middle, label values have been distributed differently for both default and custom parameters.


[Default label]


[Custom label]


[Default depth]


[Custom depth]

**Comment by SeanCurtis-TRI** [comment]
+(release notes: feature)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed (so far).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nqh_F2D3nC8QIsyH2JC:b-ovw6pg)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqiFDbj39tyoI_Gj_p-:-NqiMThG3mwqZ_jX47VP:b-umd4r2) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/geometry/render_vtk/render_engine_vtk_params.h#L132)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Should this be an advanced param and/or should we suggest a range of values to use? With the great documentation, I think I understand what it does, but I still have no idea how to set it if I want to balance between the env map vs. lights.
</blockquote></details>

My intention for providing the link and pointing out that this value was *that* value was to avoid redocumenting it. However, when I look at the website, I note that the word "exposure" doesn't appear anywhere.  :) 

So, I've made an extra effort to provide guidance.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 134 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqiDk9F26CTbvcNmG4u:-NqiMqM110zdciBUrW-Q:b9ga0od) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/geometry/render_vtk/render_engine_vtk_params.h#L134)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Is this an unfinished sentence?
</blockquote></details>

Done

Technically, it's valid English. And spoken (with proper emphasis) the meaning comes across clearly. However, it fails as written text.  :)
___
*[`tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqhyfGz-wDdXmvuAgEQ:-NqiNtZ119Bk78FxUbHG:bzadv0n) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch#L9)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. (Very trivial.) I thought from the context, it should be a comma, not a period.
</blockquote></details>

How about a colon?
___
*[`tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nqi7OCW1_cMq4t9IfWA:-NqiNeoh3MBg2564Up8g:bcnnnux) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch#L109)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. I might not fully understand the patch file syntax. Does this mean an empty `{}` that does nothing?
</blockquote></details>

Good eye! That was a relic that snuck through. It's one of the unfortunate challenges of writing glsl through a streaming output. Fortunately, you were willing to pay the personal price to actually read it.
___
*[`tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch` line 110 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nqi7bku5-dyEfue7n9Y:-NqiNI-NAid3VADAjmp_:b-f8uixc) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch#L110)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. The command says `don't change radiance`, but we are still changing that via ` radiance *= attenuation;\n`?
</blockquote></details>

It doesn't say don't change radiance. It says don't change *this definition* of radiance. I.e., it has now been defined, don't mess with the definition.
___
*[`tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch` line 193 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqiAWWvDpJu8T9QPKyu:-NqiN7kl-jvEe4aVBSNM:b53lnqg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch#L193)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit.
</blockquote></details>

Done

Another case of otherwise valid English not being up to the task in this context. :)

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: feature.

The documentation is :thumbsup:. I still need to wrap my head around `void ExtractImage(...)`, but I will send this to platform review given the tests are happy. 

> Reviewed 2 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nqiln9M1VaLITSijuMK:bx3hu9h)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqiFDbj39tyoI_Gj_p-:-Nqil6KC1AL209u8LEc0:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/geometry/render_vtk/render_engine_vtk_params.h#L132)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

My intention for providing the link and pointing out that this value was *that* value was to avoid redocumenting it. However, when I look at the website, I note that the word "exposure" doesn't appear anywhere.  :) 

So, I've made an extra effort to provide guidance.
</blockquote></details>

Thanks!
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 134 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqiDk9F26CTbvcNmG4u:-Nqil8bNB0rbKpUJo47E:b8p4hmn) ([raw file](https://github.com/RobotLocomotion/drake/blob/e99001201c8940ad698f1e8558d7b380aa5e053e/geometry/render_vtk/render_engine_vtk_params.h#L134)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

Technically, it's valid English. And spoken (with proper emphasis) the meaning comes across clearly. However, it fails as written text.  :)
</blockquote></details>

Now I know what you meant :thinking:.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sammy-tri for platform if you have the time today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-NqinRC27TNN7K7edwz6:b-4jx4w8)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
I'm not going to have time today, but I should be able to get to it before Monday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-NqitDDHAbo4SbLlF7yc:b-vvs7nq)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
That'd be great, thanks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-NqiuD4_8W_Lxh36zSc-:b-i9b36e)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 347 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqnRoTP75BszeQvneCm:-NqnRoTP75BszeQvneCn:b1gj1v8) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db396911a59a3e57673b7879f6ca05fc07fac9b/geometry/render_vtk/internal_render_engine_vtk.cc#L347)):*
> ```cpp
>       {core.renderer_name(),
>        {size, size, intrinsics.focal_x(), intrinsics.focal_y(),
>         intrinsics.center_x(), intrinsics.center_y() + y_offset},
> ```

BTW.

I thought by offsetting the `center_y`, we are pushing the image we care about down.

For a (W, H = 100, 200) image, we create a 200 x 200 image, while the part we want is on the left, and the right half is the padding.
For a (W, H = 200, 100) image, aren't we pushing the part we want down to the lower half due to the `y_offset`?



_Code quote:_
```cpp
intrinsics.center_y() + y_offset
```
___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 374 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqnTBb8EDtpB6qVfph5:-NqnTBb8EDtpB6qVfph6:b-c4dvl2) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db396911a59a3e57673b7879f6ca05fc07fac9b/geometry/render_vtk/internal_render_engine_vtk.cc#L374)):*
> ```cpp
>   const int out_row_bytes =
>       color_image_out->width() * color_image_out->kPixelSize;
>   // We flip the image vertically; row 0 in VTK is row H - 1 in the image.
> ```

BTW. To me, the `memcpy` operations make sense, but where do we flip the image vertically? I think I am missing something obvious :thinking: 



_Code quote:_
```cpp
We flip the image vertically;
```

**Review by sammy-tri — COMMENTED** [review]
This PR was a a bit of a tour de force (and that's a compliment!).  I don't have any changes to request, just holding off on the final approval until the last open discussions are resolved.

> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-NqxKCvLDJTGzY14J8rD:b-wfz69v)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 347 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqnRoTP75BszeQvneCm:-NqxTVUz7b_xtEsLehOH:bykmcge) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db396911a59a3e57673b7879f6ca05fc07fac9b/geometry/render_vtk/internal_render_engine_vtk.cc#L347)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Up and down can be confusing; they depend on how you interpret the rows. (Is zero at the top of the image or the bottom?) What we can *definitively* state is that offsetting the camera in a positive direction, we're pushing the image in the negative direction (which, in this case, means towards zero). (E.g., if I offset the camera right, the image goes left.)

All that really matters is that the offset applied *here* is correlated with where I start looking for rows in `ExtractImage()`.
</blockquote></details>

Thanks! That's clear to me now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Looks like we're resolved.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nr0Xyq70PL0FQci8Crb:b-q621sm)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Nevermind....I misused reviewable and stated that prematurely. Stay tuned....

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nr0a2oz4G5DLaNRch2w:ba8kkmg)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 344 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqnWjR4E7iRnqa8bKhz:-Nr1BOET1RN4YXlg2N-Z:b-tte92l) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db396911a59a3e57673b7879f6ca05fc07fac9b/geometry/render_vtk/internal_render_engine_vtk.cc#L344)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking issue:

Obviously this works in the unit tests -- a render camera with a horizontal aspect ratio is being correctly rendered. But it seems we should likewise be testing a vertical aspect ratio.

I probably need to add such a test.
</blockquote></details>

I did the test this morning and it isn't working as expected. Somehow, I'm either getting a *wider* image (likely) or the camera's position isn't preserved (unlikely). I'll need to do a bit more analysis before I can definitively state what's going on here.

It'll have to wait because I have platform reviewer duties.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've added the last test. The good news is that it shows that the code does the right thing whether the image has vertical or horizontal aspect ratio.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nr23vZm7Jj5Z1itiNnt:b-idq9fb)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 344 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-NqnWjR4E7iRnqa8bKhz:-Nr23qcoED3YZj9y0IFt:bm9eqnu) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db396911a59a3e57673b7879f6ca05fc07fac9b/geometry/render_vtk/internal_render_engine_vtk.cc#L344)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I did the test this morning and it isn't working as expected. Somehow, I'm either getting a *wider* image (likely) or the camera's position isn't preserved (unlikely). I'll need to do a bit more analysis before I can definitively state what's going on here.

It'll have to wait because I have platform reviewer duties.
</blockquote></details>

I'd originally written a bad test. The correct test does what it should.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (one comment nit)

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-:-Nr2QIcSAxqmYJH_vLME:b-mo6dgc)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2523 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nr2OjDMEnR_Jfl2C8-f:-Nr2OjDMEnR_Jfl2C8-g:b-amg7b3) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a7e1ea7efa483b403d30bb974ce3131bb31a5a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2523)):*
> ```cpp
>   // explicitly called out.
> 
>   // These engine parameters must match those in WholeImageCustomParams for the
> ```

nit: this sentence appears to be truncated after the word "the"

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2523 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nr2OjDMEnR_Jfl2C8-f:-Nr2SsX28Mtoo0OAtyUl:bqhp83e) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a7e1ea7efa483b403d30bb974ce3131bb31a5a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2523)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: this sentence appears to be truncated after the word "the"
</blockquote></details>

Done. The solution is *more* truncation!

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2519 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nr2SzdC2sbyiYsteSyf:-Nr2SzdC2sbyiYsteSyg:b-w6schh) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a7e1ea7efa483b403d30bb974ce3131bb31a5a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2519)):*
> ```cpp
> // When we no longer require the render-to-square-window hack, we can nuke this
> // test.
> TEST_F(RenderEngineVtkTest, WholeImageVerticalAspectRatio) {
> ```

BTW. A high-level question. I thought the same test as `WholeImageCustomParams` with a swapping h and w, i.e., {h=480, w=360}, would test the verticle aspect ratio case. Is there anything in `WholeImageVerticalAspectRatio` that exercises more test coverage than that?



_Code quote:_
```cpp
TEST_F(RenderEngineVtkTest, WholeImageVerticalAspectRatio) {
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2519 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nr2SzdC2sbyiYsteSyf:-Nr2VChnC7oUfOxRJUvs:bpgqq7b) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a7e1ea7efa483b403d30bb974ce3131bb31a5a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2519)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. A high-level question. I thought the same test as `WholeImageCustomParams` with a swapping h and w, i.e., {h=480, w=360}, would test the verticle aspect ratio case. Is there anything in `WholeImageVerticalAspectRatio` that exercises more test coverage than that?
</blockquote></details>

Simply swapping width and height *could* serve as a test of the correctness. However, I would have no reference image to compare with. By locking the image width and expanding the image height, I can crop that result down to a reference image I *do* have.

So, this was about limiting dumping binary data into git at the cost of rendering a bigger image.

That said, there is another way to articulate this test, in theory. If I reposed everything such that the universe was effectively rotated 90 degrees around the world's y-axis (objects, cameras, and environment map) and rendered to the vertical image, the resulting image should just be a rotation of the reference image. But, I suspect that infrastructure for rotating would be a bigger nuisance than that. Plus, we don't currently have a way through public APIs to re-orient the environment map -- it is currently hard-coded to be Wz up.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20944)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 2519 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20944#-Nr2SzdC2sbyiYsteSyf:-Nr2WfZG79oGLab4479-:b-kg50z4) ([raw file](https://github.com/RobotLocomotion/drake/blob/37a7e1ea7efa483b403d30bb974ce3131bb31a5a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L2519)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Simply swapping width and height *could* serve as a test of the correctness. However, I would have no reference image to compare with. By locking the image width and expanding the image height, I can crop that result down to a reference image I *do* have.

So, this was about limiting dumping binary data into git at the cost of rendering a bigger image.

That said, there is another way to articulate this test, in theory. If I reposed everything such that the universe was effectively rotated 90 degrees around the world's y-axis (objects, cameras, and environment map) and rendered to the vertical image, the resulting image should just be a rotation of the reference image. But, I suspect that infrastructure for rotating would be a bigger nuisance than that. Plus, we don't currently have a way through public APIs to re-orient the environment map -- it is currently hard-coded to be Wz up.
</blockquote></details>

Aha, because of the reference image!

**Comment by SeanCurtis-TRI** [comment]
+(status: squashing now)

**Pull request merged**
